### ISSUE TITLE
Detail editor not sortable

### ISSUE THREAD

**Issue by pmgmarques** [volkanceylan/Serenity#1001]
Hi!

When using a MasterDetail relation, the detail editor is not sortable.
How to fix this?

Thanks!

**Comment by volkanceylan** [comment]
You can't out of the box. Use tab grid if you need such functionality.

**Comment by Pinellus** [comment]
Hi Volkan,
Is there a way to solve this problem ?

I have to look at the reference to SlickGrid ?

**Comment by volkanceylan** [comment]
No, yes

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/issues/3792
