### ISSUE TITLE
Text boxes missing after publishing to IIS

### ISSUE THREAD

**Issue by thesnide1** [volkanceylan/Serenity#1002]
Hi,

Serenity runs fine locally and when published to Azure. After struggling to get the site to run on Windows 2008 R2 Standard server on my intranet the login the page displays without the username and password text boxes. I know this is not a problem with Serenity but after spending hours searching for a solution I need to ask for help. 

Thank you.

Locally
![serenity rinning local](https://cloud.githubusercontent.com/assets/17152660/17355447/b0f03ca4-591e-11e6-88fe-77a134956835.PNG)

IIS 7
![serenity rinning published](https://cloud.githubusercontent.com/assets/17152660/17355453/bc002384-591e-11e6-8e55-036b6f21935f.PNG)

**Comment by volkanceylan** [comment]
Check file permissions, IIS_IUSRS, plus see browser console, and run it in integrated mode not classic

**Comment by thesnide1** [comment]
Integrated mode fixed it.  

Thank you.
