### ISSUE TITLE
[Please Comment] References for New Serenity Web Site

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1006]
Hello All,

I'm currently preparing a web site for Serenity. I want to add a references section with information and links about "who uses Serenity".

If you / your company would like to be listed in this section, please post here with information below:

- User / Company Name
- Product Name
- Company / Product Logo if any
- Company / Product Site URL if any
- A short description of what product does
- At least one screenshot from your application, with details blurred for security purposes if required.
- A link to your application if possible. I understand Serenity apps are usually administrative so this may not be ok for you, but a link to login page only for users to confirm that Serenity is actually used would be appreciated.
- Any comments you'd like to add. How Serenity helped you, did it have a positive effect on release time, what were challanges etc.

There will be another section on landing page about "what our users say". If you'd like to be shown there need information listed below:

- Full Name / Nickname
- Company Name, if any
- Your small photo (face)
- Your review, how you use Serenity, how it helped etc.

I'm planning to add some reviews from VSGallery and user comments collected from issues here, so if you had a review there please add your username shown in VSGallery.

Thanks to all.

**Comment by samdubey** [comment]
**Who uses Serenity**
User / Company Name : Knowtulus Technologies Private Limited.
Product Name: KoFees  - Fees Management System for School and Institutes
Company / Product Logo if any
Company / Product Site URL if any: kofees.com
A short description of what product does: Easy Fees and Student Invoice Management with various 
options for creating payment plans per course

At least one screenshot from your application, with details blurred for security purposes if required.
A link to your application if possible. I understand Serenity apps are usually administrative so this may not be ok for you, but a link to login page only for users to confirm that Serenity is actually used would be appreciated.
http://fees.azurewebsites.net

Any comments you'd like to add. How Serenity helped you, did it have a positive effect on release time, what were challanges etc.
Lightning fast development for this project

**what our users say**
Full Name / Nickname: Dilip Kalantri
Company Name, if any: Knowtulus Technologies Private Limited.
Your small photo (face): 
![dsc_1070](https://cloud.githubusercontent.com/assets/4013722/17401923/092b4378-5a6e-11e6-8ff9-7a17c743ec31.JPG)

Your review, how you use Serenity, how it helped etc.
Selecting serenity framework has drastically reduced time to market for this app and this framework is well thought framework in terms of design, architecture and user experience

**Comment by Estrusco** [comment]
I'm on vacation, I return to the office in september and I will send you the data. Good summer to all!

**Comment by jdready5** [comment]
Great idea! I will have all this in here before the weekend!

**Comment by rolembergfilho** [comment]
Me too,

I'll try to post my projects this weekend !

I would like to add a question in original list (for developers)
"Which enhancement you did in your Serenity project? "

The goal is who done more differents features than listed and explained in Serenity tutorials and wiki.
I think that a good way to improve the Serenity project, and then became a new tutorials or samples for news developers!

**Comment by wdhodges** [comment]
I'll get his to you asap! Our website is internally hosted on our systems intranet, so the URL wont work but I can give screenshots :+1:

**Comment by samdubey** [comment]
# **Who uses Serenity**
User / Company Name: Antargyan CloudWorks LLP
Product Name: RecordShield
Company Logo if any: 
![antargyan-cloudworks-logo](https://cloud.githubusercontent.com/assets/4013722/17456537/70b715ea-5bf8-11e6-87e6-a7c6209eb9ca.png)

Product Logo if any:
![record-shield-logo](https://cloud.githubusercontent.com/assets/4013722/17456540/7bb378b2-5bf8-11e6-8583-d8574ab38980.png)

Company / Product Site URL if any: [www.antargyan.com](http://www.antargyan.com) / [www.recordshield.net](https://recordshield.net) 

A short description of what product does: RecordShield is Video Encryption and Distribution Platform for anyone to share their content securely with other people

At least one screenshot from your application, with details blurred for security purposes if required.
![recordshield](https://cloud.githubusercontent.com/assets/4013722/17456600/06c9a9c4-5bfb-11e6-8e20-4c17d61360d3.png)


A link to your application if possible. I understand Serenity apps are usually administrative so this may not be OK for you, but a link to login page only for users to confirm that Serenity is actually used would be appreciated.
Any comments you'd like to add. How Serenity helped you, did it have a positive effect on release time, what were challenges etc.
We faced challenges with Forms Authentication working with Mobile Apps 
RecordShield Content Activation done through Serenity Framework Over Email, SMS and Internet Channels
Serenity is very robust and powerful framework in creating multi-tenant enterprise applications

**Comment by ramveersgh** [comment]
Collecting this information sound good for Serenity. I have limited availability for checking email, So i am not able to help on the issue reported in github but glad to know that people are helping each other and sharing knowledge base.

I am sharing my demo version of the product build using Serenity.
url : http://demo.tranzol.in/TranzolERP/Account/Login
username: admin
pass: demo@123

Here are more details asked - 
User / Company Name - CIYA Technologies
Product Name - Tranzol
Company / Product Logo if any -  http://demo.tranzol.in/CIYALogo.png
Company / Product Site URL if any - www.ciyatech.com
A short description of what product does
Tranzol is a single-platform software solution designed for logistics industries to increase your productivity and improve integration, and communication with the supply chain. It integrates and automate your business with your customers and partners, streamlining processes and increasing the efficiency, visibility, and profitability of your operations.

There will be another section on landing page about "what our users say". If you'd like to be shown there need information listed below:

Full Name / Nickname : Ram
Company Name, if any : CIYA Technologies
Your small photo (face):  [http://demo.tranzol.in/MyPic.jpg](face)
Your review, how you use Serenity, how it helped etc: 
The Serenity framework is awesome which decrease development time drastically  and developer can focus on business logics only. UI, Security, Auditing etc and lot of other thing are taken care by Serenity.
This is an amazing framework and it does not have any comparison (at least in my knowledge).
The best part is that this framework is an open source with an excellent support.

**Comment by Estrusco** [comment]
Hi @volkanceylan !
Here my company information

•User / Company Name: **Speed Informatica S.r.l.**
•Product Name: **The name of the project has not yet been defined. Speed Web Edition (temporary name)**
•Company / Product Logo if any: 
![logo_speed_targ_col](https://cloud.githubusercontent.com/assets/16304015/18392651/dc1ffb4c-76b2-11e6-9e78-4716efc01743.png)

•Company / Product Site URL if any: http://www.speed-informatica.it/ 
•A short description of what product does: **HR Product**
•At least one screenshot from your application: **later**
•A link to your application if possible: **later**
•Any comments you'd like to add: **Serenity is a great framework that has accelerated very much our transition to a web application. It is stable and fast, customizable and easy to learn. Plus the fact that you use C # to server side language is very important for us.**

**Comment by volkanceylan** [comment]
Thanks to everyone who shared details so far. I've put a summary of them on front page, but page with details will come later. Let me know if i missed any. Thanks again.
