### ISSUE TITLE
Manually force local cache expiration

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1007]
Dear @volkanceylan,
I was wondering if there is a proper way to force the expiration of the local cache.
At the moment I'm using the local cache in order to store some information (counters) on the template, but when a user performs some kind of "action" (e.g. add new item), I would like to expire his cache in order to update those counters immediately.
So if I create the local user cache in the following way:

    var cachedModel = TwoLevelCache.GetLocalStoreOnly("DashboardPageModel" + Authorization.UserId, ....

how I can retrieve and expire the cache? If it's possible, I can do that both from dialog and from repository?

Thank you very much
Bye

**Comment by volkanceylan** [comment]
You should use TwoLevelCache.Remove or if you specified a group key, TwoLevelCache.ExpireGroupItems

**Comment by marcobisio** [comment]
Thank you very much @volkanceylan...just to know I can use the Remove method even if I have specified a group key when I created the cache?

**Comment by marcobisio** [comment]
Found a code sample in the UserRetrieveService :-)

Thank you very much
Bye
