### ISSUE TITLE
 Associate a long description to a field (or entity btw)

### ISSUE THREAD

**Issue by joaorod** [volkanceylan/Serenity#1008]
Hi!

First of all, never is much to say, what a brilliant job with Serenity!!

I miss in Serenity the possibility to associate a long description to a field. That would be useful to fields where the display name is not enough to completely describe the purpose of that.

In terms of implementation, IMHO, that could work based on an attribute, much like DisplayNameAttribute currently works. In this case, System.ComponentModel.DescriptionAttribute would be appropriated.

Possible usage Example:

`[DisplayName("Public Key"), Description("This key you should share with your partners.\r\n That allows your partners to send secure messages to you.")]`
`public String PublicKey {...`

This description could be placed somewhere in the form, near the associated field.
`Public Key * [VHlwZSlcmUuLi4= ]  (i) This key you should share with your partners.
			                       That allows your partners to send secure messages to you.
`

In addition to fields that could also work with entities (rows) to give some kind of description of what is the purpose of that entity.
The possibility to have multiple lines (\r\n) and support for localization would be also great!

IMHO, I think the implementation itself would not be so hard. Basically the identical job has already been done with DisplayNameAttribute.

I was trying to implement this **globally** myself but I think that this must be done inside Serenity sources. I've tried to do that, but, at least for now, I don’t know the platform well enough to perform the task. 

So, I leave here the idea. If someone could give me some guidance I would love to implement that myself...

Regards!

**Comment by rolembergfilho** [comment]
Hey Joao,

Are you from Brazil too?

I had this question months ago. After helps from Volkan and other guys, I did this way:

1 - Placeholder
1.1 - In XYZrow.cs, above the name of the field, insert the Placeholder Attribute
e.g.: 
        [DisplayName("Nome"), Size(100), Placeholder("Nome do Contato")]
        public String Nome
        {
            get { return Fields.Nome[this]; }
            set { Fields.Nome[this] = value; }
        }

2 - Hint
2.1 - If the description is so long, consider insert Hint Attribute instead Placeholder. To see it, let's the mouse hover the field DisplayName for some seconds.
e.g.:

        [DisplayName("Nome"), Size(100), Hint("Nome do Contato")]
        public String Nome
        {
            get { return Fields.Nome[this]; }
            set { Fields.Nome[this] = value; }
        }

3 - Both
3.1 - I'm using this way: placeholder to short explanation of the field, and hint to a detailed explanation of this field

e.g.:

        [DisplayName("Nome"), Size(100), Placeholder("Nome do Contato"), Hint("Nome do contato que se responsabilizará pelo contrato\nFavor preencher o nome completo.")]
        public String Nome
        {
            get { return Fields.Nome[this]; }
            set { Fields.Nome[this] = value; }
        }


ps.: to breakline, use "\n" instead "\r\n"

**Comment by joaorod** [comment]
Hi Rolemberg,

In fact I speek portuguese also but I'm from across the atlantic sea, from Portugal! 

Now I see that I totally miss issue #720, sorry for that.

I'll give it a try, yet, for what I see that doesn't seem to completely invalidate the need for Description. Yet, I must check that in action and maybe Hint+Placeholder can be enough.

For now, I'll just close this since duplicates  #720.

Thanks a lot!
