### ISSUE TITLE
query 2 unrelated tables in LookupScript

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1009]
I could use plain MVC but I want to stay with the concepts already built in. Here is my scenario; I have an order, when that order is edited or a new one added I need to choose a vendor. I am choosing a vendor based on radius. I query a zipcode table 1st and get a list of zipcodes within the radius, then I query the vendors table for a list of vendors with those zipcodes. When the user selects the vendor they want, it populates the "vendor id" field in "orders". I am using a lookup editor for orders based on vendorRow. Is writing all of my c# with both queries and my if statements best inside the one lookup script or is there a better practice to use?

**Comment by volkanceylan** [comment]
I might not understood question correctly, but lookup scripts are for static data. I recommend calling a service in your endpoint, and returning results from there.

**Comment by jdready5** [comment]
Ah, that makes more sense. I am using a query with the "great circle" calculation in it to return an array or a list of zip codes and then want to base my lookup of vendors on that list. here are my 2 queries if it helps. I can do the service in my endpoint to return the zips and then probably a custom lookup with the criteria to return my vendors.
1st query:
select zipcode from(
SELECT zipcode, ( 3959 * acos( cos( 38.6285426/57.2958 ) * cos( lat/57.2958 ) 
* cos( lon/57.2958 - -86.05296039999999/57.2958 ) + sin( 38.6285426/57.2958 ) * sin(lat/57.2958) ) ) AS distance 
FROM zip_codes)
where distance < 20 
ORDER BY distance 

2nd query:
select * from vendor where zip = 47167, 47162, 47163

**Comment by volkanceylan** [comment]
Maybe this can be helpful

https://github.com/volkanceylan/Serenity/issues/375

**Comment by jdready5** [comment]
Taking a quick glance at that looks like exactly what I need or at least points me in the direction I need to go. Thank you very much, I appreciate it.
