### ISSUE TITLE
Question: How to add time to DateTime field?

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#101]
For a DateTime field in a database record, how do I configure the Row and/or Form to capture the hour and minute (as well as, date)?

UI kinda like the attached file.

Thanks
![date and time fields](https://cloud.githubusercontent.com/assets/8460261/12264699/855a5650-b906-11e5-9625-24e3f3bbdb2b.jpg)

**Comment by volkanceylan** [comment]
Did you try DateTimeEditor?

**Comment by brettbeard** [comment]
No, didn't know about the DateTimeEditor.  However, I know about it now.  Thanks.
