### ISSUE TITLE
Cascading Filters - Drilling down on one table only

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#1010]
Hi Community,

I have a rather simple but hopefully not a stupid question.

I have this **single SQL table** with columns for countries, cities, periods and a corresponding amounts for each line. I've already generated code for it and the grid is showing in my application.

I am trying to avoid creating extra SQL tables like the "How To: Setup Cascaded Editors" sample indicates and I want it to function more like the simple filters under Customer's grid in the Northwind sample.

Now I am trying to add 2nd and 3rd level filtering in a form with Lookup Editors. I have followed the Northwind.Customer sample code but my 2nd level filter is still showing **all the cities** of the table. 

That is, the 2nd level filter in my dialog form is not dependent on the CountryId editor and still shows cities from all the lines in my table.

Is there anyone who has a useful tip for me on how to achieve this correctly?

See following pictures for further clarification:

The table which I want the filters to Lookup in:
![image](https://cloud.githubusercontent.com/assets/15879719/17415329/f3fbda7a-5a78-11e6-8dfa-113b909c3622.png)

The form showing all cities although the 1st level filter has been chosen:
![image](https://cloud.githubusercontent.com/assets/15879719/17415384/2c1281a2-5a79-11e6-8811-9b32be94916f.png)

My code for the form:

```

namespace PerDiem.Ferdir.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;

    [FormScript("Ferdir.Utanlands")]
    [BasedOnRow(typeof(Entities.UtanlandsRow))]
    public class UtanlandsForm
    {
        [Category("Grunnur")]
        public String EmployeeId { get; set; }
        [ReadOnly(true)]
        public String EmployeeName { get; set; }
        [ReadOnly(true)]
        public String TravelId { get; set; }
        [Category("Deild og samþykki")]
        public String DepartmentId { get; set; }
        public String DepartmentSupervisor { get; set; }
        public String Division { get; set; }
        public String Supervisor { get; set; }
        public String AuthorizedBy { get; set; }
        public DateTime AuthorizedDate { get; set; }
        [Category("Ferðaupplýsingar")]
        public String Category { get; set; }
        [LookupEditor(typeof(Scripts.UtanlandsCountryLookup)), QuickFilter]
        public String CountryId { get; set; }
        [LookupEditor(typeof(Scripts.UtanlandsCityLookup))]
        [QuickFilter, QuickFilterOption("CascadeFrom", "CountryId")]
        public String City { get; set; }

```

**Comment by CAlva123** [comment]
I have a similar scenario (all keys in one single table, string ids, trying to do a cascade filters).
My 3rd level filter doesn't work, but the 2nd level seems to work.

Here is the code in my table Form :

[LookupEditor(typeof(Scripts.UbigeoDepartamentoLookup))]
public String IdDepartamento { get; set; }
[LookupEditor(typeof(Scripts.UbigeoDepartamentoProvinciaLookup),
CascadeFrom = "IdDepartamento", CascadeField = "IdDepartamento")]
public String IdProvincia { get; set; }

And the query in the Lookups :

UbigeoDepartamentoLookup:

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            var fld = UbigeoRow.Fields;
            query
                .Where(

                   
                    new Criteria(fld.IdProvincia)== 0 &  // Special condition in my table
                    new Criteria(fld.IdDistrito) == 0       // Special condition in my table
                    );

        }

UbigeoDepartamentoProvinciaLookup:

 protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            var fld = UbigeoRow.Fields;
            query
                .Where(
                    
                    new Criteria(fld.IdProvincia) != 0 & //Special condition in my table
                    new Criteria(fld.IdDistrito) == 0 // Special condition in my table
                    );
        }

I hope it helps somehow.

**Comment by volkanceylan** [comment]
You don't have CascadeFrom in City property. The one you applied with QuickFilter and QuickFilterOption is only useful with columns and quick filters. They are not used for forms. You should write CascadeFrom and CascadeField in LookupEditor property, e.g. LookupEditor("XYZ", CascadeFrom = "CountryId", CascadeField = "XYZ")

**Comment by biggikalli** [comment]
BRILLIANT - Thank you for quick reply and absolutely spot-on diagnosis and cure:

![image](https://cloud.githubusercontent.com/assets/15879719/17420319/a5bdd3ea-5a91-11e6-843a-61eb8a987fa3.png)

After your solutions, my code ended like this:

```
...
        [LookupEditor(typeof(Scripts.UtanlandsCountryLookup))]
        public String CountryId { get; set; }
        [LookupEditor(typeof(Scripts.UtanlandsCityLookup), CascadeFrom ="CountryId")]
        public String City { get; set; }
...
```
