### ISSUE TITLE
Basic Samples -> Grids empty after deployment but OK when running from VS.

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1011]
Hi there,
New to this forum and product.
First things first - THANK YOU! for offering such a great product.
Everything works and the help given in the docs is right on the money! The later in itself is amazing!

For the next - if this has already been discussed please let me know where.
If not - the resolution will really go a long way to enhance the first impression.

Problem: As per the subject line
Details:
Database:      MS SQL 2014
DB Location:  On a separate server (not developer's PC)
My account:  Sysadmin + DBO on both Serene DB's; Full access to server.
Deployment: Copy/paste of Serene.Web to the IIS server.
IIS App Pool: Uses my own account which has no restrictions to the SQL and the IIS servers.
IDE:                Visual Studio Enterprise 2015

Project: 
- Created as-is from the demo template. No changes.
- Works great when I run it from VS.
- I did use the Administration tools to add my own account as a user. I can see the account in the DB.
- When I try to access the project from the URL (any browser) I do not see:
-- Northwind
-- Administration
-- Any data in the Basic Samples grids is empty.

Dashboard samples show data OK.
This is the same with either of the login id's: admin (default) and my new test ID I created from the Admin tools.

Login Behavior when running from IIS:
1st time: I login with admin + default pwd
User name is shown as "admin" in the top right.
Log Out is OK and brings me to the login screen.

2nd login with my new ID
User name properly shows my new ID in the top right - however I cannot log out.
Trying to login with admin again defaults back to my login ID in the top right.

No such problems when I run from VS in debug mode.

Many thanks in advance!

**Comment by volkanceylan** [comment]
Please check if you have an error in browser console when logged in with secondary user.

**Comment by SimeonDD** [comment]
Hi Volkan,
Thanks for responding so fast!

I do not get an error when logging in.
However when I try to open a grid I get this:

Chrome –> Network -> Lookup.Northwind.Supplier.js?....
---------------------------------------------------
Server Error in '/' Application.

Authorization has been denied for this request!

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Serenity.Services.ValidationError: Authorization has been denied for this request!

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[ValidationError: Authorization has been denied for this request!]
   Serenity.Authorization.ValidatePermission(String permission) in P:\Sandbox\Serene\Serenity\Serenity.Core\Authorization\Authorization.cs:99
   Serenity.Web.DynamicScriptManager.GetScript(String name) in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptManager.cs:94
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptHandler.cs:19
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +508
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

----------------------------------------------------------------
-> Console:
GET: 500 (Internal Server Error)

send      @jquery-2.2.0.js?v=.....:9172
ajax        @jquery-2.2.0.js?v=.....:8653
syncLoadScript  @Serenity.CoreLib.js?v=.....:1607
loadScriptData   @Serenity.CoreLib.js?v=.....:1622
ensure  @Serenity.CoreLib.js?v=.....:1636
getLookup          @Serenity.CoreLib.js?v=.....:1708
getLookup          @Serenity.Script.UI.js?v=.....:4624
updateItems      @Serenity.Script.UI.js?v=.....:4643
$Serenity_LookupEditorBase     @Serenity.Script.UI.js?v=.....:2323
$Serenity_LookupEditor               @Serenity.Script.UI.js?v=.....:2310
Widget.create   @Serenity.CoreLib.js?v=.....:2522
addQuickFilter   @Serenity.Script.UI.js?v=.....:5887
createQuickFilters           @Serenity.Script.UI.js?v=.....:5200
$Serenity_DataGrid        @Serenity.Script.UI.js?v=.....:359
$Serenity_EntityGrid      @Serenity.Script.UI.js?v=.....:1247
ConditionalFormattingGrid          @ConditionalFormattingGrid.ts:13
(anonymous function)   @ConditionalFormatting:686
fire         @jquery-2.2.0.js?v=.....:3182
fireWith               @jquery-2.2.0.js?v=.....:3312
ready    @jquery-2.2.0.js?v=.....:3531
completed          @jquery-2.2.0.js?v=.....:3547

Uncaught Error: Can’t load script Serenity.CoreLib.js?v=……:1640
Uncaught Error: Can't load script data: Lookup.Northwind.Supplier!
ensure  @Serenity.CoreLib.js?v=...:1640
getLookup          @Serenity.CoreLib.js?v=...:1708
getLookup          @Serenity.Script.UI.js?v=...:4624
updateItems      @Serenity.Script.UI.js?v=...:4643
$Serenity_LookupEditorBase     @Serenity.Script.UI.js?v=...:2323
$Serenity_LookupEditor               @Serenity.Script.UI.js?v=...:2310
Widget.create   @Serenity.CoreLib.js?v=...:2522
addQuickFilter   @Serenity.Script.UI.js?v=...:5887
createQuickFilters           @Serenity.Script.UI.js?v=...:5200
$Serenity_DataGrid        @Serenity.Script.UI.js?v=...:359
$Serenity_EntityGrid      @Serenity.Script.UI.js?v=...:1247
ConditionalFormattingGrid          @ConditionalFormattingGrid.ts:13
(anonymous function)   @ConditionalFormatting:686
fire         @jquery-2.2.0.js?v=...:3182
fireWith               @jquery-2.2.0.js?v=...:3312
ready    @jquery-2.2.0.js?v=...:3531
completed          @jquery-2.2.0.js?v=...:3547

The errors look like this:
[cid:image001.png@01D1EE7D.340BDB50]

From send jquery-2.2.0.js
[cid:image002.png@01D1EE7D.D4044F70]

**Comment by SimeonDD** [comment]
I also added an application user "TestSereneAdmin" from the admin interface. I made sure that all of the permissions in the Permissions Pop-Up are granted. This time (instead of using a domain account) I added this user as an SQL DB login and mapped it to the demo databases with DBO rights. Same thing. Northwind not showing when running from IIS and the BasicDemo grids are empty. Getting "Navigated to http://xxxxxx.245:8085/Account/Login?returnUrl=%2FNorthwind%2FOrder&denied=1"

All works like a charm when running from Visual Studio directly.

IIS Pool Identity is using my own domain account and has no restrictions or access issues whatsoever.

**Comment by SimeonDD** [comment]
Saw hope but only for a brief moment. 
Moved the database to an SQL server hosted on the same box as IIS (to avoid double-hop issues)

Disabled these in SiteInitialization.cs
//if (!ConfigurationManager.AppSettings["LDAP"].IsTrimmedEmpty())
                //    registrar.RegisterInstance<IDirectoryService>(new LdapDirectoryService());

//if (!ConfigurationManager.AppSettings["ActiveDirectory"].IsTrimmedEmpty())
                    registrar.RegisterInstance<IDirectoryService>(new ActiveDirectoryService());

Also disabled these:
            foreach (var databaseKey in databaseKeys)
            {
                //EnsureDatabase(databaseKey);
                //RunMigrations(databaseKey);
            }

Cleared browser history completely.
Logged with the default account "admin".
All grids showed fine.
Logged out. App did not go to logout screen and all problems began anew. Grids not showing and Northwind not showing.

**Comment by SimeonDD** [comment]
Confusion sets in.
Now all except logout is fine. Grids show great.

Only log out does not go back to login screen.

The only thing different this time. Cleared entire chrome history one more time ... go figure....
The test SQL account was not needed which was kind of obvious (now removed from the server and the db's).

Above code changes stay.

Observation: No matter how I login my actual active directory ID is shown on the top right.
This is not the case when I run it from Visual Studio. From VS all works fine.

**Comment by volkanceylan** [comment]
This seems like an AD case issue. Are you sure your DB collation is case insensitive. 

Second, try with a manually created user in User Administration screen, not LDAP. Grant him all rights, and check if you still get error. 

I don't understand where you get that error about Supplier lookup. It's not used in login, or dashboard as far as i remember.

**Comment by SimeonDD** [comment]
Thanks Volkan!
Both databases were created with case insensitive collation.
SQL_Latin1_General_CP1_CI_AS

About LDAP:
I even modified SiteInitialization.ApplicationsStart() like this:
//if (!ConfigurationManager.AppSettings["LDAP"].IsTrimmedEmpty())
//    registrar.RegisterInstance<IDirectoryService>(new LdapDirectoryService());
//if (!ConfigurationManager.AppSettings["ActiveDirectory"].IsTrimmedEmpty())
      registrar.RegisterInstance<IDirectoryService>(new ActiveDirectoryService());

I did add a new Test Admin user as you suggested:
[cid:image002.jpg@01D1EF32.89EABA40]


I can reliably replicate the issue now.
Exact steps:

1.       RDP ->

2.       Stop the site (IIS)

3.       Stop/Restart the IIS App Pool

4.       Start the site

5.       Local PC ->

6.       Open empty Chrome and clear all browsing history.

7.       Close the browser

8.       Re-open and go to the site.

9.       I get a login screen.

10.   I go in with admin or the new TestAdmin (it does not matter which – same result).

11.   After login I see top-right my AD login and these pages:

·         Dashboard

·         Basic Samples

·         Theme Samples
Note: Top-right now I can see my AD login ID.

At this point If I recycle the ISS Application pool used on the site and simply refresh the same page (browser stayed open) I get the full set of pages:

·         Dashboard

·         Basic Samples

·         Theme Samples

·         Norhtwind

·         Administration
Note: Top-right the name is set as per table dbo.Users

As soon as I try to see any grid or page I am re-routed to the login screen.
Console error:
Navigated to http://...:8085/Account/Login?returnUrl=%2FNorthwind%2FCustomer&denied=1

After that no kind of login works again – I have to go back to step-1 above.

**Comment by volkanceylan** [comment]
I'm unable to understand what is going on. Why your AD login is seen on top right when you login with admin. Are you sure you didn't enable Windows Auth?

**Comment by volkanceylan** [comment]
admin has all rights to all pages if you didn't change it. And you should see "admin" on top right if you login with admin. What i understand is you see your AD id, so windows auth must be kicking in.

**Comment by SimeonDD** [comment]
The only setting in the web config that I changes was the connection string.
It just points to the correct server.
The initial run created the databases on that server

  <connectionStrings>
    <add name="Default" connectionString="Data Source=<… a server IP…>; Initial Catalog=SereneCleanDemo_Default_v1; Integrated Security=True" providerName="System.Data.SqlClient" />
    <add name="Northwind" connectionString="Data Source==<… a server IP…>; Initial Catalog=SereneCleanDemo_Northwind_v1; Integrated Security=True" providerName="System.Data.SqlClient" />
  </connectionStrings>

The rest is like this (default values):
<system.web>
    <authentication mode="Forms">
      <forms loginUrl="~/Account/Login" timeout="2880" path="/" />
    </authentication>
    <compilation debug="true" targetFramework="4.5" />
    <httpRuntime targetFramework="4.5" />
    <customErrors mode="Off" />
    <globalization culture="auto:en-US" uiCulture="auto:en-US" />
  </system.web>


I am sure this can be replicated with:

1.       Any machine acting as both IIS and SQL server. It must be different than the developer’s PC.

2.       Developers PC with VS 2015

3.       Create new project from the VS template.

4.       DO NOT run yet.

5.       Modify the Web.config as shown above

6.       Now run from VS.

7.       Observe creation of databases. Btw. You should be creating the databases with owner “SA” not the given AD Login. Easier to maintain.

8.       Make sure the developer’s AD login has dbo rights to the new databases.

9.       So far all is great when running from VS.

10.   Create a default IIS site and point it to a directory in which you copy all from the .WEB folder

11.   Make sure that IIS settings, pools etc are all set for an ID that has rights to everything. Keep IIS and SQL on the same box to avoid double-hope headaches.

12.   Go back to the developer’s PC and access the site – likely you will see the problem.

**Comment by volkanceylan** [comment]
I don't see such. Check IIS settings.

**Comment by SimeonDD** [comment]
IIS Authentication:
Anonymous = Disabled
ASP.Net impersonation = Disabled
Basic Authentication = Disabled
Forms Authentication = Enabled (HTTP 302 Login/Redirect)
Windows Authentication = Enabled (HTTP 401 Challenge)

Basic Settings: Authentication pass-through via an IIS App Pool.
Test show all green.

IIS Application Pool: Uses my own AD ID - has full access, no restrictions.

Web.config:
Other than the connection string (server name & db name) I did not change any other settings.

Any other settings you would recommend I check?

**Comment by volkanceylan** [comment]
Disable Windows auth, disable pass through

**Comment by SimeonDD** [comment]
========= Core issue: ===============
The IIS site pool identity shows in the top-right corner after logging in with the default admin account.

The confusing part is that the code proceeds to show incomplete demo (as per description above). Log out does not work.

========= Workaround: ==============
Disclaimer: This is by far not a true prod setup but it will at least allow you to show something to others on the intranet.

Key Setting that fix this behavior:
IIS Settings: Site -> IIS -> Authentication:
- Anonymous Authentication = Enabled
- Windows Authentication = Disabled

Details if you are starting from scratch:
1. Start with a default IIS site.
2. Site -> Bindigs -> hard-code to IP and Port (for now disregard site name etc.)
3. Site Name: Serene (or whatever)
4. Modify the application pool created by IIS (same name as the site - Serene) as:
- .NET CLR Version v.4.0
- Pipeline mode: Integrated
- Advanced Settings: Identity = any AD account that has access to the IIS & SQL server and the database

5. Site -> IIS -> Authentication
Anonymous Authentication = Enabled
ASP.NET Impersonation = Disabled
Basic Authentication = Disabled
Forms Authentication = Enabled
Windows Authentication = Disabled

5. Site -> Basic Settings:
- Application Pool = Serene (see above)
- Connect as pass-through 
Why not something else?
Because replacing with an active dir user results in a welcome sign-in screen that does not respond.
Errors:
RegisteredScript.js => Failed to load resource: the server responded with status of 500 (Internal Server Error)
Uncaught Error => Script data Form.Membership is not found in registered script list.

**Comment by volkanceylan** [comment]
Windows auth logs you in with windows user that Serene knows nothing about. So this is completely normal.
