### ISSUE TITLE
3rd level Cascading Filters

### ISSUE THREAD

**Issue by CAlva123** [volkanceylan/Serenity#1013]
I have a problem similar to what's described in Issue #1010. As I mentioned there, I want to implement 3rd level filtering (IdDepartamento -> IdProvincia -> IdDistrito), with all data being taken from a single table.

This is how my table with the 3 ids work:
![Ubigeo Filters](http://i.imgur.com/Rp8uHRK.png)

The first two filters are working, but when I select the third combo, it just validates with IdProvincia (second combo), and not with IdDepartamento(firts combo).
  
I want to implement that logic in a form.
Here is the code, I use custom lookups because the first two Ids need special conditions to be met :

        [LookupEditor(typeof(Scripts.UbigeoDepartamentoLookup))]
        public String IdDepartamento { get; set; }
        [LookupEditor(typeof(Scripts.UbigeoDepartamentoProvinciaLookup),
        CascadeFrom = "IdDepartamento", CascadeField = "IdDepartamento")]
        public String IdProvincia { get; set; }
        [LookupEditor(typeof(Scripts.UbigeoDepartamentoProvinciaDistritoLookup),
        CascadeFrom = "IdProvincia", CascadeField = "IdProvincia")]
        public String IdDistrito { get; set; }

How can I validate the 3rd level filtering correctly?  I can't find where or how to do it, so I'd like some help with this.

Thanks in advance.

**Comment by volkanceylan** [comment]
Does this lookup, UbigeoDepartamentoProvinciaDistritoLookup, include IdProvincia and other fields.

**Comment by CAlva123** [comment]
This is UbigeoDepartamentoProvinciaDistritoLookup code:  

public class UbigeoDepartamentoProvinciaDistritoLookup : RowLookupScript<Entities.UbigeoRow>
    {
        public UbigeoDepartamentoProvinciaDistritoLookup()
        {
                      IdField = UbigeoRow.Fields.IdDistrito.PropertyName;
                      TextField = UbigeoRow.Fields.Nombre.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            var fld = UbigeoRow.Fields;
            query
            
            .Select (fld.IdDepartamento)
            .Select(fld.IdProvincia)
                .Where(

                    new Criteria(fld.IdDistrito) != 0 &
                    new Criteria(fld.IdProvincia) != "" &
                    new Criteria(fld.IdProvincia).IsNotNull() &
                    new Criteria(fld.IdDepartamento) != "" &
                    new Criteria(fld.IdDepartamento).IsNotNull());
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }

**Comment by volkanceylan** [comment]
If i understand right, your IdDistrio is not empty but it brings distrito from all departments. This is completely normal, you need to use a unique ID, it won't work this way.

**Comment by volkanceylan** [comment]
You might try using a combination ID, e.g. IDDepartmanto_IdProvincia, like 02_02

**Comment by CAlva123** [comment]
Yes, IdDistrito is not empty, but it brings Distritos (Districts) from all departments.
I will try to use a combination ID and post here if it works.

**Comment by biggikalli** [comment]
Hi @CAlva123 & @volkanceylan ,

When it rains, it pours!
I am having exactly the same issue...and I am even pushing to reach a 4th level cascading filter on the same table. Is that even possible Volkan?

I would really like to hear about your results @CAlva123 - if you would be so kind to share.

**Comment by CAlva123** [comment]
I combine both Id's in mytable.Row using CONCAT:

[DisplayName("combination ID"), Size(4), NotNull, LookupInclude, Expression("CONCAT(T0.[IdDepartamento], CONCAT('_', T0.[IdProvincia]))")]
        public String IdDepPro
        {
            get { return Fields.IdDepPro[this]; }
            set { Fields.IdDepPro[this] = value; }
        }
And this is the result:
![Image of CombID](http://i.imgur.com/iz2eQQU.png)

However,  I don't know how or where I can add the validation for the 3rd combo using this new field.
I have tried some combinations in my lookup, but without success.

Can you help me a little more with this please?

**Comment by volkanceylan** [comment]
That new field will become CascadeField, that's all.
