### ISSUE TITLE
Open Add/Edit dialog from fullCalendar dayClick event

### ISSUE THREAD

**Issue by reybatacjr** [volkanceylan/Serenity#1014]
Hi, I want to add Task Scheduler using fullCalendar.
I modified cshtml generated by sergen with these line of codes.

@{
    ViewData["Title"] = Serenity.LocalText.Get("Db.Registration.TaskSchedule.EntityPlural");
}
@section Head {
    <link rel="stylesheet" href="~/Scripts/fullcalendar/fullcalendar.min.css">
    <link rel="stylesheet" href="~/Scripts/fullcalendar/fullcalendar.print.css" media="print">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="~/Scripts/fullcalendar/fullcalendar.min.js"></script>
    <script src="~/Scripts/adminlte/demo.js"></script>
}
<div id="calendar"></div>

<script type="text/javascript">
    jQuery(function () {
        $('#calendar').fullCalendar({
            editable: true,
            dayClick: function (date, jsEvent, view) {
                PhilEnglishRegistration.Registration.TaskScheduleDialog().loadByIdAndOpenDialog(0);
            }
        })
    })
</script>

im getting this error:
Serenity.CoreLib.js?v=wXQMO0cdMs57MS97wmD5eg2:2459 Uncaught TypeError: this.addCssClass is not a function

Please help I don't know that function/s needs to be loaded before I can use xyzDialog().loadByIdAndOpenDialog method

**Comment by reybatacjr** [comment]
Thanks I found out i just need "new" keyword :D

**Comment by rolembergfilho** [comment]
could you share with your Task Scheduler using fullCalendar implementation?

What about publish it in Serene.Dev BasicSamples?

**Comment by reybatacjr** [comment]
Hi, what I did is a quick implementation of fullCalendar and think it won't fit to on BasicSamples :).

I have attached the 2 files I've modified, TaskScheduleIndex.cshtml and TaskSchedulePage.cs im still trying to find a way on how to refresh the calendar after adding new task :)

[TaskScheduleIndex.zip](https://github.com/volkanceylan/Serenity/files/404873/TaskScheduleIndex.zip)

**Comment by rolembergfilho** [comment]
If it won't fit in BasicSamples, what about create a "Enhanced Samples" or "Advanced Turbo Samples" :) ?

For refresh, did you try reloadLookup in onSaveSuccess method?

**Comment by reybatacjr** [comment]
Thanks for the time I will try that reloadLookup at home :) im in the office right now and can't run the project for testing.

What I mean with it won't fit in BasicSamples is the there might be a cleanest implementation on it, like on the JsonResult not sure if there's a native Json from Serene, and if in the right place (xyzPage.cs).

**Comment by reybatacjr** [comment]
I mean for the tip :) Thanks for the tip
