### ISSUE TITLE
How to filter the grid based on a field which has LinkingSetRelation

### ISSUE THREAD

**Issue by xjbsky** [volkanceylan/Serenity#1015]
I have a similar question to  issue 454, but I can't figure out how to use expression field with EXISTS.......

```
        [DisplayName("Task Categories"), LookupEditor(typeof(CategoryRow), Multiple = true), ClientSide]
        [LinkingSetRelation(typeof(TaskCategoryRow), "TaskId", "CategoryId")]
        [Width(150), TaskCategoryListFormatter]
        public List<Int32> TaskCategories
        {
            get { return Fields.TaskCategories[this]; }
            set { Fields.TaskCategories[this] = value; }
        }
```

How can I filter the grid based on one or multiple Category these are saved in lookup table?

please help, thanks

**Comment by volkanceylan** [comment]
Have a look at movie tutorial, multiple genre topic

**Comment by xjbsky** [comment]
thanks, I have not noticed this new topic on the tutorial.
Great work.
