### ISSUE TITLE
Cannot register an enum type in my own Module

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#1016]
Hi Volkan, just trying to declare an enum type (like MovieKind in the tutorial), it is not registered in $knowsTypes (needless to say I've hit Transform All T4 like mad like suggested in the tutorial before we bother you with an issue ;).

It works fine if I declare my types in Northwind and use them in my own project! What did I miss so that all type declarations are transformed and registred? Why does it work in MovieDB and not in mine :(
Thanks.

**Comment by xjbsky** [comment]
it seems you have to declare a field of the enum type in the  column or form

**Comment by BravoSierra** [comment]
I did, and it works perfectly when my Enum is declared in the Northwind.Entities namespace just like there is already a 'gender' Enum. 

But when the exact same Enum declaration is in my own Module, then it is not registered and when I look into $knowsTypes my type is not in there. I'm not sure if serene looks for declarations in all Modules folders, or if there is somewhere I should tell the compiler or the Template builder to look Inside my module for types déclarations.

**Comment by volkanceylan** [comment]
Check your namespace. Must start with root namespace

**Comment by BravoSierra** [comment]
it does start with root namespace "Trelis" in both cases. When I declare it in Northwind Module it works with the namespace: 
namespace Trelis.Northwind.Entities
In my module (trelis) it does not work, with this namespace:
namespace Trelis.trelis

I've even made a Movie table and a MovieKind enum to make sure I was in the exact same configuration and naming conventions than the tutorial (which works fine)

**Comment by volkanceylan** [comment]
Case might be a problem. Try put your enum in Trelis.SomeModule. If MovieKind works and your enum doesn't you need to see what is different about your enum. If you don't add ScriptInclude or use enum somewhere it won't be generated. If it is in a different assembly it won't be generated.

**Comment by BravoSierra** [comment]
MovieKind (or any other Enum) works in MovieTutorial.MovieDB
and in my own project in
Trelis.Northwind
but not in
Trelis.trelis


That module Trelis.trelis works for everything I do except types declarations (It feels like T4 templates not browsing my trelis module for types déclarations!)

I do the rebuild solution and Transform T4 as often as possible.

So my project works just fine but with my Enums in NorthWind rather than in my own module!

Thanks to take all this time to answer and wish you a good week-end

**Comment by volkanceylan** [comment]
Don't use lowercase module name.

**Comment by ngocnb90** [comment]
![image](https://cloud.githubusercontent.com/assets/23022595/20052883/885d9bde-a508-11e6-8e6a-879b0d23bce5.png)
![image](https://cloud.githubusercontent.com/assets/23022595/20052909/aaacfb26-a508-11e6-8c1a-f62c498a86d0.png)

I tried but it not creat
