### ISSUE TITLE
search in navigation doesn't work

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1017]
hi guys, 

i'm not sure when exactly but my search in the navigation seems to have stopped working. the field is there in web page but search returns nothing, Any ideas?

Thanks, 

Abu

**Comment by volkanceylan** [comment]
Check browser console, some script might be failing

**Comment by abelal83** [comment]
Thanks for your reply as always Volkan.

I’m not sure why but it’s now working… no changes made on my server which is very odd. But I’m just glad it’s working!

**Comment by abelal83** [comment]
Hi Volkan, 

Looks like the problem has appeared again. No changes made at all either. This is the error in Chrome

morris.min.js:6 Uncaught Error: Graph container element not found
d @ morris.min.js:6
c @ morris.min.js:6
d @ morris.min.js:6
(anonymous function) @ dashboard.js:127
fire @ jquery-2.2.3.js?v=qsxD1vMI-jYqyF4_T7KzDA2:3187
fireWith @ jquery-2.2.3.js?v=qsxD1vMI-jYqyF4_T7KzDA2:3317
ready @ jquery-2.2.3.js?v=qsxD1vMI-jYqyF4_T7KzDA2:3536
completed @ jquery-2.2.3.js?v=qsxD1vMI-jYqyF4_T7KzDA2:3552

I'm no javascript person so any help is appreciated?

we are considering using serene for business purposes and ideally would like some form of premium support, is such thing available? We are happy to pay for it.

**Comment by jsbUSMC** [comment]
those browser console errors you've shared have to do with the dashboard JavaScript file, relating to the Morris chart scripts. They don't have anything to do with the navigation search, unfortunately.
