### ISSUE TITLE
Controlling Field Size and Other Questions

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#1018]
I have a form in which I have been able to size the fields (columns) the way I would like (figure 1). Also I would like to move some of the fields to the header section.

![screen_one_20160805](https://cloud.githubusercontent.com/assets/19471794/17448522/7244bb94-5b1a-11e6-941a-e4ee725e01f9.PNG)

But when I open the edit dialogs I can't seem to size the fields appropriately.  (figure 2).

![screen_two_20160805](https://cloud.githubusercontent.com/assets/19471794/17448566/a2eb1ab8-5b1a-11e6-979a-204279958593.PNG)

I'm thinking I'm going to have to write some HTML and CSS to achieve my desired results, unless I've missed some better, already built-in, Serenity commands.

If I need to write the HTML, where is the best place for this, in the .cshtml files. I don't want to break the already well working Serene functionality. The CSS will of course go in the appropriate .less file.

p.s. I've been reading that there have been massive changes, especially effecting the education personnel since the troubles from a week or two ago -- be safe and be wise.

**Comment by volkanceylan** [comment]
Thanks @mlutzow, i'm ok. Width attribute only works for grids. See multi column dialog sample and its css in basicsamples.less to design a multi column dialog. If you still want to make text boxes smaller, you should do it in css with max-width etc.

**Comment by mlutzow** [comment]
Good to hear. Thanks for the pointer, I was looking for a 'header' attribute or something to move some fields to the header section or one of my forms (both grid and dialog, if possible), is this doable through CSS?

**Comment by mlutzow** [comment]
@volkanceylan you've put together a very nice tool, so far I've been able to accomplish most everything I need with little effort (other than learning the toolsets) using the environment provided to me in Serenity. 

Thanks for you contribution (I'm still trying to find where I can place a couple of fields in the header (I've probably looked at it 100 times and don't even realize it)).

**Comment by volkanceylan** [comment]
I'm not sure what you mean by "putting fields in the header"
