### ISSUE TITLE
How can I personalize Serenity pages ?

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1019]
Is it possible to use the serenity to make a template like the one i attached ?
Or is it limited to the layout left menu and links ?

I'd like to use serenity to build apps because it is awesome and the support is great.

Keep up the good work.

**Comment by rolembergfilho** [comment]
Hey Bruno

you can follow the same idea from Dashboard Page, especially the buttons "Open Orders", "Closed Orders", etc...

and to call your page, follow the same idea than the "more info" link

**Comment by reybatacjr** [comment]
In addition to rolembergfilho regarding the left menu, you can create your own layout page under Views->Shared and you can mode the menu around or remove it totally and implement that to all your page.

**Comment by brunobola** [comment]
Thanks for the help guys, just one mode question, are there any plans to improve the layout of sergen ?

**Comment by rolembergfilho** [comment]
what are you thinking to improve?

For me, I'm thinking to check if this a foreing key, and if true, put the LookupEditor automatically (I'm thinking that is more easy to delete or comment undesired lookup than create a new one....)

And other feature is input a description of field in Placeholder. If description is long, input as a Hint.

and you, what yours idea?

**Comment by brunobola** [comment]
I've added a wiki sample: https://github.com/volkanceylan/Serenity/wiki/Layout-Improvements-%5BNotification-Icons-&-User-Personalization%5D
