### ISSUE TITLE
How do i add simple lookup from master table filter on certain criteria please help ?

### ISSUE THREAD

**Issue by amitk4net** [volkanceylan/Serenity#102]
[LookupEditor(typeof(DropDownListValue.Entities.LovRow))]
 public String InqFor
        {
            get { return Fields.InqFor[this]; }
            set { Fields.InqFor[this] = value; }
        }
i want filter on certain column from LovRow??

**Comment by volkanceylan** [comment]
Set FilterField and FilterValue properties.

**Comment by volkanceylan** [comment]
Reopen if it didn't help.

**Comment by amitk4net** [comment]
sorry volkanceylan it didn't helped me 

InquiryRow.cs

I have lov (list of value) table where Lov_Group,Lov_Value,Lov_Text
i have to filter LovRow on Lov_Group Criteria but it is returning null

	[DisplayName("Inquiry For"), LookupEditor(typeof(DropDownListValue.Entities.LovRow), FilterField = "Lov_Group", FilterValue = "Status")]
        public String InqFor
        {
            get { return Fields.InqFor[this]; }
            set { Fields.InqFor[this] = value; }
        }

Please help..

**Comment by amitk4net** [comment]
Hi,

How do i add one more level to Left menu i.e Global Master / Common Master / Company
and Global Master / Export Master / Item

[assembly: NavigationMenu(2000, "Global Master", icon: "fa-cube")]
[assembly: NavigationLink(2100, "Global Master/Common Master/ Company", typeof(JeenaLogistics.DropDownListValue.Pages.CompanyController), icon: "")]
[assembly: NavigationLink(2100, "Global Master/Export Master/ Item", typeof(JeenaLogistics.DropDownListValue.Pages.ItemController), icon: "")]

Please help.

**Comment by volkanceylan** [comment]
Add LookupInclude to group value text properties.

See AdminLTe multi level sample, and there was another discussion yesterday.
