### ISSUE TITLE
Deploy XML documentation files with Serenity Packages (working for intellisense)

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#1020]
Hey Volkan,

After your answer in #1005, I opened the serenity project to start writing XML documentation in Serenity methods, attributes, etc...

It's good to see what the target of these method, properties, attributes and all in Serene Template.

So, Serenity have XML documentation in method, but don't have XML generated when the project are builded.

I would like to suggest to activate Generate XML documentation file and deploy it with Serenity Packages.

To activate it, check the "XML documentation file" in Build Tab from Project Properties.

It'll be good for us!

**Comment by volkanceylan** [comment]
Hmm, i must have missed this detail. Thanks, i'll turn it on.
