### ISSUE TITLE
Odd issue with column width after publishing

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1022]
I have an odd issue, (maybe it's simple). I have a couple columns set [Width(500)], they work just fine until I add an http to https redirect rule in my web config. After that the css class changes for some reason and I loose my Width I set. here is my addition to system.webServer
`<rewrite>
    <rules>
	<rule name="HTTP to HTTPS redirect" stopProcessing="true"> 
	<match url="(.*)" /> 
	<conditions> 
		<add input="{HTTPS}" pattern="off" ignoreCase="true" />
	</conditions> 
	<action type="Redirect" redirectType="Permanent" url="https://{HTTP_HOST}/{R:1}" />
</rule>   
    </rules>
</rewrite>`

my CSS class BEFORE the change;
class="ui-state-default slick-header-column slick-header-sortable slick-header-column-sorted ui-sortable-handle

And AFTER the change;
class="ui-state-default slick-header-column slick-header-sortable ui-sortable-handle

Anyone know why the change would cause "slick-header-column-sorted" to disappear?
I removed the setting from web config and "width" works fine, I put the setting back in to redirect and it no longer works.

**Comment by volkanceylan** [comment]
I don't know how this is possible. slick-header-column-sorted is added for already sorted columns. Are you sure you are looking at the same exact column. And, sorted columns has no relation to width. I didn't understand why you had to write such a rule btw. You just need this redirect in login.

**Comment by jdready5** [comment]
Yes positive same columns (one that worked on my local, and one that didn't on my live site) and I didn't understand either and also didn't think it should've had anything to do with width, but it was the only thing different. Anyway, redirecting in login sounds like a much better idea anyway, I don't know why I didn't think of that (duh). Something like this I assume window.location.href.replace("http://", "https://");

Thank you by the way for helping, (even when the questions sometimes can be so elementary) it's very much appreciated.

**Comment by jdready5** [comment]
If I may ask another question off this topic...I am using firebird with a date field expecting MM/dd/yyyy. DateTimeEditor formats with hh:mm:ss included. I know how to change the display format but where do I change the format when inserts go to the DB? (for my sql query)

**Comment by volkanceylan** [comment]
You're welcome. I'm trying to help as possible, but sometimes people make it real hard with reports like "it doesnt work."
