### ISSUE TITLE
Moving Serenity Under /Admin directory of an application

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#1023]
I have frontend asp.net mvc application which uses Serenity As back-end

I would like to have it all in One Asp.Net Project

What would be best practice to achieve this?

I want user to browse the front end pages and go to Serenity Application when he switch with **/Admin**

Options thought: moving all Serenity Application Under Admin folder doing AreaRegistration?

Option 2: Deploying site as sub application in IIS but it would be difficult to manage images (uploaded from Front Application) from back-end application as path would mismatch

**Comment by volkanceylan** [comment]
You dont need areas, just change route attrs to Admin/.... Dont move endpoints, just page.cs

**Comment by samdubey** [comment]
Thanks got it
