### ISSUE TITLE
How to make a Report Page from scratch

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1024]
I want to make a summary report, which may use data from several tables and show it in a grid.

i do not want (require) CRUD capabilities in the grid.

how to achieve this without using sergen.exe

**Comment by rolembergfilho** [comment]
What about create a Vision from these tables?

About the CRUD, in the day that you'll need them, I think that the CustomLinksInGrid Basic Samples will fit for you.

**Comment by jsbUSMC** [comment]
You can create a custom endpoint method for your report, that calls on the respective services for the data you need. Also, you can look at the `DashboardIndex.cshtml` file, and see how the dashboard requests info from the DB in order to populate the info boxes at the top of the dashboard. You don't need to have full CRUD, but you should reuse the Read services for the endpoints in question instead of having to rewrite your own

**Comment by volkanceylan** [comment]
See how OrderDetail report works.

**Comment by mrajalko** [comment]
Thanks jsbUSMC for your insight. 

please guide me on how to add service.ts in ServerTypings.tt file without using sergen.exe

**Comment by mrajalko** [comment]
I have made changes in repository as under:

private class MyListHandler : ListRequestHandler<MyRow>
        {
            
            protected override void OnBeforeExecuteQuery()
            {
                base.OnBeforeExecuteQuery();
                using (var connection = ConnectionHelper.GetConnection())
                {
                    this.Response.Entities = (List<MyRow>)connection.Query<MyRow>("GetTollPointWiseCollection"
                            , null, null, true, null, System.Data.CommandType.StoredProcedure);

                }
            }

            
        }

but i am unable to avoid running of default query.

**Comment by volkanceylan** [comment]
Why are you using handler if you are gonna call stored proc. Fill response in repository method or endpoint method.

**Comment by mrajalko** [comment]
Thanks i have done that and it worked.

**Comment by mrajalko** [comment]
Can you please guide me on how to take user input ( 2 dates) and populate the report in grid.
