### ISSUE TITLE
Calculated fields in form - Data derived from cascading editors

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#1025]
Hi Community,

I would really appreciate if someone could point me in the right direction regarding the below. 

I am using cascaded editors (figure 1) to drill down to a specific SDR amount (figurure 2) in a table/grid. This amount corresponds to a 4th level of a drilldown (Category => Country => City = **SDR Amount**).

**Figure 1**
![image](https://cloud.githubusercontent.com/assets/15879719/17457427/92945b5c-5be7-11e6-8faa-e35c91a7b2f9.png)

**Figure 2**
![image](https://cloud.githubusercontent.com/assets/15879719/17457489/32e38ae6-5be9-11e6-8737-47423b3a9761.png)

The problem I am facing is regarding this SDR amount from the grid/table, **how to call that variable in the computational code** of the form where I multiply it with days (Vinnudagar)?

FYI - I will be using an On-Change event of a form field to trigger the calculations. I will include that in my xyzDialog.ts

Any ideas from you bright minds?

Regards,
Birgir

**Comment by volkanceylan** [comment]
You need to attach change event of your third lookup. Hope you use ID for that lookup, so you have ID 55 as its value by reading from Q.toId(form.BorgSkvRSK.value). Then you use YourSDRRow.getLookup().itemById[Q.toId(form.BorgSkvRSK.value)] to access its row. There you have standard field you need.

**Comment by biggikalli** [comment]
Dear Volkan,

Thank you for your kind answer and guidance - This however confirmed what I worried. 
I had already **tried your exact steps** in my zyxDialog.ts but **my problem** is that the City editor is **cascaded from it's Country editor** which is furthermore cascaded from the Category editor, therefore I have **seemingly long-lost the ID connection** of the row....or am I wrong?

If so, is there any lookup/search/match function I can use to find the ID of the corresponding line of the 3rd level drilldown or some _backwards_ script I can write and I can call from xyzDialog.ts to use in the change event?

OR do I have to rethink the cascading filtering so that the row's **ID** is linked to the City editor??

Hopeful regards,
Biggi

**Comment by volkanceylan** [comment]
You shouldn't have lost ID of any dropdown value unless you did lookups using distinct. Even in that case without ID at hand, you may call list service filtered by all three columns, or another option is to find matching row in your lookup, using Q.first(yourLookup.items, x => x.Country == ... && x.City == ... )

**Comment by biggikalli** [comment]
I unfortunately used distinct in my lookup for the cascading filters = I lost my ID of the dropdown value.
Therefore I tried your last suggestion of Q.first

It doesn't deliver the ID for my lookup table. The code section in my UtanlandsDialog.ts is now:

```
`            this.form.DestinationCountry.element.on('change', (e) => {
                var ID = Q.first(Stillingar.DagpeningarRow.getLookup().items, x => x.CountryId == this.form.CountryId.value && x.City == this.form.City.value).PerdiemId;
                if (ID != null) {
                    this.form.AmountSdr.value = Stillingar.DagpeningarRow.getLookup().itemById[ID].Standard;
                }
            });`
```

Would you be so kind to review this code snippet and tell me if I am on the right track?

Thanks Volkan.

**Comment by biggikalli** [comment]
Hi @volkanceylan,

I used distinct in my cascading lookups... :(

Therefore I have been trying your suggestion Q.first and this is my experimental code in xyzDialog.ts as is:

![image](https://cloud.githubusercontent.com/assets/15879719/17500432/0d7ff568-5dc5-11e6-9484-20f45a3b870f.png)

As you can see, Intellisense is going bananas over this snippet!
But my brower console doesn't show any error and runs my lookup as far as I can see although it results in "Else" of the if statement:

![image](https://cloud.githubusercontent.com/assets/15879719/17500423/f729ed50-5dc4-11e6-9c0a-875ea536f161.png)

Do you see anything (much) peculiar with the above? I think I have almost tried everything.

BTW. Here is my lookupscript:
`

    public class UtanlandsSDRLookup : RowLookupScript<PerDiem.Stillingar.Entities.DagpeningarRow>
    {
        public UtanlandsSDRLookup()
        {
            IdField = TextField = Stillingar.Entities.DagpeningarRow.Fields.PerdiemId.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Stillingar.Entities.DagpeningarRow.Fields;
            query.Distinct(false)
                .Select(fld.Standard)
                .Where(
                new Criteria(fld.PdCat) == "International" &
                new Criteria(fld.PdCat).IsNotNull() &
                new Criteria(fld.Category).IsNotNull() &
                new Criteria(fld.CountryId).IsNotNull() &
                new Criteria(fld.City).IsNotNull());
        }`

**Comment by volkanceylan** [comment]
try with this.form.Category.value not this.form.Category.this

Btw, you actually don't have distinct (as it has false param), i'm not sure why you can't get ID

**Comment by biggikalli** [comment]
Hi @volkanceylan ,

I am making progress in using this.form.City.**filter**Value, I am using cascaded filters, e.g. City (Borg) which has a distinct lookup (otherwise I would get 4 instances of each City in the dropdown)

Now I am getting this error in the browser console: Uncaught TypeError: Cannot read property 'Standard' of undefined. (Standard = the Decimal field I am trying to get)

![image](https://cloud.githubusercontent.com/assets/15879719/17524338/b000fc32-5e4d-11e6-88ca-f31687bfb332.png)


I know this is close as I am getting some ID from the Q.toId(Q.first()) syntax. Otherwise my ELSE part in the following code would trigger, which it doesn't:

`

            this.form.City.changeSelect2(e => {
                var SDR = Q.toId(Q.first(Stillingar.DagpeningarRow.getLookup().items, x => x.Category == this.form.Category.filterValue && x.CountryId == this.form.CountryId.filterValue && x.City == this.form.City.filterValue));
                if (SDR != null && SDR != 0 && SDR != -1) {
                    this.form.AmountSdr.value = Stillingar.DagpeningarRow.getLookup().itemById[SDR].Standard;
                }; {
                    this.form.ProjectManager.value = "SDR not defined!";
                }
            });`

Do you see what may be the problem here?

**Comment by volkanceylan** [comment]
@biggikalli 

First of all you should use .value not .filterValue

x => x.Category == this.form.Category.value && ....

Value for selects is a string, so if your fields are not strings, you may use Q.toId (if needed, i'm not sure your Category field is a string or integer)

x => x.Category == Q.toId(this.form.Category.value) && ....

Next, you used Q.toId in a very wrong place:

Q.toId(Q.first(.....))

here Q.first gives you an entity, not an ID, so you don't need to look anymore in itemById, or try to convert it to an ID. its already your SDR entity.

so

var sdr = Q.first(....);
this.form.AmountSdr.value = sdr.Standard

**Comment by biggikalli** [comment]
Hi @volkanceylan,

Thank you for getting me on the right track.
However, I just get the error: "first: No element satisfies the condition.!"... whatever I try.
I have tried 1-4 conditions without luck.
`

            this.form.City.changeSelect2(e => {
                var SDR = Q.first(Stillingar.DagpeningarRow.getLookup().items, x => x.Category == this.form.Category.value && x.City == this.form.City.value);
                if (SDR != null && SDR != 0 && SDR != -1) {
                    this.form.AmountSDR.value = SDR.Standard;
                }; {
                    this.form.ProjectManager.value = "SDR not defined!";
                }
            });`

There must be something wrong with:
`Q.first(Stillingar.DagpeningarRow.getLookup().items ...` because of the error "first: No elements satisfies..."

Any ideas?

**Comment by volkanceylan** [comment]
Your UtanlandsSDRLookup doesn't select category and city fields, so you can't filter on them clientside. That's why you have no results, as these fields are NULL. Select these fields.

**Comment by biggikalli** [comment]
Dear @volkanceylan 

As always, you lead the path for lost Serenists to their salvation.
It is finally working - thanks to your comments I was able to solve this issue and along the way, learn so much new but pretty basic things. 

You're a true Maestro :+1: 

Thanks again and have a great night.

Regards,
Biggi

Ps. For future reference/help in the forum and as per your helpful comments, my final **working** code is now as below:

**from my UtanlandsDialog.ts**
`

            this.form.City.changeSelect2(e => {
                var SDR = Q.first(Stillingar.DagpeningarRow.getLookup().items, x => x.Category == this.form.Category.value && x.CountryId == this.form.CountryId.value && x.City == this.form.City.value);
                if (SDR != null) {
                    this.form.SDRperDay.value = SDR.Standard;
                }
            });
`

**from my UtanlandsSDRLookup.cs**

`

    [LookupScript("Ferdir.UtanlandsSDRLookup")]
    [RegisterPermissionKey("General")]
    [ModifyPermission("General")]
    public class UtanlandsSDRLookup : RowLookupScript<PerDiem.Stillingar.Entities.DagpeningarRow>
    {
        public UtanlandsSDRLookup()
        {
            IdField = TextField = Stillingar.Entities.DagpeningarRow.Fields.Standard.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Stillingar.Entities.DagpeningarRow.Fields;
            query.Distinct(false)
                .Select(fld.Category, fld.CountryId, fld.City, fld.Standard)
                .Where(
                    new Criteria(fld.Category) != "" &
                    new Criteria(fld.Category).IsNotNull() &
                    new Criteria(fld.CountryId) != "" &
                    new Criteria(fld.CountryId).IsNotNull() &
                    new Criteria(fld.City) != "" &
                    new Criteria(fld.City).IsNotNull());
        }
        protected override void ApplyOrder(SqlQuery query)
        {
        }

    }
}`
