### ISSUE TITLE
SAAS app, tenants

### ISSUE THREAD

**Issue by papyr** [volkanceylan/Serenity#1026]
Hi, very nice, can you tell me how to support tenants, where _company A's_ managers cannot see _CompanyB's_ employees, so when looking at salaries etc.

thanks

**Comment by biggikalli** [comment]
Hi @papyr 

Have you looked at the guide regarding multi-tenancy in:
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/multi_tenancy.html

**Comment by papyr** [comment]
Hi @volkanceylan great code so - :+1: I tried to follow that, but the link was broken https://github.com/volkanceylan/MovieTutorial/tree/master/MultiTenancy

1. - Also I wanted to recommend a couple of security add-ins NwebSec for [ASP MVC Apps, single line of web.config protects the site.](http://bit.ly/2aP2LPf) open source
2. - Also, setting the default engine to razor speed up your site
3. - setting max POST http length prevents buffer overun DOS and brute-force attacks

thanks :)

**Comment by smartmeter** [comment]
ABP is more complicated but it has tenants and role to actions mapping built in https://github.com/aspnetboilerplate/aspnetboilerplate

**Comment by jsbUSMC** [comment]
Right now, Serenity uses FormsAuth and not Identity. You will have to add Identity to your project yourself.

**Comment by volkanceylan** [comment]
MultiTenancy will be rewritten. You don't need its code to follow tuturial though.

I don't know about NwebSec, but Serenity uses standard ASP.NET pipeline so you can integrate any library you like. There is a similar wiki article about CSRF attacks.
