### ISSUE TITLE
notifications and changes on data

### ISSUE THREAD

**Issue by papyr** [volkanceylan/Serenity#1027]
Hi, I know EF already has entity tracking, but its freakishly outdated and slow, for ReadOnly-Observable is there a way to hook up the table as a virtual list to the Database table and watch/subscribe to those changes. This would help dispatch toaster events to the UI.

Here is a gem https://tabledependency.codeplex.com/

**Comment by volkanceylan** [comment]
As long as you update your tables through services, you don't need to worry much about caching. But this looks like a useful library. I'll have a look. Last time i tried SqlDependency, it had a bad habit of failing suddenly along with all code that depends on it, so i couldn't trust on its stability and gave up. Hope they fixed issues.
