### ISSUE TITLE
Movie Sample does not have the multi tenant project from doc, and build issues with 4.6.1

### ISSUE THREAD

**Issue by smartmeter** [volkanceylan/Serenity#1028]
Hi, 

This is a really nice framework  :yum:  , and I was playing around and trying to update to latest, I had some issues.

- Can you please tell me how to get the multi-tenant sample, and when saving Business objects or Models, is it possible to use/get the default tenant from the current principal to save model in the DB records.
- Where is the role mapped to the action, and what if the user types the route/url to action directly, will this intercept and redirect to login.
- Is there a way to turn on audit table, for all records performed on the transaction, I can provide you with the SQL if needed.

Attempting to gather dependency information for multiple packages with respect to project 'MovieTutorial.Web', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for multiple packages.
Unable to resolve dependencies. `'Select2.js 4.0.3' is not compatible with 'Serenity.Web 2.4.2 constraint: Select2.js (= 3.5.1)'`

thanks

**Comment by jsbUSMC** [comment]
It's been put all over the place, but DO NOT UPGRADE SELECT2 TO 4.X.X

**Comment by volkanceylan** [comment]
Please try reading multi tenant tutorial first.

There is PageAuthorize attributes that redirects to login.

**Comment by smartmeter** [comment]
ok thanks
