### ISSUE TITLE
Saving the uploaded files into the database

### ISSUE THREAD

**Issue by aghanem** [volkanceylan/Serenity#1029]
Hi,
Is there any way to save the uploaded files in the database instead of saving them under App_Data folder ?

Thanks in advance!

**Comment by volkanceylan** [comment]
There is no integrated support for this. You may write your own behavior, taking existing behaviors as sample.

**Comment by aghanem** [comment]
Thanks,
Just took a clone of the source and I will check the ImageUploadBehavior class.
