### ISSUE TITLE
Can you add options to ToastrOptions, ProgressBar and CloseButton?

### ISSUE THREAD

**Issue by ycetin** [volkanceylan/Serenity#103]
Sir,
Can you add options to ToastrOptions, ProgressBar and CloseButton? or complete all toastr options import

![image](https://cloud.githubusercontent.com/assets/15701928/12291384/936cd90e-b9ef-11e5-9e57-135aa3079e0d.png)

thanks.

**Comment by ycetin** [comment]
thanks for

**Comment by volkanceylan** [comment]
np ;)
