### ISSUE TITLE
Add Editor programmatically

### ISSUE THREAD

**Issue by lubismargana** [volkanceylan/Serenity#1032]
Dear  Mr Volkan,

How to add control like Select Editor programatically?
Ex: I want to add control editor when I click button.
Thanks.

**Comment by volkanceylan** [comment]
Use Serenity.Widget.create(Serenity.LookupEditor, { element: e => e.appendTo(yourContainer), lookupKey: 'ABC' }) etc.

**Comment by lubismargana** [comment]
Thanks Mr Volkan,

but i used serenity 2.3.3 so i try 
 Serenity.Widget.create({
                type: Serenity.DecimalEditor, options: { minValue: "-9999", maxValue: "100" },
                element: (
                    e => e.insertAfter(tex)
                        .addClass("editor flexify")
                        .after("<div class='vx'/>")
                        .attr("name", "QL" + this.i)
                        .attr("id", "QL" + this.i)
                )
            });
          
and it solved.

Thanks very much.

**Comment by rolembergfilho** [comment]
@lubismargana,

could you post your full code of this?

It's good to learn too!
Thanks

**Comment by lubismargana** [comment]
protected updateContent() {
            
            Serenity.Widget.create({
                type: Serenity.StringEditor,
                element: (
                    e => e.insertAfter(**tex**)
                        .addClass("editor flexify")
                        .after("<div class='vx'/>")
                        .attr("name", "QL" + this.i)
                        .attr("id", "QL" + this.i)

                )
                , init: (w => w.addValidationRule(this.uniqueName, e => {
                    //Q.alert('jalan');
                    return "Jalan";
                })
                )
            });
            

    
            
        }

=tex> container

**Comment by rolembergfilho** [comment]
thanks!
