### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#1033]
1. first validation length is less mean the program execution stop after(f5) that show that alert message
i want only show alert error message only not code unhandle exception

if (password == null ||
                password.Length < Membership.MinRequiredPasswordLength)
                throw new ValidationError("PasswordLength", "Password",
                    String.Format(Texts.Validation.MinRequiredPasswordLength, Membership.MinRequiredPasswordLength));

**Comment by reybatacjr** [comment]
This only happens on developer environment. if you hit continue and check your browser the alert error message is shown.

**Comment by wdhodges** [comment]
If you run it in 'Release' versus 'Debug', the browser alert that @reybatacjr was talking about will be displayed without Visual Studio going into break mode.

**Comment by volkanceylan** [comment]
Use visual studio exceptions window to disable break on that kind of exception.

**Comment by GOBIBE** [comment]
tank u
