### ISSUE TITLE
Help required for Serenity

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1034]
Dear Sir,
I require help in two scenario
1. As per reference of developer guide  how to : Setup Cascaded Editors , i have created Tables and generated Code and make changes in all classes. then cascading works fine.
but when i created Lookup Classes seperately for Country, City & District, like CountryLookUp, CityLookUp and DistrictLookup and replace lookup editor in Person class to respective Lookup Classes.
Cascading doesn't work.
2. When u open any page, Grid tries to fetch Data from Server, can we prevent this fetching and make it available only when some button is pressed.
regards
Shailesh

**Comment by volkanceylan** [comment]
Override getGridCanLoad and return false if button not pressed.

Doesnt work, doesnt work for me.

**Comment by shaileshbc** [comment]
How we can use Lookup Classes and cascade Lookup Editors?
