### ISSUE TITLE
Translate DialogUtils.ts "Q.confirm('You have pending changes. Save them?',"

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1035]
This string should be available in the Translation section.

**Comment by volkanceylan** [comment]
Nope, it can't

**Comment by volkanceylan** [comment]
Oops, sorry i thought you expect strings inside code to be available.

**Comment by MaradiagaSistemas** [comment]
Hello, Is this feature available on 2.7.0? 

Thank you. :)
