### ISSUE TITLE
Submit a language pack

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#1036]
Volkan, what's the best way to submit a French language pack? Can I just email it to you?

**Comment by volkanceylan** [comment]
You can share a gist here, or open a pull request, but gist is easier.

**Comment by BravoSierra** [comment]
Done in a public Gist, please confirm if that is correct, thanks

**Comment by volkanceylan** [comment]
Could you share link to your gist please

**Comment by volkanceylan** [comment]
@BravoSierra i can't see your Gists
