### ISSUE TITLE
Paid support

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1037]
Just curious - Is a paid-support option available for this product?

**Comment by volkanceylan** [comment]
Yes, there is such an option, had a few such experiences. Also planning to offer premium subscriptions with private forum / e-mail / remote hands-on support etc.

**Comment by SimeonDD** [comment]
That's great Volkan!
About that new subscription option. Will it be available within weeks or months?
If "weeks", great. If "months" - please drop a line on how we can get in touch re payments etc.

**Comment by volkanceylan** [comment]
I'm not sure need to decide on payment provider and a system to hold registrations subscriptions. You may contact me in linked in.

**Comment by SimeonDD** [comment]
Cool. Thanks!
