### ISSUE TITLE
How are ValidationErrors handled

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1039]
For example, a ValidationError is thrown by a Module named Planes when user with no PermissionKey attempted to access it.
Is the code below the proper way to implement error handling?
```
[HttpPost]
        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            try
            {
                return new MyRepository().Create(uow, request);
            }
            catch (ValidationError)
            {
                // return error response
            }
        }
```

If so, how is the error response returned? What class can be used? still SaveResponse?(to show a custom error message in the ajax dialog box)

**Comment by volkanceylan** [comment]
I don't recommend handling anything. Anyway if you still want, you can do this way or do it in client side.

**Comment by john20xdoe** [comment]
If i did this way and want to show the ValidationError message to the client, how can I do that? Currently the page just shows the generic `Alert` with `(undefined)`

**Comment by john20xdoe** [comment]
Ah, I get it the ValidationError is automatically displayed in the ajax error box in the browser. I was running VS in debug mode so I was not able to see it appear. Running the solution in Ctrl-F5 allowed the form to show the ValidationError message. 

So really no need for a custom handling.
