### ISSUE TITLE
Restricted Data based on Current LoggedIn User

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#104]
Dear Volkanceylan,

Thank you very much for great App Template

We are using the App Template for developing an application hosted at http://knowtulus.azurewebsites.net/

We need to display data based on current user (technically filter data based on logged in user) for almost all the screens

please let me know how to achieve that

Thanks,

Sameer

**Comment by volkanceylan** [comment]
Please see multi-tenant tutorial in Serenity guide

**Comment by volkanceylan** [comment]
Reopen if it didn't help.

**Comment by zerodev** [comment]
@samdubey how did row level filter ended up with you , any examples where to start or sample implementation form what you did ?

**Comment by samdubey** [comment]
@zerodev I have completed row level filter successfully
I had referred Multi Tenant tutorial as suggested by @volkanceylan 
please let me know if you still having issue

we could have screen sharing session for more details
