### ISSUE TITLE
Error when adding data to table with 2 primary keys "Query affected 2 rows while 1 expected!"

### ISSUE THREAD

**Issue by smodallal** [volkanceylan/Serenity#1040]
Hi,

I tried to add new record to database table and I got the following error "Query affected 2 rows while 1 expected!". The table has 2 primary keys, when I added the first record its work fine but when trying to add the second record the error appeared.

The table structure as follow:
1- XId (Primary Key)
2- ImageType (Primary Key)
3- ImagePath

first insert was: 2, 1, "valid image path".
second insert: 2, 2, "valid image path"

Thanks,
Salam

**Comment by volkanceylan** [comment]
Put a proper ID in your table, or use composite ID.

**Comment by smodallal** [comment]
I already used composite ID and got the error "Query affected 2 rows while 1 expected!".

**Comment by smodallal** [comment]
Attached the table design screenshot
![table design](https://cloud.githubusercontent.com/assets/20921211/17509906/ffee26c6-5e24-11e6-9211-5333bbc889f5.JPG)

**Comment by volkanceylan** [comment]
What is your ID field in row

**Comment by smodallal** [comment]
ChequeId and ChequeImageTypeId.

**Comment by smodallal** [comment]
Sorry the ID field is ChequeId. How can I create composite Id for the ID Field.

IIdField IIdRow.IdField
{
    get { return Fields.ChequeId; }
}

**Comment by samdubey** [comment]
You should CONCAT both the ID as One in order to be seen as One
Hope this helps

**Comment by smodallal** [comment]
How to do this in Serenity?

**Comment by samdubey** [comment]
See Issue: #691

**Comment by volkanceylan** [comment]
See mapping guide for how fullname works, but better add a autoincrement id field to your table.
