### ISSUE TITLE
QuickFilter on Date Field programmatically

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1042]
When i use Quickfilter Attribute on date field then i get Date range for selection in Quickfilter.
But when i add quickfilter programmatically then i got only single date quickfilter.
![1](https://cloud.githubusercontent.com/assets/19570368/17542284/cede9528-5ee4-11e6-9f68-301db00d55b1.png)
Also would like to know how to set Date format of DateEditor programmatically.
regards
Shailesh

**Comment by volkanceylan** [comment]
Search for date in issues for format. Use addDateFilter for date range.

**Comment by shaileshbc** [comment]
I got addDateRangeFilter, thanks for that.
But when i try to format the date, it is not working.
for formatting date in quickfilter, i used 
QuickFilterOption("DisplayFormat","dd/MM/yyyy"), but it didn't work.
where as DateFormatter is working for Column Date Format.
how to set display format for QuickFilter.
regards
shailesh

**Comment by volkanceylan** [comment]
Which part of "Search for date in issues for format" you didn't understand exactly?
