### ISSUE TITLE
LeftJoin with Where statement (or Filterable dropdownbox)

### ISSUE THREAD

**Issue by sasinallatech** [volkanceylan/Serenity#1043]
Hi,

I am having the same issue as the previously closed Issue #818 , but the solution provided there is not working. 

I am having a table with following data,
ID	Name	Active	Description
1	Mill Drum 1	NULL
2	Motor	 0	NULL
5	TestEqu	 0	NULL
6	Testfine	 0	testedfine

I need only the Active rows to be displayed in the Dropdown.
I am using the following code,

[DisplayName("Equipment"), Column("EquipmentID"), NotNull, ForeignKey("[dbo].[tblEquipments]", "ID"), LeftJoin("jEquipment"), TextualField("EquipmentEquipmentName")]
        [LookupEditor(typeof(TblEquipmentsRow), InplaceAdd = true, FilterField = "EquipmentActive", FilterValue = true), LookupInclude]
        public Int64? EquipmentId
        {
            get { return Fields.EquipmentId[this]; }
            set { Fields.EquipmentId[this] = value; }
        }

        [DisplayName("Name"), Expression("jEquipment.[Name]")]
        public String EquipmentEquipmentName
        {
            get { return Fields.EquipmentEquipmentName[this]; }
            set { Fields.EquipmentEquipmentName[this] = value; }
        }

        [DisplayName("Equipment Active"), Expression("jEquipment.[Active]")]
        public Boolean? EquipmentActive
        {
            get { return Fields.EquipmentActive[this]; }
            set { Fields.EquipmentActive[this] = value; }
        }

Still nothing is appearing in the dropdown.

**Comment by volkanceylan** [comment]
Add lookupinclude in your equipment row, not the row you are using editor on. Also filterfield is the field name in your equipment row not the row you are using editor on.....

**Comment by sasinallatech** [comment]
Thank You so much. This works :)

**Comment by pebarradas** [comment]
sasinallatech, I've same problem, can you describe how do you resolved?

Thank you!

**Comment by pebarradas** [comment]
thanks, I've already resolved.
