### ISSUE TITLE
Showing Report in Grid using Stored Procedure

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1044]
I have recently tried to show a report in the grid using a stored procedure. I have with your help called the stored procedure in repository and filled the data and shown it in the grid.

I want now to achieve a real life scenario where initial data is populated using default values of parameters passed in the stored procedure and user is given the option changing any of the parameters and the result shown in the grid is repopulated based on user input.

Kindly guide me how to achieve this.

**Comment by volkanceylan** [comment]
I don't have sample for stored proc, sorry. See source code for custom data source, e.g. VSGallery sample.

**Comment by SimeonDD** [comment]
Hi Volkan,
do you plan to include MRajalko's demo for using an SP?
If not, MRajalko, do you mind helping with some guidance/code on how to achieve this?
Many thanks!!

**Comment by SimeonDD** [comment]
Never mind guys,
Just found the issue #128 and got my answers there.
Many thanks!
