### ISSUE TITLE
Add sample in serene

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#1046]
Hey @volkanceylan,

I think that's a silly or fool question for you, but let's go...

can I submit some sample in dev.Serene?

I would like to start with #1021

If it's ok, i'll try to submit other samples (div, qtip, placeholder, hints and more)

I think that's important because I had some difficult in begin with these things. So, maybe it'll be good for new developers.

**Comment by mrajalko** [comment]
Hey @rolembergfilho,

can you please guide me how to have two date inputs on a page and a refresh button and on click of button repopulate the grid.

I am planning to move the grid in a partial page refresh that partial view in button click event.

do you think that i am on correct path.

can you please give some hints in how to achieve this feature.

**Comment by rolembergfilho** [comment]
In question about date, did you try put "QuickFilter" attribute in columns.cs of your solution ?

I know that endpoint you can give " ListRequest request" parameter (it's where the date criteria is informed to Serenity core)


I tried to do it in VSGallery, but I don't have advanced skills to set it in match or filtered lines...

**Comment by volkanceylan** [comment]
Hi @rolembergefilho. Sure you can, just send a pull request with your sample. I'll check and integrate it. Thanks.

**Comment by rolembergfilho** [comment]
Thanks @volkanceylan. I'll try do it this weekend

@mrajalko, is my suggestion fit you?

**Comment by mrajalko** [comment]
@rolembergfilho no. I am not trying to filter records on a give table, but trying to present reports (summary or detail) based on different criteria (like date range etc.)

I am planning to have stored procedures for back end data delivery and i would use data table in place of slick grid.

let me build a sample page then i would share the details with you.

**Comment by mrajalko** [comment]
Hey @volkanceylan. I have just submitted a new pull request with some a new page added in serene sample which uses stored procedure.

please see if you could use them in next release.

please guide me if I have done some mistakes.

**Comment by volkanceylan** [comment]
Sorry for late reply but cant see your pull request. Where did you sent it?

**Comment by mrajalko** [comment]
Since i have added some sample in serene therefore i have in serene

![image](https://cloud.githubusercontent.com/assets/18166582/17961563/2829d5de-6aca-11e6-8b68-ba75575581ab.png)

**Comment by volkanceylan** [comment]
Hmm you have sent pull request to yourself. But np, i'll merge it somehow, thanks.

**Comment by mrajalko** [comment]
sorry i am a novice in this.
please guide me how to send so that i don't make same mistake again.

i have given a sql script to create the procedure being used. rest are following same nomenclature therefore u can just add them in those folders.

**Comment by mrajalko** [comment]
hey @volkanceylan have you been able to merge my version.

can you please guide me how to have a date range applied on the grid and repopulate it after user input.

**Comment by mrajalko** [comment]
please guide me on how to customize 

protected createQuickSearchInput() {
            super.createQuickSearchInput();
            return;
        }

to add a daterange input in place of quick search input and have its value captured in repository.

**Comment by volkanceylan** [comment]
Method name is createQuickFilters. Use addDateRangeFilter. OrderGrid already has it server side with [QuickFilter]

**Comment by mrajalko** [comment]
Dear @volkanceylan,

I do not have date field in the grid the data is to be again repopulated based on date range as user input.

![image](https://cloud.githubusercontent.com/assets/18166582/18082854/465d07a4-6ebe-11e6-8f8f-845f8fa8769d.png)

![image](https://cloud.githubusercontent.com/assets/18166582/18082944/9e306372-6ebe-11e6-92c8-179e519142bf.png)

**Comment by mrajalko** [comment]
added a new sample page using datatable in place of slick grid.

![image](https://cloud.githubusercontent.com/assets/18166582/18086012/725802c0-6ecb-11e6-86f2-49b54a2e782f.png)


please guide me how to upload the source files correctly so that you can merge with serene sample.

also if possible kindly guide me whether i could have done same using slick grid or not.

**Comment by volkanceylan** [comment]
Please share stored procedure code with date range, and how you call it in repository.

I'll add date range filter myself, in slickgrid.

**Comment by mrajalko** [comment]
It is being used in datatable sample.

![image](https://cloud.githubusercontent.com/assets/18166582/18090798/141eb1c2-6ee4-11e6-8b10-c8350e80c479.png)


already shared in a pull request.

if you want i can share the entire code on my google drive and send you a link.

**Comment by volkanceylan** [comment]
Create Procedure CustomerWiseGrossSale
As
Begin
	Select A.CustomerID,C.ContactName,D.ProductID,P.ProductName 
	,GrossAmount = Sum(D.UnitPrice * D.Quantity)
	from Orders A
	Left Outer Join Customers C on C.CustomerID = A.CustomerID 
	Left Outer Join [Order Details] D on D.OrderID = A.OrderID 
	Left Outer Join Products P on P.ProductID = D.ProductID 
	Group by A.CustomerID,C.ContactName,D.ProductID,P.ProductName 
End

Your stored proc is this and it has no date range filter

**Comment by mrajalko** [comment]
Create Procedure [dbo].[PeriodicCustomerWiseGrossSale]
@BeginDate Date,
@EndDate Date
As
Begin
	Select A.CustomerID,C.ContactName,D.ProductID,P.ProductName 
	,GrossAmount = Sum(D.UnitPrice * D.Quantity)
	from Orders A
	Left Outer Join Customers C on C.CustomerID = A.CustomerID 
	Left Outer Join [Order Details] D on D.OrderID = A.OrderID 
	Left Outer Join Products P on P.ProductID = D.ProductID 
	Where A.OrderDate Between @BeginDate And @EndDate 
	Group by A.CustomerID,C.ContactName,D.ProductID,P.ProductName 
End

GO


used in datatable sample

**Comment by volkanceylan** [comment]
I don't see your datatable sample

**Comment by mrajalko** [comment]
shared on google drive.

https://drive.google.com/file/d/0Bxfv9QANhXyKcWVBd3NOTnFXbmM/view?usp=sharing

**Comment by mrajalko** [comment]
https://github.com/volkanceylan/Serene/pull/25

the pull request.

**Comment by mrajalko** [comment]
waiting for your response on the sample and my question whether i could have achieved same functionality using slick grid or not.

**Comment by volkanceylan** [comment]
Added in 2.4.4.2, thanks
