### ISSUE TITLE
Validating deletion in a single registry

### ISSUE THREAD

**Issue by Isofff** [volkanceylan/Serenity#1047]
In a table, when opening a single registry for edit, I'm trying to validate use of the Delete button, preventing its use if a certain bool field on that same registry is inactive.

I found an example for validating the Save button in UserRepository, but I cannot find something similar for Deletion. How would I got about doing this?

**Comment by rolembergfilho** [comment]
Good night.

In Dev.Serene, you can check the NotesBehavior.cs. You will find a method below
 **public override void OnBeforeDelete(IDeleteRequestHandler handler)**

To check what method are available to use, see the file **BaseSaveDeleteBehavior.cs**, located in Serenity.Services

**Comment by Isofff** [comment]
Thank you,  I implemented something similar using the methods listed as an example.

Have a nice day.
