### ISSUE TITLE
How to limit the length when entry in an editForm?

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1048]
Hi , Nice to see you again!

![image](https://cloud.githubusercontent.com/assets/20295114/17580435/30bfea0c-5fd1-11e6-8166-6cd2d4371a2e.png)

in the picture , when someone entry the content , if the length beyond a number which I  set , how to show a alert or some message immediately and not until out of  focus ?

**Comment by volkanceylan** [comment]
Set maxlength, if not working for you see jQuery plugins and samples for these.

**Comment by weiguanhai** [comment]
Ok, it works perfectly!  sincerely thank you!

**Comment by weiguanhai** [comment]
But I have a new trouble ,  You know , chinese is two characters , but the letter is only one characters . How can I do?

**Comment by weiguanhai** [comment]
But I have a new trouble ,  You know , chinese is two characters , but the letter is only one characters . How can I do?

**Comment by weiguanhai** [comment]
Use MaxLength().  chinese count one characters . What Can I do?

**Comment by weiguanhai** [comment]
Can I  override this , Or  I wrote  something like this in dialog
![image](https://cloud.githubusercontent.com/assets/20295114/17657092/43c247d8-62f3-11e6-8ca6-b65163cbe285.png)
But I hope it is not util the text change ,  If can, I wish it can immediately show.
And Now,  It use 'alert' , Can it be like this picture instead of a alert dialog?
![image](https://cloud.githubusercontent.com/assets/20295114/17657202/c5590cc8-62f3-11e6-84d8-1bd16536dc47.png)

**Comment by volkanceylan** [comment]
use addValidationRule

**Comment by weiguanhai** [comment]
use addValidationRule ? it trigger , when I  click saveButton?
