### ISSUE TITLE
MyListHandler Filter with INNERJOIN

### ISSUE THREAD

**Issue by sasinallatech** [volkanceylan/Serenity#1049]
Hi,

I am trying to to do a Filter in MyListHandler overriding ApplyFilters. It works when the filed is in the same table. Can you provide an example on how to filter with a Foreignkey in another table?

Thanks in advance.

Nalla

**Comment by volkanceylan** [comment]
Add that field to your row as a mapped view field, than you can filter on it normally

**Comment by sasinallatech** [comment]
This works. Thanks.

**Comment by ANDY7575** [comment]
@sasinallatech  dude im facing same problem please share ur solution.
