### ISSUE TITLE
How to await when multiple service call simultaneous?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#105]
Service calls run async but i want to run with "await" until method complete.

My code:
```
List<item> items = new List<item>();
items.add(item1); //added 1


SomeService.List(request, response =>{
foreach(var r in response.Entities){
items.add(r.item); // added 2,3,4,5,6

SomeService2.List(req, response2 =>{
foreach(var r2 in response2.Entities)
item.add(r2.item); // added 10,20,30

}
}

});
```

I want result list like that: 1,2,10,20,30,3,10,20,30...
Bu actual result is: 1,2,3,4,5,6,7,10,20,30,40,10,20,30,40

**Comment by volkanceylan** [comment]
You can simply call Service2 on success callback of first service call. Another option is to set async false in service call options.

**Comment by ademc** [comment]
Actually I have another loop outs'de th's code block w'thout serv'ce call/ Because of this first option is not solve my problem. But second option is right (and so easy) solution. thanks
