### ISSUE TITLE
Multi Line Header in Grid

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1050]
how to have multi line header in a grid and a merging of two or more columns in first line of header.

**Comment by rolembergfilho** [comment]
Maybe you can do the same idea that explained in **Grouping and Summaries in Grid** located in Basic Samples > Grids

**Comment by mrajalko** [comment]
found Implemented in http://github.com/mleibman/SlickGrid/commit/19624f6687a0d2671639c4b1f2c05eb20c9ab0c7

but converting it to our sample is a major task.

can someone please guide on how to achieve this.

**Comment by mrajalko** [comment]
I am thinking of switching to datatables in place of slick grid but implementation of grouping is not good in datatables what is your view on this.

**Comment by volkanceylan** [comment]
Sorry that feature is not supported yet.
