### ISSUE TITLE
Dev.Serene missing CsQuery dll reference (VSGallery sample)

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#1052]
Hey @volkanceylan 

I don't know if it was a problem in my local copy, but Dev.Serene.csproj missing CsQuery dll, which is necessary to run VSGallery sample.

And I had to include VSGallery folder with files. I don't know if is necessary to include the "VSGalleryQAThreads.v1.deflate" too.

So, would you see if my doubt is correct?

**Comment by volkanceylan** [comment]
Hi @rolembergfilho,

You are right, it should have that reference, but i'm usually working in Serene.csproj while adding samples / releasing VSIX, and Dev.Serene.csproj while working on new features. So i am manually merging changes in either with Winmerge. They may go out of sync sometimes, if i forget.

**Comment by volkanceylan** [comment]
Merged now thanks.

**Comment by volkanceylan** [comment]
VSGalleryQAThreads.v1.deflate shouldn't be included. I only put it there for it to be available from GitHub. Otherwise that sample would have to fetch all pages from VSGallery, which would be terribly slow.

**Comment by rolembergfilho** [comment]
In really, it's slow only in first Postback, like classic ASP.NET. But after this, the page runs quicky, both search and page navigation.

In other way, I understand that this example is a extreme external datasource, so I expected some slow.

For me, it's good!
