### ISSUE TITLE
Referencing FK columns - some renaming needed after SERGEN

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1053]
This is not a bug but it has to be mentioned.

In short: 
After importing a main table and a type table referenced by the main table I noticed that some manual renaming is needed for the main table to be able to make the controls show the type value and not the type ID.

Key:
SERGEN creates in MainTableRow.cs two entries like [DisplayName(...
1. One for the TypeID column itself "public int32 TypeId ...."
2. One for the referenced field from the type table "public String TypeName...."
However the generator picks a new name for the field that does not match the column name of the TypeTableRow.cs

It seems the generator's convention is to concatenate the table name to the field name.
So if TypeTableRow.cs has Get/Set for "public String TypeName" the generator creates "public String TypeTableTypeName" in MainTableRows.cs (the table that references the type).

Same for the classes in ServerTypings.tt

You just have to refactor the auto-generated field (Table name + Field Name) to be the same as the one used in the TypeTable (in this case "TypeName").

Then all will work.

Again - not a bug. I can totally imagine why this happens.

FYI:
This is what I did to make the ID column show as a dropdown:
1. Did the above renaming.
2. ServerTypings -> MainTableForm.ts -> Replaced the auto generated TypeId Serenity.IntegerEditor with Serentity.LookupEditor
3. ServerTypings -> TypeTableRow.ts -> added a getLookup() function.
4. Module -> MainTableForm added [LookupEditor ...] statement right above the column definition for the TypeID (this is what will make the Type-Name appear instead of the ID col)
5. Module -> TypeTableRow.cs -> added on top  [LookupScript("TestModule.TypeTable")]

Rebuilding created all needed code in Web.js and all grids and editors behaved fine.

**Comment by wldkrd1** [comment]
As a warning, transforming the T4 templates later will probably wipe out your fix.

**Comment by volkanceylan** [comment]
You shouldn't modify any generated files as @wldkrd1 specified. Sergen doesn't create lookup editors on FKs. It might be possible, though requires inspecting your code / DLL for LookupScript attributes, which Sergen doesn't do at the moment. 

TextualField attribute determines the related text field a FK should display as title. It's set to first string field from that table.
