### ISSUE TITLE
MultipleFileUploadEditor - deleting files

### ISSUE THREAD

**Issue by DavidHallEP** [volkanceylan/Serenity#1054]
Hi,
Can you tell me why some files are able to be deleted and some are not when using the MultipleFileUploadEditor 

You can see the first two items have the red cross, but the last two do not.

![2016-08-12 09_27_37-surgical preference cards](https://cloud.githubusercontent.com/assets/20979887/17608327/1eb0e502-606f-11e6-811a-ed9901af259e.png)

**Comment by marcobisio** [comment]
It's only a css issue: the files that "cannot" be deleted have a filename too long that "hide" the red cross.
I've solved with the following lines of css:

    .file-item .filename {
        position: relative;
    }
    
    .s-MultipleImageUploadEditor li .delete {
        position: absolute;
        top: 0px;
    }

don't know if it's the best approach, but it works!

Bye

**Comment by volkanceylan** [comment]
Thanks @marcobisio

**Comment by marcobisio** [comment]
You're welcome @volkanceylan

**Comment by DavidHallEP** [comment]
Thanks, that sorted out the issue! perhaps a future enhancement would be to truncate the displayed file name as it does look a little messy, but otherwise all good.
