### ISSUE TITLE
Confirm the entry value through the database in the editForm

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1055]
Hi , So nice to see you !
U know, when I  add or update  data in the editForm,  Can I validate the  row's value 
![image](https://cloud.githubusercontent.com/assets/20295114/17610662/b71a7d1e-6072-11e6-9bdc-89fe995275f3.png)

Such as , use the entry value query the other table of the  database  ,  "select name from user where account = " add the entry  value .  If  the query result is empty ,  then interrupt  the operation and give a warn,such as a dialog
.  
As for the confirm time ,  maybe when I click the save button , If when the edit row out of focus , that is no   better than it.

**Comment by volkanceylan** [comment]
attach to change event, call your service, focus field, show error, whatever.

**Comment by rgilsimoes** [comment]
Can anyone provide a sample for this? I would also appreciate!
