### ISSUE TITLE
Newtonsoft v9 compatibility

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#1058]
I have created a test app with the latest version 2.4.3.0, I then updated all the nugget packages except for selectjs2 and rebuild and run the app which runs fine, however when I transform the t4 templates it produces an error that Newtonsoft V8 cannot be found. I assume I need to update a reference somewhere, any ideas? The offending line is "Serenity.JSON.Parse[T](String input)" but I don't know where to find or fix this.

**Comment by wldkrd1** [comment]
To get it to work with v9, you need to add an assembly binding redirect in devenv.exe.config. Probably not worth it and not exactly portable to other developers on your team/build machine.

**Comment by RouteTech** [comment]
Ok Thanks.
Just to sure, it's both selectjs2 and Newtonsoft V9 that I don't update.

**Comment by wldkrd1** [comment]
Select2.js, Newtonsoft, jQuery.UI.Combined and jQuery should not be updated.

**Comment by RouteTech** [comment]
Hi,
I have made a simple Excel Import that will take an Excel sheet and import
it into a Serenity table. I called it a wizard (although it's not yet) to
avoid naming issues. It's a stripped down version of a generic importer I
wrote that may be useful . The files are attached to this email in zipped
format.
I am sending them to you this way so that you can "Serenetize" them and
post them according to your specifications. There are a number of methods
that I'm sure you have better hooks for than what I did.

I hope this helps,
Trevor
