### ISSUE TITLE
Lookup Editor Works Except for non-lookup field Display

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#1059]
I have a Lookup Editor on a field that works flawlessly, almost. The LeftJoin attribute brings the looked up field over and displays in all cases, but the 'id' (Division) field does not display. I'm sure I simply missed something rather basic, any help would be appreciated.

Example Images:
![lokupfield_1_20160812](https://cloud.githubusercontent.com/assets/19471794/17636821/42eb4710-60a5-11e6-8c24-b5c6bee85e78.PNG)

![lokupfield_2_20160812](https://cloud.githubusercontent.com/assets/19471794/17636823/47b0bee2-60a5-11e6-8d80-a66151d0a4b2.PNG)

![lokupfield_3_20160812](https://cloud.githubusercontent.com/assets/19471794/17636825/4aefcd1e-60a5-11e6-8d23-a4a3bb9cea7d.PNG)

The Code I'm using is below;

````
//...
[LeftJoin("jProd", "[budgets].[refProducts]", "T0.Company_Code = jProd.Company_Code AND T0.Product_Code = jProd.Part_Code")]
[LeftJoin("jDiv", "[budgets].[refDivisions]", "T0.Company_Code = jDiv.Company_Code AND T0.Division = jDiv.Division")]

//...

public sealed class RevenueSumAndPeriodsRow : Row, IIdRow, INameRow
    {
        [Category("Organization Info")]
        [DisplayName("Division"), Column("Division"), Width(65)]
        [LookupEditor(typeof(refDivisionsRow)), LookupInclude]
        public String Division
        {
            get { return Fields.Division[this]; }
            set { Fields.Division[this] = value; }
        }

        [DisplayName("Division Name"), Width(115)]
        [Expression("jDiv.DivisionNameShort"), LookupInclude]
        public String DivisionNameShort
        {
            get { return Fields.DivisionNameShort[this]; }
            set { Fields.DivisionNameShort[this] = value; }
        }
//...
````

**Comment by volkanceylan** [comment]
Sorry couldn't understand what you mean

**Comment by rolembergfilho** [comment]
@mlutzow, I think that you generated your classes wrong.

please, do this checklist:
1 - whats your namespace name? For these examples, Let's premise if your XYZrows.cs namespace is like below
**namespace PROJECTNAME.budgets.Entities**

2 - Are your tables have Primary Keys? Are they Int?
If don't, let's create Primary Keys, with Int datatype, and set it Identity.

3- change your [LookupEditor(typeof(refDivisionsRow)), LookupInclude] by code below:

        **[LookupEditor(typeof(budgets.Entities.refDivisionsRow), InplaceAdd = true)]**

3 - Check if your refDivisionsRow class fits these checklist above

4 - in your refDivisionsRow class, check your ID and Name fields. These should be like below:

        #region Id and Name fields
        IIdField IIdRow.IdField
        {
            get { return Fields.DivisionID; } //primaryKey, int, identity
        }

        StringField INameRow.NameField
        {
            get { return Fields.DivisionNameShort; }
        }
        #endregion Id and Name fields


Please, advise us it this checklist helped you!

**Comment by mlutzow** [comment]
Let me explain this a little clearer, by the way, thank you for your help.

All tables have Primary Keys of type int, identity defined at the table level. These Primary Keys are unrelated to the data except when used as a Foreign Keys in other tables. The reason for this are several, primarily because in the source system that this program must eventually interface with, virtually all of the fields (especially those that I would prefer to use as Key Fields) are defined as a string (usually nvarchar) of varying lengths.

@rolembergfilho, the program namespaces are defined correctly, the change for the Lookup editor you recommend produces messages that the qualifier is redundant and to simplify the name (in addition, I've used ENUMS that I've setup and they work well with the namespace setup).

Hopefully, a better definition of the issue: 

What I have are two tables, table1 contains the data, table2 is equivalent to refDivsions - a lookup table.

Table1 and table2 both contain the field Division defined as string(2). Table2 contains the Division description(s).

The Division Descriptions are being brought over just fine and this part works well. However the 'dropdown' portion that should contain the field Division is not populated.

I'm thinking I'll need to just set the field default to be the value of current field, if that's possible unless I've missed something else.

**Comment by mlutzow** [comment]
Working with the Select2 I've noticed another issue.  The LeftJoin works but when I attempt to use the Select2-Drop, the value that that is being populated is the incorrect field. It is not aThe Primary Key or is it included in the Join Property, very Strange.

The image below shows the customer name which is an expression that concats the customer number and the customer name, the data is being pulled correctly. But the drop down list contains a list of '1', which is incorrect. This, I believe is being pulled from the Company_Code field, incorrectly.

The definition of the two fields is immediately below the image.

![lokupfield_1_20160815](https://cloud.githubusercontent.com/assets/19471794/17674096/afe92ecc-62e9-11e6-82bb-6b9db60a2530.PNG)

```
`
[Category("Budget Items"), Width(100)]
        [DisplayName("Customer Number"), Column("Customer_Number"), Size(8)]
        [LookupEditor(typeof(refCustomersRow))]
        [ForeignKey("[budgets].refCustomers", "Customer_Number"), LeftJoin("jCust")]
        [LookupInclude]
        public String CustomerNumber
        {
            get { return Fields.CustomerNumber[this]; }
            set { Fields.CustomerNumber[this] = value; }
        }

        [DisplayName("Customer Name"), Width(250)]
        [Expression("jCust.Customer_Number + ' - ' + jCust.Customer_Name"), LookupInclude]
        [SortOrder(1)]
        public String CustomerName
        {
            get { return Fields.CustomerName[this]; }
            set { Fields.CustomerName[this] = value; }
        }

`
```

**Comment by volkanceylan** [comment]
Your lookups use your name field in row by default, if you have it set to CustomerCode, it show customer code.

**Comment by mlutzow** [comment]
I understand, So I should be changing the Name field. Okay, is there a way to override this behavior at the left join, or there-abouts or is my only option changing the name field?

Thank you!

**Comment by volkanceylan** [comment]
It's not about LeftJoin, its about your refCustomersRow

**Comment by mlutzow** [comment]
I understand that it's not about the left join. For this purpose and table, refCutomers, there would be no need to change the name field. The whole process (SERENE) is making more sense to me and how the various pieces are working, I can anticipate with some other tables were what I've currently set as the name works for one function but I would need to reference a different text field for something else. Hopefully by the time I encounter those situations I've gotten to a point where it won't be an issue, but can the name field be overridden or reference a different field if necessary? Then again the whole question might be a moot question.

**Comment by mlutzow** [comment]
I'm still having the initial issue where when I drill into the dialog form, the Select2 dropdown list is empty, even though the field that the select2 is bound to and references is populated with valid data.

Have I missed something?

**Comment by rolembergfilho** [comment]
@mlutzow, could you upload your 2 class (RevenueSumAndPeriodsRow  and refCustomersRow?

I think

To change the description of your dropdown list, locate the property **StringField INameRow.NameField**, and change the field to your desired field

Example: try to set NameField to these lines below

    **StringField INameRow.NameField
    {
        get { return Fields.DivisionNameShort; }
    }**

tips and tricks: you can use the same idea of FULL NAME field (explained in Serenity GitBook: https://www.gitbook.com/book/volkanceylan/serenity-guide/details) and change NameField to get this new calculated field.


but please, upload your classes.

**Comment by mlutzow** [comment]
@rolembergfilho, thank you for taking the time to review this for me. The GIST can be found at: [https://gist.github.com/mlutzow/20282805c4f4b6421ea2bf266c5ab18c](url).

I've read the manual, and have reviewed certain parts of the manual multiple times. I'm able to get the 'dropdown', joins, and view fields working fine. When I drill down into the dialog form (click on an 'EditLink') the initial display of the Select2.Dropdown before actually activating the dropdown list (the current field display for the record) is empty although the field is populated with valid data. 

![lokupfield_2_20160815](https://cloud.githubusercontent.com/assets/19471794/17680546/4845ecb6-6306-11e6-80b3-f3fa2ecf208a.PNG)

**Comment by rolembergfilho** [comment]
your gist link returned error 404( not found) ....

**Comment by mlutzow** [comment]
See if this works better:

https://gist.github.com/mlutzow/20282805c4f4b6421ea2bf266c5ab18c

**Comment by rolembergfilho** [comment]
worked, checking it

**Comment by mlutzow** [comment]
Okay, I give up on this, obviously the dropdown can't be populated with the correct information. I've tried the examples from the Northwind Products form, the Movies Tutorial, I guess it can't be done.

**Comment by rolembergfilho** [comment]
Hey @mlutzow, In really I promised you that I'll check your codes.

Unhappilly I needed to leave my children to hospital and now i'm looking them all time (flu and earache). So, appologize me. I can't do it.

I'll ask you a thing: did you check the last serenity deploy? The Sergen has a property to generate lookup editor automatically.

But check if your code have LookupScript in class.


I hope that your problem will solved.

see ya

**Comment by mlutzow** [comment]
@rolembergfilho, No Problems with you at all. Your family and especially your children are definitely first on the priority list. Praying that they get well quickly.

It's I'm more frustrated with myself for not being able to get this thing to work. I've followed all the samples that I can find and still no joy.  I'm probably going to be offline most of next week because I'm attending an accelerated training course on most of the tools that I need to know to get this and future projects completed. The only thing not covered in-depth is the JavaScript / JQuery and Typescript but I'm picking those up on my own.

I think I'm going to just roll the changes I've tried back to the point of were I was at before I tried to get the dropdown list working and start over (on the dropdown).

I generally apply updates for the Serenity framework when they are rolled out. I'd rather not regen the forms for this table because I've already done a tremendous amount of work to them. Maybe I'll create an alternate form and work from there, I don't know.

Take care of your children.

Thanks.

**Comment by rolembergfilho** [comment]
Hey @mlutzow 

Try it: download a new Serene Template and use it like a SandBox (for test and experiment).

Run last updated Sergen and generate these files in the download Serene Template.

**Comment by mlutzow** [comment]
@rolembergfilho:

generated a test form with the Serene 3.4.4 template version, I've noticed the change with the field definitions in the ...row.cs field and the added LookupScript option if selected.

I'm curious what surrounding every field with a #region brings to the table? I think I like the idea, but I'm curious how I can use the feature, perhaps in CSS or TypeScript, JavaScript, etc.
