### ISSUE TITLE
Multiple LookupEditor attributes for same entity in different fields

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#106]
@volkanceylan , once again I gotta give you the most heartfelt thanks for a wonderful project template and application! I have an issue and am wondering how to implement a solution. I have a table which sets a foreign key relationship to the user's table, and on the User table and the one I'm using I have successfully implemented the `[LookupScript("XYZ.User")]` on the default `User` table, and a `LookupEditor("XYZ.User")` in the `MyModelRow.cs` class that has the foreign key. The problem I have, however, is that I need the user to be able to select the names of other users in the same table, using a dropdown selection. In this regard, I added `[LookupEditor("XYZ.User")]` attributes above each field, and the dialog will display correctly the dropdowns for user selection. However, when trying to change the `MyModelColumns.cs` to display the usernames of the selected users instead of the Int32 Id, I receive an error from IntelliSense: MyModelColumn.cs already contains a definition for String AnalystDisplayName. Is there a different/better way of accomplishing this?

**Comment by volkanceylan** [comment]
I guess you have database columns like AnalystId, DesignerId etc. in row right? And you should have AnalystDisplayName, DesignerDisplayName etc also, corresponding to their names. So use these column names in AnalystDisplayName, DesignerDisplayName etc in MyModelColumns.cs, you're probably using AnalystDisplayName twice? Or if i didn't understand problem, copy here content of MyModelColumns.cs so i can diagnose better.

**Comment by jsbUSMC** [comment]
Essentially, yes I am using AnalystDisplayName twice, or trying to. I use it already once when defining the columns for the Analyst (User) that is entering the data. I want to use it again four more times in the same column. However, of the four columns, some of the Users selected will be different than the others. Here is some of the relevant code:

```c#
    using Newtonsoft.Json;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), DisplayName("2nd Shift Tasks"), InstanceName("2nd Shift Task"), TwoLevelCached]
    [ReadPermission("Administration")]
    [ModifyPermission("Administration")]
    public sealed class ShiftTaskARow : Row, IIdRow
    {
        [DisplayName("Shift Task A Id"), Identity]
        public Int32? ShiftTaskAId
        {
            get { return Fields.ShiftTaskAId[this]; }
            set { Fields.ShiftTaskAId[this] = value; }
        }

        [DisplayName("Analyst"), NotNull, ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jAnalyst"), TextualField("AnalystUsername")]
        [LookupEditor("Operations.User")]
        public Int32? Analyst
        {
            get { return Fields.Analyst[this]; }
            set { Fields.Analyst[this] = value; }
        }

        // ....

        [DisplayName("Videowall Refresh"), NotNull]
        [LookupEditor("Operations.User")]
        public Int32? VwRefresh
        {
            get { return Fields.VwRefresh[this]; }
            set { Fields.VwRefresh[this] = value; }
        }

        [DisplayName("Inventory Bin Check"), NotNull]
        [LookupEditor("Operations.User")]
        public Int32? InvBin
        {
            get { return Fields.InvBin[this]; }
            set { Fields.InvBin[this] = value; }
        }

        [DisplayName("Amber Light Check"), NotNull]
        [LookupEditor("Operations.User")]
        public Int32? AmberLightCheck
        {
            get { return Fields.AmberLightCheck[this]; }
            set { Fields.AmberLightCheck[this] = value; }
        }

        [DisplayName("Call In Sick or Late")]
        [LookupEditor("Operations.User")]
        public Int32? SickLate
        {
            get { return Fields.SickLate[this]; }
            set { Fields.SickLate[this] = value; }
        }

       // ....

```

Above is the Row class for `ShiftTaskARow.cs` where you can see I have the foreign key attribute on the Analyst, along with a LookupEditor attribute that corresponds to the LookupScript attribute placed on the default User class. Here is the `ShiftTaskAColumns.cs`:

```c#
    [ColumnsScript("Operations.ShiftTaskA")]
    [BasedOnRow(typeof(Entities.ShiftTaskARow))]
    public class ShiftTaskAColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 ShiftTaskAId { get; set; }
        [DisplayName("Analyst")]
        public String AnalystDisplayName { get; set; }    // Here using the AnalystDisplayName works fine
        public TimeSpan Time { get; set; }
        public DateTime Date { get; set; }
        public Boolean SdcSignIn { get; set; }
        public Boolean EslNotify { get; set; }
        public Boolean PayrollBiWeekly { get; set; }
        public Boolean PayrollSemiMonthly { get; set; }
        public Boolean PayrollMonthly { get; set; }

        // I would ideally like to have AnalystDisplayName also work here instead of these Int32 from the select dropdown

        public Int32 VwRefresh { get; set; }
        public Int32 InvBin { get; set; }
        public Int32 AmberLightCheck { get; set; }
        public Int32 SickLate { get; set; }
    }
```

I hope this helps clarify the issue. I really appreciate your prompt attention and help! Thank you very much!

**Comment by volkanceylan** [comment]
You need to add foreign key and leftjoin for other fields also.

```cs

        [ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jVwRefresh"), TextualField("VwRefreshDisplayName")]
        [DisplayName("Videowall Refresh"), NotNull]
        [LookupEditor("Operations.User")]
        public Int32? VwRefresh
        {
            get { return Fields.VwRefresh[this]; }
            set { Fields.VwRefresh[this] = value; }
        }
       
       [DisplayName("Videowall Refresh"), Expression("jVwRefresh.DisplayName")]
       public string VwRefreshDisplayName
        {
            get { return Fields.VwRefreshDisplayName[this]; }
            set { Fields.VwRefreshDisplayName[this] = value; }
        }
```

Then you can use VwRefreshDisplayName instead of VwRefresh in grid columns.

**Comment by jsbUSMC** [comment]
I really appreciate this, for some reason I didn't think that I could have multiple foreign keys associated within the same table from a single column. Works great, thank you!

**Comment by rarunkumar454** [comment]
Hi, I have a AccountRow, UserRow and ReportRow. We want to write a lookupscript on ReportRow for AccountName and UserName. The problem was when I was choose the AccountName after filter the UserName on the userlookup.
