### ISSUE TITLE
Dynamic character amount validation within a TableForm

### ISSUE THREAD

**Issue by Isofff** [volkanceylan/Serenity#1060]
Hello again.

In myTableForm, there is a ComboBox (an Enum Field), and a Text Field.   I want to change the max lenght and format of the text field depending on what the user pick in the ComboBox.

For example, if the user picks "10 digit document, only numbers", the text field max lenght should be 10 and the content should only allow numbers.

 How can I achieve this?

Thanks in advance.

**Comment by volkanceylan** [comment]
form.ComboBox.change(e => form.SomeOtherText.element.attr('maxlength', ....))

**Comment by Isofff** [comment]
Thank you, it worked.

**Comment by Isofff** [comment]
Thanks for your advice, but now I was asked to clear the textbox content whenever the combobox selection changes.

I tried something like:
form.ComboBox.change(e => form.SomeOtherText.element.attr('text', '')) but it didn't work.

How can I achieve this?

Thanks in advance and sorry for the trouble.

**Comment by volkanceylan** [comment]
form.SomeOtherText.value = ""

**Comment by Rupali92** [comment]
how to hide and unhide some textbox on checkbox checked and dropdown selectchanged
