### ISSUE TITLE
add new project use Serene template to a exists solution will make Visual Studio 2015 crash

### ISSUE THREAD

**Issue by fzhenmei** [volkanceylan/Serenity#1064]
I tried several times and two computers and every time Visual Studio 2015 will crash, after Visual Studio restart Serene extension will be disabled automatically.

Create new project use Serene template with new solution works fine.

**Comment by volkanceylan** [comment]
VS is full of bugs that are beyond my reach. Try creating a new Serene project, then use add existing project.
