### ISSUE TITLE
Problem with close button

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1065]
The close button appears misplaced, how to correct it.
![error_close](https://cloud.githubusercontent.com/assets/10889019/17651116/3e392e72-6257-11e6-8f04-9e9e8db5a526.png)

**Comment by rolembergfilho** [comment]
Hey @brunobola, check #975 

You need to add this CSS

.ui-button-icon-only {
text-indent: -9999px;
}

**Comment by volkanceylan** [comment]
Dont update jQuery UI

**Comment by brunobola** [comment]
Thanks, problem solved :)
