### ISSUE TITLE
Problem when using iphone 6 Layout in Chrome

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1066]
When using iphone 6 Layout in Chrome, the left arrow is in front of the text, how to correct it.
![error_iphone_mode_close](https://cloud.githubusercontent.com/assets/10889019/17651122/9b0abe36-6257-11e6-8962-4a70cd74e624.png)

**Comment by volkanceylan** [comment]
You probably updated jQuery UI

**Comment by brunobola** [comment]
Yah u're right.
Thanks.
