### ISSUE TITLE
Sum of column in Detail Dialog - Shown/calculated immediately in a field of Parent Dialog

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#1068]
Hi community,

Does anyone have a better solution regarding sum field in a form, exactly like issue #1021?
A solution where you do not have to save the master dialog before getting the sum-amount into the field in the master dialog? (Not write to SQL table before, preferably)

I have the exact same field, a sum of a column in detail dialog which I want to be calculated and shown immediately in the master dialog after the detail dialog has been closed. But if you take the steps in #1021, then you need to save the master-form before to be able to query directly from the saved table.

![image](https://cloud.githubusercontent.com/assets/15879719/17684598/7cc05e9a-634c-11e6-8260-2760e534e491.png)

Is it possible to call List action in xyzDetailEndpoint to sum up the cached/in-memory column data?
OR could someone point me in the right direction on how to Save a Parent-Dialog automatically upon closing it's Child-Detail-Dialog.

Thanks

**Comment by ramveersgh** [comment]
Why don't you use the grouping to show the total? like this -
![vtotsl](https://cloud.githubusercontent.com/assets/2145218/17689102/dd2a2706-63a2-11e6-96d6-a7b7906604bc.png)

**Comment by biggikalli** [comment]
Hi Ramveer, 
I want the sum to appear in a specific field on the master form/dialog, not in the detail grid which is inside the form. 
The grouping example doesn't cover that part.
I would be happy if I could just let the form save (apply changes) when the details dialog closes. With that, the sum field would calculate and show the value...  as per my picture of the form. 
Regards, Biggi 
-------- Original message --------From: Ramveer Singh <notifications@github.com> Date: 8/16/16  07:47  (GMT+01:00) To: volkanceylan/Serenity <Serenity@noreply.github.com> Cc: biggikalli <biggi@biggi.is>, Author <author@noreply.github.com> Subject: Re: [volkanceylan/Serenity] Sum of column in Detail Dialog - Shown/calculated immediately in a field of Parent Dialog (#1068) 
Why don't you use the grouping to show the total? like this -



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/volkanceylan/Serenity","title":"volkanceylan/Serenity","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/volkanceylan/Serenity"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ramveersgh in #1068: Why don't you use the grouping to show the total? like this -\r\n![vtotsl](https://cloud.githubusercontent.com/assets/2145218/17689102/dd2a2706-63a2-11e6-96d6-a7b7906604bc.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/volkanceylan/Serenity/issues/1068#issuecomment-240007050"}}}

**Comment by volkanceylan** [comment]
Here is a sample for you for OrderDialog constructor:

```ts
    @Serenity.Decorators.registerClass()
    export class OrderDialog extends Serenity.EntityDialog<OrderRow, any> {
        constructor() {
            super();

            (this.form.DetailList.view as any).onDataChanged.subscribe(() => {
                var total = 0;
                for (var k of this.form.DetailList.getItems()) {
                    total += k.LineTotal || 0;
                }
                Q.notifySuccess(total.toString());
            });
        }
```

Replace Q.notifySuccess with form.MyField.value = total;

**Comment by biggikalli** [comment]
@volkanceylan, thank you.
This code worked like a charm, just like you yourself always do :)

**Comment by rgilsimoes** [comment]
Hi! I'm tying this snipet in my Form and I get the Q.notifySuccess message upon openning the Master form but not after adding new records on the Detail Grid.

Any clues on this?

**Comment by rgilsimoes** [comment]
I just found out that I add not inherited the Dialog from GridEditorDialog. After changing the grid updated fine and the subscribe() function also worked!

**Comment by ckrassas** [comment]
> Here is a sample for you for OrderDialog constructor:
> 
> ```ts
>     @Serenity.Decorators.registerClass()
>     export class OrderDialog extends Serenity.EntityDialog<OrderRow, any> {
>         constructor() {
>             super();
> 
>             (this.form.DetailList.view as any).onDataChanged.subscribe(() => {
>                 var total = 0;
>                 for (var k of this.form.DetailList.getItems()) {
>                     total += k.LineTotal || 0;
>                 }
>                 Q.notifySuccess(total.toString());
>             });
>         }
> ```
> 
> Replace Q.notifySuccess with form.MyField.value = total;

I've been dealing with this issue for about a week now. The code from @volkanceylan works amazing. The only problem is when deleting. I did some research and it seems that instead of using onDataChanged you can use onRowCountChanged. For my project it works amazing and as it should.

> ```ts
>     @Serenity.Decorators.registerClass()
>     export class OrderDialog extends Serenity.EntityDialog<OrderRow, any> {
>         constructor() {
>             super();
> 
>             (this.form.DetailList.view as any).onRowCountChanged.subscribe(() => {
>                 var total = 0;
>                 for (var k of this.form.DetailList.getItems()) {
>                     total += k.LineTotal || 0;
>                 }
>                 Q.notifySuccess(total.toString());
>             });
>         }
> ```

This should help #3818 / #3769 and so on with delete issue. Many thanks to @volkanceylan for an amazing product and the help provided.

**Comment by ga5tan** [comment]
@ckrassas but how do u use onRowCountChange?
this:

```
(this.form.MailingList.view as any).onRowCountChange.subscribe(() => {
                this.UpdateEmailCount();                
            });

```

fails, says there is not onRowCountChange

**Comment by ckrassas** [comment]
> @ckrassas but how do u use onRowCountChange?
> this:
> 
> ```
> (this.form.MailingList.view as any).onRowCountChange.subscribe(() => {
>                 this.UpdateEmailCount();                
>             });
> ```
> fails, says there is no onRowCountChange:
> 
> > Message: TypeError: _this.form.MailingList.view.onSubmit.subscribe is not a function

Sorry but it is OnRowCountChanged. I misspelled it when I was writing my reply. Hope that helps. I updated my response also.

**Comment by ga5tan** [comment]
@ckrassas 
same with changed :(

> Message: TypeError: _this.form.MailingList.view.OnRowCountChanged is undefined

My Editor  is:

> export class MailingListEditor extends Common.GridEditorBase<MailingListRow> 

I ont understand what is the diference here :(

**Comment by ckrassas** [comment]
@ga5tan This is not to placed in the editor. This is to be used within your Dialog. It is there to see changes made to the grid.

**Comment by ga5tan** [comment]
@ckrassas - yeah, I do it in EntityDialog and it's working:

> (this.form.MailingList.view as any).onDataChanged.subscribe(() => {
>                 this.UpdateEmailCount();
>             });

but your :

>             (this.form.MailingList.view as any).OnRowCountChanged.subscribe(() => {
>                 this.UpdateEmailCount();                
>             });            

wont work :(

**Comment by ckrassas** [comment]
@ga5tan Please check the version that you are using. I am using 3.7.7 and Also make sure that your grid is updating once a change is made to reflect the changes on the grid. Another this is to make sure this is placed inside the constructor(). Not sure why it is not working if you editor works correctly.

**Comment by ga5tan** [comment]
@ckrassas somehow I ended up with spelling mistake OnDataChanged instead of onDataChanged (leading O should be lowercase)
now it works! thx

**Comment by rashidamtech** [comment]
Message: Uncaught TypeError: Cannot read property 'view' of undefined

Please Help Me . I geeting Error 

 (this.form.DetailList.view as any).onDataChanged.subscribe(() => {
                var totaldr = 0;
                for (var k of this.form.DetailList.getItems()) {
                    totaldr += k.Debit || 0;
                }
                Q.notifySuccess(totaldr.toString());
            });

**Comment by stixoffire** [comment]
@ckrassas 
Thanks for posting this answer - it is an extremely important detail - the intellisense does not show this as a function but it does work!

I have a button in my dialog that is dependent on an item in the DetailsList - Items present button visible, no items and button must be disabled.

I also have in the detailseditor a need to calculate the totals for that grid as items are added and removed.

With your direction I used the following code to achieve both requirements. 

**Dialog**
```
            (this.form.ItemsList.view as any).onRowCountChanged.subscribe(() => {
                this.submitHidden = (this.form.ItemsList.rowCount() < 1);
                this.toggleSubmitVisibility(this.submitHidden);
            });
```
**DetailEditor**
```
            (this.view as any).onRowCountChanged.subscribe(() => {
                var total = 0;
                for (var k of this.getItems()) {
                    total += k.LineTotal || 0;
                }
	});
```

**Comment by flextrio-gandhi** [comment]
@ramveersgh       > Why don't you use the grouping to show the total? like this -
> ![vtotsl](https://cloud.githubusercontent.com/assets/2145218/17689102/dd2a2706-63a2-11e6-96d6-a7b7906604bc.png)
Hi Ramveer,     I'm trying this, but i didn't get it .please post clearly
