### ISSUE TITLE
2 rows while 1 expected! hatası

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#107]
s.a.
kolay gelsin.  bi sıkıntım var yardımcı olursan sevinirim.
1 alanı güncelledikten sonra trigger ile 1 alan daha güncelliyorum. ve serenity tarafından Query affected 2 rows while 1 expected!  hatası alıyorum.  bu engeli nasıl aşabilirim .

**Comment by volkanceylan** [comment]
Trigger da SET NOCOUNT ON yazarsanız sorun olmaz.

**Comment by oaltay** [comment]
tşk.ler
