### ISSUE TITLE
about ImageUploadEditor

### ISSUE THREAD

**Issue by thisXYH** [volkanceylan/Serenity#1070]
Photos uploaded to  another FTP server by  the site, FTP on a return path as the field value when the edited image can be accessed through a path . How to achieve this function

**Comment by volkanceylan** [comment]
You need to write a custom behavior for such. See FileUploadBehavior and modify to your needs.

**Comment by thisXYH** [comment]
ok,   According to your guidance I realized I wanted the effect . thank you .But now there are new questions, Row attributes must correspond to the fields and the corresponding table, how to add additional fields in the database is not in Row

**Comment by thisXYH** [comment]
Wrong, add a field in the Row, but the table does not

**Comment by volkanceylan** [comment]
See mapping guide

**Comment by thisXYH** [comment]
In serenity-guide.pdf ?  
I have not found.
I will increase the field, but I want to be there Row, table no,

**Comment by thisXYH** [comment]
I'm sorry for my carelessness, I have not found The ClientSide Attribute
