### ISSUE TITLE
How to modify column content on code side?

### ISSUE THREAD

**Issue by bothersomeman** [volkanceylan/Serenity#1071]
I want to set value to column on code. So i tried to modify related property's getter but no luck 

xyzColumns.cs 
```
`    [ColumnsScript("Tanimlamalar.PerIlce")]
    [BasedOnRow(typeof(Entities.PerIlceRow))]
    public class PerIlceColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 Id { get; set; }
        
        [DisplayName("İl")]
        public string Il { get { return "İstanbul";} set {} }
        [DisplayName("İlçe")]
        [EditLink]
        public String IlceAdi { get; set; }
        
        [DisplayName("Belediye Adı")]
        public String BelediyeAdi { get; set; }
    }`
```

I realized that transfered data comes from sql query result directly to the grid. Even i put breakpoints, it didn't got to debug to any code that i can operate.

**Comment by bothersomeman** [comment]
I also tried custom attribute on xyzRow.cs 

```
        [ClientSide()]
        public String Test {
            get { return "İst"; }
            set { }
        }
```

nothing happened.

How can i solve this situation?

**Comment by VictorTomaili** [comment]
on dialog you can put this in constructor
```
if(this.isNew())
    this.form.Test.Value = "istanbul"
```

**Comment by bothersomeman** [comment]
Hi, thank you for your reply.
I'm trying to customise value on grid. Your solution is related with dialog.

**Comment by volkanceylan** [comment]
If database doesn't have İstanbul, why do you want to show İstanbul there? What you ask is something like a formatter. Anyway if you still want such a thing, override your MyListHandler OnReturn method, traverse response.Entities, and fill in values you would like to.

**Comment by bothersomeman** [comment]
I just wanted to see how can i customize values so i put it static in this example. 
I modified MyListHandler.OnReturn :
` private class MyListHandler : ListRequestHandler<MyRow> {
            protected override void OnReturn()
            {
                foreach (var row in Response.Entities)
                    row.Il = IL.arrIL.GetEntityWithIndex("ID", row.ILID).ILAdi;
                base.OnReturn();
            }
        }`

I have related properties on xyzRow.cs :
`[DisplayName("İl"), Column("ILID"), NotNull, QuickSearch, QuickFilter]
        [LookupEditor(typeof(PerIlRow), InplaceAdd = true)]
        public Int32? ILID
        {
            get { return Fields.ILID[this]; }
            set
            {
                Fields.ILID[this] = value;
            }
        }        

        private string m_il;
        [DisplayName("İl"), Column("Il")]
        public String Il
        {
            get { return m_il; }
            set { m_il = value; }
        }`

Also I have column on xyzColumns.cs:
`        [DisplayName("İl")]
        public string Il { get; set; }`

This changes seems ok for me but i cannot see values on grid. How can i check returned json or what could be the solution?

Thanks for your help

**Comment by volkanceylan** [comment]
You can see it in chrome dev tools (F12) xhr tab

**Comment by bothersomeman** [comment]
I added LookupInclude and problem solved. It was good to learn xhr tab. Thanks a lot.
