### ISSUE TITLE
CompileSite compiling not reponding or very long

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#1072]
Hi,

I am experiencing issue while compiling. Most of the time I stop and restart compiling and it works, but it seems that CompileSiteLess, is the issue. Any idea if I did something that could trigger an infinite loop or anything?

When not working:
2>    251084 ms  CompileSiteLess                            1 calls

When working
2>     3460 ms  CompileSiteLess                            1 calls

**Comment by volkanceylan** [comment]
Your antivirus or some other thing might be blocking, i have no such issue. Remove that line from Csproj and use an external less compilation tool if no other solution

**Comment by Boumboumjack** [comment]
Hi, 

Thank you, it seems to be indeed the case.
