### ISSUE TITLE
MasterDetailRelation, throwing NullReference on ListRequestHandler.Process()

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1073]
Hoping someone has seen something like this... I have a MasterDetailRelation, exception being thrown in the master's repository.List() method. SQL that's executed right before the exception looks fine, returns results with no empty columns.

Master row has this:

`[DisplayName("Audit Result List"), MasterDetailRelation(foreignKey: "ActiveAuditId"), ClientSide]
        public List<PolicyTestResultRow> AutomatedTestList
        {
            get { return Fields.AutomatedTestList[this]; }
            set { Fields.AutomatedTestList[this] = value; }
        }
`

Detail row has this:

`[DisplayName("Audit"), Expression("jRequest.ActiveAuditId"), ForeignKey("Audit", "Id"), LeftJoin("jAudit"), LookupInclude, MinSelectLevel(SelectLevel.List)]
        public Int64? ActiveAuditId
        {
            get { return Fields.ActiveAuditId[this]; }
            set { Fields.ActiveAuditId[this] = value; }
        }
`

And here's the stack trace for the exception:

`Serenity.Services.MasterDetailRelationBehavior.<OnReturn>b__24_1(Row x) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\IntegratedFeatures\MasterDetail\MasterDetailRelationBehavior.cs:line 167
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ...`

Anyone seen something like this before?

**Comment by volkanceylan** [comment]
MasterDetailRelation loads all detail rows in list handler with an IN query, and converts them to lookup by their master ID values, then fills them in response entities by using the lookup. But somehow you get error in lookup creation so your master value should be null in one of details but dont know how.

**Comment by wldkrd1** [comment]
Ok. I'm no longer using a MDR so this isn't blocking me. Thanks.
