### ISSUE TITLE
currency formatter

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1077]
Hi There,
I was inspired by the code suggested by jsbUSMC and biggikalli but as I could not apply it to the latest version of Serenity I kind of experimented and came up with the following code which works.
This can easily be extended with minor changes to % and other formats.

I also used ideas from the Norhwind.EmployeeFormatter and from here:
http://stackoverflow.com/questions/149055/how-can-i-format-numbers-as-money-in-javascript

Asking for the following:
While I know it works I am very early in my TypeScript/JavaScript coding (like, 4 hrs into googling what TS is, that early).
Please double check and if you spot "silly moves" - please improve & add comments (to make it like a tutorial).

Here we go:
=============== Where things are? =====================
1. Create CurrencyFormatter.ts in ...Modules.Common.Helpers (use the complete code below)
2. Visual Studio Tool Bar -> Build -> Transform All T4 Templates
3. Now this new TS will be visible in intellisense.
3. Go to ......Columns.cs in your specific module.
4. Enter above the column that is supposed to show the currency this (match your col names).
 [CurrencyFormatter(NumberProperty = "BudgetConsolidated")]
 public Decimal BudgetConsolidated { get; set; }

Ideally the above should be modified to accept various currency formats (see comments below)

=============== Code ==============================
//Make sure you use only your project name as this is a universal helper.
namespace YourProjectNameHere {

    @Serenity.Decorators.registerFormatter([Serenity.ISlickFormatter, Serenity.IInitializeColumn])
    export class CurrencyFormatter implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {

            //If the input is not a float - just bounce it back
            if (isNaN (parseFloat(ctx.value))) {
                return ctx.value;
            }

            //Use standard currency formatting; This can be modified for other styles (% etc).
            //How can this be made to accept the parameters en-US and USD as input parameters?
            //style "currency" can stay hard-coded
            var formatter = new Intl.NumberFormat('en-US', {
                style: 'currency',
                currency: 'USD',
                minimumFractionDigits: 2,
            });

            //use the above formatter to return the reformatted value
            var percentValue = formatter.format(Number(ctx.value));
            return "<span>" + percentValue + '</span>';
        }

        //What is this and why does it work?
        @Serenity.Decorators.option()
        public numberProperty: string;

        public initializeColumn(column: Slick.Column) {
            column.referencedFields = column.referencedFields || [];
            if (this.numberProperty)
                column.referencedFields.push(this.numberProperty);
        }
    }
}

**Comment by volkanceylan** [comment]
Thanks SimeonDD.

Just to note, you don't need numberProperty or initializeColumn, as you are not making use of it at the moment. You need that if you'll read value from another property, not the column your formatter is attached to.

You may remove it, and add similar ones for culture and currency options, so your formatter can be reused for others. You don't need initializeColumn and referencedFields, if you are not going to read these cultural information from another property in row.

**Comment by SimeonDD** [comment]
Thanks!
It worked in a way.
1. I managed to make the culture and currency flexible.
2. If I comment out anything below the line ----??--- the grid does not paint at all.

You got other things to worry about and there is too much I do not know at this point - meaning.
It works as is - so not urgent to cleanup (unless others want to take a stab at it)

=============================================
`
namespace YourProjectNameHere {

    @Serenity.Decorators.registerFormatter([Serenity.ISlickFormatter, Serenity.IInitializeColumn])
    export class CurrencyFormatter implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {

            //If the input is not a float - just bounce it back
            if (isNaN (parseFloat(ctx.value))) {
                return ctx.value;
            }

            //Use standard currency formatting; This can be modified for other styles (% etc).
            //How can this be made to accept the parameters en-US and USD as input parameters?
            //style "currency" can stay hard-coded
            //var cn = this.cultureName;

            //var formatter = new Intl.NumberFormat('en-US', {
            //    style: 'currency',
            //    currency: 'USD',
            //    minimumFractionDigits: 2,
            //});

            var formatter = new Intl.NumberFormat(this.cultureName, {
                style: 'currency',
                currency: this.currencyName,
                minimumFractionDigits: 2,
            });

            //use the above formatter to return the reformatted value
            var percentValue = formatter.format(Number(ctx.value));
            return "<span>" + percentValue + '</span>';
        }

        @Serenity.Decorators.option()
        public cultureName: string;
        @Serenity.Decorators.option()
        public currencyName: string;
        @Serenity.Decorators.option()
        public numberProperty: string;

        //------------ ?? --------------------
        public initializeColumn(column: Slick.Column) {
            column.referencedFields = column.referencedFields || [];
            if (this.numberProperty)
                column.referencedFields.push(this.numberProperty);
        }
    }
}
`
===============
To others:
make sure you Transform All T4 Templates.
then you can call like:
 [CurrencyFormatter(NumberProperty = "Q1Budget",CultureName = "en-US", CurrencyName = "EUR")]
 public Decimal Q1Budget { get; set; }

[CurrencyFormatter(NumberProperty = "Q2Budget", CultureName = "en-US", CurrencyName = "GBP")]
public Decimal Q2Budget { get; set; }

[CurrencyFormatter(NumberProperty = "Q3Budget", CultureName = "en-US", CurrencyName = "USD")]
public Decimal Q3Budget { get; set; }

**Comment by edson** [comment]
Hi, thanks for sharing!

Just found out Serene a few days ago, amazing job! Still learning, though...


I've made some changes, so that it would work without initializeColumn and NumberProperty:

namespace YourProjectNameHere {

    @Serenity.Decorators.registerFormatter()
    export class CurrencyFormatter implements Slick.Formatter {
        
        @Serenity.Decorators.option()
        public cultureName: string;
        @Serenity.Decorators.option()
        public currencyName: string;

        format(ctx: Slick.FormatterContext) {

            //If the input is not a float - just bounce it back
            if (isNaN(parseFloat(ctx.value))) {
                return ctx.value;
            }

            //Use standard currency formatting; This can be modified for other styles (% etc).
           //If no parameters passed then fallback to en-US , USD formatting.
            this.cultureName = this.cultureName ? this.cultureName : 'en-US';
            this.currencyName = this.currencyName ? this.currencyName : 'USD';

            var formatter = new Intl.NumberFormat(this.cultureName, {
                style: 'currency',
                currency: this.currencyName,
                minimumFractionDigits: 2,
            });

            //use the above formatter to return the reformatted value
            var percentValue = formatter.format(Number(ctx.value));
            return "<span>" + percentValue + '</span>';
        }

       
        
    }
}

Then, you just call:

[CurrencyFormatter(CultureName = "en-US", CurrencyName = "EUR")]
public Decimal Q1Budget { get; set; }

[CurrencyFormatter(CultureName = "en-US", CurrencyName = "GBP")]
public Decimal Q2Budget { get; set; }

[CurrencyFormatter]
public Decimal Q3Budget { get; set; }

**Comment by SimeonDD** [comment]
Sorry for the delayed response!
Thanks so much! And thanks for posting in a way that did not need guessing.
Yes, It works great.

**Comment by SimeonDD** [comment]
Big improvement!

**Comment by edson** [comment]
Hi, @SimeonDD . I've put this in a Wiki Page.

https://github.com/volkanceylan/Serenity/wiki/SlickGrid-Formatters

Best Regards

**Comment by naveengundala** [comment]
Hi, I was just using this code. When I try to add [CurrencyFormatter(NumberProperty = "Debit")] attribute in my column.cs file it is showing there is no namespace. Do I need to install any specific dll's to it!
