### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by mesteves** [volkanceylan/Serenity#108]
Hi, after installing Serene and run it in visual studio, gives me execution errors saying that scripts aren't registered.

**0x800a139e - JavaScript runtime error: Script data Form.Membership.Login is not found in registered script list!**

Here:
$Q$ScriptData.$loadScriptData = function(name) {
		if (!ss.keyExists($Q$ScriptData.$registered, name)) {
			throw new ss.Exception(ss.formatString('Script data {0} is not found in registered script list!', name));
		}

Am i missing something ?

Best regards,
Manuel

**Comment by volkanceylan** [comment]
Hi Manuel,

Did you try rebuilding project? Is there any build errors. What is your VS version, update and other info.

**Comment by mesteves** [comment]
Hi @volkanceylan ,

I use VS2012 Update 5. I've tried to clean and rebuild, and it compiles well. The erros that i get, are in execution time. The form don't even render...

![15-01-2016 10-02-34](https://cloud.githubusercontent.com/assets/3369185/12350474/422a26f6-bb6f-11e5-81c1-217fce7bcc82.jpg)

![signupform](https://cloud.githubusercontent.com/assets/3369185/12350483/483eb2dc-bb6f-11e5-8d1d-e3bd88dca1ee.jpg)

**Comment by volkanceylan** [comment]
From screenshots it seems like you have sytax errors even in jquery. Try with another browser to check if it is IE or Edge related.

**Comment by mesteves** [comment]
I've figured it out... 

I've tried in Chrome and the result is this:

![chorme-console](https://cloud.githubusercontent.com/assets/3369185/12352010/1ee3d1fa-bb7a-11e5-9800-45d6cf5ec04c.jpg)

Seems that the hander in not working well

in config it is there

**<add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />**

I've changed the settings in VS, changing the running server from VS development server to IIS Express and is working now. (altough with some javascript errors but that is probably because of the browser..)

In IE10 when over a grid row in console, it appears:

**SCRIPT5007: Unable to get property 'length' of undefined or null reference 
jquery.slimscroll.js, line 261 character 13**

Thank you for your help and going to start exploring Serenity! :)

Best regards,
Manuel

**Comment by volkanceylan** [comment]
VS development server uses handlers section under system.web instead of system.webserver
 You could copy handlers but IISExpress is better.

**Comment by mesteves** [comment]
Yes, it's true :+1: 

I've created a project through the installed template and though was just pressing F5 :)

Although I didn't explore the framework very much, i've been reading the documentation and seems to be a very nice FW! Nice work!!

Thanks!
