### ISSUE TITLE
Please help me to convert image from database show in gird

### ISSUE THREAD

**Issue by Takecarecom** [volkanceylan/Serenity#1080]
Please help me to convert image from database show in gird
![q2](https://cloud.githubusercontent.com/assets/13514630/17803431/99b58012-6620-11e6-9bcb-c390a79cae1a.png)

**Comment by biggikalli** [comment]
Good question. I have the same issue in one of my projects where I have a small pixel images of flags of all the world's countries saved in my MS SQL table. I would like to show them in a grid or a form next to a filtered country field.

I would really like to know if this can be done easily as I have no clue and can't find any material online.

**Comment by volkanceylan** [comment]
You might use data uri for this. Another option is to prepare a controller action that fetches images from DB and returns them as content result, so you ll have an image url

**Comment by Takecarecom** [comment]
@volkanceylan 
    Please find an example to me.

Thank you

**Comment by volkanceylan** [comment]
Try searching data uri in google

**Comment by Takecarecom** [comment]
@volkanceylan 

   Thank you
