### ISSUE TITLE
Cleanup after removing Northwind

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1081]
Thanks for the excellent instructions on how to remove Northwind. Worked great.
Could you please share a tip on how to finish the cleanup like the one on the pic below?
Also, for the future, maybe a good idea to offer two Serene project templates: One with all samples and one with only administration.
Thanks!
![defaultscreen](https://cloud.githubusercontent.com/assets/19690830/17812089/97df3210-65f3-11e6-82f7-2e67b5679a37.png)

**Comment by biggikalli** [comment]
Hi @SimeonDD ,

You have probably solved this by now :)

This is rather easy and it's almost pure html. It can be done by deleting/altering the DashboardIndex.cshtml file:

![image](https://cloud.githubusercontent.com/assets/15879719/17826783/c7cecc04-6663-11e6-84a9-e3eb9ce61374.png)

**Comment by SimeonDD** [comment]
Thanks for responding man!
It did not work, but that is OK.
I will close this one as there is quite a bit I still need to learn on the basic project structure.

I wish Serene would offer a second template with an empty projects except the Admin pages.
Thanks again.

**Comment by SimeonDD** [comment]
With biggikalli's help and some more self-education this is what needs to happen to show a blank page instead of the dashboard.
All in Modules\Common\Dashboard
1. Delete "...DashboardPageModel"
2. Reduce DashboardIndex.cshtml to only
@{
    ViewBag.Title = "Home Page";
}

3. Reduce DashboardPage.cs to only

namespace Serene1.Common.Pages
{
    using System.Web.Mvc;
    using MyViews = MVC.Views.Common;

    [RoutePrefix("Dashboard"), Route("{action=index}")]
    public class DashboardController : Controller
    {
        [Authorize, HttpGet, Route("~/")]
        public ActionResult Index()
        {
            return View(MyViews.Dashboard.DashboardIndex);
        }
    }
}

**Comment by SimeonDD** [comment]
Also make sure that in NavigationItems.cs you have on top
[assembly: NavigationLink(100, "Dashboard", url: "~/", permission: "", icon: "icon-speedometer")]

Otherwise your navbar will not put the focus on the correct item after boot.
