### ISSUE TITLE
GridRowSelectionMixin issues

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1083]
I know the guide is pending update for TypeScript but I have not been able to figure out how to do this yet. I tried using 
        
        protected creatToolbarExtensions() {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
        }
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));
            return columns;
        }

But "splice" doesn't seem to work for me. I do get a check box but only at the top of the grid next to the column titles. I have debugged in the console and the column is created fine, but doesn't show correctly on my grid. I am looking to add a select column so I can pass the value of a column in a tab grid back to the dialog. (parent), I'm tired right now so hopefully that just made sense :)

**Comment by jdready5** [comment]
I'm looking at Bulk Action in Basic Sample now to see why "splice" is not working on my grid to show the checkboxes. I may be able to figure it out, if I do I will update and close this

**Comment by volkanceylan** [comment]
I see your createToolbarExtensions method name is wrong

**Comment by jdready5** [comment]
Oh bloody hell, I can't feel any dumber or embarrassed than I do at the present moment. Sorry about this.... :)
