### ISSUE TITLE
How to Add Datepicker and Refresh button in place of add button

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1084]
How can i add a daterangepicker and a refresh button which can re-populate the data in grid.

**Comment by jdready5** [comment]
You can use getQuickFilters like such:

         protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            let filters = super.getQuickFilters();

            let fld = YourRow.Fields;

            Q.first(filters, x => x.field == fld.YourDateField).init = w => {

                (w as Serenity.DateEditor).valueAsDate = new Date(Date.now());

                let endDate = w.element.nextAll(".s-DateEditor").getWidget(Serenity.DateEditor);
                endDate.valueAsDate = new Date(Date.now());
                this.refresh();
            };
            
            return filters;            
        }

**Comment by volkanceylan** [comment]
Think your problem is resolved with stored proc sample.

**Comment by mrajalko** [comment]
yes it is solved.
thanks.
