### ISSUE TITLE
Date Picker localization

### ISSUE THREAD

**Issue by ntfox** [volkanceylan/Serenity#1085]
Hi,
How can change localization of date picker for use other date time, ex: Jalali

http://stackoverflow.com/questions/26129995/how-to-change-bootstrap-datepicker-date-to-jalali-date
https://github.com/mousavian/bootstrap-jalali-datepicker

**Comment by volkanceylan** [comment]
We use jQuery UI datepicker and it uses your UI culture

**Comment by misafer** [comment]
dear Volkan, i appreciate if you can help me with this jqueryUI customized datepicker for use in persian 👍 
https://www.nuget.org/packages/PersianDatePicker/
