### ISSUE TITLE
Setting DateTime.Now in a row

### ISSUE THREAD

**Issue by AlanGreyjoy** [volkanceylan/Serenity#1086]
I am trying to set a field named TimeStamp as DateTime.Now. So that I can record the time a record was created.

I tired to set the DefaultValue to DateTime.Now, it throws an error.
`[DisplayName("Time Stamp"), NotNull, DefaultValue(DateTime.Now)]
        public DateTime? TimeStamp
        {
            get { return Fields.TimeStamp[this]; }
            set { Fields.TimeStamp[this] = value; }
        }`

Any pointers?

I love this package... but man does it have a long learning curve. I've never used PostScript or much of JAVA. But I do have 2 Rhino5 plugins, 3 WPF/2 WinForm applications, and 1 SigmaNest plugin under my belt, so I am capable of learning it.

Thanks!

**Comment by volkanceylan** [comment]
Knowing that you cant write DateTime.Now or any dynamic value in an attribute has no relation to Serenity, its about .Net basics, so there is nothing we can do about that learning curve. But Serenity supports DateTime("now") in forms not row.

**Comment by volkanceylan** [comment]
Typo, DefaultValue("now")

**Comment by AlanGreyjoy** [comment]
Yea, I am reading up on attributes now. Never really used them before, so there was no learning process for that for me.

From what I have been reading, attributes could have saved a lot of crazy data swapping that I do.

**Comment by baliuzao** [comment]
so If i just only a year or month or day of now?

**Comment by GreenUtil** [comment]
DefaultValue("now") in forms gives time 00:00:00

**Comment by dms2701** [comment]
How can I do (Now + 1 day)?
