### ISSUE TITLE
how to copy grid data 

### ISSUE THREAD

**Issue by shailendrasingh03** [volkanceylan/Serenity#1088]
while seeing grid we dont have option to copy grid content is it possible ,

**Comment by volkanceylan** [comment]
You mean select and copy text? Search for enabletextselection in issues

**Comment by shailendrasingh03** [comment]
Not found

**Comment by biggikalli** [comment]
Try looking in the project also ;)
It will reveal this, just change the boolean to **true**:
![image](https://cloud.githubusercontent.com/assets/15879719/17908990/19f27fb0-6972-11e6-8305-68a17f6f5b54.png)

**Comment by samdubey** [comment]
[Please see the issue](https://github.com/volkanceylan/Serenity/issues/995)

**Comment by shailendrasingh03** [comment]
thanks done ..
