### ISSUE TITLE
set cascading lookup field value

### ISSUE THREAD

**Issue by Me-Kal** [volkanceylan/Serenity#1089]
hi ,
i want to set cascading lookup field value to first item of the lookup on specific condition on dialog, i tried below code but no luck.  

 constructor() {
            super();
 this.form.SCId.changeSelect2(e => {
     if (this.form.SCId.get_text() == "Branches") {
                    
                   this.form.CategoryId.value = this.form.CategoryId.cascadeValue[0]; 
                                                                     }

            });
        }

**Comment by Me-Kal** [comment]
done , this.form.CategoryId.value = Q.toId(this.form.CategoryId.items[0].id)

**Comment by Shraddha996** [comment]
@Me-Kal  
am getting an error on get_text()

**Comment by dfaruque** [comment]
`.get_text()` is now `.text`
