### ISSUE TITLE
Issue with Visual Studio build failures

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#109]
I am using VS2015 update 1 (version 14.0.24720.00) and Serenity 1.8.20. I have pushed my project to VS Team Services and have not had any trouble yet building my project until I tried to use the VSTS build with CI. I am receiving a build error because lessc is not checked into the source control for some reason. I looked at my project in VS, and sure enough, it said 'ignored'. I right-clicked, Add to Source Control and tried to commit but it basically said that I couldn't commit because there was no changes, even though the included changes have my lessc (Serenity.Web/tools/Node/less/bin/lessc) listed as an included change as an add. My remote doesn't even have the bin/ folder. Any ideas how to get the file included into the remote so it passes it's build? Thank you!

**Comment by volkanceylan** [comment]
I don't have much experience with TFS, but maybe bin folders are ignored?

You may try moving lessc under lib folder (tools\Nodes\less\lib) then editing lessc.cmd under tools\Node like this:

```cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\less\lib\lessc" %*
) ELSE (
  node  "%~dp0\less\lib\lessc" %*
)
```
I'm going to do this also in 1.9.1, to resolve issues with bin folder

**Comment by jsbUSMC** [comment]
I really appreciate the prompt response! I'm thinking I'll just edit the less.cmd file like you've said, to avoid any issue with the bin folder. Thanks, man, keep up the hard work!

**Comment by ChenZhaobin** [comment]
I have the same problem ,I can't resolve it .

**Comment by jsbUSMC** [comment]
The fix he provided above worked for me. Update to 1.9.5 and see if that helps at all.
