### ISSUE TITLE
Question on "How To: Setup Cascaded Editors" section on Serenity Guide

### ISSUE THREAD

**Issue by sasinallatech** [volkanceylan/Serenity#1092]
On "How To: Setup Cascaded Editors" section on Serenity Guide, there are 3 tables named Country, City and District as look up tables and Customer table has CountryID. CityID and DistrictID. This works fine.
What I want is, the Customer table to have only one column called DistrictID only (as City and Country are related to it through foreign key) and still be able to narrow the search by selecting Country and City?

**Comment by volkanceylan** [comment]
Add them as view fields to your Customer row

**Comment by sasinallatech** [comment]
I tried that. But Cascading didn't worked. 
Ignore DistrictID. Let us just consider, Customer has CityID alone and I want to select the Country and then the City based on the selected Country and save CityID only. My code is below,

CustomerRow:
[DisplayName("City"), Column("CityID"), NotNull, ForeignKey("[dbo].[Cities]", "ID"), LeftJoin("jCity"), TextualField("CityName")]
        [LookupEditor(typeof(CityRow)), LookupInclude]
        public Int64? CityId
        {
            get { return Fields.CityId[this]; }
            set { Fields.CityId[this] = value; }
        }

[DisplayName("Country"), Expression("jCity.[CountryID]"), ForeignKey("[dbo].[Countries]", "ID"), LeftJoin("jCountry"), TextualField("CountryName")]
        [LookupEditor(typeof(CountryRow)),LookupInclude]
        public Int64? CountryId
        {
            get { return Fields.CountryId[this]; }
            set { Fields.CountryId[this] = value; }
        }

CustomerForm:
public Int64 CountryId { get; set; }

[LookupEditor(typeof(Entities.SystemsRow), CascadeFrom = "CountryId", CascadeField = "CountryId")]
public Int64 CityId { get; set; }


Using the above code, the Country Combo box displays the list of countries and the selected country (based on city id) is also getting selected for existing customers. But, City combo box nothing is getting show (the list is not getting populated).

**Comment by volkanceylan** [comment]
Check your lookup. Honestly i'm getting tired of answering same thing. There are so many samples, so many answered questions, and still people who say it doesnt work.

**Comment by sasinallatech** [comment]
Appologise. Got the issue. The issue is with naming. It is expecting the Same name for CountryID in CustomerRow and CityRow. Thanks for your response.
