### ISSUE TITLE
customizing the design of column-specific filters

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1094]
To be able to customize the design of the column-specific filters, do we need to modify core libraries and if so will this affect other forms using these filters.
For example: If we somehow shrink the width of the filter on the screenshot below, will all other forms automatically show smaller fields for that filter?
i.e On this form I need the filter to be as wide as two-three char. But on another form I need it to be full length.

"Yes/No" will help me decide if it is worth spending the time.

There could be also a third answer. "You need to write your own".

I just need the big picture.

![columnspecificfilters](https://cloud.githubusercontent.com/assets/19690830/17858266/08d35670-6853-11e6-8fac-9db1862454a1.png)

**Comment by mlutzow** [comment]
I would think you can you use the [Width(xx)] command in your row or column .cs file(s) and then in the .less files adjust the width of the other columns there.

**Comment by volkanceylan** [comment]
Use .s-YourGrid .s-YourEditor to apply width to your filters. No need for modifying core.

**Comment by SimeonDD** [comment]
Closing this. Too much not clear (my issue not yours).
mlutzlow's advice I tried but it has only effect on the grid, not the filter.

Tried to guess the syntax Volkan suggested. Not working 'cause I am not familiar with other things.

`.s-modFin-DefBudgetDialog {
    > .size { width: 650px; }
    .caption { width: 150px; }
    .s-FinancialYearEditor  { height: 100%; margin: 6px; width: initial !important; min-width: 100%; }
}

.s-FinancialYearEditor {
   width: 40px;
}`

**Comment by mlutzow** [comment]
Okay, As a last experiment though would you try changing a couple of things.  I believe in overkill on some of this stuff so I've applied the below on my xyzColumn.cs, xyzRow,cs, and xyzForm.cs files. 

`        
[DisplayName("Year")]
        [Width(60)]
        public Int32? Year
        {
            get { return Fields.Year[this]; }
            set { Fields.Year[this] = value; }
        }
`
Include whatever other attributes / decorators you would like to / need to use.

In the site.<yourname>.less file or whatever .less file configuration you have, change the assignment from width(650px) to min-width(75px) and see if that improves anything for you.

`
    @media (**min-width: 75px**) {
        .field.ProductCode, .field.ProductGroup, .field.CustomerNumber {
            .IntialCodeProperties
        }
    }
`

**Comment by ramveersgh** [comment]
@SimeonDD 

Using saltarelle, The is an option to set element width while adding equality filter but don't know how it will be in TypeScript ecause i am not using typescript. 
```
  AddEqualityFilter<StringEditor>(Fields.WO, element: e1 =>
            {
                e1.Width(90);
            });
```

Using less style. You can set is with following in your grid class, where 1 is the position from starting.
```
.s-TranzolMining-CreateInvoiceGrid {
     .quick-filter-item:nth-child(1) {
            .s-StringEditor {
                width: 30px !important;
            }
        }
}
```
Hope this will fix for you.

**Comment by SimeonDD** [comment]
Thanks ramveersgh! Will give it a shot.
