### ISSUE TITLE
Using an equation in a new List Request

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1095]
I am writing a new list handler and have a semi complex query I need to execute. Being very new to SqlQuery Objects and Criteria I am just not quite sure the direction to take. I've been trying to read up on it but I'm still at a block on this one. Not sure how to set the equation in criteria, I know using an expression is not recommended. My query is 

`select N.vendor_num,n.name,n.TIER_LEVEL RANK, n.PHONE,n.EMAIL,n.CITY,n.ST,n.zip,3956 * 2 * ASIN(SQRT( POWER(SIN((n.lat - 35.8395) * pi()/180 / 2), 2) + COS(n.lat * pi()/180) * COS(35.8395 * pi()/180) * POWER(SIN((n.lng - -83.4803) * pi()/180 / 2), 2) )) 
actualdistance,count(order_id) ordersdone,max(o.sign_date) latestdate from NOTARY n left outer join n_order o on n.VENDOR_NUM 
= o.VENDOR_NUM where (n.lat between (35.8395-2)and (35.8395+2)) and (n.lng between(-83.4803-2)and (-83.4803+2)) and 
(3956 * 2 * ASIN(SQRT( POWER(SIN((n.lat - 35.8395) * pi()/180 / 2), 2) + COS(n.lat * pi()/180) * COS(35.8395 * pi()/180) * 
POWER(SIN((n.lng - -83.4803) * pi()/180 / 2), 2) )))<n.MAXDISTANCE group by N.vendor_num,n.name,n.TIER_LEVEL, n.PHONE,n.EMAIL,
n.CITY,n.ST,n.zip,n.lat,n.lng order by 3956 * 2 * ASIN(SQRT( POWER(SIN((n.lat - 35.8395) * pi()/180 / 2), 2) + 
COS(n.lat * pi()/180) * COS(35.8395 * pi()/180) * POWER(SIN((n.lng - -83.4803) * pi()/180 / 2), 2) ))`

Is something like this possible with SqlQuery Object? Has anyone out there done similar? I would be forever grateful for some insight. Thanks   *By the way my entityRows.cs are Notary and NOrder, and they are not foreign key linked. I am writing the new list request in my Notary files. I believe my SQLQuery will be something like this:

            var n = Entities.NotaryRow.Fields;
            var o = Entities.NOrderRow.Fields;
            query 
                .Select(n.VendorNum)
                .Select(n.Name)
                .Select(n.TierLevel, "Rank")
                .Select(n.Phone)
                .Select(n.Email)
                .Select(n.City)
                .Select(n.St)
                .Select(n.Zip)
                .Select('my equation somehow here', "Actual Distance")
                .Select("Count(Order_ID)", "Orders Done")
                .Select("max")
                .Select("(o.sign_date)", "Latest Date")
                .From (n)
                .LeftJoin(o, n.VendorNum == o.VendorNum)
                .Where( 
                      new Criteria("My equation again < n.Maxdistance"))
                .GroupBy(n.VendorNum)
                .GroupBy(n.Name)
                .GroupBy(n.TierLevel)
                .OrderBy("My equation yet again")

**Comment by volkanceylan** [comment]
If you will use multiple fields collections, you need to alias them with .As("n"), otherwise they ll both have t0 aliases.

I would define those expressions on my row. If not, you can always use inline expressions as SqlQuery does no validation.

new Criteria(" .... ") < n.MaxInstance

**Comment by volkanceylan** [comment]
Put your equation to some string and reuse it

**Comment by jdready5** [comment]
Thank you!
