### ISSUE TITLE
Dialog class is not found! hatası

### ISSUE THREAD

**Issue by ComertAhmetSahin** [volkanceylan/Serenity#1096]
LookupEditör tanımlıyorum. Gridde ve Dialogta herşey doğru çalışıyor fakat Inplace Add butonuna tıkladığımda "dialog class is not found!"  hatasıyla karşılaşıyorum.
Dökümanda bulunan yönergelere uyuyorum "ModuleName.RowType" şeklinde belirledim LookupScripti yinede sonuç aynı.

[Parametrebirimtur.txt](https://github.com/volkanceylan/Serenity/files/432035/Parametrebirimtur.txt)
[tanim_urun.txt](https://github.com/volkanceylan/Serenity/files/432036/tanim_urun.txt)

ilginiz için teşekkür ederim

**Comment by VictorTomaili** [comment]
`[LookupScript("RANDEVU.Tanim_Urun")]` lookup adı `[LookupScript("RANDEVU.TanimUrun")]` şeklinde olması gerekiyor. Böylece script tarafında `TanimUrunDialog` tespit edilebilir. Bunun için TanimUrunDialog oluşturulmuş olması gerekiyor.

**Comment by ComertAhmetSahin** [comment]
Proje ismini değiştirdiğimden kaynaklanan bir hataymış

ScriptInitialization.ts içersine
Q.Config.rootNamespaces.push('SERENEDEMO');

ekleyerek sorunu giderdim.  teşekkür ederim
