### ISSUE TITLE
Cmd.exe issue with serenity projects

### ISSUE THREAD

**Issue by AllamSudhakara** [volkanceylan/Serenity#1098]
Hi, I am getting side by side configuration issue along with CMD.exe is unable to be accessed. They started suddenly and no effort is unable to cleared off. What could be the reason for this? it seems xml configuration for less compiling in the target build is causing some issue. Could you please provide some direction for resolving the issue?

**Comment by volkanceylan** [comment]
No idea. You may disable less compilation by removing that line from csproj and use an external compiler

**Comment by AllamSudhakara** [comment]
Do you have a suggestion on which external compiler is best? And also, I
would be grateful if you could provide relevance csproj replacement.

Regards,
Sudhakar

**Comment by volkanceylan** [comment]
Line under CompileSiteLess. I don't have any replacement. Check your antivirus.
