### ISSUE TITLE
Error on save due to TimeEditor

### ISSUE THREAD

**Issue by Me-Kal** [volkanceylan/Serenity#1099]
hi ,
 i have field TimeIn , datatype in database time(7)   , if i use TimeEditor , it gives error on save "Unexpected token when deserializing row: Integer" , but if i dont use TimeEditor there is no error.

SurveyForm.cs

 [TimeEditor(StartHour=7,IntervalMinutes=5,NoEmptyOption = true,EndHour=16)]
 public TimeSpan TimeIn { get; set; }

**Comment by volkanceylan** [comment]
TimeEditor is for integer columns, counting number of mins

**Comment by Me-Kal** [comment]
thanks for fast reponse , is there any editor i can use for my case ?

**Comment by Me-Kal** [comment]
thanks

**Comment by cengkaplan33** [comment]
@Me-Kal  did you solve your problem. ? I have same problem. Did you write a new timespan editor. san you help me too?
