### ISSUE TITLE
How to validate duplicate item  while adding from dialogue to grid on editor

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#110]
How to validate duplicate item  while adding from dialogue to grid on editor.

The example like 

Northwind -> Orders -> New Order -> New Order Details  

It shows alert for duplicate products.

I want to implement same functinality in my project.

**Comment by volkanceylan** [comment]
See OrderDetailsEditor.ValidateEntity method

**Comment by chetanjoshi1988** [comment]
![new batch](https://cloud.githubusercontent.com/assets/16666095/12353545/d7502f08-bb44-11e5-82dc-04bd954b7386.png)
![newbatchweeklyoff](https://cloud.githubusercontent.com/assets/16666095/12353561/f5243baa-bb44-11e5-97cc-ce86a041cd95.png)

**Comment by chetanjoshi1988** [comment]
Thanks Volkan !
