### ISSUE TITLE
SaveAndAddNew button in a Form

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1100]
How we can add SaveAndAddNew button in a form.
When it Clicked, it will save Entity , shows success message and clear all fields for adding other Entity data.
regards
Shailesh

**Comment by shaileshbc** [comment]
Dear Volkan,
i tried with following code in xyzDialog.ts. 
It now clears all fields content in a dialog, but when i try to populate some fields, it is not working.
[code.txt](https://github.com/volkanceylan/Serenity/files/441638/code.txt)
can you help me with this.
regards
Shailesh

**Comment by adhikamafran** [comment]
reference to this issue  https://github.com/volkanceylan/Serenity/issues/890
please try this code in your dialog.

protected getToolbarButtons(): Serenity.ToolButton[]
        {
            let btns = super.getToolbarButtons();
            let newBtn: Serenity.ToolButton =
                {
                    title: "Save And New",
                    onClick: () =>
                    {
                        let req = this.getSaveRequest();
                        this.save(() => {
                            let ent: MovieRow = {};
                            this.loadEntity(ent);
                        });
                        
                    }
                }

            btns.push(newBtn);
            return btns;
        }

**Comment by shaileshbc** [comment]
thank you, so much adhikamafran ,
you solved my problem.
regards
Shailesh
