### ISSUE TITLE
Customizing Dialogs

### ISSUE THREAD

**Issue by mohammad0011** [volkanceylan/Serenity#1102]
Hi,

Is there any simple explanation or tutorial on how to customize dialogs in serenity?
I want to add custom buttons in the dialog (not in the toolbar) next to some fields to execute some ajax calls.

Also, I have this problem in Visual studio, I hope you can help me to solve it,
the .ts files appear as plain text as the were opened in note pad (see the attached image), and the intellisense is not working with .ts files.

![attach](https://cloud.githubusercontent.com/assets/20207223/17920134/2aaaf8a0-69db-11e6-8eac-8e84915056ee.jpg)

thanks in advacen

**Comment by samdubey** [comment]
[Please check here](https://github.com/Microsoft/TypeScript/issues/6958)
