### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by ntfox** [volkanceylan/Serenity#1103]
Hi,
When have hotkey operators can faster work with system, 
example New = f2, edit =f3, delete in form= f8, move in rows = arrow keys, Next Page= PgDn, Prior Page= PgUp, ...

**Comment by shaileshbc** [comment]
volkan can we use jquery.hotkeys from https://github.com/jeresig/jquery.hotkeys, for this?

**Comment by volkanceylan** [comment]
There is already hotkey support in toolbar buttons using mousetrap. Alt+S save etc.

**Comment by wdhodges** [comment]
Are they implemented into the project by default?

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/blob/master/Serenity.Script.UI/EntityDialog/EntityDialog_Toolbar.cs
