### ISSUE TITLE
New Button in Dialog - Problem with Ajax - How to get value from Callback function

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#1106]
Hi,

Has anyone solved an issue with getting value from a XML url to a field in a dialog?

I have this code but it doesn't write any value to my field "CurrencyRateSdr" in my dialog form. The browser console shows that the XHR/functions loaded without exceptions but no value is returned to my field.

`

        protected getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            buttons.push({
                title: 'Get Xrate',
                cssClass: 'send-button',
                onClick: () => {
                    var x = new XMLHttpRequest();
                    x.onreadystatechange = function () {
                        if (x.readyState == 4 && x.status == 200) {
                            var e = getXDR(x);
                            document.getElementById("PerDiem_Ferdir_UtanlandsDialog9_CurrencyRateSdr").innerHTML = e.toString();
                        }
                    };
                    x.open("GET", "http://www.sedlabanki.is/xmltimeseries/Default.aspx?DagsFra=LATEST&TimeSeriesID=4097&Type=xml", true);
                    x.send();
                    
                    function getXDR(xml) {
                        var c = xml.responseXML.lastChild.childNodes[2].childNodes[7].childNodes[1].childNodes[3].textContent;
                        var d = Q.parseDecimal(c);
                        return d;
                    }                    
                }
            });

            return buttons;
        }`

Any suggestions?

**Comment by volkanceylan** [comment]
Are you sure it hits document.getElementById line? If so console.log value there to see, and check that your ID is correct, as it is dynamic, it won't be UtalandsDialog9 everytime.

Use this.ById("CurrencyRateSdr").text(e.toString())

**Comment by volkanceylan** [comment]
Also, x.onreadystatechange = ()=> {
}

Otherwise you'll lose "this", e.g. dialog reference

**Comment by biggikalli** [comment]
IT WORKS!

Thank you so much for getting me on the right track... I did everything that you said and that did the trick. 
But because the "CurrencyRateSdr" is a decimal field (I forgot to mention), I only had to change _...RateSdr").text(e.toString())_ to _...RateSdr").val(e)_

With that, the value was shown correctly in the field :)

![image](https://cloud.githubusercontent.com/assets/15879719/17968402/291d08b6-6abc-11e6-916e-43d373e21d0e.png)


Thank you Maestro!

**Comment by volkanceylan** [comment]
You're welcome, if so use

**Comment by volkanceylan** [comment]
form.CurrencyRateSdr.value = e

**Comment by biggikalli** [comment]
Hi @volkanceylan 

Thank you. You are absolutely right - that is much better as I had numerical issues with the currency rate value if using _.val(e)_

Thank you for all your help, it has been priceless to me :)
