### ISSUE TITLE
how to handle Trigger

### ISSUE THREAD

**Issue by manivishnupriya** [volkanceylan/Serenity#1107]
There is a Trigger in tableSample
When update request for tableSample sent in serene application, I'm getting error
"Query affected 2 rows while 1 expected!" and update fails!

How to handle this? Please help

**Comment by manivishnupriya** [comment]
Also when i use "ON UPDATE CASCADE" as a constraint in tableSample, the update request for tableSample sent in serene application throws error "Query affected 2 rows while 1 expected!"

**Comment by volkanceylan** [comment]
SET NOCOUNT ON in trigger
