### ISSUE TITLE
RetrieveResponse vs ListResponse

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1108]
Could you please add a high-level explanation on the difference and uses of RetrieveResponse<myRow> and ListResponse<myRow> in the ...Endpoint.cs

If the answer is like "Well, if you knew <that> you would not have asked the question" then a reference to <that> would be much appreciated.

Many thanks!

**Comment by volkanceylan** [comment]
Retrieve is single fetch by ID, List is multiple

**Comment by SimeonDD** [comment]
When is Retrieve used in an Endpoint.cs? For the edit-popup maybe?

**Comment by volkanceylan** [comment]
Yes, dialog loads entity with Retrieve, grid loads them with List. You may check browser console for XHR requests.
