### ISSUE TITLE
Another noob question regarding calling a service from typescript

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1109]
Not an issue with the platform at all, just a noob question for me. How do I make the call to a service (MyListHandler) from typescript in the onViewSubmit? I've seen a lot of code suggestions with buttons and such but I am so new to typescript and javascript (I come from windows forms) that any suggestions would be helpful. I keep going through the guide and the questions in here but I am missing something so basic still (I know it's basic, and embarrassing) I will be making a few of these calls in different places throughout the program. I am not sure how to correctly make the call here in myGrid.ts:
        
                protected onViewSubmit() {
                    if (!super.onViewSubmit()) {
                        return false;
                    }
                //Do something here to call service........
                NotaryManager.NotaryService.ListByZip(<any>)
                }

I have my endpoint as such:
        
        public ListResponse<MyRow> ListByZip(IDbConnection connection, ListRequest request)
        {
            return new MyRepository().ListByZip(connection, request);
        }

My Repository:
        
        public ListResponse<MyRow> ListByZip(IDbConnection connection, ListRequest request)
        {
            return new MyListHandlerZip().Process(connection, request);
        }

        private class MyListHandlerZip : ListRequestHandler<MyRow>
        {

            protected override void OnBeforeExecuteQuery()
            {
                string eq1 = "3956 * 2 * ASIN(SQRT( POWER(SIN((n.lat - 35.8395)* pi() / 180 / 2), 2) OS(n.lat * pi() / 180) * COS(35.8395 * pi() / 180) * POWER(SIN((n.lng - -83.4803) * pi() / 180 / 2), 2) ))";
                string eq2 = "(n.lat between (35.8395-2)and (35.8395+2)) and (n.lng between(-83.4803-2)and (-83.4803+2)) and (3956 * 2 * ASIN(SQRT(POWER(SIN((n.lat - 35.8395) * pi() / 180 / 2), 2) + COS(n.lat * pi() / 180) * COS(35.8395 * pi() / 180) * POWER(SIN((n.lng - -83.4803) * pi() / 180 / 2), 2))))";
                base.OnBeforeExecuteQuery();
                var query = new SqlQuery();
                var n = Entities.NotaryRow.Fields.As("n");
                var o = Entities.NOrderRow.Fields.As("o");
                query
                    .Select(n.VendorNum)
                    .Select(n.Name)
                    .Select(n.TierLevel, "Rank")
                    .Select(n.Phone)
                    .Select(n.Email)
                    .Select(n.City)
                    .Select(n.St)
                    .Select(n.Zip)
                    .Select(eq1, "Actual Distance")
                    .Select("Count(Order_ID)", "Orders Done")
                    .Select("max(o.sign_date)", "Latest Date")
                    .From(n)
                    .LeftJoin(o, n.VendorNum == o.VendorNum)
                    .Where(
                    new Criteria(eq2 + "< n.Maxdistance"))
                    .GroupBy(n.VendorNum)
                    .GroupBy(n.Name)
                    .GroupBy(n.TierLevel)
                    .OrderBy(eq1);
         
                //Check query, remove when successful
                Console.WriteLine(query.ToString());
            }

**Comment by volkanceylan** [comment]
Hi @jdready5,

I'm not sure what you are trying to do at the moment, but to call the service anywhere you just write NotaryService.List({ your list request params }, response => { do something with response.Entities; });

Why onViewSubmit, i'm not sure though

**Comment by volkanceylan** [comment]
Also you are creating a new query in OnBeforeExecuteQuery, so your new query won't be executed and you are not actually modifying the query that will be executed soon.

**Comment by jdready5** [comment]
Okay, I was doing onViewSubmit because I wasn't quite sure where to call it (still experimenting) and OnBeforeExecuteQuery, that makes sense I will correct that. (That's why I finally had to ask even though I really didn't want to), but I just wasn't sure where to call the service at or to do it correctly and efficient. I'll continue re-working it. Thank you

**Comment by tonysader** [comment]
> Hi @jdready5,
> 
> I'm not sure what you are trying to do at the moment, but to call the service anywhere you just write NotaryService.ListByZip({ your list request params }, response => { do something with response.Entities; });
> 
> Why onViewSubmit, i'm not sure though

Anywhere in the client side?? When I use this in the xyzGrid, the List Request and the connection is not defined, Why ??!!


```
protected onViewSubmit(): boolean {
            if (!super.onViewSubmit()) {
                return false;
            }
            var lsi = HolidayService.List(connection, new Serenity.ListRequest, response => { });

            return true;
        }
```

**Comment by tonysader** [comment]
And if I put it in the script of .cshtml page Serenity.ListRequest is not defined
