### ISSUE TITLE
How to Add Multiple Checkbox 

### ISSUE THREAD

**Issue by sagirnar** [volkanceylan/Serenity#111]
How to add Multiple Check selection (Checkbox) for Inserting into single table.

**Comment by volkanceylan** [comment]
Add muitiple checkbox columns if it is one table. Otherwise you need something like role selection.

**Comment by PanChenhao** [comment]
Do you have any sample or code? I also need to add multiple checkbox.

**Comment by volkanceylan** [comment]
There is a how to in guide.

**Comment by volkanceylan** [comment]
About integrating third party control

**Comment by PanChenhao** [comment]
Thanks, I made it.

**Comment by PanChenhao** [comment]
But another question, how I can put several values in one column. such as "Representative", one custom would have several Representatives, I want to put Representatives as a string(Nancy Davolio, Andrew Fuller, Janet Leverling) in a column in Custom list.

**Comment by volkanceylan** [comment]
This would be bad performance wise. Anyway it's out of scope to explain here.

**Comment by volkanceylan** [comment]
2.2.0 has list of representatives in Custom Grid column
