### ISSUE TITLE
Summary of ways to populate the grid with SQL code

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1110]
It took a long time to consolidate some workable info from the forum.
I am summarizing here some workable approaches to use SQL or stored procedures.
This is not an exhaustive manual but rather meant as a time saver.
It is just enough to get you started.

I learned and used code from here:
_(sincere thanks to all who publish the actual answers in their issues)_
https://volkanceylan.gitbooks.io/serenity-guide/content/fluent_sql/sqlquery_object.html
Estrusco: #924
nmajeed: #128 (offered the break-through code for me)

Asking for assistance: 
Please **do not post questions for help** in this issue. 
If you have a clearly understood example, you could add it below. 
If you need help, please open a separate issue.

**Prerequisites:**
Samples are written against a table and a stored procedure like this:
![sqltestobjects](https://cloud.githubusercontent.com/assets/19690830/17985134/705d3414-6ae2-11e6-91d6-8375364b1b5a.png)

**Calling a stored procedure (nmajeed):**
![sql_listresponse_sp](https://cloud.githubusercontent.com/assets/19690830/17985160/90e70304-6ae2-11e6-9972-a5aa33fa2e1d.png)

**Using standard SQL:**
![sql_listresponse_sql](https://cloud.githubusercontent.com/assets/19690830/17985188/b022a2aa-6ae2-11e6-99ec-fc0fadef3944.png)

**Using Serenity SqlQuery():**
Total count hard-coded to show link to page object
![sql_listresponse_sqlquery](https://cloud.githubusercontent.com/assets/19690830/17985225/e5c2d506-6ae2-11e6-962c-c5a4c405b0bd.png)

**Comment by volkanceylan** [comment]
Thanks for sharing, would be useful for Wiki also ;)
