### ISSUE TITLE
Customizing the Serenity Entity Grid row height (including cell contents)

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1111]
I'm not sure if this is purely a SlickGrid issue, or Serenity is doing some sort of override.
I can't change the row height of the entity grid used by serenity, with the cell's data and input following suit. I've tried:
1. changing `height` by CSS of `.slick-row, .slick-cell` elements. The rows did not increase in height but the cell text and inputs went weird, like they're being hidden beneath their respective row's bottom border with only their top showing.
2. setting the `rowHeight` option in the grid constructor:
`
constructor(container: JQuery) {
          super(container);
          this.slickGrid.setOptions({
                rowHeight: 50
          });
}
`
The rows increased in height _but the cell text and inputs are still the same size._

3. Tried this: http://stackoverflow.com/questions/17262236/what-is-the-recommended-approach-to-style-a-slickgrid but still the same effect as number 2.

How do I customize the Serene grid row heights (make higher or smaller)? This is to accomodate font changes, and/or tapping area in mobile. Thanks.

**Comment by adhikamafran** [comment]
if you mean a word wrap content, this might be help https://github.com/volkanceylan/Serenity/issues/425.

cmiiw.

**Comment by john20xdoe** [comment]
@adhikamafran no, not word wrap.
I meant, from this:
![grid 1](https://cloud.githubusercontent.com/assets/14521605/17993347/9a8f5e02-6b81-11e6-954b-8a3af952f88f.PNG)

to this:
![grid 2](https://cloud.githubusercontent.com/assets/14521605/17993352/9fd52838-6b81-11e6-9499-aafb8405f137.PNG)



Ok, so I was able to do it using `rowHeight` slickgrid option and css (all set to !important) to override the height set in a `style` block (containing slickgrids' heights) that appends to the `<head>` element.

1. in the typescript file for grid, I put ` rowHeight` setting in the constructor:
`
this.slickGrid.setOptions({
                rowHeight: 50
});
`
Then match it in the css/less in the next step.

2. Then in the custom .less file (loaded after Serene's), containing my own customizations:
`
.slick-row
{
    height: 50px !important;
    line-height: 50px !important;
    > * {
        height: 46px !important;
        line-height: 46px !important;
    }
}
.slick-cell{
    border-bottom: 0px !important;
    height: 50px !important;
    > * {
        height: 43px !important;
    }
}
`

Just customize the sizes as you need.
Displayed as intended for now in Chrome and IE 11. I;m not sure if it reflects in ALL the grids in all modules.

**Comment by volkanceylan** [comment]
There are several samples in Serene that changes row height. Proper way is to use getSlickOptions. That doesn't affect line height / editor height though, which should be set by css.

**Comment by rhemasystems** [comment]
Hi please how doI also increase the height of the grid container, currently I have a vertical scrollbar for just 5 rows
![gridrow](https://user-images.githubusercontent.com/50826372/135611986-5f644a40-79fb-4e1c-ae88-c7306401ffdf.PNG)

**Comment by VictorTomaili** [comment]
@rhemasystems please use [discussions](https://github.com/serenity-is/Serenity/discussions)

**Comment by rhemasystems** [comment]
Thanks, but please can you show me which of the discussion addresses that issue because i see a whole list of discussions

**Comment by VictorTomaili** [comment]
create new one
