### ISSUE TITLE
Blank Administration Pages

### ISSUE THREAD

**Issue by rsbatacjr** [volkanceylan/Serenity#1112]
Greetings, I'm in my final test and able to publish on my dev iis machine. I've noticed that all my administration pages (user manager, language) are all blank, since it was working from the beginning and didn't require me to create more than two user account I didn't know when it was happen.

Did anyone experience this or can someone please help me restore administration pages?

**Comment by samdubey** [comment]
Seems like issue with Typescript install / update

**Comment by rsbatacjr** [comment]
Thanks, that's also what I am thinking. I have captured the error list and tried unblocking clienttype file but no luck.
![error_screenshot](https://cloud.githubusercontent.com/assets/16199919/17994917/95a919c4-6b8f-11e6-9495-f1ccc37d07ff.png)

Any solution in mind?

**Comment by volkanceylan** [comment]
Check your app pool is in integrated mode. Check file permissions. And always see browser console first.

**Comment by rsbatacjr** [comment]
Thanks for the reply, may app pool in iis is in integrated mode. I don't have console error. Those error came from Visual Studio, I thought I just forgot to run "Transform All T4 Template". I happened when my visual studio update some component automatically.
