### ISSUE TITLE
is it possible to update 2 entity on one form any example 

### ISSUE THREAD

**Issue by shailendrasingh03** [volkanceylan/Serenity#1114]
there is requirement of updating 2 entity on one form both have one filed common any example on this .

**Comment by mayatstafford** [comment]
That would be an extension table.    
I had a situation where I had the following tables:
Event: Id(Guid), Name, Display
Customer: Id(Guid), FirstName, LastName, Address etc...
EventCustomer: Id(Guid), EventId(Guid),  CustomerId(Guid),HotelName, HotelRoomNumber

Only 1 event would have  display set to 1 at a time.
CustomerRow:
`
		[LeftJoin("jEventCustomer", "EventCustomer", "jEventCustomer.[CustomerId] = T0.[Id] AND ((jEventCustomer.[Id] is null) or (NOT(jEventCustomer.[Id] Is null))) ")]
    public sealed class CustomerRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), PrimaryKey, Insertable(true)]
        public Guid? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }
		
        [DisplayName("First Name"), Size(30), QuickSearch]
        public String FirstName
        {
            get { return Fields.FirstName[this]; }
            set { Fields.FirstName[this] = value; }
        }

        [DisplayName("Last Name"), Size(50), QuickSearch]
        public String LastName
        {
            get { return Fields.LastName[this]; }
            set { Fields.LastName[this] = value; }
        }

        [DisplayName("Address 1"), Size(255)]
        public String Address1
        {
            get { return Fields.Address1[this]; }
            set { Fields.Address1[this] = value; }
        }

        [DisplayName("EventCustomerId"), Expression("jEventCustomer.[Id]"), LookupInclude]
        public Guid? EventCustomerId
        {
            get { return Fields.EventCustomerId[this]; }
            set { Fields.EventCustomerId[this] = value; }
        }

        [DisplayName("CustomerId"), Expression("jEventCustomer.[CustomerId]")]
        public Guid? CustomerId
        {
            get { return Fields.CustomerId[this]; }
            set { Fields.CustomerId[this] = value; }
        }

        [DisplayName("Hotel"), Updatable, Expression("jEventCustomer.[HotelName]")]
        public String HotelName
        {
            get { return Fields.HotelName[this]; }
            set { Fields.HotelName[this] = value; }
        }
        [DisplayName("Hotel Room #"), Updatable, Expression("jEventCustomer.[HotelRoomNumber]"), Size(50)]
        public String HotelRoomNumber
        {
            get { return Fields.HotelRoomNumber[this]; }
            set { Fields.HotelRoomNumber[this] = value; }
        }

        [DisplayName("Event"), Expression("jEventCustomer.[EventId]"), ForeignKey("Event", "Id"), LeftJoin("jEvent"), TextualField("EventName"), LookupInclude]
        public Guid? EventId
        {
            get { return Fields.EventId[this]; }
            set { Fields.EventId[this] = value; }
        }

        [DisplayName("Event"), Expression("jEvent.[EventName]"), LookupInclude]
        public string EventName
        {
            get { return Fields.EventName[this]; }
            set { Fields.EventName[this] = value; }
        }

        [DisplayName("Event Display"), Expression("jEvent.[Display]"), NotNull, DefaultValue(true), LookupInclude]
        public Int32? EventDisplay
        {
            get { return Fields.EventDisplay[this]; }
            set { Fields.EventDisplay[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.FirstName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public CustomerRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            //Customer
            public StringField Address1;
            public StringField FirstName;
			public GuidField Id;
            public StringField LastName;
            //EventCustomer
            public GuidField CustomerId;
            public GuidField EventCustomerId;
            public StringField HotelName;
            public StringField HotelRoomNumber;
            //Event
            public GuidField EventId;
            public StringField EventName;
            public Int32Field EventDisplay;


          public Int32Field Registered;
            public RowFields()
                : base("[dbo].[Customer]")
            {
                LocalTextPrefix = "Customer.Customer";
            }
        }
    }
}`

RegistrantRepository:
 ` private class MySaveHandler : SaveRequestHandler<MyRow>
        {

            public static Event.Entities.EventRow GetActiveEventId(IDbConnection connection)
            {
                var row = new MyEventRow();
                if (new SqlQuery().From(row)
                    .Select(fld.Id)
                    .Where(new Criteria(fld.Display) == 1)
                    .GetFirst(connection))
                {
                    return row;
                }

                return null;
            }
            protected override void SetInternalFields()
            {
                base.SetInternalFields();

                if (IsCreate)
                {
                    var tempGuid = Guid.NewGuid();
                    Row.Id = tempGuid;


                }
            }

            protected override void AfterSave()
            {
                base.AfterSave();

                if (Row != null)
                {
                    Row.EventId = GetActiveEventId(this.UnitOfWork.Connection).Id;

                    if (Row.EventCustomerId != null)
                    {
                        var eventCustomerTableFields = MyEventCustomerRow.Fields;
                        var updList = Connection.List<MyEventCustomerRow>(eventCustomerTableFields.Id == this.Row.EventCustomerId.Value).First();
                        updList.HotelName = Row.HotelName;
                        updList.HotelRoomNumber = Row.HotelRoomNumber;

                        var saveRequest = new SaveRequest<MyEventCustomerRow>();
                        saveRequest.Entity = updList;
                        saveRequest.EntityId = updList.Id;
                        new Event.Repositories.EventCustomerRepository().Update(this.UnitOfWork, saveRequest);
                    }
                    else
                    {
                        var updList = new MyEventCustomerRow();
                        updList.CustomerId = Row.Id;
                        updList.EventId = Row.EventId;
                        updList.HotelName = Row.HotelName;
                        updList.HotelRoomNumber = Row.HotelRoomNumber;

                        Connection.Insert<Event.Entities.EventCustomerRow>(updList);
                    }
                }
            }
        }`

**Comment by shailendrasingh03** [comment]
hi thanks a lot .. but i am looking for something which is available in base ..  however this will work ..

**Comment by fzhenmei** [comment]
Looking for it too .

**Comment by awesomegithubusername** [comment]
Hi;

You can try to override one of the save methods (in your first entity repository):
```c#
        private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void AfterSave()
            {
               base.AfterSave();
               var secondEntityrow = this.Connection.ById<MultiTenancy.Client.Entities.secondEntityRow>(this.Row.secondEntityId);
               secondEntityrow.commonField = this.Row.commonField;
            }
				
                Connection.UpdateById(secondEntityrow, ExpectedRows.One);
           }
        }
```
