### ISSUE TITLE
Sizing of Dialog

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1116]
Hi there! First of all, this is an amazing template!!! Great Great Work!

I followed  your Movie tutorial to change the dimensions of the dialog by changing the following style in site.less file

.s-SaludDB-MedicosDialog {
    > .size { width: 650px; height: 564px; }
    .caption { width: 150px; }
}

I add the Height attribute, but the autogenerated dialog doesn't seems to be aware of...can you point me in the right direction?

**Comment by volkanceylan** [comment]
Check that your css class matches exact css class your dialog has. Same case.

**Comment by javaman63** [comment]
the form autogenerated never use the autogenerated class .s-SaludDB-MedicosDialog, i dont know why

i can't find the error
