### ISSUE TITLE
use of tilde ~ in Razor scripts

### ISSUE THREAD

**Issue by SimeonDD** [volkanceylan/Serenity#1117]
Hi there,
Could you please share any reference to theory or direct explanation of the use of tilde in scripts similar to what Serene has in AccountResetPassword.cshtml.
I do know that when used with path it means relative path reference.
But what does it mean when it is used in id=
Like below - what other object will take **button id="~_SubmitButton"** or **form id="~_Form" action=""** and translate it into something else?

Many thanks!!

**Comment by volkanceylan** [comment]
Every widget has some unique prefix. ~_ is replaced with that prefix. This helps prevent clashes when multiple dialogs with similar ID values are opened, cascaded etc.

**Comment by volkanceylan** [comment]
This prefix changes everytime, so you should use this.byId("xyz") to find elements, not $('#xyz') or $('#Serene_MyDialog17_xyz") etc
