### ISSUE TITLE
admin / sereni credentials do not work on a new install

### ISSUE THREAD

**Issue by ckelsoe** [volkanceylan/Serenity#1119]
Just downloaded and installed Serenity. The default credentials do not work and an unhandled error occurs. The admin user is in the dbo.Users table. Any idea what the true password for the admin user is?

**Comment by ckelsoe** [comment]
I created a new account, then went to the DB and set it as active. I can now log in using the new account.

**Comment by volkanceylan** [comment]
Probably was a temporary problem.
