### ISSUE TITLE
Memory Grid not refreshed on apply.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#1120]
Hi

I hide the memory grid for new dialog. On saving of the dialog, I inserted some row in table related to memory grid by executing stored procedure.
But when apply button is clicked for save on new dialog, form get refreshed and memory grid is displayed but rows are not comes in memory grid. After closing the dialog and reopen it work fine.
Here is screen for more help - 
![memory grid issue](https://cloud.githubusercontent.com/assets/2145218/18032003/8238512a-6d15-11e6-84e1-cb227f56c62e.png)

Please help to resolve it. I am using Serenity 2.3.3.0.

**Comment by volkanceylan** [comment]
After save completes, dialog latest entity by calling Retrieve service, see why your retrieve service returns empty values.

**Comment by ramveersgh** [comment]
Thanks @volkanceylan for reply!

I check the Retrieve service and that is return the item rows for grid correctly and these row are also available in loadEntity event of InvoiceDialog.ts but not shown in the grid.
Here is the screen shot of debug value of ItemList in loadEntity event - 
![memory grid issue1](https://cloud.githubusercontent.com/assets/2145218/18035528/34d8db24-6d75-11e6-9170-25b94982f858.png)

**Comment by volkanceylan** [comment]
How do you hide create that grid. You are probably doing something non-standard way.

**Comment by ramveersgh** [comment]
Hmmm, You seems right!
I am hiding the grid with its category in following way -
```
this.form.ItemList.element.closest(".category").toggle(!this.isNewOrDeleted());
```
If i comment above line then grid shows at the time of creation and row is also inserted successfully in the grid after save. What is the correct way to hide the memory grid with its category name?

**Comment by ramveersgh** [comment]
Okk.. Hiding the grid category using toggle is causing the issue. 
So temporary i done following workaround which is working. Instead of using toggle i am adding and removing the class - 
```
 if (this.isNewOrDeleted()) {
                this.form.ItemList.element.closest(".category").addClass("hideGrid"); //.toggle(!this.isNewOrDeleted());
            }
            else {
                this.form.ItemList.element.closest(".category").removeClass("hideGrid");
            }
```
And here is the css class where i set position of the category out from the dialog :-) :-)
```
.hideGrid {
    position:absolute;
    top:-200000px;
    width:100%;
}
``` 

I am sure this is not the correct way and there should be another standard way to do it. 
Please suggest the correct way for this issue..

**Comment by volkanceylan** [comment]
Try using .css('visibility', 'hidden'). I guess grid has data but it can't show rows as slickgrid requires resizeCanvas call when it becomes visible to calculate available space. It probably still thinks it has 0 pixel height when you toggle it.

Another option is to this.form.ItemList.element.closest(".category").toggle(!this.isNewOrDeleted()).trigger('layout') so SlickGrid can resize its canvas

**Comment by volkanceylan** [comment]
Uhm no 
this.form.ItemList.element.closest(".category").toggle(!this.isNewOrDeleted());
this.form.ItemList.element.trigger('layout');

**Comment by ramveersgh** [comment]
Thanks @volkanceylan 
Following is working perfectly -
this.form.ItemList.element.closest(".category").toggle(!this.isNewOrDeleted());
this.form.ItemList.element.trigger('layout');

Although .css('visibility', 'hidden') is also working. I already tried it instead of toggle but at that time this was not working, Probably i might doing something wrong or may be caching issue.

**Comment by thisXYH** [comment]
@ramveersgh  

It's too awesome , How to achieve the Print button

**Comment by ramveersgh** [comment]
@thisXYH 
Do you want to add a new button on dialog or print functionality?

**Comment by thisXYH** [comment]
want to add a new print button on dialog .  in Seren Template , I only know a Sample 
![bvne7fez nc qe9s n1clr](https://cloud.githubusercontent.com/assets/16305024/18222808/650ae8d2-71d5-11e6-81a3-4ec0a94ff0dd.png)
Not seen implemented in the dialog，

**Comment by ramveersgh** [comment]
Here is the sample to generate the invoice of order. 
You can treat Invoice button as Print?? :-) You will be required wkhtmltopdf.exe in App_Data\Reporting.
![invoiceprint](https://cloud.githubusercontent.com/assets/2145218/18222845/c96a949e-71c1-11e6-8146-1edf113f0b62.png)

**Comment by thisXYH** [comment]
0 - 0 
wkhtmltopdf.exe  ,  my computer no this app   hmmm. 
I thought you were just shot me give you ended up function buttons

**Comment by thisXYH** [comment]
I use the Google Translation to talk with you , 
Sometimes difficult to understand the semantics ，
