### ISSUE TITLE
Foreing fields in mytableRepository

### ISSUE THREAD

**Issue by CAlva123** [volkanceylan/Serenity#1123]
Hello.

I have a Reservations table that basically "confirms" a registry by editing one of its fields from false to true.
This table contains a foreing key from my Users table (UserID), so I can access User's fields like UserName and UserEmail in my Reservations grid and form.

When a registry is confirmed, an email needs to be sent to the user that applied for the reserve.
I already implemented that logic in mysavehandler in myReservationsRepository, but I can't access all the foreing fields I need from there.

Fields like myRow.UserId are ok, but fields like myRow.UserName or myRow.UserEmail always bring null values.

Is there a way I can get these values in mytableRepository so I can use them?

Thanks in advance for your help.

**Comment by volkanceylan** [comment]
Override PrepareQuery and select them

**Comment by CAlva123** [comment]
Something like this?

 protected override SqlQuery PrepareQuery()
            {

                var query = new SqlQuery();
                query.Select(fld.Username);
                query.Select(fld.UserEmail);
                return base.PrepareQuery();
            }

**Comment by volkanceylan** [comment]
base.PrepareQuery(query);
query.Select(fld.SomeField);

**Comment by CAlva123** [comment]
It says "No overload for method "PrepareQuery" takes 1 argument.

 I was trying something like:

 base.PrepareQuery();
 var query = new SqlQuery().From(Row)
 .Select(fld.SomeField);
return query;

And it works, but I have to select all the table fields as well.

The problem with that query is that it brings this error when one registry is edited:  Query affected 0 rows while 1 expected!

I suspect the reason is the Old.Fields, since they bring null values with the new query.

I tried to change this line:   var query = new SqlQuery().From(Old)

And it brings the old values but from another registry, so I guess I just need to add a condition, something like  .WhereEqual(fld.IdField, Old.IdField).


Please, let me know if I am wrong or if I need to do something else.

Thanks in Advance for your answer.

**Comment by volkanceylan** [comment]
sorry, base.PrepareQuery().Select(fld.SomeField)

SaveHandler has a different PrepareQuery

**Comment by javaman63** [comment]
Someone can put an example of how to get foreign fields before performing an update. ?

Thanx
