### ISSUE TITLE
forgot password

### ISSUE THREAD

**Issue by sbkleber** [volkanceylan/Serenity#1124]
I have one item that I can't seem to figure out.

Changed "EnableSsl" to true, as follows, in class ForgotPassword.cs, and thus get the message:  "SSL must not be enabled for pickup-directory delivery methods."
...

                MailAddress from = new MailAddress("myemail@host.com.br", "Não Responder");
                message.From = from;

                var client = new SmtpClient();

                if (client.DeliveryMethod == SmtpDeliveryMethod.SpecifiedPickupDirectory &&
                    string.IsNullOrEmpty(client.PickupDirectoryLocation))
                {
                    var pickupPath = Server.MapPath("~/App_Data");
                    pickupPath = Path.Combine(pickupPath, "Mail");
                    Directory.CreateDirectory(pickupPath);
                    client.PickupDirectoryLocation = pickupPath;
                }
                //Configurando host para enveio.
                NetworkCredential nc = new NetworkCredential("myemail@host.com.br", "mypassword");
                client.Credentials = nc;
                **client.EnableSsl = true;**
                **client.Host = "outlook.office365.com";**
                **client.Port = 587;**
                client.Send(message);
...

Sorry if this seems like a basic question, this is all still very new to me.

But, there's another way to do this?

Thank you.

**Comment by volkanceylan** [comment]
Why do you have SpecifiedPickupDirectory in web.config if you'll send e-mail actually. It's for testing only.

**Comment by sbkleber** [comment]
Thank you volkanceylan, you did a fine piece of work. Now everything went right. Very good.
Unfortunately my experience level with C#, ASP.NET MVC, CSS and JScript is practically basics. 

Thank you.

**Comment by volkanceylan** [comment]
You're welcome.
