### ISSUE TITLE
How to add date field in inline editing?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#1127]
Hi

I want to add date field in inline editing.  I am able to add the field but this field is shown as normal text box. 
How to show the calnder-icon so that user can click on this icon and select the date?
Here is my DateInputFormatter
```
private string DateInputFormatter(SlickFormatterContext ctx)
        {
            var klass = "edit s-DateEditor align-left";
            var item = (OilFillingDataRow)ctx.Item;
            var pending = pendingChanges[item.Id.Value];
            if (pending != null && Script.IsValue(pending.As<dynamic>()[ctx.Column.Field]))
                klass += " dirty";

            string value = GetEffectiveValue(item, ctx.Column.Field) as string;
            if (item.Status.HasValue && item.Status != ReconciliationStatus.Pending)
                return value;
            return
                "<input id='ReconDate_" + (++indid) + "' type='text' style='width:85px'" +
                    " class='" + klass + "'" +
                    " value='" + Q.HtmlEncode(value) + "'" +
                    " maxlength='" + ctx.Column.SourceItem.MaxLength + "'" +
                "/>";
        }
```

I need to execute js to add the Icon and convert normal textbox to calender control but where to execute the script?
if i execute following script in browser console then all field are converted to datecontrol
```
 $('input[id^=ReconDate_]').each(function () {
            $("#" + this.id).datepicker();
        });
```
But i don't know how and where to execute this script... Please help.
_Just for the information that i am using saltarelle for client side scripting instead of type script._

**Comment by ramveersgh** [comment]
Hi @volkanceylan 
Can you please help to achieve the date field in inline editing?

Thanks
Ram

**Comment by volkanceylan** [comment]
// PLEASE NOTE! Inline editing in grids is not something Serenity supports nor recommends.
        // SlickGrid has some set of limitations, UI is very hard to use on some devices like mobile, 
        // custom widgets and validations are not possible, and as a bonus the code can become a mess.
        // 
        // This was just a sample how-to after much requests, and is not supported. 
        // This is all we can offer, please don't ask us to Guide you...

**Comment by Zahar661** [comment]
@ramveersgh  Hi! happened?

**Comment by arfeenmalik** [comment]
i tried the following formatter and it is working

private dateInputFormatter(ctx) {
            var klass = 'edit s-DateEditor';
            var item = ctx.item as AgentsRow;
            var pending = this.pendingChanges[item.AgentCode];
            var column = ctx.column as Slick.Column;

            if (pending && pending[column.field] !== undefined) {
                klass += ' dirty';
            }
			
            var value;
            if (item[column.field] == null)
                value = item[column.field];
            else
                value = Q.parseDate(item[column.field]).toLocaleDateString();  
            
            return "<input type='text' class='" + klass +
                "' data-field='" + column.field +
                "' value='" + value +//+ todayDate +
                "' maxlength='" + column.sourceItem.maxLength + "' />" +
                "<script>$('.s-DateEditor').datepicker();</script>";  
        }
