### ISSUE TITLE
Add validation to Multiplefileuploader

### ISSUE THREAD

**Issue by zeezment** [volkanceylan/Serenity#1128]
Hi,

I'm having an issue with getting the required field toast message to appear in my form for a field of type MultipleFileUploader. I need it to display a required message if a user tries saving it as null. I added both NotNull and Required attributes and it still doesn't inherit the toast message that is inherited by other fields and tries to update the db with the null value, the field looks like:
[DisplayName("Attachments"), MultipleFileUploadEditor(FilenameFormat ="Claims/Attatchments/~"), NotNull, Required(true)]   
public String Attachments
        {
            get { return Fields.Attachments[this]; }
            set { Fields.Attachments[this] = value; }
        }

Thanks,
Aziza

**Comment by volkanceylan** [comment]
Add a custom validation rule and check for empty string or []
