### ISSUE TITLE
Master/Detail grid and dialog help 

### ISSUE THREAD

**Issue by cslore** [volkanceylan/Serenity#1129]
I have a master form(F) with 3 detail grids(1,2,3) on it. Is it possible to reload the data on grid F3 when a delete confirmation is confirmed on a dialog from F1 or F2, or to load the data deleted from either dialog into grid F3. Can someone point me in the right direction. 

Also I would also like to be able to drag and drop between the grids if possible. 

I am using the latest version of Serenity.

**Comment by she-ll-b-rite** [comment]
howdy, I'm a first time responder so be gentle :)
If I understand correctly, you want the master Dialog to be notified when an Entity has been deleted from F1Editor or F2Editor, so you can refresh grid in F3Editor. 

Way I handled this, was to add an onChange event to the F1Editor, fire the property from deleteEntity method and listen for the event in the master Dialog.

So in the F1Editor:

```
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace MyProj {
    
    @Serenity.Decorators.registerClass()
    export class F1Editor extends Common.GridEditorBase<F1Row> {
        protected getColumnsKey() { return 'MyProj'; }
        protected getDialogType() { return F1EditorDialog; }
        protected getLocalTextPrefix() { return F1Row.localTextPrefix; }

        // define the onChange property.
        public onChange: () => void;

        protected deleteEntity(id: number): boolean {
            let r = super.deleteEntity(id);
            // call the method for the onChange property.
            if (r) this.onChange();
            return r;
        }`
```

Then back in the master Dialog constructor you subscribe to the onChange property.

```
    @Serenity.Decorators.responsive()
    @Serenity.Decorators.maximizable()
    @Serenity.Decorators.flexify()
    export class MasterDialog extends Serenity.EntityDialog<MasterRow, any> {
            
            // called when entity is delete from F1Editor
            this.form.F1List.onChange = () => {
                // refresh the F3 grid.
                this.form.F3List.refresh();
            };
```
...repeat for F2Editor.

Can't help with drag and drop sorry.

HTH.

**Comment by cslore** [comment]
Thanks,
 I'll give it a try.

**Comment by she-ll-b-rite** [comment]
You can always add the Id for the entity that was deleted from F1, as a parameter to the onChange property so the master can pass onto F3.

```
        // define the onChange property.
        public onChange: (id: number) => void;

        protected deleteEntity(id: number): boolean {
            let r = super.deleteEntity(id);
            // call the method for the onChange property.
            if (r) this.onChange(id);
            return r;
        }
```
