### ISSUE TITLE
CONCAT can't  be used in sqlserver

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#113]
In OrderRow.cs ,EmployeeFullName is decorated with [Expression("CONCAT(e.[FirstName], CONCAT(' ', e.[LastName]))")],this is used in mysql ,we can use '+' instead in Sqlserver .

**Comment by volkanceylan** [comment]
CONCAT works in any. I can't use '+' as Serenity has to work with other databases, not just SQLServer. You can change yourself though.

**Comment by ChenZhaobin** [comment]
I got t,thanks.
I  use old version Sqlserver2008,'Concat' is used in sqlserver 2012+;  ‘offset’ is the same

**Comment by volkanceylan** [comment]
Hmm didn't know about 2005. Here it says it supported in 2008 

https://msdn.microsoft.com/en-us/library/hh231515.aspx
