### ISSUE TITLE
How to access Enum in JavaScript?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#1131]
Hi

Is there any way to access Enums in javascript?
We can access Lookups by following js
```
Q.getLookup('<lookupkey>')
```

Is there any similar way to access the Enum?

**Comment by VictorTomaili** [comment]
ServerTypings.tt already generate enums for clientside. Put `[EnumKey("Northwind.OrderShippingState")]` attribute on your enum and access it like `YourApp.Northwind.OrderShippingState.Shipped`

**Comment by ramveersgh** [comment]
Thanks @VictorTomaili 
I want to use items of enum inside javascript in normal html page. I check executing javascript for my enum Tranzol.Modules.Common.Enums.LedgerGroups which return a blank function. Here is output in browser console window - 
![enumissue](https://cloud.githubusercontent.com/assets/2145218/18127438/0791bb06-6f9e-11e6-8715-0476cefe9d7b.png)

**Comment by VictorTomaili** [comment]
I have no problem when access it from console 
![image](https://cloud.githubusercontent.com/assets/2023440/18127675/8fc3d68a-6f8a-11e6-973a-d1ee43169062.png)

**Comment by ramveersgh** [comment]
Hmmmm...
I will check then what is issue with my enum.
I am still using saltarlle for script project. That may also be a reason. I will have a look on it.
Thanks for sharing the info.

**Comment by VictorTomaili** [comment]
I remember `ScriptInclude` attributes for saltarelle.

**Comment by ramveersgh** [comment]
I already tried taht.. but no luck..

**Comment by volkanceylan** [comment]
Enum must be under same root namespace. Serenity.EnumRegistry.get might also help.
