### ISSUE TITLE
T0.[Date] is not a valid field name!

### ISSUE THREAD

**Issue by blojayble** [volkanceylan/Serenity#1133]
Hello,
while trying to use repositories in my code I got this weird error:
"T0.[Date] is not a valid field name!"

Snippet:
```c#
    var dateField = new Criteria("Date");
    var dateField2 = DayOfScheduleRow.Fields.Date;
    var lr = new ListRequest { Criteria = dateField > DateTime.Now };
    var lr2 = new ListRequest { Criteria = dateField2 > DateTime.Now };
    var repo = new DayOfScheduleRepository();
    using (var connection = SqlConnections.NewByKey("WorkSchedule"))
    {
        repo.List(connection, lr);
        repo.List(connection, lr2);
    }
```

First list request works fine, but when trying to use the field object execution fails.
Have I done something wrong?

**Comment by volkanceylan** [comment]
Criteria in list request doesnt allow arbitrary Sql for security reasons.  So you can only write new Criteria("Date") where date is a property name in your row, not expression

**Comment by blojayble** [comment]
I don't know exactly how these work internally in Serenity, so I want to get one thing straight: I will not get any ambiguity errors if I have field "Date" in some of my other tables as well?

**Comment by volkanceylan** [comment]
Its property name not field name. You cant have double property with same name so no.
