### ISSUE TITLE
Extending a lookup editor

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#1135]
Hi everyone;

Has anyone figured out how to extend a lookup editor so as to expose fields other than IdField and TextField? Is it possible to select a record from a searchable grid (that's filtered by, say Age and Gender)and get its Id back to the lookup field? 

![untitled](https://cloud.githubusercontent.com/assets/13295503/18134425/404ec0cc-6f96-11e6-9486-5a8951e2716c.png)

**Comment by linpiero** [comment]
You can use the attribute LookupInclude on field of the row LookUp.

**Comment by awesomegithubusername** [comment]
Thanks buddy. I don't know why I keep forgetting about this "LookupInclude" thing!

**Comment by linpiero** [comment]
😁😁😁😁
