### ISSUE TITLE
How to use QuickFilter with EmployeeListFormatter

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#1136]
Hey guys! Children with sickness are horrible! So let's back to work!

I would like to know how to use QuickFilter with EmployeeListFormatter in Costumer Grid.

I tried to insert QuickFilter attribute, but the page cames with error.

In my personal project (with other tables), I got another error, something like "Invalid Column Name '

**Comment by volkanceylan** [comment]
Hope they get well soon. QuickFilter and Formatter has no relation, what are you trying to do.

**Comment by rolembergfilho** [comment]
Filtering Costumer by their representatives.

e.g. in http://serenedemo.azurewebsites.net/Northwind/Customer, we have the Costumer ID C0004 (Acme Widget Almagamated) with some representatives, like Janet Leverling, Laura Callahan, Robert King, etc....

I would like to filter all costumer that have Janet Leverling, or all customer with Laura Callahan and Robert King


In my project, I have a lot of services codes for each Health Insurance. These code are grouped by their Medical Specialities, like  physiotherapy, psychology, occupational therapy, and more...

sometime, I can group the same code with physiotherapy and GPR tags.

So, when i schedulle my patience, I need to filter what code are available for their purpose, according to  Health Isurance.

**Comment by volkanceylan** [comment]
See guide for genre filtering in movies tutorial

**Comment by rolembergfilho** [comment]
Worked nice!

Thank you very much!
