### ISSUE TITLE
 cascading LookUp Editor programmatically in a Form

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1137]
I am trying to programmatically cascading lookup editor in a form.
In my xyzDialog.ts , i have tried with this
this.form.SiteId.cascadeField = GTMS.Master.TourStationsRow.Fields.CustomerId;
and 
this.form.SiteId.cascadeField = "CustomerId";
still it is not cascading.
I also searched all Open issues and closed issues, but couldn't find the answer.
kindly help me.
regards
Shailesh

**Comment by awesomegithubusername** [comment]
The "[Filtered Lookup in Detail Dialog"] (https://github.com/volkanceylan/Serene/tree/353617e4637ddb9415aaf345aaf34ddfb8c8c4cd/Serene/Serene.Web/Modules/BasicSamples/Editors/FilteredLookupInDetailDialog) sample might help you.

**Comment by fzhenmei** [comment]
[How To: Setup Cascaded Editors](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html)

Hope this can help you.

**Comment by shaileshbc** [comment]
using "Filtered Lookup in Detail Dialog" only i tried with 
this.form.SiteId.cascadeField = GTMS.Master.TourStationsRow.Fields.CustomerId;
but it didn't work.
"How To: Setup Cascaded Editors" shows how to cascade lookup editors, but i want it
to be cascade pro-grammatically and not though attribute.
Thanks for your help.
i am still searching for solution.
In case of grid it is possible to cascade pro-grammatically, but the same is not
available in case of a Form.
regards
Shailesh

**Comment by volkanceylan** [comment]
If you don't set CascadeFrom, it won't cascade.

**Comment by shaileshbc** [comment]
since the field is of LookUpEditor type, it is not showing cascadefrom property.
only cascadefield and cascadevalue is available.
![cascade](https://cloud.githubusercontent.com/assets/19570368/18268432/5665cb6c-7441-11e6-9951-6ececaf37a2c.png)
In that case how to set cascadefrom property?
regards
Shailesh

**Comment by volkanceylan** [comment]
try (this.form.SiteId as any).cascadeFrom

**Comment by shaileshbc** [comment]
It worked 
Thanks a Lot
regards
Shailesh
