### ISSUE TITLE
How to service?

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#1138]
Calling a separate service,For example, a call to the reception site data

**Comment by samdubey** [comment]
can you please elaborate about your question?
did you mean to call existing service endpoint generated by Serenity?
do you want to skip Authentication?
write new service / webapi?

**Comment by 107295472** [comment]
Do not skip validation, how to call, request

**Comment by volkanceylan** [comment]
Read guide. If it is an external service, read their guide / .NET service references.

**Comment by 107295472** [comment]
Not to search?
