### ISSUE TITLE
Id field int64 problem with big values

### ISSUE THREAD

**Issue by Drunik01** [volkanceylan/Serenity#1139]
Hi!
I have a sql-view with id of int64 and having big values like 72057594098253390, 72057594098253391 and so on. In server-side all work fine and json packet formed correctly, but when this packet converted to array on client side id values rounded and I have a error because Id is not unique. The only way is to use a string type. 
You can do something to help?

**Comment by volkanceylan** [comment]
JsonSafeInt64Converter does convert Int64 values bigger than a certain value to string while serializing to JSON. In javascript number type is double so there is no Int64 type, and JSON does only support numbers of double type. I don't know what kind of JSON serializer you are using.

**Comment by volkanceylan** [comment]
Closing as no updates.
