### ISSUE TITLE
How to add Tenant Name in Shipper List Page

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#114]
Maybe this is not a question with serenity,I just want to know what's the best idea to show tenantName
in shipper list page When table shipper and table Tenant are in different database?

**Comment by ChenZhaobin** [comment]
And how to handle it  when the data comes from rest Api?

**Comment by volkanceylan** [comment]
You can use inter-database joins like ForeignKey("[Serene_Default_v1].[dbo].[Tenants].", "TenantId")

**Comment by ChenZhaobin** [comment]
thanks
