### ISSUE TITLE
FileUploadEditor used filename

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#1141]
How to use the original file name instead of the new generation when i upload the file?

**Comment by volkanceylan** [comment]
Set OriginalNameProperty

**Comment by cp1319421** [comment]
I set the OriginalNameProperty, but it's fail when save, and show can't find “D:\TMS\TMS\TMS.Web\App_Data\upload\UTDatabase.db3”, what's wrong about this?

**Comment by volkanceylan** [comment]
Saving with uploaded file name is not supported and not secure. Write your own behavior if needed.
