### ISSUE TITLE
Multiple Selection help needed

### ISSUE THREAD

**Issue by ckelsoe** [volkanceylan/Serenity#1142]
I am struggling with this error (partial snippet) which is coming from ServerTypings.tt when I try to transform the t4 templates:
`
Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'PSCRM.PSCRMDB.Entities.CustomerRow' threw an exception. ---> System.ArgumentException: 'PSCRM.PSCRMDB.Entities.CustomerRow' type doesn't have a [LookupScript] attribute, so it can't be used with a LookupEditor!
` 

I thought I had everything set up properly. I have a customer table with a primary key of CustomerID and a systemtype table with a primary key of SystemTypeID. The CustomerSystems table that joins these two tables has a primary key of CustomerSystemID and also includes CustomerID and SystemTypeID columns. 

![image](https://cloud.githubusercontent.com/assets/21282091/18238005/40ed2fc8-7306-11e6-89c8-3cb6775c61dc.png)

In CustomerRow.cs I have the following:

```
...
        [DisplayName("Systems")]

        [LookupEditor(typeof(SystemTypeRow), Multiple = true), ClientSide]

        [LinkingSetRelation(typeof(CustomerSystemsRow), "CustomerID", "SystemTypeId")]
        public List<Int32> SystemTypeList
        {
            get { return Fields.SystemTypeList[this]; }
            set { Fields.SystemTypeList[this] = value; }
        }

...

public ListField<Int32> SystemTypeList;

...
```

I think I have the order of the CustomerRow.cs code correct based on translating from the Movies sample code. However, I am missing something that after several hours I am unable to get around. 

Any guidance would be appreciated. 

Thanks, Charles

**Comment by volkanceylan** [comment]
It says "CustomerRow' type doesn't have a [LookupScript] attribute" so it should have a [LookupScript] attribute on top on your CustomerRow, not LookupEditor attribute in one of its properties.

**Comment by ckelsoe** [comment]
Thanks. I started over and got it right finally.
