### ISSUE TITLE
PDF generator returned error code 255!

### ISSUE THREAD

**Issue by she-ll-b-rite** [volkanceylan/Serenity#1143]
Hi all, I'm using the ReportHelper to create a PDF rendered to the browser, which is working perfectly in dev (Windows 10), but I'm getting the following error in prod environment (Windows Server 2012 R2)

> Server Error in '/' Application.
> 
> PDF generator returned error code 255!
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.InvalidOperationException: PDF generator returned error code 255!
> 
> Source Error: 
> 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
> 
> Stack Trace: 
> 
> 
> [InvalidOperationException: PDF generator returned error code 255!]
>    Serenity.Reporting.HtmlToPdfConverter.Execute() in P:\Sandbox\Serene\Serenity\Serenity.Web\Reporting\Tools\HtmlToPdfConverter.cs:164
>    PWB.ReportController.Execute(String key, String opt, String ext, Boolean download, Boolean printing) 

Things I've checked:

- wkhtmltopdf.exe is in folder '~\App_Data\Reporting'
- App Pool account has read, write and execute permission on this folder
- App Pool account has read & write permission on '%USERPROFILE%\AppData\Local\Temp'

Any suggestions for what to check next?

**Comment by volkanceylan** [comment]
Check 32 bit/64 bit. Check exe file is not blocked in properties, unblock it.

**Comment by she-ll-b-rite** [comment]
Solved! wkhtmltopdf.exe also has dependency on "Visual C++ Redistributable Packages for Visual Studio **2013**" which weren't installed on the server.
-thx
