### ISSUE TITLE
How to create a dialog showing a list

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1144]
Nice to see you!
Now I got in trouble again , when I  click a button, how to show me a dialog about a table data?
Like this,
![image](https://cloud.githubusercontent.com/assets/20295114/18243795/729705b0-738f-11e6-8ee7-8aa140d733c6.png)

when I click the "Order Detail" addbutton , then open a dialog, such as the follow picture.
![image](https://cloud.githubusercontent.com/assets/20295114/18243780/58991dce-738f-11e6-8a5e-2a4f791cb476.png)
Can it be realized ?

**Comment by volkanceylan** [comment]
Yes it can be realized if you look code of how UserPermission dialog gets opened
