### ISSUE TITLE
rowSelection.getSelectedKeys() on Master/Detail

### ISSUE THREAD

**Issue by Pinellus** [volkanceylan/Serenity#1145]
Hi all,
I would like to submit this issue:

I have a form Master/Detail.

![cattura](https://cloud.githubusercontent.com/assets/3186321/18248378/fc0ad104-7377-11e6-9540-c1f7e6e97b30.PNG)

The Details list (in the XyzDetailsEditor.ts) has the code for the checkbox.

`protected getColumns() {
       var columns = super.getColumns();
       columns.splice(0, 0, Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));
       return columns;
}`

In the XyzDetailsEditor.ts I added the following code:

`protected getIdProperty() { return XyzDetailRow.idProperty; }`

When I add new Detail, on save I get the following error:

`Uncaught Each data element must implement a unique 'IdXyzDetail' property. Object at index '2' has no identity value`

With the JS debugger, I discovered that items [i] of the new item has not set the property "idProperty".

`function updateIdxById(startingIndex) {
                startingIndex = startingIndex || 0;
                var id;
                for (var i = startingIndex, l = items.length; i < l; i++) {
                    id = items[i][idProperty];
                    if (id === undefined) {
                        var msg = "Each data element must implement a unique '" +
                            idProperty + "' property. Object at index '" + i + "' " +
                            "has no identity value: ";
                        msg += $.toJSON(items[i]);
                        throw msg;
                    }
                    idxById[id] = i;
                }
            }`

If I delete the code `protected getIdProperty() { return XyzDetailRow.idProperty; }` everything works fine but when I select the checkbox, these do not return me the ID of the Item but a random numbers.

What am I doing wrong?
Can you help me?
Thanks!

**Comment by volkanceylan** [comment]
Detail editor ID property has to be __id. It's a virtual ID as newly added records don't have an ID yet.

**Comment by Pinellus** [comment]
Hi Volkan,
thank you for your answer.
So, if I understand correctly, the [IdProperty] in edit dialog, overwrite the "__id" and causing unexpected behavior.
But, if I delete [IdProperty], the checkbox on DetailGrid, do not return me the row ID.
How can I get this ID?

![image](https://cloud.githubusercontent.com/assets/3186321/18251183/ea65cd22-7387-11e6-81be-91e9a2720c3b.png)

Thanks!

**Comment by volkanceylan** [comment]
Those keys are virtual ID's but strings for grid. So use Q.toId to convert them to int first, then use this.view.getItemById(x) to get access to actual row and read their actual ID values.

e.g.

keys.map(x => this.view.getItemById(Q.toId(x)))

**Comment by Pinellus** [comment]
Great Volkan,
perfect.

This work form me:

`var selectedIDs = this.rowSelection.getSelectedKeys();`
`var h = selectedIDs.map(x => this.view.getItemById(Q.toId(x)));`
`var selIDs = []; var selCnt = 0;`
`for (var i = 0; i < h.length; i++) {`
   `if (typeof h[i] != 'undefined') {` 
        `selIDs[selCnt] = h[i].IdConsumiDetail;`
        `selCnt++;`
    `}`           
`}`

Thank's!!

**Comment by volkanceylan** [comment]
One liner ;)

```
var selIDs = selectedIDs.map(x => this.view.getItemById(Q.toId(x)).IdConsumiDetail).filter(x => x != null)
```

**Comment by Pinellus** [comment]
*The Elegance* :-)
