### ISSUE TITLE
Namespace collision using bootstrap-slider with jquery-ui

### ISSUE THREAD

**Issue by DGoertzen** [volkanceylan/Serenity#1146]
The bootstrap sliders on page sliders.cshtml do not display properly because of a namespace collision when using bootstrap-slider with jquery-ui.  The issue is described at http://stackoverflow.com/questions/26691018/using-bootstrap-slider-with-jquery-ui .  The problem can be fixed by changing the line in sliders.cshtml from $('.slider').slider(); to $('.slider').bootstrapSlider();

But I just want to say, what an amazing template Serene is.  So very helpful!

**Comment by volkanceylan** [comment]
Thanks @DGoertzen, i'll apply that fix.

**Comment by DGoertzen** [comment]
Hi Volkan

As a note, the bootstrap-slider included with Serenity is not the latest
version.  I downloaded the latest one from here:
https://github.com/seiyria/bootstrap-slider, and it seemed to work fine
with the rest of the code, so you may want to consider updating.  I realize
this is a very minor thing of course, but just happened to notice it as I
was developing, so thought I'd let you know.

Regards,
Doug

**Comment by volkanceylan** [comment]
Thanks, updated in latest version.
