### ISSUE TITLE
How to click on the button to open the list interface?

### ISSUE THREAD

**Issue by caitingting** [volkanceylan/Serenity#1148]
Hi there.
When we click the button to display the Dialog interface, but I want to pop up a similar Grid interface to how to achieve?

**Comment by Estrusco** [comment]
You can try making a XYZDialog.template.html with

```html
<div id="~_Tabs" class="s-DialogContent">
    <div id="~_Toolbar" class="s-DialogToolbar">
    </div>
    <div id="~_TabXYZ" class="tab-pane s-TabXYZ">
        <div id="~_XYZYourGrid">
        </div>
    </div>
</div>
```

**Comment by volkanceylan** [comment]
Closing as no update for a week

**Comment by mantiklas** [comment]
Can i open this one?   because my question is similar with this one.
I like to open another grid from different grid by adding buttons in getButtons() named "View other Grid".
How to delegate the viewing of another page?   
 buttons.push({
                title: 'View Other Page',
                
                onClick: () => {
                   //What to add here? thanks
                    
                }
            });

**Comment by caitingting** [comment]
Do you want to click on a cell in the Grid interface to open the other dialog interface?
If so, you can refer to the following method !
IN Grid：
protected getColumns() {
            var columns = super.getColumns();
            var fld = Article.ArticleCommentRow.Fields;   //Current Fields
            Q.first(columns, x => x.field == fld.ArticleTitle).format =
                ctx => `<a href="javascript:;" class="articleId-link">${Q.htmlEncode(ctx.value)}</a>`;

            return columns;
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number): void {

            super.onClick(e, row, cell);

            if (e.isDefaultPrevented()) {
                return;
            }

            var item = this.itemAt(row);

            var target = $(e.target);

            if (target.hasClass("articleId-link")) {
                e.preventDefault();
                if (item.ArticleId != null)  // ArticleId： The field you want to implement 
                    new Article.AppArticleDialog().loadByIdAndOpenDialog(item.ArticleId);       //Article.AppArticleDialog ：You want to open the dialog 
            }
        }
