### ISSUE TITLE
Approve And Reject 

### ISSUE THREAD

**Issue by adeelhassan** [volkanceylan/Serenity#1149]
How can i add the option for admin to approve the order or pending the order

**Comment by volkanceylan** [comment]
There are many button samples, try one

**Comment by adeelhassan** [comment]
Sir i Can,t understand  about the backEnd functionality

**Comment by adeelhassan** [comment]
sir if u can help me the i will be thankful to you

**Comment by adeelhassan** [comment]
Sir i can,t understand the back-end functionality. Guid me when i add the
button how can i save the bollean value in the database.

**Comment by Estrusco** [comment]
Use serviceRequest for your Insert/Update 

```ts
    Q.serviceRequest('XYZ/Update', {
        EntityId: key,
        Entity: entity
     }, 
     (response) => {
     });
```
