### ISSUE TITLE
How to change login page style

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#115]
I want to use a login template downloaded from web ,can you help me?I can't find  @Viewbag.UserName and  @Viewbag.Password.And I can't control the width and height of the form.

**Comment by volkanceylan** [comment]
You gotta use only css part of that template. The variables you refer to is probably something related to basic MVC form model, which you can't use as is with Serenity forms. But you can replace login page completely with that template and its controller. You just need to call Account/Login service on button click.

**Comment by ChenZhaobin** [comment]
I make it ,just change  the value of MVC.Views.Membership.Account.AccountLogin  to  a page of myself,thanks
