### ISSUE TITLE
Removing Delete button in Dialog after loading it from the Grid.

### ISSUE THREAD

**Issue by mantiklas** [volkanceylan/Serenity#1150]
Under "Customs Links in Grid" of Serene I am trying to replicate the code, but after loadByIdAndOpenDialog(Customer), how to hide the Delete button in Dialog of Customer.  Please help e.. Than you in anticipation

**Comment by ckelsoe** [comment]
I also need this.

**Comment by VictorTomaili** [comment]
Any of dialog you can remove it from constructor.  

![image](https://cloud.githubusercontent.com/assets/2023440/18301512/b9a7fbc0-74da-11e6-89aa-32170631482b.png)

**Comment by mantiklas** [comment]
Thanks @VictorTomaili, I appreciate it,   but my question is: loading dialog from parent Grid, using loadByIdAndOpenDialog(), how could I remove the delete button on the dialog.. coming from a parent grid... I want to hide the delete button. so that the user could not delete the mapped row.. Regards and thanks

**Comment by VictorTomaili** [comment]
![image](https://cloud.githubusercontent.com/assets/2023440/18304216/ce05794e-74e9-11e6-9ba3-20e50b95ca69.png)

**Comment by mantiklas** [comment]
@VictorTomaili  check this link.. http://serenedemo.azurewebsites.net/BasicSamples/CustomLinksInGrid
![step1](https://cloud.githubusercontent.com/assets/21164515/18306317/d4f12ad0-751d-11e6-8580-474a6cff9146.PNG)
![step2](https://cloud.githubusercontent.com/assets/21164515/18306319/d86a5696-751d-11e6-8576-91e8804d7bb7.PNG)

How to remove the Delete button in the customer dialog.. Thank you in antcipation

**Comment by volkanceylan** [comment]
See readonly dialog samples.

**Comment by mantiklas** [comment]
Tnx @volkanceylan, it works , What I did, I created new Dialog that extends the foreign Dialog. But the drawback is, every foreignkey mapped on my row,   is another dialog.ts i need to create... which makes my dialog.ts voluminous.. Is there simplest way?  this is my code on my grid which I just based here 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/CustomLinksInGrid/CustomLinksInGrid.ts..

 protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();
            var fld = Areas.SiteRow.Fields;
            Q.first(columns, x => x.field == fld.ClusterName).format = 
                ctx => `<a href="javascript:;" class="cluster-link">${Q.htmlEncode(ctx.value)}</a>`;
}

 protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell)
            
            if (e.isDefaultPrevented()) {
                return;
            }

            var item = this.itemAt(row);
            var target = $(e.target);
            if (target.hasClass("cluster-link")) {
                var dlg = new ClusterSiteDialog();
            
                e.preventDefault();
                dlg.loadByIdAndOpenDialog(item.ClusterId); 
}

**Comment by john20xdoe** [comment]
@mantiklas 

So you mean in your grid - let's call it Site - you have (for example only) two columns. One column is an `EditLink `that opens the **SiteDialog** as normal grids do. The other column is a foreign key, let's call it Cluster. And it is also an `EditLink`, but it opens the **ClusterDialog** with the Delete button hidden. 
And you want the ClusterDialog Delete button to be hidden only when it is being called from SiteGrid, but has normal options (i.e.the Delete is shown as usual) when being called from its own grid (ClusterGrid).

1. ClusterGrid -> **ClusterDialog** with **Delete** shown as normal.
2. SiteGrid -> **SiteDialog**, **ClusterDialog** with **Delete** hidden


And you are asking how to do #2. Right?

**Comment by mantiklas** [comment]
Exactly @john20xdoe

**Comment by john20xdoe** [comment]
haha I also need this.

**Comment by john20xdoe** [comment]
Now the getDialogOptions() method (which has the `canDelete `config) in SiteGrid.ts will only affect SiteDialog, but we have no control over ClusterDialog options from within SiteGrid.

**Comment by mantiklas** [comment]
Yes , so what I did,, I  created new Dialog that extends ClusterDialog.. But it has cons,  if your Row, have  many foreignkey... It will make your file voluminous.. I am still looking for a way to hide the delete button of clusterdialog from siteGrid..

**Comment by volkanceylan** [comment]
This is a violation of seperation of concerns and encapsulation. Add a property to your dialog, e.g. AllowDelete, when set toggle delete button. Or subclass your dialog, hide deleteButton in updateInterface.
