### ISSUE TITLE
Set Criteria With Null Condition

### ISSUE THREAD

**Issue by ahsansolution** [volkanceylan/Serenity#1151]
Hi, Volcan

Please help,

How to set criteria with null condition

   request.Criteria = Serenity.Criteria.and(request.Criteria,
                    [['EntryDate'], '=', 'Null'],
                    [['Result'], '!=', 'TBC'],
                    [['ReceivedDate'], '<>', 'Null']);

I have create above criteria but get an error "Conversion failed when converting date and/or time from character string".

Regards

**Comment by VictorTomaili** [comment]
![image](https://cloud.githubusercontent.com/assets/2023440/18267724/2ba666c4-7429-11e6-9cec-970cc1903560.png)
![image](https://cloud.githubusercontent.com/assets/2023440/18267742/3d9214dc-7429-11e6-88ef-2e76cb807887.png)

**Comment by volkanceylan** [comment]
['is null', ['EntryDate']]

['is not null', ['ReceivedDate']]

**Comment by ahsansolution** [comment]
It's Perfect!

Thanks All...
