### ISSUE TITLE
LoggingRow: InsertDate or UpdateDate for particular TimeZone

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1152]
Is it possible to set value of LoggingRow: InsertDate or UpdateDate for particular TimeZone?
As Server may be in different country on which application is running.
Even after setting culture info in web.config, it is taking local server time only.

Similarly how to set value of DeleteDate for particular TimeZone, if entity is implementing
IIsActiveDeletedRow interface?
regards
shailesh

**Comment by volkanceylan** [comment]
Add DateTimeKind(DateTimeKind.Utc). For different time zone, you need to write your own log behavior, and disable default one.

**Comment by shaileshbc** [comment]
Ok, I will try.
Thanks for your Help.
regards
Shailesh
