### ISSUE TITLE
Unicode support in pdf export

### ISSUE THREAD

**Issue by far100** [volkanceylan/Serenity#1154]
First of all You have done a very great job in this framework.
and I hope you make a way to accept donations from people who appreciated your work.

The Issue:
when grid exported to pdf. it did not show unicode characters correctly.
to replicate the problem just select Farisi Language in the application and export the customers grid.

Thanks

**Comment by volkanceylan** [comment]
Please see / report in jspdf issues. We use it as is.

**Comment by far100** [comment]
Yes. it is jsPDF related. I just I thought you did something about that when you introduced RTL support in slickGrid. and passing localized column headers to PDF exporting functions . and I only missed something.

I have seen some source code of jspdf that looks like it can handle unicode. and maybe all it needs some special initialization.

will you please do some investigation when you can.
thanks again

**Comment by volkanceylan** [comment]
I don't do anything. Pdf fonts probably don't have characters you use.
