### ISSUE TITLE
Using Users table for a lookup source

### ISSUE THREAD

**Issue by ckelsoe** [volkanceylan/Serenity#1155]
Hi,

This question is not serenity specific but asp.net membership related. In my app I have several fields that look up employees. Some of those employees will be users of the application. Most probably will not. In that scenario could  I leverage the Users table to store that list of employees or should I just have a separate table that contains the user list I need to pull from? Note that there would be some additional columns needed (title, role, phone number, etc) above and beyond what is already defined in the Users table. Also since this ultimately will be an intranet app I would like to leverage Active Directory authentication.

Thanks

**Comment by volkanceylan** [comment]
I'd put a UserID column in Employee table. This way only employees that would have users would have a user record.
