### ISSUE TITLE
Variable undefined under getcolumn()

### ISSUE THREAD

**Issue by ahsansolution** [volkanceylan/Serenity#1156]
Hi Jaiq,

I have this code in in .ts, this.productType in getcolumn always return error 
"TypeError: this.productType is undefined", please kindly help. Thanks

       public productType: number = 0;

        constructor(container: JQuery) {
            super(container);
        }

        public set_productType(value: number): void {
            this.productType = value == null ? 0 : value;
        }

        protected getColumns(): Slick.Column[] {
            Q.alert(this.productType.toString());
            let fld = ProductPriceRow.Fields;
            if (this.productType == 2) {
                 return super.getColumns().filter(x => x.field !== fld.ProductPartNumber);
            }
            if (this.productType == 1) {
                return super.getColumns().filter(x => x.field !== fld.ProductModelName);
            }
        }

**Comment by VictorTomaili** [comment]
try `protected productType: number = 0;`

**Comment by ahsansolution** [comment]
It's not work, still undefined.

Thanks

**Comment by ahsansolution** [comment]
Any suggestion?

**Comment by VictorTomaili** [comment]
`this.productType = !value ? 0 : value;`  ??

**Comment by volkanceylan** [comment]
Your productType assignment runs after base constructor. Base constructor is calling getColumns so productType is undefined yet. 

This is a bad design, either use a options class, or make two different grids, both having same columnsKey.

**Comment by ahsansolution** [comment]
Thanks for suggestion Jaiq, i separate to two different grid with the same columnkey.
