### ISSUE TITLE
Help Layout

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1158]
Hello, any suggestion on how to do a page that displays a hierarchy and a botom área like this one:

![image](https://cloud.githubusercontent.com/assets/10889019/18320769/16c6b6aa-7523-11e6-8271-8572d33b151d.png)

Any sample or code would be nice.
Thanks.

**Comment by volkanceylan** [comment]
You need a hierarchical chart component for that, out of scope here.

**Comment by brunobola** [comment]
Thanks.
