### ISSUE TITLE
about  Prompt();

### ISSUE THREAD

**Issue by thisXYH** [volkanceylan/Serenity#1159]
in serenity framework , I did not find the sample about  the prompt () to expand, I want to achieve the click of a button pops up an input box, and then get the value entered. like this ，but it too Ugly。

**Comment by thisXYH** [comment]
![_20160908111645](https://cloud.githubusercontent.com/assets/16305024/18335931/c860ee0c-75b5-11e6-80fd-85355be2f985.png)
![111](https://cloud.githubusercontent.com/assets/16305024/18336042/9660cd86-75b6-11e6-8659-08b47903ef66.png)

**Comment by 107295472** [comment]
你这中文太六了，看到就不理你了

**Comment by 107295472** [comment]
我不会啊，还没看懂这个，如果有个前台网站该怎么调用这个服务器啊，是不是得用js调用啊

**Comment by volkanceylan** [comment]
You may write one using PropertyDialog and a simple form with one input.

**Comment by thisXYH** [comment]
@volkanceylan  can you give me more prompt ? something code segment.

**Comment by volkanceylan** [comment]
I dont have code segment. Wait for a sample.
