### ISSUE TITLE
How to upload excel and import it to database?

### ISSUE THREAD

**Issue by fzhenmei** [volkanceylan/Serenity#116]
Like click a button on grid toolbar, then pop-up a dialog, in the dialog select excel to upload, then import it to database.

**Comment by volkanceylan** [comment]
You can use EPPlus for this. It can load excel files. But i don't have a sample.

**Comment by fzhenmei** [comment]
thanks

**Comment by ChenZhaobin** [comment]
@fzhenmei   I have the same requirement,Could you share your solution here?
