### ISSUE TITLE
How to refresh the sidebar or whole page after setting Role permissions

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1160]
What method should I override (and whether in dialog or in grid?) to trigger a navigation sidebar refresh or a page refresh after I changed permissions (either in **Roles** or in **User > Edit Permissions**) so that the user can see immediately the new modules he can now access?

Currently this can be done by manual page refresh after clicking Save in the dialog.

**Comment by volkanceylan** [comment]
This is not a sensible thing. User will lose open dialog. And you usualky change permissions of other roles or users, not yours. Try window.location.refresh overriding onSaveSuccess of dialog.

**Comment by john20xdoe** [comment]
Ah yes, `onSaveSuccess`, thanks. Actually I plan to execute it only if a user is changing his own permission.
