### ISSUE TITLE
How can I get XYZGrid value  in XYZDialog?

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1161]
Hi ! As the title said, I want to get the XYZGrid value when I in a XYZDialog , the dialog and the grid are the same entity . Must I write a service ? Is there another way I can achieve it?

**Comment by volkanceylan** [comment]
Use this.entity or Retrieve method of your service. Dialog shouldnt access its grid. Pass it to dialog on creation, e.g. InitDialog method if required.
