### ISSUE TITLE
Grid column EditLink display based on role

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#1162]
Hello sir,

I want to display EditLink in grid column based on role. How to achieve it in saltralle version.

**Comment by volkanceylan** [comment]
Write a formatter, check permission, return a link if user has one.

**Comment by laxmanp** [comment]
Okay thanks, I'll try it.

**Comment by TechAspirant** [comment]
@laxmanp can you tell me how can I create formatter to achieve the same.
