### ISSUE TITLE
Menu Structure

### ISSUE THREAD

**Issue by LeonFNortje** [volkanceylan/Serenity#1163]
Good day Volkan,
We started down the same path about a year ago, I just went the ASP.Net Forms route with the same template, and I've built most of my system using different components. But, that said, I must be honest I like the MVC direction that this project took a lot more, and I'm contemplating moving my whole CRM across to use Serenity, but that said, I need some functionality that I've already built on my side. My question is then, what is your thinking around adding database support for the menu structures? What I've done is adding a menu structure in database, with a table that I can then populate from the front-end, and that will then update my sidebar. I understand why you did it the way you did, but how would be the best way for me to assist you in making this template better, do you want it in your template? or should I just leave it as a separate part on my side? I would really like to start contributing to this project as well, and as I move my project accross to MVC - from asp.net Forms, I would hope that I can help the community by adding (if possible) functionality to the system, where I have already done some development... 
This is a screenshot of how my system's menu editing screen looks like
![image](https://cloud.githubusercontent.com/assets/7837734/18347658/f57066d2-75c6-11e6-909b-1e7b0f98f724.png)

At the moment I see you support up to 10 levels of menus, which is very clever, but for my datagrid, I only supported 2 levels (which can be changed with little clever UI changes).

What would your recommendation be? Do I add it and make it available for you to review (to perhaps add it in) ? Or would you rather leave the menu in the Config file, and I add it on my side separately?

**Comment by volkanceylan** [comment]
Hi @LeonFNortje.

Dynamic menu can be useful in some cases like CRM/CMS etc, where end user wants to add custom menu items. Actually in some prior CMS i did, there was such a menu system. It has some clear benefits, but when you add / edit some menus as a programmer, it becomes harder to publish / merge / order your new items. Especially when you have multiple customers, it might become an headache. So i try to avoid giving end-user much customization options nowadays. I feel that, most of them request but don't actually use these features at all.

Like in this issue

https://github.com/volkanceylan/Serenity/issues/490

some users already implemented dynamic menus in Serenity. I also added dynamic items under a menu like Reports etc that comes from an external source in some projects.

Anyway, if you prepare some page to edit these items, like translation screen, i'd be happy to merge your pull request as long as it stays optional and doesn't block / mess ordering of default attribute based navigation system. Menus defined there should seamlessly merge with dynamic ones, using order values.

Thanks.

**Comment by volkanceylan** [comment]
About levels, i think you should use tree system to add menus, so you'll need only one page. SlickGrid supports that functionality. Let me know if you need help about implementing it.

**Comment by volkanceylan** [comment]
Closing this at the moment. Waiting for your pull request.

**Comment by Haribabu74** [comment]
> Good day Volkan,
> We started down the same path about a year ago, I just went the ASP.Net Forms route with the same template, and I've built most of my system using different components. But, that said, I must be honest I like the MVC direction that this project took a lot more, and I'm contemplating moving my whole CRM across to use Serenity, but that said, I need some functionality that I've already built on my side. My question is then, what is your thinking around adding database support for the menu structures? What I've done is adding a menu structure in database, with a table that I can then populate from the front-end, and that will then update my sidebar. I understand why you did it the way you did, but how would be the best way for me to assist you in making this template better, do you want it in your template? or should I just leave it as a separate part on my side? I would really like to start contributing to this project as well, and as I move my project accross to MVC - from asp.net Forms, I would hope that I can help the community by adding (if possible) functionality to the system, where I have already done some development...
> This is a screenshot of how my system's menu editing screen looks like
> ![image](https://cloud.githubusercontent.com/assets/7837734/18347658/f57066d2-75c6-11e6-909b-1e7b0f98f724.png)
> 
> At the moment I see you support up to 10 levels of menus, which is very clever, but for my datagrid, I only supported 2 levels (which can be changed with little clever UI changes).
> 
> What would your recommendation be? Do I add it and make it available for you to review (to perhaps add it in) ? Or would you rather leave the menu in the Config file, and I add it on my side separately?

Dear Mr.LeonFNortje,
I seen your message above said, i am also looking for the dynamically adding menu into the database, I hope you have done long back, Now i developing ERP system using serenity framework, So can you the code Setting module code for (Menu, Sub menu and others)  which you developed, It will grateful,
Thank you
Haribabu
haribabu74@yahoo.com
