### ISSUE TITLE
EntityId set to null in OnReturn.

### ISSUE THREAD

**Issue by blojayble** [volkanceylan/Serenity#1164]
Hi.

In my custom behavior I wanted to perform some additional actions after creating a new Row.
I need to have ID of the inserted Row, however in both OnReturn and OnAfterSave my ID field is set to null in Row, as well as in Response.

I saw ID field being used that way in MasterDetailBehavior implementation.
Do you have any ideas what might be wrong?

Thanks a lot.

**Comment by volkanceylan** [comment]
If you are using GUID, set it yourself, BeforeSave

**Comment by blojayble** [comment]
I'm using standard auto incremented integer as my primary key.

**Comment by volkanceylan** [comment]
If so you are looking at wrong row or wrong place. It works in all relations.

**Comment by blojayble** [comment]
```C# 
        public void OnReturn(ISaveRequestHandler handler)
        {
            var idField = (Field)((handler.Row as IIdRow).IdField);
            var id1 = idField.AsObject(handler.Row); // null
            var id2 = handler.Response.EntityId; // null
        }
```

This should work properly, right?

**Comment by volkanceylan** [comment]
Yep it works properly everywhere. So your behavior is running for wrong row, or row is not ID row. Debug and see what it is!

**Comment by blojayble** [comment]
In what scenario could a behavior be running for the wrong row?
I looked at that code in debugger and it is the type it's supposed to be.
From the snippet you can also see that it it indeed an ID row, since I cast it (as IIdRow) and use its property without null reference exception.

I also noticed using dev tools in chrome that the Create request returns simply '{}', whereas it's supposed to look like '{EntityId: 123}', which actually makes sense, since it's not set in OnReturn.

**Comment by blojayble** [comment]
I tried creating some other entities (auto-generated) and I also receive only '{}' on Create, although everything seems to work fine and new row is being created, so it's something else.

**Comment by blojayble** [comment]
Ok, quick peek at the source of Serenity made me realize what was wrong: my ID field had only 'PrimaryKey' instead of 'Identity' attribute which gives that field AutoIncrement flag that makes it work correctly. 

My database schema was probably not configured with AI when I autogenerated my project.

Nevertheless, problem solved.
That's why I like open source projects like this!
Thanks.

**Comment by ga5tan** [comment]
@volkanceylan fudge, I only found this article NOW?
are you saying that Guid fields do NOT work in MasterDetail and I have to populate them myself???
I just started doing that, because EVEN AFTER TRACING TO sERENITY SOURCES i WAS NTO ABLE TO FIGURE OUT wtf.
