### ISSUE TITLE
Access Custom Lookup from Editor - Syntax?

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1165]
I've created a custom lookup that is working  on my form.
Now I need to use the custom lookup on a MasterDetail relation but I don't know the syntax.  Thank you for any help!

This is an example of how I am successfully using it on a form:
LoanItemForm
`		
        [LookupEditor(typeof(LoanItem.Scripts.ProductSkuNameSerialStatusLookup), InplaceAdd = true)]
        public Guid EventProductId { get; set; }`

This is my editor.    
`protected validateEntity(row: LoanItemRow, id: number) {
            if (!super.validateEntity(row, id))
                return false;
row.EventProductSkuNameSerial = Event.EventProductRow.getLookup().itemById[row.EventProductId].ProductSkuNameSerial;
 /*Not working, needs CustomLookup*/           
row.ProductSkuName = Event.EventProductRow.getLookup().itemById[row.EventProductId].ProductSkuName;
/*Not working, needs CustomLookup*/
row.EventProductSerial = Event.EventProductRow.getLookup().itemById[row.EventProductId].Serial;
            
row.ProductStatusName = Administration.ProductStatusRow.getLookup().itemById[row.ProductStatusId].Name;`

**Comment by volkanceylan** [comment]
Use Q.getLookup('yourlookupkey') to access your custom lookup.
