### ISSUE TITLE
 'System.NotImplementedException' on new LocalizationRowHandle

### ISSUE THREAD

**Issue by masterlilou** [volkanceylan/Serenity#1167]
Using the LocalizationRow example done in serene Northwind, I try to implement the following classes

        public class RowFields : RowFieldsBase
        {
            public **StringField** CategoryID;    /// -> initialy a **Int32Field**  
            public StringField CategoryName;
            public StringField Description;
            public StreamField Picture;
  }

    public class RowFields : RowFieldsBase
        {
            public **Int32Field** Id;
            public StringField CategoryId;   /// -> initialy a **Int32Field**  
            public Int32Field LanguageId;
            public StringField CategoryName;
     }

The difference between the original source is that i change the CategoryID into StringField instead of an int32Field. 

During execution, it raises the following exception'System.NotImplementedException'  ... not managed in the code.

private class MySaveHandler : SaveRequestHandler<MyRow, SaveWithLocalizationRequest<MyRow>, SaveResponse>
        {
            protected override void AfterSave()
            {
   ......
                        _new LocalizationRowHandler<MyRow>().Update<Entities.CategoryLangRow>(this.UnitOfWork, pair.Value, Convert.ToInt32(pair.Key));_ // raised here
   ...
        }

Is it possible to correct the code ? 

Masterlilou

**Comment by volkanceylan** [comment]
Your row must be an IIdRow and CategoryId != CategoryID

**Comment by masterlilou** [comment]
Ok I change my code to have Int32Field primary keys for both tables.

Another point, the Category name in Serene is not translated according to the site langage setting. 

Is it normal ? 

Any example 

Masterlilou

**Comment by brunobola** [comment]
You can change the category and display names if you want. It's normal that serenity won't correctly know an entity name gender in all the translations.

**Comment by volkanceylan** [comment]
Search for Category in Northwind texts. Youll see how it is translated.
