### ISSUE TITLE
afterLoadEntity Issue

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1169]
after adding afterLoadEntity method in dialog.ts, i am getting extra buttons in toolbar, like
Undelete, Localization, Clone, when dialog is opened.
If i comment out afterLoadEntity then these buttons doesn't appear when dialog is opened.
I haven't turned on any of these buttons in afterLoadEntity method, still it appears.
can you help me with this.
regards
Shailesh

**Comment by Estrusco** [comment]
Have you called super.afterLoadEntity in your afterLoadEntity override?

```ts
protected afterLoadEntity() {
    super.afterLoadEntity();

    [...]
}
```

**Comment by shaileshbc** [comment]
Ok, i forgot to enter that.
after adding super.afterLoadEntity(), it does not show extra buttons.
thanks
regards
Shailesh
