### ISSUE TITLE
Calender unable to save new events

### ISSUE THREAD

**Issue by denonc** [volkanceylan/Serenity#117]
Hi, I have try the Calendar (under Theme Samples) but the system is unable to save the new events. Understand that the Calendar is an additional feature outside serenity core, but hope you could advise on this issue.

Many thanks!

**Comment by volkanceylan** [comment]
That is just a sample from AdminLTE as is. None of them has any connection. You need to create a table, handle calendar events, save them with ajax, load them from database etc.

**Comment by denonc** [comment]
Got it! Thanks!
