### ISSUE TITLE
getLookup() don't refresh data

### ISSUE THREAD

**Issue by Pinellus** [volkanceylan/Serenity#1170]
Hi all,
I have this lookup script. If I update data into "ClienteSimulazioniTotaleRow" then this code doesn't show the new date.

```
Q.reloadLookup("ClienteSimulazioniTotale");
var byId = ClienteSimulazioniTotaleRow.getLookup().itemById;
var isEnable = byId[this.IdCliente].IsEnable;
var gameOver = byId[this.IdCliente].GameOver;
```
Can you help me?
Thank's

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serenity/issues/846

**Comment by Pinellus** [comment]
Yes, I already saw. But I did not understand the implementation.
Can you give me an example?

**Comment by Pinellus** [comment]
Ok. For those who were to meet the same problem.

Make a custom Lookup Sript Class like this:

```
namespace eBillEE.EBillEE
{
    using eBillEE.EBillEE.Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;
    using System;

    [LookupScript("ClienteSimulazioniTotale")]
    public sealed class ClienteSimulazioniTotale : RowLookupScript<ClienteSimulazioniTotaleRow>
    {
        public ClienteSimulazioniTotale()
        {
            Expiration = TimeSpan.FromDays(-1);
        }
    }
}
```

Then in your Row class you must *DELETE* the annotation "LookupScript".

This work for me.
Thank's

**Comment by volkanceylan** [comment]
You don't need this in 2.4.6. LookupScript attribute now has expiration property
