### ISSUE TITLE
Filtering lookup editor

### ISSUE THREAD

**Issue by mohammad0011** [volkanceylan/Serenity#1171]
First of all, I'm sorry for this stupid question, and my poor English ):

I have a lookup editor which is based on a database tabe, I want load some of the records in the table based on the value of a column 'type' ( an int16 type column).
How and where can I apply this (where type=1)?

Can I do this by using ordanary lookup script on the table row class, or I have to write a custom lookup class?

Any example will be helpful.

Thanks in advance.

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serenity/issues/184

**Comment by mohammad0011** [comment]
Thanks for you reply.
But, for the server side implementation,  instead of constant value 

`query.Where(XYZRow.Fields.XyzID` != 0);`


I want to pass the value dynamically at run time, some thing like 

`query.Where(XYZRow.Fields.XyzID != parameter);`

How can I achieve that?

**Comment by volkanceylan** [comment]
You can't. See filtered lookup in dialog sample.

**Comment by mohammad0011** [comment]
Thanks Volkan,
I achieved by using filterField and filterValue.
