### ISSUE TITLE
Change lookupkey in typescript

### ISSUE THREAD

**Issue by ahsansolution** [volkanceylan/Serenity#1172]
Hi Jaiq,

I have this lookup in form

 public class ProductPriceForm
 {
        [LookupEditor("MasterModule.SparePartNumber")]
        public Int32 ProductId { get; set; }
        [LookupEditor("MasterModule.OrderCategory")]
        public Int32 OrderCategoryId { get; set; }
        public Decimal Price { get; set; }
}

Ho to to change lookupkey programmatically? i wanto to change lookupkey in typescript ProductId field from 'MasterModule.SparePartNumber' to 'MasterModule.UnitNumber'

**Comment by volkanceylan** [comment]
You should make multiple forms and dialogs.
