### ISSUE TITLE
Can't display DateTimeEditor

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1174]
I'm trying to edit a datetime value with a date and time picker using:
[DateTimeKind(DateTimeKind.Local), DateFormatter(DisplayFormat = "dd-MM-yyyy HH:mm.ss"), DisplayName("Data Inicio"), DateTimeEditor]

but get:
![image](https://cloud.githubusercontent.com/assets/10889019/18417847/1afa85cc-7833-11e6-8687-fe5466a84c37.png)

**Comment by volkanceylan** [comment]
Transform templates if you change editor type. It says no DateEditor, so you had a DateEditor before, now DateTimEditor.

**Comment by brunobola** [comment]
Thanks, thumbs up, u're help is precious ;)
