### ISSUE TITLE
Calculated Field not updated when changing Time value from DateTime Field

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1175]
I've got a Form with a calculated field like so:

`constructor() {
            super();            

            (this.form.DataInicio).changeSelect2(e => {
                var duracao = (this.form.DataFim.valueAsDate.valueOf() - this.form.DataInicio.valueAsDate.valueOf());
                this.form.DuracaoMin.value = (duracao/1000)/(60);
            });

            (this.form.DataFim).changeSelect2(e => {
                var duracao = (this.form.DataFim.valueAsDate.valueOf() - this.form.DataInicio.valueAsDate.valueOf());
                this.form.DuracaoMin.value = (duracao/1000)/(60);
            });
        }` 

But the value "DuracaoMin" only changes when alter the Date Value, won't work on Time change, is it a bug ?

**Comment by volkanceylan** [comment]
It's not a bug. It's a composite editor. It has two different elements. You are attaching to only first.

**Comment by brunobola** [comment]
And to accomplish this any help ? :)
Sorry volkan, i'm just getting started and y've got me motivated :)

**Comment by brunobola** [comment]
Any tip, i've tried to cast to Serenity.TimeEditor or accessing elements but don't really know how to do it, any help :(

**Comment by brunobola** [comment]
Anyone can do this guys ?

**Comment by volkanceylan** [comment]
Try this.form.DuracaoMin.element.closest('.field').find('.time')

**Comment by brunobola** [comment]
Excelent tip, the start date and time [DataInicio] and the end date and time [DataFim] changed know correctly updates the values, thanks.

Working code:
`            (this.form.DataInicio).change(e => {
                var duracao = (this.form.DataFim.valueAsDate.valueOf() - this.form.DataInicio.valueAsDate.valueOf());
                this.form.DuracaoMin.value = (duracao / 1000) / (60);
            });            

            this.form.DataInicio.element.closest('.field').find('.time').change(e => {
                var duracao = (this.form.DataFim.valueAsDate.valueOf() - this.form.DataInicio.valueAsDate.valueOf());
                this.form.DuracaoMin.value = (duracao / 1000) / (60);
            });            

            (this.form.DataFim).change(e => {
                var duracao = (this.form.DataFim.valueAsDate.valueOf() - this.form.DataInicio.valueAsDate.valueOf());
                this.form.DuracaoMin.value = (duracao / 1000) / (60);
            });

            this.form.DataFim.element.closest('.field').find('.time').change(e => {
                var duracao = (this.form.DataFim.valueAsDate.valueOf() - this.form.DataInicio.valueAsDate.valueOf());
                this.form.DuracaoMin.value = (duracao / 1000) / (60);
            });  `

You're the best volkan :+1:
