### ISSUE TITLE
Change Menu Width

### ISSUE THREAD

**Issue by justme-yeld** [volkanceylan/Serenity#1176]
Sorry guys bit rusty here, how to change menu width.
I know, i've read the tutorial, but you guys know the answer in an instant.

Thanks.

**Comment by jsbUSMC** [comment]
Which menu? The sidebar menu? You should try to figure these things out on your own instead of being given the answer. It's in the Less files.

**Comment by brunobola** [comment]
View the site.theme.less file, but u could try to find it yourself other time ;)
