### ISSUE TITLE
Guids on intersection entity

### ISSUE THREAD

**Issue by covertops69** [volkanceylan/Serenity#1178]
I have a schema much like your movie tutorial code base i.e. Movies, Genres and MovieGenres (intersection entity).  The only exception is that my primary keys are uniqueidentifiers and are auto generated with newsequentialid() rather than identity specifications.

With that as background then, in exactly the same way I want to be able select multiple genres on the movie form.  After I select my genres and save the form, the platforms throws a SQL error and tells me that the intersection entity's primary key can't be NULL.  Why is serenity trying to save the intersection entity with a NULL value for it's primary key?

How do I get around this?

**Comment by volkanceylan** [comment]
Do you have Insertable(false) on your Guid primary key?

**Comment by covertops69** [comment]
That fixed it, thanks.
