### ISSUE TITLE
Crash VS when build T4 Template

### ISSUE THREAD

**Issue by Pinellus** [volkanceylan/Serenity#1179]
Hi,
strange behavior of VS (only on my local istance on Windows 10)
When I try to build T4 Template, Visual Studio crash. No way.
Going to check line by line ClientTypes.tt file, I found that crash occurs here: 

```
var tsTypeLister = new TSTypeLister(webDir);
var tsTypes = tsTypeLister.List();
```

Any suggestions?
Thank's

**Comment by RouteTech** [comment]
I had a similar problem (#1058). 
I found that VS2015 requires update 3 and that the files mentioned in issue 1058 NOT be updated.

HTH

**Comment by volkanceylan** [comment]
Find var jsEngine = new MsieJsEngine() in CodeGenerationHelpers.ttinclude and replace it with var jsEngine = new MsieJsEngine(new JsEngineSettings { EngineMode = JsEngineMode.ChakraIeJsRt, UseEcmaScript5Polyfill = true, UseJson2Library = true });

This is something related to Edge javascript engine in anniversary update.

**Comment by Pinellus** [comment]
Works like a charm!!
Great Volkan!
