### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#118]
I have created a user and grant him all but he cannot view customer. After setting this I loggen in by that user, customer menu has gone which is expected, but when I open Order form it throw an exception, saying 

An exception of type 'Serenity.Services.ValidationError' occurred in Serenity.Core.dll but was not handled in user code

Additional information: Authorization has been denied for this request!

After pressing continue it open but without data, clicking on refresh button make grid to bind.

**Comment by volkanceylan** [comment]
If he cannot view customers, he cannot load customer lookup and create order simply.

If you want to let user add order while hiding customers page, you need to change permission for CustomerLookup class, LookupScript attribute:

[LookupScript("Northwind.Customer", Permission = "?")]

This grants lookup permission to all logged in users.

**Comment by dfaruque** [comment]
Thank you for you quick response, it works.
One more thing, If I want to give permission to someone that he can only add customer but cannot modify/delete them, how can I achieve this.

**Comment by volkanceylan** [comment]
There are InsertPermission, DeletePermission and UpdatePermission attributes for these.
