### ISSUE TITLE
PropertyDialog

### ISSUE THREAD

**Issue by manivishnupriya** [volkanceylan/Serenity#1180]
I have a Serenity.**PropertyDialog** that displays a form with 3 fields (Which are select2 lists loaded using lookupeditor). Also the form has 2 buttons "Add" and "Cancel"
I want to set the default value in all the three selectLists. 

I already have the values fetched from another grid using this Propertydialog's constructor. Just have to set those values as defaults in the respective lists.

this,form.List1.value = 1234; //This doesn't work
this.form.List1.changeSelect2(e=> {.....  //This also doesn't work

This might be a simple issue. But Please help me on this. 
                
**EntityDialog have some methods like LoadNewIDandOpenDialog, LoadEntityandOpenDialog etc. which i think i cannot use it in property dialog.

**Comment by volkanceylan** [comment]
See LoadInitialEntity method in source, override it, set your initial values

**Comment by john20xdoe** [comment]
@manivishnupriya can you post your PropertyDialog and Form snippets?
