### ISSUE TITLE
Text book Formatter throws "can't find XXX formatter type!"

### ISSUE THREAD

**Issue by covertops69** [volkanceylan/Serenity#1181]
I created the exact same formatter as is used in the movies tutorial as is described here https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/allowing_multiple_genre_selection.html.  I build, then run the template generator with success.

When I run the application and navigate to my grid, javascript throws a "can't find mysolution.myproject.web.admin formatter type!".  I suspect this has something to do with the namespace, since it's the only thing that differs from the tutorial.

Any ideas as to how to solve this one?

**Comment by volkanceylan** [comment]
Lowercase module names not supported

**Comment by covertops69** [comment]
Appologies, that's not the exact namespace, I was just using it as an example.  The real namespace is actually "BlueStar.ActiveDB.ChannelListFormatter".

**Comment by volkanceylan** [comment]
Check that it matches exact namespace of your row, case sensitive

**Comment by covertops69** [comment]
That didn't work.

In the tutorial example the MovieRow's namespace is MovieTutorial.MovieDB.Entities and the GenreListFormatter.ts namespace is MovieTutorial.MovieDB.

Is there something I'm missing?

**Comment by volkanceylan** [comment]
If it works there, find 7 differences between codes.

**Comment by covertops69** [comment]
There's definitely a namespacing issue here.

The project above I name MyProject.Web.Admin, formatter throws error described above.  I've just created a new project named MyProject and the formatter works.

I noticed that the template adds a .Web onto the end of the project name, could it be related to me naming convention?

**Comment by volkanceylan** [comment]
.Web is not part of root namespace. It is not added in guide.

**Comment by covertops69** [comment]
I'm just pointing out that if I create a project named MyProject.Web.Admin (which is common practice) the formatter falls over.  If I create a project name MyProject, it doesn't.

**Comment by volkanceylan** [comment]
You shouldnt use any dot while creating project first time. So it should be MyProject. After creation you may change project name.

**Comment by covertops69** [comment]
Thanks for the pointer ;)

**Comment by JohnRanger** [comment]
Hi all, I had the same Problem. 

My formatter was named: isDefaultFormatter which threw the above mentioned error at runtime - even when it did compile and T4 transform just fine.

Solution: Rename the formatter (including the file Name) to UPERCASE Start: IsDefaultFormatter - respective the file to: IsDefaultFormatter.ts.

...and it works. :-)

Again - thanks to JaiQ/Volkan for the impressive Progress I have seen since I last time (avout 1 year ago) worked with the saltarelle Version of Serenity.

With Kind regards,

John
