### ISSUE TITLE
how can i open a new dialog after i click the save button on old dialog?

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#1182]

**Comment by volkanceylan** [comment]
See onSaveSuccess method

**Comment by rgilsimoes** [comment]
I've made a new button for this purpose:

protected getToolbarButtons() {
            let btns = super.getToolbarButtons();
            btns.push({
                title: Q.text('Save&New'),
                icon: 'glyphicon glyphicon-duplicate',
                onClick: () =>
                {
                    this.save(response => this.loadNewAndOpenDialog());
                }
            });
            return btns;
        }
