### ISSUE TITLE
Problem Master-Detail

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1183]
Hello all, i'm trying to implement a master-detail but i can't seem to populate description fields od entities (yes I've read the tutorial and and try to find by myself to find the problem).

My code:
Main Entity (AreaInvestigacao):

- `public

 class AreaInvestigacaoForm
    {
         ...
        [CentroAreaInvestigacaoEditor, DisplayName("Centros")]
        public List<Entities.CentroAreaInvestigacaoEditorRow> Centros { get; set; }
    }`

- `public sealed class AreaInvestigacaoRow : Row, IIdRow, INameRow
    {
       ...
      [DisplayName("Centros"), MasterDetailRelation("AreaInvestigacaoID"), SetFieldFlags(FieldFlags.ClientSide)]
        public List<CentroAreaInvestigacaoEditorRow> Centros
        {
            get { return Fields.Centros[this]; }
            set { Fields.Centros[this] = value; }
        }
       ...
        public AreaInvestigacaoRow()
            : base(Fields)
        {
        }

      public class RowFields : RowFieldsBase
      {
            ...
            public readonly RowListField<CentroAreaInvestigacaoEditorRow> Centros;
            ...
      }

Details Entity (CentroAreaInvestigacao):
Specific Editor
- `/// <reference path="../../Common/Helpers/GridEditorBase.ts" />
namespace PNCCA.Tabelas {

    @Serenity.Decorators.registerEditor()
    export class CentroAreaInvestigacaoEditor
        extends Common.GridEditorBase<CentroAreaInvestigacaoEditorRow> {
        protected getColumnsKey() { return "Tabelas.CentroAreaInvestigacaoEditor"; }
        protected getDialogType() { return CentroAreaInvestigacaoEditorDialog; }
        protected getLocalTextPrefix() { return CentroAreaInvestigacaoEditorRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        protected getAddButtonCaption() {
            return "Adicionar Centro";
        }

        protected validateEntity(row: CentroAreaInvestigacaoEditorRow, id: number) {

            if (!super.validateEntity(row, id))
                return false;

            row.CentroNome = CentroRow.getLookup().itemById[row.CentroId].Nome;
            
            return true;
        }
    }
}`

The problem is the entity won't display the Nome Property even after making the validateEntity like above (has in tutorial).

What can be the problem ?

**Comment by edson** [comment]
Hi, there.

Probably you missed the includedColumns in MasterDetailRelation("AreaInvestigacaoID")
Maybe it would be

 [MasterDetailRelation(foreignKey: "AreaInvestigacaoID", IncludeColumns = "CentroNome")] ?

Regards

**Comment by brunobola** [comment]
Thanks, solved.
