### ISSUE TITLE
Date Conversion

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#1184]
@volkanceylan 

I did a deploy today in my business server, that have a production SQL Server in pt-BR Language, instead a Developer SQL Server in en-US language.

So, in these scenario, we have the problem with date or datetime conversion: In en-US, the datetime format is mm-dd-yyyy, instead a pt-BR format of dd-mm-yyyy.

So, if I choose 13/08/2016 in date picker, it's return an error showed in attached file

![date conversion](https://cloud.githubusercontent.com/assets/19523455/18479426/5495ac5c-79ab-11e6-86f5-5155949b557e.png)

In classical ASP.NET, to resolve this problem, we insert  "SET DATEFORMAT DMY;"

the question is: how to deal this in Serenity?

**Comment by rolembergfilho** [comment]
ps.: In web.config I did this:

```
    <globalization culture="pt-BR" uiCulture="pt-BR" />
  </system.web>
```

but it's not worked...

**Comment by brunobola** [comment]
Have you tried to use the [DateFormatter(DisplayFormat = "MM/dd/yyyy HH:mm.ss")] for instance ?

**Comment by volkanceylan** [comment]
Set your server language to English. Serenity sends it to SQL in ISO format, yyyyMMdd

**Comment by volkanceylan** [comment]
Server user default language i mean

**Comment by brunobola** [comment]
Depending on the installation of is sql server language or the sql user language used is not a good practice i think, volkan is right use always the default language (en-US) and customize user interface according to current culture can prevent you from many issues because of regional settings and formats.

**Comment by rolembergfilho** [comment]
Unhappily I can't change the SQL Server database language for 2 reason:

1 - I have a lot of database in this SQL (it's legaccy)
2 - It's a single package language installation...

I'll try the Bruno Bola's suggestion.

The best pratice is insert dateformat dmy

**Comment by brunobola** [comment]
You can try in alternative to create a sql user with us english language, then use it just for this development and it might solve your issues.

**Comment by volkanceylan** [comment]
Actually you shouldn't have this issue after 2.3.5, but don't know why you are having.

**Comment by edson** [comment]
Well... Maybe an IIS and operating system issue? http://stackoverflow.com/questions/11237765/datetime-format-issue-in-iis-7-server

**Comment by rolembergfilho** [comment]
@volkanceylan I'm using a 2.4.4 version.

@brunobola, this solution is so dangerous to do in this server, because the other legacy database and programns server.

I'll try to install a new SQL Server instance, in English version.

**Comment by volkanceylan** [comment]
You just need to set English as default language for the user you access to server, not server language.

**Comment by brunobola** [comment]
@rolembergfilho You don't understated what I told, if you create a new SQL server user that you currently only use to your current project, all other projects and development are untouchable , your server settings remains the same, its as safe as you can get, off course the only danger its you use that user to other developments also, but you have to keep it in mind. 

Nevertheless, if you have the resources to create another instance with default language en-US it would solve all that issues (SQL Server Express is free) so go ahead and do what you might find more suitable for you.

**Comment by rolembergfilho** [comment]
@brunobola, I must reveal that I'm shame! Your solution is so simple and funtional!

so, I create a new database user caled "teste", with English as default language.

It's works!!!

You rocks!

Thanks!
