### ISSUE TITLE
How to refresh detail grid in master/details relations

### ISSUE THREAD

**Issue by mohammad0011** [volkanceylan/Serenity#1185]
Hi, 
I have master/detail relation in which, I edit the detail grid entity at runtime in the master dialog . as following 

this.form.Quantity.element[0].onchange = (e) => {
	   for(var i=0;i<this.entity.DetailList.length;i++){
		this.entity.DetailList[i].Quantity = this.entity.DetailList[i].Quantity *   (e.target.value as number);
	this.entity.DetailList[i].LineTotal = this.entity.DetailList[i].Quntity * this.entity.DetailList[i].LineTotal ;
	}
};

 so how can I refresh the grid to reflect the data in the entity object.

Thanks in advance.

**Comment by volkanceylan** [comment]
you are modifying wrong list. you must read form.YourDetailList.value, modify items, them set form.YourDetailList.value to new list.

**Comment by mohammad0011** [comment]
Thank you very much @volkanceylan :)
