### ISSUE TITLE
Best way to dynamically create Layout

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1186]
I'd like to create a page similar to the Dashboard but the top buttons (4 buttons by default) where just created dynamically according to a table in my database.

Best way to do this ?

**Comment by volkanceylan** [comment]
Sorry but this has no relation to Serenity itself. People started to use this as general Asp.Net / programming help forum, which it is not.

**Comment by brunobola** [comment]
Ok, but a tip can't do so arm :(

I can achieve it myself, but I put it here because others like me might saw it useful also, and I've already saw you help answer questions about layout, don't really understand the diference.

Thanks anyway.
