### ISSUE TITLE
Why I added 'Expression' , the value of this field is not saved at the time of the save. 

### ISSUE THREAD

**Issue by caitingting** [volkanceylan/Serenity#1188]
Hello！
[DisplayName("审核状态"),Expression("CASE WHEN AuditStatus IS NULL THEN 1 ELSE AuditStatus END")]
        public AuditStatus? AuditStatus
        {
            get { return (AuditStatus?)Fields.AuditStatus[this]; }
            set { Fields.AuditStatus[this] = (Int32?)value; }
        }
Why I added 'Expression("CASE WHEN AuditStatus IS NULL THEN 1 ELSE AuditStatus END")' , the value of this field is not saved at the time of the save.

**Comment by volkanceylan** [comment]
How do you expect a calculated field to be saved??

**Comment by volkanceylan** [comment]
Add another calculatef expression field if you intend to display field value differently.
