### ISSUE TITLE
LookUpEditor with Multiple = true cascading programmatically in a Form

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1189]
I have Row Fields as 
`[DisplayName("Sites")]

        [LookupEditor(typeof(SiteLookUp), Multiple = true), ClientSide
        [LinkingSetRelation(typeof(UserSitesRow), "UserId", "SiteId")]
        public List<Int32> Sites
        {
            get { return Fields.Sites[this]; }
            set { Fields.Sites[this] = value; }
        }
        [ForeignKey("[xyz].[Customer]", "CustomerId"), LeftJoin("cust"), NotNull]
        [LookupEditor(typeof(CustomerLookUp)), LookupInclude]
        public Int32? CustomerId
        {
            get { return Fields.CustomerId[this]; }
            set { Fields.CustomerId[this] = value; }
        }`
I want to cascade Sites to CustomerId in a Form.
So i added following in xyzDialog.ts constructor

(this.form.Sites as any).cascaseFrom = "CustomerId";
this.form.Sites.cascadeField = "CustomerId";

It's not working, so tried with following code
                this.form.CustomerId.changeSelect2(e => {
                    var customerId = this.form.CustomerId.value;
                    if (!Q.isEmptyOrNull(customerId))
                    {
                        var sites = xyz.Master.SiteRow.getLookup().items.filter(x => x.CustomerId == parseInt(customerId));
                        this.form.Sites.clearItems();
                        sites.forEach(x => this.form.Sites.addItem(x.SiteId.toString(), x.SiteName));
                    }
                });
it gives runtime error.
how to cascade both the fields programmatically.
It works in case if i write
[DisplayName("Customer Name"), LookupEditor(typeof(CustomerLookUp))]

        public Int32 CustomerId { get; set; }

        [LookupEditor(typeof(SiteLookUp), Multiple =true, CascadeFrom ="CustomerId",CascadeField ="CustomerId")]

        public List<Int32> Sites { get; set; }
in a xyzForm.cs, but want it to be done programmatically, as i require this cascading to work based on some condition.
regards
Shailesh

**Comment by volkanceylan** [comment]
Whatnis cascaseFrom

**Comment by shaileshbc** [comment]
sorry it's a typo error.
thanks 
regards
Shailesh

**Comment by mustafalotiya** [comment]
Can you please share code ..

thanks in advance.

**Comment by shaileshbc** [comment]
It was a typo error and it has been resolved. thank you.
regards
Shailesh

**Comment by mustafalotiya** [comment]
Can u please share working code. I'm having trouble to run same code.

Thanks

**Comment by shaileshbc** [comment]
Dear mustafalotiya,
i have entered following code in constructor of a xyzdialog.ts
this.form.childId.cascadeFrom = CustomerId;
                this.form.childId.cascadeField = CustomerId;
where childId is cascaded to CustomerId;
regards
Shailesh
