### ISSUE TITLE
Difference between XYZDialog and XYZEditorDialog

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1191]
What's the difference between these two dialogs? I can;t seem to find where XYZEditorDialog is being used or if being used at all.

**Comment by dfaruque** [comment]
XYZDialog is a primary dialog for an entity and it has crud functionality directly to database.
XYZEditorDialog is a detail dialog for an master-detail relationship. Its operations are in-memory.

**Comment by john20xdoe** [comment]
Thanks!
