### ISSUE TITLE
Slickgrid & Tabs

### ISSUE THREAD

**Issue by nscgllc** [volkanceylan/Serenity#1192]
First...this framework is great!  Thanks for all the hard work.  

I am having an issue with seeing the grid data when using the slickgrid with AdminLTE tabs.  The first tab shows the grid data fine.  However the 2nd tab shows the column headings and footer (with the correct number of items....but the grid data does not display.  If I right click in the grid and view the DOM the data displays....I think its a focus issue but cannot determine where I should change the code.  I am not receiving any errors.  

![untitled picture](https://cloud.githubusercontent.com/assets/19638116/18538207/0b972bbc-7ad1-11e6-8ad7-eb3d8886f374.png)

Any help would be greatly appreciated.  I search the issues and visualstudio galleria but didn't find any answers.

**Comment by awesomegithubusername** [comment]
Any error in Console? Also, I like the way tabs look in your screenshot. Would be nice if you shared how you've implemented it.

**Comment by volkanceylan** [comment]
SlickGrid can't do layout properly when invisible. So when a tab becomes visible, you need to trigger its resizeCanvas method.

Call this on active tab change

$('.require-layout').filter(':visible').each(function (i, e) {
                $(e).triggerHandler('layout');
            });

**Comment by rgilsimoes** [comment]
@nscgllc Do you have to include all code from Serenity in the Tabs or is it possible to load them separate from original sources?
Can you post a sample of that page with the tabs?
Thanks!

**Comment by nscgllc** [comment]
@volkanceylan I am trying as you suggested but its still not displaying.  I may not be calling 'on active tab change' correct.  My code is below....

@awesomegithubusername @rgilsimoes I will post a complete sample once I have it working.

Tabs....
    <section class="col-lg-7 connectedSortable">
        
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title text-info"><i class="fa fa-files-o"></i> Client Activity</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body" style="width:100%">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#ca_tab_1" data-toggle="tab">Episodes</a></li>
                        <li><a id="PaymentTab" href="#ca_tab_2" data-toggle="tab">Payment History</a></li>
                        <li><a href="#ca_tab_4" data-toggle="tab">Medical Records & Documents</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="ca_tab_1">
                            <div id="ClientEpisodes">

                            </div>
                        </div>
                        <div class="tab-pane" id="ca_tab_2">
                            <div id="ClientPayments">

                            </div>
                        </div>

                        <div class="tab-pane" id="ca_tab_4">
                            <p>
                                Client medical records and other client documents.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </section>

On active tab click...
<script type="text/javascript">
    jQuery(function () {
        $('#PaymentTab').click(function () {
            try {
                    $('.require-layout').filter(':visible').each(function (i, e) {
                    $(e).triggerHandler('layout');
                });
            }
            catch (e) {
                Q.notifyError("Error payments tab Message: " + e.message);
                Q.notifyError(e.number & 0xFFFF);
                Q.notifyError("Error Name: " + e.name);
            }
    });
  });
</script>

Grid is loaded when page is first loaded....
<script type="text/javascript">
    jQuery(function () {
        try {
            new MyClientPaymentsGrid($('#ClientPayments'), {}).init();
            Q.initFullHeightGridPage($('#ClientPayments'));
        }
        catch (e) {
            Q.notifyError("Error loading payments Message: " + e.message);
            Q.notifyError(e.number & 0xFFFF);
            Q.notifyError("Error Name: " + e.name);
        }
....

**Comment by volkanceylan** [comment]
Please use ``` for code

You need to attach to activate event, not click event. Your tab is not visible yet at click event i guess.

**Comment by nscgllc** [comment]
@volkanceylan binding to the activate event did work!  Thanks.....here is the code.  I used boostrap js vs jquery ui.  jquery ui binding to keep the tabs look-n-feel the same as Admin LTE....for what that is worth.  

@awesomegithubusername @rgilsimoes .... this should be all the sample code, but if you think your missing something let me know.

`<script type="text/javascript">
    $(document).ready(function () {
        $(".nav-tabs a").click(function () {
            $(this).tab('show');
        });
        $('.nav-tabs a').on('shown.bs.tab', function (event) {
            $('.require-layout').filter(':visible').each(function (i, e) {
                $(e).triggerHandler('layout');
            });
        });
    });
</script>`
