### ISSUE TITLE
String or binary data would be truncated

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1193]
Hi guys, 

getting a very odd problem here...

I created a page in serene that works fine for some users but not for others. Serene errors out with "String or binary data would be truncated" for some users.

I've enabled logging, other than the username SQL is exactly the same for users who it does and doesn't work for

**Doesn't work**
DECLARE @p1 NVARCHAR(4000) = 'embleyj';
DECLARE @p2 NVARCHAR(4000) = 'LDNW540';
DECLARE @p3 BIT = 0;
DECLARE @p4 DATETIME2 = '20160915';
DECLARE @p5 BIT = 0;
DECLARE @p6 DATETIME2 = '20160916';
DECLARE @p7 NVARCHAR(1) = NULL;
DECLARE @p8 NVARCHAR(4000) = 'Domain\jembley';
INSERT INTO [dbo].[LocalAdministrators] ([DomainAndUsername], [Hostname], [AddedToAdminGroup], [DateAdded], [RemovedFromAdminGroup], [RemoveFromAdminDate], [Notes], [LastEditBy]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8);
SELECT SCOPE_IDENTITY() AS IDCOLUMNVALUE

**Does work**
DECLARE @p1 NVARCHAR(4000) = 'abelal';
DECLARE @p2 NVARCHAR(4000) = 'LDNW540';
DECLARE @p3 BIT = 0;
DECLARE @p4 DATETIME2 = '20160915';
DECLARE @p5 BIT = 0;
DECLARE @p6 DATETIME2 = '20160916';
DECLARE @p7 NVARCHAR(1) = NULL;
DECLARE @p8 NVARCHAR(4000) = 'Domain\abelal';
INSERT INTO [dbo].[LocalAdministrators] ([DomainAndUsername], [Hostname], [AddedToAdminGroup], [DateAdded], [RemovedFromAdminGroup], [RemoveFromAdminDate], [Notes], [LastEditBy]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8);
SELECT SCOPE_IDENTITY() AS IDCOLUMNVALUE

any ideas?

**Comment by joaorod** [comment]
First column of table has a maximum length of 6

**Comment by joaorod** [comment]
Or column 8 has max len of 15

**Comment by abelal83** [comment]
Hi,

Thanks for you quick response, column 8 is 20 and column 1 is 50 so I don’t think it’s that.

CREATE TABLE [dbo].[LocalAdministrators](
       [ID] [int] IDENTITY(1,1) NOT NULL,
       [DomainAndUsername] [nvarchar](50) NOT NULL,
       [Hostname] [nvarchar](50) NOT NULL,
       [AddedToAdminGroup] [bit] NULL,
       [DateAdded] [date] NULL,
       [RemovedFromAdminGroup] [bit] NULL,
       [RemoveFromAdminDate] [date] NULL,
       [Notes] [nvarchar](max) NULL,
       [LastEditBy] [nvarchar](20) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


Also I’m able to execute this in SQL directly which errors in serene

DECLARE @p1<https://github.com/p1> NVARCHAR(4000) = 'embleyj';
DECLARE @p2<https://github.com/p2> NVARCHAR(4000) = 'LDNW540';
DECLARE @p3<https://github.com/p3> BIT = 0;
DECLARE @p4<https://github.com/p4> DATETIME2 = '20160915';
DECLARE @p5<https://github.com/p5> BIT = 0;
DECLARE @p6<https://github.com/p6> DATETIME2 = '20160916';
DECLARE @p7<https://github.com/p7> NVARCHAR(1) = NULL;
DECLARE @p8<https://github.com/p8> NVARCHAR(4000) = 'Domain\jembley';
INSERT INTO [dbo].LocalAdministrators<https://github.com/volkanceylan/Serenity/issues/%5BDomainAndUsername%5D,%20%5BHostname%5D,%20%5BAddedToAdminGroup%5D,%20%5BDateAdded%5D,%20%5BRemovedFromAdminGroup%5D,%20%5BRemoveFromAdminDate%5D,%20%5BNotes%5D,%20%5BLastEditBy%5D> VALUES (@p1<https://github.com/p1>, @p2<https://github.com/p2>, @p3<https://github.com/p3>, @p4<https://github.com/p4>, @p5<https://github.com/p5>, @p6<https://github.com/p6>, @p7<https://github.com/p7>, @p8<https://github.com/p8>);
SELECT SCOPE_IDENTITY() AS IDCOLUMNVALUE

**Comment by volkanceylan** [comment]
Possible one is username. This is not related to Serenity.

**Comment by abelal83** [comment]
Correct not a serenity problem. It was a trigger that caused the issue.

Thanks for the help as usual.
