### ISSUE TITLE
Enumeditor

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#1194]
Hi,

Please, is there a way to use enumeditor and return a string rather than an int?

It is simplier as there is also a loader from excel, and I try to avoid too much parsing on this side.

Thank you,

**Comment by volkanceylan** [comment]
Need to write your own enum editor for this. See source of it.

**Comment by Boumboumjack** [comment]
Thank you,

How should I "plug" my custom editor? Is there a way to overide it in form or dialog?

**Comment by volkanceylan** [comment]
As usual, write your editor, transform templates
