### ISSUE TITLE
Master / Slave Column display does not support expression evaluation

### ISSUE THREAD

**Issue by masterlilou** [volkanceylan/Serenity#1196]
Hello, 

I try to build a  SMA tools. 

I have the following issue 

in Row.cs, I  add a text field referring the name of a collaborator, looks like ...  Expression("h.L_NOM_PRENOM") ...

I build the application and try to use it, no problem detected. 

The problem raises when I implement a Master / Slave as defined in 'serenity_guide.pdf'. 

This column is always empty in the column view.

Is it a bug ? 

MaterLilou

**Comment by volkanceylan** [comment]
Read the guide mr bug guy

**Comment by volkanceylan** [comment]
Or have a look at OrderDetailsEditor and see why i had to manually set LineTotal

**Comment by masterlilou** [comment]
Oh i have a new nick name 

mr bug nice ;o)

The way you handle LineTotal field helps me.

Thanks
