### ISSUE TITLE
SQL Server 2008 R2 Issue

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1197]
Hi @volkanceylan,
Can you tell me how to handle this :

```
/*...*/
SELECT /*...*/ FROM  /*...*/
OFFSET ## ROWS FETCH NEXT ## ROWS ONLY;
/*...*/
```

usign Serenity Application Template +  SQL Server 2008 R2.

I traced it using:

`<add key="Logging" value="{  File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0,  Level: 'Verbose' }" />`

I got my VS debug error on:

```
public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

```
And my exception thrown:

> Exception thrown: 'System.Data.SqlClient.SqlException' in Serenity.Data.dll

I know that OFFSET FETCH is a feature added to Sql Server 2012 and does not exist in Sql Server 2008, but how can i handle this? Thanks in advance!

**Comment by volkanceylan** [comment]
See guide topic about dialects

**Comment by alanlopcu** [comment]
Thank you! Serenity Developer Guide - Page 300 :smile:
