### ISSUE TITLE
PDF with SkickGrid Groupings

### ISSUE THREAD

**Issue by nscgllc** [volkanceylan/Serenity#1198]
This may be more of a question than an issue....apologize if this is a nob question or should be asked in another forum.

I have a slickgrid with groups.  When I use the PdfExportHelper it will not print the groupings or totals calculated and displayed within the grid.  Is there something you have to do to get the PdfExportHelper to print the groupings?  The pdf does contain all the rows, but no groupings or group totals.

If not, are there any recommendations from the community?  

I looked at the ReportHelper, but that seems to require a separate html page be created and programatically that would be difficult as the user may group on any of the grouping options on the grid.  If there is a way to pass the reporthelper the grid raw html that might work?

**Comment by volkanceylan** [comment]
Sorry but grouping and totals are not supported for PDF/Excel export. We are using JsPdfAutoTable, you might come with something using its docs, and slickgrid ones, but its not easy one.

**Comment by nscgllc** [comment]
@volkanceylan thanks for the quick response.  Any chance or thought on using the ReportHelper with wkhtmltopdf to create a pdf with the groupings?  Assuming there is a way to pass the slickgrid html over to it.

**Comment by volkanceylan** [comment]
Might be a bit easier, but still need to disable scrolling both ways, find a way to pass filters, grouping, etc.
