### ISSUE TITLE
Close dialog box upon clicking a button on the grid in the dialog box

### ISSUE THREAD

**Issue by sasinallatech** [volkanceylan/Serenity#1199]
I have a Dialog (an Entity Dialog). In that dialog, I had hide all the tool bar button (not needed) and displaying a grid with check boxes. It also had a button labelled "Add Selected". Upon selecting the required rows and clicking the "Add Selected" button, I am doing a Bulk Action. Till this step everything works fine. But, how to close the dialog after the bulk action is done?

**Comment by Estrusco** [comment]
Try with this.Element.Closest(".ui-dialog").Find(".ui-dialog-titlebar-close").Click();

**Comment by Estrusco** [comment]
or better in typescript in lower case:

```ts
this.element.closest(".ui-dialog").find(".ui-dialog-titlebar-close").click();
```

**Comment by sasinallatech** [comment]
The Typescript change suggested works well!! Thanks much!!!
