### ISSUE TITLE
Q.Confirmed onNo event

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#120]
var confirmed = false;
Q.Confirm(" Panik Değerleri onaylamak istiyormusunuz ?", onYes: delegate  {  confirmed = true; });
DetailService.SetTechnician( new ClaimRequest
    {
        ClaimId = options.ClaimId,
        TubeId = (int?) _grup.Value.ConvertToId(),
         Panic =  confirmed
    }, delegate { Refresh(); });

burada  confirmed=false oluyor.  seçemi beklemem gerekiyor. yardımcı olur musun?

**Comment by volkanceylan** [comment]
Q.Confirm async bir işlem dolayısıyla alt satırında birşey yapmamalısınız.

Yapacağınız işlemi ilk onYes delegate i içinde yapmalısınız.

onNo için bir parametre daha alıyor, new ConfirmOptions { onNo: () => { } } gibi oraya yazmanız gerekiyor.

**Comment by oaltay** [comment]
Q.Confirm(Q.Text("Panik Deger mevcut... Panik Değerleri onaylamak istiyor musunuz?"), () =>
                                {
                                    DetailService.SetTechnician(
                                        new ClaimRequest
                                        {
                                            ClaimId = options.ClaimId,
                                            TubeId = (int?) _grup.Value.ConvertToId(),
                                            panic = true
                                        }, delegate { Refresh(); });
                                },new ConfirmOptions { OnNo = () =>
                                {
                                    DetailService.SetTechnician(
                                        new ClaimRequest
                                        {
                                            ClaimId = options.ClaimId,
                                            TubeId = (int?) _grup.Value.ConvertToId(),
                                            panic = false
                                        }, delegate { Refresh(); });
                                } } );


şeklinde tamamladım. tşk.ler
