### ISSUE TITLE
LookupScripts access denied

### ISSUE THREAD

**Issue by zeezment** [volkanceylan/Serenity#1200]
Hi Volkan,

I've added permissions to my module classes and every time it tries loading data which is of type LookUpEditor, the user gets an access denied error. I thought specifying the Modify and Read Permissions at the top of the XYZRow, PageAuthorize in XYZPage and ServiceAuthorize in XYZEndpoint would handle all the Lookupscripts needed for a particular row..? How can I fix this?

`[ReadPermission(XYZModule.PermissionKeys.Key)]
    [ModifyPermission(XYZModule.PermissionKeys.Key)]
    [UpdatePermission(XYZModule.PermissionKeys.Key)]`
XYZRow

`[ConnectionKey("Default"), ServiceAuthorize(XYZModule.PermissionKeys.Key)]`
XYZEndpoint

` public class ServiceProvidersController : Controller
    {
        [PageAuthorize(XYZModule.PermissionKeys.Key)]
        public ActionResult Index()
        {
            return View("PathToIndex");
        }
    }`
XYZPage

Thanks,
Aziza

**Comment by volkanceylan** [comment]
Your lookups uses ReadPermission of whatever row they are placed on. If user doesn't have that permission, he'll get the error.

**Comment by zeezment** [comment]
I have the ReadPermission implemented in the row that have the lookups in and it still gives access denied, it only ends up working if i create individual permission keys for each lookup entity and grant read permission to the user for that specific lookup

**Comment by volkanceylan** [comment]
It's not possible sorry.

**Comment by volkanceylan** [comment]
Where is your lookup definition by the way.
