### ISSUE TITLE
PDF export not work with 100.000 records

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#1201]
Hi again Volkan,

I added 100.000 records to the Customers table on "Northwind", and it failed trying to export them to PDF but it works on excel.  

When including 10, 20 or 100 records it works flawlessly tho.

I added some snapshots of the processes for you to check.

Thank you!

![001](https://cloud.githubusercontent.com/assets/11929923/18592938/347559c8-7c07-11e6-8559-998f28ee7b7e.PNG)
![002](https://cloud.githubusercontent.com/assets/11929923/18592939/3476fbe8-7c07-11e6-8be5-6a6d2291ac1c.PNG)

**Comment by volkanceylan** [comment]
Sorry but there is nothing i can do about that. It's jspdf.
