### ISSUE TITLE
QuickFilter Event

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1202]
I want to know, which event i have to capture for following situation:
user selects item from Quickfilter and Grid gets populated with data. Now user clicks on x in a quickfilter.
which removes selected text from QuickFilter, but grid data does not change.
![untitled1](https://cloud.githubusercontent.com/assets/19570368/18607391/c43c2870-7ce8-11e6-82ec-d838c82b02c2.png)
regards
Shailesh

**Comment by volkanceylan** [comment]
It refreshes on clear, check if you have a script error.

**Comment by shaileshbc** [comment]
when x is clicked, it doesn't refreshes grid, neither i am getting any script error.
Text of Cascaded lookup editor gets cleared.
regards
Shailesh

**Comment by volkanceylan** [comment]
It works in all Serene pages, so sorry don't know what is problem of yours.
