### ISSUE TITLE
How to inject dialog to a page

### ISSUE THREAD

**Issue by fzhenmei** [volkanceylan/Serenity#1203]
Hi,

I try to inject a dialog into a page, then dialog works like a panel on "\Modules\Membership\Account\SignUp\SignUpPanel.ts", because Panel will ignore CategoryAttribute witch define on Form c sharp class, I need rend those Categories. So i crate a "Panel" class inherit from `Serenity.EntityDialog`  like this:
```
    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.panel(true)
    export class CustomerRequirementPanel extends Serenity.EntityDialog<CustomerRequirementRow, any> {
    //...
}
```
Call it from page, then I got a dialog look but no need to click a button to show a pop up dialog, everything looks fine, but I found a problem: the elements of **CustomerRequirementPanel ** are append to **body** element, so it will always on the bottom of **body**, but most of the time I need it display in the middle of page.

![image](https://cloud.githubusercontent.com/assets/167262/18608129/3f1f31a2-7d13-11e6-9912-e30eef6d77b4.png)

I dig into some Serenity code, and found this:
```
 function TemplatedDialog(options) {
            _super.call(this, Q.newBodyDiv(), options);
```
file: ..\Scripts\serenity\Serenity.CoreLib.js
Look it I can not pass a **container** element to inject our **CustomerRequirementPanel **...

My question is how to inject **CustomerRequirementPanel ** to a specified element, for example a DIV ?

Thanks.

**Comment by volkanceylan** [comment]
Append its element dlg.element to anywhere.
