### ISSUE TITLE
toastr positioning

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1204]
May be a little bug here

`Q.notifyError('blablabla', 'title', { positionClass: "toast-top-right"});`

the toastr does not positioned correctly (it is showing always full-width) but 

`toastr.error('blablalba', { positionClass: "toast-top-right"});`

this works fine.

**Comment by volkanceylan** [comment]
Q.notify functions doesn't support those position classes. They are specialized to position them on a dialog when a dialog is active. So if you need such positions, use toastr itself, you don't need Q.notify.
