### ISSUE TITLE
DateTime QuickFilter

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1205]
Is Their is any DateTimeQuickfilter available for DateTime field.
It shows Quickfilter for date only and not for time.
Similar to issue #1074 .
![datetimequickfilter](https://cloud.githubusercontent.com/assets/19570368/18629147/58784d7c-7e81-11e6-9ef3-51c20df35a3f.png)

**Comment by adhikamafran** [comment]
try add atribute DateTimeEditor to your field in xyzRow.cs.

**Comment by shaileshbc** [comment]
Already added and that's why time editor is shown in Dialog.
regards
Shailesh

**Comment by edson** [comment]
Try adding datetimeeditor as quickfilter on xyzgrid.ts... Instead of using the quickfilter declarative... 

Regards

**Comment by volkanceylan** [comment]
There is no DateTime filtering option yet.
