### ISSUE TITLE
Not display grid (table) in browser

### ISSUE THREAD

**Issue by mauribo** [volkanceylan/Serenity#1206]
Dear all,
when i compile the project i can see the name of the table in the menu but not display the grid,

thanks for the cooperation,

Maurizio

**Comment by edson** [comment]
You need to give more info If you want help... Code... Error on browser console, etc..

**Comment by mauribo** [comment]
The browser is microsoft edge, but the problem is also in firefox. Follows the screenshot that i find in my project. I use VS 2015 community. The Northwind pages are shown correctly.

![screen_buza](https://cloud.githubusercontent.com/assets/14540516/18642316/7d4aaafe-7ea0-11e6-9b15-e847fee3c69b.jpg)

**Comment by Estrusco** [comment]
See for error in browser console. Also see the request and the response of the List service.

**Comment by mauribo** [comment]
the browser error is:

![browser_error](https://cloud.githubusercontent.com/assets/14540516/18645240/b85b9c78-7eac-11e6-8f6a-93ab9cca5cc1.jpg)

Macroaree is the table in wich has been generated the code

**Comment by Serenis** [comment]
Don't update jQuery, period.
