### ISSUE TITLE
MasterDetail/ GridEditorbase : issue in Chrome browser

### ISSUE THREAD

**Issue by manivishnupriya** [volkanceylan/Serenity#1207]
![image](https://cloud.githubusercontent.com/assets/20909626/18641681/af38295e-7e6b-11e6-9f68-d395727d15e8.png)

In Chrome the effective date is not loading ONload, When i update any item in the detail list, then it shows the effective dates for all rows. 

In IE edge, it is working fine.
![image](https://cloud.githubusercontent.com/assets/20909626/18641803/318c50ec-7e6c-11e6-9008-7f9d8f4b88fa.png)

**Comment by manivishnupriya** [comment]
Recently i changed this

**Comment by manivishnupriya** [comment]
Recently i changed this JSEngine code. Is it because of this code change, the masterdetail not working?
private MsieJsEngine SetupJsEngine()
    {
       var jsEngine = new MsieJsEngine(new JsEngineSettings { EngineMode = JsEngineMode.ChakraIeJsRt, UseEcmaScript5Polyfill = true, UseJson2Library = true });

        try
        {
            var json2 = File.ReadAllText(projectDir + @"tools\JsEngine\json2.min.js");
            jsEngine.Evaluate(json2);

**Comment by volkanceylan** [comment]
It has no relation. You didnt set includecolumns in masterdetailrelation.

**Comment by manivishnupriya** [comment]
But i have includecolumns attribute in masterdetailrelation. That why it shows the effective date in IE.  i tried transforming templates, rebuilding, clean solution, cleaning browser cache, restarting the visual studio. 
After restarting the computer the next day, the issue is resolved automatically. So It might be because of some other reason which i couldnt figure it out

**Comment by manivishnupriya** [comment]
Thanks for your support

**Comment by manivishnupriya** [comment]
![image](https://cloud.githubusercontent.com/assets/20909626/18720939/0876b35a-7ffc-11e6-9a9e-7bc2ddad5b2d.png)
There is  a dot next to checkboX column in all the pages. The issue is only in Edge browser. In chrome it is working perfectly fine.

private rowSelection: Serenity.GridRowSelectionMixin;
 protected createSlickGrid() {
            var grid = super.createSlickGrid();

            // need to register this plugin for grouping or you'll have errors
            grid.registerPlugin(new Slick.Data.GroupItemMetadataProvider());

            return grid;
        }
        protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
        }
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));
            return columns;
        }        
I didnt change any code. It is same as in the samples.
Has anyone seen this kind of issue? Please help me resolving this

**Comment by volkanceylan** [comment]
Do you have same dot in samples?

**Comment by manivishnupriya** [comment]
Yes. 
![image](https://cloud.githubusercontent.com/assets/20909626/18748000/4e5b1c88-809e-11e6-9f97-87bbd7fdfeab.png)

**Comment by volkanceylan** [comment]
I can't reproduce this. What is content of that dot in inspector?

**Comment by manivishnupriya** [comment]
![image](https://cloud.githubusercontent.com/assets/20909626/19040621/e14ed590-8952-11e6-9988-022893bc692f.png)

When i change the checkbox style attribute height same as the row height, the dot disappeared. 
![image](https://cloud.githubusercontent.com/assets/20909626/19040699/354cac12-8953-11e6-888a-f2d0ea171852.png)

But is this the correct solution for this problem?

**Comment by manivishnupriya** [comment]
![image](https://cloud.githubusercontent.com/assets/20909626/19041297/7f8a60c4-8955-11e6-9de5-2b2297c1a437.png)

By default right margin for check box is set as 3px.
when I set right margin as 0px for the checkbox column, then the dot disappears

**Comment by volkanceylan** [comment]
Ok, i could see that in IE11. That thing is caused by text-overflow: ellipsis. Somehow, IE thinks there is a text overflow in checkbox column. If you make `.select-item { width: 14px; }` it disappears. You can do this workaround for now, and i'll probably increase default checkbox column width by 1px later.

**Comment by manivishnupriya** [comment]
Thanks for your support. :)
