### ISSUE TITLE
Negative value

### ISSUE THREAD

**Issue by rsbatacjr** [volkanceylan/Serenity#1208]
Hi, serenity. It's been a while since my last post here. I was assigned to look at other project, now im back with serenity based project may I ask if someone already had a requirement with negative amount input.

I cannot find a way to override minvalue of decimal type on form, please help.

**Comment by silvia-king** [comment]
How to added AllowNegatives property to IntegerEditor and DecimalEditor

**Comment by silvia-king** [comment]
@Estrusco  Thank you very much. you've been most helpful.
