### ISSUE TITLE
ToastrOptions duration after saving dialog

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1209]
With regards to Serene, I just want to ask if this is the correct way of customizing the ToastrOptions for a notifyInfo?

this is inside the constructor for the Dialog.

```
this.saveAndCloseButton.bind('click', function (e) {
            Q.notifySuccess("Your changes had been saved!", "Update",{ showDuration:5000 } );
});  
```

`showDuration`  is not working, it still disappears quickly in a second..

**Comment by marcobisio** [comment]
You should use the "timeOut" parameter instead of the "showDuration" one.

**Comment by volkanceylan** [comment]
@marcobisio is right.

**Comment by john20xdoe** [comment]
Thanks guys. 
So i made it into:
`Q.notifySuccess("Your changes had been saved!", "Update",{ showDuration:5000 } );`

the green notification it is still showing in less than a second. I'll play around and see how it goes.
