### ISSUE TITLE
WorkFlow Approval

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#121]
Sir,
Please advice me how can i implement this using serenity appropriately.

Suppose, A requester post a requisition then requester's line manager (which will be set for this requester) checked, than somebody will verify  and so on. according to workflow settings for this transaction.

When sequester's line manager logged in to the system he will notified that a requisition is waiting for checking. He can either approve it or reject. If he approve than next approval authority will get notification and so on.

If you please add workflow (Checked, Verified, Approve etc.) sample to serene template or tutorial, it will be helpful for all.

**Comment by volkanceylan** [comment]
You should design this yourself. I can't add a sample to Serenity for all possible scenarios out there.

**Comment by dfaruque** [comment]
Can you please give some hints or suggestion?

**Comment by volkanceylan** [comment]
As i said, you should design it at database level yourself first. I don't have such a workflow sample. After you prepare it, generate tables etc, ask questions specific to Serenity that you couldn't handle.

**Comment by mvmshakkir** [comment]
Hello, did you implement it? I need help
