### ISSUE TITLE
Using additional TS libs in Serenity

### ISSUE THREAD

**Issue by blojayble** [volkanceylan/Serenity#1211]
Hi,
I wanted to use LINQ lib for typescript, however using imports makes my file an external module, so I can't see any of the server typings in my code anymore.

How should I handle it?

**Comment by volkanceylan** [comment]
What is imports, what is external module. You just add DefinitelyTyped typings and use.

**Comment by blojayble** [comment]
But this lib is not written in js, and used with typings - it's entirely in ts. 
Just adding the files does not do anything to me. As far as my little knowledge of TS goes, if your file begins with an import, it becomes an external module - so I can't see any of my other type definitions unless I import all of them as well. 

Am I missing something?

**Comment by volkanceylan** [comment]
I dont know what is that lib, but i explained how you use libs. This is not typescript support forum sorry.
