### ISSUE TITLE
Permissions for Lookup access

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1212]
In my solution sometimes I'm including Lookup from diferent modules. For instance, if I have a Module for Movies and a Module for Person then in Movies I use the Person Entity for Lookup CastCrew.
If I have two Roles that manage Movies and Persons separately the problem becomes that when I allow Read Permission for Person Entity the Person Module shows up in the Menu navigator.

What should be the best practice?
Add another type of permission?
Add a second Person Lookup specific for the Movie Module (Redundant)?
Change the navigation menu to check for aditional permissions?

Thanks!

**Comment by volkanceylan** [comment]
Set lookups permission to empty string or ? for logged in users.

Or if lookups has sensitive info, need to define a separate permission.

**Comment by rgilsimoes** [comment]
Like this?
PersonRow.cs
        ....           
        [LookupScript("Persons.Person"), RequiredPermission("?")]
        ....

MovieRow.cs

        ...
        [DisplayName("Movies"), Column("IDMovie"), ForeignKey("[dbo].[Movies]"...
        [LookupEditor("Persons.Person")]
        public Int32? IdPerson
        {


This does not work... :-(

**Comment by volkanceylan** [comment]
LookupScript("Persons.Person", Permission = "?")
