### ISSUE TITLE
Display a grid in a dialog

### ISSUE THREAD

**Issue by riveri** [volkanceylan/Serenity#1214]
Hi,

I have a grid (called WorkstationView) with a custom SlickColumn (behaves like a button) and I have added the OnClick behaviour (everything is OK so far).

I need to display a dialog with a grid inside (called WorkstationHistory) when the SlickColumn button is clicked, but I can't find a way to display it.

Thanks and this tool is awesome.

**Comment by volkanceylan** [comment]
What about new SomeDialog().dialogOpen()

**Comment by riveri** [comment]
Hi, what kind of Dialog can I use to host the Grid?

**Comment by edson** [comment]
The usual Serenity dialog way... Just take a look from Serenity basic examples CustomLinkGrids and in this case, there is also a grid displayed in Roles... Edit permissions... Take a look at RoleDialog.ts and RolePermissionDialog.ts... Hope it helps.

Regards

**Comment by edson** [comment]
Oh sorry. My mistake. It's not actually a grid per se... but you get the idea...

**Comment by riveri** [comment]
Thanks, Great 👍
