### ISSUE TITLE
Are columns that are unmapped to DB not applicable for QuickSearch?

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1216]
I have an X entity with a Remarks column that is unmapped to db.

In XGrid.ts, in `getItemsCssClass()`, i populate the item's Remarks column with some browser-side generated validation message (e.g."Missing Code"). It appears in the grid successfully.

However, eventhough Remarks has a [QuickSearch] attribute in the XRow, it is not found when I enter the message in the search field.

Did I miss something? Or is QuickSearch allowed only for DB-mapped columns?

**Comment by volkanceylan** [comment]
Quick search only works on db columns.

**Comment by mantiklas** [comment]
![remarks](https://cloud.githubusercontent.com/assets/21164515/18771973/e07e1b88-8175-11e6-9f0e-ebcb82fab7a2.PNG)
Hi @volkanceylan , this is my scenario, I applied the Conditional Formatting of Basic Samples on my solution, and added column name remarks(string), Every condition  , I append validation on the string remarks, (e.g.  Missing Cluster, Wrong mapping) .. My question is , I want to filter the row that has remarks,     by using search.. or by applying order or sorting backend, but How? Thank you in anticipation..

**Comment by volkanceylan** [comment]
You need to add an boolean expression field that matches "has remarks". Search doesn't work on client side text.

**Comment by mantiklas** [comment]
Thanks @volkanceylan  but my remarks is appending under getItemsCssClass(), Is it where also I am gonna update the Boolean "Has Remarks"?  Or you could give me separate Function in updating the boolean... BTW the data that I am updating is  consists of more than 4k line items...

**Comment by volkanceylan** [comment]
I think you had your answer already

**Comment by mantiklas** [comment]
Thanks @volkanceylan  and @john20xdoe.. My question is now answered..

**Comment by Shraddha996** [comment]
> Quick search only works on db columns.
@volkanceylan 
then why it does not work for details DB columns.
