### ISSUE TITLE
Error when executing a page withing a new module

### ISSUE THREAD

**Issue by jadsouza** [volkanceylan/Serenity#1217]
0x800a01bd - JavaScript runtime error: Object doesn't support this action

**Comment by volkanceylan** [comment]
Let me debug it

**Comment by jadsouza** [comment]
Hi
I see you have closed this ticket. Is there a solution to the issue?

**Comment by volkanceylan** [comment]
Really, how do you expect a solution with such an error report?

I get "object reference is null" exception, now resolve my problem, then i'll help resolve yours.

**Comment by jadsouza** [comment]
Well you dont have to be rude.  I just asked if i could get some help. You are an expert in this field. If i did not provide  enough information  you could have just asked.  I do understand you are busy but being rude that is not the way.


Though  your software is nice, I have come to a conclusion is either you had a bad day or you are just an arrongant and uncultured technical person.


I just made a mistake by downloading your software. Dont take me wrong. I love your software. But if i have to deal with such arrogance,  it is not worth it. There are plenty of better software out there with less arrogance


Get Outlook for Android






On Wed, Sep 21, 2016 at 10:40 PM +1000, "Volkan Ceylan" <notifications@github.com> wrote:





Really, how do you expect a solution with such an error report?

I get "object reference is null" exception, now resolve my problem, then i'll help resolve yours.

**Comment by evelix** [comment]
@jadsouza: Sorry I can't follow you and I think you are completely off your track calling someone "arrogant" and rude, just because he exactly pointed out what the problem is.

The problem is your problem description (and maybe your level of knowledge).
I mean you did not wrote down exactly what you did, what kind of module you're talkin about or what dialog, or when the error occurs and yes, maybe the line where the error is thrown would be helpful too.

There is no one on this planet, including dead ones like Einstein or Steve Jobs that is able to help you with that problem.

**Comment by volkanceylan** [comment]
First of all, i really don't care what you think, so this is not an answer to you, but to community that might be reading this.

Serenity is not a commercial product, noone here is my client. It's a kind of present, formed from years of hard work, and anyone who don't like the present or support offered is free to look elsewhere.

It's something i develop and try to support in my precious and limited "spare time", which i am stealing from my family and friends. I have no obligacy to waste my time on someone who doesn't even mind doing his homework, before asking for help.

Serenity is a developer tool which is used by developers. They have to be different then the end-users, who i'd tolerate to report with "it doesn't work".

If you lack the fundamentals, either get educated by reading a book, attending a course etc, or try your chance in another area before its too late as you might not have a feature in programming.
