### ISSUE TITLE
Add custom icon-button in the top right toolbar of a dialog

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1218]
Dear @volkanceylan,
I'm trying to add a custom button to a dialog
![image](https://cloud.githubusercontent.com/assets/17425690/18710850/865cc0ec-8007-11e6-8839-b5264cf173b7.png)
here to the left of the maximize button.
So I have added a new DialogExtensions method in a separate ts file:

    namespace Serenity.DialogExtensions {
       export function dialogLinkable(dialog: JQuery): JQuery {
           (dialog as any).dialogExtend({ icons: { linktest: "ui-icon-link" } });
           return dialog;
       }
    }

then I tried to override the initDialog method of a dialog:

    protected initDialog(): void {
       super.initDialog();
       Serenity.DialogExtensions.dialogLinkable(this.element);
    }

and finally I've added some css:

    .ui-dialog-titlebar-buttonpane .ui-icon-link {
      background-image: url(../serenity/images/chain-small.png) !important;
      background-position: center center;
    }

but nothing happen although the dialogLinkable function is properly called.

Any idea on what I'm doing wrong?
Thank you very much
Bye

**Comment by volkanceylan** [comment]
I'm not sure what is dialogExtend but why don't you directly append an A element to dialog title bar, and position it with absolute positioning?

**Comment by marcobisio** [comment]
I'm trying to "mimic" the dialog maximizable behaviour so I can possibly define a new "MyAttribute" like the already existing "MaximizableAttribute" (MaximizableAttribute.cs in Serenity sources).
The DialogExtensions.cs class in fact contains the DialogMaximizable extension method (Serenity.Script.UI -> Widget):

    public static jQueryObject DialogMaximizable(this jQueryObject dialog)
    {
        dialog.As<dynamic>().dialogExtend(new
        {
            closable = true,
            maximizable = true,
            dblclick = "maximize",
            icons = new
            {
                maximize = "ui-icon-maximize-window"
            }
        });
    
        return dialog;
    }

So the code that I have posted before it's a clumsy attempt to replicate such behaviour, avoid touching the Serenity sources.

The dialogExtend method I think that is the one defined in the jquery.dialogextendQ.js file (Serenity.Web -> Assets -> Scripts).

I was thinking to a solution like that because is more flexible, but if you think that is not viable (or anyway too complex) I'll try to append an A element like you suggest.

**Comment by volkanceylan** [comment]
Sorry, i forgot about that plugin. It's not a quality one and i had to modify it several time to make it work. But i had to use it for quick maximize / restore functionality. I'll probably get rid of that eventually, so you shouldn't depend on that one.

**Comment by marcobisio** [comment]
Thanks for the explanation@volkanceylan...in that case I'll try the "append element" approach :-)

Thank you very much
Bye
