### ISSUE TITLE
Finding tab and hiding based on permission on TemplatedDialog

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1219]
For my dashboard I have a 4 tabbed view.   I'd like to hide tabs based on permission.   But I'm not sure how to access the tab to hide it.
I'd appreciate any help.   Thank you!

Update, here's the solution: 

    <div class="row">
    <section class="col-lg-12 connectedSortable">
        <div class="nav-tabs-custom">
            <ul class="nav nav-pills nav-justified">
            @Html.Raw((Serenity.Authorization.HasPermission("Customer:Customer:Modify")) ? "<li class=''><a href='#_TabCustomer' data-toggle='tab' id='mnuReg'>Event Customers</a></li>" : string.Empty)
            @Html.Raw((Serenity.Authorization.HasPermission("Loan:Loan:Modify")) ? "<li class=''><a href='#_TabLoan' data-toggle='tab' id='mnuLoans'>Event Loans</a></li>" : string.Empty)
            @Html.Raw((Serenity.Authorization.HasPermission("Repair:Repair:Modify")) ? "<li class=''><a href='#_TabRepair' data-toggle='tab' id='mnuRepairs'>Event Repairs</a></li>" : string.Empty)
            @Html.Raw((Serenity.Authorization.HasPermission("Event:EventProduct:Modify")) ? "<li class=''><a href='#_TabInventory' data-toggle='tab' id='mnuProd'>Event Inventory</a></li>" : string.Empty)
            </ul>
            <div class="tab-content">
                <div class="chart tab-pane " style="position: relative; height: 600px;" id="_TabRepair" role="tabpanel">a</div>
                <div class="chart tab-pane " style="position: relative; height: 600px;" id="_TabLoan" role="tabpanel">b</div>
                <div class="chart tab-pane " style="position: relative; height: 600px;" id="_TabInventory" role="tabpanel">c</div>
                <div class="chart tab-pane active" style="position: relative; height: 300px;" id="_TabCustomer" role="tabpanel">d</div>
            </div>
        </div>
    </section>
</div>

    <script type="text/javascript">
    jQuery(function () {
        eventCustGrid = new EventManager.Customer.RegistrantGrid($('#_TabCustomer'), {
        });

        Q.initFullHeightGridPage($('#_TabCustomer'));
    });
    lastPanelShown = "";

    $("#mnuRepairs").off("click");
    $("#mnuRepairs").on("click", function () {
        var curPanel = '#_TabRepair';
        try {
            var eventRepairGrid = new EventManager.Repair.ActiveEventRepairGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;
    })
    $("#mnuLoans").off("click");
    $("#mnuLoans").on("click", function () {
        var curPanel = '#_TabLoan';
        try {
            var eventLoanGrid = new EventManager.Loan.ActiveEventLoanGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;

    })
    $("#mnuProd").off("click");
    $("#mnuProd").on("click", function () {
        var curPanel = '#_TabInventory';
        try {
            var eventProdGrid = new EventManager.Event.ActiveEventProductGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;
    })
    $("#mnuReg").off("click");
    $("#mnuReg").on("click", function () {
        var curPanel = '#_TabCustomer';
        try {
            var eventCustGrid = new EventManager.Customer.RegistrantGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;
    });
</script>

**Comment by volkanceylan** [comment]
I'm finding orders tab in new record mode and disabling it in CustomerDialog.ts. It should probably work with toggling too.

**Comment by mayatstafford** [comment]
I see this 

    loadEntity(entity: CustomerRow) {
            super.loadEntity(entity);

            Serenity.TabsExtensions.setDisabled(this.tabs, 'Orders', this.isNewOrDeleted());

            this.ordersGrid.customerID = entity.CustomerID;
        }


But how do you come up with the name "Orders" ?

    <div id="~_Tabs" class="s-DialogContent">
    <ul>
        <li><a href="#~_TabInfo"><span>{{text:"Db.Northwind.Customer.EntitySingular"}}</span></a></li>
        <li><a href="#~_TabNotes"><span>{{text:"Db.Northwind.Note.EntityPlural"}}</span></a></li>
        <li><a href="#~_TabOrders"><span>{{text:"Db.Northwind.Order.EntityPlural"}}</span></a></li>
    </ul>
    <div id="~_TabInfo" class="tab-pane s-TabInfo">
        <div id="~_Toolbar" class="s-DialogToolbar">
        </div>
        <div class="s-Form">
            <form id="~_Form" action="">
                <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                    <div id="~_PropertyGrid"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>
    <div id="~_TabNotes" class="tab-pane s-TabNotes">
    </div>
    <div id="~_TabOrders" class="tab-pane s-TabOrders">
        <div id="~_OrdersGrid">
        </div>
    </div>
</div>

**Comment by volkanceylan** [comment]
href="#~_TabOrders"

**Comment by mayatstafford** [comment]
So in order for this to work the outer dive that holds the grid div needs to be named in this format?
~_TabYOURNAMEHERE

**Comment by volkanceylan** [comment]
Yes

**Comment by mayatstafford** [comment]
Where in the TemplatedDialog would I put the code below?   I tried constructor and initDialog but neither worked and when I debugged it doesn't even look like they are being hit..

              if (!Authorization.hasPermission("Loan:Loan:View")) {
                Serenity.TabsExtensions.setDisabled(this.tabs, 'Loan', true);
            }

**Comment by volkanceylan** [comment]
Constructor. How to image constructor not hit??

**Comment by mayatstafford** [comment]
Ok so I renamed the grids and divs and still no good.  I'm at a loss.   What am I doing wrong?

DashboardIndex.cshtml:
    @{ ViewData["Title"] = Serenity.LocalText.Get("Db.Event.Event.EntityPlural");}
    
    <div class="row">
    <section class="col-lg-12 connectedSortable">
        <div class="nav-tabs-custom">
            
            <ul class="nav nav-pills nav-justified">
                <li class="active"><a href="#_TabCustomer" data-toggle="tab" id="mnuReg">Event Customers</a></li>
                <li class=""><a href="#_TabLoan" data-toggle="tab" id="mnuLoans">Event Loans</a></li>
                <li class=""><a href="#_TabRepair" data-toggle="tab" id="mnuRepairs">Event Repairs</a></li>
                <li class=""><a href="#_TabInventory" data-toggle="tab" id="mnuProd">Event Inventory</a></li>
            </ul>
            <div class="tab-content">
                <div class="chart tab-pane " style="position: relative; height: 600px;" id="_TabRepair" role="tabpanel">a</div>
                <div class="chart tab-pane " style="position: relative; height: 600px;" id="_TabLoan" role="tabpanel">b</div>
                <div class="chart tab-pane " style="position: relative; height: 600px;" id="_TabInventory" role="tabpanel">c</div>
                <div class="chart tab-pane active" style="position: relative; height: 300px;" id="_TabCustomer" role="tabpanel">d</div>
            </div>
        </div>
    </section></div>

    <script type="text/javascript">
    jQuery(function () {
        eventCustGrid = new NPSEventManager.Customer.RegistrantGrid($('#_TabCustomer'), {
        });

        Q.initFullHeightGridPage($('#_TabCustomer'));

    });
    lastPanelShown = "";


    $("#mnuRepairs").off("click");
    $("#mnuRepairs").on("click", function () {
        var curPanel = '#_TabRepair';
        try {
            var eventRepairGrid = new NPSEventManager.Repair.ActiveEventRepairGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;
    })
    $("#mnuLoans").off("click");
    $("#mnuLoans").on("click", function () {
        var curPanel = '#_TabLoan';
        try {
            var eventLoanGrid = new NPSEventManager.Loan.ActiveEventLoanGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;

    })
    $("#mnuProd").off("click");
    $("#mnuProd").on("click", function () {
        var curPanel = '#_TabInventory';
        try {
            var eventProdGrid = new NPSEventManager.Event.ActiveEventProductGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;
    })
    $("#mnuReg").off("click");
    $("#mnuReg").on("click", function () {
        var curPanel = '#_TabCustomer';
        try {
            var eventCustGrid = new NPSEventManager.Customer.RegistrantGrid($(curPanel), {
            });
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        catch (ex) {
            $(curPanel).show();
            Q.initFullHeightGridPage($(curPanel));
        }
        if (lastPanelShown != "") {
            $(lastPanelShown).hide();
        }
        lastPanelShown = curPanel;
    });
</script>


DashboardDialog.ts
    
    namespace NPSEventManager.Dashboard {
    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.resizable()
    @Serenity.Decorators.maximizable()
    export class DashboardDialog extends Serenity.TemplatedDialog<any> {
        constructor() {
            super();
            if (!Authorization.hasPermission("Loan:Loan:View")) {
                Serenity.TabsExtensions.setDisabled(this.tabs, 'Loan', true);
            } else {
                Serenity.TabsExtensions.setDisabled(this.tabs, 'Repair', true);
            }         
        }     
    }
}
