### ISSUE TITLE
Field level permissions

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1220]
How to set field level permissions in form/dialog?

**Comment by volkanceylan** [comment]
There are no field level permissions.

**Comment by rgilsimoes** [comment]
Based on Issue https://github.com/volkanceylan/Serenity/issues/1221 I wrote this as a possible workaround:

On XYZDialog.ts:

`afterLoadEntity() {
            super.afterLoadEntity();

            if (!BaseNamespace.Authorization.hasPermission("Admin:UserType:Boss")) {
                this.form.UserId.getGridField().toggle(false);
            }
        }
`

**Comment by VictorTomaili** [comment]
Also you need check permission before add or update entity repostory. If has permission you can clear field assigments.  
Your solution will be modified on user browser.

**Comment by rgilsimoes** [comment]
@VictorTomaili Yes, for security precautions.
