### ISSUE TITLE
Hide/show fields based on condition

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1221]
I want to show or hide some form fields based on a condition from a master/detail relation.
I've searched for some enable() or hide() methods in "form.FieldName" bot could not get it.

**Comment by volkanceylan** [comment]
Have a look around in samples.

**Comment by Estrusco** [comment]
In tour xyzDialog 

```ts
this.form.YourField.element.hide();
```

**Comment by rgilsimoes** [comment]
@Estrusco thanks for the tip. But this only hides the Input and in case of a lookupeditor the real input is already hidden and the select remains.

Sinde we cannot set permissions on fields I wanted to hide the field in case the user has not a specific permission.

I was thinking about changing the visibility of <div class="field MyField">? is this ok?

**Comment by volkanceylan** [comment]
this.form.YourField.getGridField().toggle(false)

**Comment by rgilsimoes** [comment]
Thanks again @volkanceylan

**Comment by abelal83** [comment]
@rgilsimoes pls could you kindly share your code on how toggled fields based on permission? It is something that I'm also trying to accomplish.

Many thanks.

**Comment by rgilsimoes** [comment]
Sure:

In XYZDialog.ts you add this method:

```c#
       afterLoadEntity() {
            super.afterLoadEntity();

            if (!SIINv2.Authorization.hasPermission("Admin:TipoUser:Nucleo")) {
                this.form.UserId.getGridField().toggle(false);
                this.form.IdEntidade.getGridField().toggle(false);
            }
        }
```

To register the "Admin:TipoUser:Nucleo" permission you have to place this:

`[assembly: Serenity.ComponentModel.RegisterPermissionKey("Admin:TipoUser:Nucleo")]`

Anywhere in our code.

**Comment by abelal83** [comment]
Thank you for this.

I’ve amended as such..

dialog
        afterLoadEntity() {
            super.afterLoadEntity();
            if (serene.Authorization.hasPermission("ActiveDirectoryDomain\team-deskside-ldn")) {
                this.form.Permanent.getGridField().toggle(false);
                this.form.DateRemove.getGridField().toggle(false);
            }
        }

row
[assembly: Serenity.ComponentModel.RegisterPermissionKey("ActiveDirectoryDomain\team-deskside-ldn")]


This works in the sense that both fields do not appear even for users in team-deskside-ldn Active Directory group.

I can only assume serenity can’t see the AD group membership for users in a dialog via typescript because AD groups do work via row.cs as below

    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("desksidedb"), DisplayName("RebootWeekendExclude"), InstanceName("RebootWeekendExclude"), TwoLevelCached]
    [ModifyPermission(@"NT AUTHORITY\Authenticated Users, ActiveDirectoryDomain\team-deskside-ldn")]
    [DeletePermission(@"ActiveDirectoryDomain \test-group-ldn")]

    public sealed class RebootWeekendExcludeRow : Row, IIdRow, INameRow

any suggestions as our company mandates we use AD for permissions.

**Comment by rgilsimoes** [comment]
Sorry, I'm using Serene permissions :-(

**Comment by abelal83** [comment]
OK, there must be a way to hide GUI elements from server side as opposed to client side, in this way I can do it directly on the .cs file.

**Comment by rgilsimoes** [comment]
Well that is what I wanted in the first place with issue #1220. 
For now I can live with just hidding the fields.
