### ISSUE TITLE
Issue publishing app to Azure

### ISSUE THREAD

**Issue by zeekebud** [volkanceylan/Serenity#1222]
Hello,

I published the app as is from the VS gallery to Azure as a web app. I created a dacpac and moved the DBs and data to Azure as well. I can run the app locally just fine, connecting to the data in Azure but when I publish the web app, I get the following error. Thoughts?

Server Error in '/' Application.

Unexpected character encountered while parsing value: _. Path '', line 0, position 0.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: _. Path '', line 0, position 0.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by volkanceylan** [comment]
Sorry for late reply but this doesn't look like a Serenity error. Some JSON is tried to be parsed somewhere and that JSON has content "_" somehow. Check appSettings etc, if there is a malformed JSON.
