### ISSUE TITLE
Time Field Issue

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1223]
I have Time Field in database and corresponding to it, TimeSpanField in a ROW.
While quering database i have issue,
I am getting compilation error "Operator '==' cannot be applied to operands of type 'TimeSpanField' and 'TimeSpan'"
in case if i use  xyzRow.fields.timeSpanField == DateTime.Now.TimeOfDay.
if i change it 
xyzRow.fields.timefield == DateTime.Now.TimeOfDay.Ticks then compilation error goes off.
but while Running i am getting SqlException
"Operand type clash: time is incompatible with bigint"
so how to go about it.
regards
Shailesh

**Comment by Estrusco** [comment]
The values in your Row are in xyzRow.yourColumn (xyzRow.yourColumn.Value) not in xyzRow.fields.yourColumnField 

So you can try 

`xyzRow.timeSpan.Value == DateTime.Now.TimeOfDay`

**Comment by shaileshbc** [comment]
I am trying to query database to provide me List of Records based on filtering Time field.
hence i can't use values of Row.
for eg.
Following code gives compilation error
connection.List<row>( row.fields.timeSpanField == DateTime.Now.TimeofDay)
and following code gives runtime error 
connection.List<row>( row.fields.timeSpanField == DateTime.Now.TimeofDay.Ticks)
Thanks for your Quick reply.
regards
Shailesh

**Comment by Estrusco** [comment]
See [1133](https://github.com/volkanceylan/Serenity/issues/1133) and read the guide

In your case some 
`new Criteria(xyzRow.fields.timefield) == DateTime.Now.TimeOfDay `
in list request

**Comment by volkanceylan** [comment]
You may also try 

fld.SomeTime == new ValueCriteria(DateTime.Now.TimeOfDay)

A datetime without date portion should also work

**Comment by shaileshbc** [comment]
Volkan it works as per your suggestion.
Thanks
regards
Shailesh
