### ISSUE TITLE
Generated PDF File is empty

### ISSUE THREAD

**Issue by rsbatacjr** [volkanceylan/Serenity#1225]
Hi,

I tried adding footer from different html on my pdf report by adding this line of code on Customize function.

public void Customize(IHtmlToPdfOptions options)
        {
            // you may customize HTML to PDF converter (WKHTML) parameters here, e.g. 
            // options.MarginsAll = "2cm";
            options.FooterHtmlUrl = "/Report/Footer";
        }

without FooterHtmlUrl i can render the pdf, I can also browse /Report/Footer, but together it gives error.

Please help.

Thanks

![pdferror](https://cloud.githubusercontent.com/assets/16199919/18742672/2910ada4-80e8-11e6-8a1d-d36e7ed8e384.PNG)

**Comment by volkanceylan** [comment]
It must be an absolute url, e.g. http://something

**Comment by nsrtky** [comment]
i think this issue can be handled and show information to the developer also as information. to add something like this:
<div class="alert alert-info" role="alert">You must use an absolute url, e.g http://somthing.com</div>

**Comment by volkanceylan** [comment]
Cool, what about a pull request :)

**Comment by rsbatacjr** [comment]
Thanks, it worked. I just put the absolute url on web.config for now.
