### ISSUE TITLE
Validation Error Password

### ISSUE THREAD

**Issue by nsrtky** [volkanceylan/Serenity#1226]
Hi,
I have started a project with serenity and wanted to test it ı have faced the validation error its simple but should be solved. below ı am going to share its screensnapshot. in order to handle this problem at next version bug. 

![image](https://cloud.githubusercontent.com/assets/12385044/18756521/eab1101a-80f8-11e6-9a4e-15a542989cab.png)

**Comment by edson** [comment]
It´s not a bug..... You're running on debug mode... Just hit continue and it will show you a message...

**Comment by nsrtky** [comment]
yes thats right bu ı wanted to write it so if one person face this problem he or she will read this and informed about this issues. thank you for collobroate.
