### ISSUE TITLE
Can't find wkhtmltopdf.exe which is required for PDF generation.

### ISSUE THREAD

**Issue by nsrtky** [volkanceylan/Serenity#1227]
An exception of type 'System.InvalidOperationException' occurred in Serenity.Web.dll but was not handled in user code

Additional information: Can't find wkhtmltopdf.exe which is required for PDF generation.

Please download a stable version from http://wkhtmltopdf.org/downloads.html

![image](https://cloud.githubusercontent.com/assets/12385044/18757809/1b248308-80fe-11e6-89b3-2f82c6399000.png)

ı have faced above problem also will try to downoad the wkhtmltopdf.exe to solve this issues.

But what if ı wanted to use serenity at a shared hosting plan how can ı use this exe as ı now they are not allowing for 3rd party exe programs.

**Comment by volkanceylan** [comment]
So you can't use that feature.

**Comment by nsrtky** [comment]
just for idea, can we make this exe code as a module inside serenity if one want to add this feature he/she will be able to add it to project.in future?

**Comment by volkanceylan** [comment]
That is an external project written in C/QT. Not possible.
