### ISSUE TITLE
Cascade Editor Issue

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1228]
Hi, i have this relation:
![issue](https://cloud.githubusercontent.com/assets/22221262/18765523/af3895f2-80db-11e6-8f8a-c24684191891.png)

This is an stupid question from a man with poor english language knowledge. I need to select X equipment, then one component related to this X equipment and capture their IdEquipment and IdComponent from component_equipment in order to create new inspection.

My InspectionForm.cs code:

```
/*...*/
[LookupEditor(typeof(Entities.EquipmentRow))]
public Int32 IdEquipment { get; set; }
[LookupEditor(typeof(Entities.ComponentEquipmentRow), CascadeFrom = "IdEquipment", CascadeField = "IdEquipment")]
public Int32 IdComponent { get; set; }
/*...*/
```
I've  changed my INameRow.NameField in ComponentEquipmentRow in order to show my filtered component name in dropdown, like this:

```
StringField INameRow.NameField
        {
            //get { return Fields.Description; }
            get { return Fields.IdComponentName; }
        }
```

My InspectionRow.cs code:

```
/*...*/
[DisplayName("Id Equipment"), Column("id_equipment"), NotNull, DefaultValue(0), ForeignKey("[dbo].[component_equipment]", "id_equipment"), LeftJoin("jIdEquipment"), TextualField("IdEquipmentName")]
public Int32? IdEquipment
        {
            get { return Fields.IdEquipment[this]; }
            set { Fields.IdEquipment[this] = value; }
        }

[DisplayName("Id Component"), Column("id_component"), NotNull, DefaultValue(0), ForeignKey("[dbo].[component_equipment]", "id_component"), LeftJoin("jIdComponent"), TextualField("IdComponentName")]
public Int32? IdComponent
        {
            get { return Fields.IdComponent[this]; }
            set { Fields.IdComponent[this] = value; }
        }
/*...*/
```

My ComponentEquipmentRow.cs code:

```
[DisplayName("Component"), Column("id_component"), PrimaryKey, ForeignKey("[dbo].[component]", "id_component"), LeftJoin("jIdComponent"), TextualField("IdComponentName"), LookupInclude]
        [LookupEditor(typeof(ComponentRow))]
public Int32? IdComponent
        {
            get { return Fields.IdComponent[this]; }
            set { Fields.IdComponent[this] = value; }
        }

        [DisplayName("Id Equipment"), Column("id_equipment"), PrimaryKey, ForeignKey("[dbo].[equipment]", "id_equipment"), LeftJoin("jIdEquipment"), TextualField("IdEquipmentName"), LookupInclude]
public Int32? IdEquipment
        {
            get { return Fields.IdEquipment[this]; }
            set { Fields.IdEquipment[this] = value; }
        }
```

I can obtain my IdEquipment but i need my IdComponent, what should i do?. Thanks in advance.

**Comment by edson** [comment]
If I understood correctly... You should add LookupInclude to your Field.. It will be brought at lookup script with Id and Name. Always take a look at basic samples and serenity guide.  Hope it helps.

Regards

**Comment by edson** [comment]
Ok. If I understood correctly, you should implement your component lookup fields as a combination like what is done in #1013 .

**Comment by volkanceylan** [comment]
Sorry but i don't understand why and where you can obtain IdEquipment but not IdComponent.
