### ISSUE TITLE
TextAreaEditor

### ISSUE THREAD

**Issue by rsbatacjr** [volkanceylan/Serenity#1229]
Hello,

I am using TextAreaEditor on my address field. How can I display entered value in TextAreaEditor in multiline when exported on pdf.

Thanks

**Comment by rsbatacjr** [comment]
Additional how can I make font on rendered pdf clearer?

**Comment by rsbatacjr** [comment]
Please ignore the additional. I able to fix the distortion of font by setting dpi to 130

**Comment by edson** [comment]
If I understood correctly, this is not serenity related, but a third part plugin... try searching for this in jspdf forums... something like this https://github.com/simonbengtsson/jsPDF-AutoTable/issues/43 may help you...

**Comment by edson** [comment]
Or maybe you can try implementing a formatter for the column...

Regards

**Comment by wdhodges** [comment]
May not be ideal, but you could separate the address fields into different columns in your database?

**Comment by rsbatacjr** [comment]
thanks for the replies :) it's gives me things to try.

**Comment by edson** [comment]
Hi, @rsbatacjr . I don't know if you already did this, but I've came to this kind of demanding... So I managed to create a simple slick formatter to address this. In case anyone needs it:

```
namespace yourProject {

    @Serenity.Decorators.registerFormatter()
    export class TextAreaColumnFormatter implements Slick.Formatter {

        format(ctx: Slick.FormatterContext) {

            if ((ctx.value == null || String(ctx.value).length == 0)) {
                return ctx.value;
            }



            var textArea: String = ctx.value;
            textArea.replace(/\\r\\n/g, "<br />");
        
            return "<span>" + textArea + '</span>';
        }

       
        
    }
}
```

Best Regards

**Comment by edson** [comment]
I've created a wiki with some custom formatters:

https://github.com/volkanceylan/Serenity/wiki/SlickGrid-Formatters

Best Regards
