### ISSUE TITLE
ExpectedRows.Ignore

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#123]
public static int Execute(this SqlUpdate query, IDbConnection connection, ExpectedRows expectedRows = ExpectedRows.Ignore)
        {
            return CheckExpectedRows(expectedRows, ExecuteNonQuery(connection, query.ToString(), query.Params));
        }

çoklu update sırasında mesaj almamak için ExpectedRows.Ignore kullandım. 
serenity' de değişiklik yapmamam için başka bir yolu var mı?

**Comment by volkanceylan** [comment]
Onu parametre olarak geçirebilirsiniz neden Serenity'yi değiştiriyorsunuz ki?

**Comment by oaltay** [comment]
var que = new SqlUpdate(fld.TableName);
                que.Set(fld.Status, Status.Technician);
                que.Set(fld.TechniciansApprovalDate, DateTime.Now);
                que.Set(fld.TechniciansApprovalUserId, Authorization.UserId);
                que.Where(fld.SampleId == item.Id.Value);
                que.Where(fld.TechniciansApprovalDate.IsNull());
                que.Where(fld.ResultDate.IsNotNull());
                //Tekniker panic için evet dedi ise tümü hayır dedi ise panic olmayanlar onaylanacak 
                if (!request.Panic)
                    que.Where(fld.Hl != (short) Result.Panic);
                que.Execute(uow.Connection);

burada CheckExpectedRows'a takılıyor hata almamak için SqlHelper da ExpectedRows.Ignore yaptım.
parametre nasıl verildiğini çözemediç :(

**Comment by oaltay** [comment]
tşk.ler
