### ISSUE TITLE
QuickSearchInput: customize query and behaviour (searchdelay, etc.)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1230]
Dear @volkanceylan,
I was wondering if there is an easy way to customize the query (contains, start with, etc) and the behaviour (search delay, min text length).
I'm trying to override the "createQuickSearchInput()" method in the EntityGrid, but apparently I cannot access those properties.

Edit: just found the QuickSearch() properties: StartWith, NumericOnly, etc. so I need "only" to customize the search delay and the min length.

Thank you very much for your support
Bye

**Comment by volkanceylan** [comment]
Hi @marcobisio 

I'm afraid there is no simple way to override them without rewriting your own set of helpers for now.

Their code is in GridUtils.cs and QuickSearchInput.cs. You need to override createQuickSearchInput method in entity grid and create your own input, but it's not easy. You may change TypeDelay parameter to a static variable and i'll accept a pull request. But for min length, it requires a bit more changes.

**Comment by marcobisio** [comment]
Thanks for the tips @volkanceylan, I'll try and (in case of success!) I let you know.

Thank you very much
Bye
