### ISSUE TITLE
İliskili 3 tablo yapısı nasıl kurulmalı

### ISSUE THREAD

**Issue by ComertAhmetSahin** [volkanceylan/Serenity#1233]
![kart](https://cloud.githubusercontent.com/assets/21193114/18808407/e41be206-8261-11e6-88d2-5a499176368c.png)

Tanımkart tablosuna  Hem personel Hem müsteri hemde firmaları kaydetmek istiyoruz
Tanimkart a açılan her kaydın detay bilgilerini ise ;
Personel için TanimKartPersonel, 
Firma için TanimKartkurum, 
Musteri içinde TanimKartKisisel tablosuna kaydediyoruz.

TanımKarta açılan her kaydın tür bilgisini ise TanimkartGrup tablosunda tutuyoruz.

TanimKartBanka tablosundaki KartGrupId de, ilgili kartın türünün tutulduğu TanımKartGrup tablosundaki Id kolonuna bağlı.

Bu yapıda TanimkartKisisel Modulu içersinde 
TanimKartKisiselDialog.Template.html ile Tab Page Açıp  Müsterilerin  Banka hesaplarını göstermek istiyorum.  Bu konuda yardımcı olabilirmisiniz ?

**Comment by volkanceylan** [comment]
Sanırım ben olsam 3 ayrı ekran yapardım. Personel, Firma, Müşteri. Üçü de kendi tablolarındaki verileri gösterir. Left join üzerinden zaten ana kart bilgileri gelir. Burada yapmanız gereken, bunlarda BeforeSave i override edip, IsCreate yani yeni kayıt modunda isek, Kart tablosuna manuel kayıt atmak, new KartRepository().Create ile ve gelen KartId yi içerisinde set etmek.

this.Row.KartId = (int)new KartRepository().Create(new SaveRequest ....).EntityId;

gibi
