### ISSUE TITLE
Issue of viewing PDF file in browser

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#1234]
I have button **View Question Paper** , on click of this button i want to show PDF file , and the code is as follows

```
var buttons = base.GetButtons();
            buttons.RemoveAt(0);
            buttons.Add(new ToolButton
            {
                Title = "View Question Paper",
       OnClick = e =>
                {
                    long id = 0;
                    long i = 0;
                    List<string> rs = rowSelection.GetSelectedKeys();
                    foreach (string str in rs)
                    {
                        id = (long)str.ToInt64();
                        i = i + 1;
                    }
                    if (id == 0)
                    {
                        Q.Alert("Please select serial number !");
                    }
                    else
                    {
                        MyProductExamsRow rowdata = this.Items.Where(x => x.ID == (long)rs[0].ToInt64()).FirstOrDefault();
                        var url = "~/upload/" + rowdata.QuestionPaper;
                        Q.Externals.PostToUrl((new PostToUrlOptions
                        {
                            Url = Q.ResolveUrl(url),
                            Target="_blank"
                        }));
                    }
                }
            });

         
```

After selecting exam from list , when i click on **View Question Paper** script executes like this
![firstpage](https://cloud.githubusercontent.com/assets/16666095/18823245/b9441e16-83d5-11e6-8041-c7565700df1e.png)

After further execution it opens new window with 404 error as follows
![page2](https://cloud.githubusercontent.com/assets/16666095/18823278/167d381a-83d6-11e6-80ee-4c7b17d4a88f.png)

When I hit on url PDF dispalys as follows ,

![page3](https://cloud.githubusercontent.com/assets/16666095/18823332/8eeb2028-83d6-11e6-9292-5d22b5eb599b.png)

I want it to display directly on **View Question Paper** buttton, their should not be need to hit on the url, please  help me to correct my code so that **PDF** will be visible on **View Question Paper** button click

**Comment by volkanceylan** [comment]
Use window.open(url, '_blank') not Q.postToUrl, you are not posting anything

**Comment by chetanjoshi1988** [comment]
Thanks volkan , done !
