### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1235]
Please could I request Field level permission be available in a future release of Serenity?

Also, is it possible for me to get premium support? Happy to pay for it as we use it extensively at our company.

**Comment by abelal83** [comment]
What I'm trying to achieve is either permission a field to certain groups or at the very least hide in server side code.

**Comment by volkanceylan** [comment]
It might be possible but not a priority, and might affect performance a bit. It can be done by overriding updateInterface client side, and CanSelectField method at repository level, both using Authorization.HasPermission. Also, it is not very clear what "field level permissions" mean. It might mean not being able to retrieve them from server, or just hiding them client side. If they can't be received from server, any method that depends on their value might fail.

**Comment by volkanceylan** [comment]
For premium support, you might contact me from my e-mail.

**Comment by abelal83** [comment]
sorry to be clear, what I mean by field level permission is to use attributes such as [ModifyPermssion] on fields within XYZRow,cs. Ideally, these would take precedence over class attributes so we can give granualr permissions.

I understand there could be a performance hit due to the additional checks but when security is concerned we don't mind it being a bit slower. 

I will email you direct for prem support.
