### ISSUE TITLE
Alerts during Save Method

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1236]
I want to show alerts to user based on some business logic before saving the record.

if all criteria as per business logic is not fulfilled the save would not work but an appropriate message would be displayed.

if everything is OK then records get saved.

I can put business logic in repository, i only need guidance on how to show a message and abandon save process.

**Comment by volkanceylan** [comment]
throw new ValidationError("Your message")

**Comment by john20xdoe** [comment]
ValidationError's message will automatically display in the browser as a dialog box.
