### ISSUE TITLE
Timeout expired while running INSERT INTO SQL statement in AfterSave().

### ISSUE THREAD

**Issue by keringforza** [volkanceylan/Serenity#1239]
**Situation:**

I have two table, one main table (Engagement) and the other one is bridge table (Engagement_Project). In EngagementRepository.cs, I use AfterSave() --> IsCreate.

**Issue**
When I fill the Engagement form, I also want the data to be inserted into Engagement_Project Table using AfterSave(). The issue is when I save the Engagement form, the ID of Engagement Table is not saved to the database immediately, so that the bridge table (Engagement_Project) cannot found the new ID to be inserted. So that, the query in AfterSave() cannot be execute.

Is that other function rather than AfterSave() to solve this problem?

With Kind regards,
Kering

**Comment by volkanceylan** [comment]
What is type of ID in engagement table?

**Comment by keringforza** [comment]
type int, IDENTITY(1,1)

**Comment by volkanceylan** [comment]
So you should have your ID available in row.EngagementId

**Comment by keringforza** [comment]
When I put a break point at the query in AfterSafe(), the query get the EngagementId, but the thing is the EngagementId still not insert into Engagement table event in AfterSafe(). Or if you don't mind to go through my code, here I attach with.. Sorry I'm beginner..

Many thanks..

`if (IsCreate)
                {                           
                SqlConnection sqlConn = new SqlConnection(ConfigurationManager.ConnectionStrings["IMS"].ConnectionString);                
                SqlCommand sqlCom = new SqlCommand();
                sqlCom = sqlConn.CreateCommand();                

                var strField = new List<string>();
                var strVal = new List<string>();

                    if (this.Row.TriggerEntityID != null)
                    {
                        sqlCom.Parameters.AddWithValue("@EntityId", this.Row.TriggerEntityID);
                        strField.Add("EntityID");//name field kt table
                        strVal.Add("@EntityId");
                    }

                    if (this.Row.TriggerProjectID != null)
                    {
                        sqlCom.Parameters.AddWithValue("@ProjectId", this.Row.TriggerProjectID);
                        strField.Add("ProjectID");
                        strVal.Add("@ProjectId");
                    }             
                    sqlCom.Parameters.AddWithValue("@EngagementId", this.Row.Id);

                    string[] arrField = strField.ToArray();
                    string[] arrVal = strVal.ToArray();

                    string fld = arrField[0];
                    string val = arrVal[0];
                    for (var j = 1; j < arrField.Length; j++)
                    {
                        fld = fld + "," + arrField[j];
                        val = val + "," + arrVal[j];
                    }
                    
                    string cmd = "INSERT INTO Engagement_Project_Entity (EngagementID, " + fld + ") VALUES (@EngagementId, " + val + ")";
                   
                sqlCom.CommandText = cmd;                                   
                sqlConn.Close();
                sqlConn.Open();
                sqlCom.ExecuteNonQuery();
                sqlConn.Close();
                }`

**Comment by volkanceylan** [comment]
You are inserting row by opening another connection while in a transaction. which is pretty wrong. Of course it wont be available in another connection yet. Use Serenity helpers and this.Connection. E.g. This.Connection.Insert(new SomeRow { ... })

**Comment by keringforza** [comment]
many thanxs Volkan for the clue.. i've solve it..

`new SqlInsert(fld.TableName)
                            .Set(fld.EngagementId, ##)
                            .Set(fld.EntityId, ##)
                            .Set(fld.ProjectId, ##)
                           .Execute(this.Connection);`

**Comment by volkanceylan** [comment]
Yes, this is the right way. Could also use Connect.Insert(new YourRow())
