### ISSUE TITLE
Çalışan Örneklerin Ekran Görüntüleri

### ISSUE THREAD

**Issue by wolverine81** [volkanceylan/Serenity#124]
Merhaba Volkan Bey,

Serenityi kullananların örnek ekran görüntüleri yayınlansa faydalı olabilir.
En azından neler yapılabildiği daha kolay görülebilir.

**Comment by volkanceylan** [comment]
Aslında ana sayfada da yazdım, kullananlar bilgi paylaşırsa referans ekleyeyim diye ama dönüş olmadı. Birkaç kişi soru sormak için yaptıkları uygulamaların link lerini paylaştı, güzel yazılımlar var ancak kendilerine sormadan ekran görüntüsü koymak ne kadar doğru olur bilemiyorum.

**Comment by wolverine81** [comment]
Belki kitchen sink projesi oluşturup uygulamanın neler yapabildiği ortaya konabilir.
Ben tutorialleri incelemeye devam edeyim :)
İlginiz için teşekkür ederim.
