### ISSUE TITLE
Grid does not sort in master / detail dialog

### ISSUE THREAD

**Issue by James-A-White** [volkanceylan/Serenity#1240]
It appears as though the detail grid is not sorting in master/detail dialog. To reproduce using samples, open Northwind->Orders.  Click on any OrderID and a dialog opens with Products displayed in the grid. Try clicking the column headers to sort, and nothing happens.  I just upgraded to the 2.4.10.0 version and it still appears to be happening.

Thanks again for a GREAT template!

Jw

**Comment by volkanceylan** [comment]
In memory grid doesn't support sorting, as by default all is done server side, with SQL.

**Comment by James-A-White** [comment]
Makes sense. But if this is the case the sort arrows should be hidden or removed. Thx!

**Comment by volkanceylan** [comment]
You might add Sortable(false) to columns

**Comment by masterlilou** [comment]
How do you change default sort on server side, with SQL ?

**Comment by Zahar661** [comment]
@masterlilou in abcRow.cs for a tedious column [SortOrder(1)]
