### ISSUE TITLE
[HowTo] SlickGrid row and cell text selectable

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1241]
Dear all,
in this simple guide I'll explain how to enable the row selection and also the cell text selection in a SlickGrid (see screenshot below).

![image](https://cloud.githubusercontent.com/assets/17425690/18869528/fedda492-84ac-11e6-89db-07adfd62d645.png)

Here we go:
**1)** add the following line in your _LayoutHead.cshtml:

    @Html.Script("~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js")
just before this line

    @Html.Script("~/Scripts/Site/YOUR_PROJECT.Web.js")

**2)** add the following code in the CustomerGrid.ts file:

    protected getSlickOptions(): Slick.GridOptions {
            var opt: Slick.GridOptions = super.getSlickOptions();
            opt.enableTextSelectionOnCells = true;
            opt.selectedCellCssClass = "slickgrid-row-selected";
            opt.enableCellNavigation = true;
            return opt;
        }

        protected createSlickGrid(): Slick.Grid {
            var grid = super.createSlickGrid();
            grid.setSelectionModel(new Slick.RowSelectionModel());
            return grid;
        }

**3)** add the css required for the highlight of the selected row in the site.northwind.less file:

    .slickgrid-row-selected {
        background-color: lightblue;
    }

The example above is related only to the Customer page on Northwind, but if you need to apply such behaviour to your entire application, then I suggest to extend the EntityGrid class like this:

    namespace Serenity {
        @Serenity.Decorators.registerClass()
        @Serenity.Decorators.filterable()
        export class SelectableEntityGrid<TItem, TOptions> extends EntityGrid<TItem, TOptions> {
    
            protected getSlickOptions(): Slick.GridOptions {
                var opt: Slick.GridOptions = super.getSlickOptions();
                opt.enableTextSelectionOnCells = true;
                opt.selectedCellCssClass = "slickgrid-row-selected";
                opt.enableCellNavigation = true;
                return opt;
            }
    
            protected createSlickGrid(): Slick.Grid {
                var grid = super.createSlickGrid();
                grid.setSelectionModel(new Slick.RowSelectionModel());
                return grid;
            }
    
        }
    }

I recommend to create a new "SelectableEntityGrid.ts" file in Modules\Common\Helpers and put here all the code above.
Then in your xyzGrid.ts file replace "EntityGrid" with "SelectableEntityGrid" like this:

    export class xyzGrid extends Serenity.SelectableEntityGrid<xyzRow, any> { ... }

Finally, remember to add the following instruction at the top of your xyzGrid.ts file:

    /// <reference path="../../Common/Helpers/SelectableEntityGrid.ts" />

Hope it helps...
That's all folks!
Bye

**Comment by Estrusco** [comment]
Great! Thank you!

**Comment by dfaruque** [comment]
Nice. Would you add this sample to serene > basic samples > grid section.

**Comment by marcobisio** [comment]
You're welcome!
I'll wait a @volkanceylan feedback and then I think that can be added to the grid samples...

**Comment by volkanceylan** [comment]
It's really good amd quality one @marcobisio, have nothing to add. 

Maybe ability to check a row with space key when checkbox selection mixin is used, but not critical.

**Comment by marcobisio** [comment]
Thanks for your feedback @volkanceylan!
Let me know if you prefer to add a sample on Serene (in that case I can create a new pull request) otherwise I can put all this stuff on a wiki page.

Bye

**Comment by volkanceylan** [comment]
I'll add this as a sample. No need for a pull request.

**Comment by marcobisio** [comment]
Copy that!
Bye

**Comment by volkanceylan** [comment]
Added in 2.4.10.1, thanks

**Comment by marcobisio** [comment]
You're welcome :-)

**Comment by awesomegithubusername** [comment]
Thanks man. Good work!

**Comment by miro123** [comment]
perfect, saved me from debugging

**Comment by flextrio-gandhi** [comment]
@marcobisio @volkanceylan  good to see that..but is there any alternate  way to make 'Row Selection' Without extending xyzGrid with SelectableEntityGrid.ts class... 
i just changed  'enableTextSelectionOnCells: true' in slick.grid.js file but its not working..

**Comment by marcobisio** [comment]
Hi @flextrio-gandhi I highly recommend you to don't modify 3rd party libraries in order to do global overrides.
I don't know why you shouldn't extend from the SelectableEntityGrid...it just another "layer" between the EntityGrid and your xyzGrids...

**Comment by flextrio-gandhi** [comment]
@marcobisio I was Just planning to override at one place for global changes. Without extending all xyzgrids...  with SelectableEntityGrid.

Okay will follow your process Thanks..!
