### ISSUE TITLE
NancyFx support - Feature request 

### ISSUE THREAD

**Issue by kierepka** [volkanceylan/Serenity#1242]
Hi,

This is great work, and if you can consider another move to make it better, maybe you would like to support: http://nancyfx.org/ ?

**Comment by dfaruque** [comment]
forgive me. 
What do you mean by support? Is the serenity prevent somehow to use nancyfx?

**Comment by volkanceylan** [comment]
Nancy, Web Api, Service Stack etc. all can be used alongside with Serenity.
