### ISSUE TITLE
about this powerful Framework

### ISSUE THREAD

**Issue by thisXYH** [volkanceylan/Serenity#1243]
hi Volkanceylan ,
Your framework is very powerful, to help me reduce the most of the programming time.
When I first started to use, has been learning how to use it.
But now I want to know how to do it so cool I believe and I have the same idea certainly a lot of people.
Can you  use a few chapters about your framework?
Not how to use the angle, but how to achieve the point of view.
Thank you for sharing the framework, for me it is like a treasure, so I am eager to explore

**Comment by thisXYH** [comment]
You can use a few chapters to introduce this framework?  
Roughly the outline

**Comment by volkanceylan** [comment]
Thanks @thisXYH, but what chapter you exactly request? Something about design patterns, or how things work behind the scene?

**Comment by thisXYH** [comment]
You can describe how it works behind the scenes, using what tools and what design patterns, but not too deep into the design pattern.
Mainly to give us a direction and outline to understand the framework, so that we can more easily absorb the framework.
We can read your source code and these chapters to understand the framework,Instead of looking at samples and manuals to use this framework.
We should all know that learning things are generally used from the transition to understand why so use.
Thanks @volkanceylan .I hope I can make you understand the description

**Comment by thisXYH** [comment]
Carelessly press the Close button ...
