### ISSUE TITLE
Receving bad request upon calling the service from another application

### ISSUE THREAD

**Issue by sasinallatech** [volkanceylan/Serenity#1244]
I am using the following code as suggested in another issue (806) to use endpoint in another application,
var client = new JsonServiceClient("http://localhost:2036/");
client.Post<ServiceResponse>("Account/Login", 
    new LoginRequest {
        Username = "someuser",
        Password = "somepass"
    });
But but getting 400 - Bad Request error. 
I have added [ServiceAuthorize()] in AccountPage.cs. Except this nothing is changed in AccountPage.cs.
I am using latest serenity framework.
Any idea, what is wrong here?

**Comment by sasinallatech** [comment]
This is actual response returned by the server (upon putting a catch block),
"{\"Error\":{\"Code\":\"NotLoggedIn\",\"Message\":\"Authorization is required for this request!\"}}"

**Comment by sasinallatech** [comment]
The error seems to be from the following code in Authorization.cs,
public static void ValidateLoggedIn()
        {
           if (!IsLoggedIn)
               throw new ValidationError("NotLoggedIn", null, Serenity.Core.Texts.Authorization.NotLoggedIn);
        }

But, this should not be called as we are just trying to authenticate using the above code. Isn't it?

**Comment by blojayble** [comment]
It should not, but you asked Serenity to do this by adding ServiceAuthorizeAttribute.
You could remove it from the controller and stick it to just the action you require to be authorized.

**Comment by sasinallatech** [comment]
Without adding the attribute also, I am getting the same output.
Thanks,
Regards,
Nallakumar KC
On 28-Sep-2016 5:52 PM, blojayble <notifications@github.com> wrote:It should not, but you asked Serenity to do this by adding ServiceAuthorizeAttribute.
You could remove it from the controller and stick it to just the action you require to be authorized.

**Comment by blojayble** [comment]
Care to us the file?

**Comment by volkanceylan** [comment]
Why are you adding ServiceAuthorize to AccountController?? How Login method supposed to work before you login?

**Comment by sasinallatech** [comment]
I didn't added initially. Read some where like that. But that doesn't matter. In both the cases, I am getting the same error.
Thanks,
Regards,
Nallakumar KC
On 28-Sep-2016 6:44 PM, Volkan Ceylan <notifications@github.com> wrote:Why are you adding ServiceAuthorize to AccountController?? How Login method supposed to work before you login?

**Comment by volkanceylan** [comment]
This is the same action that is called by login form, and it also uses same JSON. So if it is not working with your call, check what is different. A first guess you have captcha in login form. Or something else, you got to find out.

**Comment by sasinallatech** [comment]
Thanks blojayble and volkanceylan. I was just trying to authenticate with wrong credentials. Since, it was throwing as exception, I was getting Bad Request in my code. Now, handled the exception properly and it is working fine now.
