### ISSUE TITLE
Master / Slave  - lookup not evaluated on slave view 

### ISSUE THREAD

**Issue by masterlilou** [volkanceylan/Serenity#1245]
Hi, 

I need your help on this behavior : 

A master view
![image](https://cloud.githubusercontent.com/assets/22059074/18908216/0b61fdcc-856f-11e6-9a1c-cc0e40898d6d.png)

Then 

A slave view 

![image](https://cloud.githubusercontent.com/assets/22059074/18908413/c5bf09da-856f-11e6-8f35-9c9732497f12.png)

Then on edit on slave view,
![image](https://cloud.githubusercontent.com/assets/22059074/18908473/005a44ce-8570-11e6-9617-19faddb3e6c6.png)

The problem is that the C Corresp is empty at window popup,

 with following behavior
 [LookupEditor(typeof(Entities.CorrespondantClientRow), CascadeFrom = "CClient", CascadeField = "CClient")]

If I change CClient field, the pick-list is correctly populated .

![image](https://cloud.githubusercontent.com/assets/22059074/18908676/d1134bf6-8570-11e6-96c3-79aa525a9936.png)

If there any way to proceed ? 

Masterlilou

Note that when i change the lookupEditor to
 [LookupEditor(typeof(Entities.CorrespondantClientRow))]

![image](https://cloud.githubusercontent.com/assets/22059074/18908982/1d0a81b8-8572-11e6-9f4d-42d66836eb07.png)

The displayed name is correct.

**Comment by volkanceylan** [comment]
Set your CascadeField to the field that is going to be filtered in your lookup, not the field in tma table.

**Comment by masterlilou** [comment]
My code is aligned with your rule. 

The fallback is to add a lookupEditor on the cascadedField in the same view.

![image](https://cloud.githubusercontent.com/assets/22059074/18948801/d33b947e-8638-11e6-9450-f20ad4960025.png)
