### ISSUE TITLE
User Lookup

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1247]
I'm trying to create a lookup script that excludes that admin user (UserId 1) and shoes the DisplayName rather than the Username.
I'm getting an error: "Can't load script data"
TIA for any help!  Here's what I have:

User/UserLookupNotAdmin.cs

    namespace EventManager.Administration.User.Scripts
    {
    using Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("Administration.UserLookupNotAdmin")]
    public class UserLookupNotAdmin : RowLookupScript<UserRow>
    {
        public UserLookupNotAdmin()
        {
            IdField = UserRow.Fields.UserId.PropertyName;
            TextField = UserRow.Fields.DisplayName.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = UserRow.Fields;
            query.Distinct(true)
                .Select(fld.UserId)
                .Select(fld.DisplayName)
        .Where(
            new Criteria(fld.UserId) != 1
            );
        }
    }
}

Loan/LoanRow.cs
The table Loan has a "UserId" column.

            [DisplayName("Staff"), NotNull, ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jUser"), TextualField("StaffDisplayName")]
        public Int32? UserId
        {
            get { return Fields.UserId[this]; }
            set { Fields.UserId[this] = value; }
        }

        [DisplayName("Staff"), Expression("jUser.[DisplayName]")]
        public String StaffDisplayName
        {
            get { return Fields.StaffDisplayName[this]; }
            set { Fields.StaffDisplayName[this] = value; }
        }

LoanForm.cs

    [LookupEditor(typeof(Administration.User.Scripts.UserLookupNotAdmin))]
        public Int32 UserId { get; set; }

**Comment by abelal83** [comment]
does the user have access to the service endpoint in loan?

**Comment by mayatstafford** [comment]
I hadn't modifed LoanEndpoint.cs but I just did this and got the same result:

    [ConnectionKey("Default"), ServiceAuthorize(Loan.PermissionKeys.Loan.Modify)]

**Comment by Estrusco** [comment]
Try calling base.PrepareQuery(query); in top of PrepareQuery

**Comment by mayatstafford** [comment]
Thank you.   This is what worked:
    
    namespace EventManager.Administration.User.Scripts{
    using Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("Administration.UserLookupNotAdmin")]
    public class UserLookupNotAdmin : RowLookupScript<UserRow>
    {
        public UserLookupNotAdmin()
        {
            IdField = UserRow.Fields.UserId.PropertyName;
            TextField = UserRow.Fields.DisplayName.PropertyName;
        }


        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            var fld = UserRow.Fields;
            query.Distinct(true)
                .Select(fld.UserId)
                .Select(fld.DisplayName)
        .Where(
            new Criteria(fld.UserId) != 1
            );
        }
    }
}


and in LoanForm.cs:

    [LookupEditor("Administration.UserLookupNotAdmin")]
        public Int32 UserId { get; set; }
