### ISSUE TITLE
Different Dashboard based on login

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1249]
I need to make a page for a kiosk where the public would search for their email, and if found they could register for an event with that email or create a new user.

I figured I could create create a generic role that would make only this page(s) accessible.  The manager would log in and rather than being directed to the dashboard they would be directed to a form.

So the first step is for me to figure out - how do I redirect to someplace other than the dashboard based on a user role?  Thank you...

**Comment by volkanceylan** [comment]
I strongly recommend avoiding relying on a role. Everything should be handled through permissions. Authorization.HasPermission etc.

**Comment by mayatstafford** [comment]
I was assigning users Roles and the Roles had permissions.   The files themselves are based on permissions as you said.  I guess I would need to create a permissions just for this.    But even if I do that, how do I show a page different than the dashboard?   I don't even want to show the navigation..

**Comment by volkanceylan** [comment]
On dashboard page, you should redirect user to another page, with another layout, if he doesn't or does have a permission.

**Comment by volkanceylan** [comment]
Use LayoutNoNavigation as layout page.
