### ISSUE TITLE
URL Attribute for Colum value to be a Link (like EditLink but for custom URL)

### ISSUE THREAD

**Issue by dcvikl** [volkanceylan/Serenity#125]
Hi,
I'm trying to URL encode the value of a Field "Company Website", I tried to find an Attribute but with no success.

Is it even possible without the use of custom scripting?

**Comment by VictorTomaili** [comment]
Try to declare a behaviour https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/using_serenity_service_behaviors.html

**Comment by volkanceylan** [comment]
I think he looks for a formatter @VictorTomaili 

It's not possible without writing a format function or formatter.

```cs
    public class UrlFormatter : ISlickFormatter
    {
        public string Format(SlickFormatterContext ctx)
        {
            return "<a href='" +  Q.UrlEncode(ctx.Value) + "'>" + 
                Q.HtmlEncode(ctx.Value) +
                "</a>";
        }
    }
```

Add this, transform T4 files, and now you have a UrlFormatter.

**Comment by VictorTomaili** [comment]
Ow sorry i dont see title well. Behaviour is when save the link to database with url encoding.

**Comment by volkanceylan** [comment]
1.9.2 has this formatter now.
