### ISSUE TITLE
Problem Select

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1250]
I was trying to make the layout more user friendly to accomodate the backend changes, but found a problem.

The bootstrap select is incorrectly themed, your version:
![image](https://cloud.githubusercontent.com/assets/10889019/18935381/91c1c3e4-85d7-11e6-921c-880155e1bc59.png)

The original select bootstrap template adminlte that i want:
![image](https://cloud.githubusercontent.com/assets/10889019/18935396/aeb2dfba-85d7-11e6-8032-f3036504dd48.png)

What changes can I do to make it right.

**Comment by volkanceylan** [comment]
It's not incorrectly themed. It's theme used. Use CSS.
