### ISSUE TITLE
Different (new/edit) dialog/form for different user/role

### ISSUE THREAD

**Issue by mrsjakie** [volkanceylan/Serenity#1252]
I hope someone can help me with this. Depending on the role a user has, the grid is filtered with the records for this user. Depending on the role the user has, there should be different dialog/forms but from the same db definition, because it is 1 record with fields for several different userroles. I tried several things but can't find where to place this and how to do it.
Can someone give me an example and tell me in what file I should do this?
I used the if (Authorization.HasPermission("Contracts:Requester")) but I was calling a different view but it is not the view I need (because that shows me a grid), it is a different dialog/form I need, when someone clicks on the grid to edit a record or add a record.

Thanx in advance.

**Comment by volkanceylan** [comment]
There is a custom links in grid sample, have a look at it. You also need multiple dialogs/forms.

**Comment by Zahar661** [comment]
possible without Custom Links

in InGrid
      ```
 entityId: any
        protected editItem(entityOrId: any): void {
            this.entityId = entityOrId;
            super.editItem(entityOrId);
        }
        protected getDialogTypeFor() {
            var item = this.view.getItemById(this.entityId);
            if (item.TypeId == 3)  return StagesTasksDdDialog;
            else  return StagesTasksDialog;
        }
```
