### ISSUE TITLE
Trying to serialize a descendant of Serenity.Row

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#1253]
Hi Volkan,

I have a web service page in my Serenity based webapp with method to return a list of rows. I get the following error message when loading the service page:

> [InvalidOperationException: System.EventHandler cannot be serialized because it does not have a parameterless constructor.]
> 
> [InvalidOperationException: Cannot serialize member 'Serenity.Data.Row.PostEnded' of type 'System.EventHandler', see inner exception for more details.]
>    System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type) +5419873
>    System.Xml.Serialization.StructModel.GetFieldModel(FieldInfo fieldInfo) +156
>    System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo) +5419837
>    System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter) +618
>    System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter) +378
>    System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter) +5421607
>    System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter) +378
>    System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter) +1799
> 
> [InvalidOperationException: There was an error reflecting type 'LCPermits.Permits.Entities.ContractorRow'.]
> 

I tried using XmlIgnore attribute but still getting the error. Here is my code:
```
namespace LCPermits.Permits.Entities
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    [ConnectionKey("Default"), DisplayName("Contractor"), InstanceName("Contractor"), TwoLevelCached]
    [ReadPermission("Permits")]
    [ModifyPermission("Permits")]
    public sealed class ContractorRow : Row, IIdRow, INameRow
    {
        [XmlIgnore()]
        public new EventHandler PostEnded
        {
            get { return base.PostEnded; }
            set { base.PostEnded = value;  }
        }

        [DisplayName("Contractor Id"), Column("contractor_id"), Identity]
        public Int32? ContractorId
        {
            get { return Fields.ContractorId[this]; }
            set { Fields.ContractorId[this] = value; }
        }

```
and code for the webservice:

```
using LCPermits.Permits.Entities;
using Serenity.Data;
using Serenity.Services;
using System.Data;
using System.Web.Services;
using System.Xml.Serialization;
using MyRepository = LCPermits.Permits.Repositories.ContractorRepository;

namespace LCPermits
{
    /// <summary>
    /// Summary description for WebService
    /// </summary>
    [WebService(Namespace = "http://tempuri.org/")]
    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
    [System.ComponentModel.ToolboxItem(false)]
    // To allow this Web Service to be called from script, using ASP.NET AJAX, uncomment the following line. 
    // [System.Web.Script.Services.ScriptService]
    public class WebService : System.Web.Services.WebService
    {

        [WebMethod]
        [XmlInclude(typeof(ContractorRow))]
        public ContractorRow[] GetAllContractors()
        {            
            ListRequest request = new ListRequest();
            IDbConnection connection = SqlConnections.NewByKey("Default");
            ListResponse<ContractorRow> result = new MyRepository().List(connection, request);

            return result.Entities.ToArray();
        }
    }
}


```

**Comment by volkanceylan** [comment]
Hi Mark,

I don't think XML serialize cares about a new property and its XmlIgnore attribute. If you have to use XML, your only option i can imagine is to create a dummy DTO class matching your row properties, and map your row to that DTO class. That's what they do with EF and similar all the time.

One easy way to convert is to JSON serialize your row[] , than deserialize it into your DTO[]

**Comment by c9482** [comment]
Hi Volkan,

Thanks for your reply. This technique worked for me in the past. However, I was never trying to  "ignore" an inherited property.

**Comment by volkanceylan** [comment]
Yes it should work for a normal property, but to CLR/XML serializer they are two different properties, and don't share attributes.
