### ISSUE TITLE
Bind data to textarea clientside and use Q.serviceCall

### ISSUE THREAD

**Issue by tverkroost** [volkanceylan/Serenity#1255]
Hi Volkan,

I learned a lot last week about Senerity.  Still not quit familiair and have some questions.
First I have a textarea within a dialog in a typescript file. I want to filll the textarea using Q.serviceCall that is calling a WebApi.  I tried to use a Serenity.EntityDialog class but without any luck. Furthermore I think that is a overkill since I need one field. How to accomplish that? 

Code:

 export class MessageContentDialog extends Serenity.TemplatedDialog<MessageContentDialogOptions>  {

        private content: string;

        constructor(opt: MessageContentDialogOptions) {
            super(opt);

            Q.serviceCall<string>({
                url: Q.resolveUrl('http://localhost:41999/api/messageContent/' + this.options.messageId),
                onSuccess: response => {
                     //Howto bind the textarea with it's data ????
                }
            });
        }

2) I use Q.serviceCall and afterwards calling the WebApi I get an exception "{"Message":"The requested resource does not support http method 'POST'."}" 
Why?

I look forward to hearing from you soon.

Kind regards,
Tako Verkroost

**Comment by tverkroost** [comment]
![issuedatabinding](https://cloud.githubusercontent.com/assets/22540578/18987471/191286a0-8702-11e6-8035-aa5935d20ddc.png)

**Comment by volkanceylan** [comment]
I wonder why you fix mix Web Api with Serenity, but if you do use $.ajax, not Q.serviceCall. I suggest you read guides a bit, and see other sample services in code.
