### ISSUE TITLE
Suggestion Required for Employee Attendance Software

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1256]
Dear Volkan,
I would like you to give me suggestion on following scenario.
I want to develop Employee Attendance Software, in which i will be storing each employee's In and Out time of Work. For this i will use a table which store In and Out timing of employee for each day.
So for a month data of an employee goes vertical, but if i want it in horizontal manner like 
![untitled](https://cloud.githubusercontent.com/assets/19570368/18987367/f0f36c58-871e-11e6-86d4-1b3a37d669b9.png)
For this i thought to use another table which will have column from 01 to 31 for each day.
But with this solution, customer can only view records of employee for a particular month and not
for date range spanning in both the month like 26 - Aug to 25 - Sept.
How we can have flexible column Names and data in serenity.
can u suggest some thing on this?
regards
Shailesh

**Comment by volkanceylan** [comment]
override getColumns() and create dynamic set of columns.

**Comment by shaileshbc** [comment]
Currently i am not sure how to design the table.
Will search a little bit and hence closing the issue.
regards
Shailesh
