### ISSUE TITLE
No mapping exists from object type - Exception

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1257]
I have added one field to UserRow.cs like
`[SetFieldFlags(FieldFlags.ClientSide)]`
`[LookupEditor(typeof(LookUpRow),Multiple =true), ClientSide]`
`[LookupEditor(typeof(LookUpRow),Multiple =true), ClientSide]`
`[LinkingSetRelation(typeof(UserSitesRow),"UserId","SiteId")]`
`public List<Int32> Sites`

It gives me following error when i am trying to change password of user through change password form.
<b>No mapping exists from object type System.Collections.Generic.List1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] to a known managed provider native type.</b>
on following code 
`if(user != null)

                {
                    user.PasswordSalt = salt;
                    user.PasswordHash = hash;
                    uow.Connection.UpdateById<UserRow>(user);
                }`
I have only this field as a List<> in UserRow.cs.
This error occurs only in Change Password form, where as User information gets successfully modified through User Dialog.
The field is declared as ClientSide still getting error.
Can you help me out.
regards
Shailesh

**Comment by volkanceylan** [comment]
Create a new user row and only populate id and other fields you'll update. You probably got that user from somewhere else, which also contains an array in Sites field.

**Comment by shaileshbc** [comment]
Dear Volkan,
original code also gives same error, hence i have fetch user from database and set Sites field, still i am getting same error.
original code
`uow.Connection.UpdateById(new UserRow

                {
                    UserId = userId,
                    PasswordSalt = salt,
                    PasswordHash = hash
                });`
and Modified code
`var user = uow.Connection.TryFirst<UserRow>(UserRow.Fields.UserId == userId);

                if (user != null)
                {
                    user.PasswordSalt = salt;
                    user.PasswordHash = hash;
                    var usersitesList = uow.Connection.List<UserSitesRow>(UserSitesRow.Fields.UserId == user.UserId.Value);
                    var usersites = new List<int>();
                    foreach (UserSitesRow usersitesRow in usersitesList)
                    {
                        usersites.Add(usersitesRow.SiteId.Value);
                    }
                    user.Sites = usersites;
                    uow.Connection.UpdateById<UserRow>(user);
                }`
regards
Shailesh

**Comment by volkanceylan** [comment]
You can't set sites with SQL update.

**Comment by shaileshbc** [comment]
Original code has same code as suggested by you.
But still i am getting error.

The error is thrown by code itself and not by sql server.
so how to solve this issue?
regards
Shailesh

**Comment by volkanceylan** [comment]
I dont think change password form in Serene doesnt work. Find what sets Sites in your code.

**Comment by shaileshbc** [comment]
After little bit of searching, I found problem. This was happening since, i have initialised Sites field in Constructor of UserRow and hence while changing password, Sites also get added into Update command.
Where as Sites is not a field in a User Table of Database and hence it was giving error.
so i changed the code  and now changing the password of user is working.
thank you for your support.
regards
Shailesh
