### ISSUE TITLE
Kayıt/Düzenleme Ekranında Gözükmemesi Gereken Alanlara Veri Girişi

### ISSUE THREAD

**Issue by wolverine81** [volkanceylan/Serenity#126]
Merhaba,

Kayıt/Düzenleme ekranında gözükmesini istemediğimiz
KayıtTarihi,KayıtYapanKullanıcı, DüzenlemeTarihi, DuzenlemeYapanKullanici gibi alanlar var 

Kayıt anında KayıtTarihi,KayıtYapanKullanıcı alanlarına veri girişini
Düzenleme anında da DüzenlemeTarihi, DuzenlemeYapanKullanici alanlarını güncellemeyi 

nasıl yapabiliriz.

Teşekkürler

**Comment by VictorTomaili** [comment]
Form alanından property lerini kaldırıp save handler da prepearequery override edilerek müdahale edilebilir. Hatırladığıma göre bu işi otomatik yapan auditlog gibi birşey vardı.

**Comment by ademc** [comment]
UserRow a bakın; orda UserRow sınıfı normal Row dan değil de LoggingRow dan türetilmiş. Yine field ları da LoggingRowFields dan türemiş. LogginRow un İnsertDate, InsertUserId, UpdateDate, UpdateUserId ve IsActive alanları var. Bu alanları tablonuzda aynı isimlerle oluşturup Row unuzu UserRow gibi düzenlediğinizde istediğiniz şey otomatik olarak yapılacak. Yani insert alanları create aşamasınada update alanları da update aşamasında otomatik olarak dolacaktır.

Bunun için tablodaki bu loglanabilir alanları User tablosundaki gibi daki gibi ve Row sınıfında da yine LoggingRowdan türetilecek şekilde düzenleme yapmanız yeterli.

**Comment by volkanceylan** [comment]
Aslında LoggingRow dan IsActive i çıkarmam gerek.

Ayrıca LoggingRow kullanmaları için alan adlarının birebir aynı olması gerekiyor. Onun yerine kendi baz row larını oluşturup IInsertLogRow, IUpdateLogRow vs. interface lerini de implemente edebilirler.

Şimdi bu alanlar kullanıcının girebileceği alanlar olmadığından öncelikle Insertable(false) ve Updatable(false) attribute larını hepsinin üzerine yerleştirin.

Formlardan diğer arkadaşların dediği gibi isterseniz saklayabilirsiniz. Ama ekranda gözüksün istiyorsanız salt okunur olacak zaten durabilir.

Eğer row larınızda IInsertLogRow, IUpdateLogRow implemente ederseniz, bu alanlar otomatik dolar.  Bunla uğraşamam derseniz, SetInternalFields metodunu override edip SaveHandler'da, IsCreate, IsUpdate durumuna göre alanları sizin set etmeniz gerekir.

**Comment by VictorTomaili** [comment]
SetInternal mi oldu o, kullanmayalı çok değişmiş. Kendimden utandım. 😃

**Comment by volkanceylan** [comment]
Evet aktif kullanmadığın ortaya çıktı :) SetInternalFields olmadı, hep öyleydi. PrepareQuery eski kaydı yükleyecek sorguyu hazırlamak için.

**Comment by VictorTomaili** [comment]
Tamam ben o zaman gideyim biraz proje filân yapayım

**Comment by volkanceylan** [comment]
Yap bakalım, ben de başlayayım, o benii sırtımdan vurduuu falan :)

**Comment by Olricz** [comment]
bu konuda ornek var mı ?

**Comment by volkanceylan** [comment]
UserRow var örnek olarak Serene içinde.

**Comment by Olricz** [comment]
Update ınsert ok. IDeleteLogRow 'a bakmıstım.

**Comment by volkanceylan** [comment]
O da benzer şekilde ancak kaydın silinmemesi lazım, IsActive gibi bir alan gerekli

**Comment by Olricz** [comment]
tesekkurler.

**Comment by Olricz** [comment]
Volkan, aynı formda dropdownlist baglantısını nasıl yapacagız. İl / İlçe dropdownlist'leri gibi. İli secince digerinin tekrar dolması. bu konuda ben ornek bulamadım. Selamlar,

**Comment by volkanceylan** [comment]
Cascaded howto var guide ta onu inceleyin

**Comment by volkanceylan** [comment]
Bir de ayrı issue açın lütfen, mümkünse ingilizce

**Comment by Olricz** [comment]
ok. tesekkur ederım.
