### ISSUE TITLE
something wrong on Tabs

### ISSUE THREAD

**Issue by masterlilou** [volkanceylan/Serenity#1261]
Need help - no idea how to correct ... I have the content of the pole tab appearing on every tab. 

![image](https://cloud.githubusercontent.com/assets/22059074/18996789/f242af0c-8731-11e6-972c-3d71de9bbb77.png)

My analyse  is that the template below is not applied  on the pole tab 
    <div id="~_TabInfo" class="tab-pane s-TabInfo">
        <div id="~_Toolbar" class="s-DialogToolbar">
        </div>
        <div class="s-Form">
            <form id="~_Form" action="">
                <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                    <div id="~_PropertyGrid"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>

Any suggestion ?

**Comment by volkanceylan** [comment]
Check your HTML

**Comment by masterlilou** [comment]
Correct 

Thanks
