### ISSUE TITLE
Connection vs Repository

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1264]
Two questions, please.

From the business logic in other classes is more convenient use Connection.Insert-GetBy-List ecc or call new MyRepo().Create-Retrieve-List ecc.? Is there any difference?
And there is a way to use Connection.List with **ColumnSelection.Details**?

```cs
var list = Connection.List<xyz1Row>(field == new ValueCriteria(value));
long? id = Connection.InsertAndGetID<other2Row>(newRow);
```
or 

```cs
var list = new MyRepo1().List(Connection, new Serenity.Services.ListRequest() { ... }).Entities.ToList();

UnitOfWork uow = new UnitOfWork(connection);
SaveRequest<MyRow> sr = new SaveRequest<MyRow>();
sr.Entity = newRow;
new MyRepo2().Create(uow, sr);
```

**Comment by volkanceylan** [comment]
Connection extensions access DB directly, without going through repositories / behaviors. If you dont need or care about behaviors / validation / permissions / business logic etc, it is fine to use them and they are faster. Details mode only meaningful for List handlers so connection.List doesnt have such a feature. You may modify query by using its second overload and select fields you like. You may write an extension method similar to SelectTableFields if you need all detail fields often.

**Comment by Estrusco** [comment]
Thank you very much for this very useful explanation @volkanceylan .

**Comment by volkanceylan** [comment]
You're welcome ;)
