### ISSUE TITLE
Not able to add new customer and order

### ISSUE THREAD

**Issue by roslinev** [volkanceylan/Serenity#1265]
Hi, I am working on serenity application. I downloaded and its running fine. Even the movie db which I replicated is working fine.But I am not able to add new customer or create new order.I am not able to figure out the place where this might be going wrong. Can you help  me with this?

**Comment by volkanceylan** [comment]
See browsee console for errors first.

**Comment by roslinev** [comment]
In the console it shows..
Cant load script data:Lookup.Northwind.Employee

**Comment by volkanceylan** [comment]
Well, now you should check what error returns from ajax request in network console. Probably permission problem.

**Comment by roslinev** [comment]
Well , even for admin Im not able to create new customers or orders. So where do we check for permsissions?  I checked in CustomerRow and Customer columns.

**Comment by volkanceylan** [comment]
Admin has all permissions. I'm not sure what you changed. See request response from network tab to get the actual error. Hope you didn't use space, dot, comma etc. while creating project.
