### ISSUE TITLE
DateFilters in mytableGrid

### ISSUE THREAD

**Issue by CAlva123** [volkanceylan/Serenity#1268]
Hello, sorry for my bad english.

Is there any example of how can I add a Date/DateTime editor quickfilter in mytableGrid?

I want to have just 1 picker per field, not a date range with two pickers like when  I use the atribute [Quickfilter] in mytableColumns.

How can I achieve this?

Thanks in advance for your help.

**Comment by volkanceylan** [comment]
You may simply use addQuickFilter method.

**Comment by CAlva123** [comment]
I used this code:

protected createQuickFilters() {
            super.createQuickFilters();
            this.addQuickFilter({
                
                type: Serenity.DateEditor,
                field: TurnoRow.Fields.MyDateField
            });
        }

and the picker appears, but it doesn't filter my grid.
Is there anything else I need to add?

Thanks in advance.

**Comment by volkanceylan** [comment]
It should be filtering the grid, i don't know what's wrong there.

**Comment by volkanceylan** [comment]
Check request to see if it is transferred in List request.

**Comment by CAlva123** [comment]
[](http://i.imgur.com/uxSJat9.png)
The criteria field is null.

**Comment by volkanceylan** [comment]
No, it goes in EqualityFilter

**Comment by CAlva123** [comment]
http://i.imgur.com/NBnNCoR.png

It does appear there.

**Comment by volkanceylan** [comment]
So it should be working. Are you sure other quick filters work but not the date one?

**Comment by CAlva123** [comment]
Yes, but this is the only one I created from MyTable.grid
The other ones use the atribute [QuickFilter] in MyTable.Columns and some use LookupScripts as well.

**Comment by volkanceylan** [comment]
I've just removed [QuickFilter] from OrderForm.cs on OrderDate, and added it with this code:

```
            this.addQuickFilter({
                type: Serenity.DateEditor,
                field: fld.OrderDate
            });
```

It is working so, see what's wrong with your field / repository etc.

**Comment by CAlva123** [comment]
Ok.

Thank you.

**Comment by CAlva123** [comment]
The problem is the time part of the datetime.

In the database, OrderDate has values like : 1996-07-04 00:00:00.000
While my table values like: 2016-09-09 16:32:26.663

When I changed the time value for something like 2016-09-09 00:00:00.000  the filter worked.

I have something like this in MyTable.Row : DisplayFormat("dd/MM/yyyy HH:mm"), but it looks like I need to format the DateTime input in another place.

Do you have any advice for this?
Thanks in advance for your answer.

**Comment by CAlva123** [comment]
Is there a way to add a criteria for the filter ?

Something like  Date Input >= MyDateField.

That way I can at least get all the registries since that Date.

Thanks for your help and sorry for the trouble.

**Comment by volkanceylan** [comment]
Date filtering already does that. If you want to filter to time scale, see code for date range filter and write on of your own.

**Comment by volkanceylan** [comment]
2.5.1 has date time quick filter

**Comment by abdulrehman0011** [comment]
someone help me to find the year range data from the table im new in serenity plzz guide me to learn serenity

**Comment by VictorTomaili** [comment]
@abdulrehman0011 please use [discussions](https://github.com/serenity-is/Serenity/discussions)
