### ISSUE TITLE
[Please Star this repository] Don't forget

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1270]
I don't understand that why serenity has only 500+ star on github. It should be at least 5000+ star. So everybody please make sure that you have clicked the Star :star: button!

**Comment by marcobisio** [comment]
done! :-)

**Comment by brunobola** [comment]
done :)

**Comment by dfaruque** [comment]
Seems it works! :)

When I open this issue the number stats was 512 now it is 548...
Hope this will 1000 by next month.

**Comment by Mumarda** [comment]
597

**Comment by dfaruque** [comment]
now it is 603. wow.

**Comment by vijaykumar3060** [comment]
610 :+1:

**Comment by dfaruque** [comment]
750(+-) now
even many dudes have not yet Give a Star. :(

**Comment by RMamoon** [comment]
830 :)

**Comment by JohnRanger** [comment]
1083 - seems counting up :-)

**Comment by Zahar661** [comment]
1120

**Comment by rolembergfilho** [comment]
done!
stopped on 1169...

**Comment by dfaruque** [comment]
700 :star:  in past 12 months
60 :star:  per Month.
2 :star:  per Day.

Not enough though.

**Comment by kjaraa** [comment]
1203 today !!  :)

**Comment by volkanceylan** [comment]
Thanks to all stargazers ;) closing
