### ISSUE TITLE
Updating to 2.4.10

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1271]
I have just updated the nuget packages to 2.4.10 version, but after this the Serenity.Services.SaveRequest<MyRow>(); (and others) don't exist.

![cattura](https://cloud.githubusercontent.com/assets/16304015/19066416/76f0d00a-8a19-11e6-8736-bd485ffc85b1.PNG)

**Comment by volkanceylan** [comment]
It's probably intellisense. Try restarting VS.

**Comment by volkanceylan** [comment]
Uhm, missed that. SaveRequest is an interface, you can't new it :) It didn't change in 2.4.10.

**Comment by Estrusco** [comment]
I have retry, But the problem is that in the downloaded packages from nuget

\packages\Serenity.Data.Entity.2.4.10\lib\net45
\packages\Serenity.Data.2.4.10\lib\net45

ecc. are empty... 

anyone have this problem?

**Comment by volkanceylan** [comment]
It's NuGet. Delete them then it will restore them. Then try reinstall.

**Comment by Estrusco** [comment]
Deleted all 2.4.10 serenity packages, restored the nuget packages, but the problem isn't resolved.
I go back to 2.4.9 for now

**Comment by Estrusco** [comment]
With versione 2.4.11 all is ok. Thank you.
