### ISSUE TITLE
Custom form redirects to dialog?

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1273]
I've created a form that looks for an email address.  If it exists I need to go to one dialog, if not it should go to another dialog.   I'd also like to pass the email that is entered to the next form. 

I based it off of some of the code in the Membership folder but I'm stuck on how do I get it to open up an existing dialog?   The example below is my attempt to send it to another form but I want it to open up CustomerDialog.    Thank you

     public ActionResult ESearch(ESearchRequest request)
        {
    ...................removed................
     if (customer == null)
                    {
                        //new customer
                        var renderUrl = "~/Register/NCustomer/NCustomer?email=" + Uri.EscapeDataString(request.Email);
                        return new RedirectResult(renderUrl);
                    }

                    else
                    {
                        //customer exists, but not for this event so register
                        var renderUrl = "~/Register/ECustomer/ECustomer?email=" + Uri.EscapeDataString(request.Email);
                        renderUrl += "&customerid=" + Uri.EscapeDataString(customer.Id.ToString());
                        return new RedirectResult(renderUrl);
                    }

**Comment by volkanceylan** [comment]
I don't recommend to use dialogs for such work. Either use one page, or use a templated panel / inline form. Anyway if you still want to open a dialog on entry to a page, do it like
```
var dlg = new SomeDialog();
dlg.loadEntity({ some entity });
dlg.dialogOpen();
```

**Comment by mayatstafford** [comment]
Thank you so much for your suggestions.   I will avoid using a Dialog. 
So on the first form you search for an email and one of the following happens:
1. email already registered for event, error
2. email found, register for event
3. email not found, register as customer and event

I have two questions. 
1. How to I get the next form to not open in a new window?
2. How do I pass information (customerId,email) from the search form to the next one?


If I use ActionResult it will open in a new window but of course it ignores the Q.servicecall in the panel.  Is there a way to send information to the Q.ServiceCall in the panel if I change ActionResult to Result<ServiceResponse>?
Thank you again.

ESearchPage.cs

           [HttpPost, JsonFilter]
        public ActionResult ESearch(ESearchRequest request)
        {
            var email = request.Email;

            using (var connection = SqlConnections.NewByKey("Default"))
            {
                var curEvent = connection.TryFirst<Event.Entities.EventRow>(Event.Entities.EventRow.Fields.Display == 1);

                var ce = Event.Entities.EventCustomerRow.Fields;
                var eventcustomer = connection.TryFirst<Event.Entities.EventCustomerRow>(q => q
                          .Select(ce.Id)
                          .Where(
                      new Criteria(ce.CustomerEmail) == request.Email &&
                       new Criteria(ce.EventId.ToString()) == curEvent.Id.ToString()
                      ));

                if (eventcustomer != null)
                {
                    return Error("Already registered");
                }
                else
                {
                    var customer = connection.TryFirst<Customer.Entities.CustomerRow>(Customer.Entities.CustomerRow.Fields.Email == request.Email);

                    if (customer == null)
                    {
                        //new customer
                        //OPENS IN NEW WINDOW
                        return View(MVC.Views.Registration.EventRegister.NewCust.NCustomer);
                    }
                    else
                    {
                        //customer exists, but not for this event so register  
                        //OPENS IN NEW WINDOW
                        return View(MVC.Views.Registration.EventRegister.ExistingCust.ECustomer);
                    }
                }

            }
        }

ESearchPanel.ts
     @Serenity.Decorators.registerClass()
    export class ESearchPanel extends Serenity.PropertyPanel<ESearchRequest, any> {

        protected getFormKey() { return ESearchForm.formKey; }

        private form: ESearchForm;

        constructor(container: JQuery) {
            super(container);

            this.form = new ESearchForm(this.idPrefix);

            this.byId('SubmitButton').click(e => {
                e.preventDefault();

                if (!this.validateForm()) {
                    return;
                }
                
                Q.serviceCall({
                    url: Q.resolveUrl('~/Search/ESearch'),
                    request: {
                        Email: this.form.Email.value
                    },
                    onSuccess: function (response) {
                            window.location.href = Q.resolveUrl('~/Registration/ECustomer');
                    }
                });
            });
        }
    }

**Comment by volkanceylan** [comment]
You should load new values through services, retrieve or other custom one you wrote. I think you are confusing CSHTML / typescript.
