### ISSUE TITLE
Lookup failed to load from _LayoutNoNavigation.cshtml

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1274]
When we try render the countries drop the name for the look is:

![capture](https://cloud.githubusercontent.com/assets/22570602/19088138/8e089e08-8a7d-11e6-9c4b-c3f19d090498.PNG)

Thank you!

**Comment by volkanceylan** [comment]
Check permission for your countries lookup. And see request response from network tab to get the actual error.

**Comment by in32bit** [comment]
Thank you for your help.
It was indeed permission issue.

![capture](https://cloud.githubusercontent.com/assets/22570602/19102583/0da5daa2-8ada-11e6-9bc4-09ee24f145f3.PNG)

**Comment by volkanceylan** [comment]
You shouldn't do that. LookupScript attribute has a permission property, set it to "*" for all users. If you remove ReadPermission, anyone can read all fields of your countries row. Even though it probably doesn't have any secret, doing it for others might lead to security holes.

**Comment by in32bit** [comment]
Thanks for your help.
I did as you wrote, but now the select2 input is missing in the post request...

![capture](https://cloud.githubusercontent.com/assets/22570602/19507555/781859a2-95dc-11e6-835c-aeac7fb517b3.PNG)

**Comment by volkanceylan** [comment]
Show your form / row  definition.

**Comment by in32bit** [comment]
Here 

[FormScript("Membership.SignUp")]
    public class SignUpForm
    {
        [DisplayName("Company Identification (VAT)"), Required(true)]
        public String CompanyIdentification { get; set; }

        [DisplayName("Company Name"), Required(true)]
        public String CompanyName { get; set; }

        [DisplayName("Country"), Required(true)]
        [LookupEditor(typeof(MasterData.General.Scripts.CountriesLookup))]
        public Int32? CountryId { get; set; }

        [Required(true)]
        public String City { get; set; }

        [Required(true)]
        public String Address { get; set; }

        [Required(true)]
        public String State { get; set; }

        [DisplayName("ZIP Code")]
        public String ZipCode { get; set; }

        [DisplayName("Telephone Number"), Required(true)]
        public String Tel { get; set; }

        [Required(true)]
        public String DisplayName { get; set; }

        [EmailEditor, Required(true)]
        public String Email { get; set; }

        [EmailEditor, Required(true)]
        public String ConfirmEmail { get; set; }

        [PasswordEditor, Required(true)]
        public String Password { get; set; }

        [PasswordEditor, Required(true)]
        public String ConfirmPassword { get; set; }
    }
