### ISSUE TITLE
hardcoded list for LookupEditor

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1276]
Hi,

Apols if this has been asked but I couldn't find any examples.

Is it possible to create a list for LookupEditor that uses a hard coded items in code? For example I would like a dropdown list where users can select True or False, using a database table for this seems excessive. Unless of course I need to use something else other than LookupEditor?

Many thanks, 

Abu

**Comment by lushmana** [comment]
I need this also but with a list of string values, returning themselves as values.

Such as a lookup for Table Type,  with values: Type 1, Type 2, Type 3, then once selected returning the Type 2 as the selected value for example.

**Comment by abelal83** [comment]
hi @lushmana 

I don't suppose you've made any attempts at this? I'm not sure where to even begin.

**Comment by awesomegithubusername** [comment]
You can use Enumeration. Take a look at [this](https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/adding_a_movie_kind_field.html).

**Comment by volkanceylan** [comment]
```
@Serenity.Decorators.registerEditor()
export class MyHardCodedEditor extends Select2Editor<any, any> {
    constructor(hidden: JQuery) {
        this.addItem("value1", "Text 1");
        this.addItem("value2", "Text 2");
    }
}
```

**Comment by lushmana** [comment]
Ok I have created the new Editor class,
```
 @Serenity.Decorators.registerEditor()
    export class TableTypeEditor extends Serenity.Select2Editor<any, any> {

        constructor(hidden: JQuery) {
            super(hidden, null);
            this.addItem("Staging", "Staging");
            this.addItem("Transaction", "Transaction");
            this.addItem("SCD 1", "SCD 1");
            this.addItem("SCD 2", "SCD 2");
        }
    }

```
And added the following EditorType tag to the field:
```
[DisplayName("Table Type"), Size(50), NotNull, QuickFilter, LookupFiltering("DWStudio.TableType"), EditorType("TableTypeEditor")]
        public String TableType
        {
            get { return Fields.TableType[this]; }
            set { Fields.TableType[this] = value; }
        }

```
Now when I click on the link to display the dialog it never shows the dialog, I'm assuming their is some sort of error when trying to display the dialog, but I just get no response!

**Comment by adhikamafran** [comment]
```
[DisplayName("Table Type"), Size(50), NotNull, QuickFilter,LookupEditor(typeof(TableTypeEditor))]
public String TableType
{
      get { return Fields.TableType[this]; }
      set { Fields.TableType[this] = value; }
}

```

**Comment by lushmana** [comment]
No go...

Error	1	The type or namespace name 'TableTypeEditor' could not be found (are you missing a using directive or an assembly reference?)

**Comment by volkanceylan** [comment]
First, put your editor type under your project namespace, e.g.

```
namespace MyProject {
 @Serenity.Decorators.registerEditor()
    export class TableTypeEditor extends Serenity.Select2Editor<any, any> {
....
}
```

Then build, transform templates, and use it:

```
[DisplayName("Table Type"), Size(50), NotNull, QuickFilter, TableTypeEditor]
public String TableType
{
      get { return Fields.TableType[this]; }
      set { Fields.TableType[this] = value; }
}
```

**Comment by abelal83** [comment]
Thanks guys, I'm having an issue still...

I've created 

```
namespace serene.Deskside {

    @Serenity.Decorators.registerEditor()
    export class OutlookDelegateRequestsItemTypeSelect extends Serenity.Select2Editor<any, any> {

        constructor(hidden: JQuery) {
            super(hidden, null);

            this.addItem("Calendar", "Calendar");
            this.addItem("Inbox", "Inbox");
        }
    }
```
and added after build and transform

```
        [DisplayName("Item Type"), Size(10), OutlookDelegateRequestsItemTypeSelect]
        public String Itemtype
        {
            get { return Fields.AccessType[this]; }
            set { Fields.AccessType[this] = value; }
        }
```

builds pass however, when I load the dialog and select Item Type it never loads, checking Chome console I see an error "Uncaught TypeError: Cannot read property 'toUpperCase' of undefined."

Any ideas?

**Comment by volkanceylan** [comment]
Why is your namespace is lowercase

**Comment by abelal83** [comment]
When I created the original project I did so in lowercase, would that be the cause?

**Comment by abelal83** [comment]
Going through the call stack I notice the call to markMatch passes result.text, result object itself is the value but .text is undefined? That doesn't seem right.

**Comment by volkanceylan** [comment]
Hmm, Saltaralle / TypeScript mapping issue. 

Try addItem({id: 'x', text: 'abc'})

Lowercase namespaces might create trouble, a lot.

**Comment by abelal83** [comment]
Cool will try that, in the meantime I'mrecreating my project using uppercase Serene :)

**Comment by abelal83** [comment]
So I've modified but another error

```
namespace Serene.Deskside {

    @Serenity.Decorators.registerEditor()
    export class OutlookDelegateRequestsItemTypeEditor extends Serenity.Select2Editor<any, any> {

        constructor(hidden: JQuery) {
            super(hidden, null);

            //this.addItem({ id: 'Calendar', text: 'Calendar' });  
            this.addItem({ id: 'Calendar', text: 'Calendar' }); 
.....
```

warning TS2345: Argument of type '{ id: string; text: string; }' is not assignable to parameter of type 'Select2Item'. It requires Source?

**Comment by volkanceylan** [comment]
Just cast to any.

**Comment by volkanceylan** [comment]
You could write 
<any>{id: ..., text: '...' } 
or 
{id: ..., text: '...', source: null, disabled: false }

Fixed in 2.4.11 also, separated into addItem and addOption.

**Comment by abelal83** [comment]
great, i've used second option which does the trick.

Can I update serene via package manager now and take advantage of the fix?

**Comment by volkanceylan** [comment]
Yes, you can

**Comment by volkanceylan** [comment]
Also added a sample in 2.4.11.3

**Comment by Boumboumjack** [comment]
The question and answer are great, thank you!

Is there a field we could use to translate to client.tt a cs file (like enumkey) to avoid the hard coded part: using description attribute as text and property as value?

Thank you for the amazing work!

**Comment by volkanceylan** [comment]
Nope, as long as you write on yourself.

**Comment by c9482** [comment]
I created the following custom editor, transformed at T4 templates but no attribute is generated in ClientTypes.tt. Consequently, I cannot reference RequestStatusEditor in my row class. Followed all the above instructions, what did I miss?

```
namespace LCPermits.Default
{
    @Serenity.Decorators.registerClass()
    export class RequestStatusEditor extends Serenity.Select2Editor<any, any>
    {
        constructor(hidden: JQuery)
        {
            super(hidden, null);
            this.addItem({ id: "Pending", text: "Pending" });
            this.addItem({ id: "Issued", text: "Issued"});
            this.addItem({ id: "Denied", text: "Denied"});
        }
    }
}
```

**Comment by abelal83** [comment]
check under imports\clienttypes\CleintTypes.tt if LCPermits.Default.cs exists, if so ensure in your row.cs file you are importing the correct namespace

**Comment by c9482** [comment]
Thanks but the problem was that I used "@Serenity.Decorators.registerClass()" instead of "@Serenity.Decorators.registerEditor()". I did not notice the hard coded values sample which gave me a clue.

**Comment by Shraddha996** [comment]
thanks @c9482  Now I can set hardcoded values for dropdown
But I want to open new dialog on the selection of dropdown value
Is It Possible in serenity framework?

**Comment by c9482** [comment]
Almost anything is possible with Serenity framework. However, I am not sure how do it. Perhaps some of the more advanced users will help you. All the best.

**Comment by Shraddha996** [comment]
okay. @c9482  thank you.

**Comment by wildanmuhlis2** [comment]
Hi, how to make the hardcode list description shown in grid column? currently grid showing data Id
