### ISSUE TITLE
Grid not loading data once IsActive has been implemented

### ISSUE THREAD

**Issue by lushmana** [volkanceylan/Serenity#1277]
I have cloned the functionality from the Users grid to implement the IsActive interfaced, however Slick Grid is not actually showing the records that the bottom display is telling me is returns!

**Comment by awesomegithubusername** [comment]
Any errors in Console?

**Comment by lushmana** [comment]
No errors in console... just no data in grid!!

![capture](https://cloud.githubusercontent.com/assets/22635566/19135700/5d7626bc-8bb2-11e6-8b81-14a37269752a.PNG)

**Comment by volkanceylan** [comment]
Check browser console.
