### ISSUE TITLE
Custom error message on exceptions

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1279]
When I save an entity which violets the unique key constraints it says something like this:

Cannot insert duplicate key row in object 'yms.Container' with unique index 'IX_Container_ContainerNo'. The duplicate key value is (CSQU305420100).
The statement has been terminated.

How can I show "Already exists" or something simpler message for this particular exception?

**Comment by volkanceylan** [comment]
Add a [Unique] attribute so service checks constraint first.

**Comment by dfaruque** [comment]
Perfect! :+1:

**Comment by dfaruque** [comment]
One more thing, what about foreign key violation message?

**Comment by volkanceylan** [comment]
See RegionRepository.cs delete handler.

**Comment by dfaruque** [comment]
thanks
