### ISSUE TITLE
Cast and Characters, not showing all rows fields

### ISSUE THREAD

**Issue by mantiklas** [volkanceylan/Serenity#1280]
![cast](https://cloud.githubusercontent.com/assets/21164515/19137851/844f25c6-8ba9-11e6-975e-888fedda6dee.PNG)

As I debug the code.. The CastList was retrieved correctly and completely . I don't know why it doesn't show all the fields and row. It shows only the last row. Please help me.. Thank you in anticipation.

**Comment by volkanceylan** [comment]
Open a developer console while you see this, and write

```
$('.s-DataGrid').last().triggerHandler('layout')
```

See if it resolve issue

**Comment by mantiklas** [comment]
@volkanceylan  It didn't work  or I was wrong in executing your solution.. But when I exaggerate the width  of the column.. that made the horizontal scrollbar  visible. Weird, but it works...

![newcast2](https://cloud.githubusercontent.com/assets/21164515/19177735/5e44089e-8c7e-11e6-9a2a-8d3c35b3a3f7.PNG)
![newcast](https://cloud.githubusercontent.com/assets/21164515/19177736/5ea18a14-8c7e-11e6-8785-132f0c038bdc.PNG)

**Comment by volkanceylan** [comment]
```
onDialogOpen() {
    super.onDialogOpen();
    this.form.ProductCodes.element.triggerHandler('layout');
}
```

**Comment by mantiklas** [comment]
@volkanceylan  I tried but unfortunately,  not yet working..  I just let the horizontal scrollbar visible for the meantime.. Thanks for the help, I'll share it here if I find out the solution..

**Comment by mantiklas** [comment]
@volkanceylan when i transform all template .. my visual studio crash..

**Comment by VictorTomaili** [comment]
#1179 Crash when t4 transform

**Comment by mantiklas** [comment]
Wow it works,, Last Question..  If I Checked-in this to TFS, and get latest by my team.. Will it affect their solution?  Some of my team have visual studio update 2... but my visual studio is update 3... thanks

**Comment by volkanceylan** [comment]
No it won't affect.
