### ISSUE TITLE
typescript sourcemap debug not working

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#1281]
Hi,

I know that it is more link to typescript issue, but does anyone of you had an issue debugging typescript with IE11? ( no symbols have been loaded)

The sourcemap is created, the link to the source map is created too(//# sourceMappingURL=MySite.Web.js.map), but ie seems unable to load it.

F12 in ie11 shows that the sourcemap was not found, even after cleaning up the history.

VS 2015 Update 3.

Thank you if you have any idea.

**Comment by volkanceylan** [comment]
I don't think IE11 is good at source mapping / debugging. Maybe Edge, or better Chrome/Firefox.

**Comment by Boumboumjack** [comment]
OK, I agree with you, thank you, I ll try to convince security guys :/
