### ISSUE TITLE
Open Form Dialog

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#1282]
How do I open the form Dialog directly without going through the Grid.
Example: I have the product form to register a new product, I click on Product menu opens the grid listing the products then click on the "NEW Product" button, then opens the formuário for the record.
I want to open the registration form directly without going through the grid form.

When you open within the grid by clicking on the new page button to enter the data appears.
the images below the grid and the new button that appears when you click the window "NovoDialog"

The form opens by clicking the button as shown below.
http://imgur.com/2FO5LD9

I want to open this form below directly without clicking the "NEW Dialog"
http://imgur.com/0FeOepz

`<div class="page-content">
    <div id="PedidoNovoDialog"></div>

</div>
<script type="text/javascript">
    $(function () {
        new Combens.Pedidos.PedidoNovoDialog($('#PedidoNovoDialog')).init();
    });

</script>`

**Comment by Estrusco** [comment]
new xyzDialog().loadEntityAndOpenDialog()
            new xyzDialog().loadByIdAndOpenDialog()
            new xyzDialog().loadNewAndOpenDialog()

**Comment by juliermefelix** [comment]
sorted out.
thank you
