### ISSUE TITLE
set JSON/htmlTable as Tooltip content

### ISSUE THREAD

**Issue by manivishnupriya** [volkanceylan/Serenity#1283]
![image](https://cloud.githubusercontent.com/assets/20909626/19170968/8004bee2-8be8-11e6-9e83-3d3d21db80df.png)
IN Grid:
In a Column, each row has a JSON data. when mouse is hovered, that JSON has to be displayed as a table   for few seconds. It can be shown as a tooltip or by any other means. 
Right now the contents of 'title' attribute is shown as  tooltip. Please help me on how to set the tooltip as htmltable.

**Comment by volkanceylan** [comment]
Please try slickgrid examples
