### ISSUE TITLE
Error when creating a new project using Serenity template for VS Studio 2013

### ISSUE THREAD

**Issue by WestleyHoxton** [volkanceylan/Serenity#1284]
Hi

Let me first commend you on this application template you created. It is indeed very professional. A little about myself. I am in BI/Data warehouse space and while I do program in c# it is specific to SSIS component.
I have created a framework in SSIS for automating ETL and I needed a front end Admin GUI to maintain the ETL meta data and that is where I found your application very useful.
Please excuse my ignorance as I have very limited knowledge in the world of ASP.net.

Okay. So here is my problem. I created a test project in VS 2013 using the latest Serenity template and it worked very well and got my hands dirty from the tutorial you supplied. I then decided to get a little more into it and created a new project the same way I created the first one. But this time I get an error as seen in the picture I attached. I restarted the machine and tried again only to get the same issue.

Based on the information, can you tell where am I going wrong. I can provide more information if you only I know where to find more. 

Thank you in advance fro your help

regards

Westley
![error](https://cloud.githubusercontent.com/assets/22673494/19178945/07ad74b8-8ca4-11e6-83a3-56e548976c6f.jpg)

**Comment by WestleyHoxton** [comment]
HI

Further to my earlier post, I researched this folder and found it to be empty. I'm not sure if this information help

Thanks

Westley

**Comment by volkanceylan** [comment]
There is an error in template, will fix it soon

**Comment by WestleyHoxton** [comment]
Hi

Appreciate your quick response. Will await the change.

Cheers

Westley

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Oct 7, 2016 at 5:11 PM +1100, "Volkan Ceylan" <notifications@github.com<mailto:notifications@github.com>> wrote:


There is an error in template, will fix it soon

-

**Comment by volkanceylan** [comment]
Fixed in 2.4.11.2. Either download latest version from VSGallery or update using VS extensions dialog.

**Comment by WestleyHoxton** [comment]
Man!!!!!! You are really quick :)

You are awesome.

Cheers

Westley

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Oct 7, 2016 at 5:29 PM +1100, "Volkan Ceylan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed in 2.4.11.2. Either download latest version from VSGallery or update using VS extensions dialog.

-
