### ISSUE TITLE
Any Serenity / Serene guidelines when contributing to the wiki?

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1285]
I intend to contribute how-to's or documentation to Serenity and the web template Serene later when I had the free time. Should we establish some ground rules on these, for others as well?

My initial thoughts on what to include when contributing to How-To's/Tutorials:
* Compatible Serenity Version/s: 
* Modules/Files Concerned:
* Instructions:
* Warnings/Important Notes:
* Examples (Code snippets):

**Comment by john20xdoe** [comment]
* Sources/Referenced Issues:

**Comment by volkanceylan** [comment]
We don't have a guideline yet. It would be nice to have one, but for now i hope to get more contributions. Your suggestions looks fine.

**Comment by john20xdoe** [comment]
I have added the list above to the wiki home. =)
