### ISSUE TITLE
Delete/Undelete/Localization/Clone buttons shown on New/Edit dialogs

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1286]
![funkynew](https://cloud.githubusercontent.com/assets/2817543/19207074/6819b368-8ca2-11e6-852f-cb4afe31e3dc.png)

One of my dialogs is showing all these buttons, even on New. I'm not overloading getToolbarButtons() in the MyDialog.ts...any idea why this is showing up, or where I might be short-circuiting the logic to hide/show them?

Not seeing this on any of my other dialogs and not seeing anything different about this one...

**Comment by volkanceylan** [comment]
Dont forget to call super.updateInterface, super.afterLoadEntity etc if you override them

**Comment by wldkrd1** [comment]
Yup, super.updateInterface() was missing. Thanks!
