### ISSUE TITLE
Problems capturing Accordion events

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1287]
After a lot of research, i can't seem to make a script that fires when an accordian is activated, any help ?

My tries so far:
1:
`    <script type="text/javascript">
        $('#accordionEstudos').accordion()
        .on('activate', function (event, ui) {
            alert('activate ' + ui.newHeader.text());
        });
    </script>`

2:
`    <script type="text/javascript">
       $('#accordionEstudos').accordion()
        .on('accordionactivate', function (event, ui) {
            alert('accordionactivate ' + ui.newHeader.text());
        });
    </script>`

3.
`        $(function () {
            $(".accordionEstudos")
                .on("change", function (e) {
              alert('TESTE);
                    });
        });`

My acordion code is:
<div class="box-group" id="accordionEstudos">
                    @foreach (var estudo in Model.Estudos)
                    {
                        if (Model.AreaInvestigacaoEscolhida != null && (estudo.AreaInvestigacaoId == Model.AreaInvestigacaoEscolhida.Id))
                        {
                            
                            <div class="panel box box-success">
                                <div class="box-header with-border">
                                    <h4 class="box-title">
                                        <a data-toggle="collapse" data-parent="#accordionEstudos" href=@("#collapse"+@estudo.Id)>
                                            @estudo.Descricao
                                        </a>
                                    </h4>
                                </div>
                                <div id=@("collapse"+@estudo.Id) class="panel-collapse collapse">
                                    <div class="box-body">
                                        @estudo.Notas
                                    </div>
                                    
                                    <div class="box-footer">
                                        Abra a <a id="fichaEstudo" href="#" title="@estudo.Id">ficha do estudo</a> para consultar a informação completa.
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>

I'm, asking this because can it be related to the jquery used in serenety, i can't seem to compreend this behaviour.

**Comment by volkanceylan** [comment]
jQuery used in Serenity is a standard one. I suggest you try your code first in an empty page with jQuery and UI included only.

**Comment by brunobola** [comment]
Thanks volkan, i've found the way doing:
 <script type="text/javascript">
        $(function () {
            //Eventos BootStrap : http://www.w3schools.com/bootstrap/bootstrap_ref_js_collapse.asp
            $('#accordionEstudos')
            .on("shown.bs.collapse", function (e) {
                //BootstrapDialog.show({
                //    title: 'TESTE',
                //    message: "Centro: " + $("#centro option:selected").val() + " - Área: " + (typeof ($("#area option:selected").val()) === "undefined" ? 0 : $("#area option:selected").val()) + "Estudo: " + (typeof ($('#accordionEstudos .in').parent().attr("id")) === "undefined" ? 0 : $('#accordionEstudos .in').parent().attr("id"))
                //});

                //alert($('#accordionEstudos .in').parent().attr("id") + "||" + $('#accordionEstudos .in').parent().index());

                //mostly used event, fired to the original element when the value changes
                //log($("#centro option:selected").val(), $("#area option:selected").val());

                window.location.href = '/CentroAcademicoAreaInvestigacaoEstudos/EscolheAreaIvestigacao/' + $("#centro option:selected").val() + '/' + (typeof ($("#area option:selected").val()) === "undefined" ? 0 : $("#area option:selected").val()) + '/' + (typeof ($('#accordionEstudos .in').parent().attr("id")) === "undefined" ? 0 : $('#accordionEstudos .in').parent().attr("id"));
            });
        });
    </script>
