### ISSUE TITLE
How to access grid row data on RowSelectionChange in grid.

### ISSUE THREAD

**Issue by joveb** [volkanceylan/Serenity#1288]
First of all I have to say that this is very powerful framework, especially for someone like me just starting to work with web apps. I have one question:
I want to display more details about a selected row in a grid, on the same page. Can you give me an example how to create "on row selection change listener", and get selected row data from a grid?

**Comment by volkanceylan** [comment]
@marcobisio can you help?

**Comment by marcobisio** [comment]
Glad to help @volkanceylan!

@joveb, assuming that you allow only single row selection, then in your grid you can do something like that:

    constructor(container: JQuery) {
        super(container);
    
        var grid = this.slickGrid;
        grid.onSelectedRowsChanged.subscribe(() => {
            var selectedRow = grid.getSelectedRows()[0];
            var supplierRow: Northwind.SupplierRow = grid.getDataItem(selectedRow);
            // get the phone...
            console.log(supplierRow.CompanyName + " - phone: " + supplierRow.Phone);
            // get the fax...
            console.log(supplierRow.CompanyName + " - fax: " + supplierRow.Fax);
            // ...and so on!
        });
    }

Have a nice weekend!
Bye

**Comment by joveb** [comment]
Perfect. Thank you.

**Comment by flextrio-gandhi** [comment]
The grid  contains columns like amount,name checkboxes etc.
so when i clicked any one or more   checkboxes  that particular rows amount should be calculated and display on grid footer.
