### ISSUE TITLE
Send context information to Dialog in tab for new insert

### ISSUE THREAD

**Issue by zeezment** [volkanceylan/Serenity#1289]
Hi Volkan,

I have a Supplier with multiple tabs and one of them represents the relationship between a Supplier and a Contact which maps onto a SupplierContacts table. I'm trying to add a new contact associated to a specific supplier but I can't seem to set the SupplierId to that save entity. The SupplierContactsDialog's constructor looks as follows:

`constructor(value: string) {
            super();
            this.form.SupplierId.value = value;
        }`

but this only sets the id for an edit dialog and not an insert dialog. How can I set the supplierId value for an insert dialog?

Thanks.

**Comment by Estrusco** [comment]
This is helpful?

https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog

**Comment by zeezment** [comment]
@Estrusco Thank you! Uber Helpful!
