### ISSUE TITLE
Question: What is the best way to pre-populate a field on a form (for a new entity)?

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#129]
Using the Northwind Database as an example, suppose you wanted pre-fill the Customer ID field for new Customers with the value of "XYZ".  How would you do that?

**Comment by volkanceylan** [comment]
Did you try DefaultValue attribute?

**Comment by brettbeard** [comment]
Yes.  Actually, I need to pre-populate a field with a value pulled from the database.  Not a static value.  (Sorry, I didn't mention that in my question.)

**Comment by volkanceylan** [comment]
You then need a service that will return those values. Then override AfterLoadEntity check if IsNew is true, call service if so, set field values by form.CustomerID.Value = xyz

**Comment by brettbeard** [comment]
So, I added the below code to CustomerDialog.cs.  I am attempting to pull data from the Employee table as an example.  It appears that the EmployeeRow does not contain much data.  In the code below, the "FirstName" field is empty.  What is the correct way to query data from a Dialog?

protected override void AfterLoadEntity()
{
     base.AfterLoadEntity();

     if (this.IsNew)
     {
           var row = EmployeeRow.Lookup.ItemById[1];                

           this.form.CustomerID.Value = string.Format("{0}", row.FirstName);
     }
}

**Comment by volkanceylan** [comment]
Add LookupInclude to fields u need.

**Comment by brettbeard** [comment]
Ah, that's what I was missing.  Thanks.
