### ISSUE TITLE
Hide Permissions from Users

### ISSUE THREAD

**Issue by Hochmah** [volkanceylan/Serenity#1291]
Firstly congrats from this amazing platform you develop! It's realy, realy amazing!

A have done all tutorials, and just started to migrate a legacy app to Serene.

I'm doing my best to figure out how implement by myself all features I find necessary along the way. And I'm achieving success in most of them. Thanks for the elegance Serene was concepted.

But now I'm struggling in an apparently silly requirement, that is: I need to hide permissions to language and translations to users that have security privileges, in the way they don't see this option when editing permissions for other users, neither being able to grant to themselves.

I'm sure I missing something obvious! Sorry for that!  
Thanks!

**Comment by volkanceylan** [comment]
You need to separate permissions for translations / other administration screens. If i remember right they were already different, e.g. Administration:Translation and Administration:Security.

See multi tenant guide for information on how to hide a permission conditionally.

**Comment by Hochmah** [comment]
Yeah the permission are already separeted. I'll try via multi tenant way.

**Comment by ga5tan** [comment]
@Hochmah why dont u just make group without those privileges?
