### ISSUE TITLE
Wrong edit dialog

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1292]
Hi, when i click on one of my XYZ grid edit link ([EditLink]) object, i get my "Add New" XYZ dialog whith the same data of that object that i clicked. How can i resolve this issue? I need my edit dialog, not copy from other. Thanks in advance.

**Comment by marcobisio** [comment]
Hi @alanlopcu, share your code otherwise we cannot help you...
EditLink are working fine since the beginning of time, so probably there is something wrong with you entity and/or the related PK.

**Comment by alanlopcu** [comment]
Ok, im sorry, was my fault. I forgot use:

protected getNameProperty() { return InspectionRow.nameProperty; }
protected getNameProperty() { return InspectionRow.nameProperty; }

On my XYZDialog.ts . Thank you.

I have another question: how can i "Add Inline Action Buttons To Grid"? 
(This section is pending update for TypeScript)

I got multiple errors using:

```
protected override List<SlickColumn> GetColumns()
        {
            var columns = base.GetColumns();

            columns.Add(new SlickColumn
            {
                Field = "DeleteRow",
                Title = "",
                Format = ctx =>
                {
                    return "<a class='inline-action delete-row' title='delete'></a>";
                },
                Width = 24,
                MinWidth = 24,
                MaxWidth = 24                
            });

            return columns;
        }
```
Thanks again.

**Comment by alanlopcu** [comment]
#1297
