### ISSUE TITLE
SQL Syntax for OnBeforeExecuteQuery

### ISSUE THREAD

**Issue by lushmana** [volkanceylan/Serenity#1293]
I'm trying to create a subselect query against my table against itself as the table contains it's own history so  I want my query to only return the current version of each record. I need to build up a query object which results in a query statement like this:
```
SELECT TOP 100 
T0.[ConnectionHash] AS [ConnectionHash],
T0.[VersionID] AS [VersionId],
T0.[ConnectionName] AS [ConnectionName],
T0.[DatabaseType] AS [DatabaseType],
T0.[ProviderName] AS [ProviderName],
T0.[BIMLProviderName] AS [BimlProviderName],
T0.[ConnectionString] AS [ConnectionString],
T0.[IsDeleted] AS [IsDeleted],
T0.[IsActive] AS [IsActive],
T0.[UserCreated] AS [UserCreated],
T0.[DateTimeCreated] AS [DateTimeCreated],
T0.[UserModified] AS [UserModified],
T0.[DateTimeModified] AS [DateTimeModified] 
FROM [meta].[Connection_V] T0 
JOIN (SELECT 
                 ConnectionHash,
                 MAX(VersionID) AS VersionID 
            FROM [meta].[Connection_V] 
     GROUP BY ConnectionHash ) mv
     ON ((mv.[ConnectionHash] = T0.[ConnectionHash]) AND (mv.[VersionID] = T0.[VersionID])) 
ORDER BY T0.[ConnectionName], T0.[VersionID];

```I've been fighting with this syntax for days, driving me nuts!

**Comment by marcobisio** [comment]
Hi @lushmana, where are you trying to apply such syntax?
For example in your xyzRepository you can override the ApplyFilters method:

    private class MyListHandler : ListRequestHandler<MyRow>
    {
        protected override void ApplyFilters(SqlQuery query)
        {
            base.ApplyFilters(query);
            var fld = MyRow.Fields;
    		var fldXyz = xyzRow.Fields;
    		query.Where(new Criteria(fld.FIELD_1) == "MY_VAL" &
    			fld.FIELD_2.In(
    				query.SubQuery()
    					.Select(fldXyz.FIELD_2)
    					.From(fldXyz)
                        .Where(MY_CRITERIA)));
    	}
    }

It's just a sample in order to explain how you can use a subquery...
Bye

**Comment by lushmana** [comment]
My issue is not where to apply the adjusted query but, how o define the syntax, I need the subquery to be based off a join not a where condition, as my join is based on multiple columns.

**Comment by volkanceylan** [comment]
On top of row add 

[OuterApply("xyz", "SELECT ConnectionHash, MAX(VersionID) AS VersionID FROM ...")]

Then add some view fields and set their expression to xyz.ConnectionHash etc.
