### ISSUE TITLE
Reciprocity of records in the same table

### ISSUE THREAD

**Issue by arielkpo40** [volkanceylan/Serenity#1296]
Sorry for my English...
Within a TagRow there is a list field containing RelacionRow as seen following:

![image](https://cloud.githubusercontent.com/assets/22621014/19279150/8bf74626-8fb6-11e6-8c71-9f1495f63c8a.png)

In front-end is seen in the following way:

![image](https://cloud.githubusercontent.com/assets/22621014/19279163/9b1827ba-8fb6-11e6-9def-c52a2d441fec.png)

When loading a relationship to the Tag Form (in this case the TagForm "Diego Maradona") clarifies a "relationship Type Name" and "Relationship Tag Description" (in this case, "Ex pareja" and "Claudia Villafane").

So, In the Tag Form of Claudia Villafane I need to see the relationship with the Tag Form Diego Maradona.

Appreciative of any help.

**Comment by volkanceylan** [comment]
Sorry but couldn't understand your question.
