### ISSUE TITLE
Add Inline Action Buttons To Grid

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1297]
How can i "Add Inline Action Buttons To Grid"? ("This section is pending update for TypeScript")

I got multiple errors using:

```
protected override List<SlickColumn> GetColumns()
        {
            var columns = base.GetColumns();

            columns.Add(new SlickColumn
            {
                Field = "DeleteRow",
                Title = "",
                Format = ctx =>
                {
                    return "<a class='inline-action delete-row' title='delete'></a>";
                },
                Width = 24,
                MinWidth = 24,
                MaxWidth = 24                
            });

            return columns;
        }
```
In my XYZGrid.ts . I need to remove records using this delete link "button".

Thanks again.

**Comment by receptuna** [comment]
protected getColumns(): Slick.Column[] {

            var columns = super.getColumns();
            columns.push(
                {
                    field: "UpdateDoctorInfo",
                    name: "",
                    format : ctx => {
                        return "<a class='inline-action delete-row' title='delete'></a>";
                    },
                    width : 24,
                    minWidth : 24,
                    maxWidth : 24
            });

            return columns;
        }

**Comment by alanlopcu** [comment]
Thank you it works!
