### ISSUE TITLE
Filter on dropdown

### ISSUE THREAD

**Issue by CarlosDias7** [volkanceylan/Serenity#1298]
Recently I added a Region field and a Territoy field in Order form.
How can I add a Region filter on Territory dropdown in Order Form?

Sample: An user selects some Region on the Region dropdown, so in the Territory dropdown only appears  territories from that Region.

**Comment by iuryamicussi** [comment]
Man, I'm having the same problem in my application.
Anyone?

**Comment by awesomegithubusername** [comment]
You can use [cascaded lookups](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html)
