### ISSUE TITLE
How to make NavBar always colapsed

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1299]
Any tip from you guys would be appreciated, i tried several changes in _Layout but it must be a simple thing and i've got no time because tomorrow i've got a presentation and still a lot of features to do.

If anyone know please give me a tip.

**Comment by Hochmah** [comment]
Add the sidebar-collapse class to the body tag.

**Comment by brunobola** [comment]
Thanks

**Comment by brunobola** [comment]
I put it like so: $('body').addClass('sidebar-collapse');
Others might need.
Thanks again.
