### ISSUE TITLE
Serenity .Net 4.0

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1300]
Hi, can i assemble or deploy this framework using .Net 4.0 or targetFramework="net40"? I got Razor,Mvc and WebPages errors when i try to change the target . I have 2008 R2 Windows Server. Thanks again.

**Comment by brunobola** [comment]
Why can't you install .net 4.5 Windows Server support it, going backward is not an answer.

**Comment by alanlopcu** [comment]
IT Policies :/ . So, Serenity F. can't be assembled it in .Net 4.0? Or which Razor, WebPages, Mvc versions should i use? Thanks again.

**Comment by volkanceylan** [comment]
It might work using bindings etc, some possiblity, but this is not Serenity specific, you need to google it
