### ISSUE TITLE
[HowTo] AdminLTE LeftNavigation Counters

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1301]
Dear all,
in this simple guide I'll explain how to add some kind of "counters" in the left menu of AdminLTE (see screenshot below). Those counters will be "calculated" every time you navigate between different pages, but also they will be periodically refreshed.

![image](https://cloud.githubusercontent.com/assets/17425690/19300983/6c03d936-905d-11e6-8235-24c193c23498.png)

Here we go:

**1) DashboardPageModel.cs:** the dashboard already contains a cached model and some counters, so it seems to be a good place to start:
    
    namespace DueQuattroUndici.Common
    {
        public class DashboardPageModel
        {
            public int OpenOrders { get; set; }
            public int ClosedOrderPercent { get; set; }
            public int NorthwindCustomerCount { get; set; }
            public int NorthwindOrderCount { get; set; }
            public int NorthwindProductCount { get; set; }
            public int NorthwindSupplierCount { get; set; }
            public int NorthwindShipperCount { get; set; }
            public int NorthwindCategoryCount { get; set; }
            public int NorthwindRegionCount { get; set; }
            public int NorthwindTerritoryCount { get; set; }
        }
    }

**2) DashboardPage.cs:** now that I've the model, I can retrieve the data and fill the model. Also here I've added a "GetCounters" get method that returns the serialized (JSON) model:
    
    namespace DueQuattroUndici.Common.Pages
    {
        using Northwind;
        using Northwind.Entities;
        using Serenity;
        using Serenity.Data;
        using Serenity.Services;
        using System;
        using System.Web.Mvc;
        using System.Web.Security;
    
        [RoutePrefix("Dashboard"), Route("{action=index}")]
        public class DashboardController : Controller
        {
            //[Authorize, HttpGet, Route("~/")]
            public DashboardPageModel GetCachedModel()
            {
                var cachedModel = TwoLevelCache.GetLocalStoreOnly("DashboardPageModel", TimeSpan.FromMinutes(5),
                    OrderRow.Fields.GenerationKey, () =>
                    {
                        var model = new DashboardPageModel();
                        var o = OrderRow.Fields;
                        using (var connection = SqlConnections.NewFor<OrderRow>())
                        {
                            model.OpenOrders = connection.Count<OrderRow>(o.ShippingState == (int)OrderShippingState.NotShipped);
                            var closedOrders = connection.Count<OrderRow>(o.ShippingState == (int)OrderShippingState.Shipped);
                            var totalOrders = model.OpenOrders + closedOrders;
                            model.ClosedOrderPercent = (int)Math.Round(totalOrders == 0 ? 100 :
                                ((double)closedOrders / (double)totalOrders * 100));
    
                            model.NorthwindCustomerCount = connection.Count<CustomerRow>();
                            model.NorthwindOrderCount = connection.Count<OrderRow>();
                            model.NorthwindProductCount = connection.Count<ProductRow>();
                            model.NorthwindSupplierCount = connection.Count<SupplierRow>();
                            model.NorthwindShipperCount = connection.Count<ShipperRow>();
                            model.NorthwindCategoryCount = connection.Count<CategoryRow>();
                            model.NorthwindRegionCount = connection.Count<RegionRow>();
                            model.NorthwindTerritoryCount = connection.Count<TerritoryRow>();
                        }
                        return model;
                    });
    
                return cachedModel;
            }
    
            [Authorize, HttpGet, Route("~/")]
            public ActionResult Index()
            {
                return View(MVC.Views.Common.Dashboard.DashboardIndex, GetCachedModel());
            }
    
            [Authorize, HttpGet]
            public string GetCounters()
            {
                return JSON.Stringify(GetCachedModel());
            }
        }
    }

**3) LeftNavigation.cshtml:** finally I've added some css classes to the left menu items and also I've added a javascript that periodically invoke the "GetCounters" method of the Dashboard controller and set those values in the DOM:

    @model DueQuattroUndici.Navigation.NavigationModel
    
    @helper renderItem(Serenity.Navigation.NavigationItem item, int depth, int[] path, string category) {
    
    var isactive = true;
    for (var i = 0; i <= depth; i++)
    {
        if (path[i] != Model.ActivePath[i])
        {
            isactive = false;
            break;
        }
    }
    
    var klass = (isactive ? "active" : "") + (item.Children.IsEmptyOrNull() ? "" : " treeview");
    var icon = (item.IconClass ?? (item.Children.Count > 0 ? "icon-layers" : (depth == 0 ? "icon-link" : "fa-circle-o")));
    var title = (LocalText.TryGet("Navigation." + category + item.Title) ?? item.Title);
    var sectionUrl = (item.Url ?? "javascript:;");
    var target = item.Target; if (target != null) { target += " target=" + target; }
    
    <li class="@klass">
        <a href="@sectionUrl"@target>
            <i class="fa @(icon)"></i>
            <span>@title</span>
            @if (!item.Children.IsEmptyOrNull()) {
            <i class="fa fa-angle-left pull-right"></i>
            }
            else
            {
                var url = item.Url;
                var cssClass = string.Empty;
                var module = "/Northwind";
                if (url.Contains(module))
                {
                    url = url.Substring(url.LastIndexOf(module));
                    cssClass = (url.Replace("/", "") + "count").ToLower();
                    <small class="label label-primary pull-right @cssClass">
                        -
                    </small>
                }
            }
        </a>
    
        @if (item.Children.Count > 0)
        {
            <ul class="treeview-menu">
            @{path[depth + 1] = 0; }
            @foreach (var child in item.Children) {
                @renderItem(child, depth + 1, path, category + item.Title + "/");
            }
            </ul>
        }
    </li>
    path[depth]++;
    }
    
    @{var path = new int[10]; }
    @foreach (var item in Model.Items)
    {
        @renderItem(item, 0, path, "");
    }
    
    <script type="text/javascript">
        function openWindow(url, width, height) {
            height = height || (screen.availHeight - 60);
            width = width || (screen.availWidth - 10);
            var x = (screen.availWidth - width) / 2 - 5; if (x < 0) x = 0;
            var y = (screen.availHeight - height) / 2 - 25; if (y < 0) y = 0;
            var winPopup = window.open(url, "", "status=0, toolbar=0, width=" + width + ", height=" + height +
                ", scrollbars=1, resizable=yes, left=" + x + ", top=" + y);
        }
    
        function updateCounters() {
            var actionUrl = '@Url.Action("GetCounters", "Dashboard")';
            $.get(actionUrl, function (result) {
                var tmp = JSON.parse(result);
                Object.keys(tmp).forEach(function (key) {
                    $(('.' + key).toLowerCase()).html(tmp[key]);
                });
                
            });
        }
        // force the first counters refresh
        updateCounters();
        // start a timed refresh
        window.setInterval(updateCounters, 10000);
    </script>

Honestly I don't know if it's the best/right approach, but it's working fine in my application...btw I'm open to any kind of comment/suggestion/feedback!

Edit: note that the cached model will be refreshed every 5 minutes (TimeSpan.FromMinutes(5)), so the window.setInterval set to 10 seconds is useless because for 5 minutes the counters will not be refreshed (because the controller returns the cached values), so set those two values accordingly!

Hope it helps...
That's all folks!
Bye

**Comment by sayuga** [comment]
Nice, I can make great use of this. You should put it in the Wiki. Thank you. @marcobisio

**Comment by volkanceylan** [comment]
Another good one @marcobisio.

**Comment by Estrusco** [comment]
Thank you very much @marcobisio !

**Comment by marcobisio** [comment]
Thanks @volkanceylan!

You're welcome @estrusco :-)

**Comment by awesomegithubusername** [comment]
Thanks @marcobisio !

**Comment by marcobisio** [comment]
I think that can be closed...I'll put all this stuff in a wiki page :-)

Bye

**Comment by ANDY7575** [comment]
@marcobisio  how to check for 2 conditions while retrieving count.
any help is Appreciated ..thank you.

**Comment by marcobisio** [comment]
Hi @ANDY7575,
do you mean a condition for the count?
Something like this:

    connection.Count<OrderRow>(o.ShippingState == (int)OrderShippingState.NotShipped);

Bye
