### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: userDefinition

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1302]
Dear @volkanceylan,
sometime I get the following error in console:

![image](https://cloud.githubusercontent.com/assets/17425690/19309552/d8c074b2-9085-11e6-8b9c-f5518903ec34.png)

I know that it's impossible to guess what's wrong without see all my code, but I really have no idea on what could be the problem or where start looking for...
In your experience, what can produce those kind of error?
From console I tried to call the GetUserData and the response seems to be ok...

![image](https://cloud.githubusercontent.com/assets/17425690/19309692/d63b8a3c-9086-11e6-868c-1fc3692dac05.png)

Any idea on what I can try to do in order to debug this thing?

Edit: digging digging I found that such error it's related to the "Object.defineProperty()" in Authorization.ts, but once again I don't know why...

Thank you very much for your support
Bye

**Comment by brunobola** [comment]
Did you update jQuery?

**Comment by marcobisio** [comment]
@brunobola currently I've version 2.2.3 while in the version in the base project is 2.2.0...
Do you think that I should try a downgrade?

Thanks

**Comment by volkanceylan** [comment]
This looks like same code that registering some propert is loading twice. Cant guess which but you might have duplicate items in bundle. E.g. Serenity.CoreLib.js separate and in bundle
 Check html source.

**Comment by marcobisio** [comment]
I checked the json bundle config file twice and it seems to be ok:

    {
      "Libs": [
        "~/Scripts/pace.js",
        "~/Scripts/rsvp.js",
        "~/Scripts/jquery-{version}.js",
        "~/Scripts/jquery-ui-{version}.js",
        "~/Scripts/jquery-ui-i18n.js",
        "~/Scripts/jquery.validate.js",
        "~/Scripts/jquery.blockUI.js",
        "~/Scripts/jquery.cookie.js",
        "~/Scripts/jquery.json.js",
        "~/Scripts/jquery.autoNumeric.js",
        "~/Scripts/jquery.colorbox.js",
        "~/Scripts/jquery.dialogextendQ.js",
        "~/Scripts/jquery.event.drag.js",
        "~/Scripts/jquery.scrollintoview.js",
        "~/Scripts/jsrender.js",
        "~/Scripts/select2.js",
        "~/Scripts/sortable.js",
        "~/Scripts/toastr.js",
        "~/Scripts/SlickGrid/slick.core.js",
        "~/Scripts/SlickGrid/slick.grid.js",
        "~/Scripts/SlickGrid/slick.groupitemmetadataprovider.js",
        "~/Scripts/SlickGrid/Plugins/slick.autotooltips.js",
        "~/Scripts/SlickGrid/Plugins/slick.headerbuttons.js",
        "~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js",
        "~/Scripts/SlickGrid/Plugins/slick.rowmovemanager.js",
        "~/Scripts/bootstrap.js",
        "~/Scripts/Saltarelle/mscorlib.js",
        "~/Scripts/Saltarelle/linq.js",
        "~/Scripts/Serenity/Serenity.CoreLib.js",
        "~/Scripts/Serenity/Serenity.Script.UI.js",
        "~/Scripts/Serenity/Serenity.Externals.js",
        "~/Scripts/Serenity/Serenity.Externals.Slick.js",
        "~/Scripts/jquery.cropzoom.js",
        "~/Scripts/jquery.fileupload.js",
        "~/Scripts/jquery.iframe-transport.js",
        "~/Scripts/jquery.slimscroll.js",
        "~/Scripts/mousetrap.js",
        "~/Scripts/fastclick/fastclick.js",
        "~/Scripts/bootstrap-multiselect.js",
        "~/Scripts/bootbox.js",
        "~/Scripts/jquery.signalR-2.2.0.js"
      ],
      "Site": [
        "~/Scripts/adminlte/app.js",
        "~/Scripts/Site/eService.Web.js"
      ]
    }

I tried to put a breakpoint clientside (on Chrome I mean) and such piece of code:

    Object.defineProperty(Authorization, 'userDefinition', {
        get: function () {
            return Q.getRemoteData('UserData');
        }
    });

is "hit" only once.
Moreover I checked also that in the sources such object definition has only one occurence.

The strange thing is that 99% of the time my application is working fine without any kind of error and suddenly (and rarely) it stops working with the error of the my first post.
I'm still digging but as a temporary workaround I have modified the code above in the following way:

    Object.defineProperty(Authorization, 'userDefinition', {
        get: function () {
            return Q.getRemoteData('UserData');
        },
        enumerable: true,
        **configurable: true**
    });

So if the object somehow will be redefined, it should be ok...

Thanks for your support
Bye

**Comment by volkanceylan** [comment]
Thanks, i removed that one, some leftover from old project. 

Anyway i'm pretty sure one of your scripts is loading twice sometimes, some ajax call might be the issue.

**Comment by marcobisio** [comment]
Uhm interesting...what kind of ajax call?  I use only your service calls (and a "get" for the counter like the sample that I've posted before).
Perhaps I use the clientside "userDefinition" too "early"? It make any sense to you?

Thanks as usual for your feedback
Bye
