### ISSUE TITLE
Sergen failure

### ISSUE THREAD

**Issue by psrleite** [volkanceylan/Serenity#1303]
Hi, I'm starting with Serene. I am using the Movie Tutorial, but when Sergen starts, the window is frozen with the message "Sergen is not responding."

Any idea?

Thank you!

PAULO LEITE

**Comment by volkanceylan** [comment]
Probably some problem with your PC, antivirus etc.

**Comment by sayuga** [comment]
I know that at times  Sergen start on my system.  Usually, closing and re-opening the project then running it again will allow it to run. Not really sure why but it works for me.

**Comment by Estrusco** [comment]
Check also the connection string in web.config

**Comment by psrleite** [comment]
Solved, it works by run as Administrator.
