### ISSUE TITLE
Row.OriginalValues, Row.PreviousValues and ExecuteSave()

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1304]
What's the difference between Row.OriginalValues and Row.PreviousValues?

Also, I notice that they both contain the new values to be saved when ExecuteSave() is entered, so Row.IsFieldChanged() and IsAnyFieldChanged returns false. Is this intended?

**Comment by volkanceylan** [comment]
They are designed work with WPF/Winforms components like DX, Telerik etc. with data binding, and row editing. They only work when used along with BeginEdit, EndEdit... 

They have no use in web service environment.

**Comment by wldkrd1** [comment]
Thanks for the clarification!
