### ISSUE TITLE
Additional Filters on Stored Procedure Grid

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1305]
Can we extend the Grid populated by a Stored Procedure to be used in such a manner that if we set Filterable property and based on different argument received from request we can dynamically send them as argument to stored procedure.

or otherwise we can set QuickFilter property of a column and based on its value we can send the additional parameter to the stored procedure.

**Comment by volkanceylan** [comment]
You can't or shouldn't let arbitrary criteria get passed to a stored proc as string, it's unsafe. 

Quick filter values are passed through EqualityFilter in list request as a dictionary. See if you can take them and pass to your stored proc.

I strongly recommend you avoid stored procs.

**Comment by mrajalko** [comment]
Thanks @volkanceylan for your insight.

What Other alternatives are your suggesting for complex report containing summary columns and joining more than 4 tables grouping also on multiple columns.

**Comment by volkanceylan** [comment]
Views comes to mind, or write your query directly with Dapper and/or SqlQuery

**Comment by mrajalko** [comment]
Thanks i would try on those lines also, meanwhile I am more comfortable in stored procedures.

It keeps my code clean and more readable and complexity of the query remains in stored procedure.

thanks for your valuable suggestions.

**Comment by aksingh1979** [comment]
I agree with mrajalko and believe to make applications more maintainable and scalable, stored procedures are must. Am having millions of records in table and feeling the pain it takes to resolve the timeout from SQL server for some reason

**Comment by mrajalko** [comment]
Thanks @aksingh1979. Serenity is great product and we should all be very thankful to @volkanceylan

**Comment by aksingh1979** [comment]
Of course, no doubt. I was thinking from point of improvement, if it make sense and what others are thinking for stored procedure. I am always the sql procedure fan.

**Comment by mrajalko** [comment]
same here. I also consider myself admirer of Stored Procedures. I would work out something and revert on this forum.

**Comment by volkanceylan** [comment]
If your queries are timing out, thats not because of Serenity, but missing indexes, lack of optimization or poor design.

**Comment by aksingh1979** [comment]
Thanks Volkan, I could have agreed with you before looking at SQL Profiler but when I see the way filters are being interpreted and sent to SQLDB, thats where I feel lack of knowledge in Serenity. 

To give you an example...one column in grid is  expression based such as
Expression["(CASE WHEN JoinDate is NULL then 1 ELSE 0 END)"]. I notice this becomes part of SELECT as well as WHERE clause. In WHERE clause it looks like (CASE WHEN JoinDate is NULL then 1 ELSE 0 END)=@p1 when filter is applied on it. I would like to leave the SELECT part but would like the WHERE part to be something like JoinDate Is Not Null or JoinDate is Null based on filter. 

Can you please advice how can I manipulate the WHERE clause to my convenience? I just want the filter to be as simple as JoinDate is NULL when filter is passed as 1 and JoinDate is not NULL when filter passed as 0. That interpretation of expression is not working at all in where clause. There is a huge huge huge difference in performance of query.

Appreciate your reply.

**Comment by volkanceylan** [comment]
There is something called persistent calculated fields in sql which can be indexed. Anothet option is having a look at custom quick filters sample. Another is ovetride applyfillters and convert equality filter to isnull and remove it from request equality filter dictionary. Need more??

**Comment by aksingh1979** [comment]
Thanks Volkan, infact to address it, we had tried, indexes, optimising views, reviewing queries and views. Persistent calculated field we are using where needed too. We are also overriding applyfilters, big but is application works like bullet when filters are removed but we cannot work without filters. Especially date filter are paining like hell. Whenever there is check for record to be in same financial year code goes for a toss. I picked the same query and when run in SQL works within 1 second. Something is happening before query even reaches SQLDB because i notice it takes a while to see the query hit in profiler.
Appreciate if you can help with more pointers. But I will try removing the equalityfilter to see if it helps.

**Comment by aksingh1979** [comment]
Sorry Volkan it didn't worked out. I move the logic to stored procedure and working extremely great. Now issue is to apply filters passed from client side.
Appreciate your few pointers to resolve.
