### ISSUE TITLE
adding Bootstrap Tooltip (data-toggle="tooltip") to forms' inline validation error 

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1306]
Is the **html template** for the little X icon (css class `vx`) beside the form field that displays the validation error updatable? if so, where? (short of building my own Serenity dll)

I want to take advantage of Bootstrap's tooltip (http://www.w3schools.com/bootstrap/bootstrap_tooltip.asp) which is triggered by adding the `data-toggle="tooltip"` property to the html element.

I have tried adding the property via browser's dev tools, and it works perfectly (i.e. upon hover, instead of the plain title, it displays the bootstrap tooltip), which means it's just _begging_ to be added to Serenity. =)

**Comment by john20xdoe** [comment]
is there a way to use `@Serenity.Decorators.addAttribute()` to add this `data-toggle` attribute to a form `.caption` or <label>?

Can anyone show me how it's done?

**Comment by volkanceylan** [comment]
Override dialogOpen, or in constructor, $('.vx').attr('data-toggle', ...)

**Comment by john20xdoe** [comment]
is there a way to make it into an attribute like [BootStrapHint("Hello World")], to be used in forms.?

I adapted it similar to [StaticTextBlock] custom editor, but now it conflicts with [BooleanEditor] : Compile Error says "multiple custom types"...probably because it is another widget.

**Comment by volkanceylan** [comment]
Define a custom base class and derive from that.

**Comment by stixoffire** [comment]
@john20xdoe 
I would like to see an example of how you did your tooltips - perhaps a wiki  page here ?
