### ISSUE TITLE
SidebarSearch on mobile device

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1307]
Dear @volkanceylan,
I'm not able to use the sidebar search from a mobile device...
I tried also with your demo site but the behaviour is always the same: as soon as I click on the input, I lose the focus and I'm unable to write inside...
Any idea?

Thank you very much
Bye

**Comment by marcobisio** [comment]
I think that when the android software keyboard appears, some kind of resize event is activated and then I lost focus...
In fact if I "long click" the input (when the paste menu shows up) then I'am able to keep the focus (no software keyboard appears in that case)...
Still digging btw...

Bye

**Comment by marcobisio** [comment]
Update: this piece of code in the _Layout.cshtml file seems to patch the issue:

var isFocus = false;
    $('#SidebarSearch').focusin(function(event) {
        isFocus = true;
    });
    $('#SidebarSearch').focusout(function(event) {
        isFocus = false;
    });
    $(window).resize(function(event) {
        if(isFocus){
            event.stopImmediatePropagation();
        }
    });

Any idea on how to do it in a cleaner way?

Thank you very much
Bye

**Comment by volkanceylan** [comment]
It might be due to some AdminLTE scale event handling. Need to dive deeper but hard to debug in android browser. Maybe search in its repository issues and see if something similar there?

**Comment by marcobisio** [comment]
Good idea I'll try to search in the AdminLTE repository...
Probably this kind of resize/scale event introduced some kind of side effect in Serenity because in the original AdminLTE demo here:

    https://almsaeedstudio.com/themes/AdminLTE/index2.html

the search input keep the focus when clicked (although there isn't any kind of event bound to it).

I let you know if I discover something else!

**Comment by mantiklas** [comment]
Same scenario I am experiencing.. But in IOS , it works fine..

**Comment by marcobisio** [comment]
It's not easy to debug on mobile...I already tried to disable the search functionality, but nothing changes...
I think that there is some kind of resize event not related to AdminLTE, but honestly I don't know...

**Comment by edson** [comment]
I've worked with browser devices while using ionic to develop some apps...

I remember that, in Ios, when keyboard is shown, the page is actually shifted up. So it does not trigger the resize event...

But in Android.... oh well... that thing triggers and it's hard to know whether the keyboard was shown or not...

Have you tried debuging using chrome://inspect ? It makes a webapp/hybrid app developer's life easier. I'll have a look later.

Best Regards.

**Comment by marcobisio** [comment]
Thanks for your feedback @edson!
I'll try with your chrome suggestion and I let you know...

Bye

**Comment by volkanceylan** [comment]
OK, your report has missed that even latest AdminLTE has this same issue. You won't notice it by default, because it doesn't use Fixed Layout by default. In your android browser, enter AdminLTE site, check fixed layout and see for yourself @marcobisio. So i can confirm this is an issue with Fixed Layout + AdminLTE + SlimScroll

**Comment by volkanceylan** [comment]
Well looks like i've managed to fix this issue by not applying slimscroll to full sidebar, but only to UL containing menu items. AdminLTE recreates slimscroll div on resize, so search input gots lost then comes back again thus loses focus. 

Try it on serenity.is and let me know if it works. It does in my Z3 compact.

**Comment by marcobisio** [comment]
You're right Volkan...
I had not ever noticed ... the default layout of adminlte has cheated me :-/

I'll open an issue on the adminlte github and we will see!

Thanks again Volkan!

**Comment by marcobisio** [comment]
Whooops concurrent comments!
Sure let me check...

**Comment by marcobisio** [comment]
Yes now it's working fine!!!
I tested it with my Galaxy Note 4 (you know, those that do not explode yet :-D) and Chrome last version.
Give your fix also to the AdminLTE guys!!

Thanks again Volkan!

**Comment by volkanceylan** [comment]
You're welcome
