### ISSUE TITLE
Static Text Block sample not showing properly in IE11

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1308]
![static text block](https://cloud.githubusercontent.com/assets/19570368/19375361/fb50572e-91f0-11e6-8d4e-0d8476212183.png)

**Comment by volkanceylan** [comment]
What to say, IE11 rox

**Comment by shaileshbc** [comment]
I am using Maxthon Browser (v 4.4.8.2000 ) from Maxthon.com.
It also shows similar output, where as Firefox works perfectly fine.
regards
Shailesh

**Comment by volkanceylan** [comment]
Fixed in latest. IE11 can't do automatic height for flex items.
