### ISSUE TITLE
Extending the excel importer

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1309]
I'm tying to clean up the excel importer so that I can make it into a more reusable item. item with a stronger mapping to the columns but I'm not having much success. I was hoping to get some input. 

Firstl, I was trying to address the issue about mapping the columns. I wanted to try to read the displayed ColumnNames that would be used in the exported report, and use them to compare against the imported report. If it matched, I wanted to pull the column number and use that to map he field. Something along these lines: 

var tblHeaders = getCurrentTableHeaders();//Headers of current Table. 
var wsheaders = worksheet.Cells[1, 1, 1,  worksheet.Dimesnion.End.Column];
if (!tblHeaders.All( e+> headers.Any(h => h.Value.Equals(e))))
{
ResultMessages.Add("Some Columns were not present on the file");
return resultMessages;
}

for (var i in tblHeaders) 
{
columnNameCol[i] = heades.First(h => h.Value.Equals(tblHeaders[i])).Address[0].ToString();
}

.....

projectTabke.Columnxyz = Convert.ToInt16(worksheet.Cells[row, columnNameCol[#].Value ?? 0);

I got the code idea from this site: https://www.paragon-inc.com/resources/blogs-posts/easy_excel_interaction_pt6 

I attempted to use the Dynamic Data Reporter getColumnList() to pull the current list names as displayed instead of as the sql column names but didn't have much success. At the end I wasn't able to figure out a successful way of pulling the names of all the columns regardless of what columns are displayed. I need the names in the current system table to compare against the header in the spreadsheet and then thus, know which column number in the spreadsheet corresponds to which column name in the system. 

I'm also took the section regarding joint columns and am trying to simplify it. I have this so far: 

 var cCol = 4; //row on Excel Sheet with joined field;  
                        var cID = SupplierRow.Fields.SupplierID; //id on secondary table
                        var cName = SupplierRow.Fields.CompanyName; //field being checked on secondary table
                        var catName = Convert.ToString(worksheet.Cells[row, cCol].Value ?? "");//value from Excel in specific column  where second table joins.
                        var mainID = product.SupplierID; //int designation on current row

```
                    if (!string.IsNullOrWhiteSpace(catName))
                    {
                        var connnectionRow = uow.Connection.TryFirst<SupplierRow>(q => q.Select(cID).Where(cName == catName));
                        var ConnectionID = connnectionRow.SupplierID.Value; //ID field to be updatad. 

                        if (connnectionRow == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": Entity with name '" + catName + "' is not found!");
                            continue;
                        }
                        mainID = ConnectionID;
                    }
                else
                    mainID = null;
```

If I can have the ConnectionID, take the ID field by default instead of having to add a specific property field, then it'd be able to be made into a separate function to call on. 

My end game hope is something like: 

namespace FMCorpDashboardv5.BasicSamples.Endpoints
{
    using Northwind.Entities;
    using Northwind.Repositories;
    using OfficeOpenXml;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Web.Mvc;
    using MyRow = Northwind.Entities.ProductRow;
    using System.Linq;
    using Serenity.Reporting;

```
[RoutePrefix("Services/BasicSamples/ProductExcelImport"), Route("{action}")]
[ConnectionKey("Northwind"), ServiceAuthorize]
public class ProductExcelImportController : ServiceEndpoint
{
    [HttpPost]
    public ExcelImportResponse ExcelImport(IUnitOfWork uow, ExcelImportRequest request)
    {
        request.CheckNotNull();
        Check.NotNullOrWhiteSpace(request.FileName, "filename");

        UploadHelper.CheckFileNameSecurity(request.FileName);

        if (!request.FileName.StartsWith("temporary/"))
            throw new ArgumentOutOfRangeException("filename");

        ExcelPackage ep = new ExcelPackage();
        using (var fs = new FileStream(UploadHelper.DbFilePath(request.FileName), FileMode.Open, FileAccess.Read))
            ep.Load(fs);

        var p = MyRow.Fields;

        var response = new ExcelImportResponse();
        response.ErrorList = new List<string>();

        var worksheet = ep.Workbook.Worksheets[1];
        var tblHeaders = getCurrentTableHeaders();//Headers of current Table. 


        List<string> wsHeaders = new List<string>();
        foreach (var cell in worksheet.Cells[1, 1, 1, worksheet.Dimension.End.Column])
        {
            wsHeaders.Add(cell.Value.ToString());

            if (!tblHeaders.All(e => wsHeaders.Any(h => h.Value.Equals(e))))
            {
                errorMessages.Add("Some Columns were not present on the file");
                return errorMessages;
            }
        }
        List<int> columnNameCol = new List<int>();
        for (var i = 1; 1 > tblHeaders.Count; i++)
        {
            columnNameCol[i] = wsHeaders.First(h => h.Value.Equals(tblHeaders[i])).Address[0].ToString();
        }

        for (var row = 2; row <= worksheet.Dimension.End.Row; row++)
        {
            try
            {
                var lineIDCol = columnNameCol[1];
                var pruductId = Convert.ToInt32(worksheet.Cells[row, lineIDCol].Value ?? "");
                var pName = Convert.ToString(pruductId);

                if (pName.IsTrimmedEmpty())
                    continue;

                var product = uow.Connection.TryFirst<MyRow>(q => q.Select(p.ProductID).Where(p.ProductID == pruductId));

                if (product == null)
                    product = new MyRow
                    {
                        ProductID = pruductId
                    };
                else
                {
                    // avoid assignment errors
                    product.TrackWithChecks = false;
                }

                var cCol = columnNameCol[4]; //row on Excel Sheet with joined field;                    
                var cID = SupplierRow.Fields.SupplierID; //id on secondary table
                var cName = SupplierRow.Fields.CompanyName; //field being checked on secondary table
                var catName = Convert.ToString(worksheet.Cells[row, cCol].Value ?? "");//value from Excel in specific column  where second table joins.
                var mainID = product.SupplierID; //int designation on current row

                mainID = jointFieldImport(cCol, cID, cName, catName, mainID, uow, response, row, typeof(SupplierRow));

                cCol = columnNameCol[5]; //row on Excel Sheet with joined field;                    
                cID = CategoryRow.Fields.CategoryID; //id on secondary table
                cName = CategoryRow.Fields.CategoryName; //field being checked on secondary table
                catName = Convert.ToString(worksheet.Cells[row, cCol].Value ?? "");//value from Excel in specific column  where second table joins.
                mainID = product.CategoryID; //int designation on current row

                mainID = jointFieldImport(cCol, cID, cName, catName, mainID, uow, response, row, typeof(CategoryRow));


                product.ProductName = Convert.ToString(worksheet.Cells[row, columnNameCol[2]].Value ?? "");
                product.Discontinued = Convert.ToBoolean(worksheet.Cells[row, columnNameCol[3]].Value ?? true);
                product.QuantityPerUnit = Convert.ToString(worksheet.Cells[row, columnNameCol[6]].Value ?? "");
                product.UnitPrice = Convert.ToDecimal(worksheet.Cells[row, columnNameCol[7]].Value ?? 0);
                product.UnitsInStock = Convert.ToInt16(worksheet.Cells[row, columnNameCol[8]].Value ?? 0);
                product.UnitsOnOrder = Convert.ToInt16(worksheet.Cells[row, columnNameCol[9]].Value ?? 0);
                product.ReorderLevel = Convert.ToInt16(worksheet.Cells[row, columnNameCol[10]].Value ?? 0);

                if (product.ProductID == null)
                {
                    new ProductRepository().Create(uow, new SaveWithLocalizationRequest<MyRow>
                    {
                        Entity = product
                    });

                    response.Inserted = response.Inserted + 1;
                }
                else
                {
                    new ProductRepository().Update(uow, new SaveWithLocalizationRequest<MyRow>
                    {
                        Entity = product,
                        EntityId = product.ProductID.Value
                    });

                    response.Updated = response.Updated + 1;
                }
                cCol = 0;
                cID = null;
                cName = null;
                catName = null;
                mainID = null;


            }
            catch (Exception ex)
            {
                response.ErrorList.Add("Exception on Row " + row + ": " + ex.Message);
            }
        }

        return response;
    }

    public static int jointFieldImport(int cCol, Int32Field cID, StringField cName, string catName, int? mainID, IUnitOfWork uow, ExcelImportResponse response, int row, Type myType)
    {
        if (!string.IsNullOrWhiteSpace(catName))
        {
            var connectionRow = uow.Connection.TryFirst < typeof(myType) > (q => q.Select(cID).Where(cName == catName));
            var connectionId = connectionRow.ID.Value; //ID field would need to be ID in all joint fields regardless of tables.

            if (connectionRow == null)
            {
                response.ErrorList.Add("Error On Row " + row + ": Entity with name '" + catName + "' is not found!");
            }
            mainID = connectionId;
        }
        else
            mainID = null;


        return mainID;
    }

    public static List<ReportColumn> getCurrentTableHeaders()
    {
        var headers = "";

        //add logic


        return headers;
    }

}
```

}

I appreciate any insight. I'll keep working on it and let you know if there are any updates.

**Comment by volkanceylan** [comment]
I actually have a better importer, especially on matching column names to fields while ignoring little differences in column order and/or title.

Anyway it is not a full featured import tool, and not so dynamic one that works in all cases. I don't recommend for you to write a very dynamic one too, unless you really need it. Better, set your standards and ask ones who imports data to adhere them.

**Comment by sayuga** [comment]
Well, the only reason I'm trying to get something more dynamic is to make it more multipurpose, thus less coding, and because I like to plan for people not following instructions. I am assuming that the user will not pay attention to the order of the columns and then try to import, possibly messing with the data. 

I was planning on mapping it on 2 specific parts that are relatively reliable regrading tables: A unique key for each record (row) and the columns default build from the xyzColumns.cs file. I figure if I can read those accordingly, I can always reliable match each record plus I can compare the column name from the DB to the column name in the xyz column to maintain consistent mapping. 

I also figured this would let me build tables without having to worry about mapping the columns directly, I'd just throw in a relationship and let the code due the rest

I might play around with it a bit more to see if I can make it work, otherwise I might just leave it as is for my current version and hope the user will follow instructions.

**Comment by sayuga** [comment]
It's not pretty, but I was able to map the full importer so that it can manage any xlsx file that is imported even if it is missing columns and maintains reliable mapping to the row ID. I think I can still clean it up some. Once I do I'll add it to the Wiki as I think it'll be helpful.  I'll add notes as well afterwards. 


namespace FMCorpDashboardv5.BasicSamples.Endpoints
{
    using Northwind.Entities;
    using Northwind.Repositories;
    using OfficeOpenXml;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Web.Mvc;
    using MyRow = Northwind.Entities.ProductRow;
    using System.Linq;        

    [RoutePrefix("Services/BasicSamples/ProductExcelImport"), Route("{action}")]
    [ConnectionKey("Northwind"), ServiceAuthorize]
    public class ProductExcelImportController : ServiceEndpoint
    {
        [HttpPost]
        public ExcelImportResponse ExcelImport(IUnitOfWork uow, ExcelImportRequest request)
        {
            request.CheckNotNull();
            Check.NotNullOrWhiteSpace(request.FileName, "filename");

            UploadHelper.CheckFileNameSecurity(request.FileName);

            if (!request.FileName.StartsWith("temporary/"))
                throw new ArgumentOutOfRangeException("filename");

            ExcelPackage ep = new ExcelPackage();
            using (var fs = new FileStream(UploadHelper.DbFilePath(request.FileName), FileMode.Open, FileAccess.Read))
                ep.Load(fs);

            var p = MyRow.Fields;

            var response = new ExcelImportResponse();
            response.ErrorList = new List<string>();

            var worksheet = ep.Workbook.Worksheets.First();
            var lastCol = worksheet.Dimension.End.Column;            
            var firstCol = worksheet.Dimension.Start.Column;
            var firstRow = worksheet.Dimension.Start.Row;
            var headers = worksheet.Cells[firstRow, firstCol, 1, lastCol];            

            var expectedHeaders = new[] { "ID", "Product Name", "Discontinued", "Supplier", "Category", "Quantity Per Unit", "Unit Price", "Units In Stock", "Units On Order", "Reorder Level" };
            int[] myCols = new int[expectedHeaders.Length];
            string[] headerArray = new string[lastCol];
            var i = 0;

            foreach (var firstRowCell in headers)
            {
                headerArray[i] = firstRowCell.Text;
                i++;
            }

            for (int counter = 0; counter < expectedHeaders.Length; counter++)
            {
                for (var x = 0; x < headerArray.Length; x++)
                {
                    if (headerArray[x] == expectedHeaders[counter])
                    {
                        var checker = headers.First(h => h.Value.Equals(expectedHeaders[counter])).Address[0].ToString();
                        myCols[counter] = ColumnIndex(checker);
                        break;
                    }
                    else
                    {
                        //response.ErrorList.Add("Column " + expectedHeaders[counter] + " appears to be missing from the file");
                        myCols[counter] = -1;
                    }
                }
            }

            for (var row = 2; row <= worksheet.Dimension.End.Row; row++)
            {
                try
                {
                    int cCol;
                    Int32Field cID;
                    StringField cName;
                    string catName ;
                    int? mainID ;

                    var lineIDCol = myCols[0];
                    var pruductId = Convert.ToInt32(worksheet.Cells[row, lineIDCol].Value ?? "");
                    var pName = Convert.ToString(pruductId);

                    if (pName.IsTrimmedEmpty())
                        continue;

                    var product = uow.Connection.TryFirst<MyRow>(q => q.Select(p.ProductID).Where(p.ProductID == pruductId));

                    if (product == null)
                        product = new MyRow
                        {
                            ProductID = pruductId
                        };
                    else
                    {
                        // avoid assignment errors
                        product.TrackWithChecks = false;
                    }

                    if (myCols[3] > -1)
                    {
                         cCol = myCols[3]; //row on Excel Sheet with joined field;                    
                         cID = SupplierRow.Fields.SupplierID; //id on secondary table
                         cName = SupplierRow.Fields.CompanyName; //field being checked on secondary table
                         catName = Convert.ToString(worksheet.Cells[row, cCol].Value ?? "");//value from Excel in specific column  where second table joins.
                         mainID = product.SupplierID; //int designation on current row

                        if (!string.IsNullOrWhiteSpace(catName))
                        {
                            var connectionRow = uow.Connection.TryFirst<SupplierRow>(q => q.Select(cID).Where(cName == catName));
                            var connectionId = connectionRow.SupplierID.Value; //ID field would need to be ID in all joint fields regardless of tables.

                            if (connectionRow == null)
                            {
                                response.ErrorList.Add("Error On Row " + row + ": Entity with name '" + catName + "' is not found!");
                            }
                            mainID = connectionId;
                        }
                        else
                            mainID = null;
                    }

                    if (myCols[4] > -1)
                    {
                        cCol = myCols[4]; //row on Excel Sheet with joined field;                    
                        cID = CategoryRow.Fields.CategoryID; //id on secondary table
                        cName = CategoryRow.Fields.CategoryName; //field being checked on secondary table
                        catName = Convert.ToString(worksheet.Cells[row, cCol].Value ?? "");//value from Excel in specific column  where second table joins.
                        mainID = product.CategoryID; //int designation on current row

                        if (!string.IsNullOrWhiteSpace(catName))
                        {
                            var connectionRow = uow.Connection.TryFirst<CategoryRow>(q => q.Select(cID).Where(cName == catName));
                            var connectionId = connectionRow.CategoryID.Value; //ID field would need to be ID in all joint fields regardless of tables.

                            if (connectionRow == null)
                            {
                                response.ErrorList.Add("Error On Row " + row + ": Entity with name '" + catName + "' is not found!");
                            }
                            mainID = connectionId;
                        }
                        else
                            mainID = null;
                    }                                    

                    if (myCols[1] > -1)
                    {
                        product.ProductName = Convert.ToString(worksheet.Cells[row, myCols[1]].Value ?? "");
                    }
                    if (myCols[2] > -1)
                    {
                        product.Discontinued = Convert.ToBoolean(worksheet.Cells[row, myCols[2]].Value ?? true);
                    }
                    if (myCols[5] > -1)
                    {
                        product.QuantityPerUnit = Convert.ToString(worksheet.Cells[row, myCols[5]].Value ?? "");
                    }
                    if (myCols[6] > -1)
                    {
                        product.UnitPrice = Convert.ToDecimal(worksheet.Cells[row, myCols[6]].Value ?? 0);
                    }
                    if (myCols[7] > -1)
                    {
                        product.UnitsInStock = Convert.ToInt16(worksheet.Cells[row, myCols[7]].Value ?? 0);
                    }
                    if (myCols[8] > -1)
                    {
                        product.UnitsOnOrder = Convert.ToInt16(worksheet.Cells[row, myCols[8]].Value ?? 0);
                    }
                    if (myCols[9] > -1)
                    {
                        product.ReorderLevel = Convert.ToInt16(worksheet.Cells[row, myCols[9]].Value ?? 0);
                    }

                    if (product.ProductID == null)
                    {
                        new ProductRepository().Create(uow, new SaveWithLocalizationRequest<MyRow>
                        {
                            Entity = product
                        });

                        response.Inserted = response.Inserted + 1;
                    }
                    else
                    {
                        new ProductRepository().Update(uow, new SaveWithLocalizationRequest<MyRow>
                        {
                            Entity = product,
                            EntityId = product.ProductID.Value
                        });

                        response.Updated = response.Updated + 1;
                    }
                    cCol = 0;
                    cID = null;
                    cName = null;
                    catName = null;
                    mainID = null;
                }
                catch (Exception ex)
                {
                    response.ErrorList.Add("Exception on Row " + row + ": " + ex.Message);
                }
            }
            return response;
        }

        public static int ColumnIndex(string reference)
        {            
            int ci = 0;
            reference = reference.ToUpper();
            for (int ix = 0; ix < reference.Length && reference[ix] >= 'A'; ix++)
                ci = (ci * 26) + ((int)reference[ix] - 64);
            return ci;
        }
    }

}

**Comment by volkanceylan** [comment]
Here is some excerpt from my column title => index mapper:

```cs
        private string Normalize(string s)
        {
            s = Serenity.StringHelper.RemoveDiacritics(s.TrimToEmpty())
                .Replace("_", "")
                .Replace(" ", "")
                .Replace("-", "")
                .Replace(":", "")
                .Replace(".", "")
                .ToLowerInvariant();

            return s;
        }

        private Dictionary<string, int> GetColumnMappings(string[] header)
        {
            var headerColByNorm = new Dictionary<string, int>();
            for (var i = 0; i < header.Length; i++)
                headerColByNorm[Normalize(header[i])] = i;

            var indexByCol = new Dictionary<string, int>();

            Action<string, string[]> addMapping = (key, alternatives) =>
            {
                int mappedIndex;
                if (!headerColByNorm.TryGetValue(Normalize(key), out mappedIndex))
                {
                    foreach (var alt in alternatives)
                    {
                        if (headerColByNorm.TryGetValue(Normalize(alt), out mappedIndex))
                        {
                            indexByCol[key] = mappedIndex;
                            return;
                        }
                    }

                    mappedIndex = -1;
                }

                indexByCol[key] = mappedIndex;
            };

            addMapping("TC Kimlik No", new[] { "TCKN", "KN", "Kimlik Numarası", "Kimlik No", "TC Kimlik No", "TC Kimlik" });
            addMapping("Öğrenci No", new[] { "Öğrenci Numarası", "Öğrenci Nosu" });
            addMapping("Adı", new[] { "Ad", "Öğrenci Adı" });

```

It supports some alternatives people might use for a given column. For example, TC Kimlik No (personal identity number) might be written in several cases (TCKN, KN....)

Then I create some reader class, with input and these column mapping dictionary:

```cs
        private class LineReader
        {
            private Dictionary<string, int> indexByCol;

            public LineReader(Dictionary<string, int> indexByCol)
            {
                this.indexByCol = indexByCol;
            }

            public Dictionary<string, int> IndexByCol { get { return indexByCol; } }
            public string[] Parts { get; set; }

            public string GetStr(string column)
            {
                 // ...
            }

            public int? GetInt(string column)...
            public double? GetDouble(string column)...
            public DateTime? GetDate(string column)...
```

GetInt, GetDouble etc do some validation and proper error reporting with line / column numbers etc.

My solution supports several file formats (XLS, CSV, XLSX etc) so it is a bit complex one to share here.

**Comment by sayuga** [comment]
hmm. Nice, I'll play around with this. It may be complex but I like a challenge. I don't have a chance today but I'll let you know what I come out with once I get to throw these in the blend.

**Comment by sayuga** [comment]
I'm still working on this but my control over c# is still average. I need some help with attempting to convert the following to Generics: 

                        cCol = myCols[4]; //row on Excel Sheet with joined field;
                        cID = CategoryRow.Fields.CategoryID; //id on secondary table
                        cName = CategoryRow.Fields.CategoryName; //field being checked on secondary table
                        catName = Convert.ToString(myVal[4] ?? "");//value from Excel in specific column  where second table joins.
                        mainID = product.CategoryID; //int designation on current row

                        if (!string.IsNullOrWhiteSpace(catName))
                        {
                            var connectionRow = myConnection.TryFirst<CategoryRow>(q => q.Select(cID).Where(cName == catName));
                            var connectionId = connectionRow.CategoryID.Value; //ID field would need to be ID in all joint fields regardless of tables.

                            if (connectionRow == null)
                            {
                                connectionRow = new CategoryRow();
                                eMessage = "Error On Row " + row + ": Entity with name '" + catName + "' was not found so it was added!";
                                myErrors.Add(eMessage);
                            }
                            mainID = connectionId;
                        }
                        else
                            mainID = null;
                    }


I've so far attempted the following but I seem to be unable to figure out the best way to call upon the ID field for the given row. Any outside input? 

public static object myJointField<T>(int cCol, Int32Field cID, StringField cName, string catName, int? mainID, IUnitOfWork uow, List<string> myErrors, int row)where T: Row, new()
            {                
                var myConnection = uow.Connection;
                string eMessage = null;

                if (!string.IsNullOrWhiteSpace(catName))
                {
                    var connectionRow = myConnection.TryFirst<T>(q => q.Select(cID).Where(cName == catName));
                    var connectionId = connectionRow.SupplierID.Value; //ID field would need to be ID in all joint fields regardless of tables.

                    if (connectionRow == null)
                    {
                        connectionRow = new T();
                        eMessage = "Error On Row " + row + ": Entity with name '" + catName + "' was not found so it was added!";
                        myErrors.Add(eMessage);
                    }
                    mainID = connectionId;
                }
                else
                    mainID = null;

                return mainID;                
            }

**Comment by sayuga** [comment]
Ok, in case anyone wants to join in, I figured I'd drop in my current standing on this. I've managed to get a ExcelImportHelper.cs that has most all the necessary handling for the importer. I just need to do something with the reading of the existing displayed columns, updating the field calls dynamically, and handling the joint fields using generics but I'll work some more on that on Monday. The following two files have my edits to the ProductExcelImportEndpoint.cs and the ExcelImportHelper.cs file I created. 

Worth noting, is that I have a myImporEntry handling the casting because I hope to have all field types, including custom, be managed through this by calling upon an enum listing the types. This way you can more consistently manage the casting and troubleshoot as needed. I wish to have the joint fields managed there too one I figure out how to properly implement generics so that I can pass the xyzRow and the ID field of the other item. 

Anyhow, I welcome all constructive criticism. I can attest that this works as it stands already for updating mixed columns and missing columns. (i've added my testing import files as well)

[ExcelImport.zip](https://github.com/volkanceylan/Serenity/files/545147/ExcelImport.zip)

**Comment by sayuga** [comment]
I need some input. I've updated most of the code in a fairly sturdy form so that it is consistent but I am having some difficulty with managing the joint fields. I wish to have it check if the joint field label exists and if it doesn't, I want it to create a new entry in the joint table and then take the new Id for that row on that table and set it for the current row of the current table. My code is below. It appears to run but it neither creates the entry in the joint table nor gets the id to set for the main table.: 

```
//.....//
  int keyCol = 0; //column with master ID field
                    var sysKey = MyRow.Fields.MatrixId;
                    var wsKeyField = Convert.ToInt32(myVal[keyCol]);
                    var currentRow = myConnection.TryFirst<MyRow>(q => q.Select(sysKey).Where(sysKey == wsKeyField));

                    if (currentRow == null)
                        currentRow = new MyRow() { };
                    else
                        currentRow.TrackWithChecks = false;     // avoid assignment errors

                    //---------------------------------Client Row - Joint Field----------------------------------//

                    m = 1; //system column for system field
                    if (myVal[m] != null)
                    {
                        var g = ClientsRow.Fields; //joint Row Fields
                        int myCol = m; //system column with matching worksheet column
                        var sysID = g.ClientId; //Id on joint Row Field
                        var sysField = g.ClientName; //field being compared against
                        var wsField = Convert.ToString(myVal[myCol]); //field to compare 
                        var currRow = myConnection.TryFirst<ClientsRow>(q => q.Select(sysID).Where(sysField == wsField)); //checks if field exists

                        if (currRow == null) //if field does not exist
                        {
                            var newRow = new ClientsRow() //create new row in joint table 
                            {
                                ClientName = wsField //assign cell value to new row field
                            };
                            currentRow.CustomerId= newRow.ClientId; //assign ID of new joint row to main table field
                            eMessage = "Error On Row " + row + ": Entity with name '" + wsField + "' was not found so it was added!"; //let the user know
                            myErrors.Add(eMessage);
                        }
                        else
                        {
                            //currRow.TrackWithChecks = false;
                            currentRow.CustomerId = currRow.ClientId; //assign a default value. First choice on dropbox or already existing value. 
                        }
                    } 
//....//
```

Once this is done, I'll upload the full coding, cleaned up. I've managed to do everything I set out to but the dynamic headers and the joint field create-if-not-found feature. I decided to forgo the dynamic headers since I can manage the headers being manually input for the time being. I'll leave that part to someone else to manage. 

I can also say this, I made the code such that the Headers and row values are mapped first then managed thus as long as the values are mapped to the proper array variable, you can essentially bring any data type that can be made into a data table. Example: 

My Excel Header mapper compares the headers from the worksheet to the expected headers(currently a manual string array), gets the alphabetic address (A1, AA1, AAA1, etc) and then converts it to an index. I separated the indexer so that it can be used with any data table that uses alphabetic addresses. 

     ```
   public static int[] myExcelHeaderMap(ExcelRange headers, string[] expectedHeaders, List<string> myErrors, int lastCol)
        {
            string[] headerArray = new string[lastCol]; //Array index for imported headers. 
            var i = 0;
            var eHeaderLength = expectedHeaders.Length; //number of unique expected headers in system. 
            string eMessage = null;
            int[] myCols = new int[eHeaderLength];

            foreach (var firstRowCell in headers) //add all import headers to headerArray array. 
            {
                headerArray[i] = firstRowCell.Text; //makes an entry for any header making an index
                i++;
            }

            for (int counter = 0; counter < eHeaderLength; counter++) //runs throufgh each existing header and compares
            {
                for (var x = 0; x < headerArray.Length; x++) //checks each item in the headerArray index to the existing header being analyzed
                {
                    var wsHeader = headerArray[x];// current wsHeader being checked. 
                    var currEHeader = expectedHeaders[counter]; //current expected header being checked against imported headers. 
                    if (wsHeader == currEHeader) //if the worksheet header exists
                    {
                        var g = headers.First(h => h.Value.Equals(currEHeader)); //takes the header location
                        var alphaAddress = g.Address[0].ToString(); //reads the address letter in the column name from first field
                        if (x >= 26) //if larger than 'Z'
                        {
                            alphaAddress = g.Address[0].ToString() + g.Address[1].ToString();//reads the address letter in the column name from first two fields
                            if (x >= 702) //if larger than 'ZZ'
                            {
                                alphaAddress = g.Address[0].ToString() + g.Address[1].ToString() + g.Address[2].ToString();//reads the address letter in the column name from first three fields
                            }
                        }
                        myCols[counter] = ColumnIndex(alphaAddress); //uses ColumnIndexer to replace the appropiate letter with the according numerical
                        eMessage = null;
                        break;
                    }
                    else //if not matching header makes -1 and continues
                    {
                        myCols[counter] = -1;
                        eMessage = "Column " + expectedHeaders[counter] + " appears to be missing from the file"; //lets user know what columns were missing from file
                    }
                }
                if (eMessage != null)
                    myErrors.Add(eMessage);
            }
            return myCols; //Index with column number of all relevant headers
}

The myExcelRowValues reader simply creates a object array to capture each cell value, regardless of type, and creates nulls for all irrelevant values using the -1 column number I set on the ExcelHeaderMapper. This way I can have my entry handler ignore the entries. As long as the values are passed as a object array with nulls for irrelevant columns, any data table row source should be able to be used. 





 ```
public static object[] myExcelRowValues(int sysHeadersLength, int row, int[] myCols, ExcelWorksheet worksheet)
        {
            object[] myVal = new object[sysHeadersLength];
            for (var f = 0; f < sysHeadersLength; f++)
            {
                try
                {
                    if (myCols[f] > -1)
                        myVal[f] = worksheet.Cells[row, myCols[f]].Value; 
                }
                catch
                {
                    myVal[f] = null;
                }
            }

            return myVal;
        }
```

**Comment by sayuga** [comment]
I managed to get it to create the new Category/Supplier when it does not exist by using 

     if (currRow == null)
                        {
                            //var newRow = new CategoryRow()
                            //{
                            //    CategoryName = wsField
                            //};        
                            myConnection.Insert(new CategoryRow{ CategoryName = wsField });
                            var newRow = myConnection.TryFirst<CategoryRow>(q => q.Select(sysID).Where(sysField == wsField));
                            product.CategoryID= newRow.CategoryID;
                            eMessage = "Error On Row " + row + ": Entity with name '" + wsField + "' was not found so it was added!"; //let the user know
                            myErrors.Add(eMessage);
                        }
But I've now run into a different problem. I am successfully Creating the entry, getting the ID and setting the ID to the main table but, the drop box will not update.  I need to have the grid refresh after committing the import. What is the best way to do this?

**Comment by sayuga** [comment]
All done. I managed to document just about everything. Here is the Helper and Endpoint files I edited. This should: 
- allow the user to Import any excel file into the system table and update regardless of having extra columns, mixing column or missing columns as long as there is an ID value and a matching header title, thus not needing multiple import file controllers.  
-If it's a new entry, you just leave the ID field blank and it will automatically add it to the system, matching all field types and joint fields.
- It will add missing joint field values. 
-It will tell you when adding values or missing columns
-The user can manage any input type by using the import entry and stating a new case scenario using the manual type designation. 
-all parts in the helper can generic thus can be used to more quickly generate an import file for new tables. 

I'm sure this can be improved upon but I figured it's now at a stage worth having you review and see if you like it enough for me to put in the Wiki. 

Let me know. 

P.S. I built the sample using the excel import sample from the Basic Sample so you should be able to drop in and only need to update the namespace, rebuild, transform and done.  

[ProductExcelImport.zip](https://github.com/volkanceylan/Serenity/files/559331/ProductExcelImport.zip)

**Comment by sayuga** [comment]
I've managed to bring the extension of the excel import feature up to where I need it to be so I went ahead and I created a wiki with the full details of how I handled it. Let me know if you want me to send you the gists. Thanks for the input while I worked on this. I may come back to it and try implementing something more along the lines of your sample mapper and line reader. I'll gladly share my findings at that time. 

Heres the wiki:  https://github.com/volkanceylan/Serenity/wiki/Add-Excel-Import---column-mapping-&-import-field-type-handling

**Comment by mreid2005** [comment]
Sayuga, Thanks for all the work that went into this I'm going to give it a go.  I just wanted to mention that I clicked on the link for Wiki page, and it took me to a blank page?  hope it didn't get deleted :)

**Comment by sayuga** [comment]
@mreid2005, it wasn't deleted, I just ran some updates on it a while back and that isn't the newest link. Click on "Wiki" on the top tab and you should see the item listed. 

here is the updated link: 

https://github.com/volkanceylan/Serenity/wiki/Excel-Import---Extended:-Column-Mapping-and-Import-Value-Type-Handling

**Comment by mreid2005** [comment]
Thanks I'll look it over!

**Comment by gfo2007** [comment]
```
if Text.StartsWith([Reader], "Main Gate") then 
  if [Response] = "Allowed In" then
     if [Time] >= Time.FromText("00:00:00") and [Time] <=          Time.FromText("03:59:59") then
        Date.AddDays([Date], -1)
     else [Date]
  else 
     if [Time] >= Time.FromText("00:00:00") and [Time] <=          Time.FromText("08:00:00") then
        Date.AddDays([Date], -1)
     else [Date]
else
  if [Response] = "Allowed In" then
    if [Time] >= Time.FromText("00:00:00") and [Time] <=          Time.FromText("06:15:00") then
        Date.AddDays([Date], -1)
    else [Date]
  else
    if [Time] >= Time.FromText("00:00:00") and [Time] <=          Time.FromText("06:00:00") then
        Date.AddDays([Date], -1)
    else [Date]
```
