### ISSUE TITLE
Why and which situation we use Transform all T4 Template in serenity

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#131]
Hello sir,

I have bit confusion why and which situation we use Transform all T4 Template in serenity.
I generate code using sergen.exe each time code generation i used Build and then Transform all T4 Template, is it right or wrong method.

**Comment by ademc** [comment]
Transform operation only required when u have changed Row, changed any service method, added/removed Form or Column property etc.

You dont have to transform any t4 for service method modification, reposity code changes.

And if you add/change any editor code from .Script project you must transform t4 for reflect to use in .Web project. 

Everytime you dont have to transform all t4 files. If you changed editor code in .Script project you ll only run ScriptEditorTypes.t4 for example

**Comment by volkanceylan** [comment]
After code generation you don't need to transform templates. These T4 templates are for type transfer for compile time checking and intellisense purposes from script to web, vice versa. When you generate code, their initial output is also generated by Sergen. 

As ademc pointed, when you do manual changes to code files, like rows, forms, enums etc. you should run templates in other side, e.g. if you changed something in web, run T4 files in script. But as sometimes it is not so clear for users, which T4 is for which, i recommend running all after a succesful build. This is important as output DLL files are used for code generation.
