### ISSUE TITLE
Serenity for Desktop Application

### ISSUE THREAD

**Issue by mahmuthaktan** [volkanceylan/Serenity#1310]
We are using devxpress controls and all our code are stand behind forms. I try to change code to entity based with dapper but i need more specifications that is in serenity. Caching ,Validation so on. Can you write very simple  demo for desktop application. I am not sure how to ise web service framework of serenity.

**Comment by volkanceylan** [comment]
You want to call Serenity services that resides in a web backend from desktop application or use Serenity classes directly in desktop application?

**Comment by mahmuthaktan** [comment]
Using serenity directly would be easy to adapt.  Dapper was very nice to use but i want more properties like caching  (in windows client) validation  (is it poaaible to interaction wirh devxpress components) and binding as data source to devxpress component.

**Comment by volkanceylan** [comment]
You can install nuget packages into your application and start using Serenity classes like SqlQuery, LocalCache etc. but integrating validation etc. which is designed for web into windows forms controls is another business. I have a desktop application written using Serenity + DX but it uses a very old version of Serenity.
