### ISSUE TITLE
What is ScriptInitialization.ts used for?

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1313]
What are the stuff that can be done or added inside `Common/ScriptInitialization.ts`? It's purpose is to initilize scripts: what examples of scripts? 

The one reason I know for now is to add the root namespace like:
```
namespace DWT.ScriptInitialization {
    Q.Config.rootNamespaces.push('MyProject');
}
```
What else? and what is not allowed? 

If we get a long enough list we can add this to the wiki.

**Comment by volkanceylan** [comment]
It is not a specialized method. You may use it for any script setup work.

**Comment by john20xdoe** [comment]
So it means it's the first TS file to execute? like a Main() method?

**Comment by volkanceylan** [comment]
Kinda, there is no main method in javascript.
