### ISSUE TITLE
Noob question : how to send non updatable field value to Save Services

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1315]
I want value of one field of a table, not to be changed, by user, but it's value should be available in SaveRequest. The value of the field should not be changed by user but it requires for some validation.

If i put any attributes like, Oneway or ReadOnly or updatable =false etc. so that the user cannot change its value, but with this its value is set as null in SaveRequest.
I know, this may be noob question, but i am not able to figure it out how, can i inject value of field into save request, before sending it to service.
regards
shailesh

**Comment by volkanceylan** [comment]
Set it in SetInternalFields server side.

**Comment by shaileshbc** [comment]
With SetInternalFields, i have to get Entity Row from Database and then set Non-Updatable field value.
But i want it to be done without going back to database, inside .ts file.
is it possible?
regards
shailesh

**Comment by volkanceylan** [comment]
You don't go back to database in SetInternalFields. ReadOnly without Oneway should also work.

**Comment by shaileshbc** [comment]
Issue with SetInternalFields is that i am doing validation in Create function of Repository, whereas, SetInternalFields will be called when i execute MySaveHandler().Process() function.
So validating will be done first and then SetInternalFields will be called.
so this solution will not work.
Before posting this issue, i was getting null value for Readonly attribute, but today i am getting value.
so my validation on Fields value is working.
regards
Shailesh
