### ISSUE TITLE
Inline grid button to call c# method using MyEndpoint and Typescript

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1317]
Awesome application framework.  I have a question.  For the life of me being new to  your framework and MVC  how do I create an inline grid button to run a method on the server for 
 
Ex. 
Button is call process and when the inline button is pressed I want to call a c# method and do some stuff
 
processMethod(Id of clicked row)
{
Do some stuff with the record
}
Thanks and any examples would be appreciated.
I saw this response below but don’t know how to implement being a webforms guy and min MVC exp. 
For approve, reject, don't need bulk action, just write a method in your endpoint (MyEndpoint) and call it with MyService.Approve(), MyService.Reject()

**Comment by Estrusco** [comment]
Calling a service from the dialog.ts is done by calling

```ts
    MyProject.XYZService.MyPersonalMethod(
                {
                    requestparams....
                },
                response =>
                {
                   this.form.xyz.value = ....;
                }
            );
```

**Comment by mcb2323** [comment]
This worked thanks

**Comment by mahmoudkheder** [comment]
@mcb2323   @Estrusco 
Could you please explane how to do it in details?
what after writing your method 
processMethod(Id of clicked row)
{
Do some stuff with the record
}
in the Endpoint.cs 
what are we do after that or how to create service that call this myMethod in endpoint?
