### ISSUE TITLE
What method is used to hash and unhash passwords?

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#1319]
I'm working on making a desktop version of my Serenity based application and would like to use the same user base. What method do you use to hash and unhash the passwords from the database? Can you point me to that location in Serenity?

Thanks!

**Comment by VictorTomaili** [comment]
For security reasons, dont use unhash password algorithms. Serenity use SHA512 with salted passwords. 
https://github.com/volkanceylan/Serenity/blob/master/Serenity.Web/Security/WebSecurityHelper.cs 

https://github.com/volkanceylan/Serene/blob/0ff1ea9e9ab3f8003a456b585cf6b2b3934bf947/Serene/Serene.Web/Modules/Administration/User/UserRepository.cs#L233

https://github.com/volkanceylan/Serenity/blob/master/Serenity.Web/Security/SiteMembershipProvider.cs#L273

**Comment by wdhodges** [comment]
Thank you good sir!
