### ISSUE TITLE
Manage DateTimeOffset

### ISSUE THREAD

**Issue by Ogost22** [volkanceylan/Serenity#1323]
I have problems when I request MSSQL DateTimeOffset fields:

An exception of type 'System.InvalidCastException' occurred in System.Data.dll but was not handled in user code

Additional information: Invalid attempt to GetBytes on column 'DetectStart (My Column DateTimeOffset)'.  The GetBytes function can only be used on columns of type Text, NText, or Image.

I need to extend the Serenity project to manage DateTimeOffset or I can cast in my own project?

Thank you,
Augusto

**Comment by volkanceylan** [comment]
DateTimeOffset not supported yet

**Comment by Ogost22** [comment]
OK, Thank you for the answer volkanceylan !!

**Comment by wolfen351** [comment]
I'm also struggling with this, I can't remove the field as it is required by azure - what can i do in the project to map it to something useful / mark it ignored? (i dont actuually want to edit it, and it is nullable)

**Comment by volkanceylan** [comment]
I've added DateTimeOffsetField to Serenity in latest commit. It seems to be working but no editor, no formatting support yet, you need to handle those manually. Will relase in 2.6.5

**Comment by wolfen351** [comment]
thank you - i assume you just made it load and save back to the db safely? - while you have this code close by, please do the same for the "timestamp" data type - its the other weird data type that azure uses

**Comment by wolfen351** [comment]
timestamp is just a fancy way to say Int - it is used for row version in azure - it has nothing to do with date and time values

**Comment by volkanceylan** [comment]
But this topic is for DateTimeOffset not timestamp. Int32 field should work for timestamp.

**Comment by wolfen351** [comment]
it should, but it is converted to StreamField and Stream data type, causing runtime exceptions (want me to log a separate bug?)

**Comment by wolfen351** [comment]
i was just thinking you can do the same as what you just did for this datatype

**Comment by volkanceylan** [comment]
https://msdn.microsoft.com/en-us/library/cc716729(v=vs.110).aspx

It says that timestamp column maps to a byte[], which is StreamField in Serenity, what is error you are getting exactly?

**Comment by wolfen351** [comment]
I remember it threw on something like .GetBytes[] with iirc invalidoperation exception, I'll try to recreate and capture more detail

**Comment by Ogost22** [comment]
Thank you very much Volkan !!
Best
Augusto

Augusto Clement
+54-911-2644-7763

**Comment by volkanceylan** [comment]
You're welcome
