### ISSUE TITLE
New Permission in site.texts.invariant.json don't load to the UI

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1324]
![capture](https://cloud.githubusercontent.com/assets/22570602/19508183/6d9d193c-95e0-11e6-8095-c1118ce62a20.PNG)

**Comment by volkanceylan** [comment]
Remove colon

**Comment by in32bit** [comment]
Colon off, IISRESET and still..

![capture](https://cloud.githubusercontent.com/assets/22570602/19517495/3b0ac742-960a-11e6-8270-79df7a103fce.PNG)

**Comment by volkanceylan** [comment]
Did you read FAQ, Troubleshooting? Where did you read a key you added there is shown in the UI?

**Comment by in32bit** [comment]
From your example. 
You created:

"Permission.Administration:Security": "User, Role Management and Permissions"

and now its display in a new role/user permission edit.
![capture](https://cloud.githubusercontent.com/assets/22570602/19522369/a39850da-961f-11e6-923c-b7c8291563f3.PNG)

**Comment by volkanceylan** [comment]
It only sets text, see FAQ
