### ISSUE TITLE
Clear Time value from DateTime Picker

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1325]
I believe is not possible to clear the entered value of on the TimeField part of the datetimepicker.

Combo should have either a blank value or a "reset" icon?!

**Comment by volkanceylan** [comment]
Did you really try save?! If you clear date part, time part goes.

**Comment by rgilsimoes** [comment]
Just not user friendly, but ok.

**Comment by volkanceylan** [comment]
Its just your opinion
