### ISSUE TITLE
HasRole

### ISSUE THREAD

**Issue by mrsjakie** [volkanceylan/Serenity#1327]
Hello @volkanceylan,
how can I use the HasRole function from PermissionService.cs in my own grid file?
I can use the Authorization.hasPermission but it doesn't check on role (string).
By the way, when I check by this f.or example: if (Authorization.hasPermission("Contracts:General")) then I get an error in firebug: An invalid or illegal string was specified or the following error: Error: Can't load script data: RemoteData.UserData!
throw new Error(Q.format("Can't load script data: {0}!", name));
What am I doing wrong?

Thanx in advance.

**Comment by volkanceylan** [comment]
There is no HasRole functionality. Use permissions.

**Comment by volkanceylan** [comment]
Check service side error code in network tab.

**Comment by mrsjakie** [comment]
Hello @volkanceylan. Thank you for the answers. The error about the remotedata is Authorization denied. I don't get this because the user has this explicit permission. When I remove the line the user can access the rows. Very strange. 
Can you tell me what the function HasRole in permissionservice.cs is used for?

Thanks in advance.

**Comment by adhikamafran** [comment]
@mrsjakie 
if you want to use hasRole, try 
`Authorization.userDefinition.Roles.indexOf("myrole") > -1`
because userDefinition.Roles type is string. 

Other way you can add code in Authorization.ts

```
export function hasRoles(roleName: string) {
        let ud = userDefinition;
        return ud.Username === 'admin' || ud.Roles.indexOf(roleName) > -1;
    }
```

I did it in my project, hope this help your problem.

**Comment by mrsjakie** [comment]
Thank you @adhikamafran, I appreciate your mail with a solution.

**Comment by PostGrad** [comment]
@adhikamafran, can you please send me the mail with solution file for this issue #1327 ? My emailId is pranaypatel008@gmail.com. Thanks in advance.

**Comment by ga5tan** [comment]
@adhikamafran can u plz email me solution too

thx

**Comment by Rajendra1002** [comment]
if (Authorization.isInRole("User")) {

                Serenity.EditorUtils.setReadonly(this.form.EmployeeName.element, true);
}
