### ISSUE TITLE
Error when using sergen to update code

### ISSUE THREAD

**Issue by scharada** [volkanceylan/Serenity#1329]
Hi. using sengen the first time runs quiet nicely. after adding fiels and modifying tables, runningsengen again throws an error saying that kdiff3 should be added to the codegenerator.config file.... 
1 - i can't find the config file
2 - after installing kdiff3, kdiff windows for each updated file appears and can't merge because of a conflict... besides the fact that i end up with tons of kdiff windows to deal with ... any idea what's going on ?

3 - there seems to be a bug in the database creation code (SiteInitialization.Migrations.cs in app_start) :
  var isLocalServer = serverConnection.ConnectionString.IndexOf(@"(localdb)\", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    serverConnection.ConnectionString.IndexOf(@".\") >= 0;

this  takes .\sqlexpress as localdb ... removing the 
 || serverConnection.ConnectionString.IndexOf(@".\")   corrects it.

**Comment by volkanceylan** [comment]
First of all, you shouldn't generate two times using Sergen. Anyway, if you still do, Sergen does its best to not override changes you might have made. So it's not logical complaining about this. If you don't want old files, then delete them before generating code, period. There is a whole chapter devoted to code generator config file in guide. 

You are free to change checks there as you like, or remove it completely.

**Comment by scharada** [comment]
i am not complaining. just reacted to the exception thrown by the tool... 
removing all the files will do, i did not think it was necessary since you even show in the animated gif that you use sengen to regenerate again  after modifying the database, otherwise , what migrations are there for ...
if i misunderstood the concept, please point me to where this is explained and i'll read it to understand how it works.

**Comment by volkanceylan** [comment]
See guide.
