### ISSUE TITLE
Question: What is the best way to do the following...?

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#133]
Using the Northwind database as an example:

1. Add a string field to the "Orders" table called "InvoiceNumber".
2. Add a table called "Settings" with the following columns
	a. SettingsId (Int32 ,Primary Key)
	b. InvoicePrefix (String)
	c. NextInvoiceID (Int32, Defaults to 1)
3. The "Settings" table is populated with one record on initialization.
4. Add an "InvoiceNumber" field to the Order form.
5. When the user selects "New Order" from the Orders page, the "InvoiceNumber" field is pre-populated from the values from the Settings table in the format "[Prefix]-[NextId]".
6. When the Order saved, the value of "NextInvoiceId" in the Settings table is incremented by one.
7. If user selects New Order again, the "InvoiceNumber" should be populated with the new "NextInvoiceId" value.

I think I know how to do steps 1-5.  Not sure about 6-7.

**Comment by volkanceylan** [comment]
You should handle step 6 and 7 by overriding AfterSave of MySaveHandler.

**Comment by brettbeard** [comment]
Okay, I added the below code for the equivalent of my "OrderRepository".  It updates the Settings table correctly but when I click "New Order" on the Orders page the previous value of "NextInvoiceId" is displayed.  It appears as if SettingsRow (in the script) is not refreshed.

```
protected override void AfterSave()
{
	base.AfterSave();

	if(this.IsCreate)
	{
		var rep = new SettingsRepository();                    
		var settings = rep.Retrieve(this.Connection, new RetrieveRequest { EntityId = 1 });
		int nextId = settings.Entity.NextAuditIdentifier.Value;

		var save = new SaveRequest<Entities.SettingsRow>();
		save.Entity = settings.Entity;
		save.Entity.NextAuditIdentifier = nextId + 1;
		var response = rep.Update(this.UnitOfWork, save);
	}
}
```

**Comment by volkanceylan** [comment]
Override OnSaveSuccess method in dialog, call Q.ReloadLookup(SettingsRow.LookupKey). Script side has no idea that source data changed at server side.

Anyway, this will resolve your problem now, but if you have two users, one of them adds a new records, other will still have old lookup, thus will try to use same number. So call ReloadLookup before setting next invoice number in dialog, e.g. AfterLoadEntity

**Comment by brettbeard** [comment]
Cool.  That was the step I was missing.  Thanks, again.
