### ISSUE TITLE
Automatic grid resizing in dialog tab

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#1331]
Hi,

I added a grid in a tab dialog below a form. 

Everything's working fine after some less twiking, though, I cannot figure out how to ask for get data when resizing the dialog box. eg on change rearange grid data.

I blocked the form then on resize it is still visible.
`<div id="~_Toolbar" class="s-DialogToolbar">
</div>

<div class="s-Form s-DialogContent">
    <form id="~_Form" action="">
        <div class="fieldset ui-widget ui-widget-content ui-corner-all">
            <div id="~_PropertyGrid"></div>
            <div class="clear"></div>
        </div>
    </form>
</div>

    <div id="~_Tabs">
        <ul>
            <li><a href="#~_TabListMap"><span>Scenario in List</span></a></li>
            <li><a href="#~_TabScenarios"><span>Scenario Available</span></a></li>
        </ul>
        <div id="~_TabListMap" class="tab-pane s-TabList">
            <div id="~_ScenarioTabMapGrid">
            </div>
        </div>
        <div id="~_TabScenarios" class="tab-pane s-TabScenarios">
            <div id="~_AllScenariosGrid">
            </div>
        </div>
    </div>
`

`.s-Report-ScenarioListDialog {
     >.size {width: 750px; height:780px; left:155px; top:55px; }
    .caption { width: 150px; }
    .s-Form{min-height:150px; max-height:150px;}    
    .grid-container{height:450px}
}
`

**Comment by edson** [comment]
Hi, there.
Sorry, I couldn't understand your problem... Did you mean resizing the canvas from slickgrid?

If that's the case, you should do something like this in your xyzdialog.ts

 ```
private _MyXYZGrid2: MyXYZGrid2;

        constructor() {

            super();

            this._MyXYZGrid2= new MyXYZGrid2(this.byId('MyXYZGrid2'));
        }



        dialogOpen() {
            var selfDialog = this;
            super.dialogOpen();
            this.element.on("dialogextendmaximize", function (event, ui) {
                selfDialog._MyXYZGrid2.slickGrid.resizeCanvas();
            });
            this.element.on("dialogextendrestore", function (event, ui) {
                selfDialog._MyXYZGrid2.slickGrid.resizeCanvas();
            });
            this.element.on("dialogresize", function (event, ui) {
                selfDialog._MyXYZGrid2.slickGrid.resizeCanvas();
            });

        }
```

Regards

**Comment by Boumboumjack** [comment]
Hi,

Thak you. Your advice helped me.

The issue I had was that I did not set the class of the tab as "s-DialogContent", the resize was not grabing the correct dimension. I guess there is an automatic resizer in s-DialogContent. But your lines reized correctly the row though.

`<div class="s-Form s-DialogContent FormTitle">
    <div id="~_Toolbar" class="s-DialogToolbar">
    </div>
    <form id="~_Form " action="">
        <div class="fieldset ui-widget ui-widget-content ui-corner-all">
            <div id="~_PropertyGrid"></div>
            <div class="clear"></div>
        </div>
    </form>
</div>

<div id="~_Tabs" class="s-Form **s-DialogContent**">
    <ul>
        <li><a href="#~_TabListMap"><span>Scenario in List</span></a></li>
        <li><a href="#~_TabScenarios"><span>Scenario Available</span></a></li>
    </ul>
    <div id="~_TabListMap" class="tab-pane s-TabList">
        <div id="~_ScenarioTabMapGrid">
        </div>
    </div>
    <div id="~_TabScenarios" class="tab-pane s-TabScenarios">
        <div id="~_AllScenariosGrid">
        </div>
    </div>
</div>`

`.s-Report-ScenarioListDialog {
     >.size {width: 750px; height:780px; left:155px; top:55px; }
    .caption { width: 150px; }
    .FormTitle{min-height:190px; max-height:190px;}
}`

The formtitle block the first 3 fields that remains above the tabs.

**Comment by edson** [comment]
You're welcome. Actually the css resizes itself, but slickgrid needs some help when there is too much columns to display or if its maximized. Maybe it has been addressed in new updates, but anyway, glad it helped somehow.

Regards.
