### ISSUE TITLE
Passing data between Page.cs and CUstom Filter .ts

### ISSUE THREAD

**Issue by paulobriennz** [volkanceylan/Serenity#1333]
Hi,

I have implemented a custom filter using the example under GridFilteredByCriteria.  In the example it references the columns, but just uses static values like '1' or 'Condiments'

I want to pass a value to the .ts file I can use in my criteria query - the value/variable I have defined in the xxPage.cs file

In the xxxPage.cs file, I am getting User.Identity.Name and doing a lookup in another table to get a CompanyId value.. I want to use this CompanyId value in my query in the Criteris .ts file but not sure how to get this value to the .ts file

I understand (not using typescript) I could then add the value to the Model and pass the model to the ..cshtml page, but not sure when typescript is being used... (typescript newbee).

Any help much appreciated.

**Comment by adhikamafran** [comment]
@paulobriennz 
Have you tried inherit ServiceResponse/ListResponse ? 
like this

```
public class CustomListResponse<T> : ListResponse<T>
{
      public string filter { get; set; }
}

```
then return it in your endpoint, it should be able to pass from cs to ts. hope this help.

**Comment by volkanceylan** [comment]
TypeScript is just javascript. If you are going to use that value in that CSHTML page, render that value to a global javascript variable in a script block. Then, where you need that value, just reference it from typescript like (window as any).someVariable

Another option is to do just like ScriptUserDefinition, e.g. a dynamic data script.
