### ISSUE TITLE
How to handle Self referencing table

### ISSUE THREAD

**Issue by WestleyHoxton** [volkanceylan/Serenity#1335]
Hi Volkan

I have table called JobType with the following columns

JobType varchar(1)   (PK)
JobTypeDesc  varchar(50) 
NextJobType(1)

This table reference itself on JobType to NextJobType.

Here is the issue
The grid is displaying the desciption of NextJobType quiet well. However when i open the dialog for editing, the dropdown for NextJobTYpe which is suppose to diplay the description display the Code rather than the description. Where am I going wrong? Your help is highly appreciated

All other drop downs are showing correct value. I just have an issue with this referencing table (This is the only referencing table in the database).  I am unable to change the design of the database at this stage.

Following is my code

[ConnectionKey("CTL"), DisplayName("CTRL_JOB_TYPE"), InstanceName("CTRL_JOB_TYPE"), TwoLevelCached]
    [ReadPermission("Administration")]
    [ModifyPermission("Administration")]
    [LookupScript("CTL.JOB_TYPE")]
    public sealed class CtrlJobTypeRow : Row, IIdRow, INameRow
    {
        [DisplayName("Job Type"), Column("JOB_TYPE"), Size(1), PrimaryKey, QuickSearch]
        public String JobType
        {
            get { return Fields.JobType[this]; }
            set { Fields.JobType[this] = value; }
        }

        [DisplayName("Job Type Desc"), Column("JOB_TYPE_DESC"), Size(50)]
        public String JobTypeDesc
        {
            get { return Fields.JobTypeDesc[this]; }
            set { Fields.JobTypeDesc[this] = value; }
        }

  [DisplayName("Next Job Type"), Column("NEXT_JOB_TYPE"), ForeignKey("[ctl].[CTRL_JOB_TYPE]", "JOB_TYPE"), LeftJoin("jNextJobType"), TextualField("NextJobTypeJobTypeDesc"), LookupInclude]
        [LookupEditor(typeof(CtrlJobTypeRow))]
        public String NextJobType
        {
            get { return Fields.NextJobType2[this]; }
            set { Fields.NextJobType2[this] = value; }
        }
 [DisplayName("Next Job Type Desc"), Expression("jNextJobType.[JOB_TYPE_DESC]")]
        public String NextJobTypeJobTypeDesc
        {
            get { return Fields.NextJobTypeJobTypeDesc[this]; }
            set { Fields.NextJobTypeJobTypeDesc[this] = value; }
        }

  public class RowFields : RowFieldsBase
        {
            public StringField JobType;
            public StringField JobTypeDesc;
            public StringField NextJobType;
        
            public StringField NextJobTypeJobTypeDesc;
            public Int32Field NextJobTypePackageId;
            public StringField NextJobType2;
                 

            public RowFields()
                : base("[ctl].[CTRL_JOB_TYPE]")
            {
                LocalTextPrefix = "EDWMetaDataManagment.CtrlJobType";
            }
        }

**Comment by volkanceylan** [comment]
Set name field for your job row to Description.

**Comment by WestleyHoxton** [comment]
Hi Volkan
Please excuse my ignorance. Which name field in the JobTypeRow ?

I have two fields
public String JobTypeDesc

public String NextJobTypeJobTypeDesc


Thanks for your help

**Comment by WestleyHoxton** [comment]
Got it sorted. Its now working. Thanks for your help

Regards

Westley
