### ISSUE TITLE
Demo UserName and Password？

### ISSUE THREAD

**Issue by ghd258** [volkanceylan/Serenity#1336]
Demo UserName and Password？

**Comment by Estrusco** [comment]
Have you try with user: admin and password: serenity    ?

**Comment by ghd258** [comment]
http://serenity.is/demo/Account/Login?ReturnUrl=%2fdemo%2f      Serene   and   Serenity

**Comment by Estrusco** [comment]
What do you mean?
I enter just now with admin and serenity

**Comment by VictorTomaili** [comment]
Read placeholder text 

![image](https://cloud.githubusercontent.com/assets/2023440/19595647/8cf1d688-9793-11e6-898d-1311bea9a5c0.png)
