### ISSUE TITLE
TeamFoundation Problemi

### ISSUE THREAD

**Issue by ComertAhmetSahin** [volkanceylan/Serenity#1337]
Modülleri Serenity.CodeGenarator ile oluşturuyoruz.
(Get Latest Version / Check In) yaptığımızda Modül ve servertyping leri include exclude etmediğimiz taktirde TeamFoundationa düşmüyor. 
Ayrıca  include/exclude işlemlerine dikkat etmemize rağmen çoğu zaman eksik dosya senkronizasyonu yapıyor. Sürekli elle müdahale etmek zorunda kalıyoruz.

Serenity Framework ile TeamFoundation kullanamıyormuyuz yoksa ilgili bir ayar mı mevcut? 
Çözüm öneriniz nedir?

**Comment by VictorTomaili** [comment]
Serenity platform ile alakalı birşey değil. TFS ayarlarınız ile ilgili

**Comment by volkanceylan** [comment]
Serenity.CodeGenerator.config te TFSIntegration: true yapın.
