### ISSUE TITLE
updating slickgrid for every inputschange

### ISSUE THREAD

**Issue by mantiklas** [volkanceylan/Serenity#1338]
![quantityvsprice](https://cloud.githubusercontent.com/assets/21164515/19592188/350919bc-97ad-11e6-8084-47a0be617e3e.PNG)

Hi @volkanceylan  ,In Product Module of serene, you can manually input the unit price, and quantity, I added column name unitprice*quantity.  I want to update the newly created column  every inputchange. I dont know how to pass the value.. Thanks

**Comment by volkanceylan** [comment]
You should bind to keyup, keydown etc events but i wouldn't suggest this as you'll run into invalid value problems.

**Comment by mantiklas** [comment]
Oh thanks  @volkanceylan , lastly, the edited textbox doesn't reflect on my  PDF generation, However in serene 1 and serene 2, Inputchanged (pending changes)  or edited texbox such as unitprice , unit in stock still reflect on the generated PdF. I don't know what is the problem... I already copy all the contents of Product grid.. Thanks

**Comment by volkanceylan** [comment]
Sorry code is there

**Comment by mantiklas** [comment]
I already Copied everything from the Product Grid... all functions.. I don't if there is dependency.  I don't know why the pendingchanges doesnt reflect on the generated PDF.
