### ISSUE TITLE
xyzRow.cs; field; DefaultValue; dynamically set DefaultValue(xyz)

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#134]
Hi JaiQ,

John Ranger here again :-)

I have a table named Costcenter which (among many other fields) has a field "isDefault" of type bit. (Only) one of the costcenter records has this bit set to true (because it is the Default costcenter).

In the Definition of ClientsRow.cs of the Costcenter_ID field which has a foreign key ref to the Costcenter table's field "Costcenter_ID", I can set the DefaultValue(1) which correctly fills in the costcenter_ID of 1 when doing an add Client Action.

I now want to dynamically populate the "x" in DefaultValue(x) but somehow only directly typed value are accepted (please forgive me my lack of knowledge as this seems a Basic knowledge theme).

How can I dynamically populate the DefaultValue(???)

Thanks again for your time and your valuable Feedback.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Hi Ranger, 

DefaultValue attribute can't do that. You should have a lookup of that costcenter table with default column included (LookupInclude).

Then, override AfterLoadEntity of ClientsDialog, find default cost center from CostCenterRow.Lookup.Items, then set its id to form like 

```cs
override AfterLoadEntity(...)
{
form.CostCenterId.Value = CostCenterRow.Lookup.Items.First(x => x.IsDefault).CostCenterId.ToString();
}
```

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your very fast answer.

I have tried that but somehow... CostCenterRow.Lookup.Items doesn't have a method ".First" - at least not in my Environment.

My Environment: 
Serenity Level: 1.9.2
Project based on Serene 1.8.20 or so

In the declaration part of xyzDialog.cs, I am using: 

using CostCenterRow = ClientManagement.Stammdaten.CostcenterRow;

then my AfterLoadEntity method Looks like this:

protected override void AfterLoadEntity()
        {
            base.AfterLoadEntity();

            if (IsNew)
            {
                form.CostCenter_ID.Value = CostCenterRow.Lookup.Items.First(x => x.IsDefault).CostCenter_Id.ToString();
            }
        }

What do I have to do in order to have the ".first" method within items?

With Kind regards,

John

**Comment by stickybro** [comment]
Did you include Linq?

using System.Linq;

**Comment by volkanceylan** [comment]
Yes, Linq, plus IsDefault == true. Serenity rows are nullable.

**Comment by JohnRanger** [comment]
Thanks ;-) that has resolved the ".First" Problem. 

For the benefit of other Readers:

The Linq Expression (x => x.IsDefault) did complain that it cannot convert a 'bool?' to 'bool'.

I had to cast it like this:

form.Costcenter_ID.Value = CostCenterRow.Lookup.Items.First(x => (bool)x.IsDefault).CostcenterId.ToString();

@JaiQ: Thanks again for your great and precise help.

With Kind regards,

John

**Comment by volkanceylan** [comment]
If in any way IsDefault is null, this will raise a cast exception, == true is on safe side.

**Comment by JohnRanger** [comment]
Hi JaiQ,
How would I write then the whole Linq query correctly? I am a total novice to this... :-(

with Kind regards,

John

**Comment by volkanceylan** [comment]
First(x => x.IsDefault==true)

**Comment by JohnRanger** [comment]
Thanks JaiQ.

While testing the whole thing, I have seen that the whole Dialog does not Show up (on pressing the new button), when absolutely None of the records in the Costcenter table have the isDefault set to true.

I have split the command into two separate Statements but the dialog does not show up even  if only the first line is there.

-----------------------------
var Costcenter_ID = CostCenterRow.Lookup.Items.First(x => x.IsDefault == true).CostcenterId.ToString();

if (Costcenter_ID != null) { form.Costcenter_ID.Value = Costcenter_ID; }
-----------------------------

Although this Situation "should" never occur, by human error this could happen and I would like to make the Dialog more robust.

I have tried to put the two Statements within a try-catch block but this didn't impreove the Situation.

the Goal is to not modify the value of CostCenter_ID field within the delivery table in case the Costcenter-Table has no record where isDefault = true and so just Show the Standard "-select-" in the dialog. But the Dialog should not be blocked from appearing.

How would I "treat" this line of code in order to make it not block the Dialog?

Thanks again and

with Kind regards,

John

**Comment by volkanceylan** [comment]
var Costcenter_ID = CostCenterRow.Lookup.Items.FirstOrDefault(x => x.IsDefault == true).CostcenterId.ToString();

if (CostCenter_ID != null)
form.XYZ.

**Comment by JohnRanger** [comment]
Hi JaiQ,

many thanks for your Patient Support. I have definitely to study this Linq Thing.

Works perfectly.

I wish you a nice evening.

With Kind regards,

John.

**Comment by JohnRanger** [comment]
For the benefit of other Readers:

The final - fully working code - which sets Default values for 3 fields Looks like this:

(within xyzDialog.cs)

---------------------------------------
        protected override void AfterLoadEntity()
        {
            base.AfterLoadEntity();

            if (IsNew)
            {

                var DefaultCostcenter = CostCenterRow.Lookup.Items.FirstOrDefault(x => x.IsDefault == true);
                if (DefaultCostcenter != null) { form.Costcenter_ID.Value = DefaultCostcenter.CostcenterId.ToString(); }
        
                var DefaultLifeCycleStatus = LifeCycleStatusRow.Lookup.Items.FirstOrDefault(x => x.isDefault==true);
                if (DefaultLifeCycleStatus != null) { form.LifeCycleStatusId.Value = DefaultLifeCycleStatus.LifeCycleStatusId.ToString(); }

                var DefaultLocation = LocationRow.Lookup.Items.FirstOrDefault(x => x.isDefault==true);
                if (DefaultLocation != null) { form.LocationId.Value = DefaultLocation.LocationId.ToString(); }

            }

        }

------------------------------
