### ISSUE TITLE
2.5.0 Upgrade Guide

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1342]
2.5.0 updates many packages, including jQuery, jQuery UI, bootstrap etc. Especially jQuery v3 has many changes. Even though i tried to fix all compatibility problems, there might be some i missed.

After updating to Serenity 2.5.0, do following:

In Views/Shared/_Layout.cshtml, find:

``` js
            height -= $('header.main-header').outerHeight();
            height -= $('section.content-header').outerHeight();
            height -= $('footer.main-footer').outerHeight();
```

replace with:

``` js
            height -= $('header.main-header').outerHeight() || 0;
            height -= $('section.content-header').outerHeight() || 0;
            height -= $('footer.main-footer').outerHeight() || 0;
```

On top of Modules/Common/Reporting/PdfExportHelper.ts, add this line:

``` ts
﻿declare var jsPDF;
```

Open your packages.config and remove this line:

``` xml
<package id="jquery.event.drag" version="2.2.0" targetFramework="net45" />
```

We are now also using TypeScript 2.0. Just install its latest version (2.0.3 as of writing) from http://typescriptlang.org 

It will ask you to upgrade your project to use newer TypeScript tools version. If it doesn't find this line:

``` xml
<TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>
```

and replace with 

``` xml
<TypeScriptToolsVersion>2.0</TypeScriptToolsVersion>
```

**Comment by Estrusco** [comment]
Thank you!

**Comment by marcobisio** [comment]
Thanks @volkanceylan!
I'm doing some tests, but the script bundler seems to be broken:
![image](https://cloud.githubusercontent.com/assets/17425690/19627152/bde450aa-9940-11e6-9b4c-6c52d671c139.png)

The screenshot is taken from a new Serene template just created...viceversa with the script bundler turned off, everything seems to be ok...

Thanks
Bye

**Comment by volkanceylan** [comment]
Either upgrade to 2.5.2 or add a ";" at the end of jquery.event.drag.min.js

**Comment by she-ll-b-rite** [comment]
Hi Volkan. FYI, couple of things I've noticed since the 2.5.2 upgrade:

1) There's a significant lag in loading of most grid pages. I spun up a new project using the latest 2.5.2 template to compare and I notice the same lag in the Northwind pages. I'm using IE 11 for test / debugging.

2) I had the "ScriptBundling" option set to false before the upgrade and after upgrading I was getting the following error on every grid page. `"0x800a001c - JavaScript runtime error: Out of stack space"` Again I tested on the new project and same error. Turning ScriptBundling to true, stops the error.

HTH

**Comment by volkanceylan** [comment]
It's about slickgrid and jQuery v3, which returns non-integer height values, that causes slickgrid to relayout indefinetly. Hopefully fixed in 2.5.3

**Comment by marcobisio** [comment]
Thanks @volkanceylan now the script bundler it's working fine!
About the @she-ll-b-rite issue, I've no lag in Chrome...it's something related only to IE11?

Thanks

**Comment by volkanceylan** [comment]
Yep, it should be only in IE11

**Comment by she-ll-b-rite** [comment]
2.5.3 has fixed both issues. Thx.

**Comment by marcobisio** [comment]
Thanks @volkanceylan.
