### ISSUE TITLE
Layout inconsistency

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1343]
I've got a problem that is somehow strange, some of my pages have the right menu misconfigured like so:
![image](https://cloud.githubusercontent.com/assets/10889019/19619451/c60f6bac-985f-11e6-9cfd-c79c586012c5.png)

and can´t seem to find the problem, my references are same to other pages:
![image](https://cloud.githubusercontent.com/assets/10889019/19619461/2600b372-9860-11e6-9b10-790c261406b5.png)

But in other pages the inspect gives (correct ones):
![image](https://cloud.githubusercontent.com/assets/10889019/19619471/5d2cbd8c-9860-11e6-9dcd-6a4e95174645.png)

And others like this one it gives this:
![image](https://cloud.githubusercontent.com/assets/10889019/19619483/925558de-9860-11e6-8996-a23af8f22090.png)

**Comment by volkanceylan** [comment]
Wild guess different version of Select2, or element with same ID.

**Comment by brunobola** [comment]
Thanks @volkanceylan same element ID...
Awesome help....
