### ISSUE TITLE
FileUploadEditor

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1344]
So I have been trying to figure out how the FileUploadEditor works, can someone point me to the location of the source? I did a search for it but only found js entries, is it not written in c#?

Thanks!!

**Comment by jdready5** [comment]
Try this, it's your FilePage.cs you should be able to find what you need there
[https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Common/File](url)

**Comment by VictorTomaili** [comment]
https://github.com/volkanceylan/Serenity/tree/master/Serenity.Web/Upload

**Comment by wdhodges** [comment]
Great thank you guys. I didn't know the Serenity.Web/Upload was that intense! Thank you @jdready5 and @VictorTomaili
