### ISSUE TITLE
Add textbox in grid toolbar and set value for column?

### ISSUE THREAD

**Issue by ngocnb90** [volkanceylan/Serenity#1346]
Help me!

how can add textbox in quick bar and using keyup set value for colums
![capture](https://cloud.githubusercontent.com/assets/23022595/19633544/2558c508-99dd-11e6-9879-d3883e7bd273.PNG)

if textbox (red) is keyup value => all value row of column(yelow) = texbox value

**Comment by Estrusco** [comment]
Add quickfilter attribute to field, and see https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InitialValuesForQuickFilters

**Comment by ngocnb90** [comment]
Thanks @Estrusco
