### ISSUE TITLE
few Issues

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1347]
Dear Volkan
I got few issues as
1. In your demo website serenity.is/demo
Basic samples -> Dialogs-> Default Values in New Dialog
Pressing "Add Order From Queen" gives following error
TypeError: Serene.Northwind.ShipperRow.getLookup(...).items.filter(...)[0] is undefined

2. In case of IE11 or Maxthon browser ( version 4.4.8.200 )
"Select With Hardcoded Values" sample does not show any thing, but it does show in Firefox 49.0.2
![serenity](https://cloud.githubusercontent.com/assets/19570368/19634484/40f48fe4-99d9-11e6-96e1-2e612b7afa1c.png)

3. can you provide link for the sample 
"showing another form in tab sample"

regards
Shailesh

**Comment by volkanceylan** [comment]
It uses shipper name, so if somebody changes the name, it fails.

http://serenity.is/demo/BasicSamples/OtherFormInTab
