### ISSUE TITLE
Someone can share for me a project using  stored proc ( view , insert, update)). Thanks

### ISSUE THREAD

**Issue by ngocnb90** [volkanceylan/Serenity#1348]

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/StoredProcedureGrid

**Comment by ngocnb90** [comment]
Thanks @Estrusco but i dont know create file  CustomerGrossSalesListRequest in TS file
![1](https://cloud.githubusercontent.com/assets/23022595/19636059/f5f0859e-99f0-11e6-9c58-71a3d57c6a27.PNG)

its in \Modules\Common\Imports\ServerTypings
![image](https://cloud.githubusercontent.com/assets/23022595/19636107/53f27cce-99f1-11e6-918f-0a2f1e83b41a.png)

please help!

**Comment by Estrusco** [comment]
You must create a C# class derived from ListRequest (or other Request or Response) then transform all T4 templete and those create for you the .ts relative file

See CustomerGrossSalesListRequest.cs in example
The T4 transformation is in Compile menu.

**Comment by ngocnb90** [comment]
Thanks @Estrusco

**Comment by ngocnb90** [comment]
@Estrusco  i try T4 template but not create file.ts
with output

Transforming templates for all project items.
-------------------------------------
Transforming template ClientTypes.tt with TextTemplatingFileGenerator ... failed.
Transforming template MVC.tt with TextTemplatingFileGenerator ... succeeded.
Transforming template ServerTypings.tt with TextTemplatingFileGenerator ... failed.
-------------------------------------
Text templating transformation complete.

**Comment by volkanceylan** [comment]
Use that request in some service. Search project for that request and see what you miss.
