### ISSUE TITLE
Do you want an OAuth implementation? I have one that I'm willing to share...

### ISSUE THREAD

**Issue by James-A-White** [volkanceylan/Serenity#1349]
Hello Volkan,  

I have implemented OAuth authentication using Azure App Services and Serenity.  The good news is that it does not require any NUGET packages and it works for Facebook, Twitter, Google, standard Microsoft accounts and Azure Active Directory.  It's also fairly lightweight with only a few files added to the Serenity project. The downside is that it works by leveraging Azure App Services so it may only work if the Serenity App is deployed on Azure.  There might be a way to deploy on-site with a small stub app in Azure, but this is not my use case, so I have not investigated this option.

I would be happy to share the code and write the necessary documentation.  Let me know if I can contribute back to the project! I would like to both give and take from this open source effort!

One warning, however... I'm more of a hacker than a professional programmer, so I'm guessing you will want to take a good look at my code before committing it to the main branch.  :-)

Thanks,

James

**Comment by volkanceylan** [comment]
Hi James,

Thanks, i'd like to see any such contribution, and this one is certainly one of most requested. If you can share your changes as a Gist, or similar, i'd have a look and decide if it is better to go in a wiki or optional feature enabled by some setting etc. Not requiring Nuget package or DLL is certainly a plus, as it won't bring an additional dependency.

**Comment by James-A-White** [comment]
Volkan, here are the OAuth files you requested:

https://gist.github.com/James-A-White/641bde233da6813d5c3be371738b56aa

I think these are all of the files required... let me know if you think something is missing.  

If you want to see it in action, feel free to log in to my test instance. 

https://harriercentralweb.azurewebsites.net/Account/Login?ReturnUrl=%2f

Additionally, you will need to configure Azure App Services for each of the 5 providers they support, which also involves going to those providers and setting up your app.  I would be happy to explain how this is done if the link below is not thorough enough:

https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-how-to-configure-google-authentication/

Please keep in mind, however, once you authenticate for the first time, you will not be able to access any information because you will not have any roles assigned to you.  It might be an interesting feature to include a flag in the roles table that indicates that the Serenity framework should automatically add that role to new users when they first authenticate. This way people can create an account and start immediately accessing information. There may be another way to do this that I have not thought of yet.

One last note: This has not been thoroughly tested.  I have logged in with each of the four providers and have seen the credentials being populated into the database. I have also assigned roles and permissions to those uses and things seem to be working well. I do not know the behavior of the system when an authentication token expires. I think it should simply ask you to log in again.  Bottom line: I'm not yet ready to offer a warranty on this code!  :-)

**Comment by James-A-White** [comment]
Updated the Gist... I had an error in the Google code that prevented the e-mail from being properly recorded.  Also I now capture the nameidentifier and store it in the PasswordHash field just in case we ever would need access to it.  Happy to answer questions if you have them.

**Comment by volkanceylan** [comment]
Thanks again @James-A-White, for great looking sample, and well documented code. I don't have much experience with Azure, so it will take some time for me to test it myself, understand and improve it if needed. But i'll try to add it to Serene, kinda blindly, with login screen parts commented out, so you and others can try and let me know if it is working as is.

**Comment by James-A-White** [comment]
If you want a little primer on Azure, I would be happy to guide you through it.  it is very, very easy to get Serenity based apps running in Azure.  I'd even be happy to create a free Azure account and share the credentials with you.  I'll then upload a Serenity app with OAuth and get it running and share the code with you.  This way, we can give you an "express lane" ride into the Azure cloud.  Happy to support in whatever way I can!

Jw

**Comment by James-A-White** [comment]
Volkan,

I've noticed a very strange behavior when logging in using Azure OAuth. I can successfully log in using Facebook, Google and Twitter, but when I go to log in using Microsoft the Authorization.UserId value does not get set... it remains null even though the Dependency.Resolve<IUserRetrieveService>().ByUsername(username) is returning a valid user record.  I think this is new behavior with the most recent framework update because when I originally implemented OAuth I tested each case. I'm a bit baffled why this would be the case, but it is something happening within the framework.

I don't know if you have had the chance to look at the OAuth stuff, but if you have, perhaps you can look deeper into the framework and see if you can figure out why this is happening.

Thanks!

James

**Comment by James-A-White** [comment]
I've updated the gist with the error handling code in OAuthService if you want to see where it is happening.

https://gist.github.com/James-A-White/641bde233da6813d5c3be371738b56aa

Thx!

J

**Comment by volkanceylan** [comment]
I couldn't try it yet, but it might be a simple caching issue.

**Comment by James-A-White** [comment]
The GIST has been updated to include code that will grab the URL to the profile picture (for Google and Facebook, not MS or Twitter yet) and insert it into the database so it can be accessed by Serenity.  I have had to also make a small modification to the _Layout.cshtml file to ensure that UserImage strings that have full URLs are not processed through the VirtualPathUtility. This has also been added to the GIST.  GIST has also been made public (not that this matters too much).  

Here's the link:

<script src="https://gist.github.com/James-A-White/641bde233da6813d5c3be371738b56aa.js"></script>

**Comment by volkanceylan** [comment]
Let's add to wiki for now. I don't have an Azure account to test at the moment. Dear Microsoft rejected my application for BizSpark.

**Comment by ynotlim** [comment]
I was able to accomplish this by simple enabling the Authentication service in Azure w/out the code updates suggested by James.  

Everything works as expected and the user is added and logged in.  Only issue is that the logout link doesn't log the user out until you manually force it to : ../.auth/logout

**Comment by James-A-White** [comment]
Excellent… can you share more details on how you did this?  Where does the login button come from that allows users to choose to log in with OAuth vs. the built-in security mechanism? Otherwise, sounds pretty simple.

Thx!

James

**Comment by ynotlim** [comment]
I'm working on an update version of your Oauthservice class with the correct variables.  Will post here when done.

**Comment by James-A-White** [comment]
Super… I’m not very good at HTML so the buttons on my home page for logging in using Facebook, Twitter, etc. were not “responsive”.  If you can get that to work, that would be great as well.

Thanks!

James
