### ISSUE TITLE
Hiding field in create dialog but show field in update dialog

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#135]
Hi all,

I have a field which I want to Show only during update Dialog but not during create Dialog (a non-DB-mapped Checkbox with which the user can indicate that certain values from the master Dialog are updated within related fields in a number of associated assets).

So far I have managed to just hide the Checkbox (but not the associated Label) by using the code below within xyzDialog.cs:

---------------------------------------------------------
protected override void AfterLoadEntity()
        {
            base.AfterLoadEntity();

            if (IsNew)
            {
                      // *** Hide Update Values checkbox and label ***
                      form.UpdateInitialValuesOnAllAssociatedClients.Element.Hide();

           }
---------------------------------------------------------

How would I hide also the Label?

With Kind regards,

John

**Comment by volkanceylan** [comment]
Better place to do this is on UpdateInterface method

form.UpdateInitialValuesOnAllAssociatedClients.GetGridField().Toggle(IsUpdate)

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your very fast answer.

In the UpdateInterface() method, I don't have the IsUpdate property.

I only have IsNew.

Environment: Serenity 1.9.2

I have now successfully used:

form.UpdateInitialValuesOnAllAssociatedClients.GetGridField().Toggle(!IsNew);

Thanks again :-)

With Kind regards,

John

**Comment by volkanceylan** [comment]
It is IsEdit in dialog, sry, anyway it is same
