### ISSUE TITLE
Implement google maps

### ISSUE THREAD

**Issue by lubismargana** [volkanceylan/Serenity#1350]
Dear Mr. Volkan,

Do you have example, how to implement google maps in Serenity?

Thanks.

**Comment by sayuga** [comment]
That depends on what you wish to accomplish. If you just want to display locations, you're best bet is to implement it by simply embedding. 

If you want to use their API, I recommend using their web-based API. It's fairly well documented and there is more than enough sample code. You can then just use HTML to set the controls for it.

**Comment by lubismargana** [comment]
Thanks Mr Sayuga.
Do you have Example?

**Comment by rockayr** [comment]
Please add sample @sayuga 
Thanks @volkanceylan

**Comment by karimQasem** [comment]
Please add sample google maps
