### ISSUE TITLE
Concurrency handling

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1351]
Dear @volkanceylan,
there is already a concurrency mechanism at the moment in Serenity?
If I'm not wrong, the last user that save an entity overwrite any other possible change (if any).
I was reading (for example) such article:

https://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/handling-concurrency-with-the-entity-framework-in-an-asp-net-mvc-application

about implementation of optimistic concurrency in mvc...
In case there isn't already a concurrency handling in Serenity, I'll be glad to implement such functionality and share the code...

Thanks

**Comment by volkanceylan** [comment]
There is no such integrated feature, but there is also nothing that prevents you from implementing something similar with RowVersion.

**Comment by marcobisio** [comment]
Thanks for your feedback @volkanceylan...
I'll work on it then...

Bye

**Comment by Parbil** [comment]
Is there any update on this ? are we done with concurrency?
