### ISSUE TITLE
change QuickFilter to lookup not equal 

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1352]
Hi, 

is it possible to change [QuickFilter] to do a not equals to lookup?

**Comment by volkanceylan** [comment]
See how date range filter works

**Comment by abelal83** [comment]
I had a look at the examples however, I can't find any examples. Any particular bit of code you could point me to?

**Comment by volkanceylan** [comment]
See the stored procedure grid. You'll need to and a filter to Criteria parameter of request in handler.
