### ISSUE TITLE
Enable Role/Users to access all Tenants

### ISSUE THREAD

**Issue by Mumarda** [volkanceylan/Serenity#1353]
Hello:

We setup multi tenant feature for our system. But we have some user with a role where they need to access information from other tenants. 

Is there any way to setup a system role to access all tenants information?

Thank you very much

Alfredo

**Comment by awesomegithubusername** [comment]
Couldn't you just grant him the "Administration:Tenants" permission?

**Comment by Mumarda** [comment]
Hi, 

What you mean?

The idea is that they are just regular users. Not administrators.

**Comment by volkanceylan** [comment]
If user has permission X, don't apply filter, that's all.

**Comment by volkanceylan** [comment]
But i would let them change their tenant with a dropdown, or on login.

**Comment by Mumarda** [comment]
Hello Volkanceylan...

> But i would let them change their tenant with a dropdown, or on login.

But I need to add the user in all the tenants...

> If user has permission X, don't apply filter, that's all.

How can I do that?

**Comment by volkanceylan** [comment]
Put a dropdown, e.g. on top navigation, let those users change their tenant freely, and update their TenantId in users table when they do.

**Comment by Mumarda** [comment]
But is there any way they can see everything... because if they do not know in which tenant is the information that they need to update... they will not be able to find it.

**Comment by volkanceylan** [comment]
Just like we show admin all users.

**Comment by Mumarda** [comment]
But is there any way they can see everything... because if they do not know
in wich tenant is the information that they need to update... they will not
ve able to find it.
