### ISSUE TITLE
Tab level permissions

### ISSUE THREAD

**Issue by zeezment** [volkanceylan/Serenity#1354]
Hi Volkan,

Is it possible to have tab level permissions?

**Comment by VictorTomaili** [comment]
its possible. handle tab visibility on script side permission control. If required, check permission from repository or endpoint too.

**Comment by zeezment** [comment]
@VictorTomaili thanks for the quick reply! Is it possible to make them visible but not editable? Tried adding just readpermission on the tabbed row but it still allows me to edit it, as a last resort I will do it repository/grid level..?

**Comment by zeezment** [comment]
Also may I please get an example of the script side permission control?

**Comment by VictorTomaili** [comment]
there is methot for check permission. You can check edit permission for disable edit mod. 
https://github.com/volkanceylan/Serene/blob/0ff1ea9e9ab3f8003a456b585cf6b2b3934bf947/Serene/Serene.Web/Modules/Administration/User/Authentication/Authorization.ts#L10

**Comment by zeezment** [comment]
@VictorTomaili thanks!! Did something like 
`protected getPropertyItems() {
            let items = super.getPropertyItems();
            let per = Authorization.userDefinition.Permissions;
            if (Authorization.hasPermission("ServiceProviders:ServiceProviders:Read"))
                items = items.filter(x => x.readOnly = true);// != ServiceProvidersRow.Fields.ServiceProviderTypeId);
            return items;`
