### ISSUE TITLE
Multiple CascadeFrom

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1355]
Hi, how can i set my Cascade Editor  with multiple "CascadeFrom" parameters. I have in my XYZForm (for example):

```
[LookupEditor(typeof(Entities.ARow))]
public Int32 IdA { get; set; }
[LookupEditor(typeof(Entities.BRow))]
public Int32 IdB { get; set; }
[LookupEditor(typeof(Scripts.CLookup))]
public Int32 IdC { get; set; }
[LookupEditor(typeof(Scripts.DLookup), CascadeFrom = "IdA,IdB,IdC", CascadeField = "IdA,IdB,IdC")]
public Int32 IdD { get; set; }
```

Is this possible? I got no results in my dropdown editor.

Thanks in advance!

**Comment by volkanceylan** [comment]
No thats not possible.

**Comment by alanlopcu** [comment]
Thanks for your fast response. So, how should i filter my dropdown editor? I have already all my A,B,C variables from another dialog in my DEditDialog.

**Comment by edson** [comment]
Hi, there.

Just implement your own custom editor derived from lookup.

Regards

**Comment by alanlopcu** [comment]
Hi edson. Can u give me an example/url where i can learn how to do this? This is my last step in my project :sob:  . Thank you again!

**Comment by edson** [comment]
Hi, @alanlopcu . Unfortunally, I don't have the project where I did this with me right now. But you can gather the ideas with the select2ajax implementation here https://github.com/volkanceylan/Serenity/issues/375 and the lookupeditorbase https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Editors/LookupFilterByMultipleValues/ProduceSeafoodCategoryEditor.ts
Or just go with the select2ajax version... It needs some tweeks but its ideas may help you.

Whenever I can, I'll post an example if no one posts it with some solution made.

Regards

**Comment by dfaruque** [comment]
what about writing change event of those lookup editors and filter the target lookup items according to selection.

**Comment by alanlopcu** [comment]
Ok. How can i filter my target lookup?. For example in my XYZDialog.ts i should have something like:

```
var A = #; //From master dialog
var B = #; //From master dialog

this.form.IdC.changeSelect2(e => {
   var idC = Q.toId(this.form.IdC.value);
   if (idSpecification != null) {
      this.form.D.Select2values = DRow.getLookup().FilterBy(A,B,idC); //Need this line (How to filter my D Select2?)
   }
});
```

Or i'm totally wrong? Thank you again.

**Comment by dfaruque** [comment]
this.form.D.items = DRow.getLookup().filter(f => f.someField == idC && bla bla bla);

**Comment by edson** [comment]
Yep. that probably is easier. the idea of custom editor is the same, only that is reusable. You be good with this approach. Nice one @dfaruque . Good to learn new tricks to use in form.

Regards

**Comment by volkanceylan** [comment]
I'm not sure that works. Did you test it @dfaruque?

**Comment by volkanceylan** [comment]
At least it should be getLookup().items.filter(x => x...).map(x => new { id: "...", text: "..." } ) etc but i still don't recommend it.

**Comment by dfaruque** [comment]
I did this before. 
 `.map(x => { id: "...", text: "..." } )` 
I missed this one.

Btw, I am still novice. would you please tell us your way of doing such?

**Comment by alanlopcu** [comment]
Ok, thanks for your replies. I'm trying this:
---- XYZForm.cs ----
```
//...
[LookupEditor(typeof(Scripts.CLookup))]
public Int32 IdC { get; set; }
[LookupEditor(typeof(Scripts.DLookup))]
public Int32 IdD { get; set; }
//...
```
---- XYZDialog ----
//...
A=###; //From master
B=###; //From master
this.form.IdC.changeSelect2(e => {
    var idC = Q.toId(this.form.IdC.value);
    if (idC != null) {
        this.form.IdD.items = DRow.getLookup().items.filter(f => f.IdC === idC).map(f => {id:"",text:""});
    }
});
//...

I got this errors in my IdD,items assign:
Type 'void[]' is not assignable to type 'Select2Item[]'.
Type 'void' is not assignable to type 'Select2Item'.

Plus i don't know what should i put in my 'map': 'id' and 'text' elements. Without map i got the same error.

Thanks again people.

**Comment by volkanceylan** [comment]
What you should do is an editor like ProduceSeafoodCategoryEditor, add some properties to pass A, B, C values, filter by them in getItems method, and when editors for A, B, C changes call updateItems method of that editor.

**Comment by edson** [comment]
Hi, there.

Ok, so my editor sliced and simplified for tests in basic samples... I'm just beggining with this typescript thing... so any suggestions or critics are welcome.

Replace ProductRow with your lookupscript row: 
```
namespace Serene1.BasicSamples {


    @Serenity.Decorators.registerEditor()
    export class ProductMultipleCascadeEditor extends
        Serenity.LookupEditorBase<MultipleCascadeEditorOptions, Northwind.ProductRow> {

        protected extraCascadeFromList: Array<string>;
        protected extraCascadeFieldList: Array<string>;
        protected extraCascadeValuesList: Array<number>;

        constructor(container: JQuery, opt: MultipleCascadeEditorOptions) {
            super(container, opt);

            
            this.extraCascadeFromList = opt.extraCascadeFrom.split(",");
            this.extraCascadeFieldList = opt.extraCascadeField.split(",");


            if (this.extraCascadeFromList.length != this.extraCascadeFieldList.length) {
                Q.alert("CascadeFrom and CascadeField must have same number of names, string comma separated.");
                return null;
            }

            this.extraCascadeValuesList = new Array(this.extraCascadeFromList.length);
            this.bindExtraFrom();
        }

        public destroy(): void {
            this.unbindExtraFrom();
            super.destroy();
        }

        protected getLookupKey() {
            return Northwind.ProductRow.lookupKey;
        }

        
        protected getItems(lookup: Q.Lookup<Northwind.ProductRow>) {
            let results = super.getItems(lookup);
            if (this.extraCascadeFieldList)
                this.extraCascadeFieldList.forEach((item, index, array) => {
                    results = results.filter(x => x[item] == this.extraCascadeValuesList[index]);


                });

            return results;
        }

        private bindExtraFrom(): void {
            if (this.extraCascadeFromList == null || this.extraCascadeFromList.length == 0)
                return;
            this.extraCascadeFromList.forEach((item, index, array) => {

                var editor = Q.findElementWithRelativeId(this.element, item).tryGetWidget(Serenity.LookupEditor);
                if (editor != null) {
                    var self = this;
                    editor.element.on("change." + this.uniqueName, () => {
                        this.extraCascadeValuesList[index] = Number(editor.value) || 0;
                        this.updateItems();
                    });
                }

            });
            
            

        }

        private unbindExtraFrom(): void {
            if (this.extraCascadeFromList == null || this.extraCascadeFromList.length == 0)
                return;
            this.extraCascadeFromList.forEach((item, index, array) => {
                var editor = Q.findElementWithRelativeId(this.element, item).tryGetWidget(Serenity.LookupEditor);
                if (editor != null) {
                    var self = this;
                    editor.element.off("change." + this.uniqueName, () => {
                        this.extraCascadeValuesList[index] = Number(editor.value) || 0;
                    });
                }

            });

           
        }
    }

    export interface MultipleCascadeEditorOptions extends Serenity.LookupEditorOptions {       
        extraCascadeFrom?: string;
        extraCascadeField?: string;
    }
}
```

To use it, you can put it in your xyzform.cs 

```
        [ProductMultipleCascadeEditor(ExtraCascadeFrom = "CategoryID,SupplierID", ExtraCascadeField = "CategoryID,SupplierID")]
        public Int32 ProductSuplierTestId { get; set; }
```
or xyzrow.cs

```
        [DisplayName("Product Id Multiple test"), NotMapped]
        [ProductMultipleCascadeEditor(ExtraCascadeFrom = "CategoryID,SupplierID", ExtraCascadeField = "CategoryID,SupplierID")]
        public Int32? ProductSuplierTestId
        {
            get { return Fields.ProductSuplierTestId[this]; }
            set { Fields.ProductSuplierTestId[this] = value; }
        }
```


Best Regards
