### ISSUE TITLE
BooleanField == true? Error

### ISSUE THREAD

**Issue by iuryamicussi** [volkanceylan/Serenity#1356]
I'm trying to compare a BooleanField with the bool value true and the Visual Studio is giving me this error:
Error	CS0019	Operator '==' cannot be applied to operands of type 'BooleanField' and 'bool'.

The source:
var a = Serene1.Administration.Entities.UserRow.Fields;
if (a.RACS == true) // <-- Error right here..
{
       request.Criteria = new Criteria(MyRow.Fields.UserID.Name) == (IdUser);
}   

It must be some dumb thing that I am doing..

**Comment by VictorTomaili** [comment]
what is your class and method? maybe you need use `Row.RACS == true`
Fields is definition for sql query build and custom functionality. Values stored on Row class.

**Comment by Estrusco** [comment]
a.RACS is a field not a value. a.RACS[row].value is your value, where row is the entity you read

**Comment by volkanceylan** [comment]
Read your RACS property from Row.RACS, Old.RACS etc.

**Comment by iuryamicussi** [comment]
Thanks  VictorTomaili, Estrusco and volkanceylan. Thanks to you I solve my problem. 
The solution:

var a = Administration.Entities.UserRow.Fields;
var RACS = connection.Single<Administration.Entities.UserRow>(new Criteria(a.UserId) == IdUser).RACS;

if (RACS == true)
{
     request.Criteria = new Criteria(MyRow.Fields.UserID.Name) == (IdUser);
}

Thanks again.
