### ISSUE TITLE
ImageUploadEditor scale not working, for me..

### ISSUE THREAD

**Issue by DouglasEFerreira** [volkanceylan/Serenity#1357]
I'm having a difficulty to scale properly  the image to the size of my screen device using the ImageUploadEditor.
Here is the deal:
I am able to upload the image nicely but when I click over the image to actually see it, when the image is too large, it's oversize practly the entire screen, mobile or desktop..
Source:
```
[DisplayName(""), Size(100)]
        [ImageUploadEditor(FilenameFormat = "RACImage/~", CopyToHistory = true)]
        public String RacImage
        {
            get { return Fields.RacImage[this]; }
            set { Fields.RacImage[this] = value; }
        }
```
And I already tried:
`[ImageUploadEditor(FilenameFormat = "RACImage/~", CopyToHistory = true,ScaleWidth =200,ScaleMode =Serenity.Web.ImageScaleMode.StretchToFit)]`

and all the types of ScaleMode..

If someone has some tip, I'll appreciate the goodnes.

PS: The issue #227 didn't help me.

**Comment by volkanceylan** [comment]
These properties are only used for upload. Not viewing.

**Comment by volkanceylan** [comment]
Use this:

            jQuery.Instance.fn.colorbox.settings.maxWidth = "80%";
            jQuery.Instance.fn.colorbox.settings.maxHeight = "80%";

**Comment by DouglasEFerreira** [comment]
It worked! Thanks volkanceylan.
