### ISSUE TITLE
URL as Links in the List view

### ISSUE THREAD

**Issue by Mumarda** [volkanceylan/Serenity#1358]
Hello,

When we create/update a record we submit the URL, like this:
![untitled0](https://cloud.githubusercontent.com/assets/19939324/19667177/be3dba10-9a25-11e6-8520-c518fcf6c200.jpg)

And when you see the record in the list, you see this:
![untitled1](https://cloud.githubusercontent.com/assets/19939324/19667178/be3f96d2-9a25-11e6-8c04-5ab21c29d262.jpg)

Is there any way to see this: (the URL as a link)
![untitled2](https://cloud.githubusercontent.com/assets/19939324/19667179/be44d836-9a25-11e6-8f29-3649cd4078ba.jpg)

Thank you very much.

**Comment by lubismargana** [comment]
you can't override getColumns

like bellow:
 protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();

            var fld = VendorPicRow.Fields;

            Q.first(columns, x => x.field == fld.Action).format =
                ctx => `<a href="${ctx.value}" class="example-link" > ${Q.htmlEncode("Link")}</button>`;

            return columns;
        }

**Comment by volkanceylan** [comment]
Use UrlDormatter
