### ISSUE TITLE
var user = Authorization.UserDefinition as UserDefinition;

### ISSUE THREAD

**Issue by thisXYH** [volkanceylan/Serenity#1359]
Why can be based on different users to different targets?
This method is better than the session.

**Comment by volkanceylan** [comment]
Well better

**Comment by thisXYH** [comment]
Sorry, I did not express clearly .  How do you achieve it? I see your code, and I know you use the IOC,
key : username      value : UserDefinition .  but not find where class  , new this UserDefinition

**Comment by thisXYH** [comment]
Sorry, I did not express clearly .  How do you achieve it? I see your code, and I know you use the IOC,
key : username      value : UserDefinition .  but not find where class  , new this UserDefinition
