### ISSUE TITLE
Error while build The application

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#136]
Error:1	The type 'System.ComponentModel.DisplayNameAttribute' exists in both 'd:\Workspace\KLMS\packages\Serenity.Script.1.9.1\lib\net2\Serenity.Script.UI.dll' and 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll'	D:\Workspace\KLMS\Serene\Serene.Script\Northwind\Note\HtmlBasicContentEditor.cs	7	14	Serene.Script
Error:2	The type or namespace name 'DisplayName' could not be found (are you missing a using directive or an assembly reference?)	D:\Workspace\KLMS\Serene\Serene.Script\Northwind\Note\HtmlBasicContentEditor.cs	7	14	Serene.Script

**Comment by volkanceylan** [comment]
Remove System reference from your Script project. Use copy/paste to create new files in script project, otherwise you'll experience this again.

**Comment by nilimajagtap** [comment]
thanks a lots..Now its working fine.
