### ISSUE TITLE
Configuring MovieCastEditor to Use MovieCastEditDialog

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1360]
When i use MovieCastEditor & MovieCastEditDialog to insert a record in a dialog it seems the Parent Entity Id is missing (Contacts List in Partner Entity).
How do i pass parameters to MovieCastEditor?

![capture](https://cloud.githubusercontent.com/assets/22570602/19675992/5329c7bc-9a9a-11e6-9d1a-e68c64d1411b.PNG)

**Comment by VictorTomaili** [comment]
are you solve it?
