### ISSUE TITLE
Use entitygrid as GridEditorBase, in memory tranfer

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#1361]
Hi,

I really try but cannot figure out how to use entitygrid as grideditor.

I can retreive selected keys from Scenario available (simple table), but I cannot figure out how to transfer it to in memory grid of scenario list (join table) as I need to be able to save the scenariolistname before the list.

Also grid will "lose the data" if I go on page 2.

I coud not find a satisfying example, and I would really appreciate some tips.

![capture](https://cloud.githubusercontent.com/assets/18526390/19681578/2f415eae-9aaa-11e6-9ec8-0467679f8f1e.JPG)

Thank you

**Comment by Boumboumjack** [comment]
Ok, 

I found my way, but I am still strugling
Simply by overriding getSaventity is magic

`
public getSaveEntity() {
            var entity = super.getSaveEntity();
            entity.ScenarioList = this.scenariosTabMapGrid.value;
            return entity;
        }`

And value as in grideditorbase.


Though, I am wondering, how do you do to upload the id of the maping table row and hide it? (to retreive it on update as with grideditorbase)

Thank you,

**Comment by volkanceylan** [comment]
Sorry but i can't understand what you are trying to do.

**Comment by Boumboumjack** [comment]
Hi,

Well basically it is like your exemple moviecast, but with tabs. The properties is the dialog, the left tab is the joint table (list<row>of the dialog or editorgridbase in your exemple) and the right tab is the source table.

I want to keep the grid format to sort and order as it is "too" (but still amazing) restrictive.

As I want to keep the joint table id on dialog retreive, I should be able to store somewhere the jointtable ids, but I cannot figure out how you do it in your exemple.

Thank you,

**Comment by Boumboumjack** [comment]
Ok,

So basically, your system does manage everything, I was trying to hard.

Basically, it is enough to use getsaveentity, afterload, push and create virtual "__id", then follow the procedure in moviecast.
