### ISSUE TITLE
html in alert dialog

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1362]
Has anyone implemented html in an alert dialog? i.e     q.message(html)

**Comment by marcobisio** [comment]
Hi @mcb2323, I use this plugin: http://bootboxjs.com/documentation.html#bb-custom-dialog
There are both the nuget package for the library and for the typescript definition...

Bye

**Comment by volkanceylan** [comment]
Q.alert has a htmlEncode parameter
