### ISSUE TITLE
GridEditorDialog open in full screen

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1365]
I can open all of my EntityDialogs in full screen but for some reason I can't get my GridEditorDialog to open in full screen.   TIA!

    /// <reference path="../../Common/Helpers/GridEditorDialog.ts" />
    namespace EventManager.Repair {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    @Serenity.Decorators.maximizable()

    export class RepairEditorDialog extends Common.GridEditorDialog<RepairRow> {
        protected getFormKey() { return RepairForm.formKey; }
        protected getIdProperty() { return RepairRow.idProperty; }
        protected getLocalTextPrefix() { return RepairRow.localTextPrefix; }
        protected getNameProperty() { return RepairRow.nameProperty; }
        protected getService() { return RepairService.baseUrl; }

        protected form = new RepairForm(this.idPrefix);

        dialogOpen() {
            super.dialogOpen();
            this.element.closest(".ui-dialog").find(".ui-icon-maximize-window").click();
        }

**Comment by edson** [comment]
Hi, there. That's just because it is not called... Take a look at https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Editors/ChangingLookupText/Index.cshtml

In this case, you should use:

```
loadNewAndOpenDialog() {
            super.loadNewAndOpenDialog();
            this.element.closest(".ui-dialog").find(".ui-icon-maximize-window").click();
        }
```

Regards

**Comment by volkanceylan** [comment]
Where did you get idea that grid editor dialog has id property, service etc. Are you sure that this is the actual dialog? If this is, you have more important problems than maximizing it. Read the guide.

**Comment by mayatstafford** [comment]
Thank you for responding.  Out of desperation I had copied code from a dialog, that's how I wound up with the id property and service.  
So I've tried using both dialogOpen and loadNewAndOpenDialog and neither is opening up a full screen.   Any ideas?

**Comment by edson** [comment]
Try putting it in constructor...

But at least you should know how it is being called... 

Regards

**Comment by mayatstafford** [comment]
Thank you.   I appreciate all the help.  The reason I was copying it from one of my other dialogs is there are buttons that are only visible with certain permissions which is standard throughout the site. But thank you for showing me how it works.  :)    This is what worked:

    namespace EventManager.Repair {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    @Serenity.Decorators.maximizable()

    export class RepairEditorDialog extends Common.GridEditorDialog<RepairRow> {
        protected getFormKey() { return RepairForm.formKey; }
        protected getNameProperty() { return RepairRow.nameProperty; }
        protected getLocalTextPrefix() { return RepairRow.localTextPrefix; }

        protected form: RepairForm;

        constructor() {
            super();
            this.form = new RepairForm(this.idPrefix);
            this.element.closest(".ui-dialog").find(".ui-icon-maximize-window").click();
        }

**Comment by Lotfyyy3** [comment]
if i have module as Master in relation and in another relation is Detail 
how should i modify it's grid and dialog
