### ISSUE TITLE
Set value of RowSelection checkbox.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1366]
![image](https://cloud.githubusercontent.com/assets/16621563/19713902/aca8b57e-9b6b-11e6-9247-44379dc1d9b9.png)

Anyone please help me to check uncheck the value of rowselection checkbox according to some logic.

**Comment by volkanceylan** [comment]
for all yourID you want to set
    (yourMixin as any).$include[yourID] = true

this.grid.invalidateAllRows();
this.grid.render();

**Comment by dfaruque** [comment]
Thanks dear,
Please give a hint to disable some check boxes?
