### ISSUE TITLE
change query for tab data based on field value from parent form

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1367]
I have in my OrderForm a tab for OrderNotaryGrid which loads my Notary based on the ID (VendorNum) passed from the OrderDialog

```
    protected afterLoadEntity() {
        super.afterLoadEntity();
        this.notaryGrid.vendorNum = this.entity.VendorNum;
    }
```

I would like to use a different query to retrieve a list of Notaries if the Order does not have a VendorNum assigned to it. Right now I load the grid from the OnReturn method in MyRetrieveHandler of OrderRepository. I added an if / else and console shows the data but it does not load into the grid. Is a good way of doing this or should I toggle a different grid altogether in the tab if my VendorNum is null?

```
     protected override void OnReturn()
        {                
            base.OnReturn();
            {
                base.OnReturn();
                var mc = Entities.NotaryRow.Fields;
                if (mc.VendorNum.IsNotNull())
                {
                    Row.NotaryList = Connection.List<Entities.NotaryRow>(q => q
                    .SelectTableFields()
                    .Select(mc.Name)
                    .Where(mc.VendorNum == Row.VendorNum.Value));
                }
                else
                {
                    Row.NotaryList = Connection.List<Entities.NotaryRow>(q => q
                    .SelectTableFields()
                   ----- new query to select list of notaries instead of one ------
                }
```

MyGrid

```
      protected getGridCanLoad() {            
        return this.vendorNum != null;            
    } 

    private _vendorNum: number;

    get vendorNum() {
        return this._vendorNum;
    }

    set vendorNum(value: number) {
        if (this._vendorNum != value) {
            this._vendorNum = value;
            this.setEquality(NotaryRow.Fields.VendorNum, value);
            this.refresh();
        }        

    }
```

**Comment by jdready5** [comment]
It seems the best way may be to use 2 different grids in the same tab and toggle between the two depending on condition. I can toggle the grid on and off right now with condition using this.element.toggle(true/false), now just working to see if its possible to display the alternate grid in the same tab.

**Comment by volkanceylan** [comment]
Grid should be loading data from List, not Retrieve but maybe i didn't understand what you did.

**Comment by jdready5** [comment]
Your right, I probably got confused. I was looking at the example for moviecast to populate my tabs with data. It does load but I should use List. I will change that over and check the results
