### ISSUE TITLE
Event addButtonClick

### ISSUE THREAD

**Issue by MsDanglar** [volkanceylan/Serenity#1369]
Hi.
I use dialog like  in your example (Using MovieCastEditor in Movie Form),
but if  i insert addButtonClick in internal editor in a dialog and click the new button is not call the addButtonClick event.

Thank you

**Comment by in32bit** [comment]
That's true, in the GridEditorBase this event won't fired.

        protected addButtonClick() {
            Q.alert("add event fired!");
        }

**Comment by in32bit** [comment]
i used 

        protected getNewEntity() {
            return <row>{
                Operation: 0
            };
        }

**Comment by volkanceylan** [comment]
GridEditorBase creates own set of buttons so there is no addButtonClick.

**Comment by MsDanglar** [comment]
Thank You, it work perfectly.
