### ISSUE TITLE
Uncaught TypeError: Cannot read property 'IceriklerGrid' of undefined

### ISSUE THREAD

**Issue by wolverine81** [volkanceylan/Serenity#137]
Merhaba,

Serenity Application Tempate 1.9.3 kurdum.
Test için kendi oluşturduğum Serene1_IcerikYonetimi_v1 veritabanına bağladım.
Bu veritabanından Icerikler adindaki tabloyu Sergen ile import ettim
Fakat Uncaught TypeError: Cannot read property 'IceriklerGrid' of undefined gibi hata alıyorum.
Kodları incelediğimde örnek Northwind için Web/Scripts/site/Serene1.Script.js içinde her ekran için Grid ve Dialog tanımlamaları var. 

Bu tanımlara sergenin otomatik yapması gerekmiyor mu? 
Ve bu konuda ne yapmak gerekiyor?

![2016-01-21 17_33_11-sqlquery33 sql - ntdbt 333_nt_as_fm1_2009 kaynakholding_murat cicekci 1259 _](https://cloud.githubusercontent.com/assets/3111668/12484936/4300bc7a-c065-11e5-9a87-179b45867a6f.png)

![2016-01-21 17_35_11-serenity code generator](https://cloud.githubusercontent.com/assets/3111668/12485005/8640b3a0-c065-11e5-9925-84246707783f.png)

![2016-01-21 17_23_39-developer tools - http___localhost_59978_cms_icerikler](https://cloud.githubusercontent.com/assets/3111668/12484837/c471e7b2-c064-11e5-8cf0-e17dbe5e2c9b.png)

**Comment by volkanceylan** [comment]
İki projeyi de rebuild ettiniz mi?

**Comment by wolverine81** [comment]
:( edince düzeldi. Teşekkürler.

**Comment by volkanceylan** [comment]
Build dependency eklerseniz web projesine script projesinden, rebuild etmeniz gerekmez. Kılavuzda bilgi vardı bununla ilgili.

CodeGenerator javascript kodu üretemez, javascript kodunu üretecek C# kodlarını hazırlıyor. Bunların derlenip script e dönüştürülmesi lazım.
