### ISSUE TITLE
Expression don't return value

### ISSUE THREAD

**Issue by MsDanglar** [volkanceylan/Serenity#1370]
Hi,
Im have a next code

`
[DisplayName("Range"), Expression("CONVERT(nvarchar(20), t0.RangeFrom) + ' ' + CONVERT(nvarchar(20), t0.RangeTo)"), QuickSearch,Width(100)]
        [MinSelectLevel(SelectLevel.List)]
        public String RangeText
        {
            get { return Fields.RangeText[this]; }
            set { Fields.RangeText[this] = value; }
        }

        [DisplayName("Range From"), NotNull]
        public Int32? RangeFrom
        {
            get { return Fields.RangeFrom[this]; }
            set { Fields.RangeFrom[this] = value; }
        }

        [DisplayName("Range To"), NotNull]
        public Int32? RangeTo
        {
            get { return Fields.RangeTo[this]; }
            set { Fields.RangeTo[this] = value; }
        }
`
but RangeText not return a values to display.

Thank you

**Comment by volkanceylan** [comment]
As long as your fields are not null, it should.

**Comment by MsDanglar** [comment]
Hi Volkan,

When we watch at the profiler we see that the SQL query generated by serenity we see that everything is correct:

`exec sp_executesql N'SELECT 
T0.[Id] AS [Id],
T0.[Name] AS [Name],
T0.[Code] AS [Code],
T0.[Year] AS [Year],
T0.[RangeFrom] AS [RangeFrom],
T0.[RangeTo] AS [RangeTo],
T0.[Active] AS [Active],
CONVERT(nvarchar(20), t0.RangeFrom) + '' '' + CONVERT(nvarchar(20), t0.RangeTo) AS [RangeText] 
FROM [dbo].[NumberRanges] T0 
WHERE ((T0.[NumberRangeHeadId] IN (@p1,@p2))) 
ORDER BY T0.[Name], T0.[Id]',N'@p1 int,@p2 int',@p1=13,@p2=14`  

At the row we expect the next property will we nicely populated... but it doesn't:

`[DisplayName("Range"), Expression("CONVERT(nvarchar(20), t0.RangeFrom) + ' ' + CONVERT(nvarchar(20), t0.RangeTo)"), QuickSearch,Width(100)]
[MinSelectLevel(SelectLevel.List)]
public String RangeText
{
get { return Fields.RangeText[this]; }
set { Fields.RangeText[this] = value; }
}`

**Comment by volkanceylan** [comment]
I don't see anything unusual here. It's not so different than full name so it should be some other error on your side.
