### ISSUE TITLE
Multiple Enum Select

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1371]
Hi Volkan,

Is it possible to select multiple enum value into a table or commaseparator string field?

Thank!

**Comment by sayuga** [comment]
Are you trying to do the same as the Basic Samples> Editors> Lookup Filtering By Multiple Values  sample but with enums? You'll probably need to create a similar custom editor.

**Comment by in32bit** [comment]
Thank you for your help.

I mean when creating a Form Field (based on enum -> select2 component ) in serenity Engine like this:

        [DisplayName("Supplier Type")]
        public SupplierTypes? SupplierType {

            get { return (SupplierTypes?)Fields.SupplierType[this]; }
            set { Fields.SupplierType[this] = (Int32?)value; }
        }

it's is possible to add the multiple attribute to save more than one value in the enum (commaseparator format)?

**Comment by VictorTomaili** [comment]
Enums will be flags for store multiple flag. but i dont ensure about lookup editor with multiple. Maybe you need write your own editor. 

```csharp
[Flags]
enum SupplierType {
    type1 = 1,
    type2 = 2,
    type4 = 4,
    type8 = 8
}
```

**Comment by volkanceylan** [comment]
Enum editor doesn't support multiple selection yet, might be in a later version. For now, you may create a select with hardcoded values, like in relevant sample.

**Comment by MsDanglar** [comment]
Thank you

**Comment by isukces** [comment]
Maybe this [commit](https://github.com/isukces/Serenity/commit/d9e6c9f7ee134968b30e47da6878b998aff0f7c6) on my fork will help. Small change solves problem. Sample usage
```
        [EnumFiltering(EnumKey = BasketInteractionConsts.SerenityEnumKey)]
        [QuickFilterOptionAttribute("multiple", true)]
        public BasketInteraction? BasketStatus
        {
            get { return (BasketInteraction?)Fields.BasketStatus[this]; }
            set { Fields.BasketStatus[this] = (int?)value; }
        }
```

**Comment by in32bit** [comment]
We upgraded to Serenity 3.9 the all out multiple enum editors stop presenting the selected values in the UI dialog. In the retrieve respond we see the properties value.

Anyone know where to check where the values pass to mutli select2 component?
Thank you

some of our editors:

`

namespace SPU.Administration {
    @Serenity.Decorators.registerEditor()
    export class CompanyRolesLookup extends Serenity.EnumEditor {

        constructor(container: JQuery) {
            super(container, { enumKey: "Administration.CompanyRoles" });
        }

        public getSelect2Options() {
            var selec2Options = super.getSelect2Options();
            selec2Options.multiple = this.options.multiple || true;
            return selec2Options;
        }

        public get_delimited() {
            return true;
        }

    }
}`

`

namespace SPU.Configuration.ServiceData {


    @Serenity.Decorators.registerEditor()
    export class ServiceTradeTypesLookup extends Serenity.Select2Editor<any, any> {

        constructor(container: JQuery) {
            super(container, null);

            this.addOption(BusinessProcess.ServiceTrade.Export.toString(), Q.text("Site.SalesProporsal.BasicInformation.Export"));
            this.addOption(BusinessProcess.ServiceTrade.Import.toString(), Q.text("Site.SalesProporsal.BasicInformation.Import"));
            this.addOption(BusinessProcess.ServiceTrade.Domestic.toString(), Q.text("Site.SalesProporsal.BasicInformation.Domestic"));
            this.addOption(BusinessProcess.ServiceTrade.Cross.toString(), Q.text("Site.SalesProporsal.BasicInformation.Cross"));
        }

        public getSelect2Options() {
            alert(9);
            debugger
            var selec2Options = super.getSelect2Options();
            selec2Options.multiple = true;
            return selec2Options;
        }

        public get_delimited() {
            return true;
        }

    }
}
`
