### ISSUE TITLE
Custom form layout

### ISSUE THREAD

**Issue by LaurentzT** [volkanceylan/Serenity#1372]
Hello,

I just started today using Serenity and it is very nice but how can we layout the generated form? For example if I want to use a tabcontrol to split my properties of a Order?

I read your dev guide but I could not find how to change the generated html to the way I want to see it...

Thanks for the help!

**Comment by sayuga** [comment]
If you are looking at how to implement tabbed forms, look at the Northwind Customers  table. It's got tabs implemented. You should be able to use that as a starting point.

**Comment by LaurentzT** [comment]
ok thanks!
