### ISSUE TITLE
LookupEditor - Add Only?

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1373]
Is there a way to make the LookupEditor add only?
Below allows Editing and Adding

    [LookupEditor(typeof(Product.Entities.ProductRow), InplaceAdd = true)]

**Comment by sayuga** [comment]
I'm not sure i understand what you mean but it sounds to me you want to simply remove the InplaceAdd. That will remove the option to edit the field from the LookupEditor being referenced. You'll be limited to only the options already in place at the other end of the LookupEditor.

**Comment by mayatstafford** [comment]
I don't want to edit existing items

**Comment by volkanceylan** [comment]
Hide edit button with css
