### ISSUE TITLE
Add Mask in Dialog

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1374]
I'm trying to add a mask to a phone field on a form.

This is what I have in the dialog:

            protected updateInterface() {
            super.updateInterface();

            this.form.Phone.element.add('data-inputmask=\'"mask": "(999) 999-9999"\' data-mask');

I'm getting this error: "0x800a139e - JavaScript runtime error: Syntax error, unrecognized expression: data-inputmask='"mask": "(999) 999-9999"' data-mask"

Can some one tell me the proper way to apply a mask from a dialog?  Thank you.

**Comment by volkanceylan** [comment]
Use MaskEditor

**Comment by mayatstafford** [comment]
Thank you.    Where would I implement that?

**Comment by mayatstafford** [comment]
How can I access or set the mask from the dialog?    I have a country drop down and when it changes I'd like to apply a different phone mask.

**Comment by volkanceylan** [comment]
Answered in other issue.
