### ISSUE TITLE
Removing Northwind

### ISSUE THREAD

**Issue by aetaylor** [volkanceylan/Serenity#1375]
Would it be possible to publish a "Serenity Lite" version for Visual Studio, without the Northwind and Sample stuff so that we don't have to keep removing it every time we create a site?

**Comment by volkanceylan** [comment]
Not probably, maybe a wizard or script to remove it but i don't think average user creates multiple sites per day, so not a priority.

**Comment by VictorTomaili** [comment]
Get serene sample from git 
open Serene.sln
clear project from northwind
save and close project
run buildtemplate.cmd
use it.
