### ISSUE TITLE
Lookup Change causes mask to change

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1377]
I have a country lookup and a phone field.   I'd like to change the phone mask when the country changes.   I'm hoping to achieve this in the dialog, just not sure how to access the action and the mask from the dialog.   Also, the country lookup is cascaded and affects the state lookup.   Thank you for any help.
This is what I have in the form:

      [LookupEditor(typeof(Administration.Entities.CountryRow), FilterField = "Display", FilterValue = 1), DefaultValue(229)]
        public Int32 CountryId { get; set; }

        [DisplayName("State/Province")]
        [LookupEditor(typeof(Administration.Entities.ProvinceRow), CascadeFrom = "CountryId", CascadeField = "CountryId")]
        public Int32 ProvinceId { get; set; }

            [DisplayName("Phone"),  MaskedEditor(Mask = "(999) 999-9999")]
        public String Phone { get; set; }

**Comment by Estrusco** [comment]
For add event to loockup you can write this cose in yourDialog.ts constructor

```cs
        // Add change event to lookup field
        this.form.LookUpField.ChangeSelect2(e =>
        {
            [....] // code for change maskeditor
        }
```

I don't know how change the mask editor

**Comment by volkanceylan** [comment]
This is the mask input used:

http://digitalbush.com/projects/masked-input-plugin/

You have element in form.SomeField.element, so it's straightforward.

**Comment by mayatstafford** [comment]
Hi,  I'm sorry I still can't figure out how to change the mask from the dialog.  
What do I do after this to access the mask?  

this.form.Email.element

Thank you for being so patient!
