### ISSUE TITLE
When capturing doing a getLookup() I only receive the idProperty and the nameProperty of the row

### ISSUE THREAD

**Issue by capetonian** [volkanceylan/Serenity#1378]
I've implemented the ChangingLookupText scenario in the basic samples with no success - as the item object passed via JSON would only have the idProperty and nameProperty available:

`export class CustomerProductClaimsLookupTextEditor extends Serenity.LookupEditorBase<Serenity.LookupEditorOptions, Management.CustomerProductsRow> {
        constructor(container: JQuery, options: Serenity.LookupEditorOptions) {
            super(container, options);
        }

        protected getLookupKey() {
            return Management.CustomerProductsRow.lookupKey;
        }

        protected getItemText(item: Management.CustomerProductsRow, lookup: Q.Lookup<Management.CustomerProductsRow>) {
            console.log(item);

            return super.getItemText(item, lookup) + ' >> ' + item.PolicyNumber + ' - ' + item.ContactName + ' ' + item.ContactSurname + ' - EMAIL: ' + item.ContactEmail + ' - CELL: ' + item.ContactMobile + ' - START: ' + item.ActivationDate + ' - END: ' + item.EndDate;  //  super.getItemText(item, lookup);
        }
    }`

I just ended up with a whole lot of undefined values under item.*

Eventually, I just implemented an expression column and set it to the name property. 

`        [DisplayName("PolicyDropDownString"), Size(50), NotNull, Expression("(t0.PolicyNumber + ' - ' + t0.ContactName + ' ' + t0.ContactSurname + ' - EMAIL: ' + t0.ContactEmail + ' - CELL: ' + t0.ContactMobile + ' - START: ' + cast(t0.ActivationDate as varchar(max)) + ' - END: ' + cast(t0.EndDate as varchar(max)))")]
        public String PolicyDropDownString
        {
            get { return Fields.PolicyDropDownString[this]; }
            set { Fields.PolicyDropDownString[this] = value; }
        }`

But now when implementing the select2 change, I get nulls anyway due to the getLookup or itemsById, which all use SerenityCoreLib anyway, do not return the full object. 

`this.form.CustomerProductId.changeSelect2(e => {
                var customerProductId = Q.toId(this.form.CustomerProductId.value);
                if (customerProductId != null) {
                    this.form.CustomerId.value = Management.CustomerProductsRow.getLookup().itemById[customerProductId].CustomerId;
                    this.form.ClaimAmountPaid.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimAmountPaid;
                    this.form.ClaimCurrencyId.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimCurrencyId;
                    this.form.ClaimDecisionDateTime.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimDecisionDateTime;
                    this.form.ClaimIncidentDateTime.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimIncidentDateTime;
                    this.form.ClaimNotificationReceived.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimNotificationReceived;
                    this.form.ClaimPaid.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimPaid;
                    this.form.ClaimStatusId.value = Management.CustomerProductClaimsRow.getLookup().itemById[customerProductId].ClaimStatusId;
                }
            });`

I feel like I've ended up with a circular nightmare. 

How do I ensure that my whole object is available in the getLookup?
All my typings are as standard from the T4, and most of my objects are as run out by sergen;

**Comment by edson** [comment]
Hi, there. If you want to include a column to lookup script, add LookupInclude attribute to the Field of Lookuprow...
Regards

**Comment by capetonian** [comment]
Thanks Edson - I appreciate that. 
I found it in the guide now - its only spoken of in a cascade, so it wasn't immediately apparent in my particular use case - but thanks never the less.

**Comment by edson** [comment]
Your're welcome, @capetonian . I was in a hurry, just popped in to read some issues, I remember to have seen it in the guide... but yeah it is not clear right away.. Might put some info in wiki to easy it.. :)

Best Regards.
