### ISSUE TITLE
Error while build The application

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#138]
Error:1	'MVC.Views.Membership.Account.SignUp' does not contain a definition for 'AccountSignUp'	D:\Workspace\KLMS\Serene\Serene.Web\Modules\Membership\Account\SignUp\AccountPage.SignUp.cs	23	61	Serene.Web

**Comment by volkanceylan** [comment]
So you deleted AccountSignup.cshtml, then delete relevant code

**Comment by nilimajagtap** [comment]
I need signup functionality, so would u please guide me.

**Comment by volkanceylan** [comment]
Just use latest template. If you copy pasted something into project, make sure take all relevant files. Run MVC.tt.

**Comment by volkanceylan** [comment]
Please reopen if not resolved.
