### ISSUE TITLE
Pagination not working when use MySQL database

### ISSUE THREAD

**Issue by freddiezhou** [volkanceylan/Serenity#1380]
Hi,

Thank you to provide this fantastic template.

When I use it to build application with MySQL database, and found one issue on Pagination, that it not working when I turn to page 2+.

**Example:**
When I turn to 'Page 4' in my application, and traced the loging file, and sql as below:
_SELECT T0.`sId` AS `SId` FROM `odm_packing` T0 ORDER BY T0.`WORKORDER`, T0.`sId` **LIMIT 300 OFFSET 100**_

And it's error, and correct one should be **LIMIT 100 OFFSET 300**. 

The issue looks like swiched parameter transfer between SKIP & TAKE, or something else. So could you please advise how to fix this? 

Thank you very much.

**Comment by volkanceylan** [comment]
Fixed in 2.5.4

**Comment by freddiezhou** [comment]
Thanks very much for your quick reply. Looking forward for releasing. : )

**Comment by volkanceylan** [comment]
It is already released

**Comment by freddiezhou** [comment]
Had updated and fixed the issue. Thank you very much for quick resolution. : )
