### ISSUE TITLE
Validation client side an extra dialog in OtherFormInTab example

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1382]
How I can validate client side an extra dialog in OtherFormInTab example? 
If I confirm second form without insert CompanyName I get database excpetion.
I would like to make to perform a .validateForm() for client validation, but I don't know how to accomplish this work.

Thank you

**Comment by volkanceylan** [comment]
Added validation to that sample in 2.5.4.1

**Comment by Estrusco** [comment]
Thank you very much @volkanceylan  , I love you! :-)
