### ISSUE TITLE
SQLQuery problem

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1384]
Hi,

Am having some real trouble here.

Trying to use Serene's SQLQuery as below to add an item to dashboard, basically to sum up a column and display result in dashboard.

```
                        SqlQuery query = new SqlQuery();
                        query.Select("SUM(TotalItemsRequired)").From(PrinterTonerStockRow.Fields);
                        var t = abudb.Query(query);
```
in the debugger when I look at the returned object t contains a collection with 1 item, within that is dapper object with the value I'm looking for but it's not easy to get hold of in a reasonable way.

What am I doing wrong here and should I be doing it differently?

**Comment by volkanceylan** [comment]
Try with Query < double? >

**Comment by abelal83** [comment]
thank you, that works with a small change as below

```
                        SqlQuery query = new SqlQuery();
                        query.Select("SUM(" + PrinterTonerStockRow.Fields.TotalItemsRequired.Name + ")").From(PrinterTonerStockRow.Fields);
                        var queryResult = abudb.Query<int?>(query);

                        // need a foreach as the result is enumerable only
                        foreach (int item in queryResult)
                        {
                            Console.WriteLine(item);
                            model.TotalTonersRequired = item;
                        }
```

as you can see I need to do a foreach as the result does not implement an indexer, any way to simplify this?

**Comment by volkanceylan** [comment]
Hmm, that's basic linq man, queryResult.First()

**Comment by abelal83** [comment]
I'm a sql man I'm afraid, still picking up linq. Thank you as always for the help.

**Comment by abelal83** [comment]
strangely qeueryResult does not contain First(). I know it should be possible on an ienumerable type. In either case I'm happy as I have what I need.

**Comment by abelal83** [comment]
Excellent, works a charm!

**Comment by biggikalli** [comment]
Hi @abelal83,

Would you be so kind to share your final working code snippet as I think it would be very useful for many, me included :)

Thank you.

Regards,
Biggi

**Comment by abelal83** [comment]
hi @biggikalli , 

of course, more than happy to share!

so I added
`using System.Linq;`

then in the i did the following

```
                    SqlQuery query = new SqlQuery();
                        query.Select("SUM(" + PrinterTonerStockRow.Fields.TotalItemsRequired.Name + ")")
                            .From(PrinterTonerStockRow.Fields).Where(PrinterTonerStockRow.Fields.PrinterName.StartsWith("LDNP"));
                        model.TotalTonersRequired = desksidedb.Query<int?>(query).FirstOrDefault();
                    }
```
i store the result in model page and finally I use it in the page itself.

```
    <div class="small-box @Model.TotalTonersRequiredDashboardColor">
        <div class="inner">
            <h3>@Model.TotalTonersRequired</h3>
            <p>London Printer toners required</p>
        </div>
```

Hope this helps!

**Comment by biggikalli** [comment]
Great @abelal83 and thanks for the reply.

It led me to my final working code of:                        

                        SqlQuery query = new SqlQuery();
                        query.Select("SUM(" + NammiPantanirRow.Fields.Quantity + ")")
                            .From(NammiPantanirRow.Fields); 
                        model.NammiSum = connection.Query<decimal>(query).FirstOrDefault();`

The only difference is that I am dealing with a decimal type, originating from a SQL View.

Thanks.
