### ISSUE TITLE
Setting default value for quick filter causes double grid population

### ISSUE THREAD

**Issue by mkoval-ua** [volkanceylan/Serenity#1385]
Hi Volkan,

Your framework is great - it's really time saver, works quite smoothly and is looking great!

Could you let us know if this is a bug or just my incorrect usage of the feature.
I tried to set default value using init for quick filter, directly setting value after locating quick filter but both cases result into duplicated population of the grid. All this was done according to your guides and samples in grid.ts - tried both places getQuickFilters and createQuickFilters.

If I'm setting value directly then it immediately populates the grid as change event is triggered in such case and then one more population on initialPopulate().
On other side If I declare init handler for the quick filter then the handler is called somewhere after initialPopulate() and results in second populate as well.

This was tracked by SQL profiler and it showed this issue constantly. Also I debugged java script but haven't found the appropriate way. The only thing that might work is populateLock/populateUnlock but I don't want to call them separately in different events as it might result in broken behavior when populateUnlock is not executed due to some reasons.

As a side note - I've implemented field level permissions behavior and can contribute it to the project - just let me know if this is needed and where to continue with this separate topic.

**Comment by volkanceylan** [comment]
It is due to use of change event, plus async nature of initialization. Tried to fix it 2.5.6 by changing initial populate to use timeout, hope won't create a side effect.

**Comment by mkoval-ua** [comment]
Thank you for prompt reply and quick fix!
Will try tomorrow if this helps.

By the way, alternatively you could lock grid population at the beginning of constructor and then unlock in the end of it (in try/finally block)? Or maybe this will also be problematical due to async nature of initialization?

**Comment by mkoval-ua** [comment]
It seems the issue has been fixed in 2.5.6! But I rolled back to 2.4.10 as there is some another issue added since this version. Namely, grid is not expanding now to full area size. It just expanded in horizontal direction properly - vertical (height) is not expanded.

**Comment by volkanceylan** [comment]
Check the upgrade guide

**Comment by mkoval-ua** [comment]
Thank you a lot!!!
