### ISSUE TITLE
Best way to load View to Serenity Dialog?

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1386]
Hi,

I have a complex cshtml page i want to load to dialog when user click edit in the grid.

I have some mvc pages in the project, but how can i manage ordinary view in diallog and still use the events of the dialog (get id, save, refresh list etc..)

Thank you.

**Comment by volkanceylan** [comment]
new SomeDialog().loadByIdAndOpenDialog, loadEntityAndOpenDialog etc.

**Comment by in32bit** [comment]
I end up using serenity generated dialog and than injecting html with jsRender:


      protected afterLoadEntity() {
            super.afterLoadEntity();

            Q.serviceCall({
                url: Q.resolveUrl('~/Activities/Get?id=' + this.entity.Id),
                onSuccess: response => {

                    var markup = jQuery("#ActivityTemplate").html();
                    var html = Q.jsRender(markup, response);
                    jQuery(".s-Form").html(html);
                }
            });
        }

Thanks

**Comment by in32bit** [comment]
using jsview


        protected afterLoadEntity() {
            super.afterLoadEntity();

            Q.serviceCall({
                url: Q.resolveUrl('~/Activities/Get?id=' + this.entity.Id),
                onSuccess: response => {
                    Q.jsViewLink("#ActivityTemplate", ".s-Form", response);
                }
            });
        }
