### ISSUE TITLE
Spinner fails to appear until 3 seconds elapsed tim

### ISSUE THREAD

**Issue by DoyleJOfTexas** [volkanceylan/Serenity#1387]
Spinner does not appear fast enough on click event of a row in grid - 3 full seconds elapsed time. 

This occurs before any code of mine runs in Endpoint class.

I there anything I can do to speed up the spinner appearance?

Love this framework.

Doyle

**Comment by volkanceylan** [comment]
It works as designed. That animation only shows after 3 seconds. Pace options are setup in LayoutHead.cshtml, see its docs if you want to change.

**Comment by DoyleJOfTexas** [comment]
Thank you.
