### ISSUE TITLE
Access save button event from another tab view and programmatically change focus on tabs

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1388]
Is there a way to access the save button onclick in the main PropertyGrid from another tab? ie: I open my orders form which has a customer tab. In my customer tab i select a customer from the grid using rowSelection then in the onClick of my button I get the value of the customerID with  var selectedIDs = this.rowSelection.getSelectedKeys()[0]; That value is passed back to my orders form using this.parentForm.CustomerID.value = +selectedIDs; This works as it should but I would like to programmatically change the focus back to the parent tab and update the record within the customer grid onclick.

OrderDialog.ts (simplified)

```
     public form = new NOrderForm(this.idPrefix);
     private customerGrid: NOrderCustomerGrid;

     this.customerGrid = new NOrderCustomerGrid(this.byId("CustomerGrid"));
     this.tabs.on('tabsactivate', (e, i) => {
            this.arrange();
        }); 

    protected afterLoadEntity() {
        super.afterLoadEntity();
    this.customerGrid.parentForm = this.form;
```

CustomerGrid.ts (simplified)

```
    public rowSelection: Serenity.GridRowSelectionMixin;
    public parentForm: NOrderForm;

    protected getButtons() {
        let buttons = [];

        buttons.push({
            title: 'Assign Customer',
            hint: 'Assign Customer',
            cssClass: 'choose-customer-button',
            onClick: () => {

                var selectedIDs = this.rowSelection.getSelectedKeys()[0];
                if (selectedIDs == null)
                    Q.notifyWarning("Please select a Customer");
                else
                    Q.notifySuccess("You have selected " + selectedIDs);                   

                this.parentForm.customerId.value = +selectedIDs;
            }
        });

        return buttons;
    }
```

I have tried "document.getElementById" and "this.element.tabs('load',0)" and "this.element.find", for changing focus back to the main orders tab but no success. I have gone through the source to try to find the best way to get access to the parents save button onclick event but also have not found anything yet. If anyone has done something similar could you share how? I am relatively new to typescript and jquery but I am having fun learning what I can and can't do with it.

**Comment by Estrusco** [comment]
I have send a pull request with this example in serene and another with selectTab in serenity. You can see
https://github.com/volkanceylan/Serene/pull/30

https://github.com/volkanceylan/Serenity/pull/1389
And this fix
https://github.com/volkanceylan/Serenity/pull/1390

**Comment by jdready5** [comment]
Thanks a ton @Estrusco , At first glance this looks like something to get me moving along. As I am only saving one entity I think I can work with this or modify it a bit to fit for what I need to do. I will post final code when working.
