### ISSUE TITLE
Creating Tabs on Dialog

### ISSUE THREAD

**Issue by denonc** [volkanceylan/Serenity#139]
Hi, I'm trying to create tabs on a dialog which resemblance CustomerOrder tabs. Can I confirm that the files that requires modification are: CustomerDialog, CustomerOrderDialog & CustomerOrderGrid? Is there other files require more input? (I tried follow the CustomerOrder but was not able to open the dialog, even after T4 build and rebuild solution) Thanks to highlight what possibly I could have missed out...

Based on the sample, it shows tabs with Notes and a grid-view capability. Will it be possible for tabs to display other module forms/dialogs instead of grid? Thanks for any suggestions to accomplish these!

**Comment by volkanceylan** [comment]
You also need a dialog template, e.g. CustomerDialog.Template.html

**Comment by denonc** [comment]
A copy of the html is pasted on the module, just edited one id="_ordergrid" on the html. But still wasn't able to show after rebuild.

**Comment by volkanceylan** [comment]
Still was unable to show is a users report on something. You should report like a developer. Console, error details etc.
