### ISSUE TITLE
ExecuteAndGetID(...) method only supports SqlServer dialect

### ISSUE THREAD

**Issue by chatcoda** [volkanceylan/Serenity#1391]
First of all, I am impressed with this platform, terrific work !
I'm working with PostgreSQL, and had no problem configuring the connection (very well explained in serenity-guide), and I'm able to manage users from the console.
However, I'm not able to set up Active Directory authentication : in AuthenticationService.ValidateFirstTimeUser(...), the user is correctly authenticated, but the the application fails to insert the record into the Users table through .ExecuteAndGetID(connection), because identityColumn == null.
It works fine with MSSQL server.
Cheers.

**Comment by volkanceylan** [comment]
I don't think ExecuteAndGetID supports only SQL server as it is also used in other screens. Try using Apply Changes button while adding a product for example, if it fails ExecuteAndGetID must be failing too. I don't have PostgreSQL at the moment so you should debug.

**Comment by chatcoda** [comment]
Thanks, I figured it out debugging.

Adding a product is working because IdentityColumn is set in \Serenity.Data.Entity\Extensions\EntityConnectionExtensions.cs through
`insert.IdentityColumn(((Field)(((IIdRow)row).IdField)).Name);`

On the other hand, with AD authentication, Users table insert threw an exception because IdentityColumn was null in \Serenity.Data\SqlHelpers\SqlHelper.cs:
`if (identityColumn == null) throw new ArgumentNullException("query.IdentityColumn");`
Note: in MSSQL, that code is not reached because (dialect.UseReturningIdentity || dialect.UseReturningIntoVar) is false.

The solution: set IdentityColumn in \Modules\Administration\User\Authentication\AuthenticationService.cs :
 `var userId = (int?)new SqlInsert(fld.TableName)
                        .IdentityColumn("UserId")
                        .Set(fld.Username, username)
                        ...
                        .ExecuteAndGetID(connection);
`

Thanks again for your great framework !

**Comment by volkanceylan** [comment]
Thanks @chatcoda for helping me debug this. As PostgreSQL doesn't have something like SCOPE_IDENTITY, i had to use such a workaround. But for it to work, you need to specify it with SqlInsert, or use other connection extension that accepts a row parameter, to automatically set it. I've now converted it and the one in signup page to connection.InsertAndGetId(new UserRow()).

**Comment by chatcoda** [comment]
Fine, thank you!
