### ISSUE TITLE
Sort list on descending order

### ISSUE THREAD

**Issue by tverkroost** [volkanceylan/Serenity#1393]
Hi Volkan, 

I want sort the list on descending order as default.  I put an attribute on this field but that doesn't work. 

[Width(180), QuickFilter, **SortOrder(0, true**)] 
public DateTime Tijdstip { get; set; }

The sort property in the request object is sorted on ascending order as default. 
public ListResponse<MyRow> List(IDbConnection connection, **ListRequest request**)
{
         return new MyRepository().List(connection, request);
}

How to accomplish this? Any help is appreciated.
I look forward to hearing from you soon.

Kind regards,
Tako Verkroost

**Comment by awesomegithubusername** [comment]
Try this in your xtzColumns.cs:

[Width(180), SortOrder(1, descending: true)]
public DateTime Tijdstip { get; set; }

**Comment by tverkroost** [comment]
Hi Volkan,

Thanks for your help. I tried your suggestion, but still doesn't work. Even if I removed the QuickFilter annotation, the list is still sorted on ascending order. Do you have other suggestions what might work?

Kind regards,
Tako Verkroost

**Comment by volkanceylan** [comment]
I'm pretty sure suggestion by @awesomegithubusername works. Orders are not sorted magicially by OrderID descending. See OrderColumns.cs.

**Comment by awesomegithubusername** [comment]
Make sure sorting isn't handled client side (yourGRid.ts file).

**Comment by tverkroost** [comment]
I removed getDefaultSortBy() method from the grid and it worked. Thanks a lot!

Kind regards,
Tako Verkroost
