### ISSUE TITLE
QuickFilter OrderDetail field in order page (OrderColumns)

### ISSUE THREAD

**Issue by CarlosDias7** [volkanceylan/Serenity#1396]
I' m using the northwind exemple and I need to filter a field of OrderDetailRow at OrderColumns.

I guess the image will represent what I'm looking for.

![2](https://cloud.githubusercontent.com/assets/20651929/19888934/0af6e9f0-a019-11e6-9599-d9471b89807c.png)

![1](https://cloud.githubusercontent.com/assets/20651929/19888936/14725db6-a019-11e6-8b07-0ce18a8ce16e.png)

Thanks in advance.

**Comment by edson** [comment]
Search for LookupScript, QuickFilter, FilteredLookupInDetailDialog in  basic samples and Guide. Please read the guide https://volkanceylan.gitbooks.io/serenity-guide/content/ and do the movietutorial before diving in.

Regards

**Comment by volkanceylan** [comment]
He wants to filter orders by a product in details, not something he can find in samples i'm afraid. I'll add one.

**Comment by edson** [comment]
Oh. My bad. Sorry.

Best regards

**Comment by volkanceylan** [comment]
Added that to order grid in latest template:

http://serenity.is/demo/Northwind/Order

**Comment by CarlosDias7** [comment]
That's it what I was looking for. 
Where I can find the source code? 
Thanks @volkanceylan

**Comment by volkanceylan** [comment]
Download latest template, or visit Serene repository.

**Comment by jaydeeprsakariya** [comment]
Hi Can you guide for how to search for simple string field order detail table like Quantity in above example.
