### ISSUE TITLE
Access MaskedEditor Mask from Dialog.ts

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#1397]
Hi,  I'm sorry I still can't figure out how to change the mask from the dialog.  #1377 This is what I have on the form:

     [DisplayName("Phone"),  MaskedEditor(Mask = "(999) 999-9999")]
    public String Phone { get; set; }
	
This is how the HTML renders so I can't figure out where I would specify "(999) 999-9999"

    <input class="editor flexify s-MaskedEditor" id="EventManager_Customer_RegistrantDialog11_Phone" name="Phone" maxlength="250" type="text">	

	
What do I do after this to access the mask in the dialog?  

this.form.Phone.element??

Thank you for being so patient!

**Comment by edson** [comment]
Hi, there.

You could do in typescript
(this.form.Phone.element as any).mask("(99) 9999999-9999");

Best Regards

**Comment by mayatstafford** [comment]
Perfect!   Thank you!

**Comment by teafmartins** [comment]
How can disable mask?
