### ISSUE TITLE
SlickGrid Click Event 3 Second Delay

### ISSUE THREAD

**Issue by DoyleJOfTexas** [volkanceylan/Serenity#1399]
I have subscribed to the slickgrid click event and there is a full 3 second delay to event firing based on the console log. Help please.. I do not think I can get that through the Windows Business Store QA process.

**Comment by volkanceylan** [comment]
There is no such delay. I don't know what you are talking about.

**Comment by DoyleJOfTexas** [comment]
I know when I click the link... I know when the log is written to..code below...perhaps I have not done something properly somewhere else buy my eyes do not lie..

namespace SereneSandR2.SandRDB {
    
    @Serenity.Decorators.registerClass()
    export class NameGrid extends Serenity.EntityGrid<NameRow, any> {
        protected getColumnsKey() { return 'SandRDB.Name'; }
        protected getDialogType() { return NameDialog; }
        protected getIdProperty() { return NameRow.idProperty; }
        protected getLocalTextPrefix() { return NameRow.localTextPrefix; }
        protected getService() { return NameService.baseUrl; }

        constructor(container: JQuery) {
            super(container);

            console.log("constructor is running");
            var grid = this.slickGrid;
            grid.onClick.subscribe(() => {
                console.log("click event running");
                
            });

        }       
    }
}

**Comment by volkanceylan** [comment]
Is this really code you test with? Click runs when you click it, constructor runs at page load, so it can be 50 seconds if you click 50 seconds later.
