### ISSUE TITLE
Azure Active Directory and Serene

### ISSUE THREAD

**Issue by okowiro** [volkanceylan/Serenity#1400]
Hello Volkan,

<add key="ActiveDirectory" value="{ Domain: 'companyname.onmicrosoft.com' }"/>

I have added this to Web. Config and entered my credentials when i logged onto Serene but i keep getting errors below. Any help will be appreciated. This is an AD on Azure. I am the administrator to this Azure environment.

System.DirectoryServices.AccountManagement.PrincipalServerDownException: The server could not be contacted. ---> System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.\r\n   at System.DirectoryServices.Protocols.LdapConnection.Connect()\r\n   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)\r\n   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)\r\n   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request)\r\n   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)\r\n   --- End of inner exception stack trace ---\r\n   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)\r\n   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
\r\n   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)\r\n   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name)\r\n   at Foresight.Genius.Administration.ActiveDirectoryService.Validate(String username, String password) in C:\\Apps\\Foresight.Genius\\Foresight.Genius\\Foresight.Genius.Web\\Modules\\Administration\\User\\Authentication\\ActiveDirectoryService.cs:line 19\r\n   at Foresight.Genius.Administration.AuthenticationService.ValidateFirstTimeUser(String& username, String password) in C:\\Apps\\Foresight.Genius\\Foresight.Genius\\Foresight.Genius.Web\\Modules\\Administration\\User\\Authentication\\AuthenticationService.cs:line 151"

**Comment by volkanceylan** [comment]
I don't know if it works with Azure. You need to check Azure AD docs, and modify that sample provider.

**Comment by okowiro** [comment]
Thanks Volkan for your quick response. I'm kinda new to Serene framework so could you kindly direct me to some links on how to authenticate with Azure AD. One more thing  which of the class files would i have to modify?

**Comment by volkanceylan** [comment]
ActiveDirectoryService.cs. Sorry but i didn't use that.

**Comment by minhhungit** [comment]
Hi @okowiro , did you resolve it, can you share please

**Comment by JardaCZ81** [comment]
@okowiro @minhhungit   did you resolve it, can you share please.

I'd love to have our app Azure AD compatible. It's 2020 ;-)

**Comment by minhhungit** [comment]
@JardaCZ81 
due to security problem so I am not sure I should share it
but there are some points you can follow:

// Reference: https://joonasw.net/view/aspnet-core-2-azure-ad-authentication  
// Complete sample application: https://github.com/juunas11/aspnetcore2aadauth
// Claims: https://andrewlock.net/introduction-to-authentication-with-asp-net-core/
