### ISSUE TITLE
Non modal form

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1401]
Hi.  How do I make a form non modal?  I basically want to make my form a page and not a popup.

**Comment by florin-nitulescu** [comment]
Hi! If you are using Serene template with two projects then use the `PanelAttribute` on your entity dialog class. In your C# (Saltarelle) code after you create the dialog use the `Element` property to insert the form anywhere you want in your DOM: `jQueryDiv.Append(dialog.Element);`.
