### ISSUE TITLE
TimeSpanField exported to excel as Decimal

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1402]
Dear Volkan,
I have TimeSpanField in a Row, when exported data to Excel, it shows as a decimal value i.e. 0.xxxxx
regards
Shailesh

**Comment by volkanceylan** [comment]
Try adding a display format

**Comment by shaileshbc** [comment]
It works, Thanks.
Sorry i didn't think it before raising an issue.
regards
Shailesh
