### ISSUE TITLE
Script bundler randomly not include boostrap-multiselect.js

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1403]
Dear @volkanceylan,
I found an issue while the script bundler is enabled: sometime "boostrap-multiselect.js" file is not included in the bundle (honestly I don't know if this issue happens only for this file).
Symptom:
![image](https://cloud.githubusercontent.com/assets/17425690/19925057/a01b9ca8-a0ee-11e6-92ca-35f7fa2b9b72.png)

Broken bundle: https://dl.dropboxusercontent.com/u/55649962/eService/broken_bundle.txt
Working bundle: https://dl.dropboxusercontent.com/u/55649962/eService/working_bundle.txt

As you can see in the "broken" file the boostrap-multiselect library is missing at all.

Here there is my ScriptBundles.json:

    {
      "Libs": [
        "~/Scripts/pace.js",
        "~/Scripts/rsvp.js",
        "~/Scripts/jquery-{version}.js",
        "~/Scripts/jquery-ui-{version}.js",
        "~/Scripts/jquery-ui-i18n.js",
        "~/Scripts/jquery.validate.js",
        "~/Scripts/jquery.blockUI.js",
        "~/Scripts/jquery.cookie.js",
        "~/Scripts/jquery.json.js",
        "~/Scripts/jquery.autoNumeric.js",
        "~/Scripts/jquery.colorbox.js",
        "~/Scripts/jquery.dialogextendQ.js",
        "~/Scripts/jquery.event.drag.js",
        "~/Scripts/jquery.scrollintoview.js",
        "~/Scripts/jsrender.js",
        "~/Scripts/select2.js",
        "~/Scripts/sortable.js",
        "~/Scripts/toastr.js",
        "~/Scripts/SlickGrid/slick.core.js",
        "~/Scripts/SlickGrid/slick.grid.js",
        "~/Scripts/SlickGrid/slick.groupitemmetadataprovider.js",
        "~/Scripts/SlickGrid/Plugins/slick.autotooltips.js",
        "~/Scripts/SlickGrid/Plugins/slick.headerbuttons.js",
        "~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js",
        "~/Scripts/SlickGrid/Plugins/slick.rowmovemanager.js",
        "~/Scripts/bootstrap.js",
        "~/Scripts/Saltarelle/mscorlib.js",
        "~/Scripts/Saltarelle/linq.js",
        "~/Scripts/Serenity/Serenity.CoreLib.js",
        "~/Scripts/Serenity/Serenity.Script.UI.js",
        "~/Scripts/jquery.cropzoom.js",
        "~/Scripts/jquery.fileupload.js",
        "~/Scripts/jquery.iframe-transport.js",
        "~/Scripts/jquery.slimscroll.js",
        "~/Scripts/mousetrap.js",
        "~/Scripts/fastclick/fastclick.js",
        "~/Scripts/bootstrap-multiselect.js",
        "~/Scripts/bootbox.js",
        "~/Scripts/jquery.signalR-2.2.1.js"
      ],
      "Site": [
        "~/Scripts/adminlte/app.js",
        "~/Scripts/Site/eService.Web.js"
      ]
    }

If I restart IIS it's likely that the bundle is properly regenerated...I don't know why randomly it's not properly generated, in particular the boostrap-multiselect.js is not bundled.

Thank you very much for your support
Bye

**Comment by volkanceylan** [comment]
Sorry @marcobisio but i can't help you with this one. Computers are supposed to be deterministic, and they perform same way when operating in same set of inputs. 

Skipping a particular script randomly is not something script bundler can do on purpose. It's gotta be a configuration problem in your site. E.g. double sites under IIS mapped under each other etc.

**Comment by volkanceylan** [comment]
I've opened your both script bundles in Winmerge, side by side, as i guessed, bootstrap-multiselect is not the only difference.

Serenity.Script.UI.js includes are also different on both sides. Also in place where multiselect should be located, there is your Site.Script.js file with TicketPreAnswerForm etc.

So, i think DynJS.axd is handled by two different sites.

**Comment by volkanceylan** [comment]
Here Serenity.Script.UI.js difference:

![image](https://cloud.githubusercontent.com/assets/752470/19927809/12b0ce7c-a104-11e6-9609-c0f179b9c7eb.png)

**Comment by volkanceylan** [comment]
Your script containing TicketSeverityForm on one side, while multiselect other:

![image](https://cloud.githubusercontent.com/assets/752470/19927824/294ad1d2-a104-11e6-98f2-a66e05492ced.png)

**Comment by marcobisio** [comment]
Thanks for the quick answer @volkanceylan!
The broken file is taken from the test environment while the working one is taken from the dev environment...my apologies...I forgot to tell you!
I took the bundle from two different environment because it's a "rare" issue and I'm keeping "frozen" the broken environment in order to do some diagnostic...
For sure there are differences, but I cannot understand why with the same configuration (the only thing that is different is the connection string) the multiselect library isn't included in the bundle...
I noticed also that the bundler throw exceptions (only if in the browser the dev tools are open ) because some js.map files are missing (at DynamicScriptHandler.cs row 23), but I think that such exceptions aren't related to my problem...
Perhaps I could modify the Serenity sources in order to log which files are bundled...

Thanks as always for your support @volkanceylan 
Bye

**Comment by marcobisio** [comment]
About five days with the bundler disabled and no more issues...
I plan to investigate further, but for now I close the issue to avoid unnecessary "noise" on github!

Thanks anyway @volkanceylan 
Bye
