### ISSUE TITLE
Expire Cache and Refresh Grid on Event

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1404]
I want to make the grid cache expire on an event and then refresh the data grid. 

To be more precise, I have a grid with LookupScript that are not updating after an import...or at least not fully. The fields are being updated on the DB but not on screen. 

I know that after 2.4.6 there is now an expiration field for LookupScript but I'm not sure i'm implementing it properly. 

I've updated the [LookupScript("xyz")] for the linked tables on their respective xyzRow.cs files to have [LookupScript("xyz"), Expiration = -1], which I believed would cause the cache to clear and thus would make the grid refresh after an import. 

At this point after import, if I refresh (F5) the screen, the cache resets and the fields update but I want to achieve the grid refresh without needing to have the user do so manually. 

Originally I wanted the grid to only reset the cache and refresh at the moment an import occurs, thus updating the lookup scripts on the grid but if I get the screen to refresh, I'm fine with leaving the general cache for LookupScript as Expiration = -1. 

I also wanted to update the refresh button since, even after import, if I click on the refresh button, the cache doesn't refresh.

**Comment by volkanceylan** [comment]
Q.reloadLookup

**Comment by sayuga** [comment]
great. Thanks.  I was looking through the sample templates and I saw that. Was going to play around with it in a bit.
