### ISSUE TITLE
Modular Serenity

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1405]
Just an idea when moving forward with Serenity. You could make serenity a modular design. Such as it is with django. Users could create an entire module complete with it's own table set up for the Migrations. It could be as simple as placing the Module in the modules folder, the migrations into the migrations directory and adding the links in `NavigationItems.cs` and you have a complete new module. It could be something to look into and add a site section on serenity.is.

Just a thought. I would also recommend adding a forum to serenity.is. myBB or phpBB are good starting points and Bitnami has a complete stack ready for download. Oh and it's free.

**Comment by edson** [comment]
Hi, there. I don't know If I undertood your suggestion correctly... But serenity is already modular... It has support for migrations through fluentmigrator and a code generator If you wish for your generated tables...
There is even a Good guide for that.. what's the different approach that Django gives you?

Best regards

**Comment by williamhodges** [comment]
I was referring to having a place where we could share modules that we have created

**Comment by volkanceylan** [comment]
Thanks for ideas. I'll consider them.
