### ISSUE TITLE
QuickFilter with LookupEditor or LookupFiltering

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1408]
I'd like reference issue #1078 

I know how to add use QuickFilter and LookupEditor with a custom lookup script to accomplish the below but I'd like to know if there's a way to do this without creating any custom lookup scripts.

What I would like is to add [QuickFilter, LookupEditor(typeof(xyzRow), FilterField = nameof(xyzRow.Fields.SetupBy))] or something similar that will create LookupEditor based QuickFilters for rows that are not not namefield.

I've tried adding [LookupInclude] to SetupBy field but that doesn't work and still returns the value from namefield. I've read the guides and searched forums but can't find any conclusively to suggest it can\can't be done.

**Comment by edson** [comment]
Hi, there.

If you want to filter quickfilter with a lookupincluded column, you could use something like
[QuickFilter, QuickFilterOption("FilterField", "IsActive"), QuickFilterOption("FilterValue", "1")]
where IsActive is your LookupInclude fieldname and FilterValue is your desired value...

But if you want to change namefield... .either change NameField property to an existing or a custom field with expression(maybe wwith a CASE WHEN etc)  from YourXYZrow.cs.

Other than that, you probably be better with a custom editor. Just like the one in basic samples.

I don't know if it is what you mean with your problem.... But anyway, hope it helps.

Best Regards

**Comment by abelal83** [comment]
hi @edson  

thanks for the response, it's not what I'm trying to accomplish and I suspect there's nothing built into Serene that will do it.

**Comment by volkanceylan** [comment]
You need to write custom editor for this, see custom text editor sample
