### ISSUE TITLE
lessc.cmd Command exit

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#141]
when I create my website with the serenity template,it can't be compiled with the error 'lessc.cmd site.less  site.css  order exit';

**Comment by ChenZhaobin** [comment]
After I update old projects nuget packages,it also get this problem

**Comment by volkanceylan** [comment]
No idea what is order exit. There should be something else in output window.

**Comment by ChenZhaobin** [comment]
Sorry,my English is just so so,the problem is at this point :   Exec Command="&quot;$(ProjectDir)tools\node\lessc.cmd&quot; &quot;$(ProjectDir)Content\site\site.less&quot; &gt; &quot;$(ProjectDir)Content\site\site.css&quot;">

**Comment by volkanceylan** [comment]
Probably tracked down the problem. NuGet wasn't including lessc file as it didn't have an extension. Try updating to 1.9.5 please.

**Comment by ChenZhaobin** [comment]
Tank you very much,It also doesn't work,but I fixed it by override the  folder tools/node over the source code pulled from git ,but coming  another error:(Serenity.Script.Core.js:645 Uncaught Script data Template.LoginPanel is not found in registered script list!)

**Comment by volkanceylan** [comment]
Rebuild project, and make sure you use IISExpress not development server.

**Comment by ChenZhaobin** [comment]
It 's my fault ,I forgot to  update serenity gallery.Now it works!

**Comment by ChenZhaobin** [comment]
Could you tell  me where is Template.LoginPanel,Is it added in  v1.9+?

**Comment by volkanceylan** [comment]
No, it was always there. Check console for other errors. Bundle.Template for example.

**Comment by ChenZhaobin** [comment]
oh,my god ! The real answer for  my problem  is that I use a solution name like A.B,then creating project names A.B.Scripts\A.B.Web ,this is not allowed in Serenity.Haha!How foolish I am!
