### ISSUE TITLE
Set date with AddMonths in row as readonly

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#1412]
Hi to all,
   I have a problem showing this in the grid upon loading.
what i want to do is to automatically add 12 months to the current date(Date Cert) in another
column, i set the DueCert as ClienSide because it is not in database.
this is what i do in My Row.. thanks in advance!

```
DisplayName("Date Cert"), NotNull]
        public DateTime? DateCert
        {
            get { return Fields.DateCert[this]; }
            set { Fields.DateCert[this] = value; }
        }

        [DisplayName("DueCert"), SetFieldFlags(FieldFlags.ClientSide)]
        public DateTime? DueCert
        {
            get
            {
                return DateCert.Value.AddMonths(12);
            }

        }
```

**Sample Output:
DateCert: 01/01/2015
DueCert: 01/01/2016**

**Comment by williamhodges** [comment]
What does your MyColumn.cs look like?

**Comment by adhikamafran** [comment]
try add this to your attr 
`SetFieldFlags(FieldFlags.Calculated),Expression("DATEADD(year, 1,[T0].DateCert)")`

**Comment by alex-444** [comment]
Thanks @adhikamafran !
I see using expression..
here is my final row..


```
[DisplayName("DueCert"), SetFieldFlags(FieldFlags.Calculated),Expression("DATEADD(month, 1,[T0].DateCert)")]
        public DateTime? DueCert
        {
                get { return Fields.DateCert[this]; }
                set { Fields.DateCert[this] = value; }
         
        }
```

**Comment by volkanceylan** [comment]
Just to note, You dont need to add calculated.
