### ISSUE TITLE
export excel/pdf buttonları ekleme

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1414]
Üstad merhaba, 
öncelikle böyle bir platform oluşturdğunuz için çok teşekkür ederim.Ben yeni kullanmaya başladım size göre çok basit soru olabilir ama ben malesef başaramadım.Sorum şu ; 
sergen ile yeni bir table için scriptleri çalıştırdıktan sonra , export excel ve pdf buttonları oluşmuyor.Ben de ProductEndpoint.cs 'de ki "FileContentResult ListExcel" ve ProductGrid.ts'de ki "getButtons" methodlarını hata vermeyecek şekilde kendi table'ım için ekledim fakat build etmeme rağmen excel,pdf buttonlarını formda göremiyorum.Ne yapmalıyım , yardımcı olursanız çok minnettar olurum

**Comment by volkanceylan** [comment]
TypeScript 2.0 kurmamışsınızdır tahminim.

**Comment by volkanturk** [comment]
üstad az önce kurdum, tekrar denedim  fakat olmadı , atladığım birşey mi var :(

**Comment by volkanceylan** [comment]
Bilemiyorum o kadar grid de çalışıyor demek ki yanlış yer yanlış grid dialog vs.
