### ISSUE TITLE
GetLookup in TS (select)

### ISSUE THREAD

**Issue by ngocnb90** [volkanceylan/Serenity#1415]
Hi everyone!

i have code for TS
 `var ngoc = Q.first(columns, x => x.field === fld.Mdg);
            ngoc.referencedFields = [fld.Mdg];
            ngoc.format = ctx => this.selectFormatter(ctx, fld.Mdg, ThongSo.MucDanhGiaRow.getLookup());`
for select box of table 
![image](https://cloud.githubusercontent.com/assets/23022595/20045361/052c9e98-a4d3-11e6-8d22-9aa6cc744d6b.png)

i want lookup by MlcdId (a column in this gird). I try with
![image](https://cloud.githubusercontent.com/assets/23022595/20045409/5ddd981c-a4d3-11e6-94c7-da2f5eb53018.png) or getLookup.items

but it not running.

How can do it? Thanks

**Comment by adhikamafran** [comment]
hi, what is your error message and selectFormatter function?

**Comment by ngocnb90** [comment]
![image](https://cloud.githubusercontent.com/assets/23022595/20046640/83580518-a4de-11e6-83f7-132d27ae59b3.png)
Here

**Comment by adhikamafran** [comment]
key : string , i assumed your MlcdId is number. try cast as string.

**Comment by ngocnb90** [comment]
![image](https://cloud.githubusercontent.com/assets/23022595/20046994/61d73388-a4e2-11e6-8264-dee92941e1ee.png)
![image](https://cloud.githubusercontent.com/assets/23022595/20047031/bb225832-a4e2-11e6-9724-fe135c6c43f9.png)
i tried

**Comment by adhikamafran** [comment]
sorry, is this.selectFormatter your custom function? i see, your parameter should be Lookup<any> not number like ThongSo.MucDanhGiaRow.getLookup().itemById[fld.MlcdId].MlcdId.

**Comment by ngocnb90** [comment]
![image](https://cloud.githubusercontent.com/assets/23022595/20051318/ffd1e9a2-a500-11e6-85d5-4bcd9be076a0.png)
![image](https://cloud.githubusercontent.com/assets/23022595/20051333/1603ad6e-a501-11e6-8fc7-669be5a85308.png)
In selectFormatter not running **itemById** ? @adhikamafran

**Comment by volkanceylan** [comment]
fld.MlcdId is a field name, not an item ID, see other samples there and apply them correctly.

**Comment by ngocnb90** [comment]
fld.MlcdId is a fieldName

`
  [DisplayName("Mlcd Id"), Hidden]
        public Int32? MlcdId
        {
            get { return Fields.MlcdId[this]; }
            set { Fields.MlcdId[this] = value; }
        }

 [DisplayName("Mdg")]
        public Int32? Mdg
        {
            get { return Fields.Mdg[this]; }
            set { Fields.Mdg[this] = value; }
        }
`

**Comment by ngocnb90** [comment]
Thanks @volkanceylan and @adhikamafran 
I change selectFormatter with
![image](https://cloud.githubusercontent.com/assets/23022595/20093842/13ec93bc-a5d1-11e6-9efa-534a7e187179.png)

![image](https://cloud.githubusercontent.com/assets/23022595/20093848/202b9b46-a5d1-11e6-9801-48ac6e9c32a5.png)
 for field Mdg
![image](https://cloud.githubusercontent.com/assets/23022595/20093866/3c3036b2-a5d1-11e6-9b2d-0f1f12f18cfc.png)
 
how to sort by it?

**Comment by volkanceylan** [comment]
Lookups are sorted by name field.
