### ISSUE TITLE
Can't find enum type!

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#1416]
Thank you for this fantastic template.

I'have defined a enum but can't find at client side. I have tried all possible solution suggested on this forum. 

 I'm using visual studio 2015 update 2. Serene version 2.5.8.0

TS file is also created after "transfer All T4 tempaltes" but still cant find enum.

Can some one please help.

Thanks.

**Comment by adhikamafran** [comment]
see https://github.com/volkanceylan/Serenity/issues/1131

**Comment by sayuga** [comment]
Check that the namespace is set correctly for the enum, then go ahead and rebuild followed by transform. At times, it's just that the namespace is misspelled or such.

**Comment by mustafalotiya** [comment]
Thanks. 

It was a name space issue. By applying correct name space and enum key fixed issue.

**Comment by djog** [comment]
I have the same issue.  I am using Serenity report template to build report criteria screen.  One of the control on the screen would be the combo box that uses enum for the dropdown list.  However, I cannot get this enum key set right.  throws an error saying cannot find the enum key.  I am assuming its the path that it cannot find.  But I cannot figure out the correct path.

How did you set the path?

**Comment by djog** [comment]
I am getting the same error!  Not able to figure out what's going on.  Trying to use the enum type for the combo box dropdown list on a report criteria screen that uses the Serenity report template.  

Followed the same procedure as in the tutorial to create the .cs file where I define the enums.  However, I am using their report template and not sure what else I have to do to make it work with the template.  I transformed ALL T4 templates and rebuilt the project as well.  No luck.

Would appreciate any clue on this!

Thanks.

**Comment by mustafalotiya** [comment]
I'm not sure about report template as I used only for form dialog type script and on forms.
