### ISSUE TITLE
Bug with first category collapsed by default

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1417]
Dear @volkanceylan,
just found a bug when the first category of a form is collapsed by default:

![image](https://cloud.githubusercontent.com/assets/17425690/20056381/2259e580-a4e6-11e6-8997-b32e6305bc51.png)

I think that's a css issue, because the first category it's the only one with the "first-category" class...
In fact the 2nd category collapsed by default it's ok...

I'll check the css and I let you know if I find the solution...

Thanks
Bye

**Comment by volkanceylan** [comment]
Are you using Serenity as submodule?

**Comment by marcobisio** [comment]
No I've developed my application starting from a standard Serene template...
I checked my original code and this glitch never happens, but your implementation it's a bit different!

**Comment by volkanceylan** [comment]
My implementation is different because you forgot to handle validation issue. Invisible items don't get validated.

**Comment by marcobisio** [comment]
I know I know...was my fault!

**Comment by volkanceylan** [comment]
:) sorry no faults

it's not a bug. it happens because customer is focused on dialog open (as it is first input). i recommend not collapsing first category initially or focus another input.

**Comment by volkanceylan** [comment]
These issues was primary reason why i didn't like much idea of collapsible forms etc. If you hide them you lose validation, if you don't you'll always have such problems.

**Comment by volkanceylan** [comment]
Ok, add this:

```css
.s-PropertyGrid .category.collapsed .field {
    visibility: hidden;
}
```
It seems to fix focus and validation issue

**Comment by marcobisio** [comment]
Yes...now it's working fine!!

Thank as always for your kind support (and for your patience!!!)
Bye
