### ISSUE TITLE
Bind Serenity Widget to jQuery element

### ISSUE THREAD

**Issue by zeezment** [volkanceylan/Serenity#1418]
Hi all!

In a partial view xyz.cshtml, if I find jQuery elements by Id, is there a way to bind it to a Serenity Widget, from the input element, in this case, the MultipleImageUploadEditor?

```
new Serenity.MultipleImageUploadEditor($('#Attachments'), {}).init();
```
the code above binds the element but only the temporary file gets uploaded, what needs to be called the get the object array for the attached files before actually posting to the endpoint

**Comment by thechadc** [comment]
@volkanceylan where is the object array stored that has all the attached files?

**Comment by volkanceylan** [comment]
yourEditor.value

**Comment by thechadc** [comment]
Thanks @volkanceylan, it was actually $('yourEditor').data().Serenity_MultipleImageUploadEditor.entities, and you'd still have to use the saverequesthandler as it processes the file from temp storage

**Comment by volkanceylan** [comment]
You should assign your editor widget to a variable first:

```
var yourEditor = new Serenity.MultipleImageUploadEditor($('#Attachments'), {})
```

If you somehow didn't have widget reference, you could get it with:

```
$('#Attachments').getWidget<Serenity.MultipleImageUploadEditor>()
```

**Comment by zeezment** [comment]
Thanks @thechadc and @volkanceylan! Works out both ways
