### ISSUE TITLE
Refresh Recaptcha

### ISSUE THREAD

**Issue by CarlosDias7** [volkanceylan/Serenity#1419]
Is there a command to refresh/reaload the recaptcha component?

**Comment by DouglasEFerreira** [comment]
I had the same problem last week and I solve this using location.reload(). So the will be reloaded and reset de catcha.

**Comment by edson** [comment]
Just call the javascript API from recaptcha:

`grecaptcha.reset();`

It will default to first widget created...
https://developers.google.com/recaptcha/docs/display#js_api

Best Regards
