### ISSUE TITLE
GridEditorBase e item eklemek

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity#142]
Aşağıda yer alan kod yapısı grid içerisine item ları ekliyor ancak grid i refresh edemiyorum, konu ile ilgili yardım edebilirseniz sevinirim,

public class QuestionOptionEditor : GridEditorBase<QuestionOptionRow>
{
    public QuestionOptionEditor(jQueryObject container)
        : base(container)
    { }

    protected override List<ToolButton> GetButtons()
    {
        List<ToolButton> buttons = base.GetButtons();
        buttons.Add(new ToolButton
        {
            Title = Q.Text("Generate Options"),
            CssClass = "generate-options-button",
            OnClick = delegate
            {
                    this.Items.Add(new QuestionOptionRow { OptionText = "YEŞİL", SortOrder = 10, IsActive = true });
                    this.Items.Add(new QuestionOptionRow { OptionText = "SARI", SortOrder = 20, IsActive = true });
                    this.Items.Add(new QuestionOptionRow { OptionText = "KIRMIZI", SortOrder = 30, IsActive = true });
                    this.Refresh();
            }
        });
        return buttons;
    }
}

**Comment by volkanceylan** [comment]
Refresh serverdan verileri yenilemek için. Bu in-memory olduğu için birşey yapmaz.

```cs
this.View.SetItems(this.Items, true)
```

Böyle bir deneyin.
