### ISSUE TITLE
Dropdown is Not getting red when it's required 

### ISSUE THREAD

**Issue by DouglasEFerreira** [volkanceylan/Serenity#1420]
My dropdown is required and not null so when I try to save a dialog if its empty a message 'that required fields are empty' pops up but the dropdown is not getting highlited.

The image shows a date field that is required and is getting red when validated but the dropdown not:
![dropdown](https://cloud.githubusercontent.com/assets/20241746/20065334/e136f89a-a4f4-11e6-80d5-4c7ef4184b4e.png)

**Comment by volkanceylan** [comment]
it doesnt seem required to me

**Comment by DouglasEFerreira** [comment]
![3](https://cloud.githubusercontent.com/assets/20241746/20071276/f7305ef0-a50a-11e6-8b30-25e26b7dfdbd.jpg)

**Comment by volkanceylan** [comment]
First of all, dropdowns doesn't get red, it's Select2 not an input, and works as designed. You may style them with CSS if you care:

```
.select2-container.error .select2-choice {
    border-color: red;
}
```

Your dialog has scroll problems and error checks not visible.

**Comment by DouglasEFerreira** [comment]
Thanks @volkanceylan
