### ISSUE TITLE
Incorrect rendering of in-memory grid by slick.grid.js

### ISSUE THREAD

**Issue by mkoval-ua** [volkanceylan/Serenity#1422]
After some manual manipulation with grid on UI the editor grid becomes blank though actually there are still many items. It's because incorrect visible region calculation. Particularly function 
```cs
        function getVisibleRange(viewportTop, viewportLeft) {
            if (viewportTop == null) {
                viewportTop = scrollTop;
            }
            if (viewportLeft == null) {
                viewportLeft = scrollLeft;
            }

            return {
                top: getRowFromPosition(viewportTop),
                bottom: getRowFromPosition(viewportTop + viewportH) + 1,
                leftPx: viewportLeft,
                rightPx: viewportLeft + viewportW
            };
        }
```

The function returned NaN for leftPx and rightPx what was then used in getRenderedRange and resulted in invalid rendering. It's because of the optimization when out-of-visible-region elements are not rendered while in that case they were indeeed within visible region.

In my case the problem was caused by NaN of scrollLeft so I fixed it as following in my project:
```cs        
        function getVisibleRange(viewportTop, viewportLeft) {
            if (viewportTop == null) {
                viewportTop = scrollTop || 0;
            }
            if (viewportLeft == null) {
                viewportLeft = scrollLeft || 0;
            }

            return {
                top: getRowFromPosition(viewportTop),
                bottom: getRowFromPosition(viewportTop + viewportH) + 1,
                leftPx: viewportLeft,
                rightPx: viewportLeft + viewportW
            };
        }
```

But probably "deeper" fix is needed there. I mean maybe NaN for scrollLeft should be prevented on earlier stages.

**Comment by volkanceylan** [comment]
Thanks for sharing. I didnt see such problem yet, but it might be due to some changes in jQuery 3. Need to identify where it sets scrollLeft to NaN though.

**Comment by mkoval-ua** [comment]
Unfortunately I cannot reproduce it now - even when undo my fix mentioned above. Probably something else changed that prevents this issue from happening. By the way it was reprodusable when to set user agent to Chrome on Mac

**Comment by mkoval-ua** [comment]
@volkanceylan This issue appears again after I've applied serenity upgrade which overrode slick.grid.js in my project. It's actually not an easy task to identify where it sets scrollLeft to NaN as this primarily UI rendering issue so any switches to debug window and mouse moves generate new events. Could you just apply this easy workaround that I've suggested at the beginning so it will not discard my fix next time when I will upgrade Serenity from nuget repository? 

Thanks in advance!

**Comment by volkanceylan** [comment]
There are a few places in slick.grid.js that scrollLeft is set. Can you put a Q.log("in somemethod ": scrollLeft) on that places so we see when it gets messed up.

**Comment by mkoval-ua** [comment]
@volkanceylan Thank you for the advice! I have found real cause of the issue. It happens there (in slick.grid.js):
`function handleMouseWheel(e, delta, deltaX, deltaY) `

delta, deltaX and deltaY is undefined due to unknown reason!

Fortunately I've found suggestion on stackoverflow to use e.originalEvent:
http://stackoverflow.com/questions/8886281/event-wheeldelta-returns-undefined

So after I've substituted the calculated values instead of deltaX, deltaY then the problem's gone:
```
            var myDeltaX = typeof (deltaX) == "undefined" ? e.originalEvent.deltaX : deltaX;
            var myDeltaY = typeof (deltaY) == "undefined" ? e.originalEvent.deltaY : deltaY;
```
Could you please apply the fix to Serenity code base.

Thank you!

**Comment by mkoval-ua** [comment]
@volkanceylan Just wondering if you haven't missed my investigation results above..

**Comment by volkanceylan** [comment]
2.7.2 should have that fix, doesn't it?

**Comment by mkoval-ua** [comment]
Yes, thank you!!!
