### ISSUE TITLE
Show data in horizontal format rather than vertical format in form

### ISSUE THREAD

**Issue by WestleyHoxton** [volkanceylan/Serenity#1423]
![2016-11-08_14-23-25](https://cloud.githubusercontent.com/assets/22673494/20085797/8497aa6e-a5bf-11e6-8675-31d8675fb0de.jpg)

Hi Volkan

As you can see in the image attached, the schedule days are shown in a vertical fashion. Is it possible to show the schedule days on horizontal format? (like using some attribute maybe?)

Regards

Westley

**Comment by Estrusco** [comment]
You can set the position using the CSS. See the example https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/MultiColumnResponsiveDialog and https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Content/site/site.basicsamples.less

**Comment by WestleyHoxton** [comment]
Hi Estrusco

Thanks for you quick reply. I went through the examples you mentioned and tried it against my module. However it did not work. I'm not sure what I'm doing wrong. This is what I did

I added the following line to site.css
  .s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Sun,
   s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Mon,
  s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Tue,
  s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Wed,
  s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Thu,
  s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Fri,
  s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog .field.Sat {
    flex: auto;
    min-width: 100%;
  }

PS: EDWMetaDataManagment is a folder  under Modules

I also added the following lines to site.EDWMetaDataManagment.less

.s-EDWMetaDataManagment-CtrlDataSourceLoadScheduleDialog {
    > .size { width: 650px; height:500px;}
    .caption { width: 150px; }
        .field.Sun, .field.Mon, .field.Tue, .field.Wed, 
        .field.Thu, .field.Fri, .field.Sat {
            flex: auto;
            min-width: 100%;
            }
 }

Do I need to do anything more?

Regards

Westley

**Comment by Estrusco** [comment]
You have to modify only .less file. The .css is auto generated in compilation.

If you have a site.EDWMetaDataManagment.less under Content/site, you must add this in site.less. In this file the Sergen have created a basic css definition for your Dialog. Find it and move to your site.xyz.less, then edit it.
**Read the manual!!!**

In addition if you write min-width: 100% then the fields have the width o100%. If you want two field in the same row, you have to write min-width: 50%  (three on row 33%, etc.)
Also try to enlarge the form (> .size { width: **950**px; height:500px;})
Also you can add a @media element to set this only for wide device

**Comment by WestleyHoxton** [comment]
Hi Estrusco

Thanks for pointing me in the right direction. I now got it working (after a lot of trial and error, since I don't have much experience with asp.net). Never the less I am happy, it is working. Many thanks to you. Below is the outcome

![2016-11-10_13-07-07](https://cloud.githubusercontent.com/assets/22673494/20162267/e75165f8-a747-11e6-845f-0b025fae7026.jpg)

**Comment by WestleyHoxton** [comment]
Closing this issue since I got it working
