### ISSUE TITLE
CascadeFrom base on a non Lookup field

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1426]
I have an Data row Partner and he hold a Contacts collection. 
When i try to filter the Contacts lookup by the PartnerId all the records gets to the client but non are showing in the UI.

----------------------- Partners ---------------------------

  public sealed class PartnersRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

       [DisplayName("Accounting Contact"), ForeignKey("[dbo].[PartnerContacts]", "Id"), LeftJoin("jAccContact"), TextualField("AccContactFirstName")]

        [LookupEditor(typeof(Scripts.PartnerContactsLookup), CascadeFrom = "Id", CascadeField = "PartnerId")]
        public Int32? AccContactId
        {
            get { return Fields.AccContactId[this]; }
            set { Fields.AccContactId[this] = value; }
        }
}

----------------------- PartnerContacts ---------------------------

    public sealed class PartnerContactsRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Partner"), NotNull, ForeignKey("[dbo].[Partners]", "Id"), LeftJoin("jPartner"), LookupInclude]
        public Int32? PartnerId
        {
            get { return Fields.PartnerId[this]; }
            set { Fields.PartnerId[this] = value; }
        }
}

Am i missing something?

**Comment by in32bit** [comment]
After reading carefully in the documentation i found out the cascading work perfectly when i put the lookup script attribute above the the entity row class. But when i create a custom lookup base on the the entity row the cascading wont work as the include property wont pass to the client.

This behavior is normal? or am i missing something?

**Comment by volkanceylan** [comment]
So add that missing field to your custom lookup.

**Comment by in32bit** [comment]
Thank you. I added the missing field in the select query at the PrepareQuery method.
