### ISSUE TITLE
Push Checkbox Column To Existing Grid

### ISSUE THREAD

**Issue by csteppe** [volkanceylan/Serenity#1429]
Hi Guys, 

Im trying to push a whole new column into an existing grid with Checkboxes in them, I found an example here but now not sure how to get the check boxes to display.

Thanks! 

```
  protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();
            columns.push(
                {
                    field: "CheckBoxRow",
                    selectable: true,
                    name: "Edit",
                    format: ctx => {
                        return "Checkbox";
                    },
                });
            return columns;
        }
```

**Comment by thechadc** [comment]
Are you kidding me?

**Comment by thechadc** [comment]
There's not magic here..
 You need to define what needs to be pushed. eg:

     protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();
                columns.push({
                    field: "something",
                    name: "something",
                    format: ctx => {
                        var item = ctx.item;  //data for that row
                        return "<input type='checkbox'>";
                    },
                    width: 150
                });
            return columns;
        }

**Comment by csteppe** [comment]
I sit opposite you . An email would have been 💯 ;)

**Comment by csteppe** [comment]
The above does not work , It adds an html textfield which is not suitable in our case . After some research I discovered that SlickGrid has Editors which serve this purpose (e.g editor: Slick.Editors.Text) I am not sure how  I would use this in Serenity though.

**Comment by marcobisio** [comment]
Hi @csteppe, I cannot understand what you are trying to achieve...
If the new column it's only for selection purposes, than look at this (for example): http://serenity.is/demo/BasicSamples/CancellableBulkAction otherwise add such column to your xyzRow...

Bye
