### ISSUE TITLE
How to display warning dialog when - in an edit dialog - a checkbox is being checked by the user

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#143]
Good evening JaiQ,

John Ranger here with another question :-)

I have a Dialog with a Checkbox, which - when checked  and then the update button on the Dialog is clicked - will as a consequence overwrite some values on a possibly large number of records in another table (reseting These values to Default values) and then syncing These Changes to System Center Service Manager. 

As this is a potentially dangerous action, I want to warn and clearly inform the user with a Special Dialog about the consequences of what happpens when he/she checks this Checkbox.

1) How would I add an Event (jquery Checked if I understand correctly) to the particular Checkbox field?
2) How would I create a similar Dialog like serenity has when an underlying SQL error is displayed?
3) How would I "attach" the displaying of this Dialog to the above Event?

Thank you for your Support 

and with Kind regards,

John

**Comment by volkanceylan** [comment]
```
form.TheCheck.Element.Click = e => { ... }
```

Q.Confirm is probably what you are looking for.

**Comment by volkanceylan** [comment]
Or Q.Alert if you just want to show message.

**Comment by JohnRanger** [comment]
Hi JaiQ,

Many thanks for guiding me into the right direction. Please keep up your excellent work!

With Kind regards, 
John 

-----------------------------


For the benefit of other Readers - here the code that worked for me (replace Value1, Value2, Value3 and xxx with real values from your project):

**do this in the xyzDialog.cs:**
-----------------------------
```
public xyzDialog()
       {
            form = new xyzForm(this.IdPrefix);
            //...

            form.UpdateInitialValuesOnAllAssociatedClients.Change(e => 
                {
                    if (form.UpdateInitialValuesOnAllAssociatedClients.Value == true)
                    {
                        var opt = new Serenity.AlertOptions();
                        Q.Warning("Warning! Checking this checkbox and click on update will reset Value1, Value2 and Value3 on xxx assets. These assets may already be in use and have these values set to their individual requirements.\n\nDo you really intend to do that?", opt);
                    }
                });
      }
```
