### ISSUE TITLE
Performance: removing unused js file includes for login page

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1431]
Hi guys,

We have deployed a Serenity app in a private cloud. However, the initial load for login page in a new browser has a significant delay, especially for mobile devices.

To improve loading time, I'm trying to cull the js script included in the Layout for the login page. (I created a special _Layout.cshtml just for login; the other pages after login use the normal _Layout.). However I'm not very familiar with the includes. Can you help me pick out which can be safely removed form the login page (that is unused by Login)?

Partly from the original _Layout.cshtml:
```
@{Html.RenderPartial(MVC.Views.Shared._LayoutHeadMeta);}
@Html.Stylesheet("~/Content/font-open-sans.css")
@Html.Stylesheet("~/Content/font-awesome.css")
@Html.Stylesheet("~/Content/simple-line-icons.css")
@Html.Stylesheet("~/Content/ionicons.css")
@Html.Stylesheet("~/Content/aristo/aristo.css")
@Html.Stylesheet("~/Content/bootstrap.css")
@Html.Stylesheet("~/Content/colorbox/jquery.colorbox.css")
@Html.Stylesheet("~/Content/jquery.fileupload.css")
@Html.Stylesheet("~/Content/pace.css")
@Html.Stylesheet("~/Content/slick.grid.css")
@Html.Stylesheet("~/Content/css/select2.css")
@Html.Stylesheet("~/Content/toastr.css")
@Html.Stylesheet("~/Content/serenity/serenity.css")
@Html.Stylesheet("~/Content/site/site.css")
@{var cookie = Request.Cookies["ThemePreference"]; var theme = cookie != null && !cookie.Value.IsEmptyOrNull() ? cookie.Value : "default"; }
<script type="application/json" id="ScriptCulture">@Html.Raw(Serenity.JSON.Stringify(new ScriptCulture()))</script>
<script type="text/javascript">window.paceOptions = { minTime: 250, ghostTime: 250, restartOnRequestAfter: 250, ajax: { trackMethods: ['GET', 'POST'], trackWebSockets: true, ignoreURLs: [] } };</script>
@Html.Script("~/Scripts/pace.js")

@* TODO: minimize the JS includes for login page to improve loading *@
@foreach (var x in CommonIncludes.Scripts) { @Html.Script(x) }
@Html.Script("~/Scripts/jquery.cropzoom.js")
@Html.Script("~/Scripts/jquery.fileupload.js")
@Html.Script("~/Scripts/jquery.iframe-transport.js")
@Html.Script("~/Scripts/jquery.slimscroll.js")
@Html.Script("~/Scripts/mousetrap.js")
@Html.Script("~/Scripts/fastclick/fastclick.js")
@Html.Script("~/Scripts/adminlte/app.js")
@Html.Script("~/Scripts/Site/XXXXXX.Web.js")
<script src="~/DynJS.axd/@HtmlScriptExtensions.GetLocalTextInclude(this.Html, "Site")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("ColumnsBundle")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("FormBundle")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("TemplateBundle")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("RegisteredScripts")"></script>
```

Also we had dispensed with the animated wallpaper change (powered by vegas.js) and stuck with a single bg image.

Thanks in advance

**Comment by volkanceylan** [comment]
You should turn on bundling and minification. You may also remove cropzoom, file upload, fastclick etc.

**Comment by john20xdoe** [comment]
Thanks @volkanceylan 
Bundling and minification is already on.
I'll try removing the mentioned libs (cropzoom, file upload, fastclick) and update this thread with the effect after we deploy on wednesday.

**Comment by john20xdoe** [comment]
Thanks @volkanceylan 
Bundling and minification is already on.
I'll try removing the mentioned libs (cropzoom, file upload, fastclick) and update this thread with the effect after we deploy on wednesday.

**Comment by john20xdoe** [comment]
I have applied bundling using this approach:
[timgthomas.com/2012/09/a-quick-start-of-asp-net-mvc-4s-bundling/](timgthomas.com/2012/09/a-quick-start-of-asp-net-mvc-4s-bundling/)


I was able to bundle the thirdparty js, including the `Common.Includes`, from this `_Layout` code block:
```
@foreach (var x in CommonIncludes.Scripts) { @Html.Script(x) }
@Html.Script("~/Scripts/jquery.cropzoom.js")
@Html.Script("~/Scripts/jquery.fileupload.js")
@Html.Script("~/Scripts/jquery.iframe-transport.js")
@Html.Script("~/Scripts/jquery.slimscroll.js")
@Html.Script("~/Scripts/mousetrap.js")
@Html.Script("~/Scripts/fastclick/fastclick.js")
@Html.Script("~/Scripts/adminlte/app.js")
@Html.Script("~/Scripts/Site/XXXXXX.Web.js")
```

by using this `BundleConfig.cs`:
```
public static void RegisterBundles(BundleCollection bundles)
        {
            
            var myJSBundle = new ScriptBundle(ScriptBundlePath);
            var myLesserJSBundle = new ScriptBundle(LesserScriptBundlePath);
            //myJSBundle.IncludeDirectory("~/Scripts/");

            /* ADD THE SCRIPTS IN ORDER*/
            myJSBundle.Include("~/Scripts/pace.js");
            myLesserJSBundle.Include("~/Scripts/pace.js");

            //Serene's common scripts (jquery etc)
            foreach (var x in Serenity.Web.CommonIncludes.Scripts)
            {
                myJSBundle.Include(x);
                myLesserJSBundle.Include(x);
            }
            myJSBundle.Include("~/Scripts/jquery.cropzoom.js");
            myJSBundle.Include("~/Scripts/jquery.fileupload.js");
            myJSBundle.Include("~/Scripts/jquery.iframe-transport.js");
            myJSBundle.Include("~/Scripts/jquery.slimscroll.js");
            myJSBundle.Include("~/Scripts/mousetrap.js");
            myJSBundle.Include("~/Scripts/fastclick/fastclick.js");
            myJSBundle.Include("~/Scripts/bootstrap-toggle/bootstrap-toggle.min.js");
            myJSBundle.Include("~/Scripts/adminlte/app.js");
            myJSBundle.Include("~/Scripts/Site/XXXXXX.Web.js");

            myLesserJSBundle.Include("~/Scripts/adminlte/app.js");
            myLesserJSBundle.Include("~/Scripts/Site/XXXXXX.Web.js");

            bundles.Add(myJSBundle);
            bundles.Add(myLesserJSBundle);
            
        }
```

The bundling works, and most (but not all) of the thirdparty JS files are minified.

However, I have two issues:
1. The generated JS from typescript `XXXXX.Web.js` is not minified, but is still included in the bundled file (therefore it still reached 1.6MB in size).

2. Is it possible to include these four lines into the minified bundle as well? How do I call them in the ByndleConfig above?
```
<script src="/DynJS.axd/LocalText.Site.en-US.Public.js?v=pz-908NP5XitOlTFyknjZQ2"></script>
<script src="/DynJS.axd/ColumnsBundle.js?v=JkuGn4UATQYT_A9h5wHFPw2"></script>
<script src="/DynJS.axd/FormBundle.js?v=oN6Vqbs-CyV1AIA247CNdQ2"></script>
<script src="/DynJS.axd/TemplateBundle.js?v=pvWAsLV5dqxamRB-upusVw2"></script>
<script src="/DynJS.axd/RegisteredScripts.js?v=NZAAbUN1J3z23MVXjZc05w2"></script>
```

I know this borders on ASP MVC logic, but based on the Serene perspective, I could appreciate any nudges to the right direction, and hope this may also help others. Thanks in advance!

**Comment by volkanceylan** [comment]
I wouldn't even try these. You are trying to do something very very wrong. Use Serenity bundling and nothing else. 

Let's say you made this work somehow, after login users will still download other bundle, which will contain same scripts, which is useless.

What you should do is define multiple bundles in ScriptBundles.json. Currently there is two there. Site and Libs. Modify it to BaseLibs, OtherLibs, BaseSite, OtherSite etc. No two bundles should have same script.

**Comment by john20xdoe** [comment]
Thanks for the guidance @volkanceylan 

(I was able to fix my issue #1 running by fixing sortable.js and sortable.min.js following this fix https://github.com/RubaXa/Sortable/issues/322.)

Ok, I was unaware of `ScriptBundles.json`. I'll try your suggestion with Serenity's bundling first and will remove the System.Web.Optimization.

**Comment by john20xdoe** [comment]
Hi, is it possible to use only a couple of bundles in a page such as login?

For example I have created a third bundle in `ScriptBundles.json` named Minimum (with the js files that are  unnecessary for login removed such as the examples you provided (cropzoom, file upload, fastclick).

Can I call the `Minimum` bundle explicitly in my Login, and skip using Site and Libs? (this is for example only). My main target is to be able to use certain script bundles selectively.

**Comment by volkanceylan** [comment]
Do you really read what i wrote
