### ISSUE TITLE
Toggle between tabs programatically

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#1432]
Basically I am trying to toggle from a tab back to the parent form.
I have a form with a couple of tabs (each are grids). When the save button is clicked inside a tab I would like to change the focus back to the main form instead of staying in the tab. I went through "Other Forms In Tab" in Basic Examples but that is using a form rather than a grid. I also have been going through the framework and scripts but have not been able to find a good approach with typescript. Any advice from any of you code wizards is appreciated. :)

**Comment by Estrusco** [comment]
There is a new example in Serene https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/OtherFormInTabOneBar that use Serenity.TabsExtensions.selectTab method

**Comment by volkanceylan** [comment]
Try with this.tabs.tabs('option', 'active', 0) or selectKeys method in that sample

**Comment by jdready5** [comment]
Thank you, I did see that example as well. I am using EntityGrid not Dialog so I am unable to access this.tabs so I am looking for a way around that if possible. Maybe I can access through getDialogOptions or a custom method using jquery I suppose.

**Comment by jdready5** [comment]
Thank you, I did see that example as well. I am using EntityGrid not Dialog so I am unable to access this.tabs so I am looking for a way around that if possible. Maybe I can access through getDialogOptions or a custom method using jquery I suppose.

**Comment by volkanceylan** [comment]
this.element.closest('.ui-tabs').tabs('option', ''active", 0)

A grid changing something about its containing dialog is pretty bad design. Grid should raise an event, dialog should attach to it, and decide what to do itself.

**Comment by jdready5** [comment]
I didn't think about that but you are correct, I need to make some design changes there. I will do that. Thank you very much for the good advice and assistance.

**Comment by jdready5** [comment]
I don't need to reopen this but I wanted to update my working code. It may be dirty but it is working as it should and currently the performance looks fine also for now. In my form if there is no VendorNum yet my Notary tab loads a grid to choose a notary (a picker). Then after save is clicked it reverts back to the original form and updates the order, also changing the Notary tab to a NotaryGrid listing the chosen Notary. I'm always open to suggestions and/or criticism but maybe this can help someone else as well.
 

    `export class NOrderDialog extends Serenity.EntityDialog<NOrderRow, any> {
        protected getFormKey() { return NOrderForm.formKey; }
        protected getIdProperty() { return NOrderRow.idProperty; }
        protected getLocalTextPrefix() { return NOrderRow.localTextPrefix; }
        protected getNameProperty() { return NOrderRow.nameProperty; }
        protected getService() { return NOrderService.baseUrl; }

        public form = new NOrderForm(this.idPrefix);

        private customerGrid: NOrderCustomerGrid;
        private notaryGrid: NOrderNotaryGrid;
        private chsnotaryGrid: ChsNotaryGrid;
        private documentsGrid: NOrderDocumentsGrid;       

        constructor() {
            super();           

            this.customerGrid = new NOrderCustomerGrid(this.byId("CustomerGrid"));
            this.notaryGrid = new NOrderNotaryGrid(this.byId("NotaryGrid"));
            this.chsnotaryGrid = new ChsNotaryGrid(this.byId("ChsNotaryGrid"));
            this.documentsGrid = new NOrderDocumentsGrid(this.byId("DocumentsGrid"));
            this.tabs.on('tabsactivate', (e, i) => {
                this.arrange();
     
            });     

            // Since both NotaryGrid and ChsNotaryGrid are in the same tab, 
            // ChsNotaryGrid will also display in the form since the tab is set in html to NotaryGrid.
            // This prevents ChsNotaryGrid from displaying within the form as well
            this.byId("ChsNotaryGrid").closest("div.tab-pane:nth-child(4)").hide();             
        }          


        protected afterLoadEntity() {
            super.afterLoadEntity();
            this.customerGrid.customerID = this.entity.CustomerId;
            this.notaryGrid.vendorNum = this.entity.VendorNum;
            this.chsnotaryGrid.vendorNum = this.entity.VendorNum;
            this.documentsGrid.orderID = this.entity.OrderId;
            this.chsnotaryGrid.parentForm = this.form;

            //toggle between the 2 Notary Grids depending on whether there is a Notary (VendorNum) already assigned or not.
            if (!this.entity.VendorNum) {

                this.notaryGrid.element.toggle(false);
                this.chsnotaryGrid.element.toggle(true);
                this.byId("ChsNotaryGrid").appendTo(this.byId("TabNotary"));
            }

            else {
                this.notaryGrid.element.toggle(true);
                this.chsnotaryGrid.element.toggle(false);
                this.byId("NotaryGrid").appendTo(this.byId("TabNotary"));
            }            
        }        `

.

    `   export class ChsNotaryGrid extends Serenity.EntityGrid<ChsNotaryRow, any> {
        protected getColumnsKey() { return 'NM.ChsNotary'; }
        protected getDialogType() { return ChsNotaryDialog; }
        protected getIdProperty() { return ChsNotaryRow.idProperty; }
        protected getLocalTextPrefix() { return ChsNotaryRow.localTextPrefix; }
        protected getService() { return ChsNotaryService.baseUrl; }

        public rowSelection: Serenity.GridRowSelectionMixin;
        public parentForm: NOrderForm;    

        constructor(container: JQuery) {
            super(container);            

        }     


        protected getButtons() {
            let buttons = [];

            buttons.push({
                ticssClass: "apply-changes-button",
                title: Q.text("Controls.EntityDialog.SaveButton"),
                hint: 'Assign Notary',
                onClick: () => {                  

                    var selectedIDs = this.rowSelection.getSelectedKeys()[0];
                    if (selectedIDs == null)
                        Q.notifyWarning("Please select a Notary first.");
                    else                       
                        Q.notifySuccess("Assigned Notary " + selectedIDs);

                    // Set selected VendorNum to NOrderDialog, access it's save button, and go back to the main tab (NOrderForm)
                    // By doing this we NOrderDialog refreshes its Retrieve method, calls afterLoadEntity again and will assign 
                    // the NotaryGrid back to the Notary tab
                    this.parentForm.VendorNum.value = +selectedIDs;
                    this.element.closest(".ui-dialog").find(".apply-changes-button").click();                    
                    this.element.closest('.ui-tabs').tabs('option', 'active', 0);
                }
            });

            return buttons;
        }         

        protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
        }

        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));
            return columns;
        }`
