### ISSUE TITLE
DataView does not exist even though it is included in the scripts

### ISSUE THREAD

**Issue by Wade227** [volkanceylan/Serenity#1433]
I am trying to use a dataview but when trying to create a new instance the reference cannot be found. I have included the script in the _LayoutHead

```
   protected createSlickGrid() {
            var grid = super.createSlickGrid();

            var dataView = new Slick.Data.DataView({ inlineFilters: true });

            return grid;
        }
```

I keep getting Slick.Data does not contain DataView

**Comment by volkanceylan** [comment]
First, you should have included its script file. And you shouldn't actually use a DataView, not sure if it is compatible with Serenity DataGrid.

**Comment by Wade227** [comment]
I'm trying to add an aggregate to the dialog but how can I do that without using a DataView?

**Comment by volkanceylan** [comment]
See grouping sample
