### ISSUE TITLE
initial value for quick filter date only doesn't work

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1435]
Hi all, 

I created a date quick filter and used the example to set initial values but it didn't work, I then tested with the example by commenting out shippingstate leaving just date and it also didn't work,

Below will still load all results and not filter on dates, only if you click into the date values and set again it will update the grid. If i add shippingstate back in then all works as expected. So it seems just date on it's own doesn't apply filter?

```
        protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            // get quick filter list from base class
            let filters = super.getQuickFilters();

            // get a reference to order row field names
            let fld = Northwind.OrderRow.Fields;

            Q.first(filters, x => x.field == fld.OrderDate).init = w => {

                (w as Serenity.DateEditor).valueAsDate = new Date(1998, 4, 1);

                let endDate = w.element.nextAll(".s-DateEditor").getWidget(Serenity.DateEditor);
                endDate.valueAsDate = new Date(1998, 6, 1);
            };

            //Q.first(filters, x => x.field == fld.ShippingState).init = w => {
            //    // enum editor has a string value, so need to call toString()
            //    (w as Serenity.EnumEditor).value = Northwind.OrderShippingState.NotShipped.toString()
            //};

            return filters;
        }
```

**Comment by iuryamicussi** [comment]
I'm having the same problem( #1421 ), furthermore I was only able to set the begin date in this filter.

**Comment by volkanceylan** [comment]
It does work on my side. Make sure you update to latest.

**Comment by csteppe** [comment]
Having the same issue , Grid is not refreshing with inital value .

> protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
> 
>             var q = Q.parseQueryString();
>             if (q.State != null && q.State.length) {
>                 if (q.State == "Open")
>                     var value = "Active"
>                 if (q.State == "Close")
>                     var value = "Inactive"
>             }
>            
>             // get quick filter list from base class
>             let filters = super.getQuickFilters();
> 
>             // get a reference to order row field names
>             let fld = CustomerProductsRow.Fields;
> 
>       
> 
>             Q.first(filters, x => x.field == fld.Status).init = w => {
>                 // enum editor has a string value, so need to call toString()
>                 (w as Serenity.EnumEditor).value = value;
>             };
> 
>             return filters;
>         }

**Comment by csteppe** [comment]
@abelal83 It seems adding a 

`this.refresh();`

in the filter works !

Complete code Below

```
Q.first(filters, x => x.field == fld.Status).init = w => {
                // enum editor has a string value, so need to call toString()
                (w as Serenity.EnumEditor).value = value.toString();
                 this.refresh();
            };
```

**Comment by abelal83** [comment]
I noticed during debugging via Chrome it also works. There must be some sort of delay before the whole thing has a chance to initialise properly. refreshing as suggested by @csteppe sorts it.

@volkanceylan  didn't get a chance to update to latest version, so perhaps that will fix it.
