### ISSUE TITLE
LookupScript help

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1437]
I have a LookupScript, which is require to send different data for different user logged into the system.
But currently it is calling preparequery once only, for first user logs in.
when other user logs in, it doesn't call preparequery function and sends same data as per previous login user.
how can we have different data for user logs into the application.
regards
Shailesh

**Comment by sayuga** [comment]
Look at the multitenancy handling of the lookup script. This should be able to give you a hint. 

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/handling_lookup_scripts.html
