### ISSUE TITLE
Permission system in 2.6.0

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1438]
## Logic Operators in Permission Keys

2.6.0 comes with a LogicOperatorPermissionService, which lets you use AND, OR operators in permission keys, e.g. ReadPermission("Northwind:General|Something:Else"). 

This means user will be able to access resource, if he has either of Northwind:General and Something:Else permissions. 

You may also use & operator if needed. It means user must have both permissions listed. & can also be mixed with |, but in that case, & will take precedence, so it will be calculated first, than OR.

This is designed for simple use cases, please don't misuse it by listing a hundred of permissions. It would be a very bad design. Instead, define a new permission key that will be shared by all those other permissions.

To be able to use this feature, you need to use LogicOperatorPermissionService in SiteInitialization.cs. Replace line below with:

```cs
registrar.RegisterInstance<IPermissionService>(new Administration.PermissionService());
```

This one:

```cs
registrar.RegisterInstance<IPermissionService>(new LogicOperatorPermissionService(
    new Administration.PermissionService()));
```

These combination permission keys shouldn't be listed in permission dialog, so we need to do a few changes in UserPermissionRepository:

Find ProcessAttributes method 
```cs
private void ProcessAttributes<TAttr>(HashSet<string> hash, 
	  MemberInfo member, Func<TAttr, string> getPermission)
	where TAttr : Attribute
{
	{
		var permission = getPermission(attr);
		if (!permission.IsEmptyOrNull())
			hash.Add(permission);
	}
}
```

and replace with this one:

```cs
private static readonly string[] emptyPermissions = new string[0];
private static readonly char[] splitChar = new char[] { '|', '&' };

private string[] SplitPermissions(string permission)
{
	if (string.IsNullOrEmpty(permission))
		return emptyPermissions;

	return permission.Split(splitChar, StringSplitOptions.RemoveEmptyEntries);
}

private void ProcessAttributes<TAttr>(HashSet<string> hash,
		MemberInfo member, Func<TAttr, string> getPermission)
	where TAttr : Attribute
{
	foreach (var attr in member.GetCustomAttributes<TAttr>())
	{
		var permission = getPermission(attr);
		hash.AddRange(SplitPermissions(permission));
	}
}
```

Also a few lines below, find:

```cs
result.Add(attr.Permission);
```

replace with:

```cs
result.AddRange(SplitPermissions(attr.Permission));
```

To show field level permissions in permission dialog add:

```cs
foreach (var type in assembly.GetTypes()) {
    // ...
    foreach (var member in type.GetProperties(BindingFlags.Instance | BindingFlags.Public))
         ProcessAttributes<PermissionAttributeBase>(result, member, x => x.Permission);
}
```

## Field Level Permissions

Another new feature, which was requested a few times, is field level permissions.

This lets you control read / insert / update permissions on field level.

Let's say we want only users with SomeSpecialPermission should be able to see ContactName field in CustomerRow:

```cs
[DisplayName("Contact Name"), Size(30), QuickSearch]
[ReadPermission("SomeSpecialPermission")]
public String ContactName
{
	get { return Fields.ContactName[this]; }
	set { Fields.ContactName[this] = value; }
}
```

Just add ReadPermission attribute, and this will hide ContactName column from rows, and forms for users who doesn't have SomeSpecialPermission.

You can also use ModifyPermission, InsertPermission, UpdatePermission, similar to row permissions, which will make field read only in relevant mode.

You may need to make a few changes, for admin to not get affected by these limitations in some special cases.

Open ScriptUserDefinition.cs and add a IsAdmin attribute:

```cs
[ScriptInclude]
public class ScriptUserDefinition
{
	public String Username { get; set; }
	public String DisplayName { get; set; }
	public Boolean IsAdmin { get; set; }
	public Dictionary<string, bool> Permissions { get; set; }
	public List<SiteRow> GrantedSites { get; set; }
}
```

And set it in GetUserData() method of UserEndpoint.cs:

```cs
[NonAction, DataScript("UserData", CacheDuration = -1)]
public ScriptUserDefinition GetUserData()
{
	//...
	result.Username = user.Username;
	result.IsAdmin = user.Username == "admin";
	//...
 }
```

**Comment by edson** [comment]
Hi, @volkanceylan .

This is a great new feature. :-) Thank you!

But It raised one issue for me... 

On previous versions, The ReadOnly attribute on form didn't affect the fields that were sent to endpoint/repository for saving/creating entity purposes.  As  I'm dealing with insurance/customers/vehicles/tickets and a third part software data... which results in 20 tables to query from... I was using the readonly enabled to not let user directly modify data in a field, but to choose from a select in a grid, values to be used from. 

My question is... is there an easy workaround to let this old behaviour from fields set to ReadOnly in form, be sent to Endpoint/Repository?  I can look for an alternative to set the readonly property... but I thought I could ask first...

Thanks for your patient!

Bye!

**Comment by volkanceylan** [comment]
It should be fixed in 2.6.1. Yes readonly fields was still sent to server side, as you might be filling them by doing some calculation on other fields. It was a bug introduced in 2.6.0.

**Comment by edson** [comment]
Thanks @volkanceylan . It is fixed.

Best Regards

**Comment by wldkrd1** [comment]
What's the difference between ModifyPermission and UpdatePermision?

**Comment by edson** [comment]
Basicly.. ModifyPermission includes Insert and UpdatePermission

There's a wiki if you want to separate that.
https://github.com/volkanceylan/Serenity/wiki/Frequently-Asked-Questions

Best Regards

**Comment by ramveersgh** [comment]
This is a nice feature and save a lot of effort for field level permission which we were doing earlier.

But this did not add permission in User Permission Dialog. I have to do it manually to show.
Is it possible to add this permission in User Permission Dialog automatically as it happens for Row class permission?
![filedpermission](https://cloud.githubusercontent.com/assets/2145218/20453963/78780f1e-ae5a-11e6-9e6e-09cdfbb38172.png)

**Comment by volkanceylan** [comment]
Yep it's possible, probably missed that detail, will later.

**Comment by volkanceylan** [comment]
I've updated comment for showing field level permissions.

**Comment by ramveersgh** [comment]
Thanks! It working fine after following updated comment.

**Comment by marcobisio** [comment]
Great job @volkanceylan...once again thanks for all your time and support!

**Comment by williamhodges** [comment]
So just for clarification, we still need to add the PermissionKeys in a file like `PermissionKeys.cs` and then parse it over to the json file right? That part is still the same?

**Comment by volkanceylan** [comment]
Yes it is same

**Comment by williamhodges** [comment]
Found a potential issue with this. When using this in my RegistryRow.cs, I'm attempting to set the permissions using the PermissionKeys.cs. I'm presented with the following error:

![1438](https://cloud.githubusercontent.com/assets/11448029/20956520/75948bbc-bc18-11e6-8386-e1cfecccd4d4.png)

Is there a way around this?

**Comment by volkanceylan** [comment]
Its string addition not boolean or

**Comment by williamhodges** [comment]
I realized that after the fact and changed it to `PermissionsKeys.Access + "|" + PermissionsKeys.NewHireFlag` and it's working perfect. Thanks again for the new addition.
