### ISSUE TITLE
[HowTo] Bootstrap Switch plugin

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1439]
Dear all,
in this simple guide I'll explain how to add and use the Bootstrap Switch plugin (http://www.bootstrap-switch.org).

![image](https://cloud.githubusercontent.com/assets/17425690/20247159/78f2df4e-a9c5-11e6-9f26-66436a88ae68.png)

Here we go:

**1)** install the following nuget packages https://www.nuget.org/packages/Bootstrap.Switch/3.3.2.1 (library) and https://www.nuget.org/packages/bootstrap-switch.TypeScript.DefinitelyTyped/0.6.4 (typescript type)

**2)** add the following lines in your _LayoutHead.cshtml:

`@Html.Stylesheet("~/Content/bootstrap-switch/bootstrap3/bootstrap-switch.css")`

`@Html.Script("~/Scripts/bootstrap-switch.js")`

**3)** create the bootstrap switch widget:

    namespace MyProject {
        @Serenity.Decorators.element("<input/>")
        @Serenity.Decorators.registerClass([Serenity.IGetEditValue, Serenity.ISetEditValue])
        export class BSSwitchEditor
            extends Serenity.Widget<BootstrapSwitchOptions>
            implements Serenity.IGetEditValue, Serenity.ISetEditValue {
    
            constructor(element: JQuery, opt: BootstrapSwitchOptions) {
                super(element, opt);
    
                this.options.size = "mini";
                element.attr('type', 'checkbox').bootstrapSwitch(this.options);
            }
    
            public setEditValue(source: any, property: Serenity.PropertyItem): void {
                this.element.bootstrapSwitch('state', source[property.name]);
            }
    
            public getEditValue(property: Serenity.PropertyItem, target: any): void {
                target[property.name] = this.element.bootstrapSwitch('state');
            }
        }
        export interface BootstrapSwitchOptions {
            state?: boolean;
            size?: string;
            animate?: boolean;
            disabled?: boolean;
            readonly?: boolean;
            indeterminate?: boolean;
            invers?: boolean;
            radioAllOff?: boolean;
            onColor?: string;
            offColor?: string;
            onText?: string;
            offText?: string;
            labelText?: string;
            handleWidth?: string;
            labelWidth?: string;
            baseClass?: string;
            wrapperClass?: string;
            onInit?: any;
            onSwitchChange?: any;
        }
    }

4) just use in your row (Northwind Product here):

    [DisplayName("Discontinued"), NotNull]
    [BSSwitchEditor(OnText = "Yes", OffText = "No")]
    public Boolean? Discontinued
    {
        get { return Fields.Discontinued[this]; }
        set { Fields.Discontinued[this] = value; }
    }

Hope it helps...
That's all folks!
Bye

Edit: still something to adjust if the field is required...I let you know

**Comment by volkanceylan** [comment]
Another nice one @marcobisio , thanks for sharing

One question, do you need to declare BootstrapSwitchOptions if you are already using its .ts.d file?

**Comment by marcobisio** [comment]
Thanks @volkanceylan!
First try was with the original BootstrapSwitch.BootstrapSwitchOptions, but I got some errors in T4 transformation, so I've declared a new one...

**Comment by volkanceylan** [comment]
Hmm, ok probably generator can't handle code in another namespace

**Comment by marcobisio** [comment]
Uhm if the fields is required I can only set to "Yes" otherwise the validation fails...any idea?

**Comment by marcobisio** [comment]
Ok ugly trick incoming...

    public setEditValue(source: any, property: Serenity.PropertyItem): void {
            if (this.element.hasClass('required')) this.element.removeClass('required');
            this.element.bootstrapSwitch('state', source[property.name]);
    }

because I think that required here it's just to show the red asterisk...

Also adjusted this:

    @Serenity.Decorators.element('<input type="checkbox"/>')

Bye

**Comment by marcobisio** [comment]
I was wondering how to implement the readonly behaviour on such plugin...
In order to do that we need this in Widgets.ts (Serenity):

    class IReadOnly{
    }

or I'm out of the way?
Because for ISetEditValue and IGetEditValue we already have both the interface and the class...
I was playing with the methods:

    get_readOnly(): boolean;
    set_readOnly(value: boolean): void;

but I think that the Serenity.IReadOnly class should be added to the registerClass instruction....

Thanks

**Comment by Estrusco** [comment]
Thank you very much @marcobisio !

**Comment by alex-444** [comment]
Thank you @marcobisio !
I have a problem when i emplement the` [QuickFilter]` in MyColumn it does not work when i tried to filter
and always default to 'No' value. I think i'm missing something in my code. 
```

[DisplayName("IsActive"), Column("IsActive"), NotNull]
        [BSSwitchEditor(OnText = "Yes", OffText ="No")]
        public Boolean? IsActive
        {
            get { return Fields.IsActive[this]; }
            set { Fields.IsActive[this] = value; }
        }
```

**Comment by marcobisio** [comment]
Hi @alex-444, I suggest to use this control only in forms and keep the original serenity filters: in order to do that just move the [BSSwitchEditor] from your xyzRow to your xyzForm (same field ofc!).

Bye

**Comment by volkanceylan** [comment]
That interface problem is caused by TS and Saltaralle type system mismatch.

**Comment by marcobisio** [comment]
I was wondering how to implement the readonly behaviour on such plugin...
In order to do that we need this in Widgets.ts (Serenity):

class IReadOnly{
}
or I'm out of the way?
Because for ISetEditValue and IGetEditValue we already have both the interface and the class...
I was playing with the methods:

get_readOnly(): boolean;
set_readOnly(value: boolean): void;
but I think that the Serenity.IReadOnly class should be added to the registerClass instruction....

Thanks

**Comment by alex-444** [comment]
I see that why its not working only in forms.
thanks @marcobisio  & @volkanceylan !

**Comment by Estrusco** [comment]
@marcobisio  I added this in Wiki 

https://github.com/volkanceylan/Serenity/wiki/Bootstrap-Switch-plugin

By

**Comment by marcobisio** [comment]
Thank you very much @Estrusco !
I hope in a @volkanceylan feedback for the readonly question in order to complete the sample!

**Comment by mkoval-ua** [comment]
Yes, I would also like to know why there is no class Serenity.IReadOnly.
@volkanceylan could you please advise on that matter?

**Comment by williamhodges** [comment]
I tried to set the OnColor to green and the OffColor to red, however it didn't take. Any ideas?

**Comment by c9482** [comment]
Followed the instructions to set this up but getting the following errors:

![image](https://user-images.githubusercontent.com/17013052/44554457-ab3f0600-a6f6-11e8-90a9-0f7e291a72be.png)

**Comment by brunobola** [comment]
@marcobisio awesome work, how to handle the changed value in dialog.ts to make same form of calculation on the fly ?
