### ISSUE TITLE
Uncaught Cannot cast object to type String

### ISSUE THREAD

**Issue by pollpaul** [volkanceylan/Serenity#144]
Hi Volkanceylan,
I am getting the error "Uncaught Cannot cast object to type String" when I try to edit a row I have just submitted. The error involves mscorlib.js at line 597. "throw new ss_InvalidCastException('Cannot cast object to type ' + ss.getTypeFullName(type)); "

What would be the work around to this?

**Comment by volkanceylan** [comment]
Please update to 1.9.5. 1.9.3 had such an issue

**Comment by pollpaul** [comment]
Alright, thank you for timely reply.
