### ISSUE TITLE
Not an issue, just a question...

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1440]
Hi  Volkan!

Since I have not been able to visualize the example of multitenancy, I would like to ask you the following question

Is it possible to develop a pyramidal application in Serene? I'm talking about the type of management system that Herbalife has.
Where users on the same level, are associated with other users and can view and share their information, but only in their group membership.

Can you point me in the right direction?

Thanks a lot..It's amazing the template you created

**Comment by volkanceylan** [comment]
Any type of application can be done with Serenity or platform X, but you design it or if can't consider  getting some professional help.

**Comment by javaman63** [comment]
Thanx for the inside!

regards!
