### ISSUE TITLE
Can help me 

### ISSUE THREAD

**Issue by Takecarecom** [volkanceylan/Serenity#1441]
When user change dropdown  productcode  can load quality in another table.it possible ?
 
![stock](https://cloud.githubusercontent.com/assets/13514630/20255217/62b3c98e-aa6d-11e6-9b63-124ebc5d45d6.png)

**Comment by adhikamafran** [comment]
use productcode.ChangeSelect2 handler that load Qty.

**Comment by volkanceylan** [comment]
There is a sample under dialogs like this.

**Comment by Takecarecom** [comment]
@volkanceylan 
Q.first() -- > Summary Qty In Order Detail Group by ProductID ?
