### ISSUE TITLE
Chrome on mac slick grid rows disappears

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1444]
Chrome on Mac: after almost any refresh of slick grid (sorting, save and close etc..) the rows disappears till we refresh page.

Did anyone else encountered this?

**Comment by volkanceylan** [comment]
Nope, might be some formatter issue or malformed html

**Comment by in32bit** [comment]
Here is a video.

[1846.zip](https://github.com/volkanceylan/Serenity/files/591769/1846.zip)

**Comment by volkanceylan** [comment]
Well, i don't have a MAC, i can't debug, and if it looks like a bug with Mac Chrome,

**Comment by smartnip** [comment]
Hi.
i have the same problem. Someone fixed this problem already? Only MAC browser got this error.
