### ISSUE TITLE
ListField and RowField

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1445]
Hi @volkanceylan !

Can you explain me please, how ListField and RowField works, in which cases are to be used, and what type of editor can be assigned to these type of fields in the form class?

I do not understand these types of fields

**Comment by volkanceylan** [comment]
You are already using them with MasterDetailRelation and LinkingSetRelation

**Comment by Estrusco** [comment]
Oh right, therefore these types are used in those cases. Thank you

**Comment by volkanceylan** [comment]
They are simple non-mapped fields with List of row / any object. As a plus they implement list comparison, by comparing counts, then invidual items etc. Not very special.
