### ISSUE TITLE
Change quick filter default behaviour

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1446]
Hi all, 

I have a couple of quick filters using lookup scripts that work well. I've been recently asked if I can change one integer filter to query using less than. the default behavior from what I can see is it will do an equal to.

I've gone through the code and tried to work out where this is but I can't work this out. Any suggestions? Even tried stored procedure example that contains the date filter but not really able to understand it.

thanks in advance!

**Comment by volkanceylan** [comment]
Search for handler argument to quick filter in code. There are samples that moves filter into criteria parameter.

**Comment by volkanceylan** [comment]
I wonder how couldn't understand that sample with so many comments. Anyway, let's make it fall into your laps:

http://serenity.is/demo/BasicSamples/QuickFilterCustomization

**Comment by abelal83** [comment]
Thanks as always for your excellent help Volkan (and of course your witty remarks!). 

I know some of questions from us can be testing but the rest of the community who are learning typescript will be just as grateful as me. Thank you 😁
