### ISSUE TITLE
QR and Code 128 Generator

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1447]
I'm in the need of using qr and code 128 generation but before bringing in a libray I wanted to make sure that you didn't have anything already in place. I don't see anything at the moment though. 

I was planning on bringing in: http://barcoderender.codeplex.com/

Any thoughts on the matter are welcome

**Comment by volkanceylan** [comment]
I had good experience with zxing

**Comment by volkanceylan** [comment]
Jquery.qrcode and qrcode.js is also fine for client side

**Comment by sayuga** [comment]
Thanks for the info. I'll do some reading up on zxing before delving in then.
