### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by SpiraMira** [volkanceylan/Serenity#1448]
@volkanceylan 

First of all, great project....I plan on contributing (both in $ and time)

- Simple one first...What theme or template did you use for the login page of your demo site? I like its flash...Is it available as open source? Especially if it's integrated with the actual underlying app.

- Do you have a roadmap? Just wondering if Angular2 support (which I here is now Typescript) is in your sights. What about .net core for its cross-platform capabilities?

- How do you recommend I keep up with the updates to both the template and the core project? Do you have a recommended setup/workflow? For example, I'm currently thinking the best way is to git fork both core Serenity and Template instead of downloading the VS extension.  Your thoughts please.

- Any developer guides available to swap out the current ADMIN LTE theme for something like Inspinia or Metronic?

Thanks in advance, keep up the great work!

Patrice

**Comment by volkanceylan** [comment]
Login page is Vegas, inspired by some users wiki entry. See that for info. Everything we use is open source.

I'm not a fan of Angular at all, so definitely no.

.Net core suppport is planned after Microsoft decides what it actually is, hopefully after .Net standard 2.

You can watch ChangeLog. You may add Serenity as submodule if you need to debug etc.

No there is no guide, with some basic Css knowledge you can.

Dont worry about donating. Offered that option based on some users requests, but so far we got 0.

**Comment by SpiraMira** [comment]
Cool. Thanks for the quick reply.

Your points all make sense.

I'm methodically going through your developer guide and so far so good. Very impressed with how all of this is stitched together. Lovely! 

To start contributing I plan on documenting all of the little missing quirks and discrepancies in your guide and tutorial. I totally understand that maintaining this is a bitch, but the tutorial, guides and docs are but one of the many strengths of your solution. Hope it will help.  

Also, not that you don't have much to do already, but a mini CRM or ERP sample app would truly be the icing on the cake. Dunno if this is in your pipeline (maybe others have contributed solutions?)

Later

**Comment by SpiraMira** [comment]
Last thing - do you accept push requests for your docs and guides?

**Comment by VictorTomaili** [comment]
@SpiraMira all contribution is accepted. You can translate exist docs or add missed parts or something else.
