### ISSUE TITLE
	Operator '==' is ambiguous on operands of type 'Field' and '<null>'

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#1449]
I want to write some thing like this below:
```
using Serenity.Data;
Field f = null;
......
if (f == null)
{
}
```
and I get error:<strong>	Operator '==' is ambiguous on operands of type 'Field' and '&lt;null&gt;'</strong>,
Is there a simple way to check if a "Field" object is null without try catch?

**Comment by volkanceylan** [comment]
ReferenceEquals(null, field)

**Comment by tky753** [comment]
Thanks.
