### ISSUE TITLE
How to add single edit page without list page

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#145]
Sure this is not much with serenity, I just want to learn something from you ; I have a requirement like this,I want tenant to edit his  own tenant  info page,can you give me some suggestion? And when  the info is so large that I don't want show all info in one edit page ,I want to have a two level nevagtor menu just like Tenant info (Parent)--> business licence(child),when I click business licence url ,I can edit the business licence page without a list page

**Comment by volkanceylan** [comment]
You can take Change Password page as sample for this. Subpages can be bootstrap tabs.

**Comment by ChenZhaobin** [comment]
Thanks very much,I will follow the  Change Password page

**Comment by ChenZhaobin** [comment]
Is the 'Change Password page' generated by sergen  console command? I write all the code related with SelfTenant Edit Page following  the 'Change Password codes' except for the folder of Imports. Imports folder codes are generated using T4,Could you give a suggestion  no better than an example  about the steps of create a self tenant info edit page ?

**Comment by volkanceylan** [comment]
It's not generated, it's manually written. Taking files in ChangePassword folder, ChangePasswordForm etc, and on script side ChangePasswordPanel as sample, should be enough. Btw, if it is still too complex for you, you can always make another standart MVC page for this part. Some other person also asked this, and took ChangePassword as sample, maybe he shares.

**Comment by ChenZhaobin** [comment]
I make another standart MVC page  follow ThemeSample Pages ,and the result is successful!Now I can use this framework to add Authorization and content manage function,Other functions I can do just as  standart MVC! Thank you!
