### ISSUE TITLE
Not an issue : TryLast is available?

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1450]
Dear Volkan,
currently i can get first record which satisifies where condition by using connection.tryfirst<>,
Do we have anything for Last record which satifies the condition, instead of getting list and selecting the last one.
regards
Shailesh

**Comment by volkanceylan** [comment]
Order by descending, and take first one

**Comment by shaileshbc** [comment]
Do you mean i have to do like
connection.list<>( condition ).OrderByDescending(fieldname).First()  ?
regards
shailesh

**Comment by edson** [comment]
See https://volkanceylan.gitbooks.io/serenity-guide/content/fluent_sql/sqlquery_object.html

something like:
Connection.TryFirst<XYZRow>(q => q
                            .Select(s.somefield)
                            .Where(xxxx)
                            .OrderBy(s.somefield, desc: true));
