### ISSUE TITLE
Study guide

### ISSUE THREAD

**Issue by AlbertoAr** [volkanceylan/Serenity#1452]
Hi Volkan

I've 2 questions??

I used to develop desktop applications, but now i need to develop an aplication for web, I started using visual studio (completely different from the basic i learned :) ) and I found Serenity, it's great!!!!  but I find out the need to study to understand the application. What topics do you suggest to study??

I had develop a static web page to show some information about the company, what is the best way to integrate the serenity application with that part??? how can i call the login page in serenity???

Thank you very much for your support

**Comment by volkanceylan** [comment]
Please read the guide, at least tutorials. And i think you should also read some about ASP.NET MVC in general.

**Comment by AlbertoAr** [comment]
Thank you
