### ISSUE TITLE
Please expose TSCPath in sergen's GeneratorConfig form

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1456]
Alternatively, update sergen to reference the Microsoft.TypeScript.Compiler nuget package. One less external item for developers to keep track of.

Thanks!

**Comment by volkanceylan** [comment]
It should find it in default location, what problem you had?

**Comment by wldkrd1** [comment]
Sergen requires TypeScript 2.0+, but our environment relies on TS 1.8 so I can't upgrade yet. Since you're version-dependent, it would make the most sense to handle the dependency via nuget but since you also have the TSCPath in the configuration options, might consider exposing that in the UI.

**Comment by volkanceylan** [comment]
TypeScript 2.0 is backwards compatible with 1.8. I didn't notice any problems with either. Sergen uses whatever latest version under program files.
