### ISSUE TITLE
RSVP is undefined

### ISSUE THREAD

**Issue by DavidHallEP** [volkanceylan/Serenity#1457]
Hi After upgrading the latest packages, i am unable to run my website and getting the error;
'RSVP' is undefined.

are you able to assist as to why this is happening? have attached screen shot and package version
![2016-11-17 14_19_12-spc - microsoft visual studio](https://cloud.githubusercontent.com/assets/20979887/20375098/fdc1bf3e-acd0-11e6-8bc4-3be06e59667f.png)
![2016-11-17 14_19_41-](https://cloud.githubusercontent.com/assets/20979887/20375099/fdc39ac0-acd0-11e6-85b1-4cf9ba4d6fbe.png)

**Comment by volkanceylan** [comment]
You don't have rsvp.js or have another error.

**Comment by volkanceylan** [comment]
Can you show Chrome console details

**Comment by DavidHallEP** [comment]
here it is, certainly loads of errors! all was fine prior to the update. and from what i can see the files are there bu tthey are not being loaded correctly?
![2016-11-18 08_09_05_2](https://cloud.githubusercontent.com/assets/20979887/20407829/1079c900-ad67-11e6-86b0-dfaddef240cd.png)

![2016-11-18 08_09_05](https://cloud.githubusercontent.com/assets/20979887/20407664/700a9562-ad66-11e6-8010-b7e924d4b1e6.png)

**Comment by volkanceylan** [comment]
Looks like you have a great deal of configuration errors. Check file permissions etc.

**Comment by innominate227** [comment]
I also got this error. I just updated all nuget packages on a new project created from the Serene template.
Solution was to remove and reinstall Serenity.Web and Serenity.Web.Assets.
