### ISSUE TITLE
Upload file in detail table

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#1458]
I used below code in Form.cs, but the file was uploaded in the default folder "Temporary", if i move this code to Rows.cs, it was error when master table save.How can i custorm the upload path in MasterDetailRelation model
[FileUploadEditor(AllowNonImage = true, CopyToHistory = true, DisableDefaultBehavior = true, FilenameFormat = "TestProgram/{0}/{0}_ECN_{2}", MaxSize = 10485760), FileDownloadFormatter]

![default](https://cloud.githubusercontent.com/assets/19610257/20375185/71930328-acb8-11e6-8cc0-5c4b87893ce0.PNG)

**Comment by volkanceylan** [comment]
Why are you disabling default behavior. Files are uploaded in temporary folder than moved.

**Comment by cp1319421** [comment]
it's in wrong path when i enable default behaivor
