### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1459]
Is it possible to create a dialog with more than two columns?

**Comment by jdready5** [comment]
There is an example in basic samples under multi column dialog if that's what you mean..

**Comment by mcb2323** [comment]
Thanks I looked at the example but it looks like it only supports 2 columns.  How do I arrange my fields into say 3 or 4 columns instead of 2

**Comment by volkanceylan** [comment]
Try maths
