### ISSUE TITLE
Toastr question

### ISSUE THREAD

**Issue by stickybro** [volkanceylan/Serenity#146]
Hi JaiQ, (or anyone else that knows)

sorry I know this is not a toastr helpline :8ball: 
I was wondering if its already been done where a toastr message shows the progress through a batch of server updates - something that shows the user that "row x of y updates have been performed" or similar... for example in your latest ProductGrid with editable UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel, imagine you edit 30 rows and the server takes 20 seconds (long distance over dial-up :P ) to do the updates.... it would be useful to show the user whats happening... and could be reused across the site.

I have spent a while looking on the toastr hub and can't find anything useful yet so thought I'd ask here... thanks if you can help!

s. :checkered_flag:

**Comment by volkanceylan** [comment]
I'd call services for each item one by one, update progress, call for next one. This is not something about toastr actually.

**Comment by volkanceylan** [comment]
Something like this

```cs
            var enumerator = Q.DeepClone(pendingChanges).GetEnumerator();
            int done = 0;
            int total = pendingChanges.Count;

            Action saveNext = null;
            saveNext = delegate ()
            {
                if (!enumerator.MoveNext())
                {
                    Refresh();
                    return;
                }

                var pair = enumerator.Current;
                var entity = Q.DeepClone(pair.Value);
                entity.ProductID = pair.Key;
                ProductService.Update(new SaveRequest<ProductRow>
                {
                    EntityId = pair.Key,
                    Entity = entity
                }, response => {
                    pendingChanges.Remove(pair.Key);
                    Q.NotifyInfo((++done) + " / " + total + " is done...");
                    saveNext();
                });
            };
```

Though a progress dialog would be better, but that's for another lesson ;)

**Comment by stickybro** [comment]
Thanks JaiQ :+1: 

That does notify as requested but like you say a progress dialog would be better :) I will try that next!

s
