### ISSUE TITLE
How to use one transaction for changes on multiple entities

### ISSUE THREAD

**Issue by allema** [volkanceylan/Serenity#1460]
I'm trying to figure out the best way to bundle changes on multiple entities into one transaction. 

Example: A user creates a new Customer. This should begin a transaction on SQL server and save the customer (transaction still open). Then the user creates an Order which will be saved in the same transaction.

When the user is done editing everything, he clicks Commit to end the transaction (save Customer and Order) or Discard to rollback (Customer and Order won't be saved).

Any hints on how to implement this scenario?

**Comment by volkanceylan** [comment]
Order and details are already saved in one transaction

**Comment by allema** [comment]
Thanks, what about a controllable way to bundle multiple changes? Goal is that users can edit multiple non-linked entities, do some reports and if they're happy with the results commit the changes, otherwise discard them.
Other advantages are that before the commit, other users won't see the changes and we can use SQL to perform additional validation at commit.

**Comment by volkanceylan** [comment]
If you are thinking about keeping transaction open server side, my answer would be a big no. I wouldn't even try this in a web environment. Also there is no gurantee that user will land in same transaction in next request. In some desktop application keeping transaction open could be possible, but still not recommended certainly. So you have to think web way, and design your application in the web way. That is request / response. If user wants to cancel something, just delete customer and related records.

**Comment by volkanceylan** [comment]
If you worry about other users seeing changes, then add a approved, in progress etc. field, and filter records.

**Comment by allema** [comment]
I feared we'd have to do it that way. Thanks again!
