### ISSUE TITLE
Get LookupEditor text value

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1461]
Dear guys,
I feel a bit dumb but...there is an easy to way to get the text value of currently selected item of a LookupEditor?
I know that for the value there is the helper Serenity.EditorUtils.getValue, but how to get the textual value?
Moreover, the LookupEditor it's in a toolbar and not in a form, so I cannot use this:

    this.form.w('myfield','Serenity.LookupEditor').get_text()

Thanks for your feedbacks

**Comment by marcobisio** [comment]
I forgot...I'm using this at the moment:

    this.toolbar.element.find(".s-MyEditor").find(".select2-chosen").text()

but I feel that isn't the right approach...

Thanks

**Comment by edson** [comment]
Hi, @marcobisio .
Maybe...
`this.toolbar.element.find(".s-MyEditor").getWidget(Serenity.LookupEditor).get_text();`

Well...Maybe someone else has a better approach...

Best Regards

**Comment by volkanceylan** [comment]
this.form.MyEditor.get_text()

**Comment by marcobisio** [comment]
Thanks you very much @edson!

@volkanceylan: thanks, but my lookupeditor it's in the toolbar and not in the form...
