### ISSUE TITLE
How to show a quick filter allowing multiple selections  in a form

### ISSUE THREAD

**Issue by okowiro** [volkanceylan/Serenity#1462]
How to show a quick filter allowing multiple selections in a form. I am new to Serenity

**Comment by sayuga** [comment]
Look at the customers table in the northwind sample. Specifically, look at how the Representatives are matched.

**Comment by okowiro** [comment]
Please see attached screenshot. Instead of TExtboxes i want to create multi select dropdown list.

<img width="1033" alt="screen shot 2016-11-17 at 5 38 01 pm" src="https://cloud.githubusercontent.com/assets/22594794/20412536/f1f7469e-acec-11e6-841c-afaddee26b6c.png">

**Comment by Estrusco** [comment]
As has been mentioned sayuga, see 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerRow.cs

You have to use same behavior of field Representatives and use attribute     [LookupEditor(typeof(EmployeeRow), Multiple = true)] and  [LinkingSetRelation]

```cs
    [LookupEditor(typeof(EmployeeRow), Multiple = true), NotMapped]
    [LinkingSetRelation(typeof(CustomerRepresentativesRow), "CustomerId", "EmployeeId")]
    [MinSelectLevel(SelectLevel.Details)]
    public List<Int32> Representatives
    {
         get { return Fields.Representatives[this]; }
         set { Fields.Representatives[this] = value; }
    }
```

![cattura](https://cloud.githubusercontent.com/assets/16304015/20422566/779dcbbe-ad6b-11e6-9b41-c251a03ce1d0.PNG)

**Comment by okowiro** [comment]
Awesome thanks its working.

**Comment by gfo2007** [comment]
@okowiro please how did you handle the saving of the multiple ids in code

**Comment by sayuga** [comment]
The saving of the multiple Id's is because it is matching through the linking set relationship. Just look through the CustomerRow code under the representative field. If you pay it close attention it's actually fairly obvious. Hint: the field is a type "List"
