### ISSUE TITLE
Did the Q&A section at the Visual Studio Gallery disappear?

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1463]
(Apologies for posting this here but I don't know how else to get in touch with the community at the moment..)

I've bookmarked and been reading the Q&A section for Serenity at https://visualstudiogallery.msdn.microsoft.com/559ec6fc-feef-4077-b6d5-5a99408a6681/view/Discussions and have posted a few questions there myself.  I now can't find the Q&A section; is anyone else having the same problem?

**Comment by DucThanhNguyen** [comment]
Yes, the Q&A section disappeared. Not sure why but you can still read Q&A in Serene basic samples
http://serenity.is/demo/BasicSamples/VSGalleryQA

**Comment by volkanceylan** [comment]
It's not specific to Serenity, they changed site and you can't now reply even to reviews, no way to Q&A, and many other things are broken.

**Comment by lquantz** [comment]
What a mess Microsoft created.  I'll try posting a question on the Visual Studio forums but if anyone knows a better way to get in touch with Microsoft about it, let me know.  How they could remove the Q&A section for all extensions (as Volkan said, it's not just Serenity) is inexplicable-- I hope it's temporary and part of a migration they're doing.

**Comment by lquantz** [comment]
It's confirmed that Microsoft, in fact, removed the Q&A section when they made the migrations to the new 'marketplace'.  

https://social.msdn.microsoft.com/Forums/vstudio/en-US/5ef8ea56-23a7-4377-8946-c6af67233484/looking-for-the-visual-studio-gallery-qa-sections-did-they-disappear?forum=visualstudiogeneral

There is a 'user voice' feature mentioned in the post to re-enable the feature, by all means feel free to vote and spread the word to the Serenity community to add their weight if you like.

**Comment by rolembergfilho** [comment]
Hey Volkan,

is there a way to save all threads in Q&A section and save it in other place (e.g. in http://serenity.is/ site?)

If you nedd an account with free MySql database, I can give you one of mine, that shared in GoDaddy.

It'll be a sad idea lost all these Knowledge Database. It's a brief history of Serenity's Life !

**Comment by volkanceylan** [comment]
Don't worry @rolembergfilho, you have all threads in VSGalleryQAThreads.v1.json file under your App_Data folder. We also have a cached / compressed copy in GitHub, which i recently updated. It loads from file in GitHub if you lose that JSON file.

**Comment by stixoffire** [comment]
@volkanceylan When the application attempts to download the file : I am getting an exception on this method   the host is disconnected- timeout - the path here is wrong and has been replaced with my site by the project builder. It is not in my App_Data folder and I have searched my drive
 ```
DownloadData("https://github.com/volkanceylan/Tutorials/raw/master/Tutorials/Tutorials.Web/" +
                    "Modules/BasicSamples/Grids/VSGalleryQA/VSGalleryQAThreads.v1.deflate");
```

**Comment by volkanceylan** [comment]
Read it from Serenity.is, or replace Tutorials with Serene
