### ISSUE TITLE
How to setup with .Net Core

### ISSUE THREAD

**Issue by reybatacjr** [volkanceylan/Serenity#1464]
Greetings,

My first Serenity project was assigned to different team and now I'm with Linux team. My question is, is there's a way we can use Serenity with VSCode running in Linux with .NetCore

Thanks

**Comment by volkanceylan** [comment]
.NET core is not supported yet

**Comment by rsbatacjr** [comment]
Thanks for your reply. I will explore .net core and see its capability and see if I can help porting serenity to it.
