### ISSUE TITLE
Impove localization features

### ISSUE THREAD

**Issue by DucThanhNguyen** [volkanceylan/Serenity#1465]
**1. Diacritic displaying**
Some diacritics in Vietnamese have been displayed not very clearly with the Open Sans font included in Serene. I tried to use Open Sans by Google webfont then it was much better.

Original font:
![serene_vietnamse_originalfont](https://cloud.githubusercontent.com/assets/22109882/20421239/4481f3ac-ad95-11e6-9414-dba0aee2d929.PNG)

```
@*@Html.Stylesheet("~/Content/font-open-sans.css")*@
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=vietnamese" rel="stylesheet">
```

![serene_vietnamse_googlefont](https://cloud.githubusercontent.com/assets/22109882/20421252/4e4be23a-ad95-11e6-942a-c3988b43a9b2.PNG)

**2. Searching without diacritics**
This feature works well in Lookup Editor or in Column Picker dialog as diacritics has been removed before searching.
But the quick search feature in entity grid doesn't work the same way. I know it's a searching query to SQL so we can't do the samething like in Lookup Editor (client searching) or in Column Picker dialog (searching in C# code). But can we use collation _CI_AI so that SQL Server ignore diacritics in 'like' command as well?
This feature is very important in Vietnamese software as user don't want (or sometimes can't) type diacritics for searching.

**3. Local text key fallback**
In many entities I have some similar fields like Code, Name, DisplayOrder, IsActive... and I don't want to translate all those texts. And with one entity, Employee for example , i have to translate these resource strings: DB.HR.Employee, DB.HR.Employee.EntitySingular, DB.HR.Employee.EntityPlural, xxx.EmployeeId... while they are the same in Vietnamese.
So if we have some fallback for local text key, it'll save time and may be improve the performance as well (as we have less resource strings with shorter keys). For example:
 - if "DB.HR.Employee.EntitySingular" can't be found, then it looks up for "DB.HR.Employee"
 - if "DB.CRM.Task.EmployeeId" can't be found, then it looks up for "Employee"
 - if "DB.HR.Employee.Name" can't be found, then it looks up for "Name"
...
Then developer can put some common text in site.texts.xxx for using in all modules.
I've implemented (3), if you agree with that, it'll create a pull request

**Comment by volkanceylan** [comment]
1. I don't want to use internet versions of fonts by default, this would be not ok for intranet apps. If font is somehow updated, we might update it from there and take a new local copy, but not a culture specific one. You are free to use any you like in your own apps though.

2. Entity grid uses the collation in your column. If you use X_CI_AI in your SQL column, it will use that. So you better change collation in database. It's also much better performance wise. We have similar requirement in Turkish_CI_AI etc and I can't imagine why would you want to use different collation for search, but if really need, that would require another attribute e.g. SearchCollationAttribute etc.

3. I would create a base class for 3, especially for shared fields. Anyway i understand there can be cases where it wouldn't solve all. I would implement that as a fake service wrapping ILocalTextRegistry, e.g.

```
Dependency.Register<ILocalTextRegistry>(new MySuperFallbackRegistry(Dependency.Resolve<ILocalTextRegistry>()));
```

I'd be happy with a pull request containing such a class, similar to LogicOperatorPermissionService.

**Comment by volkanceylan** [comment]
Btw, as a side note, i think you are putting english texts on your texts. I would use Vietnamese texts on my rows, as for you Vietnamese is primary language. That way you would do translations for English texts.

Invariant language is language neutral to your application, e.g. default, its not English

**Comment by DucThanhNguyen** [comment]
1. I also don't want to use Internet version. I was just wondering why some Vietnamese diacritics looked like they are missing and not comfortable for reading. I thought that the local font hadn't Vietnamese subset and hoped that it would be included as most Vietnamese are Latin Extended, few characters are culture specific. OK I'll download and use my own fonts.
2. I didn't notice that we can change collation for columns in SQL Server. I changed the database collation to _CI_AI but all nvarchar columns remained old collation _CI_AS, so the quick search didn't work, then I thought about adding collation to the query... It works OK now
3. Base class is a good idea for shared fields. I added code to the TryGet method of LocalTextRegistry class directly. I'll look at LogicOperatorPermissionService to see how to implement a fake service

**Comment by DucThanhNguyen** [comment]
I understand you point on primary language. Our products must support both Vietnamese and English, and all tables and fields are in English, so the generated rows have English with quite good quality. So I don't want to modify display name in all rows to Vietnamese and then translate them back to English

**Comment by volkanceylan** [comment]
Thanks for your pull request, a wiki entry later would be useful i think.

**Comment by DucThanhNguyen** [comment]
Dear @volkanceylan , I tried to use FallbackLocalTextRegistry for a sample in Serene and write a wiki. 

However, it didn't work because:
1. The TryGet method of LocalTextRegistry never return a null string as it search in language fallbacks or default language.
2. The ILocalTextRegistry was casted to LocalTextRegistry serveral times in the code so it caused exceptions

I also tried to fix above issues by:
1. Adding parameter bool searchInFallbacks = true to TryGet method
2. Adding all methods to be called of LocalTextRegistry to ILocalTextRegistry, implementing them on FallbackLocalTextRegistry. Then I  removed all casting so I could register FallbackLocalTextRegistry instead of LocalTextRegistry.
then I could built and run the application without exceptions. However, for some reasons, it couldn't register texts (approvedTexts had no element) and Dynamic Script for Local Text didn't work.  

I think that implement this feature as a fake service made it too complicated while a little modification to TryGet method of LocalTextRegistry would work fine. Key fallback should be implemented the same way as the language fallback be.

**Comment by volkanceylan** [comment]
I understand that it didnt work like you hoped but i'm not sure this is a valid fallback mechanism. For example en-us might be a fallback for en-uk and if you prioritize key fallback, it might never hit en-us even if there is a translation there. You might subclass LocalTextRegistry and change interface implementation of TryGet.

**Comment by volkanceylan** [comment]
You can also make private members of LocalTextRegistry protected and TryGet method virtual if needed.

**Comment by DucThanhNguyen** [comment]
Thanks for you suggestion. I also thought that subclass would be OK. I think language fallback should be prioritized except the default (invariant) one. 

I'm going to reimplement this feature. If it fit my need then i think it may be useful for someones else. It should be optional and easy to switch to in Serene without modify Serenity Dlls.
