### ISSUE TITLE
BasicSamples\EntityDialogAsPanel

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1466]
After adding the new sample to Extend an existing Entity the default Grid with Modal scenario does not work.
It seems that when we add the Panel Decorator it gets assigned to the base object.

I tried with two different extended classes but I get the same result.
So the solution is to have separate EntityDialogs?

**Comment by volkanceylan** [comment]
Yep, you need two separate classes if you'll use same thing in two different modes.
