### ISSUE TITLE
How can I refresh the Grid data in the dialog? 

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#1467]
How can I refresh the Grid data in the dialog?
I use method in dialog to refresh the Grid data. 

AdmMailGrid.prototype.refresh(); 

But it didn't work.

**Comment by xareas** [comment]
I use  

$(".refresh-button").click();

**Comment by newyearsoft** [comment]
It works!Thank you very much!

**Comment by edson** [comment]
As an alternative if you don't have the refresh button.

In your dialog.ts
 Serenity.SubDialogHelper.triggerDataChange(this);

Best Regards
