### ISSUE TITLE
QuickSearch with a datetime field

### ISSUE THREAD

**Issue by giovannip86** [volkanceylan/Serenity#1468]
Hi mr , I have a 1 problem when i use your theme start kit .

  [DisplayName("Release Date"), QuickSearch(SearchType.Contains)]
        public DateTime? ReleaseDate
        {
            get { return Fields.ReleaseDate[this]; }
            set { Fields.ReleaseDate[this] = value; }
        }

i have a problem when i use QuickSearch with a datetime field .
Can you help me?

**Comment by volkanceylan** [comment]
I don't think quick search works on a date field, use a quick filter, or define a new expression field that converts it into a string using CONVERT in SQL etc.
