### ISSUE TITLE
Error when click in a multiple-selection column

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1469]
Hi Volkan!

I was using your example of the multiple filter in the slick grid (Filtering with Multiple Genre List) and it works perfect.
Now, when I click on the column in the grid, it returns an error.
(Invalid Column Name "ListaRamos"). 
ListaRamos is the LIST i use to filter the grid, and its works

I Probe the same thing in your example of Movies and the same thing happens.
I can not find out where the problem is. Can you give some quick directions? 
Thanx
![000](https://cloud.githubusercontent.com/assets/8239681/20442891/4bf7295e-ada9-11e6-91dc-4104a2d4659b.png)

**Comment by Estrusco** [comment]
Check if the name of column in the database and in entity row match

**Comment by javaman63** [comment]
@Estrusco the column is generated, is not part of the table, its just like the movie genres examples

**Comment by volkanceylan** [comment]
Add [NotMapped, Sortable(false)]

**Comment by javaman63** [comment]
@volkanceylan Thanx so much. It worked
