### ISSUE TITLE
ERROR: Invalid column name 'Item'.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#147]
Hi,
I have an error what I understand but don't know how to resolve it.

here is my row (only showing two property)       
 
[DisplayName("Item Id"), NotNull, ForeignKey("[dbo].[Item]", "Id"), LeftJoin("jItem"), TextualField("Name")]
        public Int32? ItemId
        {
            get { return Fields.ItemId[this]; }
            set { Fields.ItemId[this] = value; }
        }
        [DisplayName("Item"), Expression("jItem.[Name]")]
        [MinSelectLevel(SelectLevel.List)]
        public string Item
        {
            get { return Fields.Item[this]; }
            set { Fields.Item[this] = value; }
        }

When I save this row it says: Invalid column name 'Item'.

**Comment by dfaruque** [comment]
By changing Item > ItemName, it works. why?

**Comment by volkanceylan** [comment]
Where it says this. Maybe Item is a reserved word somewhere.
