### ISSUE TITLE
View Fields with MinSelectLevel(SelectLevel.List) are not populated on Update

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1470]
`[DisplayName("Assigned User"), Expression("jAudit.[AssignedUserId]"), MinSelectLevel(SelectLevel.List)]
        public Int32? AssignedUserId
        {
            get { return Fields.AssignedUserId[this]; }
            set { Fields.AssignedUserId[this] = value; }
        }`

`private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void ValidateRequest()
            {
                base.ValidateRequest();
                if (Row.AssignedUserId.ToString() != Authorization.UserId)`

throws NullReference exception. The AssignedUserId is populated on List and Retrieve, but it (and all other View Fields) are empty when this is called.

**Comment by volkanceylan** [comment]
Only table fields are loaded in save handler. If you want other fields, override PrepareQuery and add fields you need.

**Comment by wldkrd1** [comment]
protected override SqlQuery PrepareQuery()
            {
                var query = base.PrepareQuery();
                query.SelectNonTableFields();
                return query;
            }

Yep, that did it. Thanks!
