### ISSUE TITLE
Serenity.ListRequest not calling Endpoint class

### ISSUE THREAD

**Issue by okowiro** [volkanceylan/Serenity#1471]
I have a Grid class with this method:

 protected onViewSubmit() {
            // only continue if base class returns true (didn't cancel request)
            if (!super.onViewSubmit()) {
                return false;
            }
            //this.setTitle("Client Search Results");
         
            let request = this.view.params as Serenity.ListRequest;
}

When i click on the submit button its not sending the request to the endpoint. Its not calling the endpoint. What am i doing wrong here?

This method is not being called as well
 protected onViewProcessData(response: Serenity.ListResponse<*****Row>): Serenity.ListResponse<****Row> {
            alert('Total Count: ' + response.TotalCount);
            return super.onViewProcessData(response);
        }

**Comment by volkanceylan** [comment]
If you don't return true from onViewSubmit it won't call service

**Comment by okowiro** [comment]
Volkan,

the onViewSubmit is returning a true but it still doesnt call the list service. see below..

 protected onViewSubmit() {
            // only continue if base class returns true (didn't cancel request)
            if (!super.onViewSubmit()) {
                return false;
            }
            //this.setTitle("Client Search Results");
         
            let request = this.view.params as Serenity.ListRequest;
            Q.notifyInfo("Request:" + this.view.params);

            this.StartDate = $('#Tag1').find('input[name="StartDate"]').val();
            this.EndDate = $('#Tag1').find('input[name="EndDate"]').val();
            this.Progid = $('#Tag1').find('input[name="Progid"]').val();
            this.LocationId = $('#Tag1').find('input[name="LocationId"]').val();
            var search: any[] = [];

             
            //this.view.params = request;
            Q.notifyInfo("Program" + this.Progid);
            
            Q.notifyInfo("super.onViewSubmit():" + super.onViewSubmit());
        
            return true;
        }

**Comment by volkanceylan** [comment]
Check if you have getGridCanLoad or script error somewhere. Grid editors won't call service.

**Comment by okowiro** [comment]
No i dont. Thanks for your quick response. Ok let me explain to you what im trying to do.

I created a form and want to post the selections to server side and display the results in a grid. What would you advise i do?

see attached
![screen shot 2016-11-21 at 10 17 55 am](https://cloud.githubusercontent.com/assets/22594794/20490683/6570f838-afd4-11e6-85e3-f0fdc4b47244.png)
![screen shot 2016-11-21 at 10 17 34 am](https://cloud.githubusercontent.com/assets/22594794/20490684/65743840-afd4-11e6-85fb-b9a101247809.png)
