### ISSUE TITLE
How to send an email notification after create

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#1473]
Hi to all,
   how can i send an email after create of a new ticket is save in database?
I do not know what is the best way to do this.
I want to send a notification to admin that there is a new ticket/request. thanks!

sample code...

` public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {

            var emailSubject = "New TEST Ticket ID: " + request.Entity.TicketId;
            var emailBody = " Request By: " + request.Entity.Email;

            var message = new MailMessage();
            message.To.Add("admin@gmail.com");
            message.CC.Add(request.Entity.Email);
            message.Subject = emailSubject;
            message.Body = emailBody;
            message.IsBodyHtml = true;

            var client = new SmtpClient();
            client.Send(message);

            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }
`

see screenshot.
![ticket2](https://cloud.githubusercontent.com/assets/22849322/20455390/0f0600ae-ae96-11e6-8058-af4ca7714a28.jpg)

**Comment by xareas** [comment]
In Repository, override method After Save

private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void AfterSave()
            {
                base.AfterSave();
                //send email here.
            }
        }

**Comment by volkanceylan** [comment]
There is a sample in user repository signup

**Comment by alex-444** [comment]
Sorry for late reply..
Thanks @xareas  that's what i'm looking for, i just need to override and use base.AfterSave()
This is also the same concept if i want to override the ListResponse to filter. 

@volkanceylan  I followed the sample in signup but i cannot get it to work. :) .. thanks!

**Comment by dfaruque** [comment]
Replace the following line of code in web.config to your mail settings.

  <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory" from="no-reply@mysite.com" />
    </mailSettings>
  </system.net>
