### ISSUE TITLE
User hakları

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1475]
Hocam merhaba, 
yeni eklediğim modulu X1 user için "edit user permissions" ekranında yetkilendirme yapmama rağmen, X1 user ile login olunca sol menüde modul görünmüyor, nerde hata yapıyorumdur,yardımcı olabilirseniz çok memnun olurum
Teşekkürler

**Comment by volkanceylan** [comment]
Page deki yetkiye bakın

**Comment by volkanturk** [comment]
Çok teşekkürler , çözdüm :)
