### ISSUE TITLE
Cannot make a grid span pages height

### ISSUE THREAD

**Issue by mirokulket** [volkanceylan/Serenity#1476]
Hello, 
please how could I make a grid "span" across a page's height. I have created a grid inspired by MovieTutorial (extending "Serenity.EntityGrid<MyRow, any> {"), but it's height is never correct - it is sized by number of rows and there is a vertical scrollbar on the whole <div id="#GriDiv">
I am using this method: Q.initFullHeightGridPage($('#GridDiv'));

What could be the problem?
Thank you very much!

**Comment by sayuga** [comment]
Could you add an image? Normally the grid should cover the span height unless you add to the html of the index page. 

I do know that if there is a error, the grid will sometimes not load correctly. Check the console as well and see if there are any errors.

**Comment by DucThanhNguyen** [comment]
If you created your project using previous version of 2.5.0, then upgrade to latest version of update your nuget packages, you could get this issue. Follow these instructions will fix it: https://github.com/volkanceylan/Serenity/issues/1342

If you put GridDiv inside another div, it can't be full page height as well

**Comment by mirokulket** [comment]
Upgrade solved my problem. Thank you!
