### ISSUE TITLE
select changeindex

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1478]
Hocam merhaba, bir sorum olacaktı ; 

CarikartFormumda illeri gösteren dropdownlist'im var.İstanbul'u seçince ,ilçeler dropdownlist'de sadece istanbul'a bağlı olan ilçelerin gelmesini nasıl sağlayabilirim ?

Yardımcı olabilirseniz çok memnun olurum

**Comment by VictorTomaili** [comment]
Dökümantasyonu incelemeni tavsiye ederim.
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

**Comment by volkanturk** [comment]
Teşekkürler Victor denedim fakat olmadı.
CustomerForm'da uygulayabilmek için aşağıdakii kodları  nereye nasıl eklemem gerek?

AddEqualityFilter<LookupEditor>("CountryId",
    options: new LookupEditorOptions 
    { 
        LookupKey = "MyModule.Country" 
    });

AddEqualityFilter<LookupEditor>("CityId", 
    options: new LookupEditorOptions 
    {
        LookupKey = "MyModule.City", 
        CascadeFrom = "CountryId",
        CascadeField = "CountryId"
    });

AddEqualityFilter<LookupEditor>("DistrictId", 
    options: new LookupEditorOptions 
    {
        LookupKey = "MyModule.District", 
        CascadeFrom = "CityId",
        CascadeField = "CityId"
    });

**Comment by VictorTomaili** [comment]
Gönderdiğin kod `grid tarafında filtre eklemek isterseniz` diye belirtilen kod. CarikartGrid.ts dosyasında olması gerekiyor. Fakat sen öyle birşey istemiyorsun. Sadece form dialoğunda kullanacaksın. Bu sebeple sadece alttaki gibi `*form.cs` dosyasına lookup editör attributeları ekleyip cascaded olan tabloların name alanlarına `LookupInclude` attribute u eklemen gerekiyor. 

```csharp
    [LookupEditor(typeof(Entities.CityRow), 
        CascadeFrom = "CountryId", CascadeField = "CountryId")]
    public Int32? CityId { get; set; }
```

**Comment by volkanturk** [comment]
Süper :) çok teşekkürler Victor

**Comment by VictorTomaili** [comment]
Rica ederim. Sorunun çözüldüyse issues i kapatabilirsin :)
