### ISSUE TITLE
Two level master-detail relation

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#148]
I have successfully use MasterDetailRelation attribute for master-detail crud.

My data structure is master-detail-detail2
So I have added MasterDetailRelation attribute to detail row.
 detail2 record save successfully to DB but does not retrieve.

How can I retrieve detail2 records? 

Thanks.

**Comment by ChenZhaobin** [comment]
Maybe you can add a link field

**Comment by volkanceylan** [comment]
Override OnReturn of DetailRepository.MyListHandler, then something like

foreach (var x in Response.Entities) {
    x.Detail2List = Connection.List<Detail2Row>(q => q.Detail1ID == Row.Detail1Id);
}

Something like this might work, but i didn't think about two level of master/detail.

**Comment by dfaruque** [comment]
When I retrieve master the OnReturn of DetailRepository.MyListHandler does not fire. It fires only the OnReturn of MasterRepository.MyListHandler.

So something has to add in OnReturn of MasterRepository.MyListHandler.

Is it possible. if possible then please give a snippet. Thank again.

**Comment by volkanceylan** [comment]
var d2 = Entities.Detail2Row.Fields;
            foreach (var x in Response.Entity.DetailRows)
            {
                x.Detail2Rows = Connection.List<Entities.Detail2Row>(d2.DetailId ==  x.Id));
            }

**Comment by dfaruque** [comment]
Error in compilation: Operator '==' cannot be applied to operands of type 'Serenity.Data.Int32Field' and 'int?'

**Comment by volkanceylan** [comment]
Try x.Id
Value

**Comment by dfaruque** [comment]
thanks. it works.
