### ISSUE TITLE
ScriptBundling dose not work

### ISSUE THREAD

**Issue by alitarkian** [volkanceylan/Serenity#1480]
Hi Friend,
I published some website by serenity and it's good working thanks you,
but they have some problem for example ScriptBundling dose not work or minify  script , css ......

I try to use web.optimize from MVC but conflict by serenity
can help me please!?

**Comment by edson** [comment]
See
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_enable_script_bundling.html

Best Regards
