### ISSUE TITLE
Grouping on DateTime Field

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1481]
I have a DateTime Field, when try to Group the field in grid, each record with different time is grouped separately.
How to group based on Date for DateTime Field?
regards
Shailesh

**Comment by sayuga** [comment]
You can us a formatter to handle the grouping. If you look at the grouping sample, you'll see that you can designate the field and then have it manipulated regarding it's output. 

For example, in the Basic Sample that we have, if CategoryName was a Enum you could have a function to mange  the display of the enum: 

  {
                title: 'Group By Category',
                cssClass: 'expand-all-button',
                onClick: () => this.view.setGrouping(
                    [{
                        formatter: x => 'Category: ' + this.myCategoryEnum(x.value) + ' (' + x.count + ' items)',
                        getter: 'CategoryName'
                    }
                }
myCategoryEnum(x) {
            var y;
            if (x == 1) {
                y = "CategoryA";
            }
            else if (x == 2) {
                y = "CategoryB";
            }
            else if (x == 3){
               y = "CategoryC"; 
            }
            return y;
        };

If you look at the setGrouping overloads, you'll see you can manage a few other items: 

        getter?: any;
        formatter?: (p1: Slick.Group<TItem>) => string;
        comparer?: (a: Slick.Group<TItem>, b: Slick.Group<TItem>) => number;
        aggregators?: any[];
        aggregateCollapsed?: boolean;
        lazyTotalsCalculation?: boolean;

**Comment by shaileshbc** [comment]
Dear Sayuga,
Thanks for replying.
As per your suggestion, it just change the way the field is displayed.
but in my case, its a datetime field, where each record might have different Time and hence when i try to group on datetime field, i get each record separately grouped, which is not required.
grouping all the records with same date is required.
regards
Shailesh

**Comment by edson** [comment]
Hi, @shaileshbc . You should set a function for the comparer in setGroupings so it can do grouping only in the date part of your field.

Best Regards

**Comment by edson** [comment]
Sorry. comparer and other functions in setGrouping only formats Grouping related. If you want to group, an easier way would be to separete time and date in columns using an expression... Tried to do this without it, but slickgrid seems to not support it on the fly... 

Best Regards

**Comment by shaileshbc** [comment]
Thank you @edson, what i tried with your suggestion :
put [Expression("PunchDate.Date")] in columns.cs
but since we have to specify getter value of Setgrouping as a field Name, it still grouping each records separately only.
putting getter: 'PunchDate.Date' or 'Date(PunchDate)' does make much difference, it sets group as undefined.
regards
Shailesh

**Comment by volkanceylan** [comment]
getter: item => Q.parseISODateTime(Q.formatDate(item.Date, 'yyyy-MM-dd'))

**Comment by shaileshbc** [comment]
In my case Field name is PunchDate, so i changed getter as
getter: PunchDate => Q.parseISODateTime(Q.formatDate(PunchDate.Date, 'yyyy-MM-dd'))
and 
getter: item => Q.parseISODateTime(Q.formatDate(item.Date, 'yyyy-MM-dd'))
in both the cases, i am getting group title as
PunchDate: null
i think, i have not written it wrongly, can u please suggest how do i write getter correctly.
regards
Shailesh

**Comment by volkanceylan** [comment]
You should try some javascript / TypeScript / C# basics guide

getter: item => Q.parseISODateTime(Q.formatDate(item.PunchDate, 'yyyy-MM-dd'))

**Comment by shaileshbc** [comment]
Dear Volkan,
i am getting error as
TypeError: date.getFullYear is not a function
in Serenity.corelib.js at line no. 525
regards
Shailesh

**Comment by volkanceylan** [comment]
Try Q.formatDate(Q.parseISODateTime(item.PunchDate), 'yyyy-MM-dd'))

**Comment by shaileshbc** [comment]
Thank you Very much, It Works.
One small thing, i want date to be shown in grid with format as dd/MMM/yyyy then
how i can do it.
When i am put displayformat as 'dd/MMM/yyyy' it shows month value twice for eg. for today's date shown as 30/1111/2016
can we able to show date in dd/MMM/yyyy format in grid and also in Quickfilter?
regards
Shailesh
