### ISSUE TITLE
sergen problems

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1482]
Sergen gives errors when mapping to sql server tables like "TDU_GuiasMarcacao" i think it is the character '_', because in sergen it concatenates like "TDUGuiasMarcacao"....

![image](https://cloud.githubusercontent.com/assets/10889019/20536752/3532cee4-b0e2-11e6-854d-1e5b447ba2b1.png)

**Comment by volkanceylan** [comment]
Nope, it doesn't give errors

**Comment by brunobola** [comment]
strange, to me it gives... But I have right, it it because sergen makes several fields with the same name when a table has multiple keys to other tables and the other tables have same named fields and it duplicates attributes in .ts files and .cs files.... Maybe you could create alias for it somehow... 

I was mistaken thinking it was because of that because the black dialogs when sergen is generating files are full of messages, maybe because of the situation i described, i've corrected it manually by removing the dependent atributes with the same names the principal table, but its a really hard work, i have a ERP database that have huge amount of relations.....

**Comment by volkanceylan** [comment]
Sergen doesn't generate duplicate names. You probably have multiple FKs to sample table, or very similar field names somewhere.

**Comment by brunobola** [comment]
You are wrong it generates duplicated names, following scenario:
- TABLE A ->(foreign) TABLE B
- TABLE A ->(foreign) TABLE X 
- TABLE B ->(foreign) TABLE C
- TABLE C ->(foreign) TABLE X

Then Generate Code for tables and see for your self.

**Comment by volkanceylan** [comment]
I have many such tables, Northwind is full of such tables, so why doesn't it generate duplicated names, non-sense.

**Comment by brunobola** [comment]
@volkanceylan why are you say it is non sense.

I have a real ERP database, with several thousands of tables views and it has that kind of relationships and i have to edit the ts files to fiz that kind of problems, please don't talk as if you're the only one that knows everything... I really apreciate your work, but this kind of treatment are not cool, I may not understand that much of web technologies yet, but certainly doubt you know as much SQL Server/C#/Winforms as me, that saying thanks anyway.

**Comment by brunobola** [comment]
@volkanceylan why are you say it is non sense.

I have a real ERP database, with several thousands of tables views and it has that kind of relationships and i have to edit the ts files to fiz that kind of problems, please don't talk as if you're the only one that knows everything... I really apreciate your work, but this kind of treatment are not cool, I may not understand that much of web technologies yet, but certainly doubt you know as much SQL Server/C#/Winforms as me, that saying thanks anyway.

**Comment by volkanceylan** [comment]
No i can't keep up with the level of your SQL knowledge. I'm sure noone on earth can have a database with 1000+ tables as you have.

You expect proper treatment? Than do proper treatment and report properly first. Showing two screenshots and saying oh it doesn't work makes no sense at all. Programmers should learn how to write "steps to reproduce" first before trying to write a program, but not sure you had time from designing that so complex ERP tables.

**Comment by brunobola** [comment]
@volkanceylan, i'll make you a "tutorial" in witch i'll give you a backup of my database and also a video for you to see for your self.

Second, i don't know how you treat people in your country, but in my we are polite to each other and try to understand the problems, so I response to you in the same manner as you, you were arrogant letting me know sergen hasn't problems (makes non sense)...

And if i'm using this platform is because i like it and think you make a good work sharing, i know you young programmers think you are the the best, but please try to investigate who you're talking to when not being polite to each other.

As always, keep up the good work.

**Comment by volkanceylan** [comment]
You have self referencing FK in that table, probably created by mistake in designer
