### ISSUE TITLE
quickfilter not persist

### ISSUE THREAD

**Issue by xareas** [volkanceylan/Serenity#1483]
Quickfilter not persist

I put directive in ScriptInitialization.ts file
Serenity.DataGrid.defaultPersistanceStorage = window.localStorage;
but quickfilter not restored the values

![prueba](https://cloud.githubusercontent.com/assets/5817316/20549393/594d176c-b0f1-11e6-9c4b-02ea31adb637.png)

**Comment by volkanceylan** [comment]
QuickFilters are not persisted yet. Noted in docs.
