### ISSUE TITLE
use webservis

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1485]
Hocam merhaba, 
CustomerForm'da yeni bir Customer eklemek istediğimde, kaydetmeden önce asmx uzantılı  webservis'e  bağlanıp, bir method kullanıp sonucu false ise uyarı vermek , true ise kaydetmek istiyorum,nasıl yapabilirim?

Yadımlarınız için çok teşekkür ederim

**Comment by VictorTomaili** [comment]
Repository de override edebileceğin SaveHandler altında OnBefore gibi bir metod olması lazım. Orada istediğin servisi istediğin gibi çağırabilirsin. Save ettikten sonra çalıştırılan örneği aşağıda. 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Product/ProductRepository.cs#L53

**Comment by volkanturk** [comment]
Teşekkürler Victor:)
