### ISSUE TITLE
criteria field is not found! [Insert into related tables]

### ISSUE THREAD

**Issue by reuwarwema** [volkanceylan/Serenity#1486]
Am sure am missing something small. I have a table dbo.[ApplicantDetails] with PK [RegistrationID] and another column FK [AddressID]

And the related table dbo.[PhysicalAddress] with PK [AddressID]

Below is my implementation (From Northwind DB) Customer table

//beginning of code
 [LeftJoin("jPhysicalAddress", "PhysicalAddress", "jPhysicalAddress.AddressID = t0.AddressId")]
    [UpdatableExtension("jPhysicalAddress", typeof(PhysicalAddressRow), CascadeDelete = true)]
    public sealed class ApplicantDetailsRow : Row, IIdRow, INameRow
    {
//...

 [DisplayName("Registration Id"), Column("RegistrationID"), Size(100), PrimaryKey, QuickSearch, Updatable(false), LookupInclude]
        public String RegistrationId
        {
            get { return Fields.RegistrationId[this]; }
            set { Fields.RegistrationId[this] = value; }
        }
 [DisplayName("Address"), Identity]
        public Int32? AddressId
        {
            get { return Fields.AddressId[this]; }
            set { Fields.AddressId[this] = value; }
        }
  IIdField IIdRow.IdField
        {
            get { return Fields.RegistrationId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.RegisteredName; }
        }

//

I get the error 'RegistrationId' criteria field is not found!

Am sure its something small. Please advise: Anyone

**Comment by volkanceylan** [comment]
Where do you get this error. Which is this row.

**Comment by reuwarwema** [comment]
After editing the ApplicantDetailsRow which has the PK (CandidateID‎), and FK (AddressID) for table PhysicalAddress.                                                                                                                                     I ran the app, browsed to ApplicantDetails grid, clicked on Add NewApplicant ( the error pops up when Updating / Saving data from a form) For my case, wanted to insert to both AddressDetails and PhysicalAddress tables.                                                                                                                                                                                                    Regards, Reuben Warwema

**Comment by volkanceylan** [comment]
You are still not helping, asked which row is the one that you listed above. 

You are sending RegistrationId criteria to somewhere. You don't have RegistrationId in some row, e.g. detail row. I guess you set RegistrationId in MasterDetailRelation but you don't have such a field there.

**Comment by reuwarwema** [comment]
I think I get your point and yes, I seem not to be sending RegistrationId. I followed the example on CustomerRow.cs please advise if there are more areas to look at. Thanks again                                                                                                                                                                                                                                                                                                                                        Regards, Reuben Warwema

**Comment by volkanceylan** [comment]
Please share your row sources properly and fully if you need help :)

**Comment by reuwarwema** [comment]
[PhysicalAddress and ApplicantDetails.zip](https://github.com/volkanceylan/Serenity/files/609738/PhysicalAddress.and.ApplicantDetails.zip)

**Comment by volkanceylan** [comment]
Nope, this won't work. PhysicalAddressRow is not an extension row of ApplicantDetailsRow. If it was, it should have a RegistrationId. 

[UpdatableExtension("jPhysicalAddress", typeof(PhysicalAddressRow), CascadeDelete = true)]

This make UpdatableExtension think that, primary key of PhysicalAddressRow, which is RegistrationId is the matching extension ID in PhysicalAddressRow.

You could write

[UpdatableExtension("jPhysicalAddress", typeof(PhysicalAddressRow), CascadeDelete = true, ThisKey = "AddressId")]

to specify that AddressId is the actual joining field in main table but this would still only work for updates, not inserts.

UpdatableExtension updates the detail table, it can't insert into detail table and set its ID in main table. It can only modify "Detail" table. You expect it to modify your main table to set AddressID. This is not possible.

**Comment by reuwarwema** [comment]
Let me dive into it. Thanks                                                                                                                                                                                                                                                                                                                                         Regards, Reuben Warwema

**Comment by reuwarwema** [comment]
I was able to implement it. Thanks.
