### ISSUE TITLE
Creating a custom grid-container to override the generated one.

### ISSUE THREAD

**Issue by Cameron-Smith2016** [volkanceylan/Serenity#1487]
Hi,

I am trying to change the height of the gird being displayed on the page. As serenity generates its own css styles, I was wondering if there was a way of creating a custom grid-container so that it ignores the generated container?

**Comment by edson** [comment]
You can customize css and html elements, js.... look for samples... .cshtml in your module files...

Best Regards

**Comment by sayuga** [comment]
Look in the Content/Site folder to manage the .less files
