### ISSUE TITLE
Date Format of DateQuickFilter / DateTimeQuickFilter doesn't change

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#1489]
Dear Volkan,
Date Format of DateFilter / DateTime QuickFilter, doesn't change, even if
`<globalization culture="auto:en-GB" uiCulture="auto:en-GB" /> `
or `<globalization culture="auto:en-IN" uiCulture="auto:en-IN" />`
is set in Web.config
It remains as MM/dd/yyyy whereas i require dd/MM/yyyy
regards
Shailesh

**Comment by volkanceylan** [comment]
Search issues
