### ISSUE TITLE
Question about Form generation.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#149]
Actually this is not an issue. I am wonder to know...

I have modify MyForm.cs (in web project) and add a string field to it. Then run the application.

I notice that the Form is correctly viewing in the browser. 

How serenity generates Form from MyForm.cs at runtime?

**Comment by ChenZhaobin** [comment]
Maybe this link can help you to understand [Saltarelle Compiler (https://github.com/erik-kallen/SaltarelleCompiler).]

**Comment by volkanceylan** [comment]
Serenity uses reflection to locate classes with FormKey attribute. Then it traverses all properties and outputs a JSON object with all the details. Then these details are converted to a dynamic form script. You can view it at client side, from Chrome console, with Q.GetForm("MyModule.MyForm").

Then, you have FormKey attribute on top of your dialog class. Dialog loads these form definition using Q.GetForm, and feeds it to a PropertyGrid class, which creates editors and label in script side.

**Comment by dfaruque** [comment]
Thanks a lot.

**Comment by dfaruque** [comment]
I am little bit confusion,
If serenity generate forms using reflection then what is the purpose of FormContexts.tt in script project.
Please help me to understand.
Thanks.

**Comment by volkanceylan** [comment]
It is to access form elements with intellisense, without having to use hard coded ID's. They are just shortcuts to this.ById("MyProp") methods.

**Comment by dfaruque** [comment]
In a new serenity project, I have generate code for 300 tables. Now when I transform t4 files it takes too much times (sometimes vs is being hanged). 

If I do not want to use t4. Then how much effort will need.

**Comment by volkanceylan** [comment]
It is not about t4, Saltarelle compiles project whenever a file added, so it compiles 400 Times on first run. But it will be ok for next runs.

**Comment by dfaruque** [comment]
You are right, in script project when I include a file it takes almost a minutes.

**Comment by volkanceylan** [comment]
Its .targets file is buggy, i sent a request but he didn't consider it. See my targets file in Serenity source.

**Comment by dfaruque** [comment]
ok.
