### ISSUE TITLE
MasterDetailRelation - Cant Create New Entry 

### ISSUE THREAD

**Issue by csteppe** [volkanceylan/Serenity#1491]
I have Added a MasterDetail Relation to a Row .

```
 [DisplayName("Claim Notes"), MasterDetailRelation(foreignKey: "CustomerProductClaimId"), NotMapped]
        public List<CustomerProductClaimNotesRow> notesRow
        {
            get { return Fields.notesRow[this]; }
            set { Fields.notesRow[this] = value; }
        }
```

And I have added a entry to my form.

```
 [CustomerProductClaimNotesEditor]
        [Category("Claim Notes")]

        public List<CustomerProductClaimNotesRow> notesRow { get; set; }
```

This brings up a grid in my dialogue with the correct information displayed according to the foreign key specified . 

When I try to add a new entry using this editor it simply appends it in the grid but without an ID which indicates that it actually doesnt add it to the database. I know this because the  breakpoint in my endpoint.cs under the create call is never hit . 

Not sure what im missing as Ive looked through the serene codebase and tried to follow it as close as possible.

**Comment by edson** [comment]
It is a memory grid... It will save when you hit that entity save button, so it updates its id...

Best Regards...
