### ISSUE TITLE
CaptureLog with GUID primary keys

### ISSUE THREAD

**Issue by James-A-White** [volkanceylan/Serenity#1492]
Hello Volkan,

I converted a database recently from int primary keys to GUIDs because we need to be able to move DB objects from one server to another without having ID clashes. In the process, the CaptureLog feature stopped working.  I confirmed that it is the key type that is the culprit.  Is there a workaround?

Thanks!

James

**Comment by volkanceylan** [comment]
CaptureLog doesn't yet work with anything other than integer IDs

**Comment by volkanceylan** [comment]
I'll try to have a look at it soon, hopefully faster than i looked at your AD contribution :(

**Comment by volkanceylan** [comment]
Can you try with 2.6.3 please

**Comment by James-A-White** [comment]
Haven't had a chance to try yet, but should be able to get to it in the next few days... thanks for the great support!

J

**Comment by volkanceylan** [comment]
Reopen please if it is not working.
