### ISSUE TITLE
Keyboard navigation in grid

### ISSUE THREAD

**Issue by allema** [volkanceylan/Serenity#1494]
I was trying to enable keyboard navigation in the editing grid but can't get it to work. The functionality is built into Slickgrid, so I thought I could just enable it in the options like so:
```
var options = this.slickGrid.getOptions();
options.enableCellNavigation = true;
this.slickGrid.setOptions(options);
```
When I press arrow down the cursor leaves the current cell but doesn't move to the cell below. Any hint on how to implement this?

Thanks

**Comment by volkanceylan** [comment]
I dont support inline editing and or cell navigation. It might work but you should look / ask in SlickGris.
