### ISSUE TITLE
[Bug] Inactive user toggle

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1495]
Dear @volkanceylan,
the inactive user toggle (top dx) seems to be not working properly:
![image](https://cloud.githubusercontent.com/assets/17425690/20595279/9e6297a2-b239-11e6-91d9-45c8b1744c96.png)

I see that user active/inactive are formatted in a different way (in the screenshot above the 2nd user is inactive), but I always see all records regardless of the state of the toggle button.
Any idea?

Thanks as always
Bye

**Comment by volkanceylan** [comment]
Set IsActiveField in your grid, in your row, and its not inactive toggle its deleted toggle

**Comment by marcobisio** [comment]
Ohhh...you're right! Maybe I'm too tired :-(
Sorry for the false alarm!

Thanks
Bye

**Comment by marcobisio** [comment]
Dear @volkanceylan,
sorry if I reopen this old issue, but there is something wrong (or more likely something that I don't fully understand!).
In the previous response you told me that such toggle it's a 'deleted toggle' while the tooltip shows 'display inactive record':

![image](https://cloud.githubusercontent.com/assets/17425690/22067535/f8f41474-dd91-11e6-9aee-aeed3c857e65.png)

and that's fine, it could be a typo, but which is the point of a delete toggle if there isn't any logical deletion mechanism? In fact I tried to delete a user and it's a physical deletion.

I'm missing something? I'm asking that because I'm trying to implement a show/hide inactive records functionality and I would like to re-use such button on my grids.

Thank you very much!
Bye

**Comment by marcobisio** [comment]
Assuming that 0 "means" inactive and 1 means "active", there is an error here (ListRequestHandler.cs):

    protected virtual void ApplyIncludeDeletedFilter(SqlQuery query)
    {
        if (!Request.IncludeDeleted)
        {
            var isDeletedRow = Row as IIsActiveDeletedRow;
            if (isDeletedRow != null)
                query.Where(new Criteria(isDeletedRow.IsActiveField) >= 0);
            else
            {
                var deleteLogRow = Row as IDeleteLogRow;
                if (deleteLogRow != null)
                    query.Where(new Criteria((Field)deleteLogRow.DeleteUserIdField).IsNull());
            }
        }
    }

It should be >0 and not >=0 I think...

**Comment by volkanceylan** [comment]
Nope that's correct. It should be >= 0.

**Comment by volkanceylan** [comment]
Let's take a sample.

We have users table where users might be active = 1, new users which are not activated yet, e.g. passive = 1, and ones who are (soft) deleted = -1.

In editing screens for users, i would certainly want to see active users by default, and not activated users too by default. But inactive users should look grayish to differentiate them from active ones.

I wouldnt want to see deleted users, unless i want to find a deleted one specially. For example to undelete one deleted by mistake. Deleted records are shown with a strikethrough style and grayish.

So by default, grids show active and inactive records. 

To show deleted records, we have show deleted toggle and corresponding IncludeDeleted request parameter. Yes its title is misleading but overridable.

Unless IncludeDeleted is true, we only show active and inactive, e.g. >= 0.

If you dont have soft delete, your row should be IIsActiveRow not IIsActiveDeletedRow.

If you want to use show deleted toggle and IncludeDeleted parameter as a way to hide show inactive records, then you should override ApplyIncludeDeleted filter and use > 0 instead.

Hope it helps.

**Comment by marcobisio** [comment]
I completely misunderstood the meaning/behaviour of such toggle: now it make sense!

Thank you very much @volkanceylan for the detailed explanation.
Bye
