### ISSUE TITLE
[Bug] Advanced Filter and LinkingSetRelation

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1496]
Dear @volkanceylan,
I found a bug with the advanced filter and the LinkingSetRelation. In fact if I try to add a filter condition like that:
![image](https://cloud.githubusercontent.com/assets/17425690/20595626/e4c0378a-b23a-11e6-80ba-daa920d0b02d.png)

I get this:
![image](https://cloud.githubusercontent.com/assets/17425690/20595575/b6c2d02c-b23a-11e6-9c1f-339807ab74e9.png)

Any idea?

Thanks!
Bye

**Comment by marcobisio** [comment]
Just an update: also the sort operation on the Representatitives columns throws an Exception:

    An exception of type 'System.Data.SqlClient.SqlException' occurred in Serenity.Data.dll but was not handled in user code

    Additional information: Invalid column name 'Representatives'.

Thanks again!
Bye

**Comment by volkanceylan** [comment]
Add Sortable(false) Marco. Advanced filter doesnt support multiple option

**Comment by marcobisio** [comment]
Thanks Volkan...I've added a "Sortable(false)" and a "NotFilterable" attribute in order to prevent weird behaviour.

Thanks
Bye
