### ISSUE TITLE
[Request] Simple Line Icons update

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1497]
Dear @volkanceylan,
just a (very low priority) request: could you kindly update the Simple Line Icons library to the last version?
In Serenity we have the 2.2.2 and the current version is the 2.4.0 with many other wonderful icons! :-)

Let me know if you have time to do that, otherwise I just update such library in my project but I suspect that on every Serenity update such library will be overwritten!

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Does it have a nuget package?

**Comment by marcobisio** [comment]
I'm afraid not...

**Comment by marcobisio** [comment]
Thank you very much Volkan: just see the updated library in the last Web.Asset version!
Have a nice weekend!
Bye
