### ISSUE TITLE
Decimal and int values in entities not nullable

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1499]
Hi @volkanceylan !
Is there any contraindication to making the decimal and int values in entities not nullable?

```cs
        [DisplayName("Decimal"), Size(9), Scale(2), DefaultValue(0)]
        public Decimal MyDecimal
        {
            get { return (decimal)Fields.MyDecimal[this]; }
            set { Fields.MyDecimal[this] = value; }
        }
```

I would like to do this to avoid casting in some arithmetic operations that involve decimal (or int) values.

Thank you

**Comment by volkanceylan** [comment]
Never do it

**Comment by Estrusco** [comment]
So, what do you recommend to avoid continuous cast to decimal? to decimal, an intermediate property in in the class that performs the calculations?

**Comment by volkanceylan** [comment]
.Value is not that hard to type

**Comment by volkanceylan** [comment]
At least do ?? 0. Not direct cast.

**Comment by Estrusco** [comment]
Ok @volkanceylan  then I can use in entity row

```cs
        [DisplayName("Decimal"), Size(16), Scale(2), DefaultValue(0)]
        public Decimal MyDecimal
        {
            get { return Fields.MyDecimal[this] ?? 0; }
            set { Fields.MyDecimal[this] = value; }
        }
```

Can I make a pull request for add an option in the Sergen editor to make this?
Thank you very much

**Comment by volkanceylan** [comment]
I don't think it should be integrated in Sergen. It already has too many options to my taste and this is not something i recommend.

**Comment by Estrusco** [comment]
OK. Thank you for suggestions.
