### ISSUE TITLE
 image upload path

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#150]
How can I upload the pics in path format just like this "Movie/PrimaryImage/{TenantId}" or  "Movie/PrimaryImage/{DateTime.Now}"

**Comment by ChenZhaobin** [comment]
Also how can I change the image size？

**Comment by volkanceylan** [comment]
Unless you write your own ImageUploadBehavior, you can't do such things, only supported parameters are entity id and some random file code. Take ImageUploadBehavior as sample and write your own if you are desperate.

ImageUploadEditor has some attributes to control image size. ScaleWidth, ScaleHeight, ThumbSizes etc. It's pretty well documented.
