### ISSUE TITLE
Is it possible to use IsActiveField without Int16Field

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#1500]
My IsActive values "Y" or "N" ,so it's a StringField. And I want to use **IsActiveField**, is it possible?

I also have a problem with **ILoggingRow** as I need to use **InsertUserIdField** and **UpdateUserIdField** with StringField,

I think these two problems are similar

**Comment by Estrusco** [comment]
Why you don't use a boolean for a bit value (true or false, 1 or 0) instead of string Y or N?

**Comment by volkanceylan** [comment]
Define an expression column

**Comment by volkanceylan** [comment]
InsertUserId doesnt have to be integer.

**Comment by tky753** [comment]
I see **UpdateUserIdField** and **InsertUserIdField** don't have to be IntField. Forgive my stupid.

but how to use expression to set value to StringField IsActive? do I have to do someting in SaveRequestHandler.BeforeSave function to convert value?

**Comment by tky753** [comment]
one more question, if I want to save **username** in **InsertUserIdField** , I need to convert userid to username in **SaveRequestHandler.BeforeSave** function, right?

**Comment by volkanceylan** [comment]
You can't save username in InsertUserId field. If you need such, write your own behavior and your own logging row type.

**Comment by tky753** [comment]
Thanks.
