### ISSUE TITLE
[NEW] Integrate a new dialog Decorator, maybe?

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1501]
Having seen the Read Only Dialog sample in Serene demo, is it possible to set the code that does it as a part of Serenity.Decorators in the next version?

so that it will be alongside the  `@Serenity.Decorators.maximizable()` and `@Serenity.Decorators.responsive()` , etc.

so that we can just set dialogstaht serve only for viewing as `@Serenity.Decorators.readonly()`.

**Comment by volkanceylan** [comment]
Maybe but not sure it will be so useful feature. Next you'll ask to make it conditional, then ask to switch it by a button so on.
