### ISSUE TITLE
3 beginner questions

### ISSUE THREAD

**Issue by LaurentzT** [volkanceylan/Serenity#1503]
Hi,

How can we create a combobox with a where clause?
How can we create a combobox with an other dependency? For example select CustomerAddress where CustomerId= other Combobox with Customers on the form.

How can we make the grid editable?

If we create a master detail screen and we click on the column of the detailgrid then he show the arrows to sort but he doesn't sort the data. Any idea's?

Thanks for the answers!

**Comment by Estrusco** [comment]
Search Lookup in Serentiy issues and and you will get your answers. Also consider the idea to read the manual https://www.gitbook.com/book/volkanceylan/serenity-guide/details
