### ISSUE TITLE
Add more content to GridDiv

### ISSUE THREAD

**Issue by mirokulket** [volkanceylan/Serenity#1504]
Hello,
I want to add some content into a `<div id="GridDiv"></div>`, beside a grid.
My grid extends Serenity.EntityGrid

```
view.cshtml:     
    var grid = new MyGrid($('#GridDiv'), {});
     grid.init();

............
MyGrid.ts:
    export class MyGrid extends Serenity.EntityGrid<MyRow, any> {
            constructor(container: JQuery) {
              super(container);
           }

```
Do I have to rewrite the constructor, or change type of grid ?

Thank you
Miro

**Comment by Estrusco** [comment]
You can add other element with jQuery, or modify your Grid.cshtml file

**Comment by mirokulket** [comment]
I forgot to put the html code:
```
<div id="GridDiv">
   <span>content</span></div>
</div>
```
the <span> inside is removed in grid's constructor implicitly...

**Comment by Estrusco** [comment]
The div with id="GridDiv" is the part where the grid is drawn dynamically.
If you want aside content your html must be

<div id="GridDiv">
</div>
<div id="AnotherDiv">
   <span>content</span>
</div>

or you add dinamically with jQuery in .ts grid file

**Comment by mirokulket** [comment]
Since it is a content closely linked to data of the grid I'd like to have  it inside the grid's box, under the grid's title. 
What do you mean by dynamically adding it to ts grid file? Adding a new function that would load the additional content?

**Comment by Estrusco** [comment]
In  your grid.ts you can modify the DOM with jQuery.

```ts
        constructor(container: JQuery) {
            super(container);

            // Get your gridDiv with jQuery... 
            // $('#GridDiv')
        }

       // Overraide createSlickGrid to get the grid element
        protected createSlickGrid(): Slick.Grid {
            var grid = super.createSlickGrid();
            
            return grid;
        }
    }
```

**Comment by Estrusco** [comment]
See this exmple that add one dropdown button to toolbar. With the same process you can add what you want

https://github.com/volkanceylan/Serenity/wiki/SplitButton%20dropdowns

**Comment by mirokulket** [comment]
thank you for your help
