### ISSUE TITLE
serenity and Wcf

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1505]
Is it possible to insert data from Wcf service to sergen?
Is there any other way to use serenity functionality with Wcf service return?
thanks in advance

**Comment by volkanceylan** [comment]
No. You could create similar tables and generate code for them. Sergen doesnt insert data. See how i use Vsgallery.

**Comment by brunobola** [comment]
@volkanceylan is right, the best way it to mimic the tables build your logic and use the sergen to auxiliante  you. 

Alternatively you can do this behaviour yourself changing the save events...

**Comment by satsokn** [comment]
thanks a lot. i created a service reference and changed List service.
