### ISSUE TITLE
How to add PDFExportHelper in XYZgrid.ts as a column

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1506]
Hi guys, im trying to create new column with pdf export button for each XYZrow. Im doing this (for my 3rd column):

```
protected getColumns() {
   var columns = super.getColumns();
   columns.splice(2,0,{
   field: "Report PDF",
   name: "Report",
   format: ctx => {
      return "<a class='inline-action report-pdf' title='Report pdf'>Report this!</a>";
   },
   width: 100,
   minWidth: 24,
   maxWidth: 100
   });
}
```
And i don't know yet how to implement my "onClick" function:

```
protected onClick(e: JQueryEventObject, row: number, cell: number): void {
   super.onClick(e, row, cell);
   if ($(e.target).hasClass('report-pdf')) {
      e.preventDefault();
      MyProject.Common.ReportHelper.createToolButton({
         title: 'Report',
         cssClass: 'export-pdf-button',
         reportKey: 'MyModule.XYZEntity',
         getParams: () => ({ MyRowId: item.MyRowId })
      })
   }
}
```

But obviously this doesn't work. I'll appreciate any suggestion or help. Thanks in advance!

**Comment by volkanceylan** [comment]
Get a reference to item first, see samples

**Comment by alanlopcu** [comment]
Hi volkan, well i forgot that line in my example. I'm already using it in my code:

`let item = this.itemAt(row);`

But my question is, how must i call my "show report pdf for this itemID" action. Because this:

```
MyProject.Common.ReportHelper.createToolButton({
         title: 'Report',
         cssClass: 'export-pdf-button',
         reportKey: 'MyModule.XYZEntity',
         getParams: () => ({ MyRowId: item.MyRowId })
      })
```

doesn't work. It just "createToolButton". I need generate my report. Like in your "InlineActionButtons" example call:

`Northwind.CustomerService.Delete({ EntityId: item.ID,, response => { this.refresh(); }); }`
or
`this.editItem(item.ID);`
or
```
var dlg = new Northwind.OrderDialog();
                    this.initDialog(dlg);
                    dlg.loadEntityAndOpenDialog(<Northwind.OrderRow>{
                        CustomerID: item.CustomerID
                    });
```
I hope i can explain what i need. Thank you again.

**Comment by volkanceylan** [comment]
Use PdfExportHelper.exportToPdf. It shouldnt be that hard to type and press dot for intellisense.

**Comment by alanlopcu** [comment]
Ok, thank you again. But I don't need to export my XYZgrid. I need to use my XYZreport.csthml and build my XYZreport.pdf. Like the Northwind Example / orders invoice button, again I don't need that button in my "Orders Dialog" (XYZ Dialog) rather in my Orders grid (XYZGrid) as a column identified by this XYZId per row (this.itemAt (row). MyRowId). Thanks again and again.

**Comment by volkanceylan** [comment]
So take onClick part of ReportHelper

**Comment by alanlopcu** [comment]
The only function that i can use from MyProject.Common.ReportHelper is createToolButton:

```
protected onClick(e: JQueryEventObject, row: number, cell: number): void {
   super.onClick(e, row, cell);
   let item = this.itemAt(row);
   if ($(e.target).hasClass('report-pdf')) {
      e.preventDefault();
      MyProject.Common.ReportHelper.createToolButton({
         title: 'Report',
         cssClass: 'export-pdf-button',
         reportKey: 'MyModule.XYZEntity',
         getParams: () => ({ MyRowId: item.MyRowId })
      })
   }
}
```
How can i just call his action. Or simulate this click like trigger('click') or something. Or this is just not possible? Thanks again for you help :+1: : .

**Comment by volkanceylan** [comment]
Do you how to use Copy/Paste?

**Comment by wldkrd1** [comment]
Here's what I use to add a Print button column in my grid:


protected getColumns() {
            const columns = super.getColumns();
                columns.push(
                    ({
                        field: "Print",
                        name: "Print",
                        format: ctx => {
                            return "<a class='inline-action print-row' title='Print'><img  src='/Content/serenity/images/pdf.png' />Print</a>";
                        },
                        width: 120,
                        minWidth: 120,
                        maxWidth: 120
                    }));
}
protected onClick(e, row, cell) {
            super.onClick(e, row, cell);
            if (e.isDefaultPrevented())
                return;
            const item = this.getItems()[row];
            if ($(e.target).hasClass("inline-action")) {
                e.preventDefault();
                if ($(e.target).hasClass("print-row")) {
                    Q.postToUrl({
                        url: '~/Report/Render',
                        params: {
                            key: "MyModule.XYZEntity",
                            ext: 'pdf',
                            opt: $.toJSON({ MyRowId: item.MyRowId })
                },
                        target: '_blank'
                    });
                    return;
                }
}

**Comment by alanlopcu** [comment]
Thank you wldkrd1!!! :smiley: . That worked. Thank you too volkanceylan. Have a nice day.

```
protected getColumns() {
   var columns = super.getColumns();
   columns.splice(2,0,{
   field: "Report PDF",
   name: "Report",
   format: ctx => {
      return "<a class='inline-action report-pdf' title='Report pdf'>Report this!</a>";
   },
   width: 100,
   minWidth: 24,
   maxWidth: 100
   });
}

protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);

            let item = this.itemAt(row);

            if ($(e.target).hasClass('report-pdf')) {
                e.preventDefault();

                Q.postToUrl({
                    url: '~/Report/Render',
                    params: {
                        key: "MyModule.MyEntity",
                        ext: 'pdf',
                        opt: $.toJSON({ MyIdEntity: item.MyIdEntity })
                    },
                    target: '_blank'
                });
                return;
           }
}
```
