### ISSUE TITLE
noob question : filter by duplicates

### ISSUE THREAD

**Issue by mh5775** [volkanceylan/Serenity#1507]
is it possible to apply filter on grid to find duplicate values ?

**Comment by brunobola** [comment]
@mh5775 You can easily do a view or include a boolean attribute in your entities, and then filter by it using the grid in normal ways.

**Comment by edson** [comment]
@mh5775 One simple approach, as its listing is done server side, is to add a custom boolean quickfilter, some custom listrequest and do a subquery ( select IN subquery grouped by your Desired Comparative Fields having count > 1 etc) in your listing query from repository when the parameter in request is true...

See the sample from Northwind/Orders, in particular the quickfilter for the contains in details products for guidance on how to do it.

Best Regards
