### ISSUE TITLE
Layout Improvements

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1508]
If you guys wan't your interface to have a notification icons in main windows like this:

![image](https://cloud.githubusercontent.com/assets/10889019/20648000/154d0c66-b493-11e6-89d4-cf899cb1abba.png)

Just edit the _Layout.cshtml and as an example change it to have:
 
                            <li class="dropdown messages-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="label label-success">4</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">Tem 4 Mensagens</li>
                                    <li>
                                        
                                        <ul class="menu">
                                            <li>
                                                
                                                <a href="#">
                                                    <div class="pull-left">
                                                        <img src="/Content/adminlte/img/avatar5.png" class="img-circle" alt="User Image">
                                                    </div>
                                                    <h4>
                                                        Bial Group
                                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                                    </h4>
                                                    <p>Oportunidade de realização de Estudo ?</p>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">Ver todas as Mensagens</a></li>
                                </ul>
                            </li>
                            
                            <li class="dropdown notifications-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-bell-o"></i>
                                    <span class="label label-warning">10</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">Tem 10 notificações</li>
                                    <li>
                                        
                                        <ul class="menu">
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-users text-aqua"></i> 5 novos membros registaram-se hoje
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">Ver todas as Notificações</a></li>
                                </ul>
                            </li>
                            
                            <li class="dropdown tasks-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-flag-o"></i>
                                    <span class="label label-danger">9</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">Tem 9 Tarefas</li>
                                    <li>
                                        
                                        <ul class="menu">
                                            <li>
                                                
                                                <a href="#">
                                                    <h3>
                                                        Terminar Relatório de Contas
                                                        <small class="pull-right">20%</small>
                                                    </h3>
                                                    <div class="progress xs">
                                                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                            <span class="sr-only">20% Complete</span>
                                                        </div>
                                                    </div>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="footer">
                                        <a href="#">Ver todas as Tarefas</a>
                                    </li>
                                </ul>
                            </li>

**Comment by brunobola** [comment]
In the same Way you can customize the User interface changing a Bit Like So:
![image](https://cloud.githubusercontent.com/assets/10889019/20648021/93867590-b493-11e6-8b8c-a39d54c1e072.png)


User Code:

                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="@(((UserDefinition)Serenity.Authorization.UserDefinition).UserImage)" class="user-image" alt="User Image">
                                    <span class="hidden-xs">@Serenity.Authorization.UserDefinition.DisplayName</span>
                                </a>
                                <ul class="dropdown-menu">
                                    
                                    <li class="user-header">
                                        <img src="@(((UserDefinition)Serenity.Authorization.UserDefinition).UserImage)" class="img-circle" alt="User Image">
                                        <p>
                                            @Serenity.Authorization.Username
                                            <small>Member since Nov. 2012</small>
                                        </p>
                                    </li>
                                    
                                    <li class="user-body">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Followers</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Sales</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Friends</a>
                                        </div>
                                    </li>
                                    
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="~/Account/ChangePassword" class="btn btn-default btn-flat">@Texts.Forms.Membership.ChangePassword.FormTitle</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="~/Account/Signout" class="btn btn-default btn-flat">@LocalText.Get("Navigation.LogoutLink")</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>

**Comment by Estrusco** [comment]
Splendid! Thank you very much @brunobola

**Comment by brunobola** [comment]
happy to help :)

**Comment by williamhodges** [comment]
I recommend you move this to the wiki and we can close the ticket :+1:

**Comment by brunobola** [comment]
thanks for the suggestion @williamhodges i created the page https://github.com/volkanceylan/Serenity/wiki/Layout-Improvements-%5BNotification-Icons-&-User-Personalization%5D

Is it ok like so ?

**Comment by volkanceylan** [comment]
Thanks @brunobola

**Comment by brunobola** [comment]
No problem, @volkanceylan :)
