### ISSUE TITLE
how i can set a serial number instead of column Id in the grid?

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#151]
how i can set a serial number instead of column Id in the grid?

**Comment by jsbUSMC** [comment]
You could add a SerNo property to the db as a migration, run sergen and then remove the ID property from column class.

**Comment by volkanceylan** [comment]
If serial number means row indexes like 1, 2, 3, 4... 

```cs
    public class RowIndexFormatter : ISlickFormatter
    {
        public string Format(SlickFormatterContext ctx)
        {
            return (ctx.Row + 1).ToString();
        }
    }
```

Add this to script code, build, transform templates then iny MyForm.cs

```cs
[RowIndexFormatter, EditLink]
public int RowIndex { get; set; }
```

**Comment by kuyu7766** [comment]
public class RowIndexFormatter : ISlickFormatter
    {
        public string Format(SlickFormatterContext ctx)
        {
            return (ctx.Row + 1).ToString();
        }
    }
where is this code to add? can you detailed description？ thank you very much!!

**Comment by volkanceylan** [comment]
next to yourgrid.cs on script project.

**Comment by kuyu7766** [comment]
When i rebuild the script project after adding the RowIndexFormatter  class . The script project will show error about "  “System.ComponentModel.DisplayNameAttribute” in “d:\MyPro\teaRunState\packages\Serenity.Script.1.9.5\lib\net2\Serenity.Script.UI.dll” and “c:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll”  at the  same time. serenity.Script\Northwind\Note\HtmlBasicContentEditor.cs "  

i use vs2013

**Comment by volkanceylan** [comment]
Remove System reference from script project. Use copy paste to create files, otherwise VS will do this always.

**Comment by kuyu7766** [comment]
THANK YOU。 but when i add this code.
      [RowIndexFormatter, EditLink]
        public int RowIndex { get; set; } iny MyColumns.cs
and run the application.  the whole grid and  quickSearch will not display , only show "New" "Refresh" Button on page

**Comment by volkanceylan** [comment]
See console for errors

**Comment by kuyu7766** [comment]
The column name 'RowIndex' is invalid

**Comment by volkanceylan** [comment]
Don't add it to row, just columns

**Comment by kuyu7766** [comment]
if just add columns the grid and quicksearch will not display,only show "New" "Refresh" Button on page. and no console for errors

**Comment by volkanceylan** [comment]
I don't know, maybe you messed with something else in page.

**Comment by kuyu7766** [comment]
Thank you very much.  i messed "public" in   class RowIndexFormatter.

**Comment by MaziarSangi** [comment]
> next to yourgrid.cs on script project.

Hi
Where is **script Project**?

**Comment by amirkian** [comment]
you said add this 
`
    public class RowIndexFormatter : ISlickFormatter
    {
        public string Format(SlickFormatterContext ctx)
        {
            return (ctx.Row + 1).ToString();
        }
    }
`
 next to yourgrid.cs on script project.
![image](https://user-images.githubusercontent.com/19525693/96548663-1ecf0480-12bb-11eb-953f-33a5a241592e.png)

but there is no yourgrid.cs on my project , I made a file named it FormatterContext and inside it I have
`
namespace Vision1.LifePlus {
    @Serenity.Decorators.registerFormatter()
    export class RowIndexFormatter  implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {
            
            return (ctx.Row + 1).ToString();
        }

       
      
    }
}
`
but it is unable to find row.where is the problem?!

**Comment by Vinith-kumar47** [comment]
> public class RowIndexFormatter : ISlickFormatter { public string Format(SlickFormatterContext ctx) { return (ctx.Row + 1).ToString(); } } where is this code to add? can you detailed description？ thank you very much!!

it is not working for me. Can you please explain how you add this in your project?
