### ISSUE TITLE
About TextualField attribute...

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1510]
Dear guys,
I've a doubt about the TextualField attribute...when is really neeeded?
For example in the OrderRow there is an employee lookup with TextualField attribute, but why such information isn't inferred from the NameField of the EmployeeRow?
Sorry if it's an already answered question, but I tried both to check the sources and old issues and nevertheless I still have some doubts...

Thank you very much for your answers/feedbacks
Bye

**Comment by volkanceylan** [comment]
It's used to determine related ID field, given textual field. When you put QuickFilter on CustomerCompanyName for example, it is how it determined it should actually filter on CustomerID and show a customer editor.

**Comment by marcobisio** [comment]
Ahh it's the other way round of what I was thinking! Ok now it's clear...

Thank you very much Volkan!
Bye
