### ISSUE TITLE
Passing information from a grid to a dialog (and from one dialog to another dialog)

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1511]
I'm trying to customize things a bit.  In certain circumstances when I click on a grid entry and open a dialog I would like to 'remember' information from that grid entry when the dialog is created, and use it to pre-populate dropdown values, that kind of thing.  Is this possible?

Also, I've seen the demo that hard-codes values when creating a new record/dialog.  I'd like to pass in some values when creating a new record from an existing dialog.  

For instance; in my Automobile dialog I have a 'Parts' tab.  I would like to have a 'create new part' button in that tab, which opens a new Part dialog-- but with the Part's associated automobile entry filled in from the Automobile dialog we're in.  In other words, somehow save the Automobile and use it in the new Part dialog.  Is this possible?

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts

**Comment by lquantz** [comment]
Yes, that's a good example but it uses hard-coded values such as 'Anton' and 'Speedy Express'.  

Is it possible to use values that are in a dialog instead?  For instance, in the Order dialog there's a button to create a new Order Details item.  When I click that button I would like to (say) use the Order's date in the new Order Details record.  Is that possible, to pass in a dialog's value for use in another dialog?

**Comment by volkanceylan** [comment]
I don't think you should need an example for every other topic. You access values in dialog editors with this.form.Something.value, which there is a lot of samples. If you need something from loaded entity, then its in this.entity. Please take your time and have a look around code.

**Comment by lquantz** [comment]
Hi Volkan,
Thanks for the information.  I agree you can't have examples for everything.  However it is tough to find information on certain topics at times.  

After searching the code, I notice that 'this.entity' appears to be used only in the Administration section, in the User and Role dialogs.  I had been looking through the Northwind examples, assuming that would be where samples of this kind would be.  In this case it wasn't, and that's fine, and I appreciate the pointer.  I know Serenity is an open source project and doesn't have a big budget or team dedicated to documentation.

**Comment by volkanceylan** [comment]
Yes docs are not enough, partly because of resources, and partly because not many actually read them. even if i write something in guide, faq, wiki, prior issues, people still ask same questions. Also i think reference guides are not so useful unless they sample where and how to use some member.

**Comment by slang123** [comment]
If anyone should stumble upon this. The trick is to create a property in the grid that you are using in your (parts)tab. And then set that property value when opening the main (Automobile) dialog.
