### ISSUE TITLE
How to implement 'Import from Excel' function on Detail Table?

### ISSUE THREAD

**Issue by freddiezhou** [volkanceylan/Serenity#1512]
Hi,

Could you please advise how to add the function 'Import from Excel' on Detail Table, when use Master-Detail? Thank you.

![test](https://cloud.githubusercontent.com/assets/23111403/20661488/f79922a2-b589-11e6-8a5c-6bb47279c694.png)

**Comment by volkanceylan** [comment]
Write a custom service method returning imported entities instead of inserting them. Then append them with view.SetItems

**Comment by freddiezhou** [comment]
Thanks for your guidance. I had created customer service as below, and it works & can insert items from excel. 

But one issue is the grid not refresh the data which use 'view.setItems' inserted, after ExcelImportDialog closed.

```
                    var dialog = new CodItemsExcelImportDialog();

                    dialog.element.on('dialogclose', () => {
                        CodItemsService.ExcelImport({
                            FileName: dialog.dialogTitle
                        }, response => {
                            this.view.setItems(response.InsertItems, true);
                        });
                     
                        this.refresh();
                        dialog = null;
                    });
                    dialog.dialogOpen();
```

**Comment by freddiezhou** [comment]
Solved it by add 'nextId++', and works ok. Thank you.
     **for (var x of response.InsertItems) {
          (x as any).__id = this.nextId++;}**
    this.view.setItems(response.InsertItems, true);

**Comment by freddiezhou** [comment]
Solved it by add 'nextId++', and works ok. Thank you.
     **for (var x of response.InsertItems) {
          (x as any).__id = this.nextId++;}**
    this.view.setItems(response.InsertItems, true);

**Comment by bernah77** [comment]
Can you publish the complete example?
