### ISSUE TITLE
Column Picker Improvments

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1514]
When we have a huge DataTable with a lot of columns, it is difficult to search for the comuns we want because this dialog don't have a paging system nor a search mechanism, I think this is a musty have, what you guys think ? 

Here is a print of this situation:
![image](https://cloud.githubusercontent.com/assets/10889019/20667348/b9e38624-b560-11e6-9ee4-90bc75771b19.png)

![image](https://cloud.githubusercontent.com/assets/10889019/20667360/c8784a4e-b560-11e6-843f-a3eff5e96c34.png)

**Comment by edson** [comment]
I had this problem, but you can easily style its dialog css... The search works fine for me, but if you want to improve it, would be great for us.
```

.s-ColumnPickerDialog {
     > .size { width: 690px; height: 550px; }
}
```

**Comment by volkanceylan** [comment]
> this dialog don't have a paging system nor a search mechanism

there is a search box on top left

**Comment by brunobola** [comment]
Humm, for now i'll style it, but if i have some time will try to make it more paging style.
Thanks @volkanceylan  and @edson

**Comment by shakazulu89** [comment]
if anyone runs across this for me the css property i had to change was this property in serenity.css:
.s-ColumnPickerDialog .columns-container
