### ISSUE TITLE
Noob Question: Implement a Service Request(AJAX) to MVC XYZController(In file XYZEndPoints.cs)

### ISSUE THREAD

**Issue by reuwarwema** [volkanceylan/Serenity#1515]
Ping. I have three tables
 
[VehicleDetails]
ChasisNo(PK)
RegNo
RegistrationId(FK)

[ApplicantDetails]
RegistrationId(PK)

[FacilityDetails]
FacilityId(PK)
ChasisNo(PK)
FacilityStatus(int)

I'd like to iterate through dbo[Facility] using an ajax and display each returned record(irrespective of its tenantid).

I have a Textbox "searchText" on the dashboard and I want all tenants to search either by RegistrationId/ChasisNo/RegNo and return facility/facilities that have any of the "searchText"

**Comment by volkanceylan** [comment]
Call list service, or write a custom service. MyService.List(....)
