### ISSUE TITLE
Google Maps Editor - Simple Sample

### ISSUE THREAD

**Issue by edson** [volkanceylan/Serenity#1516]
Hi, @volkanceylan . I was thinking of implementing a google maps editor as a basic sample in Serene project... Do you already have something like that?

If not, do you have any advice for doing this in the right way, before I do something awkward to the Sample? :-)

Thanks a lot.

Best Regards

**Comment by volkanceylan** [comment]
There is a GoogleMap widget, and i'll add a sample sooner or later. Anyway pull requests are always welcome.

**Comment by edson** [comment]
Ok.. I'll take a look at the widget and code and think of something to work on.

 Thanks @volkanceylan
