### ISSUE TITLE
Create an entity Row only server side (no .ts file)

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1518]
There is a way to create a row class without creating the corresponding Row.ts when trasform T4 templates?

I have entities that are used only server side and never client side.

**Comment by volkanceylan** [comment]
Currently that's not possible, unless you put them in a separate assembly.

**Comment by volkanceylan** [comment]
Another option is to add generated .ts file into exclude list in tsconfig.json

**Comment by Estrusco** [comment]
Perfect, thank you @volkanceylan
