### ISSUE TITLE
Multiple Column Layout for Categories

### ISSUE THREAD

**Issue by hansen168** [volkanceylan/Serenity#1519]
Hi, I'm new to Serenity. So far love it.
Is there a way to change the layout of a form, so I can put the categories' div side by side. Say, in Northwind, I want Shipping category and Ship To category side by side.

Also, I wanto to assign css class to category. How can I do that?
Thanks

**Comment by volkanceylan** [comment]
You need to do it with CSS. It is not possible to assign CSS class to category. You may do it in dialog, using jQuery and index.

**Comment by hansen168** [comment]
Do it in dialog, using jQuery and index: May I trouble you with some sample code?

Css class for category: May I request the feature? Some overload in CategoryAttribute: Category("categoryname", "cssClass"). I think that would be useful for others too

Thanks

**Comment by volkanceylan** [comment]
this.form.SomeCategory.element.closest('.category').addClass('something')

I don't think it's a priority.
