### ISSUE TITLE
How to offer translate codes?

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#152]
I am from China ,and I want to offer Simple Chinese Localization  and Traditional Chinese Localization to this project?How can I do this?

**Comment by enesasillioglu** [comment]
You can read this guide.
https://volkanceylan.gitbooks.io/serenity-guide/content/serene_tour/localization.html

**Comment by volkanceylan** [comment]
Add language from interface, simple...

**Comment by volkanceylan** [comment]
Also modify initial migration if you want them available on deploy

**Comment by kuyu7766** [comment]
好啊。 我也在用这个框架， 大家一起研究啊。 我qq 32361551

**Comment by volkanceylan** [comment]
If you share your translations, i can add them to Serenity and Serene.

**Comment by fzhenmei** [comment]
@ChenZhaobin 支持你，也许我也可以贡献一点微薄之力:)

**Comment by volkanceylan** [comment]
You can share translations by sharing user.texts.cz-xx.json file created under App_Data folder of your app.
