### ISSUE TITLE
Clone function for In-Memory Grids

### ISSUE THREAD

**Issue by RandalGeorge** [volkanceylan/Serenity#1520]
I have attempted to use the Clone function for an In-Memory Grid and find that the Save button does not work and that the applyChangesButton is hidden in the GridEditorDialog. I do not get any console errors.
Is this function not yet supported for In-Memory Grids or have I missed something?

Thanks for any assistance provided.

**Comment by volkanceylan** [comment]
It is not supported for in-memory grids.
