### ISSUE TITLE
ReadOnly Sample - Editors still editable

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1521]
Just an observation. I noticed the ReadOnly Sample still allows editing the email address, photo and inplace adds. It doesn't save changes since it doesn't have that functionality enabled for the current grid items such as the PhotoEditor and EmailEditor but the InPlaceAdd still allows the user to edit the associated Dialogs since those dialogs are not set to read only. 

To those using the ReadOnly as a sample, note that you'll have to secure the other dialogs as well or at least hide the buttons.

**Comment by volkanceylan** [comment]
What you should secure is on server side, repository level. Save and delete buttons are hidden so user can't do anything.

**Comment by sayuga** [comment]
That is true, its always best to secure server side but I meant mostly that, display wise, having those boxes editable on screen among all the read only ones looks unbalanced. 

Regarding the InPlaceAdd buttons, I tested and noticed I was still being able to edit the related records so I was mostly just pointing it out in the event someone thought the full feature was locked.

**Comment by volkanceylan** [comment]
Yes readonly should disable those buttons, noted.

**Comment by sayuga** [comment]
I'm going to go ahead and close this since it was mostly just to let you know about it.
