### ISSUE TITLE
How to create a Grid with Custom List

### ISSUE THREAD

**Issue by u0122300** [volkanceylan/Serenity#1523]
Hi
My name is Edison and i want to show in Grid a custom list object with search (Serene Framework Style). I create this object getting the data from Oracle Database only for reading not for update/edit/delete transaction.  Do you have any sample code implement serene framework with oracle database.  

Thanks...

**Comment by williamhodges** [comment]
If I understand you correctly, you are looking for read only. Volkan has given us a sample of this located [here](https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/ReadOnlyDialog). Take a look around and see if that is what you are looking for.

**Comment by u0122300** [comment]
Hi
Thanks for answer.  My default repository belongs to SQL Server Database but I want to access some tables from Oracle Database for validation purpose.  That's I want to populate the grid. I Already create the connection string on web.config to oracle database but I don't know exactly to do use the serene framework on it to access and display the data on that grid.. I read that sergen.exe doesn't work for oracle database and I had to create manually. Any help on this its appreciate..

**Comment by williamhodges** [comment]
Let me do a little research on it and I'll get back to you. Everyone else -
feel free to jump in and help.

**Comment by edson** [comment]
Hi, @u0122300 Where did you read that sergen doesn't work with oracle?

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_work_with_other_database_types.html

The sample already works with more than one connection string. There is the default and Northwind keys... Take a look around sample, guide, etc for more intel on how to work with it.

Best Regards

**Comment by u0122300** [comment]
[SerenityDeveloperGuidePage224.pdf](https://github.com/volkanceylan/Serenity/files/620887/SerenityDeveloperGuidePage224.pdf)
 Here in this page says Sergen doesn't works with oracle Serenity Developer Guide

**Comment by edson** [comment]
Yes, indeed. I corrected that a few seconds after I've sent it. 

See my answer again. Unless you get stuck with something related to a db oracle behavior, I hope It helps. In fact, creating your own rows is just... boring, but it's not that slow... but sometimes, correcting db old fashioned designed names is just overboring. :-)

Best Regards

**Comment by u0122300** [comment]
Hi

When  I execute sergen.exe with the Oracle Connection String configured in web.config its display the following error message.

![sergenerror](https://cloud.githubusercontent.com/assets/9947061/20752914/333fefa6-b6da-11e6-8911-c7c5ca204b92.PNG)
The created connection string its all ready tested and interact with Oracle Database.

 <add name="ConnectionString" connectionString="DATA SOURCE=150.1.36.131:1521/PROD;PASSWORD=****;PERSIST SECURITY INFO=True;USER ID=IGTXY"
      providerName="Oracle.DataAccess.Client" />

**Comment by edson** [comment]
Yes. It does not work. You have to write your own row.cs, etc.

ConnectionKey("Northwind") orConnectionKey("Default")

or in services
var connection = SqlConnections.NewByKey("Default")

are for configuring that in code.

Best Regards

**Comment by volkanceylan** [comment]
As noted in guide, Sergen doesn't support Oracle
