### ISSUE TITLE
A New Multi Tenancy approach?

### ISSUE THREAD

**Issue by SpiraMira** [volkanceylan/Serenity#1526]
Hi @volkanceylan -

You mentioned in #1026 a rework of multi tenancy in Serenity.

I need multi tenancy in my biz app. A single db per user would be too expensive, even though you make some good points about modern Cloud based infrastructures making it all more cost-effective. So I'm about to use your recommended Service Behavior pattern but am wondering if you have another approach in mind (in the near future).

Regards, P

**Comment by volkanceylan** [comment]
It is multi-db or not multidb. There is no third option.

**Comment by SpiraMira** [comment]
Of course. But then what did you mean by your comment in 1026?  That was my question.

**Comment by volkanceylan** [comment]
It's topic in guide would be rewritten, and it did.

**Comment by SpiraMira** [comment]
Cool. Thanks. Sounds good to me. 
BTW, more props on your framework, almost finished your guide and it's all stitched together very well.  Highly recommendable...

P
