### ISSUE TITLE
Oracle: New entity id created did not return

### ISSUE THREAD

**Issue by tqvtqv** [volkanceylan/Serenity#1527]
I've change to use oracle database and replace Identity columns with sequence and trigger to get new id on insert.
So the Create method of Serenity.Data didn't return that value, entity Id returned is always 0.

**Comment by volkanceylan** [comment]
It works with other tables in Oracle, so find what you did wrong with your table.

**Comment by tqvtqv** [comment]
Hi volkanceylan,
In my application, it didn't return new created id on every tables that use sequence.
Do i have to configure something on entityrow id field for serenity to recognize that id uses a sequence?

**Comment by tqvtqv** [comment]
Did anyone has succeed using oracle database table with primary key triggered bay sequence, please help ???

**Comment by volkanceylan** [comment]
@tqvtqv, if you create a new Serene application and apply steps written in manual it works and properly creates sequences out of the box. And it returns inserted sequence. Dont remove Identity attribute from your ID field!

I don't know what you did in your database, and i don't have Oracle at the moment, so i can't help you more... 

It uses this code to get inserted value:

"DECLARE INSERTED__VALUE NUMBER(18); 
BEGIN INSERT INTO bla bla INTO INSERTED__VALUE; DBMS_OUTPUT.PUT_LINE(INSERTED__VALUE); END"

**Comment by tqvtqv** [comment]
@volkanceylan: the record inserted properly with sequence next value in the identity column, my problem is the returned SaveResponse.EntityId always is zero instead of the inserted id value.

**Comment by volkanceylan** [comment]
Do you read what i wrote? Put [Identity] on your column. If it still doesn't help, sorry you are on your own.

**Comment by tqvtqv** [comment]
@volkanceylan: i debugged and now can confirm to you that the inserted value didn't return with oracle sequence.
The table i tried is LANGUAGES
the following script run and print out properly inserted id
```
DECLARE
  INSERTED__VALUE NUMBER(18);
BEGIN
  INSERT INTO LANGUAGES(LANGUAGEID, LANGUAGENAME) 
    VALUES('test', 'test')
  RETURNING ID INTO INSERTED__VALUE;
  DBMS_OUTPUT.PUT_LINE(INSERTED__VALUE);
End;
```
but the following code didn't return exactly the inserted id
```
public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            long id = 0;
            var query = EntityConnectionExtensions.ToSqlInsert(request.Entity);
            string queryText = query.ToString();
            string identityColumn = query.IdentityColumn();
            if (identityColumn == null)
                throw new ArgumentNullException("query.IdentityColumn");

            queryText += " RETURNING " + SqlSyntax.AutoBracket(identityColumn);

            
                queryText = "DECLARE\r\n INSERTED__VALUE NUMBER(18);\r\nBEGIN\r\n" +
                    queryText + " INTO INSERTED__VALUE; DBMS_OUTPUT.PUT_LINE(INSERTED__VALUE);\r\nEND;";

            using (var command = SqlHelper.NewCommand(uow.Connection, queryText, query.Params))
            {
                var param = command.CreateParameter();
                param.Direction = ParameterDirection.Output;
                param.ParameterName = identityColumn;
                param.DbType = DbType.Int64;
                command.Parameters.Add(param);
                SqlHelper.ExecuteNonQuery(command);
                id = Convert.ToInt64(param.Value);
            }

            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }
```
I placed a break point at line `id = Convert.ToInt64(param.Value);` and it shows that param.Value is null so id is Zero. That why SaveResponse.EntityId always is zero instead of the inserted id value.

**Comment by volkanceylan** [comment]
So good luck

**Comment by tqvtqv** [comment]
@volkanceylan: My problem can be fix as following change of code in function public static Int64? ExecuteAndGetID(this SqlInsert query, IDbConnection connection) of namespace Serenity.Data.
from line 48 to 70
```
if (dialect.UseReturningIdentity || dialect.UseReturningIntoVar)
            {
                string identityColumn = query.IdentityColumn();
                if (identityColumn == null)
                    throw new ArgumentNullException("query.IdentityColumn");

                queryText += " RETURNING " + SqlSyntax.AutoBracket(identityColumn);

                //if (dialect.UseReturningIntoVar)
                //    queryText = "DECLARE\r\n INSERTED__VALUE NUMBER(18);\r\nBEGIN\r\n" +
                //            queryText + " INTO INSERTED__VALUE; DBMS_OUTPUT.PUT_LINE(INSERTED__VALUE);\r\nEND;";
                if (dialect.UseReturningIntoVar)
                    queryText = queryText + " INTO :" + identityColumn;

                using (var command = NewCommand(connection, queryText, query.Params))
                {
                    var param = command.CreateParameter();
                    //param.Direction = ParameterDirection.Output;
                    param.Direction = ParameterDirection.ReturnValue;
                    param.ParameterName = identityColumn;
                    param.DbType = DbType.Int64;
                    command.Parameters.Add(param);
                    ExecuteNonQuery(command);
                    return Convert.ToInt64(param.Value);
                }
            }
```
2 statement was commented out and replace by my statement that make the function work correctly with oracle 11g. I'm not sure for another version, so i post here for you to consider my code changes.

Regards,

**Comment by volkanceylan** [comment]
@tqvtqv show your ID property in your Row.cs

**Comment by tqvtqv** [comment]
@volkanceylan As i said i was debugged with table LANGUAGES and so the LanguageRow class.
```
[DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }
```

**Comment by volkanceylan** [comment]
Just change this line or try with latest commit

param.ParameterName = dialect.UseReturningIntoVar ? "INSERTED__VALUE" : identityColumn;

**Comment by volkanceylan** [comment]
Please try this:

```cs
                string identityColumn = query.IdentityColumn();
                if (identityColumn == null)
                    throw new ArgumentNullException("query.IdentityColumn");

                queryText += " RETURNING " + SqlSyntax.AutoBracket(identityColumn);

                if (dialect.UseReturningIntoVar)
                    queryText = "DECLARE\r\n INSERTED__VALUE NUMBER(18);\r\nBEGIN\r\n" +
                        queryText + " INTO INSERTED__VALUE; DBMS_OUTPUT.PUT_LINE(INSERTED__VALUE);\r\nEND;";

                using (var command = NewCommand(connection, queryText, query.Params))
                {
                    var param = command.CreateParameter();
                    param.Direction = dialect.UseReturningIntoVar ? ParameterDirection.ReturnValue : ParameterDirection.Output;
                    param.ParameterName = dialect.UseReturningIntoVar ? "INSERTED__VALUE" : identityColumn;
                    param.DbType = DbType.Int64;
                    command.Parameters.Add(param);
                    ExecuteNonQuery(command);
                    return Convert.ToInt64(param.Value);
                }
```

**Comment by tqvtqv** [comment]
With oracle, querytext must be:
```
if (dialect.UseReturningIntoVar)
                queryText = queryText + " INTO :INSERTED__VALUE";
```
Otherwise, param.Value will be null.

**Comment by volkanceylan** [comment]
Well if i remember right it only worked after a certain Oracle version so thats why i had to do that workaround and i am pretty sure it was working. And some users requested this dialect and they must be using it and having no problems unlike you. I will not accept your change. You are free to fork and write your own Serenity. I lost enough time with Oracle and you and i wont lose another second. Bye.
