### ISSUE TITLE
onDialogOpen() breaks grid in Dialog

### ISSUE THREAD

**Issue by csteppe** [volkanceylan/Serenity#1528]
I used  the override onDialogOpen() in my Dialog.ts file . Once the dialogue opens I need to get a value from the form and do something - in this case hide a button.

```
protected onDialogOpen() {
           
            var claimId = $("input[name=CustomerProductClaimId]").val();
            if (claimId == "") {
                $('.notesRow > .s-DataGrid > div.grid-toolbar.s-Toolbar.clearfix').hide();
            }
        }
```

Once I add this code no data loads in the grid and once I take it out everything works fine.

**Comment by reach2rv** [comment]
Hi,
I am facing the same issue. How to resolve this.

**Comment by stixoffire** [comment]
@reach2rv , @csteppe 

For others :

call super.onDialogOpen(); first before your code - when you override you should call the base code , then your code.

```
protected onDialogOpen() {
           super.onDialogOpen(); 
            var claimId = $("input[name=CustomerProductClaimId]").val();
            if (claimId == "") {
                $('.notesRow > .s-DataGrid > div.grid-toolbar.s-Toolbar.clearfix').hide();
            }
        }
```
