### ISSUE TITLE
IIsActiveRow is not working as expected

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#1529]
I followed this link [http://serenity.is/demo/Administration/User](url) to implement the show/hide inactive records functions. Howerver, it does not work, and the link sample is not too.

**Comment by volkanceylan** [comment]
while (true) do it is for deleted records not inactive records

**Comment by PanChenhao** [comment]
Hello, Volkanceylan, I meet the same problem with @KlynkC .  Could you explain more detail about this issue? @volkanceylan

**Comment by PanChenhao** [comment]
#1495
