### ISSUE TITLE
Show multiple selections in columns

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#153]
I have added multi-select as the example shows. However, in the example, the multi-select is only saved in the form for each entity. When I try to display the multiple selections in a column, it doesn't appear. There are no console errors, and when I view the XHR payload, the column where my list is defined is part of the `IncludeColumns:`. I get a HTTP 200 status code for the XHR. When looking at the response data, there is no data for my list sent. Do I need to define a foreign key attribute on top of the multiselect attribute in order for Serenity to resolve my list data? Thank you for your help.

**Comment by volkanceylan** [comment]
If you are using a List<int>, you can't show this multi select simply as in SQL it is not possible in a performant way. It is possible to use FOR XML and parse returning string, but it is a bit complicated. For now, override on return method of your list handler, traverse entities, and select these related rows with IN critieria.

**Comment by jsbUSMC** [comment]
Ok. Thank you very much for your guidance.

**Comment by swordz36** [comment]
I am using a CustClassField<List<Int32>> for the collection from the multiple select control but I do not follow your comment about using XML.
