### ISSUE TITLE
Editor  option  undefined 

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#1530]
I find option in Editor.ts not work right:
I do a test below:
1.update to version 2.6.3.0
2.change Northwind.ShipperForm;
![AltText](https://snag.gy/LQYgKG.jpg)
3.change Northwind.PhoneEditor;
![AltText](https://snag.gy/AnUj03.jpg)
![AltText](https://snag.gy/p93eH8.jpg)
4.ctrl+F5 open this page and try to open dialog,I get
![AltText](https://snag.gy/DuxpXw.jpg)

and my other custom editors does not work right either,

**Comment by volkanceylan** [comment]
Well it works on pretty well on my side
There is no such change in 2.6.3.0, check what you have broken.

**Comment by tky753** [comment]
@volkanceylan  I think I find out why. the opnion is set value  later than **constructor** function.
I check value in **set_value**:
![AltText](https://snag.gy/kSVB0G.jpg)
then it works well
![AltText](https://snag.gy/2PcbTn.jpg)

**Comment by volkanceylan** [comment]
Oh, of course it is set after constructor :)

**Comment by volkanceylan** [comment]
Unless your constructor uses an option parameter, and multiple is there

**Comment by tky753** [comment]
yes , I think I will use an option insted, sorry for my stupid.

**Comment by wirble** [comment]
@tky753 I having this same issue not sure why it's undefined, were you able to figure it out?
