### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by p1099** [volkanceylan/Serenity#1532]
How to compare using booleaneditor :(

            var concursos = new List<ConcursoEstudoRow>();

            using (var connection = SqlConnections.NewFor<ConcursoEstudoRow>())
            {
                var cc = ConcursoEstudoRow.Fields;
                concursos = connection.List<ConcursoEstudoRow>
                (
                    c => c.SelectTableFields()
                    .Select(cc.Id)
                    .Select(cc.Codigo)
                    .Select(cc.Descricao)
                    .Select(cc.EntidadeExternaId)
                    .Select(cc.Nacional)
                    .Select(cc.Internacional)
                    .Select(cc.Regional)
                    .Select(cc.Notas)
                    .Where(cc.TipoConcursoOutro == true)
                );
            }
            return concursos;

**Comment by volkanceylan** [comment]
== 1

**Comment by p1099** [comment]
thanks @volkanceylan  :)
