### ISSUE TITLE
SERGEN : BUG REPORT: Multiple Table  misclassifies Modules 

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1537]
When using SERGEN: I had two modules to create, JobList and JobListAdmin
The first JobList I select some tables (Multiples Tab) from the Database 
I Set 
_ModuleName = JobList
PermissionKey = User_
and it runs and creates everything just fine. 

Now on to my Second Module:
I then select different tables to be in JobListAdmin so I set my Module Name to JobListAdmin and My 
_ModuleName = JobListAdmin
PermissionKey = Administration_

 If I UNselect one of those tables - the values in 
_ModuleName
PermissionKey_

Reverts to Previous Setting for JobList.

If I then were to set the 
_ModuleName = JobListAdmin
PermissionKey = Administration_

 - ONLY the first Table is classified correctly - the others are classed as the Previous JobList Module with those permissions.

Editing the SERGEN CONFIG FILE the behaviour is the same only the first table modules are created with the correct classification. The others follow the pattern of the previous Module.

**Comment by sayuga** [comment]
Are you running Sergen for each module one after the other before rebuilding?I've come to learn that with Sergen it's best to upload the first run, perform a rebuild then re-run Sergen.

**Comment by volkanceylan** [comment]
I'm going to remove multiple option

**Comment by stixoffire** [comment]
@volkanceylan and @sayuga - yes I run it, rebuild and then try to run the next. 
The first run of Multiples works fantastic! 
After that I must simply run on individual tables. I think what is happening is that Sergen is not mapping out the ModuleName and PermissionKey in its iteration of the tables - it is reading in from the config file on each iteration - and somehow gets out of sync (perhaps because the table parameters do not exist in the sergenconfig file on this second run - so it just uses what it found previously (old value) instead of accepting my inputs.

I like the multiple option on first run (would hate to see that go away.) - but after that it is best to only do single tables. 

If I get some time - I will try to look at it and see if I can find the source of the bug in order to get it fixed. I believe it is in Serenity.CodeGenerator .

**Comment by volkanceylan** [comment]
This is not a bug. It works as expected. Parameters are saved among the table. Multiple doesn't mean use these parameters for all of checked tables. It uses what you set manually in single tab for that table. Sergen works in single table mode. Multiple was added by a pull request and UI is not so intuitive as you still need to enter table params one by one. Average Joe doesn't understand what's going on. So i'll remove that functionality. Use one by one.
