### ISSUE TITLE
[Temporary Fix] for Select2 label/focus problem - Quickfix

### ISSUE THREAD

**Issue by edson** [volkanceylan/Serenity#1538]
Hi, all.

 I don't know if you have noticed, but select2 has a bug when we try to focus in its element. You can test it by clicking the label for any lookupeditor/select2editor and it will try to focus to the input element that's hidden on top screen/dialog.

Even the newest version of select2 has this problem not yet fixed.
https://github.com/select2/select2/issues/4580

For example, click here at serenity.is/demo:
![image](https://cloud.githubusercontent.com/assets/62490/20736478/ee45e4ba-b68d-11e6-9801-5e639d54d91b.png)

And it will bring you here:
![image](https://cloud.githubusercontent.com/assets/62490/20736504/209aaacc-b68e-11e6-9015-9677434f7f39.png)

**So... Here is a quickfix... but you will have to add it to your dialog's constructor as its elements are dynamicly created and it is just adding a focus handler to use the select2('focus').**

`this.element.find('.select2-offscreen').focus(function () { ($(this) as any).select2('focus'); });`

Best Regards

**Comment by edson** [comment]
You can do a similar approach if you don't need it in dialog.
I think I'll keep this open for a day, in case anyone needs it,

**Comment by volkanceylan** [comment]
Hmm i didnt notice it before. I think we can fix it with some code in property grid. Need to test.
