### ISSUE TITLE
How to alert message in Controller?

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#1539]
How to alert message in Controller?
This method can alert a message
throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);

But I don't want to throw an Exception.Only alert a message.

**Comment by awesomegithubusername** [comment]
You can start with this
```javascript
 Q.serviceCall({
                    url: Q.resolveUrl('~/Account/Login'),
                    request: request,
                    headers: headers,
                    onSuccess: function (response) {
                        var q = Q.parseQueryString();
                        var returnUrl = q['returnUrl'] || q['ReturnUrl'];
                        if (returnUrl) {
                            window.location.href = returnUrl;
                        }
                        else {
                            window.location.href = Q.resolveUrl('~/');
                        }
                    },
                     onError: function (response) {                                             
                              Q.notifyError(Q.text('Invalid username or password!'));<----------
                     },
                });
```

Keep in mind that the AuthenticationError isn't the only exception that could be thrown in the login method.

![github](https://cloud.githubusercontent.com/assets/13295503/20796627/44d98224-b7d7-11e6-9325-8f8ea16af9c0.png)

**Comment by VictorTomaili** [comment]
> Keep in mind that the AuthenticationError isn't the only exception that could be thrown in the login method.

You can throw any exception with message from controller. After that;

```ts
    onError: function (response) {                                             
        Q.notifyError(Q.text(response.Message)); //check response object from console
    }
```

**Comment by awesomegithubusername** [comment]
@VictorTomaili yeah you can do that, but be careful not to expose too much info about your app ( connection strings, table schemas...that could be included in the exception message stack).

**Comment by volkanceylan** [comment]
Create your own response class deriving from ServiceResponse, ListResponse etc. and a message property, use and show it on client side.
