### ISSUE TITLE
Update to FontAwesome V4.5

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#154]
Hi JaiQ,

John Ranger here again :-)

I would like to use some of the new Icons which are provided within fontAwesome 4.5 (e.g. the USB icon).

I have seen that Serenity (V1.9.5) currently uses FA V4.4.0. Is there any specific reason why Serenity stays on V4.4.0 or could you include FA V4.5 in one of your next Serenity updates?

(I don't like to update this on my own because then I am out of the Serenity Standard packages versions).

Thanks again for your great work.

With Kind regards,

John.

**Comment by volkanceylan** [comment]
You can update manually. It wont cause any problems. I updated last week, will do it with next version too.

**Comment by volkanceylan** [comment]
https://www.nuget.org/packages/FontAwesome/

This is the package i'm using and it's latest version is 4.4.0 unfortunately.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your valuable Feedback.

with Kind regards,

John
