### ISSUE TITLE
Load grid records based off UserId

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1540]
I have a new hire row and what I can't seem to figure out is how to load the grid and only load the record where the UserId matches that of the UserId that is signed in.

My goal is the following

- If the user has the permission (flag) of NewHire
- When they go to the NewHire section, the NewHireGrid only loads the records where NewHireRow.UserId matches the current logged in UserId
- If the user does not have the permission (flag) of NewHire, then it loads all records.

Is this possible?

**Comment by edson** [comment]
See https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/making_roles_multi-tenant.html for the listhandler guidance

You can have the current userid with  Authorization.UserId

Best Regards

**Comment by williamhodges** [comment]
Thank you @edson I'll take a look at it now.

**Comment by williamhodges** [comment]
I looked at this but for some reason I can't figure it out.

**Comment by edson** [comment]
Hi, @williamhodges .

Well, If I understood your goals, you would be doing something like this in NewHireRepository:

```
private class MyListHandler : ListRequestHandler<MyRow>
{
    protected override void ApplyFilters(SqlQuery query)
    {
        base.ApplyFilters(query);

        var user = (UserDefinition)Authorization.UserDefinition;
        if (Authorization.HasPermission(PermissionKeys.NewHireFlag /*"NewHire:User etc"*/))
            query.Where(fld.UserId == user.UserId /*or Authentication.UserId*/);
    }
}
```

So when user has that authorization permission, it applies the filter for listing rows with row.userId == currentLogged.UserId. If he does not have it, it will not filter and shows everything...

You should do that to RetriveHandler too overiding PrepareQuery so he can't retrieve UserId!=his.UserId on console, postman, ajax endpoint...

Hope it helps.
Best Regards

**Comment by williamhodges** [comment]
I will try this when I get back to the server. I feel like that will be the
solution! If that works and everything I will write up a wiki article and
cite your answer! Thank you sir!!

**Comment by williamhodges** [comment]
I'm going to close this and then wiki it with your permission @edson

**Comment by edson** [comment]
sure @williamhodges .

Glad it helped. :-)

Best Regards

**Comment by williamhodges** [comment]
So I thought that I had it.. this is what I have in the MyListHandler.

`private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);
                var user = (UserDefinition)Authorization.UserDefinition;
                
                if (Authorization.HasPermission(PermissionsKeys.NewHire))
                {
                    query.Where(fld.UserId == Authorization.UserId);
                }                

                else if (Authorization.HasPermission(PermissionsKeys.GeneralAccess))
                {
                    return;
                }
            }
        }`

If I'm logged in as the admin, I can't save a new entry nor can I see all entries. If I'm logged in with someone who has 'GeneralAccess' I should be able to see all entries, however I can't.

Do you know what I'm doing wrong @edson ? Thanks again for your help!

**Comment by edson** [comment]
Hi @williamhodges 
Have you checked if the ones with GeneralAccess does not have the NewHire granted?
You would have to design what is desired... and how your users permissions should behave... For admin, I supose you are granting all permissions... so if it has NewHire, you would only check that in the code you provided...

It seems that you have a problem with precedence for permissions... 

Maybe you should check GeneralAccess first then NewHire...

something like:

```
 if (!Authorization.HasPermission("Administration") )  {
           if (!Authorization.HasPermission(PermissionsKeys.GeneralAccess))
            {
                if (Authorization.HasPermission(PermissionsKeys.NewHire))
                {
                      query.Where(fld.UserId == Authorization.UserId);
                 }        
            }                
 }
```
           
Probably you have for your ReadPermission in row.cs set to both GeneralAccess|NewHire, so you would only have one or both cases when you got to applyfilters, as it evaluates this permission first and would deny access if it does not have it... Unless offcourse it is admin, as it is a literal in PermissionService.cs and it is always allowed... But if you flagged it with GeneralAccess and NewHire, you would still access and filter by it, in the code you provided...

Best Regards

**Comment by williamhodges** [comment]
While I got the filter permission to work with what you provided (thank you so much by the way!), if the user has the newhire flag they cannot open the record dialog. They have the right permission to open the file. Any idea on what I'm doing wrong?

**Comment by williamhodges** [comment]
Found the issue. Thank you again for your help!
