### ISSUE TITLE
How to Pass Data from Panel to Grid

### ISSUE THREAD

**Issue by okowiro** [volkanceylan/Serenity#1542]
I have this input form with 4 fields....and the search button when clicked calls a function in the EndPoint which returns a List Response. My question is how do i get the List Response result set to display in the grid below?

See attached screenshots..
Panel

<img width="999" alt="screen shot 2016-11-29 at 9 59 04 pm" src="https://cloud.githubusercontent.com/assets/22594794/20739371/8f32992c-b67f-11e6-92e7-27d242ceb949.png">

Grid

<img width="1012" alt="screen shot 2016-11-29 at 9 59 50 pm" src="https://cloud.githubusercontent.com/assets/22594794/20739378/9b070508-b67f-11e6-91c9-cd0a76fa6056.png">

**Comment by okowiro** [comment]
Marco Bisio

**Comment by volkanceylan** [comment]
grid.view.setItems(list, true)
