### ISSUE TITLE
Disable authentication on some pages, only for local network requests

### ISSUE THREAD

**Issue by mirokulket** [volkanceylan/Serenity#1544]
Hello,
Though this is more of a .net issue, maybe there is a "serenity way" of doing this:
I want to allow local network (intranet) users to access a specific page on my website without authentication.

I have found I could do this with `<location> ` tag in config file ([here](https://forums.asp.net/post/2085285.aspx)), but this would also allow internet users to access the page without authentication.

**Comment by volkanceylan** [comment]
There is no Serenity way. You might try windows auth mode but not sure.
