### ISSUE TITLE
Child entries should not be deleted when IIsActiveDeletedRow is used for parent Row which is being deleted

### ISSUE THREAD

**Issue by mkoval-ua** [volkanceylan/Serenity#1546]
I have LinkingSetRelation and MasterDetailRelation fields on a Row which is IIsActiveDeletedRow. I expect that it should not delete child rows in that case. So Undelete will recover Row properly. But actually it deletes child rows so they disappear on deleted Row dialog as well as is not restored when I Undelete the Row. 

It does not help even if I use IIsActiveDeletedRow for child rows as it marks them as deleted and there might be present some other child records which were deleted earlier so it's make them hard to distinguish if I would want to restore child rows on AfterDelete.

**Comment by volkanceylan** [comment]
You need to write your own LinkingSetRelation in that case

**Comment by volkanceylan** [comment]
Sorry i understood what you mean now, you say it LinkingSetRelation should do nothing on delete if master is IIsActiveRow

**Comment by mkoval-ua** [comment]
Yes exactly. And MasterDetailRelation as well.

**Comment by mkoval-ua** [comment]
I think that it should IIsActiveDeletedRow - not just IIsActiveRow. Because when you implement IIsActiveRow it does not prevent record from deletion unlike IIsActiveDeletedRow which actually marks record as deleted

**Comment by volkanceylan** [comment]
Yep i meant that

**Comment by volkanceylan** [comment]
Fixed with da1b0134ecd96a52b9069b1953de48eef9874793, will go 2.6.4

**Comment by mkoval-ua** [comment]
Thank you a lot, Volkan! You are the best!!!
When 2.6.4 is going to be published?
