### ISSUE TITLE
How to use stored proc in SaveResponse Create endpoint?

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#1549]
Hi to All,
   I have a problem implementing a stored procedure in SaveResponse Create,
I'm able to call the sproc but it insert twice in the database.

I think because of my wrong code. Can someone help me how to
properly do this. I already search for any solution in the issues but only 
for ListResponse available. thanks for any help!

here is my sample code. I have a special function in my stored proc 
that will automate the TiketID, just like this T1600001

` [HttpPost]
        public SaveResponse Create(SaveRequest<MyRow> request)
        {
            using (var connection = SqlConnections.NewByKey("Default"))

            using (var uow = new UnitOfWork(connection))
            {

                uow.Connection.Execute("CreateTicket",
                                          param: new
                                          {

                                              @fkid = request.Entity.TUserId,
                                              @catid = request.Entity.CategoryId,
                                              @status = request.Entity.TStatus,
                                              @desc = request.Entity.Description,
                                              @refid = request.Entity.RefId

                                          }
                                          , commandType: CommandType.StoredProcedure);

                var result = new MyRepository().Create(uow,request);
                uow.Commit();
                return result;
            }`

**Comment by volkanceylan** [comment]
Remove line with new MyRepository().Create(uow,request), replace last line with return new CreateResponse

**Comment by alex-444** [comment]
Thanks @volkanceylan ! here is the final code.

`[HttpPost]
        public SaveResponse Create(SaveRequest<MyRow> request)
        {
            using (var connection = SqlConnections.NewByKey("Default"))

            using (var uow = new UnitOfWork(connection))
            {

                uow.Connection.Execute("CreateTicket",
                                          param: new
                                          {

                                              @fkid = request.Entity.TUserId,
                                              @catid = request.Entity.CategoryId,
                                              @status = request.Entity.TStatus,
                                              @desc = request.Entity.Description,
                                              @refid = request.Entity.RefId

                                          }
                                          , commandType: CommandType.StoredProcedure);

                uow.Commit();
                return new SaveResponse();
            }

        }
here is the final code.
'

**Comment by teafmartins** [comment]
@alex-444  Hi, if sp fails do you show any error alert?
Thx
