### ISSUE TITLE
Add multiple record at a time in detail grid.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#155]
Hello.
Good Evening,

How can I add multiple record (with some default value) at a time in detail grid with another Add button click event and without showing popup. So that people can edit them on later.

Thank you for your help.

**Comment by volkanceylan** [comment]
this.Items.Add(new XRow { ... });
this.Items.Add(new XRow { ... });
this.SetItems(this.Items, true);

**Comment by dfaruque** [comment]
These codes give me an error in console

uncaught exception: Each data element must implement a unique '__id' property. Object at index '0' has no identity value: {"Id":2,"ItemId":2,"ItemName":"dfsdfa","Qty":90}

:(

**Comment by volkanceylan** [comment]
Cast iten to dynamic and set it to an incrementing value

**Comment by volkanceylan** [comment]
Make nextId field in GridEditorBase protected and use it with ++

**Comment by dfaruque** [comment]
Adding this method in GridEditorBase has solved this.

        protected virtual void SetItems(List<TEntity> items)
        {
            foreach (var item in items)
            {
                item.As<dynamic>().__id = nextId++;
            }
            view.SetItems(items, true);
        }

**Comment by dfaruque** [comment]
For test purpose I have created hard coded object. But I have to retrieve them from server.

var btnAddMulti = new ToolButton()
            {
                Title = "My New Button",
                CssClass = "my-new-button",
                OnClick = delegate
                {
                    //Q.ServiceCall(new ServiceCallOptions { });???????????????????????????????
                    this.Items.Add(new OrderDetailRow { ItemId=2,ItemName="Item1",Qty=90 });
                    this.Items.Add(new OrderDetailRow { ItemId = 3, ItemName = "Item2", Qty = 34 });

                    this.SetItems(this.Items);
                }
            };
 
How can I call services? Give me an example please?

**Comment by volkanceylan** [comment]
TestGet(IDbConnection connection, string barcode), first this won't work. Put this barcode param inside an object deriving from ServiceRequest.

Then compile, transform templates, you'll have OrderDetailService.TestGet method in script side.

**Comment by dfaruque** [comment]
It is working now. 
Thanks.
