### ISSUE TITLE
Coffee Break...

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1550]
![image](https://cloud.githubusercontent.com/assets/17425690/20801808/5844c252-b7ea-11e6-800e-55cce679c133.png)

Aahahah wonderful ahahaha! :-)

**Comment by volkanceylan** [comment]
So you noticed my passion about Oracle 👎

**Comment by volkanceylan** [comment]
But there is nothing wrong about you Oracle, problem is with me :)

**Comment by marcobisio** [comment]
Tales of the explicit commit... :D :D :D

**Comment by VictorTomaili** [comment]
@marcobisio buy a coffee for @volkanceylan :smile: 
https://www.goshopier.com/ShowProduct/show_product.php?id=71898

**Comment by marcobisio** [comment]
Already working on that...I'm still "fighting" with my boss ;-)
