### ISSUE TITLE
Point of Sale (POS) screen sample using northwind db #add-sample

### ISSUE THREAD

**Issue by asadmalik** [volkanceylan/Serenity#1552]
A POS screen sample (using northwind database), will give users a chance to see how multiple interlinked controls like grid, details-view and dropdowns etc respond to changes and updates. 

Suggested feature:

- Barcode scanning
- Messages about out of stock, low stock, item on hold etc
- Payment by cash, card etc
- Current operator
- Session sale
- Touch Screen support
- etc.

Hope it helps.

Thanks,
Asad.

**Comment by stixoffire** [comment]
@asadmalik did you add the sample or are you requesting a sample ?

**Comment by asadmalik** [comment]
Requesting

**Comment by VictorTomaili** [comment]
But there is no custom something about serenity.

**Comment by asadmalik** [comment]
Sorry I don't understand what you mean @VictorTomaili :)

**Comment by VictorTomaili** [comment]
You dont need sample.

**Comment by asadmalik** [comment]
I sure don't. Serenity future users might! :) 
Anyhow...It was just a suggestion.

Keep up the GREAT work!
Asad.

**Comment by volkanceylan** [comment]
Noted as an idea, thanks.

**Comment by juliermefelix** [comment]
any news regarding this request?
