### ISSUE TITLE
AD Login Question

### ISSUE THREAD

**Issue by ProgrammerThatsBadAtMath** [volkanceylan/Serenity#1556]
I've followed your wiki document on how to implement AD and it worked perfectly. I'm working towards changing to authentication to work so that if they have an AD account and the DB account with same username it automatically signs in without a password. I am new to C# and MVC apps so I'm having trouble locating a good place in the application to implement this. In a standard asp.net page I'd be looking for either a page onload for the login page or for the code that actually calls the login form to appear... Is there a place you would recommend ?

**Comment by volkanceylan** [comment]
Sorry what i recommend and know is in that document.

**Comment by ProgrammerThatsBadAtMath** [comment]
Also, I am familiar with how to utilize the IDirectoryService to validate AD credentials and I have done the other required work such as allowing nulls for the password hash and salt database columns.

**Comment by ProgrammerThatsBadAtMath** [comment]
Ah ok, maybe you can help me locate where the decision to draw the login form occurs?

**Comment by volkanceylan** [comment]
It's standard Forms Authentication. Sorry i can't help you with auto login.
