### ISSUE TITLE
how upload images or files as a Stream

### ISSUE THREAD

**Issue by vahid211** [volkanceylan/Serenity#1557]
hi

in my project i need to attach a file(such as Image, Doc File or any things) to a entity.
now i define a field in the table with datatype varbinary(max) and i want to use Stream object in my project.
please guide me how can i upload files like Product Image field in Northwind Project.
also I read the doc guide, you used String datatype in database for image field but in my project i use varbinary datatype.

thanks for your cooperation

**Comment by awesomegithubusername** [comment]
Hi,
The uploaded files aren't stored in the database but rather in a folder location that can be set in web.config. The string field is used for the file path.

**Comment by stixoffire** [comment]
You could upload to a temp folder first and then in your repository override  before save in MySaveHandler read the file into stream and assign to your Row.Field object.

**Comment by volkanceylan** [comment]
Currently only file uploads is possible and strongly recommended. As @stixoffire, you may do a workaround on AfterSave, or write a custom behavior. Maybe i'll add a sample later.
