### ISSUE TITLE
dialog.ts message

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1558]
Merhaba bir sorum olacaktı; 
TerritoryDialog.ts 'de yazan aşağıdaki kod çalışıyor.Fakat benim sergen ile oluşturduğum form için  citydialog.cs'de aşağıdaki kodun aynısını kopyalayıp     ,       Q.notifySuccess(this.form.**CountryID**.value.toString()); olarak değiştirdiğimde , gridlist geliyor fakat linke tıklayınca popup form dahi açılmıyor, mesaj da vermiyor Nerde hata yapmış olabilirim?

constructor() {
            super();

            Q.notifySuccess(this.form.RegionID.value.toString());

        }

**Comment by stixoffire** [comment]
Izgara listeniz hangi formu çağırıyor, yazım hatası hata ayıklamayı etkinleştirerek asp.net hata ayıklamasını ve diğer hata ayıklayıcıları işaretini kaldırarak etkinleştirebilirsiniz. Siteniz bittiğinde Internet Explorer NOT'u (Chrome veya Firefox) hata ayıklamak için F12'ye basın; hata iletisini geliştirici çerçevesinin konsol sekmesinde görebilirsiniz.
F12, krom üzerinde hata gösterebilir - ancak yalnızca Internet explorer yazım hatalarının hata ayıklama kesilme noktalarına etkili bir şekilde erişir.

**Comment by volkanturk** [comment]
çok teşekkürler , çözdüm :)
