### ISSUE TITLE
Grid View Editor

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#156]
Firstly, great template. I love it. I've just recently gotten back into programming and your well documented instruction and code have been a joy to use to bring me back into the swing of things.

That being said, I'm not quite that avidly back to coding so I'd like some help. I'm attempting to take the view of a grid created on table "Matrix" which contains about 50 columns and add buttons to the toolbar that essentially call a sub view of the same grid but displaying only specific columns. 

Example: I have columns names A through J. 

                 The default view would be: Column A through J 
                  EditView1 ButtonClick: ColumnsC, D, E, F
                  EditView2 ButtonClick: ColumnsC, A, G,H, I

I have an excel export on it already too using the Excel Export helper. So I would like to be able to use the export to pull the view in use. 

I attempted a number of things to no success. I created alternate MatrixColumn#.cs files, that are would be called depending on button call but that didn't work. If I edit the GridEditor, it edits everything. I was going to try mapping a SQL View onto an HTML but I'd like something directly interacting at the present view. 

The columns required to be called in each view are predefined so If I can build one set I should be able to build all of them from the get go. Being able to dynamically show or hide columns though would be nice. 

Any guidance is appreciated.

**Comment by volkanceylan** [comment]
If you want to switch columns in grid, use slickGrid.SetColumns(Q.GetColumns("YourColumnsKeyN")

To show different dialogs based on active columns, override EditItem, create your DialogN which uses FormKeyN then LoadByIdAndOpenDialog

**Comment by sayuga** [comment]
Thank you for the quick response. I'll give that a try and let you know how it works out.
