### ISSUE TITLE
Listing rows from stored procedure

### ISSUE THREAD

**Issue by jhirsch41** [volkanceylan/Serenity#1560]
Hi, amazing project, thank you so much for developing this. 

I had a quick question regarding how to implement a grid that is populated from a stored procedure as opposed to a table. I don't see any example in the e-book or in the northwind sample project that do this. Please let me know if this is possible.

 Thank you!
   Warm regards

**Comment by stixoffire** [comment]
@jhirsch41   Your stored procedure should return a table.
How you query the DB should not matter - it is the object returned - and a sp returns a table, if it is a joined query in the sp Just create your objects to match the stored procedure columns returned  and you should have it.

**Comment by xareas** [comment]
check this
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/StoredProcedureGrid

**Comment by dougdsank** [comment]
IS there a way to have the slickgrid paging work with results returned from a StoredProcedure. The grid fills but unable to page and get row count.
Thanks so much
