### ISSUE TITLE
Mult File Upload

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#1562]
![capture](https://cloud.githubusercontent.com/assets/728937/20866458/64c944b4-ba36-11e6-8120-21d828a42b60.PNG)

any idea why i am losing the Delete Button , this happened after restoring the database , i fi upload again a file the new files will get the delete Button

**Comment by marcobisio** [comment]
Hi @zerodev,
look at this: #1054 

Bye

**Comment by volkanceylan** [comment]
It's fixed in latest version.

**Comment by zerodev** [comment]
thanks @marcobisio  and @volkanceylan

**Comment by marcobisio** [comment]
You're welcome @zerodev
