### ISSUE TITLE
How to Save and Retrieve As Enumeration Text in the Database Table instead of Integer Value?

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1563]
I have an Enumeration - I would like to save the actual text values of the enumeration in the database table.
Currently I am displaying a string value in my column . and the row has the integer value (unfortunately this is what is saved in the db) I need to save and retrieve the text value.
Is there a declaration in serenity to allow for this, is there a special way to do it in serenity - or do I refer to the long drawn out C# way of translating text to enum ?

code is below:
```
    public sealed class ProjectRow : Row, IIdRow, INameRow
    { 

       public Status? ProjectStatus
        {
            get { return (Status?)Fields.ProjectStatus[this]; }
            set { Fields.ProjectStatus[this] = (Int32?)value; }
        }

public class RowFields : RowFieldsBase
{
  public Int32Field ProjectStatus;
}
}

public class ProjectColumns
{
        [DisplayName("Status"), Width(100), AlignCenter]
        public String ProjectStatus { get; set; }
}
```

**Comment by volkanceylan** [comment]
Your field is not an enum in that case. See select with hardcoded values sample.
