### ISSUE TITLE
Sergen and Mysql Connection fails

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#1564]
Hi,
I created a new Serene project and i try to generate a mysql datatable maintenance with Sergen.
My web.config connectionstring is as follow

   <add name="Portal" connectionString="Server=localhost; Port=3306; Database=portal;user id=root;password=123456" providerName="Mysql.Data.SqlClient" />

I installed Nuget package
PM> Install-Package Mysql.data -Version 6.9.9
I have in references Mysql.Data so I can access to Database in VStudio 2105
In folder D:\Geshotel\Visual_studio 2015\Geshotel\packages\Serenity.CodeGenerator.2.6.3\tools y have a copy of Mysql.Data.dll and a file sergen.exe.config as described in your tutorial

But when I choose my connection I get an error message as described in attached file
![image](https://cloud.githubusercontent.com/assets/24249067/20892344/c06c6aba-bb05-11e6-8a52-6b29e2807dbe.png)

I send you another attached image how tools folder is
Any help would be apreciated.
Thank you so much
Javier
![image](https://cloud.githubusercontent.com/assets/24249067/20892433/238fd21c-bb06-11e6-8609-a2443b6af6b2.png)

**Comment by volkanceylan** [comment]
I suggest you follow guide properly. That error indicates provider is not registered.

**Comment by pesnunj0** [comment]
Hi,
I found the issue, at least what happenned to me.
If i choose one existing connection in sergen (click in listbox) then it fails, but if I click the buttom new connection and I write the same then it works.
I don´t know why but it is.
Thanks

**Comment by volkanceylan** [comment]
I guess its because providerName in your web.config is wrong.
