### ISSUE TITLE
Widget.create error in IE11

### ISSUE THREAD

**Issue by manivishnupriya** [volkanceylan/Serenity#1565]
On clicking a link in left navigation panel, i'm trying to display a page that has tabs & form (instead of displaying a grid by default) like below
![image](https://cloud.githubusercontent.com/assets/20909626/20895781/c7f820e8-bae8-11e6-8709-4b6ee9c1d2e4.png)

 The code below works fine in chrome browser. But in IE11 it shows 3 tabs with no content/form elements inside the tabs.
In Console it shows syntax error on line 
**"e => e.insertAfter()."**
And a warning : "DOM7011: The code on this page disabled back and forward caching. For more information, see: http:go.microsoft.com/fwlink/?LinkID=291337"

Index.cshtml
![image](https://cloud.githubusercontent.com/assets/20909626/20895454/868583cc-bae7-11e6-9873-72ef9ab89603.png)

Please help me sorting out this issue.

**Comment by volkanceylan** [comment]
new CheckDialog().element.appendTo($('#tab_1'))
