### ISSUE TITLE
Remove revoke column

### ISSUE THREAD

**Issue by hansen168** [volkanceylan/Serenity#1567]
Say that I don't want to use Role feature in Adminstrations.
Is that possible to remove or hide revoke column in Edit User Permissions ?

Thanks

**Comment by volkanceylan** [comment]
You could, should be some simple search replace and a few changes.

**Comment by hansen168** [comment]
![hide_revoke](https://cloud.githubusercontent.com/assets/24227848/20936955/56a6c914-bc17-11e6-88f7-b87a8e32fed2.png)

Wow, it's so simple.
Just set it false in UserPermissionDialog.ts

Thanks
