### ISSUE TITLE
Do not display virtual keyboard

### ISSUE THREAD

**Issue by James-A-White** [volkanceylan/Serenity#1568]
Hello Serenity community,

I'm building an app primarily designed for mobile use. I have an editor with a single QuickFilter that has four items used to control filtering of the grid.  When the users select this dropdown, a search box is included and it causes the "virtual keyboard" to display on iPhones (and probably Android as well).  Is there a way to configure the QuickFilter so that no editor is displayed with the dropdown?

I've been hacking away at this, but still don't have an easy solution.

Second issue. When the user clicks on a menu item in the dropdown, the click event is also registered on the object that is underneath the menu, causing unwanted actions to be executed. Does anyone have any tips for either suppressing event handling while a menu is active or clearing the event queue.

Thanks!

James

**Comment by volkanceylan** [comment]
Try setting MinResultsForSearch option of Select2 a high value

**Comment by volkanceylan** [comment]
Here is a workaround i did for a customer once:

```js
var isTouchOnlyDevice = (window.screen.availWidth <= 768 || window.screen.availHeight <= 768) && ('ontouchstart' in window.window || window.window.navigator.msMaxTouchPoints > 0);
		isTouchOnlyDevice = isTouchOnlyDevice || navigator.userAgent.indexOf('iPad') >= 0;
		if (!!isTouchOnlyDevice) {
			var d = $.fn.select2.defaults;
			// -1 means never show search input, 0 means always, if you want it to be shown for example > 100 results, set it to 100
			d.minimumResultsForSearch = -1;
			Serenity.TemplatedDialog.prototype.__proto__.onDialogOpen = function() {
				this.arrange();
				$(':input:eq(0)', this.element).blur();
			};
		}
		$.fn.select2.defaults.shouldFocusInput = function(instance) {
			if (!!isTouchOnlyDevice) {
				if (!!(instance.opts.minimumResultsForSearch < 0)) {
					instance.focusser.hide();
					instance.search.hide();
				}
				return false;
			}
			return true;
		};
```
