### ISSUE TITLE
DatePicker Localization

### ISSUE THREAD

**Issue by misafer** [volkanceylan/Serenity#1569]
dear Volkan, i appreciate if you can help me with this jqueryUI customized datepicker for use in persian 👍
https://www.nuget.org/packages/PersianDatePicker/

**Comment by volkanceylan** [comment]
There is a how to in guide to use custom components.

**Comment by misafer** [comment]
i've tried to use that but there is something wrong with the help. there is no .cs file to describe the custom editor in c# classes. just a typescript class. is it wrong ?

**Comment by VictorTomaili** [comment]
.cs file is eq to ts editor file. old serenity is use saltarelle c# to javascript compiler. you can write same things in typescript.

**Comment by misafer** [comment]
dear Victor, i know about the changes in new version and use of typescript. but just try that help and see the error. in c# files it cant recognize your .ts class as well.

**Comment by VictorTomaili** [comment]
c# files compiled to javascript file. typescript files recognize javascript files. Also serverside code is need attribute for generate typescript code from *.tt files.

**Comment by misafer** [comment]
thus as you described i need to make changes in my .tt files ? thanks i try again.

**Comment by VictorTomaili** [comment]
Nope, you dont need make changes in tt files. 
this server side class generated by tt file. 

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Administration/Translation/TranslationItem.cs#L12

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Imports/ServerTypings/Administration.TranslationItem.ts

**Comment by misafer** [comment]
ok. thats right. its generated the .cs file based on .tt and .ts but not included in my project. thats the problem. thanks for your help.
