### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1571]
Hi @volkanceylan 

It's possible to donate for Serenity? And if yes, what is the link?

**Comment by VictorTomaili** [comment]
look at bottom of this page http://serenity.is/

**Comment by Estrusco** [comment]
Thank you @VictorTomaili 
I keep open this post to spam :)

**Comment by volkanceylan** [comment]
Thanks @Estrusco you are 2nd donator. So your name is also Marco. I fix mix you with @marcobisio for a second :)

**Comment by marcobisio** [comment]
Argh! So I hope to hit the 3rd place!

**Comment by volkanceylan** [comment]
Interesting thing is our donators are all contributors so far, not "users" in traditional sense. I'll try to donate you back by helping on some issues you'll have.

**Comment by Estrusco** [comment]
Thanks to you too @volkanceylan . The great work you've done so far is already very important for us: D

**Comment by marcobisio** [comment]
I totally agree with @Estrusco: despite the donations, we are "indebted" to you!
P.S. Let me know if I'm on the podium ;-)

**Comment by williamhodges** [comment]
What I'm trying to figure out is why Microsoft hasn't picked up and hired Volkan yet ;)

**Comment by volkanceylan** [comment]
Well i'm not sure anybody from Microsoft even heard or care about Serenity. I applied for BizSpark to test some integrations with Azure but someone from MS Turkey called and asked what is Serenity? They rejected application right away as i don't have a company, even though i tried to explain its for their own advantage. Clearly they have a great open source support culture. 

I would like to have an opportunity to work with @aheljsberg, who is a real genius and such a modest person to title himself as "technical fellow".

**Comment by lquantz** [comment]
Thanks for the link, just donated...didn't see it at the bottom of the page previously.

**Comment by lquantz** [comment]
Not sure if this would help, but I personally am more inclined to donate if a Paypal option is available, rather than having to use a credit card.  Just my own opinion.

**Comment by volkanceylan** [comment]
Thanks @lquantz, but unfortunately PayPal doesn't work in my country anymore. Shopier is one of a few respectable providers we can use here, which is similar to PayPal in security.

**Comment by lquantz** [comment]
Ok, good to know, Shopier works too.  Sorry to hear Paypal isn't available in Turkey anymore, I prefer to have the money taken out immediately rather than have to remember to pay the CC company at the end of the month (and watch them try to charge me interest.)

**Comment by volkanceylan** [comment]
Yes me neither but when you don't have an option. 
For those worried, here is more info on Shopier:

https://www.goshopier.com/index_en.php

They are supported by our goverment research instutite, and one of best universities here.

**Comment by mhussein67** [comment]
@volkanceylan I'm in my way to donate for this great offer. it helps me a lot to complete my project in Student enrollments and registrations in Oracle.

Thanks again

**Comment by emrekirpiksiz** [comment]
Hi Volkan,

We have Bizspark membership. I would like to support your project if you need Azure Products.

Thanks

**Comment by volkanceylan** [comment]
@emrekirpiksiz thanks, but i won't use somebody elses membership. I will probably won't use Azure or any of its services anyway.

**Comment by vinaykulkarni89** [comment]
I'm getting following error

Oops! Something went wrong with your payment. We have received a 'General Error' message from your credit card issuer bank. The best way to resolve this is to give your bank a quick call, let them know you want to proceed with the payment. If the problem persists, please try with another credit card.

Bank haven't got any notification for payment

**Comment by vinaykulkarni89** [comment]
Is the issue because my currency is INR?

**Comment by volkanceylan** [comment]
I dont know, you should probably ask your bank or shopier. Thanks for trying anyway.

**Comment by chizdamasii** [comment]
@volkanceylan i want to donate for fixing 2 major bugs with serenity. 
1) If a column has multiple string values, in excel export it shows only the id. (see Customers with multiple representatives)
2) jsPDF is not printing UTF-8 chars, if you have a fix or you can change it to pdfmake, (the ReportHelper is good, but sometimes if there are too many rows it overlaps with the column names)

What donation would be suffice to cover for your time?

**Comment by mahmuthaktan** [comment]
You should create Serenity Professional Help site with credit card payment support.

**Comment by volkanceylan** [comment]
@mahmuthaktan i'm planning on some professional support subscription options, with private forum, e-mail support, remote assistance etc. options. Still can't use PayPal :/

**Comment by brunobola** [comment]
Next month i'll donate also, keep up the excelent work.

**Comment by aksingh1979** [comment]
Do you accept bitcoins also?
