### ISSUE TITLE
Entity inheritance ?

### ISSUE THREAD

**Issue by jfdomitor** [volkanceylan/Serenity#1572]
Is it possible to use inheritance among entities. Eg. to have one generic table, repo and endpoint to store all kinds of customers. But for example (a bad one) several entities like GoodCustomerRow, BadCustomerRow etc that derives from a base entity (CustomerRow : Row). (If the answer is yes is it then possible to have language support on the top entities in the inheritance hierarchy ?

**Comment by volkanceylan** [comment]
UpdatableExtensionAttribute might help you. See customer dialog, row and how details are saved.

**Comment by jfdomitor** [comment]
OK, thanks.
