### ISSUE TITLE
Logging into console on local dev, different levels for different namespaces

### ISSUE THREAD

**Issue by mirokulket** [volkanceylan/Serenity#1573]
Hello,
Is it possible to setup the serenity logging like in Java - different levels for different classes/namespaces, file & console (debug) output for development ('Debug' mode in visual studio), etc..

Thank you

**Comment by VictorTomaili** [comment]
write your custom logging wrapper for this.

**Comment by volkanceylan** [comment]
All you need to do is to implement ILogger interface, which also accepts a source Type parameter.
