### ISSUE TITLE
Make C# Enums available for Javascript .

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1574]
As I was trying to easily manage getting my Enums into the javascript , I came across a nifty article with code. While I am going to put this piece of code in my project - I thought it was nifty enough that perhaps it can be added to Serenity. Here is the link:
[making-c-enums-available-within-javascript/](https://fairwaytech.com/2014/03/making-c-enums-available-within-javascript/)

**Comment by volkanceylan** [comment]
Serenity already transfers enums to typescript

**Comment by stixoffire** [comment]
Is there any way to make it so I can get the Enum Description Attribute via the type script ? 
I am trying to enumerate my enum descriptions so I can add it to the hardcodedvalues via  .addOption("key", "text") - but I do not see how to do this in typescript. 
Could you provide a link or an example where I can find this?

**Comment by volkanceylan** [comment]
Look source of how enum editor does it
