### ISSUE TITLE
GridEditorBase on another tab ?

### ISSUE THREAD

**Issue by jfdomitor** [volkanceylan/Serenity#1576]
Hi !

I've spent the day trying to solve this.

I have tabbed dialog but having problem with a GridEditor (extends Common.GridEditorBase). I can only get it to work as expected if I put it in the first tab (eg. on the form). Is it something more to handle when using GridEditorBase on another tab ? If I add a new inmemory record through my dialog it will not show up in the GridEditor, but if I move the editor to the first tab (and form) it works.

```
<div id="~_Toolbar" class="s-DialogToolbar">
</div>
<div id="~_Tabs" class="s-DialogContent">
    <ul>
        <li><a href="#~_TabInfo"><span>Remissvar</span></a></li>
        <li><a href="#~_TabFindings"><span>Fynd</span></a></li>
        <li><a href="#~_TabDiagnoses"><span>Diagnoser</span></a></li>
    </ul>
    <div id="~_TabInfo" class="tab-pane s-TabInfo">
        <div id="~_Toolbar" class="s-DialogToolbar">
        </div>
        <div class="s-Form">
            <form id="~_Form" action="">
                <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                    <div id="~_PropertyGrid"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>

    <div id="~_TabDiagnoses" class="tab-pane s-TabDiagnoses">
        <div class="s-Form">
            <form id="~_RemittanceReplyDiagnoseForm" action="">
                <div class="fieldset">
                    <div id="~_RemittanceReplyDiagnosePropertyGrid"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>
</div>
```

**Comment by volkanceylan** [comment]
I'm not sure what you mean by adding a record through your dialog, but need more code, from your dialog.ts etc. Btw, grid editors are not designed to be used in another tab by default. They are for in memory editing of main form fields.

**Comment by jfdomitor** [comment]
Hi !

What I would like to accomplish is exactly like the northwind order application but to have the order details on another tab. Can you give me a hint if it's best to use GridEditorBase/GridEditorDialog or EntityGrid/EntityDialog for this.

Thanks for a great product.

**Comment by volkanceylan** [comment]
Then you should better use a EntityGrid and Dialog. Just like on in orders tab of customer.
