### ISSUE TITLE
[Suggestion] Quickfilter - Int use range

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1578]
Small suggestion to the Quickfilter. It may be worthwhile to make the quick filter for Integers similar to the DateTime Quickfilter, so that it can ask for a upper and lower bound by default. At the moment it treats it like a single search box with exact match constraint. 

I ended up making my own filter lookup but it's clunky so I'm leaning more towards the Filter that is accessible through the filterable decorator.

**Comment by volkanceylan** [comment]
There is a customizing quick filters sample. I'm not sure if it should be default. There are integer fields that are not numbers in traditional sense.

**Comment by sayuga** [comment]
I did see the sample, that is essentially what I am using now. You do make a valid point regarding not all integers being traditional numbers but I think there may still be value in having a default integer range filter. maybe it's something worth adding through QuickFilterOptions. The way I'm thinking about it, the more predominant types of filters that a client user will use will be sorting through dates, traditional integers and looking for a string. 

I think of the most common filter fields used in websites like shopping sites. You usually filter quantities available, price points, filter for keywords, boolean's for has or has not's and use date range filters to see how new it is. 

Anyhow, it's just a suggestion. I am fine with what I have for now but figured I'd mention it. 

By the way, small side question while talking about non traditional integers. Wouldn't it make more sense to have the IsActiveField be a Boolean since it's essentially a 0 and 1 restricted value field?

**Comment by volkanceylan** [comment]
IsActiveField could be a boolean but IsActiveDeletedField has to be three state. So for backwards compability it has to be integer. But in database your field can be boolean, it will work.
