### ISSUE TITLE
XmlException on Code Generator

### ISSUE THREAD

**Issue by AsHaFLoki** [volkanceylan/Serenity#1579]
Hi,
I'm having a problem to use Serenity Code Generator, after I try to generate the Entity code, this message of xmlexception appears:
![2](https://cloud.githubusercontent.com/assets/17962972/20941920/f291305e-bbdf-11e6-804c-f4c5a1424baf.png)

I noticed that some of the necessary files are created, for if I try to run it again in the same project, the Kdiff will start and show some of the files are already there.

Thanks.

**Comment by volkanceylan** [comment]
Your project file looks corrupt

**Comment by AsHaFLoki** [comment]
It worked after transferring the original code to another project and running the code generator again.
Thanks
