### ISSUE TITLE
SQLQuery works but all fields in returned row are null - LookupInclude is defined on desired fields

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#158]
Hi JaiQ,

John Ranger here again :-)

Environment: Serenity upgraded to 1.9.5.

Challenge: 
I want to return a CSV delimiter [char] out of my CSVDelimiter table when given the Row ID number of that particular CSV delimiter.

--------
The Delimiter table has (among others) the following fields:

```
CSV_Delimiter_ID
Delimiter
```

--------
The CsvDelimiterRow.cs file maps this table into my serenity solution.
--------
I have the following using declared within xyzRepository.cs:
```using CSVRow = ClientManagement.Stammdaten.Entities.CsvDelimiterRow;```
--------

In the xyzRepository.cs - in "private class MySaveHandler", I have the following method (widely copied from one of your Serene methods):

------------------------------
```
            private static Char? GetDelimiter(IDbConnection connection, int DelimiterID)
            {
                var row = new CSVRow();
                if (new SqlQuery().From(row)
                    .Select("*")
                    .Where("CSV_Delimiter_ID=" + DelimiterID)
                    .GetSingle(connection))
                {

                    Console.Write(row);

                    return row.Delimiter.ToString()[0];

                }

                return null;
            }

```

The GetDelimiter method works so far that it finds the correct row (e.g. when I give a wrong Name for the field Name, it complains) but all fields (except the ID field) are null.

If I remember correctly, in one of your answers to another issue of somebody else here (or over at visualstudiogallery) you mentionned that [LookupInclude] must be defined within the relevant row.cs. I have done this within the CSVDelimiterRow.cs file but still the fields have null values instead of the desired values.

May I ask you to give me a hint in what I am missing in order to fill the other fields?

Thanks again and

with Kind regards,

John

**Comment by JohnRanger** [comment]
Sorry, I got it now.

I have to use the following select:

```.Select(CSVRow.Fields.CsvDelimiterId,CSVRow.Fields.Delimiter)```

Thanks again 

and with Kind regards,

John

**Comment by volkanceylan** [comment]
Hi Ranger, Instead of Select("*") i'd recommend SelectTableFields(). But of course selecting fields you need explicitly is better. Just use local var like "var csv = CSVRow.Fields; ....Select(csv.CsvDelimiterId).Select(csv.Delimiter)

And instead of this:

.Where("CSV_Delimiter_ID=" + DelimiterID)

.Where(fld.CsvDelimiterId == DelimiterID)

**Comment by JohnRanger** [comment]
Hi JaiQ,

thank you very much for this insight. I was already searching for the "select all fields" Approach but didn't recognize that there is a Special "Select" command for this.

The "where" command I have changed to your recommendation. Seems to me much better than hard.coding the string.

Thanks again, 

Have a nice evening and

with Kind regards,

John
