### ISSUE TITLE
Query affected 13 rows while 1 expected!

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1581]
Hi guys, i got this error:

> Query affected 13 rows while 1 expected!

 Im trying to update (edit) one row (XXX table). But in my database i have after update trigger for this XXX table. This trigger updates another rows in YYY linked table. So, 13 rows means 12 rows updated from the YYY table plus 1 row from XXX (XXXDialog).
What should i do, how can i fix this alert.

Thanks in advance.

**Comment by tvldev02** [comment]
Use SET NOCOUNT ON in trigger. same as #285

**Comment by alanlopcu** [comment]
Thank you @tvldev02 it worked! :+1: 
Used `SET NOCOUNT ON;` after my `BEGIN` trigger.
