### ISSUE TITLE
Multiple OrderDetails in DefaultValuesInNewDialog demo

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1582]
I'm trying to figure out a way to have multiple _orders_ populate in a new dialog when the grid button is selected. I have been looking at this [file](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts) most notably this part: 

```
dlg.loadEntityAndOpenDialog(<Northwind.OrderRow>{
                        CustomerID: 'GOURL',
                        EmployeeID: lauraCallahanID,
                        DetailList: [{
                            ProductID: chai.ProductID,
                            ProductName: chai.ProductName,
                            UnitPrice: chai.UnitPrice,
                            Quantity: 5,
                            LineTotal: chai.UnitPrice * 5
                        }]
                    });
```

With that, I was wondering if you could iterate through all Products if you wanted to. So basically when you press the button it opens a dialog box up with all products in the DetailList. 

My question is this, would it work if you did something like the following:

```
...
let products = new ProductRow();
...
DetailList: for (let product of products) {
                       [{
                     ProductID: product.ProductID,
                     ProductName: product.ProductName,
                     UnitPrice: product.UnitPrice,
                     Quantity: product.UnitPrice,
                     LineTotal: product.UnitPrice * 2
        }]
}
```

Would that potentially work?

**Comment by Estrusco** [comment]
You can use a function

```ts
       protected yourFunc() {
            let products = new ProductRow();
            [...]
            DetailList: addDetails()
        }

        protected addDetails(products: Product[]): XYZRow[] {
            let details = new Array<XYZRow>();

            for (let p of products) {
                  details.push({ ProductID: p.ProductID, etc... });                  
            }
            return details;
        }
```

**Comment by williamhodges** [comment]
Thank you @Estrusco, I'll test it out tonight. Typescript is an amazing tool.

**Comment by williamhodges** [comment]
When I try to do the `DetailList: addDetails()` part it states that it can't find `addDetails`. Is there a special spot I need to place the protected function?

**Comment by Estrusco** [comment]
Write this.addDetails()

**Comment by williamhodges** [comment]
Thank you @Estrusco
