### ISSUE TITLE
Not able to login with changed password until restart the application

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#1583]
Hi 

   I have created my custom functionality to change password 
   ```` var salt = Membership.GeneratePassword(5, 1);
            var hash = SiteMembershipProvider.ComputeSHA512(password + salt);
            var userId = int.Parse(Authorization.UserId);
            int stat = dataService.ChangePassword(userId, hash, salt); 
 ````

  With the help of stored procedure i am updating hash and salt.

 But i am not  able to login with changed password until restart the application.

How to solve this issue.

**Comment by volkanceylan** [comment]
Use UserRepository.Update() to change password, not stored proc.  TwoLevelCache.ExpireGroupItems(UserRow.Fields.GenerationKey) another option.
