### ISSUE TITLE
Catching any exceptions - showing custom error messages in red message box

### ISSUE THREAD

**Issue by mirokulket** [volkanceylan/Serenity#1584]
Hello,
how can I display custom error message in case of some unexpected (and/or) system exception, e.g. while I had DB server unavailable I got this error message (in a red box on top) on GUI: "İsteğin işlenmesi esnasında bir hata oluştu!"
 (exception thrown from EndpointExtensions.cs)

Thank you

**Comment by volkanceylan** [comment]
It hides exception details in production as usual with ASP.NET, though error message should be in English.

Try <customErrors mode="Off" />

**Comment by mirokulket** [comment]
Can I handle these errors and display something different?

**Comment by volkanceylan** [comment]
There is Exceptionless integrated. It's accessible from navigation. For handling exceptions, see .NET docs.
