### ISSUE TITLE
The command tsc.exe -project tsconfig.json exited with code 3

### ISSUE THREAD

**Issue by DGoertzen** [volkanceylan/Serenity#1589]
I created a new Serenity Project Ver 2.6.3 using Visual Studio Professional 2015 Version 14.0.25425.01 Update 3.
I ran "Build Solution" on project without making any changes,
I got a warning message "The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe" -project "C:\Perforce\Project\Project\Project.Web\tsconfig.json"" exited with code 3.
I verified that tsconfig.json is in the specified directory and am not sure what the problem is, if it matters, nor how to fix it.

**Comment by renditionstune** [comment]
Hi. I had that problem. Happens because v2.0 is not installed (you probably just have 1.8). Just install 2.0 via package manager.

**Comment by volkanceylan** [comment]
Do you have TSC there. Install 2.0.6. And see error list.

**Comment by stixoffire** [comment]
I know I had the error - it was something I searched and searched for but nothing came up for the code 3 error. I did resolve it without updating typescript - but it was  a while ago so I can't remember  it was either enabling something or adding a simple line . I just can't remember - maybe I reinstalled it.

**Comment by DGoertzen** [comment]
Thanks for the tips.  For reference, installing Microsoft.TypeScript.MSBuild and Microsoft.TypeScript.Compiler from the "Manage NuGet Packages for Solution" did not resolve the issue for me as "TscToolPath" continued to point to C:\Program Files (x86)\Microsoft SDKs\TypeScript\ and the Package Manager install in the project directory,  

I did resolve the problem by installing http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS2.0.3-TS-release20-nightly-20160921.1/TypeScript_Dev14Full.exe as indicated on the web site at https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/

However, if anybody is aware of how I should properly use the NuGet packages, I'd appreciate the information.

Thanks for your help.

**Comment by volkanceylan** [comment]
You shouldnt. You need to download and install it from typescriptlang.org as already specified in guide
