### ISSUE TITLE
In toolbar of grid editor, using text box instead of button.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#159]
Hi again.
I have to add a text box in place of add button in detail grid and bind keyup/down event of this button. So that barcode scanner can use this textbox.

Please help to achieve this task. 
Thanks.

**Comment by volkanceylan** [comment]
In CreateToolbarExtensions, access toolbar element with toolbar.Element and use jQuery to add input and attach events. jQuery is available with J() method.

**Comment by dfaruque** [comment]
protected override void CreateToolbarExtensions()
        {
            toolbar.Element.AddHtml(@"<input type=""text"" id=""txtBarcode""/>");

            J("#txtBarcode").Click(
                e =>
                {
                    Q.Alert("AAAAAAAAA");
                });

            base.CreateToolbarExtensions();
        }

Adding this does not create textbox in toolbar. what is going wrong?

**Comment by VictorTomaili** [comment]
Try this one
```
protected override void CreateToolbarExtensions()
{
    var input = J(@"<input type=""text"" id=""txtBarcode""/>");
    toolbar.Element.Append(input);
    input.Click(e => {
        Q.Alert("AAAAAAAAA");
    });
    base.CreateToolbarExtensions();
}
```

**Comment by dfaruque** [comment]
Thank you. Now a textbox is added to the toolbar. But I have to listen keydown event instead of click.
like this

            input.Keydown(e =>
            {
                if (e.keyCode/which == 13)
                    Q.Alert("AAAAAAAAA");
            });
Here e.keyCode/which is not there. How can I check keyCode?

**Comment by muhammedyaman** [comment]
@dfaruque how can i implement a barcode scanner into serenity?

**Comment by dfaruque** [comment]
did you implement barcode elsewhere?

**Comment by muhammedyaman** [comment]
I made a sample windows forms app to my scanner. I want the scanner to be triggered via serenity and get the read barcode in the textbox. But my scanner is windows ce 5.0 so I dont really know if thats possible.

**Comment by muhammedyaman** [comment]
Thank you now i got the logic.
