### ISSUE TITLE
Entity with reference cannot be deleted

### ISSUE THREAD

**Issue by mirokulket** [volkanceylan/Serenity#1590]
If I try to delete a user that has a Role / Permission
I get an error:
The DELETE statement conflicted with the REFERENCE constraint "FK_UserPermissions_UserId". The conflict occurred in database "Demo_Serene_Default_v1", table "dbo.UserPermissions", column 'UserId'.
The statement has been terminated.
If this is a desired behavior the error message could be more comprehensible...

**Comment by williamhodges** [comment]
You need to make sure that there are no users that still have that role. Once you have verified that and that the role does not have any assigned permissions, you can then delete the role.

**Comment by mirokulket** [comment]
I want to delete the user, not a role

**Comment by williamhodges** [comment]
My apologies, make sure the user is not assigned any role or explicit permissions.

**Comment by mirokulket** [comment]
I know, but the error message looks horrible to a web user unless he is a programmer...

**Comment by volkanceylan** [comment]
That "horrible" message comes from SQL server. And it is what you get in any ORM. Serenity can't and shouldn't handle that. Serenity is DB agnostic. If you want, set FK to CASCADE DELETE, or in UserRepository delete related records. Or see prior issues on how to handle it gracefully.

**Comment by sayuga** [comment]
I know this is closed but my two cents on this is that you can always set the User table to have a IIsActiveDeletedRow interface. This lets you keep the record in case you ever need to re-instantiate the user, removes loss of reference in the event you are running any audit or joint fields using the userId and, even though the record still technically exists, since it's a active delete, it still closes all permissions for the user. 

I've tested this and it works well with my setup. All I had to do was add IsActive to the table and it's proper edits to the xyzRow and xyzGrid files.

**Comment by mirokulket** [comment]
Thank you for your help. @volkanceylan : I think no matter if an application is DB agnostic or not, GUI should never show database error messages as-is to an end user, unless it's a test environment. First, it reveals database structure, which is a security risk and second it is totaly irrelevant for him. 
The most visited webs on the Internet never show exception traces.
[User Interface Design Tips](http://www.ambysoft.com/essays/userInterfaceDesign.html), http://www.goodui.org/

**Comment by volkanceylan** [comment]
Well, design your better framework with tips from there then. Good luck.

**Comment by mirokulket** [comment]
@volkanceylan  sorry if I insulted you, I didn't want to. I won't design my framework because Serenity is very cool and I appreciate it very much!

**Comment by volkanceylan** [comment]
https://en.wikipedia.org/wiki/Security_through_obscurity

Stack traces in ASP.NET are controlled by customErrors mode ON OFF.
