### ISSUE TITLE
Dinamik EditLink(ItemType = “XXXXXX”)

### ISSUE THREAD

**Issue by ComertAhmetSahin** [volkanceylan/Serenity#1592]
XYZRow.cs içersinde bir alanda

EditLink(ItemType = “XXXXXX”)

ItemType' ı Dinamic Olarak Verebilme Şansımız Varmı? 
Yani Entity içersinde bir alanın değerine bağlı olarak EditLink-ItemType ‘ı değiştirebilirmiyiz

**Comment by stixoffire** [comment]
Belki ara bağlantı öğesini kullanabilir ve bu çağrıyı gerçek bağlantınıza sahip olursunuz - bildiğimden başka.

**Comment by volkanceylan** [comment]
Custom links örneğine bakınız.
