### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by girish-a** [volkanceylan/Serenity#1593]
In my project, I have created a role called Team Member. I have a module called "Orders" and I want to grant access to that module to the Team Member role.

I have created a user and have assigned the team member role to that user. 

In my code, I have defined a PermissionKeys file as follows (I know this is only for intellisense):

```
public class PermissionKeys
{
        public class Orders
        {
            public const string Delete = "MyProject:Orders:Delete";
            public const string Modify = "MyProject:Orders:Modify";
            public const string View = "MyProject:Orders:View";
        }
        public const string General = "Orders:General";
}

```
In my OrderRow class, I have added the following attributes:
 
```
[ReadPermission(MyProject.PermissionKeys.Products.View)]
[ModifyPermission(MyProject.PermissionKeys.Products.Modify)]
[DeletePermission(MyProject.PermissionKeys.Products.Delete)]
public sealed class OrderRow : Row, IIdRow, INameRow
{

}
```

I can now see the modules listed in the permissions dialog when I log in as admin. However, when I grant the access to the user (as well as the Team Member role) and log in with that username, I am not seeing the Order module. 

How can I get the module to appear for the Team Member role?

Thanks!

**Comment by volkanceylan** [comment]
Check permissions in your page and endpoint

**Comment by volkanceylan** [comment]
See FAQ

**Comment by girish-a** [comment]
Thanks! I can now see the Order module in the navigation. However, when I select it, I get the following error: "Authorization has been denied for this request". 

I checked the documentation for this error, but couldn't find a fix.
