### ISSUE TITLE
Nood question

### ISSUE THREAD

**Issue by thelmapeluche** [volkanceylan/Serenity#1596]
Hello guys, i can't seem to understand why my project hasn't a tittle info next to the rotating logo :(
Help please.

![image](https://cloud.githubusercontent.com/assets/24476434/21049583/a238220e-be0d-11e6-978c-abb62e567129.png)

**Comment by stixoffire** [comment]
@thelmapeluche  Your Texts file may not have any string to describe it . Or maybe you do not have a texts file - check there first.

**Comment by thelmapeluche** [comment]
Strange, whats the variable I would change in text please ?

**Comment by volkanceylan** [comment]
You should debug it yourself.

**Comment by volkanceylan** [comment]
This is like coming here and saying my car is not working any idea?

**Comment by thelmapeluche** [comment]
sorry won't asking, i came from a windows background, and yes i was getting for fast free help, but i guess  @volkanceylan if this is the kind of help i get, oh well gut look for your future !!!
