### ISSUE TITLE
VS 2017 RC support

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1598]
It seems Serenity is working fine in VS2017, except for the error handling part, it gives an error when trying to write to the database. Did anyone tested  Serenity on VS 2017?

**Comment by williamhodges** [comment]
What error are you getting?

**Comment by williamhodges** [comment]
@chizdamasii I have Serene and Serenity both working in VS 2017 RC1 Community and Enterprise. Can you provide the error that you are getting when you try to write to the database?
