### ISSUE TITLE
Can't edit permissions on a role as admin

### ISSUE THREAD

**Issue by jmace** [volkanceylan/Serenity#1599]
Hello,

On my local machine, I have no issue creating roles and then editing those roles.

When I deploy to a test server, I get an error when I try to edit permissions for a newly created role.

These are my error messages chrome inspector

`
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
GET http://##MyServer##/##MyProject##/DynJS.axd/RemoteData.Administration.PermissionKeys.js?636168701625317124 500 (Internal Server Error)
Uncaught SyntaxError: Unexpected token <(…)
Uncaught Error: Can't load script data: RemoteData.Administration.PermissionKeys!(…)
`

Below are the packages for my deployment
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="bootstrap" version="3.3.7" targetFramework="net45" />
  <package id="CsQuery" version="1.3.4" targetFramework="net45" />
  <package id="Dapper" version="1.42" targetFramework="net45" />
  <package id="EPPlus" version="4.1.0" targetFramework="net45" />
  <package id="flot" version="0.8.3" targetFramework="net45" />
  <package id="FluentMigrator" version="1.6.2" targetFramework="net45" />
  <package id="FluentMigrator.Runner" version="1.6.2" targetFramework="net45" />
  <package id="jQuery" version="3.1.1" targetFramework="net45" />
  <package id="jquery.blockUI.TypeScript.DefinitelyTyped" version="0.0.4" targetFramework="net45" />
  <package id="jquery.cookie.TypeScript.DefinitelyTyped" version="0.2.1" targetFramework="net45" />
  <package id="jquery.TypeScript.DefinitelyTyped" version="3.1.2" targetFramework="net45" />
  <package id="jQuery.UI.Combined" version="1.12.1" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.15.1" targetFramework="net45" />
  <package id="jquery.validation.TypeScript.DefinitelyTyped" version="0.4.5" targetFramework="net45" />
  <package id="jqueryui.TypeScript.DefinitelyTyped" version="1.5.1" targetFramework="net45" />
  <package id="jspdf.TypeScript.DefinitelyTyped" version="0.0.4" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="MsieJavaScriptEngine" version="2.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="Select2.js" version="3.5.1" targetFramework="net45" />
  <package id="Serenity.CodeGenerator" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Core" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Data" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Data.Entity" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Services" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Web" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Web.Assets" version="2.6.4" targetFramework="net45" />
  <package id="Serenity.Web.Tooling" version="2.5.0" targetFramework="net45" />
  <package id="sortablejs.TypeScript.DefinitelyTyped" version="0.1.8" targetFramework="net45" />
  <package id="StackExchange.Exceptional" version="1.0.122" targetFramework="net45" />
  <package id="toastr" version="2.1.1" targetFramework="net45" />
  <package id="toastr.TypeScript.DefinitelyTyped" version="0.3.1" targetFramework="net45" />
  <package id="wkhtmltopdf-x86-win32" version="0.12.3.6" targetFramework="net45" />
</packages>
`

This is all as the admin user.

**Comment by volkanceylan** [comment]
See FAQ/Troubleshooting. IIS to integrated mode.

**Comment by jmace** [comment]
Volkan,

I don't see any mention of IIS to integrated mode in the FAQ or the Troubleshooting sections. Am I overlooking that?

I have tried deploying the site to my local IIS as well and it functions correctly as long as it is run on my developer machine. Once I deploy to my remote server, I get the errors above and can not modify the permissions of a role.

**Comment by volkanceylan** [comment]
http://##MyServer##/##MyProject##/DynJS.axd/RemoteData.Administration.PermissionKeys.js

Type this in your browser or click the address in error link. You are getting IIS 500 error. See what is it about.

**Comment by jmace** [comment]
I get an "Authorization has been denied for this request!" error message. 

Stack Trace: 

```
[ValidationError: Authorization has been denied for this request!]
   Serenity.Authorization.ValidatePermission(String permission) +85
   Serenity.Web.DynamicScript.CheckRights() +12
   Serenity.Web.DynamicScriptManager.GetScript(String name) +55
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) +49
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessRequest(HttpContext context) +143
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
```

**Comment by jmace** [comment]
To add, I had the same error on both my localhost version as well as the version on my remote server, yet I can edit role permissions on my localhost version and not the remote server version.

**Comment by volkanceylan** [comment]
Don't know, that script requires only logging in. I can't know whats wrong there.

**Comment by jmace** [comment]
I'm sorry. I should have logged in prior to testing the URL you gave me above.

After logging in on my localhost version,
`Q.ScriptData.set('RemoteData.Administration.PermissionKeys', {"Entities":["Administration","Northwind:General","Northwind:Customer:View","Northwind:Customer:Modify","Northwind:Customer:Delete","Administration:Security","Administration:Translation"],"TotalCount":0,"Skip":0,"Take":0});`

After logging in on my remote server version, System.Reflection.AmbiguousMatchException: Ambiguous match found.

Stack Trace:
`[AmbiguousMatchException: Ambiguous match found.]
   System.DefaultBinder.SelectProperty(BindingFlags bindingAttr, PropertyInfo[] match, Type returnType, Type[] indexes, ParameterModifier[] modifiers) +10909246
   System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers) +218
   System.Type.GetProperty(String name, BindingFlags bindingAttr, Type returnType) +59
   System.Attribute.GetParentDefinition(PropertyInfo property) +150
   System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit) +153
   System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit) +133
   System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo element) +71
   TotalDepth.Administration.Repositories.UserPermissionRepository.ProcessAttributes(HashSet`1 hash, MemberInfo member, Func`2 getPermission) +82
   TotalDepth.Administration.Repositories.UserPermissionRepository.<ListPermissionKeys>b__10_0() +1082
   Serenity.LocalCache.Get(String cacheKey, TimeSpan expiration, Func`1 loader) +100
   TotalDepth.Administration.Repositories.UserPermissionRepository.ListPermissionKeys() +90
   TotalDepth.Administration.Endpoints.UserPermissionController.ListPermissionKeys() +17

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +192
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +155
   Serenity.Web.<>c__DisplayClass0_1.<Initialize>b__2() +235
   Serenity.Web.DataScript.GetScript() +17
   Serenity.Web.Item.GenerateContent() +50
   Serenity.Web.Item.EnsureContentBytes() +27
   Serenity.Web.DynamicScriptManager.GetScript(String name) +65
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) +49
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessRequest(HttpContext context) +143
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +341
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69`

**Comment by stixoffire** [comment]
@jmace I am seeing the same thing in my permissions dialog on the remote server I get this error, yet on development I do not. This occurs on any of my full IIS installations and not the VS2015 built in IISExpress - so I am thinking it has to be some crazy permission thing in IIS whether on a folder or what not.

**Comment by volkanceylan** [comment]
It's strange. It seems like you have duplicate DLLs in your bin directory, or something similar. It is failing why enumerating attributes of a property. You might try putting try catch in ProcessAttributes method in UserPermissionsRepository and ignore errors. But actually it's better to fix the cause, but not sure what it is.

**Comment by volkanceylan** [comment]
https://github.com/Microsoft/dotnet-apiport/blob/master/docs/BreakingChanges/112%20Calling%20Attribute.GetCustomAttributes%20on%20an%20indexer%20property%20no%20longer%20throws%20AmbiguousMatchException.md

This might be the cause or something similar. It seems like before .NET 4.6 it might throw this exception in indexer properties. Maybe you don't have .NET 4.6.1 on server, so it runs with 4.5 etc.

**Comment by volkanceylan** [comment]
@marcobisio you might be having the same problem

**Comment by jplee75** [comment]
I was experiencing this issue and upgrading the .Net Framework(to 4.6.2) on the problem server fixed it

**Comment by marcobisio** [comment]
Ohhh yes @volkanceylan I think so!! Thank you very much for remembering my issue!!
I'll try tomorrow on my test environment and I let you know!

Bye

**Comment by marcobisio** [comment]
Also thanks to @jplee75 for your feedback!

**Comment by stixoffire** [comment]
@volkanceylan upgrading to 4.6.2 on the web server solved the problem (why my dev with VS2015 worked who knows) - I was researching the issue here http://blog.abodit.com/2010/02/asp-net-mvc-ambiguous-match/         as well to try to find out the bottom line on the issue - and he resolves the issue another way  by limiting what signatures are matched via filtering.  My dev machine does not error so catching the bug is like biting nails.

**Comment by volkanceylan** [comment]
Because VS2015 has 4.6.2

**Comment by jmace** [comment]
An update, upgrading my server to .NET 4.6.2 resolved the issue.  Thanks @jplee75 , @volkanceylan .

**Comment by kilroyFR** [comment]
For the record, issue can be fixed (even not deploying new net4x version), see explanation and registry update here :

https://trailheadtechnology.com/solving-could-not-create-ssl-tls-secure-channel-error-in-net-4-6-x/
