### ISSUE TITLE
Having a Q.Confirm but wanting to display the yellow warning triangle from the Q.Warning dialog

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#160]
Hi JaiQ,

I want to use the Q.Confirm Dialog (letting the user make an active decision) but instead of the "calm" blue theme I want to have the same Image, Font- and Background Color like the Q.Warning Dialog.

I have looked into this and searched this github repository here regarding how to do this but didn't find much.

Challenge:
How would I temporarily Change the appearance of the Q.Dialog to a similar look like Q.Warning for one specific Situation but not Change the Q.dialog appearance permanently. (or creating a clone of the Q.Confirm dialog --> e.g. a Q.WarningConfirm dialog)

Thanks again for your time and Support in advance.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Hi John,

```cs
Q.Confirm("test", () => { }, 
new ConfirmOptions { DialogClass = "s-MessageDialog s-WarningDialog" });
```

should do the trick.

You may also do add an extra class of your own like

new ConfirmOptions { DialogClass = "s-MessageDialog s-WarningDialog s-MyStyle" })

then style s-MyStyle with css;

Regards,
Volkan

**Comment by JohnRanger** [comment]
Hi JaiQ,

that works perfectly (your first recommendation). Such an elegant, painless way...

Thank you again very much for your Support

and with Kind regards,

John
