### ISSUE TITLE
Datetime Offset Error

### ISSUE THREAD

**Issue by MaradiagaSistemas** [volkanceylan/Serenity#1601]
Hi,

Thank you for your amazing job with Serenity,

Recently I updated serenity to 2.6.6 Version, but when I try to update an existing record throws an error "Cannot convert an object type 'System.DateTimeOffset' to 'System.IConvertible'

This wasn't hapening in 2.6.4 version.

Error:
https://postimg.org/image/45ybkaxr7/

**Comment by volkanceylan** [comment]
Are you using DateTimeOffsetField or not? And need stack trace.

**Comment by MaradiagaSistemas** [comment]
No, Im not using DateTimeOffSetField,

This is happening with all Master-Detail Forms (When Detail form has data throws that error, but when is empty saves entity normally)

I'm using Multitenancy Behaviour.

https://postimg.org/image/ghba1sdqj/

**Comment by volkanceylan** [comment]
Use DateTimeOffset field for DateTimeOffset fields and show the stack trace in request, clicking XHR tab response.

**Comment by MaradiagaSistemas** [comment]
I dont have any DatetimeOffset Field in my project, should i change every single datetimefield to datetimeoffset field?

**Comment by volkanceylan** [comment]
How do you get DateTimeOffset value if you don't have any datetimeoffset field in database??

**Comment by volkanceylan** [comment]
OK i could reproduce that, and it is a bug, releasing 2.6.7 now, please test and let me know if it works.

**Comment by volkanceylan** [comment]
You could also do this without update:

JsonSettings.Tolerant.DateParseHandling = DateParseHandling.DateTime
JsonSettings.Strict.DateParseHandling = DateParseHandling.DateTime

**Comment by MaradiagaSistemas** [comment]
It works just Perfect after 2.6.7 Upgrade.

Thank you very much, definitely you saved my day.

**Comment by tistek** [comment]
Dear  volkanceylan
I am Getting one problem  . how to take server date time not local system date time . I want to save server date time in table not local system date time . if you have any solution  can you guide me soon as possible

**Comment by VictorTomaili** [comment]
@tistek use Discussion Q&A section. Please don't comment on closed issue if not related.
