### ISSUE TITLE
How to install on Sharepoint 2013 ?  Any pitfalls guidance or how to links ... 

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1602]
I am looking for any information on how I can install this on a sharepoint 2013  - I installed on a local server and have blank web pages , my development machine VS2015 it works perfectly. 

Any links , insights or help is greatly appreciated.  Since I am new to sharepoint ; I tried installing on a local server machine first and have blank pages, and I notice uncaught exception Jquery not found.

**Comment by volkanceylan** [comment]
This doesn't work with Sharepoint
