### ISSUE TITLE
Manually refresh a grid from a dialog?

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1604]
I have a datagrid with Products in there.  At the top of the grid I've added a button to open an unrelated dialog, of type Customer.

When I save the Customer I would like to refresh the grid of Products.  I've been looking through the Serenity source in the EntityGrid.cs class to see how it automatically refreshes whenever I open an entity dialog and save, but I must be missing that section.  

Regardless, is it possible to refresh a grid manually when I save or update in a dialog?

**Comment by volkanceylan** [comment]
call initDialog method of grid, after creating dialog

**Comment by lquantz** [comment]
That should work great, I see it's used in the DefaultValuesInNewGrid.ts sample too.  Thanks!
