### ISSUE TITLE
When run ServerTypings then System.NullReferenceException

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#1605]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		正在运行转换: System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Serenity.CodeGeneration.ServerImportGeneratorBase.GetServiceUrlFromRoute(Type controller) 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\Base\ServerImportGeneratorBase.cs:行号 395
   在 Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass13_0.<GenerateService>b__0() 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.Service.cs:行号 21
   在 Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) 位置 P:\Sandbox\Serene\Serenity\Serenity.Core\Reflection\CodeWriter.cs:行号 50
   在 Serenity.CodeGeneration.ServerTypingsGenerator.GenerateService(Type type) 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.Service.cs:行号 19
   在 Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass22_1.<GenerateCodeFor>b__1() 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:行号 39
   在 Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) 位置 P:\Sandbox\Serene\Serenity\Serenity.Core\Reflection\CodeWriter.cs:行号 50
   在 Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass22_0.<GenerateCodeFor>b__0(Action`1 action) 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:行号 37
   在 Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(Type type) 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:行号 46
   在 Serenity.CodeGeneration.ServerImportGeneratorBase.GenerateAll() 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\Base\ServerImportGeneratorBase.cs:行号 146
   在 Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() 位置 P:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:行号 25
   在 Microsoft.VisualStudio.TextTemplating5EAEFF825099E0572E462F5A8D2A99AEFBA46F58009C5E4C27DCDE748D7E6E0586B9FE4DDEC472CA687B368B39A3F7FD476C21B95FB655FB96A5B01F320244FD.GeneratedTextTransformation.TransformText()	myproject.Web	E:\Documents\Visual Studio 2015\WebSite\myproject\myproject\myproject.Web\Modules\Common\Imports\ServerTypings\ServerTypings.tt	1	

What can I do ?

**Comment by volkanceylan** [comment]
Probably something related to route attributes on one of your endpoints.
