### ISSUE TITLE
Getting Dynamic Links to auto-update

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1606]
First off thank you to @DucThanhNguyen for laying out the wiki for Dynamic Navigation. I was wondering how I could get this to update automatically at run time. I followed the wiki guide directly, however I see that it only sorts through at the initial start of the application. Is there a way for it to update auto or semi auto?

**Comment by DucThanhNguyen** [comment]
The navigation items are cached in local storage for each logged in user. See NavigationModel in Common module for details.

To update dynamic items with the database changes, you need to reset the cache for group items withe the key "LeftNavigationModel:NavigationItems:". Add this static method to NavigationModel class and call it whenever related records changed.

```c#
        public static void ResetCache()
        {
            TwoLevelCache.ExpireGroupItems("LeftNavigationModel:NavigationItems:");
        }
```

I'm going to add a pull request for Serene that includes this method.

**Comment by volkanceylan** [comment]
Group key you should reset is UserPermissionRow.Fields.GenerationKey as they are cached in Serene/NavigationModel.cs

```
TwoLevelCache.ExpireGroupItems(UserPermissionRow.Fields.GenerationKey)
```

Also need to reset ones cached in Serenity NavigationHelper.cs:

```
LocalCache.Remove("NavigationHelper:NavigationItems")
```

You should do both in CategoryRepository, aftersave etc.

I don't recommend doing this often, it would kill performance.

**Comment by williamhodges** [comment]
I can see how that would kill performance. Thank you @DucThanhNguyen and @volkanceylan for your help.

**Comment by jaamkamran** [comment]
See
https://youtu.be/UapCtkcmE18
