### ISSUE TITLE
Authorization has been denied for this request

### ISSUE THREAD

**Issue by girish-a** [volkanceylan/Serenity#1608]
1. I assigned permissions to a role and assigned that role to a user.
2. I also went to the user's permissions and added permissions for that user.

But I still get a message "Authorization has been denied for this request" when I click on the module on the left navigation.

I checked the documentation for this error, but I didn't find this error mentioned.

Thanks for the great template! I want to contribute after this project is completed!

**Comment by volkanceylan** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/faq/troubleshooting.html

**Comment by AmarSS** [comment]
The below page is not working..

https://volkanceylan.gitbooks.io/serenity-guide/content/faq/howto/howto/how_to_register_permissions_in_serene.md

**Comment by marcobisio** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_register_permissions_in_serene.html
