### ISSUE TITLE
How to set/adjust widths of input fields?

### ISSUE THREAD

**Issue by girish-a** [volkanceylan/Serenity#1609]
Hi,
I have a text box which just accepts 10 chars and another which accepts 5. I want to place them side by side instead of one below the other. Every input field is on one line. 

If I want to place multiple fields on a single line, how should I do it? I checked the Movie tutorial/documentation for this but didn't find the solution.

Thanks!

**Comment by volkanceylan** [comment]
Have a look around in samples.
