### ISSUE TITLE
Show data from view create in mssql database

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#161]
Hi,
When I create form with sergen to show data from view in mssql database, not table, the data won't show in grid.

Please help.

**Comment by volkanceylan** [comment]
Do you have a ID column in view?

**Comment by JohnRanger** [comment]
Does the view Show any data in MS SQL Mgmt Studio when selecting: "Returning 1000 rows" in the context menu of the view? 

--> If not, please resolve the reason why there are no record shown within the view.

--> If yes, then please check if there is an unneccessary table (one with no relation to any of the required tables within the view) dragged within the view designer.

-- I had this once. The result was that the view in MS SQL mgmt Studio showed records but serenity wouldn't Show them. After I removed the unneccessary table from the view, the records showed up in Serenity as well.

With Kind regards, 

John

**Comment by Nikola7i** [comment]
1. Yes, I have column with ID field (about 7 tables are connected)
2. No table are unrelated , all make one view
3. Does the order from view must be same in grid?
4. In server exlporer in visual studio I can open view and see data

**Comment by volkanceylan** [comment]
That ID column must be unique. See chrome console and share what error you got there.

**Comment by sayuga** [comment]
I ran into the same issue when I was pulling in views and I found out that MyProject.Web/MyViewRow,cs and MyProject.Script/MyViewGrid.cs were missing information. I designated and ommited information at the following locations: 



Firstly in MyProject.Web/MyViewRow,cs

...
   IIdField IIdRow.IdField
        {
            get { return Fields.**"ReplaceWithID"**; }
        }


Then in MyProject.Script/MyViewGrid.cs

....

    [ColumnsKey("Module.MyView"), **IdProperty(MyViewRow.IdProperty)**, NameProperty(MyViewRow.NameProperty)]

...


After updating the information I rebuilt and Transformed the Templates and it ran fine. Hope this helps.

**Comment by Nikola7i** [comment]
Tnx sayuga,

that was the problem. I modify first time in MyProject.Web/MyViewRow.cs, and then I have problem with **IdProperty(MyViewRow.IdProperty)**, because , in .script.Imports.ServiceContaract.MyViewRow.cs I have to add  [InlineConstant] public const string IdProperty = "MyID";
After that everything start to work fine.
I try with sergen new add view ,same that view which work, and again same things are missing. Some problem with sergen?

**Comment by volkanceylan** [comment]
You must set ID field yourself. There is no way to determine ID property in views.

**Comment by Nikola7i** [comment]
Tnx, btw. nice job about templates, like it. I hope you are going forward.

**Comment by volkanceylan** [comment]
Thanks, have a lot todo in list.

**Comment by paulobriennz** [comment]
I've hit this a couple of times now, and i keep coming back to this site and searching for the solution.

the fix for me is in the new view you've added's xxxxxxxGrd.ts file is missing the identity ref:

  protected getIdProperty() { return xxxxxxxxxRow.idProperty; }

**Comment by stixoffire** [comment]
In case some one is coming late to this party one of the ways this can be accomplished is using a ROW_NUMBER over (ORDER BY myColumn ) As Id in your View and use that as your Identity Column.
 
So in your XYZRow.cs place the [Identity] over your Id property. Then in the IIDField in XYZrow set i to the ID.  Your XYZRow should not Inherit from INameRow because there is no corresponding property of Name for the ID (unless you work this out in your View ) or an Unmapped Property such as Expression[("CONCAT('Row ' + T0.Id")]

```
        [Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }


        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }
```
