### ISSUE TITLE
how show a grid instead of dialog box in another grid 

### ISSUE THREAD

**Issue by vahid211** [volkanceylan/Serenity#1612]
Dear volkanceylan

in a form we are showing, a list of entities as grid, now we defined a icon in every row . we are respect to when click in icon shows a list of attributes, those are related to selected row.

as you see in attached image.
i see a sample in BasicSample>Grids>Inline Action Button , but in sample you show a dialog, we want to show a grid instead of dialog.

please guide me, how to do it.
note: i am amateur in serenity.

Best Regards,
VAHID
![Uploading Untitled.jpg…]()

**Comment by vahid211** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24287017/21078415/778ac15c-bf83-11e6-89f7-ad8877e21e32.jpg)

**Comment by volkanceylan** [comment]
You could put a grid inside dialog and show that. Use TemplatedDialog as base class.

**Comment by vahid211** [comment]
Dear

thanks for your answer. but how can i do it.
i use below function in my EntityGrid file.
but it shows Attribute Dialog, i am going to show attributes grid.

please guide me by code, i am not peroffesional in TypeScript.

Thanks
------
protected getColumns() {
            var columns = super.getColumns();

            columns.splice(1, 0, {
                field: 'View Attribute Details',
                name: '',
                format: ctx => '<a class="inline-action view-attributs" title="view attributa"></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            return columns;
        }
//---------------
protected onClick(e: JQueryEventObject, row: number, cell: number){
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();
                if (target.hasClass('view-attributs')) {
                    var dlg = new DataDictionary.EntityAttributeDialog();
                    this.initDialog(dlg);
                    dlg.loadByIdAndOpenDialog(<DataDictionary.DdEntityAttributeRow>{
                        EntityId: item.EntityId
                    });
}
}
}

**Comment by volkanceylan** [comment]
There are several places with grids in Serene, e.g. Northwind, and in tutorial. You should use dialogOpen.

**Comment by volkanceylan** [comment]
I may add a sample later.
