### ISSUE TITLE
Good news for Serenity community

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1613]
I am really happy to see this.
Serene (Serenity Application Template) is now Highest Rated extension in https://marketplace.visualstudio.com/

![highestrated1](https://cloud.githubusercontent.com/assets/16621563/21078615/c3e85aac-bf9f-11e6-90d5-7b3af687d802.png)

Among all other extensions, Serene is the top rated.

![highestrated](https://cloud.githubusercontent.com/assets/16621563/21078651/7ac96d1e-bfa1-11e6-98f9-16e0ffbfb6e8.png)

Good Luck.
Thank you @volkanceylan for your hard work and patience.
This is the result.
May Allah bless you.

**Comment by marcobisio** [comment]
I'm happy to see that the meritocracy is still alive!

**Comment by brunobola** [comment]
The community will keep rising i'm sure, if people help each other and spread the word :)

**Comment by volkanceylan** [comment]
Old VSGallery was prioritizing extensions with more votes. So Serenity was in page 4-5 or so as it had less votes than others, even though rating was higher. Think this new one doesn't care much about number of votes like old one. Need more reviews to stay there, in case they change algorithm again.

**Comment by volkanceylan** [comment]
Btw, we are still not among Top 200 projects with C# language in GitHub, sorted by stars. Have a long way to go.
