### ISSUE TITLE
Adding Custom Button on Grid

### ISSUE THREAD

**Issue by ozkan35selek** [volkanceylan/Serenity#1614]
Hi @volkanceylan ,
I'm newbie in Serenity. i'm sorry for my dummy questions.
#-i want to add custom button on grid for card view popup.
#-i want to add excel and pdf buttons on grid.

agentgrid.ts

`
namespace SHS.LABS {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.filterable()
    export class AgentGrid extends Serenity.EntityGrid<AgentRow, any> {
        protected getColumnsKey() { return 'LABS.Agent'; }
        protected getDialogType() { return AgentDialog; }
        protected getIdProperty() { return AgentRow.idProperty; }
        protected getLocalTextPrefix() { return AgentRow.localTextPrefix; }
        protected getService() { return AgentService.baseUrl; }

        constructor(container: JQuery) {
            super(container);
        }

        getButtons() {
            var buttons = super.getButtons();
            var MyRow = AgentRow.Fields;

            buttons.push(SHS.Common.ExcelExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: AgentService.baseUrl + '/ListExcel',
                separator: true,
                hint: "This is the Hint",
                title: "This is the Title"
            }));

            buttons.push(SHS.Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));

            return buttons;
        }

    }
}`

and 

`

`
AgentEndpoint.cs

` public FileContentResult ListExcel(IDbConnection connection, ListRequest request)
        {
            var data = List(connection, request).Entities;
            var report = new DynamicDataReport(data, request.IncludeColumns, typeof(Columns.AgentColumns));
            var bytes = new ReportRepository().Render(report);
            var reportName = "xyzList_";
            return ExcelContentResult.Create(bytes, reportName + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".xlsx");
        }
`
but buttons are not visible...
what's my mistake?
and how can i create custom button...

**Comment by brunobola** [comment]
See this: https://github.com/volkanceylan/Serenity/wiki/Adding-Excel-Export
and this: https://github.com/volkanceylan/Serenity/wiki/Adding-Excel-Export

**Comment by volkanceylan** [comment]
Try installing TypeScript 2.0
