### ISSUE TITLE
Sergen error with tables+foreignkeys

### ISSUE THREAD

**Issue by SpiraMira** [volkanceylan/Serenity#1616]
Hi, I get the attached serene error when attempting to generate code for my tables with foreign keys.  

```
Serenity.CodeGenerator.EntityField does not contain a definition for Type'
 at CallSite.Target(Closure,Callsite,Object)
at Serenity.CodeGenerator.Views.EntityRow.Execute()
...
```

I confirmed my hunch by removing the foreign keys in sox and rerunning serene (successfully). Pretty simple Person table:

CREATE TABLE [org].[Person] (
    [PersonId]   INT            IDENTITY (1, 1) NOT NULL,
    [Firstname]  NVARCHAR (50)  NOT NULL,
    [Middlename] NVARCHAR (50)  NOT NULL,
    [Lastname]   NVARCHAR (50)  NOT NULL,
    [BirthPlace] NVARCHAR (100) NULL,
    [BirthDate]  DATETIME       NULL,
    [Gender]     INT            NULL,
    [Location]   INT            NULL,
    [Photo]      NVARCHAR (255) NULL,
    CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([PersonId] ASC),
    CONSTRAINT [FK_Person_GenderId] FOREIGN KEY (Gender) REFERENCES [org].Gender (GenderId)
);

The snapshot is from the the latest 2.6.8 of Serenity.Code. In fact here is my current packages.config:

`<packages>
  <package id="bootstrap" version="3.3.7" targetFramework="net45" />
  <package id="CsQuery" version="1.3.4" targetFramework="net45" />
  <package id="Dapper" version="1.42" targetFramework="net45" />
  <package id="EPPlus" version="4.1.0" targetFramework="net45" />
  <package id="flot" version="0.8.3" targetFramework="net45" />
  <package id="FluentMigrator" version="1.6.2" targetFramework="net45" />
  <package id="FluentMigrator.Runner" version="1.6.2" targetFramework="net45" />
  <package id="jQuery" version="3.1.1" targetFramework="net45" />
  <package id="jquery.blockUI.TypeScript.DefinitelyTyped" version="0.0.4" targetFramework="net45" />
  <package id="jquery.cookie.TypeScript.DefinitelyTyped" version="0.2.1" targetFramework="net45" />
  <package id="jquery.TypeScript.DefinitelyTyped" version="3.1.2" targetFramework="net45" />
  <package id="jQuery.UI.Combined" version="1.12.1" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.15.1" targetFramework="net45" />
  <package id="jquery.validation.TypeScript.DefinitelyTyped" version="0.4.5" targetFramework="net45" />
  <package id="jqueryui.TypeScript.DefinitelyTyped" version="1.5.1" targetFramework="net45" />
  <package id="jspdf.TypeScript.DefinitelyTyped" version="0.0.4" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="MsieJavaScriptEngine" version="2.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="Select2.js" version="3.5.1" targetFramework="net45" />
  <package id="Serenity.CodeGenerator" version="2.6.8" targetFramework="net45" />
  <package id="Serenity.Core" version="2.6.8" targetFramework="net45" />
  <package id="Serenity.Data" version="2.6.8" targetFramework="net45" />
  <package id="Serenity.Data.Entity" version="2.6.8" targetFramework="net45" />
  <package id="Serenity.Services" version="2.6.8" targetFramework="net45" />
  <package id="Serenity.Web" version="2.6.8" targetFramework="net45" />
  <package id="Serenity.Web.Assets" version="2.6.6" targetFramework="net45" />
  <package id="Serenity.Web.Tooling" version="2.6.6" targetFramework="net45" />
  <package id="sortablejs.TypeScript.DefinitelyTyped" version="0.1.8" targetFramework="net45" />
  <package id="StackExchange.Exceptional" version="1.0.122" targetFramework="net45" />
  <package id="toastr" version="2.1.1" targetFramework="net45" />
  <package id="toastr.TypeScript.DefinitelyTyped" version="0.3.1" targetFramework="net45" />
  <package id="wkhtmltopdf-x86-win32" version="0.12.3.6" targetFramework="net45" />
</packages>`

You can tell from the screen capture that I ran a multiple table sergen.  Only my tables without foreign keys worked as expected.  Thanks for your help.

![sergen-error](https://cloud.githubusercontent.com/assets/286122/21085091/3098f054-bfdb-11e6-9037-f8bfb7d7e522.png)

**Comment by volkanceylan** [comment]
Hmm must be some template i missed to change. Will fix asap.

**Comment by SpiraMira** [comment]
Thanks.  

I traced as far as I could. 
Seems like something is out of sync.

In the meantime, my workaround is to ...

1. comment out all FK declarations in migrations
2. sergen my tables
3. re-insert the FKs manually 
4. finally decorate my  xyzRow.cs class(es) appropriately with ForeignKey,LeftJoin and TextualField attributes


Does that sound ok to you?

P

**Comment by volkanceylan** [comment]
No i think you should wait a bit, recently did some changes to Sergen, forgot to replace it somewhere

**Comment by volkanceylan** [comment]
Please update to 2.6.9

**Comment by SpiraMira** [comment]
Thanks so much for the quick response!

Works like a charm again.

quick question: what does Sergen option Row Fields Surround With Region do? Couldn't find any docs about it...

Thanks again and Regards, P.

**Comment by volkanceylan** [comment]
It's an option added by somebody else, which adds #region directives around fields i think. I'm not a fan of regions.
