### ISSUE TITLE
Multiple select lookup save as comma separated string

### ISSUE THREAD

**Issue by onkarbahirat22** [volkanceylan/Serenity#1618]
Hi Volkanceylan,

i have added one drop down as multiple=true. Is there any any way to save selected value as comma separated string and again bind to it while editing

Thanx in advance...

**Comment by volkanceylan** [comment]
CommaSeparatedValues = true

**Comment by abelal83** [comment]
should it not be something like

`Multiple = True, Delimited = True`

as there is no CommaSeperatedValues attribute that I could find?
