### ISSUE TITLE
question: quickfilter has no dropdown list

### ISSUE THREAD

**Issue by vihorlat** [volkanceylan/Serenity#1619]
Hello, 
how can I get a quickfilter to work with an autocomplete as in serenity demo-orders grid:
![image](https://cloud.githubusercontent.com/assets/11267965/21095688/e1a738e8-c05c-11e6-8649-5ac2cc08c7b9.png)

I have used it the same way as in serenity demo- orders, but I don't have the dropdown. I didn't use `LookupScript`

Thank you

**Comment by williamhodges** [comment]
You just press enter and it will select the Federal Shipping that is highlighted.

**Comment by vihorlat** [comment]
@williamhodges, sorry I didn't explain it correct, my dropdown doesn't show up...

**Comment by williamhodges** [comment]
You're going to have to post some of your code, I can't help with out seeing it.

**Comment by vihorlat** [comment]
```
public sealed class PersonRow : Row, IIdRow, INameRow
{
        [DisplayName("City Id"), ForeignKey("CityTable", "Id"), LeftJoin("city")]
        public Int64? CityId
        {
            get { return Fields.CityId[this]; }
            set { Fields.CityId[this] = value; }
        }

        [DisplayName("City"), Expression("city.[City]"), QuickSearch(SearchType.Contains)]
        public String City
        {
            get { return Fields.City[this]; }
            set { Fields.City[this] = value; }
        }
......



[ColumnsScript("MyModule.Person")]
[BasedOnRow(typeof(Entities.PersonRow))]
public class PersonColumns
{
        public Int64 CityId { get; set; }

        [Width(140), QuickFilter, QuickFilterOption("multiple", true)]
        public String City { get; set; }
....
```
The City field maps correctly.
Have I forgotten anything ?

**Comment by volkanceylan** [comment]
See how Northwind city works

**Comment by vihorlat** [comment]
Awesome, so simple!
Thank you
