### ISSUE TITLE
Flexify tool tips defaulting to Turkish

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#162]
The tooltip when hovering over the maximize button on entity dialogs are displaying in Turkish. My globalization configs are set to en-US by default, not sure if this is a language issue or not, perhaps the tool tips are hard coded strings?

**Comment by jsbUSMC** [comment]
I forgot to mention that the restore/minimize button from being maximized also has a Turkish tooltip. The close button is in English.

**Comment by volkanceylan** [comment]
Might be, need to check

**Comment by volkanceylan** [comment]
Will be fixed in next version

**Comment by jsbUSMC** [comment]
Closing since 1.9.8 was released. Thank you @volkanceylan
