### ISSUE TITLE
Dateeditor start from 2006

### ISSUE THREAD

**Issue by ahsansolution** [volkanceylan/Serenity#1622]
How to set start year value in date editor, i need to set date editor start from 1950.
Thanks

![dateeditor](https://cloud.githubusercontent.com/assets/21119641/21103122/af91ea7c-c0b3-11e6-8d5e-2c6b559d6905.png)

**Comment by marcobisio** [comment]
Hi @ahsansolution,
you can set MaxValue and MinValue as attributes of the editor:

    [DateEditor(MinValue = ...)]

Bye

**Comment by volkanceylan** [comment]
https://api.jqueryui.com/datepicker/#option-yearRange
