### ISSUE TITLE
sergen.exe last version

### ISSUE THREAD

**Issue by mesmerisem** [volkanceylan/Serenity#1623]
Merhaba,
sanırım 10.12.2016 tarihinde V.S. Serene Template güncellendi, buradaki  sergen.exe ile Join bağlantısı olan tablolarda kode oluşturmak istendiğin aşağı daki hatayı veriyor, Join bağlantısı olmayan tablolar herhangi bir sorun yok.
![generatecodes_click](https://cloud.githubusercontent.com/assets/3017731/21104486/bbc052e6-c097-11e6-886e-38c6086f3383.PNG)

Teşekkürler

**Comment by mesmerisem** [comment]
hata oluştuğunda kullanılan örnek tablo

            this.CreateTableWithId32("MaterialSubConcept", "SubConseptId", s => s
              .WithColumn("ConceptId").AsInt32().NotNullable()
              .ForeignKey("FK_MaterialSubConcept_ConceptId", "MaterialConcept", "ConceptId")
            .WithColumn("SubConsept").AsString(30).NotNullable());

**Comment by SpiraMira** [comment]
hi - I got the same error on 2.6.8. This problem with foreign keys was fixed in 2.6.9. See #1616

**Comment by mesmerisem** [comment]
thank you very much SpiraMira
