### ISSUE TITLE
Sergen Generation Problem

### ISSUE THREAD

**Issue by ozkan35selek** [volkanceylan/Serenity#1624]
Hi @volkanceylan 
I updated Serenity yesterday on Package Manager Console like that;

Update-Package Serenity.Web
Update-Package Serenity.CodeGenerator
Update-Package Serenity.Script

Today i want to regenerate Entities but Sergen throws this exceptions. 
What's my mistake?

![capture](https://cloud.githubusercontent.com/assets/3073437/21116559/b77d1012-c0be-11e6-9220-b95c247180d3.PNG)

**Comment by volkanceylan** [comment]
Update again to latest.

**Comment by ozkan35selek** [comment]
it's ok. Serenity.CodeGenerator.2.6.10 is working well. Thanks @volkanceylan
