### ISSUE TITLE
Making a form field full width

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#1626]
Hi, First of all, thanks for a brilliant framework. It will save me a lot of time once I really understand some of the detail.

I'm trying to get a form field to fill the full width (using [Category] for the field name. Even with [DisplayName("")], the field remains indented. Do you have any code in the samples that show how to do this?

Since this will be an Html field (and I'm using the html editor), is there any way to use the CK Editor by using an attribute?

Thanks a lot!

**Comment by volkanceylan** [comment]
You can do this with css, e.g.

.s-MyDialog field.MyPropertyName .caption { display: none }

There is HtmlContentEditor you can use for CK.

**Comment by karimhyatt** [comment]
Perfect! Thanks a lot for that.

**Comment by volkanceylan** [comment]
Np, thanks ;)

**Comment by rcoproc** [comment]
@volkanceylan , I did like this:

.s-Public-ClientDialog field.Tipcadven .caption { display: none }

And did not hide the label of my form. How can I hide only the caption from my field?
