### ISSUE TITLE
KDiff3 AutoMerge

### ISSUE THREAD

**Issue by ozkan35selek** [volkanceylan/Serenity#1627]
Hi @volkanceylan 

I regenerate model and modules with Sergen and after opening KDiff3. 
How can i automerge with KDiff3?
i'm clickin AutoMerge button but Kdiff throws this message
Impossible to manually compare 110 files.

Is there an easy way?
![capture](https://cloud.githubusercontent.com/assets/3073437/21156523/cc3ad762-c17e-11e6-85d6-8eb8e93010cf.PNG)

**Comment by volkanceylan** [comment]
No there is not an easy way i know, why do you generate code for so many tables again anyway, you shouldn't.

If have to, delete or move old files then generate again.

**Comment by ozkan35selek** [comment]
My project's development type is Sprint development. Too many changes available in project. Too many tables are changing.i understand you if db is ok then go... but real life is sh*t, you know :)
So,ok. i will compare manually.. Thanks for your fast response @volkanceylan

**Comment by volkanceylan** [comment]
You're welcome
