### ISSUE TITLE
CheckListEditor

### ISSUE THREAD

**Issue by EchoParking** [volkanceylan/Serenity#1628]
Is there a guide on how to add the CheckListEditor off of an enum list?  I'm having trouble adding it to my row.

**Comment by volkanceylan** [comment]
I don't think it will work with enums. You might need to subclass it add your items.

**Comment by EchoParking** [comment]
Do you have an example on how to subclass CheckListEditor?  I can't find a good example.  Thanks!

**Comment by volkanceylan** [comment]
PermissionCheckListEditor
