### ISSUE TITLE
Error Executing Sergen - Does not contain a definition for 'Type'

### ISSUE THREAD

**Issue by BrMail** [volkanceylan/Serenity#1629]
I get an error running sergen in one table.
The table fields are just varchar(50) and int 

![image](https://cloud.githubusercontent.com/assets/17357390/21166280/5b08d76a-c19c-11e6-99f9-b571f6d76ca7.png)

Thanks!!

**Comment by zulander1** [comment]
see https://github.com/volkanceylan/Serenity/issues/1616

**Comment by BrMail** [comment]
The update solve it.

Thanks Zulander1 and  Volkanceylan
