### ISSUE TITLE
How to add Multiple tabs?

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#163]
I want to add 4 tabs for a screen.i can do 1st and second tab successfully but it doesn't show anything for next tab.Instead of using with same code.Please help me how to do?
Thanks in advance.

**Comment by volkanceylan** [comment]
See CustomerDialog, it has 3 tabs and no problems.

**Comment by nilimajagtap** [comment]
I am doing the same according to  customer .but still its not working.
In console it show the error "Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by volkanceylan** [comment]
What is the URL

**Comment by nilimajagtap** [comment]
http://localhost:55555/fonts/fontawesome-webfont.woff2?v=4.4.0

**Comment by volkanceylan** [comment]
This is irrelevant. Just a font file.

**Comment by nilimajagtap** [comment]
yeah...that's the my point.
I am following the same code.But Still it doesn't work.
Ok I will tell u step by step what i have done  then u correct me where I am going  wrong
First i have added Template file in web
then add file to show column in that tab
In Script Project
I have Added a Dialog & grid  file
then in master file give call to the tab as it is done in customer

**Comment by volkanceylan** [comment]
Open a gist with your template and script files

**Comment by nilimajagtap** [comment]
Hello Sir,I have shared my template & script files on gist.
Please do needful.
Thanks in Advance.

**Comment by volkanceylan** [comment]
Could you share a link to your gist, how can i see your gist otherwise :)

**Comment by nilimajagtap** [comment]
https://gist.github.com/nilimajagtap

**Comment by volkanceylan** [comment]
Make it public or share the link to gist

**Comment by nilimajagtap** [comment]
i  have make it public.Could u please check

**Comment by volkanceylan** [comment]
Why TabSectionDetail div inside the TabSection????

```html
<div id="~_TabSection" class="tab-pane s-_TabSection">
        <div id="~_SectionGrid">

        </div>
        <div id="~_TabSectionDetail" class="tab-pane s-_TabSectionDetail">
            <div id="~_SectionDetailGrid">

            </div>
```

**Comment by nilimajagtap** [comment]
By mistake I have putted.Now its working absolutely fine.
Thanks for quick replay.
Always greatful :)
