### ISSUE TITLE
Serenity.Mobile?

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1630]
@volkanceylan Sorry for this type of issue.

I believe there are many in this community who already implemented Serenity.Mobile. (e.g. running serenity app as mobile app instead of web app.) so that the app will be able to run without a browser and net connection.

Has anyone in this community who wishes to share their implementation (or just thought/guidance)?

Any kind of help is greatly appreciated.

**Comment by williamhodges** [comment]
What type of database would you use? Would you eventually push it to a cloud database once a net connection is made? I'm interested in seeing how this would work.

**Comment by dfaruque** [comment]
@williamhodges 
Database does not matter (any mobile supported DB).
Yes.

**Comment by dfaruque** [comment]
@john20xdoe  Thank for the information

**Comment by stixoffire** [comment]
@dfaruque this is of interest to me - how would I implement it without the browser. Basically I have some queries that need to run on the sql  server (community edition) and I need to mail them out as PDF. I also need to set some defaults each 1 January. So I was thinking to create an App on the desktop and run it in the Task scheduler and let it execute the web service to perform these functions. If you have examples, links etc I would _**GREATLY**_ Appreciate it.

**Comment by dfaruque** [comment]
This may be the nearest one which I am talking about.
https://developer.xamarin.com/guides/cross-platform/advanced/razor_html_templates/
Has anyone some experience using xamarin? 
Please guide us on the right direction.

**Comment by dfaruque** [comment]
They provide the ability to overrideUrl like bellow
```
class HybridWebViewClient : WebViewClient {
    public override bool ShouldOverrideUrlLoading (WebView webView, string url) {
        // return true if handled in code
        // return false to let the web view follow the link 
    }
}
```
This might be useful to determine whether should we use main server Or local data store (e.g. SQLite etc.)

Or. We may use local data store for CRUD operation and sync them later with server or vice-versa???

**Comment by stixoffire** [comment]
@dfaruque xamarin, MVC, Razor, and typescript are all new to me , webview I would imagine is a browser interface . I am not sure I would use it, I would just code against the service.  Unless I specifically wanted to browse the site. 
There is a project called trackable entities that I would look into for some guidance , it might not give a specific info but perhaps by looking at the code we can glean some details how it might be done here.

**Comment by volkanceylan** [comment]
I don't think there is anybody who did this unlike your guess @dfaruque 

Making an application designed to work online, work offline is not a trivial task. Even if you do somehow, there will always be synchronization problems.

Only some, limited functionality parts of application might be made to work offline.

Anyway, see tests under Dev.Serene.Test project, and how i virtualize Ajax calls to make tests continue to work like they are actually calling some service, while they don't. It might be some starting point. Not easy.

**Comment by williamhodges** [comment]
What about making it based off of Cordova?

**Comment by dfaruque** [comment]
@volkanceylan  I understand your point and fully agree.
Last part of your comment seems to be helpful to me. 

@williamhodges  I don't have experience using Cordava. Is it possible to use C# in Cordova? May be not.

Thank you guys.

**Comment by volkanceylan** [comment]
This also looks kinda promising:

https://developer.xamarin.com/guides/xamarin-forms/custom-renderer/hybridwebview/
https://spin.atomicobject.com/2016/06/08/native-html-apps-xamarin/
