### ISSUE TITLE
data not show in grid using panel

### ISSUE THREAD

**Issue by arunkumar12712** [volkanceylan/Serenity#1631]
![error](https://cloud.githubusercontent.com/assets/15244940/21170120/5711302a-c1e8-11e6-874e-62581d4730ee.png)

**Comment by williamhodges** [comment]
Can you give us more information? Code snippets? Browser console output when debugging?

**Comment by stixoffire** [comment]
@arunkumar12712 - if it is the standard application - check your database , especially if you are using a join - make sure you have data in the data base. If it is a join and these columns are showing - make sure you have the expression declarations on your properties with in the xyzRow.cs file.
