### ISSUE TITLE
Mixed TypeScript / Saltaralle for customer Dialog

### ISSUE THREAD

**Issue by okw1285** [volkanceylan/Serenity#1632]
Hi,

can Saltaralle contain partial methods working together with typescript method?

Example, for Customer Dialog can i have remain the old Saltaralle method code and together write new method Typescript code customer dialog concurrently?

**Comment by volkanceylan** [comment]
Not partial methods, but you can call methods from vice versa.

**Comment by okw1285** [comment]
Thanks. But how can i call the methods written in Typescipt from Saltaralle?

**Comment by volkanceylan** [comment]
See how do we call javascript methods from Saltaralle, with imports, inlinecode etc.
