### ISSUE TITLE
FilterField and FilterValue not working

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1633]
[DisplayName("Patient"), NotNull, ForeignKey("[dbo].[Patient]", "Id"), LeftJoin("jPatient"), TextualField("PatientName"), EditLink, LookupInclude]

[LookupEditor(typeof(Patient.Entities.PatientRow), InplaceAdd = true, __FilterField = nameof(Patient.Entities.PatientRow.Gender), FilterValue = 2__)]

public Int32? PatientId { get { return Fields.PatientId[this]; } set { Fields.PatientId[this] = value; } }
public partial class RowFields { public Int32Field PatientId; }

_**Above is returning empty results in dropdown list**_

**Comment by vinaykulkarni89** [comment]
above lookup is not refreshed until i recompile project

**Comment by volkanceylan** [comment]
See FAQ, Guide
