### ISSUE TITLE
PropertyGrid.cs change adding Categories/Category divs to login form

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1634]
I suspect a recent change to Serenity.Script.UI/PropertyGrid/PropertyGrid.cs  is causing div class="categories">div class="category"> to be added to the LoginForm's PropertyGrid

Old DOM:
![oldform](https://cloud.githubusercontent.com/assets/2817543/21203181/358ef3ec-c206-11e6-96f1-e1f1e2af0e28.png)

New DOM:

![newform](https://cloud.githubusercontent.com/assets/2817543/21203202/4568925a-c206-11e6-8f24-97110eeea62b.png)

And here's the resulting tall login form:
![loginform](https://cloud.githubusercontent.com/assets/2817543/21203305/bb02463c-c206-11e6-83b7-e50ebe000f34.png)

**Comment by volkanceylan** [comment]
Yes, add a .s-LoginForm .s-PropertyGrid .categories { height: auto }. Ill remove default height for categories div later.

**Comment by wldkrd1** [comment]
Replacing .s-LoginForm with .s-LoginPanel fixes it. Thanks!

.s-LoginPanel .s-PropertyGrid .categories { height: auto }
