### ISSUE TITLE
"notnull" not working When I use "MultipleFileUploadEditor" 

### ISSUE THREAD

**Issue by KhatamiMasoud** [volkanceylan/Serenity#1635]
Hi,
When using MultipleFileUploadEditor with notnull ,It's not working for me.
 [DisplayName("Gallery Images"),MultipleFileUploadEditor(FilenameFormat = "HProperty/GalleryImages/~"),NotNull]

**Comment by KhatamiMasoud** [comment]
I want user attach at least one image.

**Comment by volkanceylan** [comment]
Add a custom validation rule
