### ISSUE TITLE
Customize layout of a propertygrid

### ISSUE THREAD

**Issue by vihorlat** [volkanceylan/Serenity#1637]
Hello,
what would be a serenity-compatible way to customize layout of a Panel, e.g. the AccountChangePassword.cshtml from serenity demo.
I would like to assign css classes, so that the layout is responsive.
Could I create my own panel by inheriting a serenity class?

Thank you very much

**Comment by volkanceylan** [comment]
There is panel sample.

**Comment by vihorlat** [comment]
http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077
Awesome thank you!
