### ISSUE TITLE
IsntanceName and DisplayName are not working

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1638]
I have changed the InstanceName and DisplayName but these changes are not reflected in Dialog and Editor
(I have used same table for two different modules, is that causing issue?)

**Comment by volkanceylan** [comment]
You shouldn't use same table twice.

**Comment by vinaykulkarni89** [comment]
Thankyou for reply, but is there any way i can change the InstanceName and DisplayName for current situation

**Comment by volkanceylan** [comment]
No, there isn't. Remove one of rows.

**Comment by vinaykulkarni89** [comment]
OK thankyou
