### ISSUE TITLE
HTTP Error 404.0 - Not Found Error handler

### ISSUE THREAD

**Issue by alitarkian** [volkanceylan/Serenity#1639]
Hi dear,
can you help me to config route to handle error for "HTTP Error 404.0 - Not Found" on Serenity
I try but don't work. I tired.
thank you

**Comment by volkanceylan** [comment]
Serenity is a standard MVC application. There is nothing different or special about handling 404.

**Comment by stixoffire** [comment]
@alitarkian  are you getting this while trying to debug or on the webserver. If while debugging you might be trying to debug your application when your .cshtml file is the selected file - in which case VS tries to get to that page. If on the IIS server - you need to check your set up of IIS.

**Comment by alitarkian** [comment]
@volkanceylan @stixoffire 
thank you, I check it.
