### ISSUE TITLE
How to login through webapi

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#164]
Now I have a requirement that user can edit his own tenant data through web api ,how can I auth this,Could you give me some suggestion?

**Comment by volkanceylan** [comment]
Use RestSharp or WebClient with a CookieContainer directly to login using Account/Login. Then call services like you'd do with a JSON/Rest service.

**Comment by volkanceylan** [comment]
Reopen if didn't help. Also there is some sample in VS gallery for android.

**Comment by ChenZhaobin** [comment]
No ,I am in a holiday now ,so not reply this .It helps  me a lot and I have  known more powerful function with serenity,I hava done a multinant backoffice for my company for partners who use our service .Thank you so much.Web api we use HMAC validation ,so I use common three layer to do this ,Serenity as the backoffice.
