### ISSUE TITLE
Using foreach loop gives error as

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1640]
Following error is thrown when i access my calendar from NagivationItems

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 77: 
Line 78:             events: [
Line 79:             @foreach (var d in Model.Details)
Line 80:             {

________________________________________________________________________________________________
_Below is AppointmentCalender.cs file_

namespace TabeClinic.Appointment
{
    using Entities;
    using Serenity.Data;
    using System.Collections.Generic;

    public class Calender
    {
        public object GetData()
        {
            var data = new AppointmentCalenderSub();

            using (var connection = SqlConnections.NewFor<AppointmentRow>())
            {
                var od = AppointmentRow.Fields;
                data.Details = connection.List<AppointmentRow>(q => q
                    .SelectTableFields()
                    .Select(od.PatientName)
                    .Select(od.Appointment)
                    .Where(od.DisplayName == Serenity.Authorization.UserDefinition.DisplayName));
            }
            return data;
        }
    }

    public class AppointmentCalenderSub
    {
        public List<AppointmentRow> Details { get; set; }
    }
}

_____________________________________________________________________________________

_and AppointmentCalender.cs file is as below_

@model TabeClinic.Appointment.AppointmentCalenderSub
@{
    ViewData["Title"] = "Calendar";
}

@foreach (var d in Model.Details)
{
//Html code
}

_____________________________________________________________________________________

_Code in NavigationItems.cs_

**[assembly: NavigationLink(1001, "Appointment Calendar", url: "~/Appointment/Appointment/Calender", permission: "", icon: "fa-calendar")]**

_______________________________________________________________________________________

_Code in AppointmentPage.cs_

**public ActionResult Calender()
{
            return View("~/Modules/Appointment/Appointment/AppointmentCalender.cshtml");
}**

**Comment by VictorTomaili** [comment]
Where are you set data for model?

**Comment by vinaykulkarni89** [comment]
In AppointmentCalender.cs

**Comment by vinaykulkarni89** [comment]
I'm new to MVC and ASP technology, please simplify your question

**Comment by VictorTomaili** [comment]
`return View("~/Modules/Appointment/Appointment/AppointmentCalender.cshtml", [model??]);`

**Comment by VictorTomaili** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Dashboard/DashboardPage.cs#L37

**Comment by volkanceylan** [comment]
Please read a C# and ASP.NET MVC guide first.

**Comment by vinaykulkarni89** [comment]
Thankyou @VictorTomaili and @volkanceylan  for helping, after going through basics i was able to accomplished above mentioned task
