### ISSUE TITLE
Reporting Sample of Northwind object does not support this method. executeReport.

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1641]
I was running the Northwind sample Reporting where there are two samples CustomerGross and Sales By Cat  and I receive the following error when clicking the excel icon: - of course there also looks to be no data in the popped up grids.
 
The code breaks in 
ReportDialog.ts 
getToolBarButtons{ onClick: () => this.executeReport('_blank', 'xlsx', true) }

Unhandled exception at line 7200, column 48 in http://localhost:...../Site/Tutorials.Web.js 

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'executeReport'

**Comment by volkanceylan** [comment]
It works in serenity.is, so i'm pretty sure you miss some file.

**Comment by jmace** [comment]
@stixoffire , check to see that all of the northwind .cshtml pages are being included in the publish.

**Comment by volkanceylan** [comment]
Also try taking latest ReportDialog.ts, your project might have an out of date version.

**Comment by stixoffire** [comment]
@volkanceylan - I downloaded vsix 2.6.10.2 from vs gallery yesterday (as I wanted to try out the other samples and see the examples ) - I also have a separate project I Nugetted up to 2.6.10 these both exhibit the same issue.

I have an older test project 2.6.3.0 and it works just as expected.

**Comment by stixoffire** [comment]
@volkanceylan after running the other build that worked it seems I am able to run these in 2.6.10.0  must be something was cached that should not have been. Sorry for the trouble. Thought for sure with 2 projects doing the same thing and one earlier version working - that something broke.
