### ISSUE TITLE
How to validate duplicate field on Database

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1642]
Hellow.

How to validate if the fied exist in Database.

Example of the message displayed when you tried to enter the record
![image](https://cloud.githubusercontent.com/assets/22305532/21242683/d69d9f00-c2eb-11e6-9859-2d30b29ccc6c.png)

How can I validate the field and display the message?

**Comment by abelal83** [comment]
do you mean the value in field or a the column in database?

if column surely want to check this manually and amend code to remove fields?

**Comment by haajit** [comment]
> Add UniqueConstrait, see guide.

Hi

**Comment by haajit** [comment]
> Add UniqueConstrait, see guide.

Hi
I used
[UniqueConstraint("Fieldname", CheckBeforeSave = true,ErrorMessage = "Message of Error",IgnoreDeleted = true)]
but it dosn't work!

**Comment by VictorTomaili** [comment]
Please use [discussions ](https://github.com/serenity-is/Serenity/discussions)
