### ISSUE TITLE
Reloading full grid (including column headers and custom Attributes) from call within the xxGrid class

### ISSUE THREAD

**Issue by DGoertzen** [volkanceylan/Serenity#1643]
How do I force reload of all the parameters associated with a grid, including the custom attributes/captions (e.g. Formatters) associated with the grid, from a call within the xxGrid.ts file (e.g. upon the selection of a drop down list)?

The more detailed description of my problem is:
I have coded a solution where the custom attributes of the Field items that are members of "public static readonly RowFields Fields" defined in the xxRow.cs file are changed from functions within MyListHander in xxRepository.cs.  For example, I am changing some of the Formatters and some of the captions of the columns.   In xxGrid.ts, I have added a DateYearEditor, and would like the entire Grid to be updated on the changeSelect2 handler.  The code I am using right now is:

        protected createToolbarExtensions(): void {
            super.createToolbarExtensions();

            let opt: Serenity.DateYearEditorOptions = {
                minYear: '2007',
                maxYear: '2017',
                descending: false,
            };

            this.targetYear = Serenity.Widget.create({
                type: Serenity.DateYearEditor,
                element: el => el.appendTo(this.toolbar.element).attr('placeholder', ''),
                options: opt
            });
            this.targetYear.value = '2016';

            this.targetYear.changeSelect2(e => {
                (this.view.params as DisplayTimeTableListRequest).Year = Number(this.targetYear.value);
                this.refresh();
            });
        }

The call to this.refresh() above only refreshes the data in the grid, not the custom attributes or column captions.
If I click on the sidebar to select the table, the custom attributes and column captions that I changed do load properly.  However, I have not been able to figure out how to make the updated attributes/captions load properly from a call within xxGrid.ts.  I have tried using code like below in the changeSelect2 handler, but that does not seem to work either.

          var request = this.view.params as DisplayTimeTableListRequest;
          request.Year = Number(this.targetYear.value);
          Q.serviceRequest('Time/DisplayTimeTable/List', request, (response) => { });

or

          this.init();

Note that in the MyListHandler, after making changes to the Field items that are members of "public static readonly RowFields Fields", I do call:

          TwoLevelCache.ExpireGroupItems(MyRow.Fields.GenerationKey);
          DynamicScriptManager.Reset();

I can seem to get it to work by adding the below code to my changeSelect2 handler, but it seems to me there may be a better way that doesn't cause such a long reload time.  Not sure though.

          window.location.href = '/Time/DisplayTimeTable';

I am sure I am overlooking some simple thing.  Thanks for your help.

**Comment by john20xdoe** [comment]
This is partly a SlickGrid topic.

To refresh the viewport (meaning just refresh the rows inside the grid, no new ajax call), use `this.slickGrid.view.refresh()`

To refresh the grid (fire the call to the endpoint for the list of rows), use 'this.slickGrid.refresh()`

You may or you may not need to invalidate the grid contents before triggering the above statements. `this.slickGrid.invalidateRows()`

**Comment by DGoertzen** [comment]
Thanks for the idea, but this did not work for me.  For reference, the specific calls I made were:

                this.slickGrid.invalidateAllRows();
                this.refresh();

 It does redraw the slickGrid, but does not update the custom attributes/captions (e.g. Formatters) that are associated with the grid on the server side.  I think what is needed is for the client to reload the dynamically generated files ColumnsBundle.js and FormBundle.js.  Is there a call that can be made to xxGrid that forces a reload of these files, or is the only way to reload the whole page by calling   window.location.href = '/Time/DisplayTimeTable';?

**Comment by sayuga** [comment]
Try using Q.reloadLookup("module.LookupEditorName").  You might also be able to set the expiration to -1

**Comment by DGoertzen** [comment]
Thanks for the tip.  Q.readLookup didn't work as I was not trying to reload a lookup table.  However, it did point me in the direction to try Q.ScriptData.reload.  I changed my code to

                Q.ScriptData.reload('Columns.Time.DisplayTimeTable');
                Q.ScriptData.reload('Form.Time.DisplayTimeTable');
                this.slickGrid.invalidateAllRows();
                this.refresh();

However, this still did not seem to change the custom attributes/captions (e.g. Formatters) on the client that are associated with the updated custom attributes/captions on the server.

I don't understand how to set the expiration to -1 as was suggested.  Can you clarify how to do that?

**Comment by volkanceylan** [comment]
Most grid methods like GetColumns etc. are only called once, and should only be called once. I don't understand what you are trying to do exactly, but if that many things change, destroy the grid and create a new one.
