### ISSUE TITLE
Wiki lateral menu

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1644]
Hi @volkanceylan 
I have tried adding the side menu to the wiki, but without success. I want to add this menu to rationalize the wiki navigation. Some like this

![cattura](https://cloud.githubusercontent.com/assets/16304015/21255702/d74d7b32-c36d-11e6-87ee-78f075232d93.PNG)

This change requires special editing privileges?

**Comment by volkanceylan** [comment]
Hi @Estrusco, i've tried to add a sidebar, see if you can edit it.

**Comment by Estrusco** [comment]
Perfect! Thank you 👍
