### ISSUE TITLE
typescript issue

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1645]
The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe" -project "C:\...\F_Serene\F_Serene.Web\tsconfig.json"" exited with code 3.

i think that code 3 means path issue. The warning has to do with the line that i am declaring the UserPermissionRow. Any ideas how to fix this?

**Comment by Estrusco** [comment]
Have you installed TypeScript?

**Comment by satsokn** [comment]
yes

**Comment by satsokn** [comment]
Any Ideas?

**Comment by volkanceylan** [comment]
Do you know that there is an output window in Visual Studio?

**Comment by volkanceylan** [comment]
Also check that you have tsc.exe at that location. You probably installed 2.1 not 2.0,

**Comment by satsokn** [comment]
i have installed 1.8 but demo RolePermission are working. Can i define with version is going to be used?
Sorry if i am being irritating

**Comment by volkanceylan** [comment]
Install 2.0. If you have to use 1.8, then change TypescriptToolsVersion in csproj.
