### ISSUE TITLE
read.cshtml issue & others

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1646]
Line 209 in read.cshtml has a unmatched </div> tag,
jvectormap has a // comment at line 22,
raphael-min.js has a faulty switch at:  switch(!(a[0]in f)&&(b.qx=b.qy=null),a[0]){case"M"
jspdf.autotable has at line 1: declare interface jsPDF ... , should be:  interface jsPDF ...
in site.membership.less, at /*AdminLTE style login/register box*/
  padding-bottom: 0 0 20px;
should be:     padding-bottom: 20px;
These are minor issues.

**Comment by volkanceylan** [comment]
Thanks, mostly third party issues.
