### ISSUE TITLE
SQL server computer column

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1647]
hi all, 

First of all I apologise if this is available somewhere but I've read guide, looked at example but unable to find.

I have a SQL server computed column, when adding a new record through Serenity form it's visible but set to readonly(true), however the form will not save with the mssage "The column "DaysToDueDate" cannot be modified because it is either a computed column or is the result of a UNION operator."

Are there any attributes to force Serene to realise this is a computed value on server side?

Many thanks,

**Comment by stixoffire** [comment]
@abelal83  I believe you need to declare the column as  NOTMAPPED

**Comment by abelal83** [comment]
thank you @stixoffire 
I resolved by setting field to computed value instead.

**Comment by volkanceylan** [comment]
Insertable(false), Updatable(false) could also work.

**Comment by dudeman972** [comment]
Dear Volkan,
I have a similar problem.  I tired your solution, but it doesn't seems to be working in my situation.  In my situation i am explicitly saving the entity by calling uow.Connection.UpdateById(myEntity)  on the server side.  I suspect that doing so ignores those flags.  I decorated the offending property with the following:
Insertable(insertable: false), Updatable(updatable:false)  .  There are no other attributes on that property.

**Comment by volkanceylan** [comment]
Don't load entity by connection.ById, this is not entity framework, just update fields you need to update

**Comment by dudeman972** [comment]
Thanks,  That worked!
