### ISSUE TITLE
Extend ServerTypingsGenerator for static types with const field values

### ISSUE THREAD

**Issue by florin-nitulescu** [volkanceylan/Serenity#1648]
It would be great if I could add a` [ScriptImport]` attribute on a static class where I group some string constants that I would like to be accessible from typescript code. 

In my app I've successfully used the` [DataScript]` attribute to get the user settings in TS scripts (key value pairs), but I have some predefined settings that I would like to access server side and client side using some const field values.

Thank you!

**Comment by volkanceylan** [comment]
It could be possible, but not very critical i think.
