### ISSUE TITLE
Making fields uneditable

### ISSUE THREAD

**Issue by bardagadvergur** [volkanceylan/Serenity#165]
I want to make only a part of fields on a form editable. How can I do that and can you point me to a resource on the possibilities on the forms?

**Comment by ademc** [comment]
Which user control you use?

To set readonly

EditorUtils.SetReadonly(form.controlName,false)

**Comment by bardagadvergur** [comment]
Not sure what you mean by which user control ... but I achieved what I wanted by this:

        [Updatable(false)]
        public String OrderId { get; set;  }

**Comment by ademc** [comment]
OK you can use

```
 [ReadOnly(true)]
 public String OrderId { get; set;  }
```
