### ISSUE TITLE
Issue in VS 2017 using MySql

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1651]
I got this error in VS 2017, the error is not present in VS 2015

> MySql.Data.MySqlClient.MySqlException occurred
>   HResult=0x80004005
>   Message=Fatal error encountered during command execution.
>   Source=MySql.Data
>   StackTrace:
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
>    at Serenity.Data.SqlHelper.ExecuteNonQuery(IDbCommand command)
> ....
> Inner Exception 1:
> MySqlException: Parameter '@ErrorHash' must be defined.

The error occurs when the program tries to write to the exceptions table.

**Comment by volkanceylan** [comment]
We don't support VS2017, but anyway MySql acting different in VS versions not expected.
