### ISSUE TITLE
difference between `ForeignKey("t", "f"), LeftJoin("c")`   and   `LeftJoin("c",t","f")`

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#1653]
In your example, you always use     **ForeignKey("t", "f"), LeftJoin("c"),**
but I find  **LeftJoin("c",t","f")**   can do almost the same work.

Is there any difference between these two?

**Comment by volkanceylan** [comment]
First one works on properties while second one only on top of row. And second one doesn't let you specify foreign key.
