### ISSUE TITLE
Login Ekranında Firma Seçtirmek

### ISSUE THREAD

**Issue by ComertAhmetSahin** [volkanceylan/Serenity#1654]
Kullanıcı Login Sırasında Lookup ile firma seçtirip daha sonra modüller içersinde seçilen firma bilgisine göre filter eklemek istiyoruz. örneği varmıdır ?

**Comment by volkanceylan** [comment]
Örneği yok, ancak login formuna bir dropdown ekleyip cookie lerle deneyiniz.
