### ISSUE TITLE
Calling Dialog from Dashboard results in stranger things

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#1655]
Hi fellow Serenists,

I have a strange problem which I haven't found a solution to.

My dialogs are all set up and I have polished them very well, in my opinion.
But whenever I want to access/call them directly from the Dashboard - they get messed up.

Please see here when I access a dialog from a standard route (menu -> grid -> new{})

![image](https://cloud.githubusercontent.com/assets/15879719/21291302/63a67c14-c4d1-11e6-981f-acdb8601d25e.png)

I can call this Dialog directly from the Dashboard with the following code:

```
    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h4>Utanlands</h4>
                <p>-skrá nýja beiðni</p>
            </div>
            <div class="icon">
                <i class="ion-earth"></i>
            </div>
            <a onclick="opnaUtan()"  class="small-box-footer">Smella hér <i class="fa fa-arrow-circle-right"></i></a>
            <script>
                function opnaUtan()
                {
                    new PerDiem.Ferdir.UtanlandsDialog().dialogOpen();
                }
            </script>
        </div>
    </div><!-- ./col -->
```

BUT this is what happens when called from the Dashboard:

![image](https://cloud.githubusercontent.com/assets/15879719/21291292/0f793532-c4d1-11e6-8a04-736f6f26de9f.png)

- There is a lot of unwanted/useless buttons appearing
- The "new" dialog doesn't follow the TypeScript functions and calculations in the UtanlandsDialog.ts
- E.g. the auto serial numbering doesn't work
- The dates are in US format and also in forbidden 12/18/2016 us format?!

Browser console does not show anything peculiar and I doubt that this is permission related.

What can the reason be behind these problems - I would really like to call the original and correct dialogs directly from the dashboard.

All helps is very appreciated.

Thank you :)

**Comment by dfaruque** [comment]
try one of these methods

        loadById(id: any)
        loadByIdAndOpenDialog
        loadEntity(entity: any): void
        loadEntityAndOpenDialog(entity: any): void
        loadNewAndOpenDialog()

**Comment by biggikalli** [comment]
Thank you dear @dfaruque,

`loadNewAndOpenDialog()` made the trick.

Only thing that was wrong afterwards, was the datepicker.
It was all messed up and showed the US dateformat with either mm.DD.yyyy or mm/DD/yyyy.

It was very strange but I found the problem. It was that DashboardIndex.cshtml was calling 3 scripts for datepickers and that was interfering with the form.

It was enough to comment out two of them and then it all worked perfectly:
```
@*<script src="~/Scripts/daterangepicker/daterangepicker.js"></script>
<script src="~/Scripts/datepicker/bootstrap-datepicker.js"></script>*@
```

Thank you again.
