### ISSUE TITLE
Can't find custom Select2Editor without @Serenity.Decorators.registerEditor()

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#1657]
I want to use a custom  Select2Editor  without @Serenity.Decorators.registerEditor(),

but got error here
![alt text](https://snag.gy/7T4tpA.jpg)
my code:
![alt text](https://snag.gy/43Tjcq.jpg)

if I add **@Serenity.Decorators.registerEditor()**
![alt text](https://snag.gy/MB95vN.jpg)
then I can find it.

I don't know why as code below can be found too.
![alt text](https://snag.gy/gKDPyn.jpg)

why Serenity.Widget<any> can while  Serenity.Select2Editor<any,any> can't.

**Comment by volkanceylan** [comment]
That is required, period.

**Comment by tky753** [comment]
@volkanceylan ,well, if I have to add **@Serenity.Decorators.registerEditor()**, is it possible to stop generaging file by **ClientTypes.tt**, as I want to rewrite AAAEditorAttribute.cs 
If can't, I may have to inherit AAAEditorAttribute class.

**Comment by tky753** [comment]
OK,don't have to inherit ,I see it's a partial class
