### ISSUE TITLE
CommaSeperated values contain commas!

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1659]
Hi all, 

I have a unique requirement to use comma separated values with a lookup editor however, the values contain comma as well.

for example, the drop will show as below
Test, test1
Test, test2
Test, test3

on initial save all looks good, the values are saved to database but when we load the record in Serene form the values are blank but look OK in grid.

Can we tell Serene to use to something else instead of comma to separate values, such as semi colon?

**Comment by volkanceylan** [comment]
No you can't. I don't think Select2 supports this either.

**Comment by abelal83** [comment]
there is an option to change token used here [https://github.com/select2/select2/issues/4596]
here's the excerpt

```
$('#test').select2({
multiple:true,
placeholder: 'Select value...'
,tokenSeparators: [','],
});
```
I'm guessing serenity doesn't have an attribute for this, is there a way for me to override in typescript?

**Comment by volkanceylan** [comment]
If so that should work for Select2 side. But editor value will still might be invalid, need to test that. For now, i'd suggest you use a unmapped List field, and serialize / deserialize its value, at getSaveEntity, loadEntity etc. or repository side.
