### ISSUE TITLE
delete request

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1660]
how can i get the whole entity (like in save request) when i call delete service. i changed deleterequest to saverequest but the entity returns null. i get only entityId.(i also changed it inside service)
thanks

**Comment by Estrusco** [comment]
Why you want the Delete return the entity that as been deleted? If you call Delete with ID for entity to delete, you can call first a Retrieve with ID to get the full entity.

**Comment by satsokn** [comment]
when i open a row from grid i use retrieve to get data. if i use update i get the whole entity from save request. Instead of using update i push the deletebutton. so inside the delete service i would like to get the whole entity.

**Comment by Estrusco** [comment]
You can create yout own delete action in Endpoint and in Repository with personal Request and Retrive. Some like

```cs
[HttpPost]
public MyDeleteResponse MyDelete(IUnitOfWork uow, MyDeleteRequest request)
{
    return new MyRepository().MyDelete(uow, request);
}
```
