### ISSUE TITLE
lookup issue

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1662]
What class do i need to create to  use [LookupScript("path")] so the lookup from RoleCheckEditor loads from my own entity (which probably would be inside the created class)?
thanks a lot

**Comment by dfaruque** [comment]
What are you exactly trying to do. It seems hard to understand.

Please clearly mention your problem.

**Comment by satsokn** [comment]
i changed all services in repository to get data from servicestack. When i try to apply a role on a user from the button inside the grid, the RoleCheckEditor.ts has a lookup service to get the checkbox options(getTreeItems())(which gets its valuews from RoleRow). Is there any way to get these checkbox options from another class?
