### ISSUE TITLE
Custom editor

### ISSUE THREAD

**Issue by sottnik** [volkanceylan/Serenity#1664]
Hello guys
We have table column where the values can be edited with different editors according to its type. We need quite complex editor to handle value of recurring event (stored as a text).
We tried to use the TimeEditor from the Serenity sources ( \Serenity.Script.UI\Editor\TimeEditor.cs) as starting point and modify it for our needs, but we failed to install all dependencies for Saltarelle, etc in our own product.
When we tried to add the reference to Serenity.Script to be able to use the Widget class, the compilation failed with thousands errors mostly about ambiguous references.
Can you point us in the right direction how to achieve this?

**Comment by dfaruque** [comment]
forgot Saltarelle, try using typescript.

take this as sample https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Note/NotesEditor.ts

hope this will help somehow. :)

**Comment by volkanceylan** [comment]
You may also make use of its generated JS source in Serenity.Script.UI.js
