### ISSUE TITLE
Using GoogleMap Widget

### ISSUE THREAD

**Issue by vietnguyen8392** [volkanceylan/Serenity#1667]
I tried to write a simple Script to use Google Map in an EntityDialog like this:
```
constructor(){
super();
let options: Serenity.GoogleMapOptions = {
                latitude : 41.0191602,
                longitude : 29.086761,
                zoom: 16
            }
            var map = new Serenity.GoogleMap(this.byId('map'), options).init();
}
```
However, when I run my project to browser, it doesn't work and the Console log show "google is not defined". Is there any missing library?

**Comment by volkanceylan** [comment]
Include google maps

**Comment by MaradiagaSistemas** [comment]
@vietnguyen8392 Did you solve this? I want to populate this widget but without success!
