### ISSUE TITLE
How can i use Q.reloadLookup("xxx.xxxxxxx")  in .ts

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#1668]
Dear Volkan,

How can i use Q.reloadLookup("xxx.xxxxxxx") to get latest item list? It seems not work. It seems just work at the beginning of whole program start. However sometime, during program lifecycle i have added some new data dictionary items, and immediately want to pick it in the related dropdown list. 

Thanks for your advise.
Harry

**Comment by dfaruque** [comment]
Q.reloadLookup(someRow.lookupKey);

**Comment by harrypassport** [comment]
Seems need to use Q.reloadLookup("someRow.lookupKey") rather Q.reloadLookup(someRow.lookupKey); But it can't be got the lastest item list form database for me. I don't why.


Thanks for your advise.
Harry

**Comment by harrypassport** [comment]
Who can answer my questions? It's appreciated to get your help.

When I use Q.reloadLookup("GKL.V_GetMappedDevices") to get latest item list just added before, but I fail to get that(Below is my lookup script), it just get old item list excluding new item.

So it there other way to get the latest itemlist in xx.ts?


Thanks,
Harry


    [LookupScript("GKL.V_GetMappedDevices")]
    public class V_GetMappedDevicesLookup : RowLookupScript<GKL.Entities.V_GetMappedDevicesRow>
    {
        public V_GetMappedDevicesLookup()
        {
            this.IdField = Entities.V_GetMappedDevicesRow.Fields.Id.PropertyName;
            this.TextField = Entities.V_GetMappedDevicesRow.Fields.Desp.PropertyName;
            Permission = "*";
        }
 protected override void PrepareQuery(SqlQuery query)
        {
             var fld = Entities.V_GetMappedDevicesRow.Fields;
            query.Distinct(true)
                .Select(fld.Id, "DevId")
                .Select(fld.NodId, "ParentId")
                .Select(fld.Desp, "Name")
                .OrderBy(fld.Id);
    }
}

**Comment by xareas** [comment]
Removes the data from the cache

public class V_GetMappedDevicesLookup : RowLookupScript<GKL.Entities.V_GetMappedDevicesRow>
{
    public V_GetMappedDevicesLookup()
    {
         Expiration = TimeSpan.FromDays(-1); //add this line
        this.IdField = Entities.V_GetMappedDevicesRow.Fields.Id.PropertyName;
        this.TextField = Entities.V_GetMappedDevicesRow.Fields.Desp.PropertyName;
        Permission = "*";
    }

**Comment by dfaruque** [comment]
try calling `someRow.getLookup().update();`

**Comment by harrypassport** [comment]
It's fantastic. Many thanks xareas's advice.
Harry
