### ISSUE TITLE
treeItems of RoleRow

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1669]
i am using servicestack to get data. i changed every part of code that gets data directly from database. i am not using any connection string. when i try to apply a role to a user, i press button "edit roles" inside user grid but i cant load getTreeItems inside RoleCheckEditor(probably because the lookup refers to RoleRow ).  Any suggestions
thanks

**Comment by volkanceylan** [comment]
No suggestions.

**Comment by dfaruque** [comment]
the RoleCheckEditor is designed to work with RoleRow.
Btw you may write another editor to work with your data.
