### ISSUE TITLE
Repository not getting values of foreign fileds 

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1670]
I'm doing some task in

protected override void AfterSave()
{
                base.AfterSave();
        
Here i'm trying to access the value of CustomerName where CustomerName is Foreign table filed linked with CustomerId

I'm able to get Request.Entity.CustomerId , where CustomerId is foreign field from table customer, but when trying to access Request.Entity.CustomerName i get following error

              **_Object reference not set to an instance of an object._**
}

**Comment by stixoffire** [comment]
@vinaykulkarni89 
Select it in your aftersave method by using the id - I think the framework is lazy loading - I had to select the entity by id  from the foreign table  - I was working in the beforesave method.  I do not know if this is the right way in serenity but it did work for me.

**Comment by volkanceylan** [comment]
You can also override PrepareQuery and select that field. But that won't work if customer ID change on update.

**Comment by vinaykulkarni89** [comment]
Thnakyou @stixoffire  and @volkanceylan  for your time, but rather i was thinking to get values from Dialog, and pass to function
e.g:
I was sending the email after saved, but thinking to provide send mail button in dialog and onclick event calls the sendmail(),

in Dialog:

buttons.push({
                title: 'Send Mail',
                cssClass: 'mail-button',
                onClick: () => {
               //How can i call the SendMail() here     
                }
            });

Where can i define the following function so that it can be accessible in dialog
public void SendMail(String To, String Subject, String Body)
{
            var message = new MailMessage();
            var addr = new MailAddress("mymail@mysite.com", "Vinay Kulkarni");

            message.To.Add(To);
            message.Subject = Subject;
            message.Body = Body;
            message.IsBodyHtml = true;
            message.From = addr;
            message.Sender = addr;

            var mail = new SmtpClient();

            //Configuration
            NetworkCredential nc = new NetworkCredential("test@test.com", "password");
            mail.Credentials = nc;
            mail.EnableSsl = true;
            mail.Host = "smtp.live.com";
            mail.Port = 587;

            mail.Send(message);
}

**Comment by xareas** [comment]
add method in your ClassEmailEndPoint, example SendEmail(IDbConnection connection, EmailRequest request), and then invoke in javascript ClassEmailService.SendEmail({paremetersEmailRequest}).

check this
https://volkanceylan.gitbooks.io/serenity-guide/content/services/service_endpoints.html

**Comment by vinaykulkarni89** [comment]
@xareas thankyou for your valuable time

**Comment by vinaykulkarni89** [comment]
Is there any other way to get values of foreign fields in AfterSave() or @volkanceylan please elaborate how can i accomplish my task with PrepareQuery

**Comment by volkanceylan** [comment]
Type PrepareQuery in VS search and see how...
