### ISSUE TITLE
initialize dialog with different tab page active

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#1672]
I have a dialog with multiple tab pages, I want to open it with the second tab page,
I tried to reload initDialog like this:
```
protected initDialog(): void {
            super.initDialog();
            Serenity.TabsExtensions.selectTab(this.tabs, 'MyTabKey');
        }
```
It does not work, 
this function(**Serenity.TabsExtensions.selectTab(this.tabs, 'MyTabKey');**) works if the dialog is already open, 
but if I want to change tab page when initializing the dialog,
where should I place it?

**Comment by volkanceylan** [comment]
onDialogOpen

**Comment by tky753** [comment]
@volkanceylan   
I wonder if this is a bug ,if I execute code below, the DialogOpen function does not invoke,
```
 let dlg = new MyDialog(<MyDialogOptions>{
                        TabKey:'Dtl'
                    });
                    this.initDialog(dlg);
                    dlg.loadEntityAndOpenDialog(<XSEnumRow>{
                        Id: item.Id
                    });
```
I must add **dlg.dialogOpen();** after loadEntityAndOpenDialog, then the DialogOpen function invokes.

Any way, The problem is solved, Thanks.
