### ISSUE TITLE
Grid serach and Oracle case sensitive

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1673]
As you know Oracle is data case sensitive, is there away to convert the QuickSearch text and the searchable columns values to lower()?

**Comment by volkanceylan** [comment]
```
    public class MyOracleDialect : OracleDialect, ISqlDialect
    {
        bool ISqlDialect.IsLikeCaseSensitive
        {
            get { return true; }
        }
    }

SqlConnections.GetConnectionString("Default").Dialect = new MyOracleDialect();
```

**Comment by mhussein67** [comment]
ok I have defined the class, but where to add: 

`SqlConnections.GetConnectionString("Default").Dialect = new MyOracleDialect();`

**Comment by volkanceylan** [comment]
@mhussein67 SiteInitialization, please read the guide

**Comment by mhussein67** [comment]
Sorry it seems I'm tired:) Thanks very much it works like magic
