### ISSUE TITLE
Aurelia Integration

### ISSUE THREAD

**Issue by vorgang** [volkanceylan/Serenity#1675]
Hi, I'm just wondering if anyone has tried to integrate the Aurelia Framework into a project generated using Serenity.  If so, how did it go?

Thanks,
Dave

**Comment by williamhodges** [comment]
I highly doubt it since Serenity uses Typescript which is a super set of javascript. Aurelia Framework seems to be the same way.

**Comment by vorgang** [comment]
Yes, Aurelia can use Typescript but I don't understand why that would prevent integrating Aurelia in a Asp.Net application. 

I'm just wondering if it can be done and if anybody has tried it.

Thanks

**Comment by dfaruque** [comment]
I don't try aurelia but vuejs

**Comment by volkanceylan** [comment]
Serenity doesn't use MVVM or Virtual DOM. I looked at several options like React, Mithril, Bobril etc. Even though they have some good parts, disadvantages outweigh their advantages, hard to debug, no compile time checking etc.
