### ISSUE TITLE
adding MVC Paging Nuget Package PagedList.MVC ?

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1676]
Is there any reason that PagedList.MVC package could not or should not be used in Serenity ?

I am trying to do simple paging on the dashboard page and maybe it is the wrong approach - I am trying to do this with in the confines of what is already in the serenity application and keep it as clean and as simple as possible.

**Comment by awesomegithubusername** [comment]
Not that I know of. I've tested it in one of my pages and it seems to work just fine.
