### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zebzak** [volkanceylan/Serenity#1677]
I have Visual Studio 2015, trying to setup Serenity by using the new->project->Serenity Project Template
and running into errors

"A problem was encountered creating the sub project 'Serene5.Web'.  
Object reference not set to an instance of an object."

I have all the components needed. 

Is there an Installation Log that will tell me what the issue could be.

Please help.

Regards
zebzak

**Comment by stixoffire** [comment]
@zebzak I installed it with out any issues and I also have VS2015 - which template vsix are you using ?
Did you install the typescript library first ?
Do you have .NET framework 4.5 installed ?

**Comment by volkanceylan** [comment]
See VS logs, use google.
