### ISSUE TITLE
How can I implement dynamically sort through clicking field on Grid header?

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#1678]
Dear Volkan,

Is there any sample for reference? I want to implement dynamically sort the grid view through clicking one of fields on Grid header?

Thanks to get your advice.
Harry

**Comment by dfaruque** [comment]
the grid column is already sortable.
what do you mean by dynamically sort?

**Comment by harrypassport** [comment]
My grid "view.setItems(items, true)", the items is from customize service and not from List service, so how can I  capture the onCLick event for gird header. 

Currently the onClick function in xxxGrid.ts just focus on gird data rows excluing grid header. 
protected onClick(e:JQueryEventObject, row, cell): void 
 {
.... 
....
}


Thanks for your supports.
Harry

**Comment by volkanceylan** [comment]
In memory grids don't support sorting. 

SlickGrid has a OnSort event, and getSortColumns method. See its docs.

**Comment by harrypassport** [comment]
Thanks Volkan.
Harry
