### ISSUE TITLE
How to implement custom functionality

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#168]
How to implement custom functionality in serenity project using MVC. I want custom UI (like AdminLTE/Examples/Register form means own html control) and some logics, so how can be achieve this in serenity project. Is it possible or not. If possible please implement some customize functionality as soon as possible. Please help me.

**Comment by volkanceylan** [comment]
They are ordinary MVC pages, so you can implement custom functionality using MVC guides, check some books. I can only offer help for Serenity specific questions.

**Comment by sayuga** [comment]
Iaxmanp, Microsoft has some decent introductory videos I recommend checking them out on their Virtual Academy. http://www.asp.net/mvc. Additionally, there are many samples and resources you can play with by simply searching for MVC on Google. 

w3Schools is also a good simple introduction to different coding types. 

http://www.w3schools.com/aspnet/mvc_intro.asp

If you look, you can find a lot of reference material online for MVC. It's actually not as difficult to learn.
