### ISSUE TITLE
How to filter a grid using multiple criteria

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1681]
I'm trying to customize a grid's contents in a tabbed dialog, and up until now have been able to do something like this, as shown in the grid samples:

     set automobileLicenceID(value: number) {
            if (this._automobileLicenceID != value) {
                this._automobileLicenceID = value;
                this.setEquality(AutomobileRow.Fields.AutomobileLicence, value);
                this.refresh();
            }
        }

The problem now is I need to filter for *two* variables at the same time, not just for `AutomobileLicence`, but for `AutomobileColor `as well.

I assume calling `this.setEquality(...)` in two different sections will simply overwrite the first equality test with the second, but is there a way to AND them together?  [_Edit: in looking at the Serenity source, it appears setEquality is tied to fields individually, and that you *can* in fact call the method 2, 3, 10 times with different fields and each one will play a part in the final selection?_]

I noticed in the code some samples using `request.Criteria` and `Serenity.Criteria.and(...)`, but they were in an `onViewSubmit()` method and I'm not sure using them outside of that method would work for me in this situation?

**Comment by dfaruque** [comment]
you may try to declare a private field/property in yourGrid.ts
then set that private field/property value whenever you want.
then use the  private field/property in `onViewSubmit() { ... Serenity.Criteria.and(...)}`

**Comment by mhussein67** [comment]
Not sure if this will help you in adding multiple filters, I have a dashboard in my project showing widgets with some values, when the user click on the numbers to display the details, I'm sending a querytsring to  xxxxgrid.ts  in getQuickFilters:

        protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
            let filters = super.getQuickFilters();
            let fld = Students.EnrollmentRow.Fields;

           var v_QueryS = Q.parseQueryString();

            if (v_QueryS.t == "N") {
                Q.first(filters, x => x.field == fld.STYP_DESC).init = w => {
                    (w as Serenity.EnumEditor).value = "New First Time";
                Q.first(filters, x => x.field == fld.GENDER).init = w => {
                    (w as Serenity.EnumEditor).value = "M";
                  };
                };

            if (v_QueryS.PG == "Y") {
                Q.first(filters, x => x.field == fld.POTENTIAL_GRADUATE).init = w => {
                    (w as Serenity.EnumEditor).value = "Y";

                 //add more conditions and filters
                };
            }
               
            return filters;
        }

**Comment by lquantz** [comment]
It looks like using setEquality on both of my fields does AND them together when the service calls are made, so that's good.
