### ISSUE TITLE
cascadeFrom option in QuickFilterOption

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1682]
In:
 [QuickFilterOption("cascadeFrom", "Column_Name")]

If the cascade From Column_Name has no selected value the drop-down filter is showing nothing.

Is there any option to show all values even if the cascade From is not selected?

**Comment by xareas** [comment]
add LookupInclude to ForeignKey

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

**Comment by receptuna** [comment]
[LookupInclude]

**Comment by volkanceylan** [comment]
No there is no such option. FilterField / FilterValue does that but it doesn't work out of the box with cascade. You need to do manual cascade.
