### ISSUE TITLE
How to add multiple criteria in .Where

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1684]
I was wondering how to add multiple criteria in .Where() in following example

var od = OrderDetailRow.Fields;
                data.Details = connection.List<OrderDetailRow>(q => q
                    .SelectTableFields()
                    .Select(od.ProductName)
                    .Select(od.LineTotal)
                    .Where(od.OrderID == this.OrderID));

**Comment by dfaruque** [comment]
try using single 
`&` for (And) 
`|` for (Or)

you may also chain another .Where(...)

**Comment by xareas** [comment]
var sqlOfi = new SqlQuery()
                     .Select("KeyValue")
                     .From("[MasterData].[TableName]")
                     .Where($"Id={Value1} AND Id2={Value2}");

**Comment by vinaykulkarni89** [comment]
Thankyou @dfaruque  and @xareas , it solved my isuue
