### ISSUE TITLE
warning TS2451: Cannot redeclare block-scoped variable 'baseUrl'.

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1685]
After installing typescript 2 I got many warnings on xxxService.ts for the declaration of baseUrl, Retrieve, List... as they are declared on both 
 Modules/Common/Imports/ServerTypings/MyFolder.xxxService.ts
and i already have this on Modules/MyFolder/xxxService.ts

Do I need to keep the Service file in my project folder (Modules/MyFolder/xxxService.ts)?

**Comment by sayuga** [comment]
Did you double check that the proper updates were done? I know that when we moved to Typescript 2 there were some break changes.

https://github.com/volkanceylan/Serenity/issues/1342

**Comment by mhussein67** [comment]
Yes a proper updates were done for ts2, they are just  a warnings the project are built successfully.

I've checked the Northwind samples and found all Service under \Modules\Common\Imports\ServerTypings\
So I'm just wondering if I really need to create the xxxService.ts in my project modules? if I don't need to to do so how the "transform A4 build" are creating them?

Thanks

**Comment by volkanceylan** [comment]
xyzService is created by T4, you shouldn't create them.

**Comment by paulobriennz** [comment]
hi volkanceylan.. ive downloaded very latest serenity.. (which I have been using for a year or so now).. new project.. i run sergen to create my custom entities, build - all good, but then if i run Transform All T4 templates, i get lots of errors like above but on all generated .ts files..  ...Row.ts, ...Form.ts - same issue where there is a duplicate, cannot redeclare block-scoped variable etc.. should i be doing something different now?  i have the latest NodeJS and TypeScript installed.. all is working fine until i run Transform T4 templates..

**Comment by volkanceylan** [comment]
Do you have both YourProject.Web/Imports/ServerTypings and Modules/Common/Imports/ServerTypings  folders?

**Comment by volkanceylan** [comment]
I tried this but can't reproduce. Under Tools -> Extensions Updates -> Tools check that you have TypeScript for Visual Studio 2.1.5, not 1.8.6.

Also, you may try this in tsconfig.json:

```
    "exclude": [
        "Scripts/site/Serene.Web.d.ts",
        "node_modules/"
    ]
```

e.g. adding node_modules/ to excludes.
