### ISSUE TITLE
Lazy / async load grid column

### ISSUE THREAD

**Issue by vihorlat** [volkanceylan/Serenity#1686]
Hello,
I have a database query with two columns that are calculated with SUM / MAX which slows the query down a lot.
I am wondering if / how I could load the grid with all data except these 2 slow columns (so that the user sees something) and asynchronously load the rest ?
My solution suggestion: I put `[Ignore] ` attribute over the 2 columns. I add another method into endpoint / repository to load data of just the 2 columns (and Identifier) by bypassin the `[Ignore]` 

Any other suggestions?

Thank you.

**Comment by volkanceylan** [comment]
There is a asyncpostrender option in SlickGrid, see its docs / examples.

**Comment by vihorlat** [comment]
Perfect, thank you
