### ISSUE TITLE
https://github.com/volkanceylan/Serenity-Tutorials/tree/master/MultiTenancy 

### ISSUE THREAD

**Issue by FARIVER** [volkanceylan/Serenity#1687]
https://github.com/volkanceylan/Serenity-Tutorials/tree/master/MultiTenancy
I can not find it

**Comment by volkanceylan** [comment]
OMG, you wrote this in 2 issues, plus mailed me. 

It's not available, follow the guide.

**Comment by FARIVER** [comment]
OK,Thanks
