### ISSUE TITLE
Multiple Saved Filters per user

### ISSUE THREAD

**Issue by jonathan82** [volkanceylan/Serenity#1688]
I'm wondering if there a clean way to implement the feature where a user can save multiple filters, and recall them later. For example, a user could save a filter called "Completed Orders" on the Orders table and later on load this filter instead of having to setup the filter again.  I know filters can be saved but it only remembers the last one. 

Basically wondering if there is a way to override how the filter gets loaded by the grid so I can implement a custom saved filters functionality.

**Comment by volkanceylan** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/grids/persisting_settings.html

**Comment by mhussein67** [comment]
Hi Volkan
After adding:

`Serenity.DataGrid.defaultPersistanceStorage = new Common.UserPreferenceStorage();`

I got the below errors:

```
ScriptInitialization.ts:5 Uncaught TypeError: PSUADPortal.Common.UserPreferenceStorage is not a constructor
    at PSUADPortal.ScriptInitialization.PSUADPortal.ScriptInitialization (ScriptInitialization.ts:5)
    at PSUADPortal (ScriptInitialization.ts:6)
    at ScriptInitialization.ts:6
PSUADPortal.ScriptInitialization.PSUADPortal.ScriptInitialization @ ScriptInitialization.ts:5
PSUADPortal @ ScriptInitialization.ts:6
(anonymous) @ ScriptInitialization.ts:6
jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3846 jQuery.Deferred exception: PSUADPortal.Membership.LoginPanel is not a constructor TypeError: PSUADPortal.Membership.LoginPanel is not a constructor
    at HTMLDocument.<anonymous> (http://localhost/PSUADPortal/Account/Login?ReturnUrl=%2fPSUADPortal%2f:144:5)
    at mightThrow (http://localhost/PSUADPortal/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3570:29)
    at process (http://localhost/PSUADPortal/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3638:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3846
process @ jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3642
jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3855 Uncaught TypeError: PSUADPortal.Membership.LoginPanel is not a constructor
    at HTMLDocument.<anonymous> (Login?ReturnUrl=%2fPSUADPortal%2f:144)
    at mightThrow (jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3570)
    at process (jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3638)
```
below is the structure of the USERPREFERENCES in the Oracle databse:

CREATE TABLE USERPREFERENCES
(
  USERPREFERENCEID  NUMBER(10)                  NOT NULL,
  USERID            NUMBER(10)                  NOT NULL,
  PREFERENCETYPE    NVARCHAR2(100)              NOT NULL,
  NAME              NVARCHAR2(200)              NOT NULL,
  VALUE             NCLOB
)

Any idea?

**Comment by volkanceylan** [comment]
Check your sources, it's typescript error

**Comment by mhussein67** [comment]
Ok, I have fixed that by using 
```
protected getPersistanceStorage(): Serenity.SettingStorage {
            return new Common.UserPreferenceStorage();
        }
```
I found the below glitch in : Modules\Common\Migrations\DefaultDB\DefaultDB_20160515_072600_UserPreferences.cs

line 26: 
`Utils.AddOracleIdentity(this, "UserPreferences", "UserId");`

it should be:
`Utils.AddOracleIdentity(this, "UserPreferences", "UserPreferenceId");`

Thanks

**Comment by volkanceylan** [comment]
Hmm, it must be an error in older versions. I'm now using another helper in migrations, e.g:

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Migrations/DefaultDB/DefaultDB_20160515_072600_UserPreferences.cs

**Comment by dfaruque** [comment]
@jonathan82 Sorry for this. I have checked your profile and you might be forgotten to Star this repository. :) 
If you use it then why not to give a Star?

**Comment by jonathan82** [comment]
@dfaruque Sure, is starring it sort of like giving it a good rating? I am a happy to show my support for this project as it has been very useful for us. 

@volkanceylan thanks for the response. I'll be sure to look at the docs first next time!

**Comment by dfaruque** [comment]
github sort the project by their stars and forks count
