### ISSUE TITLE
Using SQLite database.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1689]
I have added the following Nuget package
`<package id="System.Data.SQLite.Core" version="1.0.104.0" targetFramework="net45" />`

Then changed my connection string as 
`<add name="Default" connectionString="Data Source=Default_v1.db;" providerName="System.Data.SQLite" />`
also tried,
`<add name="Default" connectionString="Data Source=e:\Default_v1.db;Version=3;" providerName="System.Data.SQLite" />`

But when run my solution it says : Unable to find the requested .Net Framework Data Provider.  It may not be installed.

SQLite users please point to the right direction. 

Thanks.

**Comment by dfaruque** [comment]
Within my solution the following code is working fine

                ```
SQLiteConnection.CreateFile(@"e:\MyDatabase.sqlite");

                SQLiteConnection m_dbConnection = new SQLiteConnection(@"Data Source=e:\MyDatabase.sqlite;Version=3;");
                m_dbConnection.Open();

                string sql = "create table highscores (name varchar(20), score int)";

                SQLiteCommand command = new SQLiteCommand(sql, m_dbConnection);
                command.ExecuteNonQuery();

                sql = "insert into highscores (name, score) values ('Me', 9001)";

                command = new SQLiteCommand(sql, m_dbConnection);
                command.ExecuteNonQuery();

                m_dbConnection.Close();
```

**Comment by williamhodges** [comment]
Sorry for the comment, but I had to laugh at your last post. `sql = "insert into highscores (name, score) values ('Me', 9001)";` 

First thought in my mind was '*It's over 9000!*'

**Comment by stixoffire** [comment]
@dfaruque You might also want to change the Dialect of your provider in site initialization - I use  a switch statement there so if my connection string has MySQL it uses that dialect, if it has SQL server it uses that one..

**Comment by dfaruque** [comment]
```
  <connectionStrings>
    <add name="Default" connectionString="data source=|DataDirectory|Default.db" providerName="System.Data.SQLite" />
  </connectionStrings>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite" />
      <add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
    </DbProviderFactories>
  </system.data>

```

in web.config 
And

```

            else if (String.Equals(cs.ProviderName, "System.Data.SQLite", StringComparison.OrdinalIgnoreCase))
                databaseType = "SQLite";

```

in SiteInitialization.Migration.cs

is resolved my issue

**Comment by stixoffire** [comment]
@dfaruque I have the following in one of my projects  siteInitialization file you can use a switch case statement as well but this is the jist. I added it because with mysql things some things would work and some things would not work until I set the dialect.


```
    public static partial class SiteInitialization
    {
        public static void ApplicationStart()
        {
            try
            {

                if(SqlConnections.GetConnectionString("Default").ProviderName.Contains("MySqlClient"))
                { 
                    SqlConnections.GetConnectionString("Default").Dialect = MySqlDialect.Instance;

                }

                if (SqlConnections.GetConnectionString("Northwind").ProviderName.Contains("MySqlClient"))
                {                
                    SqlConnections.GetConnectionString("Northwind").Dialect = MySqlDialect.Instance;
                }
```

**Comment by dfaruque** [comment]
@stixoffire  Thanks for the info.
