### ISSUE TITLE
How to Add 'With(Nolock)' To Query

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1690]
Hi , Merry Christmas in advance !
As the title said , The auto-generate queryString without 'With(Nolock)' , What should I do to solve this problem?
Can I override something?

**Comment by volkanceylan** [comment]
This is not supported, maybe in a later version sorry

**Comment by weiguanhai** [comment]
No problem , It is already really powerful !   Thank you !

**Comment by brunobola** [comment]
No need to use this it you are using row versioning, see http://dba.stackexchange.com/questions/29289/options-for-setting-nolock-hint-in-dataset-queries
