### ISSUE TITLE
SiteInitalization crashes in sergen app made with no modification

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#1691]
Hi,
Update : I solved this issue adding LooupScript and LookupEditor.
I made a simple app with sergen. It is very simple table regions joined to countries and countries are  joined to languajes and currency. After executing base(Fields) un territoriesRow.cs the application crashes.
The error i get is Target invocation exception.
I did not make any change from code generated by sergen. I run the latest version 2.6.10
I send you row.cs file. Sorry I'm from Spain and the name is comunidadesautonomasrow.cs equivalent to region.
Thanks in advance & wish you Merry Christmas
Javier
[ComunidadesAutonomasRow.txt](https://github.com/volkanceylan/Serenity/files/670731/ComunidadesAutonomasRow.txt)

**Comment by stixoffire** [comment]
@pesnunj0 If you solved it close the issue.
