### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1692]
Hi @volkanceylan 

After updating to 2.7 all are working fine except the user permission form, when trying to give the user  a permission to a specific permission key I got:
Value does not fall within the expected range.

Any Idea?

**Comment by stixoffire** [comment]
@mhussein67 have you tried deleting your typscripts and recreating them by running the T4 templates - I had to do this after manually editing some files - for some reason it refused to rebuild those type scripts 
look in the IMPORTS folder. This is probably where the issue is , some naming convention may have changed and the script did not get rebuilt by the T4 template build ..

**Comment by mhussein67** [comment]
I've done that many times, I also check if any changes on USERPERMISSIONS table but no different BTW 2.7 and older version, even all the ts files are the same. 
One more thing I should mention that I'm using Oracle, do you think it make since?

**Comment by volkanceylan** [comment]
There is no problem in serenity.is/demo which also uses 2.7. So it should be about Oracle. I don't have it and can't test. So you should try and come some stack trace etc.

**Comment by mhussein67** [comment]
ok, this what I found: In UserPermissionRepository.cs the value Granted is sent as bool 

```
uow.Connection.Insert(new MyRow
                    {
                        UserId = userID,
                        PermissionKey = k,
                        Granted = newList[k]
                    });


```
the Dialect  is converted it to something else which prevent the provider from insert/update the submitted bool value:
SqlConnections.GetConnectionString("Default").Dialect = new MyOracleDialect();

When I disable the Dialect it works fine., bit I need to keep the Dialect.

**Comment by stixoffire** [comment]
@mhussein67 the value Granted is bool ? is the newList[k] picking up a bool , or a short? and how does your Oracle table look like - is it a SMALLINT -
 I would venture your newList[k] has an Integer value [32 bit ] cast it to short and I think you will be fine.

**Comment by mhussein67** [comment]
Yes Granted value is true/false, the Oracle table created by the Serenity migration tools see the below script. in oracle the bool value is converted to number of 1 default is 1. when the insert statement executed in oracle the value true will be converted to 1 and false to 0, but I think the Dialect is converted this value to some thing else which prevent oracle provider from saving the value. As I said if I disable the Dialect it works fin.
```

this.CreateTableWithId64("UserPermissions", "UserPermissionId", s => s
                .WithColumn("UserId").AsInt32().NotNullable()
                    .ForeignKey("FK_UserPermissions_UserId", "Users", "UserId")
                .WithColumn("PermissionKey").AsString(100).NotNullable()
                .WithColumn("Granted").AsBoolean().NotNullable().WithDefaultValue(true));
```

**Comment by volkanceylan** [comment]
Oracle provider is stupid, unlike Sql one which converts true false to 1 0 automatically as it should, it gives error above.  I had to put a workaround in SqlHelper but it checks exact dialect type so your subclass doesnt work. Will fix next ver, for now remove dialect.

**Comment by mhussein67** [comment]
@volkanceylan Thank you
