### ISSUE TITLE
Error after install 2.7

### ISSUE THREAD

**Issue by MsDanglar** [volkanceylan/Serenity#1693]
Hi Voolkan,
After installed a version 2.7  I'm get a next error

**Could not load file or assembly 'MsieJavaScriptEngine' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.IO.FileLoadException: Could not load file or assembly 'MsieJavaScriptEngine' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Help please.
Thank you

**Comment by volkanceylan** [comment]
Try reinstalling it

**Comment by brunobola** [comment]
Maybe your AV with a false positive remove the .js file
