### ISSUE TITLE
Get textual field value from Foreign Key of Foreign Key

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1694]
I have three tables eg:

Table Patient:
Id ,Name

Table Appointment:
Id, PId(Foreign Key on Id of Patient), Time, Remarks 

Table Prescription:
Id, AId(Foreign Key on Id of Appointment), Other Columns

In above scenario I'm using sergen on Prescription table,
but i want Patient Name to be selected instead of PatientId on form, is there any way?

**Comment by dfaruque** [comment]
use lookup editor on PatientId filed in yourRow.cs

See guide to know more. https://www.gitbook.com/book/volkanceylan/serenity-guide/details

I suggest you to follow movie tutorial line by line and then you will be familiar on these basic things.

**Comment by dfaruque** [comment]
you could change NameField to PatientName instead of PatientId

**Comment by dfaruque** [comment]
find 
```
        StringField INameRow.NameField {
            get { return Fields.PId; }
        }
```
in AppointmentRow.cs
And replace PId with PatientName/PName or whatever it is.
Then user [LookupEdito(typeof(AppointmentRow))] on top of AId in PrescriptionRow.cs

hope this will help.

**Comment by vinaykulkarni89** [comment]
@dfaruque Thankyou for your time, it worked awesome, but i have lil bit issue in PrescriptionColumns.cs how can i show the PatientName in columns

**Comment by dfaruque** [comment]
replace patientId with patientName. [match this name with yourRow.cs]

**Comment by dfaruque** [comment]
and change Int32 => string in column.cs

**Comment by vinaykulkarni89** [comment]
As you can see that this PatientName is from Table Patient and Lookup is on Appointment Table to PatientName cannot be mapped in Prescription

**Comment by dfaruque** [comment]
```
        [DisplayName("AId"), Expression("jAppointment .[PId]")]
        [ForeignKey("Patient", "Id"), LeftJoin("jPatient")]
        public Int32? AppointmentPId{ get { return Fields.AppointmentPId[this]; } set { Fields.AppointmentPId[this] = value; } }

        [DisplayName("PName"), Expression("jPatient.[Name]"), MinSelectLevel(SelectLevel.List)]
        public String PName{ get { return Fields.PName[this]; } set { Fields.PName[this] = value; } }
        
```
put these lines in PrescriptionRow.cs and declare corresponding fields to RowFields class
then use the PName in PrescriptionColumn.cs
hope this will help.

**Comment by dfaruque** [comment]
As I said before these things are covered in guide. so please read that.

**Comment by vinaykulkarni89** [comment]
@dfaruque  thankyou i solved my issue, and i'm referring the guide
