### ISSUE TITLE
QuickFilterOption("cascadeFrom","colname") in IE

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1695]
HI,
I've noticed that the LookupEditor (in IE only) is showing "no matches found" in any LookupEditor with  QuickFilterOption("cascadeFrom","colm-name"), it works fine in Chrome and Firefox. but if I remove the  QuickFilterOption it works fine in all browsers included IE.  

Any ideas?

Thanks

**Comment by mhussein67** [comment]
Does anyone have the same problem on IE?

**Comment by volkanceylan** [comment]
Cascade from in http://serenity.is/demo/Northwind/Customer works properly in IE. I guess your property name is wrong.
