### ISSUE TITLE
Exception log crashes using mysql

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#1696]
Hi,
When I try to see exception log in Administration menu the system halts at getAllErrors.
I use Mysql as database
The error I get is
MySql.Data.MySqlClient.MySqlException was unhandled by user code
  ErrorCode=-2147467259
  HResult=-2147467259
  Message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '200 
* 
FROM `Exceptions` 
WHERE ((`ApplicationName` = 'Geshotel') AND `Deletion' at line 1
  Number=1064
  Source=MySql.Data
  StackTrace:
       en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
       en MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
       en MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
       en MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
       en MySql.Data.MySqlClient.MySqlDataReader.NextResult()
       en MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
       en MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
       en System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
       en Serenity.Data.SqlMapper.<QueryInternal>d__38`1.MoveNext() en P:\Sandbox\Serene\Serenity\Serenity.Data\SqlHelpers\Dapper.cs:línea 879
       en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       en Serenity.Data.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) en P:\Sandbox\Serene\Serenity\Serenity.Data\SqlHelpers\Dapper.cs:línea 819
       en Serenity.Data.SqlMapper.Query[T](IDbConnection cnn, ISqlQuery sql, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) en P:\Sandbox\Serene\Serenity\Serenity.Data\SqlHelpers\Dapper.cs:línea 800
       en Geshotel.SqlErrorStore.GetAllErrors(List`1 errors, String applicationName) en D:\Geshotel\Visual_studio 2015\Geshotel\Geshotel\Geshotel.Web\App_Start\SqlErrorStore.cs:línea 324
       en StackExchange.Exceptional.ErrorStore.GetAll(List`1 errors, String applicationName) en C:\BuildAgent\work\d20fce4a5bb47bd3\StackExchange.Exceptional\ErrorStore.cs:línea 370
  InnerException: 
Thanks in advance

**Comment by volkanceylan** [comment]
Set default dialect properly

**Comment by pesnunj0** [comment]
Excuse me I don´t know what you mean

**Comment by volkanceylan** [comment]
Try reading guide about dialects

**Comment by pesnunj0** [comment]
Thanks.
I added the following line at SiteInitialization.cs
 SqlConnections.GetConnectionString("Default").Dialect = MySqlDialect.Instance;
and got the same result.
Then I tried to add
 <add key="ConnectionSettings" value="{Default: {Dialect: 'Mysql'}}"/>
and got the same result

**Comment by volkanceylan** [comment]
Ok this should be fixed in next version.

**Comment by pesnunj0** [comment]
Thanks
