### ISSUE TITLE
Update row aftersave()

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1697]
protected override void AfterSave()
            {
                base.AfterSave();

                new SqlUpdate("Appointment")
                    .Set("Prescribed", true)
                    .Where("Id=="+Request.Entity.AppointmentId) ;
            }

i want to update after save, is above right way?, as its not working

**Comment by VictorTomaili** [comment]
```csharp
new SqlUpdate("Appointment") // prefer fld.TableName
   .Set("Prescribed", true) // prefer fld.Prescribed
   .Where(new Criteria("Id") == Request.Entity.AppointmentId) // prefer fld.Id == Request.Entity.AppointmentID
   .Execute(uow.Connection, ExpectedRows.ZeroOrOne);
```

**Comment by vinaykulkarni89** [comment]
here uow is not accessible 
![image](https://cloud.githubusercontent.com/assets/17939331/21499766/b37dcf14-cc5e-11e6-8c85-d7ba0137078d.png)

**Comment by vinaykulkarni89** [comment]
![image](https://cloud.githubusercontent.com/assets/17939331/21499797/f34aa162-cc5e-11e6-93f8-8b7d2baaeb36.png)

**Comment by VictorTomaili** [comment]
ohh find your connection or unit of work in current object. its already set and ready for use.

**Comment by vinaykulkarni89** [comment]
Yes seen its been there but how can i access it in aftersave()

**Comment by VictorTomaili** [comment]
use intellisense

**Comment by vinaykulkarni89** [comment]
Sorry but again i have error

![image](https://cloud.githubusercontent.com/assets/17939331/21500075/44ea1438-cc61-11e6-8775-8b8ea311bbd9.png)

**Comment by VictorTomaili** [comment]
Look at diff `.Where(new Criteria("Id") == Request.Entity.AppointmentId)`

**Comment by vinaykulkarni89** [comment]
![image](https://cloud.githubusercontent.com/assets/17939331/21500127/bb283fb2-cc61-11e6-9f90-2e74e527fa8c.png)

**Comment by VictorTomaili** [comment]
Ohh and use `Request.Entity.AppointmentId.Value`
criteria doesnt accept nullable values.

**Comment by vinaykulkarni89** [comment]
.Where(new Criteria("Id") == Request.Entity.AppointmentId.Value)

Yes this worked and also following works fine

.Where(new Criteria("Id") == new Criteria(Request.Entity.AppointmentId.ToString()))

@VictorTomaili thankyou for your precious time
