### ISSUE TITLE
Little Help with Cascade Combos

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1699]
The cascade combos works just fine in my project, but with this i can't make it work. This is my code

`

        [DisplayName("Marca"), NotNull, ForeignKey("[dbo].[Vehiculos_Marcas]", "IdMarca"), LeftJoin("jIdMarca"), TextualField("IdMarcaDescripcion")]
        [LookupEditor("Parametros.VehiculosMarcas")]
        public Int32? IdMarca
        {
            get { return Fields.IdMarca[this]; }
            set { Fields.IdMarca[this] = value; }
        }

        [DisplayName("Modelo"), NotNull, ForeignKey("[dbo].[Vehiculos_Modelos]", "IdModeloVehiculo"), LeftJoin("jIdModeloVehiculo"), TextualField("IdModeloVehiculoDescripcion"), LookupInclude]
        [LookupEditor("Parametros.VehiculosModelos", CascadeFrom = "IdMarca", CascadeField = "IdMarca")]
        public Int32? IdModeloVehiculo
        {
            get { return Fields.IdModeloVehiculo[this]; }
            set { Fields.IdModeloVehiculo[this] = value; }
        }

        [DisplayName("Año"), NotNull, ForeignKey("[dbo].[Vehiculos_Anio]", "IdVehiculosAnio"), LeftJoin("jIdVehiculosAnio"), TextualField("IdVehiculosAnioAnio"), LookupInclude]
        [LookupEditor("Parametros.VehiculosAnios", CascadeFrom = "IdModeloVehiculo", CascadeField = "IdModeloVehiculo")]
        public Int32? IdVehiculosAnio
        {
            get { return Fields.IdVehiculosAnio[this]; }
            set { Fields.IdVehiculosAnio[this] = value; }
        }

        [DisplayName("Versión"), NotNull, ForeignKey("[dbo].[Vehiculos_Version]", "IdVehiculosVersion"), LeftJoin("jIdVehiculosVersion"), TextualField("IdVehiculosVersionDescripcion"), LookupInclude]
        [LookupEditor("Parametros.VehiculosVersion", CascadeFrom = "IdVehiculosAnio", CascadeField = "IdVehiculosAnio")]
        public Int32? IdVehiculosVersion
        {
            get { return Fields.IdVehiculosVersion[this]; }
            set { Fields.IdVehiculosVersion[this] = value; }
        }

`

Can anyone help me to debug in the browser or point me in the right direction?

Thanx

**Comment by Estrusco** [comment]
What is the console error?

**Comment by javaman63** [comment]
That's my problem. I have no error in the console. it's making me crazy

**Comment by volkanceylan** [comment]
Add LookupInclude to your lookup row, not this one.

**Comment by javaman63** [comment]
@volkanceylan Thank youuuu! It worked!
