### ISSUE TITLE
Module wise different project.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#170]
In serenity, Is it possible to have Module wise different project.

**Comment by volkanceylan** [comment]
What does this mean?

**Comment by dfaruque** [comment]
Suppose I Have Purchase, Inventory, Sales, HR, Accounting etc module in my Applicalion. I want to organize them in different script, repository etc project.

**Comment by volkanceylan** [comment]
You could. Only problem is T4 files. You need to find a way to split them.

**Comment by dfaruque** [comment]
I have generated 1000+ tables in my project. Now it takes about 10 minutes to build. Any suggestion?

**Comment by volkanceylan** [comment]
Omg, what kind of project you are doing

**Comment by volkanceylan** [comment]
Splitting wont help much, remove repository, endpoint, page cshtml etc that you wont use. Get a faster SSD get a faster CPU :)

**Comment by VictorTomaili** [comment]
Maybe incredibuild increase your build performance

**Comment by stixoffire** [comment]
I know your post is old .. 
> Suppose I Have Purchase, Inventory, Sales, HR, Accounting etc module in my Applicalion. I want to organize them in different script, repository etc project.

I am wondering if you would be able to build them as separate projects .. and then simply take the modules and add them in to the application - much like Northwind is existing ? Just food for thought..
