### ISSUE TITLE
LookupScript in LanguageRow.cs

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#1700]
Hi,
I'm a starter with serenity and MVC so I'm a little lost
I try to reuse Language data table in order to know customers speaking language.
If I add [LookupScript("Administration.Language")] to LanguageRow.cs then LanguageSelection in Main Page does not work.
I would appreciate so much any help
Thanks
Javier

**Comment by dfaruque** [comment]
try adding another class for lookup like this

```
    [LookupScript("Administration.Language", Permission = "?")]
    public class LanguageLookup : RowLookupScript<LanguageRow>
    {
        public LanguageLookup()
        {
        }
}
```

**Comment by pesnunj0** [comment]
Thank you so much,
There is a class called LanguageLookup with that LookupScript, so if I add that to LanguageRow the first one fails.
What I did is add another LookupScript to LanguageRow.
I close the issue 
Thanks so much
