### ISSUE TITLE
ClientTypes.tt üzerinde "Run Custom Tool" u çalıştırdıktan sonra giriş web hata veriyor

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1705]
Merhaba,

ClientTypes.tt üzerinde "Run Custom Tool" u çalıştırdıktan sonra yeni eklediğim formların Attribute'ları oluşuyor fakat siteye girişte aşağıdaki hata veriyor

Sorunu nasıl çözebilirim ? 

Server Error in '/' Application.

Multiple custom attributes of the same type found.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.

Source Error: 

Line 38: @Html.Script("~/Scripts/fastclick/fastclick.js")
Line 39: @Html.Script("~/Scripts/adminlte/app.js")
Line 40: @Html.Script("~/Scripts/Site/Serene_Brkt.Web.js")
Line 41: 
Line 42: <script src="~/DynJS.axd/@HtmlScriptExtensions.GetLocalTextInclude(this.Html, "Site")"></script>

Source File: c:\Users\mim5\Documents\Visual Studio 2015\Projects\Serene_Brkt\Serene_Brkt\Serene_Brkt.Web\Views\Shared\_LayoutHead.cshtml    Line: 40

**Comment by volkanceylan** [comment]
Aynı class tan 2 tane olmadığından emin ol, .NET 4.5.2
