### ISSUE TITLE
Question: How to Insert Custom HTML between Search Panel and Grid

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#1709]
I would like to add custom html in my Grid <div id=gridDiv> after the status and before the entities rows.

[http://imgur.com/a/BonTa](See this picture for an example: http://imgur.com/a/BonTa)

I see in my Grid.ts I have a constructor and this is where I think I need to add it. 
Basically I want to add simple table is there an example , somewhere ?

**Comment by volkanceylan** [comment]
This is basic jQuery, i don't think an example is needed.

**Comment by stixoffire** [comment]
@volkanceylan - that is good enough direction for me. I am new to jQuery , years (eons) ago I learned java, but have been away from coding for a long time .. so thank you very much for pointing me to the right direction.

**Comment by Estrusco** [comment]
In your typescript XYZGrid.ts file get the element grid by jQuery and prepend your HTML code

```ts
     constructor(container: JQuery) {
            super(container);

            this.element.find('.grid-container').prepend("<p>your code</p>");
        }
```

**Comment by stixoffire** [comment]
@Estrusco thank you - this lets me know I put java code there.
