### ISSUE TITLE
Paging in grid.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#171]
When I go to next page in main grid it says 

An exception of type 'System.Data.SqlClient.SqlException' occurred in Serenity.Data.dll but was not handled in user code

Additional information: Incorrect syntax near 'OFFSET'.

Invalid usage of the option NEXT in the FETCH statement.

**Comment by volkanceylan** [comment]
Read guide to set your dialect to Sql 2005

**Comment by dfaruque** [comment]
Wow. :+1:
