### ISSUE TITLE
TypeScript Slick Formatter with Options

### ISSUE THREAD

**Issue by florin-nitulescu** [volkanceylan/Serenity#1711]
Hi,

I've tried making a slick formatter with parameters set via the autogenerated C# attribute class. The parameters are there, but under the hood, the `ReflectionOptionsSetter` can't set the decorated option field on the formatter. I've managed to find something to work, but I'm curious if there's a better approach to this.

```typescript
@Serenity.Decorators.registerFormatter()
export class DetailListFormatter implements Serenity.ISlickFormatter {
        
    @Serenity.Decorators.option()
    DetailField: string;

    format(ctx: Slick.FormatterContext): string {
        let list = ctx.value as Array<{ [key: string]: any }>;

        if (!this.DetailField) {
            this.DetailField = this.getOption(ctx, 'DetailField');
        }   

        return list.map(elem => elem[this.DetailField]).join(", ");
    }        
        
    protected getOption(ctx: Slick.FormatterContext, name: string): any {
        let slickColumn = (ctx.column as Slick.Column);
        if (slickColumn && slickColumn.sourceItem) {
            let params = slickColumn.sourceItem.formatterParams;
            if (params) {
                return params[name] || null;
            }
        }
        return null;
    }
}
```

**Comment by volkanceylan** [comment]
First of all use lowerCase property names

**Comment by florin-nitulescu** [comment]
Ok. I've changed to lowerCase property names, but the values are still `undefined`.

**Comment by volkanceylan** [comment]
You don't need to get option from source column, you just add a option() then it gets populated.

**Comment by florin-nitulescu** [comment]
Sure, but it gets populated only if I create the formatter with C# (Saltarelle). With TypeScript, using the option decorator has an effect only on the corresponding attribute.

**Comment by wirble** [comment]
@florin-nitulescu were you able to figure this out, I am having the same issue?

**Comment by florin-nitulescu** [comment]
@wirble, No. As a compromise I've made a 'getOption()' method like in the above example to read the options passed via c# attribute and it works.
