### ISSUE TITLE
Transform All T4 Templates

### ISSUE THREAD

**Issue by MaximilianoSoftur** [volkanceylan/Serenity#1713]
Hello when running transform All T4 Template. It locks or restarts Visual Studio. On two desktop with windows 10 and visual studio 2015. While on a desktop with windows 7 and visual studio 2015 works well. What could it be. Thank you so much

**Comment by stixoffire** [comment]
@MaximilianoSoftur I have both Windows 10 and also a setup on Windows 7, neither have issues on T4 build. Check your event viewer in Windows 10. Also make sure you have typeScript 2.1 Installed on Windows 10 box.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/1179

**Comment by MaximilianoSoftur** [comment]
thank you very much for your help. I worked well
