### ISSUE TITLE
Nominate Volkan Ceylan as MVP

### ISSUE THREAD

**Issue by mahmuthaktan** [volkanceylan/Serenity#1714]
I wantto thank Volkan for this platform. I nominate Volkan for adding his name to MVP list. 
With this action serenity may became known to more people.
Everyone can advise with this link:
https://mvp.microsoft.com/en-us/Nomination/nominate-an-mvp

**Comment by vinaykulkarni89** [comment]
I'm eager to vote for Volkan Ceylan but link is down

**Comment by vinaykulkarni89** [comment]
Ok link is up but its asking for confirmation as,

I affirm I have 's explicit permission to submit this personal information to Microsoft and I understand an email will be send to me and on my behalf when I click submit. 

so i request @volkanceylan is it ok if i submit you name and mail id to microsoft?

**Comment by john20xdoe** [comment]
We should as @volkanceylan if it's ok with him. being an MVP is not only a title; it has responsibilities that need to be maintained (something like yearly?) that Volkan may not have the time to do.

**Comment by samdubey** [comment]
Done

**Comment by volkanceylan** [comment]
Thanks to all nominators. I've received one e-mail per nomination. Applied one of them, waiting for results.
