### ISSUE TITLE
Display class value in grid

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1715]
Hello All

I have a class I encrypts and decryption values.  That being said how do display a calculated value on a grid.  I know how to do this many different ways but I would like input on how to do this the Serenity way.

I basically want my grid to look like this

ColumnA  ColumnB = Encrypted(ColumnB value)

I want  the column B value to be available to my form and grid pages so I need to do this on the entity if possible

**Comment by volkanceylan** [comment]
Do it overriding OnReturn of your repository, or use a formatter

**Comment by mcb2323** [comment]
Didnt even think to use a formatter.  Thanks and you the man!!!!


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Volkan Ceylan <notifications@github.com> Date: 12/31/16  9:35 AM  (GMT-05:00) To: volkanceylan/Serenity <Serenity@noreply.github.com> Cc: mcb2323 <mbrown@blackwolftech.com>, Author <author@noreply.github.com> Subject: Re: [volkanceylan/Serenity] Display class value in grid (#1715) 
Do it overriding OnReturn of your repository, or use a formatter

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/volkanceylan/Serenity","title":"volkanceylan/Serenity","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/volkanceylan/Serenity"}},"updates":{"snippets":[{"icon":"PERSON","message":"@volkanceylan in #1715: Do it overriding OnReturn of your repository, or use a formatter"}],"action":{"name":"View Issue","url":"https://github.com/volkanceylan/Serenity/issues/1715#issuecomment-269867574"}}}

**Comment by mcb2323** [comment]
Can you tell me what Im missing

repository:

 private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void OnReturn()
            {
                base.OnReturn();
                Row.EId = "Some String";
            }
        }

Entity

 [DisplayName("EId"), NotMapped]
        public String EId
        {
            get { return Fields.EId[this]; }
            set { Fields.EId[this] = value; }
        }

**Comment by volkanceylan** [comment]
Row in list request handler is one entity used to load, your list handler can return multiple entities right?

Do it like

```
foreach (var e in Response.Entities)
    e.Eld = "Some String";
```
