### ISSUE TITLE
Opening a new dialog from navigation

### ISSUE THREAD

**Issue by shaunbsoft** [volkanceylan/Serenity#1716]
Hi,

Just wondering if anyone can offer advice on opening a new dialog from the nav menu.

For example, we have a quotes module, and currently, to add a new quote, you have to click on Quote->Quotes then the new quote button above the grid. I have added a nav item that says 'New Quote' however, I am stuck as to how to bring up the quote dialog for a user to create a new quote when they click this nav item.

I know they are opened via javascript, but don't know how to add an onclick event or something to a nav item.

Many Thanks,

**Comment by volkanceylan** [comment]
use "javascript:new MyApp.MyModule.MyDialog().loadNewAndOpenDialog()" as url parameter
