### ISSUE TITLE
Slick options row height effect all grids 

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#1719]
Hi!

I used example to change the height of the grid:

```
        protected getSlickOptions(): Slick.GridOptions {
            var opt = super.getSlickOptions();
            opt.rowHeight = 90;
            return opt;
        }
```

And i found-out that this effect also on other grids in dialog:
![capture](https://cloud.githubusercontent.com/assets/22570602/21581485/2d5ea084-d03c-11e6-9000-554e5e20a421.PNG)

thanks!

**Comment by MsDanglar** [comment]
Hi Volkan
Im also came across this issue.
Thank you

**Comment by in32bit** [comment]
I'm sorry. You are right, it was a version margin issue.
Thank you.
