### ISSUE TITLE
Query multiple tables and filtering based on date range

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#172]
I am wondering how to go about generating a page where multiple tables are queried and filtered based on a given date range from user. Should this be in its own model class kind of like DashboardPageModel.cs and DashboardPage.cs?

**Comment by volkanceylan** [comment]
So you'll show multiple grids in multiple tabs? I didn't understand your aim.

**Comment by VictorTomaili** [comment]
Serenity doesnt use directly view models. Serenity use rows over api. If you want to edit Dashboarad view with razor you need handle it yourself. 
Otherwise read the [documentation](https://volkanceylan.gitbooks.io/serenity-guide/content/entities/entities_row.html) for relation multiple tables and show&filter they in grid.

**Comment by jsbUSMC** [comment]
Sorry, I mean to use not the dashboard page, but to use a similar style page using elements from AdminLTE, but I want to basically return rows from multiple entities, and use that data to populate the page using Razor. I would also like to use some of the widgets that come with AdminLTE to interact with Serenity.

**Comment by VictorTomaili** [comment]
On page.cs and cshtml you can use razor  and repositories for CRUD. Its mvc style not handled from serenity. Send model and use razor basically.

**Comment by jsbUSMC** [comment]
Thank you for your feedback, Victor. If I may reiterate what you're saying to be sure I understand...I can use the repositories created by Serenity for my tables to perform the CRUD operations I need in my Page classes and Razor to format and display the data in the cshmtl?

**Comment by VictorTomaili** [comment]
if you want to custom views like dashboard, yes.

**Comment by jsbUSMC** [comment]
Thank you very much for your help Victor, I appreciate it.
