### ISSUE TITLE
Question: Only allow users to see their entries

### ISSUE THREAD

**Issue by Satal** [volkanceylan/Serenity#1720]
Is there built in functionality in Serenity to allow for users to be restricted to only viewing their own entries? I've found your blog post [Don't Repeat Your Permissions](http://serenity.is/blog/2016/12/17/dont-repeat-your-permissions), which talks about restricting access by groups.

The example I would give is an application like your Movie sample but instead of being one collection, each user having their own, though without going to the extent of doing multi-tenancy.

**Comment by volkanceylan** [comment]
You can do this with a simple behavior, e.g. add a IOwnedBy interface to rows, handle ApplyFilters in behavior, and add a Where to handler.Query

**Comment by Satal** [comment]
Thanks for the response, I am admittedly unsure about what you meant by "handle ApplyFilters in behaviour, and add a Where to handler.Query". I ended up taking the following approach:

In Endpoint.cs I replaced the Create method with:

```
        [HttpPost, AuthorizeCreate(typeof(MyRow))]
        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            int userId;

            if (Int32.TryParse(Authorization.UserId, out userId))
            {
                request.Entity.UserId = userId;
                return new MyRepository().Create(uow, request);
            }
            else
            {
                return new SaveResponse()
                {
                    Error = new ServiceError() { Message = "You do not appear to be logged in" }
                };
            }
        }
```
and List method with:
```

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            int userId;

            if (Int32.TryParse(Authorization.UserId, out userId))
            {
                request.EqualityFilter.Add("UserId", userId);
                return new MyRepository().List(connection, request);
            }
            else
            {
                return new ListResponse<Entities.UserBookiesRow>();
            }
        }
```

If your method is preferable to my approach then I would be grateful if you could provide a little more detail.

**Comment by volkanceylan** [comment]
Where you should set these are inside MyListHandler, overriding ApplyFilters.

See tutorials for some info on behaviors.
