### ISSUE TITLE
Uncaught Error: Cannot find stylesheet.   jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3855 

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#1721]
Hi,
In Chrome I got this error in slick.grid.js so grid is not displayed well
In Firefox it works fine
Thanks in advance
![image](https://cloud.githubusercontent.com/assets/24249067/21582642/c8dd3248-d058-11e6-8534-cf9add8c2bf9.png)

**Comment by stixoffire** [comment]
@pesnunj0 , the error is telling you that it can't find the style sheet, Firefox is probably bypassing the error, because if it can't find the style sheet , Firefox, IE, chrome are not the storer's of your style sheet . I would venture your folder with style sheets doe snot have proper permissions . Check your sites permissions on the style sheet folder.

**Comment by pesnunj0** [comment]
Hi,
It is a random issue. I noticed that if I reload page with ctrl pushed it works, so it is not a permission problem. Looking for this issue in the internet I've seen I was not the first one.

Reading about it I've found one trick that worked for me.
I write it, maybe another one has the same.
 
To fix this I have added css rule vai JS. This
works on (chrome,firefox and IE)

In file slickgrid.js Replace createCssRules() and add new function addCSSRule. addCSSRule force
browser to create stylesheet under document.styleSheets.

function createCssRules() {
  $style = $("<style type='text/css' rel='stylesheet' />").appendTo($("head"));
  var rowHeight = (options.rowHeight - cellHeightDiff);
  if ($style[0].styleSheet) { // IE
    $style[0].styleSheet.cssText = "";
  } else {
    $style[0].appendChild(document.createTextNode(""));
  }
    var sheet =  $style[0].sheet;
    var index = 0;
    addCSSRule(sheet,"." + uid + " .slick-header-column", "left: 1000px;",index++);
    addCSSRule(sheet,"." + uid + " .slick-top-panel", "height:" + options.topPanelHeight + "px;",index++);
    addCSSRule(sheet,"." + uid + " .slick-headerrow-columns", "height:" + options.headerRowHeight + "px;",index++);
    addCSSRule(sheet,"." + uid + " .slick-cell", "height:" + rowHeight + "px;",index++);
    addCSSRule(sheet,"." + uid + " .slick-row", "height:" + options.rowHeight + "px;",index++);


    for (var i = 0; i < columns.length; i++) {

        addCSSRule(sheet,"." + uid + " .l" + i , "",index++);
        addCSSRule(sheet,"." + uid + " .r" + i, "",index++);
      }
}

function addCSSRule(sheet, selector, rules, index) {
    if(sheet.insertRule) {
        sheet.insertRule(selector + "{" + rules + "}", index);
    }
    else {
        sheet.addRule(selector, rules, index);
    }
}
Thanks
Javier

**Comment by stixoffire** [comment]
@pesnunj0 this link will be useful to you:
http://stackoverflow.com/questions/385367/what-requests-do-browsers-f5-and-ctrl-f5-refreshes-generate
 
I am glad your work around is working for you - but I think it has to do with browser caching and not cacheing - Chrome uses Is Modified since so there is probably some bad behavior going on tricking it not to request properly. 
Clear your browser cache and see if it works the first time, then if it does not work again - you can no this is where the real crux lies.

**Comment by pesnunj0** [comment]
If I clear cache it works for first time only.
Really it is very strange unless I am not the only one afortunately. A few weeks weeks ago when I started testing serenity it worked well. I don´t know if updating typescript or something could affect this.
What I can say is with this patch, the project works fine
I will continue testing with another project.
Thanks for your comments, they have been very usefull

**Comment by stixoffire** [comment]
@pesnunj0 
From Google: Query: Force Chrome to reload css every time

Force only while debugging:
http://stackoverflow.com/questions/15562384/how-to-force-chrome-browser-to-reload-css-file-while-debugging-in-visual-studio

Force it in the browser.
Google chrome css doesn't update unless clear cache
http://stackoverflow.com/questions/20300400/google-chrome-css-doesnt-update-unless-clear-cache

1.Open DevTools
2.Open Settings (bottom right or use F1 shortcut)
3.Check Disable cache (while DevTools is open)

**Comment by volkanceylan** [comment]
https://github.com/mleibman/SlickGrid/issues/223

**Comment by pesnunj0** [comment]
I found the patch where Volkan points.
Thank you so much guys.
