### ISSUE TITLE
enum column in in-memory Grid showing value instead of text/description at first time add.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1722]
tried to write something in

```
validateEntity(row, id) {
...
}
```

but don't find a way.
would you please give a quick hint on this?

**Comment by volkanceylan** [comment]
Use Q.toId to convert it no number there

**Comment by dfaruque** [comment]
awesome. it works. Thank you very much.

**Comment by imkheong** [comment]
Hey sorry guys, I might have a similar problem with an enum showing as number instead of text after added on client side / browser.

Can you provide a little more info / code as to how I can show the text after it's been added?

Thanks!

**Comment by volkanceylan** [comment]
In validateEntity method of your grid editor

Write

row.SomeEnum = Q.toId(row.SomeEnum)
