### ISSUE TITLE
Filter Grid

### ISSUE THREAD

**Issue by helpj** [volkanceylan/Serenity#1723]
I've got a grid that repeats the results:
![imagem](https://cloud.githubusercontent.com/assets/24883874/21598106/2a224dae-d14e-11e6-931e-f40c44b2dd65.png)

I'm using the approach described by the tutorials and have this:
...
set areaInvestigacaoID(value: number)
        {
            if (this._areaInvestigacaoID != value)
            {
                this._areaInvestigacaoID = value;
                this.setEquality(InvestigadorEstudoRow.Fields.EstudoAreaInvestigacaoId, value);
                this.refresh();
            }
        }
...

But as my entity InvestigadorEstudoRow as tha same investigator several times, how to filter the results to make it distinct like...

**Comment by stixoffire** [comment]
@helpj use a SQLQuery in your repository to select distinct records - there is an example  in BasicSamples  and Northwind CustomerCity ..

**Comment by ali-h2010** [comment]
@helpj , were you able to achieve this? can we override the sql query that list the grid columns?

**Comment by teafmartins** [comment]
Yes, you can override in MyListHandler  in repositor.cs change the InvestigatorStudyRow against a database view.

Boa Sorte! :)
