### ISSUE TITLE
Help debugging an issue

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1726]
I know, this is only for issues in regards to the Serenity platform however I have been trying to figure something out for the last 4 hours and can't figure it out. I had no one else to ask, so I'm asking you guys.

I have my site on a test server connected to a test database. I then copy the entire contents of that folder to my production server. I verify that it's still working on the production server with the test server connection. I go to Administration/Role and attempt to edit permissions and I get the following error. I do not get this on the test server. 

Does anyone have _any_ idea at all what it could be?

![image](https://cloud.githubusercontent.com/assets/11448029/21601929/6253359e-d15d-11e6-8d2d-b4fccc3d407c.png)

EDIT: I can edit roles when I select a user. However, if I go to edit permissions for that user or role, I get the above error message.

EDIT 2: I have completely removed the Northwind database from everything and it works fine on the test server. It's just the move over to production on that production box where it finds the issue.

**Comment by williamhodges** [comment]
I have a feeling that it's something on the server side but just have no idea where it could be.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/1599

**Comment by williamhodges** [comment]
@volkanceylan ... my friend. Thank you. Just..thank you.
