### ISSUE TITLE
Problem with cascading when using the same form in different dialogs 

### ISSUE THREAD

**Issue by jfdomitor** [volkanceylan/Serenity#1727]
I have dialog with a form (A) that includes two lookup editors where the second editor cascades from the first. The dialog and casading is working perfectly fine. My problem occurs when I load form (A) into a tab in a different dialog like below: (I'm reusing the same form as a view in another dialog)

```
 constructor() {
            super();
          this.secondPropertyGrid_in_other_dialog = new Serenity.PropertyGrid(this.byId("secondPropertyGrid_in_other_dialog "), { items:   Q.getForm(MyForm.formKey), 
useCategories: true });
        }

         protected afterLoadEntity() {
            super.afterLoadEntity();

           Service.Retrieve({
                EntityId: this.entity.SomeId
            }, response => {
                this.secondPropertyGrid_in_other_dialog .load(response.Entity);
              });
        }
```
What happens is that the form loads fine except the cascaded field. I get an error: **Can't find cascaded parent element with ID: "MyCascadeField**". The error comes from Serenity.Script.UI.js

```
var parent = Q.findElementWithRelativeId(this.$widget.element, this.$parentID).tryGetWidget(TParent);
				if (ss.isValue(parent)) 
{
					parent.element.bind('change.' + this.$widget.uniqueName, ss.mkdel(this, function() {
						this.$parentChange(parent);
					}));
					return parent;
				}
				else {
					Q.notifyError("Can't find cascaded parent element with ID: " + this.$parentID + '!', '', null);
					return null;
				}
`

```
        Driving me nuts..any help apreciated...

I believe it has something to do with the generated html id:s that look diferent when I use the form with another propertygrid. All Id:s begins with "undefined....."

**Comment by dfaruque** [comment]
did you use a template for that dialog?

**Comment by jfdomitor** [comment]
Yes I do. Another template with tabs and a form with a property grid on the
first tab.
Den 4 jan 2017 05:31 skrev "dfaruque" <notifications@github.com>:

**Comment by volkanceylan** [comment]
This wont work. Find full ID somehow

**Comment by volkanceylan** [comment]
Even if you succeed this is a bad design

**Comment by jfdomitor** [comment]
Thanks, but I don't understand what you mean with full ID.

**Comment by jfdomitor** [comment]
Ok I understand now what you mean by full ID, but I don't understand why it's not generated in my example.

**Comment by volkanceylan** [comment]
Dialogs has unique ID, generated every time, an editor can only find elements in its own container, e.g. dialog with relative ID.

**Comment by jfdomitor** [comment]
What I am doing is exactly what you show in your example BasicSample/Dialogs/another from in tab. I have discovered that your example behaves the same way like my code, and I bet casacding wouldn't work in your example either.

![image](https://cloud.githubusercontent.com/assets/16256718/21650723/352f6340-d2a6-11e6-92bf-5e5c24e82db1.png)

**Comment by jfdomitor** [comment]
Sorry for the big image, but as you see the id's in the cutomer tab is being prefixed with undefined, and i belive that this is the problem. Now I wonder how to workaround this.

**Comment by volkanceylan** [comment]
Hmm pass idPrefix option as this.idPrefix while creating second property grid

**Comment by jfdomitor** [comment]
Thanx alot... IT WORKS....... I understand you have much to do. But if you have a minute over please explain why it works.

**Comment by volkanceylan** [comment]
If you pass idPrefix (which you should always pass, i forgot that in sample), property grid creates elements with IDs that are prefixed with that idPrefix, which is the same for main property grid in dialog, thus they all have ID's that start with SomeDialog1357_ etc.

This also means your if you have two properties with same name in those grids, they will clash. So if thats the case, use idPrefix: this.idPrefix + "Secondary_" etc. So items in first property grid will have SomeDialog1357_Field1 while second one, SomeDialog1357_Secondary_Field2. This should still let you use CascadeFrom("Field1") on Field2, as it can split on "_" and find a parent element.

**Comment by jfdomitor** [comment]
Thanks for helping me out with this.
