### ISSUE TITLE
Code Generator SQLite

### ISSUE THREAD

**Issue by stefano5885** [volkanceylan/Serenity#1728]
Hello,
when i try connect to connect to SQLite DB
I get this error:
![cattura](https://cloud.githubusercontent.com/assets/7619692/21625583/97d8d110-d20c-11e6-9c09-4b180d439ea1.PNG)

in sergen.exe directory doesn't exist any .config files and my solution work with SQLite DB.

Regards 
Stefano

**Comment by stefano5885** [comment]
This topic didn't help me. [https://github.com/volkanceylan/Serenity/issues/1689](url)

**Comment by stixoffire** [comment]
@stefano5885  have a look here https://github.com/volkanceylan/Serenity/issues/337

**Comment by stefano5885** [comment]
I had read that issue unsucessully. 
I had comment, uncomment, delete, create the configuration file (machine.conf) and orher .conf file.
It's possible to register the sqlite dll in sergen?

**Comment by volkanceylan** [comment]
Read the guide. If it doesnt help search net on how to install a provider.
