### ISSUE TITLE
fastreport'da ImageLocation  için Url

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#173]
s.a.
url = Detail/00001/00001168_tyrqbdcpnw2su.png
bu görüntüyü fast report'ta nasıl görüntüleyebilirim ?

    private void Data1_BeforePrint(object sender, EventArgs e)
    {
      Picture1.ImageLocation =   ((String)Report.GetColumnValue("Detail.Picture"));                         
    }

bunu denedim ama başarılı olamadım.

File = D:\Projects\NET\LBYSNet\LBYSNet\LBYSNet.Web\App_Data\upload\Detail\00001\00001168_tyrqbdcpnw2su.png

tşk.ler.

**Comment by volkanceylan** [comment]
URL eklemeniz lazım başına mysite
com/upload/Detail...

**Comment by oaltay** [comment]
http://localhost:14304/upload/Detail/00001/00001168_tyrqbdcpnw2su.png

bu haliyle resmi görüntüledim. tşk.ler
