### ISSUE TITLE
Excel Multiple values in column representatives error

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1730]
I am using the Customers table, added multiple representatives, and when using the Excel export button, at the representatives column i am getting numbers (ids) instead of the actual representative name. 

Also, in ReportRepository.cs at      public byte[] Render(IDataOnlyReport report), the return doesnt have the representatives names, only their ids, i think from here the problem originates.

**Comment by sayuga** [comment]
do you have the formater on your rows.cs or your columns.cs Excel export uses the Columns.cs to define a lot of the information format

**Comment by volkanceylan** [comment]
A formatter you define in script code don't and can't work with Excel output as it works on server side. Pdf output might to some degree as text is read from client side and Pdf is generated client side. For server side you need to write a decorator attribute, deriving from BaseCellDecorator.

By the way you wrote this in another topic.
>i want to donate for fixing 2 major bugs with serenity. If a column has multiple string values, in excel export it shows only the id... jsPDF is not printing UTF-8 chars.
> What donation would be suffice to cover for your time?

You probably misunderstand meaning of a "donation", and fix mix it with sponshorship or professional support.

First one is not a bug, works as designed.

Second one i'm not author of jsPDF, you should ask in their repo.

**Comment by chizdamasii** [comment]
@volkanceylan I used http://serenity.is/demo/Northwind/Customer export to Excel, as you can see the Representatives column is not showing properly. Thank you for your feedback. Usually donating means supporting something, but sometimes you can donate and receive something in return. The reason i used the donation term is i dont plan to use the fix for myself only, im letting you add it to the source, thus supporting the cause. Logically speaking it leans towards sponsorship. Will a 50$ donation cover your time with the excel bug?

**Comment by volkanceylan** [comment]
Which part of "it is not a bug" you didn't understand?
