### ISSUE TITLE
DateTimeEditor is not working with rtl

### ISSUE THREAD

**Issue by zasZakareia** [volkanceylan/Serenity#1732]
i like this template it gives me ability to create a project in fast and easy way but i think there a small bug in serenity when change layout to rtl with DateTimeEditor, there is no time and when you try to change the date it gives you "The string is not recognized as a valid date time. there is  unknown word starting at index 10", i tried to add (jquery-ui-i18n.js) script in layout header. the time is appeared but gives me an error invalid date format for both (rtl and ltr)

Please go to 'http://serenity.is/demo/Meeting/Meeting' change language to  farsi and try to edit the meeting start date. i think this link explaining the error

best regards, and thank you for this great template

**Comment by volkanceylan** [comment]
It's a bug with date picker, but anyway

Find this code in Serenity.Script.UI.js

```js
this.$time = $('<select/>').addClass('editor s-DateTimeEditor time').insertAfter(input.next('.ui-datepicker-trigger'));
```

Replace with

```js
		this.$time = $('<select/>').addClass('editor s-DateTimeEditor time');
		var after = input.next('.ui-datepicker-trigger');
		if (after.length > 0) {
			this.$time.insertAfter(after);
		}
		else {
			after = input.prev('.ui-datepicker-trigger');
			if (after.length > 0) {
				this.$time.insertBefore(after);
			}
			else {
				this.$time.insertAfter(input);
			}
		}
```
