### ISSUE TITLE
How can I generate a row in Dialog

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1733]
Hi , Nice to see you again!
As the title , How can I create a row in dialog.ts.  as the 'Country' Row . Such as, I want to create a new 'Tel' row behind the 'Country' Row. What should I do in xyzDialog.ts.
![image](https://cloud.githubusercontent.com/assets/20295114/21643982/2095b932-d2c6-11e6-8ade-94ee73d7fc0e.png)

**Comment by brunobola** [comment]
have you read the tutorials ?

**Comment by weiguanhai** [comment]
I want to create it when I loadEntity , It really in tutorials? Maybe I miss it , Can you tell me something about?

**Comment by abelal83** [comment]
@weiguanhai can you explain a little better what you're trying to do? If you simply want to add an additional row in dialog why not create the column in database, add to row.cs and then to form? This was it will be auto generated for you in dialog.

**Comment by weiguanhai** [comment]
Sorry ! It's my fault, Such as ,I have a column in database ,and  it is a 'json' data . but I want to  separate it for better edit way ,  So we need serval undefined count row for this .  and make up them in a column ,then save the json to my table of the db . So I want to create them when loadEntity by dynamic .@abelal83 .
