### ISSUE TITLE
Need Example ListRequestHandler for Web API

### ISSUE THREAD

**Issue by aa6my** [volkanceylan/Serenity#1734]
Can anyone here personally guide me how to use ListRequestHandler. I read from documentation quite confuse.

I want to implement Web API and using ListRequestHandler for execute json object for api GET. Anyone have any idea how should i start?

Okay i succesfully implement Web API in serenity.
And already add new database using sergen command at PM console name GenWell.

So it already generate

GenWellColumns.cs
GenWellDialog.ts
GenWellEndpoint.ts
GenWellForm.ts
GenWellGrid.ts
GenWellIndex.ts
GenWellIndex.cshtml
GenWellPage.cs
GenWellRepository.cs
GenWellRow.cs

So how do i using repository to generate json for Web API

```
public class GenWellsController : ApiController
{
    private GenWellContext db = new GenWellContext();

    // GET: api/GenWells
    public IQueryable<GenWell> GetGenWells()
    {
        return db.GenWells; // How do i change this to json ?
    }
}
```

**Comment by dfaruque** [comment]
var connection = SqlConnections.NewFor<GenWellRow>();
var request= new ListRequest();

rreturn new GenWellRepository().List(connection, request).Entities;

**Comment by aa6my** [comment]
var request= new ListRequest();

which one i should include for using

**Comment by aa6my** [comment]
error when i using GenWellRepository

An explicit conversion exists (are you missing a cast?)

**Comment by xareas** [comment]
change IQueryable<GenWell> to IList<GenWell>
