### ISSUE TITLE
Resizing height of editor fields when dialog height changes

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1735]
Any way to easily change the height of HtmlNoteContentEditor or TextAreaEditor fields on a dialog when the dialog is resized or maximized? I see the width grows with the dialog but the height remains the same...

Thanks!

**Comment by edson** [comment]
Some css styling would be the easiest way... I suppose.

Best regards

**Comment by volkanceylan** [comment]
I prefer to do it with javascript, with CSS auto height is too painful, at least for me

**Comment by edson** [comment]
Agreed, @volkanceylan . CSS and I are not even friends, but I've been trying to get along with it... Sometimes it's just love and sometimes it's just hate... :-)

Best Regards
