### ISSUE TITLE
Enable and disable  the Add and the Update buttons at run time according to the role

### ISSUE THREAD

**Issue by Dinesteine** [volkanceylan/Serenity#1737]
Hi Volkanceylan,

I am developing an application in Serenity. Thanks for developing the senerity framework. It works awesome. But, in my application Add,Update and Delete buttons should be enabled and disabled according to the role provided to the user. 

Thanks,
Dinesh H.

**Comment by dfaruque** [comment]
you may use jQuery at yourDialog.ts
inspect browser and get the add/... button css class and get that element by jquery
i mean `$('.save-and-close-button').hide()`

**Comment by wldkrd1** [comment]
in yourDialog.ts, override getToolbarButtons()

`protected getToolbarButtons() {
			var buttons = super.getToolbarButtons();
			if (!Authorization.hasPermission("Review:Audit:Modify")) {
                buttons = buttons.slice(2);
            }
            if (!Authorization.hasPermission("Review:Audit:Delete")) {
                buttons = buttons.slice(1);
            }
			return buttons;
		}`

**Comment by Dinesteine** [comment]
Thanks wldkrd1, but when i put above script in Dialog.ts. After compilation, when i refresh the browser it gives blank screen. There is an error in consol of the browser. It would be really helpful, if you provide correction location or whole yourDialog.ts file.

**Comment by wldkrd1** [comment]
Sorry, that was an example; in my case, I'm checking for specific permissions and removing buttons if they aren't there. You wouldn't have those same permissions, perhaps that's why you are getting an error? What error are you getting?

**Comment by Dinesteine** [comment]
Thanks wldkrd1.

In my case, after removing protected  word from you have suggested. It works for me.

Thanks Again.

**Comment by fremar83** [comment]
Amazing job! Thanks to everyone's investment !!
It always returned false for me and I realized that I gave autorisations across roles. If I deliver Autorisation directly to user, it works. How can I test autorisation across roles ?
Thanks by advance !

**Comment by fremar83** [comment]
My mistacke ! I changed permissions in roles (from Modify to Update and Delete separated) and did not check roles again. So roles did have "...:Modify" as I was waiting for "...:Update". It works like a charm! This really is an amazing solution.  I really enjoy it a lot!
Many thanks again!

**Comment by fremar83** [comment]
Hi again! I'm sorry but I don't understand how slice property works (particularly start and end numbers).
In a standard Toolbar, we get 3 buttons (update and save, apply changes, delete).
I want to hide the second button (apply changes) depending on some rights. 
I did some tests (see below) and I don't find this case.
First column is start and end number. The cross in the 3 columns after is placed when the first, second or third button is hided. I don't reach my case in it.
 
    0 |   |   |  
0_0 | x | x | x
0_1 |   | x | x
0_2 |   |   | x
0_3 |   |   |  
    1 | x |   |  
1_0 | x | x | x
1_1 | x | x | x
1_2 | x |   | x
1_3 | x |   |  
    2 | x | x |  
2_1 | x | x | x
2_2 | x | x | x
2_3 | x | x |  
2_4 | x | x |  
   3 | x | x | x
3_0 | x | x | x
3_1 | x | x | x
3_2 | x | x | x
3_3 | x | x | x

Chears

**Comment by fremar83** [comment]
Problem solved here [https://github.com/volkanceylan/Serenity/issues/932]
By the way, it solved mi The hide of the add button.
Many thanks again!!
