### ISSUE TITLE
Header Grouping

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1738]
can we use the example below to group the headers in serenity.

http://hariharanpalani.github.io/SlickGrid/examples/example-HeaderGrouping.html

**Comment by volkanceylan** [comment]
No, thats a custom extension

**Comment by mrajalko** [comment]
is there in any other way some columns can be grouped.

do you recommend that i may use any other grid like data table to display data.

**Comment by volkanceylan** [comment]
I don't know.
