### ISSUE TITLE
MySaveHandler With MasterDetailRelation not working

### ISSUE THREAD

**Issue by LaurentzT** [volkanceylan/Serenity#1741]
Hi,

I have a Master Detail relation between Account =>> Stal:
`[MasterDetailRelation(foreignKey: "AccountID", CheckChangesOnUpdate = false)]
        [DisplayName("Stal lijst"), SetFieldFlags(FieldFlags.NotMapped)]
        public List<StalRow> StalList
        {
            get { return Fields.StalList[this]; }
            set { Fields.StalList[this] = value; }
        }`

But now I want him to also Execute the BeforeSave function of the Stal:

` protected override void BeforeSave()
            {
                base.BeforeSave();
                Request.Entity.BeslagNummer = "wqdqwfaa";
            }

            protected override void AfterSave()
            {
                base.AfterSave();
                Request.Entity.BeslagNummer = "wqdqwf";
            }`

The problem is that he doesn't enter these functions...

Thanks for the help!

**Comment by LaurentzT** [comment]
And if I use this code in the TypeScript file of Stal:

`protected addButtonClick() {
            this.editItem(<Northwind.OrderRow>{
                BeslagNummer : 'test'
            });
        }`

It also doesn't init my Property

**Comment by dfaruque** [comment]
In `MasterDetailRelationAttribute` the detail's repository won'n be called. use Master's Repository instead.
