### ISSUE TITLE
Pre Populated form with data from database

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1743]
I have 2 Tables with similar structures.
I need, as a result of what the user chooses, to populate the fields in table #2 with data from table #1
I think I have to do this by rewriting the AfterLoadEntity method in my MyOwnDialog.ts

Can you point me in the right direction?

**Comment by javaman63** [comment]
Thanks for the reply!!

What I need is to take certain fields from table #1 and pre fill them in the form of table #2, an example of this would be an address and a PO box of a customer, for example

**Comment by Boumboumjack** [comment]
Like here? [PopulateLinkedDataDialog.ts  ](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/PopulateLinkedData/PopulateLinkedDataDialog.ts)

**Comment by javaman63** [comment]
THANK YOUUUUUUUUUUUU!!!

You're a Life-Saver!!!!
