### ISSUE TITLE
Serenity doumentation

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1744]
Hello Volcan.
First I like to congratulate you for the job you have done. 
I am an old developer who has been working with tools and languages from dinosaur age, as Visual basic, visual form design etc. I have never worked with css. On the other hand I have worked with case tools and code generators, erp implementation, and web platforms to develop specific applications as BI and I am a very experienced application analyst.
I tried serene template using your tutorial and found it amazing. I am convinced that it can deliver professional applications very quickly.
I don't know c# yet, but I had no problem go with the tutorial and find my way to some issues out of it: For example, you describe the old version of sergen, but found out how this one works. Or you don't describe anywhere how to put an "edit filter" functionality in the grids, but I copied the line @serenity.Decorators.filtered() from CustomerGrid.ts into MovieGrid.ts and worked. I found also the slider images, the favicon etc.
On the other hand, I have found the logo image that is loading at the login screen and I can overwrite it giving the same name at my own logo, although I suspect this is not the proper way. I have also tried the copy-paste method for excel-export and pdf-export buttons from the customergrid.ts but they didn't work. So this is definitely not the proper way. I have also tried to put another editor for the movie storyline field, finding its name and using it the same way as the text editor described in the tutorial, but didn't work either.
My request is to advice for documentation about the rest of the serenity functionality, as a reference guide if such exists, and how to accomplish the functionality there is in the demo (charts, widgets, dashboard, etc) 

Thank you for your time

Dimitris Kontodimos

**Comment by stixoffire** [comment]
@dkontod look here for more info https://www.gitbook.com/book/volkanceylan/serenity-guide/details
