### ISSUE TITLE
Using in or exists Criteria in request.Criteria

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1745]
Hi,
I'm using Oracle in my project and wondering if it's possible to use "in" or "exists" in request.Criteria as the below example:
```
var request = this.view.params as Serenity.ListRequest;
            request.Criteria = Serenity.Criteria.and(request.Criteria,
                [['DEPT_CODE'], 'in', "(select DEPT_CODE from USERS_DEPTS_INFO WHERE USERID=" + vUserID +")" ]);
```
or 

`  ['DEPT_CODE'], 'in', "(" + vUserDepts +")"`

I want the grid to show the user departments courses only, but it shows no records, no errors, no console messages, if I remove the criteria it shows all records.

If not possible I will change to stored procedure.

Thanks

**Comment by volkanceylan** [comment]
You can't use arbitrary SQL in client side criteria, as clearly noted in docs.

That filtering must go to server side applyfilters.

**Comment by mhussein67** [comment]
Thanks Volkan, that what I thought. I've converted this to stored procedure.
