### ISSUE TITLE
Hide a table from the toolbar, but still have it available in dialogs etc.

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1746]
I've noticed in the Serene demo that a number of Northwind tables aren't shown in the Admin LTE toolbar on the lefthand side of the screen (EmployeeTerritory, CategoryLang, etc.)

In those cases there's no corresponding <XYZ>Page.cs class, which is where the NavigationLink entries are set.  I'd like to hide certain tables from the toolbar, since they're dealt with in the app itself and there's no need to give them their own toolbar entry.  

However, since they are being used in the app I need their corresponding <XYZ>Page.cs classes, but am not sure how to hide them from the toolbar?  (I tried commenting out the assembly:NavigationLink entry at the top of the page class, but that just led to a runtime error.)

**Comment by abelal83** [comment]
Can you post the runtime error message you're getting to better understand as commenting navlink should work.

**Comment by lquantz** [comment]
Thanks for double-checking for me.  As it turns out, you're correct, commenting out that line does do the trick; what had happened is I rebuilt the solution and hit the debug button in visual studio-- ordinarily that step takes me to the homepage.  

This time, possibly because I was sitting on XYZpage.cs, the debug session opened on a non-existent route (something like http://localhost:1111/Serene/NoRouteHere, which led to a runtime error about a route.  

I simply assumed my commenting out that line led to the error, but in fact for some reason VS opened the debug session on an incorrect URL-- I haven't been able to replicate the issue since.
