### ISSUE TITLE
responsivedialog içerisinde grid resize işlemi

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#1747]
![dialog](https://cloud.githubusercontent.com/assets/6660401/21711726/175bfb90-d3f9-11e6-9573-8203756fda66.png)

diyalog resize oldugunda grid yüksekliği değişmiyor. her hangi bir css eklemedim grid için herhangi bir tetikleyici metod varmı?

varsayılan olarak diyalogun yüksekliği ile geliyor. ama dialog resize olunca grid resize olmuyor.
@volkanceylan

**Comment by xareas** [comment]
add CSS class to container  s-DialogContent

**Comment by oaltay** [comment]
thanks you.
