### ISSUE TITLE
Using the entity within the getToolbarButtons function

### ISSUE THREAD

**Issue by JoshDiDuca** [volkanceylan/Serenity#1748]
Hi there, I'm trying to push a button with a value from the entity and the current entity ID but it seems as if getToolbarButtons is called before the entity is loaded therefor the entity is always null when the button is pressed by the user.

Would it be possible to point me in the right direction? I'm fairly new to typescript but have good amount of C# experience.

getToolbarButtons Function:

        getToolbarButtons() {
            var buttons = super.getToolbarButtons();
            if (this.entity != null) {
                buttons.push(BusinessManagement.Common.StatusHelper.createAcceptStatusButton({
                    title: 'Accept',
                    cssClass: 'accept-button',
                    entityID: this.get_entityId(),
                    currentStatus: this.entity.StatusId
                }));
                buttons.push(BusinessManagement.Common.StatusHelper.createDeclineStatusButton({
                    title: 'Decline',
                    cssClass: 'decline-button',
                    entityID: this.get_entityId(),
                    currentStatus: this.entity.StatusId
                }));
            } 
            return buttons;
        }

**Comment by volkanceylan** [comment]
Yes it runs before an entity is loaded. You should handle entity dependent operations in on click event, so better call your handlers acceptStatusClick etc. passing entity on click, or do it like it is done with ReportingHelper create button sample, e.g. one in order dialog.

**Comment by JoshDiDuca** [comment]
Thank you volkanceylan, just the answer I needed!

You're a big help, thanks, our team will definitely be donating once we've gotten everything out of the way.
