### ISSUE TITLE
How to get the update date?

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1749]
How to get the update date from my row?

`        public DateTime? FechaVisita { get; set; }`

**Comment by joheric** [comment]
When I create a user I want this to have the default date and at the time of updating the date change.

**Comment by stixoffire** [comment]
@joheric your db column can be set with a default date, if you wish to place the date then you can overide the BeforeSave method in MySaveHandler class in your repository.

            protected override void BeforeSave()
            {
                base.BeforeSave();

                if (IsUpdate)
                {
MyColumnField = DateTime.Now() // Format how you want it ..
}
}

**Comment by joheric** [comment]
Thanks!!!

**Comment by vinaykulkarni89** [comment]
@joheric please close the issue if it is solved
