### ISSUE TITLE
How to display html text as plain text in grid column.

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#175]
Hello sir,

I want to display html text as plain text in grid column, so how to display.

**Comment by linpiero** [comment]
Hi,
i have create a htmlFormatter in project.Script:
public class HtmlFormatter : ISlickFormatter, IInitializeColumn
    {
        public string Format(SlickFormatterContext ctx)
        {
            var text = HttpUtility.HtmlDecode(ctx.Value.ToString());

            return "<div>" + text + "</div>";
        }
        public void InitializeColumn(SlickColumn column)
        {
            
        }
    }
then i have used the attribute on the columns of entityColumns  in project.
Ps.
however I have seen the example "EmployeeFormatter" in the NorthWindProject.
regards

**Comment by laxmanp** [comment]
I used above code same as  EmployeeFormatter but following error throws -
Uncaught TypeError: Cannot read property 'lastChild' of null
slick.grid.js?v=8a8b2f7ykyKq9dzhH06b7A2:1741 

Uncaught TypeError: Cannot read property 'toString' of undefined
Serene.Script.js?v=7yKFo7e9AP9Pjja1ZnSjxQ2:5217

**Comment by VictorTomaili** [comment]
EmployeeFormatter has a example for encode html code. I think this works

```csharp
    public class HtmlFormatter : ISlickFormatter, IInitializeColumn
    {
        public string Format(SlickFormatterContext ctx)
        {
            return Q.HtmlEncode(ctx.Value);
        }
    }
```

**Comment by volkanceylan** [comment]
Why you use HtmlDecode? Victor's sample is correct, but you don't need a formatter for this, as columns already html encode. Are you trying to show raw html markup like <span> etc, or just text content stripping html tags? Btw, the error in code is ctx.Value.ToString(), you should check for not null first before calling toString

**Comment by linpiero** [comment]
Hi, 
it's right , however, the response is to indicate to use "HtmlFormatter" and not my implemation.
thank's for your job
regards

**Comment by laxmanp** [comment]
Thanks

**Comment by muhammedyaman** [comment]
```

namespace  Northwind.Customers{

    @Serenity.Decorators.registerFormatter()
    export class HtmlFormatter implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {
            var text = ctx.value;

            return text;
        }
    }
}
```
this works for me.
