### ISSUE TITLE
Quick Search With Stored Procedures

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1751]
Can anyone please guide me on how to get quick search option working in a scenario where data is being populated via stored procedures.

otherwise please guide me on how to display only a few records of a large table (around 40 million rows) based on fixed criteria that can never be overridden so that user is not able to ask for full data of the table.

**Comment by volkanceylan** [comment]
Write your criteria on server side.

**Comment by mrajalko** [comment]
thanks @volkanceylan  for your response.
Are you suggesting that i should be be overriding something in *grid.ts.

is there something like getquickserach.

is there some sample to show how to override default behavior of quck serach.

**Comment by volkanceylan** [comment]
Override applyfilters in list handler
