### ISSUE TITLE
One to one relation with image in details

### ISSUE THREAD

**Issue by atip29** [volkanceylan/Serenity#1753]
I have 2 tables with a 1-to-1 relation.  The foreign key table has an image.  I have changed the form so that it retrieves fields from both tables as explained in the "LeftJoin attribute" chapter of the guide (page 359), but when I save the form I get the exception "For security reasons, only temporary files can be used in uploads!".

    [LeftJoin("pf", "Person_photo", "pf.[person_id] = T0.[person_id]")]
    public sealed class PersonRow : Row, IIdRow, INameRow
    {
        [DisplayName("Person Id"), Column("person_id"), Identity]
        public Int32? PersonId
        {
            get { return Fields.PersonId[this]; }
            set { Fields.PersonId[this] = value; }
        }

`

        [DisplayName("Photo"), Size(255), ImageUploadEditor(FilenameFormat = "Person/Photo/~")]
        [Expression("pf.[photo_filename]"), ReadOnly(true)]
        public string PhotoFilename
        {
            get { return Fields.PhotoFilename[this]; }
            set { Fields.PhotoFilename[this] = value; }
        }
`

Even marking the picture field as ReadOnly does not prevent the error.
Any ideas on what I may be doing wrong?

Is it possible to save the details table with the picture from the same form, or do I have to open a dialog to edit the picture?

Thanks,

Antonio.

**Comment by atip29** [comment]
After debugging through Serenity I found that the problem was that the field from the details table in SaveRequestHandler.Old property had not been initialized, and it seemed like the picture was new and it was coming from a folder other than the temporary folder, therefore validating it.
I solved it by adding the following to the PersonRepository:

```
       private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override SqlQuery PrepareQuery()
            {
                SqlQuery q = base.PrepareQuery();
                q.SelectNonTableFields();
                return q;
            }

```
I do not know if there is a declarative-more-proper way to do this.

I am trying to change the repository to save these fields now.  If someone knows how to go about this, I would appreciate any samples.

Antonio.

**Comment by Estrusco** [comment]
But you have already uploaded the photo in Person_Photo, then the ImageUploaderEditor in PhotoFilename is not necessary

**Comment by atip29** [comment]
@Estrusco, how do you show/upload the image without an ImageUploadEditor?

That would be the Person edit form/dialog.  I want to be able to edit the Person Photo, and also the Person's main entity fields from the same form (if possible).  I have removed the ReadOnly(true) attribute in order to achieve this: 

Person_Photo(person_id) references Person(person_id).  Both person_id fields are pk fields of both tables, thus it is a 1-1 relation.

The fields shown below the photo in the image are fields in Person table.

![image](https://cloud.githubusercontent.com/assets/8558729/21781594/715c6cce-d6b0-11e6-9e32-0813bbf84409.png)

**Comment by atip29** [comment]
Thanks @Estrusco .  I will try to create a custom ImageUploadEditor as you suggest.
