### ISSUE TITLE
MyApp.Administration.Entities not recognized

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1754]
Hello.
I have created an application with Serene. I have built and run the demo project and everything was fine.
Then I have created several tables using a migration, run sergen and produces the source files for these tables, and then tried to rebuild with no success. There are errors in the administration oblects and every one of them starts for the declaration "using MyApp.Administration.Entities;" which - as the explanation says - cannot find any Administration namespace.
Note that this started when I created a new project with new version of serene. I tried update packages, but no update needed to be installed.
Here is the build error log:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Validation (CSS 3.0): "-ms-transition" is not a known CSS property name.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Welcome.htm	66	
Error	CS0234	The type or namespace name 'Administration' does not exist in the namespace 'AddressDB.AddressDB' (are you missing an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\Language\LanguageLookup.cs	4	Active
Error	CS0246	The type or namespace name 'LanguageRow' could not be found (are you missing a using directive or an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\Language\LanguageLookup.cs	10	Active
Error	CS0234	The type or namespace name 'Administration' does not exist in the namespace 'AddressDB.AddressDB' (are you missing an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\Translation\TranslationRepository.cs	17	Active
Error	CS0234	The type or namespace name 'Administration' does not exist in the namespace 'AddressDB.AddressDB' (are you missing an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	3	Active
Error	CS0234	The type or namespace name 'Administration' does not exist in the namespace 'AddressDB.AddressDB' (are you missing an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Common\Navigation\NavigationModel.cs	4	Active
Error	CS0103	The name 'LanguageRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\Language\LanguageLookup.cs	14	Active
Error	CS0103	The name 'LanguageRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\Language\LanguageLookup.cs	22	Active
Error	CS0103	The name 'UserRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\Translation\TranslationRepository.cs	148	Active
Error	CS0103	The name 'UserPermissionRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	36	Active
Error	CS0246	The type or namespace name 'UserPermissionRow' could not be found (are you missing a using directive or an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	44	Active
Error	CS0103	The name 'RolePermissionRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	57	Active
Error	CS0246	The type or namespace name 'RolePermissionRow' could not be found (are you missing a using directive or an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	65	Active
Error	CS0103	The name 'UserRoleRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	77	Active
Error	CS0246	The type or namespace name 'UserRoleRow' could not be found (are you missing a using directive or an assembly reference?)	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Administration\User\Authentication\PermissionService.cs	85	Active
Error	CS0103	The name 'UserPermissionRow' does not exist in the current context	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Common\Navigation\NavigationModel.cs	20	Active
Warning		Validation (CSS 3.0): "-ms-transition" is not a known CSS property name.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Welcome.htm	50

**Comment by dkontod** [comment]
I visited every one of the objects in error and replaced the declaration
using MyApp.Administration.Entities;
with the following:
using Administration.Entities;
Then I tried to rebuild which was successful, with the following warning errors:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe" -project "D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\tsconfig.json"" exited with code 3.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\AddressDB.Web.csproj	2842	
Warning		Validation (CSS 3.0): "-ms-transition" is not a known CSS property name.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Welcome.htm	50	
Warning		Validation (CSS 3.0): "-ms-transition" is not a known CSS property name.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Welcome.htm	66

**Comment by volkanceylan** [comment]
How did you manage to use MyApp as root namespace, while your project name is AddressDB.

Others are warnings. Also install TypeScript 2.0 not 2.1

**Comment by dkontod** [comment]
"MyApp" was just a general reference. Of course my project is AddressDB. It was AddressBook, but I considered that the name was some like a reserved word which was causing the errors, or because there is a table named AddressBook in my database, that's why I created the project AddressDB and started all over. Typescript 2.1 is installed/updated automatically by either visual studio or serenity. I'll try to install 2.0 and respond. Shall I have to undo the changes I've already done?

**Comment by volkanceylan** [comment]
Everything has to be under your root namespace, which is solution name by default that was stated in docs.

**Comment by dkontod** [comment]
Thank you. Happy new year
