### ISSUE TITLE
How to solve AuthenticationError, similar to issue #1539

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#1755]
Hello Friends!

Please your help (I'm newbee), how to change the following line of code in the AccountPage.cs

`throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);`

I'll need only show a message that the username or password not match. I make the following changes in the LoginPanel.ts but still not working.

`onError: function (response) {                                             
                              Q.notifyError(Q.text('Invalid username or password!'));
                     },`
![error1](https://cloud.githubusercontent.com/assets/24989427/21751720/b1a33406-d599-11e6-9c3c-55c4c907d6c2.jpg)

Please help me with what more changes we need to make in this files (LoginPanel.ts and AccountPage.cs) to the throw exception not stop the program.

Thanks for your help and congrats @volkanceylan for this excellent work.

Wait your important comments.

**Comment by volkanceylan** [comment]
It doesn't stop the program, it throws an error which is caught in javascript as a message. Don't debug if you don't want to break on exceptions, or uncheck Common Language Exceptions there.
