### ISSUE TITLE
Continuing Issue #1754: More errors after Typescript 2.0.3 installation

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1756]
Hello Volkan.
I uninstalled Typescript 2.1 and installed Typescript 2.0 as you suggested. But as I had 3 warning messages when build, now I have 2 errors and 6 warnings, in different typescript files than before:

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2339	Property 'Common' does not exist on type 'typeof AddressDB'.	TypeScript Virtual Projects	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Northwind\Customer\CustomerGrid.ts	19	Active
Error	TS2339	Property 'Common' does not exist on type 'typeof AddressDB'.	TypeScript Virtual Projects	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules\Northwind\Customer\CustomerGrid.ts	26	Active
Warning		The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\tsc.exe" -project "D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\tsconfig.json"" exited with code 2.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\AddressDB.Web.csproj	3058	
Warning		Property 'Northwind' does not exist on type 'typeof AddressDB'.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules/BasicSamples/Dialogs/SerialAutoNumber/SerialAutoNumberDialog.ts	37	
Warning		Property 'Common' does not exist on type 'typeof AddressDB'.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules/Northwind/Customer/CustomerGrid.ts	19	
Warning		Property 'Common' does not exist on type 'typeof AddressDB'.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules/Northwind/Customer/CustomerGrid.ts	26	
Warning		Property 'Common' does not exist on type 'typeof AddressDB'.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules/Northwind/Order/OrderDialog.ts	20	
Warning		Property 'Common' does not exist on type 'typeof AddressDB'.	AddressDB.Web	D:\Visual Studio Projects\AddressDB\AddressDB\AddressDB.Web\Modules/Northwind/Order/OrderGrid.ts	95

**Comment by volkanceylan** [comment]
Please understand that this is not TypeScript support line. I suggest you start from beginning and do proper naming this time.

**Comment by dkontod** [comment]
Thanks for the reply Volkan.
I am afraid I caused a misunderstanding. I have not made any naming from myshelf. My namespace is named AddressDB. I have written MyApp as the issue title to have it general. My mistake.
All problems started when I created a new project and a new version of serene was downloaded automatically. There are changes in migrations (there is a CreateTable32 method now), in sergen (there are options for lookup generation among others). I've done nothing of my own except creating a migration, and then generating code with sergen for the tables. Nothing - absolutely nothing - else. And I've done this three times. I'll do it a forth now, but I am not optimistic.

**Comment by volkanceylan** [comment]
Serene doesn't auto update in your existing projects, it just applies to new projects. Serenity nuget packages can be updated but still you do it yourself.

**Comment by volkanceylan** [comment]
The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\tsc.exe" 

You still have TypeScript 2.1

Property 'Common' does not exist on type 'typeof AddressDB'

There is a namespace Common under Serene, so AddressDB, this errors makes no sense.

**Comment by dkontod** [comment]
OK I'm going to create a new project from scratch. The only thing I'll do, is to copy my migration code to the new project instead of re-typing it.

**Comment by dkontod** [comment]
Brand new project AddressBookDB. Nothing else but the serene demo. I tried to run customer excel report (At excel button was the error with common namespace).
This appeared: 
![image](https://cloud.githubusercontent.com/assets/24634785/21754323/a9863404-d606-11e6-9f33-4853a0d2e1b2.png)
If I continue, it stops one more time and then the excel is produced.
The same in orders
The same at products.

**Comment by volkanceylan** [comment]
I don't get such an error. And if it really fails it can't produce excel file.
