### ISSUE TITLE
Sergen. System Argument Out Of Range Exception

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#1757]
Hi,
I´m trying to generate code for a very simple table with only 2 fields (id and description) and sergen crashes.
StartIndex cannot be longer than the chain length 
Any idea? Thanks in advance
I have codeGenerator 2.7.2 unless with 2.7.1 got the same result
![image](https://cloud.githubusercontent.com/assets/24249067/21754092/fc278cb4-d5f0-11e6-8746-a9bfafcd5110.png)

**Comment by stixoffire** [comment]
@pesnunj0 - what DB engine , and is this table related to a Foreign table ?  It looks like it is trying to get a property from the table an it cannot or has a null value  so taking a Substring of it is where the issue is - check your column names  for example description field is normally reserved key word - so it could be choking on that field - depending on db ..

**Comment by pesnunj0** [comment]
Thanks for your quick answer.
Db Engine is mysql. Another table is related to this one. The name of the fields are in spanish
1.- "concepto_acelerador_id"  type smallint Key, Not null, Autoincrement,
2.- "concepto"  type varchar(20)
I don´t see ant strange thing....

**Comment by volkanceylan** [comment]
concepto is detected as a table field prefix, common for all fields, so concepto fields generated name is empty string. that's why it fails.

**Comment by pesnunj0** [comment]
Oh, I never guess a Spanish word would be used.
I generated the code manually.
I assume that if it happens again is due to a reserved word
Thanks a lot

**Comment by pesnunj0** [comment]
Sorry,
I have two new tables with exactly the same issue. The first one is sexos with only two fields sexo_id and sexo. This one is not a problem, I built it manually, but the second ne is a big table.
Will you be so kind and tell me wich field is reponsible for the crash in order to rename it?
Are there a list of reserved words?
Is it posible to solve these kind of issue in other way?
Thanks a lot
[clientes.zip](https://github.com/volkanceylan/Serenity/files/698348/clientes.zip)

**Comment by volkanceylan** [comment]
Upgrade to 2.8.0. It is not about reserved words, it is about prefixes.

**Comment by pesnunj0** [comment]
Sorry but with 2.8.0 I get the same result.
