### ISSUE TITLE
Adding Products to an Order on the Order Dialog

### ISSUE THREAD

**Issue by shaunbsoft** [volkanceylan/Serenity#1758]
Hi,

I am trying to replicate the Northwinds order dialog, where you can add order details to the order. I have replicated everything required, however, I am getting a typescript error, saying that getLookup does not exist on type 'typeof StockProductsRow'.

I have added this function the the Stock.StockProductsRow.ts file in common/imports/servertypings, but it gets removed every time I build the templates, hence why I am getting an error to say it is missing. Is there a reason this is removed? I assume it is rebuilt, and getting removed. If so, where do I place the function, or an override file for this?

Many Thanks,

**Comment by stixoffire** [comment]
@shaunbsoft I think your StockProductsRow needs a declaration of LookupScript on your details - pay close attention to the Declarations on your properties. Also make sure your values and types  match the Northwind example between StockProductsRow and StockProductsColumn.  The server typings do not need to be edited they are auto generated every time you build the T4.

**Comment by sayuga** [comment]
Long story short, make sure there is a [LookupScript()] on the StockProductsRow.cs
