### ISSUE TITLE
Missing language and setting option

### ISSUE THREAD

**Issue by ahsansolution** [volkanceylan/Serenity#1759]
Dear All,

We still use old version 2.3.6, why, every time we go to dashboard page,
we miss language and theme options? Anyone have the same problem?

![missing_language](https://cloud.githubusercontent.com/assets/21119641/21759335/2b560c24-d676-11e6-938d-44dbe72bf0de.PNG)

**Comment by williamhodges** [comment]
I had the same issue, however if you upgrade to 2.7+ it has been resolved. It may be resolved in an earlier version, but in 2.7+ it's fixed.

**Comment by ahsansolution** [comment]
Oke noted thanks for answer

**Comment by ahsansolution** [comment]
Any other solution without upgrade version?, my application already fix for Go Live. :)

**Comment by volkanceylan** [comment]
Check console
