### ISSUE TITLE
Add Serenity to existing project

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#176]
Hi all, I love Serenity project, but i would like to use Serenity project to my existing project as an administrative zone. Have you got any ideas how to do that ? 

For example :
1) Add new Area in my existing project
2) Add new Asp.Net MVC project to My Solution
3) Add new Solution which will use curent database 

Thanks

**Comment by volkanceylan** [comment]
All would be fine. I dont use areas though. If MVC versions same, it would work in same project. Just make sure you enable attr routing and include settings from web.config. It could also run as IIS subsite like admin under your app.
