### ISSUE TITLE
Could not find field '__id' on row of type 'TRow'

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#1760]
I have used `GridEditorBase` to set the data of master/detail handly with `setItems` method.
This method required a `__id` field, therefore, I cast the list of object to dynamic
This worked fine for loading the data to the detail list
However, when I click `Save` button, it throw an exception: 
`Could not find field '__id' on row of type 'TRow'`
How can I fix that

**Comment by volkanceylan** [comment]
You fix that by not doing invalid things at first

**Comment by volkanceylan** [comment]
__id must start with ` character (tilda)
