### ISSUE TITLE
Hide navigation items

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1761]
I have created an XYZ module with sergen, in user module when i deselect all permissions to this XYZ module the link appears in navigation menu(with error when accessing moudle), i need to know if it is possible to hide navigation link if all permissions are removed to user

**Comment by sayuga** [comment]
If they have all the permission un-selected but you are still seeing the navigation link, check the xyzPages.cs. the 'PageAuthorize' permission key should be set such that when a permission is removed that someone is not allowed to see the page, the page dissapears from the link. 

The three main locations to remember for permissions are: 

xyzPage.cs -     [PageAuthorize(PermissionKeys.General)] - says whether you can see the page. 

xyzRow.cs-     [ReadPermission(PermissionKeys.General)] /  ModifyPermission(PermissionKeys.General)] / etc  - Controls who can do what on the page

xysEndpoint.cs -     [ServiceAuthorize(PermissionKeys.General)] / [AuthorizeCreate(typeof(MyRow))] / etc. - controls access to the service controllers. 

You can also add the permission attribute to the NavigationLink, if necessary.

**Comment by vinaykulkarni89** [comment]
thankyou @sayuga
