### ISSUE TITLE
FilterField and FilterValue

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1762]
How can i add multiple FilterFields and Values?

**Comment by dkontod** [comment]
I have put "@Serenity.Decorators.filterable()" at the top of EntityGrid.ts and it worked. An "Edit Filter" button appeared at the bottom-right of the grid and when pushing it an Edit Filter form pops up.

**Comment by vinaykulkarni89** [comment]
I have LookupEditor where i'm using FilterField and FilterValue, i wanted to know if i can apply filter on multiple Fields

**Comment by Estrusco** [comment]
See here https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/handling_lookup_scripts.html
