### ISSUE TITLE
Enabling browser spellchecker on HtmlReportContentEditor

### ISSUE THREAD

**Issue by nscgllc** [volkanceylan/Serenity#1763]
First, I want to thank @volkanceylan and everyone contributing to this fantastic framework!  Really great job!

I do not think this is an issue per say but more ... how to.  I am struggling to enable the default browser spellchecker on the HtmlReportContentEditor, HtmlContentEditor, and HtmlNoteContentEditor.  I have tried to set the CKEditor property disableNativeSpellChecker = false through Serenity but nothing works.  If I use the CKEditor outside of Serenity setting the property disableNativeSpellChecker = false works fine.

Can the native browser spell checker be enabled through this framework?

Any advice or recommend would be greatly appreciated.

**Comment by edson** [comment]
Hi.
You mean, like this? 
![image](https://cloud.githubusercontent.com/assets/62490/21862114/f4e7a436-d81e-11e6-955c-b035a895790f.png)



I did this by extending Serenity.HtmlContentEditor and overriding the getConfig() to set disableNativeSpellChecker = false and customize somethings.

I don't know if it is what you are looking for.

Best Regards

**Comment by volkanceylan** [comment]
Yep, that's the correct way.

**Comment by nscgllc** [comment]
Thanks for the help!  I will try that....I have not tried extending anything so this will be a good opportunity.  I know there are examples ....if there is one in particular I should check out let me know.

**Comment by teafmartins** [comment]
> Hi.
> You mean, like this?
> ![image](https://cloud.githubusercontent.com/assets/62490/21862114/f4e7a436-d81e-11e6-955c-b035a895790f.png)
> 
> I did this by extending Serenity.HtmlContentEditor and overriding the getConfig() to set disableNativeSpellChecker = false and customize somethings.
> 
> I don't know if it is what you are looking for.
> 
> Best Regards

Can you post example code?
