### ISSUE TITLE
User details in Dialog

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1764]
How can i get Serenity.Authorization.UserId in *Dialog.ts
as of now i'm getting DisplayName and Username but i need UserId

**Comment by stixoffire** [comment]
@vinaykulkarni89 is userId column Declared Hidden() or Visible(false) ?

**Comment by Estrusco** [comment]
In UserForm add 

[Hidden]
public Int32 UserId { get; set; }

Compile, Transform all T4 template and you get in dialog.ts

**Comment by vinaykulkarni89** [comment]
@Estrusco i want the UserId in Serenity.Authorization, in *Dialog.ts

currently i'm getting only Username, DisplayName and HasPermission

**Comment by edson** [comment]
@vinaykulkarni89 Add UserId in ScriptUserDefinition.cs and UserEndpoint.cs

Best Regards

**Comment by vinaykulkarni89** [comment]
@edson thankyou, it helped me a lot
