### ISSUE TITLE
Filter in Listing Movies in Person Dialog

### ISSUE THREAD

**Issue by MsDanglar** [volkanceylan/Serenity#1765]
Hi Volkan,
I have a dialog with tabs as example "Listing Movies in Person Dialog"
In order to filter we have the next sample code:

`set personID(value: number) {
 if (this._personID != value) {
this._personID = value;
 this.setEquality(MovieCastRow.Fields.Persons, value);
 this.refresh();
  }
 }`

But Fields.Persons on my row is multiple field.
Can you kindly advise how can i filter a grid by multiple property?
thank You for you help.

**Comment by stixoffire** [comment]
@MsDanglar in the Movie Tutorial you will find the MovieGenre Lookup it is filterable - there is an example for the Quick Search - if you are using FilterField and FilterValue  - I am not sure . I hope this helps you in the right direction.

**Comment by MsDanglar** [comment]
Hi 
thanks for your reply, however, we have tried to follow the movie example as you mentioned above but without success.

**Comment by stixoffire** [comment]
@MsDanglar I am using the example and the quickfilter - mine works , the key is you must pay attention to your relations Id's and also Identity columns and also the <List> , I am using he User object and a Group object - it works correctly, you need to follow the guide very closely for the Movie Tutorial - I read it several times and made small mistakes here and there - and it works, are you using a SetRelationLink ?
