### ISSUE TITLE
How can I set the dialog width/Height with Screen Width/Height 

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#1766]
Dear Volkan,

How can I set the dialog the same width and height with screen's width and height. I want to let the dialog to show the monitoring information to users and maximize it's same size as screen?

Thanks,
Harry

**Comment by Estrusco** [comment]
https://github.com/volkanceylan/Serenity/issues/367

**Comment by harrypassport** [comment]
Thanks Estrusco,
I use your code in my dialog.ts file as below:
protected onDialogOpen()
 {
           J(".ui-dialog-titlebar-maximize").Click();
           super.onDialogOpen();
            
 }

And system tell me that the J can not be recognized by system.(I can not use J("") before). So can you tell me what should be referred and how to be recognized by system?


Thanks a lot.
Harry

**Comment by Estrusco** [comment]
The code is in saltarelle. For jQuery is 

```ts
$(".ui-dialog-titlebar-maximize").click();
```

**Comment by MaradiagaSistemas** [comment]
Just Write:

  protected onDialogOpen() {
            $(".ui-dialog-titlebar-maximize").click();
            super.onDialogOpen();

        }

On YourDialog.ts

**Comment by harrypassport** [comment]
Thanks Estrusco & Maradiaga.

So where should I put [Maximizable] attribute, or other position?
 
[Maximizable]
export class BranchDialog extends Serenity.EntityDialog<BranchRow, any> {
        protected getFormKey() { return BranchForm.formKey; }
.....
....
It seems fail to pass the compiling.
Can you give me sample as brief description?


Thanks,
Harry

**Comment by volkanceylan** [comment]
@harrypassport there is a search function in Visual Studio, search for maximizable.

**Comment by harrypassport** [comment]
Thanks Volkan.
I got that.
Harry
