### ISSUE TITLE
Excel export

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1767]
Hello.
How I can create an excel export for my table (as the one in Customer page) which will export the columns I have on the grid for the selected records. Can I have a record selector to have the procedure working for the selected records?

**Comment by sayuga** [comment]
The current Excel Export will export whatever records are actively displayed on the grid. If you filter the grid such that it displays the records you want then you just need to export as is. See the Wiki. https://github.com/volkanceylan/Serenity/wiki/Adding%20Excel%20Export 

There is also a excel export button in place for almost all northwind samples. Check the code on it and you'll see it's pretty straight forward,

**Comment by dkontod** [comment]
Thank you very much. I had copied the code from CustomerGrid.cs, but it needed some editing as I understand now. Plus that I needed the code from CustomerEndPoint.ts as well.
