### ISSUE TITLE
ServiceAuthorize attribute

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1769]
Hi all, 

I'd like to change behavior ServiceAuthorize attribute to handle multiple permissions, for example [ServiceAuthorize("group1", "group2")]. What I would do is split the groups being passed in and check for membership - I know how to do this but I can;'t work out how to override the default behavior. Any ideas?

Thanks!

**Comment by volkanceylan** [comment]
There was an issue explaing this. Do some searching.

**Comment by abelal83** [comment]
@volkanceylan  thanks for the quick response as always. I did some searching and read https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_register_permissions_in_serene.html however, from what I understand ServiceAuthorize checks if user is logged in, and if permission is passed will check for that too. But I'd like to know if it's possible to pass multiple permissions to ServiceAuthorize? I think as it is it won't but can we override with another class?

**Comment by volkanceylan** [comment]
Issue means it is in github, LogicalOperatorPermissionService

**Comment by abelal83** [comment]
I worked this out, for anyone who is interested...

my PermissionService.cs was already modified as below
```

    public class PermissionService : IPermissionService
    {
        public bool HasPermission(string permission)
        {
            if (Authorization.Username == "admin")
                return true;

            string[] permissionItems = permission.Split(',');

            foreach (string permissionItem in permissionItems)
            {
                if (Roles.IsUserInRole(permissionItem.Trim()))
                    return true;

                if (Authorization.Username == permissionItem.Trim())
                    return true;
            }

            return false;
        }
```

this is customised (Active Directory provider based) for our requirement and is different to the original one supplied in serenity. As I split permission by comma I simply passed [ServiceAuthorize("group1", "group2")] and it just works. I wasn't entirely sure if ServiceAuthorize implemented its own permission methods but as it uses PermissionService (found out after testing) I posted this question. 

Hope this helps others.
