### ISSUE TITLE
How to handling concurrency ? 

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#177]
Hi Volkan,
How to handling concurrency ? 
Is there a way to do this? or is there example ? 

Thanks

**Comment by volkanceylan** [comment]
I usually dont worry about this as even if you check and warn user about changes, they ll say yes without reading and override. You may handle it at database level with locks etc or use usual where conditions on timestamp, more key fields etc for critical operations, but i dont have a sample.

**Comment by MrPec** [comment]
Sorry to reopen the topic. I also have to handle concurrency. The first step, adding a rowversion column in SQL server is very easy. On every update/insert SQL server automatically updates the column. (".WithColumn("VerCol").AsCustom("Rowversion")") 

So, I only need to find out on how to adjust the save handler update statement, e.g. include current rowversion like:

Update XYZTable set .... where XYZTableId = 1 and rowversion = previousvalue

In case no row was affected I can proceed and give the user the information that the changes could not be saved.

I examined the MySaveHandler class, but I did not get the created SQL statement... Where should I look, is there a method I can override within the SaveHandler? Or do I have to modify the sources?

**Comment by ielbury** [comment]
@MrPec, Did you ever figure this out? This is one area in Serenity that I think is not addressed. The solution is likely there but it's not clear.

@volkanceylan . I always have a couple of screens that I need to do concurrency checks. In my case, I always make the user re-enter/resubmit the data. Is there an easy way to detect concurrency violations?

**Comment by volkanceylan** [comment]
Serenity doesn't have to or can't address every need of every programmer. But it doesn't prevent you from doing something. You should just try to look at code or other samples and understand where to inject something. Try something like this:

```
        protected override void ExecuteSave()
        {
            if (IsUpdate)
            {
                var idField = Row.IdField as Field;
                if (Row.IsAnyFieldAssigned)
                {
                     new SqlUpdate(Row.Table).Set(Row)
                         .Where(
                              fld.YourID == new ValueCriteria(idField.AsObject(Row)) &
                              fld.YourTimeStamp == yourOldTimeStamp)
                         .Execute(Connection);
                        
                    Response.EntityId = idField.AsObject(Row);
                    InvalidateCacheOnCommit();
                }
            }
           else
                base.ExecuteSave();
        }
