### ISSUE TITLE
sergen: what is the functions of the new generation options?

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1771]
Hello.
Serenity 2.7.2 has some extra generation options in sergen:
![image](https://cloud.githubusercontent.com/assets/24634785/21815966/1264cb32-d767-11e6-92e8-c557614ffb68.png)
What is the meaning of them?

**Comment by stixoffire** [comment]
@dkontod TSC path - typescript path for different versions of TypeScript ie 1.8, 2.0, 2.06 etc.
You can set the Module name in the grid for each of your tables - so they can be in different modules - really cool and it defaults to the Connection Name if you do not change it in the grid.
I think the others are really self explanatory .. like region endregion around row fields (don't really like that) as it is individual fields.

**Comment by dkontod** [comment]
Thank you very much

**Comment by dfaruque** [comment]
@dkontod  To work inplace edit/add you have to remove the "Row" from the generated Row.cs I mean replace `[LookupScript("somthingRow")]` with `[LookupScript("something")]`

**Comment by dkontod** [comment]
Thank you very much @dfaruque. I would have never found it myself. Is this a bug?

**Comment by dfaruque** [comment]
hmm. #1775 already fixed this issue.
