### ISSUE TITLE
Unable to install Visix in 2017 RC1

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#1776]
I'm not sure if you are aware, but if you cannot install the visix into VS 2017 RC1. This maybe due to it being a release candidate, but just wanted to bring it to your attention.

**Comment by volkanceylan** [comment]
Yep VSIX doesn't support 2017

**Comment by williamhodges** [comment]
Thanks @volkanceylan I didn't know that about '17RC1
