### ISSUE TITLE
Good way to disable add buttons when appropriate?

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1777]
I'm wondering if there's a good way to disable the add buttons when needed.  

For example, if I have an Order dialog with a tab for an Order Details grid, I would like to disable the "New Order Details" button on the Order Details grid unless there's an actual order first.  This way, I have to create the order before trying to add any order details.

Alternatively, if it's possible to disable the tabs themselves in these circumstances, that could work too.  I see in the samples there's a Remove Add Button example, and if that's the canonical way of handling a situation like this I can do that as well.

**Comment by edson** [comment]
If you want to disable a tab, you can use  Serenity.TabsExtensions.setDisabled function... Other than that is just a matter of finding the element and hiding ou toggling it by some logic...

There is a sample for this tab behavior, search for OtherTabInForm... etc...

Best Regards

**Comment by volkanceylan** [comment]
Order details in order dialog is already disabled on new record mode

**Comment by lquantz** [comment]
Thanks edson, I'll look at that for disabling a tab.

Regarding the Order Details on a new Order dialog...it seems I can add new Order Detail records to a new Order, based on the screenshot below.  Am I missing something, should the button be disabled?

![image](https://cloud.githubusercontent.com/assets/2700083/21873283/6fece8f0-d822-11e6-9d41-9aa2f166e78a.png)

**Comment by Mzamo7** [comment]
Hi 
did anyone managed to get the above, disabling the Order Details button on a new Order dialog.
I am experiencing the same issue, i have tried everything but i can't seem to get it right..

Regards,
Mzamo

**Comment by ANDY7575** [comment]
@Mzamo7 CAN PLEASE share code how to disable details add button on master dialog..
thanks in advance..

**Comment by ShaikBaresha** [comment]
[Category("Version Details"), HideOnInsert]
public List<Entities.CoDcVersionsRow> VersionList { get; set; }

Just add "HideOnInsert" in form.
