### ISSUE TITLE
Excel Import

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1778]
Hello.
I have an excel file with thousands lines that I want to a table. The mapping can be done manually in the excel file. The excel file must be located by a user dialog. This procedure has to be standardized because this update has to be done in a regular basis. The lines in the excel file can exist or not exist in the table. The identification will be done with a combination of 4 fields (LastName, FirstName, FatherName, MotherName). If they exist they will be updated. If not they will be inserted. The excel file can contain less fields than the table's columns. The mapping will ensure that all required columns exist in the file. The procedure must have the option to run partially (for a fragment of the excel file).
A report must be produced to indicate the inserts or updates and possible errors (missing required field, non-existing foreign key etc) and this must have the possibility to run in proof, thus without making any changes for checking purposes.
Any advice how to create this tool?
Is there a tool that can be used for direct upload?

**Comment by volkanceylan** [comment]
There is an excel import sample already and this is best advice you can get.

**Comment by dkontod** [comment]
Volkan where can I find this example?

**Comment by mreid2005** [comment]
You can find it here.
https://github.com/volkanceylan/Serenity/wiki/Excel-Import---Extended:-Column-Mapping-and-Import-Value-Type-Handling
