### ISSUE TITLE
Updating auditing fields in table

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1779]
Hello
I have a main table with 4 auditing fields: CreationDate, LastUpdateDate, LastUpdateUser, LastUpdatePrg.
I have written the following lines in Repository MySaveHandler:

            protected override void BeforeSave()
            {
                base.BeforeSave();
                Row.LastUpdateDate = DateTime.Now;
                Row.LastUpdateUser = Authorization.Username;
                Row.LastUpdatePrg = "AddressBookForm.cs";
                if (IsCreate)
                {
                    Row.CreationDate = DateTime.Now;
                }
            }
But I am getting the error 
![image](https://cloud.githubusercontent.com/assets/24634785/21845519/aa928266-d7fb-11e6-8a7f-863cbece6272.png)

What is wrong?

**Comment by volkanceylan** [comment]
See mapping guide, see logging row attributes

**Comment by dkontod** [comment]
Sorry @volkanceylan but I cannot find a solution. I have read carefully the topic "Mapping Attributes" at the page 351 of the "Serenity Guide" - it is the only "mapping guide" I could find - and I haven't found anything that I have done differently. The code I have written is as suggested in the issue #1749 from stixoffire. As for the logging row attributes, the only information I have found is how to remove them from the foreign fields of a Row.cs. The debugging I've done showed me that Authorization.Username has the correct value when the error occurs. I don't know why it is not applied at the field to be written in the table.  
Thank you for your time.

**Comment by volkanceylan** [comment]
Is it so hard to see this line in LoggingRow.cs:

```
        [Insertable(false), Updatable(false)]
        public Int32? UpdateUserId
```

The man who put it there must have a reason right? What is your reason for using me like google.

**Comment by dkontod** [comment]
I am very sorry if you feel I am using you like Google. I have posted a question (rookie question I understand) for anyone who feels he can help and wants to. I understand you have thousands of such questions and you feel you have to answer to all of them, but as I have already introduced myself to you, I am an experienced analyst who is very new in c# and serenity. If you feel you don't have the time for me, just ignore me and I hope some other experienced will help me. 
The thing is that I feel serenity is a treasure for developers and I don't want to abandon it. The other thing is that I cannot find full documentation for it. I try by reverse engineering in a language I don't know, upon a platform I am now learning to use, to understand what's happening. If you can suggest me another action path that will bring me at the state of developing business applications without silly questions, please advice.
Thanks for the advice. I'll try to implement it.

**Comment by dkontod** [comment]
The solution surprisingly was to make the logging fields in the table and the row class nullable. This bypassed the error and updated the fields with the right data.
