### ISSUE TITLE
Timestamp Designations and Field Lock on event. 

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#178]
So, my brain has been spinning on how to best deal with this but I've been hitting a wall. I get the feeling it's something so simple I'm just missing it but I've probably just been staring at the coding much too long. 

Here is the premise: 

I have four 'DateTime' Fields and a 'Status' enumerated field. 

        [Category("Revisions")]
        public DateTime LastUpdated { get ; set; }
        [Updatable(false)]
        public DateTime AddedOn { get; set; }
        public DateTime EditedOn { get; set; }
        public DateTime RemovedOn { get; set; }
        public Int32 Status { get; set; }

Now, i will not be allowing the deletion of any records because we need to be able to audit everything thus I instead am Time stamping changes according to the "Status" field. 

Status Field has 3 enumerations MatrixStatus.Added, MatrixStatus.Editted" and MatrixStatus.Removed. 

Essentially, I need to accomplish the following. When a record is fist created, LastUpdate AND AddedOn Populate to Now(). AddedOn then becomes locked so it can't be updated Manually. I have "Status" field with DefaultValue(1), meaning MatrixStatus.Added, which is meant to be the trigger for the initial update. 

From that point onward, any change needs to be recorded by triggering the LastUpdated field with New() and either EditedOn or RemovedOn should be triggered as well whenever the "Status" field is changes to 2 (Editted) or 3 (Removed).

Additionally, when an item is set to Removed, it needs to be locked from updating. 

So far I've been attempting to designate the restrictions on the TableForm.cs  file since it should only affect the form but not much success.

  [Category("Revisions")]
        [Updatable(false)]
        public DateTime LastUpdated
        {
            get { return LastUpdated; }
            set
            {
                DateTime CurrentTime = DateTime.Today;

                if (Status = MatrixStatus.Added)
                { LastUpdated = CurrentTime; }

                else if (Status = MatrixStatus.Removed)
                { LastUpdated = CurrentTime; }

                else if (Status = MatrixStatus.Updated)
                { LastUpdated = CurrentTime;  }

                else
                { LastUpdated = value;   }
            };
        }

                  ...
//I reuse the same set up for AddedOn, EditedOn and RemovedOn
            [Updatable(false)]
        public DateTime AddedOn
        {
            get {  return AddedOn; }
            set
            {
                DateTime CurrentTime = DateTime.Today;

                if (Status = MatrixStatus.Added)
                    {AddedOn = CurrentTime;}
                else
                    {AddedOn = value;}
            };
        }

Any suggestions? Any way Serenity can implicitly default a date to a form? What about a fields lock trigger for whenever a field is no longer 'Null'?

**Comment by volkanceylan** [comment]
See LoggingRow and IUpdateLogRow, IInsertLogRow and IDeleteLogRow, IIsActiveDeletedRow interfaces. All your fields should be Updatable(false), Insertable(false) and so not editable by end user.

**Comment by sayuga** [comment]
I give. Could I have you provide me a sample when you have a moment? No immediate rush but help is appreciated. (I have it set to manual entry for the time being) 

I attempted to recreate the LoggingRow setup on the fields I needed but I'm getting nothing. It'll rebuild and transform properly and when I go to the item in question when running the item is locked from update but holds no data. Here is what I've done: 

I  added the following to the MatrixRow.cs:

// ILoggingRow was added to class for logging test. 
    public sealed class MatrixRow : Row, IIdRow, INameRow, ILoggingRow 

...
//Added Insertable(false), Updatable(false) to all DateTime fields
      [DisplayName("Last Updated"), Width(100), AlignCenter, NotNull, Insertable(false), Updatable(false)]
        public DateTime? AddedOn
        {
            get { return Fields.AddedOn[this]; }
            set { Fields.AddedOn[this] = value; }
        }

...

        DateTimeField IInsertLogRow.InsertDateField
        {
            get { return Fields.LastUpdated; }

        }

        DateTimeField IUpdateLogRow.UpdateDateField
        {
            get { return Fields.LastUpdated; }
        }

   IIdField IUpdateLogRow.UpdateUserIdField
        {
            get
            {
                throw new NotImplementedException();
            }
        }

        IIdField IInsertLogRow.InsertUserIdField
        {
            get
            {
                throw new NotImplementedException();
            }
        }

**Comment by volkanceylan** [comment]
You also need UpdateUserId fields otherwise this will raise an error. If you just want LastUpdated column,don't implement this interface, remove it.

Override SetInternalFields method of your SaveHandler and set Row.LastUpdated = DateTime.Now

**Comment by sayuga** [comment]
Well, I need LastUpdated, AddedOn, RemovedOn and EditedOn. Thus my challenge. 

The sequence of events goes: 
Create Item: LastUpdated and AddedOn Triggers
Make a Change to existing record: LastUpdated and EditedOn triggers. 
Remove(delete) item.  Instead of delete:: LastUpdated and RemovedOn Triggers. Plus Record locks thus no more edit allowable. 

I was attempting to use an enumerated field called "status" as the trigger but....not working too well.

**Comment by volkanceylan** [comment]
Start by overriding SetInternalFields, you can set all of these fields there.

**Comment by sayuga** [comment]
Thanks for the guidance, I'll give it another go and let you know how it goes.

**Comment by sayuga** [comment]
Ok, so I've gone ahead and locked the fields on the xxxxRow.cs using the "[Updateable(false), Insetable (false)]"

I've created a override for both IsCreate and IsUpdate as follows:

            protected override void SetInternalFields()
            {
                base.SetInternalFields();

                if (IsCreate)
                {
                    Row.LastUpdated = DateTime.Today;
                    Row.AddedOn = DateTime.Now;
                }
                if (IsUpdate)
                {
                    Row.LastUpdated = DateTime.Now;
                    if (Row.Status.Value == MatrixStatus.Updated)
                    {
                        Row.EditedOn = DateTime.Now;
                    }
                    else if (Row.Status.Value == MatrixStatus.Removed)
                    {
                        Row.RemovedOn = DateTime.Now;
                    }
                    else if (Row.Status.Value == MatrixStatus.Added)
                    {
                       return;
                    };
                };
            }

I reviewed the logic behind it and it seems solid yet it does not appear to be implementing. 

My understanding is as follows: 

By overriding the SetInternalFields I designate the initial values present at the moment the form show a new Item (IsCreated) or an item being updated (IsUpdate). Since these are overrides, they should implement behind the update and insertable clauses block to the fields thus by using the if else on the status field, I should be able to implement a change to the value of the locked fields. Am I wrong somewhere? 

If I don't get anywhere further on this from here, I'm going shelf this for some other time. and continue to some other parts of the code. I don't want to waste too much of your time on this.

**Comment by volkanceylan** [comment]
This method is called on every save (insert/update). Why are you checking Status field here? Here you should set only AddedOn, EditedOn and LastUpdated fields. I recommend you override DeleteRequestHandler and instead of calling base method (ExecuteDelete), update your rows LastUpdated and RemovedOn fields.

**Comment by sayuga** [comment]
Ahh, I think I see my mistake.  these override when committing the entry. I was under the impression it was building when the form initializes. That is why I was attempting to build the event into the insert/update. Ok, I think I'm back on track on this. I was just looking at things backwards. Sorry about that.

**Comment by sayuga** [comment]
Ok, so I managed to figure everything out except for one thing, the locking of the fields after "delete". 

I've overridden the delete ExecuteDelete and listed all the fields that I wish to lock. But I can't seem to figure out how to properly update the field attributes on the repository side so as to make them "Updatable(false)". What is the serenity command I can use to override the current attribute? 


namespace FMCDashboardV2.FMCorp.Repositories
{
    using Serenity;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using Serenity.Services;
    using Serenity.Web.Providers;
    using Serenity.ComponentModel;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Web.Security;
    using MyRow = Entities.MatrixRow;
    using UDefinition= Administration.UserDefinition;

                  //.......//
     private class MyDeleteHandler : DeleteRequestHandler<MyRow>
        {
            protected override void ExecuteDelete()
            {
                using LockUpdate = GetAttribute<UpdatableAttribute>(false);

                
                Row.CustomerName.LockUpdate;
                Row.AddressOptional.LockUpdate;
                //.....//
                Row.RemovedOn = DateTime.Now;
                Row.Status = MatrixStatus.Removed;
            }
       }
