### ISSUE TITLE
Enumerator does not return the description

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1780]
I have implemented an one-to-many editing procedure, following the one described for MovieCast. The difference is that I have an enumerator (CommunicationType) instead a foreign key. So I used the logic described for Gender in the guide.

Here is my CommunicationType.cs:

using Serenity.ComponentModel;
using System.ComponentModel;

namespace AddressDB.AddressBookDB.Entities
{
    [EnumKey("AddressBookDB.CommunicationType")]
    public enum CommunicationType
    {
        [Description("Mobile")]
        Mobile = 1,
        [Description("Home Phone")]
        HomePhone = 2,
        [Description("Work Phone")]
        WorkPhone = 3,
        [Description("Skype")]
        Skype = 4,
        [Description("Viber")]
        Viber = 5,
        [Description("Email")]
        Email = 6,
        [Description("Web Site")]
        WebSite = 7
    }
}

Here is my CommunicationRow.cs:

namespace AddressDB.AddressBookDB.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), DisplayName("Communication"), InstanceName("Communication"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class CommunicationRow : Row, IIdRow, INameRow
    {
        [DisplayName("Communication Id"), Column("CommunicationID"), Identity]
        public Int32? CommunicationId
        {
            get { return Fields.CommunicationId[this]; }
            set { Fields.CommunicationId[this] = value; }
        }

        [DisplayName("Address"), Column("AddressID"), NotNull, ForeignKey("[adr].[AddressBook]", "AddressID"), LeftJoin("jAddress"), TextualField("AddressLastName")]
        public Int32? AddressId
        {
            get { return Fields.AddressId[this]; }
            set { Fields.AddressId[this] = value; }
        }

        [DisplayName("Communication Type"), NotNull]
        public CommunicationType? CommunicationType
        {
            get { return (CommunicationType?)Fields.CommunicationType[this]; }
            set { Fields.CommunicationType[this] = (Int32?)value; }
        }

        [DisplayName("Communication Number"), Size(100), NotNull, QuickSearch]
        public String CommunicationNumber
        {
            get { return Fields.CommunicationNumber[this]; }
            set { Fields.CommunicationNumber[this] = value; }
        }

        [DisplayName("Communication Description"), Size(100)]
        public String CommunicationDescription
        {
            get { return Fields.CommunicationDescription[this]; }
            set { Fields.CommunicationDescription[this] = value; }
        }
.....................

And here is my CommunicationColumns.cs. The difference from the guide is that I could not change the type of CommunicationType field from Int32 to CommunicationType, until I included the "using Entities;" declaration, the same as in CommunicationForm.cs:

namespace AddressDB.AddressBookDB.Columns
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;
    using Entities; //needed for the declaration of CommunicationType

    [ColumnsScript("AddressBookDB.Communication")]
    [BasedOnRow(typeof(Entities.CommunicationRow))]
    public class CommunicationColumns
    {
        //[EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        //public Int32 CommunicationId { get; set; }
        //public Int32 AddressId { get; set; }
        [EditLink]
        public CommunicationType CommunicationType { get; set; }
        [EditLink]
        public String CommunicationNumber { get; set; }
        [EditLink]
        public String CommunicationDescription { get; set; }
    }
}

Here is the result where although in the dialogue the description "Mobile" appears correctly, in the grid appears the value "1":

![image](https://cloud.githubusercontent.com/assets/24634785/21848356/02b4c780-d809-11e6-8644-dbb59e9ac0ea.png)
![image](https://cloud.githubusercontent.com/assets/24634785/21848375/1031fe0a-d809-11e6-8a98-ec0e50998321.png)

**Comment by volkanceylan** [comment]
Search prior issues.

**Comment by dkontod** [comment]
Sorry @volkanceylan but I cannot find a solution. I have found a couple of issues, but if the originator is an experienced developer he just throws a breadcrumb of information and closes the issue. Cannot find the cause of this event or the way to fix it. 
Thank you for your time.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/1722
