### ISSUE TITLE
Inplace add and filtered lookup

### ISSUE THREAD

**Issue by allema** [volkanceylan/Serenity#1781]
We have an issue with inplace add and cascaded lookup. Serenity seems to ignore `‘InplaceAdd = true’` for fields that have a filtered lookup. In our example we want to inplace add a member which is filtered by member type (see screenshot)

![image](https://cloud.githubusercontent.com/assets/1392746/21851083/da7689fc-d80d-11e6-831e-28b188686c35.png)

**Comment by volkanceylan** [comment]
Sorry @allema but i can't reproduce this.

Tried it in Northwind Customers:

```
        [LookupEditor(typeof(Scripts.CustomerCountryLookup))]
        public String Country { get; set; }
        [LookupEditor(typeof(Scripts.CustomerCityLookup), 
              CascadeFrom = "Country", CascadeField = "Country", InplaceAdd = true)]
        public String City { get; set; }
```

![image](https://cloud.githubusercontent.com/assets/752470/22056195/965f355c-dd67-11e6-9a61-d0da0da8ce04.png)

Are you sure you don't have a custom editor, or some other thing that overrides InplaceAdd, e.g. duplicate editor attributes on row and form?

**Comment by allema** [comment]
Thanks, was indeed a duplicate editor attribute.

**Comment by fremar83** [comment]
I have neither CascadeField nor CascadeFrom attributes in lookupEditor in my project.
Even in NorthWind Customers. 
`[Width(130), LookupEditor(typeof(Scripts.CustomerCountryLookup)), QuickFilter]
        public String Country { get; set; }
        [Width(120), LookupEditor(typeof(Scripts.CustomerCityLookup))]
        [QuickFilter, QuickFilterOption("cascadeFrom", "Country")]
        public String City { get; set; }
        [Width(120)]`
Is this feature (QuickFIlterOption) the new way to filter a LookupEditor or am I focusing on the wrong file (CustomerColumns.cs) ?
