### ISSUE TITLE
[Everyone] Join us on Slack

### ISSUE THREAD

**Issue by VictorTomaili** [volkanceylan/Serenity#1782]
Here is community slack channel. Feel free for join.

Visit for invitation: https://serenityslackinvitation.herokuapp.com

http://serenityplatform.slack.com/

**Comment by dfaruque** [comment]
# great

**Comment by dkontod** [comment]
Hello. I get a "Failed! token_revoked" when I put my email there.

**Comment by VictorTomaili** [comment]
Fixed

**Comment by john20xdoe** [comment]
The Slack community there can provide support on topics that should not be posted here in Issues, (referring to #1610).
Examples: noob issues, language basics, setups, etc.

**Comment by rolembergfilho** [comment]
I'm there!


great @VictorTomaili

**Comment by VictorTomaili** [comment]
**Serenity Platform’s Weekly Summary**
Sunday, January 15th – Sunday, January 21st

Team sent a total of 473 messages last week (that's 419 more than the week before). Of those, 43% were in public channels and 57% were direct messages. Also uploaded 42 files

![Weekly Summary](https://resize.yandex.net/mailservice?url=https%3A%2F%2Fslack.com%2Femail_chart.php%3Fchart_type%3Dmessages_by_type%26team_id%3DT3PCTVBCZ%26ts%3D1485154812%26signature%3Daace11887a9f42fa924e08da35a4e48c33389b67&proxy=yes&key=3cc0b5138fc7e469d403ee7ac6b8a685)

**Comment by sayuga** [comment]
Considering how much we are now doing a lot more back and forth on slack, has anyone worked on an integration between slack and serenity? Would be a nice add-in

**Comment by VictorTomaili** [comment]
Serenity Platform’s Weekly Summary

Sunday, January 22nd – Sunday, January 28th

Your team sent a total of 253 messages last week (that's 220 fewer than the week before). Of those, 76% were in public channels and 24% were direct messages. Your team also uploaded 15 files (that's 27 fewer than the week before).

![image](https://cloud.githubusercontent.com/assets/2023440/22415307/27f91fbe-e6d7-11e6-8863-a798e38cdb63.png)
