### ISSUE TITLE
Field Unique accept NULL

### ISSUE THREAD

**Issue by DouglasEFerreira** [volkanceylan/Serenity#1784]
I have a unique field and would like it to accept the null value .. when populated it would do the unique value check. Can someone help me?

**Comment by Estrusco** [comment]
Post your row

**Comment by DouglasEFerreira** [comment]
[DisplayName("RAC"),Size(6), QuickSearch,Unique]
        public Int32? CodRac
        {
            get { return Fields.CodRac[this]; }
            set { Fields.CodRac[this] = value; }
        }

**Comment by VictorTomaili** [comment]
try to add notnull attribute and great news, i create a slack for disqus this questions and more. 
#1782
