### ISSUE TITLE
Paging in slickgrid with rows returned from stored procedure

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#1787]
Is there a way to have the slickgrid paging work with results returned from a StoredProcedure. The grid fills but is unable to page or display a row count?
Thanks so much

**Comment by volkanceylan** [comment]
Please ask in one place.

Nope, you need to handle paging like in VSGallery sample. Anyway, i strongly recommend against stored procedures unless absolutely necessary. They kill flexibility.

**Comment by dougdsank** [comment]
Thanks. Sorry for the double post. I totally agree but unfortunately we have to use SP for a few searches. Which VSGallery sample are you referring to? Thanks for the rapid response.

**Comment by volkanceylan** [comment]
The one in Serene, search in navigation.

**Comment by dougdsank** [comment]
Thank you I found it.
