### ISSUE TITLE
What could be the possible cause

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1788]
I have following two Coulumns in *Column.cs 

public Int32 Id { get; set; }
 public String Name { get; set; }

but only Id field is visible in grid, Name field isn't visible

![image](https://cloud.githubusercontent.com/assets/17939331/21879347/3c840362-d8be-11e6-91c0-d8adbb3a7683.png)

**Comment by abelal83** [comment]
have you checked it's not hidden in column picker?

**Comment by Estrusco** [comment]
See also if the column name is the same of the row field

**Comment by dfaruque** [comment]
try renaming `public String Name { get; set; }` to `public String PName { get; set; }` in Row.cs and column.cs.
also specify `[Column("[Name]")]` at PName in Row.cs
don't try to be logical here. please make the change and see what happens. :)

**Comment by abelal83** [comment]
just as note, sergen should have automatically done all this for you. Easiest option would be to delete the module (if there's no customisation to it) then recreate with sergen.

**Comment by vinaykulkarni89** [comment]
@abelal83 you were right the column was hidden in column picker and i have saved settings to local storage so every time the settings were restored

@dfaruque @Estrusco  thankyou for your time and sorry to bother you
