### ISSUE TITLE
How to display respected data of main tab in other tab

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#179]
I want to Show respected entries of master tab,in next tab.I am referring the example of customer & order,but in this case you  have use String.and here I  am using Long datatype.so its giving me an error of type cast.I am not getting how to achieve this?
Thanks in Advance.

**Comment by volkanceylan** [comment]
What is the error you getting and what is stack trace. Enable < customErrors mode="Off" />

**Comment by nilimajagtap** [comment]
jquery-2.2.0.js:1463 
Uncaught Error: Syntax error, unrecognized expression: #Serene_Exams_TestMasters_$TestMastersTestSectionsDialog31_Form

**Comment by volkanceylan** [comment]
You should go to that line and check if any syntax errors there. I can't understand whats wrong with info you present
