### ISSUE TITLE
Grouping and sum in master detail of dialog

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#1791]
I followed the `Grouping and summary` examples to implement a similar functions.
It worked fine with the grid, but in the master detail of dialog, it burned some issues:
- It also worked when I update, create the detail of the record
- But when I delete a new detail, for all details without the last detail, it worked fine too. However, when I delete the last detail of the record, the summary was not been updated.
Can you test yourself and show me the solution.
Thank you.

**Comment by volkanceylan** [comment]
It is not supported in master detail
