### ISSUE TITLE
how to Reports Design & how to custom validation and throw msg

### ISSUE THREAD

**Issue by mohansolai** [volkanceylan/Serenity#1794]
How to Custom Reports Creating & Custom Validation checking for database  to throw the stored procedure how to handled. Exception handling ,new added screens role permission how to added
1.Exist record validations
2.checkbox list examples
3.custom report how to i will write

**Comment by dfaruque** [comment]
have a look at northwind sample module.
http://serenity.is/demo/Northwind/Reports
for pdf
http://serenity.is/demo/Northwind/Order
click on pdf icon :)

**Comment by mohansolai** [comment]
how to custom validation and report included image

**Comment by mohansolai** [comment]
Thank you for your reply and once this doubt only you clarify.

**Comment by dfaruque** [comment]
see https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Northwind/Order
OrderDetailReport.cshtml is the report design with is pure razor/html.

**Comment by juliermefelix** [comment]
yes I read the article, I implemented it in the query but I did not get the result.
![image](https://user-images.githubusercontent.com/7516443/38036239-ab7b4140-327c-11e8-9fa2-e4a88daa8ce7.png)
