### ISSUE TITLE
Investigating possibility to make Form/Column type safe.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1795]
This is a less important issue!

Sometimes I have this kind of issues.
If I put a field in Form.cs but that field is not in Row.cs and I forgot to specify [OneWay] then I have runtime error. 

Is this possible to avoid such kind of unexpected behavior?

**Comment by volkanceylan** [comment]
It would be possible to add a check that raises error, but maybe you'd be handling that detail at client side. System can't be sure about that. It could only be a warning but unless you write some compiler extension, it is not trivial. Maybe an external tool to check.

**Comment by dfaruque** [comment]
Thanks for your valuable comment @volkanceylan
