### ISSUE TITLE
After sergen I can't see records.

### ISSUE THREAD

**Issue by Mumarda** [volkanceylan/Serenity#1796]
Hello I'm new at this... after running sergen and adding code for one of my db tables. When I try to see the information in the table, the grid is empty... I can see the numbers of records, but not the records:

![sergenerror](https://cloud.githubusercontent.com/assets/19939324/21912308/de39ffe6-d903-11e6-8042-9c6aa95c554d.jpg)

As you can see, the grid is empty, but the records are there in the DB, and If I click on "New Application Log" I can create a new record in the DB but I cann't see the record in Serenity.

Thank you.

**Comment by adhikamafran** [comment]
1. Did you rebuild & transform your sln ?
2. See your browser console, if any error.

**Comment by stixoffire** [comment]
Rebuild T4 templates
