### ISSUE TITLE
How can I keep back the old file on server when update a new file

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#1797]
like below, when I update the BOM file, I want to keep the old file on server, how can I do it?
![default](https://cloud.githubusercontent.com/assets/19610257/21917926/c4af6042-d986-11e6-96d6-3c87479c9d6a.PNG)

**Comment by edson** [comment]
CopyToHistory = true

Best Regards

**Comment by cp1319421** [comment]
@edson yes, it's can do it, but I want the old file in old folder don't be delete when update new file.

**Comment by edson** [comment]
Well... then you have to write your own behavior... There is no default parameter to attribute for this... See ImageUploadBehavior.cs for guidance..

Or replace your history record with the new file path (uploads/history/yearmonth...) when it's added to history table...

Best Regards
