### ISSUE TITLE
Creating a panel to update multiple entities

### ISSUE THREAD

**Issue by Satal** [volkanceylan/Serenity#1799]
I doubt this is something that has built in functionality but I've thought that a number of times before and been pleasantly surprised to find there is, hence asking here.

I'm trying to develop a panel page, which has a parent object and then two child objects (through a one-to-many relationship) that will be created at the same time.  While I appreciate it would be easier from our point of view to have the parent object created then add the child objects as separate steps the users' existing system implements it in one form so don't really want to add more steps in.

I've tried basing the development on [Entity Dialog as Panel](http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077) without success. Is there a simple way of achieving this through Serenity or am I just overcomplicating the Entity Dialog as Panel approach?

Any guidance you're able to give would be greatly appreciated.

**Comment by Estrusco** [comment]
Have you tried with a mix of example in http://serenity.is/demo/BasicSamples/OtherFormInTab or http://serenity.is/demo/BasicSamples/OtherFormInTabOneBar and http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077  ?

I do not know, however, it could be a starting point

**Comment by sayuga** [comment]
how about calling the other dialogs on AfterSave() and passing on the information there? If it's a matter of simply duplicating the data onto the appropriate columns on the other grids without using joint fields, I think it should work.
