### ISSUE TITLE
Dates before 1753

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#180]
Hi, I have data where I keep author information. Some of these dudes were born before 1753. How do I get past the DateEditor validation for this? In SQL the datatype = datetime2 in order to allow dates before 1753.

**Comment by volkanceylan** [comment]
Add [EditorOption("minValue", "1000-01-01")]

**Comment by wpvking** [comment]
I added this attribute, but now get the following error:

"An exception of type 'System.Data.SqlTypes.SqlTypeException' occurred in Serenity.Data.dll but was not handled in user code

Additional information: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM."

Any suggestions?

**Comment by volkanceylan** [comment]
Hmm it is about Sql parameter type probably. Dont have a workaround sorry. Use a string field in sql and row and add dateeditor attr for now.

**Comment by wpvking** [comment]
Thanks, that worked.
