### ISSUE TITLE
Dialog back button does not work on mobile

### ISSUE THREAD

**Issue by Satal** [volkanceylan/Serenity#1800]
When you browse to the serenity demo site, if you try to add any new item the dialog box shows up over the entire screen. While on the desktop there is a cross in the top right hand corner to close the dialog, on mobile you're presented with a back button in the top left hand corner. This back button does not cause for the dialog to close and the user is stuck on this page.

I am able to replicate this every time but I have only been able to test this on Chrome (55.0.2883.91) on Android 7.1.1. If there is any further information you require around this please do not hesitate to let me know and I'll do what I can to provide it :)

**Comment by sayuga** [comment]
I tested it on Opera and Chrome on my phone plus ran it through a few emulators and the button does appear to work but it seems the positioning may be getting in the way.  It's not very responsive in that corner...maybe making it larger or offsetting it from the edge may help.

**Comment by Estrusco** [comment]
I have the same problem with my Samsung S6 on Android 6.0.1

**Comment by sayuga** [comment]
I've come to notice the responsiveness of screens on mobile systems is tricky when the buttons are not of a particular size. has anyone tested slide on the screens? Maybe we should try making it so when mobile, slide right works as back?

**Comment by volkanceylan** [comment]
It works on my phone, not sure if it is about size, or jQuery UI block is preventing something. Try making that button bigger with CSS, and see if it still doesn't work.

**Comment by jmace** [comment]
I had this same issue on my android phone with chrome. 

I modified my serenity.css like below changing the width parameter. I can now get that button to fire from my phone.

`.ui-dialog.mobile-layout .ui-dialog-titlebar-close,
.ui-dialog.mobile-layout .ui-dialog-titlebar-close:hover {
  border: none;
  left: .3em;
  width: 38px; /*Mace Changed from 28 */
  height: 28px;
  background-color: transparent;
  background-image: url(images/back-arrow-black.png);
  top: 45%;
}`

**Comment by jmace** [comment]
Just an update on this... I've started adding this snippet to my xxxdialog.ts to catch a tap/click on the top dialog as a back press. This helps my users consistently navigate backward despite device or finger size. Glad to pass on or take any recommendations/improvements. 

Also, I'd love to know if there was a way I could make this type of behavior global to every dialog?

`//Mace: In mobile mode only, let a click on the title bar back out of the dialog window
            $('.ui-dialog-title').on('click touchstart', function (e) {
                e.preventDefault();
                if ($('body').hasClass("mobile-device"))
                    $(".ui-dialog-titlebar-close").triggerHandler('click');
            });
            $('.ui-dialog-titlebar').on('click touchstart', function (e) {
                e.preventDefault();
                if ($('body').hasClass("mobile-device"))
                    $(".ui-dialog-titlebar-close").triggerHandler('click');
            });`

**Comment by volkanceylan** [comment]
This is no longer a problem in latest Serenity, it was about cropzoom.js having an obsolete plugin that breaks touch devices.
