### ISSUE TITLE
Sorting in grid on master detail mode

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#1801]
How can I implement sorting feature on master detail grid?

**Comment by edson** [comment]
I've done this guided by these:

http://stackoverflow.com/questions/9678309/calling-sort-on-slickgrid
https://github.com/mleibman/SlickGrid/wiki/Slick.Grid

It's straightforward by sorting array and subscribing to onSort event. For general use, you should put it in a namespace and export that function so you can reuse it in any detailGrid.



Best Regards

**Comment by KlynkC** [comment]
@edson  Thank you so much
