### ISSUE TITLE
Error in Update platform

### ISSUE THREAD

**Issue by DouglasEFerreira** [volkanceylan/Serenity#1803]
Update 2.4 to 2.8 Using #1770

Assembly not found MsiEjavaScriptEngine.dll 2.0 
Using command Install-Package MsieJavaScriptEngine -Version 2.0.0

after error : Print
![erroserene1](https://cloud.githubusercontent.com/assets/20241746/21929021/592432a0-d975-11e6-86c0-f2dbfcd694b6.png)

Help me, please!

**Comment by volkanceylan** [comment]
Reinstall codegenerator

**Comment by DouglasEFerreira** [comment]
Update-Packege serenity.codegenerator ?

**Comment by DouglasEFerreira** [comment]
![print](https://cloud.githubusercontent.com/assets/20241746/21983344/f073beb4-dbd7-11e6-89bc-1852756219ec.png)

**Comment by volkanceylan** [comment]
Serenity uses Json.Net 9.0.1,  i don't know what you are trying to do.
