### ISSUE TITLE
Is Master Detail UI workflow with two EntityGrids possible?

### ISSUE THREAD

**Issue by uwascan** [volkanceylan/Serenity#1804]
I am new to this Wonderful Platform and would love to get guidance on how to achieve a  Master Detail UI workflow with two EntityGrids. This Platform has a lot of potentials but I think that there is need for more documentation of the Frontend Widget library. I would love to be able to use other UI Libraries like the once provided by Syncfusion Essential Studio for Javascript.

Thanks for this Cool Platform.

**Comment by dfaruque** [comment]
This is a full stack asp.net/core framework. You just need to **spend some more time** to digest the full life-cycle of this framework. **Anything is possible with javascript is possible with serenity**. 
You can always use other libraries along with serenity.
