### ISSUE TITLE
Unique Constraint on Expression Fields

### ISSUE THREAD

**Issue by MaradiagaSistemas** [volkanceylan/Serenity#1805]
Hi, Thank you for your amazing Job with Serene/Serenity.

I have a question, How can I add a Unique Constraint to an Expression Field.

This is how mi Row Looks like:

```
[DisplayName("Group Name"),
        Expression("(jType.[Name] + ', ' + jRegion2.[Name] + '/' + jRegion3.[Name] + '/' + jRegion4.[Name] + '/' + jRegion5.[Name])"), QuickSearch, MinSelectLevel(SelectLevel.Always)]
        public String GroupName
        {
            get { return Fields.GroupName[this]; }
            set { Fields.GroupName[this] = value; }
        }
```

Thank you for you help.

**Comment by abelal83** [comment]
Put the constraint on the column in database itself, when serenity attempts to write database engine will report back constraint error. I prefer this over adding constraint code as database can be updated with other apps following same set of rules.
