### ISSUE TITLE
Grid missing scrollbars when putting grid in a Tab

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#1806]
For some reason when I put below in a Tab control the grid scroll bars are missing. I added my chtml file for quick review. Thanks so much in advance.
<div id="GridDiv" class="grid-container">
                        </div>
                        <script type="text/javascript">
                jQuery(function () {
                    new ReverseQuest.Reversequest.LoanSearchResultsGrid($('#GridDiv'), {}).init();

[LoanSearchResultsIndex.txt](https://github.com/volkanceylan/Serenity/files/704821/LoanSearchResultsIndex.txt)
                    Q.initFullHeightGridPage($('#GridDiv'));
                });
            </script>

**Comment by edson** [comment]
My guess is to remove Q.initFullHeightGridPage($('#GridDiv')); and handle the height by yourself... It resizes it to Mobile view depending on width... But I didn't test your html.

Best Regards

**Comment by DouglasEFerreira** [comment]
@dougdsank  
I'm really having trouble
Did it work?

**Comment by dougdsank** [comment]
Set width and height

**Comment by wirble** [comment]
Thanks for the question and answers:

Set in .cshtml file and works good:
<div id="GridDiv" style="width:800px;height:600px;"></div>
