### ISSUE TITLE
MySql Guide for the .NET Core version.

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1809]
I need help connecting to the database in the new ASP.Net Core version.
What i had done:
1. Changed appsettings.json data in:

> "Data": {
>     "Default": {
>       "ConnectionString": "Server=localhost; Port=3306; Database=serene; Uid=root; Pwd=12345678",
>       "ProviderName": "MySql.Data.MySqlClient"
>     },
>     "Northwind": {
>       "ConnectionString": "Server=localhost; Port=3306; Database=serene; Uid=root; Pwd=12345678",
>       "ProviderName": "MySql.Data.MySqlClient"
>     }
>   },
2. Added mysql connector using: npm install 7.0.6-IR31

3. In project.json it added 

>     "MySql.Data.EntityFrameworkCore": "7.0.6-IR31"

After   "dependencies": {},

When im trying to connect i get the error:

> ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: providerInvariantName
> 
> Serenity.Data.DbProviderFactories.GetFactory(string providerInvariantName)

Can anyone help with this issue?

**Comment by volkanceylan** [comment]
Only SqlServer (remote) is supported yet

**Comment by volkanceylan** [comment]
I've updated guide for MySql:

https://volkanceylan.gitbooks.io/serenity-guide/content/mysql.html

There is no code generator support for MySql yet, though

**Comment by Amitloh** [comment]
will you be adding code generator support for MySql anytime this year?
