### ISSUE TITLE
Nested Menu.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#181]
In serenity, Is it possible to have tree like navigation menu?

**Comment by ademc** [comment]
Serenity already has a tree navigation menu ability. You can edit navigationLink line hierarchy module text how you want

[assembly: NavigationLink(7100, "Northwind/Customers", typeof(Northwind.CustomerController), icon: "icon-wallet")]
"Northwind/Customers"
"Northwind/newNode/Customers"
"Northwind/OtherNode/AnotherNode/Customers"
"Northwind/OtherNode/AnotherNode/DifferentNode/Customers"

**Comment by dfaruque** [comment]
@ademc does it work for you?

**Comment by sayuga** [comment]
Did you make sure there was a NavigationMenu parent in place first? The child items also need to be designated as NavigationLink. 

[assembly: NavigationMenu(4000, "Northwind", icon: "icon-star")]
[assembly: NavigationLink(4100, "Northwind/OtherNode/AnotherNode/DifferentNode/Customers", icon: "icon-star")]

**Comment by volkanceylan** [comment]
AdminLTE samples has 3 level menu, more than that should be possible similarly.

**Comment by VictorTomaili** [comment]
Here is working sample
```csharp
[assembly: NavigationMenu(7000, "Northwind", icon: "icon-anchor")]
[assembly: NavigationMenu(7000, "Northwind/x", icon: "icon-anchor")]
[assembly: NavigationMenu(7000, "Northwind/x/y", icon: "icon-anchor")]
[assembly: NavigationLink(7100, "Northwind/x/y/Customers", typeof(Northwind.CustomerController), icon: "icon-wallet")]
```
