### ISSUE TITLE
How to set default MinValue and MaxValue for all DecimalEditor

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1811]
I know about `[DecimalEditor(MinValue = "-999999999.99", MaxValue = "999999999.99")]`
But I want to set it globally.
 
@volkanceylan Here I found that you have set the initial value of MinValue and MaxValue
https://github.com/volkanceylan/Serenity/blob/ccac54404309bdb1317373f80ddb6f4760389b2b/Serenity.Script.UI/Editor/DecimalEditor.cs
```
        public DecimalEditorOptions()
        {
            MinValue = "0.00";
            MaxValue = "999999999999.99";
        }
```
How can I set these values so that the value I provided will be applicable across my full application?
Thanks in advance for your support.

**Comment by volkanceylan** [comment]
You shouldn't change defaults, why change defaults while they are overridden by field settings.

If you have to for some reason i don't understand, write your own DecimalEditor deriving from Serenity.DecimalEditor, override default one with yours.

**Comment by dfaruque** [comment]
Ok. Can I tell serenity to use myDecimalEditor for Decimal fields by default?

**Comment by dfaruque** [comment]
Don't mind. the purpose of these questions are to increase my knowledge about serenity and of course I love it so much.

**Comment by volkanceylan** [comment]
In javascript you can override any class and/or method

e.g.

Serenity.DecimalEditor = MyApp.MyDecimalEditor

**Comment by dfaruque** [comment]
I guess that before. after your suggestion. I am confident a little bit.
Thank you very much.
