### ISSUE TITLE
Change size page export pdf

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1813]
How to change the size of pdf export.

I need to change at 11x17

**Comment by edson** [comment]
If you refer to jsPDF, see how it is handled with options in PdfExportHelper.js and its docs
http://rawgit.com/MrRio/jsPDF/master/docs/

For wkhtmltopdf commands, see http://wkhtmltopdf.org/usage/wkhtmltopdf.txt and ReportController.cs among other files in Common/Reporting/

Best Regards

**Comment by VictorTomaili** [comment]
Please use slack channel for ask questions except bug and feature request related.

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)
