### ISSUE TITLE
Multi Authentication

### ISSUE THREAD

**Issue by omidmolaei** [volkanceylan/Serenity#1814]
hi
I need two side of home. how can create two multi authentication for admin and user?

**Comment by VictorTomaili** [comment]
We always use user panel with admin privilages and menus. all admins also an user. If you need 2 diffrent home page, you can reddirect admin home page with privilage condition on dashboard. 

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)

**Comment by omidmolaei** [comment]
Another question
how can i move side bar menu to top page?

**Comment by abelal83** [comment]
@omidmolaei that's a seperate issue to your title, anyway you should be able to find guide here https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#layout
