### ISSUE TITLE
Different look for Serene theme.

### ISSUE THREAD

**Issue by dkontod** [volkanceylan/Serenity#1815]
Hello.
Is there a different look for serene theme (change fonts, colors, field and forms borders etc)? For example make it seem like MS Access forms?

**Comment by dfaruque** [comment]
As my knowledge; there is no such themes.

Play with less/css.

and if possible share your theme with the community.

**Comment by sayuga** [comment]
There is a small set of themes that are accessible from the right hand menu but that is mostly base color changes that came from the original AdminLTE base. You can edit most all the look using .css and less though plus if you go to Contente> Site folder, you;ll see the site.theme.less currently used. It should be a good starting point

**Comment by brunobola** [comment]
Goto the wiki section and just see several changes you may wan't and how to do them.
