### ISSUE TITLE
add class to slick grid cells

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#1816]
I'd like to add a class to specific slick grid cells, for example, if the value of a cell anywhere on grid is less than 5 it should be green. I've looked at the example of conditional formatting which shows how to format columns and rows but not specific cells. 

is there a method available that will tell me the value of a cell then apply a css class to it?

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ConditionalFormatting

**Comment by abelal83** [comment]
Thanks @estrusco but as said I've seen that example which does column and row level. In either case I've found another example where it's possible to create custom formatter and as as attribute to row.cs which is much preferred.

**Comment by abelal83** [comment]
for anyone who also needs this I accomplished with this code

```
    @Serenity.Decorators.registerFormatter()
    export class WimWinTelRotaOnCallFormatter implements Slick.Formatter {

        format(ctx: Slick.FormatterContext) {

            var onCallPattern = /\*/ig;
            var user: string = ctx.value;
                                    
            if (user.match(onCallPattern)) {
                                
                return "<div class='col-oncall'>" + user + "</div>";
            }

            return user;           
        }
    }
```

all the thanks goes to edson chen

**Comment by JoelLapointe86** [comment]
I was looking for this since monday, thanks !
Here's the link for Edson's post:
https://github.com/volkanceylan/Serenity/wiki/SlickGrid-Formatters
