### ISSUE TITLE
Detail of Master/Detail in different tab

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#1818]
Hi,

I've been trying to get a detail grid to appear on a separate dialog tab. By using the tutorials and examples, I have been able to get the grid to appear, and show correctly. However, when creating a new detail record, the master id is not saved.

Can you give me any hints or point to some code as to why this is and where to set this? I've tried a lot of things without success.

Thanks a lot!

**Comment by karimhyatt** [comment]
Just Seen the Customer/Notes/Orders example and will try to replicate it... typical. After looking and looking, it was only after I posted the issue that I found it.... I will re-open if I have any issues...

**Comment by karimhyatt** [comment]
Hi... Ok, Implemented what I could see of CustomerDialog implementation.

My master rows are in ReportsRow 

I have created a secondary set of dialog/pages until I get this right...

- ReportMaterialityDialog.Template.html
- ReportmaterialityDialog.cs
- ReportMaterialityForm.cs
- ReportMaterialityGrid.ts
- ReportMaterialityIndex.cshtml
- ReportsMaterialityPage.cs

The implementation mirrors CustomerDialog/CustomerOrderDialog/CustomerOrdersGrid in the samples. 

The grid displays and the edits work. So far so good. But adding a new record to the ReportMaterialityGrid omits the ReportId. 

Not sure what I'm missing and a pointer would be helpful....

Thanks!

**Comment by volkanceylan** [comment]
See tutorials for examples, and you have the code.

**Comment by karimhyatt** [comment]
OK Thanks. I have been working through this quite a bit. 

Maybe you can help just a little :} It won't take you long becuase I'm misunderstanding something... just what it is, I have no idea.

So I re-generated the detail classes from scratch.

which are ReportMaterialityListXXX

In the sergen-generated code, the information was generated like this:

ReportMaterialityListRow:
`        [DisplayName("Disclosure"), ForeignKey("[dbo].[GRIDisclosures]", "DisclosureId"), LeftJoin("jDisclosure"), TextualField("DisclosureDisclosureName")]`
`        public Int32? DisclosureId`
`        {`
`            get { return Fields.DisclosureId[this]; }`
`            set { Fields.DisclosureId[this] = value; }`
        }
`

`       [DisplayName("Disclosure Disclosure Name"), Expression("jDisclosure.[DisclosureName]")]`
`        public String DisclosureDisclosureName`
`        {`
`            get { return Fields.DisclosureDisclosureName[this]; }`
`            set { Fields.DisclosureDisclosureName[this] = value; }`
`        }`
`

Then when I add a DisclosureDisclosureName to  ReportMaterialityListColumn it displays correctly. 

If I change the above to DisclosureName (everywhere in the above code), it no longer displays anything in the grid. 

Any reason why?

**Comment by volkanceylan** [comment]
Change it also in columns

**Comment by karimhyatt** [comment]
Yes, I just checked. Although I had changed it in columns, I had not changed the type DOH! Sometimes the obvious  is invisible

**Comment by VR-Architect** [comment]
If you still need help on this let me know. I just got mine working and created a template from the Customers/Orders code you can see here: https://github.com/volkanceylan/Serenity/issues/4231
