### ISSUE TITLE
ScriptBundling broken after upgrade?

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1819]
I upgraded to 2.7.8 -> 2.8.7 this morning following the guide, but ScriptBundling no longer appears to work - it now complains that jQuery isn't found when loading the login page. If I turn it off, it works.
~/Scripts/site/ScriptBundles.json  is still there, didn't change.

Any ideas how I can troubleshoot this? Thanks!

**Comment by volkanceylan** [comment]
I don't think there is a change in script bundling.

**Comment by volkanceylan** [comment]
Check script references in ScriptBundles.json are same with ones when it is disabled and in exact same order.

**Comment by wldkrd1** [comment]
Huh...running under IISExpress, I open up the dynamic BundleLibs.js and it's filled with lines like this:

//
//!!!ERROR: File /Scripts/jquery-3.1.1.js is not found!!!!
//

Everything exists in the project at those locations, so I'm not sure where it's actually looking...

**Comment by wldkrd1** [comment]
I'm able to reproduce the problem with a new Serene project - as soon as I enable ScriptBundling, it can't find the files it needs.

**Comment by volkanceylan** [comment]
Ok i'll have a look

**Comment by volkanceylan** [comment]
Regression bug. Should be resolved in 2.8.8

**Comment by wldkrd1** [comment]
Verified, thank you!
