### ISSUE TITLE
Post to endpoint from form

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#1820]
I need to pass some values from a form to my custom listrequest. I need to pass form values to LoanSearchResultsListRequest. How can I do this? Below is some code I tried.

@using (Html.BeginForm("List", "Services/Reversequest/LoanSearchResults", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
    

    <div class="form-group">
        @Html.LabelFor(m => m.Loan_Skey , new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Loan_Skey , new { @class = "form-control" })
        </div>
    </div>
   
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

////////////////////////Endpoint

[HttpPost]
        public ListResponse<MyRow> List(IDbConnection connection, LoanSearchResultsListRequest  request)
        {
           ListResponse<MyRow>  Rsp = new MyRepository().List(connection, request);
            return Rsp;
        }

**Comment by volkanceylan** [comment]
Don't fix mix MVC helpers with Serenity services

**Comment by dougdsank** [comment]
ok how do I do with serenity service? I have to pass values from the form and refresh the grid. We have stored procedures.

**Comment by dougdsank** [comment]
Any help would be appreciated. I am stuck. Instead of the quickfilters with slick grid I need to create a form and pass in the values.

**Comment by volkanceylan** [comment]
I cant help you with your custom reqs. There are many samples in Serene where we call services from script code, e.g. MyService.List. How you merge it with your reqs is something you handle.

**Comment by dougdsank** [comment]
Should I use Q.Servicecall. I want to return results to Grid. Unfortunately I can't use quick filter in slickgrid.
