### ISSUE TITLE
Introductory information about ASP.NET Core Version

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1821]
Hi all. I've written an introductory post with information about .NET Core version and Sergen.

http://serenity.is/blog/2017/01/18/welcome-to-aspnet-core

Hope it will help you test .NET Core version, though it is still in beta, just like .NET Core itself.

Please try it and let me know how it goes.

> Only Sql Server supported and you need Sql Authentication / Remote Server for OSX / Linux

**Comment by marcobisio** [comment]
Once again, thank you very much for your time and your effort @volkanceylan !

**Comment by Estrusco** [comment]
Thank  you very much @volkanceylan !

**Comment by dfaruque** [comment]
You are really a genius man.

**Comment by felipeenco** [comment]
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1-preview2.1-download.md
This is the version used in the project

**Comment by JohnRanger** [comment]
Congratulation! A great step into the right direction imho.

**Comment by volkanceylan** [comment]
Some things have changed after VS2017, see latest blog post.
