### ISSUE TITLE
.Net Core Migration issue with MySql.

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1822]
When trying to import the database i get the following error: (When using an old serene database its working fine, i can login easily, so the problem is with running migrations for the 1st time)
I Modified line 147,148 in DataMigrations to

>                 SkippedMigrations = false;
>                 //return;
and i get:
> MySql.Data.MySqlClient.MySqlException: Invalid attempt to Read when reader is closed.
> 
>    at MySql.Data.MySqlClient.MySqlDataReader.Throw(Exception ex)
> 
>    at MySql.Data.MySqlClient.MySqlDataReader.Read()
> 
>    at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
> 
>    at FluentMigrator.Runner.MigrationRunner..ctor(IAssemblyCollection assemblies, IRunnerContext runnerContext, IMigrationProcessor processor)
> 
>    at FluentMigrator.Runner.Initialization.TaskExecutor.Initialize()
> 
>    at FluentMigrator.Runner.Initialization.TaskExecutor.Execute()
> 
>    at VIGMA.DataMigrations.RunMigrations(String databaseKey) in ....AspNetCore\Initialization\DataMigrations.cs:line 172

**Comment by chizdamasii** [comment]
At line 172 its:

>  new TaskExecutor(runner)
>                     {
>                         ConnectionString = cs.ConnectionString
>                     }.Execute();

**Comment by volkanceylan** [comment]
Read docs carefully
