### ISSUE TITLE
Reach Field from Relation Multiple Tables

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#1823]
Hello Friends!
Please help me with the following issue: Please see the image.

![relation](https://cloud.githubusercontent.com/assets/24989427/22041922/d4385b10-dcd6-11e6-999e-37de520001cc.png)

I'll need from the table QUOTEDETAILS access the field DESCRIPTION of the BODYWORKS table, the image show the relations between the other tables used in the process.

Could you please help me how can reach the field DESCRIPTION  in red from the table or QUOTEDETAILSROW.CS to use in a Report.cshtml similar to Northwind sample ORDERDETAILREPORT.

Sorry if is a simple question, but i'm newbee and not find the solution in past posts.

Wait your important comments.

Thanks for your help.

Best Regards!

Andres

**Comment by volkanceylan** [comment]
See mapping topic in guide, city country, district etc.

**Comment by VirtualHome** [comment]
Hello, I use a mapping option like this.

`[LeftJoin("cc","Tarifs","cc.[IDtarifa]=T0.[IdTarifa]")]`
   `public sealed class QuoteDetailsRow : Row, IIdRow`
   ` {`
`.....`
`.....`

   `[Expression("cc.[Descripcion]")]`
        `public string Descripción`
        `{`
            `get { return Fields.Descripcion[this]; }`
            `set { Fields.Descripcion[this] = value; }`
        `}`

But when i try to use the field **Descripcion** result of the join in my report, said the following error:

![error](https://cloud.githubusercontent.com/assets/24989427/22073521/71c94c6a-dd9d-11e6-8f2d-5a9baae5d564.png)

How can solve this situation?

Thanks for your help.

Andres

**Comment by VirtualHome** [comment]
Works now with [LeftJoin] attribute on top of the row. Thanks for the contributions.. :)
