### ISSUE TITLE
Errors using InplaceAdd with from multi-select LookupEditor

### ISSUE THREAD

**Issue by nidhiNV** [volkanceylan/Serenity#1824]
I am facing issues using the InplaceAdd function within a LookupEditor where Multiple=true.

For example, take the TopicList field within the StripsRow and add InplaceAdd=true:
[LookupEditor(typeof(TopicRow), Multiple = true, InplaceAdd = true), ClientSide]

The New/Edit button then appears as expected next to the field. If there are one or zero selections, this function works fine. However after selecting a couple items, this feature produces several errors:

If you just click on the Edit button, an error of "Input string was not in a correct format" is shown.
If you select the option "*** No results. Click to define a new one ***, it selects that item and does not produce the New Employee dialog as expected.
This was an issue opened in March 2016. and was closed as well in March 2016 with just incompatibility mentioned as the solution.
Just wondering if there has been any workaround found since then to make these features work?

Thanks

**Comment by edson** [comment]
You can add it manually and customize how it is handled through a Button. See 
https://github.com/volkanceylan/Serenity/issues/829 . Só you choose what behavior it should Have(New, edit, etc). After saving, you then handle it by passing values through custom event to master dialog and decide what it should do to the Field. See https://github.com/volkanceylan/Serenity/issues/1254 for an example on binding events.

Best regards

**Comment by volkanceylan** [comment]
InplaceAdd doesn't support Multiple. What you are looking for is tagging, see Select2 guides for that
