### ISSUE TITLE
How do I change this width?

### ISSUE THREAD

**Issue by euclidesgc** [volkanceylan/Serenity#1825]
How do I change this width and put another editor on the side?
![sem titulo](https://cloud.githubusercontent.com/assets/12780402/22048667/941ca43e-dd15-11e6-9989-5988f7ebd6cc.png)

**Comment by VictorTomaili** [comment]
There is some css basics. Find selector and write css. 

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)

**Comment by volkanceylan** [comment]
See multi column dialog sample.
