### ISSUE TITLE
HardcodedValuesEditor custom matcher

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1828]
Dear guys,
I would like to know if someone here has managed to run a custom matcher on a select2 control: http://select2.github.io/select2/#documentation (matcher option).
I tried to do something like that (in a custom editor):

    public getSelect2Options() {
        var select2Options = super.getSelect2Options();
        select2Options.matcher = (term, text, opt) => {
            console.log('test');
            return true;
        };
        return select2Options;
    }

Seems that such function is not called at all: I'm trying to do that in order to search both by key and value in an editor similar to the HardcodedValuesEditor (basic samples).
I'm asking here because I found many many example around, but I cannot make it work on a Serenity custom editor so I don't know if there some bug here or if the bug it's me!

Thanks for your feedbacks

**Comment by edson** [comment]
Hi @marcobisio . How were holidays?

Maybe it is overridden somewhere. I've also found some quirks when customizing other options like this, but anyway, the matcher would only show you the option values if it was a select dom, but as of 3.5.1, we are only dealing with input fields... So even if it worked, you would still only have the text data...

So, a workaround would be to deal the search with query:

something like this:
```

  public getSelect2Options() {
            var select2Options = super.getSelect2Options();

            select2Options.query = (query: Select2QueryOptions) => {
                var data: Select2Result = { more: false, results: [], context: null };
                
                this.get_items().forEach( (item,index,array) => {
                    if (query.term.length == 0 || item.text.toUpperCase().indexOf(query.term.toUpperCase()) >= 0 || item.id.toUpperCase().indexOf(query.term.toUpperCase()) >= 0) {
                        data.results.push({ id: item.id, text: item.text, disabled: item.disabled });
                    }
                });
                
                query.callback(data);
            }
            
            return select2Options;
        }
```

![image](https://cloud.githubusercontent.com/assets/62490/22066045/2f22731c-dd72-11e6-9470-61201a2378ca.png)


Hope it helps somehow... 

Best Regards

**Comment by marcobisio** [comment]
Hi @edson, fine thanks and yours? :-)

Ahh you're right man: I was on the wrong way at all!

Thank you very much @edson, this approach is working perfectly!
Bye

**Comment by marcobisio** [comment]
Forgot to close ;-)
