### ISSUE TITLE
RetrieveResponse selects unused fields.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#183]
In your northwind category form, there are two fields: Category Name and Description.
When I open an existing category for edit, it retrieve Picture field also. 
It should only select ID, Category Name and Description fields.

**Comment by VictorTomaili** [comment]
what unused fields ? Serenity has Select Level on row properties. try to use MinSelectLevelAttribute for set minimum select level. SelectLevel.Details for dialogs. Explicit is never selected while not explicitly called.

**Comment by volkanceylan** [comment]
Right, add [MinSelectLevel(SelectLevel.Explicit)] if you don't want it to load on retrieve.

**Comment by dfaruque** [comment]
Thanks
