### ISSUE TITLE
Service Endpoint/Response issue

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#1830]
For, some reason my Response is going here 
http://localhost:53512/Services/Loan/LoanSearchResults 
instead of where the grid is
here http://localhost:53512/Loan/LoanSearchResults

how do I redirect response with entities to http://localhost:53512/
![1-18-2017 3-12-24 pm](https://cloud.githubusercontent.com/assets/3937709/22081274/f5f146c6-dd90-11e6-85e3-8ea151356d61.png)
![1-18-2017 3-13-31 pm](https://cloud.githubusercontent.com/assets/3937709/22081275/f5f73c20-dd90-11e6-8361-5fff9582a526.png)

Loan/LoanSearchResults

**Comment by dougdsank** [comment]
This is what im getting back.

![1-18-2017 3-18-06 pm](https://cloud.githubusercontent.com/assets/3937709/22081422/8549bd8a-dd91-
11e6-8bce-dc7fec9f1eb0.png)

**Comment by dougdsank** [comment]
![1-18-2017 3-18-06 pm](https://cloud.githubusercontent.com/assets/3937709/22081446/9dbe5682-dd91-11e6-9cbf-788f14bc9bfb.png)

**Comment by volkanceylan** [comment]
Please have some jQuery/AJAX/ASP.NET MVC guide, learn what an AJAX call, what a service, what a page is.

**Comment by dougdsank** [comment]
Thank you.

**Comment by dougdsank** [comment]
The problem I'm having is with the response returning back to the service not the actual page.

**Comment by volkanceylan** [comment]
Yes, it is doing what it should.
