### ISSUE TITLE
Setting username from Authorization

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1834]
[DisplayName("Assigned"), NotNull, ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jAssigned"), TextualField("AssignedUsername")]
            [LookupEditor(typeof(Administration.Entities.UserRow))]
            public Int32? AssignedId { get { return Fields.AssignedId[this]; } set { Fields.AssignedId[this] = value; } }
            public partial class RowFields { public Int32Field AssignedId; }

______________________________________________________________________________________________________________

In Dialog.ts

this.form.AssignedId.value = Authorization.userDefinition.UserId.toString()

this isnt working

**Comment by volkanceylan** [comment]
First send UserId to client, search for userdefinition and references

**Comment by vinaykulkarni89** [comment]
I have already added UserId to ScriptDefinition
when i check for value of Authorization.userDefinition.UserId.toString() it shows proper Id but it is not assigned to this.form.AssignedId, my question is why it is not assigning value
