### ISSUE TITLE
SQL Query 

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#1839]
Hello Friends!

Please help me with the following issue, when i try to use the next query on the below section.

**Query**

                var m = QuoteRemarksRow.Fields;
                data.Comments = connection.First<QuoteRemarksRow>(q => q
                .SelectTableFields()
                    .From(m)
                    .Select(m.Comentarios));

**Section of code**

 `public object GetData()
     `{
           ` var data = new QuoteDetailsReportData();`

            using (var connection = SqlConnections.NewFor<QuotesRow>())
            {
                var o = QuotesRow.Fields;
                data.Quote = connection.TryById<QuotesRow>(this.IdQuote, q => q
                     .SelectTableFields()
                     .Select(o.TerceroRazonSocial)) ?? new QuotesRow();

                var od = QuoteDetailsRow.Fields;
                data.Details = connection.List<QuoteDetailsRow>(q => q
                    .SelectTableFields()
                    .Select(od.IdTarifaDescripcion)
                    .Select(od.Descripcion)
                    .Select(od.DescripcionVehiculo)
                    .Select(od.DescripcionUnidadServicio)
                    .Select(od.Origen)
                    .Select(od.Destino)
                    .Where(od.IdQuote == this.IdQuote));

                var c = CustomersRow.Fields;
                data.Customer = connection.TryFirst<CustomersRow>(c.IdTercero == Convert.ToInt32(data.Quote.IdTercero))
                    ?? new CustomersRow();

                var m = QuoteRemarksRow.Fields;
                data.Comments = connection.First<QuoteRemarksRow>(q => q
                .SelectTableFields()
                    .From(m)
                    .Select(m.Comentarios));
            }

            return data;
        }

When i try to use the result of the query in my report cshtml with the model, the result is the following error.

![error](https://cloud.githubusercontent.com/assets/24989427/22129852/8375414c-de76-11e6-84f1-d8d4c83ea681.png)

Thanks for all your important comments, to solve this issue, or how build the query correctly to use in my model.

Best Regards!

Andres

**Comment by edson** [comment]
If Comentarios is not an expression, remove it. selecttablefields already builds with those.

Best Regards

**Comment by uwascan** [comment]
Try
```
var m = QuoteRemarksRow.Fields.As("qr");
            data.Comments = connection.First<QuoteRemarksRow>(q => q
            .SelectTableFields()
                .From(m)
                .Select(m.Comentarios));
```

**Comment by volkanceylan** [comment]
You shouldn't add From. Connection extensions already adds " from" to q parameter you get.

**Comment by VirtualHome** [comment]
Thanks to everyone for your help!!! :)
