### ISSUE TITLE
LookupEditor but filtering out/off one specific result

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#184]
Hi all,

I have a table which serves as the Lookup (via LookupScript, LookupEditor) for the selectable filling (dropdown) of a field in a Dialog.

Within this table, I have a "Special" record (ID 0) which serves as the virtual placeholder for "not yet selected". 

Now I want to filter this one record (with ID 0) off within the Dropdown so the user cannot select it/see it.

I have tried with FilterField and FilterValue in the xyzRow.cs field declaration but had no luck to filter off just this one record.

How would I do this?

Thanks for your Support and

with Kind regards,

John

P.S: environment = Serenity 1.9.7

**Comment by volkanceylan** [comment]
Hi John,

I recommend not to use such empty values in database but anyway if you have to, you need to filter it on script side, or in lookup definition server side.

For script side:

```cs
using System.Linq;
...
    [Editor]
    public class MyXYZEditor : LookupEditorBase<LookupEditorOptions, XYZRow>
    {
        public MyXYZEditor(jQueryObject hidden, LookupEditorOptionsopt)
            : base(select, opt)
        {
        }
    }

    protected override IEnumerable<XYZRow> GetItems(Lookup<XYZRow> lookup)
    {
          return lookup.Where(x => x.XyzID != 0);
    }

```

Or at server side, remove lookupscript attribute from row and define a custom one:

    [LookupScript("MyModule.XYZ")]
    public class XYZLookup : RowLookupScript<XYZRow>
    {
        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);

            query.Where(XYZRow.Fields.XyzID != 0);
        }
    }

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your extremely fast reply :-)

I want to implement this on the client side (because I Need all records of that table at another place) and have tried to put this into xyzDialog.cs. 

Currently I have the Problem that it does not recognize LookupEditorOptionsopt. (Is this something which I have to declare somewhere else or is there a typo in your example?)

Hint: I have tried to put a comma between LookupEditorOptions and opt (like this: LookupEditorOptions,opt) but this was also not accepted by VS 2015.

Then also the : base is complaining - telling that "select" and "opt" are not known in the current context. --> Do I Need a Special "using" in order that select and opt are working?

Forgive me my low knowledge of Serenity, C# and where to put such things the best.

Questions:

- Where should I put the client-side code? in a separate class file? In xyzdialog.cs (I would like to put it there as it has to do with how the Dialog is displayed)
- What about the LookupEditorOptionsopt, select and opt Errors?

Thanks again for your Support 

and with Kind regards,

John

**Comment by volkanceylan** [comment]
LookupEditorOptions opt actually, and replace select with hidden, typo, put it next to your dialog, build and transform templates, than you'll have XYZEditor

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks again for the corrections. It works now perfect :-)

In your example above, the protected override IEnumerable is outside of the class MyXYZEditor. I have moved it inside the class. --> Maybe you could modify your example for future reference.

For other Readers: 

In the abcRow.cs (the row file on which my Dialog is based) I have added the following "property" to the corresponding field definition: 
**[ClientTypeEditor(LookupKey = "Stammdaten.Client_Type")].**
public Int32? Client_Type_ID
        {
            get { return Fields.Client_Type_ID[this]; }
            set { Fields.Client_Type_ID[this] = value; }
        }

The Stammdaten.Client_Type is the Name defined in [LookupScript("Stammdaten.Client_Type") in the xyzRow.cs file.

Thanks again goes to JaiQ for very professional and kind help.

With Kind regards,

John
