### ISSUE TITLE
Converting a typical serenity application to SPA (Single Page Application).

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1840]
For some reason, I want to convert a serenity application to SPA.
So before I started, I want some guidance/suggestion from those who has already walked to this way.

@volkanceylan  Is there something special in this case? I mean If I convert to SPA somehow, Is there anything that may lead to misbehave or arise memory leakage or some other issues what I should taking care of.

Thanks is advance.

**Comment by volkanceylan** [comment]
I don't know, didn't try this

**Comment by dfaruque** [comment]
Thanks. 
Let me give a try. :)

**Comment by dfaruque** [comment]
Keep this issue open for some time. 
someone might help somehow.

**Comment by john20xdoe** [comment]
Haven't tried this with Serene, but I had attempted an SPA in an Angular project once.

I think, a typical Serenity Page (XXXPage) with the Grid and Dialog can be construed as an SPA, (if you disregard the existence of any other modules. =) )

Having only one page as a sort of homepage and calling multiple dialogs from different modules without leaving the page is SPA behavior.

You may need to create different Widget elements to modify the page appearance.

Just my two cents. =)

**Comment by dfaruque** [comment]
Hello,
I am trying this now and facing a little issue.

When I Initialize a grid withing a div then it works fine. but when I initialize another grid using the same div it says 
"The element already has widget 'XXX_someModule_SomeGrid'!"
How can I destroy the previous one.

Thanks

**Comment by volkanceylan** [comment]
someGrid.destroy()

**Comment by dfaruque** [comment]
Ok. found that.

**Comment by dfaruque** [comment]
I think It has been successfully converted with a little effort by using the following code
```
    window.onhashchange = (ev) => {
        let newURL = ev.newURL.split('#');

        if (newURL.length > 0) {
            let hash = newURL[1];
            let hash2 = hash.split('/');
            let moduleName = hash2[0];
            let gridName = hash2[1] + 'Grid';

            let gridContainer = $('#GridDiv');

            if (g_currentGrid && g_currentGrid.destroy) g_currentGrid.destroy();
            g_currentGrid = new SereneXamarin[moduleName][gridName](gridContainer);

            Q.initFullHeightGridPage(gridContainer);

        }
    };
```

And changing the NavigationItems like the following
`[assembly: NavigationLink(9000, "Administration/User Management", "#Administration/User", PermissionKeys.Security, icon: "icon-people")]`

Now, the issue arises at second time call to the `Q.initFullHeightGridPage(gridContainer);` function
though the functionality of the application seems ok. but the layout is broken (grid is displayed half-paged)

In the browser console I have

![image](https://cloud.githubusercontent.com/assets/16621563/22175902/e5beeef8-e028-11e6-84cf-7c74721b86bf.png)

**Comment by dfaruque** [comment]
If somebody give it a try, this might be helpful  https://github.com/dfaruque/SereneXamarin

**Comment by dfaruque** [comment]
I have temporarily fixed the layout issue by doing the following
In Serenity.Script.UI.js
replacing
at Line 5177: ` if (!this.element.is(':visible')) {`
with : ` if (this.element && !this.element.is(':visible')) {`

And 
at Line 5184: `if (this.element.hasClass('responsive-height')) {`
with: `if (this.element && this.element.hasClass('responsive-height')) {`

@volkanceylan  would you please incorporate these little change to Serenity.Script.UI.js?
Or Give me a direction to make these changes permanent.

**Comment by volkanceylan** [comment]
Try Serenity.Script.UI.js from latest commit

**Comment by volkanceylan** [comment]
Also Serenity.CoreLib.js

**Comment by dfaruque** [comment]
Thank you very much.
