### ISSUE TITLE
Wiki Lookup Section

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1841]
Hi all!

I have started to write the lookup section of wiki

https://github.com/volkanceylan/Serenity/wiki/Lookups

Anyone can write a part relating to LookupFilteringAttribute?

Soon I will continue writing the section on customizing lookup, even inserting the old issues.

Enjoy :)

**Comment by edson** [comment]
Hi, @Estrusco . I will try to write it later, if no one else do... :-)

Best Regards

**Comment by Estrusco** [comment]
I see you have done, thank you @edson !
