### ISSUE TITLE
Grid calling List

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#1842]
Is there a way to not have the grid call the service/List. I am calling the Service/List with a Ajax call and return json. I want to load the grid with that json response. Thanks in advance.

**Comment by dougdsank** [comment]
To clarify I want to post values from a form and return JSON. The problem is the grid/ list service is automatically triggered when the grid loads. Any suggestions?

**Comment by volkanceylan** [comment]
getGridCanLoad method, see GridEditorBase
