### ISSUE TITLE
Implement TreeView

### ISSUE THREAD

**Issue by Daffyydd** [volkanceylan/Serenity#1843]
Thanks for this nice template.

I want to implement tree Grid for a chart of  accounts.

I have followed  both DucThanhNguyen (#1394) and Sample Tree Grid, however, the Grid is not displaying any records.

I have checked on the console and no error is showing.

namespace SaccoManager.Master {

    @Serenity.Decorators.registerClass()
    export class AccountsGrid extends Serenity.EntityGrid<AccountsRow, any> {
        protected getColumnsKey() { return 'Master.Accounts'; }
        protected getDialogType() { return AccountsDialog; }
        protected getIdProperty() { return AccountsRow.idProperty; }
        protected getLocalTextPrefix() { return AccountsRow.localTextPrefix; }
        protected getService() { return AccountsService.baseUrl; }

        private treeMixin: Serenity.TreeGridMixin<Master.AccountsRow>;

        constructor(container: JQuery) {
            super(container);

                this.treeMixin = new Serenity.TreeGridMixin({
                grid: this,
                initialCollapse: () => true,
                toggleField: AccountsRow.Fields.AccountNumber,
                getParentId: x => x.ParentId
            });
        }       
    }
}
What am I not doing here.

**Comment by Daffyydd** [comment]
updated the template and now working ok

**Comment by Mohamed-Ali-Salim** [comment]
hey Daffyydd
can you help me to do Chart of account ?
i'm new in serenity .
Table design is (ID ,Code,Name,ParentID )
ParentID is related with ID for the same table ?
can you help me and let me see your final page ?
thanks
