### ISSUE TITLE
Error calling Delete Service

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1844]
All I am calling the delete service with Ajax and for some reason my entityid is null.  Any ideas I know its simple.  Thanks

<script type="text/javascript">
    function Dismiss(id) {
        $.ajax({
            url: "Services/Alerts/UserAlerts/Delete",
            data: "{EntityId :"+ id"}",
            dataType: "json",
            type: "Post",
            success: function (data) {
                alert(data);
            },
            error: function (x, y, z) {
                alert(x.responseText + "  " + x.status);
            }
        });
        }
</script>

**Comment by VictorTomaili** [comment]
try use object instead json string.  Also check your id is correct inside Dismiss method. 
```
data: {
EntityId: id
}
```
