### ISSUE TITLE
Cannot resolve the collation conflict between "Turkish_CI_AS" and "SQL_Latin1_General_CP1254_CI_AS" in the equal to operation.

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#1845]
Merhaba, UserRow'a aşağıdaki kodla ayrı bir database ile ilişkilendiriyorum.Fakat Userform'u açtığımda
"Cannot resolve the collation conflict between "Turkish_CI_AS" and "SQL_Latin1_General_CP1254_CI_AS" in the equal to operation." hatası alıyorum

Bu soruna rastlayan varmı ? nasıl çözebilirim sizce?

 [DisplayName("Email"), ForeignKey("CENTER_TEST.DBO.BD_KULLANICILAR", "EMAIL"), LeftJoin("jBdKullanicilar")]
        [LookupEditor(typeof(Center_test.Entities.BdKullanicilarRow))]
        public String Email
        {
            get { return Fields.Email[this]; }
            set { Fields.Email[this] = value; }
        }

**Comment by volkanceylan** [comment]
SQL server ınızda database ler arasında collation farkı var, bu Serenity ile ilgili bir durum değil

**Comment by volkanturk** [comment]
Teşekkür ederim
