### ISSUE TITLE
ServerTyping not being created for Enum

### ISSUE THREAD

**Issue by DGoertzen** [volkanceylan/Serenity#1846]
Hello,

I have defined a new enum and the corresponding typescript file does not appear to be generated.

I have defined the enum as follows:

```
using Serenity.ComponentModel;
using System.ComponentModel;

namespace Demo.Time
{
    [EnumKey("Time.SummaryReport")]
    public enum SummaryReport
    {
        [Description("Weekly")]
        Weekly = 1,
        [Description("Monthly")]
        Monthly = 2,
        [Description("Pay Period")]
        PayPeriod = 3,
        [Description("Overtime Period")]
        OvertimePeriod = 4,
    }
}

```
I run "Transform all T4 templates" and expected the enum to show up in a typescript file in Modules\Common\Imports\ServerTypings so I can make use of it in the typescript files.  However, it does not.

I reviewed the example for Northwind.OrderShippingState provided, which works fine.  I can modify that enum, and the typescript file in Modules\Common\Imports\ServerTypings is updated as expected.  However, I am unable to determine why the typescript file is not being generated for the enum I have created.

What am I overlooking?

Thanks!

**Comment by volkanceylan** [comment]
Unless you reference that enum somewhere it won't be generated.

**Comment by DGoertzen** [comment]
Thanks for the quick response.  I do reference the enum in a Row.cs file, and that works fine.  In the .ts file where I want to use it, I have the following code

```
namespace KardiumHR.Time {

    @Serenity.Decorators.registerEditor()
    export class PeriodEditor extends Serenity.Select2Editor<any, any> {

        constructor(container: JQuery) {
            super(container, null);
     
            this.addOption(Time.SummaryReport.Weekly.ToString(), Time.SummaryReport.Weekly.GetText());
            this.addOption(Time.SummaryReport.Monthly.ToString(), Time.SummaryReport.Monthly.GetText());
            this.addOption(Time.SummaryReport.PayPeriod.ToString(), Time.SummaryReport.PayPeriod.GetText());
            this.addOption(Time.SummaryReport.OvertimePeriod.ToString(), Time.SummaryReport.OvertimePeriod.GetText());
            this.options.allowClear = false;  
            this.value = "1";
        }

        public getSelect2Options() {
            var opt = super.getSelect2Options();
            opt.allowClear = false;            
            return opt;
        }
    }
}
```
I followed the format of usage of "Northwind.OrderShippingState.NotShipped.toString()" in the sample file "InitialValuesForQuickFilters.ts".  Sorry for this minor question.  I am sure it something rather embarrassing on my part.   Thanks for the help.

**Comment by DGoertzen** [comment]
Hello,

I found that I can get the enum reference to be generated by including a the following function as per the example in the serenity guide.
```
        public SummaryReport? SummaryReportRow
        {
            get { return (SummaryReport?)Fields.SummaryReportRow[this]; }
            set { Fields.SummaryReportRow[this] = (Int32?)value; }
        }
```
Prior to adding this code, I was only making a call in the Rowfields constructor as follows (just for test purposes)

`this[0].PropertyName = SummaryReport.Monthly.ToString();`

This line of code was not sufficient to cause the enum reference to be generated.

Is there a note somewhere that clarifies what needs to be done to get a typescript file generated for the enum?  Do I have to declare a function as per above, or is there some other way?  

Of course, it is not a problem to include the function, but I prefer not to have extra code for which the purpose is not obvious.

As I've stated before, it is an amazing framwork that you have created.  Thanks!

**Comment by DGoertzen** [comment]
Ok. I think I figured it out now.  I only need to add "ScriptInclude" to the enum.   If I change my enum declaration to the code below, all works great and I don't need the  public SummaryReport? SummaryReportRow function.

```
using Serenity.ComponentModel;
using System.ComponentModel;

namespace KardiumHR.Time
{
    [EnumKey("Time.SummaryReport"), ScriptInclude]
    public enum SummaryReport
    {
        [Description("Weekly")]
        Weekly = 1,
        [Description("Monthly")]
        Monthly = 2,
        [Description("Pay Period (Hourly)")]
        PayPeriodHourly = 3,
        [Description("Pay Period (Salary)")]
        PayPeriodSalary = 4,
        [Description("Overtime Period")]
        OvertimePeriod = 5
    }
}
```

**Comment by volkanceylan** [comment]
If you use enum in some row, service or form, you dont need ScriptInclude.

**Comment by Shraddha996** [comment]
hello, @volkanceylan how to use enum in form??
