### ISSUE TITLE
Bug after All T4 Templates

### ISSUE THREAD

**Issue by alitarkian** [volkanceylan/Serenity#1847]
Hi,
I Create new Serenity Project ASP.Net MVC
and after that rebuild and run everything is good.
so when Click All T4 Templates get Error like Picture 1 

![error1](https://cloud.githubusercontent.com/assets/19204100/22183034/4ed6689e-e0c9-11e6-9cf1-64111e5d40ef.jpg)

and when run project show this

![error2](https://cloud.githubusercontent.com/assets/19204100/22183043/71b62f7a-e0c9-11e6-9abe-ee329ac5788b.jpg)

help me please?!

**Comment by volkanceylan** [comment]
Do you what is the TSC version on top of your console window?
