### ISSUE TITLE
Dialog Grids Only Showing One Result?

### ISSUE THREAD

**Issue by JoshDiDuca** [volkanceylan/Serenity#1849]
Hi Volkanceylan, 

I appreciate your time and project but it seems we're having a problem with dialog grids not showing all results.

Basically we have a Clients dialog with a Contacts tab, when you add a contact through the New Contact button, it inserts it into the database with the correct ClientID field, refreshing the grid doesn't seem to do anything. 

It seems to show only one result at all, I've even tried copying the exact same row twice in the database but it only shows one of them.
We're using Serenity 2.6.0.0 if that helps, could be an issue that would be fixed via an update.

Thanks.

**Comment by volkanceylan** [comment]
If it is working in Northwind Customer and other simiar dialogs, then it should be an error in your code.

**Comment by volkanceylan** [comment]
Do you have code that calls arrange that binds to tab index change in your Dialog.ts?

**Comment by VictorTomaili** [comment]
Please use slack channel for ask questions.

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)

**Comment by JoshDiDuca** [comment]
Hi Volkanceylan,

Thanks for the fast replies, I'll take a look into our code now but other than the ClientID variable and setting the equality in the Grid file I haven't made any changes. The dialog is still the same as what sergen generated.

Thanks Victor, I've joined the Slack too.

**Comment by volkanceylan** [comment]
So you didn't add that code, you should follow the tutorial.

**Comment by JoshDiDuca** [comment]
Hi there, sorry I didn't quite understand what you meant, I do in fact have the code that calls the arrange: 

"this.contactsGrid = new ClientCompanyContactGrid(this.byId("ContactsGrid"));
this.tabs.on('tabsactivate', (e, i) => {
this.arrange();
});"

I've read through and completed every step in the following tutorial several times, 
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/listing_movies_in_person_dialog.html
as soon as I add the equality filter it only shows one row.

You might find it a little easier with some code, 
here's my ClientDialog: http://pastebin.com/GmE4H175
and here's my ContactGrid: http://pastebin.com/EYQVTDKa

Thanks for everything so far, I appreciate it.

**Comment by JoshDiDuca** [comment]
Managed to fix it and I don't even know how, thank you for your time Volkanceylan.
My team will be throwing a donation your way once we've finished this project, we're really struggling for documentation on serenity though, that would be our biggest recommendation.

Thanks again.
