### ISSUE TITLE
Formatting code in this GitHub issue textboxes

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#185]
Hi JaiQ,

I have one question regarding the very beautifully formated code in your answers: 

How do I mark it up so that it Looks similar like the one you have? (I have read the Basics about Github formatting (e.g. the 3 backticks for code) but mine always Looks relatively terrible and sometimes github writes very big letters and I can't get them back to normal)...

Is there a simple way to let it auto-Format like yours?

With Kind regards, 

John

**Comment by volkanceylan** [comment]
I just use 3 backticks followed by "cs" nothing special. Then end with 3 backticks again.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your feedback. The "cs" must be it.

Have a nice evening

and with Kind regards,

John

**Comment by VictorTomaili** [comment]
Bottom of comment area has a link like [Styling with Markdown is supported](https://guides.github.com/features/mastering-markdown/)
