### ISSUE TITLE
Serenity and Informix DB

### ISSUE THREAD

**Issue by gotenks** [volkanceylan/Serenity#1850]
I recently discovered Serenity and I decided to give it a try to run with Informix DB ( we use Informix DB - old version 7.23 - to run legacy apps ). As you might expect, I encountered a lot of problems :). For now, I have GodeGenerator working with IFX, but unfortunately, I am not able to force Serenity itself, to do the same. The current problem I have, is the fact, that Informix does not support "[" and "]" in field names, but it seems, Serenity Query helpers (SqlHelpers) use "hard-coded" Bracket implementation (if I am not missing something of course). Is this intentional ?

If so, what dialects implementations are for (except for loading the proper driver) ?

I'd expect them to hide different DB differiences, like the one mentioned above :)

Please, advice what could I do to go a step forward :)

**Comment by volkanceylan** [comment]
Serenity already supports 6 databases, have a look in the code and write your own dialect.

**Comment by gotenks** [comment]
Arrrgh ... I have finally found where Serenity seriously fails to work with Informix DB. 
Serenity only handles named query parameters, but Informix, on the other side, only 
handles positional parameters.
I would have to seriously rewrite Serenity.Data to get it working with Informix DB ... pitty ... :(

Thanks for assistance
