### ISSUE TITLE
Save changes of the entity a one tab

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1851]
As I can save the changes an one tab of an entity each time the user caambie.

Example:

State
---Active
---Inactive
---Canceled

I want to save a record when the user makes the change of one of these options.

Sorry but I'm very new to this.

**Comment by joheric** [comment]
With date and user

**Comment by volkanceylan** [comment]
You should override BeforeSave method of your SaveHandler, check (IsCreate || Old.State != Row.State) then set Row.WhoMadeChange = Convert.ToInt32(Authorization.UserId)

**Comment by VictorTomaili** [comment]
Please use slack channel for ask questions.

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)
