### ISSUE TITLE
Rowindex

### ISSUE THREAD

**Issue by KhatamiMasoud** [volkanceylan/Serenity#1852]
I want to share my solution for row number:
In Endpoint:
        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            ListResponse<MyRow> rt;
            rt= new MyRepository().List(connection, request);
            Int32 II;
            II = 1;
            rt.Entities.ForEach(a => { a.RowIndex = rt.Skip + II++ ; });
            return rt;
        }

**Comment by dfaruque** [comment]
Please format code by ``` ```

In Endpoint:
```
public ListResponse List(IDbConnection connection, ListRequest request)
{
ListResponse rt;
rt= new MyRepository().List(connection, request);
Int32 II;
II = 1;
rt.Entities.ForEach(a => { a.RowIndex = rt.Skip + II++ ; });
return rt;
}
```

**Comment by VictorTomaili** [comment]
by `` ``` `` tags? @dfaruque
