### ISSUE TITLE
grid lines in slick grid

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1853]
banging my head to find how to have vertical lines to show separation of columns in a grid.

i think this should be very easy by modifying some css.

but i am unable to locate the place.

kindly help.

**Comment by VictorTomaili** [comment]
override css for slickrow

![image](https://cloud.githubusercontent.com/assets/2023440/22246497/4421273a-e246-11e6-841e-95555bc4feb7.png)

**Comment by VictorTomaili** [comment]
Ohh sorry you can override slickcell 

![image](https://cloud.githubusercontent.com/assets/2023440/22246598/9c1361b0-e246-11e6-8b4d-8ba04073403a.png)

**Comment by mrajalko** [comment]
thanks @VictorTomaili , actually i am trying to have vertical lines for visible separation of columns, let me try with border-right-color etc.

thanks again for your help.

**Comment by VictorTomaili** [comment]
same css class 

![image](https://cloud.githubusercontent.com/assets/2023440/22250595/8e329d74-e258-11e6-9558-a217b8df4e64.png)

**Comment by mrajalko** [comment]
thanks a lot @VictorTomaili 
.
worked.
