### ISSUE TITLE
LookupEditor and AddressEditor conflicting. 

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1854]
So, I have a AddressEditor I created emulating the CustomerEditor from Northwind. The editor works fine on it's own. The problem is that I need that field to allow for inplaceAdd() and to cascade from another field. 

If I try to do  [AddressEditor(InplaceAdd = true, CascadeFrom = "CustomerId")], it does nothing. 

If instead I add [LookupEditor(typeof(AddressRow), InplaceAdd = true, CascadeFrom = "CustomerId", CascadeField ="CustomerId"), AddressEditor], Only the InplaceAdd button appears to work (no cascade) but none of the entries in the Address table are displayed. If I attempt to enter a new entry using the inplace add, the back end shows me that the entry is in the table without the CustomerId but it still doesn't display in the Dialog Field. 

If I do the [LookupEditor(typeof(AddressRow), InplaceAdd = true, CascadeFrom = "CustomerId", CascadeField ="CustomerId")] without the editor, the cascade works and the inplace add appear to work but the entry on the Address Table does NOT capture the CustomerId. Additionally, the changeSelect2 event is not being triggered on the field (I have another piece of code that triggered on selection).

If I have the [AddressEditor] on it's own, the Address displays properly on form but then I don't get the InplaceAdd nor Cascade that I need. 

Here is my editor: 

***
namespace MatrixOne.Default {

    @Serenity.Decorators.registerEditor()
    export class AddressEditor extends Serenity.LookupEditorBase<AddressRow, any> {

        constructor(hidden: JQuery) {
            super(hidden);
        }

        protected getLookupKey() {
            return AddressRow.lookupKey;
        }

        protected getItemText(item, lookup) {

            var thisItem = super.getItemText(item, lookup);
            var otherItem = item.Room;

            var result = "Floor: " + thisItem + ' - [Room: ' + otherItem + ']';

            return result;
        }

    };
}
***
The xyzRow.cs that I'm using this on has: 

[DisplayName("Address Info"), Column("AddressLogId"), NotNull]
        [ForeignKey("Address", "AddressId"), LeftJoin("adl"), LookupInclude]
        [LookupEditor(typeof(AddressRow), InplaceAdd = true, CascadeFrom = "CustomerId", CascadeField ="CustomerId")]//, AddressEditor]
        public Int32? AddressId
        {
            get { return Fields.AddressId[this]; }
            set { Fields.AddressId[this] = value; }
        }

***

the AddressRow.cs has: 

 [LookupScript("Default.Address")]
    public sealed class AddressRow : Row, IIdRow, INameRow
    {
//....///

        [DisplayName("CustomerId"), Size(255), LookupInclude]
        [ForeignKey("Customer", "CustomerId")]
        public Int32? CustomerId
        {
            get { return Fields.CustomerId[this]; }
            set { Fields.CustomerId[this] = value; }
        }

//....//
}

I'm racking my brain  on this but I know i'm just missing something stupid. Help please.....

**Comment by volkanceylan** [comment]
You constructor must accept a options deriving from LookupEditorOptions and pass that to base constructor

**Comment by sayuga** [comment]
ahh, that's where my mistake was. I was reading up on TypeScript constructors and I kept trying to pass the wrong reference to the constructor. 

Excellent, that piece is working properly now. Thank you for the help.

**Comment by sayuga** [comment]
Ok, so I stand corrected. I am still having an issue with my custom editor. 

Here is the custom editor: 

namespace MatrixOne.Default {

    @Serenity.Decorators.registerEditor()
    export class AddressEditor<row,AddressEditorOptions> extends Serenity.LookupEditorBase<AddressLogRow, any> {


        constructor(hidden: JQuery, opt: Serenity.LookupEditorOptions) {
            super(hidden, opt);                                 
                        
        }

        protected getLookupKey() {
            return AddressLogRow.lookupKey;
        }

        protected getItemText(item, lookup) {

            var thisItem = super.getItemText(item, lookup);
            var otherItem = item.Room;

            var result = "Floor: " + thisItem + ' - [Room: ' + otherItem + ']';

            return result;
        }                
        
    }
                

};


Per my understanding, I needed to pass options through the constructor. This should give me access to the same options the standard LookupEditor should have. That appears to work if I use inplaceadd or cascade separately but if I try use them together, even though it calls the cascaded dialog, it does not seem to capture the Customer Id and pass it to the AddressLog Table. I've gone up and down the cascade setup and I don't believe I've missed anything. 

- Checked syntax. no typos
- IncludeLookup is in place for the CustomerId Field on the AddressLog Table as well as the CustomerId and AddressLogId of the table I'm using the cascade on. 
- AddressLog Table has a CustomerId Field with [Foreignkey("Customer", "CustomerId")] 
-AddressLogForm has the CustomerId Field with a [Hidden] attribute
- All tables have LookupScripts
- I'm calling the editor as         [AddressEditor(CascadeFrom = "CustomerId", CascadeField = "CustomerId", InplaceAdd = true)]
- Made sure there is no second editor in place for that field anywhere else. 

The only difference I see is that I'm using a custom editor but I'm not certain why it wouldn't work with the options enabled in the constructor. I'm going to make a fresh project and rebuild the cascade sample then try adding the custom editor, to see if I notice anything different.

**Comment by sayuga** [comment]
Ok, I just recreated the sample from the manual without using a custom editor and I'm still having the same issue. Might it be a bug somewhere? Could someone test having a cascade with and inplaceadd and let me know if they are also having the same issue? I don't have any errors on the console nor the build so I'm a bit at a loss why the Id for the cascade is not being passed through the inplaceadd.

**Comment by sayuga** [comment]
Got some pointers on the Slack Channel so I'll be reworking my approach on this. Turns out it's not a available feature....which would be why it doesnt work. I'll be working something out so I'll close this.
