### ISSUE TITLE
Excel Export Error

### ISSUE THREAD

**Issue by klangley-toyo** [volkanceylan/Serenity#1855]
I had the excel export button working and now it has stopped working.

When I click on the excel export a blank window opens for .../services/Opportunities/Projects/ListExcel
On the original grid window I have an open or save dialog for ListExcel and it is only 2.66 KB

Here is the endpoint code
 public FileContentResult ListExcel(IDbConnection connection, ListRequest request)
        {
          

                var data = List(connection, request).Entities;
                var report = new DynamicDataReport(data, request.IncludeColumns, typeof(Columns.ProjectsColumns));
                var bytes = new ReportRepository().Render(report);
                return ExcelContentResult.Create(bytes, "ProjectList_" +
                    DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".xlsx");
           
        }
Here is the grid code. The PDF works
 protected getButtons() {
            var buttons = super.getButtons();

            buttons.push(SalesManager.Common.ExcelExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: SalesManager.Opportunities.ProjectsService.baseUrl + '/ListExcel',
                separator: true
            }));

            buttons.push(SalesManager.Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));

            return buttons;
        }

**Comment by sayuga** [comment]
What does the console say?

**Comment by klangley-toyo** [comment]
I actually just solved this, it was one of the columns in the grid causing the export to fail. I removed the column and the export works now. Thanks
