### ISSUE TITLE
Default Values through Tab Form

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1857]
I have a form, with defualt values set it in xyzMyDialogGrid.ts 

`  
protected addButtonClick() {
                 this.editItem(<Policies.SinisterRow>{
                UserId: Authorization.userDefinition.UserId,
                Date: Q.formatDate(new Date(), 'yyyy-MM-dd'),
            });

`      

It's work just fine. But when i load this dialog, into a tab, The default values do not appear.

Can anyone point me in the right direction? Look in the issues but I did not find anything to help me

**Comment by javaman63** [comment]
I am completely unaware of the DefaultValue on the Form

Sorry

I close this now

**Comment by jmace** [comment]
@javaman63 , do you care to comment on how you used DefaultValue to set the userID in a field?

**Comment by javaman63** [comment]
@jmace hi there!. The DefaultValue is to set for example a DATE. If you want to set the userID in a field, you have to go to the xyzDialog or xyzGrid and set the value there

UserId: Authorization.userDefinition.UserId

**Comment by jmace** [comment]
@javaman63 , thanks. I've used DefaultValue in that way several times, but thought you had somehow made it work for Authorization.
