### ISSUE TITLE
Updating Projects 

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#1858]
I always have questioned  my self should we or  we shouldn’t update other references in the project 
I know we shouldn’t update select2 for compatibility issues , but what about other libraries fluent migrator and other stuff  and is using nuggets update would update everything 

![capture](https://cloud.githubusercontent.com/assets/728937/22321640/1ef68a68-e39f-11e6-8aa4-abf594b67527.PNG)

**Comment by volkanceylan** [comment]
You can update anything other than Select2.js, but if you update them to a newer version than the one in latest Serene template, you'll be using an untested version, and any problems you'll have will be in your hands.

**Comment by volkanceylan** [comment]
Check here to see what Serene latest uses:
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/packages.config

**Comment by zerodev** [comment]
thanks my friend ,
 i have updated project today and am getting error  with less 
Error	6	The command ""[...]\tools\node\lessc.cmd" "[...]\Content\site\site.less" > "[...]\Content\site\site.css"" exited with code 3.[...].Web.csproj	2099	5

**Comment by volkanceylan** [comment]
See output window. I don't understand how you expect me to help you with some exit code.

**Comment by zerodev** [comment]
fownd why , for some reason when updating the code generator its removing everything uder tools folder 

is it from the updated soe 
------ Updating...Serenity.CodeGenerator 2.9.0 -------
Installing 'Serenity.CodeGenerator 2.9.0'.
Added file 'Readme.CodeGenerator.txt' to folder 'Serenity.CodeGenerator.2.9.0\content'.
Added file 'dotnet-sergen.dll' to folder 'Serenity.CodeGenerator.2.9.0\lib\netcoreapp1.0'.
Added file 'dotnet-sergen.runtimeconfig.json' to folder 'Serenity.CodeGenerator.2.9.0\lib\netcoreapp1.0'.
Added file 'Newtonsoft.Json.dll' to folder 'Serenity.CodeGenerator.2.9.0\tools\net45'.
Added file 'RazorGenerator.Templating.dll' to folder 'Serenity.CodeGenerator.2.9.0\tools\net45'.
Added file 'Serenity.Core.dll' to folder 'Serenity.CodeGenerator.2.9.0\tools\net45'.
Added file 'Serenity.Data.dll' to folder 'Serenity.CodeGenerator.2.9.0\tools\net45'.
Added file 'Serenity.Data.Entity.dll' to folder 'Serenity.CodeGenerator.2.9.0\tools\net45'.
Added file 'sergen.exe' to folder 'Serenity.CodeGenerator.2.9.0\tools\net45'.
Added file 'Serenity.CodeGenerator.2.9.0.nupkg' to folder 'Serenity.CodeGenerator.2.9.0'.
Successfully installed 'Serenity.CodeGenerator 2.9.0'.
Looking for updates for 'Serenity.CodeGenerator'...
Updating 'Serenity.CodeGenerator' from version '2.7.2' to '2.9.0' in project 'ABPnPE.Web'.
Removing 'Serenity.CodeGenerator 2.7.2' from ABPnPE.Web.
Removed file 'Readme.CodeGenerator.txt'
Added file 'packages.config'.
Successfully removed 'Serenity.CodeGenerator 2.7.2' from ABPnPE.Web.
Removing 'Serenity.Web.Tooling 2.6.6' from ABPnPE.Web.
Removed file 'alpha.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'anonymous.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'assignment.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'call.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'color.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'comment.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'condition.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'detached-ruleset.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'dimension.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'directive.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'element.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'expression.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'extend.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'import.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'javascript.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'keyword.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'media.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'mixin.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'negative.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'operation.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'paren.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'quoted.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'rule.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'ruleset-call.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'ruleset.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'selector.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'unicode-descriptor.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'url.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'value.js' from folder 'tools\Node\less\lib\less\tree'
Removed file 'variable.js' from folder 'tools\Node\less\lib\less\tree'
Removed folder 'tools\Node\less\lib\less\tree'
Removed file 'colors.js' from folder 'tools\Node\less\lib\less'
Removed file 'encoder.js' from folder 'tools\Node\less\lib\less'
Removed file 'env.js' from folder 'tools\Node\less\lib\less'
Removed file 'extend-visitor.js' from folder 'tools\Node\less\lib\less'
Removed file 'fs.js' from folder 'tools\Node\less\lib\less'
Removed file 'functions.js' from folder 'tools\Node\less\lib\less'
Removed file 'import-visitor.js' from folder 'tools\Node\less\lib\less'
Removed file 'index.js' from folder 'tools\Node\less\lib\less'
Removed file 'join-selector-visitor.js' from folder 'tools\Node\less\lib\less'
Removed file 'lessc_helper.js' from folder 'tools\Node\less\lib\less'
Removed file 'parser.js' from folder 'tools\Node\less\lib\less'
Removed file 'rhino.js' from folder 'tools\Node\less\lib\less'
Removed file 'source-map-output.js' from folder 'tools\Node\less\lib\less'
Removed file 'to-css-visitor.js' from folder 'tools\Node\less\lib\less'
Removed file 'tree.js' from folder 'tools\Node\less\lib\less'
Removed file 'visitor.js' from folder 'tools\Node\less\lib\less'
Removed folder 'tools\Node\less\lib\less'
Removed file 'lessc.js' from folder 'tools\Node\less\lib'
Removed folder 'tools\Node\less\lib'
Removed file 'Mono.Cecil.dll' from folder 'tools\Mono.Cecil'
Removed file 'Mono.Cecil.Mdb.dll' from folder 'tools\Mono.Cecil'
Removed file 'Mono.Cecil.Pdb.dll' from folder 'tools\Mono.Cecil'
Removed file 'Mono.Cecil.Rocks.dll' from folder 'tools\Mono.Cecil'
Removed folder 'tools\Mono.Cecil'
Removed folder 'tools\Node\less'
Removed file 'json2.min.js' from folder 'tools\JsEngine'
Removed file 'lib.d.ts_' from folder 'tools\JsEngine'
Removed file 'MsieJavaScriptEngine.dll' from folder 'tools\JsEngine'
Removed file 'typescriptServices.js' from folder 'tools\JsEngine'
Removed folder 'tools\JsEngine'
Removed file 'lessc.cmd' from folder 'tools\Node'
Removed file 'node.exe' from folder 'tools\Node'
Removed folder 'tools\Node'

**Comment by volkanceylan** [comment]
It doesn't remove anything, if it does it is NuGet bug. Try reinstall.
