### ISSUE TITLE
Serene-master problem

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#1859]
Hi @volkanceylan 
I have cloned Serene, but when I open the Dev.Serene.Web.sln in Visual Studio Community Edition 2015 there are two projects that will not open:

Serenity.TypeScript.CodeGeneration and Serenity.TypeScript.CoreLib

I forget something?

Other this the npm console output me

====Executing command 'npm install'====

npm WARN package.json serenity.test@1.0.0 No README data
npm http GET https://registry.npmjs.org/types/jquery.cookie
npm http GET https://registry.npmjs.org/types/sortablejs
npm http GET https://registry.npmjs.org/types/jquery.blockui
npm http GET https://registry.npmjs.org/types/jquery
npm http GET https://registry.npmjs.org/types/jquery.validation
npm http GET https://registry.npmjs.org/types/toastr
npm http GET https://registry.npmjs.org/types/jqueryui
npm http GET https://registry.npmjs.org/typescript
npm http 404 https://registry.npmjs.org/types/jquery
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/jquery' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'serenity.test'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Marco\Documents\GitHub\Serene\Serenity\Serenity.Test
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code E404
npm http 404 https://registry.npmjs.org/types/jquery.cookie
npm http 404 https://registry.npmjs.org/types/sortablejs
npm http 404 https://registry.npmjs.org/types/jquery.blockui
npm http 404 https://registry.npmjs.org/types/jquery.validation
npm http 404 https://registry.npmjs.org/types/jqueryui
npm http 404 https://registry.npmjs.org/types/toastr
npm http 200 https://registry.npmjs.org/typescript
npm

====npm command completed with exit code 1====

**Comment by VictorTomaili** [comment]
Try to update npm latest for fix 404 errors. You can search for "visual studio npm update" on google.

**Comment by volkanceylan** [comment]
Update your node / npm, and install dotnet 1.1 sdk + visual studio tools

**Comment by Estrusco** [comment]
Perfect! I have updated all and installed visual studio tools. The DotNet 1.1 SDK was already installed. Now all works.
Thank you @volkanceylan  and @VictorTomaili
