### ISSUE TITLE
How to hide fields ?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#186]
Hi,
How to hide fields on dialog from row or form?
I used that on row and form [visible(false)]  as a attribute but it doesn't work.
Then I hide fields on dialog cs. but I wonder why this attribute does not run on row or form?

**Comment by volkanceylan** [comment]
It is for columns only, controls if column is initially visible, as columns are customizable, user might show/hide columns, but this is not usually possible with forms. 

If you don't want to show a field, you don't include it in form definition simply.

In client side, form.XYZ.GetGridField().Toggle(false) in UpdateInterface is also possible. Next version will also have HideOnInsert, HideOnUpdate attrs.

**Comment by volkanceylan** [comment]
On a second thought, with a similar suggestion from @VictorTomaili, visible attribute now works for forms too. Next version...

**Comment by ademc** [comment]
It would be nice thanks

**Comment by tonysader** [comment]
Does the visible attribute work now ?? 
@volkanceylan
