### ISSUE TITLE
Entity edit form - don't ask user if he want to save changes before closing form in case without changes

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#1861]
Hello Volkan,

I have edit form for some basic entity and several tabs with grids for additional entities related to basic one and my goal is to add functionality that asks user if he want to save changes before closing the form. I've added the following method in entity dialog class that should cover this case:

        private void SaveAndClose()
        {
            var closeButton = Element.Closest(".ui-dialog").Find(".ui-dialog-titlebar-close");
            closeButton.Off("click");
            var options = new ConfirmOptions
            {
                Title = "Save Changes Confirmation",
                OnNo = DialogClose
            };
            closeButton.On("click", e =>
            {
                Q.Confirm("Do you want to save changes before closing form?", () =>
                {
                    SaveChanges(i =>
                    {
                        DialogClose();
                    });
                }, options);
            });
        }

And overriden Save(...) is presented below:

        protected override bool Save(Action<ServiceResponse> callback)
        {
            return SaveChanges(callback);
        }

        private bool SaveChanges(Action<ServiceResponse> callback)
        {
            if (!IsNewOrDeleted)
            {
                if (sowPositionsGrid.SOWPositionPeriods != null)
                {
                    SowPositionsService.SaveAllPeriods(new SOWPositionsSaveRequest
                    {
                        SOWPositionPeriods = sowPositionsGrid.SOWPositionPeriods
                    },
                    response =>
                    {
                    });
                }
                if (tripsGrid.Trips != null)
                {
                    TripsService.SaveAllTrips(new TripsSaveRequest
                    {
                        Trips = tripsGrid.Trips
                    },
                    response =>
                    {
                    });
                }
                if (expensesGrid.Expenses != null)
                {
                    ExpensesService.SaveAllExpenses(new ExpensesSaveRequest
                    {
                        Expenses = expensesGrid.Expenses
                    },
                    response =>
                    {
                    });
                }
            }
            return base.Save(callback);
        }

But, I don't know how to check if there aren't any changes in basic entity dialog and appropriate tabs. Could you please share me you point of view regarding right approach for this?

**Comment by sayuga** [comment]
I believe northwind customers table samples has that in place.  you should be able to get the save and load states for all the tabs using the same general idea. 

from Northwinds CustomerDialog.ts: 

constructor() {
            super();

            this.ordersGrid = new CustomerOrdersGrid(this.byId('OrdersGrid'));
            this.ordersGrid.element.flexHeightOnly(1);

            this.byId('NoteList').closest('.field').hide().end().appendTo(this.byId('TabNotes'));
            DialogUtils.pendingChangesConfirmation(this.element, () => this.getSaveState() != this.loadedState);
        }

getSaveState() {
            try {
                return $.toJSON(this.getSaveEntity());
            }
            catch (e) {
                return null;
            }
        }

        loadResponse(data) {
            super.loadResponse(data);
            this.loadedState = this.getSaveState();
        }

**Comment by stepankurdylo** [comment]
Thanks sayuga,

It is what I was looking for.

Regards.
