### ISSUE TITLE
How to add a Employee, can not see this

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1862]
I'm looking for where to add an employee and select their gender.

![screenshot 2017](https://cloud.githubusercontent.com/assets/22305532/22335381/e24d793a-e3b4-11e6-80b7-567d58bf7a67.png)

**Comment by sayuga** [comment]
The employee table is currently not shown on the sample. You'll need to add 

Columns.cs, Dialog.ts, Endpoint.cs, Form.cs, Grid.ts, Index.cshtml, Page.cs, and Repository.cs  to the Employee module. You should be able to do most of it using the CodeGenerator. 

Gender is currently ascertained according to the TitleofCurtesy field. Look at the EmployeeRow.cs file and you'll find 

Expression("(CASE WHEN T0.[TitleOfCourtesy] LIKE '%s%' THEN 2 WHEN T0.[TitleOfCourtesy] LIKE '%Mr%' THEN 1 END)")

on the Gender Field.

**Comment by joheric** [comment]
Wuaoo thank you very much for your help @sayuga you are my hero
