### ISSUE TITLE
Refresh grid from ajax call

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#1863]
Does anyone Know how to refresh the grid with a return of json to the client. See my code below. It will not refresh. Any help will be appreciated. I am receiving the correct json response.

 $("#LoanSearchForm").submit(function (event) {
        /* stop form from submitting normally */
        event.preventDefault();
        /* get some values from elements on the page: */
        var $form = $(this),
            term = $form.find('input[name="Loan_Skey"]').val(),
            url = $form.attr('action');
        /* Send the data using post */
        var posting = $.post(url, {Loan_Skey: term});
        /* Put the results in a div */
        posting.done(function (data) {
            //alert(JSON.stringify(data));
           
            //var loanGrid = new ReverseQuest.Loan.LoanSearchResultsGrid($('#LoanSearchGridDiv'), {});
            //loanGrid.initializeAsync();
           // Q.initFullHeightGridPage($('#LoanSearchGridDiv'));
            //loanGrid.initialPopulate();
            //loanGrid.destroy();
            //loanGrid.render();
            //loanGrid.refresh();
            //new ReverseQuest.Loan.LoanSearchResultsGrid($('#LoanSearchGridDiv'), {}).init();
            
            alert("complete");
           // $("#LoanSearchGridDiv").empty();

            //var content = $(data).find('#content');
            //alert(content.html);
            //$("#result").empty().append(content);
        });
    });

**Comment by VictorTomaili** [comment]
#389
