### ISSUE TITLE
Int to String field (Serenity.IntegerEditor to Serenity.StringEditor)

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1864]
I have a string field that used to be integer. 
Having generated the interface as an integer, the dialog only allows me to enter numbers and not characters. (Serenity.IntegerEditor)
How Can I Change the Serenity.IntegerEditor to Serenity.StringEditor on my T4 templatting?

**Comment by sayuga** [comment]
Why do you have it as a integer if you need to use it as a string? It sounds to me like you should just update the field to be a string field instead of an integer field to begin with.

**Comment by javaman63** [comment]
@sayuga I do not have it as a Integer . I have it as String.
In the past it was Integer, I changed it to String in my XYZRow.cs, XYZForm.cs, but when t4 generates the template, I still add the integer validator (Serenity.IntegerEditor) in the dialog and not the string (Serenity.StringEditor)

**Comment by Estrusco** [comment]
Have you compiled before T4 transformation? See if there are errors in transformation

**Comment by javaman63** [comment]
Yes and there is not error in transformation.

**Comment by volkanceylan** [comment]
Unless you put IntegerEditor somewhere, and checked that form field, property and row has String type, and build before transform, its impossible for T4 to generate IntegerEditor, you're missing something.

**Comment by javaman63** [comment]
Oh my god. You right. Im sorry. I close this

**Comment by volkanceylan** [comment]
So, where was the mistake? :)

**Comment by javaman63** [comment]
Im feel so newbie. I leave the int32 field in the form file. I only change the string in the rowfile. Anyway thanks for always pointme in the right direction
