### ISSUE TITLE
Responsive dialog not so responsive with New or Clone when using custom button

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1865]
So, here's the short story. I was asked to make it so that the form we use hides fields until a particular field is field. Additionally, once the form is filled, it needs to be able to save and close OR save and start a new form with the same CustomerId and AddressLogId as the original. Most all of that works but I've ran into a small snafu. 

When I open a update dialog, the dialog will resize according to the number of Category sections available to display. Exactly what I want. 

When I open a new or clone dialog, It's meant to be maximized, which it does, and it also does hide the categories but, when I un-maximize the dialog, the dialog will revert only to the size of the first category but will not autosize to include the other active categories. Instead it shows me a scroll bar.  

my .less file does have height: auto so I'd expect that to help. 

Here is my code, I welcome any insight. I'll be playing around with the css on it tomorrow. 

namespace MatrixOne.Default {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    @Serenity.Decorators.maximizable()
    export class EquipmentDialog extends Serenity.EntityDialog<EquipmentRow, any> {
        protected getFormKey() { return EquipmentForm.formKey; }
        protected getIdProperty() { return EquipmentRow.idProperty; }
        protected getLocalTextPrefix() { return EquipmentRow.localTextPrefix; }
        protected getNameProperty() { return EquipmentRow.nameProperty; }
        protected getService() { return EquipmentService.baseUrl; }

        protected form = new EquipmentForm(this.idPrefix);
        
        protected getToolbarButtons() {
            let buttons = super.getToolbarButtons();

            buttons.push({
                title: Q.text('SaveAndNew'),
                cssClass: 'save-and-new-button',
                icon: ' icon-docs text-blue',
                onClick: () => {

                    this.saveAndCloseButton.click();

                    var dlg = new EquipmentDialog();
                    var CustId = this.getSaveEntity().CustomerId;
                    var AddId = this.getSaveEntity().AddressLogId;

                    dlg.loadEntityAndOpenDialog(<EquipmentRow>{
                        CustomerId: CustId,
                        AddressLogId: AddId                       
                    });                    

                }
            });
            return buttons;
        };                        
                       
                       
        protected onDialogOpen() {
            super.onDialogOpen();
                        
            this.toggleRun();

            if (this.isNew()) {
                $(".ui-dialog-titlebar-maximize").click();
                
            };
            
        }

        protected toggleRun() {            

            var catOne = 'Equipment';
            var catTwo = 'Address';

            this.categoryToggler(this.form.CustomerId, catTwo);
            this.categoryToggler(this.form.AddressLogId, catOne);
        }

        protected categoryToggler(triggerField: Serenity.LookupEditor, categoryTitle: string) {
            var myTag = categoryTitle;                
            var ele = this.element.find(".category-title:contains('" + myTag + "')").parent();
            var checkTrigger = triggerField.value;

            if (this.isNew) {

            }

            if (Q.isEmptyOrNull(checkTrigger)) {
                ele.toggle(false);

                triggerField.changeSelect2(e => {
                    var myTrigger = triggerField.value;

                    if (Q.isEmptyOrNull(myTrigger) === true) {
                        ele.toggle(false);
                    }

                    else {
                        ele.toggle(true);
                    }
                });
            }

            else {
                triggerField.changeSelect2(e => {
                    var myTrigger = triggerField.value;

                    if (Q.isEmptyOrNull(myTrigger) === true) {
                        ele.toggle(false);
                    }

                    else {
                        ele.toggle(true);
                    }
                });
            }    
        };               

    }
}

**Comment by edson** [comment]
Hi @sayuga .

It seems that your problem is actually a pre-cached dialog size that is done with the DialogExtend plugin when the dialog is maximized.
When you open that dialog, it fits the contents of your form, that is already toggled. As you maximize it and toggle back the categories, it wouldn't know, so it maintains its original size which was the dialog with only one category. That is... it saves the last dialog size to restore to it...

So, you could workaround it with events handling triggered from dialogextend, by giving it its original full size before toggling. Something like:

```
protected onDialogOpen() {
            super.onDialogOpen();

            var selfDialog = this;
            
            this.element.on("dialogextendmaximize", function (event, ui) {
                selfDialog.toggleRun();
            });
           
             if (this.isNew()) {
                 $(".ui-dialog-titlebar-maximize").click();
            
             };
            

        }
```

But, if you have to deal with different category toggling at a time, the full height would leave a blank space when dialog is restored from maximized one... so you would have to deal somehow with the height if you really need to use the maximize option... So there's another event triggered when it is restored and you could use it to set height accordingly : "_dialogextendrestore_"...

Hope it helps somehow.

Best Regards.

**Comment by sayuga** [comment]
Very helpful actually though it seems that if I use it as is, it works for the new and update but the new  dialog has the toggle broken. I'll play around with this some more. It's a good starting point. 

The reason I'm using a maximized view is because the manager that is having me work this out, wants the people entering the information to be forced to focus only on the form and to only be able to see fields after they've entered the information for prior fields but I know there may be times they may need to minimize the dialog so I just want to cover my bases instead of removing the restore button. I don't really mind the empty space that much so I'm not too worried about the height.  Worst case scenario, i'll just remove the restore button.

**Comment by edson** [comment]
Yep. It would only toggle when It is maximized, so the event is triggered.

Maybe you could save the dialog size before toggling and always restore to that state.. or dynamically calculate the height.. or so Just a flag to know when It Will open  maximized.. but you know better the behavior It needs to have. 

Best regards.
