### ISSUE TITLE
MasterDetailRelation Don't Save. Why?

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#1866]
I have several MasterDetalRelation working just fine on my project.
I add to the XYZRow.cs
`
        [DisplayName("Estados"), MasterDetailRelation(foreignKey: "IdSiniestro"), ClientSide]
        public List<GestionesSiniestrosXEstadosRow> ListaEstadosGestiones
        {
            get { return Fields.ListaEstadosGestiones[this]; }
            set { Fields.ListaEstadosGestiones[this] = value; }
        }

`

On my XYZForm.cs file the Custom editor
`
        [GestionesSiniestrosXEstadosEditor]
        public List<Entities.GestionesSiniestrosXEstadosRow>  ListaEstadosGestiones { get; set; }

`

But when I click on save, nothing happens, no error, no nothing, and the form keep visible and thats is weird for me. 
and thats my question...anyone can give some inside ?

![captura-de-pantalla-2017-01-26-20 06 23](https://cloud.githubusercontent.com/assets/8239681/22354376/cfce9362-e403-11e6-817f-5a425443d536.png)

**Comment by brunobola** [comment]
transform t4 rebuild....

**Comment by javaman63** [comment]
I did it so many times

**Comment by volkanceylan** [comment]
I dont see anything wrong here

**Comment by javaman63** [comment]
I Find the reason why my dialogue did not save the changes.
I forgot to put a "return true" in the validateentity method.

I hope it will serve somebody in the future.
