### ISSUE TITLE
Bypass login 

### ISSUE THREAD

**Issue by annapras** [volkanceylan/Serenity#1868]
Is there a way I can bypass the login screen and go directly to the dashboard page as we are building an I tranet only app..
If so, how can that be done..

**Comment by samdubey** [comment]
Hi @annapras 
You can simply remove all "Authorize" attributes from Pages / Controllers
for example:
    [RoutePrefix("Dashboard"), Route("{action=index}")]
    public class DashboardController : Controller
    {
        [Authorize, HttpGet, Route("~/")]
        public ActionResult Index()
...
....

**Comment by VictorTomaili** [comment]
I don't recommend remove all authantication from code. If you have Active Directory, you can authenticate users by AD. Or more simply one, move login page to adminlogin and create simple login page with auto login by default user.

**Comment by annapras** [comment]
Thanks for the tips, @victor, would you recommend doing a a redirect from the account controller or if there is any other sample that I can reference,

**Comment by volkanceylan** [comment]
What u are looking for is Windows auth which may only work properly on IE, and i dont support nor sample.
