### ISSUE TITLE
What if I don't have MsSqlLocalDB?

### ISSUE THREAD

**Issue by James-A-White** [volkanceylan/Serenity#1869]
When I try to create a new VS 2015 project, I get an error 

A problem was encountered creating the sub project 'Serene.Web'.
"SQL Server LocalDB is not installed on <Machine name>".  

I have a SQL Server 2016 instance installed on my machine and I wish to use that.  I don't see a way for me to get around this, and I don't want to install another SQL on my machine.

Any help would be appreciated.

Thanks!

Jw

(p.s. I think I must be missing something very basic!)

**Comment by volkanceylan** [comment]
Change connection string

**Comment by James-A-White** [comment]
Sorry for the silly question... I don't see where I can change the connection string. 

I'm getting the error before any files are created in my solution; all I have is an empty folder structure. And I can't seem to find where the Serenity templates were downloaded.

Thx! J

**Comment by VictorTomaili** [comment]
Try recreate from sample and use google for change connectionstring.

**Comment by James-A-White** [comment]
Perhaps my problem is that I'm creating the project using visual studio directly?  Should I download a sample from Github?

**Comment by VictorTomaili** [comment]
Nope, use serenity template from visual studio gallery.

**Comment by James-A-White** [comment]
Hmmm... I don't have the LocalDB option installed on my machine (I'll do that next week if I have to). So, either the Serenity template installer has an error when installing on a machine without a LocalDB or my VS 2015 installation is corrupt.  I don't see any opportunity to change the connection string before I get the error.  I've removed the Serenity template from my computer and re-downloaded it and I still get the same error.  Thx for your help!  :-)

**Comment by jmace** [comment]
An example connection string for a locally installed sql express is Data. I may be wrong, but I thought SQL express was installed with visual studio? You'll need to do your modifications within the web.config file in your newly initiated serenity project. 

`Source=YOURMACHINENAME\SQLEXPRESS;`

**Comment by stixoffire** [comment]
@James-A-White are you building the Serenity Project itself ? , or are you building a new project from the VSIX template - the vsix template installs into VS 2015 , then select new project and select Serenity as your project - if you are having an issue even after that something else is wrong. I have different systems that I have used the template with - no problems VS2015 actually creates a LocalDb if I am not mistaken. (not to be confused with a Local instance of SQL

**Comment by James-A-White** [comment]
I went ahead and installed a version of LocalDB and all works fine now.  

Mine may have been an edge case because VS 2015 normally installs LocalDB... I probably "unchecked" that option during installation because I thought it was redundant to have it and a full-fledged SQL Server instance running on the same machine.  

It *may* be worth trying the Serenity installation on a clean machine with no LocalDB installed to see if it can be made to fail more gracefully (an error message that states that LocalDB is required) or give users the option to add in a connection string to another server.

Thanks everyone for your help.

James

**Comment by volkanceylan** [comment]
2.9.1 shouldn't crash if no SQL local db exists, well theorically.
