### ISSUE TITLE
Dialog; Stringfield; "Realtime" validation of field regarding length and numbers

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#187]
Hi JaiQ,

John Ranger here again :-)

One last question for today for which I didn't find the answer in the dev guide nor within Northwind example.

On a Dialog I have a field (InventoryLabel) which I want to be a 6-char string (not technically handled as an integer).
- It must contain only numbers (0-9)
- but must be always 6 chars in length - even when the number value would be less than 100000 (e.g. 012345)

I have tried by defining the Field within the xyzRow.cs as an IntegerEditor (on a Stringfield) but this has technically converted the type on the Client side (script Project part) to a real integer which has caused some other Problems (e.g. length Validation).

How can I achieve the following:
- field must always be treated as a string
- Field must never accept more Digits than 6 (I want later to pull this length dynamically out of a Settings table so the solution must not be statically defined)
- field must only accept numbers (0-9)
- Validation of field shall fail when the save-and-Close button (update button) is clicked and for example only 5 Digits have been entered

Thanks again for guiding me into the right direction.

With Kind regards,

John

**Comment by VictorTomaili** [comment]
I know somethink like masked editor.

**Comment by volkanceylan** [comment]
See OrderDetailDialog for input based validation sample, line with form.XYZ.AddValidationRule

**Comment by JohnRanger** [comment]
Hi Victor,

thanks for your Input :-)

I have tried to use MaskedEditor Attribute on the relevant field in xyzRow.cs but when I apply it then the form Dialog does not anymore Show up.

I have used the following:
```[MaskedEditor(Mask = "999999", Placeholder = "999999")]```

(also in different variants with mask="nnnnnn" and mask ="000000") but with no avail.

In Northwind serene and in dev guide I didn't find any reference to the MaskedEditor and how to use and or modify it.

(I am no real dev but only an IT admin with some developer ambitions so please forgive me my lack of understanding).

Can you explain to me how to use the MaskedEditor correctly and what is required for it to work.

Thanks and with Kind regards,

John

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks, that was the hint into the right direction. 

@Victor: The MaskedEditor must be for something else when I look at the Definition.

For the benefit of other Readers, here the code which worked for me (put this into the xyzDialog.cs):

```cs
public StageThisClientDialog()
        {
            form = new StageThisClientForm(this.IdPrefix);

            Regex regex = new Regex(@"^\d{6}$"); // *** Replace the number 6 with the amount of Digits you Need ***
            form.InventoryLabel.AddValidationRule(this.uniqueName, e =>
            {
                if (regex.Test(form.InventoryLabel.Value))
                {
                    return null;
                }
                else
                {
                    return "Inventory must be exactly 6 DIGITS long (e.g. 123456)";
                }

                //return regex.Test(form.InventoryLabel.Value) ? null : "Inventory must be exactly 6 DIGITS long (e.g. 123456)"; // *** Does exactly the same as the above IF-then-else structure ***
            });

        }

```

Thanks to all for your Support and to JaiQ for the correct solution. Keep up your excellent work!

With Kind regards,

John

**Comment by victor** [comment]
No comment

**Comment by VictorTomaili** [comment]
hahah :D @victor lets replace accounts.
