### ISSUE TITLE
Serene Template wizard dialog is not scaled properly on High DPI

### ISSUE THREAD

**Issue by jozefizso** [volkanceylan/Serenity#1870]
When I chose to create new project from **SERENE (ASP.NET Core)** template, the Serene dialog box is not scaled properly on High DPI screens.

The OK and Cancel buttons are functional, but they are not legible.

![serene_vs_dialog](https://cloud.githubusercontent.com/assets/287778/22372425/df72323a-e49c-11e6-88ca-334e79b90f70.png)

**Comment by volkanceylan** [comment]
Is your fonts on %200 or higher?  Thats something Windows should handle actually.

**Comment by jozefizso** [comment]
It's on 4k monitor with scaling set to 200%.

**Comment by volkanceylan** [comment]
Thanks, this should be fixed in latest template
