### ISSUE TITLE
Custom Lookup Text returning Undefined

### ISSUE THREAD

**Issue by Daffyydd** [volkanceylan/Serenity#1871]
I have a lookup which i would like to custom the text by combining 2 fields.

The fields are 
AccountId -- Identity
Accountnumber
AccountName

I have followed the example in Basic Samples but am getting Undefined for Item.AccountName, am getting right values for Item.AccountId or Item.AccountNumber.

Below is my code for the lookup Editor.

namespace SaccoManagementSystem.Masters {

    @Serenity.Decorators.registerEditor()
    export class MappedAccount extends Serenity.LookupEditorBase<Serenity.LookupEditorOptions, ChartofAccountsRow>{

        constructor(container: JQuery, options: Serenity.LookupEditorOptions) {
            super(container, options);
        }

        protected getLookupKey() {
            return ChartofAccountsRow.lookupKey;
        }

        protected getItemText(item: ChartofAccountsRow, lookup: Q.Lookup<ChartofAccountsRow>) {
            return super.getItemText(item, lookup) + ' - '+ item.AccountName;
        }

    }
}

What am i Missing here?

Thanks for your values inputs

**Comment by VictorTomaili** [comment]
look at lookupinclude attribute. 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.AspNetCore/Modules/Northwind/Territory/TerritoryRow.cs#L30

**Comment by sayuga** [comment]
I believe the issue is in the extension values. You should have it as Serenity.LookupEditorBase<ChartofAccountsRow, any>. Additionally there is no need to pass the row and lookup the way you do in the getItemText call. 

Try this: 


namespace SaccoManagementSystem.Masters {

@Serenity.Decorators.registerEditor()
export class MappedAccount extends Serenity.LookupEditorBase<ChartofAccountsRow, any>{

    constructor(container: JQuery, options: Serenity.LookupEditorOptions) {
        super(container, options);
    }

    protected getLookupKey() {
        return ChartofAccountsRow.lookupKey;
    }

        protected getItemText(item, lookup) {

            var firstField= super.getItemText(item, lookup);
            var secondField = item.AccountName;

            var result = "AccountNumber: " + firstField + ' - [AccountName: ' + secondField+ ']';

            return result;
        }

}

**Comment by VictorTomaili** [comment]
@sayuga please use ``` tags for code styntax in markdown.

**Comment by Daffyydd** [comment]
thanks you so much @VictorTomaili  and @sayuga  for you valuable direction.

I only needed to add LookupInclude

**Comment by sayuga** [comment]
oops, sorry about that @VictorTomaili. I'll take note.
