### ISSUE TITLE
error on UpdateById

### ISSUE THREAD

**Issue by yvcabrera** [volkanceylan/Serenity#1872]
I have the following error "Invalid column name 'GlobalReference'.", When I try to update the entity "DocumentRow". The "GlobalReference" property does not exist as a table field in the database, it is only on the client side.

**CODE** 
 foreach (var doc in doclist)
 {
   var tmp = doc.TableClone();
   tmp.IdSobre = (int?)idsobre;
   **//ERROR IN THIS LINE**
  **uow.Connection.UpdateById<DocumentoRow>(tmp);**
}

And "**DocumentoRow**" 

public sealed class DocumentoRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), Identity, PrimaryKey]
        public int? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        DisplayName("Razón Referencia")]
        public string ReferenciaExterna
        {
            get { return Fields.ReferenciaExterna[this]; }
            set { Fields.ReferenciaExterna[this] = value; }
        }

        [SetFieldFlags(FieldFlags.ClientSide)]
        public bool? ReferenciaGlobal
        {
            get { return Fields.ReferenciaGlobal[this]; }
            set { Fields.ReferenciaGlobal[this] = value; }
        }

        [DisplayName("Serie"), Size(2)]
        public string Serie
        {
            get { return Fields.Serie[this]; }
            set { Fields.Serie[this] = value; }
        }
        
        IIdField IIdRow.IdField => Fields.Id;

        StringField INameRow.NameField => Fields.Observaciones;

        public static readonly RowFields Fields = new RowFields().Init();

        public DocumentoRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public StringField ReferenciaExterna;
            public BooleanField ReferenciaGlobal;
            public StringField Serie;
            
            public RowFields()
                : base("[dbo].[Documento]")
            {
                LocalTextPrefix = "Factura.Documento";
            }
        }
    }

**Comment by volkanceylan** [comment]
I don't know what is TableClone you are using, but client side fields shouldn't be set (not assigned, even null) while calling connection extensions like UpdateById, as they don't care about field flags.

**Comment by yvcabrera** [comment]
TableClone is:

public static TRow TableClone<TRow>(this TRow row)
            where TRow : Row, new()
        {
            var clone = new TRow();

            foreach (var field in row.GetFields())
            {
                if (field.GetAttribute<ClientSideAttribute>() == null &&
                    field.GetAttribute<ExpressionAttribute>() == null &&
                    field.GetAttribute<MasterDetailRelationAttribute>() == null &&
                    field.GetAttribute<LinkingSetRelationAttribute>() == null)
                {
                    field.Copy(row, clone);
                }
            }

            return clone;
        }

**Comment by volkanceylan** [comment]
You should use GetTableFields() extension, it's safer then what you wrote

Your mistake is in this line:

```
if (field.GetAttribute<ClientSideAttribute>() == null &&
```

ReferenciaGlobal has SetFieldFlags attribute with a ClientSide enum flag, not ClientSideAttribute

**Comment by yvcabrera** [comment]
Thanks ..!!!
