### ISSUE TITLE
add data-toggle to  buttons.push

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1873]
Hi guys,
has anyone tried to add dropdown menu to using buttons.push in xxGrid.ts? 

I have a grid with checkbox selection and would like to add a button with dropdown menu, currently I'm using a dialog to display the options of the selected rows.

Please share the code if you have done that.

Thanks

**Comment by edson** [comment]
See https://github.com/volkanceylan/Serenity/wiki/SplitButton%20dropdowns
