### ISSUE TITLE
Dialog as Panel

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1874]
How to change the default behavior from dialog to panel.

protected editItem(entityOrId) {
            // check that this is an edit link click, not add button, ID is always a string
            if (typeof entityOrId == "string") {
                console.log(entityOrId);
                new AddNewVoucher().loadByIdAndOpenDialog(entityOrId);
            }
            else {
                super.editItem(entityOrId);
            }
        }

would this work.

**Comment by Estrusco** [comment]
Do you want a sample for dialog as panel?
See https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/EntityDialogAsPanel

**Comment by mrajalko** [comment]
No i was asking how this panel can be shown from grid.

**Comment by volkanceylan** [comment]
You use dialogs or you use panel, there is nothing between.

**Comment by wldkrd1** [comment]
Well, there is _something_ in between...He could create a custom formatter to generate the hyperlink in the grid pointing to the entity panel.

**Comment by wldkrd1** [comment]
Or the built-in URLFormatter, that would be even easier

**Comment by mrajalko** [comment]
@wldkrd1 thanks.

I would give it a try and revert.

**Comment by mrajalko** [comment]
thanks @wldkrd1 your suggestion worked for me. I have done as under

![image](https://cloud.githubusercontent.com/assets/18166582/22784649/f2303f0c-eef6-11e6-8ad8-33e573de02f3.png)

do you think i have approached it correctly.

**Comment by wldkrd1** [comment]
Yes, that's the easiest and most straightforward way to accomplish it.
