### ISSUE TITLE
Changing report key

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1875]
getToolbarButtons() {
          var buttons = super.getToolbarButtons();
         
          buttons.push(Test.Common.ReportHelper.createToolButton({
              title: rpttitle,
              cssClass: 'export-pdf-button',
              reportKey: rptkey,
              getParams: () => ({ StartDate: this.form.StartDate.value, EndDate: this.form.EndDate.value })
          }));

       return buttons;
}

there's an dropdown on form, when the item in dropdown is changed i want to change the reportKey

if (this.form.Type.value == "2") {
//Here i want to change reportKey
}

**Comment by volkanceylan** [comment]
You can't use createToolButton in that case. Create buttons manually and use executeReport of that helper.

**Comment by vinaykulkarni89** [comment]
is there any sample? in northwind example?

**Comment by volkanceylan** [comment]
No sample
