### ISSUE TITLE
VS2015 Crashes on new project create

### ISSUE THREAD

**Issue by wolfen351** [volkanceylan/Serenity#1876]
Hi there

I did the following steps:
1. Open VS2015 (SP3) Community 
2. Select File, New Project, Online, Serene (Serentiy Application Template) (it was already installed)
3. Name=MyboxSerene   Location=C:\Stuff\Code\MyboxSerene   Solution Name=MyboxSerene, OK
4. Leave everything checked, OK
5. Watch as it installs a million nuget packages
6. It pops up a "this is taking very long dialog, vs may be hung" (but this disappears after a few seconds)
7. Watch as more nuget packages are installed
8. The dreaded this application has stopped working popup appears, and the solution is not complete

Version Info:
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.02012

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2015   00322-20000-00000-AA422
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-20000-00000-AA422
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA422
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA422
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.17.00119.9
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20810.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.3.16270.0
GhostDoc automatically generates XML documentation comments.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.3.1    Build 107.0.20161222.212756
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 2)   14.1.20810.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1700.68
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1700.68

SQL Server Data Tools   14.0.60812.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1700.68
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1700.68

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by volkanceylan** [comment]
Template contains two project, VS chooses .Net core one by default. If you use new project window you can choose MVC one. .Net Core version doesnt install any NuGet packages, its probably because you are creating a .net core project first time, VS is initializing .Net core sdk. You can report a million package issue to MS itself.

**Comment by wolfen351** [comment]
Thanks for the feedback, where do i find the .net core vs mvc setting?  In the New Project window i have selected .Net 4.5.2 at the top. The only dialog that pops up asks me which bits of serentity I want to install, with all checked by default. 

After clicking OK on that dialog, I get asked no more questions, and after a few mins of waiting for packages to download and install VS crashes. 

The million nuget packages was an exaggeration, i was just referring to the many packages normally installed with serenity :) (A good thing)

**Comment by wolfen351** [comment]
The crash occurs while installing package: Serentity.Web 2.9.0

**Comment by wolfen351** [comment]
Ok I clicked on new Project again, and this time I went to "Installed" instead of "Online" - there is a decision on MVC vs Core, and i'm running another round with the MVC one

**Comment by wolfen351** [comment]
Nope, same issue using the MVC template in the "Installed" section in New Project.

Are there any logs I can provide?

**Comment by volkanceylan** [comment]
Do you have SQL Local DB? Also you may try disabling Resharper. VS should have some crash log, it might help identifying where it is crashing. Serenity.Web is the last installed package, it probably crashes after installing packages somewhere in project initialization.

**Comment by wolfen351** [comment]
I tried on a different pc and got the same crash but on a different package:  select2.js 3.5.1

**Comment by wolfen351** [comment]
I'll disable resharper and retry, also will see if I can find a crash log somewhere

**Comment by wolfen351** [comment]
I do have sql localdb installed, will find version number and report back - I basically have a full install of SqlExpress 2014 (with advanced)

**Comment by volkanceylan** [comment]
I'll try to put try catch to possible places, and release a new template, maybe we can see where it is crashing somehow

**Comment by wolfen351** [comment]
I did get the activitylog.xml from visual studio, but there are no relevant errors logged

**Comment by wolfen351** [comment]
Is there a serenity specific log (for the init process)?

**Comment by volkanceylan** [comment]
Please uninstall Serene completely from extensions, install new one using Online now, i also want to be sure that MVC is selected by default on first install. Unfortunately i have no option to set it, probably chosen by naming. 

You'll get an error message if it is crashing on some code for Serenity project wizard.

**Comment by wolfen351** [comment]
Success, I managed to get a good install with resharper disabled!

I'll do what you ask now.

**Comment by wolfen351** [comment]
Uninstalled 2.9.0.3
Installed 2.9.1.1

Running the install now

**Comment by wolfen351** [comment]
Another success. Next I'll re-enable resharper and try again.

**Comment by wolfen351** [comment]
lol, now it works even with resharper enabled. Whatever you did in this new version, or perhaps just reinstalling it helped! Thanks!

**Comment by wolfen351** [comment]
Ok, some final feedback - on the other pc that had the issue, I ONLY reinstalled the extension, and left resharper running. It worked fine after the reinstall. I guess somehow the installation got messed up since the original install. 

Thanks again for the help in resolving this.

**Comment by volkanceylan** [comment]
You're welcome, anyway there might be other new users who experience this and give up without reporting, thanks.
