### ISSUE TITLE
ProjeAdi.Script kurulmiyor

### ISSUE THREAD

**Issue by SorinGFS** [volkanceylan/Serenity#1877]
Merhaba Volkan. Iki gun even sizin Seren template-yi gordum youtube'de, ve cok ilgimi cekti. Visual Studio 2013 kullaniyordum dun'e kadar, fakat anlatacagim problemlerden sonra 2015 versiyonunu da kurdum, ayarladim.

Basta, Seren template'ini kurdum visual studioya, sonra yeni proje > c# > projeAdi yeni bir proje acmaya calistim template'i kullanarak. Fakat TypeScript'le ilgili hatalar verdi, sonra anladim ki benim TypeScript versyonu cok eskiymis, guncellestirmeye calistim. Baktim seren projesinde en son TypeScript versyonu gerektirir, package manager console'den kurmaya calistim, fakat en son versyonunu 1.8.5 verdi. Kurdum onu, baktim ki onla da calismiyor, arastirmaya basladim. Buldum ki VS 2013'te ondan fazlasi direkmen olmuyor. Visual Studio 2015 kurayim dedim, kurdum, ayarladim. Onda da en son TypeScript versyonu 2.0.6 verdi, arastidrim ilgili linkinde ve gordum ki o versyonu tavsiye edilmiyormus, visual studyo'yu boziyormus, bundan dolayi onu kurmamaya karar verdim. Biraz daha arastirdiktan sonra buldum ki TypeScript son versyonu sadece node.js araciligi'ila kurulabilir, node.js'yi kurdum, guncellestirdim, ve de sonunda npm install -g typescript@next son versyonunu kurmus oldum.

Neyse ki bu da yaramadi, hic bir sekilde ikinci proje kurulmiyor (projeAdi.script olan), ve de sana sormaya karar verdim, acaba yanlis bir sey mi yapiyorum?

Problem: sergen gelmiyor :) 

PS - turkce'mi af et, ben turk degilim, ve de uzun zamandir turkce konusmadim.

**Comment by volkanceylan** [comment]
Merhaba, Serene de artık Script projesi yok, ayrı değil, TypeScript kodları
Web projesi içinde. TypeScript 2.1 kurun

**Comment by SorinGFS** [comment]
Tamam, cok hizli cevabi icin tessekur ediyorum. 
Simdi typescript 2.2.0 kurulu, typescript ile hic tecrubem yok, acaba versiyonlar .net.Framework versiyonlari gibisi bir birine engel olmuyormu, yoksa nasil? TypeScript 2.1 eklemek mi lazim?

**Comment by SorinGFS** [comment]
Ayrica, simdi script projesi olmayinca proje nasil ozellestirilir? 

Bununla ilgili ogrenme amaciyla bakabilecegim bir yer varmi?

**Comment by volkanceylan** [comment]
Sorun olmaz guide ı okuyun
