### ISSUE TITLE
Drag and drop in simple grid

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#1878]
How to drag and drop row , and rearrange sequence of rows in simple grid

**Comment by williamhodges** [comment]
Please check the samples at serenity.is/demo

**Comment by karimhyatt** [comment]
Can you be more precise please. The example in basic samples allows you to move one row under another. I'm also struggling to identify the gap between two rows as a drop target.

**Comment by volkanceylan** [comment]
SlickGrid has some drag drop plugin, see its examples.
