### ISSUE TITLE
Getting Build Error - exited with code 1

### ISSUE THREAD

**Issue by jamesalvin49** [volkanceylan/Serenity#188]
Hello,

Just downloaded serenity and tried my first project and got this error. 

The command ""D:\Serene1\Serene1\Serene1.Web\tools\node\lessc.cmd" "D:\Serene1\Serene1\Serene1.Web\Content\site\site.less" > "D:\Serene1\Serene1\Serene1.Web\Content\site\site.css"" exited with code 1.	

Serene1.Web	

D:\Serene1\Serene1\Serene1.Web\Serene1.Web.csproj	

1661	

Regards

James Alvin

**Comment by dfaruque** [comment]
Download node.exe for 32-bit.
and replace it in D:\Serene1\Serene1\Serene1.Web\tools\node

**Comment by jamesalvin49** [comment]
Thanx dfaruque it worked !!
