### ISSUE TITLE
Sergen dose not work in new update

### ISSUE THREAD

**Issue by alitarkian** [volkanceylan/Serenity#1880]
Hi friends
Can you help me? please

I create new Serenity project 
and when call sergen it dost not work and get this error

![image](https://cloud.githubusercontent.com/assets/19204100/22440182/a98e2784-e747-11e6-8adf-c47ad0737354.png)

**Comment by Estrusco** [comment]
See here http://serenity.is/blog/2017/01/18/welcome-to-aspnet-core

**Comment by wldkrd1** [comment]
I don't think this is an asp.net core issue, notice the error is coming from package manager. I've got the same issue on two of my workstations.
