### ISSUE TITLE
Unique numbering

### ISSUE THREAD

**Issue by eadjeidjan** [volkanceylan/Serenity#1881]
Hello, please how do i generate a unique numbering for an entity, example creating member registration number or an account number for a client
 something like (DDMMYYY001BRCODE) --> (140120170018DF009)

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/SerialAutoNumber
