### ISSUE TITLE
Trying to get a dialog to fill the right side of the screen

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#1882]
In looking at the "Grid as Panel' dialog sample I had a notion of using a dialog to fill the right hand side of the screen, past the menubar.   The idea is to have the dialog take up the same space as a grid listing.

I tried a few things, but only got to the point where the dialog fills half the available vertical space.  I have to use the scroll bar on the right to see all the dialog info, and I'm not sure why-- I played with some CSS but nothing worked.  

Here's what I'm seeing, and note too that this dialog has tabs, which for some reason aren't formatted correctly when used in this instance (they look fine in a regular dialog scenario):

![image](https://cloud.githubusercontent.com/assets/2700083/22494777/35fc656c-e7ef-11e6-9e3a-60e37b3500d5.png)

The dialog 'works', in that I can edit and save information, but the UI is a little off, as you can see. 

Here's what I did to get to this point.  In the cshtml I added a new div tag ('DialogDiv') and hid it by default:

```
<div id="GridDiv"></div>
<div id="DialogDiv" style="display: none;"></div>

<script type="text/javascript">

    jQuery(function () {
        new Serene2.Hindsight.IncidentsGrid($('#GridDiv'), {}).init();

        Q.initFullHeightGridPage($('#GridDiv'));
        Q.initFullHeightGridPage($('#DialogDiv'));


    });
</script>
```

In the dialog class itself all I did was add the `@Serenity.Decoratos.panel()` attribute.  In the grid, I hid the standard `GridDiv `on an item click, and loaded and showed the '`DialogDiv`':

```
        protected editItem(entityOrId) {
            if (typeof entityOrId == "string") {
                var item = this.view.getItemById(Q.toId(entityOrId));
                var dlg = new Hindsight.IncidentsDialog();
                this.initDialog(dlg);
                dlg.load(item.Id, () => {               
                    $('#GridDiv').fadeOut(1);
                    $('#DialogDiv').fadeIn(1000);
                    dlg.element.appendTo('#DialogDiv');
                },
                    () => {
                });
            }
        }
```
 I don't expect anyone to have a magic 'change this one line of code and you're set' answer to the problem, but if you have some ideas or guidance I'd be grateful.  I suspect some CSS stuff is the culprit here but I haven't been able to nail it down.

**Comment by VictorTomaili** [comment]
what is your css ?

**Comment by lquantz** [comment]
I didn't modify any of the core css involved with the dialogs or other Serenity UI elements, so no changes.  My only changes are in the code snippets above.  

I *did* try fiddling with the CSS in the Chrome dev tools, to see if I could hack something but couldn't make any progress, quite possibly due to my beginner-level CSS skills

**Comment by javaman63** [comment]
Try this: Edit your site.less file (Content/Site/site.less)

use this code

` .s-YourDialog {
    > .size { width: 650px; height:700px; }
    .caption { width: 150px; }
} `

Save file, compile project and BUILD T4

**Comment by lquantz** [comment]
Thanks for the tip, didn't see this until just now
