### ISSUE TITLE
problem with related table

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1883]
does the framework allow me to access fields in a related related table?

ex       I want to access field in third table through table 1 and table 2

hope Im explaining it right.

table 1 ------------>table 2 ------------------> table 3 with field

I know how to do this with two tables but not with three

ex  

[DisplayName("Agenda Type"), NotNull, ForeignKey("MeetingAgendaTypes", "AgendaTypeId"), LeftJoin("jAgendaType"), TextualField("AgendaTypeName")]
        public Int32? AgendaTypeId
        {
            get { return Fields.AgendaTypeId[this]; }
            set { Fields.AgendaTypeId[this] = value; }
        }

**Comment by VictorTomaili** [comment]
you can add `related related related related table` too. And you dont need add all related properties in row. 
Its standart sql join. Please read docs and take a look at serene sample. 

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerRow.cs#L15

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)
