### ISSUE TITLE
2nd level detail does not retrieved by calling x.xService.Retrieve

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1884]
```
x.xService.Retrieve({ EntityId: id }, response => {
                    response.Entity;

                });
```

here response.Entity does not retrieved 2nd level details
It only happens if I call it manually by .ts
but works in dialog.

What would be the reason?

Please help.

**Comment by marcobisio** [comment]
Hi @dfaruque,
already tried with "IncludeColumns" properties in the RetrieveRequest?
Something like this:

    {
    EntityId: id,
    IncludeColumns: [fld.X, fld.Y]
    }

Bye

**Comment by dfaruque** [comment]
Thank you @marcobisio 

`{ EntityId: Id, ColumnSelection: Serenity.RetrieveColumnSelection.details }`

this resolved my issue

**Comment by volkanceylan** [comment]
Details should be the default for retrieve, which doesn't differ between first or second level foreign fields.
