### ISSUE TITLE
Starting line

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#1885]
HI All, 

I'm in a bit of a lull in the project I've been working on with Serenity at the core so I figured I'd run some refreshers for myself regarding C#, Typescript and .Net. Most of what I know has been self taught and lacks structure so I figured it's a good time to bring things back in line while focusing it around Serenity. With that in mind, I figured I'd inquire 2 things from all of you. 

First, do any of you have preferences in resources or references to use when dealing with any of the base languages for Serenity. 

Second, I intend to build a Wiki page with a organized version of all the information I gather so that those people coming in with Entry Level knowledge, have a good place to start since I've seen there are more and more people being drawn to Serenity and not all are advanced experienced programmers. 

I am considering, with @volkanceylan persmission, to maybe put some training materials together where I take Serenity and, essentially, dissect the different parts of serenity and make sample implementation guides, videos, etc. I know there is already a decent number of Wiki's and samples withing the code but I figure I can do a couple videos where I show the steps so that even beginners can grasp as they get more involved. 

Anyhow, I will be making personal reference materials anyway so I figured sharing never hurts.

**Comment by javaman63** [comment]
It's a good idea!

**Comment by abelal83** [comment]
sounds like a great idea @sayuga !
if you need any help I'll be happy to give.

**Comment by dfaruque** [comment]
Go ahead. @sayuga

**Comment by sayuga** [comment]
glad to hear there is desire for this. I'll be trolling through the archived issues and pulling information and I'll be cleaning up samples and probably putting together a repository with common additions to Serenity such as the missing files for the Employee Table that make it not show itself on the sample. Once I put some more concrete information together I'll start posting onto here what I have looking for feedback. Meanwhile, if anyone has links to particular things they feel strongly about adding in, or specific issue numbers you want me to add samples for, please reply here and I'll do my best to be prompt.

**Comment by sayuga** [comment]
I'm in the process of translating the existing manual into Spanish and grabbing the Wiki's and adding them to the manual I'm writing. I'll add the link to the gitbook soon. Meanwhile, I have a question. What is easier, written manuals or would it be best to have video links? I was wondering whether to write out the full manual or just make a library of videos implementing all the samples.

**Comment by javaman63** [comment]
@sayuga Los videos son generalmente mas ilustrativos que los ejemplos estaticos. Voto por ellos

Videos are generally more illustrative than static examples. I vote for them 💃

**Comment by sayuga** [comment]
Ok, I'll start then running a screen recorder as I implement all the features I go finding. @volkanceylan Do you want me to send you the videos as I go making them or is it alright if I make a Youtube channel of my own for now?

**Comment by volkanceylan** [comment]
I can put links to your channel in Readme, later we may consider a common channel

**Comment by sayuga** [comment]
Alright, Once I get a few together I'll send them over. Meanwhile i'm in the process of translating the existing manual to Spanish. I've had a number of Spanish speakers ask me about things that are already in the manual. I'll start posting items in the next week or so.

**Comment by sayuga** [comment]
Hi All, I've started a Repository where i'll be keeping the tutorials and related files. Mind you I'm still drafting the manual, doing videos and building the sample files so it's a tad empty at the moment but I welcome any and all corrections, additions and even code donations you'd like to add. I'm focusing on making the instructions as simple as possible while also adding sample files on the repository specific to the files changes/used/created. Here is the link: 

https://github.com/sayuga/SerenityTutorials 

Meanwhile I still am working on translating the original manual to spanish and getting some video tutorials up

**Comment by javaman63** [comment]
Hi @sayuga if you want any help translatting the manual to spanish, let me know

**Comment by akaAlso** [comment]
Thanks for this @sayuga, I will be following with great interest.
I came across Serenity from the Lightswitch announcement page. I explored sharepoint/lightswitch a few years ago, and followed along with the Michael Washington book, together with a few other tutorials that were around -  but never really achieved anything. 
I dabble in my spare time, but am not a programmer although I watched a lot of courses on MVA and have a very sketchy grasp of overall concepts - it's time I followed through and produced something I can use to make my day job more efficient. 
I'm reasonably familiar with Excel, filters, formatting etc, and put an Access Db together into a small package at the turn of the century, but really, I'm the complete novice beginner you speak of.
I'm at the stage where I'm looking to get VS Community set up, and I've started watching some Typescript beginner tutorials on Pluralsight - it's free for 3 months with the VS Community registration.
https://app.pluralsight.com/library/courses/typescript/table-of-contents
I've also joined the Slack channel.
What I would appreciate knowing is getting the right tools in place to start exploring and learning and what order to build the knowledge. It looks like a big jigsaw puzzle to me at the moment, and I need to understand how all the pieces fit together.

**Comment by sayuga** [comment]
@javaman63 Any help is appreciated. I'm essentially working through it by writing it section by section. Do you want to take on the How-To guides? I've created a blank gitbook. I'll be adding the sections I've already translated as soon as I get a moment. I don't think gitbook currently allows forking or pull requests but I can add collaborators with a email address. you are welcome to Private Message me through slack and give me your address and I'll add you to the collaborators list.

**Comment by sayuga** [comment]
Hi all, I've started a couple Serenity Playlists on my Youtube. I'm going first through the tutorials on the manual showing all the steps on how to implement each section. Once I'm done with the tutorial I'll start running through the wiki. 

Here is the link: https://www.youtube.com/channel/UCHGyxXj-vI32YaRs0v3HvKw

**Comment by sayuga** [comment]
The set of videos for the Movie Tutorial are up and I've created a repository with the final version of the project used for the video so that other can reference. There is still some editing left and Captions to add but the videos should be able to be used alongside the Guide for now.

**Comment by volkanceylan** [comment]
Added link to Readme, thanks again @sayuga
