### ISSUE TITLE
TreeGrid: Order vs OrderDetails

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1886]
Hi guys,
someone has already managed to setup a TreeGrid with Order and OrderDetails tables?
In the example we have the same entity (Order) both parents and children, but I would like to show the details for each order (if any).
Any idea? 

Thanks!
Bye

**Comment by volkanceylan** [comment]
Sorry Marco but SlickGrid doesn't support what you aim.

**Comment by marcobisio** [comment]
No problem Volkan, thanks for your feedback!
Btw I achieved a suboptimal (but acceptable for me) result by using a view and by cheating with the ids...I'll post here in case anyone needs the same thing :-)

Bye!

**Comment by marcobisio** [comment]
Here we go:

1 - define the order tree view (nothing particularly smart: just cheating with the ids). Here we cannot use the trick of the calculated ids like the "View Without ID" sample, because treegrid would go crazy and would "break" at every grid refresh.

    CREATE VIEW [dbo].[OrderTreeView]
    AS
    SELECT 'H' + CONVERT(VARCHAR, OrderID) AS OrderTreeViewId
    	,OrderID
    	,CustomerID
    	,EmployeeID
    	,OrderDate
    	,RequiredDate
    	,ShippedDate
    	,NULL AS ParentId
    	,NULL AS ProductID
    	,NULL AS UnitPrice
    	,NULL AS Quantity
    	,NULL AS Discount
    FROM Orders
    
    UNION ALL
    
    SELECT 'D' + CONVERT(VARCHAR, d.DetailID) AS OrderTreeViewId
    	,h.OrderID
    	,h.CustomerID
    	,h.EmployeeID
    	,h.OrderDate
    	,h.RequiredDate
    	,h.ShippedDate
    	,'H' + CONVERT(VARCHAR, d.OrderID) AS ParentId
    	,d.ProductID
    	,d.UnitPrice
    	,d.Quantity
    	,d.Discount
    FROM Orders h
    RIGHT JOIN [Order Details] d ON h.OrderID = d.OrderID
    GO

2 - sergen the view above and manually set the the id field on the OrderTreeViewRow class:

    IIdField IIdRow.IdField
    {
        get { return Fields.OrderTreeViewId; }
    }

3 - in the OrderTreeViewGrid add the getIdProperty(), setup the TreeGridMixin, remove some buttons and add a toggle button in order to collapse/expand all items.
    
    namespace DueNoveCinque.Northwind {
    
    @Serenity.Decorators.registerClass()
    export class OrderTreeViewGrid extends Serenity.EntityGrid<OrderTreeViewRow, any> {
        protected getColumnsKey() { return 'Northwind.OrderTreeView'; }
        protected getDialogType() { return OrderTreeViewDialog; }
        protected getIdProperty() { return OrderTreeViewRow.idProperty; }
        protected getLocalTextPrefix() { return OrderTreeViewRow.localTextPrefix; }
        protected getService() { return OrderTreeViewService.baseUrl; }
    
        private treeMixin: Serenity.TreeGridMixin<Northwind.OrderTreeViewRow>;
    
        constructor(container: JQuery) {
            super(container);
    
            this.treeMixin = new Serenity.TreeGridMixin({
                grid: this,
                initialCollapse: () => true,
                toggleField: Northwind.OrderTreeViewRow.Fields.OrderID,
                getParentId: x => {
                    return x.ParentId;
                }
            });
        }
    
        protected usePager() {
            return false;
        }
    
        protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "column-picker-button"), 1);
    
            // toggle expand/collapse all
            buttons.push({
                title: null,
                hint: "Expand/Collapse All",
                cssClass: 'treegrid-toggle-expand-collapse-all',
    
                onClick: () => {
                    this.treeMixin.toggleAll();
                }
            });
    
            return buttons;
        }
    }
    }

4 - add the css class of the toggle button in the site.northwind.less and you're done

    .treegrid-toggle-expand-collapse-all span.button-inner {
        background-image: url(../serenity/images/node-select-all.png);
    }


And this is the result:

![image](https://cloud.githubusercontent.com/assets/17425690/22967476/e38a7e58-f366-11e6-8b79-cd9be4d3e6d4.png)


I know there are a ton of potential improvements, but that's all for now! 

Hope it helps!
Bye!

**Comment by marcobisio** [comment]
Just realized that the issue is closed :D
Volkan feel free to reopen if you think that can be useful to someone else! :-)

**Comment by volkanceylan** [comment]
Can you add that to wiki, think it can be useful, thanks

**Comment by marcobisio** [comment]
You're welcome :-)

**Comment by gowthamcarmel** [comment]
It didnt work for me

**Comment by gowthamcarmel** [comment]
Do i need to change in the form level
