### ISSUE TITLE
how to change caption format of dialog

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1889]
i changed the instance name but i need to change the format of caption of a dialog 
![image](https://cloud.githubusercontent.com/assets/7503623/22584864/6d8e769a-e9fd-11e6-8d62-81e1bacf6a35.png)
Edit <intance neme ><property>. Where should i look to change the whole format?

**Comment by Estrusco** [comment]
You can override updateTitle in your XYZDialog.ts

**Comment by satsokn** [comment]
where do i find XYZDialog.ts (is there any example)

**Comment by satsokn** [comment]
is it possible just to change only the atrribute of given format?

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serenity/issues/421 and https://github.com/volkanceylan/Serenity/issues/941 

```ts
namespace YourNamespace {

    @Serenity.Decorators.registerClass()
    export class XYZDialog extends Serenity.EntityDialog<XYZRow, any> {
        protected getFormKey() { return XYZForm.formKey; }
        protected getIdProperty() { return XYZRow.idProperty; }
        protected getLocalTextPrefix() { return XYZRow.localTextPrefix; }
        protected getNameProperty() { return XYZRow.nameProperty; }
        protected getService() { return XYZService.baseUrl; }

        constructor() {
            super();
        }
        
        protected updateTitle() {
            this.dialogTitle = "Your title ";
        }
```

**Comment by satsokn** [comment]
thanks a lot

**Comment by VictorTomaili** [comment]
create your own decorator for this.

**Comment by satsokn** [comment]
how do i access data inside dialog.ts ?

**Comment by volkanceylan** [comment]
this.entity
