### ISSUE TITLE
Node On Windows 7 32Bit

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#189]
after installing Serenity on a win7 32Bit and building the application for the first run it sows an error build in lessc.cmd after debugging the application build it appears that node in the tools folder is 64 bit replacing node with 32bit exe worked for build with no errors , any other issues might raise here ?

**Comment by volkanceylan** [comment]
No, i already replaced node in Serene with 32 bit version, will be in next update

**Comment by zerodev** [comment]
great product, waiting for updates :)
