### ISSUE TITLE
Read Only Quick Filter

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1892]
We can have a default value of quick filter by init method.

how can we fix that this value remains fixed and user is not allowed to change.

one way is to have this filter as read only and another can be to make it visible = false.

how can we achieve a constant filter which is fixed for a grid.

**Comment by volkanceylan** [comment]
Use SetEqualityFilter of grid and don't add a quick filter at all. Or set readonly using EditorUtils.setReadOnly etc.

**Comment by mrajalko** [comment]
thanks it worked.

**Comment by PedroHFranco** [comment]
Hello @volkanceylan ,
Could u give one example of SetEqualityFilter ?
