### ISSUE TITLE
QuickFilter based on the data in Grid

### ISSUE THREAD

**Issue by iuryamicussi** [volkanceylan/Serenity#1893]
I need that my quickfilter only presents the elements that already are in my Grid.
Example:
ID   |   Group   |   Description
1    |       2       |  One thing
2    |       4       |  Other thing
3    |      2        |  Another thing

And Group quickfilter only has two choices in the dropdown: 2,4. Knowing that my Group table has a lot more items than 2,4.

I'm trying here, if someone could help me. I really appreciate.
Thanks in advance.

**Comment by mrajalko** [comment]
quick filter is server side and therefore cannot be based on client side data.

**Comment by volkanceylan** [comment]
See City/Country filters in Northwind

**Comment by iuryamicussi** [comment]
Thanks @mrajalko and volkan.
@volkanceylan Just as a consideration, in the Customers option when I insert a new record with a new Country and City, they are not been inserted in the quickfilter so I need to reload the page.
Neverthless, your answer solved my problem.

**Comment by uwascan** [comment]
@iuryamicussi try 
```
Q.reloadLookup('lookupkey');
```
to reload the Lookup records after saving a new record

**Comment by fremar83** [comment]
Hi all, 
I have quite same issue : A good example is the Northwind Customer form, on oders Tab.
My selected customer (Alfreds Futterkiste) has 6 orders, 4 different employes got his orders. When we try to filter by employe, we don't have only those 4 employes but all Northwind employes. How can it be filtered to get only those 4 employes ?
![employe filter](https://user-images.githubusercontent.com/28645113/48561490-5de6c500-e8f0-11e8-995d-a3fa57036a8c.PNG)
Thank's
