### ISSUE TITLE
Only show hours and minutes in DateTimeEditor

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1894]
How show only hours and minutes in DateTimeEditor?

`     [DateTimeKind(DateTimeKind.Local), DateFormatter(DisplayFormat = "dd-MM-yyyy HH:mm.ss"), DisplayName("Actualizado"), DateTimeEditor]`

**Comment by volkanceylan** [comment]
DateTimeEditor doesn't support such. You may try hiding date editor with CSS but not sure if it will work.
