### ISSUE TITLE
Quick Filter removal does not reset the grid data

### ISSUE THREAD

**Issue by prasannavasan** [volkanceylan/Serenity#1895]
I am trying out the example demo in the website, When I remove the country filter before the city filter the grid does not seem to reset and show the records, Instead the filtered records are shown and it shows the filters are cleared in the header. (Northwind/Customer)

Demo Link - http://serenity.is/demo/Northwind/Customer

Steps - Add the Country and City Filters, Remove the Country Filter keeping the City Filter. I am expecting both the filters to be removed and the whole grid to be shown. The filters are removed as expected but the Grid data is populated with the filtered result set. Am I missing anything here? 

Thank you for this great framework again :)

**Comment by volkanceylan** [comment]
You need to attach to change event of country filter, clear the city when it gets cleared. Cascade is actually not supported for quick filters, so it might have such a side effect.

**Comment by volkanceylan** [comment]
I mean clear the city from EqualityFilter of grid.

**Comment by prasannavasan** [comment]
Hi Volkan,

Is there any sample change event scenario in the examples? I tried with "this.setEquality" in my class extending EntityGrid but it still did not allow me to reload the data. Am I missing something?

Thank you very much for your support.
Regards

**Comment by volkanceylan** [comment]
After set equality, call refresh

**Comment by prasannavasan** [comment]
Thank you very much,

quick clarification, what is the best way to track the change event of quick filter from ts side? For example to get the event when cleared "x" mark is clicked on the filter
