### ISSUE TITLE
Entity "Id" always Included into the query sort clause

### ISSUE THREAD

**Issue by diskman** [volkanceylan/Serenity#1897]
Hi,

I try to use 2.9.3 and I have generated Entity code based on sql server view. I have initialized sorting by some date column and I have disabled sorting on Id column. ListRequest object contains only one correct parameter for sorting but Sereneity somehow appends Id as secon parameter to sort cluase. On my profiler there is appended T0.[Id].

```
FROM [dbo].[vw_Contractors] T0 
ORDER BY T0.[pub_date] DESC, T0.[Id];
```

How to resolve that?

**Comment by volkanceylan** [comment]
ListHandler always add ID field to sort. Override ApplyKeyOrder and don't call base.

**Comment by diskman** [comment]
@volkanceylan much better now thanx 👍
