### ISSUE TITLE
HtmlContentEditor shows editor in different language

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#190]
Hi, I am using the HtmlContentEditor attribute on some of my fields. The editor that displays, does not show in my language (which now is set to English).

![htmlcontenteditor](https://cloud.githubusercontent.com/assets/7986251/12777206/009b3ee2-ca64-11e5-993f-5c8dda9d5f28.PNG)

**Comment by VictorTomaili** [comment]
Currently its not customizable. Try to create customized one from [there](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Script.UI/Editor/HtmlContentEditor.cs)

**Comment by VictorTomaili** [comment]
Create new class based on linked class. And override GetConfig, Dont forget class attributes.

**Comment by volkanceylan** [comment]
Will be using autodetect in next version
