### ISSUE TITLE
Edit/Update set [NotNull] String fields to empty

### ISSUE THREAD

**Issue by prasannavasan** [volkanceylan/Serenity#1900]
Is it possible to set the NotNull String type database columns to empty string when editing the records with empty values. This is to allow the fields to get updated with empty string when no value is entered respectively in the dialog rather than showing the below error message?

![image](https://cloud.githubusercontent.com/assets/8968433/22628265/07d0bea2-ebf7-11e6-8b45-bd968a7d59c7.png)

Thanks!

**Comment by Estrusco** [comment]
You can add DefaultValue("") attribute, and remove NotNull attribute. Also see here https://github.com/volkanceylan/Serenity/issues/739 for Trim

**Comment by volkanceylan** [comment]
Remove NotNull from property, or add Required(false), and also add [SetFieldFlags(FieldFlags.TrimToEmpty)]

**Comment by prasannavasan** [comment]
Thank you @volkanceylan . Works like a charm
