### ISSUE TITLE
Sergen error after updated

### ISSUE THREAD

**Issue by joheric** [volkanceylan/Serenity#1904]
`sergen : The term 'sergen' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ sergen
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (sergen:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by volkanceylan** [comment]
Try reading the guide

**Comment by joheric** [comment]
What guide?

**Comment by PedroHFranco** [comment]
What guide?

**Comment by gguadalupe** [comment]
The guide.... you know... guide... as in... La guia?

https://volkanceylan.gitbooks.io/serenity-guide/content/
Good stuff... I read it every night to my toddler... true story.

Gus
