### ISSUE TITLE
Using servicestack-client - how to install

### ISSUE THREAD

**Issue by diskman** [volkanceylan/Serenity#1905]
Hi, I would like to use on client side API generated by http://docs.servicestack.net/typescript-add-servicestack-reference. What is the proper way to include https://github.com/ServiceStack/servicestack-client into Serenity project?

**Comment by VictorTomaili** [comment]
you already send document for implementation. install typings and use it. Nothing diffrent from other typescript products.

**Comment by diskman** [comment]
@VictorTomaili could you send me some more details, I am just starting with typescript and I am not sure how to organize serenity project structure. I see that servicestack-client has several dependencies like isomorphic-fetch. I am not sure how to include that library into project.
