### ISSUE TITLE
Unable to display number with commas

### ISSUE THREAD

**Issue by imkheong** [volkanceylan/Serenity#1907]
Hi

I would like to show Int64 numbers with commas on the grid so that they can be easily 'digested'.

I tried to use the DisplayFormat attribute but to no avail.

>         [DisplayName("Committed"), DefaultValue(0), AlignRight, DisplayFormat("#,##0"), NotNull]
>         public Int64? CommittedVolume
>         {
>             get { return Fields.CommittedVolume[this]; }
>             set { Fields.CommittedVolume[this] = value; }
>         }

It is showing without commas.
![image](https://cloud.githubusercontent.com/assets/6950029/22675322/f58eadb0-ed1f-11e6-86c1-48b92f6e71a1.png)

What should I do to have it show with commas?

**Comment by imkheong** [comment]
Here is the RowFields class:

>         public class RowFields : RowFieldsBase
>         {
>             ...
>             public Int64Field CommittedVolume;
>             ...
>         }

**Comment by Dinesteine** [comment]
Hi imkheong
Override getColumns method in grid.ts. For example, go to https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/CustomLinksInGrid/CustomLinksInGrid.ts link.

**Comment by imkheong** [comment]
@Dinesteine

I expect an easy way by simply specifying the DisplayFormat as it is the usual way it is formatted in NorthWind sample.

**Comment by Estrusco** [comment]
You can write your own editor

**Comment by uwascan** [comment]
I think DisplayFormat("#,##0") is meant or Decimal or Double values. Consider changing your field type to decimal or double

**Comment by volkanceylan** [comment]
[DisplayFormat("#,##0."), NumberFormatter]

**Comment by imkheong** [comment]
As @volkanceylan rightly pointed out, it is the easiest way.

Thanks @volkanceylan and all who responded!
