### ISSUE TITLE
Inplace Create

### ISSUE THREAD

**Issue by emrebayrakdar** [volkanceylan/Serenity#1909]
Ana formumuz da inplace butonuyla açtığımız tanımlama ekranına parametre olarak herhangi değer set edebilir miyiz?
Örneğin : 
![image](https://cloud.githubusercontent.com/assets/10575455/22686265/15ba748c-ed2c-11e6-9cb3-923c78004300.png)

**Comment by volkanceylan** [comment]
xEditor.onInitNewEntity = x => x.SubeId = ...
