### ISSUE TITLE
Two row classes for one table DisplayName and InstanceName 

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1910]
if i have two row classes for a single table. the display name and instance name properties are being displayed as full class name.

I need to define two rows  as data being displayed are different in nature but reside in same table.

**Comment by mrajalko** [comment]
![image](https://cloud.githubusercontent.com/assets/18166582/22690139/42812ca8-ed5a-11e6-8068-7c404898dd8a.png)

**Comment by mrajalko** [comment]
![image](https://cloud.githubusercontent.com/assets/18166582/22690239/da96ef28-ed5a-11e6-9309-ff9d6159a8fc.png)

**Comment by volkanceylan** [comment]
Don't use two row classes, use two columns / forms

**Comment by mrajalko** [comment]
I need to show different data in grid therefore i have two grids

and one grid have this line

this.setEquality('VoucherTypeNature', 0);

another grid has

this.setEquality('VoucherTypeNature', 1);

how can i achieve this by using two columns / forms.

**Comment by volkanceylan** [comment]
You don't need two rows to have two different grids
