### ISSUE TITLE
How Can I get grid row value? - contextMenu

### ISSUE THREAD

**Issue by emrebayrakdar** [volkanceylan/Serenity#1911]
User open a context menu when right click on grid row. I could not get row value because grid rowclick event do not fired (expected). So How Can I get row value this case?

![image](https://cloud.githubusercontent.com/assets/10575455/22692799/4e7b9e8c-ed49-11e6-9d37-5a8b2ae194ab.png)

**Comment by volkanceylan** [comment]
SlickGrid getCellFromEvent might help but you need to check its docs, have no sample

**Comment by ayberkcal** [comment]
I am not a Serenity expert but if you can enable right click to row selection, you could get selected row value.
