### ISSUE TITLE
Blank Page Showing http://localhost:5974/Account/Login?ReturnUrl=%2f

### ISSUE THREAD

**Issue by BuiltRightTech** [volkanceylan/Serenity#1914]
Error list
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\tsc.exe" -project "C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\tsconfig.json"" exited with code 3.	BRT.Web	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\BRT.Web.csproj	2682	
Error	TS2304	Cannot find name 'Common'.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Modules\Default\Building\BuildingEditor.ts	7	Active
Error	TS4020	Extends clause of exported class 'BuildingEditor' has or is using private name 'Common'.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Modules\Default\Building\BuildingEditor.ts	7	Active
Error	TS6053	File 'C:/Users/Brent/documents/visual studio 2015/Projects/BRT/BRT/BRT.Web/Modules/Modules/Common/Helpers/GridEditorDialog.ts' not found.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Modules\Default\Building\BuildingEditorDialog.ts	2	Active
Error	TS2304	Cannot find name 'Common'.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Modules\Default\Building\BuildingEditorDialog.ts	8	Active
Error	TS4020	Extends clause of exported class 'BuildingEditorDialog' has or is using private name 'Common'.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Modules\Default\Building\BuildingEditorDialog.ts	8	Active
Error	TS2339	Property 'idPrefix' does not exist on type 'BuildingEditorDialog'.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Modules\Default\Building\BuildingEditorDialog.ts	11	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\node_modules\@types\toastr\index.d.ts	7	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Scripts\typings\serenity\Serenity.CoreLib.d.ts	1	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Scripts\typings\serenity\Serenity.CoreLib.d.ts	2	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Scripts\typings\serenity\Serenity.CoreLib.d.ts	3	Active
Error	TS1084	Invalid 'reference' directive syntax.	TypeScript Virtual Projects	C:\Users\Brent\documents\visual studio 2015\Projects\BRT\BRT\BRT.Web\Scripts\typings\serenity\Serenity.CoreLib.d.ts	4	Active

All these files where generated using the sengen

**Comment by volkanceylan** [comment]
Check your TS version, install VS updates, ....

**Comment by BuiltRightTech** [comment]
Visual studio is updated 14.0.25431.01 and typescript is at 2.1.5.0

Errors are gone just a lot of warnings

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Device/DeviceEditor.ts	7	
Warning		The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\tsc.exe" -project "C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\tsconfig.json"" exited with code 1.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\BRT.Web.csproj	2682	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Customer/CustomerEditor.ts	7	
Warning		Extends clause of exported class 'CustomerEditor' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Customer/CustomerEditor.ts	7	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Customer/CustomerEditorDialog.ts	8	
Warning		Extends clause of exported class 'CustomerEditorDialog' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Customer/CustomerEditorDialog.ts	8	
Warning		Property 'idPrefix' does not exist on type 'CustomerEditorDialog'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Customer/CustomerEditorDialog.ts	11	
Warning		Extends clause of exported class 'DeviceEditor' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Device/DeviceEditor.ts	7	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Device/DeviceEditorDialog.ts	8	
Warning		Extends clause of exported class 'DeviceEditorDialog' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Device/DeviceEditorDialog.ts	8	
Warning		Property 'idPrefix' does not exist on type 'DeviceEditorDialog'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Device/DeviceEditorDialog.ts	11	
Warning		Extends clause of exported class 'LocationEditor' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Location/LocationEditor.ts	7	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Location/LocationEditor.ts	7	
Warning		Extends clause of exported class 'LocationEditorDialog' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Location/LocationEditorDialog.ts	8	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Location/LocationEditorDialog.ts	8	
Warning		Property 'idPrefix' does not exist on type 'LocationEditorDialog'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/Location/LocationEditorDialog.ts	12	
Warning		Extends clause of exported class 'ServiceTicketEditor' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/ServiceTicket/ServiceTicketEditor.ts	7	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/ServiceTicket/ServiceTicketEditor.ts	7	
Warning		Extends clause of exported class 'ServiceTicketEditorDialog' has or is using private name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/ServiceTicket/ServiceTicketEditorDialog.ts	8	
Warning		Cannot find name 'Common'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/ServiceTicket/ServiceTicketEditorDialog.ts	8	
Warning		Property 'idPrefix' does not exist on type 'ServiceTicketEditorDialog'.	BRT.Web	C:\Users\Brent\Documents\Visual Studio 2015\Projects\BRT\BRT\BRT.Web\Modules/Default/ServiceTicket/ServiceTicketEditorDialog.ts	12

**Comment by BuiltRightTech** [comment]
Got it working had to add the project namespace to all the generated files

**Comment by paulobriennz** [comment]
sorry to sound dumb, but which files.. like the files that you generate with SERGEN.exe for a db table?

**Comment by volkanceylan** [comment]
I think i should be setting root namespace automatically to solution name, as users gets confused
