### ISSUE TITLE
Q.information

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1915]
Hi,
I've a problem with Q.information in IE only (other browsers are OK) the console error is "syntax error" and pointed to () =>

```

                    Q.information("Click ok to view your results",
                () =>{
                   Q.notifySuccess("Loading the results page");
                    window.location.href = Q.resolveUrl('~/Student/Reults');
                });

```

Is this because of my code? or it's known issue with IE?

**Comment by volkanceylan** [comment]
Are you writing this in javascript? If so IE 11 doesn't support arrow functions

**Comment by mhussein67** [comment]
Yes @volkanceylan it's a javascript code, I will convert to ts.

**Comment by volkanceylan** [comment]
You may also write, instead of () =>

```
function() {
                   Q.notifySuccess("Loading the results page");
                    window.location.href = Q.resolveUrl('~/Student/Reults');
                });
```
