### ISSUE TITLE
Limit Login Attempts

### ISSUE THREAD

**Issue by VinMilky** [volkanceylan/Serenity#1916]
Hi, I am trying to limit user's login attempts to 3, is there an easy solution for this. Thanks

**Comment by sayuga** [comment]
You'd probably want to add that behaviour on the loginpanel.ts You'll see how the onSuccess is managed . You can probably make it so that the else has a counter that, upon 3 attempts, locks the account

**Comment by volkanceylan** [comment]
Not login panel or any client side code. You should do it in AccountPage Login method

**Comment by VinMilky** [comment]
Thanks for the quick response, how do I lock the account, is there a specific method somewhere I can refer to? Thanks again

**Comment by volkanceylan** [comment]
There is an Active property on user row that might be used for this purpose.
