### ISSUE TITLE
Direct linking to a record

### ISSUE THREAD

**Issue by wirble** [volkanceylan/Serenity#1917]
How can I create a direct link to an item to show in the proper dialog?  I send an email out for notifications but I have yet able to figure out how to direct link to a item.  A user would have to search for the item and click on the link on the grid.  Is there a built in mechanism already that I don't know about?

Thanks

**Comment by adhikamafran** [comment]
try querystring that pass entityId, then in grid constructor if there's query string, open dialog based on entity id.

**Comment by edson** [comment]
see https://github.com/volkanceylan/Serenity/issues/663
works great.

A third option would be using dialog as panel and passing entityid by querystring, see basic samples...

Best Regards

**Comment by wirble** [comment]
Thanks all--I will try out suggestions.

**Comment by wirble** [comment]
I checked out #663 but it was too advanced for me, not sure where to put that typescript and a matter of routing also to achieve the entity/1.  I was able to get the panel method partially working from the basic samples.

I was able to achieve the same end results but I am sure it's not a good practice with below code in the 
xxxxentityGrid.ts file:

`        constructor(container: JQuery) {
            super(container);

            //add a querystring parser name 'id' to open the dialog to edit if it exist
            var id = this.getParameterByName('id', container[0].baseURI);
            if (id) {
                var diag = new InmateIncidentDialog();
                diag.loadByIdAndOpenDialog(id);
            }
            //end custome dialog

        }`

`//parse the querystring by name, took from stackoverflow QA
        protected getParameterByName(name, url) {
            if (!url) {
                url = window.location.href;
            }
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }`

**Comment by wirble** [comment]
Changed it to below from the Northwind orderpage sample instead of parsing with getParameterByName:

`var q = Q.parseQueryString();`

 `if (q.id) {`

`}`
