### ISSUE TITLE
Serenity Code Generator

### ISSUE THREAD

**Issue by BuiltRightTech** [volkanceylan/Serenity#1918]
The code generator is Missing the fields for Module Name, Connection key, Entity Identifier and permission key. And I missing something? Can't see files generated unless I choose show all file in solution explorer.

**Comment by williamhodges** [comment]
They're still there. When the list of table appear in the grid, double click on the field to the right of your table name to edit it

**Comment by volkanceylan** [comment]
Set csproj location properly

**Comment by BuiltRightTech** [comment]
OK I see them and that worked. But all the files that the sergen.exe generated are still hidden till I show all files and the folder icon and file icons are just a dotted line.

![eroor](https://cloud.githubusercontent.com/assets/20980197/22782897/d369a03a-ee8e-11e6-8709-d819a4b19269.jpg)

**Comment by volkanceylan** [comment]
Use include files in project.

**Comment by amrdipoo** [comment]
i have the same isuue just show 
webproject
Root NameSpace
connectionString
![Untitled](https://user-images.githubusercontent.com/33197980/175547526-6bf3d585-b305-447f-bea0-5ef944b3094d.png)

**Comment by amrdipoo** [comment]
@VictorTomaili  What is the currently supported version?

**Comment by VictorTomaili** [comment]
Current supported version is here https://www.nuget.org/packages/sergen/
For old projects, we suggest upgrading serenity to latest. If you still want to use old version, ensure about the project file location. I didn't remember well, but probably after choosing the connection string, you can change other options per table.

Please use discussions for questions.
