### ISSUE TITLE
Element can't perform events in other form

### ISSUE THREAD

**Issue by vietnguyen8392** [volkanceylan/Serenity#1919]
Hi @volkanceylan  and everyone,
I have a dialog with 2 forms in different tabs. The main form is placed in first tab, the second in second tab.
The dialog can retrives and save data from these forms. But the problem happens when I want to perform the event "change()" in any element in the form of second tab. How can I set the events for it?

**Comment by Estrusco** [comment]
See how the sample https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/OtherFormInTabOneBar/ gets an helper for form

```ts
    export class OtherFormOneBarDialog extends Northwind.OrderDialog {

        private customerPropertyGrid: Serenity.PropertyGrid;
        private customerForm: Northwind.CustomerForm;
        private customerValidator: JQueryValidation.Validator;
        private selfChange = 0;

        constructor() {
            super();

            // entity dialogs by default creates a property grid on element with ID "PropertyGrid".
            // here we explicitly create another, the customer property grid (vertical form) on element with ID "CustomerPropertyGrid".
            this.customerPropertyGrid = new Serenity.PropertyGrid(this.byId("CustomerPropertyGrid"), {
                items: Q.getForm(Northwind.CustomerForm.formKey).filter(x => x.name != 'CustomerID'),
                useCategories: true
            });

            // this is just a helper to access editors if needed
            this.customerForm = new Northwind.CustomerForm((this.customerPropertyGrid as any).idPrefix); 

```

**Comment by vietnguyen8392** [comment]
@Estrusco Thanks for your help. I read and my code followed the sample you showed. The problem here is that when I set an event for an element in other form, it didn't work. Even the dialog didn't work too. For example, I set event for this:
```

this.secondform.CategoryId.change(e=>{
});
```
``

**Comment by Estrusco** [comment]
It seems that there isn't a lookup object. Have you make T4 transform? Insert LookupInclude in field? You have to post your code
