### ISSUE TITLE
field validation; cosmetic; red "x" behind field does not get cleared when correcting data and not yet move out of field

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#192]
Hi JaiQ,

John Ranger here again. :-)

Although this is only cosmetic, I allow myself to bring it up here:

When in a field with "Validation active" some wrong data is entered and then the Focus changed to another field (and Validation warning is displayed with a red "x" and red Background of field) and then the data in the field with "Validation active" is corrected to a valid value,

the Background of the field is immediately changed from red to normal but the red "x" is still displayed until the focus is moved to another field.

From my perspective, it would be more intuitive (more clear) for the end user when the red "x" would also immediately disappear together with the red Background of the field when Validation is successful.

What do you think regarding my proposal and is this something you could integrate in one of the future Version of Serenity? (or is there a workarround)

Thanks for your valuable Feedback

and with Kind regards,

John

**Comment by volkanceylan** [comment]
It was working that way. Probably happened after jQuery validate update. Will check.

**Comment by volkanceylan** [comment]
Hello John,

I tried but can't reproduce this. Can you give more info about what is Serenity / Serene version, browser and editor types in form etc.

**Comment by volkanceylan** [comment]
@JohnRanger reopen with more info please

**Comment by JohnRanger** [comment]
Hi JaiQ,

sorry, have seen only now that you wanted more Infos.

Serene-based app, done with V1.9.9, now upgraded to V1.9.13.

This happens with the following Browsers:

- IE 11 (on Windows 8.1)
- Forefox 44.0.2

(Also with a Chrome  version in our Company but I don't know the version).

The field is defined in xyzRow.cs like this:

```cs
        [DisplayName("Db.Staging.ClientStaging.InventoryLabel"), Size(6)]
        [Required(true)]
        public String InventoryLabel
        {
            get { return Fields.InventoryLabel[this]; }
            set { Fields.InventoryLabel[this] = value; }
        }
```

In xyzDialog.cs, in the constructor, I have the following for the Validation:
```cs

            var ValidationText = new LocalText("Forms.Staging.ClientStaging.Validation.InventoryLabel.Wrong").ToLocaleString();

            // *** Define validation for InventoryLabel field ***
            Regex regex = new Regex(@"^\d{6}$");
            form.InventoryLabel.AddValidationRule(this.uniqueName, e =>
            {
                if (regex.Test(form.InventoryLabel.Value))
                {
                    return null;
                }
                else
                {
                    return ValidationText;
                }

                //return regex.Test(form.InventoryLabel.Value) ? null : "Inventory must be exactly 6 DIGITS long (e.g. 123456)"; // *** Does exactly the same as the above IF-then-else structure ***
            });
```

With Kind regards,

John

**Comment by volkanceylan** [comment]
Does this only happen on this field? Or all?

**Comment by JohnRanger** [comment]
Hmm, 

I have only this one field with a specific Validation in place.

The rest are all strings - or integer controlled by a lookupeditor so no wrong values can be entered there.

I will test this within the next two weeks and provide Feedback here.

With Kind regards,

John
