### ISSUE TITLE
'Sergen' is not working properly:showing error

### ISSUE THREAD

**Issue by vipinkrmishra** [volkanceylan/Serenity#1920]
The term 'sergen' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was incl
uded, verify that the path is correct and try again.
At line:1 char:7

sergen <<<<
CategoryInfo : ObjectNotFound: (sergen:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException

**Comment by vipinkrmishra** [comment]
![sergen error](https://cloud.githubusercontent.com/assets/25637763/22772324/07cf8848-eec2-11e6-8fe1-935068945294.PNG)

**Comment by WasimAhmad** [comment]
if you are having this problem after update to 2.9.3. Then you can resolve is it by these simple steps

1. GO you project\packages\Serenity.CodeGenerator.2.9.3\tools\net45
2. copy all files at one level up.. project\packages\Serenity.CodeGenerator.2.9.3\tools

it worked for me..

**Comment by WasimAhmad** [comment]
proper solution is to amend the sergen exe path.. i was unable to find the path config file...

**Comment by volkanceylan** [comment]
Its nuget bug, stated in docs, troubleshooting and 100 issues before. Please do some search before opening.

**Comment by Itsathere** [comment]
I am using ASP.NET Core and facing the same issue 

> sergen : The term 'sergen' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ sergen
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (sergen:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Itsathere** [comment]
Able to resolve it by insalling package Serenity.CodeGenerator but got another error related to merging "Could not locate Kdiff3 utility which is required to merge chnages. Now, I have installed Kdiff3 package but still have same issue.

**Comment by shivanandkhatte** [comment]
> 

done
