### ISSUE TITLE
while compiling webpage ,getting lots of warnings . Geting blank page when execute the page .

### ISSUE THREAD

**Issue by vipinkrmishra** [volkanceylan/Serenity#1921]

**Comment by vipinkrmishra** [comment]
![typescriptimg](https://cloud.githubusercontent.com/assets/25637763/22772241/920688b4-eec1-11e6-9f89-c2b266a3dd1e.PNG)
![visual studio img](https://cloud.githubusercontent.com/assets/25637763/22772240/9204c5e2-eec1-11e6-8a2d-b14ee0599f50.PNG)

**Comment by vipinkrmishra** [comment]
I am lot of warnings as following during compilation - 
1>E:\SerenityDemo\seregentyDemo\seregentyDemo\seregentyDemo.Web\Imports/ServerTypings/Administration.LanguageService.ts(5,169): warning TS2304: Cannot find name 'JQueryXHR'.
1>  
1>E:\SerenityDemo\seregentyDemo\seregentyDemo\seregentyDemo.Web\Imports/ServerTypings/Administration.LanguageService.ts(5,169): warning TS4060: Return type of exported function has or is using private name 'JQueryXHR'.
1>  
1>E:\SerenityDemo\seregentyDemo\seregentyDemo\seregentyDemo.Web\Imports/ServerTypings/Administration.LanguageService.ts(6,169): warning TS2304: Cannot find name 'JQueryXHR'.
1>  
1>E:\SerenityDemo\seregentyDemo\seregentyDemo\seregentyDemo.Web\Imports/ServerTypings/Administration.LanguageService.ts(6,169): warning TS4060: Return type of exported function has or is using private name 'JQueryXHR'.
1>  
1>E:\SerenityDemo\seregentyDemo\seregentyDemo\seregentyDemo.Web\Imports/ServerTypings/Administration.LanguageService.ts(7,160): warning TS2304: Cannot find name 'JQueryXHR'.
1>  
1>E:\SerenityDemo\seregentyDemo\seregentyDemo\seregentyDemo.Web\Imports/ServerTypings/Administration.LanguageService.ts(7,160): warning TS4060: Return type of exported function has or is using private name 'JQueryXHR'.

please help. just downloaded latest serenity from visual studio market place and flow the steps written in guide. but that is not working.

**Comment by paulobriennz** [comment]
Yes same, I downloaded brand new template a few days ago and got blank login script.. ive downloaded and executed a few times before with no issue.. just tried latest version via VS and I am getting these errors too.. have downloaded the latest TypeScript for VS2015 - 2.1.5.0

**Comment by volkanceylan** [comment]
TS 2.1 + NPM all is stated in readme

**Comment by JohnBurgin** [comment]
I had the same issue with the template.  Followed the welcome page and made sure TS 2.1.5, Node and NPM were installed and the path to Node was correct in the VS options. The solution builds (with many typescript warnings) but runs ok.  From hunting around, looks like the .d.ts TypeScript definitions arn't in the template any more under Scripts/typings.  Can see them though in the github version of MovieTutorial.

Noticed the current template also has a new package.json file with the missing definitions defined as dependancies. 

`{
  "name": "serene.web",
  "version": "1.0.0",
  "description": "MovieTutorial",
  "main": "index.js",
  "dependencies": {
    "@types/jquery": "^2.0.39",
    "@types/jquery.blockui": "0.0.27",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jquery.validation": "^1.13.32",
    "@types/jqueryui": "^1.11.32",
    "@types/jspdf": "^1.1.31",
    "@types/sortablejs": "^1.3.31",
    "@types/toastr": "^2.1.32"
  },
  "devDependencies": {},
  "scripts": {
  },
  "author": "",
  "license": "ISC"
}`

I'm new to TypeScript but found a post about restoring the .d.ts files from the packages.json which fixed the issue for me. In VS from the solution explorer right clicking on the file package.json and select "Restore Packages". This created a node_modules directory and downloaded the required .d.ts files. Think for this to work the VS extension "Web Extension Pack 2015" needs to be installed:  https://visualstudiogallery.msdn.microsoft.com/f3b504c6-0095-42f1-a989-51d5fc2a8459 

Other option is from the command line.  Navigate to the location of package.json (e.g. for the Movie Tutorial it was under MovieTutorial\MovieTutorial\MovieTutorial.Web) and run "npm install"

Not sure if this is the correct way, but worked for me.

**Comment by vipinkrmishra** [comment]
Thanks for your Guidance .

Appreciate your support !!
