### ISSUE TITLE
How to Combo Filter on dialog 

### ISSUE THREAD

**Issue by Duhano** [volkanceylan/Serenity#1922]
İyi çalışmalar

Yeni açtığım dialogda combo içerisinde o formun türüne göre datasını getirmem gerekiyor, lookup ile sorunumu çözemedim, acaba başka nasıl bir çözüm üretebilirim ? 

![image](https://cloud.githubusercontent.com/assets/24972168/22772951/4759a774-eea8-11e6-99bd-460b43d9e086.png)

![image](https://cloud.githubusercontent.com/assets/24972168/22772987/6a28429c-eea8-11e6-9a9e-1ba56518749e.png)

**Comment by VictorTomaili** [comment]
biraz daha detaylandırabilir misin? Ad alanı seçildiğinde alttaki doldurulması gereken alanlar mı değişmesini istiyorsun?

**Comment by Duhano** [comment]
Hayır, İlk resimdeki alış ve satış bölümlerim var, açılan dialog ise ikisinin ortak formu ve ad alanında hem alış hemde satış dataları geliyor. ben onun türüne göre datayı filtre etmek istiyorum

**Comment by VictorTomaili** [comment]
2 adet custom lookup oluştur. ayrıca 2 ayrı dialog yap. Aynı entity den oluşturulmasında sakınca olmaz aynı servisi de kullanabilir. Lookup lar filtrelenmiş olarak gelecekleri için ve dialogların kendi formunda tanımlanmış olacakları için ikisi de kendine özgü ekranlara sahip olacaklar. İleride istediğin ekrana diğerinden bağımsız özellikler katabiliyor olursun.

**Comment by Duhano** [comment]
Çözümünüz için teşekkürler gayet güzel fakat projemizde bu tip ekranlar çok fazla ve her türlü değişiklik de her iki ekranda da yönetmemiz bizim işimizi zorlaştırır. Bizim tek dialog üzerinden çözüm üretebilmemiz gerekiyor

**Comment by VictorTomaili** [comment]
Bu durumda grid de dialog açma butonunu override etmeniz gerekiyor. Dialog açarken entity ile beraber yollayıp dialog tipini entity den okumanız gerekmekte. Ardından ad alanının lookup keyini değiştirip, custom oluşturulan filtreli lookup keyi yapmanız gerekiyor. Yada ona benzer birşey. 

Serene projesini inceleyip benzer kod örneklerini bulup toparlayabilirsiniz. İstediğinizi yapmaya yetecek örnek olduğunu düşünüyorum.

**Comment by volkanceylan** [comment]
Bunun için örnekler var biraz araştırınız
