### ISSUE TITLE
New solution from current Template had many typescript compilation and intellisense warnings

### ISSUE THREAD

**Issue by JohnBurgin** [volkanceylan/Serenity#1925]
Originally replied to #1921 but then noticed it was closed.

After creating a new solution from the Serenity MVC Templete, followed the welcome page and made sure TS 2.1.5, Node and NPM were installed and the path to Node was correct in the VS options. The solution builds (with many typescript warnings) but runs ok.  From hunting around, looks like the .d.ts TypeScript definitions arn't in the template any more under Scripts/typings.  Can see them though in the github version of MovieTutorial.

Noticed the current template also has a package.json file with the missing definitions defined as dependancies. 

`{
  "name": "serene.web",
  "version": "1.0.0",
  "description": "MovieTutorial",
  "main": "index.js",
  "dependencies": {
    "@types/jquery": "^2.0.39",
    "@types/jquery.blockui": "0.0.27",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jquery.validation": "^1.13.32",
    "@types/jqueryui": "^1.11.32",
    "@types/jspdf": "^1.1.31",
    "@types/sortablejs": "^1.3.31",
    "@types/toastr": "^2.1.32"
  },
  "devDependencies": {},
  "scripts": {
  },
  "author": "",
  "license": "ISC"
}`

I'm new to TypeScript and Serenity but found a post about restoring the .d.ts files from the packages.json which fixed the issue for me. In VS from the solution explorer right clicking on the file package.json and select "Restore Packages". This created a node_modules directory and downloaded the required .d.ts files. Think for this to work the VS extension "Web Extension Pack 2015" needs to be installed:  https://visualstudiogallery.msdn.microsoft.com/f3b504c6-0095-42f1-a989-51d5fc2a8459 

Other option is from the command line.  Navigate to the location of package.json (e.g. for the Movie Tutorial it was under MovieTutorial\MovieTutorial\MovieTutorial.Web) and run "npm install"

Not sure if this is the correct way, but worked for me.

**Comment by volkanceylan** [comment]
Normally, with VS2015, it should restore these packages at template creation. I don't have the extension you suggested, but probably some other update (VS2015 update 3 maybe), or .Net Core SDK is enabling this feature. I guess you have VS2013 right?

Anyway, i added "npm install" to CSPROJ to "BeforeBuild" step in latest template for those who might be having same issue. Still you need correct version of Node/NPM though.

Thanks for reporting.

**Comment by JohnBurgin** [comment]
Thanks for the change.  I'm using VS2015 with Update 3, but don't have the .NET Core SDK.
