### ISSUE TITLE
Editör Validateentity

### ISSUE THREAD

**Issue by smallnatre** [volkanceylan/Serenity#1926]
Örneklerde bulunan şipariş editör gibi bir editörüm var. validateentity yapmak istediğimde listedeki id alanı bende undefined gelmekte. Örneklerde çalışıyor bütün karşılaştırmaları yaptıysamda bir türlü listedeki id alanı alamadım. sebebi ne olabilir acaba.

        validateEntity(row, id) {
            row.MuhasebeId = Q.toId(row.MuhasebeId);
             
            var MuhasebeKart = Q.tryFirst(this.view.getItems(), x => x.MuhasebeId === row.MuhasebeId);
            if  (MuhasebeKart && this.id(MuhasebeKart) !== id) {
                Q.alert(MuhasebeKart.MuhasebeAd+ ' hesabına ait fiş hareketi mevcut !');
                return false;
            }

            row.MuhasebeKod = TanimKartMuhasebeRow.getLookup().itemById[row.MuhasebeId].Kod;
            row.MuhasebeAd = TanimKartMuhasebeRow.getLookup().itemById[row.MuhasebeId].Ad;
            row.MasrafAd = TanimMasrafMerkeziRow.getLookup().itemById[row.MasrafMerkezId].Ad;
            return true;
        }

kodum bu şekilde.

**Comment by volkanceylan** [comment]
Yazdığınız koddan ilk satıra neden MuhasebeId null gelir anlamak mümkün değil malesef.
