### ISSUE TITLE
Create button to copy a record in other entity

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#1929]
Hello Friends!

I have the following scenery, i have a entity called Quotes, when the customers accepts the Quote, i need with a button in the grid copy or insert the QuoteID for the accepted Quote in other entity or table called Orders.

Please help me with this issue or please indicate me if exist any example similar to this scenery.

Thanks for your help.

Best Regards!

Andres

**Comment by VirtualHome** [comment]
Hello Friends, 

My advance in this issue:

- I create a InlineActionGrid button in QuotesGrid and this button calls a Service.

But we need that this service clones or copy the row information of the Quote in a new entity called Orders, how can insert the information of the first entity (Quotes) in the second entity (Orders)?

Please any approach to solve this scenery? Thanks in advance for your help.

Best Regards!

Andres

**Comment by volkanceylan** [comment]
See connection extensions or call retrieve get your entity copy data as you like.
