### ISSUE TITLE
Error when querying lookup table

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#193]
Hi, I am trying to get a dropdown field for a foreign key reference on my form. I followed the instructions in the guide (p74 ff), but when I query it with q.getLookup(Researcher.Publisher), I get the following error:

Script data Lookup.Researcher.Publisher is not found in registered script list

What am I doing wrong?

**Comment by VictorTomaili** [comment]
You need add lookup attribute on publisher row for auto register.

**Comment by wpvking** [comment]
I have the following on the PublisherRow class:

![image](https://cloud.githubusercontent.com/assets/7986251/12784954/badf425c-ca92-11e5-9f39-d5b743c3a7b7.png)

Still not working.

**Comment by VictorTomaili** [comment]
typo fix `Reasercher` => `Researcher`

**Comment by wpvking** [comment]
Thanks! Did not spot that. It works.

**Comment by VictorTomaili** [comment]
Np :smile: extra two eyes always better
