### ISSUE TITLE
Slickgrid; Call function within plugin; Converting from Saltarelle to typescript

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#1930]
Good morning JaiQ/Volkan,

I am currently trying to convert a specific Action from Saltarelle to typescript.

Actually, I want the Autocolumnsize Slick plugin to work with current Serenity Framework. 

So far I was able to fix the plugin itself so that it works with current Serenity Framework (see the last comments over here: [https://github.com/volkanceylan/Serenity/issues/447](url)

Now Comes the conversion of the Action that after the grid has just loaded, the resizeAllColumns() function within the plugin should be called.

In Saltarelle, we could do the following (xyzGrid.cs):

```cs
private SlickAutoColumnSize autoSize;

        protected override SlickGrid CreateSlickGrid()
        {
            //return base.CreateSlickGrid();

            var grid = base.CreateSlickGrid();
            autoSize = new SlickAutoColumnSize();
            grid.RegisterPlugin(autoSize);
            return grid;
        }

        protected override void MarkupReady()
        {
            base.MarkupReady();
            if (autoSize != null)
            {
                autoSize.As<dynamic>().resizeAllColumns();
            }
        }
```

How can this be done within typescript? I have tried several things but somehow I don't get access to the resizeAllColumns() function.

I have in the xyzGrid.ts the following:

```ts
protected createSlickGrid(): Slick.Grid {
            let grid = super.createSlickGrid();

            this.autoSize = new Slick.AutoColumnSize();
            grid.registerPlugin(this.autoSize);

            return grid;
        }

```
This makes the plugin load properly and also Register and it can be used by clicking between two column Header and it will autoresize the left column.

But I am missing the MarkupReady hook (for when the page is loaded and ready) and also I am not able to access  the resizeAllColumns() function within the plugin.

May I kindly ask to point me into the right direction?

Thanks for your feedback and

with Kind regards,

John

**Comment by volkanceylan** [comment]
```ts
protected void markupReady() {
    super.markupReady();
    this.autoSize && (this.autoSize as any).resizeAllColumns();
}
```

I kindly recommend reading TypeScript official tutorial

**Comment by JohnRanger** [comment]
Good evening JaiQ,

thanks for your valuable help. That works fine.

P.S: I did read may way through the Typescript documentation and did some basic tutorials but it is the Connection between Typescript, the DOM and the Serenity Framework which makes the Thing so difficult for me and where expert knowhow in every field is required :-)

Thanks again. When all works fine I will add the proper solution to your Wiki. Ok for you?

With kind regards,

John
Somehow, Saltarelle was a more abstracted way
