### ISSUE TITLE
build

### ISSUE THREAD

**Issue by postonoh** [volkanceylan/Serenity#1931]
Getting the following error message
![capture](https://cloud.githubusercontent.com/assets/1761420/22854196/e9339dc2-f036-11e6-8038-2db044caae5f.PNG)

npm ERR! cwd L:\Serenity-master\Serenity.TypeScript.CoreLib
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code E404
npm http 404 https://registry.npmjs.org/types/jqueryui
npm http 404 https://registry.npmjs.org/types/jquery.validation
npm http 404 https://registry.npmjs.org/types/sortablejs
npm http 404 https://registry.npmjs.org/types/toastr
npm http 404 https://registry.npmjs.org/types/jquery.blockui
npm http 404 https://registry.npmjs.org/types/jquery.cookie
npm

====npm command completed with exit code 1====

**Comment by volkanceylan** [comment]
Try updating your Node / NPM, info is in Welcome.htm.
