### ISSUE TITLE
Reload the grid manually when you clear a filter

### ISSUE THREAD

**Issue by prasannavasan** [volkanceylan/Serenity#1933]
Is there a possibility to manually load the grid data (refresh/reload without filters) when we clear a filter off?

![image](https://cloud.githubusercontent.com/assets/8968433/22856670/fe64b926-f0bb-11e6-9848-5d980451f753.png)

Thanks

**Comment by volkanceylan** [comment]
It refreshes / reloads when filters are cleared. Your issue is about cascading, which is not actually supported for quick filters. Attach to change event and clear the city filter when it is cleared.
