### ISSUE TITLE
condition formating image

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1934]
is it possible in condition formating when value is 0 to display an image instead of changing colour?
i applied class 
```
 .zero-price .col-unit-price{
        background-image:url("~\App_Data\oos.jpg");
    }
```
but didn't work. 
is it possible to display image in grid?

**Comment by edson** [comment]
See formatter as in http://serenity.is/demo/BasicSamples/InlineImageInGrid

Best Regards

**Comment by satsokn** [comment]
thanks a lot
