### ISSUE TITLE
How to properly apply DateTimeKind attribute?

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#1935]
john20xdoe [5:59 PM] 
Hi can anyone explain how the `[DateTimeKind]` attribute works?
I followed this https://github.com/volkanceylan/Serenity/issues/970 and applied it as Utc to my DateTime field in a row.

The effect is as follows, after *deployment to cloud server, which provides UTC value by default*:
1. No attribute set -> the field stores UTC. reflects physically as Utc in database and in Form.
2. `DateTimeKind.Utc` applied -> the field stores our local time (+8). how it does this, I have no idea as the server should have no way to know which zone to apply?. reflects physically as Local time (Utc + 8 value) in database and in Form.
3. `DateTimeKind.Local` applied -> same effect as # 2. So what's the difference :grey_question:

**What I would like to implement is the value stored physically in db should be UTC while the one displayed in grid or form is Localized time. Am I doing it wrong? Hopefull be able to do this in less code as possible (like simply using an attribute above)**

(I also checked the code at https://github.com/volkanceylan/Serenity/blob/ccac54404309bdb1317373f80ddb6f4760389b2b/Serenity.Data.Entity/FieldTypes/DateTimeField.cs)

**Comment by volkanceylan** [comment]
When not set, field is supposed to have "Date" type not "DateTime" type. 

DateTimeKind.UTC is correct for UTC date/time storage, and it shows local time in browser.

DateTimeKind.Local is for local non-translated date/time storage, but i think there might be an issue with it that i noticed lately.

**Comment by john20xdoe** [comment]
thanks @volkanceylan 

will experiment further with the field as `Date` and update this thread if successful. I'll also update and reopen this with more observations about `.Local`, if I find some more.

**Comment by john20xdoe** [comment]
we were still using Serenity 2.4.* so our workaround may not be important (we created our own localdate formatter). I noticed Volkan had committed some code related to DateTimeKind, so it may have been fixed in later versions of Serenity. Please use the latest version of Serenity/Serene.
