### ISSUE TITLE
LinkingSetRelation n Tane Parametre Geçmek

### ISSUE THREAD

**Issue by emrebayrakdar** [volkanceylan/Serenity#1936]
Şuana kadar multiselect'lerin her birisini ayrı tablolara yazıyordum şu şekilde;
![image](https://cloud.githubusercontent.com/assets/10575455/22928735/ab9882fc-f2c0-11e6-8036-bca735a31872.png)

Her multiselect tablom için ayrı ayrı tablo yapıyordum, fakat kirliliğe yol açtığından tek tabloda toplamak istedim. Tablomun yapısı şu şekilde;
![image](https://cloud.githubusercontent.com/assets/10575455/22928765/c85c1106-f2c0-11e6-9c34-124737b72a5e.png)

xyzRow.cs  içerisi
`  [LookupEditor(typeof(ParametreSektorRow), InplaceAdd = true, Multiple = true), ClientSide, DisplayName("Sektörler")]
        [LinkingSetRelation(typeof(TanimKartSektorRow), "**KartId**", "**SektorId**")]
        [MinSelectLevel(SelectLevel.Details)]
        public List<Int32> Sektorler
        {
            get { return Fields.Sektorler[this]; }
            set { Fields.Sektorler[this] = value; }
        }`

Fakat LinkingSetRelation attribute içerisine baktığımda 
 [LinkingSetRelation(typeof(TanimKartSektorRow), "**KartId**", "**SektorId**")] sadece 2 parametre geçebiliyorum. Fakat benim EntityType, EntityId,DetayEntity,DetayId parametrelerini attribute içerisine geçmem gerekiyor. veya izleyebileceğim farklı bir yol mevcut mudur? @volkanceylan

**Comment by volkanceylan** [comment]
LinkingSetRelation bu kadar çok parametre geçiremez. MasterDetailRelation kullanın ya da LinkingSet i örnek alıp kendiniz yazın.
