### ISSUE TITLE
Last Inserted SQL

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#1939]
Hello!

Please confirm if Serenity allows to excute the following query? Is correct build? Because when try to execute generates a exception. 

`var m = OrdersRow.Fields;`
`               SqlQuery query = new SqlQuery();`
            `query.Select("IDENT_CURRENT('Orders')")`
                `.From(OrdersRow.Fields);`

`LastRec= (Int32)connection.Query<OrdersRow>(query).FirstOrDefault();`

The idea with this code is obtain the last IdentityID of the entity Orders.

Please your important comments.

Best Regards!

Andres

**Comment by volkanceylan** [comment]
How are you trying to cast a OrdersRow to a Int32 value? Have a look at LINQ / Dapper.
