### ISSUE TITLE
First Run Windows 10 /Vs 2015 Community edition breaks/SQL EXp

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#194]
First Run Windows 10 /Vs 2015 Community edition breaks only change made is the SQl Express insted of localDB
error:
Unhandled exception at line 645, column 4 in http://localhost:57874/Scripts/Serenity/Serenity.Script.Core.js?v=fe93Kc3-TVjk7Btvymduuw2

0x800a139e - JavaScript runtime error: Script data Template.LoginPanel is not found in registered script list!

login page blank

**Comment by volkanceylan** [comment]
Are you using IIS express or development server

**Comment by zerodev** [comment]
IIS express

**Comment by volkanceylan** [comment]
Please rebuild solution and share what error you got with dynjs.axd in chrome request log

**Comment by zerodev** [comment]
this what i got in developer tools    
Uncaught Script data Template.LoginPanel is not found in registered script list!

and if tell me how to do so it would be great

**Comment by volkanceylan** [comment]
You need to check network tab for request that calls dynjs.axd, watch for something with Template.Bundle

**Comment by volkanceylan** [comment]
Or while app running, open a new tab and type this address:

http://localhost:55555/DynJS.axd/TemplateBundle.js

replace 55555 with your port number

**Comment by zerodev** [comment]
![image](https://cloud.githubusercontent.com/assets/728937/12793585/fbc9d79c-cab9-11e5-9c66-61288d4821d0.png)

this the image i got when i run 

and all DynJS.axd/ as below with 200 resonse
<script src="/DynJS.axd/LocalText.Site.en.Public.js?v=JEO5yOt4Veqd3yZma4gXYA2"></script>
<script src="/DynJS.axd/ColumnsBundle.js?v=fA96gAJ8l4nrCp1ZIYdQxA2"></script>
<script src="/DynJS.axd/FormBundle.js?v=SY0srev4CiW0rDGso9AxZw2"></script>
<script src="/DynJS.axd/TemplateBundle.js?v=XN2T2qV8ty-pkP_LxVjGFg2"></script>
<script src="/DynJS.axd/RegisteredScripts.js?v=J4dQkNUVFZj9A4oIxEe81w2"></script>




response from TemplateBundle.js

Q$ScriptData.set('Template.EntityDialog', '<div class="s-DialogContent">\r\n    <div id="~_Toolbar" class="s-DialogToolbar">\r\n    <\/div>\r\n    <div class="s-Form">\r\n        <form id="~_Form" action="">\r\n            <div class="fieldset ui-widget ui-widget-content ui-corner-all">\r\n                <div id="~_PropertyGrid"><\/div>\r\n                <div class="clear"><\/div>\r\n            <\/div>\r\n        <\/form> \r\n    <\/div>\r\n<\/div>')


Q$ScriptData.set('Template.PropertyDialog', '<div>\r\n    <div class="s-Form">\r\n        <form id="~_Form" action="">\r\n            <div class="fieldset ui-widget ui-widget-content ui-corner-all">\r\n                <div id="~_PropertyGrid"><\/div>\r\n                <div class="clear"><\/div>\r\n            <\/div>\r\n        <\/form> \r\n    <\/div>\r\n<\/div>')


Q$ScriptData.set('Template.CustomerDialog', '<div id="~_Tabs" class="s-DialogContent">\r\n    <ul>\r\n        <li><a href="#~_TabInfo"><span>{{text:"Db.Northwind.Customer.EntitySingular"}}<\/span><\/a><\/li>\r\n        <li><a href="#~_TabNotes"><span>{{text:"Db.Northwind.Note.EntityPlural"}}<\/span><\/a><\/li>\r\n        <li><a href="#~_TabOrders"><span>{{text:"Db.Northwind.Order.EntityPlural"}}<\/span><\/a><\/li>\r\n    <\/ul>\r\n    <div id="~_TabInfo" class="tab-pane s-TabInfo">\r\n        <div id="~_Toolbar" class="s-DialogToolbar">\r\n        <\/div>\r\n        <div class="s-Form">\r\n            <form id="~_Form" action="">\r\n                <div class="fieldset ui-widget ui-widget-content ui-corner-all">\r\n                    <div id="~_PropertyGrid"><\/div>\r\n                    <div class="clear"><\/div>\r\n                <\/div>\r\n            <\/form>\r\n        <\/div>\r\n    <\/div>\r\n    <div id="~_TabNotes" class="tab-pane s-TabNotes">\r\n    <\/div>\r\n    <div id="~_TabOrders" class="tab-pane s-TabOrders">\r\n        <div id="~_OrdersGrid">\r\n        <\/div>\r\n    <\/div>\r\n<\/div>')

**Comment by volkanceylan** [comment]
I'm running out of guesses.

Does typing 
$('script#Template_Membership_LoginPanel')

return any result in chrome console?

Maybe you should try creating a new project.

**Comment by zerodev** [comment]
runing script return this

`
<div>
    <h3>Welcome to SERENE (Serenity Application Template)</h3>
    <form id="~_Form" action="">
        <div class="s-Form">
            <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                <div id="~_PropertyGrid"></div>
                <div class="clear"></div>
            </div>
            <div class="buttons">
                <button id="~_LoginButton" type="submit" class="btn btn-primary">
                    Sign In
                </button>
                <a href="/Account/ForgotPassword">forgot password?</a>
                <a class="clear" href="/Account/SignUp">register a new account</a>
            </div>
        </div>
    </form>
</div>`

**Comment by zerodev** [comment]
will try fresh installation

**Comment by zerodev** [comment]
very strange after 2 fresh installations it worked, could it be the name of the project ? i hade it with a XXX.XXX with the dot

**Comment by volkanceylan** [comment]
Yes thats it
