### ISSUE TITLE
Sergen can't work when using Oracle (Oracle.ManagedDataAccess.Client)

### ISSUE THREAD

**Issue by newpie** [volkanceylan/Serenity#1941]
I checked the 'Serenity.CodeGenerator' and found 'schemaProvider.GetTableNames(connection)' returns a list of ‘TableName‘’ with all values null
And in 'OracleSchemaProvider.cs' is the following code:
```
public IEnumerable<TableName> GetTableNames(IDbConnection connection)
        {
            return connection.Query("SELECT owner, table_name FROM all_tables")
                .Select(x => new TableName
                {
                    Schema = x.owner,
                    Table = x.table_name
                });
        }
```
So,I have no idea where the problem is? Case sensitivity?

**Comment by volkanceylan** [comment]
Sergen doesn't support Oracle, they are just placeholders
