### ISSUE TITLE
Need to add third button ('Cancel') to confirm dialog

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#1942]
Hello Guys,

Could you please tell me how I can extend typical confirmation dialog in Serenity? In my case need to add third button - 'Cancel' (like it is on the picture below) - instead of x sign in right top corner of window? Could you please give me a piece of advice how to do this action in some simple way?

Thanks.

![additional_cancel](https://cloud.githubusercontent.com/assets/18590952/22971103/3c46a524-f37d-11e6-90a2-0b873d7cd31c.jpg)

**Comment by volkanceylan** [comment]
Cancel is already Close button. If you have to this design, use jQuery ui dialog docs to write your own dialog, or use another bootstrap dialog

**Comment by stepankurdylo** [comment]
OK, Volkan, I've got your point of view. Not an issue and not related to framework. Closed.
