### ISSUE TITLE
Grouping of Products in OrderDetailsReport.cs

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1943]
var od = OrderDetailRow.Fields;
               data.Details = connection.List<OrderDetailRow>(q => q
                   .SelectTableFields()
                   .Select(od.ProductName)
                   .Select(od.LineTotal)
                   .Where(od.OrderID == this.OrderID));

in OrderDetailsReport.cs i want to group by product name and in report want to show the Product and the count and SUM of price wrt above code
(i have removed the validation to check if product already exists,)

**Comment by mrajalko** [comment]
please see example.

 http://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid

**Comment by edson** [comment]
You can see some sql grouping  usage in 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/BasicSamplesEndpoint.cs

As of sum, see Sql.Sum(xxx)

Best Regards

**Comment by vinaykulkarni89** [comment]
Thankyou @mrajalko and @edson

**Comment by wirble** [comment]
This might be trivial to some but, adding grouping as in the sample will remove/overwrite the default buttons.  You can add it back by using concat:

    protected getButtons() {
            var buttons = super.getButtons();
            buttons =  buttons.concat(
             [{
                title: 'Group By xxxx',
                cssClass: 'expand-all-button',
                onClick: () => this.view.setGrouping(
                    [{
                        getter: 'xxxx'
                    }])
            },
             {
                title: 'No Grouping',
                cssClass: 'collapse-all-button',
                onClick: () => this.view.setGrouping([])
                }]);
            return buttons;
        }
