### ISSUE TITLE
Serenity.Services.UpdateInsertLogBehavior.OnSetInternalFields 

### ISSUE THREAD

**Issue by MykhayloKonopelskyy** [volkanceylan/Serenity#1944]
Hi.
By implementing IUpdateLogRow or IInsertLogRow Serenity.Services.UpdateInsertLogBehavior sets UpdateDateField or InsertDateField in OnSetInternalFields method.

It is possibile to have a bug if my DateTimeField has DateTimeKind.Utc datetime kind(i am storing utc date in db) and if server running machine is in time-zones that practice daylight savings time.

Because the value DateTime.Now().ToUniversalTime()  will be off by an hour if called during the extra hour that occurs during the daylight savings time switch in the fall.

To fix this call DateTime.UtcNow instead of calling DateTime.Now in Serenity.Services.UpdateInsertLogBehavior.OnSetInternalFields when date time kind is utc for a DateTimeField.

https://msdn.microsoft.com/en-us/library/ms973825.aspx#datetime_topic8

**Comment by volkanceylan** [comment]
Thanks, i applied this fix, will be in next version.
