### ISSUE TITLE
LookupEditor backed by Guids not Ints

### ISSUE THREAD

**Issue by itachi500** [volkanceylan/Serenity#1946]
Hi all

How would create a lookupScript for a grid column that is backed/identified with a guid not a int. 
Below is the script so far:
[LookupScript("Management.Plans")]
    public class PlanLookup : RowLookupScript<BookingsRow>
    {
        public PlanLookup()
        {
            IdField = TextField = "Plan";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = sanlamactiveadmin.Management.Entities.BookingsRow.Fields;
            query.Distinct(true)
                .Select(fld.PlanId)
                .Where(
                    new Criteria(fld.PlanId) != "" &
                    new Criteria(fld.PlanId).IsNotNull());
        }
On my Column I have the following:
[Width(130), LookupEditor(typeof(PlanLookup)), QuickFilter]

The filter is brought in but no content is read into the filter, any help where my issue is would be appreciated.

Thanks 
Dylan

**Comment by edson** [comment]
Either you're missing right name field  in constructor

```
public PlanLookup()
{
IdField = TextField = sanlamactiveadmin.Management.Entities.BookingsRow.Fields.PlanId.PropertyName;
}
```

Or your're missing select field Plan in preparequery... depends on what you want.


Best Regards

**Comment by volkanceylan** [comment]
LookupEditor shouldn't have any problems with Guid as long as you set things right
