### ISSUE TITLE
Dynamic Navigation

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1947]
Hey guys,
anyone already tried to use the Dynamic Navigation feature with some user-based property?
I would like to use such feature with the groups of the user, but what I see it's that such menu it's generated only once (such code it's triggered only once): there is a smart way to re-trigger menu dynamic generation?
I already achieved that by customizing the NavigationModel, but I would like to know if there is another approach...

Thanks!
Bye

**Comment by DucThanhNguyen** [comment]
Currently the navigation items are cached at application start for all users. You must customize the NavigationModel to archive that

**Comment by marcobisio** [comment]
Thanks for your feedback @DucThanhNguyen!
In fact I've already customized the NavigationModel :-)

Bye

**Comment by jmkamran** [comment]
subscribe my channel also your answer is in my video https://youtu.be/Ib8OLxC4Jrs
