### ISSUE TITLE
Menu Administration Missing!!!

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#1948]
HI,
I just created an empty application with 2.9.5.1 template, I do not understand why entering as "admin" user does not see the administration menu(see image) !!!
**Thanks in advance**
![image](https://cloud.githubusercontent.com/assets/15787703/22980539/206a2318-f39a-11e6-8df6-a776dd0f005a.png)

**Comment by volkanceylan** [comment]
Include AdministrationNavigation.cs in project or create a new one using 2.9.5.2

**Comment by linpiero** [comment]
Thanks!!! :-)
