### ISSUE TITLE
Sergen generate error with Sqlite

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#1953]
Hi, I Have configured the Serenity.CodeGenerator as as described in https://volkanceylan.gitbooks.io/serenity-guide/sqlite.html.
I see my db and tables, when I try to create by selecting a table I have the following error:
![image](https://cloud.githubusercontent.com/assets/15787703/23013056/644ecbf8-f429-11e6-94c1-2b55af99d7bd.png)
What could be the problem?
Thanks

**Comment by linpiero** [comment]
the error probably due to the fact that the SQLite database is created without Foreign Key......

**Comment by volkanceylan** [comment]
What is PRAGMA foreign_key_list returning for your table? This is probably Dapper bug, as i'm not using any multi-mapping feature of it, and using a bare Query method.

**Comment by linpiero** [comment]
for example in database **ProjectXXX_Default_v1.sqlite** for  table **Contacts** the query "PRAGMA foreign_key_list([Contacts])" return empty list.
the problem is in Serenity.Data\SqlHelpers\Dapper.cs row 1638 
![image](https://cloud.githubusercontent.com/assets/15787703/23063342/5751f3c6-f50a-11e6-8c30-5023bf5ace44.png)
whiut fieldCount and startBound = 0.

**Comment by volkanceylan** [comment]
Please test with 2.9.7

**Comment by linpiero** [comment]
Yes this works!!!!thanks
