### ISSUE TITLE
jsPDF alternative

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1954]
I found a modified jsPDF library that supports unicode, in fact it supports adding any code.

https://github.com/sphilee/jsPDF-CustomFonts-support

Can this be added instead of the default one from serenity?

**Comment by volkanceylan** [comment]
Why dont you try it

**Comment by chizdamasii** [comment]
I tested and it works. I recommend this instead of the default one.

**Comment by PanChenhao** [comment]
Hello, which file need to be replaced? i have replaced jspdf.min.js, but it doesn't work. the chinese word still dispalyed incorrect.
