### ISSUE TITLE
How to pick single date

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#1956]
Dear Volkan,

I can know use the "date range picker" to select two date values as date range(from/to) in sample "AdvancedElement". 
But I don't know how to pick single date value, is there any sample to pick single date for reference or sample code?

Thanks,
Harry Zhang

**Comment by wldkrd1** [comment]
'[DateEditor]' is what you're looking for

**Comment by harrypassport** [comment]
Thanks @wldkrd1.

[DateEditor] property just code in  ***Row.cs/***Form.cs/***.Columns.cs. 

I want to code it in ****.cshtml. So can you have good idea to implement what I need(To pick a single Date)?

Thanks,
Harry

**Comment by Estrusco** [comment]
Why you want insert it in *.cshtml ? 
Is not possible for you add a myDateField in your From.cs and add an [DateEditor] attribute over?

**Comment by edson** [comment]
If you really need it only in cshtml for any other mvc templating, you can use bootstrap datepicker https://bootstrap-datepicker.readthedocs.io/en/latest/
or the already included http://jqueryui.com/datepicker/

For usage, see its docs.

Best Regards

**Comment by harrypassport** [comment]
I got that.
Thanks you edson.
Harry

**Comment by volkanceylan** [comment]
```html
<input id="SomeID" />
<script>
new Serenity.DateEditor($('#SomeID'));
</script>
````

**Comment by harrypassport** [comment]
Many Thanks Volkan.
Harry
