### ISSUE TITLE
Display Issue in detail grid in panel

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1959]
I have a panel showing data from a dialog.

the detail grid does not shows data correctly as show below
![dialog in panel](https://cloud.githubusercontent.com/assets/18166582/23055774/a52fc41c-f50d-11e6-95ce-076c87e2e09a.png)

but if we try and adjust column width it starts showing data.

![dialog in panel after column adjustments](https://cloud.githubusercontent.com/assets/18166582/23055813/ddfeb4f6-f50d-11e6-9540-5af0ce84dc08.png)

can someone please guide me what might be causing this problem.

**Comment by Estrusco** [comment]
Try to refresh grid after data loading.  yourGrid.refresh()

**Comment by edson** [comment]
If refreshing doesn't work, as this is a slickgrid rendering related issue due to how elements are first created... Try to use 
this.yourDetailGrid.slickGrid.invalidateAllRows(); 
this.yourDetailGrid.slickGrid.render();

Best Regards

**Comment by mrajalko** [comment]
problem can be seen in 

http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

also.

I have tried both suggestions by @edson  and @Estrusco  in afterLoadEntity but without any success.

**Comment by edson** [comment]
I see.

Use

this.form.DetailList.element.triggerHandler('layout');

![image](https://cloud.githubusercontent.com/assets/62490/23070971/f9db485a-f513-11e6-96f8-d460bcc3167e.png)


Best Regards

**Comment by mrajalko** [comment]
Thanks @edson it worked for me as well.
