### ISSUE TITLE
publishing Issue

### ISSUE THREAD

**Issue by anandnathtiwari** [volkanceylan/Serenity#196]
Cannot set a constant field.
[FieldAccessException: Cannot set a constant field.]
   System.Reflection.RtFieldInfo.PerformVisibilityCheckOnField(IntPtr field, Object target, RuntimeType declaringType, FieldAttributes attr, UInt32 invocationFlags) +0
   System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark) +255
   System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture) +36
   Serenity.Data.RowFieldsBase.Initialize() +1609
   Serenity.Data.RowExtensions.Init(TRowFields rowFields) +12
   MovieTutorial.Northwind.Entities.CategoryRow..cctor() +44

[TypeInitializationException: The type initializer for 'MovieTutorial.Northwind.Entities.CategoryRow' threw an exception.]
   MovieTutorial.Northwind.Entities.CategoryRow..ctor() +17

**Comment by volkanceylan** [comment]
Probably running under low trust. Try removing readonly from all field declarations. But you might still have issues.

**Comment by anandnathtiwari** [comment]
What is the best way to publish this type of project

**Comment by anandnathtiwari** [comment]
I will try but same result.

**Comment by volkanceylan** [comment]
Ask your hosting provider for medium trust, high trust. Or change it.

**Comment by anandnathtiwari** [comment]
Thanks
You Save My Life and my 3 months working.

**Comment by volkanceylan** [comment]
.NET doesn't allow reflection in low/medium trust level. These fields are initialized through reflection. What can i do about this. If this is saving your life, i'm glad, good luck with your overly protective hosting provider that no-one elses uses.
