### ISSUE TITLE
differences between free and premium versions

### ISSUE THREAD

**Issue by hamid-gh** [volkanceylan/Serenity#1960]
Is there all of online demo's features of Serenity such as components, UI  element , etc. in your source on the GitHub repository ?
What is differences between free and premium versions (except full supports)?

**Comment by volkanceylan** [comment]
Premium samples are not available for public yet, maybe i'll make a demo available later.

They will be samples based on customer requests, and some from my internal applications.

Currently we have these three available:

* Integrated background task system
* Bulk e-mail background task
* Datatables Integration sample including server side source

I'm planning to add new samples at least once a week, prioritized by customer requests.

**Comment by hamid-gh** [comment]
According to your answer, I think all of existing components, elements, dialogs, etc. in your demo, are available for public and I can use them to create  my custom applications same as your demo (and may be better) using Serenity with no payment. Is it correct?

Can I see these tree samples demo?

**Comment by hamid-gh** [comment]
According to your answer, I think all of existing components, elements, dialogs, etc. in your demo, are available for public and I can use them to create my custom applications same as your demo (and may be better) using Serenity with no payment. Is it correct?

**Comment by VictorTomaili** [comment]
Yes, is it correct.
