### ISSUE TITLE
Changes to typescript files not included when upgrading Serenity.Web nuget package

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1961]
Not sure how to fix this or raise awareness, but upgrading Serenity.Web to new versions will not include changes to common typescript files, e.g. \Modules\Common\Helpers\GridEditorBase.ts

I think we have to do that manually, unless there's a better suggestion/best practice?

**Comment by volkanceylan** [comment]
Yes, they are part of Serene, not Serenity, and currently there is no way to auto update them. You might have made modifications to them also so it is not safe either.
