### ISSUE TITLE
Visual Glitch - Dialogs/ Entity Dialog as Panel

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#1962]
Hi everyone, how can i fix this visual glitch in Online Serene Demo / Basic Samples / Dialogs / Entity Dialog as Panel ----> Master Detail - Order Detail [Columns: "Discount" & "Line Total"]:
![image](https://cloud.githubusercontent.com/assets/22221262/23081175/a301cf5a-f521-11e6-979f-3e639a48c3d3.png)

In mobile mode those columns are shown:
![image](https://cloud.githubusercontent.com/assets/22221262/23081226/d9d23b64-f521-11e6-8942-d6bb187b1864.png)

Thanks in advance! :smiley:

**Comment by edson** [comment]
Use
```

protected afterLoadEntity() {
            super.afterLoadEntity();
            this.form.DetailList.element.triggerHandler('layout');
        }
```
![image](https://cloud.githubusercontent.com/assets/62490/23082330/0d37e81e-f540-11e6-92e6-9b2da6d6854b.png)

Duplicate of https://github.com/volkanceylan/Serenity/issues/1959

**Comment by alanlopcu** [comment]
Thank you @edson , it worked! :+1:
