### ISSUE TITLE
difference between two time automatically

### ISSUE THREAD

**Issue by Delapais** [volkanceylan/Serenity#1963]
Please, I have two column "StarTime" and "EndTime", and I want to a add a thirt column "Duration" where can I calculate the difference between "StarTime" and "EndTime" automatically. How can I make this possible ? 

Here is What I did but it does not work : 
`using FluentMigrator;

namespace Serene3.Migrations.DefaultDB
{
    [Migration(20170216025000)]
    public class DefaultDB_20170216_025000_StopProduction : Migration
    {
        public override void Up()
        {
            Create.Schema("stop");
            Create.Table("StopProduction").InSchema("stop")
            .WithColumn("StopId").AsInt32()
            .Identity().PrimaryKey().NotNullable()
            .WithColumn("DateStop").AsDate().NotNullable()
            .WithColumn("StartTime").AsTime().NotNullable()
            .WithColumn("EndTime").AsTime().NotNullable()
            .WithColumn("Line").AsString(200).NotNullable()
            .WithColumn("Project").AsString(100).NotNullable()
            .WithColumn("Machine").AsString(100).NotNullable()
            .WithColumn("Problem").AsString(1000).NotNullable()
            .WithColumn("PersonalID").AsInt32().NotNullable()
            .WithColumn("Duration").AsInt32().Nullable();

            Execute.Sql("UPDATE stop.StopProduction SET Duration = DATEDIFF(minute, StartTime, EndTime) where Duration is NULL");
        }
        public override void Down()
        {

        }
    }
}`

**Comment by volkanceylan** [comment]
When you create the table, there are no records in there, how do you expect this to work?

**Comment by Delapais** [comment]
Yes this is logical, so how can I achieve this??, after the user click in save button the column "Duration" fills automatically

**Comment by volkanceylan** [comment]
Use a calculated field, or expression field, or set that field on BeforeSave of your repository.
