### ISSUE TITLE
ConnectionKey issue

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#1964]
I want to show a chart in diaglog like the sample "ChartInDialog", but it is an error when I write [ConnectionKey(typeof(IctDataCollectRow))], it's need do some anthing for this?
![1](https://cloud.githubusercontent.com/assets/19610257/23089837/704f85c0-f5cb-11e6-9b0e-2b256e88a588.png)

**Comment by volkanceylan** [comment]
Upgrade to latest Serenity if you want to use typeof in ConnectionKey, otherwise use a string conneciton key.
