### ISSUE TITLE
Detail Dialog in Master Panel

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#1965]
I have created a panel for a dialog. which is linked with a detail table.

i want the detail dialog also to be a part of master dialog panel.

some what like this

![image](https://cloud.githubusercontent.com/assets/18166582/23092812/19e00894-f5f9-11e6-81b9-cf59026c227e.png)

**Comment by wldkrd1** [comment]
See Meeting and MeetingAttendee in the samples. For the 'add' row functionality for Order Items above - you'll have create those display elements manually in DetailEditor.ts createToolbarExtensions()

Or you can leave the default behavior of a 'New' button opening a dialog to create an Order Item.

**Comment by mrajalko** [comment]
thanks @wldkrd1 i would try to follow your suggestions and post the results of my efforts.

**Comment by mrajalko** [comment]
Thanks again @wldkrd1 your suggestions were helpful.
