### ISSUE TITLE
update another table based on row insert

### ISSUE THREAD

**Issue by Daffyydd** [volkanceylan/Serenity#1966]
Hi,

I have two tables in which i would to update one with values from another. let me give an example

table A.(members)

member Id
Member shares 
......

tables b (transaction)

TransId
MemberId
TranstypeId
Amount

i want to increament the member shares ( table A) whenever transaction type is share receipts by the amount of transaction.

Any exampe that i can follow to achieve this?

**Comment by volkanceylan** [comment]
I'd recommend doing this in SQL triggers, but if you can't, override AfterSave of TransactionRepository, if this.IsUpdate compare Old.Amount - Row.Amount and update the member, or if this.IsNew increase member. You'll also need to override Delete handler BeforeDelete etc.

**Comment by Daffyydd** [comment]
Dear Volkan,

Thanks I have created a trigger already. I was looking if there is another way to have it on the application itself as most of the articled i have read discourages using triggers.

Thanks once again

**Comment by hafizTahir** [comment]
Please share code for update the another table inside AfterSave()

**Comment by VictorTomaili** [comment]
Please use discussions for new questions etc.
