### ISSUE TITLE
LookupEditor Issue

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#1967]
Hello Friends!

I have the following scenery, i have 3 entities:

- Orders
- Customers
- Senders

The SendersRow have a expresion field (CustomerName) from a relation with the entity Customers, i need to use this expression field to load a LookupEditor in Orders dialog with the (CustomerName) passing by Senders, because actually exist also a relation between Senders/Customers, but when i try to use this expression field generates a exception error (The Column name not exist in Orders).

![issue](https://cloud.githubusercontent.com/assets/24989427/23097268/95d12808-f5fd-11e6-80b0-ec585679d8b2.png)

I have in the SendersRow the following portion of code:

 `[DisplayName("Customer Name"), Expression("jIdCustomer.[CustomerName]"), QuickSearch, LookupInclude]`
        `public String CustomerName`
        `{`
            `get { return Fields.CustomerName[this]; }`
            `set { Fields.CustomerName[this] = value; }`
        `}`

How i can reach this expression field from Orders, knowing that this expression field originate from other relation.

Wait your important comments and suggest.

Best Regards!

Andres

**Comment by Daffyydd** [comment]
Dear @VirtualHome,

You need to define CustomerID in SenderRow which is foreignkey to CustomersRow (if not yet included)

**Comment by VirtualHome** [comment]
Thanks @Daffydd for your answer, CustomerID exists in SendersRow, remember that SendersRow is a entity child of Customers, and i need to use from Orders, but i need the CustomerName not from the relation of the Customers with Orders but yes from Customers with SendersRow. Any other suggest to reach this field?

**Comment by Estrusco** [comment]
Try to set [MinSelectLevel(SelectLevel.Always)] in CustomerName

**Comment by VirtualHome** [comment]
Thanks @Estrusco for your answer, let me try and i'll be back with comments.

**Comment by VirtualHome** [comment]
Thanks for all your answers. Finally i solve the issue with the following code.

 `StringField INameRow.NameField`
        `{`
           `get { return Fields.CustomerName; }`
        `}`

Best Regards!

Andres
