### ISSUE TITLE
Exporting Grid to Excel export "System.Collections.Generic.List`1[System.Int32]" not value

### ISSUE THREAD

**Issue by Dhaka93** [volkanceylan/Serenity#1969]
I have written a formatter  to show comma separated value instead of instead of integer. In this grid it shows correctly i.e. abc; xyz; mno... but when I export in excel, they dont appear instead System.Collections.Generic.List`1[System.Int32] appears as value. How to fix it? 

Here is the code from column.cs file

      [ClientBranchNamesFormatter, NotFilterable, Width(200),DisplayName("Branch")]
        public List<int> Branches { get; set; }
And exported result from excel:

ID	Client Name	Branch
1	Test Client   	System.Collections.Generic.List`1[System.Int32]

**Comment by volkanceylan** [comment]
First, you need to understand that Formatter is a client side concept, which works only on HTML/Javascript side. So, as Excel output works server side, and Excel doesn't support Javascript/HTML there is no way to execute your formatter for Excel output. So there is nothing to "FIX", but workaround through something called Cell Decorator.

See changes in DynamicDataReport.cs, CustomerColumns.cs, and EmployeeListDecorator.cs under Serene repository.

**Comment by Dhaka93** [comment]
Thank you, volkanceylan . It works  now with your sample code. I had to made a small change in *ListDecorator.cs file  by commenting out two lines as follow: 

  var idList = this.Value as IEnumerable<int>;
            //if (idList == null || !idList.Any())
            //    return;

I had to do this because if there is no  client does not have any branch associated with it, it exports 
"System.Collections.Generic.List`1[System.Int32]" instead of empty.

**Comment by volkanceylan** [comment]
No, correct way is to set this.Value = ""

**Comment by Dhaka93** [comment]
Thank you, changed it as you suggested.
