### ISSUE TITLE
1.9.7  KDiff3 path  ? 

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#197]
Where is the configuration file for KDiff3 & Sergen.exe ?

**Comment by volkanceylan** [comment]
Serenity.CodeGenerator.config in your solution path

**Comment by Olricz** [comment]
OK. file path changed. :)

**Comment by zerodev** [comment]
what is the best way to regenerate a code , best practice, kdiff3 keeps popping up

**Comment by volkanceylan** [comment]
You actually shouldnt be regenerating code. Should manually add new fields to row and column or form if required. It popups not to override customizations you might have made.

**Comment by Olricz** [comment]
Thanks. Wating for new feature updates.
