### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by RomanBilyak** [volkanceylan/Serenity#1974]
Hi,
Could you suggest tools to implement visualization of API's resources and generation interactive online documentation that allowing end consumers to easily get started with application API?

I have tried to integrate Serenity with [Swagger](http://swagger.io/) but all like this tools automatically generate documentation based on web api controllers inherited from System.Web.Http.ApiController.

I know that Serenity doesn't use Web API framework and base ServiceEnpoint controller derives from System.Web.Mvc.Controller. In my opinion creation of new base api controller that duplicate the logic of security and injection of db connection is not very good.

Thanks in advance!

**Comment by volkanceylan** [comment]
I never understood reasoning behind Web API, and fortunately they removed it or merged it with ordinary controllers in MVC 6 / Asp.Net Core. I think you can use Swashbuckle.AspNetCore with Serenity .NET Core version. I didn't use it myself. For MVC version, i don't know what you can use.

**Comment by mjacoup** [comment]
I also need to have a clear API layer with documentation. I need to make Mobile APP that call Some services from serenity but really confused from offered solutions .

**Comment by wchitirobho** [comment]
You can create a class with code below to authenticate with your username and password for serenity application, i just gave u a small piece that will let u perform a login and some code below to perform any other query.

// c# code
namespace Serene3.Service.WebAPI
{
    using Administration;
    using Administration.Entities;
    using Administration.Repositories;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Serene3.Membership;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.IO;
    using System.Net;
    using System.Net.Mail;
    using System.Security.Principal;
    using System.Web.Mvc;
    using System.Web.Security;

    [RoutePrefix("Transaction"), Route("{action=index}")]
    public class TransactionController : Controller
    {

        [HttpGet]
        public JsonResult GetRequest(string jsonRequest)
        {
            var result = new WSResult();
            try
            {
                var requestObj = JsonConvert.DeserializeObject<WSRequest>(jsonRequest);

                #region Authenticate Request
                var authenticateResult = Authenticate(requestObj.clientid, requestObj.clientsecret);
                #endregion

                #region Execute Request
                if (authenticateResult == "true")
                {
                    //do anything else
                    result = Execute(requestObj);
                }
                else
                {
                    result.StatusCode = "2";
                    result.StatusDescription = authenticateResult;
                }
                #endregion

                result.FinishTimeStamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:sss");

                var jResult = JsonConvert.SerializeObject(result);
                requestObj = null;
            }
            catch (Exception ex)
            {
               // result = UnhandledERROR(ex.Message);
            }
            finally
            {

            }
            return Json(new { result = result }, JsonRequestBehavior.AllowGet);
        }
        public string Authenticate(string username, string password)
        {
            var result = "false";

            var usern = username;
            if (WebSecurityHelper.Authenticate(ref usern, password, false))
            {
                result = "true";

                using (var connection = SqlConnections.NewByKey("Default"))
                using (var uow = new UnitOfWork(connection))
                {
                    // do queries here as normal

                    return result;
                }
            }
            else
                result = Texts.Validation.AuthenticationError;

            return result;
        }

       
    }

    public class WSRequest
    {
        public string method { get; set; }
        public string data { get; set; }
        public string clientid { get; set; }
        public string clientsecret { get; set; }
        public string token { get; set; }
    }
    public class WSResult
    {
        public WSResult()
        {
            ReceivedTimeStamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:sss");
            StatusCode = string.Empty;
            StatusDescription = string.Empty;
            Data = string.Empty;
            AdditionalInformation = string.Empty;
        }
        public string StatusCode { get; set; }
        public string StatusDescription { get; set; }
        public string Data { get; set; }
        public string AdditionalInformation { get; set; }
        public string ReceivedTimeStamp { get; set; }
        public string FinishTimeStamp { get; set; }
    }

}
//end

Perform an Ajax call from your mobile app or anywhere

//
let req: WSRequest = new WSRequest();

	req.method = "UpdateDeviceSettings";
	req.clientid = ""; 
	req.clientsecret = ""; 

	let platform: string = "";
	if (app.android) {
			platform = "android";
	} else if (app.ios) {
			platform = "ios";
	}

	let param = JSON.stringify({ deviceToken: deviceToken, platform: platform });
	req.data = param;

	let data: string = 'jsonRequest=' + JSON.stringify(req);
	let url = "http://youserenityappurl/transaction/getrequest?" + data;
	let auth = "Basic " + u.base64Encode(username + ":" + "password");

	Ajax.request({
			url: url,
			method: "GET",
			headers: {
					"Content-Type": "application/json; charset=utf-8",
					"dataType": "json",
					"Authorization": auth,
					"Authorization-Token": "",
			},
	}).then((response) => {

			if (response.statusCode == 200) {
					Alert('success');
			}
			else {
				Alert('failed');
			}
	});


Hope this works !!
