### ISSUE TITLE
Getting Quickfilter to show data from another column.

### ISSUE THREAD

**Issue by Anxaxin** [volkanceylan/Serenity#1975]
I've tried getting my Quickfilter attribute to show data from a specific column, but when trying to assign it to that column, using CascadeField and CascadeFrom, it returns "No matches found". If I leave CascadeField and CascadeFrom empty, it defaults to first non-hidden column in the xyzRow.cs

My xyzRow.cs entity, which I want to refer to, looks like this:
`        [DisplayName("Cc Queue"), Column("CCQueue"), Size(50), Width(100), NotNull, LookupInclude, QuickSearch]
        public String CcQueue
        {
            get { return Fields.CcQueue[this]; }
            set { Fields.CcQueue[this] = value; }
        }`

And my xyzColumns.cs entity looks like this:
`        [QuickFilter, LookupEditor(typeof(Entities.ProjectRow), CascadeFrom = "CcQueue", CascadeField = "CcQueue")]
        public String CcQueue { get; set; }`

Hopefully I'm just overseeing something, but I've been struggleling with this one.

Best Regards
Anders Christensen

**Comment by sayuga** [comment]
wait, so you're trying to make a quickfilter that cascades from itself? that sounds redundant and probably is the reason it doesnt work. If you just want to add a quickfilter to a joint field just simply add [LookupEditor(typeof(xyzRow))] on xyzRow.cs and add the [quickFilter] attribute on the columns.cs for that field. Look at the SupplierId for the Products Row.

**Comment by volkanceylan** [comment]
Yes a field cant cascade from itself
