### ISSUE TITLE
Dynamic Entities 

### ISSUE THREAD

**Issue by LuboSta** [volkanceylan/Serenity#1978]
Hello , 
First of all I really love Serenity Framework, following it for last half year and I am really impressed with progress you made. I would like to ask you if you can outline when do you expect implementation of Dynamic Entities ? (is it still expected feature set ? ) My focus is more on working with data ( ETL and then analyze, comparison of various sources ...) and use Serenity as gui for some tables which helps with mapping and configuration. Serenity eliminate lot of coding  and sergen is really key feature to make it perfect I am looking for two additional features : 
1, "sharepoint like" way of adding new columns via modification of model stored in Database. 
2, Entity-Attribute-Value support 
Any chance you can comment if these are expected to come or if there is simple way how to utilize what is already in serenity to get this done somehow ? 
Thank you

**Comment by volkanceylan** [comment]
Sorry i dont have a timeplan, this might be a premium feature.

**Comment by LuboSta** [comment]
Ok any chance you can outlined what would be the best approach so that I can "plug in" into existing serenity structure ?
