### ISSUE TITLE
BACKSPACE, ESCAPE and other keyboard handles just close dialog without saving changes

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#1979]
Hello Dear Community,

Have the following issue: 'BACKSPACE' and 'ESCAPE' buttons close editing dialog without saving changes. Is it possible to just have a handle on for any keyboard presses before leaving the page and having a simple confirmation there? It would work regardless 'BACKSPACE' or 'ESCAPE' or other keyboard's down why a entity dialog page to be closed and lose changes.

Thank you in advance.

**Comment by Estrusco** [comment]
See in Modules\Common\Helpers\DialogUtils.ts  the method pendingChangesConfirmation

and in constructor of XYZdialog.ts 

```ts
constructor() {
    super();
    
    DialogUtils.pendingChangesConfirmation(this.element, () => this.getSaveState() != this.loadedState);
}
```

See CustomerDialog.ts

**Comment by volkanceylan** [comment]
You may try handling onbeforeunload event, but not so sure about browser support
