### ISSUE TITLE
sqlite query ignore case

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#1982]
Hi,
I tried searching but could not find anything about it.
I have the following statement:
```
connection.TryFirst<EntityxxxRow>(
                new Criteria(EntityxxxRow.Fields.Fieldxx) == "value");
```
the result is null because the value persisted in database "**sqlite**" is "Value",
how can I indicate that the "criteria" is case insensitive?

**Comment by adhikamafran** [comment]
alternatively, you can create table in sqllite with collate nocase.

**Comment by dfaruque** [comment]
see #1673

**Comment by linpiero** [comment]
but i don't use the operator "LIKE", i use operator "=="

**Comment by linpiero** [comment]
```
public class CriteriaIgnoreCase
    {
        public BaseCriteria OpEqual(BaseCriteria criteria1, BaseCriteria criteria2)
        {
            return new BinaryCriteria(criteria1, CriteriaOperator.Like, criteria2);
        }
    }
```
**usage**:
`connection.TrySingle<Entities.UserRow>(new CriteriaIgnoreCase().OpEqual(new Criteria(fld.xxxxx), new ValueCriteria("xxxxxxxx")));`

_maybe it could be the right way or not?_

**Comment by volkanceylan** [comment]
Right way is to use a case insensitive collation. Bad way is to use new Criteria("TOUPPER(" + fld.Something.Expression + ")") == "value"

**Comment by linpiero** [comment]
I know in sqlite you can define "collate nocase" for the single column and not for the entire database
