### ISSUE TITLE
Serenity separate data model generation

### ISSUE THREAD

**Issue by sid80210** [volkanceylan/Serenity#1985]
Hi,

I'm completely new to Serenity and it seems really powerfull.
What I would like to is to keep entities generation completely separated from the web project.

Is it possible (and how) to achieve this in Serenity?
My need is to build a project in the same solution where I can code (and generate with Serenity) my entities and than reference it in the web project.

Thanks a lot!

**Comment by dfaruque** [comment]
https://github.com/volkanceylan/SereneLayers

**Comment by sid80210** [comment]
Ok, but SereneLayer seems to be older than Serenity...is this right?

**Comment by dfaruque** [comment]
yep. this is for sample purpose only, you should follow that to your latest serenity project.
