### ISSUE TITLE
Serenity stop working asap I insert a new table

### ISSUE THREAD

**Issue by sid80210** [volkanceylan/Serenity#1987]
Hi,

as soon as I create a new table in MSSQL and use "sergen" to create the code (without any errors) when I run the solution inside VS2013 (after clean and rebuild all the solution) the web sites stop working.
The URL point to "http://localhost:50275/Account/Login?ReturnUrl=%2f" but all I get is a blank page.

What I'm doing wrong?

Thanks a lot!

**Comment by volkanceylan** [comment]
There is a browser console, try it

**Comment by sid80210** [comment]
I just get this message; 

"jQuery.Deferred exception: Serene1.Membership.LoginPanel is not a constructor @http://localhost:50667/Account/Login?ReturnUrl=%2f:142:5
resolve/</mightThrow@http://localhost:50667/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3570:21
resolve/</process<@http://localhost:50667/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3638:12
 undefined 1 jquery-3.1.1.js:3846:3£

and than

"TypeError: Serene1.Membership.LoginPanel is not a constructor"

**Comment by sid80210** [comment]
I tried to download the project "Entegra" from git and when I create a new table it works perfectly, but I have seen that there is another version of "sergen" in that project.

Does this can help to understand better?

**Comment by volkanceylan** [comment]
Check your TS version
