### ISSUE TITLE
Issues with *.Web.js

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#1988]
Our *.Web.js file does not get updated correctly, hence we see lot of issues during in testing/production.
Only time it gets updated if we make any changes *.ts file. Any previous changes will not get written unless manually *ts file is changed. 
We have 4 developers, and we want to make sure this file does get updated correctly. 
Do you have any advise how should we work with this file?

**Comment by volkanceylan** [comment]
Follow readme
