### ISSUE TITLE
Serenity Date Filter does not produce result

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#1989]
If we use any DATE   filed in "Edit Filter", and try to use "equal" criteria, it does not hit/find the record even though date is correct. Why does it not find it? How should we fix it (if there is any fix)?

**Comment by marcobisio** [comment]
The "issue" here it's that the comparison takes account also of the time part of the datetime: in order to verify this behaviour, simply use the "greater than" or "lesser than" operators.
A quick solution could be add the "DateTimeFiltering" attribute to your field in xyzColumns.cs

Bye

**Comment by volkanceylan** [comment]
Yes, you can use quick filter which handles this issue, or use range operator
