### ISSUE TITLE
Group fields of same object in different tabs

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#199]
I have a row object that is rather big. I want to group the fields into tabs on my dialog so that the dialog does not need to be too big and scroll too much. How do I specify which fields to put on which tab? I have created a new template with the tabs I want, but now I am stuck.

**Comment by volkanceylan** [comment]
There is no such functionality out-of-the-box at the moment. You need to movie fields like i moved Notes editor into tab in CustomerDialog. It will be too much work i guess. 

Doesn't categories help? They are not so different than tabs anyway, when you click category link you scroll to that category. You may also try hiding some categories and expanding them on click.

**Comment by wpvking** [comment]
Thanks, I will work with categories. The grouping it gives will help somewhat.
