### ISSUE TITLE
How can I make QuickFilter to implement range filtering for String/Int32 type fields

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#1990]
Dear Volkan,

For QuickFilter of date type field, there automatically occur Date range (From  date1 To date2). That's good. 

But for String type/Int32 type field, it seems no range filtering. For example, I want to make a field called Category with String type, implement Category>='AAA' and Category<='AZZ'.  How can I set the Category field QucickFilter/or QuickFilterOption?

It's appreciated to get your advise/help

Harry

**Comment by edson** [comment]
See http://serenity.is/demo/BasicSamples/QuickFilterCustomization

Best Regards

**Comment by harrypassport** [comment]
Thansk @edson
Harry

**Comment by harrypassport** [comment]
Why my customize filter field's title style(font color is blue) is different from general one (font color is black)? How can set them the same as general ones? 

let filters = super.getQuickFilters();
let fld = GKL.AudDevNormalDiffRow.Fields;

let endSiteId: Serenity.StringEditor = null;
            filters.push({
                field: fld.SiteId,
                type: Serenity.StringEditor,
                title:Q.text("Validation.L_SiteIdRange"),
                element: e1 => {
                    e1.css("width", "80px");
                    endSiteId = Serenity.Widget.create({
                        type: Serenity.StringEditor,
                        element: e2 => e2.insertAfter(e1).css("width", "80px")
                    });
                    endSiteId.element.change(x => e1.triggerHandler("change"));
                    $("<span/>").addClass("range-separator").text("-").insertAfter(e1);
                },
                handler: h => {
                    var active1 = h.value != null;
                    var active2 = endSiteId.value != null;
                    h.active = active1 || active2;
                    if (active1 && h.value != "")
                        h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
                            [[fld.SiteId], '>=', h.value]);
                    if (active2 && endSiteId.value != "")
                        h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
                            [[fld.SiteId], '<=', endSiteId.value]);
                }
            });
return filters;


Thanks,
Harry

**Comment by edson** [comment]
To differenciate from the others when it s Active... You can override It with CSS.

Best regards

**Comment by harrypassport** [comment]
It got it.
Thanks @edson 
Harry
