### ISSUE TITLE
How is your experimentation with Vue.js going?

### ISSUE THREAD

**Issue by uwascan** [volkanceylan/Serenity#1991]
Hello @volkanceylan, how is your experimentation with Vue.js going? I am currently trying to integrate Vue.js into my Serenity based Web App. The goal for me is to eventually be able to build a SPA frontend using Serenity as backend and still be able to leverage Serenity Features like Forms and Column data. Do you have any guidance?

**Comment by volkanceylan** [comment]
Serene .NET Core version has a web based VueJS version, thats all i have for now

**Comment by volkanceylan** [comment]
Of Sergen
