### ISSUE TITLE
LookupEditör

### ISSUE THREAD

**Issue by smallnatre** [volkanceylan/Serenity#1992]
Merhaba

Gridde quickfilter verdiğimiz bir kolonun kayıtlarının ilgili rowdan değilde veritabanında girilmiş kayıtlardan gelmesi için ne yapmam gerekiyor. Bunu ayrı ayrı lookup yazarak prepare query müdahale ederek  çözdüm fakat bir sürü ekranım var hepsinde ayrı ayrı lookup yazmak istemiyorum. Bunun bir çözümü var mıdır ?

Teşekkürler.

**Comment by volkanceylan** [comment]
Dinamik birşeyler yapılabilir ancak şu an için öyle bir çözüm mevcut değil.
