### ISSUE TITLE
Can dialogOpen() be opened by "async" mode?

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#1994]
Dear Volkan,

When use .dialogOpen() method to open one dialog, can I let it run in "async" mode. If the dialog need consume a lot of time, I need to wait it until it end.

so if .dialogOpen() can be run in "async", it's better to let user to know it's still at running status with on-process bar.

Thanks
Harry

**Comment by volkanceylan** [comment]
It already runs async with pace progress

**Comment by harrypassport** [comment]
So how can insert some code before open the dialog?
Just like using "response => {
.....
}
, {async: true,
   beforeSend: function () {
   some coding....
 }

Thanks,
Harry
