### ISSUE TITLE
Some warnings about typescript?

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#1997]
Hi, volkanceylan , Nice to see you again ! 

![warn](https://cloud.githubusercontent.com/assets/20295114/23347844/24974ffc-fce0-11e6-8b28-4ce6c7a05c48.png)

I use the 1.8 version typeScript when I created the project , Now I update my typeScript to 2.1 ，There have some warnings like the picture .  How can I sovle it ?

**Comment by sayuga** [comment]
did you use the  upgrade checklist on #1342 ?

**Comment by volkanceylan** [comment]
These are not warnings but hints from tslint. Create a tslint.json with braces, e.g. `{}`

**Comment by weiguanhai** [comment]
I create a tslint.json in my proj , it works well !  No more hints ,    Thanks a lot !  Hope serenity more powerful !
