### ISSUE TITLE
How to use other Endpoint method instead of List method

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#1999]
I want to "MyGrid.ts" call other method from Endpoint to get the data list instead of the default 'List' method.
Or,
I have a custom list to be set to the Grid, that the filter can not excecute. I use `grid.setItems()` to do that. Howerver, I dont know where I place this code because the custom list is created from the server response.
How can I do that?

**Comment by volkanceylan** [comment]
Try overriding getViewOptions and setting URL to Q.resolveUrl("~/Services/YourModule/YourEntity/YourMethod")

**Comment by KlynkC** [comment]
Thank you so much!
