### ISSUE TITLE
Selection boxes or List for Referenced Tables Values

### ISSUE THREAD

**Issue by smohd** [volkanceylan/Serenity#20]
Hi, back again with an issue.

I have two tables one references from the other, how can I make the sergen to generate dropdown or list in a place of foreign key id. Is this possible or you have some classes by yourself?

Example like the region selection drop down in the sample project.

**Comment by volkanceylan** [comment]
Currently CodeGenerator doesn't generate dropdowns itself. It is done after generating code, but rather simple.

Let's say your foreign row is named Serene1.SomeModule.ListRow. Put a --**LookupScript("SomeModule.List")** on it just like region does, so its data will be available to script side.

ListRow should implement IIdRow and INameRow interfaces so LookupScript will know which fields to include in dropdown as id and text.

Then go to your MainForm.cs where you will use dropdown editor, find ListId property and put **LookupEditor("SomeModule.List")** on it.

**Comment by smohd** [comment]
Thanks, it is working great
