### ISSUE TITLE
xyzEditor; how to access current entity/row data for use to calculate return result

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#200]
Hi JaiQ,

John Ranger here again :-)

Within my custom Editor for the filling of a dropdown which filters out the record with ID 0 (where you helped me recently and which works great) I want to use the ID value of the currently displayed Dialog (where the custom Editor controls the values of one of the Dropdowns of a field) within the editor's code.

I have looked into this but didn't find a way either to pass an additional Parameter to the Editor or to Access the currently open Dialog to retrieve the desired value.

Is my idea at all possible and if yes, how?

Below the current code of my Editor:

```cs
 [Editor]
    public class ClientTypeEditor : LookupEditorBase<LookupEditorOptions, myClientTyp>
    {

        private int currentHardwareType_ID;

        public ClientTypeEditor(jQueryObject hidden, LookupEditorOptions opt, int Hardware_Type_ID)
        : base(hidden, opt)
        {
            currentHardwareType_ID = Hardware_Type_ID;

        }

        protected override IEnumerable<myClientTyp> GetItems(Lookup<myClientTyp> lookup)
        {

            var ValidclientTypes = myLinkTable.Lookup.Items.Where(x => x.HardwareTypeId == currentHardwareType_ID);

            //Q.Alert(ValidclientTypes.Count().ToString());

            return lookup.Items.Where(x => x.Client_Type_Id != 0);
        }

    }

```
Thanks again for your valuable Feedback

and with Kind regards,

John

**Comment by volkanceylan** [comment]
You should pass such parameters from dialogs AfterLoadEntity method, form.XYZField.MyCustomProperty = this.Entity.SomeValue; 

Add a simple property to editor.

Will you use this for filtering or some other? If for filtering, you should update items (UpdateItems) when this property change. Do this in set method of your property.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for you valuable answer and especially for the tip with UpdateItems. Works perfectly :-)

Here the full code that worked for me:

Editor code:
```cs

namespace ClientManagement.Staging
{
    [Editor]
    public class ClientTypeEditor : LookupEditorBase<LookupEditorOptions, myClientTyp>
    {
        private int HardwareTypeID = 0;

        public int currentHardwareType_ID {
            get
            {
                return HardwareTypeID;
            }

            set
            { HardwareTypeID = value;
                UpdateItems();
            }
       }

        public ClientTypeEditor(jQueryObject hidden, LookupEditorOptions opt)
        : base(hidden, opt)
        {
        }

        protected override IEnumerable<myClientTyp> GetItems(Lookup<myClientTyp> lookup)
        {

            var ValidclientTypes = myLinkTable.Lookup.Items.Where(x => x.HardwareTypeId == currentHardwareType_ID);

            var returnItems = new List<myClientTyp>();

            foreach (var ValidclientType in ValidclientTypes)
            {
                var currentClienTyp = myClientTyp.Lookup.Items.FirstOrDefault(x => x.Client_Type_Id == ValidclientType.ClientTypeId);
                returnItems.Add(currentClienTyp);
            }

            return returnItems;
         
        }

    }

```
Setting of the field property in xyzDialog.cs which is then passed to the Editor:

```cs

        protected override void AfterLoadEntity()
        {
            base.AfterLoadEntity();

            form.Client_Type_ID.currentHardwareType_ID = (int)Entity.Hardware_Type_ID.ToInt32(); // *** Send the current hardware type ID over to the ClientTypeEditor
        }
```

Thank you very much, JaiQ and have a nice evening.

With Kind regards,

John

**Comment by volkanceylan** [comment]
You're welcome. Thank you too for detailed requests, and sharing results
