### ISSUE TITLE
InsertDate, InsertedById,UpdateDate, UpdatedBy

### ISSUE THREAD

**Issue by doyuga** [volkanceylan/Serenity#2003]
How do you deal with these fields (InsertDate, InsertedById,UpdateDate, UpdatedBy) for purpose of tracking logs. 

Kind regards,

Dan

**Comment by edson** [comment]
See https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Administration/User/LoggingRow.cs

Best Regards
