### ISSUE TITLE
Developer Guider doesn't seem to match reality

### ISSUE THREAD

**Issue by MartinTittensor** [volkanceylan/Serenity#2004]
I'm _really_ new to web development and Serenity, and I'm trying to follow the **Developer Guide**'s tutorial to figure out how easy it is to use and what it can do.

I understand that the Developer Guide is always likely to lag behind where Serenity development is at, but I figured that the Developer's Guide would be as good a way as any to get an introduction.

The problems start with the code generator (sergen). The tutorial says that you can run it from the package manager console, but really you can't (well, I couldn't). I eventually figured out that you can add the sergen.exe folder to the path and it would at least launch it, but it doesn't populate it as the tutorial describes (for me) so it's no better than just running the executable. Second problem is that the Code Generator dialog doesn't bear too much of a resemblance to that in the tutorial. I eventually figured out that the fields such as Module Name, Connection Key etc are integrated into the grid. But _which_ files need generating is a bit of guesswork. Row? Column? Form? All of them? The default ones?

And then generating the files may or may not work! A command prompt briefly flashes up, then disappears. Grabbing a screenshot of this reveals a bunch of errors in the tcs.exe (which, I think, is the typescript compiler?):

![image](https://cloud.githubusercontent.com/assets/22616381/23413053/79c2b6e8-fdcf-11e6-8be6-f584458f154f.png)

I think these must be legit errors, since now the admin form is broken. It's missing the input fields:

![image](https://cloud.githubusercontent.com/assets/22616381/23413148/c227bc6c-fdcf-11e6-83d8-02d0a816d678.png)

Oh, and the background image has gone.

Is it worth persevering with this tutorial or am I flogging a dead horse?

Just to reiterate, I am a complete novice a web development so if I'm doing something fundamentally wrong then I apologise, but I really don't have much experience to fall back on to figure out where I might have gone wrong. I'm guessing maybe I've got too new a version of typescript or something (is that even possible?), but that's nothing more than a guess.

All help very much appreciated.

FWIW, I'm on Visual Studio 2015 (Update 2). The installed typescript compiler version 2.2.1.

**Comment by volkanceylan** [comment]
You need TypeScript 2.1.5, you don't have 2.2.1 for Visual Studio, maybe you installed standalone version i don't know. 2.1.5+ requires Visual Studio Update 3.

Before guide, there is a Welcome.htm that was displayed in your screen when you created the template. It writes the versions you need.

As clear from screenshot, you have TypeScript 1.8.

**Comment by MartinTittensor** [comment]
Thanks Volkan. Super quick reply! You're right, even though I'd installed what I thought was 2.2.1, in Visual Studio it was reporting 1.8.31 as the version.

Ok, that explains it. I'll see about moving to VS2015 Update 3 and revisiting this.
