### ISSUE TITLE
How to use GetViewOptions Method?

### ISSUE THREAD

**Issue by vietnguyen8392** [volkanceylan/Serenity#2006]
Hi @volkanceylan and everyone,

I wrote a method in Endpoint named GetEmployeeUser with EmployeeUserId. And, I created any grid named EmployeeUserRqfGrid in EmployeeUserRqfGrid.ts.

In that file, I used getViewOptions() to call the method in Endpoint:
    
```
        protected getViewOptions() {
            let viewOptions = super.getViewOptions();
            // viewOptions.params = { EmployeeUserId: this.devper };
            //EmployeeService.GetEmployeeUser({ EmployeeUserId: this.devper });
            viewOptions.url = Q.resolveUrl('/services/OrgStructure/Employee/GetEmployeeUser?EmployeeUserId='+this.devper);
            return viewOptions;
        }
```

The "devper" param is passed in constructor but in getViewOptions() Method, it is undefined. What if getViewOptions() method ran before contructor? How can I get list from the method I created in Endpoint?

![image](https://cloud.githubusercontent.com/assets/24261992/23445232/8884d588-fe6c-11e6-8845-862e8c7fa5fa.png)

**Comment by Estrusco** [comment]
Have you a code of type

```ts
export class XYZMyGrid extends Serenity.EntityGrid<MyRow, string> {
        [...]

        constructor(container: JQuery, options: string) {
            super(container, options);

        }

        protected myFunc() {
           // in this.options there is your devper
            string myOpt = this.options;
        }

}
```

call with 
new XYZMyGrid($('#GridDiv'), "testString").init()
