### ISSUE TITLE
ReadOnly field throws BadRequest error by call service from desktop application by using RestSharp

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#2007]
Hello sir,

I call serenity web service from desktop application using RestSharp nuget package. I want update ProductDTO Entity on server as well as local database, so i call serenity Products Update service. It's call successful but it throws InsertUserId field is ReadOnly error. I tried many things to set null values of all 4 properties (InsertUserId, InsertDate, UpdateUserId, UpdateDate) but it didn't resolved. So please help me.

![deskrestserviceentity1](https://cloud.githubusercon
![deskrestservicecall3](https://cloud.githubusercontent.com/assets/15955425/23448071/db331bb6-fe74-11e6-8640-6fbf4ea49ca6.png)
tent.com/assets/15955425/23448055/cc8f2384-fe74-11e6-9959-8e66aa4ded5c.png)
![deskrestservicecall2](https://cloud.githubusercontent.com/assets/15955425/23448063/d35885e8-fe74-11e6-91eb-776cd70be235.png)
![deskrestservicecall3](https://cloud.githubusercontent.com/assets/15955425/23448088/f57dc2b4-fe74-11e6-88d6-3702ca491b7a.png)
![deskrestservicecall4](https://cloud.githubusercontent.com/assets/15955425/23448209/9d6bdace-fe75-11e6-9913-88549e6a53cb.png)

**Comment by volkanceylan** [comment]
Use JsonServiceClient in Serenity. Either find a way not serialize fields you didn't set. I don't how it is done in RestSharp. Maybe you can use a dictionary.

**Comment by sebacamino** [comment]
How you can authorize with RestSharp? Thanks
