### ISSUE TITLE
Dialog with Inputs

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#2008]
I would like to show a dialog with some inputs, which are returned as part of response.

can anyone please guide me on how to achieve this.

**Comment by mrajalko** [comment]
can i use this sample code.

http://serenity.is/demo/BasicSamples/StaticTextBlock 


please help.
I have a requirement of displaying a dialog to take 2 inputs.

**Comment by edson** [comment]
All you need is basicly there and here... http://serenity.is/demo/BasicSamples/ProductExcelImport
You just have to figure if you need a new form to return those entered input values somewhere or a form based on an existing row... see your requirements..
 

Best Regards

**Comment by mrajalko** [comment]
thanks @edson for your suggestion and help.

thanks a lot.

**Comment by rarunkumar454** [comment]
Hi i am working on serenity platform. I have a customer information in multiple tables. I need to execute CRUD operations using a single  dialogue or repository. For example in a customer details - we have the Address information in a separate table, Bank detail information in a separate table( Can i execute the CRUD operation on a single dialogue box). There is a example other form in a tab, but the same the i need to perfoem CURD on that tab. It's possible please guid me.
