### ISSUE TITLE
Is this for ASP MVC?

### ISSUE THREAD

**Issue by MYounas** [volkanceylan/Serenity#2013]
Where is controllers and models folde?
plz check the image attached
![falto](https://cloud.githubusercontent.com/assets/13608139/23534560/913919e0-ffda-11e6-8d24-5482ca713824.png)

**Comment by MYounas** [comment]
And where I can add my own controller and models and my own stuff..please help...

**Comment by JoshDiDuca** [comment]
Modules folder, use the serenity code generator in the packages folder to create a model from a database table.

**Comment by MYounas** [comment]
Please Help how to do that?much needed..

**Comment by volkanceylan** [comment]
Try the guide
