### ISSUE TITLE
escaping single and double quotes in grid

### ISSUE THREAD

**Issue by DataminerIP** [volkanceylan/Serenity#2016]
Hello all, 

I have successfully followed the serenity examples on how to add a stringformatter on a certain column. 
However, the data for this column contains both single and double quotes. 
This incorrectly interrupts the string and only shows half of the data. 
At which point on the data retrieval do i have to make a certain replace ? 

Thanks in advance, 
Joris

**Comment by volkanceylan** [comment]
Q.htmlEncode
