### ISSUE TITLE
NodeJS/NPM installation check on the new project wizard

### ISSUE THREAD

**Issue by rjaquez-ais** [volkanceylan/Serenity#2017]
I get the warning, even though I have a recent version of NodeJS/NPM, and I have no problems building/running Serenity based applications.

The new project Wizard in version 2.9.9 runs "cmd /c npm.cmd version", and get the output into a string (RootWizard.cs).

There is check for the string to start with "{" and end with "}", but mine ends with a line feed (hex 0A) character.

Output from my system:

C:\>cmd /c npm.cmd version
"{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.4',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.89',
  zlib: '1.2.8' }
"

**Comment by volkanceylan** [comment]
Thanks a lot for reporting, i'll add a trim first. It was a quick check that needs refinement.

**Comment by volkanceylan** [comment]
I think issue is not \r but yours start and end with double quotes somehow?

**Comment by rjaquez-ais** [comment]
I added the double quotes for the email. They are not in the output.

It looks like the current github code from the CheckNodeNpmVersion() in RootWizard.cs is correct.
I just tested it in Visual Studio C# interactive console.

But I am still got the warning when creating a new project using the updated nuget package.

**Comment by volkanceylan** [comment]
Can you check with latest template please, thanks.

**Comment by rjaquez-ais** [comment]
This is fixed in the latest nuget package (2.9.9.1)
