### ISSUE TITLE
Accessing Model values in razor 

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#2019]
.Select(Sql.Count(), "Count")
.Select(Sql.Sum("SourceId"), "Total")

how can I access the Count and Total in .cshtml by using Model

**Comment by awesomegithubusername** [comment]
Take a look at this:
[Dashboard](https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Common/Dashboard)

**Comment by VictorTomaili** [comment]
This is a standard MVC question. You have "page.cs controller" and "cshtml view" file. Fill model and use it.
