### ISSUE TITLE
class Serenity.Authorization

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#202]
Hello,
I implemented a few asynchronous methods using Task.Run ( ( ) = > ..... , the problem is that the Serenity.Authorization class is empty , there would be a way to use that class in another thread???
Thanks
Best Regards

**Comment by VictorTomaili** [comment]
Try to set it manually like startup class.

**Comment by volkanceylan** [comment]
Does your SiteInitialization run before these tasks? Dependency uses static variable so it shouldnt be null as long as u init before

**Comment by linpiero** [comment]
Yes I will launch the task after saving a entity , exactly in the update method of the repository

**Comment by volkanceylan** [comment]
Reopen please if you still have the issue
