### ISSUE TITLE
Bootstrap Switch Plugin 

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#2020]
Hello!

For use the [Bootstrap Switch plugin by @marcobisio ](https://github.com/volkanceylan/Serenity/wiki/Bootstrap%20Switch%20plugin#howto-bootstrap-switch-plugin-by-marcobisio) where i'll need to put this portion of code?

For set:

`public setEditValue(source: any, property: Serenity.PropertyItem): void {`
        `if (this.element.hasClass('required')) this.element.removeClass('required');`
        `this.element.bootstrapSwitch('state', source[property.name]);`
`}`

Wait your important comments.

Best Regards!

Andres

**Comment by edson** [comment]
Replace the setEditValue one with that in custom editor...

Best Regards

**Comment by VirtualHome** [comment]
Sorry @edson not understand where i'll need to put this code, only need this step to work with this Plugin, you can please more specific in your answer. Thanks for your help.

**Comment by edson** [comment]
It is just to remove the required class from element... Just put that in bsswitcher editor (over the setEdit in there). There's a link to it in wiki if you don't understand the code usage and the issues it has. Be sure to check it.

Best Regards
