### ISSUE TITLE
Possible to isolate Year from DateTimeField when doing a comparison?

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#2021]
I'm doing a comparison using a DateTimeField and I'd like to tell my criteria just to use the year.  

I've done this kind of thing before:
```
var flds = MyRow.Fields;

var count = connection.Count<MyRow>(flds.OrderDate > DateTime.Today);
```

That works, but what I need now is something like:
`
var count = connection.Count<MyRow>(flds.OrderDate.Year > DateTime.Today.Year);`

**Comment by edson** [comment]
Compare by creating a criteria with"DATEPART(YEAR, " + flds.OrderDate.Expression + ")" Or "Year(" + flds.OrderDate.Expression + ")" or other sql syntax from your DB of choice...


Best Regards

**Comment by lquantz** [comment]
Thanks for the tip.  I wound up doing this (I use SQL Server)--
```
Criteria myCrit = new Criteria("Year(" + fld.OrderDate.Expression + ")");
var count = connection.Count<MyRow>(myCrit > DateTime.Today.Year);
```

**Comment by volkanceylan** [comment]
You could also do fld.OrderDate > new DateTime(DateTime.Today.Year, 1, 1)

**Comment by lquantz** [comment]
Thanks @volkanceylan

**Comment by el4dr14l** [comment]
I tried to part the date like in the above example, but I keep getting an error: "DATEPART(QUARTER,T0.[Fecha]) Is not a valid field name.
