### ISSUE TITLE
Getting MyRow Data on MyEntityRepository.cs

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#2022]
So I have enabled push notifications via OneSignal, but I would like to push a notification when something is created. I can get this done by simply calling the server side `void` however, I can seem to figure out how to get the actual data. 

The code:

```
 public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            Common.OneSignal.Notify("Heading", "New event with " + fld.Id + " has been created.", "Endpoint", "Icon");
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }
```

When the desktop notification comes through, there the `fld.Id` is supposed to be all I get is "[TO].Id".

Any idea how to actually get the Id that was inserted or any other field that was inserted?

Also if anyone is interested I can share the code for the OneSignal integration I created.

Many thanks!

**Comment by edson** [comment]
Your fld in Repository is only a shortcut to your Entities.YourRow.Fields definitions...

If you are passing through request, that would be  request.Entity.Id ... 
Depends on your implementation... 

Best Regards

**Comment by edson** [comment]
Sorry... Probably you should put the notify in AfterSave() from SaveHandler in Repository (Access Row.Id) if this Create you posted is called from your entity creation. Thought you were saving the notification info to DB... but maybe it's not the case...


Best Regards

**Comment by edson** [comment]
Another option, if you just want the id created...

```
public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            SaveResponse response = new MySaveHandler().Process(uow, request, SaveRequestType.Create);
            Common.OneSignal.Notify("Heading", "New event with " + response.EntityId + " has been created.", "Endpoint", "Icon");
            return response;
        }
```

Best Regards

**Comment by williamhodges** [comment]
The reason I didn't do it like this is because I could figure a way to tell
if it was updated or created because updated gets a different type of alert
over created. Any idea? I'll doublecheck when I get to my work PC in a
moment

**Comment by edson** [comment]
Either put it in Endpoint (Create Response and Update Response) or check AfterSave() in SaveHandler. There is a flag you can check IsCreate or IsUpdate in there. So you can put more info for your Notification.

I did the latter way.

Best Regards.

**Comment by williamhodges** [comment]
Thank you! I'll give it a shot when I get to work.

**Comment by williamhodges** [comment]
I got that part working on getting just the ID. For some reason using that doesn't allow me the ability to get any other row information. Any ideas?

**Comment by edson** [comment]
Which one did you go? The SaveResponse (The one returned in Endpoint) only returns EntityId unless you do some custom changes...

That's why for simplicity my own notification system is working in AfterSave() (MySaveHandler in Repository) not in Endpoint.

Best Regards

**Comment by williamhodges** [comment]
I chose the one in the endpoint. Is it in the same way from the `AfterSave()`? As in the same code structure?

**Comment by williamhodges** [comment]
Closed by accident, but reopened.

**Comment by edson** [comment]
Same way as filtering rows to authorized users access... Only it is at

  ```
private class MySaveHandler : SaveRequestHandler<MyRow> {

             protected override void AfterSave()
            {
                base.AfterSave();

                if(IsCreate)
                    ....
             }
   }

```

Best Regards
