### ISSUE TITLE
How to get value in Repository Class

### ISSUE THREAD

**Issue by arunkumar12712** [volkanceylan/Serenity#2023]
How to Get Values of VoucherStatus.

[DisplayName("Voucher"), ForeignKey("[dbo].[Accounts_Vouchers]", "Id"), LeftJoin("jVoucher"), TextualField("VoucherReferenceNo")]
        public Int32? VoucherId
        {
            get { return Fields.VoucherId[this]; }
            set { Fields.VoucherId[this] = value; }
        }

[3:28]  
[DisplayName("Voucher Status"), Expression("jVoucher.[Status]")]
        public Int32? VoucherStatus
        {
            get { return Fields.VoucherStatus[this]; }
            set { Fields.VoucherStatus[this] = value; }
        }

 protected override void OnBeforeDelete()
            {
                if (Row.VoucherId.HasValue && (Row.VoucherStatus.Value ==     ApprovalStatus.Submitted.ToInt32() || Row.VoucherStatus.Value == ApprovalStatus.Submitted.ToInt32()))
                    throw new ValidationError("Voucher has been created for this Bulk Payment. Can not be deleted..");
                base.OnBeforeDelete();
            }

Vouc

**Comment by Estrusco** [comment]
What is the problem?

**Comment by volkanceylan** [comment]
Override PrepareQuery and select that field. DeleteHandler only selects table fields by default.
