### ISSUE TITLE
_LayoutNoNavigation does not support Localization

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#2024]
I am using printing html to pdf with `LocalText.Get(key)` function to show the header title or something like that
However, it does not work with current language, but it use the default language to show the result.
What is missing from this layout?

**Comment by volkanceylan** [comment]
See my latest commit in Serene repo.

**Comment by VictorTomaili** [comment]
[This line](https://github.com/volkanceylan/Serene/blob/6f760b765d1a74409dc70f6020a88739d4ce87b5/Serene/Serene.Web/Modules/Common/Reporting/ReportController.cs#L129)

**Comment by KlynkC** [comment]
Thank you.
I have seen that
