### ISSUE TITLE
Max upload in bytes - MultipleImageUploadEditor

### ISSUE THREAD

**Issue by jtuszynski** [volkanceylan/Serenity#2025]
Hi, I use  [MultipleImageUploadEditor(FilenameFormat = "Images/~" , CopyToHistory = true, AllowNonImage = false, MaxSize = 4000000)] . Images are blocked, when exceed the size of 4 mb. I would like to block it, when all the pictures in MultipleImageUploadEditor exceed the value of such 10mb. Is it possible?

**Comment by edson** [comment]
What's the problem with setting MaxSize to 10mb?

**Comment by volkanceylan** [comment]
See ASP.NET upload limits in their docs or StackOverflow etc.
