### ISSUE TITLE
How to add parametters to service for export PDF file

### ISSUE THREAD

**Issue by KlynkC** [volkanceylan/Serenity#2028]
I used `wkhtmltopdf` to export HTML to PDF file
Howerver, I want to export filtered data, not all data, so I have to pass the filter values to the method `GetData`.
How can I do that?

**Comment by Junariz** [comment]
How about getParams parameter in tool button ?

["getParams" parameter in Common.ReportHelper.createToolButton] will pass to [ Execute method Module/Common/ReportController.cs] as JSON value to JsonConvert.DeserializeObject.
It will map to property of report class that imprement IReport (i.e OrderDetailReport.cs), and use it in GetData method.
