### ISSUE TITLE
How to display file in grid as a downloadable format?

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#203]
How to display file in grid as a downloadable format?

**Comment by ademc** [comment]
You can use EPPlus (http://epplus.codeplex.com/) library to export grid data to excel file.

**Comment by laxmanp** [comment]
Thanks but I want file download functionality by click on grid column button name "Download". Admin upload some files and it will available for users to download it like pdf, word or others files.

**Comment by volkanceylan** [comment]
You need to put link to /upload/yourfolder/0000/...., you need a formatter that will put /upload/ in front of file name.

**Comment by volkanceylan** [comment]
Next version will contain a FileDownloadEditor

**Comment by laxmanp** [comment]
Thanks. I also want to display multiple document files in left pane and open selected file in document viewer editor.
