### ISSUE TITLE
anyone doing dashboard customizations, per customer or per user?

### ISSUE THREAD

**Issue by lquantz** [volkanceylan/Serenity#2030]
This is more a question on what, if anything, others have done with the dashboards in their apps.  Has anyone tried customizing them so that from the same codebase a customer can choose the widgets they want on their homepage?  Or even on a per user basis?  

If I were doing something quick and from scratch I might change the DashboardPageModel to read some values from a configuration table(s) (values included: number of widgets, type of each widget, data or criteria for each widget) and then loop over and build the necessary `<divs>` in DashboardIndex.cshtml, one per widget, but that's off the top of my head.  Wasn't sure if anybody else has tried something along these lines?

**Comment by Estrusco** [comment]
I used a similar system for customizing the menu. As you said you can save the preferences in db table and use razor in .cshtml page to create the widget according the user preferences.

**Comment by lquantz** [comment]
Thanks @Estrusco.  If I do anything with this (other things to do with my app first) I'll post it up for others to use/critique.
