### ISSUE TITLE
Image Uploader validate image distentions before upload

### ISSUE THREAD

**Issue by itachi500** [volkanceylan/Serenity#2033]
Hey guys
I am looking for a method to validate the width and height of an image before I upload it using Serenity's ImageUploadEditor. I have tried the following just in the HandleUploadRequest method:

 System.Drawing.Image sourceImage = System.Drawing.Image.FromStream(file.InputStream);
                //Check promotion image dimentions
                if (context.Request.Form.AllKeys[3] == "Name")
                {
                    if (sourceImage.Width > 400 || sourceImage.Height > 200)
                    {
                        var response = new UploadResponse()
                        {
                            IsImage = true,
                            Error = new ServiceError()
                            {
                                Arguments = file.FileName,
                                Code = "Exception",
                                Message = "Image too large",
                                Details = "This image is too large"
                            }
                        };
                        return response;
                    }
                }
                else
                {
                    if (sourceImage.Width > 640 || sourceImage.Height > 600)
                    {
                        return new UploadResponse()
                        {
                            IsImage = true,
                            Error = new ServiceError()
                            {
                                Code = "Exception",
                                Message = "Image too large",
                                Details = "This image is too large"
                            }
                        };
                    }
                }
This would kick back the response before the actual upload would take place.
The image is correctly validated but I am struggling to get a error dialog to appear displaying the result. Anyone have a method of solving the user feedback side of things :)

Thanks in advance.

**Comment by volkanceylan** [comment]
ImageUploadEditor attribute already has these checks, you should use that.
