### ISSUE TITLE
Script initialization error .Net  Core

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#2034]
When publishing to iis, when i try to see the record details in Norhwind by clicking on it i get a Line: 1601
Error: Script data Template.CustomerDialog is not found in registered script list!
Line: 1601
Error: Script data Template.OrderDialog is not found in registered script list!
etc...
The app is working fine when debugging in VS2015, the error occurs only when publishing.

**Comment by chizdamasii** [comment]
My script ini is:
namespace Serene.ScriptInitialization {
    Q.Config.responsiveDialogs = true;
    Q.Config.rootNamespaces.push('Serene');
    //Serenity.EntityDialog.defaultLanguageList = LanguageList.getValue;
}

**Comment by chizdamasii** [comment]
The error i think is linked to uncommenting the Serenity.EntityDialog.defaultLanguageList = LanguageList.getValue;
The reason for doing that is i get another error when i leave it uncommented:
Uncaught TypeError: Cannot read property 'getValue' of undefined
    at Serene.ScriptInitialization (ScriptInitialization.ts:4)

**Comment by edson** [comment]
Maybe you are confusing the namespace... 
Shouldn't it be 
`Serene.EntityDialog.defaultLanguageList = LanguageList.getValue;`

Or your namespace should be Serenity....

Best Regards

**Comment by chizdamasii** [comment]
Just Build a fresh Serene project, and still getting the error  JavaScript runtime error: Unable to get property 'getValue' of undefined or null reference on line     Serenity.EntityDialog.defaultLanguageList = LanguageList.getValue;

**Comment by TomaszKustra** [comment]
I had the same problem, the file simply is not published. You need to set BuildAction on Content

**Comment by marcobisio** [comment]
Put this at the top of ScriptInitialization.ts file:

    /// <reference path="../Common/Helpers/LanguageList.ts" />

**Comment by volkanceylan** [comment]
Thanks @marcobisio, i've added this to both now 👍

**Comment by marcobisio** [comment]
You're welcome @volkanceylan !
