### ISSUE TITLE
Login page error

### ISSUE THREAD

**Issue by prasertk** [volkanceylan/Serenity#2035]
Hi volkanceylan
 I have deployed a Serenity app in IIS8 and login page with error. 
![err](https://cloud.githubusercontent.com/assets/11329499/23667508/af5ca57c-0390-11e7-89d9-afa06f5bc2b1.jpg)

**Comment by volkanceylan** [comment]
Check your server errors, sql, connections, settings, users, i can't help you with deployment beyond what is written in FAQ, Troubleshooting.

**Comment by prasertk** [comment]
Application pools setting integrated mode and enable 32-bit application is true fixed it.

Thank you.
