### ISSUE TITLE
Newly registered user gets error when attempting to activate via email

### ISSUE THREAD

**Issue by jmace** [volkanceylan/Serenity#2038]
I had a user register for an account on my site (Serenity 2.9.8). Once they receive their activation email, they click the link and see the error message attached. The registration and activation happen within minutes of each other.

![image](https://cloud.githubusercontent.com/assets/420315/23719992/5a8df48a-040b-11e7-933d-93b8db8a4c51.png)

Is there a timeout token somewhere that I can extend the time on? or something else I should be chasing?

**Comment by volkanceylan** [comment]
Check the code where token is generated, it should be 30 mins or so.
