### ISSUE TITLE
How to get values of Filters

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#2039]
I have been pursuing a long time requirement of showing grouping in PDF and Excel File #1340.

i was thinking that if we can use the PDF generated by html page as shown in sample page of Order Dialog.

we can make a cshtml file and show it as PDF as shown in sample.
this way the group headers and the group totals can be shown.

for this we need to call a report class identified by a report key.

but my problem now is how can i get the current values of filter and send them to the report class.

please guide me if i am thinking in correct line.

**Comment by volkanceylan** [comment]
Check browser console for request contents. That won't be easy.
