### ISSUE TITLE
UniqueConstraintSaveBehavior behavior problem

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2040]
Hi @volkanceylan !

I have an issues with UniqueConstraintSaveBehavior.

My row has four behaviors, and some of these sets field values (as TenantId behavior).

![behaviorlist](https://cloud.githubusercontent.com/assets/16304015/23745520/ce337dda-04b8-11e7-9106-aba5bb6ca208.PNG)

The framework call first UniqueConstraintSaveBehavior, but at this point the the values of TenantId and other field updated by other behaviors, that create a unique constraint index, are not valorized. Then the record are always insert, and the db return index error.

![validateuniqueconstraint](https://cloud.githubusercontent.com/assets/16304015/23745641/3e0fc1b8-04b9-11e7-91b5-e78210be22f3.PNG)

Is there a way to set the order that the framework call the behaviors? 
And if not, I was thinking of adding an Order or CallingOrder attribute to behavior class to force the order of behavior.

What do you think about it?

**Comment by volkanceylan** [comment]
Well, i think UniqueConstraint attribute should be using BeforeSave not ValidateRequest, and your behaviors should be using SetInternalFields. I committed this change.

Anyway, override GetBehaviors

```

protected virtual IEnumerable<ISaveBehavior> GetBehaviors()
{
            var behaviors = base.GetBehaviors();
            var unique = behaviors .OfType<UniqueConstraintSaveBehavior>();
            return behaviors .Except(unique).Concat(unique);
}

```

**Comment by Estrusco** [comment]
Yes my behaviors use SetInternalfields. Then your change solves the problem.

Thank you :)
