### ISSUE TITLE
MitarbeiterId field on PersonAbteilungenRow is read before assigned a value!

### ISSUE THREAD

**Issue by DanielBasler** [volkanceylan/Serenity#2041]
When saving a list, the following error message is displayed.
The field is specified as follows:
[DisplayName("Mitarbeiter"), NotNull, ForeignKey("[dbo].[NET_Mitarbeiter]", "MitarbeiterId"), LeftJoin("jMitarbeiter"), TextualField("MitarbeiterName")]
        public Int32? MitarbeiterId
        {
            get { return Fields.MitarbeiterId[this]; }
            set { Fields.MitarbeiterId[this] = value; }
        }

Can someone help

**Comment by volkanceylan** [comment]
You are trying to read it somewhere while it wasn't selected

**Comment by DanielBasler** [comment]
Yes, it was.
I created in the automatic code generation, columns, forms and dialog.
After removing the classes, it works perfectly. Thank you.
