### ISSUE TITLE
Noob Help :(

### ISSUE THREAD

**Issue by jUST220** [volkanceylan/Serenity#2042]
I'm trying to insert a Combo into the login screen and after the login, redirect to diferente pages depending the option choosed, how to do this ?

Sorry for not having greate skills as you guys...

**Comment by jmace** [comment]
You can modify the login screen files under Modules > Membership > Account

Also, you'll need to modify LoginPanel.ts around these lines to adjust where you are sending the user. I have not done this, but this is where I would start. The more experienced guys may jump in here and give you much more guidance.

```
this.byId('LoginButton').click(e => {
                e.preventDefault();

                if (!this.validateForm()) {
                    return;
                }

                var request = this.getSaveEntity();
                Q.serviceCall({
                    url: Q.resolveUrl('~/Account/Login'),
                    request: request,
                    onSuccess: function (response) {
                        var q = Q.parseQueryString();
                        var returnUrl = q['returnUrl'] || q['ReturnUrl'];
                        if (returnUrl) {
                            window.location.href = returnUrl;
                        }
                        else {
                            window.location.href = Q.resolveUrl('~/');
                        }
                    }
                });

            });
```

**Comment by VictorTomaili** [comment]
Use slack for non bug related questions.

**Comment by jUST220** [comment]
Thanks will try to implement it.
