### ISSUE TITLE
radiobuttons instead of drop-down

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#2043]
Hello all,
Could someone explain how to change an enum Drop-down into radio buttons in the form? Thanks

(I've found a broken link in visualstudiogallery about this topic "So it is possible to display them as Radio Button instead of select2 drop-down".  Where are these older posts moved to?)

Thanks

**Comment by Estrusco** [comment]
On form

```cs
        [RadioButtonEditor]
        public YourEnum YuorProperty { get; set; }
```

**Comment by ga5tan** [comment]
@Estrusco what if my items for radio come from DB?
if not, How can I provide more description for enum types?

**Comment by Estrusco** [comment]
@ga5tan if you want add an alternative description for enum values, you can add [Description] attribute over the enum entry.

```cs
    public enum MyEnum
    {
        [Description("The First!")]
        FirstValue = 1,
        [Description("Second Value")]
        SecondValue = 2,
        [Description("Third Value")]
        ThirdValue = 0
    }
```

**Comment by ga5tan** [comment]
@Estrusco thx
any idea how to make radios out of DB table?

**Comment by AbhishekhHugar** [comment]
can i get a example of radio button
