### ISSUE TITLE
Visual Studio 2017; Support for Serene planned?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2044]
Good evening Volkan,

are you planning to Support VS 2017 soon?

With kind regards,

John

**Comment by VictorTomaili** [comment]
We are trying with Volkan ceylan at the moment. But vs2017 has a bug.

**Comment by JohnRanger** [comment]
Thanks Victor for your feedback. I know you are in the "inner" circle so your Feedback is very welcome :-)

With kind regards,

John
