### ISSUE TITLE
Line Total formula 

### ISSUE THREAD

**Issue by MunsterUSMC** [volkanceylan/Serenity#2047]
Not a problem but thought I could at leased give you the only code I could fix.

Using this will calculate the discount correctly. See the screenshot below.
`[DisplayName("Line Total"), Expression("(t0.[UnitPrice] * (1 - t0.[Discount]) * t0.[Quantity])")]`

![screen shot 2017-03-12 at 11 56 01 pm](https://cloud.githubusercontent.com/assets/26091852/23842007/8a0bef88-077f-11e7-896c-b22564f91b0d.png)

Great work on the program!

Sincerely, 
MunsterUSMC

**Comment by volkanceylan** [comment]
I'm not sure if Discount is a percentage from price, or amount to reduce from price or amount to reduce from total. Thanks, wonder if there is some doc about this.
