### ISSUE TITLE
SCTask Errors in Visual Studio 2017

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#2049]
If you are still using Saltaralle and get some errors on SCTask.dll in Visual Studio 2017, open an administrative command prompt:

```cmd
> cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
> "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\gacutil.exe" /i Microsoft.Build.dll
> "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\gacutil.exe" /i Microsoft.Build.Framework.dll
```

This works for community version default install location, change your folder if you are using Professional, Enterprise etc.

This made me lose a few hours to resolve...

**Comment by c9482** [comment]
Hi @volkanceylan,

I have an old Saltarelle based app which requires a small change and I am getting the following error:

The "SCTask" task failed unexpectedly.

> 2>C:\ngs-projects\LCBudgetsProduct\packages\Saltarelle.Compiler.2.7.0\tools\Saltarelle.Compiler.targets(32,3): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. 

I tried following your tip adjusting it to Visual Studio 2019 CE but I get the error:

> Failure adding assembly to the cache:   The system cannot find the file specified.

I have no files in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin folder except for one folder named Roslyn. Where do I find those 2 missing assemblies? Many thanks in advance.

**Comment by c9482** [comment]
For VS19, these assemblies are actually located in: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin

However, still getting the following error (even though the project appears to be running fine):

> Running transformation: System.IO.FileNotFoundException: Could not find file 'C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Script\bin\debug\Serenity.Script.Imports.dll'.File name: 'C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Script\bin\debug\Serenity.Script.Imports.dll'   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)   at Microsoft.VisualStudio.TextTemplating5FC9B993D1F2E2E20B16792E1E7686911D099565B7370833B723E6DF22378E8F4EE0086DD2EAF86153FD9B8772FD9144297567C857B07FA69A33B3F0765CA025.GeneratedTextTransformation.SSTypeLister..ctor(String[] assemblies)   at Microsoft.VisualStudio.TextTemplating5FC9B993D1F2E2E20B16792E1E7686911D099565B7370833B723E6DF22378E8F4EE0086DD2EAF86153FD9B8772FD9144297567C857B07FA69A33B3F0765CA025.GeneratedTextTransformation.TransformText() | Solution 'LCBudgets' ‎(2 of 5 projects) | C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Common\Imports\ServerTypings\ServerTypings.tt | 1 |
