### ISSUE TITLE
FieldAccessException: Cannot set a constant field.

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#205]
Hi,on my production site I get the following error:

FieldAccessException: Cannot set a constant field.

I do not get this on my development environment.

The web.config points to the same database instance in both environments.

This is the full error message:

[FieldAccessException: Cannot set a constant field.]
   System.Reflection.RtFieldInfo.PerformVisibilityCheckOnField(IntPtr field, Object target, RuntimeType declaringType, FieldAttributes attr, UInt32 invocationFlags) +0
   System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark) +255
   System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture) +36
   Serenity.Data.RowFieldsBase.Initialize() +1609
   Serenity.Data.RowExtensions.Init(TRowFields rowFields) +12
   ResearcherWeb.Researcher.Entities.AuthorRow..cctor() +44

[TypeInitializationException: The type initializer for 'ResearcherWeb.Researcher.Entities.AuthorRow' threw an exception.]
   ResearcherWeb.Researcher.Entities.AuthorRow..ctor() +17

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +113
   System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +232
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +83
   System.Activator.CreateInstance(Type type) +66
   Serenity.Data.RowRegistry.Initialize() +148
   Serenity.Data.RowRegistry.EnsureRegistry() +14
   Serenity.Data.<EnumerateRows>d__8.MoveNext() +66
   Serenity.Localization.EntityLocalTexts.Initialize(String languageID) +102
   Serenity.Web.CommonInitialization.InitializeLocalTexts() +119
   Serenity.Web.CommonInitialization.Run() +38
   ResearcherWeb.SiteInitialization.ApplicationStart() +343
   ResearcherWeb.Global.Application_Start(Object sender, EventArgs e) +195

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9918157
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9932052
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

**Comment by volkanceylan** [comment]
Your hosting provider is probably on medium trust. If you can't ask them to grant high/full trust, you need to replace all "public static readonly" field declarations to "public static ".

**Comment by wpvking** [comment]
Will I have to do this for all "public readonly" fields as well?

**Comment by volkanceylan** [comment]
Sorry *public readonly* in *Row.cs.

**Comment by volkanceylan** [comment]
Btw, it looks like ASP.NET has made medium trust obsolete.

http://stackoverflow.com/questions/16849801/is-trying-to-develop-for-medium-trust-a-lost-cause

Need to change your hosting provider.

**Comment by wpvking** [comment]
I see I have a problem. Removing all the "readonly" declarations, yields the following error:

Description: The application attempted to perform an operation not allowed by the security policy.  To grant this application the required permission please contact your system administrator or change the application's trust level in the configuration file. 

Exception Details: System.Security.SecurityException: Request failed.

Let's see what the isp does with my request. :(
