### ISSUE TITLE
UpdatableExtensionBehavior with [Origin] Field - Bug Correct 

### ISSUE THREAD

**Issue by claudiovolpato** [volkanceylan/Serenity#2050]
I upgraded the library and now it works but I'm not sure is the best method

UpdatableExtensionBehavior

        public override void OnPrepareQuery(ISaveRequestHandler handler, SqlQuery query)
        {
            base.OnPrepareQuery(handler, query);

            foreach (var field in handler.Row.GetFields())
            {
                if (field.Join != null )    query.Select(field); 
            }

        }

[https://github.com/volkanceylan/Serenity/issues/2037](https://github.com/volkanceylan/Serenity/issues/2037)

**Comment by volkanceylan** [comment]
You can use GetTableFields
