### ISSUE TITLE
Results by groups in the top

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2052]
Hello! Prompt please, It is possible to transfer results of aggregation in heading of group?
![group](https://cloud.githubusercontent.com/assets/26430136/23940623/b6548372-0976-11e7-85ea-98b92fe6a3b9.JPG)

**Comment by Zahar661** [comment]
formatter: x => x.value + ' ' + x.totals.sum.Summa,

It turned out this way, but so far the format and rounding can not be applied

**Comment by Zahar661** [comment]
formatter: x => x.value + ' ' + (Math.round(x.totals.sum.Summa * 100) / 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,'),

Maybe not the most elegant, but it works!

**Comment by volkanceylan** [comment]
Totals in group headers not supported, but you can put it on title like you did, just as count
