### ISSUE TITLE
Useful Tool: Typewriter 

### ISSUE THREAD

**Issue by uwascan** [volkanceylan/Serenity#2053]
@All Checkout this tool called Typewriter [https://kamranicus.com/posts/2016-02-02-typewriter   and http://frhagn.github.io/Typewriter/index.html] it may be very useful to th Community

**Comment by williamhodges** [comment]
interesting, thanks for sharing!

**Comment by uwascan** [comment]
Typewriter Workthrough [https://www.linkedin.com/pulse/typewriter-typescript-webapi-oh-my-justin-kirkwood]

**Comment by JohnRanger** [comment]
jep, thanks for this Information. Very interesting.

With Kind regards,

John

**Comment by volkanceylan** [comment]
We are already generating import classes. Couldnt see what is plus of this. But thanks anyway for sharing.
