### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by naushadqamar** [volkanceylan/Serenity#2056]
Everything was working fine after generating new form i got npm err during build here is the log :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tsc' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info lifecycle serene@1.0.0~pretsc: serene@1.0.0
6 silly lifecycle serene@1.0.0~pretsc: no script for pretsc, continuing
7 info lifecycle serene@1.0.0~tsc: serene@1.0.0
8 verbose lifecycle serene@1.0.0~tsc: unsafe-perm in lifecycle true
9 verbose lifecycle serene@1.0.0~tsc: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\i\Documents\Visual Studio 2015\Projects\xxxx\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\i\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Users\i\AppData\Local\Microsoft\WindowsApps;C:\Users\i\AppData\Roaming\npm
10 verbose lifecycle serene@1.0.0~tsc: CWD: C:\Users\i\Documents\Visual Studio 2015\Projects\xxxx.Web
11 silly lifecycle serene@1.0.0~tsc: Args: [ '/d /s /c', 'tsc -p ./tsconfig.json' ]
12 silly lifecycle serene@1.0.0~tsc: Returned: code: 2  signal: null
13 info lifecycle serene@1.0.0~tsc: Failed to exec tsc script
14 verbose stack Error: serene@1.0.0 tsc: `tsc -p ./tsconfig.json`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid serene@1.0.0
16 verbose cwd C:\Users\i\Documents\Visual Studio 2015\Projects\adminPanel\H4cAdminPanel\H4CAdminPanel\H4CAdminPanel.Web
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error serene@1.0.0 tsc: `tsc -p ./tsconfig.json`
22 error Exit status 2
23 error Failed at the serene@1.0.0 tsc script 'tsc -p ./tsconfig.json'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the serene package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc -p ./tsconfig.json
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs serene
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls serene
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Estrusco** [comment]
See if this https://github.com/volkanceylan/Serenity/issues/1859 help you

**Comment by volkanceylan** [comment]
Run tsc manually in a command prompt and see what errors you got
