### ISSUE TITLE
EditorUtils.setReadOnly(true) does not work for HtmlNoteContentEditor

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#2057]
In Typescript, Serenity.EditorUtils.setReadOnly(this.form.MyHtmlNoteContentColumn, true); sets the textarea readonly=readonly, but does not change the contenteditable=false in the associated s-HtmlContentBody body. Since the textarea is invisible and not the actual control used to capture/enter text, this isn't sufficient.

Marking the column as ReadOnly(true) in the .cs performs readonly correctly.

**Comment by volkanceylan** [comment]
You need to use one that accepts a Widget (setReadOnly), not jQuery object (setReadonly).

**Comment by wldkrd1** [comment]
Hmm. Yup, that's what I'm using...

![setreadonly2](https://cloud.githubusercontent.com/assets/2817543/24004966/f6eb6438-0a24-11e7-964a-1c49bd85a349.png)

**Comment by volkanceylan** [comment]
Well thats also what PropertyGrid is using to set read only:

```cs
                bool readOnly = item.ReadOnly == true || !CanModifyItem(item);
                EditorUtils.SetReadOnly(editor, readOnly);
                EditorUtils.SetRequired(editor, !readOnly && Q.IsTrue(item.Required) && 
                    (item.EditorType != "Boolean"));
```

You should also use updateInterface for such work and call base method always.

**Comment by wldkrd1** [comment]
`
$Serenity_EditorUtils.setReadOnly = function(widget, isReadOnly) {
		var readOnly = ss.safeCast(widget, $Serenity_IReadOnly);
		if (ss.isValue(readOnly)) {  // readOnly is null, so this isn't called
			readOnly.set_readOnly(isReadOnly);
		}
		else if (widget.element.is(':input')) {
			$Serenity_EditorUtils.setReadonly(widget.element, isReadOnly); // this is called on the jQuery object
		}
`

Stepping through, readOnly is coming up as null so it never attempts the set_readOnly() call

**Comment by wldkrd1** [comment]
Thanks for your recent work on this. The CKEditor is not $instanceReady by the time updateInterface() is called, but I can set it to readonly successfully within a setTimeout() block called from there.

**Comment by volkanceylan** [comment]
Ok will have another look

**Comment by wldkrd1** [comment]
Maybe expose the InstanceReady event from the CKEditor onto the parent HtmlContentEditor so our code can attach event handlers to it? That way we won't have to guess at when it might be ready.

**Comment by marcobisio** [comment]
Hi guys,
I've just completed the porting of the HtmlContentEditor to TypeScript and I managed to solve the readonly issue this way:

    set_readOnly(value: boolean): void {
        if (this.get_readOnly() != value) {
            if (value)
                this.element.attr("disabled", "disabled");
            else
                this.element.removeAttr("disabled");
    
            var instance = this.getEditorInstance();
            if (instance != null && instance.status == 'ready') {
                instance.setReadOnly(value);
            } else {
                instance.on("instanceReady", function (event) {
                    instance.setReadOnly(value);
                });
            }
        }
    }

Note that in the last versions of CKEditor, the status are changed (http://docs.ckeditor.com/#!/api/CKEDITOR-property-status).

I can also share the entire code if someone needs it!

Bye
