### ISSUE TITLE
To the implementation of the .net Core

### ISSUE THREAD

**Issue by TomaszKustra** [volkanceylan/Serenity#2058]
Settings in different locations are read in different ways, eg. ScriptBundleManager (does not work), LocalTextScript, UploadSettings.
Folder names should be unified except in linux "Scripts" <> "scripts" "Site" <> "site", etc.

**Comment by volkanceylan** [comment]
I think settings work as they should. You might be right about folders, can you try with 2.9.19?

**Comment by TomaszKustra** [comment]
ScriptBundleManager -  .Net Core - don't work, try read appsetings like in ScriptBundleManager and like in UploadHelper You'll see.

The code that reads properly tested and settings:
`[SettingScope("Application"), SettingKey("ScriptBundling")]`
`public class ScriptBundlingSettings`
`    {` 
`       public bool? Enabled { get; set; }`
`     public bool? Minimize { get; set; }` 
`       public bool? UseMinJS { get; set; }`  
`  }`
......... 
`var settings=Serenity.Config.TryGet<ScriptBundlingSettings>();`

**Comment by TomaszKustra** [comment]
Example implementation (MyScriptBundleManager, MyHtmlScriptExtensions) in the attached file, in the file _LayoutHeader.cshtml changed Html.Script (...) -> Html.MyScript (...) - and working properly.

[MyScriptBundleManager.txt](https://github.com/volkanceylan/Serenity/files/849245/MyScriptBundleManager.txt)

**Comment by volkanceylan** [comment]
This should be working in latest
