### ISSUE TITLE
The version of SQL Server in use does not support datatype ‘datetime2

### ISSUE THREAD

**Issue by MaximilianoSoftur** [volkanceylan/Serenity#2059]
Hello volkanceylan, when I want to create a user, I get the following error 
I have SQL Server 2005

Thank you

**Comment by JohnRanger** [comment]
Hi MaximilianoSoftur,

according to Microsoft, the Extended Support for SQL 2005 has ended nearly 1 year ago (https://www.microsoft.com/en-us/cloud-platform/sql-server-2005). So it is generally not recommended to continually using this Version for production. :-)

And for development, you can easily get SQL 2012 express to 2016 express for free. 

Regarding your error: Maybe some suggestions on the following page will help you:

http://stackoverflow.com/questions/10224406/the-version-of-sql-server-in-use-does-not-support-datatype-datetime2

With Kind regards,

John

**Comment by volkanceylan** [comment]
See dialects topic
