### ISSUE TITLE
Popup Lookup

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#206]
I need a lookup editor so that users can select record by filtering certain search criteria. (Popup looks like serenity main grid).

In serenity, Is it possible to use a grid as lookup?

Regards

**Comment by volkanceylan** [comment]
Not possible with default lookup. You need to use bootstrap pull down or a dialog to show grid for selection, but i dont have a sample.

**Comment by dfaruque** [comment]
I want to show a icon at right of dropdown  just like inplace add. how can i do that?
After that how to show a dialog.

**Comment by volkanceylan** [comment]
Check DateTimeEditor source for a sample
