### ISSUE TITLE
Exporting DateTime value in PDF

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#2060]
We save all our dates in UTC format in our tables, and during display, all dates are shown in local time zone based on user location.
When we export to PDF, it exports in user local time zone. Is there anyway (using decorator or any other means), that date values can be exported to PDF as UTC with user time zone info?

**Comment by volkanceylan** [comment]
PDF displays whatever shown in column. You may try writing a formatter for pdf column, see formatting samples with PDF exports

**Comment by XDDDev** [comment]
Would you please us know where can we find this sample?

**Comment by volkanceylan** [comment]
file xyz.cs line 13578, come on don't be lazy, how many pdf export samples there
