### ISSUE TITLE
Custom formatting of slickgrid

### ISSUE THREAD

**Issue by klangley-toyo** [volkanceylan/Serenity#2062]
I am trying to put the filters from a grid into a collapsed-box and put the quicksearchbar in the header of the collapsed-box with the actual grid displaying in another box on the page. How can I do this?
Here is a sample of what I am trying to do
`<div class="row">`  
 ` <div class="box box-default collapsed-box box-solid">`
       ` <div class="box-header with-border">`
           ` <div class="box-tools pull-left">`
                `<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>`
          `  </div>`
         `   <div class="box-title"><h3>Filters</h3>  Search box goes here</div>`
      `  </div>`
        `<div class="box-body">`
		`Filters go here`
        `</div>`
   ` </div>`
`</div>`
`<div class="row">`
    `<div class="col-md-3">`
       ` <div id="MyProjectsList">`
        `    grid goes here`
        `</div>`
    `</div>`   
`</div>`

Thanks to anyone who can help me

**Comment by volkanceylan** [comment]
This could be some jQuery magic, but can't guide sorry
