### ISSUE TITLE
Adding Button to Dialog unique location

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#2063]
I need to add 2 buttons to a dialog but NOT in the toolbar. I would like to put them under a category-anchor if possible. Thanks in advance.

**Comment by in32bit** [comment]
Use jquery to access and add element in the form after load entity.

**Comment by Estrusco** [comment]
You can also use a template for your dialog - XYZDialog.template.html - for write your HTML code

```html
<div class="s-DialogContent">
    <div id="~_Toolbar" class="s-DialogToolbar">
    </div>
    <div class="s-Form">
        <form id="~_Form" action="">
            <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                <div id="~_PropertyGrid"></div>

                <button id=MyButton>Your button</button>
                <div class="clear"></div>
            </div>
        </form>
    </div>
</div>
```

then get element by id=MyButton with jQuery and, as said @in32bit attach in your DOM element.
