### ISSUE TITLE
.Net Core DynamicScriptMiddleware - exception : Headers are read-only, response has already started.

### ISSUE THREAD

**Issue by TomaszKustra** [volkanceylan/Serenity#2064]
When enabled ScriptBundling on .Net Core DynamicScriptMiddleware throws exception:

 

> Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
>       An unhandled exception has occurred: Headers are read-only, response has already started.
> System.InvalidOperationException: Headers are read-only, response has already started.
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
>    at Serenity.Web.Middleware.DynamicScriptMiddleware.<ReturnScript>d__4.MoveNext()
> 

The problem described on stackoverflow

[http://stackoverflow.com/questions/37918547/middleware-to-set-response-contenttype](http://stackoverflow.com/questions/37918547/middleware-to-set-response-contenttype)

[log.txt](https://github.com/volkanceylan/Serenity/files/849885/log.txt)

**Comment by volkanceylan** [comment]
ScriptBundling didn't work as you suggested, please try with latest template

**Comment by TomaszKustra** [comment]
Problem with new version sill exists! Exception throws in DynamicScriptMiddleware and it's associated with .net core Kestrel server requests processing.
Please start with enabled ScriptBundling :  dotnet Serene1.Web.dll you'll see exception.

The problem described on stackoverflow
[http://stackoverflow.com/questions/37918547/middleware-to-set-response-contenttype](http://stackoverflow.com/questions/37918547/middleware-to-set-response-contenttype)

**Comment by volkanceylan** [comment]
I already started with ScriptBundling and i get no such error, sorry

**Comment by TomaszKustra** [comment]
I sent you details of my test environment.
