### ISSUE TITLE
Visual Studio 2017 template project creation error: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by angeor2** [volkanceylan/Serenity#2066]
I'm having trouble creating a Serenity project using the Serene Template (2.9.19.0) on a fresh installation of Visual Studio 2017.

Tried both the Serene.Template and the SereneCore.Template options, once I press OK on the project creation wizard I get an error message: 'The given key was not present in the dictionary'.

I've reinstalled the vsix, with no luck.

**Comment by volkanceylan** [comment]
My VS2017 Community doesn't have this error. Can you provide exact version you see in About dialog?

**Comment by angeor2** [comment]
Visual Studio/15.0.0+26228.9

I've noticed that there is something weird with the proposed project name as you may see in the screenshot. This may be irrelevant of course...

![screenshot 264](https://cloud.githubusercontent.com/assets/24318853/24075355/20ba2f20-0c22-11e7-934f-6e67c0a2ab94.png)

**Comment by volkanceylan** [comment]
These are probably broken templates, i also saw them now. They shouldn't be visible as they are subprojects. You should see actual templates under Visual C# and they should be named Serene and Serene (Asp.Net Core Beta) with Serenity logo.

**Comment by volkanceylan** [comment]
With capital letters, e.g. SERENE

**Comment by angeor2** [comment]
Yes, you are right, I found the templates, they are working fine...

Sorry about the false alarm!

**Comment by volkanceylan** [comment]
Np, thanks its something i should look into
