### ISSUE TITLE
Downloaded extension doesn't contain any templates error

### ISSUE THREAD

**Issue by ckelsoe** [volkanceylan/Serenity#2071]
I am attempting to create a new Serenity project in VS 2017. I am getting this error when I try to create a new project using the template: "Downloaded extension doesn't contain any templates". I have uninstalled and reinstalled VS 2017 in the event something was an issue with my install. I also am starting VS 2017 as administrator. I have Googled the error to see if I can find some tips on resolving this. So far no success. Any help is appreciated.

**Comment by volkanceylan** [comment]
I can't reproduce this. Your VS2017 installation might be lacking some optional parts, e.g. .NET Core, Web Development, Desktop Development etc.

**Comment by volkanceylan** [comment]
Also uninstall the extension and install it from New Project => Online, VS should restart

**Comment by ckelsoe** [comment]
I have tried that - I will run through the steps again. I also uninstalled and reinstalled VS 2017 and made sure I had the correct optional parts. Looks like I have a very localized issue.

**Comment by ynotlim** [comment]
I am getting the same issue.

**Comment by edson** [comment]
I have this issue if I try to create through Online -> Templates -> Serene

![image](https://cloud.githubusercontent.com/assets/62490/24152605/e26b21e2-0e2a-11e7-8d77-e5a5ebdcbca3.png)

But it's template is actually listed in Installed -> Templates ->Visual C#
![image](https://cloud.githubusercontent.com/assets/62490/24152774/5d6208ac-0e2b-11e7-9b4b-0bfd211665e2.png)

So it works:

![image](https://cloud.githubusercontent.com/assets/62490/24152821/822a522a-0e2b-11e7-828f-df870ec14124.png)


Best Regards

**Comment by volkanceylan** [comment]
Thanks @edson, can you share your VS About dialog so i could check what is different than my VS2017?

**Comment by edson** [comment]
Hi @volkanceylan 

Sure. There it is:

Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA780
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017   00369-60000-00001-AA780
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA780
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA780
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA780
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.3.50201.08
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

![image](https://cloud.githubusercontent.com/assets/62490/24154576/52cefcc4-0e30-11e7-9012-fbbbb1b1c2a1.png)


Best Regards

**Comment by volkanceylan** [comment]
Version is similar, i'm using Community though, can you uninstall Serene and try with 2.9.20.4?

**Comment by volkanceylan** [comment]
Here is what i get when i download Serene from Visual Studio => New Project => Online => Templates section

![image](https://cloud.githubusercontent.com/assets/752470/24158151/2e3c7de4-0e64-11e7-8494-a4b458b4df28.png)

This causes Visual Studio 2017 to close and install Serene. VS2017 requires itself to close to install extensions. This is not specific to Serene. 

After installation, i have to open Visual Studio again manually and if you go to Online section again, i see this error message:

![image](https://cloud.githubusercontent.com/assets/752470/24158332/ad262a7e-0e64-11e7-8c5e-73707799d07d.png)

So i think this is a Visual Studio 2017 bug. For now, you should use **Installed** section to create projects after installing Serene, not **Online** again...

**Comment by edson** [comment]
@volkanceylan The results from installing again are the same as you posted. (Using Enterprise Trial)

Seems like a VS2017 bug to me too. I have no problem with that... but newcomers from VS2015 may see this as confusing...

Best Regards

**Comment by volkanceylan** [comment]
Yes, not just ones from VS2015 but also ones who are trying it first time, finding it under Online section by luck. Hope MS will fix it soon or i'll be able to find a workaround.

![image](https://cloud.githubusercontent.com/assets/752470/24159324/79d6e0a2-0e67-11e7-84ff-847e965407aa.png)

**Comment by john20xdoe** [comment]
We can catch their attention by emailing to vsfeedback@microsoft.com. ( as per http://stackoverflow.com/questions/40656621/how-to-feedback-in-visual-studio-2017-when-report-a-crash-crashes)
(i did not send email, please do)

or 

filing an issue (which may take some time =( )
https://connect.microsoft.com/VisualStudio/Feedback

Hope this does not affect Serene's VS Gallery rating.
