### ISSUE TITLE
Question: Method to add Excel/PDF Export on all forms?

### ISSUE THREAD

**Issue by mreid2005** [volkanceylan/Serenity#2072]
I'm new to quite a lot of this but I have gotten to the point that I can add manually 'edit filters', 'excel and pdf export', and multi-tabbed dialogues to name a few tasks I have gotten a handle on.  while working on the export portion after about my fifth time of doing the same steps with only slight differences each time I figured I may be better off asking here if there is a 'common' file or location I should be enabling/editing to allow excel and pdf format on all items created by sergen.  Since my use cases 99% of the time will require the export and edit filter functionality.  

Any insight is appreciated. 
And thank you Volkanceylan for making me look like a rockstar @ work by creating this template, I'm glad I stumbled across it.

**Comment by volkanceylan** [comment]
There is no simple way to add it in a common location. You might define a base class or replace javascript prototype but its a bit like vodoo magic, so better use normal way.

**Comment by mreid2005** [comment]
Okay, thanks :) I kindof thought if it was "straightforward" you likely would have already implemented it. But figured it wouldn't hurt to ask.
Thanks for sharing this template with the world it is very useful!
