### ISSUE TITLE
System.NullReferenceException: Serenity.CodeGenerator.ProjectFileHelper

### ISSUE THREAD

**Issue by marcipunk** [volkanceylan/Serenity#2073]
Dear Everybody!

I'd like to try Serenity Framework .net.Core version.
I have installed it, it works on localdb with the Default and Northwind databases.

As a next step I've downloaded Serenity.CodeGenerator (v 2.9.20) with NuGet for the solution.
I can run it from the Package Manager Console, but when I choose a table from a database (connection string is correct), and press on Generate Code for Checked Entites, it throw me an exception:

```
System.NullReferenceException: object reference not set to an instance of an object
the next place. Serenity.CodeGenerator.ProjectFileHelper <> c__DisplayClass0_0 <AddFileToProject> b__0 (string filename).
 The following locations: Serenity.CodeGenerator.ProjectFileHelper.AddFileToProject (String Project file, code file String, String dependentUpon)
at Serenity.CodeGenerator.EntityCodeGenerator.Run ()
 The following locations: Serenity.CodeGenerator.MainWindow.GenerateCodes_Click (Object sender, RoutedEventArgs e)
```

After OK, it generate only a row.cs.

Can anyone suggest something to solve this proplem?

**Comment by volkanceylan** [comment]
That Sergen is for .NET Framework, not .NET Core version. See my blog post for how to work with .NET core version.
