### ISSUE TITLE
LookupEditor Issue

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#2075]
I  Use LookupScript in  my XYZRow ,   The  ABCRow  use LookupEditor to get Value from XYZRow.
When I add some record  in my XYZRow.  It will not be synchronized immediately When I edit in ABCRow.
How Can I solve  it?

**Comment by sayuga** [comment]
Q.ReloadLookup() allows to manually refresh lookups. A quick search should show a couple samples. You can also use LookupScript("xyz.abc", Expiration =  -1). If you do a search through the issues, this has actually been asked a couple times too.

**Comment by weiguanhai** [comment]
My version is  too low that I can't use Expiration param ,  Can I use Q.reloadLookup? Where  should I use it?
@sayuga
