### ISSUE TITLE
SqlQuery Select with Join

### ISSUE THREAD

**Issue by jonathan82** [volkanceylan/Serenity#2077]
I hope this isn't a stupid questions but how do I do a select with join on multiple tables using the built-in Serenity.Data system?  It looks like I can do so using a dynamic object but I'd like to be able to select from multiple tables and get back strongly typed Row objects.

Also is there an example of how I can use SqlQuery object to generate a query with multiple joins, select from multiple tables?
 
Thanks

**Comment by DavorDumeljic** [comment]
https://github.com/volkanceylan/Serenity/blob/master/Serenity.Data/Join/Join.cs
