### ISSUE TITLE
How to show column name for column id

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#208]
I have a very basic issue in column generating while on mapping.The problem is that I want to display name of the entity of its respected ID.As you have done in Order->Order Details->Add new order.Then it display in column ProductName for productId.I want to do same but I am going somewhere wrong.as soon as i click on SAVE it disappears  from column.I am following to your code but still not achieve it.

**Comment by volkanceylan** [comment]
See OrderDetailEditor ValidateEntity method for how i set product name by using lookup.
