### ISSUE TITLE
Override BeforeSave

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2080]
I add an override function for BeforeSave,
```
private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                if (Row.SalesOrder == null)
                {
                    Row.SalesOrder = "3333444466";
                }
            }
        }
```

but after i add this function, i always got this error 'Did not realize the method or operation. '

**Comment by PanChenhao** [comment]
i test a lot. and found if i remove the attribute [identity] from below
```
[DisplayName("Sales Order"), Column("salesOrder"), Size(20), PrimaryKey,Identity, QuickSearch]
        public String SalesOrder
        {
            get { return Fields.SalesOrder[this]; }
            set { Fields.SalesOrder[this] = value; }
        }
```
create will be success. but actually, i don't want user to change this field, because SalesOrder is the PrimaryKey。 and while creating, this field will be generate automatic.

**Comment by Estrusco** [comment]
If a field is an Identity field it is automatically incremented and you can not set it. 
If you don't want the user change it set [Insertable(false), Updatable(false)]

And see https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/SerialAutoNumber if can help you

**Comment by PanChenhao** [comment]
Thanks you, i found the solution.
