### ISSUE TITLE
Error npm

### ISSUE THREAD

**Issue by vaskopm** [volkanceylan/Serenity#2082]
Hi:

I am having this error when building a project in visual studio:

21 error code ELIFECYCLE
22 error serene@1.0.0 tsc: `tsc -p ./tsconfig.json`
22 error Exit status 2
23 error Failed at the serene@1.0.0 tsc script 'tsc -p ./tsconfig.json'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the serene package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc -p ./tsconfig.json

I am using visual studio 2013 with tsc version 1.0. 

With serenity I need 2.1+ tsc version.

However, in Visual Studio 2013 the maximum version is 1.8.

How do I solve that?

**Comment by brunobola** [comment]
Install VS2015 community, now that even VS2017 is released, I can see no reason for VS2013 be a better choice.

**Comment by volkanceylan** [comment]
Yep, agree, VS2013 no longer supported
