### ISSUE TITLE
Hide grid-toolbar and s-QuickSearchBar in Grid 

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#2086]
Please, how can I hide these items (grid-toolbar and s-QuickSearchBar)?

With a template xyzGrid.Template.html?

Thank you

**Comment by dfaruque** [comment]
in your grid constructor 
use jQuery to play with html.

**Comment by Estrusco** [comment]
Overraide createToolbar and createQuickFilters

```ts
protected createToolbar(): void {
}

protected createQuickFilters(): void {
}
```

**Comment by ArsenioInojosa** [comment]
Thank you.

As well createQuickSearchInput()

**Comment by ga5tan** [comment]
@Estrusco cool deal man!
Any idea how do I hide bottom navigation of the grid (it's always just a bunch of lines, so no need with heavy navigation buttons

**Comment by Estrusco** [comment]
@ga5tan if you talk about pager, you can override usePager in your xyzGrid.ts

```ts
        protected usePager(): boolean {
            return false;
        }
```

**Comment by ga5tan** [comment]
@Estrusco MAN! you are on fire. Spot on. BIG THANKS
Since I have u on the line, can u please suggest, how to replace (override) Save button with fancier Submit button at the bottom of the page (under all the entry forms)

**Comment by ga5tan** [comment]
btw where do u get info like this. Is there any other documentation besides Developers Guide?

**Comment by dfaruque** [comment]
You may try to edit the following file

`.\Views\Templates\EntityDialog.Template.html`

It will change all your dialog look.

**Comment by ga5tan** [comment]
@dfaruque  thx, I checked that, but there is not much.
and no mention of the button.
for now I guess I will just try to hide the save button and put another one with service call at the bottom.
