### ISSUE TITLE
Duplicated declaration of getContainer in Core version

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2087]
Hi all.

I've just downloaded and compiled .Net Core version of Serene in VS2017. 
I compiled, but the output say me that there is a duplicated declaration of getContainer identifier in Serenity.CoreLib.d.ts.
I not found a real duplicate.

Is there anything I can do?
![cattura](https://cloud.githubusercontent.com/assets/16304015/24293373/b7894c24-1091-11e7-8398-45ccd30b6e68.PNG)

**Comment by volkanceylan** [comment]
Set your toastr version in package.json to 2.1.32 not "^2.1.33"

**Comment by Estrusco** [comment]
Ok now works! 

Thank you @volkanceylan
