### ISSUE TITLE
Time Field

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2088]
Hey
For the life of me i cant figure out whats the best way to implement a simple Time field...

all i want is a just a simple appointment time field. What is the preferred column type in sql server and how to implement in serene?

I have Time column on my database. (i can change this if need be)
I tried TimeSpan field but when updating the form i get conversion error.
What am i missing here? 
Thanks!

**Comment by brunobola** [comment]
Try to use datetime on DB and then choose TimeEditor as default editor.

**Comment by shakazulu89** [comment]
thanks for the tip.. ill give it a try tomorrow!
