### ISSUE TITLE
Little issue with Serene installation process

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2089]
@volkanceylan  another little issue with Serene Core installation process.
I have notices that if I select only Theme Samples (AdminLTE) during installation, the installation never ends.
Also, in the file system, the directories and the files of Basic Sample, Metting, etc. are created.

![cattura2](https://cloud.githubusercontent.com/assets/16304015/24296410/4f5fc0b6-109f-11e7-8d1e-a4a9053789f4.PNG)

**Comment by mreid2005** [comment]
I'll try to reproduce.

**Comment by mreid2005** [comment]
I ran it with just theme samples selected and it created the project in a reasonable amount of time. and the modules that are initially built included - 
Administration
AdminLTE
Common
Membership

built the project and it loaded and the ThemeSamples appear properly.

**Comment by Estrusco** [comment]
OK @mreid2005 thank you, I retry

**Comment by mreid2005** [comment]
your welcome, let us know how it turns out.

**Comment by Estrusco** [comment]
I have updated VS 2017 and now works. Tnx 👍
