### ISSUE TITLE
Yetkilendirme hakkında

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#209]
Merhaba Volkan,
Kategoriler diye bir tablo olusturuyorum. Sonra Sergen ile bunun sayfalarını. Yalnız Sergen ile olustururken "Permission Key"e de "Kategoriler" yazıyorum. 
Modul'un altında yeni bir PermissonKey.cs de aşağıdaki gibi yazırlıyorum. 

`namespace Serene4.ERP
{
    public class PermissionKeys
    {
        public class Kategoriler
        {
            public const string Delete = "ERP:Kategoriler:Delete";
            public const string Modify = "ERP:Kategoriler:Modify";
            public const string View = "ERP:Kategoriler:View";
        }        
        public const string General = "ERP:General";
    }
}
`
Fakat Hakları duzenlemek ıcın geldıgımde asagıdakı gıbı bır goruntu ile karsılasıyorum. Sorum şu : Neden işaretli yerdeki gibi bir node olusturuyor da benim PermissionKey.cs e yazdıgımı dikkate almıyor. Ayrıca işaretli olanı secmezsem o kullanıcının menusunde gorunmuyor. 

![volkan](https://cloud.githubusercontent.com/assets/16984654/12867349/cd6e35b4-ccf3-11e5-8a4c-717412ca323b.JPG)

**Comment by volkanceylan** [comment]
Biryerlerde PageAuthorize("Kategoriler") kalmıştır, Page.cs, Endpoint.cs vs. kontrol edin.

PermissionKeys class ının hiçbir önemi yok, ServiceAuthorize, PageAuthorize, ReadPermission gibi attribute lardan toplanıyor key ler. Bu class sadece intellisense için.

**Comment by Olricz** [comment]
Peki yöntem her tabloya ayrı bir PermissonKey mi olusturmalı ? Eger Admin gerektiren bir durum degilse.

**Comment by Olricz** [comment]
Ok. Authorize'ları PermıssıonKey'e gore ayarlarsan oluyormus. Tesekkur ederım Volkan.

**Comment by volkanceylan** [comment]
Tek tek yapmaya gerek yok, bütün admin ekranlarına tek permission da atayabilirsiniz.
