### ISSUE TITLE
getLookUp Items Undefined

### ISSUE THREAD

**Issue by alanlopcu** [volkanceylan/Serenity#2091]
Hi guys, i'm trying this in my XYZDialog:

`alert(Administration.UserRow.getLookup().items.filter(x => x.Email === 'my.user.email@randomdomain.com')[0].DisplayName);`

This "my.user.email@randomdomain.com" exists in my database (UserRow), but my response is related to "Undefined".

If i try with Language for example, this:

```
var msg = "";
Administration.LanguageRow.getLookup().items.forEach((item, index) => {
    msg = msg + "Item: " + item.LanguageName + ", Index: " + index + "\n";
});
alert(msg);
```

I receive this: 

![image](https://cloud.githubusercontent.com/assets/22221262/24301691/3f903fec-107e-11e7-8af2-c300f67dd435.png)

It seems ok. But again, if i try this with Users:

```
var msg = "";
Administration.UserRow.getLookup().items.forEach((item, index) => {
     msg = msg + "Item: " + item.DisplayName + ", Index: " + index + "\n";
});
alert(msg);
```

I receive this:

![image](https://cloud.githubusercontent.com/assets/22221262/24301798/86209a24-107e-11e7-8a77-e419ee5f98a0.png)

(I have three users btw)

Why my User items still being "undefined" and languageRow, for example, dont. Thanks in advance!

**Comment by volkanceylan** [comment]
If you don't send display name to script you can't read.

**Comment by JohnRanger** [comment]
For anyone who arrives here because he has a similar problem: What Volkan means with "sending displayName tp script" is:

Tag the DisplayName field within xyzRow.cs with the [LookupInclude] flag. Then this field will be included within the lookup script so .Lookup() can have access to it.

Hope this helps someone.

John
