### ISSUE TITLE
Batch Editing

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2092]
How will one go about batch editing? Selecting multiple rows and editing their values? 
For example if you want to change a category for multiple items.

**Comment by PanChenhao** [comment]
Hi, i think you could refer to the Products page in NorthWind module. use SlickGrid Formatter. you also can refer to this guide [How To: Use a SlickGrid Formatter](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_use_a_slickgrid_formatter.html).
