### ISSUE TITLE
How to use MaterialLookup in validateEntity

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2095]
I create a MaterialLookup in Material Module. but when i try to use this in validateEntity function in SalesOrderItem module. it always says Scripts in not defined. How to use MaterialLookup in validateEntity?
![default](https://cloud.githubusercontent.com/assets/16734387/24329456/3132ad3c-123a-11e7-8c21-58ca841a86d5.png)

**Comment by PanChenhao** [comment]
Below code is also can be successfully running. I just confused why the MaterialLookup cannot be directly use.

```
protected validateEntity(row: SalesOrderItemRow, id: number) {
            if (!super.validateEntity(row, id))
                return false;

            row.MaterialName = MovieTutorial.Material.MaterialsRow.getLookup()
                .itemById[row.MaterialId].MaterialName;
            return true;
        } 
```

**Comment by volkanceylan** [comment]
You are in script code.
