### ISSUE TITLE
warning MSB3073: The command "cmd /c "npm" run tsc" exited with code 1

### ISSUE THREAD

**Issue by tjpatange** [volkanceylan/Serenity#2097]
Hi I'm getting such error while building the project. 
Also following is the npm-log:
[npm-log.txt](https://github.com/volkanceylan/Serenity/files/870818/npm-log.txt)

**npm ERR! Windows_NT 10.0.10586
1>  npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"

1>  run" "tsc"
1>  npm ERR! node v6.9.5
1>  npm ERR! npm  v3.10.10
1>  npm ERR! code ELIFECYCLE
1>  npm ERR! serene@1.0.0 tsc: `tsc -p ./tsconfig.json`
1>  npm ERR! Exit status 2
1>  npm ERR! 
1>  npm ERR! Failed at the serene@1.0.0 tsc script 'tsc -p ./tsconfig.json'.
1>  npm ERR! Make sure you have the latest version of node.js and npm installed.
1>  npm ERR! If you do, this is most likely a problem with the serene package,
1>  npm ERR! not with npm itself.
1>  npm ERR! Tell the author that this fails on your system:
1>  npm ERR!     tsc -p ./tsconfig.json
1>  npm ERR! You can get information on how to open an issue for this project with:
1>  npm ERR!     npm bugs serene
1>  npm ERR! Or if that isn't available, you can get their info via:
1>  npm ERR!     npm owner ls serene
1>  npm ERR! There is likely additional logging output above.
1>  
1>  npm ERR! Please include the following file with any support request:
1>  npm ERR!     C:\Users\tejas\Documents\Visual Studio 2015\Projects\MultiTenancy\MultiTenancy\MultiTenancy\MultiTenancy
1>  .Web\npm-debug.log
1>C:\Users\tejas\Documents\Visual Studio 2015\Projects\MultiTenancy\MultiTenancy\MultiTenancy\MultiTenancy.Web\MultiTenan
1>cy.Web.csproj(2689,5): warning MSB3073: The command "cmd /c "npm" run tsc" exited with code 1.**
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by volkanceylan** [comment]
Run tsc and see what errors you are getting. This is not TypeScript support forum
