### ISSUE TITLE
Custom Dialog Boxes

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#2099]
![image](https://cloud.githubusercontent.com/assets/11448029/24336939/ecb0f6ac-1264-11e7-9540-e1922a0a37fd.png)

I'm trying to figure out where the code is to create this box. I want to change the Yes and No buttons to a material design. Any idea?

**Comment by sayuga** [comment]
Look at the dialog boxes samples in the Basic Samples> Dalogs>>Dialog Boxes.

**Comment by williamhodges** [comment]
That's not what I meant but thank you for your answer. I need to location
of where the actual dialogue box div is located. I know how to get the
dialog boxes to appear. But thanks again!

**Comment by williamhodges** [comment]
what i'm looking for is a way to change like the icon, and the way the yes and no buttons look and what have you. I'm trying to find where the actual <div> is located in code to make that change but I can't seem to find it. @volkanceylan or @VictorTomaili do you guys have any idea?

**Comment by VictorTomaili** [comment]
Is this?

https://github.com/volkanceylan/Serenity/blob/master/Serenity.TypeScript.CoreLib/Q/Q.Dialogs.ts

**Comment by williamhodges** [comment]
That appears to be it! Do you know if it will be overwritten when I transform T4 or upgrade the framework? Just so I know what to be conscious about in the future.

**Comment by williamhodges** [comment]
And that appears to be in Serenity, do you know the location of it in Serene or should I fork Serenity and make the change and reference my forked project over Serenity?

**Comment by williamhodges** [comment]
Any update on this? Just curious
