### ISSUE TITLE
Is there an example for reporting?

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#210]
Is there an example for reporting?

**Comment by volkanceylan** [comment]
Not yet but in todo list

**Comment by sayuga** [comment]
One thing I did for reporting is pull in SQL Views and then bringing them in using Sergen. You'll have to set the identifier values and remove the toolbar button to edit but it works nicely since it can dynamically update according to most recent data. 

Sprinkle in the excel exporter and done.

**Comment by Olricz** [comment]
now the solution. Thanks @sayuga But I wonder what Volkan would do.

**Comment by volkanceylan** [comment]
I used SSRS, Excel, and wkhtmltopdf for reporting. I have examples but don't want to integrate them into Serene till they are good enough. When i add a not so well designed feature into Serene, it's really hard to maintain.

**Comment by Olricz** [comment]
I understand. there's no rush. I think it will be a good platform.
