### ISSUE TITLE
Grid: how to set the default value with BooleanEditor

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2100]
My code as below, but it does not work.
```
Q.first(filters, x => x.field == fld.Deliveried).init = w => {
                (w as Serenity.BooleanEditor).value = true;
            };
```

**Comment by marcobisio** [comment]
Deliveried it's a typo for "Delivered"?

Moreover where are doing this operation (I mean in which method)?
Try this:

    protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
            let filters = super.getQuickFilters();
            var fld = xyzRow.Fields;
    
            filters.push({
                type: Serenity.BooleanEditor,
                field: fld.YOUR_FIELD,
                title: "YOUR_TITLE",
                init: (w) => { (w as Serenity.BooleanEditor).value = true; }
            });
    
            return filters;
    }

Bye

**Comment by PanChenhao** [comment]
Yours  works, thank you very much. 
Before i was doing like below.
In SalesOrderItemColumns.cs file
```
[QuickFilter]
        public Boolean Deliveried { get; set; }
```
In SalesOrderItemGrid.ts file
```
protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            let filters = super.getQuickFilters();
            var fld = SalesOrderItemRow.Fields;

            Q.first(filters, x => x.field == fld.Deliveried).init = w => {
                (w as Serenity.BooleanEditor).value = true;
            };

            return filters;
        }
```

but it does not work.

**Comment by marcobisio** [comment]
You're welcome @PanChenhao
