### ISSUE TITLE
stored procedure with output parameter

### ISSUE THREAD

**Issue by ALFONSOES** [volkanceylan/Serenity#2101]
Please, I need to call a stored procedure that returns me an output parameter, as the call would be implemented.

**Comment by volkanceylan** [comment]
See Dapper docs

**Comment by Cossey** [comment]
*For anyone searching the repo for this particular issue:*

Here's a direct link to the Stored Procedure information located in the dapper docs:
https://github.com/StackExchange/Dapper/blob/master/Readme.md#stored-procedures
