### ISSUE TITLE
Why grid miss scroll bar after i upgrade the serenity to latest version

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2102]
It really trouble me a lot. and very strange. Since i upgrade my serenity to latest version  by NuGet packages.
The scroll bar of grid is missing. Could anyone hlep me?
![default](https://cloud.githubusercontent.com/assets/16734387/24402947/609e15e8-13ed-11e7-9a9b-e2bd227b4e45.png)

**Comment by PanChenhao** [comment]
i checked the CSS, seems no problem.
```
<div class="slick-viewport slick-viewport-top slick-viewport-left" tabindex="0" hidefocus="" style="overflow: auto; height: 460px; width: 100%;">
         <div class="grid-canvas grid-canvas-top grid-canvas-left" tabindex="0" hidefocus="" style="height: 443px; width: 1650px;">
```
The calculated width of .slick-viewport is 1068, width of .grid-canvas is 1653. but why there is not scroll bar for .slick-viewport

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/1342
