### ISSUE TITLE
Blank Pages for .Net Core Template with Postgres

### ISSUE THREAD

**Issue by szoora** [volkanceylan/Serenity#2103]
Hullo Volkan.
After Installation of .Net Core beta Template, the login (Default Page) is blank, even with the default database. Migration to Postgres Database is successful but I have a blank page for display of database rows. What am I doing wrong. I prefer to use postgres. Thanks

**Comment by volkanceylan** [comment]
Hullo Szoora,

This is not a proper report, so sorry.

**Comment by szoora** [comment]
After Installation of .Net Core beta Template from Visual Studio 2017, the login (Default Page) is blank when I run the project.

**Comment by volkanceylan** [comment]
Still the same

**Comment by szoora** [comment]
![image](https://cloud.githubusercontent.com/assets/10994696/24418617/379f6090-13f5-11e7-8e4b-ce5a32a345e7.png)
New Installation of core template - beta. That is all I see when I run the project. I expect a login page just like the one from the mvc template. Thx

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/wiki/Issue-Guidelines
