### ISSUE TITLE
Unable to translate or do not find the translation page

### ISSUE THREAD

**Issue by tobesoeasy** [volkanceylan/Serenity#2106]
![qq 20170329221420](https://cloud.githubusercontent.com/assets/13215836/24459094/4c84805c-14cd-11e7-977c-6540443fc4db.png)
  
Dear friend
Cannot find the translation entry in page "Administration/Translation" 
The "sergen.exe" files generated by many can not find the translation of page
What should I do?

**Comment by PanChenhao** [comment]
你可以试试在Modules/Texts.cs 文件里增加CMS.Fast.Link.Link

**Comment by tobesoeasy** [comment]
还是不行,可能是一个模型我生成了几次,但是命名空间不一样,不晓得怎么回事

**Comment by PanChenhao** [comment]
在你的XYZRow.cs文件里看看 InstanceName的属性是什么，通常这个属性影响新增按钮的显示名称。
```
[ConnectionKey("Default"), TableName("[dbo].[customers]"), DisplayName("客户"), InstanceName("客户"), TwoLevelCached]
    [ReadPermission("Customer:Read")]
    [ModifyPermission("Customer:Change")]
    public sealed class CustomersRow : Row, IIdRow, INameRow
```

**Comment by tobesoeasy** [comment]
[ConnectionKey("Default"), TableName("[dbo].[Classifictions]"), DisplayName("Classifictions"), InstanceName("Classifictions"), TwoLevelCached]
    [ReadPermission("Articles.Classification")]
    [ModifyPermission("Articles.Classification")]
    [LookupScript("Articles.ClassifictionsRow")]
    public sealed class ClassifictionsRow : Row, IIdRow, INameRow

这个代码是生成的 除了LookupScript  之前是可以翻译  后来突然不行了  
原因是这样的 :
这个类原来是仅仅给文章使用的  后来拓展了字段 可以给多个模型使用,所以就给每个模型都生成了一个
cms.model1.Classifictions
cms.model2.Classifictions
cms.model3.Classifictions
....
第一天只有model1 显示翻译(其他的在翻译页面找不到) 之后就完全没了,找不到,手写翻译也不行(写入位置,appdata or Script  都进行尝试过 无效果),现在的解决方案是只生成一次这个模型,正常...
源码我也阅读了  没找到问题,技术不精,还需要努力学习,多谢PanChenhao ☺

**Comment by PanChenhao** [comment]
我是在第一个命名空间里生成多个类。如下面两个
第一个
```
namespace yp.Sales.Entities
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;

    [ConnectionKey("Default"), DisplayName("销售订单明细"), InstanceName("订单内容"), TwoLevelCached]
    [ReadPermission("Sales:Read")]
    [ModifyPermission("Sales:Change")]

    public sealed class SalesOrderItemInSalesOrderRow : Row, IIdRow, INameRow
    {

        [DisplayName("id"), Column("id"), Identity]
        public Int32? Id
```

第二个
```
namespace yp.Sales.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), DisplayName("销售订单明细"), InstanceName("订单内容"), TwoLevelCached]
    [ReadPermission("Sales:Read")]
    [ModifyPermission("Sales:Change")]
    public sealed class SalesOrderItemRow : Row, IIdRow, INameRow
    {
```

不确定是否可以帮到你，仅供参考。

**Comment by tobesoeasy** [comment]
DisplayName("销售订单明细"), InstanceName("订单内容") 你在这里直接写上中文了 ,我是想利用这个翻译系统来操作,可以随时修改,我们做法有些不同,你的更直接些

**Comment by PanChenhao** [comment]
哦，我目前不需要多语言。所以我都直接写上中文了。

**Comment by tobesoeasy** [comment]
恩 谢谢你了
