### ISSUE TITLE
How can I show warning if I close without saving?

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#211]
How can I show warning if I close without saving?

**Comment by volkanceylan** [comment]
You can attach to dialogclose event, prevent it and ask for confirmation

**Comment by Olricz** [comment]
"Yeni Müşteri" ekranını kapatırken bi mesaj veren ornek yazabilir misin Volkan ? 
Selamlar

**Comment by volkanceylan** [comment]
Son şablonda ekledim.

**Comment by Olricz** [comment]
Son sablon derken ?

**Comment by volkanceylan** [comment]
Gallery, Serene

**Comment by Olricz** [comment]
ok. Çok tesekkur ederim.
