### ISSUE TITLE
getLookup kayıt getirmiyor.

### ISSUE THREAD

**Issue by kingcoskun** [volkanceylan/Serenity#2110]
Merhaba,

Master ve MasterDeneme adlı iki entity var. Master Diyaloğundan, MasterDeneme diyaloğuna buton ile verileri clikcte kaydettiriyorum. Butonu değiştirip Master diyaloğu kapanmadan kaydetmiş olduğum verileri kullanarak MasterDeneme diyaloğunu açtırmaya çalışıyorum. 

 Q.first(Serenity.MasterDenemeRow.getLookup().items, x => x.EntityType == "Serenity.Master" && x.EntityId == this.Deneme.Id).Id; } catch (e) { }
 ile lookupi çağırmak istiyorum fakat kayıt dönmüyor.   

Q.reloadLookupAsync('Serenity.MasterDenemeRow') 
ile lookup yenilemesi yapmama rağmen lookup yenilenmediği için manuel olarak MasterDenemeRow entitysine kaydettiğim kaydı alamıyorum. Çözüm için ne yapmam gerekir. 

Teşekkür ederim.
-------------
Kodlar;

     this.toolbar.options.buttons[8].onClick = () => {//Detay kaydet
                let message = "Kaydetmek ister misiniz?";

                Q.confirm(message, () => {
                  //Id: otomatik artan
                    MasterDenemeService.Create({
                        Entity: {
                            EntityId: Number(this.Deneme.Id),
                            EntityType: "Serenity.Master",       
                            Aciklama: "",
                            Durum: true
                        }
                    });                  
                    $(".DetayKaydet").hide();
                    $(".DetayGöster").show();            
                }, {});
                setTimeout(this, 1000);
                Q.reloadLookupAsync('Serenity.MasterDeneme')           
            }

//------------------------------
            this.toolbar.options.buttons[7].onClick = () => {//DetayGöster
                Q.reloadLookupAsync('Serenity.MasterDeneme');
                var dialogMasterDeneme = new Serenity.MasterDenemeDialog();
// sonuc => MasterDenemeye kaydettiğim veririn Id si tabloda görüyorum fakat gelmiyor.
                try { var sonuc= Q.first(Serenity.MasterDenemeRow.getLookup().items, x => x.EntityType == "Serenity.Master" && x.EntityId == this.Deneme.Id).Id; } catch (e) { }
                dialogMasterDeneme .loadByIdAndOpenDialog(sonuc);
            }

**Comment by volkanceylan** [comment]
Ajax/servisler async çalışır, daha iş bitmeden reload çağırıyorsunuz, onSuccess te yapacaksınız.
