### ISSUE TITLE
Yeni dashboard ekleme hatası

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2111]
merhaba, 
yeni dashboard eklemek için modules/common/dashboard klasorunu kopyalayıp  modules/common/dashboardv olarak oluşturdum, kod tarafındaki tüm hataları dashboard yerine dashboardv yazarak düzelttim , projeyi rebuild edip çalıştırdığımda aşağıdaki hatayı alıyorum, ne yapmalıyım ya da yeni dashboard nasıl eklemeliyim ? yardımcı olabilirmisiniz

***```
*Hata kodu : 

Multiple controller types were found that match the URL. This can happen if attribute routes on multiple controllers match the requested URL.

The request has found the following matching controller types: 
Serene_Brkt2.Common.Pages.DashboardVController
Serene_Brkt2.Common.Pages.DashboardController

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Multiple controller types were found that match the URL. This can happen if attribute routes on multiple controllers match the requested URL.

The request has found the following matching controller types: 
Serene_Brkt2.Common.Pages.DashboardVController
Serene_Brkt2.Common.Pages.DashboardController**
```**

**Comment by VictorTomaili** [comment]
Just google it. That error code is describe everything.  And it's not serenity specific error. It's about mvc.

**Comment by volkanturk** [comment]
Teşekkür ederim cevabınız için bakacağım

**Comment by rolembergfilho** [comment]
just add an information:

In my case, it was happened because I didn't clear the bin folder.

SO, when I build the solution, I had 2 binaries from 2 project (old and new)...


follow these steps:
1 - open the bin folder
2 - select ALL files and folder
3 - DELETE
4 - clear solution
5 - build, transform T4 templates and rebuild
6 - run the project!
