### ISSUE TITLE
Change default english to another language in localizations

### ISSUE THREAD

**Issue by jtuszynski** [volkanceylan/Serenity#2112]
Hi, i have a problem with langugages. I have three languages: **English, German, Russian**
![przechwytywanie1](https://cloud.githubusercontent.com/assets/24196548/24504644/598b14d4-1557-11e7-82f9-6aaee0da84d8.PNG)
 
**I would like to translate field names also into english**. If english is set as default, how do you change it?

![przechwytywanie2](https://cloud.githubusercontent.com/assets/24196548/24504651/5eb8f020-1557-11e7-94ca-092b5df665ba.PNG)

**Comment by jtuszynski** [comment]
I solved my problem.  **LanguageList.ts** 


namespace SzkieletSerenity.LanguageList {
    export function getValue() {
        var result: string[][] = [];
        for (var k of Administration.LanguageRow.getLookup().items) {
         //   if (k.LanguageId !== 'en') {
                result.push([k.Id.toString(), k.LanguageName]);
           // }
        }
        return result;
    }
}

**Comment by Estrusco** [comment]
You can change globalization culture in web.config

https://volkanceylan.gitbooks.io/serenity-guide/content/serene_tour/localization.html

**Comment by adalberto-argente** [comment]
What about the dotnet core?

**Comment by Mohamed-Ali-Salim** [comment]
hi jtuszynski
How can I display the product name in Arabic if the user chooses Arabic and also if he chooses the German language, the product name appears in German
I have already translated the product name into Arabic and German language
Thanks
