### ISSUE TITLE
Unknown file when Create/ Save Entity.

### ISSUE THREAD

**Issue by adhikamafran** [volkanceylan/Serenity#2115]
Hi @volkanceylan  , i had a problem when Create/ Save entity sometimes got unknown file at upload field. 

![result](https://cloud.githubusercontent.com/assets/4415913/24535071/119c3f18-15fc-11e7-909a-b4a624579042.JPG)

my  Row :
     
```
[DisplayName("File Document"),MultipleFileUploadEditor]
public String FileDocument
{
get { return Fields.FileDocument[this]; }
set { Fields.FileDocument[this] = value; }
}
```

Web.Config :

```
<add key="LocalTextPackages" value="{ Site: [ 'Controls.', 'Db.', 'Dialogs.', 'Enums.', 'Forms.', 'Permission.', 'Site.', 'Validation.' ] }" />
    <add key="Logging" value="{  File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0,  Level: 'Debug' }" />
    <add key="ScriptBundling" value="{ Enabled: false, Minimize: true, UseMinJS: true }" />
    <add key="UploadSettings" value="{ Path: '~\\App_Data\\upload\\' }" />
```

Db  :

`[{"Filename":"ECRFTracker/00006/00006601_aktkmf7ibyb7e"},{"Filename":"ECRFTracker/00006/00006601_upi3c3byc6czg"},{"Filename":"ECRFTracker/00006/00006601_c2adp6bk6lv5k"},{"Filename":"ECRFTracker/00006/00006601_c4l6o72gkqahs.pdf","OriginalName":"1774_JATIROTO.pdf"}]`

it's not always happen, please help @volkanceylan . Thank you.

**Comment by volkanceylan** [comment]
I dont know, serenity doesnt create such

**Comment by psigma** [comment]
It happens when user copy/paste some info from Excel (for example) to edit control. And it looks like client send blob to server

**Comment by adhikamafran** [comment]
@psigma i've noticed it before. thanks anyway.

I create validation if the file has no extension. but ur way much simpler. :)
