### ISSUE TITLE
Serenity Rapor ve Grafik Hakkında

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#2117]
İyi günler,
 Serenity   yeni başladım ve rapor ve grafik kullanmayla  yapma ilgili  dokuman bilgi paylaşırsanız.

**Comment by VictorTomaili** [comment]
Here are some samples for reporting and charts

http://serenity.is/demo/Northwind/Reports
http://serenity.is/demo/BasicSamples/ChartInDialog

You can find them under serene sample project. 
https://github.com/volkanceylan/Serene

**Comment by YunusV** [comment]
İyi günler

Burdaki  demodaki   raporlarlar excel,yada pdf  olarak gösterilmektedir. Normal cıktı şekilden olanı varmıdır?

**Comment by VictorTomaili** [comment]
If you need to be customized something, you can also write a page with some printing css. A simple one is standard mvc razor page with a print-only stylesheet.
