### ISSUE TITLE
cascading when using linkingsetrelation

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2118]
Hey
Im trying to understand how i can use cascading when there is a linkingsetrelation. for example:
a Location can have many doctors, and a doctor can have many locations. sitting between Location row and Doctor row i have LocationDoctors as a link.
what im trying to achieve is when adding a listing i have 2 drop downs: location and doctors. when a location is selected only doctors that are listed in that location should be shown.
i followed the example on the site but that doesnt seem to work. what am i missing here?

thanks!  just want to say again how much i appreciate this platform that you created!
Roy

**Comment by Estrusco** [comment]
You must have a code of this type in your row

```cs
public sealed class XYZRow : Row, IIdRow, INameRow
{
    [...]

    [LookupEditor(typeof(LocationLookup)), LookupInclude]
    public Int32? IdLocation
    {
        get { return Fields.IdLocation[this]; }
        set { Fields.IdLocation[this] = value; }
    }

    [LookupEditor(typeof(DoctorsLookup), CascadeFrom = "IdLocation")]
    public Int32? IdDoctor
    {
        get { return Fields.IdDoctor[this]; }
        set { Fields.IdDoctor[this] = value; }
    }
 
    [...]
}
```

**Comment by shakazulu89** [comment]
I actually had to use the LocationDoctorRow instead of Doctor row as editor and then it worked (after a few other tweaks).
Thanks

**Comment by shakazulu89** [comment]
im sorry i thought i had it but there is still an issue:
Basically in the "listing" form the cascading drop boxes work. When i select the location the proper doctors show up. but since i am using the "LocationDoctorsRow" as the editor for the "Doctors" dropbox, when inserting the listing it takes the Identity of locationdoctorsrow, which is locationdoctorid. I need it to take another field from that row, DoctorId. How can i achieve this? is the only way to make a custom editor or lookup?
I can change the IIdRow.IdField of locationdoctorsrow and then it works but this doesnt seem like the proper solution... ?
