### ISSUE TITLE
DateTimeOffset and DisplayFormat

### ISSUE THREAD

**Issue by sfackrell** [volkanceylan/Serenity#2120]
Is it possible to add support for `DateTimeOffset`?  If I change the type from `DateTimeOffset` to `DateTime`, the `DisplayFormat` attribute works correctly but if I use `DateTimeOffset`, the `DisplayFormat` has no affect (`2014-07-16T09:56:51.8810457+10:00`). 

At the moment, the only way I can see to format these dates correctly is to add another property derived from the DateTimeOffset property.

**Comment by edson** [comment]
Are you using DateTimeOffsetField  instead of DateTimeField in xyzRow.cs?

**Comment by volkanceylan** [comment]
Add DateTimeFormatter attribute to property. If it still doesnt work you can write a formatter

**Comment by sfackrell** [comment]
Thank you.  I will try this tonight and update this thread

**Comment by sfackrell** [comment]
DateTimeFormatter has no effect but if I write a custom formatter like this

```cs
public class DateTimeOffsetFormatterAttribute : CustomFormatterAttribute
{
	public DateTimeOffsetFormatterAttribute() : base("DateTime") { }

	public string DisplayFormat
	{
		get { return GetOption<String>("displayFormat"); }
		set { SetOption("displayFormat", value); }
	}
}

[DateTimeOffsetFormatter(DisplayFormat = "dd/MM/yyyy HH:mm:ss")]
public DateTimeOffset? CreatedWhen
{
	get { return Fields.CreatedWhen[this]; }
	set { Fields.CreatedWhen[this] = value; }
}
```

I get the dates formatted in the grid correctly :+1: .

Unfortunately this doesn't work in the xxForm.  Is there any way to use a custom formatter with a StringEditor (read only) or a StaticTextBlock in a form?  Or am I trying to do the form implementation the wrong way?

**Comment by volkanceylan** [comment]
Editors doesnt use display format. Only culture settings for dmy ordering.

**Comment by sfackrell** [comment]
I don't really want to use or need an "editor" as the field in question is always read only and never editable, but it does need to appear on the form for reference purposes.  

The StaticTextBlock would work if it could use model data rather than only constants. Is it possible to add my own custom StaticTextBlock or read only textbox, deriving from a base editor class?

**Comment by volkanceylan** [comment]
You can write some simple editor, e.g. readonly always that uses spans etc.

**Comment by sfackrell** [comment]
Thanks Volkan.  I'll try this and if it's worth sharing, I'll post some details
