### ISSUE TITLE
Attributes to support a read-only derived property

### ISSUE THREAD

**Issue by sfackrell** [volkanceylan/Serenity#2121]
How can you add a read-only property to a form or a grid/list that is not a database field?  I have tried all sorts of combinations of attributes across the `xxRow` and `xxForm` classes (after adding the property to `xxColumns`) but the field is always an empty string in the form and in the grid.

Have tried:

```cs
[NotMapped]
[Expression]
[SetFieldFlags(FieldFlags.Reflective)]
[SetFieldFlags(FieldFlags.Foreign)]
[SetFieldFlags(FieldFlags.Calculated)]
```

and combinations of the above.  All of these were just trying to output a hardcoded string to test (to begin with).  The intention is to transform another property's value.

Details on what was attempted:
Added string property to `xxRow` with attributes above (hardcoded string on property getter)
Added string property to `xxForm` with attributes above (hardcoded string on property getter)
Tried with and without extra properties on `xxColumns`

If you add the properties to the RowFields class, it falls over with a SQL exception as it's looking for the property in the SQL SELECT (have tried this with [NotMapped] but has no affect)

I'm trying to resolve an issue with not being able to format DateTimeOffset columns.

Thanks in advance for any assistance

**Comment by Estrusco** [comment]
Have you looked at https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Editors/StaticTextBlock example?

**Comment by sfackrell** [comment]
Hi @Estrusco, thank you for your reply.  I hadn't seen that example and it is similar to what I need but as you have to set Text in the attribute then you can only use a constant.  What I need to do is transform another property's value at runtime.  

It is linked to my other issue with DateTimeOffset.  I have no way to format this date correctly so was hoping to to something like this:

```cs
public DateTimeOffset UpdatedWhen { get; set; }

[ReadOnly(true)]
[DisplayName("Updated When")]
public string UpdatedWhenFormatted => UpdatedWhen.ToString("dd/MM/yyyy HH:mm:ss");
```

**Comment by Estrusco** [comment]
@sfackrell the example show that is also possible to display the property value. See the code in 

```ts
 /**

         * By implementing ISetEditValue interface, we allow this editor to display its field value.

         * But only do this when our text content is not explicitly set in options

         */

        public setEditValue(source: any, property: Serenity.PropertyItem) {

            if (this.options.text == null) {

                this.value = Q.coalesce(this.options.text, source[property.name]);

                this.updateElementContent();

            }

        }
```

**Comment by john20xdoe** [comment]
@sfackrell 

as @Estrusco said, it will use the value at runtime, by default

just add `[StaticTextBlock]` on top of the property in you Form. by itself, it will use the property value.

if you do not wish to use the value (for example, want to use your own instructions) you will add the string to the  `Text` parameter, like:

[StaticTextBlock(Text="Please do not use numbers"), NotMapped, OneWay]
public String Tips {get;set;}

*Optional:*
In this case I add NotMapped because `Tips` is not in the database.
And OneWay because I do not want it to be included as data in the form when it is POSTed back (like when clicking `Save` button.)

**Comment by sfackrell** [comment]
Thank you both for your answers.

@john20xdoe this doesn't help as I need to transform another property's value at runtime, just putting the attribute on it is no different to leaving the default text editor, the DateTimeOffset value is always incorrectly formatted and I have no control over the format as the DisplayFormat attributes have no effect.

@Estrusco I am not sure what you meant but after digging into templates using ```IGetEditValue``` and ```ISetEditValue``` I have a solution which works for me.  It might be overkill but I can't see a simpler way to do it

```cs
//[DisplayName("Created When"), NotNull, ReadOnlyDate]
[DisplayName("Created When"), NotNull, StaticTextBlock]
public DateTimeOffset? CreatedWhen
{
    get { return Fields.CreatedWhen[this]; }
    set { Fields.CreatedWhen[this] = value; }
}

[DisplayName("Updated When"), NotNull, ReadOnlyDate]
public DateTimeOffset? UpdatedWhen
{
    get { return Fields.UpdatedWhen[this]; }
    set { Fields.UpdatedWhen[this] = value; }
}
```

```ts

@Serenity.Decorators.registerEditor([Serenity.IGetEditValue, Serenity.ISetEditValue])
@Serenity.Decorators.element("<div/>")
export class ReadOnlyDate extends Serenity.TemplatedWidget<any>
  implements Serenity.IGetEditValue, Serenity.ISetEditValue {
  
  constructor(div: JQuery) {
    super(div);
  }

  private formattedDateValueAsString: String;
  private dateValueAsString: String;

  protected getTemplate() {
    return "<div id='~_Date' class='s-StaticTextBlock'>-- No data --</div>";
  }

  protected updateContent() {
    var dateDiv = this.byId('Date');
    dateDiv.text(Q.coalesce(this.formattedDateValueAsString , ''));
  }

  public get value() : String {
    return this.dateValueAsString;
  }

  public set value(value: String) {
    this.dateValueAsString = value;

    try {
      var dt = new Date(value);
      this.formattedDateValueAsString = dt.toLocaleDateString().concat(' ', dt.toLocaleTimeString()); 
    } catch (e) {
      this.formattedDateValueAsString = '';
    }
    
    this.updateContent();
  }

  public getEditValue(prop: Serenity.PropertyItem, target) {
    target[prop.name] = this.value;
  }

  public setEditValue(source, prop: Serenity.PropertyItem) {
    this.value = source[prop.name];
  }

  public onChange: () => void;
}
```
<img width="497" alt="datetimeoffset" src="https://cloud.githubusercontent.com/assets/1954474/25038421/abf810dc-20f6-11e7-8679-e11fcddb7ce5.png">

**Comment by xareas** [comment]
Insertable(false), Updatable(false) could also work.

**Comment by sfackrell** [comment]
> Insertable(false), Updatable(false) could also work.

This just hides the field completely on insert and makes the text box read-only on edit.  The content remains the same and you have no way to change its format

**Comment by volkanceylan** [comment]
The one you wrote is too complex for such simple display box. You only need setEditValue method and formatting value there before setting its text.
