### ISSUE TITLE
how to use sql stored procedure and login based data displaying

### ISSUE THREAD

**Issue by kuradaganesh** [volkanceylan/Serenity#2122]
1.How pass pass values from application to sql stored procedure and display that data into grid system.
2.Display login based data to jquery grid system.
  for example,where userid='123'

**Comment by edson** [comment]
Check Basic Samples
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/StoredProcedureGrid

And do the movie tutorial
https://volkanceylan.gitbooks.io/serenity-guide/content/

Best Regards

**Comment by kuradaganesh** [comment]
first one is working fine and second question i am not getting
if user login from this template then after displays user based data.
for example admin login number of orders displays 20 records only
for abc login  number of orders displays 50 records
for another user login number of orders displays 80 records.......etc like that any solution is there??

**Comment by VictorTomaili** [comment]
I don't recommend user id based backend code. But you can create some roles for this. like admin sees 80, editor sees 50, others sees 20. 
roles are never changed in back-end. If it changed, it will be refactored.  But user ids will be changed at runtime. 

Put your logic inside service call repository with checking role.

**Comment by kuradaganesh** [comment]
yes role based login is correct but how to send role id from this serenity login page.

**Comment by kuradaganesh** [comment]
for example role id='80' then after Showing 100 total records in northwind--->custmer page,
if role id='100' then after Showing 200 total records in northwind--->custmer page any solution is there??

**Comment by sayuga** [comment]
You should be able to factor that in the same way the multi tenancy samples manage with the tenant Id. The only difference is you'll be using the roleId 

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/securing_tenant_selection_at_server_side.html

**Comment by kuradaganesh** [comment]
if using the multi tenancy samples the dash board like data open order,closed orders,total customers,different products counts is changed or not??

**Comment by kuradaganesh** [comment]
if using the multi tenancy samples in dash board page data like open order,closed orders,total customers,different products counts is changed or not??
Thank you so much for the speedy reply volkanceylan/Serenity Team.

**Comment by edson** [comment]
You have to put your logic in dashboard controller. It's only a matter of selecting rows by role. as multi_tenancy.
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Dashboard/DashboardPage.cs

https://github.com/volkanceylan/Serenity/issues/1540

Best Regards

**Comment by kuradaganesh** [comment]
Thank you so much for the speedy reply
