### ISSUE TITLE
Adding SlickGrid plugin

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2123]
Hey
Im trying to integrate the auto width plugin posted by John Ranger: 
https://github.com/volkanceylan/Serenity/wiki/Slickgrid-AutoColumn-resize
but i get "Object doesn't support this action" on this line:
let autoSize = new Slick.AutoColumnSize(true);

Intelisense picks up AutoColumnSize but when i debug and look at Slick object AutoColumnSize is not there. Seems as if its not picking it up. I did generate t4. 
i have a feeling like the new .d.ts file is not getting compiled or something.
Any ideas why this is happening?
thanks for any help to come :)

**Comment by shakazulu89** [comment]
I had a feeling it was something like that but had no idea where to look. Still getting used to this whole shabang.
it worked.. thanks!!!

**Comment by kilroyFR** [comment]
Still having an issue on this. 
After overriding :
        protected createSlickGrid(): Slick.Grid {
            var grid = super.createSlickGrid();

            // Full Row Selection
            grid.setSelectionModel(new Slick.RowSelectionModel());

            // Columns auto resize
            let autoSize = new Slick.AutoColumnSize(true); 
            grid.registerPlugin(autoSize);

            return grid;
        }

Pb rises when you have a column picker button. If you click on OK (even without changing anything), grid is displayed again but with NO REFRESH (so all columns remains not auto resized).
is there a way to refresh grid after this Event ? (quitting column picket dialog box)
