### ISSUE TITLE
memory grid editor not created in xyzform.ts 

### ISSUE THREAD

**Issue by jas2008** [volkanceylan/Serenity#2124]
Hi volkan,

I have a few memory grid editors in form, but recent versions seems to ignore and did not create these grid fields in  xyzform.ts.

Currently using latest version, 2.9.21

old salaryform.ts generated as below: 

export interface SalaryForm {
        Basic: Serenity.DecimalEditor;
        OvertimeList: OTTranEditor;                                 <--- not generated in new version
        AllowanceList: AdTranEditor;                                <--- not generated in new version
        SalarySummaryList: SalarySummaryEditor;           <--- not generated in new version
    }

The editors are placed in separate folders below the salaryform, not sure if this is path probing issue? 

FYI, my solution has a few serenity projects (plugins), where I have placed them in the plugin folder of the main Web project.  

Thank you.

**Comment by volkanceylan** [comment]
T4 only generates types in web project, not others.
