### ISSUE TITLE
avaible material for selecting would only be relevant with the selected material category

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2126]
There is a form with Material categories and material. I want to add a function that, if a material category chose, then the avaible material for selecting would only be relevant with the selected material category.
How to realize it? i didn't see any example related with it.

Thanks in advance.

![default](https://cloud.githubusercontent.com/assets/16734387/24706019/ce6b0762-1a40-11e7-8bbf-7be55bdeb65b.png)

**Comment by edson** [comment]
See CascadeFrom issues/tutorial examples...

Best Regards

**Comment by PanChenhao** [comment]
Thank you very much. i have do it successfully according to the tutorial.
But actually i have another file MaterialLookup.cs to define the LookupScript, please see as below.
The problem is i don't know how to add the 'MaterialCategoryId' field in to lookup fields. 
If in MaterialRow, we can use LookupInclude attribute, but how to define it by manual in MaterialLookup.cs
```
namespace yp.Material.Scripts
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;
    [LookupScript("Material.Materials")]
    public class MaterialLookup : RowLookupScript<Entities.MaterialsRow>
    {
        public MaterialLookup()
        {
            IdField = "MaterialId";
            TextField = "MaterialName";                     
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Entities.MaterialsRow.Fields;
            query.Distinct(true)
                .Select(fld.MaterialId, fld.MaterialName)
                .Where(
                    new Criteria(fld.IsDelete) == 0);
        }
        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}
```

**Comment by edson** [comment]
query.Distinct(true)
                .Select(fld.MaterialId)
                .Select(fld.MaterialName)
                .Select(fld.MaterialCategoryId)
                .Where(
                    new Criteria(fld.IsDelete) == 0);

**Comment by PanChenhao** [comment]
It works, thank you very much.
