### ISSUE TITLE
OrderItems grid

### ISSUE THREAD

**Issue by marcipunk** [volkanceylan/Serenity#2127]
Hi!

The starting point of my idea is the Orders grid on the sample site: http://serenedemo.azurewebsites.net/Northwind/Order

It is possible to create a grid to display data in rows from the orders ("head") and the items both?
I also need to open the Order from a row.

For example columns of the row:
OrderId | OrderDate | Customer | ProductId | ProductCode | ProductName | Quantity | NettUnitPrice | VAT

My problem also that a Product has more name, one per language :
ProductId | LanguageId | ProductName
1               | EN               | Car
1               | DE               | Auto

How can I select the ProductName by the actual UI language?

Maybe is there a sample in the [guide](https://www.gitbook.com/book/volkanceylan/serenity-guide/details) that I missed?

Thank You in advance!

**Comment by marcipunk** [comment]
Smbody, please! How can I select the ProductName by the actual UI language?

**Comment by volkanceylan** [comment]
Add ProductName (English)  ProductName (German) etc. properties, set some expression for them using left join.

**Comment by marcipunk** [comment]
Sorry, could You write there an example?

**Comment by marcipunk** [comment]
Should I have to add somewhere an `AND LanguageId = 'en'`?
But where?

**Comment by volkanceylan** [comment]
Your Row.cs, ProductEN property, Expression attribute.
