### ISSUE TITLE
Controlling automatic session time out

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#2129]
Hello Volkan,

My users are complaining that the application is automatically logging them out (laziness, I know). Is setting the application pool idle time out the correct way to prevent automatic logout?

![image](https://cloud.githubusercontent.com/assets/17013052/24720986/7b83aa5e-1a04-11e7-9c32-f5ce29008002.png)

Many thanks in advance.

**Comment by volkanceylan** [comment]
Nope, increase timeout value in web.config

**Comment by c9482** [comment]
Like this? Thanks.

<configuration>
  <system.web>
     <sessionState timeout="20"></sessionState>
  </system.web>
</configuration>

**Comment by c9482** [comment]
Is this what I need to change? If I set timeout to 300, does it mean it will stay up for 5 hrs?
`
<forms loginUrl="~/Account/Login" timeout="300" path="/" slidingExpiration="true" />`

**Comment by volkanceylan** [comment]
Yes, that is it
