### ISSUE TITLE
Not an issue - Master Detail Picker/? for second Master Detail relationship help

### ISSUE THREAD

**Issue by MunsterUSMC** [volkanceylan/Serenity#2130]
Good afternoon,

I would like to see if someone could help me how use a checkbox selection on the Order Details grid to import into my Invoice dialog when creating a new invoice. 

I have tried the everything I've read on here so far but have yet to even get close to making it work.
I tried the following examples so far. If there is something else that would be a better option please let me know. 
#834,  #1254 and #1582 

To make this easier to understand I created a screenshot. The reason I need to allow the user to pick the item to import into the Invoice Detail is based on when the product shipped. We can have 1 to 10 invoices off the same OrderId.

Thank you for any help!

Sincerely,

Bob

![screen shot 2017-04-05 at 1 39 29 pm](https://cloud.githubusercontent.com/assets/26091852/24721955/c4519330-19f6-11e7-8b9a-3ef33a874f2f.png)

**Comment by edson** [comment]
Proceed the same way it is done there:
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/CancellableBulkAction/CancellableBulkActionGrid.ts


in your xyzEditor.ts

Look for Serenity.GridRowSelectionMixin and getColumns
the selected rows keys you will get in this.rowSelection.getSelectedKeys()


then you'll have something like this:
![image](https://cloud.githubusercontent.com/assets/62490/24774940/415fa344-1af1-11e7-9903-eeb3d1f01f65.png)

But with checkboxes.

Best Regards

**Comment by MunsterUSMC** [comment]
Hi Edison,

Thank you for your replay. 

I tired that as well. I could get the checkbox as shown in the picture. What happen ‘onclick’ it would create a new blank row with the InvoiceID an Invoice Detail ID. None of the original field would pass though the click event. I copied the example then looked at the BulkOrderAction.ts in Northwind/Orders to see if I was missing something there as well but without any luck. 

I used the example code you had on #1254. I did notice that the onclick event would not fire. I’ll go back again to see If I can get it to work or see why it’s not firing.

I also email Volkanceyan to see If I could get this create as a pay service. I have to move on to other projects soon. 

Sincerely,

Bob

**Comment by edson** [comment]
I see. It's been a while since this went to production... So I May Have Forgotten some steps. But If volkan is going to help you, I won't interfere. That would be a greater help Than Mine.:)

Best regards

**Comment by MunsterUSMC** [comment]
Hi Edson,

I greatly appreciated the response.

He did email be back this morning. I'm going to have him create it for me.
Easier to have the person who knows the code complete it than me trying
over and over.

If it would help I'll glady share his finished work.

Bob





On Apr 6, 2017, at 5:19 PM, Edson Chen <notifications@github.com> wrote:

I see. It's been a while since this went to production... So I May Have
Forgotten some steps. But If volkan is going to help you, I won't
interfere. That would be a greater help Than Mine.:)

Best regards

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/volkanceylan/Serenity/issues/2130#issuecomment-292340844>,
or mute the thread

**Comment by edson** [comment]
I have it working fine. But off course it would be better to have a code from a master Pro to learn things. but share only if you wish or think you should or simplify the code... because sometimes we can't share the exact code by companies policies reasons when in production.

Gook Luck
Best Regards

**Comment by MunsterUSMC** [comment]
No worries Edson. I'll post so other trying to get it to work in the future will have the code written as you say the Master.
