### ISSUE TITLE
Serin downloading lastest serene template fail

### ISSUE THREAD

**Issue by xuj668** [volkanceylan/Serenity#2131]
I want to test serenity by vscode on linux (debian)
I fellow your blog "Serene Install" (http://serenity.is/blog/2017/03/30/serene-install), but serin can't create the project, the error message:
(node:24269) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/home/recozo/.serene/SereneCore.Template.124.zip'

**Comment by volkanceylan** [comment]
Update serin, e.g. "npm update -g serin"

Then it should work.
