### ISSUE TITLE
More complicated Excel export

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#2132]
Hello Dear Community,

Have the following dialog with General tab and other tabs where just grids located (milestones, positions, travels, expenses).

![excel_export](https://cloud.githubusercontent.com/assets/18590952/24744147/a0a2e8ee-1ab9-11e7-9a33-67d17433be31.jpg)

Is the some way to export each grid in separate Excel's sheet and all of the above from General tab too?
Could you please advise?
Thank you.

**Comment by volkanceylan** [comment]
Have a look at Epplus
