### ISSUE TITLE
New to Serene Editor Not Working

### ISSUE THREAD

**Issue by RReyes277** [volkanceylan/Serenity#2134]
Hello I am trying my new project in Serene.

Created the following editor:

/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace BBB.Default {
    @Serenity.Decorators.registerEditor()
    export class AuditDTLSEditor
        extends Common.GridEditorBase<AuditDtlsRow> {
        protected getColumnsKey() { return "Default.AuditDTLS"; }
        protected getLocalTextPrefix() { return AuditDtlsRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }
    }
}

Using it on the following Form:

namespace BBB.Default.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;

    [FormScript("Default.AuditHdr")]
    [BasedOnRow(typeof(Entities.AuditHdrRow))]
    public class AuditHdrForm
    {
        public String DocName { get; set; }
        public String DocNumber { get; set; }
        public String Auditor { get; set; }
        public String AuditNumber { get; set; }
        public DateTime AuditDate { get; set; }

        [AuditDTLSEditor]
        public List<Entities.AuditDtlsRow> AUditDTL { get; set; }
       

    }
}

Getting the following error when trying to open the form:

Bundle.Libs.js:223 Uncaught Error: Script data Columns.Default.AuditDTLS is not found in registered script list!
    at u (Bundle.Libs.js:223)
    at Object.c [as ensure] (Bundle.Libs.js:223)
    at Object.l [as getColumns] (Bundle.Libs.js:223)
    at i.getPropertyItems (Bundle.Libs.js:232)
    at i.getColumns (Bundle.Libs.js:232)
    at i.createSlickGrid (Bundle.Libs.js:232)
    at i.y [as constructor] (Bundle.Libs.js:229)
    at i.R [as constructor] (Bundle.Libs.js:229)
    at i.t [as constructor] (Bundle.Site.js?v=Cpqzz-Yur2uv6jvUWxjQSA2:48)
    at new i (Bundle.Site.js?v=Cpqzz-Yur2uv6jvUWxjQSA2:48)

![image](https://cloud.githubusercontent.com/assets/27016786/24806482/093e4dde-1b83-11e7-9371-1f0331c2e1d9.png)

**Comment by sayuga** [comment]
Looks to me like it's saying it can't find the columns.cs did you doublecheck the file to ensure the script call doesn't have a typo?

**Comment by RReyes277** [comment]
Hello Sayuga,

thanks for replying which file are you referring too?

**Comment by RReyes277** [comment]
Sayuga, this was the issued I looked it over many times looked ok, so I did a copy pasted. and it work do you know if is is case sensitive?

**Comment by sayuga** [comment]
I do believe it is.
