### ISSUE TITLE
Frozen Column

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2135]
Hi! Please help me! How to freeze left column when scrolling horizontally? Thank you!

**Comment by sayuga** [comment]
I don't think that is currently implemented but you may be able to emulate JLynch7's frozen columns. https://github.com/JLynch7/SlickGrid/tree/2.0-frozenRowsAndColumns/examples

**Comment by Zahar661** [comment]
SlickGrid Consists of two panes horizontally, left and right. to pin columns, you have to leave them in the left pane, and the rest to throw to the right. Serenity by default writes all columns in the left panel, and how to bring in the right it is not clear(((

http://jlynch7.github.io/SlickGrid/examples/example-frozen-columns.html

**Comment by Zahar661** [comment]
Everything was just as always!
` protected getSlickOptions() {
            var opt = super.getSlickOptions();
            opt.frozenColumn = 0
            return opt;
        }`

**Comment by john20xdoe** [comment]
^ Note that the number starts from 9

i.e. if you want to freeze first column in your xxxColumns.cs file (used by Grid), use 0, for first two columns, use 1...etc.

**Comment by Zahar661** [comment]
Thanks, I understood it. I now have another problem. Find a way to change the order of the columns using the button.

**Comment by volkanceylan** [comment]
Yes, i've merged frozen columns implementation, but out of the box, only frozenColumn option works.
