### ISSUE TITLE
Trying multi column dialog sample 

### ISSUE THREAD

**Issue by RReyes277** [volkanceylan/Serenity#2136]
So I am trying multi column dialog but do not seem to get the CSS to take effect here are the codes as per the basic samples

THIS IS THE CLASS With Multi Column
/// <reference path="../../../Modules/Default/AuditHdr/AuditHdrDialog.ts" />
namespace  BBB.Default{
    @Serenity.Decorators.registerClass()
    export class mAuditHdrDialog extends BBB.Default.AuditHdrDialog{

        constructor() {
            super();
        }
    }
}

THIS IS THE CLASS With Grid Class Multi Column
/// <reference path="../../../Modules/Default/AuditHdr/AuditHdrGrid.ts" />
namespace BBB.Default {
    @Serenity.Decorators.registerClass()
    export class MAuditHdrGrid extends BBB.Default.AuditHdrGrid{

        protected getDialogType() { return mAuditHdrDialog; }

        constructor(container: JQuery) {
            super(container);
        }
    }
}

THIS IS THE Entry in the Site.Less File 
.s-Default-mAuditHdrDialog {
    > .size { width: 850px; height: 650px; }
    .caption { width: 130px; }
    
    @media (min-width: 768px) {
        .field.DocName, .field.DocNumber, .field.Auditor, .field.AuditNumber, 
        .field.AuditDate {
            flex: auto;
            min-width: 50%;
            background-color: lightgreen;
        }
        
        .field.DocName, .field.DocNumber, .field.Auditor { 
            flex: auto;
            min-width: 33%;
            .caption { width: 90px; } 
        }
    }
}

This is the Original Grid Tried modifying here didn't work 

namespace BBBB.Default {
        @Serenity.Decorators.registerClass()
    export class AuditHdrGrid extends Serenity.EntityGrid<AuditHdrRow, any> {
        protected getColumnsKey() { return 'Default.AuditHdr'; }
        protected getDialogType() { return mAuditHdrDialog; }
        protected getIdProperty() { return AuditHdrRow.idProperty; }
        protected getLocalTextPrefix() { return AuditHdrRow.localTextPrefix; }
        protected getService() { return AuditHdrService.baseUrl; }

        constructor(container: JQuery) {
            super(container);
        }
    }
}

Below is the picture show the dialog
![image](https://cloud.githubusercontent.com/assets/27016786/24820521/7c3ee68e-1bb7-11e7-8f8c-56421508520e.png)

**Comment by korlu** [comment]
Try this: 

.s-Default-mAuditHdrDialog {
     > .size { width: 850px; height: 650px; }
     .caption { width: 130px; }

     .category > .field.DocName, .category > .field.DocNumber, .category > .field.Auditor, .category > .field.AuditNumber, .category > .field.AuditDate {
        -ms-flex: 1 0 200px; 
        -webkit-flex: 1 0 200px; 
        flex: 1 0 200px; /*adjust the 200px to meet you need or change to %*/
     }
}

**Comment by RReyes277** [comment]
Hello Korlu, 

I tried it and got the same results.

**Comment by RReyes277** [comment]
![image](https://cloud.githubusercontent.com/assets/27016786/24830775/6113a3f6-1c5a-11e7-89d0-6b9bd9184c76.png)

**Comment by RReyes277** [comment]
Korlu, 

How do I know that the Correct CSS section is being called. ? Or that the write version of the Dialog screen is being instantiated? any quick thoughts or ideas?

**Comment by korlu** [comment]
If you are using FireFox or chrome, use the element inspector. 
OR try s-mAuditHdrDialog instead of .s-Default-mAuditHdrDialog

**Comment by korlu** [comment]
and one more thing... case sensitivity
change 

.category > .field.DocName, .category > .field.DocNumber, .category > .field.Auditor, .category > .field.AuditNumber, .category > .field.AuditDate {

to

.category > .field.docName, .category > .field.docNumber, .category > .field.auditor, .category > .field.auditNumber, .category > .field.auditDate {

**Comment by RReyes277** [comment]
Korlu,

Tried it.. Same results. I feel that the block of CSS is not being called.. Is there any way to verify if its executing I put a breakpoints but is not stopping there

**Comment by korlu** [comment]
Using Chrome browser see this screenshot. Hope this helps.

![element inspector](https://cloud.githubusercontent.com/assets/14118008/24831099/5462eebc-1c61-11e7-9ca7-75c1a7e94197.png)

**Comment by RReyes277** [comment]
Korlu,

This is a great help. So by doing that i found that the problem is that the code is not executing the

.s-Default-mAuditHdrDialog {
    > .size {
        width: 450px;
        height: 450px;
    }

    .caption {
        width: 130px;
    }

    .category > .field.docNumber, .category > .field.docNumber, .category > .field.auditor, .category > .field.auditNumber, .category > .field.auditDate {
        -ms-flex: 1 0 100px;
        -webkit-flex: 1 0 100px;
        flex: 1 0 100px; /*adjust the 200px to meet you need or change to %*/
    }
}
I copied the into the original ".s-Default-AuditHdrDialog {" and it worked.  How does the proper CSS section get called ? is that by name? or is there a reference?

**Comment by korlu** [comment]
The Serenity framework seems to follow a convention... ".s-MODULEFOLDER-xxxDialog".  Glad I could help.
