### ISSUE TITLE
Remove quick search box from Grid

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2137]
Is this possible without code hacking?  I have one grid page where I don't want the quick search box visible.

Thanks

**Comment by korlu** [comment]
mcb2323,  in the xxxGrid.ts add this code: 

protected createQuickSearchInput() { }

In this case you are simply overriding the createQuickSearchInput().

**Comment by john20xdoe** [comment]
^ @mcb2323 @korlu's solution means you are overriding createQuickSearchInput() to do nothing. (hence no search box created)
