### ISSUE TITLE
Error when opening a record from grid

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2138]
Incorrect syntax near the keyword 'AS'.

**Comment by marcipunk** [comment]
Hi, it's an error from the SQL Server. Serenity build SQL query from your xxRow.cs.
Something around a LeftJoin or expression, etc is incorrect.

Use https://expressprofiler.codeplex.com/ to get information about exactly what is the query that build and sent by Serenity to your db, and You will see what's wrong.

**Comment by edson** [comment]
Or enable logging in Web.Config for Debug level and check log files for the queries...

Best Regards.
