### ISSUE TITLE
how to customize the format of PDF reporter

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2139]
Hello all, I have a requierment to download a deliveried order list as PDF. i look into demo, found in Northwind module, the orders page has the similar function, export order details as PDF. but how to change the format, could i add a new reportKey?

```
buttons.push(Serene7.Common.ReportHelper.createToolButton({
                title: 'Invoice',
                cssClass: 'export-pdf-button',
                reportKey: 'Northwind.OrderDetail',
                getParams: () => ({
                    OrderID: this.get_entityId()
                })
            }));
```

**Comment by adhikamafran** [comment]
Yes, you could add new report key. 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Order/OrderDetailReport.cs

And for report formatting, see this example
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Order/OrderDetailReport.cshtml

**Comment by PanChenhao** [comment]
Thanks you very much@adhikamafran,  I will try it.

**Comment by PanChenhao** [comment]
@adhikamafran ,I tryed it, and it works. thanks again.

**Comment by AhmedRHegab** [comment]
the the common folder is missing the reporting folder, I can not access it!
