### ISSUE TITLE
Multi column form layout

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#214]
Hi,
I love serenity so much. In serenity almost every thing is good. Current form layout is suitable for some cases but containing many fields it is not suitable.

In my opinion if there is an option where we can specify the layout of the forms it will be best for all cases.

I want to organize fields in the forms like existing search panel in grid page.
![form](https://cloud.githubusercontent.com/assets/16621563/12881289/d5abc734-ce72-11e5-8e0c-35ab19930ab4.png)

Regards,
Faruque

**Comment by jsbUSMC** [comment]
You can do that using less, you have to customize it yourself. If you want the fields to be different from the default, you can edit `xyzForm.cs` and rearrange the order of the fields, or remove them. As long as they are declared in `xyzRow.cs` you will be able to utilize them in your form class.

**Comment by dfaruque** [comment]
Thank you.
I know that using less I can do.

 Since serenity platform is declarative and I want to show the form as given layout. So it will be great to have a attribute like FormLayoutAttribute.

**Comment by volkanceylan** [comment]
I have such plans, but trying to find a way to do it in a responsive and backward compatible way. Bootstrap grid or flexbox layout are some options. Waiting for BS4.

**Comment by dfaruque** [comment]
Great

**Comment by mzamonkosi** [comment]
Hi Guys 

Im new to serenity, is there a guide i can use or video i can watch if i want to further customize it

Regards
Mz
