### ISSUE TITLE
IIS NET CORE 

### ISSUE THREAD

**Issue by FARIVER** [volkanceylan/Serenity#2141]
Uncaught Error: Script data Template.UserDialog is not found in registered script list!
Uncaught Error: Script data Template.RoleDialog is not found in registered script list!
...
The app is working fine when debugging in VS2017, the error occurs only when publishing.
Put this at the top of ScriptInitialization.ts file:
///`<reference path="../Common/Helpers/LanguageList.ts" /> `
Can not open！

**Comment by FARIVER** [comment]
///<reference path="../Common/Helpers/LanguageList.ts" />

**Comment by FARIVER** [comment]
![Uploading 01.PNG…]()

**Comment by FARIVER** [comment]
![02](https://cloud.githubusercontent.com/assets/8403680/24911659/56e10f8a-1efe-11e7-9f4c-0c48a569237e.PNG)

**Comment by FARIVER** [comment]
![01](https://cloud.githubusercontent.com/assets/8403680/24911678/657b9876-1efe-11e7-8ce6-f93fb4ab2ed0.PNG)

**Comment by volkanceylan** [comment]
You have some missing file. Thats not about reference path.

**Comment by FARIVER** [comment]
Can you give me some tips!

**Comment by FARIVER** [comment]
1>  任务“Exec”
1>    任务参数:Command=dotnet sergen servertypings
1>    dotnet sergen servertypings
1>    Transforming ServerTypings at: C:\Users\TEXT\Desktop\TM_C\iRECO 03\iRECO\iRECO.Web\Imports\ServerTypings
1>
1>    Unhandled Exception: System.IO.DirectoryNotFoundException: 系统找不到指定的路径。 (Exception from HRESULT: 0x80070003)
1>       at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>       at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>       at Serenity.CodeGenerator.ServerTypingsCommand.Run(String csproj, List`1 tsTypes)
1>       at Serenity.CodeGenerator.Program.Main(String[] args)
1>    C:\Users\TEXT\Desktop\TM_C\iRECO 03\iRECO\iRECO.Web\iRECO.Web.csproj(59,5): warning MSB3073: 命令“dotnet sergen servertypings”已退出，代码为 -532462766。

**Comment by renattomachado** [comment]
+1

I've same problem!

**Comment by renattomachado** [comment]
@volkanceylan can you help me?

**Comment by renattomachado** [comment]
@FARIVER did you resolve that problem?

**Comment by volkanceylan** [comment]
There is no UserDialog template, so it means you don't have EntityDialog.Template.html or it is in different case. Use a file compare tool.

**Comment by renattomachado** [comment]
Realy I didn't have the folder Templates on folder View. But I put on there and the problem not solve.

**Comment by volkanceylan** [comment]
volkanceylan commented 12 days ago
You have some missing file. Thats not about reference path.

**Comment by renattomachado** [comment]
But only publishing with VS 2017 to Azure Web App Service, didn't should works?

**Comment by renattomachado** [comment]
I copying same folders to Azure folder and now it's works.
I'll verify wich solve this problem and I'll report here for documentation.

**Comment by Febriantos** [comment]
@renattomachado: I can replicate this issue, may I know which folders did you copy?

**Comment by Febriantos** [comment]
I resolved it by copying node_modules folder
