### ISSUE TITLE
OriginalNameProperty Purpose?

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#2143]
What exactly does OriginalNameProperty do? I set it to another StringField and I still don't get the file name of the file I am trying to upload. I need to save the original file name for audit reasons.

**Comment by Estrusco** [comment]
see here https://github.com/volkanceylan/Serenity/issues/1005

**Comment by dougdsank** [comment]
Thanks but that didn't work. I have a strigfield in my row named uploadname I set OriginalNameProperty='uploadname' in the attribute where the FileUploader is. Do you have an example? Thanks

**Comment by volkanceylan** [comment]
That's case sensitive.
