### ISSUE TITLE
Application Question

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2145]
Hi,  Im not sure if this is the correct venue to ask this so I will apologize in advance if it's not but have anyone developed a loan servicing/management type application with the serenity framework?

Thanks

**Comment by john20xdoe** [comment]
since Issues are supposedly for Serenity-code specific issues, you get limited answers. But you can try with the community at the Slack channel. (Invite yourself at https://serenityslackinvitation.herokuapp.com) =)
