### ISSUE TITLE
Navigation bar scroll

### ISSUE THREAD

**Issue by basselz** [volkanceylan/Serenity#2146]
Hi @volkanceylan 

for a laptop (resolution 1300x768) if u have many navigation bar items (the left side bar) 
it will be hidden with no possibility of reaching some items,
it can be solved by removing the class "fixed" from the _layout.cshtml
but is there any way to add scrolling functionality to the navigation bar? 

thanks

**Comment by xareas** [comment]
add to site.less

.slimScrollBar {
        background: none repeat scroll 0 0 #ca195a !important;
        border-radius: 2px!important;
        display: none;
        height: 40vh!important;
        position: absolute;
        right: 1px;
        top: 5px;
        width: 10px!important;
        z-index: 100;
        opacity:0.7!important;
}

**Comment by volkanceylan** [comment]
It works with trackball, i don't see a problem there

**Comment by basselz** [comment]
@xareas 
that actually worked,
thanks brother

**Comment by wsphuoc** [comment]
Thanks @xareas
