### ISSUE TITLE
Bulk Action Grid

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#2147]
Hello Everyone!

Could any help me to understand how can implement a Bulk Action over an Entity. 

I follow the Basic Sample CancellableBulkActionGrid but i don't understand the steps of this example, please correct me if the following flow is not correct:

1. I have in the grid the option to select some rows.

![1](https://cloud.githubusercontent.com/assets/24989427/24937091/fa0087aa-1ef3-11e7-8ee4-b4108a3c0b4b.png)

2. When select different rows and press the button Crear, the system ask me if i'll want to make the operation with the selected rows.

3. The system raise a message with the following text: All record(s) that are processed had errors! and nothing happens.

![2](https://cloud.githubusercontent.com/assets/24989427/24937190/89159174-1ef4-11e7-94d6-7c821c645fe6.png)

I need to understand step by step the calls of methods of the Sample CancellableBulkActionGrid, because not understand in which order this example works.

Please help me with some information to try to solve this scenery.

Best Regards!

Andres

**Comment by john20xdoe** [comment]
It's hard to step by step explain BulkAction without doing it by voice (but the code is easy, promise), we have to depend on your skill whether you understand about javascript callbacks.

as first step, please use Google Chrome, open Development Tools (F12), go to Network tab, then run your bulk action. click XHR and the JSON response, see what those errors are about.

or better, run in Debugging Mode and run your bulk action, see what error the controller is throwing.

**Comment by VirtualHome** [comment]
Thanks @john20xdoe
