### ISSUE TITLE
Tab questions

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2148]
I have a two part question

1.   is it possible split form fields across multiple tabs in a dialogue?

2.  is it possible to nest tabs in a dialogue?

**Comment by Estrusco** [comment]
See basic sample in Serene 

https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/OtherFormInTab
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/OtherFormInTabOneBar
