### ISSUE TITLE
[How-To] Using `const`s to map your LookupScripts keys

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#2150]
I would like to share a practice I came up with to help minimize the string literals used around a Serene template. 

When creating our own `LookupScript`, we create a class like (`using` statements removed for brevity):

```
namespace YourProjectNamespace {
    [LookupScript("Default.ActiveUsers")]  // <--- the LookupScript's "name" or key
    public class ActiveUserLookup : RowLookupScript<UserRow>
    {
        public ActiveUserLookup()
        {
            IdField = UserRow.Fields.UserId.PropertyName;
            TextField = UserRow.Fields.FullName.PropertyName;  //selected field to be viewed in combo box
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            // base.PrepareQuery(query);
            var fld = UserRow.Fields;
            query.Distinct(true)
                .Select(fld.Username, fld.FirstName, fld.LastName, fld.MiddleName, fld.UserId, fld.Email, fld.FullName)
                .Where(
                    new Criteria(fld.IsActive) == 1
                      & new Criteria(fld.IsDeleted) == 0);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
               base.ApplyOrder(query);
        }
    }
...
```
_yours may vary depending on Serene version or the code you customized_

To consume this script, we use its name in our `Row`s like
```
[LookupEditor("Default.ActiveUsers")]
public Int32? User {
 ....
}
```

And thus the LookupEditor generated in the UI will run that script when retrieving its data for the Select2 dropdown. We can also call the script by:
```
Q.getLookup("Default.ActiveUsers");
```
which will provide us with a JSON array of the entities.

**Problem: This can be prone to misspellings. Using a literal string repeatedly is not a good practice. Also, Visual Studio or IDEs do not care about the string values, whether you use them correctly or not, so if you misspell, your only clue to debug is the RUNTIME error message in the browser console.**

Now, using a simple technique, we can only place the literal value `"Default.ActiveUsers"` in the code only once, and call the script anywhere using an identifier that is used by Intellisense.

> _Currently, this only works in .cs files. If we can add this to the T4 transform scripts, then we can get typescript covered too._

See the revised code:
```
namespace YourProjectNamespace {
    [LookupScript(Key)]
    public class ActiveUserLookup : RowLookupScript<UserRow>
    {
        public static const string Key = "Default.ActiveUsers";
        public ActiveUserLookup()
        {
            IdField = UserRow.Fields.UserId.PropertyName;
            TextField = UserRow.Fields.FullName.PropertyName;  //selected field to be viewed in combo box
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            // base.PrepareQuery(query);
            var fld = UserRow.Fields;
            query.Distinct(true)
                .Select(fld.Username, fld.FirstName, fld.LastName, fld.MiddleName, fld.UserId, fld.Email, fld.FullName)
                .Where(
                    new Criteria(fld.IsActive) == 1
                      & new Criteria(fld.IsDeleted) == 0);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
               base.ApplyOrder(query);
        }
    }
```

You can formulate several LookupScripts in one file with the `[LookupScript]` attribute all the same:
```
namespace YourProjectNamespace {
    [LookupScript(Key)]
    public class ActiveUserLookup : RowLookupScript<UserRow>
    { 
        public static const string Key = "Default.ActiveUsers";
        ... 
    }

    [LookupScript(Key)]
    public class ActiveRoleLookup : RowLookupScript<RoleRow>
    { 
        public static const string Key = "Default.ActiveRoles";
        ... 
    }

    [LookupScript(Key)]
    public class ActiveSomethingLookup : RowLookupScript<SomethingRow>
    { 
        public static const string Key = "Default.ActiveSomething";
        ... 
    }
...
}
```

We can consume them in .cs `Row` as:
```
[LookupEditor(YourProjectNamespace.ActiveUserLookup.Key)]
public Int32? User {
 ....
}
```
without having to copy/paste the string literal key "Default.ActiveUsers". The only risk of misspelling the key value is on the LookupScript declaration itself, but still, VisualStudio is none the wiser and will still use the `Key` static const without causing bugs to the whole `Row`'s.

*This is also applicable to other keys such as `[ColumnScript]` , `[ServiceAuthorize]`, `[PageAuthorize]`, `[ReadPermission], [DeletePermission], etc...`*

You can create a permission mapping file like the default `Administration.PermissionKeys` class. Hopefully it can be reflected in the next `sergen`.

**TODO: find a way to also transform these `const` into Typescript form, which would probably involve updating the `.tt` files in the `Imports` folder. But it is out of my skill =)**

**Comment by volkanceylan** [comment]
You may also use LookupScript(typeof(YourLookupScript/YourRow)), but anyway planning to add more constant transfer between script/c#
