### ISSUE TITLE
2000+ compile errors in Visual Studio

### ISSUE THREAD

**Issue by rpmnickd** [volkanceylan/Serenity#2151]
I'm not sure if this is the correct place to ask for help, but I'm having a major headache over this.

I'm trying to use the Serenity template in Visual Studio 2015 Update 2. I'm getting over 2000 compile errors all related to TypeScript. These errors range from:

Cannot write file 'D:/VS2015Projects/ProjectAtlas/Atlas/Atlas/Atlas.Web/Scripts/site/Atlas.Web.d.ts' because it would overwrite input file.

to 

Duplicate identifier 'SomeIdentifier'

and

Cannot redeclare block-scoped variable 'SomeVariable'

According to the Help -> About Microsoft Visual Studio, I'm using TypeScript 1.8.31.0 and I've also installed Typescript 2.2, but it appears no where in the Extensions and Updates window.

In the project.Web.config, I have the TypeScriptToolsVersion set to 2.2.
 
This issue is also happening when I start a new project using the Serenity template without any modifications.

Please, someone tell me what I'm doing wrong.

Thanks.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/blob/master/INSTALL.md
