### ISSUE TITLE
Multiple Images Next Prev functionality

### ISSUE THREAD

**Issue by basselz** [volkanceylan/Serenity#2152]
Hi @volkanceylan 
I used MultipleImageUploader
but when the  images are loaded in the edit form I can't navigate through them,
I have to close and open one by one,
I noticed that the navigation functionality of colorbox is disabled here ,
how can we enable it ? 

Regards

**Comment by volkanceylan** [comment]
Sorry, i don't know. Try colorbox settings to if there is a default.
