### ISSUE TITLE
Dynamic connection string

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2153]
Hi
My requirement is to have multiple databases, one for each client. These DBs will be identical in terms of schema. How can i change the "default" connection string based on which client is browsing. Noting that i do know which client is browsing based on the domain they use (john.site.com, jane.site.com).

pretty much i need the ConnectionKey attribute of each entityrow to be dynamic.

I tried adding a connection key to webconfig on application_start but it seems to not pick it up.

`Configuration Config1 = WebConfigurationManager.OpenWebConfiguration("~");
            ConnectionStringsSection conSetting = (ConnectionStringsSection)Config1.GetSection("connectionStrings");
            ConnectionStringSettings stringSettings = new ConnectionStringSettings("Default", "Data Source=111.1.1.1;Initial Catalog=johnDB;Persist Security Info=True;User ID=john;Password=john123;", "System.Data.SqlClient");
            conSetting.ConnectionStrings.Remove(stringSettings);
            conSetting.ConnectionStrings.Add(stringSettings);
            Config1.Save(ConfigurationSaveMode.Modified);
            ConfigurationManager.RefreshSection("connectionStrings");`

any help appreciated!
Roy

**Comment by ArsenioInojosa** [comment]
See Service Endpoints in Tutorial [Here](https://volkanceylan.gitbooks.io/serenity-guide/content/services/service_endpoints.html)

using (var dbGlobal = SqlConnections.NewByKey("ConnectionStringsInWebConfig"))
{
     ...
}

**Comment by shakazulu89** [comment]
Hi and thanks for the reply.
I had seen that tutorial but i dont see how i can use that in my case.
I dont have a list of DBs in web config, its a list i have to recover from a "shared" db where i keep all the domains and their connection strings. Also, in SiteInit.ExceptionLog.cs there is a method:
ErrorStore.Setup("DynaHub", new SqlErrorStore(null, "Default"));
this causes an error because i have yet to set up the connection string. 
I have code that checks, based on the domain, which connection string to use and then modify the webconfig file. But I havent been able to figure out at which point to do this. Application_start is too early because i dont have access to httpcontext.request to check the domain.
Am i approaching this the wrong way?

**Comment by ArsenioInojosa** [comment]
Find your connection string in share BD
Create SqlConnection 

![image](https://cloud.githubusercontent.com/assets/11929923/25051213/7d8faebc-2119-11e7-9acb-116502329bd0.png)

Or
Find your connection string in share BD and use SqlConnections.New()

![image](https://cloud.githubusercontent.com/assets/11929923/25051252/b2b426fe-2119-11e7-9c2f-9b0df5eae356.png)

**Comment by ArsenioInojosa** [comment]
I would use a "Default DB" in the web.config for this.

**Comment by shakazulu89** [comment]
Now im thinking the only way i can do this is if i just manually select the right connection in all my Service Endpoints. Because if i just use "DefaultDB" in web.config and just change it based on the domain it might cause problems if i have many users on at the same time on different domains, it will cause the web.config to constantly change... if i understand it correctly.
If i want to modify the base service endpoint so i dont have to do it for each row, what file would i do that in?
Just want to say thanks again for the help, still coming to grips with Serenity :)

**Comment by volkanceylan** [comment]
I don't recommend trying dynamic connection thing. You better try separate apps with separate web.configs of their own. You can make use of web.config cascade from parent app to sub app in IIS, check its docs.

**Comment by volkanceylan** [comment]
I've already answered your question

**Comment by shakazulu89** [comment]
hm sorry i guess i didnt quite understand it because it seems with your suggestion ill end up having multiple code bases that ill have to keep updating across the board everytime i make a change.
Ill keep reading but if you can point in the right direction ill be greateful. but i understand if you are too busy! thanks!!!

**Comment by shakazulu89** [comment]
at the risk of nagging: ive decided to just use the manul logic you provide in your endpoint documentation
so for every module i would use this to set the connection
using (var connection = SqlConnections.NewByKey(HttpContext.Request.Url.Host))
and just add the connection strings to web.config. i can live with this.

my question is if there is a way to extend the functionality of either the iunitofwork orridbconnection o maybe the requesthandlers (or something else i completely miss) to just get the connection key based on host? that way i dont have to have this logic all over the place.

**Comment by volkanceylan** [comment]
NO

**Comment by GreenUtil** [comment]
I think I understand user shakazulu89 at some point.  SiteInitialization with public static void ApplicationStart()  and EnsureDatabase(databaseKey);   is happening before     protected void Application_BeginRequest(object sender, EventArgs e){ var cookie = Request.Cookies["LanguagePreference"];   in Global.asax.cs.  So, when some query string must be read, for example to define which database to use, the Request object is available too late to EnsureDatabase().

**Comment by GreenUtil** [comment]
I am going to use the Service Endpoints Tutorial solution as ArsenioInojosa  wrote.

**Comment by stevenrboone** [comment]
shakazulu89 and/or GreenUtil - Did you end up solving your dynamic key issue? I am trying to do something very similar with dynamic ConnectionKeys and have modified all of the *EndPoint.cs files, but have found a few functions that require the SettingRow.cs and LanguageRow.cs ConnectionKey to be set or they won't work (such as User Management, Edit User). Thanks!

**Comment by brunobola** [comment]
The behaviour can after login, for instance:

```
RoutePrefix("Account"), Route("{action=index}")]
    public partial class AccountController : Controller
    {
        public static bool UseAdminLTELoginBox = false;

        [HttpGet]
        public ActionResult Login(string activated)
        {
            ViewData["Activated"] = activated;
            ViewData["HideLeftNavigation"] = true;

            if (UseAdminLTELoginBox)
                return View(MVC.Views.Membership.Account.AccountLogin_AdminLTE);
            else
                return View(MVC.Views.Membership.Account.AccountLogin);
        }

        [HttpPost, JsonFilter]
        public Result<ServiceResponse> Login(LoginRequest request)
        {
            return this.ExecuteMethod(() =>
            {
                request.CheckNotNull();

                var company = request.Company;

                if (string.IsNullOrWhiteSpace(request.Company))
                    throw new ArgumentNullException("company");

                //Configure new Connection String
                var cs = SqlConnections.GetConnectionString("Default");
...
```

Off course there are several issues that must contemplate after like permissions etc....

**Comment by JohnRanger** [comment]
I understand the requirement very well as I also don't want to have web.configs with different sets of connection strings per application instance. The only setting which should change from web.config to web.config is an appKey setting called "Environment". Then within the app instance, the app switches its behavior according to given environment setting value. so it makes very well sense to have dynamic evaluation of connectionstring at runtime. Currently I am testing the solution presented here (modifying each xyzEndpoint.cs). But If I find a solution to modify the correct SF base classes, I will make a wiki.

Regards,

John
