### ISSUE TITLE
Firefox File upload Button alignment issue

### ISSUE THREAD

**Issue by manivishnupriya** [volkanceylan/Serenity#2156]
![image](https://cloud.githubusercontent.com/assets/20909626/25048900/030d7676-210d-11e7-8abf-0ea60652be83.png)

Please share your idea on fixing this alignment issue!

**Comment by brunobola** [comment]
You can css it accordingly or use another of your choice component.
Is this only occouring at Firefox ?

**Comment by manivishnupriya** [comment]
Yes it occurs only in firefox. Changing position as "Inherit" solves the issue. 

```
.fileinput-button
{
   position:inherit;
}
```
