### ISSUE TITLE
sergen does not pick field for IIdField IIdRow.IdField

### ISSUE THREAD

**Issue by 04071967** [volkanceylan/Serenity#2157]
Hi

I'm a big fan of Serenity and Appreciate work done around serenity, big salute to you Volkan

Requesting to help for silly issue

Tried latest build of Serenity with VS 2017 community edition, found that IIdField IIdRow.IdField does not picks the ID field automatically, My row id (identity) field is named PKEY

Even after making the following changes in the XXXXRow.cs
        IIdField IIdRow.IdField
        {
            get { return Fields.PKey; }
        }

I do not get records in Grid (List), Console is saying

Uncaught Each data element must implement a unique 'ID' property. Object at index '0' has no identity value: {"Pkey":1,"Name":"                                   ","IsActive":1,"InsertUserId":1,"InsertDate":"2016-03-20T15:17:45.633"}

But i do have identity attribute
        [DisplayName("Pkey"), Column("pkey"), NotNull, Identity]
        public Int64? Pkey
        {
            get { return Fields.Pkey[this]; }
            set { Fields.Pkey[this] = value; }
        }

Please suggest what is being overlooked here by me.

Thanks in advance

**Comment by 04071967** [comment]
Generated files for new Table, from MSSQL, using sergen 

Able to get the records in list, for this new Table, no issues

compared the cs file of row class and row.ts with one which does not gets data in list view, no difference.

Still surprised as to what is missing.

**Comment by Zahar661** [comment]
Pkey rename it to ID and it will work. This happens if the field Pkey is not the primary key or create a grid-based representation.

**Comment by volkanceylan** [comment]
Transform templates

**Comment by 04071967** [comment]
Thank you Volkan, but it never solved my issue, Build and then Transform templates are basic steps.

Did all possible ways to find missing links then i gave up and  deleted all files related to that table, regenerated them using sergen, now things are fine.

**Comment by jmace** [comment]
In your xxxxGrid.ts add

    protected getIdProperty() { return yourEntityRow.idProperty; }
