### ISSUE TITLE
net45 or net core

### ISSUE THREAD

**Issue by mickagau** [volkanceylan/Serenity#2158]
Hello
sorry if this is not right place to ask question but i do not find another place.

I find serenity really amazing and I would like to use serenity framework for one project.

I am bit confused with netcore and net45. 
Which framework to use. Serene sample is with net45 and i guess that serenity future is netcore. Am i right?

Is there a schedule to update serene sample with net core ?
Any roadmap to share for serene template or serenity framework?

Thank you very much for this project, i learn a lot :).

Mickael

**Comment by volkanceylan** [comment]
.NET Core and .NET Framework versions both work. .NET Framework version is probably used by more people, but there are some who started using other as well, so you choose.
