### ISSUE TITLE
Best Place For default Value

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#216]
I want to add the username/ID that created the record ,
lets say we have a project table with project name and date created , 
where is the best place to handle this without the need to add them manually or showing them in the form

**Comment by VictorTomaili** [comment]
Its looks like [LoggingRow](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Administration/User/LoggingRow.cs). There is [sample](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Administration/User/UserRow.cs)

**Comment by zerodev** [comment]
any other alternative of creating loggingrow class?

**Comment by VictorTomaili** [comment]
There is other alternative, you can create a behaviour for insert user info on row.
[Sample behaviour](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Web/Upload/EmbeddedFileUploadBehaviourAttribute.cs)
