### ISSUE TITLE
Viewing document attachemtents without being logged in

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#2163]
So I was wondering if there is a way, or a flag that I need to set, to not allow someone to view an attachment without being logged in. Right now if I have a file at `~/upload/articles/1_asdf2334fa.pdf` I can still view that `.pdf` if I'm not logged in. Is there a way to prevent that? Yes I know it's hard for someone to guess that but at the same time I don't want them to have the possibility to potentially guess it.

**Comment by volkanceylan** [comment]
Add an [Authorize] attribute to Read method in FileController

**Comment by williamhodges** [comment]
That works! Thanks @volkanceylan
