### ISSUE TITLE
How can I get  current "Connection" object in xxxxLookup.cs file?

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#2166]
Hello Volkan,

How can I get  current "Connection" object in xxxxLookup.cs file?

Thanks,
Harry

**Comment by Estrusco** [comment]
You can use SqlConnections.New(), SqlConnections.NewByKey() or SqlConnections.NewFor<TClass>()

**Comment by volkanceylan** [comment]
That's true, there is no current connection in Lookup class.
