### ISSUE TITLE
Sergen GUI Generator

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2167]
Hello Volcan,
Please I am using Visual Studio 2017 and have created a project using the Serene MVC template. When I am using sergen GUI to generate pages, I am not allowed to choose the module name like I could do in the past.

It appears every page you generate is automatically added to Default module name. Kindly help me as I want to capture various functionalities under different module names.

**Comment by volkanceylan** [comment]
Just click module name and edit it
