### ISSUE TITLE
While Uploading file it takes an encrypted file name, how to get the Original file name 

### ISSUE THREAD

**Issue by lizadey** [volkanceylan/Serenity#2168]
Hi,

When I upload a file , its takes an encrypted name for e.g. 00000035_nk6hhccvcodoc.pfx . Originally my file name was test.pfx but it changed to the 00000035_nk6hhccvcodoc.pfx . How to maintain the original name while uploading ?

**Comment by volkanceylan** [comment]
Not possible, write your own behavior if you need.
