### ISSUE TITLE
PDF Report Row Background Color

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#2169]
Hello!

If the PDF Reports of Serenity is a simple HTML with CSS, why the following HTML code does not make the color background will be Grey for a column, in the PDF file result.

`<td colspan="4" bgcolor="#999999">`
                `<p align="left"><strong>DESCRIPTION</strong>:</p>`
`</td>`

The PDF file would be a table with a color column Gray, and not White, or the PDF Report Generator not accepts colors in the tables HTML code?

Thanks for your help.

Andres

**Comment by edson** [comment]
Actually, it's bootstrap's css fault. You should override its css style...
something like
```
@media print {

  .table td {
    background-color: #999 !important;
    -webkit-print-color-adjust:exact;
  }
}
```

Best Regards

**Comment by volkanceylan** [comment]
Thanks @edson
