### ISSUE TITLE
using LoggingRow

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#217]
any tutorials for using LoggingRow

**Comment by VictorTomaili** [comment]
Look at the UserRow on Serene sample project. You only need implement ILoggingRow interface for an abstract row named like LoggingRow. And inherrit it from row what you want to use logging fields. Also you need create table fields on database.

**Comment by zerodev** [comment]
is there a faster way to just user DefaultValue (xxxx) , and replace it the current loggedin user?

**Comment by VictorTomaili** [comment]
Maybe in future but currently serenity has 2 way for this. Logging row and save behaviour. And its will be good option, may be we write something DefaultValue(xxxRow.field, condition) or something like this. @volkanceylan ?

**Comment by zerodev** [comment]
can ou explain about save behaviour, how dose it work if i want to use it

**Comment by VictorTomaili** [comment]
I comment on previous issue about this. But i research and find [this](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Note/NotesBehavior.cs) what i missed.You need implement `BaseSaveBehavior, IImplicitBehavior, IRetrieveBehavior`

**Comment by volkanceylan** [comment]
Please check MultiTenantcy tutorial for sample on behaviors
