### ISSUE TITLE
XYZEndpoint.cs'de storedprocedure kullandığımda arama yapmıyor

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2171]
Merhaba, 

XYZEndpoint.cs 'de aşağıdaki gibi stored procedure kullanıyorum sorun yok veriler geliyor fakat , oluşan gridde arama yapamıyorum , yardımcı olabilirmisiniz ? 

Not: XYZEndpoint.cs'de stored procedure kullanmasam, default halinde oluşan gridde arama yapıyobiliyorum 
 

 public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            
            ListResponse<MyRow> listReturn = new MyRepository().List(connection, request);
 
            var p = new DynamicParameters();
            p.Add("@p2", value: DateTime.Today.Month, dbType: DbType.Int32, direction: ParameterDirection.Input);
            p.Add("@p1", value: "sbdr", dbType: DbType.String, direction: ParameterDirection.Input);

            listReturn.Entities = (List<MyRow>)connection
                .Query<MyRow>("sp_xxx", p, commandType: CommandType.StoredProcedure);
            listReturn.Skip = request.Skip;
            listReturn.Take = request.Take;

            listReturn.TotalCount = listReturn.Entities.Count;

            return listReturn;
        }

**Comment by volkanceylan** [comment]
Aramayı kendiniz yapacaksınız, request.ContainsText e göre

**Comment by volkanturk** [comment]
Üstad merhaba, 
aşağıdaki gibi kod yazdığımda "Cannot use a CONTAINS or FREETEXT predicate on table or indexed view 'dbo.SERENE2' because it is not full-text indexed." hatası alıyorum, sizce nerde hata yapıyorum?


private class MyListHandler : ListRequestHandler<MyRow, SatisDetayListRequest>
        {
            protected override void AddFieldContainsCriteria(Field field, string containsText, long? id, SearchType searchType, bool numericOnly, ref BaseCriteria criteria, ref bool orFalse)
            {
                switch (searchType)
                {
                    case SearchType.Contains:
                        criteria |= new Criteria("Contains(" + field.Name + ", '" + containsText + "')");
                        break;

                    case SearchType.StartsWith:
                        criteria |= new Criteria("Contains(" + field.Name + ", '" + containsText + "*')");
                        break;

                    case SearchType.Equals:
                        criteria |= new Criteria("Contains(" + field.Name + ", '" + containsText + "')");
                        break;
                    default:
                        throw new ArgumentOutOfRangeException("searchType");
                }
            }
         
        }
