### ISSUE TITLE
Users Table

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2173]
Dear Volcan,
Please I have an existing database which already has a users table. I want to use this table as my users table and NOT the one generated by serene. How do I ensure my already existing users becomes the users table for the application and not the serene one? Is there any configuration I am expected to do and how would it affect upgrades?

Regards,
George

**Comment by abelal83** [comment]
this is the same issue as #2184 
you should really close this before opening another with the same problem. check the response in #2184.
