### ISSUE TITLE
Chart In Dashboard

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2174]
Hello! There are instructions or an example of the output graphs on the Dashboard? The data is taken from the grid. The only thing that found it ChartInDialog, but something is not clear((

**Comment by edson** [comment]
Check BasicSamplesEndpoint.cs and BasicSamplesModels.cs....

But really... It depends on which chart you're using and adjust data models at serverside or even at clientside... I like C3, NVD3 and ChartJs... MorrisJs is outdated and not updated anymore... 

Best Regards.

**Comment by Zahar661** [comment]
![image](https://cloud.githubusercontent.com/assets/26430136/25215222/babfc788-25a4-11e7-8718-99ca8a452320.png)

This is needed, on the client or server is not important.

**Comment by Zahar661** [comment]
It is necessary to generate here such a data output, with it the problem. ((
data: [
      {y: '2011 Q1', item1: 2666, item2: 2666},
      {y: '2011 Q2', item1: 2778, item2: 2294},
      {y: '2011 Q3', item1: 4912, item2: 1969},
      {y: '2011 Q4', item1: 3767, item2: 3597},
      {y: '2012 Q1', item1: 6810, item2: 1914},
      {y: '2012 Q2', item1: 5670, item2: 4293},
      {y: '2012 Q3', item1: 4820, item2: 3795},
      {y: '2012 Q4', item1: 15073, item2: 5967},
      {y: '2013 Q1', item1: 10687, item2: 4460},
      {y: '2013 Q2', item1: 8432, item2: 5713}
    ],

**Comment by jmace** [comment]
Using chartjs... I have the following, My data sets in the cshtml file are timeArray, flowArray, and pressureArray.... this is the last part. 

myPageIndex.cshtml
     ...
     @section Head {
     ... other scripts here...
     <script src="~/Scripts/chartjs/Chart.bundle.min.js"></script>
     ...
     <script> 
    ... Some early javascript where I reference my model using 'Model.dataA'
     //Create visual

    var lineChartData = {
        labels: time1Array,
        datasets: [{
            label: "Flow Rate (MSCFD)",
            borderColor: window.chartColors.green,
            backgroundColor: window.chartColors.green,
            fill: false,
            data: flowArray,
            yAxisID: "y-axis-1",
        }, {
            label: "Outlet Pressure (PSIG)",
            borderColor: window.chartColors.red,
            backgroundColor: window.chartColors.red,
            fill: false,
            data: pressureArray,
            yAxisID: "y-axis-2"
        }]
    };

    window.onload = function () {
        var ctx = document.getElementById("myChart").getContext("2d");
        window.myLine = Chart.Line(ctx, {
            data: lineChartData,
            options: {
                responsive: true,
                maintainAspectRatio: false,
                hoverMode: 'index',
                stacked: false,
                title: {
                    display: true,
                    text: 'Shawville Station'
                },
                scales: {
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Flow Rate (MSCFD'
                        },
                        type: "linear", // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                        display: true,
                        position: "left",
                        id: "y-axis-1",
                    }, {
                        scaleLabel: {
                            display: true,
                            labelString: 'Pressure (PSIG)'
                        },
                        type: "linear", // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                        display: true,
                        position: "right",
                        id: "y-axis-2",

                        // grid line settings
                        gridLines: {
                            drawOnChartArea: false, // only want the grid lines for one axis to show up
                        },
                    }],
                }
            }
        });
    };

</script>

Now...actually getting that data to the razor side...
In xxxxPage.cs, under my ActionResult Index(), I run the following code

    var myTempVariable = myDataEntityRow.Fields;
    var data = new DataDetails();
    using (var connection = SqlConnections.NewFor<myDataEntityRow>())
        data.DetailsA = connection.List<myDataEntityRow>(q => q
            .SelectTableFields()
       **** insert remaining  sql logic here...see serenity guide for syntax ****
    
    var myModel = new myGraphPageModel();
            myModel.dataA = data.DetailsA;
            


    public class DataDetails
    {
        public List<myDataEntityRow> DetailsA { get; set; }
    }

Finally, you need to define your model (probably actually do this before getting the data... So in myGraphPageModel.cs...

    
    using System;
    using System.Collections.Generic;
 
    namespace myProjectName.myModule
    {
    public class myGraphPageModel
    {
        public List<myModule.Entities.myDataEntityRow> dataA { get; set; }
    }
}


I've changed this code on the fly attempting to simplify and remove my own variable names, so there may be mistakes. But this will get you from querying data  from your database, Passing it through your model to the razor size, and adding it to a chartjs element for display.

Finally, Attached is an image of what I'm making using chartjs. Nothing incredible. Just results.
![graph](https://cloud.githubusercontent.com/assets/420315/25227659/65ede170-2597-11e7-859e-1eff15bd0bee.PNG)

**Comment by Zahar661** [comment]
@jmace, Please tell me. As of Model.dataA to timeArray, flowArray, and pressureArray
