### ISSUE TITLE
Tabs on form not displaying

### ISSUE THREAD

**Issue by paulobriennz** [volkanceylan/Serenity#2176]
Hello, I am having an issue getting Tabs to display on a form.  I have done this in other serenity deployments before no problem, and I just can't figure what I am doing wrong.

As per the below guide, I am creating a  _myenitityDialog.Template.html_ file but I just don't see the tabs when I preview the form.  This project is using more advanced security (roles etc) and I am wondering if its something to do with that?  Do I need to do something additional for the extra tabs to be visible?

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/listing_movies_in_person_dialog.html

Just cant figure out why I cant see the tabs (even empty) under this form...  any help appreciated..

I've tried the file in my Entity folder (generated by sergen) along with in the Views/Templates folder. I've triple checked spelling, content etc..

I've also tried the exact HTML (copy and paste) in a different (more simple) Serenity Project (admittedly with a different file name to match the specific entity) and it works - I get tabs.. so wondering if something else in the project is stopping this

**Comment by williamhodges** [comment]
Is the web console displaying any errors?

**Comment by volkanceylan** [comment]
Template file names are case sensitive. If your dialog is SomeDialog, its template should be SomeDialog.Template.html
