### ISSUE TITLE
Page don't reset when apply filter

### ISSUE THREAD

**Issue by CarlosDias7** [volkanceylan/Serenity#2177]
For demonstrate this issue I'll use an example of Nothwind models:
In the Northwind models, on the customer page there are 91 registers. Now change the Registers per Page to 20. Go to the page 2. Now, on the Country filter, put "Argentina". You'll can see there's no one register in the table because there are 3 registers that the country is Argentina and the current page shows "Page 2/1", but there isn't page 2.

**Comment by abelal83** [comment]
I think this is be design...
you are asking to filter by country on set of 20 records, of which none contain argentina so you see no records. enable debugging in web.config and look at the sql queries being carried out it will make more sense.

**Comment by CarlosDias7** [comment]
Thanks abelal83.
I sold this creating a filter buffer. So, every time that grid is populated, verify if  news filters were added. If it's true return to the page 1. (Serenity.CoreLib.js)

**Comment by abelal83** [comment]
No problem. Would be great if you could share your code if others would like to do the same.

**Comment by CarlosDias7** [comment]
In Serenity.CoreLib.js, in populate method I added this code:

if (equalityFilterBuffer != $.toJSON(request.EqualityFilter))
 {
               request.Skip = 0;
               intf.seekToPage = 1;
               equalityFilterBuffer = $.toJSON(request.EqualityFilter);
}
 else
 {
               if (containsTextBuffer != $.toJSON(request.ContainsText))
               {
                        request.Skip = 0;
                        intf.seekToPage = 1;
                        containsTextBuffer = $.toJSON(request.ContainsText);
               }
 }

Everytime that grid is changed, the filters are checked.

**Comment by abelal83** [comment]
very cool, thank you for sharing :+1:
