### ISSUE TITLE
Expression Quick Filter

### ISSUE THREAD

**Issue by kingcoskun** [volkanceylan/Serenity#2179]
Merhaba Volkan Bey,

 [DisplayName("Çözüm Durumu"), Expression("(SELECT TOP 1 TTS.Ad FROM Parametre_Sikayet_Cozum TTS where TTS.Id = (SELECT TOP 1 TTM.DurumId FROM Tanim_Sikayet_Cozum TTM where TTM.SikayetId = T0.Id))"), QuickFilter]
        [LookupEditor("NBYSCRM.ParametreSikayetCozum")]
        public String CozumAd
        {
            get { return Fields.CozumAd[this]; }
            set { Fields.CozumAd[this] = value; }
        }

şeklinde expression ile çekilmiş bir alanı quickfilter a koyuyorum. fakat quickfilter a veriler gelmesine rağmen gridde filtereleme yapmıyor. bunun için çözüm önerirseniz çok sevinirim.

İyi günler.

**Comment by volkanceylan** [comment]
CozumAd bir string alan, Id üzerinde filtreleme olur
