### ISSUE TITLE
LookUp kontrol güncellemesi

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity#218]
![p01](https://cloud.githubusercontent.com/assets/2571927/12887841/91954932-ce7f-11e5-9a3c-491597e3d192.PNG)
![p02](https://cloud.githubusercontent.com/assets/2571927/12887840/91952d94-ce7f-11e5-8348-6d808e7a9848.PNG)

Yukarıda resimde yer aldığı gibi Sorular ve yanıtları var, Yeni bir soru için grid de Yeni soru diyorum ve Yanıtlar disable geliyor, yeni soruyu tanımlayıp Kaydet resmini tıklıyorum, bu durumda Yanıtlar enable duruma geçiyor, Yanıtlar tab ına geçtiğimde ilgili lookUp içerisinde yeni kayıt ettiğim model yer almadığı için seçili kayıt boş gelmekte. Sanırım cache den geldiği için tekrar load edilmiyor.

ID yi yakalıyıp set ettikten sonra tekrar nasıl veriyi refresh edebilirim, bu örnegi Northwind den bakarak yaptım aynı sorun ilgili örnek için de geçerli, Sipariş i yeni açıp sonradan siperiş detayı girmeyi deneyince...

Konu ile ilgili nasıl bir yol izlemeliyim,

**Comment by volkanceylan** [comment]
Q.ReloadLookup("YourLookupKey")

**Comment by neonemivar** [comment]
Teşekkür ederim, sorun çözüldü.

Elinizde detaylı bir doküman var mı, ben bir süredir bu Framework üzerinde bazı uygulamalar geliştirmeye çalışıyorum, yapıyı biraz kavram isem sanırım projeye katkıda bulunma imkanım da olur, gelecek vadeden bir framework ellerinize sağlık.

**Comment by VictorTomaili** [comment]
Dökümanlar ingilizce gitbook sitesi üzerinde mevcut

**Comment by neonemivar** [comment]
İlgili dokümanlar inceledim, ancak yeterli değil, development guid tarzı bir doküman projenin yaygınlaşması daha yararlı olacaktır. Mevcut doküman sadece teknolojiyi genel olarak anlatıyor, ancak method ve iş akışları (UML) anlamında yeterli değil, bir yazılımcının en sevmediği konu doküman hazırlamaktır farkındayım ama olsa çok iyi olur, saygılarımla.
