### ISSUE TITLE
Changing Uploaded files storage method

### ISSUE THREAD

**Issue by intnovaction** [volkanceylan/Serenity#2182]
Hello,
I'm working on a cloud-based multitenant application using Serenity.
One of the difficulties I'm encountering is that, when a certain user uploads a file, the file is always stored in the application folder. And it seems that all users can access any other tenant files if they guess the url of the file.

In our very specific scenario, our desired behaviour would be to store the files in some azure storage container, specific for each tenant. So we can secure each container separately.

The problem I'm facing is that the logic of the storage is "hardcoded" in the UploadHelper and UploadProcessor, it seems that the UploadProcessor class is doing "too many things": Analyzing the file type, creating the thumbnails, and (I've not debugged it yet, so I'm not so sure) saving the file in the file system.

My suggestion is (**and I'm willing to help with a PR, testing or anything**) is to separate the actual IO logic for the save, path calculation and retreiving of the uploaded file to a "IUploadedContentStorageProvider" that can be injected with Munq, just like the IAuthenticationService.

The out-of-the-box implementantion can be the current filesystem-based flavour, but any one can implement his own in case it is needed.

Thank you!

**Comment by volkanceylan** [comment]
You can always write a custom behavior for uploads. I've written one that saves in Sharepoint and displays them from there through its web services for example. 

You may add some authentication to Read method of File controller. That's not so easy to guess file names, as they have random suffixes.

Yes, UploadProcessor has a long history and a bit complex to my taste as well, but it just works for general case.

**Comment by intnovaction** [comment]
Thanks!

I'll have to take that option. The pity is the duplication of some of the image treatment logic and things so.

Anyway: all the upload, download, seems a bit "too complex" with the uploadHelper, uploadProcessor, etc. It would be clearer if only a single (and injectable) class took care of all the file operations. So it would be easily extensible.

If you ever decide to implement that, I'm willing to help!

**Thanks again**!

**Comment by aakiff** [comment]
so did someone implemented OVH storage extender? That should be taking care of SFTP URL and user credentials I believe. I need one, else have to do it..
