### ISSUE TITLE
Using One's own Users Table

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2184]
Hello Volkan,
When you have an existing database with its own Users Table, can it be used as the Users table for serenity applications? How do you do that?

**Comment by abelal83** [comment]
you can do that, you'll need to modify UserRow.cs and most likely a lot of the files inside modules\administration\user folder.

**Comment by volkanceylan** [comment]
There is some info in guide about writing your own IAuthenticationService etc.
