### ISSUE TITLE
Asp.Net Core Project Error

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2185]
Hello Volkan,
I have created a project with the Asp.net Core which has been introduced in serenity. When I try to run the project, the error below shows:

System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Serene1.AppServices.UserCultureProvider' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Serene1.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\george.otoo\Documents\Visual Studio 2017\Projects\Serene1\Serene1\Serene1.Web\Initialization\Startup.cs:line 91

Inner Exception 1:
CultureNotFoundException: Culture is not supported.

**Comment by cp1319421** [comment]
I have met this error also， is there have any help？

**Comment by volkanceylan** [comment]
What is your Windows default culture

**Comment by cp1319421** [comment]
china

**Comment by gfo2007** [comment]
English (United States)

**Comment by volkanceylan** [comment]
Sorry i don't get such an error, maybe you should use Startup.cs from a recent template

**Comment by marc-d** [comment]
I receive the same error - has anyone found a resolution?

**Comment by samdubey** [comment]
I have commented following code to make it work on Windows OS
`public static readonly List<CultureInfo> SupportedCultures = new List<CultureInfo>
        {
            new CultureInfo("de-DE"),
            new CultureInfo("en-US"),
            //new CultureInfo("en-UK"),
            new CultureInfo("es-ES"),
            //new CultureInfo("fa-FA"),
            new CultureInfo("it-it"),
            new CultureInfo("pt-PT"),
            new CultureInfo("pt-BR"),
            new CultureInfo("ru-RU"),
            new CultureInfo("tr-TR"),
            new CultureInfo("vi-VN"),
            new CultureInfo("zh-CN")
        };`
