### ISSUE TITLE
SQL processing Issue with Serenity

### ISSUE THREAD

**Issue by arunkumar12712** [volkanceylan/Serenity#2186]
Below query runs within seconds in DB but serenity takes 3minutes or sometime more to display results. Please advice if I am missing anything
SELECT TOP 500 
T0.[Id] AS [Id],
T0.[TokenNo] AS [TokenNo],
T0.[PartyId] AS [PartyId],
T0.[ReceivedOn] AS [ReceivedOn],
T0.[PaidOn] AS [PaidOn],
T0.[LedgerId] AS [LedgerId],
T0.[ChkNeftRefNo] AS [ChkNeftRefNo],
T0.[Narration] AS [Narration],
T0.[VoucherId] AS [VoucherId],
T0.[Remarks] AS [Remarks],
T0.[MCode] AS [MCode],
T0.[OtherDeduction] AS [OtherDeduction],
T0.[OtherDeductionRemarks] AS [OtherDeductionRemarks],
T0.[ForceDeductTDS] AS [ForceDeductTDS],
T0.[PaymentMode] AS [PaymentMode],
jPaymentMode.[Name] AS [PaymentModeMode],
T0.[TDSDeclaration] AS [TDSDeclaration],
jParty.[PartyName] AS [PartyPartyName],
jParty.[ContactNo] AS [PartyContactNo],
jParty.[BankACNo] AS [PartyBankAcNo],
jParty.[IFSCCode] AS [IFSCCode],
jLedger.[LedgerName] AS [LedgerLedgerName],
T0.[Attachments] AS [Attachments],
jVoucher.[VoucherNo] AS [VoucherVoucherNo],
CASE When VoucherId IS Null Then 0 Else 1 END AS [VocuherStatus],
T0.[TokenStatus] AS [Status],
T0.[TokenBranchId] AS [TokenBranchId],
T0.[Amount] AS [Amount],
T0.[IsLock] AS [IsLock],
T0.[DiscounterId] AS [DiscounterId],
jRecovery.[Amount] * -1 AS [RecoverAdjustment],
T0.[RecoveryId] AS [RecoveryId],
T0.[FY] AS [FY],
T0.[InsertUserId] AS [InsertUserId],
T0.[InsertDate] AS [InsertDate],
T0.[UpdateUserId] AS [UpdateUserId],
T0.[UpdateDate] AS [UpdateDate] 
FROM [dbo].[Tranzol_Token] T0 
LEFT JOIN [dbo].[Accounts_PaymentMode] jPaymentMode ON (jPaymentMode.[Id] = T0.[PaymentMode]) 
LEFT JOIN [dbo].[Common_Parties] jParty ON (jParty.[Id] = T0.[PartyId]) 
LEFT JOIN [dbo].[Accounts_Ledgers] jLedger ON (jLedger.[Id] = T0.[LedgerId]) 
LEFT JOIN [dbo].[Accounts_Vouchers] jVoucher ON (jVoucher.[Id] = T0.[VoucherId]) 
LEFT JOIN [dbo].[Tranzol_Recovery] jRecovery ON (jRecovery.[Id] = T0.[RecoveryId]) 
WHERE ((T0.[FY] = @p1) AND (T0.[TokenBranchId] IN (4048,4043,4050,4034,4036,4037,4038,4047,4044,4030,4049,4051,4052,4031,4032,4042,4028,4041,4029))
ORDER BY T0.[ReceivedOn] DESC, T0.[Id] DESC;

**Comment by abelal83** [comment]
as discussed in issue #2181 this is not serenity related but a problem through dapper. Best to raise with dapper github issues.

**Comment by volkanceylan** [comment]
There is also a COUNT part of that query for grid, try running that part also in SQL
