### ISSUE TITLE
How to add charts to Serenity - Admin dashboard

### ISSUE THREAD

**Issue by rahuls-bridge** [volkanceylan/Serenity#2187]
I have tried with sample project, but i couldn't find any answer for this. how can I add charts( high charts/D3charts or any). I have also some doubts,

1. How to add stored procedure to serenity ?
2. How to fetch data from db using serenity ?

**Comment by abelal83** [comment]
stored proc - http://serenity.is/demo/BasicSamples/StoredProcedureGrid
fetch data from db - you obviously haven't used this at all as that's pretty much what serenity does, try reading the manual https://volkanceylan.gitbooks.io/serenity-guide/content/

**Comment by volkanceylan** [comment]
You add charts like usual in a MVC application. And there is several chart samples in Serene.

**Comment by rahuls-bridge** [comment]
I have found an answer, hope it will help you friends,
[](http://stackoverflow.com/questions/43516639/how-to-add-new-chartany-charts-highcharts-or-d3-charts-in-serenity-admin-dash)

**Comment by rahuls-bridge** [comment]
I have found an answer, hope it will help you friends,
[dd](url)
