### ISSUE TITLE
Working with stored procedures

### ISSUE THREAD

**Issue by SergeyRKR** [volkanceylan/Serenity#2188]
deleting from a dialog box, how do I pass multiple parameters to a stored procedure which does the removal ? DeleteRequest only supports EntityId. How to get around this problem ?

**Comment by abelal83** [comment]
dialogbox should have a reference to entityid, are you not able to pass that to DeleteRequest? maybe I don't understand but why use a stored proc when serenity handles that for you?

**Comment by SergeyRKR** [comment]
I have a complex stored procedure.
It collects aggregated data from the various tables and provides data to the user.
As such, EntityId, I'm getting a composite of A_Id, B_Id and C_Id.
In order to remove some entry, I need to pass to the stored procedure, not one 
the key is in the form of EntityId and a few

**Comment by abelal83** [comment]
OK so I guess you'll need to get A_Id, B_Id and C_Id first and pass these to the stored proc? If so, from the dialog you can query your other endpoints to get id for B and C using a relation from A and pass that to your stor proc. for example this is how I've done to get ID from another table.
```

            this.form.IntachangeUser.changeSelect2(e => {
                var selectedIntachangeUser = this.form.IntachangeUser.value;

                if (Q.isEmptyOrNull(selectedIntachangeUser)) {
                    this.setNewUserDetails({});
                    return;
                }

                //this is another way of getting the user info but it requires another service call which is not needed if data exists
                //var intachangeUsers = Q.getLookup<IntachangeStarterRow>("Deskside.IntachangeStarterUserNameLookup"); 
                //let user = Q.first(intachangeUsers.items, x => x.FullName == selectedIntachangeUser);

                var id = (Q.first(this.form.IntachangeUser.items, x =>
                    ((x.source as IntachangeStarterRow).FullName == selectedIntachangeUser)).source as IntachangeStarterRow).IcmdUid;

                //var id = (intachangeStarterRowUser.source as IntachangeStarterRow).IcmdUid;

                IntachangeStarterService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setNewUserDetails(response.Entity);
                });

```

**Comment by SergeyRKR** [comment]
It's all to do in the constructor of the dialog ?

**Comment by abelal83** [comment]
well in my case yes as I'm using the event from select2 but only because I need it to change values in other fields. you could probably override the delete button function and put your bits in there.

**Comment by SergeyRKR** [comment]
how to override the event for the delete button in the dialogue ?

**Comment by abelal83** [comment]
that bit I don't know I'm afraid, if anyone else reads this thread maybe they could assist with that.

**Comment by SergeyRKR** [comment]
thank you

**Comment by abelal83** [comment]
check #814 

shows how to intercept button events

**Comment by SergeyRKR** [comment]
what I need. thank you

**Comment by volkanceylan** [comment]
Thanks @abelal83 for your helpful contrubitions in last few days.
