### ISSUE TITLE
Creating new entries on a table based on input from another screen...

### ISSUE THREAD

**Issue by rpmnickd** [volkanceylan/Serenity#2189]
Hello. I am completely stumped on how to accomplish what I'd like to do.

I have a screen (Project) which has what the user will see as a Name and a Description. They are both text fields for the user to type in. I would like to store these on another table in the database as two entries in the Description table which has a DescriptionId and a column called Comment (this is where the text saves), then store the two newly created DescriptionId on the Project table in the Title and Description columns.

The problem I am having is that when I try to save the Project screen, it is telling me that Title cannot be null.

Here is the table structure:

Project (table)
    ProjectId (PK)
    Title (FK -> DescriptionId)
    Description (FK -> DescriptionId)

Description (table)
    DescriptionId (PK)
    Comment (Varchar)

Here is the relevant code from the ProjectRow.cs file:

    [ConnectionKey("Atlas"), TableName("[dbo].[Project]"), DisplayName("Project"), InstanceName("Project"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class ProjectRow : Row, IIdRow
    {
        //..

        [ForeignKey(typeof(DescriptionRow)), LeftJoin("jTitle"), TextualField("TitleComment")]
        [DisplayName("Name"), NotNull]
        public Int32? Title
        {
            get { return Fields.Title[this]; }
            set { Fields.Title[this] = value; }
        }

        [DisplayName("Name"), Expression("jTitle.Comment")]
        public String TitleComment
        {
            get { return Fields.TitleComment[this]; }
            set { Fields.TitleComment[this] = value; }
        }

        [ForeignKey(typeof(DescriptionRow)), LeftJoin("jDescription"), TextualField("DescriptionComment")]
        [DisplayName("Description"), NotNull]
        public Int32? Description
        {
            get { return Fields.Description[this]; }
            set { Fields.Description[this] = value; }
        }

        [DisplayName("Description"), Expression("jDescription.Comment")]
        public String DescriptionComment
        {
            get { return Fields.DescriptionComment[this]; }
            set { Fields.DescriptionComment[this] = value; }
        }

        //..

        public class RowFields : RowFieldsBase
        {
            //..

            public Int32Field Title;
            public Int32Field Description;
            public StringField TitleComment;
            public StringField DescriptionComment;

            //..

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Atlas.Project";
            }
        }
    }

**Edited for clarity.

**Comment by volkanceylan** [comment]
Remove NotNull attribute from Title
