### ISSUE TITLE
permission param in navigation link

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#219]
what should go inside the permission parameter here as string

**Comment by volkanceylan** [comment]
PermissionKey just like ReadPermission in rows etc. But it reads default from controller if you don't specify.

**Comment by kuyu7766** [comment]
after i set user Permission , when i visit the menu in permission will show alert about "Authorization has been denied for this request"

**Comment by volkanceylan** [comment]
So your page link permission and list service permission from row doesn't match. See FAQ in guide.

**Comment by kuyu7766** [comment]
where FAQ in guide thank you!

**Comment by volkanceylan** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/faq/troubleshooting.html

**Comment by iansilaran** [comment]
The page on how to register permission keys was not found or broken.
Could you send me a link to another tutorial on registering permission keys? Thank you

> https://volkanceylan.gitbooks.io/serenity-guide/content/faq/troubleshooting.html

**Comment by volkanceylan** [comment]
It's a gitbook bug, anyway it shouldn't be so hard to find that chapter in left navigation i guess, or replacing .md at end with .html

**Comment by iansilaran** [comment]
Sorry for the trouble.. Thanks!

**Comment by kuyu7766** [comment]
Sorry ,when i set Permission , on some page can not pop the dialog box when i click "new XXX" button. but if you give the user administration power ,it will be OK.  Can you help me ?
