### ISSUE TITLE
automatically generating lookupscript attributes based on foreign keys?

### ISSUE THREAD

**Issue by appetiteoven** [volkanceylan/Serenity#2192]
hi there-

amazing project. thank you!

is there a way to have serenity  automatically generate lookupscript attributes for any foreign key relationships? i'm not sure if i'm missing something but it seems i have to go in and manually add them

thanks

**Comment by abelal83** [comment]
do you mean when sergen generates code for you at that time it should decorate with [lookupscript] ?

**Comment by appetiteoven** [comment]
yes exactly. is that possible to enable during code generation?

**Comment by abelal83** [comment]
sergen generates code for you which I think you can edit within the sergen gui, you can then modify as you need before pressing generate code button. As for doing it automatically on its own I doubt it, not seen an option for it but modifying with sergen is pretty easy.

**Comment by PanChenhao** [comment]
If you have setup the foreign relation ship in database, the lookupscript code will be automatic generated,

**Comment by volkanceylan** [comment]
Somebody added that option but i'm not sure it works.

**Comment by appetiteoven** [comment]
@PanChenhao yeah that's what i was thinking and asking about. i have my FKs setup but dont get the lookup tables

@volkanceylan so that's not officially supported... you need to manually add those lookups. is that correct? if so, appreciate it. definitely would be an awesome feature to add, +1 for that and thanks for all your work on this great project.

**Comment by VR-Architect** [comment]
I created a Powershell script I called Clean.ps1 and run it after each sergen. It adds lookups, adds multi-tenant, moves the navigation, adds security, and a bunch more. A real time saver.

**Comment by appetiteoven** [comment]
@VR-Architect can you share that script in github? might be useful to myself and others.

thanks
