### ISSUE TITLE
Add predefined filter value at client side on page load

### ISSUE THREAD

**Issue by aksingh1979** [volkanceylan/Serenity#2193]
Please advice how can I set a predefined value in dropdown filter on load.

I got a grid displaying 2500 records with some filter dropdown on top of grid, but I want to have only few records loaded based on predefined filter whenever page gets first loaded based on filter. User can later choose filter based on his convenience.

Thanks

**Comment by Zahar661** [comment]
in XxxGrid.ts wriet

`protected createQuickFilters(): void {

            // let base class to create quick filters first
            super.createQuickFilters();

            // get a reference to order row field names
            let fld = Task.TaskRow.Fields;

            // find a quick filter widget by its field name
            this.findQuickFilter(Serenity.LookupEditor, fld.TaskStateId).values = ["1", "2"];
        }`
