### ISSUE TITLE
Update record : Query affected -1 rows while 1 expected!

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#2194]
Hi!

First of all thank you for this platform.

I'm facing issue on client server after deploying application. 
When I'm updating records on any table , system prompt below error.

_Query affected -1 rows while 1 expected! This might mean that your query lacks a proper WHERE statement or a TRIGGER changes number of affected rows. In the latter case, you may try adding "SET NOCOUNT ON" to your trigger code._

Not all table contains trigger.

Note: 
Update is working perfectly for all tables on my development environment.

Kindly please help to resolve this issue.

Regards,
Mustufa

**Comment by mustafalotiya** [comment]
I have added "SET NOCOUNT ON" on triggers.

**Comment by volkanceylan** [comment]
Your SQL server has NOCOUNT on global setting i guess

**Comment by mustafalotiya** [comment]
Actually Scope of "set nocount on" is a connection session (spid) . 
I run set nocount on on database also.

Still same issue.

**Comment by abelal83** [comment]
on your development environment, are you testing through serenity?

**Comment by mustafalotiya** [comment]
Yes serenity platform on both development and client side.

Anyhow, by reinstalling SQL server solved the issue. 

Thank you.

**Comment by djk4rl** [comment]
I know this is closed, but I had the same problem with a different cause and solution, so I thought I would share in case someone else had the same issue...
I had a SQL table with an ID field that was initially NOT an "Identity" field, but then changed it to be an Identity field.  I was receiving this error until I added the "Identity" attribute to the fields Attributes int the "Rows" file...
[DisplayName("Slide Id"), Column("SlideID"), PrimaryKey, Hidden, **Identity**]

**Comment by resitaufan** [comment]
@djk4rl I have same issue, could you share the solution for me?

**Comment by haajit** [comment]
> [@djk4rl](https://github.com/djk4rl) I have same issue, could you share the solution for me?

In Serenity, if you give a field the IdProperty attribute in the Row, you must also give it the Identity attribute, otherwise you will encounter this error during update.
