### ISSUE TITLE
Mysql Default ve Nortwind Tabloları

### ISSUE THREAD

**Issue by emrebayrakdar** [volkanceylan/Serenity#2196]
Selamlar Arkadaşlar, Serenity'de Mysql kullanıyorum. Default ve Nortwind tablolarının sql'ini almak istiyorum. Migration ile çalışmıyorum, direk sunucuma default ve nortwind veritabanlarını koydum ordan çalışıyorum, Fakat  Proje içerisindeki migrationları sunucuya attığımda çoğu demo ekranı çalışmıyor tablolar eksik olduğu için, default tablosu içerisinde exceptions,contacts vs tabloları yok. Migrationlar içerisinden alayım dedim, mssql olduğu için kullanamadım, mysql gerekiyor. Bunları bulabileceğim bir yer varmıdır acaba. Şimdiden teşekkürler @volkanceylan 
Örneğin alttaki default tablosunun sql'ini almak istiyorum.
![image](https://cloud.githubusercontent.com/assets/10575455/25409264/ec06b7f6-2a19-11e7-99ab-a5532fc524cf.png)

**Comment by volkanceylan** [comment]
Bir proje oluşturur, MySql ayarlarını yapar çalıştırırsınız, sonra script lerini alırsınız.
