### ISSUE TITLE
Export excel missing one column

### ISSUE THREAD

**Issue by arunkumar12712** [volkanceylan/Serenity#2198]
I am trying to export but one column is missing. That column is of type List. I tried to handle it like this
columns.Insert(6, new SlickColumn
            {
                Field = TokenRow.Fields.ChallanList.Length.ToString(),
                Title = "Challans",
                
                Format = ctx =>
                {
                    var item = (TokenRow)ctx.Item;
                    if (item.ChallanList != null)
                        return "<span style='width:100%; text-align:right; display:block'>" + item.ChallanList.Count + "</span>";
                    return "<span style='width:100%; text-align:right'>N/A</span>";
                },
                Width = 70,
            });

But still function getColumns in serenity is not considering it and for some reason still getting null.

Please advice

**Comment by volkanceylan** [comment]
Excel export uses column list you define at server side. So it is not possible to use dynamic columns.
