### ISSUE TITLE
MaxValue and MinValue not working for DateTimeEditor

### ISSUE THREAD

**Issue by erik888** [volkanceylan/Serenity#2199]
I want to set a max value for a date like so:
`[DateEditor(MaxValue = new DateTime(9999, 12, 31, 23, 59, 59, 997))]`

But i get an error:
'MaxValue' is not a valid named attribute argument because is is not a valid attribute parameter type.

Any suggestions?

**Comment by Estrusco** [comment]
In C# attributes in not possible use non const values.

**Comment by erik888** [comment]
So how do i set the max date value then?

I've a record with a date set to 31/12/9999. When i update another field, i get an error "Please enter a date before 31/12/9999"

**Comment by Estrusco** [comment]
Try with [DateEditor(MaxValue="9999-31-12")] or some like this, but I don't know if this work

**Comment by volkanceylan** [comment]
Use a ISO-8901 date string.
