### ISSUE TITLE
Lookup ile ilgili

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#220]
Volkan Selam,

Şöyle bir şey mümkün müdür ? 

Birinci ve ikinci comboboxda secılen ( yanı her ıkı degere )  göre üçüncü comboyu doldurmak  ?

**Comment by volkanceylan** [comment]
Mümkün FilterField FilterValue üzerinden ancak bağlantıyı change event inde sizin yapmanız gerekir

**Comment by Olricz** [comment]
tesekkurler. deneyecegım.
