### ISSUE TITLE
Master-Detail Versioning

### ISSUE THREAD

**Issue by pavelku** [volkanceylan/Serenity#2202]
Hello,
I'm trying to develop master-detail with versioning. Meaning that both master and detail table would have a column VersionId as part of the primary key. On update there should be an update to master column CurrentFlag on the current record and new rows should be inserted to both master and detail as a new version. 

I have been trying to find an example but I failed. I tried to debug class implemented IImplicitBehavior and ISaveBehavior but don't know which method to override. Probably OnPreparyQuery but I don't really know how but how?

Could you please point me the right direction?

Thanks in advance.

**Comment by volkanceylan** [comment]
You may try looking at source of CaptureLogBehavior.

**Comment by pavelku** [comment]
Thanks a lot. I'm looking into it. Will report back when I digest :)

**Comment by pavelku** [comment]
I looked at it as well as the source code for ISaveBehavior. CaptureLogBehavior is centered on OnAudit which is called "after row is inserted to / updated and auditing should be performed".

I will explain my issue in more detail. Let's say I have a table PRODUCT:

`CREATE TABLE PRODUCT
( 
  PRODUCT_ID INT NOT NULL,
  VERSION INT NOT NULL,
  PRODUCT_NAME NVARCHAR(200),
  PRODUCT_DESC NVARCHAR(1000),
  VERSION_TIMESTAMP DATETIME,
  VERSION_AUTHOR NVARCHAR(50),
  CURRENT INT,
  RECORD_ID INT NOT NULL IDENTITY,
  PRIMARY KEY (PRODUCT_ID,VERSION)
);
INSERT INTO PRODUCT VALUES (1,1,'Product1','Product description',getdate(),'author1',1);
`

When I have an update for PRODUCT_ID 1 and VERSION 1, I want the following to happen:
`UPDATE PRODUCT
  SET CURRENT = 0
  WHERE PRODUCT_ID = 1 AND VERSION = 1; -- or WHERE RECORD_ID = 1

INSERT INTO PRODUCT VALUES (1,2,'Product1','New product description',getdate(),'author2',1);
`
It seems to me that in OnAudit it is too late because in this case the following update has already run:
`UPDATE PRODUCT
SET PRODUCT_ID = 1,
  VERSION = 2,
  PRODUCT_NAME = 'Product1',
  PRODUCT_DESC = 'New product description',
  VERSION_TIMESTAMP = getdate(),
  VERSION_AUTHOR = 'author2',
  CURRENT = 1
WHERE RECORD_ID = 1;
`
So, much better place would be probably in any method which is call before the above update like OnBeforeSave or more likely in OnPrepareQuery. That is if I want to stick to implementing this as Behavior.

But after some digging, I see that even OnPrepareQuery is too late as the query is already setup as UPDATE. 
Therefore I created custom save request handler (inheriting from SaveRequestHandler) and overrode ExecuteSave:
`protected override void ExecuteSave()
        {
            if (IsUpdate)
            {
                if (Row.IsAnyFieldAssigned)
                {
                    var idField = (Field)Row.IdField;

                    var update = new SqlUpdate(Row.Table);
                    //update.Set(Row);
                    update.Set("Current", 0);
                    update.Where(idField == new ValueCriteria(idField.AsObject(Old))); 
                    update.Execute(Connection, ExpectedRows.One);
        
                    var entityId = Connection.InsertAndGetID(Row);
                    Response.EntityId = entityId;
                    Row.IdField[Row] = entityId;

                    Response.EntityId = idField.AsObject(Row);
                    InvalidateCacheOnCommit();
                }
            }
            else if (IsCreate)
            {
                ... stayed the same ....
            }
        }`

At the moment I need to initiate VersionTimestamp, VersionAuthor, etc. in the repository Update method but that I can deal with.

Please is there better way to deal with this?

**Comment by volkanceylan** [comment]
Not out of the box, write a trigger, write a custom behavior etc.

**Comment by pavelku** [comment]
Ok. I am ok with the functionality being in the overriden custom handler as I sketched above.
Thanks a lot!!
