### ISSUE TITLE
Working with stored procedure

### ISSUE THREAD

**Issue by kuradaganesh** [volkanceylan/Serenity#2203]
is there is any way to perform crud operations(create,retrieve,update,delete) using  stored procedure.if if it is possible how to use it??

**Comment by volkanceylan** [comment]
There is a stored proc sample. That's a good starting point. You can't use request handlers if you go stored proc way. You need to manually write endpoint methods. Before you possibly ask, i don't have a sample. See Dapper docs.

**Comment by kuradaganesh** [comment]
thank u volkanceylan
