### ISSUE TITLE
Specific Document Validation

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2204]
Hello, I am new to using serenity and would like to know how I can validate the numbering of a document through the form field, since a method was created that validates the number entered
Thank you

**Comment by volkanceylan** [comment]
I'm sorry but couldn't understand what you mean

**Comment by alexneocart** [comment]
I have a field that informs a value of 125.154.154-11 so I created a method that informs if the value is valid or invalid the problem and that I am not aware in which serenity file I perform this implementation or if the serenity has some specific method that I Insert this method you create.

**Comment by wirble** [comment]
#2159 i was able to do something similar by modifying the phoneeditor example in northwind

**Comment by alexneocart** [comment]
I solved the problem by entering the method in PersonEditor 
Using the phoneeditor
  // CPF Validation
        static validaCpf(cpf) {
            if (cpf == '')
                return false;
            // Elimina CPFs invalidos conhecidos    
            if (cpf.length != 11 ||
                cpf == "00000000000" ||
                cpf == "11111111111" ||
                cpf == "22222222222" ||
                cpf == "33333333333" ||
                cpf == "44444444444" ||
                cpf == "55555555555" ||
                cpf == "66666666666" ||
                cpf == "77777777777" ||
                cpf == "88888888888" ||
                cpf == "99999999999")
                return false;
            // Valida 1o digito 
            var add = 0;
            for (var i = 1; i < 9; i++)
                add += parseInt(cpf.charAt(i)) * (10 - i);
            var rev = 11 - (add % 11);
            if (rev == 10 || rev == 11)
                rev = 0;
            if (rev != parseInt(cpf.charAt(9)))
                return false;
            // Valida 2o digito 
            add = 0;
            for (var i = 0; i < 10; i++)
                add += parseInt(cpf.charAt(i)) * (11 - i);
            rev = 11 - (add % 11);
            if (rev == 10 || rev == 11)
                rev = 0;
            if (rev != parseInt(cpf.charAt(10)))
                return false;
            return true;
        }


    
// Validate cpf when typing the information in the field
            this.form.Cpf.addValidationRule(this.uniqueName, e => {
                var cpf: string;
                cpf = this.form.Cpf.value;   
                if (cpf != null) {
                    if (PessoaEditor.validaCpf(cpf) == true) 
                        return null;                    
                    else
                        return "erro";
                else
                    return "erro";           
            });
