### ISSUE TITLE
CORE Beta: Contact field validation is not English

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2206]
Running ASP.NET CORE Beta v2.9.21 with no changes from the initial install from Github. When entering a new contact the field validation hover-over is in a non-English language. General setting of app is in English.

**Comment by volkanceylan** [comment]
Like the other issue, meeting is not yet finalized. Thanks.

**Comment by volkanceylan** [comment]
I couldn't reproduce this issue, closing.
