### ISSUE TITLE
CORE Beta: Meeting Location Latitude / Longitude

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2207]
Running v2.9.21 ASP.NET CORE

Adding a new meeting location for New York, NY. 

Latitude needs to allow 6 decimal places. e.g. 40.712784
Longitude needs to allow negative number. e.g. -74.005941

**Comment by volkanceylan** [comment]
Meeting is not actually finalized sample, there might be some missing parts / errors. I'll take a note of this thanks.

**Comment by volkanceylan** [comment]
Should be fixed in latest version.
