### ISSUE TITLE
Sergen Incorret Load When Opened from Package Manager Console

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#2208]
When working with a solution the first time the sergen loads correctly the settings for "the web project", "Root Namespace" and consequently "Connection String", but if we close the solution and open other serene based solution and call the sergen again we have to correct the settings because they remain the last opened project.

Not so of a big problem for not so newbie users as we easy correct them, but may somehow be a pain for new users.

**Comment by volkanceylan** [comment]
Sergen uses a config file in solution directory. If package manager console is still having same PATH, so running it from another solution directory, there is nothing i can do about that.
