### ISSUE TITLE
how customizing entity insert or update  database

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#221]
if i have a dataColumn which is not filled by user,but automatic statistics generated, so I want to customize the process about insert into database. How can I do it?  
And how can i customize validation about data. Thank you!

**Comment by volkanceylan** [comment]
Override SetInternalFields and ValidateRequest methods in your SaveHandler of repository.

**Comment by kuyu7766** [comment]
think you very much
