### ISSUE TITLE
Dynamic SQL query support

### ISSUE THREAD

**Issue by ash1007** [volkanceylan/Serenity#2210]
Does serenity framework support to create the grid depending upon the SQL query supplied dynamically?
If yes is there any sample available for the same. I need to create the grid depending upon the columns pulled from 2 tables using join.
Thanks in advance

**Comment by brunobola** [comment]
Just create a view and use it.

**Comment by ash1007** [comment]
Hi Bruno, 
I think i am not make my question clear to you. I want a query to be dynamic which user can pass through any dialog or window and that query should be executed and create the grid along with data filled inside it.
(query can contain joining of 2 or 3 tables)

**Comment by volkanceylan** [comment]
There is a sample available in premium version

**Comment by ash1007** [comment]
Can you  plz let me know how to get premium version or please send me the direct link for the same.
Thanks in advance

**Comment by volkanceylan** [comment]
http://serenity.is

**Comment by LuboSta** [comment]
is there option to make something like "entry support". I am working mostly on free projects for friends or nonprofits and even 750 USD / year is much. Have no need to get extra support or developer , only access to extra samples / content. Something like 10-20 USD/month and it could be also good teaser for people to try it an then decide to go with more expensive membership. On other hand I understand that you value your work somehow and I respect that , you made really great solution

**Comment by volkanceylan** [comment]
@LuboSta i'll think about it, but premium doesn't have so many samples that you'll need for basic personal applications. I'm already sharing lots of samples in Serene. I'll put a separate demo of it after it gets more stable and more samples. It'll eventually turn into a separate product, with a separate name and support will be an extra on it.
