### ISSUE TITLE
Not able to make payment for Premium

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2211]
I tried twice with two different credit cards and not able to pay. Do you take PayPal?

Here is the error message:

Your payment cannot be completed due to an error. Please try again.
Error Message: Error in 3D Init (12332)

Pay with Debit - Credit Card
Amount to pay: 750.00 USD

**Comment by volkanceylan** [comment]
Our payment provider require 3D secure system in all payments to prevent fraud, but they don't have a system to check if your bank supports this technology, and they can't offer a solution when it doesn't. Unfortunately we can't use PayPal in my country. Please contact me from mail address for some alternatives like bank transfer, Payoneer, Transferwise etc.

**Comment by VR-Architect** [comment]
Email sent
