### ISSUE TITLE
Handling Lookup Scripts for Tenants

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2215]
On page 196 of the developer guide shows us to change the SupplierCountryLookup.cs file to  inherit MultiTenantRowLookupScript. However, I get an VS2017 editor error saying:

The type 'FCS.Northwind.Entities.SupplierRow' cannot be used as type parameter 'TRow' in the generic type or method 'MultiTenantRowLookupScript<TRow>'. There is no implicit reference conversion from 'FCS.Northwind.Entities.SupplierRow' to 'FCS.IMultiTenantRow'.

Here is the changed code line:
     public class SupplierCountryLookup : MultiTenantRowLookupScript<Entities.SupplierRow> {}

**Comment by Estrusco** [comment]
Your row must implement the IMultiTenantRow interface
