### ISSUE TITLE
Cascade table information

### ISSUE THREAD

**Issue by kboughedada** [volkanceylan/Serenity#2216]
Hi Volkan,

First thank you for your amazing work and I am a newbie in web technology.

From your example NorthWind database : 

Orders (OrderId,CustomerId ...

OrdersDetails(OrderId, ProductID .....)

Products(ProductId, ProductName, ProductRef.....

In OrdersDetailsRow : 

 [DisplayName("Product"), PrimaryKey, ForeignKey(typeof(ProductRow)), LeftJoin("p")]
        [LookupEditor(typeof(ProductRow))]
        public Int32? ProductID
        {
            get { return Fields.ProductID[this]; }
            set { Fields.ProductID[this] = value; }
        }

 [Origin("p"), MinSelectLevel(SelectLevel.List)]
        public String ProductName
        {
            get { return Fields.ProductName[this]; }
            set { Fields.ProductName[this] = value; }
        }

What I want is FROM the ProductName selected in the list TO fill the field ProductRef automatically :   

[Origin("p"), ????]
        public String ProductRef
        {
            get { return Fields.ProductRef[this]; }
            set { Fields.ProductRef[this] = value; }
        }
It is a kind of cascade but I don't know how to do it. The idea is to give more informations in Order details view.

Can you help me please ?

Thanks in advance

**Comment by Estrusco** [comment]
Use Expression attribute, some like

[Expressione("p.[ProductRef])"]
public String ProductRef
{
get { return Fields.ProductRef[this]; }
set { Fields.ProductRef[this] = value; }
}
