### ISSUE TITLE
Download link for file stored in database

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#2217]
Hello Volkan,

I have a database column of image type which contains an arbitrary file (pdf, excel, etc). Currently, this column is initialized by an outside process (outside of the webapp). How can I render this column in a grid or form as a download link?

![image](https://cloud.githubusercontent.com/assets/17013052/25504139/636a302c-2b62-11e7-82a4-b7d45a28dacd.png)

I looked thru closed issues and I see some clues on how to store files in database rather than on disk but I did not find anything on how to implement a download link to such file. I would appreciate pointing me to an existing example or another resource. Many thanks in advance.

**Comment by volkanceylan** [comment]
Hi Mark,

Try to do it like:

http://jsfiddle.net/pYpqW/

e.g. with anchor and data uri.

You can take static text block sample as starting point for your custom editor.

**Comment by c9482** [comment]
Hi Volkan,

Do you think this approach will work with very large files (20-30 MB in size)? Is there another method I could use?

**Comment by volkanceylan** [comment]
Nope id recommend something like FilePage in that case, reading from db

**Comment by c9482** [comment]
I solved my problem by creating a simple .aspx file in the project which streams the file stored in database. Then I used the UrlFormatter attribute to create the link.

[DisplayName("File Name"), Size(255), ReadOnly(true), UrlFormatter(Target = "_blank", UrlFormat = "~/DownloadAttachment.aspx?id={0}", UrlProperty = "AttachmentId")]
