### ISSUE TITLE
How to set above two ForeignKeys for same table in xxxRow.ts

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#2219]
Dear @Estrusco,

How can I set above two fields as
 ForeignKey("DevTable", "DeviceId"), LeftJoin("Dev") &  
 ForeignKey("DevTable", "SiteId"), LeftJoin("Dev") 
to link two fields in xxxxRow.ts?
(If write SQL, means " from t0 left outer join t1 on t0.SiteId=t1.SiteId and t0.DeviceId=t1.DeviceId)

Here I have two fields in xxxRow.ts

        [DisplayName("Site Id(Excluding Site Prefix Code)"), Size(7), NotNull, QuickSearch]
        public String SiteId
        {
            get { return Fields.SiteId[this]; }
            set { Fields.SiteId[this] = value; }
        }

        [DisplayName("Device Id"), Size(10), NotNull, QuickSearch]
        public String DeviceId
        {
            get { return Fields.DeviceId[this]; }
            set { Fields.DeviceId[this] = value; }
        }

Thanks,
Harry

**Comment by Estrusco** [comment]
Hi Harry. I think you can put LeftJoin attribute on top of your row

```cs
     [LeftJoin("Dev", "[dbo].[DevTable]", "T0.[SiteId] = Dev.[SiteId] and T0.[DeviceId] = Dev.[DeviceId]")]
    public sealed class xxxRow : Row, IIdRow, INameRow
    {
```

**Comment by harrypassport** [comment]
I do it as you described. It's ok now.

Thanks @Estrusco a lot.
Harry

**Comment by Estrusco** [comment]
You're welcome @harrypassport
