### ISSUE TITLE
MultiTenancy Örnegi

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#222]
Merhaba Volkan, 
MultiTenancy örnegini direkt indirdiğim gibi çalıştırınca, user yaratırken veya degıstırırken dropdownlıst gorunmuyor. Dokumanda gorunuyor sekılde var. Bı sorun mu var ornekte. Expressionları da ınceledım. Normal gorunuyor. 

Selamlar,

**Comment by volkanceylan** [comment]
admin ile mi deniyorsunuz?

**Comment by volkanceylan** [comment]
Tamam tahmin ettiğim gibi, script tarafında da Authorization.HasPermission methodu var, bu kullanıcı adı admin ise true döndürmeli.

Tutorial ı takip edip gittiğinizde Administration:Tenants yetkisini admin e atayabiliyorsunuz, ben de öyle yapmışımdır, ancak sizin database'de bu yetki atanmadığı için script tarafında yokmuş gibi algılıyor, 

Server tarafında kullanıcı admin ise HasPermission true döndürüyor, aynısı olmalı.

**Comment by Olricz** [comment]
evet. 
![volkan](https://cloud.githubusercontent.com/assets/16984654/12918343/5a8de9d0-cf47-11e5-9072-b1ffadba22ee.JPG)
![volkan2](https://cloud.githubusercontent.com/assets/16984654/12918379/89ff1978-cf47-11e5-9a33-f9df9aec2cf4.JPG)

**Comment by Olricz** [comment]
kullanıcı adı "admin" zaten.

**Comment by volkanceylan** [comment]
Son commit e bakınız.

**Comment by Olricz** [comment]
tamam. son commit ok'dir. 
Tesekkur ederim.
