### ISSUE TITLE
Problem with movie tutorial.

### ISSUE THREAD

**Issue by jheinz57** [volkanceylan/Serenity#2222]
I am new to serenity.
I have been trying to complete the movie tutorial at
https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/generating_code_for_movie_table.html

The migration worked and the movie table is there.
I think the sergen.exe had a problem generating the code
(the sergen program has a lot of different fields than what is shown in the movie demo page too, maybe I didn't configure it right).

I generated the code, rebuilt the project and ran it.
In the browser, the movie link shows in the left navigation pane, but when I click on it, I get this javascript error and a blank page is shown:

Unhandled exception at line 18, column 31635 in http://localhost:59246/DynJS.axd/Bundle.Libs.js?v=4QKvfi6rKuQIOag6lshXKw2

0x800a138f - JavaScript runtime error: Unable to get property 'MovieGrid' of undefined or null reference

Any ideas on how to resolve this issue?

Thanks,  Jeff Heiner

**Comment by VR-Architect** [comment]
Is there a MovieGrid.ts file in the project?

**Comment by jheinz57** [comment]
Yes, I have that file.  You put me in the correct direction.

"AgentPortalWeb" is the name of my project.
I had checked the project into TFS.
the Scripts/Site/AgentPortalWeb.Web.js file was read only.
It wasn't getting replaced during a rebuild as the build/clean was failing on this file.
I checked out this file and rebuilding now works correctly and I now have my movie grid.
Thanks - Jeff
