### ISSUE TITLE
How to set QuickFilter default value (older version of Servenity 2.1.9, pre .tt)

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#2224]
Hi Volkan,

I have an application built using an older version of Serenity. Trying to set the quick filter default value as such but it's not working:

```
        protected override List<QuickFilter<Widget, object>> GetQuickFilters()
        {
            List <QuickFilter<Widget, object>> filters = base.GetQuickFilters();

            QuickFilter<Widget, object> qf = filters[0];
            qf.Field = "2017";

            return filters;
        }

```
Many thanks in advance for a hint.

**Comment by volkanceylan** [comment]
That would change the field, not value, you should do similar to initializing quick filter sample
