### ISSUE TITLE
GroupBy in OrderDetailsReport

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#2225]
In OrderDetailsReport.cs

var od = OrderDetailRow.Fields;
               data.Details = connection.List<OrderDetailRow>(q => q
                   .SelectTableFields()
                   .Select(od.ProductName)
                   .Select(od.LineTotal)
                   .Where(od.OrderID == this.OrderID));

I needed to remove validation from OrderDetailsEditor.ts for the same product, now I wanted to group the same products and show the total and count,

I tried

var od = OrderDetailRow.Fields;
               data.Details = connection.List<OrderDetailRow>(q => q
                   .SelectTableFields()
                   .Select(od.ProductName)
                   .Select(Sql.Count("ProductName"))
                   .Select(od.LineTotal)
                   .Where(od.OrderID == this.OrderID));
                   .GroupBy(od.ProductName)

the list obtained isn't grouped by ProductName

**Comment by volkanceylan** [comment]
I don't think that's possible, there is a GroupBy, so it will be grouped, results may not be what you expect, turn debugging and try it directly in SQL.

**Comment by vinaykulkarni89** [comment]
Yes that works fine in SQL, 
Got another solution I just grouped them in view
Thank you for reply 👍
