### ISSUE TITLE
GridEditorBase with join field, value is empty

### ISSUE THREAD

**Issue by rogerfillion** [volkanceylan/Serenity#2228]
With Order in Northwind, when I add join field ProductQuantityPerUnit in orderDetailColumns, this field stay empty in the grid OrderDetailsEditor and the OrderDetailDialog.

What do I need to do to access the value of the join fields?

**Comment by Estrusco** [comment]
How did you declared this field on the Row?

**Comment by rogerfillion** [comment]
I use declaration on the installation demo: 

>  [Origin("p")]
>         public String ProductQuantityPerUnit
>         {
>             get { return Fields.ProductQuantityPerUnit[this]; }
>             set { Fields.ProductQuantityPerUnit[this] = value; }
>         }

And in orderDetailColumns, I add:
> public String ProductQuantityPerUnit { get; set; }

**Comment by Estrusco** [comment]
Try adding [MinSelectLevel(SelectLevel.List)] on field ProductQuantityPerUnit

```cs
        [Origin("p"), MinSelectLevel(SelectLevel.List)]
        public String ProductQuantityPerUnit
        {
            get { return Fields.ProductQuantityPerUnit[this]; }
            set { Fields.ProductQuantityPerUnit[this] = value; }
        }
```

**Comment by rogerfillion** [comment]
Tanks! 
Now this field it's show with value.
