### ISSUE TITLE
CORE Beta: Issue on Forgot Password page

### ISSUE THREAD

**Issue by Febriantos** [volkanceylan/Serenity#2229]
Error "Object reference not set to an instance of an object" on ForgotPassword screen.
![image](https://cloud.githubusercontent.com/assets/20570367/25594613/2ed96410-2e76-11e7-906b-0b6adc3c84d8.png)

**Comment by volkanceylan** [comment]
That's about config system returning null when no such section exists in .net core appsettings. Will be fixed in next version soon.
