### ISSUE TITLE
How to use external js libraries?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#223]
I saw lots of js library serenity uses; moment.js, toastr, select2, jquery,pace.js, slickgrid etc. How can i use this libraries in *Script project. 

Is there any way to call js function somitehing like:

dynamic dt = Q.Eval("moment().fromNow()")

Q.RunJavascript("$('btnOk').click()")

Q.EvaluateJs("toastr.warning('I am superman')")

**Comment by VictorTomaili** [comment]
[Here is saltarelle style sample](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Script.Imports/CKEditor/CKEditor.cs) for import js library. Look at directory too. There is too much sample.

**Comment by VictorTomaili** [comment]
Sometimes js libs has too much property. And you use it at one line. Use dynamic variable like [this](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Script.UI/Widget/Flexify.cs#L33) `object.As<dynamic>()`

**Comment by ademc** [comment]
I mean how to use external library's ability or how to call their method directly. Already I have using this components. Or I  ask

**Comment by VictorTomaili** [comment]
for moment you need static import class
`Moment.Locale()`
`Moment.format('YYYY [escaped] YYYY');     // 2016 escaped 2016`

If you dont want to implement completly
```csharp
 [Imported, IgnoreNamespace, ScriptName("Moment")] // or [ScriptName("Moment()")]
public static class Moment
{
}
```
After this class usages is like `Moment.As<dynamic>().format(...)`
if you use it as dynamic, be careful about case.

button sample is like this
`JQuery("btn").As<dynamic>().click();`

Toaster already has [import file](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Script.Imports/Toastr/Toastr.cs). Use it directly
`Toaster.Warning("I am superman")`

**Comment by volkanceylan** [comment]
You can use InlineCode on any method to write script code as you wish.

```cs
static SomeJsLibrary
{
     [InlineCode("someJsLibrary.doSomething({p1}, {p2})")]
     static void DoSomething(int p1, int p2)
     {
     }
}
```

Another option is to get an instance to window and cast it to dynamic and do what you like:

```cs
Window.Instance.As<dynamic>().Moment.format()
```

**Comment by volkanceylan** [comment]
Though, i'd recommend writing an import library, like my imports, instead of writing inline code.

**Comment by VictorTomaili** [comment]
@volkanceylan i cannot remember inlinecode attribute name :smile:

**Comment by ademc** [comment]
Thanks Victor and Volkan. This is what i need. 

These are pretty good solutions but.... 
---------nagging mode ON--------------------
still not comfortable enough using only js. Firstly we can not debug without build, and simple syntax errors takes so much time etc.  
--------nagging mode OFF-------------------
Typescript would be nice, better yet angularjs with serenity.. this is the dream team :+1: :)

**Comment by VictorTomaili** [comment]
dont say me angular js :fearful: it's scary. i use it about 5 months.

**Comment by volkanceylan** [comment]
Tryscript is not so different about debugging. There is no debug from typescript AFAIK.

**Comment by VictorTomaili** [comment]
What about [this](http://www.gamefromscratch.com/post/2014/05/27/TypeScript-debugging-in-Visual-Studio-with-IE-Chrome-and-Firefox-using-Source-Maps.aspx)?

**Comment by volkanceylan** [comment]
It doesn't debug from VS and i'm not so sure about if it really works, practice can differ. Btw, what is so hard about debugging from chrome, code is so similar anyway.

**Comment by VictorTomaili** [comment]
Similar is not same :smile: and in browser debugged source code is pure typescript. Don't compiled js.

**Comment by ademc** [comment]
Everybody likes off-topic yeah in that easy debugging is matter i can say something :)

If you like refactoring code when debugging you must try netbeans -chrome synergy.
https://www.youtube.com/watch?v=O85AV406SXI

I am not actually asp.net (or web based languages) programmer but visual studio has no enough mature tools. If serenity had not be I don’t know what I’d have done :)

**Comment by volkanceylan** [comment]
Bridge (Saltarelle next) will hopefully support debugging and add typescript import / compilation target support but its coming in Q2 2016 at best
