### ISSUE TITLE
CORE Beta: RenderViewToString is not working due to FindView problem

### ISSUE THREAD

**Issue by Febriantos** [volkanceylan/Serenity#2230]
Dear volkanceylan,

I found an error on AccountPage.ForgotPassword.cs > ForgotPassword:
var emailBody = TemplateHelper.RenderViewToString(....

The error because of this method viewEngine.FindView at TemplateHelper.cs:
var viewEngineResult = viewEngine.FindView(actionContext, viewName, false); on this file 

The error related with this issue:
https://github.com/aspnet/Mvc/issues/4936

I have solved it like this (TemplateHelper.cs > RenderViewToString):
int index = viewName.LastIndexOf('/')+1;
var executingFilePath = viewName.Substring(0, index);
var viewPath = viewName.Substring(index, viewName.Length-index);
var viewEngineResult = viewEngine.GetView(executingFilePath, viewPath, false);

and removed this code:
var viewEngineResult = viewEngine.FindView(actionContext, viewName, false);

Should I commit it or you want to commit it?

Thank you.

**Comment by volkanceylan** [comment]
Thanks @Febriantos, i just changed it into GetView and it appearently works, also had to fix a few more issues with mail system
