### ISSUE TITLE
How to update a grid after changes to the dialog box

### ISSUE THREAD

**Issue by SergeyRKR** [volkanceylan/Serenity#2232]
In the dialog box, override the click on the "delete"button:

protected getToolbarButtons(): Serenity.ToolButton[] {
let buttons = super.getToolbarButtons();
buttons.push({
                title: Q.text('Controls.EntityDialog.DeleteButton'),
                cssClass: 'delete-button',
                hotkey: 'alt+x',
                onClick: e => {
                    Q.confirm
                        ("Delete record?",
                        () => {
                            XYService.Delete(
                                {
                                    xID: this.entity.xId,
                                    yID: this.entity.yId,
                                    zID: this.entity.zId
                                }, response => {
                                    this.element.dialog().dialog('close');
                                    //this.dialogClose();
                                    window.setTimeout(() => Q.notifySuccess(Q.text('Deleted successfully')), 0);
                                });
                        }
                    );
                }
            });            
            return buttons;
}

the desired records are deleted and the dialog box closes, but how do I now update the grid ?

**Comment by SergeyRKR** [comment]
protected getToolbarButtons(): Serenity.ToolButton[] {
let buttons = super.getToolbarButtons();
buttons.push({
                title: Q.text('Controls.EntityDialog.DeleteButton'),
                cssClass: 'delete-button',
                hotkey: 'alt+x',
                onClick: e => {
                    Q.confirm
                        ("Delete record?",
                        () => {
                            XYService.Delete(
                                {
                                    xID: this.entity.xId,
                                    yID: this.entity.yId,
                                    zID: this.entity.zId
                                }, response => {
                                    this.element.dialog().dialog('close');
                                    //this.dialogClose();
                                    window.setTimeout(() => Q.notifySuccess(Q.text('Deleted successfully')), 0);
                                });
                        }
                    );
                }
            });            
            return buttons;
}

**Comment by wldkrd1** [comment]
Call this.TriggerDataChange() before closing dialog
#389

**Comment by SergeyRKR** [comment]
strange, I inserted the line of Serenity.SubDialogHelper.triggerDataChange(this); before this.dialogClose(); nothing has changed. And line this.TriggerDataChange() fails with the error: "Property does not exists triggerDataChange in XYZdialog.ts". tell me, what could be wrong ?

**Comment by wldkrd1** [comment]
What's wrong is that 'this' is no longer the context of the dialog since it's an async callback from XYZService. Add this to the top of getToolbarButtons(): 
let self = this;
then call Serenity.SubDialogHelper.triggerDataChange(self);  in the callback

**Comment by SergeyRKR** [comment]
here is the full code of the function. after removal, the grid is still not updated

protected getToolbarButtons(): Serenity.ToolButton[] {
            let self = this;

            let buttons = super.getToolbarButtons();

            buttons[Q.indexOf(buttons, x => x.cssClass == "delete-button")].onClick = e => {
                Q.confirm
                    ("Delete record?", () =>
                        {
                            CatalogService.Delete(
                                {
                                    ClientID:  this.entity.ClientId,
                                    LicenseID: this.entity.LicenseId,
                                    ProductID: this.entity.ProductId
                                }, response => {
                                    Serenity.SubDialogHelper.triggerDataChange(self);
                                    self.dialogClose();
                                    window.setTimeout(() => Q.notifySuccess(Q.text('Deleted successfully')), 0);
                                });
                        }
                    );
            };
            return buttons;
        }
