### ISSUE TITLE
Multiple Enum Values

### ISSUE THREAD

**Issue by kingcoskun** [volkanceylan/Serenity#2236]
Hi,

I have enum values. Multiptle run lookupeditor, but i need multiselect  will run enumvalues .

I search in this issue but i didn find..

Can you help me pls.

..

Merhaba,

Enumdan gelen değerler için çoklu seçim yaptırmak istiyorum. Fakat lookupeditor de multiple özelliği var. enumdan gelen değerleri çoklu seçim yapmak için ne yapmam gerekiyor. 
Yardım edebilir misiniz.

**Comment by volkanceylan** [comment]
Editör örneklerine bakınız. Enum ile olmaz.
