### ISSUE TITLE
CORE Beta: [Minor]: Mismatch validation message

### ISSUE THREAD

**Issue by Febriantos** [volkanceylan/Serenity#2237]
The validation error message for EmailInUse is CantFindUserWithEmail. It should be Texts.Validation.EmailInUse.
![image](https://cloud.githubusercontent.com/assets/20570367/25643584/724e9384-2f55-11e7-8db1-aeca7018e216.png)

**Comment by volkanceylan** [comment]
Thanks @Febriantos, fixed.
