### ISSUE TITLE
Is it possible to override LinkingSetRelation behavior?

### ISSUE THREAD

**Issue by john20xdoe** [volkanceylan/Serenity#2239]
Instead of a `[LinkingSetRelation]` to physically delete the child rows, is it possible to create an override of its behavior to just update them, like for example toggle an `IsActive` column  instead?

**Comment by Estrusco** [comment]
If not sufficient that your Row implements the IIsActiveDeletedRow ?

**Comment by john20xdoe** [comment]
Admittedly we can't and did not use that interface since the database designer used `Boolean` for the IsActive column instead of `int`. So we had to do a workaround in the C# side.

**Comment by dfaruque** [comment]
This could be helpful
implement IIsActiveDeletedRow then return a int depending on boolen value like the following
```

        public Int16Field IsActiveField
        {
            get
            {
                return IsActive?1:0;
            }
        }
```

**Comment by john20xdoe** [comment]
@dfaruque thanks let me try that.

**Comment by volkanceylan** [comment]
Your column might be boolean in database, while IsActive column in row is Int16
