### ISSUE TITLE
IIsActiveRow.IsActiveField

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#224]
In my Database IsActive Field is bit.

![untitled](https://cloud.githubusercontent.com/assets/16621563/12916018/6c2c3f2c-cf59-11e5-83b3-3f1ecab62988.png)

How to solve this?

**Comment by VictorTomaili** [comment]
IsActive field will be `[-1, 0, 1]` or some state too. I prefer convert `IsActive` field to `BooleanField`. @volkanceylan ?

**Comment by volkanceylan** [comment]
Convert field to Int16 in Row. You don't have to do it in database.

**Comment by volkanceylan** [comment]
Btw, you don't have to implement IIsActiveRow.

**Comment by dfaruque** [comment]
Thanks
