### ISSUE TITLE
Paging Error in MSSQL Server 2008

### ISSUE THREAD

**Issue by hakkism** [volkanceylan/Serenity#2240]
I have an application running with database in MSSQL Server 2008 and i want to renew it with SERENE. After creating modules with sergen, i run the application and try to use paging. Then i get the error :  "Incorrect Syntax near 'OFFSET', invalid usage of the option next in the fetch statement". Because MSSQL2008 does not have OFFSET...FETCH feature.
İyi Çalışmalar.

**Comment by volkanceylan** [comment]
Dialect topic bir okuyun
