### ISSUE TITLE
setEquality on List field

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2241]
im trying to set equality filter on a grid but i can only get it to work on a simple int field like ID. But how do i do it when i want to check if a List<int> field contains a value? 
Again the feeling of missing something simple :/

 this.setEquality(Hub.ListingRow.Fields.UserID, 1); // this works on a simple id field
 this.setEquality(Hub.ListingRow.Fields.UserList, [1,2]); // but when its a list it doesnt

**Comment by shakazulu89** [comment]
#1513 
i feel thats in the direction but i coldnt get it to work...

**Comment by shakazulu89** [comment]
maybe an easier way to explain my issue:
i have this field
`[DisplayName("Users")]
        [LookupEditor(typeof(UserRow), Multiple = true), NotMapped, LinkingSetRelation(typeof(UserListingsRow), "NumListingId", "UserId")]
        public List<Int32> UserList
        {
            get { return Fields.UserList[this]; }
            set { Fields.UserList[this] = value; }
        }`

this is the field i need to setequality on. so if this relation field contains the currently logged in user then show the record, if not filter it out.

**Comment by volkanceylan** [comment]
pass an array as value. it will search with IN filter not equals
