### ISSUE TITLE
Suggestion with Display Format

### ISSUE THREAD

**Issue by RReyes277** [volkanceylan/Serenity#2242]
Hello Group,

I am working on my first serenity project and I need a bit of help  I have been away from code in awhile and I am rusty..

What I am trying to do is turn the entries from the schedule entities on their side please see the picture below.  

I would greatly appreciate suggestions and pointers to the examples that may help

![image](https://cloud.githubusercontent.com/assets/27016786/25668660/56d86f80-2ff5-11e7-880b-773b087f95ca.png)

**Comment by wirble** [comment]
You mean you want them to print in that format or display in that format instead of the grid?

**Comment by RReyes277** [comment]
Hello 

Wirble,   I want them to display on the screen that way.

The users find it easier if the entries are listed under the Equipment name i.e. Still A

thanks for a quick reply

**Comment by RReyes277** [comment]
Wirble,

       Is it possible to make the Grid display n that format?

**Comment by Febriantos** [comment]
Try update your ScheduleColumns.cs file

**Comment by wirble** [comment]
That wouldnt make sense as a display? What you are showing is more of a report with groupings by dates. Your sample doesnt make sense to me, how do you know which stilla/b goes to which date? Is there another column to indicate a pair...

In any case of you look at the chart examples and the report example, you can create custom tables or data. I dont think you can modify the slickgrid easily to match what you want to do.

**Comment by Febriantos** [comment]
Grouping and pivoting, try it using SP and grid.

**Comment by RReyes277** [comment]
Hello,

Febriantos,

I think those are great suggestion.. If I Use a store Procedure, does that changes the  insert and edit functions?

I will take a look at the sample of the SP and Grip one more time.. 

thanks
