### ISSUE TITLE
TemplatedDialog

### ISSUE THREAD

**Issue by folkyringo** [volkanceylan/Serenity#2244]
Hi,
I'm new in Serenity Development (and also new in WebDevelopment)  and have a general Question:

is it possible to do my complete 'own thing' with TemplatedDialog? 
I need an additional Popup, beside the Standard Editdialog produced by Sergen, to do some very special Database Operations.
I created an additional button for the Standard Dialog and open a new Dialog Window (based upon TemplatedDialog). This is no problem, but I have no Idea how to put Controls into the new Popup and how to communicate with the Controller for reloading Data etc.

Maybe somebody has some codesamples that could help me?

Thanks
Volker

**Comment by volkanceylan** [comment]
You need to play with samples, read the guide etc. This is very general question.
