### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2246]
Hi All,

Before I dig through code and reinvent the wheel is it possible to make the menu text and icons different colors?

**Comment by wirble** [comment]
Yes those are all just a part of the theme.

**Comment by sayuga** [comment]
most of it can be managed through the .less. The easiest sample of this is the Content/site/site.theme.less which controls the general theme as it comes out of the box now. You could technically create a whole fresh theme if you felt so inclined.
