### ISSUE TITLE
querying with related tables

### ISSUE THREAD

**Issue by wirble** [volkanceylan/Serenity#2247]
When you do a query of a master detail tables, is there a way to automatically get all the related tables which you defined in your row.cs files.  I find that when I select for the master table, all the lookup value or lookup list are not there and gives me an error or "read before assigned a value".  I then have to separately do queries to fill in these values.  Seems highly inefficient.  Is there another way to get all related data all at once.  Like if you query a customer data in Northwind, it should get all orders and orderdetails.

                //get the main  data
                //this is how i query the data now...is there a way to get all related data  with it???
                var s =mymaintableRow.Fields;
                dataObject.Info = connection.TryById<mymaintableRow>(this.Id, q => q
                 .SelectTableFields()
                 ) ?? new mymaintableRow();

thanks

**Comment by Estrusco** [comment]
Use Retrieve of repository

```cs
    var rep = new XYZRepository();
    var request = new RetrieveRequest() { EntityId = this.Id };
    RetrieveResponse<MyRow> resp = rep.Retrieve(connection, request);

    resp.Entity.listOfYourRelatedTable ...
```

**Comment by wirble** [comment]
wow that works, it's almost as life changing as when I found Serenity. :-) Was this in the manual?  I need to read up on this repository stuff...thanks @Estrusco
