### ISSUE TITLE
Small project freelance

### ISSUE THREAD

**Issue by jgranade** [volkanceylan/Serenity#2248]
I have a Lightswitch app that I'd like to convert to Serenity.  I've actually done it testing and it works fine but there is a lot of wiring up (CRUD screens) and I think I'd rather just outsource this.  Is anyone interested in a freelance project?  

I also may have some much bigger projects that I think Serenity would work great for so that's down the road but I'd like to start with this easy one.

Thanks,

John

**Comment by volkanceylan** [comment]
Hi @jgranade, i'm referring you a friend who has experience with Serenity, please contact him by e-mail kalkan84@gmail.com
