### ISSUE TITLE
Framework Simplification

### ISSUE THREAD

**Issue by PeterAkakpo** [volkanceylan/Serenity#2251]
Hi there, mine is just  a suggestion to simplify the framework. my thoughts are influenced by the devexpress XAF framework where majority of the work is done through attributes.

consider a base object SerenityObject which is a system class where other entities inherit from. Inheriting from this class should automatically generate tables with the class name and columns with the public properties.

public class SenerityObject
{
         public int ID {get;set;}
         ......
}

public class Employee : SenenityObject
{
       public string FirstName{get;set;}
       public string LastName{get;set;}
       ......
}
this should generate a table called Employee with two columns FirstName and LastName.

From here on all other minor features should be implemented through attributes.

to make the FirstName Searchable, a system Searchable attribute should be available.

public class Employee : SenenityObject
{
       [Searchable]
       public string FirstName{get;set;}
       public string LastName{get;set;}
       ......
}
to hide the lastname in the gridview or detail view

public class Employee : SenenityObject
{
       [Searchable]
       public string FirstName{get;set;}

      [VisibileInGridView(false)]
      [VisibleInDetailView(false)]
       public string LastName{get;set;}
       ......
}

to reference another class object

public class Nationality :SenerityObject
{
      public string Name {get;set;}
}

public class Employee : SenenityObject
{
       [Searchable]
       public string FirstName{get;set;}

      [VisibileInGridView(false)]
      [VisibleInDetailView(false)]
       public string LastName{get;set;}
       public Nationality Nationality{get;set;}
}
doing this should as a new table called Nationality with ID and Name Columns

also this should update the Employee table by adding  Nationality Column that is related to the nationality table.

on the UI, a lookup should automatically be generated for the nationality on the employee details view.

**Comment by volkanceylan** [comment]
Thanks, but this is not XAF, it won't be.
