### ISSUE TITLE
Question about date picker

### ISSUE THREAD

**Issue by paulmrozowski** [volkanceylan/Serenity#2255]
I've been pulling bits and pieces of Serenity into another project, but one thing I've been struggling with is figuring out how/where the date controls get initialized and hooked up. There are a few different date picker classes in the project; I >think< the samples use JQuery UI's picker (ex. the ones on [this page](http://serenity.is/demo/Northwind/Order) . But I can't quite figure out where it's being initialized (so that things like the calendar image get hooked up, the masking works, etc.) Could anyone point me in the right direction? I could manually do it from the JQueryUI docs but I like the current behavior and don't want to have to try to figure out all the switches to get it working the same way.

**Comment by volkanceylan** [comment]
Find DateEditor.cs in code. Thats jQuery UI datepicker.
