### ISSUE TITLE
uncaught TypeError: Cannot read property 'prototype' 

### ISSUE THREAD

**Issue by basselz** [volkanceylan/Serenity#2256]
Dear @volkanceylan 

Everytime I build T4 templates and refresh I got this error 
uncaught TypeError: Cannot read property 'prototype' of undefined     at __extends (Bundle.Libs.js?v=4QKvfi6rKuQIOag6lshXKw2:223)     at Bundle.Site.js?v=cqjOHppQ5VkD2icv6C-yHg2:48

Issue2: I got undefined error every time I call isAdmin in typescript 

P.S: it didn't happened before 
now I have to close the browser and load again from VS

**Comment by volkanceylan** [comment]
You don't have proper references statement in one of your .ts files, can't know which, probably something deriving from GridEditorBase etc.

**Comment by basselz** [comment]
ok but when I close the browser and load again it works, 
so this is a bit confusing
