### ISSUE TITLE
CORE Beta: Upgrade from 2.9.21 to 2.9.22 failure

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#2257]
Hi , i use package manager console to update Serenity packages but after that vs build gives ^400 errors. In source tree i see that all of the forms scripts are removed. I try to restart, reinstall , restore but nothing works. 

```
Successfully uninstalled 'Serenity.Core 2.9.21' from PatientManagement.Web
Successfully uninstalled 'Serenity.Data 2.9.21' from PatientManagement.Web
Successfully uninstalled 'Serenity.Data.Entity 2.9.21' from PatientManagement.Web
Successfully uninstalled 'Serenity.Services 2.9.21' from PatientManagement.Web
Successfully uninstalled 'Serenity.Web 2.9.21' from PatientManagement.Web
Successfully installed 'Serenity.Core 2.9.22' to PatientManagement.Web
Successfully installed 'Serenity.Data 2.9.22' to PatientManagement.Web
Successfully installed 'Serenity.Data.Entity 2.9.22' to PatientManagement.Web
Successfully installed 'Serenity.Services 2.9.22' to PatientManagement.Web
Successfully installed 'Serenity.Web 2.9.22' to PatientManagement.Web
Executing nuget actions took 2.04 sec
Time Elapsed: 00:00:05.6105193
```
![image](https://cloud.githubusercontent.com/assets/10474555/25799370/6687dcb2-33ed-11e7-9471-c7046e7f0dab.png)

and here is  [my project](https://github.com/Magik3a/PatientManagement_Admin)

![image](https://cloud.githubusercontent.com/assets/10474555/25799453/ad8e5f50-33ed-11e7-94d8-442cec4f3b7d.png)

**Comment by volkanceylan** [comment]
Revert changes to .ts files, e.g. undelete them

**Comment by volkanceylan** [comment]
Better remove dotnet sergen servertypings, clienttypes etc. lines from csproj

**Comment by Magik3a** [comment]
Ok, now the project is building 
![image](https://cloud.githubusercontent.com/assets/10474555/25806903/944d0350-340d-11e7-8564-1711268b71da.png)

 and after that is only one error (i follow the exact documentation for MultiTenancy) 
![image](https://cloud.githubusercontent.com/assets/10474555/25806797/25c850f6-340d-11e7-9c16-1548e4c48d7e.png)

this is fixed with changing 
```
     public MultiTenantRowLookupScript()
        {
            Expiration = TimeSpan.FromDays(-1);
        }
```
to
  ```
   public MultiTenantRowLookupScript()
        {
            Expiration = TimeSpan.FromDays(0);
        }

```
But if i use 

> dotnet sergen t

the files are still removed and the errors grow as my nerves

**Comment by Magik3a** [comment]
And the lookup params are cached even after log out and login with different user (different tenant)

**Comment by volkanceylan** [comment]
try with TimeSpan.FromTicks(1) for now

**Comment by lishewen** [comment]
Set the .csproj file
`<DotNetCliToolReference Include="Serenity.CodeGenerator" Version="2.9.21" />`
to
`<DotNetCliToolReference Include="Serenity.CodeGenerator" Version="2.9.22" />`
than `dotnet sergen t` can be use
