### ISSUE TITLE
How to use 'beforeShowDay' to disable few dates before edit dialog open.

### ISSUE THREAD

**Issue by mohit18** [volkanceylan/Serenity#2258]
I have basic grid for display information, in which i have column 'ReportDate'as datetime.
Now i want to disable some dates on edit before display in ABCDialog.ts file.

i tried it in this way,

  protected beforeLoadEntity() {          
              $("#sampleDate").datepicker('DisableDate', 'beforeShowDay');
        }

  protected DisableDate() {
            alert('test');
           }

But its not working, kindly guide me on this.

**Comment by edson** [comment]
Use something like
```
this.form.sampleDate.element.datepicker("option", "beforeShowDay", this.disabledDates);

protected disabledDates(date: Date) {
            //check if date is selectable etc return true if yes false if not
            console.log(date);
            return true;
        }
```
Best Regards
