### ISSUE TITLE
Where is the localization label for Customer?

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2259]
Can anyone help me out to figure where the Customer label value is set in the Multi-tenancy demo?

Using the Multi tenancy as a base, I see in the northwind.invariant.json file has a label for customers (plural)
...
"Permission.Northwind:Customer": "Customers",
...

And I see the Customer (singular) class in NorthwindPermissionKeys.cs file

And when I run the application and look at the permissions list, customer is singular. I would have expected it to be plural as defined in the json file.

When I duplicate the setup for my table/class I don't get the value in the json file either. I get the name of the class. All my other invariant names show up fine though.

My voogu.invariant.json file:
...
{
  "Permission.Voogu:General": "[General]",
  "Permission.Voogu:MasterLocationState": "States",
  "Permission.Voogu:MasterLocationState:Delete": "Delete",
  "Permission.Voogu:MasterLocationState:Modify": "Create/Update",
  "Permission.Voogu:MasterLocationState:View": "View",
}
...
 
My VooguPermissionKeys.cs file
...
namespace MultiTenancy.Voogu
{
   public class PermissionKeys
    {
        public const string General = "Voogu:General";

        public class MasterLocationState
        {
            public const string Delete = "Voogu:MasterLocationState:Delete";
            public const string Modify = "Voogu:MasterLocationState:Modify";
            public const string View = "Voogu:MasterLocationState:View";
        }
    }
...

What shows up in the GUI:
...
Voogu
   - MasterLocationState   <= should say States
         - Create/Update
         - Delete
         - View
...

Thanks for any help.
Scott

**Comment by volkanceylan** [comment]
The permission key you should localize is "Voogu:MasterLocationState:" not "Voogu:MasterLocationState", former is group key that ends with colon while second one is a permission key

**Comment by VR-Architect** [comment]
That worked. Thank you very much!

You might consider to make the same change to the northwind.invariant.json form in the MultiTenacy demo .

**Comment by volkanceylan** [comment]
Let's hope with 2.9.23 it will be more obvious and easier.
