### ISSUE TITLE
Change Image Folder

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#226]
I want to change Folder where stores images. By default Serenity saves images in "App_Data/Upload" folder, what should I do, if i want to store images in "C://User/Documents/Images folder"
Thanks

**Comment by VictorTomaili** [comment]
What about [web.config](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Web.config#L12)

**Comment by BolatovAlau** [comment]
You are the best
Thanks
