### ISSUE TITLE
unable to create or edit record from within tab

### ISSUE THREAD

**Issue by koenmd** [volkanceylan/Serenity#2260]
Hi,

Great framework.
However I have an issue I can't find what's wrong.
I have made a detail page and from this page everything works fine (I can edit and create new records with a dialog).
When I include the list of records in a tabbed page, no extra dialog is shown (I get no javascript errors) when I click on add or edit an existing record.
To arrive at the point where I am, I looked at the Northwind Customer - Orders example.
Any advice would be very welcome!

Regards,
Koen.

**Comment by volkanceylan** [comment]
Please follow tutorial, there we have detail samples.
