### ISSUE TITLE
Numbers only

### ISSUE THREAD

**Issue by maurojblk** [volkanceylan/Serenity#2261]
How can I do to allow "numbers only" values for a field that in fact is a string?

**Comment by dfaruque** [comment]
use [DecimalEditor] on top of that field in yourRow.cs or yourForm.cs

**Comment by maurojblk** [comment]
Thanks for your reply but DecimalEditor is showing thousand separators and I need only numbers without commas.

**Comment by volkanceylan** [comment]
[IntegerEditor]

**Comment by maurojblk** [comment]
IntegerEditor does not support 25 digits

**Comment by wirble** [comment]
If nothing meets your need, you can probably follow the phoneeditor sample #2159 and write your own.  You probably just have to do  a regex check for numbers only.

**Comment by volkanceylan** [comment]
Another option is MaskEditor
