### ISSUE TITLE
HTML to PDF error

### ISSUE THREAD

**Issue by lubismargana** [volkanceylan/Serenity#2262]
Dear Mr Volkan,

I found error when used htmltopdf with error message : PDF generator returned error code -1073741701!

Please help me.

Regards,

Gomgom

**Comment by volkanceylan** [comment]
Render your report in HTML mode:

http://yoursite.com/Report/Render?key=Northwind.OrderDetail&Opt={OrderID:11085}&ext=htm&print=1

Replace key with your report key or full class name if none, opt with options your report expects in JSON format

**Comment by volkanceylan** [comment]
See if you have any exception, missing images, etc.
