### ISSUE TITLE
Why all dialogs do not work on tablets? Is this a bug or can you fix it? [VERY IMPORTANT]

### ISSUE THREAD

**Issue by jtuszynski** [volkanceylan/Serenity#2264]
Why all dialogs do not work on tablets? Is this a bug or can you fix it? [Displayed on ipad]

>
![img_0002](https://cloud.githubusercontent.com/assets/24196548/25841965/7ba1841c-34a2-11e7-9d98-774d030d9b5c.PNG)
![img_0003](https://cloud.githubusercontent.com/assets/24196548/25841966/7ba3a40e-34a2-11e7-9a13-ef7ebe2dd18e.PNG)

**Comment by volkanceylan** [comment]
It works for me

**Comment by jtuszynski** [comment]
@volkanceylan  It works, but the components do not fit properly on the page.
