### ISSUE TITLE
CORE Beta 2.9.22: Fresh project with NorthwindDB failing to find sql resources

### ISSUE THREAD

**Issue by pavelku** [volkanceylan/Serenity#2265]
Just created a new project with northwindDB samples and it keeps failing to find sql scripts for initializing the northwindDB:

Exception: Error executing migration: /* 20141123155100: DefaultDB_20141123_155100_Initial migrating =============== */ /* Beginning Transaction */ /* ExecuteEmbeddedSqlScript serene_core.Web.Migrations.NorthwindDB.NorthwindDBScript_SqlServer.sql */ /* !!! Could not find resource named serene_core.Web.Migrations.NorthwindDB.NorthwindDBScript_SqlServer.sql in assemblies serene_core.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null */ /* Rolling back transaction */

**Comment by volkanceylan** [comment]
Use a proper project name, e.g. no spaces, no underscores, pascalized words, something like MyProject

**Comment by pavelku** [comment]
Thanks. Silly me.
