### ISSUE TITLE
The demo "Entity Dialog as Panel" DetailsList Control cann't display

### ISSUE THREAD

**Issue by lishewen** [volkanceylan/Serenity#2269]
http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

the Order Details list col Quantity/Discount/Line Total cann't display value.

How to Solve?

it is normal in the gird form dialog.

**Comment by edson** [comment]
See 
https://github.com/volkanceylan/Serenity/issues/1962

Best Regards
