### ISSUE TITLE
AfterSave - Alert information

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2271]
Üstad merhaba,  aşağıdaki kodda mesaj çıkıyor ,tamam'a basınca form kapanmıyor, kapanmasını nasıl sağlarım? teşekkürler 

`private class MySaveHandler : SaveRequestHandler<MyRow> {

            protected override void AfterSave()
            {
                base.AfterSave();

                throw new ValidationError("Your message");`

**Comment by volkanturk** [comment]
Yardım edebilir misiniz :/

**Comment by volkanturk** [comment]
üstad  konuyu kapamışsınız ama ben çözüm bulamadım ,, 1-2 cümle yazsanız , bir yol gösterseniz ne kadar iyi olurdu , yanlış bir soru mu sordum anlamayamadım

**Comment by volkanceylan** [comment]
Öncelikle ingilizce yazmalısınız. Artı burası genel programlama eğitim yeri değil, adı üstünde Issue, kodları inceleyin, guide ı okuyun, platformda bir sorun olmadıkça buradan size yardım etmek gibi bir zorunluluğumuz yok, Slack te soru sorabilirsin, cevaplayan olursa

**Comment by volkanturk** [comment]
Peki üstad , bilmiyordum kusura bakmayın öğrendim , teşekkürler bilgi için , size  hak veriyorum , her yoldan geçen yazarsa yönetemezsiniz, elimden geldiğince uyacağım kurallara
