### ISSUE TITLE
Checklist ekleme

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2272]
Üstad merhaba, xyzform.cs'ye checklist nasıl ekleyebilirim ? 
sqldeki emaillerin tutulduğu table'daki satırları checklist olarak göstermek istiyorum,  bir örneği varmıdır?

teşekkürler

**Comment by volkanceylan** [comment]
role dialog bakin

**Comment by volkanturk** [comment]
Üstad forma ekleyebildim , fakat herhangi birini işaretleyip kaydetmek istediğimde "**# Unexpected token when deserializing row: EndArray**" hatası alıyorum. Aşağıda eklediğim kodlar mevcut ,nerede hata yapıyor olabilirim? 
xyzform.cs'de
`[Category("Emailler")]
 public List<BdKullanicilarRow> Emailler { get; set; }`
xyzrow.cs'de 
`[BdKullanicilarCheckEditor]
        public List<BdKullanicilarRow> Emailler
        {
            get { return Fields.Emailler[this]; }
            set { Fields.Emailler[this] = value; }
        }
        public partial class RowFields { public RowListField<BdKullanicilarRow> Emailler; }`

 BdKullanicilarCheckEditor.cs de şu şekilde
`namespace Serene_Brkt2.Center {

    @Serenity.Decorators.registerEditor()
    export class BdKullanicilarCheckEditor extends Serenity.CheckTreeEditor<Serenity.CheckTreeItem<any>, any> {

        private searchText: string;

        constructor(div: JQuery) {
            super(div);
        }

        protected createToolbarExtensions() {
            super.createToolbarExtensions();

            Serenity.GridUtils.addQuickSearchInputCustom(this.toolbar.element, (field, text) => {
                this.searchText = Select2.util.stripDiacritics(text || '').toUpperCase();
                this.view.setItems(this.view.getItems(), true);
            });
        }

        protected getButtons() {
            return [];
        }

        protected getTreeItems() {
            return BdKullanicilarRow.getLookup().items.map(BdKullanicilar => <Serenity.CheckTreeItem<any>>{
                id: BdKullanicilar.Id.toString(),
                text: BdKullanicilar.Email
            });
        }

        protected onViewFilter(item) {
            return super.onViewFilter(item) &&
                (Q.isEmptyOrNull(this.searchText) ||
                 Select2.util.stripDiacritics(item.text || '')
                     .toUpperCase().indexOf(this.searchText) >= 0);
        }
    }
}`
