### ISSUE TITLE
Why are the graphical elements of the dialog box poorly stacked on tablets? [VERY IMPORTANT]

### ISSUE THREAD

**Issue by jtuszynski** [volkanceylan/Serenity#2273]
Hi,
Why are the graphical elements of the dialog box badly stacked on tablets? [Displayed on iPad]
Graphic elements of the dialog box such as filters, text boxes do not fit well on the page. Applies to all dialogs. Is this a bug or can you fix it? [It's about  elements]
![img_0002](https://cloud.githubusercontent.com/assets/24196548/25886731/3c427a02-355f-11e7-82a6-b18553418240.PNG)
![img_0003](https://cloud.githubusercontent.com/assets/24196548/25886732/3c42fa7c-355f-11e7-8f34-f0c3982325b3.PNG)

**Comment by volkanceylan** [comment]
I accept pull requests for your very important fixes.
