### ISSUE TITLE
How to make GridEditorBase.ts to work with [Required] attribute?

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#2275]
I have successfully implemented `Serenity.IReadOnly` to work with `[ReadOnly]` attribute.

Will you please give some hints to solve the title question?

Regards.

**Comment by volkanceylan** [comment]
I don't think that's possible simply, as grid editor is not an input. You may override validateBeforeSave, raise an error and return false if it is not filled in.
