### ISSUE TITLE
Old/New value in after save

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2276]
Hello! You need to make a notification after the task is completed! Is it possible to understand that the task for the first time has passed to the status "Completed"? Or just the button to complete?

**Comment by volkanceylan** [comment]
if you mean a service call, there are samples in code

**Comment by Zahar661** [comment]
I am lol

 
    private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void AfterSave()
            {
                base.AfterSave();

                if (base.Row.TaskStateId == 3 && base.Old.TaskStateId!=3)
                {
                 .....
                 }
         }
   }
