### ISSUE TITLE
Howto update table and/or grid automatically updated when a row is added/changed/updated/deleted in database

### ISSUE THREAD

**Issue by mickagau** [volkanceylan/Serenity#2279]
Hello
I add a look to serene template sample with meeting and northwind but i did not find example showing howto update automatically table and/or grid when a row is added/changed/updated/deleted in database.

Could you point to example if any or give a way to do so with serene?

My plan was to use datatable jquery + signalR but always good to ask if something exists first

Thank You

Mickael

**Comment by brunobola** [comment]
You can use signalr has u suggested or you can implement a async task to detect changes of an entity and refresh the grid for instance, its not a good cenario when having a bad implementation because of performance or issues and overload, but its certainty possible.

**Comment by mickagau** [comment]
Hi Brunobola
what is 'bad' implemenation? 
Use of signalr, use of asynctask or the grid (or chart) auto refreshing from server event?

My need is to auto refreshing data displayed to the customer when a change in an entity is detected. 

Thanks
Mickael

**Comment by shakazulu89** [comment]
@mickagau  did you ever implement this? looking for similar functionality...
