### ISSUE TITLE
update VS2017 update 2 & Typescript 2.2 error TS2690

### ISSUE THREAD

**Issue by lishewen** [volkanceylan/Serenity#2283]
When Transforming ClientTypes 

> 1>Transforming MVC at: E:\Source\Repos\Car0774.OA\Car0774.OA\Car0774.OA.Web\Imports\MVC
> 1>Transforming ClientTypes at: E:\Source\Repos\Car0774.OA\Car0774.OA\Car0774.OA.Web\Imports\ClientTypes
> 1>E:\Source\Repos\Car0774.OA\Car0774.OA\Car0774.OA.Web\Modules\Default\OrderDetails\OrderDetailsDialog.ts(5,42): error TS2690: A class must be declared after its base class

This ts file core is:
```
namespace Car0774.OA.Default {

	@Serenity.Decorators.registerClass()
	@Serenity.Decorators.responsive()
	export class OrderDetailsDialog extends Common.GridEditorDialog<OrderDetailsRow> {
		protected getFormKey() { return OrderDetailsForm.formKey; }
		protected getLocalTextPrefix() { return OrderDetailsRow.localTextPrefix; }

		protected form: OrderDetailsForm;

		constructor() {
			super();

			this.form = new OrderDetailsForm(this.idPrefix);

			this.form.ProductId.changeSelect2(e => {
				var productID = Q.toId(this.form.ProductId.value);
				if (productID != null) {
					this.form.UnitPrice.value = ProductsRow.getLookup().itemById[productID].UnitPrice;
				}
			});

			this.form.Discount.addValidationRule(this.uniqueName, e => {
				var price = this.form.UnitPrice.value;
				var quantity = this.form.Quantity.value;
				var discount = this.form.Discount.value;
				if (price != null && quantity != null && discount != null &&
					discount > 0 && discount >= price * quantity) {
					return "折扣不能大于总价！";
				}
			});
		}
	}
}
```

My solution now is to edit the csproj and add TypeScriptToolsVersion node
`<TypeScriptToolsVersion>2.1</TypeScriptToolsVersion>`

This can be normal, but I'll try typescript 2.2,how I can modify it.

**Comment by volkanceylan** [comment]
You are missing a /// references statement
