### ISSUE TITLE
HtmlToPdfConverter Error

### ISSUE THREAD

**Issue by SergeyRKR** [volkanceylan/Serenity#2284]
Hello. 
Create pdf:
 getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            buttons.push(Common.ReportHelper.createToolButton({
                title: 'Invoice',
                cssClass: 'export-pdf-button',
                reportKey: 'Management.AccountDetail',
                extension: 'pdf',
                getParams: () => ({
                    AccountId: this.get_entityId()
                })
            }));

            return buttons;
        }
under visual studio it works, but once transferred to the test server, it gives an error
![image](https://cloud.githubusercontent.com/assets/27959956/25939278/f033f91a-363a-11e7-870c-fa0eb31a9a2d.png)

tell me, what could be wrong ? why is the file empty ?

**Comment by SergeyRKR** [comment]
maybe it's to do with this:
export namespace ReportHelper {

        export function createToolButton(options: ReportButtonOptions): Serenity.ToolButton {
            return {
                title: Q.coalesce(options.title, 'Report'),
                cssClass: Q.coalesce(options.cssClass, 'print-button'),
                icon: options.icon,
                onClick: () => {
                    ReportHelper.execute(options);
                }
            };
        }

        export function execute(options: ReportExecuteOptions) {
            var opt = options.getParams ? options.getParams() : options.params;

            Q.postToUrl({
                url: '~/Report/' + (options.download ? 'Download' : 'Render'), // ???
                params: {
                    key: options.reportKey,
                    ext: Q.coalesce(options.extension, 'pdf'),
                    opt: opt ? $.toJSON(opt) : ''
                },
                target: Q.coalesce(options.target, '_blank')
            });
        }
    }
you need to change the line: url: '~/Report/' + (options.download ? 'Download' : 'Render') ?

**Comment by Zahar661** [comment]
Hi! How to solve the problem?
