### ISSUE TITLE
How can we add custom validation in the new data creation dialog box ?

### ISSUE THREAD

**Issue by rahuls-bridge** [volkanceylan/Serenity#2285]
I'm having one drop down, by default it is mandatory and enable. But I have to check with end date. if the end date is less than current date dropdown should be  disable  otherwise it should be enable  and perform validation too. how can i implement that ?

**Comment by Estrusco** [comment]
https://github.com/volkanceylan/Serenity/issues/576

**Comment by lubismargana** [comment]
May be you can try : 
constructor(container: JQuery) {
            this.form.EndDateName.element.on("change", () => { 
if (enddate< curdate)
Serenity.EditorUtils.setReadOnly(this.form.YourDropdownname, true); 
});
        }
