### ISSUE TITLE
Custom Grid does not have the LocalTextPrefix Key

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#2287]
I have created my own grid but I cannot override the name that is being displayed. What am I missing?

![image](https://cloud.githubusercontent.com/assets/17201265/25972519/e9e23560-3665-11e7-9dc0-83502057beab.png)

**Comment by Estrusco** [comment]
You have miss to change DisplayName in your Row (and InstanceName) and you forgot to read the manual

**Comment by swordz36** [comment]
You already did that 

![image](https://cloud.githubusercontent.com/assets/17201265/26017735/c16f0236-3730-11e7-8cc1-dfe767a3b890.png)

**Comment by swordz36** [comment]
I did that also

![image](https://cloud.githubusercontent.com/assets/17201265/26017788/0176d836-3731-11e7-9734-d893a9d3dcc1.png)

**Comment by Estrusco** [comment]
See if your LocalTextPrefix in Row constructor is correct (ex "Default.ApprovedSummary")

**Comment by edson** [comment]
If your row is reusing an already existing table (i.e. there's another row with same [dbo].sometable), that happens... Probably you should customize the Report Grid based on the original table row.... it that is the issue case.

Best Regards

**Comment by volkanceylan** [comment]
set this.title in constructor

**Comment by volkanceylan** [comment]
or override getInitialTitle
