### ISSUE TITLE
Is Expression not from Database possible?

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#2288]
I want a expression field like this:
```
[Expression("ISNULL(TT_DESC,'') + '#'+ CONVERT(VARCHAR,TT_COLOR)"),OneWay]
public String Desc_Color
{
    get { return Fields.Desc_Color[this]; }
    set { Fields.Desc_Color[this] = value; }
}
```
but I find the expression **ISNULL(TT_DESC,'') + '#'+ CONVERT(VARCHAR,TT_COLOR)** does not work in some database, what I need is something like this:
```
[NotMapped]
public String Desc_Color
{
    {
        return Fields.Desc_Color[this] = Fields.Desc[this]+"#"+ Fields.Color[this];
    }
}
......
......
public Int32Field Color;
public StringField Desc;

public StringField Desc_Color;
```
And this field should be **INameRow.NameField** for lookup text field.

Does anyone have a better idea?

**Comment by volkanceylan** [comment]
No not possible. 

http://serenity.is/blog/2017/01/13/database-specific-expressions
