### ISSUE TITLE
Cascaded QuickFilter clearing bug

### ISSUE THREAD

**Issue by quidrick** [volkanceylan/Serenity#2291]
On default Northwind Customers example:
1. Select Country - for example Brazil
2. Select City
3. Clear Country using x

Result: Both filters are cleared but list is still filtered by selected city.

**Comment by volkanceylan** [comment]
This is NOT a bug, asked many times, QuickFilters doesn't support CASCADE, you need to clear it manually if you care.

**Comment by quidrick** [comment]
In that case - may I suggest removing `QuickFilterOption("cascadeFrom"` from Customers and Orders in Serene template, or marking it clearly as a not fully functional hack?
