### ISSUE TITLE
Slowdown of Typescript in VS2017

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2292]
I know this isn't Typescript repository, but anyone have experienced a slowdown in generation of Typescript (2.1.5 or 2.2.2) in VS 2017 Community?

In the same project, the generation in VS 2015 is very fast, while in VS 2017 is very very slow.

Have any idea?
I tried around but did not find a solution...

**Comment by edson** [comment]
Hi, Estrusco. I don't know if you're referring to after T4 transformation or if it's during the process...

My caveat is the after process... so I had to disable compile on save in tsconfig.json, as vs2017's node seems to recompile all ts files again in a very slow mode, blocking js file and a very consuming cpu process... The downfall is that after transforming you have to build solution again so files are updated correctly...

Best Regards

**Comment by Estrusco** [comment]
Hi @edson 
Yes, my problem is after save and in ASP.Net MVC (but I've tested it and it also happens in Core version), including the process of Node.js that spends high cpu. 
Now I have disabled the compile on save as you suggested. and the file is generated at compile time.

Thank you for suggestion :)

**Comment by edson** [comment]
Sure, @Estrusco :-)

yep, thanks @xareas . That's about it. They say it will be fixed in some release. The last one still has this problem, though. https://developercommunity.visualstudio.com/content/problem/10762/typescript-background-compilation-too-often-causes.html
