### ISSUE TITLE
Textual field not showing

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2293]
Using serenity, I am trying to show name instead of foreign Key ID but it is not working. 
I am using the following code.

`            [DisplayName("Region"), Column("RegionID"), NotNull, ForeignKey("[dbo].[Region]", "RegionID"), LeftJoin("jRegion"), TextualField("RegionRname")]
            [LookupEditor(typeof(Master.Entities.RegionRow), InplaceAdd = true)]
            public Int16? RegionId { get { return Fields.RegionId[this]; } set { Fields.RegionId[this] = value; } }
            public partial class RowFields { public Int16Field RegionId; }`

**Comment by VR-Architect** [comment]
I may be wrong, but I think the TextualField is used for searching feature and not what is displayed in the editor control. For the field you want to show, put a [LookupInclude] decorator on it. For example RegionName.

**Comment by VR-Architect** [comment]
BTW, Volkan if you see this and I am correct in my assumption. I recommend changing the name of the TextualField decorator as I also had this perception. Maybe call it SearchField? 

And it would be awesome if a new decorator could be added called DisplayField which would set which field(s) to display in a dropdown for a lookup. It could take a formula like DisplayField(FirstName + ' ' + LastName).

Of course, if I am wrong in the assumption, please disregard.

**Comment by ms4hafiz** [comment]
Thanks 
I included the [LookupInclude] decorator but it is not working. Following is my new code. 
` [DisplayName("Region"), Column("RegionID"), NotNull, ForeignKey("[dbo].[Region]", "RegionID"), LeftJoin("jRegion"), TextualField("RegionRname"),LookupInclude]`
and following is the screen shot of a list i want to display name instead of ID.
 I want to display region name instead of the Id.
 [https://drive.google.com/file/d/0B1NVPakPahSMdXR1NGtyQnRwNEk/view](url)

**Comment by volkanceylan** [comment]
Put correct name in Columns.cs, app is full of examples.
