### ISSUE TITLE
Thanks and two questions 

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2296]
Hi Volkan;

Million thanks for amazing work and facilities you made available and your support. I am exploring The Serenity to get myself acquainted with its nice features.

I would like to know how it is set to insert primary key value in foreign key value automatically when inserting data in child/subform. Like the OrderDetails, When we enter an Order Details, the Orderid is automatically inserted.

my second question is about cascade drop down. I found this guide https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html which seems to be for an earlier version. If you have an updated one that would be great.

Thanks

**Comment by volkanceylan** [comment]
Thanks @ms4hafiz, but you really should read guide, read sample code etc. I can't explain same things to everybody again and again.

**Comment by ms4hafiz** [comment]
Thanks Volkan
