### ISSUE TITLE
Date Range quick Filter issue

### ISSUE THREAD

**Issue by krupaupadhyay** [volkanceylan/Serenity#2297]
I have "DateCreated" Column in database which stored date and time. I have decorated column as QuickFilter. It shows Range Filter (As Expected) but when I try to filter grid using "DateCreated" it throws an exception , "Can not create an abstract class. Object type 'Serenity.Data.BaseCriteria'." 

In Column File
        [Width(125), AlignCenter, DisplayFormat("MM/dd/yyyy"), QuickFilter]
        public DateTime DateCreated { get; set; }

This is how Request looks like 
Criteria : [["DateCreated"], ">=", "2017-05-02"] 
          0 : ["DateCreated"]
          1: ">="
          2: "2017-05-02"

Not sure what I am doing wrong but any help would be appreciated. 

Thanks

**Comment by volkanceylan** [comment]
I don't know, it looks fine to me. Check samples.

**Comment by ahmedabdelh** [comment]
up
