### ISSUE TITLE
Guidance needed with 1 to many editors

### ISSUE THREAD

**Issue by cobusmin** [volkanceylan/Serenity#2298]
Hello. 
I need to build the following but I am not sure where to start and I can't seem to figure out how it has been done. Please can someone guide me in the right direction :)

This is what I need:
**Profile** Table: Int32Field ProfileId;StringField Name;Int32Field CategoryId;Int32Field StatusId
**Questions** Table: Int32Field QuestionId;StringField Text;Int32Field ProfileId
**Answers** Table: Int32Field AnswerId;StringField Name;StringField Image;Int32Field QuestionId;Int32Field QuestionTypeId;Int32Field PersonalityId

I have to be able to create a Profile, a Profile can have any number of Questions and each Question can have any number of Answers.

I am looking at the Northwind sample - I would like to be able to add Profiles similar to the Customers page. Then be able to select an individual Profile and be able to capture the questions for the profile. Once the questions have been captured I would like to be able to select and individual question to capture answers for the question. 

Guidance will be appreciated.

**Comment by brunobola** [comment]
I believe yo answer your own, the northwind sample alonside the samples from the various types of dialogs should help you get started. ;)

**Comment by cobusmin** [comment]
Thanks for the feedback brunobola. You are right, the problem is that I have not been able to figure out what the inner workings are and how to replicate the Northwind examples, for instance how to add the tabs or how to enable the Orders Tab only once the product has been saved. I am still learning the platform but some guidance would be appreciated. :)

I was hoping someone can give me a pseudo code example for me to get started. ie. 

> Generate the code for the 3 tables with Sergen. Then on the ProfilesRow add attribute [xyz] to ProfileId property. In ProfilesDialog.ts add the following line of code. In the QuestionsRow add a [LookupEditor] with FK and JOIN to Profiles table on ProfileId property etc... Repeat this for the other tables and you should be ok.

**Comment by volkanceylan** [comment]
Read the guide
