### ISSUE TITLE
Send mail on button click

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#2302]
In northwind after creating an Order, I have added a code in AfterSave to send auto mail, I'm wondering how can I send manual mail by clicking on send mail button 
buttons.push({
  title: 'Send Mail',
 cssClass: 'mail-button'
 onClick: ???
})

I tried adding method in Endpoint but cannot pass arguments, i tried browsing issues but none helped out

**Comment by adhikamafran** [comment]
in onclick use : [ModuleName]Service.[MethodName]([pass argument here using RequestAtribute])

**Comment by lubismargana** [comment]
onClick: () => { [ModuleName]Service.[MethodName]({[pass argument here using RequestAtribute]}) }

**Comment by vinaykulkarni89** [comment]
Thankyou will give it a try
