### ISSUE TITLE
Display 3 Decimals on the Grid

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#2303]
I've trying to show 3 decimals in the grid, but with no luck
I Tried the         [DisplayFormat("#,###")] 
In the form it shows me 3 decimals without problem(Scale(3) , but then the grid only shows me 2 and rounds the number.

Any Body have a workaround?

Thanx!

**Comment by volkanceylan** [comment]
It's #,##0.###

**Comment by javaman63** [comment]
a BIG THANK YOU @volkanceylan !!

**Comment by chrisomeara** [comment]
on save, the form was truncating my 6 decimal place numbers to two, If you are trying to get more than two decimal places to edit in the form, the following worked for me:

[DisplayName("Average Price"), Column("Average_Price"), DecimalEditor(Decimals = 8), DisplayFormat("#,##0.########"), Scale(8), AlignRight]
        public Double? AveragePrice
        {
            get { return Fields.AveragePrice[this]; }
            set { Fields.AveragePrice[this] = value; }
        }

hope that saves somebody a few hours....

**Comment by aichamansar** [comment]
> on save, the form was truncating my 6 decimal place numbers to two, If you are trying to get more than two decimal places to edit in the form, the following worked for me in the row:
> 
> [DisplayName("Average Price"), Column("Average_Price"), DecimalEditor(Decimals = 8), DisplayFormat("#,##0.########"), Scale(8), AlignRight] public Double? AveragePrice { get { return Fields.AveragePrice[this]; } set { Fields.AveragePrice[this] = value; } }
> 
> hope that saves somebody a few hours....

Thank you sooooo much ! I searched for about 1 month
