### ISSUE TITLE
Sergen Error

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2304]
Dear Volkan,
When I try to generate code with sergen, I keep getting the following error below

**"System.Exception: Couldn't locate KDiff3 utility which is required to merge changes. Please install it, or if it is not installed at default location, set its path in CodeGenerator.config"**

KDiff3 was already installed at default located when I installed serenity.I can't find CodeGenerator.config and I am unable to generate typescript code using sergen. Please help for it is urgent.

**Comment by VR-Architect** [comment]
Did you recently upgrade/patch Visual Studio by chance? When I did, I got the same error. Then I restarted VS and all worked fine.

**Comment by gfo2007** [comment]
I haven't done any upgrade or patch. I generated code from one table in my database and then I deleted all the generated code in that folder and rebuilt my solution.

When I tried to generate the code from the table again, i started getting that error.

**Comment by gfo2007** [comment]
![sergen error](https://cloud.githubusercontent.com/assets/14317420/26194755/f9633fc8-3ba8-11e7-9946-1e2794ba28e9.PNG)

**Comment by volkanceylan** [comment]
Install KDiff3

**Comment by Itsathere** [comment]
After installing KDiff3 Still getting the same exception in ASP.NET Core.

**Comment by volkanceylan** [comment]
ASP.NET Core uses "dotnet sergen", see blog posts and INSTALL.md on GitHub

**Comment by Itsathere** [comment]
Are you taking about [this](http://serenity.is/blog/2017/01/18/welcome-to-aspnet-core) documentation. If not please provide the latest documentation for ASP.NET Core.

**Comment by SalterFernandes** [comment]
I found the same problem, i just deleted the folder of the generated code from an table, and now im getting the same error.
If i try to generate code for another table it works ok, just for this particulary table im getting this problem, allready tried to install de the KDiff3 and the problem persists..

Itsathere, did you found any solution?

**Comment by javaman63** [comment]
When you delete folders from an MVC-Serenity project, what you also have to do is remove the generated tables inside the Serenity.CodeGenerator file and delete the last generated files inside the Imports\ServerTypings folder.
The files xxxxForm, xxxRow and xxxService
