### ISSUE TITLE
app asking for login continually

### ISSUE THREAD

**Issue by AlbertoAr** [volkanceylan/Serenity#2305]
Hi Volkan

Hoping you're fine, i have a problem and need your help.

Recently i publish an application with serenity, and each time i select an option of the menu, accessing a table, the application ask for the login, i'm not sure, but i remember read something similar in another issue but i can't find it, do you have any ideas???  i guess it's something related to save somewhere the information of the session and permissions...

Thanks a lot for the help and Serenity, it's very helpful :)

**Comment by shaileshbc** [comment]
It happens when Logged In User does not have permission for viewing the page and redirects to Login Page.
Check Permission of User.
