### ISSUE TITLE
An issue with compile

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2306]
Today when I want to build the serenity template. It gives the following error
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "cmd /c "npm" install" exited with code 1.	PLV.Web	:\vs2017\dontDel2\PLV\PLV\PLV.Web\PLV.Web.csproj	2726	
`

**Comment by volkanceylan** [comment]
See console for error, install NPM

**Comment by ms4hafiz** [comment]
The problem solved with re-installing it. I think there were some other app that forced the node to close. Thanks
