### ISSUE TITLE
Code generator error

### ISSUE THREAD

**Issue by likeshan168** [volkanceylan/Serenity#2307]
when we have schema like "test.test1.tablename" it does't work and I have checked the source code

 schema = tableName.Substring(0, tableName.IndexOf('.'));
 tableName = tableName.Substring(tableName.IndexOf('.') + 1);

how about changing it like the following
schema = tableName.Substring(0, tableName.LastIndexOf('.'));
tableName = tableName.Substring(tableName.LastIndexOf('.') + 1);

**Comment by volkanceylan** [comment]
Don't use such schema names, sorry it's not supported
