### ISSUE TITLE
How do I export word files?

### ISSUE THREAD

**Issue by CuiFY** [volkanceylan/Serenity#2308]
Hi,
    If I have some content to export the word file, will that be all right?

Does anyone have a better idea?

Thanks.

**Comment by lubismargana** [comment]
Maybe you can custom by using RDLC report...

**Comment by sayuga** [comment]
Right now, there is no functionality for word export. We use EPPLus and jsPDF, if i'm not mistaken, to render the Excel and PDF exports. You'll have to find a new integration or write your own.

**Comment by CuiFY** [comment]
Thank you very much! I have solved the problem by transforming HTML into PDF,so the customization of special content is realized.
