### ISSUE TITLE
Preventing of Loading Hidden LookupEditor

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#231]
In my Form, I have a Lookup editor and its visibility is set to false. But when I open this form it loads the data of lookup editor. [I see this using chrome console]

How can I prevent not to load them if they are hidden?

**Comment by VictorTomaili** [comment]
if you dont use, remove if from form.

**Comment by dfaruque** [comment]
Ok. 

Is there anyways to do this without remove them from Form.

**Comment by VictorTomaili** [comment]
if you dont want to load lookup, dont use lookupeditor. Lookup editors is [auto registering](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Script.UI/Editor/LookupEditorBase.cs#L27) on constructor when form is generated.

**Comment by VictorTomaili** [comment]
Create new editor based lookupeditor. And override `UpdateUtems` method

**Comment by volkanceylan** [comment]
Use [StringEditor] in form, though i don't understand why you want that field in form if you won't use it.

**Comment by jsbUSMC** [comment]
I think it's because he uses the form in multiple places. This is the guy with 1,000 tables

**Comment by dfaruque** [comment]
Many many thanks for helping.
