### ISSUE TITLE
Tricksy Bulk Action

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2311]
i have a tricky one for you guys, its a two part question:
1) i need to be able to add different types of "bulk actions" on a grid. but i want to avoid adding a button for each action. i was thinking a drop down and then a button to initiate the selected action. i havent found anywhere an example how to add a drop down to the grid toolbar at the top.
2) i need the ability to specify a parameter to the bulk action. for example if i want to bulk change the supplier to "Acme" i want a bulk action called "change supplier" and then you can choose to which supplier you want to change to. i can create a separate action for each supplier but you can see how that can get out of hand very fast.

thanks for any tips!

**Comment by sayuga** [comment]
A good sample about adding the drop down is : https://github.com/volkanceylan/Serenity/wiki/SplitButton-dropdowns

Additionally, if you want to pass parameters, I'd recommend you have a dialog appear asking for the parameters before the action runs. this will let you best intercept the action and edit as needed.

**Comment by shakazulu89** [comment]
@sayuga  thanks man .. ill take a look!
