### ISSUE TITLE
Slick Grid Event - disable add button if rowcount > 0

### ISSUE THREAD

**Issue by GitHubOrim** [volkanceylan/Serenity#2313]
Hi all,
i have problems to select the right event to check rowcount in slick grid.
i tried events init, refresh, initialrefresh, gridcanload etc...
I have a Master/Detail form. What i want to achieve is... on selecting row in Matergrid display all joint rows in Details-Grid... but if Details-Grid have one row (one record) disable the add button.
I trie grid.rowcount but this gives me 0
Any Idea Thanks
![t1](https://cloud.githubusercontent.com/assets/25506715/26549881/7c4155b2-447b-11e7-9627-c09fb6cb3464.jpg)

**Comment by sayuga** [comment]
I believe you just need to do something like: 

```
protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            var numRows = this.getItems().length;
            if (numRows > 0) {
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);
            }

            return buttons;
        }
```

Not 100% sure on the this.getItems().length being the row count though. I'll test it later and let you know,
