### ISSUE TITLE
dependency between two or more dropdown list

### ISSUE THREAD

**Issue by MBagherii** [volkanceylan/Serenity#2314]
I have three dropdown list in a form.one of them shows fullname of employees, another one shows his/her degree and rhe last shows his/her job.
I want to do this task : when I select a value from first dropdown other dropdowns fill automatically. for example when I selected x from first dropdown, then second dropdown became y and the last dropdown became z .what should I do? I'm new to serinity and I don't know how can I do that. 
thank you.

**Comment by volkanceylan** [comment]
See samples
