### ISSUE TITLE
How to remove login area in some modules?

### ISSUE THREAD

**Issue by alessandromoraes** [volkanceylan/Serenity#2315]
Hello, I need an area that anyone can access without login, but I can not do that in serenity. Any tips?

**Comment by volkanceylan** [comment]
Remove xyzAuthorize from pages / endpoints

**Comment by alessandromoraes** [comment]
Thanks, I made a change in ReadPermission("*") and commented PageAuthorize and ServiceAuthorize. It worked that way.

**Comment by alessandromoraes** [comment]
Rectifying my comment: It is 80% working, when I enter the page the data in the grid does not appear, but if I click on any column they appear.
If I update or access the page it runs EntityPage and does not load the data, but when I click on the column it executes the ListResponse in EntityEndpoint and shows the data.

How can I resolve this issue?

**Comment by alessandromoraes** [comment]
I solved the problem, some relations of the entity were not as public. After I removed the xyzAuthorize from the other entities that related, then it worked.
