### ISSUE TITLE
Using the dialog of one entity to update another

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2316]
Hello Volkan,
Please if I have the dialog of an entity A and I display a field of entity B and I type some value inside that field, how do I update the table that links entity A from the dialog of entity B?

**Comment by volkanceylan** [comment]
Look at customer details part of customer dialog / row

**Comment by gfo2007** [comment]
OK.I will check it up and see.

**Comment by gfo2007** [comment]
I tested the customer details dialog and it works perfectly. I however do not know which files are involved in the process to make it happen.

Can you help me?

**Comment by volkanceylan** [comment]
Row
