### ISSUE TITLE
Premium support buy now page not working ....

### ISSUE THREAD

**Issue by jheinz57** [volkanceylan/Serenity#2317]
Hi Volkan, I am trying to purchase a single developer support license.
I am in the United States.
I get to "shipping details".
 I fill out all boxes.
Proceed to pay button doesn't do anything and no error messages.
I tried Edge, Firefox, and chrome and can't get the "proceed to pay" button to work.

Thanks - Jeff

**Comment by volkanceylan** [comment]
Hi Jeff,

Please contact me from my mail address, i can offer you some alternative payment methods.
