### ISSUE TITLE
Not load new entity

### ISSUE THREAD

**Issue by yvcabrera** [volkanceylan/Serenity#2318]
I have the following problem:
When I try to create a document [the document has a receiver associated], you must load the list of receivers, as the image shows.
 
![image](https://cloud.githubusercontent.com/assets/16673786/26377701/64ccde42-3fdf-11e7-8e6d-417bd314221b.png)

There loads the receivers that were created in the database.

After that step: I try to insert a receiver into the database [using an sql statement, directly inserting the receiver]
![image](https://cloud.githubusercontent.com/assets/16673786/26377727/7f8fff0c-3fdf-11e7-8134-6e20ab95e265.png)
 

When I refresh the page and try to create a document, with the new receiver, does not appear in the list of possible receivers.
 
![image](https://cloud.githubusercontent.com/assets/16673786/26377716/71ed67b8-3fdf-11e7-89f5-e426017f2f3e.png)

I have removed the "TwoLevelCached" attribute from the "DocumentRow" entity, but it also does not load the new inserted element until I restart the internet information service [iis]

I show a summary of the classes involved:
**[ConnectionKey("Default"), DisplayName("Documento"), InstanceName("Documento")]
    [ReadPermission(PermissionKeys.DocumentoReadOnly)]
    [ModifyPermission(PermissionKeys.Documento)]
    public sealed class DocumentoRow : Row, IIdRow, INameRow**
    {
    [DisplayName("Receptor"), NotNull, ForeignKey("[dbo].[Receptor]", "Id"),
         LeftJoin("receptor"),
         TextualField("RazonSocialReceptopr")]
        public int? IdReceptor
        {
            get { return Fields.IdReceptor[this]; }
            set { Fields.IdReceptor[this] = value; }
        }
}

**[FormScript("Factura.Documento")]
    [BasedOnRow(typeof(DocumentoRow))]
    public class DocumentoForm**
    {
  [LookupEditor(typeof(ReceptorLookup))]
        public int IdReceptor { get; set; }
}

**[LookupScript("Catalogo.Receptor")]
    public class ReceptorLookup : RowLookupScript<ReceptorRow>**
    {
        public ReceptorLookup()
        {
            IdField = ReceptorRow.Fields.Id.PropertyName;
            TextField = ReceptorRow.Fields.RazonSocial.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            query.Select(ReceptorRow.Fields.Id)
                .Select(ReceptorRow.Fields.Documento)
                .Select(ReceptorRow.Fields.RazonSocial)
                .Select(ReceptorRow.Fields.IdTipoDocReceptor);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }

**Comment by Estrusco** [comment]
Try Q.reloadLookup(someRow.lookupKey);

**Comment by volkanceylan** [comment]
Also set timeout to negative in LookupScript

**Comment by yvcabrera** [comment]
Hi @volkanceylan , do you can explaining, do you have any examples?

**Comment by volkanceylan** [comment]
Please search in prior issues.
