### ISSUE TITLE
Need help to use NOLOCK in select queries

### ISSUE THREAD

**Issue by aksingh1979** [volkanceylan/Serenity#2319]
Can you please advice on how to use NOLOCK in select within Serenity? or if it is possible or not?
Thanks

**Comment by volkanceylan** [comment]
It is not possible in standard queries. You can use that with Dapper though.

**Comment by aksingh1979** [comment]
Thanks Volkan.
Sorry not sure I understood, I was thinking in context to Serenity. I mean sort of flag anywhere which could help may be.

**Comment by volkanceylan** [comment]
You asked if it is possible, and i said it is not possible, what is that you didn't understand?

**Comment by aksingh1979** [comment]
Thanks, within Serenity, do I have option to set it up in Drapper?  something like

using (new TransactionScope(
                    TransactionScopeOption.Required, 
                    new TransactionOptions 
                    { 
                         IsolationLevel = IsolationLevel.ReadUncommitted 
                    })) 
{
        using (var db = new MyDbContext()) { 
            // SELECT VoucherId from transaction where fyid=2
        }
}

**Comment by volkanceylan** [comment]
https://github.com/StackExchange/Dapper
