### ISSUE TITLE
serenity cannot be properly resolved

### ISSUE THREAD

**Issue by yvcabrera** [volkanceylan/Serenity#2321]
I lost the reference:

![image](https://cloud.githubusercontent.com/assets/16673786/26425935/a0ea4930-40a4-11e7-847d-cff4760f54cc.png)

**Comment by dfaruque** [comment]
please describe how it happened? Or after which action ?

**Comment by volkanceylan** [comment]
Check that you have Serenity.CoreLib.d.ts, reinstall NuGet if not
