### ISSUE TITLE
Role Permission

### ISSUE THREAD

**Issue by AliPoyraz** [volkanceylan/Serenity#2323]
Hi I want to make the role settings. How can I edit this field as seen in the image. 

For example, I want to delete the field I want, update the field. Also, the newly created database does not appear in the authorization list.

I will not make the user table while the other problem is creating the table. But when I enter the record, it shows how the recording is entered by who.

Can you help me. [https://i.hizliresim.com/r3AJDm.png](url)

**Comment by sayuga** [comment]
Image link is broke. The authorization list, which I am assuming you mean the permissions tab, fills in according to the [xyzPermission()] attribute at each Row Class. Check that the permissions are properly filled in. It could be that you are using the same permission for multiple tables thus it's listing them all together under one tag.
