### ISSUE TITLE
How to get Active Filter text just like advanced filter does in grid footer

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#2324]
request.EqualityFilter provides the following Object
`{someId:"1101"}`
which is fine for database queries. but when grid data is exported to Pdf or Other. It is need to show Active Filter just like advanced filter does in grid footer. e.g
![image](https://cloud.githubusercontent.com/assets/16621563/26452247/151cc486-4181-11e7-8446-26bbf86d2d89.png)

How can I get same text for applied quick filters also?

I can do this by manual coding. But a generic solution will be great.

Thanks.

**Comment by dfaruque** [comment]
I have managed it by the following method. 

        protected getReportRequest(): ReportRequest {
            let view = this.getView();
            var request = Q.deepClone(view ? view.params : {}) as ReportRequest;
            request.ReportServiceMethodName = null;     // if some value found in this property than "view as report" button will appear
            request.ReportKey = null;                   // if some value found in this property than "export to pdf" button will appear
            request.ListExcelServiceMethodName = null;  // if some value found in this property than "export to xls" button will appear
            request.EqualityFilterWithTextValue = {};

            if (request.EqualityFilter) {
                let quickFilters = this.getQuickFilters();

                for (let ef in request.EqualityFilter) {
                    let quickFilter = Q.first(quickFilters, x => x.field == ef);
                    let filterValue = request.EqualityFilter[ef];
                    if (filterValue) {
                        if (quickFilter.options.lookupKey) {
                            let lookup = Q.getLookup(quickFilter.options.lookupKey);
                            request.EqualityFilterWithTextValue[quickFilter.title] = lookup.itemById[filterValue][lookup.textField];

                        } else if (quickFilter.options.enumKey) {
                            let enumKey = quickFilter.options.enumKey;
                            let enumValue = Q.toId(filterValue);
                            request.EqualityFilterWithTextValue[quickFilter.title] = Serenity.EnumFormatter.format(Serenity.EnumTypeRegistry.get(enumKey), enumValue);
                        }
                        else {
                            request.EqualityFilterWithTextValue[quickFilter.title] = filterValue;
                        }
                    }
                }
            }
            return request;
        }

**Comment by volkanceylan** [comment]
You could access text by (this.filterBar as any).$store.$displayText, not pretty though
