### ISSUE TITLE
Not able to debug

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2325]
When I put a break point on OrderEndpoint.cs Retrieve method and step through the code, I get this error. I don't have a C:\Sandbox folder so I am not sure why it is looking there. I am using VS2017CE on Win10. 
```
ServiceEndpoint.cs not Found
...
Locating source for 'C:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs'. (No checksum.)
The file 'C:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs' does not exist.
Looking in script documents for 'C:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs'...
Looking in the projects for 'C:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs'.
The file was not found in a project.
Looking for source using source server...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: C:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs.
The debugger could not locate the source file 'C:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs'.
```

**Comment by volkanceylan** [comment]
You can't step into Serenity source code, as you don't have it, just like you can't step into .NET source code. If you need to step into that, you'll need to add Serenity as submodule, or enable source server as explained in Serenity Blog

http://serenity.is/blog/2016/12/18/debugging-serenity-libraries

**Comment by VR-Architect** [comment]
I already followed those instructions when I set it up a few weeks ago and it was working fine. I guess one of the two last VS2017 patches changed the behavior or broke. I don't have this issue on VS2015 though.  I will follow the instructions for the SubModule approach. Thanks for the help.
