### ISSUE TITLE
Is it a bug or my code error

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2327]
Hi Serenity users

I am trying to change dialog height and with also caption width. When I open the dialog directly it works fine and less is applied but when I call it from inside master form it down work. 
Is there a problem with my less code?
`.s-Campaign-DailyVaccinationsDialog {
    > .size {
        width: 450px;
    }

    .caption {
        width: 250px;
        text-align: left;
    }
}`
the above works fine. 

the following is the main dialog, when i call this form and then call the DailyVaccinationsDialog the size does not change.

`.s-Campaign-CampaignDayDialog {
    > .size {
        width: 650px;
    }

    .caption {
        width: 150px;
    }

    .s-DailyVaccinationsDialog {
        > .size {
            width: 450px;
        }

        .caption {
            width: 250px;
            text-align: left;
        }
    }
}`

**Comment by volkanceylan** [comment]
Your dialogs are not under each other, so don't put their CSS rules under each other.
