### ISSUE TITLE
HtmlContentEditor image not display and upload image on server

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#2328]
I used HtmlContentEditor for saving Html questions but image not display in HtmlContentEditor when i add image in question. I also want to upload that image on specific folder on server. Please help me how to display image in HtmlContentEditor and upload image on server. Another is i display that html question in custom MVC page same image display from server path. How to do?

**Comment by volkanceylan** [comment]
Sorry, no such feature, check out CKEditor docs and plugins.
