### ISSUE TITLE
BooleanField in SqlQuery

### ISSUE THREAD

**Issue by psigma** [volkanceylan/Serenity#2329]
May be, I have the same problem, as https://github.com/volkanceylan/Serenity/issues/1356, not sure.

Some field declared as Boolean in Row and when I try to use it in Connection.Query<Row>.Where(new SqlQuery(...)) clause, I'v got mismatch.

I think, this happens because no operator in BaseCriteria which accept bool, e.g. 
`public static BaseCriteria operator ==(BaseCriteria criteria1, **bool** value);`

And for now you should convert it to int

**Comment by PanChenhao** [comment]
maybe you can try with IsNULL IsNotNull

.where(yourBooleanfield.IsNull())

**Comment by volkanceylan** [comment]
You can use fld.Something == 1

It is because there is no boolean type in SQL server.

**Comment by GreenUtil** [comment]
When I use fld.Something == 1  then I get : 

![image](https://user-images.githubusercontent.com/2122311/33288712-7f99ebb2-d3bd-11e7-9cee-6290423fbf61.png)

**Comment by GreenUtil** [comment]
When I use  fld.Something == 1,  I get : 

![image](https://user-images.githubusercontent.com/2122311/33312989-be5d9ae4-d429-11e7-853b-36350ce56574.png)

**Comment by edwardch** [comment]
Have you tried:
`.Where(new Criteria(fld.Something) == 1)`

**Comment by fabio-basedev** [comment]
Hi,
I had the same problem and I resolved with ".Where(new criteria(fld. Something)"
And if you want to test false value, use ".Where(!(New Criteria (fld. Something)))"
