### ISSUE TITLE
One to one connection (new tab)

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#233]
"Serenity book" hasn't got any examples how to do <b><i>one to one</i></b> connection. </br></br>Examples: </br>1) When i click <b>UsersDetailsTab</b> from <b>UserForm</b>, I want to see <b>UserDetailForm</b> with <b>buttons</b>, not <b>UserDetailColumn</b>. </br>2) When i click <b>UserForm</b> i should also see <b>UserDetailsForm</b> at the bottom in that form, and be able to modify it </br></br>Any ideas, examples, sample codes please
Thanks

**Comment by BolatovAlau** [comment]
Is it possible to show Dialog in new tab not grid ?

**Comment by volkanceylan** [comment]
Why don't you show a new dialog for details? I don't have such a sample yet, though its possible by adding a dialog template, putting a PropertyGrid in a new tab, loading an entity from retrieve service into that property dialog, adding a toolbar with save buttons etc.

**Comment by volkanceylan** [comment]
Add a [Panel] attribute to dialog, move your dialog into tab after dialog is created, i'm not sure if it will be useful

**Comment by BolatovAlau** [comment]
This is UsersDialog
```
namespace Serene.Users
{
    using Serenity;

    [IdProperty(UsersRow.IdProperty), NameProperty(UsersRow.NameProperty)]
    [FormKey(UsersForm.FormKey), LocalTextPrefix(UsersRow.LocalTextPrefix), Service(UsersService.BaseUrl)]
    public class UsersDialog : EntityDialog<UsersRow>
    {
        private UserDetailsDialog UserDetailsDialog;

        public UsersDialog()
        {
            UserDetailsDialog = new UserDetailsDialog();
            tabs.OnActivate += (e, i) => Arrange();
        }

        protected override void AfterLoadEntity()
        {
            base.AfterLoadEntity();
            UserDetailsDialog.UserId = (int?)EntityId;
        }
    }
}
```
This is UserDetailsDialog I added PanelAttribute
```
namespace Serene.Users
{
    using Serenity;

    [IdProperty(UserDetailsRow.IdProperty), NameProperty(UserDetailsRow.NameProperty)]
    [FormKey("Users.UserDetails"), LocalTextPrefix(UserDetailsRow.LocalTextPrefix), Service(UserDetailsService.BaseUrl)]
    [Panel]
    public class UserDetailsDialog : EntityDialog<UserDetailsRow>
    {
        protected UserDetailsForm form;

        public UserDetailsDialog()
        {
            form = new UserDetailsForm(IdPrefix);
        }

        private int? UserId;
        public int? UserId
        {
            get { return UserId; }
            set { UserId = value; }
        }
    }
}
```
And This Is UserTemplate
```
<div id="~_Tabs" class="s-DialogContent">
    <ul>
        <li><a href="#~_TabInfo"><span>Event</span></a></li>
        <li><a href="#~_TabEventDetails"><span>EventDetails</span></a></li>
    </ul>
    <div id="~_TabInfo" class="tab-pane s-TabInfo">
        <div id="~_Toolbar" class="s-DialogToolbar">
        </div>
        <div class="s-Form">
            <form id="~_Form" action="">
                <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                    <div id="~_PropertyGrid"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>
    <div id="~_TabEventDetails" class="tab-pane s-TabEventDetails">
        <div id="~_EventDetailsDialog">
        </div>
    </div>
</div>
```

When i run app Only UserForm appears. What is wrong?

**Comment by volkanceylan** [comment]
userDetailsDialog.AppendTo(this.ById("EventDetailsDialog")

Also, instead of UserDetailsDialog.UserId = (int?)EntityId;

this.userDetailsDialog.LoadById(this.EntityId);

**Comment by BolatovAlau** [comment]
Two problems 
1) There is no method "AppendTo" in EventsDialog class instead i used `userDetailsDialog.ById(EntityId+"");`
2) LoadById method must have 2 arguments LoadById(long, Action<RetrieveResponse<UserDetailsRow>>)

**Comment by volkanceylan** [comment]
userDetailsDialog.Element.AppendTo
Just pass an empty delegate

**Comment by BolatovAlau** [comment]
Thanks it works ))

**Comment by BolatovAlau** [comment]
It works fine but have some errors.
If the data in UserDetailTable doesn't exist i get new Exception. I think that I should check if the Data in UserDetailTable exsist from ClientSide, and add or delete buttons for two possible сase (data exsist or not).

**Comment by BolatovAlau** [comment]
And, `LoadById((long)EntityId, delegate { });` deactivate default functionalities for UserForm

**Comment by BolatovAlau** [comment]
I think i should add if, else to check if it is update or create in UserEntityDialog

**Comment by volkanceylan** [comment]
You should bring in some field from UserDetail to be sure it exist. If doesnt, load an empty entity but with userid filled in to detail dialog, otherwise loadbyid.
