### ISSUE TITLE
Composite Primary key

### ISSUE THREAD

**Issue by xglobe** [volkanceylan/Serenity#2330]
I use composite primary keys like this: 

`this.Create.Table("ProcessFlow")
                .WithColumn("ProductId").AsInt32().PrimaryKey().ForeignKey("Fk_StepLog_Product", "Product", "ProductId")
                .WithColumn("PanelId").AsInt32().PrimaryKey().ForeignKey("FK_StepLog_Panel", "Panel", "PanelId")
                .WithColumn("CPNumber").AsString().PrimaryKey();`

When I try to load the webpage I get error:

> uncaught exception: Each data element must implement a unique 'ProductId' property. Object at index '0' has repeated identity value '2'

How can I handle this problem?

**Comment by wldkrd1** [comment]
Add an identity column to the table. Doesn't have to be a primary key, you can keep the composite key as primary.

**Comment by xglobe** [comment]
Thank you!
