### ISSUE TITLE
Focus on HtmlNoteContentEditor automatically

### ISSUE THREAD

**Issue by jmann45** [volkanceylan/Serenity#2331]
I've been trying to automatically set the focus to the CKEditor when adding a new new note using the HthmlNoteContentEdtior (like as seen with Edit Customer --> Notes --> Add Note) and have not been able to figure it out.  Just looking to click the "Add Note" button then start typing without having to click in the editor first.  I've tried putting various .focus() lines in the onDialogOpen and initDialog methods, but none seem to have any effect.  Any ideas on how to achieve this?

**Comment by volkanceylan** [comment]
You probably need to attach CKEditor instanceReady event as iframe is not initialized yet when dialog is opened.
