### ISSUE TITLE
multiple lookup editors of same entity with out foreign key in different fields

### ISSUE THREAD

**Issue by naveenare** [volkanceylan/Serenity#2332]
in issues #106 
can we do the same thing with out using foreign key(joining  the tables)

**Comment by sayuga** [comment]
how do you expect to have the fields match back to a foreign table without a foreign key?

**Comment by ShahzanSyed** [comment]
Hello @naveenare,
Did you implement the Lookup without a Foreign Key? I, too have a similar situation. Would appreciate your help on this.
