### ISSUE TITLE
Different forms on same table

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2335]
Hello Volkan,
If I have table called Contracts and I want to create 3 different forms for this table with different conditions:

1. First form will have open tender contracts
2. Second form will have restricted tender contracts
3. Third form will have sole source contracts

How will I do this?

**Comment by ms4hafiz** [comment]
I also need similar functionality. What I want is to be able to create different forms based on the available column of data. I have table for example like following:
Day 1: target, vaccined, not vacinated, vials used
Day 2: vaccinated, not vaccinated, vials used. 

The table is not normalized but I need to make it in one table. 

So I need two forms while the data is on the same table.

Anyone has any idea.

**Comment by sayuga** [comment]
Create the three dialog templates in the 3 formats you want them and then call them using the _namespace_.xyzDialog().loadNewAndOpenDialog() on a custom button. 

You can create any form using the the Dialog.ts and Form.cs files. Look at the PopulateLinkedData sample. that is a custom Form for a existing grid.
