### ISSUE TITLE
2 Forms in separate tabs demo

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2336]
Hello I am having problems working implementing this feature.  I followed the demo.  I followed the instructions to a T.    Everything works great including save and update.  The only issue I have is the secondary form tab wont populate the initial values from the database.  What can I be missing.  I can post code if needed.  I just couldnt figure what code loads the fields in the secondary form.  The first form loads correctly.

**Comment by Magik3a** [comment]
You can use this in your dialog
```

 loadEntity(entity: YourEntityRow) {
            super.loadEntity(entity);

 if (this.isNewOrDeleted()) {
                // no entity is selected, just load an empty entity
                this.patientHealthGrid.load({});
                return;
            }

   YourSecondTabEntityService.Retrieve({
                EntityId: entity.YourSecondTabEntityID
            }, response => {
                this.YourSecondTabEntityGrid.load(response.Entity);
            });
}
```

But i cant still figure out how to ask for saving if changes are made to the other tabs :(

**Comment by mcb2323** [comment]
Worked like a charm thanks
