### ISSUE TITLE
DateTime Quickfilter and SQL Server Issue

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#2337]
I have DateTime field in a Table. I am storing Indian Standard Time ( UTC + 05:30 ) in dateTime field.
My server is located in US where Time zone is UTC - 08:00.
When i am using quickfilter on this DateTime field, data fetched from database is + 8 hours then the quickfilter time for e.g. if i select Date time as 28/05/2017 17:00 then data shows after 29/05/2017 01:00 which is 8 hours forward then the required one. To get data starting from 17:00 i need to change quickfilter to 09:00.
I converted the Date time to UTC in database, but still i am getting same data.
Whether is it possible to change quick filter before querying to database.
i.e. when user change quickfilter then i will subtract 8 hours from its value and then pass it to application,
or any other way is available for this.
regards
Shailesh

**Comment by volkanceylan** [comment]
Add [DateTimeKind(DateTimeKind.Utc)] to field
