### ISSUE TITLE
how to hide samples

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2338]
I would like to hide samples instead of removing them. How is it possible?

**Comment by ninoraccoon** [comment]
yes, instruccion here https://volkanceylan.gitbooks.io/serenity-guide/content/howto/removing_northwind.html

**Comment by ms4hafiz** [comment]
thanks

**Comment by sayuga** [comment]
If you remove the navigation entry, then they wont display on the menu but will still exist in the background.

**Comment by ms4hafiz** [comment]
thanks
