### ISSUE TITLE
Serene + WebService

### ISSUE THREAD

**Issue by ninoraccoon** [volkanceylan/Serenity#2339]
Hello, I want know if is possible that in the same instance of serene project cant publish web service to be consumed fromother client using of course de same serene architecture?

**Comment by ninoraccoon** [comment]
I mean, serve json form sereve service  an proceses reques, make a rest api form serene...

**Comment by sayuga** [comment]
See issue #806, #971 and  #1734

**Comment by ninoraccoon** [comment]
thanks...
