### ISSUE TITLE
How to override "DeleteConfirmation" text?

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#234]
Is it possible to change the "DeleteConfirmation" text for one particular dialog?

**Comment by VictorTomaili** [comment]
Serenity use localization texts. [Like this one](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Web/Includes/Scripts/serenity/texts/serenity.texts.tr.json#L7). You can override what you want

**Comment by brettbeard** [comment]
Wouldn't change the confirmation text for every dialog?  I only to change for one dialog.

**Comment by volkanceylan** [comment]
```cs
protected override List<ToolButton> GetToolbarButtons()
{
    var buttons = base.GetToolbarButtons();
    buttons.First(x => x.CssClass == "delete-button").OnClick =  () =>
               Q.Confirm("MyConfirmation", () => 
                     this.DoDelete(() => self.element.Dialog().Close());
}
```

**Comment by brettbeard** [comment]
Sorry to keep bothering you with this but I'm getting some compile errors and not sure how to fix them.

![gettoolbarbuttons](https://cloud.githubusercontent.com/assets/8460261/12957210/8a65d854-cff9-11e5-9708-f5d6ec132185.jpg)

**Comment by VictorTomaili** [comment]
you need self variable. 

```csharp
var self = this;
buttons.First(... self.element.Dialog().Close());
...
```

**Comment by volkanceylan** [comment]
If you looked at the code, you'd see i modified it before you wrote again

**Comment by brettbeard** [comment]
Couldn't posted code to compile so went with this:

`protected override List<ToolButton> GetToolbarButtons()
        {
            var self = this;

            var buttons = base.GetToolbarButtons();

            buttons.First(x => x.CssClass == "delete-button").OnClick = delegate
            {
                Q.Confirm("Unique confirmation", delegate
                {
                    self.DoDelete(delegate
                    {
                        self.element.Dialog().Close();
                    });
                });
            };

            return buttons;
        }`

**Comment by stixoffire** [comment]
Just in case someone else finds this thread and wants the code.

```
        protected getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            var entityName = this.currentEntity.Name;

            Q.tryFirst(buttons, x => x.cssClass == "delete-button").onClick = () =>
                Q.confirm("Delete Position: " + entityName + "?", () =>
                    this.doDelete(() => this.element.dialog('close')));
            return buttons;

        }
```
