### ISSUE TITLE
CORE Beta: SignalR Error when creating hubs

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#2340]
HI, whatever i say, we all know this project is pretty cool, so i will get directly to the question:

I am using core beta serenity with signalR, the problem is when i add new HUB in web project under hubs folder i get error after building on generating servertypings. you can see the error here 

`Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Serenity.CodeGeneration.ServerImportGeneratorBase.GenerateAll()
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll()
   at Serenity.CodeGenerator.ServerTypingsCommand.Run(String csproj, List`1 tsTypes)
   at Serenity.CodeGenerator.Program.Main(String[] args)`

After i comment the hub everything is working fine
![image](https://cloud.githubusercontent.com/assets/10474555/26558933/f714de88-44b4-11e7-82eb-32cacc44c8f3.png)

**Comment by volkanceylan** [comment]
I'm not sure if SignalR supports .NET Core, but this error looks like one of the assemblies doesn't like to list its types.

**Comment by Magik3a** [comment]
Here is the link for signalr server: [click]( https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR.Server)

After this error i have really big problems with generating server typings and so far if i make changes, i have to change the servertypings by hand to. 
Next few days i will find time to dig deep in to this problem because the frustration is enormous

**Comment by Magik3a** [comment]
Yep its exactly from the signalr hub... Is there a safe folder that command dotnet sergen t dosn't check?
