### ISSUE TITLE
Show hide inline checkbox based on value of another column in same row.

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2341]
Any ideas on this as Im having issues getting this to work.  I figured I can set the visibility property but I dont know when this should go.  I was thinking of putting it in getColumns but I dont think I have access to cell values.  Any ideas?

**Comment by mcb2323** [comment]
basically if  column 1 == 2 show checkbox else hide.

**Comment by Estrusco** [comment]
In afterLoadEntity() of your xyzDialog.ts

```cs
    protected afterLoadEntity() {
        super.afterLoadEntity();

        if (this.entity.YourFlag == 1)
            this.form.xyzYourField.element.toggle();
    }
```
