### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2344]
Hello Volkan,
In my application, every user belongs to an agency so on the user form, one can select an agency for the user when creating the user. The problem is that, users who have Agency permissions but do not have User Administration permissions cannot view the list of agencies in the agency grid. It keeps showing the error : _**"Authorization has been denied for this request"**_

Below are the AgencyRow and UserRow codes

**AGENCYROW**

namespace ppa.MasterData.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), TableName("[ppa2013sql].[New_Agency_Table]"), DisplayName("Agency"), InstanceName("Agency"), TwoLevelCached]
    //[ReadPermission("Administration:General", MasterData.PermissionKeys.Agency.View)]
    //[ModifyPermission("Administration:General")]
    [ReadPermission(MasterData.PermissionKeys.Agency.View)]
    [InsertPermission(MasterData.PermissionKeys.Agency.Add)]
    [UpdatePermission(MasterData.PermissionKeys.Agency.Edit)]
    [DeletePermission(MasterData.PermissionKeys.Agency.Delete)]
    [LookupScript("MasterData.Agency")]
    public sealed class AgencyRow : Row, IIdRow, INameRow
    {
        [DisplayName("Agency Id"), Column("ppa_agency_id"), Identity]
        public Int32? AgencyId
        {
            get { return Fields.AgencyId[this]; }
            set { Fields.AgencyId[this] = value; }
        }

        [DisplayName("Agency Name"), Column("ppa_agency_name"), Size(255), QuickSearch]
        public String AgencyName
        {
            get { return Fields.AgencyName[this]; }
            set { Fields.AgencyName[this] = value; }
        }

        [DisplayName("Ag Type"), Column("ppa_ag_type"), ForeignKey("[ppa2013sql].[New_Agency_Type]", "ag_type_id"), LeftJoin("jAgType"), TextualField("AgTypeTypeName"), LookupInclude]
        [LookupEditor(typeof(AgencyTypeRow), InplaceAdd = true)]
        public Int32? AgType
        {
            get { return Fields.AgType[this]; }
            set { Fields.AgType[this] = value; }
        }

        [DisplayName("Ag Type Type Name"), Expression("jAgType.[ag_type_name]")]
        public String AgTypeTypeName
        {
            get { return Fields.AgTypeTypeName[this]; }
            set { Fields.AgTypeTypeName[this] = value; }
        }

        [MasterDetailRelation(foreignKey: "agency", IncludeColumns = "PositionName,PositionTypeName,RegionName,DistrictDisName")]
        [DisplayName("Tender Committee"), NotMapped]
        public List<TenderCommitteeRow> MemberList
        {
            get { return Fields.MemberList[this]; }
            set { Fields.MemberList[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.AgencyId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.AgencyName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public AgencyRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field AgencyId;
            public StringField AgencyName;
            public Int32Field AgType;

            public StringField AgTypeTypeName;
            public readonly RowListField<TenderCommitteeRow> MemberList;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "MasterData.Agency";
            }
        }
    }
}

**USERROW** 

namespace ppa.Administration.Entities
{
    using ppa.MasterData.Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;

    [ConnectionKey("Default"), DisplayName("Users"), InstanceName("User"), TwoLevelCached]
    [ReadPermission(PermissionKeys.Security)]
    [ModifyPermission(PermissionKeys.Security)]
    [LookupScript("Administration.User", Permission = PermissionKeys.Security)]
    public sealed class UserRow : LoggingRow, IIdRow, INameRow, IIsActiveRow
    {
        [DisplayName("User Id"), Identity]
        public Int32? UserId
        {
            get { return Fields.UserId[this]; }
            set { Fields.UserId[this] = value; }
        }

        [DisplayName("Username"), Size(100), NotNull, QuickSearch, LookupInclude]
        public String Username
        {
            get { return Fields.Username[this]; }
            set { Fields.Username[this] = value; }
        }

        [DisplayName("Source"), Size(4), NotNull, Insertable(false), Updatable(false), DefaultValue("site")]
        public String Source
        {
            get { return Fields.Source[this]; }
            set { Fields.Source[this] = value; }
        }

        [DisplayName("Password Hash"), Size(86), NotNull, Insertable(false), Updatable(false), MinSelectLevel(SelectLevel.Never)]
        public String PasswordHash
        {
            get { return Fields.PasswordHash[this]; }
            set { Fields.PasswordHash[this] = value; }
        }

        [DisplayName("Password Salt"), Size(10), NotNull, Insertable(false), Updatable(false), MinSelectLevel(SelectLevel.Never)]
        public String PasswordSalt
        {
            get { return Fields.PasswordSalt[this]; }
            set { Fields.PasswordSalt[this] = value; }
        }

        [DisplayName("Display Name"), Size(100), NotNull, LookupInclude]
        public String DisplayName
        {
            get { return Fields.DisplayName[this]; }
            set { Fields.DisplayName[this] = value; }
        }

        [DisplayName("Email"), Size(100)]
        public String Email
        {
            get { return Fields.Email[this]; }
            set { Fields.Email[this] = value; }
        }

        [DisplayName("User Image"), Size(100)]
        [ImageUploadEditor(FilenameFormat = "UserImage/~", CopyToHistory = true)]
        public String UserImage
        {
            get { return Fields.UserImage[this]; }
            set { Fields.UserImage[this] = value; }
        }

        [DisplayName("Password"), Size(50), NotMapped]
        public String Password
        {
            get { return Fields.Password[this]; }
            set { Fields.Password[this] = value; }
        }

        [NotNull, Insertable(false), Updatable(true)]
        public Int16? IsActive
        {
            get { return Fields.IsActive[this]; }
            set { Fields.IsActive[this] = value; }
        }

        [DisplayName("Confirm Password"), Size(50), NotMapped]
        public String PasswordConfirm
        {
            get { return Fields.PasswordConfirm[this]; }
            set { Fields.PasswordConfirm[this] = value; }
        }

        [DisplayName("Last Directory Update"), Insertable(false), Updatable(false)]
        public DateTime? LastDirectoryUpdate
        {
            get { return Fields.LastDirectoryUpdate[this]; }
            set { Fields.LastDirectoryUpdate[this] = value; }
        }

        [DisplayName("Agency"), ForeignKey("[ppa2013sql].[New_Agency_Table]", "ppa_agency_id"), LeftJoin("jNewAgency"), TextualField("Agency Name")]
        [LookupEditor(typeof(AgencyRow), InplaceAdd = true)]
        public Int32? UserAgency
        {
            get { return Fields.UserAgency[this]; }
            set { Fields.UserAgency[this] = value; }
        }

        [DisplayName("Agency Name"), Expression("jNewAgency.[ppa_agency_name]")]
        public String AgencyName
        {
            get { return Fields.AgencyName[this]; }
            set { Fields.AgencyName[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.UserId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Username; }
        }

        Int16Field IIsActiveRow.IsActiveField
        {
            get { return Fields.IsActive; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public UserRow()
            : base(Fields)
        {
        }

        public class RowFields : LoggingRowFields
        {
            public Int32Field UserId;
            public StringField Username;
            public StringField Source;
            public StringField PasswordHash;
            public StringField PasswordSalt;
            public StringField DisplayName;
            public StringField Email;
            public StringField UserImage;
            public DateTimeField LastDirectoryUpdate;
            public Int16Field IsActive;

            public StringField Password;
            public StringField PasswordConfirm;

            public readonly Int32Field UserAgency;
            public readonly StringField AgencyName;

            public RowFields()
                : base("Users")
            {
                LocalTextPrefix = "Administration.User";
            }
        }
    }
}

**Comment by Zahar661** [comment]
TenderCommitteeRow available User?

**Comment by gfo2007** [comment]
Please I don't get you.

**Comment by Zahar661** [comment]
oops. TenderCommitteeRow have permission User?
