### ISSUE TITLE
How to embeded Senerity security authentication into mobility apps? 

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#2345]
Dear @Estrusco, 

I want to make a mobility app and mirgrated user authentication of PC-side into it as below. How can I implement it? Thanks to advise that.

Below is some code from AccountPage.cs 
[
     if (string.IsNullOrEmpty(request.Username))
           throw new ArgumentNullException("username");
     var username = request.Username;

     if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
            return new ServiceResponse();
]

Thanks,
Harry

**Comment by harrypassport** [comment]
Because I want to use the same user table for authentication in mobility app as in PC-side. So is there anyone can give me hands. How can I get the details for the below function(SiteMembershipProvider.ComputeSHA512(password + salt);)? 

public static string CalculateHash(string password, string salt)
        {
            return SiteMembershipProvider.ComputeSHA512(password + salt);
        }


Many thanks.
Harry

**Comment by volkanceylan** [comment]
See my Gists for Android sample.

**Comment by PanChenhao** [comment]
Dear,

how to see your gists? I don't know how to open your gists? could you please give any hints? thanks very much @volkanceylan
