### ISSUE TITLE
batch edit rows

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2347]
Hi! 2 days I can't think of how to implement a button for the grid. when you click on that the following logic:

_update myTable set [date]=getdate() where [date]<getdate() and [fact]=0_

therefore you need to handle multiple rows. Does anyone have thoughts on this?

**Comment by wldkrd1** [comment]
Add a button in getButtons()

```
protected getButtons() {
            let buttons = super.getButtons();
                    buttons.push({
                        title: 'Save',
                        cssClass: 'apply-changes-button disabled',
                        onClick: e => this.saveClick(),
                        separator: true
                    });
            return buttons;
}
```

add a function saveClick()

```
private saveClick() {
            var current = -1;
            var self = this;
            Q.serviceRequest('PathToService/Method', {}, (response) => {
                //notify success with a toastr?
                super.refresh();
            });
        }
```

and add method on your service which executes your SQL statement.

**Comment by Zahar661** [comment]
I lol((( written in the service method UpdateDate. now it is necessary to describe the Repository and Endpoint, Endpoint a reference to the Repository, and the Repository need to describe the logic
 _update myTable set [date]=getdate() where [date]<getdate() and [fact]=0_. 
Here the problem is that SqlQuery has no Update, only Select(((

**Comment by wldkrd1** [comment]
```
var cmd = Connection.CreateCommand(sqlStatement);
var result = cmd.ExecuteNonQuery();
```

**Comment by Zahar661** [comment]
Grid.ts
.........
buttons.push({
                title: 'Перенести просроченные',
                cssClass: 'change-date-button',
                onClick: () => this.multiEdit() 
            });
........
        private multiEdit() {
            Q.serviceRequest(PayService.baseUrl + '/PayToDate', {}, (response) => {
                super.refresh();
            });
        }
-------------------------------------------------------------------------------------------------------------------

....Endpoint.cs
public String PayToDate(IDbConnection connection)
        {
            var cmd = connection.CreateCommand();
            cmd.CommandText = "UPDATE [Pay] set [Date]=getdate() where [Date]< getdate() and Fact=0";
            connection.Open();
            var result = cmd.ExecuteNonQuery();
            connection.Close();
            return "Ok";
        }

**Comment by jmace** [comment]
@Zahar661 , Can you expand on this example by passing a variable from the typescript into the endpoint?

**Comment by Zahar661** [comment]
@jmace probably will not be able to help. What's the message?
