### ISSUE TITLE
Range validation not working

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2348]
I am setting a range validation in myRow but it is not working. I would like to limit it between 0 and 1000.
How and where to do it.

thanks

**Comment by Estrusco** [comment]
Range validation in what field? Is an integer? In your form set

[IntegerEditor(MinValue = 0, MaxValue = 1000)]

over the field

**Comment by ms4hafiz** [comment]
Thanks. @Estrusco  that is what I needed.
