### ISSUE TITLE
How to use Undelete function

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2349]
Why i try to undelete, it comes out a error information, 'The method or operation is not implemented'
I have add below code in XYZEndpointes.cs and XYZRepository.cs
```
[HttpPost, AuthorizeDelete(typeof(MyRow))]
        public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request)
        {
            return new MyRepository().Undelete(uow, request);
        }
```
```
  public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request)
        {
            return new MyUndeleteHandler().Process(uow, request);
        }
....
private class MyUndeleteHandler : UndeleteRequestHandler<MyRow> { }

```

What's the problem?

**Comment by sayuga** [comment]
undelete needs a few things. 

* Row.cs needs to have isActiveDeleteRow, IsActiveRow set to the class, 
* The table should have and IsActive Field
* Repository and Endpoint must have a Undelete Handler. 

If memory serves me right, I believe the UserRow uses a similar feature already in place. Look at the User module and look at it's LoggingRow

**Comment by PanChenhao** [comment]
Yes, thank you for your answer. after i add isActiveDeleteRow to XYZRow class. it is runing successfull.

And with your guiding, i find there is a LoggingRow which i just need it.

Thank you very much.
