### ISSUE TITLE
Loglama Nasil Çalışıyor ? 

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#235]
Merhaba Volkan,

Loglama nasıl calısıyor. Kayıt ekleme ve son guncelleyen tutuluyor bılıyorum. Bunun dısında bir loglama var mı ? Mesela Serenity'nin içinde, xxx user'ı neler yapmıs diye bakmak istersem, ne yöntem önerirsin ? 

Teşekkür ederim.

**Comment by VictorTomaili** [comment]
Ben olsam Behavior oluşturup tüm servislerde işlem yapılınca belli alanları tabloya kaydettirirdim.

**Comment by volkanceylan** [comment]
CaptureLog var, ona bakın o daha detaylı, Product ya da Customer row üzerindeydi

**Comment by VictorTomaili** [comment]
Ahahah :smile: [hazırı varmış](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Services/RequestHandlers/IntegratedFeatures/CaptureLog/CaptureLogBehavior.cs)

**Comment by Olricz** [comment]
Ben de gördüğümü hatırlıyorum. O yüzden sordum. Volkan boşluk bırakmamış valla. :) 
Bu urunlerdeki calısıyor mu, ya da ne yapınca calısıyor ? Incelemeye devam edıyorum gerçi...

**Comment by Olricz** [comment]
Bu hangi durumda product'ı logluyor ?

**Comment by volkanceylan** [comment]
Her durumda (insert/update/delete)

**Comment by volkanceylan** [comment]
Tabi repository üzerinden işlem yapılmışsa

**Comment by Olricz** [comment]
Baska verıtabanına bakıyormusum. pardon. tesekkurler. Bu konuda guzel olmus. eline saglık.
