### ISSUE TITLE
How to use localText in Placehold attribution

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2350]
I want to make it two languages that can be chose by user, for the placeholder content.
But i got error if i write as below. Error info is 'An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type'
```
 [DisplayName("Sales Desc"), Size(250),Placeholder(Texts.Db.Product.ProdcutTemp.SalesDescription)]
        [TextAreaEditor]
        public String SalesDesc
        {
            get { return Fields.SalesDesc[this]; }
            set { Fields.SalesDesc[this] = value; }
        }
```

Could anyone help me?

**Comment by volkanceylan** [comment]
Placeholder("Db.Product.ProdcutTemp.SalesDescription")
