### ISSUE TITLE
Filling a textbox from dropdown

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2351]
Hi;

I am trying to fill two textboxes DateFrom and DateTo after picking the value from a lookup. The DateFrom and DateTo exist in the lookup table but not in the table I want to enter. However, i want to just show them in the form.

I have added the following code in xxDialog.ts:
`        
protected form: PcmForm;

        constructor() {
            super();

            this.form = new PcmForm(this.idPrefix);

            this.form.RoundId.changeSelect2(e => {
                var roudID = Q.toId(this.form.RoundId.value);
                if (roudID != null) {
                    this.form.DateFrom.value = PremiumSamples.Lookup.RoundRow.getLookup().itemById[roudID].DateFrom;
                    this.form.DateTo.value = PremiumSamples.Lookup.RoundRow.getLookup().itemById[roudID].DateTo;

                }
            });
        }`
and also added the DateFrom and DateTo variables in the xxForm.ts and have specified as Serenity.DateEditor

`        DateFrom: Serenity.DateEditor;
        DateTo: Serenity.DateEditor;`

and ` ['DateFrom', () => Serenity.DateEditor], ['DateTo', () => Serenity.DateEditor]`

But when I run this, it gives the following script error:

![image](https://cloud.githubusercontent.com/assets/20435849/26690209/b2b995fc-470d-11e7-84fa-294b354cac36.png)

Am I missing anything?

**Comment by sayuga** [comment]
Since it sounds like you are trying to populate data that exists and is linked to that form, I'd say you want to look at the PopulateLinkedDataDialog Sample. Additionally, your call doesn't need the Q.toId(), not to mention that you should simplify your code a bit. Here is a quick rewrite using the Populate Linked Data sample as a base. You may still need to edit it some. 

constructor() {
            super();
            this.form.RoundId.changeSelect2(e => {
                var roundId = this.form.RoundId.value;
                if (Q.isEmptyOrNull(roundId )) {
                    this.setDateDetails({});
                    return;
                }
                var id = Q.first(Northwind.CustomerRow.getLookup().items, x => x.RoundId == roundID).ID;

                PremiumSamples.Lookup.RoundService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setDateDetails(response.Entity);
                });
            });
        }

        private setDateDetails(details: PremiumSamples.Lookup.Roundrow) {
            this.form.DateFrom.value = details.DateFrom;
            this.form.DateTo.value = details.DateTo;
        }

**Comment by ms4hafiz** [comment]
Same error even after applying this.
`_error
:
Error at new Exception$ (http://localhost:58993/Scripts/saltarelle/mscorlib.js?v=AO_L_1E_BHK8K8k5pu8Fmg2:3218:16) at http://localhost:58993/Scripts/serenity/Serenity.Script.UI.js?v=6fXOtbJRCJlqG560c8Uo6g2:4320:11 at PcmForm.w (http://localhost:58993/Scripts/serenity/Serenity.Script.UI.js?v=6fXOtbJRCJlqG560c8Uo6g2:9416:35) at PcmForm.get [as RoundId] (http://localhost:58993/Scripts/Site/PremiumSamples.Web.js?v=G8c4utiZ0hPDTLY2ZWr-5g2:3219:3085) at new PcmDialog (http://localhost:58993/Scripts/Site/PremiumSamples.Web.js?v=G8c4utiZ0hPDTLY2ZWr-5g2:13374:27) at Function.Widget.create (http://localhost:58993/Scripts/serenity/Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:2576:26) at PcmGrid.createEntityDialog (http://localhost:58993/Scripts/serenity/Serenity.Script.UI.js?v=6fXOtbJRCJlqG560c8Uo6g2:8196:33) at PcmGrid.editItem (http://localhost:58993/Scripts/serenity/Serenity.Script.UI.js?v=6fXOtbJRCJlqG560c8Uo6g2:8131:9) at PcmGrid.editItemOfType (http://localhost:58993/Scripts/serenity/Serenity.Script.UI.js?v=6fXOtbJRCJlqG560c8Uo6g2:8144:10) at PcmGrid.onClick (http://localhost:58993/Scripts/serenity/Serenity.Script.UI.js?v=6fXOtbJRCJlqG560c8Uo6g2:5513:10)
_innerException
:
null
_message
:
"Element has no widget of type 'Serenity.IntegerEditor'!"
__proto__
:
Object`

I tried to debug but no success. 
The code is 
`        constructor() {
            super();
            this.form.RoundId.changeSelect2(e => {
                var roundId: number = this.form.RoundId.value;
                if (Q.isEmptyOrNull(roundId)) {
                    this.setDateDetails({});
                    return;
                }
                var id = Q.first(Lookup.RoundRow.getLookup().items, x => x.RoundId == roundId).RoundId;

                PremiumSamples.Lookup.RoundService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setDateDetails(response.Entity);
                });
            });
        }

        private setDateDetails(details: PremiumSamples.Lookup.RoundRow) {
            this.form.DateFrom.value = details.DateFrom;
            this.form.DateTo.value = details.DateTo;
        }`

The RoundId is number does it make a problem?

**Comment by Estrusco** [comment]
In which line of code the script send you this exception?

Try to us Serenity.EditorUtils.getValue(this.form.RoundId) to get value of RoundId.

**Comment by ms4hafiz** [comment]
I found there is a problem with this block of code.

`this.form.RoundId.changeSelect2(e => {
                var roundId = this.form.RoundId.value;
                if (!Q.isValue(roundId)) {
                    this.setDateDetails({});
                    return;
                }
                var id = Q.first(Lookup.RoundRow.getLookup().items, x => x.RoundId == roundId).RoundId;
                //var id = Serenity.EditorUtils.getValue(this.form.RoundId)

                PremiumSamples.Lookup.RoundService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setDateDetails(response.Entity);
                });
            });`
Changed this line from 
   if (Q.isValue(roundId)) {
to 
   if (Q.isEmptyOrNull(roundId)) {

does it make a problem?

**Comment by Estrusco** [comment]
Q.isValue is this:

```ts
ss.isValue = function ss$isValue(o) {
	return (o !== null) && (o !== undefined);
};
```

if you have to test if roundId is different from null and undefined you can use it.

Q.isEmptyOrNull is for string

```ts
function isEmptyOrNull(s) {
        return s == null || s.length === 0;
    }
```

**Comment by ms4hafiz** [comment]
Thank you. I was not able to make it.

Neither worked nor the code you proposed earlier and not the following code.
````           
this.form.RoundId.changeSelect2(e => {

                var roundId = this.form.RoundId.value;

                if (roundId != null) {
                    this.form.DateFrom.value = Lookup.RoundRow.getLookup().itemById[roundId].DateFrom;
                }

**Comment by ms4hafiz** [comment]
The previous error is gone. Now there is another error in this line `var elementType = element.getAttribute('type');` after I select a value from DropDown and it does not populate value to other textboxes (DateFrom and DateTo).

The console error is `Cannot read property 'getAttribute' of null`  or `element is null`.

the code is as following:
```` 
       constructor() {
           super();

            this.form.RoundId.changeSelect2(e => {
                var roundId = this.form.RoundId.value;
                if (roundId !== null || roundId !== undefined) {
                    this.setDateDetails({});
                    return;
                }
                ///var id = Q.first(Lookup.RoundRow.getLookup().items, x => x.RoundId == roundId).RoundId;
                var id = Serenity.EditorUtils.getValue(this.form.RoundId)

                PremiumSamples.Lookup.RoundService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setDateDetails(response.Entity);
                });
            });
        }

        private setDateDetails(details: PremiumSamples.Lookup.RoundRow) {
            this.form.DateFrom.value = details.DateFrom;
            this.form.DateTo.value = details.DateTo;
        }
    }

**Comment by volkanturk** [comment]
I get the same problem myself
help please ?

**Comment by Estrusco** [comment]
The error is in setDateDetails function? Try with

```ts
    PremiumSamples.Lookup.RoundService.Retrieve(
        {
            EntityId: id
        }, 
        response => {
            Serenity.EditorUtils.setValue(this.form.DateFrom, response.Entity.DateFrom);
            Serenity.EditorUtils.setValue(this.form.DateTo, response.Entity.DateTo);
        });
```

**Comment by ms4hafiz** [comment]
![image](https://user-images.githubusercontent.com/20435849/27083999-9db53688-505f-11e7-81d0-7677cebbcbf0.png)
Now this error.

**Comment by Estrusco** [comment]
Probably 'element' is null or not valid, then getAttribute is not a function in element.
You have to debug in console and find why element is not valid.

**Comment by volkanceylan** [comment]
You are modifying the generated files, not Form.cs file. First try fixing that.
