### ISSUE TITLE
how to set first element of select2 jquery as default?

### ISSUE THREAD

**Issue by MBagherii** [volkanceylan/Serenity#2352]
Hi volkanceylan.I am in the middle of project and new to serenity.
I have some dropdown list in my form so I want to show first element of each list  as default value instead of (....select... )text for dropdowns. I see samples but I could not find the answer of my question.please help me.
for example there is a list such as : apple , orange and so on. when dialog open I want to show apple (first element of dropdown list)as default in select2.
how can I do that? and where?
thank you

**Comment by sayuga** [comment]
so you just want to designate a [DefaultValue('')] attribute to form field then?

**Comment by MBagherii** [comment]
yes
I find [DefaultValue(int)] in serenity but it get an integer value so It shows the value of list that have for example ID = 1 and when the element that have this ID removed it does not show anything.

**Comment by sayuga** [comment]
DefaultValue actually has multiple interfaces. It can also take on a string. Look at the UserRow.cs -> Source Field in the sample and you'll see it's set to "site". The reason you loose the reference in the event of the ID is because it's being referenced as an enumeration from the list thus, if it doesn't exist the return value will obviously be null.

**Comment by MBagherii** [comment]
thank you for your answer but my problem does not solve yet. 
my select2 recieve data from a table in sql for example I have a table that have 5 records. I want when a dialog open the default value become first item from that list, if I use from another interfaces for example string , I can not set a string for that because select2 value in my project fill dynamic and I don't know what is the first item of list? 
List = apple , orange , banana , ....
if apple be first default value become apple if orange be first default value become orange

**Comment by gguadalupe** [comment]
What you want is to have the combo pre-selected with the first option of the table (order by the name of the fruit).
I don't have any idea how to do that, but I encourage you to read the guide. for example the Default Values In New Dialog https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts
Combined with Serial Auto Number https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/SerialAutoNumber/SerialAutoNumberDialog.ts
You need to play with the logic of these two examples, to choose the first item of the table and pre-select it, in the correct function.

**THE FOLLOWING CODE IS JUST PSEUDO CODE!** It is just an example to show you how I got 2 different examples and combined in a possible solution.

```
        protected afterLoadEntity() {
            super.afterLoadEntity();
            // fill next number in new record mode
            if (this.isNew())
                this.form.YourFruitComboField = Northwind.FruitRow.getLookup().items.[0].FruitID
        }

```
In the examples you will find so much info that you will be able to graduate as a brain surgeon. true story! Read On!

**Comment by edson** [comment]
```
protected afterLoadEntity() {
       super.afterLoadEntity();

       if (this.isNew()) {
       this.form.YourField.value = this.form.YourField.get_items()[0].id;
       this.form.YourField.element.triggerHandler("change"); //if there is some change handler you've set
    }
 }
```

Best Regards

**Comment by MBagherii** [comment]
@edson : thank you for your help. I tested that and worked fine.
@gguadalupe and @sayuga thank you too for your helps.
