### ISSUE TITLE
Join parent parent table

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2353]
I have three table like following,
Region:
-RegionId
-RegionName

Province:
-ProvinceId
-RegionId
-ProvinceName

District:
-DistrictId
-ProvinceId
-DistrictName

I would like to get RegionName through District. How can I do it?

**Comment by sayuga** [comment]
Read the manual. there is a full run through. 

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

**Comment by ms4hafiz** [comment]
Thank you 

I need it to use and get the RegionName in the districtGrid   but it is not working. 

I used the following in districtRow 

`        [LookupEditor(typeof(Locations.Entities.ProvinceRow), CascadeFrom = "RegionId", CascadeField = "RegionId")]
        [DisplayName("Region"), Expression("jRegion.[RegionNname]")]
        public String RegionName
        {
            get { return Fields.RegionName[this]; }
            set { Fields.RegionName[this] = value; }
        }`

but it gives the following error.

The multipart identifier "jRegion.RegionNname" could not be bound.

**Comment by sayuga** [comment]
You have a typo on the expression attribute. "jRegion.[RegionNname]" should be "jRegion.[RegionName]

**Comment by ms4hafiz** [comment]
Same message even after correcting the typo.

I am attaching the tables relation. I want to get name of Region (Rname) into DistrictGrid.

**Comment by dfaruque** [comment]
give your full row.cs code.

**Comment by ms4hafiz** [comment]
Hi @dfaruque 
Thank you
I am copying the codes one for all three:

# RegionRow.cs
`    [LookupScript("Locations.Region")]`
`    public sealed class RegionRow : Row, IIdRow, INameRow
    {`
`      [DisplayName("Region Id"), Column("RegionID"), Identity]
        public Int16? RegionId
        {
            get { return Fields.RegionId[this]; }
            set { Fields.RegionId[this] = value; }
        }

        [DisplayName("Region"), Size(30), NotNull, QuickSearch]
        public String Rname
        {
            get { return Fields.Rname[this]; }
            set { Fields.Rname[this] = value; }
        }

        [DisplayName("Region Abrv"), Size(5), NotNull]
        public String RAbrv
        {
            get { return Fields.RAbrv[this]; }
            set { Fields.RAbrv[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.RegionId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Rname; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public RegionRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int16Field RegionId;
            public StringField Rname;
            public StringField RAbrv;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Locations.Region";
            }
        }`

# ProvinceRow.cs
`    [LookupScript("Locations.Province")]
    public sealed class ProvinceRow : Row, IIdRow, INameRow
    {
        [DisplayName("Province Id"), Identity]
        public Int16? ProvinceId
        {
            get { return Fields.ProvinceId[this]; }
            set { Fields.ProvinceId[this] = value; }
        }

        [DisplayName("Code"), Size(2), NotNull, QuickSearch]
        public String Pcode
        {
            get { return Fields.Pcode[this]; }
            set { Fields.Pcode[this] = value; }
        }


        [DisplayName("Region"), Column("RegionID"), NotNull, ForeignKey("[dbo].[Region]", "RegionID"), LeftJoin("jRegion"), TextualField("Rname"),LookupInclude]
        [LookupEditor(typeof(Locations.Entities.RegionRow), InplaceAdd = true)]
        public Int16? RegionId
        {
            get { return Fields.RegionId[this]; }
            set { Fields.RegionId[this] = value; }
        }

        [DisplayName("Province"), Size(30), NotNull,LookupInclude,QuickSearch]
        public String Pname
        {
            get { return Fields.Pname[this]; }
            set { Fields.Pname[this] = value; }
        }

        [DisplayName("P Abrv"), Size(5), NotNull]
        public String PAbrv
        {
            get { return Fields.PAbrv[this]; }
            set { Fields.PAbrv[this] = value; }
        }

        [DisplayName("Center"), Size(30), NotNull]
        public String Pcenter
        {
            get { return Fields.Pcenter[this]; }
            set { Fields.Pcenter[this] = value; }
        }

        [DisplayName("Area Km Sqr"), NotNull]
        public Int32? AreaKmSqr
        {
            get { return Fields.AreaKmSqr[this]; }
            set { Fields.AreaKmSqr[this] = value; }
        }

        [DisplayName("No Of districts")]
        public Int32? NoOfDistricts
        {
            get { return Fields.NoOfDistricts[this]; }
            set { Fields.NoOfDistricts[this] = value; }
        }

        [DisplayName("Region"), Expression("jRegion.[Rname]"),LookupInclude]
        public String Rname
        {
            get { return Fields.Rname[this]; }
            set { Fields.Rname[this] = value; }
        }

        [DisplayName("Region R Abrv"), Expression("jRegion.[RAbrv]")]
        public String RegionRAbrv
        {
            get { return Fields.RegionRAbrv[this]; }
            set { Fields.RegionRAbrv[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.ProvinceId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Pname; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public ProvinceRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int16Field ProvinceId;
            public StringField Pcode;
            public Int16Field RegionId;
            public StringField Pname;
            public StringField PAbrv;
            public StringField Pcenter;
            public Int32Field AreaKmSqr;
            public Int32Field NoOfDistricts;

            public StringField Rname;
            public StringField RegionRAbrv;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Locations.Province";
            }
        }
    }`

# DistrictRow.cs
`    [LookupScript("Locations.District")]
    public sealed class DistrictRow : Row, IIdRow, INameRow
    {
        [DisplayName("District Id"), Identity]
        public Int32? DistrictId
        {
            get { return Fields.DistrictId[this]; }
            set { Fields.DistrictId[this] = value; }
        }
       
        [DisplayName("Code"), Size(4), NotNull, QuickSearch]
        public String Dcode
        {
            get { return Fields.Dcode[this]; }
            set { Fields.Dcode[this] = value; }
        }

        [DisplayName("Province"), Column("ProvinceId"), NotNull, ForeignKey("[dbo].[Province]", "ProvinceId"), LeftJoin("jProvince"), TextualField("Pname"),LookupInclude]
        [LookupEditor(typeof(Locations.Entities.ProvinceRow), InplaceAdd = true)]
        public Int16? ProvinceId
        {
            get { return Fields.ProvinceId[this]; }
            set { Fields.ProvinceId[this] = value; }
        }

        [DisplayName("District"), Size(50), NotNull,LookupInclude,QuickSearch]
        public String Dname
        {
            get { return Fields.Dname[this]; }
            set { Fields.Dname[this] = value; }
        }

        [DisplayName("Total Population"), NotNull]
        public Int32? TotalPop
        {
            get { return Fields.TotalPop[this]; }
            set { Fields.TotalPop[this] = value; }
        }

        [DisplayName("Target Population"), NotNull]
        public Int32? TargetPop
        {
            get { return Fields.TargetPop[this]; }
            set { Fields.TargetPop[this] = value; }
        }

        [DisplayName("Type"), Size(30), NotNull]
        public String Type
        {
            get { return Fields.Type[this]; }
            set { Fields.Type[this] = value; }
        }

        [DisplayName("Priority")]
        public Int16? Priority
        {
            get { return Fields.Priority[this]; }
            set { Fields.Priority[this] = value; }
        }

        [DisplayName("Population Year"), NotNull]
        public Int32? PopYear
        {
            get { return Fields.PopYear[this]; }
            set { Fields.PopYear[this] = value; }
        }


        [DisplayName("Province"), Expression("jProvince.[Pname]"), LookupInclude,QuickSearch]
        public String Pname
        {
            get { return Fields.Pname[this]; }
            set { Fields.Pname[this] = value; }
        }

        [DisplayName("Province Pcode"), Expression("jProvince.[Pcode]")]
        public String ProvincePcode
        {
            get { return Fields.ProvincePcode[this]; }
            set { Fields.ProvincePcode[this] = value; }
        }

        [DisplayName("Province Region Id"), Expression("jProvince.[RegionID]")]
        public Int16? ProvinceRegionId
        {
            get { return Fields.ProvinceRegionId[this]; }
            set { Fields.ProvinceRegionId[this] = value; }
        }


        [DisplayName("Province P Abrv"), Expression("jProvince.[PAbrv]")]
        public String ProvincePAbrv
        {
            get { return Fields.ProvincePAbrv[this]; }
            set { Fields.ProvincePAbrv[this] = value; }
        }

        [DisplayName("Province Pcenter"), Expression("jProvince.[Pcenter]")]
        public String ProvincePcenter
        {
            get { return Fields.ProvincePcenter[this]; }
            set { Fields.ProvincePcenter[this] = value; }
        }

        [DisplayName("Province Area Km Sqr"), Expression("jProvince.[AreaKmSqr]")]
        public Int32? ProvinceAreaKmSqr
        {
            get { return Fields.ProvinceAreaKmSqr[this]; }
            set { Fields.ProvinceAreaKmSqr[this] = value; }
        }

        [DisplayName("Province No Of Districts"), Expression("jProvince.[NoOfDistricts]")]
        public Int32? ProvinceNoOfDistricts
        {
            get { return Fields.ProvinceNoOfDistricts[this]; }
            set { Fields.ProvinceNoOfDistricts[this] = value; }
        }

        [LookupEditor(typeof(Locations.Entities.ProvinceRow), CascadeFrom = "RegionId", CascadeField = "RegionId")]
        [DisplayName("Region"), Expression("jRegion.[Rname]")]
        public String RegionName {
            get { return Fields.RegionName[this]; }
            set { Fields.RegionName[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.DistrictId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Dname; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public DistrictRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field DistrictId;
            public StringField Dcode;
            public Int16Field ProvinceId;
            public StringField Dname;
            public Int32Field TotalPop;
            public Int32Field TargetPop;
            public StringField Type;
            public Int16Field Priority;
            public Int32Field PopYear;

            public StringField ProvincePcode;
            public Int16Field ProvinceRegionId;
            public StringField Pname;
            public StringField ProvincePAbrv;
            public StringField ProvincePcenter;
            public Int32Field ProvinceAreaKmSqr;
            public Int32Field ProvinceNoOfDistricts;
            public StringField RegionName;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Locations.District";
            }
        }
    }`

**Comment by Estrusco** [comment]
In DiscrictRow you haven't a jRegion join. So the jRegion.[Rname] isn't valid.

**Comment by ms4hafiz** [comment]
Yes as seen in the diagram. RegionRow does not have link with DistrictRow but it can be linked via ProvinceRow.

So how is it possible to get Rname in the DistrictRow? or it is not possible to get the Rname from Region in to district?

**Comment by gguadalupe** [comment]
As I see it, you have 2 options:
1. Rethink your data model. You have the Region table as your "main" table, when in fact the most important table is District. Both Region and Province should hang from District. 
2. Try to implement something similar to the PersonFullname in the movie tutorial, https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/the_cast_and_characters_they_played.html

Remember that Serenity is a data driven platform, your data model is complex, your Serenity implementation will be complex.

**Comment by ms4hafiz** [comment]
Thank you @gguadalupe for the response and support

I was able to get RegionName from this guide
https://volkanceylan.gitbooks.io/serenity-guide/entities/mapping_attributes.html

My code is now written as following
`
        [Expression("jProvince.[RegionId]"), ForeignKey("Region", "Regionid"), LeftJoin("r")]
        public Int16? RegionId
        {
            get { return Fields.RegionId[this]; }
            set { Fields.RegionId[this] = value; }
        }

        [Expression("r.[Rname]")]
        public string Rname
        {
            get { return Fields.Rname[this]; }
            set { Fields.Rname[this] = value; }
        }`

This expression allow to leftjoin from district to region table via ProvinceId and get whatever column from Region.
`[Expression("jProvince.[RegionId]"), ForeignKey("Region", "Regionid"), LeftJoin("r")]`
