### ISSUE TITLE
T4 Transform - Failed - VS2015

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#2356]
I seem to be having difficulties with the T4 Transform in VS2015. 

```
Transforming templates for all project items.
-------------------------------------
Transforming template ClientTypes.tt with TextTemplatingFileGenerator ... failed.
Transforming template MVC.tt with TextTemplatingFileGenerator ... succeeded.
Transforming template ServerTypings.tt with TextTemplatingFileGenerator ... failed.
-------------------------------------
Text templating transformation complete.

```
I've checked my TypeScript Version, it's at 2.1.5. 

Npm and Node:

PM> npm -v
3.10.10
PM> node -v
v6.10.3
PM> 

Did a reinstall of TypeScript and NodeJs/NPM LTS. Double checked the External Web Tools path. Restarted VS2015 and rebuilt-T4 Transform but the same Output error still occurs. 

Errors list is displaying: 

```
Error		Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Serenity.JSON.Parse[T](String input)
   at Microsoft.VisualStudio.TextTemplatingE90FB93F087812C11772DC489EBC976C54D22CFD8A09E05331C74716ABEB516122FE6958E54C9BEC581DA754AB0C23FF899F4AD1324B9135278B74A21478F38E.GeneratedTextTransformation.TSTypeLister.List()
   at Microsoft.VisualStudio.TextTemplatingE90FB93F087812C11772DC489EBC976C54D22CFD8A09E05331C74716ABEB516122FE6958E54C9BEC581DA754AB0C23FF899F4AD1324B9135278B74A21478F38E.GeneratedTextTransformation.TransformText()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].	Serene2.Web	D:\VisualStudio2015\Projects\Serene2\Serene2\Serene2.Web\Imports\ClientTypes\ClientTypes.tt	1	
```

This is happening with a clean demo install as well. Anyone else experiencing the same issue?

**Comment by wldkrd1** [comment]
It's complaining about Newtonsoft.Json. Did you accidentally upgrade that package?

**Comment by sayuga** [comment]
Not that I recall. I've been busy with a different project all together so I'm just coming back to this project. (mind you i'm the only programmer on it). The only things I've updated are TypeScript and the usual update-package [blabla] on the Package Manager

**Comment by sayuga** [comment]
I just made a full search and I see that all of the Newtonsoft.json references in my current serenity demo build reference version 10 but the error is that it's searching for V9. From what I see in the core files under Serenity/Serenity.web/... here on git, comparing apples to apples, the build here references V9. I don't know how I ended up wit the newer version. I'll try downgrading.

**Comment by sayuga** [comment]
Ok, so I made a amateur mistake and ran 'update-package' on the package manager console without stipulating the package to update causing all packages to update. i'm closing this and going to go fix my mistake as I wallow in my own stupidity....
