### ISSUE TITLE
OuterApply In Properties

### ISSUE THREAD

**Issue by edson** [volkanceylan/Serenity#2357]
Hi @volkanceylan .

Sorry to bother. Just wondering... Is there any reason why OuterApply is not applyable to Property Targets?

using System;
```

namespace Serenity.Data.Mapping
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    public class OuterApplyAttribute : Attribute, ISqlJoin
    {
        public OuterApplyAttribute(string alias, string innerQuery)
        {
            this.Alias = alias;
            this.InnerQuery = innerQuery;
        }

        public String Alias { get; private set; }
        public String InnerQuery { get; private set; }
        public String PropertyPrefix { get; set; }
        public String TitlePrefix { get; set; }
        public Type RowType { get; set; }

        string ISqlJoin.OnCriteria => InnerQuery;
        string ISqlJoin.ToTable => null;
    }
}
```
https://github.com/volkanceylan/Serenity/blob/e0246fb2f406aae5428d4466bf97e91c9b827e42/Serenity.Data/Mapping/OuterApplyAttribute.cs

Best Regards

**Comment by volkanceylan** [comment]
Usually, outer apply WHERE statement is not a simple foreign key, but a full fledged query with a TOP 1 clause. LEFT join is a natural one on a foreign key. So i don't think its much useful to add a OuterApply join to a column.

**Comment by edson** [comment]
Thanks @volkanceylan . It is indeed. I was Just too lazy to write the left joins with top clause so I ended trying the outer apply first. :-)

Best regards
