### ISSUE TITLE
REST API Along Serenity

### ISSUE THREAD

**Issue by bretanac93** [volkanceylan/Serenity#2358]
Hey there guys, anybody can tell me how can I make a REST API along with my Serenity app?, thanks.

**Comment by sayuga** [comment]
Please search through past issues, This has been asked multiple times. 

https://github.com/volkanceylan/Serenity/issues?utf8=%E2%9C%93&q=API

**Comment by petebr** [comment]
I've read all through those other issues and it's not quite been answered fully.
I can see how to "log into" my app from another client, but only if it's on the same domain and I can manage the cookie that makes me authorized. Then consuming the API is straightforward.

If you want to consume your API from another domain, a mobile app or the like, I think you need to issue tokens like JWT such as  "identity server 4" would do - http://docs.identityserver.io/en/release/ and I see no clear way of achieving that yet. Would really appreciate more help there.

**Comment by volkanceylan** [comment]
I've answered this questions many times, see my Gists etc for sample on Android, see JsonServiceClient for source on how to properly use a CookieContainer.

**Comment by samdubey** [comment]
Refer: #630

**Comment by samdubey** [comment]
Duplicate of #630
