### ISSUE TITLE
[Serenity Developer Guide] Changelog / Update notifications

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#236]
Hello, is there any way to see what changes have been made to the Serenity Developer Guide? It says the time it was last updated, but I can't find a place to see a diff of the changes made. Thank you.

**Comment by volkanceylan** [comment]
You should be able to see commits and changes here

https://www.gitbook.com/book/volkanceylan/serenity-guide/activity

Or directly in github:

https://github.com/volkanceylan/serenity-guide/commits/master

**Comment by jsbUSMC** [comment]
Thank you very much. The /activity link to the gitbook site gave me a 403 Forbidden response. However, I am able to view the github changelog just fine, which works for me. Thank you very much!
