### ISSUE TITLE
Use Non-Identity Field as Foreign Key

### ISSUE THREAD

**Issue by ryasin** [volkanceylan/Serenity#2361]
Hi,
I am newbie in Serenity and this is my first try out, Your help will be deeply appreciated. 
I have the following 2 Tables, 
**Region**:
Table("Region").WithColumn("c").AsInt32().Identity().NotNullable()
                .WithColumn("Code").AsString(50).PrimaryKey().NotNullable()
                .WithColumn("Name").AsString(100).NotNullable()
                .WithColumn("Description").AsString(255).Nullable();
**Country**:
 Create.Table("Country").WithColumn("CountryId").AsInt32().Identity().NotNullable()
                .WithColumn("Code").AsString(50).PrimaryKey().NotNullable()
                .WithColumn("Name").AsString(100).NotNullable();
**Foreign Key**:
Alter.Table("Country").AddColumn("RegionCode").AsString(50).Nullable().ForeignKey("FK_Country_RegionCode", "Region", "Code");

As you can see i am not using Identity Columns as Primary / Foreign Key. I want to use Region.Code as Foreign Key in Country. I have created the tables / Code using Serenity. Now when i create a Country and select a Region (It should show Region Name but it shows Region Code), it gives me SQL error which means it is trying to save the RegionId of Region in my RegionCode foreign key in Country table. 

Thank You

**Comment by gguadalupe** [comment]
I'm not an expert on Serenity, but I know something about databases.
This Region table have 2 keys, c and Code (an identity field is a key by itself). From an architectural point of view, you should have only one key in your table. I suppose you are migrating some functionality from another system? or why you want to keep both c and Code in Region?
You should use the foreign keys as simple as possible. A String of 50 is not a recommendable key.
Use **c** as the foreign key and you can keep **Code** as the primary key.
If you do this, then later you can play with the LookupEditor and LookupInclude to bring the description of the Region in the Country dialog.

**Comment by ryasin** [comment]
Hi,
As i am trying to migrate from another system. My Idea was not to rely on Autogenerated Columns in SQL Server for Relationship. Your suggestions were valuable.  Can you please elaborate little with examples of LookupEditor and LookupInclude so that it helps me with understanding of flexibilities as well

**Comment by gguadalupe** [comment]
You have many examples in the Northwind implementation.
My recommendation is the following:
1. Drop the c, you don't need it. Use Code as your only key (without the identity)
2. Review the Lookup sample.
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Editors/ChangingLookupText (http://serenity.is/demo/BasicSamples/ChangingLookupText)
2.1. Also review the movie tutorial. It's really easy to follow and explains in details how to implement the lookup.
3. If you are going to add records in table Region with Serenity, review another piece of sample that will allow you to control de id creation. In the future I will implement this to create the id outside of my serenity app.

Hope this helps.

**Comment by ryasin** [comment]
Thank you for your valuable suggestions.
