### ISSUE TITLE
how could I customize the output format for excel ?

### ISSUE THREAD

**Issue by CuiFY** [volkanceylan/Serenity#2362]
Hi,
how could I customize the output format for excel ?

Thank You!

**Comment by javaman63** [comment]
take a look to the ExcelReportGenerator.cs on Folder Reporting

**Comment by sayuga** [comment]
You also want to look at the information for EPPlus. The exporter is based on it. 

http://epplus.codeplex.com/

**Comment by CuiFY** [comment]
Thank you very much. I know how to do it!
