### ISSUE TITLE
Hosting on Azure or any Linux VPS

### ISSUE THREAD

**Issue by bensonokiora** [volkanceylan/Serenity#2364]
Can Anyone help to write how to host the dotnet core version on Azure or any Linux VPS? , I keep getting errors on Azure such as (unsupported x86 dotnetcore)

**Comment by sayuga** [comment]
There are two videos depicting how to launch on Azure 

Setting up Continuous Deployment on Microsoft Azure for Serenity Applications:

https://www.youtube.com/watch?v=tcywhS9k9Wc

Serenity Application Deployment to Microsoft Azure:

https://www.youtube.com/watch?v=hkU6iVFlWl8
