### ISSUE TITLE
How to refresh Serenity.Authorization.UserDefinition after user logged on

### ISSUE THREAD

**Issue by wirble** [volkanceylan/Serenity#2365]
What is the best way for me to get an updated version of the UserDefinition of the currently logged on user.

When a user logged on, I have a background process that updates their profile on certain criteria.  After this background process is done, what is the best way for me to update their cached UserDefinition and how?

Should I turn off the cache function, if so how can I do that?

Or is there a way to retrieve their current userdefinition instead of the cached version?

Thanks much.

**Comment by marcobisio** [comment]
Try this way:

UserRetrieveService.RemoveCachedUser(....)

**Comment by wirble** [comment]
Thanks @marcobisio , where should I call that? In the AuthenticationService.cs file? So It doesn't cache it anymore...or right before I need it and Serenity will automatically retrieve the current user profile?

**Comment by marcobisio** [comment]
You're welcome @wirble.
You probably should do that every time your background process update a user, in order to force the cache expiration of such user, otherwise you can do some tuning on the expiration interval here (always UserRetrieveService):

    public IUserDefinition ByUsername(string username)
    {
        if (username.IsEmptyOrNull())
            return null;
    
        return TwoLevelCache.Get<UserDefinition>("UserByName_" + username.ToLowerInvariant(),
            TimeSpan.Zero, TimeSpan.FromDays(1), fld.GenerationKey, () =>
        {
            using (var connection = SqlConnections.NewByKey("Default"))
                return GetFirst(connection, new Criteria(fld.Username) == username);
        });
    }

Bye

**Comment by wirble** [comment]
@marcobisio thanks again. I have seen the removecacheduser after the update in authenticationservice file. I wasnt sure if I had to call retrieve again, but i assume serenity will do that automatically.

**Comment by ga5tan** [comment]
@marcobisio 
calling UserRetrieveService.RemoveCachedUser(id, usename) with both parameters filled in in SetInternalFields seemed to do the trick. Ofcourse, I had to forward browser to dashboard, to refresh UserMenu and display new display name
