### ISSUE TITLE
Inline action button not showing up in IE, only Chrome

### ISSUE THREAD

**Issue by wirble** [volkanceylan/Serenity#2366]
I have a user which reported inline button is not showing up in IE but only in Chrome.  I am not sure what could be the issue.  Just in case anyone already ran into this issue, please share your solution.  I am going to do a site visit also and see what the problem is and report back.

        protected getColumns() {
            var columns = super.getColumns();
            var fld = MyRow.Fields;

            columns.unshift({
                field: 'MyButton',
                name: '',
                format: ctx => '<a class="inline-action mycustombutton" title="My Custom Button">' +
                    '<i class="fa fa-phone"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });
        }

**Comment by wirble** [comment]
It looks to be a font awesomeness issue with IE11.  The columns are there bit icons are now appearing. Trying different solution found online to no avail...

**Comment by volkanceylan** [comment]
Try playing with CSS, or other rules that may be changing your inline buttons.
