### ISSUE TITLE
MultiTenancy 

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2367]
Community!

I would like to restrict my application to authorize users to view/edit only their own records not others.

Should I use MultiTenancy or there is other way?

If MultiTenancy, can I modify my existing application to make it MultiTenant? if apply the tenancy at user is enough or should apply for each table?

**Comment by gguadalupe** [comment]
I have implemented multitenancy and works like a charm.
Follow the multitenancy tutorial, not only explains the questions you have, but also I have learned other stuff that I used in my app.
You don't have to do the same code for each table, the tutorial will explain how to implement a behavior for all the tables you choose.

**Comment by ms4hafiz** [comment]
Thank you @gguadalupe

**Comment by ms4hafiz** [comment]
I want to reopen the issue with the following question:

As defined in the tutorial, applying multi-tenant allow view/modification of records for a specific tenant group. What if I want a type of tenant that will have the right to view (only view) all records? is it possible through serenity?

Thanks

**Comment by gguadalupe** [comment]
Yes we can!
I don't know how, but you can... of this I'm 102% almost sure!
You need to check how Serenity works with the security and the permissions for each user.
You can create a new permission and set it for each XXXRow.cs, 
Follow this guide:
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_register_permissions_in_serene.html

Or you can change the behavior of the multi tenancy and add roles for this type of user.

Again, no idea what I'm talking about, but maybe this may give you and idea of what you can do.

Gus.

**Comment by sayuga** [comment]
You control the Read, Delete, Update and Modify by generating permissions. You can also add more than one permission key if I'm not mistake. What you can do is create a view-only permission for the table and apply only that permission to the user.

**Comment by ms4hafiz** [comment]
Thanks for the response. It works now as I wanted.
