### ISSUE TITLE
Login Page issue

### ISSUE THREAD

**Issue by iansilaran** [volkanceylan/Serenity#237]
Tried this on browsers : Edge, Chrome, and Firefox

HTML1300: Navigation occurred.
Login
SCRIPT5009: 'Q$LT' is undefined
LocalText.Site.en-US.Public.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
ColumnsBundle.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
FormBundle.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
TemplateBundle.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
RegisteredScripts.js (1,1)
SCRIPT5009: 'jQuery' is undefined
Login (126,1)

**Comment by volkanceylan** [comment]
There should be some file load errors in console. Missing scripts etc. And what is your solution name?

**Comment by iansilaran** [comment]
This was when I deployed/published to my local IIS.. 
Any idea why it failed to load those files/scripts?
BCISystem is my solution name..

**Comment by iansilaran** [comment]
Okay. I've got it working on Chrome and Firefox - (I forgot to enable static content on windows features. - so I enabled it.)

But I can't get it to work on Edge, I've had this exact issue:

[https://github.com/volkanceylan/Serenity/issues/99](url)

versions:
Serenity.Web - 1.9.9
Serenity.Script - 1.9.9
Serenity.CodeGenerator - 1.9.9

Microsoft Edge - 25.10586.0.0

**Comment by volkanceylan** [comment]
Latest version (1.9.11) should resolve Edge issue
