### ISSUE TITLE
Problem with my scroll-x

### ISSUE THREAD

**Issue by kjaninaramos** [volkanceylan/Serenity#2370]
Why my scroll-x doesn't work?
![nuevo2](https://user-images.githubusercontent.com/25013636/26838515-f76d422a-4aa5-11e7-9546-09c8f422b993.jpg)

**Comment by weichanxiang** [comment]
I have experienced the same issue, the scroll bar disappears when there is data in the grid.

**Comment by kjaninaramos** [comment]
#1342
