### ISSUE TITLE
Cascading Cloning

### ISSUE THREAD

**Issue by fernandocordero** [volkanceylan/Serenity#2371]
Guys am fairly new to serenity, I can see that in the dialog for the entity am cloning, the clone object also returns the associated foreign entity. Basically what I need to do is not just cloning the current record but at the same time any other record(s) associated to it with a foreign key. Can anyone point me into the right direction?

**Comment by volkanceylan** [comment]
You can only clone master/detail relations that are loaded with entity, cloning all related entities is a no.

**Comment by fernandocordero** [comment]
I see, thanks Volkan.


Fernando Cordero
407-286-9095


________________________________
