### ISSUE TITLE
Different between loadentity and afterloadentity

### ISSUE THREAD

**Issue by dxh141130** [volkanceylan/Serenity#2373]
I donot know what is difference between loadentity and afterloadentity. Anyone could give me explain?

**Comment by Estrusco** [comment]
Simply the loadEntity function is called before afterloadentity

```ts
loadResponse: function(data) {
    data = data || {};
    this.onLoadingData(data);
    var entity = data.Entity || new Object();
    
    this.beforeLoadEntity(entity);
    this.loadEntity(entity);
    this.set_entity(entity);
    this.afterLoadEntity();
}
```

In beforeLoadEntity the entity isn't yet loaded. In loadEntity the function return the entity loaded and set data on property grid, in afterLoadEntity you can act on entity before the form is displayed.

**Comment by GreenUtil** [comment]
When I change the value of an attribute of an entity in afterLoadEntity, like

`this.entity.ApplicationID = this._applicationId;`

the change isn't revealed in the form.
Am I missing something ?
I am using Serene Core framework.

**Comment by GreenUtil** [comment]
Somewhere in 

`UserRepository.cs`

`protected override void ValidateRequest()`

 `Row.ApplicationID = null`   (or the default value, but not the desired value)
