### ISSUE TITLE
Upgrade problem from 2.9.8 to 2.9.24

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#2374]
I tried using "Update-Package Serenity.Web" but it failed with:

> Update-Package : 'Serenity.Web' was not installed in any project. Update failed.

Then I used the NuGet Package manager to install 9 updates. All went well without any errors and the solution also compiled with out any errors. However, now I get the following error:

> Server Error in '/LCPermits.Web' Application.
> Could not load file or assembly 'MsieJavaScriptEngine' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
> 

I went thru the NuGet Package manager update twice and still get the above error. Any help would be appreciated.

**Comment by c9482** [comment]
I removed the reference and re-added it by browsing to packages - no avail. Then I noticed that the MsieJavascriptEngine reference was pointing to the tools folder which had an older version of the .dll. 

I replaced the older version of .dll in tools folder with the latest (2.2.1) and recompiled. Now the bin contained the correct version but web.config still had the old dependent assembly (2.0.2).

So, I downgraded MsieJavascriptEngine to version 2.0.2 and now the web.config dependent assembly was saying it's version 2.2.1 (why?). So now NuGet says I need to update to 2.2.1 but web.config and bin are at 2.2.1.

So, I transformed the templates and get the following error:

> Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

Application starts without an error but grids do not populate:

> Error: No select2/compat/query

I am giving up and restoring to state before upgrade. 

Why would "Update-Package Serenity.Web" not work in the first place as documented?

**Comment by volkanceylan** [comment]
You upgraded Select2, you shouldn't. Use Update-Package Select2.js -Version 3.5.1    etc.

Also don't update Newtonsoft.Json to v10

**Comment by c9482** [comment]
Thanks for the info, I appreciate it. Why isn't "Update-Package
Serenity.Web" working for me?

Best regards,

Mark C. Orciuch
N e x t  G e n e r a t i o n  S o l u t i o n s, L t d.
e-mail: mark_orciuch@ngsltd.com
website: http://www.ngsltd.com
LinkedIn: http://www.linkedin.com/in/ngsltd
Twitter: http://twitter.com/ngsltd
Twitter: http://twitter.com/activenwi
YouTube: http://www.youtube.com/user/ngsltdtube
office: 219-488-9066
mobile: 219-488-9002

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material.  Any review, re-transmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and destroy this material.

**Comment by volkanceylan** [comment]
You probably have another, e.g. Script project selected.
