### ISSUE TITLE
Alphabetical order lookup

### ISSUE THREAD

**Issue by kjaninaramos** [volkanceylan/Serenity#2375]
How can I do so that the drop-down list is not sorted alphabetically, I want it to be deployed as it is in the database

![sin titulo](https://user-images.githubusercontent.com/25013636/26939515-276df27e-4c3d-11e7-9931-7a1d2f45a4fb.png)

**Comment by marcobisio** [comment]
Define your xyzLookup and override the PrepareQuery method with the OrderBy clause that you wish.
Look at the LanguageLookup.cs  if you have any doubt.

Bye
