### ISSUE TITLE
Remove Upload button in Read Only Dialog

### ISSUE THREAD

**Issue by alessandromoraes** [volkanceylan/Serenity#2376]
I tried to remove the Upload button and edit button in Dialog, but without success.

I used the standard removal in Dialog.ts
```
Buttons.splice (Q.indexOf (buttons, x => x.cssClass == "save-and-close-button"), 1);
Buttons.splice (Q.indexOf (buttons, x => x.cssClass == "apply-changes-button"), 1);
```
I tried to remove it that way, but it did not work.
`Buttons.splice (Q.indexOf (buttons, x => x.cssClass == "add-file-button"), 1);`

What would be the way to remove these other buttons?

**Comment by volkanceylan** [comment]
Hide them on updateInterface() method, this.toolbar.findButton('.xyz-button').toggle(false)
