### ISSUE TITLE
Multiple Grids,Multiple Navigation menu items

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2377]
Hello Volkan, 
Please if I want to create two separate grids and forms from the same database table and have separate menu items for them in the main navigation file, how do I do this?

**Comment by dudeman972** [comment]
I have the same question

**Comment by sayuga** [comment]
Navigation items just adds the reference to where to go. you can create the entries without too much trouble by simply updating the controller reference. You can either add separate page.cs files with unique controller names and add them to the navigation (see any Northwind xyzPage.cs) or you can use one controller with multiple page references by adding the controller and defining the page you want using the 'action' attribute (see Basic Samples xyzNavigation.cs and xyzPages.cs).

You could add 20+ navigation links to the same table if you wanted by simply adding the same link that many times. 

Additionally, ponder on this: Aren't you asking for the exact same thing as the Basic Samples do? The basic samples has different views of the existing Northwind tables while each sample has it's own menu link?

**Comment by volkanceylan** [comment]
@sayuga is correct
