### ISSUE TITLE
2 pages for a given table

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#2379]
Hi guys,
Is it possible to create 2 pages for any given table.  
For example, I have a table called cars.  In there it has a column called imported.  Can I generate code for 2 pages, one called Imported Cars and other called Local Cars?
Thanks

**Comment by mrajalko** [comment]
Yes you can do that by having two *grid.ts files and two *.cshtml files and two actions in your *page.cs files.

**Comment by dudeman972** [comment]
Thanks!  that did it.
