### ISSUE TITLE
Automating Enums dropdowns based on a convention

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#2380]
Hello all,

I would like to automate the creation of Enum dropdowns that are described in the documentation pages 76+, based on a convention that would be enum names ending with 'Enum', (for example : public enum MovieKindEnum rather than MovieKind)

This would automatically generate (or change and replace) the code, with something like

[DisplayName("Kind"), NotNull]
public MovieKindEnum? Kind
{
get { return (MovieKindEnum?)Fields.Kind[this]; }
set { Fields.Kind[this] = (Int32?)value; }
}

Pushing this logic forward we could have more conventions, like MovieKindRadioEnum generating a  [RadioButtonEditor] public Int32 Kind { get; set; } in the Forms.

What would be the best way to achieve this? Should it be something that Volkan should consider, since only him can decide on conventions that would be followed by the community? Thanks for your thoughts.

**Comment by volkanceylan** [comment]
Sorry, this is not something i'd like to implement as it is purely your personal taste.
