### ISSUE TITLE
Lookup filter

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#2381]
Dialog  olulşturuldugunda   şartlara göre Lookup doldurmak istiyorum. Yardımcı olurmusunuz
aşağıdaki gibi yaptım fakat olmadı.

 constructor() {

this.form.AdresId.items =AdresRow.getLookup().items.filter(f => f.Id === 5 );
}

**Comment by volkanceylan** [comment]
LookupEditor bu şekilde çalışmaz. FilterField, FilterValue deneyin.
