### ISSUE TITLE
TimeEditor minute change do not trigger data refresh

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#2382]
when we apply a time filer we can see two select one for hour and one for mintues. 

the change done in hour fires the data refresh event but the same is not triggered when minute figure is changed.

is there any setting of time editor which i might be missing.

**Comment by volkanceylan** [comment]
This is a bug. You may try finding the time dropdown and triggering change for now.

**Comment by mrajalko** [comment]
please suggest how to find and trigger change.

**Comment by dfaruque** [comment]
User the following method
```
static bindDateTimeEditorChange(editor, handler): void {
            editor.change(handler);
            editor.element.closest('.field').find('.time').change(handler);
            editor.element.closest('.field').find('.inplace-now').click(handler);
        }
```

**Comment by ArsenioInojosa** [comment]
I have the same problem.

It works with DateTimeEditor but not with TimeEditor.

Trigger does not work when the minutes are changed.

**Comment by slang123** [comment]
this is still a bug.
