### ISSUE TITLE
Filters are not working at all

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#2386]
I have updated Serene to 2.9.24,
before updating Quick Filters and Edit Filter were working absolutely fine, but after the update, no filters are working

What can be the possible cause, did it caused due to updating packages?

**Comment by JoshDiDuca** [comment]
Updated to Serenity version 2.9.24 from 2.6 yesterday and my filters are fine.

**Comment by vinaykulkarni89** [comment]
In MyListHnadler -> ApplyFilters I have added my code for grid records, is it causing the issue?

**Comment by vinaykulkarni89** [comment]
Tried to version 2.6, but no use,

I have added my custom filters in Repository, for filtering grid, these custom filters are causing issue, what can I do so that filters will work with my custom filtering in Repository

**Comment by volkanceylan** [comment]
If you don't call base.ApplyFilters, it won't work.

**Comment by vinaykulkarni89** [comment]
@volkanceylan thank-you for reply,
Following is my code,

private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                var user = (UserDefinition)Serenity.Authorization.UserDefinition;

                if (user.UserId == 1)
                {
                    return;
                }
                
                var data = new UsersList();

                using (var connection = SqlConnections.NewFor<UserRow>())
                {
                    var od = UserRow.Fields;
                    data.Users1 = connection.List<UserRow>(q => q
                        .SelectTableFields()
                        .Select(od.UserId)
                        .Where(od.UpperLevel == user.UserId));

                    data.Users2 = connection.List<UserRow>(q => q
                        .SelectTableFields()
                        .Select(od.UserId)
                        .Where(od.UpperLevel2 == user.UserId));

                var str = fld.OwnerId + " = "+ user.UserId + " OR " + fld.AssignedId + " = "+ user.UserId;

                var str1 = ""; var str2 = "";

                foreach (var item in data.Users1)
                {
                    str1 = str1 + " OR " + fld.OwnerId + " = " + item.UserId.Value + " OR " + fld.AssignedId + " = " + item.UserId.Value;
                }

                foreach (var item in data.Users2)
                {
                    str2 = str2 + " OR " + fld.OwnerId + " = " + item.UserId.Value + " OR " + fld.AssignedId + " = " + item.UserId.Value;
                }

                query.Where(new Criteria(str + str1 + str2));
            }

**Comment by volkanceylan** [comment]
Use PARENTHESIS

**Comment by vinaykulkarni89** [comment]
@volkanceylan do you mean to say i'm missing paranthesis somewhere?

**Comment by volkanceylan** [comment]
query.Where(new Criteria("(" + str + str1 + str2 + ")"));

You know about SQL AND/OR operator precedence right?

**Comment by volkanceylan** [comment]
And why are you strings to build criteria???

**Comment by vinaykulkarni89** [comment]
@volkanceylan Thankyou, will strings cause any effect on performance?

@JoshDiDuca thankyou for suggestion
