### ISSUE TITLE
User Sign up

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2388]
Hello Volkan,
Please in my application,every user belongs to an agency and users who are not administrators only see the data of their agency. So agency is being used as the tenantId in a multitenancy system. I want the users to sign up themselves by going to the sign up page and typing their username and their agency. The default signup page has fullname, email and password. How do I add username and agency fields to that form such that they are saved to the users table?

**Comment by volkanceylan** [comment]
Start by trying to modify the form
