### ISSUE TITLE
Custom LookupEditor

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#2389]
I have a custom Lookup Editor that needs to use a Stored Procedure. For the Stored Procedure, I need to pass an ID. The problem is we store this ID in a session Variable which we cannot access in the LookupEditor for some reason. It comes back null. Is there a way to pass a parameter for a lookupeditor?

**Comment by volkanceylan** [comment]
Lookup editors does not support parameters, nor stored procedures.
