### ISSUE TITLE
Cascade dialog

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#239]
Greeting,

I have InPlaceAdd on a Lookup which is self reference. i.e When click InPlaceAdd button another new  dialog will appear. Since  dialogs are same and their position is also same, so It difficult to see the effect of InPlaceAdd button click.

This is what happening
![untitled](https://cloud.githubusercontent.com/assets/16621563/12970727/a9ec7a70-d0bc-11e5-8970-44a7ec0124ab.png)

This is what I am trying to achieve.
![untitled2](https://cloud.githubusercontent.com/assets/16621563/12970810/abd1838e-d0bd-11e5-8804-d0b3bb97cdd5.png)

**Comment by ademc** [comment]
You will send a parameter or check is there any opened dialog with its css class (dom contains any xxxdialog class) Aftet that you can add backdrop effect

**Comment by dfaruque** [comment]
How can I subscribe the click event of InplaceAdd button?

**Comment by ademc** [comment]
You can check all dom contains dialog css class with this:
http://stackoverflow.com/questions/4256339/javascript-how-to-loop-through-all-dom-elements-on-a-page

You can add opacity with this code part:
```csharp
 protected override void OnDialogOpen()
        {
            base.OnDialogOpen();

            J(".ui-widget-overlay.ui-front").Last().CSS("opacity", "0.5");
        }
```

**Comment by VictorTomaili** [comment]
Lets handle something. Firstly enable parent lookup editor after Name is filled. After that you can set child name parameter for in-place dialog. And rename in-place dialog tittle like `Add Parent for [Child Name]`. In-place dialog is block behind dialog for editing. if you want to more visual effect, try to change diffrent color for each in-place dialog or add some information label on toolbar.

**Comment by volkanceylan** [comment]
protected override void OnDialogOpen()
        {
            base.OnDialogOpen();

            var prior = J(".ui-dialog").Eq(-2);
            if (prior.Length > 0)
                if (prior.HasClass(this.GetCssClass()))
                    SubDialogHelper.Cascade(this, prior);
        }

**Comment by dfaruque** [comment]
Wow;

Thank you very much.

**Comment by JohnRanger** [comment]
Thanks again, @volkanceylan for this super tip.

For all which came here after the switch from Saltarelle to Typescript, the typescript way is like this:

```ts
        protected onDialogOpen(){
            super.onDialogOpen();

            var prior = J(".ui-dialog").Eq(-2);
            if (prior.Length > 0) {
                Serenity.SubDialogHelper.cascade(this, prior);
            }
        }
```

Hope this helps somebody.

With kind regards,

John

**Comment by minhhungit** [comment]
I don't know why your code does not work for me @JohnRanger 

But this works

```javascript
protected onDialogOpen() {
    super.onDialogOpen();

    let prior = $(".ui-dialog").eq(-2);
    if (prior.length > 0) {
        this.element.dialog().dialog('option', 'position', { my: 'left top', at: 'left+24 top+24', of: prior[0] });
    }
}
```

**Comment by minhhungit** [comment]
Or something like this:

```javascript
protected onDialogOpen() {
    super.onDialogOpen();

    let prior = $(".ui-dialog").eq(-2);
    if (prior.length > 0) {
        $(document).one("dialogopen", (e) => {
            this.element.dialog().dialog('option', 'position', { my: 'left top', at: 'left+24 top+24', of: prior[0] });
        })
    }
}
```
