### ISSUE TITLE
Saltarelle-Serenity support of current features

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2390]
Dear Volkan,

I have followed the Transition of Serenity from Saltarelle to Typescript and - while learning typescript - also created 2 Little Projects with Typescript-Serenity. But after really trying it - I have to admit that the Saltarelle/Split-Project mode and your clear abstraction of the different Events on the Client side within Saltarelle C#  is much easier to understand and troubleshoot for me.

As I am Standing before a new (larger) Project which I will do with Serenity, here my question: In current Serenity (V9.x) are all Features which you did put into the Type-script-Version of Serenity also available in the "Saltarelle Version"? (I mean the Client side stuff, the Type transforms, etc)

Thanks for your valuable Feedback and

with Kind regards,

John Ranger

**Comment by volkanceylan** [comment]
Saltaralle is still working for old projects, i have several such big scale projects, but new features will come with TypeScript primarily.

**Comment by JohnRanger** [comment]
Good evening Volkan,

thanks for your valuable Feedback. Do you have a comparison Chart with Serenity-Features supported or not by these two client-side "Scripting Environments"?

Thanks again for your valuable Feedback 

and with Kind regards,

John

**Comment by volkanceylan** [comment]
No, i don't have such a chart, but you can always call TypeScript code from Saltaralle or vice-versa.
