### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2391]
1.  Where can I find the code for the the "edit filter" button at the bottom of the grid?  I want to disable the link and create a toolbar button to do this.

2.  I want to overide the column chooser button.  how can I call the function to open the column picker

Thanks

**Comment by Estrusco** [comment]
To remove edit filter in grid, remove the decoratore @Serenity.Decorators.filterable() in your xyzGrid.ts

**Comment by mcb2323** [comment]
Thanks
