### ISSUE TITLE
loadEntityAndOpenDialog for loop insert in the DetailList object

### ISSUE THREAD

**Issue by vinslake** [volkanceylan/Serenity#2392]
How can I do for loop insert in the DetailList?
            buttons.push({
                title: 'Add Order with 5 Chai by Laura', cssClass: 'add-note-button',
                onClick: () => {
                    // we could use EditItem here too, but for demonstration
                    // purposes we are manually creating dialog this time
                    var dlg = new Northwind.OrderDialog();

                    // let grid watch for changes to manually created dialog, 
                    // so when a new item is saved, grid can refresh itself
                    this.initDialog(dlg);

                    // get a reference to product Chai
                    var chai = Northwind.ProductRow.getLookup().items
                        .filter(x => x.ProductName === 'Boston Crab Meat')[0];

                    // LoadEntityAndOpenDialog, loads an OrderRow 
                    // to dialog and opens it
                    var lauraCallahanID = Northwind.EmployeeRow.getLookup().items
                        .filter(x => x.FullName === 'Laura Callahan')[0].EmployeeID;

                    dlg.loadEntityAndOpenDialog(<Northwind.OrderRow>{
                        CustomerID: 'GOURL',
                        EmployeeID: lauraCallahanID,
                        //loop an object here
                        DetailList: [{
                            ProductID: chai.ProductID,
                            ProductName: chai.ProductName,
                            UnitPrice: chai.UnitPrice,
                            Quantity: 5,
                            LineTotal: chai.UnitPrice * 5
                        }
                        ]
                    });
                }
            });

**Comment by volkanceylan** [comment]
Please try a Javascript / Programming course

**Comment by vinslake** [comment]
sorry to ask but can give me a sample loop with the object? im new to java programming
thanks

**Comment by volkanceylan** [comment]
That's why you should read a Javascript book
