### ISSUE TITLE
Problem with new Serenity project

### ISSUE THREAD

**Issue by jorgemota** [volkanceylan/Serenity#2393]
Hi, I just followed the guide at with netcore in linux
http://serenity.is/blog/2017/01/18/welcome-to-aspnet-core
first time I build project

Modules/Meeting/MeetingAttendee/MeetingAttendeeEditor.ts(1,1): warning TS6053: File '/tmp/proj/Test.Web/Modules/common/helpers/grideditorbase.ts' not found. [/tmp/proj/Test.Web/Test.Web.csproj]
/tmp/proj/Test.Web/Test.Web.csproj(46,5): warning MSB3073: The command "node_modules/.bin/tsc -p ./tsconfig.json" exited with code 2.

Build succeeded.

Modules/Meeting/MeetingAttendee/MeetingAttendeeEditor.ts(1,1): warning TS6053: File '/tmp/proj/Test.Web/Modules/common/helpers/grideditorbase.ts' not found. [/tmp/proj/Test.Web/Test.Web.csproj]
/tmp/proj/Test.Web/Test.Web.csproj(46,5): warning MSB3073: The command "node_modules/.bin/tsc -p ./tsconfig.json" exited with code 2.
    2 Warning(s)

If I run dotnet build  after a few times with another empty project I got this:
Imports/ServerTypings/Northwind.OrderRow.ts(70,34): warning TS2451: Cannot redeclare block-scoped variable 'ShipViaCompanyName'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderRow.ts(71,34): warning TS2451: Cannot redeclare block-scoped variable 'ShipViaPhone'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderRow.ts(72,34): warning TS2451: Cannot redeclare block-scoped variable 'ShippingState'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderRow.ts(73,34): warning TS2451: Cannot redeclare block-scoped variable 'DetailList'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderService.ts(3,22): warning TS2451: Cannot redeclare block-scoped variable 'baseUrl'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderService.ts(12,34): warning TS2451: Cannot redeclare block-scoped variable 'Create'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderService.ts(13,34): warning TS2451: Cannot redeclare block-scoped variable 'Update'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderService.ts(14,34): warning TS2451: Cannot redeclare block-scoped variable 'Delete'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
Imports/ServerTypings/Northwind.OrderService.ts(15,34): warning TS2451: Cannot redeclare block-scoped variable 'Retrieve'. [/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj]
/home/jorge/Desarrollo/sstt/front.Web/front.Web.csproj(46,5): warning MSB3073: The command "tsc -p ./tsconfig.json" exited with code 2.

If I run dotnet run  I got a empty blank page with a lot off errors 404 for a lot of files...
GET http://localhost:5123/Content/simple-line-icons.css?v=2017521303 
localhost/:19 GET http://localhost:5123/Content/aristo/aristo.css?v=2017521303 
localhost/:21 GET http://localhost:5123/Content/bootstrap.css?v=2017521303 
localhost/:17 GET http://localhost:5123/Content/ionicons.css?v=2017521303 
localhost/:13 GET http://localhost:5123/Content/font-awesome.css?v=2017521303 
localhost/:11 GET http://localhost:5123/Content/font-open-sans.css?v=2017521303 
localhost/:23 GET http://localhost:5123/Content/colorbox/jquery.colorbox.css?v=2017521303 
localhost/:25 GET http://localhost:5123/Content/jquery.fileupload.css?v=2017521303 
localhost/:27 GET http://localhost:5123/Content/pace.css?v=2017521303 
localhost/:31 GET http://localhost:5123/Content/css/select2.css?v=2017521303 
localhost/:29 GET http://localhost:5123/Content/slick.grid.css?v=2017521303 
localhost/:33 GET http://localhost:5123/Content/toastr.css?v=2017521303 
localhost/:35 GET http://localhost:5123/Content/serenity/serenity.css?v=2017521303 
localhost/:13 GET http://localhost:5123/Content/font-awesome.css?v=2017521303 
localhost/:11 GET http://localhost:5123/Content/font-open-sans.css?v=2017521303 
localhost/:15 GET http://localhost:5123/Content/simple-line-icons.css?v=2017521303 
localhost/:19 GET http://localhost:5123/Content/aristo/aristo.css?v=2017521303 
localhost/:17 GET http://localhost:5123/Content/ionicons.css?v=2017521303 
localhost/:21 GET http://localhost:5123/Content/bootstrap.css?v=2017521303 
localhost/:23 GET http://localhost:5123/Content/colorbox/jquery.colorbox.css?v=2017521303 
localhost/:25 GET http://localhost:5123/Content/jquery.fileupload.css?v=2017521303 
localhost/:27 GET http://localhost:5123/Content/pace.css?v=2017521303 

I am not sure what to do...
npm -v 5.0.3
node_modules/.bin/tsc -v 2.1.5
node_modules/.bin/lessc -v lessc 2.7.2 (Less Compiler) [JavaScript]

dotnet
[jorge@blackrabbit .bin]$ dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

dotnet --version 
1.0.4

**Comment by jorgemota** [comment]
Maybe the core version is broken.. created from visual studio an empty project for asp.net and all was ok, but I cannot run that version on linux box.

**Comment by millerpro** [comment]
Replace the first line in file \Modules\Meeting\MeetingAttendee\MeetingAttendeeEditor.ts
by 
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

**Comment by jorgemota** [comment]
hi @millerpro  First line in file is:
/// reference path="../../common/helpers/grideditorbase.ts" /

I need to uncomment that line ?

**Comment by millerpro** [comment]
No, look at the upper case in my example

**Comment by jorgemota** [comment]
Oh, first time github only show me  /// not the text  I am going to check

**Comment by jorgemota** [comment]
The first error is gone, Thx 
after build and run I Got this now

Web.csproj]
Imports/ServerTypings/Northwind.EmployeeRow.ts(60,34): warning TS2451: Cannot redeclare block-scoped variable 'BirthDate'. [/home/jorge/Desarrollo/sstt/web/sstt.Web/sstt.Web.csproj]
Imports/ServerTypings/Northwind.EmployeeRow.ts(61,34): warning TS2451: Cannot redeclare block-scoped variable 'HireDate'. [/home/jorge/Desarrollo/sstt/web/sstt.Web/sstt.Web.csproj]
Imports/ServerTypings/Northwind.EmployeeRow.ts(62,34): warning TS2451: Cannot redeclare block-scoped variable 'Address'. [/home/jorge/Desarrollo/sstt/web/sstt.Web/sstt.Web.csproj]
Imports/ServerTypings/Northwind.EmployeeRow.ts(63,34): warning TS2451: Cannot redeclare block-scoped variable 'City'. [/home/jorge/Desarrollo/sstt/web/sstt.Web/sstt.Web.csproj]
Imports/ServerTypings/Northwind.EmployeeRow.ts(64,34): warning TS2451: Cannot redeclare block-scoped variable 'Region'. [/home/jorge/Desarrollo/sstt/web/sstt.Web/sstt.Web.csproj]
/home/jorge/Desarrollo/sstt/web/sstt.Web/sstt.Web.csproj(46,5): warning MSB3073: The command "node_modules/.bin/tsc -p ./tsconfig.json" exited with code 2. 

And when opened http://localhost:5123 got redirected to http://localhost:5123/Account/Login/?ReturnUrl=%2F But I always got a blank page, with a lot of 404 errors :(

**Comment by jorgemota** [comment]
If I comment  the Excludes part on tsconfig.json I don't get errors, but receive a error about overwrite target file :(

**Comment by volkanceylan** [comment]
Linux is case sensitive, check that cases in exclude matches ones actually in disk.

**Comment by jorgemota** [comment]
@volkanceylan  No, the problem is excluding files I got no problems about duplicity of variables, but got an error about overwrite target file.  Using latest version in netcore you cannot create a  new proyect to test. 

I am leaving it, you can close the ticket, I was just trying to evaluate Serenity but this is not a mature option to start developing projects in .net.
