### ISSUE TITLE
Missing Navigation Links

### ISSUE THREAD

**Issue by marc-d** [volkanceylan/Serenity#2398]
I'm sure it's something I did but I've spent hours trying to resolve it without luck.

Any new Tables created with Sergen are not being displayed in the Navigation Panel.  

Steps:

1. Open Sergen, select Connection String
2. Select Table Name - All Files to be Generated except Grid Editor/Grid Editor Dialog
3. Generate Code
4. Reload Solution/Rebuild Solution/Publish Solution

New Table is not in Navigation Panel

I have tried moving the navigation info to NavigationItems.cs - still not showing.

I have made changes to NavigationItems.cs to existing Menus, Links and they reflect fine - it is only NEW items that won't populate.  

No errors are showing - I've cleaned, manually deleted the Folders from the Module, Server Typings, etc. and tried renaming the tables, selecting new tables - nothing seems to work.

The below in red is what is not showing up:

![image](https://user-images.githubusercontent.com/17240237/27161391-fc815572-512f-11e7-8353-9a034d1cb6c9.png)

![image](https://user-images.githubusercontent.com/17240237/27161410-1d615cc4-5130-11e7-9dec-a7629a285eb4.png)

**Comment by sayuga** [comment]
If you aren't getting any errors, then it could simply be a typo somewhere breaking the transaction. Try duplicating a working navigation link. If it shows the duplicated link in the menu I'd check the namespace, controller name and the link map for the page.

**Comment by marc-d** [comment]
Still couldn't find the fault anywhere - ended up rebuilding from scratch.
