### ISSUE TITLE
DateEditor assign date issue

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#24]
Hi,

I want to assign date value to a field when opening dialog. This my code:

    public class SomeDialog : EntityDialog<SomeRow>
    {
        SomeForm form;

        public SomeDialog()
        {
            form = new SomeForm(this.idPrefix);
        }

        protected override void LoadEntity(SomeRow entity)
        {
            base.LoadEntity(entity);
            if (IsNew)
                form.DateTimeTypeField.Value = JsDate.Today.ToDateString();// OR Datetime.Now.ToDateString() etc
        }
    }

When dialog opens DatetimeTypeField always shows  1.1.1970 value.

**Comment by volkanceylan** [comment]
DateEditor.Value property is a string in ISO date/time format (yyyy-MM-ddTHH:mm:ss). This is to provide compability with JSON encoding of dates server side. 

You can use ValueAsDate property like `ValueAsDate = JsDate.Today` or `Value = JsDate.Today.ToString("yyyy-MM-dd")`

**Comment by ademc** [comment]
I notice my SERENE template is obsolete. I updated and i can use ValueADate property now. Thakns
