### ISSUE TITLE
MultiTenancy - Admin user not able to designate tenancy

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#240]
I think you tackled this with someone before but even using google translate I had some difficulty following what you were telling them to do so I ask here in English with hopes of a solution. 

I've implemented the MultiTenancy per the guide and I've ran into two issues. Firstly, I designated the restriction on the UserDialog,cs regarding showing TenantID only when the admin user logs in.  

 protected override List<PropertyItem> GetPropertyItems()
        {
            var items = base.GetPropertyItems();

            if (!Authorization.HasPermission("Administration:Tenants"))
                items = items.Where(x => x.Name != UserRow.Fields.TenantId).ToList();

            return items;
        }

This make the TenantID field disappear for secondary tenant (great) but it's also disappearing for the admin user. 

Secondly, the restriction upon the Tenancy table is present for the second user but it is still displaying the Tenant table on the left nav bar for the secondary user though it will break when the secondary user attempt to access the table "{"Authorization has been denied for this request!"}".

**Comment by volkanceylan** [comment]
Your HasPermission method in script side should be like this:
```cs
         public static bool HasPermission(string permissionKey)
          {
            return 
                UserDefinition.Username == "admin" ||
                UserDefinition.Permissions[permissionKey];
        }
```

For navigation problem, set permission Administration:Tenants for row, page and endpoint

**Comment by volkanceylan** [comment]
This is also changed in latest version.
