### ISSUE TITLE
Grid Question

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#2400]
Is there a function that is called after the grid is loaded on the client I can put some jquery function in line the afterloadentity for dialog.  I basically want to apply the datepicker to a textbox on my grid after it loads.  I tried to do this in the view page but it didnt work.

**Comment by sayuga** [comment]
Are you adding it to the dialog or the grid?

**Comment by mcb2323** [comment]
Grid sir.

**Comment by mcb2323** [comment]
used an onclick event which works for my solution.
