### ISSUE TITLE
Select2 search, clicking define new puts search text name field but with lowercase.

### ISSUE THREAD

**Issue by JoshDiDuca** [volkanceylan/Serenity#2401]
I noticed that when you search in the select2 dropdown then click "Define new" it adds the search text to the name field automatically which is an absolutely amazing feature of Serenity. Although I noticed that throughout the versions of Serenity it's always put it in lowercase.

Here's an example of what I mean:

![new client](https://user-images.githubusercontent.com/24326522/27234398-c88b0ed0-52b4-11e7-85e1-77cfcd78be6e.PNG)
![new client2](https://user-images.githubusercontent.com/24326522/27234397-c88a6048-52b4-11e7-8bdc-1d545a2ff6f3.PNG)

Does anybody have a fix for this or can this be fixed?

**Comment by JoshDiDuca** [comment]
I managed to fix this by editing the Serenity.Script.UI.js at line 4474 (Version 2.9.24)

Changed:
s = ss.coalesce(Select2.util.stripDiacritics(s), '').toLowerCase();
To:
s = ss.coalesce(Select2.util.stripDiacritics(s), '');

The only problem is now, I presume that when I update Serenity I'm going have to do it again and again.
Not sure if I should close this or not but feel free to close if needed.

**Comment by Estrusco** [comment]
You can make a pull request to merge the variation in source of serenity.

**Comment by volkanceylan** [comment]
This is a bug, will be fixed in next version

fabf1af2b8adb174dcfc668e38f97d0205994390

**Comment by JoshDiDuca** [comment]
Thanks both, 
@Estrusco I've only really just started to learn Git and the Serenity source as I'm still a bit of a newbie so I will in the future, Thank you. 

@volkanceylan Thanks volkanceylan, feels good to contribute to the actual framework! I also noticed that you can also edit read only DateTime editors when you're viewing the dialog from the dashboard. I fixed this by adding the disabled property on the setReadonly method.

Thanks again both.
