### ISSUE TITLE
MasterDetailEditor - list not showing on reload

### ISSUE THREAD

**Issue by wojtj** [volkanceylan/Serenity#2402]
Hi
First of all, thanks for this fantastic framework.
I would appreciate any pointers about where I may be going wrong. 
I am using the MasterDetailEditor as per the documentation. 

When I first add a detail record, and close the detail dialog, the correct column is displayed with the new record:
![image](https://user-images.githubusercontent.com/8101578/27239760-9a1058f6-5315-11e7-9be5-967c13e0a43d.png)

However, when I save that record, and go back into it, the column is now empty:
![image](https://user-images.githubusercontent.com/8101578/27239792-b6044e00-5315-11e7-864c-861ff19a0ee5.png)

- No errors in the console.
- I have confirmed that the record has been correctly created in the database.
- Using the console, I have confirmed that getLookup is populating the column names correctly.
- As far as I can tell, I have followed the steps in the example to the letter.

Does anyone have any pointers about where I should be looking for my error?

Thanks in advance.

**Comment by sayuga** [comment]
Would you mind adding the snippet of code of how you implemented the Master detail?

**Comment by Estrusco** [comment]
See issue https://github.com/volkanceylan/Serenity/issues/1959 and https://github.com/volkanceylan/Serenity/issues/1962

In your xyzDialog.ts try to add

```ts
protected updateInterface() {
    super.updateInterface();
    this.form.YoutDetailList.element.triggerHandler('layout');
}
```

**Comment by volkanceylan** [comment]
Again :) See tutorial, IncludeColumns and MinSelectLevel
