### ISSUE TITLE
Send Invoice over Mail

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#2404]
In
buttons.push(Test.Common.ReportHelper.createToolButton({
title: 'Inovice',
cssClass: 'export-pdf-button',
reportKey: 'Invoice.PrintInvoice',
//I have set 
download: true
}

this is downloading file on the local computer, I want to download this on the server so that I can attach this file to mail
Or is there any another way to send this PDF over mail as attachment

**Comment by vinaykulkarni89** [comment]
Ok got some solution for it

**Comment by joheric** [comment]
Do you solved this?

**Comment by vinaykulkarni89** [comment]
@joheric  yes i have got solution

**Comment by ANDY7575** [comment]
@vinaykulkarni89  can please share code..
thank you..
Aniket

**Comment by vinaykulkarni89** [comment]
@ANDY7575 
You can customize the reportcontroller, where you can add an attribute similar to download and add the PDF rendered data as below

mm.Attachments.Add(new Attachment(new MemoryStream(renderedBytes), "Invoice-" + DateTime.Now.ToLongDateString() + ".pdf"));
