### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by drogit** [volkanceylan/Serenity#2405]
Cannot insert the value NULL into column 'xxColxx', table 'Serene3_xxDbxx_v1.dbo.xxTablexx'; column does not allow nulls. INSERT fails.
newbie followed movie tutorial to add table but as you can see, adding records gets the error. the  primary key field does appear in grid but not appear in edit view.  i missed a step somewhere but everything else worked great.  the db i added has tables with compound primary keys, but his table just has the one primary key (small int). no other tables added yet.
PS. spectacular app dude, well done, even documentation great (just not for newbie like me!)

**Comment by sayuga** [comment]
Check on your tables on the DB side and make sure you don't have a column set to not accept nulls, that is attempting to add nulls from the client side. 

In other words, your xyzRow.cs file fields and the table fields on the DB should match regarding which ones are set to 'NotNull'. You probably have a not null column on the database that you are not managing accordingly on the front end.
