### ISSUE TITLE
wkhtmltopdf&IIS Firewall?

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2406]
Hi! In other PCs are not generated reports. The PDF is generated with the text "Error 404: Not Found". From the local machine works. If generate HTML report it works too.

**Comment by vinaykulkarni89** [comment]
Have you hosted server?

**Comment by Zahar661** [comment]
vinaykulkarni89, Home PC, Win10 Pro

**Comment by Zahar661** [comment]
The router is the problem, but the 80 port is not enough.

**Comment by Zahar661** [comment]
proxy Client
