### ISSUE TITLE
save fails 1 to 1 relation - null not allowed

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#2407]
hi,
i have a emplyee table that has a personID column, which is a foreign key to person table.  There is a 1-to-1 relationship.  When i hit save on a employee dialog, i get a "Cannot insert the value NULL into column 'PersonId' ..." exception.  I have personId column decorated as such: 
[DisplayName("Person"), NotNull, ForeignKey("[x].[Person]", "Id"), InnerJoin("jPerson"), TextualField("PersonName")]
Am i missing some thing.  I considered MasterDetail and LinkSet relation but i don't think they apply.

**Comment by sayuga** [comment]
Why is your foreign key table reference '[x].Person'? Look at the intellisense for the table and you'll clearly see youre calling it wrong. If anything, it should be ForeignKey(typeof(PersonRow),'Id'). Do a Find call on your project for 'foreignkey' and you'll find tons of samples on how to properly use it.

**Comment by dudeman972** [comment]
I believe it was auto generated by sergen.  Even in the developer guid it using this pattern: [DisplayName("Genre"), ForeignKey("[mov].Genre", "GenreId"), LeftJoin("g")]
public Int32? GenreId
{
get { return Fields.GenreId[this]; }
set { Fields.GenreId[this] = value; }
}
Therefore, i don't think that is the problem.

**Comment by sayuga** [comment]
so your schema name is 'x'?

**Comment by dudeman972** [comment]
That's correct.  it's something else but for privacy reason i replaced it with x

**Comment by dudeman972** [comment]
Hi the issues are still unresolved. any help will be appreciated.

**Comment by VictorTomaili** [comment]
`[DisplayName("Person"), NotNull, ForeignKey("[x].[Person]", "Id"), InnerJoin("jPerson"), TextualField("PersonName")]`

You have **NotNull** attribute on your row property. If it's auto generated by sergen, you must ensure about your table column is nullable.

**Comment by dudeman972** [comment]
The column 'PersonId' on table 'Employee' is not nullable by design.  As all emplyees are considered person.  I was hoping there was some behavior like MasterDetail or LinkingSetBehavior, that would do insert in the Person table prior to inserting into Employee and using the Id from Person table insert for PersonId column in employee table.
I even tried modifying the database to make PersonId nullable, eventhough i don't get any error, however, only employee table was inserted into and nothing was inserted into person table.

**Comment by sayuga** [comment]
I think I'm understanding the issue. You essentially want to create the the employee record BEFORE the person record exists. If you do not assign a value to the personId and it's set to null it wont take the value but if you just need it to create a fresh person record when saving the employee record, you could make the personId field on the employee table to allow null and then add behavior so that the dialog will trigger a new personId if you save the field as null. You should be able to add in the savehandler repository a 

   protected override void BeforeSave()
            {
                base.BeforeSave();
                if (Request.Entity.personId === null) {
                    Request.Entity.personID = //create new dialog on person table and return id or give it a default id;
                }
            }

**Comment by dudeman972** [comment]
Yes i can follow the example in listing movies for a person (the hardway) to create the person record before saving employee in the database.  However, i was hoping there would be already some behavior implemented for 1 to 1 relationship.  I will wait for Volkan to voice his opinion on this before proceeding further.

**Comment by dudeman972** [comment]
Well, actually having trouble doing the manual way as well.  Unable to create a new PersonRow in SaveRequestHandler<MyRow> {
            protected override void BeforeSave()

**Comment by dudeman972** [comment]
Dear Volken,
upon your convenience i would appreciate if you can have a look at my dilemma and advise me appropriately.  Basically all i am trying to do is save a Employee and Person Entity together.  Employee table contains a personID foreign key to person table.  The edit dialog is for the employee entity which has person columns such as first and last name using expression attribute.  When i try to save, i get an error saying PersonID doesn't allow null.  I tried to overwrite the before save logic on the repository but i can't instantiate the personrow object as that class is sealed.  I was hoping there would be an easier way to do all this as opposed to manually handling all that work, similar to MasterDetail or linkingSet relations.  Please advise.  thanks.

**Comment by volkanceylan** [comment]
:) Sealed classes can be instantiated, "not subclassed"

You need to insert PersonRow yourself, with Connection.InsertAndGetID(new PersonRow { ... }), take its ID and set it to your Row.PersonID.

UpdatableExtension is as name implies, updates an extension table, it doesn't auto insert a record.

**Comment by dudeman972** [comment]
Thanks Volkan!.  I appreciate the help.  I have one general question.  Would you recommend with regards to serenity, database designs that implement inheritance such as Person table and Employee table or a single employee table that encapsulate both person and employee fields?

**Comment by volkanceylan** [comment]
Keep it sing(mp)le and stupid

**Comment by dudeman972** [comment]
hehehe Thanks Volkan.  Thumbs up!
