### ISSUE TITLE
Repository not getting a foreign field to send mail

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#2409]
Hi Guys! Anyone can put me in the right direction?. I want to query some foreign fields after save my entitiy to send a email. Actually, i want to retrieve the mail address from the user table. this is my actual code 
`

	    protected override void AfterSave()
            {

                base.AfterSave();
                base.PrepareQuery().Select(fld.UserEmail,fld.IdEstadoSolicitudDescripcion);

		if (Row.UserEmail != null && Row.UserEmail != "")
                    {
                        var emailSubject = Row.NroSolicitud;
                        var emailBody = Email;
                        Common.EmailHelper.Send(emailSubject, emailBody, Row.UserEmail);
                    }
	   }

`

The field have a value (the adress mail of the user) but Row.Usermail is ALWAYS null, i can't figure out.

**Comment by vinaykulkarni89** [comment]
#1670 see if it can help you

**Comment by Zahar661** [comment]
Working

```
 protected override void AfterSave()
            {
                base.AfterSave();
                    UserRow user;
                    using (var connection = SqlConnections.NewFor<UserRow>())
                    {
                        user = connection.TryById<UserRow>(base.Row.UserId.Value);
                    }
                    var emailSubject = "Выполнена задача:"+ base.Row.TaskId+" "+ base.Row.Name;
                    var emailBody = Serenity.Web.TemplateHelper.RenderTemplate(
                        "~/Modules/Task/Task/TaskEmailSolution.cshtml", emailModel);

                    Common.EmailHelper.Send(emailSubject, emailBody, user.Email);
            }
```

**Comment by javaman63** [comment]
@vinaykulkarni89 I read every issue available and neither have an code example

@Zahar661 Thank YOU
