### ISSUE TITLE
Question: Columns using generator?

### ISSUE THREAD

**Issue by iansilaran** [volkanceylan/Serenity#241]
How to integrate or implement value generator for columns 
e.g. XX-00001, XX-00002, etc..

**Comment by volkanceylan** [comment]
I don't have such a sample. You can do this in repository SetInternalMethods or in dialog side, by setting value in form.XYZField.Value = nextvaluefromsomeservice

**Comment by iansilaran** [comment]
This what I needed to know.. I would try this
Thank you man!

Btw love what you've done here.. such a big help.. keep it up man. thank you
