### ISSUE TITLE
Get Date

### ISSUE THREAD

**Issue by kjaninaramos** [volkanceylan/Serenity#2410]
How to insert the current date into a table from the form?

**Comment by Zahar661** [comment]
If the type of creation date

**Comment by Zahar661** [comment]
If the type of creation date xxxRepository.cs
private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                if (base.IsCreate)
                {
                    base.Row.Create = DateTime.Now;
                }
                base.Row.Change = DateTime.Now;
            }
        }
