### ISSUE TITLE
How to customize the name of PDF reporter 

### ISSUE THREAD

**Issue by CuiFY** [volkanceylan/Serenity#2414]
#Hello,
I have seen the issue of "how to customize the format of PDF reporter"(https://github.com/volkanceylan/Serenity/issues/2139 ),I tried it, and it worked. 
But I don't know how to customize the name of PDF reporter.I didn't find the field of interface.
Could you tell me how to do it?
Thank you very much!

**Comment by sayuga** [comment]
You mean the name of the output report for when exporting the pdf? 

https://github.com/volkanceylan/Serenity/wiki/Adding-PDF-Export

**Comment by CuiFY** [comment]
I 'm so sorry that I didn't explain it clearly. I know how to set up the common  output PDF of the Button.
In fact, I mean this one :
` Serene7.Common.ReportHelper.execute({
                    reportKey: 'Nomination.NominateionLetterReport',
                    download: true,
                    params: {
                        NominationId: item.NominationId
                    }
                });`
![image](https://user-images.githubusercontent.com/24852465/27461604-707f86a6-57ed-11e7-8911-a8960b18681f.png)

But,I didn't find the field of interface in ReportHelper.cs.

` export interface ReportExecuteOptions {
        reportKey: string;
        download?: boolean;
        extension?: 'pdf' | 'htm' | 'html' | 'xlsx' | 'docx';
        getParams?: () => any;
        params?: { [key: string]: any }
        target?: string;
    }`

**Comment by Estrusco** [comment]
In ReportController.cs inc Common/Reporting there is this code

```cs
        private ActionResult PrepareFileResult(IReport report, string ext, bool download,
            byte[] renderedBytes, ReportRegistry.Report reportInfo)
        {
            string fileDownloadName;
            var customFileName = report as ICustomFileName;
            if (customFileName != null)
                fileDownloadName = customFileName.GetFileName();
            else
                fileDownloadName = (reportInfo.Title ?? reportInfo.Key) + "_" +
                    DateTime.Now.ToString("yyyyMMdd_HHss");

            fileDownloadName += "." + ext;

         [...]
```

So, I not try, but if you implement ICustomFileName in your Report class and override GetFileName() you can set the output file name.

**Comment by CuiFY** [comment]
Thank you for your answer. That's exactly what I want. I just don't know where this interface is .
Thanks very much
