### ISSUE TITLE
ScriptTestsPasses test fails

### ISSUE THREAD

**Issue by isukces** [volkanceylan/Serenity#2415]
`ScriptTestsPasses` test fails when project repository is in path containing # char.
In my case it is `e:\#github\Serenity`.
 I've investigated that the problem source is inside Selenium. See [https://github.com/SeleniumHQ/selenium/issues/1938](https://github.com/SeleniumHQ/selenium/issues/1938).

**Comment by volkanceylan** [comment]
Thanks for information. I'm not sure if it is a common practice to use # in file / directory names, and wouldn't recommend anyway.
