### ISSUE TITLE
Comma Separated Quicksearch, QuickFilter, or Lookup?

### ISSUE THREAD

**Issue by mreid2005** [volkanceylan/Serenity#2416]
Is it worth the effort to try and modify Quicksearch,Quickfilter, or a lookupfilter to parse a comma separated list of values and return the results, or should I start from scratch?  Or (crossing fingers) hopefully I overlooked a sample that shows how to do this?

Thanks for any insights.

Michael

**Comment by sayuga** [comment]
are you just looking to select multiple items? you can just use the LookupEditor(typeof(MyRow), Multiple = true) to allow for multiple search items.

**Comment by mreid2005** [comment]
Sorry for the delay, we have a table with 40,000 assets stored by serial number, sometimes we may want to view a few hundred of them or more, by Serial Number, the checkbox method works fine when we only want a few of them, but gets unwieldy when wanting to do more than 20 or so.

**Comment by JohnRanger** [comment]
Hi, 

I don't fully understand your challenge / what you want to achieve but if Excel can do what you are looking for, you just can Export what you already have filtered within your Serenity app into Excel and then do a fine filtering within Excel...

Examples how to do an Export to Excel are within the Northwind samples.

With Kind regards,

John

**Comment by volkanceylan** [comment]
I don't have a recent code sample for you but one i wrote in Saltaralle, i'll paste as is:
You need to convert this to TypeScript, but you can live without it as it only handles paste into quick search input, and replaces line endings with comma etc. You also need jQuery textrange plugin for this to work.

```cs
protected override void CreateQuickSearchInput()
        {
            base.CreateQuickSearchInput();

            var input = toolbar.Element.Find(".s-QuickSearchInput").First();
            if (input.Length > 0)
            {
                var quickSearch = input.GetWidget<QuickSearchInput>();

                quickSearch.Element.On("paste", e =>
                {
                    if (!e.HasOriginalEvent())
                        return;

                    var text = (((dynamic)e).originalEvent.clipboardData.getData("text/plain")) as string;

                    if (string.IsNullOrEmpty(text))
                        return;

                    e.PreventDefault();

                    char[] splits = new char[] { '\r', '\n', '\t', ',', ' ' };

                    var parts = text.Split(splits, StringSplitOptions.RemoveEmptyEntries);
                    text = String.Join(", ", parts);

                    quickSearch.Element.As<dynamic>()
                        .textrange("replace", text)
                        .triggerHandler("change");
                });
            }
        }
```

and the code that you need in your repository.cs listhandler:

```cs
protected override void AddFieldContainsCriteria(Field field, string containsText, long? id, SearchType searchType, bool numericOnly, ref BaseCriteria criteria, ref bool orFalse)
            {
                if (containsText != null && containsText.IndexOf(",") >= 0)
                {
                    var parts = containsText.Split(new char[] { ',' },
                        StringSplitOptions.RemoveEmptyEntries)
                        .Select(x => x.TrimToNull())
                        .Where(x => x != null)
                        .Distinct();

                    if (!parts.Any())
                    {
                        orFalse = true;
                        return;
                    }

                    criteria &= field.In(parts);
                }
                else
                    base.AddFieldContainsCriteria(field, containsText, id, searchType, numericOnly,
                        ref criteria, ref orFalse);
            }
```
