### ISSUE TITLE
Can´t seem to hide Default Category

### ISSUE THREAD

**Issue by www111222333444** [volkanceylan/Serenity#2417]
How to hide the default category  from dialogs ?

**Comment by sayuga** [comment]
just tweak the .less file. You should be able to have the category element be hidden by tweaking it there.

**Comment by www111222333444** [comment]
Any tip on how to ?

**Comment by brunobola** [comment]
Just plain old CSS like this one can do the trick for section qith ref like "#FichaProjeto_Projetos_ProjetosDialog8_Category1"

Code:
`    [href^='#FichaProjeto_Projetos_ProjetosDialog8_Category1']{
        visibility: hidden;
        height: 0px; 
    }`

**Comment by sayuga** [comment]
Think of .less as .css on steroids. .less just lets you be more modular. 

Another 'cheat' to do it is to simply use something like: this.element.find(".category-title:contains('" + categoryName + "')").hidden(true); in the dialog.ts and simply add it to the onOpen()

**Comment by javaman63** [comment]
Another way to do it, it this on your xyzDialog.ts

                this.form.SomeField.element.closest('.category').toggle(false);
You took some filed under ther category you want and toggle de category to false

hope it helps
