### ISSUE TITLE
Assembly Version

### ISSUE THREAD

**Issue by CelsoGoya** [volkanceylan/Serenity#2418]
I'm trying to add assembly version information on footer, but i get 0.0.0.0 when execute at _Layout.cshtml:
``
@System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString()
``
I'd like to use assembly version information to organize development issues.

**Comment by volkanceylan** [comment]
Sorry but this is not a Serenity issues, add version information to your assembly and check .NET docs.
