### ISSUE TITLE
How to run MVC controller Index() action by using NavigationItems.

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#242]
How to run MVC controller Index() action by using NavigationItems.
[assembly: NavigationMenu(5100, "Test", icon: "icon-anchor")]
[assembly: NavigationLink(5200, "Test/Test", typeof(Serene.Controllers.TestController), icon: "icon-wallet")]

They shows message "Route attribute for System.Web.Mvc.ActionResult Index() action of Serene.Controllers.TestController controller is not found!"

**Comment by volkanceylan** [comment]
Add Route attribute to your TestController or use Url parameter of NavigationLink instead of controller.

**Comment by Olricz** [comment]
You can look @laxmanp 

![1](https://cloud.githubusercontent.com/assets/16984654/13003658/958ed582-d17f-11e5-9a4a-ceb6acc8ed6d.JPG)

![2](https://cloud.githubusercontent.com/assets/16984654/13003663/9e0b08d4-d17f-11e5-9a5d-0fd4854f3268.JPG)
