### ISSUE TITLE
Failed build after publish

### ISSUE THREAD

**Issue by sfackrell** [volkanceylan/Serenity#2421]
When you publish .NET Core VS2017, Visual Studio creates a `\obj\Release\netcoreapp1.1\PubTmp\Out` which will contain the compiled `project.d.ts`.  If you then rebuild the solution `dotnet sergen clienttypes` will fail with hundreds of 

`TS2300	Build:Duplicate identifier 'xForm'`

errors because it's picking up this temp file when harvesting all of the `*.ts` files.  The ` \obj\Release\netcoreapp1.1\PubTmp` isn't cleared with a solution clean either so you have to manually delete it each time in order to be able to build again. 

Would be nice if the standard template was changed so that `"obj/"` was added to the `exclude` array in `.tsconfig` - then the problem goes away

**Comment by volkanceylan** [comment]
Thanks for reporting, i will add it to default exclude array.
