### ISSUE TITLE
If you'd like to run migrations on this database, remove the safety check in SiteInitialization.RunMigrations method

### ISSUE THREAD

**Issue by dansef** [volkanceylan/Serenity#2422]
I have created a serenity asp.net core app, when i run and try to login i get: If you'd like to run migrations on this database, remove the safety check in SiteInitialization.RunMigrations method. What is the way forward coz i cannot get the SiteInitialization.RunMigrations to edit

**Comment by sebacamino** [comment]
How you solve this? Thanks

**Comment by Eric-Zhong** [comment]
I Solved. 

`            // safety check to ensure that we are not modifying an arbitrary database.
            // remove these lines if you want ETOPMS migrations to run on your DB.
            // 在这里它会判断数据库名是不是 "ETOPMS_Default_v1" 和 "ETOPMS_Northwind_v1". 
            // 如果上面这两个数据库名称没有包含在 ConnectionString中，说明是全新的数据库，需要跳过 Migration 操作.
            if (!isOracle && cs.ConnectionString.IndexOf(typeof(DataMigrations).Namespace +
                    @"_" + databaseKey + "_v1", StringComparison.OrdinalIgnoreCase) < 0)
            {
                SkippedMigrations = true;
                return;
            }
`
If you create a database for serenity, the database name should be "<Project Name>_default_v1". 
Change the connection string in appsettings.json config file. For example: 
`    "Default": {
      "ConnectionString": "Data Source=127.0.0.1;Database=MYTEST_Default_v1;user id=sa;password=sa",
      "ProviderName": "System.Data.SqlClient"
    },
`

**Comment by mh-hassan** [comment]
I think  the database name be like this 

Namespace_DatabaseName_V1
