### ISSUE TITLE
custom calculated column

### ISSUE THREAD

**Issue by wimdevriendt** [volkanceylan/Serenity#2425]
Hi I have a datacolumn which is binary
        public Stream LoRaData { get; set; }

now I need to convert this to a hexadecimal string
I want to add a new column with the hexvalue which is retrieved when getting the list
how can I do this ?

**Comment by volkanceylan** [comment]
I'm not sure but try converting it to byte[] and ByteArrayField

**Comment by JohnRanger** [comment]
Hi,

is it not possible for you to do this directly within SQL Server and make this a calculated field within your table? (I had this to do to give the amount of links from a link table to a given Record in the main table).

Then you can handle it within Serenity just like a normal field and offload the calculation work to the SQL Server.

An example how to create a function within MS SQL Server and then create a calculated Field from it is here: [https://stackoverflow.com/questions/8725629/how-to-create-a-calculated-column-in-a-sql-server-2008-table](url)

With Kind regards,

John
