### ISSUE TITLE
Filter working slow to a level of Timeout

### ISSUE THREAD

**Issue by aksingh1979** [volkanceylan/Serenity#2426]
Hi All,

I tried different formats of filter in order to resolve the issue but problem continues to be same. I alternatively checked that the Query received by SQL Server is very fast. The moment filter is enabled system gives the timeout. Below you can see my different attempts to solve the issue.

Please advice.

Thanks in anticipation.

protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);
                var FYObj = FinancialYearRow.GetCurrentFinancialYearObject();
               //AccountUtil.ApplyFYFilter(query, fld.CreateDate);
               // //query.Where((new Criteria(fld.FYNoName) == FYObj.NameForInvoice));
               // //if(fld.IsPendingForPayment.IsNull())
               // string fldName = fld.CreateDate.ToString();
               //// DateTime d = Convert.ToDateTime(t);
               // //if(.IsPendingForPayment..ToInt32()==1)
               //   query.Where("jVoucher.FinancialYear="+FYObj.Id);
               // //query.Where(.Where((new Criteria(d.ToSQLDateFormat()) >= convert(date,FYObj.StartDate.ToSQLDateFormat(),102) & new Criteria(d.ToSQLDateFormat()) <= FYObj.EndDate.ToSQLDateFormat()));
               // //else if (fld.IsPendingForPayment.ToInt32()==1)
               // //    query.Where((new Criteria(fld.CreateDate) >= FYObj.StartDate.ToSQLDateFormat() 
               // //                 & new Criteria(fld.CreateDate) <= FYObj.EndDate.ToSQLDateFormat()
               // //                 & new Criteria(fld.IsPendingForPayment) == 1
               // //                 ));
                
            }

**Comment by volkanceylan** [comment]
Check your SQL that is submitted by SQL profiler etc. Filter doesn't do anything special.

**Comment by aksingh1979** [comment]
Thanks Volkan,

I checked but when I remove the filter and run the query directly with desired parameter it works much much faster. I mean if I run the query which i get via Profiler in SQL directly it is much much faster.

Please advice, its still a pain point

**Comment by volkanceylan** [comment]
That's NOT possible, there is something you are missing.
