### ISSUE TITLE
Can we transfer Serenity Application to VB.NET

### ISSUE THREAD

**Issue by zeeshangrw** [volkanceylan/Serenity#2427]
Dear Admin,

I feel comfortable in VB.NET. Is it possible to convert serenity application in VB ?

Regards,
Zeeshan

**Comment by sayuga** [comment]
Nothing is impossible. I'm sure it can be done but that would be a pretty large task considering you'd have to rework large amounts of the mixed in items. For one you'd likely have to make a module to be able to mediate between the existing build of Serenity, which is heavy c# and typescript, and then make those visible and usable on the VB.net side. There are ways to do it but it'd be a chore if I'm not mistaken. This sounds like something you'd likely have to do yourself. 

https://stackoverflow.com/questions/2903430/using-c-sharp-and-vb-net-in-one-solution
