### ISSUE TITLE
Adding movies from person dialog - Help from serenity guide

### ISSUE THREAD

**Issue by Soufraz** [volkanceylan/Serenity#2429]
I am studying the Serenity and I am following the guide in https://volkanceylan.gitbooks.io/serenity-guide/.

In section "Listing Movies in Person" there is a feature that adds to the Movies tab inside the create form of Person. I would like to know if it is possible to use the Movies tab added to create a Movie related with Person direct from that modal. Here the section that I am following:
Https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/listing_movies_in_person_dialog.html

Trying to use other words to clarify, I would like to open the modal person, click on Movies tab and from the Movies tab create a Movie related with the person that I am editing.

I have the tab Movies working normally already. In which section should I search for or what is the name of this feature in Serenity?

Thanks advance.

**Comment by javaman63** [comment]
The "thing"you want to do, it is explain here

https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/listing_movies_in_person_dialog.html

**Comment by Soufraz** [comment]
Almost, the create button doesn't work. This section is just to list movies inside person. Look that the last step, is remove create button.

**Comment by javaman63** [comment]
There are many examples of what you want to accomplish. You have to look for examples of MasterDetail Relation. 
What you want to do is start from the movies to create people. The example is in reverse, it start with  the movies and shows people. You should face the example in reverse and use as a first form the one of people and then relate the TAB with the one of Movies
