### ISSUE TITLE
Hiding div 

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2430]
How can I reference a Serenity div through typescript?

What I'm trying to do is hide a div, depending on the value of a form field. Serenity does not fill in the "name" or "id" attribute.

Any idea how to do this?

**Comment by dfaruque** [comment]
what are you exactly trying to do?

anyway, if you want to hide a field div, you may use

`this.form.someEditor.element.closest('.field').hide();`

**Comment by alexneocart** [comment]
Thanks, so much
