### ISSUE TITLE
This.isNew not working properly.

### ISSUE THREAD

**Issue by zKarp** [volkanceylan/Serenity#2431]
When using the property This.isNew in a dialog, the result is always TRUE no matter if it is an inserted record or update.

[See sample ](http://serenity.is/demo/BasicSamples/GetInsertedRecordId) where issue occurs.

**Comment by dfaruque** [comment]
this.isNew is a function. so call this like 

this.isNew()

**Comment by Estrusco** [comment]
Also, where you have make the test? I have try now, and the function return the correct value in afterLoadEntity

```ts
protected afterLoadEntity() {
    super.afterLoadEntity();

    var testNew = this.isNew();
}
```

**Comment by volkanceylan** [comment]
Yes, that's a function, could be a property, but has to stay for now backward compability

**Comment by zKarp** [comment]
Thanks, not sure how I missed that.
