### ISSUE TITLE
How to use localization on client side (TS)

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2432]
Dear all,

under Saltarelle-Serenity, we could do 

new LocalText("Dialog.something.AddButton") 

and it reteived the real text from the JSON text translation files under scripts/site/Texts/...

Unfortunately I don't find an equivalent for this Feature within Serenity client side (TS).

Not under the  Q. nor under Serenity Name space.

As the Dialogs and Grids generated with sergen do have localization, the Feature is surely present.

How can I Access the localization functionality in TS client side Serenity?

Hint: The Serenity guide does not explain, how to do client-side localization (only server-side localization). Also I didn't find any examples in Northwind or Basic Samples.

Can anybody point me in the right direction?

Thanks and with Kind regards,

John

**Comment by dfaruque** [comment]
try Q.text("Dialog.something.AddButton")

**Comment by JohnRanger** [comment]
Hi dfaruque,

perfect! Exactly what I was searching for. Thank you very mcuh for your fast help. 🥇 

With Kind regards,

John
