### ISSUE TITLE
LoadbyIdandOpenDialog saves as Creat not as Update

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#2433]
Dlg. LoadbyIdandOpenDialog (12345) is retrieving the correct record but when I click save it looks for Create not Update.

**Comment by Estrusco** [comment]
Check sample CustomLinksInGrids. This works fine.

![loadbyidandopendialog](https://user-images.githubusercontent.com/16304015/27624724-36c92e78-5be2-11e7-8d31-84706b22e1fb.JPG)

**Comment by volkanceylan** [comment]
Check IdProperty of your column.

**Comment by volkanceylan** [comment]
of your Row
