### ISSUE TITLE
BigInt Id Column Rounding

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#2434]
I have an Id Column which is SQL type BigInt.  When I select from the table in serenity, it rounds the Id (1330100000000000002 to 1330100000000000000).  When I try to edit a row, it tries to edit the rounded row which fails because the rounded key is not a key.  The key is Int64 in serenity.  Is there a fix for this?

**Comment by volkanceylan** [comment]
Javascript number type is double, not BigInt, so you'll have such errors very often unless you fix your IDs to more managable range.
