### ISSUE TITLE
sergen V2.9.2x; Option Create Lookup; wrong Module when LookupScript in different Module

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2436]
Good morning Volkan,
as usual, ist a great pleasure to code a Project with your excellent Framework. 👍 

**Environment description:**
(Serenity V2.9.23, VS 2017 CE)
Today with sergen I generated the usual set of "grid-dialog-row-etc" files from a table but added the option: **generate lookup**.

So far this has created the lookupeditor entry within the XYZrow.

My freshly created XYZrow.cs is by purpose in another Module than the ABCrow.cs where the Lookup data is coming from. --> Lets say: XYZrow is in ModuleXYZ where as the ABCrow.cs is in ModuleABC.

**Error Description**
According to my understanding, here is now an error within sergen: Sergen has created the LookupEditor entry within the XYZrow.cs like this:

```cs
[LookupEditor(typeof(ModuleXYZ.Entities.ABCRow), InplaceAdd = true)] 
```
But this should actually be:

```cs
[LookupEditor(typeof(ModuleABC.Entities.ABCRow), InplaceAdd = true)] 
```

May I kindly ask you to check this?

Thank you very much and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Sorry, this option is added by somebody else. That's not one of my favorite features as is.

**Comment by JohnRanger** [comment]
Hi Volkan,
thanks for your feedback. May I ask, how I have to address this issue to the correct person (and if you know - who is the correct person for that)?

With kind regards,

John

**Comment by volkanceylan** [comment]
I recommend not using that feature. I don't remember who added it.

**Comment by JohnRanger** [comment]
Hi Volkan,

ok, it is not a very important Feature and I have no Problems to create that entry manually.

With Kind regards,

John
