### ISSUE TITLE
cascading dialog windows

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#2437]
Brother Volkan,
Is there a way to open each new popup dialog slightly offset both vertically and horizontally from the previous popup dialog window.  This will give user an idea/context of all the previous windows. Assuming all windows will be styled to have fixed height and width
Thanks

**Comment by Estrusco** [comment]
See here https://github.com/volkanceylan/Serenity/issues/239

**Comment by volkanceylan** [comment]
If only could people thank and close issue. Thanks @Estrusco

**Comment by dudeman972** [comment]
Brother Volkan,  
I am truly very sorry.  It is truly lazyness on my part.  I should have as you mentioned above thanked and closed the issue.  Thanks Estrusco. Too late to close as its already closed but for future I promise to improve myself with regards.
