### ISSUE TITLE
Deployment Errors

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2438]
Hello Volkan and Sayuga,
Please serenity application has been deployed in a hosting space and the log in page is showing blank. When I inspected it from chrome debugger, the attached are the errors which show.
![errors](https://user-images.githubusercontent.com/14317420/27681213-f784822c-5cad-11e7-94d1-7d1ae129cd0d.PNG)

**Comment by volkanceylan** [comment]
We are not helpdesk for your iis config

**Comment by gfo2007** [comment]
Wow.I wasn't expecting this kind of answer. I was only trying to find out if someone here had experienced similar issues while deploying a serenity application because this is my first deployment on a production server.
