### ISSUE TITLE
basicSample - Grouping and Summaries In Grid (sort grouped column)

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#2439]
Hi, 
in my local solution or in "http://serenedemo.azurewebsites.net/BasicSamples/GroupingAndSummariesInGrid" the example "BasicSamples/GroupingAndSummariesInGrid" (after group the grid by category) is not possible to sort by column category.
But the same example in "http://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid" this work fine!!!!

**Comment by sayuga** [comment]
you need to put more info than just, 'mine doesn't work but the sample does'. What does your console say? Are there any errors in the log or console? Do you have any additional custom code that could be affecting the sort?

**Comment by linpiero** [comment]
In log or console no errors!!! I've created a solution from **scratch without making any changes**  with the default template SERENE
