### ISSUE TITLE
Filter LookupEditor

### ISSUE THREAD

**Issue by evagelos21** [volkanceylan/Serenity#2440]
Hi to all,
This is my first attempt to serenity.
I have a LookupEditor with values from DB. The table name is "CS2" and the fields are "CS2", "Item", "Code", "Qty"
I have try everything (I think) in order to filter the values from CS2, depending the "Item" field value.
This value can be change by the user.
Any help please?
thanks in advance

**Comment by Estrusco** [comment]
Try with this in xyzDialog.ts constructor. Note that in your Row, the Item field must have LookupInclude attribute

```ts
constructor() {
    super();
    
    this.form.yourItemField.change(e => {
                var lookup = Q.getLookup<CS2Row>("CS2LookupKey");
                this.form.CS2LookupField.filterField = "Item";
                this.form.CS2LookupField.filterValue = this.form.yourItemField.value;
    });
}
```

**Comment by evagelos21** [comment]
Thank you for your answer
It is not stopping in my break-point.
My Row:
`    
...

        protected form = new SalesLinesForm(this.idPrefix);
        constructor() {
            super();

            this.form.Item.change(e => {
                var lookup = Q.getLookup<Cs2Row>("Item");  <== No Break point
                //this.form.CS2LookupField.filterField = "Item";
                //this.form.CS2LookupField.filterValue = this.form.yourItemField.value;
            });
...
`
and in my SalesLinesRow
`
        [LookupInclude, LookupEditor(typeof(Cs2Row))]
        [DisplayName("Size"), Column("CS2")]
        public String Cs2
        {
            get { return Fields.Cs2[this]; }
            set { Fields.Cs2[this] = value; }
        }
`

**Comment by evagelos21** [comment]
OK!
I managed
Thanks a lot!!!
