### ISSUE TITLE
Deletes on Updates 

### ISSUE THREAD

**Issue by fernandocordero** [volkanceylan/Serenity#2442]
Guys,

I have a dialog window with tabs,  one tab holds the header entity, the other the detail. Now if I use the detail tab and add a new record and then (without closing the dialog) I click[Update] on the header entity tab, the record I just added gets removed. If I close the dialog before doing an update of the header entity and i open that  row again and click [Update] then the new detail record remains. What can be producing this odd  behavior? It seems that after I add the new detail record something is not been "cleared" from the previous action like some sort of caching. Any ideas?
Thanks in advance!

**Comment by javaman63** [comment]
Perhaps this can help you
http://serenity.is/demo/BasicSamples/OtherFormInTabOneBar

**Comment by fernandocordero** [comment]
Found it , just needed to use the **Updatable(false)** decorator.
