### ISSUE TITLE
Thumbnail doesn't keep proportions

### ISSUE THREAD

**Issue by chekyassine** [volkanceylan/Serenity#2443]
Hi ,
I think It would be preferable if thumbnails are created of maximum width or height and cropped if necessary

**Comment by Felix-ZL** [comment]
check out about "bootstrap grid system",

**Comment by volkanceylan** [comment]
Thumbnails keeps propotions.

**Comment by chekyassine** [comment]
Hi, please check out this picture I've put in products page in serenity demo : 
[original](http://serenity.is/demo/upload/ProductImage/00000/00000017_lec3vxs7j7bfu.jpg)
[thumbnail](http://serenity.is/demo/upload/ProductImage/00000/00000017_lec3vxs7j7bfu_t.jpg)

Am I missing something ?

**Comment by volkanceylan** [comment]
There is nothing wrong, it takes center, works as designed
