### ISSUE TITLE
How to send pdf report as email attachment

### ISSUE THREAD

**Issue by slang123** [volkanceylan/Serenity#2445]
Hi, Is there an easy way to attach a generated pdf report to an email?

**Comment by vinaykulkarni89** [comment]
In Modules/Common/Reporting/ReportController you can customize code for attachment, you can use MemoryStream for adding renderedBytes as attachment

**Comment by slang123** [comment]
Yes i did modify the controller to suit my need. I just figured there was a tool for this somewhere, and I just couldn't find it :)

**Comment by kjaraa** [comment]
Hi everyone,
I've the same problem, but I've no idea how to do that. Could you give me any example ?

Thanks all
