### ISSUE TITLE
How to change Save button location

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2446]
Hi,
I am a newbie to Serenity, Please tell me how to change the Save Button from top of the griddialog to bottom of the griddialog.

thankx

**Comment by Estrusco** [comment]
You can use css or jQuery to move items in the dialog. Search for .s-DialogToolbar class to get toolbar

**Comment by srinivas1910** [comment]
Iam  able to find out the .s-DialogToolbar class, not able to change the save button from top of the form to bottom of the form as every time i have to go to top to save the form as it is having around 25 fields in the form. Please help with a little bit of procedure to get it done.
Thank you

**Comment by Estrusco** [comment]
In your xyzDialog.ts constructor, some like this

```ts
    constructor() {
        super();

        var tb = this.element.find('.s-DialogToolbar');
        this.element.append(tb);
    }
```

**Comment by dfaruque** [comment]
change the following file 
Views\Templates\EntityDialog.Template.html
with the following content.
```
<div class="s-DialogContent">

    <div class="s-Form">
        <form id="~_Form" action="">
            <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                <div id="~_PropertyGrid"></div>
                <div class="clear"></div>
            </div>
        </form> 
    </div>

    <div id="~_Toolbar" class="s-DialogToolbar">
    </div>
</div>
```

**Comment by srinivas1910** [comment]
Hi  Estrusco,

constructor() {
        super();

        var tb = this.element.find('.s-DialogToolbar');
        this.element.append(tb);
    }
 
This Worked form me. But I want this for all the forms. Where should i implement this to get it on all the forms. Thank you

**Comment by Estrusco** [comment]
The solution proposed by @dfaruque is useful to you.

**Comment by srinivas1910** [comment]
Thank you @Estrusco  and @dfaruque  I Got the solution.

**Comment by gowthamcarmel** [comment]
> Thank you @Estrusco and @dfaruque I Got the solution.

Can you please tell how to keep both in top and bottom of the dialog
