### ISSUE TITLE
Quickfilter

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2449]
Hi,
How can i place the quick filter field contant as the title for pdf exporter.

thanks

**Comment by JohnRanger** [comment]
Hi,

can you explain your challenge a bit more in Detail please - so we can better understand what you want to achieve?

With Kind regards,

John

**Comment by srinivas1910** [comment]
Hi @JohnRanger

When a grid is filtered with xyz city. The title of the pdf exporter must be shown like Dealers of xyz city.


Thanks,
Srinivas

**Comment by JohnRanger** [comment]
Hi,

on a high Level, you would do it like this:

(1) in the onClick Event of the PDF exporter button, you would query the filter Dropdown for it's value (it will be the ID of the corresponding record in the City table)
(2) Then you would query the City table for this record and store the Name of the City from this record in a variable
(3) then you would modify the title of the Report by modifying the reportTitle property.

While I was trying to basically test this, I have found an error while changing the reportTitle. Currently the reportTitle can be changed but it also always influences the fileName of the PDF. This means that in the title you must always add ".PDF" at the end or the file will not open in the web browser. So your Report will always have a title of "blabla.pdf".

I have reported this as an issue some minutes ago.

Hope this gives you some idea how to Approach the challenge.

With Kind regards,

John

**Comment by srinivas1910** [comment]
Hi @JohnRanger ,

Thank you John will try and let your know the result.


Regards,
Srinivas

**Comment by rajashekargoka** [comment]
how to bind normal textbox with data in serenity

**Comment by JohnRanger** [comment]
Hi Srinivas,

as I wanted to learn something, I have worked out a solution for this.

(1) you Need to get the fixed PDFExporterHelper.ts from my repository (I have created a pull request on Volkans master repository so that the fix gets integrated within Standard serene): [https://github.com/JohnRanger/Serene/pull/1/commits/d5edd34d47ef4e4ab0951d6db83acdff77b99773](url)

My example works with the northwind customer grid and the PDF exporter there.

(2) You have to replace CustomerGrid.ts with the following Code:

```ts
namespace test2.Northwind {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.filterable()
    export class CustomerGrid extends Serenity.EntityGrid<CustomerRow, any> {
        protected getColumnsKey() { return "Northwind.Customer"; }
        protected getDialogType() { return <any>CustomerDialog; }
        protected getIdProperty() { return CustomerRow.idProperty; }
        protected getLocalTextPrefix() { return CustomerRow.localTextPrefix; }
        protected getService() { return CustomerService.baseUrl; }

        // *** We need a in-class variable to store the current value of the city filter dropdown when it changes ***
        private CityName = "";

        constructor(container: JQuery) {
            super(container);

        }

        // *** We have to override getQuickFilters in order to manipulate the filter handler of the city quickfilter ***
        protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            // get quick filter list from base class, e.g. columns
            let filters = super.getQuickFilters();

            let filter = Q.first(filters, x => x.field == "City");  // *** The city filter is special because it does not derive its values from a real xyzRow but its values are collected from all customers (see Northwind/Customer/CustomerCity.cs) ***

            filter.handler = h => {
                this.CityName = h.value;    // *** We want to store the selected value from the city quickfilter in the CityName private string field of this grid class ***
                if (h.active) {
                    h.request.Criteria = Serenity.Criteria.and(h.request.Criteria, [["City"], '=', h.value]); // *** We need this in order to filter the customer's city when something in the city quickfilter dropdown has been chosen ***
                }
            };

            return filters;
        }

        getButtons() {
            var buttons = super.getButtons();

            buttons.push(test2.Common.ExcelExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: 'Northwind/Customer/ListExcel',
                separator: true
            }));

            // *** We have to create our own PDF button as the one from PDF helper does not support custom onClick routine ***
            let pdfbutton : Serenity.ToolButton = {
                title: 'to PDF' || '',
                hint: 'Export to PDF',
                cssClass: 'export-pdf-button',
                onClick: () => {

                    // *** Compose your report title string ***
                    let ReportTitle = "Customers of " + this.CityName;

                    // *** Set the required PDF export options (including our composed Report title) ***
                    let pdfexportoptions: test2.Common.PdfExportOptions = {
                        grid: this,
                        onViewSubmit: () => this.onViewSubmit(),
                        reportTitle: ReportTitle,
                        fileName: "jojo123.pdf",    // *** Either use here a constant or compose the filename dynamically ***

                    };

                    // *** Call the PDF exporter ***
                    test2.Common.PdfExportHelper.exportToPdf(pdfexportoptions);
                }
                //, separator: pdfexportoptions.separator
            };

            buttons.push(pdfbutton);

            return buttons;
        }

    }
}
```
Hint: Test2 is the Name of my Project - replace it with your Project.

Hope this helps.

With Kind regards,

John

**Comment by JohnRanger** [comment]
@rajashekargoka ,

as your question is unrelated to the original Topic here in this issue I have downvoted your question here in this thread to Keep a bit of order here in the forum.

Please ask unrelated questions in it's own issue so it can be seen by all and eventually answered.

With Kind regards,

John

**Comment by srinivas1910** [comment]
Thank you @JohnRanger ,

For your great help will implement this in to my project and let you know the Result.


Regards,
Srinivas
