### ISSUE TITLE
How to call repository method from MVC controller?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#245]
Every repository method has connection parameter. When I call service directly from service url, framework handle connection parameter. But i want to call from MVC controller class how to get/create  connection parameter?

And... why serenity override all MVC coding style (or philosophy)? Model (M) is perfect usefull (of course) but It seems like controller (C) is useless, view (V) is useless in serenity. 

Is creating TemplateDialog, PropertyDialog etc easier/faster/better then coding cshtml with razor syntax? 

May be this is not suitable place to discuss in detail but i wonder your philosophy.

**Comment by volkanceylan** [comment]
You can use SqlConnections.NewByKey or NewFor methods to create connections.

Every part of MVC is there just not in traditional sense. And you are not prevented from using traditional pages.

Listing editing pages are always very similar and using traditional MVC pages would lead to too many spagetthi pages containing useless html markup with inline scripts. For such pages i prefer domain oriented, component based, declarative ui and reusable service code to basic mvc. Anything you write in actions, views are tied to that specific page.

**Comment by ademc** [comment]
Thank you for answer.

I agree with you. 

> For such pages i prefer domain oriented, component based, declarative ui and reusable service code to basic mvc. Anything you write in actions, views are tied to that specific page.

Serenity provide these things very good of course. But I guess this (serenity) style coding advice/force moving business rules to script side. We are putting (almost)  everything (UI operations, some right contraints, filter operations, even we can send all standart query parameters we want for listing etc)  in Project.js file an groving it.

I know sounds like this is bad critics, no i only want to hear your solution, want to understand the solution, correct my own misunderstanding.

By the way english is very very bad communication tool for me, so sorry :)

**Comment by volkanceylan** [comment]
Yes moving UI application logic to script side is a very good thing and its the trend.Users has free resources for you to use. Otherwise server will have to do jobs other than responding to service requests.

Growing application (script) size is a concern but when properly mininified, compressed and cached its not a big deal. My biggest app script size is 250k gzipped which has almost 500 pages. This is acceptable even in mobile.
