### ISSUE TITLE
How to open custom .cshtml page in serenity dialog

### ISSUE THREAD

**Issue by laxman24x7** [volkanceylan/Serenity#2451]
Hello sir,

I want to open custom .cshtml page in serenity dialog and call jquery events for populating or bind data by using serenity architecture only dialog content is different for making dialog UI attractive and some more html UI controls. How to do? Please give me some sample code.

Thanks,
Laxman Patil

**Comment by sayuga** [comment]
Look at the ChartInDialog sample of the Basic Samples. It's essentially the same thing. Just remove the chart code on the ChartDialog.ts and add your reference to the custom .cshtml.

**Comment by volkanceylan** [comment]
There is also a Q.iframeDialog method, look at its source, this is actually about jQuery / jQuery UI
