### ISSUE TITLE
how find changed value when SaveResponse Update 

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2455]
I want to compare the initial value of request.Entity.cityid with the value in the update order in the "SaveResponse Update" command and how to do it, how do I do it?

**Comment by awesomegithubusername** [comment]
Try this:
 In your xyzRpository.cs file:
Override one of the methods of MySaveHandler (BeforeSave(),SetInternalFields()...)
```c#
private class MySaveHandler : SaveRequestHandler<MyRow (
 {
      protected override void SetInternalFields()
      {
          base.SetInternalFields();
          if (Old.fieldXYZ != Row.fieldXYZ)   
           {
                        //something something
           }
      }
}
```

**Comment by volkanturk** [comment]
thanks :)

**Comment by volkanturk** [comment]
Sorry, how can use this code in xyzendpoint.cs ?

**Comment by awesomegithubusername** [comment]
Is there any reason you don't wanna use the repository?

**Comment by volkanturk** [comment]
I would like to be able to update with webservice. According to the result returned from webservice, the update will be successful or prevented. I sent the following code as an example, how can I proceed like this?

xyzendpoint.cs

`[HttpPost, AuthorizeUpdate(typeof(MyRow))]
        public SaveResponse UpdatebyWebService(SaveRequest<MyRow> request)
        {
            //create webservice
            webservis.temp b = new servis.temp();


            bool resutboolen;
            //set resutboolen value
            if (Old.Onaydurumu != Row.Onaydurumu)
            {
                resutboolen = true;
            }
            else
            {
                resutboolen = false;
            }
            //send webservis return result
            string result=   b.UpdateTable(resutboolen);
            if (result == "Ok")
            {
                return new SaveResponse();
            }
            else
            {
                return null;
            }
 
        }`

**Comment by awesomegithubusername** [comment]
You can retrieve the row from the database and compare the two values:
var oldRow = retrieve your row here
 if (oldzRow.fieldXYZ == request.Entity.fiekdXYZ)
{
}

**Comment by volkanturk** [comment]
Thank you very much for your support:)
