### ISSUE TITLE
"Generated PDF file is empty" error when accessed from the Internet

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#2456]
Hi everyone!

PDF generator works fine from a local address (Intranet). However, I'm getting this error from the Internet for the same report:

`[InvalidOperationException: Generated PDF file is empty!]
   Serenity.Reporting.HtmlToPdfConverter.Execute() +1856
   MultiTenancy.ReportController.RenderAsPdf(IReport report, String key, String opt) +369
   MultiTenancy.ReportController.Execute(String key, String opt, String ext, Boolean download, Boolean printing) +361
   lambda_method(Closure , ControllerBase , Object[] ) +201
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +37
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +584
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +167''`

Is there a configuration setting I am missing?

**Comment by vinaykulkarni89** [comment]
If you have deployed it, then you need to use another version of wkhtmltopdf.exe

Use below link to download:
https://drive.google.com/file/d/0BzI_u_O3vUM1aEppb3ZVZXNsc28/view

**Comment by awesomegithubusername** [comment]
@vinaykulkarni89 : Thanks, but that didn't work.

**Comment by qtgh1** [comment]
We had the same problem, but it was not a serenity issue. 

You have to ensure that the URL you use to access the application is accessible from server itself. 

For example if you use https://app.example.com/serenity/ you have to ensure that this url can be accessed from the server hosting the application.

In our case app.example.com resolved to the public/external ip of our internet connection. Due to limitations of our internet router it was not possible to access the public/external ip address from internal computers. The wkhtmltopdf.exe request timed out and resulted in "Generated PDF file is empty!" error. 

As soon as we setup our internal DNS server to resolve app.example.com to the internal ip address of our server PDF report generation worked as expected.

**Comment by awesomegithubusername** [comment]
@qtgh1: Thanks for your comment. I'll try it and let you know if it solved the issue.
