### ISSUE TITLE
WebCam Integration

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2457]
Hi,
Is there an example or procedure to integrate Webcam to take the picture of a user to the application. 

Thank you

**Comment by vinaykulkarni89** [comment]
http://www.c-sharpcorner.com/UploadFile/4d9083/capturing-image-from-web-cam-in-Asp-Net-mvc139/

**Comment by rolembergfilho** [comment]
Hey @srinivas1910 and @vinaykulkarni89 ,

how you did this webcam integration?

could you give me a help?
