### ISSUE TITLE
Penetration testing

### ISSUE THREAD

**Issue by MsDanglar** [volkanceylan/Serenity#2458]
Hi guys! Did anyone have a genric solution for limiting the access at the data entities (Row) level. 

For example, if i have a Product entity with the "UserId" property and i want to limit the access to it (by the current user) in each of the CRUD operations in the repository.

It will be great to have a solution for that in a generic and infrastructure level.
Thank you for your help guys.

**Comment by wldkrd1** [comment]
Built-in? No. You can create your own attribute to decorate your entity and create associated behaviors which overrides OnPrepareQuery() to do any filtering you want for List, Retrieve, Save and Delete. Check the guide for details (I believe there is something similar with the multi-tenancy example)

**Comment by in32bit** [comment]
We did it like this:

namespace Serenity.Services
{
    public class BaseDeleteRequestHandler<MyRow> : DeleteRequestHandler<MyRow> where MyRow : Row, IIdRow, new()
    {
        protected override void ValidateRequest()
        {
            base.ValidateRequest();
            var user = (UserDefinition)Authorization.UserDefinition;
            if (this.Row["CompanyId"] != null && Convert.ToInt64(this.Row["CompanyId"]) != user.CompanyId)
                Authorization.ValidatePermission(PermissionKeys.Security);
        }
    }

    public class BaseRetrieveRequestHandler<MyRow> : RetrieveRequestHandler<MyRow> where MyRow : Row, IIdRow, new()
    {
        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            var user = (UserDefinition)Authorization.UserDefinition;
            if (!Authorization.HasPermission(PermissionKeys.Security) && this.Row.GetFields().Count(f => f.Name == "CompanyId") == 1)
            {
                var flds = this.Row.GetFields();
                query.Where(flds.FindField("CompanyId") == user.CompanyId);
            }
        }
    }

    public class BaseSaveRequestHandler<MyRow> : SaveRequestHandler<MyRow> where MyRow : Row, IIdRow, new()
    {
        protected override void ValidateRequest()
        {
            base.ValidateRequest();
            if (IsUpdate)
            {
                var user = (UserDefinition)Authorization.UserDefinition;
                if (Old["CompanyId"] != null && Convert.ToInt64(this.Row["CompanyId"]) != user.CompanyId)
                    Authorization.ValidatePermission(PermissionKeys.Security);
            }
        }
    }

}
