### ISSUE TITLE
Possible bug: Dropdown within Dialog not populated with current value when filtering Lookup with filterfield/Filtervalue

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2459]
Good evening Volkan,

This is with SF 2.9.24.
I have a standard lookup (defined with Lookupscript in XYZrow.cs and lookupeditor in XYZform.cs). 

As long as I don't filter this lookup script with filterfield, the Dropdown (the one visible value in this form field - when the form is first displayed) within the XYZdialog.cs is properly populated with the representation of the current value of that field when I edit a record/row via click on EditLink.

But the moment I filter the lookup with adding FilterField, Filtervalue within the AfterLoadEntity event (because I Need to get the filtervalue from the current row) the Dropdown only shows "-- select --", even though all correct items are there when I click on the Dropdown (e.g. all the expected (filtered) entries are there (including the one which's value is already present within the underlying form field) and I successfully can select one of them and when I click "save" the DB gets correctly updated with it.

The XYZdialog.cs looks like this:
```cs
protected afterLoadEntity() {
            super.afterLoadEntity();

            var wsgroupid = Q.toId(this.form.Workstationgroupid.value); // *** Here I get first time access to the desired value ***

            this.form.LinkQueuesId.filterField = MapPrintQueues.LinkQueuesWithWorkstationgroupsRow.Fields.Workstationgroupid;
            this.form.LinkQueuesId.filterValue = wsgroupid;
            //this.form.LinkQueuesId.cascadeField = MapPrintQueues.LinkQueuesWithWorkstationgroupsRow.Fields.Workstationgroupid;
            //this.form.LinkQueuesId.cascadeValue = wsgroupid;
        }
````

**Question:**
Is this behavior "by design" and do I have to tell the form field to refresh iits visualization after filtering with filterfield or is this a bug?

If I have to tell the form field to refresh ist visualization, how can I do this?

Thanks for your valuable feedback and

with Kind regards,

John

**Comment by JohnRanger** [comment]
I will answer my own question as refernce for others:

I had to add the following line within the afterLoadEntity Event to explicitly set the value within this field:

```ts
this.form.LinkQueuesId.value = this.get_entity().LinkQueuesId.toString();;
```

The full afterloadentity Event code looks now like this:

```ts
protected afterLoadEntity() {
            super.afterLoadEntity();

            var wsgroupid = Q.toId(this.form.Workstationgroupid.value); // *** Here I get first time access to the desired value ***

            this.form.LinkQueuesId.filterField = MapPrintQueues.LinkQueuesWithWorkstationgroupsRow.Fields.Workstationgroupid;
            this.form.LinkQueuesId.filterValue = wsgroupid;

            this.form.LinkQueuesId.value = this.get_entity().LinkQueuesId.toString();;

        }
```

Hope this helps someone.

With Kind regards,

John

**Comment by fernandocordero** [comment]
Thanks it helped me.
