### ISSUE TITLE
Column Add  & Insert

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#246]
Bu nasıl oldu ? 

![4](https://cloud.githubusercontent.com/assets/16984654/13023040/bbb7fca2-d1ed-11e5-9a35-fdf20e1266ba.JPG)

![5](https://cloud.githubusercontent.com/assets/16984654/13023046/c089189c-d1ed-11e5-9a2f-351306c7d0a1.JPG)

**Comment by ademc** [comment]
Belli ki

columns.Insert(0,  ....

kolonu "seçim kolonu" üretiyor. Yanlış mı anladım, soru "o onay kutuları nerden geldi?" değil mi?

**Comment by Olricz** [comment]
Koddaki gibi bir kolon Add, bir kolonda insert edince checkbox'ın arka tarafına delete.png'yi yerlestiriyor. Fotodan tam gorunuyor mu bilmiyorum.

**Comment by ademc** [comment]
Hmm görünmüyordu, dikkatli bakınca ancak farkettim. Sanırım css ile alakalı bir durum: inline-action class ına bakmak lazım, checkbox zaten başta olmalıydı.

**Comment by Olricz** [comment]
Dokumandaki css uyguladım. 

`.inline-action {
background-repeat: no-repeat;
background-position: center center;
width: 16px;
height: 16px;
cursor: pointer;
opacity: 0.5;
display: inline-block;
&:hover {
opacity: 1;
}
}
.delete-row {
background-image: url(../serenity/images/delete2.png);
}`

**Comment by volkanceylan** [comment]
Şu "a" tag ini

<a></a> şeklinde yazmayı bir deneyin. Sanırım orası patlıyor.

**Comment by Olricz** [comment]
Nasıl ? 

return "<a class='inline-action delete-row' title='delete' />";

**Comment by Olricz** [comment]
Nasıl anlamadım.
```
return "<a class='inline-action delete-row' title='delete' />";
```

**Comment by volkanceylan** [comment]
Sondaki `/>"` yerine `></a>"`

**Comment by Olricz** [comment]
Evet bu şekilde yapınca düzeldi. 
Teşekkür ederim Volkan.
