### ISSUE TITLE
How can I make the full width of the list details in xyzdialog ?

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2461]
hi,

I want to delete the details header and expand the details list, how do I do it?
https://i.resimyukle.xyz/L07OI.jpg

**Comment by sayuga** [comment]
you would want to go to edit the .css of the dialog. Under your ./Content/Site folder you should find the .less files. Find the .less file with the style for the dialog you want to edit and then edit the .less to meet your style needs.

**Comment by volkanturk** [comment]
thanks a lot:)
