### ISSUE TITLE
Populate a textbox from two different dropdown lists

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2463]
Hello Volkan,
I have a dropdown list called Agency and another one called PositionType. I also have a textbox called Position.

I need the values from both Agency and PositionType dropdown lists to populate the Position textbox. How do I go about this? Below is the code snippet on what I tried to do inside the typescript dialog file.

constructor() {
            super();

            // "changeSelect2" is only fired when user changes the selection
            // but "change" is fired when dialog sets customer on load too
            // so we prefer "changeSelect2", as initial customer details 
            // will get populated by initial load, we don't want extra call
            this.form.MemberPositionType.changeSelect2(e => {
                var agencyId = parseInt(this.form.Agency.value);
                var Id = this.form.MemberPositionType.value;
                if (Q.isEmptyOrNull(Id)) {
                    this.setPositionDetails({});
                    return;
                }

                // in northwind CustomerID is a string like "ALFKI", 
                // while its actual integer ID value is 1.
                // so we need to convert customer ID to ID.
                // you won't have to do this conversion with your tables
                var agencyTypeId = MasterData.AgencyRow.getLookup().itemById[agencyId].AgType;
                console.log(agencyTypeId);

                var positionType = Q.first(MasterData.PositionRow.getLookup().items, x => x.AgencyType == agencyTypeId).PositionType;

                Id = String(positionType);

                MasterData.PositionService.Retrieve({
                    EntityId: positionType
                }, response => {
                    this.setPositionDetails(response.Entity);
                });
            });
        }

**Comment by JohnRanger** [comment]
Hi, 

I don't fully understand: What is the desired Output:

Two possibilites are possibe:
(1) The last Action (changing either Agency or Positiontype Dropdown) sets the value within the TextBox (I mean: any Change of within any of the dropdowns will fully replace the Content of the TextBox

(2) You want a mix of the results of the two Dropdowns in the TextBox

For Requirement (1) you do something like this:

```ts
this.form.AGENCY.changeSelect2(e => {
... (do calculation of TextBox value in regard of the agency Dropdown field change and then)
this.form.Position.value = "value which you want to set in the textbox";
});

this.form.MemberPositionType.changeSelect2(e => {
... (do calculation of TextBox value in regard of the MemberPositionType Dropdown field change and then)
this.form.Position.value = "value which you want to set in the textbox";
});

```

With Kind regards,

John
