### ISSUE TITLE
Refresh data pass to loadResponse method

### ISSUE THREAD

**Issue by fernandocordero** [volkanceylan/Serenity#2464]
Guys,

Am new to Serenity template and now I have an scenario where I need to refresh the entity assigned to variable "data". Is there a way to  reload  data of type Serenity.RetrieveResponse<myRow> ? Say I call this "refresh" method from the constructor?  This is the method called upon opening the dialog:

loadResponse(data) {
            super.loadResponse(data);
            this.loadedState = this.getSaveState();
 }

I can't find where "data" is being initialized. Any help will be greatly appreciated it

**Comment by Estrusco** [comment]
What do you want meen with refresh the entity?

**Comment by fernandocordero** [comment]
What I mean is that in one entity  I have a field which is a list and it keeps a rows of a child record. Well I need to "refresh" that field once in tab be a new row is added/deleted. Reason is that in memory in tab A, I still have the old version of that list field so when I click [Update] (without closing the window)  and if I added a new record in tab B, that record is removed from the table. Sorry I know this sounds a bit confusing. Is there a decoration I can use to that field to force an update upon updates?

**Comment by fernandocordero** [comment]
I tried this decorator but it did not do the trick

<img width="412" alt="capture" src="https://user-images.githubusercontent.com/26776121/28020303-e1000498-6551-11e7-8f91-4e244d72bf4a.PNG">

**Comment by fernandocordero** [comment]
I should not have said the "refresh entity" , I meant to say a field within that entity that needs to be refreshed upon execution of an update action at the endpoint. Hope this can help so I can get help.

**Comment by volkanceylan** [comment]
Refresh grid (this.refresh, this.xGrid.refresh()) or refresh dialog entity (this.loadById(this.entityId))

**Comment by jinu4747** [comment]
I have to reload the loadedstate only no need to refresh dialog entity..Thanks for any help in advance
