### ISSUE TITLE
Setting a form field of type boolean to readonly within XYZgrid.cs is not possible

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2466]
Good evening Volkan,

I am able to programmatically set the readonly property of a form field within XYZdialog.cs when the type of the field is an int.

```ts
this.form.PrintQueueId.readOnly = true;
```
But the same is not possible when the form field is of type Boolean.

(ResetPrintqueuesAll is a Checkbox)
```ts
this.form.ResetPrintqueuesAll.readOnly = true;
```

The error message is: Property readOnly does not exist on type BooleanEditor. This is with SF 2.9.24.

Now I know that I can toggle the *visibility* of a boolean field but I want to display the field but make it readonly when the user has only read permissions and leave it readwrite when the user has modify or admin rights.

Is this a bug - or if not, how would I programmatically Change a boolean field to readOnly?

Thanks for your valuable Feedback and

with Kind regards,

John

**Comment by sayuga** [comment]
Have you tried using isDisabled instead?

**Comment by volkanceylan** [comment]
Serenity.EditorUtils.setReadonly

**Comment by JohnRanger** [comment]
Hi Volkan,

thanks for your valuable Feedback.

With Kind regards,

John
