### ISSUE TITLE
How to remove the Search in grideditor

### ISSUE THREAD

**Issue by vinslake** [volkanceylan/Serenity#2467]
![capture](https://user-images.githubusercontent.com/8706163/27989367-1c5c1fe6-6461-11e7-958e-0cc4b39b8b21.PNG)

**Comment by Estrusco** [comment]
In your xyzGrid.ts override createQuickSearchInput()

``
protected createQuickSearchInput() {
   // Nothing
}

**Comment by vinslake** [comment]
thanks so much... it works..
