### ISSUE TITLE
sum

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2468]
hi,

How to add alternate rows and get on last column row in serenity grid dialog.

**Comment by Estrusco** [comment]
See GroupingAndSummariesInGrid sample in Serene

https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/GroupingAndSummariesInGrid

http://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid
