### ISSUE TITLE
 customize button in StoredProcedureGrid - two questions

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2472]
Hello,  Reloading the grid when you enter the date filter in the link (http://serenity.is/demo/BasicSamples/StoredProcedureGrid) 
I am adding a new button and I just want to load the grid again by clicking on this button

there are 2 questions in my code;
1- How can I get the data read in OrderDate  
2- How can I reload to grid  the returning data from the service

` protected getButtons() {
            var buttons = [];
        
            buttons.push({
                title: Q.text('Get Report'),
                
                onClick: () => {
 
                    Q.serviceRequest(CustomerGrossSalesService.baseUrl + "/List", { StartDate: null, EndDate: null }, () => {
                        Q.notifySuccess('Successfuly', '', null);

                    });
 
                }
            });
         
            return buttons;
        }`

**Comment by volkanturk** [comment]
Help please :(

**Comment by JohnRanger** [comment]
Hi Volkanturk,

can you try a "this.refresh();" in the onClick Code of the button?

Regards,

John

**Comment by volkanturk** [comment]
Hi John , this code was succcesfull
thanks a lot :)

` buttons.push({
                title: Q.text('Limite Takılanları Hesapla'),
                hint: "Accept Ticket",
                cssClass: 'accept-ticket-button',
                icon: 'fa-bell',
                onClick: () => {
                    //çok önemli
                    var self = this;
                    Q.confirm('Eminmisiniz?', function () {
                        Q.serviceRequest(CrmLimittalepleriService.baseUrl + "/ListSP", {
                            Secim: "Limite Takılanlar",
                            Userid: Authorization.userDefinition.BdKullanici.Id,
                            Cariid: "%",
                            StartDate: $('#Serene_Brkt2_Center_CrmLimitSpLimitTalepleriGrid0_QuickFilter_Taleptarihi').val(),
                            EndDate: $('#Serene_Brkt2_Center_CrmLimitSpLimitTalepleriGrid0_QuickFilter_Taleptarihi').nextAll('input').first().val(),
                            YenidenHesapla: "E"
                        }, function (response) {
                            
                           // location.reload();
                           self.refresh();
                           Q.notifySuccess("Başarıyla,tamamlandı");
                        }, null);
                    });
                }
                       
            });`
