### ISSUE TITLE
using stimulsoft with serenity

### ISSUE THREAD

**Issue by MBagherii** [volkanceylan/Serenity#2473]
Hello Volkanceylan.
I am new to serenity and I think Serenity is very useful to me. Now I'm in the middle of project and I need to have a Reporting module. I want to know can we use specially stimulsoft or other Reporting Tools in serenity ?

**Comment by volkanceylan** [comment]
We already have a reporting system, it's possible to use other reporting systems, but i'm not going to explain, this is just an ASP.NET MVC application, check out internet resources.

**Comment by kilroyFR** [comment]
I am using Stimulsoft for complex reporting inside my application but anyway still keeping the standard Serenity report tool (mainly to enable fast/out of the box print of all grids in a standard way - not requiring development).
So both have are meaningful in same application (not same purpose).
