### ISSUE TITLE
Serenity with 2.9.24; login credentials timeout after short period of doing nothing

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2474]
Good evening all,

older Apps written with the the Serenity Framework had by design the Feature that once you were logged in, the Login never timed out (until you closed the web page).

But with current app written with SF 2.9.24, the Login credentials time out very quickly (less than half an hour of not using the app actively I would say).

How can this be set back to infinity or at least one working day?

I have checked the guide but didn't find any hint to this.

Thanks and 

with Kind regards,

John

**Comment by javaman63** [comment]
In the older versions of serenity, You could control it from the web.config

`
    <authentication mode="Forms">
      <forms loginUrl="~/Account/Login" timeout="2880" path="/" />
    </authentication>


`

**Comment by JohnRanger** [comment]
Hi Javaman63,

thanks, exactly what I needed. This setting also exists in current version V2.9.24.

With kind regards,

John
