### ISSUE TITLE
Dynamically formatting Field in grid and Dialog according to "virtual type"

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2475]
Hi all,

I have a settings table with the following fields:
- SettingID (int)
- SettingName (nvarchar(max))
- SettingValue (nvarchar(max))
- SettingType (nvarchar(max))   --> This Field will have the following values:  string, boolean, Lookup
- LookupName (nvarchar(max))

The goal/challenge is to dynamically format the SettingValue field within grid and dialog to behave according to the SettingType value.

E.G:

1) If the value of SettingType is "boolean", then the value field should be displayed and behave as a checkbox
2) if the value of SettingType is "string" then the value field should  be displayed and behave like a standard string field
3) If the value of SettingType is "lookup" then the value field should be displayed and behave like a dropdown whose lookupscript/Editor is the one defined within LookupName (only in dialog).

I have unfortunately no idea how to do this as there is - according to my understanding - no such example given within the demo or in the Serenity-Guide.

For any hints and tips I am thankful :-)

With kind regards,

John

**Comment by sayuga** [comment]
Why don't you instead set the SettingType as an enum for each type and then add behavior according to the enum value caught. You'll need to set it so that whatever your response is cast toString() and then cast back properly since you wont be able to have the server side field behave dynamically.

**Comment by dfaruque** [comment]
Here is some hints....In grid, you may override the getColumns() like 
```

        protected getColumns(): Slick.Column[] {
            let columns = super.getColumns();
            let fld = xxxRow.Fields;
            let SettingValueColumn = Q.first(columns, x => x.field == fld.SettingValue);
            SettingValueColumn.format = ctx => { 
                 if (ctx.item.SettingType == 'boolean') 
                      return ctx.item.SettingValue ;
                 else bla bla
               }
            return columns;
        }
```

**Comment by JohnRanger** [comment]
Hi dfaruque,

thanks for the hint. I will try that and give here Feedback.

With kind regards,

John

**Comment by c9482** [comment]
Hi @JohnRanger. I am wondering if you have ever found a solution to dynamically changing the field editor on a dialog? Something that would work with the current release of framework, of course. Many thanks in advance.

**Comment by reach2rv** [comment]
Hi @JohnRanger ,
Are you able to achieve this? If yes can you please share a working solution. 

Thanks
