### ISSUE TITLE
Server side validation

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#2477]
Dear brother Volkan
What is the proper way to do server side validation with serenity both standard (like required, email, etc...) and custom.
Thanks

**Comment by javaman63** [comment]
Take a look to yours xyzEndpoint.cs

**Comment by dudeman972** [comment]
Yes, I am there, its pretty much is all stubs.  Can you please provide an example.  thanks

**Comment by dfaruque** [comment]
see https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Administration/User/UserRepository.cs

**Comment by dudeman972** [comment]
thanks
