### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2478]
Hi,
How can i get only the data of a user who login to the application. Should i use Multi tenant to get this or is there any other method to get it. For Example if an Employee login, only the employee data has to be show to him.

thank you
Srinivas

**Comment by javaman63** [comment]
Use

Authorization.userDefinition at client and server side

**Comment by srinivas1910** [comment]
Hi @javaman63 ,
Can you please explain how to implement Authorization.userDefinition. If posible with an example.

Thanks ,
Srinvas

**Comment by volkanceylan** [comment]
Have a look around in guide, multitenancy and permissions.

**Comment by joheric** [comment]
@srinivas1910  Do you can resolved this?
