### ISSUE TITLE
Export to Excel Modal

### ISSUE THREAD

**Issue by fernandocordero** [volkanceylan/Serenity#2479]
Guys,

Is there an option to make :

buttons.push(Common.ExcelExportHelper.createToolButton({
--
  | grid: this,
  | service: CustomerGrossSalesService.baseUrl + '/ListExcel',
  | onViewSubmit: () => this.onViewSubmit(),
  | separator: true
  | }));

Open as a modal window, in other word, open within the application and not as _blank target?

Thanks in advance.

**Comment by volkanceylan** [comment]
You have the source for ExcelExportHelper, modify it as you like.
