### ISSUE TITLE
IsActive 

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#248]
Merhabalar,
IsActive'i kayıt silinmek istediginde kaydı kalıcı silmeden false olarak ayarladıgın birsey diye dusunuyorum. Bu sekilde mi planladın ? Bu sekilde ise orneklerde çalışan bir yer var mı ? incelemek için. Yok ise nasıl bunu aktif edebilirim ? 

Tesekkurler.

**Comment by volkanceylan** [comment]
IsActive daha çok inaktif personel, birim vs için, bunların değeri 0 olur ve grid de pasif gözükür, ancak row IIsActivenyerine IIsActiveDeleted interface ini sağlıyorsa -1 değeri silinmiş kayıtlar için kullanılır, listelerde gözükmez

**Comment by Olricz** [comment]
IIsActiveDeleted bulamadım ?

**Comment by volkanceylan** [comment]
IIsActiveDeletedRow

**Comment by Olricz** [comment]
XXXRow.cs ekliyorum sanırım ? 
Vakit olunca bir ornek yapabilirsen sevınırım. Selamlar.

**Comment by Olricz** [comment]
eklemek yeterliymiş. çok kolaylastırmıssın. Tesekkurler.

**Comment by Olricz** [comment]
Yalnız şu şekilde yaptıgımda ve sildigimde ISactive -1 oluyor ama Update User ve Date guncellenmiyor. Yanı ne zaman silindigi belli olmuyor. 

```
public sealed class LargeTableRow : LoggingRow, IIdRow, INameRow, IMultiTenantRow, IIsActiveDeletedRow
{....}
```

**Comment by volkanceylan** [comment]
Onun için IDeleteLogRow u da eklemeniz lazım.

Aslında IDeleteLogRow yoksa IUpdateLogRow da kullanılabilir bunu bir değerlendireyim

**Comment by Olricz** [comment]
LoggingRow.cs eklenebilir aslında...

**Comment by Olricz** [comment]
LoggingRow.cs ekledim olmadı. Olması gerek miyordu. Yani Update Fieldları gibi.

**Comment by volkanceylan** [comment]
Tamam şöyle bir sorun varmış, IIsActiveDeletedRow olduğunda silmede delete / update audit alanları güncellenmiyor. Bir sonraki sürümde düzelecek. Ayrıca IDeleteLogRow yoksa IUpdateLogRow kullanılması için de gerekli düzenlemeyi yaptım. Onu da kaldırabilirisiniz ayrı bir alana ihtiyaç yoksa.

**Comment by Olricz** [comment]
Ben MultiTenancy uzerinden calısıyorum. Dokumandaki update için yazdıgın aşağıdaki komutları uyguladım. Fakat update sonrası herşey gitti. Northwind bile çalışmıyor. List ekranı gelmiyor. 

Update-Package Serenity.Web
Update-Package Serenity.CodeGenerator
Update-Package Serenity.Script

**Comment by volkanceylan** [comment]
mscorlib.js nuget paketinden gitmiş bir şekilde, 1.9.11 i bekleyin, şimdilik elle script/saltarelle/mscorlib.js i elle kopyalayabilirsiniz.

**Comment by Olricz** [comment]
Eywallah, beklerim.

**Comment by Olricz** [comment]
Elle kopyalamak ıse yaramadı.

**Comment by volkanceylan** [comment]
Scripts / site / saltarelle altında olması gerekiyor. Neyse 1.9.11 nuget çıktı.

**Comment by Olricz** [comment]
benim hatam :(  hallettim. 
tesekkur ederım.

**Comment by volkanceylan** [comment]
Birşey değil, neyse IsActiveDeleted meselesi de çözülmüş olmalı.

**Comment by Olricz** [comment]
Selam Volkan, 
Tabloya DeleteDate veDeleteUserId ekledim. LoggingRow.cs'e de "IDeleteLogRow" implemente ettim. 
Bu sekılde update guncellemıyor ama delete e guncellıyor. Dogru yani. Ama LoggingRow'a implemente ettigim XXXRow.cs ekrana "silinmiş kayıtları goster" i bozmus. Menuden girdiginde silinmişleri de gosteriyor. "silinmişleri goster" e bişey olmuş. 

Selamlar.

**Comment by volkanceylan** [comment]
IsActive alan adı doğru mu?

**Comment by Olricz** [comment]
evet..o kolon dogru deger alıyor.

**Comment by volkanceylan** [comment]
Grid üzerinde IsActiveProperty olacak oradaki doğru mu?

**Comment by Olricz** [comment]
Pardon IsActive dogru degıl. sildim bi kayıt, -1 olmadı.  
(delete audit alanı guncellenmiş. )

**Comment by volkanceylan** [comment]
IIsActiveDeletedRow implemente edilmiş mi peki row da yada base class ta

**Comment by Olricz** [comment]
Yok edilmedi.

**Comment by Olricz** [comment]
Şöyle : 
![6](https://cloud.githubusercontent.com/assets/16984654/13033383/60306320-d31d-11e5-9af4-e40071ddde4d.jpg)

![7](https://cloud.githubusercontent.com/assets/16984654/13033384/635e37e8-d31d-11e5-997a-431507f8b5b2.jpg)

**Comment by volkanceylan** [comment]
O zaman -1 yapmaz ki

**Comment by volkanceylan** [comment]
IIsActiveDeleted olması lazım silince -1 olmasını istiyorsanız

**Comment by Olricz** [comment]
IIsActiveDeletedRow , LoggingRow.cs'e mi implemente etmeliyim yoksa XXXRow.cs'e mi ?

**Comment by volkanceylan** [comment]
Farketmez, bütün log row larınız böyle olacaksa LoggingRow, değilse XXXRow. Ama aynı anda ikisinde de olmasın, ya da IsActive birinde IsActiveDeleted birinde olmasın

**Comment by Olricz** [comment]
iki yere de ekledim. Silme işlemi yapılamaz oluyor. Kayıt silinmiyor yani. Ben butun log rowlarda insert, update ve delete audit alanını kullanmak istiyorum.  Buna gore asagıdaki iki satiri nasıl olmalı.

```
public abstract class LoggingRow : Row, IIsActiveRow, ILoggingRow, IDeleteLogRow

```

```
public sealed class FreakTablesRow : LoggingRow, IIdRow, INameRow, IMultiTenantRow, IIsActiveDeletedRow
```

**Comment by volkanceylan** [comment]
public abstract class LoggingRow : Row, IIsActiveDeletedRow, ILoggingRow, IDeleteLogRow

public sealed class FreakTablesRow : LoggingRow, IIdRow, INameRow, IMultiTenantRow

**Comment by Olricz** [comment]
Tamamdır. Sadece platform iyi olsun diye yazıyorum bunu : Sildigin kaydı geri aldıgında DeleteUserId ve DeleteDate dolu kalıyor. Belki kalmalı bilmiyorum. Ne zaman silindiğini görebilirsin. Ama birden fazla sildiginde de sonuncuyu goreceksin filan. Log'dan takip edebilirsin gerçi. Sana bıraktım. 

Tesekkur ederım. Loglama guzel oldu ..eline saglık.

**Comment by Olricz** [comment]
CaptureOperationType 'a bir ara **undelete** eklenebilir.

**Comment by volkanceylan** [comment]
CaptureLog silmeyi de update olarak görür, database deki CDC gibi düşün. Onun bir sanal delete işlemi olduğunu log viewer bilip gerekirse gösterecek. Dolayısıyla undelete için de aslında işlem bir update.

DeleteDate vs temizlemeyi ekleyeyim o eksik kaldı.

**Comment by Olricz** [comment]
OK. Undelete'i de zaten Before ve After satırlar aynı olunca secebiliyorsun.
