### ISSUE TITLE
Cascade DB Field to Enum field

### ISSUE THREAD

**Issue by Myxville** [volkanceylan/Serenity#2480]
Hi,

Can't find the way how to achieve this with the Enum, and I don't want it to be SQL table as this Enum contains only 2 values 
GenderEnum { M = 1, F = 2 }

And I have PersonForm with set of fields and the 2 specific I need to link
        public GenderEnum Gender { get; set; }
        public Int32 MaritalStateId { get; set; }

MaritalState is the table, where I store different states based on Gender (don't ask me why :) )
        [DisplayName("Gender"), Size(1), NotNull, LookupInclude]
        public String Gender
        {
            get { return Fields.Gender[this]; }
            set { Fields.Gender[this] = value; }
        }

How can I cascade MaritalState to the selection of Gender?
I tried the following with no luck
        [LookupEditor(typeof(MaritalStateRow), CascadeFrom = "Gender", CascadeField = "Gender")]
        public Int32 MaritalStateId { get; set; }

**Comment by Myxville** [comment]
Ok, I figured out, that the problem is that my field Gender in MaritalState table stores 'M' or 'F'
But dropdown on the UI works with values of my enum - 1 and 2
How can I change drop down to work with M/F, not 1/2 ?

**Comment by volkanceylan** [comment]
See constant values sample.
