### ISSUE TITLE
Error Log will not login

### ISSUE THREAD

**Issue by buddhatripp** [volkanceylan/Serenity#2482]
I am implementing a custom authentication system using Serenity's interfaces and ASP.NET Identity. I can login and maintain users without any problems, but when I try to open the Exception Log using the main menu, the new window that opens goes to the login screen with errorlog.axd as the return url parameter. I try to login and it returns to the login screen repeatedly with no errors being thrown. I'm not sure what I'm missing here. Any help would be appreciated. Thank you!

**Comment by volkanceylan** [comment]
It's set in web.config, only admin can see that page.
