### ISSUE TITLE
Hide URL (Route) after 2.9.28 Update

### ISSUE THREAD

**Issue by MaradiagaSistemas** [volkanceylan/Serenity#2484]
Hi Volkan,

Congrats for this amazing Framework, 

After 2.9.28 Update, Does exist any way available to Hide URL (Route) ?

I Just updated, but I want to remove this feature., Thank you very much.

![image](https://user-images.githubusercontent.com/1533653/28277666-debfd36c-6ad7-11e7-9a5a-00e115b05e7c.jpg)

Regards.

**Comment by volkanceylan** [comment]
No, its integrated

**Comment by MaradiagaSistemas** [comment]
Thank you very much.
