### ISSUE TITLE
div title

### ISSUE THREAD

**Issue by fernandocordero** [volkanceylan/Serenity#2485]
Guys,

Is there a way to change the alert title to something else? I have this helper that invokes a service call

![image](https://user-images.githubusercontent.com/26776121/28284950-e9560048-6b00-11e7-8a93-8220407a091d.png)

But as you can see it will use the draggable div with the Alert title

![image](https://user-images.githubusercontent.com/26776121/28285047-319cdb2e-6b01-11e7-96cd-7272ceb27570.png)

Is there an option where I can at least change the div title? Maybe JQuery, some guidance will be appreciated.

**Comment by volkanceylan** [comment]
That "Alert" is showing an error, why would you use an error display as something to show a page?? Services shouldn't return pages, you are doing it all wrong.

**Comment by fernandocordero** [comment]
It makes sense, I was just experimenting. I will try to convert this into a dialog. But if this is an error why the service would allow to replace the iframe with the page's content.

**Comment by volkanceylan** [comment]
It expects JSON, it shows response so that you can understand what is wrong.

**Comment by fernandocordero** [comment]
Got it thanks.
