### ISSUE TITLE
How to give permission to particular column ...and at which location 

### ISSUE THREAD

**Issue by AbhishekBorkar04** [volkanceylan/Serenity#2488]

**Comment by sayuga** [comment]
I believe you can simply use the xyzPermission attribute on the row. 

Example: 

[DisplayName("Territory Description"), Size(50), NotNull, QuickSearch, LookupInclude, DeletePermission(PermissionKeys.General)]
        public String TerritoryDescription
        {
            get { return Fields.TerritoryDescription[this]; }
            set { Fields.TerritoryDescription[this] = value; }
        }

**Comment by AbhishekBorkar04** [comment]
Thanks
