### ISSUE TITLE
Jquery AutoComplated

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#249]
Jquery AutoComplated kullanımana örnek var mı ? Ya da kullanan var mı ? 
Örneğin Yeni Customer girerken, Customer adını yazarken çalıştırabilmek için nasıl bir yol izlemeliyim ? 

Tesekkurler.

**Comment by volkanceylan** [comment]
Select2 bunu yapıyor

**Comment by Olricz** [comment]
tamam bugun bunu yapmaya calısacagım.
