### ISSUE TITLE
How to retrieve fields in a custom lookup class in typescript

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2493]
Hello Volkan,
Please if I have a custom lookup class with the select query having more fields than the IdField and TextField, how do I retrieve the other fields in typescript? Find below my code.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Serenity.ComponentModel;
using Serenity.Data;
using Serenity.Web;
using ppa.MasterData.Entities;
using Serenity;

namespace ppa.Modules.MasterData.Position
{
    [LookupScript("MasterData.PositionPositionType")]
    public class PositionPositionTypeLookup : RowLookupScript<PositionRow>
    {
        public PositionPositionTypeLookup()
        {
            IdField = PositionRow.Fields.PositionType.PropertyName;
            TextField = PositionRow.Fields.PositionTypeTypeName.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            //base.PrepareQuery(query);
            var user = (UserDefinition)Authorization.UserDefinition;
            var fld = PositionRow.Fields;
            if (!Authorization.HasPermission("Administration:Security"))
            {
                if (user.UserAgencyType != null)
                {
                    query
                        .Distinct(true)
                        .Select(fld.PositionType)
                        .Select(fld.PositionTypeTypeName)
                        .Select(fld.PositionId)
                        .Select(fld.PositionName)
                        .Select(fld.AgencyType)
                        .Select(fld.AgencyTypeTypeName)
                        .Where(
                            new Criteria(fld.PositionTypeTypeName) != "" &
                            new Criteria(fld.PositionTypeTypeName).IsNotNull() &
                            new Criteria(fld.AgencyType) == user.UserAgencyType.Value);
                }
            }
            else
            {
                query
                    .Distinct(true)
                    .Select(fld.PositionType)
                    .Select(fld.PositionTypeTypeName)
                    .Select(fld.PositionId)
                    .Select(fld.PositionName)
                    .Select(fld.AgencyType)
                    .Select(fld.AgencyTypeTypeName)
                    .Where(
                        new Criteria(fld.PositionTypeTypeName) != "" &
                        new Criteria(fld.PositionTypeTypeName).IsNotNull());
            }
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}

I want to be able to retrieve all the Select fields in typescript.What code can I use to do that?

**Comment by sayuga** [comment]
Make sure that the field has the LookupInclude attribute on their xyzRow.cs. Then simply use the xyzRow.getLookup() on typescript to access the lookup for the Row. 

DefaultValuesInNewGrid has a decent sample of accessing lookup items on ts. 

var lauraCallahanID = Northwind.EmployeeRow.getLookup().items
                        .filter(x => x.FullName === 'Laura Callahan')[0].EmployeeID;

By the way, don't forget to add the LookupScript() at the top of the xyzRow class
