### ISSUE TITLE
Pass values ​​from some field to a grid

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2494]
Pass the values ​​of some field to be displayed in the grid.

**Comment by alexneocart** [comment]
#
![img](https://user-images.githubusercontent.com/28063632/28387140-4be0d2d4-6ca4-11e7-8d1c-55cf598990f7.jpg)

**Comment by alexneocart** [comment]
I need to pass values ​​from several fields from an entity x to the entity grid Y through a MasterDetailRelation as shown in the image above

**Comment by javaman63** [comment]
Check this example:
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts

                   dlg.loadEntityAndOpenDialog(<Northwind.OrderRow>{
                        CustomerID: 'GOURL',
                        EmployeeID: lauraCallahanID,
                        DetailList: [{
                            ProductID: chai.ProductID,
                            ProductName: chai.ProductName,
                            UnitPrice: chai.UnitPrice,
                            Quantity: 5,
                            LineTotal: chai.UnitPrice * 5
}]
