### ISSUE TITLE
Querying Records with multiple conditional fields in a changeSelect2 dropdown event

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2495]
Hello Volkan,
Below is my code.

namespace ppa.TenderCommitteeList {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class TenderCommitteeDialog extends Serenity.EntityDialog<TenderCommitteeRow, any> {
        protected getFormKey() { return TenderCommitteeForm.formKey; }
        protected getIdProperty() { return TenderCommitteeRow.idProperty; }
        protected getLocalTextPrefix() { return TenderCommitteeRow.localTextPrefix; }
        protected getNameProperty() { return TenderCommitteeRow.nameProperty; }
        protected getService() { return TenderCommitteeService.baseUrl; }

        protected form = new TenderCommitteeForm(this.idPrefix);

        agencyTypeId: number;

        /*
        constructor() {
            super();

            // Add change event to control field
            if (!Authorization.hasPermission("Administration:Security"))
            {
                // Set read only to true for a field
                Serenity.EditorUtils.setReadOnly(this.form.MemberPositionType, false);
                Serenity.EditorUtils.setReadOnly(this.form.Position, false);
            }
            else
            {
                // Set read only to true for a field
                Serenity.EditorUtils.setReadOnly(this.form.MemberPositionType, true);
                Serenity.EditorUtils.setReadOnly(this.form.Position, true);
            }
                
        }*/

        constructor() {
            super();

            // "changeSelect2" is only fired when user changes the selection
            // but "change" is fired when dialog sets customer on load too
            // so we prefer "changeSelect2", as initial customer details 
            // will get populated by initial load, we don't want extra call
            
            this.form.PositionType.changeSelect2(e => {
                //var agencyId = parseInt(this.form.Agency.value);
                var positionTypeId = this.form.PositionType.value;
                //var agencyTypeId = String(this.form.AgencyAgType.value);
                if (Q.isEmptyOrNull(positionTypeId)) {
                    this.setPositionDetails({});
                    return;
                }

                // in northwind CustomerID is a string like "ALFKI", 
                // while its actual integer ID value is 1.
                // so we need to convert customer ID to ID.
                // you won't have to do this conversion with your tables
                //var agencyTypeId = MasterData.AgencyRow.getLookup().itemById[agencyId].AgType;
                //var newEntityId = Id + " & " + agencyTypeId;
                
                console.log(this.form.AgencyAgType.value);
                console.log(positionTypeId);

                var positionId = Q.tryFirst(MasterData.PositionRow.getLookup().items, x => x.PositionType == parseInt(positionTypeId) && x.AgencyType == this.form.AgencyAgType.value).PositionId;
                //console.log(positionId);
                //Id = String(positionType);
                //console.log(this.form.AgencyAgType.value);
                //console.log(positionId);
                
                MasterData.PositionService.Retrieve({
                    EntityId: positionId
                }, response => {
                    this.setPositionDetails(response.Entity);
                });
            });
            
            this.form.Agency.changeSelect2(e => {
                //var agencyId = parseInt(this.form.Agency.value);
                var agencyId = this.form.Agency.value;
                //var positionTypeId = parseInt(this.form.MemberPositionType.value);
                if (Q.isEmptyOrNull(agencyId)) {
                    this.setAgencyTypeDetails({});
                    return;
                }

                // in northwind CustomerID is a string like "ALFKI", 
                // while its actual integer ID value is 1.
                // so we need to convert customer ID to ID.
                // you won't have to do this conversion with your tables
                //var agencyTypeId = MasterData.AgencyRow.getLookup().itemById[agencyId].AgType;
                //var newEntityId = Id + " & " + agencyTypeId;
                //console.log(agencyTypeId);

                //var positionId = Q.first(MasterData.PositionRow.getLookup().items, x => x.AgencyType == agencyTypeId && x.PositionType == positionTypeId).PositionId;

                //Id = String(positionType);

                MasterData.AgencyService.Retrieve({
                    EntityId: agencyId
                }, response => {
                    this.setAgencyTypeDetails(response.Entity);
                });
            });
        }
        
        private setAgencyTypeDetails(details: MasterData.AgencyRow) {
            this.form.AgencyAgType.value = details.AgType;
            //console.log(this.agencyTypeId);
            //this.form.PositionName.value = details.PositionName;
        }

        private setPositionDetails(details: MasterData.PositionRow) {
            this.form.Position.value = details.PositionId;
            this.form.PositionName.value = details.PositionName;
        }

        /**
         * This method is a good place to update states of
         * interface elements. It is called after dialog
         * is initialized and an entity is loaded into dialog.
         * This is also called in new item mode.
         */
        protected updateInterface(): void {

            super.updateInterface();

            // Add change event to control field
            if (!Authorization.hasPermission("Administration:Security")) {
                // Set read only to true for a field
                Serenity.EditorUtils.setReadOnly(this.form.Agency, true);
                Serenity.EditorUtils.setReadOnly(this.form.PositionType, true);
                Serenity.EditorUtils.setReadOnly(this.form.PositionName, true);
            }
            else {
                // Set read only to true for a field
                Serenity.EditorUtils.setReadOnly(this.form.Agency, false);
                Serenity.EditorUtils.setReadOnly(this.form.PositionType, false);
                Serenity.EditorUtils.setReadOnly(this.form.PositionName, false);
            }

            // finding all editor elements and setting their readonly attribute
            // note that this helper method only works with basic inputs, 
            // some editors require widget based set readonly overload (setReadOnly)
            //Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);

            // remove required asterisk (*)
            //this.element.find('sup').hide();

            // here is a way to locate a button by its css class
            // note that this method is not available in 
            // getToolbarButtons() because buttons are not 
            // created there yet!
            // 
            // this.toolbar.findButton('delete-button').hide();

            // entity dialog also has reference variables to
            // its default buttons, lets use them to hide delete button
            //this.deleteButton.hide();

            // we could also hide save buttons just like delete button,
            // but they are null now as we removed them in getToolbarButtons()
            // if we didn't we could write like this:
            // 
            // this.applyChangesButton.hide();
            // this.saveAndCloseButton.hide();

            // instead of hiding, we could disable a button
            // 
            // this.deleteButton.toggleClass('disabled', true);
        }

    }
}

In the Q.tryFirst query inside **this.form.PositionType.changeSelect2**, there are two conditions that need to be satisfied for PositionId to return a result
1.  x.PositionType == parseInt(positionTypeId)
2.   x.AgencyType == this.form.AgencyAgType.value

The PositionType dropdown is what triggers the changeSelect2 event. The value of the agencyType is gotten from the agency changeSelect2 dropdown.

The strange thing is that, though the agencyType value is being retrieved and printed correctly via console, when it is passed as part of the condition in the Q.tryFirst query, an error is thrown because the query doesn't see the retrieved agencyType value.

Please kindly help me know the best way to pass multiple field conditions into a Q.tryFirst query

**Comment by volkanceylan** [comment]
Add [LookupInclude] to AgencyType field first. If you are using tryFirst, it might return null if none matches that criteria, so take result into a variable, and continue only if it is not null.

**Comment by stixoffire** [comment]
@gfo2007 Thanks for posting your code - the retrieve and update from xyzdialog/editor was what I was searching for how to do. Your code showed me how it was done!! Thanks for sharing. 
I made a WIKI entry for that as well, so others that might not have all the details on typescript and the framework can learn from it .
