### ISSUE TITLE
unable to clear cookies and/or clean session with safari

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [volkanceylan/Serenity#2496]
Hello,

this is my first time here. In my setup, I am running my tests for CucumberWithSerenity.class
The issue is after execution of my tests with safari browser, safari does not clear the cookies and other related data. e.g. After login steps are completed, i have to search for a user and set the user so i get relevant sections. But safari retains the set user information from previous test execution. To address this issue, i have set the following in serenity.properties file : safari.options.useCleanSession=true
however, this does not seem to work. 

On other browsers, i do not have such an issue. Is there a fix for this or am i implementing the property incorrectly?

**Comment by volkanceylan** [comment]
You're probably at wrong place, try:

https://github.com/serenity-bdd/serenity-cucumber
