### ISSUE TITLE
i have following row object  in grid.ts  i want to store this in new Table ..how to do it? pls tell me

### ISSUE THREAD

**Issue by AbhishekBorkar04** [volkanceylan/Serenity#2497]
this.rowSelection.getSelectedKeys().map(x => this.view.getItemById(Q.toId(x))
this object contains
Id:
1
EmailAddress:
"Abhishekfcc@Mail.com"
Name:
"Abhishek Borkar1"
DateCreated:
"2017-07-18T00:00:00.000"
_

**Comment by JohnRanger** [comment]
Hi @AbhishekBorkar04 ,

what exactly do you want to achieve? (Overall Picture please, so we can better understand and eventually help).

With Kind regards,

John
