### ISSUE TITLE
Getting localization form to display field from a foreign table

### ISSUE THREAD

**Issue by FloweryScythe13** [volkanceylan/Serenity#2498]
I have what seems to be a difficult problem with the localization sub-form in EntityDialogs. I have a MakeRow defined as follows:

```
[ConnectionKey("myKey"), TableName("[dbo].[Make]"), DisplayName("Make"), InstanceName("Make"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General"), LeftJoin("ml", "[dbo].[MakeLocalized]", "ml.[MakeId] = t0.[MakeId] AND ml.[LanguageId] = 0", RowType = typeof(MakeLocalizedRow))]
    [UpdatableExtension("ml", typeof(MakeLocalizedRow))]
    [LocalizationRow(typeof(MakeLocalizedRow))]
    public sealed class MakeRow : Row, IIdRow, INameRow
    {
        [DisplayName("Make Id"), Identity]
        public Int64? MakeId
        {
            ...
        }

        [DisplayName("Sort Order"), NotNull, Hidden]
        public Int64? SortOrder
        {
           ...
        }

        [DisplayName("Description"), NotNull, Expression("ml.[Description]")]
        public string Description
        {
            ...
        }

        [DisplayName("Created By")]
        public String CreatedBy
        {
            ...
        }

        .........
    }
````
I then have my MakeLocalizedRow defined as follows:
```
[ConnectionKey("myKey"), TableName("[dbo].[MakeLocalized]"), DisplayName("Make Localized"), InstanceName("Make Localized"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class MakeLocalizedRow : Row, IIdRow, INameRow, ILocalizationRow
    {
        [DisplayName("Make Localized Id"), Identity]
        public Int64? MakeLocalizedId
        {
            ...
        }

        [DisplayName("Make"), NotNull, ForeignKey("[dbo].[Make]", "MakeId")]
        public Int64? MakeId
        {
            ...
        }

        [DisplayName("Language Id"), NotNull, DefaultValue(0)]
        public Int64? LanguageId
        {
            ...
        }

        [DisplayName("Description"), NotNull, QuickSearch]
        public String Description
        {
            ...
        }

        [DisplayName("Created By"), Hidden]
        public String CreatedBy
        {
            ...
        }

        ...........

        IIdField IIdRow.IdField
        {
            get { return Fields.MakeLocalizedId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Description; }
        }

        public Field CultureIdField
        {
           get { return Fields.LanguageId; }
        }

    }
```

Note that my Make table basically contains only an index of MakeIds and their metadata related to the back end (like IsDeleted, CreatedDate, etc), while all of the textual values (like Description) and their localizations across all languages are stored in the MakeLocalized table (LanguageId = 0 corresponds to English, the default). I know this complicates things, but the DB schema isn't something I have much control over here. 

Now, the above works fine for MakeForm, and the Description field is displayed with its default English value for any given make. However, I can't seem to get Description to display in the Localization form of the dialog, and it's the only field here that actually needs translating from the user. 

After a lot of debugging, I have a suspicion that ILocalizationRow/LocalizationHandler doesn't trigger LeftJoin attributes and other similar behavior on a row being localized, in this case Make (so it doesn't display any field for Description, because Description is joined from MakeLocalized itself). Is this the likely culprit? How can I best get around this problem in general? Any help here is appreciated.

**Comment by volkanceylan** [comment]
Sorry but localization system doesn't support fields from other tables, it can only localize table fields. As it is javascript, you may try to fool UI to show that field, by overriding GetPropertyItems, finding that field and setting its Localizable property to true.

After that, you need to somehow handle storage of those localizations in your repository SaveHandler as localization behavior won't be able to handle itself.
