### ISSUE TITLE
Dosya Yükleme

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#2499]
İyi Günler ,
Dosya Yüklemede  sadece resim mi yükleyebiliriz? başka bir dosya(pdf,word) ekleyeme çalıştıgımızda  Yüklemeye calıştığınız  dosya bir resim değildir hatası veriyor.
İyi Çalışmalar.

**Comment by JohnRanger** [comment]
Hi Dosya,

if you would like that more People help you out, please write in english (as many of us do not understand the turkish language but of Course if you address Volkan directly, that's fine :-)).

With Kind regards,

John

**Comment by volkanceylan** [comment]
Use [FileUploadEditor] not [ImageUploadEditor]
