### ISSUE TITLE
CaptureLog 

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#250]
CaptureLog claslarını manuel mi olusturuyoruz  ? 

ServiceContracts altındakini vs.. ,

**Comment by volkanceylan** [comment]
ServiceContracts altındakini değil, web tarafındaki row u manuel yapıyorsunuz. Diğerleri T4 leri dönüştürünce oluşur.

**Comment by Olricz** [comment]
Yani web tarafındakini olusturup compile edince ServiceCon'tarafı kendi olusuyor. Dogru mu anlamısım ?

**Comment by volkanceylan** [comment]
Compile edip, ardından ServiceContracts ı kaydedince, yani dönüştürünce kendi oluşuyor evet.

**Comment by Olricz** [comment]
1. "FreakTableLogRow.cs" manuel olusturdum. 
2."Test.FreakTableLogRow.cs" ServiceContracts altında olusturdum. Compile ettim. Şötle bir mesaj alıyorum. Field'ı match edememiş. 

![4](https://cloud.githubusercontent.com/assets/16984654/13033154/eb2284b2-d314-11e5-8f6f-73e5968b5d5d.JPG)

**Comment by Olricz** [comment]
Benim hatam. hallettim.
