### ISSUE TITLE
I have created a stored procedure and a corresponding action controller method in myprojpage.cs file and I want to call this method on onclick even in grid.ts file.please provide some soln.  

### ISSUE THREAD

**Issue by AbhishekBorkar04** [volkanceylan/Serenity#2500]
myprojPage.cs
[HttpPost, JsonFilter]
        public Result<ServiceResponse> ExecuteProc(ProcParam request)
        {
            return this.UseConnection("Default", connection =>
            {
                using (IDbCommand command = connection.CreateCommand())
                {
                    IDbDataParameter Param1 = command.CreateParameter();
                    Param1.ParameterName = "@Param1";
                    Param1.Value = request.Param1;
                    command.Parameters.Add(Param1);

                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "[<MySPName>]";
                    command.ExecuteNonQuery(); /*Can be execute with corret proc.*/

                    ProcResponse oProcResponse = new ProcResponse();
                    oProcResponse.ExecutionResult = "Success";
                    return (ServiceResponse)oProcResponse;
                }
            });
        }

ProcParam.cs
    public class ProcParam : ServiceRequest
    {
        public string Param1 { get; set; }
    }

ProcResponse.cs:

    public class ProcResponse : ServiceResponse
    {
        public string ExecutionResult { get; set; }
    }

**Comment by JohnRanger** [comment]
Please have a look at the example: ChartInDialog.ts. There a Service endpoint is called from Client-side.

And your xyzDialog is Client-side.

Hope this helps.

with Kind regards,

John

**Comment by volkanceylan** [comment]
There is a stored proc grid sample, that should be a good start.
