### ISSUE TITLE
Gives exception while using edit filter between option

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#2501]
Unhandled exception at line 4912, column 4 in http://localhost:60265/Scripts/serenity/Serenity.Script.UI.js?v=EDkoNVTRZKcOM09DeHNujg2
0x800a139e - JavaScript runtime error: Filtering 'StringFiltering' has no editor for 'bw' operator occurred

**Comment by sayuga** [comment]
@Parabil, even if you share your link to your project, since you are posting the "localhost" link, no one else will be able to see it unless they are on your system. Please add screen shots and post whatever error information is in the error log or/and console.

**Comment by Parbil** [comment]
![image](https://user-images.githubusercontent.com/7609571/28537233-bdb17270-70c7-11e7-8b71-e787a0dcb104.png). Also would like to know how get the error log for this.

Hope this will help,

**Comment by sayuga** [comment]
'bw', seems to be the reference to the 'Between' operator. This seems to be a bug since it's calling it as a string editor type.

**Comment by volkanceylan** [comment]
If your field ID is a string, you can't get between operator, find out how you managed to do that.
