### ISSUE TITLE
Large Amount of data

### ISSUE THREAD

**Issue by kuradaganesh** [volkanceylan/Serenity#2502]
1.How much of rows and columns supported in serenity grid view system if supported any  perform issues??
2.above 10 lacs of rows and more than 100's of columns is supported or not??

**Comment by JohnRanger** [comment]
Hi,

rows should be virtually unlimited (limited only by the underlying SQL Server System). Performance will always be very good as Long as you Limit the rows per page in the grid to - let's say 100.

About columns amount I don't know but simply test it and then post here your eperience.

As even on the biggest Screens with a 4K Resolution you cannot Display too many colums at the same time more than 100 columns seems a bit much for me - but of Course I don't know your Project...

With Kind regards,

John
