### ISSUE TITLE
how to add the new form/entities to permissions

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#2503]
Hi,
First of all thank you so much for such wonderful product. I am new to web programming and this tool really helping me. I am following the Movie tutorial everything seems working  till creating a Movie Kind

I have noticed two points so far

1) the field Kind is added as mandatory field with default value, if we try to save without value it validates but unlike title field the field is not highlighting with red borders.  what is missing in this case

2)the movies module is not listed under user permissions, or any other place. what is to be done for this

**Comment by sayuga** [comment]
Parabil, Permissions are currently listed under the Administration/AdministrationPermissionKeys.cs. You'll also notice that the permission on top of the MovieRow.cs is "Administration:General". That is what is added into the User Permissions tree. 

Look at this section of the manual for more details: https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_register_permissions_in_serene.html

Regarding MovieKind. It looks like it may be a bug with regards to the editor. The Field is still being treated as a required error but the css for the box is just not triggering. I'll leave that to @volkanceylan

**Comment by Parbil** [comment]
Thanks, I have gone through them and applied all three methods, with class, with assembly and using string. all of them appearing in the tree and going to the db  table..amazing work!

Regarding css triggering, I will wait for @volkanceylan feedabck

**Comment by JohnRanger** [comment]
@Parbil: In order that Volkan can trace this faster: Could you please Feedback here the browser(s) in which that Problem occurs?

With Kind regards,

John

**Comment by Parbil** [comment]
Thanks, I have tried IE, Firefox, chrome all giving same result.
![image](https://user-images.githubusercontent.com/7609571/28692218-4781d216-733d-11e7-96f9-56f0061b3e14.png)

**Comment by volkanceylan** [comment]
It's a CSS issue, i don't think that's critical, you have RED crossmark there anyway.
