### ISSUE TITLE
how to access the global variables vial dialogeditor in Global.asax 

### ISSUE THREAD

**Issue by vinslake** [volkanceylan/Serenity#2504]
hi guys, how to access the variables in global.asax via dialogeditor

**Comment by JohnRanger** [comment]
Here the very high Level Approach (not tested from a dialogeditor (only from xyzDialog.ts) but should give you the Basic idea):

As DialogEditor is client-side you will have to write a Service endpoint on Server side which will deliver the desired variables and their content over to client-side. This Service endpoint you can call from client-side.

(1) Add a Service endpoint to the xyzEndpoint.cs 
(2) then call it from client-side (xyzDialog.ts or xyzDialogEditor.ts).

How to call a Service endpoint from client-side? Please have a look at the Serenity example: ChartInDialog.ts

Hope this helps.

With Kind regards,

John

**Comment by vinslake** [comment]
thnk got it
