### ISSUE TITLE
Limit data for the current user?

### ISSUE THREAD

**Issue by rodneykendall** [volkanceylan/Serenity#2506]
I need to limit the rows returned on a page to only rows with the same userid (from the Users table) as the logged in user.  Where do I add that criterion and how should it be coded?

**Comment by javaman63** [comment]
On you XYZRepository code something like this on the MyListHandlerClass

        private class MyListHandler : ListRequestHandler<MyRow>

        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                    query.Where(fld.UserId == Convert.ToInt32(Authorization.UserId));
            }

        }

**Comment by rodneykendall** [comment]
Thank you!  That works perfectly.
