### ISSUE TITLE
Localise tabs 

### ISSUE THREAD

**Issue by Myxville** [volkanceylan/Serenity#2507]
Hi,

Following the https://github.com/volkanceylan/serenity-guide/blob/master/tutorials/movies/listing_movies_in_person_dialog.md

How is this possible to localise TAB titles? 
In this case - Person, Movies.

**Comment by JohnRanger** [comment]
Within the followin lines:

```ts
<li><a href="#~_TabInfo"><span>Person</span></a></li>
        <li><a href="#~_TabMovies"><span>Movies</span></a></li>
```
I have not tested this but try the following:
replace the Static text (Person and Movies) with the following:

```ts
<li><a href="#~_TabInfo"><span>Q.Text("Dialogs.Tabs.Persons")</span></a></li>
<li><a href="#~_TabMovies"><span>Q.Text("Dialogs.Tabs.Movies")</span></a></li>
```

And then add in the file: /scripts/site/Texts/site.texts.invariant.json the following entries:
```json
"Dialogs.Tabs.Person" : "Persons",
"Dialogs.Tabs.Movies" : "Movies"
```
Now find/create such json files for your desired language.

E.G. for german there is a file called site.texts.de.json.
Add here the same Tokens but with translated text:
```json
"Dialogs.Tabs.Person" : "Personen",
"Dialogs.Tabs.Movies" : "Filme"
```

Make a full build.

Now if you Change the user's language to german the Tabs should appear in german.

Hope this helps.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Thanks @JohnRanger

**Comment by Myxville** [comment]
This approach won't work, because Q.Text("Dialogs.Tabs.Persons") in plain HTML is just a text.
But I found workaround.

In html I added ID to the span
`<li><a href="#~_TabInfo"><span id="Db.Default.Person">Person</span></a></li>`

And, in PersonDialog.ts added this
`document.getElementById("Db.Default.Person").innerText = Q.text("Db.Default.Person.EntitySingular");`

Not sure this is an elegant solution, but it works like I need

**Comment by volkanceylan** [comment]
Look in customer dialog template
