### ISSUE TITLE
LookupEditor Returns Blanks

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#2508]
![form with blanks](https://user-images.githubusercontent.com/8422795/28579872-e2aec0a0-712b-11e7-9c09-fc0bae846f63.PNG)

When I use the LookupEditor for an attribute, it gives me a list of blanks.  It lets me search for the values, but not select with a dropdown.

It is a LookupScript on a class that has blank names filtered out in the repository class.  How can I fix this?

**Comment by Estrusco** [comment]
See in you row if the  NameField interface return the correct field you want as description for lookup.

**Comment by leahmayschneider** [comment]
I do want the NameField to have blanks.  However, it makes no sense in a lookup to show the blanks.  I fixed it with custom lookup scripts.
