### ISSUE TITLE
Method in C # call XtpEditorTs

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2509]
I wrote a class in installment.cs which has a GenerateParcemento method where it receives a value, QuantityParcela, generates all the parcels and saves to the database by clicking on the button How do I call this method in ParcelEsEditor.ts.

namespace NeoAdm.Vendas {
    
    @Serenity.Decorators.registerClass()
    export class ParcelasEditor extends Common.GridEditorBase<ParcelasRow> {    
        protected getColumnsKey() { return 'Vendas.Parcelas'; }
        protected getDialogType() { return ParcelasEditorDialog; }
        protected getLocalTextPrefix() { return ParcelasRow.localTextPrefix; }

  
        constructor(container: JQuery) {
            super(container); 
        } 

        public Parcelamento((valor: number, numeroParcela: number, dataVencimento: Date)
        {
               Call method c# g
        }
    }
}

  public class Parcelamento   - (Method in c#)
    {      
        public static void GerarParcelas(double valor, int numeroParcela, DateTime dataVencimento)
        {
            ParcelasRow parcela = new ParcelasRow();

            if (numeroParcela == 0)
            {

                parcela.Valor = valor;
                parcela.DataVencimento = dataVencimento;
                parcela.NumeroParcelas = numeroParcela;
                IDbConnection connection = Serenity.Data.SqlConnections.NewByKey("Default");
                new SqlInsert("parcelas")
                    .Set(parcela)
                    .Execute(connection);
            }
            else
            {
                for (int i = 1; i <= numeroParcela; i++)
                {
                    parcela.Valor = valor / numeroParcela;
                    parcela.DataVencimento = dataVencimento;
                    parcela.NumeroParcelas = i;

                    IDbConnection connection = SqlConnections.NewByKey("Default");
                    new SqlInsert("parcelas")
                        .Set(parcela)
                        .Execute(connection);
                }
            }
        }
    }

**Comment by xareas** [comment]
Debes poner el metodo en el la clase EndPoint ParcelasEndPoint, una vez que haya puesto el metodo, genera las plantillas, y luego invocalo desde el archivo ts.

ParcelasServices.MethodName();

**Comment by alexneocart** [comment]
I can call the method but I can not save the data what I'm doing wrong.
ParcelasEndpoints

 [HttpPost]
        public void Insert(IDbConnection connection, double valor, int numeroParcelas, DateTime dataVencimento, int vendaId)
        {                                   
                
                new SqlInsert("parcelas")
                    .Set(new ParcelasRow
                    {   VendaId = vendaId,
                        Valor = valor,                       
                        DataVencimento = dataVencimento,
                        NumeroParcelas = numeroParcelas,
                    })
                    .Execute(connection);
                  
        }

//ParcelasServices

namespace NeoAdm.Vendas {
    export namespace ParcelasService {
        export const baseUrl = 'Vendas/Parcelas';

        export declare function Create(request: Serenity.SaveRequest<ParcelasRow>, onSuccess?: (response: Serenity.SaveResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function Update(request: Serenity.SaveRequest<ParcelasRow>, onSuccess?: (response: Serenity.SaveResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function Delete(request: Serenity.DeleteRequest, onSuccess?: (response: Serenity.DeleteResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function Retrieve(request: Serenity.RetrieveRequest, onSuccess?: (response: Serenity.RetrieveResponse<ParcelasRow>) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function List(request: Serenity.ListRequest, onSuccess?: (response: Serenity.ListResponse<ParcelasRow>) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        **export declare function Insert(valor: number, numeroParcelas: number, dataVencimento: Date, vendaId: number);**
        

        export namespace Methods {
            export declare const Create: string;
            export declare const Update: string;
            export declare const Delete: string;
            export declare const Retrieve: string;
            export declare const List: string;
            export declare const Insert: void;
            
        }
       

        ['Create', 'Update', 'Delete', 'Retrieve', 'List', 'Insert'].forEach(x => {
            (<any>ParcelasService)[x] = function (r, s, o) { return Q.serviceRequest(baseUrl + '/' + x, r, s, o); };
            (<any>Methods)[x] = baseUrl + '/' + x;
        });
    }
}

**Comment by xareas** [comment]
step 1: put in the file ParcelasEndpoint.cs(file c#)
   public void Insert(IDbConnection connection, double valor, int numeroParcelas, DateTime 
                                         dataVencimento, int vendaId){
}

step 2: Generate template T4, go to Menu Build->Transform All T4 Templates

step 3: And the final step is to call the endpoint
 @Serenity.Decorators.registerClass()
export class ParcelasEditor extends Common.GridEditorBase<ParcelasRow> {    
    protected getColumnsKey() { return 'Vendas.Parcelas'; }
    protected getDialogType() { return ParcelasEditorDialog; }
    protected getLocalTextPrefix() { return ParcelasRow.localTextPrefix; }

    constructor(container: JQuery) {
        super(container); 
    } 

    public Parcelamento((valor: number, numeroParcela: number, dataVencimento: Date)
    {
           ParcelasServices.Insert(valor,numeroParcela,dataVencimiento);
    }
}

sorry for my English
