### ISSUE TITLE
Autosize form dialogs

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#251]
Is it possible to make the dialog auto sized?

**Comment by volkanceylan** [comment]
No

**Comment by volkanceylan** [comment]
It is auto height already, what does auto size mean?

**Comment by dfaruque** [comment]
I want to remove the scrollbars in all forms. 
![untitled](https://cloud.githubusercontent.com/assets/16621563/13066916/eb7f99f0-d494-11e5-8db3-26cd773eee47.png)

**Comment by sayuga** [comment]
To remove the scroll bar you'll have to increase the height for the dialog on the site.less file. That I know of, it is not a dynamic field but you can also add 'Flexify' and 'Maximizable' to the xyzDialog.cs file   allowing you to manually adjust the size of the dialog client side.

**Comment by volkanceylan** [comment]
.MyXYZDialog {
        > .size { .widthAndMin(750px); }
        .dialog-styles(@h: auto, @l: 170px, @e: 520px);
        .s-PropertyGrid .categories { height: auto; }
}

Such a dialog is auto height.
