### ISSUE TITLE
Using data from database to populate ChartJS 

### ISSUE THREAD

**Issue by eclipzd** [volkanceylan/Serenity#2510]
I am trying to create a new page with a ChartJS using data retrieved from a database.  I have thoroughly gone through the ChartInDialog sample, but still having difficulties.  Would anyone have some sample code to be able to do this?

Thanks

**Comment by JohnRanger** [comment]
Hi @eclipzd 

What do you not understand with the ChartInDialog sample?

What do you want to achieve?

Some General hints:
(1) The data is calculated within BasicSamplesEndpoint.cs, in the endpoint: **OrdersByShipper**
(2) The data is loaded from the client-side (the Dialog) within: **ChartsInDialog.ts** in the following line: **BasicSamplesService.OrdersByShipper({}, response => {..**
(3) The data, delivered by the Service call is directly usable by the Morris.js Chart, which is called in the Response Event:

this.areaChart = new Morris.Area({
                    element: this.idPrefix + 'Chart',
                    resize: true, parseTime: false,
                    **data: response.Values,**
                    xkey: 'Month',
                    ykeys: response.ShipperKeys, labels: response.ShipperLabels, hideHover: 'auto'


With Kind regards,

John

**Comment by sayuga** [comment]
https://github.com/sayuga/AdminLTE-Widgets-in-Typscript/tree/master/Charts

**Comment by eclipzd** [comment]
Thank you for your feedback John and Sayuga.  I really appreciate it.  I have been able to replicate the functionality in the ChartInDialog on a Morris Chart, so all good there.  I am wanting to be able to replicate it using the ChartJS, since the Morris Charts are not longer maintained.  It does appear that the attributes are similar - but if you have an example of passing database retrieved data into a ChartJS, then I would welcome the example.  Thanks again - and I am really impressed by this Serenity template.
