### ISSUE TITLE
MasterDetailRelation does not trigger MySaveHandler for detail part

### ISSUE THREAD

**Issue by petebr** [volkanceylan/Serenity#2513]
I have a master detail relation, configured using `[MasterDetailRelation]` decorator.
The detail record has a timestamp and a userid to identify its creator, and I have been able to inject values in the BeforeSave override in MySaveHandler like this:-

```ts
private class MySaveHandler : SaveRequestHandler<MyRow>
 {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                if (IsCreate)
                {
                    Row.UserId = Authorization.UserId.AsInt();
                    Row.Created = DateTime.Now;
                }
            }
```

but only on the master form, the detail seems to bypass these events. 

Is there a good place to inject these values for the detail form, or another way to ensure events are triggered?

**Comment by vinaykulkarni89** [comment]
@petebr me too facing same issue

**Comment by petebr** [comment]
I've got a workaround (hack) for now, which is to loop through all the child records on the master object in its BeforeSave event and fill in any that are null at that point.

`    private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                Row.Events.ForEach(x =>
                {
                    if (!x.UserId.HasValue)
                    {
                        x.UserId = Authorization.UserId.AsInt();
                        x.CreatedDate = DateTime.Now;
                    }
                });
            }`

"Events" is my detail record.

**Comment by petebr** [comment]
format of the code seems to have ignored my line breaks.

**Comment by JohnRanger** [comment]
How did you mark the Code start and end?

I do it with 3x`  (Back ticks) directly followed by the desired language (either TS or CS)

then paste Code with line breaks

then 3x` (back tick)

**Comment by petebr** [comment]
thanks @JohnRanger I have updated my comment and it looks right now.

**Comment by volkanceylan** [comment]
You write your behavior for detail rows, as a detail row behavior.

**Comment by petebr** [comment]
Apologies if I have misunderstood this. 
Are behaviors something more than overriding events in the handlers? In my project anything with `[MasterDetailRelation] ` ignores all overridden events such as `BeforeSave() `.
If there are any instructions that I've missed, can you point them out to me?

Many thanks for your help.

**Comment by volkanceylan** [comment]
MasterDetailRelatin can trigger behaviors for your detail row, but not handlers. Handlers can only be called from endpoints, MasterDetailRelation and any behavioer has no way to know which handler is related to which row.
