### ISSUE TITLE
DateTimeEditor AM/PM time picker

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2515]
Hey all
as the subject implies, how do i set the time picker of a datetimeeditor to show US times with AM/PM .. ive managed easily with the grid using display format but it doesnt seem to be picked up by the form editor...
everything is already set to en-US culture.  kinda feel like im missing something simple...

**Comment by volkanceylan** [comment]
DateTimeEditor doesn't support AM/PM, you need to write your own editor.
