### ISSUE TITLE
Runtime login error

### ISSUE THREAD

**Issue by jez26753297** [volkanceylan/Serenity#2517]
I’ve installed the software onto VS 2017 but I get the error after entering the username and password 
Microsoft JScript runtime error: Object doesn't support property or method 'querySelector'
The code stops on this line 
el = document.querySelector("[data-pace-" + key + "]");

**Comment by jez26753297** [comment]
I've managed to get the demo running now. It would not run using ie9 but Chrome is ok when I disable the debugging

**Comment by volkanceylan** [comment]
only IE11 partially supported, IE8, IE9, IE10 not.
