### ISSUE TITLE
Cascade Delete IIsActiveDeletedRow

### ISSUE THREAD

**Issue by jonathan82** [volkanceylan/Serenity#2518]
I was wondering if Serenity supports cascading delete of entities that implement IIsActiveDeletedRow?  If not what's the best way to handle this? (marking foreign key entities as inactive).  Thanks

**Comment by sayuga** [comment]
I believe it should work fine as long as you add the IIsActiveDeletedRow to both the master table and the cascaded table. You may also need to add the IsActivefield to both tables.

**Comment by volkanceylan** [comment]
Nope, this won't work. Let's say you have deleted a master record by mistake, and before delete there was 30 detail records connected to master of which 2 were deleted. How do we restore 28 detail records when we try to undelete the master?

You shouldn't delete details when master is made inactive. You should write your to query to ignore detail records if master is deleted by a simple join.

Anyway if you have to then override AfterDelete method of master.
