### ISSUE TITLE
When expression is ignoring while generates a query?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#252]
I just add a column with expression to show a field value from related table. But generator ignores these fields with two different sceneraio.

1.  
 SortOrder is appliying but column is not shown

```csharp
 public sealed class TopicRow : Row, IIdRow, INameRow
    {
[DisplayName("LastUpdateDate"), SortOrder(1, true)]
        [Expression("(ISNULL((SELECT top 1 ISNULL(t.UpdateDate, t.InsertDate) FROM Post t (NOLOCK) Where t.TopicId = T0.Id order BY t.UpdateDate,t.InsertDate),ISNULL(T0.UpdateDate, T0.InsertDate)))")]
        public DateTime? LastUpdateDate
        {
            get { return Fields.LastUpdateDate[this]; }
            set { Fields.LastUpdateDate[this] = value; }
        }
```
2.
 Column is not showing anywhere (generated query does not contains this column)
```csharp
[DisplayName("Text"),
        //SetFieldFlags(FieldFlags.ClientSide),
        Expression("(Select top 1 p.Text from [dbo].Post p Where p.Topic=t0.Id order by p.InsertDate)")]
        public String Text
        {
            get { return Fields.Text[this]; }
            set { Fields.Text[this] = value; }
        }
```
Output:
```sql
SELECT TOP 100 
T0.Id AS [Id],
T0.Title AS [Title],
T0.ViewCount AS [ViewCount] 
FROM [dbo].Topic T0 
ORDER BY (ISNULL((SELECT top 1 ISNULL(t.UpdateDate, t.InsertDate) FROM Post t (NOLOCK) Where t.TopicId = T0.Id order BY t.UpdateDate,t.InsertDate),ISNULL(T0.UpdateDate, T0.InsertDate))) DESC, T0.Id;
SELECT count(*)  
FROM [dbo].Topic T0
```

What is wrong with this row or columns?

**Comment by volkanceylan** [comment]
There is nothing wrong. You set default sort order to 1 for LastUpdateDate so repository is sorting by this column by default. Sorted columns doesn't have to be visible.

Second, if you didn't add Text column to Columns, it won't be selected by default. If you put ClientSide flag to it, it won't be selected ever, as it is unmapped (though it is commented there)

**Comment by ademc** [comment]
Oh how did i miss column declerations. I did lots of changes to undestand what happened. But i can not catch because of first rule:

> Sorted columns doesn't have to be visible.

I am so surprised, Why? Is there anyway to override this rule?

**Comment by volkanceylan** [comment]
This is to determine natural order for a row/grid. If you don't want it to be sorted, why put a SortOrder? You can override it in form or grid GetSortColumns

**Comment by ademc** [comment]
No I want to sort by this column but I also want to see in result list. Why do not I want to see column that sort criteria? I have never need "this rule". I guess I **miss**understand something

**Comment by ademc** [comment]
Volkan so sorry about this ugly details. I am obsessed with tiny details I guess. If you do not want to explain you will close. These details are not about your framework actually. I do not want to tire you.

**Comment by volkanceylan** [comment]
SortOrder doesn't control if this column can be sorted. It controls initial sorting order for list. If you put SortOrder to some fields, records are sorted by these fields initially, unless it is overridden somewhere.

**Comment by volkanceylan** [comment]
For example in a customer transactions list, you might want records to be sorted by transaction date descending, then ID descending. So you put SortOrder(1, desc: true) on date and SortOrder(2, desc: true) on ID. Thus records come sorted by date and id desc, even if you don't show ID on screen. User can always change this order by clicking grid column headers.

**Comment by ademc** [comment]
I got over with adding **MinSelectLevel(SelectLevel.Always)** attribute to field i want to get. 
Maybe somebody needs to this info.
