### ISSUE TITLE
Existing Database support?

### ISSUE THREAD

**Issue by TheColonel2688** [volkanceylan/Serenity#2520]
Does serenity support targeting and existing databases? 

I have a desktop program that I have developed using EF code first, it has an existing database.

I would like to use serenity to create a web interface for it. Is this possible? If so are there any tutorials that can get me started?

**Comment by Parbil** [comment]
I am new to this and learning now. I believe it is possible you can simply check the DB creation code (initiation) and add the script which covers your existing db and then you can carry one with serenity way.

**Comment by JohnRanger** [comment]
yes of Course! For this you use sergen from the package Management console from Visual Studio to generate grid and Dialogs fully automated.

For Details please read the serenity guide.

With Kind regards,

John
