### ISSUE TITLE
Typescript function for enum description

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2521]
Hi all! 
There is a typescript function in Serenity to get the name (or description if set) in an enum?

I have get this from code, but work only with name of enum without consider Description attribute. Also in typescripy ss.**Enum** is signed as error.

```ts
 ss.Enum.toString(Enum.MyPersonalEnum, itemSource.EnumField);
```

Thanks

**Comment by volkanceylan** [comment]
Serenity.EnumFormatter.format(YourRootNamespace.YourModule.YourEnumType, value)

**Comment by volkanceylan** [comment]
Also to get identifier (name) of enum value:

Serenity.EnumFormatter.getName(YourRootNamespace.YourModule.YourEnumType)(value)

**Comment by Estrusco** [comment]
Wow, thank you @volkanceylan it works!

The only question: I see that the .format funciont take, as first parameter, a function, the I have used Serenity.EnumTypeRegistry.get("keyofmyenum"). 
Can I avoid the hardcoded key of enum?

This is current code:

```ts
var enumDescr = Serenity.EnumFormatter.format(Serenity.EnumTypeRegistry.get("YourRootNamespace.YourModule.YourEnumType"), enumValue);
```

**Comment by volkanceylan** [comment]
All types including enums are functions in javascript, if it complains just write " YourType as any "

**Comment by Estrusco** [comment]
Wonderful 👍 

Going out of the topic, if you have time see my last pull request for NoClientSideAttribute and tell me what do you think, please.

Best regards @volkanceylan

**Comment by elenaaralla** [comment]
Hello,

I'm trying to use the Serenity.EnumFormatter.format(YourRootNamespace.YourModule.YourEnumType, value) but it doesn't resolve enum.

In my xyzGrid.ts I have this code:

`
import { FrequencyUnit } from '../../ServerTypes/Web/Modules.Administration.SysConfig.Enum.FrequencyUnit';
...

// this.downloadFrequencyUnit = 2
console.log("this.downloadFrequencyUnit = " + this.downloadFrequencyUnit);

// this code cause js error: var enumDescr = Serenity.EnumFormatter.getName("PecDownloaderAdmin.Web.Modules.Administration.SysConfig.Enum.FrequencyUnit")(this.downloadFrequencyUnit)

// this code cause js error: : var enumDescr = Serenity.EnumTypeRegistry.get("PecDownloaderAdmin.Web.Modules.Administration.SysConfig.Enum.FrequencyUnit")(this.downloadFrequencyUnit);

// this code return enum id not description  : var enumDescr = Serenity.EnumFormatter.format(Serenity.EnumTypeRegistry.get("PecDownloaderAdmin.Web.Modules.Administration.SysConfig.Enum.FrequencyUnit"), this.downloadFrequencyUnit);


// this code return enum id not description
var enumDescr = Serenity.EnumFormatter.format(FrequencyUnit, this.downloadFrequencyUnit);`

this is my enum FrequencyUnit.cs:

`using Serenity;
using Serenity.ComponentModel;
using System.ComponentModel;

namespace PecDownloaderAdmin.Web.Modules.Administration.SysConfig.Enum
{
    [EnumKey("SysConfig.FrequencyUnit"), ScriptInclude]
    public enum FrequencyUnit
    {
        [Description("hour")]
        hour = 1,
        [Description("day")]
        day = 2,
        [Description("week")]
        week = 3
    }
}`

and this is the generated file in servertypes.web

'import { Decorators } from "@serenity-is/corelib";

export enum FrequencyUnit {
    hour = 1,
    day = 2,
    week = 3
}
Decorators.registerEnumType(FrequencyUnit, 'PecDownloaderAdmin.Web.Modules.Administration.SysConfig.Enum.FrequencyUnit', 'SysConfig.FrequencyUnit');'


What am i missing?

Thank you,
Elena.
