### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by buddhatripp** [volkanceylan/Serenity#2523]
I have created several permissions in AdministrationPermissionKeys.cs and registered with the assembly as follows:

Administration:Security:Users
Administration:Security:Roles

I have added the permission attributes to the corresponding row classes and ServiceAuthorize and PageAuthorize attributes to the corresponding end points and pages, respectively. However, when I login with a user (not admin) that has no permissions they can still see and do everything. Breakpoints in the PermissionService and GetUserData method never get hit. It's like there is no security at all. Obviously I'm doing something completely wrong, but I have spent 2 days trying to figure it out and it just won't work. Please help! Thank you!

**Comment by Parbil** [comment]
please see your permissions are listed under edit permission screen. if so please see if you can revoke them

**Comment by buddhatripp** [comment]
It still does not work. I verified there are no records in the database assigning permissions to the user or role.

**Comment by Parbil** [comment]
Please check at the level user screen edit permission tree .. is it listed there?

**Comment by sayuga** [comment]
If a user has ReadPermission to a page they will see the page. Make sure that the user is profile on the client side has not been associated with a role or permission that allows them to see the restricted page.
