### ISSUE TITLE
User Level Permissions

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2525]
Hi,

Many of us are looking for  User Level Permissions can any one please explain the this with  an  example. I am looking for a employee level permissions and department permissions to the department head level permissions. How to get this done.

Thanks and Regards,
Srinivas

**Comment by sayuga** [comment]
Permissions are well documented in the manual https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_register_permissions_in_serene.html

Please take a look there first.

**Comment by volkanceylan** [comment]
And there is tenancy sample, and there are several prior issues / wiki.
