### ISSUE TITLE
Firefox gives wrong edit dialog while  chrome and IE give correct dialog for editing 

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#2527]
![image](https://user-images.githubusercontent.com/7609571/28796332-c775a2c0-765a-11e7-9d8d-5223d5ae0502.png)

in Firefox the edit automatically changes to new dialog
![image](https://user-images.githubusercontent.com/7609571/28796439-237ed834-765b-11e7-967b-c1d54ad562e8.png)

**Comment by rcruzfalcon** [comment]
hi, i have the same error in Firefox. With Firefox Developer Edition i can debug and look like  here is the exception :
![image](https://user-images.githubusercontent.com/21364279/28857636-4f49965e-7721-11e7-848e-1819617cb8f6.png)
i continue debug this error, and comment any result.
best regards

**Comment by volkanceylan** [comment]
Hmm, that's a nasty bug with router in Firefox. While i try to fix that add this line to ScriptInitialization.ts to disable router:

```ts
Q.Router.enabled = false
```

**Comment by rcruzfalcon** [comment]
Hi @volkanceylan , i add this line in ScriptInitialization.ts and work perfect!!
Thanks for this wonderful application!
best regards.

**Comment by Parbil** [comment]
Thanks it worked.  What I have noticed is that I have another project in VS 2017 and there it works perfectly without any change. The issues was  in VS 2015 Project.

**Comment by rcruzfalcon** [comment]
In my case was in 2017 Project with the last Serene version ...
