### ISSUE TITLE
What's the user name and password for the demo?

### ISSUE THREAD

**Issue by ghd258** [volkanceylan/Serenity#2528]
http://serenity.is/demo/     the user name and password for the demo?
http://serenedemo.azurewebsites.net/      the user name and password for the demo?

**Comment by srinivas1910** [comment]
Hi @ghd258  

Username   "Admin"
Password  "Serenity"

for Both the links which are mentioned on the login page.
 

Regards,
Srinivas

**Comment by sayuga** [comment]
Please make sure to look through the old issues before posting questions. This has been asked a number of times plus the placeholders for Login page do state the default name and password on them.
