### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by KbraGl** [volkanceylan/Serenity#2529]
I want to draw donut chart which use response values. I get response values truly. But i didnt put it them chart's data. Can you help me ?

Here is my dialog's onOpenDialog method:

protected onDialogOpen() {
            super.onDialogOpen();         
            MovieService.MoviesByGenre({}, response => {
                this.donutChart = new Morris.Donut({
                    element: "sales-chart",
                    resize: true,
                    data: response.Values,
                    hideHover: 'auto'
                });
            })
        }

**Comment by sayuga** [comment]
I've added code to my repository that you can use with the Serenity ChartsInDialog Sample to see all 4 types of charts. 

https://github.com/sayuga/AdminLTE-Widgets-in-Typscript/tree/master/Charts

I'll be adding the other 3 types of charts by end of week (ChartJs, Flot, and InlineCharts)

**Comment by volkanceylan** [comment]
Thanks @sayuga
