### ISSUE TITLE
How to define a default language about this System

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#253]
i have seen the guid about localization. But  how to set my new language to default language.
And when i select my new language in dropdown control, it will do not work?

**Comment by Olricz** [comment]
you can look MovieTutorial. 

[https://github.com/volkanceylan/Serenity-Tutorials](url)

![1](https://cloud.githubusercontent.com/assets/16984654/13032561/e0e74754-d2ff-11e5-9f4d-386147ac7d94.JPG)
![2](https://cloud.githubusercontent.com/assets/16984654/13032562/e4ab5092-d2ff-11e5-99f2-ce70a9f08bea.JPG)

**Comment by volkanceylan** [comment]
You change default language in web.config. If you don't want users to change language, remove dropdown.

**Comment by kuyu7766** [comment]
and how to set language about datepick control ? Thank you

**Comment by volkanceylan** [comment]
From Languages screen add new language

**Comment by kuyu7766** [comment]
SORRY I i try to add new language "zh-cn" , but the DatePicker control always show en. how to set detailly?

**Comment by volkanceylan** [comment]
Set it to zh-CN not zh-cn

**Comment by kuyu7766** [comment]
Sorry For Bothering,  I set system language "zh-CN",  the DatePicker will not show chinese. And I try to set datepicker.defaults language to "zh-CN" in bootstrap-datepicker.js but still not work?  How can i do?  please help me.

**Comment by volkanceylan** [comment]
Are you sure it works with other languages? Try setting to tr-TR for example.

And its not bootstrap datepicker, jQuery UI one.

**Comment by kuyu7766** [comment]
sorry  set language tr-TR the datePicker will change but tr-TR is not chinese.

**Comment by volkanceylan** [comment]
There is no special handling for tr-TR

**Comment by volkanceylan** [comment]
Ok, i have some guess, try removing toLowerCase call in jQuery datepickerinitialization method of Serenity.Externals.js

**Comment by kuyu7766** [comment]
by the way,i have a view in sqlserver ,and how can I show in grid? I try to generate code but not success .I guess view have no primary key and not insert update.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/161

Please use search "feature" in issues and avoid reusing same topic

**Comment by kuyu7766** [comment]
thank you very much!!
