### ISSUE TITLE
Exception in ListResponse

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#2530]
I am trying to import a table with a memo field and it throws this, can anyone help?

![exception](https://user-images.githubusercontent.com/27406433/28825994-44d6b9b0-76c0-11e7-8b88-eaa115865ad3.PNG)

**Comment by javaman63** [comment]
import a table? can you post some more code?

**Comment by volkanceylan** [comment]
That is an SQL error that has no relation to import. Add [Sortable(false)] to your field.
