### ISSUE TITLE
Template.<Type>Dialog is not found in registered script list!

### ISSUE THREAD

**Issue by vladmkd** [volkanceylan/Serenity#2531]
Seeking some help of what am i doing wrong.
I have SereneCore project template in Visual Studio 2017 Community.
 When i start it from VS everything work perfect.
Then i do publish in Custom Folder, deploy its on IIS hosting and start site.
When i open site in browser i log in and everything seems fine BUT when i hit "New Customer" or another " New ..." button or click on some row in table nothing happens.
All i can get is from browser inspector mode:
Uncaught Error: Script data Template.SupplierDialog is not found in registered script list! at u (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:233) at Object.c "ure (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:233) at Object.d "Template (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:233) at r.i.getTemplate (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:234) at r.i "structor (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:234) at r.i "structor (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:234) at r.q "structor (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:239) at new r (Bundle.Site.js?v=h2TVaHEmao8rL4ieFY_ZUw:48) at Function.e.create (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:234) at i.createEntityDialog (Bundle.Libs.js?v=x1qWJe2-Z0sxqSb86aLLFA:244)
Help please, what i miss or do wrong.
Thank you.

**Comment by sayuga** [comment]
does the dialog show or not? I'd start by checking that there are no typo's in the script tags such as the FormScript(). Then I'd also check that when you published to the live folder, that the dialog files were properly published

**Comment by vladmkd** [comment]
To  sayuga. Thank for your participation.
Dialog doesnt show.
If there was typo it wouldnt work when i run it from VS i think.
> Then I'd also check that when you published to the live folder, that the dialog files were properly published
There is the problem i think, but i dont know which files and where should be.

**Comment by vladmkd** [comment]
Found it.
This html templates property "Copy to Output Directory" by default was set to "Do not Copy".
![template](https://user-images.githubusercontent.com/13932905/28917079-14114b9a-784d-11e7-9c75-0ff703c38d05.png)
