### ISSUE TITLE
Sergen : syntax erros despite rebuilt

### ISSUE THREAD

**Issue by DoeJowns** [volkanceylan/Serenity#2532]
For one of my internship mission, I need to use a C# app-builder, serenity.is with Visual Studio 2015. I'm following this official tutorial. More precisely, i followed the begin of the tutoriel p 43. (I'm just adapting it to what I do, I join the code at the end of the post). Nothing is going wrong till p 49. The code generator of the app-builder, sergen.exe, is creating some code (I don't have the detail of what he creates but it doesn't seems to be important).

They ask me to "rebuild all", what I did, and everything should work smoothly.

Nevertheless, when i compile and execute my code, I've got a bunch of syntax error which shouldn't happen.

Please find code and screen capture [here](https://stackoverflow.com/questions/45459791/sergen-syntax-erros-despite-rebuilt)

Is there any Serenity user which could help ?

Feel free to ask any other details

**Comment by sayuga** [comment]
for straters. You did a big mistake with the naming of the columns.

**Comment by DoeJowns** [comment]
Could you provide more details please x) ?

**Comment by sayuga** [comment]
Well, DB's have restrictions on the use of certain characters on the name of the columns

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/154c19c4-95ba-4b6f-b6ca-479288feabfb/characters-that-are-not-allowed-in-table-name-column-name-in-sql-server-?forum=databasedesign

If what you want is to have the field sdisplay the "<---" and "--->" on the client side, you  should just create the fields and use the DisplayName() attribute to deal lwith the display of the field name.

**Comment by DoeJowns** [comment]
Ooh !! Ok ! Thank you a lot 👍 :D

**Comment by sayuga** [comment]
have you worked much with DB's before?

**Comment by DoeJowns** [comment]
Not so much.. Some SQL Request on already-created DBs but no real DB construction
