### ISSUE TITLE
dialog editor refreshing drop-down on parent dialog

### ISSUE THREAD

**Issue by buddhatripp** [volkanceylan/Serenity#2534]
I am using the Serenity user interface for users and roles. We wish to support multiple roles, but we have to specify a primary role. I would like to do this on the edit user dialog via a drop-down that contains roles currently assigned to the user. However, I need the options in the primary role drop-down to refresh when the user's role assignments change via the edit user roles dialog. How can make the drop-down refresh? Thank you!

**Comment by volkanceylan** [comment]
Q.reloadLookup
