### ISSUE TITLE
isCloneMode

### ISSUE THREAD

**Issue by KbraGl** [volkanceylan/Serenity#2536]
why methods content which defined in Serenity.EntityGrid, always return false ??
![unnamed 1](https://user-images.githubusercontent.com/2952500/28920329-f38cf042-7859-11e7-81bb-e19134010a9e.png)
![unnamed](https://user-images.githubusercontent.com/2952500/28920328-f38c7ca2-7859-11e7-9793-a67ec855d534.png)

**Comment by volkanceylan** [comment]
it is a method that might be overridden in derived classes

**Comment by KbraGl** [comment]
Override edilmiş örnek bir kullanımı var mı acaba ?

**Comment by volkanceylan** [comment]
TypeScript language guide
