### ISSUE TITLE
Multilevel Recursive Multitenant

### ISSUE THREAD

**Issue by Hochmah** [volkanceylan/Serenity#2538]
Has anyone implemented this scenario?

I have an Partner Manager entity and it's an user that can have many Partners, that is a Tenant (can see only its records), but this Partner can enroll Companies, that are also users and Tenants, and this Companies can have Employees, that are users, and also can see only their records.... 

It's like an hierarchy three and each level must see only its own records and its children records.

Can anyone point me into the right direction?

**Comment by volkanceylan** [comment]
I've implemented more complex scenarios for some customers. Anyway, multi tenancy tutorial is what you should start at.

**Comment by TechAspirant** [comment]
@Hochmah have you implemented like mentioned case ? If so can you please share sample code ?
