### ISSUE TITLE
Wiki new How to Create Lookup Editor for code description tables

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2539]
Hi all! 

I have added new wiki entry for How to Create Lookup Editor for code description tables

https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables

I hope it will be useful for you, enjoy ;)

![cattura1](https://user-images.githubusercontent.com/16304015/28995017-d2a6d0f2-79dd-11e7-903d-2740aa74374a.JPG)

![cattura2](https://user-images.githubusercontent.com/16304015/28995018-d72a7912-79dd-11e7-8f28-7ff3b4004e4d.JPG)

**Comment by Magik3a** [comment]
I didn't get anything from your description. Could you please add more info for which files are created and when i try your code, there is 2 errors 
`
         container.data("codeName", opt.codeName);
         container.data("descrName", opt.descrName);
`

should be 

`
         container.data("codeName", opt.codeFieldName);
         container.data("descrName", opt.descrFieldName);
`

**Comment by Estrusco** [comment]
I have fixed errors. Tnx.
You can create two code file, one .ts (for example in common/helpers dir) that contains editor class and options, and another file .cs with code for attribute.

**Comment by stixoffire** [comment]
@Estrusco  I am using your code, but I have an issue with MasterDetail Relations and the DropDown there - it shows the Name, but the Description shows 'undefined'.

The code works fine for a non-related table. 
My issue is in the Master-Detail (Details Relation I do not get the description - only the name field.)
I tried placing the [Lookup attribute on the Fields in the Details .

So I have for eample:
Master:Employee Where EmpId is PK
Detail:Training Where TrainId is PK

On the Details Tab of the Employee Form the List<Training> , I utilize the TrainId field for the drop down with TextualField of Name .

I tired putting the lookup in my EmployeeTraiining Row and tried the Form as well 
(individually and also both for grins & giggles)..

[LookupCodeDescr(typeof(Modules.Training), "Name", "Description"]
Int32? TrainId 

Any Idea what could be wrong .. is there a reason I am not getting the description field in the Detail Relationship 
I am using in the Employee [MasterDetailRelation ... blah blah] on my TrainingRow ..
