### ISSUE TITLE
LastDirectoryUpdate

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#254]
Hi,
LastDirectoryUpdate What is the purpose ? How to use ? 

Thanks.

**Comment by volkanceylan** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_authenticate_with_active_directory_or_ldap.html

It is used to store last directory update from active directory/ldap

**Comment by Olricz** [comment]
ok. thanks.
