### ISSUE TITLE
[MasterDetailRelation] editor grid cannot be sorted and is ordered by a random column

### ISSUE THREAD

**Issue by petebr** [volkanceylan/Serenity#2540]
This can be replicated in the MovieDB tutorial. The sub-grid editor of movie cast cannot be sorted by using `SortOrder` or by clicking the group heading. 
In the Northwind Orders page, try sorting the order detail grid. Same problem.

In my project I've included the my detail id in `xyzColumns.cs` just to double check and it's ordering based on a random column called Notes which is a varchar field.

In the guide, "The Cast and Characters they Play", the last paragraph begins to talk about `MasterDetailRelation` and how it ..
   _intercepts Retrieve/Save/Delete handlers and methods we had overridden before and performs similar operations._
but not how to affect the result. I'd like to be able to specify which column to sort by or just default to its own Id field would work in this case.

**Comment by volkanceylan** [comment]
In memory grid editors doesn't support any sort options.

**Comment by petebr** [comment]
That's fair enough.
My grid is sorted by its "Notes" field. Any idea how that came to be selected or how I might influence that choice? The table has in it, ID, MasterTableId, Notes (varchar), user id, date created

**Comment by volkanceylan** [comment]
It's probably sorting by name field. Try adding [SortOrder(1)] on ID column

**Comment by petebr** [comment]
Yes, already tried that but it was ignored.

**Comment by jplee75** [comment]
If anyone comes up with a working solution for sorting detail grid I would love to hear it - want to sort my detail by month and its just not happening

**Comment by volkanceylan** [comment]
You need to add [SortOrder(1)] in your Row.cs, not Columns.cs

**Comment by petebr** [comment]
Confirmed. Thank you @volkanceylan

**Comment by yaseenhejazi** [comment]
You can sort the list by adding these codes to editor:

`
        protected layout(): void {
            super.layout();
            this.setEntities(this.view.getItems());
        }
`

`
        protected setEntities(items: XYZRow[]) {
            this.view.setItems(this.sortedItems(items) , true);
        }
`

Add your sorting logic in sortedItems function

Sample code:

`
        sortedItems(items: XYZRow[]): XYZRow[] {
            return items.sort((i1, i2) => (i1.Notes == i2.Notes) ? 0 : (i1.Noyes > i2.Notes) ? 1 : -1);
        }
`
