### ISSUE TITLE
Filter a Stored Procedure with a Quickfilter/Combo/Lookupeditor

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#2541]
it this possible? Anyone have an working example of this?

Thanx!

**Comment by volkanceylan** [comment]
There is stored proc with date filter sample already.

**Comment by fremar83** [comment]
Hi all,
I'm trying to use a stored procedure on a lookupEditor.   
I have build my code arounr CustomerGrossSales exemple.. When I try to add a lookupScript to the "MyStoredProcedureRow" (CustomerGrossSalesRow in the exemple), I have a error  Invalide object name 'dbo.MyStoredProcedure'. Code finds this name in the table attribute of the row.

Many Thanks !
