### ISSUE TITLE
Disable hotkey

### ISSUE THREAD

**Issue by MaradiagaSistemas** [volkanceylan/Serenity#2542]
Hi Volkan, 

Thank you for this amazing framework,

I Have a situation, sometimes users press Alt+A hotkeys to Update a Records, but when is first time (Creating a new Record) sometimes this record get duplicated.

Is there any way to Disable this Hotkey (Alt+A) ?

Thank you!

**Comment by volkanceylan** [comment]
Hide the button.

**Comment by MaradiagaSistemas** [comment]
Thank you!
