### ISSUE TITLE
Many to Many Foreign Key Support?

### ISSUE THREAD

**Issue by rodneykendall** [volkanceylan/Serenity#2543]
I have the following entity relationships:
Primary Table: Quotes
     Primary Key: QuoteId
Many-to-Many Table: QuoteParts 
     Foreign Key: QuoteId
     Foreign Key: PartId
Secondary Table: Parts
     Primary Key: PartId

Using the various examples available, I have the QuoteParts grid showing up on the Quotes page, which is a great first step.  The pop up from the QuoteParts grid to show the QuoteId and Partid works and I have the 'InPlaceAdd' flag enabled so the user can go to the Parts record and see the full details in another dialog.  What I'd like to do is get the part details, like the name and model number, from the Parts table to display in the QuoteParts grid.  Is that possible to do?

**Comment by volkanceylan** [comment]
See mapping guide.
