### ISSUE TITLE
Quickfilter not working for LookupEditor

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#2544]
I have a quick filter on a field that is a look up.  The quick filter works but it isn't a dropdown.  It is a drop down in form.  How do I fix this?

Filter:
![not dropdown](https://user-images.githubusercontent.com/8422795/29073941-8966c61e-7c1b-11e7-8eb6-9747eacda71e.PNG)

Columns Code:
![columns](https://user-images.githubusercontent.com/8422795/29073962-a1371b2c-7c1b-11e7-99d5-4725361eb79b.PNG)

Row Code:
![rows](https://user-images.githubusercontent.com/8422795/29073974-af40c38a-7c1b-11e7-926a-4853623ae630.PNG)

**Comment by AlperanQ** [comment]
Hi,
Use LeftJoin instead of InnerJoin. Adding TextualField can also be useful.

**Comment by leahmayschneider** [comment]
Neither of those things help.  I don't believe it is the join.  The join works.  I can type in the word "Bank" and it will filter for those that are banks.  The only issue is the drop down in columns.

**Comment by volkanceylan** [comment]
He is telling truth. Use LeftJoin and proper ForeignKey attribute.
