### ISSUE TITLE
Cannot Get Rid of Logged In User Between Browser Sessions

### ISSUE THREAD

**Issue by buddhatripp** [volkanceylan/Serenity#2545]
I have an application that should be able to force the user to login when the browser is closed then reopened. Serenity.Authorization.UserDefinition is not null on the new session. I have added the following handler, but it is still not null (and IsLoggedIn is true). The application session is expired, but the user is still authenticated. How can I force a user logout?

protected void Session_Start(object sender, EventArgs e)
{
	UserRetrieveService.RemoveCachedUser(Convert.ToInt32(Serenity.Authorization.UserId), Serenity.Authorization.Username);

	if (Serenity.Authorization.IsLoggedIn)
	{
		Session.Abandon();

		FormsAuthentication.SignOut();

		var autheticationManager = HttpContext.Current.GetOwinContext().Authentication;
		autheticationManager.SignOut();

		Serenity.WebSecurityHelper.LogOut();
	}
}

**Comment by buddhatripp** [comment]
I got around the problem with a custom ActionFilter that checks if the session is null. If the session is null, then it redirects to the account signout. I just expected that when I perform all of the sign out operations above that it would actually sign out. It was not because it was still trying to load _Layout.cshtml, but throwing an error because the session is null.

**Comment by AlperanQ** [comment]
Hi,
Serenity doesnt use session at all. It only adds a auth cookie that gets deleted when browser is closed. The issue you are having is probably about, Chrome is allowed to run in background, thus it is not closing, or restore my tabs feature which persists cookies even if you close your browser. Same thing happens in Gmail for example. So, turn them off better.
