### ISSUE TITLE
Data Binding 

### ISSUE THREAD

**Issue by vishmanthisuresh111** [volkanceylan/Serenity#2549]
How to bind Data using Label and Textbox ,Checkbox (or) Data from the Database is not Accessing by the textbox

**Comment by sayuga** [comment]
Please add more detail to your question. What would you like to accomplish?

**Comment by vishmanthisuresh111** [comment]
The grid contains columns like amount,name,checkbox etc.when the user clicks the one or more checkbox then the particular row amount should be calculated and display on the grid footer. or it can subtracted from the total amount.
