### ISSUE TITLE
not able to filter data in tab

### ISSUE THREAD

**Issue by onkarbahirat22** [volkanceylan/Serenity#255]
I want to show data in tabs just like customer and his orders.
In my case its employee and his bank details,in Employee grid when i set BankGrid.EmpId = (entity.EmpId).ToString();  this filters data but addEmployee button is not functionable.It shows error
TypeError: Cannot read property 'toString' of undefined.
and if i comment BankGrid.EmpId = (entity.EmpId).ToString(); then it doesn't filter bank data according to employee

Thanx in Advance...

**Comment by volkanceylan** [comment]
Where are you writing this code? Your entity.EmpId is null. You should check for null before calling toString. Write such code in LoadEntity method.

**Comment by onkarbahirat22** [comment]
In Employee Dialog
namespace Serene.Employees
{
    using jQueryApi;
    using Serene.Employees.Employees;
    using Serenity;
    using System.Collections.Generic;

    [IdProperty(EmployeesRow.IdProperty), NameProperty(EmployeesRow.NameProperty)]
    [FormKey("Employees.Employees"), LocalTextPrefix(EmployeesRow.LocalTextPrefix), Service(EmployeesService.BaseUrl)]
    public class EmployeesDialog : EntityDialog<EmployeesRow>
    {
        protected EmployeesForm form; //change in Exam master
        private EmployeesEmployeeBanksGrid BankGrid;
       // private ExamSectionDetailsGrid SectionDetailGrid;
      //  private ExamQuestionsGrid QuestionGrid;

        public EmployeesDialog()
        {
            //form = new EmployeesForm(this.IdPrefix);
            BankGrid = new EmployeesEmployeeBanksGrid(this.ById("BankGrid"));
            BankGrid.Element.FlexHeightOnly();
            tabs.OnActivate += (e, i) => this.Arrange();

            //SectionDetailGrid = new ExamSectionDetailsGrid(this.ById("SectionDetailGrid"));
            //SectionDetailGrid.Element.FlexHeightOnly();
            //tabs.OnActivate += (e, i) => this.Arrange();

            //QuestionGrid = new ExamQuestionsGrid(this.ById("QuestionGrid"));
            //QuestionGrid.Element.FlexHeightOnly();
            //tabs.OnActivate += (e, i) => this.Arrange();
        }
        protected override void LoadEntity(EmployeesRow entity)
        {
            base.LoadEntity(entity);
           // tabs.SetDisabled("BankInfo", this.IsNewOrDeleted);
           BankGrid.EmpId = (entity.EmpId).ToString();
           
        }

    }
}

In EmployeeEmployeeBanksGrid

using System;
using System.Collections.Generic;
using System.Text;
namespace Serene.Employees.Employees
{
    using jQueryApi;
    using Serene.Employees;
    using Serene.Employees.Employees;
    using Serenity;

    [DialogType(typeof(EmployeesEmployeeBanksDialog))]
   public class EmployeesEmployeeBanksGrid : EmployeeBanksGrid
    {
        public EmployeesEmployeeBanksGrid(jQueryObject container)
            : base(container)
        {
        }
        protected override void InitEntityDialog(string itemType, Widget dialog)
        {
            base.InitEntityDialog(itemType, dialog);
            Serenity.SubDialogHelper.Cascade((EmployeeBanksDialog)dialog, this.Element.Closest(".ui-dialog"));
        }
        protected override void AddButtonClick()
        {
            EditItem(new EmployeeBanksRow
            {
                EmployeeId = int.Parse(employeeId)
            });
        }

        protected override string GetInitialTitle()
        {
            return null;
        }
        protected override void CreateToolbarExtensions()
        {
            base.CreateToolbarExtensions();

           // CustomerFilter.Element.Closest(".quick-filter-item").Remove();
        }

        protected override bool GetGridCanLoad()
        {
            return base.GetGridCanLoad();
        }

        private string employeeId;

        public string EmpId
        {
            get { return employeeId; }
            set
            {
                if (employeeId != value)
                {
                    employeeId = value;
                    SetEquality(EmployeeBanksRow.Fields.EmployeeId, EmpId);
                    Refresh();
                }
            }
        }
    }
}

**Comment by volkanceylan** [comment]
BankGrid.EmpId = entity.EmpId == null ? null : entity.EmpId.ToString();

**Comment by onkarbahirat22** [comment]
thanx, I have changed my code
 BankGrid.EmpId = entity.EmpId == null ? null : entity.EmpId.ToString();
but when i click on new Employee it shows all records from EmployeeBanks 
and also addEmployeeBanks is not functioning it is giving jquery error
 Syntax error, unrecognized expression: #Serene_Employees_Employees_$EmployeesEmployeeBanksDialog70_Form

**Comment by volkanceylan** [comment]
Please check sample again. Your GetGridCanLoad is empty.

**Comment by onkarbahirat22** [comment]
great man,this solved my issue

**Comment by onkarbahirat22** [comment]
Any Idea on jquery error,not able to add bank details...

**Comment by volkanceylan** [comment]
I have no idea, wonder where does $ in this expression comes from:

#Serene_Employees_Employees_$EmployeesEmployeeBanksDialog70_Form

**Comment by volkanceylan** [comment]
Hope you resolved issue
