### ISSUE TITLE
Q.enumerateTypes ignores type when any namespace part doesn't start with capital letter

### ISSUE THREAD

**Issue by isukces** [volkanceylan/Serenity#2550]
Some types like `rootname.namespacePart.Type` are ignored by `Q.enumerateTypes`. 
I've found that it's because condition
```
if (k.charAt(0) < 'A' || k.charAt(0) > 'Z')
 continue;
```
When full type name is `rootname.NamespacePart.Type` everything works properly.

**Comment by volkanceylan** [comment]
This is by design. Every function in javascript can potentially be a type. Serenity has to enumerate all types in root namespaces. It limits this journey to members whose name starts with capital letter to skip ordinary functions. Always use Pascal case for types, both in C# and Javascript.

**Comment by volkanceylan** [comment]
Also namespaces.

**Comment by isukces** [comment]
Thank you for explanation. Response time is impressive.  :)

**Comment by isukces** [comment]
There is workaround for such special case:
Add 
`Q.Config.rootNamespaces.push('rootname.namespacePart');`
to  
`ScriptInitialization.ts`

**Comment by volkanceylan** [comment]
I wouldnt recommend that
