### ISSUE TITLE
Updating Serenity NuGet Packages Causes a Bug about dialogopen

### ISSUE THREAD

**Issue by Felix-ZL** [volkanceylan/Serenity#2553]
Dear @volkanceylan  I update the Serenity NuGet Packages today, then I found that a "#new" appear in the end of address bar,so that the "new dialog" will not be closed when I refresh the page.
But, there is a bug ,When I open a custom dialog using "dialogOpen",the dialog will flash bach in Firefox,and it even doesn't appear in IE.
At the same time ,there will be a "#!(n)" in the end of address bar.
best regards.

**Comment by volkanceylan** [comment]
This is not a bug, works as intended. Take your time to read changelog, and recent issues.
