### ISSUE TITLE
back office development

### ISSUE THREAD

**Issue by thilandakshina** [volkanceylan/Serenity#2556]
Dear Volkanceylan,

Our Company have an idea to use this kind of framework to implement our **booking tool back office system.**
actually we are international company and we have to maintain our records and we have to keep this as fast and reliable system.
could you please give me some advice regarding this framework?
I already know this framework have better security ,reduce development time by using better software design practices.
I want to know how far we can expand this system? because current ui already have limitation as i can see.
can you recommend your framework to our development? or do we need to move asp.net mvc with solid framework , i mean different approach?

we have to call multiple api for our booking tool,are those kind of things possible with this framework?
as i know it is possible because this framework built on asp.net mvc. but can you please suggest me about this.

**Comment by volkanceylan** [comment]
We are using Serenity for pretty complex apps with 100k users, and it is built on Asp.Net MVC. Answer is yes but depends on your skills, not just the platform.

**Comment by thilandakshina** [comment]
Dear Volkanceylan,

Thanks for your quick reply and yes we have good team that can take this kind of challenges. 
i want to know if we use this then do we need to get Enterprise Edition? or can we build this system on free version? what do you suggest on that?

can you please suggest me sample sites that use this framework? (if it is possible)

and yes our one is very complex system. currently we estimate our annual booking can be more than 100,000 and there are more than 10 agents and need to handle agents by using this system,i mean agent commissions like wise.but this using this system we are planing to handle other booking tools also because it is back office.

**Comment by volkanceylan** [comment]
Enterprise comes with direct support and has additional features. As you probably have more than one or two developers thats the licence level you need. This doesnt mean you cant go with free version but you ll rely only on community support and getting premium would speed up development, avoid time lost on troubles

**Comment by thilandakshina** [comment]
yes i can see.what do you think about Current UI?
This dashboard template looks old is it possible to customize  completely according to our preferences

**Comment by volkanceylan** [comment]
Well, i dont think its old, its one of most popular open source templates, AdminLTE. Anyway you could replace it with another, using some CSS skills.

**Comment by thilandakshina** [comment]
Thanks for quick reply Volkanceylan.
yes its great, may be we need community support i guess.i ll looking to solve that issue in future.
this is my last question regarding this framework, what are the existing limitations on this framework ,which we should consider before our development?

**Comment by volkanceylan** [comment]
I dont know any, try and see
