### ISSUE TITLE
Request an example to select more than one item.

### ISSUE THREAD

**Issue by Takecarecom** [volkanceylan/Serenity#2557]
Click on add item and display product selection screen. You can select more than one item by color search, and when you select the item and enter the quantity, submit it to the Order detail.

![222](https://user-images.githubusercontent.com/13514630/29167413-85efae94-7df4-11e7-95d1-7e82a6126289.png)

Thank You

**Comment by volkanceylan** [comment]
This example is already available in premium.

**Comment by Takecarecom** [comment]
@volkanceylan 

I can not go to the source code preview.

![no](https://user-images.githubusercontent.com/13514630/29168592-b4585984-7df9-11e7-9acb-bf07b8e29191.png)

**Comment by volkanceylan** [comment]
You cant
