### ISSUE TITLE
Serenity.Externals.ts: validateOptions

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#2558]
Dear @volkanceylan,
I found a little problem with the validateOptions function (Serenity.Externals.ts):

**ignore: ":hidden"** should be **ignore: options.ignore**
 
export function validateOptions(options: JQueryValidation.ValidationOptions) {
        return $.extend({
            ignore: options.ignore,
            meta: 'v',
            errorClass: 'error',

.....

Otherwise the ignore setting will be always defaulted to ":hidden"

Let me know
Bye

**Comment by volkanceylan** [comment]
No, you cqn override it

**Comment by marcobisio** [comment]
Ah and which is the right approach in order to override such parameter?

**Comment by volkanceylan** [comment]
Whatever you pass in options will override defaults. Extend overrides from left to right

**Comment by marcobisio** [comment]
Uhm but if I try to add a global ignore in the validate js library, it doesn't work.
On the other side, after the patch above, the global ignore it's working fine...
Do you suggest to override the entire validateOptions method?

Thanks!

**Comment by volkanceylan** [comment]
In dialog.cs there is a getValidatorOptions method, you should override that.
