### ISSUE TITLE
Can we set addEqualityFilter for enum with readonly 

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#256]
I want to  set addEqualityFilter  for enum with readonly values.Is it possible in serenity?

**Comment by volkanceylan** [comment]
What does it mean enum with readOnly values??

**Comment by nilimajagtap** [comment]
I want to load data  by default set  value from dropdown.and in my case the dropdown I want to use is enum type.
for ex.in dropdown I have multiple options  like accepted,pending,checked etc. and I want to Load only pending results.
Can u guide me how to do this using addEqualityFilter

**Comment by volkanceylan** [comment]
I think you are trying set initial value of an enum filter editor:

```cs

AddEqualityFilter<EnumEditor>(Fields.MyEnum,
                options: new EnumEditorOptions { EnumKey = "ABC" },
                init: e =>
                    {
                        e.Value = ((int)TheEnum.SomeValue).ToString()
                    });
```
