### ISSUE TITLE
EF Auditing.

### ISSUE THREAD

**Issue by saeedahmad101** [volkanceylan/Serenity#2560]
Hi, i need to track each property's value change or addition / modification / deletion of records in a sql database.

is it possible to integrate this auditing package with serene

[EF+ Audit](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#autosave-audit)

**Comment by sayuga** [comment]
I believe you'll have to map it in yourself but there is a Auditing sample in the Wiki from a fellow Serenity User.

**Comment by saeedahmad101** [comment]
yes, got it working after a bit of struggle 👍
