### ISSUE TITLE
Cosuming Serenety Api Web Post File

### ISSUE THREAD

**Issue by ninoraccoon** [volkanceylan/Serenity#2561]
Hello again an thank for the old reponse I tried to send a file To the serene web Api file uoload and alway my request.files is empty here is may code:

**Comment by ninoraccoon** [comment]
sorry bad key:
`var client = new JsonServiceClient(BaseUrl);
            client.Post<ServiceResponse>("Account/Login",
                new LoginRequest
                {
                    Username = User,
                    Password = Pass
                });
 MultipartFormDataContent content = new MultipartFormDataContent();
            ByteArrayContent fileContent = new ByteArrayContent(System.IO.File.ReadAllBytes(filepath));
            System.Net.Http.StringContent txtContent = new StringContent("lalala");
            fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment") { FileName = filename };
            content.Add(fileContent);            
            var value = client.Post<Object>("File/TemporaryUpload1", content);`
cosuming other services there is no problem.... but with this my request alway have troubles on FileController, is empty.

**Comment by fernandocordero** [comment]
Look at **ProductExcelImport** tutorial from **BasicSamples** it performs a file upload. In this case Excel but you can restrict the file format.

**Comment by ninoraccoon** [comment]
thanks , I make it similar , in my case my client was an .net api, no js, finally I doing using the serene architecture style creating a file model
public class FilesModel
    {
        public string Nombre { get; set; }
        public byte[] Content { get; set; }
    }
and an endpoint for process that request.

**Comment by fernandocordero** [comment]
Good deal. Don't forget to close the ticket if it's resolved.
