### ISSUE TITLE
Load Image on Dialog.js Picture Box

### ISSUE THREAD

**Issue by jimran** [volkanceylan/Serenity#2563]
I want to load the image using the image path provided behind the search button. 

1. I created a search button on visitDialog.js
2. I wrote ajax call for content from db
3. I populated all the fields on form
4. How to populate Image in image box from js script

Please help

**Comment by sayuga** [comment]
I'm not sure I understand what you mean. Are you trying to simply add a image using the dialog ? Just use the ImageUploadEditor. BasicSamples also has a sample for displaying the images in-line in the grid
