### ISSUE TITLE
2.0 migration

### ISSUE THREAD

**Issue by gdeacon** [volkanceylan/Serenity#2564]
I have serene project written with version 1.9.19.  I'm following the Migration steps in the How-to guide

https://volkanceylan.gitbooks.io/serenity-guide/howto/how_to_upgrade_to_serenity_2_typescript.html

I'm not adding the Typscript integration at the moment.  However when I try to create the new CodGeneratonHelpers ttinclude file the link for the file is brokern and I've tried snooping around github for it but nothing is comming up.

Has there been an update to this How-To?  Also I'm getting build errors on my dialog code in the script project GetEntitySingluar method is no longer defined.

Thanks in advance for any help.

ps if this has been reported I apologize in advance
-Garrett

**Comment by gdeacon** [comment]
OK, Here's some additional information and I know you guys are busy so if this has been covered please let me know...

Here's what I've done to help diagnose...

1. Upgraded from 1.9.19 to 2.0.0
2. Rebuilt my applicaiton
3. Attempted to run the applicaiton.
4. The main table "Programs" displays but theres an HTTP Get error of...
GET http://localhost:53051/Scripts/Serenity/Serenity.Script.Core.js?v=2017341704 

This seems like a generated entry what could be preventing this file to load?

Thanks again in advance

**Comment by volkanceylan** [comment]
They are moved up two levels.

https://raw.githubusercontent.com/volkanceylan/Serene/master/Serene/Serene.Web/Imports/CodeGenerationHelpers.ttinclude

Try to update to latest, not 2.0.0, but you need to follow other upgrade guides in issues, and it won't be easy, you are somewhat late to upgrade.

**Comment by gdeacon** [comment]
Hmm would it be better to just start with a 2.10.x project and then manually migrate my code to the new framework?  Sounds like from a time perspective it might be a wash.  Thanks for the response I know I'm on an older version the project I prototype d with the older version got revived

-Garrett

**Comment by volkanceylan** [comment]
You might also try that but not sure about what changed since.
