### ISSUE TITLE
The term 'sergen' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by PedroHFranco** [volkanceylan/Serenity#2568]
Hello,
I have created a new project, and i trying to make a Sergen, gotting this error from web Sergen.
This is a AspNetCore BETA Serene Project.

dotnet --info:
![image](https://user-images.githubusercontent.com/10779853/29409954-dec0a0f2-8324-11e7-83c3-f4ed81e38115.png)

Visual Studio versions:
![image](https://user-images.githubusercontent.com/10779853/29409977-fc8ff696-8324-11e7-9da1-d9ac8cc88e5c.png)

The error:
![image](https://user-images.githubusercontent.com/10779853/29378081-23e64ea2-8294-11e7-9f35-980129c5d412.png)

and this when type 'sergen' on Package Manager Console, i'm gotting this error:

> sergen : The term 'sergen' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + sergen
> + ~~~~~~
>     + CategoryInfo          : ObjectNotFound: (sergen:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

I have closed and opened project a lot of time.
I already reinstalled the serene.vsix
I restarted the computer
And tryied to create a blank solution and type sergen on pmc.
None of this solutions works for my case, as i seen in all topocis i have found.

I also tryed in other computer and got the same.

Have something more to do?

**Comment by JohnRanger** [comment]
in the worst case you can start sergen outside of VS to create the desired Code.

I had to do this on several cases.

Normally, this resolves after closing and reopening VS but as in your ase it seems not to resolve.

Hope this helps a bit.

With Kind regards,

John

**Comment by PedroHFranco** [comment]
Yeah, cause of this error i'm using .NET 4.5 instead of Core.
I have looked for the sergen inside packages/SerenityCodeGerenator/tools , but when i create it in .Net Core even this folder has been created, the packages dosen't exists.

Using .NET 4.5 is running normal. But .Net Core are better.

**Comment by volkanceylan** [comment]
We don't support .NET Core 2 yet

**Comment by PedroHFranco** [comment]
Thx,.

**Comment by PedroHFranco** [comment]
After

**Comment by PedroHFranco** [comment]
I degread my version of .net core now i'm gotting this erro:

![image](https://user-images.githubusercontent.com/10779853/29847493-45fea008-8cf2-11e7-8d89-0b477ee327b4.png)

My .net version:

![image](https://user-images.githubusercontent.com/10779853/29847523-643afb52-8cf2-11e7-9b50-6c3cdc69f25a.png)

**Comment by guluehmedova** [comment]
install Microsoft.EntityFrameworkCore.Tools
