### ISSUE TITLE
How to passing value to grideditordialog

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#257]
How to pass Approval Type selected value to equipment editor dialog, after click add new equipment?

![editordialog](https://cloud.githubusercontent.com/assets/6382278/13045460/0466066e-d406-11e5-8b1d-9f6582792d29.png)

![editor](https://cloud.githubusercontent.com/assets/6382278/13045377/89929b28-d405-11e5-93a9-8f098ec6e495.png)

**Comment by volkanceylan** [comment]
var dialog = new XYZDialog();
dialog.LoadEntityAndOpenDialog(new XYZEntity {
      SomeValue = form.MyField.Value
});

**Comment by volkanceylan** [comment]
Btw, how did you find about data localization feature? I don't remember explaining it anywhere :)

**Comment by volkanceylan** [comment]
Oh, not, you just opened dialog without loading anythings, thats why its visible.

**Comment by stickybro** [comment]
I think now you need to explain it somewhere JaiQ :P

**Comment by rudianto2008** [comment]
Hi Jaiq,

Thanks for the answer but i dont want to create new dialog, currently dialog is come from default dialog editor like master detail in tutorial below.

` [DisplayName("Equipment List"), MasterDetailRelation(foreignKey: "AppFormID"), ClientSide]
  public List<ApprovalEqpRow> Equipments
  {
            get { return Fields.Equipments[this]; }
            set { Fields.Equipments[this] = value; }
  }`

If i create new dialog i will missing all function in that dialog like save and delete.

Regards

**Comment by rudianto2008** [comment]
Problem was solve. 

Thanks Jaiq.

**Comment by stixoffire** [comment]
@fazanan Sure would like to see your solution . I have links in the editor - I want my editordialog as readonly  when the parentdialog sets the editor to read only - my links are still active and I need to be able to toggle the editordialog readOnly.
