### ISSUE TITLE
How to change range of years in "datetimepicker"?

### ISSUE THREAD

**Issue by sebacamino** [volkanceylan/Serenity#2570]
I want to add more years to those that come by default. Can any one help me?
Thanks
![captura](https://user-images.githubusercontent.com/25614080/29389758-7152ae3c-82c2-11e7-870e-ed3c36da00b0.PNG)

**Comment by gguadalupe** [comment]
Hey Seba,
I believe you have an attribute in your xyzRow. You can set you max and you min value.

Check issue #1622
You will find what you need there.

Gus.

**Comment by sebacamino** [comment]
Thanks for your help gguadalupe! 
How i can set year? 
Because show me this error: "MinValue" is not a valid name attribute argument because it is not a valid attribute parameter type

**Comment by gguadalupe** [comment]
Hey @sebacamino, did this worked? Please remember to close the ticket once it's done!

**Comment by sebacamino** [comment]
@gguadalupe It's worked! Thanks!!
