### ISSUE TITLE
Transferring data from one table to another

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2571]
Hi

I have imported data into a table using serenity. Now I would like to transfer the imported data, after validation and processing,  to another table.  Any example and clues please.

**Comment by sayuga** [comment]
well, all you have to do is, essentially, call the service for that table and p-ass the information. It greatly depends on how you want to do the transfer of the data. 

If you want to just pass the data using a button click on the form, for example, you could add a button to the Dialog.ts toolbar that takes the form values and passes them to the correct table. using the xyzService.Create(). 

If you want to do it in bulk form ro do it more securely from .cs, you could emulate the BulkAction sample from the basic samples and then create a ServiceResponse that validates your data and then creates the data in the other table. 

Additionally, you could save some space on the Tables and have the data kept in a single table and just use ForeignKey references. When you assign the table data to the new table, you'd only have to update the Joint Key.

**Comment by ms4hafiz** [comment]
Thank you very much for the response. Validating this through seems a little time consuming for me. Is there a way to run a SQL Server stored procedure from Serenity?

**Comment by sayuga** [comment]
Yup, There is actually a sample under the BasicSamples

**Comment by ms4hafiz** [comment]
Thanks
