### ISSUE TITLE
Anyone interested in part time job?

### ISSUE THREAD

**Issue by bowlvan** [volkanceylan/Serenity#2572]
Please leave message in thread. :)

**Comment by ms4hafiz** [comment]
What is the requirement of the job?

**Comment by sayuga** [comment]
You should provide more details on what you want to accomplish. If needed myself and various others, including @volkanceylan do custom support.

**Comment by bowlvan** [comment]
The job is product development (UI & backend services) on Serene framework, will provide detail design document. Please send mail to bowlvan@hotmail.com for details. Thanks.

**Comment by dfaruque** [comment]
I am interested though...

**Comment by sayuga** [comment]
well @dfaruque send @bowlvan an email and you might get the contract. Now that I think about it, It wouldn't hurt to get a Rolodex of Serenity Developers looking to promote themselves for custom work.  Somethign for a different thread though.

**Comment by TheDanishDynamo** [comment]
I'm currently available. Developing using Serenity on 4.5. Integration with SAP and Salesforce, LDAP. Visual Studio 2015, Sql Server 2014. Senior Developer with USA Greencard, east coast time. Global experience. Speak English, Danish.

https://www.linkedin.com/in/thedanishdynamo

**Comment by dfaruque** [comment]
ok @sayuga , I have commented here because @bowlvan  has asked to leave message in this thread.

**Comment by volkanceylan** [comment]
Closing this, use slack for such
