### ISSUE TITLE
Select2 with optgroup

### ISSUE THREAD

**Issue by TomaszKustra** [volkanceylan/Serenity#2574]
My implementation for LookupEditor with OPTGROUP in Select2 to display item in group override "getItemGroup" and return group name for item.

export interface Select2ItemEx {
        children: Serenity.Select2Item[];
        text: string;
    }
export class LookupEditorGroups<TOptions extends Serenity.LookupEditorOptions, TItem> extends Serenity.LookupEditorBase<TOptions, TItem>
    {
        getSelect2Options(): Select2Options {
            var opt = super.getSelect2Options();

            var old_query = opt.query;

            opt.query = (query: Select2QueryOptions) => {
                var old_callback = query.callback;

                query.callback = (p1: Select2Result) => {
                    var results: Serenity.Select2Item[] = p1.results as Serenity.Select2Item[];
                    var res: Serenity.Select2Item[] = [];

                    results.forEach(v => {
                        var gn = this.getItemGroup(v.source);

                        if (gn) {
                            var gr: Select2ItemEx = null;
                            var grs = res.filter(g => g.text == gn && !g.id);
                            if (grs.length > 0) {
                                gr = ((grs[0] as any) as Select2ItemEx);
                            }

                            if (gr) {
                                gr.children.push(v);
                            }
                            else {
                                gr = {
                                    children: [],
                                    text: gn
                                };
                                gr.children.push(v);
                                res.push((gr as any) as Serenity.Select2Item);
                            }
                        }
                        else {
                            res.push(v);
                        }
                    });

                    p1.results = res;

                    old_callback(p1);
                };

                old_query(query);
            };

            return opt;
        }

        protected getItemGroup(item: TItem): string {
            return null;
        }
    }

![image](https://user-images.githubusercontent.com/4504375/29437260-d9e78088-83af-11e7-95e0-babeea12adc1.png)

**Comment by Estrusco** [comment]
Thank you!

**Comment by JohnRanger** [comment]
Very good! Thank you!

**Comment by volkanceylan** [comment]
Nice sample, thanks, will try to add it to Serene

**Comment by qprotex** [comment]
Was this added to Serene?
