### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by grobberD** [volkanceylan/Serenity#2575]
Hello Community,

I'm very impressed about the intention, possibilities and capabilities of Serenity. It seems to be that we need for development of database driven applications. 
But I cannot install the version. E.G. NuGet libraries are missing in Visual Studio a.s.o. 
What have I to do to get support? Do I have to buy a premium support (before evaluation) ?

Best regards, Torsten

**Comment by volkanceylan** [comment]
What do you mean by NuGet packages are missing? Which version are you using? Maybe you cloned or downloaded project directly here?

Follow steps in guide
https://www.gitbook.com/book/volkanceylan/serenity-guide/details

and installation instructions in 

https://github.com/volkanceylan/Serenity/blob/master/INSTALL.md

**Comment by grobberD** [comment]
Thank you for your last response.
I followed all steps you described in that documents. At this moment I'm not in front of my computer. 

The sergen based installation also does not work, because some error messages occurs while installation. I can try it again and can post this error messages into this thread. Hope that is the right place and  you can help me. I'm very interested in using Serenity. 
Also I miss description of needed database settings. That is not described in the installation guide. How now Serinity the credential for log in?

**Comment by volkanceylan** [comment]
Please read the guide, all you need is there.

**Comment by grobberD** [comment]
Hello,
I had to reinstall Nuget and Visual Studio. After that it worked. 
Now I made some exercises with Serenity and it works fine. It covers all what I need (I'm very impressed).  You made a good job. I would like to buy the premium service "personal". For that I don't want to use a credit card. Is it possible to get an invoice from Serenity so that I can transfer money? Can you help me in this?
Best regards, Torsten

**Comment by volkanceylan** [comment]
Hi @grobberD, please contact me from my mail
