### ISSUE TITLE
Open grid to click inline button

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2576]
I need to call a grid from a button on the Master Relation
![img01](https://user-images.githubusercontent.com/28063632/29471727-6dbcc792-8427-11e7-94da-c7c171af38ab.jpg)

**Comment by MaradiagaSistemas** [comment]
Hoy did you put # 1,2 etc on detail items?

Thanks.

**Comment by alexneocart** [comment]
Based on the examples I developed the code below but it only invokes the form dialog and never the grid. For my intention is to list all the objects of the bank class on a grid and select the corresponding account. What is incorrect?

 if (target.hasClass('boleto-row')) {
                    var dlg = new ParcelasContasDialog(container);
                    this.initDialog(dlg);               

                    var contasBancarias = Administration.Cadastros.ContasbancariasRow.getLookup().items
                        .filter(x => x.ContaBancariaId === 4)[0];               

                    dlg.loadEntityAndOpenDialog(<Administration.Cadastros.ContasbancariasRow>{  
                        ListaContas: [{
                            ContaBancariaId: contasBancarias.ContaBancariaId,
                            BancoCodigoBanco: contasBancarias.BancoCodigoBanco,
                            BancoNomeBanco: contasBancarias.BancoNomeBanco,
                            Agencia: contasBancarias.Agencia,
                            Conta: contasBancarias.Conta,
                            BancoId: contasBancarias.BancoId,
                        }]
                    });

**Comment by sayuga** [comment]
If you just want to edit the one item, you don't want to open the Grid, you want to open the dialog for the item. You should make sure that the inline-button is referencing the correct dialog. 

If you are looking to open the grid itself, then you pretty much want to navigate to the grid page so you would want the inline-button to go to the url for the grid but that would mean going away from the dialog and page you are at completely.

**Comment by alexneocart** [comment]
The intention is the same with the inline button and the url of the grid for the client to select the Bank account, as it could implement.

**Comment by JohnRanger** [comment]
So you want actually another Dialog on top of the current page which contains a grid with the bank accounts, correct?

John

**Comment by alexneocart** [comment]
![carregar](https://user-images.githubusercontent.com/28063632/29729992-ce5ec07c-89b4-11e7-8cf9-32110e0599d5.png)
This, after loading the grid I just want to take the account id and move on to a method that will generate the ticket

**Comment by alexneocart** [comment]
Resolvido utilizando
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/listing_movies_in_person_dialog.html

**Comment by controllernet** [comment]
Alex, estou com esta mesma necessidade, mas não consegui tirar no meu Dialog(template) o formulário , aparecem os dois o Grid e o formulário.

**Comment by alexdaywid** [comment]
@controllernet segue o exemplo do meu template dialog, tive que criar TemplateDialog , templateGrid 



/// <reference path="../../../Common/Helpers/GridEditorBase.ts" />
namespace AdmCadastro {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class ContasbancariasVendasDialog extends Serenity.TemplatedDialog<ContasVendasOptions> {
       
        protected form = new ContasbancariasForm(this.idPrefix);      
        private ContasbancariasVendasGrid: ContasbancariasVendasGrid;

        constructor(opt : ContasVendasOptions) {
            super(opt);

            this.dialogTitle = "Selecione a conta bancária para a emissão do boleto";
            this.ContasbancariasVendasGrid = new ContasbancariasVendasGrid(this.byId("ContasbancariasVendas"));
            this.tabs.on('tabsactivate', (e, i) => {
                this.arrange();
            });
         }
      
        protected getDialogOptions(): JQueryUI.DialogOptions {
            let opt = super.getDialogOptions();
            opt.buttons = [
                {
                   
                    text: Q.text('Dialogs.OkButton'),
                    click: e => {
                        var selectedIDs = this.ContasbancariasVendasGrid.rowSelection.getSelectedKeys();
                        var h = selectedIDs.map(x => Q.parseInteger(x));
                        
                        for (var i = 0; i < h.length; i++) {
                            var _id = h[i];
                        }
                        var contabancariaId = _id;
                        var parcelaId = this.options.parcelaId;
                        var vendaId = this.options.vendaId;
                        var opcao = this.options.opcao;
                        switch (opcao) {
                            case 0:
                                if (contabancariaId != null && parcelaId != null) {
                                    BoletosService.RegistrarBoleto({
                                        ParcelaId: parcelaId,
                                        ContaBancariaId: contabancariaId,
                                    }, response => {
                                        this.dialogClose();
                                        });
                                   
                                } else {
                                    Q.notifyError("Erro ao gerar o boleto")
                                }     
                                break;
                            case 1:
                                BoletosService.ListarEmail({
                                    VendaId: vendaId,
                                    ParcelaId: parcelaId,
                                    ContaBancariaId: contabancariaId,
                                }, response => {
                                    Q.notifySuccess("Boleto enviado com sucesso");
                                    this.dialogClose();
                                });
                                break;
                            case 2:
                                if (contabancariaId != null && parcelaId != null){
                                     NeoAdm.Common.ReportHelper.execute({
                                        reportKey: 'Vendas.Parcelas',
                                        parcela: parcelaId,
                                        contaBancaria: contabancariaId,
                                    });
                                     this.dialogClose();
                                } else {
                                    Q.notifyError("Error ao imprimir boleto")
                                }                                
                                break;
                            default:
                                break;
                        }
                                              
                    }
                }, {
                    text: Q.text('Dialogs.CancelButton'),
                    click: () => this.dialogClose()
                }];
                opt.title = Q.format(Q.text('Site.RolePermissionDia.DialogTitle'),
                this.options.title);
            return opt;
        }
    }

    export interface ContasVendasOptions {
        parcelaId?: number;
        vendaId?: number;
        opcao?: number;
        title?: string;
    }
}
