### ISSUE TITLE
Slick grid data selection is not available

### ISSUE THREAD

**Issue by TheDanishDynamo** [volkanceylan/Serenity#2577]
Hello,

Firstly thank you for such a great platform, pretty much 99% of all requirements can be done using the samples as guide.

My contribution would be a suggestion to use DataTables as grids instead of slick.

https://datatables.net/

This will enable selection (copy) of table contents, which is not available in slick.

**Comment by volkanceylan** [comment]
Hi, SlickGrid supports text selection actually, just override getSlickOptions in grid, and set enableTextSelectionOnCells to true.

DataTables is also nice, but SlickGrid is especially good on very big data sets, and doesn't rely on tables. We have some examples in StartSharp using DataTables though.

**Comment by TheDanishDynamo** [comment]
I'll try that, closing the issue.

I just saw the StartSharp, I'll recommend a subscription to my client, so far I feel like I owe you money already. http://serenity.is/demo/AdvancedSamples/BasicInit
