### ISSUE TITLE
display data from another table 

### ISSUE THREAD

**Issue by AbhishekBorkar04** [volkanceylan/Serenity#2578]
I have one table(CustomerTable).In that table i created customer id and name,and created  tables for eg. city ,country etc .now i want to create grid that shows Customer Id and name(which should be automatically populated from customer table).when i click on customer name all data(City,country) related to that customer should be populated in dialogue.

**Comment by sayuga** [comment]
Please review the manual. Dealing with Joint tables is stipulated there. Additionally, there is a sample for populating linked data in a dialog among the Serenity Basic Samples. 

https://www.gitbook.com/book/volkanceylan/serenity-guide/details

You are also welcome to use my Youtube MovieTutorial videos along the manual to see how it gets implemented. 

https://www.youtube.com/channel/UCHGyxXj-vI32YaRs0v3HvKw

**Comment by JohnRanger** [comment]
Why not creating a view on SQL Server side which includes all fields of These Tables and then generate grid and Dialog from this view with sergen?

With Kind regards,

John
