### ISSUE TITLE
Birden fazla şart kullanabilme ?

### ISSUE THREAD

**Issue by Osman06** [volkanceylan/Serenity#258]
Row da LeftJoin attribute kullanırken birden fazla şart kullanabilir miyiz ? Join'lediğim tabloyu filtrelemek istiyorum.
("dbo.[Order Details] jOrderDetails ON T0.OrderID = jOrderDetails.OrderID AND jOrderDetails.DetailID = 1 ") gibi...

**Comment by volkanceylan** [comment]
Property üstüne değil ama row üzerine LeftJoin yazarsanız orada kriter belirtmek mümkün
