### ISSUE TITLE
How to start new project with asp.net core 2.0 & Serenity framework?

### ISSUE THREAD

**Issue by 19317362** [volkanceylan/Serenity#2580]
Serenity is the best data based dotnet framework I have seen.
I want my project can run on linux server with postgresql or mysql.
I want start to try to use it with dotnet core 2.0. 
After some search on the web, I don't know how to start.
Any idea is welcome.

**Comment by ms4hafiz** [comment]
I am planning to develop the next project using asp.net core 2.0. I learning experiences and lessons learned using this framework.

**Comment by sayuga** [comment]
Read the Manual and check the blog. They have what you are looking for

http://serenity.is/blog/2017/01/23/dotnet-core-sergen-part1
http://serenity.is/blog/2017/01/30/dotnet-core-sergen-part2
https://www.gitbook.com/book/volkanceylan/serenity-guide/details

**Comment by 19317362** [comment]
@sayuga Thanks a lot. I've read those post a few months ago. I'll have a try.

**Comment by mahmuthaktan** [comment]
is that worked.
 is there any issue with linux

**Comment by volkanceylan** [comment]
Linux should also be working now, 3.0.4+
