### ISSUE TITLE
Use of third party components

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2581]
Hi community members

Is there a way to use ASP.NET third party component from Syncfusion, DevExpress or reporting tools like fast report or crystal report with serenity? any idea and example please.

Thanks for help

**Comment by sayuga** [comment]
You should be able to add anything ASP.Net to serenity but you'll have to map it accordingly for your needs. I don't think there are samples in place for any of the ones you mentioned.

**Comment by ms4hafiz** [comment]
Thank you. 
If there is any third party example would help me a lot. However, I will start working and will need your support.

**Comment by volkanceylan** [comment]
We have some component integration sample in guide.
