### ISSUE TITLE
Add user accounts in batch via Services?

### ISSUE THREAD

**Issue by drak0s** [volkanceylan/Serenity#2583]
Is there a way I can add users accounts in batch via Serenity Services?
Thanks upfront.

**Comment by sayuga** [comment]
The user accounts table is not that much different from the other tables. You should be able to, for example, import a spreadsheet with a batch of users. You'll just need to make sure that the data imported is meeting the validation criteria. 

Look at the User Repository and Endpoint and you should see the Serenity Service for Create and pretty much the same as the other, regular tables.

**Comment by drak0s** [comment]
Thanks Sayuga. I can understand most of the Services function except the SaveRequest Create function. Could you able to provide me a simple example how to use Service to add a user login and password.
Much appreciated.

**Comment by drak0s** [comment]
all good now. Thank
