### ISSUE TITLE
SQLUpdate - works only with default Dialect

### ISSUE THREAD

**Issue by TomaszKustra** [volkanceylan/Serenity#2584]
Can't set Dialect for SQLUpdate, the only solution is to change SqlSettings.DefaultDialect.

var cn = Connection as WrappedConnection;

SqlSettings.DefaultDialect = cn.Dialect;

var prUpd = new SqlUpdate(Entities.ProduktRow.Fields.TableName)

                .Where(Entities.ProduktRow.Fields.ProduktId == Row.ProduktId.Value);

**Comment by volkanceylan** [comment]
There is nothing dialect sensitive in SqlUpdate if i remember right

**Comment by TomaszKustra** [comment]
Try:
1. Create SqlUpdate
2. Create any subquery CreateSubQuery<SqlQuery> 
3. Add subquery to WHERE in SqlUpdate - subquery is sensitive for Dialect

**Comment by volkanceylan** [comment]
Subquery can set its own dialect with .Dialect though.

Anyway, ok ill consider adding a similar method to set dialect with SqlQuery
