### ISSUE TITLE
Joining with multiple criteria

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2585]
Hey @volkanceylan or anyone else who might be able to point me in the correct direction,

I've been searching through the guide, code and issues and haven't seen much on this.
I'm currently working with a few tables on one of my Rows and I'm having trouble trying to figure out how to LeftJoin one of my tables while matching multiple criteria. Pretty much the SQL equivalent of what I'm trying to do is this:

`from TABLE_A as A`
`left outer join TABLE_B as B on A.column0 = B.column0`
`left outer join TABLE_C as C on B.column0 = C.column0 and A.column1 = C.column1` 

The last line is where I'm running into issues. Is it even possible to do though Serenity?

**Comment by volkanceylan** [comment]
Mapping guide has this, put a Left Join on row.

**Comment by z-combs** [comment]
Worked perfectly, thank you.
For future reference, the code I used to achieve this:
`LeftJoin("e", "TABLE_B", "e.column0 = T0.column0"), `
`LeftJoin("s", "TABLE_C", "e.column0= s.column0 and s.column1= T0.column1")`

[Mapping Attributes](https://volkanceylan.gitbooks.io/serenity-guide/content/entities/mapping_attributes.html)

**Comment by naushadqamar** [comment]
Hi Guys I tried to do the same but it is not generating left join I checked in the sql profiler .

`  [ForeignKey(typeof(ArticleCharityRow), "ArticleId"), LeftJoin("ac")]
        [DisplayName("Article Id"), Identity]
        public Int32? ArticleId
        {
            get { return Fields.ArticleId[this]; }
            set { Fields.ArticleId[this] = value; }
        }`

**Comment by rajashekargoka** [comment]
i have some data in table with different customers but in grid i want to display each customer with no.of orders   as orders based on orderid and orderdate which i have to show in grid but those two are not in the table i
SELECT name, Count(order) as Items, SUM(amount) as Total  FROM table GROUP BY orderid,orderDate ;
