### ISSUE TITLE
Page Title and Add Button Have Entire Solution Name

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#2588]
This only happens occasionally but I don't know what's causing it or how to fix it.
The below should be called Share Classes.

![whole name](https://user-images.githubusercontent.com/8422795/29619702-b7c40bdc-87e9-11e7-9e29-19e9bc26b39b.PNG)

**Comment by JohnRanger** [comment]
Hi Leahmayschneider,

In such cases I open the following file: /scripts/site/Texts/site.texts.invariant.json and add the "serene.Web.Magnitude.ShareClasses" (or whatever is not displayed correctly) entry manually - including ist Translation.

After that, make a complete rebuild and the text should then be correctly translated into the desired text.

Hope this helps.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Your class namespace is probably not under root one. Use your project name, e.g. Serene, not Serene.Web

**Comment by leahmayschneider** [comment]
Latest update fixed.
