### ISSUE TITLE
Question: Best practice Data Access and FK relation

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [volkanceylan/Serenity#2589]
There's no hint at the documentation on how to get data out of FK linked entities.

Let's look at a MovieDB tutorial related sample:
I assume that "MovieRow" has the field `List<int> GenreList` for assignment of multiple genres.

```c#
var movieRows = new List<MovieRow>();
using (var connection = SqlConnections.NewFor<MovieRow>()) 
{
    movieRows = connection.List<MovieRow>();
}
```

` movieRows[x].GenreList` will, of course, throw an InvalidOperationException because it hasn't been initialized yet.

So now i would go on and query through every single `movieRows[x]` in order to fill `GenreList` of every item. This, of course, would result in a huge amount of queries against the DB. But Serenity does this in a more elegeant manner through the repository so the question is:
How can we use the built-in facilities to retrieve these resultsets?

**Comment by dfaruque** [comment]
user this
`var movieRows = new MovieRepository().List(connection, new ListRequest { ColumnSelection = ColumnSelection.Details} );`

**Comment by Neuroquila-n8fall** [comment]
Great!
