### ISSUE TITLE
Within xyzGrid.cs; How to set cursor focus into search field

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#259]
Hi JaiQ,

John Ranger here again :-) 

While I easily found a way to set the Cursor Focus within an Editor Dialog field,

```cs
       protected override void OnDialogOpen()
        {
            base.OnDialogOpen();

            form.InventoryLabel.Element.Focus();    // *** Set focus on the InventoryLabel field ***

        }
```

 I cannot figure out how to set it into the search field within a grid.

(I don't find a proper Event (like OnGridLoaded or so) and do not find a proper "form"  or "field" to dig down to an element in order to set the .Focus() Event on it. I am sure they are there...)

How would I do this?
.

Thank you for your help 

and 

with Kind regards,

John

**Comment by volkanceylan** [comment]
You can focus on grid constructor, or if this is a dialog, ondialogopen etc,

If from grid constructor
this.Element.Find(".s-QuickSearchInput").Focus()

From dialog

form.MyGridField.Element.Find(".s-QuickSearchInput").Focus();

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks again :-) Works perfectly out of the grid constructor.

With Kind regards,

John
