### ISSUE TITLE
Is there any way to know TableField/NonTable[Expression]Field from Typescript?

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#2590]
Hello Dears...

Is there any way to know TableField/NonTable[Expression]Field from Typescript?

**Comment by fernandocordero** [comment]
You mean from a dialog file? in a dialog you refer to form elements.  In the row  class you have a representation of the table if you look at:

   public class RowFields : RowFieldsBase
   {
   }

Not sure what your question really is.

**Comment by dfaruque** [comment]
I mean 
```
        protected getColumns(): Slick.Column[] {
            let cols = super.getColumns();
            cols.forEach(c => {

                if (c.IsTableField== true)
                ..............
........

```
here I need to check whether c is a table field or not...

**Comment by volkanceylan** [comment]
No, it is not possible, though you may write a custom lookup script that sends such information to client side.
