### ISSUE TITLE
adding new columns in the grid based on grouping 

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2591]
i have some data in table which contains no.of customers but in grid i want to display each customer with no.of orders as orders  he ordered based on orderid and orderdate which i have to show in grid but those two are not in the table 
SELECT name, Count(order) as Items, SUM(amount) as Total FROM table GROUP BY orderid , orderDate ;

**Comment by JohnRanger** [comment]
Hi rajashekargoka,

why don't you create a SQL view out of your select Statement and just create the Grid and the Dialog with sergen from it?

With Kind regards,

John

**Comment by rajashekargoka** [comment]
can you say how to create grid and dialog from view using sergen

**Comment by rajashekargoka** [comment]
after doing all the things above i.e generating row,column,...etc from view but in the grid the data is not loading showing 0 records but when we click on any column or refresh buttton it shows 49052 records but those are not displaying on grid . what to do to display those records on grid please help me

**Comment by JohnRanger** [comment]
Hi,

I am sorry but never had any issues with displaying records from a view within a serenity grid. So I cannot help you with this issue.

John

**Comment by volkanceylan** [comment]
Check your browser console.
