### ISSUE TITLE
Error on calling save button

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2592]
There is a problem on saving data. Following screenshot when I click on Save button it give an error. The error screen shot is following the form. 

![image](https://user-images.githubusercontent.com/20435849/29668961-282449d8-88f7-11e7-9241-7b7d65e2f692.png)

here is the error.
![image](https://user-images.githubusercontent.com/20435849/29668917-04a600e6-88f7-11e7-93cb-1795c2205f68.png)

**Comment by JohnRanger** [comment]
That can be anything. Looks like your Project has a file missing.

Do you have this with every save (it occurs with different Tables) or only with one?

If it is with all, please re-create your Project with the newest serenity template and copy over from your existing Project all your Program logic.

If it is only with one table, delete all corresponding files for this table under /modules and re-create this particular module with sergen.

With Kind regards,

John

**Comment by ms4hafiz** [comment]
Thanks
