### ISSUE TITLE
Stored Procedure Simple execution.

### ISSUE THREAD

**Issue by FGLedesma** [volkanceylan/Serenity#2593]
Sorry this is a rookie one...
How can I simply execute a stored procedure (without returning a table), calling it from a button in the grid toolbar?.
The SP will fill an already existent table that shows in the grid, so I then only need to refresh the grid.
For example...
protected getButtons() {
            // Save original btts.
            var buttons = super.getButtons();
            buttons.push({
                title: 'Gen Orders Shipment Files',
                cssClass: 'add-button',
                onClick: () => {

                    // HERE Call execution of SP ...

                }
            })

            return buttons;

Thank you so much in advance.

**Comment by JohnRanger** [comment]
You have to create a new endpoint in your server-side xyzEndpoint.cs and there you execute the SQL SP with Standard C# Code.

```cs
...
[HttpPost]
        public String ExecuteSP(IDbConnection connection)
        {
                // your C# Code for calling a SQL Stored procedure here...
                return "ok";
        }
```

Then - from the Client side within your onClick() code , you have to call the Service endpoint on the Server side like this:

```ts
onClick: () => {
    
                  var bla = xyzService.ExecuteSP(
                        {
                            
                        },
                        response => {
                            // *** Success ***
                            var message = JSON.parse(bla.responseText);
                            Q.notifySuccess(message, "All ok"));

                            this.refresh();
                        },
                        {
                            blockUI: true,
                            onError: response => {
                                // *** Error ***
                                Q.notifyError("There was an error"), Q.text("Error"));
                                this.refresh();

                            },
                            //onCleanup: () => this.serviceCallCleanup()
                        });

...
```

Hope this gives you the Basic idea.

With Kind regards,

John

**Comment by FGLedesma** [comment]
JohnRanger Thanks a lot for the quick replay!
I'll try it and will inform any issue.
