### ISSUE TITLE
Asp.net core Sergen NullReferenceException 

### ISSUE THREAD

**Issue by sergproger** [volkanceylan/Serenity#2594]
Hi,
I´m trying to generate code for a simple table and sergen crashes.
Any idea? Thanks in advance
I have codeGenerator 2.10.3
![sergenexcep](https://user-images.githubusercontent.com/7138164/29684404-80001ae2-891a-11e7-8432-432a2f3ed05c.png)

**Comment by volkanceylan** [comment]
Please use "dotnet sergen" for generating code, see INSTALL.md file at root
