### ISSUE TITLE
How to add two kinds of mask in same field

### ISSUE THREAD

**Issue by PedroHFranco** [volkanceylan/Serenity#2595]
Hello,

I have an field, CpfCnpj and acording of his size i have to put the respective mask.
Ex.: "999.999.999-99" or "99.999.999/9999-99"

I have tryied this in my Dialog.ts ,but not working fine:

```
            this.form.CpfCnpj.element.change(e => {
                if (this.form.CpfCnpj.value.length <= 11)
                    (this.form.CpfCnpj.element as any).mask("999.999.999-99");
                else if (this.form.CpfCnpj.value.length >= 14)
                    (this.form.CpfCnpj.element as any).mask("99.999.999/0009-99");
            })
```

How is the best way to do this ?

**Comment by volkanceylan** [comment]
Sorry, I'm not sure that's possible, you should check docs of jquery input mask plugin.

**Comment by rolembergfilho** [comment]
Hey @PedroHFranco ,

você conseguiu criar esse script?

**Comment by PedroHFranco** [comment]
Olá @rolembergfilho 
Não, por enquanto deixei sem mascara.

**Comment by VGsss** [comment]
[Uma forma de fazer a máscara](https://github.com/serenitybrasil/SerenityBrasil/wiki/Cheat-Sheet---XYZDialog.ts#m%C3%A1scara-de-cpfcnpj-no-mesmo-campo-cr%C3%A9ditos-httpselciocombrajaxmascara)

Se quiser que ela apague ao perder o foco do campo caso o valor inserido pelo usuário seja inválido, é só utilizar o onblur para tal, utilizando como parâmetro o lenght do valor atual do campo.
