### ISSUE TITLE
New Button Dialog

### ISSUE THREAD

**Issue by dougdsank** [volkanceylan/Serenity#2596]
I was using the code below and it used to work fine. All of a sudden it stopped working. What it does now is quickly open the new dialog and closes right away. This code is in the constructor of the grid.ts
Thanks for any help.

 $('#btnnew').click(() => {
             
               
                var dlg = new AppAlertDialog();               
                this.initDialog(dlg);
                dlg.loadNewAndOpenDialog();

            });

**Comment by Neuroquila-n8fall** [comment]
Immediately closing dialogs are in most cases related to double-loading jquery. Have you recently added a library or plugin which uses jquery and/or maybe loads it a second time?

**Comment by volkanceylan** [comment]
Try adding Q.Router.enabled = false in your ScriptInitialization.ts
