### ISSUE TITLE
Multiple Grids with filtered results on the same page

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [volkanceylan/Serenity#2597]
I wonder if there is a way to display a bunch of Grids on a custom page where the resultset is pre-filtered?
Let's say we're looking at the MovieDB and I'd like to have a Listing for every Genre that contains the associated movies like so:
``` 
[Quicksearch] [Add] [Filters]
---Genre1------------
Movie 1
Movie 2
Movie 3

[Quicksearch] [Add] [Filters]
---Genre2-----------
Movie 2
Movie 4
```

**Comment by volkanceylan** [comment]
You could put multiple GridDivs in CSHTML, create multiple grids, pass filters as option to grids.

**Comment by cnphiliplau** [comment]
> You could put multiple GridDivs in CSHTML, create multiple grids, pass filters as option to grids.

Hi,
Thanks for the serene.

I found that it only support one `GridDiv', this GridDiv is set by default.
I have dig the code, it is hard coded, model.HtmlMarkup ??= "<div id=\"GridDiv\"></div>"

Is it possible to put multiple GridDivs in the Index cshtml?

I have tried the code, but failed.

export class MultiGridPage {
    constructor() {
        new CommodityGrid({ element: document.getElementById("CommodityGridDiv") }).render();
        new CustomerGrid({ element: document.getElementById("CustomerGridDiv") }).render();
    }
}

new MultiGridPage();
