### ISSUE TITLE
How to connect Serenity Web Services with a mobile project (Xamarin).

### ISSUE THREAD

**Issue by sebacamino** [volkanceylan/Serenity#2599]
I have to dial customer support through a tablet, so I'll need to connect from the tablet to the Serenity project web service.
How to consume a Serenity Web Service in xamarin?
Thanks!

**Comment by fernandocordero** [comment]
As far as I know Serenity supports serviceRequest accessible from the Q namespace. But I think you want to use Serenity as an API? I don't think it works that way.

**Comment by sebacamino** [comment]
I want to use a POST, or "Create" from xyzendpoint. How do you recommend that I do?
Watch this #806
Thanks

**Comment by fernandocordero** [comment]
See this portion of code from ticket #655. Specially 

 **Q.serviceRequest(TicketService.baseUrl + "/Accept"**. Of course you will have to define you own base url  and suppress "/Accept" to match your qualified service path. I think this should give you a good starting point.
 
 var box = bootbox.prompt({
                    title: "Please enter a reason?",
                    value: "",
                    callback: function (result) {
                        if (result === null) {
                            Q.notifyWarning("test");
                        } else {
                            Q.serviceRequest(TicketService.baseUrl + "/Accept", { Entity: this.getSaveEntity() }, () => {
                                Q.notifySuccess('Case ' + this.form.SourceSystemId().get_value() + ' has been successfully assigned to ' + this.form.OwnerId() + '.', '', null);
                                Serenity.SubDialogHelper.triggerDataChange(this);
                                this.dialogClose();
                            });
                        }
                    }
                });
                box.zIndex(1200);
