### ISSUE TITLE
Hide (or desable) Fields 

### ISSUE THREAD

**Issue by LadeuKone** [volkanceylan/Serenity#260]
Hi,
Maybe this issue has already been posted, but i haven't seen, so...

How to hide or show  a field (or desable or enable a field), depending on the value of another field in a dialog?

Thanks

**Comment by linpiero** [comment]
in AfterLoadEntity
this.ById("xyzField").Closest(".field").Hide();

**Comment by LadeuKone** [comment]
Thanks,
But this applies after Loading (or during loading). But what I'm talking about is during user Input in the form. e.g, when the user checks a checkbox, i want to hide some fields and show other fields and vice-versa.

**Comment by linpiero** [comment]
in constructor of dialog:
 form.xzyField.Change(e =>
                { //Your code});

if lookup:
form.xzyField.ChangeSelect2(e =>
                { //Your code});

**Comment by LadeuKone** [comment]
Ok, that's Great! Thank you

**Comment by volkanceylan** [comment]
Thanks @linpiero, it's good to see users helping each other

**Comment by linpiero** [comment]
You are welcome and also Thank's to you, your  work is good and full of knowledge.
