### ISSUE TITLE
How to open another form

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2600]
I have a problem in opening a from. I have designed an import form that is different from data entry form. I want to open the import form from data entry form using a new button. My data entry form looks like the following 

![image](https://user-images.githubusercontent.com/20435849/29952008-c0e7122e-8edb-11e7-919c-bd71128e366b.png)

any please in how to open the import form.

Thanks

**Comment by Estrusco** [comment]
If yuo want to open a dialog you can use one of these methods:

```ts
new YuorNamespace.XYZDialog().dialogOpen();
```

or 

```ts
new YuorNamespace.XYZDialog().loadByIdAndOpenDialog()
```

or

```ts
new YuorNamespace.XYZDialog().loadNewAndOpenDialog()
```

**Comment by volkanceylan** [comment]
@ms4hafiz you could use StartSharp repository to open issues as a premium member, that's prioritized and i can't regularly check here.

**Comment by ms4hafiz** [comment]
Thanks Volkan and Estrusco;

I would like to open another page(form) /link using the button shown above. It is not a dialog it is a grid from another form.
