### ISSUE TITLE
Programmatically generate data for custom column in row

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2601]
hey @volkanceylan and all,

I'm trying to add a column to one of my row classes that is a celsius conversion of an existing column. 
When I look at the grid my "Coolant Temp (C)" is blank on all rows.

`[DisplayName("Coolant Temp (F)"), Size(18), Scale(2)]`
`public Decimal? WaterTemp`
`{`
`get { return Fields.WaterTemp[this]; }`
`set { Fields.WaterTemp[this] = value; }`
`}`

`[DisplayName("Coolant Temp (C)"), Size(18), Scale(2), NotMapped]`
`public Decimal? WaterTempC`
`{`
`get { return Fields.WaterTempC[this]; }`
`set { Fields.WaterTempC[this] = TemperatureConversion.F_to_C(WaterTemp.Value); }`
`}`

 Any ideas as to how I can achieve this, everything I've thought of trying hasn't worked?

**Comment by TomaszKustra** [comment]
Use Expression attrubute on WatherTempC column


[DisplayName("Coolant Temp (C)"), Size(18), Scale(2), NotMapped]
[Expression("((T0.[WaterTempC]-32)/1.8)")]
public Decimal? WaterTempC
{
get { return Fields.WaterTempC[this]; }
set { Fields.WaterTempC[this] =value ; }
}

**Comment by z-combs** [comment]
Perfect, a little additional editing and removing the NotMapped attribute got the data generating.
Thanks!
