### ISSUE TITLE
Someone adapted Serenity.Services for Xamarin?

### ISSUE THREAD

**Issue by sebacamino** [volkanceylan/Serenity#2604]
I need this, for connect to the serenity project and use the endpoints.
As the following example: # 806

**Comment by samdubey** [comment]
We have consumed Serenity.Services using [RestSharp](http://restsharp.org/) in WPF Application storing cookies in CookiesContainer 
in Android in similar fashion we are consuming Serenity Apis

**Comment by sebacamino** [comment]
I'll keep that in mind. You can send me a basic example of how to authorize and consume a service.
Thanks for all!

**Comment by samdubey** [comment]
`public static class SereneRequester
    {
        public static CookieContainer rsCookie = new CookieContainer();

        // Check user is LoggedIn or not
        [Protect]
        public static IRestResponse<bool> IsLoggedIn(string baseUrl, string cookieName)
        {
            #region IsLoggedIn Request
            IRestResponse<bool> response = new RestResponse<bool>();
            if (InternetConnection.IsConnectedToInternet() == true)
            {
                try
                {
                    var restClient = new RestClient(baseUrl);
                    var request = new RestRequest(Method.POST);
                    request.Resource = "/Account/IsLoggedIn";
                    CookieContainer rscookie = RestoreCookie(cookieName);
                    if (rscookie == null)
                    {
                        rscookie = new CookieContainer();
                    }
                    restClient.CookieContainer = rscookie;
                    response = restClient.Execute<bool>(request);
                    if (response.StatusCode == HttpStatusCode.OK && response.ResponseStatus == ResponseStatus.Completed)
                    {
                        SereneRequester.SaveCookie(restClient.CookieContainer, cookieName);
                    }
                }
                catch (Exception ex)
                {
                    response.ErrorMessage = ex.Message;
                    response.ErrorException = ex.InnerException;
                    //MessageBox.Show(ex.Message);
                }
                return response;
            }
            else
            {
                response.ErrorMessage = "Internet connection not available. Please check connection.";
                return response;
            }
            #endregion
        }`

this code is to check User Logged In or Not

`public static IRestResponse<ServiceResponse> Login(string baseUrl, string username, string password, string cookieName)
        {
            #region Login Service Request
            IRestResponse<ServiceResponse> response = new RestResponse<ServiceResponse>();
            if (InternetConnection.IsConnectedToInternet() == true)
            {
                try
                {
                    var restClient = new RestClient(baseUrl);
                    var request = new RestRequest(Method.POST);
                    request.Resource = "/Account/Login";
                    //Method 1 : Passing parameters in c# object
                    request.AddParameter("Username", username);
                    request.AddParameter("Password", password);

                    #region Other Method to pass JSON Parameters (Working)
                    //Method 2 : Passing parameters in Json body format
                    //request.AddHeader("Content-type", "application/json");
                    //request.AddJsonBody(
                    //    new
                    //    {
                    //        Username = txtUsername.Text,
                    //        Password = txtPassword.Password
                    //    });

                    //Method 3 : Passing parameters in Json object string format
                    //dynamic jsonParameters = new JObject();
                    //jsonParameters.Username = txtUsername.Text;
                    //jsonParameters.Password = txtPassword.Password;
                    //var parameters = jsonParameters.ToString();
                    //request.AddParameter("application/json", parameters, ParameterType.RequestBody);
                    #endregion

                    restClient.CookieContainer = new CookieContainer();
                    response = restClient.Execute<ServiceResponse>(request);
                    if (response.StatusCode == HttpStatusCode.OK && response.ResponseStatus == ResponseStatus.Completed)
                    {
                        SereneRequester.SaveCookie(restClient.CookieContainer, cookieName);
                    }
                }
                catch (Exception ex)
                {
                    response.ErrorMessage = ex.Message;
                    response.ErrorException = ex.InnerException;
                    //MessageBox.Show(ex.Message);
                }
                return response;
            }
            else
            {
                response.ErrorMessage = "Internet connection not available. Please check connection.";
                return response;
            }
            #endregion
        }`

**Comment by sebacamino** [comment]
Very Thanks for your time @samdubey! Can you explain me about parameter "string cookiename"?

**Comment by volkanceylan** [comment]
Thanks a lot @samdubey

**Comment by samdubey** [comment]
@sebacamino cookiename is any name given to cookie just like in web application cookie name could be 
APP.AUTH or FORMS.AUTH

**Comment by sebacamino** [comment]
@samdubey I'm sorry for my insistence, but I'm doing a final job of my study and I need it.
Could you send me an example? POST data of person (Id(Identity), Name, SecondName, Sex), i need auth and i dont know how do it...
Thank you so much for everything

**Comment by samdubey** [comment]
Replied to you over email

**Comment by samdubey** [comment]
I will post sample showing CRUD + Fileupload from WPF / Desktop Application

**Comment by sebacamino** [comment]
It's ok! I will waiting the link!
Thanks a lot!

**Comment by sebacamino** [comment]
Hey @samdubey! You have already the sample?
