### ISSUE TITLE
displaying data in textbox based on  row selection from grid

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2605]
i have a customer related data in my table i.e customer name,order id,address ,amount etc
but i have to display customer name,order id,address in grid and below the grid i have a readonly textbox for displaying the amount  for the specific cusomer based on the row selection in the grid.

**Comment by volkanceylan** [comment]
Search prior issues to get reference to selected row. Then its about your jQuery knowledge to pass values from row to inputs.
