### ISSUE TITLE
Grid in Dialog without Add button

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#2607]
Hi,
 I am new in serenity, i am facing problem as below.

Want to display grid in dialog without Add button but can should be editable.
in row class i added 
        [MasterDetailRelation(foreignKey: "ProductCartId", IncludeColumns = "FullNumber,Description")]
        [DisplayName("Cart List"), SetFieldFlags(FieldFlags.ClientSide)]
        public List<ProductCartDetailsRow> CartDetailsList
        {
            get { return Fields.CartDetailsList[this]; }
            set { Fields.CartDetailsList[this] = value; }
        }

Want to display grid as per below image.
 
![dialoggridedit](https://user-images.githubusercontent.com/31484362/29885917-119d7e26-8dd6-11e7-9857-c0e96a3e5a5d.png)

**Comment by alexneocart** [comment]
Button inline no grid.
http://serenity.is/demo/BasicSamples/InlineActionButtons

**Comment by Estrusco** [comment]
I you don't want the add button, override  getButtons() in your editor for CartDetails and return null

```ts
        protected getButtons() {
            return null;
        }
```

**Comment by rakeshpatil20** [comment]
Thanks it works !!!
