### ISSUE TITLE
Read only Grid in Read only Dialog 

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#2609]
Hello,

I create dialog having grid. I make all field read only but facing below issues 
1) Not able to make grid as read only 
2) Not able to remove add button 

Want to remove add button? any suggestion !!!

![dialoggridedit3](https://user-images.githubusercontent.com/31484362/29911700-7834c4de-8e4c-11e7-850f-cff13dc9fef6.png)

**Comment by rakeshpatil20** [comment]
protected getButtons() {
            return null;
   }
Above function remove Add button. :)

Now how to make grid as read only?

**Comment by Estrusco** [comment]
Grids are read-only. If you want remove the edit links, remove the editlink attribute in columns.cs

**Comment by rakeshpatil20** [comment]
Thanks ,
I want to remove editlink attribute conditionally?

**Comment by rakeshpatil20** [comment]
hey,
I override EditItem method and call super.editItem method conditionally and it works for me ;) 

Thanks

**Comment by stixoffire** [comment]
@rakeshpatil20  sometimes it is really nice to have your solution posted - that way people can see how you achieved the functionality and you help someone else..
