### ISSUE TITLE
Override Attribute to Updatable(false) on ExecuteDelete

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#261]
I've overridden the delete ExecuteDelete and listed all the fields that I wish to lock. But I can't seem to figure out how to properly update the field attributes on the repository side so as to make them "Updatable(false)". What is the serenity command I can use to override the current attribute? 

namespace FMCDashboardV2.FMCorp.Repositories
{
    using Serenity;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using Serenity.Services;
    using Serenity.Web.Providers;
    using Serenity.ComponentModel;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Web.Security;
    using MyRow = Entities.MatrixRow;
    using UDefinition= Administration.UserDefinition;

                  //.......//
     private class MyDeleteHandler : DeleteRequestHandler<MyRow>
        {
            protected override void ExecuteDelete()
            {
                using LockUpdate = GetAttribute<UpdatableAttribute>(false);

                
                Row.CustomerName.LockUpdate;
                Row.AddressOptional.LockUpdate;
                //.....//
                Row.RemovedOn = DateTime.Now;
                Row.Status = MatrixStatus.Removed;
            }
       }

**Comment by volkanceylan** [comment]
I'm having difficulty trying to understand what is your aim. What are you doing here with UpdatableAttribute. It only controls save handler. If you want to update row on delete, you need to do it like Connection.UpdateById(new MyRow { Id = Row.Id, RemovedOn = ..., Status = ... }); etc.

**Comment by sayuga** [comment]
What I'm attempting to do is lock all fields from a specific row from any further updates instead of deleting the actual data when someone chooses to click on the delete button. 

Our current internal protocols says we need to maintain all records indefinitely thus I can't have people delete any data BUT I also can't allow any changes to be made to any field once a row has been decommissioned. I'm essentially attempting to make the one row that is deleted, ReadOnly, meanwhile any other rows would still be editable. The current identifier triggers I've added are a RemovedOn DateTime Field and a Status enumerated field that would change to "Removed". 

I need to update the triggers and make the row read only but I can't seem to figure out how to properly override this event. 

Now that I think about it, I may also be going the wrong way about it since, as I write this, I realized that if I attempt to override the fields attribute, it'd affect all rows....Perhaps overwrite the function of the "Delete" button on the dialog so that when it is clicked it instead runs another SetInternalFields function which updates the triggers, followed by an additional override in the RetrieveHandler that would show rows with that have status "Removed" as read only.....

...I'm going to chase this idea a bit unless you have a better suggestion. Otherwise, sorry for the troubles.

**Comment by volkanceylan** [comment]
I recommend you implement IIsActiveDeletedRow interface, so that deleted rows won't be editable.

**Comment by sayuga** [comment]
I took your recommendation and also took the time to mess around in a copy of my project and test the logging row and a few other features and I must say it worked like a charm. Sorry for having been so much trouble with my explanations. 

Long story short, I successfully have the Created, Updated and Deleted Dates updated by emmulating the LoggingRow  from the Users Table and updating the DateTimeFields to relate to my fields and the the LastUpdated and Status Fields I use additionally are being updated on the xyzRepository.cs using the SetInternalFields Override for IsCreated and IsEdited and then updating the Deletion fields using the OnbeforeDelete override and a Connection.UpdateById. 

Thank you for all the help and patience.
