### ISSUE TITLE
Calculating amount when the check box is checked.

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#2610]
The grid contains columns like amount,name,checkboxes etc.when the user clicks the one or more checkboxes then the particular row amount should be calculated and display on the grid footer.

**Comment by gguadalupe** [comment]
Hey!,

I did something like this, but not on a Grid. I did this on a form.
Every time you change a combo or you change the Detail List, the "Premium" (or total amount) is recalculated.

In the xxxDialog.ts I named every control that will change the amount.

```
        constructor() {
            super();

            this.form.StateId.changeSelect2(() => {
                this.calcPremium();
            });
            (this.form.CrossQuoteDetailList.view as any).onDataChanged.subscribe(() => {
                this.calcPremium();
            });
        }

        calcPremium() {
            try {
                this.form.Premium.value = a bunch of calculations...;
            }
            catch (e) {
                return null;
            }
        }

```
I don't know if something like this works with the grid, but should be a good starting point for you to investigate how to get the info.

Gus.

**Comment by flextrio-gandhi** [comment]
As the application starts one  pop-up(parent pop-up) will appear on the webpage and it consists of  buttons,textboxes etc.
and when the user clicked on the button another pop-up(child pop-up) will appear on the screen and this pop-up consists of grid and some textboxes,buttons etc. 
My requirement:-is when the user clicked on grid-row that particular row data should be shown in the textboxes of first(previous or parent pop-up) how we can bind that??
