### ISSUE TITLE
 how to add  button for each row at the end of the row 

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2611]
how to add  button for each row at the end of the row ?

**Comment by chintansoni54** [comment]
Hi @rajashekargoka,

You can add button for each row at end by following ways

` 
     export class InlineActionGrid extends Northwind.CustomerGrid {

       constructor(container: JQuery) {
            super(container);
        }

        protected getColumns() {
            var columns = super.getColumns();

            columns.push({
                field: 'Delete Row',
                name: '',
                format: ctx => '<a class="inline-action delete-row" title="delete">' + 
                    '<i class="fa fa-trash-o text-red"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24                   
            });
          
            return columns;
        }
`

**Comment by volkanceylan** [comment]
Thanks @chintansoni54
