### ISSUE TITLE
Display Forms as full page instead of popup window

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2612]
hey, first thanks for the awesome job you are doing with your team.

Question ! 
i use NopCommerce application (using AdminLTE theme too). 
When switching to a FORM display (ie : add/update stuff), display of form is FULL client display area; an additional link (breadcrumb) is then added on top near the title of the page
I would like to know if it's something possible to add this possibility in a future version 
(i mean never display popup window but switch to full page display).

See sample screenshot : https://ibb.co/hRaZZ5

Thanks again !

**Comment by mahmuthaktan** [comment]
Did You check this example:
http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

**Comment by kilroyFR** [comment]
My bad ! perfect  thanks !
