### ISSUE TITLE
GridRowSelectionMixin Select Unique Option

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2613]
GridRowSelectionMixin select unique option grid? Sugestion?
![img01](https://user-images.githubusercontent.com/28063632/29941119-d175b416-8e67-11e7-9648-0261dd2eb163.jpg)

**Comment by JohnRanger** [comment]
Hi,
could you please describe a bit more clearly what you want to achieve?

If you want that only one entry can be selected, don't do this as a grid but make it a Dropdown with customized Text (text which contains Description, Bank, Agency and Account).

If you have many records with the same Content, then just create a MS SQL view with UNIQUE and then generate Grid and Dialog from it with sergen.

If I didn't understand you reequest correctly, explain here in more Details what you really want to achieve.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Reopen with a better description please.
