### ISSUE TITLE
I want to modify multiple entries at once

### ISSUE THREAD

**Issue by Lukemcc10** [volkanceylan/Serenity#2614]
I've been stuck trying to work with multiple entries at once and I'm just not sure how to move forward. I have looked at examples in the basic samples and gotten as far as I can get. Any help or guidance would be amazing. 

I want to be able to modify / delete multiple records at once. The user marks the checkbox of the entries he wants to modify or delete. I have gotten the checkboxes on each line and I have the array ( like in the excel import example) but now I need to figure out how to handle it.

I just want the modify screen to show blanks and when they click save I want to update the database with the values if they're not blank.

![image](https://user-images.githubusercontent.com/17455078/29947011-a911c876-8e75-11e7-9741-d823302d68f4.png)

![image](https://user-images.githubusercontent.com/17455078/29947057-d002cac0-8e75-11e7-99b3-a0d90cf7698d.png)

**Comment by JohnRanger** [comment]
Hi,

please have a look at the "Cancellable Bulk Action With Progress" in the Basic examples.

At least your desired "delete" Action can easily be implemented like the example.

Basically the workflow is like this: (very high Level description)

(1) you select some rows/records by checking the Checkbox in front of each row
(2) you click the Action button (Update or Delete) --> The record IDs are transported from Client side to Service endpoint
(3) in the Service endpoint (create a new one for each action) you have to do the actual DB update (e.g. delete)

For the update Szenario, you will have to develop your own Dialog which has the data fields in it which values you want the user to type in and then send These field data including the record ids over to the Service endpoint for the update Action you have to do the actual DB updating (e.g. process each selected record and update the desired fields).

I will add something similar I have developed in a few minutes.

With Kind regards,

John

**Comment by Lukemcc10** [comment]
Thank you so much for the code It took a few hours to implement and get working but Its working great. 

I appreciate your time so much,

Luke
