### ISSUE TITLE
When the decimal column  number is minus,can't open the Dialog.

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#2616]
When the decimal column  number is minus,can't open the Dialog.
What can I do.
![20170901070226944](https://user-images.githubusercontent.com/20983211/29948864-cbffab64-8ee3-11e7-9ce4-4dde2adc773d.jpg)

**Comment by samdubey** [comment]
go to decimal editor set min value to some large -ve value to make it work
