### ISSUE TITLE
Delete button in detail grid in dialog

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#2617]
Hello,

I added grid in dialog  and added on more column with delete button in grid.
Now how to remove row on delete button click and on update button it should update in database.
![dialoggridedit4](https://user-images.githubusercontent.com/31484362/29965914-3daef0c8-8f2d-11e7-9fc0-db9f5bdfaa34.png)

**Comment by rakeshpatil20** [comment]
Hello,
Anyone know how to remove row from grid and on update button click save it in database.

**Comment by chintansoni54** [comment]
Hi @rakeshpatil20 ,

I think you want to do some thing like this http://serenity.is/demo/BasicSamples/InlineActionButtons

so you can refer basic sample code https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons/InlineActionGrid.ts#L46

**Comment by rakeshpatil20** [comment]
@chintansoni54 : Thanks for your response,

If i call service then it delete record directly from DB & dialog grid also not get refreshed, 
As i want when user click update button then only it should delete record from database & On delete click it also remove the row.

Thanks

**Comment by alexneocart** [comment]
Insert em XptoGrid.ts  
 //Remove buttons toolbar
        protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 3);
            return buttons;
        }

**Comment by volkanceylan** [comment]
this.view.deleteItemById(id)
