### ISSUE TITLE
Refresh LookupEditor after .change()?

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2618]
I've been working on having a LookupEditor filter it's items when a selection is made in another LookupEditor. I've got that working perfectly but I'm having trouble trying to figure out how to reflect the change. After the change takes place, to get the LookupEditor to reflect the changes you have to: 

1. Open the editor (still shows all of the original options)
2. Select an option, the editor closes itself
3. Open the editor again (now shows the new options)

So the question is, how can I get the LookupEditor to refresh the options after the change happens without having to click a bunch of times?

**Comment by Estrusco** [comment]
You can use Try Q.reloadLookup(someRow.lookupKey); or set timeout to negative in LookupScript. 

See here https://github.com/volkanceylan/Serenity/issues/2318 and https://github.com/volkanceylan/Serenity/issues/2075

**Comment by z-combs** [comment]
Alrighty, I've added the -1 timeout to the lookup scripts, I've added the Q.reloadLookup in multiple places throughout my dialog (on both click events and during the .change) and I'm still having the same problem.

I think that the Q.reloadLookup is definitely the solution here but I'm having issues as to where I'm inserting it into my code. Logically, the reload should take place as the last thing in my click event but it doesn't seem to be triggering or the lookup editor isn't refreshing.

**Comment by Estrusco** [comment]
Have you tried to add it in beforeLoadEntity or in grid.ts before the dialog open?

**Comment by z-combs** [comment]
Neither of them work as expected. What I'm looking to do happens after the constructor, beforeLoadEntity and afterLoadEntity all finish. What I'm trying to do is remove the options from LookupEditor B when a selection is made in LookupEditor A.

So:
```typescript
this.form.LookupEditorA.element.on("click", e => {
    this.form.LookupEditorB.change(a => {
         //Filter code
    });
});
```

**Comment by Estrusco** [comment]
Mmm I don't understand what you want to achieve.

But in this way you remove only the visual element in lookupEditorB.
If you want to remove record from db in table that populate the lookupEditorB, you have to call a service Delete 

Some like

```ts
this.form.LookupEditorA.element.on("click", e => {
   YourNamespace.RowBService.Delete(
        { 
              EntityId: idToRemove 
        },
        {
            Q.reloadLookup(RowB.lookupKey);
        }
   );
   
});
```

**Comment by z-combs** [comment]
> But in this way you remove only the visual element in lookupEditorB.
> @Estrusco 

That's exactly what I want to happen. What's happening though is that using the Q.reloadLookup isn't visually reloading until after a user tries to select an element that no longer exists in the LookupEditor.

**Comment by z-combs** [comment]
I have this working as I expect it to. Due to time constraints, I'm not removing some of the extra bits I have in the code and I'm not renaming things. Also I could probably condense a good bit of the code but it's working and, again, I have time constraints. For anyone interested in how I got this working:

```typescript
private Default_UMM: Serenity.Select2Item[] = new Array();
private Filtered_UMM : Serenity.Select2Item[] = new Array();
private uid: number = -1;
```

In my constructor:
```typescript
this.form.UnitId.element.on("click", e => {
    this.form.Ummid.value = "";
    this.form.UMM_Description.value = "";

    var units = Q.getLookup<Units.UnitsRow>(UnitsRow.lookupKey);
    var thisUid = Q.first(units.items, a => a.SerialNumber == this.form.UnitId.get_text()).UnitId;

    if (thisUid != this.uid) {
        this.uid = thisUid;
        this.form.Ummid.items = this.Default_UMM;
        this.Filtered_UMM = new Array();

        var modelId = Q.first(units.items, b => b.UnitId == parseInt(this.form.UnitId.value)).ModelId;
        var lookup = Q.getLookup<Maintenance.UnitModelMaintenanceRow>(UnitModelMaintenanceRow.lookupKey);
        var ummid = -1;
        try {
            ummid = Q.first(lookup.items, a => a.ModelId == modelId).Ummid;
        } catch (err) {
            if (err.message != "first:No element satisfies the condition.!") console.log(err.message);
        }
        if (ummid > -1) {
            while (ummid > -1) {
                var index = this.GetIndex(this.form.Ummid.items, ummid);
                if (index > -1) this.Filtered_UMM.push(this.form.Ummid.items[index]);
                try {
                    ummid = Q.first(lookup.items, a => a.ModelId == modelId && a.Ummid > ummid).Ummid;
                } catch (err) {
                    ummid = -1;
                    break;
                }
            }
            this.form.Ummid.items = this.Filtered_UMM;
            this.form.Ummid.readOnly = false;
        } else this.form.Ummid.readOnly = true;
    }
});
```
