### ISSUE TITLE
ForeignKey Composite Key

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2619]
hey again,

in the definition of an entity (Row definition - ex : ProjectRow),

ex :
We have a table 'employee' defined with 'Employee ID/Company ID' as COMPOSITE PK.
I have added an additional ID field + sequence to number them uniquely.

Problem comes with tables referencing this table. 
They are using (EmployeeId/CompanyID) as composite FK.

Association table with fields
(EmployeeID / CompanyID)
+ Date entry, Date Exit

I wish i could redesign the db but that's not possible right now and on other side i would really like to show my organisation we have a fast/efficient solution with Serenity to go further on our many enterprise projects.

Is it possible to specify a COMPOSITE FK Key (the syntax does not allow only expecting a single field as FK).

ex: (syntax not valid but dont know if possible to make it valid)

[DisplayName("Employee"), ForeignKey("Employee", "EmployeeId,CompanyId"), LeftJoin("jemp"), TextualField("EmployeeFirstName")]
        [LookupEditor(typeof(EmployeeRow), InplaceAdd = true)]
        public Int32? EmployeeId
        {
            get { return Fields.EmployeeId[this]; }
            set { Fields.EmployeeId[this] = value; }
        }

Thanks for any help. Really hoping for a solution, this framework is so amazing i really want to make it the enterprise GUI framework.

**Comment by brunobola** [comment]
You can put a new column with a identity specification and then use it as key just in coding... This way I think that the database stays the same and the new column just have almost zero impact....

**Comment by kilroyFR** [comment]
I have added an additional ID field + sequence to number them uniquely (for SlickGrid/ IIdRow column definition).
I would like the code generated to look something like :

SELECT t0.employeeId, t0.companyId, t1.DateEntry, t1.DateExit 
FROM employee t0 
LEFT JOIN EmployeeCompanyInfos t1 on t0.EmployeeId = t1.EmployeeId and t0.CompanyId = t1.CompanyId

Is that possible ?

**Comment by volkanceylan** [comment]
Foreign Keys are one column to one column as should be in SQL. Add [LeftJoin] on top of your row. See mapping guide.
