### ISSUE TITLE
LookupEditor for Boolean Fields

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#262]
I have a number of fields I'm putting into filters for my table. I've ran into two issues. Firstly with the cascading filter:

I've implemented the cascading filter, per the guide. 

xyzRow.cs has [LookupScript("myModule.table")] and all fields that need filtering have LookupIncluded attribute added as such: 

        [DisplayName("Floor"), Width(100), Size(100), AlignCenter, QuickSearch, LookupInclude]
        public String Floor
        {
            get { return Fields.Floor[this]; }
            set { Fields.Floor[this] = value; }
        }

        [DisplayName("Room Number"), Size(100), Width(100), AlignCenter, LookupInclude]
        public String RoomNumber
        {
            get { return Fields.RoomNumber[this]; }
            set { Fields.RoomNumber[this] = value; }
        }

xycGrid.cs has the cascading defined by overriding the CreateToolbarExtension

            //Floor->Room Cascading Filter [PENDING FIX]
            AddEqualityFilter<LookupEditor>(Fields.Floor,
                options: new LookupEditorOptions { LookupKey = "myModule.table" });
            AddEqualityFilter<LookupEditor>(Fields.RoomNumber,
                options: new LookupEditorOptions
                {
                    LookupKey = "myModule.table",
                    CascadeFrom = Fields.Floor
                });

The fields keep defaulting to the Name property. The fields I'm trying to reference are part of the xycRow.cs thus I would assume I'd be using the LookupKey for the script. Additionally, I need the cascade to be available only on the Grid and not on the Form since the Form will allow manual inputs. I was able to create queries  emulating the ordershipcity and ordershipcountry filters on the Northwind samples and have it work, but I wanted to see if there is a better alternative. 

Secondly, and this one may be a tad trickier, I want to add a filter for a number of boolean fields. I can currently use the 'filterable' function from the Matrix Grid but I wish to have a cascade that allows me to designate: Yes or No but if no selection made, thus Not Applied, to skip filter. (Essentially: Yes/No/Null). 

I've attempted to have the fields in xycRow.cs with LookupInclude and using BooleanEditor or LookupEditor on the xycGrid.cs but no success.

**Comment by volkanceylan** [comment]
See how i implement shipping status filter in order grid for second one. But for first one, didn't understand the problem. Where is your CascadeField btw.

**Comment by sayuga** [comment]
I managed to do what I needed by implementing queries much like OrderShipCity.cs on the Northwind sample and then customizing the output. I essentially, though, wondered if there was a simpler way to accomplish the same. Something such as the following without having to use a LookupKey if the fields are on the same table. 

//Parent
 AddEqualityFilter<LookupEditor>(Fields.Floor) 

//Child
 AddEqualityFilter<LookupEditor>(Fields.RoomNumber,
                options: new LookupEditorOptions {CascadeFrom = Fields.Floor});

I've currently designated the cascade in a Query and in the xyzGrid.cs, 

//Querry Builder

  [LookupScript("FMCorp.MatrixFloor")]
    public class MatrixFloorLookup : MultiTenantRowLookupScript<MyRow>
    {
        Field fld = MyRow.Fields.Floor;
        public MatrixFloorLookup()
        {
            IdField = TextField = fld.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {            
            query.Distinct(true)
                .Select(fld)
                .Where(
                    new Criteria(fld) != "" &
                    new Criteria(fld).IsNotNull());

            AddTenantFilter(query);
        }

        protected override void ApplyOrder(SqlQuery query){}
    }

    //Cascades from FMCorp.MatrixFloor
    [LookupScript("FMCorp.MatrixRoom")]
    public class MatrixRoomLookup : MultiTenantRowLookupScript<MyRow>
    {
        Field fldOne = MyRow.Fields.Floor;
        Field fldTwo = MyRow.Fields.RoomNumber;

        public MatrixRoomLookup()
        {
            IdField = TextField = fldTwo.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            query.Distinct(true)
                .Select(fldOne)
                .Select(fldTwo)
                .Where(
                    new Criteria(fldOne) != "" &
                    new Criteria(fldOne).IsNotNull() &
                    new Criteria(fldTwo) != "" &
                    new Criteria(fldTwo).IsNotNull());

            AddTenantFilter(query);
        }

        protected override void ApplyOrder(SqlQuery query){}
    }

//In MatrixGrid.cs

              //Floor->Room Cascading Filter 
            AddEqualityFilter<LookupEditor>(Fields.Floor,
                options: new LookupEditorOptions { LookupKey = "FMCorp.MatrixFloor" });
            AddEqualityFilter<LookupEditor>(Fields.RoomNumber,
                options: new LookupEditorOptions
                {
                    LookupKey = "FMCorp.MatrixRoom",
                    CascadeFrom = Fields.Floor

I'm having to build individual Queries for each cascade case and wonder if I can simply reuse a preset class such as  AddSomeCascadeClass<CascadeEditor>(ParentField = Field.One, ChildField = Field.Two) without having to state the LookupKey much like with AddDateRangeFilter(Field.Date).

**Comment by volkanceylan** [comment]
AddDateRangeFilter is a helper method, you may write a similar helper if you need such.
