### ISSUE TITLE
Custom Attribute

### ISSUE THREAD

**Issue by chintansoni54** [volkanceylan/Serenity#2620]
How can i create custom attributes like Lookup Attribute.

I want to create sub dialog of dialog.

I tried with create dialog using 

` Serenity.Widget.create({
     type: Test.ChildDialog,
     element: null,
      options: {},
     init: function (dlg) {
                dlg.dialogOpen();
     }
});
`
Child dialog open but some how parent dialog call form submit handler. It seems like old form submit first.

So how can i stop submitting own form.  

Note : I see that lookup attribute do something like that but i want to create my own attribute.

**Comment by Estrusco** [comment]
Try to see here https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables
