### ISSUE TITLE
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

### ISSUE THREAD

**Issue by ghd258** [volkanceylan/Serenity#2623]
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

**Comment by xareas** [comment]
Razor Pages fit well to smaller scenarios where building controllers and models as separate classes is overkill.

**Comment by volkanceylan** [comment]
This feature should be enabled by default, if not, please check Asp.Net Core 2 docs, nothing to do on our side
