### ISSUE TITLE
Setting Lookup FilterValue programmatically

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2625]
hey there,

is it possible to programmatically set FilterValue data on LookupEditor ?
Generally it's hardcoded :
[LookupEditor(("Contratos.Clientes"), FilterField = "GrupoClienteId", FilterValue = 2)]

I would like to know if it's possible to set this value on code (dynamic FilterValue, not set as attribute).

Many thanks !

**Comment by Estrusco** [comment]
See here https://github.com/volkanceylan/Serenity/issues/2440

**Comment by kilroyFR** [comment]
awesome thanks !
