### ISSUE TITLE
view in sql Server

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#2626]
Dear,
I created a view in sql Server and used sergen to generate the grid and columns, but data is not displayed when I log into the system.

![image](https://user-images.githubusercontent.com/7516443/30028614-23170dbe-915c-11e7-8a96-f11c0ea23636.png)

`  [ReadPermission("Inscricao")]
    [ModifyPermission("Inscricao")]
    public sealed class QryEventoRow : Row, IIdRow, INameRow
    {
        [DisplayName("Evento"), Size(250), QuickSearch]
        public String Evento
        {
            get { return Fields.Evento[this]; }
            set { Fields.Evento[this] = value; }
        }

        [DisplayName("Local"), Size(200)]
        public String Local
        {
            get { return Fields.Local[this]; }
            set { Fields.Local[this] = value; }
        }

        [DisplayName("Dt Evento")]
        public DateTime? DtEvento
        {
            get { return Fields.DtEvento[this]; }
            set { Fields.DtEvento[this] = value; }
        }

        [DisplayName("Dt Inscricao")]
        public DateTime? DtInscricao
        {
            get { return Fields.DtInscricao[this]; }
            set { Fields.DtInscricao[this] = value; }
        }

        [DisplayName("Id Evento"), Column("IDEvento"), NotNull]
        public Int32? IdEvento
        {
            get { return Fields.IdEvento[this]; }
            set { Fields.IdEvento[this] = value; }
        }

        [DisplayName("Id Local"), Column("IDLocal"), NotNull]
        public Int32? IdLocal
        {
            get { return Fields.IdLocal[this]; }
            set { Fields.IdLocal[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.IdLocal; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Evento; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public QryEventoRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public StringField Evento;
            public StringField Local;
            public DateTimeField DtEvento;
            public DateTimeField DtInscricao;
            public Int32Field IdEvento;
            public Int32Field IdLocal;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Inscricao.QryEvento";
            }
        }
    }`

**Comment by Febriantos** [comment]
Any error message?

**Comment by juliermefelix** [comment]
you do not have an error message, the view data does not appear.

**Comment by JohnRanger** [comment]
Hi @juliermefelix ,

**2 questions:**

(1) Are there any records displayed when you query the same view within SQL management Studio? (e.g. select * from <your_view>)

(2) Is there an identifier field within your view (e.g. the underlying table has an identity field and this field is also within the view)?

With kind regards,

John

**Comment by juliermefelix** [comment]
answer
1) yes. I am seeing the data when I run the query in SQL Management Studio
![image](https://user-images.githubusercontent.com/7516443/36921211-36ec9318-1e42-11e8-82ff-261e3080add4.png)
2) yes
![image](https://user-images.githubusercontent.com/7516443/36921268-72d064b8-1e42-11e8-8195-5f6b9c1d33f9.png)

**Comment by kilroyFR** [comment]
I made it work with Oracle view so that should work with SqlServer.

did you try : 

public RowFields()
            : base("[dbo].[myview]")

or TableName("[dbo].[myview]")

**Comment by juliermefelix** [comment]
when generating the sergen data and then compiling the error in that part of the code
  IIdField IIdRow.IdField
         {
             get {return Fields .; }
         }

as if you were missing a field. I add in the code the "IdEvento" field and compile again, but the records do not appear.

   IIdField IIdRow.IdField
         {
             get {return Fields.IdEvento; }
         }

**Comment by brunobola** [comment]
Try to use a trick so your view have a primary key.

http://girlfromoutofthisworld.com/entity-framework-and-setting-primary-keys-on-views/

**Comment by leahmayschneider** [comment]
You also need to add protected getIdProperty() { return [TableName]Row.idProperty; } to [TableName]Grid.ts and [TableName]Dialog.ts.

**Comment by juliermefelix** [comment]
is giving the error below.
![image](https://user-images.githubusercontent.com/7516443/38028154-65733842-3268-11e8-976a-1f77e2e493d1.png)

already added getIdProperty ()

**Comment by brunobola** [comment]
@juliermefelix you defined a id property that is repeated, check the message !!!
primary keys can not be repeated of course....

**Comment by juliermefelix** [comment]
Yes, OK. but it's a query, I need to display query data on the grid. How do I solve this?

**Comment by brunobola** [comment]
@juliermefelix did you see my previous comment in wich a say for you to see this:

http://girlfromoutofthisworld.com/entity-framework-and-setting-primary-keys-on-views/

**Comment by juliermefelix** [comment]
@brunobola 
I used the explanations of the article indicated above, and I generated it again with sergen and now it is ok.

Thank you for your help.
