### ISSUE TITLE
filter with field diferent than Id, Name

### ISSUE THREAD

**Issue by evagelos21** [volkanceylan/Serenity#2627]
Hi to All,
I have DB looks like this:
Table **Item**:
**Item**(ID Auto increment), **Code**, **Name**, **ERPid**
Table **Sizes**
**SIZEID**(Barcode EAN13),**Item**(ID Of Item table),**Code**,**Name**
Table **Basket** 
**ID**(ID Auto increment), **Item**(ID Of Item table), **SIZEID**(ID Of Sizes table), **QTY**(Normal Decimal Field)

How can I Filter the values of Sizes depending the selected Item in BasketDialog.ts
I have tried the "this.form.Sizes .filterValue" but as I see I can filter only with **ID** or **text** field. Really why **text** and not **name**? in BasketRow there are  IIdRow and INameRow.

How can I add more fields in the BasketDialog.ts "filterField" ?I read in many places about Custom FieldEditor/custom editor. Is this the right place? Can anyone provide me an example or a how to?

**Comment by evagelos21** [comment]
thanks a lot for your interest.
my Code is like this:
`[LookupEditor(typeof(Cs2Row), CascadeFrom = "Item", CascadeField = "Item")]
        public String Cs2
        {
            get { return Fields.Cs2[this]; }
            set { Fields.Cs2[this] = value; }
        }
`
but it still does not work and brings all the data from the table (properties cascadeField and  cascadeFrom are null. 

thanks in advance

**Comment by javaman63** [comment]
You have to use a LookupInclude Atribute parameter on you cascade row

Check it!

**Comment by evagelos21** [comment]
No, I have added but the same:
`[DisplayName("Db.Default.Basket.CS2"), Column("CS2"), Size(50)]
[LookupInclude]
[LookupEditor(typeof(Cs2Row), CascadeFrom = "Item", CascadeField = "Item")]
public String Cs2
{
	get { return Fields.Cs2[this]; }
	set { Fields.Cs2[this] = value; }
}
`

Still not filtering

**Comment by javaman63** [comment]
on your chrome console, type Q.GetLookUp(typeof(Cs2Row)), on Items you should see the Field "Item", if you dont, you put the lookupinclude attribute on the wrong field

**Comment by evagelos21** [comment]
In BasketDialog.ts I add a break point in "afterLoadEntity" and there is the point witch I see that are nulls (var a = this.form.Cs2.cascadeField).
in Chrome Concole "Q.GetLookUp(typeof(Cs2Row))" returns "Uncaught TypeError: Q.GetLookUp is not a function"

**Comment by javaman63** [comment]
![untitled-1](https://user-images.githubusercontent.com/8239681/30083720-05c27428-9266-11e7-87ec-19137076bde9.png)

IdProvinciaPart, IdLocalidadPart --> Are my Lookinclude fields (cascade field)

**Comment by evagelos21** [comment]
in Chrome with Q.getLookup (small g) I get: 
Uncaught Error: Script data Lookup.undefined is not found in registered script list!
    at loadScriptData (Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:1610)
    at Object.ensure (Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:1627)
    at Object.getLookup (Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:1699)
    at <anonymous>:1:3
loadScriptData @ Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:1610
ensure @ Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:1627
getLookup @ Serenity.CoreLib.js?v=JUDCYVeHtw6kQtpTs3EhMA2:1699
(anonymous) @ VM268:1

**Comment by evagelos21** [comment]
When I execute Q.getLookup("Default.CS2") in Chrome it brings only the columns Cs2, Code and Name and not the columns Item and Qty which also have LookupInclude.... I don't underdstand why it does not bring these columns (Item and Qty).
If I remove LookupInclude from Code then it brings Cs2 and Name, which is partially correct, because it still does not bring the other two columns (Item and Qty).

**Comment by volkanceylan** [comment]
Check that you don't have multiple lookups with same key, and these columns are mapped.
