### ISSUE TITLE
Like search in QuickFilter

### ISSUE THREAD

**Issue by amnippon** [volkanceylan/Serenity#2629]
How do I like ( `%SearchText%` ) search in `QuickFilter` in text field.

**Comment by WasimAhmad** [comment]
override getQuickFilters() like this..

 protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            let filters = super.getQuickFilters();
            let fld = Welfare.DaughterMarriageGrantRow.Fields;
            let filter = Q.first(filters, x => x.field == fld.EmpName);
            filter.title = "Applicant Name";
            filter.type = Serenity.StringEditor;
            filter.handler = h => {
                if (h.active) {
                    h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
                        [[fld.EmpName], 'like', '%' + h.value + '%']);
                }
            };
                h.active = !!h.value;
                if (h.active) {
                    this.rowSelection.clear();
                    this.toolbar.findButton('send-button').toggle(h.active);
                    h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
                        [[fld.Status], '=', 'Eligible']);
                    h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
                        ['is null', [fld.ProcessingDate]]);
                    ;
                } else {
                    this.toolbar.findButton('send-button').hide();
                }
            };

            return filters;
        }

**Comment by amnippon** [comment]
Thanks for you reply friend. Let me try.

**Comment by amnippon** [comment]
Thank you for reply friend. Let me try.

**Comment by amnippon** [comment]
Thank you @WasimAhmad, It working nicely.

**Comment by ali-h2010** [comment]
@WasimAhmad Where to override this? In xyzGrid.ts? 
I am able to override the function but 'Q' is unknown and the code seems to be outdated
