### ISSUE TITLE
Error	CS1056	Unexpected character '

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#263]
Merhaba Volkan. 
aşağıdaki duruma rastladın mı ?
![6](https://cloud.githubusercontent.com/assets/16984654/13111220/54a23386-d58d-11e5-84ed-819afabd23b0.JPG)

**Comment by volkanceylan** [comment]
Malesef. Garip bir karakter var sanırım dosyalarda, kodlamaları bozulmuş ta olabilir, utf-8 with bom deneyin.

**Comment by volkanceylan** [comment]
İ harfinden yapmıştı buna benzer birşey ANSI kodlamalı dosyada

**Comment by Olricz** [comment]
Tamamdır. Benim ortamla alakalı.
