### ISSUE TITLE
UserRetriveService GetFirst(...) method returns null for User even if user exists in table Users

### ISSUE THREAD

**Issue by HairyPloper** [volkanceylan/Serenity#2631]
I was working on same database with same application hosted on different virtual machines, and occasionally with same username\password i could log in on one Web page but not on the other.
I debugged and saw that 
`var user = connection.TrySingle<Entities.UserRow>(criteria);`
returns null in one case, but user is present in table. 
If i try (on the same db\table)
``var user = connection.List<Entities.UserRow>(criteria);``
it will return list of users correctly.

> Workaround is to manually go into DB and update\change username to lower\upper-case(one letter is enough) and i can log in again.

Eager to hear any idea, thanks in advance

**Comment by HairyPloper** [comment]
I solved problem, 
If you set up your database\table to be searched as key sensitive(CA) and you insert incorrect value for username (etc. Admin instead of admin). TwoLevelCache will cache it as invalid credentials

`return TwoLevelCache.Get<UserDefinition>("UserByName_" + username.ToLowerInvariant(), 
                TimeSpan.Zero, TimeSpan.FromDays(1), fld.GenerationKey, () =>
            {
                using (var connection = SqlConnections.NewByKey("VTassure"))
                    return GetFirst(connection, new Criteria(fld.Username) == username);
            });`
and because of  `username.ToLowerInvariant()` , it will be invalid for both "Admin" or "admin" (doesn`t care for upper\lower-case letters).But your Db\table doesn, so if you try then to put "admin" it will not go into database to look up for user, it will find it in cache and will reject.

**Comment by volkanceylan** [comment]
Yes, if your user table is case sensitive you should change that code accordingly, maybe username.ToLowerInvariant() inside criteria as well. But you should be storing usernames in lower case also in DB. Anyway if possible use CI collation.
