### ISSUE TITLE
How to Override these static members...

### ISSUE THREAD

**Issue by WasimAhmad** [volkanceylan/Serenity#2632]
I want to change change the text "edit filter" to something else like "Advance Filter" on a filterable grid..
i have archived this by this.element.find('.edit').text('Advance Filter');

I have read in C# or java we can't override a static member of parent class. 

what's about if i want to change FilterPanel=>DialogTitle = "Advance Search"???
can i move these members in Texts.cs under modules in Web Project???

namespace Serenity.Web
{
    internal static partial class Texts
    {
        public static partial class Controls
        {
            public static class FilterPanel
            {
                public static LocalText AddFilter = "add criteria";
                public static LocalText All = "<all>";
                public static LocalText And = "and";
                public static LocalText AndInParens = "(and)";
                public static LocalText ChangeAndOr = "click to switch between AND/OR";
                public static LocalText CurrentFilter = "Active Filter: {0}";
                public static LocalText SelectField = "---select field---";
                public static LocalText RemoveField = "remove criteria";
                public static LocalText InvalidOperator = "invalid operator";
                public static LocalText InvalidDate = "invalid date!";
                public static LocalText InvalidNumber = "invalid number!";
                public static LocalText Or = "or";
                public static LocalText OrInParens = "(or)";
                public static LocalText ResetButton = "reset";
                public static LocalText SearchButton = "apply filter";
                public static LocalText ValueRequired = "value required!";
                public static LocalText GroupBy = "--group--";
                public static LocalText ThenBy = "--then by--";
                public static LocalText ApplyGroups = "apply grouping";
                public static LocalText ClearGroups = "clear grouping";
                public static LocalText DialogTitle = "Edit Filter";
                public static LocalText EditFilter = "edit filter";
                public static LocalText ResetFilterHint = "clear filter";
                public static LocalText EffectiveFilter = "Active Filter:";
                public static LocalText EffectiveEmpty = "none";
                public static LocalText FixErrorsMessage = "Please fix errors that are marked in red";

                public static class OperatorNames
                {
                    public static LocalText @true = "yes";
                    public static LocalText @false = "no";
                    public static LocalText contains = "contains";
                    public static LocalText startswith = "starts with";
                    public static LocalText eq = "equal";
                    public static LocalText ne = "not equal";
                    public static LocalText gt = "greater than";
                    public static LocalText ge = "greater than or equal";
                    public static LocalText lt = "less than";
                    public static LocalText le = "less than or equal";
                    public static LocalText bw = "between";
                    public static LocalText @in = "in";
                    public static LocalText isnull = "is null";
                    public static LocalText isnotnull = "is not null";
                }

                public static class OperatorFormats
                {
                    public static LocalText @true = "{0} = yes";
                    public static LocalText @false = "{0} = no";
                    public static LocalText contains = "{0} contains '{1}'";
                    public static LocalText startswith = "{0} starts with '{1}'";
                    public static LocalText eq = "{0} = {1}";
                    public static LocalText ne = "{0} <> {1}";
                    public static LocalText gt = "{0} > {1}";
                    public static LocalText ge = "{0} >= {1}";
                    public static LocalText lt = "{0} < {1}";
                    public static LocalText le = "{0} <= {1}";
                    public static LocalText bw = "{0} is between {1} and {2}";
                    public static LocalText @in = "{0} is one of [{1}]";
                    public static LocalText isnull = "{0} is null";
                    public static LocalText isnotnull = "{0} is not null";
                }
            }
        }
    }
}

**Comment by Estrusco** [comment]
In \\Scripts\site\texts\site.texts.invariant.json you can add an entry like

"Controls.FilterPanel.EditFilter":  "Advance Filter"

**Comment by volkanceylan** [comment]
Yes, either edit them in translation UI, or write a similar class and fill texts, you don't need to override anything.
