### ISSUE TITLE
Serenity-User-specific row filtering / hiding records from other users

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2634]
Dear all,

I am Standing before a new Project with Serenity - but before I start I wanted to clear an issue which will be a Show stopper if I don't find a solution for it.

What should the app do? 
It will be a small "file sharing" platform for my Company where multiple users can upload files which they want to "share" with someone outside our Network. The app will run on our on-Premises web Server as I don't trust any file sharing platform not under our own full Control (incl source Code :-))

What I want is basically, that a user - which will be defined within serenity's Standard user management - can create a new file upload (record with metadata within database and a file which will be uploaded through http and stored on our webserver's local harddisk). All users Uploads (Metadata) will be stored within the same table.

**Challenge:** Each user should only see (be able to manage) his/her Uploads - so I need a "hard" filtering of the records on Basis of the currently logged on user - which the user cannot override.

Within the table, I thought of having a column with the id of the user which created the "upload" record.

But how to pre-filter that table for this user within Serenity this I do not know.

How can I achieve this with Serenity?

Thanks for your help and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Hi John,

In your MyListHandler override ApplyFilters

if (!Authorization.HasPermission("SomePermissionThatLetsUserSeeAllRows")
query.Where(fld.CreatedByUserId == Convert.ToInt32(Authorization.UserId))

**Comment by JohnRanger** [comment]
Hi Volkan,

wow - that was the fastest Reply I got ever on any new issue :-) And such an elegant solution. I love SF.

Thank you very much for your help.

Wish you a nice evening.

With Kind regards,

John

**Comment by JohnRanger** [comment]
For the reference - if someone wants to do the same, here the full MyListHandler method (you find this in xyzRepository.cs):

```cs
private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                if (!Authorization.HasPermission("SomePermissionThatLetsUserSeeAllRows"))
                {
                    query.Where(fld.UserId == Convert.ToInt32(Authorization.UserId));
                }
            }

        }
```

Hope this helps someone.

John

**Comment by sangincode404** [comment]
I have a Patient Table and in this table i have a column UserId where i store user id of a logged in user automatically in the background when i insert Patient data. I tried your methods shown here but i couldn't get any solutions.Please can anybody help me how to solve this issue. Im using Serene latest verson .net core.
