### ISSUE TITLE
Authorization.hasPermission always returns FALSE

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2636]
Hello! Help me Please! Authorization.hasPermission("") in .....Grid.ts  always returns FALSE. Granted permissions to the user and role. ((   
in UserEndpoint.cs changed "ScriptUserPermissions:" on "UserPermissions:", did not help. 
In ...Row.cs for fields works without problems.

```
protected getColumns() {
.......... 
           alert(Authorization.hasPermission("Role:FRP"));
            alert(Authorization.hasPermission("Razr"));
            alert(Authorization.hasPermission("Role:RP"));
            alert(Authorization.hasPermission("FRP"));
.......
}
```

**Comment by Zahar661** [comment]
I also set up LDAP Authorization

**Comment by volkanceylan** [comment]
Don't change anything, open a new Serene project, check what you changed to break it.

**Comment by Zahar661** [comment]
In another project without LADA, everything works fine. When connecting LDAP I used the instruction
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_authenticate_with_active_directory_or_ldap.html

**Comment by volkanceylan** [comment]
It changes nothing.

**Comment by Zahar661** [comment]
Hooray! Found! Precisely calculate and describe.
