### ISSUE TITLE
Add button [Today] to assign today to TransDate in Dialog , then Call Update Services;

### ISSUE THREAD

**Issue by kcvincent** [volkanceylan/Serenity#2637]
protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();

            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
    
            buttons.push(
                {
                    title: 'Today',
                    cssClass: 'outlook-meeting-button',
                    onClick: () => {
                        this.form.TransDate.valueAsDate = new Date();
                        // How to Call the Save Service ??
                    }
                }
            );

            return buttons;
        }

**Comment by javaman63** [comment]
`

            buttons.push(Common.ExcelExportHelper.createToolButton({
                grid: this,
                service: SolicitudesService.baseUrl + '/ListExcel',
                onViewSubmit: () => this.onViewSubmit(),
                separator: true
            }));

`

this is an example to export to excel, see the guide and examples

**Comment by kcvincent** [comment]
protected getToolbarButtons()
        {
            let buttons = super.getToolbarButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
	buttons.push(
            {
                title: '',
                cssClass: 'approve-button',
				onClick: () => {
				Q.confirm('Are you Confirm ?', 
							() => {
									var row = Q.deepClone(this.entity) ;
									row.StatusId = 4;
									MCD.MCDApproveService.Approve(
										{EntityId : row.SNId,Entity : row},
										response => { 
											this.loadById(row.SNId);
											Serenity.SubDialogHelper.triggerDataChange(this);
										}
									);
							
									});
                },
				separator: true
            });

            return buttons;
        }
