### ISSUE TITLE
Editor Hatası

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#264]
Volkan Selam,

Dün bilgisayarı kapattıgımda proje çalışıyordu. Bugun build ettim. Editor ile ilgili bişey bulamıyor. Update ettim. Update de yok diyor..

![capture](https://cloud.githubusercontent.com/assets/16984654/13120389/4ed56ecc-d5b6-11e5-9075-f3947c010de8.JPG)

**Comment by volkanceylan** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/faq/troubleshooting.html

**Comment by Olricz** [comment]
Burası mı ? 

I'm getting several ambiguous reference errors after adding a file to Script project :
Remove System.dll reference from script project. Visual Studio adds this reference when you use Add New File dialog. Saltarelle Compiler doesn't work with such references, as it has a completely different runtime.+

Please use copy/paste to create code files in Script project.

**Comment by volkanceylan** [comment]
Yes, System.dll referansını sileceksiniz

**Comment by Olricz** [comment]
Çok tesekkur ederım.
