### ISSUE TITLE
'set' method throws error that value falls outside of the vMin / vMax range

### ISSUE THREAD

**Issue by HairyPloper** [volkanceylan/Serenity#2640]
I have row that contains negative value (-1) and when i try to open dialog with 
`dialog.loadByIdAndOpenDialog(...);` i get error message 

>  The value (-1) from the 'set' method falls outside of the vMin / vMax range

I tracked error to the root and seams that error is here in this call.

`load: function(source) {
			for (var i = 0; i < this.$editors.length; i++) {
				var item = this.$items[i];
				var editor = this.$editors[i];
				if (!!(this.get_mode() === 0 && !ss.isNullOrUndefined(item.defaultValue) && typeof(source[item.name]) === 'undefined')) {
					source[item.name] = item.defaultValue;
				}
				here----- >>$Serenity_EditorUtils.loadValue(editor, item, source);
			}
		},`

I didn`t read complete documentation ,Are negative values restricted from entity rows, or this is configurable.
PS. When i switch value to 0++ dialog opens without errors. Where i can configure vMin-vMax values inline for specific dialog or globaly
Thanks in advance.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/wiki/Frequently-Asked-Questions
