### ISSUE TITLE
Failing to publish - Duplicate identifier

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2641]
Alright, just tried publishing the project and am getting these errors causing the publish to fail. Building the project locally works fine, these errors don't even show up. Any ideas?

![image](https://user-images.githubusercontent.com/31215482/30215297-918b731a-947d-11e7-8d7d-f387a997c52b.png)

lib.es6.d.ts ln 4956
```
declare namespace Reflect {
    function enumerate(target: any): IterableIterator<any>;
}
```

lib.es6.d.ts ln 5537
```
declare namespace Reflect {
    function apply(target: Function, thisArgument: any, argumentsList: ArrayLike<any>): any;
    function construct(target: Function, argumentsList: ArrayLike<any>, newTarget?: any): any;
    function defineProperty(target: any, propertyKey: PropertyKey, attributes: PropertyDescriptor): boolean;
    function deleteProperty(target: any, propertyKey: PropertyKey): boolean;
    function get(target: any, propertyKey: PropertyKey, receiver?: any): any;
    function getOwnPropertyDescriptor(target: any, propertyKey: PropertyKey): PropertyDescriptor;
    function getPrototypeOf(target: any): any;
    function has(target: any, propertyKey: PropertyKey): boolean;
    function isExtensible(target: any): boolean;
    function ownKeys(target: any): Array<PropertyKey>;
    function preventExtensions(target: any): boolean;
    function set(target: any, propertyKey: PropertyKey, value: any, receiver?: any): boolean;
    function setPrototypeOf(target: any, proto: any): boolean;
}
```

Serenity.CoreLib.d.ts ln 5
```
declare var Reflect: any;
```

**Comment by z-combs** [comment]
Got it, getting different errors now. Looking into fixing them.

**Comment by shakazulu89** [comment]
hey @z-combs 
Can you share how you got around this? having the same issue :/

**Comment by z-combs** [comment]
The only thing I ended up doing to fix this was upgrade my visual studio to the newest version. Sorry if it doesn't help very much.

**Comment by z-combs** [comment]
I started having this issue again today and was able to get my commits/publish to go through by Transforming T4 Templates and NOT rebuilding after. It seems the rebuild after cleared the whatever the transform cleaned. I don't think this is a permanent fix and completely expect it to happen again, but it may work for others so I thought I'd share.
