### ISSUE TITLE
ImageUploadEditor  only save files to Temporary folder

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#2645]
Hi, i am really really thankfull for updating to core 2.0 ! After reading the guidence from the Master my project was fully working and everyting looks soo butifull (thanks @volkanceylan i am really promising to get you beers some day ) 
But here it is the problem now: 
I use service request to update a little bit the user profile: 

` using Serenity.Data.Mapping;
namespace PatientManagement.Membership
{
    using Serenity.ComponentModel;
    using Serenity.Services;
    using System;
    using System.ComponentModel;

    [FormScript("Membership.EditUserProfileRequest")]
    public class EditUserProfileRequest : ServiceRequest
    {
        [DisplayName("Display Name"), Required]
        public string DisplayName { get; set; }

        [DisplayName("Your Email"), Required]
        [EmailEditor]
        public string UserEmail { get; set; }

        [DisplayName("User Web Site")]
        public String UserWebSite { get; set; }

        [DisplayName("User Image"), Size(100)]
        [ImageUploadEditor(FilenameFormat = "UserImage/~", CopyToHistory = true)]
        public String UserImage { get; set; }
        

        [DisplayName("User Email Signature"), Size(-1), NotNull, HtmlContentEditor, CssClass("email-signature")]
        public String USerEmailSignature { get; set; }
    }
}`

and the problem is that, every time i use the image uploader , the image is saved to Temporary folder not correct one from the attribute 

this is in the view: 
`     <div class=" active tab-pane" id="settings">
                    <div class=" tab-pane" id="user-profile-editing">

                        <script id="Template_Membership_EditUserProfilePanel" type="text/template">

                        <form id="~_Form" action="">
                            <div class="s-Form">
                                <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                                    <div id="~_PropertyGrid"></div>
                                    <div class="clear"></div>
                                </div>
                                <div class="buttons">
                                    <button id="~_EditUserProfileSubmitButton" type="submit" class="btn btn-primary">
                                        @Texts.Forms.Membership.Profile.ButtonSaveProfile

 
                                    </button>
                                </div>
                            </div>
                        </form>
                    </script>
                        <div id="EditUserProfilePanel">
                        </div>
                    </div>
                </div>`

And the initialization

`<script type="text/javascript">
    $(function () {
        new Membership.EditUserProfilePanel($('#EditUserProfilePanel')).init();
    });
</script>`

And the Action in the Controller:

`[HttpPost, JsonFilter]
        public Result<ServiceResponse> EditUserProfile(EditUserProfileRequest request)
        {
            return this.UseConnection("Default", connection =>
            {
                request.CheckNotNull();
                
                
                var user = (UserDefinition)Serenity.Authorization.UserDefinition;

                if (request.DisplayName.IsEmptyOrNull())
                    throw new ArgumentNullException("name");

                if (request.UserEmail.IsEmptyOrNull())
                    throw new ArgumentNullException("email");

                var userEntity = connection.ById<UserRow>(user.Id);
                userEntity.DisplayName = request.DisplayName;
                userEntity.Email = request.UserEmail;
                userEntity.UserImage = request.UserImage;
                userEntity.EmailSignature = request.USerEmailSignature;
                userEntity.WebSite = request.UserWebSite;

                connection.UpdateById(userEntity);

                return new ServiceResponse();
            });
        }`

Here it is the TS file, only one small issue here is to set existing file to ImageUploadEditor 

namespace PatientManagement.Membership {

    @Serenity.Decorators.registerClass()
    export class EditUserProfilePanel extends Serenity.PropertyPanel<EditUserProfileRequest, any> {

        protected getFormKey() { return EditUserProfileForm.formKey; }

        private form: EditUserProfileForm;

        constructor(container: JQuery) {
            super(container);

            this.form = new EditUserProfileForm(this.idPrefix);

            var user = <Administration.UserRow>{};

            console.log(Authorization.userDefinition.UserId);

            Administration.UserService.Retrieve(<any>{
                EntityId: Authorization.userDefinition.UserId
            },
                resp => {
                    user = resp.Entity;
                    this.form.DisplayName.value = user.DisplayName;
                    if (this.form.UserImage.value != null)
                        this.form.UserImage.value.Filename = user.UserImage;
                        
                    this.form.UserEmail.value = user.Email;
                    this.form.UserWebSite.value = user.WebSite;
                    this.form.USerEmailSignature.value = user.EmailSignature;
                });

            this.byId('EditUserProfileSubmitButton').click(e => {
                e.preventDefault();

                if (!this.validateForm()) {
                    return;
                }

                var request = this.getSaveEntity();
                Q.serviceCall({
                    url: Q.resolveUrl('~/Account/EditUserProfile'),
                    request: request,
                    onSuccess: response => {
                        Q.information(Q.text('Forms.Membership.Profile.Success'), () => {
                            location.reload();
                        });
                    }
                });
            });
        }
    }
}

**Comment by volkanceylan** [comment]
If you directly update a record in DB, behaviors won't be triggered, so upload behavior can't intercept save and move files to correct target.

Use your repository to update the record, e.g. new UserRepository().Update(...)

You may get permission errors as user row has administration permission, but you may work around that by using transientgrantingpermissionservice and temporarily granting user that permission during update

**Comment by Magik3a** [comment]
Soo i change the controller to 

[HttpPost, JsonFilter]
        public Result<ServiceResponse> EditUserProfile(EditUserProfileRequest request)
        {
            return this.UseConnection("Default", connection =>
            {
                request.CheckNotNull();
                var user = (UserDefinition)Serenity.Authorization.UserDefinition;

                if (request.DisplayName.IsEmptyOrNull())
                    throw new ArgumentNullException("name");

                if (request.UserEmail.IsEmptyOrNull())
                    throw new ArgumentNullException("email");

                var saveRequest = new SaveRequest<UserRow>();
                saveRequest.Entity = connection.ById<UserRow>(user.Id).Clone();
                saveRequest.EntityId = user.UserId;

                saveRequest.Entity.UserId = user.UserId;
                saveRequest.Entity.DisplayName = request.DisplayName;
                saveRequest.Entity.Email = request.UserEmail;

                if (!request.UserImage.IsNullOrEmpty())
                    saveRequest.Entity.UserImage = request.UserImage;

                saveRequest.Entity.EmailSignature = request.USerEmailSignature;
                saveRequest.Entity.WebSite = request.UserWebSite;
                saveRequest.Entity.PhoneNumber = request.UserPhone;
                
                new UserRepository().Update(new UnitOfWork(connection), saveRequest);

                UserRetrieveService.RemoveCachedUser(user.UserId, user.Username);

                return new ServiceResponse();
            });
        }

but i got error that say: Password field on UserRow is read before assigned a value!
And do you have any idea how to add picture to ImageUploadEditor, this is what i try for now 

  
            Administration.UserService.Retrieve(<Administration.UserRow>{
                EntityId: Authorization.userDefinition.UserId
            },
                resp => {
                    user = resp.Entity;
                    this.form.DisplayName.value = user.DisplayName;
                    if (this.form.UserImage.value != null)
                        this.form.UserImage.value.Filename = user.UserImage;

                    this.form.UserPhone.value = user.PhoneNumber;
                    this.form.UserEmail.value = user.Email;
                    this.form.UserWebSite.value = user.WebSite;
                    this.form.USerEmailSignature.value = user.EmailSignature;
                });

**Comment by volkanceylan** [comment]
Create a new user row dont use byid

**Comment by Magik3a** [comment]
Worked like a charm, thank you for everything !!! 

Finally for the permissions: 

I added this in Startup.cs

     services.AddSingleton<ITransientGrantor, Serenity.Web.TransientGrantingPermissionService>();
directly after

     services.AddSingleton<IPermissionService, Administration.PermissionService>();

and in the action: 

                var perminsion = Dependency.Resolve<IPermissionService>();

                var grantor = new TransientGrantingPermissionService(perminsion);
                grantor.GrantAll();

                try
                {
                }
                finally
                {
                    grantor.UndoGrant();
                }

but i get error 
No service for type 'Serenity.Abstractions.IRequestContext' has been registered.

**Comment by volkanceylan** [comment]
Register Serenity.Web.RequestContext before that

**Comment by Magik3a** [comment]
Yep, this fixed the error but permissions are not granted and 400 error . I try even with 

                var grantor = Dependency.Resolve<ITransientGrantor>();

**Comment by volkanceylan** [comment]
You had to wrap your permission service with transient granting one, see comments in its constructor

**Comment by Magik3a** [comment]
Dude, i dont know what more to say... Thanks man, really really thank you! 
here it is the fix 

            services.AddSingleton<IPermissionService>(new TransientGrantingPermissionService(new PermissionService()));
            services.AddSingleton<IRequestContext, Serenity.Web.RequestContext>();

and this is cleaned 

 services.AddSingleton<IPermissionService, Administration.PermissionService>();

**Comment by pradeep-pandit** [comment]
Just remove this attribute [ImageUploadEditor(FilenameFormat = "UserImage/~", CopyToHistory = true)] from Form and put it in Row.
