### ISSUE TITLE
check permissions for user that does not have permission for userRow 

### ISSUE THREAD

**Issue by MBagherii** [volkanceylan/Serenity#2646]
I want to hide buttons for users that doesn't have permission.for example when I have created a user that can only read data not update,create and delete so I use this code bellow 
           
 if (!(Authorization.hasPermission("Default:Business:Delete"))) { 
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
            }
            if (!(Authorization.hasPermission("Default:Business:Update"))) { 
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "save-and-close-button"), 1);
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "apply-changes-button"), 1);    
            }

but because the user doesn't have permission for security module it throws exception. what should I do?

**Comment by Zahar661** [comment]
What is the exception? You do not need access to the security module. Permissions are cached during authorization and the access from the TS goes to the cache line.

**Comment by javaman63** [comment]
With this I Hide some categorys and the pdf button..check it out

`
            if (Authorization.userDefinition.UserId != 1) {
                this.form.FechaInicioOrden.element.closest('.category').toggle(false);
                this.form.ListaEstados.element.closest('.category').toggle(false);
                this.toolbar.findButton(".export-pdf-button").remove();
            }


`

**Comment by MBagherii** [comment]
I used bellow code for hide buttons for users does not have permission...
but it throw exception : Serenity.Services.ValidationError       
 getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            if (!Authorization.hasPermission("Default:Attribute:Delete")) { /*buttons = buttons.slice(3);*/
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
            }
            if (!Authorization.hasPermission("Default:Attribute:Update")) { /*buttons = buttons.slice(3);*/
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "save-and-close-button"), 1);
                buttons.splice(Q.indexOf(buttons, x => x.cssClass == "apply-changes-button"), 1);
            }
            return buttons;
        }

**Comment by volkanceylan** [comment]
Make sure GetUserData method in your UserEndpoint.cs looks like this:

```
        [NonAction, DataScript("UserData", CacheDuration = -1), ServiceAuthorize]
        public ScriptUserDefinition GetUserData()
```

You might be missing ServiceAuthorize there.

**Comment by MBagherii** [comment]
I checked it. It is the same.

        [NonAction, DataScript("UserData", CacheDuration = -1), ServiceAuthorize]
        public ScriptUserDefinition GetUserData()

**Comment by JohnD832** [comment]
What does the `CacheDuration = -1` do?
