### ISSUE TITLE
Generate Autoincrement (Identity) before saving

### ISSUE THREAD

**Issue by antoniojp** [volkanceylan/Serenity#2649]
I use Serenity with **MySQL**, and I need to have control in generating the autoincrement field of a table. In Serenity I put the **[Identity]** tag, but the field (base.Row.Id) is only updated after the recording, which is obvious.

However I need to know the field Id to update some fields of the record itself in the same table. Using the **BeforeSave()** event, the Id field is not updated (null), and using **AfterSave()**, I can not update the fields because the "existing primary key" message is displayed. I tried to use **SQLUpdate** in the **AfterSave()** method, but it returns Timeout, I believe it is because the registry is locked.

I thank the help of all you.

_Ps_: In time, I already researched here in the forum but I did not get any similar case.

**Comment by Estrusco** [comment]
An identity field is auto incremented and is not updatable.
If you want auto generate your Id, you have to remove Identity attribute and set PrimaryKey attribute, and also remove identity from your DB (if present) and then set your Id value in BeforeSave.

If you are in insert mode (save after new record), you have to commit current transaction before make an update. 

```cs
UnitOfWork.Connection.GetCurrentActualTransaction().Commit();
```
Anyway you can override SetInternalFields() to set your fields in insert/update transaction. You can test IsCreate property to test if you are in insert or in update fase.

**Comment by antoniojp** [comment]
Thanks, Entrusco.

I put it in **AfterSave()** and it worked, but always the message `"Transaction has already been committed or is not pending"` is displayed, and does not close **Dialog**. However, when I close the dialog, I realize that he did exactly what he was expecting.

Any ideas how not to display this message?

**Comment by Estrusco** [comment]
If yuo have committed the transaction, try to open new before the update, with UnitOfWork.Connection.BeginTransaction();


Your steps:

AfterSave -> commit current insert - open new transaction - update

Then this last transaction is closed by Serenity

**Comment by antoniojp** [comment]
Hi, Entrusco. The **BeginTransaction()** has worked, but the message `"Transaction has already been committed or is not pending"` is still displayed. I do not know why the Serenity framework displays this message. I am sending the code snippet for a better illustration.

```
protected override void AfterSave() {
	base.AfterSave();
	/*---various treatments---*/

	IDbConnection conexao = UnitOfWork.Connection;
	if (base.IsCreate) {
		conexao.GetCurrentActualTransaction().Commit();
		conexao.BeginTransaction();
		
		var campos = MyRow.Fields;
		new SqlUpdate("remessas")
			.Set(campos.QtdeBoletos, qtdeBoletos)
			.Set(campos.DataProcessamento, DateTime.Now)
			.Set(campos.Status, 1)
			.Set(campos.Arquivo, nomeArquivo)
			.WhereEqual(campos.RemessaId, base.Row.RemessaId)
			.Execute(conexao);
	}
}
```

After closing the Dialog, we verified that all the commands worked, that is, it works, but the message continues.

**Comment by volkanceylan** [comment]
Check your triggers, triggers shouldn't commit or rollback any transaction.

**Comment by antoniojp** [comment]
Hi Volkan. My program does not have triggers in DB tables.

**Comment by volkanceylan** [comment]
Don't commit transaction, or begin new one as recommended or as shown in your code.

Your ID is available in AfterSave method, and you should use this.Connection to execute any actions. You were probably opening a new connection, so in that connection/transaction your new ID is not available.

**Comment by antoniojp** [comment]
Hi, Volkan. You're right!

The `UnitOfWork.Connection` object was creating another connection instance. I changed to **this.Connection**, removed the `Commit()` and `BeginTransaction()`, and it worked.

I thank everyone!

**Comment by nfulgen** [comment]
Hi,

I have this scenario below we want to auto populate customer id field before save. It will contain 3 letter prefix "CUS" + auto increment number  which will be the max Id from customer table + 1. Any idea how i can implement this?

Thank you in advance

**Comment by VictorTomaili** [comment]
Can you ask this question to stackoverflow with [serenity-platform](https://stackoverflow.com/questions/tagged/serenity-platform) tag instead closed issue?
