### ISSUE TITLE
Noob Question - Advanced Filter Dialog (Multiple Criteria)

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#2650]
Look at all the issues and examples online and I could not find how to use this dialog.
Does anyone have any examples of how to use this dialog with multiple criteria?
Thanx in advance

![example](https://user-images.githubusercontent.com/8239681/30342945-022ae3e2-97d2-11e7-97b6-686428fc8449.png)

**Comment by volkanceylan** [comment]
You already used it with multiple criteria. If you mean about grouping paranthesis etc just click paranthesis.

**Comment by javaman63** [comment]
I just want to use this dialog. How can i lunch it ? The "Edit Filter" link doesn't appear in my grid @volkanceylan 

I was looking at all the issues but I could not find an example of how to use it

![filter](https://user-images.githubusercontent.com/8239681/30692904-be5a16f0-9ea3-11e7-8ced-8c923bd45ea0.png)

**Comment by volkanceylan** [comment]
Add 

@Serenity.Decorators.filterable()

on top of your Grid class

**Comment by javaman63** [comment]
THANNNNK YOUUU!!!
