### ISSUE TITLE
Sending email from dialog

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2651]
Anyone have any idea how I would implement nodemailer to send emails from a dialog?

I've done the `npm install nodemailer` and `npm install nodemailer-smtp-transport` and started trying to create a new email helper typescript file but I keep getting a typescript error on `require` in my line `var nodemailer = require('nodemailer');`

**Comment by javaman63** [comment]
Serenity has his own helper to send mail, you can use this: 
`
     Common.EmailHelper.Send(emailSubject, emailBody, Authorization.UserDefinition.Email);
`

and you have to configure you web.config

`
      <smtp from="your@account.com" deliveryMethod="Network">
        <network host="your.mail.server.com" userName="user" password="password" />
      </smtp>

`
Checkit out

**Comment by z-combs** [comment]
> Serenity has his own helper to send mail, you can use this:
Common.EmailHelper.Send(emailSubject, emailBody, Authorization.UserDefinition.Email);

Yes, that works in a c# file, you can't use it from a typescript file.

**Comment by javaman63** [comment]
you can call a service from a button, to send a mail

**Comment by z-combs** [comment]
How would I do that? I've been going crazy all day trying to figure out how to get this working and I'm about ready to put it aside.

**Comment by javaman63** [comment]
Check de issue [2637](https://github.com/volkanceylan/Serenity/issues/2637)

**Comment by z-combs** [comment]
#2302 is closer but still has me lost. I have no clue where to even start with doing this.

**Comment by z-combs** [comment]
Alright, so i finally got this after sleeping on it. 

In my endpoint I added:
```c#
[HttpPost, ServiceAuthorize(typeof(MyRow))]
public void SendEmail() { 
    //Code to send email
}
```
After doing transforming the T4 templates and rebuilding, `SendEmail` finally showed up in my Dialog by using `xyzService.SendEmail();`. 

My xyzService.ts has lines added:
```typescript
//...
export declare function SendEmail(request: Serenity.ServiceRequest, onSuccess?: (response: null) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;

export namespace Methods {
    export declare const SendEmail: string;
}

['Create', 'Update', 'Delete', 'Retrieve', 'List', 'SendEmail'].forEach(x => {
//...
```

**Comment by z-combs** [comment]
Alright so after adding in the parameters to the c# SendEmail, how do I pass them in from typescript?
Doing this `xyzService.SendEmail({ subject: "", body: "", address: ""}, () => { });` throws me a `SCRIPT438: Object doesn't support property or method 'SendEmail'`

**Comment by z-combs** [comment]
So I looked into the different requests and saw that ListRequest has a few `List<string>` fields I could use to pass the information in but my transform T4 and rebuilds are not regenerating the SendEmail lines in my Service.ts, any idea what I'm doing wrong?

**Comment by amust** [comment]
Try follow this steps:
Thanks to @z-combs for your following advice 👍 
i just make some changes from your suggestion, it works for me.

1. *Endpoint.cs
------------------------------------------------------------------------------------------------------- 
[HttpPost, ServiceAuthorize(typeof(MyRow))]
 public void SendEmail(IUnitOfWork uow, SaveRequest<MyRow> request)
{
     string subjectMail = "subjectMail";
     Common.EmailHelper.Send(subjectMail, BodyMailNotification(request), request.Entity.ContactMail );
}


2. *XYZService.ts
------------------------------------------------------------------------------------------------------
 export namespace XYZService {
.................................................................................              
                 export declare function SendEmail(request: Serenity.SaveRequest<TicketRow>, onSuccess?: (response: Serenity.SaveResponse) => void, opt?: Serenity.ServiceOptions<any>): JQueryXHR;

        export namespace Methods {
          .............................
            export declare const SendEmail: string;
        }

        ['Create', 'Update', 'Delete', 'Retrieve', 'List','SendEmail'].forEach(x => {
            ............................
    }


3. *Dialog.ts
----------------------------------------------------------------------------------------------------------
protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();
            //buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
            buttons.push(
                {
                    title: 'Send Mail Notification',
                    cssClass: 'outlook-meeting-button',
                    onClick: () => {
                            Q.confirm('Send Mail Notification ?',
                                () => {
                                    XYZService.SendEmail(
                                        { EntityId: this.entityId, Entity:this.entity },
                                        response => {
                                            Serenity.SubDialogHelper.triggerDataChange(this);
                                        }
                                    );

                                });
                    }
                }
            );
            return buttons;
        }

**Comment by stixoffire** [comment]
@javaman63 Do you know if I can override that behavior of using the web.config and instead just put it in the EmailHelper - the reason I want to do this; is that my user is logged in with ActiveDirectory and when they create a specific xyzRow - I want to notify another specific user via email. My intent is to use the users own email address and password from the active directory to send an email to the required people ..

 
"
Common.EmailHelper.Send(emailSubject, emailBody, Authorization.UserDefinition.Email);

and you have to configure you web.config

  <smtp from="your@account.com" deliveryMethod="Network">
    <network host="your.mail.server.com" userName="user" password="password" />
  </smtp>
"
