### ISSUE TITLE
The method or operation is not implemented.

### ISSUE THREAD

**Issue by Vviobiscu** [volkanceylan/Serenity#2653]
I have two table as per below pictures:

![image](https://user-images.githubusercontent.com/19631322/30363324-6381b6a2-9868-11e7-9e8c-ca1a345dd56f.png)

after I add rows to the second table (details) I click the "save" for the in memory List. Then I click "Update" to the main form and get error "The method or operation is not implemented."

![image](https://user-images.githubusercontent.com/19631322/30363516-2e6d3a6c-9869-11e7-8bce-f21cb51ce1b3.png)

` public class TestSablonsRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            request.Entity.Id =  Guid.NewGuid(); 
            request.Entity.CreatedBy = Authorization.Username;
            request.Entity.CreatedDate = DateTime.Now;
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {

            request.Entity.CreatedBy = Authorization.Username;
            request.Entity.CreatedDate = DateTime.Now;
            foreach (Entities.TestSablonRowsRow item in request.Entity.TestList)
            {
                if (item.Id == null) {
                    item.Id = Guid.NewGuid();
                    item.TestId = request.Entity.Id;
                    item.CreatedBy = Authorization.Username;
                    item.CreatedDate = DateTime.Now;
                }

            }
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }`

fail on this line:  return new MySaveHandler().Process(uow, request, SaveRequestType.Update);

**Comment by JohnRanger** [comment]
Hi,

how are the two Tables related? From the field names this is not clear as there is no field Name in 2nd table which corresponds to a field in 1st table.

with Kind regards,

John

**Comment by Vviobiscu** [comment]
ID from TestSablons este TestID in TestSablonRows  (Foreign Key)

Vio

**Comment by volkanceylan** [comment]
If you are using MasterDetailRelation set CheckChangesOnUpdate = false
