### ISSUE TITLE
ProductExcelImport Error

### ISSUE THREAD

**Issue by Hochmah** [volkanceylan/Serenity#2658]
I was trying to implement the ProductExcelImport by myself and getting this error. So I've installed I new instance with samples. And I'm getting the same error on a fresh install.

![1](https://user-images.githubusercontent.com/20425869/30434590-1097bbd6-993e-11e7-87db-bebce7c18f7c.PNG)

Looking old issues I founded this workaround, but unfortunately didn't work.
![2](https://user-images.githubusercontent.com/20425869/30434791-7b944dfa-993e-11e7-8d79-a61caadac3ca.PNG)

The error occurs on super() call of constructor extended from Serenity.PropertyDialog.

![3](https://user-images.githubusercontent.com/20425869/30434940-e45ff622-993e-11e7-98e7-337506b5e36b.PNG)

**Comment by volkanceylan** [comment]
Actually not copy to output directory but content type should be "Content" for publish to work properly.
