### ISSUE TITLE
AD integration appsetting 

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2659]
Microsoft shifted the application settings from web.config and into appsettings.json file. According to the Serenity developer guide, it states to put in web.config file. Should this be moved to appsettings.json? If yes, please provide correct syntax.

Also, I put the AD setting into web.config for Serenity 3.0.5.1 CORE version. The directoryService in ValidateFirstTimeUser is returning a null value. I am on a Microsoft Active Directory corporate network.

Thanks for the help

**Comment by VR-Architect** [comment]
I tried this also in appsettings.json but still getting a null for directoryService.

```
{
  "Data": {
    "Default": {
      "ConnectionString": "xxxxx",
      "ProviderName": "System.Data.SqlClient"
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AppSettings": {
    "LocalTextPackages": {
      "Site": [ "Controls.", "Db.", "Dialogs.", "Enums.", "Forms.", "Permission.", "Site.", "Validation." ]
    },
    "ScriptBundling": {
      "Enabled": false,
      "Minimize": true,
      "UseMinJS": true
    },
    "UploadSettings": {
      "Path": "~/App_Data/upload/"
    },
    "ActiveDirectory": {
      "Domain": "MyDomainNameHere"
    }
  }
}

```

**Comment by volkanceylan** [comment]
I don't think AD works in .NET Core, if it does you should put settings under AppSettings => ActiveDirectory

**Comment by VR-Architect** [comment]
According to this article it is supported. 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth 

I tried putting the setting in both files and they both work to kick off the logic to call the AD service. It is just return back a null.

**Comment by volkanceylan** [comment]
That's IIS windows auth, not .NET Core windows auth

**Comment by volkanceylan** [comment]
It's not supported yet, sorry.
