### ISSUE TITLE
Help with Lookup filter by current field in form

### ISSUE THREAD

**Issue by thefitar** [volkanceylan/Serenity#2661]
Hi, I have a form with a field "CompanyId" and  other field named "Site" with a LookupEditor. 
What I need is to be able to only show on "Site" options that are related (in database) to "CompanyId".

Example:
CompanyId = 1; (this value should come from the form)
only show in "Site" options that in the database have a specific column (CompanyId) with the value 1.

So far I have this:

```
[LookupScript("Information.Sites")]
 public class SitesLookup : RowLookupScript<SitesRow>
    {
        protected override void PrepareQuery(SqlQuery query)    {
            base.PrepareQuery(query);
            query.Where(SitesRow.Fields.CompanyId == 1);  /*Here I need something like this.form.CompanyId*/
        }
  }
```

Thanks.

**Comment by Estrusco** [comment]
You can use cascadeFrom option in lookup attribuite. Search in basic sample.

**Comment by thefitar** [comment]
Thanks!

**Comment by kilroyFR** [comment]
Any chance thefitar, you have sample of code. I have exactly same request and having hard time with CascadeFrom Syntax.
