### ISSUE TITLE
Modify Serenity Menu Navigation

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#2662]
Hi there

I am quite new with this framework, I am trying to move the side bar menu (on the left) to be ontop just like the menu in this page i.e. https://github.com/volkanceylan/Serenity/issues 

I was looking at the following css less files i.e. control-sidebar.less, sidebar-mini.less, sidebar.less, I made changes and I had no luck. Is there an easier way to achieve this? Also are there templates (in serenity) that can be incorporated on the site?

**Comment by volkanceylan** [comment]
Sorry, you have to be competent in CSS to achive something like that.
