### ISSUE TITLE
This Form Error -  Please help!

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#2667]
Hi, I'm new in Serenity, and stuck in problem : this.form.ID.value  on lookup field with name , return : 

throw new ss.Exception(ss.formatString("Element has no widget of type '{0}'!", ss.getTypeFullName(TWidget)));

                        var servicecall = TArtikliService.TArtikliBulkActionRequest(
                            {
                                ArtikliIDs: this.selectedItems,
                                BrendIDs: +this.form.IdTBrendovi.value

                            },

I use dialog to get value for batch process. When I use regular field and enter number, everything work fine. But when I use lookup filed with name, can't get ID in table of that name. 
The +this.form.Id.value stuck with "element has no widget"

I'm going to take premium service, but need start project to show.

**Comment by Estrusco** [comment]
Try Serenity.EditorUtils.getValue(this.form.IdTBrendovi) to get value. 

`
var idVal = Serenity.EditorUtils.getValue(this.form.IdTBrendovi);
`

Why you put the plus sign before this.form ?

**Comment by volkanceylan** [comment]
Transform your T4 templates, anytime you change an editor type in a form / row, you need to transform T4. This is stated in guide, please first complete guide and tutorials.

**Comment by Nikola7i** [comment]
Tnx for your help, but it's not that. I have this problem only with any  IDfield who is filed with name from another table in dropdown lookup. If I manualy put number work's fine.
In green filed work fine. In red can't get ID. When press button for bulk action, nothing happens.

![image](https://user-images.githubusercontent.com/16926063/30666482-c298f992-9e54-11e7-904d-ced1084ae5b7.png)

**Comment by Nikola7i** [comment]
This is what i caught :  
![image](https://user-images.githubusercontent.com/16926063/30666598-283836d2-9e55-11e7-88da-800ba1e949f6.png)

**Comment by volkanceylan** [comment]
Transform templates!
