### ISSUE TITLE
localization logon screen 

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2668]
hey ! wouldn't it be appropriate to have the selection of LANGUAGE with USER/PASSWORD login infos ?
(so that user can select his language on login).
He can still have the ability to change it later with top menu but on login it's still displayed with one unique language.

PS : or if anyone did modify login screen to allow selection of language it would be perfect

**Comment by volkanceylan** [comment]
You may apply similar language box in login screen as well, see source for it in layout page.

**Comment by kilroyFR** [comment]
I am coming back to this question.

In the LoginRequest.cs i have added the 'Language' member

```
namespace Mercury.Membership
{
  using Serenity.ComponentModel;
  using Serenity.Services;

  [FormScript("Membership.Login")]
  [BasedOnRow(typeof(Mercury.Entities.UserRow))]
  public class LoginRequest : ServiceRequest
  {
    public string language { get; set; }

    public string Username { get; set; }

    [PasswordEditor, Required(true)]
    public string Password { get; set; }

    [Ignore]
    public string TwoFactorGuid { get; set; }
    [Ignore]
    public int? TwoFactorCode { get; set; }
  }
}
```
But how should i define that this field should be a list ?

**Comment by kilroyFR** [comment]
@volkanceylan i would like to fix the first issue 
(after selection the field is set to blank after switching value).

How can i keep displayed the current value in the select2 language dropdown 
(and not reset it to blank once user changed the value) ?
