### ISSUE TITLE
Excel and Pdf buttons

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#2670]
Hello Volkan,
The Excel and Pdf buttons are not appearing on top of my grid. How do enable them?
![capture](https://user-images.githubusercontent.com/14317420/30544586-8010fcda-9c76-11e7-9aaa-7bcc74fee297.PNG)

**Comment by javaman63** [comment]
On your XYZGrid.ts put the following

`
        protected getButtons() {
            var buttons = super.getButtons();

            buttons.push(Common.ExcelExportHelper.createToolButton({
                grid: this,
                service: FormulariosService.baseUrl + '/ListExcel',
                onViewSubmit: () => this.onViewSubmit(),
                separator: true
            }));

            buttons.push(Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()

            }));

`

**Comment by gfo2007** [comment]
Thanks. Please do you have an idea how I can format the columns in terms of their width?

**Comment by javaman63** [comment]
On your xyzcolumns.cs use the atribute 
`

        [Width(80)]
        public String SomeField{ get; set; }


`

**Comment by gfo2007** [comment]
I want the formatting in the pdf report not the grid itself

**Comment by javaman63** [comment]
Take a look to the jsPDF documentation

https://github.com/MrRio/jsPDF/tree/master/docs

**Comment by javaman63** [comment]
Also take a look to the helper in your serenity project

PdfExportHelper.ts
