### ISSUE TITLE
PropertyGrid manual update

### ISSUE THREAD

**Issue by costinmilea** [volkanceylan/Serenity#2671]
I'm writing an application which is pretty much similar with the tutorial's "The cast and Characters they played" example. In fact there are three List type objects similar with the CastList (public List\<MovieCastRow\> CastList). In the "Row" type file the code looks similar with the tutorial's one:

[MasterDetailRelation(foreignKey: "MovieId", IncludeColumns = "PersonFullname")]
[DisplayName("Cast List"), NotMapped]
public List\<MovieCastRow\> CastList
{
get { return Fields.CastList[this]; }
set { Fields.CastList[this] = value; }
}

for all three GridEditorBase derived objects.

What is different is that I'm not using the "add-button" class type generated by default in the examples code (it is removed), but working with other buttons, still of "add-button" class type, but each having another functionality (those buttons are in fact adding data in the underlying database, but with different data and in different columns).

The problem is I cannot update the grids associated with the Lists (those similar with the CastList) to reflect the change in the database.

Can you help me with a hint / how to do in this matter?

**Comment by volkanceylan** [comment]
See GridEditorBase and how it works.

**Comment by costinmilea** [comment]
Thank you for your answer, but I read that code I'm getting no clue how to or where to start. Please, can you give me more on this?

**Comment by costinmilea** [comment]
I just raised you a question, why did you close the issue?

**Comment by volkanceylan** [comment]
This place is for Issues, not tutoring

https://github.com/volkanceylan/Serenity/wiki/Issue-Guidelines
