### ISSUE TITLE
Dialog with tabs inside other dialog

### ISSUE THREAD

**Issue by thefitar** [volkanceylan/Serenity#2672]
Hi, I have a dialog showing 2 tabs (a form and a list), when I click on any item of the list (second tab) another dialog shows up with the details but it is not showing the tabs for that specific form. 

So I'd like to know if its posible ?

**Comment by volkanceylan** [comment]
Sorry, need to provide more details, code, screenshots etc.

**Comment by thefitar** [comment]
Hi, I'm leaving a scheenshot with the detail.
Thanks!
![tabs](https://user-images.githubusercontent.com/26069981/30712947-5c6e0412-9ed3-11e7-927a-6c1566fb3a7b.jpg)

**Comment by volkanceylan** [comment]
Then you need to convert your other dialog into tabs, e.g. declare a template for it etc. See movie tutorial.

**Comment by Zahar661** [comment]
Perhaps it. for a grid on a tab, you can specify which dialog to open and for this dialog create a template by analogy one.

**Comment by thefitar** [comment]
Thanks!
