### ISSUE TITLE
Database is locked Error for SqLite Database in AspNetCore 2.0

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#2675]
![database is locked](https://user-images.githubusercontent.com/4013722/30592338-fa38d490-9d63-11e7-8987-49547311ed56.png)

**Comment by samdubey** [comment]
Solved by putting 
"Default": {
      "ConnectionString": "Filename=App_Data/Fees_Default_v1.sqlite;**cache=shared**",
      "ProviderName": "Microsoft.Data.Sqlite"
    }

**Comment by Zezis** [comment]
That didn't solve the problem for me

**Comment by samdubey** [comment]
check you have opened another Connection object which is accessing database
