### ISSUE TITLE
Fluent Migration don't insert special character

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#2677]
Hi Volkan,

When database is created, it can't insert original special character, like "_Respiratória_" or "_Fonoaudiólogo_" in data.

It's inserting like "_Respirat?ria_" or "_Fonoaudi?logo_".

All insert data script are in a plain sql file. When I open this file direct in SQL Server Manager and execute it, all data are inserted correctly.

So, where is the problem ?

**Comment by volkanceylan** [comment]
Check encoding of the file, make sure it is UTF-8 with BOM

**Comment by rolembergfilho** [comment]
It's works.

Thanks!
