### ISSUE TITLE
Force Q.getLookup to re-run

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2678]
Is there any way to force a Q.getLookup to run again after you close a dialog and open a new instance of it? From testing the only time I've seen the lookup update is when the page is refreshed.

For the time being I'm using `window.location.reload();` but I'd still like to see if there is a better way of doing this that refreshing the page.

**Comment by volkanceylan** [comment]
Q.reloadLookup

**Comment by z-combs** [comment]
That worked after I moved everything from my `constructor` to `afterLoadEntity` and added all of the `Q.reloadLookup` that are used in the filtering before the rest of the code in `afterLoadEntity`

```typescript
protected afterLoadEntity() {
    super.afterLoadEntity();

    Q.reloadLookup(RowA.lookupKey);
    Q.reloadLookup(RowB.lookupKey);
    Q.reloadLookup(RowC.lookupKey);

    //...
}
```
