### ISSUE TITLE
how to set the default PageSize  in gird?

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#268]
I want to set a default nums about page rows in grid? I see the source file "dataGrid.cs" have a function CreatePager()   which have a variable rowsPerPage. But how can i use it in my seren system?

**Comment by volkanceylan** [comment]
Override GetViewOptions and set RowsPerPage to 100 etc.

**Comment by kuyu7766** [comment]
Thank you

**Comment by kuyu7766** [comment]
Thank you

**Comment by VGsss** [comment]
```
protected getViewOptions() {
	let opt = super.getViewOptions();
	//Default option
	opt.rowsPerPage = 10;
	return opt;
}
```

```
protected getPagerOptions() {
	let opt = super.getPagerOptions();
	//Options in the dropdown
	opt.rowsPerPageOptions = [10, 25, 50, 100];
	return opt;
}
```

**Comment by qprotex** [comment]
I needed to add Slick.PagerOptions as the return type:

protected getPagerOptions(): Slick.PagerOptions {
            var opt = super.getPagerOptions();
            opt.rowsPerPageOptions = [20, 100, 500, 2500, 5000]
            return opt;
        }
