### ISSUE TITLE
Icons are not visible when running from docker

### ISSUE THREAD

**Issue by GeorgeKuczogi** [volkanceylan/Serenity#2680]
First of all, thank you for the Serenity framework, it is absolutely great.
I have created a new web app by sergen under ASP.NET Core 1.1. I have no modifications besides providing DB access. 

If I run it under Kestrel on my dev box (no docker), icons are fine.
When I deployed the app to a docker container and run it on the server, icons are not visible. 

Please see screenshot below. Could you give me any advise, where to look? 

![missing-favicon](https://user-images.githubusercontent.com/18260577/30679788-2c577baa-9e9c-11e7-88e9-db49ff6128cb.png)

**Comment by volkanceylan** [comment]
Either you didn't deploy fonts under fonts directory or your server lacks a mapping for woff fonts. See browser console. This is not a Serenity specific issue.

**Comment by GeorgeKuczogi** [comment]
Thank you. It turned out to be a docker related problem. Somehow the content inside the docker container is not the same as in the dev environment. For the same reasons, popup dialogs do not work either.
