### ISSUE TITLE
change adminlte Theme

### ISSUE THREAD

**Issue by guiRui11** [volkanceylan/Serenity#2681]
Does anybody already change the adminlte theme serenity has with the most recent one or another one ?
That would be great.

Also I can't seem to put the signarR workink even after following the wiki :(

By the way awesome framework...

**Comment by Magik3a** [comment]
For the signalr implamentation: If you use latest Serenity package and you write your code based on the WIKI you have really big problems with .net frameworks. Latest SignalR package was introduced with verry big article before a week check the link [HERE](https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/)

I will try to create a new wiki after a few hours/days.

**Comment by volkanceylan** [comment]
There shouldn't be any problems in latest version, and SignalR supports .NET CORE 2 i think.
