### ISSUE TITLE
How to add Custom Editable drop down in Grid

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#2682]
Hello, 
For custom drop down I create typescript file 
    @Serenity.Decorators.registerEditor()
    export class XYZType extends Serenity.Select2Editor<any, any> 
    {
       ...
      this.addItem({ id: "", text: "" });
      ...
    }
and in Row I used it 
       [DisplayName("Type"), NotNull, Width(150), XYZType]
        public String Field1
        {
            get { return Fields.Field1[this]; }
            set { Fields.Field1[this] = value; }
        }

I want create editable drop down in grid and want to use XYZType editor 

  protected getColumns() {
           var columns = super.getColumns();
            var fld = OtherRow.Fields;
            var sp = Q.first(columns, x => x.field === fld.Field1);
            sp.referencedFields = [fld.Field1];
            // facing problem here to add XYZType  
            sp.format = ctx => this.selectFormatter(ctx, fld.Field1,XYZType  );

  }

How I can use custom drop down (Select2Editor) in Grid? or How to use hard coded drop down? 
Or any other alternative. 

Thanks

**Comment by rakeshpatil20** [comment]
Hello,
 Because am using hard coded drop down i don't have XYZrow.getLookup(). 
`sp.format = ctx => this.selectFormatter(ctx, fld.Field1,XYZRow.getLookup() );`

can anybody help me to add custom drop down in grid??

**Comment by Zahar661** [comment]
Hi!
In the comments to the Grid Editor, it is written that there are no questions on this topic ((
I would have written this part of the code to the one I needed for a particular case.
![image](https://user-images.githubusercontent.com/26430136/30733810-4061398e-9f81-11e7-8725-cd6e92724d5b.png)

**Comment by rakeshpatil20** [comment]
Thanks for your replay. 

I already added selectFormatter. 
but How can pass hard-coded value to `, lookup: Q.Lookup<any>)`

thanks

**Comment by dfaruque** [comment]
see this
https://github.com/dfaruque/Serenity.Extra#to-make-a-detail-grid-inline-editable

**Comment by rakeshpatil20** [comment]
I removed last parameter from selectFormatter method, and manage code as per @Zahar661  suggested.
