### ISSUE TITLE
Localization not working for custom ServiceRequest .net core 2

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#2683]
Hi Master, i add new service request in a new folder Profile under Membership/Account.
Aftet that i add new .cs file with following code: 

`
[FormScript("Membership.EditUserProfile")]
    public class EditUserProfileRequest : ServiceRequest
    {
        [DisplayName("Display Name"), Required]
        public string DisplayName { get; set; }

        [DisplayName("Your Email"), Required]
        [EmailEditor]
        public string UserEmail { get; set; }
        [DisplayName("Your phone")]
        public string UserPhone { get; set; }

        [DisplayName("User Web Site")]
        public String UserWebSite { get; set; }

        [DisplayName("User Image"), Size(100)]
        [ImageUploadEditor(FilenameFormat = "UserImage/~", CopyToHistory = true)]
        public String UserImage { get; set; }
        

        [DisplayName("User Email Signature"), Size(-1), NotNull, HtmlContentEditor, CssClass("email-signature")]
        public String USerEmailSignature { get; set; }
    }`

But in translations page, this fields not exist

**Comment by volkanceylan** [comment]
That system only works for Rows, not Forms, if your fields are based on some row fields, put BasedOnRow attribute to that form, and use captions from row itself.

**Comment by Magik3a** [comment]
Thanks master, like every time, worked like a charm!
