### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#2685]
Hello,

I am getting the error below during compilation. Is this something to be concerned with?

> 1>------ Rebuild All started: Project: LCPermits.Web, Configuration: Debug Any CPU ------
> 1>  LCPermits.Web -> C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\bin\LCPermits.Web.dll
> 1>  '"C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.5\"' is not recognized as an internal or external command,
> 1>  operable program or batch file.
> 1>C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\LCPermits.Web.csproj(2805,5): warning MSB3073: The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.5\" -project "C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\tsconfig.json"" exited with code 9009.
> ========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by kilroyFR** [comment]
Looks like you have problem with TypeScript. i would check or install it again.

**Comment by volkanceylan** [comment]
Edit CSProj, find $(TscToolExe) replace it with tsc

**Comment by c9482** [comment]
Thanks, this worked but I got these 2 warnings now. Can I ignore these?

> 1>------ Rebuild All started: Project: LCPermits.Web, Configuration: Debug Any CPU ------
> 1>  LCPermits.Web -> C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\bin\LCPermits.Web.dll
> 1>C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\Modules/Northwind/Customer/CustomerEditor.ts(4,67): warning TS2559: Type 'CustomerRow' has no properties in common with type 'LookupEditorOptions'.
> 1>  
> 1>C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\Modules/Organization/BusinessUnit/BusinessUnitEditor.ts(4,71): warning TS2559: Type 'BusinessUnitRow' has no properties in common with type 'LookupEditorOptions'.
> 1>  
> 1>C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\LCPermits.Web.csproj(2806,5): warning MSB3073: The command ""C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.5\tsc.exe" -project "C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\tsconfig.json"" exited with code 2.
> ========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
>

**Comment by volkanceylan** [comment]
Change them like this:

```ts
export class CustomerEditor extends Serenity.LookupEditorBase<Serenity.LookupEditorOptions, CustomerRow>

export class BusinessUnitEditor extends Serenity.LookupEditorBase<Serenity.LookupEditorOptions, BusinessUnitRow>
```

**Comment by c9482** [comment]
The first error was resolved. The 2nd one still remains:

![image](https://user-images.githubusercontent.com/17013052/30815489-fee7d53a-a1d8-11e7-98d6-521fe9799c94.png)
