### ISSUE TITLE
Get parent of Dialog Editor

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#2686]
Hi,

I have an editor that is used in a lot of place (e.g. Contact Editor, that used in Patience, Professional and Supplier form).

So, I need to get the parent Dialog name or type in order to toggle some fields.

I know a solution in #837

I would like another way that don't need to create variable to store parent form name.

**Comment by rolembergfilho** [comment]
None solution ?

**Comment by dfaruque** [comment]
you may use my serenity utils
https://github.com/dfaruque/Serenity.Extra#to-access-parentmaster-dialog-from-childdetail-dialog

**Comment by rolembergfilho** [comment]
@dfaruque thanks for sharing your code.
