### ISSUE TITLE
how to change defaut page size from 100 to 20?

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#2687]
i try to set it in getSlickOptions(), but not work. can anyone help me?

**Comment by kilroyFR** [comment]
I would try something like this:

```
        protected GetViewOptions() {
            var opt = super.getViewOptions();
            opt.rowsPerPage = 20;
            return opt;
        }
```

**Comment by PanChenhao** [comment]
thanks for you help.  I have add the code, but it doesn't work.

**Comment by kilroyFR** [comment]
getViewOptions instead of GetViewOptions. Sorry my mistake

**Comment by PanChenhao** [comment]
I will try this. thank again.
