### ISSUE TITLE
Using Utc date only will set chosen date to chosen date minus one day

### ISSUE THREAD

**Issue by D-R-Contracting-Ltd** [volkanceylan/Serenity#2689]
I need a date chooser and I don't care about the time. I have the following set up. Everything is displayed correctly but when updating/saving a record on the form a day is removed from the chosen day. 

If I have DateTimeKind set to use Local a day is not removed. 

I assume what is happening is that the day is set as the very start of the day and so UTC removes one hour thus putting the day back. The values stored in the DB are just the date as the type is date.

My work around is to use Local, but do you have any suggestions? 

AbcRow.cs
        [DisplayName("End Date"), NotNull]
        [DateTimeKind(DateTimeKind.Local), DateEditor] //Sets the choosen day correctly
        //[DateTimeKind(DateTimeKind.Utc), DateEditor] //Sets the choosen day -1
        public DateTime? EndDate
        {
            get { return Fields.EndDate[this]; }
            set { Fields.EndDate[this] = value; }
        }

AbcColumn.cs
        [DisplayFormat("dd/MM/yy")]       
        public DateTime? EndDate { get; set; }
        
AbcForm.cs
        //    No default required as dates are far in the future 
        public DateTime? StartDate { get; set; }

**Comment by volkanceylan** [comment]
Use DateTimeKind.None if you want to use just date...
