### ISSUE TITLE
sergen converted datetime2 to Stream

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#269]
CREATE TABLE [dbo].[OS](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](10) NULL,
	[CreatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_OS] PRIMARY KEY CLUSTERED 
([ID] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
----

sergen output this:

[DisplayName("Created Date")]
        public Stream CreatedDate
        {
            get { return Fields.CreatedDate[this]; }
            set { Fields.CreatedDate[this] = value; }
        }

This means the editor doesn't know what to do with it, and it won't translate input correctly.

**Comment by wldkrd1** [comment]
And I just saw that datetime2 support is on the todo list. Whoops :+1:

**Comment by volkanceylan** [comment]
You can use String field for DateTime2 columns till this is resolved. Use [DateTimeEditor] on them.

**Comment by volkanceylan** [comment]
It should be working now

**Comment by wldkrd1** [comment]
Not sure if this is related, but I'm seeing some weird behavior in IE11 for dialogs using datetime2 (e.g. an UpdateDate for rows implementing ILoggingRow). Once that field has data, opening the dialog in IE11 does not show the dialog but a flashing cursor where the first field would be. Resizing the IE window then shows the dialog, maximizing the window hides it again. The dialog is in the DOM but it isn't visible. Also, the logo spinner slows to one update per second.

Setting that field to null seems to fix everything. Can't replicate the problem in Firefox.

**Comment by wldkrd1** [comment]
Interesting, it doesn't seem to matter if that field is shown in the dialog, so long as it exists in the entity. Here's an example Entity field: "UpdateDate":"2016-02-24T11:13:49.217"

**Comment by wldkrd1** [comment]
I updated all my tables to have Insert, Update, Delete and IsActive support columns, created a new project from scratch and added all via sergen. Have not been able to reproduce the issue, so you can probably ignore this.
