### ISSUE TITLE
Sheduler Quartz.NET and TemplateHelper.RenderTemplate

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2692]
Hi!
I wrote a scheduler based on Quartz.NET, everything works well except for Serenity.Web.TemplateHelper.RenderTemplate("~/Modules/Sheduler/TaskEmailDeadline.cshtml", emailModel), The value can not be undefined.
![image](https://user-images.githubusercontent.com/26430136/30845978-6e66a100-a29e-11e7-884a-a5a29f4764dd.png)
Similarly, from an authorized user, everything works fine.
![image](https://user-images.githubusercontent.com/26430136/30846250-8fc29362-a29f-11e7-9801-fad07708e6c8.png)

**Comment by VictorTomaili** [comment]
one of a property is null while you trying to render your model. You must check your template and model. If you can't find, we need to see your template and model for telling you what is wrong. Also in all cases, it looks like your issue, not serenity :) check twice your cshtml file for possible null reference errors.

**Comment by VictorTomaili** [comment]
Ok, I see, Quartz.net doesn't use a HttpContext, and razor generator needs it.

**Comment by Zahar661** [comment]
@VictorTomaili thank you
