### ISSUE TITLE
GPS Coordinates in Text Editor

### ISSUE THREAD

**Issue by Tripex48** [volkanceylan/Serenity#2693]
I have a project whereby GPS coordinates must be added to a textbox within a form, once a button is clicked.

Although I have the code to add HTML5 GPS functionality, I have not been able to determine where to put the JavaScript script. Added hereto, I also cannot identify how to access the relevant textbox within the JavaScript.

Ideally, I would like to have an interface similar to the DateTime Picker; but instead want GPS coordinates.

Any suggestions on how the above could be achieved, will be sincerely appreciated.

**Comment by rolembergfilho** [comment]
Hi @Tripex48,

you can follow the instructions in #413 to coding (javascript, and all)

and about a new editor (an inputbox with custom button) you can take the steps explained in https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables

(of course: it's show how to create a new kind of lookup. but you'll get the idea in how to create new atribute, editor, and more)
