### ISSUE TITLE
Personal paketi hakkında sorularım

### ISSUE THREAD

**Issue by musullu** [volkanceylan/Serenity#2698]
Merhaba Volkan Bey,

Personal paketini almayı düşünüyorum da bir kaç sorum olacak. Burdan mı yazayım ya da size ulaşabileceğim mail adresi varsa ordan mı yazayım?

İyi çalışmalar.

**Comment by volkanceylan** [comment]
Merhaba, profilimde e-mail adresim gözüküyor, oradan yazabilirsiniz.
