### ISSUE TITLE
Force LookupScript reload/refresh server side

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#2699]
Dear @volkanceylan,
I need to refresh a LookupScript server side (normally I do that client side with the Q.reloadLookup() utility):
which is the proper way to do that?
Lookups are stored in the TwoLevelCache and/or LocalCache and should be removed from them?

Thank you very much
Bye

**Comment by sayuga** [comment]
You can simply set the LookupScript expiration to -1

**Comment by marcobisio** [comment]
Thanks @sayuga for your feedback, but I'm not sure how to do that: could you kindly show me a sample code?

Thanks!

**Comment by volkanceylan** [comment]
[LookupScript("....", Expiration = -1)]

**Comment by marcobisio** [comment]
Thank you very much @volkanceylan 

Bye
