### ISSUE TITLE
KDiff3 required for sergen?

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#270]
![kdiffreq](https://cloud.githubusercontent.com/assets/2817543/13155496/e068cb6e-d632-11e5-9320-384d77b61b24.png)

When updating an existing entity using sergen, it complains that KDiff3 isn't installed or configured. Personally I use diffmerge, but if that's a requirement could you indicate it in the docs or bundle it with your installer?

**Comment by volkanceylan** [comment]
I recommend not generating code twice. You can set it to diffmerge etc. exe location in config file if parameters are similar.

**Comment by wldkrd1** [comment]
I'm fine with installing KDiff3, but I'll need some directions...where to put it, or where to find/edit CodeGenerator.config.

DB tables change over time...new fields get added, deleted, updated. Int becomes BigInt, 1:1 relationships become 1:Many, etc. I'm evaluating Serenity for a business and am trying to get an idea of what will be required in terms of maintenance and modification. If sergen is meant to be run only once, perhaps the docs could be expanded explaining specifically what it does so that we can do the same by hand when we need to?

Thanks!

**Comment by volkanceylan** [comment]
There is such info in docs at several places, to avoid regenerating code unless there are big changes that worth it. And in tutorials i'm always adding new fields manually. If you install KDiff3 to default location, it will find it.

**Comment by volkanceylan** [comment]
Btw, config file is at your solution directory.

Did you see developer guide, there is answer to all these questions there:

https://volkanceylan.gitbooks.io/serenity-guide/content/faq/frequently_asked_questions.html
