### ISSUE TITLE
Missing column "IdUvoznikaP"

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#2700]
Please help, I cant finde reason why descritpion name "ju.[Naziv]" , when I put in Columnn, give error missing column "IdUvoznikaP"
This is row code:
amespace RSP_RetailSalePharmacy.Rsp.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("RSP"), DisplayName("Šifarnik Nadbrendova"), InstanceName("  Nadbrend"), TwoLevelCached]
    [ReadPermission("Rsp:tNadBrend:Read")]
    [InsertPermission("Rsp:tNadBrend:Insert")]
    [UpdatePermission("Rsp:tNadBrend:Update")]
    [DeletePermission("Rsp:tNadBrend:Delete")]
    [LookupScript("Rsp.TNadBrend")]
    public sealed class TNadBrendRow : Row, IIdRow, INameRow
    {        
            #region Id Nad Brend
            [DisplayName("Id Nad Brend"), Column("ID_NadBrend"), Identity]
            public Int32? IdNadBrend { get { return Fields.IdNadBrend[this]; } set { Fields.IdNadBrend[this] = value; } }
            public partial class RowFields { public Int32Field IdNadBrend; }
            #endregion IdNadBrend
                
            #region Id Proizvodac
            [DisplayName("Id Proizvodac"), Column("ID_Proizvodac"), ForeignKey("[dbo].[tProizvodac]", "ID_Proizvodac"), LeftJoin("jIdProizvodac"), TextualField("IdProizvodacNaziv")]
            [LookupEditor(typeof(Rsp.Entities.TProizvodacRow), InplaceAdd = true)]
            public Int32? IdProizvodac { get { return Fields.IdProizvodac[this]; } set { Fields.IdProizvodac[this] = value; } }
            public partial class RowFields { public Int32Field IdProizvodac; }
            #endregion IdProizvodac

            #region X Computor Creator
        [DisplayName("X Computor Creator"), Column("xComputorCreator"), Size(50), QuickSearch]
            public String XComputorCreator { get { return Fields.XComputorCreator[this]; } set { Fields.XComputorCreator[this] = value; } }
            public partial class RowFields { public StringField XComputorCreator; }
            #endregion XComputorCreator
                
            #region Naziv
            [DisplayName("Naziv"), Size(100)]
            public String Naziv { get { return Fields.Naziv[this]; } set { Fields.Naziv[this] = value; } }
            public partial class RowFields { public StringField Naziv; }
            #endregion Naziv
                
            #region Napomena
            [DisplayName("Napomena"), Size(1024)]
            public String Napomena { get { return Fields.Napomena[this]; } set { Fields.Napomena[this] = value; } }
            public partial class RowFields { public StringField Napomena; }
            #endregion Napomena
                
            #region Aktivan
            [DisplayName("Aktivan")]
            public Boolean? Aktivan { get { return Fields.Aktivan[this]; } set { Fields.Aktivan[this] = value; } }
            public partial class RowFields { public BooleanField Aktivan; }
            #endregion Aktivan
                
            #region Zemlja Id
            [DisplayName("Zemlja Id"), Column("ZemljaID")]
            public Int32? ZemljaId { get { return Fields.ZemljaId[this]; } set { Fields.ZemljaId[this] = value; } }
            public partial class RowFields { public Int32Field ZemljaId; }
            #endregion ZemljaId
                
            #region X Creator
            [DisplayName("X Creator"), Column("xCreator"), Size(50)]
            public String XCreator { get { return Fields.XCreator[this]; } set { Fields.XCreator[this] = value; } }
            public partial class RowFields { public StringField XCreator; }
            #endregion XCreator
                
            #region X Datum Kreiranja
            [DisplayName("X Datum Kreiranja"), Column("xDatum_Kreiranja")]
            public DateTime? XDatumKreiranja { get { return Fields.XDatumKreiranja[this]; } set { Fields.XDatumKreiranja[this] = value; } }
            public partial class RowFields { public DateTimeField XDatumKreiranja; }
        #endregion XDatumKreiranja

        #region Foreign Fields

        ////Nadproizvođač
        //[DisplayName("Id Uvoznik Naziv"), Expression("jIdUvoznik.[Naziv]")]
        //public String IdUvoznikNaziv { get { return Fields.IdUvoznikNaziv[this]; } set { Fields.IdUvoznikNaziv[this] = value; } }
        //public partial class RowFields { public StringField IdUvoznikNaziv; }

        ////uvoznik
        //[DisplayName("Uvoznik"), Column("IDUvoznika"), Expression("jIdProizvodac.[ID_UvoznikP]"), ForeignKey("[dbo].[TSifarnikUvoznika]", "IdUvoznikaP"), LeftJoin("jU")]
        //[LookupEditor(typeof(Rsp.Entities.TSifarnikUvoznikaRow))]
        //public Int32? Id_Uvoznika
        //{
        //    get { return Fields.Id_Uvoznika[this]; }
        //    set { Fields.Id_Uvoznika[this] = value; }
        //}
        //public partial class RowFields { public Int32Field Id_Uvoznika; }

        //[Expression("jProvince.[RegionId]"), ForeignKey("Region", "Regionid"), LeftJoin("r")]

        **[Expression("jIdProizvodac.[ID_UvoznikP]"), NotNull, ForeignKey("[dbo].[TSifarnikUvoznika]", "IdUvoznikaP"), LeftJoin("jU2")]
        [LookupEditor(typeof(Rsp.Entities.TSifarnikUvoznikaRow))]
        public Int32? Id_Uvoznika
        {
            get { return Fields.Id_Uvoznika[this]; }
            set { Fields.Id_Uvoznika[this] = value; }
        }
        public partial class RowFields { public Int32Field Id_Uvoznika; }

        [Expression("jU2.[Naziv]")]
        public string Unaziv
        {
            get { return Fields.Unaziv[this]; }
            set { Fields.Unaziv[this] = value; }
        }
        public partial class RowFields { public StringField Unaziv; }**

                [DisplayName("Id Proizvodac Id Uvoznik"), Expression("jIdProizvodac.[ID_Uvoznik]")]
                public Int32? IdProizvodacIdUvoznik { get { return Fields.IdProizvodacIdUvoznik[this]; } set { Fields.IdProizvodacIdUvoznik[this] = value; } }
                public partial class RowFields { public Int32Field IdProizvodacIdUvoznik; }

                        
                [DisplayName("Id Proizvodac Id Tip Proizvodaca"), Expression("jIdProizvodac.[ID_TipProizvodaca]")]
                public Int32? IdProizvodacIdTipProizvodaca { get { return Fields.IdProizvodacIdTipProizvodaca[this]; } set { Fields.IdProizvodacIdTipProizvodaca[this] = value; } }
                public partial class RowFields { public Int32Field IdProizvodacIdTipProizvodaca; }

                        
                [DisplayName("Id Proizvodac Naziv"), Expression("jIdProizvodac.[Naziv]")]
                public String IdProizvodacNaziv { get { return Fields.IdProizvodacNaziv[this]; } set { Fields.IdProizvodacNaziv[this] = value; } }
                public partial class RowFields { public StringField IdProizvodacNaziv; }

                        
                [DisplayName("Id Proizvodac Napomena"), Expression("jIdProizvodac.[Napomena]")]
                public String IdProizvodacNapomena { get { return Fields.IdProizvodacNapomena[this]; } set { Fields.IdProizvodacNapomena[this] = value; } }
                public partial class RowFields { public StringField IdProizvodacNapomena; }

                        
                [DisplayName("Id Proizvodac Aktivan"), Expression("jIdProizvodac.[Aktivan]")]
                public Boolean? IdProizvodacAktivan { get { return Fields.IdProizvodacAktivan[this]; } set { Fields.IdProizvodacAktivan[this] = value; } }
                public partial class RowFields { public BooleanField IdProizvodacAktivan; }

                        
                [DisplayName("Id Proizvodac Zemlja Id"), Expression("jIdProizvodac.[ZemljaID]")]
                public Int32? IdProizvodacZemljaId { get { return Fields.IdProizvodacZemljaId[this]; } set { Fields.IdProizvodacZemljaId[this] = value; } }
                public partial class RowFields { public Int32Field IdProizvodacZemljaId; }

                        
                [DisplayName("Id Proizvodac X Creator"), Expression("jIdProizvodac.[xCreator]")]
                public String IdProizvodacXCreator { get { return Fields.IdProizvodacXCreator[this]; } set { Fields.IdProizvodacXCreator[this] = value; } }
                public partial class RowFields { public StringField IdProizvodacXCreator; }

                        
                [DisplayName("Id Proizvodac X Datum Kreiranja"), Expression("jIdProizvodac.[xDatum_Kreiranja]")]
                public DateTime? IdProizvodacXDatumKreiranja { get { return Fields.IdProizvodacXDatumKreiranja[this]; } set { Fields.IdProizvodacXDatumKreiranja[this] = value; } }
                public partial class RowFields { public DateTimeField IdProizvodacXDatumKreiranja; }

                        
                [DisplayName("Id Proizvodac X Computor Creator"), Expression("jIdProizvodac.[xComputorCreator]")]
                public String IdProizvodacXComputorCreator { get { return Fields.IdProizvodacXComputorCreator[this]; } set { Fields.IdProizvodacXComputorCreator[this] = value; } }
                public partial class RowFields { public StringField IdProizvodacXComputorCreator; }

            
    #endregion Foreign Fields

    #region Id and Name fields
    IIdField IIdRow.IdField
    {
    get { return Fields.IdNadBrend; }
    }
        
            StringField INameRow.NameField
            {
            get { return Fields.Naziv; }
            }
            #endregion Id and Name fields

    #region Constructor
    public TNadBrendRow()
    : base(Fields)
    {
    }
    #endregion Constructor

    #region RowFields
    public static readonly RowFields Fields = new RowFields().Init();

    public partial class RowFields : RowFieldsBase
    {

            public RowFields()

    : base("[dbo].[tNadBrend]")
    {
    LocalTextPrefix = "Rsp.TNadBrend";
    }
    }
    #endregion RowFields
    }
    }

**Comment by volkanceylan** [comment]
Check that you have such a field, exact case, "not property name" in DB.
