### ISSUE TITLE
Report : How to show/Hide Column according to Query String or Login user

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#2701]
Hello,

I have 2 Questions, 

1) how we can show/hide search column according to user in report dialog? 
Same report accessed by different user and according to user login i want to show filters. 
like user1 want to see date, textbox and drop down in search, user2 only want drop down. 
so how we can do this? and In which file we can add this logic? 

2) want to download report in PDF so how we can add buttons in report?
please see attached image
![image](https://user-images.githubusercontent.com/31484362/31001121-fa1f9604-a4fe-11e7-9696-aa41790ac062.png)

Thanks

**Comment by rakeshpatil20** [comment]
can anyone help me to hide end date run-time?

**Comment by Estrusco** [comment]
You can use jQuery. In your dialog.ts 

```ts
this.form.yourField.element.hide();
```

or 

```ts
this.form.youtField.element.toggle();
```

**Comment by dfaruque** [comment]
try thsi https://github.com/dfaruque/Serenity.Extra#to-hide-a-field-in-a-dialog
