### ISSUE TITLE
ListHandler get front claim ID and do filter

### ISSUE THREAD

**Issue by dxh141130** [volkanceylan/Serenity#2702]
Hello,

I am new for Serenity, I want to open a claim(open) and there are several tabs show up, on the servicedetail tab, it load the whole list from database(about 200 thousands records, takes long time), how can i get the main tab id field when i open the form dialog, and send to the servicedetail repository list handler and then i can do override ApplyFilter method to SqlQuery filter in MyListHandler. That is what i think, when i click editlink, it will show form, but i do not know how to get value of form field "ID" and send to servicedetail tab before servicedetaill call mylisthandler.

**Comment by volkanceylan** [comment]
See how customer order grid lists orders for customer.
