### ISSUE TITLE
Fields side by side

### ISSUE THREAD

**Issue by grobberD** [volkanceylan/Serenity#2703]
Hello,

In the example of meeting dialog there are fields side by side (for instance start date and end date, or organized by and reporter). I didn't found any setting in the source code. 
How can I apply for my dialogs? 

Best regards, 
Torsten

![image](https://user-images.githubusercontent.com/31124491/30987462-5f69bbc4-a497-11e7-8d71-cc848760207d.png)

**Comment by Estrusco** [comment]
You can act on .less file
See example https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/MultiColumnResponsiveDialog (and site.basicsamples.less file), and search in prior issues. This question is post every month.

**Comment by grobberD** [comment]
Thank you Estrusco,
it works now. 
May be it is helpful for others, please see the examples.

Remark: The module has the name Tasks and the object the name ActionItem. 

content of file ActionItemIndex.CSHTML (folder ActionItem):
-------------------------------------------------------------------
@{
    ViewData["Title"] = Serenity.LocalText.Get("Db.Tasks.ActionItem.EntityPlural");
}

@section ContentHeader {
    <h1>@ViewData["Title"]<small></small></h1>
}

<div id="GridDiv"></div>

<script type="text/javascript">
    jQuery(function () {
        new Project1.Tasks.MultiColumnResponsiveGrid($('#GridDiv'), {}).init();

        Q.initFullHeightGridPage($('#GridDiv'));
    });
</script>

content of file MultiColumnResponsiveDialog.ts (folder ActionItem)
-------------------------------------------------------------------
/// <reference path="../../../Modules/Tasks/ActionItem/ActionItemDialog.ts" />
/// <reference path="multicolumnresponsivegrid.ts" />

namespace Project1.Tasks {

    @Serenity.Decorators.registerClass()
    export class MultiColumnResponsiveDialog extends Tasks.ActionItemDialog {

        constructor() {
            super();
        }
    }
}

content of file MultiColumnResponsiveGrid.ts (folder ActionItem
-------------------------------------------------------------------
/// <reference path="../../../Modules/Tasks/ActionItem/ActionItemGrid.ts" />

namespace Project1.Tasks {

    /**
     * Subclass of OrderGrid to override dialog type to MultiColumnResponsiveDialog
     */
    @Serenity.Decorators.registerClass()
    export class MultiColumnResponsiveGrid extends Tasks.ActionItemGrid {

        protected getDialogType() { return MultiColumnResponsiveDialog; }

        constructor(container: JQuery) {
            super(container);
        }
    }
}

I created this new file
content of file site.tasks.less (folder   ..\Content\Sites)
-------------------------------------------------------------------
@import "site.mixins.less";

.s-Tasks-MultiColumnResponsiveDialog {
    > .size { width: 850px; height: 550px; }
    .caption { width: 120px; }

    @media (min-width: 768px) {
         .field.StartDate, .field.EndDate {
            max-width: 50%;
        }
    }
}
