### ISSUE TITLE
Deleted records also shown on drop down menu

### ISSUE THREAD

**Issue by chintansoni54** [volkanceylan/Serenity#2707]
I implemented soft delete for some master table which is gone bind in drop down menu.

And while i am delete some record from master table then this record have Active = -1 

It will not shown into grid but it's shows into drop down.

So any solution to hide this record ???

**Comment by ademc** [comment]
Try this
`[LookupEditor(typeof(XyzRow), FilterField = "IsActive", FilterValue = 1)]`

**Comment by chintansoni54** [comment]
@ademc It's doesn't work are you sure we can hide deleted record with this?
