### ISSUE TITLE
3.0.5 returnUrl #edit/id

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2708]
Hi @volkanceylan!

Thank you very much for this feature!
but there is a bug, when you go to the link **..../Northwind/Product#edit/60**
If you are not authorized to delete part of the link **edit/60**

**Comment by volkanceylan** [comment]
Delete it from address bar.

**Comment by Zahar661** [comment]
@volkanceylan 
bad translate(
Serenity removes this part of the text. ReturnURL removes part of the url **edit/60**

**Comment by volkanceylan** [comment]
Hash part of URL is not sent to web server, so there is no way to restore that in returnURL

**Comment by Zahar661** [comment]
@volkanceylan  Thank you! I will use the panel.

**Comment by volkanceylan** [comment]
Think i've found a way to restore hash, see commit https://github.com/volkanceylan/Serene/commit/6ba982ab71f21132c1598b3c2b53d0abc7a307ad

**Comment by Zahar661** [comment]
Super! Working!
