### ISSUE TITLE
UndeleteResponse  &  RetrieveResponse

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#271]
Merhaba Volkan,

UndeleteResponse  &  RetrieveResponse  
Bir table için oluşturdu sergen, baska bir table için oluşturmadı. hangi duruma göre oluşuyor ? 

Selamlar.

**Comment by volkanceylan** [comment]
Retrieve hepsi için oluşur. Undelete IsActive varsa oluyordu sanırım.

**Comment by Olricz** [comment]
1.9.11 Sergen olusturmadı. IsActive var.

**Comment by volkanceylan** [comment]
Tabloda IsActive adlı bir alan varsa oluşur. Sonradan eklenen interface e bakmaz.

**Comment by volkanceylan** [comment]
Ya da Aktif

**Comment by Olricz** [comment]
Anladım. Ben IsActive sonradan eklemiştim. Sanırım ondan.

**Comment by volkanceylan** [comment]
RowGenerator.cs:

```cs
if (model.IsActiveField == null)
            {
                var fld = model.Fields.FirstOrDefault(
                    z => (z.Type == "Boolean" || z.Type == "Int16" || z.Type == "Int32") && (z.Ident == "Aktif" || z.Ident == "IsActive"));
                if (fld == null)
                    fld = model.RowBaseFields.FirstOrDefault(
                        z => (z.Type == "Boolean" || z.Type == "Int16" || z.Type == "Int32") && (z.Ident == "Aktif" || z.Ident == "IsActive"));

                if (fld != null)
                    model.IsActiveField = fld.Ident;
            }
```

**Comment by Olricz** [comment]
Şöyle bir durum var : 

Her tabloda asagıdaki fieldlar olacak. Bunu Sergen ile form olusturmadan once eklersem grid'de ve Yeni Kayıt Formunda bu alanlarda gorunuyor. Sonra eklersem de eksik olusuyor. IsActive'de oldugu gibi. Nasıl bir yol izlemek dogru olur ? 


```
 [InsertDate]          DATETIME      NOT NULL,
    [InsertUserId]        INT           NOT NULL,
    [UpdateDate]          DATETIME      NULL,
    [UpdateUserId]        INT           NULL,
    [DeleteDate]          DATETIME      NULL,
    [DeleteUserId]        INT           NULL,
    [IsActive]            SMALLINT      CONSTRAINT [DF_Sektorler_IsActive] DEFAULT ((1)) NOT NULL,
    [LastDirectoryUpdate] DATETIME      NULL,
    [TenantId]            INT           CONSTRAINT [DF_Sektorler_TenantId] DEFAULT ((1)) NOT NULL,
```

**Comment by volkanceylan** [comment]
CodeGenerator.config te BaseRowClasses diye bir opsiyon var, bunda olabilecek baz class lar ve bunların alan listesi mevcut (varsayılan olarak boş)

"BaseRowClasses": [ { "ClassName": "MyLoggingRow", Fields: ["InsertDate", "DeleteDate".....] }]

**Comment by Olricz** [comment]
Buraya ekledigimde, ekledigim alanları **olusturmuyor ** mu ?

**Comment by volkanceylan** [comment]
Yes

2016-02-18 22:59 GMT+02:00 Olricz <notifications@github.com>:

**Comment by Olricz** [comment]
Pardon Volkan. Sergen Crash oluyor. 
```
    "KDiff3Path": "C:\\Program Files\\KDiff3\\kdiff3.exe",
    "WebProjectFile": "..\\..\\..\\MultiTenancy\\MultiTenancy.Web\\MultiTenancy.Web.csproj",
    "ScriptProjectFile": "..\\..\\..\\MultiTenancy\\MultiTenancy.Script\\MultiTenancy.Script.csproj",
    "RootNamespace": "MultiTenancy",
    "BaseRowClasses": [ { "ClassName": "LoggingRow", Fields: ["InsertDate", InsertUserId","UpdateDate","UpdateUserId", "DeleteDate","DeleteUserId","IsActive","LastDirectoryUpdate","TenantId"] }],
    "RemoveForeignFields": []
```

**Comment by Olricz** [comment]
Tamamdır. Sagol.

**Comment by volkanceylan** [comment]
LastDirectoryUpdate neden var base row da onu anlamadım, bu sadece UserRow ve LDAP için lazım olan birşey

**Comment by Olricz** [comment]
Onu sildim. "Geri Al" ile veriyi geri aldıgımda DeleteDate ve DeleteUserId boşalmadıgından ikinci defa silinmiyor. Bu alanları boşaltma işini eklerim demiştin. Yapabildin mi ? Önemli oldu benim için.

**Comment by Olricz** [comment]
Merhaba Volkan, 
Commit etmişsin, gördüm. Yalnız Serenity'i build ederken şu hatayı aldım. 

![x](https://cloud.githubusercontent.com/assets/16984654/13170780/3ee24278-d6f7-11e5-889a-4f46a5eaeaed.JPG)

**Comment by volkanceylan** [comment]
TypeScript inizi güncelleyin ;)

**Comment by Olricz** [comment]
şimdi böyle :)
![x](https://cloud.githubusercontent.com/assets/16984654/13171746/1abae912-d6fd-11e5-85e8-d33cf0f7a72b.JPG)

**Comment by volkanceylan** [comment]
Değişen birşey yok sanki, bir restart mı lazım acaba 

1.9.12 de düzeldi zaten.

**Comment by Olricz** [comment]
eywallah. Kolay Gelsin.
