### ISSUE TITLE
Json Serialization Null Values

### ISSUE THREAD

**Issue by jonathan82** [volkanceylan/Serenity#2710]
Hi, I'm trying to get the Json serializer to include certain properties even if they are null (default is to not include). I added this attribute to the properties in my row file:

`JsonProperty(NullValueHandling=NullValueHandling.Include)`

but it doesn't seem to do anything.  Any  ideas how I can achieve this?

**Comment by kilroyFR** [comment]
Not directly linked with Serenity Framework. I guess you checked stackoverflow already.

**Comment by jonathan82** [comment]
Ok so this what I found out.  Serenity implements its own Json row converter and doesn't look at this attribute.  I needed certain fields to be serialized even when null since I'm using Vue, and Vue requires object properties to be present to make them reactive.  My workaround was just to initialize these properties in Javascript if they weren't present before.
