### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by basselz** [volkanceylan/Serenity#2714]
Hi @volkanceylan 
how can I Enable CORS for EndPoint Methods 
I have an EndPoint Method which doesn't require Authorization,
but I can't add Attribute for Enabling CORS to it to be able to send requests from javascript
like : 
    var xhttp = new XMLHttpRequest();
    xhttp.open("POST", "http://......", false);
    xhttp.send(leads);

**Comment by ademc** [comment]
This is not Serenity issue, it is about asp.net. 

Try this: https://docs.microsoft.com/en-us/aspnet/core/security/cors

**Comment by basselz** [comment]
Dear @ademc 
it is when u try to call EndPoint method from another domain, 
I don't think the solution you've sent me is working with Serenity
 but thanks for the answer

**Comment by ademc** [comment]
Are try trying to call another web site's api/service/url method? If is it your web site you have to disable CORS from web.config file. Again i have to say it is not related Serenity.

May be you can try jsonp method like this:

`
$.ajax({
          url: "https://...com/api/v2/users/all.json",
          type: 'GET',
          dataType: 'jsonp',
          cors: true ,
          contentType:'application/json',
          secure: true,
                    headers: {
                        'Access-Control-Allow-Origin': '*',
                    },
          beforeSend: function (xhr) {
              xhr.setRequestHeader ("Authorization", "Basic " + btoa(""));
          },
          success: function (data){
            console.log(data);
          }
      })
`

**Comment by basselz** [comment]
Sir
I don't think u understand my question to @volkanceylan ,
I've done all you're suggesting and more, 
the issue is that pace.js is intercepting the ajax call - Same even if I used Q.ServiceCall - 
and if the source is from another domain it will block it,
and I would like to ask Volkan if there's is anyway to Enable CORS for Serenity EndPoint Methods, or to allow cross domain requests ,

so Thanks again for your answer, I really appreciate it, but your solution is not working

**Comment by volkanceylan** [comment]
You may enable CORS by looking at ASP.NET docs. Serenity has no special treatment to CORS.

**Comment by samdubey** [comment]
See wiki for How to enable cors for serenity applications
https://github.com/volkanceylan/Serenity/wiki/Enable-Cors-For-Serenity-Applications

**Comment by juliermefelix** [comment]
@samdubey 
where do i put the code for this wiki?
