### ISSUE TITLE
Filter LookupEditor

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#2715]
Good Day

I want to know if there is a way control what gets (list items) displayed on the lookup, what I mean is for instance instead of displaying all the states/provinces determine which ones gets shown. Will this be possible to achieve perhaps if using the PrepareQuery method in the LookupEditor?

protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);
      if (!Authorization.HasPermission(PermissionKeys.Companies))
                        query.Where(fld.CompanyId == user.CompanyID);

            }

**Comment by Estrusco** [comment]
If you want to filter data in server side, you can use the override of PrepareQuery(SqlQuery query). I think don't understand exatly what you want.

**Comment by fremar83** [comment]
I think you are talking about that 

`  protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Entities.OaRow.Fields;
            query.Select(fld.TitreOa)
                .Where(
                    new Criteria(fld.TitreOa) != "" &
                    new Criteria(fld.TitreOa).IsNotNull());
        }`

**Comment by wirble** [comment]
You should be able to use the built in decorator?  When you specify lookupeditor, you can also add filter value and filter by column. I forgot the exact name but if you put in filter the intellisense should pop up. Its in tje samples also....

**Comment by stixoffire** [comment]
@sshandu I know your question is old but for the sake of others coming here looking for answers.

[LookupEditor(typeof(CompanyRow), FilterField = "InActive", FilterValue = false)]

Is one way to filter - you can modify the filter value and use reloadLookup()  from the client side.
