### ISSUE TITLE
Inplaceadd difficulties with custom filter lookup form

### ISSUE THREAD

**Issue by alexneocart** [volkanceylan/Serenity#2716]
In the form have a search with custom filter, what happens is that the inplaceadd does not work and I get the msg "** PessoasLookupDialog dialog class not found. "** Follow code

Segue código

Add in lookupEditor --> DialogType = "PessoasLookup") e create o PessoasLookupDialog 
 
[DisplayName("Funcionário"), ForeignKey(typeof(PessoasRow)), LeftJoin("jPessoa")]
[LookupEditor(typeof(PessoasLookup), **InplaceAdd = true, DialogType = "PessoasLookup"**)]

*****************PessoasLookupDialog **********************
namespace NeoAdm.Vendas{
    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class PessoasLookupDialog extends Serenity.EntityDialog<PessoasRow, any> {
        protected getFormKey() { return PessoasForm.formKey; }
        protected getIdProperty() { return PessoasRow.idProperty; }
        protected getLocalTextPrefix() { return PessoasRow.localTextPrefix; }
        protected getNameProperty() { return PessoasRow.nameProperty; }
        protected getService() { return PessoasService.baseUrl; }

        protected form: PessoasForm;

        constructor(container: JQuery) {
            super(container);

            this.form = new PessoasForm(this.idPrefix);
            //Oculta/mostra os campos de Pessoa (Fisica/Juridica)
            function CarregaTipoPessoa(): void {
                this.alteraTipoPessoa(this.form);
            }

            //Evento change de Tipo de Pessoa
            this.form.TipoPessoa.change(e => {
                this.alteraTipoPessoa(this.form);
            });

            this.form.Cpf.addValidationRule(this.uniqueName, e => {
                var cpf: string;
                cpf = this.form.Cpf.value;
                if (cpf != null) {
                    if (PessoasEditor.validaCpf(cpf) == true)
                        return null;
                    else
                        return "erro";
                }
                else
                    return "erro";
            });
        }

        private alteraTipoPessoa(f: PessoasForm): void {
            var visible: boolean;
            //Física
            if (f.TipoPessoa.value == NeoAdm.Modules.Vendas.Pessoas.EnumTipoPessoa.Física.toLocaleString()) {
                visible = true;
                //Jurídica
            } else if (f.TipoPessoa.value == NeoAdm.Modules.Vendas.Pessoas.EnumTipoPessoa.Jurídica.toLocaleString()) {
                visible = false
            }

            f.Cpf.getGridField().toggle(visible);
            f.DataNascimento.getGridField().toggle(visible);
            f.Rg.getGridField().toggle(visible);
            f.Sexo.getGridField().toggle(visible);
            f.Cnpj.getGridField().toggle(!visible);
            f.RazaoSocial.getGridField().toggle(!visible);
            f.InscEstadual.getGridField().toggle(!visible);
            f.InscMunicipal.getGridField().toggle(!visible);
            f.DataFundacao.getGridField().toggle(!visible);
            f.TipoImposto.getGridField().toggle(!visible);
        }
    }
}

      

![erroinplace](https://user-images.githubusercontent.com/28063632/31094950-53e79f70-a78d-11e7-8c30-10819eb7ec4a.jpg)

**Comment by rolembergfilho** [comment]
ps: você fez sua validação de CPF em typescript ou javascript? teria como compartilhar?

**Comment by alexneocart** [comment]
@rolembergfilho  sou de João Pessoa - Pb 
O código em cpf mas é em javascript,  alterei para realidade do Serenity e está funcionando
PessoasEditor
 //Validação CPF
        static validaCpf(cpf) {
            if (cpf == '')
                return false;
            // Elimina CPFs invalidos conhecidos    
            if (cpf.length != 11 ||
                cpf == "00000000000" ||
                cpf == "11111111111" ||
                cpf == "22222222222" ||
                cpf == "33333333333" ||
                cpf == "44444444444" ||
                cpf == "55555555555" ||
                cpf == "66666666666" ||
                cpf == "77777777777" ||
                cpf == "88888888888" ||
                cpf == "99999999999")
                return false;
            // Valida 1o digito 
            var add = 0;
            for (var i = 1; i < 9; i++)
                add += parseInt(cpf.charAt(i)) * (10 - i);
            var rev = 11 - (add % 11);
            if (rev == 10 || rev == 11)
                rev = 0;
            if (rev != parseInt(cpf.charAt(9)))
                return false;
            // Valida 2o digito 
            add = 0;
            for (var i = 0; i < 10; i++)
                add += parseInt(cpf.charAt(i)) * (11 - i);
            rev = 11 - (add % 11);
            if (rev == 10 || rev == 11)
                rev = 0;
            if (rev != parseInt(cpf.charAt(10)))
                return false;
            return true;
        }

**Comment by rolembergfilho** [comment]
Show de bola
Sou de Vitória-ES.

conseguiu resolver o problema do LookupScript?

uma dica: execute o sergen e gere os scripts das duas tabelas em um outro projeto e veja se funciona.

**Comment by alexdaywid** [comment]
@rolembergfilho não consegui, nao sei se você entendeu meu problema com lookup. Eu tenho pessoas do tipico física e juridica então crie um arquivo chamado pessoaLookup com um consulta, para me retorna nesse lookup só as pessoas do tipo pessoa física porem o problema é que ao clicar no botão para editar está abrindo o dialog para poder editar o cadastro de pessoas.

**Comment by rolembergfilho** [comment]
Realmente ficou bem vaga sua descrição em inglês, RS...

No seu caso, favor olhar o populate linked data no demo:

http://serenity.is/demo/BasicSamples/PopulateLinkedData



Em 6 de out de 2017 20:01, "alexdaywid" <notifications@github.com> escreveu:

**Comment by alexneocart** [comment]
Resolvido  o dialogtype estava incorreto apos realizar a alteração DialogType= "Vendas.PessoasLookup" funcionou.
 [LookupEditor(typeof(PessoasLookup),InplaceAdd =true, DialogType= "Vendas.PessoasLookup")]
