### ISSUE TITLE
Frozen column not works properly

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#2717]
Hi,

In this issue about frozen column and mentioned that frozenColumn option works. 

When i try this code

`    constructor(container: JQuery) {
                super(container);
                this.slickGrid.setOptions({ frozenColumn: 3 });
            }`

i see this result:
![image](https://user-images.githubusercontent.com/3390438/31097410-e46006d4-a7c7-11e7-8b14-c973567dc4dc.png)

What am i doing wrong? Thanks

**Comment by receptuna** [comment]
try this

```
        constructor(container: JQuery) {
            super(container);
        }

        **protected getSlickOptions() {
            let opt = super.getSlickOptions();
            opt.frozenColumn = 2;
            return opt;
        }**
```

**Comment by ademc** [comment]
I already tried. Same result :(

**Comment by volkanceylan** [comment]
Frozen column controls index of left frozen columns, so it is working as it should in your sample. Use 1 for example, use a large number of visible columns and see that one/two column is scroll locked to left.
