### ISSUE TITLE
Installing Serenity Template

### ISSUE THREAD

**Issue by kuradaganesh** [volkanceylan/Serenity#2718]
Hi volkanceylan,

I downloaded  Serene Volkan Ceylan template from marketplace.visualstudio.com and then after install in with out internet computer.so many exceptions and 1 error is occured  like
1.an error occured while installing package:bootstrap your project might be incomplete.
2.an error occured while installing package:dapper your project might be incomplete.
3.an error occured while installing package:serenity.data your project might be incomplete.
4.an error occured while installing package:serenity.codegerator your project might be incomplete.
5.an error occured while installing package:serenity.services your project might be incomplete.......etc
error:the command cmd/c npm exited with code 1

So I would like to know if it is possible or not with out internet?

regards,
K.Ganesh

**Comment by volkanceylan** [comment]
Nope, internet required on project creation

**Comment by kuradaganesh** [comment]
my work is in internet restricted area what i will do any suggestion?

**Comment by rolembergfilho** [comment]
Hi @kuradaganesh ,

I did it in the beginning of Serenity studies.

I've created a default Serene project solution in my notebook, and download nugets, builded, tested, deployed to iis and all...

Afer I get a fully fucntional Serene project (from Serene Template), I copied all folder and files (i mean folder with .sln, project's folder and **nuget packages** folder.

It's works for me since June/2016

**Comment by kuradaganesh** [comment]
Hey Thanks for your answer

**Comment by rolembergfilho** [comment]
PS: don't forget to read install Guide. You need typescript and node.js

Em 5 de out de 2017 22:16, "kuradaganesh" <notifications@github.com>
escreveu:

**Comment by kuradaganesh** [comment]
I created Serenity project solution in my internet computer and it is working properly then after copied to intranet pc and also installing node.js,Type Script and adding all references like serenity.core,serenity.data,csquery,dapper,epplus,fluentmigrater........etc. 
the following error is raised
1.command cmd/c npm install exited with code 1
2.i am not founding Tools-->Options-->Projects and Solutions-->External Web Tools in visual studio 2013
