### ISSUE TITLE
choose columns returned with LookupScript

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#2719]
Hi, 
I have tables Books and Comity. I need to be returned from LookupScript the title of the book in the comityRow (a comity reads a book). How can I select witch columns will be returned ? 
At the moment, it returns  le codeBook and the refBook (1st string in my table, i guess).
I need nameBook an not refBook.
![image](https://user-images.githubusercontent.com/28645113/31121761-ca18e274-a839-11e7-96a4-850f07a01c17.png)

**Comment by fremar83** [comment]
I'm sorry (again). I had the answer in the CustomerLookup class of the demo solution.
We just have to create it
I'll check harder next time.

Cheers

**Comment by fremar83** [comment]
It seems that the CustomerLookup class PrepareQuery void had to be overrided
Could someone confirm that's the right way to choose the returned column ?

namespace OragNetAdmin.Oragnet.Scripts
{
    using Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("OragNet.OA")]
    public class OaTitreLookup : RowLookupScript<OaRow>
    {
        public OaTitreLookup()
        {
            IdField = OaRow.Fields.CodeOa.PropertyName;
            TextField = OaRow.Fields.TitreOa.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Entities.OaRow.Fields;
            query.Select(fld.TitreOa)
                .Where(
                    new Criteria(fld.TitreOa) != "" &
                    new Criteria(fld.TitreOa).IsNotNull());
        }
    }
}

**Comment by marcobisio** [comment]
Just add "LookupInclude" attribute to the property that you want to include in the lookup (do it in your xyzRow.cs). For performance reasons, lookups by default only include the id field and the name field of your entity.

Bye

**Comment by fremar83** [comment]
I did that but when I try to change TextualField to titreOA it has no effect on the result : I get the refOA in the Select when I try do associate a book (OA) to a new comite.

**Comment by fremar83** [comment]
I got it! TextualField as nothing to do here. I did not change RefOA in TitreOA in NameField in the ComitesRow.
 StringField INameRow.NameField
        {
            get { return Fields.**TitreOa**; }
        }
Thanks!!
