### ISSUE TITLE
Is there anyway to create only form field?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#272]
I want to add some fields to form to edit some values for only show on form. But I dont want to add to Row event ClientSide attribute. I want to take advantage property grid and its editors of serenity?

I have a lot of field to show on form because of this i want to put fields on Form.cs only. When I want to save from throws serialization exception.

**Comment by volkanceylan** [comment]
You may add [OneWay] attribute to such fields. They don't get serialized.

**Comment by volkanceylan** [comment]
I mean in Form.cs

**Comment by ademc** [comment]
This framework likes batmobile :+1:  Thanks Bruce...oh sorry Volkan of course :)
