### ISSUE TITLE
Custom Table in Form

### ISSUE THREAD

**Issue by Gone4Coding** [volkanceylan/Serenity#2720]
Hi everyone :)

I'm new to Serenity and there're things I'm not capable of doing. And that thing is a custom table in a form.

I don´t mean create a new Entity and call the Grid onto that form. I want to rearrange my form fields into a table like you do with 'td' and 'tr' in HTML. 

I've already tried with the CSS related to the form and my major problem was it wasn't responsive. 
I can't find anything similar, so if anyone could give me a hand it would a huge help.

Thanks to everyone in advance!! :)

**Comment by Gone4Coding** [comment]
@javaman63 
Hey. Thanks for your answear.

I've already tried that but it's really difficult to achieve a good looking and responsive table..
Is it possible to manipulate the .less file with HTML? I mean, use the normal 'td' and 'tr' in that file to manipulate the fields?
I don't know if it's possible and I've already searched for it but I only get results where the solution includes HTML.
If it's not possible to manipulate the .less file, another solution would be to create a custom template to support the form and create it the way I want it to be?

Thanks!! :)

**Comment by javaman63** [comment]
Take a look to the following example:
[serenity.is/demo/BasicSamples/StaticTextBlock](url)

maybe This example can help you

**Comment by Gone4Coding** [comment]
I already tried to use that. It didn't worked well.
But thanks for the example

**Comment by brunobola** [comment]
PLease specify what youive tried so far for others to assist you on what you really wan't your design to look to and the code you've done.

**Comment by Gone4Coding** [comment]
To be more clear, this is what I have:
![capture](https://user-images.githubusercontent.com/18728780/31517553-361effb0-af94-11e7-9781-251420be33f6.PNG)

... and this is what I need:
![capture2](https://user-images.githubusercontent.com/18728780/31517568-4102b4d0-af94-11e7-86e7-2d9977baa46a.PNG)

**Comment by javaman63** [comment]
Try with something like this on your site.less

 
`

.s-your-XYZDialog {
    > .size { width: 1024px; height: 743px; }
    .caption { width: 110px; }
      @media (min-width: 300px) {
			.field.YourField1,
			.field.YourField2,
			.field.YourField3,
			.field.YourField4,
			.field.YourField5,
			.field.YourField6,
			.field.YourField7,
			.field.YourField8,
			.field.YourField9,

		  {
		     flex: auto;
		     min-width: 33%;
		  }
      }

}

`

**Comment by brunobola** [comment]
I've tryed to achieve your layout but without success, @volkanceylan does serenity override some behaviour using Less ?

I tried this https://css-tricks.com/responsive-data-tables/ and it didn't work as expected.

**Comment by volkanceylan** [comment]
You may use [OneThirdWidth] in latest version.
