### ISSUE TITLE
when the user clicks on grid row that particular values should be populated in pop-up

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#2724]
As the application starts one pop-up(parent pop-up) will appear on the webpage and it consists of buttons,textboxes etc.
and when the user clicked on the button another pop-up(child pop-up) will appear on the screen and this pop-up consists of grid and some textboxes,buttons etc.
My requirement:-is when the user clicked on grid-row that particular row data should be shown in the textboxes of first(previous or parent pop-up) how we can bind that??

**Comment by Estrusco** [comment]
I think you can use, as starting point, the BasicSamples/CustomLinksInGrid sample. 
To se data in current dialog, you can use Serenity.EditorUtils.setValue() method

**Comment by flextrio-gandhi** [comment]
yes  it is working on  grids which are placed on main page,but
my grid is not populated on the main page but it is populated on one dialog box.
