### ISSUE TITLE
Combining more then one column and displaying as one column on the pop-up(dialog) grid

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#2725]
Pop-up(dialog) consists of grid with several columns How to concat the 2 or more columns as one column   and display on the grid??
   but here we are using this code [Expression("CONCAT(T0.[column1], CONCAT(' /', T0.[column2]))")] but it is         working on main grid like without pop-up(dialog), but not working on  grid which were present in 
poup-up(dialog)

**Comment by rolembergfilho** [comment]
could you post an image of problem?

**Comment by flextrio-gandhi** [comment]
![image](https://user-images.githubusercontent.com/28822452/31307295-f5977684-ab7e-11e7-8d43-7b5c478fbcff.png)

**Comment by javaman63** [comment]
Take a look to the "Declaring FullName Field" on the manual

[https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/the_cast_and_characters_they_played.html](url)

**Comment by JohnRanger** [comment]
@javaman63 

Above link does not work.

Can you provide a workng link?

Thanks and with Kind regards,

John

**Comment by javaman63** [comment]
i dont know why isnt work. May be you can take a look on the PDF Serenity Manual
