### ISSUE TITLE
Assigning String[] to Lookupeditor

### ISSUE THREAD

**Issue by cvenkatr** [volkanceylan/Serenity#2726]
Hi,
  When i am trying to assigning string[] type values which is getting from api response to Lookupeditor. I am getting exception like "Type string[] is not assignable to type Lookupeditor".
Could you please give the solution for this.

**Comment by marcobisio** [comment]
HI @cvenkatr,
did you set the multiple attribute to true in your lookup editor? Moreover are you using the ".values" property?
