### ISSUE TITLE
page height not adjusting well

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2730]
I have included a third party component in my project. When I run it displays well but the height is not adjusted 100%. I tried to change the height of parent container but was not able to find. 
![image](https://user-images.githubusercontent.com/20435849/31232956-8a7daff0-aa00-11e7-8c10-6e4ef2e0123d.png)

Any hint is appreciated .

**Comment by kilroyFR** [comment]
What is this third party component so we can try reproduce problem ?

**Comment by ms4hafiz** [comment]
The third party is .net component. It is syncfusion dashboard platform.  The link is here. https://help.syncfusion.com/dashboard-platform/dashboard-sdk/getting-started/aspnet-mvc

**Comment by volkanceylan** [comment]
Sorry but can't help you without seeing component / css
