### ISSUE TITLE
DateEditor via script, validation not working

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2731]
Hi all!

If I add a DateEditor via script in an html page, the validation for date not working. I have the calendar and all functionality, but if I set a non valid date, the validation don't work.

Any idea?

```html
[...]
<input type="text" class="editor flexify" id="elementID" name="elementName">
[...]
<script type="text/javascript">
    $().ready(function () {
        new Serenity.DateEditor($("#elementID");
    });
</script>
```

**Comment by brunobola** [comment]
Maybe mixed jquery versions in app ?

**Comment by Estrusco** [comment]
No, I have normal jQuery version that are in Serene.

@volkanceylan  can you help me please?

**Comment by MichaelQuint** [comment]
Hello, I have the same issue. The code below does successfully create the datepicker, but does not validate like the datepickers on dialogs. Any ideas why?

`new Serenity.DateEditor($('#div'));`
