### ISSUE TITLE
How to deactivate logo in sidebar from rotating

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2733]
Hi all,

as I don't like unneccessary animations in applications (they distract from productive work) I want to stop the application logo in the sidebar from rotating.

I have already searched many .less files and css files and also reverse-engineered the _Layout.cshtml but I simply don't find where the rotating Action/style is defined.

I can remove the logo entirely out of  the app - no Problem - but I like the logo but want to stop it from rotating.

I don't see this in the less file, where the logo and logo-mini classes are defined.

Also I didn't find anything about this in the current Serenity guide.

Any hint is greatly appreciated.

Thanks and with Kind regards,

John

**Comment by wldkrd1** [comment]
From Site.css:


.main-header .logo i {
  width: 50px;
  height: 50px;
  float: left;
  background: url(images/serenity-logo-w-40.png) no-repeat center center;
  **animation: fa-spin 5s infinite linear reverse;**
}

**Comment by JohnRanger** [comment]
Thanks wldkrd1,

your hint brought me to find the correct place.

**Here for reference the full solution (in case someone Needs this):**

Actually, the Change must not be made within site.css directly but within **site.theme.less** because site.css is everytime overwritten by the less Compiler when rebuilding the solution.

--> In the end of Course, the Change is reflected within site.css.

Thanks again and

with Kind regards,

John

**Comment by JohnRanger** [comment]
A note for myself: As of SF 3.9.14, this has been moved to site.default.less
