### ISSUE TITLE
Getting value of a QuickFilter

### ISSUE THREAD

**Issue by grobberD** [volkanceylan/Serenity#2735]
Hello,
I would like to set a default value for a new item in a grid, depending on a value of a QuickFilter. I don't know exactly how to make this. To explain my need I prepared a code excerpt. Please see below. 
Can anybody give me a hint what I had to add to set the value filter. Thank you in advance. 
...
XYZGrid.ts: 
private pprojectId: number;
protected addButtonClick() {
   let this.pprojectid = number;
   let filters = super.getQuickFilters();
   let filter = Q.first(filters, x => x.field == "ProjectId");
   this.projectId =  //... missing code to get value of the filter.  
   this.editItem(<Tasks.ActionItemRow>{
      ProjectId: this.pprojectId
   });
}

**Comment by javaman63** [comment]
Take a look to this example in Serene or in your defualt template

http://serenity.is/demo/Northwind/Order?shippingState=0

**Comment by grobberD** [comment]
Thank you @javaman63 
That is not for what I'm searching (but I can need it for other requirements). 
I'm searching for following example: In the order grid the customer "Berglunds snabbköb [BERGS]" is selected in the QuickFilter "Customer". If the user creates now an order, this customer should be the default value for the customer field in the new order form. 

I know how to get filter object, but I didn't found the possibility to get the value of that field (see code excerpt).

**Comment by javaman63** [comment]
Can you send me the link of what grid are you seeing?

**Comment by grobberD** [comment]
That I see: 

![image](https://user-images.githubusercontent.com/31124491/31318821-7063a7d2-ac58-11e7-9d29-7c727c429d17.png)

**Comment by javaman63** [comment]
When in the example (serenti.is/demo) you select a customer and you click "new order" the customer is no automatic prefilled in that example, is that what you want to get?

**Comment by grobberD** [comment]
Wished Szenario:
The user selects a customer "Berglunds snabbköb [BERGS]". Than he press the button "Order anlegen" (create order). In the form for the order the customer "Berglunds snabbköb [BERGS]" is prefilled. 

![image](https://user-images.githubusercontent.com/31124491/31348942-7d252c10-ad21-11e7-8e1f-e5479ab4c7b1.png)

I hope that this is possible.

**Comment by volkanceylan** [comment]
protected addButtonClick() {
            var eq = this.view.params.EqualityFilter;
            this.editItem(<OrderRow>{
                CustomerID: eq ? eq.CustomerID : null
            });
        }

**Comment by vinaykulkarni89** [comment]
@volkanceylan 
How can I get the value of Date Range?

**Comment by vinaykulkarni89** [comment]
Ya found in params.Criteria
