### ISSUE TITLE
How to refresh my grid after insert/update a row 

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2736]
I am using the following code which works fine. but the only issue i am having is its not refreshing the grid after insert/update. can you please help ? 

           protected getButtons() {
            var buttons = [];
            
            buttons.push(Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));

            
            buttons = [  {
                title: 'Clock In',
                cssClass: 'send-button',
                
                onClick: ()  => {

                    UserClockInOutService.ClockInUser();

                   
                    
                }

            }

                , {
                title: 'Clock Out',
                cssClass: 'send-button',
             
                onClick: () => {

                    UserClockInOutService.ClockOutUser();
                   
                    
                }
                

            }

            ];

            //if (!UserClockInOutService.isClockedIn())
            //    buttons = buttons.slice(0);
            //else
            //    buttons = buttons.slice(1);

            return buttons;
        }

**Comment by wirble** [comment]
Look in the basic samples with the default values button. I think its initdialog. There is a comment to the effects....

**Comment by ManzoorPK** [comment]
how can i access a variable value from endpoint in .ts file?

**Comment by Estrusco** [comment]
if you are in grid.ts

this.refresh();
this.element.triggerHandler('layout');

if you are in dialog.ts 

this.yourGridEditor.refresh();
this.yourGridEditor.element.triggerHandler('layout');

See https://github.com/volkanceylan/Serenity/issues/1962 and https://github.com/volkanceylan/Serenity/issues/1959

**Comment by ManzoorPK** [comment]
i am in grid.ts and i implemented like
                 onClick: () => {
                        
                        UserClockInOutService.ClockInUser();
                        this.refresh();
                        this.element.triggerHandler('layout');
                    }

BUT not working

**Comment by ManzoorPK** [comment]
Nevermind i fixed it

**Comment by kilroyFR** [comment]
Any chance you can share your solution so that it can help others ?
