### ISSUE TITLE
xyzDialog.ts; trigger save new record programmatically (like when clicking on save button)

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2738]
Dear all,

as I am in Progress of writing a small file sharing solution with Serenity, I want the creation of the filename for a file-to-be-uploaded to be securely generated. This means, it has to be generated on server-side so it can be verified at upload time. 

As I Need the filename before the file actually gets uploaded and I generate the unique storage filename in the BeforeSave-Event, I want the "new Dialog" to immediately save the first time when it opens. 

**Workarround:**
At the Moment, I solve this with calling: ```this.applyChangesButton.click();```

**Problem:**
This causes a toast to Show up which says: Successfully saved.

**Desired Outcome:**
What I want is actually calling the same function programmatically which the applyChanges button also calls - but without the toast to appear.

I have looked into calling: ```xyzService.Create();``` but I don't get how to parameterize this in order to work as desired.

Any help is greatly appreciated.

With Kind regards,

John

**Comment by JohnRanger** [comment]
To answer my own question for reference:

```ts
this.save((response: Serenity.SaveResponse) => {  //*** if you Need, do something here after save - otherwise leave empty *** 
} );
```

With Kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger that solves the in memory grid save issue where you want to save when you add an item. I subscribe to the in memory list changed event .. run this and it works great!
