### ISSUE TITLE
Getting error about IsActiveProperty after Transforming template

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#274]
sergen Generate code by putting [IsActiveProperty(xxxRow.IsActiveProperty)] on top  of my dialogs.
That is fine and it was working.

But after transform t4 template compiler catch error all of dialogs that has this attribute.

Please help.

**Comment by volkanceylan** [comment]
Does your row has IIsActiveRow interface

**Comment by dfaruque** [comment]
Oho. Thank you.

**Comment by swordz36** [comment]
You have to update the Serenity.Script.Ui.js (line 9255)
