### ISSUE TITLE
how to Get EndPoint Return value in grid.ts file

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2740]
Hello Friend. i have a function in serviceendpoint like ,

        public bool isClockedIn()
        {
            return new ClockInOut().isClockedIn();
        }

Which returns true, false. i want to use this returned value in my grids.ts and want to show/hide button 
i am using like this in .ts files

                  namespace Payroll.Default {
    export namespace UserClockInOutService {
        export const baseUrl = 'Default/UserClockInOut';

        export declare function isClockedIn(): boolean;

        export namespace Methods {

            export declare const isClockedIn: boolean;
        }

        ['Create', 'Update', 'Delete', 'Retrieve', 'List', 'ClockInUser', 'ClockOutUser','isClockedIn'].forEach(x => {
            (<any>UserClockInOutService)[x] = function (r, s, o) { return Q.serviceRequest(baseUrl + '/' + x, r, s, o); };
            (<any>Methods)[x] = baseUrl + '/' + x;
        });
    }
}

And using this service like 

       if (UserClockInOutService.isClockedIn())
                    buttons = buttons.slice(0);
                else
                    buttons = buttons.slice(1);

            return buttons;

BUT NOT WORKING. i am always getting UserClockInOutService.isClockedIn() as object Object. how can i call and get the returned value here in grid.ts ????

**Comment by Estrusco** [comment]
```ts
UserClockInOutService.isClockedIn(
    {
    },
    response =>
    {
        if (response === true)
            buttons = buttons.slice(0);
        else
            buttons = buttons.slice(1);
    }
);
```

**Comment by ManzoorPK** [comment]
thank you for your reply friend, but now i am getting this error
http://prntscr.com/gv26qo

**Comment by ManzoorPK** [comment]
i tried it like this
   UserClockInOutService.isClockedIn()
                {
                    response => {
                        alert(response);
                        if (response === true)
                            buttons = buttons.slice(0);
                        else
                            buttons = buttons.slice(1);
                    }
                };

**Comment by Estrusco** [comment]
You have to define isClockedIn in your endpoint in this way.

Define a model with response:

```cs
    public class ClockedInResponse : ServiceResponse
    {
        public bool IsClocked { get; set; }
    }
```

```cs
public ClockedInResponse IsClockedIn(ServiceRequest request)
{
    [...] your code

   return new ClockedInResponse() { IsClocked = [true or false] };
}
```

Compile, transform T4 and then use in .ts with 

```ts
UserClockInOutService.IsClockedIn(
    {
    },
    response =>
    {
        if (response.IsClocked)
            buttons = buttons.slice(0);
        else
            buttons = buttons.slice(1);
    }
);
```

**Comment by ManzoorPK** [comment]
Under UserClockInOutServer.ts i am having isClockedIn like

        export declare function isClockedIn(): JQueryXHR;
       export namespace Methods {
            
            export declare const isClockedIn: string;
        }

**Comment by ManzoorPK** [comment]
Keep in mind i am using grid.ts not dailog.ts

**Comment by Estrusco** [comment]
No, if you have declared in endpoint this method

```cs
public ClockedInResponse IsClockedIn(ServiceRequest request)
{
```

you must have, after T4

```ts
        export declare function IsClockedIn(request: Serenity.ServiceRequest, onSuccess?: (response: ClockedInResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
```

**Comment by ManzoorPK** [comment]
sorry i am new how to convert to T4?

**Comment by ManzoorPK** [comment]
I rebuild the solution and these things not comming.

**Comment by Estrusco** [comment]
In visual studio, Build -> Transform all T4 template

**Comment by ManzoorPK** [comment]
Thank you friend its working fine, but now i have one problem both of the buttons still showing none of them hiding. can you take a look? 

   protected getButtons() {
            var buttons = [];

            buttons.push(Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));

          




            buttons = [{
                title: 'Clock In',
                cssClass: 'send-button',

                onClick: () => {

                    UserClockInOutService.ClockInUser(
                        {},
                    );
                    this.refresh();
                    this.element.triggerHandler('layout');
                }



            }

                , {
                title: 'Clock Out',
                cssClass: 'send-button',

                onClick: () => {

                    UserClockInOutService.ClockOutUser(
                        {},
                    );
                    this.refresh();
                    this.element.triggerHandler('layout');

                }

            }



            ];


            
            UserClockInOutService.IsClockedIn(
                {
                },
                response => {
                    if (response.IsClocked) {

                        buttons = buttons.slice(1);
                    }

                    else {

                        buttons = buttons.slice(0);
                    }
                }
            );


            return buttons;
        }

**Comment by Estrusco** [comment]
The getButtons function is called only at start of dialog. I think you can hide or show button using element.show() or element.hide() - where element is button.

**Comment by ManzoorPK** [comment]
OK now i have a store procedure with join in it. How can i show the other columns in grid.ts ?????

**Comment by JohnRanger** [comment]
@ManzoorPK : This is a completely unrelated question to your initial issue. Please Close this issue and open a new issue for your new Thema.

So other People can more easilier Profit from your new issue.

Thanks and

with Kind regards,

John
