### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by Tripex48** [volkanceylan/Serenity#2741]
I am looking to implement soft delete on separate two entities.

Having added an IsActive flag in the database tables for the entities, I need some assistance as to how to set this flag during the delete process.

I think that MyDeleteHandler in the repository classes needs to be changed, but I have no idea as to what code is required.

Any assistance will be greatly appreciated.

**Comment by wirble** [comment]
I am not sure what you mean by separate two entities, but here is the builtin Serenity way of doing it.


     public sealed class MydataxxxxRow : Row, IIdRow, INameRow, IIsActiveDeletedRow,IIsActiveRow
        {

    [NotNull, Insertable(false), Updatable(true), DefaultValue(1), Hidden,IntegerEditor(MinValue 
    =-1,MaxValue =1)]
        public Int16? IsActive
        {
            get { return Fields.IsActive[this]; }
            set { Fields.IsActive[this] = value; }
        }

        Int16Field IIsActiveRow.IsActiveField
        {
            get { return Fields.IsActive; }
        }

    }

Endpoint file should have:
```
[HttpPost, AuthorizeDelete(typeof(MyRow))]
public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request)
{
	return new MyRepository().Undelete(uow, request);
}

```
repository file should have:

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }
        public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request)
        {
            return new MyUndeleteHandler().Process(uow, request);
        }
    private class MyUndeleteHandler : UndeleteRequestHandler<MyRow> { }
    private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }

**Comment by Tripex48** [comment]
Thank you for the prompt response. It addresses my exact needs.

I meant that I have two different MydataxxxRow classes, which each would
require the attributes that you shared in the response.

Regards,
Jacques Coertze

**Comment by wirble** [comment]
I am glad it helped, can you close out this ticket?  thanks.
