### ISSUE TITLE
Am I missing anything?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2742]
The following controller has been created by Serenity which works fine and allow navigation to this page
![image](https://user-images.githubusercontent.com/20435849/31354103-58141c82-ad4a-11e7-9a3f-b835d2716acf.png)

But when I create the following controller
![image](https://user-images.githubusercontent.com/20435849/31354151-82e88c18-ad4a-11e7-9f27-0e11f05e8704.png)

it gives the following error when I run
    
![image](https://user-images.githubusercontent.com/20435849/31354169-9bbb0b58-ad4a-11e7-826d-196aa4099130.png)

Am I missing anything? 
Thank you

**Comment by wirble** [comment]
Did you add an index file at the expected location?  Ot looks like there isnt one? If you added it make sure to do a transform after rebuilding.

**Comment by ms4hafiz** [comment]
Thanks @wirble 

Even adding Index.cshtml is not working. It gives the same error.

**Comment by wirble** [comment]
You didnt explicitly specify a location in the return view. So its looking for an index file under dashboard2 and shared.

**Comment by ms4hafiz** [comment]
Thank you @wirble 

Yes it looks for the view under the view folder. It is a question for me as well that as you can see in the first example, it does not have a view inside the view folder but works fine while in the second example it is looking for the view.

Maybe there is specific configuration needed for Serenity.

**Comment by javaman63** [comment]
Add this on your RouteConfig.cs

`
            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );

`

**Comment by ms4hafiz** [comment]
Thanks @javaman63 

I had to working using the default functionality of MVC.

Regards
Hafiz
