### ISSUE TITLE
Add items dynamically to lookupeditor combobox on runtime

### ISSUE THREAD

**Issue by vinslake** [volkanceylan/Serenity#2743]
Hi there,

How to to add items dymanically to  lookupeditor combobox on runtime base on the selected value on other combobox.

thnks....

**Comment by JohnRanger** [comment]
Hmm,

can you please explain more clearly in Detail what you want to achieve (e.g. with some screenshots)? 

In General you always can programmatically manipulate the browser's DOM object and add additional entries to a Dropdown element.

But this would Bypass the meaning of a lookup in my understanding.

With Kind regards,

John
