### ISSUE TITLE
RowLookupScript and CascadFrom

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2744]
Hi! Help me please!

How can I get the value of a cascading field in a RowLookupScript?

_e.g.  int orgId= **CascadeFild["OrganizationId"]**_

```
public class LookupServicesLookup : RowLookupScript<Entities.ServicesRow>
    {
        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
                UserRow user;
                using (var connection = SqlConnections.NewFor<UserRow>())
                {
                    user = connection.TryById<UserRow>(Authorization.UserId);
                }

            OrganizationRow org;
            using (var connection = SqlConnections.NewFor<OrganizationRow>())
            {
                int orgId= **CascadeFild["OrganizationId"]**
                org = connection.TryById<OrganizationRow>(orgId);
            }

            if (org != null) query.Where(ServicesRow.Fields.CategoryClientId.Like("%"+org.CategoryClientId.Value+"%"));
            
        }

    }
```

**Comment by Zahar661** [comment]
Or the standard cascade can filter on the third field?
![image](https://user-images.githubusercontent.com/26430136/31380274-87b7976a-adb9-11e7-8961-cee1dda3d91a.png)

**Comment by wirble** [comment]
Looking in the sample or the manual.  There is an example somewhere, but you shouldn't have to mess with the codes.  That can be done using the decorator in the row file.

        [DisplayName("Top Dog"), Size(25), QuickSearch, NotNull, QuickFilter, ForeignKey("[dbo].[TopDog_DBTAble]", "TopDogName"), LeftJoin("jTopDog"), TextualField("MoreDescriptiveName")]
        [LookupEditor(typeof(MyNameSpace.MyModule.Entities.TopDogRow))]
        
        public String TopDogLocation
        {
            get { return Fields.TopDogLocation[this]; }
            set { Fields.TopDogLocation[this] = value; }
        }
		[LookupEditor(typeof(MyNameSpace.MyModule.Entities.BottomDogRow), CascadeFrom = "TopDogLocation", CascadeField = "TopDogName"), QuickSearch]
        [DisplayName("Bottom Dog"), Size(25)]
        public String BottomDogLoc
        {
            get { return Fields.BottomDogLoc[this]; }
            set { Fields.BottomDogLoc[this] = value; }
        }

**Comment by Zahar661** [comment]
Hi @wirble !
does not work, there is not a direct link. 

```
public class ServiceInOrganizationForm
    {
        [LookupEditor(typeof(LookupOrganizationLookup), InplaceAdd = true, DialogType = "LK.ContragentDialog")]
        public Int32 OrganizationId { get; set; }

        [LookupEditor(typeof(ServicesRow), CascadeField = "CategoryClientId", CascadeFrom = "OrganizationId")]
        public Int32 ServiceId { get; set; }

        [LookupEditor(typeof(PersonRow), InplaceAdd = true, Multiple = true, Delimited = true, CascadeField = "OrganizationId", CascadeFrom = "OrganizationId")]
        public String Users { get; set; }
        [LookupEditor(typeof(ServiceInOrganizationStateRow))]
        public Int32 ServiceInOrganizationStateId { get; set; }
        public DateTime DateStart { get; set; }
        public DateTime DateEnd { get; set; }
        public Double Price { get; set; }
        [TextAreaEditor]
        public String Description { get; set; }
        public String Results { get; set; }
    }
```

**Comment by wirble** [comment]
maybe your requirement is different.  The cascade in Serenity I am using is from a drop down.  Yours is a multi-select.  I am not sure how to do that in Serenity.  I have not seen an builtin samples that does that.

**Comment by Zahar661** [comment]
Multiple choice works fine in the box below, and the problem in the field ServiceId
![image](https://user-images.githubusercontent.com/26430136/31402335-5e4beae4-adfe-11e7-81d1-ab97def35e42.png)

**Comment by Zahar661** [comment]
```
export class ServicesEditor extends Serenity.LookupEditorBase<ServicesRow,any> {

        protected FromValue: number;

        constructor(hidden: JQuery) {
            super(hidden);

            var editor = Q.findElementWithRelativeId(this.element, "OrganizationId").tryGetWidget(Serenity.LookupEditor);
            if (editor != null) {
                var self = this;
                editor.element.on("change." + this.uniqueName, () => {
                    this.FromValue = Number(editor.value) || 0;
                    this.updateItems();
                });
            }
            
        }

        protected getLookupKey() {
            return ServicesRow.lookupKey;
        }
            
        
        protected getItems(lookup: Q.Lookup<ServicesRow>) {
            let results = super.getItems(lookup);
            if (this.FromValue != null) {
                var o = OrganizationRow.getLookup().itemById[this.FromValue];
                if (o.CategoryClientId!=null) results = results.filter(x => x["CategoryClientId"].includes(o.CategoryClientId));
            }
            return results;
        }
```

**Comment by gpraveenraj** [comment]
Hi 

Multiple selection is not working fine after i implemented the Lookupscript

![image](https://user-images.githubusercontent.com/28450286/33305348-a7cae9b8-d405-11e7-8f39-82801c7d4cbf.png)

It is allowing user to reselect the same option again. How i can restrict it?
