### ISSUE TITLE
Stored Procedure :how to pass field value to parameter...

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2745]
@volkanceylan 
@Estrusco 
@VictorTomaili
 
 As my request not contains value for commented field bcoz it is a create request..
how can i load the value ..I have reference to these table..

public SaveResponse Create(SaveRequest<MyRow> request)
        {
            using (var connection = SqlConnections.NewByKey("DSLAppDB"))

            using (var uow = new UnitOfWork(connection))
            {
                try
                {
                    uow.Connection.Execute("PMS_GenerateEnquiryNo",
                                    param: new
                                    {
                                        @customerID = request.Entity.CustomerId,
                                        @RegionID = request.Entity.RegionId,
                                        @projectDomainID = request.Entity.ProjectDomainId,
                                        @CustomerContactperson = request.Entity.CustomerContactPerson,
                                        @customerContactDetails = request.Entity.CustomerContactDetails,
                                        @ProjectDescripton = request.Entity.ProjectDescription,
                                        @AssignTo = request.Entity.AssignTo,
                                        @ReferedBy = request.Entity.ReferedBy,
                                        @CustCode =          //belongs to customer table
                                        @ProjectDomain =   //belongs to ProjectDomain Table

                                    },

                                    commandType: CommandType.StoredProcedure);
                    uow.Commit();
                }
                catch (System.Exception ex)
                {

                }

                return new SaveResponse();
            }
        }
thanx in advance....

**Comment by Estrusco** [comment]
Try to add two joins field in your entity, or you can get data before execution of stored procedure calling repository of Customer and ProjectDomain

**Comment by javaman63** [comment]
@Estrusco  do you have an example of how to pass a value from a lookupeditor (Ex: Customer) to an stored procedure to filter?

I have seen the stored procedure example with dates, but I can not figure out how to do it with others types of  "COMBO BOXES"

**Comment by ANDY7575** [comment]
thank you guys..
actually i managed to do it in SP.
