### ISSUE TITLE
Combine fields in Stored Procedure with fields in Serenity modules

### ISSUE THREAD

**Issue by galof** [volkanceylan/Serenity#2746]
I wish to combine fields included in a Stored Procedure with fields left out of the SP (but included in Serenity modules – XYZrow.cs code, etc.) in dialogs.

I have a Stored Procedure that includes fields from 3 tables (fields that cannot be null, leaving the null-able ones out of the SP so to keep the SP to a minimal, basic form). (The case is that 2 of these 3 tables need a new row to be created in the third table in order for them to be populated so this must be done simultaneously.)

Now I consider to use this basic SP and get other fields needed –including fields from other tables that are related to the tables in the SP– fields that show up in Serenity modules (as XYZrow.cs code, etc.) but not in the SP and combine them with the ones included in the SP. I try to keep the SP to a minimal form and not include all related tables and their fields so that I can use it over and over again without amendment. These fields are meant to be used in dialogs.

Is there a way to have this working?

Needless to say that the basic SP works fine in Serenity.

**Comment by volkanceylan** [comment]
Write a view or SP that combines them in SQL side.
