### ISSUE TITLE
grid yüklendiğinde ilk seferinde verilerin yüklenmesini istemiyorum

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#2748]
grid yüklendiğinde ilk seferinde verilerin yüklenmesini istemiyorum.

getViewOptions den autoLoad  denedim işe yaramadı başka bir yardımcı metod varmı?

```
        protected getViewOptions(): Slick.RemoteViewOptions {
            var opt = super.getViewOptions();
            opt.autoLoad = false;
            return opt;
        }
```

**Comment by JohnRanger** [comment]
Hi oaltay,

if you Need only Volkan's help, then turkish is fine :-) but if you want that all of us potententially can help you, then may I kindly ask that you translate your question / issue into english :-)

With Kind regards,

John

**Comment by volkanceylan** [comment]
Override initialPopulate(), don't call base method.
