### ISSUE TITLE
Chat widget for Serenity

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2749]
Hi All;

I would like to add a chat option to the database build using Serenity. Can anybody please guide me with this.

Thanks

**Comment by Zahar661** [comment]
As far as I know, there is no such thing.

**Comment by ms4hafiz** [comment]
Thank you

**Comment by kilroyFR** [comment]
I would try to use Candy chat JavaScript component. It's fully functionalities (not LinkedIn to dB though)
