### ISSUE TITLE
HTMLEditor placed incorrectly after updating nuget to 1.9.11 / 1.9.12

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#275]
Hi,
After updating my nuget packages to version 1.9.11, my dialogs with an HTMLEditor places the HTML Editor aligned incorrectly relative to other components. I updated again to 1.9.12 but problem persists. See attached image. See the gap between label for the html editor and the editor itself. The editor is also aligned left of form and not with other editors.

![image](https://cloud.githubusercontent.com/assets/7986251/13173442/26c031aa-d706-11e5-8e77-51ba993d72f9.png)

**Comment by volkanceylan** [comment]
Decrease editor widths a bit, this has no relation to 1.9.12, require space for validation check

**Comment by wpvking** [comment]
Where do I do this? And which attribute should I use?

**Comment by volkanceylan** [comment]
In less file, site.less etc

**Comment by wpvking** [comment]
So I reduced the editor size to 200px in the site.less file, with the following result:

![image](https://cloud.githubusercontent.com/assets/7986251/13176502/733f46fa-d71b-11e5-9e83-aaa025957387.png)

**Comment by volkanceylan** [comment]
Sorry, have no idea, as i guessed it is about size but there is some strange left margin there, and i can't reproduce this. Check other css.

**Comment by wpvking** [comment]
So i reverted back to nuget package 1.9.07 and this is what it looks like without changing any less or css:

![image](https://cloud.githubusercontent.com/assets/7986251/13177866/703c6cd6-d724-11e5-9515-fab3fdcd7790.png)

**Comment by volkanceylan** [comment]
Do you notice that its Turkish? This is only difference.

I went back to 1.8.18 template, updated to 1.9.12 and still no such issue.

Find what is left to your CKEditor when you made it 200px, there is something (margin or an invisible div) using Chrome dev tools

My guess is your Select2 version is not 3.5.1

**Comment by volkanceylan** [comment]
Please reopen with more info if not resolved

**Comment by wpvking** [comment]
Hi, I attached the images with the html that was generated. You will see that a <textarea> section is added between the label and the HTMLContentEditor. Where do I disable this insertion please?

![image](https://cloud.githubusercontent.com/assets/7986251/13249910/9287a2fc-da2f-11e5-88fb-0bfc8409cdbd.png)

**Comment by volkanceylan** [comment]
As i guessed

Update-Package Select2.js -version 3.5.1

**Comment by wpvking** [comment]
Thanks, that worked.
