### ISSUE TITLE
No connection string with key '' in configuration file!

### ISSUE THREAD

**Issue by jez26753297** [volkanceylan/Serenity#2750]
Hi, I created a new Serene project and ran the code generator to connect to an existing database which has six tables. I added a new connection in the generator with Connection Key called kDB. After running the generator it looked like the correct table folders were created in the Modules>kDB folder.
When I run the project in Chrome and click to display the tables, a red message banner appears with the text “No connection string with key kDB in configuration file!”.
Have I missed something or have to modify something somewhere?
Thanks

**Comment by Estrusco** [comment]
See connection strings in your Web.config

**Comment by karimhyatt** [comment]
Check your Web.config. You should add your connection string.

In App_Start/SiteInitialization.Migrations, you will need to add/change the databaseKeys to match your connection strings (you need a string for each connection string/key name in your web config.

You then will have to comment out the safety check in RunMigrations method.

**Comment by volkanceylan** [comment]
You shouldn't have changed Connection String Key in Sergen, leave it as Default, you may change it at Row.cs
