### ISSUE TITLE
How Get and Save in Record Login User (Authorization.UserID)

### ISSUE THREAD

**Issue by rickyhasudungan** [volkanceylan/Serenity#2751]
Hi sorry for this very dummy question

I just need to ask how  to set default value as  Authorization.UserID and save in table ?

Please find below sample that I try but failed

[DisplayName("Create User"), Size(10), DefaultValue(Authorization.Username)]
        public String CUser
        {
            get { return Fields.CUser[this]; }
            set { Fields.CUser[this] = value; }
            //get { return Authorization.UserId; }
            //set { Fields.CUser[this] = Authorization.UserId; }
        }

**Comment by javaman63** [comment]
Can you explain a little more what is you want to acomplish?

**Comment by rickyhasudungan** [comment]
What I would to accomplish
1st get the login user name / id 
--> my assumption this could be get from `Authorization.Userid` or Authorization.UserName``

2nd save the user name or id in database
--> my assumption to save this information in transaction let say in "TransactionRow.cs" 
sample of code
[DisplayName("Login User"), Size(10)] 
// /record the Login User ID or User Name 
// not input by user but set default value or get value from Authorization Userid from Login screen 
public String LUser
{
get { return Fields.LUser[this]; }
set { Fields.LUser[this] = value; }
}

I hope this explanation could give more detail information

**Comment by Zahar661** [comment]
I did so
xxxGrid.ts
```
protected addButtonClick() {
            this.editItem(<Task.TaskRow>{
                AuthorId: Authorization.userDefinition.UserId
                
            });
        }
```

**Comment by Zahar661** [comment]
or 
```
private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                if (base.IsCreate)
                {
                    base.Row.Author = Convert.ToInt32(Authorization.UserId);
                    base.Row.Create = DateTime.Now;
                }
                base.Row.AuthorChange = Convert.ToInt32(Authorization.UserId);
                base.Row.Change = DateTime.Now;
            }
        }
```

**Comment by JohnRanger** [comment]
Hi

yes, I also do this in MySaveHandler in the beforeSave() Event - like Zahar661 explained.

If you Need also that a specific user only sees his own records, see: #2634 

With Kind regards,

John

**Comment by rickyhasudungan** [comment]
Thanks a lot Guys this very help, now I know how to solve it
Best Regards
