### ISSUE TITLE
xyzDialog.Template.HTML disables size set within .less file

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2752]
Dear all,

normally I easily can define width and height and caption width within the .less files for my Dialogs.

Now I Need to use a xyzDialog.Template.html to add additional Content to the the Dialog.

This works very fine (very elegant method of defining a Dialog by the way) but unfortunately - the Moment I have a xyzDialog.template.html file in my module, the dimensions set within the less file stop working for that particular Dialog.

Is this an expected behavior?

If yes: How can the Settings done within the less file be applied again to the dialog?

If no: @Volkan: Could you please look into this?

My template Looks like this:

```html
<!-- Serenity -->
<div id="~_Toolbar" class="s-DialogToolbar">
</div>
<div id="~_Tabs" class="s-DialogContent">

    <div id="~_TabOrder" class="tab-pane s-TabOrder">
        <div class="s-Form">
            <form id="~_Form" action="">
                <div class="fieldset">
                    <div id="~_PropertyGrid"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- FileUpload part -->
<div id="jojo">
    <div id="actions">
        <div class="col-lg-7">
            <table>
                <tr style="height:40px;">
                    <td width="30%">    <!-- Column 1 (Add File button)-->
                        <span class="btn btn-success fileinput-button">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>Add files...</span>
                            <input id="fileupload" type="file" name="files[]" data-url="/Services/Default/SharedFiles/Upload" single>
                        </span>
                        
                    </td>
                   
                    <td width="10px"></td>

                    <td width="100%">    <!-- Column 4 (Progress bar) -->
                        <div id="progress">
                            <div class="bar" style="width: 0%; height: 18px; background: green;"></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    
</div>
```

Thanks for any Feedback and

with Kind regards,

John

**Comment by Zahar661** [comment]
Hmm ... Standard CSS.
e.c.
.s-MyModul-xxxDialog {
    > .size {
        width: 750px;
        height: 550px;
    }

    .caption {
        width: 120px;
    }

    #jojo tr {
        height: 40px;
    }

    #jojo tr td .bar {
        width: 0%;
        height: 18px;
        background: green;
    }
}

**Comment by Zahar661** [comment]
You can also try !important

**Comment by JohnRanger** [comment]
Hi Zahar661,

thanks for your Feedback. This is more or less what is automatically generated by Serenity by compiling the .less file into the site.css (see below):

```css
.s-Default-SharedFilesDialog > .size {
  width: 300px;
  height: 700px;
}
.s-Default-SharedFilesDialog .caption {
  width: 200px;
}
```

But unfortunately this does not Change the Dialog one Little bit.

I will have to investigate further...
 
Maybe the relevant Elements have different names than what Serenity thinks they should be (if a template is used). The Moment no template is used this works as expected.

Thanks again and

With Kind regards,

John

**Comment by JohnRanger** [comment]
Hi all,

sorry, my fault: I had Exported the Dialog under a different Name (like in GetInsertedRecordIdDialog.ts from samples) so serenity could not Auto-generate the css for the correct Dialog.

Interesdingly when I earlier tested without template it worked. How - I don't know.

Thanks again for all your help and

with Kind regards,

John

**Comment by Zahar661** [comment]
in file less you need to write styles yourself. there is an example in \BasicSamples\Dialogs\MultiColumnResponsiveDialog

.s-Default-SharedFilesDialog #jojo #action tr {
        height: 40px;
    }

  .s-Default-SharedFilesDialog  #jojo #action tr td .bar {
        width: 0%;
        height: 18px;
        background: green;
    }
