### ISSUE TITLE
Tabs inside a form ?

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2753]
I already used the scenario that is a dialog box with a FORM on first tab then others grids in related tabs (same as NorthWind Customers/Orders sample).

I wanted to know if it's possible to display the tabs not aside the main FORM tab but at the bottom of the FORM fields ? 
```
-----------------------
|      FORM FIELDS    |
-----------------------
|TAB1|TAB2|TAB3     |
-----------------------
```
PS : (i have seen the 3.0.7 additions but sub-tabs are related to same FORM fields).
BTW this tab display is great addition when too many fields to display.

**Comment by Estrusco** [comment]
You can modify the xyz..template.html and move the <ul> element in the bottom of page

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/31545778-6411e35c-b029-11e7-9cb1-6950e95c04b0.png)

![image](https://user-images.githubusercontent.com/26430136/31545799-7ad960ce-b029-11e7-9f29-eb82b4585b30.png)
