### ISSUE TITLE
Setting lookup filterValue programmatically

### ISSUE THREAD

**Issue by LarsMengel** [volkanceylan/Serenity#2755]
Hi,
I set up a lookup Editor in one of my forms. This lookup should be filtered by a field of my form. I ended up with a variant of the solution from Issue #2440 .
```typescript
        protected changeInProcess = false; // used to avoid the second change event triggered by the first change event
        protected lastValue = undefined; // used to store the original selected value to restore it after handling all recursive change events

        constructor() {
            super();

            this.form.EquipmentAliasId.change(e => {
                if (!this.changeInProcess) {
                    this.changeInProcess = true;
                    this.lastValue = e.target.value;
                    this.form.EquipmentAliasId.filterValue = this.form.EquipmentId == null ? "@@@@@@" : parseInt(this.form.EquipmentId.value);
                    this.changeInProcess = false;
                }

                this.form.EquipmentAliasId.value = this.lastValue;
            });
```
Obviously this is more a workaround than a solution.
Is there any other event I can use than the change event on the property with the lookupeditor. This would be a little bit nicer because it avoids recursive calls of the event itself.

**Comment by JohnRanger** [comment]
Hi LarsMengel,

do I understand correct that you have one field (lets Name it Field1) in the form and a Change within this field1 should update the lookupEditor on EquipmentAliasId?

If yes, then I don't understand why you trigger on the EquipmentAliasId.change Event instead on the Field1.change Event.

Otherwise please add a screenshot with the fields involved :-)

With Kind regards,

John

**Comment by LarsMengel** [comment]
Hi John,
it's an edit dialog and it's opened from a grid view by clicking an edit link. My first idea was to use change event on equipmentid (Field1) as you suggested. But it's never called during the opening process of the edit dialog. 
To tell the whole story - there is a grid view showing items of some kind of equipment. Each equipment item has an Id and a unique name. Additionally the user has the possibility to create aliases for each equipment item and to set a current alias property. I make use of two tables: Equipment and EquipmentAlias. EquipmentAlias contains a list of aliases bound to an equipment item. When the Equipment is edited the alias lookup has to be filtered by the current equipmentId because the user shouldn't be able to see aliases of other equipment items. 
Unfortunately I wasn't able to reach this behaviour using the cascade or filter functionallity of the lookup editor attribute.

**Comment by LarsMengel** [comment]
Ok, it took me a while but eventually I ended up overwriting the afterLoadEntity methode:
```typescript
        protected afterLoadEntity() {
            super.afterLoadEntity();
            if (this.entity.EquipmentId != null) {
                this.form.EquipmentAliasId.filterValue = this.entity.EquipmentId;
            }
            else {
                this.form.EquipmentAliasId.filterValue = "@|\?"; // we don´t want to see any items for a new Equipment 
            }

            if (this.entity.EquipmentAliasId != null) {
                this.form.EquipmentAliasId.value = this.entity.EquipmentAliasId.toString();
            }
        }
```
