### ISSUE TITLE
DateFormatter applied in xyzRow.ts are respected in xyzGrid.ts but not in xyzForm.ts

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2756]
Hi all,

I know there are plenty of issues/questions regarding Date- and DateTimeFormatter and I have read through many of them but I simply don't get the Display of a date within a form correct:

I have applied a DateFormatter to a field within xyzRow.ts like this:

```ts
[DateTimeKind(DateTimeKind.Utc), DateFormatter(DisplayFormat = "yyyy-MM-dd")]
 [DisplayName("Time Stamp Upload"), Column("TimeStamp_Upload"), ReadOnly(true)]
```

**Problem:**
This results that in the xyzGrid.ts, the Date is correctly displayed but not correctly displayed within the xyzForm.ts.

![issue](https://user-images.githubusercontent.com/2699447/31568074-db3c8a4c-b072-11e7-88e8-b469b68a0937.png)

I have read in other issues that this depends on the culture Setting in web.config but there is of Course no culture which Displays the date in the desired Format.

**Question:**

Is there a way to easily apply the dateformatter also to a form field so that the form also Displays the date in the form: yyyy-MM-dd or if not, how can this be accomplished?

Thanks for your time and

with Kind regards,

John

**Comment by dfaruque** [comment]
changing culture in web.config might be helpful

        `<globalization culture="ts-ZA" uiCulture="ts-ZA" />`

**Comment by kilroyFR** [comment]
As explained by Volkan, you can : 1. should change culture in web.config to something that uses dd/MM/yyyy, or set your preferred format in LayoutHead, setting your prefs in ScriptCulture object constructor.'

**Comment by kilroyFR** [comment]
As explained by Volkan, you can 1. change settings in web.config or setting ScriptCulture in _LayoutHead.cshtml
`(@Html.Raw(Serenity.JSON.Stringify(new ScriptCulture() {DateFormat = "yyyy-MM-dd" }))`

this gives results expected. Other Culture settings can be changed

**Comment by JohnRanger** [comment]
@kilroyFR ,

thanks for your feedback - this solves the problem described in my issue. @dfaruque  - thanks also for your feedback.

With kind regards,

John
