### ISSUE TITLE
using a single column page in different forms

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2757]
i have customer column class i have to use that in two modules as grid with different columns how to use it 

for ex. in module 1 grid i have to display c1,c2,c3 columns where as in module 2 grid  c4,c5 
please help me

**Comment by JohnRanger** [comment]
Hi.

You anyway Need 2 different xyzColumns.cs files as you have different modules.

So let's say: 
- Module abc = abcColumns.cs 
- Module xyz = xyzColumns.cs.

In each of the ...Columns.cs file you can use the tag: visible(true/false) on top of each field - like this:

abcColumn.cs:
```cs
[EditLink, Width(150), visible(true)]
public String c1 { get; set; }
[EditLink, Width(150), visible(true)]
public String c2 { get; set; }
[EditLink, Width(150), visible(true)]
public String c3 { get; set; }
[EditLink, Width(150), visible(false)]
public String c4 { get; set; }
[EditLink, Width(150), visible(false)]
public String c5 { get; set; }
```

and in xyzColumns.cs:

```cs
[EditLink, Width(150), visible(false)]
public String c1 { get; set; }
[EditLink, Width(150), visible(false)]
public String c2 { get; set; }
[EditLink, Width(150), visible(false)]
public String c3 { get; set; }
[EditLink, Width(150), visible(true)]
public String c4 { get; set; }
[EditLink, Width(150), visible(true)]
public String c5 { get; set; }
```

Or alternatively just delete the unwanted fields (the ones with visible(false) from the ...Columns.cs fields.

Hope this helps.

With Kind regards,

John
