### ISSUE TITLE
SereneLayers / decoupling services from gui

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2759]
Is it possible to split a Serenity project into 2 parts :  
- 1 website hosting only Services (requests/responses and repository)) 
- 1 wesbite hosting GUI interfaces only (accessing to services provided by the other websites).

Why ? to decouplate api (providing REST/JSON data) from the gui rendering

I have checked SereneLayers projects but basically services/repository are on a separate project/assembly (dll) but they don't exist as standalone web services.

Anyone tried this already ? i am planning on testing this but wanted to ask first if someone already tried. Thanks !

**Comment by samdubey** [comment]
this should solve your issue
https://github.com/volkanceylan/SereneLayers

**Comment by volkanceylan** [comment]
It could be possible, but you'll need to design that on your own.
