### ISSUE TITLE
IS there a way to filter lookUpEditors based on a selection on another lookupEditor?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#276]
![untitled](https://cloud.githubusercontent.com/assets/17201265/13179565/17e8566a-d6ea-11e5-9fd9-bbada73612f6.jpg)
Is there a way to configure the lookup editor to filter on selection of a another selection. I have created the joining table in the database, but I am not sure is I can use the LookUpFilter attribute.

**Comment by dfaruque** [comment]
See casecade lookup in serenity guide.

**Comment by swordz36** [comment]
Do you have an example I not to familiar with all of the editors and settings?

**Comment by volkanceylan** [comment]
Did you have a look at How To: Cascaded Dropdowns in Serenity Developer Guide??

**Comment by swordz36** [comment]
Thanks a lot

**Comment by swordz36** [comment]
I addressed this issue by using this code
![image](https://cloud.githubusercontent.com/assets/17201265/14368650/b43a7f3c-fce4-11e5-8f16-cf2d42dc0329.png)

Also to make that lookupinclude is on the Foreign Keys of the joining table.
Make sure that implement INameRow for the joining table
