### ISSUE TITLE
How to show controls column wise in dailog.ts window

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2760]
I want to show my controls in two or three in one row. 

right now all of my property showing like one in a row.

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/MultiColumnResponsiveDialog/Index.cshtml

**Comment by ManzoorPK** [comment]
No friend i want when dialog box opens i want to show the control in columns not by row. like i have many checkbox i want to show them all in one row right now its all showing separate in new row each.

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/31600178-23aa009c-b25e-11e7-87ca-351d1dcd46f5.png)
![image](https://user-images.githubusercontent.com/26430136/31600239-629cf2dc-b25e-11e7-84f4-bb7e44b7dd58.png)

**Comment by ManzoorPK** [comment]
Where you wrote that code? under which file?

**Comment by VictorTomaili** [comment]
Under "site.less" write your own css for customizing fields in the dialog.

**Comment by Zahar661** [comment]
MyProject.Web\Content\site    *.less  
If you did not create them for the module then by default site.less

**Comment by ManzoorPK** [comment]
:(

**Comment by ManzoorPK** [comment]
and how then i can integrate this css into my dialog?

**Comment by Zahar661** [comment]
Already everything is there, just find the file site.les
In it, find the .s-MyModul-xyzDialog {}
Add
```
.s-MyModul-xyzDialog {
    > .size {
        width: 1074px;
    }

    .caption {
        width: 110px;
    }
        .field.MyField1, .field.MyField2, .field.MyField3 {
            flex: auto;
            min-width: 200px;
            width: 25%;
        }
    }
}
```

**Comment by ManzoorPK** [comment]
and where can i write css to manage grid.ts columns ? to manage width

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/31601198-b3a26254-b261-11e7-977d-6e3ce5285b66.png)

**Comment by ManzoorPK** [comment]
and where can i write css to manage grid.ts columns ? to manage width

**Comment by ManzoorPK** [comment]
thanks all for your helps, its worked i followed your instruction Zahar thank you friend.
