### ISSUE TITLE
How can i retrieve from store procedure in serenity framework 

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2762]
Can any body help me how can i retrieve my fields from Store procedure ?

      public RetrieveResponse<MyRow> loadUserWorkingDetailsByUser( RetrieveRequest request)
        {
            
            return this.UseConnection("Default", connection =>
            {
                connection.Open();
                using (IDbCommand command = connection.CreateCommand())
                {
                    IDbDataParameter ParamUserId = command.CreateParameter();

                    ParamUserId.ParameterName = "@UserId";
                    ParamUserId.Value = user.Id;
                    command.Parameters.Add(ParamUserId);
                   
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "spUserWorkingHoursDetails_Single";
                    command.ExecuteNonQuery();

                    

                }
            });
           
        }

**Comment by xareas** [comment]
Serenity orm is dapper, try this
https://www.codeproject.com/Articles/889668/SQL-Server-Dapper
