### ISSUE TITLE
Add a Signature Data Type Attribute

### ISSUE THREAD

**Issue by saeedahmad101** [volkanceylan/Serenity#2764]
hi,
i am working on an application and using serenity as template for it,

how ever during development at multiple places i need clients to sign the form which should get saved along with the record.

i am able to use following library to achieve that functionality in a regular MVC project i was wondering how i can integrate it into serenity project. any help would be highly appreciated thankx.
[signaturepad](https://github.com/szimek/signature_pad)

**Comment by saeedahmad101** [comment]
a small hint would help resolving this problem, thankx...awaiting

**Comment by volkanceylan** [comment]
There is a 3rd party component integration sample in guide, try that.

**Comment by wezmag** [comment]
see https://github.com/volkanceylan/Serenity/issues/4533 for implementation
