### ISSUE TITLE
How access Serenity MODEL with html helpers.

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2766]
Hello, i am trying to access Serenity model with html helpers but it is not working. here is my code.

        @model  Payroll.Default.Entities.UserClockInOutRow
       @{
    ViewData["Title"] = Serenity.LocalText.Get("Db.Default.UserClockInOut.EntityPlural");
          }
       <div class="alert alert-info alert-dismissable">

        <p style="text-align: right;">
        <b>User :</b>
       
            @Html.LabelFor(m => m.DisplayName)
        
    </p>
         </div>
         <div id="GridDiv"></div>

      <script type="text/javascript">
          jQuery(function () {
        new Payroll.Default.UserClockInOutGrid($('#GridDiv'), {}).init();

        Q.initFullHeightGridPage($('#GridDiv'));
        });
        </script>

**Comment by volkanceylan** [comment]
Serenity entities are not models in MVC sense. You should define a form and use that. Otherwise create inputs manually matching row property names.
