### ISSUE TITLE
NullReferenceException when transforming T4 templates after v3.0.8 -> v.3.1.0 update

### ISSUE THREAD

**Issue by DWepp** [volkanceylan/Serenity#2768]
I updated the Serenity VS Extension to v3.1.0, then closed everything and reopened my project, updated it from v3.0.8 to v3.1.0 via NuGet, and now I'm getting errors trying to transform.

The project rebuilds successfully, but when I then try to transform all T4 templates, I get a NullReferenceException.

I'm not sure where to begin troubleshooting this.

![image](https://user-images.githubusercontent.com/32848470/31625858-9e16883e-b275-11e7-8dc9-13690da81d1b.png)

**Comment by zKarp** [comment]
Same, thought this was due to updating Typescript to 2.5 today.
Glad I'm not the only one.

**Comment by volkanceylan** [comment]
Please try with 3.1.1, it should be resolved.

**Comment by DWepp** [comment]
Confirmed. Thank you for the swift resolution.
