### ISSUE TITLE
Website skipped running migrations to avoid modifying an arbitrary database. If you'd like to run migrations on this database, remove the safety check in SiteInitialization.RunMigrations method.

### ISSUE THREAD

**Issue by matthewpomar** [volkanceylan/Serenity#2769]
We tested Serenity in our dev environment and didn't see this message. We are building a UI for some existing tables in a database and when we published the changes to production we got this (very scary) message:

> Website skipped running migrations to avoid modifying an arbitrary database. If you'd like to run migrations on this database, remove the safety check in SiteInitialization.RunMigrations method.

This makes me worry that Serenity will someone make unwanted changes to our production database without us knowing. 

How can I be sure that Serenity will never change our database structure in production?

Any ideas on why we didn't see this message in dev but we did in production?

**Comment by VictorTomaili** [comment]
A description is here. 

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/App_Start/SiteInitialization.Migrations.cs#L156

**Comment by volkanceylan** [comment]
Serenity cares about you, plays safe and doesn't run migrations that will create users, roles etc. on a production database. You didn't get that in development because your DB name was something like MyProject_Default_v1 which is the default one it creates. I really don't understand what is so scary about that.

**Comment by matthewpomar** [comment]
Thanks for your reply; I think I understand what happened. Because our production server doesn't have the localdb engine installed, we migrated the "MyProject_Default_v1" database aka the "Administration DB" to a regular SQL Server database. That's why it was different than dev.

1. So is the error message only applicable to the "Administration DB"?

2. Even though we close the error at the top of the page, it keeps coming back. Is there a way to hide it forever?

Very nice project, BTW. You guys do great work! :)

Thanks again.

**Comment by volkanceylan** [comment]
Remove the check
