### ISSUE TITLE
Conditional Formatting on Grids

### ISSUE THREAD

**Issue by raycmitchell** [volkanceylan/Serenity#2770]
Hi

Trying to apply conditional formatting on grids where columns are not shown but are hidden.  Is there any way this can be done, so we can format on a field that is in the database row but is hidden from the screen and field chooser.

Thanks

**Comment by Zahar661** [comment]
Visible and Hidden  work in different ways.

**Comment by raycmitchell** [comment]
Used both which seem to put the column in question in the field chooser but the field is not available when going through all of the columns.
