### ISSUE TITLE
Typo in Serenity.Web/Texts/Texts.Controls.ImageUpload.cs

### ISSUE THREAD

**Issue by DWepp** [volkanceylan/Serenity#2773]
I realize this is a nitpicky item. Not sure if you even care, but there's a typo ("smallar") in Serenity.Web/Texts/Texts.Controls.ImageUpload.cs

Also, can we add the word "bytes" to this alert?

![image](https://user-images.githubusercontent.com/32848470/31640755-2eb4e7c2-b2ae-11e7-9393-ff9812dbbbfd.png)

**Comment by Zahar661** [comment]
there you can do everything!
