### ISSUE TITLE
How to write sql query on multiple where clause

### ISSUE THREAD

**Issue by johnbucayan** [volkanceylan/Serenity#2774]
Hi Volkanceylan,
I'm in learning process as of now. I would like to know how to write this queries on serenity.

Select table_Id from mytable where table_foreignId= 3 and table_Active = 1
Select table_Id from mytable where table_foreignId= 3 or  table_foreignId= 4 and table_Active = 1

the reason is that the data comes from the session, I want to validate user from mytable if the user is authorize to access the page using the session values

**Comment by alexneocart** [comment]
I hope it helps
https://volkanceylan.gitbooks.io/serenity-guide/content/fluent_sql/fluent_sql.html

**Comment by johnbucayan** [comment]
thank you very much sir. this really helps @alexneocart
