### ISSUE TITLE
Looking for developer

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#2775]
I'm looking for ASP.net MVC developer with knowledge in JavaScript and SQL script to work full time (remotely). 

Interested may send their CV to-  mlotiya at outlook dot com with expectation.

Please mention number of years of total experience.

Serenity experience will be preferable. (Please mention in subject line)

**Comment by mahmuthaktan** [comment]
You could also check this:
http://serenity.is/#Pricing
