### ISSUE TITLE
Saving Filters with Favorite Views

### ISSUE THREAD

**Issue by matthewpomar** [volkanceylan/Serenity#2776]
It is possible to save your filter values with your Favorite Views? If not, can this be added as a feature request? It would be nice if saved views saved:

1. Filters
2. Sort Order
3. Columns

**Comment by javaman63** [comment]
Take a look to this chapter
[https://volkanceylan.gitbooks.io/serenity-guide/content/grids/persisting_settings.html](url)

**Comment by matthewpomar** [comment]
Thanks for the link. That's helpful. I cannot tell, however, if this works with the Save Favorite View, though. The online demo doesn't work that way.

**Comment by volkanceylan** [comment]
Online demo saves all that you asked, which is default, includes filters, columns, sort etc.
