### ISSUE TITLE
Custom Formatter for Duration Time Field

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#2777]
Hi everyone,

I've got a table with an integer field, which represents a duration time (in minutes). 

![field](https://user-images.githubusercontent.com/22232670/31671822-26511a94-b35b-11e7-9d51-be5d425573dc.png)

I added in my XYZForm.cs and XYZRow.cs the **TimeEditor()**, so in the table I see the duration in minutes.

![grid](https://user-images.githubusercontent.com/22232670/31672757-ae4a3b72-b35d-11e7-80ea-fa9edf05ca99.png)

 
In my XYZGrid.ts I'd like to show it in this format _(hour_ hours and _minute_ minutes). At this scope, I've created a custom formatter and I register it in my XYZColumns.cs, but it doesn't work: it gives me a console error and I can't see the entire grid.  

I show you my custom Formatter:
`

    @Serenity.Decorators.registerFormatter()
    export class DurationFormatter implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {
            let durata = ctx.value as number; /* Dovrebbe essere, ad esempio, "60" */
            console.log(durata);
            if (durata == null)
                return "";

            let output = ""; /* Il risultato finale */
            var quoziente = durata / 60;

            if (quoziente == 1)
                output = "1 ora";
            else
                output = quoziente.toString() + " ore";

            if (quoziente.toString().indexOf(".") != -1)
            {
                let minuti = quoziente.toString().split(".")[1];
                output += " e " + Number(minuti) * 0.6;
                if (minuti.length == 0)
                    output += "0 minuti";
            }

            return output;
        }
    }

`

My Console Error:
![error console](https://user-images.githubusercontent.com/22232670/31672420-d269e616-b35c-11e7-89e0-548650815c99.png)

I compiled and transformed templates, so I see that my Formatter was registered in the scripts.

What's wrong ?

Thanks for your help.

Kind regards.

**Comment by alexdaywid** [comment]
Check the link 
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Northwind/Employee
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Order/OrderColumns.cs

**Comment by volkanceylan** [comment]
Make sure your formatter type is under your project namespace, e.g. MyProject. Namespace is important, at it has to be in PascalCase.

**Comment by kjaraa** [comment]
I solved that. Thanks @alexdaywid and @volkanceylan for your time :)
