### ISSUE TITLE
Calling server side method from client side

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2778]
I want to call a server side method available at xxendpoints.css from xxGrid.ts. Any example and thought please with confirmation message. I am just learning Serenity.

           public void MoveData(IDbConnection connection)
           {
            //server side code goes here
           }

**Comment by Zahar661** [comment]
```
protected getButtons() {
            var buttons = super.getButtons();
            buttons.push({
                title: 'Pay To Date,
                cssClass: 'change-date-button',
                onClick: () => this.multiEdit() 
            });
            return buttons;
        }

        private multiEdit() {
            Q.serviceRequest(PayDcService.baseUrl + '/PayToDate', {}, (response) => {
                super.refresh();
            });
        }
```

**Comment by dfaruque** [comment]
see last three comments https://github.com/volkanceylan/Serenity/issues/155

**Comment by ms4hafiz** [comment]
Thanks 
It works and runs the server  side method but there is an error. 
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by fzhenmei** [comment]
Use Chrome DEV tool check your server response.

**Comment by ms4hafiz** [comment]
Thank you for the hint;

The problem was with return type of the server side method.
