### ISSUE TITLE
Build error in ReportRepository.cs after update

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#278]
Good Afternoon JaiQ,

I updated to latest Serenity packages version 1.9.13, and I followed the guide to change the return type of `GetData()` from IEnumerable to object, as specified. However, I am receiving the following error when rebuilding the project from `ReportRepository.cs`:

> foreach statement cannot operate on variables of type 'object' because 'object' does not contain a public definition for 'GetEnumerator'

The error occurs at line 13 of ReportRepository.cs:

```c#
namespace FlowState
{
    using Serenity.Reporting;
    using System.Collections.Generic;

    public class ReportRepository
    {
        public byte[] Render(IDataOnlyReport report)
        {
            var columns = report.GetColumnList();

            var data = new List<object>();
            foreach (var item in report.GetData())
                data.Add(item);

            return ExcelReportGenerator.GeneratePackageBytes(columns, data);
        }
    }
}
```

Any ideas how to fix this, or is it just a problem somehow on my end?

**Comment by jsbUSMC** [comment]
Ok. It looks like I've managed to get the error to go away by casting the GetData() method as `dynamic`.

```c#
namespace FlowState
{
    using Serenity.Reporting;
    using System.Collections.Generic;

    public class ReportRepository
    {
        public byte[] Render(IDataOnlyReport report)
        {
            var columns = report.GetColumnList();

            var data = new List<object>();
            foreach (var item in (dynamic)report.GetData())
                data.Add(item);

            return ExcelReportGenerator.GeneratePackageBytes(columns, data);
        }
    }
}
```

I haven't tested it out yet to see if it's working fine but the build passes with no errors or warnings.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Reporting/ReportRepository.cs

You better copy this one but anyway cast to IEnumerable would work too. I'll update change log.

**Comment by jsbUSMC** [comment]
Thank you very much. I appreciate the quick response and fix!
