### ISSUE TITLE
Data explorer with Export functionality

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2780]
I want to expand the data explorer to add two things:
Need all your support and suggestion:
1. Want to get list of tables stored in another table
2. Adding a button to export selected table data to excel

![image](https://user-images.githubusercontent.com/20435849/31710534-93e09bac-b40a-11e7-945b-055957992de9.png)

**Comment by alexdaywid** [comment]
Add Button excel Grid check o link 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Order/OrderGrid.ts

**Comment by volkanceylan** [comment]
@ms4hafiz please use StartSharp repo for your issues.
