### ISSUE TITLE
Sıralama

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#2782]
Gridte Birden fazla alana göre sıralama  yapılabiliniyor. mu?

yardımcı olursanız.

Kolay gelsin.

**Comment by AlperanQ** [comment]
Evet yapılabiliyor. Control (CTRL) tuşuna basılı tutarak yapabilirsiniz.

İyi çalışmalar.

**Comment by mahmuthaktan** [comment]
Kod tarafından Sıralamak için xyzColumns.cs: tanımladığımız yerde istediğimiz alanların hemen üstünde atribute olarak asagıdaki gibi sıralayabilirsin. 

[Width(180), SortOrder(1, descending: true)]
public DateTime BaslangicTarihi { get; set; }
[Width(180), SortOrder(2, descending: true)]
public DateTime GelisTarihi { get; set; }

https://github.com/volkanceylan/Serenity/wiki/Defining-a-Sort-Order.
