### ISSUE TITLE
Is Sernerity framework can be hosted on any MVC 5 supported shared hosting ?

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2786]
Hello Friends, Please advise me i have already created an HR system in Serenity Framework.

Now i need to host it, i don;t want to host it on azure for now. 

can i host it on normal MVC 4,5 supported shared hosting. i am planning to buy but i need to make sure it will work on it.

**Comment by brunobola** [comment]
Just any windows device (also works on linux but lets stay simple) with iis and sql server and you shouldn't have any problems with it....

**Comment by ManzoorPK** [comment]
when i upload any new control to hosting its not showing anything. 
any suggestions
