### ISSUE TITLE
Compound/composite keys and slickgrid

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#279]
I didn't see anything in the guide about interacting with tables with Compound or Composite keys. Since SlickGrid expects a single column to be primary/unique, it blows up as soon as the table has duplicates in one of the columns marked as PrimaryKey in the row class (or possibly the IIdField?)

Have any examples for how to get Serenity to generate an auto-incrementing fake id column for SlickGrid to use?

Thanks!

**Comment by volkanceylan** [comment]
What about adding an expression field to row concatting your composite key values, and using it as ID field. Another option is to add an identity column to table if possible, you dont have to make it primary key.

**Comment by volkanceylan** [comment]
Another option is to use a fake id client side like i did in GridEditor base class.

**Comment by volkanceylan** [comment]
Latest template has a view without ID sample

**Comment by wldkrd1** [comment]
Using an expression field fixes the grid view, create/edit dialog and inserts write to the db, but updates and deletes fail with 'Record not found' exception. E.g. from the repository's Retrieve() call, request.EntityId = '3.1.1' which succeeds, but then on Delete(), request.EntityId = 3 which then throws that exception when Process() is called. Any idea what I'm missing?

Thanks!

**Comment by volkanceylan** [comment]
Check IdProperty on dialog.cs

**Comment by wldkrd1** [comment]
`[IdProperty(RequirementScriptRow.IdProperty)]
    [FormKey("Review.RequirementScript"), LocalTextPrefix(RequirementScriptRow.LocalTextPrefix), Service(RequirementScriptService.BaseUrl)]
    public class RequirementScriptDialog : EntityDialog<RequirementScriptRow>
    {
        protected RequirementScriptForm form;
        public RequirementScriptDialog()
        {
            form = new RequirementScriptForm(this.IdPrefix);
        }
    }`
Looks ok, RequirementScriptRow.IdProperty resolves to "Id" which is the correct column. Here's the json it retrieves when the dialog loads:
`{"Entity":
	{
	"RequirementId":3,
	"ScriptId":1,
	"OsId":1,
	"Id":"3.1.1"
	}
}`

**Comment by volkanceylan** [comment]
Why request.EntityId is 3 on delete then? There must be RequirementId left somewhere. Did you transform T4.

**Comment by wldkrd1** [comment]
Yeah...can't seem to find it. Clean, rebuilt solution, Transformed T4, built Script project. Same problem. Searching solution for RequirementId, not seeing it anywhere it shouldn't be. I'll try again tomorrow. Thanks for the help!

**Comment by wldkrd1** [comment]
Still not sure what's going on. Here's the json being passed around when opening the Edit dialog.

Request: `{"EntityId":"3.1.2"}`

Response: `{"Entity":{"RequirementId":3,"ScriptId":1,"OsId":2,"Id":"3.1.2"}}`

Update: `{"Entity":{"RequirementId":"3","ScriptId":"1","OsId":"2","Id":3},"EntityId":3}`

**Comment by wldkrd1** [comment]
Aha, found it. Serenity.Externals.js line 587:
var v = parseInt(id, 10);
is converting "3.1.2" into 3.

You're more familiar with this so perhaps you can suggest a fix for handling strings as Id fields.

**Comment by volkanceylan** [comment]
I'll have a look into this, definitely a bug

**Comment by wldkrd1** [comment]
Forcing it to an int (e.g. 312) still causes problems on update/delete, this time the generated SQL looks like this and it complains that 0 rows were affected (Expected 1)

`exec sp_executesql N'UPDATE [dbo].[RequirementScript] SET [RequirementID] = @p1, [ScriptID] = @p2, [OS_ID] = @p3 WHERE (cast(RequirementID as varchar(20)) + cast(ScriptID as varchar(20)) + cast(OS_ID as varchar(20)) = @p4)',N'@p1 int,@p2 int,@p3 smallint,@p4 nvarchar(4000)',@p1=3,@p2=2,@p3=2,@p4=NULL`

Maybe using an Expression for the Id column isn't the best route...I could just add an Identity column on the db.

**Comment by volkanceylan** [comment]
Yes, adding an extra ID column shouldn't hurt but there are some who use tables with string IDs, this bug would affect them too, so i'll try to resolve it anyway. Thanks.
