### ISSUE TITLE
Changing the logo .png file path in site.membership.less breaks Styles

### ISSUE THREAD

**Issue by TheColonel2688** [volkanceylan/Serenity#2792]
I am trying to change this line in site.membership.less

```
.logo {
            margin: 0 auto 20px auto;
            width: 128px;
            height: 128px;
            background: transparent url(images/serenity-logo-w-128.png) no-repeat center center;
        }
```

when I change it to 

```
.logo {
            margin: 0 auto 20px auto;
            width: 128px;
            height: 128px;
            background: transparent url(images/betz-logo-200.png) no-repeat center center;
        }
```

rebuild and run and it breaks the styles for main layout (after login), but login page works correctly. breaks as in no CSS loads, just HTML.

Then if I change it back to the default, the main layout style stays broken. So to fix the problem I have to do a GIT undo. I have repeated this process several times, with the same result.

I have not a clue what is causing it. 

![image](https://user-images.githubusercontent.com/8753759/31943697-82097ec6-b897-11e7-9f18-2fa6f18766df.png)

**Comment by volkanceylan** [comment]
It might be file permission issue, check permissions.
