### ISSUE TITLE
Missing left join in generated SQL

### ISSUE THREAD

**Issue by gdeacon** [volkanceylan/Serenity#2793]
I've been trying to figure out a way to extract some "detail" data from a set of tables that have a Master/Detail relationship.

Programs MASTER has many ProgramVendors DETAIL.  I want to display the ProgramVendor has a field called Primary to signify it as the primary vendor for the program.  Here's the fields of both tables
ProgramVendor
Id	int	
VendorId	int	
VendorContact	nvarchar(50)	
SubmittedBy	nvarchar(50)	
[Primary]	bit	
ProgramId	int	FK to Program Table

Programs
id	int
businessKey	varchar(30)
effOrderStart	datetime	
effOrderEnd	datetime	
effShipStart	datetime	
effShipEnd	datetime	
notes	nvarchar(MAX)
created	datetime	
createdBy	varchar(50)
modified	datetime	
modifiedBy	varchar(50)
CompanyId	int	
ProgramTypeId	int	
ProgramTimeFrameId	int	
ProgramTermsId	int	
ProgramDealClassId	int	
ExcludeMonthEndCalc	bit	
IsActive	bit	

In my ProgramRow.cs class I defined this field and this class level join
    [LeftJoin("jProgramVendor", "[dbo].[ProgramVendor]", "T0.Id = jProgramVendor.ProgramId")]
    public sealed class ProgramsRow : Row, IIdRow, INameRow
    {
          ....
        [DisplayName("Primary Vendor"), ForeignKey("[dbo].[Vendor]", "id"), Expression("jProgramVendor.VendorId"), NotMapped]
        [LookupEditor(typeof(VendorRow))]
        public Int32? PrimaryVendor
        {
            get { return Fields.PrimaryVendor[this]; }
            set { Fields.PrimaryVendor[this] = value; }
        }

   }
The join works fine in SQL server but when I look at the generated SQL it is not present at all when the grid is displayed.
SELECT TOP 100 
T0.[id] AS [Id],
T0.[businessKey] AS [BusinessKey],
T0.[effOrderStart] AS [EffOrderStart],
T0.[effOrderEnd] AS [EffOrderEnd],
T0.[effShipStart] AS [EffShipStart],
T0.[effShipEnd] AS [EffShipEnd],
T0.[notes] AS [Notes],
T0.[created] AS [Created],
T0.[createdBy] AS [CreatedBy],
T0.[modified] AS [Modified],
T0.[modifiedBy] AS [ModifiedBy],
T0.[CompanyId] AS [CompanyId],
T0.[ProgramTypeId] AS [ProgramTypeId],
T0.[ProgramTimeFrameId] AS [ProgramTimeFrameId],
T0.[ProgramTermsId] AS [ProgramTermsId],
T0.[ProgramDealClassId] AS [ProgramDealClassId],
T0.[ExcludeMonthEndCalc] AS [ExcludeMonthEndCalc],
T0.[IsActive] AS [IsActive],
jCompany.[Name] AS [CompanyName],
jProgramType.[Value] AS [ProgramTypeValue],
jProgramTimeFrame.[Value] AS [ProgramTimeFrameValue],
jProgramTerms.[Value] AS [ProgramTermsValue],
jProgramDealClass.[Value] AS [ProgramDealClassValue] 
FROM [dbo].[Programs] T0 
LEFT JOIN [dbo].[Company] jCompany ON (jCompany.[Id] = T0.[CompanyId]) 
LEFT JOIN [dbo].[ProgramType] jProgramType ON (jProgramType.[Id] = T0.[ProgramTypeId]) 
LEFT JOIN [dbo].[ProgramTimeFrame] jProgramTimeFrame ON (jProgramTimeFrame.[Id] = T0.[ProgramTimeFrameId]) 
LEFT JOIN [dbo].[ProgramTerms] jProgramTerms ON (jProgramTerms.[Id] = T0.[ProgramTermsId]) 
LEFT JOIN [dbo].[ProgramDealClass] jProgramDealClass ON (jProgramDealClass.[Id] = T0.[ProgramDealClassId]) 

I know that join will give me records for all the ProgramVendors for the Program.

Is there a better way to slice out data from a detail table to display on the master grid?  I've searched and searched and tried overiding the OnReturn of MyListHandler class to fetch what I want etc with no luck.

If this can't be done so be it I will tell the client we'll have to do some work-around etc.  But I'm at a loss.

Why is the class level join not sowing up and if there's a better way I'm all keyboard.
-Garrett

**Comment by Zahar661** [comment]
The columns added PrimaryVendor?

**Comment by gdeacon** [comment]
Yes I added a new field in the ProgramsRow for the PrimaryVendor that is not mapped to the Programs Table ... see code snippet...

        [DisplayName("Primary Vendor"), ForeignKey("[dbo].[Vendor]", "id"), Expression("jProgramVendor.VendorId"), NotMapped]
        [LookupEditor(typeof(VendorRow))]
        public Int32? PrimaryVendor
        {
            get { return Fields.PrimaryVendor[this]; }
            set { Fields.PrimaryVendor[this] = value; }
        }

Perhpas I'm not declaring the attribute correctly but the name of the leftjoin is jProgramVendor.

Thank you for your response and help

**Comment by volkanceylan** [comment]
He is asking if you added it to "Columns", invisible foreign fields are not loaded by grid by default. Search for "getIncludeColumns" in source to force load a invisible property when needed.

**Comment by gdeacon** [comment]
Is there an example of how to properly specify the "columns"  is it part of the LeftJoin attribute?
