### ISSUE TITLE
Can't find enum type error while using serenity report template

### ISSUE THREAD

**Issue by djog** [volkanceylan/Serenity#2794]
I am getting Can't find enum type! error while using report template! Not able to figure out what's going on. 
Trying to use the enum type for the combo box dropdown list on a report criteria screen that uses the Serenity report template.

Followed the same procedure as in the tutorial to create the .cs file where I define the enums. However, I am using their report template and not sure what else I have to do to make it work with the template. I transformed ALL T4 templates and rebuilt the project as well. No luck.

I am using VS 2015 update 3
Type Script 2.5.2

Would appreciate any clue on this!

Thanks.

**Comment by volkanceylan** [comment]
Check enum namespace, check that it is used somewhere, check case, make sure namespace is PascalCased and is under your root namespace, e.g. MyProject.

**Comment by kcvincent** [comment]
The  "Transform ALL T4 Template" would not compile ENUM to server.type.tt name.ts, If the program just use the enum type at the Report Sub System.
