### ISSUE TITLE
BUG  Report : When ScriptBundling is enabled,  when host with IIS-SubAppllaction  bundle path error

### ISSUE THREAD

**Issue by 19317362** [volkanceylan/Serenity#2795]
ASP.NET CORE version, when hosted with IIS as sub-module, When ScriptBundling( name "CoreApp" in my test) is enabled via modify the config file "appsettings.json",  DynaJS.axd bundled with errors.
The config if IIS looks like this (copy to  address bar to view):

https://github.com/19317362/dotnet-win32-service/raw/master/20171021160856.png

In this way, http://localhost/  is the default Site of IIS. http://localhost/CoreApp is Serenity WEB APP
http://localhost/CoreApp/DynJS.axd/Bundle.Libs.js?*** give the following error.

//
//!!!ERROR: File  
...\PublishOutput\wwwroot\CoreApp/Scripts/pace.js is not found!!!!
//

//!!!ERROR: File 
.....\PublishOutput\wwwroot\CoreApp/Scripts/rsvp.js is not found!!!!
//

Then a traced into System.Web.Hosting.HostingEnvironment.MapPath, 
Modify to add log like this

            var pp = Path.Combine(host.WebRootPath, path);
            log.LogWarning($"MapPath {path} => {pp}");
            return pp;
The log looks like:
MapPath **CoreApp/**Scripts/pace.js => e:\lock\dcms\App\HiLock.Web\bin\Release\PublishOutput\wwwroot\**CoreApp/**Scripts/pace.js

The output sould without "CoreApp/".

I don't know how to fix this in my APP, So , I come here.

Best regards.

**Comment by 19317362** [comment]
It seams not easy to fix.  Maybe System.Web.VirtualPathUtility.ToAbsolute and Serenity.Web.ScriptBundleManager need to be adjust.
I tried to fix like this:
1. Add a function to System.Web.VirtualPathUtility
        public static string ToAbsoluteBundle(string contentPath)
        {
            var context = Dependency.Resolve<IHttpContextAccessor>().HttpContext;
            if (context.Request.PathBase != context.Request.Path)
            {
                return GenerateClientUrl(context.Request.Path, contentPath);
            }
            else
            {
                return GenerateClientUrl(context.Request.PathBase, contentPath);
            }
        }
2. Modify Serenity.Web.ScriptBundleManager  to call the new added function
--   sourceUrl = VirtualPathUtility.ToAbsolute(sourceUrl);
++ sourceUrl = VirtualPathUtility.ToAbsoluteBundle(sourceUrl);

It seems ok. Not full tested.

**Comment by 19317362** [comment]
@volkanceylan  I have tested on  latest 3.3.2. the issue is still there.
My modify works but breaks bundle.

**Comment by volkanceylan** [comment]
Asp.net core doesnt support sub applications, nor virtual paths, it works with IIS through reverse proxy.

**Comment by 19317362** [comment]
@volkanceylan For my test , it works fine.
The parent site is ASP.NET 4.0 managered. The sub application is asp.net core. It works. 
In the document of MS, it says "Note: Setting the .NET CLR version to No Managed Code is optional. ASP.NET Core doesn't rely on loading the desktop CLR."

For my case , it works. Just the path issue.
It's because I'm in China. The port of 80 is restrict to open. I must use the app as sub application to share the 80 port. :(
I'm very sad of living in China. No google, no facebook, very slow to github, very very slow to nuget...

If you think this is not a problem, I'll try to fix myself.
Many thanks to your Great framework.

**Comment by volkanceylan** [comment]
OK, sorry i see now, i thought ASP.NET core doesn't support virtual paths but seems like i'm wrong. I think problem is mapping in DynamicScriptMiddleware doesn't take virtual path into account. Will try to handle that somehow.

**Comment by volkanceylan** [comment]
Try updating to 3.3.3, it should be resolved

**Comment by 19317362** [comment]
Thank you very much. I'll try 3.3.3 later. 
I'm totally wrong on trying to deal with this. DynamicScriptMiddleware is skipped by me.

**Comment by 19317362** [comment]
@volkanceylan  3.3.3 works fine!  
Thanks a lot.

**Comment by iquirino** [comment]
I'm with this error with the latest version.

**Comment by in32bit** [comment]
We are having this error also with the latest version.
