### ISSUE TITLE
WepAPI handling in Serenity

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2796]
I have added a third party control with Serenity. The control will get data from API. Everything works fine but it does not fire the API. 
I wanted to know if there is a control that prevents application from running WebAPI.

Thank you

**Comment by kilroyFR** [comment]
I personnally using 3 personal webapis (rest) with no problemo. I dont think problem comes from setenity

**Comment by volkanceylan** [comment]
Serenity doesnt use WebAPI nor has any prevention to use that. See WebAPI docs on how to add it to existing Asp.Net MVC project.

**Comment by ms4hafiz** [comment]
Thanks.
Actually there was issues with configuration files and views.

**Comment by tmartinscopo** [comment]
Hi @ms4hafiz , can you share some example how to get data from another API ?
