### ISSUE TITLE
Programmatically change the value of lookupeditor

### ISSUE THREAD

**Issue by FGLedesma** [volkanceylan/Serenity#2797]
Hi,
How is the right way to change the value of a lookupeditor? ... I mean
if (this.form.anyformfieldvalue= xxx) {
    this.form.mylookupeditor.value = "String Value of related data"
}
I tried the above but it just put no value in the lookup.
In addition, I see no way to set the underlying id of the lookupeditor.

Thanks a lot in advance for your kindly replay.

**Comment by sweetnini87** [comment]
Try this..

if (this.form.anyformfieldvalue= xxx) {
this.form.mylookupeditor.value = this.form.mylookupeditor.get_items ().filter (x=>x.text ==="string value of related data")[0].id;
}

If i understood you correctly

**Comment by FGLedesma** [comment]
Hi sweetnini87, thanks a lot! It works perfectly.
Again, thanks for your kindle attention on the matter.

**Comment by GreenUtil** [comment]
I guess 

`this.form.mylookupeditor.value = this.form.mylookupeditor.get_items ().filter (x=>x.text ==="string value of related data")[0].id;`  

should be

`this.form.mylookupeditor.value = this.form.mylookupeditor.get_items ().filter (x=>x.text ==="string value of related data")[0].id.toString();`
