### ISSUE TITLE
Notify AfterSave 

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#2798]
Friends! How to show Notify After Save?
Something like:
```
 protected override void AfterSave()
            {
                base.AfterSave();
                var d = RERow.Fields;
                 var re = Connection.TryFirst<RERow>(d.DogovorId == 
                    Row.DogovorId.Value);
                        if (re == null)
                            throw new ValidationError("InvalidPayDebet", "Summa",
                            "The payment was saved, but the efficiency calculation was not found for checking the limits !!!");
.........
            }
```
when call "throw new ValidationError", the saving is canceled (((

**Comment by Estrusco** [comment]
Q.notifyInfo("your message", "title");

**Comment by Zahar661** [comment]
@Estrusco Hi!
Q.notifyInfo ("your message", "title") is not in the xyzRepository.cs

**Comment by Estrusco** [comment]
If you want send message from server side, you must return it with response. If you throw an exception you stop the execution of current elab.

**Comment by Zahar661** [comment]
how can it be returned?

**Comment by karimhyatt** [comment]
```
XXXService.MyBackEndMethod({
     EntityId: realthis.entity.DisclosureId
},
response => {
    Q.NotifyInfo(reponse.myMessage)
});
```

Make sure you define and instantiate an appropriate response in your method. See the examples and other issues of how to do this, There are MANY examples.

**Comment by Estrusco** [comment]
Write a method in endpoint, with return type derived from ServiceResponse, compile, transform T4 and then use it as @karimhyatt says.
You can start fom example in BasicSamples -> Dialogs -> SerialAutoNumber https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/SerialAutoNumber

**Comment by Zahar661** [comment]
@Estrusco @karimhyatt  Thanks, I understood, about an example with SerialAutoNumber did not think, I will try!
