### ISSUE TITLE
The command "dotnet sergen mvct" exited with code -532462766.

### ISSUE THREAD

**Issue by TheColonel2688** [volkanceylan/Serenity#2799]
Edit: See Next Comment Below for updated status
_______________________________________________________________________________________________
I am receiving the following error on build. It does not halt the build. Could someone tell me what is happening and how I can fix it.

I am running Windows 10, VS 2017.4 using serenity for .Net Core. Serenity Version 3.2.2 (Updating to 3.3.1 breaks my grid pages....)

When I create the project, I did not have Typescript 2.5 installed. I have since installed it. 

> 1>Transforming MVC at: C:\Users\Ben-Laptop\OneDrive\Software Projects\BetzIntranetApplication\BetzIntranetApplication\BetzIntranetApplication.Web\Imports\MVC
> 1>
> 1>Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
> 1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
> 1>   at System.Diagnostics.Process.Start()
> 1>   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> 1>   at Serenity.CodeGenerator.TSTypeLister.List()
> 1>   at Serenity.CodeGenerator.Program.<>c__DisplayClass0_0.<Main>b__1()
> 1>   at Serenity.CodeGenerator.Program.Main(String[] args)
> 1>C:\Users\Ben-Laptop\OneDrive\Software Projects\BetzIntranetApplication\BetzIntranetApplication\BetzIntranetApplication.Web\BetzIntranetApplication.Web.csproj(70,5): warning MSB3073: The command "dotnet sergen mvct" exited with code -532462766.
> 1>BetzIntranetApplication.Web -> C:\Users\Ben-Laptop\OneDrive\Software Projects\BetzIntranetApplication\BetzIntranetApplication\BetzIntranetApplication.Web\bin\Debug\netcoreapp2.0\BetzIntranetApplication.Web.dll
> 1>
> 1>Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
> 1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
> 1>   at System.Diagnostics.Process.Start()
> 1>   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> 1>   at Serenity.CodeGenerator.TSTypeLister.List()
> 1>   at Serenity.CodeGenerator.Program.<>c__DisplayClass0_0.<Main>b__1()
> 1>   at Serenity.CodeGenerator.Program.Main(String[] args)
> 1>C:\Users\Ben-Laptop\OneDrive\Software Projects\BetzIntranetApplication\BetzIntranetApplication\BetzIntranetApplication.Web\BetzIntranetApplication.Web.csproj(77,5): warning MSB3073: The command "dotnet sergen servertypings" exited with code -532462766.
> 1>Done building project "BetzIntranetApplication.Web.csproj".

**Comment by TheColonel2688** [comment]
1 year later I still have this issue.

**Comment by volkanceylan** [comment]
TypeScript has ordering issues, unless you add /// references, this is stated clearly in guide
