### ISSUE TITLE
How to create dynamic editor ?

### ISSUE THREAD

**Issue by jimzarthur** [volkanceylan/Serenity#280]
Hello,

Do you have any sample to create editor like option or checkbox dynamically ? How to do this? I have read serenity developer guide and not found any solution to do this. Thanks

**Comment by volkanceylan** [comment]
What does it mean? What are you trying to do?

**Comment by jimzarthur** [comment]
I mean i want to create dynamic views using serenity editor in runtime. Do you have any solution or sample to do this?

**Comment by volkanceylan** [comment]
You can override GetPropertyItems of a dialog and return a dynamic list of items. Or create widgets manually.

**Comment by jimzarthur** [comment]
Hello volkan,

So do you have any sample? It will be more helpful. Thanks for your fast reply.

**Comment by volkanceylan** [comment]
No, i don't have a sample.
