### ISSUE TITLE
3.08 -> 3.3.3 images getting 404'd

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#2800]
I assume due to this change: 

> convert most used toolbar buttons, pager buttons, back buttons, dialog close button, quick search icon, select2, date picker and filter panel images to data uris image to data uris

URL looks like https://myserver.mydomain.com/Content/serenity/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAKnRFWHRDcmVhdGlvbiBUaW1lAE1pIDEgT2t0IDIwMDMgMDA6MDk6MTQgKzAxMDDXmCS5AAAAB3RJTUUH0wkeFgk243t37gAAAAlwSFlzAAALEgAACxIB0t1+/AAAAARnQU1BAACxjwv8YQUAAAG+SURBVHjapZK/TxRREMe/b0GC5FBJjBUWFHQ2XMe/QGHlf6HGBBptbGywM7EVO0ujMSQ02huLq+wsTK64BC63wHHe/ngzb5iZhUDMakh4m83bnd35zme+b4BrrtAWvPduoXd/aXlNkiClhMQJ/eHg+9Gzav3vf2fbBCQFPN94jAnlqLnA4LCPN58/tRK0C4iAhTCO+6hoipMq91jbytoJFF2Si6REnizc7oET3N252YNiWyKSqkq2IibABFKBoE5lWVhdfD3XM6HGG0HxkrpuYvfjqrzYeNJU1ERLntIxhuVvRKpRxQKdG0uYCx3UVGBa/8H7L18x2DoOTmBqExppzwcuYpVjqkAUQRzBSpFP9zU+0JsRo5IRX7QgelQ1l26Y9WzYnNiTI1fNUeq77eaHFfR2zwUskE8OMK5GjWF6zcwGJ7Ekq1gU0Z+NwKonlotBuvN2/meQxhxtX4NhefPRw9vjMvfK45MSH/Z+jBSsb9/ljIC2pesER0/LB5ePpqNuz2e31g55eFZV7yi/6lfpapNoLdVUOq737Pt/5qBtEgs9KuvdxEgJzk27GoEatLP7Daxm+dCwTeI/EK67TgGbD2DNvD1ymgAAAABJRU5ErkJggg==

What might I need to change/enable to get the images to load (close, minimize, restore, update, save and close, close, etc)?

**Comment by euclidesgc** [comment]
Try execute "Update-Package Serenity.Web -reinstall" on Package Manager Console.
Works to me!

**Comment by volkanceylan** [comment]
You might have problem with a https conversion filter, we don't know such error at serenity.is/demo

**Comment by wldkrd1** [comment]
Reinstall didn't fix it, switching to http didn't fix it either. :-(

**Comment by wldkrd1** [comment]
This request results in a 400 Bad Request when loading a grid:

http://myserver.mydomain.com/Content/serenity/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAOCAYAAAAmL5yKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuNvyMY98AAAIwSURBVDhPhZPbS5NxGMf3F3VRgRQYQol5VhoFilKpNdHsQjLUmM45db7q3sYO2uZcNvMYli7PbuTGxma6NEkrMerCu1V3deH69PqS5duCLr7w8Dzfw8X391MB/0XN+E3EJUEak2+/hy/f4/g+ziNGjFR7yyl6XMAlVza5tnQ0I1e5PliMONMlUf9hsPd1F3tMRB+oxxw14nxlwbVhpU/aWVa7MEXaaQ82o7bmYZ42SZJjBp+/xbGt9dATMeDZctC7buJBzIz1ZTditAMhpMcQ1NL0op6c7gyME+1Kg8W9WbT+Ozzc7MUZs9AdbqNiuJS0tjOc1Z7mVN0J8sVMsoR0dENahVg2EAKtGAPNcmJnUE9RnxrLgqgg5uqyqHPWKnZHUJWPlqB25pBvvSgnOXx2aa8kWabMHCQOWPngw7+7xPLbBRbfzDL3+jmqxe055rdmmNnw4l2f4tnqJIkfCRY+eZOMRmIeit1qOSxDSCNPyFASjjC046I13CiNf3buiEOusifUJrXSQd30bW71VyqFhxh/58EgiXUrdykdV3PlUR6FjkyqJsoQAnq5UmOohcv2Agb9bqV48v0o+mA9w9suudKBTbui0paVBrnSMk8J1X2V7Mf3/zLYGePeci0DGza5UtuaifvRToSwAZ2vgeonFRSas6mya1jfXZMkv17icbhXHdQ8vYFm7BoXhFTO6VNIaTzJ+aZUNLZy3EsuOfmIn2RwiMOPU9ZfKo3JNyVQ/QSSN361nc45cgAAAABJRU5ErkJggg==

**Comment by volkanceylan** [comment]
No idea, try turning off bundling

**Comment by euclidesgc** [comment]
When I updated the version there were several errors as well. The login page is empty.
Through the Chrome (F12) console I noticed that several files were missing.
I also noticed that the files that were missing were actually in the ".. \ packages \ Serenity.Web.3.3.3 \ content \ Content \ serenity" folder and others.
Two alternatives at this point:
1 - Copy the files from these folders to the right location in the project
2 - Try to reinstall the packages to see if it worked this time.

The second option worked for me!

Excuse me, my English is not very good.
I used Google Translator this time, I'm Brazilian.

**Comment by volkanceylan** [comment]
@euclidesgc, if you are using .net core, you need to run "dotnet sergen restore" after updating packages, as .net core nuget doesn't support installing content into project folders

**Comment by wldkrd1** [comment]
No change when bundling is disabled. Updated to 3.3.4, no change. Running locally instead of publishing to IIS, no change.

Creating a new project and running it, images load correctly. 

Any requests to data:image result in 404 or 400...what's the technology behind that?

**Comment by wldkrd1** [comment]
And the answer is: data-uri - encoding the image files directly in the CSS instead of making a network call.
So, why is it translating this to a network resource (pre-pending /Content/serenity/ to data:image)
Very strange...

**Comment by wldkrd1** [comment]
The CSS is specifying /Content/serenity/ and I had BundleOptimizations = true in code. Turned that off and images show up fine.

**Comment by volkanceylan** [comment]
That's ASP.NET bundling bug with data URI's, in addition to many other that system has, you shouldn't use that with Serenity, we have a better one

**Comment by wldkrd1** [comment]
Noted, thanks!
