### ISSUE TITLE
"Build -> Transfrom All Templates" not possible in ASP.net Core

### ISSUE THREAD

**Issue by TheColonel2688** [volkanceylan/Serenity#2801]
The Developer's Guide says to perform a template transform on the T4 templates. However this is not possible in ASP.net Core.

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/adding_a_movie_kind_field.html

It does say that "You might not have this error with ASP.NET Core version as it auto transforms T4" but it doesn't make it clear that it is not possible to perform this step with ASP.NET Core.

Could this be made clearer?

**Comment by mahmuthaktan** [comment]
For .net core it automaticaly transforms.

**Comment by TheColonel2688** [comment]
Yes I know. The point is that it does not make it clear in the Guide. It should say something to the effect of "ASP.net Core performs this transform automatically. It cannot be done manually.

**Comment by volkanceylan** [comment]
It says in a lot of places, no need to repeat it, read guide from top to bottom.

**Comment by volkanceylan** [comment]
Running T4 Templates (.tt files, ASP.NET MVC Version)

In prior sample we harcoded field names like Description, Storyline etc. This may lead to typing errors if we forgot actual property names or their casing at server side (javascript is case sensitive).
Serene contains some T4 (.tt) files to transfer such information from server side (rows etc in C#) to client side (TypeScript) for intellisense purposes.
Before running these templates, please make sure that your solution builds successfully as templates uses your output DLL file (MovieTutorial.Web.dll) to generate code.
After building your solution, click on Build menu, than Transform All Templates.
Running T4 Templates (ASP.NET Core Version)

You don't have to transform templates in ASP.NET Core version. Serene does it automatically on build.
Actually, there isn't any T4 file in ASP.NET Core version.
So from now on, when we say transform templates, just build your project (if you use ASP.NET Core version).
It is also possible to open a command prompt in project directory and type dotnet sergen t to transform templates manually.
