### ISSUE TITLE
Running sergen on table with more than 350 columns

### ISSUE THREAD

**Issue by Gone4Coding** [volkanceylan/Serenity#2802]
![image](https://user-images.githubusercontent.com/18728780/31909405-eafea66a-b831-11e7-879a-cc83103acf64.png)

**Comment by brunobola** [comment]
Can you guys give a hint on this error ?
Is it a limitation of sergen ?

I ask because i'm making a study and need to have more columns also :(

**Comment by volkanceylan** [comment]
That is a default limit of Scriban template engine, will increase that in next version.
