### ISSUE TITLE
Initializing dialog fields after clicking "New" button from a grid

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#2804]
Trying to follow the samples to populate dialog with initial values. Some values get initialized, some don't. In my *Grid.ts, I have:

```
protected addButtonClick() {
            var request = RequestRow.getLookup().items.filter(x => x.RequestId === this.requestID)[0];
            this.editItem(<EmailRow>{
                RequestId: this.requestID,
                EmailTo: request.Email,
                EmailFrom: request.Username,
                InsertDateTime: Q.formatDate(new Date(), 'MM/dd/yyyy HH:mm'),
                InsertUser: Authorization.userDefinition.Username
            });
        }
```

EmailTo and EmailFrom do not get populated. Am I looking up the "request" object correctly using the "RequestRow.getLookup().items.filter(x => x.RequestId === this.requestID)[0]" call? Many thanks in advance.

**Comment by Zahar661** [comment]
in RequestRow  EmailTo and EmailFrom LookupInclude?

**Comment by Zahar661** [comment]
and  
`var request = RequestRow.getLookup().itemById[this.requestID];`

**Comment by c9482** [comment]
That was exactly it (forgot the LookupInclude attribute)!. Thank you very much.
