### ISSUE TITLE
Open page in a new tab

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2806]
Any way on how to open the page in new tab. I have the following menu items, I want each page to be opened in new tab.
![image](https://user-images.githubusercontent.com/20435849/31933927-d2587a94-b8bf-11e7-9b45-3911cf925592.png)

**Comment by Zahar661** [comment]
[assembly: NavigationLink(1505, "Region", typeof(RegionController),Target = "_blank")]

**Comment by ms4hafiz** [comment]
Thank you @Zahar661
