### ISSUE TITLE
Which files need to upload when new control done.

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2807]
Hello Friends. 

i hosted sernerity on a live MVC supported shared hosting. its working fine. but now when i create a control on localhost and then try to upload it on server its showing empty form. 

can any one tell me what files i need to upload to show the full form?

**Comment by Zahar661** [comment]
Minimum
bin\myProject.Web.dll
bin\myProject.Web.pdb
\Scripts\site\
\Content\site\site.css

form template if available

**Comment by ManzoorPK** [comment]
still form showing like this 
![form](https://user-images.githubusercontent.com/2439608/31938062-d782d45a-b8cf-11e7-9f73-78cfc2790ce3.png)

**Comment by ManzoorPK** [comment]
its worked after rebuild and option the mentioned files.
