### ISSUE TITLE
Hide records from grid based on a field value

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2808]
Hi;
I would like to hide records from user on a condition that a specific field has a specified value like 1 for example. This is in addition to multi-tenancy but it maybe possible through multi-tenancy as well.  But i want the records to be viewed by admin users.

Thank you

**Comment by Zahar661** [comment]
in xyz.Repository

```
 private class MyListHandler : ListRequestHandler<MyRow> {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                if (!Authorization.HasPermission("Admin"))
                {
                    query.Where(fld.FildName == 1);
                }
            }
        }
```

**Comment by ms4hafiz** [comment]
thank you @Zahar661
