### ISSUE TITLE
Can't seem to create a Editor

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#2809]
What am i doing wrong ?

[Editor.ts]

`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace StudyCases.Estudos {

    @Serenity.Decorators.registerClass()
    export class AblationIndexInParoxysmalAfLIPVEditor
        extends Common.GridEditorBase<AblationIndexInParoxysmalAfLIPVRow> {
        protected getColumnsKey() { return "Estudos.AblationIndexInParoxysmalAfLIPV"; }
        protected getDialogType() { return AblationIndexInParoxysmalAfLIPVDialog; }
        protected getLocalTextPrefix() { return AblationIndexInParoxysmalAfLIPVRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        protected getAddButtonCaption() {
            return "Adicionar LIPV";
        }

        protected validateEntity(row, id) {

            if (!super.validateEntity(row, id))
                return false;

            //Colocar campos dependentes caso necessário
            //row.AblationIndexInParoxysmalAfId =  id;
            
            return true;
        }
    }
}`

[Form.cs]
![image](https://user-images.githubusercontent.com/10889019/31943262-189ab972-b8c0-11e7-94dc-1838a2d214a0.png)

I'm tired what can be the problem please....

**Comment by Zahar661** [comment]
in Imports\ClientTypes  add Estudos.AblationIndexInParoxysmalAfLIPVEditorAttribute.cs

```
namespace StudyCases.Estudos
{
    public partial class AblationIndexInParoxysmalAfLIPVEditorAttribute : CustomEditorAttribute
    {
        public const string Key = "StudyCases.Estudos.AblationIndexInParoxysmalAfLIPVEditor";

        public AblationIndexInParoxysmalAfLIPVEditorAttribute()
            : base(Key)
        {
        }
    }
}
```

**Comment by brunobola** [comment]
Thanks a million i'm used to make the project from scrtch, so i din't prepare it for user types... My bad, sorry @Zahar661
