### ISSUE TITLE
how to load script data which is having differnt permissionkey.. 

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2810]
@volkanceylan 
@Estrusco 
@VictorTomaili 
im having two permissionkeys as belows
1.Enquiryall---Assigned modules-Enquiry
2.DSL_Admin---Assigned modules-Employee
when im facing problem
Role    |  permissionkey
sales   |   Enquiryall

When im logging by sales im unable to load New Enquiry and Edit link 
i think it is because i having AssignTo[belongs to Employee ]..

during debugging it showing error as below.
unable to load script data:Enquiry.lookup.EmployeeDeatils
please,suggest me how to deal with.thank you..

**Comment by JohnRanger** [comment]
Hi Andy575,

I define all permissions centrally in one separate class and then use them where required.

With this approach, would it not be possible for you to create a "Sales" role which holds all required permissions and then assign this role to the "Sales" People? 

Or do I missunderstand your challenge?

With Kind regards,

John

**Comment by ANDY7575** [comment]
hello @JohnRanger 
i understand what u just said but,
if i give all permission with employee, employee will be displayed in navigation menu,
i dont want employee to be displayed on my navigation??
please suggest if any...

with Kind regards,
Aniket

**Comment by Zahar661** [comment]
[assembly: NavigationLink(7100, "Northwind/Customers", typeof(Northwind.CustomerController), icon: "icon-wallet",Permission= "Customers:Modifi")]

**Comment by volkanceylan** [comment]
You can assign lookups a separate permission.

[LookupScript("SomeLookup", Permission = "?")]

This gives access to lookup to all logged in users.
