### ISSUE TITLE
Many to One Relationship?

### ISSUE THREAD

**Issue by TheColonel2688** [volkanceylan/Serenity#2812]
I have read these
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/allowing_multiple_genre_selection.html

https://github.com/volkanceylan/Serenity/wiki/LinkingSetRelation-Explanation-by-jsbUSMC

These both seem to apply to Many to Many. I would like a Many to One relationship. 

I have a Job and a Quote relationship.

On the Jobs form I would like to be able to select multiple Quotes (if they are not already used) and on the Quotes form I would like to be able to select only one Job.

Is this possible? If so could I have a modified explanation on how to achieve this?

```
        [DisplayName("Quotes")]
        [LookupEditor(typeof(QuoteRow), Multiple = true), NotMapped]
        //[LinkingSetRelation(typeof(MovieGenresRow), "Id", "Id")] // This seems to be many to many
        public List<Int32> QuoteList
        {
            get { return Fields.QuoteList[this]; }
            set { Fields.QuoteList[this] = value; }
        }
```

```
public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public Int32Field CustomerId;
            public Int32Field JobId;
            public StringField Name;

            public Int32Field JobCustomerId;
            public StringField JobJobName;
            public Int32Field JobJobNumber;
            public Int32Field JobStatus;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Betz.Quote";
            }
        }
```

```
        public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public Int32Field CustomerId;
            public StringField JobName;
            public Int32Field JobNumber;
            public Int32Field Status;
            public StringField NameNumber;
            public ListField<Int32> QuoteList;



            public RowFields()
                : base()
            {
                LocalTextPrefix = "Betz.Jobs";
            }
        }
```

**Comment by volkanceylan** [comment]
So linking set relation + dropdown in other form.

**Comment by TheColonel2688** [comment]
I want to be able to handle this in the Jobs form, not the Quotes form. This is a for an easier user experience.

**Comment by judejay** [comment]
Speaking as a complete novice, (I only know some VB, and html), the "serenity guide" is the only place to start. I've got most of my demo web app done, I'm stuck one joining the notes table, to the rest of them. I suspect any waste of the developers time on video, will not be any benefit to most people. If you ask me and no-one did, you need to play to your strengths and finish sergen, It needs to be able to assign relationships between two or more tables. It's almost there, but when I have EXISTING tables that sergen can't pick up the Private key from the foreign, the novice user like me, needs to do joins assign relationships. All the features that you are rich enough, but I will cut most of them. Play to your strengths handling large amounts of data easily.
