### ISSUE TITLE
I want a lookup drop down on top as filter the grid

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2816]
Hello Friends i am trying to read values from database and then want to bind it with dropdown and that dropdown should behave like filter and it should filter the grid i am trying the following code but no dorpdown showing at the top. please help.

         protected createQuickFilters(): void {

        // let base class to create quick filters first
        super.createQuickFilters();

        // get a reference to order row field names

        this.addQuickFilter(
            {
                handler: h => {
                    var request = (h.request as UsersRow);
                    var value = (h.widget as Serenity.LookupEditor).value;

                    if (value != "" && value != null) {
                        request.DisplayName = value;
                        h.active = true;
                    }
                    else {
                        h.active = false;
                    }

                    h.handled = true;
                },
                type: Serenity.LookupEditor,
                field: "DisplayName", // i used dummy field here
                title: "DisplayName"
            }
        );
       
    }
    }

**Comment by ManzoorPK** [comment]
this is showing dropdown now 

          protected createQuickFilters() {
            super.createQuickFilters();
            let fld = Payroll.UsersRow.Fields;
            this.addQuickFilter({
                type: Serenity.LookupEditor,
                field: fld.UserId,
                title: "Select Employee"

            });
        }

BUT NO RECORDS IN IT :(

**Comment by Zahar661** [comment]
Add  UserName in xyzRow
and in "Columns", add QuickFilter and LookupEditor
```
namespace MyProject.myModul.Columns
{
    using Serenity.ComponentModel;
    using System;
    using TSRUTS.Administration.Entities;

    [ColumnsScript("myModul.xyz")]
    [BasedOnRow(typeof(Entities.xyzRow))]
    public class xyzColumns
    {
        [LookupEditor(typeof(UserRow)),QuickFilter]
        public String UserName { get; set; }
        .......
    }
}
```

**Comment by ManzoorPK** [comment]
thank you it worked
