### ISSUE TITLE
difficulty in Adding Column in grid From Another Grid. 

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2821]
hello Guys,
I want my EnquiryGrid to add Column from EnquiryDetailsGrid.
Here is my Try,
protected getColumns(): Slick.Column[] {
            try {
                var columns = super.getColumns();
                var fld = Enquiry.EnquiryDetailsRow.Fields;
                columns.push({
                    field: fld.Status,
                    name: "Status",
                    format: ctx => {
                        var item = ctx.value  //data for that row
             //here im returning Checkbox, I want to data for status Column.
                        return "<input type='checkbox'>"; //should i Bind here 
                                                          
                    },
                });
            } catch (e) {
            }
            return columns;
        }
         any help is appreciated..
thank ..
With kind regards,
Aniket

**Comment by Zahar661** [comment]
EnquiryGrid 1-∞ EnquiryDetailsGrid?  Why not use "Row"?

**Comment by ANDY7575** [comment]
Hello @Zahar661 
Enquiry-PK
EnquiryDetails-Fk

if u understood my question can u Give me Solution edited with above Code.

Thanx
With kind regards,
Aniket

**Comment by TheColonel2688** [comment]
If all you want to do is add a field from another table simply added it is the EnquiryRow.cs,

for example if the field is Status, You will have to adjust varable names accordingly.

If this not what you want then disregard.

```
[DisplayName("Status"), Expression("jEnquiryDetails.[Status]")]
        public String EnquiryDetailStatus
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }

```


then
```
public class RowFields : RowFieldsBase
{
    ....
    public StringField EnquiryDetailStatus;
    ....
}
```

**Comment by ANDY7575** [comment]
@TheColonel2688 
thanx for your efforts..
i did all changes u suggested but im unable to load Status.
After Loading of Grid it shows Alert As multipart identifier JEnquiryDetails could not be found...

**Comment by Zahar661** [comment]
JEnquiryDetails must be declared at the binding field ID  

[Column("EnquiryDetailStatusID"), ForeignKey("[dbo].[MyBase]", "EnquiryDetailStatusID"), LeftJoin("jEnquiryDetail"), TextualField("EnquiryDetailStatusName")]
        public Int32? EnquiryDetailStatusId
        {
            get { return Fields.DogovorId[this]; }
            set { Fields.DogovorId[this] = value; }
        }

[DisplayName("Status"), Expression("jEnquiryDetails.[EnquiryDetailStatusName]")]
        public String EnquiryDetailStatus
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }

**Comment by Zahar661** [comment]
in the Northwind every second field from another table. look how it's done there.

**Comment by ANDY7575** [comment]
@Zahar661 
Actually in this case 
Enquiry is Primary key table-EnquiryID
EnquiryDeatils is foreign key table-EnquiryID  
now tell me how can i use left join on EnquiryDetails..

**Comment by Zahar661** [comment]
```
[DisplayName("State"), Expression("(select top1 status from [EnquiryDetails] AS T1 WHERE T0.EnquiryID = T1.EnquiryID)")]
        public String EnquiryDetailStatus
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }
```

**Comment by ANDY7575** [comment]
working sample..

[DisplayName("State"), Expression("(select status from [EnquiryDetails] AS T1 WHERE T0.EnquiryID = T1.EnquiryID)")]
        public String EnquiryDetailStatus
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }
