### ISSUE TITLE
Hide,show Of Dialog Element By UserRole

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2822]
Hi guys,
Can we access user Role in dialog.ts.
I want to Hide ,show data from same Dialog for Different Role.
or is there any Way ,if there please suggest.
Thank you.
With kind Regards,
Aniket.

**Comment by Zahar661** [comment]
There is no access to the role. There are to permissions.  iAuthorization.HasPermission("permissionName")

**Comment by ANDY7575** [comment]
Thanx @Zahar661 ..in my case My both User l.e 
for role sales n manager have same permission ,so for hiding some data from manager
 im looking for Role checking..

is there any option...
@volkanceylan..  Master Do u have any solution for same...
Thanks,
with Kind Regards,
Aniket

**Comment by Zahar661** [comment]
@volkanceylan asks everyone to use the permissions. 
I did this:
in xyzRow
`[ReadPermission("Orders:Read|Manager|Client")]`
in dialog 
`if (Authorization.HasPermission("Manager"))`

**Comment by ANDY7575** [comment]
Thanx @Zahar661 ..
I  never had Thought of [ReadPermission("Orders:Read|Manager|Client")]..
applying more than 1 Permission..
with Kind Regards,
Aniket..
