### ISSUE TITLE
Cascading with multi select 

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#2823]
Hello All,

i want to apply multiselect cascading on drop down.

`  [LookupEditor(typeof(CountryRow), Multiple = true)]
        public string CNT { get; set; }
   [LookupEditor(typeof(StateRow), Multiple = true, CascadeFrom = "CNT", CascadeField = "CCode")]
        public string STAT { get; set; }`

but it's not working for multiple selection it works for single selection. 
I want to select multiple country and on that selection populate states. 

Please help me how i can achieve cascading with multiple selection. 

Thanks.

**Comment by rakeshpatil20** [comment]
can anybody help on this??

**Comment by volkanceylan** [comment]
Cascade doesn't support multiple.
