### ISSUE TITLE
how to loadform from the grid when some row contains -amount 

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2824]
i have a grid with amount column and some rows contain negative amount i.e (-30)
when i click on editlink of the row it shows the following error and doesn't open the form 

Uncaught Error: The value (-30) from the 'set' method falls outside of the vMin / vMax range
    at Function.error

**Comment by Zahar661** [comment]
in xyzRow or xyzForm
```
[IntegerEditor(MinValue = -99999999)]
public Int32? FieldName ....
```
