### ISSUE TITLE
how to use grids in different criteria?

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2825]
i have student grid with columns s1,s2,s3
and class grid with c1,c2,c3;

and i have to use the same classgrid in some other module with s1,s2,c2,c3;
how to use without creating new column class.

**Comment by ANDY7575** [comment]
Looking for the same ..
Anyone out there..
any help appreciated..
with kind Regards,
Aniket...

**Comment by ANDY7575** [comment]
#2821 
check here u will Get Solution..
