### ISSUE TITLE
Bug in custom quick filter

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2826]
Hi @volkanceylan 
The $Serenity_EditorUtils.saveValue function have a bug.
If there is a date custom quick filter in grid, there is an error,

Uncaught TypeError: Cannot read property 'getEditValue' of null

You can see that in http://serenity.is/demo/BasicSamples/QuickFilterCustomization

**Comment by volkanceylan** [comment]
Thanks, actually that's a bug in sample, not saveValue. Need to clear loadState, saveState, displayText methods as changing type from range to single:

```ts
            (filter as any).loadState = null;
            (filter as any).saveState = null;
            (filter as any).displayText = null;
```
