### ISSUE TITLE
I want to show the save button at bottom of the form how can i do this?

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2829]
I want to show the save button at bottom of the form how can i do this?

![screenshot_2](https://user-images.githubusercontent.com/2439608/32140808-d906e37a-bc8f-11e7-837f-64c51e9093fd.png)

**Comment by davidzhang9990** [comment]
change css style I think.. in .less file

**Comment by dfaruque** [comment]
change

~\Views\Templates\EntityDialog.Template.html

**Comment by Estrusco** [comment]
See here https://github.com/volkanceylan/Serenity/issues/2446
