### ISSUE TITLE
How to use [SortOrder(int, true)] attribute?

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#283]
I have searched the guide but cannot find about it.

[SortOrder(int > What does this int means?, true)]

**Comment by linpiero** [comment]
in entityColumns set SortOrder(1, descending: true) as attribute on Property.
the first parameter "1"  indicates the position of the entity column for which you want to order.
for example:
[BasedOnRow(typeof(Entities.EntityRow))]
    public class EntityColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight, SortOrder(1, descending: true)]
        public Int32 Idobj { get; set; }

**Comment by dfaruque** [comment]
Thank you,
