### ISSUE TITLE
Master/Detail grid hide or show columns

### ISSUE THREAD

**Issue by davidzhang9990** [volkanceylan/Serenity#2830]
![image](https://user-images.githubusercontent.com/23019715/32141130-4aa6cde2-bcb3-11e7-8a0d-892b29c4278c.png)
![image](https://user-images.githubusercontent.com/23019715/32141134-6227d100-bcb3-11e7-80b4-e367f503914a.png)

I want when '类型' change or  default value eql  0  .the detail grid hide columns [ ‘厚度’,'面积','完成面']
when '类型'  change or  default value eql  1 。the detail grid hide columns [ ‘高’,'体积','重量']

**Comment by davidzhang9990** [comment]
like when column 'Type' eql 0，detail grid hide some columns
when column 'Type' eql 1,detail grid hide other some columns

**Comment by dfaruque** [comment]
```
            let columns = this.getColumns();

            columns = columns.filter(f => f.field != 'removedFieldName');

            this.slickGrid.setColumns(columns);
```

**Comment by davidzhang9990** [comment]
@dfaruque  
I see，but I need a parameter passed to the Detail Editor, used to dynamically determine the display or hide some fields. These fields are not fixed

**Comment by davidzhang9990** [comment]
PurchaseOrderGrid.ts code

 //打开窗体
        private openOrderDialog(orderType: number) {
            //var form = new PurchaseOrderForm(typeof (PurchaseOrderForm));
            //form.OrderDetailsList.orderType = orderType.toString();
            var dlg = new PurchaseOrderDialog();
            dlg.getPrefix();
            
            this.initDialog(dlg);
            dlg.loadEntityAndOpenDialog(<PurchaseOrderRow>{
                Type: orderType
            });
        }
        //david 设置页面按钮
        protected getButtons() {
            // preserving default New Item button
            var buttons = super.getButtons();
            //删除默认添加按钮
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);
            buttons.push({
                title: '新增荒料',
                cssClass: 'add-button',
                onClick: () => {
                    this.openOrderDialog(Default.PurchaseType.Stone);
                }
            });
            buttons.push({
                title: '新增板材',
                cssClass: 'add-button',
                onClick: () => {
                    this.openOrderDialog(Default.PurchaseType.Slab);
                }
            });
            return buttons;
        }

**Comment by davidzhang9990** [comment]
PurchaseOrderForm.cs  code
        [Tab("采购信息")]
        [Category("采购明细")]
        [PurchaseOrderDetailEditor]
        public List<Entities.PurchaseOrderDetailRow> OrderDetailsList { get; set; }
PurchaseOrderDetailEditor.ts code

  //格式化列
        protected getColumns() {
            Q.log("column details Id：" + this.orderType);
            var columns = super.getColumns();
             if (orderType === PurchaseType.Stone.toString()) {
               this.allColumns.splice(7, 3);
              } else {
                         this.allColumns.splice(10, 3);
               }
            return columns;
}

**Comment by davidzhang9990** [comment]
@dfaruque   
I want get a parameter from  PurchaseOrderGrid.ts => new PurchaseOrderDialog(),passing to
PurchaseOrderDetailEditor.ts=> getColumns   function

**Comment by dfaruque** [comment]
try this
https://github.com/dfaruque/Serenity.Extra#to-access-parentmaster-dialog-from-childdetail-dialog

**Comment by davidzhang9990** [comment]
@dfaruque   
Thanks

**Comment by jmkamran1** [comment]
I have a solution
I want to hide UnitPrice field from OrderDetail to select Customer 
CustomerID is from Order
Now first you should add HeaderCssClass on UnitPrice Like this
 [Width(100)]
        [HeaderCssClass("ABCDE")]
        public Decimal UnitPrice { get; set; }
your field css class is fixed now
Next you should add these line in constructor of OrderDialog
 this.form.CustomerID.changeSelect2(e => {
                $('.ABCDE').hide();
              
			}) 
Hope this will help you

**Comment by ShifanilaSenthil** [comment]
How could we resolve that? 
//columns = columns.filter(f => f.field != 'Bcc');
                    //columns = columns.filter(f => f.field != 'Body');
                    //columns = columns.filter(f => f.field != 'MailFrom');
                    //this.slickGrid.setColumns(columns);
