### ISSUE TITLE
how to show edit icon in grid

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2831]
Hello Friends,

how can i show edit, delete etc icons in grid using serenity ?

**Comment by kilroyFR** [comment]
See : http://serenity.is/demo/BasicSamples/InlineActionButtons

**Comment by brunobola** [comment]
Just follow the samples...

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons/InlineActionGrid.ts
