### ISSUE TITLE
Grid not displaying Records

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2832]
Hello 
I created a view and it has rows but when i generated code from sernerity.exe now the gird is showing nothing like the attached image. any ideas? 
![screenshot_3](https://user-images.githubusercontent.com/2439608/32143157-34be11ca-bcc7-11e7-8ca4-c713d9898bed.png)

**Comment by dfaruque** [comment]
look at your browser's console.
it should gives you some hint.
