### ISSUE TITLE
Cannot find name 'Promise' - Typescript Compiltation error after 3.3.5 Update

### ISSUE THREAD

**Issue by MaradiagaSistemas** [volkanceylan/Serenity#2834]
Hello,

Thanks for this amazing framework, I have been using Serenity since 10 months ago, yesterday i Updated to Last version but while transforming T4 Templates shows an error "Cannont find name 'Promise'"

Should I update or install something?

Thanks for your support.

**Comment by volkanceylan** [comment]
Reinstall Serenity.Web, you miss some files, or if using .net core, run dotnet sergen restore.

**Comment by MaradiagaSistemas** [comment]
Thanks for your quick Reply volkanceylan, 
 I ran Update-Package Serenity.Web -reinstall but without success, I'm using MVC version, error es on "Serenity.CoreLib.d.ts" File.

**Comment by volkanceylan** [comment]
Hmm, update your typescript, see INSTALL.md

**Comment by MaradiagaSistemas** [comment]
Solved installing this: npm install @types/es6-shim

Thanks!
