### ISSUE TITLE
(3.3.5 update - Enitity As Panel not working) memory grid in dialog panel and first tab, not rendered properly

### ISSUE THREAD

**Issue by jas2008** [volkanceylan/Serenity#2835]
after updated to 3.3.5, memory grid in dialogpanel not rendered correctly.

1. dialogaspanel (no tab),  the grid show all rows but only the first column shown, the rest of the columns(rowindex column) not rendered 

2. dialogaspanel(grid inside tabs), the grid in first tab rendered same as 1 above, grid in other tabs rendered fine.

**Comment by mike993** [comment]
same here... any suggestion?

**Comment by jas2008** [comment]
Thanks mike993,   

Not working :(

**Comment by ramveersgh** [comment]
Hi Guys
Any update on this? 
I am also facing this same issue and this is also reproducible in the demo as well at below link where memory grid does not display the records - 
http://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

**Comment by volkanceylan** [comment]
add a call to "arrange" after appending.

```js
myDialogAsPanel.element.removeClass('hidden').appendTo('#DialogDiv');
myDialogAsPanel.arrange();
```

**Comment by ramveersgh** [comment]
Thanks @volkanceylan 
After adding a call to "arrange" works fine.

**Comment by jas2008** [comment]
Thanks @volkanceylan.
