### ISSUE TITLE
Enum filter on Grid ...Error.Input string was Not In correct format.

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2837]
when i select any value from enum Filter it will show Above alert ..
Is there Is need to add equality filters..
 protected createQuickFilters() {
        super.createQuickFilters();
        this.addQuickFilter({
            title: "Status Filter",
            cssClass: Q.text(""),
            type: Web_DSL.Common.StatusEditor,
            field: EnquiryRow.Fields.Status
        });
guys,
Suggest if u guys have any idea..

**Comment by ANDY7575** [comment]
@Estrusco 
please have look.

**Comment by Estrusco** [comment]
Can you explain? What do you want to achieve?

**Comment by ANDY7575** [comment]
@Estrusco 
thanx for reply..
here is my problem..

EnquiryGrid-parent
EnquiryDetailsGrid-Child 
 i have loaded Status(enum type) in EnquiryGrid which is field from EnquiryDetailsGrid..
for the same i have created Enumfilter and applied..
but when im trying to filter im getting Alert Msg= "Input string was Not In correct format"

protected createQuickFilters() {
super.createQuickFilters();
this.addQuickFilter({
title: "Status Filter",
cssClass: Q.text(""),
type: Web_DSL.Common.StatusEditor,
field: EnquiryRow.Fields.Status  //here when i change Field Status to any another string Field For checking                  its working fine..
});

**Comment by Estrusco** [comment]
Why you don't put QuickFilter attribute on field in row?

Can you post code of rows?

**Comment by ANDY7575** [comment]
ooh thanx buddy,I have deleted above code and applied Quickfilter on the 
row now its working ..

with kind Regards,
Aniket

**Comment by ANDY7575** [comment]
ooh thanx buddy,I have deleted above code and applied Quickfilter on the 
row now its working ..

with kind Regards,
Aniket
