### ISSUE TITLE
Two UpdatableExtension

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#2838]
I have two updatable extensions one dependent upon the other:

    [InnerJoin("jFund", "[ser].[Funds]", "jFund.[FundId] = t0.[FundId]", RowType = typeof(FundsRow))]
    [UpdatableExtension("jFund", typeof(FundsRow), CascadeDelete = false, ThisKey = "FundId")]
    [InnerJoin("jFundFamily", "[ser].[FundFamilies]", "jFund.[FundFamilyId] = jFundFamily.[FundFamilyId]", RowType = typeof(FundFamiliesRow))]
    [UpdatableExtension("jFundFamily", typeof(FundFamiliesRow), CascadeDelete = false, ThisKey = "FundFamilyId")]

When I update a row, it updates the first updatable extension, but not the second.  Is there a way to do this?

**Comment by volkanceylan** [comment]
You should put updatable extension for third row, to second row.

**Comment by leahmayschneider** [comment]
I'm sorry but I don't know what you mean by that.  Can you go into more detail?

**Comment by volkanceylan** [comment]
Updatable extension for FundFamilies should be on FundsRow.

**Comment by leahmayschneider** [comment]
I put the updatable extension for FundFamilies on FundsRow and add columns from FundFamilies to the original row class.  When I try to transform t4 templates, it crashes Visual Studio.  I've tried this a lot with different tables and having two layers of updatable extension invariably crashes Visual Studio.

**Comment by volkanceylan** [comment]
I don't think it could crash Visual Studio, make sure your row classes are actually valid before running T4.

**Comment by leahmayschneider** [comment]
Migration Script:

`using FluentMigrator;
using System;

namespace Serene14.Migrations.DefaultDB
{
    [Migration(20160519115100)]
    public class Default_Db_20171201_Test1 : Migration
    {
        public override void Up()
        {
            Create.Schema("test");

            Create.Table("Test1").InSchema("test")
                .WithColumn("Test1Id").AsInt32()
                    .Identity().PrimaryKey().NotNullable()
                .WithColumn("Notes").AsString(200).NotNullable()
                .WithColumn("Test2Id").AsInt32();

            Create.Table("Test2").InSchema("test")
                .WithColumn("Test2Id").AsInt32()
                    .Identity().PrimaryKey().NotNullable()
                .WithColumn("Notes2").AsString(200).NotNullable()
                .WithColumn("Test3Id").AsInt32();

            Create.Table("Test3").InSchema("test")
                .WithColumn("Test3Id").AsInt32()
                    .Identity().PrimaryKey().NotNullable()
                .WithColumn("Notes3").AsString(200).NotNullable();
        }

        public override void Down()
        {
        }
    }
}`

Test1 Row: 
`
namespace Serene14.Default.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), TableName("[test].[Test1]")]
    [DisplayName("Test1"), InstanceName("Test1"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [InnerJoin("jTest2", "[test].[Test2]", "jTest2.[Test2Id] = t0.[Test2Id]", RowType = typeof(Test2Row))]
    [UpdatableExtension("jTest2", typeof(Test2Row), CascadeDelete = false, ThisKey = "Test2Id")]
    public sealed class Test1Row : Row, IIdRow, INameRow
    {
        [DisplayName("Test1 Id"), Identity]
        public Int32? Test1Id
        {
            get { return Fields.Test1Id[this]; }
            set { Fields.Test1Id[this] = value; }
        }

        [DisplayName("Notes"), Size(200), NotNull, QuickSearch]
        public String Notes
        {
            get { return Fields.Notes[this]; }
            set { Fields.Notes[this] = value; }
        }

        [DisplayName("Test2 Id"), NotNull]
        public Int32? Test2Id
        {
            get { return Fields.Test2Id[this]; }
            set { Fields.Test2Id[this] = value; }
        }

        [Origin("jTest2")]
        public String Notes2
        {
            get { return Fields.Notes2[this]; }
            set { Fields.Notes2[this] = value; }
        }

        [Origin("jTest2")]
        public String Notes3
        {
            get { return Fields.Notes3[this]; }
            set { Fields.Notes3[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Test1Id; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Notes; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public Test1Row()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field Test1Id;
            public StringField Notes;
            public Int32Field Test2Id;
            public StringField Notes2;
            public StringField Notes3;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Default.Test1";
            }
        }
    }
}
`

Test 2 Row:
`
namespace Serene14.Default.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), TableName("[test].[Test2]")]
    [DisplayName("Test2"), InstanceName("Test2"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [InnerJoin("jTest3", "[test].[Test3]", "jTest3.[Test3Id] = t0.[Test3Id]", RowType = typeof(Test3Row))]
    [UpdatableExtension("jTest3", typeof(Test3Row), CascadeDelete = false, ThisKey = "Test3Id")]
    public sealed class Test2Row : Row, IIdRow, INameRow
    {
        [DisplayName("Test2 Id"), Identity]
        public Int32? Test2Id
        {
            get { return Fields.Test2Id[this]; }
            set { Fields.Test2Id[this] = value; }
        }

        [DisplayName("Notes2"), Size(200), NotNull, QuickSearch]
        public String Notes2
        {
            get { return Fields.Notes2[this]; }
            set { Fields.Notes2[this] = value; }
        }

        [DisplayName("Test3 Id"), NotNull]
        public Int32? Test3Id
        {
            get { return Fields.Test3Id[this]; }
            set { Fields.Test3Id[this] = value; }
        }
        [Origin("jTest3")]
        public String Notes3
        {
            get { return Fields.Notes3[this]; }
            set { Fields.Notes3[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Test2Id; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Notes2; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public Test2Row()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field Test2Id;
            public StringField Notes2;
            public Int32Field Test3Id;
            public StringField Notes3;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Default.Test2";
            }
        }
    }
}
`

This crashes Visual Studio on Transform T4 Templates.

**Comment by volkanceylan** [comment]
You should update Visual Studio i think. T4 templates are not supposed to crash VS.
