### ISSUE TITLE
ColumnPickerDialog.cs (Saltarelle, Serenity 1.9)

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#2840]
Hello Community,

Could you please provide me info regarding column picker's implementation not for TypeScript-oriented project? Does ColumnPickerDialog.cs or similar functionality exist for older versions of framework (Saltarelle style) actually or it has been implemented after general architecture changes?

Thank you in advance.

**Comment by volkanceylan** [comment]
It was implemented after TS port, but anyway it should work in both.
