### ISSUE TITLE
Editor grids won't work as expected (like normal grids) !!!

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#2841]
Can anybody tell me how to make this works as expected...

![image](https://user-images.githubusercontent.com/10889019/32186525-2d61c1aa-bd9a-11e7-8091-72a5e1548351.png)

Code Used:
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace StudyCases.Estudos {

    @Serenity.Decorators.registerClass()
    export class StudyAuxAblationIndexInParoxysmalAfLipvEditor extends Common.GridEditorBase<StudyAuxAblationIndexInParoxysmalAfLipvRow> {
        protected getColumnsKey() { return "Estudos.StudyAuxAblationIndexInParoxysmalAfLipv"; }
        protected getDialogType() { return StudyAuxAblationIndexInParoxysmalAfLipvDialog; }
        protected getLocalTextPrefix() { return StudyAuxAblationIndexInParoxysmalAfLipvRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);

            this.slickContainer.on('change', 'select', e => {
                var cell = this.slickGrid.getCellFromEvent(e);
                if (!cell)
                    return;

                var item = this.itemAt(cell.row);
                var field = this.slickGrid.getColumns()[cell.cell].field;
                item[field] = Q.toId($(e.target).val());
                this.view.updateItem(this.id(item), item);
            });
        }

        protected getAddButtonCaption() {
            return "Adicionar LIPV";
        }

        protected validateEntity(row: StudyAuxAblationIndexInParoxysmalAfLipvRow, id: number) {

            if (!super.validateEntity(row, id))
                return false;

            //Colocar campos dependentes caso necessário
            //Q.alert("Atualizar campos " + id);  

            var isolation = Tabelas.YesNoValuesRow.getLookup().itemById[row.Isolation];
            var twentyMinuteWaiting = Tabelas.EnumProcedureThirtyMinuteWaitingRow.getLookup().itemById[row.TwentyMinuteWaiting];
            var adenosine = Tabelas.EnumProcedureAdenosineRow.getLookup().itemById[row.Adenosine];
            var afterAdenosineDescricao = Tabelas.EnumProcedureAfterAdenosineRow.getLookup().itemById[row.AfterAdenosine];

            row.IsolationDescricao = isolation.Descricao;
            row.TwentyMinuteWaitingDescricao = twentyMinuteWaiting.Descricao;
            row.AdenosineDescricao = adenosine.Descricao;
            row.AfterAdenosineDescricao = afterAdenosineDescricao.Descricao;

            return true;
        }

        getColumns(): Slick.Column[] {
            var columns = super.getColumns();

            columns.unshift({
                field: 'Delete Row',
                name: '',
                format: ctx => '<a class="inline-action delete-row" title="delete">' +
                    '<i class="fa fa-trash-o text-red"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            columns.splice(1, 0, {
                field: 'View Details',
                name: '',
                format: ctx => '<a class="inline-action view-details" title="view details">' +
                    '<i class="fa fa-search text-blue"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            return columns;
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                if (target.hasClass('delete-row')) {
                    Q.confirm('Delete record?', () => {
                        StudyAuxAblationIndexInParoxysmalAfLipvService.Delete({
                            EntityId: item.Id,
                        }, response => {
                            this.refresh();
                        });
                    });
                }
                else if (target.hasClass('view-details')) {
                    this.editItem(item.Id);
                    this.refresh();
                }
            }
        }
    }
}`

**Comment by Estrusco** [comment]
See if this post can help you https://github.com/volkanceylan/Serenity/issues/2846

**Comment by brunobola** [comment]
@Estrusco sorry it won't work, how to make it work, is there any sample that uses this behaviour or is it a limitation... 

Thanks.

**Comment by volkanceylan** [comment]
Editor grids work in-memory, they are not SQL grids, and it works as EXPECTED!!!

**Comment by brunobola** [comment]
@volkanceylan I know this but is it possible to make the funcionalities i describe in editor grids or not ?
And if so how to do that ?

**Comment by volkanceylan** [comment]
This is asked many times, and i answered it, search in issues, and in guide, in memory grids as name implies, works in memory, use a normal grid if you want to work with services.

**Comment by brunobola** [comment]
@volkanceylan thanks, but i was wondering if i make a virtual ID (server side only) and use it as entity ID could this work ?

By the  way I have read all the guides a long time ago and offcourse search the issues, but as the product evolves you might make/add other methods that aren't documented or something.

Thanks anyway.
