### ISSUE TITLE
How to pass value to editordialog...

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2845]
@Estrusco 
@volkanceylan 
Guys please Read ,if not getting my Question, let me know
..
pk table-enquiry-Enquiryid is PK
i have current dialog named Documents-enquiryid FK
which contain list of SowDocument[enquiryId-fk]..
on click of New sow in document dialog i want to pass EnquiryId to It..
please suggest solution if any.

**Comment by Estrusco** [comment]
You can pass data using option in constructor. Some like this

```ts
    constructor(opt?: number) {
            super(opt);
    }
```
then use this.options

**Comment by ANDY7575** [comment]
@Estrusco 
I trying but  Im not getting .
here is my code sample from document constructor
constructor(opt?:number) {

            super(opt);
}
n here I want value to be loaded  in SOW 
constructor(Option) {
            super(Option);
          
            this.form.EnquiryId = this.options  //
}
can u please suggest me...

**Comment by davidzhang9990** [comment]
protected getButtons() {
        buttons.push({
                title: 'custom',
                cssClass: 'add-button',
                onClick: () => {
                    var dlg = new customDialog(option);
                    this.initDialog(dlg);
                    dlg.loadEntityAndOpenDialog(<customRow>{
                    });
                }
            });
}

try this way..  add custom buttom  in  getButtons .and pass parm  when  new  dialog  ..
then  get parm in  dialog  constructor function..

**Comment by ANDY7575** [comment]
thanx @davidzhang9990 ...it helped..
