### ISSUE TITLE
My Detail Lists do not show items

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#2846]
Hi everyone,

I've a form with 4 tabs: two of these contain a detail list. These have a relation with the main table. 
My problem is: when I create a new item of one of the two lists, the item is not displayed, but in my DB was saved. It seems it ignores the relation with the main table.

I read the guide and I followed the steps, but I don't know if I'm missing something.

I show you my code and my views:

**- My main Form:**
![rappdialog](https://user-images.githubusercontent.com/22232670/32231633-63b6f45c-be56-11e7-9511-81fc80109d05.png)

**- One of the two lists:**
![interdialog](https://user-images.githubusercontent.com/22232670/32231644-6cf5723c-be56-11e7-99d6-988ec27a65b4.png)

**- The definition of the two lists in the _XYZRow.cs_ of the main table:**
![listsdefinitionrow](https://user-images.githubusercontent.com/22232670/32231521-16e2b4e0-be56-11e7-91a4-0f0c80764cdf.png)

**- The definition of the two lists in the _XYZForm.cs_ of the main table:**
![listsdefinitionform](https://user-images.githubusercontent.com/22232670/32231606-4e791a20-be56-11e7-92c4-fb22c1eb1d27.png)

**- Definition of the FK which is in the _XYZRow.cs_ of the two detail list:**
![definitionfk](https://user-images.githubusercontent.com/22232670/32231960-38f5f406-be57-11e7-9cd6-27fe3f24fc52.png)

**- This is the table of the list: where there is the NULL, it should be an integer number that is the FK to the main table**:
![resultsql](https://user-images.githubusercontent.com/22232670/32231700-9a4ba6fc-be56-11e7-8094-2ff8a7634b1e.png)

**- My Editor:**
![intereditor](https://user-images.githubusercontent.com/22232670/32231873-090084be-be57-11e7-806e-ba64efb8da45.png)

I really thank you in advance for your time :)

**Comment by Estrusco** [comment]
In your testataDialog.ts try this

```ts
protected updateInterface() {
    super.updateInterface();

    this.interventiGrid.slickGrid.resizeCanvas();
    this.interventiGrid.element.triggerHandler('layout');
}
```

**Comment by kjaraa** [comment]
I don't have **interventiGrid** in my main dialog, because I've added the tab with _[Tab("Interventi")]_. I don't modified the **Views => Templates => EntityDialog.Template.html** file.

The problem seems to be in Row, I think ...

**Comment by Zahar661** [comment]
in Editor?
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />`
in detailDialog?
`/// <reference path="../../Common/Helpers/GridEditorDialog.ts" />`

**Comment by kjaraa** [comment]
Yes @Zahar661,
I’ve the reference you mentioned ...

**Comment by kjaraa** [comment]
Yes @Zahar661,
I’ve the reference you mentioned ...

**Comment by Zahar661** [comment]
can
![image](https://user-images.githubusercontent.com/26430136/32261974-fa007f1e-bee2-11e7-8ba7-73ea03155936.png)

**Comment by kjaraa** [comment]
@Zahar661, I removed that, but still not working:(

**Comment by kjaraa** [comment]
I’ve no idea: any help, please ? 
Thanks all :)

**Comment by Zahar661** [comment]
In one tab work?

**Comment by kjaraa** [comment]
It does not worked neither

**Comment by Zahar661** [comment]
All text send in mail alkazar@inbox.ru

**Comment by kjaraa** [comment]
Hi @volkanceylan,
do you have any idea how to solve that ?
I work all day, but I don’t know what I’m missing or wrong.

Thanks for your time !! :)

**Comment by Estrusco** [comment]
@kjaraa even if you use tab, you have added two editor in your form. InterventiEditor and MaterialiEditor. These two are derived by GridEditorBase.
Then, you can use, in xyzDialog.ts the triggerHandler. I have write e.g interventiGrid, but in your case is `this.form.interventiList` and `this.form.Materiali`.


You can try with:

```ts
protected updateInterface() {
    super.updateInterface();

    this.form.interventiList.slickGrid.resizeCanvas();
    this.form.interventiList.element.triggerHandler('layout');

    this.form.Materiali.slickGrid.resizeCanvas();
    this.form.Materiali.element.triggerHandler('layout');
}
```

**Comment by kjaraa** [comment]
It worked: thank to @Zahar661 and @Estrusco for the help, the patience and your time :)
