### ISSUE TITLE
Class-level LeftJoin not generating part 2

### ISSUE THREAD

**Issue by gdeacon** [volkanceylan/Serenity#2847]
Hi All,
I know I posted a similar issue recently but I'm still having the issue.  Let me see if I can be clearer.
1. I want to show some information from a "detail" table on the "master" grid 
2. The "detail" has a 1 to many relationship to the "master"
3. From the article on the LeftJoin attribute I see you can declare a class level join so I did that see below the "detail" table is linked by the ProgramId field which I'm attempting to join (see below)
[LeftJoin("jPrimaryVendors", "ProgramVendor", "jPrimaryVendors.[ProgramId] = T0.[Id]", RowType = typeof(ProgramVendorRow), TitlePrefix = "")]

I defined a field tin the "master" row class as this
        [Expression("jPrimaryVendors.[VendorId]")]
        [LookupEditor(typeof(VendorRow))]
        public Int32? VendorId
        {
            get { return Fields.VendorId[this]; }
            set { Fields.VendorId[this] = value; }
        }

With the exception of being a 1 to many relation this is almost exactly like the example in the guide.
When this is run the following SQL is generated ....

SELECT TOP 100 
T0.[id] AS [Id],
T0.[businessKey] AS [BusinessKey],
T0.[effOrderStart] AS [EffOrderStart],
T0.[effOrderEnd] AS [EffOrderEnd],
T0.[effShipStart] AS [EffShipStart],
T0.[effShipEnd] AS [EffShipEnd],
T0.[notes] AS [Notes],
T0.[created] AS [Created],
T0.[createdBy] AS [CreatedBy],
T0.[modified] AS [Modified],
T0.[modifiedBy] AS [ModifiedBy],
T0.[CompanyId] AS [CompanyId],
T0.[ProgramTypeId] AS [ProgramTypeId],
T0.[ProgramTimeFrameId] AS [ProgramTimeFrameId],
T0.[ProgramTermsId] AS [ProgramTermsId],
T0.[ProgramDealClassId] AS [ProgramDealClassId],
T0.[ExcludeMonthEndCalc] AS [ExcludeMonthEndCalc],
T0.[IsActive] AS [IsActive],
jCompany.[Name] AS [CompanyName],
jProgramType.[Value] AS [ProgramTypeValue],
jProgramTimeFrame.[Value] AS [ProgramTimeFrameValue],
jProgramTerms.[Value] AS [ProgramTermsValue],
jProgramDealClass.[Value] AS [ProgramDealClassValue] 
FROM [dbo].[Programs] T0 
LEFT JOIN [dbo].[Company] jCompany ON (jCompany.[Id] = T0.[CompanyId]) 
LEFT JOIN [dbo].[ProgramType] jProgramType ON (jProgramType.[Id] = T0.[ProgramTypeId]) 
LEFT JOIN [dbo].[ProgramTimeFrame] jProgramTimeFrame ON (jProgramTimeFrame.[Id] = T0.[ProgramTimeFrameId]) 
LEFT JOIN [dbo].[ProgramTerms] jProgramTerms ON (jProgramTerms.[Id] = T0.[ProgramTermsId]) 
LEFT JOIN [dbo].[ProgramDealClass] jProgramDealClass ON (jProgramDealClass.[Id] = T0.[ProgramDealClassId]) 
ORDER BY T0.[businessKey], T0.[id];

As you can see there's no LEFT JOIN on ProgramVendor (the "detail" ) table.

What the heck am I missing  Is it the nature of the relation?  I tried it with a view that would make it a 1 to 1 and still nothing

I'm so stumped and I apologize for posting this again

**Comment by Zahar661** [comment]
can also https://github.com/volkanceylan/Serenity/issues/2821

**Comment by gdeacon** [comment]
Thank you my firend after reading issue #2821 I was able to use a select statement in the expression.  Perhaps we need to add this to the Wiki I was not aware that you could do this.  I know you should use the frameworks as much as possible for sometimes you need to do something outside the box.

Thanks again
