### ISSUE TITLE
want to show a prompt

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2850]
Hello Friends,

I want to read a Quantity from db and if someone try to exceed it i want to show a prompt how can i do this in serenity where i need to implement the code and how it should be.  ??

**Comment by javaman63** [comment]
Use  this on your xyzDialog.ts (remember to transform your templates)

 Q.notifyError('Some error');
 Q.notifySuccess('Some Sucess');

**Comment by JohnRanger** [comment]
Hi @ManzoorPK ,
what do you mean with **quantity**? An amount of records?

Can you Elaborate a bit more in Detail what you want to achive?

Javaman's answer Shows how to Display an error or a success Dialog but you Need to have some trigger for your Dialog.

John.
