### ISSUE TITLE
(3.3.5/3.3.7 Update) Datepicker issues with date format

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#2852]
Hi,

I was wondering whether anyone had noticed an issue with the date picker or whether I've missed something.

Since 3.3.5 the datepicker now formats the date in US format whereas previously it was fine (my dev environment is en-GB).

I have specified auto in the web.config and the funny thing is that the input flags an error when the datepicker picks a date which ends up as incorrect (in GB culture) i.e. 7/30/17. 

The date picker works in 3.0.5 but not in the latest updates 3.3.5 or 3.3.7.

Downgrading to 3.0.5 restores the correct functionality.

**Comment by PanChenhao** [comment]
i have the same issue. By the way, how to downgrade to 3.0.5?

**Comment by karimhyatt** [comment]
The best way is to go into VS Tools -> NuGet Package Manager -> Manage NuGet. Packages for Solution. That allows you to easily choose the versions you want.

**Comment by karimhyatt** [comment]
See the link above, but this fixes the problem with the date.
