### ISSUE TITLE
 how to Fill editor Grid from database...

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2853]
hello guys..
 @Estrusco 

here i am overriding Getbuttons().. im able to save records,but how to load grid editor from `database..` 
     `   protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            buttons[0].onClick = () => {
                
                this.createEntityDialog(this.getItemType(), dlg => {
                    var dialog = dlg as EnquirySowDialog;
                    dialog.onSave = (opt, callback) => this.save(opt, callback);
                    var entity = this.getNewEntity() as EnquiryDocumentsRow;
                 //   this.PassEnquiryId = entity.EnquiryId;
                    entity.EnquiryId = this.PassEnquiryId;
                    
                    dialog.loadEntityAndOpenDialog(entity);
                });
            }

            return buttons;
        }`

**Comment by ANDY7575** [comment]
@volkanceylan  
can u please suggest any way to do same..

any help is appreciated.
thanx ..
kind Regards,
Aniket

**Comment by ANDY7575** [comment]
sorry bro that's not..
let me explain it in detail..
i have enquiryDocument which contains List of SowDocument .
SowDocument is a list belongs to enquirySow 
so enquirySoweditor in EnquiryDocument dialog...
here im not using enquirySowEditorDialog im using enquirySowDialog
so on save data saved into db..
so after save i want to load saved row into EdenquirySoweditor grid..
i hope u will understand ..

thanking you,
Aniket.

**Comment by JohnRanger** [comment]
Sounds very complicated to understand. A few screenshots which explains what you want to achieve surely would help.

With Kind regards,

John

**Comment by ANDY7575** [comment]
hey @JohnRanger 
sorry bro im new to github and unable to upload screenshots.
im trying to upload but getting error ..Something went wrong..
any help

**Comment by JohnRanger** [comment]
Hi Andy7575,

Directly Here in the edit window, there is an Option to attach files. If this does not work for you then use a different browser or make sure you are properly connected to the Internet (no Proxy inbetween, sufficient Speed and stable Connection) - no strange browser plugins.

John

**Comment by ANDY7575** [comment]
Sorry for late appreciation @JohnRanger .
i managed to achieve above Functionality..
