### ISSUE TITLE
xyzGrid.ts; getColumns(); Replacing emty value in one column with value from different (related) table

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2854]
Dear all,

Im am currently writing an Enterprise print Manager solution as an Addition to an existing Commercial product (TAC Reservation Assistant).

The Goal is to manage the application's Default Printer on a Workstation Group or Workstation Level. A Workstation Group is a "bracket" arround a Collection of Workstations which share some common Things (like the same room and with that: Mostly the same Default Printer).

For this I have two Tables:

- one which holds the Workstation Groups (including their Default Printer)
- another table which holds the Workstations (and their Default Printer as well as a reference to the Workstation Group the workstation belongs to).

The admin can define a Default Printer on a **Workstation Group** Level and - as Long as there is no Default Printer set on the **Workstation** Level, the Default Printer from the Workstation Group shall be used. The logic for this is already implemented in the powershell scripts which are used to Launch the application and that works perfectly fine.

What I now want to achieve is, to Display the **Workstation Group's** Default Printer in the **Workstation**Grid.ts as Long as there is no specific Default Printer set on the Workstation Level.

For this 

- I have modified the xyzWorkstationRow.cs to include the neccessary fields from the WorkstationGroups table.
- Have modified the workstationColumns.cs to include the neccessary foreign field from the Workstation group **(and set its width to 0)**
- Also overrided the getColumns() method within WorkstationGrid.ts like the following:

```ts
protected getColumns(): Slick.Column[] {
            let columns = super.getColumns();
            let fld = ForWorkstationsRow.Fields;

            var WSGDefaultPrinterName = "";
            let DefaultPrinter_WSGNameColumn = Q.first(columns, x => x.field == fld.WSGDefaultPrinter_PrintqueueIDShareName);
            DefaultPrinter_WSGNameColumn.format = ctx => { WSGDefaultPrinterName = ctx.value; return ctx.value };

            let DefaultPrinter_PrintqueueIDShareNameColumn = Q.first(columns, x => x.field == fld.DefaultPrinter_PrintqueueIDShareName);
            DefaultPrinter_PrintqueueIDShareNameColumn.format = ctx => {

                if (ctx.value == null)
                {
                    if (WSGDefaultPrinterName == null)
                    {
                        DefaultPrinter_PrintqueueIDShareNameColumn.toolTip = "No default printer defined";
                        ctx.value = ""; return ctx.value;
                    }
                    else
                    {
                        DefaultPrinter_PrintqueueIDShareNameColumn.toolTip = "default printer defined in workstation group";
                        ctx.value = "( " + WSGDefaultPrinterName + " )"; ctx.item.title = "from Workstation group"; return ctx.value;
                    }

                }
                else
                {
                    DefaultPrinter_PrintqueueIDShareNameColumn.toolTip = "default printer defined here";
                    return ctx.value;
                }
                
            };

            return columns;
        }
```

This works technically perfectly fine (I copy the desired value from the foreign field column in case there is no Default Printer set for the current Workstation).

**Problem:**
There is one Thing I want to avoid:
When I do that, the foreign column is visible at the most right Position of the grid - even though I set ist width to 0.

I have tried to completely hide the column with the "hidden(true) and visible(false) Attribute for this foreign column - but when I do that, then the column is not only **not visible** -- it is **not there** (which in my opinion are two different Things).

I know that I _could_ retrieve the values for the foreign field also by using webservice calls but this does not look very elegant for me (would give a lot of single webservice calls).

**Question:**
- Is there a more elegant way to do this?
- How can a Slick column be completely hidden but technically still be present?
- Should this be done by pulling the values via webservice instead of using an additional column which delivers the neccessary values?

Thanks for any Feedback and

with Kind regards,

John

**Comment by volkanceylan** [comment]
You don't need to show a column to make sure it is loaded. There is getIncludeColumns method you may override in Grid.ts and you could also add [MinSelectLevel(SelectLevel.List)] to your foreign field.

**Comment by JohnRanger** [comment]
Good evening Volkan,

thanks for your very fast Reply. 

I have tried both variants and obviously I don't understand the full application of what you explained.

(I tried to find an example for getIncludeColumns within one of the newest serenes but dind't find any Code. As I am only an Admin (no real dev) I only can look at existing Code and then transform it to my Needs. I also tried to find out how to use it by go to Definition.

I tried to use it like this:

```ts
protected getIncludeColumns(_WSRow: ForWorkstationsRow) 
        {
            var myColumns = {
                [_WSRow.WSGDefaultPrinter_PrintqueueIDShareName]: true
            };
           
            return myColumns;
        };
```
But when I don't include the WSGDefaultPrinter_PrintqueueIDShareName column within xyzColumn.ts then I get an exception when trying to Q.first... within getColumns() later.

When I do include the column but set it to hidden then I get all empty values.

 --> What is the exact usage of getIncludeColumns? Include non-visible columns to the Overall set of columns so that they are accessible within getColumns? How do I properly override it? 

-----------

As a second try, I have added the [MinSelectLevel(SelectLevel.List)] to my foreign field but when I then either 

(1) do not list at all the foreign field within my xyzColumns.cs then I get an error stating that the field is not available (which is reasonnable) 

or when I set it to hidden then I have the same effect as before: The values in the hidden column are not available. --> How would I Access the value of the hidden column in this case from within GetColumns?

May I kindly ask you for a few words how to use getIncludeColumns in order to be able to copy data from an invisible column into a visible column?

Or how to fully use the [MinSelectLevel(SelectLevel.List)] with the same Outcome? (Accessing the data of an invisible column and copy it into a visible column?

Many thanks for this and

with Kind regards,

John

**Comment by JohnRanger** [comment]
For reference to anybody which runs into the same Problem:

I was unable (due to lack of the needed developer Knowledge on my part) to follow Volkan's instructions but I found a very easy applicable solution by manipulating directly the Slickgrid (freely transformed from this stackoverflow question: [https://stackoverflow.com/questions/6373336/possible-to-hide-a-slickgrid-column-without-removing-it-from-the-columns-array](url))

You only Need to override GetColumns() within xyzGrid.ts like this:

```ts
protected getColumns(): Slick.Column[] {
            let columns = super.getColumns();
            let fld = ForWorkstationsRow.Fields;
            
            var WSGDefaultPrinterName = "";
            let DefaultPrinter_WSGNameColumn = Q.first(columns, x => x.field == fld.WSGDefaultPrinter_PrintqueueIDShareName); // *** Your column from where you will pull data and which should be hidden ***
            DefaultPrinter_WSGNameColumn.name = "";
            DefaultPrinter_WSGNameColumn.headerCssClass = "reallyHidden";
            DefaultPrinter_WSGNameColumn.cssClass = "reallyHidden";
            DefaultPrinter_WSGNameColumn.format = ctx => {

                WSGDefaultPrinterName = ctx.value; return ctx.value
            };

            let DefaultPrinter_PrintqueueIDShareNameColumn = Q.first(columns, x => x.field == fld.DefaultPrinter_PrintqueueIDShareName);
            DefaultPrinter_PrintqueueIDShareNameColumn.format = ctx => {

                if (ctx.value == null)
                {
                    if (WSGDefaultPrinterName == null)
                    {
                        ctx.value = ""; return ctx.value;
                    }
                    else
                    {
                        ctx.value = "( " + WSGDefaultPrinterName + " )"; return ctx.value;
                    }

                }
                else
                {
                    return ctx.value;
                }
                
            };

            return columns;
        }
```

and add the following css into your site.less:

```css
.reallyHidden {
    display: none !important;
}
```

Hope this helps somebody.

With Kind regards,

John
