### ISSUE TITLE
Master - details: some columns not showing in details

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2855]
I have created a master detail form. It works but does not show two columns. These columns are marked as foreign key. They show in the xxdialog but not in grid.

the xxRow.cs is like following:
![image](https://user-images.githubusercontent.com/20435849/32289854-aba5a830-bf55-11e7-88ca-9073c6b3430d.png)

the xxColumn.cs is like this
![image](https://user-images.githubusercontent.com/20435849/32290170-cc3a2d40-bf56-11e7-8169-d892ae26f42a.png)

but the result in grid is shown like this.
![image](https://user-images.githubusercontent.com/20435849/32289935-fde046dc-bf55-11e7-91a5-6dc00e5bab12.png)

**Comment by JohnRanger** [comment]
Hi @ms4hafiz,

you have to use type String (not StringField) and you must add {get; set;} to your two fields within xyzColumns.ts.

With Kind regards,

John

**Comment by ms4hafiz** [comment]
@JohnRanger  
Thank you that what I had missed. Now it works.
