### ISSUE TITLE
Serenity Premium Support

### ISSUE THREAD

**Issue by likeshan168** [volkanceylan/Serenity#2858]
Hi Volkanceylan,

I have paid the Serenity Premium Support, but my phone cannot receive the message code and how can I get the premium samples

Thanks

**Comment by volkanceylan** [comment]
Hi Shan, we've sent you an e-mail, let's continue from there.

**Comment by likeshan168** [comment]
Hi Volkanceylan,

About half an hour ago, I have paid the premium support from the web page.
My register phone is 13901012476 and email is chiva.zhao@icloud.com, could
you help to check it

Thanks,
Shan

2017-11-02 14:09 GMT+08:00 Volkan Ceylan <notifications@github.com>:

**Comment by volkanceylan** [comment]
Hi Shan, please use mail address to continue, sharing your personal details here is not recommended ;)

**Comment by premsudheer** [comment]
Hi Volkanceylan
I just purchased Serenity Premium (Personal, 12 Months) license. I got payment confirmation as well. But nothing else. can you please check
