### ISSUE TITLE
Custom Links In Grid demo..open custom dialog.

### ISSUE THREAD

**Issue by davidzhang9990** [volkanceylan/Serenity#2859]
HI.
When I open a custom form, when want to delete this data. 
The grid page data is not refreshed after deleting..

**Comment by davidzhang9990** [comment]
EntityGrid . initEntityDialog #2814，This bug led to this new bug

**Comment by davidzhang9990** [comment]
HI .
the default edit dialog used  initEntityDialog(Serenity.Script.UI.JS)  function ,
this function has bind change event  (subDialogDataChange ).
but custom edit dialog used  loadByIdAndOpenDialog  function. 
That might be the reason，I think..Can fix it？
Thanks much..

grid.ts  --code

 protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);
            if (e.isDefaultPrevented()) {
                return;
            }
            var item = this.itemAt(row);
            var target = $(e.target);
            if (target.hasClass("customer-link")) {
                e.preventDefault();
                if (item.Type == 0) {
                    new Default.PurchaseOrderStoneDialog().loadByIdAndOpenDialog(item.PurchaseOrderId);
                } else {
                    new Default.PurchaseOrderSlabDialog().loadByIdAndOpenDialog(item.PurchaseOrderId);
                }
            }
        }

**Comment by davidzhang9990** [comment]
sorry for that . I copy code from the demo , initdialog  before open dialog  can fix it question.

           if (item.Type == 0) {
                    var stonedlg = new PurchaseOrderStoneDialog();
                    this.initDialog(stonedlg);
                    stonedlg.loadByIdAndOpenDialog(item.PurchaseOrderId);
                } else {
                    var slabdlg = new PurchaseOrderSlabDialog();
                    this.initDialog(slabdlg);
                    slabdlg.loadByIdAndOpenDialog(slabdlg);
                }

**Comment by ga5tan** [comment]
worked fine for me, did not even need initDialog
