### ISSUE TITLE
Question : Updating multiple table values

### ISSUE THREAD

**Issue by jamesalvin49** [volkanceylan/Serenity#286]
Hi,
I have 2 tables 
Table A and Table B
While Creating or Updating Table A, an attribute in Table B need to be updated.
How could i achieve this?

**Comment by volkanceylan** [comment]
You override AfterSave and update record in B by its id Connection.UpdateById

**Comment by jamesalvin49** [comment]
Thanks @volkanceylan for the quick feedback.
