### ISSUE TITLE
Gain access to the premium material

### ISSUE THREAD

**Issue by Kaltininkas** [volkanceylan/Serenity#2860]
I paid for the premium personal version, but received nothing about gaining access to the premium content.  Please help.

Thanks,
Dave

**Comment by volkanceylan** [comment]
Hi Dave,

We've sent you your order confirmation and invoice from support@serenity.is
to your daveculp@aol.com address yesterday. Please check your junk mail
folder just in  case.

Need your GitHub *account name* not e-mail that you use to grant access to
private repository.

GitHub doesn't let us find users by their e-mails.

Here is the mail that you received yesterday:

Hello David Culp,

We received payment for your Serenity.is support subscription. See your
invoice attached. Thanks for your business!

Questions? Please contact support@serenity.is

Please share your GitHub *account name* that should be granted access to
private repository (https://github.com/volkanceylan/StartSharp),
where you can download StartSharp template (under Releases tab), access
additional samples and open issues. Unfortunately,
GitHub doesn't allow us to search users by e-mails who didn't make it
public.

Kind regards,
Serenity Support



2017-11-03 0:13 GMT+03:00 kaltininkas <notifications@github.com>:

**Comment by volkanceylan** [comment]
Your account is granted access to private repository, please make sure you are logged in before clicking link:

https://github.com/volkanceylan/StartSharp

**Comment by Kaltininkas** [comment]
Thanks for your quick response.  I didn’t receive any prior email and can only assume that the use of AOL had something to do with that…apologies.  That said, I am now able to access and look forward to diving more deeply into the Serenity platform.  Thanks again!

 

Regards,

Dave

**Comment by ssuriset1** [comment]
How much does the premium support cost?

**Comment by dfaruque** [comment]
@ssuriset1 https://serenity.is/#Pricing
