### ISSUE TITLE
Datepicker loses images when ScriptBundling enabled

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#2861]
When using ScriptBundling, the html emitted for the Datepicker objects is different. Bundling seems to replace img with buttons
No bundling:
![nobundling](https://user-images.githubusercontent.com/2817543/32353742-ef7cbc90-bfe3-11e7-900c-de0598132a6c.PNG)

Bundling:
![bundling](https://user-images.githubusercontent.com/2817543/32353737-ece1dd1c-bfe3-11e7-8dcc-b547879335b9.PNG)

**Comment by volkanceylan** [comment]
Your CoreLib.min.js is not correct one

**Comment by wldkrd1** [comment]
Updated to latest CoreLib.min.js checked into Serene here, no change: https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Scripts/serenity/Serenity.CoreLib.min.js

**Comment by volkanceylan** [comment]
Serene doesn't have latest CoreLib, why are you insisting? Either reinstall Serenity.Web, or turn off UseMinJs

**Comment by wldkrd1** [comment]
Reinstalled Serenity.Web, no change. Manually minified Serenity.CoreLib.js, no change. Manually minified Serenity.Script.UI.js, no change. Not trying to be a pain, just seems like this is a legit bug in the script minification logic.

**Comment by volkanceylan** [comment]
Man you are using ASP.NET bundling, clearly its a bug in your side, not Serenity, it works at serenity.is/demo and all projects i have....

**Comment by wldkrd1** [comment]
I was using ASP.NET bundling, but I removed it a week ago, relying only on the ScriptBundling tag in Web.config. But ok, I suppose it's possible I missed something.

I have an existing empty Serenity project on another workstation which has been upgraded from 3.0.5 to 3.3.7, it also is missing the images in the datepicker for the Orders page for Northwind. 

I just created a new Serenity project, currently 3.0.5, and the images show up correctly when ScriptBundling is enabled. Upgraded it to 3.3.7, and the images are missing.

**Comment by volkanceylan** [comment]
Ok, have you tried UseMinJS: false?

**Comment by wldkrd1** [comment]
Yes. When ScriptBundling is enabled, the images do not appear, regardless of Minimize or UseMinJS settings.

**Comment by wldkrd1** [comment]
Looks like images are replaced with buttons for the dialogs as well when ScriptBundling is enabled

![dialog](https://user-images.githubusercontent.com/2817543/32523150-f57fe65a-c3ce-11e7-9106-2aaf7b63b7f7.png)

**Comment by volkanceylan** [comment]
You have old version of CoreLib.js or CoreLib.min.js laying somewhere, period.

**Comment by wldkrd1** [comment]
Ok. This is in the new project which was upgraded from 3.0.5 to 3.3.7.

I've manually copied the content from https://raw.githubusercontent.com/volkanceylan/Serenity/master/Serenity.TypeScript.CoreLib/Serenity.CoreLib.js
into both Serenity.CoreLib.js and Serenity.CoreLib.min.js

Same behavior. Deleted content of those files, tried again to make sure some version wasn't cached and Serenity wouldn't load. Restored with the version in GitHub from link above, Serenity loads but same problem.

**Comment by volkanceylan** [comment]
This doesnt make sense. ScriptBundling doesnt change any code. How can it have different source??? Try add some dummy comment in CoreLib.js, disable minimize, enable bundling see if it is still there

**Comment by volkanceylan** [comment]
Also make sure you dont have double corelib.js include in page

**Comment by volkanceylan** [comment]
Ah also Script.UI.js and Script.UI.min.js

**Comment by wldkrd1** [comment]
Confirmed fixed, thanks!

**Comment by vajlo** [comment]
Hi Volkan,
missin icon **display inactive records** FIX

pleas remove  **no-repeat -48px -72px** from serenity.css in .s-IncludeDeletedToggle a

thanks
