### ISSUE TITLE
Project Title is not displayed

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#2863]
Hi everyone,

I have a problem: when I launch my application, I don't see my project title (**Gestione Rapportini**).
It seems that a CSS rule is missing, but I don't know what it is.
My _site.css_ and _site.less_ are the same as the Serene Project on GitHub. 

In the browser console, I see the title, but it's not displayed in the page. Maybe, I have to add a rule in my _site.default.less_ ...

**I show you my HomePage**:
![nessun titolo](https://user-images.githubusercontent.com/22232670/32371172-2c6ae436-c090-11e7-9119-27ce69546e24.png)

and my browser console:
![console](https://user-images.githubusercontent.com/22232670/32371185-37df41e0-c090-11e7-98ea-33e4bb63ea5f.png)

Could you please help me ?

Thanks all for your time :)

Chiara

**Comment by kilroyFR** [comment]
This text comes from the :   "Navigation.SiteTitle": "mytitle"
in your : App_Data\texts\user.texts.<lng>.json  (<lng> being your local text settings)

**Comment by kjaraa** [comment]
Thanks @kilroyFR: now it worked. You're right: the problem was that the title was too long. I've chosen a shorter name. 

Thanks for your time :)
