### ISSUE TITLE
Overlay not working after 3.3.6 Update

### ISSUE THREAD

**Issue by MaradiagaSistemas** [volkanceylan/Serenity#2865]
Hi,

I have included this on site.less for overlay: 

```
.ui-widget-overlay {
opacity: 0.5;
}
```

But this is not working anymore, How can enable this feature again?

Thanks.

**Comment by wldkrd1** [comment]
add a background-color: black to that CSS block

**Comment by MaradiagaSistemas** [comment]
Thanls @wldkrd1 it works!
