### ISSUE TITLE
RemoveForeignFields

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#287]
RemoveForeignFields nasıl kullanılır. Örnek verebilir misiniz ? 

Aşağıdaki gibi mi ?  ScreenShot'dakilerin generate edilmesini engellemek için mi kullanılıyor ? 
```
"RemoveForeignFields": [
                "InsertDate",
                "InsertUserId",
                "UpdateDate",
                "UpdateUserId",
                "DeleteDate",
                "DeleteUserId",
                "IsActive",
                "TenantId"
]
```

![x](https://cloud.githubusercontent.com/assets/16984654/13197682/b0c4410a-d7fd-11e5-8523-f7c66f261e2a.JPG)

Tesekkurler

**Comment by volkanceylan** [comment]
Normalde row u üretirken bağlı tablodaki tüm alanları getiriyor, bu ada sahipleri siliyor, Customer ın InsertUserId si Order da ne işe yarar gibi

**Comment by Olricz** [comment]
Yanlıs yazıyorum sanırım. Yıne de getırıyor. Şu şekilde yazıyorum : 

```
"BaseRowClasses": [
        {
            "ClassName": "LoggingRow",
            "Fields": [
                "InsertDate",
                "InsertUserId",
                "UpdateDate",
                "UpdateUserId",
                "DeleteDate",
                "DeleteUserId",
                "IsActive",
                "TenantId"
            ]
        }
    ],
    "RemoveForeignFields": [
                "IsPotansiyelTipInsertDate"
	   ]
```

**Comment by volkanceylan** [comment]
Sadece InsertDate şeklinde yazılmalı

**Comment by Olricz** [comment]
"RemoveForeignFields": ["InsertDate"]
Bu sekilde yazdım ama 
PotansiyelTipInsertDate i olusturuyor

**Comment by volkanceylan** [comment]
Baktım şimdi de koda, eskiden vardı, şu an kullanılmamış, sanırım şu baserow dan sonra kaybolmuş, bakarım sonra şimdilik elle silinebilir

**Comment by Olricz** [comment]
Tamamdır. Tesekkur ederim Volkan.

**Comment by volkanceylan** [comment]
1.9.15 ile dener misin

**Comment by Olricz** [comment]
volkan eline saglık. 1.9.17'de duzeltmişsin. Yalnız bi sorum olacak. Sergen, LookupEditorleri otomatik olusturmuyor mu ? Ben oyle algıladım. Sonrasında manuel eklemeler mı yapmak lazım ?
