### ISSUE TITLE
Passing parameter in save handler

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2872]
I would like to pass parameter in save handler and then based on the parameter value want to execute some additional task. Any though please.

**Comment by davidzhang9990** [comment]
try create new request and  new  mycustomSave Handler in Repository
like this 
 private class MyCustomSaveHandler : SaveRequestHandler<MyRow,customRequest>
{
    do something ...
}

end  .

**Comment by ms4hafiz** [comment]
@davidzhang9990  
Thank you for the response. With customRequest you mean a parameter and how can I call MyCustomSaveHandler ?

**Comment by davidzhang9990** [comment]
you can find it in demo code .try movie Tutorial  first by pdf help
[serenity-guide.pdf](https://github.com/volkanceylan/Serenity/files/1448913/serenity-guide.pdf)

**Comment by davidzhang9990** [comment]
add  function in XXXEndpoint as one service .so you can call it like this . XXXService.(newfunction)

**Comment by ms4hafiz** [comment]
Thank you I should review the Toturial.
