### ISSUE TITLE
 how to overcome the issue with table generetaed from view

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#2873]
when we trying to display data in grid that uses row which was created by view 

it doesn't shows data 

Uncaught Each data element must implement a unique 'ID' property. Object at index '0' has no identity value: {"Controlno":1,"InventPk":2,"Compno":"","Saledate":"1949-12-10T00:00:00.000","Items":1,"Total":0}

**Comment by javaman63** [comment]
Check this example

http://www.serenity.is/demo/BasicSamples/ViewWithoutID

**Comment by brunobola** [comment]
@javaman63 the sample gives an error...

![image](https://user-images.githubusercontent.com/10889019/32490572-816f9788-c3ab-11e7-95f5-ab0c4e399425.png)

**Comment by javaman63** [comment]
In my View I do it this:

On the MyViewGrid.ts i put this: 
`

        protected getIdProperty() { return MyViewRow.idProperty; }



`

On my MyViewRow.cs: 

`


        IIdField IIdRow.IdField
        {
            get { return Fields.IdVwMulti; }
        }


`

and on My Migration, i create the views like this...

`

 create view vw_MyView as
            
   select 
                                       ROW_NUMBER() OVER (order by idmarca) as IdVwMulti,

		                              t.IdCompany,
		                              t.IdGame,
.....


`

And it is working...hope this help
