### ISSUE TITLE
BUG with Dialog Layout with Maximize and Close buttons - 3.0.6+

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#2875]
These versions have a layout error tested in chrome and edge.

![image](https://user-images.githubusercontent.com/10889019/32414692-8e5b0ffa-c224-11e7-961d-50793a83f69e.png)

**Comment by volkanceylan** [comment]
There is no BUG, bug is with your set of missing files, it works in demo

**Comment by brunobola** [comment]
@volkanceylan what files are missing ?

**Comment by brunobola** [comment]
@volkanceylan forget, just do a package -reinstall and it works, sorry, but never happend after an upgrade.

**Comment by volkanceylan** [comment]
Np, just please make sure it is a bug before reporting it as a BUG :) There are so many bugs with NuGet, that is out of my control.
