### ISSUE TITLE
Request: Add argument to serin so we can pass in the project name with out it asking

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2876]
Trying to use PowerShell to keep my project up to date with base Serenity code then add my changes. It would help a lot if we could pass the project name as an arg to serin. 

Thanks

**Comment by volkanceylan** [comment]
Couldn't understand your method? Aren't you manually merging sources after creating a new one? It should take much more time than entering project name?

**Comment by VR-Architect** [comment]
Sorry I misspoke. We are not manually merging an existing project.

We have created a .net Core command line program which:
1. Developer runs program and enters the project name
2. Grab the most recent version Serenity core
3. Creates a new blank Serenity project (need to pass in project name here)
4. Makes changes to blank Serenity project's code per our team's specification 
         - For example, we add in multi-tenant support, set-up authentication
5. Adds any common code and 3rd party widgets our team uses

This is only done as part of new projects and not for upgrading existing Serenity-based projects.  

As this is always a new project, the developer passes in the new project name into our application (step 1). As the  serin requires us to enter the project name (step 3), the developer has to type it in twice at the command line.

It is just a minor nuisance but the developer could enter the project name in wrong the second time.

thanks for the considerations

**Comment by volkanceylan** [comment]
Latest serin supports this now.
