### ISSUE TITLE
FileLogger sharing violation - small enhancement

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2877]
hey !

i wanted to enable filelogging integrated to Serenity.Core but noticed the .log file that is generated does not include share settings (not possible to read file while application is running).

Would it be possible in future release to enable this as it's particularly useful to display log while application is running on production (using File.Open + sharing attribute instead of File.OpenWrite that is providing unshared filestream object.

filelogger.cs :

                           var fs = File.Open(newFile, FileMode.Append, FileAccess.Write, FileShare.Read);
                            stream = new StreamWriter(fs, Encoding.UTF8);
...

**Comment by kilroyFR** [comment]
Volkan, any chance to take this small enhancement into account in a version ? i think it's useful on production. Thanks

**Comment by volkanceylan** [comment]
Thanks @kilroyFR, changed in e80e6f9724124b4824c4b24218e87c665e04c453
