### ISSUE TITLE
Data localization feature? 

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#288]
Hi JaiQ,

John Ranger here again :-)

While reading through all the closed issues here to learn something, I stumbled over your remark to RudiAnto: "How did you find out about Data localization feature? I don't remember explaining it anywhere :)" And there is a Localization button in one of his screenshots.

Now... As I have some tables with english Content (Status Messages which I Show within some grids) which I would like to appear in the current language the user Interface is running, I thought that data localization sounds great :-)

So my question is: Is this Feature already production ready and if yes, how does it work/how can it be used? How has it to be implemented on the DB side?

(I know that I could have some link table between the Status message table and the language table and then put the translations there in and innerjoin the Status message field...)

Thanks for your Feedback 

and with Kind regards,

John

**Comment by volkanceylan** [comment]
It is available in category and product dialogs, see latest templates

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your fast reply. I will look them up :-)

With Kind regards,

John

**Comment by JohnRanger** [comment]
Hi JaiQ,

I have looked into the newest Serene template. The localization Feature is there --> I could translate a category "Beverages") into german --> Also the comment of it.

But...

I then would expect that in the list of categories - since my GUI runs in german - the Category of "Beverages" would now be displayed as "Getränke" (german word for beverages).

Also in the products in the category column, I would expect the category "beverages" being displayed as "Getränke".

This is not the case with Serenity V1.9.13 (Serene upgraded from 1.9.12 or so).

The column headers and the Buttons are all properly displayed in german. So the Browser has detected my language corrrectly.

Do I have wrong expectations of the data localization Feature? (I have not found it mentioned within the latest DEV-Guide).

Thanks for your Feedback

and

with Kind regards,

John

**Comment by volkanceylan** [comment]
There is no such functionality yet. You need to add joins to bring in texts you like.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your Feedback.

With Kind regards,

John

**Comment by volkanceylan** [comment]
It could be done with some list behavior but originally this was only designed for translation. We usually use these translated texts in public site, not data editing site, so i didn't have such a requirement. Anyway it could be possible in list mode with some extension but i'm not so sure about dialog.

**Comment by JohnRanger** [comment]
Sorry, didn't see your comment as I was also writing :-)

Yes, this is mainly for Grid.

In the Editor mode, I suggest that this would apply to Dropdown boxes (only) which pull their Content from LookupScripts.

With Kind regards,

John
