### ISSUE TITLE
Show a grid in dailog.ts

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2881]
Hello Friends, 

I want to show a grid in Dailog.ts when its in edit mode only. how can i do this?

**Comment by Estrusco** [comment]
In dialog there is a isNew() method.

You can test in afterLoadEntity

```ts
protected afterLoadEntity() {
    if (this.isNew())
        [...]
}
```

then hide your grid when unecessary.

**Comment by ManzoorPK** [comment]
and what is the method to show the gird. ???

**Comment by Estrusco** [comment]
If you want the grid only in edit mode, hide it on insert.

Therefore you can act with jQuery hide function on element of the grid. Search the web for jQuery documentation.

**Comment by ManzoorPK** [comment]
no i mean how can i show it on dailog.ts file the grid

**Comment by Estrusco** [comment]
Add editor on form class. 

Please read manual https://www.gitbook.com/book/volkanceylan/serenity-guide/details
see example https://github.com/volkanceylan/Serene source and demo http://serenity.is/demo/Account/Login?ReturnUrl=%2fdemo%2f
and search prior issues with grid editor.

This is very very basic question

**Comment by ManzoorPK** [comment]
i didn't got success what i need to write on dailog.ts to display the grid into it.

**Comment by volkanceylan** [comment]
Yes, some reading is highly recommended...
