### ISSUE TITLE
Edit User Permissions Dialog Resize bug

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#2882]
When I try to resize **Edit User Permissions Dialog**,  the width and height of the slickgrid becomes smaller and smaller.
![image](https://snag.gy/qXGIrn.jpg)
BTW: Test in Chrome V62.

**Comment by tky753** [comment]
Finally, I figure out the point, it's because  css in **site.administration.less**:
```
.s-UserPermissionDialog, .s-RolePermissionDialog, .s-UserRoleDialog {
    > .size { .widthAndMin(670px); .heightAndMin(450px); }
    .s-DataGrid { height: 100%; }
    .ui-dialog-content { padding: 8px; }
}
```
change from **.ui-dialog-content { padding: 8px; }**
to   **.ui-dialog-content { margin: 8px; }**
can fix it.

it's because 
**$.width()** and **$.height()** include padding

@volkanceylan

**Comment by volkanceylan** [comment]
I don't see any such behavior in demo, sorry.

**Comment by tky753** [comment]
well, this link
http://serenity.is/demo/Administration/User#edit/1
and :
![image](https://snag.gy/N1e72X.jpg)
@volkanceylan

**Comment by volkanceylan** [comment]
What is the browser you are using?

**Comment by tky753** [comment]
Chrome Version 62.0.3202.75 (Official Build) (64-bit)
OS: Win Server 2008R2

**Comment by tky753** [comment]
Chrome      Version 62.0.3202.75 (Official Build) (64-bit)
OS: Win Server 2008R2 / Win10

win10:
![image](https://snag.gy/L3mrET.jpg)
@volkanceylan
