### ISSUE TITLE
How To open Dialog like Grid Opens in Window...

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2885]
i have seen very samples contains Dialog fit to Control same like Grid..
With Back button..

**Comment by brunobola** [comment]
use @Serenity.Decorators.panel()

**Comment by ANDY7575** [comment]
@brunobola 
thanx ..but the dialog is appearing down to grid While opening New ..
Any suggestion to make it work as expected..

**Comment by javaman63** [comment]
You have to have the 3.2.2 (2017-10-18) version (or above) of serenity template and
you have to add @Serenity.Decorators.panel() on your xyzDialog.ts, build and transform t4 templates

Hope this help

**Comment by ANDY7575** [comment]
Thanx @javaman63 worked after updates..cheers..
