### ISSUE TITLE
Saltarelle project 1.9.20; Howe to set initial values for quickfilters in grid

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2886]
Dear all,

as I have to maintain an old Serenity-Saltarelle_based app (non-migratable because of lacking Budget on customer's side) I am trying to set an initial value within a quickfilter above a grid from within Saltarelle.

As I didn't find any example for this (non typescript) also with the latest Saltarelle-based Serene (V1.9.24) I an a bit lost how to set an initial value on a Saltarelle-based quickfilter.

(this would be super easy with the current Serene).

Anyone which has a quick example how to do this?

Thanks for your help and

with Kind regards,

John

**Comment by volkanceylan** [comment]
I don't have an example, but the method you should override is GetQuickFilters, other than that, e.g. PascalCase its mostly similar

**Comment by ramveersgh** [comment]
Hi John

I used to create the quick filter in method **CreateToolbarExtensions** using Saltarelle and initilize it by assigning the value. Here is source code - 
_I never used GetQuickFilters with Saltarelle Code._ 

```
        LookupEditor lkeJobType;
        public ImExJobGrid(jQueryObject container)
            : base(container)
        {
        
        }
        
        protected override void CreateToolbarExtensions()
        {
            base.CreateToolbarExtensions();
             lkeJobType =  AddEqualityFilter<LookupEditor>(ImExJobRow.Fields.JobType,
                   options: new LookupEditorOptions { LookupKey = ImExJobTypeRow.LookupKey });
             lkeJobType.Value = "2"; //Set default running jobs as selected
        }

```

Please confirm if this is your requirement.

**Comment by JohnRanger** [comment]
Hi @ramveersgh,

yes - many thanks - that's exactly what I Need.

Thanks for sharing.

Thanks also @volkanceylan for valuable Feedback.

With Kind regards,

John
