### ISSUE TITLE
MasterDetailRelation Attribute  used question?

### ISSUE THREAD

**Issue by davidzhang9990** [volkanceylan/Serenity#2887]
@volkanceylan 
HI .
I find some code in source.
source file :MasterDetailRelationBehavior.cs

 private void DetailListSave(IUnitOfWork uow, object masterId, IList oldList, IList newList)
{
.....
            if (oldList.Count == 0)
            {
                foreach (Row entity in newList)
                    SaveDetail(uow, entity, masterId, null);
                return;
            }
.....
}

I try to set detail AsGuid and PrimaryKey but  failed..
is there any solution fix it ?
question is Because the newly created detail object does not pass values to the database, this is based on the specific way of int type  for PrimaryKey and Identity。
Thanks much.

**Comment by volkanceylan** [comment]
MasterDetail works with non-integer types, i didn't understand the question
