### ISSUE TITLE
Implement a Signature Pad on Dialog

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#2888]
Hi everyone,

I've to implement a signature pad in my XYZDialog.ts: I've already chosen a [jQueryPlugin](http://keith-wood.name/signature.html), but I don't know how to implement that in my XYZDialog.ts.

I tried to create a new dialog template for my entity and I added a **div** for my signatures.
I'd like also to receive some suggestions to be able to save the signatures in my DB (with **DataURL** I think) and replicate them in my report PDF of the entity.

- **I show you my dialog template:**
![code](https://user-images.githubusercontent.com/22232670/32502149-48b1a876-c3da-11e7-9d9f-fd5d0c53a255.png)

- **How the final dialog should be:**
![dialog](https://user-images.githubusercontent.com/22232670/32502192-6083c16e-c3da-11e7-9889-870ee34fbd08.png)

Thanks in advance for your time and your help !!

Chiara

**Comment by kjaraa** [comment]
I forgot to say that I've already add the CSS and JS files of the plugin in LayoutHead.cshtml

**Comment by wirble** [comment]
This is interesting but this one doesnt seem to work well with touch. Tested on iphone. I am interested to hear if anyone has already done something like this too...

**Comment by saeedahmad101** [comment]
i have already created one issue for this, but no one shared any solution to it yet.
[#2764](https://github.com/volkanceylan/Serenity/issues/2764)

**Comment by wezmag** [comment]
see https://github.com/volkanceylan/Serenity/issues/4533 for implementation

**Comment by stixoffire** [comment]
@kjaraa Do you have sample code where you replicated the images in your reports ?

@wezmag I have one issue with #4533 and that is when I try to edit the stored signature - I get an empty canvas and not the signature. 
Is there any way I can do this, do you have a sample ? I have all typescript code - no java libraries for this. Works fine with your editor to save the signature - just when I click to edit - I have blank canvas and not an image.
