### ISSUE TITLE
Potentially new issue with script bundle in ver 3.3.*

### ISSUE THREAD

**Issue by HairyPloper** [volkanceylan/Serenity#2894]
I`ve noticed that in new version of serenity if you bundle scripts together. (Enabled:true)

`<add key="ScriptBundling" value="{ Enabled: true, Minimize: true, UseMinJS: true }" />`
2 new issues occur 
![bug](https://user-images.githubusercontent.com/25281647/32550367-19f0f2d6-c48d-11e7-9f17-4f5048e652d6.png)
![bu1](https://user-images.githubusercontent.com/25281647/32550368-1a31cb6c-c48d-11e7-96e5-5c6ae7c6373d.png)
Also icon_spring.png is missing from serenity/images
Not sure if this is caused by buggy Package Manager update. Can you confirm?
Tnx in advance

**Comment by volkanceylan** [comment]
Use minimize false and useminjs false and try again.

**Comment by HairyPloper** [comment]
![bug3](https://user-images.githubusercontent.com/25281647/32551452-d9b915be-c490-11e7-9aba-2d2cc213cc83.png)

I already tried that and other couple cases, also i tried to remove some scripts to find potential overriding issue between them but without success.
I set Enabled=false Useminjs=true Minimize=true solves this problem.

**Comment by volkanceylan** [comment]
Enabled false means no script bundling.

Can you paste contents of your ScriptBundles.json and LayoutHead.json files please.

**Comment by volkanceylan** [comment]
Sorry _LayoutHead.cshtml

**Comment by HairyPloper** [comment]
ScriptBundles.json
`{
    "Libs": [
        "~/Scripts/pace.js",
        "~/Scripts/rsvp.js",
        "~/Scripts/jquery-{version}.js",
        "~/Scripts/jquery-ui-{version}.js",
        "~/Scripts/jquery-ui-i18n.js",
        "~/Scripts/jquery.validate.js",
        "~/Scripts/jquery.blockUI.js",
        "~/Scripts/jquery.cookie.js",
        "~/Scripts/jquery.json.js",
        "~/Scripts/jquery.autoNumeric.js",
        "~/Scripts/jquery.colorbox.js",
        "~/Scripts/jquery.dialogextendQ.js",
        "~/Scripts/jquery.event.drag.js",
        "~/Scripts/jquery.scrollintoview.js",
        "~/Scripts/jsrender.js",
        "~/Scripts/select2.js",
        "~/Scripts/sortable.js",
        "~/Scripts/toastr.js",
        "~/Scripts/SlickGrid/slick.core.js",
        "~/Scripts/SlickGrid/slick.grid.js",
        "~/Scripts/SlickGrid/slick.groupitemmetadataprovider.js",
        "~/Scripts/SlickGrid/Plugins/slick.autotooltips.js",
        "~/Scripts/SlickGrid/Plugins/slick.headerbuttons.js",
        "~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js",
        "~/Scripts/SlickGrid/Plugins/slick.rowmovemanager.js",
        "~/Scripts/bootstrap.js",
        "~/Scripts/Saltarelle/mscorlib.js",
        "~/Scripts/Serenity/Serenity.CoreLib.js",
        "~/Scripts/Serenity/Serenity.Script.UI.js",
        "~/Scripts/jquery.cropzoom.js",
        "~/Scripts/jquery.fileupload.js",
        "~/Scripts/jquery.iframe-transport.js",
        "~/Scripts/jquery.slimscroll.js",
        "~/Scripts/mousetrap.js",
        "~/Scripts/fastclick/fastclick.js"
    ],
    "Site": [
        "~/Scripts/adminlte/app.js",
        "~/Scripts/Site/SereneVT.Web.js"
    ]
}`
_LayoutHead.cshtml
`
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<link rel="home" id="ApplicationPath" href="~/" />
<link rel="icon" type="image/x-icon" href="~/favicon.ico" />
@Html.Stylesheet("~/Content/font-open-sans.css")
@Html.Stylesheet("~/Content/font-awesome.css")
@Html.Stylesheet("~/Content/simple-line-icons.css")
@Html.Stylesheet("~/Content/ionicons.css")
@Html.Stylesheet("~/Content/aristo/aristo.css")
@Html.Stylesheet("~/Content/bootstrap.css")
@Html.Stylesheet("~/Content/colorbox/jquery.colorbox.css")
@Html.Stylesheet("~/Content/jquery.fileupload.css")
@Html.Stylesheet("~/Content/pace.css")
@Html.Stylesheet("~/Content/slick.grid.css")
@Html.Stylesheet("~/Content/css/select2.css")
@Html.Stylesheet("~/Content/toastr.css")
@Html.Stylesheet("~/Content/serenity/serenity.css")
@Html.Stylesheet("~/Content/site/site.css")
@if (System.Globalization.CultureInfo.CurrentUICulture.TextInfo.IsRightToLeft)
{
    @Html.Stylesheet("~/Content/site/site.rtl.css")
}
@{var cookie = Request.Cookies["ThemePreference"]; var theme = cookie != null && !cookie.Value.IsEmptyOrNull() ? cookie.Value : "default"; }
<script type="application/json" id="ScriptCulture">@Html.Raw(Serenity.JSON.Stringify(new ScriptCulture()))</script>
<script type="text/javascript">window.paceOptions = { minTime: 250, ghostTime: 250, restartOnRequestAfter: 250, ajax: { trackMethods: ['GET', 'POST'], trackWebSockets: true, ignoreURLs: [] } };</script>
@Html.Script("~/Scripts/pace.js")
@foreach (var x in CommonIncludes.Scripts) { @Html.Script(x) }
@Html.Script("~/Scripts/jquery.cropzoom.js")
@Html.Script("~/Scripts/jquery.fileupload.js")
@Html.Script("~/Scripts/jquery.iframe-transport.js")
@Html.Script("~/Scripts/jquery.maskedinput.js")
@Html.Script("~/Scripts/jquery.slimscroll.js")
@Html.Script("~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js")
@Html.Script("~/Scripts/mousetrap.js")
@Html.Script("~/Scripts/fastclick/fastclick.js")
@Html.Script("~/Scripts/adminlte/app.js")
@Html.Script("~/Scripts/Site/SereneVT.Web.js")

<script src="~/DynJS.axd/@HtmlScriptExtensions.GetLocalTextInclude(this.Html, "Site")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("ColumnsBundle")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("FormBundle")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("TemplateBundle")"></script>
<script src="~/DynJS.axd/@DynamicScriptManager.GetScriptInclude("RegisteredScripts")"></script>`

**Comment by volkanceylan** [comment]
Thanks, please first check if there are any javascript errors in browser console.

Then try replacing "jquery-ui-{version}.js" in ScriptBundles.json with "jquery-ui.js".

I'll try to use same configuration and see error meanwhile, couldn't reproduce that yet.

**Comment by volkanceylan** [comment]
Ok, confirmed that is the issue, replace "jquery-ui-{version}.js" in ScriptBundles.json with "jquery-ui.js".

**Comment by HairyPloper** [comment]
Ok also i can confirm that was issue, after changing "jquery-ui-{version}.js" to "jquery-ui.js"
Thank you for fast response and solution.
Just one thing more, icon_spring.png was missing from serenity/images for me. This was in some other folder images.
