### ISSUE TITLE
Serenity 3.3.x Upgrade Guide [Breaking Change!]

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#2895]
After upgrading your older project to Serenity 3.3 you might have errors like date picker icons missing, or dialog close button looking as text instead of image, as soon as you enable script bundling.

This is due to double jquery-ui include in your page. 

Serenity now has a slimmer version of jQuery UI by default, and CommonIncludes has "jquery-ui.js", instead of "jquery-ui-{version}.js".

But as you might have "jquery-ui-{version}.js" in your ScriptBundles.json, as soon as you enable script bundling, you'll have both  "jquery-ui.js" (from CommonIncludes.Scripts) and "jquery-ui-1.12.1.js" (in Site bundle) in your page.

To resolve this issue, open *Scripts/site/ScriptBundles.json", find line with:

```json
"~/Scripts/jquery-ui-{version}.js"
```

replace with

```json
"~/Scripts/jquery-ui.js"
```

**Comment by karimhyatt** [comment]
Hi Volkan,

Just did a new test and that also seems to fix the problem #2852.

**Comment by wldkrd1** [comment]
#2852

**Comment by brunobola** [comment]
I belieave that if users do a nuget reinstall it creates the missing scripts, and updates everithing also.

**Comment by astrohart** [comment]
Am trying to follow the "Movie Tutorial" in the docs and the icon-speedometer, icon-film and icon-camrecoder are not showing in the latest Serenity.

I tried to follow the steps listed in this issue and it ended up breaking the login page's look so that all that displays is a small, dark-grey rounded rectangle.

**Comment by astrohart** [comment]
![image](https://user-images.githubusercontent.com/8261875/34792364-a261f976-f5fc-11e7-872e-8ea499f9c66d.png)

**Comment by astrohart** [comment]
So i have tracked down that the icons in question are from http://simplelineicons.com/.  But maybe the support has been removed?

Since the code copied from the tutorial does reference the correct CSS names, but it seems like only the FontAwesome icons actually work.

**Comment by volkanceylan** [comment]
Simple line icons no longer included by default, to improve load time. Guide should be updated.

**Comment by kilroyFR** [comment]
add :     "~/Content/simple-line-icons.css", 

in Content\site\CssBundles.json
