### ISSUE TITLE
Unicode database identifiers

### ISSUE THREAD

**Issue by Junariz** [volkanceylan/Serenity#2896]
First, I love Serenity very much.

I want to know Serenity will have some trouble if it allow non-Latin Database identifier in Criteria validation ?

My database has unicode column name, but Serenity.Data seems allow only Latin letters (and numbers).
in Serenity.Data/SqlHelpers/SqlSyntax.cs,  IsValidIdentifier method says:

var c = Char.ToUpperInvariant(s[0]);
if (c != '_' && (c < 'A' || c > 'Z'))
    return false;

for (var i = 1; i < s.Length; i++)
{
    c = Char.ToUpperInvariant(s[i]);
    if (c != '_' &&
        !((c >= '0' && c <= '9') ||
          (c >= 'A' && c <= 'Z')))
        return false;
}

At https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers, 

"A letter as defined by the Unicode Standard 3.2. The Unicode definition of letters includes Latin characters from a through z, from A through Z, and also letter characters from other languages."

( Perhaps first letter would be unicode letter class of Lu/Ll/Lt/Lm/Lo, next letter add class Mn/Mc/Nd/Pc ? )

Thanks.

**Comment by Junariz** [comment]
i.e:
        public static bool IsValidIdentifier(string s)
        {
            const String first = @"\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}";
            const String next = first + @"|" + @"\p{Mn}|\p{Mc}|\p{Nd}|\p{Pc}";

            if (string.IsNullOrEmpty(s))
                return false;

            var identifierReg = new Regex(string.Format("^({0})({1})*$", first, next));
            return identifierReg.IsMatch(s.Normalize());
        }

and build Serenity.Data.dll , my application seems running well.

**Comment by volkanceylan** [comment]
I think you could use Char.IsLetter in places where there is a check for A..Z and it would be more performant. 

There is also need to check where this function used that prevents you from using such column names. As long as i remember when you use brackets Serenity doesnt validate anything.

Another issue is about db compability. For some db types same rules might not apply.

**Comment by Junariz** [comment]
I understood that identifiers are limited to Latin characters for compatibility other than SQLServer.

Unfortunately I use Unicode column names in Criteria field of ListRequest.
Since Criteria of ListRequest uses JsonSafeCriteriaConverter, so SafeCriteriaValidator#VisitCriteria seems to call SqlSyntax.IsValidIdentifier directly.

I was happy if I could find IsValidQuotedIdentifier on this call stack.
I might customize Serenity.Data.dll and use it, Thanks.

**Comment by volkanceylan** [comment]
I actually did change the code and it will be available in next version. Anyway you could rename your property to latin letters and use Column attribute and it should work as is.

**Comment by Junariz** [comment]
Thanks so much !
