### ISSUE TITLE
Visual Studio no longer debugging typescript source

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#2897]
Hi all,

This should be a no-brainer, but I've tried pretty much everything to get the debugger to work again but it has stopped working all of a sudden, so I'm hoping this has happened to someone before and can point me in the right direction.

The debugging options set are:
- Enable Just my Code: Unchecked
- Enable source server support: checked
- Edit and Continue: unchecked.
- Enable Javascript debugging: checked

I have made sure that the tsconfig.json contains "sourceMap": true 

I have tried both IIS express and Local IIS.

I also tried to see whether it was a typescript debugging error, but a simple javascript file seems to debug ok. 

Thanks for your help!

**Comment by volkanceylan** [comment]
Use Chrome, we don't support nor recommend VS script debugging, better turn it off.
