### ISSUE TITLE
Many checkboxes in form

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2898]
Hey all
So i have an entity that has many checkboxes in the form dialog. I cant get the design to really look nice because theres so much spacing between each checkbox, and having one per row is also not really nice.

Anyone found the right combination working with the .less to get them looking nice?

Thanks!
Roy

**Comment by MaradiagaSistemas** [comment]
Try this on your site.less inside your Dialog section : 

`@media (min-width: 768px) {
         .field.YourField1, .field.YourField2, .field.YourField3, .field.YourField4  {
            max-width: 25%;
        }
    }`

**Comment by volkanceylan** [comment]
You could also use [QuarterWidth] etc.

**Comment by shakazulu89** [comment]
thanks guys ill give it a try.
[QuarterWidth] ... how could i have known that existed? is it documented somewhere? it doesnt have it here: [https://github.com/volkanceylan/Serenity/wiki/Serenity-Attributes](url)

**Comment by volkanceylan** [comment]
Its a new attribute, just wanted to offer an option

**Comment by shakazulu89** [comment]
Serenity has too many options! :P
Its a cool process discovering everything it has to offer. You really did
an amazing job.

On Thu, Nov 16, 2017 at 3:53 PM, Volkan Ceylan <notifications@github.com>
wrote:

> Its a new attribute, just wanted to offer an option
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvolkanceylan%2FSerenity%2Fissues%2F2898%23issuecomment-344946286&data=02%7C01%7Crharel%40hotmail.com%7C1e95dfbd1e4746b2abad08d52d01c978%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636464408043636865&sdata=nEw5YtbL8QolT9rZ0VlHFlVQQwlv7fZpPMGeuDdrSwk%3D&reserved=0>,
> or mute the thread
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABUaVIm72kdy63IIZh4i8e0tUaMa5nDXks5s3ExigaJpZM4QW8-z&data=02%7C01%7Crharel%40hotmail.com%7C1e95dfbd1e4746b2abad08d52d01c978%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636464408043636865&sdata=3V5PJr9CFf6ihZvVXIRlMiEUjuVUp69BnoRuoNKlO%2FA%3D&reserved=0>
> .
>



-- 
Thanks,
Roy

**Comment by Estrusco** [comment]
I update wiki page with these new attributes as soon as I can
