### ISSUE TITLE
How to remove "New" button on a particular page

### ISSUE THREAD

**Issue by denonc** [volkanceylan/Serenity#29]
Hi, I will like to remove the "New Record" button in one of the pages, did read up the guide but was unable find clues regarding it (or probably missed it), thanks to advise!

**Comment by volkanceylan** [comment]
You can override GetButtons method in YourGrid.cs and return an empty list. Or call base method, remove first button from list and return the list.

**Comment by biggikalli** [comment]
Dear Volcan,
I have tried the above suggestion but I am getting (more) grey hairs as I am not succeeding in getting rid of these two buttons (see picture).

Could you kindly get me on the right track?
I would be deeply grateful if you could point me to some instruction on how to manipulate/remove buttons in Serenity.

Thank you in advance.

![image](https://cloud.githubusercontent.com/assets/15879719/14018912/0e4985fe-f1c8-11e5-87ef-aff5ec61544b.png)

**Comment by volkanceylan** [comment]
I don't understand what is so hard that makes you have gray hairs :)

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_remove_add_button_from_a_grid.html

**Comment by biggikalli** [comment]
Ahh.... you great Maestro. Thank you so much for your prompt reply.
Now I will get my black hairs back quickly :)
I had totally missed the chapter in the guidebook.
Thank you again and sorry for, perhaps, a foolish question.

**Comment by biggikalli** [comment]
Worked like a charm :+1:
