### ISSUE TITLE
Logical validation 

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#290]
is there a way to validate field based on a field , lets say if there is a check box yes/no, and a text box ....

if yes is selected , disable , clear the text box, 
and how to implement custom validator such as age is mor then XX

**Comment by volkanceylan** [comment]
See form.AddValidationRule samples in code, you can write anything there

**Comment by zerodev** [comment]
thanks volkanceylan for the fast response,  but couldnt find form.AddValidationRule in template northwind? what sample code are you refering here

**Comment by volkanceylan** [comment]
OrderDetailDialog for example, how did you search?

**Comment by zerodev** [comment]
![untitled](https://cloud.githubusercontent.com/assets/728937/13202401/e5a1c9ca-d8a1-11e5-97e7-283a392cc3d8.png)

like this? is ther any other way

**Comment by volkanceylan** [comment]
Find in Files (Ctrl+Shift+F), solution explorer only searches for file names

**Comment by zerodev** [comment]
thanks found it , ithouth it was C# code , and it would have find it my bad, just to confirm its this path

C:\Users\tariq-k\Documents\Visual Studio 2013\Projects\ISACSerenityTest\ISACSerenityTest\ISACSerenityTest.Web\Scripts\serenity\Serenity.Script.UI.js

**Comment by volkanceylan** [comment]
No its C# code, OrderDialog.cs

**Comment by zerodev** [comment]
thanks will look at it
