### ISSUE TITLE
ReadOnly DateTimeEditor

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#2901]
Does DateTimeEditor has a readonly problem ?
It allows edit anyway.

**Comment by ANDY7575** [comment]
nope its working fine bro..have u installed updates n changed Jquiry reference in scriptbundle.json file..
applicable for updated version.

**Comment by brunobola** [comment]
@ANDY7575  Are you sure, i've used this in dialog.ts.

 this.form.DataInsercao.readOnly = true;~

And it still edits....

**Comment by brunobola** [comment]
@volkanceylan can you confirm this behaviour please.

**Comment by AlperanQ** [comment]
I tried both DateTimeEditor and DateEditor with ReadOnly attribute and it doesnt allow editing, so you probably have something misconfigured.

**Comment by ANDY7575** [comment]
@brunobola  why you are doin this this.form.DataInsercao.readOnly = true;
Apply readonly attribute on  form or Row  unless u have to Apply it on some condition..

**Comment by brunobola** [comment]
@ANDY7575 of course i need a condition it admin then not readonly else readonly.
It works with other editors timedit not, so must be a but i believe.

**Comment by brunobola** [comment]
Since no one give me a solution I have to thnks this is the default behaviour unlike other editors......

**Comment by ANDY7575** [comment]
@brunobola  sorry brother have no idea. Ask @volkanceylan master...

**Comment by volkanceylan** [comment]
Who said there is a readOnly property on DateTimeEditor? Using a property that is not there, and you are also getting TypeScript errors probably, and reporting it as a bug??

someEditor.set_readOnly(true)

or 

EditorUtils.setReadonly

**Comment by brunobola** [comment]
@volkanceylan you were right, this property exists with other lookup fields but not dateeditor, sorry my bad.

Yout could be more friendly thought, maybe its your english skills, but as you may know I try to help if I can, I don't use only your platform so not a specialist.

And by the way if someone buy the premium package your support will be like this even if user is a bit lazy ?

**Comment by volkanceylan** [comment]
I might not be so friendly sometimes, but should check if you are friendly enough.

There is nothing wrong with being novice but being lazy and reporting like there is fire somewhere is not something i tolerate, let's check some of your issues, and reporting style, e.g. CAPS and Exclamations and insisting BUGs:

Editor grids won't work as expected (like normal grids) !!!
BUG with Dialog Layout with Maximize and Close buttons - 3.0.6+
Serenity Calendar bug (while its calendar widget and its compatibility to jquery 3.0)

**Comment by brunobola** [comment]
@volkanceylan yes I understand, but I wan't I can check alot of issues that people asked you and you just answer "read the guide".... And worse, no need to prove my point, I never said anything personal to you and by the way most of these posts I give you the reason and know your platform is good.

You didn't answer to my questions if I give you 2000+ $$$ your answers will be the same ?

**Comment by dfaruque** [comment]
Hey guys cool down please.
@brunobola  If you need some help ask for help. Do not report bug/ something like that if you are not sure.

@volkanceylan  is working hard in this platform to improve further. He is trying to fix all bugs that are reported. When he see an issue with BUG then he expects that should be a really bug. 
So. please don't disturb him.

Thank you.

**Comment by volkanceylan** [comment]
You're asking me such a question and you are the one who is nice and me is the rude person? We're not living in your dream world, where you have right to be lazy as hell, and person who is working hard has to be nice as angels. If you give money I will send you to read damn guide. Because you must be pretty sure in bug. When you architect, write and test every little thing by yourself messages like ''BUUUUGGGGG OH SERENE DOESNT WORK'' makes you know. I use sore programming English but if you say its rude, well I dont know how to say reread documents, really.



https://github.com/volkanceylan/Serenity/wiki/Issue-Guidelines

**Comment by brunobola** [comment]
@volkanceylan You take things to much personal and why the use of "BUUUUGGGGG OH SERENE DOESNT WORK" ?

Don't really wan't to enter in that field becasu I always said your platform is good (not perfect) and you are a person like me, the diference is that I know how to make my pride not to cloud my mind and you on the other and seem more like a programmer with no good inter-personal/social skills (you know kindness) only if people give you something in return.

I like your platform but in terms of support you have a lot to learn.

That said always will consider you an excelent master programmer (with web based C#/MVC) and this is a pretty good platform, don't reaaly know you personally so just expressing my opinion based on what i have seen so far (please don't mistake this comments like if I'm attacking you nothing like that, I know you aren't from an english country, but please try to read carefully before responding).

Best regards, and will always help others if/when i can.

**Comment by Estrusco** [comment]
Guys stop here. Take a coffee, take a break. Discussing while you are angry does not take you anywhere.

Is a bad world, but here is a SERENE world ;)

**Comment by brunobola** [comment]
@Estrusco WIll do, but i'm not angry :)
