### ISSUE TITLE
Grid Of Class Own Properety Inside Dialog/panel

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2903]
Hello Everyone..
i have condition that, 
in myxyz dialog I want 1 field as ImageUploader
and rest fields will in grideditor of same XYZdialog..
is there any way..

Any help is appreciated..
thanx And Regards.
Aniket

**Comment by JohnRanger** [comment]
Hi Andy7575,

if I understand you correct, then that is the normal way how an imageuploader field and the rest of the fields work already.

ImageUploader will uploade Image/file and the rest of the fields will modify / add a grid row.

...or did I missunderstand your request?

With Kind regards,

John

**Comment by ANDY7575** [comment]
yes @JohnRanger  
I have not seen any sample ..
so,i u have one for reference, please share .
i want all field belongs to same class and having dialog of same with one field is uploadimage and rest will
be like added and on save or apply changes of dialog this field should be in grid of same dialog..
thank and regards,
Aniket

**Comment by ANDY7575** [comment]
Thanx @johnRanger..
