### ISSUE TITLE
HtmlContentEditor not working on Custom Request

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#2905]
Hi @volkanceylan , after updating Serenity to version 3.3.10 , HtmlContentEditor stoped working for custom on custom request based on row. See the problem with EmailSignature 
![image](https://user-images.githubusercontent.com/10474555/32692301-3a8490d2-c71e-11e7-85e1-73a019a71aed.png)

![image](https://user-images.githubusercontent.com/10474555/32692308-69afc57a-c71e-11e7-95f6-bb81499918da.png)

And here it is User row that contains HtmlContentEditor  for EmailSignature 

![image](https://user-images.githubusercontent.com/10474555/32692318-95be1040-c71e-11e7-858e-90934d248f18.png)

![image](https://user-images.githubusercontent.com/10474555/32692335-e25b963e-c71e-11e7-88e6-cd4c6291a467.png)

**Comment by volkanceylan** [comment]
this.form.EmailSignature.triggerHandler('shown')

**Comment by volkanceylan** [comment]
this.form.EmailSignature.element.triggerHandler('shown')

**Comment by Magik3a** [comment]
Thanks for the answer but is not working 
![image](https://user-images.githubusercontent.com/10474555/32699704-a5685d44-c7c2-11e7-9c8d-d7c51b2c453a.png)

**Comment by volkanceylan** [comment]
You need to execute that after making panel visible

**Comment by Magik3a** [comment]
i try with method after the panel is created
```javascript
<script type="text/javascript">
    $(function () {      
        var userPanel = new PatientManagement.Membership.EditUserProfilePanel($('#EditUserProfilePanel'));
        userPanel.visible();
    });
</script>
```

![image](https://user-images.githubusercontent.com/10474555/32702753-183680cc-c7f4-11e7-9b8d-f38291b4f03c.png)
but still no result

**Comment by volkanceylan** [comment]
You actually not using a dialog panel, but PropertyPanel so there is no change in latest versions related to your case. Better check script errors. As you can see below that's working pretty fine:

![image](https://user-images.githubusercontent.com/752470/32711962-e0bea50c-c852-11e7-9332-7acbba9c4c68.png)

**Comment by Magik3a** [comment]
Here the problem was from bootstrap tabs 
i use this to fix it:
`

    // hook into Bootstrap's tab JS
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        // get the ID of the textarea (I have IDs based on the tab pane ID)
        var paneId = $(this).attr('href').replace('#', '');
        var textareaId = 'content-' + paneId;
        console.log(paneId);
        // get the CKEditor instance and focus it
        $("#" + paneId + " .s-HtmlContentEditor").triggerHandler('shown');
    });

`
