### ISSUE TITLE
Possible bug: ByteArray translates to nvarchar on update

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#2907]
Hi,

I've been getting an new error which is being thrown by an update I call on a byte array property.

To be clear, I have run T4 transforms and rebuilt. 

The error itself is a conversion error and I've been able to isolate it in the update statement that is sent to the server.

```e.Message = "Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query."```

The update statement sent to the server is this one:

```UPDATE [dbo].[ReportContent] 
SET [ReportContentTitle] = @p1, 
[ReportContentOrder] = @p2, 
[ReportSectionId] = @p3, 
[ReportContactId] = @p4, 
[ReportDisclosureId] = @p5, 
[ReportContentText] = @p6, 
[ReportContentWordDocRef] = @p7, 
[ReportContentFile] = @p8,   <==== CORRESPONDING PROPERTY 
[DateAssigned] = @p9, 
[Deadline] = @p10, 
[DateCompleted] = @p11, 
[StatusId] = @p12, 
[OriginalFileName] = @p13, 
[DirectToIndex] = @p14 
WHERE ([ReportContentId] = @p15)
@p1 nvarchar(4000),
@p2 nvarchar(4000),
@p3 nvarchar(4000),
@p4 int,
@p5 int,
@p6 nvarchar(4000),
@p7 nvarchar(4000),
@p8 nvarchar(4000),  <====== THIS IS THE TRANSLATION
@p9 datetime2(7),
@p10 nvarchar(4000),
@p11 datetime2(7),
@p12 int,
@p13 nvarchar(4000),
@p14 bit,
@p15 int',
...
```

The ReportContentRow code is as follows:

```        
public byte[] ReportContentFile
        {
            get { return Fields.ReportContentFile[this]; }
            set { Fields.ReportContentFile[this] = value; }
        }

...

            public ByteArrayField ReportContentFile;
```

in my mind, the @P8 should be generating varbinary(4000).

Any help, suggestions if I'm doing something incorrectly would be appreciated.

**Comment by volkanceylan** [comment]
I'm not sure it would be possible. Make sure you don't have misused get / set, e.g. reading / writing from another column in your field get set statements.

**Comment by volkanceylan** [comment]
Something like this:

```
public string SomeField
        {
            get { return Fields.SomeField[this]; }
            set { Fields.SomeOtherField[this] = value; }
        }
```

**Comment by karimhyatt** [comment]
Hi Volkan, thanks for you response. That was also my first reaction. I did do a "find in files" in VS to see where it was being used. I have checked every instance of ReportContentFile to make sure it was being defined correctly. Even the generated code in ServerTypings is correct. 

The Create works correctly, by the way. It's only when I call Update manually that it seems to complain. I do have a workaround by updating the table manually in this one particular instance. 

The only place I can't debug at the moment is your code. But I will set up a new solution and try to replicate it. 

Please leave this open until I have had time to investigate further.

**Comment by volkanceylan** [comment]
Please reopen with replicate info.

**Comment by karimhyatt** [comment]
Hi Volkan,

It's taken me some time, but I did have some spare time and I make a few tests. 

The way to replicate:

Create a XXXRow with a field defined as byte[] (varbinary in sql).

Manually create a row and make sure the field has data in it and call the XXXRepository.Create()
Manually Create a row and make sure the byte field is null and call the XXXRepository.Create()

Now you should get the error above. 

The code works as long as the field is not null (i.e. you can put in an empty byte array and that seems to work. The code that fails is in . 

The trace during the create is:
```
SaveRequestHandler::ExecuteSave()
EntityConnectionExtensions::ToSqlInsert
SqlHelper::ExecuteAndGetID
SqlHelper::ExecuteReader
```
The query that is sent into ExecuteAndGetID from my code is:
```
"INSERT INTO [dbo].[ReportContent] ([ReportContentTitle], [ReportContentOrder], [ReportSectionId], [ReportContactId], [ReportDisclosureId], [ReportContentText], [ReportContentWordDocRef], [ReportContentFile], [DateAssigned], [Deadline], [DateCompleted], [StatusId], [OriginalFileName], [DirectToIndex], [ContentType], [TopicId]) VALUES (N'Headquarters', 7, 737, 2, 4766, NULL, N'content/00020_7qjohkuncfzrk.docx', NULL, '20170707', NULL, '20170710', 2, NULL, 0, 1, NULL)"
```
And this actually executes fine in SQL Server

The command that is sent into the ExecuteReader is
```
"INSERT INTO [dbo].[ReportContent] ([ReportContentTitle], [ReportContentOrder], [ReportSectionId], [ReportContactId], [ReportDisclosureId], [ReportContentText], [ReportContentWordDocRef], [ReportContentFile], [DateAssigned], [Deadline], [DateCompleted], [StatusId], [OriginalFileName], [DirectToIndex], [ContentType], [TopicId]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16);\nSELECT SCOPE_IDENTITY() AS IDCOLUMNVALUE"
```

And the parameter value @p8 is no longer null but blank (`{[@p8, ]}`. 

I'm wondering whether the interpreter changes this to a nvarchar in this particular case.

I hope I was specific enough. If not let me know what you need.
