### ISSUE TITLE
Showing date in NameField

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#2908]
I need to show date in Namefield instead of String. How can I do it? any help.
![image](https://user-images.githubusercontent.com/20435849/32697333-d20cc428-c7ab-11e7-9e54-4d69107dd49c.png)

Thank you.

**Comment by volkanceylan** [comment]
Use an expression field and CONVERT

**Comment by ms4hafiz** [comment]
Thank @volkanceylan 
It works as expected.
