### ISSUE TITLE
icon_sprite.png is not found in latest serenity

### ISSUE THREAD

**Issue by AlperanQ** [volkanceylan/Serenity#2909]
icon_sprite.png which is referenced in serenity.css datepicker next prev spans doesnt exist. 

Should probably convert it to data uri as well.

**Comment by karimhyatt** [comment]
Try this #2895. It solved all the problems for me.

**Comment by volkanceylan** [comment]
There are still two references that old sprites image in serenity.css that should be fixed.

@AlperanQ is right, he is Serenity employee btw.

**Comment by volkanceylan** [comment]
This is fixed in latest version.
