### ISSUE TITLE
Costume editor with a lookup from another module.table

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#291]
i Have a costume editor , actually 2 of them in a form one is working and the other is not as below 
the working one is in the same name space the other is form another one under one solution but am not able to debug it and get why its  not showing data, its saving data updating , and if i try override retrieve it gets all table content 
![untitled](https://cloud.githubusercontent.com/assets/728937/13204155/3cc33c5a-d8d1-11e5-8359-bbdf4f454d70.png)

**Comment by volkanceylan** [comment]
You probably didn't fill Country by looking up its ID from country lookup

**Comment by zerodev** [comment]
where should i do this? i followed the movie tutorial cast/movie and it worked perfectly with stakeholders am using MasterDetailRelation

**Comment by volkanceylan** [comment]
On your ValidateEntity method of GridEditor

**Comment by zerodev** [comment]
i used this after saving the selection from lookup but after saving the form and loading it dose not show the selected values i can see links for actions for country's but not the country name

**Comment by volkanceylan** [comment]
Add [MinSelectLevel(SelectLevel.List)] to your country name field

**Comment by volkanceylan** [comment]
Here is an excerpt from Movie Tutorial, this is where you missed:

We'll just have to make a little change in MovieCastRow.cs to select PersonFullname on retrieve (just like we did manually in MyRetrieveHandler):

```cs
[DisplayName("Actor/Actress"), 
 Expression("(jPerson.Firstname + ' ' + jPerson.Lastname)")]
[MinSelectLevel(SelectLevel.List)]
public String PersonFullname
{
    get { return Fields.PersonFullname[this]; }
    set { Fields.PersonFullname[this] = value; }
}
```
This ensures that PersonFullname field is selected on retrieve. Otherwise, it wouldn't be loaded as only table fields are selected by default.

**Comment by zerodev** [comment]
but country name is not an Expression field so i spiked this part ass it worked in the other one i have implemented

**Comment by volkanceylan** [comment]
It doesn't have to be expression field. By default only table fields are selected in list mode. Your country name is a foreign view field. It won't be loaded without this.

**Comment by zerodev** [comment]
thanks , just added the    [MinSelectLevel(SelectLevel.List)] and kaboom worked like charm u rock
seams i was missing this line sorry still learning on serenity
