### ISSUE TITLE
Multi tenant 

### ISSUE THREAD

**Issue by stefano5885** [volkanceylan/Serenity#2910]
I've implement Multitenant in a new project.
In Roles Table all seems ok, but, when I edit a Role-User-Permission with the related button "Edit Roles" in UserDialog i can see all Roles (also the roles assigned to another tenant).
I missing something?

In my opinion in UserRoleRepository.cs missing a check that verify if the every tenant's role in Roles table is equal to user's tenant. Right?

**Comment by volkanceylan** [comment]
Maybe you forgot to make roles lookup multi tenant? You know removing lookup script from row, and using tenantlookupscript etc?

**Comment by rodneykendall** [comment]
Did you get this working?  Thanks to the samples I was able to do the same thing and I'd be happy to paste my Roles repository code here if it'd help.

**Comment by JohnRanger** [comment]
Hi @rodneykendall ,

yes - please post your solution here for reference to others. That's how we can learn from each other...

With Kind regards,

John

**Comment by rodneykendall** [comment]
Sure thing.  First, an interface class is needed.  I decided to use the field 'clientid' instead of 'tenantid' for various reasons.  I also implemented the change tracking interface (ILoggingRow) on most of my row based classes as you'll see in the code below.  I also changed the project name to 'MyProject' here instead of the one I used to make it generic.

IClientRow interface:
`using Serenity.Data;

namespace MyProject
{
    public interface IClientRow
    {
        Int32Field ClientIdField { get; }
    }
}`

Then I defined a permission key (in AdministrationPermissionKeys.cs) to be used to setup a user as an admin (I also limited access to the dashboard, exception log, etc. as you can see here).

`using Serenity.Extensibility;
using System.ComponentModel;

namespace MyProject.Administration
{
    [NestedPermissionKeys]
    [DisplayName("Administration")]
    public class PermissionKeys
    {
        [Description("User, Role Management and Permissions")]
        public const string Security = "Administration:Security";

        [Description("Exception Log")]
        public const string ExceptionLog = "Administration:ExceptionLog";

        [Description("View Users")]
        public const string AdminViewOnly = "Administration:AdminViewOnly";

        [Description("Languages and Translations")]
        public const string Translation = "Administration:Translation";

        [Description("Manage Statuses, Types, Priorities and Teams")]
        public const string Lookups = "Administration:ISSUES";

        [Description("View Statuses, Types, Priorities and Teams")]
        public const string LookupsRead = "Administration:ISSUES:ReadLookups";

        [Description("Clients")]
        public const string Client = "Administration:AdminOnly";

        [Description("Access Dashboard")]
        public const string Dashboard = "View:Dashboard";
    }
}`

Next, a lookup script is needed since the basic lookup script doesn't limit the data by any field.  I called mine "MultiClientLookupScript".  The key here is 'AddClientFilter' which limits the list of values to the user's client id unless the user has the special permission key 'Client' (see above).

`namespace MyProject
{
    using Administration;
    using Serenity;
    using Serenity.Data;
    using Serenity.Web;
    using System;
    public class MultiClientLookupScript<TRow> : RowLookupScript<TRow>
        where TRow : Row, ILoggingRow, IClientRow, new()
    {
        public MultiClientLookupScript()
        {
            Expiration = TimeSpan.FromDays(-1);
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            AddClientFilter(query);
        }
        protected void AddClientFilter(SqlQuery query)
        {
            var r = new TRow();
            if (!Authorization.HasPermission(PermissionKeys.Client))
                query.Where(r.ClientIdField == ((UserDefinition)Authorization.UserDefinition).ClientId);
        }
        public override string GetScript()
        {
            return TwoLevelCache.GetLocalStoreOnly("MultiClientLookup:" + this.ScriptName + ":" +
                ((UserDefinition)Authorization.UserDefinition).ClientId,
                TimeSpan.FromHours(1),
                new TRow().GetFields().GenerationKey, () =>
                {
                    return base.GetScript();
                });
        }
    }
}`

Finally, the RoleRow class needed to be modified to use the above lookup script and supply the client id value through the ClientIdField property.
`
namespace MyProject.Administration.Entities
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;

    [ConnectionKey("Default"), DisplayName("Roles"), InstanceName("Role"), TwoLevelCached]
    [ReadPermission(PermissionKeys.Security)]
    [ModifyPermission(PermissionKeys.Security)]
    [LookupScript("Administration.Role", LookupType = typeof(MultiClientLookupScript<>))]
    public sealed class RoleRow : LoggingRow, IIdRow, INameRow, IClientRow
    {
        #region IClientRow implementation
        public Int32Field ClientIdField
        {
            get { return Fields.ClientId; }
        }
        [Column("CLIENT_ID")]
        public Int32? ClientId { get { return Fields.ClientId[this]; } set { Fields.ClientId[this] = value; } }
        public partial class RowFields { public Int32Field ClientId; }
        #endregion IClientRow implementation

        [DisplayName("Role Id"), Identity, ForeignKey("Roles", "RoleId"), LeftJoin("jRole")]
        public Int32? RoleId
        {
            get { return Fields.RoleId[this]; }
            set { Fields.RoleId[this] = value; }
        }

        [DisplayName("Role Name"), Size(100), NotNull, QuickSearch]
        public String RoleName
        {
            get { return Fields.RoleName[this]; }
            set { Fields.RoleName[this] = value; }
        }

        #region InsertUpdateUserNames
        [DisplayName("Created By"), ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jInsertUser"), Expression("T0.InsertUserId")]
        public Int32? INSERT_USER_ID { get { return Fields.INSERT_USER_ID[this]; } set { Fields.INSERT_USER_ID[this] = value; } }
        public partial class RowFields { public Int32Field INSERT_USER_ID; }

        [DisplayName("Created By"), Expression("jInsertUser.[DisplayName]")]
        public String InsertUserDisplayName { get { return Fields.InsertUserDisplayName[this]; } set { Fields.InsertUserDisplayName[this] = value; } }
        public partial class RowFields { public StringField InsertUserDisplayName; }

        [DisplayName("Updated By"), ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jUpdateUser"), Expression("T0.UpdateUserId")]
        public Int32? UPDATE_USER_ID { get { return Fields.UPDATE_USER_ID[this]; } set { Fields.UPDATE_USER_ID[this] = value; } }
        public partial class RowFields { public Int32Field UPDATE_USER_ID; }

        [DisplayName("Updated By"), Expression("jUpdateUser.[DisplayName]")]
        public String UpdateUserDisplayName { get { return Fields.UpdateUserDisplayName[this]; } set { Fields.UpdateUserDisplayName[this] = value; } }
        public partial class RowFields { public StringField UpdateUserDisplayName; }
        #endregion InsertUpdateUserNames

        IIdField IIdRow.IdField
        {
            get { return Fields.RoleId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.RoleName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public RoleRow()
            : base(Fields)
        {
        }

        public partial class RowFields : LoggingRowFields
        {
            public Int32Field RoleId;
            public StringField RoleName;

            public RowFields()
                : base("Roles")
            {
                LocalTextPrefix = "Administration.Role";
            }
        }
    }
}`

I hope that helps you along.

**Comment by rodneykendall** [comment]
I just realized that I missed a file!  The last file is the 'behavior' that overrides the pertinent methods on the repositories.

`using MyProject.Administration;
using Serenity;
using Serenity.Data;
using Serenity.Services;

namespace MyProject
{
    public class ClientBehavior : IImplicitBehavior, ISaveBehavior, IDeleteBehavior, IListBehavior, IRetrieveBehavior
    {
        private Int32Field fldClientId;

        bool IImplicitBehavior.ActivateFor(Row row)
        {
            var cr = row as IClientRow;
            if (cr == null) return false;
            fldClientId = cr.ClientIdField;
            return true;
        }

        void IDeleteBehavior.OnAfterDelete(IDeleteRequestHandler handler)
        {
        }

        void IListBehavior.OnAfterExecuteQuery(IListRequestHandler handler)
        {
        }

        void IRetrieveBehavior.OnAfterExecuteQuery(IRetrieveRequestHandler handler)
        {
        }

        void ISaveBehavior.OnAfterSave(ISaveRequestHandler handler)
        {
        }

        void IListBehavior.OnApplyFilters(IListRequestHandler handler, SqlQuery query)
        {
        }

        void ISaveBehavior.OnAudit(ISaveRequestHandler handler)
        {
        }

        void IDeleteBehavior.OnAudit(IDeleteRequestHandler handler)
        {
        }

        void IDeleteBehavior.OnBeforeDelete(IDeleteRequestHandler handler)
        {
        }

        void IListBehavior.OnBeforeExecuteQuery(IListRequestHandler handler)
        {
        }

        void IRetrieveBehavior.OnBeforeExecuteQuery(IRetrieveRequestHandler handler)
        {
        }

        void ISaveBehavior.OnBeforeSave(ISaveRequestHandler handler)
        {
        }

        void ISaveBehavior.OnPrepareQuery(ISaveRequestHandler handler, SqlQuery query)
        {
        }

        void IDeleteBehavior.OnPrepareQuery(IDeleteRequestHandler handler, SqlQuery query)
        {
        }

        void IListBehavior.OnPrepareQuery(IListRequestHandler handler, SqlQuery query)
        {
            var user = (UserDefinition)Authorization.UserDefinition;
            if (!Authorization.HasPermission(PermissionKeys.Client))
                query.Where(fldClientId == user.ClientId);
        }

        void IRetrieveBehavior.OnPrepareQuery(IRetrieveRequestHandler handler, SqlQuery query)
        {
            var user = (UserDefinition)Authorization.UserDefinition;
            if (!Authorization.HasPermission(PermissionKeys.Client))
                query.Where(fldClientId == user.ClientId);
        }

        void ISaveBehavior.OnReturn(ISaveRequestHandler handler)
        {
        }

        void IDeleteBehavior.OnReturn(IDeleteRequestHandler handler)
        {
        }

        void IListBehavior.OnReturn(IListRequestHandler handler)
        {
        }

        void IRetrieveBehavior.OnReturn(IRetrieveRequestHandler handler)
        {
        }

        void ISaveBehavior.OnSetInternalFields(ISaveRequestHandler handler)
        {
            if (handler.IsCreate && !Authorization.HasPermission(PermissionKeys.Client))
            {
                fldClientId[handler.Row] = ((UserDefinition)Authorization.UserDefinition).ClientId;
            }
        }

        void ISaveBehavior.OnValidateRequest(ISaveRequestHandler handler)
        {
            if (handler.IsUpdate)
            {
                var user = (UserDefinition)Authorization.UserDefinition;
                if (fldClientId[handler.Old] != fldClientId[handler.Row])
                    Authorization.ValidatePermission(PermissionKeys.Client);
            }
        }

        void IDeleteBehavior.OnValidateRequest(IDeleteRequestHandler handler)
        {
            var user = (UserDefinition)Authorization.UserDefinition;
            if (fldClientId[handler.Row] != user.ClientId)
                Authorization.ValidatePermission(PermissionKeys.Client);
        }

        void IListBehavior.OnValidateRequest(IListRequestHandler handler)
        {
        }

        void IRetrieveBehavior.OnValidateRequest(IRetrieveRequestHandler handler)
        {
        }
    }
}`

**Comment by volkanceylan** [comment]
Thanks for sharing, closing.

**Comment by tynmas02** [comment]
Hi! I know that this issue has been closed, but there is a simpler way to do this @stefano5885 . Add [LookupScript("Administration.Role", LookupType = typeof(MultiTenantRowLookupScript<>))], in RoleRow .Rebuild and Transform all T4 Templates and it will fix your problem.
