### ISSUE TITLE
GitBook döküman

### ISSUE THREAD

**Issue by safakseyrek** [volkanceylan/Serenity#2912]
https://www.gitbook.com/book/volkanceylan/serenity-guide
Döküman linki çalışmıyor lütfen biryere yükleyebilir misiniz ?

**Comment by AlperanQ** [comment]
Verdiğiniz linkten PDF olarak indirebilirsiniz. İyi günler.

**Comment by safakseyrek** [comment]
Türkçe hali var mı acaba şuan ?

**Comment by AlperanQ** [comment]
Malesef henüz tam olarak Türkçe hali bulunmamakta.
