### ISSUE TITLE
No sound on Youtube tutorial videos and they go super fast

### ISSUE THREAD

**Issue by astrohart** [volkanceylan/Serenity#2914]
Hi,

I browsed in YouTube to the "Serenity Application Framework" channel, at:
https://www.youtube.com/channel/UCUL4l2DlXCOCprdUfsoP0iw/featured

Your videos are very unhelpful.  They have zero sound, so I can't really follow along mentally with what is being done, and the screens are clicked very fast, making it necessary to pause the video frequently.

I think Serenity/Serene is a good choice for ASP.NET LOB application development; however, the support side leaves much to be desired with these bad videos.  They really need to have sound added to them.

Brian Hart

**Comment by volkanceylan** [comment]
Those videos are a contribution made by a community member just like you. You could be a bit nicer to that person as he probably spent much time to do them without having any obligacy to do so.

Guide is the recommended source. If that leaves much to be desired, you may look elsewhere.

**Comment by astrohart** [comment]
No one is trying to be mean.  It's just feedback.

**Comment by JohnRanger** [comment]
Hi Astrohart,
the Support side here is absolutely fantastic - if you would have been arround since the starting time, you would know the direct Support by Volkan and many top developers.

Yes - the Videos have some improvement potential - why don't you get in contact with the creator of These Videos and help improve them? :-)

With Kind regards,

John

**Comment by judejay** [comment]
Speaking as a complete novice, (I only know some VB, and html), the "serenity guide" is the only place to start. I've got most of my demo web app done, I'm stuck only on joining the notes table, to the rest of them. I suspect any waste of the developers time on video, will not be any benefit to most people. If you ask me and no-one did, you need to play to your strengths and finish sergen, It needs to be able to assign relationships between two or more tables. It's almost there, but when I have EXISTING tables that sergen can't pick up the Private key from the foreign, the novice user like me, needs to do joins assign relationships. All the features that you are rich enough, but I will cut most of them. Play to your strengths handling large amounts of data easily.

**Comment by samdubey** [comment]
@astrohart No worries Brian, I will add sound to that video and will add more videos on ASP.NET Core 2.0 based serenity package. videos are in making please be patient it will be released soon
thanks for feedback, no hard feeling here
