### ISSUE TITLE
Add Validation to check already stored Data

### ISSUE THREAD

**Issue by Daffyydd** [volkanceylan/Serenity#2915]
Hi,

I have the following fields in the form.
1. BeneficiallyId
2. MemberId
3. Relationship
4. Percentage

A member can have more that one beneficially, however the Percentage allocated to Beneficiaries should not exceed 100%

I need to validate this before saving the form. How do I go about it.

Regards
David

**Comment by Estrusco** [comment]
You can call override BeforeSave() in your MySaveHandler in xyzRepository.

```cs
private class MySaveHandler : SaveRequestHandler<MyRow>
{
    protected override void BeforeSave()
    {
        base.BeforeSave();

        [...] your chek
        if (!)
           throw Exception("error");
    }
}
```
