### ISSUE TITLE
HTML to PDF - Chart Support and Page Per Order

### ISSUE THREAD

**Issue by zKarp** [volkanceylan/Serenity#2916]
2 questions regarding the HTML to PDF capability.

1. How would you create a report listing all orders by customer, with each order being it's own page in a pdf? IE- Customer A has 5 orders, a 5 page PDF will be produced.

2. Has anyone gotten one of the chart libraries to work with html2pdf?

**Comment by volkanceylan** [comment]
Hi @zKarp,

You could put each order in a separate div of its own and apply CSS property page-break-after: always to add a page break.

Usual charts we use in dashboard etc. should probably work with wkhtml2pdf, have you got any errors?

**Comment by zKarp** [comment]
Thanks @volkanceylan!

I was having issues with the charts not displaying when I took a first crack at it. Either the library I used wasn't supported or I had a syntax error somewhere. Either case it works. 

Thanks.

/closed
