### ISSUE TITLE
How to hide Bootstrap Tab in form

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#2918]
Hi, I want to hide some tabs base on some condition, 
someone please tell me how?

![image](https://user-images.githubusercontent.com/16621563/32763797-194089ca-c92c-11e7-86d6-6dbbec9f265f.png)

**Comment by Estrusco** [comment]
Try some like this

```ts
var aElements = $(".nav-tabs").children("li").children("a");
var aEl = Q.first(a, x => x.text == "Attachments");  // title of tabs
$(aEl).parent().hide(); // or show
```

**Comment by dfaruque** [comment]
I have written a utility function to do that
```ts
        static hideEditorTab(editor: Serenity.Widget<any>, value: boolean = true) {
            let tabId = editor.element.closest('.tab-pane').hide().attr('id');

            let tabAnchor = editor.element.closest('.s-PropertyGrid').find(`a[href='#${tabId}']`);

            tabAnchor.closest('li').hide();
        }
```

usage:

`hideEditorTab(this.form.LicenseNo);`

**Comment by volkanceylan** [comment]
I should probably add something similar to property grid, thanks

**Comment by kilroyFR** [comment]
yes would be great to add something similar in addition to :
`Serenity.TabsExtensions.setDisabled()`
 to hide conditionally some tabs
