### ISSUE TITLE
xyzDialog.cs; Using a xyzRow.cs to find the current max value of a field does not update on adding new records

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#292]
Hi JaiQ,

John Ranger here again :-)

the challenge: probably again a LookupScript Problem - but this time on Client side.

I have a Dialog (Jobstatus) where I want to add the diverse Job stati into a table (normal sergen-generated grid and dialog).

In this table, there are (among others) two fields:
- JobTypeID (a Dropdown, feed from another table called JobTypes via Lookupscript)
- JobStep  (where I freely can define a number from 0-n for the above jobtype)

Hint: The Jobstatus-Table also has a lookup script on it.

Now...

I want that when the user chooses a Job type, that in the JobStep field the next free jobstep number is automatically provided.

For this, I have added the following code to the constructor of the xyzDialog.cs:

```cs

var MaxValue = 0;

            form.JobTypeId.Change(e =>
            {
                //Q.Alert("JobTypeID: " + form.JobTypeId.Value);
                
                if (form.JobTypeId.Value != null)
                {
                    JobStatusRecords = myJobStatus.Lookup.Items.Where(x => x.JobTypeId == form.JobTypeId.Value.ToInt32());

                    //Q.Alert(JobStatusRecords.Count().ToString());

                    if (JobStatusRecords.Count() != 0)
                    {
                        MaxValue = JobStatusRecords.Max(x => (int)x.JobStatusStep);
                    }
                    else
                    {
                        MaxValue = 0;
                    }

                }
                
                MaxValue++;
                form.JobStatusStep.Value = MaxValue;
                form.JobStatusStep.GetGridField().Property("title", new LocalText("Forms.JobManagement.JobStatusDialog.NextFreeStepNumber").ToLocaleString());
            });
```
This works fine for the first record which I add after I have opened the browser. The next record to be added while still on the xyzGrid will show the same max value. If I move to another grid (e.g. Delivery) and then move back to the xyzGrid, adding another record seems to properly calculate the next free jobstep number.

As I have understood you from one of our last conversations, the LookupScript on the Server side is rebuilt when an insert/update/delete occurs on the related table. So as there is a normal insert on the table, the server-side lookupscript should automatically be updated. --> This is confirmed by the fact that when I move to another grid and then come back to the Jobstatus grid, the lookupscript is refreshed.

But how can I force the client-side to refresh its lookup script at adding of the record?

I have looked around but didn't find a command to flush Cache or do a forced reload of the lookupscript or something similar.

Thanks again for your help and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Q.ReloadLookup ;)

**Comment by volkanceylan** [comment]
This is third time today this is asked, i just don't know where to put this information other than FAQ in guide.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks again for your excellent Feedback. Works perfectly.

Regarding the FAQ: I nearly cannot Keep up with downloading and re-reading your very good dev-guide. :-)

From my Point of view it would be extremely useful to have an online, searchable and timestamp-sortable FAQ beside the open/closed issues so that new FAQ entries can be spotted easily (e.g. every day I can look up the new FAQs which have been added since one day ago).

Would it make sense for you to have such a FAQ directly on Github?

Have a nice evening 

and 

with Kind regards,

John

**Comment by volkanceylan** [comment]
Unfortunately, Github doesn't offer such a feature. There is only wiki pages. Anyway you may follow changes to guide directly from github 

https://github.com/volkanceylan/serenity-guide/commits/master
