### ISSUE TITLE
Synchrone webservice

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#2920]
Hello all,

I want to use a synchrone webservice call in Serene, to fill a CheckTreeEditor :

is this the way to do it ?   I tried asynchrone call, creating CheckTreeItems in the response callback, but then types of List-service and CheckTreeItem are conflicting.....

 protected getTreeItems() {

            Administration.UserService.List({
            }, response => {
                this.userList = response.Entities.map(x => x);
                }
                , (ServiceOptions => { ServiceOptions.async = false } ));

            return this.userList.map(user => <Serenity.CheckTreeItem<any>>{
                id: user.UserId.toString(),
                text: user.Username
            });
  }

**Comment by GreenUtil** [comment]
My asynchrone call is not working :

Administration.UserService.List({
            }, response => {
                this.userList = response.Entities.map(x => x);
                return this.userList.map(user => <Serenity.CheckTreeItem<any>>{
                    id: user.UserId.toString(),
                    text: user.Username
                })});

Because of : 

1>    Types of property 'getTreeItems' are incompatible.
1>      Type '() => void' is not assignable to type '() => CheckTreeItem<any>[]'.
1>        Type 'void' is not assignable to type 'CheckTreeItem<any>[]'.

**Comment by volkanceylan** [comment]
```ts
Administration.UserService.List({ ...
}, response => { ... }, { async: false });
```

**Comment by GreenUtil** [comment]
Great, thank you very much, it's a big difference between ":" and "="  when setting options....
