### ISSUE TITLE
Serenity.Core template missing Exceptions Log?

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#2921]
When creating a new template from `serin` I noticed that the Exceptions Log doesn't come with the template. Did I do something wrong or is this by design now? Been using Serenity for over a year and a half now, still loving it.

![image](https://user-images.githubusercontent.com/11448029/32776655-40964530-c901-11e7-8735-e029907b354f.png)

**Comment by volkanceylan** [comment]
That's not available in .NET core
https://www.nuget.org/packages/StackExchange.Exceptional/

**Comment by williamhodges** [comment]
Gotcha, thanks Volkan.
