### ISSUE TITLE
Attribute for client side that not override editor

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2922]
Hi @volkanceylan 

Is it possible to create attribute/editor for form's fields that isn't derived from Serenity.Widget and that not override existent editor?

I want to make an attribute for add data to element, but this data must be added to existing element and editor. 

I would like to have 

```cs
public class xyzForm 
{
      [IntegerEditor(MaxValue = 999), ExtraData(value = 1, other = 2, ecc...)]
      public Int32 IntegerEditor { get;set; }

      [ExtraData(value = 1, other = 2, ecc...)]
      public String TextEditor { get;set; }

      [...]
}
```

Thanks

**Comment by volkanceylan** [comment]
I'd recommend subclassing editor type and adding some option like extraData

**Comment by Estrusco** [comment]
OK, some like this for each editor I want?

```ts
export class StringExtEditor extends class StringEditor {
        [...]
}

export class IntegerExtEditor extends class IntegerEditor {
        [...]
}
```

**Comment by volkanceylan** [comment]
Yes and a helper method to apply that maybe. Another option is to use a custom editorOption that won't be used e.g. EditorOption("extraDataValues") or something like that and overriding Widget constructor:

Serenity.Widget.prototype = ...

**Comment by Estrusco** [comment]
Oh ok, I will try this.
Thank you very much!
