### ISSUE TITLE
serenity.is/demo does not work properly at current moment

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2923]
Hi @volkanceylan ,

at the Moment (2017-11-14 16:30 CET+1) your demo of Serene does not work properly. The Login page only Shows a Grey Panel.

This Problem is with Internet Explorer 11. With Chrome it renders correctly.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Thanks John for reporting, fixed.

**Comment by JohnRanger** [comment]
Hi Volkan,

confirmed, works again with IE11. Thanks for Fixing it.

With Kind regards,

John
