### ISSUE TITLE
Retrieve information from the main dialog when updating and closing

### ISSUE THREAD

**Issue by alexdaywid** [volkanceylan/Serenity#2925]
How could I retrieve updated information in my DialogClient when updating and closing DialogPersonal.
I provisionally created an update button that retrieves and updates the information in the ClientForm.

![updatedialog](https://user-images.githubusercontent.com/6788801/32793494-33b603a4-c94d-11e7-9f6a-cbfe6a40a3dd.png)

**Comment by rodneykendall** [comment]
Depending upon how you open that dialog, you could cache a reference to 'this.form' on the ClientForm that you pass into the dialog upon creation and use that to set the fields on ClientForm from the values on your dialog before you close the dialog.

**Comment by alexdaywid** [comment]
@rodneykendall would you have some code for example?

**Comment by volkanceylan** [comment]
See updating Populate Linked Data sample, basically your refresh button should do same thing.

**Comment by volkanceylan** [comment]
http://serenity.is/demo/BasicSamples/PopulateLinkedData

**Comment by alexdaywid** [comment]
What I would like to do and when closing the dialog person he will update the information of the client dialog.

**Comment by volkanceylan** [comment]
Though didn't understand difference, you may reload record by id, e.g. loadById.
