### ISSUE TITLE
Trying to make Result<ServiceResponse> method async Task

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#2926]
**I tried** 

`        [HttpPost, JsonFilter]
        public async Task<Result<ServiceResponse>> ForgotPassword(ForgotPasswordRequest request)
`

**and to return** 

`  return new Result<ServiceResponse>(new ServiceResponse());`

**But i still get the yellow screen instead the exception wrapper alert.

Cant make it work.**

**Comment by volkanceylan** [comment]
We don't support async tasks in service endpoints. You may use that in regular pages, but its not something related to Serenity at all.
