### ISSUE TITLE
serenity.dialogs.less

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#2928]
Say I want to override something in the `Serene` template that comes from Serenity. Example: `https://github.com/volkanceylan/Serenity/blob/master/Serenity.Web/Style/serenity.dialogs.less`. How would I go about overriding that?

**Comment by volkanceylan** [comment]
Override in your site.less

**Comment by williamhodges** [comment]
Sorry Volkan, what do you mean by override it in my site.less?

**Comment by williamhodges** [comment]
![image](https://user-images.githubusercontent.com/11448029/33159403-a8b613bc-cfe0-11e7-896a-46989aff3d97.png)

That is what I'm working with. I can't seem to find where I can change the or remove the `span` tags. Any ideas?

**Comment by williamhodges** [comment]
Any idea?
