### ISSUE TITLE
xyzDialog.cs; Intercepting Save-and-close-button with Confirm dialog; save entity when clicking on yes

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#293]
Hi JaiQ,

again me, John Ranger :-)

I have a "sensitive" Dialog - the Client wiping Dialog - where I really want to enforce it on the guys to be really sure that they want to wipe a specific Client.

For this, I have intercepted the save-and-Close-button in the protected override List<ToolButton> GetToolbarButtons() method like this:

```cs

 protected override List<ToolButton> GetToolbarButtons()
        {
            var buttons = base.GetToolbarButtons();

            // *** Only get the save-and-close button
            var newButtons = new List<ToolButton>();
            newButtons.Add(buttons[0]);

            // *** Ask for wiping confirmation ***
            newButtons.First(x => x.CssClass == "save-and-close-button").OnClick = delegate
            {
                Q.Confirm(new LocalText("Dialogs.Wiping.ClientWiping.WipingConfirmation").ToLocaleString(), delegate
                        {
                            // *** Save Entity here ***
                            //this.Save();

                            DialogClose();
                        }
                        , new ConfirmOptions { DialogClass = "s-MessageDialog s-WarningDialog", HtmlEncode = false });

            };

            return newButtons;

        }

```
With the current implementation of mine, the record does not get updated because there is missing the this.Save(???) line.

As I could not figure it out how to parameterize this function (even with looking into goto definition), I allow myself to ask you how to parameterize it so that the Standard server-side calls are done.

Thanks again and

With Kind regards,

John

**Comment by volkanceylan** [comment]
What about calling

Save(response => this.DialogClose());

Does this cause a problem?

**Comment by JohnRanger** [comment]
Hi JaiQ,

no, that works perfectly, thank you very much. 

For the benefit of other Readers, here the whole code block if you Need to get confirmation on clicking the save-and-Close button. Please note that I remove here all Buttons in the toolbar and only take the first one (the save-and-Close-button):

```cs
protected override List<ToolButton> GetToolbarButtons()
        {
            var buttons = base.GetToolbarButtons();

            // *** Only get the save-and-close button
            var newButtons = new List<ToolButton>();
            newButtons.Add(buttons[0]);

            // *** Ask for wiping confirmation ***
            newButtons.First(x => x.CssClass == "save-and-close-button").OnClick = delegate
            {
                Q.Confirm(new LocalText("Dialogs.Wiping.ClientWiping.WipingConfirmation").ToLocaleString(), delegate
                        {
                            // *** Save Entity here ***
                            Save(response => this.DialogClose());
                            
                        }
                        , new ConfirmOptions { DialogClass = "s-MessageDialog s-WarningDialog", HtmlEncode = false });

            };

            return newButtons;

        }

```
I just didn't know this Syntax and I could not reverse-engineer it from the whole solution. 

Please remember: I am just an Admin with some dev enthusiasm ;-)

With Kind regards,

John.
