### ISSUE TITLE
Call a service from an external application

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#2930]
Hi all,

I've a custom Endpoint.cs that do an import of some CSV files. Here is my code:
![immagine](https://user-images.githubusercontent.com/22232670/32840190-3fb9d75a-ca17-11e7-9a82-ab848762c5f2.png)

How can I call that method from an external application (so I have to let the method bypass the Login Authentication) ?

I also tried to call manually the service from my browser (like **http://localhost:<port>/Services/Common/Anagrafiche/methodName**), but it gives me a 404 Error.

Thanks for your help and your time :)

Chiara

**Comment by Estrusco** [comment]
See if this can help you 

https://github.com/volkanceylan/Serenity/issues/806
or 
https://github.com/volkanceylan/Serenity/issues/1310

**Comment by kjaraa** [comment]
Thanks @Estrusco: I took a look at the two tickets and I add this attributes in my code:

![immagine](https://user-images.githubusercontent.com/22232670/32879452-55e72e36-caaa-11e7-9882-d5541d500118.png)

But when I call the service from my browser, it still gives me a 404 error and I can't get to the method (there is a breakpoint).

Any ideas ??

Thanks all :)

**Comment by Zahar661** [comment]
hm! Maybe you need a controller to run?

**Comment by Zahar661** [comment]
Or do a start on the button, like Import from Excel

**Comment by kjaraa** [comment]
Thanks for your response @Zahar661 :)

I don't use a button because an external application called the URL that is connected to this method.
End user shoud not see this procedure.
I try to use a controller ...

**Comment by Zahar661** [comment]
Pay attention to AccountPage.cs, as the entry point, direct access to the Endpoint, it does not seem to work

**Comment by volkanceylan** [comment]
A 404 means page is not found, not some server / permission error, make sure you are calling the correct URL

**Comment by kjaraa** [comment]
I solved that: I used a Controller with the Index() that call my custom method.
I share my code.
![immagine](https://user-images.githubusercontent.com/22232670/32905920-b2f29218-cafb-11e7-9c7a-d6a42e1f1aa8.png)

Thanks for your help @Estrusco,  @Zahar661 and @volkanceylan :)

Good Evening :)

Chiara
