### ISSUE TITLE
Email adress validation

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#2931]
Hello all,

I encountered the following behaviour in the SignUp/New user functionality with respect to the Email adress validation : 

email adress  with  format  ab.cd@nl.abc.com   is not valid.......

I am trying to find out how to fix this : 

**public class SignUpForm
    {
        [Required(true), Placeholder("Full name")]
        public String DisplayName { get; set; }
        [EmailEditor, Required(true), Placeholder("Email")]
        public String Email { get; set; }
        [EmailEditor, Required(true), Placeholder("Confirm email")]**

And then

 **public class EmailEditorAttribute : CustomEditorAttribute, ICustomValidator
    {
        public static readonly Regex EmailPattern;

        public EmailEditorAttribute();

        public string Domain { get; set; }
        public bool ReadOnlyDomain { get; set; }

        public string Validate(IValidationContext context);
    }**

Next thing is how to investigate this EmailPattern.......where is it defined ?

**Comment by volkanceylan** [comment]
It's jquery validate email pattern, see jquery validate docs for replacing validation methods.

**Comment by GreenUtil** [comment]
Thanks again....
