### ISSUE TITLE
Serenity.Decorators.panel - toolbar and categories not sticky

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2932]
Hey all
I love the new Serenity.Decorators.Panel i think it makes the user experience even more friendly. But i have one major issue with it: the Toolbar and categories dont stick, meaning when you scroll down  they disappear in a form that has many fields. Can anyone help me where i can fix this? (im sure many others will want the same functionality) 
Thanks!

**Comment by javaman63** [comment]
Another new functionality is the use of the [Tab] Atribute
on your xyzForm you can use with your fields
[Tab("YourTab")]
public Int32 IdPlace{ get; set; }
Is not a solution for your problem, but it work like a workaround i think

**Comment by shakazulu89** [comment]
hmm thats not bad at all. i can live with it! thanks for the quick reply @javaman63

**Comment by shakazulu89** [comment]
so ... still need these floating categories :) 
has anyone come across a solution for this?

**Comment by volkanceylan** [comment]
In panel mode, page should scroll, so give some fixed height to categories.

**Comment by shakazulu89** [comment]
thanks volkan ill give it a try

**Comment by haajit** [comment]
> In panel mode, page should scroll, so give some fixed height to categories.
Hi

**Comment by shakazulu89** [comment]
i know this is super old but just wanted to thank you @haajit  this worked with a few little tweaks:

```
.category-links.sticky {
    position: fixed;
    background-color:lightblue;
    color:black !important;
    z-index:10000;
    right: unset;
    width: calc(100% - 20px);
    top: 50px;
}
.category-links.sticky > a { 
    color: black !important; 
}
```
