### ISSUE TITLE
Drag & Drop the Elements of a ListField<Int32> to Sort it

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#2934]
Hi there!

Is there any way (some attribute?) that allows me to order a List32Field using the drag and drop?
This is what I want to achieve:

![drag](https://user-images.githubusercontent.com/8239681/32862415-cdc6e29e-ca36-11e7-8e83-470c3cbd7b6f.png)

**Comment by volkanceylan** [comment]
No that's not supported, linking list behavior won't keep order anyway.

**Comment by javaman63** [comment]
Ok thank you Volkan
