### ISSUE TITLE
SlickGrid/GridEditorBase not sorting on RestSharp samples

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2935]
In the samples i noticed all GridBaseEditor have no sorting capabilities.
Tried to add them autocolumnresize.js plugin with no luck.

 ![serenity1](https://user-images.githubusercontent.com/31513956/32862934-028fdc10-ca5a-11e7-876a-96d75a5de18e.jpg)

**Comment by volkanceylan** [comment]
You should search prior issues, probably Nth time repeating, in memory grids doesn't support sorting.
