### ISSUE TITLE
[3.3.11] Grid not auto resized

### ISSUE THREAD

**Issue by jas2008** [volkanceylan/Serenity#2936]
Hi,

Grid in dialog form not resized to full height after upgrade,  

The following code was working fine before, but not working after upgrade.
                  
            Q.initFullHeightGridPage($('#GridDiv'));

![image](https://user-images.githubusercontent.com/5105376/32873054-e32b19e6-cac4-11e7-940a-f965727c6595.png)

Thanks

**Comment by volkanceylan** [comment]
That function is only targeted for full page grids, not grids in dialogs or panels

**Comment by jas2008** [comment]
In dialogOpen(), attached windows event to resize grid : 


            this.element.on("dialogextendmaximize", function (event, ui) {
                selfDialog.theGrid.slickGrid.resizeCanvas();
            });
            this.element.on("dialogextendrestore", function (event, ui) {
                selfDialog.theGrid.slickGrid.resizeCanvas();
            });
            this.element.on("dialogresize", function (event, ui) {
                selfDialog.theGrid.slickGrid.resizeCanvas();               
            });


used to be working fine. somehow broken now.

**Comment by volkanceylan** [comment]
Sorry, there is no such change.
