### ISSUE TITLE
Read only error when cloning entity

### ISSUE THREAD

**Issue by gdeacon** [volkanceylan/Serenity#2938]
Hi,
I've implemented the audit logging described in the Wiki.  All is working well until I attempt to implement cloning.  When I attempt to save a cloned entity I get an error stating that the InsertUserId is read-only.  Here's the definition of those audit fields per the Wiki ariticle

        [NotNull, Insertable(false), Updatable(false)]
        public Int32? InsertUserId
        {
            get { return loggingFields.InsertUserId[this]; }
            set { loggingFields.InsertUserId[this] = value; }
        }

        [NotNull, Insertable(false), Updatable(false)]
        public DateTime? InsertDate
        {
            get { return loggingFields.InsertDate[this]; }
            set { loggingFields.InsertDate[this] = value; }
        }

I'm also overriding the  getCloningEntity method for my entity dialog and am setting those fields to null thinking that it was pulling the values from the clone...

        protected getCloningEntity() {
            var clone = super.getCloningEntity();

            // add (Clone) suffix if it's not already added
            var suffix = ' (Clone)';
            if (!Q.endsWith(clone.BusinessKey || '', suffix)) {
                clone.BusinessKey = (clone.BusinessKey || '') + suffix;
            }

            clone.InsertUserId = null;
            clone.InsertDate = null;
            clone.UpdateDate = null;
            clone.UpdateUserId = null;

            return clone;
        }//eom

Do I need to relax the Insertable attributes?  If I do that will that affect the auditing functionality?

ps I did search for a similar issue with no luck but If there is one already let me know thanks in advance for your help

-Garrett

**Comment by volkanceylan** [comment]
You may try deleting those, null values are still there.

delete clone.InsertUserId

Anyway, save handlers ignores null values assigned to readonly fields actually. Maybe you didn't implement IInsertLogRow etc?

**Comment by gdeacon** [comment]
I tried your suggestion with no luck (see below)
        protected getCloningEntity() {
            var clone = super.getCloningEntity();

            // add (Clone) suffix if it's not already added
            var suffix = ' (Clone)';
            if (!Q.endsWith(clone.BusinessKey || '', suffix)) {
                clone.BusinessKey = (clone.BusinessKey || '') + suffix;
            }

            delete clone.InsertUserId;
            delete clone.InsertDate;
            delete clone.UpdateDate;
            delete clone.UpdateUserId;

            return clone;
        }//eom

My row classes are direct subclasses of  LoggingRow from Administration.Entities so the implementation is the one for the User Entity I'm not reinventing the wheel here.  Any suggestions?  Should I not derive from LoggingRow?  I figured that was the smarter move since I have full control of the field names.

Thank you for the quick response.
-garrett

**Comment by volkanceylan** [comment]
I dont know, if it is working in sample, but not yours then there should be some difference you have, e.g. some master detail.

**Comment by gdeacon** [comment]
Yes the Entity in question does have several master/detail relationships.  The User UI doesn't support cloning (ie the toolbar does not have the clone botton).  I could turn it on and see what happens as an exercise.  If it works then maybe it's the master/detail.  If it is the master/detail how do I drill into those entities and set their InsertUserId to null

**Comment by volkanceylan** [comment]
They r simple arrays inside your entity, so for k of and clean

**Comment by gdeacon** [comment]
OK let me try the delete call for all the child entities and see what happens again thank you for your help.
-Garrett

**Comment by gdeacon** [comment]
Hi Volkan,

I did what you suggested I iterated through all of the child entities that make up the details and called delete on their respective audit fields.  Cloning is working great.

Thank you for the help
