### ISSUE TITLE
Sergen.exe dökümantasyon farkı

### ISSUE THREAD

**Issue by safakseyrek** [volkanceylan/Serenity#2939]
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/img/sergen_tenants.png

yukarıdaki link dökümantasyondaki sergen.exe formu.
aşağıdaki benim nuget ile yüklediğim sergen.exe

![screenshot_2](https://user-images.githubusercontent.com/8484502/32897971-f5a335a8-caf7-11e7-94b5-486406d0cf32.png)

Tamamen farklı bunu nasıl düzeltebilirim ?

**Comment by volkanceylan** [comment]
Düzeltilecek bir durum yok, bağlantıyı seçin, parametreleri satır editörler yerine kolonlarda düzenleyin, bu kadar.

**Comment by safakseyrek** [comment]
Cevabın için çok teşekkürler ama sormak istediğim bu değildi . 
Bahsettiğim aşağıda işaretlediğim gibi işaretlediğim alanlar. 👍 
![screenshot_3](https://user-images.githubusercontent.com/8484502/32902670-13f251e0-cb04-11e7-9e04-3c9f3e609d7a.png)

**Comment by volkanceylan** [comment]
İşte o gösterdiğin alanları kolona yazacaksın, kılavuzu baştan okursan nasıl kullanıldığını görebilirsin.

**Comment by safakseyrek** [comment]
Anladığım kadarıyla sergen i değiştirdiniz bende arayüz farklı olunca yanlış birşey yaptım sandım . Burda grid dialog repo tek tek seçildiği için şuanki halinde tek UI gibi hepsi oluşturuluyor. Teşekkürler 💯
