### ISSUE TITLE
UserRetrieveService and PermissionService are not controlled by System.Web.Mvc.Controller

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#2940]
Why not ?
Are they different from other services ?
Is it possible to add a controller ?

Problem is : 
 **using (var connection = SqlConnections.NewByKey("Default"))**  whereas I want to use a dynamic  
connectionstring stored in Session :

 **using (var connection = SqlConnections.NewByKey((string)Session["CustomConnection"]))**

Any other solutions ?

**Comment by volkanceylan** [comment]
They are derived from ServiceEndpoint, which in turn derived from Controller.

Remove the IDbConnection connection parameter from method, open your connection manually.

Anyway, i guess you'll have problems, if you are trying to achieve dynamic connections based on session. That's a scenario not supported. Try to implement something like multi tenancy.

**Comment by GreenUtil** [comment]
I'll give it a try, dynamic connections based on session.
Should it work, I could share my additional code with the Serene project.
In fact, I am making Invitation functionality based on the SignUp functionality, in which one user can invite another user to join the application.
I could share that too, if you like.

**Comment by GreenUtil** [comment]
Hello Volkan, I decided to switch to the multi-instance architecture. Then multi-database, one database per customer, can also be achieved. For the future, I hope Serenity can be made multi-database-proof in a single instance architecture. I'd like to help/assist/contribute with/to that !

**Comment by volkanceylan** [comment]
I'll consider that feature, but don't have any plans for short term, there are workarounds that do pretty well for the moment.
