### ISSUE TITLE
Break Line in Form with annotations

### ISSUE THREAD

**Issue by euclidesgc** [volkanceylan/Serenity#2941]
Is there any annotation to break the line in the form?
I'd like to put two controls with the [HalfWidth] annotation, though, one below the other.
How would I do it these days?

**Comment by Estrusco** [comment]
In forms you can use bootstrap (v3.3) grid system https://getbootstrap.com/docs/3.3/css/#grid 
Using FormCssClass attribute you can specify all bootstrap class you want.

E.g. FormCssClass("col-sm-12 col-md-6") if you want the field take all line in small device and half row in medium device.

**Comment by volkanceylan** [comment]
You may also use [FormCssClass("line-break-lg")] etc in latest version.
