### ISSUE TITLE
PDF in Column

### ISSUE THREAD

**Issue by SebSCo** [volkanceylan/Serenity#2942]
Hello,

I know this can sound like a basic question but I learning and I stuck 

I manage to use MultipleFileUploadEditor and i want to store PDF files in data base and all is working  

The issue I have is with xyzColumn.cs is there any property I can use to show a PDF ico and when user will click on it he will be able to download the files ?

I used FileDownloadFormatter and it will be ok it showing arrow rather then scr String but when I click on it I'm getting an error

A potentially dangerous Request.Path value was detected from the client (:).

I was looking for solutions but nothing working for me including changes to web config to httpRuntime what was the suggestion on Stackoverflow

Any one any suggestions ?

Thank You in Advance

**Comment by Estrusco** [comment]
See http://serenity.is/demo/BasicSamples/InlineActionButtons and source https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons

**Comment by SebSCo** [comment]
Thanks I must miss this sample or just I never pay attention as i was looking all over there

Now I need to see If I can implement it just how I want it

Regards

**Comment by SebSCo** [comment]
OK,

I manage to implement the PDF Icon but it's not a clean solution I need to look for some better solution in future to make it more clean and user friendly but cause I just learning that will do for now


I added below code to xyzGrid.ts

```
        protected getColumns() {
            var columns = super.getColumns();

            columns.splice(6, 0, {
                field: 'PDF Detiles',
                name: '',
                format: ctx => '<a class="inline-action pdf-row" title="PDF">' +
                    '<i class="fa fa-file-pdf-o text-red"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            return columns;

        }

        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();


                if (target.hasClass('pdf-row')) {
                    this.editItem(item.EmployeeSkillId);
                }



            }
```

In the result I have my ico at end 

![pdf1](https://user-images.githubusercontent.com/25355634/32972591-0fff9c40-cbeb-11e7-9d1d-1460a8581b80.jpg)


I  added hidden Property to the Column SSOWImage to make sure the scr= to pdf file is not showed 
if not there was shown a column with a long String with path to the file what was not looking to good

```
    [ColumnsScript("Training.EmployeeSkill")]
    [BasedOnRow(typeof(Entities.EmployeeSkillRow))]
    public class EmployeeSkillColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 EmployeeSkillId { get; set; }
        [EditLink, Width(150)]
        public DateTime DateSkillAcquired { get; set; }
        [EditLink, Width(150)]
        public String EmployeeName { get; set; }
        [Width(100)]
        public String SkillName { get; set; }
        [Width(200)]
        public String SkillLevelName { get; set; }
        [Width(100)]
        public Boolean SSOW { get; set; }
        [Width(100),Hidden]
        public String SSOWImage { get; set; }
    }
}
```

and the down site of this is the icon works just like EditLink

![pdf2](https://user-images.githubusercontent.com/25355634/32972677-61d2d320-cbeb-11e7-9a54-a8a61f744d22.jpg)


But at end of the day it will indicate to the User there are some files there and they can view them from form just I need to see if I can do that form Read only when they press that icon 

If someone have better solution I will be grateful to hear about it or see an example what will help me with my learning progress


Thank You for support so far :)
