### ISSUE TITLE
Lookup issue

### ISSUE THREAD

**Issue by SebSCo** [volkanceylan/Serenity#2943]
Hello,

Don't know why but one of my look ups do not work like intended below Img

![issue1](https://user-images.githubusercontent.com/25355634/32920483-5018c3ee-cb21-11e7-8225-91af99262116.jpg)

it should show SkillLevelName but it is Blank below I adding a code I using

 [DisplayName("SkillLevelid"), NotNull, ForeignKey("[cdc].[SkillLevel]", "SkillLevelId"), LeftJoin("s")]
        [LookupEditor(typeof(SkillLevelRow))]
        public Int32? SkillLevelId
        {
            get { return Fields.SkillLevelId[this]; }
            set { Fields.SkillLevelId[this] = value; }
        }
        [DisplayName("Skill Level Name"), Expression("s.SkillLevelName"), QuickSearch]
        public String SkillLevelName
        {
            get { return Fields.SkillLevelName[this]; }
            set { Fields.SkillLevelName[this] = value; }

        }
....

    public class RowFields : RowFieldsBase
        {
            public Int32Field EmployeeSkillId;
            public DateTimeField DateSkillAcquired;
            public Int32Field EmployeeId;
            public Int32Field SkillId;
            public Int32Field SkillLevelId;

            public StringField EmployeeName;
            public StringField SkillName;
            public StringField SkillLevelName;
            public BooleanField SSOW;
            public readonly StringField SSOWImage;

here is Form Class 

   [FormScript("Training.EmployeeSkill")]
    [BasedOnRow(typeof(Entities.EmployeeSkillRow))]
    public class EmployeeSkillForm
    {
        [DisplayName("Skill Acquired at:")]
        public DateTime DateSkillAcquired { get; set; }
        [DisplayName("Employee Name :")]
        public Int32 EmployeeId { get; set; }
        [DisplayName("Skill :")]
        public Int32 SkillId { get; set; }
        [DisplayName("Skill Level :")]
        public Int32 SkillLevelId { get; set; }
        [DisplayName("SSOW Completed? :")]
        public Boolean SSOW { get; set; }
        public String SSOWImage { get; set; }
    }

Please note the other look ups are working like You see on the screen below that's why I do not get it

![issue2](https://user-images.githubusercontent.com/25355634/32920584-b77526fe-cb21-11e7-88be-fc5eb6e776de.jpg)

Here is the SkillLevel class maybe one of you guys will see something I don't see

    [ConnectionKey("Default"), TableName("[cdc].[SkillLevel]")]
    [DisplayName("Skill Level"), InstanceName("Skill Level"), TwoLevelCached]
    [ReadPermission("Administration:Training")]
    [ModifyPermission("Administration:Training")]
    [LookupScript("Training.SkillLevel")]
    public sealed class SkillLevelRow : Row, IIdRow
    {
        [DisplayName("Skill Level Id"), Identity]
        public Int32? SkillLevelId
        {
            get { return Fields.SkillLevelId[this]; }
            set { Fields.SkillLevelId[this] = value; }
        }

        [DisplayName("Skill Level"), NotNull]
        public Int32? SkillLevel
        {
            get { return Fields.SkillLevel[this]; }
            set { Fields.SkillLevel[this] = value; }
        }
        [DisplayName("Skill Level Name")]
        public String SkillLevelName
        {
            get { return Fields.SkillLevelName[this]; }
            set { Fields.SkillLevelName[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.SkillLevelId; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public SkillLevelRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field SkillLevelId;
            public Int32Field SkillLevel;
            public StringField SkillLevelName;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Training.SkillLevel";
            }
        }
    }
}

Thank You in Advance for any advice

**Comment by kilroyFR** [comment]
Transformt4 ?

**Comment by volkanceylan** [comment]
Implement INameField

**Comment by Zahar661** [comment]
in SkillLevel class

public sealed class SkillLevelRow : Row, IIdRow, **INameRow**
{
................................
StringField INameRow.NameField
        {
            get { return Fields.SkillLevelName; }
        }
}

**Comment by SebSCo** [comment]
Thank You 

That works perfectly and again thanks for support with this


Regards
