### ISSUE TITLE
Promise missing all

### ISSUE THREAD

**Issue by sottnik** [volkanceylan/Serenity#2945]
Hello Volkan

The changed functionality of Promise handling in 3.3.0 and up misses the static all method in Promise class. The RSVP functionality is no longer available (or is it?) . Do you plan to implement the aggregated functionality in Promise class any time soon?
What would be otherwise the proper workaround?

**Comment by volkanceylan** [comment]
It should be there, just not available in d.ts. In tsconfig you may include es.promise or (Promise as any).all etc.

**Comment by sottnik** [comment]
Could you be please more specific? I really get it work. I tried to import es2015.promise module, I tried to remove rsvp from serenitcorelib, nothing works.

**Comment by volkanceylan** [comment]
(Promise as any).all should work, if it is not there is something wrong in your browser, it is a function that is always there for modern browsers. Try adding a declare var Promise: any on top of your file.
