### ISSUE TITLE
Parent grid from template dialog

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2948]
Hey
couldnt find an answer to this, maybe i missed it but:
I have a TemplatedDialog which performs some batch operations. Once the batch action is complete i need to update the parent grid. How do i get a reference to the parent from within the templatedialog.ts?
Thanks!

**Comment by rodneykendall** [comment]
Do you just need the parent grid to refresh from stored data?  If that is the case, you can use:
Serenity.SubDialogHelper.triggerDataChange(self);

In this case, 'self' is a cached copy of 'this' within the parent grid code (let self = this;) that would be cached before the code that opens your dialog.

**Comment by shakazulu89** [comment]
hm interesting .. i will try it right now

**Comment by shakazulu89** [comment]
im not sure what self should be ..  here is the code where i need to call it. this is in the templatedialog on the action.done event handler:
`var action = new Modules.BulkActions.BulkUpdateListingsAction();
                var lettersToPrint = [];
                //let priceListMap: map<number, Product[]> = new Map<number, Product[]>();
                action.done = () => {
                    let self = this;
                    debugger;
                    Serenity.SubDialogHelper.triggerDataChange(self);
                };`

**Comment by rodneykendall** [comment]
The let self line needs to be before the var action line so that it is cached before your 'done' function is created.  The key is the 'this' variable always refers to the current object and within a generated function like that the 'this' is the parent of the object ('action' in this case) instead of the dialog itself.  Caching it as the 'self' variable before your generated function allows you to have the proper reference to the dialog rather than your action object. 

Yes, you should be able to do it during the close action (dialogClose is the overridable method as I recall) but you still need to get a proper reference to the 'this' object.  It MIGHT work just as 'this' in that method, but you'd have to test that.

**Comment by shakazulu89** [comment]
well duh on the "this" being the parent of the object .. i knew that :P
but whats happening now is it simply closes the dialog (which i dont want to happen i want it to stay open). the grid is still not refreshed. im still trying but just wanted to give an update ;)

**Comment by rodneykendall** [comment]
Make sure you are not passing through the original click event and calling it.  That will close the dialog, depending upon your dialog setup.  Pasting the code you have in here may be helpful to pinpoint that should you continue to be stuck.

**Comment by rodneykendall** [comment]
Maybe so.  Your code would probably help a lot in figuring out the missing item or items for making this work.

**Comment by shakazulu89** [comment]
above you saw how i call the bulk service .. then i just put this in the ondialogclose:

`protected onDialogClose() {
            Serenity.SubDialogHelper.triggerDataChange(this);
            super.onDialogClose();
        }`

**Comment by shakazulu89** [comment]
i tried it without the panel decorator still no go .. any ideas amigo?

**Comment by rodneykendall** [comment]
You don't want the dialog to close, correct?  That definitely eliminates the close method (I think the method is 'dialogClose' rather than 'onDialogClose' but I might be wrong).  On the other method, is this basically how you have it setup?

private myFunction(params) {
    let self = this;
    var action = new Modules.BulkActions.BulkUpdateListingsAction(); 
    action.done = () => { Serenity.SubDialogHelper.triggerDataChange(self); };
    action.execute();
}

That's what I was thinking you were doing, but if your 'action' code is some place else there might be a problem with the value of 'self' pointing at the wrong object still.

**Comment by shakazulu89** [comment]
no i dont want it to close after the update but im ok with the grid refresh happening when the user closes the dialog. (since the user anyways cant see the grid because im using panel decorator on the dialog).
i did confirm the ondialogclose function is getting hit (i first tried dialogclose and it didnt work).
anyways here is the code where the action is being called:
`
        protected onDialogOpen() {
            super.onDialogOpen();
            let self = this;
$('#doupdatebatch').click({ ids: this.listingIds }, function (e) {
var action = new Modules.BulkActions.BulkUpdateListingsAction();
                var lettersToPrint = [];
                //let priceListMap: map<number, Product[]> = new Map<number, Product[]>();
                action.done = () => {
                   // alert(self);
                    //debugger;
                    //Serenity.SubDialogHelper.triggerDataChange(self);
                };
action.execute(e.data.ids);

            });
`

**Comment by rodneykendall** [comment]
It looks like you have the triggerDataChange call commented out.  Is that intended?

**Comment by shakazulu89** [comment]
agh i just commented it out when i tried the ondialogclose method .. when i tried it it wasnt commented out ;) .. ill edit the comment

**Comment by rodneykendall** [comment]
Which file is that actually within?  We might be looking at two different typescript files because the xyzDialog.ts is the one I was talking about and the open method is 'dialogOpen' rather than 'onDialogOpen'.

**Comment by shakazulu89** [comment]
Its a TemplateDialog that i am opening from a custom button in the Grid toolbar.
so youre saying it should be: protected dialogOpen() { super.dialogOpen(); ...} ?

**Comment by dfaruque** [comment]
in your grid where you open the dialog. init dialog like this
```
            var dlg = someDialog();
            this.initDialog(dlg);
            dlg.OpenDialog()

```

**Comment by shakazulu89** [comment]
haha the simple things we miss in life!! 
that did it! you DA MAN! rodney youre also awesome! thank you for taking the time i really appreciate it :)

**Comment by Josky-olo** [comment]
> in your grid where you open the dialog. init dialog like this. otherwise triggerDataChange won't work
> 
> ```
>             var dlg = someDialog();
>             this.initDialog(dlg);
>             dlg.OpenDialog()
> ```

That worked for me appreciate.
