### ISSUE TITLE
Q.Authorization.hasPermission - Can't load script data: RemoteData.UserData

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#2950]
I have a trouble in Q.Authorization.hasPermission('myKey') with an user that isn't admin.

I get the message 'Can't load script data: RemoteData.UserData!'

The problem is in user endpoint, why GetUserData() is not called becouse the ServiceAuthorize(typeof(MyRow)) define [ReadPermission(PermissionKeys.Security)] (that is for admin).

Can I change securely this ReadPermession in a general permission?

**Comment by volkanceylan** [comment]
Your method should look like:
```cs
[NonAction, DataScript("UserData", CacheDuration = -1), ServiceAuthorize]
public ScriptUserDefinition GetUserData()
```

**Comment by Estrusco** [comment]
Perfect! Thank you @volkanceylan
