### ISSUE TITLE
Question about Grid

### ISSUE THREAD

**Issue by SebSCo** [volkanceylan/Serenity#2952]
Hello,

First question:
Could someone point me out to a sample or an example what will explain me how to create Grid like below. I was looking for an hour and I must missing something

I have Table called Skills there is column SkillName (Loading,Picking,Receiving..) then there is table Skill Level with column SkillLevel (1,2,3..)  I have Table EmployeeSkill what relating  table Skill, SkillLevel and Employee

I'm looking for a grid what will be as fallow:

Employee Name | Loading | Picking | Reviving
John                   |     2       |     3      |       1

I know this looks like basic question but that will learn me a lot I don't look for a ready solution but just example / Sample how to handle scenarios like that.

Second question
Is there possibility to do more dynamic Columns for example with dates something like 

Employee Name | 20/11/2017 | 21/11/2017 | 22/11/2017
John                            IN                OFF                IN

and when I set for example starting date 26/11/2017 in a filed that will  change the column 2 to that date and rest +1,+2,+3 ?

This question is not that impotent as i think if i understand how to resolve first I will be able to manage to do this logic on a class level

Thank You in Advance for any time spend on this it's really important to me

Regards

**Comment by rodneykendall** [comment]
The simplest thing would be to setup a database view that you use as the source of your grid.  Depending upon your database system, the syntax should be something similar to this:
(First some sample data setup with the assumptions on table definitions)
create table Employee (
EmployeeId [INT] NOT NULL IDENTITY(1, 1) PRIMARY KEY,
EmployeeName [NVARCHAR] (255) NOT NULL
)
insert into Employee (employeename) values ('John'),('Jane'),('Harry')

Create Table SkillName (
SkillNameId [INT] NOT NULL IDENTITY(1, 1) PRIMARY KEY,
SkillName [NVARCHAR] (255) NOT NULL
)
Insert into SkillName (Skillname) VALUES ('Loading'),('Picking'),('Receiving')

Create Table SkillLevel (
SkillLevelId [INT] NOT NULL IDENTITY(1, 1) PRIMARY KEY,
SkillLevel [INT] NOT NULL
)
Insert into SkillLevel (SkillLevel) VALUES (1),(2),(3),(4),(5)

Create table EmployeeSkill (
EmployeeId [INT] NOT NULL CONSTRAINT FK_EmployeeSkill_Employee FOREIGN KEY REFERENCES Employee (EmployeeId),
SkillNameId [INT] NOT NULL CONSTRAINT FK_EmployeeSkill_SkillName FOREIGN KEY REFERENCES SkillName (SkillNameId),
SkillLevelid [INT] NOT NULL CONSTRAINT FK_EmployeeSkill_SkillLevel FOREIGN KEY REFERENCES SkillLevel (SkillLevelId)
)
insert into employeeskill (employeeid, skillnameid, skilllevelid)
select employeeid, employeeid, employeeid
from employee a 
go

--Now the actual view
create view EmployeeSkillStats
AS
SELECT A.EmployeeName, MAX(CASE WHEN C.SkillName = 'Loading' THEN D.SkillLevel ELSE 0 END) as Loading, 
	MAX(CASE WHEN C.SkillName = 'Picking' THEN D.SkillLevel ELSE 0 END) AS Picking, 
	MAX(CASE WHEN C.SkillName = 'Receiving' THEN D.SkillLevel ELSE 0 END) AS Receiving
FROM Employee A
    LEFT OUTER JOIN EmployeeSkill B
        ON A.EmployeeId = B.EmployeeId
    LEFT OUTER JOIN SkillName C
        ON B.SkillNameId = C.SkillNameId
    LEFT OUTER JOIN SkillLevel D
        ON B.SkillLevelId = D.SkillLevelId
GROUP BY A.EmployeeName
GO

select * from EmployeeSkillStats

**Comment by SebSCo** [comment]
I will look into this solution and let you know how I get on with it.

I think it will be really great to see solution like this https://www.codeproject.com/Articles/25167/Simple-Advanced-Pivots-with-C-and-ASP-NET

Build in in the Serenity couse this will help with scenarios like my for reporting purposes or user view

My skill in programming is not on that level yet but I will work hard to get there :)

Thank you for your time spend on this topic Rodney.

Regards
