### ISSUE TITLE
How can I bypass the authentication ?

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#2954]
Hi everyone,

I've a method that I need to call **before** the login, so when I run my application I should write **http://localhost:port/myMethod**. 

How can I do it ? 

Thanks all for your help and your time :)

Chiara

**Comment by kjaraa** [comment]
Any help ?

**Comment by Estrusco** [comment]
See if this can help you https://github.com/volkanceylan/Serenity/issues/2411
Anyway you can see how work AuthenticationService that is called from login form, than before user is logged.

**Comment by kjaraa** [comment]
I saw how work AuthenticationService. I've to impersonate _admin_ user: i searched on the Web and I found a lot of solutions, but no one works :( I'm desperate :(

**Comment by Estrusco** [comment]
Why you want to impersonate admin if you don't want to login?
If you want impersonate admin you can login with method see in issue https://github.com/volkanceylan/Serenity/issues/806

In membership, account, AccountPage.cs there is 

```cs
        [HttpPost, JsonFilter]
        public Result<ServiceResponse> Login(LoginRequest request)
        {
            return this.ExecuteMethod(() =>
            {
                request.CheckNotNull();

                if (string.IsNullOrEmpty(request.Username))
                    throw new ArgumentNullException("username");

                var username = request.Username;
                
                if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
                    return new ServiceResponse();

                throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);
            });
        }
```

How can you see the WebSecurityHelper.Authenticate method authenticate the user. Try to manage with it.

But if you want act as admin, you have to login as admin, IMHO.

**Comment by rodneykendall** [comment]
You could make another landing page in a higher level site that the users first visit then it redirects them to the serenity based site after your method is called.

**Comment by shakazulu89** [comment]
is it at all possible to do this sort of thing from a console application (sitting in the same solution). I need to perform CRUD operations from the console but only way i could manage so far is remove authentication from the rows i need access to. (temporary solution)

**Comment by volkanceylan** [comment]
This wiki entry has some solution, check info about ImpersonatingAuthenticationService

https://github.com/volkanceylan/Serenity/wiki/Background-Task-Bulk-Email-Sending

If you just want to make your method public, remove ReadPermission from your Row, remove ServiceAuthorize etc. from endpoint.cs

**Comment by shakazulu89** [comment]
thanks volkan ill take a look

**Comment by kjaraa** [comment]
It works for me !! Thank you so much @volkanceylan :)

**Comment by ShayneJud** [comment]
> oi

FYI...
(Link Corrected from above:)
     https://github.com/volkanceylan/Serenity/wiki/Background-Tasks:-Bulk-Email-Sending
