### ISSUE TITLE
How to Hide Details Editor ?  

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2958]
Hello Everyone,
Details Query i here..

I have Cost Field in master Dialog,master dialog also contains list for Details.
I want To Show Details Editor if n only if Cost Of master is Loaded I.e Available..

Thank In Advance..
Aniket

**Comment by dfaruque** [comment]
the these utilities https://github.com/dfaruque/Serenity.Extra#to-hide-a-field-in-a-dialog

**Comment by ANDY7575** [comment]
Thanx Buddy..@dfaruque

**Comment by ANDY7575** [comment]
hey @dfaruque
giving error while using Extra package
#2960
