### ISSUE TITLE
Serenity Event Lifecycle

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#2959]
Hi @volkanceylan and everyone,
Can someone document event lifecycle for Serenity. Serenity is a great framework to build web application but it is hard to understand and handle/decor event in typescript (at least for me). Sometime I want to do something but I don't know where do I should start if I don't see demo for that feature.

**Comment by dfaruque** [comment]
Hm, need a chapter in guide.

**Comment by dfaruque** [comment]
something like this https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram

**Comment by Estrusco** [comment]
In wiki there is a page for repository calling sequence in server side 

https://github.com/volkanceylan/Serenity/wiki/Repository-overridable-methods-and-calling-sequence

**Comment by minhhungit** [comment]
@Estrusco yeah, that page is great for server side, still need life-cycle for client side

**Comment by volkanceylan** [comment]
There is not a predefined, step by step lifecycle like ASP.NET WebForms or Vue there but i agree that frontend and some parts in repository side should be documented more.

**Comment by AlperanQ** [comment]
Closing due two inactivity.
