### ISSUE TITLE
Routing Names with 'Admin/' keyword

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#296]
What should i do if i want to add "Admin/" before all Routes
For example 
From -> `/Administration/Language`
To -> `Admin/Administration/Language`

or 
From -> `'Users/User'`
To -> `"Admin/Users/User'`

Thanks

**Comment by volkanceylan** [comment]
Search in all `*.Page.cs` files, find `RoutePrefix("` and replace with `RoutePrefix("Admin/`

**Comment by BolatovAlau** [comment]
It seems that it  doesn't work 
HTTP 404 error (File not found)

**Comment by BolatovAlau** [comment]
Url was `Admin/Users/User`

**Comment by BolatovAlau** [comment]
But if i write -> `[RoutePrefix("Users")]` it works

**Comment by volkanceylan** [comment]
I don't think so 

[RoutePrefix("Admin/Administration/User"), Route("{action=index}")]

http://localhost:55555/Admin/Administration/User

and it works

**Comment by BolatovAlau** [comment]
And now it works with previous Serenity project. It seems that i accidentally deleted something 
Thanks
