### ISSUE TITLE
ERROR...  Class "GridEditorBase" used before Declaration..While Using _Ext..

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2960]
@volcanceylan
I have installed Extra package But While replacing base classes With New One Showing Above Error... 
 Please suggest Way ..
Thanx,
Aniket

**Comment by dfaruque** [comment]
drag the file GridEditorBase.ts file and drop into your file where the errors come from.

**Comment by dfaruque** [comment]
you should not use this repository for _Ext related issue. 
you should report this in  https://github.com/dfaruque/Serenity.Extra

**Comment by dfaruque** [comment]
please close this.
