### ISSUE TITLE
Grid with dynamically generated header

### ISSUE THREAD

**Issue by evje** [volkanceylan/Serenity#2961]
Hi, Volkan Ceylan!
Thank U for this great application platform 'Serenity'.
I'm novice at Serenity, so I've started with base template for ASP.NET MVC. It's working!
For example U can see this screenshot:

![now](https://user-images.githubusercontent.com/16364615/33128285-e4e8d5b6-cf9c-11e7-88c3-0ebe6675d256.png)

Everything is fine, but I think that's good to make some customization. For example, we can try to change grid's header in order to make it something like that:

![needed](https://user-images.githubusercontent.com/16364615/33128355-2f4933d0-cf9d-11e7-9f51-d15efa8286d3.png)

I start read documentation and find, that the only place where the grid's header is defined is that:

![code](https://user-images.githubusercontent.com/16364615/33128436-75c2a6a2-cf9d-11e7-9532-f4c9c4c6c756.png)

Could U explain me, what it needs to be done to customize that header and give some example, if it's possible.
Best regrades

**Comment by Estrusco** [comment]
Using the issue https://github.com/volkanceylan/Serenity/issues/2817 and mix some things, you can override two method in your grid.ts (e.g. CustomerGrid.ts)

```ts
export class YourGrid extends Serenity.EntityGrid<YourRow, any> {
    [...]

    protected totalRecord: number;

    [...]

    // Here you can set the onDataLoaded event to use for set new title 
    protected createView(): Slick.RemoteView<AnagraficaRow> {
        let view = super.createView();
        (view as any).onDataLoaded.subscribe((e, ui) => {
            this.setTitle("Your title with number of record: " + this.totalRecord);
        });
        return view;
    }

    // Here you can get the total number of records
    protected onViewProcessData(response: Serenity.ListResponse<YourRow>): Serenity.ListResponse<YourRow> {
        var lr = super.onViewProcessData(response);
        this.totalRecord = lr.TotalCount;
        return lr;
    }
}
```

**Comment by evje** [comment]
Thank U very much, Estrusco!
You've gave me clear response.
**BUT**, what if we need further movement?
For example, in this example we need not only total quantity of **Customers**, but we need do some filtering, e.g. select those Customers, which are from London...
Of course, we can count the number of Londoner's from lr.Entities array, where lr.Entities[i].City == 'London', but here we can face one more problem...
For example, we have 10 000 customers, but the page size is set to 20 records. in this case we have the length of lr.Entities is equal to 20 too.
Maybe, we need add one more method to our CustomerEndpoint, which will count the quantity of customers from London etc. But how we can call to such new method from CustomerGrid.ts?

**Comment by Estrusco** [comment]
Before setTitle you can call a list service (in sync mod) to get those information from server.
But this can slow the user interface.

See here for sync service https://github.com/volkanceylan/Serenity/issues/2920

**Comment by evje** [comment]
Thanks a lot, **Estrusco**!
U are real angel)
The problem is that I'm novice in Serenity, in typescript, so I need some more explanations and examples.
Let's see:
Here is the part of my **CustomerService.ts** from a standard Serenity template:
`export declare function GetNextNumber(request: GetNextNumberRequest, onSuccess?: (response: GetNextNumberResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;`

Here is the part of my **CustomerEndpoint.cs** from a standard Serenity template:

`public GetNextNumberResponse GetNextNumber(IDbConnection connection, GetNextNumberRequest request)
        {
            return new MyRepository().GetNextNumber(connection, request);
        }`

Here is the part of my **CustomerGrid.ts** I was added in accordance with Yours advice:

`protected createView(): Slick.RemoteView<CustomerRow> {
            let view = super.createView();
            (view as any).onDataLoaded.subscribe((e, ui) => {
                this.setTitle("Your title with number of record: " + this.totalRecord);
            });
            return view;
        }
`

> Before setTitle you can call a list service (in sync mod) to get those information from server

Can U give me an example of code - how can I call to GetNextNumber ?

**Comment by Estrusco** [comment]
There is an example in serene, se how work https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/SerialAutoNumber/

A call to serenity service is made from a first parameter that is the request, a second parameter that is the response, and optional third parameter for the options. In your case you can use this third parameter to set the async: false property.

```ts
    // From Serene example

    // call our service, see CustomerEndpoint.cs and CustomerRepository.cs
    Serene.Northwind.CustomerService.GetNextNumber(
     // Request
     {
         Prefix: prefix,
         Length: 5 // we want service to search for and return serials of 5 in length
     }, 
     // Response
     response => {
         this.form.CustomerID.value = response.Serial;

          // this is to mark numerical part after prefix
         (this.form.CustomerID.element[0] as any).setSelectionRange(prefix.length, response.Serial.length);
     },
     // Options
     { 
          async: false 
      }
); 
```

**Comment by evje** [comment]
**Estrusco**, U are a genius!

Here is the new part of my **CustomerGrid.ts** I was added in accordance with Yours advice:
`protected someNumber: number;
        protected someString: string;`

`

                SereneFirstAppMvc.Northwind.CustomerService.GetNextNumber(
                    // Request
                    {
                        Prefix: "",
                        Length: 5 // we want service to search for and return serials of 5 in length
                    },
                    // Response
                    response => {
                        this.someString = response.Serial;

                        // this is to mark numerical part after prefix
                        this.someNumber = response.Number;
                    },
                    // Options
                    {
                        async: false
                    }
                ); 

                this.setTitle("SomeString = " + this.someString + " SomeNumber = " + this.someNumber);
            });
            return view;
        }`

Here is the part of my CustomerEndpoint.cs:

`GetNextNumberResponse response = new GetNextNumberResponse
            {
                Number = 111,
                Serial = "111"
            };`

![result](https://user-images.githubusercontent.com/16364615/33163362-3db1ff5e-d03f-11e7-93f0-67cbef585b2b.png)

**Comment by evje** [comment]
Maybe, it can be added to documentation, I think)
Thanks a lot.

**Comment by Estrusco** [comment]
You're welcome :D

**Comment by gpraveenraj** [comment]
@Estrusco 

Hi,

As per this example, i put this event in my SampleGrid.ts file.

 protected createView(): Slick.RemoteView<PlanDetailsRow> {
            let view = super.createView();
            (view as any).onDataLoaded.subscribe((e, ui) => {
                //this.setTitle("Your title with number of record: ");
                **Q.notifyWarning("GRID DATA LOADED");**
            });
            return view;
        }

but the warning "**GRID DATA LOADED**" which i have put appears twice .

**Comment by Estrusco** [comment]
Probably onDataLoaded event is fired two times.
You can set a flag to true in the first passage, an set Q.notify under condition.
