### ISSUE TITLE
GridRowSelectionMixin shift select multiple

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#2962]
guys, as the title says, is it possible to shift select multiple rows using the SelectionMixin? without it users might have to do a lot of clicking if they need to select many, but not all rows... 
i feel like i saw somewhere a tutorial for this somewhere at some point but i cant find it ...

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/EnablingRowSelection

**Comment by shakazulu89** [comment]
@Zahar661  haha i knew i saw it somewhere .. i should be able to make this work together with selectionmixin (checkboxes) .. will have time next week to try it .. will reopen if i fail miserably ;) 
thanks!

**Comment by shakazulu89** [comment]
so, i kind of never tried this and now i see this doesnt help with actually selecting the checkboxes of the grid when shift selecting multiple... any more pointers?

**Comment by volkanceylan** [comment]
No, it's not possible
