### ISSUE TITLE
Cache-Control and ETags

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#2963]
Hi Master, do you think this implementation will be helpful?

https://rehansaeed.com/asp-net-core-caching-in-practice/

**Comment by volkanceylan** [comment]
Thanks for the link. We already have a pretty good caching mechanism that also works fine with CDNs, and it is based on some methods in article. Not using ETAG though, not sure need that for now.

**Comment by Magik3a** [comment]
Ok so no need for more complecity. Can i ask you something else
Do you plan to add identity server at some point? I wanted to add new wiki for implementation of signalr but microsoft still strugle with documentation and correct implementation of their nuget package

**Comment by volkanceylan** [comment]
I don't think signalr requires identity server, does it? I don't have a plan, you can use identity server if you like to, by implementing proper interfaces / login screen.

**Comment by Magik3a** [comment]
signalr dosnt need identity server that was different thing that i just want to ask. 
Thanks for your time man.
