### ISSUE TITLE
intranet serenity template issues

### ISSUE THREAD

**Issue by kuradaganesh** [volkanceylan/Serenity#2967]
I created Serenity project solution in my internet computer and it is working properly then after copied to intranet pc and also installing node.js,Type Script and adding all references like serenity.core,serenity.data,csquery,dapper,epplus,fluentmigrater........etc.
the following error is raised
1.command cmd/c npm install exited with code 1
2.i am not founding Tools-->Options-->Projects and Solutions-->External Web Tools in visual studio 2013

Regards,
K.Ganesh

**Comment by SebSCo** [comment]
This error most of the time is related to administration restrictions to Command Line I will check first if you can access command line from windows laver if it's restricted to you contact your administrator

**Comment by kuradaganesh** [comment]
I will check with administrator and get back to you

**Comment by kuradaganesh** [comment]
i login with administrator account but same issue command cmd/c npm install exited with code 1

**Comment by volkanceylan** [comment]
You should check Output window of your Visual Studio first, before reporting here please.

**Comment by kuradaganesh** [comment]
above error get's from visual studio output window only cmd/c npm install exited with code 1
