### ISSUE TITLE
ScriptUserDefinition GetUserData()

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2968]
hey all, 

I need to add some extra stuffs to be set on Authorization.UserDefinition (addition of Granted Sites).
Tried to do modifications on code but cannot DEBUG in GetUserData() (UserEndpoint.cs)

When does this GetUserData() is called (could not find any reference) ?

Thanks !

**Comment by ademc** [comment]
Hi,

That method has a NonAction attribute. This means that method is not Endpoint's regular method. Also method has an attribute named DataScript. This means this methods result usable for client side with given key name. Like this:

`Q.getRemoteData("UserData");`

You can find an example at PermissionCheckEditor.ts

`            let keys = <string[]>Q.getRemoteData('Administration.PermissionKeys').Entities;
`

**Comment by kilroyFR** [comment]
Great many thanks
