### ISSUE TITLE
Can't post JSON into a controller action

### ISSUE THREAD

**Issue by paulmrozowski** [volkanceylan/Serenity#2969]
I'm trying out Serenity and I can't seem to make this work. I am posting some JSON back to a controller action but the parameter coming in never has anything set (that is, it's not getting posted in correctly). To verify my Javascript/jQuery code and controller method, I created an empty MVC project (VS2017), added a and tried it from there. It works fine in the test project. 

I think other versions required the [FromBody] attribute (WebApi 2?) to be applied to the incoming "Invoice" parameter (which I tried after adding the missing Microsoft.AspNet.WebApi.Core package). Same results - it didn't work. This attribute wasn't needed in my test project.

I'm guessing there is some configuration difference but I'm not sure where. This may not even be related to Serenity, but there is a lot going on so it's hard to isolate where it might be failing.

I'm trying from the JS console (start website, log in, navigate to Sales/Entry page):

```javascript
var invoice = { PhoneNum: "5552221212", PaymentType: "Credit" };
$.ajax({url:"Entry/CreateInvoice", type:"POST",data: JSON.stringify(invoice),dataType:"json",contentType:"application/json; charset=utf-8"}).fail(function(e) { alert(e.status); });
```
The controller & parameter looks like this:

```cs
public class Invoice
{
    public string PhoneNum { get; set; }
    public string PaymentType {get; set; }
}

[Authorize, RoutePrefix("Sales/Entry"), Route("{action=ReceivePayment}")]
public class EntryController : Controller 
{
    [HttpPost]       
    public JsonResult CreateInvoice(Invoice invoice)
    {
        // Code here...
    }
}
```

**Comment by minhhungit** [comment]
Hello @paulmrozowski 
Because you defined routePrefix("Sales/Entry") so you must call $ajax like this:

```csharp
$.ajax({ 
    url: "/Sales/Entry/CreateInvoice", // <= look at this
    type: "POST", 
    ....
)
```

**Comment by paulmrozowski** [comment]
Thanks for the reply. No, the URL I have is correct. jQuery sticks the Sales portion of the URL on automatically (if I add it, it tries posting to /Sales/Sales/Entry/CreateInvoice). The post is making it to the server and the action. But the invoice variable isn't populated.

**Comment by volkanceylan** [comment]
This is not a Serenity issue, please use Serenity endpoints / services, or if you decide to use $.ajax and ordinary controllers, look at MVC docs.

**Comment by Mohammad-Yasfo** [comment]
Hi @volkanceylan 
how do I use Serenity endpoints services for post ajax, please send examples..?
I look forward to hearing from you.

Yours sincerely,
