### ISSUE TITLE
Register Permissions in Serene

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#297]
wen testing northwind Permissions i create a user with  view Attribute for the customerbuilt sample but when i try to add new customer popup openes and after adding some data it givevs me exception on 

public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

![untitled](https://cloud.githubusercontent.com/assets/728937/13228896/e7eb2748-d9a6-11e5-843b-ecf90ca56ecc.png)

**Comment by volkanceylan** [comment]
So what is the problem, grant save permission

**Comment by zerodev** [comment]
the problem its braking ?!

**Comment by volkanceylan** [comment]
It's not breaking, its raising exception because you are trying to call an operation you don't have permission to. And its only because you are in debugging mode.

**Comment by zerodev** [comment]
thanks , but one more thing , sometimes when i run the customer page and click on the add new customer , clicking dose nothing, but i took previous image i was able to click with the same user

**Comment by volkanceylan** [comment]
No idea, see chrome console log for errors

**Comment by zerodev** [comment]
and if possible can you explain this 

> These attributes can be used with and located from one of these types:
> On top of XYZRow (Read, Write, Insert, Update, Delete permissions)
> On top of XYZPage and in action methods (PageAuthorize)
> On top of XYZEndpoint and in service actions (ServiceAuthorize)

as far as i understand adding one of the above is enough  get permissions done or it have to be on all of them

**Comment by volkanceylan** [comment]
You're jumping from topic to topic. All has different targets, you use all or use one or none. You use PageAuthorize on pages to limit access to page. You use Row attributes to limit access in repository level to different operations. You use ServiceAuthorize to limit access at endpoint/service level.

**Comment by zerodev** [comment]
thanks , and sorry for jumping :)
