### ISSUE TITLE
Arabic Language in PDF Export 

### ISSUE THREAD

**Issue by Ghufran-Essa** [volkanceylan/Serenity#2971]
I am trying to export pdf file and I have column in Arabic language , the words export as samples like this (":A1'F
9J3I") , 
I tried to change the font in  jspdf.js but nothing changed ! 
please How to fix this?

**Comment by ademc** [comment]
This is about jspdf library arabic support. https://github.com/MrRio/jsPDF/issues/1099

**Comment by volkanceylan** [comment]
This issue should go to jsPDF repo.

**Comment by ra-bedo11** [comment]
Not Working from .net 3.1 toooooooooooooo .net 8
whhhhhhhhhhhhhy ????????
