### ISSUE TITLE
how to enable filters for the grid.

### ISSUE THREAD

**Issue by gpraveenraj** [volkanceylan/Serenity#2972]
Hi,

I have used @Serenity.Decorators.filterable but no filters is visible.

Please help me

**Comment by kilroyFR** [comment]
The 'edit filter' button not visible on bottom right under the grid ?

**Comment by minhhungit** [comment]
@gpraveenraj  did you know how to use [QuickFilter] attribute, this post might help you:
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/filtering_with_multiple_genre_list.html

**Comment by Zahar661** [comment]
```
protected getSlickOptions() {
            var opt = super.getSlickOptions();
            opt.showFooterRow = true;
            return opt;
        }
```

**Comment by gpraveenraj** [comment]
Thanks

**Comment by gpraveenraj** [comment]
No. I don’t know how to use.

**Comment by brunobola** [comment]
Just use the approprieted decoretor to enable filtering
