### ISSUE TITLE
Multiselect dropdown

### ISSUE THREAD

**Issue by gpraveenraj** [volkanceylan/Serenity#2975]
Hi,

I have two dropdown list. 1) Region 2) Office.

I need to know how i can write code to bind Office based on Region selection.
For ex, if i select UK in Region, Office list should show LONDON & BIRMINGHAM

Please share some examples.

**Comment by Estrusco** [comment]
Search cascadeFrom in previous issue. Also search in basic sample.

https://github.com/volkanceylan/Serenity/issues/2661
https://github.com/volkanceylan/Serenity/issues/2763
https://github.com/volkanceylan/Serenity/issues/2744
