### ISSUE TITLE
Is it possible To Refresh GridEditor[memory Grid]..

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#2977]
hi Guys.
Im opening Dialog by using Inline Action button of Grid editor 
While filling dialog Which contains some field from Grid Editor Table
and some belongs to another table ..
Im able to update database Table,but i also want to referesh grideditor ..
here Sample Of what i have tried...

` protected onSaveSuccess(response: Serenity.SaveResponse): void {
            Q.reloadLookup(EnquiryPoRow.lookupKey);
          
            Q.reloadLookup(Enquiry.PurchaseMilestoneRow.lookupKey);
            
            EnquiryPoService.Retrieve({     // 
                EntityId: this.EnquiryID
            }, response => {
What should I add here...
                Q.alert("Refreshed")     //try refreshing grid
                
                });

        }`
Any help is Appriciated..
Aniket

**Comment by volkanceylan** [comment]
In memory grids can't be refreshed. You may try dialog.loadById(dialog.entityId) etc. though.

**Comment by ANDY7575** [comment]
thanx @volkanceylan ..

**Comment by ANDY7575** [comment]
@volkanceylan  
i have tried your suggestion, but still im unable find refreshed  data inside grid..

any help appreciated..
Aniket

**Comment by brunobola** [comment]
@ANDY7575 please see issue https://github.com/volkanceylan/Serenity/issues/3792 It can refresh the content and more ;)
