### ISSUE TITLE
Enhancement for Authentication using LDAP

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#298]
a good thing to do is to disable password and username for LDAP

**Comment by volkanceylan** [comment]
There is active property for that. LDAP management is not Serenity business.

**Comment by zerodev** [comment]
oh sorry i thnk i was not clear , i ment that in serenity , once a user logedin useing Active directory , he can still go to his profile and change usr name and  add a apassword

**Comment by volkanceylan** [comment]
Change password ok but i don't remember letting users change their usernames

**Comment by zerodev** [comment]
check the adminstration page its the admin who can change the username :)

**Comment by volkanceylan** [comment]
Admin can change this is not a problem, what if ldap username changes

**Comment by zerodev** [comment]
heheheh yep  good point , and answer is for me is its AD admin problem :)
