### ISSUE TITLE
Error on Mac: Package 'EPPlus 4.1.0' This package may not be fully compatible with your project.

### ISSUE THREAD

**Issue by renattomachado** [volkanceylan/Serenity#2980]
@volkanceylan How solve this error when build the serene application on mac?

The full error:

Package 'EPPlus 4.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by volkanceylan** [comment]
Serene.Core comes with EPPlus .NET core version, you probably installed a .NET framework version.

**Comment by mahmuthaktan** [comment]
this worked for me

dotnet nuget locals all --clear
