### ISSUE TITLE
 LookUps question when using Free Version of Serenity Template (3.3.12.)

### ISSUE THREAD

**Issue by jaszb** [volkanceylan/Serenity#2981]
Hi,

Are Look-ups supposed to work after doing a sergen command? I have a simple scenario with an `Address.AdressTypeId ->AddressType.Id`

There does not seem to be any automatic generation of the relevant types i.e. `RowLookupScript<T>`

If I have to add them myself I'm happy to but is there any documentation around doing that manual step?

Thanks in advance ,

John

**Comment by jaszb** [comment]
I can see from the NW sample there are a few nice options of doing this.  Does the paid version of the template give more auto generated code for these look-up? or is it all still a bit manual (albeit trivial)?

**Comment by volkanceylan** [comment]
No, lookups are generated manually, when you need them, and it is one liner.
