### ISSUE TITLE
Action Button problemi

### ISSUE THREAD

**Issue by onerkaloglu** [volkanceylan/Serenity#2983]
Serenity ile geliştirme yapmaya yeni başladım. İssueları da inceledim ama benzer birşey bulamadım.

Firma Gridi üzerinden action buton ile Firma Mail detaylarının yer aldığı tablonun dialogunu açmaya çalışıyorum ama başaramadım. Sadece FirmID bilgisi doluyor. Diğer bilgileri yükleyemedim.
Örnekte sipariş gridi üzerinden sipariş detay dialogu açılıyor. 

else if (target.hasClass('mail')) {
                    var dlg = new Nakityonetimi.MailDialog();
                    InitEntityDialog(dlg);
					dlg.LoadByIdAndOpenDialog(item.FirmId);
                    
                }

![image](https://user-images.githubusercontent.com/18145375/33371006-62411bd2-d50a-11e7-842b-277cc1efd2c5.png)

**Comment by Zahar661** [comment]
```
else if (target.hasClass('mail')) {
                    var dlg = new Nakityonetimi.MailDialog();
                    this.initDialog(dlg);
                    dlg.loadEntityAndOpenDialog(<Nakityonetimi.MailRow>{
                        FirmId: item.FirmId
                    });
                }
```

**Comment by onerkaloglu** [comment]
thanks for answer. But it is not success for me. Only FirmID field loaded. I need to help for loading of other fields.

![image](https://user-images.githubusercontent.com/18145375/33470198-0ebcce7e-d678-11e7-83c4-35e0de2bc8d3.png)

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/33470427-417fe46c-d679-11e7-9a31-e765d801dff8.png)

**Comment by Zahar661** [comment]
If the event creates a new letter, and does not open the old one, then you need to describe all the fields
```
else if (target.hasClass('mail')) {
                    var dlg = new Nakityonetimi.MailDialog();
                    this.initDialog(dlg);
                    dlg.loadEntityAndOpenDialog(<Nakityonetimi.MailRow>{
                        FirmId: item.FirmId,
                        Field2: item.Field2,
                        Field3: item.Field3,
                        Field4: item.Field4,
                        Field5: item.Field5
                    });
                }
```

**Comment by onerkaloglu** [comment]
There is only one fkey on table. I have only FirmId for Mail table. 

![image](https://user-images.githubusercontent.com/18145375/33483021-c1f4e2ea-d6ac-11e7-8ee7-6a10897e1e8b.png)

**Comment by Zahar661** [comment]
hm. not quite the right approach.
but it is possible and so.
in MailRow  field FitmID add [LookupInckude] and top [lookupscript(.....)] if it does not exist

```
else if (target.hasClass('mail')) {
                    var dlg = new Nakityonetimi.MailDialog();
                    this.initDialog(dlg);
                    var msgId = Nakityonetimi.MailRow.getLookup().items
                        .filter(x => x.FirmId == item.FirmId)[0];
                    dlg.loadEntityAndOpenDialog(<Nakityonetimi.MailRow>{
                        MailId: msgId
                    });
                }
```

**Comment by volkanceylan** [comment]
If you are trying to load a mail item, then you should load it by its MailId, not FirmId.
