### ISSUE TITLE
Core Project can't find updated packages

### ISSUE THREAD

**Issue by jaszb** [volkanceylan/Serenity#2987]
I started a brand new core project.  I updated the nuget packages from within VS2017.

now when i run dotnet sergen t is see the following errors
![capture](https://user-images.githubusercontent.com/32381192/33407037-7e8259fa-d5aa-11e7-91cb-79b8ca9fed3e.PNG)

Any ideas?  Did i make a mistake using vs2017 to update the nuget packages?

**Comment by brunobola** [comment]
that's strange, please do a nuget reinstall and check again...

**Comment by volkanceylan** [comment]
You shouldn't update ASP.NET Core to a version other than the one Serenity uses. .NET Core assembly loading is pretty problematic at the moment.
