### ISSUE TITLE
LinkingSetRelation, Can't show multiple value in grid column

### ISSUE THREAD

**Issue by mafdy** [volkanceylan/Serenity#2989]
Hello dears,

I'm posting this issues because i tried every possible ideas to solve the problem but i didn't succeed.

- [NotMapped, or ClientSide]
- [MinSelectLevel(SelectLevel.List)]
- replace  htmlEncode with attrEncode as @volkanceylan said when version 3.3.12 released
- tried to play with OnReturn in Repository
i don't know where is the problem
current serenity version: 3.3.13

the problem is in Linking Set Relation, there's no way to show the multiple  value in the grid, when it works will in the old tutorial "Move Tutorial"

here's screen shot of my code:
column code:
![column code](https://user-images.githubusercontent.com/30433229/33429472-a393dedc-d5d5-11e7-9a56-a6c2578515b6.PNG)
--------
row code:
![row code](https://user-images.githubusercontent.com/30433229/33429517-ca9ac7b6-d5d5-11e7-89be-202533117a4b.PNG)
-------
formatter:
![formatter code](https://user-images.githubusercontent.com/30433229/33429567-04c732b2-d5d6-11e7-96e7-46e6d31173a6.PNG)
--------
wrong result:
group are having two value (Group A, Group B). It show null if there is more than one value, but if one value it shown correctly, 
![row column](https://user-images.githubusercontent.com/30433229/33429592-27b4e17a-d5d6-11e7-8104-a8c9528ef197.PNG)
--------
result that I'm trying to archive, like the Move Tutorial :
![right](https://user-images.githubusercontent.com/30433229/33429650-6613b63a-d5d6-11e7-88f8-4d07f32e1598.PNG)

a little instruct will helps a lot, thanks in advance

**Comment by rodneykendall** [comment]
For one thing, the 'QuickFilter' attribute won't work with a multiple linking set.  You have to add the quick filter through code (see below).

Make sure your parameters on the LinkingSetRelation match the child table (the parent record ID is AttendanceDeductionRuleID and the child record ID is GroupID, correct?

In the formatter, I found that I had to remove the ' || !idList.length' criteria of the first 'if' statement.  That always returned true so it always returned an empty string!

For the 'quickfilter', override the 'getQuickFilters' method within your grid.ts file of your master row to something like the following and you also need a list request class.

First the list request class is a CS class that should (for simplicity) be in the same folder as your master row class.  Call it 'MasterListRequest' or something like that for easy recognition.

`using Serenity.Services;
using System.Collections.Generic;

namespace MyProject.Master
{
    public class MasterListRequest : ListRequest
    {
        public int? CHILD_ID { get; set; }
        public int? MASTER_ID { get; set; }
    }
}`

Then you need to replace 'ListRequest' in your repository and end point classes for the master with your new 'MasterListRequest' class.  That will allow the passing of the child id and master id around between client and server calls.

Next the getQuickFilters override:
`
protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
            let filters = super.getQuickFilters();

            filters.push({
                type: Serenity.LookupEditor,
                options: {
                    lookupKey: Lookups.ChildRow.lookupKey
                },
                field: 'CHILD_ID',
                title: 'Child Title',
                handler: w => {
                    (this.view.params as MasterListRequest).CHILD_ID = Q.toId(w.value);
                }
            });
       return filters;
}
`

The child id (whatever you actually call it) gets set in the grid class for filters and is then applied client side.

Finally you need to override the ApplyFilters method of the ListRequestHandler on your master repository class:

`        private class MyListHandler : ListRequestHandler<MyRow, MasterListRequest>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                if (Request.CHILD_ID != null)
                {
                    var child = Entities.ChildRow.Fields.As("child");

                    query.Where(Criteria.Exists(
                        query.SubQuery()
                            .Select("1")
                            .From(child)
                            .Where(
                                child.MasterId == fld.MasterId &
                                child.ChildId == Request.CHILD_ID.Value)
                            .ToString()));
                }
            }
        }
`

I hope that helps.

**Comment by mafdy** [comment]
**Hey rodneykendall,** 

I'm so sorry, i was on a vacation, and I just saw your post right now.

I already tried ListRequest, but you let me understand the whole picture. So, i'll work on it and let you know the result.

thank you so much for your help. I appreciate that a lots.

 best regards,
