### ISSUE TITLE
sorgudan istenmeyen alanların çıkarılması

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#299]
group by için bazı alanları kaldırmam gerekli . lakin row'dan bütün alanlar sorguda geliyor. yardımcı olabilir misin?
(Left joinden gelen id'ler ve  kriter için alanlar...)

**Comment by volkanceylan** [comment]
SelectTableFields yapmayın tek tek seçin

**Comment by oaltay** [comment]
ListRequestHandler içinde bunu nasıl yapabilirim. 
CreateQuery() 'de olmadı çünkü.

**Comment by volkanceylan** [comment]
SelectFields ı override edip sadece istediklerinizi seçin base i çağırmayın

**Comment by oaltay** [comment]
tşk.ler
