### ISSUE TITLE
Multi-Level of a MasterDetail

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#2990]
I want to implement a Multilevel Master Detail but i can't figure out how to do it. 
I have a Entity Call Show, and Show have a NotMapped List<ShowsSongs> of Songs, and Songs have a NotMapped List<ShowsSongsInstruments> of Instruments
When I Select the (foreignKey: "ShowId") y cannot put in the second list (foreignKey: "ShowId, SongId") and serenity always tell me "Cannot Insert Null values on SongId" or "Cannot Insert Null values on ShowId"

Can anyone point me in the right direction ? I know serenity supports multi level of master detail

**Comment by wirble** [comment]
Have you made sure on the row file of song that it is returning the id and when you mapped them, you have put in the correct id.  Maybe you have it reversed?  For linksetrelation both ids have to be numeric.   Maybe post some codes.

**Comment by javaman63** [comment]
Thanx @wirble for you response. i've never used a List<MyOwnRow> with a SetRelation. Do you have an example?

**Comment by rodneykendall** [comment]
Here's an example:

On the master Row:
`        [DisplayName("Child"), MasterDetailRelation(foreignKey: "MasterId", IncludeColumns = "CHILD_NAME"), LookupInclude, MinSelectLevel(SelectLevel.Always)]
        public List<ChildRow> ChildList
        {
            get { return Fields.ChildList[this]; }
            set { Fields.ChildList[this] = value; }
        }
        public partial class RowFields { public RowListField<ChildRow> ChildList; }
`

On the master Form:
`[ChildEditor]
        public List<Entities.ChildRow> ChildList { get; set; }`

Be sure to include the 'LookupScript' attribute on the child row class:
`[LookupScript("ChildNamespace.Children")]`

The text for the parameter to the LookupScript is the 'LocalTextPrefix' that is set at the bottom of the generated ChildRow class.

One thing that I still haven't been able to get to work, though, is when this is used and a new row is added to the child relation, the grid on the master row just gets a new empty row until the master row is saved.  The 'IncludeColumns' parameter is supposed to help that from what I've seen but only the ID ever gets applied before saving the master row in my experience.

**Comment by javaman63** [comment]
Hi @rodneykendall Thank you for your answer. Looking at your code, that example is to implemente ONE level of MasterDetail. What I need to do, is implement a MasterDetail from a MasterDetail and save the ALL entity in one click.

**Comment by volkanceylan** [comment]
Serenity supports multi level master detail, implement it on both like you would do one level, make sure to include MinSelectLevel(SelectLevel.List) etc on detail properties.
