### ISSUE TITLE
What is actually called when searching in a lookup dropdown?

### ISSUE THREAD

**Issue by rodneykendall** [volkanceylan/Serenity#2991]
I'm trying to override the search functionality in a lookup drop down but I can't find any method on the lookup classes that gets called when typing partial searches.  What actually gets called?  I want to implement a templated search where users can enter a numeric value and records that match within a variance of 25% are retrieved instead of the straight 'contains' search that the default functionality provides.  I put override methods in the 'List' and 'Retrieve' handlers in the Repository but no breakpoints are ever reached?  I also don't see the data being retrieved from the database (using SQL Profiler) so I am REALLY at a loss as to where the data is derived.

Anyone know where I need to look?

**Comment by javaman63** [comment]
I think you have to create your own LookUp Clase and override PrepareQuery, take a look of this example

`


    public sealed class CmbPesoLookup : RowLookupScript<CmbPesoRow>
    {
        public CmbPesoLookup()
        {

            IdField = CmbPesoRow.Fields.IdPeso.PropertyName;

            Permission = "*";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            query.Select(CmbPesoRow.Fields.IdPeso).OrderBy(CmbPesoRow.Fields.IdPeso);
        }
    }

}



`
Hope This Help

**Comment by rodneykendall** [comment]
Thanks, I'll try implementing a lookup override script.  I assume I'd just decorate the lookup on the row that is using it with the name of the new lookup script, right?  In our example it would be [CmbPesoLookup]?

**Comment by javaman63** [comment]
Yes! this is part of my code!
`

    [ModifyPermission("HealthyCare:Parametricas")]
    [LookupScript("Parametricas.CmbPesoLookup")]
    public sealed class CmbPesoRow : Row, IIdRow, INameRow


`

**Comment by rodneykendall** [comment]
Thank you very much!  Now that I saw your script I did find the examples related to this in the documentation.  Apologies for wasting your time.

**Comment by ali-h2010** [comment]
@rodneykendall ,@Javaman63, does this work with big number of records in the filter? I have 2 million records that i want users to filter with .

**Comment by ali-h2010** [comment]
I tried the code and the drop down is showing "Searching" but then it returns an empty doropdown
