### ISSUE TITLE
Loginpanel Logo

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2993]
Hi,
I am trying to change the loginpanel Logo. Where can i find the code. Tried by changing the base64 image data with a png image but getting a blank image.

thank you,
Srinivas

**Comment by Zahar661** [comment]
~/Modules/Membership/Account/AccountLogin.cshtml

**Comment by Zahar661** [comment]
~\Content\site\site.membership.less

**Comment by edwardch** [comment]
And if you want to convert your image to base64 you can use something like [Base64 Image Encoder](https://www.base64-image.de/)

**Comment by srinivas1910** [comment]
Thank you Guys got it
