### ISSUE TITLE
Summing

### ISSUE THREAD

**Issue by GayathriSravya** [volkanceylan/Serenity#2995]
Hi
 I'm in a project which requires summing of  Specific columns and result on a new column.
I am entirely new to serenity so please guide me..

Regards
   Sravya.

**Comment by edwardch** [comment]
You can use an [ExpressionAttribute](https://github.com/volkanceylan/Serenity/wiki/ExpressionAttribute-[Mapping]) field...

**Comment by javaman63** [comment]
Take a look to this sample

[http://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid](url)
