### ISSUE TITLE
Authorization.HasPermission return always false

### ISSUE THREAD

**Issue by mail955** [volkanceylan/Serenity#2997]
hi
Authorization.HasPermission return always false.
I want to check if a particular user is a member of a role.
For example: I created a role named **Test**.
I'm trying to get if this code:
```
  if (Authorization.HasPermission ("Test"))
{
run if true .....
}
```
But he returns me false all the time.
Where am I wrong?
Thanks!

**Comment by volkanceylan** [comment]
Roles and permissions are different things. HasPermission checks permissions, not roles.

**Comment by mail955** [comment]
Thanks.
How can I tell if a certain role belongs to a particular user? (Or current user?)
