### ISSUE TITLE
Prevent Repository to bring a List with none defined properties

### ISSUE THREAD

**Issue by in32bit** [volkanceylan/Serenity#2998]
In case we have a table with 10 Columns and we want to view only 5 in the the grid, the Repository always bring all 10 (that where define in the Row).

How to let the grid request only the table fields that where define in the C# Columns file.

thank you

**Comment by volkanceylan** [comment]
Search for ColumnSelection.KeyOnly in source code, you'll be able to find how it used.

**Comment by in32bit** [comment]
Thank you.

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            request.ColumnSelection = ColumnSelection.KeyOnly;
            return new MyListHandler().Process(connection, request);
        }
