### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2999]
Hi,
Based on MovieDB i wrote the following validation to display two entities from two different tables in an order form but only one entity is getting displayed after saving the order. where am going wrong pls guide me.

protected validateEntity(row: EmpListRow, id: number) {
            if (!super.validateEntity(row, id))
                return false;
            
            row.Event = Design.EventRow.getLookup()
                .itemById[row.EventId].Event

            row.DesignerFullName = Employee.EmployeeRow.getLookup()
                .itemById[row.Designer].FullName

                       
            return true;

           
        }

only Event is getting displayed 

![image](https://user-images.githubusercontent.com/29406374/33527225-d3748fbc-d872-11e7-9ca0-08b844f9ed7a.png)

Regards,
Srinivas

**Comment by volkanceylan** [comment]
Check the guide, where there is some notes about why some fields are not shown after loading. What happened to Neo? etc.

**Comment by ra-bedo11** [comment]
Whats Solution ?
