### ISSUE TITLE
Clientside Validation for LookupEditor

### ISSUE THREAD

**Issue by stickybro** [volkanceylan/Serenity#30]
Thanks for this awesomeness and for adding the order/detail example. I have been working with Serenity for about a week and already amazed at what features are provided.

I have a question on clientside validation of the LookupEditor as used in your "New Order" form (*Customer). When a LookupEditor is a required field and not given a value before submission, clientside validation does not occur and instead server side validation throws an error in Turkish. Do you have any suggestions regarding where to best solve this issue? Thanks again sb

**Comment by volkanceylan** [comment]
Oops, it is probably a bug related to a recent jquery.validate upgrade. It wasn't like this before. I'll fix it and Turkish leftover error.

**Comment by volkanceylan** [comment]
Ok, located the problem. It is not jquery.validate upgrade actually, but Select2.js 3.5.2.

Select2 3.5.2 is incompatible with jquery.validate. I'll downgrade it to 3.5.1 in next version of Serene.

Before it is released, a quick fix for your problem can be to open package manager console and type:

> Update-Package Select2.js -Version 3.5.1

Also, i localized Turkish texts that i forgot in DataValidation.cs.

**Comment by stickybro** [comment]
You are a legend :) thanks so much for the quick fix and support!!!
