### ISSUE TITLE
Using linq in queries.

### ISSUE THREAD

**Issue by mail955** [volkanceylan/Serenity#3001]
Using linq in queries.
I have a code that I have to execute. Not as declarative programming, but as a logical section of examination and decision.
Is there a way to perform linq queries on the Entities?
Or is it possible to write with SQL query?
The query returns an array. You can not manipulate it on linq /

Thanks for Serenity. It's great !!

**Comment by volkanceylan** [comment]
We use Dapper, please see its samples.
