### ISSUE TITLE
Allow anonymous access to API

### ISSUE THREAD

**Issue by davidzhang9990** [volkanceylan/Serenity#3002]
Hi EveryOne:

How Can I Allow anonymous access to API?

**Comment by mail955** [comment]
Before every action has what it can perform.
For example:

       ```
  [HttpPost, AuthorizeCreate (typeof (MyRow))]
         public SaveResponse Create (IUnitOfWork uow, SaveRequest <MyRow> request)
         {
             return new MyRepository (). Create (uow, request);
         }
```

Delete AuthorizeCreate or Authorize

**Comment by davidzhang9990** [comment]
Thanks @mail955  
I try this,but fail .

**Comment by domints** [comment]
Please check if your Controller (_endpoint_) has by any chance `ServiceAuthorizeAttribute`. If so, remove it from Controller and apply to all methods that you DO NOT want to be accessed by anonymous users.
