### ISSUE TITLE
Reporting tool

### ISSUE THREAD

**Issue by SebSCo** [volkanceylan/Serenity#3003]
Hello,

I’m looking for advice, what is the best and easiest reporting tool to implement with serenity?

Do someone try Nreco or crystal report with Serenity? 
And how they getting on?

Or do you have any better suggestions?

Regards

**Comment by edwardch** [comment]
Depends on what you're trying to achieve (bulk/adhoc/custom) I guess. I use [Telerik Reporting](https://www.telerik.com/products/reporting.aspx) and have been very happy so far. I try to keep away from SAP products, and never tried NReco out.

**Comment by SebSCo** [comment]
Telerik and Devexpress looking to expensive for me currently I'm learning and enjoying serenity I learn a lot about MVC and c# by creating my own project and using Serenity and struggle with it to start :P 

The difficult part and most complicated for me is Pivot reporting what I need to include in my project but without a good example it's hard to learn for me that's why I was thinking to use some BI tools and implement them.

Telerik looking ok but my worries is if I use trial and I like it I will depend on it and it's a year subscription :/ I do that application, for now, to learn and help my self at my current job what don't have anything to do with app development :)

**Comment by edwardch** [comment]
Ya it's quite expensive, but works really well and reports look really good. It's also _not_ a year subscription - it is _perpetual_ so it's only a once-off cost. If you can get the company to pay then that's even better :)

You can also look at using PowerBI and embed the reports/dashboards - that can work really well too.

If you'd like to get your hands a bit more dirty you can write custom report queries (SQL PIVOT) and then display that on a graph on the page - see the chart examples in the Serenity Demo.

**Comment by SebSCo** [comment]
This is what I'm learning now SQL SP for pivot then I already save some links to topics about using SP in Serenity.

**Comment by MaradiagaSistemas** [comment]
I have been ussing Telerik Reporting and it's quite easy to integrate this tool to serenity.

![report](https://user-images.githubusercontent.com/1533653/33558533-bb33ba9c-d8cf-11e7-8e7c-f27391db7d36.jpg)

Best Regards!

**Comment by SebSCo** [comment]
I think I try it they have a lot of tutorials and support materials what helping with learning  price of only Reporting tool is not that scary just need to check the trial version If I will be able to implement it to serenity myself or how much learning that will involve and if this gives me exactly what I'm looking for :)

Is there anything I need to know or can be difficult when implementing Telerik to serenity or following the documentation will be enough?

**Comment by MaradiagaSistemas** [comment]
Just following documentation will be enough since they allow to create a "Telerik MVC Report View"

**Comment by SebSCo** [comment]
The only down side of it is 30 day trial and actual reporting do not have pivot table and Grid view you need to buy Telerik UI for them and they are helpful :) I think that's why Nreco looking good but I think it's harder to implement for me :/ I need more experience to use this but I will try both and see what will work better for my self :) 

Thank You for input

**Comment by galof** [comment]
What about SQL Server Reporting Services?

**Comment by ReatKay** [comment]
If you are within the European Union:
EU courts have decided, that companys like Microsoft cannot forbid the sale of OEM keys which have been legitly given out. What does that mean? Certain server keys (for example: MS Server 2016, SQL etc. with Reporting Services) are now widely available. Some people that got keys as bundle with their servers but don't need em, sell them now - for a ridicilous low price. I bought myself Microsoft Licenseses that are usually thousands, for hundreds instead. I first tested as I didn't know about that court decision - as I didn't believe that it's legit or whatever. But I officially registred all keys with microsoft and even got goodies like Azure credits, and other stuff. 

What does this mean:
Reporting Services and stuff that usually meant costs that are over the top for small proejcts, are not anymore :)  

Just a little tip! :)

**Comment by BrMail** [comment]
You can use Reporting Services for FREE 

SQL Server Express With Advanced Services (FREE)
will include de reporting services express  
The only limitation is the databases you connect needs to be in the same SQL Instance  

Please keep this post updated if you find other solutions ! 

Regards

**Comment by BrMail** [comment]
I just discover that AWS QuickSight released the embebeded feature the costs are low. 
When i have more time available i will test it on Serenity !!

**Comment by edwardch** [comment]
@MaradiagaSistemas are you still embedding Telerik reports into Serenity? 

If you have any pointers or suggestions on how to implement that it would be much appreciated!

Thanks,
Edward

**Comment by edwardch** [comment]
For anyone searching for this there is a wiki entry on [integrating Telerik Reporting with Serenity](https://github.com/volkanceylan/Serenity/wiki/Reporting:-Integrating-Telerik-Reporting)
