### ISSUE TITLE
EmailEditor 

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#3004]
EmailEditor alan  bir field  autocomplete olabilir mi?
Yardımcı olursanız.
Kolay gelsin.

**Comment by mail955** [comment]
Before every action has what it can perform.
For example:
```
         [HttpPost, AuthorizeCreate (typeof (MyRow))]
         public SaveResponse Create (IUnitOfWork uow, SaveRequest <MyRow> request)
         {
             return new MyRepository (). Create (uow, request);
         }

```
Delete AuthorizeCreate or Authorize

**Comment by volkanceylan** [comment]
Malesef, kendiniz yazmayı deneyebilirsiniz.
