### ISSUE TITLE
Custom Delete Message for Grid Editor Dialog in Entity Dialog

### ISSUE THREAD

**Issue by buddhatripp** [volkanceylan/Serenity#3006]
![image](https://user-images.githubusercontent.com/16328936/33564199-ee0db644-d8e7-11e7-9042-d90283d6ba91.png)

How can I change the text for this message?

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/33566984-c2f76662-d932-11e7-8406-3c4b7aa272a9.png)

**Comment by buddhatripp** [comment]
I believe this will only change the confirmation for languages other than English, at least I don't see English as a choice in the texts. Also, that will change the text for all entity dialogs. I want the message to be dialog-specific. For example, when I'm deleting an address then the confirmation should say, "Are you sure you wish to delete this address?"

Thank you!

**Comment by Estrusco** [comment]
I think you have two ways.
First, unbind click event from delete button and then bind your custom event:

```ts
constructor() {
    super();

    this.deleteButton.unbind('click');
    this.deleteButton.on('click', (e) => {
        Q.confirm('your text', () => {
            this.doDelete(() => {
                this.dialogClose();
            });
        });
    });
}
```

Or you can override getToolbarButtons(), remove the delete button and recreate it

```ts
protected getToolbarButtons(): Serenity.ToolButton[] {
    var buttons = super.getToolbarButtons();

    buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
    buttons.push({
        title: Q.text('Controls.EntityDialog.DeleteButton'),
        cssClass: 'delete-button',
        hotkey: 'alt+x',
        onClick: () => {
            Q.confirm('your text', () => {
                this.doDelete(() => {
                    this.dialogClose();
                });
            });
        }
    });

    return buttons;
}
```

**Comment by volkanceylan** [comment]
Or maybe:

```ts
protected getToolbarButtons(): Serenity.ToolButton[] {
    var buttons = super.getToolbarButtons();
    Q.first(buttons, x => x.cssClass == "delete-button").onClick = () => 
        Q.confirm('your text', () => {
                this.doDelete(() => {
                    this.dialogClose();
                });
            });
        }
    });

    return buttons;
}
```
