### ISSUE TITLE
grid showed sum value

### ISSUE THREAD

**Issue by dxh141130** [volkanceylan/Serenity#3007]
I have primary table order and sub table order detail, one order has mutilple order detail. i want to show the order amount is sum of several order detail amount in order grid. i tried to use expression, but i can not use group by. and i tried to use formatter, editor. I donot know what kind of reason, it does not show error, but the order grid did not show sum order detail amount. Please give me an example about that ,thanks

**Comment by Zahar661** [comment]
Expression("Select SUM(Summa) from [OrderDetail] AS T1 WHERE T0.OrderId = T1.OrderId")]

**Comment by Zahar661** [comment]
in Nortwind Order
```
[DisplayName("Summ"), Expression("(Select SUM(t1.[UnitPrice] * t1.[Quantity] - t1.[Discount]) from [Order Details] AS t1 WHERE T0.OrderId = t1.OrderId)")]
        public Decimal? Summ
        {
            get { return Fields.Summ[this]; }
            set { Fields.Summ[this] = value; }
        }
```
![image](https://user-images.githubusercontent.com/26430136/33576937-7dc82d90-d952-11e7-885e-fea73c5efb5f.png)

**Comment by Zahar661** [comment]
and count 
```
[DisplayName("Count"), Expression("(Select Count(t1.[DetailID]) from [Order Details] AS t1 WHERE T0.OrderId = t1.OrderId)")]
        public Decimal? Count
        {
            get { return Fields.Count[this]; }
            set { Fields.Count[this] = value; }
        }
```
![image](https://user-images.githubusercontent.com/26430136/33577115-128435f0-d953-11e7-8329-31cb1a00a6d8.png)

**Comment by dxh141130** [comment]
Thank you so much. i used to think what i can do is work on one row, now it looks i could write sql query to a field. MANY THANKS
