### ISSUE TITLE
Error in console after Transform All T4 Templates

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#3008]
Hi Guys

I am getting following error in browser console after Transform All T4 Templates. If I undo my changes then it works fine and all work even after  Transform All T4 Templates.
Now I am adding a new field in MemberRow.cs and It also works if I am not doing Transform All T4 Templates. 
But it started showing below error after Transform All T4 Templates. Seems something goes wrong with ProjectName.Web.d.ts file.

Can anyone please help on this?

![image](https://user-images.githubusercontent.com/2145218/33594060-5d0dbcc6-d9b8-11e7-83d8-13cd1ce6842e.png)

**Comment by Estrusco** [comment]
See if you have 

/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

in top of .ts

**Comment by ramveersgh** [comment]
Many Thanks @Estrusco!

Yes, reference was missing, I don't know why i didn't realize it to have the reference and wondering why this was working before.

But now the issue is resolved, Thanks Again!
