### ISSUE TITLE
Custom action in EditDialog

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#301]
Dear Volkan,
first of all I would like to thank you for sharing with us your wonderful template: it had been years since I've seen a project so well done and well documented!

I was wondering if there is a way to perform a custom action in a grid EditDialog...something like trigger an action (press button, dropdown value change, etc.) and preload some other fields of the same EditDialog. Moreover, the "custom action" described above must retrieve data directly from database.

What I managed to do so far has been:
1) add a new tab in an edit dialog
2) add a form, a drop-down and an input-submit in that tab
3) added an action in the xxxEndpoint.cs in order to handle such action (HttpPost)

I don't know how to:
1) remain in the same EditDialog after execution of the custom action (I was able only to return to the underlying Grid)
2) manipulate the EditDialog model (if any)
3) programmatically populate (I mean change value) some fields of the same/others tabs

Thanks for your support
Best Regards

**Comment by volkanceylan** [comment]
Use toolbar or input type button to stay there. You can use LoadEntity or use form.XField.Value to manupilate items.

**Comment by volkanceylan** [comment]
Some code snippets could be helpful to understand issue

**Comment by marcobisio** [comment]
Let's take the Customer module of Northwind database:

1) in the CustomerDialog.Template.html I've added a tab like this:
`<div id="~_TabTest" class="tab-pane">
        <form action="/Services/Northwind/Customer/Test" method="post">
            <input id="City" name="City" type="text" value="">
            <input type="submit" class="btn btn-block btn-success btn-sm" value="test 123">
        </form>
    </div>`

2) then in the CustomerEndpoint.cs I've added the related action method:
`[HttpPost]
        public ActionResult Test() {
            // do some kind of data processing/retrieving...
            return View(MVC.Views.Northwind.Customer.CustomerIndex);
        }`

Is this the right approach or I'm doing something conceptually wrong?
What I want to achieve is to "remain" in the same customer edit dialog and, for example, change the  field "Contact Name" in the first (Customer) tab of the edit dialog.

Thanks for your quick answer!

**Comment by volkanceylan** [comment]
I recommend writing methods like others in endpoint, with request and response objects. In client side you dont have to use submit button or form post. Use an ordinary button, read values from form, use CustomerService.Test to call your service. Of course you need to transform templates after build to have that method.

**Comment by marcobisio** [comment]
Uhm...could you kindly provide some basic code snippets of such implementation?

Thanks again for your support

**Comment by volkanceylan** [comment]
You should first work a bit on it, then ask about where you stuck, i can't write a sample for every request out there

**Comment by marcobisio** [comment]
You're right...I'll try and let you know...
thanks anyway!

**Comment by volkanceylan** [comment]
Please reopen another issue later with your experiences if required

**Comment by marcobisio** [comment]
Ok thanks...I'm still working on that.

**Comment by okowiro** [comment]
Hi Marcobisio,

Could you share your the above code if you managed to get it working? Im working on a similar requirement.

**Comment by marcobisio** [comment]
Hi @okowiro,
I open this issue when I was a super beginner (more than now!): it's too generic...
I suggest to open a new issue with all the details of your implementation and I can give you some hint (I hope)...

Bye
