### ISSUE TITLE
No records in DB after Importing

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#3010]
Hi everyone,

I've a method that import some data. Importing works fine with no errors, but the problem is that when I do a **select * from MyTable** there is no record. 

This is my call to import data:
...
![immagine](https://user-images.githubusercontent.com/22232670/33599809-8ea228d2-d9a7-11e7-887f-05f4c387e9da.png)

Could anyone give me any suggestion, please ??

Thanks all for your time :)

**Comment by Zahar661** [comment]
it works

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ProductExcelImport/ProductExcelImportEndpoint.cs

saving in the database
![image](https://user-images.githubusercontent.com/26430136/33606972-63957b3e-d9d0-11e7-97c8-85e0786d3e42.png)

**Comment by volkanceylan** [comment]
You are closing connection, so transaction is rollbacking. Take a look at sample, and implement as is.
