### ISSUE TITLE
Can't find CreateEnList.Sex enum type! 

### ISSUE THREAD

**Issue by davidzhang9990** [volkanceylan/Serenity#3014]
HI.
Can't find CreateEnList.Sex enum type! If you have recently defined this enum type in server side code, make sure your project builds successfully and transform T4 templates. Also make sure that enum is under your project root namespace, and your namespace parts starts with capital letters, e.g. MyProject.Pascal.Cased namespace

...
 [RadioButtonEditor(typeof(MemberSex)), Required(true), Placeholder("Sex")]
...
![image](https://user-images.githubusercontent.com/23019715/33641487-a3e2c35e-da70-11e7-8b22-248e4dd4c6df.png)

How Can I fix it? Thanks EveryOne

**Comment by 107295472** [comment]
这个框架好难啊，封装的太厉害了。从后台到前端全封装，太难改了

**Comment by 107295472** [comment]
dotnet sergen  你知道是做什么用的吗?

**Comment by receptuna** [comment]
```
    **[ScriptInclude]**
    public enum MemberSex
    { 
    }
```

try to write **[ScriptInclude]** attribute, and then transform T4 templates

**Comment by 107295472** [comment]
$(DotNetSergen) ?
