### ISSUE TITLE
Update sonrası 

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#302]
1.9.13  update sonrası bunu alıyorum. 

'DynamicDataReport' does not implement interface member 'IReport.GetData()'. 'DynamicDataReport.GetData()' cannot implement 'IReport.GetData()' because it does not have the matching return type of 'object'.	
MultiTenancy.Web	C:\MultiTenancy\MultiTenancy\MultiTenancy.Web\Modules\Common\Reporting\DynamicDataReport.cs

**Comment by volkanceylan** [comment]
Change log bakarsanız

**Comment by Olricz** [comment]
tesekkurler.

**Comment by Olricz** [comment]
Volkan Selam, 

Bu problem için update cıkmasını bekledim. Cozumu 1.9.17 ye eklenmedi mi ? Update ettim duzelmedi  ?

![xxrr](https://cloud.githubusercontent.com/assets/16984654/13378279/10fab18c-de0a-11e5-8877-7f6bfb5cf231.JPG)

**Comment by Olricz** [comment]
tamam hallettim. Daha onceki issue'lardan baktım.. Son updatelere bakacagım. neler eklenmişsin. Geliştikçe daha çok seviyorum valla bu platformu. eline saglık.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/blob/master/CHANGELOG.md

ChangeLog'a [BREAKING CHANGE] başlığı ile yazıyorum böyle durumları oradan takip edebilirsiniz.
