### ISSUE TITLE
this.Save with ValidationError

### ISSUE THREAD

**Issue by Wivison** [volkanceylan/Serenity#3022]
I'm calling the this.save method in Dialog. My repository has the implementation of the BeforeSave method with a validation. When the ValidationError is raised, the error message is displayed, but it does not enter the response of this.save:

```
this.save((response) => {
      ...
});
```
Any suggestion?

**Comment by Wivison** [comment]
Someone?

**Comment by brunobola** [comment]
Take a look at this: https://github.com/volkanceylan/Serenity/wiki/Repository-overridable-methods-and-calling-sequence

it may help :)

**Comment by Wivison** [comment]
Thank you @brunobola, but I had seen this sequence and it did not help me. :(

**Comment by Estrusco** [comment]
Try using yout service with

```ts
xyzYourService.yourService(
    // Your request
    {
        EntityId: x.Id,
    }, 
   // On success
    () => manage success
    {
        onError: () => manage error
    }
);
```

**Comment by Wivison** [comment]
Thank you very much @Estrusco!! I was successful implementing the following code:
'
	var self = this;
	if (this.validateForm() && this.validateBeforeSave()) {
		var options = this.getSaveOptions((response) => {
			self.reloadById();
		});

		options.onError = function (response) {
			Q.alert(response.Error.Message);
			self.reloadById();
		}

		Q.serviceCall(options);
	}
`
