### ISSUE TITLE
Load lookup From Another module.

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#3023]
I want To load Lookup from Employee into UserDialog..
this.form.Employee.changeSelect2(e => {
                var EmpId = Q.toId(this.form.Employee.value);
                if (EmpId !== null) {
                    this.form.Email.value = EmployeeDetailsRow.getLookup().itemById[EmpId].Email;  
                }                                         how to load this Scipt.  
            });

**Comment by Estrusco** [comment]
If your problem is that Email is undefined, you have to add [LookupInclude] on Email field in EmployeeDetailsRow

**Comment by ANDY7575** [comment]
no Brother i have problem with Error like "cannot find name "EmployeeDetailsRow" "

**Comment by ANDY7575** [comment]
here is the Solution to my own Query.
` this.form.Employee.changeSelect2(e => {
                var EmpId = Q.toId(this.form.Employee.value);
                if (EmpId !== null) {

                    this.form.Email.value = Web_DSL.Enquiry.EmployeeDetailsRow.getLookup().itemById[EmpId].Email;
                }
            });`
Regards,
Aniket
