### ISSUE TITLE
 Lock the columns

### ISSUE THREAD

**Issue by Marcod93** [volkanceylan/Serenity#3024]
Hello,
I would like to know if there is an attribute for the columns of a form to make sure that by scrolling the table you lock a certain column and remain visible.

Thanks!

**Comment by Zahar661** [comment]
protected getSlickOptions() {
            var opt = super.getSlickOptions();
            opt.frozenColumn = 0
            return opt;
        }

**Comment by Marcod93** [comment]
Thank you very much!! @Zahar661
