### ISSUE TITLE
User Management Edit User Dialog Boxes Not Displaying

### ISSUE THREAD

**Issue by stevenrboone** [volkanceylan/Serenity#3029]
I am very new to Serenity, so I apologize in advance for what seems like it should be an easily resolvable issue. I am making some changes to Serenity to enable dynamically overriding the connection variable based on MachineName to match connection key names in the web.config file. Everything seems to be working fine EXCEPT for the User Management -> Edit User dialog window. It won't come up when the User Name or User's Key Field is clicked on. I am thinking there is either: 1.) Still one or more places I need to dynamically set the connection - that I am not finding - or - 2.) A section of code wasn't modified correctly and has disabled the Edit User dialog. If needed, I can provide any desired code/files; I have inserted my modified UserEndpoint.cs, below. 

Thank you in advance for your kind assistance!

`
namespace IronSpiderSerenity.Administration.Endpoints
{
    using Entities;
    using Repositories;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Services;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web.Mvc;
    using MyRepository = Repositories.UserRepository;
    using MyRow = Entities.UserRow;

    [RoutePrefix("Services/Administration/User"), Route("{action}")]
    [ConnectionKey(typeof(MyRow)), ServiceAuthorize(typeof(MyRow))]
    public class UserController : ServiceEndpoint
    {
        [HttpPost, AuthorizeCreate(typeof(MyRow))]
        public SaveResponse Create(SaveRequest<MyRow> request)
        {
            using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
            using (var uow = new UnitOfWork(connection))
            {
                var result = new MyRepository().Create(uow, request);
                uow.Commit();
                return result;
            }
        }

        [HttpPost, AuthorizeUpdate(typeof(MyRow))]
        public SaveResponse Update(SaveRequest<MyRow> request)
        {
            using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
            using (var uow = new UnitOfWork(connection))
            {
                var result = new MyRepository().Update(uow, request);
                uow.Commit();
                return result;
            }
        }

        [HttpPost, AuthorizeDelete(typeof(MyRow))]
        public DeleteResponse Delete(DeleteRequest request)
        {
            using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
            using (var uow = new UnitOfWork(connection))
            {
                var result = new MyRepository().Delete(uow, request);
                uow.Commit();
                return result;
            }
        }

        [HttpPost, AuthorizeDelete(typeof(MyRow))]
        public UndeleteResponse Undelete(UndeleteRequest request)
        {
            using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
            using (var uow = new UnitOfWork(connection))
            {
                var result = new MyRepository().Undelete(uow, request);
                uow.Commit();
                return result;
            }
        }

        public RetrieveResponse<MyRow> Retrieve(RetrieveRequest request)
        {
            using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
            {
                return new MyRepository().Retrieve(connection, request);
            }
        }

        public ListResponse<MyRow> List(ListRequest request)
        {
            using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
            {
                return new MyRepository().List(connection, request);
            }
        }

//

        private static string[] permissionsUsedFromScript;

        /// <summary>
        /// This declares a dynamic script with key 'UserData' that will be available from client side.
        /// We don't cache it at dynamic script manager, because dynamic scripts are cached globally,
        /// similar to static variables, not per user.
        /// </summary>
        [NonAction, DataScript("UserData", CacheDuration = -1), ServiceAuthorize]
        public ScriptUserDefinition GetUserData()
        {
            var result = new ScriptUserDefinition();
            var user = Authorization.UserDefinition as UserDefinition;

            if (user == null)
            {
                result.Permissions = new Dictionary<string, bool>();
                return result;
            }

            result.Username = user.Username;
            result.DisplayName = user.DisplayName;
            result.IsAdmin = user.Username == "admin";

            result.Permissions = TwoLevelCache.GetLocalStoreOnly("ScriptUserPermissions:" + user.Id, TimeSpan.Zero,
                UserPermissionRow.Fields.GenerationKey, () =>
                {
                    var permissions = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);

                    if (permissionsUsedFromScript == null)
                    {
                        permissionsUsedFromScript = new UserPermissionRepository().ListPermissionKeys().Entities
                            .Where(permissionKey =>
                            {
                                // this sends permission information for all permission keys to client side.
                                // if you don't need all of them to be available from script, filter them here.
                                // this is recommended for security / performance reasons...
                                return true;
                            }).ToArray();
                    }

                    foreach (var permissionKey in permissionsUsedFromScript)
                    {
                        if (Authorization.HasPermission(permissionKey))
                            permissions[permissionKey] = true;
                    }

                    return permissions;
                });

            return result;
        }
    }
}
`

**Comment by biggikalli** [comment]
Have you checked the apparent errors in browser console? That is the first step in checking causes and often gives more direct information than opening an issue and ask for review and suggestions. Can you add a screen shot to this issue if your browser console shows any error when opening the Edit Window?Good luck. On Dec 8, 2017 2:47 PM, stevenrboone <notifications@github.com> wrote:I am very new to Serenity, so I apologize in advance for what seems like it should be an easily resolvable issue. I am making some changes to Serenity to enable dynamically overriding the connection variable based on MachineName to match connection key names in the web.config file. Everything seems to be working fine EXCEPT for the User Management -> Edit User dialog window. It won't come up when the User Name or User's Key Field is clicked on. I am thinking there is either: 1.) Still one or more places I need to dynamically set the connection - that I am not finding - or - 2.) A section of code wasn't modified correctly and has disabled the Edit User dialog. If needed, I can provide any desired code/files; I have inserted my modified UserEndpoint.cs, below.
Thank you in advance for your kind assistance!
`
namespace IronSpiderSerenity.Administration.Endpoints
{
using Entities;
using Repositories;
using Serenity;
using Serenity.ComponentModel;
using Serenity.Data;
using Serenity.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using MyRepository = Repositories.UserRepository;
using MyRow = Entities.UserRow;
[RoutePrefix("Services/Administration/User"), Route("{action}")]
[ConnectionKey(typeof(MyRow)), ServiceAuthorize(typeof(MyRow))]
public class UserController : ServiceEndpoint
{
    [HttpPost, AuthorizeCreate(typeof(MyRow))]
    public SaveResponse Create(SaveRequest<MyRow> request)
    {
        using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
        using (var uow = new UnitOfWork(connection))
        {
            var result = new MyRepository().Create(uow, request);
            uow.Commit();
            return result;
        }
    }

    [HttpPost, AuthorizeUpdate(typeof(MyRow))]
    public SaveResponse Update(SaveRequest<MyRow> request)
    {
        using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
        using (var uow = new UnitOfWork(connection))
        {
            var result = new MyRepository().Update(uow, request);
            uow.Commit();
            return result;
        }
    }

    [HttpPost, AuthorizeDelete(typeof(MyRow))]
    public DeleteResponse Delete(DeleteRequest request)
    {
        using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
        using (var uow = new UnitOfWork(connection))
        {
            var result = new MyRepository().Delete(uow, request);
            uow.Commit();
            return result;
        }
    }

    [HttpPost, AuthorizeDelete(typeof(MyRow))]
    public UndeleteResponse Undelete(UndeleteRequest request)
    {
        using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
        using (var uow = new UnitOfWork(connection))
        {
            var result = new MyRepository().Undelete(uow, request);
            uow.Commit();
            return result;
        }
    }

    public RetrieveResponse<MyRow> Retrieve(RetrieveRequest request)
    {
        using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
        {
            return new MyRepository().Retrieve(connection, request);
        }
    }

    public ListResponse<MyRow> List(ListRequest request)
    {
        using (var connection = SqlConnections.NewByKey("Default_" + Environment.MachineName))
        {
            return new MyRepository().List(connection, request);
        }
    }

//
    private static string[] permissionsUsedFromScript;

    /// <summary>
    /// This declares a dynamic script with key 'UserData' that will be available from client side.
    /// We don't cache it at dynamic script manager, because dynamic scripts are cached globally,
    /// similar to static variables, not per user.
    /// </summary>
    [NonAction, DataScript("UserData", CacheDuration = -1), ServiceAuthorize]
    public ScriptUserDefinition GetUserData()
    {
        var result = new ScriptUserDefinition();
        var user = Authorization.UserDefinition as UserDefinition;

        if (user == null)
        {
            result.Permissions = new Dictionary<string, bool>();
            return result;
        }

        result.Username = user.Username;
        result.DisplayName = user.DisplayName;
        result.IsAdmin = user.Username == "admin";

        result.Permissions = TwoLevelCache.GetLocalStoreOnly("ScriptUserPermissions:" + user.Id, TimeSpan.Zero,
            UserPermissionRow.Fields.GenerationKey, () =>
            {
                var permissions = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);

                if (permissionsUsedFromScript == null)
                {
                    permissionsUsedFromScript = new UserPermissionRepository().ListPermissionKeys().Entities
                        .Where(permissionKey =>
                        {
                            // this sends permission information for all permission keys to client side.
                            // if you don't need all of them to be available from script, filter them here.
                            // this is recommended for security / performance reasons...
                            return true;
                        }).ToArray();
                }

                foreach (var permissionKey in permissionsUsedFromScript)
                {
                    if (Authorization.HasPermission(permissionKey))
                        permissions[permissionKey] = true;
                }

                return permissions;
            });

        return result;
    }
}

}
`

**Comment by stevenrboone** [comment]
biggikalli 

Thank you for pointing out the obvious - that I was overlooking! I have begun to go down the browser console route, hopefully that will lead to success in fixing this issue!

**Comment by biggikalli** [comment]
No problem. Just my little contribution in paying it forward. In late 2015, when starting my Serenity journey, I was soon pointed to that same exact "obvious". Volkan & the community created a special Issue/Thread long ago which contains a guideline for self help instead of asking premature and perhaps an unnecessary question:1. "Developer Guide" gives great insight into best practices, common detailed tasks.2. Diving into previous & relevant solved/closed issues for info. My lifesaver in 80%3. Wiki... & other stuff on serenity.isIf still stuck, there is little harm in creating an issue but it's good to follow the short checklist Issue structure, see same old thread. This helps to get quicker replies with more quality advice. I found Serenity in November 2015 and it was a big bite/steep curve, at least for me. But men how I was amazed on the possibilities and in 2016 alone, I was able to finish 4 web apps that served very different & separate purposes. I was "away" this year but now starting again, there are so many ideas and also ways to achieve them w Serenity. I just hope to be able to catch up with the rapid & exciting changes. You wouldn't believe this incredible Volkan dude, he started and is driving Serenity with incredible growth & impact.  Good journey. On Dec 8, 2017 3:40 PM, stevenrboone <notifications@github.com> wrote:biggikalli
Thank you for pointing out the obvious - that I was overlooking! I have begun to go down the browser console route, hopefully that will lead to success in fixing this issue!

**Comment by stevenrboone** [comment]
I have edited all of the *Endpoint.cs files according to the instructions given, but find that the Edit User dialog of the User Management module requires that the ConnectionKey be specified in SettingsRow.cs in order to work, and also to be specified in LanguageRow.cs in order for no errors to be thrown by the application. Because of this, I am not able to dynamically specify the ConnectionKey - which is my goal. Does anyone have any workarounds/ideas for this? Thank you!
