### ISSUE TITLE
Northwind Customer EditDialog not showing after switch to SS2008R2

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#303]
Dear Volkan,
I have a (brand) new Serenity template project which is working fine on LocalDB, but when I modify the connection strings in order to connect to a Microsoft SQL Server 2008 R2 (SP3), then I'm unable to use the EditDialog of the Customer table (Northwind database of course).
All others edit dialog seems working fine (Product, Orders, etc) but when I click on the customer grid, nothing happens and the edit dialog don't show up...
Can be something related to the auto detection of the sql dialect?
Btw, the connection strings that I use are something like this: 

`<add name="Northwind" connectionString="Data Source=SERVERNAME;Initial Catalog=eService_Northwind_v1;Integrated Security=False;User Id=USER;Password=PASSWORD;MultipleActiveResultSets=True" providerName="System.Data.SqlClient" />`

Note that such issue cannot be related to my other issue because it's a brand new project with zero customization...

Once again thanks for your support

**Comment by volkanceylan** [comment]
There is no way to auto detect SQL 2008 R2 etc, you need to set your dialect to 2005 or 2008.

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_set_database_dialect_for_connections.html

**Comment by marcobisio** [comment]
Ok thank you very much!

**Comment by marcobisio** [comment]
Nothing to do...Customer edit dialog isn't showing up...
I tried both 
`SqlConnections.GetConnectionString("Northwind").Dialect = SqlServer2005Dialect.Instance;`

and 

`SqlConnections.GetConnectionString("Northwind").Dialect = SqlServer2012Dialect.Instance;`


All others edit dialog are working fine...any ideas?

Thanks

**Comment by dfaruque** [comment]
Replace CONCATE with + in customerRow.cs
