### ISSUE TITLE
LookupInclude for LinkingSetRelation Field

### ISSUE THREAD

**Issue by tomuee** [volkanceylan/Serenity#3030]
Hello all!

I have the Problem that i don't know how to include a field of a row into the lookup.
For example:
Table "Components"
Table "Products"
Table "ComponentsProducts"
The Components table and the products table have a n:m relation with ComponentsProducts as link table.
In the ProductsRow.cs is the ComponentsList, like this

> [LookupEditor(typeof(ComponentsRow), Multiple = true), NotMapped]
> [LinkingSetRelation(typeof(ComponentsProductsRow), "ProductsId", "ComponentsId")]
> public List<Int32> ComponentsList
> {
>     get { return Fields.ComponentsList[this]; }
>     set { Fields.ComponentsList[this] = value; }
> }

When I add the `LookupInclude` Attribute a SQLException is thrown. Obviously.
But how can i add this field into the lookup?

Thank you in andvance for your help
tomuee

**Comment by javaman63** [comment]
What field do you want to add, to what lookupeditor?

**Comment by tomuee** [comment]
I must say that I'm new to Serenity.

I want to have the ComponentsList in ProductsRow on the client-side dialog. Is there any possibility i can do that?
With `LookupInclude` a SQLException is thrown because Serenity selects the column "ComponentsList" of the Products Table, which doesn't exist.
In some other places I need this too. With `Q.getLookup('Products')` i get the Lookup which contains the items, but without ComponentsList.

**Comment by javaman63** [comment]
You have to define the list on your xyzForm.

        public ListField<Int32> ComponentsList { get; set; }

**Comment by volkanceylan** [comment]
LookupInclude wouldn't work with such columns, it just does a simple select query.

**Comment by tomuee** [comment]
okay thank you.
