### ISSUE TITLE
Select All Checkbox on Form

### ISSUE THREAD

**Issue by mayatstafford** [volkanceylan/Serenity#3031]
Have some static checkboxes on my form.  I want to add a checkbox or button that will select/deselect all when clicked.
Here's what I have so far:
_Layout.cshtml

`function toggle() {
        cbCheckAll = document.getElementsByName('CheckAll');

        cb1 = document.getElementsByName('option1');
        cb1.checked = source.checked;

        cb2 = document.getElementsByName('option2');
        cb2.checked = source.checked;

        cb3 = document.getElementsByName('option3');
        cb3.checked = source.checked;
    }`

Form.cs
` public Boolean CheckAll { get; set; }`

EditorDialog.ts
`this.form.CheckAll .element.add("onClick","toggle();")`

This is not working of course, the onClick is underlined.   I don't have much experience with typescript so please excuse me if this is a dumb question.   Thank you.

**Comment by Estrusco** [comment]
You have to write your code in xyzEditorDialog.ts. Your toggle function 

```ts
    constructor() {
       super();

       this.form.CheckAll.change(e => {
           this.toggleCheck(this.form.CheckAll.value);
        });
   }

   protected toggleCheck(value) {
       [...]
   }
```

**Comment by mayatstafford** [comment]
Thank you so much!    I'm going to add what I did in case some one else needs it:

On xyForm.ts I had to add the CheckAll checkbox.
` export interface xyzForm {
        CheckAll: Serenity.BooleanEditor;
    }

[['CheckAllCamera', () => Serenity.BooleanEditor]]`

On xyzForm.cs:
`public Boolean CheckAll { get; set; }`

xyzEditorDialog.ts
`        constructor() {
            super();
            this.form = new xyzForm(this.idPrefix);

            this.form.CheckAll.change(e => {
                this.toggleCheck(this.form.CheckAll.value);
            });
        }



        protected toggleCheck(value) {
            this.form.cb1.value = value;
            this.form.cb2.value = value;
 	    this.form.cb3.value = value;
       }`

**Comment by brunobola** [comment]
@Estrusco awesome work, how to handle the changed value in dialog.ts to make same form of calculation on the fly ?
