### ISSUE TITLE
Removing Toolbar div completely

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3032]
Hi All,

for a very Special case (only displaying Action Buttons within a Serenity grid) I want to completely remove the Toolbar div so that there is no large gap between the title and the actual grid.

I know that I can remove the toolbar Buttons and the search field but that leaves still the same vertical gap between title and the grid.

Is there some easy overriding of a method (like removing the search field by overriding createQuickSearchInput)?

I did a search in the classes:
- Serenity.EntityGrid
- Serenity.DataGrid

but didn't find anything useful.

Thanks for any input and

with Kind regards,

John

**Comment by Zahar661** [comment]
in .less
.s-MyModule-xyzDialog  s-Toolbar{
    display:none;
}

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serenity/issues/2086

**Comment by Estrusco** [comment]
You can completely hide div with $('.s-DialogToolbar').hide();

**Comment by JohnRanger** [comment]
Hi @Zahar661 ,
thanks - the solution in #2086 given by Estrusco is exactly what I wanted :-)

Thanks @Estrusco , I played around with this but found your solution in #2086 the perfect hit :-)

```ts
protected createToolbar(): void {
}
```

Thanks for all your help and with Kind regards,

John
