### ISSUE TITLE
Filtering menu with permissions

### ISSUE THREAD

**Issue by paulmrozowski** [volkanceylan/Serenity#3033]
This seems like it should be easy, but I'm having trouble finding a good example of how to do this. In the AdminLTENavigation.cs file there is the "Theme Samples" NavigationMenu. As a test, I want to hide this menu if the logged in user doesn't have permission. It seems like I should just be able to define a permission key that the current user doesn't have assigned to them, and it shouldn't appear when they log in.

```c#
[assembly: NavigationMenu(8000, "Theme Samples", icon: "fa-diamond", Permission= TestWebsite.Administration.PermissionKeys.General)]

[Description("Site Administration")]
public const string General = "SiteAdministration:General";
```

Yes, I just defined the "General" constant in the AdministrationPermissionKeys.cs file and not AdminLTEPermissionKeys.cs, but since this is just a string anyway, I wouldn't think that would make a difference. 

Is there an example in the docs that I'm missing? Or can someone point out what I'm doing wrong? 

Thanks,

**Comment by volkanceylan** [comment]
Your permission keys should start with same module prefix like other strings in that file. Other than that it doesn't matter where you define, or not even define it.
