### ISSUE TITLE
How can i add double click event on data grid ?

### ISSUE THREAD

**Issue by chintansoni54** [volkanceylan/Serenity#3034]
Currently there is not any method available to handle double click event in data grid.
Is there any way to add double click event on data grid.

**Comment by brunobola** [comment]
https://github.com/mleibman/SlickGrid/wiki/Grid-Events

**Comment by JohnRanger** [comment]
@brunobola ,
sorry, but your information does not help too much in this particular case (how to implement this in Serenity) :-).

What @chintansoni54 probably means is, to extend the serenity.datagrid class to also support double click events within the grid as the Standard "onClick" Event is defined there (if I understand correctly).

...and then define the **onDblClick** method probably like this:

```ts
protected onDblClick(e: JQueryEventObject, row: number, cell: number): void;
```

@volkanceylan : Would it be possible for you to consider also to support the doubleclick Event within the Serenity grid by Default? (Slickgrid provides this out of the box).

With Kind regards,

John

**Comment by volkanceylan** [comment]
in constructor:

```ts
            this.slickGrid.onDblClick.subscribe((e, p) => {
                // p.row, p.col
            });

```

**Comment by volkanceylan** [comment]
i wouldn't recommend double click from a usability / mobile perspective though

**Comment by chintansoni54** [comment]
@volkanceylan  @JohnRanger @brunobola 

I fixed this issue with this 
https://rakeshkanani.gitbooks.io/detail-development/content/enabled-double-click-event-in-data-grid.html
