### ISSUE TITLE
Question about Authorization

### ISSUE THREAD

**Issue by chockyu** [volkanceylan/Serenity#3035]
According the docs , I used  ModifyPermission and InsertPermission  to myrow.cs . but the Authorization only worked when the user click savebutton or updateButtion... how  should I do    when the users without authorization click Creatbutton or click collume Editer link , the  Alert message  show at the first time.

**Comment by JohnRanger** [comment]
Hi @chockyu ,
I suggest to remove the unallowed Buttons and other things - if a user does not have the appropriate authorization - so he/she cannot even click on something they should not.

How to remove Buttons: #2376 

and put this into the following Code:

```cs
  if (!Authorization.HasPermission ("<your desired permission here>"))
{
     // *** Code for removing button goes here... *** 
}

With Kind regards,

John
