### ISSUE TITLE
Master-detail-relation

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#3036]
Hello,

I am constructing a master detail relation similar to the Northwind orderdetail example.
The Edit Order Detail form is like : 

 **[FormScript("Northwind.OrderDetail")]
    [BasedOnRow(typeof(Entities.OrderDetailRow))]
    public class OrderDetailForm
    {
        public Int32 ProductID { get; set; }
        public Decimal UnitPrice { get; set; }
        public Int32 Quantity { get; set; }
        public Double Discount { get; set; }
    }** 

When running this form, Product Name gets filled in for the ProductID.
I am trying to understand the lookup functionality of Serenity, but this is a hard one for me.

My goal is to show more than one field of the parent-entity, not just one as in the orderdetail example with Product Name.
Is this possible ?

Greetings from the Netherlands......

**Comment by gguadalupe** [comment]
Hi! If I understand you correctly, you need to work on your ChildEditor.ts

In my case, I have 4 with descriptions that I communicate back to the Parent Object.

This is the code I have in my ChildEditor.ts

```
        protected validateEntity(row: CrossQuoteDetailRow, id: number) {
            if (!super.validateEntity(row, id))
                return false;

            row.SizeDescription = CrossSizeRow.getLookup()
                .itemById[row.SizeId].Description;
            row.RadiusDescription = CrossRadiusRow.getLookup()
                .itemById[row.RadiusId].Description;
            row.MinorDescription = CrossMinorRow.getLookup()
                .itemById[row.MinorId].Description;
            row.MajorDescription = CrossMajorRow.getLookup()
                .itemById[row.MajorId].Description;

            return true;
        }
```
Remember to add the LookupScript in each of your objects.
This is the result.

![image](https://user-images.githubusercontent.com/24615955/33808811-446e4504-dda1-11e7-9a67-ec479cfb94ae.png)

Hope it helps

Gus

**Comment by GreenUtil** [comment]
As far as I can see the validateEntity method is called when a new detail record is saved. What I mean is a grid with detail records in which more than one field of the parent are shown, I think just like yours, but not only when adding a detail record but also when loading some existing detail records.

**Comment by GreenUtil** [comment]
Well, I found a workaround. With an additional database-view the necessary fields can be retrieved. A database-view can't be updated, so the default Update functionality of the detail-record has be to overridden...
