### ISSUE TITLE
Table with Views

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#3037]
Hi,

I am trying to create a table as Order Status with views from different tables. I want a table with data from order table, employee table, event table and a column with status. My scenario is to create a table with the information of  order id, customer name from order table, events from event table and employee from the employee table all are having relation with order id and  a new editable column with status. How to achieve this is there any sample or example available. I searched the guide but not able to find one. Should i write a migration for this.

Regards,
Srinivas

**Comment by Zahar661** [comment]
Hello! You will give an example of 2 lines in EXCEL. Attach a photo here.

**Comment by srinivas1910** [comment]
Hi @Zahar661 ,

![image](https://user-images.githubusercontent.com/29406374/33839041-32af6c78-deb7-11e7-930c-48906090dc54.png)


this is my order form. the order form will be having different types of events.  Each event will be assigned to a different employee. I require a table which will be tracking the status of the order. Each employee will update their work in a column named as status with drop down values like InProgess, Completed etc..

Regards,
Srinivas

**Comment by Zahar661** [comment]
BasicSamples/Grids/GridFilteredByCriteria

**Comment by srinivas1910** [comment]
Hi @Zahar661 thanks for the quick response, but my requirement is not GridFilteredByCriteria.
Below is the table iam looking for

![image](https://user-images.githubusercontent.com/29406374/33844261-c529e548-dec5-11e7-9142-c78cd1439114.png)

In my order form i have added different tables with details of Event and the work assigned to the employee for that particular order.  (tables are based on the castlist entity from movieDB example). 
so the data iam looking for the table is to be retrieved from two different tables (eventlist and employee list tables)based on Order Id and a column with Status (like genre in MovieDB Example).

**Comment by Zahar661** [comment]
EventRow view. Leftjoin to Ordrer and LeftJoin to Castomer through Ordrer.CastomerId. Select and Save Line in  example GridFilteredByCriteria

**Comment by Zahar661** [comment]
example
```
[DisplayName("IP"), Expression("jDogovor.[IngenerProjectID]"), Column("IngenerProjectID"), ForeignKey("[dbo].[IngenerProject]", "IngenerProjectID"), LeftJoin("jIngenerProject"), TextualField("IngenerProjectName")]
        public Int32? IngenerProjectID
        {
            get { return Fields.IngenerProjectID[this]; }
            set { Fields.IngenerProjectID[this] = value; }
        }
        [DisplayName("IPName"), Expression("jIngenerProject.[Name]")]
        public String IngenerProjectName
        {
            get { return Fields.IngenerProjectName[this]; }
            set { Fields.IngenerProjectName[this] = value; }
        }
```

**Comment by srinivas1910** [comment]
Thank you @Zahar661  i think is done for me
