### ISSUE TITLE
When I go to assign permissions to a role, the new Modules are not showing up,

### ISSUE THREAD

**Issue by SamCam15** [volkanceylan/Serenity#3038]
I have ReadPermisision and ModifyPermisision on each table in the modules as below. 

    [ConnectionKey("Portal"), TableName("[dbo].[tblCaseDetails]")]
    [DisplayName("Case"), InstanceName("Case"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class CaseRow : Row, IIdRow, INameRow
    {

Really great framework by the way, loving it!

**Comment by Zahar661** [comment]
I do like this
[ReadPermission("MyModule:MyRow:Read")]
[ModifyPermission("MyModule:MyRow:Modify")]

**Comment by VR-Architect** [comment]
Did you 1) define the permission in your *Row.cs file, 2) assign permissions to the role via the GUI, 3) then the role to the user via the GUI as an administrator, and then 4) log in as that new user?

**Comment by judejay** [comment]
Zahar Thanks that did the trick.
