### ISSUE TITLE
New Entries Dialogue

### ISSUE THREAD

**Issue by TetsuwanAtom** [volkanceylan/Serenity#3039]
Hi
I have a tenant running with AD authentication and different levels of permissions for the users.  They have access to 1 table to enter data but when they click the Add button the dialogue doesn't appear.  If i log in with my admin account, open the dialogue, then log out.   They log back in and the Add dialogue works as intended.  

The custom permissions are read, write, update, and delete.  As far as i can tell they work like they're supposed to once the dialogue is working.

Thanks

**Comment by Zahar661** [comment]
Use LookupEditor? Permission to Lookup is there? what does it write in the browser console?

**Comment by TetsuwanAtom** [comment]
I found the issue.  I hadn't set read permissions for these users on the lookup tables that their table references.
  
Thanks for your help

**Comment by Zahar661** [comment]
[LookupScript("MyModule.MyName",Permission ="*")]

**Comment by TetsuwanAtom** [comment]
I see what you mean now.  Thanks again for your help.
