### ISSUE TITLE
Location of uploaded files

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#304]
Is there any way to customize the location of upload folder (\App_Data\upload\....)? What is the setting or what class/method to override? Or some more hints on how save to database ;-)

It would make app re-deployments easier if the upload folder was somewhere outside of the application root directory (or on a different volume). Many thanks in advance.

**Comment by VictorTomaili** [comment]
look at web.config :)

**Comment by c9482** [comment]
Thanks Victor, that's slightly embarrassing. I would still like some hints on saving to database.

**Comment by VictorTomaili** [comment]
I dont prefer save files to database. And i dont have some hints. Sorry.

**Comment by c9482** [comment]
Understood, thanks anyway.
