### ISSUE TITLE
Roles and Permissions in Serenity

### ISSUE THREAD

**Issue by MayaBurns** [volkanceylan/Serenity#3040]
I have created permission keys and then added permission keys to roles.  I then assign the roles to a user.  However, the user does not seem to have permission through the roles.  

I was just wondering if someone can clarify if this feature had been built out yet.  I was reading the manual and it says:
"Serene has user, role and rights management built in."  but then under it, it says "This feature is not embedded in Serenity itself..."

I assume it's just the adding of permissions to roles and CRUD of users, roles and permission keys.

Searching the forum, it seems like users has to add roles into Serenity to be recognized?

Is the above the correct assumption? if so, has anyone done this and would like to share or point me to the right direction? 

Thank you in advance.

**Comment by Zahar661** [comment]
User permissions are inherited from roles. Check the spaces at the beginning and end of the permission. especially if you use "or" "permission1|permissions2", "permission1 | permissions2" error.

**Comment by MayaBurns** [comment]
@Zahar661  Thanks for the reply but what you are doing is permission keys.  Have you used the roles to give users permission directly and it works out of the box?

**Comment by Zahar661** [comment]
no. I make a permission with the title of the role. and I assign his roles. then I use permission.

**Comment by MayaBurns** [comment]
@zahar661 looks like we can only use permission keys as stated un this post and else where #2822.

 How do you guys manage a large user base?  
(1) First they have to log in and (2) then you have to give them permission?  Is there an easier method I am missing? @volkanceylan

**Comment by VR-Architect** [comment]
If you are creating a corporate application, it is best practice to have the roles granted explicitly by an admin and not automatically as part of registering. If you are building a public website like say like a WordPress site, you could auto-assign roles to the user after they register a new account via a database trigger.  I would bet there was a spot to do it in the Serenity code under that same area.

**Comment by MayaBurns** [comment]
I got it to where i was assigning usernames who belong to active directory groups and map them to a particular role. The plan was to auto assign user to role based on their groupsnin active directory. Howevere, the builtin roles does not seem to work with the permission keys yet. So i was wondering if there is an implementation existing to get roles to work with permissions. 

Maybe, instead of mapping it to roles, I need to map it to permission keys based on their active directory?  Any thoughts on best practices?

**Comment by volkanceylan** [comment]
You may query their AD groups on first creation / or each login, map them to roles in DB, add / update roles. Did this in a project with also IdentityServer4 and it worked fine (can't share code sorry).

**Comment by MayaBurns** [comment]
I already built a separate table to map defined usernames or groups to a role defined in serenity. However, when the users has this role and the role has the permission. Serenity does not seems to grant them permission through the roles. By default, is the permission using roles work out of the box or  I have to extend that??
