### ISSUE TITLE
Sample for multi field lookup search

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#3041]
Hi, is there any sample where I can see lookup dialog rather than a drop down. For example a product lookup with multiple fields with search and return back with product code

**Comment by AlperanQ** [comment]
I think you're asking the sample in the Serenity Demo. You can check it out [here](http://serenity.is/serene/Northwind/Order).

**Comment by Parbil** [comment]
Thanks, what I am looking is a sample where it goes to a search dialog with multi column search and selected row field value to return in to the form field. The order sample all of them are single field drop down, but in case if we need search customer with their mobile no etc.  we need a lookup screen with sorting and search as seen in the list grid screen. I know it is possible but just looking if there any sample so that I can straightway implement that.

**Comment by AlperanQ** [comment]
I understand. Unfortunately, I don't know such an sample.

**Comment by volkanceylan** [comment]
See product picker in demo (StartSharp only)

**Comment by Parbil** [comment]
Excellent. Thanks.  

Now going through all required features. 
Planning to become a premium soon.
