### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by ilannt** [volkanceylan/Serenity#3044]
Hi,

I'm trying to create unit tests for my serenity based website and it seems like it can't read the connection strings located in the web.config file, error message: System.InvalidOperationException: No connection string with key Default in configuration file! I'm trying to call the endpoint from my test method. are there some prerequisites when we need to call endpoints from outside the application?

please help

thank you

--ilann

**Comment by ilannt** [comment]
I figured it out but now I'm getting the following error message:
Message: Test method Project1.Test.UnitTest1.TestMethod1 threw exception: 
System.InvalidProgramException: Default IDependencyResolver implementation is not set. Use Serenity.Dependency.SetResolver to set your dependency resolver implementation.

please help.

**Comment by volkanceylan** [comment]
See tests in Serenity source code, e.g. under Serenity.Test and Serene.Test
