### ISSUE TITLE
How to remove extra buttons from dialog

### ISSUE THREAD

**Issue by Itsathere** [volkanceylan/Serenity#3047]
I am opening BugComment dialog in Bug module. Module opens but it adds extra buttons of **undo, localisation, clone and delete** which is unnecessary. Extra button is coming when I open it into another module, it work fine with same module. I have tried to find that button using class and tried to remove them but when I remove/hide/disable button on edit in another module it effect the edit dialog.

![1](https://user-images.githubusercontent.com/16954075/34031070-b260021c-e195-11e7-90c7-4c76be3f3d5e.PNG)
![2](https://user-images.githubusercontent.com/16954075/34031071-b2b2ee32-e195-11e7-9ba1-64088097ece1.PNG)
![3](https://user-images.githubusercontent.com/16954075/34031072-b2e67414-e195-11e7-86bf-f148d902db71.PNG)
![4](https://user-images.githubusercontent.com/16954075/34031073-b31bf9cc-e195-11e7-9976-49988d87a329.PNG)

And may I know how to **add dialogue title**
I used to find class **ui-dialog-title** and added text to this class. Is there any another way to add dialog title

**Comment by Estrusco** [comment]
See here https://github.com/volkanceylan/Serenity/issues/1286

and search for getToolbarButtons in samples.

Also see https://github.com/volkanceylan/Serenity/issues/1889 for title

**Comment by Itsathere** [comment]
I have followed #1286 but still facing the same issue. Actually, I have dialog over another dialog.
Code snippet I have added is **super.updateInterface();**. For more you can check below code
` protected afterLoadEntity() {
            super.afterLoadEntity();
            super.updateInterface();
}`

**Comment by Estrusco** [comment]
Use

```ts
protected getToolbarButtons(): Serenity.ToolButton[] {
    var b = super.getToolbarButtons();

    b.splice(Q.indexOf(b, x => x.cssClass == "delete-button"), 1);
    b.splice(Q.indexOf(b, x => x.cssClass == "undo-delete-button"), 1);
    b.splice(Q.indexOf(b, x => x.cssClass == "localization-button"), 1);
    b.splice(Q.indexOf(b, x => x.cssClass == "clone-button"), 1);

    return b;
}
```

**Comment by Itsathere** [comment]
` buttons.push({
        title: Q.text('Comments'),
        cssClass: 'comment-button',
        icon: 'icon-speech text-blue',
        onClick: () => {
                var dlg = new CommentUserDialog();
                // let grid watch for changes to manually created dialog, 
                // so when a new item is saved, grid can refresh itself
                this.initDialog(dlg);
                dlg.loadEntityAndOpenDialog(<CommentUserRow>{
                    UserID: 1,   // your value
                    secondField: value
                });
        }
    });`

The way I had implemented opendialog was incorrect. When I have followed the above code I am seeing the actual dialog. 
Thanks
You can close the ticket.

**Comment by JohnRanger** [comment]
Hi @Itsathere 

you can Close the ticket yourself :-)

With Kind regards,

John
