### ISSUE TITLE
Edit User Roles checklist and multitenancy

### ISSUE THREAD

**Issue by JKneenChaparral** [volkanceylan/Serenity#305]
In the MultiTenancy example, when you Edit User Roles, the checklist contains all roles, not just roles associated with the current TenantId. How would one go about restricting the checklist to include only the roles associated with the current TenantId? 
Thanks!!

**Comment by volkanceylan** [comment]
Did you try applying topic below to RoleRow lookup script?

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/handling_lookup_scripts.html

**Comment by JKneenChaparral** [comment]
Thank you!

I had simply forgotten to  remove the [LookupScript] attribute from RoleRow.

Thank you for the quick response and terrific work!


Regards


John Kneen

**Comment by volkanceylan** [comment]
You re welcome
