### ISSUE TITLE
How to set value in dropdown of .dialogOpen()

### ISSUE THREAD

**Issue by Itsathere** [volkanceylan/Serenity#3051]
I want to set dropdown(LookupEditor) value when dialog opens from another module's dialog.ts

         `buttons.push({
                title: Q.text('Comments'),
                cssClass: 'comment-button',
                icon: 'icon-speech text-blue',
                onClick: () => {
                        new CommentUserDialog().dialogOpen(); //Here, I want to pass data to set lookupeditor value 
                }
            });`

**Comment by mafdy** [comment]
`buttons.push({
            title: Q.text('Comments'),
            cssClass: 'comment-button',
            icon: 'icon-speech text-blue',
            onClick: () => {
                    var dlg = new CommentUserDialog();

                    // let grid watch for changes to manually created dialog, 
                    // so when a new item is saved, grid can refresh itself
                    this.initDialog(dlg);
                    dlg.loadEntityAndOpenDialog(<CommentUserRow>{
                        UserID: 1,   // your value
                        secondField: value
                    });
            }
        });`

**Comment by Wivison** [comment]
Take a look at this: http://serenity.is/demo/BasicSamples/DefaultValuesInNewDialog
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts

it may help
