### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rcmsoftwaredevelopment** [volkanceylan/Serenity#3054]
Hi Volkan

Do you have a road map for the serenity framework over the next 12 months or know what additional functionality (code samples or examples like e-commerce) you may add to the advanced samples?

Cheers

Ray

**Comment by brunobola** [comment]
You already have more samples at the Professional versions...

**Comment by JohnRanger** [comment]
@brunobola ,
yep - but that was not the question :-) and it is a good one in my opinion. I am also interested to know the Roadmap.

Some suggestions :
- Getting out of beta for the asp.net Core
- new styles
- updated guide with much more insides (like customizing grids and Dialogs - eg what can be disabled / overridden, etc)

:-)

With Kind regards,

John

**Comment by kilroyFR** [comment]
Totally Interested here too. Starting my yearly subscription in january and having several projects i want to use serenity framework.

**Comment by volkanceylan** [comment]
Here are a list of some of examples / modules that might make it into StartSharp:

- Premium Themes (will try to get some popular themes integrated, but need to sort out licencing issues, in worst case it will be only a how-to document, e.g. how to apply Metronic, Limitless, Remark etc.)
- Survey module (like Google Forms, already implemented for some other project, will port into SS)
- Mobile native application samples for IOS / Android (will show how to call services, implement some of Northwind there, limited offline functionality / sync will come later, currently developing an app for a client)
- Push notification queue, and integration with APNS / Firebase
- Finalize Meeting module with Agenda, Decisions, SSRS report output, and Outlook calendar invitation
- CMS (did this years ago but need to check modern ones and get best parts out of them)
- E-Commerce (our new dev Alper is very reluctant on this)
- Better docs for premium

I can't gurantee this will all be done in a year, but these are the ones on horizon.

**Comment by volkanceylan** [comment]
@JohnRanger Core is already out of beta for about 6 months, there are customers that are using that in production

**Comment by JohnRanger** [comment]
Hi @volkanceylan ,

many thanks for your Feedback and the continuous effort you put into SF. Roadmap looks very interesting 👍 . Did not realize that Core was so Long out of beta (sorry for that).

With Kind regards,

John

**Comment by VR-Architect** [comment]
Would love to see an example of the Meeting module interfacing with Google Home / Google Assistant to schedule a meeting. 

Also would love to see a good open source diagramming widget added. For example, to show an org chart from Northwinds employee table.

BTW, my production code is .Net Core

**Comment by brunobola** [comment]
Excelente news @volkanceylan the product will be awesome with those features for sure  👍

**Comment by rcmsoftwaredevelopment** [comment]
Sorry to put you on the spot! All looking very rosy, I will be renewing my subscription when it is up!  Looking forward to the native mobile applications/integration.  How about a forum so people can put in what they like and the most votes takes priority maybe?

**Comment by rcmsoftwaredevelopment** [comment]
Closing for now.
