### ISSUE TITLE
Possible bug with MasterDetailRelation, FilterField and FilterValue

### ISSUE THREAD

**Issue by Wivison** [volkanceylan/Serenity#3056]
When I'm using the FilterField = "EndDate" and FilterValue = null in the MasterDetailRelation I can not update the entity by assigning a value to the EndDate field!

        [MasterDetailRelation(foreignKey: "ServiceId", FilterField = "EndDate", FilterValue = null)]
        [DisplayName("Service"), NotMapped]
        public List<ServiceRow> Services
        {
            get { return Fields.Services[this]; }
            set { Fields.Services[this] = value; }
        }

I've replicated the same situation in the Northwind examples:

        [DisplayName("Details"), MasterDetailRelation(foreignKey: "OrderID", FilterField = "Quantity", FilterValue = 1), NotMapped]
        public List<OrderDetailRow> DetailList
        {
            get { return Fields.DetailList[this]; }
            set { Fields.DetailList[this] = value; }
        }

I can not change the Quantity of 1 to another value and with it it disappears from the view after the update. If you remove the FilterField and the FilterValue the field assignment works normally.

I apologize if this behavior is normal and I did not quite understand the logic.

Well I would like to apply the filter in MasterDetail, but I can update the field and it disappear from the view.

Thank you in advance

**Comment by volkanceylan** [comment]
You are filtering detail records, e.g. the records that are bound to master record are only ones that matches filter. So that behavior is completely works as is.

**Comment by Wivison** [comment]
hi @volkanceylan,
The filter is working as it should. However, you can not change the value of the filtered field.
As I mentioned in the example, the Quantity field is filtering the detail records that has a value of 1.

![image](https://user-images.githubusercontent.com/1743256/34071894-a1ef6752-e25c-11e7-982e-8aeac6514402.png)

But when I try to edit the quantity field for another value, it does not update.
**Step 1: Editing the value**
![image](https://user-images.githubusercontent.com/1743256/34071899-c5ce7b9a-e25c-11e7-8fac-247ad0bae3ef.png)

**Step 2: Saving the change**
![image](https://user-images.githubusercontent.com/1743256/34071942-6fd10680-e25d-11e7-92b4-ba312ae4b554.png)

**Step 3: Re-accessing the registry... Did not update quantity.**
![image](https://user-images.githubusercontent.com/1743256/34071965-aef9934a-e25d-11e7-9422-74402bcb0616.png)

I understand it was to update the quantity and when I re-accessed the registry, it was not to load any detail records.

**Comment by volkanceylan** [comment]
You cant modify that filter column. That is not for filtering in UI.

**Comment by Wivison** [comment]
So how can I filter the detail records and still be able to modify the value of the column being used as a filter?
