### ISSUE TITLE
Inserting detail rows in Master Detail scenario

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#3057]
I am trying to insert some detail rows while saving the master row. I used the AfterSave() method to do so as such:

            ```
protected override void AfterSave()
            {
                base.AfterSave();

                foreach(PermitContractorRow pcr in Row.ContractorList)
                {
                    SaveRequest<PermitContractorRow> saveRequest = new SaveRequest<PermitContractorRow>();
                    saveRequest.Entity = pcr;
                    pcr.RequestId = Row.RequestId;
                    SaveResponse saveResponse = new PermitContractorRepository().Create(this.UnitOfWork, saveRequest);
                }
            }

```
Problem that I am experiencing is that for every item in Row.ContractorList, 2 rows are inserted. For example, if there is 1 item, 2 rows are inserted (I ensured that there is only 1 item).

Is this the proper way to handle this scenario? Any idea why I am getting duplicate rows created? Many thanks in advance.

**Comment by JohnRanger** [comment]
Hi @c9482 ,
I do similar Things with simple SQL insert into Statements and send them to the Detail table with:

```cs
SQLCommmand = "insert into <table> set field1=value1, field2=value2"
connection.execute(SQLCommand);
```
This works fine.

Of Course in the above example I do pull the table Name out of the dapper Entity Framework - also the field names.

With Kind regards,

John

**Comment by c9482** [comment]
Hi @JohnRanger ,

Thanks for your reply. So does that mean it will not work the way I am doing it (leveraging the framework to do the work rather than embedding SQL statements into the code)?

**Comment by JohnRanger** [comment]
Hi @c9482 ,

honestly - I don't know that @volkanceylan  could give here a definitive answer - but I showed you a possible way how to do it. 

So - depending on the time Frame in which you Need a solution - you either have to wait for a moe competent answer as mine :-) or you can implement my simple solution. Please note that my solution is tested only on MS SQL Backend (but should work also with other DB backends).

As I have more Knowhow in MS SQL than in the Serenity Framework (I am only an IT admin with some dev ambitions, no great dev qualities), I always fall back on direct SQL Manipulation when I am not able to solve a Problem within SF data Access within a reasonable time.

With Kind regards,

John

**Comment by c9482** [comment]
Hi @JohnRanger ,

I will keep your solution as a backup if I don't get any other suggestions. To me, all answers are competent if they solve the problem. Thanks again for your quick response.

**Comment by JohnRanger** [comment]
@c9482 ,

what happens if you put a breakpoint on your last line of Code:
```cs
SaveResponse saveResponse = new PermitContractorRepository().Create(this.UnitOfWork, saveRequest);
```
and then step once over it?

If you then check within your SQL table to which **PermitContractorRow** Points, are there immediately 2 added records or only one?


If the whole Thing is done with begin...end Transaction, then you will probably not see much immediately in your table. Then use the following:

As an alternative to find what SQL Statements are produced, you could also activate Debugging within web.config like this:

```XML
<configuration>
  <appSettings>
    ...
    <add key="Logging" value="{  File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0,  Level: 'Debug' }" />
	...
  </appSettings>
  ...
</configuration>
```

With that, log files are created within /App_Data/logs/ and you can see the SQL Statements which hit the SQL backend.

What do you see there when you put the breakpoint as described above and then step once over the last Statement?

With  Kind regards,

John

**Comment by c9482** [comment]
I get a database time out because it's in the middle of transaction.

**Comment by c9482** [comment]
It almost looks like 1st row is inserted by the SaveHandler and the duplicate is inserted somewhere else. The SaveHandler initializes the InsertUser and InsertDateTime columns:

![image](https://user-images.githubusercontent.com/17013052/34075275-59f80906-e287-11e7-9655-ddd0aebbe82b.png)

**Comment by c9482** [comment]
I figured it out. I did not need to explicitly insert the detail rows. Looks like the framework is smart enough to insert them for me because of the MasterDetailRelation attribute. The only thing is that it does not fire the SetInternalFields in PermitContractor SaveRequestHandler.

        ```
[DisplayName("Contractors"), MasterDetailRelation(foreignKey: "RequestId", IncludeColumns = "ContractorName,ContractorLicense"), NotMapped]
        public List<PermitContractorRow> ContractorList
        {
            get { return Fields.ContractorList[this]; }
            set { Fields.ContractorList[this] = value; }
        }

```
