### ISSUE TITLE
InplaceAdd behavior should always be "add" and never "edit"

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#3058]
When using the InplaceAdd = true decorator, the expectations is the UI button functions as an add. When I use the below decorators, it has these behaviors:

1. If Multiple = false and no value in the user interface's textbox - Behavior is add.
2. If Multiple = false and 1 value in the user interface's textbox - Behavior is edit. 
3. If Multiple = true and no value in the user interface's textbox - Behavior is add.
4. If Multiple = true and 1 value in the user interface's textbox - Behavior is edit.
5. If Multiple = true and 2+ values in the user interface's textbox - Behavior is error.

If behavior was always "add" then scenario 5 above would not result in an error. And the user would be able to add a new tag even though there are two already in the textbox. 

In addition, there is no InplaceEditPermission decorator to handle the edit behavior.

BTW, my many-to-many code is based upon the CustomerRow.cs in the StartSharp project and works as expect.

Example *Row.cs code:
```
        [DisplayName("Type"), ForeignKey("acct.AccountType", "AccountTypeId"), LeftJoin("jAccountTypeId_AccountType"), TextualField("AccountTypeId_AccountTypeLookup")]
        [LookupEditor(typeof(AccountTypeRow), InplaceAdd = true, InplaceAddPermission = PermissionKeys.AccountType.Insert)]
        public Int64? AccountTypeId
        {
            get { return Fields.AccountTypeId[this]; }
            set { Fields.AccountTypeId[this] = value; }
        }

        [LookupEditor(typeof(TagRow), Multiple = true, InplaceAdd = true, InplaceAddPermission = PermissionKeys.Tag.Insert), NotMapped]
        [LinkingSetRelation(typeof(Account2TagsRow), "AccountId", "TagId")]
        [MinSelectLevel(SelectLevel.Details), QuickFilter(CssClass = "hidden-xs")]
        public List<Int64> Account2TagsType
        {
            get { return Fields.Account2TagsType[this]; }
            set { Fields.Account2TagsType[this] = value; }
        }
```

**Comment by volkanceylan** [comment]
InplaceAdd is not designed for multiple, there is already another issue here

**Comment by volkanceylan** [comment]
This should resolve issue with multiple lookup editor and inplace add:

https://github.com/volkanceylan/Serenity/commit/5cc6de6b8dbb5719d60b083ce0164063f809d6d7

**Comment by AlperanQ** [comment]
This is resolved in latest version.
