### ISSUE TITLE
Code Generator Options for Editor files?

### ISSUE THREAD

**Issue by MayaBurns** [volkanceylan/Serenity#3059]
Hi all,

I was using code generator on a new table today on version 3.3.10 and it doesn't seem to create the editor and editor dialog anymore and there are no options to turn it on?  Can someone tell me how I can enabled this?

The previous code generator had GridEditor and GridEditorDialog and a few other options.

**Comment by volkanceylan** [comment]
They weren't official extensions, latest sergen supports custom files though, docs will be later
