### ISSUE TITLE
T4 template transformation not generating xxRow.IsActiveProperty for IsActive column

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#306]
If my table has an IsActive column (tried with bit and tinyint), after transforming the T4 template, it generates this on the grid.cs: IsActiveProperty(xxxRow.IsActiveProperty)]
except it never generated xxxRow.IsActiveProperty.

Doesn't appear tied to datatype (tried bit and tinyint) or NOT NULL. Is IsActive some kind of Serenity keyword that should be avoided in the db? Here's an example table script:

`CREATE TABLE [dbo].[xxx](
	[ID] [int] IDENTITY(1,1) NOT NULL,	
	[IsActive] [tinyint],
 CONSTRAINT [PK_xxx] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
`

**Comment by volkanceylan** [comment]
IsActiveProperty is only generated for rows implementing IIsActiveRow interface. Does your implement this?

**Comment by wldkrd1** [comment]
No, here's the class signature: 
`public sealed class ReviewerRow : Row, IIdRow, INameRow`

The table it was generated from has an IsActive column though.

**Comment by volkanceylan** [comment]
So use a Int16 field in row and implement IIsActiveRow if you want it to generate IsActiveProperty.

**Comment by wldkrd1** [comment]
So I guess the bug is that it added the reference to the property on grid.cs which doesn't exist. But I'm curious as to what IsActive means in the context of Serenity. Why would I want to implement IIsActiveRow? What does that do? I don't see a reference to it in the developer guide.

**Comment by volkanceylan** [comment]
It allows grid to show inactive records as gray. If you don't need this or want to implement manually no need. Actually row should be generated with IIsActiveRow interface in your case but somehow its missing from the row template in code generator. This is probably a bug that i should have a look at.

**Comment by wldkrd1** [comment]
Good to know, and that sounds very useful. I'll go ahead and implement it :+1:

**Comment by swordz36** [comment]
Yes, I experienced the same issue, I have to remove the attribute from the Service Contract class when I transform the templates.

**Comment by volkanceylan** [comment]
I decided, sergen shouldn't try to determine IIsActiveRow and it no longer adds IsActiveProperty to dialog / grid. If somebody wants it, can add interface manually.

b8c7967f3427ca4bfd58965446557e5081b08571
