### ISSUE TITLE
FYI for future version

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#3060]
FYI, getting this warning in Chrome console. Happens when clicking an item in a row of a *Row.cs file and the *Form.cs pops up. 

`pace.js?v=evfXQgyADGar15z3wQSTJA:434 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by volkanceylan** [comment]
That is a warning i'm aware of, nothing to worry about, lookups are loaded synchronously by default, would make them async but it would break many things, tried that before
