### ISSUE TITLE
Creating Lists from views or stored procedures

### ISSUE THREAD

**Issue by paulmrozowski** [volkanceylan/Serenity#3061]
A common pattern we use in our applications is to allow the user to interact with a list of data that is generated either via a stored procedure, a view, or sometimes dynamically generated SQL. An edit screen isn't always needed (sometimes we just link to other pages). Kind of a simple "report" with filters and the ability to export them. Is there a way to build the files by using the sergen utility? I know we could generate something from the "primary" table, but then we're left with manually adding a bunch of columns. 

(thinking out loud). What would really be nice is if it could just build the classes but then stuck a TODO or threw an exception in the places where we would need to hook in our code to call our stored procs. That would help a bit with discoverability since stored procs for sure would require us to create our own ListHandler.

**Comment by brunobola** [comment]
@paulmrozowski agree with your suggestion nevertheless the docs, the wiki and the support issues (staf) are becoming really good :)

**Comment by volkanceylan** [comment]
There is not enough metadata information for stored procs, nor they support features required by list, update etc. handlers. I usually avoid them unless there is a strong reason to use. I agree it would be a nice to have, but don't have any plans atm.
