### ISSUE TITLE
Example of using Common/Reporting

### ISSUE THREAD

**Issue by paulmrozowski** [volkanceylan/Serenity#3062]
Are there any examples or docs on the Modules/Common/Reporting code?

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Northwind/Order for order detailsreport

**Comment by paulmrozowski** [comment]
Thanks, but maybe I should have been more specific. There is a ReportController and ReportPage.cshtml that looks like it can generate a nested grouping of reports under different categories. That's actually the part I was referring to.

**Comment by AlperanQ** [comment]
Have a look at files ending with Report.cs and you will notice that they have a category attiribute which controls location of report in navigation.
