### ISSUE TITLE
TemplatedDialog  invokes setupPanelTitle after onDialogOpen?

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#3064]
It seems that **TemplatedDialog** has a private method **setupPanelTitle** which is invoked after **onDialogOpen**.
**setupPanelTitle**  is used for creating panel dialog title and close button, It works really well most of time.

but sometimes I find I need to invoke **layout** or something similar after **setupPanelTitle**,
for example, slick grid's horizental scrollbar disappears because its canvas's height is fixed and I use flex layout, which means I need to invoke its **resizeCanvas** method after **setupPanelTitle**.
So I wonder if you could whether
1.  invoke **onDialogOpen** after **setupPanelTitle**, or
2.  makes **setupPanelTitle** protected ,then I can override it.

**Comment by volkanceylan** [comment]
You can override that method. I should call arrange after setting panel title first time probably as well.
