### ISSUE TITLE
Retrieve response error learning to debug in Chrome.

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#3066]
![image](https://user-images.githubusercontent.com/27406433/34103055-439a024c-e3e3-11e7-82f6-c3db7deb726b.png)
How to include the list of notes in the cases row, just like in Northwinds>>Customer>>Notes.
Defined in the TblCaseDetails row as:-
 //wrong probably

        [NotesEditorAttribute, NotMapped]
        public List<TblCaseNotesRow> NoteList
        {
            get { return Fields.NoteList[this]; }
            set { Fields.NoteList[this] = value; }
        }

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/34105697-6db97a76-e406-11e7-8ccd-2300380128f9.png)

**Comment by judejay** [comment]
The result is the same.  It's not getting that far before it errors. On the VS debug,
it goes and tries to find a Serenity file, retrieverequesthandler.cs . Think it's wired up wrong here at the controller, it goes  TblCaseDetailsEndpoint.cs 

public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRepository().Retrieve(connection, request);
        }


then TblCaseDetailsRepository.cs

  public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }
then errors.

**Comment by judejay** [comment]
![myretrieveresponse](https://user-images.githubusercontent.com/27406433/34107185-2a313d38-e3f3-11e7-8243-6e232bd94566.PNG)

**Comment by judejay** [comment]
public Field Target { get; set; }

        public bool ActivateFor(Row row)
        {
            if (ReferenceEquals(null, Target))
                return false;

            var attr = Target.GetAttribute<TblCaseNotesEditorAttribute>();
            if (attr == null)
                return false;

            if (Target.ValueType != typeof(List<TblCaseNotesRow>))
            {
                throw new ArgumentException(String.Format("Field '{0}' in row type '{1}' has a TblCaseNotesEditorAttribute " +
                    "but its property type is not a List<TblCaseNotesRow>!",
                    Target.PropertyName ?? Target.Name, row.GetType().FullName));
            }

            return true;
        }
![noexistingnotes](https://user-images.githubusercontent.com/27406433/34107942-fe894e16-e3f5-11e7-8347-64311a1d4c30.PNG)

**Comment by judejay** [comment]
I done this eventually, if anyone is interested it's in the Movie tutorial , thanks guys, Happy New Year!

![casenotesintab](https://user-images.githubusercontent.com/27406433/34441994-23bd01b8-ecb7-11e7-8c8e-cfe2a333c559.PNG)
