### ISSUE TITLE
Help needed to build UI grid

### ISSUE THREAD

**Issue by gpraveenraj** [volkanceylan/Serenity#3067]
Hi All,

We are using the Serenity, your framework is great. And we are looking for an option to design such a page below. Can you suggest how it can be done?

Basically we would like to build a grid to allow user to enter multivalue data as per each slot.

![image](https://user-images.githubusercontent.com/28450286/34109900-0791c558-e42b-11e7-8aa6-e80ac90378f6.png)

For ex, 2-4am slot, Mon-Fri, user entered value 1

**Comment by brunobola** [comment]
Check this samples https://github.com/mleibman/SlickGrid/wiki/Examples and see if it helps.

**Comment by gpraveenraj** [comment]
Thank you . We will check.

**Comment by gpraveenraj** [comment]
Thank you brunobola. Great response.

**Comment by AlperanQ** [comment]
Close due to inactivity.
