### ISSUE TITLE
Handling Long Forms

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#307]
dont know how easy to span one form into several tabs , it would be a nice something to have like the same way lie custom editors [Tab=""tabename ]

and what is the best way to do this

**Comment by volkanceylan** [comment]
use categories not tabs

**Comment by zerodev** [comment]
am trying to follow northwind customer forms to do this any special directions or should i add categories for that , and is it possible to do what i have in mind

**Comment by volkanceylan** [comment]
category titles are clickable and navigatable, not very different than tabs

**Comment by zerodev** [comment]
just tried them they are great will do for now, but let me now if you have thoughts for spanning them into tabs

**Comment by volkanceylan** [comment]
You can do like i moved Notes editor in customer dialog into a tab.

But, i usually find tabs to be confusing. Considering expandable categories instead.

**Comment by zerodev** [comment]
i tried the categories but whats expandable catigories
