### ISSUE TITLE
Serenity.Services.ValidationError: '2017-12-20 is not a valid field name!'

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#3070]
i have **date** column with **varchar(8)** and data like 12122017etc
and in the grid i showed it as 12/12/2017 using query and i applied # date quikfilter on date column and when am performing filterting using the datequickfilter it shows 
 Serenity.Services.ValidationError: '2017-12-20 is not a valid field name!' how to overcome and how to perfoem filtering i.e when am selecting date from the datequickfilter the grid has filter based on that date

**Comment by brunobola** [comment]
T4 transform templates and rebuild !

**Comment by rajashekargoka** [comment]
@brunobola  it's not working showing same errror.

**Comment by volkanceylan** [comment]
You can't use varchar column as date, use proper date.
