### ISSUE TITLE
Invalid column name 'UserId'.

### ISSUE THREAD

**Issue by Itsathere** [volkanceylan/Serenity#3071]
> var u = UserRow.Fields;
                var ur = UserRoleRow.Fields.As("ur");
                var r = RoleRow.Fields.As("r");
                query.Select(r.RoleName, ur.RoleId)
                    .LeftJoin(ur, ur.UserId == u.UserId)
                    .LeftJoin(r, r.RoleId == ur.RoleId)
                    .Where(u.UserId == 1);
I need to check user role that's why i have written this query in PrepareQuery and getting exception 
**Invalid column name 'UserId'.**

**Comment by brunobola** [comment]
Make sure you got:

...in UserRoleRow..
`        [DisplayName("User Id"), NotNull, ForeignKey("Users", "UserId"), LeftJoin("jUser"), LookupInclude]
        public Int32? UserId
        {
            get { return Fields.UserId[this]; }
            set { Fields.UserId[this] = value; }
        }`

**Comment by Itsathere** [comment]
That's great. But how will I read query values everywhere in repository methods.

**Comment by JohnRanger** [comment]
Hi @Itsathere ,

why don't you create a view within SQL Server which contains all required rows and use that?

I do this often when it gets too complex within Dapper.

With Kind regards,

John

**Comment by Itsathere** [comment]
Hello @JohnRanger 
After view creation how will I use that in serenity project. How will I call view and retrive data from view?

**Comment by volkanceylan** [comment]
There are some view samples in demo.
