### ISSUE TITLE
How to apply multiple condition in connection.Count<EntityTpe>(Condtion1 Condition2)

### ISSUE THREAD

**Issue by RahulShete01** [volkanceylan/Serenity#3079]
Hi,  I very new in serenity. Need help to apply multiple condition in connection.Count<EntityType>. Below is my code.

**var conn = SqlConnections.NewByKey("DatabaseName")
conn.Count<EntityType>(Condition1  Condition2);**

 Please help. and Thank in advance.

**Comment by JoelLapointe86** [comment]
You can add multiple criteria inside the Count( ) method.
Such as 
```
Count(
new Criteria("Month") > 5 &
new Criteria("Year") < 4 &
new Criteria("Name").Contains("a")
)
```

see:
https://volkanceylan.gitbooks.io/serenity-guide/fluent_sql/criteria_objects.html
