### ISSUE TITLE
How to execute/run table's join query in serenity

### ISSUE THREAD

**Issue by Itsathere** [volkanceylan/Serenity#3083]
- var u = UserRow.Fields;
                var ur = UserRoleRow.Fields.As("ur");
                var r = RoleRow.Fields.As("r");
                query.Select(r.RoleName, ur.RoleId)
                    .LeftJoin(ur, ur.UserId == u.UserId)
                    .LeftJoin(r, r.RoleId == ur.RoleId)
                    .Where(u.UserId == Convert.ToInt32(1));

How to run this query in ..repository.cs and read the results anywhere in the repository methods. As I have seen query run inside below method
`private class MyListHandler : ListRequestHandler<MyRow>` 
` {` 
`protected override void PrepareQuery(SqlQuery query)`
`{`
                `base.PrepareQuery(query);`
`var u = UserRow.Fields;`
               ` var ur = UserRoleRow.Fields.As("ur");`
                `var r = RoleRow.Fields.As("r");`
                `query.Select(r.RoleName, ur.RoleId)`
                   ` .LeftJoin(ur, ur.UserId == u.UserId)`
                   ` .LeftJoin(r, r.RoleId == ur.RoleId)`
                   ` .Where(u.UserId == Convert.ToInt32(1));`
`}`
` }` 
but when I run this query I got exception **Invalid column name 'UserId'.**. I am new to query in serenity. So, I need a suggestion.

I have tried another way to run the same query by inline query by below code snippet

`string sql = string.Format("select UR.RoleId,R.RoleName from dbo.[Users] U left join dbo.[UserRoles] UR on UR.UserId=U.UserId left join dbo.Roles R on R.RoleId=UR.RoleId where U.UserId={0}", 1); `
`var items = uow.Connection.Query(sql);`

I am getting result but I am unable to read that values. You can see the result in attached image
![image](https://user-images.githubusercontent.com/16954075/34245407-c0576cf2-e64f-11e7-968c-780bbba23bf5.png)

if you have provided `uow.Connection.Query(query)` then there must be a way to access data from this result. So, can you kindly suggest me to read data from `.Query` method.

**Comment by brunobola** [comment]
Maybe something like this: 

` var rep = new XYZRepository();
    var request = new RetrieveRequest() { EntityId = this.Id };
    RetrieveResponse<MyRow> resp = rep.Retrieve(connection, request);

    resp.Entity.listOfYourRelatedTable ...`


See issue: https://github.com/volkanceylan/Serenity/issues/2247

**Comment by Itsathere** [comment]
Hello @brunobola 
What if table is not related to each other
Suppose I have table 
**User with fields Id, Name, Email, Password etc
UserRole with fields UserRoleId, UserId and RoleId
Role with fields RoleId, RoleName and TenantId**

Now, I need **current user role** in table named **bug** which is unrelated table and have no field defined in current row then how will I able to retrive data in mentioned way.

**Comment by volkanceylan** [comment]
Add required fields to your row as join / expression, see mapping guide.

**Comment by Itsathere** [comment]
I still have doubts about topic. What about the dynamic parameter **UserId** . I have done mapping but how will I send dynamic parameter UserId in mapping. I have created mapping like below

`[ForeignKey("Users", "UserId"), LeftJoin("u")]
        public Int32? UserId
        {
            get { return Fields.UserId[this]; }
            set { Fields.UserId[this] = value; }
        }

        [Expression("u.UserId"),ForeignKey("UserRoles", "UserId"), LeftJoin("ur")]
        public Int32? UserRoleId
        {
            get { return Fields.UserRoleId[this]; }
            set { Fields.UserRoleId[this] = value; }
        }

        [Expression("ur.RoleId"), ForeignKey("RoleId", "RoleId"), LeftJoin("r")]
        public Int32? RoleId
        {
            get { return Fields.RoleId[this]; }
            set { Fields.RoleId[this] = value; }
        }

        [Expression("r.RoleName")]
        public String RoleName
        {
            get { return Fields.RoleName[this]; }
            set { Fields.RoleName[this] = value; }
        }`

My sql query was `select UR.RoleId,R.RoleName from dbo.[Users] U left join dbo.[UserRoles] UR on UR.UserId=U.UserId left join dbo.Roles R on R.RoleId=UR.RoleId where U.UserId=**@UserId**`

**Can you explain that or I need to create new issue.**

**Comment by mjacoup** [comment]
???
