### ISSUE TITLE
Grid header filter

### ISSUE THREAD

**Issue by Febriantos** [volkanceylan/Serenity#3085]
Is there anyone implement this kind of filter ?
https://mleibman.github.io/SlickGrid/examples/example-header-row.html
https://github.com/mleibman/SlickGrid/blob/master/examples/example-header-row.html

**Comment by brunobola** [comment]
Serenity has samples of:
-> Quick Filter (http://serenity.is/demo/BasicSamples/QuickFilterCustomization/)
-> Custom Filter (http://serenity.is/demo/BasicSamples/CustomLinksInGrid/)

(more samples....)

**Comment by Febriantos** [comment]
I'm looking something like this:
[IMG]http://i63.tinypic.com/2aanfgl.png[/IMG]
http://oi63.tinypic.com/2aanfgl.jpg

**Comment by volkanceylan** [comment]
Nice sample, thanks for sharing

**Comment by Febriantos** [comment]
I found this:
https://ghiscoding.github.io/Angular-Slickgrid
https://github.com/ghiscoding/Angular-Slickgrid
