### ISSUE TITLE
No data being returned to grid

### ISSUE THREAD

**Issue by paulmrozowski** [volkanceylan/Serenity#3089]
I built a page based on the Stored Procedure Grid example. The page does a callback to the endpoint, which calls the repo's List method, which runs the query based on the filters (and there IS data) but no data is returned back to the page. More specifically, it returns an empty JSON structure:

```Javascript
{"Entities":[{},{},{}],"TotalCount":0,"Skip":0,"Take":0}
```
Additionally, the title immediately above the search button shows most of the full path to the report, ex. "Reports.Sales.SalesByAgent.SalesByAgent", but the title in the page shows the correct title (the [Description] attribute on the Row itself). I don't know if the two issues are connected or not.

I've compared and re-compared the example and my code, but I'm missing something (and that could even be some convention in naming I'm missing). Maybe something isn't getting cast correctly as that would explain why I'm seeing the exact number of records being returned as empty items (so in the above result, I was trying to return 3 records), but I'm not sure what I should be looking at besides the repo. I also thought it could be a permission issue, so I explicitly create a ReadPermission and assigned it to the user (admin).

In my ListResponse<MyRow> List method, these lines of code DO have values set/data in them:

```C#
var response = new ListResponse<MyRow>();
response.Entities = (List<MyRow>)data;
return response;
```
Here's what the defined "MyRow" looks like:

```C#
    [ConnectionKey("Default")]
    [DisplayName("Sales by Agent"), InstanceName("Sales by Agent Report")]
    [ReadPermission("Reports:SalesByAgent")]
    public class SalesByAgentRow : Row, INameRow
    {
        public DateTime AddedOn { get; set; }

        [DisplayName("Phone #")]
        public string PhoneNum { get; set; }

        [DisplayName("Description")]
        public string ItemDesc { get; set; }

        [DisplayName("Inv. Amount")]
        public decimal? Amount { get; set; }

        public decimal? Paid { get; set; }

        [DisplayName("Agent"), QuickSearch]
        public string UserName { get; set; }

        [DisplayName("ISO"), QuickSearch]
        public string DealerName { get; set; }

        public StringField NameField
        {
            get { return Fields.UserName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();
        public SalesByAgentRow() : base(Fields) { }

        public class RowFields : RowFieldsBase
        {
            public DateTimeField AddedOn;
            public StringField PhoneNum;
            public StringField ItemDesc;
            public DecimalField Amount;
            public DecimalField Paid;
            public StringField UserName;
            public StringField DealerName;

            public RowFields() : base()
            {
                LocalTextPrefix = "";
            }
        }
    }
```

The endpoint looks like this:
```C#
    [RoutePrefix("Services/Reports/Sales/SalesByAgent"), Route("{action}")]
    [ConnectionKey(typeof(MyRow)), ServiceAuthorize(typeof(MyRow))]
    public class SalesByAgentEndpointController : ServiceEndpoint
    {        
        [HttpPost]
        public ListResponse<MyRow> List(IDbConnection connection, SalesByAgentListRequest request)
        {
            return new MyRepository().List(connection, request);
        }
```

**Comment by brunobola** [comment]
Are the permissions ok ?
Have you done T4 then rebuild then check console for erros ?
Have you done a SQL profiler to see what happens behind ?

**Comment by paulmrozowski** [comment]
Yes, I have permission to the page. 
Yes, I rebuilt the generated files.
No, no need. The query definitely runs correctly as I see data being returned in the debugger.

**Comment by volkanceylan** [comment]
If data is returned from query in debugger from repository and it returns no records back to client as json that doesnt make much sense. Otherwise id say check query and ID property

**Comment by paulmrozowski** [comment]
This turned out to be total code-blindness. Take a look at the property definitions for the Row. They are simple get;set instead of using the Fields.

ex.

```c#
[DisplayName("Phone #")]
public string PhoneNum
{
    get { return Fields.AddedOn[this]; }
    set { Fields.AddedOn[this] = value; }
}
```

Fixing that mostly fixed the table.
