### ISSUE TITLE
Database timeout during repository create method call

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#3090]
I am experiencing a database timeout during repository create operation. My assumption was that once the main record is created, I can use AfterSave to insert any additional records because the main record is already committed. Unfortunately, it is not working the way I expected. The execution hangs when I try to select from the same table in AfterSave:
```
public SaveResponse CreateFromRequest(IUnitOfWork uow, PermitSaveRequest<MyRow> request)
        {
            return new MyPermitSaveHandler().Process(uow, request, SaveRequestType.Create);
        }
.......
protected override void AfterSave() <-- from my save handler
            {
                base.AfterSave();

                IDbConnection connection = SqlConnections.NewByKey("Default");

                using (var uow = new UnitOfWork(connection))
                {
                    string key = "Default.Permit";
                    string opt = "{\"RequestId\":" + Row.RequestId + "}";
                    var reportInfo = ReportRegistry.GetReport(key);

                    var report = (IReport) JsonConvert.DeserializeObject(opt.TrimToNull() ?? "{}",
                        reportInfo.Type, JsonSettings.Tolerant);

                    byte[] bytes = new ReportController().RenderAsPdf(report, key, opt,
                        ((PermitSaveRequest<MyRow>) this.Request).Ctxt);

                    SaveRequest<AttachmentRow> sra = new SaveRequest<AttachmentRow>();
                    AttachmentRow ar = new AttachmentRow
                    {
                        RequestId = Row.RequestId,
                        AttachmentBytes = new MemoryStream(bytes),
                        Type = "PERMIT",
                        Size = bytes.Length,
                        MimeType = "application/pdf",
                        FileName = Row.RequestId + "-PERMIT.pdf",
                        Description = "Permit"
                    };
                    sra.Entity = ar;
                    SaveResponse sva = new AttachmentRepository().Create(uow, sra);
                    uow.Commit();
                }
            }
......
        public object GetData() <--- from my IReport class
        {
            var data = new PermitReportData();

            if(this.RequestId <= 0) throw new ArgumentException("Missing request id");

            using (var connection = SqlConnections.NewFor<PermitRow>())
            {
                var o = PermitRow.Fields;

                data.Permit = connection.TryById<PermitRow>(this.RequestId, q => q
                     .SelectTableFields()) ?? new PermitRow();

                var od = PermitContractorRow.Fields;
                data.Contractors = connection.List<PermitContractorRow>(q => q
                    .SelectTableFields()
                    .Select(od.ContractorName)
                    .Select(od.ContractorLicense)
                    .Where(od.RequestId == this.RequestId));
            }

            return data;
        }
```
I must not be understanding how the transaction control works within the framework. Many thanks in advance for your help.

**Comment by volkanceylan** [comment]
You shouldn't create a transaction within a handler, e.g. there is already a transaction there. Use this.UnitOfWork, this.Connection

**Comment by teafmartins** [comment]
Hi,  @c9482 , did you find any solution to generate pdf inside AfterSave() ? 
I need to generate pdf after save record. 
Thx

**Comment by c9482** [comment]
Yes, in the ReportController, I ended up injecting database connection into the IReport.GetData():

`    public interface IDbReport : IReport
    {
        object GetData(IDbConnection connection);
    }
`

`        private ActionResult RenderAsHtml(IReport report, bool download, bool printing,
            ref byte[] renderedBytes)
        {
            var designAttr = report.GetType().GetAttribute<ReportDesignAttribute>();

            if (designAttr == null)
                throw new Exception(String.Format("Report design attribute for type '{0}' is not found!",
                    report.GetType().FullName));

            var dbReport = report as IDbReport;
            var data = dbReport != null ? dbReport.GetData(_connection) : report.GetData();

            var viewData = download ? new ViewDataDictionary(data) : ViewData;

            var iadditional = report as IReportWithAdditionalData;
            if (iadditional == null)
                viewData["AdditionalData"] = new Dictionary<string, object>();
            else
                viewData["AdditionalData"] = iadditional.GetAdditionalData();

            viewData["Printing"] = printing;

            if (!download)
                return View(viewName: designAttr.Design, model: data);

            var html = TemplateHelper.RenderViewToString(designAttr.Design, viewData);
            renderedBytes = Encoding.UTF8.GetBytes(html);
            return null;
        }
`

**Comment by teafmartins** [comment]
Thank You.
End up doing this way:

				...
                string key = "YourReportkey";

                string opt = "{\"Id\":223044}";
                var reportInfo = ReportRegistry.GetReport(key);

                var report = (IReport)JsonConvert.DeserializeObject(opt.TrimToNull() ?? "{}",
                    reportInfo.Type, JsonSettings.Tolerant);

                byte[] renderedBytes = null;
                renderedBytes = new ReportController().RenderAsPdf(report, key, opt);
                System.IO.File.WriteAllBytes(@"youfolder\rpr.pdf", renderedBytes);
				...

**Comment by teafmartins** [comment]
@c9482 , if I replace ID 223044 with ID variable I also get time out issue... know why?
thanks

**Comment by c9482** [comment]
I use a dictionary to pass parameters:

            var reportOptions = new Dictionary<string, string>
                    {
                        { "ReceiptId", request.EntityId.ToString() },
                        { "Multipart", "no" }
                    };

... and then do something like this:

        public static byte[] ReportAsPdf(IDbConnection connection, string reportKey, Dictionary<string, string> reportOptions)
        {
            var reportInfo = ReportRegistry.GetReport(reportKey);
            var opt = JsonConvert.SerializeObject(reportOptions);
            var report = (IReport)JsonConvert.DeserializeObject(opt.TrimToNull() ?? "{}",
                reportInfo.Type, JsonSettings.Tolerant);

            return new ReportController(connection).RenderAsPdf(report, reportKey, opt);
        }

**Comment by teafmartins** [comment]
@c9482 
Now using Dictionary opt is with correct values... but I'm getting time out in GetData(). Do you known why?

**Comment by c9482** [comment]
Not sure. I did show you my code.

**Comment by teafmartins** [comment]
I end up doing an endpoint to generate pdf instead aftersave.
Thanks for your time.
