### ISSUE TITLE
Group management & GUI 

### ISSUE THREAD

**Issue by papyr** [volkanceylan/Serenity#3092]
Hi, can I request the addition of [group management](http://johnatten.com/2014/08/10/asp-net-identity-2-0-implementing-group-based-permissions-management/) or core version.

Also the _Master Details grid samples with approval button on each row_ is missing, any chance you add a sample, for e.g. document approval in the master grid row, with document details and versions in the child grid.

thanks

**Comment by volkanceylan** [comment]
Sorry, not accepting requests here.
