### ISSUE TITLE
C# native objects & graph as DB

### ISSUE THREAD

**Issue by papyr** [volkanceylan/Serenity#3093]
Hell, this is a feature request for

- [ ] C# [native graph/objects as the DB](https://github.com/mbdavid/LiteDB), its great with strong following and free. LiteDB, I am sure their users will flow here to use Serenity too :)
- [ ] Tenant Resolver/Multi-tenancy:  [sample](https://github.com/aspnetboilerplate/aspnetboilerplate/tree/cae84a2c7b259beb00b478b81e2c64bc0096023d/src/Abp/MultiTenancy) any chance we can get tenant resolver.
- [ ] Theme color [switcher in user profile](https://github.com/camsjams/jquery-style-switcher)
- [ ] Lastly, an architectural picture/developer guide picture only showing how to implement/extend for our specific LOB

thanks

**Comment by JohnRanger** [comment]
Hi @papyr ,

the 1st two I agree.

The last two Sound more like a Christmas wish list - especially the last one - except your Company is contracting Volkan:-)

With Kind regards,

John

**Comment by volkanceylan** [comment]
Thanks for suggestions.

**Comment by papyr** [comment]
Hi @JohnRanger With bootstrap there should be no reason we cant leverage that. Not sure how this is a wishlist, theming is now very integral to all web solutions. 
A picture is a basic need for the dev. community, it would help increase traction and users of Serenity.
