### ISSUE TITLE
Having a Q.confirm but wanting to display the yellow warning triangle from the Q.warning dialog

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3098]
Hi all,

back in Saltarelle, we could do this easy Thing: #160 .

I have tried to convert this over to Typescript - but without success.
Also there is no example within Serene how to use / set Q.confirmOptions.

I have tried it like this:

```ts
let bla = new Q.ConfirmOptions { dialogClass ="s-MessageDialog s-WarningDialog"};
```

...but I get: ConfirmOptions does not exists on TypeOf Q. when I type Q. then ConfirmOptions is shown - so I don't understand why I can't use Q.ConfirmOptions.

I looked at the Definition of confirmOptions but didn't find a way how to set the style of the confirm Dialog.

**Question:**

How can the appearance of the Q.confirm Dialog be changed to the appearance of the Q.warning Dialog but still providing the possibility to give the user multiple buttons to choose?

**SF Version:**
2.9.24.

Thanks for your help and 

with Kind regards,

John

**Comment by JohnRanger** [comment]
As a reference for those running into the same Problem:

I was not able to generate a variable of type Q.ConfirmOptions but the Problem can be solved by using the following Syntax of Q.confirm:

```ts
Q.confirm(
                "Click one of buttons, or close dialog with [x] on top right, i'll tell you what you did!",
                () => {
                    Q.notifySuccess("You clicked YES. Great!");
                },
                {
                    onNo: () => {
                        Q.notifyInfo("You clicked NO. Why?");
                    },
                    onCancel: () => {
                        Q.notifyError("You clicked X. Operation is cancelled. Will try again?");
                    },
                    dialogClass : 's-MessageDialog s-WarningDialog'
                });
```

Note the added stuff:
```ts
                    ,
                    dialogClass : 's-MessageDialog s-WarningDialog'
```

Hope this helps somebody.

With Kind regards,

John

**Comment by dfaruque** [comment]
Thanks @JohnRanger
