### ISSUE TITLE
Double-leftjoined field causes (only) error when used in DeliveryRepository.cs; The multi-part identifier "jDataImport.Delivery_ID" could not be bound.

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#310]
Hi JaiQ,

John Ranger here with a "strange" Problem :-)

I have a ClientsRow.cs which has (among others) the two fields declared like this:

```cs
[DisplayName("Db.Clients.Clients.DataImportId"), Column("DataImport_ID"), NotNull, ForeignKey("DataImport_Clients", "DataImport_Clients_ID"), LeftJoin("jDataImport"),QuickSearch]
        [LookupEditor("Delivery.DataImport_Clients")]
        public Int32? DataImportId
        {
            get { return Fields.DataImportId[this]; }
            set { Fields.DataImportId[this] = value; }
        }

[DisplayName("Data Import Delivery Id"), Expression("jDataImport.[Delivery_ID]"), ForeignKey("Deliveries", "Delivery_ID"), LeftJoin("jDelivery"), LookupInclude]
        [LookupEditor("Delivery.Delivery")]
        public Int32? DataImportDeliveryId
        {
            get { return Fields.DataImportDeliveryId[this]; }
            set { Fields.DataImportDeliveryId[this] = value; }
        }

```

I am using this "cascaded" leftjoin to get innerjoined fields from the DataImport_Clients as well as from the Deliveries table.

This works very well within the clientsColums.cs / ClientsGrid.cs.

But...

I now want to use this also in the DeliveryRepository.cs where I want in the AfterSave() Event to bulk update all associated Clients with some initial values from the Deliveries table.

I get the following error which I don't understand where it Comes from: The multi-part identifier "jDataImport.Delivery_ID" could not be bound.

--> I see that this is logged in the error console as a sqlexception (but I don't get the Details because the exception is catched and then displayed directly in the serenity GUI. So it seems that Serenity is somehow passing this string directly down to the SQL database instead of resolving it to the correct SQL Statement.

The ClientsRow.cs file is the only place in the whole Project where this string is defined.

In the DeliveryRepository.cs, I have the following code:

```cs

...
using Clients = Clients.Entities.ClientsRow;
using PeripheryAssets = PeripheryAssets.Entities.PeripheryAssetsRow;
...
            protected override void AfterSave()
            {
                base.AfterSave();

                // *** Update fields in all associated clients ***

                var CurrentDeliveryID = Row.DeliveryId.Value;

                var clients = new Clients();
                var update_Clients = new SqlUpdate(clients.Table.ToString());

                var peripheryAssets = new PeripheryAssets();
                var update_PeripheryAssets = new SqlUpdate(peripheryAssets.Table.ToString());


                // *** Also reset individually set Costcenter, LifeCycle status and Location settings on clients and periphery assets back to what is defined within delivery ***
                if (Row.UpdateInitialValuesOnAllAssociatedAssets == true)
                {

                    // *** Update all associated clients (there may be none if the delivery has only periphery assets) ***
                    update_Clients.Set(Clients.Fields.Costcenter_ID, Row.Costcenter_ID);
                    update_Clients.Set(Clients.Fields.LifeCycle_Status_ID, Row.LifeCycleStatusId);
                    update_Clients.Set(Clients.Fields.Location_ID, Row.LocationId);

                    // *** Update all associated periphery assets (there may be none if the delivery has only clients) ***
                    update_PeripheryAssets.Set(PeripheryAssets.Fields.CostcenterId, Row.Costcenter_ID);
                    update_PeripheryAssets.Set(PeripheryAssets.Fields.LifeCycleStatusId, Row.LifeCycleStatusId);
                    update_PeripheryAssets.Set(PeripheryAssets.Fields.LocationId, Row.LocationId);

                }

                // *** In all delivery update cases, set the associated clients and/or periphery assets to be synched with SCSM ***


                // *** Clients *** 
                update_Clients.Set(Clients.Fields.SCSM_Sync_Required, true);
                update_Clients.Where((Clients.Fields.DataImportDeliveryId == Row.DeliveryId.ToString())); //& (Clients.Fields.StatusScsmUpdateId != 0));
                update_Clients.Execute(Connection, ExpectedRows.Ignore);

                // *** PeripheryAssets ***
                update_PeripheryAssets.Set(PeripheryAssets.Fields.ScsmSyncRequired, true);
                update_PeripheryAssets.Where((PeripheryAssets.Fields.DataImportPeripheryAssetsDeliveryId == Row.DeliveryId.ToString())); //& (PeripheryAssets.Fields.StatusScsmUpdateId != 0));
                update_PeripheryAssets.Execute(Connection, ExpectedRows.Ignore);

```
The exception is thrown when executing the 
```cs 
update_Clients.Execute(Connection, ExpectedRows.Ignore);
```

The SQL table of DataImport_Clients Looks like this:

```SQL

CREATE TABLE [dbo].[DataImport_Clients](
	[DataImport_Clients_ID] [int] IDENTITY(1,1) NOT NULL,
	[Delivery_ID] [int] NOT NULL,
	[TimeStamp_Import] [datetime] NULL,
	[Status_CSVImport_ID] [int] NULL CONSTRAINT [DF_DataImport_Status_CSVImport_ID]  DEFAULT ((0)),
	[CSV_Data_Import_Status_Info] [nvarchar](max) NULL,
	[CSV_Delimiter_ID] [int] NOT NULL,
	[CSV_Content] [nvarchar](max) NOT NULL,
	[Remarks] [nvarchar](max) NULL,
 CONSTRAINT [PK_DataImport] PRIMARY KEY CLUSTERED 
(
	[DataImport_Clients_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
```

I believe that the Problem is somewhere in the "Where" clause as there I want to use the DataImportDeliveryId which is one of the innerjoined fields (altough only 1 innerjoin away from the Clients table).

I also had Problems to do a simple 
```cs
update_Clients.Where((Clients.Fields.DataImportDeliveryId == Row.DeliveryId));
```
because visual Studio was complaining that I could not compare an INT32Field with an int? with the "==" comparator. Interestingly, It accepted the ".ToString() on the right side of the "==".

I could not cast the Int32field to int - nothing was accepted, except the toString() method.

Do you have any idea what could be wrong? Am I at all allowed to double-innerjoin as I did?

Thanks again for you Support and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Hello John, could only have a fast look but i guess problem is you are trying to use joins with UPDATE which you know doesnt work with standard. It only could be used with UPDATE FROM if i remember right. Can't you write your WHERE condition using a subquery like WHERE x in (select id from ....)

You should use .Value when building criteria as criteria objects doesnt have overload for nullables.

If you re using vs2015 new diag tools shows SQL. Also its possible to set breakpoint just before update executed and check its DebugText propery.  Another option is to set LogLevel to Debug in web.config which is by default Off and you ll get log files under App_Data / Log

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your valuable Feedback. I will try the subquery route.

Yes, I have VS2015. 

I will also try the rise of the LogLevel and see what my app is doing.

...and I will give Feedback in this issue.

Thanks and

with Kind regards,

John

**Comment by JohnRanger** [comment]
Hi JaiQ,

the log activation reveals what is sent to the underlying MS SQL engine. And it seems to be wrong:

```SQL

[D] 2016-02-24T08:12:23.516 END - ExecuteNonQuery
[D] 2016-02-24T08:12:31.422 ExecuteNonQuery
DECLARE @p1 INT = 1;
DECLARE @p2 INT = 7;
DECLARE @p3 INT = 11;
DECLARE @p4 BIT = 1;
DECLARE @p5 INT = 4;

UPDATE [dbo].[Clients] SET [Costcenter_ID] = @p1, [LifeCycle_Status_ID] = @p2, [Location_ID] = @p3, [SCSM_Sync_Required] = @p4 WHERE (jDataImport.[Delivery_ID] = @p5)

```

The Statement after the where clause reveals that Serenity passes the "jDataImport.Delivery_ID" string down to the SQL engine. But it should actually resolve this Expression to an innerjoin Expression if I am right.

The rest of the Update command seems correct to me and it would only update fields which are directly in the Clients table.

Is there something which I can do here?

Thanks again for your time and your help.

With Kind regards,

John

**Comment by volkanceylan** [comment]
As i said SqlUpdate doesn't support UPDATE ... FROM syntax, you need to use subquery

**Comment by JohnRanger** [comment]
Hi JaiQ,

although I couldn't figure out the Linq subquery Syntax correctly (even with a lot of googling and trying), I could solve it by using a MS SQL view where I just do the same Thing as within the serenity Clientsrow:

I do the leftjoins and then within Serenity, I have one flat table.

Thanks again and

with Kind regards,

John
