### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#3100]
Hello all,

Until now I've been using the default editors/validators for row fields.
Next, I am trying to replace a numeric row field with a slider.

I can't find examples how to achieve this in the documentation, is that right ?

So, I've got this EntityDialog and then : 

 **protected onDialogOpen() {
            super.onDialogOpen(); 
            $(".field Score").slider();
        }**   

In the div containing the input element for the row field, I want to set the slider, reflecting the value of the numeric field.
Is this a good approach ?

**Comment by Estrusco** [comment]
IMHO the best way is create an editor that implement the slider control. Your editor have to make a control like this, and implement Serenity.IGetEditValue and Serenity.ISetEditValue interface 

```html
<div class="field">
    <input id='mySlide' name='SliderTest' type='text'
        data-provide='slider'
        data-slider-ticks='[0, 1, 2, 3, 4]'
        data-slider-ticks-labels='["One", "Two", "Three", "Four", "Five"]'
        data-slider-min='0'
        data-slider-max='4'
        data-slider-step='1'
        data-slider-value='0'
        data-slider-tooltip='hide' />
     <script>
          $('#mySlide').slider();
     </script>
</div>
```

**Comment by GreenUtil** [comment]
Hi Etrusco, thanks for your hints. I've implemented as much as possible, but I am still getting the default Integer-Editor, an input textfield, for the numeric row field : 

 **@Serenity.Decorators.registerClass()
    @Serenity.Decorators.editor()
    export class ReviewCompetenceSliderEditor extends Serenity.IntegerEditor implements Serenity.IGetEditValue, Serenity.ISetEditValue
    {
        protected getColumnsKey() { return "Default.ReviewCompetence"; }
        protected getDialogType() { return ReviewCompetenceDialog; }
        protected getLocalTextPrefix() { return ReviewCompetenceRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);

            var element1 = document.createElement("div");
            element1.className = "field";
 
            var element2 = document.createElement("input");
            
            //Assign different attributes to the element.

            element2.setAttribute("type", 'text');

            element2.setAttribute("id", 'mySlide');

            element2.setAttribute("name", 'SliderTest');

            element2.setAttribute("data-provide", 'slider');

            element2.setAttribute("data-slider-ticks", '[0, 1, 2, 3, 4]');

            element2.setAttribute("data-slider-ticks-labels", '["One", "Two", "Three", "Four", "Five"]');

            element2.setAttribute("data-slider-min", '0');

            element2.setAttribute("data-slider-max", '4');

            element2.setAttribute("step", '1');

            element2.setAttribute("value", '0');

            element2.setAttribute("data-slider-tooltip", 'hide');

            element1.appendChild(element2);

            var oScript = document.createElement("script");
            oScript.type = "text\/javascript";
            oScript.text = "$('#mySlide').slider();"
            element1.appendChild(oScript);

            document.body.appendChild(element1);

        }

        public get value(): number {
            return this.element.slider('value');
        }

        public set value(value: number) {
            this.element.slider().slider('value', value);
        }

        public getEditValue(property, target) {
            target[property.name] = this.value;
        }

        public setEditValue(source, property) {
            this.value = source[property.name];
        }**

**Comment by GreenUtil** [comment]
For our newborn company, [apprezi.com](url), it's important to get the custom editor working. If somebody wants to help us to solve this, for us it's worth a financial rewarding. If you're interested, let us know your proposal at    barent.brouwers@apprezi.com

**Comment by GreenUtil** [comment]
Some new information : 

when I add 

var old_element = document.body.getElementsByClassName("field Score")[0];

to the  ReviewCompetenceSliderEditor code,

then this old_element can't be found !

Document.body is still referencing the previous EntityDialog from which the ReviewCompetence EntityDialog is started.......

**Comment by GreenUtil** [comment]
Some new information : 

Even in the onDialogOpen still the previous dialog is referenced by document.body !

**Comment by GreenUtil** [comment]
When working with **this.element[0]** in onDialogOpen, it's possible to get a reference to the right field element on the dialog and to replace this element with something new like a slider.

**Comment by Estrusco** [comment]
Hi @GreenUtil 

The editor can create his own html code. In the container variable there is the element that contain the field where you apply the editor attribute.

Your attribute can start with 

```ts
namespace YourNameSpace {

    /**
     * This is an Slider editor widget
     *  
     */
    @Serenity.Decorators.element("<div/>")
    @Serenity.Decorators.registerEditor([Serenity.IGetEditValue, Serenity.ISetEditValue])
    export class SliderEditor extends Serenity.Widget<SliderEditorOptions>
        implements Serenity.IGetEditValue, Serenity.ISetEditValue {

        constructor(container: JQuery, options: SliderEditorOptions) {
            super(container, options);

            this.updateElementContent();
        }

        private updateElementContent() {
            var ticks: string;
            var tickslabels: string;

            // Here you can dynamically create ticks and ticks labels
            //for (var t of this.options.ticks) {
            //    [...]
            //}

            var elID = 'sld' + this.uniqueName;

            this.element.append('<input id="' + elID + '" />');
            var input = this.element.find('#' + elID);
            input.attr({
                    'data-provide': 'slider',
                    'data-slider-ticks': '[0, 1, 2, 3, 4]', // TODO: create dynamically
                    'data-slider-ticks-labels': '["One", "Two", "Three", "Four", "Five"]', // TODO: create dynamically
                    'data-slider-min': this.options.min,
                    'data-slider-max': this.options.max,
                    'data-slider-step': this.options.step,
                    'data-slider-value': 0,
                    'data-slider-tooltip': 'hide'
                });
            input.append('<script>$("#' + elID + '").slider();</script>');
        }

        [...] // Implement get and set
    }

    export interface SliderEditorOptions {
        min: number;
        max: number;
        step: number;
        ticks: number[];
        tickslabels: string[];
    }
}
```

**Comment by GreenUtil** [comment]
Thanks again @Estrusco, I am wondering, where do you set the SliderEditorOptions ? In the SliderEditorAttribute in the form ?  When I run my application with the SliderEditor, the jquery-ui-1.12.1.js with the jQuery UI Slider 1.12.1 is called, instead of bootstrap-slider.js. I think that's the reason the slider is like this (Score field) :  

![image](https://user-images.githubusercontent.com/2122311/34516939-3b11c91e-f079-11e7-8e04-f90954d82891.png)

**Comment by Estrusco** [comment]
Yes, the option are set from attribute in the form. But if you want you can set option programmatically (in dialog.ts).

For second question, see if there are errors in console, or try to change the .slider() in script with .bootstrapSlider()

**Comment by GreenUtil** [comment]
.boostrapSlider() : This is much better, however :  initially the ticklabels are lying in top of each other, and jQuery-ui is still being called, that's probably why I see an extra square on top of the leftmost round tick. The console says : 

bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.

SCRIPT5007: Kan de eigenschap toggleClass van een niet-gedefinieerde verwijzing of een verwijzing naar een lege waarde niet ophalen  (It's dutch !)
jquery-ui-1.12.1.js (569,3)

![image](https://user-images.githubusercontent.com/2122311/34517797-df874af2-f07c-11e7-8a85-60f4c8281d6d.png)

**Comment by Estrusco** [comment]
mmm... which version of Serenity you have?

I think you have to check your version of scripts bootstrap-slider and the _LayoutHead. Compare with latest serene project.

I have make a test in my project, using .slier() and all works without console error messages.

**Comment by GreenUtil** [comment]
SerenityCore.3.0.5.0

**Comment by Estrusco** [comment]
Try to update to latest Serenity version (3.3.14)

**Comment by GreenUtil** [comment]
Done that.
I've got 
Serenity.Core
Serenity.Data
Serenity.Data.Entity
Serenity.Services
Serenity.Web

all version 3.3.14 now

Errors with  _LayoutHead.cshtml still exist.....

**Comment by Estrusco** [comment]
Check if your ScriptBundles.json is same this (without nortwind zone)

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Scripts/site/ScriptBundles.json

or restore your initial _LayoutHead.cshtml keeping new serenity version.

**Comment by GreenUtil** [comment]
Application won't start up again...restarting Visual Studio etc. etc. doesn't help....

**Comment by Estrusco** [comment]
Post console errors.

You have to compare with Serene (use WinMerge or some other program):
Web.config
Global.asax
packages.config
View\Shared\_Layout.cshtml
View\Shared\_LayoutHead.cshtml
Scripts\Site\ScriptBundles.json

You have a problem with script. 

Or, if you can, start with new clean Serene project and move your code.

**Comment by GreenUtil** [comment]
Pffff, I migrated my sourcecode to a clean Serene project. Building correctly took some time. But the result is great ! My slider is working properly....well, almost, it isn't listening to the attributes.....it counts to 10 whereas data-slider-max is 4 and an error in the console : 

![image](https://user-images.githubusercontent.com/2122311/34538983-f16fee34-f0ce-11e7-9cf9-55d0acf43a0b.png)

**Comment by Estrusco** [comment]
Nice :D

Now, seem that you use a value property that not exist in slider object. If you open debug tool in browser (F12), go in sources tab, you can debug editor and see where is the error.

If you post your editor code, I can take a look.

**Comment by GreenUtil** [comment]
Thanks, I'll try to fix it by myself first......:D

**Comment by GreenUtil** [comment]
My editor code now is :    without errors on the console, however I wonder how to get the initial data-slider-value from database.......and the tooltips don't appear so I have added {tooltip: "always"}

```
/**
 * This is an Slider editor widget
 *  
 */

namespace AppreziSolution.Default {

    @Serenity.Decorators.element("<div/>")
    @Serenity.Decorators.registerEditor([Serenity.IGetEditValue, Serenity.ISetEditValue])
    export class SliderEditor extends Serenity.Widget<SliderEditorOptions>
        implements Serenity.IGetEditValue, Serenity.ISetEditValue {

        constructor(container: JQuery, options: SliderEditorOptions) {
            super(container, options);

            this.updateElementContent();
        }

        private updateElementContent() {
            var ticks: string;
            var tickslabels: string;

            // Here you can dynamically create ticks and ticks labels
            //for (var t of this.options.ticks) {
            //    [...]
            //}

            var elID = 'sld' + this.uniqueName;

            this.element.append('<input id="' + elID + '" />');
            var input = this.element.find('#' + elID);
            input.attr({
                'data-provide': 'slider',
                'data-slider-ticks': '[1, 2, 3, 4]', // TODO: create dynamically
                //'data-slider-ticks-labels': '["One", "Two", "Three", "Four"]', // TODO: create dynamically
                'data-slider-min': 0, //this.options.min,
                'data-slider-max': 4, //this.options.max,
                'data-slider-step': 1, //this.options.step,
                'data-slider-value': 0,
                'data-slider-tooltip': 'hide'
            });
            input.append('<script>$("#' + elID + '").slider({tooltip: "always"});</script>');
        }

        // Implement get and set
        public get value(): number {
            return this.element[0].children[1].value;
        }

        public set value(value: number) {
            this.element[0].children[1].value = value;
        }

        public getEditValue(property, target) {
            target[property.name] = this.element[0].children[1].value;
        }

        public setEditValue(source, property) {
            this.element[0].children[1].value = source[property.name];
        }
    }

    export interface SliderEditorOptions {
        min: number;
        max: number;
        step: number;
        ticks: number[];
        tickslabels: string[];
    }
}
```

**Comment by Estrusco** [comment]
Change the set get etc. function in:

```ts
        // Implement get and set
        public get value(): number {
            var sld = this.element.find('#sld' + this.uniqueName);
            return Q.toId(sld.slider('getValue'));
        }

        public set value(value: number) {
            var sld = this.element.find('#sld' + this.uniqueName);
            sld.slider('setValue', value);
        }

        public getEditValue(property, target) {
            target[property.name] = this.value;
        }

        public setEditValue(source, property) {
            this.value = source[property.name];
        }
```

**Comment by GreenUtil** [comment]
I understand this construction. (What does Q.toId do ?)  However, thinking up this myself is another thing.....
But it's working, great !
I hope I can construct more custom editors in the future myself.
Thanks !

**Comment by Estrusco** [comment]
Q.toId simply convert string in number.

You are welcome ;)

Remember to close the issue...

**Comment by vsudik** [comment]
Hello friends,
I am trying to use Type definitions for bootstrap-slider.js 9.9 (Project: http://github.com/seiyria/bootstrap-slider) in SliderEditor extends Serenity.Widget<SliderOptions>. But I can't register interface\make reexport of type SliderOptions from 'node_modules\@types\bootstrap-slider\index.d.ts ' for using in MyForm.cs like [SliderEditorAttribute(Min=0, Max=5)]. Can somebody help me, please, how to make reexport or register interface SliderOptions from Type definitions for bootstrap-slider.js?
