### ISSUE TITLE
Anyone having an EditorDialog template issue?

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#3102]
Code that we have been running daily for the last 3 weeks all of a sudden is throwing a browser error saying it cannot find the EditorDialog template. Funny thing is this is now happening on two different previously working active projects. However, if I create a new SmartStart serenity application using the SmartStart template, the error is not there. I have scanned the code and all seems the same. 

Just wondering is anyone has this same issue?

**Comment by VR-Architect** [comment]
I deleted my modules and the issue went away. So it is something in my code which the compiler is not catching. I will troubleshoot now and post here the fix once I find today.

**Comment by volkanceylan** [comment]
Make sure you add /// references statements to classes that reference GridEditorBase etc. TypeScript is not able to order files correctly, e.g. a base class should be generated before a derived class, but TS can't unless you add /// references

**Comment by VR-Architect** [comment]
Thanks, I deleted all my modules/objects except one. Then I used sergin to generate the same object in the default module in the same project. That new one ran fine. I checked every line of code of the new and old one and they are identical. My eyes need a break. I will take your advise and try in a couple of hours. Thanks for the suggestion.

**Comment by VR-Architect** [comment]
Hi Volkan, I think you advice is on the right track but shouldn't that be the Serenity.EntityDialog class? 

This is in my BankDialog.ts file:
`export class BankDialog extends Serenity.EntityDialog<BankRow, any> `

I added this to every *.ts and *.cs file in my object and still had same error:
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />`

So I then added this to the same files and still had the same error:
```
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />
/// <reference path="../../Common/Helpers/GridEditorDialog.ts" />
```

Full error message:
```
Serenity.CoreLib.js?v=UoFTEXH4uI4wzwgaIpeeAg:3007 Uncaught Error: Can't locate template for widget 'EntityDialog' with name 'EntityDialog'!
    at BankDialog.TemplatedWidget.getTemplate (Serenity.CoreLib.js?v=UoFTEXH4uI4wzwgaIpeeAg:3007)
    at BankDialog.TemplatedWidget [as constructor] (Serenity.CoreLib.js?v=UoFTEXH4uI4wzwgaIpeeAg:2918)
    at BankDialog.TemplatedDialog [as constructor] (Serenity.CoreLib.js?v=UoFTEXH4uI4wzwgaIpeeAg:3285)
    at BankDialog.$Serenity_EntityDialog [as constructor] (Serenity.Script.UI.js?v=uD875r9fyeblf72cPYkIRA:1273)
    at new BankDialog (BankDialog.ts:5)
    at Function.Widget.create (Serenity.CoreLib.js?v=UoFTEXH4uI4wzwgaIpeeAg:2870)
    at BankGrid.createEntityDialog (Serenity.Script.UI.js?v=uD875r9fyeblf72cPYkIRA:8278)
    at BankGrid.editItem (Serenity.Script.UI.js?v=uD875r9fyeblf72cPYkIRA:8196)
    at BankGrid.addButtonClick (Serenity.Script.UI.js?v=uD875r9fyeblf72cPYkIRA:8193)
    at Object.onClick (Serenity.Script.UI.js?v=uD875r9fyeblf72cPYkIRA:8174)
```

**Comment by VR-Architect** [comment]
Note that my object is in a module called "acct" and the object is called "Bank".

**Comment by VR-Architect** [comment]
Hey Volkan,
I used sergen from the web application to generate 3 objects:

1. module name "acct" (testing to see if namespace issue with my "XXXX.acct" namespace) - Got error
2. module name some random value - got error
3. module name with defaults in sergen - works as expected

Any ideas?

**Comment by volkanceylan** [comment]
As specified in guide, module names must be PascalCase, that's the reason.

**Comment by VR-Architect** [comment]
You are such a rockstar! That was it. Thank you, thank you, thank you.
