### ISSUE TITLE
setEquality not working 

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#3104]
Hello , 

previously Set Equality is working with below code 
`  export class TemplateProductsGrid extends Serenity.EntityGrid<SoTemplateOrderLinesRow, any> {
protected getColumnsKey() { return 'OnLineOrderEntry.TemplateProduct'; }
protected getIdProperty() { return SoTemplateOrderLinesRow.idProperty; }
protected getLocalTextPrefix() { return SoTemplateOrderLinesRow.localTextPrefix; }
protected getService() { return SoTemplateOrderLinesService.baseUrl; }

protected getGridCanLoad() {return this.DealerNo != null;}
private _DealerNo: string;
     get DealerNo() { return this._DealerNo; }
      set DealerNo(value: string) {
            if (this._DealerNo != value) {
                this._DealerNo = value;
                //alert("Got DNo = " + value);             
                this.setEquality(SoTemplateOrderLinesRow.Fields.OrderDealershipNo, value);
                this.refresh();
            }
        }`

than i change it to below code :(

`   export class TemplateProductsGrid
        extends Serenity.EntityGrid<SoTemplateOrderHeaderRow, any> {
        protected getColumnsKey() { return 'OnLineOrderEntry.TemplateProduct'; }
        protected getIdProperty() { return SoTemplateOrderHeaderRow.idProperty; }
        protected getLocalTextPrefix() { return SoTemplateOrderHeaderRow.localTextPrefix; }
        protected getService() { return SoTemplateOrderHeaderService.baseUrl; }

  set DealerNo(value: string) {
            if (this._DealerNo != value) {
                this._DealerNo = value;
                //alert("Got DNo = " + value);             
                this.setEquality(SoTemplateOrderHeaderRow.Fields.DealerDealershipNo, value);
                this.refresh();
            }
        }
`
now its not working ... 

can anybody please tell me where i did wrong???
and to use 'setEquality' which steps need to check. 

Thanks.

**Comment by dfaruque** [comment]
https://serenity.is/demo/BasicSamples/GridFilteredByCriteria

**Comment by rakeshpatil20** [comment]
Thanks for you help @dfaruque  
i did that also but not working :(
`protected onViewSubmit() {
            if (!super.onViewSubmit()) {
                return false;
            }
            var request = this.view.params as Serenity.ListRequest;
            request.Criteria = Serenity.Criteria.and(request.Criteria,
                [['DealershipNo'], '=', this._DealerNo]
            ); 
            return true;
        }`

can you tell me where i did wrong in my previous code and this code?

**Comment by volkanceylan** [comment]
Check browser console for the value that is passed to service. Check that property name matches actual field property name, e.g. in your row property name is DealerDealershipNo not DealershipNo
