### ISSUE TITLE
Need Help to use Sergen AutoGenerate classes MVC 5

### ISSUE THREAD

**Issue by CS-beglnner** [volkanceylan/Serenity#3105]
I'm trying to add Serene in my project as admin panel
After importing MyDB with Sergen how I can read my data in Front-end UI ? 
I know my quiz is stupid but need help for migration my project with Serene. I read wikis and google search but I cant found helpful articles.
If is possible can you help me a little with a simple codes?!
A answer with "Meeting Template" as Base is very very  helpful. 

> How to show all meetings and a meeting detail by Id (in _UserLayout with !ReadPromise)_ with serene searching method

**Comment by volkanceylan** [comment]
You may call repository methods, they are basic C# methods.

var records = new MyRepository().List(new ListRequest { ... }).Entities
