### ISSUE TITLE
SaaS Multitenancy with multiple databases

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#3108]
Hi,

I know there have been a lot of posts about this, but I was wondering what the best way would be to implement a single instance/multiple database multi-tenancy model.

I was thinking of adding a customer number to the login screen and forking the connection string just before logging on. The customer number would be in a central lookup where the connection string would be retrieved. Everything else would then be the same, based on that one dynamic connection string.

However, I have noticed that a lot of the background work around the UnitOfWork is governed by the ConnectionKeyAttribute. At what point do you suggest I intercept the connection key? 

I was thinking of removing the attribute from the XXXRow classes, and creating the connection with a behavior.  I was just wondering what else I need to add to make the repository work.

I know this is a bit vague.. but it is more about what is required and what's missing if the ConnectionKey is removed and how to replace it with a custom attribute.

**Comment by volkanceylan** [comment]
Yes, this was asked lots of times and my suggestion was to use configuration inheritance feature in IIS. Serenity and ASP.NET MVC is not designed for dynamic connection strings.

**Comment by karimhyatt** [comment]
Ok Thanks. I'll have a look at that and post back anything I find. 

Have a great 2018!
