### ISSUE TITLE
A Grave Multi-tenancy Security Issue

### ISSUE THREAD

**Issue by galof** [volkanceylan/Serenity#3109]
I'd like to wish all a Happy and Prosperous New Year! I would also like to thank everyone in Serenity for keeping this project alive and special thanks to volkanceylan for all his tremendous effort to create and maintain such a wonderful work. Thanks once again to everybody that offered to help me and the whole community to solve the various issues faced with.

The issue faced here, as I could see is a timely one. And what is more, it is a really grave one as it threatens the security of any Multi-tenancy Serenity project right from the start. I must say that I really feel a bit bewildered that it hasn't been cured for quite a long time now but only suggestions offered. It's a time-bomb in the foundations of any Multi-tenancy Serenity project.

What I'm talking about is not other than the notorious "User account issue": any single user can became an Administrator by his/her own actions and potentially create havoc across a certain Serenity project that applies Multi-tenancy. I strongly feel that this issue should be eliminated once and for all in a next Serenity edition. Let's keep our fingers crossed!

Thanks to all Serenity community and a Happy New Year to everybody!
Diera

**Comment by volkanceylan** [comment]
First of all, there is no multi tenancy integrated to Serenity, so there is no such issue.

If you are talking about multi tenancy tutorial, there is also not such an issue as long as you apply all the steps there properly.

If there is one we don't know of, it could be more helpful to report / explain how that happens then shooting "fire".
