### ISSUE TITLE
How to insert userId for CreatedBy , UpdatedBy and DeletedBy Column

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#311]
Dear Volkan Ceylan,

I would like to add UserId of Current Logged In user to following columns based on their operation in Serenity how do i do that

Suppose customer table has following column not visible on the screen:

CreatedBy : Int32   (UserId to be inserted here on Insert Operation )
CreatedAt : DateTime ( System Date time)
UpdatedBy : Int32 (UserId to be inserted here on Update Operation)
UpdatedAt : DateTime (System Datetime when Update Operation Performed)
DeletedBy : Int32  (UserId for soft delete)
DeletedAt : Date/Time (System DateTime when delete performed)
IsDeleted : Boolean

**Comment by volkanceylan** [comment]
Implement IInsertLogRow IUpdateLogRow IDeleteLogRow interfaces or create a base row like LoggingRow sample and implement them there once

**Comment by samdubey** [comment]
Thanks
Implemented Done :+1:
