### ISSUE TITLE
How can I return TenantID

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3110]
Hi serenity users

I am trying to create a lookup value using serenity similar to sample Northwind\Customer\CustomerCountryLookup.cs. But I want to filter the list based on logged user's TenantId.

I have the following code but the filter is not working. Please see the method `Tenant_ID()`. I know it will return a sql but I don't know how retrieve the value. Any hint please.

     public ChartOfAccountsLooup()
        {
            IdField = TextField = CoaMappingRow.Fields.EmisCoADescription.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            int tenID=Tenant_ID()
            
            var fld = CoaMappingRow.Fields;
            query.Distinct(true)
                .Select(fld.CoACode)
                .Select(fld.EmisCoADescription)
                .Where(
                    new Criteria(fld.seFlag).IsNotNull() &
                    new Criteria(fld.TenantId) == Tenant_ID());
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }

        public static int Tenant_ID()
        {
            string tenId;

            var query = new SqlQuery()
                            .Select("TenantId")
                            .From("Users")
                            .Where("UserId").Text == Authorization.UserId;

            tenId =query.ToString();

            return int.Parse(tenId);
        }

**Comment by volkanceylan** [comment]
Think you have already resolved that in StartSharp repo, please reopen if not.
