### ISSUE TITLE
Can't change to new language

### ISSUE THREAD

**Issue by vgalicc** [volkanceylan/Serenity#3111]
When I add new language(Dutch - nl) I can't select it. I choose Dutch in menu but it always returns to English. Project is ASP.NET Core.

**Comment by volkanceylan** [comment]
Nl is not a valid 4 letter language ID

**Comment by volkanceylan** [comment]
https://msdn.microsoft.com/en-us/library/ee825488%28v=cs.20%29.aspx?f=255&MSPPError=-2147217396

**Comment by vgalicc** [comment]
I have also tried with nl-NL. When I select Dutch in language picker it reverts to English. When I select Turkish, which is already there, it works ok. Can you give me some advice how to debug it?

**Comment by abusayedruetcse** [comment]
You can try adding language code to static variable Dictionary and supportedCultureIdentifiers in UserCultureProvider.cs file.
