### ISSUE TITLE
Web.js'in güncellenmeme sorunu?

### ISSUE THREAD

**Issue by sinerjik** [volkanceylan/Serenity#3115]
Volkan Bey,

Daha öncede soranlar olmuş fakat *web.js in neden güncellenmediğini/ nasıl güncelleneceğini bulamadım. (Not : vs2017 kullanıyorum.)

Yardımcı olursanız sevinirim. Başarılarınızın devamını dilerim.

**Comment by volkanceylan** [comment]
Typescript inizi kontrol edin
