### ISSUE TITLE
Exception not displaying in standard alert dialog

### ISSUE THREAD

**Issue by buddhatripp** [volkanceylan/Serenity#3118]
In the Reset Password module, I am throwing an exception based on password history to prevent repeat passwords. However, the exception is not displaying in the red alert dialog that is used throughout the rest of the application. How can I make exceptions display in the standard alert dialog?

![image](https://user-images.githubusercontent.com/16328936/34499418-fefb9928-efd3-11e7-8b0c-7f6d9e15940d.png)

**Comment by volkanceylan** [comment]
Write your validation code inside the InTransaction block of ResetPassword method, as it is in sample code there.
