### ISSUE TITLE
How to allow  some user to see a part of table records

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#312]
when i try to use method of setting tenantId to some table to allow user to see a part of table records, I can not to allow more than one user to see a same part of table records. For example ,I want to allow Employees of the same department to see a table records about this department but not allow to see others department records. How can I do? Thank you.

**Comment by volkanceylan** [comment]
So your tenant id is department id, why you can't let more than one user

**Comment by kuyu7766** [comment]
that I want a department user see other department info some times .for example a administrative department can see some departments they are managed.

**Comment by volkanceylan** [comment]
Then you need a table like allowed departments and filter with IN

**Comment by volkanceylan** [comment]
This goes into todo-list as a future sample
