### ISSUE TITLE
dotnet sergen servertypings Filed! VS2017 & Asp.Net Core2

### ISSUE THREAD

**Issue by FeynmanLoo** [volkanceylan/Serenity#3122]
When I follow the tutorials "Adding Kind Field to MovieRow Entity", I got the error "Uncaught Can't find MovieTutorial.MovieDB.MovieKind enum type!" . When I try to run command "dotnet sergen servertypings" to fix it,  I got the error messages :

D:\project\MySerene\MovieTutorial\MovieTutorial.Web>dotnet sergen servertypings
Transforming ServerTypings at: D:\project\MySerene\MovieTutorial\MovieTutorial.Web\Imports\ServerTypings
Couldn't list types in project assembly: 'D:\project\MySerene\MovieTutorial\MovieTutorial.Web\bin\Debug\netcoreapp2.0\MovieTutorial.Web.dll'!

Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

This is happening with a clean demo install as well. Anyone else experiencing the same issue?

**Comment by volkanceylan** [comment]
Don't update ASP.NET Core, use 2.0.0.0

**Comment by FeynmanLoo** [comment]
@volkanceylan   Thx a lot !
