### ISSUE TITLE
Whats happen to new VSIX version?!!! 

### ISSUE THREAD

**Issue by CS-beglnner** [volkanceylan/Serenity#3123]
1. Awesome Meeting Module gone :(
2. Sergen PShell has workflow error (Application Has stopped)
3. Adding new Module with Sergen (Manuel opening) broken my project UI with clean browser console as attachment jpg
![untitled](https://user-images.githubusercontent.com/23167047/34568605-93f802a2-f17b-11e7-98e7-f5dc5f549ae2.jpg)

  Cache is clean, Project is rebuild before run

**Comment by volkanceylan** [comment]
Meeting module is moved to StartSharp.

Check your site.less file, there should be a missing closing double quote there.

**Comment by CS-beglnner** [comment]
@volkanceylan With this description, do I have permission to use the previous version?

**Comment by volkanceylan** [comment]
You can use old version :) I'll just won't maintain it.

I'd recommend following the tutorials in guide, not meeting module.

**Comment by CS-beglnner** [comment]
@volkanceylan Yes Sir, Thanks
