### ISSUE TITLE
Grouping and Auto Collapsed data

### ISSUE THREAD

**Issue by evagelos21** [volkanceylan/Serenity#3129]
Hi to all,
I'm using this http://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid in orderto group my data.
so far so good.
How can I set the data, auto group and auto collapse?
Is this possible?
Thanks in advane

**Comment by dfaruque** [comment]
in constructor 
```
this.view.setGrouping(
                    [{
                        getter: 'CategoryName'
                    }])
```

**Comment by evagelos21** [comment]
1/2 :)
and how about collapsed?

**Comment by evagelos21** [comment]
and how is possible (is so) to add the sub values in the same line of the group data?
ex:
![untitled](https://user-images.githubusercontent.com/9623090/34648688-01cae6c8-f3a7-11e7-9e33-36b185826085.png)

**Comment by volkanceylan** [comment]
That's not possible, grouping is feature of SlickGrid, check its docs.
