### ISSUE TITLE
Filter Record By Checking Their Role

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#313]
Dear Volkan Ceylan,

We are developing Learning Management Solution with Serenity:
We have following roles defined, we need to fetch data based on Roles assigned to User

Administrators
Institute Admins
Branch Admins
**Teachers**
**Students**

I have checked following class
public class UserDefinition : IUserDefinition
    {
        public string Id { get { return UserId.ToInvariant(); } }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public short IsActive { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string Source { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? LastDirectoryUpdate { get; set; }
        public int TenantId { get; set; }
    }
Do i need to extend this class to check for Roles in order to bring data based on Roles for User

Many Thanks,
Sameer

**Comment by volkanceylan** [comment]
I recommend using permissions not roles, you may define similar named permissions. Roles are only for grouping permissions. But anyway if you still want to use roles, yes you could add it here if you want it be cached.

**Comment by samdubey** [comment]
Thanks
