### ISSUE TITLE
role based lookup in serenity

### ISSUE THREAD

**Issue by Itsathere** [volkanceylan/Serenity#3130]
I have static editor like below code snippet

`namespace AS.SDLC {
    
    @Serenity.Decorators.registerEditor()
    export class BidStatusEditor extends Serenity.Select2Editor<any, any> {
        constructor(hidden: JQuery) {
            super(hidden, null);

            this.addItem({id:'Abandon', text:'Abandon', source: null, disabled: false});
            this.addItem({id:"Winning", text:"Winning", source: null, disabled: false});
            this.addItem({id:"Accepted", text:"Accepted", source: null, disabled: false});
            this.addItem({id:"Rejected", text:"Rejected", source: null, disabled: false});
        }
    }
}`

I want to show editor in as per role 

Example: 
**If role is Product Manager then lookup editor will only show**
>Wining
>Rejected

**If role is User then  then lookup editor will only show**
>Accepted
>Rejected

**If role is Authorize bidder then  then lookup editor will only show**
>Abandon
>Rejected

How will I manage dynamic editor from static list

**Comment by volkanceylan** [comment]
Use Q.Authorization.hasPermission, check some permission that roles has, you can't check roles, and you shouldn't.

**Comment by Itsathere** [comment]
If I am not wrong, Q.Authorization.hasPermission check the module authorisation but I need to check current logged In user role not the module permission.

**Comment by Itsathere** [comment]
**I have found my solution. My solution is below code snippet**

> 
namespace Voogu.SDLC {
    @Serenity.Decorators.registerEditor()
    export class BidStatusEditor extends Serenity.Select2Editor<any, any> {
        constructor(hidden: JQuery) {
		super(hidden, null);
			FRBugBidService.GetUserRoles({
				RoleName: Authorization.userDefinition.Username,
			},
				response => {
				switch(response.RoleName) { 
				   case "product manager": { 
					  this.addItem({id:'Wining', text:'Wining', source: null, disabled: false});
					  this.addItem({id:"Rejected", text:"Rejected", source: null, disabled: false});
					  break; 
				   } 
				   case "user": { 
					  this.addItem({id:"Accepted", text:"Accepted", source: null, disabled: false});
					  this.addItem({id:"Rejected", text:"Rejected", source: null, disabled: false});
					  break; 
				   } 
				   case "authorized bidder": {
					  this.addItem({id:"Abandon", text:"Abandon", source: null, disabled: false});
					  this.addItem({id:"Rejected", text:"Rejected", source: null, disabled: false});
					  break;    
				   } 
				}
			});
        }
    }
}

**changes in repository**

public RoleResponse GetUserRoles(IDbConnection connection, RoleRequest request)
        {
            var roleName =new RoleResponse();
            var loggedInUser = (UserDefinition)Authorization.UserDefinition;
            if (loggedInUser != null)
            {
                Administration.Entities.RoleRow role = new Administration.Entities.RoleRow();
                var userrole = connection.TryFirst<Administration.Entities.UserRoleRow>(new Criteria(Administration.Entities.UserRoleRow.Fields.UserId) == Convert.ToInt32(loggedInUser.UserId));
                if (userrole != null)
                    role = connection.TryFirst<Administration.Entities.RoleRow>(new Criteria(Administration.Entities.RoleRow.Fields.RoleId) == Convert.ToInt32(userrole.RoleId));
                if (role != null)
                {
                    roleName.RoleName = role.RoleName.ToLower();
                }
            }
            return roleName;
        }

**Comment by MayaBurns** [comment]
@itsathere was looking at this and was wondering why you only get ine role for the user?  Couldnt a iser have more than one role?
