### ISSUE TITLE
Windows/Linux/Mac OS X: Serin Error Couldn't read template source URL from VSGallery

### ISSUE THREAD

**Issue by ckrassas** [volkanceylan/Serenity#3132]
Hello All,

I have searched for a resolution to this but I cannot find something. 

Using:
serin v3.3.1500
node v9.2.1
npm v5.6.0

I have tried on 3 different machines to get this working but I keep getting the same error:

Couldn't read template source URL from VSGallery.

Update:
Did a little bit of digging around. After looking at the the serin/index.js file I found that the error I get is from - 
...
`           if (!assetSource) {
                console.error("Couldn't read template source URL from VSGallery.");
                process.exit();
            }`
....

Any help would be appreciated.

**Comment by artapp-ds** [comment]
replace
`if (f && f.assetType && f.assetType.endsWith('/Serene.Template.vsix'))`
to
`if (f && f.assetType && f.assetType.endsWith('Serene.Template.vsix'))`

in file _serin/index.js_
at line **188**

**Comment by ckrassas** [comment]
Worked like a charm! Thank you very much!
