### ISSUE TITLE
Antiforgery Web Interface Problem

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3134]
I'm trying to pass some parameters from my web interface to a controller (on a JSON format )and I get the error "" __RequestVerificationToken "is not present"
Then I followed the steps described in the section WIKI [Security] Preventing CSRF attacks (Implementing AntiForgery) and my code was as follows:
In the cshtml added:
`
@Html.AntiForgeryToken()
`
My script section looks like:

`

                $("#btnShow").click(function () {
                    var token = $('input[name="__RequestVerificationToken"]').val();//<----------
                    var headers = {};//<--------------------------------------------------------------------------
                    headers['X-RequestVerificationToken'] = token;//
                    $.ajax({
                        url: '@Url.Action("MyMethod", "MyController")',
                        type: 'POST',
                        dataType: 'json',
                        data: { Nombre: $('#name').val(), email: $('#email').val(), message: $('#message').val() },
                        headers: headers,
                        success: function (result) {
                            alert('OK');
                        },
                        error: function (data) {
                            alert('Error.');

                        },
                        complete: function (result) {

                       }
                    })

                });

`

But I still get the same error, I know I'm missing something but I can not realize that. Can someone point me in the right direction?

**Comment by javaman63** [comment]
I have to modify the header from 

```
headers['X-RequestVerificationToken'] = token; 
to 

headers['X-CSRF-TOKEN'] = token;
```

And my controoller method i put follow attribute

```
        [AutoValidateAntiforgeryToken]
        public ActionResult MyMethod (string paaram1, string param2)
```
And It worked

**Comment by PanChenhao** [comment]
@javaman63 I  meet the the same issue now.  where is this token get in your code?
`headers['X-CSRF-TOKEN'] = **token**;`
