### ISSUE TITLE
Build:Type 'string' is not comparable to type 'JQueryXHR'

### ISSUE THREAD

**Issue by Itsathere** [volkanceylan/Serenity#3136]
I am getting this error in typescript. Below is complete error.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	TS2678	Build:Type 'string' is not comparable to type 'JQueryXHR'.

**Comment by Estrusco** [comment]
When you post errors like this, you must specify much more information. 
Which is the file that have error? In which line of code? In which context? 
Possible post your code, or code with error.

**Comment by Itsathere** [comment]
`public string GetUserRole(IDbConnection connection)
        {
            var roleName = "";
            return roleName;
        }`
I try to call this method from typescript(.ts) and able to see object in browser and I had assigned that object in switch case statement that's why I was getting this error.Below is code snippet in .ts file

               

> var role=Voogu.SDLC.FRBugBidService.GetUserRole("");
> 		console.log(role); 

 Now error is resolved but the way I am seeing object I am not able to access on same way. For more you can see the below attachment

![capture](https://user-images.githubusercontent.com/16954075/34765193-e25166f6-f616-11e7-924a-472a57a339ef.PNG)

When I use 

> console.log(role); then it returns object in above attached picture
> console.log(role.responseText); then it return undefined

You can see both colsole results. My question is How will I access object to get exact data

**Comment by Estrusco** [comment]
Try with console.log(role)['responseText']

**Comment by Itsathere** [comment]
Your solution is not working getting error
`Uncaught TypeError: Cannot read property 'responseText' of undefined`

**Comment by Estrusco** [comment]
Sorry, I wanted to write console.log(role['responseText'])

If this not work, I don't know what is the problem. Try to set a breakpoint in browser in this line of code, and in console type role and see if at moment of method call this is valid

**Comment by Itsathere** [comment]
I have tried that too, getting same error.

**Comment by volkanceylan** [comment]
Read the guide topic about service endpoints. It is clearly stated there that you should derive your request response from some base classes. Closing.

**Comment by Itsathere** [comment]
I am getting same issue if i use base class instead of string. I am unable to extract data from class.
