### ISSUE TITLE
Serene template is incompatible with ReSharper

### ISSUE THREAD

**Issue by astrohart** [volkanceylan/Serenity#3138]
Hi,

I am using Visual Studio 2017 Update 15.5.2 and I am using ReSharper Ultimate 2017.3.

When I create a new project with the Serene template, everything creates just fine initially, and pressing F5 builds the project no problem and I can work on it okay, but ReSharper gives about 62 red errors in 14 files because it does not seem to understand TypeScript or the way C# is utilized in the project.

I was wondering if there was a plan to try and edit the code to remove issues such that ReSharper will give a green check mark in the status bar upon new template creation?  It makes it very hard to tell what is just ReSharper not understanding something properly vs a genuine error in my own code.

Yours,

Brian Hart

**Comment by astrohart** [comment]
![pic2](https://user-images.githubusercontent.com/8261875/34786675-ae82bef6-f5e9-11e7-8b18-a417242e8c69.png)

See the graphic above for what I mean, look in the lower right corner of the picture for the red circle.

**Comment by volkanceylan** [comment]
We dont code for Resharper sorry

**Comment by volkanceylan** [comment]
I'm not using Resharper and have no plan to use that :)

There should be some option in Resharper to ignore / turn into warning those errors.
