### ISSUE TITLE
Cascade LookupEditor on a Normal Razor View

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3140]
I have a interface that uses a regular view with razor. I need to load 2 Lookupeditor, which I did with the following code, 
```
                new Serenity.LookupEditor($('#Vehicles'), {
                    lookupKey: 'Parameters.Vehicles'
                })
```
but also need to make a Cascade
I try putting the value I need in the field, but it does not work.
```
                new Serenity.LookupEditor($('#Vehicles_Years'), {
                    lookupKey: 'Parameters.Vehicles_Years',
                    cascadeFrom: 'IdVehicles'
                })
```
I Have the Parameters.Vehicles_Years with the lookupinclude attribute on IdVehicles
Is this possible in this situation?
I hope you can help me, since I have been fighting this situation for some time.

**Comment by volkanceylan** [comment]
CascadeFrom should be 'Vehicles' as your main editor has that ID

**Comment by javaman63** [comment]
Thanx you @volkanceylan 
Again, you're a lifesaver
