### ISSUE TITLE
Apply Role Permission on Serenity Grid 

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3142]
Hi,

I have 3 different grids in my page. I need to display the grid based on the User Roles.
For a specific UserRole(for example:vendor), 1 particular grid should not be displayed out of 3 grids and for that specific user it should not allow to create new form option. 

can you please help me out for this.

**Comment by volkanceylan** [comment]
Roles are a group of users, use permissions unique to roles, not roles
