### ISSUE TITLE
Default Values in serenity grid

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3144]
Hi,

How to Set the default value in serene grid? 
I have 5 columns, 4 columns I will retrieve it from DB. The remaining 1 column I need to disply a static content. (Say "View") . How can I achieve this.
Kindly help me on this.

**Comment by minhhungit** [comment]
Use **Expression** attribute or even you will need to create a **formatter** 
https://github.com/volkanceylan/Serenity/wiki/SlickGrid-Formatters

**Comment by AmuthaKondusamy** [comment]
Hi,

Thanks @minhhungit .
I have used Stored procedure. In Stored Procedure, I have declared and set the value for static column. Now I have add a new entry in my _Row.cs and _column.cs with the same name as in stored procedure.
So, now i can able to display the static text in separate column.

**Comment by AmuthaKondusamy** [comment]
This can also be done by pushing the column dynamically in getcolumns() method in xyzgrid.ts.
