### ISSUE TITLE
dts-bundling ?

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3145]
hey again, just wondering, in the project of splitting some common features 
(ex : Administration features (language, roles, permissions etc) separately into a dedicated assembly (shared by several Serenity applications), there is the 'problem' of MERGING the .d.ts files.

did anyone already managed to do this ? 
is that technically possible to MERGE .d.ts from several assemblies (projects) ?
use of Webpack ?

The idea is to separate each functionalities into different assemblies (including corresponding .ts scripts).

**Comment by volkanceylan** [comment]
I don't think you need to merge d.ts files, but the biggest problem you'll have is about T4 templates, and code generation, so i wouldn't recommend trying that

**Comment by kilroyFR** [comment]
ok thanks Volkan
