### ISSUE TITLE
get fields by category

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#3147]
Hi
is it possible to get all the fields of a form based on the category they are under? 
Im also wondering if its possible to have a form that contains fields from two different entities. so kind of like the "another form in tab" sample but have the other form in the same tab and just under a different cattegory. then i can handle CRUD manually, just need an easy way to tell which fields belong to which entity (without hard-coding).
might be completely wrong way to do it but figured i'd ask...
thanks

**Comment by volkanceylan** [comment]
this.form.someField.getGridField().closest('.category').find('.field')
