### ISSUE TITLE
Customize the Excel reports - Charts, Pivots, Fonts

### ISSUE THREAD

**Issue by zKarp** [volkanceylan/Serenity#3148]
I'm not familiar enough with how this excel reporting works.

Any direction to implement some "standard" features into reports. Such as take data written to sheet1 and create a pivot chart?
Or change default font?

I'm very comfortable with Python and openpyxl but this is completely new.

Thanks,
Zach

**Comment by zKarp** [comment]
I found an old close issued and referenced EPPLUS.

I've added the following snipped after `PopulateSheet(worksheet, columns, rows, tableName, tableStyle);
` inside ExcelReportGenerator. What would be the ideal solution to put this to only modify certain reports?

`
            string pageName = "pvt-" + sheetName.Replace(" ", "");
            var wsPivot = package.Workbook.Worksheets.Add(pageName);

            //header
            var headerCells = worksheet.Cells[1, 1, 1, worksheet.Dimension.End.Column];
            var headerFont = headerCells.Style.Font;
            headerFont.SetFromFont(new Font("Arial", 9));
            headerFont.Bold = true;
            headerFont.Color.SetColor(Color.White);
            headerCells.Style.Fill.PatternType = ExcelFillStyle.Solid;
            headerCells.Style.Fill.BackgroundColor.SetColor(Color.DarkBlue);`

**Comment by volkanceylan** [comment]
What we use is EPPlus package, you may have a look at its samples

**Comment by qprotex** [comment]
I am interested to know also how we can customize the reports. I know Serenity it uses EPPlus but is ExcelReportGenerator the right place to add the custom code, and if yes, is there any suggested way to only modify specific reports?
