### ISSUE TITLE
Ensure a function in a behavior only run once

### ISSUE THREAD

**Issue by MayaBurns** [volkanceylan/Serenity#3149]
I am experimenting with adding a behavior on table1 onaftersave, look for some criterias then update table2. The behavior is called for all the rows in table1 when saved, this happens when table1 is a child table of table2. When table2 is saved, the added behaviors get called for all rows of table2.  How can I ensure that this function only runs once per save event of table2?  I can't just add the behavior on table1 since I need this to run for both table1 and table2. 

Scenario1: save event of table2

Table2(parent)
    Table1(child) - has added behaviors to just run once, currently runs for all saved rows

Scenario2: save event of table1 only
   Table1 - by default only run once

thanks

**Comment by volkanceylan** [comment]
Behavior runs for the row its defined for, so you need to define that behavior on main row, not detail.

**Comment by MayaBurns** [comment]
Ok thanks. I was trying not to repeat the code twice in different behaviors...
