### ISSUE TITLE
Customer Edit Dialog not working with Sql Server 2008 R2

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#315]
[Sorry for the new issue, but I cannot re-open the previous one...]

Btw Customer edit dialog is not working with sql server 2008 r2...
I tried both 
SqlConnections.GetConnectionString("Northwind").Dialect = SqlServer2005Dialect.Instance;

and

SqlConnections.GetConnectionString("Northwind").Dialect = SqlServer2012Dialect.Instance;

All others edit dialog are working fine...any ideas?

Thanks

**Comment by volkanceylan** [comment]
What is error you are getting in console

**Comment by volkanceylan** [comment]
It might be due to CONCAT, it seems like it wasn't available before SQL 2012, replace concat with + calls

**Comment by marcobisio** [comment]
You're right!
Replaced CONCAT instructions with + operator in the EmployeeRow.cs and now it's working fine.

Once again, thanks for your support
