### ISSUE TITLE
Customize the page after Login

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#3150]
Hi everyone,

I've a question: how can I change the page after login ?
When I login, I'll be redirected to the Dashboard. 
How can I change the page in **http://localhost:port/MyApp/CustomURL** ?

Thanks all for your time :)

Chiara

**Comment by kilroyFR** [comment]
> AccountPage.cs > public ActionResult Login(int? denied, string activated, string returnUrl)

perform a `return Redirect(myURL);`

**Comment by kjaraa** [comment]
[RoutePrefix("Account"), Route("{action=index}")]
    public partial class AccountController : Controller
    {
        public static bool UseAdminLTELoginBox = false;

        [HttpGet]
        public ActionResult Login(string activated)
        {
            ViewData["Activated"] = activated;
            ViewData["HideLeftNavigation"] = true;

            if (UseAdminLTELoginBox)
                return View(MVC.Views.Membership.Account.AccountLogin_AdminLTE);
            else
                return View(MVC.Views.Membership.Account.AccountLogin);
        }

        [HttpGet]
        public ActionResult AccessDenied(string returnURL)
        {
            ViewData["HideLeftNavigation"] = !Authorization.IsLoggedIn;

            return View(MVC.Views.Errors.AccessDenied, (object)returnURL);
        }

        [HttpPost, JsonFilter]
        public Result<ServiceResponse> Login(LoginRequest request)
        {
            return this.ExecuteMethod(() =>
            {
                request.CheckNotNull();

                if (string.IsNullOrEmpty(request.Username))
                    throw new ArgumentNullException("username");

                var username = request.Username;
                
                if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
                    return new ServiceResponse();

                throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);
            });
        }

        private ActionResult Error(string message)
        {
            return View(MVC.Views.Errors.ValidationError,
                new ValidationError(Texts.Validation.InvalidResetToken));
        }

        public ActionResult Signout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return new RedirectResult("~/");
        }
    }

That's my AccountPage.cs: where I put the redirect line ?

Thanks :)

**Comment by kilroyFR** [comment]
Instead of : 

return View(MVC.Views.Membership.Account.AccountLogin);

use redirect : 
ex :        return Redirect(config.AuthAPIServer + "AUTH.HTML/?app=" + ConfigurationManager.AppSettings["ApplicationCode"]);

**Comment by kjaraa** [comment]
Ok. Thank u so much !! :)
