### ISSUE TITLE
Edit Role Permissions multitenancy

### ISSUE THREAD

**Issue by tynmas02** [volkanceylan/Serenity#3151]
Hi! I have followed your multitenancy tutorial and it works fine. I have one question though. Is there a way when I edit a role and click edit role permission to see different things for every tenant? For example, if I login as tenant2, I see Administration,Northwind ( https://ibb.co/j3uKgm ). The same, if I login as admin. So, is there a way, when I login as tenant2 to see only Administration and not Northwind, while as admin I can see all ( Administration,Northwind ). Thank, you.

**Comment by AlperanQ** [comment]
Hi, when you login as admin, you can authorize other users. So you can choose their want to show. Do i understand the problem correctly?

**Comment by tynmas02** [comment]
Hi @AlperanQ , I know, I can authorize other users as an admin. Let me explain my problem thoroughly. So my application is a multitenancy application. Say I have two different tables, one called School Management and the other Optics Management. So in my School Management, there are various roles ( teachers, admins, students ). So there is a user say tenant2 that is the admin of School Management say for a bussiness called A. So as an admin he creates users and assigns roles to them. Teachers and students can't see the role table, only tenant2 can. So my problem is that when I create roles for School Management, I click edit role, then edit role permission and I can see both Optics Management's tables and School Management's table ( in this picture I see Northwind  https://ibb.co/j3uKgm for example ). What I would like to see, is only School Management table ( Create, Delete , View ), not Optics Management, because it is irrelevant to my customer's needs. When I sell my app to a School Business, I don't want them to have this option. Although they can't see any of the data of Optics Management, they can see this option. I did the multitenancy tutorial and it works like a charm, but I have this problem. In the tutorial, it hided the Tenants table from being an option on edit permission dialogue. So tenant2 couldn't give himself this privilege by editing his roles. This is what I want to be altered. I want Tenant table option to be seen my admin, but not by tenant2. Thank, you.

**Comment by AlperanQ** [comment]
Navigation items are controlled by permissions, so if you setup permissions correctly, you can hide menus based on permissions

**Comment by tynmas02** [comment]
Hi @AlperanQ . I don't think you understand the problem. Hiding navigation items is easy. They are controlled by permissions. My problem is that say for example I want to hide Northwind from tenant2. I login as admin, I edit tenant2 's permissions ( revoke access to Norhwind ). But, If I login as tenant2, I can grand this permission ( of seeing Northwind ) to myself, by editing my permissions. So want I want is hide this possibility from tenant2, I want to give permissions from admin but not from tenant2. And I can't just hide user management because tenants need to create users via it. Thank, you.

**Comment by volkanceylan** [comment]
Actually he understands the problem, and just as you hide Tenants permission, you may hide any permission from end users, so simple solution is there.

Anyway, custom requests are not covered for support offered here.
