### ISSUE TITLE
Permission and Automatic Disable/Enable Edition

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3153]
hey, i have set ReadPermission/ModifyPermission (2 different permissions) on my xyzrow.cs.
Now i would like to set readonly controls when ModifyPermission is not set (in updateInterface()).
At this time i can make it works by hardcoding in my Dialog.ts

```
    protected updateInterface(): void {
      super.updateInterface();

 if (!Authorization.hasPermission("MyModifyPermission")) {
          // finding all editor elements and setting their readonly attribute
          // note that this helper method only works with basic inputs, 
          // some editors require widget based set readonly overload (setReadOnly)
          Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);
```

Is there a better way to get current Permissions associated to the xyzrow in updateInterface() (to avoid hardcoding) ?

Thanks !

**Comment by fredvaliant** [comment]
Have you found a better way to do it or any one has a better solution, client side or server side?

**Comment by fwd079** [comment]
No there is no such way. Currently either hardcode/duplicate your code or create a "permission.ts" file by hand, copy all permission strings as constant by hand there, and use in ts files.

Regards
