### ISSUE TITLE
Problem with Master-Detail-SubDetail Relationship

### ISSUE THREAD

**Issue by hannesb** [volkanceylan/Serenity#3155]
I came across this problem if a detail table contains another detail table (i.e. if the Northwind Orders table would have a field with a MasterDetailRelation attribute, lets say 'OrderFlags'):
Sometimes, if only rows are added to the SubDetail table (OrderFlags), an no other changes are made to master or detail fields, no INSERTs are generated for the added rows.

**Comment by volkanceylan** [comment]
Think this should be solved with your pull request, thanks.

**Comment by hannesb** [comment]
I can confirm that the problem with the missing INSERTs is fixed in V3.4.0
