### ISSUE TITLE
Advisory from Netsparker - Serenity Application Platform 3.0.5

### ISSUE THREAD

**Issue by DanielBishtawi** [volkanceylan/Serenity#3160]
Hello,

While testing the Netsparker web application security scanner we identified a vulnerability in Serenity Application Platform 3.0.5.

Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me: daniel (at) netsparker (dot) com

Looking forward to hearing from you.

Regards,

Daniel Bishtawi

**Comment by volkanceylan** [comment]
No ads here.
