### ISSUE TITLE
Grid: save column settings

### ISSUE THREAD

**Issue by tomuee** [volkanceylan/Serenity#3161]
Hello all!

In the current Serenity demo in Northwind->Customers i can change the grid's column width and order. After changing to another site and changing back to the Northwind Customers site the column settings are restored.
In my Serenity project these settings won't be restored. I just updated my template to the newest version.
Is there any built-in feature of serenity to archieve this?

Thanks in advance

**Comment by kilroyFR** [comment]
To Enable user preferences saving/restore, set :
Serenity.DataGrid.defaultPersistanceStorage = window.localStorage; //to store user prefs in browser cache
or
 Serenity.DataGrid.defaultPersistanceStorage = new Common.UserPreferenceStorage(); //store user prefs in database i.e. persist across browsers

in Modules\Common\ScriptInitialization.ts

**Comment by tomuee** [comment]
This worked! Thank you!

**Comment by tomuee** [comment]
Hello,
try this:
`Serenity.DataGrid.defaultPersistanceStorage = new Serenity.Extensions.UserPreferenceStorage();`

**Comment by NivethaTechStarz** [comment]
It worked.Thanks
