### ISSUE TITLE
Dialog; Toolbar buttons are not reached by pressing "Tab" key when editing fields

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3162]
Hi @volkanceylan ,

this is with SF 2.9.24 but I have also tested it with the most current SF 3.3.15 (as now no Dialogs are shown by Default, test it with Basic samples --> Dialogs).

When having a Dialog open and having the Focus on one of the form fields, it is not possible to Focus any of the Buttons within the toolbar (e.g. save button) **by pressing the Tab key**.

The Focus round robins between the form fields and also the X button to Close the dialog but it is not possible to Change the Focus to one of the toolbar Buttons.

I only have realized this when I now have to enter a lot of data via a Dialog and always have to Change between Keyboard and mouse to finalize a record's data entry.

(Also with the new "integrated" Dialog view (no popup window) the TAB Focus also goes to the URL entry line and other "unuseful" fields which are not related with the current form entry.)

@volkanceylan : It would be very useful if the Default behavior of pressing the TAB key within a Dialog is so, that all objects (Buttons, fields, etc) could be reached by pressing the "TAB" key. For the "integrated" Dialog, it would be very useful to Limit the TAB focusing on the Things relevant for the current "Dialog"  .

The benefit of this is high when a high volume of data has to be entered (all can be done with the Keyboard without changing every time to the mouse).

How do you see this?

Thanks for your Feedback and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Toolbar buttons are not supposed to be tab focusable, they are not even tab focusable in MSWord, just like you can't reach toolbar buttons in GitHub where i'm writing this reply. 

Buttons support shortcuts, e.g. there is Alt+S (save), Alt+X (delete) etc.

**Comment by JohnRanger** [comment]
Hi Volkan,

thanks for your Reply. So far in all the business web apps which I was using, the relevant Buttons were accessible by using tab. But I can accept the suggested workarround :-)

With Kind regards,

John
