### ISSUE TITLE
Is it possible to use Serenity with Pomelo.EntityFrameworkCore.MySql?

### ISSUE THREAD

**Issue by ofir-shapira-como** [volkanceylan/Serenity#3163]

**Comment by volkanceylan** [comment]
Serenity uses Dapper and its own SQL helpers. This doesn't prevent you from using any data access framework you want. Serenity won't use it though.

**Comment by ofir-shapira-como** [comment]
I want Serenity to use it for the migrations (instead of can use "System.Data.SqlClient" as I find it more friendly).
Tried to configure with no luck so far.
