### ISSUE TITLE
Refresh  (data) parent dialog when a child table was open via dialog directly on the opened parent dialog

### ISSUE THREAD

**Issue by MayaBurns** [volkanceylan/Serenity#3164]
Hi all,

I allow a user to open a child table dialog directly on the parent dialog using a button.  It's not going through the editordialog.  When user save data in this child table, the data on the parent child obviously changed.  How can I request the entity or data on the parent dialog so that it's aware of the changes and does not get overwritten,.

Currently, I make it so that when user click to open the child dialog; it closes the parent dialog.  Then when the child dialog finish.  Using the ondialogclose event of the child, I reopen the same parent child again so that the data get reloaded.

Is there a better way to do that???

thanks much.

**Comment by minhhungit** [comment]
Try using a trigger, read more at here:
Trigger: https://github.com/volkanceylan/Serenity/issues/1254
Refresh grid:  https://github.com/volkanceylan/Serenity/issues/389

**Comment by AlperanQ** [comment]
Closing do to inactivity.
