### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by gpraveenraj** [volkanceylan/Serenity#3165]
Hi ,

I have following in my Dialog form.

public class PlanDetailsForm
    {
       [Hidden]
        public Int32 FeedId { get; set; }

        [Category("Day Part")]
        [LookupEditor(typeof(DayPartRow))]
        [QuarterWidth]
        public Int32 DayPartId { get; set; }
}

Here DayPart is lookup drop down list. I want to know how to set PlanDetailsForm FeedId='ES' and load daypart accordingly.

Here is my PlanDetailsDialog code

 @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class PlanDetailsDialog extends Serenity.EntityDialog<PlanDetailsRow, any> {
        protected getFormKey() { return PlanDetailsForm.formKey; }
        protected getIdProperty() { return PlanDetailsRow.idProperty; }
        protected getLocalTextPrefix() { return PlanDetailsRow.localTextPrefix; }
        protected getNameProperty() { return "Plan Details"; }
        protected getService() { return EndPoints.PlanDetailsService.baseUrl; }

        protected form = new PlanDetailsForm(this.idPrefix);
        constructor() {
            super();
        }
        public okClick: () => void;
    }

Please guide me

**Comment by gpraveenraj** [comment]
@volkanceylan Please guide me

**Comment by Estrusco** [comment]
But if FeedId is Int32 how you would set it to "ES"?

**Comment by gpraveenraj** [comment]
@Estrusco  sorry about typo.  The value  will be Integer only. ie., 20. (ES is mapped value of 20)

**Comment by Estrusco** [comment]
If you want load record with Id = 20, and in your record there is a value of DayPartId the lookup is automatically loaded.
If you want to set the Id you can act use loadByIdAndOpenDialog(id) but this must be called in a script before. E.g.

```html
<script>
    $('#button').click(function () {
        new PlanDetailsDialog().loadByIdAndOpenDialog(20);
    });
</script>
```

**Comment by gpraveenraj** [comment]
@Estrusco Thanks. But this DayPartId field is cascaded from another form field which needs to be set on loading of dialog. How do we achieve this?

**Comment by Estrusco** [comment]
You can override  protected beforeLoadEntity(entity: TItem): void; of Dialog and set your data in entity

**Comment by gpraveenraj** [comment]
@Estrusco . will this "beforeLoadEntity" work in New(Create) mode?

**Comment by Estrusco** [comment]
@gpraveenraj I don't understand what is goal that you want to reach.
See if this sample can help you

http://serenity.is/demo/BasicSamples/DefaultValuesInNewDialog

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts

**Comment by gpraveenraj** [comment]
@Estrusco Thanks. This gives some clue for me to achieve my goal to achieve default lookup load. I will try and get back to you.

**Comment by volkanceylan** [comment]
Please don't open another issue with Need Help...
