### ISSUE TITLE
Issue with form styles. i.e display: none is automatically added.

### ISSUE THREAD

**Issue by WasimAhmad** [volkanceylan/Serenity#3166]
hy volkanceylan! i have updated the project to the latest commit. after rebuilding the project and transforming T4 templates. facing issue in some forms.
1. Categories toolbar is not working.
2. css automatically added to the category div like style="display: none". how to fix it.

![inkeddisplay none_li](https://user-images.githubusercontent.com/5045365/35235983-8bd1ddf0-ffc7-11e7-8598-945c788f0e71.jpg)

**Comment by Estrusco** [comment]
If you updating from version before 3.2.0, there is a breaking change:

[BREAKING CHANGE] panels are hidden by default, so you need to .removeClass('hidden') after appending panel element to a container. see EntityDialogAsPanel sample Index.cshtml

See https://github.com/volkanceylan/Serenity/blob/master/CHANGELOG.md

**Comment by WasimAhmad** [comment]
ok thanks dear. will check it out.
