### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by gpraveenraj** [volkanceylan/Serenity#3167]
Am trying the below dynamic selection. and i see **.map** throws error. Can you please help?

this.form.DayofWeekId.changeSelect2(e => {
                var weekId = Q.toId(this.form.DayofWeekId.value);
                Q.notifyInfo('Change' + weekId);
                if (weekId != null) {
                    this.form.DayPartId.items = Metadata.DayPartRow.getLookup().items.filter(c => c.DayofWeek === weekId).map(l => { id: "c", text; "p" });
                }
            });

**Comment by dfaruque** [comment]
you may try this approach

```
Metadata.DayPartRow.getLookup().items.filter(c => c.DayofWeek === weekId)
                .forEach(m => {
                    this.form.DayPartId.addItem({ id: String(m.Id), text: m.Name, source: m });
                });
```

**Comment by gpraveenraj** [comment]
Thank you @dfaruque .  It works !
