### ISSUE TITLE
Issue in serene.is demo CancellableBulkAction

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#3168]
Hi @volkanceylan 

I experimented a strange issue in Serene.is demo in CancellableBulkAction ( http://serenity.is/demo/BasicSamples/CancellableBulkAction )
I don't able to check single checkbox to select and item. Only select all works. I tried with Chrome, IE and Edge.
The same problem is in http://serenity.is/demo/AdvancedSamples/LongRunningAction

Is only my problem?

**Comment by volkanceylan** [comment]
There is an ongoing Saltaralle to TypeScript conversion so such issues are expected from time to time

**Comment by Estrusco** [comment]
Well, then isn't real problem.
I close, thank  you :D
