### ISSUE TITLE
 How can I keep the language culture cookie for some time like 7 days?

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#317]
When I close webbrowser,$.cookie expired;   reopen webbrowser,luguage culture is still 'en'.
 How can I keep the language culture cookie for some time like 7 days?
$.cookie('LanguagePreference', select.val(), { path: Q$Config.applicationPath });

**Comment by ChenZhaobin** [comment]
Just change the code like below:
  $.cookie('LanguagePreference', select.val(), { path: Q$Config.applicationPath ,expires: 7 });

**Comment by volkanceylan** [comment]
Thanks, i changed default to 365 days now in Serene too, also for theme selection
