### ISSUE TITLE
Using jsZip Library

### ISSUE THREAD

**Issue by WasimAhmad** [volkanceylan/Serenity#3170]
Help Needed!
I am using jszip for packing and downloading files. but i think i m not using is properly. because i m not getting the intellisense.
1. i have install jszip using nuget.
2. i have install jszip typings using npm install @types/jszip --save (not --save-dev because in packages other @types are install as dependencies, i don't know way)
3. impted js in _LayoutHead.cshtml.

download is working but i want to know the proper way to use a JavaScript library having type definitions. so that i can have the intellisense.

**Comment by WasimAhmad** [comment]
issue resolved by exporting module like this 

declare module "JSZip" {
    export = JSZip;
}


instead of 

//export = JSZip;

**Comment by WasimAhmad** [comment]
thanks to me 👍

**Comment by volkanceylan** [comment]
It's declaration file probably uses module syntax instead of namespace syntax
