### ISSUE TITLE
Upgrade from StartSharp

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3172]
Question here !

with last release (3.4) and new themes, do i have to manually get the themes files from startsharp sources (not updated yet) or do we have a special nuget access to  keep our application updated.

Many thanks once again. This framework is pure gem.

**Comment by volkanceylan** [comment]
You should get them from latest source, there is no special NuGet package for StartSharp (or Serene)

**Comment by kilroyFR** [comment]
ok thanks !
