### ISSUE TITLE
CustomFormatter and Display Enum Text

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3173]
hey, 

I have defined a : 
```
[EnumKey("MyCustomType")]
public enum MyCustomType
{
  [Description("Local")]
  Local = 0,
  [Description("Global")]
  Global= 1
}
```
```
On my xxxRow.cs, i have replaced the custom type 👍 
    public MyCustomType? xxx
    {
      get { return (MyCustomType)Fields.xxx[this]; }
      set { Fields.xxx[this] = (Int16)value; }
    }
```

I would like to display an ICON + enum text. 
So i have created a custom formatter (used in a column defined in xxxColumns.cs), i would like to display  the  text of the Enum and not the ctx.value that is always displaying the numeric value.

Is there a way to do this ?
On the Orders sample the Shipper value is a string and not an enum.
If i wanted to display only text, displaying the MyCustomType correctly displays the Enum text.
In my application i would like to display both  : icon + enum text.

Thanks for any help.

**Comment by minhhungit** [comment]
I think you have to create a custom slickgrid formatter, you can read some examples of formatter at here:
https://github.com/volkanceylan/Serenity/wiki/SlickGrid-Formatters

**Comment by volkanceylan** [comment]
You should call EnumFormatter.format(MyProject.MyModule.MyEnum, ctx.value)

**Comment by kilroyFR** [comment]
@minhhungit : it 's already a slick grid custom formatter but it's the syntax to access Enums label i was looking for.

Many thanks Volkan. that's exactly what i was looking for.
