### ISSUE TITLE
Creating a Workflow Application

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3174]
Hello,
If I intend to create a workflow application where there will be approvals, how will I be able to achieve this in serenity? For example, if I want to be able to create a leave management system so that people can request for leave and have it approved by their superiors, what is the best way to carry this out in a serenity project?

**Comment by wldkrd1** [comment]
Hi!
This isn't the appropriate forum for this kind of request (this is more for reporting bugs in Serenity). But to answer your question in a general way:

- figure out the desired workflows for each type of user
- figure out the data you need to capture
- design your database schema accordingly
- sergen your tables into your app
- modify business logic and UI as necessary

Good luck!

**Comment by gfo2007** [comment]
Thanks for the reply. Please where are such questions asked? Slack?

**Comment by volkanceylan** [comment]
Yes slack is more suitable for wishes, guidance etc.
