### ISSUE TITLE
Form Wizard

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3175]
Hello,
How can I implement a form wizard in serenity?

**Comment by volkanceylan** [comment]
That's available in StartSharp:

http://serenity.is/demo/AdvancedSamples/OrderWizard#!1

**Comment by gfo2007** [comment]
Thanks. One quick question. If you develop an application in the community edition and you want to migrate to StartSharp, how easy will it be?

**Comment by kilroyFR** [comment]
I can answer this if you permit Volkan. 
I am in the process of switching from community to StartSharp and migration is nicely done. 
Every premium addition, javascript components, skins etc are located in dedicated directories, well, nicely organized the way it is in community edition.

**Comment by volkanceylan** [comment]
You may create a new project with same name of your old project and copy paste code you need.
