### ISSUE TITLE
how to display a LookupEditor in dashboard

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#3176]
Hi guys,
here is the scenario:
I have LocationRow.cs that is decorated with LookupScript.
I have xyzRow.cs that has LocationId property which is decorated with [LookupEditor(typeof(LocationRow))] .  This make this property show up as a select list in the UI.
I want the same Location select list in the Dashboard, whose selected value will be bound to the LocationId property in the DashboardPageModel.  
All help will be appreciated.
Thanks

**Comment by dudeman972** [comment]
Hi @volkanceylan, 
When you have a moment if you can please look into this.
Thanks

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/3140

**Comment by dudeman972** [comment]
Thanks Volkan :)
