### ISSUE TITLE
Refresh grid on closing a custom dialog

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3179]
Hi all,

I have a grid, where I am allowing bulk Actions (a column with checkboxes where the user can select one ore more rows).

On click of a custom button within the toolbar I open a custom Dialog (the original Dialog generated by sergen is used when clicking on a single row) where the user can Chose an Action with the bulk-selected
rows.

On click on a "execute Action" button within the custom Dialog, the bulk Action is performed against the selected rows and the Dialog is being closed.

**Problem:**
On closing the Dialog, the underlying grid is not refreshed and does not reflect the bulk Change. A click on the refresh button near the quick search field does bring up the changes.

**Question:**
How can I refresh the grid after closing the custom Dialog.

**Hint:**
I have read the following commenct of @Estrusco in the following issue: #2736 but cannot find the **yourGridEditor** part of his Input there:

```ts
this.yourGridEditor.refresh();
 this.yourGridEditor.element.triggerHandler('layout');
```

I don't find any *GridEditor for any of my grids.

So how can I refresh the underlying grid from within the Dialog code?

Thanks for your help and with Kind regards,

John

**Comment by kilroyFR** [comment]
I would search on GridEditorBase as it works (when editing OrderDetail List when closing popup dialog that automatically update detail grid.

**Comment by Estrusco** [comment]
At click event, try this

```ts
    var dlg = new YourNamespace.XYZ_dialog();
    dlg.loadNewAndOpenDialog(); // or what you use

    // This update the grid at dialog save
    this.initDialog(dlg);
```

or


```ts
    var dlg = new YourNamespace.XYZ_dialog();
    dlg.loadNewAndOpenDialog();
    Serenity.SubDialogHelper.bindToDataChange(ins, this, (e, dci) => {
        this.refresh();
    }, true);
```

**Comment by JohnRanger** [comment]
Hi @Estrusco ,

I have tried both of your recommendations but None worked.

the 1st: this.initDialog(dlg) gets already triggered when opening the Dialog (meaning that the execution does not wait at dlg.loadNewAndOpenDialog();

the 2nd: this.refresh() never gets triggered (I debugged it). The reason may be because this is a custom Dialog which does not directly save anything like the normal xyzDialog into one row but it updates in the afterSave Event some fields within the selected rows based on some checked/unchecked checkboxes within the custom dialog.

I also have searched to explicitely trigger a data changed Event from within the Dialog but didn't find anything like this.

Do you have any further ideas how to trigger a grid refresh after closing the custom Dialog? (e.g. how to triger the datachanged Event so that the subialoghelper.bindToDataChange callback can be triggered from the inside of the Dialog?)

@kilroyFR : I will try your recommendation also and give Feedback here when I found a solution.

Thanks for all your help and

with Kind regards,

John

**Comment by minhhungit** [comment]
Try using a trigger, read more at here:
Trigger: #1254
Refresh grid: #389

**Comment by JohnRanger** [comment]
For all which do have the same challenge:

The solution of @minhhungit is the solution for this.

For reference, I post here the complete Code: (this has to be put in the onClick Event of the button within xyzGrid:

```ts

                            var dialog = new ResetClientPrintQueuesDialogBulk();
                            dialog.SendSelected(selectedOutput);

                            dialog.element.bind('dialogclose', () => {
                                // *** This is triggered after closing dialog ***
                                this.rowSelection.resetCheckedAndRefresh();
                            });

                            dialog.loadNewAndOpenDialog();
```
Hope this helps somebody.

With Kind regards,

John

**Comment by fwd079** [comment]
> At click event, try this
> 
> ```ts
>     var dlg = new YourNamespace.XYZ_dialog();
>     dlg.loadNewAndOpenDialog(); // or what you use
> 
>     // This update the grid at dialog save
>     this.initDialog(dlg);
> ```
> 
> or
> 
> ```ts
>     var dlg = new YourNamespace.XYZ_dialog();
>     dlg.loadNewAndOpenDialog();
>     Serenity.SubDialogHelper.bindToDataChange(dlg, this, (e, dci) => {
>         this.refresh();
>     }, true);
> ```
Thank you for pointing in right direction.

This worked for me:

```typescript
let dialog = new DetailsDialog();
this.initDialog(dialog);
dialog.dialogOpen();
```

Kind Regards.
