### ISSUE TITLE
Customer Dialog Template Overlap

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#318]
I'm having an issue with a Dialog Template overlap that seems to be ghosting around and I can't figure out where to remove it from. 

I created most of my tables before removing the Northwind Database and Samples. At the time there seemed to have been a overlap where my own Customer table in Modules/MyProject/Customer was overlapping with the Northwind Customer dialog template. After I removed all of the Northwind and samples data, per manual, I now have an odd Dialog template that has broken tab links yet I can't find where it's feeding from. I attached a screen shot. 

As a side note, I did notice that every time I rebuild the MVC.cs file also re-adds the Northwind Class, no matter how many times I've removed it. I've ran up and down the files making sure to scrub out Northwind and have yet to find it. 

![customerdialogtemplateoverlap](https://cloud.githubusercontent.com/assets/16759829/13324461/e061abc6-dbab-11e5-87ea-5a107e1bd6a0.png)

**Comment by volkanceylan** [comment]
You have Northwind folder in disk. Use file explorer to delete files.

**Comment by sayuga** [comment]
Damn. So simple ....I completely forgot about that. sorry for the troubles.

**Comment by volkanceylan** [comment]
Np. If you dont want templates got mixed you can prefix them with namespaces. E.g. Northwind.CustomerDialog.Template.html

**Comment by sayuga** [comment]
I know but since I was planning on getting rid of Northwind anyway I didn't bother. I just haven't finished scrubbing out the disk side of things due to laziness since I'm still developing the platform. I'm planning on redoing a number templates we need internally anyhow so I figured I'd deal with it then,.
