### ISSUE TITLE
Category on XYZForm.cs

### ISSUE THREAD

**Issue by euclidesgc** [volkanceylan/Serenity#3180]
Hi @volkanceylan , first, thanks for your beautiful work. 
My name is Wivison and I'm a big fan!
But, what happened with the categorys on form? 
Its here but not show correctly!
Look the print I have made:
**Before:**
![before](https://user-images.githubusercontent.com/12780402/35418163-84abd022-020f-11e8-9192-9329b6a0e592.png)
**After**
![after](https://user-images.githubusercontent.com/12780402/35418175-938c6c96-020f-11e8-8e00-588c9a7e28e1.png)
Thanks for all!

**Comment by hairangsua** [comment]
this.yourTabPropertyGrid = new Serenity.PropertyGrid(this.byId("yourTabPropertyGrid"), {
                items: Q.getForm(YourForm.formKey),
                useCategories: true,
                idPrefix: this.idPrefix
            });

**Comment by euclidesgc** [comment]
Sério?! Era tão fácil antes. Este exemplo não parece correto...
Antes colocávamos apenas colocar a anotaçao [Category("XXX")]

**Comment by hairangsua** [comment]
Can u speak English? @@

**Comment by euclidesgc** [comment]
Thanks for listening. I'll check.

**Comment by volkanceylan** [comment]
use categories default was changed during TypeScript port, fixed in 3.4.1
