### ISSUE TITLE
Draggable Events cannot drop into calendar 

### ISSUE THREAD

**Issue by HSME** [volkanceylan/Serenity#3181]
Hello,
The draggable events cannot drop into calendar even in demo.
And I see error "SCRIPT438: Object doesn't support property or method 'getClientRects' " every time I click on calendar page. How can I solve this problem?
Thank you

**Comment by brunobola** [comment]
Already discussed here: https://github.com/volkanceylan/Serenity/issues/1724

**Comment by volkanceylan** [comment]
I should probably update that component, meanwhile you should manually.

**Comment by HSME** [comment]
I tried full calendar-3.8.0 but the problem still occur. Maybe I try to make it with another calendar.Thank you for your feedback.
