### ISSUE TITLE
Error ("entityId field is required!") when clicking on "Apply Changes" before saving (Oracle Db + Trigger) 

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3186]
I know there is another topic about his subject and problem is linked to using GUID column type.
So far i am using Oracle DB with standard fields.
Using 'Apply Changes' raises an exception (trigger not being fired) but record is created.
So when i click on Update button i got a Duplicate record.

Anyone here is working with Oracle and managed this (as IDENTITY field type is not existing, i normally use the TRIGGER before insert to get next ID (sequence)). Thanks all

**Comment by volkanceylan** [comment]
You should set that to Insertable(false), Updatable(false) and set that fields value on SetInternalFields method of your SaveHandler, if (IsCreate)

**Comment by kilroyFR** [comment]
the problem was finally fixed setting the 'IDENTITY' attribute on my column. This way during Apply-changes  the before insert trigger seems to be fired and value set correctly (so either Save or ApplyChanges work even on creation).
(My DB column is simple NUMBER column + trigger to set column value from a sequence).

Many thanks
