### ISSUE TITLE
Bag (ImageUloadBehavior)

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#319]
1) When you delete record with image , image is not actually deleted from the folder
2) When you add image and close dialog without changing temp files don't deleted

**Comment by volkanceylan** [comment]
It should be with recent versions, what is Serenity version.

**Comment by volkanceylan** [comment]
Btw its bug not bag and you shouldnt decide if it is a bug yourself.

**Comment by BolatovAlau** [comment]
Sorry

**Comment by BolatovAlau** [comment]
How to know version of curent serenity

**Comment by volkanceylan** [comment]
Update to latest please. It will delete after.
