### ISSUE TITLE
[Serenity Version -> 3.4.3] Time is not displayed

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#3190]
Hi everyone,

yesterday, I updated Serenity.Web at latest version and I realized that in my grids I don't see the time anymore.
Before, I had date + time, now I've only date.

Now, I've that.

![immagine](https://user-images.githubusercontent.com/22232670/35576217-be6bb926-05de-11e8-85a9-26aa8e107e2c.png)

In my XYRow.cs, I've the **DisplayFormat** attribute with this format **("dd/MM/yyyy hh:mm:ss")**.

Could anyone explain me why ?

Thanks all for your time :)

Chiara

**Comment by volkanceylan** [comment]
This is a bug, will be fixed in 3.4.4

**Comment by volkanceylan** [comment]
Meanwhile, i recommend using HH (e.g. 24 hours) not hh (12 hours)

**Comment by kjaraa** [comment]
Ok, thanks :)
