### ISSUE TITLE
Different Dialog/Form for Add/Edit

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#3191]
Is there a way to get a different dialog type for add and edit?  I have some fields that are only really applicable for a new instance and some that are only applicable for an existing instance.

**Comment by hairangsua** [comment]
I think u can try this.isEditMode() or this.isNew() on updateInterface to hide some field

**Comment by Estrusco** [comment]
If you need to hide or show some fields in new or update, you can use HideOnInsert or HideOnUpdate attributes in your xyzRow.cs (or xyzForm.cs).
If your dialog is completely different, you can create another xyzDialog.ts and call it in protected addButtonClick()

**Comment by leahmayschneider** [comment]
Thanks so much.  I can't believe I didn't think of HideOnInsert and HideOnUpdate.
