### ISSUE TITLE
Adding HTML onload to dashboard <body>

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#3194]
In the DashboardIndex.cshtml there is no `<body>` div. I'm trying to add an `onload` to it. Any idea on how to accomplish this? I've seen the body in the development elements screen via the browser I'm testing in but can't seem to figure out how to get access to editing it.

**Comment by JoshDiDuca** [comment]
You'll find the <body> in the _Layout.cshtml.

If you're trying to execute Javascript code when loading the dashboard page, you could add a script tag and simply call the code in there. Like it's done on this page:

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerIndex.cshtml

**Comment by z-combs** [comment]
Perfect, thanks. It's still not acting the way I would expect but it seems like everything that I was looking for here is working.
