### ISSUE TITLE
Column attribute in getColumns()

### ISSUE THREAD

**Issue by JoshDiDuca** [volkanceylan/Serenity#3195]
Hi there,

I was just wondering if there's any way to get data from attributes in the Columns.cs? 

Such as something like this suedo code (Example not related to what I'm actually trying to do): 

Columns.cs
```
        [ColumnColor("ff0000")]
        public DateTime Date { get; set; }
```

Grid.ts
```
        protected getColumns() {
            var columns = super.getColumns();
            var dateColumnColor = Q.first(columns, x => x.field === "Date").sourceItem["columnColor"];
            return columns;
        }
```

Thanks, suggestions appreciated.

**Comment by volkanceylan** [comment]
You should write a formatter, that accepts a color option

**Comment by JoshDiDuca** [comment]
Hi Volkanceylan,

Hope you're having a nice day, thanks for your response. Unfortunately, I couldn't use a formatter in this situation as I was already using a formatter in the Grid.ts which referenced variables from within the class. 

I managed to find another way to do what I needed though, thank you for your time.
