### ISSUE TITLE
[UX Issue]: Page index is not reverted to 1 after applying the filter

### ISSUE THREAD

**Issue by Febriantos** [volkanceylan/Serenity#3198]
Hi all,

It would be nice if we could fix this UX issue. 

The default paging number is not reverted to 1 after applying the filter.

How to replicate:
1. Go to http://serenity.is/demo/Northwind/Order
2. Press button pager "Last"
3. Go to Customer Filter
4. Select one of the customer name. E.g: Alfreds Futterkiste [ALFKI]
5. Grid is showing empty record and the pager is showing Page "9/1"

The expected result is the Page index should be reverted back to 1 instead of 9

Thank you.

![image](https://user-images.githubusercontent.com/20570367/35652312-e1cb8b3a-0697-11e8-9363-0dc9ba6474a8.png)

Related with issue: https://github.com/volkanceylan/Serenity/issues/2177

**Comment by Febriantos** [comment]
My work around:

protected quickFilterChange(e: JQueryEventObject): void {
	super.quickFilterChange(e);

	let currentPage = Number(this.element.find('input.slick-pg-current').val());
	let btnFirst = this.element.find('div.slick-pg-first');
	if (currentPage > 1 && btnFirst)
		btnFirst.click();
}

It would be nice if we can include this by default.

**Comment by volkanceylan** [comment]
I agree that's confusing, this commit should fix that:

d1646e9de64625b06b63e04ed613f5ab346ee634

It also does for sorting, quick filtering, advanced filtering

**Comment by Febriantos** [comment]
You are fast, thank you Volkanceylan.
