### ISSUE TITLE
Multi level left joins: Origin vs Expression

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#3199]
Dear @volkanceylan,
I'm progressively migrating from the legacy LeftJoin / Expression mechanism to the new Origin based one.
I'm having some trouble to manage multiple level joins: for example I'm used to do something like that
			
    [DisplayName("Country"), ForeignKey("[dbo].[Countries]", "Id"), LeftJoin("jCountry")]
    public Int32? CountryId
    {
        get { return Fields.CountryId[this]; }
        set { Fields.CountryId[this] = value; }
    }
    
    [DisplayName("Country"), Expression("jCountry.[Name]")]
    public String CountryName
    {
        get { return Fields.CountryName[this]; }
        set { Fields.CountryName[this] = value; }
    }
    
    [DisplayName("Region"), Expression("jCountry.[RegionId]"), ForeignKey("[dbo].[Regions]", "Id"), LeftJoin("jRegion")]
    public Int32? CountryRegionId
    {
        get { return Fields.CountryRegionId[this]; }
        set { Fields.CountryRegionId[this] = value; }
    }
    
    [DisplayName("Region"), Expression("jRegion.[Name]")]
    public String RegionName
    {
        get { return Fields.RegionName[this]; }
        set { Fields.RegionName[this] = value; }
    }

so CountryRegionId is retrieved with a left join on Countries table, but it's also used to join with "Regions" table, in order to retrieve RegionName (for example).
The syntax above is perfectly working, but I'm not able to do the same thing with the Origin attribute syntax:

    [DisplayName("Country"), ForeignKey(typeof(CountryRow)), LeftJoin("jCountry")]
    public Int32? CountryId
    {
        get { return Fields.CountryId[this]; }
        set { Fields.CountryId[this] = value; }
    }
    
    [DisplayName("Country"), Origin("jCountry")]
    public String CountryName
    {
        get { return Fields.CountryName[this]; }
        set { Fields.CountryName[this] = value; }
    }
    
    [DisplayName("Region"), Origin("jCountry"), ForeignKey(typeof(RegionRow)), LeftJoin("jRegion")]
    public Int32? CountryRegionId
    {
        get { return Fields.CountryRegionId[this]; }
        set { Fields.CountryRegionId[this] = value; }
    }
    
    [DisplayName("Region"), Origin("jRegion")]
    public String RegionName
    {
        get { return Fields.RegionName[this]; }
        set { Fields.RegionName[this] = value; }
    }

And then, while transforming T4 templates, I get this:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'x.y.Entities.EquipmentRow' threw an exception. ---> System.ArgumentOutOfRangeException: Property 'RegionName' on row type 'EquipmentRow' has a [Origin] attribute, but its corresponding property 'RegionName' on row type 'RegionRow' is not found!

The name of the field on the Regions table is "Name" and not "RegionName", but if I'm not wrong, the pattern for the fields name should be EntityFieldname, so RegionName should be fine.

I'm doing something wrong or multilevel join isn't supported with the Origin attribute?

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Did you try Origin("jRegion", "Name")

**Comment by marcobisio** [comment]
Just tried: it's working!
This is a workaround or just the way it should work? I just want to be sure that I'm using the right approach and the proper field naming convention!

Thanks!

**Comment by volkanceylan** [comment]
I didnt test but if your property name was CountryRegionName it could be able to match Name fielf in RegionRow with that. As you are using RegionName, it searches for a property with that exact name.

**Comment by volkanceylan** [comment]
You could also use LeftJoin("jRegion", PropertyPrefix = "Region")

**Comment by marcobisio** [comment]
I tried with "CountryRegionName": it works like a charm and it make perfectly sense: one more join level involves one more prefix in the name field. Nice!

Thank you very much @volkanceylan 
Bye
