### ISSUE TITLE
How to filter LookupEditor by multiple values?

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#320]
Is there some way to assign multiple values to "FilterValue"?

FilterValue = {1,2}?

**Comment by volkanceylan** [comment]
No for this you need to subclass lookup editor

**Comment by brettbeard** [comment]
Okay, I have been looking into doing that but am not sure how to do it.  Is there an example somewhere?

**Comment by volkanceylan** [comment]
See LookupEditor source for how it derives from LookupEditorBase, then you just need to override GetItems and filter result with linq etc.

**Comment by volkanceylan** [comment]
I'll probably add a sample tomorrow.
