### ISSUE TITLE
Dialog not maximizing

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3200]
Need your time saving help with this

I have xxDialog.ts with maximizable() attribute set but when I run the Dialog is not maximized but the maximize button is enable and when i click on the button it maximizes. What i need is to open the dialog maximized by default. 

    @Serenity.Decorators.maximizable()
    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    @Serenity.Decorators.panel()
    export class CampaignDayEditorDialog extends Common.GridEditorDialog<CampaignDayRow> {
        protected getFormKey() { return CampaignDayForm.formKey; }
        protected getLocalTextPrefix() { return CampaignDayRow.localTextPrefix; }
        protected getNameProperty() { return CampaignDayRow.nameProperty; }
        protected form = new CampaignDayForm(this.idPrefix);

        constructor() {
            super();
            this.element.closest('.ui-dialog').find('.ui-dialog-titlebar-minimize').click();
        }
    }

**Comment by volkanceylan** [comment]
Write that under onDialogOpen not constructor, and its class is maximize not minimize

**Comment by ms4hafiz** [comment]
Thank you @volkanceylan 
I tried the following but still it is not maximizing

        dialogOpen() {
            this.element.closest('.ui-dialog').find('.ui-dialog-titlebar-maximize').click();
            }

![image](https://user-images.githubusercontent.com/20435849/35675634-5d590312-0766-11e8-972d-f37e4c58e2f0.png)

**Comment by volkanceylan** [comment]
@ms4hafiz, i wrote "onDialogOpen", you write "dialogOpen", please more care

**Comment by volkanceylan** [comment]
and don't forget to call super.onDialogOpen()

**Comment by ms4hafiz** [comment]
Thanks 👍 
It works now :)
