### ISSUE TITLE
Search in Grid not working

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3207]
Hi,

In my project we are displaying the grid by overriding the List method in Repository file by calling stored procedure. The list is displaying fine but the default search and sorting of fields in grid is not working. Can anyone please help me to make this work?

**Comment by AmuthaKondusamy** [comment]
This issue is also existing in Serenity Demo-  in Basic Samples -Grids -Stored procedure Grid

**Comment by AmuthaKondusamy** [comment]
@volkanceylan  can you please help me on this?

**Comment by volkanceylan** [comment]
They are not supported with stored procs

**Comment by AmuthaKondusamy** [comment]
Is there any way to override the ApplySort(),ApplyContainsText() methods when using stored procedure?

**Comment by volkanceylan** [comment]
You can't use ListHandler with stored proc. You have the request, you have the sample, filter and sort according to the request params.

**Comment by AmuthaKondusamy** [comment]
Thank you so much @volkanceylan. It Works
