### ISSUE TITLE
Humanizer

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#321]
any thoughts to embed [Humanizer ](https://github.com/Humanizr/Humanizer) to be declarative, it would be great to add it

**Comment by volkanceylan** [comment]
Integrate it for what? I'm using StringInflector for code generator. Anyway you can use it by adding NuGet reference.

**Comment by zerodev** [comment]
i meant to utilize some of its features like Number to words on row level , somethign like this

[ToWords]
public int XXX ........

and int transorm to word 


https://github.com/Humanizr/Humanizer#number-to-words

**Comment by volkanceylan** [comment]
You can write formatter for it. I dont think its so common need.

**Comment by VictorTomaili** [comment]
Also you can write a Behavior for humanizer with attributes.

**Comment by zerodev** [comment]
my first thoughts was formatter , just wanted to check if there is another ways , will check both
