### ISSUE TITLE
Issue with lookup caching if table references itself

### ISSUE THREAD

**Issue by nootn** [volkanceylan/Serenity#3210]
I have a table which references itself using the id as a "parent id".  Here is a subset with the relevant columns from the migration:

    Create.Table("data_set").InSchema("meta")
    .WithColumn("data_set_id").AsInt32().PrimaryKey().Identity().NotNullable()
    .WithColumn("data_set_parent_id").AsInt32().Nullable().ForeignKey("fk_dataset_parent", "meta", "data_set", "data_set_id")
    ...

Then on the DataSetRow class, I define the lookup and use it:

    [ConnectionKey("Default"), TableName("[meta].[data_set]")]
    [DisplayName("Data Set"), InstanceName("Data Set"), TwoLevelCached]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [LookupScript("Lookups.DataSet")]
    public sealed class DataSetRow : Row, IIdRow, INameRow
    {
        [DisplayName("Data Set Id"), Column("data_set_id"), Identity]
        public Int32? DataSetId
        {
            get { return Fields.DataSetId[this]; }
            set { Fields.DataSetId[this] = value; }
        }
        [DisplayName("Data Set Parent"), Column("data_set_parent_id"), ForeignKey("[meta].[data_set]", "data_set_id"), LeftJoin("jDataSetParent"), TextualField("DataSetParentDataSetCode")]
        [LookupEditor(typeof(DataSetRow))]
        public Int32? DataSetParentId
        {
            get { return Fields.DataSetParentId[this]; }
            set { Fields.DataSetParentId[this] = value; }
        }
    ...

If I then add a new item, and go to add another item - the one I just added will not show up:
![image](https://user-images.githubusercontent.com/1258499/35776717-7e72aa4c-09ed-11e8-8a20-f950a0686605.png)

If I use the browser console and do `Q.getLookup("Lookups.DataSet")` it also is not returned.

The only way to get it to come up is to refresh the browser, then it will show.

**Comment by volkanceylan** [comment]
You need to call Q.reloadLookup, search this in prior issues.

**Comment by nootn** [comment]
If anyone else is interested in the exact answer... if you have a parent/child relationship, edit the XDiaglog.ts (where "X" is your entity name) adding this:

`        onSaveSuccess(response) {
`            super.onSaveSuccess(response);
`
`            Q.reloadLookup('X');
`        }
`
