### ISSUE TITLE
How can i change login after page ?

### ISSUE THREAD

**Issue by safakseyrek** [volkanceylan/Serenity#3211]
How can i change login after page ?

**Comment by minhhungit** [comment]
I don't know how to change login after page, but if you want to change page after login, read this https://github.com/volkanceylan/Serenity/issues/3150#issuecomment-358113972 😄

**Comment by safakseyrek** [comment]
After logging in, it is redirected to the dashboard page. I want to redirect to another controller.

**Comment by ms4hafiz** [comment]
a simple one
Go to Modules>Common>Dashboard and open DashboardPage.cs 
then remove  Route("~/") 
then add following on Index controller of your desired page to open as I did for customer as example.

**[Authorize, HttpGet, Route("~/")]**

     [RoutePrefix("Northwind/Customer"), Route("{action=index}")]
    [PageAuthorize(typeof(Entities.CustomerRow))]
    public class CustomerController : Controller
    {
        [Authorize, HttpGet, Route("~/")]
        public ActionResult Index()
        {
            return View(MVC.Views.Northwind.Customer.CustomerIndex);
        }
    }

**Comment by safakseyrek** [comment]
Hey thanks answer,
but 
error ; 

![err](https://user-images.githubusercontent.com/8484502/35847128-60425016-0b2a-11e8-8285-a9db12bf7fad.png)

solution explorer ;

![tree](https://user-images.githubusercontent.com/8484502/35847142-68f6d0b0-0b2a-11e8-96c3-3a8c6b539729.png)

**Comment by ms4hafiz** [comment]
Apply this on the controller you want to be default with this you have to remove or change the Dashboard page.

        [Authorize, HttpGet, Route("~/")]

**Comment by volkanceylan** [comment]
@safakseyrek use a mvc book please
