### ISSUE TITLE
Using another table name than 'Users' in database

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#3212]
Hi. It seems to be possible to change the default names for the security tables, like so:
public RowFields() : base("MySerenityRoles")
public RowFields() : base("MySerenityUserPermissions")
etc
However, this is not possible with the Users table, since this: 
public RowFields() : base("MySerenityUsers")
Throws an exception : Tablename in row type UserRow can't be overridden by attribute!

It seems that it's because UserRow.RowFields inherits LogginrowFields which inherits RowFieldBase
I've tried this in vain: public RowFields() : base.RowFieldBase("MySerenityUsers")

what I read about two levels overrides usually suggest it's a bad idea,  
Is there a workaround and what would be the prefered way to uses another table name for Users?

Note: the use case is that I already have similar table names in the database.

**Comment by volkanceylan** [comment]
Check tablename attribute on top of your row, remove the one on constructor

**Comment by BravoSierra** [comment]
That was so simple and I tried the hard way first! Thanks Volkan.
