### ISSUE TITLE
MySql not working - shows "Failed to find or load the registered .Net Framework Data Provider." error

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#3214]
Hello,

i did all steps mention in "https://github.com/volkanceylan/serenity-guide/blob/master/mysql.md" this URL.
i am able to see tables in serenity code generator dialog and it generate all files as well. 

but when i run it shows error  "Failed to find or load the registered .Net Framework Data Provider." please see attach screen show 
![mysql error in seren](https://user-images.githubusercontent.com/31484362/35810451-ca087616-0ab1-11e8-9f54-956d3bc57f43.PNG)

facing issue in sqlErrorStore.cs file when it check SqlConnections.GetFactory(this.providerName);

Please let me know how to fix this issue?

**Comment by volkanceylan** [comment]
Install provider in your project, check .net docs and provider docs.

**Comment by ali-h2010** [comment]
I am getting similar error. I followed the guide https://github.com/volkanceylan/serenity-guide/blob/master/mysql.md

Error details in the screenshot:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/h1jz1Tw/My-SQLDATAProvider-Error.png" alt="My-SQLDATAProvider-Error" border="0"></a>

**Comment by ali-h2010** [comment]
Apparently, i needed to install MySQL connector for .NET
https://dev.mysql.com/downloads/connector/net/6.10.html
