### ISSUE TITLE
DateEditor/EditorOption("minValue", "now") ?

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3217]
Is there a way to programmatically specify a minValue (for a date field) that is not hard-coded in attributes ?

ex: I would like to set minimum value to current date/time by default (or any other date-time correctly formatted) ?

Thanks

**Comment by kilroyFR** [comment]
So far i made it works not using MinDate but adding : 
$("[name='ValidityStartDate']").datepicker("option", "minDate", new Date());

On dialog.ts constructor().
Seems to be the only way to do it (bypasssing attributes requiring const strings).
Thoughts ?

**Comment by reacharihant** [comment]
By using the above, I am able to set the minValue and maxValue for the datepicker. But the user can still go and edit the text that can be out of min-max range. How can I control this behavior or put validation that the date has be within the date range?
