### ISSUE TITLE
No connection string with key '' in configuration file!

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#3218]
I have add a connection string into web.config. 

`<connectionStrings>
<add name="Snapshot" connectionString="Server=94.94.94.94;Database=db;Uid=use5;Pwd=ppppp;CHARSET=utf8;convert zero datetime=True" providerName="MySql.Data.MySqlClient"  /> 
</connectionStrings>`

I used this connectionString for my row with ConnectionKey attribute but endpoint connections executed with Default.

And I want to check 
for testing purpose

I have add this piece of code in SiteInitialization.ApplicationStart

`public static void ApplicationStart()
        {
            try
            {
                SqlConnections.GetConnectionString("Snapshot").Dialect =
                    SqlServer2005Dialect.Instance;`

I got this error: No connection string with key Snapshot in configuration file!

This is simple serene project, no advanced modification. Why i am getting this error?

**Comment by WasimAhmad** [comment]
where should a connection string with the name of Default. as the default configuration of serenity.

**Comment by ademc** [comment]
I have removed default connection string from my first post. Here is complete version:

`<connectionStrings>
 <add name="Default" connectionString="Data Source=(LocalDb)\MSSqlLocalDB; Initial Catalog=Project1_Default_v1; Integrated Security=True" providerName="System.Data.SqlClient"/>
    <add name="Snapshot" connectionString="Server=94.94.94.94;Database=db;Uid=use5;Pwd=ppppp;CHARSET=utf8;convert zero datetime=True" providerName="MySql.Data.MySqlClient" />
</connectionStrings>
`

**Comment by volkanceylan** [comment]
You need to write line after CommonInitialization.Run as configuration subsystem is not initialized yet

**Comment by volkanceylan** [comment]
Serenity.Web.CommonInitialization.Run();
SqlConnections.GetConnectionString("Snapshot").Dialect = SqlServer2005Dialect.Instance

**Comment by ademc** [comment]
I got it. I have take this example from https://volkanceylan.gitbooks.io/serenity-guide/setting-connection-dialect.html
I guess little edit reqiured.
Thanks
