### ISSUE TITLE
Aggregate functions in Linq

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3222]
Hi,

Can anyone please help me on how to use aggregate functions in Linq?

**Comment by kilroyFR** [comment]
wow this is not related to Serenity at all and google is your friend for such questions (http://www.c-sharpcorner.com/article/aggregate-function-with-linq-in-c-sharp/)

**Comment by AmuthaKondusamy** [comment]
Hi,
Thanks @kilroyFR . 
Ya the solution which you suggested will work fine.
But, I need to first select Max(majorversion) with respect to Plan and then Max(Minorversion) with respect to Max(majorversion).
How to achieve this in serenity linq?

**Comment by AmuthaKondusamy** [comment]
I have found there is Sql.Max() (and also other aggregate functions) .Thank You
