### ISSUE TITLE
Multitenancy Issues

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3224]
Hi,
I am working on a multitenancy application. Strangely, when I am on the Users Grid and I try to open the User Dialog, I get the error attached in the image. Below is the detailed error as shown by Google Chrome.

![serenity error](https://user-images.githubusercontent.com/14317420/35947134-419e2aa6-0c5e-11e8-8c93-ac466108d35b.PNG)

{"Error":{"Code":"Required","Arguments":"entityId","Message":"entityId field is required!","Details":"Serenity.Services.ValidationError: entityId field is required!\r\n   at Serenity.Services.RetrieveRequestHandler`3.Process(IDbConnection connection, TRetrieveRequest request) in P:\\Sandbox\\StartSharp\\Serenity\\Serenity.Services\\RequestHandlers\\Retrieve\\RetrieveRequestHandler.cs:line 193\r\n   at xhr.Administration.Repositories.UserRepository.Retrieve(IDbConnection connection, RetrieveRequest request) in J:\\Visual Studio Projects\\xhr\\xhr\\xhr.Web\\Modules\\Administration\\User\\UserRepository.cs:line 54\r\n   at xhr.Administration.Endpoints.UserController.Retrieve(IDbConnection connection, RetrieveRequest request) in J:\\Visual Studio Projects\\xhr\\xhr\\xhr.Web\\Modules\\Administration\\User\\UserEndpoint.cs:line 49\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in P:\\Sandbox\\StartSharp\\Serenity\\Serenity.Web\\Mvc\\ServiceEndpoint.cs:line 155\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)"}}

**Comment by volkanceylan** [comment]
Create the tenants table.

**Comment by gfo2007** [comment]
Please the tenants table is already there and has always been there but this error keeps popping up. Is there something else that could be causing it?

**Comment by postonoh** [comment]
Can you post the data in the Tenants table
