### ISSUE TITLE
detail editor height

### ISSUE THREAD

**Issue by hairangsua** [volkanceylan/Serenity#3225]
![capture](https://user-images.githubusercontent.com/26143405/35953067-73011bc4-0cb5-11e8-9b9f-f6540d4f9ba1.PNG)

Hi everyOne.
how i can make this editor height grow with dialog height?
Thank for reading!

**Comment by minhhungit** [comment]
@hairangsua : read more at here https://github.com/volkanceylan/Serenity/issues/1729
