### ISSUE TITLE
Unique values in LookUp Editor

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3229]
Hi,

I have duplicate values in a particular field. while using lookup,I just need to select the unique values.
can anyone please help me out?

**Comment by AmuthaKondusamy** [comment]
@volkanceylan  can you please suggest me the solution?

**Comment by javaman63** [comment]
You have to create a YourCustomLookUpEditor and Override the PrepareQuery, using a Distinct on the SqlQuery

**Comment by AmuthaKondusamy** [comment]
Thank you @javaman63  It works
