### ISSUE TITLE
Is there a clone feature available?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#323]
Is there a way to clone a row and pass all the values to the form to be edited?

**Comment by volkanceylan** [comment]
Override UpdateInterface, cloneButton.Toggle(!IsNew) you ll get a clone button in dialog toolbar.

**Comment by swordz36** [comment]
Great I'll give this a try, I was looking for an interface like IClonable ti implement on the table row.

**Comment by volkanceylan** [comment]
Added a clone dialog sample in latest template
