### ISSUE TITLE
Update Table

### ISSUE THREAD

**Issue by GayathriSravya** [volkanceylan/Serenity#3232]
Hello, 
I am working on a project where there are Employee Registration, Employee Attendance Tables
Here my issue is when a new record is entered into Employee registration then it should automatically update in Employee Attendance.
Can anyone please help me out??

Regards,
Sravya.

**Comment by kilroyFR** [comment]
The simplest solution for this is using a trigger doing the job.

**Comment by GayathriSravya** [comment]
@kilroyFR  I am new to serenity can u please give me any referencelink

**Comment by karimhyatt** [comment]
Personally, I don't like triggers. makes the code difficult to read. 

You can also use the AfterSave() override in the SaveHandler (see the Multitenancy code in the guide for this) or create a method in your repository and call the XXXService when you click the save/update button. 

To create a new method in the repository, you will need to create your own request/response objects and hook it in to the XXXEndpoint (in the same way the Create/Update/Delete methods are). 

You can then use the c# code to insert new XXXRow the objects you need, using any of the data from the Employee registration row you just created.

Yet a 3rd way if the database is designed that way is to use LinkingSetRelation attribute on linked fields, but I have a feeling that won't work in your case.

**Comment by GayathriSravya** [comment]
@kilroyFR  Trigger not Working

**Comment by GayathriSravya** [comment]
@karimhyatt Thanks for responding will try and let u know

**Comment by kilroyFR** [comment]
Trigger after insert on main table should work.
