### ISSUE TITLE
Adding more UI/entities to Order Details!

### ISSUE THREAD

**Issue by amonragz** [volkanceylan/Serenity#3234]
Hi community,

How can I add more entities to the UI, since I was able to see .TS files with right blue arrow, but if I add manually I'm seeing a C# at the top of sheet, is there any tool to create/generate all those files? I want to add a new table called 'Additional Cost' and populate with a UI below of Order Detail. But I can see about 12 o 13 files regarding to OrderDetail for example Row, Column, Service, Dialog, EndPoint, Form, cshtml, page, Repository. can you provide a tutorial to add more classes, please? and the relational model.

**Comment by brunobola** [comment]
Please read the tutorial first.

**Comment by amonragz** [comment]
can you provide URL please?

**Comment by minhhungit** [comment]
@amonragz  Do you know how to google ?

**Comment by amonragz** [comment]
yup, thanks, can you help me with one issue? I was able to add more entities/tables but just wondering if you can help for once?

**Comment by minhhungit** [comment]
please read README page first, it is homepage of serenity github repository https://github.com/volkanceylan/Serenity
so after you read it, you will see something like this:
`See Serenity Developer Guide at https://www.gitbook.com/book/volkanceylan/serenity-guide for documentation, and step by step tutorials.`

**Comment by amonragz** [comment]
Got It Thank you!
