### ISSUE TITLE
Added new class/table but when click on 'New Order', nothing happens.

### ISSUE THREAD

**Issue by amonragz** [volkanceylan/Serenity#3236]
I'm experiencing a kind of error where i'm unable to move forward 'New Order' can you please provide assistance?

**Comment by brunobola** [comment]
@amonragz with that description of your error no one can help, what's your console errors ?
Have you done T4 transform and rebuild ?

**Comment by amonragz** [comment]
yup I've done that part, the part I'm experiencing issues:  Exception$
_error
:
Error at new Exception$ (http://localhost:11796/Scripts/saltarelle/mscorlib.js?v=AO_L_1E_BHK8K8k5pu8Fmg2:3218:16) at http://localhost:11796/Scripts/serenity/Serenity.Script.UI.js?v=iwLRTH3-QQAWtzKcY7UYIA2:4309:11 at AdditionalCostForm.w (http://localhost:11796/Scripts/serenity/Serenity.Script.UI.js?v=iwLRTH3-QQAWtzKcY7UYIA2:9564:35) at AdditionalCostForm.get [as AddCostID] (http://localhost:11796/Scripts/site/SIGO.Web.js?v=tkBX3xefPe0hCN8Nn4INEw2:7261:332) at new AdditionalCostDialog (http://localhost:11796/Scripts/site/SIGO.Web.js?v=tkBX3xefPe0hCN8Nn4INEw2:1529:28) at Function.Widget.create (http://localhost:11796/Scripts/serenity/Serenity.CoreLib.js?v=JSgGubkiwudNQrYkXBF-VQ2:2893:26) at AdditionalCostEditor.createEntityDialog (http://localhost:11796/Scripts/serenity/Serenity.Script.UI.js?v=iwLRTH3-QQAWtzKcY7UYIA2:8406:33) at Object.onClick (http://localhost:11796/Scripts/site/SIGO.Web.js?v=tkBX3xefPe0hCN8Nn4INEw2:777:35) at HTMLDivElement.<anonymous> (http://localhost:11796/Scripts/serenity/Serenity.Script.UI.js?v=iwLRTH3-QQAWtzKcY7UYIA2:10473:7) at HTMLDivElement.dispatch (http://localhost:11796/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:5201:27)
_innerException
:
null
_message
:
"Searching for widget of type 'Serenity.StringEditor' on a non-existent element! ()"

How to implement String Editor's where they need to be existing?

**Comment by volkanceylan** [comment]
You haven't transformed T4, or haven't check TypeScript errors.
