### ISSUE TITLE
LookupScript debugging

### ISSUE THREAD

**Issue by sottnik** [volkanceylan/Serenity#3238]
Hi serenitas
just a convenience question. Did you find a convenience way to debug lookupscripts? I find it very difficult almost impossible to trace that particular code. What I mean is, it is written in C# and then translated somehow (I don't get it how) to client side. Unfortunately I cannot find where it is and how to set breakpoints.
I have some issues in results of my custom lookup scripts (derived from rowlookupscript) and cannot find out what is the problem.

**Comment by minhhungit** [comment]
- First, you will need to know how to debug serenity, read it here  https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_debugging_with_serenity_sources.html

- With lookup script, find and check this:
![image](https://user-images.githubusercontent.com/2279508/36027224-fc7c0cde-0dcc-11e8-9e7c-6f13a93efdec.png)

**Comment by sottnik** [comment]
Thanks for your response. I have no problems to trace server side even into serenity. I have also no problem to trace client side as long as it is my code. I have problem to trace C# code written by me, translated somehow to client code by serenity.

**Comment by minhhungit** [comment]
I can not help if I can not see your code

**Comment by sottnik** [comment]
Lookup script definition:

    [LookupScript("R5.ProductLookupByPortfolio",Expiration = -1)]
    public class ProductLookupByPortfolio : RowLookupScript<ProductRow>
    {
        public ProductLookupByPortfolio()
        {
            IdField = ProductRow.Fields.Id.PropertyName;
            TextField = ProductRow.Fields.Name.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            if (Authorization.HasPermission("Administration"))
            {
                base.PrepareQuery(query);
                return;
            }
            var fld = ProductRow.Fields;
            query
                .Select(fld.Id)
                .Select(fld.Name)
                .Where(
                    ListRequestHandlerHelper.GenerateWhereForFilter(
                        "PRODUCT"
                        , Authorization.UserId
                        , UserRepository.GetCurrentDsId()
                    )
                );
        }

        protected override void ApplyOrder(SqlQuery query)
        {
            query.OrderBy(ProductRow.Fields.Name);
        }
    }

The lookup script is consumed like this:

MyForm.cs:

...
`[ReadPermission("Fact:ProductReader"), LookupEditor(typeof(Scripts.ProductLookupByPortfolio))]`
`public String Product { get; set; }`
...
and here:

MyRow.cs:
`[DisplayName("PRODUCT"), Expression("jProduct.[NAME]"),LookupFiltering("R5.ProductLookupByPortfolio")]`
`        public String ProductName
        {
            get { return Fields.ProductName[this]; }
            set { Fields.ProductName[this] = value; }
        }`
...

I cannot figure out how to trace `ProductLookupByPortfolio.PrepareQuery` method.

**Comment by minhhungit** [comment]
I usually create getItems method:

```csharp
[LookupScript("CustomLookup.SupplierLocations", Expiration = 10 * 60)]
    public class SupplierLocationLookup : Serenity.Web.LookupScript
    {
        public SupplierLocationLookup()
        {
            this.IdField = "InventoryLocationId";
            this.TextField = "InventoryLocationId";
            this.getItems = this.GetLookupItems; // <===================== here
        }

        protected virtual IEnumerable GetLookupItems()
        {
            using (var connection = SqlConnections.NewFor<SupplierLocationRow>())
            {
                var query = new SqlQuery().From(SupplierLocationRow.Fields)
                    .Select(SupplierLocationRow.Fields.InventoryLocationId)
                    .Select(SupplierLocationRow.Fields.SupplierId);

                return connection.Query(query);
            }
        }
    }
``` 

About PrepareQuery, try this:
```csharp
protected override void PrepareQuery(SqlQuery query)
{
    base.PrepareQuery(query);

    var fld = xyzYourRow.Fields;
    // add your code here
    query.OrderBy(fld.YourSortField, true);
}


```

**Comment by sottnik** [comment]
My problem is not whether my code is wrong or right. I can fix it if I know what it really does. My problem is I cannot debug it in VS. So I cannot see what is going wrong.

**Comment by minhhungit** [comment]
I don't know why you can't, but I can
![image](https://user-images.githubusercontent.com/2279508/36034188-d2eaca86-0de5-11e8-83ed-bc50fd3999c4.png)

maybe cache is problem

**Comment by sottnik** [comment]
Never mind. My wrong. This is again some weird VS behavior. I cannot debug any server code although all settings and profiles are set to debug. 
Actually that lookupscript code is never translates to client. It stays on the server.
