### ISSUE TITLE
Sidebar menu help needed

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3239]
Anybody I need your help with making the following menu setting in serenity.
I am not very much familiar with the menu setting.

![image](https://user-images.githubusercontent.com/20435849/36036062-737b9c7e-0dd6-11e8-99ae-de9804f0a5f6.png)

**Comment by kilroyFR** [comment]
In _Layout.cshtml on line:  
<body id="s-@(ViewData["PageId"])Page" class="@(ViewData["BodyClass"]) fixed sidebar-mini hold-transition skin-@theme@(hideNav ? " no-navigation" : " has-layout-event")@(rtl ? " rtl" : "")">

remove the 'fixed' style and you have it.

**Comment by ms4hafiz** [comment]
Thank you @kilroyFR
