### ISSUE TITLE
AdminLTE Widgets and Tables - Serenity Implementations

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#324]
What is good example to look at regarding implementing some of the AdminLTE Examples with Serenity data tags? 

To be more precise, I'm hoping to make use of the following widgets from both the Dashboard and AdminLTE Examples and would like a solid reference point: 

-DataTables with Full Features 
- Calendar
- Mailbox
- Quick email
- Chat box
- Recently Added
- Lock Screen 
- User Profile

**Comment by volkanceylan** [comment]
You can implement them as ordinary MVC pages. Might use some Serenity services. Serenity is complementary not alternative to Asp.Net MVC.

**Comment by sayuga** [comment]
Cool, that means I can play around with it more comfortably then. Thanks for the info.

**Comment by jsbUSMC** [comment]
@sayuga would you mind sharing an example of what you've done to implement these widgets? Did you end up writing Saltarelle import classes? Thank you.
