### ISSUE TITLE
Load Permission Tree without caching

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3240]
Hi,
I have a multitenancy application and I am trying to hide the Tenants permission from the Permission Tree on the Edit Permissions Dialog. The problem is that, when I log on with the default admin, the Tenants permissions on the Edit Permissions appears anc caches it. So when I log out and log in with a user belonging to a Tenant, it still shows the Tenant permission in the Edit Permissions dialog due to the cache.

How do I remove caching when loading Permissions on the Edit Permission Dialog?

**Comment by volkanceylan** [comment]
That permission should not be shown.
