### ISSUE TITLE
How to override afterLoadEntity() to set a date field with JsDate.Today;

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#3244]
Hi, this could be a basic question, but I am  Trying to override afterLoadEntity()  in one my entitydialog , but it is saying this 
Cannot find name 'afterLoadEntity()'  how can I include this to my ts file , 

Infact I am trying to reset my date in a cloneable entity using the below from Frequently asked
form.MyDateField.AsDate = JsDate.Today;
but it is not allowing me to access JsDate

**Comment by kilroyFR** [comment]
did you try using : 

> new Date()

 instead of JsDate.Today

ex: That the way i am using it to set mindate in datepicker to current: 
$("[name='OperationStartDate']").datepicker("option", "minDate", new Date());

**Comment by Parbil** [comment]
It is a string field , so I am not able set it 

 export interface TransactionsRow {
        TranId?: number;
        TranDate?: string;

**Comment by kilroyFR** [comment]
If date string is correctly formatted (ISO) then using new date(mystring) should work.

**Comment by Estrusco** [comment]
If you want a date in string formate, use Q.formatDate(new Date()).
If you want parse a string in date, use Q.parseDate(s: string, dateOrder?: string):
See other utility function in Q.

**Comment by Parbil** [comment]
thanks @Estrusco
