### ISSUE TITLE
BOM characters getting added on build

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#3246]
Hi again :)
have no idea why this suddenly started but now everytime i build or transform t4 templates my xyz.Web.js files get these BOM characters added right in the beginning  "ï»¿" ... this forces me to delete them then build again or less i get xyz.web.js is undefined and nothing works.
i tried telling vs to save the file as UTF 8 without signature as per what i read online but it seems serene keeps putting it back or something..
any ideas??
thanks

**Comment by volkanceylan** [comment]
Please report to TypeScript repo, it's bug in 2.7

**Comment by volkanceylan** [comment]
Serene doesn't put it, it's TypeScript compiler

**Comment by shakazulu89** [comment]
ok i did have a look there but just wasnt sure if its coming from serene or ts .. now i know thanks once again volkan.. ill post here my solution for others then close this issue

**Comment by volkanceylan** [comment]
I opened an issue now, for now you may remove emitBOM: true from tsconfig.json

https://github.com/Microsoft/TypeScript/issues/21878

**Comment by shakazulu89** [comment]
you good you ..  fixed it for me .. you want to leave this issue open for now?

**Comment by volkanceylan** [comment]
Yes, others might see and don't double report (hopefully :)

**Comment by shakazulu89** [comment]
wishful thinking :P

**Comment by xareas** [comment]
Add line to tsconfig.json
"emitBOM": false

**Comment by volkanceylan** [comment]
TypeScript 2.7.2 fixes this.
