### ISSUE TITLE
[Bug] QuickSearchInput.ts 

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#3248]
Dear @volkanceylan,
I found a little bug in QuickSearchInput.ts.
The constructor contains this:

    ...
    }, function (e: any) {
        e.preventDefault();
        this.$this.$fieldChanged = !(ss as any).referenceEquals(self.field, this.field.$);
        self.field = this.field.$;
        this.$this.$updateInputPlaceHolder();
        this.$this.checkIfValueChanged();
    }
    ...

but (I think) it should be:

    ...
    }, function (e: any) {
        e.preventDefault();
        this.$this.fieldChanged = !(ss as any).referenceEquals(self.field, this.field.$);
        self.field = this.field.$;
        this.$this.updateInputPlaceHolder();
        this.$this.checkIfValueChanged();
    }
    ...

I already tried the fix above and it's working fine!

Thank you very much
Bye

**Comment by dfaruque** [comment]
@marcobisio  you might send a pull request.

**Comment by marcobisio** [comment]
I know @dfaruque, but they are just a couple a dollar signs, so it seemed like an overkill!

**Comment by dfaruque** [comment]
Ok. I think it will be better to see the changes.

We have to read those 6 lines of code manually with our eyes to see the differences. And it take some time to identify the dollar signs.

BTW, it does not a big deal.

Thanks.

**Comment by volkanceylan** [comment]
That code is such a mess because of porting from Saltaralle and there is no out/ref params in javascript. Will fix that, thanks
