### ISSUE TITLE
Email Functionality

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#3253]
Hi there

I have been tasked with having email functionality on the application, I see that already there is mailbox functionality built in, my question is how can I get this to work as currently there are just interfaces. This functionality must link/integrate with gmail, meaning that whatever inbox, meetings/events,tasks etc on gmail must also appear on the website. I hope what I am requesting makes sense, how do I get started with this?

**Comment by wldkrd1** [comment]
This isn't a Serenity question, so I expect it will be closed soon. You'll have to either get very familiar with whatever API Google provides, or make heavy use of iframes to host gmail directly in your app.

**Comment by vinaykulkarni89** [comment]
You can use google API's as said by @wldkrd1 or even you can go with NuGet packages like Mailkit

**Comment by sshandu** [comment]
Thanks for the suggestion guys
