### ISSUE TITLE
Error after upgrading from 3.4.2 to 3.4.4 (ASPNETCORE)

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#3259]
Hi man, after updating using Nuget i get this error 
![image](https://user-images.githubusercontent.com/10474555/36213633-e128979a-11af-11e8-85e9-3c5e309a23f1.png)

**Comment by volkanceylan** [comment]
You're periodically having such issues. There is no such change, so better restore, reinstall and so on.

**Comment by Magik3a** [comment]
Last time i got exception from using SignalR alpha package, now even to remove that one the error continues 
you can check the build 
https://ci.appveyor.com/project/Magik3a/patientmanagement-admin

**Comment by volkanceylan** [comment]
And your sergen is 3.4.2 isn't it @Magik3a

**Comment by Magik3a** [comment]
Yep that was the problem! Sorry for stupid problem @volkanceylan
