### ISSUE TITLE
Sizing of dialogs

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#326]
I followed directions to change the dimensions of the dialog by changing the following style in site.less file. My changes do not have effect on changing the size of dialog box. I don't even see this style when inspecting the element. Many thanks in advance for pointing me in the right direction.

.s-ComplaintAttachmentDialog {
    > .size { .widthAndMin(350px); }
    .dialog-styles(@h: 560px, @l: 150px, @e: 400px);
    .s-PropertyGrid .categories { height: 560px; }
}

![2016-02-25_143526](https://cloud.githubusercontent.com/assets/17013052/13336324/0f2e9d7c-dbdb-11e5-9514-84075544e932.png)

**Comment by dzahler** [comment]
Hi,

It appears that your class selector for the dialog should be something like .s-Complaint-AttachmentDialog 


Take a look at the class that directly precedes s-Complaints-Complaint-AttachmentDialog in the class for the div. Your screen shot has a bunch of ellipses shortening the string.

David

**Comment by c9482** [comment]
The complete class is "ui-dialog ui-widget ui-widget-content ui-corner-all ui-front s-Dialog s-AttachmentDialog s-Complaints-Complaint-AttachmentDialog ui-draggable"

The "s-AttachmentDialog" and "s-Complaints-Complaint-AttachmentDialog" are not defined anywhere I can find.

Is there any other place besides site.less to look for these?

**Comment by c9482** [comment]
I know that I can just rename the class in site.less  to "s-AttachmentDialog" but I am wondering how these were generated and why the name went out of sync.

**Comment by volkanceylan** [comment]
They are generated from namespace and class name putting dashes instead of dots. Prefer s-Module-ClassName version.

**Comment by c9482** [comment]
Looks like class "s-ComplaintAttachmentDialog" was generated but "s-Complaints-Complaint-AttachmentDialog" was actually used on the page. I was hoping to find a template that has the reference to "s-Complaints-Complaint-AttachmentDialog" but I cannot - it's probably dynamic. How are the css class names attached to dialogs at runtime?

**Comment by volkanceylan** [comment]
As i explained in prior message its generated from your dialog class name and namespace. What is your dialog class name and namespace

**Comment by volkanceylan** [comment]
I guess its AttachmentDialog, and module is Complaint, and solution name is Complaints.

So your dialog has following classes:

s-AttachmentDialog
s-Complaint-AttachmentDialog
s-Complaints-Complaint-AttachmentDialog

I have no idea how you got .s-ComplaintAttachmentDialog unless you manually write it or changed dialog class name later.

**Comment by c9482** [comment]
Yes, I manually created ComplaintAttachmentDialog class. So, I guess, css will not be generated for manually created classes. Thanks.
