### ISSUE TITLE
Adding html options in the Lookup Editor

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#3261]
```
var data = [{
   id: 0,
   text: 'enhancement',
   html: '<div style="color:green">enhancement</div>'
}];
```

I want to customize lookupitem as in the example
Could you help.

**Comment by cengkaplan33** [comment]
Hi Oaltay, 
you can override "formatResult" method for html content or whatever you want.

![image](https://user-images.githubusercontent.com/3457947/36255875-c20fc24a-1261-11e8-9eca-3e166424ab1e.png)

**Comment by oaltay** [comment]
thanks

**Comment by Estrusco** [comment]
See this example in Wiki https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables

**Comment by fwd079** [comment]
> See this example in Wiki https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables

Above link doesn't work anymore. This one does:
[https://github.com/volkanceylan/Serenity/wiki/Lookup-Editors:-How-to-Create-Lookup-Editor-for-code-description-tables](https://github.com/volkanceylan/Serenity/wiki/Lookup-Editors:-How-to-Create-Lookup-Editor-for-code-description-tables)

Regards.
