### ISSUE TITLE
Serenity demo does not work right now

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#3262]
Hi @volkanceylan 
Could not load file or assembly 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies

![image](https://user-images.githubusercontent.com/2279508/36247461-aff2e72c-1266-11e8-81fd-a0cac9e8bc07.png)

**Comment by volkanceylan** [comment]
Thanks, just updated AspNetMvc, needed to update bindings in web.config
