### ISSUE TITLE
Q.Notify.xxx üzerindeki varsayılan Toastr Opsiyonlarına sabit opsiyon eklenmesi ricası :)

### ISSUE THREAD

**Issue by receptuna** [volkanceylan/Serenity#327]
Merhaba Volkan  bey @volkanceylan ,

Genel anlamda tost popupları çok geç kapanıyor ve dialogların close crossuna yapışıyorlar :)

ya timeout süresini düşürelim yada CloseButton = true özelliğini ekleseniz nası olur.

tamam Toastr implementi üzerine opsiyon verilebiliyor 
`Toastr.Success(message, "", GetToastrOptions());`

ama örnek savesuccess de sürekli sizin base classlardan override etmek zorunda kalıyoz bunu :)

![image](https://cloud.githubusercontent.com/assets/2880274/13353976/985c522c-dca0-11e5-82a4-e7f72c3c2640.png)

iyi çalışmalar.

**Comment by volkanceylan** [comment]
3bc04c10d438974e16f9b4956f1856edc4497c9d işiniz çözer herhalde

**Comment by receptuna** [comment]
teşekkürler @volkanceylan elinize sağlık.
