### ISSUE TITLE
Upgrade 3.4.4 -> 3.5.2

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#3271]
Hello everybody!
I have errors after the update. ((

in \Imports\ClientTypes\..\CodeGenerationHelpers.ttinclude missing FullName
```
foreach (var intf in type.Interfaces)
            externalType.Interfaces.Add(intf.FullName);
```
If I delete these lines, T4 has no errors, but the program does not work error:
**An error occured while trying to load dynamic script: ""!. Please check the error message displayed in the dialog below for more info.**
_Error HTTP 404.0 — A dynamic script with key is not found!
http://localhost:80/IUS/DynJS.axd/.js?undefined_

Help me please

**Comment by volkanceylan** [comment]
Some change in Mono.Cecil, replace externalType.Interfaces.Add(intf.FullName) with externalType.Interfaces.Add(intf.InterfaceType.FullName)

**Comment by xareas** [comment]
I get this error...
![image](https://user-images.githubusercontent.com/5817316/36377234-04aa6d8a-153c-11e8-9eee-6d8e69b3014c.png)

**Comment by Zahar661** [comment]
@volkanceylan T4 formed without errors! Thank you. 
http://localhost:80/DynJS.axd/.js?  still error

**Comment by Zahar661** [comment]
@xareas similar error

**Comment by volkanceylan** [comment]
Don't know, you'll need to debug or revert back to prior version

**Comment by Zahar661** [comment]
Can help?
In this case, everything seems to work, but the message crashes when the page is updated. if the message is closed then it can be used.
![image](https://user-images.githubusercontent.com/26430136/36378137-b1b18f74-158a-11e8-85fe-648889552c57.png)
![image](https://user-images.githubusercontent.com/26430136/36378162-cdf30000-158a-11e8-8e67-31fc1bcf1ff1.png)

**Comment by Zahar661** [comment]
in **_Layout.cshtml** comment _new IUS.Common.LanguageSelection($('#LanguageSelect'), 'ru');_   the error was gone

**Comment by volkanceylan** [comment]
Then you'll lose language selection dropdown, issue is possibly in Q.getLookupAsync

**Comment by Zahar661** [comment]
@volkanceylan Thank you! I understood this, but I turned it off and removed it from the template for a long time. I do not need this functionality!

**Comment by volkanceylan** [comment]
Please just test with 3.5.3 when released, i can't reproduce this but found the possible location. Then you can remove again :)

**Comment by Zahar661** [comment]
```
 function loadScriptAsync(url) {
            return Promise.resolve().then(function () {
                Q.blockUI(null);
                return Promise.resolve($.ajax(loadOptions(name, false))
                    .always(function () {
                    Q.blockUndo();
                }));
            }, null);
        }
```
In CoreLib
Here comes the error

return Promise.resolve($.ajax(loadOptions(name, false))
                    .always(function () {
                    Q.blockUndo();
                }));

**Comment by Zahar661** [comment]
I have 1 language only and that Russian

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/36381599-2e3b52d0-1597-11e8-98c2-a47c5e55a4c6.png)

**Comment by Zahar661** [comment]
in 3.5.3 does not work at all
![image](https://user-images.githubusercontent.com/26430136/36393190-a3e925de-15bf-11e8-979d-893c476ccdd0.png)

_The type "LocalText" is defined in the assembly, which is not referenced. You must add a link to the assembly "Serenity.Core, Version=3.5.3.0, Culture=neutral, PublicKeyToken=null"_

**Comment by volkanceylan** [comment]
I think you need to reinstall packages

**Comment by volkanceylan** [comment]
Also, the error you see is about your code, and /// references

**Comment by Zahar661** [comment]
This is my error in the code, 2 minutes and check the update

**Comment by Zahar661** [comment]
All works well! no mistakes! Thank you!
