### ISSUE TITLE
CheckTreeEditor :  getTreeItems and constructor

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#3273]
Hello all,

I am trying to pass a parameter (option) to the getTreeItems method of the CheckTreeEditor. When debugging I notice that the getTreeItems method is executed **before** the constructor method, in which the opt? parameter is set. 
Does anyone know how to solve this ?

Greetings

**Comment by she-ll-b-rite** [comment]
I reckon you might not be passing the options to the super class correctly, as options are assigned before getTreeItems is invoked in all my projects and testing.

```
export interface DummyOptions {
        dummy: string;
}

export class DummyCheckEditor extends Serenity.CheckTreeEditor<Serenity.CheckTreeItem<any>, DummyOptions> {
        constructor(container: JQuery, opts?: DummyOptions) {
            // make sure you pass the options/params to the super class & should work as expected.
            super(container, opts);
        }

        protected getTreeItems() {
            // this should have the value passed in as a parameter
            this.options.dummy;
            ...
        }
}
```

**Comment by GreenUtil** [comment]
Super, that's the trick....thanks
