### ISSUE TITLE
Expotr to pdf orientation: 'Landscape'

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#3276]
Hello! I can not find how to turn the sheet in PDF.
Is there such a way?

**Comment by Estrusco** [comment]
If you talk about reports, you can override Customize method

public override void Customize(IHtmlToPdfOptions options)
{
            base.Customize(options);
            
            options.Landscape = true;
}

**Comment by Zahar661** [comment]
@Estrusco  Many thanks!
