### ISSUE TITLE
Issue with 'declare' keyword in Enum Fields ( typescript >2.4)(Serenity 3.5.3)

### ISSUE THREAD

**Issue by HairyPloper** [volkanceylan/Serenity#3277]
When running T4 templates to create server types for modules, It will add keyword 'declare' for const enum Fields for that Modul. In xyzGrd if you want to use enum you must import it but it will always be undifiend,
![image](https://user-images.githubusercontent.com/25281647/36417576-9a197528-162c-11e8-88ec-3f747e3ad752.png)
after removing 'declare' from .ts file it will work.
Problem is that on every generation it will create enums with declared keyword again. Where i can update generation mechanism for typescript in general?
Typescript version : Use latest available (2.5)

**Comment by Estrusco** [comment]
This can help you? https://github.com/volkanceylan/Serenity/issues/3171

**Comment by HairyPloper** [comment]
Thanks @Estrusco, I already read this #3171 thread. but i`m still struggling to make enums work with new version of typescript and Serenity.  As i described above removing single keyword from declaration of enom solves my problem, but i`m not sure how to update generation process of templates.

**Comment by HairyPloper** [comment]
This is how object looks if i don`t remove declare from declaration 
![image](https://user-images.githubusercontent.com/25281647/36419135-57e63434-1631-11e8-9b06-e4598a6884d5.png)
There is no fields, i suppose its not correctly transferd or compiled

**Comment by volkanceylan** [comment]
Everything you need is written in that issue. There wont be a Fields class / enum in script. Your TypeScript version is old probably.

**Comment by HairyPloper** [comment]
@volkanceylan, I downloaded latest typescript sdk 2.7.2 and configured it correctly in VS, still have issue...
tested also with 2.5

**Comment by volkanceylan** [comment]
There is also a TypeScript.MsBuild package in your project and if you created project very early one in your package.json.

**Comment by HairyPloper** [comment]
Global Version of typescript:
![image](https://user-images.githubusercontent.com/25281647/36425435-13c73b34-1647-11e8-93c8-ae4c065773e1.png)
Error:
![image](https://user-images.githubusercontent.com/25281647/36425524-70d549f6-1647-11e8-984d-55c7d32ec9fe.png)

Configuration
```
{
  "name": "serene",
  "version": "1.0.0",
  "description": "VTAssureNew",
  "repository": {
    "type": "git",
    "url": "https://github.com/volkanceylan/serenity"
  },
  "main": "index.js",
  "dependencies": {
    "@types/jquery": "^2.0.39",
    "@types/jquery.blockui": "0.0.27",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jquery.validation": "^1.13.32",
    "@types/jqueryui": "^1.11.32",
    "@types/jspdf": "^1.1.31",
    "@types/sortablejs": "^1.3.31",
    "@types/toastr": "^2.1.32"
  },
  "devDependencies": {
    "typescript": "2.7.2"
  },
  "scripts": {
    "tsc": "tsc -p ./tsconfig.json"
  },
  "author": "",
  "license": "ISC"
}
```
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "preserveConstEnums": true,
    "experimentalDecorators": true,
    "declaration": true,
    "emitBOM": true,
    "sourceMap": true,
    "outFile": "Scripts/site/VTAssureNew.Web.js",
    "target": "es5"
  },
  "include": [
    "Imports/",
    "Modules/",
    "Scripts/typings/"
  ]
}
```
I don`t have MSBuild typescript in my csproj
I assume it is typescript corrupted but still not able to solve this issue

**Comment by volkanceylan** [comment]
Sorry but you should report this to VS/TypeScript, this is not a Serenity issue

**Comment by volkanceylan** [comment]
Also see this document, make sure you have 2.7 there, and install latest VS2017 updates

https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017

**Comment by volkanceylan** [comment]
![image](https://user-images.githubusercontent.com/752470/36426290-a311d322-165a-11e8-9bbf-5909e0c5e3ff.png)

**Comment by volkanceylan** [comment]
![image](https://user-images.githubusercontent.com/752470/36426391-e16ca4c6-165a-11e8-8d38-7d0aa61a6b53.png)

**Comment by HairyPloper** [comment]
@volkanceylan  Thanks again, I tried everything mentioned above, if i find what is issue i will post it here

**Comment by CleverKiran** [comment]
Pls check if packages.json has any old typescript dependencies. If so, remove them.
I had similar issue/s and was able to fix it. My packages.json looked like below
...
"devDependencies": {
    "typescript": "2.1.5"
  },
  "scripts": {
    "tsc": "tsc -p ./tsconfig.json"
  },
...

I modified the above as 
...
"devDependencies": {},
  "scripts": {},
...
