### ISSUE TITLE
Issue with "DateTime2" and MySQL

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#328]
Updated to latest version of Serenity framework and started experiencing issues with DateTime fields.  It appears that on an Update, the SqlHelper class incorrectly sets the DbType to DateTime2.  This happens because the call to "command.Connection.GetDialect()" in "AddParamWithValue" does not return the correct dialect.

```
public static DbParameter AddParamWithValue(this DbCommand command, string name, object value)
{
    DbParameter param = command.CreateParameter();

    value = FixParamType(value);
    param.Value = value;

    var str = value as string;
    if (str != null && str.Length < 4000)
        param.Size = 4000;

    if (value != null && value != DBNull.Value)
    {
        param.DbType = SqlMapper.LookupDbType(value.GetType(), name);

        // Do not get exception with these lines commented out
        //if (param.DbType == DbType.DateTime &&
        //    command.Connection.GetDialect().UseDateTime2)
        //    param.DbType = DbType.DateTime2;
    }

    param.ParameterName = name;
    command.Parameters.Add(param);
    return param;
}
```

**Comment by volkanceylan** [comment]
Thanks for your pull request, i assumed command.Connection to be same with original connection but this is not the case as original one is a WrappedConnection while command.Connection is actual one.

I'll just change connection parameter to ISqlDialect for consistency reasons
