### ISSUE TITLE
Check data before recording

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3281]
How to verify if the data in the form already exists in the DB and so do not duplicate the records.
Image Example.
The product "Alice Mutton" already exists for the supllier and the category, but clicking the save button will save again, thus doubling the product.
How can I validate this before saving?
How to compare the name of the product that is in the form if it already exists in the DB?
![image](https://user-images.githubusercontent.com/7516443/36440386-68fe77e6-164e-11e8-925f-4a1bb5ece6fc.png)

In a windows forms application I do this:
  var content = (from c in mdc.Products
                                    where c.DescricaoProduto == txtProduto.Text
                                    select c);

                     if (conteID.Count ()> 0)
                     {
                         MessageBox.Show ("Product Already Registered !!");
                         txtProduct.Focus ();
                     }

But inside the serenity I can not.

**Comment by hairangsua** [comment]
i think u should not do this in client. In client u just validate if this validate is simple( like check format, number or string, etc.. ). 
if u still want to validate date exist in DB. 
- u cant retrieve data in ts in check it, using event change or addValidateRule. 
- Validate on Create, update in repository.cs

**Comment by juliermefelix** [comment]
I'm trying to make a repository a beforesave, but I'm not able to reference the dialog fields so I can check in the database.

private class MySaveHandler: SaveRequestHandler <MyRow> {

             protected override void BeforeSave ()
             {
                 base.BeforeSave ();
                 if (base.IsCreate)
                 {
                     var memberID = fld.Idemember;
                     var eventID = fld.IDEvento;
            
    'I'm not sure how to reference the fields in the form (dialog) to do the tests here comparing with the variables.
                 
                 }

                

             }

         }

**Comment by hairangsua** [comment]
im not sure for you solution. im usually validate on typescript.

if u C# do u try this? sorry guy because my project dont use repository (just use endpoints file) so i dont have much knowledge about it
`       
 private Boolean Validatesomething(SaveRequest<MyRow> request)
        {
            //validate something like

            var a = request.Entity.CatCode;

            var b = request.Entity.ChoiceCode;


            return true;
        }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            var b = Validatesomething(request);

            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            var b = Validatesomething(request);

            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }`

**Comment by juliermefelix** [comment]
781/5000
I need something like this:

   private class MySaveHandler: SaveRequestHandler <MyRow> {

             protected override void BeforeSave ()
             {
                         
                 base.BeforeSave ();
                    var FormInscricao = new Forms.InscricaoForm ();
                     var campoform = FormInscricao.Idember;
              
                 var content = (from c in MyRow.Fields
                                where c.IdMember == campoform
                                select c);

                 if (content.Count ()> 0)

                     {
                      throw new ValidationError ("user already registered");
          
                     }

             
             }

         }

but this is giving error in the line of "where"

**Comment by minhhungit** [comment]
@juliermefelix Try this
Here is my current project, it is not the answer for your question but I think it will help a bit
```csharp
protected override void ExecuteSave()
{
	base.ExecuteSave();

	var users = Connection.List<UserRow>();

	foreach (var user in users)
	{
		if (this.Row.Id != null && user.UserId != null)
		{
			if (user.Username.ToLower().Trim() == "admin" || (user.AllowAssignAllSupplier != null && user.AllowAssignAllSupplier.Value))
			{
				if (!this.Connection.Exists<SupplierUserRow>(SupplierUserRow.Fields.SupplierId == (Guid)this.Row.Id & SupplierUserRow.Fields.UserId == (int)user.UserId))
				{
					this.Connection.Insert(new SupplierUserRow { SupplierId = this.Row.Id, UserId = user.UserId });
				}
			}                        
		}
	}
}
```

**Comment by minhhungit** [comment]
@juliermefelix Hope this help:
```csharp
private class MySaveHandler : Common.SequenceGUID.SequenceGUIDSaveHandler<MyRow> {
	protected override void BeforeSave()
	{
		base.BeforeSave();

		if (!this.Connection.Exists<SupplierRow>(MyRow.Fields.CompanyName == this.Row.CompanyName))
		{
			// do anything you want to do
		}
		else
		{
			throw new ValidationError("This supplier already registered");
		}
	}
}
```
By the way, you can use **UniqueConstraint** attribute on ROW class to validate, something like:
```csharp
[UniqueConstraint(new string[] { "SupplierId", "CompanyName"})]
public sealed class ViewInventoryQuoteRow : Row, IIdRow, INameRow
{
   ...
}
```

**Comment by juliermefelix** [comment]
@minhhungit
Thank you!
It worked now.

**Comment by juliermefelix** [comment]
@minhhungit
Thank you!
It worked now.

**Comment by stixoffire** [comment]
@juliermefelix 
You probably know this by now - but here is how you access the entity that was entered into the form fields.. this.Row.<myfield>

```
                 base.BeforeSave ();
                 if (base.IsCreate)
                 {
                     var memberID = fld.Idemember;
                     var eventID = fld.IDEvento;
         //    should be this to access your new Entity
                       var memberID = this.Row.Idemember;
                     var eventID = this.Row.IDEvento;



  'I'm not sure how to reference the fields in the form (dialog) to do the tests here comparing with the variables.
                 
                 }

```
