### ISSUE TITLE
Lookup Editor for code description tables servertypings missing 

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#3286]
Hi guys , After upgrading to 3.5.5 the lookup editor from the wiki 
https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables
stop to generate servertypings 
![image](https://user-images.githubusercontent.com/10474555/36475843-b539adf4-1704-11e8-9af2-e8d849366a60.png)
![image](https://user-images.githubusercontent.com/10474555/36475854-c1daa446-1704-11e8-8ecc-048a04f51356.png)
![image](https://user-images.githubusercontent.com/10474555/36475907-ed592e6c-1704-11e8-889a-acc168fb6321.png)
![image](https://user-images.githubusercontent.com/10474555/36475988-3452be3c-1705-11e8-9e01-9362cfe492d3.png)

**Comment by volkanceylan** [comment]
Please everybody can stop mentioning my name?

**Comment by volkanceylan** [comment]
That article is not written by me, and this is not Volkan Ceylan private support services

**Comment by Magik3a** [comment]
You're correct, i will buy private desk

**Comment by Estrusco** [comment]
I have tried now with latest serene project, and all works. Try to remove .Common from namespace in your editor, regen typescript then make T4 transformation

**Comment by Estrusco** [comment]
In form really are not generated correct type. I investigate in code generator... wait

**Comment by Estrusco** [comment]
@Magik3a 
The problem is that now the code generator see the attribute LookupCodeDescrAttribute and search editor for it, not finding the editor. 
You can use directly generated attribute, LKCodeDescrAttribute to bypass the problem. In this case you have to hardcode lookup key.

LKCodeDescr(LookupKey = "yourKookupKey", CodeName = "code", DescrName = "description")]

**Comment by Magik3a** [comment]
Thanks @Estrusco , that fixed the problem i just tested it

**Comment by Estrusco** [comment]
You're welcome :)
