### ISSUE TITLE
Serene Translations module not working anymore

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#3288]
Hello all,

At the start of this year I upgraded my Serene project to Serenity version 3.3.14
For the Serene modules I kept the old situation, because in some modules customizations were made.
For most of the modules no problem.
However, for Modules->Administration->Translations an error arose in TranslationGrid.ts
And indeed, there was a new version of this file as well, so I took this new one.
But still an error arises when starting the Translations module : 

```
jQuery.Deferred exception: AppreziSolution.Administration.TranslationGrid is not a constructor @http://localhost:49997/Administration/Translation:383:9
mightThrow@http://localhost:49997/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3570:21
resolve/</process<@http://localhost:49997/Scripts/jquery-3.1.1.js?v=RoNrvGA8lWW1zAYRAMy6yA2:3638:12
 undefined jquery-3.1.1.js:3846:3
```
Does anyone have a clue where this error comes from ?

**Comment by brunobola** [comment]
@GreenUtil try to upgrade using nuget, then T4 and build

**Comment by GreenUtil** [comment]
Hello Brunobola, what package should I upgrade ?

**Comment by brunobola** [comment]
@GreenUtil just follow the documentation and try to see the wiki :)

**Comment by GreenUtil** [comment]
Solved it ! 

On some way I had this in my TranslationGrid.ts : 

namespace Serene.Administration.Administration {
