### ISSUE TITLE
Reload dialog

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3289]
Dear,
I have a dialog according to the example "Entity Dialog as Panel" with a Save button
I would like that after clicking on the button Save the dialog was reloaded, so that you can make a new inscription.
As it is not being reloaded it is displaying the last data, I would like the fields to be cleaned.

**Comment by xareas** [comment]
in XXXDialog.ts , try this

    getToolbarButtons(): Serenity.ToolButton[] {
            let btns = super.getToolbarButtons();
           
            if (!this.isEditMode()) {
                let newBtn: Serenity.ToolButton =
                {
                    title: "Guardar/Nuevo",
                    hint: "Guardar y Agregar Nuevo Registro",
                    separator: false,
                    cssClass: "button-saveandnew",
                    icon: Resources.saveAndNew,
                    onClick: (e) => {
                        e.preventDefault();
                        this.saveAndNew();
                    }
                };
                btns.push(newBtn);
            }
            
           
            return btns;
        }

        private saveAndNew() {
            let e = this.entity; let f = this.form;
            this.save((response) => {
                let ent: MovDetailRow = { KeyMovimiento: e.KeyMovimiento,KeyBodega:parseInt(f.KeyBodega.value) };
                this.loadEntity(ent);
            });
        }

**Comment by juliermefelix** [comment]
Thank you!
