### ISSUE TITLE
What is the meaning of [PageAuthorize]?

### ISSUE THREAD

**Issue by gyygyy32** [volkanceylan/Serenity#3292]
Code is below.

[assembly:Serenity.Navigation.NavigationLink(int.MaxValue, "Production/Issue", typeof(Serene7.Production.Pages.ProductionIssueController))]

namespace Serene7.Production.Pages
{
    using Serenity;
    using Serenity.Web;
    using System.Web.Mvc;

    [RoutePrefix("Production/ProductionIssue"), Route("{action=index}")]
    [PageAuthorize(typeof(Entities.ProductionIssueRow))]
    public class ProductionIssueController : Controller
    {
        public ActionResult Index()
        {
            return View("~/Modules/Production/ProductionIssue/ProductionIssueIndex.cshtml");
        }
    }
}

**Comment by xareas** [comment]
read this....

https://serenity.is/blog/2016/12/17/dont-repeat-your-permissions
