### ISSUE TITLE
Cannot find Enum type 

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#3293]
Hi, I' cannot avoid this error with my Enum in a new project (I've been using Enums in previous projects)

_Can't find BaseFoie.CirrhoseEnum enum type! If you have recently defined this enum type in server side code, make sure your project builds successfully and transform T4 templates. Also make sure that enum is under your project root namespace, and your namespace parts starts with capital letters, e.g. MyProject.Pascal.Cased namespace_

My Enum is defined in namespace BaseFoie. It is version 3.5.5 and with the Core version the Build should 

Is this related to #3171 breaking change? What I notice is that in former projects I had an enum declaration in Project.Web.d.ts but nothing in this current project.

**Comment by BravoSierra** [comment]
I mean with the Core version the T4 templates transform suggestion should not apply right? Otherwise the project builds successfully

**Comment by BravoSierra** [comment]
It works after a complete fresh reinstal from scratch, so I thinks it's an update that caused the problem.

**Comment by UlyssesAlves** [comment]
I also get this error, but can't understand why new enums produce the error.

"Can't find Transacoes.TransactionResultCode enum type! If you have recently defined this enum type in server side code, make sure your project builds successfully and transform T4 templates. Also make sure that enum is under your project root namespace, and your namespace parts starts with capital letters, e.g.MyProject.Pascal.Cased namespace"

"Error
    at new Exception$ (http://127.0.0.1:5010/Scripts/saltarelle/mscorlib.js?v=AO_L_1E_BHK8K8k5pu8Fmg:3218:16)
    at Object.get (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:9422:23)
    at EnumEditor.updateItems (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:6372:79)
    at new EnumEditor (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:6367:19)
    at Function.Widget.create (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:4159:26)
    at HistoricoTransacoesGrid.DataGrid.addQuickFilter (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:11953:42)
    at HistoricoTransacoesGrid.DataGrid.createQuickFilters (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:11220:22)
    at HistoricoTransacoesGrid.DataGrid [as constructor] (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:11169:19)
    at HistoricoTransacoesGrid.EntityGrid [as constructor] (http://127.0.0.1:5010/Scripts/serenity/Serenity.CoreLib.js?v=rbgJkLyDAsVUi5O9rfQr3w:12514:32)
    at new HistoricoTransacoesGrid (http://127.0.0.1:5010/Scripts/site/SIAGRIAPI.Web.js?v=ocxxeCm39gBGPNmd2Fu_kw:7237:36)"

**Comment by christophermarch** [comment]
Hello,

I have this issue as well, same as UlyssesAlves.  Can anyone out there assist?
Thank you for your time and help.

**Comment by erehtolleh** [comment]
Did you make sure to build the T4 Templates?  That is probably the issue.  If you don't build the templates, Serenity won't know about the new enums.

**Comment by christophermarch** [comment]
Thank you very much, and I apologize for not responding sooner
to your help which resolved my issue.  Are you also able to assist
me in spacing out the radio buttons?  I need much greater spacing
between the options.  Thank you in advance for any assistance.

***@***.***D7199D.751F1490]

Christopher March
Experienced Technology Consultant
+1.540.539.8585
Join the conversation: LinkedIn<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fprotiviti&data=02%7C01%7CChristopher.March%40protiviti.com%7C7706593ad44a4833e50008d850e0ed98%7C16532572d5674d678727f12f7bb6aed3%7C0%7C0%7C637348274269562047&sdata=OufJb04TDK5DpULRiZvppw2yPET6zzIPrP53EVWPqCU%3D&reserved=0> | Facebook<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.facebook.com%2Fhome.php%3F%23%2FProtiviti&data=02%7C01%7CChristopher.March%40protiviti.com%7C7706593ad44a4833e50008d850e0ed98%7C16532572d5674d678727f12f7bb6aed3%7C0%7C0%7C637348274269572041&sdata=GEycoFY1m%2Fe%2BThETnZNOippOhlD5jfLnQ3xU08cgyd8%3D&reserved=0> | Twitter<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fprotiviti&data=02%7C01%7CChristopher.March%40protiviti.com%7C7706593ad44a4833e50008d850e0ed98%7C16532572d5674d678727f12f7bb6aed3%7C0%7C0%7C637348274269582037&sdata=o9bWjTzKf4JDVwDLUzm9vh8gHrZht9vdk0CVuSKA4h8%3D&reserved=0> | YouTube<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.youtube.com%2Fprotivitiinc&data=02%7C01%7CChristopher.March%40protiviti.com%7C7706593ad44a4833e50008d850e0ed98%7C16532572d5674d678727f12f7bb6aed3%7C0%7C0%7C637348274269582037&sdata=INiCddM0fl8nybLKj2szog57E%2FiP0MMbXk9rNVL5uxM%3D&reserved=0>

Protiviti | Winchester | VA 22602 USA | Protiviti.com<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.protiviti.com%2F&data=02%7C01%7CChristopher.March%40protiviti.com%7C7706593ad44a4833e50008d850e0ed98%7C16532572d5674d678727f12f7bb6aed3%7C0%7C0%7C637348274269592038&sdata=QQhFY36uX7QE92dk2Q87HEH9APM8v67YJhB7ofYTwYY%3D&reserved=0>
[vk]

**Comment by christophermarch** [comment]
![image](https://user-images.githubusercontent.com/80417970/111193699-d2999f00-8590-11eb-9143-a3414f246f09.png)

Sorry, here is the image referenced above.
