### ISSUE TITLE
ServiceEndPoint and AllowAnonymous

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#3295]
Hi,I am trying to call http://MYSERVERandPORT/Services/MovieDB/Genre/List from a different browser  and it is giving AccessDenied  Error

I have added  attribute to skip the authorization, but it still giving the error
[AllowAnonymous]
 public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
 {
        return new MyRepository().List(connection, request);
 }

{"Error":{"Code":"AccessDenied","Message":"Authorization has been denied for this request!","Details":"Serenity.Services.ValidationError: Authorization has been denied for this request!\r\n   at Serenity.Authorization.ValidatePermission(String permission) in P:\\Sandbox\\Serene\\Serenity\\Serenity.Core\\Authorization\\Authorization.cs:line 108\r\n   at Serenity.Services.ListRequestHandler`3.ValidatePermissions() in P:\\Sandbox\\Serene\\Serenity\\Serenity.Services\\RequestHandlers\\List\\ListRequestHandler.cs:line 441\r\n   at Serenity.Services.ListRequestHandler`3.ValidateRequest() in P:\\Sandbox\\Serene\\Serenity\\Serenity.Services\\RequestHandlers\\List\\ListRequestHandler.cs:line 446\r\n   at Serenity.Services.ListRequestHandler`3.Process(IDbConnection connection, TListRequest request) in P:\\Sandbox\\Serene\\Serenity\\Serenity.Services\\RequestHandlers\\List\\ListRequestHandler.cs:line 501\r\n   at MovieTutorial.MovieDB.Repositories.GenreRepository.List(IDbConnection connection, ListRequest request)

**Comment by she-ll-b-rite** [comment]
Couple of things you might check:
1) from memory the default http verb is 'post', which means you can't whack the url into a browser as this uses 'get'. If this is what you want, then make sure you add the [HttpGet] attribute to your method.

2) check the [ServiceAuthorize] attribute is not applied at the Controller level.

HTH

**Comment by Parbil** [comment]
I have tried the same and it is giving the same security validation, it goes till repository then after that it return the error.  I have removed ReadPermission from Movie row but no luck. 

    [RoutePrefix("Services/MovieDB/Movie1"), Route("{action}")]
    [ConnectionKey("Default")]
    public class Movie1Controller : ServiceEndpoint
    {
        
        [HttpGet,AllowAnonymous]
        public ListResponse<MyRow> List(IDbConnection connection, MovieListRequest request)
        {
            return new MyRepository().List(connection, request);
        }
    }

**Comment by she-ll-b-rite** [comment]
couple of things:
* you probably don't need the 'AllowAnonymous' attribute.
* have you tried removing all permission attributes from row class? I'm assuming if you have insert, update, modify or delete permissions attributes set, then read / view permission will be implicit.

if this doesn't work or you don't want to modify the row permissions, you can access the data directly using the connection object. be careful though as this bypasses all permissions checks.

```
[HttpGet]
public ListResponse<MyRow> List(IDbConnection connection, MovieListRequest request)
{
   var entities = connection.List<MyRow>(request.Criteria);
   return new ListResponse<MyRow>() { Entities = entities, TotalCount = entities.Count };
}
```

**Comment by Parbil** [comment]
It is working. Thanks.

**Comment by ga5tan** [comment]
@Parbil how did u solve it? did you go directly to DB?
I SerGened page and want to make it FrontEnd available - without authorization.
