### ISSUE TITLE
How to get public variable value from child Dialog when closing the dialog.

### ISSUE THREAD

**Issue by vinslake** [volkanceylan/Serenity#3296]
Hi everyone how can i get the child dialog public variable when closing then pass it to parent dialog..

thnks everyone.

**Comment by she-ll-b-rite** [comment]
i reckon this should help #3274. You should invoke your anonymous method in the 'onDialogClose' function of the child EntityDialog.

HTH

**Comment by vinslake** [comment]
thanks so much..
