### ISSUE TITLE
Connecting to Sql

### ISSUE THREAD

**Issue by DwightRutledge1** [volkanceylan/Serenity#330]
Ok, I installed Serenity into my Visual Studio and followed all instructions. Created my first project fine. I ran the system and it was perfect. I followed the instructions and added my own database as a localdb according to the instructions for the movie database. Now I get error that I do

Cannot open database my database" requested by the login. The login failed.
Login failed for user my user.  But I can connect to the database without issue through management console

**Comment by DwightRutledge1** [comment]
Never mind. I found the issue.

**Comment by HelgeSverre** [comment]
What was the issue?
