### ISSUE TITLE
SqlQuery issue

### ISSUE THREAD

**Issue by chiangim** [volkanceylan/Serenity#3302]
var fldCAT = ServicecategoriesRow.Fields;
            var fldVS = VendorservicesRow.Fields;

            var vendorId = request.FilterVendorId.Value;
            var query = new SqlQuery()
                .From(fldCAT)
                .Select("*")
                .LeftJoin(new Alias(fldVS.TableName, "vs"),
                    new Criteria("vs", "ServiceCategoryId") == new Criteria(0, "ServiceCategoryId")
                )
                .Where(
                    **new Criteria("vs", "VendorId") == vendorId**
                ).OrderBy(fldCAT.Name);

Why above code, i am always getting @p1 even my vendorId value is 1?

Below is output generated:-
SELECT 
* 
FROM [servicecategories] T0 
LEFT JOIN [vendorservices] vs ON (vs.[ServiceCategoryId] = T0.[ServiceCategoryId]) 
WHERE (vs.[VendorId] = **@p1**) 
ORDER BY T0.[Name]

**Comment by brunobola** [comment]
the @p1 is a parameter

**Comment by chiangim** [comment]
Find out solution as below:-
https://volkanceylan.gitbooks.io/serenity-guide/fluent_sql/criteria_objects.html

new SqlQuery()
    .From("MyTable")
    .Select("MyField")
    .Where(
        new Criteria("Field1") == **new ConstantCriteria(1)** &
        new Criteria("Field2") != **new ConstantCriteria("ABC")**
    )

OR 
*ParamCriteria and Explicit Param Names*
If you want to use some explicitly named parameter, you can make use of ParamCriteria:
new SqlQuery()
    .From("SomeTable")
    .Select("SomeField")
    .Where(new Criteria("SomeField") <= new ParamCriteria("@myparam"))
    .Where(new Criteria("SomeOtherField") == new ParamCriteria("@myparam"))
    .SetParam("@myparam", 5);
