### ISSUE TITLE
TimeField

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3303]
In a TimeSpanField, I have a Time field with AM/PM .
In Table, I am having column with Time Datatype.
When I try to save, I get conversion error.   What is the preferred column type in sql server and How to implement in serenity?

**Comment by brunobola** [comment]
You can write your own formatter or in alternative just use a datetime column and format the result you want.

**Comment by AmuthaKondusamy** [comment]
If I have datetime in SQL then, it appends a default date with the time.
