### ISSUE TITLE
[Fixes/Tricks] Sergen and Oracle

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3304]
Here are required steps in order to make Oracle and Sergen works properly
(tested by updating a custom Serenity.CodeGenerator project) :

1/ FIXES (ideally would love to have them updated on Serenity.Data nuget)
Here are some minor fixes that allows Sergen working with Oracle (all are typo errors)

File : OracleSchemaProvider.cs 

(Line 19) GetFieldInfos (there is a useless ',' after double quotes)
```
    CASE WHEN c.nullable = 'N' THEN 1 ELSE 0 END ""IsNullable"",
=>  CASE WHEN c.nullable = 'N' THEN 1 ELSE 0 END ""IsNullable""
```
				   
(Line 81/82) GetTableNames (Case sensitivity is required for OWNER and TABLE_NAME)
```
    Schema = x.owner,
    Table = x.table_name	
=>  Schema = x.OWNER,
    Table = x.TABLE_NAME
```

(Line 68) GetPrimaryKeyFields (Invalid character ';' in the query string after cols.position)
```
    ORDER BY cols.position;",	
=>  ORDER BY cols.position",
```

Fixes to support Oracle Data standard types (varchar2, number) :

SchemaHelper.cs
```
    private static Dictionary<string, string> SqlTypeToFieldTypeMap =
      new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
      {
       ............
        {"tinyint", "Int16"},
        {"uniqueidentifier", "Guid"},
        {"varbinary", "Stream"},
        {"varchar", "String"},
        // Oracle datatype 
        {"varchar2", "String"}
      };

            public static string SqlTypeNameToFieldType(string sqlTypeName, int size, out string dataType)
    {
      dataType = null;
      string fieldType;
      sqlTypeName = sqlTypeName.ToLowerInvariant();

      if (sqlTypeName == "varbinary")
      {
        if (size == 0 || size > 256)
          return "Stream";

        dataType = "byte[]";
        return "ByteArray";
      }
      else if (sqlTypeName == "timestamp" || sqlTypeName == "rowversion")
      {
        dataType = "byte[]";
        return "ByteArray";
      }
      // Oracle custom type
      else if (sqlTypeName == "number")
      {
        if (size < 5) // maxvalue 32767
          return ("Int16");
        if (size >= 11)
          return "Int64";
        return "Int32"; // maxvalue 2147483648
      }
      else if (SqlTypeToFieldTypeMap.TryGetValue(sqlTypeName, out fieldType))
        return fieldType;
      else
        return "Stream";
    }
```
EntityModel.cs
Oracle does not support syntax [SCHEMA].[TABLE] but SCHEMA.TABLE

```
        public string SchemaAndTable
        {
        // get { return string.IsNullOrEmpty(Schema)? Tablename : "[" + Schema + "].[" + Tablename + "]"; }
        get { return string.IsNullOrEmpty(Schema) ? Tablename : Schema + "." + Tablename; }
        }
```

2/ TRICKS
In order to make Sergen working with Oracle.Managed.DataAccess provider (recommended driver by Volkan - see Serenity Guide)

Do not forget to add : 
```
  <system.data>
    <DbProviderFactories>
      <remove invariant="Oracle.ManagedDataAccess.Client" />
      <add name="ODP.NET, Managed Driver" invariant="Oracle.ManagedDataAccess.Client" description="Oracle Data Provider for .NET, Managed Driver" type="Oracle.ManagedDataAccess.Client.OracleClientFactory, Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342" />
    </DbProviderFactories>
  </system.data>  
```
in Sergen app.config file

and check that the corresponding line is listed on MACHINE.CONFIG file (DbProviderFactories tag) : 
`		 <add name="Oracle Data Provider for .NET" invariant="Oracle.ManagedDataAccess.Client" description="Oracle Data Provider for .NET" type="Oracle.ManagedDataAccess.Client.OracleClientFactory, Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342" />`

**Comment by JohnRanger** [comment]
Hi @kilroyFR ,

why don't you create a pull request? :-)

With kind regards,

John

**Comment by kilroyFR** [comment]
yes will do. I was not certain it could interest many.

**Comment by kilroyFR** [comment]
Having issue pushing my branch to Github... (credential issue)

**Comment by kilroyFR** [comment]
Pull request has been done
