### ISSUE TITLE
Row in xyzRepository.cs; Values from expression/innerjoined fields are all null

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3306]
Hi all,

I have an xyzRow.cs where I have many innerjoined fields added via expression like this:
```cs
            #region Workstationid
            [DisplayName("Workstationid"), Column("WORKSTATIONID"), NotNull, ForeignKey("[dbo].[WORKSTATIONS]", "WORKSTATIONID"), LeftJoin("jWorkstationid"), TextualField("WorkstationidIdentifier"), LookupInclude, QuickSearch]
            public Int32? Workstationid { get { return Fields.Workstationid[this]; } set { Fields.Workstationid[this] = value; } }
            public partial class RowFields { public Int32Field Workstationid; }
            #endregion Workstationid

                [DisplayName("Workstationid DefaultPrinter_PrintqueueID"), Expression("jWorkstationid.[DefaultPrinter_PrintqueueID]"), LookupInclude]
                public Int32? WorkstationidDefaultPrinter_PrintqueueID { get { return Fields.WorkstationidDefaultPrinter_PrintqueueID[this]; } set { Fields.WorkstationidDefaultPrinter_PrintqueueID[this] = value; } }
                public partial class RowFields { public Int32Field WorkstationidDefaultPrinter_PrintqueueID; }
```

The values of these innerjoined fields are perfectly available e.g. in the grid.

**Problem:**
If I try to access these innerjoined fields within xyzRepository.cs via the Row variable, only the direct fields but not the innerjoned fields have their values set. (The innerjoined fields are visible but their values are not set.)

```cs
             private Int32? _PrintQueueID;

            protected override void OnBeforeDelete()
            {
                base.OnBeforeDelete();
                _PrintQueueID = Row.WorkstationidDefaultPrinter_PrintqueueID.Value;
                var bla = Row;

                var Bla2 = 2;

            }
```
In above example, WorkstationidDefaultPrinter_PrintqueueID.Value contains null - but actually should contain an integer number.

**Questions:**
(1) Is this "by design"? 
(2) Is there an easy way (e.g. by declarative programming) to force the Row variable to be filling also the innerjoined fields?

Hint: I know that I can get to the desired values by doing manual queries to the relevant tables but it would be much nicer to just "tap" into the already innerjoined fields.

Thanks for any help with this.

With kind regards,

John

**Comment by she-ll-b-rite** [comment]
1) yes this is by design, as you wouldn't normally require this data
2) yes, if you explicitly request the field be populated in the 'PrepareQuery' override method, your code should work:

```
        private class MyDeleteHandler : DeleteRequestHandler<MyRow>
        {
            protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);
                query.Select(xyzRow.Fields.WorkstationidDefaultPrinter_PrintqueueID);
            }
        }
```

HTH

**Comment by JohnRanger** [comment]
Hi @she-ll-b-rite ,

thanks for your very fast answer. This worked perfectly :-)

With kind regards,

John
