### ISSUE TITLE
Add a lookup editor on top of detail grid.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#331]
I have successfully add a textbox on top of the detail grid.

![untitled](https://cloud.githubusercontent.com/assets/16621563/13370827/c185ac86-dd3e-11e5-8ad7-625a9a0f2df5.png)

Now, I want to add a lookup editor on top of detail grid. Please give some hints.

**Comment by volkanceylan** [comment]
Use Widget.Create<LookupEditor>(e => e.AppendTo(toolbar.Element), new LookupEditorOptions { });

**Comment by dfaruque** [comment]
Thank you. 

Now how can I access this lookup editor [for getting selected value or bind some events]

Regards

**Comment by dfaruque** [comment]
Got it

**Comment by reach2rv** [comment]
> Thank you.
> 
> Now how can I access this lookup editor [for getting selected value or bind some events]
> 
> Regards

How you have achieved this??

**Comment by stixoffire** [comment]
@dfaruque I would like to know what you did to achieve the functions. I have a View that I am trying to put a filter on one of the values. hence I am searching the issues - and anything that points me to the right direction without having to create an issue is better.

**Comment by reach2rv** [comment]
@stixoffire Please see if following works for you.. its not yet fully tested by me for changeselect event.

in your XYZeditor.ts

```C#
private XYZ: Serenity.LookupEditor;

protected createToolbarExtensions(): void {
            super.createToolbarExtensions();
            let opt: Serenity.LookupEditorOptions = {
                lookupKey: OMS.XYZrow.lookupKey
            };

            this.voucherType = Serenity.Widget.create({
                type: Serenity.LookupEditor,
                element: el => el.appendTo(this.toolbar.element).attr('placeholder', '--- ' +
                    Q.text('Db.Administration.Translation.SourceLanguage') + ' ---'),
                options: opt
            });

            this.XYZ.changeSelect2(e => {                

            });
        }
```

**Comment by stixoffire** [comment]
@reach2rv  I have accomplished getting the lookup - I am trying to assign it to filter the grid in the change subscription. This where I need to assign the value to filter the grid .. I am limited on my slickGrid knowledge and how to assign the select2 value to the filtering mechanism - I know in the change subscription is the where but how.

```
            this.XYZ.changeSelect2(e => {                
 this.getGrid().getColumns().filter(x => { x.field = "Number" }); 
            });
```

**Comment by waleed51** [comment]
how can i add a textbox in the grid toolbar ??? @dfaruque
