### ISSUE TITLE
Possible Bug: NULL Byte Array translates to nvarchar on insert

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#3321]
Hi Volkan,

I'm reopening issue #2907 which is now too old to reopen. It's taken me some time, but I did have some spare time and I made a few tests. Sorry it's taken so long.

The way to replicate:

Create a XXXRow with a field defined as byte[] (varbinary in sql).

Manually create a row and make sure the field has data in it and call the XXXRepository.Create()
Manually Create a row and make sure the byte field is null and call the XXXRepository.Create()

Now you should get the error above. 

The code works as long as the field is not null (i.e. you can put in an empty byte array and that seems to work. 

The trace during the create is:
```
SaveRequestHandler::ExecuteSave()
EntityConnectionExtensions::ToSqlInsert
SqlHelper::ExecuteAndGetID
SqlHelper::ExecuteReader
```
The query that is sent into ExecuteAndGetID from my code is:
```
"INSERT INTO [dbo].[ReportContent] ([ReportContentTitle], [ReportContentOrder], [ReportSectionId], [ReportContactId], [ReportDisclosureId], [ReportContentText], [ReportContentWordDocRef], [ReportContentFile], [DateAssigned], [Deadline], [DateCompleted], [StatusId], [OriginalFileName], [DirectToIndex], [ContentType], [TopicId]) VALUES (N'Headquarters', 7, 737, 2, 4766, NULL, N'content/00020_7qjohkuncfzrk.docx', NULL, '20170707', NULL, '20170710', 2, NULL, 0, 1, NULL)"
```
And this actually executes fine in SQL Server

The command that is sent into the ExecuteReader is
```
"INSERT INTO [dbo].[ReportContent] ([ReportContentTitle], [ReportContentOrder], [ReportSectionId], [ReportContactId], [ReportDisclosureId], [ReportContentText], [ReportContentWordDocRef], [ReportContentFile], [DateAssigned], [Deadline], [DateCompleted], [StatusId], [OriginalFileName], [DirectToIndex], [ContentType], [TopicId]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16);\nSELECT SCOPE_IDENTITY() AS IDCOLUMNVALUE"
```

And the parameter value @p8 is no longer null but blank (`{[@p8, ]}`. 

I'm wondering whether the interpreter changes this to a nvarchar in this particular case.

I hope I was specific enough. If not let me know what you need.

**Comment by karimhyatt** [comment]
Hi. Anything further I can do to help regarding this?

**Comment by volkanceylan** [comment]
I don't understand what's the problem here, parameter type is irrelevant as long as value is NULL. You shouldn't get any errors on insert.

**Comment by karimhyatt** [comment]
I'm just reporting what I get. The parameter sends nvarchar instead of varbinary. I also think it's weird. Do you need more info to verify this? 

Using the SQL Server profiler I was able to see the error on the server as well. 

For the moment, I have been able to circumvent the error using sql commands, circumventing the xxxRow but using the uow in order to maintain the transaction. So if I write the SQL manually it works.

**Comment by karimhyatt** [comment]
Sorry for the delay in response (travelling). 

SQL Server does not like that. It complains that you need to convert it to varbinary.
