### ISSUE TITLE
Following code only works if logged in user is given "Administration:Security" permission

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#3325]
onDialogOpen() {
            super.onDialogOpen();
 
           this.element.closest(".ui-dialog").find(".ui-dialog-titlebar-maximize").click();
}

In the above dialog maximizing code only works if logged in user has "Administration:Security" permission, what can be the issue

**Comment by vinaykulkarni89** [comment]
Hello is there anyone, who can have any idea for above?

**Comment by dfaruque** [comment]
Please check your browser console. is there any error?

**Comment by vinaykulkarni89** [comment]
Hi @dfaruque, the following is the screenshot, from the console,

![image](https://user-images.githubusercontent.com/17939331/37395314-fcfcb4a4-279b-11e8-94d4-b634add42a20.png)

**Comment by dfaruque** [comment]
see #2950

**Comment by vinaykulkarni89** [comment]
@dfaruque 
The referenced issue helped me, thanks
