### ISSUE TITLE
How open Edit/Insert page in panel instead of grid

### ISSUE THREAD

**Issue by PedroHFranco** [volkanceylan/Serenity#3328]
Hello guys,
I want to create a panel page to insert/edit, instead use the default grid.

I was looking at custumer and order sample and just found the @Serenity.Decorators.panel()
When i'm setting this in my Dialog its opening in the end of the page?
Any idea how fix this?

```
namespace API.Cadastros {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.panel()
    export class EventosDialog extends Serenity.EntityDialog<EventosRow, any> {
        protected getFormKey() { return EventosForm.formKey; }
        protected getIdProperty() { return EventosRow.idProperty; }
        protected getLocalTextPrefix() { return EventosRow.localTextPrefix; }
        protected getNameProperty() { return EventosRow.nameProperty; }
        protected getService() { return EventosService.baseUrl; }

        protected form = new EventosForm(this.idPrefix);

        
        constructor() {
            super();
        }
    }
```

![image](https://user-images.githubusercontent.com/10779853/37033575-44ab1980-2125-11e8-8751-472e95185997.png)

**Comment by juliermefelix** [comment]
try this on dialog.ts
  @ Serenity.Decorators.registerClass ()
     @ Serenity.Decorators.responsive ()
     @ Serenity.Decorators.panel ()
     export class InscriptionDialog extends Serenity.EntityDialog <InscriptionRow, any> {
       
         protected form = new InscriptionForm (this.idPrefix);

         private grid: InscriptionGrid;
         constructor () {
             super();
             this.form = new InscriptionForm (this.idPrefix);

and in cshtml

<div id = "DialogDiv"> </ div>

<script type = "text / javascript">
    var myDialogAsPanel;
    jQuery (function () {
        // first create a new dialog
        myDialogAsPanel = new inscription.Inscricao.InscricaoDialog ();
        // load a new entity if url does not contain an ID, or load order with specified ID in URL page
        // here we use event in second parameter, to be sure operation succeeded before showing panel
        myDialogAsPanel.load (@ Html.Raw (Model.ToJson ()) || {}, function () {
            // if we did not reach here, probably there is no order with specified id in url
            myDialogAsPanel.element.removeClass ('hidden'). appendTo ('# DialogDiv');
            myDialogAsPanel.arrange ();
        });
    });
</ script>

**Comment by PedroHFranco** [comment]
Hello @juliermefelix ,
Not working, error when getting my dialog, its null.

![image](https://user-images.githubusercontent.com/10779853/37091067-8fb0b51e-21e5-11e8-8714-77f35c4b1c87.png)

**Comment by juliermefelix** [comment]
a look at the attached file, it's the .cshtml file, look also at my dialog.
[arquivo_cshtml.txt](https://github.com/volkanceylan/Serenity/files/1789490/arquivo_cshtml.txt)
[diagolo_ts.txt](https://github.com/volkanceylan/Serenity/files/1789500/diagolo_ts.txt)

**Comment by PedroHFranco** [comment]
Solved it by updating serenity.
I picked up new errors, then opened a new issue #3338
