### ISSUE TITLE
update site javascript file after generate code  for new table

### ISSUE THREAD

**Issue by ragoob** [volkanceylan/Serenity#333]
after generate code using sergen.exe code added to my project but  "/scripts/site/Myprojectname.Script.js
not updated and i have run time exception 
"Cannot read property 'mytableGrid' of undefined"

**Comment by jsbUSMC** [comment]
You need to **Rebuild** your solution after generating code with `sergen.exe`. Right click on the solution and choose Rebuild, do not just hit F6 or F5 as only MyProject.Web will get built.

**Comment by ragoob** [comment]
thank you , i have Another question , i want make forging key column select2 from primary entity  because it is Show as textbox

**Comment by volkanceylan** [comment]
See faq and troubleshooting sections in guide

**Comment by volkanceylan** [comment]
Basically you need to rebuild or add project dependency so script project is build when web is built. Information is in guide.
