### ISSUE TITLE
Problem when inserting a string P.K value in master detail entity.

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#3334]
I am using a string primary key, and I create master detail entity but when inserting the child entity the primary key value is set to null and neglect its default value which appears in the detail grid .
also I trace all code and the P.K value is not null but at somewhere this value is set to null.

please advice

**Comment by hannesb** [comment]
Don't use a default value for the foreign key field of the detail rows, the MasterDetailRelation will take care of that anyway.

**Comment by amrgDev** [comment]
I set a default value for the primary key not for the F.K because I am using P.K of type string not int,so I need to set the P.K value before inserting the detail record.

**Comment by hannesb** [comment]
Ah ok, then you should try to override getIdProperty() in your ...GridEditor.ts class (the one based on GridEditorBase)

**Comment by amrgDev** [comment]
already overridden and return the right value.
protected getIdProperty() { return xxxxRow.idProperty; }

**Comment by hannesb** [comment]
Ok I just checked MasterDetailRelationBehavior.cs

Seems not to be supported. In SaveDetail(), an empty PK is used as a flag for an new detail row. Would never work if the PK is already set in the client.

I see two solution: Create your own Behavoir, or set the PK of the detail rows on database level (i.e. insert trigger)

**Comment by amrgDev** [comment]
Thanks for your time & fast response.
I will do the second solution.

**Comment by hannesb** [comment]
Close the issue?
