### ISSUE TITLE
Cutomer Representatives Multiple Ids Insertion into Database

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3337]
Hi,
I am trying to implement an idea similar to what is found in customer representatives in serenity where multiple employee ids are selected and inserted into the customer representatives table from the customer dialog.

Could someone guide me how the ids are received and handled in code so that they are inserted in the customer representatives table in Northwind? I am a bit confused as to which files make this happen.

**Comment by hannesb** [comment]
See LinkingSetRelationBehavior.cs

**Comment by gfo2007** [comment]
Thanks for the quick reply. Please which folder contains the LinkingSetRelationBehavior.cs

**Comment by hannesb** [comment]
Use the 'Find file' in the code tab here on github to search for file names

**Comment by gfo2007** [comment]
I have found it. Could you help with a snippet on how to use it with LinkingSetRelation id values in an entity?

**Comment by hannesb** [comment]
Hmm it's all in the Serene template, look for Representative field in CustomerRow.cs.
