### ISSUE TITLE
LinkingSetRelation Error

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3339]
Hi,
I have 3 tables. Companies, Houses and CompanyAllocations. 

CompanyAllocations is the composite table for Companies and Houses and therefore contain the CompanyId and HouseId. Each company can have multiple (whichj appears One to Many) but for keeping historical records sake, the CompanyAllocations table was created to keep track of all the houses a company has been allocated either currently or in the past.

Sergen has been used to create screens for CompanyAllocations to handle the allocation process. The image below shows the CompanyAllocation dialog.

![company alloc 1](https://user-images.githubusercontent.com/14317420/37179764-a53d9070-231e-11e8-8d84-4e8c4e2340cb.PNG)

On this dialog, I select a Company from a dropdown and also select multiple Houses using a list with the LinkingSetRelation as shown in the image below.

![company alloc 2](https://user-images.githubusercontent.com/14317420/37179864-0f15968c-231f-11e8-82ea-c3d0eeb868a2.PNG)

When I try to save I get the following error in the image below.

![company alloc 3](https://user-images.githubusercontent.com/14317420/37179997-6f6c6b0a-231f-11e8-94ea-a1707b50dfc4.PNG)

Both Company and House IDs in the CompanyAllocations table do not allow nulls and it appears the Houses ids are not being inserted into the company allocations table.

What I am trying to do it to be able to loop through the selected houseIds for that one company and insert them in the CompanyAllocations table using the CompanyAllocations dialog.

Below are my CompanyAllocationRow.cs and ComapnyAllocationForm.cs

**CompanyAllocationRow**

namespace hails.HouseAllocations.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;
    using hails.MasterData.Entities;
    using System.Collections.Generic;

    [ConnectionKey("Default"), Module("HouseAllocations"), TableName("[hails].[CompanyAllocations]")]
    [DisplayName("Company Allocations"), InstanceName("Company Allocation")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class CompanyAllocationRow : Row, IIdRow
    {
        [DisplayName("Company Allocation Id"), Identity, Hidden]
        public Int32? CompanyAllocationId
        {
            get { return Fields.CompanyAllocationId[this]; }
            set { Fields.CompanyAllocationId[this] = value; }
        }

        [DisplayName("Company"), NotNull, ForeignKey("[hails].[Companies]", "CompanyId"), LeftJoin("jCompany"), TextualField("CompanyCompanyName")]
        [LookupEditor(typeof(CompanyRow))]
        public Int32? CompanyId
        {
            get { return Fields.CompanyId[this]; }
            set { Fields.CompanyId[this] = value; }
        }

        [DisplayName("House"), ForeignKey("[hails].[Houses]", "HouseId"), LeftJoin("jHouse"), TextualField("HouseHouseNo"), Hidden]
        [LookupEditor(typeof(HouseRow), CascadeFrom = "CustomHouseEstateId", CascadeField = "EstateId")]
        public Int32? HouseId
        {
            get { return Fields.HouseId[this]; }
            set { Fields.HouseId[this] = value; }
        }

        [DisplayName("Allocation Status"), ForeignKey("[hails].[Statuses]", "StatusId"), LeftJoin("jAllocationStatus"), TextualField("AllocationStatusStatusName")]
        [LookupEditor(typeof(StatusRow))]
        public Int32? AllocationStatusId
        {
            get { return Fields.AllocationStatusId[this]; }
            set { Fields.AllocationStatusId[this] = value; }
        }

        [DisplayName("Allocation Date")]
        public DateTime? AllocationDate
        {
            get { return Fields.AllocationDate[this]; }
            set { Fields.AllocationDate[this] = value; }
        }

        [DisplayName("Expected Exit Date")]
        public DateTime? ExpectedExitDate
        {
            get { return Fields.ExpectedExitDate[this]; }
            set { Fields.ExpectedExitDate[this] = value; }
        }

        [DisplayName("Actual Exit Date")]
        public DateTime? ActualExitDate
        {
            get { return Fields.ActualExitDate[this]; }
            set { Fields.ActualExitDate[this] = value; }
        }

        [DisplayName("Company"), Expression("jCompany.[CompanyName]")]
        public String CompanyCompanyName
        {
            get { return Fields.CompanyCompanyName[this]; }
            set { Fields.CompanyCompanyName[this] = value; }
        }

        [DisplayName("Company Contact Name"), Expression("jCompany.[ContactName]")]
        public String CompanyContactName
        {
            get { return Fields.CompanyContactName[this]; }
            set { Fields.CompanyContactName[this] = value; }
        }

        [DisplayName("Company Contact No"), Expression("jCompany.[ContactNo]")]
        public String CompanyContactNo
        {
            get { return Fields.CompanyContactNo[this]; }
            set { Fields.CompanyContactNo[this] = value; }
        }

        [DisplayName("House No"), Expression("jHouse.[HouseNo]")]
        public String HouseHouseNo
        {
            get { return Fields.HouseHouseNo[this]; }
            set { Fields.HouseHouseNo[this] = value; }
        }

        [DisplayName("Estate Id"), Expression("jHouse.[EstateId]")]
        public Int32? HouseEstateId
        {
            get { return Fields.HouseEstateId[this]; }
            set { Fields.HouseEstateId[this] = value; }
        }

        [DisplayName("Company Id"), Expression("jHouse.[CompanyId]")]
        public Int32? HouseCompanyId
        {
            get { return Fields.HouseCompanyId[this]; }
            set { Fields.HouseCompanyId[this] = value; }
        }

        [DisplayName("House Status Id"), Expression("jHouse.[HouseStatusId]")]
        public Int32? HouseHouseStatusId
        {
            get { return Fields.HouseHouseStatusId[this]; }
            set { Fields.HouseHouseStatusId[this] = value; }
        }

        [DisplayName("Allocation Status"), Expression("jAllocationStatus.[StatusName]")]
        public String AllocationStatusStatusName
        {
            get { return Fields.AllocationStatusStatusName[this]; }
            set { Fields.AllocationStatusStatusName[this] = value; }
        }

        [DisplayName("Estate"), Expression("jHouse.[EstateId]"), ForeignKey("hails.Estates", "EstateId"), LeftJoin("jEstate"), TextualField("CustomHouseEstateName")]
        [LookupEditor(typeof(EstateRow), InplaceAdd =true, AutoComplete = true)]
        public Int32? CustomHouseEstateId
        {
            get { return Fields.CustomHouseEstateId[this]; }
            set { Fields.CustomHouseEstateId[this] = value; }
        }

        [DisplayName("Estate"), Expression("jEstate.[EstateName]")]
        public String CustomHouseEstateName
        {
            get { return Fields.CustomHouseEstateName[this]; }
            set { Fields.CustomHouseEstateName[this] = value; }
        }

        [LookupEditor(typeof(HouseRow), Multiple = true, CascadeFrom = "CustomHouseEstateId", CascadeField = "EstateId"), NotMapped]
        [LinkingSetRelation(typeof(CompanyAllocationRow), "CompanyId", "HouseId")]
        //[MinSelectLevel(SelectLevel.Details), QuickFilter(CssClass = "hidden-xs")]
        [DisplayName("Houses"), NotNull]
        public List<Int32> HouseList
        {
            get { return Fields.HouseList[this]; }
            set { Fields.HouseList[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.CompanyAllocationId; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public CompanyAllocationRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field CompanyAllocationId;
            public Int32Field CompanyId;
            public Int32Field HouseId;
            public Int32Field AllocationStatusId;
            public DateTimeField AllocationDate;
            public DateTimeField ExpectedExitDate;
            public DateTimeField ActualExitDate;

            public StringField CompanyCompanyName;
            public StringField CompanyContactName;
            public StringField CompanyContactNo;

            public StringField HouseHouseNo;
            public Int32Field HouseEstateId;
            public Int32Field HouseCompanyId;
            public Int32Field HouseHouseStatusId;

            public StringField AllocationStatusStatusName;

            public Int32Field CustomHouseEstateId;
            public StringField CustomHouseEstateName;

            public ListField<Int32> HouseList;

        }
    }
}

**CompanyAllocationForm**

namespace hails.HouseAllocations.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;

    [FormScript("HouseAllocations.CompanyAllocation")]
    [BasedOnRow(typeof(Entities.CompanyAllocationRow), CheckNames = true)]
    public class CompanyAllocationForm
    {
        public Int32 CompanyId { get; set; }
        public Int32 CustomHouseEstateId { get; set; }
        public Int32 HouseId { get; set; }
        public List<Int32> HouseList { get; set; }
        public Int32 AllocationStatusId { get; set; }
        public DateTime AllocationDate { get; set; }
        public DateTime ExpectedExitDate { get; set; }
        public DateTime ActualExitDate { get; set; }
    }
}

Please help.

**Comment by gfo2007** [comment]
Hi @sayuga thanks for the reply. I will uncomment the MinSelectLevel(SelectLevel.Details) though I am not sure what that line does. And yes the typeof(CompanyAllocationsRow) is within the CompanyAllocationsRow class because I use the CompanyAllocations dialog to link houses to a company. The reason I am using this approach is that I want to separate MasterData (Company entries and House entries) from transactional data (Company Allocation entries) though I know for most examples in serenity, the allocations would have happened on the company dialog.

Any ideas on what could be the problem and how I can solve it?

**Comment by hannesb** [comment]
You need another table for LinkingSetRelation. The logical name would be CompanyAllocationHousesRow. Move the HouseId field to that table, so that it will have the fields CompanyAllocationHouseId, CompanyId and HouseId.

The use of MinSelectLevel is to load the data only when required. Normally you don't need to load data from CompanyAllocationHousesRow for the grid display, only for the editing dialog. That's what 'SelectLevel.Details' does.

**Comment by gfo2007** [comment]
Hello @hannesb, the CompanyAllocations table has both CompanyId and HouseId already so I don't want to create another table again to do that otherwise it will defeat the purpose of the CompanyAllocations table I already have.

**Comment by hannesb** [comment]
Two options:

Either store the list of HouseIds in a string field (sample data: 284,259,1234) in CompanyAllocations table. In that case, you don't need a LinkingSetRelation.

Or create the CompanyAllocationHouses table und use the LinkingSetRelation.

**Comment by gfo2007** [comment]
@hannesb does it mean that I can't use the typeof(CompanyAllocationsRow) within the CompanyAllocationsRow class?

**Comment by hannesb** [comment]
Hmm well it might be possible, but looks like a really bad database design to me.

**Comment by hannesb** [comment]
Actually if you allow NULLs on HouseId it might work. But not like you itended I think.

**Comment by gfo2007** [comment]
The data base design is not a bad one. CompanyAllocations is the composite table for linking Companies and Houses so it has CompanyId and HouseId. For the examples in serenity I have seen, the multiple houseIds would have been selected from the Company dialog (eg. selecting CustomerRepresentatives from the Customer dialog). However, I want master data dialogs like Company and Houses to be used for their own entries and then use the Company Allocations dialog to link Company Ids to House Ids.

Allowing or not allowing nulls is not really the problem because if I allowed nulls, it will mean that the record will save without saving the house Ids despite selecting the house Ids. I need to be able save each of the house Ids with the company id.

**Comment by gfo2007** [comment]
@hannesb I get your point about allowing nulls since it may have to first commit the company id and then use the companyid to update the houseids. Let me try it and give you feedback on whether ti will work.

**Comment by gfo2007** [comment]
@hannesb though it worked when I allowed nulls on houseId, I am realizing that it first inserted the companyId and then went ahead to insert two new records with the houseIds. See image below.

![company alloc 4](https://user-images.githubusercontent.com/14317420/37199291-1bbd74fe-2379-11e8-9a2e-5b3eccbd6230.PNG)


So it appears I may have to do the allocations on the Companies dialog so that when the company's Id is saved, the Id will be used to save the houseIds in the CompanyAllocations table. I wanted to avoid it but it appears I may not have a choice.

Or do you have another suggestion that will make what I want to do work?

**Comment by hannesb** [comment]
No.

You have a many-to-many relation (or m:n), best way to realize this in a relational database is an extra table.

**Comment by gfo2007** [comment]
yes I have a many to many relationship between Company and House. This relationship is what led to the creation of CompanyAllocations table which contains CompanyId and HouseId.

**Comment by hannesb** [comment]
Is the many to many relationship between Company and House or between Allocation and House?

**Comment by gfo2007** [comment]
It is between Company and House. Allocation is just a nomenclature I am using in the composite table to indicate that a company has been allocated houses. So Allocation is not a table. It is just a name. Please do you get it now?

**Comment by hannesb** [comment]
But you have extra infos in the composite table like Status, Allocation Date, etc.. Should those infos be identical for all houses 'booked' in one allocation, or different for each house?

**Comment by gfo2007** [comment]
It may or may not be identical. For instance if 3 houses are being allocated to a company on the same day, their status(active,inactive,... for active and historical records) and allocation dates will be same.

The idea is to allow the user to either allocate one or more houses to a company at one entry screen if he/she chooses to do so based on the info given.

**Comment by hannesb** [comment]
Well then.

The many-to-many relationship is between Allocation and Houses :-)

**Comment by gfo2007** [comment]
No. there is no table called Allocation. The relationship is between Company and Houses. I could have named the composite table CompanyHouses. I just chose to name it CompanyAllocations. Don't let the name of the table confuse you.

**Comment by hannesb** [comment]
Well you wrote '...allocate one **_or more_** Houses...' This **_is_** a many-to-many relationship between Allocation and Houses, isn't it.

**Comment by gfo2007** [comment]
No. Like I said. it is just nomenclature. the tables are 3. Company table which contains CompanyId, Houses table which contains HouseId and their many-many table which I named CompanyAllocations containing both CompanyId and HouseId. I could have named this table CompanyHouses. so don't focus on the name of the table but what it does.

**Comment by hannesb** [comment]
What does the design of your table (whatever the name is) say?

For Company A and House B, their is a certain relationship for a given timespan with a given status. Timespan an status are only valid for this specific combination of Company and House. Right?

**Comment by gfo2007** [comment]
The design of the table says that a company will be allocated some houses. When the contract of the company is over, the company will exit the houses that were allocated to it meaning the status will change. However these records will be kept for historical purposes. Doe this make it clear?

**Comment by hannesb** [comment]
Their it is again: 'some houses'

**Comment by gfo2007** [comment]
I meant any number of houses as agreed to be given the company

**Comment by hannesb** [comment]
Fine. Then stop thinking that you can select more than one house in the Company Allocation form. Just fill out one form for each house.

**Comment by gfo2007** [comment]
I know that is the ideal. Unfortunately if a user has to allocate for instance 10 houses and will have to do this one after the other, by doing 10 clicks, it can get boring so I was trying to avoid that especially when the other extra field values like status and allocation date ain't diiferent.

**Comment by hannesb** [comment]
Ah ok. Maybe you what to create a bunch of rows in the table with the Create Company Allocation form?

**Comment by gfo2007** [comment]
Exactly @hannesb. 
![company alloc 4](https://user-images.githubusercontent.com/14317420/37204814-3aa93fd6-238a-11e8-86e7-3eb8ab7f777e.PNG)

Some like this at one click

**Comment by hannesb** [comment]
Ah, we're getting closer...

LinkingSetRelation is not good for that.

You could try:

- Remove the LinkingSetRelation Attribute, keep 'NotMapped' and add 'HideOnUpdate'
- Modify the SaveRequestHandler in your ___Repository.cs class to something like this:

        private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void ExecuteSave()
            {
                foreach(var houseId in Row.Houses)
                {
                    Row.HouseId = houseId;
                    base.ExecuteSave();
                }
            }
        }

I'm not sure about bad side effects though

**Comment by gfo2007** [comment]
Oh ok cool. Let me try the code out and see. Will give you feedback.

**Comment by hannesb** [comment]
You should add if (IsCreate), because this makes no sense on updates

**Comment by gfo2007** [comment]
This is the code:

 private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void ExecuteSave()
            {
                if (IsCreate)
                {
                    foreach (var houseId in Row.HouseList)
                    {
                        Row.HouseId = houseId;
                        base.ExecuteSave();
                    }
                } 
            }
        }

However, when I try it out on the dialog, this error shows up.

![company alloc 5](https://user-images.githubusercontent.com/14317420/37206108-3ea46df4-238f-11e8-9a4c-febb22df96e4.PNG)

**Comment by hannesb** [comment]
Set CompanyAllocationId to NULL before calling base.ExecuteSave()?

And you will need to call base.ExecuteSave() on the else branch of if (IsCreate)

And **WARNING**: This will not work for rows that are using one of these [behaviors](https://github.com/volkanceylan/Serenity/tree/master/Serenity.Services/RequestHandlers/IntegratedFeatures) (which seems not to be the case here).

**Comment by gfo2007** [comment]
The code:

 protected override void ExecuteSave()
            {
                if (IsCreate)
                {
                    foreach (var houseId in Row.HouseList)
                    {
                        Row.CompanyAllocationId = null;
                        Row.HouseId = houseId;
                        base.ExecuteSave();
                    }
                }
                else
                {
                    base.ExecuteSave();
                }
            }

Same error. Am I doing soemthing wrong?

**Comment by gfo2007** [comment]
Hi @hannesb I realized ExecuteSave had Connection.Insert(Row) in it so I removed the base.ExecuteSave() which was giving me error and replaced it with Connection.Insert(Row) and viola it saves without an error.

Thanks so much for all the time and patience you had to help me through this. I appreciate your efforts. 

Cheers

**Comment by gfo2007** [comment]
@hannesb another error. After the records have been saved, I tried to open the dialog for one of them and the error below keeps showing up meanwhile CompanyId is a valid column name.

![company alloc 7](https://user-images.githubusercontent.com/14317420/37215164-1a402c26-23af-11e8-9a63-3c20f4f3db72.PNG)

**Comment by stixoffire** [comment]
Just going to say the Order and Items in Northwind  Customer > Orders > items

A Customer can have many orders , and and order can have many items and 1 item can belong to many orders ..

Just saying for others that might do this. The design of  gfo2007 database is fine the way he had it to begin with - link set relation (I would not use - a master detail yes)
