### ISSUE TITLE
Yeni Field eklendiğinde..

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#334]
Merhaba Volkan Bi sorum var. Bi tablo yaptık ve sergen ile formları urettık dıyelım. Sonra tabloya bir field daha eklersem tekrar sergen ile olusturmak gerekiyor degil mi ? Manuel eklememeliyiz degil mi, script projesinde kendi eklediklerini atlamamak için. 

Ya da yontem nedir ? 

Selamlar

**Comment by volkanceylan** [comment]
Hayır manuel eklemek daha iyi, row, form ve columns nerede gerekiyorsa

**Comment by Olricz** [comment]
Eywallah.
