### ISSUE TITLE
Edit Button Text

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3340]
Hi,

I want to change the existing 'add-button' text value. How to do this? can anyone please help?

**Comment by hairangsua** [comment]
protected getToolbarButtons(): Serenity.ToolButton[] {
            var btns = super.getToolbarButtons();
            btns[0].title = "your text";
            return btns;
        }

Or

 this.saveAndCloseButton.text("your text");

**Comment by AmuthaKondusamy** [comment]
@hairangsua  Thanks for your quick help.
But when I add this piece of code in XYZGrid.ts, the button gets disappeared.
       
 protected getButtons() {
            var buttons = super.getButtons();
            var btn = Q.first(buttons, x => x.cssClass == "add-button");
            btn.title = Q.text("test");
  }

**Comment by AmuthaKondusamy** [comment]
Hi @hairangsua ,

Thank you so much for your Quick help.
It worked as expected.

**Comment by AmuthaKondusamy** [comment]
Hi @hairangsua,

How to achieve the same for the editor's existing add-button?

**Comment by chrisomeara** [comment]
apologies, I am new to serenity and trying to move out of dependence on MS access, I would also like to change the add-button text, which file is the above code segment placed?
