### ISSUE TITLE
LinkingSetRelation

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#3341]
[LinkingSetRelation(typeof(TanimMasterDetayRow), "EntityId", "DetayId")]
Birden fazla parametre gönderebilirmiz     şuan tek parametreye göre yapıyor.
Örnegin
 [LinkingSetRelation(typeof(TanimMasterDetayRow), "EntityId", "DetayId","Id","MasterId")]şeklinde olabilir mi?

**Comment by AlperanQ** [comment]
Olabilir, deneyebilirsiniz.
