### ISSUE TITLE
Get current user login

### ISSUE THREAD

**Issue by postonoh** [volkanceylan/Serenity#3345]
I know traditional mvc get current user.
var user = UserManager.FindById(User.Identity.GetUserId());
System.Web.HttpContext.Current.User.Identity.GetUserId();

How do I get with serenity frameworkk.

**Comment by postonoh** [comment]
never mind got it

**Comment by glenngsanchez** [comment]
Hi @postonoh, Can you share your solution?

**Comment by Estrusco** [comment]
((UserDefinition)Serenity.Authorization.UserDefinition).UserId

**Comment by ArunkumarRamkumar** [comment]
> ((UserDefinition)Serenity.Authorization.UserDefinition).UserId

It's working :)
