### ISSUE TITLE
Invalid column name 'CompanyId'

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3347]
Hi,
**CompanyId** is a foreign key in a table called CompanyAllocations and it was successfully generated by sergen. It is however surprising that when you try to view any record in the CompanyAllocations grid by clicking on any EditLink field, it throws the error in the image below
![company alloc 7](https://user-images.githubusercontent.com/14317420/37257157-3604893e-255d-11e8-82a6-275cce4ca4e9.PNG)

Below is the code for the CompanyAllocationsRow

namespace hails.HouseAllocations.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;
    using hails.MasterData.Entities;
    using System.Collections.Generic;

    [ConnectionKey("Default"), Module("HouseAllocations"), TableName("[hails].[CompanyAllocations]")]
    [DisplayName("Company Allocations"), InstanceName("Company Allocation")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class CompanyAllocationRow : Row, IIdRow
    {
        [DisplayName("Company Allocation Id"), Identity, Hidden]
        public Int32? CompanyAllocationId
        {
            get { return Fields.CompanyAllocationId[this]; }
            set { Fields.CompanyAllocationId[this] = value; }
        }

        [DisplayName("Company"), NotNull, ForeignKey("[hails].[Companies]", "CompanyId"), LeftJoin("jCompany"), TextualField("CompanyCompanyName")]
        [LookupEditor(typeof(CompanyRow))]
        public Int32? CompanyId
        {
            get { return Fields.CompanyId[this]; }
            set { Fields.CompanyId[this] = value; }
        }

        [DisplayName("House"), ForeignKey("[hails].[Houses]", "HouseId"), LeftJoin("jHouse"), TextualField("HouseHouseNo"), Hidden]
        [LookupEditor(typeof(HouseRow), CascadeFrom = "CustomHouseEstateId", CascadeField = "EstateId")]
        public Int32? HouseId
        {
            get { return Fields.HouseId[this]; }
            set { Fields.HouseId[this] = value; }
        }

        [DisplayName("Allocation Status"), ForeignKey("[hails].[Statuses]", "StatusId"), LeftJoin("jAllocationStatus"), TextualField("AllocationStatusStatusName")]
        [LookupEditor(typeof(StatusRow))]
        public Int32? AllocationStatusId
        {
            get { return Fields.AllocationStatusId[this]; }
            set { Fields.AllocationStatusId[this] = value; }
        }

        [DisplayName("Allocation Date")]
        public DateTime? AllocationDate
        {
            get { return Fields.AllocationDate[this]; }
            set { Fields.AllocationDate[this] = value; }
        }

        [DisplayName("Expected Exit Date")]
        public DateTime? ExpectedExitDate
        {
            get { return Fields.ExpectedExitDate[this]; }
            set { Fields.ExpectedExitDate[this] = value; }
        }

        [DisplayName("Actual Exit Date")]
        public DateTime? ActualExitDate
        {
            get { return Fields.ActualExitDate[this]; }
            set { Fields.ActualExitDate[this] = value; }
        }

        [DisplayName("Company"), Expression("jCompany.[CompanyName]")]
        public String CompanyCompanyName
        {
            get { return Fields.CompanyCompanyName[this]; }
            set { Fields.CompanyCompanyName[this] = value; }
        }

        [DisplayName("Company Contact Name"), Expression("jCompany.[ContactName]")]
        public String CompanyContactName
        {
            get { return Fields.CompanyContactName[this]; }
            set { Fields.CompanyContactName[this] = value; }
        }

        [DisplayName("Company Contact No"), Expression("jCompany.[ContactNo]")]
        public String CompanyContactNo
        {
            get { return Fields.CompanyContactNo[this]; }
            set { Fields.CompanyContactNo[this] = value; }
        }

        [DisplayName("House No"), Expression("jHouse.[HouseNo]")]
        public String HouseHouseNo
        {
            get { return Fields.HouseHouseNo[this]; }
            set { Fields.HouseHouseNo[this] = value; }
        }

        [DisplayName("Estate Id"), Expression("jHouse.[EstateId]")]
        public Int32? HouseEstateId
        {
            get { return Fields.HouseEstateId[this]; }
            set { Fields.HouseEstateId[this] = value; }
        }

        [DisplayName("Company Id"), Expression("jHouse.[CompanyId]")]
        public Int32? HouseCompanyId
        {
            get { return Fields.HouseCompanyId[this]; }
            set { Fields.HouseCompanyId[this] = value; }
        }

        [DisplayName("House Status Id"), Expression("jHouse.[HouseStatusId]")]
        public Int32? HouseHouseStatusId
        {
            get { return Fields.HouseHouseStatusId[this]; }
            set { Fields.HouseHouseStatusId[this] = value; }
        }

        [DisplayName("Allocation Status"), Expression("jAllocationStatus.[StatusName]")]
        public String AllocationStatusStatusName
        {
            get { return Fields.AllocationStatusStatusName[this]; }
            set { Fields.AllocationStatusStatusName[this] = value; }
        }

        [DisplayName("Estate"), Expression("jHouse.[EstateId]"), ForeignKey("hails.Estates", "EstateId"), LeftJoin("jEstate"), TextualField("CustomHouseEstateName")]
        [LookupEditor(typeof(EstateRow), InplaceAdd =true, AutoComplete = true)]
        public Int32? CustomHouseEstateId
        {
            get { return Fields.CustomHouseEstateId[this]; }
            set { Fields.CustomHouseEstateId[this] = value; }
        }

        [DisplayName("Estate"), Expression("jEstate.[EstateName]")]
        public String CustomHouseEstateName
        {
            get { return Fields.CustomHouseEstateName[this]; }
            set { Fields.CustomHouseEstateName[this] = value; }
        }

        [LookupEditor(typeof(HouseRow), Multiple = true, CascadeFrom = "CustomHouseEstateId", CascadeField = "EstateId"), NotMapped]
        //[LinkingSetRelation(typeof(CompanyAllocationRow), "CompanyId", "HouseId")]
        //[MinSelectLevel(SelectLevel.Details), QuickFilter(CssClass = "hidden-xs")]
        [DisplayName("Houses"), NotNull]
        public List<Int32> HouseList
        {
            get { return Fields.HouseList[this]; }
            set { Fields.HouseList[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.CompanyAllocationId; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public CompanyAllocationRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field CompanyAllocationId;
            public Int32Field CompanyId;
            public Int32Field HouseId;
            public Int32Field AllocationStatusId;
            public DateTimeField AllocationDate;
            public DateTimeField ExpectedExitDate;
            public DateTimeField ActualExitDate;

            public StringField CompanyCompanyName;
            public StringField CompanyContactName;
            public StringField CompanyContactNo;

            public StringField HouseHouseNo;
            public Int32Field HouseEstateId;
            public Int32Field HouseCompanyId;
            public Int32Field HouseHouseStatusId;

            public StringField AllocationStatusStatusName;

            public Int32Field CustomHouseEstateId;
            public StringField CustomHouseEstateName;

            public ListField<Int32> HouseList;

        }
    }
}

**Comment by dfaruque** [comment]
Check your database table.
Have you modified the Row.cs after generating?

**Comment by gfo2007** [comment]
The table is fine. Sergen was used to generate Row fields. The only modification made to the Row class was the addition of EstateId expression to enable me access EstateName and I also added an unmaaped field called the HouseList which I commit to database via the Repository class.

**Comment by gfo2007** [comment]
I didn't really try it before I made changes. I have never seen this error on the few small projects i've tried out with serenity.

**Comment by dfaruque** [comment]
check your Grid.ts, Repository.cs, Column.cs is there any customization?

**Comment by Estrusco** [comment]
Also check if CompanyId is present in jHouse join - Expression("jHouse.[CompanyId]")]

**Comment by gfo2007** [comment]
Thanks @Estrusco. I think initially I had CompanyId in the House table but I deleted it and created a composite table for Houses and Companies. I should have edited the code in the Row class to refelect the changes I made in the database. It works perfectly now.
