### ISSUE TITLE
UndeleteHandler hk.

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#335]
1.9.17 den sonra sergen ile Undelete olusmadı repositoryde ?  IsActive var. 
```
public sealed class AdresTipiRow : LoggingRow, IIdRow, INameRow, IMultiTenantRow
public abstract class LoggingRow : Row, IIsActiveDeletedRow, ILoggingRow, IDeleteLogRow
```

**Comment by Olricz** [comment]
Bu ozellik kaldırıldı mı ?

**Comment by Olricz** [comment]
Evet kaldırmıssın. Abi bu önemli bi ozellikti neden kaldırdın bilemedim.  Kendi Serenity'imizi yaptık. :)

**Comment by volkanceylan** [comment]
Sadece Undelete i kaldırdım alan isminden anlaşılmıyor silinme mi inaktif anlamında mı. Sonuçta interface i ekleyip undelete i endpoint ve repository ye copy paste ile alabilirsiniz.

**Comment by Olricz** [comment]
Ben Sergen.exe senin sildiklerini ekledim. Gerek yok mudu. Interface i ekleyip derken ;?

**Comment by volkanceylan** [comment]
Sergen o metodları ekliyor ama Row a IIsActive/IIsActiveDeleted eklemediği için T4 ler dönüştürüldüğünde hata alıyorlardı, o yüzden kodu sildim.

Tekrar geri getirebilirim, ama önce IsActive ya da IsActiveDeleted olup olmadığını belirlemek için bir metod lazım. Integer tipindeyse IsActiveDeleted, bool sa IsActive olabilir.

Ben yapana kadar eski Serenity'nin sergen.exe sini alıp kullanabilirsiniz.

Ya da Undelete methodlarını repository ve endpoint.cs inize başka bir repository den kopyalayabilirisniz.

**Comment by Olricz** [comment]
Tamamdır. Yine de yapılabiliyor olması guzel. Yazdıgın gıbı fieldlar var mı diye kontrol edip eklersek olur bu iş. 
Kolay gelsin.
