### ISSUE TITLE
Auto adjustable Field width in Grid

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3351]
Hi,

can anyone please help me to adjust the field's width in XYZGrid according to the longest text in the overall grid?

**Comment by AmuthaKondusamy** [comment]
@volkanceylan Can you please suggest some solution to this?

**Comment by Estrusco** [comment]
See this https://github.com/Estrusco/Serenity.Extra or ask to @dfaruque

**Comment by AmuthaKondusamy** [comment]
Hi @dfaruque,

Can you please help me on this?

**Comment by dfaruque** [comment]
Please read the readme at https://github.com/dfaruque/Serenity.Extra
Currently, it auto-sizes columns according to their header text

**Comment by AmuthaKondusamy** [comment]
Hi @dfaruque,

By using Serenity-Extra we have to specify the width of the particular column right?
I need to adjust the width automatically (dynamically) with respect to the longest text in that field.
Is that possible?

**Comment by dfaruque** [comment]
no. 
it adjusts the width automatically (dynamically) with respect to the **header text** in that field.

**Comment by AmuthaKondusamy** [comment]
okay. Thanks for your clarification.
Closing this issue.
