### ISSUE TITLE
Getting this error message

### ISSUE THREAD

**Issue by postonoh** [volkanceylan/Serenity#3352]
Getting following error message, add a new table add a dynamic logo and favicon 
TableName: Logo
ColumnNames:
ID int identity
Logo NVarchar (200)
Favicon Nvarchar (200)

Query affected 0 rows while 1 expected! This might mean that your query lacks a proper WHERE statement or a TRIGGER changes number of affected rows. In the latter case, you may try adding "SET NOCOUNT ON" to your trigger code.

**Comment by postonoh** [comment]
Fixed my problem thanks

**Comment by resitaufan** [comment]
@postonoh please sharing your solution
