### ISSUE TITLE
Can I call another function in a function in Endpoint?

### ISSUE THREAD

**Issue by gyygyy32** [volkanceylan/Serenity#3354]
Code is below
public TaskConfirmResponse TaskConfirm(IDbConnection connection, TaskConfirmRequset request)
{
     .......
   var res =   UpdateQualifiedQty(connection, newUpdateQtyRequest {..} )
}
public UpdateQtyResponse UpdateQualifiedQty(IDbConnection connection, UpdateQtyRequest request)
{
   .........
}
It is OK?

**Comment by dfaruque** [comment]
I think it is Okay.
