### ISSUE TITLE
PermissionKeys

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#336]
i have added a Permission key to  PermissionKeys "to be used as intellisense" 

` [PageAuthorize(PermissionKeys.HomePagePeViewpages)]
    public class DashboardController : Controller
    {`

on PermissionKeys class 

` public const string HomePagePeViewpages = "PnpTools:DashBoard:View";`

but its not showing in the Permissions page ? tried rebuilding /transform templates rebuild but its not showing

**Comment by jsbUSMC** [comment]
You need to add the to the `site.texts.invariant.json` file in MyProject.Web

**Comment by volkanceylan** [comment]
Does other keys e.g. PnpTools:Test showing?

**Comment by zerodev** [comment]
the keys are in the invariant json file, and others are showing

**Comment by volkanceylan** [comment]
Seems like PageAuthorize attribute is not located 

In UserPermissionRepository.cs, find code below:

```cs
                    foreach (var type in assembly.GetTypes())
                    {
                        ProcessAttributes<PermissionAttributeBase>(result, type, x => x.Permission);
                        ProcessAttributes<ServiceAuthorizeAttribute>(result, type, x => x.Permission);

                        foreach (var member in type.GetMethods(BindingFlags.Instance | BindingFlags.Public))
                        {
                            ProcessAttributes<PermissionAttributeBase>(result, member, x => x.Permission);
                            ProcessAttributes<ServiceAuthorizeAttribute>(result, member, x => x.Permission);
                        }
                    }
```

Replace with this:

                    foreach (var type in assembly.GetTypes())
                    {
                        ProcessAttributes<PageAuthorizeAttribute>(result, type, x => x.Permission);
                        ProcessAttributes<PermissionAttributeBase>(result, type, x => x.Permission);
                        ProcessAttributes<ServiceAuthorizeAttribute>(result, type, x => x.Permission);

                        foreach (var member in type.GetMethods(BindingFlags.Instance | BindingFlags.Public))
                        {
                            ProcessAttributes<PageAuthorizeAttribute>(result, member, x => x.Permission);
                            ProcessAttributes<PermissionAttributeBase>(result, member, x => x.Permission);
                            ProcessAttributes<ServiceAuthorizeAttribute>(result, member, x => x.Permission);
                        }
                    }

**Comment by zerodev** [comment]
that was the issue 
                        ProcessAttributes<PageAuthorizeAttribute>(result, member, x => x.Permission);
was missing
to avoid this again should i allwasy check UserPermissionRepository.cs what was the reason ?

**Comment by volkanceylan** [comment]
I forgot to traverse PageAuthorize, that was the reason, will be fixed in next template
