### ISSUE TITLE
Multiple Project

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3365]
Hi

would it be feasible to split solution into multiple project? We are facing problems when two developers add files to project. We have to merge it all the time and its becoming quite painful.
Specifically one is working on migrations, the other on the pages...
Any suggestions would be appreciated.

**Comment by edwardch** [comment]
You could split the Serenity components into their own projects, and reference those projects from your Serene project. This is assuming you are wanting to work on different components of Serenity.

Are you using TFS or git? Are you using separate branches?

I use git (hosted by Visual Studio / MS) and have not struggled yet...

**Comment by kilroyFR** [comment]
you can make each dev a separate project that delivers a nuget. So from time to time each team publish nuget and other team get updates. That could work actually (what i did on my side).

**Comment by ga5tan** [comment]
@edwardch VSTS. had problems mergin project file, when two guys added files to it.
@kilroyFR sounds quite complicated, but I will check into it
thx for sugestions
