### ISSUE TITLE
how to use Inner Join With Expression On Row Field Contains Where Clause.

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#3368]
`Expression(("Select` CustomerDetails.CustomerID ,CustomerDetails.RegionID from [CustomerDetails] T0 INNER JOIN [UserRegions] T1 ON T0.RegionID = T1.RegionID Where T1.UserId =" + **Authorization.UserId** ))
i want filter on userid
How to Achive this..

**Comment by hannesb** [comment]
Not sure what you are trying to do. Can you explain a bit more?

**Comment by ANDY7575** [comment]
@hannesb  
Actully im having Enquiry table
fields:enquiryid, customerId, RegionId and many more
 With customerid as ForeignField of CustomerDetails ,now
i am having another table UserRegion Contains 
fields: UserId , RegioniD,
here i want to load only that customer Which having same Region as User have 
so i have prepared query as below working fine,i just want to know where to apply
`select CustomerDetails.CustomerID ,CustomerDetails.RegionID
from CustomerDetails
  inner join UserRegions on CustomerDetails.RegionID = UserRegions.RegionID
  where UserRegions.UserId=35`
thanx

**Comment by hannesb** [comment]
You could customize the ListRequestHandler in EnquiryRepository.cs (just guessing the name)

**Comment by ANDY7575** [comment]
@hannesb  
thanx for your quick reply.
will try n let u know..

**Comment by ANDY7575** [comment]
@hannesb 
i tried like below,
still not working.
please have a look and suggest me where to currect.
` protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);
                query.Where("select T0.CustomerID from [CustomerDetails] T0 INNER JOIN [UserRegions] T1 ON T0.RegionID = T1.RegionID Where T1.UserId =" + Authorization.UserId);
            }`

**Comment by hannesb** [comment]
Try something similar to the ListRequestHandler in OrderRepository.cs (Northwind sample).
You probably need two .From() clauses, adjust the .Where() clause as required.

**Comment by ANDY7575** [comment]
thank you ..still i am struggling  to find ,any help is appreciated.

**Comment by hannesb** [comment]
Have you studied the section about [Fluent SQL](https://volkanceylan.gitbooks.io/serenity-guide/content/fluent_sql/fluent_sql.html) in the Dev Guide?

**Comment by hannesb** [comment]
The right place to apply filters is - ApplyFilter() (sic!)

**Comment by ANDY7575** [comment]
thank you.
i will look into it.
