### ISSUE TITLE
sergen.exe error

### ISSUE THREAD

**Issue by LucianoCimenti** [volkanceylan/Serenity#337]
hello,
I'm trying your interesting generator, but I met this error running sergen.exe after choice "default" on connection string field:
System.Configuration.ConfigurationErrorsException: The section "DbProviderFactories" it can appear only once in each configuration file....  

![sergen_error](https://cloud.githubusercontent.com/assets/17531373/13380736/04a32c44-de4a-11e5-8588-09cad9d42757.png)

where am I doing wrong?
many thanks in advance
Luciano Cimenti

**Comment by volkanceylan** [comment]
Check your web.config and sergen.config you probably have multiple DbProviderFactories section inside. Are you using some other database?

**Comment by LucianoCimenti** [comment]
I could not find the DbProviderFactories section in all *.config files on my pc. Can you suggest where they should be?

**Comment by volkanceylan** [comment]
Can you paste contents of Serenity.CodeGenerator.config file in your solution directory?

**Comment by LucianoCimenti** [comment]
Serenity.CodeGenerator.config is already in ...\MovieTutorial folder
The content is:
****************
{
    "Connections": [],
    "KDiff3Path": "C:\\Program Files (x86)\\KDiff3\\kdiff3.exe",
    "WebProjectFile": "..\\..\\..\\MovieTutorial\\MovieTutorial.Web\\MovieTutorial.Web.csproj",
    "ScriptProjectFile": "..\\..\\..\\MovieTutorial\\MovieTutorial.Script\\MovieTutorial.Script.csproj",
    "RootNamespace": "MovieTutorial",
    "BaseRowClasses": [],
    "RemoveForeignFields": []
}
***********

**Comment by volkanceylan** [comment]
Hmm ok, can you also paste packages\Serenity.CodeGenerator.x.y.z\content\tools\sergen.exe.config

**Comment by LucianoCimenti** [comment]
doesn't exist sergen.exe.config in any sub path...

**Comment by volkanceylan** [comment]
Then my only guess is some faulty driver put duplicate DBFactory entries in machine.config

Look under C:\Windows\Microsoft.Net\Framework64\v4.0...\machine.config

Did you install a .NET provider for a third party database?

**Comment by volkanceylan** [comment]
Looks like something like this to me
http://stackoverflow.com/questions/23754055/sqlite-error-the-dbproviderfactories-section-can-only-appear-once-per-config

**Comment by LucianoCimenti** [comment]
Yes, I have "IBM DB2 for i .NET Provider" (and also "Microsoft SQL Server Compact Data Provider" plus "Microsoft SQL Server Compact Data Provider 4.0").

**Comment by volkanceylan** [comment]
So your issue that buggy DB2 installer. Info in link.

**Comment by LucianoCimenti** [comment]
Now work! 
thanks a lot
