### ISSUE TITLE
Close order button!

### ISSUE THREAD

**Issue by amonragz** [volkanceylan/Serenity#3378]
I want to place a button with an inner function where it's going to put the current date in shipped date field and then load listed orders dashboard, closing the order.

I tried this but it doesn't work

            buttons.push({
                title: 'Close Order', cssClass: 'edit-button',
                onClick: () => {
                  var dlg = new TrackLog.OrderDialog();
                  this.load(<TrackLog.OrderRow>{
                      ShippedDate: Q.formatDate(new Date(), 'yyyy-MM-dd'),
                  }
            });
            return buttons;

In order dialog, creates a new instance of order with the current date. How can I do described function.

**Comment by she-ll-b-rite** [comment]
hi there. apologies up front if i've misunderstood your question. 
what i believe you are asking is, you want to add a toolbar button to the OrderDialog, that when clicked, will:

1. populate the current date in the 'ShippedDate' field
2. save the current order 
3. open a dialog called 'ListedOrdersDashboard' &
4. close the current OrderDialog

```
onClick: () => {
    // 1. populate the current date in the 'ShippedDate' field
    this.form.ShippedDate.value = Q.formatDate(new Date(), 'yyyy-MM-dd');
    // 2. save the current order
    this.save(response => {
        // 3. open a dialog called 'ListedOrdersDashboard' 
        (new ListedOrdersDashboardDialog()).dialogOpen();
        // 4. close the current OrderDialog
        this.dialogClose()
    });
}
```
HTH

**Comment by amonragz** [comment]
Ready it should be like this, and works fine, thank you so much:

            buttons.push({
                title: 'Close Order', cssClass: 'edit-button',
                onClick: () => {
                    this.form.ShippedDate.value = Q.formatDate(new Date(), 'yyyy-MM-dd');
                    this.save(response => {
                        Q.notifySuccess("Closed order on " +
                            Q.formatDate(new Date(), 'yyyy-MM-dd') + " Order Number: " +
                            response.EntityId + " ");
                        this.dialogClose()
                    }
            }
