### ISSUE TITLE
Customizing Display of Fields on Page

### ISSUE THREAD

**Issue by absaakash** [volkanceylan/Serenity#338]
Hi

Based on attributes setting, your framework decorates the fields on page properly. Here Fields are listed one below other.

Field1
Field2
Field3
.
.
.

I was looking at Customizing the page and display the fields as per my/user requirement.

Field1    Field2    Field3

Field4   Field5   Field 6 

Please advise.

Thanks and Regards

**Comment by volkanceylan** [comment]
See latest template multi column dialog samples under basic samples

**Comment by rudianto2008** [comment]
Where we can see it Jaiq? In northwind sample or where? :)

**Comment by volkanceylan** [comment]
Install latest template (Serene), click Basic Samples from left navigation, and click Multi Column Dialog, clear enough? :)

**Comment by sayuga** [comment]
It may be worth noting you should download a fresh copy to see the section. I ran the update-package command on a version of Serene template I use for reference and though it updated the package, it didn't build the file properly, thus the BasicSamples files did not load.
