### ISSUE TITLE
LookupEditor filter for Form Field.how to filter join result..

### ISSUE THREAD

**Issue by ANDY7575** [volkanceylan/Serenity#3380]
@volkanceylan 
hi ,
actually i am trying to achive below result from last 4 days,
your help is must  or anyone out their aware about please help..
Structure is as below
EnquiryRow Contain Customerid[foreign key field] which i want to be filterd like below query..
`select CustomerDetails.CustomerID,CustomerDetails.CompanyName
from CustomerDetails
  inner join userRegions on CustomerDetails.RegionID = UserRegions.RegionID
  where UserRegions.UserId=35`

**Comment by 107295472** [comment]
Conditions are written here

ApplyFilters

**Comment by 107295472** [comment]
protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);
                //query.LeftJoin("RYTreasureDB.dbo.UserRoomCard", Alias.T1,Criteria.Bracket("T0.UserID"));
                //query.Select("T1.UserRoomCard");
            }
--------------------------------------------------------
I have such a list of inquiries, useless to understand

**Comment by 107295472** [comment]
Criteria  
The generated is this
[T0.UserID]
And I want this [T1.UserID]=[T0.UserID]

**Comment by ANDY7575** [comment]
@107295472  
not getting what you are asking or trying to tell..
had u faced such situation before..

**Comment by 107295472** [comment]
No, for the first time
Now use feature association tables instead

**Comment by 107295472** [comment]
Still like to use sql to write
