### ISSUE TITLE
Object Reference not set to instance of an object error

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3381]
Hi,
I am getting **"Object Reference not set to instance of an object"** error from a repository query code but I am not sure why that is happening since objects in the repository code have been instantiated. I have attached the error as an image and also added the Row and Repository code below.
![iwms object reference error](https://user-images.githubusercontent.com/14317420/37595452-c77f9034-2b70-11e8-8781-a9e2535ec0ec.PNG)

**ReceivingRepository.cs**

namespace iwms.Transactions.Repositories
{
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using System;
    using System.Data;
    using MyRow = Entities.ReceivingRow;

    public class ReceivingRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            
            protected override void AfterSave()
            {
                base.AfterSave();
                var tType = MasterData.Entities.TransactionTypeRow.Fields;
                var inv = Entities.InventoryRow.Fields;
                var transactionTypeRow = new MasterData.Entities.TransactionTypeRow();
                

                if (Row.Items != null)
                {
                    var mc = Entities.ReceivingItemRow.Fields;
                    var oldList = IsCreate ? null : Connection.List<Entities.ReceivingItemRow>(mc.ReceivingId == this.Row.ReceivingId.Value);
                    new Common.DetailListSaveHandler<Entities.ReceivingItemRow>(oldList, Row.Items, x => x.ReceivingId = Row.ReceivingId.Value).Process(this.UnitOfWork);

                    transactionTypeRow = Connection.TryFirst<MasterData.Entities.TransactionTypeRow>(t => t
                                                                                           .Select(tType.TransactionTypeId)
                                                                                           .Where(tType.TransactionTypeName == "Receiving"));

                    foreach (var item in Row.Items)
                    {
                        var invRow = new Entities.InventoryRow();
                        invRow = Connection.TryFirst<Entities.InventoryRow>(q => q
                                                        .Select(inv.StockOnHand)
                                                        .Select(inv.StockIn)
                                                        .Where(
                                                                inv.ItemId == item.ItemId.Value &
                                                                inv.StoreId == item.StoreId.Value &
                                                                inv.TransactionTypeId == Convert.ToInt32(transactionTypeRow.TransactionTypeId))
                                                        .OrderBy(inv.InventoryDate, desc: true));

                        if (invRow == null)
                        {
                            invRow.StoreId = item.StoreId.Value;
                            invRow.ItemId = item.ItemId.Value;
                            invRow.StockOnHand = item.Quantity.Value;
                            invRow.StockIn = item.Quantity.Value;
                            invRow.StockOut = 0;
                            invRow.InventoryDate = DateTime.Now.Date;
                        }
                        else
                        {

                            invRow.StoreId = item.StoreId.Value;
                            invRow.ItemId = item.ItemId.Value;
                            invRow.StockOnHand = invRow.StockOnHand + item.Quantity.Value;
                            invRow.StockIn = item.Quantity.Value;
                            invRow.StockOut = 0;
                            invRow.InventoryDate = DateTime.Now.Date;
                            invRow.TransactionTypeId = Convert.ToInt32(transactionTypeRow.TransactionTypeId);
                        }

                        Connection.Insert(invRow);
                    }

                }
            }
            
        }

        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>{}
        private class MyListHandler : ListRequestHandler<MyRow> { }
    }
}

**ReceivingRow.cs**

namespace iwms.Transactions.Entities
{
    using iwms.MasterData.Entities;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), Module("Transactions"), TableName("[iwms].[Receivings]")]
    [DisplayName("Receiving"), InstanceName("Receiving")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [LookupScript("Transactions.Receiving")]
    public sealed class ReceivingRow : Row, IIdRow, INameRow
    {
        [DisplayName("Receiving Id"), Identity]
        public Int32? ReceivingId
        {
            get { return Fields.ReceivingId[this]; }
            set { Fields.ReceivingId[this] = value; }
        }

        [DisplayName("Supplier"), ForeignKey("[iwms].[Suppliers]", "SupplierId"), LeftJoin("jSupplier"), TextualField("SupplierSupplierName")]
        [LookupEditor(typeof(SupplierRow))]
        public Int32? SupplierId
        {
            get { return Fields.SupplierId[this]; }
            set { Fields.SupplierId[this] = value; }
        }

        [DisplayName("Items"), NotMapped]
        //[MasterDetailRelation(foreignKey: "ReceivingId")]
        public List<ReceivingItemRow> Items
        {
            get { return Fields.Items[this]; }
            set { Fields.Items[this] = value; }
        }

        [DisplayName("Receiving Date"), NotNull]
        public DateTime? ReceivingDate
        {
            get { return Fields.ReceivingDate[this]; }
            set { Fields.ReceivingDate[this] = value; }
        }

        [DisplayName("Main Doc"), Size(255), FileUploadEditor(FilenameFormat = "Docs/~", OriginalNameProperty = "MainDocOriginalFileName")]
        public String MainDoc
        {
            get { return Fields.MainDoc[this]; }
            set { Fields.MainDoc[this] = value; }
        }

        [DisplayName("Original File Name"), Column("MainDocOriginalFileName"), Size(-1)]
        public String MainDocOriginalFileName
        {
            get { return Fields.MainDocOriginalFileName[this]; }
            set { Fields.MainDocOriginalFileName[this] = value; }
        }

        [DisplayName("Other Docs"), MultipleFileUploadEditor(FilenameFormat = "ExtraDocs/~")]
        public String OtherDocs
        {
            get { return Fields.OtherDocs[this]; }
            set { Fields.OtherDocs[this] = value; }
        }

        [DisplayName("Responsible Person"), NotNull, ForeignKey("[iwms].[Employees]", "EmployeeId"), LeftJoin("jResponsiblePerson"), TextualField("ResponsiblePersonEmployeeNo")]
        [LookupEditor(typeof(EmployeeRow))]
        public Int32? ResponsiblePerson
        {
            get { return Fields.ResponsiblePerson[this]; }
            set { Fields.ResponsiblePerson[this] = value; }
        }

        [DisplayName("Comments")]
        public String Comments
        {
            get { return Fields.Comments[this]; }
            set { Fields.Comments[this] = value; }
        }

        [DisplayName("Supplier Supplier Name"), Expression("jSupplier.[SupplierName]")]
        public String SupplierSupplierName
        {
            get { return Fields.SupplierSupplierName[this]; }
            set { Fields.SupplierSupplierName[this] = value; }
        }

        [DisplayName("Supplier Contact Person"), Expression("jSupplier.[ContactPerson]")]
        public String SupplierContactPerson
        {
            get { return Fields.SupplierContactPerson[this]; }
            set { Fields.SupplierContactPerson[this] = value; }
        }

        [DisplayName("Supplier Contact No"), Expression("jSupplier.[ContactNo]")]
        public String SupplierContactNo
        {
            get { return Fields.SupplierContactNo[this]; }
            set { Fields.SupplierContactNo[this] = value; }
        }

        [DisplayName("Supplier Supplier Address"), Expression("jSupplier.[SupplierAddress]")]
        public String SupplierSupplierAddress
        {
            get { return Fields.SupplierSupplierAddress[this]; }
            set { Fields.SupplierSupplierAddress[this] = value; }
        }

        [DisplayName("Supplier Location Id"), Expression("jSupplier.[LocationId]")]
        public Int32? SupplierLocationId
        {
            get { return Fields.SupplierLocationId[this]; }
            set { Fields.SupplierLocationId[this] = value; }
        }

        [DisplayName("Responsible Person Employee No"), Expression("jResponsiblePerson.[EmployeeNo]")]
        public String ResponsiblePersonEmployeeNo
        {
            get { return Fields.ResponsiblePersonEmployeeNo[this]; }
            set { Fields.ResponsiblePersonEmployeeNo[this] = value; }
        }

        [DisplayName("Responsible Person First Name"), Expression("jResponsiblePerson.[FirstName]")]
        public String ResponsiblePersonFirstName
        {
            get { return Fields.ResponsiblePersonFirstName[this]; }
            set { Fields.ResponsiblePersonFirstName[this] = value; }
        }

        [DisplayName("Responsible Person Last Name"), Expression("jResponsiblePerson.[LastName]")]
        public String ResponsiblePersonLastName
        {
            get { return Fields.ResponsiblePersonLastName[this]; }
            set { Fields.ResponsiblePersonLastName[this] = value; }
        }

        [DisplayName("Responsible Person Gender Id"), Expression("jResponsiblePerson.[GenderId]")]
        public Int32? ResponsiblePersonGenderId
        {
            get { return Fields.ResponsiblePersonGenderId[this]; }
            set { Fields.ResponsiblePersonGenderId[this] = value; }
        }

        [DisplayName("Responsible Person Phone No"), Expression("jResponsiblePerson.[PhoneNo]")]
        public String ResponsiblePersonPhoneNo
        {
            get { return Fields.ResponsiblePersonPhoneNo[this]; }
            set { Fields.ResponsiblePersonPhoneNo[this] = value; }
        }

        [DisplayName("Responsible Person Email Address"), Expression("jResponsiblePerson.[EmailAddress]")]
        public String ResponsiblePersonEmailAddress
        {
            get { return Fields.ResponsiblePersonEmailAddress[this]; }
            set { Fields.ResponsiblePersonEmailAddress[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.ReceivingId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.MainDoc; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public ReceivingRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field ReceivingId;
            public Int32Field SupplierId;
            public DateTimeField ReceivingDate;
            public StringField MainDoc;
            public StringField OtherDocs;
            public Int32Field ResponsiblePerson;
            public StringField Comments;

            public StringField SupplierSupplierName;
            public StringField SupplierContactPerson;
            public StringField SupplierContactNo;
            public StringField SupplierSupplierAddress;
            public Int32Field SupplierLocationId;

            public StringField ResponsiblePersonEmployeeNo;
            public StringField ResponsiblePersonFirstName;
            public StringField ResponsiblePersonLastName;
            public Int32Field ResponsiblePersonGenderId;
            public StringField ResponsiblePersonPhoneNo;
            public StringField ResponsiblePersonEmailAddress;

            public StringField MainDocOriginalFileName;

            public readonly RowListField<ReceivingItemRow> Items;

        }
    }
}

**Comment by karimhyatt** [comment]
Check the error message in the console. You should be able to get a stack trace to see exactly where your problem is.

**Comment by Estrusco** [comment]
Before of all set a breakpoint in AfterSave and debug at the line of code that throw exception.

Most probably one of your linq queries return null.

IMHO you have to check the line with:

```cs
invRow = Connection.TryFirst<Entities.InventoryRow>(q => q
                                                    .Select(inv.StockOnHand)
                                                    .Select(inv.StockIn)
                                                    .Where(
                                                            inv.ItemId == item.ItemId.Value &
                                                            inv.StoreId == item.StoreId.Value &
                                                            inv.TransactionTypeId == Convert.ToInt32(transactionTypeRow.TransactionTypeId))
                                                    .OrderBy(inv.InventoryDate, desc: true));
```

Try to refactor internal query in a method to see if return some data.

**Comment by gfo2007** [comment]
@karimhyatt this is the console error

The source map 'Serenity.CoreLib.js.map' for file 'mdha:http://localhost:50451/Scripts/serenity/Serenity.CoreLib.js?v=wzbnF5VYCxeH3Cc6iZ1FJg2' could not be read from the specified location due to error 'Exception of type 'TypeScriptSourceMapReader.SourceMapReadFailedException' was thrown.'.The source map 'Serenity.CoreLib.js.map' for file 'mdha:http://localhost:50451/Scripts/serenity/Serenity.CoreLib.js?v=wzbnF5VYCxeH3Cc6iZ1FJg2' could not be read from the specified location due to error 'Exception of type 'TypeScriptSourceMapReader.SourceMapReadFailedException' was thrown.'.The source map 'Serenity.CoreLib.js.map' for file 'mdha:http://localhost:50451/Scripts/serenity/Serenity.CoreLib.js?v=wzbnF5VYCxeH3Cc6iZ1FJg2' could not be read from the specified location due to error 'Exception of type 'TypeScriptSourceMapReader.SourceMapReadFailedException' was thrown.'.Exception thrown: 'System.NullReferenceException' in iwms.Web.dll
Exception thrown: 'System.NullReferenceException' in System.Web.Mvc.dll
Exception thrown: 'System.NullReferenceException' in System.Web.Mvc.dll
System.NullReferenceException: Object reference not set to an instance of an object.
   at iwms.Transactions.Repositories.ReceivingRepository.MySaveHandler.<>c__DisplayClass0_1.<AfterSave>b__2(SqlQuery q) in J:\Visual Studio Projects\iwms\iwms\iwms.Web\Modules\Transactions\Receiving\ReceivingRepository.cs:line 66
   at Serenity.Data.EntityConnectionExtensions.TryFirst[TRow](IDbConnection connection, Action`1 editQuery) in C:\Projects\StartSharp\Serenity\Serenity.Data.Entity\Extensions\EntityConnectionExtensions.cs:line 148
   at iwms.Transactions.Repositories.ReceivingRepository.MySaveHandler.AfterSave() in J:\Visual Studio Projects\iwms\iwms\iwms.Web\Modules\Transactions\Receiving\ReceivingRepository.cs:line 66
   at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) in C:\Projects\StartSharp\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 292
   at iwms.Transactions.Repositories.ReceivingRepository.Create(IUnitOfWork uow, SaveRequest`1 request) in J:\Visual Studio Projects\iwms\iwms\iwms.Web\Modules\Transactions\Receiving\ReceivingRepository.cs:line 17
   at iwms.Transactions.Endpoints.ReceivingController.Create(IUnitOfWork uow, SaveRequest`1 request) in J:\Visual Studio Projects\iwms\iwms\iwms.Web\Modules\Transactions\Receiving\ReceivingEndpoint.cs:line 19
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in C:\Projects\StartSharp\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 139
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_0.<InvokeActionMethodWithFilters>b__0()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
Configuration invalid: ToAddress must have a value
The thread 0x1cc8 has exited with code 0 (0x0).
The thread 0x29a0 has exited with code 0 (0x0).
The thread 0x4534 has exited with code 0 (0x0).
The thread 0x2e98 has exited with code 0 (0x0).
The thread 0x417c has exited with code 0 (0x0).
The thread 0x4108 has exited with code 0 (0x0).
The thread 0x53f8 has exited with code 0 (0x0).

**Comment by gfo2007** [comment]
@Estrusco that particular line returns null because at the moment there is no data in the table. But the query is expected to do something when null, and another thing when not null. Could you guide me on how to avoid the error?

**Comment by brunobola** [comment]
@gfo2007 try to do a if(transactionTypeRow==null)... To see if it is null somehow and protect it in that case...

**Comment by gfo2007** [comment]
@brunobola, the error is coming from this line

invRow = Connection.TryFirst<Entities.InventoryRow>(q => q
                                                    .Select(inv.StockOnHand)
                                                    .Select(inv.StockIn)
                                                    .Where(
                                                            inv.ItemId == item.ItemId.Value &
                                                            inv.StoreId == item.StoreId.Value &
                                                            inv.TransactionTypeId == Convert.ToInt32(transactionTypeRow.TransactionTypeId))
                                                    .OrderBy(inv.InventoryDate, desc: true));

There is no record in the table yet but I need to both check for when there is no record and when there is a record.

**Comment by gfo2007** [comment]
Thanks everyone for at least taking a bit of time to respond to my issue. I have found after debugging for hours. I needed to instantiate the invRow object inside the null condition before passing the values to its fields. Below is the code in my repository.


namespace iwms.Transactions.Repositories
{
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using System;
    using System.Data;
    using MyRow = Entities.ReceivingRow;

    public class ReceivingRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            
            protected override void AfterSave()
            {
                base.AfterSave();
                
                var inv = Entities.InventoryRow.Fields;
                //var transactionTypeRow = new MasterData.Entities.TransactionTypeRow();
                //var invRow = new Entities.InventoryRow();
                

                if (Row.Items != null)
                {
                    var mc = Entities.ReceivingItemRow.Fields;
                    var oldList = IsCreate ? null : Connection.List<Entities.ReceivingItemRow>(mc.ReceivingId == this.Row.ReceivingId.Value);
                    new Common.DetailListSaveHandler<Entities.ReceivingItemRow>(oldList, Row.Items, x => x.ReceivingId = Row.ReceivingId.Value).Process(this.UnitOfWork);
                    Int32 tTypeId = getTransactionTypeId("Receivings");

                    foreach (var item in Row.Items)
                    {

                        Console.WriteLine("Item ID: " + item.ItemId.Value);
                        Console.WriteLine("Store ID: " + item.StoreId.Value);
                        Console.WriteLine("Transaction Type ID: " + getTransactionTypeId("Receivings"));


                        var invRow = Connection.TryFirst<Entities.InventoryRow>(q => q
                                                      .Select(inv.StockOnHand)
                                                      .Select(inv.StockIn)
                                                      .Where(
                                                              inv.ItemId == item.ItemId.Value &
                                                              inv.StoreId == item.StoreId.Value &
                                                              inv.TransactionTypeId == tTypeId)
                                                      .OrderBy(inv.InventoryDate, desc: true));


                        if (invRow == null)
                        {
                            invRow = new Entities.InventoryRow();
                            invRow.StoreId = item.StoreId.Value;
                            invRow.ItemId = item.ItemId.Value;
                            invRow.StockOnHand = item.Quantity.Value;
                            invRow.StockIn = item.Quantity.Value;
                            invRow.StockOut = 0;
                            invRow.InventoryDate = DateTime.Now.Date;
                            invRow.TransactionTypeId = tTypeId;
                        }
                        else
                        {


                            invRow.StoreId = item.StoreId.Value;
                            invRow.ItemId = item.ItemId.Value;
                            invRow.StockOnHand = invRow.StockOnHand + item.Quantity.Value;
                            invRow.StockIn = item.Quantity.Value;
                            invRow.StockOut = 0;
                            invRow.InventoryDate = DateTime.Now.Date;
                            invRow.TransactionTypeId = tTypeId;
                        }

                        Connection.Insert(invRow);
                    }

                }
            }

            private Int32 getTransactionTypeId(String tTypeName)
            {
                var tType = MasterData.Entities.TransactionTypeRow.Fields;

                var transactionTypeRow = Connection.TryFirst<MasterData.Entities.TransactionTypeRow>(t => t
                                                                                                       .Select(tType.TransactionTypeId)
                                                                                                       .Where(tType.TransactionTypeName == tTypeName));
                Int32 tTypeId = 0;
                if(transactionTypeRow != null)
                {
                   tTypeId = transactionTypeRow.TransactionTypeId.Value;
                }

                return tTypeId;
            }
        }

        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>{}
        private class MyListHandler : ListRequestHandler<MyRow> { }
    }
}

**Comment by Estrusco** [comment]
@gfo2007 yes, invRow = new Entities.InventoryRow() is missing in null statment. Now works?

**Comment by gfo2007** [comment]
Works perfectly @Estrusco
