### ISSUE TITLE
Lookup use text instead of value

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#3384]
Pretty sure this is an easy one but cant quite get it for some reason (probably has to do with the screaming baby in the background :( 
I have a lookup i want to use but i want to save the text field of the lookup, not the id field.
so i have the lookup:
ID: 1 Value: test1
ID: 2 Value: test2
ID: 3 Value: test3

when i save the entity that uses this lookup its saving with the ID. I want to save the text instead.
sorry i explained that pretty bad!

**Comment by Estrusco** [comment]
If you want get description in client side, see https://github.com/volkanceylan/Serenity/issues/2521
If you want get descriotion in server side use  Serenity.GetText() enum extension method

**Comment by shakazulu89** [comment]
thanks but it is not an enum actually .. i have a table that holds this lookup .. called "reviewtypes"
has rows like "surgery" , "anesthesia", etc.

**Comment by she-ll-b-rite** [comment]
A simple solution, may be to create a separate lookup (server side) that uses the text as both the 'IdField' and 'TextField'...note that I haven;t tried this myself though.

```
namespace MyApp.Scripts
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;
    using Entities;

    [LookupScript("MyApp.MyLookup", Permission = "*")]
    public class MyLookup : RowLookupScript<MyRow>
    {
        public MyLookup()
        {
            IdField = MyRow.Fields.Name.PropertyName;
            TextField = MyRow.Fields.Name.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var flds = MyRow.Fields;
            query.Distinct(true)
                .Select(flds.Id, flds.Name, ...)
                .Where(...);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}
```
Make sure you update the LookupEditor attribute in your Form or Row class.

        public Int32 Id { get; set; }
        [LookupEditor(typeof(MyLookup)), ...]
        public String Name { get; set; }
        ...


client side - add a changeSelect2 event to the 'LookupField' that transfer the text to the 'LookupFieldText' field.
```
constructor() {
    super();
    ...
    this.form.LookupField.changeSelect2(e => this.entity.LookupFieldText = this.form.LookupField.text);
    ...
}
```

server side - in the repository class

        private class MySaveHandler : SaveRequestHandler<MyRow> {

            protected override void ValidateRequest()
            {
                // code to lookup the text from 
                base.ValidateRequest();
            }
        }

**Comment by abelal83** [comment]
Lookupscript as suggested is the way.
