### ISSUE TITLE
Serenity.DataGrid.defaultPersistanceStorage = window.localStorage issue ?

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3386]
Using this setting (and not the persistance in DB), any favoriteView (Mixin) created by one user can be also used by others users (as they share same local storage entry).

Wouldn't it require to filter list of favoriteviews to the ones belonging to current logged user ?

Looks like different behavior for same purpose (saving settings either in db or in local storage). 
When using DB as persistance, favoriteviews are only visible to user that created them while it's less restrictive when using browser local storage.

**Comment by volkanceylan** [comment]
If multiple users are using the same browser, and you want them to have different settings, then you should implement a custom persistance storage (see guide) and add current username to keys.
