### ISSUE TITLE
@Serenity.Decorators.filterable() issue

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3387]
I have defined some fields available only with a certain PermissionKey in xyzRow.cs / xyzColumns.cs / xyzForm.cs (ReadPermission as attribute).
When i log with a user not having this permission, these columns are CORRECTLY : 
- NOT available in the Grid
- NOT available in the Column Picker

but they are ALL AVAILABLE to filter when the grid is defined using the `@Serenity.Decorators.filterable()` decorator (columns are proposed while they should NOT - to be consistent with others).

Looks like the filterable does not take into account permissionkey setting.

**Comment by she-ll-b-rite** [comment]
you can see from the source below that there's no client side permission checks when creating the filterbar, so you'll need to add the `[NotFilterable]` attribute to the fields you want to hide in xyzColumns.cs class, OR override the createFilterBar method on the xyzGrid.ts and add your own permission checks to filter out.

https://github.com/volkanceylan/Serenity/blob/ea41e1f28fc0aa0bae911738f76487acb0de92af/Serenity.TypeScript.CoreLib/UI/DataGrid/DataGrid.ts#L651-L669

**Comment by kilroyFR** [comment]
Thanks.

Fixed - maybe i am gonna push a pull request for this modification in Serenity.

```
protected createFilterBar(): void {
      var filterBarDiv = $('<div/>').appendTo(this.element);
      var self = this;
      this.filterBar = new Serenity.FilterDisplayBar(filterBarDiv);
      if (!this.isAsyncWidget()) {
        this.filterBar.set_store(new Serenity.FilterStore(this.allColumns.filter(function (x) {
          return (x.sourceItem != null) && (x.sourceItem.notFilterable !== true) && (Authorization.hasPermission(x.sourceItem.readPermission) || x.sourceItem.readPermission == null);
        }).map(function (x1) {
          return x1.sourceItem;
        })));
        this.filterBar.get_store().add_changed((s: JQueryEventObject, e: any) => {
          if (this.restoringSettings <= 0) {
            self.persistSettings(null);
            self.view && (self.view.seekToPage = 1);
            self.refresh();
          }
        });
      }
    } 
```

**Comment by she-ll-b-rite** [comment]
great idea, you might even find you can reuse the method `canShowColumn `to perform the permission check.

https://github.com/volkanceylan/Serenity/blob/ea41e1f28fc0aa0bae911738f76487acb0de92af/Serenity.TypeScript.CoreLib/UI/DataGrid/DataGrid.ts#L1308-L1327
