### ISSUE TITLE
handle many to many relationship

### ISSUE THREAD

**Issue by ragoob** [volkanceylan/Serenity#339]
i have many to many relationship in my model how i can implement this and make 
"select2" multiple select mode

**Comment by volkanceylan** [comment]
In customer dialog there is a Representatives field with multi select, see how i implement it there.

**Comment by ragoob** [comment]
well , thank you , are Available viewing many to many  in grid columns for example i have entites called "children" ,"parents" and many to many entity "parentofchildren" i want to view name of parents of child in grid custom column ?

**Comment by volkanceylan** [comment]
I'm not sure if i understand right but what you ask is probably similar to Master/Detail samples.
