### ISSUE TITLE
PDF generator returned error code -1073741515!

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3390]
I have this error on a production (Hosting) Server
I check this things before a put this issue:

- My HTML is well formed (On browser console i have 0 errors)
- I have the 64 bits version of wkhtmltopdf.exe on bin folder and root folder, cause my server is a 64 bits windows version (I've trying with both 32 and 64 bits versions)
- I trying to put the msvcp120.dll on the bin folder with no luck

Any one has some ideas on what can a I touch to getting worked?

**Comment by kilroyFR** [comment]
C00135 is a classic error related to missing DLL(s).. 
I would suspect it's missing one or several MSVC runtime DLLs for your 64 bits version.
Try to install VC++ runtime 2013 64 bits. It should fix the problem.

https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by javaman63** [comment]
@kilroyFR  thanx for your answer but
I can't install it because its a hosting service, i just only got access to the public_html folder

**Comment by kilroyFR** [comment]
Try to manually copy all files included in the installer into your bin directory

**Comment by javaman63** [comment]
@kilroyFR 

I tried it, but without luck.
I think those libraries should be in the System32 folder and not in the bin

Someone? Ideas?

**Comment by postonoh** [comment]
What hosting company

**Comment by javaman63** [comment]
@postonoh www.donweb.com.ar

its a web hosting in argentina

**Comment by postonoh** [comment]
try this
https://stackoverflow.com/questions/16779736/include-visual-c-runtime-with-application

**Comment by javaman63** [comment]
@postonoh i have no luck with that

**Comment by postonoh** [comment]
Deixe-me fazer uma pergunta. Como você está implantando o site.

**Comment by javaman63** [comment]
Right click on the project folder ---> publish. And i uplodaded the generated files trough the ftp

**Comment by postonoh** [comment]
What version of Visual Studio are you using.

**Comment by javaman63** [comment]
VS 2015 Enterprise Version

**Comment by postonoh** [comment]
C0000135‬ is a classical error related to missing DLL(s)..
I would suspect it's missing one or several MSVC runtime DLLs for your 64 bits version.
Try to install VC++ runtime 2013 64 bits. It should fix the problem.

Okay First make a backup copy of you solutions. 
You want to make backup just in case this does not work.

Then check to see if whatever files are missing in your solutions.
check you solutions to see if they exist in your solutions under references.
If they exist right click on them then click properties. You should see something in the properties titled misc  look for copy local value set to false change it to true. 
This should copy all the files and change reference association in your project file to look for them in your project and not to the GAC or the server.

If this does not work you can delete the solution and restore the backup or use the backup.

Then I would call the hosting company.

**Comment by kcvincent** [comment]
I Install wkhtmltoPDF 64 bit at IIS machine .Then copy and replace 64 bit exe to bin/wkhtmltopdf.exe.
It seems OK for last 5 days.

**Comment by javaman63** [comment]
I've tryit but with no luck at all. I think there is a Hosting issue and not a Serenity one. 
I will close this issue and if in the near future i came with the solution i will share it here

Thanks everybody for your insides
