### ISSUE TITLE
[How To] Maximize Slickgrid

### ISSUE THREAD

**Issue by zKarp** [volkanceylan/Serenity#3391]
I thought I would share a modification I made to maximize the slick-grid. Since my users use this similar to excel and would like it to be the main focus sometimes. Clicking the maximize button will fill the screen with the GridDiv, clicking again will restore it back it it's original state.

**CSS in Dashboard.html**
```
<style type="text/css">
        #GridDiv.fullscreen {
            z-index: 9999;
            width: 100%;
            height:100vh;
            min-height: 100%;
            position: fixed;
            top: 0;
            left: 0;
        }
</style>


```

**JS in Dashboard.html**
Add after Q.initFullHeightGridPage($('#GridDiv'));
```
        $('#GridDiv .grid-title .title-text').append('<a href="#" id="panel-fullscreen" class="pull-right" role="button" title="Toggle fullscreen"><i class="glyphicon glyphicon-resize-full"></i></a>');

        $('#panel-fullscreen').click(function (e) {
            $('#GridDiv').toggleClass('fullscreen');
            Q.initFullHeightGridPage($('#GridDiv'));
        });
```

![maximize-slickgrid](https://user-images.githubusercontent.com/1206496/37682254-69ee4f74-2c5f-11e8-9669-c2ad4afdd364.png)

If anyone wants to expand or clean this up, feel free.

**Comment by kilroyFR** [comment]
Very nice and useful thanks for sharing.

**Comment by Estrusco** [comment]
Nice, thank you!

**Comment by hannesb** [comment]
Looks like a cool feature to me, maybe add it to the wiki?

**Comment by kilroyFR** [comment]
hey again. I just noticed a side effect.

When you have @Serenity.Decorators.filterable() on a grid, when screen is maximized, the EDIT FILTER button at the bootom right is not working.

**Comment by kilroyFR** [comment]
For those using CardMixin, change the js in .html with : 
```
      $('#GridDiv .view-switch').append('<a href="#" id="panel-fullscreen" class="pull-right" role="button" title="Toggle fullscreen"><label class="btn btn-default"><i class="glyphicon glyphicon-resize-full text-purple"></i></label></a>');
      $('#panel-fullscreen').click(function (e) {
        $('#GridDiv').toggleClass('fullscreen');
        Q.initFullHeightGridPage($('#GridDiv'));
      });
```

It will add the fullsize icon after cardmixin icons giving nice visual effect.

**Comment by mustafalotiya** [comment]
Nice Feature.
Thank you.

**Comment by JohnRanger** [comment]
Works great. Thanks for sharing.

**Comment by JohnRanger** [comment]
Based on the version of zKarp, I have made a more Serenity Framework integrated version.

For this, do the following:

**(1) Create a new less file:** e.g. site.myProject.less and insert the following content:
```less
    #GridDiv.fullscreen {
        z-index: 9999;
        width: 100%;
        height:100vh;
        min-height: 100%;
        position: fixed;
        top: 0;
        left: 0;
    }
```

**(2) Import this new less file within site.less** like this:
```less
@import "site.myProject.less";
```
**(3) Create a new Helper Typescript file called GridHelpers.ts** under /Common/Helpers/ and insert the following:
```ts
namespace <yourProject>.GridHelper {
    export function EnableFullSizeGrid() {
        Q.initFullHeightGridPage($('#GridDiv'));
        $('#GridDiv .grid-title .title-text').append('<a href="#" id="panel-fullscreen" class="pull-right" role="button" title="Toggle fullscreen"><i class="glyphicon glyphicon-resize-full"></i></a>');
        $('#panel-fullscreen').click(function (e) {
            $('#GridDiv').toggleClass('fullscreen');
            Q.initFullHeightGridPage($('#GridDiv'));
        });
    }
}
```
**(4) In the Modules where you want this feature to be added within the grid, do the following two steps:**

**(4a) Within xyzGrid.ts, insert the following:**
```ts
    // *** Enable Full size grid resize ***
    <yourProject>.GridHelper.EnableFullSizeGrid();
```

**(4b) Within xyzIndex.cshtml, remove the following line:**
```js
    Q.initFullHeightGridPage($('#GridDiv'));
```

With that, you can enable this feature on any grid you want and you don't have to write the full javascript code every time.

Hope this helps somebody.

With kind regards,

John

**Comment by alex-444** [comment]
Hi @JohnRanger !
I try to follow your instructions for grid full size and it works.
My problem, when i try to open the edit link the dialog does not show when i'm in full size mode.
thanks!

**Comment by JohnRanger** [comment]
Hi @alex-444 ,

I have quickly tested it and - yes - you are right - this does not work - I expect, that this also does not work with the original implementation.

Actually, the Dialogs _do_ open but they are hidden under the full size grid.

If you do resize the grid back then they appear.

I will see if I can adjust the Z-index of full size panel so that it stays behind the dialogs.

With kind regards,

John

**Comment by JohnRanger** [comment]
@zKarp ,

as this issue (actually a how to) is already open since nearly 1 year and howtos should be within the wiki, I have created a wiki article for your howto.

Would you mind to close this issue here? :-)

With kind regards,

John
