### ISSUE TITLE
Transform All T4 Templates

### ISSUE THREAD

**Issue by hairangsua** [volkanceylan/Serenity#3392]
Hi everyone. I want to transform All T4 when i had builded my project. No need to use Transform All T4 template button in Menu of Visual Studio. How i can do that?

**Comment by brunobola** [comment]
@hairangsua You could just assign a shortcut key to this function say CTRL+F6 and then just do CRT+F6 followed by a CTR+F5 to open without debug.

Then just do changes anywhere and do a CTRL+F6 and/or CTRL+F6 and your already running browser just need a F5 to refresh and see the changes.

See if this helps.

**Comment by hairangsua** [comment]
Thanks bro!
