### ISSUE TITLE
Dialog without Grid

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3394]
Hi

I placed link into Events grid via URLFormatter to open Users dialog in Add mode.
(I have yet to figure out, how to pass selected row and prepopulate it in Dialog)
Problem right now is, there is grid with list of users below User Add dialog (no good)
I decorated UsersDialog with @Serenity.Decorators.registerClass(), but there is still blink of the users list briefly visible. 
Ideally I want smaller dialog (not full-size panel) that goes to thank you page after successfully saved.
Would it be better to open User Add dialog from grid via JS somehow?

thx

**Comment by hannesb** [comment]
You could like @Serenity.Decorators.panel()

**Comment by ga5tan** [comment]
@hannesb yeah, sorry, ofcourse I decorated with @Serenity.Decorators.panel()
sorry, I mistyped in my original post.
But the problem is still there. there is grid showing up, before dialog pops up :(

**Comment by hannesb** [comment]
The normal routing in Serenity always loads the grid too. You need an additional routing if you want to load a dialog directly and bypass the grid view. It's all about the V and C in MVC (not really Serenity related btw.).

**Comment by ga5tan** [comment]
I worked it out, somehow.
based on http://serenity.is/serene/BasicSamples/EntityDialogAsPanel/
sample, I instantiated dialog in cshtml
for some reason it is still panel, which I dont want anymore but hopefully I work it out
now I am dealing with parameter from URL.

**Comment by ga5tan** [comment]
any idea how to display dialog as pop up dialog (not whole page width)?

**Comment by Estrusco** [comment]
If your dialog is a serenity dialog, use
new YuorNamespace.XYZDialog().dialogOpen();

**Comment by ga5tan** [comment]
cool, that did it! thx
But now my afterLoadEntity even is not triggered (where I populate combo with selection from grid) 
@Estrusco  any idea which even to take now?

**Comment by Estrusco** [comment]
If you want load an entity, try with

```ts
new YuorNamespace.XYZDialog().loadByIdAndOpenDialog()
```

or for new entity

```ts
new YuorNamespace.XYZDialog().loadNewAndOpenDialog()
```

**Comment by ga5tan** [comment]
@Estrusco 
new YuorNamespace.XYZDialog().loadNewAndOpenDialog() worked. 
THX
