### ISSUE TITLE
Serenity Guide

### ISSUE THREAD

**Issue by SerenityUser1** [volkanceylan/Serenity#3396]
Is there a proper guide available to learn serenity framework??? what are the functions available and where and when I can use them. The basic control flow and other details instead of just the examples? And also where can I find all the examples that I can refer to?

**Comment by Zahar661** [comment]
https://www.gitbook.com/book/volkanceylan/serenity-guide/details

**Comment by brunobola** [comment]
And the Wiki section has several things also....

**Comment by SerenityUser1** [comment]
Thank you both. Yes, I am following those examples.

**Comment by brunobola** [comment]
@SerenityUser1 close the issue if you are satisfied....
