### ISSUE TITLE
Cloning entity in popup dialog Box (on a panel dialog)

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3398]
hey all,

2 questions regarding CLONING ENTITY feature :

1/ I have set  `@Serenity.Decorators.panel()` decorator on my dialog.
Then i have enabled entity cloning (`this.cloneButton.toggle(this.isEditMode());`  on updateInterface().

Now when i click on 'Clone' button i would like it displays a popup window and not another panel in the existing panel (hard to identify it's new entity).

It looks like the new dialog is inheriting from parent decorators (when dialog is not panel i have 2 popup dialogs).

Is that possible ?

2/ When cloning is done, is that possible to add an additional process.
I used the getCloningEntity() prior to cloning but could not find an event related to return of cloning operation (except onSaveSuccess() but i cannot identify cloning operation from the insert).

**Comment by she-ll-b-rite** [comment]
haven't tested this myself, but perhaps a minor tweak to the clone buttons onClick event would get the result you're after. if you look at the code below from EntityDialog, the call to open the dialog on line 967 has 'null' for the 'asPanel' param, which meas it's using the default, which is true in your case. override the onClick event for the clone button (or add your own button) and change 'asPanel' param to false.

https://github.com/volkanceylan/Serenity/blob/ea41e1f28fc0aa0bae911738f76487acb0de92af/Serenity.TypeScript.CoreLib/UI/Dialogs/EntityDialog.ts#L952-L970

**Comment by kilroyFR** [comment]
it works. Thanks !
