### ISSUE TITLE
getting install error for CsQuery, EpPlus, FluentMigrator.runner, Serenity.Web on vs 2017

### ISSUE THREAD

**Issue by Amitloh** [volkanceylan/Serenity#3403]
getting install error for CsQuery, EpPlus, FluentMigrator.runner, Serenity.Web on vs 2017. How do I fix this? I can not start first step...

**Comment by williamhodges** [comment]
Can you copy the entire stack trace?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brunobola** [comment]
That's strange I've got VS2017 always updated and can't simulate this, maybe some Extension you might have.

**Comment by sekeroth** [comment]
I am getting the same results on my desktop in VS 2017, but on my laptop it works without a flaw. Both computers are up to date with the latest node.js, etc. I tried to figure out what's going on without success to this point.

**Comment by volkanceylan** [comment]
This is probably connection / NuGet server issue. NuGet server fails from time to time.
