### ISSUE TITLE
Error Creating new project: NO PACKAGE INSTALLED

### ISSUE THREAD

**Issue by FGLedesma** [volkanceylan/Serenity#3405]
Hi, this issue is preventing me from using serene template. I've using it for 2 years without any problem.
Out of the blue, yesterday, when I tried to create a new project, it shows an error with the following information:
Title of the window:
System.InvalidOperationException: Error retrieving metadata 
An error occured while installing package: CsQuery
your project might be incomplete
...
The same thing is repetid for every package like "EPPlus", "flot"... even "fluentMigrator.Runner" and all of the packages serene usually  installs.

The serene version is 3.5.2.5 (Last version I believe).
Visual Studio 2017 -  Ver. 15.6.4

My internet connection is perfectly working, no windows firewall rules impeding nothing, 
Is not an intranet, is at home.

I've tried the "Restore nuget package", etc... nothing fix the problem...

Any help would be greatly appreciated.
Please, I need to work!

![serene error](https://user-images.githubusercontent.com/24248165/37911705-2d0d5c94-30e7-11e8-91a2-5e49ec2f0186.JPG)

**Comment by kilroyFR** [comment]
did you try : update-package -reinstall 
from nuget command line ?

**Comment by FGLedesma** [comment]
Hi KilroyFR, yes I tried, but beyond that, given the fact that the error comes when you're simply creating a new project based on serene template, dealing with packages immediately after project creation, with a lot of errors,  is not the expected one. 
Not even serene proprietary packages get installed, impairing the project for any further action. 
Sorry if I not being absolutely clear, English is not my native language.

**Comment by volkanceylan** [comment]
I created Serene in several PCs, and got no such error, sometimes NuGet server fails, and unfortunately there is nothing we can do about that.

**Comment by shakazulu89** [comment]
@kilroyFR  do you remember what fixed this for you? i am also suddenly having this issue :(
