### ISSUE TITLE
Prevent UpdatableExtension from Saving

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#3406]
I have an UpdateableExtension on my row class.  Is there a way that I can prevent the related record from saving when a particular field is checked?

**Comment by williamhodges** [comment]
Is that field stored in the database or is it just checked on the client side?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leahmayschneider** [comment]
It's in the database.

**Comment by leahmayschneider** [comment]
I set all UpdateableExtension fields to null in SetInternalFields which works but is inelegant.
