### ISSUE TITLE
Multitenancy & MultiTenantRowLookupScript CPU performance

### ISSUE THREAD

**Issue by florin-nitulescu** [volkanceylan/Serenity#3407]
Hi,

I've read the tutorial for extending `RowLookupScript<>` to filter by 'TenantId' ([link](https://volkanceylan.gitbooks.io/serenity-guide/tutorials/multi_tenancy/handling_lookup_scripts.html)). The `Expiration` property is set to a negative value to disable caching at the `DynamicScriptManager` level and to rely on the cache at the LookupScript level.  I've noticed that the `DynamicScriptManager.Item.EnsureContent()` method will create one or two streams for **every request** when the caching is disabled at this level. The second stream is a compressed (gzipped) one and will be created if the length of the first stream exceeds 4096. I'm concerned about the frequent gzipping of long lookup scripts (big # of rows and many included columns in the lookup script).

Do you think this will impact CPU performance enough to worth searching for a different approach?

**Comment by volkanceylan** [comment]
I don't think it affects much but could possibly make it optional.

**Comment by florin-nitulescu** [comment]
If you don't think it affects much then it's no need to make it optional. In the future I will try to avoid multitenant apps and go with one database per customer approach as you suggested in the guide.

Thank you for your prompt response!
