### ISSUE TITLE
Merge cells vertically

### ISSUE THREAD

**Issue by jvscheers** [volkanceylan/Serenity#3409]
Is there a way to merge cell vertically in grid ?
Group can do pretty much the same but will have repeat data 

Basically it will like this
![image](https://user-images.githubusercontent.com/37527505/38006385-673e96ee-3277-11e8-872d-ce4224998af4.png)

d~j are actually data rows. a,b and c combined with same value.

**Comment by Estrusco** [comment]
You have to see in the slickgrid support https://github.com/mleibman/SlickGrid
In the examples there is http://mleibman.github.io/SlickGrid/examples/example-colspan.html for colspan. See if rowspan are similar
