### ISSUE TITLE
InplaceAdd = true

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#341]
Merhaba Volkan, 

Sergen ile olusturduktan sonra "InplaceAdd = true" ekledim ama disable gorunuyor. 

```

namespace MultiTenancy.Crm.Entities
{
    using MultiTenancy.Administration.Entities;
    using Newtonsoft.Json;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), DisplayName("Bolgeler"), InstanceName("Bolgeler"), TwoLevelCached]
    [ReadPermission("Bolge")]
    [ModifyPermission("Bolge")]
    [JsonConverter(typeof(JsonRowConverter))]
    [LookupScript("MultiTenancy.Bolgeler")]
    public sealed class BolgeRow : LoggingRow, IIdRow, INameRow, IMultiTenantRow
    {
        [DisplayName("Bolge Id"), Column("BolgeID"), Identity]
        public Int32? BolgeId
        {
            get { return Fields.BolgeId[this]; }
            set { Fields.BolgeId[this] = value; }
        }

        [DisplayName("Bolge Adi"), Size(15), NotNull, QuickSearch]
        public String BolgeAdi
        {
            get { return Fields.BolgeAdi[this]; }
            set { Fields.BolgeAdi[this] = value; }
        }


        [DisplayName("Last Directory Update"), Insertable(false), Updatable(false)]
        public DateTime? LastDirectoryUpdate
        {
            get { return Fields.LastDirectoryUpdate[this]; }
            set { Fields.LastDirectoryUpdate[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public Int32? TenantId
        {
            get { return Fields.TenantId[this]; }
            set { Fields.TenantId[this] = value; }
        }

        public Int32Field TenantIdField
        {
            get { return Fields.TenantId; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.BolgeId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.BolgeAdi; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public BolgeRow()
            : base(Fields)
        {
        }

        public class RowFields : LoggingRowFields
        {
            public Int32Field BolgeId;
            public StringField BolgeAdi;
            public readonly DateTimeField LastDirectoryUpdate;
            public readonly Int32Field TenantId;

            public RowFields()
                : base("[dbo].[Bolgeler]")
            {
                LocalTextPrefix = "Crm.Bolge";
            }
        }
    }
}
```

namespace MultiTenancy.Crm.Entities
{
    using MultiTenancy.Administration.Entities;
    using Newtonsoft.Json;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Default"), DisplayName("Musteriler"), InstanceName("Musteriler"), TwoLevelCached]
    [ReadPermission("Musteri")]
    [ModifyPermission("Musteri")]
    [JsonConverter(typeof(JsonRowConverter))]
    public sealed class MusteriRow : LoggingRow, IIdRow, INameRow,IMultiTenantRow
    {
        [DisplayName("Musteri Id"), Column("MusteriID"), Size(5), PrimaryKey, QuickSearch]
        public String MusteriId
        {
            get { return Fields.MusteriId[this]; }
            set { Fields.MusteriId[this] = value; }
        }

        [DisplayName("Musteri Adi"), Size(255), NotNull]
        public String MusteriAdi
        {
            get { return Fields.MusteriAdi[this]; }
            set { Fields.MusteriAdi[this] = value; }
        }

        [DisplayName("Vergi No"), Size(20)]
        public String VergiNo
        {
            get { return Fields.VergiNo[this]; }
            set { Fields.VergiNo[this] = value; }
        }

        [DisplayName("Vergi Dairesi"), Size(20)]
        public String VergiDairesi
        {
            get { return Fields.VergiDairesi[this]; }
            set { Fields.VergiDairesi[this] = value; }
        }

        [DisplayName("Hesap Kodu"), Size(30)]
        public String HesapKodu
        {
            get { return Fields.HesapKodu[this]; }
            set { Fields.HesapKodu[this] = value; }
        }
        //-----------------------------------------------------------------
        [DisplayName("Bolge"), Column("BolgeID"), ForeignKey("[dbo].[Bolgeler]", "BolgeID"), LeftJoin("jBolge"), TextualField("BolgeAdi")]
        [LookupEditor("MultiTenancy.Bolgeler", InplaceAdd = true)]
        public Int32? BolgeId
        {
            get { return Fields.BolgeId[this]; }
            set { Fields.BolgeId[this] = value; }
        }

        [DisplayName("Bolge Bolge Adi"), Expression("jBolge.[BolgeAdi]")]
        public String BolgeAdi
        {
            get { return Fields.BolgeAdi[this]; }
            set { Fields.BolgeAdi[this] = value; }
        }
        //-------------------------------------------------------

        [DisplayName("Sektor"), Column("SektorID"), ForeignKey("[dbo].[Sektorler]", "SektorID"), LeftJoin("jSektor"), TextualField("SektorSektorAdi")]
        [LookupEditor("MultiTenancy.Sektorler", InplaceAdd = true)]
        public Int32? SektorId
        {
            get { return Fields.SektorId[this]; }
            set { Fields.SektorId[this] = value; }
        }

        [DisplayName("Is Potansiyel Tip"), Column("IsPotansiyelTipID"), ForeignKey("[dbo].[IsPotansiyelTipleri]", "IsPotansiyelTipID"), LeftJoin("jIsPotansiyelTip"), TextualField("IsPotansiyelTipIsPotansiyelTipAdi")]
        [LookupEditor("MultiTenancy.IsPotansiyelTipleri", InplaceAdd = true)]
        public Int32? IsPotansiyelTipId
        {
            get { return Fields.IsPotansiyelTipId[this]; }
            set { Fields.IsPotansiyelTipId[this] = value; }
        }

        [DisplayName("Musteri Kategori"), Column("MusteriKategoriID"), ForeignKey("[dbo].[MusteriKategorileri]", "MusteriKategoriID"), LeftJoin("jMusteriKategori"), TextualField("MusteriKategoriMusteriKategoriAdi")]
        [LookupEditor("MultiTenancy.MusteriKategori", InplaceAdd = true)]
        public Int32? MusteriKategoriId
        {
            get { return Fields.MusteriKategoriId[this]; }
            set { Fields.MusteriKategoriId[this] = value; }
        }

        [DisplayName("Aktif"), NotNull]
        public Boolean? Aktif
        {
            get { return Fields.Aktif[this]; }
            set { Fields.Aktif[this] = value; }
        }

        [DisplayName("Id"), Column("ID"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        

       

        [DisplayName("Sektor Sektor Adi"), Expression("jSektor.[SektorAdi]")]
        public String SektorSektorAdi
        {
            get { return Fields.SektorSektorAdi[this]; }
            set { Fields.SektorSektorAdi[this] = value; }
        }

        [DisplayName("Is Potansiyel Tip Is Potansiyel Tip Adi"), Expression("jIsPotansiyelTip.[IsPotansiyelTipAdi]")]
        public String IsPotansiyelTipIsPotansiyelTipAdi
        {
            get { return Fields.IsPotansiyelTipIsPotansiyelTipAdi[this]; }
            set { Fields.IsPotansiyelTipIsPotansiyelTipAdi[this] = value; }
        }

        [DisplayName("Musteri Kategori Musteri Kategori Adi"), Expression("jMusteriKategori.[MusteriKategoriAdi]")]
        public String MusteriKategoriMusteriKategoriAdi
        {
            get { return Fields.MusteriKategoriMusteriKategoriAdi[this]; }
            set { Fields.MusteriKategoriMusteriKategoriAdi[this] = value; }
        }
        [DisplayName("Last Directory Update"), Insertable(false), Updatable(false)]
        public DateTime? LastDirectoryUpdate
        {
            get { return Fields.LastDirectoryUpdate[this]; }
            set { Fields.LastDirectoryUpdate[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public Int32? TenantId
        {
            get { return Fields.TenantId[this]; }
            set { Fields.TenantId[this] = value; }
        }

        public Int32Field TenantIdField
        {
            get { return Fields.TenantId; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.MusteriId; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public MusteriRow()
            : base(Fields)
        {
        }

        public class RowFields : LoggingRowFields
        {
            public StringField MusteriId;
            public StringField MusteriAdi;
            public StringField VergiNo;
            public StringField VergiDairesi;
            public StringField HesapKodu;
            public Int32Field BolgeId;
            public StringField BolgeAdi;

            public Int32Field SektorId;
            public Int32Field IsPotansiyelTipId;
            public Int32Field MusteriKategoriId;
            public BooleanField Aktif;
            public Int32Field Id;
            public readonly DateTimeField LastDirectoryUpdate;
            public readonly Int32Field TenantId;

            public StringField SektorSektorAdi;
            public StringField IsPotansiyelTipIsPotansiyelTipAdi;
            public StringField MusteriKategoriMusteriKategoriAdi;

            public RowFields()
                : base("[dbo].[Musteriler]")
            {
                LocalTextPrefix = "Crm.Musteri";
            }
        }
    }
}
```

```

**Comment by volkanceylan** [comment]
Formda mı readonly gözüküyor, star ikonu mu anlamadım, denedim ama böyle birşeyle karşılaşmadım.

**Comment by Olricz** [comment]
evet formda readonly gorunuyor.FK'ların tablo yapısında   asagıdakiler de var. Onlar olmadıgından olabilir mi ? 

"InsertDate",
                "InsertUserId",
                "UpdateDate",
                "UpdateUserId",
                "DeleteDate",
                "DeleteUserId",

**Comment by volkanceylan** [comment]
Sanmam InplaceAdd yapmayınca şimdi BolgeId alanı mesela normal ama yapınca readonly mi geliyor editör tümüyle?

**Comment by Olricz** [comment]
aslında readonly derken, tıkladıgımda yeni Bolge Formu gelmıyor.  Bolgeden birini sectigimde star , pencil oluyor. sadece yenı bolge olusturmak ıcın form gelmıyor. ya da duzeltmek için olan form gelmıyor.

**Comment by volkanceylan** [comment]
MultiTenancy.Bolgeler bence burada bir sorun var, sizin lookup key ler yanlış olsa gerek, normalde LookupKey lerin Module.Tablo yapısında olması lazım. MultiTenancy root namespace. Sanki Crm.Bolgeler olmalı. Lookup editör dialog tipini bulmak için lookup key e bakar, dolayısıyla MultiTenancy.BolgelerDialog arar. Oysa sizin dialog MultiTenancy.Crm.BolgelerDialog. Crm.BolgelerDialog olsa bulabilir ama Multitenancy.BolgelerDialog bulamaz.

**Comment by volkanceylan** [comment]
Eğer lookup key i dialog namespace ve adıyla uyumlu yapmayacaksanız, DialogType opsiyonuna da vermelisiniz:

[LookupEditor("MultiTenancy.Bolgeler", InplaceAdd = true, DialogType = "Crm.Bolgeler")] gibi

**Comment by Olricz** [comment]
eywallah. hallettim. 
bastan sona bi proje yapana kadar biraz yardım gerekecek. Ama güzel olucak sonunda bu platformda calısmak.

**Comment by volkanceylan** [comment]
Evet biraz ilk öğrenme süresi var ama sonrasında genelde kullananlar memnun kalıyor.

**Comment by Olricz** [comment]
eline saglık. sakın bırakma geliştirmeyi. :)
