### ISSUE TITLE
Feature Requests [comment to suggest]

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#3410]
First of all I want to make a tribute to the @volkanceylan and his team for the excellent platform that they develop.

Saying that I believe that one missing feature that would help truly the platform further more is:

- Create the ability to refresh "in-memory grids" (this one is an excellent feature that allows data persistence making the platform more robust)
- Create the ability to refresh the full entity dialog and all its in-memory grids in a simple way (same reason, data persistence and additional flexibility to the platform)
 - One Click Entity-Dialog data Print (this is a feature that mimics the ERP ones and would certainly benefit the users and add extra power to the already Excellent platform)

Please comment if interested.
All the credits are for the master @volkanceylan and is team.

Please continue the excellent development and your great support.
👍

**Comment by volkanceylan** [comment]
In memory grids can't be refreshed, as name implies, they are loaded along with dialog entity and edited in memory, there is nothing to refresh. You can use a normal entity grid otherwise. You can reload entity with this.loadById.

**Comment by brunobola** [comment]
@volkanceylan yes i'm fully aware, but perhaps making some extension to it and enable that feature, by doing some tricks like hashing the ids or exposing the internal grid ids, etc, don't really know how, just said it would be a really nice feature ( nothing is impossible ;) ), let's see what other users think, i only wan't to improve your awesome platform.

I'll continue to use and recommend it.  Also the premium support its's a must have for anyone who are an active business developer :)
