### ISSUE TITLE
Maskeditor - Two patterns at once

### ISSUE THREAD

**Issue by adalberto-argente** [volkanceylan/Serenity#3411]
Is there any way to make a mask fit the character quanity of the textbox? For example, in the same field I need to accept two formats of numbers:
(81) 1234-5678  or  (81) 1 2345-6789
Maybe like: (99) [9]9999-9999

Thanks!

**Comment by brunobola** [comment]
You can do your own editor and use a regular expression.

Also check this: https://github.com/volkanceylan/Serenity/issues/2159
