### ISSUE TITLE
No grid on dialog windows, second tab

### ISSUE THREAD

**Issue by isukces** [volkanceylan/Serenity#3412]
Grid embedded on second or third tab in dialog is not displayed properly. I think it has width set to 0%. Serenity demo page is also affected. Please look at  customer details i.e. https://serenity.is/demo/Northwind/Customer#edit/49 . He has some orders but they are not visible on "Orders" tab.

**Comment by ga5tan** [comment]
your URL did not work
did u mean this cutomer? there is bunch of orders on third tab
![image](https://user-images.githubusercontent.com/36483170/38047464-dd1a4b62-327f-11e8-953f-9713c8ce0e00.png)

**Comment by isukces** [comment]
I checked on Firefox and it is OK. For me problem is under Chrome 64.0.3282.186.  My application witten under Serenity AspNetCore 3.3.7 works properly both on Chrome and Firefox, but the same typescript dialog under Serenity 3.5.5 displays no grid. So maybe some combination of browser and Serenity gives this problem.

**Comment by ga5tan** [comment]
maybe, screenshot is from Chrome Version 65.0.3325.181 (online demo as you can see from URL)

**Comment by isukces** [comment]
I think the problem comes from two elements
1. jquery patch 'Account for unreliable border-box dimensions' (jquery-3.3.1.js line 6591) that provides subtract value so always width-substract=0
2. jquery line 6099
`scrollboxSizeVal =  div.offsetWidth === 36 || "absolute";`

scrollboxSizeVal value equals `true` for Firefox and `absolute` in my affected browser. For my browser `div.offsetWidth` was about `35.8` so not exactly `36`. When I changed font size by ctrl+wheel and then reloaded page everything works perfectly.

**Comment by isukces** [comment]
Problem has been reported to jquery team https://github.com/jquery/jquery/issues/4029

**Comment by volkanceylan** [comment]
Thanks a lot for this, is there a workaround till they fix that?

**Comment by isukces** [comment]
Seems that Jquery problem has been fixed.

**Comment by AlperanQ** [comment]
Closing due to inacticity.
