### ISSUE TITLE
In Serenity 3.5.2.5 not able to generate "Grid Editor and Grid Editor Dialog" can anyone help me how to generate this?

### ISSUE THREAD

**Issue by rakeshpatil20** [volkanceylan/Serenity#3415]
In Serenity 3.5.2.5 not able to generate "Grid Editor and Grid Editor Dialog" can anyone help me how to generate this?
![image](https://user-images.githubusercontent.com/31484362/38075211-30783a56-334f-11e8-93d4-50fd8390ef90.png)

**Comment by rakeshpatil20** [comment]
Thanks @ga5tan for you help,

I am able to connect DB and able to generates Row, Services, column,Dialog, grid & form

**Comment by ga5tan** [comment]
Grid.ts is Grid
Dialog.ts is add\edit dialog.
that's wrong? if u missing menu entries, u need to find generated navigation and put it to main navigation
u specify filed labels in Row.cs
u modify Grids columns in Columns.cs
u modify Dialogs fields in Form.cs
