### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3417]
Hi,

I want to implement custom image and document upload functionality. I have override my Save method in Service class. So in client side, I have to set the model value and passing it to the service method. on setting model value for image field, I can get only the OriginalFileName and Temporary path. Finally, it is saving only the temporary path in DB and the image is stored only in temporary path not in physical path. 

can anyone please suggest me a solution ?

**Comment by javaman63** [comment]
The [MultipleFileUploadEditor] is no good enough for you?

**Comment by hairangsua** [comment]
when we upload 1 image or file by upload editor of serenity, this file just upload to temporary folder. if you want to upload it to your DB, you need read file int Temporary folder and convert it to bit array type (bit[]).

**Comment by AmuthaKondusamy** [comment]
Thank You @hairangsua. It works fine
