### ISSUE TITLE
How to add row to detail (slick grid) of master-detail relation by client-side code (type script)?

### ISSUE THREAD

**Issue by kimheangcheng** [volkanceylan/Serenity#3418]
I want to add records to detail grid of master-detail relationship automatically from client-side code (typescript) without require to use EditorGrid. The record doesn't insert to database unless users click Save button.

**Comment by javaman63** [comment]
Use: 
```
                    dlg.loadEntityAndOpenDialog(<Northwind.OrderRow>{
                        CustomerID: 'GOURL',
                        EmployeeID: lauraCallahanID,
                        DetailList: [{
                            ProductID: chai.ProductID,
                            ProductName: chai.ProductName,
                            UnitPrice: chai.UnitPrice,
                            Quantity: 5,
                            LineTotal: chai.UnitPrice * 5
}]
```

Check this example:

http://www.serenity.is/demo/BasicSamples/DefaultValuesInNewDialog


Hope This Helps

**Comment by kimheangcheng** [comment]
Thank javaman63. Is it possible to add to DetailList without open Diaglog?

**Comment by kimheangcheng** [comment]
Close due to the solution is Product Picker on Advance Sample (require premium).

**Comment by angelogl** [comment]
Hello, I would like to know about the solution of this issue. Please,  Is it possible to add to DetailList without open Dialog? From server-side for example, and client-side? It is a code of function we alway need in programming. 

Thanks a lot. I will appreciate your help.
