### ISSUE TITLE
Cannot apply equality filter on field ... error

### ISSUE THREAD

**Issue by MoheebP** [volkanceylan/Serenity#3419]
On change of quick filter I am getting the above error. 
In my column.cs file I have declared like
        [QuickFilter(), FilterOnly(), TrueFalseEditor]
        public Boolean LinkedWithDebitVoucher { get; set; }
- I am filling this field in -  private class MyListHandler : ListRequestHandler<MyRow> --> in OnReturn method.
I have tried like
        protected onViewSubmit() {
            if (!super.onViewSubmit()) {
                return false;
            }
            var request = this.view.params as Serenity.ListRequest;
            if (request.EqualityFilter['LinkedWithDebitVoucher'].toString() == "true") {
                //
                this.setEquality(Transaction.AccVoucherInformationRow.Fields.LinkedWithDebitVoucher, true);
            } else if (request.EqualityFilter['LinkedWithDebitVoucher'].toString() == "false"){
                //
                this.setEquality(Transaction.AccVoucherInformationRow.Fields.LinkedWithDebitVoucher, false);
            }
            return true;
        }
But no luck. any help?
![untitled](https://user-images.githubusercontent.com/16447947/38095561-93051250-3392-11e8-93a1-c5db697a7a48.png)

**Comment by dfaruque** [comment]
try adding [Expression("some sql")] on LinkedWithDebitVoucher field. try to avoid filtering in the repository.

**Comment by MoheebP** [comment]
ok. thank you.
