### ISSUE TITLE
Null Boolean

### ISSUE THREAD

**Issue by leahmayschneider** [volkanceylan/Serenity#3420]
I'm having a problem with nullable booleans.  If I have a database row with a null in a boolean column and edit that row (but not the boolean column) in Serenity, it saves a false to the previously null boolean.  Is there any way to prevent this?

**Comment by rcruzfalcon** [comment]
Hi @leahmayschneider , try change in the Form.cs the field type to String, specific the BooleanEditor for this field, and when try to cast this string field to bool value, if is empty put value null in the Row.cs field.
i hope this help you..

this is in the source file 
 ```
case JsonToken.String:
                    var s = ((string)reader.Value).TrimToNull();
                    if (s == null)
                        _setValue(row, null);
                    else
                        _setValue(row, Convert.ToBoolean(s, CultureInfo.InvariantCulture));
                    break;
```

**Comment by leahmayschneider** [comment]
Thanks @rcruzfalcon.  I'm not sure what the source file is to put the code snippet you sent.  Additionally, the more I think about this, the less it makes sense.  I need a three value boolean and I don't think that Serenity provides for that.
