### ISSUE TITLE
Razor view as dialog template

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#3421]
Hi
Im trying to open a dialog that uses a razor view as the template. or open a razor view as a panel dialog.
goal is when a user clicks a link in another razor page i have it should pop up this dialog as a panel.
I looked at these two issues: #2451  and #1386
cant seem to figure it out. the chartindialog example uses regular html as template .. i need cshtml.
any ideas?
thanks!

**Comment by ga5tan** [comment]
well, all the pages are based on cshtml. So i guess you put put your razor there.
the thing is, they only have JS section instantiating  TS dialog. Did u try there?
I suppose that Template.html wont get parsed, if u put expressions there?

**Comment by shakazulu89** [comment]
yea but how do i open the page as a dialog? im sure im missing something simple (as is mostly the case 😊 )
template.html wont work for what im trying to do.

**Comment by ga5tan** [comment]
you open dialog and it will use .cshtml page.
you specify it (cshtml page) in mvc.cs and or in *Page.cs:
public ActionResult Index()
        {
            return View(MVC.Views.Northwind.Customer.CustomerIndex);
        }

**Comment by shakazulu89** [comment]
I'm sorry I don't really follow. I still don't understand how it's possible to specify a cshtml page as the template of a dialog?. What would be the syntax of opening the dialog?

**Comment by ga5tan** [comment]
you can open dialog form CSHTML like this:<div id="DialogDiv"></div>

`<script type="text/javascript">
    var myDialogAsPanel;
    jQuery(function () {
        // first create a new dialog
        myDialogAsPanel = new IDI5.Events.EventRegistration();
        myDialogAsPanel.iEventID = @Html.Raw(Model.ToJson());

 //show dialog in add new entity mode
        myDialogAsPanel.load({}, function() {
            // if we didn't reach here, probably there is no order with specified ID in url
            myDialogAsPanel.element.removeClass('hidden').appendTo('#DialogDiv');
            myDialogAsPanel.arrange();
        });
    });
</script>
`
