### ISSUE TITLE
Update a Coulmn in Leavemanagement

### ISSUE THREAD

**Issue by GayathriSravya** [volkanceylan/Serenity#3422]
Hello Everyone! 
   How to get the Daysrequired Field automatically when From and To fields are filled
    Expression is not working here can anyone help me ?

thank you 

![untitled](https://user-images.githubusercontent.com/34158884/38142862-ab48f3a8-345b-11e8-873e-96954836d625.png)

**Comment by rcruzfalcon** [comment]
Hi @GayathriSravya , you can use the EditorUtils.setRequired in the From and To Change event
example:
 Serenity.EditorUtils.setRequired(this.form.youField, true);

best regards

**Comment by GayathriSravya** [comment]
Thanks @rcruzfalcon  
where should I write this ?? Can u please explain it as I m new to this platform

**Comment by rcruzfalcon** [comment]
Hi, in the XYZDialog.ts you must binding the change event of **From** and **To** for know if the **Days Required** is or not required.
Example, in the constructor you can put some like this:

```
this.form.ForField.element.bind('change', () => this.ChangeDaysRequiredCondition());
this.form.ToField.element.bind('change', () => this.ChangeDaysRequiredCondition());
```
and create the method ChangeDaysRequiredCondition where 

` Serenity.EditorUtils.setRequired(this.form.DaysRequiredField, this.form.ForField.value && this.form.ToField.value );`

i hope this help you.

best regards.

**Comment by GayathriSravya** [comment]
Here is my code in XYZDialog.ts
its not working   

private DaysRequired() {
            this.form.DaysRequired.value = +this.form.To.value - +this.form.From.value;
        }
        constructor(container: JQuery) {
            super(container);

            this.form.From.change(e => this.DaysRequired);
            this.form.To.change(e => this.DaysRequired);

        }

**Comment by GayathriSravya** [comment]
Here is my code in xyzDialog.ts
its not working `private DaysRequired() {
this.form.DaysRequired.value = +this.form.To.value - +this.form.From.value;
}
constructor(container: JQuery) {
super(container);
        this.form.From.change(e => this.DaysRequired);
        this.form.To.change(e => this.DaysRequired);

    }`

**Comment by ga5tan** [comment]
oh man, I am not so good with JS.
are there no errors in console in your JS
did u try to put in some traces, or alerts to see if events get fired?

**Comment by GayathriSravya** [comment]
@ga5tan  
There are no errors its not displaying anything in that field
