### ISSUE TITLE
LinkingSetRelation with additional field data

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#3424]
Hi All.. First to all my hearty warm appreciation for providing such a framework. I have done a small project in a very less time and I definitely owe for the creators of this framework. Now I am looking for more larger scale application using this framework.

I have a case where my child records need dynamic description in a db field such as DoctorName/PatientName using expression. Description is not null field. Where can I set this  data while saving the record

this is the sample code and if I set default value for DoctorPatientsrow description it works, but in my case I want to set description based on some other values in the entity.

`        [DisplayName("Doctors")]
        [LookupEditor(typeof(DoctorsRow), Multiple = true, InplaceAdd = true), NotMapped]
        [LinkingSetRelation(typeof(DoctorPatientsRow), "Doctor", "Patient")]
        public List<Int32> Patients
        {
            get { return Fields.Patients[this]; }
            set { Fields.Patients[this] = value; }
        }`

**Comment by brunobola** [comment]
@Parbil I'm not sure if I understand, but you personalize NotMapped fields with Expressions with sql expressions like (t0.Name + t0.firstname + t0.lastname) for instance...

**Comment by Parbil** [comment]
Thanks. I have seen and done that for a different context. 
But here I need this data to store in Database and not a NotMapped field. so that other system can query based on that field

**Comment by ga5tan** [comment]
maybe try to override SetInternalFields?
``
protected override void SetInternalFields()
            {
                base.SetInternalFields();

                if (IsCreate)
                {
                    Row.Source = "site";
                    Row.IsActive = Row.IsActive ?? 1;
                }

                if (IsCreate || !Row.Password.IsEmptyOrNull())
                {
                    string salt = null;
                    Row.PasswordHash = GenerateHash(password, ref salt);
                    Row.PasswordSalt = salt;
                }
            }
``

**Comment by volkanceylan** [comment]
Yes, SetInternalFields.
