### ISSUE TITLE
Bug Demo Only - Inputs With Inline Buttons Misplaced events

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#3426]
https://serenity.is/demo/AdvancedSamples/InputWithInlineButtons

The buttons are misplaced. 
Not a big deal just a misplaced event message for sure :)

Action 2 and Action 1 are misplaced at the clicked buttons.

**Comment by Zahar661** [comment]
Hi! StartSharp here to discuss prohibited from! :-D

**Comment by brunobola** [comment]
Hello, don't understand what you mean, just point out the not important misplaced events e/or messages like so:
![image](https://user-images.githubusercontent.com/10889019/38252641-a0b76f98-374c-11e8-8c9d-92657171971b.png)

and

![image](https://user-images.githubusercontent.com/10889019/38252655-a9fa1952-374c-11e8-9e59-007daef8b098.png)

:)

**Comment by JohnRanger** [comment]
@Zahar661 ,

where do¨you otherwise expect startsharp issues to be discussed? :-)

With kind regards,

John

**Comment by volkanceylan** [comment]
Thanks, fixed.
