### ISSUE TITLE
QuickSearch works only with one column

### ISSUE THREAD

**Issue by olaferlandsen** [volkanceylan/Serenity#3427]
Well, my question is... How I can work with multiple column like "title" and "description"?
When I defined my columns I using `[QuickSearch]` like this:
```C#
using Serenity.Data.Mapping;

namespace Project.Columns
{
    using Serenity.ComponentModel;
    using System;
    using System.ComponentModel;

    [ColumnsScript("Project.Xyz")]
    [BasedOnRow(typeof(Entities.XyzRow), CheckNames = true)]
    public class XyzColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId")]
        public Int64 Id { get; set; }
        
        [EditLink, QuickSearch]
        public String Title{ get; set; }
        
        [DisplayName("Descripción"), QuickSearch]
        public String Description{ get; set; }
        
    }
}
```

But this, only search on "title" column,

**Comment by dfaruque** [comment]
Try adding `QuickSearch` in Row, not Column.
e.g You should add `QuickSearch` on the field in Row.cs file

**Comment by olaferlandsen** [comment]
@dfaruque I already tried but it don't work. I'll even leave [QuickSearch] on Description column.

**Comment by olaferlandsen** [comment]
So sorry, now it works but after clean cache.
Thanks too much for you time!
