### ISSUE TITLE
Translations module

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#3428]
Translations module is an effective way to change DisplayNames without hard coding. 
When a class extends another class, for example : 

```
[ConnectionKey("Default"), TableName("[public].[Activity]"), DisplayName("Activity"), InstanceName("Activity"), TwoLevelCached]
    [ReadPermission(PermissionKeys.ActivityListUserExecutedByOpen.View)]
   
    public sealed class ActivityListUserExecutedByOpenRow : ActivityRow
```
I notice that : 

1. Fieldnames of ActivityListUserExecutedByOpenRow are not listed as local text key in Translations module.  Seems logical.
2. Changes for DisplayNames of the superclass ActivityRow in the Translations module are not reflected in the grid and form of the ActivityListUserExecutedByOpen module. And that's a pity, because probably only hard coding the DisplayNames will do the job, I guess, or...........?

Any solution ?

**Comment by GreenUtil** [comment]
When a Row class inherits from another Row class, the permission keys are inherited, or in any case, the permission keys of the superclass have to be assigned in the role/permissions system to let the subclass work. Is it possible to let the DisplayNames be inherited as well ?

**Comment by volkanceylan** [comment]
No, that's not possible, and inheritance for rows are not so recommended, avoid unless absolutely necessary.

**Comment by GreenUtil** [comment]
Ok, that's a pity. Re-using code by inheritance is a very powerful aspect of .NET C#. Why not use it ?
