### ISSUE TITLE
LookupEditor too slow with too much rows

### ISSUE THREAD

**Issue by olaferlandsen** [volkanceylan/Serenity#3429]
I have one table(members) with around 19,000 rows and using it on a `LookupEditor`.
The problem is, the `LookupEditor` download all rows and show it "paginated" on dropdown.
How I can improve it with? This `LookupEditor` is too slow...

Example:
```C#
using System.ComponentModel;
using Xyz.Entities;

namespace Colabra.smu.Agenda.Forms
{
    using Serenity.ComponentModel;
    using System;
    [DisplayName("Bla")]
    [FormScript("Xyz.Members")]
    [BasedOnRow(typeof(Entities.MembersRow), CheckNames = true)]
    public class MyForm
    {
        public Int64 Id{ get; set; }
        [DisplayName("Members"), LookupEditor(typeof(MembersRow))]
        public Int64 Member { get; set; }
        
    }
}
```

**Comment by Estrusco** [comment]
See this old post https://github.com/volkanceylan/Serenity/issues/375

**Comment by brunobola** [comment]
@olaferlandsen Please close the issue if solved....
