### ISSUE TITLE
Is there any SQL Transaction when saving record of Master-Detail relationship?

### ISSUE THREAD

**Issue by kimheangcheng** [volkanceylan/Serenity#3430]
Hello Team,

Is there anyone could tell me whether saving record of Master-Detail relationship is using SQL transaction or not? If not, could you please guide me to do it by open sql transaction and rolling back if there is something wrong while saving data.

Thank you.

**Comment by hannesb** [comment]
Yes.

**Comment by volkanceylan** [comment]
IUnitOfWork contains and indicates a transaction.
