### ISSUE TITLE
Serenity 3.6.0 Upgrade Guide

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#3433]
Serenity 3.6.0 comes with React integration but it is currently activated in StartSharp only. Anyway, once you upgrade to Serenity 3.6.0, you may get some errors about React, as Serenity.CoreLib has references to it.

> Serenity doesn't require React, it is just a TypeScript warning, so, you don't actually need to include React scripts in your site

To resolve such errors, you'll need to include typing for React in your package.json:

```json
  "dependencies": {
    //...
    "@types/react": "^16.1.0",
  }
```

**Comment by kjaraa** [comment]
Thanks @volkanceylan :)

**Comment by ga5tan** [comment]
@volkanceylan  is the React going to be replacing jQuery in frontend interactions?

**Comment by volkanceylan** [comment]
No, not yet, they'll be working together for now

**Comment by volkanceylan** [comment]
React will be *replacing* Vue actually, this post has more info on that:

http://serenity.is/blog/2018/04/03/hello-react-email-client

**Comment by Estrusco** [comment]
Thank you!

**Comment by kilroyFR** [comment]
Question here, i have integrated 3.6.0 with react and i am using CardViewMixin.
It works but i still always have warnings (i have react listed in packages.json)

```
warning TS2304: Cannot find name 'React'.
warning TS4020: 'extends' clause of exported class 'xxxxCard' has or is using private name 'React'.
```

I have created another Startsharp dummy project but dont have those warnings.

Is there something (trick) i did miss ?

**Comment by ga5tan** [comment]
did u do this?
"dependencies": {
    //...
    "@types/react": "^16.1.0",
  }

add dependancy to package.json as Volkan said?

**Comment by kilroyFR** [comment]
yes i did this. Did a file compare of allmost all files from startsharp.

**Comment by volkanceylan** [comment]
Closing this, @kilroyFR if you are still having this issue, please try updating Visual Studio and TypeScript. Especially VS 2015 might have such issues.

**Comment by trusktr** [comment]
Regarding the all-too-common "has or is using private name" error, I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
