### ISSUE TITLE
Group View in Grid

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3435]
Dear,
Following the steps in the example http://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid
I implemented it on my grid, but when I visualized I noticed that it is repeating some items as shown in the image below, the items highlighted in yellow.

![image](https://user-images.githubusercontent.com/7516443/38329191-71fe1d00-3823-11e8-9012-da316c27ee5e.png)

Can I solve this?

**Comment by brunobola** [comment]
Your records don't seem to be repeated, check your query,
Do a distinct to see if they really are repeated or not.

**Comment by juliermefelix** [comment]
the query is derived from several tables with the field 'IDSala', I want to display for example what has inside the IT room (example: computer, printer, nobreak)

I made a distinct and actually the query is repeating

in the image above for example I have the 'Library' room in it I have 4 computers (EST00800131 A EST00800134) and 2 printers, but note that the printers repeat for each line of the computer

I do not know how to do this with this grouping on the grid, I thought of something like a excel table.

or something like cubes.

**Comment by hannesb** [comment]
Grid grouping is not good for what you want. It does not condense the records in any way. It just collects records with a certain property ('Nome Sala' in your screenshot) under a heading.

Maybe a sql view on server side is what you need.

**Comment by JohnRanger** [comment]
@juliermefelix ,

may I ask you to provide a mockup screenshot how you want the outcome to look like?

Maybe two different grids are necccessary?

(1) one which only shows the computers in a room
(2) one which only shows the printers in a room

For (1), make a SQL view with a select distinct which covers the room and the computer field
For (2), make a SQL view with a select distinct which covers the room and the printer field

Then use sergen to make each a grid from (1) and (2) and do your grid grouping.

Maybe this solves your problem.

With kind regards,

John

**Comment by juliermefelix** [comment]
Dear,
I'm trying, using the UNION query in sql, I was able to group the equipment in the room, but who does not know the equipment will not know the type of equipment it is (printer, monitor, nobreak, etc.)
When entering the report appears the error due to primary key, but after clicking the grouping button the visualization is displayed, as shown below.

error:
![image](https://user-images.githubusercontent.com/7516443/38580102-7c722892-3cdf-11e8-96aa-41fed2f63f4a.png)

after clicking the group button
![image](https://user-images.githubusercontent.com/7516443/38580181-a80623e6-3cdf-11e8-8b38-9370faa5063e.png)

in the sql query attachment.
[sql_Rela.txt](https://github.com/volkanceylan/Serenity/files/1896212/sql_Rela.txt)

**Comment by juliermefelix** [comment]
Dear,
I reached the goal of the grid, as shown below. Now I need to put the button to export to PDF but it is not giving and also solve the problem of the initial error that is related to the primary key.

![image](https://user-images.githubusercontent.com/7516443/38633528-5b81c054-3d96-11e8-8512-791d92f1a00c.png)

Follow the code that forms the button to display the grouping.

'protected getButtons(): Serenity.ToolButton[]{
            var buttons = super.getButtons();

             return  [{
                title: 'Visualizar',
                cssClass: 'expand-all-button',
                onClick: () => this.view.setGrouping(
                    [{
                        formatter: x => 'Sala: ' + x.value + ' (' + x.count + ' items)',
                        getter: 'NomeSala'
                    }])
            },
          
                             
            ];
        }'

I tried putting the export button to PDF there but I could not execute it.

**Comment by volkanceylan** [comment]
Grouping and PDF doesn't work together.
