### ISSUE TITLE
DropDownTreeEditor or TreeEditor in ComboBox

### ISSUE THREAD

**Issue by vsudik** [volkanceylan/Serenity#3436]
Hello everyone,
is it possible to make DropDownTreeEditor or TreeEditor in ComboBox?
Could somebody give some ideas how to do it?

**Comment by JohnRanger** [comment]
@vsudik,

can you provide a mockup of how that should like? I have difficulty to visualize such a thing in my mind...

With kind regards,

John

**Comment by vsudik** [comment]
More precisely - DropDownTreeView or TreeView in ComboBox. Items of ComboBox DropDownList must be  in TreeView  not in List.

**Comment by vsudik** [comment]
Does nobody else need ComboBox with drop down tree of items on form of dialog?

**Comment by dfaruque** [comment]
Yes I need.
