### ISSUE TITLE
Using serenity Framework without an actual SQL table

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3437]
Dear all,

**Situation:**
I want to create an SF-based app which will control several Windows Services.
Now one of the Grids should reflect the current status of the windows services on a specific server.
The status of the services I will retrieve programmatically.

**SF-related question:**
As I want to avoid (if reasonably possible) to run a scan on the given server for the status of the services and then store the current status of the services into a table and then show the content of the table but want rather to just scan the status of the services and return an entity created by the scan routine...

My question is: Does the SF allow for such scenarios (e.g. store the data which should be showed within the SF-Grid only in-memory (without using an actual table on the SQL backend)?

Thanks for any input regarding this.

With kind regards,

John

**Comment by dfaruque** [comment]
What about creating a fake list of entities and returned that from your endpoint instead of calling repository method?

**Comment by JohnRanger** [comment]
@dfaruque ,

thanks - good idea. Will try to go down that route.

With kind regards,

John
