### ISSUE TITLE
MVC Controler and View

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#3438]
Good Day

I want to know if it is possible to have your own mvc controller and views in serenity, I already have a controller and views I am getting routing errors when I include them in my solution.

**Comment by sshandu** [comment]
Highlighted controller should be called along with views/actions


the bellow views in account folder must be viewed on the application

**Comment by brunobola** [comment]
Yes it is possible if course.
If you check previous issues will find usefull information.

**Comment by sshandu** [comment]
Thanks for pointing that out, I find that it is possible to do what I asked
through the  *Endpoint.cs *file,
