### ISSUE TITLE
ID saved to table instead of value from LookupEditor

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#3439]
Hi all, 

I've not used Serenity for a long time and have since forgotten some aspects of how to use it.
I have a similar issue to #980 but the resolution is not what I'm looking for.

I have a lookupeditor which shows string values from a table, when I save those values in a form the grid shows IDs from the referenced table, what I would like is to save the actual string values displayed in the LookupEditor directly into table, not the ID.

![image](https://user-images.githubusercontent.com/20558784/38367537-de359f7c-38da-11e8-8dc0-4b715be4b9cb.png)

Grid should display what's displayed in form, and RestoreDatabase table should store the actual values, not IDs, is that possible without any elaborate effort?

**Comment by dfaruque** [comment]
user autocomplete like      
  `[LookupEditor(typeof(...Row), AutoComplete = true)]`

**Comment by abelal83** [comment]
just tried that but no luck, still same result.

`        [LookupEditor(typeof(DatabasesRow), AutoComplete = true)]
        [DisplayName("Database"), Size(255), NotNull, QuickSearch]
        public String Database
        {
            get { return Fields.Database[this]; }
            set { Fields.Database[this] = value; }
        }`

![image](https://user-images.githubusercontent.com/20558784/38372604-26232e74-38e7-11e8-8a6a-2635a9b5cd45.png)

**Comment by hannesb** [comment]
See CustomerCountryLookup.cs in Serene template.

**Comment by abelal83** [comment]
thanks for you response @hannesb 
I was hoping to avoid using lookupscripts but if that's the only way I'm happy to do so, is there no way to do it otherwise? I was hoping there may be an attribute to use value as is :)

**Comment by abelal83** [comment]
thanks @brunobola and @hannesb for your help.

lots of options, I'll test them out and see what works best. Thank you both again!
