### ISSUE TITLE
Installation Wizard with Serenity

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#344]
Dear Volkaceylan,

It's Great framework

We have develop some application with Serenity

We would like to host it on Microsoft Web Gallery

We would like to ask user installing application for the first time to create Admin User

How to achieve this?

Many Thanks,
Sameer

**Comment by volkanceylan** [comment]
I don't know much about web app installers but you can probably find some open source ones. If you are gonna ask user admin username / password, you should remove admin insert statement from initial migration and find a way to get admin username from web.config etc so you can handle permission checks in PermissionService

**Comment by samdubey** [comment]
Thanks
