### ISSUE TITLE
Convert.ToDecimal with '.' and ',' Excel import

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#3440]
Hi,
i need help about convert field with decimal separator '.' to ',' when use excel import .
Original in excel is value : 
**58514,6**
I use syntax :
Convert.ToDecimal(worksheet.Cells[row, 4].Value ?? 0, CultureInfo.CurrentCulture);

and in mssql convert is : 5814.6 insted of 58541,60

Please help

**Comment by brunobola** [comment]
You can always treat the value before really using it, for instance converting the string to a correct readable Decimal according to your culture settings and/or Sql server settings.

that way even it nothing is wrong you just replace the '.' by '.' or other ...

**Comment by Nikola7i** [comment]
Yes, that is one way I tried, but can you please give me some example ? I converted to string, replace '.' with ',' , and how to get back to decimal for sql ?

**Comment by volkanceylan** [comment]
Probably value is string, check the Value you see at Value
