### ISSUE TITLE
Administration links 

### ISSUE THREAD

**Issue by tuppoeq** [volkanceylan/Serenity#3442]
If I create a new project using the VS template and open RoleGrid.ts or any other .ts file and save it the web.js file gets created.  Once that happens all Administration links breaks (Languages/Users/Roles).  

I found that if I look at the web.js file it moves the return value of the function declaration, if I use KDIFF to merge it back everything works again.

![capture](https://user-images.githubusercontent.com/1531045/38401028-fc5bc1f0-3918-11e8-8cb7-6f995fb7ba71.PNG)

**Comment by volkanceylan** [comment]
Update your TypeScript
