### ISSUE TITLE
Endless errors

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3449]
Hi

why do I get such a screen?
![image](https://user-images.githubusercontent.com/36483170/38462983-eae27930-3ab4-11e8-9632-34002e61ef75.png)

In console:
![image](https://user-images.githubusercontent.com/36483170/38462987-08e9bb8c-3ab5-11e8-978c-ece64a9eb028.png)
afterwards the application is not  working anymore

**Comment by dfaruque** [comment]
try these
- running Visual Studio as an administrator.
- grant the (windows user/iisuser/iuser etc.) to access the web folder

**Comment by ga5tan** [comment]
@dfaruque thx.
normally it works, but sometimes I get erroring out like this. I wanna figure it out, so that it never happens in production

**Comment by ga5tan** [comment]
@dfaruque I think it may be either when I change something on server on exception
or when maybe there is a problem in TS.
it' shappening less  now
but I am surprised nobody had the same problems...

**Comment by brunobola** [comment]
@ga5tan It points out to be a permissions (scripts folder....) problem, and there several issues regarding this already, that's why probably people don't have this problem.
