### ISSUE TITLE
publish to IIS from VS on windows 10 shows success but browsing localhost throws error

### ISSUE THREAD

**Issue by Amitloh** [volkanceylan/Serenity#3450]
I was successfully able to build serene app using configuration guide(empty folder etc.) and it also works in debug from VS but after publishing to IIS it shows below error.
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Module | IIS Web Core
-- | --
Unknown
Not yet determined
0x8007000d
 
\\?\C:\inetpub\wwwroot\serenity\web.config

**Comment by ga5tan** [comment]
is there indeed web.config there?

**Comment by Amitloh** [comment]
yes there is a web config in published folder and VS shows publish as successful.

**Comment by brunobola** [comment]
@Amitloh check if your webconfig have incorrect values and/or tags
