### ISSUE TITLE
Master Detail does not populate foreign key in detail

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3452]
Hi

I am getting error saving master detail row. column UserOrderedItems.Payment is not filled in with guid of master table (UserPayment.Guid)

Master detail relation works ok on displaying details grid in edit form.

I create detail entity in service:
`PaymentRequest.Entity.DetailList = new List<Entities.UserOrderedItemsRow>{new Entities.UserOrderedItemsRow
                    {
                        ItemOrder = 1,
                        ProductCategory = 1,
                        ProductName = "Registration",
                        Quantity = 1,
                        Price = UserRequest.Entity.EventPrice,
                        Subtotal = UserRequest.Entity.EventPrice
                    } };

                    //Save Payment
                    new MyRepository().Create(myUow, PaymentRequest);`

but saving fails with error Payment field cannot be null.

master (UserPaymentRow) looks like this:
` [DisplayName("Details"), MasterDetailRelation(foreignKey: "Payment"), NotMapped]
        public List<UserOrderedItemsRow> DetailList
        {
            get { return Fields.DetailList[this]; }
            set { Fields.DetailList[this] = value; }
        }`

detail looks like this:
`[DisplayName("Payment"), ForeignKey("[dbo].[UserPayment]", "Guid"), LeftJoin("jPayment"), Updatable(false)]
        public Guid? Payment
        {
            get { return Fields.Payment[this]; }
            set { Fields.Payment[this] = value; }
        }`

I based this on Oders and OrderDetails from Northwind sample, but for hours cannot figure out what is wrong.

**Comment by dfaruque** [comment]
put `[MinSelectLevel(SelectLevel.List)]` on top of the filed in your detailRow.cs

**Comment by ga5tan** [comment]
Which field? Payment? I copied calculated field subtotal from orderdetail and no joy:
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Cannot insert the value NULL into column 'Payment', table 'dbo.UserOrderedItems'; column does not allow nulls. INSERT fails.

**Comment by dfaruque** [comment]
Sorry, I am bit confused. 
In the issue the title, you said another issue.
anyway, in database Is the `Payment `in is nullable?

**Comment by dfaruque** [comment]
remove Updatable(false) from `Payment` field

**Comment by ga5tan** [comment]
it looks like this now (master)
`
[DisplayName("Details"), MasterDetailRelation(foreignKey: "Payment", IncludeColumns = "Payment")]
        public List<UserOrderedItemsRow> DetailList
        {
            get { return Fields.DetailList[this]; }
            set { Fields.DetailList[this] = value; }
        }
`


detail:
`

[DisplayName("Payment"), ForeignKey("[dbo].[UserPayment]", "Guid"), LeftJoin("jPayment"), MinSelectLevel(SelectLevel.List)]
        public Guid? Payment
        {
            get { return Fields.Payment[this]; }
            set { Fields.Payment[this] = value; }
        }

`

**Comment by ga5tan** [comment]
@hannesb  any idea why would the detail field not get populated by guid field of master table?

**Comment by ga5tan** [comment]
ok, I found somewhere that Guid fields have to be manually set.
I did that on Master and it works, but problem is, I am unable to get GUID to the detail. Even if I set it, I think MasterDEtail behaviour clears it. It is also NOT calling any events from Repository, so I dont know how to set it back to not null.
Any ideas

**Comment by dfaruque** [comment]
what is your primary key in master table?

**Comment by ga5tan** [comment]
Guid of type Guid
from other thread I gathered it has to be populated manually on Master.
on Detail I had to use hack and designate IDField as some other, cause otherwise Guid set by me got nulled
