### ISSUE TITLE
Cannot implicitly convert type 'Serenity.Data.DecimalField' to 'Serenity.Data.IIdField'	MySerene.Web	C:\Projects\MySerene\MySerene.Web\Modules\Hospital\TblDept\TblDeptRow.cs	

### ISSUE THREAD

**Issue by Amitloh** [volkanceylan/Serenity#3455]
Getting below error after generating serene code for my custom database in sql.
Cannot implicitly convert type 'Serenity.Data.DecimalField' to 'Serenity.Data.IIdField'	MySerene.Web	C:\Projects\MySerene\MySerene.Web\Modules\Hospital\TblDept\TblDeptRow.cs

**Comment by brunobola** [comment]
Have you a primary key in your table ?
If so, is it a decimal column ?
