### ISSUE TITLE
Dynamically removing/adding   @Serenity.Decorators.panel()

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3457]
hey there, is it possible to dynamically change settings of a dialog (either removing or adding equivalency of the   @Serenity.Decorators.panel()) ?

I dont want to generate 2 applications versions because some users wants the PANEL display (use on mobile) and the others want the dialog box/popup display.

Thanks !

**Comment by brunobola** [comment]
@kilroyFR I believe it isn't really necessary, if you chose the jquery ui with dialogs (better for some business used to ERP applications)  and then use the application with the smartphone the ui is automatic updated.

That always have been the default behaviour of serenity.

**Comment by volkanceylan** [comment]
This post has more info: http://serenity.is/blog/2017/11/29/panel-mode-dialogs

**Comment by kilroyFR** [comment]
Very nice, perfect Volkan. Thanks
