### ISSUE TITLE
Implement query using Serenity.Data 

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#346]
Hello sir,

I have filter cascade lookup for grid data filter and I want below query so how to implement this using Serenity.Data 

SELECT DISTINCT 
jClass.[CourseId] AS [ClassCourseId],
jClass.[ClassName] AS [ClassClassName] 
FROM [dbo].[Classes] jClass 
LEFT JOIN [dbo].[Courses] jCourses ON (jClass.[CourseId] = jCourses.[CourseId]) 
WHERE jClass.[CourseId] != N'' AND jClass.[CourseId] IS NOT NULL AND jClass.[ClassId] != N'' AND jClass.[ClassId] IS NOT NULL

I used below query,

 public SubjectsByClassLookup()
        {
            IdField = SubjectsRow.Fields.ClassCourseId.PropertyName;
            TextField = SubjectsRow.Fields.ClassClassName.PropertyName;
            //IdField = ClassesRow.Fields.CourseId.PropertyName;
            //TextField = ClassesRow.Fields.ClassName.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Entities.SubjectsRow.Fields;
            query.Distinct(true)
                .Select(fld.ClassCourseId)
                .Select(fld.ClassId)
                .Where(
                    new Criteria(fld.ClassCourseId) != "" &
                    new Criteria(fld.ClassCourseId).IsNotNull() &
                    new Criteria(fld.ClassId) != "" &
                    new Criteria(fld.ClassId).IsNotNull());
        }

**Comment by sayuga** [comment]
If you are going to cascade the you'll also want to add a Lookup query for the parent item. Once you do that you can go to the xyzGrid.cs and implement it there. 

  [LookupScript("MyProject.ParentField")]
    public class ParentFieldLookup : RowLookupScript<MyRow>
    {
        Field fld = MyRow.Fields.ParentField;

        public ParentFieldLookup()
        {
            IdField = TextField = fld.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {            
            query.Distinct(true)
                .Select(fld)
                .Where(
                    new Criteria(fld) != "" &
                    new Criteria(fld).IsNotNull());
        }

        protected override void ApplyOrder(SqlQuery query){}
    }

    //Cascades from Parent Field
    [LookupScript("MyProject.ChildField")]
    public class ChildFieldLookup : RowLookupScript<MyRow>
    {
        Field fldOne = MyRow.Fields.ParentField;
        Field fldTwo = MyRow.Fields.ChildField;

        public ChildFieldLookup()
        {
            IdField = TextField = fldTwo.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            query.Distinct(true)
                .Select(fldOne)
                .Select(fldTwo)
                .Where(
                    new Criteria(fldOne) != "" &
                    new Criteria(fldOne).IsNotNull() &
                    new Criteria(fldTwo) != "" &
                    new Criteria(fldTwo).IsNotNull());
        }

        protected override void ApplyOrder(SqlQuery query){}
    }


Once you have both the parent and child query filters in place. You then go to xyzGrid.cs and override the CreateToolbarExtension and add the filter there referencing the lookup script. 

  protected override void CreateToolbarExtensions()
        {
            base.CreateToolbarExtensions();

           
            // Parent-> Child Cascading Filter  - PARENT
            AddEqualityFilter<LookupEditor>(Fields.ParentField,
                options: new LookupEditorOptions { LookupKey = "MyProject.ChildField" });

            // Parent-> Child Cascading Filter  - CHILD
            AddEqualityFilter<LookupEditor>(Fields.ChildField,
                options: new LookupEditorOptions
                {
                    LookupKey = "MyProject.ChildField",
                    CascadeFrom = Fields.ParentField                    
                });
      }

**Comment by volkanceylan** [comment]
You query lacks .From(MyRow.Fields) or you probably forgot to call base .PrepareQuery(). What is error you are getting?

**Comment by volkanceylan** [comment]
Please reopen if not resolved.
