### ISSUE TITLE
Why Not load ‘'~/Scripts/CKEditor/config.js’,CKEditor Config doesn't work

### ISSUE THREAD

**Issue by Csirme** [volkanceylan/Serenity#3462]
I try this:

HtmlContentEditor.includeCKEditor = function () {
            $('<script/>').attr('type', 'text/javascript')
               .attr('id', 'CKEditorScriptConfig')
               .attr('src', Q.resolveUrl('~/Scripts/CKEditor/config.js?t=I2G9'))
               .appendTo(window.document.head);
        };

But CKEditor Config also  doesn't work ,can you help me ?

**Comment by Csirme** [comment]
Serenity Network:
![image](https://user-images.githubusercontent.com/16202890/38603298-ca9a2108-3d9f-11e8-8bff-0b953368d6b8.png)

Ckeditor Demo Network:
![image](https://user-images.githubusercontent.com/16202890/38603380-10100e5a-3da0-11e8-9cda-9f831dd4d1a1.png)

**Comment by Csirme** [comment]
public class MintInformationForm
    {  
      [DisplayName("Content"), HtmlContentEditor, CssClass("MintInformationContent")]
        public String Content { get; set; }
}

**Comment by volkanceylan** [comment]
We don't use config.js, see source of HtmlContentEditor, NoteContentEditor etc.
