### ISSUE TITLE
Popup Dialog on button click for custom changes

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#3463]
Hi,
Here am trying a scenario like this in order grid select some orders with check box. On button click the selected orders and their price columns to be displayed in a popup dialog with a text box where the new price will be entered. On update button click the price of the orders to be updated with the new price entered. Any Ideas on how to achieve this.

Thanks

**Comment by hairangsua** [comment]
I think it possible but i dont know you want to update direct price to Database or just view in grid? 
i think you should try some example about inline button in grid. Click to button to show a dialog have prive editor and call save request to update price to db. after this call refresh grid and your new price will be show
