### ISSUE TITLE
Excel Import Issue

### ISSUE THREAD

**Issue by GoodGoing** [volkanceylan/Serenity#3466]
Hi All,

Not sure what i am doing wrong, help is needed from the group, this is my first attempt with Serenity.

Trying to import from an excel file and below are the details:

1. in the main grid added a custom button
2. Created 4 new files - CostImportDialog.ts, CostImportEndpoint.cs, CostImportForm.cs and CostImportGrid.ts

In the design time i get an error:
TS2304: Cannot find name 'CostImportForm'.	TypeScript

When I click the import button - i get an error 
**"Uncaught TypeError: USTVendorCost4.CostImportDialog is not a constructor"**
![image](https://user-images.githubusercontent.com/38285604/38616810-1b9c6eb8-3d4a-11e8-8f0d-84cabe6c1b4d.png)

Code:

**TrfVendorCostGrid.ts**
`
            buttons.push({
                title: 'Import',
                cssClass: 'export-xlsx-button',
                onClick: () => {
                    // open import dialog, let it handle rest
                    var dialog2 = new USTVendorCost4.CostImportDialog().loadNewAndOpenDialog;
                    dialog2.element.on('dialogclose', () => {
                        this.refresh();
                        dialog2 = null;
                    });
                    dialog2.dialogOpen();
                }
            });
`

**CostImportDialog.ts**
`namespace USTVendorCost4.Default {

    @Serenity.Decorators.registerClass()
    export class CostImportDialog extends Serenity.PropertyDialog<any, any> {

        private form: CostImportForm;

        constructor() {
            super();

            this.form = new CostImportForm(this.idPrefix);
        }

        protected getDialogTitle(): string {
            return "Excel Import";
        }

        protected getDialogButtons(): Serenity.DialogButton[] {
            return [
                {
                    text: 'Import',
                    click: () => {
                        if (!this.validateBeforeSave())
                            return;

                        if (this.form.FileName.value == null ||
                            Q.isEmptyOrNull(this.form.FileName.value.Filename)) {
                            Q.notifyError("Please select a file!");
                            return;
                        }

                        CostImportService.ExcelImport({
                            FileName: this.form.FileName.value.Filename
                        }, response => {
                            Q.notifyInfo(
                                'Inserted: ' + (response.Inserted || 0) +
                                ', Updated: ' + (response.Updated || 0));

                            if (response.ErrorList != null && response.ErrorList.length > 0) {
                                Q.notifyError(response.ErrorList.join(',\r\n '));
                            }

                            this.dialogClose();
                        });
                    },
                },
                {
                    text: 'Cancel',
                    click: () => this.dialogClose()
                }
            ];
        }
    }
}`

**CostImportEndpoint.cs**
`namespace USTVendorCost4.Default.Endpoints
{
    using Northwind.Entities;
    using Northwind.Repositories;
    using OfficeOpenXml;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Web.Mvc;
    using MyRow = Northwind.Entities.ProductRow;

    [RoutePrefix("Services/Default/CostImport"), Route("{action}")]
    [ConnectionKey(typeof(MyRow)), ServiceAuthorize]
    public class CostImportController : ServiceEndpoint
    {
        [HttpPost]
        public ExcelImportResponse ExcelImport(IUnitOfWork uow, ExcelImportRequest request)
        {
            request.CheckNotNull();
            Check.NotNullOrWhiteSpace(request.FileName, "filename");

            UploadHelper.CheckFileNameSecurity(request.FileName);

            if (!request.FileName.StartsWith("temporary/"))
                throw new ArgumentOutOfRangeException("filename");

            ExcelPackage ep = new ExcelPackage();
            using (var fs = new FileStream(UploadHelper.DbFilePath(request.FileName), FileMode.Open, FileAccess.Read))
                ep.Load(fs);

            var p = ProductRow.Fields;
            var s = SupplierRow.Fields;
            var c = CategoryRow.Fields;

            var response = new ExcelImportResponse();
            response.ErrorList = new List<string>();

            var worksheet = ep.Workbook.Worksheets[1];
            for (var row = 2; row <= worksheet.Dimension.End.Row; row++)
            {
                try
                {
                    var productName = Convert.ToString(worksheet.Cells[row, 1].Value ?? "");
                    if (productName.IsTrimmedEmpty())
                        continue;

                    var product = uow.Connection.TryFirst<ProductRow>(q => q
                        .Select(p.ProductID)
                        .Where(p.ProductName == productName));

                    if (product == null)
                        product = new ProductRow
                        {
                            ProductName = productName
                        };
                    else
                    {
                        // avoid assignment errors
                        product.TrackWithChecks = false;
                    }
                    
                    var supplierName = Convert.ToString(worksheet.Cells[row, 2].Value ?? "");
                    if (!string.IsNullOrWhiteSpace(supplierName))
                    {
                        var supplier = uow.Connection.TryFirst<SupplierRow>(q => q
                            .Select(s.SupplierID)
                            .Where(s.CompanyName == supplierName));

                        if (supplier == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": Supplier with name '" +
                                supplierName + "' is not found!");
                            continue;
                        }

                        product.SupplierID = supplier.SupplierID.Value;
                    }
                    else
                        product.SupplierID = null;

                    var categoryName = Convert.ToString(worksheet.Cells[row, 3].Value ?? "");
                    if (!string.IsNullOrWhiteSpace(categoryName))
                    {
                        var category = uow.Connection.TryFirst<CategoryRow>(q => q
                            .Select(c.CategoryID)
                            .Where(c.CategoryName == categoryName));

                        if (category == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": Category with name '" +
                                categoryName + "' is not found!");
                            continue;
                        }

                        product.CategoryID = category.CategoryID.Value;
                    }
                    else
                        product.CategoryID = null;

                    product.QuantityPerUnit = Convert.ToString(worksheet.Cells[row, 4].Value ?? "");
                    product.UnitPrice = Convert.ToDecimal(worksheet.Cells[row, 5].Value ?? 0);
                    product.UnitsInStock = Convert.ToInt16(worksheet.Cells[row, 6].Value ?? 0);
                    product.UnitsOnOrder = Convert.ToInt16(worksheet.Cells[row, 7].Value ?? 0);
                    product.ReorderLevel = Convert.ToInt16(worksheet.Cells[row, 8].Value ?? 0);

                    if (product.ProductID == null)
                    {
                        new ProductRepository().Create(uow, new SaveRequest<MyRow>
                        {
                            Entity = product
                        });

                        response.Inserted = response.Inserted + 1;
                    }
                    else
                    {
                        new ProductRepository().Update(uow, new SaveRequest<MyRow>
                        {
                            Entity = product,
                            EntityId = product.ProductID.Value
                        });

                        response.Updated = response.Updated + 1;
                    }
                }
                catch (Exception ex)
                {
                    response.ErrorList.Add("Exception on Row " + row + ": " + ex.Message);
                }
            }

            return response;
        }
    }
}
`

**CostImportForm.cs**
`
namespace USTVendorCost4.Default.Forms
{
    using Serenity.ComponentModel;
    using Serenity.Web;
    using System;

    [FormScript("Default.TrfVendorCost")]
    public class CostImportForm
    {
        [FileUploadEditor, Required]
        public String FileName { get; set; }
    }
}
`

**CostImportGrid.ts**
`namespace USTVendorCost4.Default {

    @Serenity.Decorators.registerClass()
    export class CostImportGrid extends Northwind.ProductGrid {

        constructor(container: JQuery) {
            super(container);
        }

        /**
         * This method is called to get list of buttons to be created.
         */
        protected getButtons(): Serenity.ToolButton[] {

            // call base method to get list of buttons
            var buttons = super.getButtons();

            // add our import button
            buttons.push({
                title: 'Import From Excel',
                cssClass: 'export-xlsx-button',
                onClick: () => {
                    // open import dialog, let it handle rest
                    var dialog = new CostImportDialog();
                    dialog.element.on('dialogclose', () => {
                        this.refresh();
                        dialog = null;
                    });
                    dialog.dialogOpen();
                }
            });

            return buttons;
        }

    }
}`

Guidance please. 

Thnx

**Comment by GoodGoing** [comment]
I tried using the existing Product Import sample but not much success

**Comment by volkanceylan** [comment]
You don't have parenthesis after loadNewAndOpenDialog for a start.

**Comment by volkanceylan** [comment]
And also you are missing namespace, TypeScript should be raising errors in Visual Studio already, you need to check build errors carefully.

**Comment by volkanceylan** [comment]
E.g. it should be `new USTVendorCost4.Default.CostImportDialog()` not `new USTVendorCost4.CostImportDialog()`

**Comment by GoodGoing** [comment]
Thanks a ton Volkanceylan, will be making the suggested changes and update the thread.
really appreciate your feedback.

**Comment by GoodGoing** [comment]
No luck yet

run time error:
![image](https://user-images.githubusercontent.com/38285604/38764740-83576f28-3f69-11e8-85b7-2d10d7b14be8.png)



Compile error:
![image](https://user-images.githubusercontent.com/38285604/38764802-9140aa86-3f6a-11e8-9b00-a5dfe199336b.png)


Grid: Export button logic:
![image](https://user-images.githubusercontent.com/38285604/38764838-564ad70c-3f6b-11e8-8e84-69d0464b6c87.png)


Form:
![image](https://user-images.githubusercontent.com/38285604/38764845-91b0009c-3f6b-11e8-966c-cfaec302bff5.png)


Not sure why there are so many compile errors!

Help needed...

**Comment by GoodGoing** [comment]
will for sure do the needful, new to typescript.

Lot of compile errors went away after doing the Transform T4 action
but it ended up giving me new errors:

![image](https://user-images.githubusercontent.com/38285604/38780383-3b45b948-408a-11e8-9b1a-8ebab8fc1e97.png)

looks like reference errors, any quick tip or direction?

**Comment by GoodGoing** [comment]
Going to close the case. thanks for your help Volkanceylan. It is a fantastic solution/tool.
i am sure more Qs down the road.
