### ISSUE TITLE
Not Mapped Field Display

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3467]
Hi,

How to display a Not Mapped field in the grid?
can anyone please help me with this.

**Comment by brunobola** [comment]
Just use an expression and put it in ....columns.cs....

**Comment by JohnRanger** [comment]
Hi @AmuthaKondusamy ,

why do you not want to map a field which you obviously need?
Why not just add the field within xyzRow?

With kind regards,

John

**Comment by brunobola** [comment]
@AmuthaKondusamy Dude just do like I told you...

1.  Add expressin field in Row.cs
2.  Add filed on column.cs
3.  Add field to yout form.cs as readonly for instance....

**Comment by AmuthaKondusamy** [comment]
Hi @brunobola 

In Row,
 [Size(100), NotMapped]
        [Expression("jTest_Table.[testname]", Dialect = "Sqlite")]
        public String Start
        {
            get { return Fields.Start[this]; }
            set { Fields.Start[this] = value; }
        }

In Column,

        public String StartTime { get; set; }

In Form,
 public String StartTime { get; set; }

But it is not working.Do u have any idea?

**Comment by brunobola** [comment]
@AmuthaKondusamy no need to use  NotMapped with Expression:

Row.cs:
```
        [DisplayName("Descrição Pesquisa"), Expression("( (CASE WHEN t0.[Tipo] IS NULL THEN '' ELSE (CASE WHEN LEN(t0.[Tipo])=0 THEN '' ELSE t0.[Tipo] + ' | ' END) END) + isnull(t0.[Descricao], t0.[Tipo]))")]
        public String DescricaoPesquisa
        {
            get { return Fields.DescricaoPesquisa[this]; }
            set { Fields.DescricaoPesquisa[this] = value; }
        }
```

Columns.cs:
`public String DescricaoPesquisa { get; set; }`

Form.cs
`public String DescricaoPesquisa { get; set; }`

**Comment by AmuthaKondusamy** [comment]
@brunobola  If I am taking [NotMapped] attribute out, it is throwing SqlException. 
"'Invalid column name 'Start'.'"

**Comment by AmuthaKondusamy** [comment]
@brunobola ,

Dude, I have done it through getColumns() in grid.ts. I have removed that field in XYZColumn.cs and pushed the columns in getColumns() and implemented the logic there. Now it is working fine.
