### ISSUE TITLE
How to remove/hide quickfilter dynamically? 

### ISSUE THREAD

**Issue by olaferlandsen** [volkanceylan/Serenity#3469]
For example, on my row:

```C#
[QuickFilter]
public string MyField { get; set; }
```

So, on my Grid.ts:

```typescript
protected getQuickFilters() : Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
            let filters = super.getQuickFilters();
            let filter = Q.tryFirst(filters, (x) => x.field == fld.Id);
            filter.remove(); // I wanna this!! for example, to using with condition 
}
```

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/issues/3446

**Comment by olaferlandsen** [comment]
@brunobola I wanna remove quickfilter control dynamically, not a simple control.

**Comment by brunobola** [comment]
@olaferlandsen dude just point some start point, please search the issues....

**Comment by olaferlandsen** [comment]
@brunobola is for GRID not for Dialog

**Comment by brunobola** [comment]
@olaferlandsen I notice that just a little search and find this topics related....won,t be big problem for you to achieve your goal I think.....

https://github.com/volkanceylan/Serenity/issues/2961
https://github.com/volkanceylan/Serenity/issues/342
https://github.com/volkanceylan/Serenity/issues/447

**Comment by olaferlandsen** [comment]
I resolve it with you help:
When set some variable/propertie/member:
```typescript
let filters = super.getQuickFilters();
filters.splice(1,1);
```
