### ISSUE TITLE
IValidatableObject

### ISSUE THREAD

**Issue by ecarandang** [volkanceylan/Serenity#3474]
This is more of a question than an Issue. Is it possible to implement IValidatableObject inside Serenity? If so, how do we use it? Thank you in advance.

**Comment by volkanceylan** [comment]
I don't know what it is, so possibly no, try overriding OnValidateRequest

**Comment by ecarandang** [comment]
Thanks volkan! Really appreciate your reply. And really great work on the framework. I just started learning it for less than a week and the things that I can do with it are really awesome and very easy!!!
