### ISSUE TITLE
Id Field with (guid) won't be passed to the database

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#3479]
Can anyone tell me what I'm doing wrong, I've got a error telling me that a id filed is null saving, having searched previous records I've overrides the BeforeSave and saw It has value, can«t seem to figure this one out :(

@volkanceylan  Any tip ?

Sample Override:
![screenshot_3](https://user-images.githubusercontent.com/10889019/38728377-a4032fee-3f07-11e8-926e-6f8e17d9d608.png)

Error I've Got:
![screenshot_1](https://user-images.githubusercontent.com/10889019/38728394-ae9e9272-3f07-11e8-924f-84b720f1e885.png)

**Comment by volkanceylan** [comment]
MasterDetailBehavior won't let you use arbitrary ID's in client records, as it might be a injection attempt, so on insert it will clear those IDs. You should write a behavior for detail record and set guid there.

Anyway i'd add a SQL table default to that field.

**Comment by brunobola** [comment]
@volkanceylan thanks that makes sence, will do the changes accordingly.
