### ISSUE TITLE
How many ways can I use to custom the showing of one field

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#348]
Just like ,if I have a field wich stored in database with the format of JsonString ,How can I transform json string to keyvalue pair  showing  in edit dialog?

**Comment by volkanceylan** [comment]
Hmm, maybe add some [ClientSide] fields that will be filled OnReturn method of retrieve handler by deserializing that JSON field and filling values to those client side fields.

**Comment by ChenZhaobin** [comment]
Thanks,you just hist the point ,that is what I want
