### ISSUE TITLE
Editor Layout Help

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#3480]
Anybody knows how to remove this using less ?

![image](https://user-images.githubusercontent.com/10889019/38733070-7adba158-3f18-11e8-913e-4c2ec42002dc.png)

**Comment by volkanceylan** [comment]
.s-MyDialog .field.MyField .vx { display: none !important }

**Comment by brunobola** [comment]
@volkanceylan Has always, many thanks.
