### ISSUE TITLE
LookupScript & Typescript Generator

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#3481]
Hello team, sorry if someone ask about this before.

- Right now, I see that if  Row class has LookupScript attribute, Serenity will generate `lookupKey` and `getLookup()`
![image](https://user-images.githubusercontent.com/2279508/38749473-ec35780c-3f7b-11e8-8712-254d6a370e95.png)
If we don't define that attribute, it will not generate typescript code. I think that's fine although it will be better if Serenity can generate default lookup key (by row name, namespace...).

<br />

- BTW, can Serenity generate lookup key &  getLookup() for **custom lookup class**, for example I have  custom lookup classes like bellow:
![image](https://user-images.githubusercontent.com/2279508/38750316-c1710e4e-3f7e-11e8-9abf-7d231bac7aea.png)

Agree that I can use **Q.getLookup('something_key')** but this can cause typo issues. So any chance Serenity generate it for us?

My Serenity version is 3.5.5 and typescritp 2.7.2
Thanks!

**Comment by volkanceylan** [comment]
If you don't add a LookupScript attribute, that means row doesn't have a lookup, not all rows has or should have lookups.

**Comment by minhhungit** [comment]
@volkanceylan yeah, but how about custom lookup, can serenity generate all **custom** lookup into a file or something like that.
I also think if a custom look inherited from Row which used RowLookupScript<Row> then it should generate lookup key into Row.ts file, right :cry:

**Comment by volkanceylan** [comment]
It can, as long as some conditions matched, see these tests:

https://github.com/volkanceylan/Serenity/blob/98785f843a9dab8452f7300fda34690108e9eaa5/Serenity.Test/CodeGeneration/ServerTypingsGenerator/ServerTypingsGeneratorTests.RowLookupKey.cs

**Comment by minhhungit** [comment]
Thank you sir, I will check

**Comment by minhhungit** [comment]
@volkanceylan  After checked it, I think a ROW just have only one lookupKey, right ?
- when we use a [LookupScript] on Row class
- when Row class use an external script, from a custom lookup class (RowLookupScript<External>)
whatever, it always need [LookupScript] attribute and we can not have duplicate [LookupScript] attribute

So, problem is how a Row can have **multiple** lookup, for example, pretend I need 3 Product lookup data, like:
- list product with qty > 0
- list product for a special catalog
- all products 

How can I do it 😳

**Comment by brunobola** [comment]
@minhhungit Maybe you can create a table withthose options then create a lookup and called say "options" them depending the selected change of the option you can filter the source of your lookup achieving what you wan't without the need to further create more lookups to the same row.

**Comment by minhhungit** [comment]
thank you @brunobola , can you give me a quick sample, I'm still don't clear your idea

**Comment by minhhungit** [comment]
I will try to create a pull request to generate custom lookups, something like:
```csharp
[HasCustomLookup(typeof(CustomLookup_Without_Key_Lookup))]
[HasCustomLookup(typeof(CustomLookup_With_Key_Lookup))]
[LookupScript] // primary lookup
public class RowForCustomLookupRow : Row
{
    public class RowFields : RowFieldsBase
    {
    }

    public static RowFields Fields = new RowFields().Init();

    public RowForCustomLookupRow() : base(Fields)
    {
    }
}

[LookupScript]
public class CustomLookup_Without_Key_Lookup : LookupScript
{
}

[LookupScript("This.is.custom.lookup.key")]
public class CustomLookup_With_Key_Lookup : LookupScript
{
}
```
and Row.ts maybe like:
```javascript
export const lookupKey = 'Default.CccCarriers';  // primaryKey

export function getLookup(): Q.Lookup<CccCarriersRow> {
    return Q.getLookup<CccCarriersRow>('Default.CccCarriers');
}

// custom lookup generated code here which I don't know for now
// ...
// ...
```

**Comment by minhhungit** [comment]
typescript code generated will be something like
```javascript
export namespace RssChannelsRow {
    export const idProperty = 'Id';
    // ...

    export const lookupKey = 'Default.CccCarriers'; // primary lookup

    export function getLookup(): Q.Lookup<CccCarriersRow> {
        return Q.getLookup<CccCarriersRow>('Default.CccCarriers');
    }

    // custom
    export declare function CustomLookup_First(): Q.Lookup<{}>;
    export declare function CustomLookup_Second(): Q.Lookup<{}>;

    export enum CustomLookupKeys {
        CustomLookup_First = "CustomLookup_Without_Key_Lookup",
        CustomLookup_Second = "CustomLookup_With_Key_Lookup"
    }

    Object.keys(CustomLookupKeys).forEach(x => {
        (<any>RssChannelsRow)[x] = function () {
            return Q.getLookup(CustomLookupKeys[x]);
        }
    });

    export declare const enum Fields {}
```

**Comment by minhhungit** [comment]
@volkanceylan I created PR https://github.com/volkanceylan/Serenity/pull/3484 
Can you review it please

**Comment by volkanceylan** [comment]
I will later implement that with a Lookups class generated on client side, this version didn't seem Serenity-ish to me

**Comment by minhhungit** [comment]
okay @volkanceylan, sounds interesting. I'm waiting for your push
