### ISSUE TITLE
Error run ' Transform  All T4 Templates ' 

### ISSUE THREAD

**Issue by Csirme** [volkanceylan/Serenity#3486]
Transforming templates for all project items.
-------------------------------------
Transforming template ClientTypes.tt with TextTemplatingFileGenerator ... failed.
Transforming template MVC.tt with TextTemplatingFileGenerator ... succeeded.
Transforming template ServerTypings.tt with TextTemplatingFileGenerator ... failed.
-------------------------------------
Text templating transformation complete.

Error		Compiling transformation: 'InterfaceImplementation' does not contain a definition for 'FullName' and no extension method 'FullName' accepting a first argument of type 'InterfaceImplementation' could be found (are you missing a using directive or an assembly reference?)	Miscellaneous Files	H:\........\Imports\ClientTypes\..\CodeGenerationHelpers.ttinclude	167	

LINE 166 |       foreach (var intf in type.Interfaces)

LINE 167 |          externalType.Interfaces.Add(intf.FullName);

**Comment by minhhungit** [comment]
Check this please https://github.com/volkanceylan/Serenity/issues/3275
