### ISSUE TITLE
New Dialog on Button Click

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#3487]
Hi, 
am working on a Employees project where i have to get the list of employee names from employee table with check box selection and on button click a new dialog should open with the selected employee names and with a text box (one text box is enough) to assign a project to them and on save the data to be saved in a new employeeproject table. Can any body help me with this am able to get the check box selection on employee grid but how to get the new dialog with the selected employee names with text box.

Thanks in advance

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewGrid.ts

**Comment by srinivas1910** [comment]
Thank you @Zahar661 once again i tried this with other examples from some issues but not able to achieve the result thanks for your link will with that and let you know the output.

Regards,
Srinivas
