### ISSUE TITLE
Error with EditorGrids in a dialog - Implement a unique '__id' - preventing dialog opening

### ISSUE THREAD

**Issue by shaunbsoft** [volkanceylan/Serenity#3489]
I have 3 editor grids on a dialog. All three are showing the following error in the console:

"Uncaught Each data element must implement a unique '__id' property. Object at index '0' has no identity value:"

It is preventing the dialog from opening.

All of them have ID fields in the database. This didn't used to prevent the dialog opening, but there did seem to be an issue where it would only load half of the editor grid within the dialog, and would load the other fields as you scrolled along, otherwise, those fields were blurred.

Any ideas on this? Much appreciated.

Shaun.

**Comment by JohnRanger** [comment]
Hi @shaunbsoft ,

your tables which you use with Serenity Framework must have an identity field - that is: It must be marked as the identity field within the table. Also I recommend to set this as the primary index.

With kind regards,

John
