### ISSUE TITLE
Can I use Serenity with a NoSQL db?

### ISSUE THREAD

**Issue by joaolongo** [volkanceylan/Serenity#349]
I am currently developing a LMS platform and I'd like to use Serenity on the Admin part of the website. The problem is I am using MongoDb as main database. Can Serenity be integrated used with MongoDb? I already have a "ORM" that i updated so i could make my life easy with Mongo drivers.

**Comment by volkanceylan** [comment]
UI part can be used with any backend but you need to write your own service handlers for this. Especially entity system (row) and ListRequestHandler is SQL oriented. I don't think MongoDB can execute SQL right? If so, you need to change endpoint List code for example, that takes a ListRequest, converts it into a query usable with MongoDB and return ListResponse.

**Comment by joaolongo** [comment]
I already have the code to make the convertions, i will check those endpoints tonight and see if it's already usable on Serenity. But I think it's going to, because the ORM like tool I am using is really adaptable, about the specific objects, it already handles BSON convertion to me. =]

Date: Wed, 2 Mar 2016 08:04:00 -0800

**Comment by joaolongo** [comment]
About the integration between MongoDb and Serenity... I am currently developing a library to isolate MongoDb, if i succeed, Serenity won't even know it's actually connected to a MongoDb engine. I am currently having a slow progress as I am developing two projects with serenity and I had to abandon the MongoDb approach in one of them... But for the time being the LMS platform will continue to use MongoDb as database.

**Comment by volkanceylan** [comment]
Thanks @joaolongo, i'd like to know about further updates. Let me know if there is something i can help you with.

**Comment by joaolongo** [comment]
Hello, I am currently on a dead end. Serenity as it is right uses migrations to create database and then generate pages and models... The thing is, MongoDb creates the collections on demand. This doesn't mean it's impossible to create a collection without basic data, but I think that I would need to create a library that can replace the migrations function. That being said, could you provide me with a list of the endpoints that I would need to replace on Serenity's source code?
I think that I would progress a a little faster. Another point to highlight is that I will have to make database changes on the WPF project as well (i know its a little obvious but it's good to point this out =] ). 
Anyway, I was also wondering if Serenity would be loose coupled enough in order to unplug sql server, plug Mongo (or another database). Do you have suggestions on how to make a choice option where we can switch between mongo and other DBs?

**Comment by volkanceylan** [comment]
You don't have to handle migrations, you can simply skip them if they are not feasible in MongoDB. Serenity doesn't depend on migrations. Serene runs them using FluentMigrator. You might create a dialect IMongoDbDialect for example to use conditional statements. Anyway Serenity doesn't have any endpoints, Serene (template) does. You should handle UserEndpoint, UserPermissionEndpoint at minimum, or write your own IPermissionService etc.

**Comment by joaolongo** [comment]
I see, then I will start making a dialect and start working on the services.

**Comment by volkanceylan** [comment]
Any updates on this, or you gave up?

**Comment by joaolongo** [comment]
I'm still working on it, but with small progress, as right now I have to much to do in my hands. As soon as I have a workable version I will update you.

PS: Sorry for the (really) delayed response.

**Comment by samdubey** [comment]
+1 for NOSQL Db

**Comment by kpetersondev** [comment]
I hope to give the MongoDB customization a try whenever it is ready.  I know this will be very helpful to my future projects and will help a lot of developers as well.  I wish I could assist but I'm just working on the basics at this stage and using SQL for now.  @joaolongo may the force be with you!

**Comment by samdubey** [comment]
I have found this open source NoSQL DB http://www.litedb.org/
Developed in C# looks promising please have a look

**Comment by samdubey** [comment]
has anyone consider cassandra[https://cassandra.apache.org/]  (it has fairly similar syntax like sql called CQL)

**Comment by teafmartins** [comment]
@joaolongo Any updates with MongoDB ?
Conseguiste adaptar o ao MondoDB ? :)
