### ISSUE TITLE
Change Login Interface - How to Add Lookup ?

### ISSUE THREAD

**Issue by bolaNew** [volkanceylan/Serenity#3491]
Hello, I'm a newbie and before Post I've research issues, and haven't found any that explains how to do this

I want to include a lookup/select in the login page but I don't know how to do this, I've managed to include a text only...

Any tips ?

**Comment by kilroyFR** [comment]
I managed to do this to display Language selection on Login; see LanguageList.ts as sample

**Comment by bolaNew** [comment]
Mr @volkanceylan any tips from you please.

**Comment by brunobola** [comment]
@bolaNew have you tried the @kilroyFR tip ?

**Comment by bolaNew** [comment]
Thanks @kilroyFR  and @brunobola.

**Comment by brunobola** [comment]
@ArsenioInojosa to help @bolaNew post full code otherwise he may not understand.
