### ISSUE TITLE
How to support web api in serenity

### ISSUE THREAD

**Issue by tranthebao** [volkanceylan/Serenity#3493]
i'm want to use api replace service enpoint
serenity's support it.

**Comment by volkanceylan** [comment]
We dont support but you can try

**Comment by tmartinscopo** [comment]
Hi @tranthebao , did you do it?

**Comment by tranthebao** [comment]
Dear Mr tmartinscopo

I got it.

I'm resolved it.

Thanks help.

Regards,

Bao.Tran

**Comment by tmartinscopo** [comment]
@tranthebao and can you share your code? 
I'm trying to do the same, get results from external api and display it in the grid.
