### ISSUE TITLE
How to customize the fields displayed by 'QuickFilter'

### ISSUE THREAD

**Issue by Csirme** [volkanceylan/Serenity#3495]
**This my data returns：**
`Q.ScriptData.set('Lookup.Business.MintBicycle', new Q.Lookup({"idField":"BicycleGuid","textField":"BicycleNumber"}, 
[{"BicycleGuid":"f2177e0c-86e4-4e6e-86ce-572acafd9d99","BicycleNumber":"6f5433ef5","LockNumber":"6f5433ef5"},{"BicycleGuid":"5089e375-b819-47bb-b861-d798ae3a0f55","BicycleNumber":"7613f7dea","LockNumber":"7613f7dea"},{"BicycleGuid":"c14fb520-fffb-4395-90c4-eba9e562ef79","BicycleNumber":"da95b12ab","LockNumber":"da95b12ab"}]
));`
**This is my column binding：**
`  [EditLink(ItemType = "Business.MintBicycle")]
   [LookupEditor(typeof(Entities.MintBicycleRow)),QuickFilter]
   public String BicBicycleNumber { get; set; }
`
this way only show ‘BicycleNumber’ in options.
**Or use ‘CascadeFrom & CascadeField’**
` [EditLink(ItemType = "Business.MintBicycle")]
 [LookupEditor(typeof(Entities.MintBicycleRow),CascadeFrom = "LockNumber",CascadeField = "LockNumber"),QuickFilter]`

this way show nothing,not matched in options.

How should I display the fields I want in the filter drop-down menu?

**Comment by javaman63** [comment]
You have on your xxxxRow.cs, at the end of that file something like this
```
        IIdField IIdRow.IdField
        {
            get { return Fields.IdReclamo; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.NroReclamo; }
        }
```
The String  Field Is The Field That Will Show The Lookupeditor. If That Field Does Not Serve You
 You Can  Change it, Or you can check the example:

http://serenity.is/demo/BasicSamples/ChangingLookupText

Hope This Help
