### ISSUE TITLE
Create in page controller

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#3497]
I have a page QuickBooksController that executes the code below.
The autoincrement works, the referential integrity etc is checked but the record is not committed and the response or F12 doesn't indicate any errors. If I add a new record from a Serenity grid it works fine.
Can anyone please point me in the right direction for debugging this.

Thanks

using (var connection = SqlConnections.NewByKey("RT5"))
 {
using (var uow = new UnitOfWork(connection))
 {
AccountRow accountRow = new AccountRow();
accountRow.Name = item.DisplayName;
SaveRequest<AccountRow> saveRequestAccount = new SaveRequest<AccountRow>
 {
Entity = accountRow
};
SaveResponse saveResponseAccount = new AccountRepository().Create(uow, saveRequestAccount);

AccountRow
[DisplayName("Account Id"), Column("PKACCTID"), PrimaryKey, NotNull, AutoIncrement, QuickSearch]

**Comment by ga5tan** [comment]
looks good to me. dont u have any exception afterward, which would cancel transaction?
or dont u cancel transaction explicitly?

**Comment by RouteTech** [comment]
I've tried wrapping it it in a try catch block but there are no exceptions and the autoincrement still increments successfully.

**Comment by RouteTech** [comment]
fwiw, i've also tried connection.InsertAndGetID with the same result

**Comment by volkanceylan** [comment]
uow.Commit()

**Comment by RouteTech** [comment]
Thanks that was it. The autoincrement threw me off.
