### ISSUE TITLE
Basic Sample --> 'Custom links in grid' Question

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3498]
In the Custom Link in Grid example, when I click on the Employee, and he lets me edit the order through the OrderDialog, if I change the Ship Via (on the Shipping Tab) , and update it, the grid does not refresh the field Ship Via
Is there any way for the grid to show me the newly added value? (this.refresh() or something like that?)

If I click on the menu, the grid reads and shows me the correct value.

**Comment by ga5tan** [comment]
I think it was discussed here in forum already, did u try to search for it?

**Comment by brunobola** [comment]
@javaman63 that's a pretty basic question, please search or see at least the guide its all there.

**Comment by javaman63** [comment]
Sorry Guys My Bad!

For anyone interested you have to Initialize the dialog, before to load
```

                    var dialog = new Clients.GestionesDialog()
                    this.initDialog(dialog);
                    dialog.loadByIdAndOpenDialog(item.IdGSC);
```
