### ISSUE TITLE
Extend Serenity with AngularJs frontend and Api Backend

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#350]
Hello Volkanceylan,

Serenity being excellent framework

I have few thoughts for extension of the same

what if we have:

1. Pure AngularJs FrontEnd Web Application
2. API Backend Web Application Powered by Serenity Framework
3. JWT Token Authentication Implemented / HMAC Authentication 

Benefits:
Api layer can be reuse further for any Mobile Application Development
pure separation of UI from Service Layer

What is your views on the same?

**Comment by volkanceylan** [comment]
I don't have much experience with Angular, don't know if it fits, or how it can be useful. I have some interest on React, Riot, Mithril, e.g. web components. I like component based, modular, declarative UI more than MVVM. Maybe will go with ASP.NET 5 tag helpers.

Serenity widgets already looks fine on mobile, can be customized with some simple CSS, and dialogs got responsive in recent update.

API layer is already usable in mobile, we use it in Android / IPhone native apps. Actually Serenity is backend for several such apps.

JWT token authentication or any other such requirements can be implemented with ordinary MVC action filters or subclassing ServiceEndpoint.

Serenity already has no UI <-> Service Layer direct dependency. You can take a Serenity web app and implement its UI with WPF for example. I already have working one with WinForms.

**Comment by samdubey** [comment]
Thanks for your comments
