### ISSUE TITLE
Hide [ReadPermission("*")] from menu

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3504]
I gave entity [ReadPermission("*")] in PriceListRow.cs in order to be able to list items on public page.
But now I want to hide this entities being listed in Menu for regular user.
How can I do that. Due [ReadPermission("*")] I get Administration menu with PriceList item no matter what user privileges I set for certain group :(

**Comment by volkanceylan** [comment]
So use a permission, star means all

**Comment by ga5tan** [comment]
@volkanceylan I put star there, so I can list part of price-list on public page (where no user is logged in).
How do I assign privileges to guest/not logged in user?
