### ISSUE TITLE
QuickFilter for Fields in a View

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3505]
Hi, 
I have created a view in the database and used sergen to generate the necessary files. When I add a Quickfilter to a field, it shows a textbox instead of a dropdown.

Is there a way to do this when the database object is a View and not a Table?

**Comment by javaman63** [comment]
You have to put the             [LookupEditor] tag on the field on you xxxxRow.cs
Build  + Transform T4

**Comment by gfo2007** [comment]
@javaman63, thanks for your response but I am not trying to edit. I am trying to filter records in the grid which requires QuickFilter and not LookUpEditor. Or am I missing something?

**Comment by javaman63** [comment]
If you dont tell to serenity where to look the values for the filter...is not going to work

**Comment by gfo2007** [comment]
Ok let me try it and give you feedback @javaman63

**Comment by gfo2007** [comment]
Thanks @javaman63. Your suggestion worked.

**Comment by stixoffire** [comment]
@gfo2007 I have a view that includes the name field for one of my  tables Order .. I use the lookupeditor on  MyViewRow.cs  Property for example OrderNumber. I get the data in the dropdown but SlickGrid is not filtering the grid like it should.

 Is there anything different than the below that you did - did you include the primary key value in your view?

```
ViewOrderDetailsRow()
{
[LookupEditor(typeof(OrderRow))]
OrderNumber  {get;set;}
}

OrderRow()
{
//primary key autoincrement
Id {get;set;}
// name field
OrderNumber {get;set;}


```
