### ISSUE TITLE
Calendar question

### ISSUE THREAD

**Issue by JonesyBoy** [volkanceylan/Serenity#3506]
Hi,
I'm looking for a code generation tool that has a calendar/scheduler something like Kendo UI https://demos.telerik.com/kendo-ui/scheduler/date-grouping
The Serenity demo calendar does not show how an event is edited or added. 
Can a calendar event be edited by clicking the event?
Can an event be generated from clicking a date?
Can the information appearing on a calendar be extended from database fields?
Can a tool tip showing extended data be used?
Thank You,
JonesyBoy

**Comment by JohnRanger** [comment]
Hi @JonesyBoy ,

the dashboard widgets are all non-functional within Serene. This is more or less a 1:1 copy of AdminLTE.

If you want calendar event functionality - you will have to program this yourself.

With kind regards,

John
