### ISSUE TITLE
Using a LookupEditor in Direct Entry in a Grid

### ISSUE THREAD

**Issue by Doomisateur** [volkanceylan/Serenity#3508]
Hello, I wanted to use a **LookupEditor** drop-down list to make direct entry in a grid. In the demo, on the product screen, there are examples of drop-down lists, but they are just fixed lists of type Select2Editor.

Volkan had already answered this question in another post saying that this is not possible in the current version of Serenity. After much research, I confirm that it is impossible.

However, I absolutely wanted to use a LookupEditor and founded how to do it. _Attention, to get there, I had to modify basic classes of Serenity_. This post is for sharing this find for those who are interested in this use.

To get there, modify the following files ...

**Modify the file /Scripts/SlickGrid/slick.grid.js** _(remember to save this file before making any changes and it will be overwritten if you update the Serenity version)_

```
function render() {
   ...
   trigger(self.onRender, { grid: self });
}

```
```
$.extend(this, {
   "slickGridVersion": "2.1",

   // Events
   ...
   "onRender": new Slick.Event(),

```

**Modify the file /Scripts/typings/serenity/Serenity.CoreLib.d.ts** _(remember to save this file before making any changes and it will be overwritten if you update the Serenity version)_

```
interface Grid {
   ...
   onRender?: Slick.Event;
}

```

_These changes will add a new event to each render in the grid._

**Example of adding a LookupEditor in direct entry in a grid (in xxxEditor.ts for an entry in a master-detail grid)**

```
...
constructor(container: JQuery) {
   ...
   this.slickGrid.onRender.subscribe(() => {
      this.liaisonEditeurs();
   }
}

private liaisonEditeurs() {
   var laLignes = this.view.getItems();
   for (let lnCpt in laLignes) {
      this.liaisonEditeur(lnCpt, laLignes);
   }
}

private liaisonEditeur(pnIndex: string, paLignes: trs_CtcTelRow[]) {
   if (!$("#CtcTelIdf" + pnIndex).hasClass("select2-offscreen")) {
      var loEditeur = new Tables.TabIdfListeEditor($("#CtcTelIdf" + pnIndex));
      loEditeur.value = Q.toId(paLignes[pnIndex].CtctelIdfFk);
      loEditeur.changeSelect2(e => {
         paLignes[pnIndex].CtctelIdfFk = Q.toId(loEditeur.value);
      });
   }
}

protected getColumns() {
   var laColonnes = super.getColumns();

   var loCtcTelIdf = Q.first(laColonnes, x => x.field === fld.CtctelIdfFkIdf);
   loCtcTelIdf.referenceFields = [fld.CtctelIdfFk];
   loCtcTelIdf.format = ctx => { return '<input type="hidden" id="CtcTelIdf' + ctx.row + '" title="Indicatif" />'; };

   return laColonnes;
}

```

It works very well for me, I hope it will help you. Perhaps this could be a suggestion for adding it to a future version of Serenity.

**Comment by Doomisateur** [comment]
I think on the same way you can use a DateEditor or DateTimeEditor...

Here an example of the dialog with the LookupEditors :

![image](https://user-images.githubusercontent.com/17436539/39249143-4086c73c-489e-11e8-82a1-0bf74ac74df8.png)

**Comment by JohnRanger** [comment]
Hi @Doomisateur ,

merci beaucoup pour l'information :-) This would make up a good Wiki entry. May I kindly ask that you also put this into the wiki? (It's easier to find there than within the solved issues).

Thanks again for the info and

with kind regards,

John

**Comment by Doomisateur** [comment]
With pleasure, I created a page in the wiki visible at this address: https://github.com/volkanceylan/Serenity/wiki/Using-a-LookupEditor-in-direct-entry-in-a-Grid

I added some comments (in english, sorry if bad translation) in my code to make it more readable for everyone.

**Comment by dfaruque** [comment]
@Doomisateur  Thanks for your work.
It will be even better if you give some screenshots on the wiki page

**Comment by Doomisateur** [comment]
@dfaruque Done ! ;)

**Comment by reach2rv** [comment]
Hi @Doomisateur @dfaruque  any idea how I cam make this grid editor readonly if entity is in view mode

**Comment by Doomisateur** [comment]
Hi @reach2rv,

I suppose you can do that with Serenity.EditorUtils.setReadOnly(...).

Be careful, you have setReadonly and setReadOnly. The first one is for a JQuery component and the second (with the o uppercase) is for a widget.

Example :
Serenity.EditorUtils.setReadOnly(this.form.myFieldLookup, true);
The second parameter is a boolean, true to readonly, else false.

**Comment by reach2rv** [comment]
@Doomisateur hey thanks for quick reply.. I am able to achieve it using serenity extra by @dfaruque.. thanks again for this great tutorial saved my time n efforts..

**Comment by Doomisateur** [comment]
You're welcome
