### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#351]
when ever i page or sort i get this error
{"Incorrect syntax near 'OFFSET'.\r\nInvalid usage of the option NEXT in the FETCH statement."}

![paging error](https://cloud.githubusercontent.com/assets/728937/13463841/d47b3fda-e096-11e5-94e9-f5d75cc23b1b.png)
any Idea
Update: if i do paging first then sort it show the exception

**Comment by volkanceylan** [comment]
Your sql dialect is 2012 set it to 2005, see guide for info

**Comment by zerodev** [comment]
thanks, will try it , do you think i will have  any issues with SQL 2014

**Comment by volkanceylan** [comment]
No you shouldn't have problems with 2012 or 2014. You get this error with one of them??

**Comment by zerodev** [comment]
i have 2 pc's one with 2008 and the other with 2014 , seams i missed the settings for dialect  working like charm on 2014
