### ISSUE TITLE
import invoice xml

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3510]
Hello everyone,
How do I import the xml file from an invoice into Serenity? and then update the product table.
Does anyone have an example?
Thankful,

**Comment by Doomisateur** [comment]
Hi,

In the demo of Serenity (StarSharp or Serene) : http://serenity.is/demo/BasicSamples/ProductExcelImport
In these files :
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ProductExcelImport/ProductExcelImportDialog.ts
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ProductExcelImport/ProductExcelImportEndpoint.cs
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ProductExcelImport/ProductExcelImportGrid.ts
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ProductExcelImport/SampleProductList.xlsx
