### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#3513]
Hi @volkanceylan 
I understand that there is a wizard in the StartSharp project, if so which one did you use. I'd like to be consistent. Previously you suggested
https://github.com/rstaib/jquery-steps
https://github.com/VinceG/twitter-bootstrap-wizard

Thanks

**Comment by brunobola** [comment]
@RouteTech I'm pretty sure you are the one that have to make that choice according to your needs.

**Comment by RouteTech** [comment]
@brunobola I get that, if I do decide to use StartSharp I don't want two and it's also nice to know which one is working without issues.

**Comment by volkanceylan** [comment]
None, its a custom widget

**Comment by RouteTech** [comment]
Ok.
Thanks
