### ISSUE TITLE
Using Multiple fields For LookupEditor text

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3516]
Hi,
Please if I have an Item object, and I want to show both ItemNo and ItemName as the text in the LookupEditor, how can I do this?

**Comment by dfaruque** [comment]
use `[Expression("T0.ItemNo + ' ' + T0.ItemName")]`

**Comment by dfaruque** [comment]
sorry for the late reply 
I am referring to ItemRow

**Comment by Mohamed-Ali-Salim** [comment]
dear all
this is my code
`[DisplayName("Application"), Column("ApplicationID"), ForeignKey("[dbo].[SEC_Applications]", "ID"), LeftJoin("jApplication"), TextualField("ApplicationApplicationCode")]
        [LookupEditor(typeof(SecApplicationsRow))]
        [Category("Use by Application")]
        [Expression("ApplicationCode + ' ' + ApplicationNameAr")]
        public Int32? ApplicationId
        {
            get { return Fields.ApplicationId[this]; }
            set { Fields.ApplicationId[this] = value; }
        }`

and this is the error msg
Conversion failed when converting the nvarchar value '1 تخطيط الموارد والمؤسسات' to data type int

please help

**Comment by VictorTomaili** [comment]
@Mohamed-Ali-Salim please use [discussions](https://github.com/serenity-is/Serenity/discussions) for new questions.
