### ISSUE TITLE
How to inject my "DAL layer" without big change in serenity

### ISSUE THREAD

**Issue by loringao** [volkanceylan/Serenity#3518]
I have a rich-client project(WPF), now I want create a web site to access my original system without change my server site code, Is it possible to do that in serenity?

Client side UI (WPF, User.xaml, UserControl.cs .....)   //Here is where I want to replace with serenity
Client side Framework( UserClient.cs)
Server side Application Service(UserAppservice.cs)
Server side Domain(UserDomain.cs)
Server side Repository(hibernate)

It looks similar to serenity architect, now I want to reuse serenity's row, repository, controller and all things, seems the inject point is ServiceEndpoint or repository.

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            //return new MyRepository().Create(uow, request);            
             UserClient uc = UseClientManger.CreateUser(request.xxxxxxx)
             var userRow = TransferToViewModel(uc)
             return new SaveResponse(userRow)
       }
The problem is serenity always inject unit of work, in my project, web is only a client, no transaction and database. ignore it or remove the parameter? is there any other place to inject my "DAL layer"?

**Comment by samdubey** [comment]
Yes it is possible, we have done it for more than 3 WPF application

**Comment by loringao** [comment]
@samdubey, if you do not mind，could you 
introduce your way? do we have to remove the uow parameter?

**Comment by ga5tan** [comment]
do not use Serenity's CRUD, just call your services to do the job...
or better yet, for trivial CRUD use Serenity, for you legacy code just call it as webservice.

**Comment by loringao** [comment]
@ga5tan ,thank you
