### ISSUE TITLE
INameRow doubt..

### ISSUE THREAD

**Issue by mloro** [volkanceylan/Serenity#3519]
Hi all, i have one question..
I have one foreign key to another table and i just want to show in the dropdown all the values of the id key and now it shows like that:

![imagen](https://user-images.githubusercontent.com/25487918/39399708-1455e0f0-4af9-11e8-8701-2d32ffc7a0fc.png)

I know that the issue is because i have no field related to the INameRow.NameField , but i do not use that because it requires an StringField, and the value i just want to show is a Int32Field.

Is it possible to use the same value for INameRow.NameField and IIdRow.IdField ??

If it's not clear, please tell me so i can explain better.

Thanks..

**Comment by dfaruque** [comment]
You may try to add a string expression field and use that as NameField
```
        [Expression("(T0.Id)")]
        public String LookupText { get { return Fields.LookupText[this]; } set { Fields.LookupText[this] = value; } }
```
