### ISSUE TITLE
page open with query string to filter grid

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#352]
what is required to open a page with its grid filtered based on query string

**Comment by volkanceylan** [comment]
see how i list open/closed orders when you click more info from dashboard

**Comment by zerodev** [comment]
so i only need to pass the property name like "shippingState" in the query string? no other constrains

**Comment by volkanceylan** [comment]
no see how i implement that in OrderPage.cshtml, OrderGrid.cs etc

**Comment by zerodev** [comment]
You mean OrderIndex.cshtml and the 
` var q = Q.parseQueryString();
        if (q.shippingState != null && q.shippingState.length) {
            orderGrid.set_shippingState(parseInt(q.shippingState, 10));
        }`

if yes i have to add the filter to the grid class and implement this JS
