### ISSUE TITLE
Did Meeting&Organization modules be removed?

### ISSUE THREAD

**Issue by Just1n** [volkanceylan/Serenity#3521]
I have done all the steps according to the serenity-guide.
However I can't see Meeting&Organization modules been displayed in the Creating-Project-Selection-Dialog.
See:
![image](https://user-images.githubusercontent.com/517376/39408384-e5befca8-4c07-11e8-8ca4-95efaf948925.png)

Did the Meeting&Organization modules be removed by design?

All the required environments versions are newest.

**Comment by kilroyFR** [comment]
i think they are available in startsharp only right now

**Comment by Just1n** [comment]
@kilroyFR So do you mean that they are not available for the VS extension?

**Comment by volkanceylan** [comment]
Yes, that's not in Serene
