### ISSUE TITLE
Questions about the framework...

### ISSUE THREAD

**Issue by avifatal** [volkanceylan/Serenity#3522]
Hi,
I'm evaluating the framework for my company before buying a license.
I have few questions if I may...

1. I some cases, you want to control the form HTML. 
   Can I override the form and write it in HTML / typescript. But still, benefit from the framework form fields. So let's say just as an example I want a different layout of the form. 10 fields in parallel...
   I assume that eventually some piece of code in the framework is looping the form definition and display it.
   So I want to break that apart and write the HTML myself and maybe reuse the form fields.
   Is it possible?

2. Row Level security, Looking at the ORM I assume that it is not supported out of the box. Correct?
   Did someone manage to implement it in the framework?

3. Can I replace the ORM to something with Linq support such as NHibernate? if so, what are the pros and cons? and how to do that?

Thanks

**Comment by avifatal** [comment]
I know you are pushing me to buy a license (-: which is ok.
But I want to run some tests, Licenses for my developers is after I have managed to accomplish that.
Can you point me to some resources to start and create it?
Thanks

**Comment by volkanceylan** [comment]
First of all, he is not pushing you as he is just a community member, not a company representative. 

It is possible to use custom HTML and create Serenity widgets inside that. There are some samples in demo. Also StartSharp contains React integration for Serenity widgets.

Multi tenancy is a sample for row level security, i recommend you should add the guide to your evaluation.

You may use any ORM you like, but Serenity won't be using your ORM, so you won't be getting any advantages of Serenity.
