### ISSUE TITLE
Cascading with more than one condition

### ISSUE THREAD

**Issue by masudijames** [volkanceylan/Serenity#3523]
Hi there,
The  cascading used in  serenity guide use COUNTRY and City example use something like
SELECT CITY WHERE COUNTRYID=X 
How to achieve cascading with two conditions 
SELECT CITY WHERE COUNTRYID=X && POPULATION<10000

**Comment by brunobola** [comment]
You can do it from several ways, personally I like to make lookup editors and overriding the get_items...

**Comment by masudijames** [comment]
Thanks, Can you show me an example or link to similar question

**Comment by masudijames** [comment]
I create a lookup.cs file and used prepare query, instead of **xx** below I need form value like **this.form.myfield**

 query.Distinct(true)
                .Select(fld.MyFieldName)
                .Where(
                    new Criteria(fld.MyFieldId) ==**xx** );

**Comment by mafdy** [comment]
there's an example on creating custom editor, here it's 




>     Create Type Script file with the following and change the variable with yours:
     @Serenity.Decorators.registerEditor()    
     export class ProduceSeafoodCategoryEditor extends
        Serenity.LookupEditorBase<Serenity.LookupEditorOptions, Northwind.CategoryRow> {

        constructor(container: JQuery, opt: Serenity.LookupEditorOptions) {
            super(container, opt);
        }
        protected getLookupKey() {
            return Northwind.CategoryRow.lookupKey;
        }
        protected getItems(lookup: Q.Lookup<Northwind.CategoryRow>) {
            return super.getItems(lookup).filter(x =>
                x.CategoryName === 'Produce' || x.CategoryName === 'Seafood');
        }
    }
