### ISSUE TITLE
Can you prevent rows from being deleted?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#353]
I there a way to disable the delete button or prevent users from deleting the row?

**Comment by sayuga** [comment]
See the Loggingrow features implemented in the Users table in the Northwind sample. 

You are looking for the information on IIsActiveDeletedRow and IDeleteLogRow.

**Comment by volkanceylan** [comment]
Override UpdateInterface and deleteButton.Hide()

**Comment by swordz36** [comment]
Great! I was able to override UpdateInteface in the Dialog class and that removed the button from he dialog

**Comment by volkanceylan** [comment]
Note that this won't prevent them from calling service ;)

**Comment by swordz36** [comment]
I assuming that the only to make a call to the service is by using the delete  button on the UI, is that not correct?

**Comment by jsbUSMC** [comment]
Using the browser console the user could make a call to the service and it would execute server side. This is why you have to alter the service behaviors to prevent something like this.

**Comment by c9482** [comment]
How about hiding the other 2 save buttons?

**Comment by volkanceylan** [comment]
They are saveButton and applyChangesButton .

**Comment by c9482** [comment]
They do not see to be valid properties in the context of EntityDialog. The deleteButton is valid but saveButton and applyChangesButton are not. I must be missing something.

**Comment by volkanceylan** [comment]
applyChangesButton is certain. saveButton is wrong but saveAndCloseButton you could see easily by intellisense.

**Comment by c9482** [comment]
Got it. Thanks.
