### ISSUE TITLE
Enable/Disable button on toolbar (xyzGrid.ts)

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3530]
hey all, i would like to enable a button on my toolbar (xyzGrid.ts) if a row is selected.

I call a service to get a parameter: 

```
      buttons.push({
        title: 'Edit Parameter',
        cssClass: 'edit-permissions-button',
        onClick: () => {
          $(location).attr('href', '/Referential');
        },
        separator: true
      });

      MyService.IsEditEnabled(
        {},
        response => {
          if (response.Id != 0) {
            this.toolbar.findButton('edit-permissions-button').show();
          }
          else
            this.toolbar.findButton('edit-permissions-button').hide();
        });
```

So far it does not work. 

How is it possible to refresh display of Grid dynamically (display/hide) button ?
Do i have to access directly using jquery ?

**Comment by kilroyFR** [comment]
I tried using : 

`buttons.splice(Q.indexOf(buttons, x => x.cssClass == "edit-permissions-button"), 1); `

to hide button but it is still visible.

I checked the buttons and the button is not listed (but still displayed)
Looks like a problem of display refreshing ?

is there a this.refresh() or something to get buttons updated ?

**Comment by JohnRanger** [comment]
Hi @kilroyFR 
for me - in general the hiding of a button with your method of finding an hiding the button works fine.

I believe that your problem ist the scope of "this" when you do a this.toolbar.findbutton... as you are within the scope of the callback and not of your typescript "root".

With kind regards,

John
