### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Poojapusunuri** [volkanceylan/Serenity#3531]
Created a student  form, I want to display particular student details after login, but its displaying all Records for every student
Please help me with this
Here are the details of my code
 first I have added student in UserTable

StudentPermissionKeys
![permissionkeys](https://user-images.githubusercontent.com/36690954/39571858-8d864d62-4eea-11e8-8fc9-fe5242b527a5.png)

StudentRow
![studentrow](https://user-images.githubusercontent.com/36690954/39571850-88bd276a-4eea-11e8-97e3-a91c28a815a2.png)

 StudentId property in UserDefinition
![userdefinition](https://user-images.githubusercontent.com/36690954/39571844-82163fd2-4eea-11e8-8db6-849c96842bff.png)

UserRetrieveService.cs
![userretriveservice](https://user-images.githubusercontent.com/36690954/39571839-7af75628-4eea-11e8-9f57-13338b953eac.png)

UserRepository
![userrepository](https://user-images.githubusercontent.com/36690954/39571830-734cb058-4eea-11e8-867f-1862690ef5d7.png)

UserDialog
![userdialog](https://user-images.githubusercontent.com/36690954/39571821-68afa01a-4eea-11e8-90c0-f4f65ddefb85.png)

**Comment by kilroyFR** [comment]
did you check if permission "Student:Students" is same as Student.PermisionKeys.Students ?

**Comment by Poojapusunuri** [comment]
Yeah both are same

**Comment by Poojapusunuri** [comment]
![usd1](https://user-images.githubusercontent.com/36690954/39573250-0e8ef56c-4ef0-11e8-8731-726fb69bbc30.png)

**Comment by ga5tan** [comment]
just try to filter it without permission first, to see if u got that running

**Comment by ga5tan** [comment]
anyway, I just used similar filtering in Behaviour and it work like a charm (MultiTenancy Tutorial)
