### ISSUE TITLE
New custom dialog.

### ISSUE THREAD

**Issue by mloro** [volkanceylan/Serenity#3532]
Hi all, im new to serenity and i have a doubt about dialogs.

First, i use that code to create a new button that opens a new dialog:
'protected getButtons() {

            // preserving default New Item button
            var buttons = super.getButtons();
            buttons.push({
                title: 'Devolución',
                cssClass: 'add-button',
                onClick: () => {
                    // using EditItem method as a shortcut to create a new Reserve dialog,
                    // bind to its events, load our reserve row, and open dialog
                    this.editItem(<Default.ReservasRow>{
                        //FechaDevoluciónReal: Q.formatDate(new Date(), 'yyyy-MM-dd'),
                      
                    });
                }
            });'

It works fine but it shows all the fields from my ReserveRow class but its not what i want..
I just want to know if its possible to create a new dialog with custom fields and when i save i just want to call my  Update method from my ReserveEndpoint.. 
It's possible? Can anyone give me an advice on how to do it or an example ?

Thanks, if its not clear , please tell me ..

**Comment by ga5tan** [comment]
You can make custom form, just make custom selection of fields in xyzForm.cs

and you can call Service function from you button (in this case save()) like this (for example):
(in this case I send two entities to service for saving both and couple of more are generated as well)

` // This is called when save/update button is pressed
        protected save(callback: (response: Serenity.SaveResponse) => void) {            

            if (!this.validateForm()) {
                return;
            }

            if (!this.paymentValidator.form()) {
                return false;
            }
            
            //get data from grids into Rows
            var p = <Payment.UserPaymentRow>{};
            this.paymentPropertyGrid.save(p);            

            var u = <Events.UsersRow>{};
            this.propertyGrid.save(u);
            u.EventName = this.form.SeminarID.text;                      

            Q.serviceCall({
                url: Q.resolveUrl('~/Services/Payment/RegisterUser'),
                request: {
                    PaymentRow: p,
                    UserRow: u
                },
                onSuccess: response => {
                    Q.information(Q.text('Forms.Events.EventRegistration.RegisteredSuccess') + "\r\n" + (<Common.PaymentResponse>response).sOutput , () => {
                        window.location.href = Q.resolveUrl('~/Account/Login');
                    });
                }
               
                                
            });
           
        }`

**Comment by mloro** [comment]
Thanks @ga5tan but i have one doubt, when you said "You can make custom form, just make custom selection of fields in xyzForm.cs", you reffers that i should create another xyzForm.cs in the same folder where i have my default form? , but then how i should call the new form from my grid when i click the new button, with that like you do ?? :
if (!this.validateForm()) {
            return;
        }

        if (!this.paymentValidator.form()) {
            return false;
        }

Sorry if my questions are so basic, but im new here and it costs me a bit to understand the behavoiur..
Thanks..

**Comment by ga5tan** [comment]
just customize default form then!
yeah, u can have multiple forms for one row. there is even tutorial for that:
https://github.com/volkanceylan/Serenity/wiki/Create-another-form-of-the-same-Sergen-generated-table

may be good for what u want?

**Comment by mloro** [comment]
I'll take a look at that, i thinks its what i want!
Thank you so much for your help and patience!
If i have another question i'll search in the wiki o ask here again..

Thanks!

**Comment by FGLedesma** [comment]
Hi, the link "https://github.com/volkanceylan/Serenity/wiki/Create-another-form-of-the-same-Sergen-generated-table" doesn't show a tutorial but a blank page suggesting the creation of a new one.
has being moved maybe? ... Can you update this thread with the correct link so it is really useful. Thanks a lot.

**Comment by ga5tan** [comment]
https://github.com/volkanceylan/Serenity/wiki/Forms:-Create-another-form-of-the-same-Sergen-generated-table

**Comment by FGLedesma** [comment]
Hey ga5tan, Really appreciate it. You rock.
