### ISSUE TITLE
Error in ServerTypings.tt and ClientTypes.tt

### ISSUE THREAD

**Issue by mloro** [volkanceylan/Serenity#3533]
I just created a new formatter attribute and when i try to run my t4 templates i got 2 errors in the followings files:

### ServerTypings.tt:
Error	 Ejecutando transformación: MsieJavaScriptEngine.JsRuntimeException: Compile error: Error de sintaxis
   en MsieJavaScriptEngine.JsRt.Ie.ChakraIeJsRtJsEngine.InvokeScript[T](Func`1 func)
   en MsieJavaScriptEngine.JsRt.Ie.ChakraIeJsRtJsEngine.Execute(String code)
   en MsieJavaScriptEngine.MsieJsEngine.Execute(String code)
   en Microsoft.VisualStudio.TextTemplating18736F7ECAFFB868B703D951CC71E6422C26D8C0915BC70F756355BBD9BCC3EA88C7B750DCB7052568E97634CEE36AD92A975F8457C3D29131B4B399ACCBE8C6.GeneratedTextTransformation.TSTypeLister.List()
   en Microsoft.VisualStudio.TextTemplating18736F7ECAFFB868B703D951CC71E6422C26D8C0915BC70F756355BBD9BCC3EA88C7B750DCB7052568E97634CEE36AD92A975F8457C3D29131B4B399ACCBE8C6.GeneratedTextTransformation.TransformText()	BibliotecaWebIces.Web	C:\Users\mloro\Documents\bibliotecaicesweb\BibliotecaWebIces\BibliotecaWebIces\BibliotecaWebIces.Web\Imports\ServerTypings\ServerTypings.tt  1

### And other in ClientTypes.tt:
 Error		Ejecutando transformación: MsieJavaScriptEngine.JsRuntimeException: Compile error: Error de sintaxis
   en MsieJavaScriptEngine.JsRt.Ie.ChakraIeJsRtJsEngine.InvokeScript[T](Func`1 func)
   en MsieJavaScriptEngine.JsRt.Ie.ChakraIeJsRtJsEngine.Execute(String code)
   en MsieJavaScriptEngine.MsieJsEngine.Execute(String code)
   en Microsoft.VisualStudio.TextTemplatingA1E694B29897AD37C9D403584EE8128DEB2ED9DECE76FF816EA207667B01A4E57CD9F33F50F1BFF42B8534EEA5D1A8E59E27A68390D2214DACE6813EA882FEC9.GeneratedTextTransformation.TSTypeLister.List()
   en Microsoft.VisualStudio.TextTemplatingA1E694B29897AD37C9D403584EE8128DEB2ED9DECE76FF816EA207667B01A4E57CD9F33F50F1BFF42B8534EEA5D1A8E59E27A68390D2214DACE6813EA882FEC9.GeneratedTextTransformation.TransformText()	BibliotecaWebIces.Web	C:\Users\mloro\Documents\bibliotecaicesweb\BibliotecaWebIces\BibliotecaWebIces\BibliotecaWebIces.Web\Imports\ClientTypes\ClientTypes.tt	1	

Any advice on how to fix it?
Thanks..

**Comment by volkanceylan** [comment]
It says syntax error, remove formatter try again, add formatter and check for syntax errors.

**Comment by mloro** [comment]
I tried but the error continues..
Im going to update my java version and see what happens.

Thanks
