### ISSUE TITLE
why select2 delete icon disappear

### ISSUE THREAD

**Issue by gyygyy32** [volkanceylan/Serenity#3534]
I use select2 3.5.1 that serenity provide .I already set allowClear: true. code as below

        $('#ddlDate').html(strDDL);
        $('#ddlDate').val('');
        $('#ddlDate').select2({
            allowClear: true,
            placeholder: "Select an attribute"
        });

**Comment by gyygyy32** [comment]
![00](https://user-images.githubusercontent.com/5733435/39642310-ecfba156-5003-11e8-8600-98c0af3dcb84.jpg)

**Comment by volkanceylan** [comment]
Sorry, that's a select2 widget / javascript question
