### ISSUE TITLE
Hide QuickFilter

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3537]
hi
is it possible somehow to hide filtering lookups based on permissions?

**Comment by wldkrd1** [comment]
Absolutely! The .ts files defining the Grid or Dialog have access to the Authorization.hasPermission() method. Use the result of that call to decide whether to add your lookup.

**Comment by ga5tan** [comment]
Got it:

`

protected getQuickFilters() {

            var filters = super.getQuickFilters();
        
            if (!Authorization.hasPermission("IDI:Roles:UnfilteredRows")) {
                filters.splice(Q.indexOf(filters, x => x.field == "PaidBy"), 1);
                filters.splice(Q.indexOf(filters, x => x.field == "BillTo"), 1);
            }
            return filters;

        }

`
