### ISSUE TITLE
What can be the cause for following

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#3538]
Following is the error:
The asynchronous action method '' returns a Task, which cannot be executed synchronously.

Server Side in ServiceEndoint:
 [HttpPost]
 public async Task<ActionResult> SomeAction(SomeRequest request)
 {
//
return Json(response, JsonRequestBehavior.AllowGet);
}

In Grid file:
buttons.push({
                title: 'SomeAction',
                cssClass: 'send-button',
                
                onClick: () => {
                     ContactsService.SomeAction({
                        Ids: this.rowSelection.getSelectedKeys()
                    },
                        response => {
                            if (response == "Success") {
                                this.rowSelection.resetCheckedAndRefresh();
                                Q.information('Added Successfully', () => { Q.resolveUrl('#'); });
                            }
                            else {

                                Q.alert('Error');
                            }
                        },
                        { async: true } //Even tried with false
                    );
                }
            });

**Comment by volkanceylan** [comment]
Why don't you use a normal service endpoint method with retrieveresponse

**Comment by vinaykulkarni89** [comment]
Actually using a NuGet package which has all methods which execute in async

**Comment by volkanceylan** [comment]
You may use Task.Run(() => SomeMethod).Result to execute any async method synchronusly

**Comment by vinaykulkarni89** [comment]
Used NuGet to accomplish the task
