### ISSUE TITLE
FilterField and FilterValue

### ISSUE THREAD

**Issue by MagDev175** [volkanceylan/Serenity#3539]
I have a filter field and value set up on the LookupEditor of the row class: 
[LookupEditor(typeof(AccountsRow), FilterField = "IsInvestorAccount", FilterValue = 0)]

The field is included in the lookup on the AccountsRow page but it will not filter in the form drop down.  I see it selecting the IsInvestorAccount field when I click on the drop down but it doesn't filter it. Can someone help with what I'm doing wrong?

**Comment by mloro** [comment]
Maybe you missed to put LookupInclude on your IsInvestorAccount field  in AccountsRow ..

**Comment by MagDev175** [comment]
I have LookupInclude.  I can see the field included in a sql trace.  It just doesn't filter by the field.

**Comment by MagDev175** [comment]
I don't understand what you mean.  It's a drop down.  It has values when I click on it.  They just are not filtered.

**Comment by ga5tan** [comment]
do you want to have distinct values in filter, or filter them out as u filter?
or, when u pick up one value in filter, it wont filter down the grid?

**Comment by leahmayschneider** [comment]
There is a lookup on a field.  I would like that lookup filtered based on the value of another column.  It is not filtered.

**Comment by ga5tan** [comment]
@leahmayschneider is this thread hijacking or what?
anyway, what u want is lookup cascading. check out samples in orders (Country, City)

**Comment by MagDev175** [comment]
@ga5tan I'm sorry I logged in on my other account.  

I do not want cascading.  I want the values in the lookup to be filtered by a preset value (in this case always 0), not based on the value of another lookup.  I want FilterValue and FilterField.

**Comment by volkanceylan** [comment]
Try with some value other than zero

**Comment by MagDev175** [comment]
It does work with a value other than 0 but this doesn't help me filter on the value 0.

**Comment by volkanceylan** [comment]
Can't reproduce this, 0 is working fine as a filter value.

**Comment by Shraddha996** [comment]
hey everyone!
My question is can we add Not EqualsTo term for FilteraValue?
Because I want  my dropdown should be Filtered all value except one

**Comment by stixoffire** [comment]
@MagDev175  Your Database is storing that data as boolean or Integer ? , try using false for your filter value and see if that works for you .

**Comment by MagDev175** [comment]
@stixoffire It's been awhile since I've looked at this since I found a workaround but I generally have better luck with filtering on 0/1 as opposed to false/true.

**Comment by stixoffire** [comment]
@MagDev175 Yes I prefer 0/1 integer values as it is easier to migrate to 0/1/2 , in my case I had my db as I preferred integers, but in my code as my brain logic is boolean  .. so the code was written for boolean and it just did not like to filter (which brought me here) and then the Homer DOH!.. which got me working. I changed DB to bit and used true/false it worked correctly. I am thinking integer would have been fine if my datatypes matched.

**Comment by Mohamed-Ali-Salim** [comment]
@MagDev175 
Did you find the solution ?
I'm in the same problem now

**Comment by MagDev175** [comment]
@Mohamed-Ali-Salim  I'm sorry it was so long ago and I no longer remember. I don't have that code snippet in my code any more so I'm guessing I couldn't find a solution. I almost definitely set the filter in the grid or dialog ts class.
