### ISSUE TITLE
site.less (or maybe site.mixins.less) unable to be compiled

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#354]
I upgraded this morning from 1.9.15 -> 1.9.17, now project fails to build, complaining about transforming site.less into site.css

2>Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
2>  "C:\ServerReview.Web\tools\node\lessc.cmd" "C:\ServerReview.Web\Content\site\site.less" > "C:\ServerReview.Web\Content\site\site.css" (TaskId:89)
2>  [31mnon_object_property_loadError: Cannot read property 'Call' of undefined[39m[31m in [39mC:\tfs\Applications\ServerReview\ServerReview\ServerReview.Web\Content\site\site.less[90m on line null, column 0:[39m (TaskId:89)
2>  [90m1 @import "site.mixins.less";[39m[0m[0m (TaskId:89)
2>   (TaskId:89)

Reverting back to 1.9.15 isn't fixing it, so I suspect the upgrade isn't the issue. Any ideas what I should be looking at to figure out what's causing the .less file to have a problem?

**Comment by volkanceylan** [comment]
Looks like something wrong with your less compiler under tools\Node\less

Can you try clearing site.less and writing very simple css

dummy { color: white; }

for example

**Comment by wldkrd1** [comment]
That gives me this:
Task "Exec" (TaskId:35)
1>  Task Parameter:Command="C:\ServerReview.Web\tools\node\lessc.cmd" "C:\ServerReview.Web\Content\site\site.less" > "C:\ServerReview.Web\Content\site\site.css" (TaskId:35)
1>  "C:\ServerReview.Web\tools\node\lessc.cmd" "C:\ServerReview.Web\Content\site\site.less" > "C:\ServerReview.Web\Content\site\site.css" (TaskId:35)
1>  [31mnon_object_property_loadError: Cannot read property 'Definition' of undefined[39m[31m in [39mC:\ServerReview.Web\Content\site\site.less[90m on line null, column 0:[39m (TaskId:35)
1>  [90m1 [39m[0m[0m (TaskId:35)
1>   (TaskId:35)

**Comment by wldkrd1** [comment]
Hmm...ServerReview.Web\tools\Node\less\lib\less\tree\mixins.js is 0 bytes...could that be the problem?

**Comment by wldkrd1** [comment]
Yup, that was it....I think the upgrade somehow borked that file. Good luck reproducing that, though...

**Comment by volkanceylan** [comment]
Save congrats for NuGet ;)
