### ISSUE TITLE
Advanced Samples

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#3546]
Good Day

I want to have advanced sample on my project so I can access E-mail Client (IMAP) functionality. This functionality works perfectly on the demo site, however I want to include this on my project, how do I go about doing this because when I create a new project I only have access to the following modules i.e. Basic Samples, Northwind, Theme Samples(AdminLTE)  and not Advanced samples

**Comment by sshandu** [comment]
This is the below screen shot that I get when creating a new project

Must serenity be updated? or is there another way for me to get advanced
samples module?

**Comment by ga5tan** [comment]
Obviously, license is perpetual and u can use functionality permanently. You just loose updates after one year support if you don't extend it.
Maybe you can contact product owner (@volkanceylan ) to get "special treatment" but I don't suppose there is much room for deal cutting at such reasonable price points...

**Comment by sshandu** [comment]
ngiyabonga mfwethu 😁

**Comment by sshandu** [comment]
So since my project is currently on serene in terms of migrating to the
startup template will I get support or assistance in doing this? or is
migrating easier to do?
