### ISSUE TITLE
Unable to subclass Common.GridEditorDialog

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3548]
I was trying to subclass 'Common.GridEditorDialog' to be able to have common MakeReadOnly functionality like I did with 'Serenity.EntityDialog'
but for some reason it is not possible.
any ideas why?

`namespace MyTest {
    @Serenity.Decorators.registerClass()
    export class MyGridEditorDialog<TEntity> extends Common.GridEditorDialog<TEntity> {

        protected MakeReadOnly(bHide: boolean) {      
            if (!this.isNew()) {
                if (bHide) {
                    Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);
                    this.element.find('sup').hide();
                    this.deleteButton.hide();
                    this.saveAndCloseButton.hide();
                    this.applyChangesButton.hide();
                }
            }
        }
    }
}`

**Comment by dfaruque** [comment]
What problem you have actually?
Any error?

**Comment by ga5tan** [comment]
@dfaruque - Yeah, big bad red errors:
Message: Object doesn't support this action
File: http://localhost:53312/Scripts/jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg2, Line: 3827, Column: 3

SCRIPT ERROR! See browser console (F12) for details.
Message: Unable to get property 'prototype' of undefined or null reference
File: http://localhost:53312/Scripts/serenity/Serenity.CoreLib.js?v=4DMOWnm4a2N3HOKpnMBgLQ2, Line: 21, Column: 5

![image](https://user-images.githubusercontent.com/36483170/39923484-0cb2a36c-5524-11e8-920f-fee6d320222b.png)

**Comment by volkanceylan** [comment]
Add /// reference to base file, this is Nth time people do same mistake

**Comment by ga5tan** [comment]
sorry. I did not find it and did not need it in other cases.
it seems to inherit fine now
