### ISSUE TITLE
Distinct and SortBy dont work together in lookup

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3549]
I have lookup in QuickFilter:

protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            query.Distinct(true)
                .Select(SystemCatalogRow.Fields.Type, "Type")
                .OrderBy(SystemCatalogRow.Fields.Type);            
        }

With Distinct I got only unique items in table, but once I tried to sort them, uniqueness is gone.
But sorting works.
Any idea how to have both?

**Comment by VictorTomaili** [comment]
Try use distinct on end of query

**Comment by volkanceylan** [comment]
Or better look at sample lookups properly.

**Comment by volkanceylan** [comment]
CustomerCountryLookup
