### ISSUE TITLE
Masked input?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#355]
Is there a was to mask a IntergerEditor or DecimalEditor?

**Comment by swordz36** [comment]
MaskedEditior does the job

**Comment by swordz36** [comment]
I tried this [MaskedEditor(Mask = "$#.##")]

**Comment by volkanceylan** [comment]
You need to include jquery.inputmask.js for it.

**Comment by swordz36** [comment]
Are you talking about in the _LayoutHead.cshtml?

**Comment by swordz36** [comment]
I just used the [DisplayFormat("#,##0.00")]

**Comment by Thebenmandude** [comment]
Hi, I have also tried to mask a String field by using MaskedEditor(Mask="(###) ### ####") in my Row.cs. I have also added the following to my cshtml file but I still cannot get the mask to work.
"< script src="~/Scripts/input-mask/jquery.inputmask.js" type="text/javascript"></script >" 

When opening the dialog I get the following: 
![image](https://cloud.githubusercontent.com/assets/6910368/14081029/be03ee2e-f508-11e5-9ae2-38373e8670e3.png)
![image](https://cloud.githubusercontent.com/assets/6910368/14081042/da1f428e-f508-11e5-9bc7-b328c4b99cdc.png)

Am I missing something?

**Comment by smv2001ua** [comment]
#484
