### ISSUE TITLE
Changing Menu Layout

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#3552]
Good Day

Is there a way to change how the menu layout is setup, For instance instead of having the default side bar menu have the menu ontop of each page,

**Comment by sshandu** [comment]
So move the side bar ontop of the page as I have highlighted

**Comment by dfaruque** [comment]
look at `_Layout.cshtml` and change the sidebar as your need.

**Comment by JoshDiDuca** [comment]
This is possible, I have done this previously.
You just need to see how the sidebar is rendered and change it to create the html dropdown elements in the top bar instead. I remember having some issues with multi-levels but eventually got around them.
Sorry I can't provide code, good luck.

**Comment by dfaruque** [comment]
Geat @JoshDiDuca , Could you please add a screenshot. so that we can see the result.
Thanks.

**Comment by volkanceylan** [comment]
Thanks @JoshDiDuca

**Comment by PanChenhao** [comment]
@JoshDiDuca, The Top-Navigation wiki is blank. Could you check it? I also try to make the Top-Navigation but failed.
