### ISSUE TITLE
How to work with domains that return string instead of numbers?

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3553]
With Serenity it is possible to work with an enum or some other type of property that returns an Enum with string values? Example:

using Serenity.ComponentModel;
using System.ComponentModel;

namespace MovieTutorial.MovieDB
{
    [EnumKey("MovieDB.MovieKind")]
    public enum MovieKind
    {
        [Description("Film")]
        Film = **"F",**
        [Description("TV Series")]
        TvSeries = **"J",**
        [Description("Mini Series")]
        MiniSeries = "**M"**
    }
}

**Comment by volkanceylan** [comment]
See select with hardcoded values sample

**Comment by rcoproc** [comment]
Thank you Vokan, worked properly.
