### ISSUE TITLE
Why do we create a new page after the example, and the other page has JS error?

### ISSUE THREAD

**Issue by 374142863** [volkanceylan/Serenity#3556]
Hello Everyone，
 After I create a new task web page, other management pages, especially role management and user management, can not be used properly, and there will be some mistakes：
script error! sere browser console (F12)for details.
Message : TypeError:Administration.UserRow.Fieleds is undefined
File:http://localhost:53152/Scripts/site/MyTasks.web.js?v=Tx-d1sk-vHyZROfgFvLZDg2.Line:5975,Column:25

Look forward to your reply

Look forward to looking forward to

**Comment by 374142863** [comment]
But, how can I change this problem?

**Comment by ga5tan** [comment]
If u fixed it in xyzRows.cs, u gotta Build>Transform All T4 templates (in VS), so that typings for your Row are refreshed on client side.
