### ISSUE TITLE
Stuck at Calculation 

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#3557]
hi 
am working on the below attached grid am stuck at calculating the Balance Loan amount to be paid.
able to get the total emi paid from the slickgrid sum.
![emi](https://user-images.githubusercontent.com/29406374/40049651-ebe9f4b4-5852-11e8-82df-6a62e469a5a2.PNG)

but stuck at getting the balance calculation. How can i get it in serenity with out going for a store procedure.

Regards

**Comment by rcoproc** [comment]
And the total row of how columns should be configured in a grid?

**Comment by srinivas1910** [comment]
Thank you Guys Issue being resolved for me followed the #1021.
