### ISSUE TITLE
LockupEditor with InplaceAdd does not work when I use a custom Dialog (Editor)

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3559]
DisplayName("Munentcli"), Column("munentcli"), ForeignKey(typeof(MunicipioRow), "Muncod"), LeftJoin("c"), MunentEditor]
        [LookupEditor(typeof(MunicipioRow), InplaceAdd = true)]
        public Int16? Munentcli
        {
            get { return Fields.Munentcli[this]; }
            set { Fields.Munentcli[this] = value; }
        }

Here MunentEditor code:

namespace ControllerERP.Public {

  @Serenity.Decorators.registerEditor()
  export class MunentEditor extends Serenity.LookupEditorBase<Serenity.LookupEditorOptions, MunicipioRow> {

    constructor(hidden: JQuery) {
      super(hidden);
    }

    protected getLookupKey() {
      return 'Public.Municipio';
    }

    protected getItemText(item, lookup) {
      return super.getItemText(item, lookup) + ' - [' + item.Muncod + ']' ;
    }
  }
}

**Comment by volkanceylan** [comment]
You are not passing options to base class

**Comment by rcoproc** [comment]
Thanks Volkan, worked properly with your tip.

**Comment by axelcasauran** [comment]
where should I pass the options to base class?
