### ISSUE TITLE
How do I change the default language of my Application (dotnetcore)?

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3560]
I would like it to come already in Portuguese (BR) as default language.

**Comment by volkanceylan** [comment]
You should check .NET core docs.

**Comment by controllernet** [comment]
I make this and works
in initialization folder, UserCultureProvider.cs,  

  public Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext)
        {
            var culture = httpContext.Request.Cookies["LanguagePreference"];
            if (string.IsNullOrEmpty(culture))
                culture = "pt-BR";
            else
