### ISSUE TITLE
Is it possible to make fields visible or invisible based on another field? (Conditional Visibility)

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3561]
![visible_conditional](https://user-images.githubusercontent.com/7529472/40065586-214045fa-5830-11e8-830f-9648d3a40570.png)

In this example I even managed to make a CNPJCLI field invisible, but the label was not, and these two resources depend on the result of the select2 type (client).

**Comment by rcoproc** [comment]
Thanks Estrusco, i do this is correct ?

constructor() {
      super();

      this.form = new ClienteForm(this.idPrefix);

      this.form.Tippescli.changeSelect2(e => {
        var tippescli = this.form.Tippescli;

        if (tippescli.value == "F") {
          this.trataPessoaFisica();
        }
        else {
          this.trataPessoaJuridica();
        }
      })

    }

    // Oculta ou Mostra os atributos conforme o tipo da Pessoa
    private trataPessoaFisica(): void {
        console.log('Tratando pessoa Física');
        this.element.find(".Cnpjcli").hide();
        this.element.find(".Insestcli").hide();
        this.element.find(".Insmuncli").hide();
        this.element.find(".Rgcli").show();
        this.element.find(".Cpfcli").show();
        this.element.find(".Orgexpcli").show();
        this.element.find(".Datrgcli").show();
    }

    private trataPessoaJuridica(): void {
        console.log('Tratando pessoa Jurídica');
        this.element.find(".Cnpjcli").show();
        this.element.find(".Insestcli").show();
        this.element.find(".Insmuncli").show();
        this.element.find(".Cnpjcli").show();
        this.element.find(".Cpfcli").hide();
        this.element.find(".Rgcli").hide();
        this.element.find(".Orgexpcli").hide();
        this.element.find(".Datrgcli").hide();
    }

**Comment by Estrusco** [comment]
Yes. To hide elements you can use this.form.Cnpjcli.element.hide(), etc.

**Comment by mloro** [comment]
Hi guys, i have one question..

It's possible to hide/show  a button based on the value of a filed of the row that i select?

Thanks

**Comment by VictorTomaili** [comment]
Yes

**Comment by VictorTomaili** [comment]
Find element with selector and use key press events and condition statement. Then find button with selector and show or hide button (or best one, disable or enable button)

You asked first "is it possible", so I answered for this question. If you need learn "how to", try to check serene samples and do some google re-searches.

**Comment by mloro** [comment]
I tried and now i know how to do that!
Thanks @VictorTomaili
