### ISSUE TITLE
"List" how to get values

### ISSUE THREAD

**Issue by jukuikk** [volkanceylan/Serenity#3563]
Hi All , I would like to use List in ProductForm.cs , and I need to use three tables

step1.  add "color" and "size" in TableA
step2.  add their values in TableB
step3. click button to add all combinations in TableC
![default](https://user-images.githubusercontent.com/19999495/40103833-62f77df0-5921-11e8-8e2c-ed9fe97ba9bf.png)
But this result in picture is incomplete and many bug....
It doesn't work when I add new product...

My button code write in TableC.Editor.ts.
How can I get this Product Name add in combination like "ProductName-Green-L"?
And TableC how to get value in TableB lookup from TableA?

Thanks, if its not clear , please tell me .

**Comment by brunobola** [comment]
you can make you own editors for instance see: https://github.com/volkanceylan/Serenity/issues/3485

**Comment by jukuikk** [comment]
Hi @brunobola ,thanks for your help,and I read it .
I think I need to use this function "
`public setEditValue(source, property) {`
`            this.value = source[property.name];`
`        }`

But I don't understand where to put it in my code and use it.

**Comment by brunobola** [comment]
@jukuikk you can just use the GridEditorBaseAdvanced then create your editor extending the GridEditorBaseAdvanced and use like the post and u'll get access to the source properties and more...

**Comment by jukuikk** [comment]
Thanks a lot ,I'd try it.
