### ISSUE TITLE
CKEditor warning on Customers Note tab

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#3564]
Bundle.CKEditor.js?v=vmn3-g0BA0nrgCxTou0AnQ2:21 [CKEDITOR] Error code: uploadimage-config.
Bundle.CKEditor.js?v=vmn3-g0BA0nrgCxTou0AnQ2:21 [CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-uploadimage-config

**Comment by wldkrd1** [comment]
I'm seeing this error also with dialogs using HtmlNoteContentEditor

**Comment by volkanceylan** [comment]
Fixed in next version.
