### ISSUE TITLE
Grouping in Grid for Enum

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#3565]
Hi, I have added grouping on Enum field,

            buttons.push(
                {
                    title: 'GroupBy Status',
                    cssClass: 'expand-all-button',
                    onClick: () => {
                       this.view.setGrouping(
                        [{
                            getter: 'Status'
                        }])
                    }
                }
            );

Here on the grid after grouping, I'm getting 
![image](https://user-images.githubusercontent.com/17939331/40162849-c94eb116-59d2-11e8-8273-f380b40b8053.png)

How can i get Description of Enum instead of number

**Comment by dfaruque** [comment]
user enum formatter
``` ts
this.view.setGrouping(
                    [{
                        formatter: x => Serenity.EnumFormatter.format(Serenity.EnumTypeRegistry.get(enumKey), Q.toId(x.value)),
                        getter: 'Status'
                    }])
```

**Comment by vinaykulkarni89** [comment]
Thankyou @dfaruque , it worked awesome, thankyou once again

**Comment by engOmniaShawky** [comment]
if i have number not enum how can i make condition like if it's 1 name it "something" else if 2 name it "something 2 "
@dfaruque
