### ISSUE TITLE
Changed the Folder Where Project is and Sergen generates at older Folder

### ISSUE THREAD

**Issue by guiRui11** [volkanceylan/Serenity#3567]
Changed the Folder Where Project is and Sergen generates at older Folder, what I need to change so sergen sees the current folder ?

All the project builds fine and transform also, only sergen won't seem to understand the new folder.

**Comment by brunobola** [comment]
You can change this settings using the sergen:

![image](https://user-images.githubusercontent.com/10889019/40173212-fd4571a8-59c8-11e8-99db-3164307d178e.png)

**Comment by guiRui11** [comment]
Thanks @brunobola works 👍
