### ISSUE TITLE
Edit Dialogue's styling

### ISSUE THREAD

**Issue by tynmas02** [volkanceylan/Serenity#3569]
Hello! Is there a way I can edit dialogue field styling with html and css? What I mean is if I could do something like this (https://ibb.co/c8TiQd) in serenity. All dialogues are generated, is there a way I can make a custom dialogue with that design in the picture I sent you? If so, could you please sent me an example. I'm in my final stages of a project based in serenity and I'm stuck. Thank, you very much.

**Comment by rcruzfalcon** [comment]
Hi @tynmas02 , yes, you can "move" the controls to any locations, with jscript or, we create "virtual" grid with the field and when save put each value in table field.
For example, this case above is the "virtual grid" with all the field of one row in fare table on our system.
![image](https://user-images.githubusercontent.com/21364279/40194933-5fcfb8d8-59e2-11e8-91f4-fe1c2c5fc4bb.png)
Best regards.

**Comment by tynmas02** [comment]
@rcruzfalcon Hello! Thank you for your tip! Could you please send me a code example? Thank, you!

**Comment by tynmas02** [comment]
Hello Roberto Cruz! Could you please send me a sample code with custom
dialogues? I am in the final stages of a project, and I have no idea how to
style and create custom dialogues. Thank, you!

**Comment by dfaruque** [comment]
You can design that page using .cshtml if you know asp.net mvc

**Comment by tynmas02** [comment]
@dfaruque Thank you very much! I know asp.net mvc, but how can I implement it in Serenity. Could you please give me an example?

**Comment by dfaruque** [comment]
you could take dashboard page as a sample.

**Comment by tynmas02** [comment]
@dfaruque Thank, you very much that was what I was looking for, but couldn't find in the samples.
