### ISSUE TITLE
Note Dialog css

### ISSUE THREAD

**Issue by Olricz** [volkanceylan/Serenity#357]
Volkan not tab'ı yerıne eklenmıyor. css yerı neresı acaba ? 

![ekran alintisi](https://cloud.githubusercontent.com/assets/16984654/13477117/8b14c9d2-e0d3-11e5-83d5-d15b91a9abc2.JPG)

**Comment by volkanceylan** [comment]
Tab a taşımayacak mısınız Customer dialog gibi

**Comment by Olricz** [comment]
Evet. Ayni nortwind ornegindeki gibi. Tab"a ekleyen yer neresi ?

**Comment by volkanceylan** [comment]
Dialog kodu

**Comment by Olricz** [comment]
Kodlar filan aynı gorunuyor ornekle. ama ekran goruntusundekı gıbı geliyor.
![11](https://cloud.githubusercontent.com/assets/16984654/13493420/b9efcfe0-e146-11e5-8df1-fea375cf8824.JPG)

**Comment by volkanceylan** [comment]
Dialog.cs :)

**Comment by Olricz** [comment]
eywallah.
