### ISSUE TITLE
dotnetcore project debug typescript outside wwwroot

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#3570]
asp.net core project only loads files inside wwwroot, but almoust all the **ts** files are outside wwwroot, 

I find I can only debug **ProjName.Web.js** , and **ProjName.Web.js.map** becomes useless.

Does anyone have a solution?

**Comment by volkanceylan** [comment]
Add 

```ts
    "inlineSourceMap": true,
    "inlineSources": true
```

to your tsconfig.json

**Comment by tky753** [comment]
Thanks @volkanceylan  for the advice!
That's exactly what I want.
