### ISSUE TITLE
Split Header in  Serenity Grid 

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3571]
Hi,

I just need to group some of the columns under an additional header. 
How can I achieve this? can anyone please help me on this.

![image](https://user-images.githubusercontent.com/11703554/40228267-b2c80e2c-5a88-11e8-8469-49300927e49c.png)

**Comment by ga5tan** [comment]
Maybe just make custom fields where you concatenate strings together (padded with space and maybe separated by |), to make it look like multiple columns ?

**Comment by AmuthaKondusamy** [comment]
![image](https://user-images.githubusercontent.com/11703554/40292481-7921c766-5cc3-11e8-871c-0f272452564e.png)
@ga5tan  For clear understanding I have attached another image that portraits my need clearly. I just want to add an additional header in the top for some of the columns by dynamically grouping it (2018 in the attached image) as like for all years.

**Comment by ga5tan** [comment]
Well, I am not gonna screenshot u what I meant, but you may consider checking in with slickgrid forums to see how to do it...

**Comment by AmuthaKondusamy** [comment]
@JohnRanger

**Comment by AmuthaKondusamy** [comment]
@JohnRanger / @volkanceylan : 
can you please help me on this?

**Comment by volkanceylan** [comment]
That is not currently possible, sorry.

**Comment by AmuthaKondusamy** [comment]
Okay Volkan. Thank you.

**Comment by MahendranTechStarz** [comment]
Is it Possible Now? @volkanceylan
