### ISSUE TITLE
Is there a quick way to configure logs to view  the database selects that are generated by serenity in the logs?

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3572]
In Ruby on Rails this is already native to the Development environment.

**Comment by volkanceylan** [comment]
In web.config there is a "Logging" setting, set its Level to Debug, see logs under App_Data/log

**Comment by brunobola** [comment]
@rcoproc if u're using a MS SQL instance, why don't you use the SQL Server Profiler that tells you everything you want and more.

![image](https://user-images.githubusercontent.com/10889019/40451684-4ff908ca-5ed7-11e8-9cfc-cafa4410fc19.png)

**Comment by brunobola** [comment]
@wldkrd1 The performance impact would be minimal, also you can filter for an huge amount of parameters to match only your criteria.

Nevertheless you're right sometimes there are better alternatives according to your needs.

**Comment by rcoproc** [comment]
In Ruby on Rails, we can see the selects logs in the Development environment in a very quick and practical way.

![imagem_log](https://user-images.githubusercontent.com/7529472/40523712-fcd9a48c-5fa4-11e8-8f5a-b0cc30292f6b.png)
