### ISSUE TITLE
Before Delete validation 

### ISSUE THREAD

**Issue by mloro** [volkanceylan/Serenity#3573]
Hi all.
I have that situation : 
I want to delete a  row from my "Author" table but my problem is that i use that row in my "Books" table , because when i create a book i need one author, can anyone gives me an advice on how to validate in my  repository that? 
I know that i need to create a validation in the Delete request but i dont know how to ask if my "Author id " exists in a Book that was already created.

Thanks.

**Comment by JoshDiDuca** [comment]
Override the delete function in the dialog and implement your own validation if you need to,

**Comment by ga5tan** [comment]
@mloro if you use foreign keys on your DB, DB wont let u delete master record, while it still has detail records. That's the easiest handling and the one I would suggest. It will also keep you from inserting books without existing author. Alternatively (which may not be you case) you can set up cascade delete, where by deleting master record (author), all it's detail records (books) will be deleted automatically...

**Comment by mloro** [comment]
Thanks @ga5tan  for the advice.!
