### ISSUE TITLE
Arabic localization file to help serenity grow in Arabic community :heart:

### ISSUE THREAD

**Issue by mafdy** [volkanceylan/Serenity#3574]
Serenity platform is unbelievable achievement on business apps development.    
kindly check the attached file, Arabic Egypt localization text of my beloved platform **Serenity** :heart: , hope it helps serenity grow in Arabic community and become greater and greater world wild .

Right to left CSS need some modification, I'll work on them. Once i finish, I'll upload that or ask for pull request.
I hope I can do more because I owe it.

@volkanceylan and all of the team, **thanks for Serenity**, wish you unlimited success :smile: :+1: :+1:
[user.texts.ar-EG.zip](https://github.com/volkanceylan/Serenity/files/2020701/user.texts.ar-EG.zip)

**Comment by volkanceylan** [comment]
Thanks @mafdy for your contribution!

**Comment by mjacoup** [comment]
thanks @mafdy
