### ISSUE TITLE
Error when sending mail

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3575]
Hi,
I am trying to send a mail inside a repository file on AfterSave(). The code is below

namespace hails.IncidentLogging.Repositories
{
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.Data;
    using System.Net.Mail;
    using MyRow = Entities.PendingIncidentRow;

    public class PendingIncidentRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void AfterSave()
            {
                base.AfterSave();

                var externalUrl = Config.Get<EnvironmentSettings>().SiteExternalUrl;

                var pendingIncidentLink = UriHelper.Combine(externalUrl, "IncidentLogging/PendingIncident?edit/t=#" + fld.IncidentId);
                //pendingIncidentLink = pendingIncidentLink + Uri.EscapeDataString(token);

                var emailModel = new IncidentEmailModel();
                emailModel.Username = Authorization.UserDefinition.Email;
                emailModel.IncidentLink = pendingIncidentLink;

                MailMessage mailMessage = new MailMessage();
                mailMessage.From = new MailAddress(emailModel.Username);
                mailMessage.To.Add("george.frank.otoo@gmail.com");
                mailMessage.Subject = fld.IncidentTitle.ToString();
                
                mailMessage.Body = TemplateHelper.RenderTemplate(MVC.Views.IncidentLogging.PendingIncident.PendingIncidentEmail, emailModel);

                //fld.IncidentDesc.ToString();
                mailMessage.IsBodyHtml = true;

                var connection = SqlConnections.NewByKey("Default");

                var userRow = connection.TryFirst<Administration.Entities.UserRow>(Administration.Entities.UserRow.Fields.Username == Authorization.UserDefinition.Username);

                SmtpClient smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Credentials = new System.Net.NetworkCredential(Authorization.UserDefinition.Username, userRow.Password),
                    Timeout = 30000,
                };
                smtp.Send(mailMessage);

            }
        }
        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { }
        private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);
                var user = (UserDefinition)Authorization.UserDefinition;
                if (!Authorization.HasPermission("Administration:Security"))
                {
                    query.Where(fld.IncidentStatusStatusName == "Pending" && fld.InsertUserId == user.UserId);
                }

            }
        }
    }
}

When I click the save button, the error below is shown. Kindly help.

![email error](https://user-images.githubusercontent.com/14317420/40316865-2dbdd16a-5d0f-11e8-953a-27191928e43b.PNG)

**Comment by volkanceylan** [comment]
Look at where you copied that code from, and see how it handles externalUrl when it is not specified in web.config.

**Comment by gfo2007** [comment]
Thanks
