### ISSUE TITLE
Basic question on forms/dialogs

### ISSUE THREAD

**Issue by tynmas02** [volkanceylan/Serenity#3576]
I'd like to make a very basic question concerning -specific, not all- forms and particularly dialogs:

Is there a way to arrange the various elements (labels, text boxes, etc) as one wishes supposedly with the use of HTML, CSS, Bootstrap, or other code or not. Or is that Serenity won't allow for any amendments to a form/dialog automatically created arrangement of the various elements?

This is very important to me as I will or will not allow to go on with Serenity.

Thank, you!

**Comment by brunobola** [comment]
Serenity allows a certain amount of personalization using less and/or html hacks.
Search a bit in the issues u'll find several samples.

**Comment by tynmas02** [comment]
@brunobola I have searched anywhere, all answers are vague. You say I will find several samples and there are no samples and all the other answers are the same type, no one tells me which sample exactly they are referring to. I don't know if there is a way to achieve this, answers of the type, you can do it, doesn't help me at all, I don't ask whether I can do it generally or hack my way to it, I ask how exactly I can do it. I have searched all samples and there is none solving my problem. I have made a big project with Serenity, I was going to buy the professional plan that Serenity offers in order to extend and reserve my project and It's been months searching to find a solution to my problem and I can't do anything to finish the last piece of my project. Therefore, I will not continue with Serenity as I have no time for trying to solve this and I don't get any info or help due to lack of information and the fact that Serenity is known by a small amount of people makes it even harder.

**Comment by brunobola** [comment]
I suggest you to do this:

1. https://serenity.is/demo      -> and see what you expect in Professional
2. https://github.com/volkanceylan/Serenity/wiki     -> See the wiki
3 . https://legacy.gitbook.com/book/volkanceylan/serenity-guide/details      -> Guide   
4. https://github.com/volkanceylan/Serenity/issues/2720      -> One Sampls

**Comment by volkanceylan** [comment]
> This is very important to me as I will or will not allow to go on with Serenity.

Can only say good luck.

**Comment by tky753** [comment]
Thanks @volkanceylan for the advice.! 
That's exactly what I want,
