### ISSUE TITLE
What's the step to implement  CustomEditor,Just as OrderDetailsEditor

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#358]
When I add a attribute  in the ScriptEditorType.cs,It will override by the T4 Template?

**Comment by volkanceylan** [comment]
Yes, don't add something there. When you transform T4 it'll bring your new editor type there.

**Comment by ChenZhaobin** [comment]
Thanks,Just need use [LookupScript("Northwind.OrderDetailsEditor")] ,then I can have [LookupEditor("Northwind.OrderDetailsEditor")] ,I forgot it!

**Comment by volkanceylan** [comment]
No, it's wrong, lookup editor has no relation to OrderDetailsEditor, typo?

**Comment by ChenZhaobin** [comment]
GridEditor?

**Comment by ChenZhaobin** [comment]
Then how ?Where did it implement OrderDetailsEditor?

**Comment by ChenZhaobin** [comment]
I resolved it by create a file named XXEditor,then every thing works!
I realised this by the code in MultipleOutputHelper.ttinclude  just as below
 foreach (var type in lister.List().Values) {
        if (lister.IsEditorType(type))
        {
            generator.EditorTypes[type.FullName] = new EditorTypeInfo {
                Options = lister.GetOptions(type)
            };                
        }
    }

**Comment by ChenZhaobin** [comment]
I want to implement  something  just like OrderDetailsEditor,I also have a Composite Primary Key,but datatype is not integer,it is string ;When I update ,It warning NotImplementedException,I can't figureout it
