### ISSUE TITLE
Generate Typings in different namespace

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3583]
I am migrating some legacy code with different namespace (CodeI). Is it possible to configure typings generator to generate from different namespace? Outside of the scope of main project (CodeSys)?

**Comment by Estrusco** [comment]
You have to create your .tt file in the new project. Try to start from original .tt file, and change according your project.

**Comment by ga5tan** [comment]
@Estrusco thx. I experimented a little bit, but ended up moving legacy namespace into main project ones to make life easier
