### ISSUE TITLE
Shamsi DatePicker

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3586]
I am trying to replace existing date picker in Serenity or add a different DatePicker but cannot figure out how to make it in Serenity.

It will work for me to use existing jquery UI culture available like Persian data Picker or a custom one.
But I need some clue on how to fire or attach the datepicker with the date picker button available in Serenity.

![image](https://user-images.githubusercontent.com/20435849/40522146-97d83e28-5fe4-11e8-84a5-f962ad9e99a1.png)

**Comment by VictorTomaili** [comment]
create custom, don't use exist one.

**Comment by ms4hafiz** [comment]
Thank you @VitorTomaili

I will use my custom one but I need a support on how to add a button next to Textbox in the dialog.

**Comment by volkanceylan** [comment]
You should have inline action buttons sample in your StartSharp.
