### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3587]
I have the following code in xxDialog.ts and want to get some value. 
But when I create new new record it gives error. I understand when Facility is blank it gives this error but **how can I ask Serenity to ignore when Facility is blank. I used this check  if (facilityId != null || facilityId != undefined || facilityId!="") but it is not working. **

        loadEntity(entity: pnddbAsp.Add.NutritionDataRow) {
            super.loadEntity(entity);

            var facilityId = this.form.FacilityId.value;
            if (facilityId != null || facilityId != undefined || facilityId!="") {

                var id = Serenity.EditorUtils.getValue(this.form.FacilityId)

                pnddbAsp.Geography.HealthfacilitiesService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setDateDetails(response.Entity);
                });
            }
            else
                return;
        }

![image](https://user-images.githubusercontent.com/20435849/40523088-48880862-5fe9-11e8-9cb0-60b9fe8da14c.png)

**Comment by VictorTomaili** [comment]
Facility is required field. So you need use custom validation for customize it in typescript.

**Comment by ms4hafiz** [comment]
Thank you @VictorTomaili 

I removed the validation (required) from Facility but still there is this error. It works fine with the following code

            this.form.FacilityId.changeSelect2(e => {
                var facilityId = this.form.FacilityId.value;
                if (facilityId == null || facilityId == undefined) {
                    this.setDateDetails({});
                    return;
                }

                var id = Serenity.EditorUtils.getValue(this.form.FacilityId)

                pnddbAsp.Geography.HealthfacilitiesService.Retrieve({
                    EntityId: id
                }, response => {
                    this.setDateDetails(response.Entity);
                });
            });

but it need similar functionality with LoadEntity which does not work when I apply it on the onload of the form as my previous Typescript code.

**Comment by ms4hafiz** [comment]
solved by adding a check.
