### ISSUE TITLE
What is the difference / meaning of "Imports" subfolders in Serenity Dotnet Core?

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3589]
Some of the files in the ClientTypes folder are generated during Build, I want to know how they will behave (build time) in large projects (500 tables)?

**Comment by VictorTomaili** [comment]
Just try it, generate default tables from db for 500 tables and build. 

If you don't like build time, write your own optimized typing.ts code generator what ignores finalized tables. 

tip: create an attribute like [ExcludeClientType] and modify exist serenity code generator for ignore types with this attributes. Then move .ts files from clientTypes folder to permant folder.
