### ISSUE TITLE
How do I know in the Northind Report Order example which order (id) will be printed?

### ISSUE THREAD

**Issue by rcoproc** [volkanceylan/Serenity#3592]
In this section of the code where the report data to be printed is obtained, you have these instructions:

[
[Report("Northwind.OrderDetail")]
    [ReportDesign(MVC.Views.Northwind.Order.OrderDetailReport)]
    [RequiredPermission(PermissionKeys.General)]
    public class OrderDetailReport : IReport, ICustomizeHtmlToPdf
    {
        public Int32 OrderID { get; set; }

        public object GetData()
        {
var data = new OrderDetailReportData();

            using (var connection = SqlConnections.NewFor<OrderRow>())
            {
                var o = OrderRow.Fields;

                data.Order = connection.TryById<OrderRow>(this.OrderID, q => q
                     .SelectTableFields()
                     .Select(o.EmployeeFullName)
                     .Select(o.ShipViaCompanyName)) ?? new OrderRow();](url)

...

My question is: Which parameter (maybe the q), tells me which is the Order I want to filter / print?

**Comment by ga5tan** [comment]
this.OrderID tells u, which order u want to print

**Comment by rcoproc** [comment]
Thank Juraj now well understood how this routine.
