### ISSUE TITLE
Filter Lookup

### ISSUE THREAD

**Issue by sshandu** [volkanceylan/Serenity#3597]
Hi Guys

I have a Goal table with the following fields GoalID,GoalName,Description, DepartmentID, I want only values with departmentID 3 to be shown. On my GoalLookupEditor.ts file I have the below

 protected getItems(lookup: Q.Lookup<Strategicplanning3.GoalsRow>) {
            return super.getItems(lookup).filter(x =>
                x.DepartmentID === 3);
        }

The above does not work, the above method only works when I specify a unique value for example goalID
protected getItems(lookup: Q.Lookup<Strategicplanning3.GoalsRow>) {
            return super.getItems(lookup).filter(x =>
                x.GoalID === 1 || x.GoalID === 7);
        }

Is there a way I can achieve this buy showing items only with departmentID 3 on the lookup?  there are about 7 of these items

**Comment by Garozh** [comment]
What you are searching for is FilterType and FilterValue Attribute.

Put in your XYZRow/XYZForm File the following attribute:
FilterType("DepartmentID"), FilterValue("3")

**Comment by sshandu** [comment]
Hi Garozh

I have the following on my form

        public Int32 GoalId { get; set; }

so where do I put what you suggested?

**Comment by Estrusco** [comment]
Over public Int32? GoalId  in your GoalsRow.cs class

**Comment by sshandu** [comment]
Hi guys

Is there a way I can use a stored procedure for my Lookup just like you
will do in MVC and pass a parameter i.e. @departmentID? and assign that
stored proc to my lookup so I can have filtered results based on the
departmentID?
