### ISSUE TITLE
For Brazilian and Latin America - WhatsApp Group

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#3599]
Dear Volkan,

I've create a WhatsApp group for Brasil and Latin America Developers.

I would like to know if I can post the link to join the group here.

The main idea is share  knowledge of Serenity. I noted that the main doubt is the simple question, that we answered a lot here.

Of course if any interesting code appears, I'll share here.

**Comment by volkanceylan** [comment]
Hi @rolembergfilho, its ok you may share your group link here

**Comment by rolembergfilho** [comment]
Thanks !!!!


So, this is the link to our WhatsApp group for Brasil and Latin America Developers.

**https://chat.whatsapp.com/0Jlk5nzJnvuAHSfPiPSdua**

**Comment by jmkamran** [comment]
this group is for indian,emerican and pakistan to learn about serenity
https://chat.whatsapp.com/IUtjk5fFRX27IqzVgivnjK

**Comment by rolembergfilho** [comment]
hey volkan!!

the idea of WhatsApp group is growing! we solved and shared a lot of solutions that existed here, but some developers still have found some difficulties.

So, we created a other group: Serenity Latino America, where Spanish is the main language

https://chat.whatsapp.com/AtaXa826AFz49soMU9A3cL

**Comment by rolembergfilho** [comment]
due to the last few occurrences, I closed the registration link.
Now, to register, please send an email to contato@serenitybrasil.com.br
After brief questions (if you are a developer, etc) I will personally add in the group

The e-mail for subscription is **contato@serenitybrasil.com.br**

**Comment by rogmauri** [comment]
OK Rolemberg.
Registering that way got better.

**Comment by jaamkamran** [comment]
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q/videos?view_as=subscriber
For Learners. how to make Project in serenity? Kindly subscribe my channel.
