### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#360]
Hi Volkan, just simple question (need your opinion)
We are going to buy new template for our 'admin' zone and i wonder if it is too difficult to change design of Serene from AdminLte to another one 
Thanks

**Comment by volkanceylan** [comment]
I'm using some other template too. Prefer a bootstrap one. But anyway you need to have some CSS/CSHTML skills

**Comment by BolatovAlau** [comment]
Thanks
