### ISSUE TITLE
Filter Lookup

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3601]
Hi,

I am having a YEAR field as a textbox in my XYZForm. I just need to filter the rows by Year. I have referred  Countries Filter in Customer module in Serenity demo and added a filter to my application. Now it is displaying already added year in the filter. But it is not displaying the new year if I added. 
How to make the filter to display the value that is newly added. 

Can anyone please help me on this

**Comment by VictorTomaili** [comment]
Please update title for question.

**Comment by ga5tan** [comment]
you have to refresh cliend side script. see demo samples.
I think here: https://serenity.is/demo/BasicSamples/OtherFormInTab
for example, Customers are reloaded when added in second tab...

**Comment by AmuthaKondusamy** [comment]
Thanks. working
