### ISSUE TITLE
Why do we have "change" and "changeSelect2"

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#3602]
I have found a little difference between "change" and "changeSelect2"

changeSelect2() does not fire after updating a record using InPlaceAdd dialog
while change() does

why changeSelect2 there?

**Comment by volkanceylan** [comment]
changeSelect2 only fires when user changes the value, change fires when value is set, e.g. when data is loaded into dialog.

**Comment by dfaruque** [comment]
Thank you, got it.

**Comment by dfaruque** [comment]
Hello dear,
in the new version (3.13.4) the behavior of changeSelect2 is changed. It always fires whether the user changed the value or programmatically loaded by the code.

But we need the previous behavior as you said.

> changeSelect2 only fires when user changes the value, change fires when value is set, e.g. when data is loaded into dialog.
