### ISSUE TITLE
Prompt user if data is not saved in Grid textbox

### ISSUE THREAD

**Issue by AmuthaKondusamy** [volkanceylan/Serenity#3605]
Hi,

I just need to prompt User, when the user is trying to leave the site by pressing panel back button without saving the data in grid.

I can able to prompt in dialog and I find difficult in Grid. can anyone please suggest me a solution.
And also, though it is not serenity thing, How to detect the browser back button click and stop user going back?

**Comment by brunobola** [comment]
see this https://serenity.is/demo/Northwind/Product

**Comment by volkanceylan** [comment]
You may also check javascript window beforeunload event

https://stackoverflow.com/questions/1631959/how-to-capture-the-browser-window-close-event
