### ISSUE TITLE
How do ensure server side validation and force some feild value before save

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#3606]
How do ensure server side validation and force some feild value before save, below code throws error

private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                MyRow.Fields.IsActive = 1;
                 if (MyRow.Fields.Name=="Jhon")
                //    throw new Exception("error in adding because of this issue");
            }
        }

**Comment by wldkrd1** [comment]
You're looking for
`protected override void ValidateRequest()
{
    base.ValidateRequest();
    if (Row.Name =="Jhon")
    {
        throw new Exception("Jhon's not allowed");
    }
}`
