### ISSUE TITLE
How to add inline button in Dialog.ts next to a textbox

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3608]
Hi;

I would like to add a button after a textbox. As you can see in the following image I would like to add it after Filling Date(Shamsi) but it shows next to toolbar buttons. What I need is to add similar to date picker.

![image](https://user-images.githubusercontent.com/20435849/40868661-1e545cf8-6624-11e8-82a4-974f8ce275a3.png)

I have this could code to start but now working

        protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();

            buttons.push({
                title: "Shamsi",
                hint: "Another date picker",
                cssClass: "'dd-note-button",
                icon: "fa-pencil",
                onClick: () => { }
            })
            return buttons;
        }

**Comment by minhhungit** [comment]
Hi @ms4hafiz , put this into your dialog
```javascript
protected afterLoadEntity() {
    super.afterLoadEntity();

    $('<a class="inplace-button inplace-create"><b><\/b><\/a>')
         .insertAfter(this.form.YOUR_FIELD_HERE.element)  // <======================
         .click(() => this.myFunction());
}

private myFunction() {
    Q.alert("clicked");
}
```

**Comment by ms4hafiz** [comment]
thank you @minhhungit 

It is helping and now I can bind the button next the textbox I want.

I would like to make some more binding to the button as following:

        <button class="btn btn-default" data-mddatetimepicker="true" data-targetselector="#dateWithFormat" data-enabletimepicker="true"
          data-placement="left" data-mdformat="dddd dd MMMM ">
          <span class="glyphicon glyphicon-calendar"></span>
        </button>
How can i do it . I am new and learning

**Comment by minhhungit** [comment]
@ms4hafiz sorry I am not sure what you want to do. Can you explain with more detail

**Comment by ms4hafiz** [comment]
Thank you @minhhungit 

What I want is to fire and get value of a date picker. The date picker is available here https://github.com/Mds92/MD.BootstrapPersianDateTimePicker

In MVC 5, I call the date picker using the following 

                                         @Html.EditorFor(model => model.ComitmentDate, new
                                        {
                                            htmlAttributes = new
                                            {
                                                data_mddatetimepicker = "true",
                                                data_trigger = "click",
                                                data_targetselector = "#ComitmentDate",
                                                data_enabletimepicker = "false",
                                                data_placement = "bottom",
                                                data_disablebeforetoday = "false",
                                                data_isgregorian = "false",
                                                data_englishnumber = "true",
                                                @class = "form-control"
                                            }
                                        })

But in serenity, I cannot figure it out how to activate the date picker or use the above code in dialog.ts.

**Comment by minhhungit** [comment]
I think the best way is you should create a custom editor for yourself
check this: [DateTimeEditor](https://github.com/volkanceylan/Serenity/blob/c2eedd43d73377180a5e947f6e2a577197c6129d/Serenity.Scripts/CoreLib/UI/Editors/DateTimeEditor.ts)

check more editor examples on wiki

![image](https://user-images.githubusercontent.com/2279508/40873486-043a0d4c-668b-11e8-9deb-7dad64a52f74.png)

**Comment by ms4hafiz** [comment]
Thank you 
I will look at it but is it possible without creating additional editor?

**Comment by ms4hafiz** [comment]
Thank you
I am working to learn how to create custom editor for my special need. I am not sure if I will succeed.
