### ISSUE TITLE
Error encountered when I "tab" into a datetime field

### ISSUE THREAD

**Issue by cfthong** [volkanceylan/Serenity#361]
Using Northwind sample screen, I tried to create a NEW ORDER. After selecting the CUSTOMER from the drop-down, I use the "tab" key to go to the ORDER DATE and encounter the following error:

Unhandled exception at line 1463, column 2 in http://localhost:62811/Scripts/jquery-2.2.0.js?v=VvHQHuS7aNFXLP1gdVz2eg2

0x800a139e - JavaScript runtime error: Syntax error, unrecognized expression: unsupported pseudo: readonly

Please advise how to resolve this problem.

**Comment by volkanceylan** [comment]
It's about wrong usage of a pseudo class, in Serenity.Script.UI.js find

`if (input.is(':readonly') || input.is(':disabled')) {`

Replace with 
`if (input.is('[readonly]') || input.is(':disabled')) {`

Will be fixed in next version.

**Comment by cfthong** [comment]
Ok. thanks.
