### ISSUE TITLE
Can we use a CKEditor in a inline Grid column ?

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#3611]
The goal is enable a way to edit html code directly from the row in this space:

![image](https://user-images.githubusercontent.com/10889019/41093341-f797d5c2-6a42-11e8-9cc1-d929d148982d.png)

**Comment by brunobola** [comment]
I believe it is described as an image, any ideas anyone ?

**Comment by volkanceylan** [comment]
Sorry, using widgets / components in slickgrid is not supported as noted in Product grid code.
