### ISSUE TITLE
How to handle bool value columns in an existing database on serentiy .net app (not .net core)?

### ISSUE THREAD

**Issue by thomasmt** [volkanceylan/Serenity#3613]
I have connected an existing postgres database to .net serenity application (not .net core). I have created the module related codes using sergen.exe. The data type for boolean field in the database appears as Stream in the generated classes. After running the application and trying to get entity with postgres boolean data type, it throws an exception showing the message "GetBytes() not supported for type IsActive" in ListResponse<MyRow> List(.....) method in Repository class  ( IsActive is datacolumn name). And not able to create a entity because it shows the error in the form on clicking save button
![image](https://user-images.githubusercontent.com/24644845/40903315-96dce858-67f4-11e8-9308-293b715604a4.png)
 Can you suggest a solution ? Thanking you in advance.

**Comment by ga5tan** [comment]
I have MS SQL server and Booleans (bit) gets generated as Boolean?
Works fine with checkboxes (BooleanEditor)
just change type in Row class to something proper and it should work.
I remember I had some weird field type generated once, but after change in Row it all worked ok
