### ISSUE TITLE
Suggest to build a standard project for Sql Query Builder function.

### ISSUE THREAD

**Issue by kcvincent** [volkanceylan/Serenity#3614]
I had used serenity  about  a year.It is very helpful for building C# application.  I compared the SQLKata( a C# SQL Query Builder) with Fluent SQL function of Serenity. My feeling is the Fluent SQL function better than the SQLKata. 
I suggest to build a standard project for Sql Query Builder function of Serenity.
So we can use it at console program or other C# program.

**Comment by volkanceylan** [comment]
Does it not work when you add a nuget reference to Serenity.Data?

**Comment by kcvincent** [comment]
It Work but we must include the serenity.core. Do you MIND that create a project in this repo and let me do this simplified task ? Give me a chance to let me do do something for buddies ?

**Comment by kcvincent** [comment]
After a simply study , I think that no need to build single project for this purpose. The DLLs file size are very small.
Serenity.Core.dll  => 129K , Serenity.Data.dll => 237K
