### ISSUE TITLE
Is serene localization RTL layout  compactible?

### ISSUE THREAD

**Issue by dipin14** [volkanceylan/Serenity#3615]
Will serene localization support local languages like Arabic? Is RTL layout direction supported?

**Comment by Estrusco** [comment]
Yes, 

see changelog

2.4.1 (2016-07-29)
Features:

serene and slickgrid now has RTL support (thanks @misafer)

**Comment by ga5tan** [comment]
@dipin14 dude, there is even Arabic localisation (see #3574 by mafdy )
