### ISSUE TITLE
Master Detail Behavior Seems trying to insert a null value in foreign key

### ISSUE THREAD

**Issue by FGLedesma** [volkanceylan/Serenity#3617]
Hi,
I'm having an error when saving in a Maser-Detail Context. As far as I know, using Master detail behavior automatically resolves insertion of Master (primary) key in Child (as a foreign) ...
Already have...
[DisplayName("Detalle"), MasterDetailRelation(foreignKey: "IdPpal")] in Master.
And Use ...
[ChildEditor] ... In MasterForm
public List<Entities.TablaHijaRow> ListaDetalle { get; set; }

Additionally, Of course, there is a relation Between Master and Child, Being "IdPpal" the primary key in Master, and, as a foreign key in Child. The dB is MS-SQL (SqlLocaldB).

But, when I try to save a record...  constantly receive an error:
![image](https://user-images.githubusercontent.com/24248165/41006003-1c5fcfde-68f6-11e8-8bc9-8ced8ceb27c4.png)

Yes, I'm sure I'm missing something, but cannot figure out what it is... Anybody help me please?

Kind Regards,
Felix

**Comment by hannesb** [comment]
Does your child dialog derive from GridEditorDialog?

**Comment by FGLedesma** [comment]
Hi hannesb, first, thanks a lot for your interest.
Yes, it derives from GridEditorDialog... (Code follows):

/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace ProbarMasterDetail.Ventas {

    @Serenity.Decorators.registerClass()
    export class TablaHijaDialog extends Serenity.EntityDialog<TablaHijaRow, any> {
        protected getFormKey() { return TablaHijaForm.formKey; }
        //protected getIdProperty() { return TablaHijaRow.idProperty; }
        protected getLocalTextPrefix() { return TablaHijaRow.localTextPrefix; }
        //protected getNameProperty() { return TablaHijaRow.nameProperty; }
        //protected getService() { return TablaHijaService.baseUrl; }

        protected form = new TablaHijaForm(this.idPrefix);

    }
}

**Comment by hannesb** [comment]
Hmm well your dialog derives from EntityDialog, not GridEditorDialog.

**Comment by FGLedesma** [comment]
hannesb... Thanks a billion, 
I was absolutely blind, seeing the reference but not the <actual> declaration extends in the corresponding file!
Working in 3 projects at the same time is too much for my mind.

Again, I really appreciate your help. 
Kind regards
Felix
