### ISSUE TITLE
Conditional row formatting not working as expected

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#3618]
I have implemented conditional formatting in my grid. Basically, if cell contains value "CANCEL", the row background color  should be changed to pink. It appears that even/odd styles are conflicting with my custom style (property-cancelled). Theoretically it should not conflict because my custom style gets applied last (or I am missing something). How do I turn off alternating colors in the grids (odd/even)? Many thanks in advance for any help.

![image](https://user-images.githubusercontent.com/17013052/41009955-fb20eaca-68f9-11e8-84a7-73ed6dd82bdf.png)

**Comment by c9482** [comment]
Solved by adding "!important" attribute to my custom styles.

**Comment by dBianchii** [comment]
> Solved by adding "!important" attribute to my custom styles.

Thank you! Exactly what I needed
