### ISSUE TITLE
Serenity Issue -  Editor

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3619]
How should I add Editor attribute under client type.

**Comment by volkanceylan** [comment]
Start by reading guide.

**Comment by Shraddha996** [comment]
the link which is given in the ClientTypes.tt from guide can't open. It shows 404. NOT FOUND error

**Comment by Shraddha996** [comment]
we created tbl_OIS and tbl_OIS_tran In our customized Database same tables as orders and orders details from Northwind but It shows error while inserting products.

![screenshot 3](https://user-images.githubusercontent.com/39983941/41097584-21a9f196-6a76-11e8-9001-dd0cfdb1f260.png)
![screenshot 4](https://user-images.githubusercontent.com/39983941/41097587-23140b34-6a76-11e8-900d-15fe2c6a6dfb.png)
![screenshot 5](https://user-images.githubusercontent.com/39983941/41097588-24b1b28e-6a76-11e8-8e3e-1813a3d77336.png)
![screenshot 6](https://user-images.githubusercontent.com/39983941/41097590-2624b29c-6a76-11e8-8893-cdf7c00ff13b.png)
