### ISSUE TITLE
How  to resize the OrderDetailEditor

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#362]
Yesterday,I have followed your code to build an OrderDetailEditor successfully,But it is too small,I want to extend its width and height .How can I do it?

**Comment by volkanceylan** [comment]
See css in northwind.less for OrderDetailEditor

**Comment by ChenZhaobin** [comment]
Thank you ,another question,what is the meaning  of @h:@l: @e: 
.s-Dic_CountryDialog {
    > .size { .widthAndMin(650px); }
    .dialog-styles(@h: auto, @l: 150px, @e: 400px);
    .s-PropertyGrid .categories { height: 560px; }
}

**Comment by jsbUSMC** [comment]
Those are LESS variables

**Comment by volkanceylan** [comment]
Tab height, label width, editor width

**Comment by zerodev** [comment]
i like to use Flexify, Maximizable Attribute on EntityDialog
