### ISSUE TITLE
Unable to update to .NET Core 2.1

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#3621]
I switch my target framework from .NET Core 2.0 to .NET Core 2.1. When you go to build the `.csproj` file using `dotnet build` you are presented with in excess of 4,000 error stemming from the Serenity framework. Not sure if this has been reported yet or if it's currently being worked on.

I can provide a error log file upon request, but it's massive.

**Comment by volkanceylan** [comment]
Even though i don't expect any problems, you shouldn't update to a version that we don't update yet. So, if you are getting errors, you are on your own to solve any problems if any.

**Comment by williamhodges** [comment]
It was a test as I wanted to see if it supported it. I switched back to
2.0, just wanted to make you aware. That’s all.
