### ISSUE TITLE
How do I add a new view/controller in the same module

### ISSUE THREAD

**Issue by zillaitor** [volkanceylan/Serenity#3622]
I know that this should be simple, but please bear with me.
I have added the movie table and generated the code with Sergen. The page and dialogs all work without issue. 
How do I add a new view/controller in the same module while retaining the layout and search functions of the original movie page?
Basically, I would like to add pages to a module after running sergen, these pages should still maintain the search and sorting functionality that comes default with sergen, but I would like to run some filtering from the controller end before the data is sent to the view, for instance, show only movies in a particular genre.

**Comment by Estrusco** [comment]
You can override OnBeforeExecuteQuery in ListRequestHandle in repository and modify query. Or you can override setCriteriaParameter in your xyzGrid.ts file

```cs
 private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void OnBeforeExecuteQuery()
```

or 

```ts
        protected setCriteriaParameter() {
            super.setCriteriaParameter();

            this.view.params.Criteria = Serenity.Criteria.and(this.view.params.Criteria,
                     [[fld.YourField], '=', yourValue]);
       }
```

**Comment by ga5tan** [comment]
@zillaitor did u get the answer? You can run sergen  multiple times and add more pages/entities to module. You can also manually copy and hack/modify existing pages and have multiple forms/grids for one entity...
Just explore demo project

**Comment by zillaitor** [comment]
Thank you very much. This answers my question.
