### ISSUE TITLE
Exporting grid with conditional formatting to PDF

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#3623]
I created print css stylesheet like shown below but the generated PDF is not the same as the grid. Perhaps I need to use specific stylesheet?

I would appreciate any guidance on how to achieve this.

```
@media print {
  .property-cancelled {
    background-color: pink !important;
    -webkit-print-color-adjust:exact;
  }
  .property-sold {
    background-color: yellow !important;
    -webkit-print-color-adjust:exact;
  }
}
```
![image](https://user-images.githubusercontent.com/17013052/41119068-6f41a102-6a57-11e8-9118-b607999db5c3.png)

![image](https://user-images.githubusercontent.com/17013052/41119111-8d7c5bf8-6a57-11e8-8d95-15c686f038c3.png)

**Comment by c9482** [comment]
My project is kind of stuck on this. Is this something that can be resolved or do I need Plan B? Many thanks in advance.

**Comment by ga5tan** [comment]
I guess PDF is generated with this tool:
https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
so u may wanna check how to feed it your CSS ?

**Comment by Estrusco** [comment]
No, print of list are made client side with jsPDF. See PdfExportHelper in Modules -> Common - Reporting

**Comment by ga5tan** [comment]
IC,

well, he may also want to check about reports, where they are rendered via wkhtmltopdf
see function RenderAsPdf in  Modules\Common\Reporting\ReportController.cs
there are client helpers in Modules\Common\Reporting\ReportHelper.ts
and sample of use in Modules\Common\Reporting\ReportDialog.ts

**Comment by Estrusco** [comment]
Yes other reports are rendered with wkhtmltopdf that offers more possibilities of customization
