### ISSUE TITLE
Error while inserting products in Serenity 

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3626]
we created tbl_OIS and tbl_OIS_tran In our customized Database same tables as orders and orders details from Northwind but It shows error while inserting products.

![screenshot 3](https://user-images.githubusercontent.com/39983941/41097584-21a9f196-6a76-11e8-9001-dd0cfdb1f260.png)
![screenshot 4](https://user-images.githubusercontent.com/39983941/41097587-23140b34-6a76-11e8-900d-15fe2c6a6dfb.png)
![screenshot 5](https://user-images.githubusercontent.com/39983941/41097588-24b1b28e-6a76-11e8-8e3e-1813a3d77336.png)
![screenshot 6](https://user-images.githubusercontent.com/39983941/41097590-2624b29c-6a76-11e8-8893-cdf7c00ff13b.png)

**Comment by dfaruque** [comment]
delete `protected getIdProperty(){...}` and `protected getService() {...}` from your tbl_OIS_tran dialog.ts

**Comment by dfaruque** [comment]
see OrderDetailDialog.ts

**Comment by VictorTomaili** [comment]
Please update isssue with more specific title.

**Comment by Shraddha996** [comment]
we want to create order and order details module from northwind in our own customized database. we created same tables in our DB as well as compare each and every file from solution but it still showing error while inserting products

**Comment by Shraddha996** [comment]
even we tried the solution suggested by @dfaruque  but it didn't affect.

**Comment by Shraddha996** [comment]
This is the code for TblOisRow.cs and TblOisTranRow.cs files 
[TblOisRow.txt](https://github.com/volkanceylan/Serenity/files/2092606/TblOisRow.txt)
[TblOisTranRow.txt](https://github.com/volkanceylan/Serenity/files/2092607/TblOisTranRow.txt)

**Comment by dfaruque** [comment]
does your dialog extend form Common.GridEditorDialog?

**Comment by Shraddha996** [comment]
Yes. @dfaruque 
Am attaching that file just check once

[TblOisTranDialog.txt](https://github.com/volkanceylan/Serenity/files/2092999/TblOisTranDialog.txt)

**Comment by dfaruque** [comment]
see output window, is there any warning related to typescript?
if yes fix those.
to ensure typescript build you may delete ~/Scripts/site/xxx.web.js
then build.

**Comment by Shraddha996** [comment]
To, @dfaruque 
Thank You! Sir 
Its Working Now

**Comment by vssgkp** [comment]
I am facing same issue, Please help me.
<img width="912" alt="Screenshot_9" src="https://user-images.githubusercontent.com/89934690/132168824-cdb82d6c-e9fd-4b98-bcc0-fa661c11d066.png">
<img width="951" alt="Screenshot_10" src="https://user-images.githubusercontent.com/89934690/132168843-76e7a25c-8c95-48b9-b554-1de8f9fdb468.png">
<img width="957" alt="seren" src="https://user-images.githubusercontent.com/89934690/132168853-2a2ad710-6604-4c19-9f62-06a8bec1e74c.png">

**Comment by vssgkp** [comment]
<img width="957" alt="Screenshot_12" src="https://user-images.githubusercontent.com/89934690/132168970-40d03416-77e5-4762-ba0f-75538b8fd6e0.png">
