### ISSUE TITLE
MaskEditEditor

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#3627]
Benim sorum şu olacak. form şu şekilde yapıyoruz
 [MaskedEditor(Mask = "+9999(999)999 99 99"] fakat +90 olan  var +380 olan var bunu dinamik olarak nasıl ayarlayabiliriz şimdi bizim 4 karakter olacak sekilde ayarlı.

Kolay gelsin.

**Comment by brunobola** [comment]
See if this helps https://github.com/volkanceylan/Serenity/issues/2159
