### ISSUE TITLE
pdf size değiştirme...

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#363]
IHtmlToPdfOptions 'da width ve heigth  nasıl verebiliriz.

**Comment by volkanceylan** [comment]
24cm vs

**Comment by oaltay** [comment]
daha açıklayıcı olabilir misin.?
public void Customize(IHtmlToPdfOptions options)
{                   
          options.PageSize = "24cm";
}

gibi mi demek istedin.? ("A4" , "Letter") oluyor ama 24 cm olmadı.

**Comment by volkanceylan** [comment]
PageWidth PageHeight yok mu

**Comment by oaltay** [comment]
yok
sadece pagesize var

**Comment by volkanceylan** [comment]
O zaman CustomArgs.Add("--page-width"); CustomArgs.Add("20cm");

**Comment by oaltay** [comment]
Generated PDF file is empty! hatası veriyor. 

options.CustomArgs.Add("--page-width"); options.CustomArgs.Add("20cm");

**Comment by volkanceylan** [comment]
Bununla alakalı olacağını sanmam, errorlog a falan bakın

**Comment by oaltay** [comment]
wkhtmltopdf.exe 'de problem var.
.tmp dosyasını oluşturamıyor. 
ilgilendiğin için tşk.ler.
