### ISSUE TITLE
Is it possible to change entire styling of serenity applicaition

### ISSUE THREAD

**Issue by thomasmt** [volkanceylan/Serenity#3630]
How can we change the look and feel of serenity application to a new different custom style? For example change the style of grid, style of pop up, the layout structure etc. Thanks in advance

**Comment by volkanceylan** [comment]
Use CSS/HTML.

**Comment by thomasmt** [comment]
Sorry I did not understand what to do from your answer. Can you please explain little more and an example if possible?. I would like to know how to change the style of the grid, the create/edit form etc. I tried to apply custom styles as attributes in C# code, but that makes changes to only corresponding input control, but not able to change the label style. I need to change the style of the entire form. Could you please help me.

**Comment by dfaruque** [comment]
write css/less in site.less file under contents folder.
inspect element using your browser to get classes of the elements you want to style
