### ISSUE TITLE
Could not load file or assembly (After update Serenity)

### ISSUE THREAD

**Issue by euclidesgc** [volkanceylan/Serenity#3632]
Is anyone going through this too?
![problems](https://user-images.githubusercontent.com/12780402/41374122-b175c14a-6f28-11e8-8357-25bb714dddd6.png)

**Comment by volkanceylan** [comment]
Did you miss to update Serenity.CodeGenerator tooling reference in CSPROJ?

**Comment by adalberto-argente** [comment]
**I think so, would that be?**

![image](https://user-images.githubusercontent.com/8500507/41411658-f50d95d2-6fb3-11e8-82d9-28e269d7d634.png)

**Comment by euclidesgc** [comment]
I think so, would that be?


![image](https://user-images.githubusercontent.com/12780402/41411824-82c7f408-6fb4-11e8-9baf-2e80714352a4.png)

**Comment by volkanceylan** [comment]
Serenity.CodeGenerator reference
