### ISSUE TITLE
Help - After adding MovieDB module using sergen, I am getting error!

### ISSUE THREAD

**Issue by MoheebP** [volkanceylan/Serenity#3633]
![image](https://user-images.githubusercontent.com/16447947/41392107-77e8ef5e-6fc0-11e8-8557-4203262e2067.png)

UPDATE:-
I have committed getDefaultSortBy() method of LanguageGrid.ts file and the error disappeared!
Have I missed any thing during using sergen to generate MovieDB module?

**Comment by volkanceylan** [comment]
You probably forgot to add /// reference to some code that you wrote, ones that derive from GridEditorBase

**Comment by MoheebP** [comment]
ok, here is the hack for react related error. All error has gone after restart pc.
