### ISSUE TITLE
On the ServiceEndpoint classes, can you please specifically add [HttpGet] for Retrieve and List methods?

### ISSUE THREAD

**Issue by nootn** [volkanceylan/Serenity#3634]
Hi, I wanted to add Swagger to a project, which was quite simple using NSwag (E.g  https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag).  What this did was expose the swagger documentation for all the ServiceEndpoint classes.  However any methods that don't specifically define the HTTP Verb are ignored!

I believe all it would take is to make:

`

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRepository().Retrieve(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyRepository().List(connection, request);
        }
`

become:

`

        [HttpGet]
        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRepository().Retrieve(connection, request);
        }

        [HttpGet]
        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyRepository().List(connection, request);
        }
`

in the generated code, which shouldn't break anything, they are already GET's.
Cheers.

**Comment by volkanceylan** [comment]
No, it would break everything, they are not HttpGet, they can both be accessed by GET/SET. It's probably an issue that should be fixed in SWAG.

**Comment by nootn** [comment]
Hi thanks for pointing that out, I did some testing and they do need to support GET and POST to work.

Then I will just change it, this also works, it's good to be explicit about which HTTP Verbs are supported rather than leaving it open, so this fixes the swagger issue plus still seems to work in the application:

`

        [HttpGet, HttpPost]
        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRepository().Retrieve(connection, request);
        }

        [HttpGet, HttpPost]
        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyRepository().List(connection, request);
        }

`

Would you consider adding that to the code generator?

**Comment by dfaruque** [comment]
code generator support templating. so you could generate code as you like
here are some sample custom templates according to my preference
https://github.com/dfaruque/Serenity.Extra/tree/master/SerExtra/SerExtra.Web/Modules/_Ext/CodeGeneratorTemplates
you can take these and set the path as sergen's custom template under options.

**Comment by kilroyFR** [comment]
> Hi, I wanted to add Swagger to a project, which was quite simple using NSwag (E.g  https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag).  What this did was expose the swagger documentation for all the ServiceEndpoint classes.  However any methods that don't specifically define the HTTP Verb are ignored!
> I believe all it would take is to make:
> `
>     public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
>     {
>         return new MyRepository().Retrieve(connection, request);
>     }
> 
>     public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
>     {
>         return new MyRepository().List(connection, request);
>     }
> 
> `
> become:
> `
>     [HttpGet]
>     public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
>     {
>         return new MyRepository().Retrieve(connection, request);
>     }
> 
>     [HttpGet]
>     public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
>     {
>         return new MyRepository().List(connection, request);
>     }
> 
> `
> in the generated code, which shouldn't break anything, they are already GET's.
> Cheers.

Did you use NSwag for .netCore version or regular webApi ?

**Comment by kilroyFR** [comment]
@nootn any help ? i cannot see any serviceEndpoints
