### ISSUE TITLE
Serenity Stored Procedure

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3635]
Can I add Stored Procedure in Serenity Application?

**Comment by Estrusco** [comment]
https://github.com/volkanceylan/Serenity/issues/2745
https://github.com/volkanceylan/Serenity/issues/2593

and search in other issues

**Comment by dhyani081** [comment]
@volkanceylan Hi sir..I am new to serenity framework..I have gone through your unfiltered vedio on serenity but I want to add stored procedure in movie and movie cast so that data can print on html file...could you help me out

**Comment by VictorTomaili** [comment]
Hello @dhyani081 please use discussions for questions. And you can call stored procedure with dapper.
