### ISSUE TITLE
PopUp issue

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3636]
I have designed modules same as orders from Northwind but after clicking on new order it shows the result in PopUp window.
I want it same as orders from Northwind, what should I do?

![screenshot 14](https://user-images.githubusercontent.com/39983941/41404826-d0e49b60-6fe5-11e8-83fe-17f2511efcbe.png)

**Comment by Estrusco** [comment]
In dialog ts use decorator

    @Serenity.Decorators.panel()

**Comment by Shraddha996** [comment]
thank you. It works
