### ISSUE TITLE
Issue while Updating order

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3637]
I have created order module in my customized database and it is working fine but while updating existing record it does not show the product description which is added while creating the order.

![screenshot 15](https://user-images.githubusercontent.com/39983941/41407033-d2494324-6feb-11e8-8d93-a9482f2ef7c9.png)

**Comment by brunobola** [comment]
Use the [Lookupinclude] in xxxrow.cs and includecolumns=("DescriptionColumn") in master relation

**Comment by Shraddha996** [comment]
Actually, it does not show the product description while updating existing record

![screenshot 17](https://user-images.githubusercontent.com/39983941/41451190-5886737e-7089-11e8-8382-0dac03592cf0.png)

**Comment by Estrusco** [comment]
If Product Description in Row is an expression, set add attribute MinSelectLevel(SelectLevel.Always)

**Comment by Shraddha996** [comment]
thank you. Its working
