### ISSUE TITLE
Import From Excel

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3639]
Is there any way to Import all data from Excel sheet directly to Database Tables?

**Comment by edwardch** [comment]
You can check out the [ProductExcelImport demo](https://serenity.is/demo/BasicSamples/ProductExcelImport).

If you just need to load data once-off you can always just do it through Management Studio. Right click on the database > Tasks > Import data.

**Comment by Shraddha996** [comment]
I have created ImportExcel module by referring ProductExcelImport demo. But It shows error after clicking on import to excel button

![screenshot 18](https://user-images.githubusercontent.com/39983941/41463891-c139f11c-70b5-11e8-806a-81f88e8fd23b.png)

**Comment by ga5tan** [comment]
maybe try to build and Transform T4 ?

**Comment by Shraddha996** [comment]
Thanks! @ga5tan 
But after build and transform T4 still getting same error

**Comment by ga5tan** [comment]
maybe the name and case do not match ?
