### ISSUE TITLE
How to: Grid toolbar button like split buttons?

### ISSUE THREAD

**Issue by ZioZenigata** [volkanceylan/Serenity#3640]
Hello,
In my grid-toolbar I added these two buttons:

            buttons.push(bNet.Common.ExcelExportHelper.createToolButton({
                hint: 'Export',
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: ScheduleService.baseUrl + '/ListExcel',
                separator: true
            }));

            buttons.push(bNet.Common.PdfExportHelper.createToolButton({
                title: 'Export',
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));

Instead of having two buttons, how can I make a single button that contains the two functions above "Split buttons" style (example page: https://serenity.is/demo/AdminLTE/UIElements/Buttons)
Thanks in advance

**Comment by Estrusco** [comment]
See in wiki https://github.com/volkanceylan/Serenity/wiki/SplitButton-dropdowns

**Comment by ZioZenigata** [comment]
Thank you very much for your excellent answer!
