### ISSUE TITLE
How to save hour,minute and seconds in a datetime Field?

### ISSUE THREAD

**Issue by kanesunny** [volkanceylan/Serenity#3641]
Assuming we have a form containing a DateTime property, i found i can only pick a date, but sometimes i need the data including hour,minute and second, how can i fix it?  thanks

**Comment by kanesunny** [comment]
thanks for answering this question. can you tell me how to do it step by step?
when building the solution, it automatically transforms datetime field to a DateEditior.
1) i tried to write code to save the datetime, for example:

 this.form.AttendanceTime.set_value(Q.formatDate(new Date(), "yyyy-MM-dd HH:mm:ss")); 

unfortunately,it doesn't work. The datetiem field "AttendanceTime" only accepts the date and ignores the time.

2) After searching files in solution, i got bootstrap-datepicker.js and bootstrap-timepicker.min.js.  There is no bootstrap-datetimepicker in Serenity.

**Comment by dfaruque** [comment]
user `[DateTimeEditor]`  attribute on top of that field in Row.cs or Form.cs

**Comment by kanesunny** [comment]
cool, thank you, dfaruque
