### ISSUE TITLE
Publishing on IIS Server

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3642]
I want to publish my serenity application to IIS Server, what should I do?

**Comment by chadburnett** [comment]
I published to IIS without much issue.  Have you tried it?  Are you getting errors?

**Comment by chadburnett** [comment]
Just as a side note.  I see you've created a lot of issues recently.  Just a fair warning, this community is helpful and respectful.  However, we all react in a more helpful way when someone has put a bit of effort in.  If you have a question please take the time to read the docs, study the examples, and check here to see if it's been asked.

**Comment by WasimAhmad** [comment]
i am using IIS without any issue. can you tell what errors you are getting?
