### ISSUE TITLE
No lookup with key "Membership.Company" is registered.

### ISSUE THREAD

**Issue by ShaikBaresha** [volkanceylan/Serenity#3644]
No lookup with key "Membership.Company" is registered. Please make sure you have a [LookupScript("Membership.Company")] attribute in server side code on top of a row / custom lookup and its key is exactly the same.

I am trying to add one more field(Company) in "LoginRequest " as dropdownlist. 

Created custom lookup file like below.

[LookupScript]
	public class CompanyLookup : RowLookupScript<CompanyRow>
    {
        public CompanyLookup()
        {
		   IdField = CompanyRow.Fields.Wlcid.PropertyName;
                  TextField = CompanyRow.Fields.CompanyName.PropertyName;
		}

        protected override void PrepareQuery(SqlQuery query)
      {
            var fld = CompanyRow.Fields;
            query.Distinct(true)
              .Select(fld.Wlcid)
                .Where(
                  new Criteria(fld.Wlcid) != "" &
                    new Criteria(fld.Wlcid).IsNotNull());
        }
}

In Login request added below code.

[Placeholder("Company"), Required(true),LookupEditor(typeof(CompanyLookup))]
public string CompanyName { get; set; }

Company drop down not filling and i am getting above error message in login screen.

Thanks in advance...

**Comment by mafdy** [comment]
I think it's a permission problem, as the user isn't login yet, you can add     
[LookupScript(Permission = "*")]
 above your CompanyRow class.
by the way why you don't make it as  a type script class as a custom editor?

**Comment by ShaikBaresha** [comment]
@mafdy Thanks for your response. I have tried changing permission,but no luck.Still i am getting same error message.
I am new to SERENITY.Can you please explain me how to make this work with typeScript class.

**Comment by ga5tan** [comment]
maybe try to build and Transform T4 ?

**Comment by ShaikBaresha** [comment]
@mafdy  Thanks for editor example. Yes this is working fine after login to site.But in login page it's not even showing dropdown.

![image](https://user-images.githubusercontent.com/40324130/41720185-e69c39a0-757f-11e8-9c7d-a2d1067ae721.png)
I tried to adding below code then..
[Required(true), LookupEditor(typeof(CompanyEditorAttribute))]
public string CompanyName { get; set; }

This is also showing error like Lookupscript in included...

**Comment by ga5tan** [comment]
on login page u need to give script * privileges!!!

**Comment by ShaikBaresha** [comment]
I did every possible thing.I don't know what i am missing here.Still i am getting same message.

Is anyone implemented Editor in Login Screen??

**Comment by volkanceylan** [comment]
Login page is implemented differently to be slimmer so you can't simply use some widgets, lookups etc. there.

Try adding this on bottom of _LayoutSlimHead.cshtml:

```html
<script type="text/javascript">
    @Html.Raw(DynamicScriptManager.GetScriptText("RegisteredScripts"))
</script>
```

**Comment by ShaikBaresha** [comment]
@volkanceylan Thank you sooo much...It's worked like charm...
