### ISSUE TITLE
Paging Issue

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3651]
I have created application in my own customized database and inserted multiple records in it but it shows error to paging.

![screenshot 21](https://user-images.githubusercontent.com/39983941/41641117-d10b48dc-7481-11e8-8445-6ff64e516206.png)

**Comment by hannesb** [comment]
Setting [Dialect](https://volkanceylan.gitbooks.io/serenity-guide/content/setting-connection-dialect.html) might help

**Comment by volkanceylan** [comment]
Yes, check dialect topic in guide.
