### ISSUE TITLE
Upload Files

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#3653]
I have a child entity ,when I try to insert record after upload any file ,screen show this error

Query affected 0 rows while 1 expected! This might mean that your query lacks a proper WHERE statement or a TRIGGER changes number of affected rows. In the latter case, you may try adding "SET NOCOUNT ON" to your trigger code.

and it is working without any problem at update   or  insert without uploading the file 
please advise.

**Comment by amrgDev** [comment]
yes, I saw it
inserting any new record with upload any file issue this error and works fine at updating.

**Comment by chadburnett** [comment]
Sorry, I don't quite understand the issue.  Can you provide more information and some code?  I haven't run into any issues with file uploads.

**Comment by amrgDev** [comment]
Yes I saw it,
my entity works at update but not work when Insert new record
just I add this attribute to the property **ImageUploadEditor**

**Comment by amrgDev** [comment]
to upload files , I added this attribute  [**FileUploadEditor**("Files/~")]
to a property in my entity
when I try to insert any record after upload the file by the file uploader control , it issue an error
and works without problem when update the record.

here is my code
[DisplayName("File Id"), Column("FileID"), Size(250),FileUploadEditor("Files/~")]
        public String FileId
        {
            get { return Fields.FileId[this]; }
            set { Fields.FileId[this] = value; }
        }

**Comment by chadburnett** [comment]
Code in Row.cs
'        [DisplayName("Sds Files"), Column("SDSFiles")]
        public String SdsFiles
        {
            get { return Fields.SdsFiles[this]; }
            set { Fields.SdsFiles[this] = value; }
        }


public StringField SdsFiles;
'

Code in Form.cs
'
[FileUploadEditor]
        public String SdsFiles { get; set; }
'

I just tested and it works fine.  Perhaps, you are using the FileUploadEditor in the wrong spot?

**Comment by amrgDev** [comment]
Thank you chadburnett 
Yes , FileUploadEditor should be in Form.cs Code.

**Comment by imismaindra** [comment]
> FileUploadEditor

but the file will saved in temporary

> Code in Row.cs
> 
> ```
> [DisplayName("Sds Files"), Column("SDSFiles")]
> public String SdsFiles
> {
>      get { return Fields.SdsFiles[this]; }
>       set { Fields.SdsFiles[this] = value; }
> }
> 
> public StringField SdsFiles;
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> Code in Form.cs
> 
> ```
> [FileUploadEditor]
> public String SdsFiles { get; set; }
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> I just tested and it works fine. Perhaps, you are using the FileUploadEditor in the wrong spot?

but the file/image will saved in temporary folder
