### ISSUE TITLE
Accessing lookup from serverside 

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#3656]
In typescript, we have the following to get a lookup item by its id
`someRow.getLookup().itemById[key]`

Is there something similar for c#?

**Comment by Estrusco** [comment]
There is retrieve service of repository

```cs
Retrieve(connection, new RetrieveRequest { EntityId = key })
```

**Comment by dfaruque** [comment]
Thank you @Estrusco 
But Retrieve in repository requires read permission and it unnecessarily retrieved all columns with details although that could be handle.

and of course it is not that super handy like this `someRow.getLookup().itemById[key]`

**Comment by Estrusco** [comment]
You can also use SqlQuery object and construct your query. Make a method like this

```cs
public MyRow ItemById(int id)
{
     MyRow result = null;

     using (IDbConnection connection = SqlConnections.NewFor<MyRow>())
     {
         result = connection.Single<MyRow>(q =>
         {
             q.SelectTableFields();

             q.Where(new Criteria(MyRow.Fields.Id) == id);
         });
    }

    return result;
}
```

**Comment by dfaruque** [comment]
Thank you very much. @Estrusco  for your time and cooperation.

**Comment by mafdy** [comment]
To achieve this; you need to use Dapper. For example,
```c#
    using (IDbConnection connection = SqlConnections.NewFor<Entities.CourseRow>())
    {
        var _course= connection.TryById<Entities.CourseRow>(/*key*/);
    }
```
Also LINQ can be used to handle your Criteria perfectly.
This is just my opinion, hope it helps.
Best regards

**Comment by dfaruque** [comment]
Thank you @mafdy
