### ISSUE TITLE
Entity Dialog as Panel örneğinde HtmlContentEditor çalışmıyor

### ISSUE THREAD

**Issue by BurakPamuk** [volkanceylan/Serenity#3658]
Merhabalar. Entity Dialog as Panel örneğindeki gibi bir form ekranım var ve  HtmlContentEditor kullanmak istediğimde o form elemanını resimde görüldüğü gibi CKEditor olarak değil Text Area olarak ekliyor. Farklı bir sorun da Volkan bey this.form.HtmlContent.element.triggerHandler('shown'); kodunu kullanılmasını söylemiş denedim fakat başarılı olamadım. 

![image](https://user-images.githubusercontent.com/17962986/41718595-12fb663e-7566-11e8-9af8-28c7a43db473.png)

![image](https://user-images.githubusercontent.com/17962986/41718653-40508b0a-7566-11e8-8b2a-fa4511904393.png)

Sorun ile ilgili düzenlemem gereken kısım ya da farklı bir yöntem tavsiyeniz varsa yardımcı olursanız sevinirim.

**Comment by volkanceylan** [comment]
Gösterdiğiniz Serene örneği, kendi formunuzda HtmlContentEditor koyduysanız ve Form.cs de ezmediyseniz gelir. Script hatası var mı kontrol edin. Lütfen ingilizce yazınız.
