### ISSUE TITLE
Detail grid editing

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#366]
![untitled](https://cloud.githubusercontent.com/assets/16621563/13532478/e981d626-e255-11e5-860b-02174c4ede8b.png)

I have enable some fields for editing in detail grid following your product grid in northwind sample.

Everything works great but it does not save.

Please give some work around.

With kind regards
Faruque

**Comment by volkanceylan** [comment]
That sample was working with pending queue. When something changes in editors, listening to change events, you should take value and directly set in item, and call view.UpdateItem()

**Comment by swordz36** [comment]
How did you get your layout to be in columns like bootstrap.

**Comment by dfaruque** [comment]
Thank you

**Comment by dfaruque** [comment]
@swordz36 follow multicolumnsample in latest serene template.
