### ISSUE TITLE
Tenant Per DB support

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#3661]
In the guide documnet, there is already a tutorial about **multi tenancy**, It's great for the **standalone app** architecture, 

But recently my project needs to **shard DataBase** by tenant Id, every tenant has an independent database, and one connection key may map to different connection strings.

I find it diffcult to handle this with Serenity, as I can not overrite static methods ` public static ConnectionStringInfo TryGetConnectionString(string connectionKey)` in  **Serenity.Data.SqlConnections**.  

Does anyone meet this before?
I would appreciate any guidance.

**Comment by ga5tan** [comment]
why not make separate installs (like one app one DB) ?

**Comment by Estrusco** [comment]
You can use IIS location functionality and virtual directory

```xml
<configuration>
  <location path="customer1">
    <connectionStrings>
         [...]
    </connectionStrings>
  </location>
  <location path="customer2">
    <connectionStrings>
         [...]
    </connectionStrings>
  </location>
</configuration>
```

https://serverfault.com/questions/713152/how-can-i-split-out-connection-strings-for-an-iis-site-but-maintain-a-shared-ap

**Comment by volkanceylan** [comment]
thanks @Estrusco

**Comment by adalberto-argente** [comment]
And how about Dot Net Core? (appsettings.json)

**Comment by Mohammad-Yasfo** [comment]
Does anyone have an example of MultiTenancy with core 2.x?

**Comment by ShifanilaSenthil** [comment]
> And how about Dot Net Core? (appsettings.json)

Did you receive any answers to your question?
