### ISSUE TITLE
How to Fetch Username in Textbox

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3662]
I want to fetch Username in a textbox field when the page loads. Is there a way to do it in Serenity?
Or Can I use Sessions for it?

**Comment by Shraddha996** [comment]
@Estrusco  can u please elaborate this? or is there any reference link regarding this?

**Comment by Estrusco** [comment]
If you want to display username in a textbox of your dialog, you can set field in constructor or afterLoadEntity of your xyzDialog.ts

```ts
   protected afterLoadEntity() {
         super.afterLoadEntity();

         Serenity.EditorUtils.setValue(this.form.YourField, Authorization.userDefinition.Username;
   }
```

**Comment by Shraddha996** [comment]
thank you @Estrusco sir, Its working now
