### ISSUE TITLE
Roadmap 2018

### ISSUE THREAD

**Issue by rcmsoftwaredevelopment** [volkanceylan/Serenity#3663]
Hi Volkan

Thank you for your continued support.  We are six months on since the last road map topic was raised and from your last comments back in December I would like to revisit the road map for the year ahead so we can keep the carrot dangling in front of us when it comes to feature requests for Start#.  Here are the features from December 2017.

* Premium Themes (will try to get some popular themes integrated, but need to sort out licencing issues, in worst case it will be only a how-to document, e.g. how to apply Metronic, Limitless, Remark etc.)
* Survey module (like Google Forms, already implemented for some other project, will port into SS)
* Mobile native application samples for IOS / Android (will show how to call services, implement some of Northwind there, limited offline functionality / sync will come later, currently developing an app for a client)
* Push notification queue, and integration with APNS / Firebase
* Finalize Meeting module with Agenda, Decisions, SSRS report output, and Outlook calendar invitation
CMS (did this years ago but need to check modern ones and get best parts out of them)
* E-Commerce (our new dev Alper is very reluctant on this)
* Better docs for premium

Are there any new features that you are thinking of implementing and a timescale if known for any of the above.  

Best regards

Ray

**Comment by volkanceylan** [comment]
Premium themes are done, also did some work on meeting, SSRS and invitation is pending. 

Roadmap is now in GitHub projects:

https://github.com/volkanceylan/Serenity/projects/1

I also have a longer list in a private GitHub repo, which i'll be transferring to this project page soon.
