### ISSUE TITLE
assign values to multiple fields

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3664]
how to assign same values to multiple fields in 1 form ?
we  have created detail module and in the form we are going to display same value to two different fields
(quantity and pending quantity)  is there any way to figure out the issue

**Comment by chadburnett** [comment]
I think this example should get you started.

[https://serenity.is/demo/BasicSamples/PopulateLinkedData](https://serenity.is/demo/BasicSamples/PopulateLinkedData)

**Comment by AbhishekhHugar** [comment]
i meant to say is if i enter some quantity the same value should be stored in pending quantity and the pending quantity should not be editable

**Comment by AbhishekhHugar** [comment]
fixed by adding  row.PendingPrQuantity = row.Quantity; in editor.ts
