### ISSUE TITLE
How to reflect same value on multiple fields

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3665]
I have created a module detail  and in that table, there are fields like quantity and pending quantity
so when I'm going to save the quantity at that time it should reflect same value in pending quantity field also.
Is it possible in serenity??

**Comment by chadburnett** [comment]
Hello! 
Have you seen this?
[https://github.com/volkanceylan/Serenity/issues/3664](https://github.com/volkanceylan/Serenity/issues/3664)
