### ISSUE TITLE
SignUpPanel error

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3666]
Dear,
I'm finding an error in the registration form, in the field to confirm the email and password, as shown in the image.
Inform you that the property of confirming email and password does not exist.
How to solve?
![image](https://user-images.githubusercontent.com/7516443/41791232-8c8bb164-762b-11e8-9dc3-31343d30904c.png)
![image](https://user-images.githubusercontent.com/7516443/41791253-9a9455fe-762b-11e8-90ea-43b75d3a2e6c.png)

**Comment by ga5tan** [comment]
seems like fields do not exist in your form. try to comment out code with errors (whole constructor)
and compile and T4
then uncomment and see if it's without error

**Comment by juliermefelix** [comment]
I tried, but the error remains.

**Comment by alexsandrocruz** [comment]
Same problem here. 
I can't create new users with actual version of Serenity.

Someone can help us, please?

**Comment by ga5tan** [comment]
is this new app generated by Serenity recently? I have older one and latest packages and all works...

**Comment by juliermefelix** [comment]
I am using the latest version.
What I did was start over another project.
So far everything is OK.
