### ISSUE TITLE
Defaulting dialog to open as maximized

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#367]
I am trying to have a dialog open up maximized, I have tried to override UpdateInterface but that is not working, is this even possible to do?

**Comment by dfaruque** [comment]
Put [Maximizable] attribute on top of your dialog. and put this method 

        protected override void OnDialogOpen()
        {
            J(".ui-dialog-titlebar-maximize").Click();
            base.OnDialogOpen();
        }

**Comment by swordz36** [comment]
Thanks for the info that is exactly what I wanted.
