### ISSUE TITLE
Upload Path

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#3671]
Hello,
I want to upload files to a remote server. Below is my path to the remote server but the files are not being saved to the folder.

**add key="UploadSettings" value="{ Path: '208.118.63.210\\root\\home\\designworks-001\\www\\site1\\' }"**

This is the folder for the files in the Row class

        [DisplayName("File Upload"), Column("ppb_filename"), Size(-1), FileUploadEditor(FilenameFormat = "sitedocuments/publishingdocs/~")]
        public String PpbFilename
        {
            get { return Fields.PpbFilename[this]; }
            set { Fields.PpbFilename[this] = value; }
        }

What am I doing wrong?

**Comment by volkanceylan** [comment]
Do you know network paths start with \\, if it is not network share, it won't work.

**Comment by mijaved** [comment]
The network path such as `\\FileServer_Name-or-IP\Upload`,  must shared and given read-write permission to IIS_IUSRS user and must be accessible from Application Server; in my case it was `\\TVLLAP36\upload`
![FileUpload](https://user-images.githubusercontent.com/5019196/81526198-c9401480-9378-11ea-9ef0-ab1bfbd4440f.png)

Most important is providing path in web.config with appropriate escape character
`<add key="UploadSettings" value="{ Path: '\\\\FileServer\\upload\\' }" />`
