### ISSUE TITLE
BUG? Header's Hint in Grid column

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3674]
Is it possible somehow to have column header and hint ?
There is some kind of autohint feature - when column is too narrow for header to be displayed in full
but  I need to prevent it with short Header, that fits and long hint displayed on hover over

**Comment by ga5tan** [comment]
Could it be a bug? I set a hint for column, but that is not being set to SlickGrids ToolTip

**Comment by volkanceylan** [comment]
Hint only used for form

**Comment by ga5tan** [comment]
Thanks @volkanceylan for getting back to me. So it's feature then. Since there is Hint attribute in Column.cs file, -if I may suggest- why not transfer hint of the Column to toolTip of the SlickGrid column?

I work around like this for now (but I feel there is such a 'little' step required:

```
protected getColumns() {
            var c = super.getColumns();

            c[Q.indexOf(c, x => x.field == UsersRow.Fields.FieldWithLongCaption)].toolTip = "Very long hint/tooltip, different from Column header";

            return c;
        }

```

**Comment by volkanceylan** [comment]
Hint is only useful in a form, and a hint in a form might not be meaningful for a hint at a column. You may do as you show though.

**Comment by ga5tan** [comment]
But I can make Hint in column.cs, which is for grid? (at least Visual Studoi shows me, there is Hint). Why not make it work? just a suggestion. It is supported by slickgrid and you make it seem like it's supported in Columns.cs... It is just logical extension. Just my 2 cents. You wanna make it declarative on one hand and on other hand you want this simple Form supported feature to go in wain, because of what? Answer this simple Q and u will see...

**Comment by volkanceylan** [comment]
Its your opinion and i said no
