### ISSUE TITLE
Issue after Hardcoded dropdown selection

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3677]
getting an error while selected any items from the dropdown

![screenshot 33](https://user-images.githubusercontent.com/39983941/41966140-04504504-7a1c-11e8-815e-e586f2289118.png)

**Comment by AbhishekhHugar** [comment]
Even i am having the same issue  does anyone have solution for this?

**Comment by volkanceylan** [comment]
Check if your row has a string field, if it is Integer than your hardcoded values should be integer.
