### ISSUE TITLE
Redirect Form

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3679]
I want to ask a simple question, that how to redirect from one form to another form.
I refer many previous issues but didn't get the exact solution
Please help me in that

**Comment by ga5tan** [comment]
you can put hyperlink somewhere in grid or form, or via pushing a button ?

**Comment by Shraddha996** [comment]
@ga5tan  thanks for the reply
I have created a new button on my form by the following code

protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();

            buttons.push({
                title: "OpenPO",
                hint: "Another date picker",
                cssClass: "'dd-note-button",
                onClick: () => { }
            })
            return buttons;
        }

Now I want to open a new form on that button click.
Please suggest.

**Comment by ga5tan** [comment]
you can open dialog like this:
this.paymentDialog.loadNewAndOpenDialog(true); 

or this:
dialog.loadEntityAndOpenDialog(item);

seach for opendialog in sample app (Serenity)

**Comment by Shraddha996** [comment]
@ga5tan  I just tried 
 this.TblPoTranDialog.loadNewAndOpenDialog(true);
![screenshot 38](https://user-images.githubusercontent.com/39983941/42146866-4bc8dbba-7de8-11e8-9bb1-51b66f38099f.png)
Above code and the dialog I want to open on drop-down selection is TblTranDialog so I put this in my code and built it but it showing error on NewTblPo button click.
![screenshot 39](https://user-images.githubusercontent.com/39983941/42146879-5e57c6ce-7de8-11e8-8ecf-fe634d7d1bab.png)

**Comment by volkanceylan** [comment]
new TblPoTranDialog().loadNewAndOpenDialog(true);
