### ISSUE TITLE
Validation.InvalidFormMessage (message at Login)

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#3680]
Hi all,

I reopen the issue n. [3124](https://github.com/volkanceylan/Serenity/issues/3124), because my (and I think also ours) problem is that: when I click the Login Button without enter username and password, it gives me an error:

![34575471-358977be-f17b-11e7-8508-15b466f1ac35](https://user-images.githubusercontent.com/22232670/42039709-4efb1840-7aee-11e8-9068-33bf1bd891ea.png)

I check my translations json files and all is correct.

Could you please help me ? 

Thanks all for your time :)

Chiara

**Comment by kjaraa** [comment]
Any help ?

Thanks all

**Comment by volkanceylan** [comment]
Find this part in your web.config:

Login: [ 'Forms.Membership.Login.', 'Db.Administration.User.', 'Validation.Required', 'Dialogs.' ]

Replace it with:

Login: [ 'Forms.Membership.Login.', 'Db.Administration.User.', 'Validation', 'Dialogs.' ]

**Comment by kjaraa** [comment]
Thanks you very much @volkanceylan :)

Chiara
