### ISSUE TITLE
Hide Navigation Menu Item Based on User Role 

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#3681]
Hello,

I have created three roles as Admin,Store and production and two users admin [Role : Admin ], TechAspirant [Role : Store ], I want to hide only customer navigation menu item if I sign in with user having store user role. Please guide me how can I achieve this.

**Comment by dfaruque** [comment]
put the appropriate permission-key in row.cs
open the role you want to modify permission.
click on "Edit Permissions" button
then grant or revoke some permission keys

read guide for more...

**Comment by TechAspirant** [comment]
Thanks, Done It Worked
