### ISSUE TITLE
radio button click open form 

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3682]
hey,
  i could have  issue like i have a dropdown which has hardcoded values like open Po,imported ,indigenous and based on those respective values different form should get open eg-if i select open po then open po form should get opened ,if i select imported then imported form should get opened etc, i tried doing this using hardcoded dropdown but cant get any results ,so even the use of radio buttons could work.

thankyou in advance

**Comment by dfaruque** [comment]
you have to write the code in constructor of Dialog.ts
like this

```
this.someEditor.change(e=>{ 
let  selectedValue =  this.someEditor.value;

if (selectedValue == "bla")
new someDialog().dialogOpen(); 
else
new anotherDialog().dialogOpen();

});
```

**Comment by AbhishekhHugar** [comment]
hey @dfaruque 
i tried the code suggested by you ,error is generated while create new form it doesnt even redirect to the drop down selection page
![screenshot 40 e](https://user-images.githubusercontent.com/40484328/42147552-0203ab1e-7dec-11e8-8456-2c516ebc364a.png)
![screenshot 41 e](https://user-images.githubusercontent.com/40484328/42147554-0230c54a-7dec-11e8-84ac-0930fa338bfe.png)

**Comment by Estrusco** [comment]
Your radio is an editor in form. Then, you must use this.form.YourRadio.

What is TblPoEditor: any declared in top? Where you have instantiated? If you expect this work, I recommend you read guide before.

**Comment by AbhishekhHugar** [comment]
@Estrusco  not radio button its a hard coded dropdown  and based on the selection of the  drop down value respective form is created.
![screenshot 7](https://user-images.githubusercontent.com/40484328/42150183-93403502-7df6-11e8-973e-99b15a89e810.png)

**Comment by Estrusco** [comment]
If you have created an editor, first of all you must execute T4 transformation. This make for you an TblPreEitorAttribute. You can use this in form.cs over the field that you want to use with this editor, and then use this.form.yourFieldWithEditor.

See sample
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Editors/SelectWithHardcodedValues 

and see that in form is used the attribute

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Editors/SelectWithHardcodedValues/HardcodedValuesForm.cs

**Comment by AbhishekhHugar** [comment]
E:\Serene(26-06-2018)Indentors\Serene1\Serene1.Web\Modules\PurchaseOrder\TblPo\ i did this way i also did t4 transform there is an error for tblpoeditor in dialog, i tried but the dialog cannot get reference of editor

**Comment by Estrusco** [comment]
First of all, in your code 

```ts
if (selectedvalue = "OpenBo") 
etc...
```

there is an error. You make an assignment. If you want to test use double equal

```ts
if (selectedvalue == "OpenBo") 
etc...
```

Remove from editor getColumnKey, getDialogType and getLocalTextPrefix. 

Also your test on selected value is outside constructor and outside function. This is an error.
Also you haven't associated it with an event. You have to revisit your code

**Comment by Shraddha996** [comment]
Hi @Estrusco sir, Am commenting here because my issue is related to this,
actually, I have created a module called TblPo with the two dialogs and two forms
And I want to open TblPoDialog1 from TblPoDialog
Is this possible in serenity?
![screenshot 42](https://user-images.githubusercontent.com/39983941/42159363-208156ac-7e11-11e8-85b1-f790250be1b2.png)
this is the screenshot of my code

**Comment by Shraddha996** [comment]
Hey @Estrusco,
I want to hide and show form with help of dropdown selected value? 
Could you please help me out with this?

OR ELSE

I want to redirect to Dialog of same module and same form. Is there any solution on this?

**Comment by volkanceylan** [comment]
This is not a Serenity issue, you need to learn some TypeScript / Javascript, please continue in Slack / StackOverflow, or try reading some programming guide for TS.
