### ISSUE TITLE
How to show in UPPER CASE All my string fields on a grid?

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3684]
I want to show all my string fields on my grids always in UPPER CASE.
I have to override "MyListHandler"? Anyone have some sample to guide me?

Thanx in advance

**Comment by dfaruque** [comment]
use this in the field you want to 
`[CssClass("text-uppercase")]`

**Comment by javaman63** [comment]
THANXX!!!! @dfaruque It works!

You're a life saver!
