### ISSUE TITLE
Group controls on Form

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3686]
Is there any way to group bunch of controls/fields/edits together, so that they can be hidden or shown depending on internal logic?
Something like Panel used to be in asp.net

**Comment by Estrusco** [comment]
There are categories and collapible attribues for form fields.

     [Category("Text of category"), Collapsible(Collapsed = false)]

**Comment by ga5tan** [comment]
THX @Estrusco 
It looks fine. Any idea  how to control collapsing programmatically (from TS)?
Say on button click

**Comment by fwd079** [comment]
> THX @Estrusco
> It looks fine. Any idea how to control collapsing programmatically (from TS)?
> Say on button click

This [wiki link](https://github.com/volkanceylan/Serenity/wiki/UI:-Hide-Form-Categories-then-Show-on-Field-Trigger) might help.

Regards.
