### ISSUE TITLE
How to Send Data from Module to _Layout.cshtml

### ISSUE THREAD

**Issue by rezafd23** [volkanceylan/Serenity#3687]
hello there

is there anybody can help me how to pass data from modules to _Layout.cshtml
![image](https://user-images.githubusercontent.com/31206753/42144640-60ce0eba-7de6-11e8-9fa8-3e205e12e5fd.png)
i want to set data from database to that notification, but the data from module can't be called at _Layout.cshtml

do you have any solution my dear @volkanceylan 
thanks

**Comment by Estrusco** [comment]
See how works dashboard for Open Orders, Closed Orders, ect. 
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Dashboard/DashboardPage.cs

**Comment by rezafd23** [comment]
@Estrusco 
Yeah i've tried that but that example is for passing data in the same directory, what about in the different directory?

**Comment by Estrusco** [comment]
What mean different directory? If you mean same controller, you can call action method of another controller using RedirectToAction()

But this is MVC related, no a Serenity issue.

**Comment by rezafd23** [comment]
@Estrusco what i mean for different directory is how i can call method form "Pesanpage.CS" to "_Layout.cshtml", i've tried  that example for "PesanIndex.cshtml" and it works, what about that?

**Comment by Estrusco** [comment]
mmm....
In _Layout.cshtml you can call 

```cshtml
@{Html.RenderPartial(MVC.Views.PesanIndex);}
```

and retrieve data directly in razor page, or some like this...

```cshtml
    var row = new YourController().Retrieve(connection, new Serenity.Services.RetrieveRequest()
    {
        EntityId: xxxx
    });
```

**Comment by rezafd23** [comment]
thanks man @Estrusco  it's work!
