### ISSUE TITLE
how to make details readonly in master-detail-relation?

### ISSUE THREAD

**Issue by kanesunny** [volkanceylan/Serenity#3688]
![default](https://user-images.githubusercontent.com/8517144/42145132-fe473f44-7df1-11e8-83b4-16fcd450d069.png)
is there an easy way to remove the link? thanks.

**Comment by vinaykulkarni89** [comment]
Remove editlink attribute on ProductName property from colums.cs

**Comment by kanesunny** [comment]
vinaykulkarni89, thanks. sorry, i didn't describe the problem exactly. In one scenario,  the employee creates the order. He needs the editlink to open a product dialog. But in another scenario, the officer audits this order. He shouldn't click on this editlink. So my question is "do we have an easy way to remove editlink attribute" In scenario 2? for example, by using jquery or coding in order_dialog.ts?

**Comment by volkanceylan** [comment]
Try writing a column formatter

**Comment by vinaykulkarni89** [comment]
Do you need to remove edit link attribute depending on the permissions?

**Comment by kanesunny** [comment]
volkanceylan, thank you.
vinaykulkarni89, the solution in #2609 is cool. thank you very much.
