### ISSUE TITLE
Cannot setequality

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#369]
Hi Jaiq,

I want to filter grid when first load but it's not work filter grid with null value, any suggestion?

SetEquality("ApprovalDate",  null);

        protected override bool OnViewSubmit()
        {
            if (!base.OnViewSubmit())
                return false;

            SetEquality("UserID", Authorization.UserDefinition.UserId);
            SetEquality("ApprovalDate",  null);

            return true;
        }

**Comment by volkanceylan** [comment]
SetEquality doesn't work with null values. Null and empty string is simply ignored. As leaving a searchbox with empty value doesn't filter.

Try this:
```
((ListRequest)this.View.Params).Criteria &= new Criteria("ApprovalDate").IsNull()
```

**Comment by rudianto2008** [comment]
It works thanks Jaiq.

Regards
Rudianto
