### ISSUE TITLE
In background work Authorization.UserDefinition is null

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#3690]
Hi all!

In my procedure I use HostingEnvironment.QueueBackgroundWorkItem for background work, but when I try to access to (UserDefinition)Authorization.UserDefinition this is null.

Anyone has experimented this before?

**Comment by volkanceylan** [comment]
It's expected to be null, users are only valid for requests, any other thread would return null

**Comment by Estrusco** [comment]
Ok, I had thought this.

Any contraindications if I pass userdefinition at background method?

**Comment by volkanceylan** [comment]
Probably shouldn't be a problem

**Comment by Estrusco** [comment]
OK thank you @volkanceylan
