### ISSUE TITLE
EditFilter [Column] with all RowFields available

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#3691]
Hey all,

is there a better way to show all values from xyzRow in the xyzColumn edit filter.

My solution is to call all properties in the xyzColumn with the Hidden attribute, but that is definitly not the way to do it.

Any suggestions?

**Comment by volkanceylan** [comment]
If you don't want them to be shown as columns, put [FilterOnly] instead of [Hidden], other than that only columns in Columns.cs can be filterable.

**Comment by Garozh** [comment]
Thank you very much, that is what I was looking for.

**Comment by stixoffire** [comment]
Any way to apply this FilterOnly attribute when a QuickFilter has been selected ? So my quickfilter has no value and all my columns appear but when they select a filter option - the filtered column I want to be hidden at that moment?
