### ISSUE TITLE
Issues with Promise.

### ISSUE THREAD

**Issue by Febriantos** [volkanceylan/Serenity#3694]
It seems there are some issues with promise on chrome.

Uncaught (in promise) {message: "Could not establish connection. Receiving end does not exist."}

Please go to https://serenity.is/demo/
And check with Chrome > DevTools.

![image](https://user-images.githubusercontent.com/20570367/42193705-f193749c-7e24-11e8-8948-bd226bc145e0.png)

**Comment by volkanceylan** [comment]
I don't have such. Those are probably caused by your Chrome extensions.

**Comment by Febriantos** [comment]
Yes, you are correct. My bad. I tried using another computer and I don't have that issue. Thanks.
