### ISSUE TITLE
How to Activate React in my Serene Project

### ISSUE THREAD

**Issue by uwascan** [volkanceylan/Serenity#3695]
Hello @volkanceylan , please can you give me guide lines on how to activate React in Serenity Platform project (Community edition)

**Comment by volkanceylan** [comment]
React is only available in StartSharp

**Comment by uwascan** [comment]
Why do I keep getting the following error after installing @types/react as suggested by you?
```
typings/serenity/Serenity.CoreLib.d.ts:1252:31 - error TS2503: Cannot find namespace 'React'.
1252         editorType?: string | React.ComponentType<any>;
```

**Comment by volkanceylan** [comment]
You should read upgrade guides before upgrading.

**Comment by uwascan** [comment]
I created a new dotnet core  project using serin cli so I doubt if the upgrade guide applies here because it is a brand new project using the latest version of serin.

**Comment by undyingkevin** [comment]
in my Serene Project, Can I use react? Do I have to just use StartSharp?
