### ISSUE TITLE
How to Create Report?

### ISSUE THREAD

**Issue by rezafd23** [volkanceylan/Serenity#3696]
do somebody can help me how to create report page like this? is this generate with tool like sergen? or is it created manually?
![image](https://user-images.githubusercontent.com/31206753/42204173-21afacee-7ecb-11e8-9672-9020e2068b37.png)

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Northwind/Reports
