### ISSUE TITLE
Can I use my joining table to filter out items in a select list?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#370]
I am trying to mimic a one to one relationship, I need to remove an item from a select list if it is already assigned, is that possible in serenity? I am still figuring out all the configurable areas so forgive me.

**Comment by volkanceylan** [comment]
You need to subclass LookupEditorBase class, add custom logic to filter in GetItems method

**Comment by volkanceylan** [comment]
There is a custom editor sample to filter under Basic Samples of Serene
