### ISSUE TITLE
DisplayFormat percentage works good in grid but not in Excel

### ISSUE THREAD

**Issue by qprotex** [volkanceylan/Serenity#3702]
In my columns file I have the following field:

```
[DisplayName("PD"), Width(100), DisplayFormat("#,##0.00%")]
public Single Pd { get; set; }
```

These are the PD values in the database
![DB](https://i.imgur.com/SoSnRP1.png)

Those values lookgs good in the grid using the DisplayFormat:
![Grid](https://i.imgur.com/zymC4OX.png)

But in Excel, for some reason they look like this:
![Excel](https://i.imgur.com/7cPCq4f.png)

I have US OS, Excel and Browser and in web.config I am using en-US:
`<globalization culture="en-US" uiCulture="en-US" />`

I am missing something or how I can get the same format in Excel?

Thanks in advance.

**Comment by edwardch** [comment]
Hi @qprotex,

The display format looks correct in your app but the number 1 is typically recognised as 100%. So with Excel you're always going to get it showing up as 100X too high. 

If you can *change this to be stored in your database as 0.0808* it will be correct and it will also show up correctly in Excel.

What I did was create my own Formatter to display the % value in the app correctly. It gets the value from the database, then multiplies it by 100 in the grid.

```typescript
namespace YourProject.Common  {
        @Serenity.Decorators.registerFormatter()
        export class PercentageFormatter implements Slick.Formatter {
            format(ctx: Slick.FormatterContext) {
                if (ctx.value) {
                    return Q.htmlEncode(Q.formatNumber(ctx.value * 100, "#,##0.0000")) + "%";
                }
            }
        }
    }
```

Then when you do an export to Excel it'll be correct too.

PS. After you add that formatter you'll want to transform your T4's, then add [PercentageFormatter] to your column.

Hope it helps!

**Comment by qprotex** [comment]
Thanks edwardch, it works!
