### ISSUE TITLE
Use a Lookupeditor without log in into Serenity Backend?

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3703]
Can I use a Serenity.Lookupeditor from a cshtml page, without log in into the serenity backend?

I use: 

```
                new Serenity.LookupEditor($('#Cities'), {
                lookupKey: 'Parameters.Cities'
                })
```

But the browser console tell me: Serenity is not defined

Anyone can point me in the right direction?

**Comment by volkanceylan** [comment]
Use LayoutNoNavigation as your layout.
