### ISSUE TITLE
access levels

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3704]
Dear,
How can I make access levels in serenity.
Ex .: I need to develop a system of registration of Workers, where I will have the following profiles:
Worker
Coordinator
Manager

I will have several units of work in the same application, the worker will be registered in a unit, and I can transfer it between units.

The Coordinator is responsible for a unit of work, and will be able to visualize all the workers of that unit.

The manager is responsible for more than one unit of work and can see the workers of all the units in which he is responsible.

When the worker logs in he will only see his data.
When the coordinator logs in he will see the data of all the workers of his unit.
When the manager logs in he will see the data of all the units he is responsible for, and can choose the unit.

when we use sergen we assign a Permission Key, which I understand will access the tables, grid, pages, etc in the permissions, I hedge the users to have access to this Permission Key
![image](https://user-images.githubusercontent.com/7516443/42289925-c521c100-7f98-11e8-9eaf-8e2fe198b740.png)

![image](https://user-images.githubusercontent.com/7516443/42289963-eccefcb8-7f98-11e8-8c04-92dcbb1a7ded.png)

I define here in the Repository.cs in MyListHandler which will be displayed according to the logged in user, in the user register I reference him in the unit.
private class MyListHandler : ListRequestHandler<MyRow> {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                var user = (UserDefinition)Authorization.UserDefinition;
                if (!Authorization.HasPermission("SomePermissionThatLetsUserSeeAllRows"))
                {
                    query.Where(fld.IDUnidade == Convert.ToInt32(user.IDUnidade));
                }

            }

        }

so I get that user to see only his data on the unit.
however when it arrives on the part of the Manager you have to see all the unit
no longer appears
because in his register I only mention one unit

**Comment by dfaruque** [comment]
these might be helpful
https://volkanceylan.gitbooks.io/serenity-guide/tutorials/multi_tenancy/multi_tenancy.html
https://github.com/volkanceylan/MultiTenancy

**Comment by juliermefelix** [comment]
resolved, creating a permissions file and mounting the appropriate permissions
Delete
Modify
View
Insert

**Comment by srinivas1910** [comment]
Thank You @juliermefelix 

my mail id srinivas@s3in.com

Regards,
Srinivas

**Comment by srinivas1910** [comment]
Hi @juliermefelix am expecting a mail from you

Regards,
Srinivas

**Comment by juliermefelix** [comment]
@srinivas1910 
email sent
