### ISSUE TITLE
How to Create Auto Update

### ISSUE THREAD

**Issue by rezafd23** [volkanceylan/Serenity#3705]
Hi, i want to ask is there any possibility to auto update a table when i clik this circle
![image](https://user-images.githubusercontent.com/31206753/42304382-2b947c68-8050-11e8-9c9e-1c859b7d6f3f.png)

i've made this method but i confuse where i should to call this method
![image](https://user-images.githubusercontent.com/31206753/42304544-f55a98de-8050-11e8-9116-68722064ff57.png)

thanks

**Comment by hannesb** [comment]
A modified Retrieve handler might do the job. If you want a reusable solution, implement a Behaviour.

**Comment by rezafd23** [comment]
@hannesb Thanks for response
so what about get data from the field which we cliked?

**Comment by hannesb** [comment]
If you implement a retrieve behaviour, it will be passed as parameter (i.e. to OnReturn)
