### ISSUE TITLE
Dynamically change LookupEditor on same field according to "type" of the field

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#371]
Hi JaiQ,

John Ranger here again with a Special challenge.

**Is it possible to dynamically change LookupEditor on a field according to the "type" of the field?**

Let me explain what I mean by "type" of the field.

Let's assume that I have a usersettings table which holds a set of Settings which can be applied to a user via a user-to-usersettings-link table.

The Usersettings table does not hold individual Settings for a user - it only holds the "template Settings". Each of the Settings must have a type which is derived from a SettingTypes table.

the UserSettings table Looks like this:

```SQL
CREATE TABLE [dbo].[UserSettings](
	[UserSettingsID] [int] IDENTITY(1,1) NOT NULL,
	[SettingName] [nvarchar](max) NOT NULL,
	[SettingTypeID] [int] NOT NULL CONSTRAINT [DF_UserSettings_SettingTypeID]  DEFAULT ((0)),
	[Remarks] [nvarchar](max) NULL,
 CONSTRAINT [PK_UserSettings] PRIMARY KEY CLUSTERED 
(
	[UserSettingsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
```

The SettingTypes table like this:
```SQL
CREATE TABLE [dbo].[SettingTypes](
	[SettingTypeID] [int] IDENTITY(1,1) NOT NULL,
	[SettingTypeName] [nvarchar](max) NOT NULL,
	[DBTypeName] [nvarchar](max) NULL,
	[CSHARPTypeName] [nvarchar](max) NULL,
	[SerenityTypeName] [nvarchar](max) NULL,
	[Remarks] [nchar](10) NULL,
 CONSTRAINT [PK_SettingTypes] PRIMARY KEY CLUSTERED 
(
	[SettingTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
```

Currently, the SettingTypes table has the following 3 entries:

```cs
SET IDENTITY_INSERT [dbo].[SettingTypes] ON 

GO
INSERT [dbo].[SettingTypes] ([SettingTypeID], [SettingTypeName], [DBTypeName], [CSHARPTypeName], [SerenityTypeName], [Remarks]) VALUES (1, N'String', N'nvarchar(max)', N'String', N'StringField', N'String    ')
GO
INSERT [dbo].[SettingTypes] ([SettingTypeID], [SettingTypeName], [DBTypeName], [CSHARPTypeName], [SerenityTypeName], [Remarks]) VALUES (2, N'Integer', N'int', N'int', N'Int32Field', N'Integer   ')
GO
INSERT [dbo].[SettingTypes] ([SettingTypeID], [SettingTypeName], [DBTypeName], [CSHARPTypeName], [SerenityTypeName], [Remarks]) VALUES (3, N'Boolean', N'bit', N'bool', N'BooleanField', N'Boolean   ')
GO
SET IDENTITY_INSERT [dbo].[SettingTypes] OFF
```

Now, when I define a new UserSetting (in the "template" table UserSettings), I define the Setting Name and the type of the Setting.

**This all works fine.**

Individual Settings for users (normally a subset of the settings defined in UserSettings) are set within a link table.

```SQL
CREATE TABLE [dbo].[Link_User__with__UserSettings](
	[LinkId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[UserSettingsId] [int] NULL,
	[SettingValue] [nvarchar](max) NOT NULL,
	[Remarks] [nvarchar](max) NULL,
 CONSTRAINT [PK_Link_User__with_UserSettings] PRIMARY KEY CLUSTERED 
(
	[LinkId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

**But now Comes the challenge:** When Setting a specific Setting for a user in the link table (both user and UserSetting can be selected with a Dropdown) I want the LookupEditor of the SettingValue field be adapted according to the "type" of the selected UserSetting (dynamically Change LookupEditor and the presentation of the value field on Client side when modifying the UserSettingsId value through the dropdown).

**For example:** 
- when the "SettingType" of the UserSetting is "Boolean", then I want to give the Value field a Dropdown with "true" and "false" in it.
- when the "SettingType" of the UserSetting is "String", then let it be an entry field
- when the "SettingType" of the UserSetting is an integer, then let it be an entry field
- etc

In Addition to that I am playing with the thought of adding an additional field in the UserSettings table where I can optionally define the Name of a LookupScript which would then be used in the Dropdown for the SettingValue field in the Link table when the corresponding usersetting is selected.

**Question:** Is it possible to Change the lookupEditor for a form field dynamically and if yes, how would I do this?

Thanks for your Kind Support and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Hi Ranger,

This is kinda complicated to example here. I recommend you prefer Serenity configuration system, where classes are used to define settings and UI while storing JSON in DB. I'll probably add a sample for such to Serene later.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your Feedback. Looking Forward to see the example ;-)

with Kind regards,

John

**Comment by ZCombs** [comment]
Is there any examples for this yet? I'm interested in doing something like this for a notes table I've created.

![image](https://user-images.githubusercontent.com/1860789/39435402-4fcf6c84-4c69-11e8-90d4-94de058847be.png)

My thought process being that you select a 'Note Type', then the 'Note For' selections get populated for that 'Note Type'.
