### ISSUE TITLE
Change Radiobuttoneditor style

### ISSUE THREAD

**Issue by rezafd23** [volkanceylan/Serenity#3710]
hii alll, i have some problem of radiobutton editor style, is that possible to change this radiobutton to vertical?

![oke prob](https://user-images.githubusercontent.com/31206753/42486466-772cb724-8426-11e8-965b-c0e2e42ba7d8.png)

Thanks

**Comment by rezafd23** [comment]
@volkanceylan hi volkan do you know how the way to do it?
Thanks

**Comment by Estrusco** [comment]
Your radio button element is composed by a div cointains couples of label input elements.
Add style="display: block;" to label element (or use css class). You can use jQuery to do this

```html
<div class="editor flexify s-RadioButtonEditor" id="yourRadioID">
    <label style="display: block;"><input type="radio" name="radioEditorName" id="radioEditorName_1" value="1">Text 1</label>
    <label style="display: block;"><input type="radio" name="radioEditorName" id="radioEditorName_2" value="2">Text 2</label>
</div>
```
