### ISSUE TITLE
Selection of value in Lookup editor

### ISSUE THREAD

**Issue by Tushar5292** [volkanceylan/Serenity#3712]
By selecting value in lookup editor master I want to bind the data in detail section.
How to proceed ahead.

For example :
I have drop down with OrderIds, with that Id i want to bind the dropdown of detail section of same form.

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/OrderDetail/OrderDetailsEditor.ts

` row.ProductName = ProductRow.getLookup().itemById[row.ProductID].ProductName;`

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serenity/issues/837
