### ISSUE TITLE
MultiSelect Lookup Filter Not Working

### ISSUE THREAD

**Issue by aksingh1979** [volkanceylan/Serenity#3713]
Dear All,
Need some help to filter the MultiSelect lookup list to display only unassigned records not all.
Please advice.
Tried some logic but do not know how to get the id of current editable record in PrepareQuery.

 protected override void PrepareQuery(SqlQuery query)
        {
            var fld = LRDetailsRow.Fields;
            var ml =  MultipleLRRow.Fields.As("ml");
          //  var a = this.getItems();
            query.Distinct(true)
                 .Select(fld.Id, fld.LrNo) //; 
                 .LeftJoin(ml, ml.LrNumberId == fld.Id | ml.TripId==[How to get current edit record Id]);
                // .Where(ml.LrNumberId.IsNull());
        }

![image](https://user-images.githubusercontent.com/5478776/42382755-e414f85a-8152-11e8-9252-2c5b5460b283.png)

**Comment by volkanceylan** [comment]
Lookups are not dynamic, please read guide and other lookup samples here so far.
