### ISSUE TITLE
Validation Radio Button

### ISSUE THREAD

**Issue by AlifAbhiesa** [volkanceylan/Serenity#3716]
Hallo volkan, can you explain how to make required form for radio button object?
if type of form is string, number, or dropdown it works whem i'm adding Not Null and automatic that form has marked by red color. But it doesn't work on radio button. thanks

**Comment by Estrusco** [comment]
One radio value must be always selected. 
In case of new record simply set a default value for your radio.

**Comment by AlifAbhiesa** [comment]
Thank you @Estrusco But if i want show the error message and still not give a default value. is it possible?

**Comment by Estrusco** [comment]
You can try to add a valditionRule to radioControl. But IMHO this is not standard way to use radio buttons.

```ts
this.form.YourRadio.addValidationRule(this.uniqueName, (e) => {
    if (!Q.isValue(this.form.YourRadio.value))
        return "error message";
    }
);
```

**Comment by rezafd23** [comment]
you can add this Condition in SaveResponse method in Repository file
    if(request.Entity.ProcurementTypeId==null)
            //if (proc.ProcurementTypeId.Value == null)
            {
                throw
                    new Exception("Please Choose Procurement Type");
            }
            else
            {
                return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
            }

it works for me

**Comment by brunobola** [comment]
You can use the beforesave of the dialog and evaluate the value.
