### ISSUE TITLE
Can't find cascaded parent element with ID: TblPrTran!

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3719]
Hi everyone!
I'm having a problem with cascading field
Actually I have created module called PurchaseOrder where I use foreign key of PurchaseRequisition table i.e.  PrId (Below file contains screenshot of that)

![screenshot 50](https://user-images.githubusercontent.com/39983941/42511482-9e5ea0fc-846f-11e8-88f6-683052ba417f.png)

Now i want to update my Items   from detail section on selection of Perticular PrId And I use cascading for that

![screenshot 52](https://user-images.githubusercontent.com/39983941/42511598-f760aa42-846f-11e8-846e-f05378a71143.png)

But it shows error

![screenshot 51](https://user-images.githubusercontent.com/39983941/42511611-02db3f7c-8470-11e8-8eb9-8e2ba605ac42.png)

I also refer #968 but couldn't find any solution........please help!!

**Comment by volkanceylan** [comment]
Cascaded element must be in same form, before the editor.
