### ISSUE TITLE
Custom LookupScript not showing TextFieldName from third table

### ISSUE THREAD

**Issue by PedroHFranco** [volkanceylan/Serenity#3720]
I'm making an CustomUserLookup to pick up the users in a specific role.

This is the Lookup:

```
namespace Project.Web.Modules.Cadastros.Contas
{
    [LookupScript]
    public class ContasUserLookup : RowLookupScript<UserRow>
    {
        public ContasUserLookup()
        {
            IdField = TextField = "Usuário";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = UserRow.Fields;
            query.Distinct(true)
                .Select(fld.UserId)
                .Select(fld.Username)
                .Where("exists (select UserId from UserRoles ur where ur.UserId = T0.UserId and  ur.RoleId = (select r.RoleId from Roles r where r.RoleName like '%Administrador da Conta%'))");
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }

    }
}
```

I have an account register and on this Dialog i have the third table to link account with user.
![image](https://user-images.githubusercontent.com/10779853/42516621-98cc6808-8434-11e8-8161-7b5182b0167b.png)

```
[Category("Usuarios")]
[UsuariosContaEditor]
public List<Entities.UsuariosContaRow> Usuarios { get; set; }
```

In this `UsuariosContaEditor` i have set the custom LookupEditor:

```
[DisplayName("User"), NotNull, ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jUser"), TextualField("UserUsername")]
[LookupEditor(typeof(ContasUserLookup), InplaceAdd = true, DialogType = "Administration.UserDialog")]
public Int32? UserId
{
	get { return Fields.UserId[this]; }
	set { Fields.UserId[this] = value; }
}
```

But when i open this Lookup is comming with white value

![image](https://user-images.githubusercontent.com/10779853/42516138-c68a350a-8433-11e8-9a7c-c9e7c1966895.png)

I'm not sure if i'm making some wrong i could not found an example for this.

How make this works ?

Thank's.

**Comment by alexdaywid** [comment]
No seu contrutor informe o IdField e TextField como exemplo abaixo 
 public PessoasLookup()
 {
     IdField = PessoasRow.Fields.PessoaId.PropertyName;
     TextField = PessoasRow.Fields.Nome.PropertyName;
  }

**Comment by PedroHFranco** [comment]
Resolvido!

Obrigado @alexdaywid
