### ISSUE TITLE
Drill Down on Orders to Order Line and then to Order Line Shipment Schedule

### ISSUE THREAD

**Issue by mhgressenhall** [volkanceylan/Serenity#3721]
I am currently trying to create a way to select a order, then a order line and then show/manage the order line shipment schedules.  I have used the MasterDetail to create the order to order line relationship, but I can't figure out how to do the order line to order line schedule.  Thanks

**Comment by ga5tan** [comment]
I have the same problem in second step.
I would like detail to open another entity grid, instead of in memory form/editor

**Comment by ga5tan** [comment]
@mhgressenhall In the end I figured how to open Entity Dialog from Detail memory grid and that is ok for me. lemmie know if O should paste sample.
Also, in premium template, there is split grid master detail, when u have second grid showing details to selected row in first grid. somethink to think about, especially if u plan go premium...

**Comment by mhgressenhall** [comment]
Could you please post a sample please.

**Comment by ga5tan** [comment]
sure, just put this into your DetailList Editor.ts:

```
protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);
            if (e.isDefaultPrevented()) {
                return;
            }
            var item = this.itemAt(row);
            var target = $(e.target);
            {
                e.preventDefault();
                new Proj.Module.MyItemDialog().loadByIdAndOpenDialog(item.ItemId);
            }
        }
```
