### ISSUE TITLE
Getting Started with Serenity

### ISSUE THREAD

**Issue by tomatoe45** [volkanceylan/Serenity#3723]
Question:
[New to Serenity]
1. Is Serenity is for Server side only?
2. How to achieve for User/Client side of serenity.

Thanks..

**Comment by samdubey** [comment]
1. Serenity is Web Application Framework for Rapidly Developing Line of Business Application from database tables ( though you are not restricted to create any sort of application with it, it's great framework)

2. When serenity generates the code for UI it also generates API for the same to access from any rest client (Mobile / WPF / Any Language)

3. You need to use Cookie based authentication to login and retain the cookie client side to make a call
If you are able to implement IdentityServer4 working with Serenity you can also use Token Authentication and lot of other types authentication with Serenity

hope this answers you questions

**Comment by tomatoe45** [comment]
Thanks for the info.
because i'd like to try this serenity framework as may server side for my projects/program.

**Comment by Estrusco** [comment]
There is a great guide at https://legacy.gitbook.com/book/volkanceylan/serenity-guide/details (online or PDF)

**Comment by tomatoe45** [comment]
hi @Estrusco .. user guide is already in my bookmark thanks..

**Comment by tomatoe45** [comment]
One thing.. how to run this sample from master into local computer. seems like i cannot find the startup project .. 

Thanks.

**Comment by volkanceylan** [comment]
Read the guide plz, all you need is there
