### ISSUE TITLE
Get Value from Daterange

### ISSUE THREAD

**Issue by rezafd23** [volkanceylan/Serenity#3724]
Helloo all, i've got some issues within creating filter graph from daterange picker?

![image](https://user-images.githubusercontent.com/31206753/42559483-71ad7e20-851e-11e8-8a91-0bd49bc350f9.png)

how can i get a value from daterange picker to fill the parameters when i call it at dashboardindex.cshtml

thanks

**Comment by brunobola** [comment]
That's not specific for serenity see the documentation of adminlte for instance.
