### ISSUE TITLE
 addition of two fields

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3725]
hello all,
i have a issue regarding addition of two fields
i have to add two fields how to do it
like :
stock form(currentstock)= stock plus(currentstock) +(Quantity) stock plus
  note the above mentioned  stock form and stock plus in the above syntax is for reference to which form they belong and the  currentstock to right of equalto symbol has foreign key of first curremt stock 
the current stock field is another form named stock and the quantity is another form named stock plus how to do the addition everything is given like foreign keys etc 
thanks in advance

**Comment by ga5tan** [comment]
on server, u can lookup items and calculate how much you want:

Endpoint:
```
//lookup price, since we just pass ItemType
            var fldPL = IDI5.Administration.Entities.PriceListRow.Fields;
            Int16 iItemType = UserRequest.Entity.EventPriceId.Value;
            var iItemPrice = IDI5.Administration.Repositories.PriceListRepository
                .GetPrice(uow.Connection,
                new Criteria(fldPL.ItemType) == iItemType);

```


Repository:


```
public static MyRow GetPrice(IDbConnection connection, BaseCriteria filter)
        {
            var row = new MyRow();
            if (new SqlQuery().From(row)
                .Select(
                    fld.Price
                    )
                .Where(filter)
                .GetFirst(connection))
            {
                return row;
            }

            return null;
        }

```

**Comment by AbhishekhHugar** [comment]
hey @ga5tan i think you didnt get my point 
![capture1](https://user-images.githubusercontent.com/40484328/42613673-d5baf040-85bf-11e8-98a0-05b9203739bc.PNG)
i the above image when i enter the quantity then it should perform addition of current stock and quantity and it should update the current stock from the below image 
![capture2](https://user-images.githubusercontent.com/40484328/42613766-42bd4daa-85c0-11e8-865a-962d29470ca8.PNG)


and reflect it in the image 2  everytime i do the process the current stock should get updated
like when i select an item then current stock + quantity and it should store the updated stock and reflect in image 2

**Comment by ga5tan** [comment]
I guess you can lookup current stock on client and add there like this:

```
Northwind.EmployeeRow.getLookup().items
                    .filter(x => x.FullName === 'Robert King')[0].EmployeeID
```

but since u still have to update table, I would just call webservice, and reload updated value from server ...

**Comment by Shraddha996** [comment]
The above solution work for me. But one thing I need to ask is how to call webservice, and reload updated value from server in lookupscript?

**Comment by ga5tan** [comment]
check wiki, there is some cheat sheet with reloading lookups.
https://github.com/volkanceylan/Serenity/wiki/Cheat-Sheet

onSaveSuccess(response) {
    super.onSaveSuccess(response);

    Q.reloadLookup('Northwind.Customer');
}

**Comment by ga5tan** [comment]
maybe check this then:
https://github.com/volkanceylan/Serenity/issues/3740

**Comment by AbhishekhHugar** [comment]
yup it worked thankyou @ga5tan
