### ISSUE TITLE
[Question] ReadOnly = false disable editor

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#3726]
Currently I see that if I set [ReadOnly(false)] then editor is also disabled. Is that correct 🤔 
If it's correct, can someone show me what is the difference between ReadOnly = false & ReadOnly = true

**Comment by minhhungit** [comment]
I think there is a bug with ReadOnly attribute, method `set_value(value: string)` of Serenity.IReadOnly always return **true** even for ReadOnly(false)
```javascript
set_value(value: string) {
   // value is always 'true' if a field was marked ReadOnly, it does not care value of ReadOnly = false or true

   if (value == null) {
      this.element.val('');
   }
   else if (value.toLowerCase() === 'today' || value.toLowerCase() === 'now') {
      this.element.val(moment((ss as any).today()).format('MMMM DD, YYYY'));
   }
   else {
      this.element.val(moment(value).format('MMMM DD, YYYY'));
   }
}
```

**Comment by volkanceylan** [comment]
That's correct, required an extra check there.

**Comment by minhhungit** [comment]
>required an extra check there

@volkanceylan  I don't sure what I will check
Can you show me how to get value of **ReadOnly** please

**Comment by volkanceylan** [comment]
Read only doesn't mean value cannot be set by code. Your set_value will be called anyway.

**Comment by minhhungit** [comment]
It's my mistake, my question should be relate to **set_readOnly** method, not **set_value**. sorry

```javascript
set_readOnly(value: boolean): void {
   // at here, [value] is always TRUE
}
```

imho, I think that the value = false if [ReadOnly(false)] or value = true if [ReadOnly(true)]

**Comment by Serenis** [comment]
It is fixed in next version @minhhungit
