### ISSUE TITLE
Call Stored Procedure in cshtml

### ISSUE THREAD

**Issue by rezafd23** [volkanceylan/Serenity#3729]
hallo @volkanceylan  and all, i wish someone can help me

does a method with calling stored procedure in controller class can be called at cshtml file?

i have this below method in dashboardpage.cs and always failed when i call this method in dashboardindex.cshtml

        public ListResponse<ViewStoredGraphRow> GetDataGraph()
        {
            using (var connection = SqlConnections.NewFor<TryGraphRow>())
            {
               var data = connection.Query<Item>("StoreGraph",
                    param: new
                    {
                        StartDate = 2018 - 07 - 07,
                        EndDate = 2018 - 07 - 09
                    },
                    commandType: System.Data.CommandType.StoredProcedure);

                var response = new ListResponse<ViewStoredGraphRow>();
                response.Entities = (List<ViewStoredGraphRow>)data;
                return response;
            }
        }

and this one is error message

![image](https://user-images.githubusercontent.com/31206753/42613304-88408496-85ca-11e8-9f5c-cbce29894714.png)

**Comment by volkanceylan** [comment]
There is no C# help here sorry.
