### ISSUE TITLE
Customize query filter and columns visibility through url parameters

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#373]
Hi Volkan,
I managed to customize the query filter overriding the ApplyFilters method in the MyListHandler class, but I was wondering if there is a way to customize that "where" clause (and also which columns to show/hide) based on the request url.
I see your Open Orders example (Dashboard) but if I'm not wrong, in that case you filter the table by setting an already existing filter in the custom toolbar...the point is that I want to apply filters on fields that aren't in the custom toolbar.
The idea is to have only an entity of a specific table and then customize the presentation without create an entity for every "customized" view...that's what I've done now :-( ...

Thanks for your patience and support

**Comment by volkanceylan** [comment]
You may add a subclass of ListRequest and add custom params and based on these params like if (request.OpenOrdersOnly == true) .... customize your filter in repository.

Another option is Criteria parameter of ListRequest. A sample is in this issue:

https://github.com/volkanceylan/Serenity/issues/369

**Comment by marcobisio** [comment]
Thank you very much Volkan!
Btw, more time I spend on this template and more I realize how it is well done... you've really done a great job!

Best Regards

**Comment by marcobisio** [comment]
Ok subclassed the ListRequest with my new flag but which is the proper way to set it?
I've added a new navigation item with the url of such table and the new parameter "?myflag=1" but now I want to get this parameter and set in my subclassed ListRequest...

Thanks in advance

**Comment by volkanceylan** [comment]
You should set it in same place. OnViewSubmit method. Transform T4 before to make your XYZListRequest available client side.

**Comment by marcobisio** [comment]
Done!

Thank you very much for your support.
Regards
