### ISSUE TITLE
How to get value of CascadeFrom in custom LookUp

### ISSUE THREAD

**Issue by PedroHFranco** [volkanceylan/Serenity#3730]
Hello, 
I'm making an CasaceFrom, but i dont have direct relation between the tabels, the relation is in third table cause it can be n to n.

Its like this:

```
public class Account
{
	public int Id {get; set;}
}

public class Application
{
	public int Id {get; set;}
}

public class AccountApplication
{
	public int Id {get; set;}
	public int AccountId  {get; set;}
	public int ApplicationId {get; set;}
}
```	

I'm consuming this tables and need to make an CascadeFrom get all Application in same Account.

I have tryed the normal LookupEditor and got no success and tryed to make an custom LookupScript but the value in CascadeFrom don't come.

Any idea/example how to do this ?

**Comment by alexdaywid** [comment]
Segue esse exemplo
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

**Comment by PedroHFranco** [comment]
Já segui... dessa forma não funciona, pq no meu caso o vinculo ano está dentro na própria tabela.

**Comment by alexdaywid** [comment]
Acho que faltou você informar o AutoComplete = true

[LookupEditor(typeof(AplicativosRow), CascadeFrom = "ContaId" , CascadeField = "ContaId", AutoComplete = true)]

**Comment by PedroHFranco** [comment]
Mesma coisa....

Preciso fazer um Cascade que faça um inner join com a terceira tabela se nao nunca ira retornar algo.
@alexdaywid

**Comment by PedroHFranco** [comment]
The problem was not Resolved @volkanceylan , why did u close it?

**Comment by GentleRen** [comment]
I had the same problem. Once the fields associated with the two tables are inconsistent, the data cannot be loaded. @volkanceylan .....And, @PedroHFranco Have you solved the problem?

**Comment by GentleRen** [comment]
I got it @PedroHFranco
