### ISSUE TITLE
Data not saving into db in master-detail relation screen by using Common.GridEditorDialog

### ISSUE THREAD

**Issue by ShaikBaresha** [volkanceylan/Serenity#3731]
I just followed Order-order detail example in notrhwind sample.

VersionDialog.ts

namespace WorldliveSerene.Worldlive {

	@Serenity.Decorators.registerClass()
	@Serenity.Decorators.panel()
	export class CoDcVersionsDialog extends Common.GridEditorDialog<CoDcVersionsRow> {
		protected getFormKey() { return CoDcVersionsForm.formKey; }
		protected getLocalTextPrefix() { return CoDcVersionsRow.localTextPrefix; }
		

		protected form: CoDcVersionsForm;

		constructor() {
			super();

			this.form = new CoDcVersionsForm(this.idPrefix);
		}

	}
}

VersionDetailsEditor.ts

namespace WorldliveSerene.Worldlive {

    @Serenity.Decorators.registerClass()
	export class VersionDetailsEditor extends Common.GridEditorBase<CoDcVersionsRow> {
		protected getColumnsKey() { return "Worldlive.CoDcVersions"; }
		protected getDialogType() { return CoDcVersionsDialog; }
		protected getLocalTextPrefix() { return CoDcVersionsRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

MasterRow

[DisplayName("Details"), MasterDetailRelation(foreignKey: "WLDCID_FK"), NotMapped]
		[VersionDetailsEditor]
		public List<CoDcVersionsRow> VersionList
		{
			get { return Fields.VersionList[this]; }
			set { Fields.VersionList[this] = value; }
		}
By clicking on save it's showing data in grid and after page refresh no records in grid and not saving data to db as well.

I just checked in serenity demo site as well there also same problem.

Can any one help me to fix this....Thanks in advance...

**Comment by ga5tan** [comment]
worked fine for me:
https://serenity.is/demo/Northwind/Order#edit/11081

you have to save master and only then are details saved!
GridEditorDialog  is just in memory editor, does not save item when Update or Save is pressed.

**Comment by ShaikBaresha** [comment]
@ga5tan Thanks for your response.Yes you are right...But in my details table i have to  save custom primary key instead of auto generated.While i am trying to update master row after adding data to details grid,it's showing null primary key error..

Sorry i am new to serenity and learning now...Can you please show me,how can we add custom primary key while saving details record?

**Comment by ShaikBaresha** [comment]
@ga5tan Thanks for your quick response. I tried already in may places

In Master(CoDCDocuments)

public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
		{
			foreach (Entities.CoDcSupportDocumentsRow Sup in request.Entity.DocumentPath)
			{
				Int64 _iMaxValue =  LookUps.GetPrimaryKeysHelper.GetLastPrimaryKey(uow.Connection, "WLDSID") + 1;
				string _WLDSID = "WLDSID" + _iMaxValue.ToString().PadLeft(9, '0');
				Sup.Wldsid = _WLDSID;
			}

			return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
		}

	private class MySaveHandler : SaveRequestHandler<MyRow>
		{

			protected override void SetInternalFields()
			{
				base.SetInternalFields();


				if (IsUpdate)
				{

					foreach (Entities.CoDcSupportDocumentsRow Sup in Row.DocumentPath)
					{
						Sup.Wldsid = "afiubfuiw";
					}

				}




			}

			protected override void ExecuteSave()
			{
				try
				{
					base.ExecuteSave();

					foreach (Entities.CoDcSupportDocumentsRow Sup in Row.DocumentPath)
					{
						//Int64 _iMaxValue = LookUps.GetPrimaryKeysHelper.GetLastPrimaryKey(uow.Connection, "WLDSID") + 1;
						//string _WLDSID = "WLDSID" + _iMaxValue.ToString().PadLeft(9, '0');
						Sup.Wldsid = "WLDCID000000001";
					}
				}
				catch (Exception e)
				{
					//SqlExceptionHelper.HandleSavePrimaryKeyException(e, fld.TerritoryID.Title);
					//throw;
				}
			}


		}

In Details(CoDcSupportDocuments)

    public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
			Int64 _iMaxValue = LookUps.GetPrimaryKeysHelper.GetLastPrimaryKey(uow.Connection, "WLDSID") + 1;
			string _WLDSID = "WLDSID" + _iMaxValue.ToString().PadLeft(9, '0');
			request.Entity.UploadedDt = DateTime.Now;
			request.Entity.Wldsid = _WLDSID;
			return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

  private class MySaveHandler : SaveRequestHandler<MyRow>
		{
			protected override void SetInternalFields()
			{
				base.SetInternalFields();


				if (IsCreate)
				{

					Row.Wldsid = "WLDCID0989099";
					

				}




			}


		}

But still this is not working...Can anyone help me on this @volkanceylan

**Comment by ga5tan** [comment]
dude, my sample works like a charm. do it in masters row Repository (and in details as well), like I said
otherwise look up "SetInternalFields" in Serenity demo app and check for yourself.
Just set breakpoints and see if you code even gets trigerred
(AFAIK there is some behaviour, where U MUST leave PK empty, in order for it to be filled)

**Comment by ShaikBaresha** [comment]
@ga5tan you are correct with normal columns in db. Mine was different case,I was trying to insert IIdField IIdRow.IdField  for details table.
I just added ID(INT32) column as identity to existing table and used that in IIdField IIdRow.IdField...Now this is working fine..Thanks for your help..
