### ISSUE TITLE
Missing Dialog style class

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3735]
All my dialogs have some kind of generated class in it like this:

`<div class="s-TemplatedDialog s-PaymentDialog s-Common-PaymentDialog flex-layout" id="IDI5_Common_PaymentDialog13">`

and I can style them with less files.

Now all of a sudden I got dialog with just "s-TemplatedDialog" class:

`<div class="s-TemplatedDialog" id="IDI5_Orders_OrderDialog0"><div class="s-DialogContent">`

I would like to have it specific styles as other dialogs have (s-Orders-OrderDialog). Any idea what is wrong???

**Comment by volkanceylan** [comment]
All of a sudden, you should check what is different than other dialogs, for example @registerClass

**Comment by ga5tan** [comment]
thx @volkanceylan!
it seems 

`@Serenity.Decorators.panel()
`

was missing for some reason
