### ISSUE TITLE
How to store same value into multiple tables

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3736]
I have two modules 1.ItemMaster 2.ItemStock
where ItemStock Have  ItemMaster ForeignKey

Now I want a solution like, whenever I create New Item in ItemMaster Then the Same ItemDescription Should also save in the ItemStock Table

If Anyone has a solution for this then please help..
ThankYou!

**Comment by ga5tan** [comment]
Ideally (relational table design) u dont wanna store same info in multiple places.
so just have ItemDescription in one table and retrieve it via relation in VIEW or SELECT

**Comment by kilroyFR** [comment]
Simplest and almost 0 coding way is using trigger on first table (i know many prefer to code this logic in C# but definitively not the simplest way - can be enabled/disabled easily with 0 software deployment).
