### ISSUE TITLE
Serenity.Data How can table column names names be quoted by default?

### ISSUE THREAD

**Issue by leak** [volkanceylan/Serenity#3737]
Is there a way that all column names can be quoted using the correct dialect by default in a query?

**Comment by ga5tan** [comment]
did u check Developers Guide ? there is something about it I beleive

**Comment by leak** [comment]
The only thing I found is `SqlSettings.AutoQuotedIdentifiers = true;`

But it does not work as expected:

````
SqlSettings.AutoQuotedIdentifiers = true;

var postgresConnection = new WrappedConnection(new NpgsqlConnection($"xxxxxxxxxx"), new PostgresDialect());

query = new SqlQuery().Dialect(new PostgresDialect()).Select("_TimeStamp").From("test");

var result = postgresConnection.Query(query);
````

generates 
````
SELECT 
_TimeStamp 
FROM [test]
````

where not only the column is not quoted but also the table name is invalid quoted for Postgres (even though i explicitly specified the proper dialect multiple times.

**Comment by ga5tan** [comment]
I am sorry to hear that. Maybe u doing it wrong?
All works fine for me with MS SQL Server

**Comment by leak** [comment]
Feel free to point out what I am doing wrong, see code above.

**Comment by volkanceylan** [comment]
Auto means bracket when required, there is no option to always bracket.

**Comment by ga5tan** [comment]
other option is to use proper names, so that no bracketing is needed.
I had to go that way in MySQL, where tablenames could not contain dash (-) without quoting it properly in PHP. Ended up renaming tables, rather than hacking 10y old PHP code for quoting

**Comment by leak** [comment]
The problem is I need to query 3rd party databases where I cannot control the database layout. Also every database type has different dislikes when it comes to quoting identifier.
So I'd prefer to be safe than sorry by always quoting things properly.
