### ISSUE TITLE
new Draggable Grouping small issue 

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3739]
![image](https://user-images.githubusercontent.com/31513956/42786923-7a03c05a-8958-11e8-8b3b-1e10a6981f93.png)

using the demo, by mistake i have added the column (with no name) that is PDF file and drag into the grouping area.
Since then i was unable to remove this grouping as seen on screen shot (all others selected grouping could be remove but not the one with no name).

Thanks - great additions this draggable grouping feature

**Comment by Zahar661** [comment]
give it a name and delete it)

**Comment by kilroyFR** [comment]
yes would be no problemo. Just wanted to inform in such situation (column with no name) it causes a side effect (if you have user_preferences enabled you will never be able to remove this column - that can be a problem).
Up to Volkan to decide if it should be either fixed or always settings a column name is MANDATORY.

**Comment by Zahar661** [comment]
And in the standard functionality, enable the cleaning function of the view

**Comment by volkanceylan** [comment]
Well, it shouldn't be mandatory, but shouldn't group by that or let it be removed somehow, will check.

**Comment by volkanceylan** [comment]
It wasn't about having no title, but having a space inside field name, will be fixed in next version.
