### ISSUE TITLE
Reload Lookupscript

### ISSUE THREAD

**Issue by Tushar5292** [volkanceylan/Serenity#3740]
constructor() {
            super();

            this.form = new TblAdjustmentplusTranForm(this.idPrefix);

            this.form.ItemStockId.changeSelect2(e => {
                var ItemStockId = Q.toId(this.form.ItemStockId.value);
                if (ItemStockId != null) {
                    
                    this.form.CurrentStock.value = Inventory.TblItemStockRow.getLookup().itemById[ItemStockId].CurrentStock;

           
				}
            });

        }

------------------------------------------------------------------------------------------------------------------

****In above code snippet I am getting the current stock value and I could save it in database also only I cannot reload the lookup script what should I do for that to reload the lookpup dropdown.

I reffered all the issues raised before but I am not getting the proper solution.
Could anyone please help?****

**Comment by dfaruque** [comment]
set `[LookupScript(Expiration = -1)]` in row.cs
and call
`Q.reloadLookup(Inventory.TblItemStockRow.lookupKey);` in some ts

**Comment by Tushar5292** [comment]
Thank you!!! It works for me.
