### ISSUE TITLE
Detail section on another tab

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3741]
hey @volkanceylan 
Am just having an issue on moving detail section on another tab

![screenshot 55](https://user-images.githubusercontent.com/39983941/42811615-b5aa2bbe-89d8-11e8-9592-c3e6149474f6.png)
Now here I want to move the detail section on BOMTran tab
what should I do?

**Comment by dfaruque** [comment]
use [Tab("TabTitle")] on you detail property in form.cs

**Comment by Shraddha996** [comment]
hey @dfaruque  I just tried this but it creates a bootstrap tab like this
![screenshot 57](https://user-images.githubusercontent.com/39983941/42861739-019795ce-8a7a-11e8-995a-9251b80efc35.png)
but I already created a tab in the separate HTML file and I want my detail section should display in that 
but its still empty
![screenshot 58](https://user-images.githubusercontent.com/39983941/42861769-228e5ad8-8a7a-11e8-8332-0a10069dd4f7.png)

**Comment by dfaruque** [comment]
why you use old style tab? 
use the latest bootstrap tab. you should delete the template.html file.

**Comment by dfaruque** [comment]
if you stick to use the old style tab 
see the code of the following
https://serenity.is/demo/Northwind/Customer

**Comment by Shraddha996** [comment]
Am using old style Tabs because I want to apply (enable/disable) property on that tab,
so that I can enable BOMTran tab on the selection of any dropdown value from First Tab 

Is it a possible in bootstrap tabs?

**Comment by dfaruque** [comment]
http://jsfiddle.net/Sherbrow/nZaLY/

**Comment by dfaruque** [comment]
```
this.form.someDropdown.change(e=>{
//write something here
});
```
