### ISSUE TITLE
pdf oluşturma

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#3742]
Gridte birden fazla secip  pdf oluşturabilirmiyiz.Kullandıgım method bu
Q.postToUrl({
                                url: '~/Report/' + (false ? 'Download' : 'Render'),
                                params: {
                                    key:  ModulAd,
                                    ext: Q.coalesce('pdf'),
                                    opt: ($.toJSON({ Id: opt.arr[a], ilkTarih: ilktarih, SonTarih: sontarih }))
                                },
                                target: Q.coalesce('_blank')
                                });

**Comment by volkanceylan** [comment]
Malesef
