### ISSUE TITLE
Populate Grid with Static Data from JSON String

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#3743]
Hello,

How can I populate serenity grid from any static JSON String along with filtration options ?

**Comment by dfaruque** [comment]
`this.view.setItems(items, true);` should do the job

**Comment by dfaruque** [comment]
also you might need to override getGridCanLoad
```
       protected getGridCanLoad() {
            return false;
        }
```

**Comment by TechAspirant** [comment]
Hello,

Thanks for the response. Sorry for the stupid question but where  to write this.view.setItems(items, true); and where to pass json string so that It will show in grid. If possible can you show example of it

**Comment by TechAspirant** [comment]
will check and Let you know....{ Id: 1 }, { Id: 2 } this should be replaced by my json stuff......But filter will work with this
