### ISSUE TITLE
OnBeforeDelete Problem!

### ISSUE THREAD

**Issue by javaman63** [volkanceylan/Serenity#3745]
I need to get value from some table on OnBeforeDelete to delete some record on another table, but i cant get any, because trows me an error
Any body can point me in the right direction?

```
            protected override void OnBeforeDelete()
            {
                base.OnBeforeDelete();
                var o = PendientesRow.Fields;
                var IdPendientes= Connection.TryFirst<PendientesRow>(o.IdTipoPendiente == 4 && o.IdGSC == Row.IdCotizacion.Value);

                if (IdPendientes.IdPendiente.Value>0)
            
                {
                    var sqlCommand = "delete from pendientes where IdPendiente = " + PendientesRow.Fields.IdPendiente.ToString();
                    Connection.Execute(sqlCommand);
                }
	    }
```
the TryFirst error throw me an error but the query on dabatase with that criteria return a value. I'm Lost

**Comment by ga5tan** [comment]
what kind of error ?

**Comment by javaman63** [comment]
Basically the TryFirst returns null, but on the database..have a value

**Comment by volkanceylan** [comment]
use exclamations sparingly, and your delete command is wrong
