### ISSUE TITLE
Need to restrict use to open new Form

### ISSUE THREAD

**Issue by patelaakash** [volkanceylan/Serenity#3746]
Hi all,

I am new to serenity i need some help about the following issue.
I have a job list page and have new button on the grid. I have made it invisible when the customer get logged in but when I write #new behind the URL it still opens the new form i want to restrict that.
When the customer user get logged in he/she should not be able to show new job form.
It should be only visible to admin users.
Is there any way out to stop customer user to get restricted from controller side?

Thank you in advance

**Comment by ga5tan** [comment]
check Serenity Developer Guide, there is mention of further securing.
I think you can check in form itself, or just leave it for row level security (which repository checks on) and wont let user to save if he has no privileges...

**Comment by Zahar661** [comment]
use [InsertPermission]
