### ISSUE TITLE
Deduct stock quantity after order has been made in Northwind

### ISSUE THREAD

**Issue by masudijames** [volkanceylan/Serenity#3751]
Hi there,
Why in Northwind sample after purchase has been made does not deduct quantity from products table.
How to do it?
Thank you

**Comment by VirtualHome** [comment]
Hello, could any please help us with this issue. Thanks to all for the help.

**Comment by gguadalupe** [comment]
I'm going on wild guess here... The Northwind sample is just that, a sample. It is not intended for you to use it as a functional system (don't get me wrong, it works like a charm! but is not the intention.)
Now, if you want to do this, you might want to check the onSaveSuccess of OrderDialog.ts
From there you can call a Product service to decrease the quantity of whatever you have in OrderDetail, or change the value of UnitsInStock right there, and call the update service. (I prefer to have a service dedicated to each function)

You can do something like (and BTW, this is me **free-styling + I'm not a web developer**)
```
for (var Det of this.form.DetailList.getItems()) {

  ProductItem = ProductRow.GetLookup().itemById[Det.ProductID];
  ProductItem.UnitsInStock = ProductItem.UnitsInStock - Det.Quantity;
  ProductService.Update( { Enrity: ProductItem }, (r) => this.refresh());
  
}
```

Hope this helps

Gus

P.S.: Now that I finish writing this, I notice I'm completely **WRONG**!
You can do the same in the Order endpoint or Repository **Create**, not sure which one is the best place (I'm inclined to Repository...)

**Comment by Serenis** [comment]
I'd recommend doing that with a trigger in SQL, but if prefer Serenity way, you should do that in AfterSave / AfterDelete of SaveHandler / DeleteHandler

**Comment by gguadalupe** [comment]
You could do it in a trigger and it's going to work perfectly, but you will be breaking the architecture of the platform.
It may take you longer to understand all the pieces of Serenity, but in the long run if you do it as intended, the reward is a more stable, and structured system.
I'm not a web developer and I understand (or I think I understand) how to develop in Serenity and IT IS SUPER EASY! you just need to pay attention to the examples provided in northwind/basic examples and read this forum.
