### ISSUE TITLE
[HowTo] Remove QuickSearch Entirely

### ISSUE THREAD

**Issue by JoeyFerg** [volkanceylan/Serenity#3752]
I was wondering if there was a way to splice out or hide the QuickSearch bar entirely. Keeping the column picker and refresh button is important to me, but I want to get rid of QuickSearch.

Anyone have a solution?

**Comment by volkanceylan** [comment]
Override createQuickSearchInput and do nothing.

```ts
        protected createQuickSearchInput() {
        }
```

**Comment by JoeyFerg** [comment]
Thank you, Volkan. This is exactly what I wanted.
