### ISSUE TITLE
Autorization (UserId)

### ISSUE THREAD

**Issue by adalberto-argente** [volkanceylan/Serenity#3755]
I have the following code on my system for quite some time, after upgrading to StartSharp it is no longer working.
@volkanceylan , how do I get the UserId on the client side?
```
 private permiteAlteracao(note: NoteRow) {
            if (note.InsertUserId != Authorization.userDefinition.UserId) {
                Q.alert("Ops! Não é possível alterar ou excluir anotação de outro usuário!");
                return false;
            }

            return true;
        }
```

![image](https://user-images.githubusercontent.com/8500507/42897280-e4feca24-8a95-11e8-8ab3-f878f6f8fe3a.png)

**Comment by Febriantos** [comment]
Update your class ScriptUserDefinition.cs
Add a new property UserId into it.
Update your function public ScriptUserDefinition GetUserData()
Assign the UserId value from UserDefinition.Id into that new property

**Comment by javaman63** [comment]
ON your xyzDialog use

`var UserId = Authorization.userDefinition.UserId;`

**Comment by adalberto-argente** [comment]
@Febriantos, I thought about it, but why did @Volkan remove it?
Is this what I want to do differently?
If I add this property again, will it go wrong at another point in the system?

**Comment by volkanceylan** [comment]
You should perform such checks at repository, not client side. Don't depend on any clientside information.

**Comment by JohnRanger** [comment]
Hi @adalberto-argente 

For checks I agree with Volkan - only on the server side you have full control.

But there are other scenarios - e.g. when using the CloneEntity on client-side and you want to set for example who has done the cloning directly while cloning - then you want to have the user Id on client-side and in such a scenario, @Febriantos suggestion makes much sense.

With kind regards,

John

**Comment by fremar83** [comment]
Hi all,
Regarding to your observations on using the server side with repository, I have a question : Who can I manage this in a detail form (my notes are attached to a treatment).
When I  create a note within treatment master form, NoteRepository doesn't fire BeforeSave void. 
This code works well from NoteForm direct add.
 public class NoteRepository
    {
.../...
 private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                if (!Row.UsersUserId.HasValue)
                {
                    Row.UsersUserId = ((UserDefinition)Serenity.Authorization.UserDefinition).UserId;
                    Row.DateNote = System.DateTime.Now;
                }
               
            }
Thank's
