### ISSUE TITLE
Theming (Change Theme)

### ISSUE THREAD

**Issue by tomatoe45** [volkanceylan/Serenity#3756]
Hi,
I create project with serenity. (Thanks to you)  and i would like to change the theme of this nice app..
my question is does this app (serenity) is capable of changing theme to angular? or just the default one.
because i'de like my app does have a day and night mode.

Thanks.

**Comment by ga5tan** [comment]
upper right corner, there Is control to change theme

**Comment by tomatoe45** [comment]
I mean.. im going to bind the angular to this project. is that possible?

**Comment by tomatoe45** [comment]
btw thanks..
