### ISSUE TITLE
One-to-many Relationship with LookupEditor: Update Child entries instead of Create New Ones

### ISSUE THREAD

**Issue by igkouts** [volkanceylan/Serenity#3759]
Hi all,

firstly I'd like to apologize in advance if my question is tiring (length/repetition), bothering or already answered, but studying the MovieCast and OrderDetails tutorials as well as searching the issues section, didn't led me to any viable solution, although I got some piece of information...
The scenario I'm facing is a simple one-to-many relationship; many invoices created via another dialog are "paid" by a single payment. So when a payment is created, I'd like to open a combo box with the invoices, assigning them one by one to the payment.
Following the tutorials mentioned above I added a list of invoices in the PaymentsRow.cs as below
```
...
[DisplayName("Invoices"), MasterDetailRelation(foreignKey: "InvoicePayment"), NotMapped]
public System.Collections.Generic.List<InvoicesRow> InvoicesList
{
    get { return Fields.InvoicesList[this]; }
    set { Fields.InvoicesList[this] = value; }
}
...
public readonly RowListField<InvoicesRow> InvoicesList;
...
```
and the corresponding editor in the PaymentsForm.cs
```
[Accounting.Payments.PaymentDetailsEditor]
public List<Entities.InvoicesRow> InvoicesList { get; set; }
```
PaymentDetailsEditor and PaymentDetailsEditDialog are as follows. I carefully got the getPropertyId out of the way, in order to prevent duplicate child entries (borrowed from the troubleshooting section)
```
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />
namespace Porto.Accounting.Payments {
    @Serenity.Decorators.registerEditor()
    export class PaymentDetailsEditor extends Common.GridEditorBase<Accounting.InvoicesRow> {
        protected getColumnsKey() { return "Accounting.PaymentDetails"; }
        protected getDialogType() { return PaymentDetailsEditDialog; }
        protected getLocalTextPrefix() { return Accounting.InvoicesRow.localTextPrefix; }
        constructor(container: JQuery) {
            super(container);
        }
        protected validateEntity(row: Accounting.InvoicesRow, id: number) {
            row.InvoiceId = Q.toId(row.InvoiceId);
            var duplicateInvoice = Q.tryFirst(this.view.getItems(), i => i.InvoiceId === row.InvoiceId);
            if (duplicateInvoice && this.id(duplicateInvoice) !== id) {
                Q.alert("The selected invoice has already been added!");
                return false;
            }
            row.InvoiceNo = Accounting.InvoicesRow.getLookup().itemById[row.InvoiceId].InvoiceNo;
            // Rest of the fields I want to bring in; omitted for clarity
            return true;
        }
    }
}
```
```
/// <reference path="../../Common/Helpers/GridEditorDialog.ts" />
namespace Porto.Accounting.Payments {
    @Serenity.Decorators.registerClass()
    export class PaymentDetailsEditDialog extends Common.GridEditorDialog<Accounting.InvoicesRow> {
        protected getFormKey() { return Accounting.PaymentDetailsForm.formKey; }
        protected getLocalTextPrefix() { return Accounting.InvoicesRow.localTextPrefix; }
        protected form: Accounting.PaymentDetailsForm;
        constructor() {
            super();
            this.form = new Accounting.PaymentDetailsForm(this.idPrefix);
            this.form.InvoiceId.changeSelect2(e => {
                var invoiceId = Q.toId(this.form.InvoiceId.value);
                if (invoiceId != null) {
                    // this.form.InvoiceNo.value = Accounting.InvoicesRow.getLookup().itemById[invoiceId].InvoiceNo;
                }
            });
        }
    }
}
```
The PaymentDetailsEditDialog opens PaymentDetailsForm, which contains only the LookupEditor as below
```
[FormScript("Accounting.PaymentDetails")]
public class PaymentDetailsForm
{
    [LookupEditor(typeof(Entities.InvoicesRow))]
    public Int32? InvoiceId { get; set; }
}
```
Finally, as I don't want all the invoices' available fields, I created a PaymentDetailsColumns.cs file, keeping only the necessary fields.
```
[ColumnsScript("Accounting.PaymentDetails")]
[BasedOnRow(typeof(Entities.InvoicesRow), CheckNames = true)]
public class PaymentDetailsColumns
{
    [EditLink]
    public Int32 InvoiceId { get; set; }
    public String InvoiceNo { get; set; }
    // Rest of the fields omitted for clarity
}
```
As far as I can tell, assigning a payment via the invoice works great. Furthermore, the framework is smart enough (through the MasterDetailRelation) to retrieve the records already inserted in the DB correctly, when viewing a payment with it's child invoices (I manually inserted some dummy records for testing purposes). The problem begins when I try to add/edit a new/existing payment while assigning the invoices, where I get new invoice entries, instead of updating the selected ones. I can totally understand such a behavior; after all this is the editor's default usage, but technically speaking, as you can see, what I'd like to do is update the invoices' foreign key(s) (InvoicePayment field) with the payment id, either when adding or removing an invoice to/from a payment accordingly.
I'm pretty sure that I have to override some functions in the PaymentsRepository.cs file; even SetInternalFields and/or LinkingSetRelation may become useful in my case, I just cannot fill all the pieces together in order to solve the problem, so I would be glad if someone could give some piece of advice.

Best regards,

**Comment by MoheebP** [comment]
I have faced the same problem. In my case, packages.config file has changed during new nuget package (flurl) install. serenity packages rolled back to backdated version.

**Comment by igkouts** [comment]
Nice one @MoheebP!
Thanks a lot for your time!
