### ISSUE TITLE
Enhancement: Nested Grid with collapse and expend like Tree functionality.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#376]
It will be great if you will add a feature of grouping in Grid with collapse and expend.
Here is sample: 
http://mleibman.github.io/SlickGrid/examples/example-grouping

**Example: **
For example, on Order page, every row in order grid may contains a nested grid of order details (as shown in dialog) with collapse and expend functionality. 
 It will be great if it will be export in Excel to with nested grid.

**Comment by volkanceylan** [comment]
Yeah it would be also great if some users do such things and share with community

**Comment by volkanceylan** [comment]
Btw, this is not nested grid, its just grouping and SlickGrid doesn't support nested grids. So this is not possible.
