### ISSUE TITLE
No Style after login screen

### ISSUE THREAD

**Issue by james-wheeler** [volkanceylan/Serenity#3760]
Just installed Serenity Platform on a new laptop and trying to build application but I have no styling after login screen. The login screen style is correct. 
Im sure I am probably missing something but I have created projects with no samples and all 3 sample sets and all behave the same.

![image](https://user-images.githubusercontent.com/5492035/42999293-5eacdd8a-8c5c-11e8-92b1-51b571e06832.png)

**Comment by james-wheeler** [comment]
Here is an example output from devtools
![image](https://user-images.githubusercontent.com/5492035/43002687-ce815530-8c68-11e8-969b-09c1150391f2.png)

**Comment by chadburnett** [comment]
The slow network thing is probably a clue, but I'm not sure.  If I think or find anything I'll chime in.

**Comment by ga5tan** [comment]
try to setup Serenity sample app.
see if that works.
you can always trim it down to "empty" app

**Comment by volkanceylan** [comment]
Try to open CSS files using source, if can't reinstall your IIS Express / VS
