### ISSUE TITLE
populate data 

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3761]
hello,
i have a table enquiry which has (foreign key)fields from  customer
and i have a table quotation  which have foreign key of table enquiry 
is it possible to populate data of customers from enquiry into table quotation?

**Comment by ga5tan** [comment]
if u have set FKeys in DB and generate you instrumentation with sergen, your Row (Entity) class will have coulumns joined from FK tables!
dont hesitate, go for it, it even includes looked up texts in Grid and IDs in Form.

**Comment by AbhishekhHugar** [comment]
hey @ga5tan 
thanks for the reply but i dont think you got my issue
i have tables  table1,table2,table3.

table2 has foreign key of table1 and table3 has foreign key table2 i have done sergen etc and have all includes,grid, ids in form
all i want is to get all the data from table2 which has table1 data into table3.   i.e into the forms

**Comment by ga5tan** [comment]
consider adding some screenshots or examples to help other to help you.
You can still lookup additional tables via Expressions, or u can just use view to put all the data together you want.
If you are talking about copying data from one table to another, then you have to do it in Repository or Endpoint...

**Comment by volkanceylan** [comment]
See mapping section in Serenity guide.
