### ISSUE TITLE
Querry returned no result Dialog box

### ISSUE THREAD

**Issue by PrasadK1990** [volkanceylan/Serenity#3762]
Hello,
Where  the String written 'Querry returned no result' alertbox present in the serenity.

Thanks you.

**Comment by ga5tan** [comment]
try to search for it in sources. make sure .js, txt, sql and all kinds of useful file extensions are included.
I thi ther eis file modules/texts.* that has text exposed for translation/modification addition

**Comment by Serenis** [comment]
It's something coming from Linq, check your such statements.

**Comment by ga5tan** [comment]
it can be also from SQL server (or your DB backend)
in that case doublecheck spelling and just google it.
you will find it soon enough
