### ISSUE TITLE
EMailHelper Mailkit

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#3764]
Hi All,
I've got a dotnetcore 2.0 app that is using the emailhelper. It's throwing an exception saying : 'No sender has been specified.' It's easy enough to fix but I'm not familiar with mailkit and  was wondering if I'm missing something.
Thanks

**Comment by ga5tan** [comment]
I am hearing first time about Mailkit (an dgoogled it for 10 seconds) and all I can say is, without sender, you cannot send email

**Comment by RouteTech** [comment]
in the email helper dotnetcore apps use mailkit and other use net mail.
I modified the helper as follows

 public class MailSettings
    {
        public string Host { get; set; }
        public int Port { get; set; }
        public bool UseSsl { get; set; }
        public string From { get; set; }  <--- added this
    }

 public class EmailHelper
    {
        public static void Send(string subject, string body, string address, string displayName = "")
        {
#if COREFX
            var message = new MimeMessage();
            message.To.Add(new MailboxAddress(displayName, address));
            message.Subject = subject;
            var bodyBuilder = new BodyBuilder();
            bodyBuilder.HtmlBody = body;
            message.Body = bodyBuilder.ToMessageBody();
            var config = Config.Get<MailSettings>();
            message.From.Add(new MailboxAddress("Blah@Blah", config.From)); <--- Added this
            if (!string.IsNullOrEmpty(config.Host))
'''''

**Comment by volkanceylan** [comment]
Thanks, applied your solution, will be in next version.

**Comment by RouteTech** [comment]
Thank You.
