### ISSUE TITLE
Regex Field Validation with Sergen 

### ISSUE THREAD

**Issue by DoeBurner** [volkanceylan/Serenity#3765]
I created a basic web app with the Serene template and used Sergen to generate a simple CRUD table. I am trying to add field validation to only one of the input fields associated with that table (frequency) by using the validate jQuery plugin. This input field is found in the generated modal/form for adding rowing to the table. My added code (added to the Sergen generated cshtml file) is as follows:

            $(document).on('click', 'div.tool-button add-button', function () {
            $.validator.addMethod("FrequencyRule", function (value, element) {
                return this.optional(element) || /(\d)+(d|h|m|s)/.test(value);
            }, "Frequency is invalid: Please enter a valid frequency.");

            var inloc = $("div.field Frequency").find("input");
            $('inloc').each(function () {
            $(this).rules("add", {
                    FrequencyRule: true
                });
            });
            $('inloc').validate();
            });

Using the above code, field validation fails to occur. Any help would be greatly appreciated, whether it be changes to my code or a general template/example for field validation.

**Comment by ga5tan** [comment]
there is validation included with generated interface
just put it required, or not null attributes in Row.cs and fields will be validated.
dont sweat it. let the framework do the heavy lifting for u.
consider checking sample app out

**Comment by DoeBurner** [comment]
Thank you for your response. I'm still unsure of how to implement regex field validation. I added a RegularExpressionAttribute to my TableDataRow.cs (where get/set occurs for my migrated rows) and field validation is still not being implemented. How exactly do I let the framework do the heavy lifting for me?

**Comment by DoeBurner** [comment]
I do need it, I'm trying to add required formatting (by using regex) to the string input field in the frequency row in my CRUD table. I have not found any information regarding custom regex field validation relating to Serenity anywhere.

**Comment by Serenis** [comment]
```ts
this.form.SomeField.addValidationRule(this.uniqueName, e => { if (!(/someregex/.test(this.form.SomeField.value)) return "It doesn't match the regex!"; });
```
