### ISSUE TITLE
Call an Oracle procedure from Serene Application

### ISSUE THREAD

**Issue by dsCloud** [volkanceylan/Serenity#3766]
Hello All,

Good work Volkan!!!

Please I have my serene application on SQL Server database where all processes are done but at the end of the data manipulation on SQL Serve database, I need to send some data to an Oracle DB through a procedure call.

Any guide will be appreciated.

Regards,

**Comment by kilroyFR** [comment]
Looks more a problem of link between those 2 DB.
Seen ; https://www.sqlshack.com/link-sql-server-oracle-database/ ??

**Comment by dsCloud** [comment]
Thanks for the response @kilroyFR. But I do not have any problem with Oracle but just trying to figure out how to intercept OR insert a custom Oracle Procedure call codes in my Serene application. Using a linked server can be an option though but would prefer an integrated codes in Serene app.

Any guide will be appreciated.

Regards,

**Comment by dsCloud** [comment]
Thanks!
