### ISSUE TITLE
How can I get total of certain  field?

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#377]
For example,I have one colume Price with type decimal,How can I get the total price ,and show it in page view. 
I can use sql just like 'select sum(Price) from ordertb'

**Comment by ChenZhaobin** [comment]
Refer https://github.com/volkanceylan/Serenity/issues/282

**Comment by volkanceylan** [comment]
You should add a service getting this sum and show it in a textbox with jquery

**Comment by ChenZhaobin** [comment]
Could you give me more detail suggestion?Is it just to implement IListBehavior?But how can I get the Sum value and  get the row list data at a same time?And how can I add a custom textbox in page view generated by serenity UI Script?

**Comment by ChenZhaobin** [comment]
Can you give me more suggestion,I don't know how to handle it.

**Comment by ChenZhaobin** [comment]
I guess it should be implemented in orderGrid.cs,but I don't know which method to overrider?

**Comment by ChenZhaobin** [comment]
I add a method in OrderEndPoint ,but I don't know how to get the value through Jquery,and I don't know when to trigger this Jquery method?

  public decimal GetTotalFreight(IDbConnection connection, ListRequest request)
        {
            var data = List(connection, request).Entities;
            decimal total = 0;
            foreach (var item in data)
            {
                total += item.Freight == null ? 0 :(decimal) item.Freight; 
            }
            return total;
        }

**Comment by volkanceylan** [comment]
Your method should return subclass of ServiceResponse than you can build, transform templates and will have a OrderService.GetTotalFreight method.

**Comment by ChenZhaobin** [comment]
I have already have a subclass of ServiceResponse ,But  how can I use jquery to get the result of OrderService.GetTotalFreight ,and How can I capture the event when gridtable's data is changed?
public class SumResponse : ServiceResponse
    {
        public decimal Total;
        public decimal TotalPrice;
        public decimal TotalShippingFee;
        public decimal TotalDuty;
       
    }

**Comment by ChenZhaobin** [comment]
Refer  #381
