### ISSUE TITLE
services now results in a alert dialog showing stack trace as oppose to a friendly error message

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#3771]
Hi @volkanceylan 
I was hoping may be you can be of some assistance.
In forget password dialog when i enter an email address that doesn't have an account, then instead of showing a alert dialog with friendly error message as in the example at your demo site, i get an alert dialog with the default aspnet error page with stack trace on the yellow back ground.  If i go in my web.config and change the custom error to "on", the the popup simple says an error occurred.  This is also not what i expected as in your demo site it would say:  "can't find a user with that email address".  
I verified the method in such a case throws a validationError exception which i can see the default aspnet expection page in the alert dialog.  I am sure i messed up some setting somewhere such that on client side it now shows default aspnet error in the alert dialog as oppose to simply showing the exception message.  Can you please assist.
Thanks

**Comment by Serenis** [comment]
Sorry, it's not possible to know what you changed.

**Comment by dudeman972** [comment]
Thanks i got it figured out.
