### ISSUE TITLE
Fields Calculation

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3773]
In my form, there are two fields BasicTotal and LandedPrize.
I want to display the subtraction of this two fields in the Final amount Textbox
On the Inline Button click
![screenshot 63](https://user-images.githubusercontent.com/39983941/43068458-145e2224-8e88-11e8-9777-8bedc25e9b69.png)

**Comment by Shraddha996** [comment]
Have this code but don't know what to write in MyFuction()?


protected afterLoadEntity() {
            super.afterLoadEntity();

            $('<a class="inplace-button inplace-create"><b><\/b><\/a>')
                .insertAfter(this.form.LandedTotal.element)  // <======================
                .click(() => this.myFunction());

               }

        private myFunction() {
          
        }

**Comment by Zahar661** [comment]
```
 protected afterLoadEntity() {
            super.afterLoadEntity();
            this.form.BasicTotal.change(e => {    
            
               this.form.Summ.value = this.form.BasicTotal.value - this.form.LandedPrize.value;

            }); 
            this.form.LandedPrize.change(e => {    
            
               this.form.Summ.value = this.form.BasicTotal.value - this.form.LandedPrize.value;

            });
        }
```

**Comment by Shraddha996** [comment]
@Zahar661  thanks it's working fine
