### ISSUE TITLE
Grid Binding on dropdown selection

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3774]
Hello everyone,
Am having a problem with binding a grid
Like, On my dropdown selection I want a grid should display all the product added to that particular ID 
I don't know how to do it
Is anyone have a solution for this?

**Comment by Zahar661** [comment]
```
namespace MyProdject.MyModul.Scripts
{
    using Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("MyModul.LookupMyProduct", Permission = "*",Expiration = 0)]
    public class LookupMyProduct : RowLookupScript<Entities.ProductRow>
    {
        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);

            query.Where(ProductRow.Fields.AuthorId=Serenity.Authorization.UserId);
        }
    }
}
```

**Comment by Shraddha996** [comment]
@Zahar661 
Thanks for the quick reply
   But I think I need to explain 
![capture](https://user-images.githubusercontent.com/39983941/43074474-0b44772a-8e9b-11e8-86af-8f2d9dd30ad8.PNG)
Here you can see the Domestic enquiry lookup where each ID contains some products and i want to bind that product in grid
![capture1](https://user-images.githubusercontent.com/39983941/43074549-54480f90-8e9b-11e8-8c00-221631b7e35e.PNG)

**Comment by Zahar661** [comment]
Maybe not elegant, but it should work. DomesticEnquiry  LookupInclude
```
ProductRow.getLookup().items.forEach(x => {
                var i = Q.toId(x);
                if (ProductRow.getLookup().itemById[i].DomesticEnquiry == this.form.DomesticEnquiry.Value) {
                    var name = ProductRow.getLookup().itemById[i].Name
                    obj.push({ BusinessTripServiceId: i, BusinessTripServiceName: name });
                }
            })
```

**Comment by Shraddha996** [comment]
@Zahar661  will you please tell me in which file I should write this code?
If you have any link similar to this then please share.
