### ISSUE TITLE
Coloring in a multi column dialog form ?

### ISSUE THREAD

**Issue by GAdji2005** [volkanceylan/Serenity#3775]
Hi there

    Have been using Serenity for some data entry forms and display of data.
is there a simple way to color - multi column dialog form fields, like a vertical section in a form ?

  for example all first [OneThirdWidth] fields in a blue box section
  all second [OneThirdWidth] fields in a white box section  
  and all third [OneThirdWidth] fields in a green box section 

Thanks for any help ...

**Comment by Zahar661** [comment]
So?
![image](https://user-images.githubusercontent.com/26430136/43076706-bb59a2c4-8e8d-11e8-9fe4-8f90844fb17f.png)

**Comment by GAdji2005** [comment]
Hii 
  
Yes, something similar to that... 

   Did you use the template index html ? 

Thanks again

**Comment by Zahar661** [comment]
CSS 
```
.s-Reports-PlanFactContractDialog {
    > .size {
        width: 800px;
    }

    .caption {
        width: 200px;
    }

    .plan, .DogovorStateName, .PlanWorkNumber, .Summa, .DebetSaldo, .DebetFact, .Act {
        flex: auto;
        width: 50%;
    }

    .fact, .saldo {
        flex: auto;
        width: 25%;

        .caption {
            display: none;
        }
    }

    .fact {
        background-color: #b8e88c;
    }

    .plan {
        background-color: #8cccea;
    }

    .saldo {
        background-color: #c4c6c7;
    }
}
```
![image](https://user-images.githubusercontent.com/26430136/43077541-715d8ce6-8e90-11e8-94c2-595cb38f5a19.png)

**Comment by GAdji2005** [comment]
Thanks
   
    Where did u plant the css class? 
 Do you think it will work in the panel type dialog form ?
