### ISSUE TITLE
Virtaul keyboard in Login

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#3776]
Hi i am a newbie to serene ... How can I integrate a virtual keyboard at Login screen.? 
Please help... Thanks in advance .

**Comment by Zahar661** [comment]
https://mottie.github.io/Keyboard/

**Comment by vinaysalian** [comment]
Thanks for the help

**Comment by vinaysalian** [comment]
i am trying to use jquery keyboard in Select 2 Search . It allows typing text but it is not filtering items from drop down. I am able to filter the items when typing text  but unable to do so using Jquerykeyboard, Please help .. Thanks in advance .

**Comment by vinaysalian** [comment]
Can anyone help out ? Struggling since 3 days

**Comment by volkanceylan** [comment]
This is not a Serenity issue.
