### ISSUE TITLE
How to Bind Grid on lookup selection

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3778]
hello everyone!
I am having problem with binding a grid
![capture](https://user-images.githubusercontent.com/40484328/43122535-0c684c22-8f3f-11e8-99e2-a5713c821fda.PNG)
here you can see the lookup of enquiry table and each enquiry contains some products 
![capture1](https://user-images.githubusercontent.com/40484328/43122591-3e55ff5e-8f3f-11e8-8c94-f6f0ed22a6b4.PNG)
And on that enquiry selection i want to display all products in this grid
anyone have solution then please help

**Comment by ga5tan** [comment]
just use build in filtering feature

**Comment by AbhishekhHugar** [comment]
hey @ga5tan 
can you explain it in detail or give a reference with an example ?

**Comment by ga5tan** [comment]
there is crapload of examples on demo site.
But this one has extra customization of QuickFilters:
https://serenity.is/demo/BasicSamples/QuickFilterCustomization

**Comment by AbhishekhHugar** [comment]
hey @ga5tan 
the link you sent is for grid.ts  
and i have to bind the data on dialog.ts
