### ISSUE TITLE
Date and DateTime formatting

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#378]
Hi Volkan,
I'm trying to customize date and datetime format both in a grid and in a dialog, but without any success...I was playing with DateTimeFormatter and DisplayFormat attributes but I'm doing something wrong because the date and datetime are always displayed in the same format...
Moreover, there is any way to hide the date/time picker when such fields is ReadOnly(true) ?
Or it's better to force the field to use another editor type? I tried to force a datetime field with a StringEditor but once again I don't know how to control the output format (that in such case in something like "dateTtime".

Edit: DisplayFormat do the job on grids.

Thanks
Regards

**Comment by volkanceylan** [comment]
Columns and editors are different things. DisplayFormat works on columns. Editors uses server Culture, not UI culture. This culture info is transferred to script side from LayoutHead.cshtml.

```html
< script type="application/json" id="ScriptCulture">@Html.Raw(Serenity.JSON.Stringify(new ScriptCulture()))</ script>
```

You may change culture in web.config, or override ScriptCulture settings transferred to client side here, e.g. new ScriptCulture { DateFormat = .... }

**Comment by marcobisio** [comment]
Copy that!
But which is the right approach to show a date/datetime readonly calculated field on a dialog (for example LastUpdate or Created) with a custom format and without (I mean hidden and not disabled) the time picker icon?

Thanks in advance

**Comment by volkanceylan** [comment]
ReadOnly should hide button, what is version you are using??

**Comment by volkanceylan** [comment]
Not hide disable actually

**Comment by marcobisio** [comment]
Exactly the picker is disabled and not hidden.
I'm trying to hide the picker because such date/datetime fields are always readonly in my dialog...perhaps I can force a StringEditor? In that way I obtain a disabled control without picker (obviously), but I haven't control on the output format (that is something like "dateTtime").
Any suggestion to achieve that result/behaviour?

Thanks in advance
Regards

**Comment by volkanceylan** [comment]
I don't understand why its so important to hide picker image but you can hide it with CSS
.s-MyDialog .MyReadOnlyField .ui-datepicker-trigger { display: none }
Check classes, i don't remember what was it

**Comment by marcobisio** [comment]
It's important  (at least for us) to give users the feeling that such field will never be editable.

Thanks

**Comment by mantiklas** [comment]
In hiding  the  disable  button.. add a stringfield  in your row then pass the value of the datetime  through expression..

**Comment by amnippon** [comment]
Thanks @volkanceylan it works,

```
<script type="application/json" id="ScriptCulture">
    @Html.Raw(Serenity.JSON.Stringify(new ScriptCulture { DateFormat = "dd/MM/yyyy" }))
</script>
```

**Comment by sasikr** [comment]
> Thanks @volkanceylan it works,
> 
> ```
> <script type="application/json" id="ScriptCulture">
>     @Html.Raw(Serenity.JSON.Stringify(new ScriptCulture { DateFormat = "dd/MM/yyyy" }))
> </script>
> ```

Excuse me, where is this code placed?

**Comment by amnippon** [comment]
@sasikr 
Put that code in \Views\Shared\_LayoutHead.cshtml
don't forget to erase code 

`@Html.Raw(Serenity.JSON.Stringify(new ScriptCulture()))`

**Comment by amnippon** [comment]
@sasikr 
Put that code in \Views\Shared\_LayoutHead.cshtml
don't forget to erase this code 
`@Html.Raw(Serenity.JSON.Stringify(new ScriptCulture()))`
