### ISSUE TITLE
Start with empty grid

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3782]
Hi

I need Grid.ts to start out with empty (unqueried) grid. Dotn wanna waste time with getting some infiltered first page, but rather query DB only after users chooses some filters. Any ideas how to do that?

THX

**Comment by edwardch** [comment]
Try something like this in XYZEndpoint:

```c#
public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
{
    // Only return data when Criteria is set
    if (request.Criteria is BaseCriteria)
        return new MyRepository().List(connection, request);

    // Otherwise return an empty ListResponse
    return new ListResponse<MyRow>();
}
```

I imagine you want to do this because it's a really big table or slow view?

**Comment by ga5tan** [comment]
THX @edwardch 
Problem is, your condition (request.Criteria is BaseCriteria) is always true.
There is "Username = @p1" there


request has EqualityFilter, but that also contais some values :(

**Comment by edwardch** [comment]
Hmm, I tried it out and it worked for me. There was no Username criteria there. Do you have this as a field in your table?

Try and play around with that to see if you can get it to work. I’m in a limited internet access area at the moment and will check back next week.

Sent from my phone

On 27 Jul 2018, at 23:44, Juraj Benadik <notifications@github.com<mailto:notifications@github.com>> wrote:


THX @edwardch<https://github.com/edwardch>
Problem is, your condition (request.Criteria is BaseCriteria) is always true.
There is "Username = @p1<https://github.com/p1>" there

request has EqualityFilter, but that also contais some values :(

**Comment by ga5tan** [comment]
Oh, I tried.

I'll give it one more shot. Worry not, I appreciate your suggestions. Please let me know if you come up with something else.
Yes, username is field in table.

**Comment by ga5tan** [comment]
@edwardch did u have a chance to look at it please?

**Comment by edwardch** [comment]
Unfortunately I haven't had any time to look at this. It seems it's because you have the user field in your table it will always be in the request. 

See if you can inspect all the variables in question on your connection/request objects, and if you can't find anything neat, cheat :/

Sorry I can't be of more help at the moment.
