### ISSUE TITLE
Execute sql query inside select2editor

### ISSUE THREAD

**Issue by masudijames** [volkanceylan/Serenity#3783]
Hi
Based on example of populating select2 with hardcoded values. Instead I want to query database within select2editor. The result is a list to be populated to select2 drop down. How to do it. 
Your help is much appreciated

**Comment by Estrusco** [comment]
Why you don't use LookupEditor?

**Comment by masudijames** [comment]
I wanted to populate dropdown based on condition something like SeaFood Categories in Northwind.
There it was
x.CategoryName === 'Produce' || x.CategoryName === 'Seafood');
but I want something like
x.CategoryName === 'Produce' || x.CategoryName === **this.form.dropdownName**);

this.form.dropdownName shouldbe selected first then execute the editor

**Comment by volkanceylan** [comment]
You can't execute SQL there.

**Comment by JohnRanger** [comment]
Hi - I have exactly the same requirement. It surely should be possible within the onClick event of the Dropdown to call a service endpoint on server side, feed it with the value of this.form.dropdownName and then return a list with ids and text which then can be used to populate the dropdown.

**Comment by stixoffire** [comment]
@masudijames @JohnRanger  I would love to see an example of how to do this. I am trying to implement a similar function. I have 2 drop downs for Item and Vendor, if a vendor is selected then the unit price is different - so I need to be able to filter my result by vendorId.
