### ISSUE TITLE
properly closing transaction

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3784]
I am using another DAL in Endpoint , so I close transaction like this:

```
//finish transaction for .netTiers code to take over
            uow.Connection.GetCurrentActualTransaction().Commit();
```

It works ok, but I end up with error, when at the end Serenity wants to commit transaction which was already commited and my servicecall ends up with RED error.

Any Idea how this could be solved?

thx

**Comment by volkanceylan** [comment]
No, then your endpoint shouldn't use IUnitOfWork parameter, remove that.
