### ISSUE TITLE
how to call jQuery

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3785]
I found this sample to hide radio button:

$("label:contains('Invoice')").css("display", "none");

but I don't know how to call it in Serenity.

Any ideas?

thx

**Comment by ga5tan** [comment]
I figured this one out:

this.element.find("label:contains('Invoice')").css("display", "none");

works ok, but I'd prefer to base search on something else, cause item description can possibly change with different language

**Comment by Shraddha996** [comment]
Hi!
@ga5tan 
Actually, having the same issue
want to hide the radio button from the Transaction grid while editing records

Thanks in advance.

**Comment by ga5tan** [comment]
So? Try this one, or get inspired by tab hiding code.
In browser check what div or container radios are and hide it, or hide column. Do u edit in grid or dialog?

**Comment by Shraddha996** [comment]
thanks, @ga5tan sir  
I already try hiding by div and container radios but it's just not working
I  haven't seen any sample for hiding DetailList grid columns from the master dialog

**Comment by ga5tan** [comment]
sorry, I have no better idea than hiding.
inspiration was to be taken from tab hiding, not DetailList grid columns hiding.
but there must be some way to hide columns as well, since there is column picker...
