### ISSUE TITLE
Stream field type not supported on MasterDetailRelation

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#379]
Hi Volkan,
I was fighting with a master detail dialog (like what you did for Orders - OrdersDetail) but I get an exception because (I think) the Stream field type is not supported.
Removed such field and everything is working fine...
Not a big issue for me because I can change the field type both in the application and also in the database, but I decided to open an issue just to inform you...

Thanks
Regards

**Comment by volkanceylan** [comment]
How do you show this field in dialog?

**Comment by marcobisio** [comment]
Like orders details in order dialog: a grid inside the  dialog itself.
The field is a "text" on db (sql server) and sergen mapped such field as a Stream.
When I try to save the "order" from the dialog I get the exception even if I haven't modified the details.
The other way round if there aren't details (so the table is empty) then no exception is raised.

**Comment by volkanceylan** [comment]
So you can use a string field for that field.

**Comment by jsbUSMC** [comment]
Like @volkanceylan just mentioned, if you go into your `XYZRow.cs` and alter the field from stream to string, things should work for you. 

```c#
// ...
public class RowFields : RowFieldsBase
{
    public readonly StreamField myField; // this is the field to change
    public readonly StringField myField; // you can also use 'static' instead of 'readonly'
}
```

**Comment by marcobisio** [comment]
Thanks @volkanceylan and thanks @jsbUSMC: I already did the change and now is working properly!
I opened the issue just to inform the developers behind the project of such (wierd?) behaviour.

Thanks again
Regards

**Comment by volkanceylan** [comment]
Probably sergen has mapping for ntext -> StringField but not text -> StringField, i'll add later but why still use "text" in decade of unicode?

**Comment by marcobisio** [comment]
I'm not sure but I think that such table was generated automatically from a data import/migration from mysql to sql server.
