### ISSUE TITLE
Issue with dialog when sizing browser

### ISSUE THREAD

**Issue by mikevbaker** [volkanceylan/Serenity#3790]
I'm just getting started and going through the tutorial. I found an issue when sizing the browser while a dialog is open.
Steps:
Run tutorial up to [customizing_movie_interface](https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/customizing_movie_interface.html).
Size the browser width smaller until the dialog converts to the full screen mode (I didn't use F12 as it is in the picture)
Size the browser width larger until the dialog comes back out of full screen and into the floating mode.

Issue: The dialog positions itself below the grid instead of returning to its original absolute position.
Expected: The dialog should save its absolute position and return to that when coming out of the full screen mode.

Scroll down to find the dialog and drag it away from the edge and up.
Attempt to size the dialog by dragging any edge.

Issue: Dialog snaps back down below the grid.
Expected: Dialog should size in place.

**Comment by volkanceylan** [comment]
I dont think such a scenario is common, so no need to worry about.
