### ISSUE TITLE
GridPersistanceFlags not being recognized

### ISSUE THREAD

**Issue by JoeyFerg** [volkanceylan/Serenity#3791]
I was using window storage for my persisting settings, which was working great:

```
protected getPersistanceStorage(): Serenity.SettingStorage {  
     return new Common.UserPreferenceStorage();  
}
```

But then I realized I didn't want QuickFilter values to be saved.

Per the [Persisting Settings page](https://volkanceylan.gitbooks.io/serenity-guide/content/grids/persisting_settings.html), I tried to add the following:

```
protected getPersistanceFlags(): GridPersistanceFlags {
     return {
          columnWidths: true,
          columnVisibility: true,
          sortColumns: true
     }
}
```

but I am getting these errors:

```
warning TS2304: Cannot find name 'GridPersistanceFlags'.  
warning TS4055: Return type of public method from exported class has or is using private name 'GridPersistanceFlags'.
```

I can't figure out why it won't recognize GridPersistanceFlags. Any ideas?

**Comment by volkanceylan** [comment]
Serenity.GridPersistanceFlags

**Comment by JoeyFerg** [comment]
Ah, that makes sense. Thank you!
