### ISSUE TITLE
Windows Explorer Widget

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#3793]
Hello !
Thanks for helping out for suggesting  jquery  virtual keyboard at login last time   .It works great.
Can we provide a Windows explorer widget where i can control to which folder where the pdfs and documents getting downloaded and other folders cannot be accessed or visible .I hope my question is clear. Thanks for the help in advance

**Comment by volkanceylan** [comment]
No :)

**Comment by vinaysalian** [comment]
Ok .. Thanks
