### ISSUE TITLE
RadioButton Error

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3794]
Hi! I want a radio button on my Form.cs but getting an error on Labels

![capture2](https://user-images.githubusercontent.com/39983941/43309513-9b24fbe4-91a2-11e8-8e29-3a2f4beb6e72.PNG)

**Comment by Estrusco** [comment]
You can use enum

[RadioButtonEditor]
public YourEnum FormDescription {get; set;}

**Comment by DevAdrian02** [comment]
did not manage to make a radiobutton, does anyone know how to create it?
