### ISSUE TITLE
Open dialog on RadioButton click

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3795]

**Comment by Shraddha996** [comment]
hey..!
![capture3](https://user-images.githubusercontent.com/39983941/43322589-aca542dc-91cc-11e8-9d19-8baedf319ca0.PNG)
 
I want to redirect two different forms on these two Radio Button click
Is anyone have solution for this?

**Comment by volkanceylan** [comment]
This is a javascript question
