### ISSUE TITLE
Multipleimageuploadeditor read only issue ?

### ISSUE THREAD

**Issue by GAdji2005** [volkanceylan/Serenity#3796]
Hii there 

     in relation to the issue number #3157  is there a fix at the moment ? 

readonly for the  multipleimageuploadeditor still shows the delete button ...

    can this delete button,  be removed somehow ?

Thanks

**Comment by GAdji2005** [comment]
normally yes 
but the button is embedded in the element - and we would like to keep the element ...

  using entities at the moment to keep the information same before and after save - 
it is one kind of solution but not the best one :/

**Comment by ga5tan** [comment]
just hide the button then

**Comment by volkanceylan** [comment]
Fixed, will be in next version.
