### ISSUE TITLE
you advise on using serenity for developing hospital database 

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3797]
Hi users of the serenity!
I am planning to develop a hospital database which will include different activities of a hospital.
I need your advise and suggestion if serenity would be a proper option for this.  I mean serenity is a great tool, fast and good but i wonder if i may face some functionality during development that i won't be able to do using Serenity.

Thank you

**Comment by brunobola** [comment]
Serenity isn't a database its a platform that can use several database engines.
It can be used for almost any type of development purposes so depending your skills you can achieve almost any features.

**Comment by ms4hafiz** [comment]
Thank you @brunobola 
Serenity is limited only to my skill.
