### ISSUE TITLE
.net core ~/Administration/TranslationGrid.ts QuickSearchInput bug

### ISSUE THREAD

**Issue by tky753** [volkanceylan/Serenity#3799]
.net framework project `Serenity.GridUtils.addQuickSearchInputCustom` method will auto execute **done** function after **onSearch**,
.net core project does not, so we need to execute **done** manually : 
```
protected createQuickSearchInput() {
            Serenity.GridUtils.addQuickSearchInputCustom(this.toolbar.element,
                (field, searchText, done) => {
                    this.searchText = searchText;
                    this.view.setItems(this.view.getItems(), true);
                    done(true);
                });
        }
//done is required.
```
Otherwiese, in `~/Administration/Translation` page, the cusor will be `wait` after using **QuickSearch**.

BTW, `addQuickSearchInputCustom` is also used in `RoleCheckEditor` and `PermissionCheckEditor`
and `CheckLookupEditor`

**Comment by volkanceylan** [comment]
.NET Core uses same set of scripts.

**Comment by tky753** [comment]
@volkanceylan  Okey, I'm sorry, I found my .net framework Serene project's version is very old.

And I just init a new .net core Serene project, and I can reproduce the same issue.

I found the old version `addQuickSearchInputCustom` is:
```
//file   in   Serenity.Script.UI.js
$Serenity_GridUtils.addQuickSearchInputCustom = function(container, onSearch, fields) {
	$Serenity_GridUtils.addQuickSearchInputCustom$1(container, function(x, y, z) {
		onSearch(x, y);
		z(true);//auto execute z/done function
	}, null);
};
```

and the new version is:
```
function addQuickSearchInputCustom(container, onSearch, fields) {
            var div = $('<div><input type="text"/></div>')
                .addClass('s-QuickSearchBar').prependTo(container);
            if (fields != null && fields.length > 0) {
                div.addClass('has-quick-search-fields');
            }
            new Serenity.QuickSearchInput(div.children(), {
                fields: fields,
                onSearch: onSearch
            });
        }
```
I'm not sure, but it seems that the new version does not execute done function automatically.

**Comment by tky753** [comment]
@volkanceylan  in page https://serenity.is/demo/Administration/Translation
I can reproduce it by inputting anything in **QuickSearch**, then the cusor will always be **wait**.
