### ISSUE TITLE
Dialog fields not shown as expected

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#380]
I have the code below. I expected the DeptNbr to be disabled/optional and FundNbr to have a drop down box. It is not the result I am getting. Do you see anything wrong with the code?

    public sealed class AppropriationBudgetRow : Row, IIdRow, INameRow, IMultiDepartmentRow
    {

        [DisplayName("Dept Nbr"), Column("dept_nbr"), Size(32), ForeignKey("[dbo].[department]", "dept_nbr"), LeftJoin("jDeptNbr"), QuickSearch, Updatable(false), Insertable(false)]
        public String DeptNbr
        {
            get { return Fields.DeptNbr[this]; }
            set { Fields.DeptNbr[this] = value; }
        }

        [DisplayName("Dept Name"), Expression("jDeptNbr.[dept_name]"), QuickSearch]
        public String DeptNbrName
        {
            get { return Fields.DeptNbrName[this]; }
            set { Fields.DeptNbrName[this] = value; }
        }

        [DisplayName("Fund Nbr"), Column("fund_nbr"), Size(32), NotNull, ForeignKey("[dbo].[fund]", "fund_nbr"), LeftJoin("jFundNbr"), TextualField("FundNbrName")]
        [LookupEditor(typeof(FundRow))]
        public String FundNbr
        {
            get { return Fields.FundNbr[this]; }
            set { Fields.FundNbr[this] = value; }
        }

        [DisplayName("Fund Name"), Expression("jFundNbr.[fund_name]")]
        public String FundNbrName
        {
            get { return Fields.FundNbrName[this]; }
            set { Fields.FundNbrName[this] = value; }
        }
....
```
    [FormScript("LCBudgets.AppropriationBudget")]
    [BasedOnRow(typeof(Entities.PositionBudgetRow))]
    public class AppropriationBudgetForm
    {
        public Int32 FiscalYear { get; set; }
        public String DeptNbr { get; set; }
        public String FundNbr { get; set; }
        public String AcctCategory { get; set; }
        public String Activity { get; set; }
        public Double Balance { get; set; }
        public Double RequestedBudget { get; set; }
        public Boolean Finalized { get; set; }
        public Boolean Exported { get; set; }
        public DateTime InsertDate { get; set; }
        public String InsertUser { get; set; }
        public DateTime UpdateDate { get; set; }
        public String UpdateUser { get; set; }
    }

```

![2016-03-09_131951](https://cloud.githubusercontent.com/assets/17013052/13647428/c7cffa4c-e5f9-11e5-8b6e-097ee59e22f8.png)

**Comment by volkanceylan** [comment]
[BasedOnRow(typeof(Entities.PositionBudgetRow))]

**Comment by c9482** [comment]
You have an eagle eye, my friend! Thanks again.
