### ISSUE TITLE
Password Expiration

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3804]
Hi

I would like to implement expiration of password.
Say after 30 days users are forced to change their passwords.
Any hints as to where to place code, so it will be compatible with future updates?

**Comment by Zahar661** [comment]
hi. Modules\Administration\User\Authentication\AuthenticationService.cs Validate

**Comment by ga5tan** [comment]
@Zahar661  yesh, it's easy to check there, but how do I propagate it out out back to login form and possibly forward to change pass page ???
