### ISSUE TITLE
is User logged in in TS

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3806]
How can I see if user is logged in in TS?
I tried to handle it somehow, but none works. I always end up with red error (access denied) when user is not logged in. It work ok when user is logged in:

```
try {
                if (!Authorization.userDefinition == null) Q.alert("null");
            }
            catch (e) {
                
                    console.log('logged out exception');

            }

```

**Comment by volkanceylan** [comment]
You can't access user information if a user is not logged in. That's only meant to be used in admin pages. Add a flag to your cshtml page.

**Comment by ga5tan** [comment]
I dont want to access user info. Just want to see, if he is logged in or not.
simply detect on FE, if in public region or already logged in
