### ISSUE TITLE
BUG? updateInterface not called in embedded dialog

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3807]
I am inserting/embedding dialog in Grid. It all works fine, but for some reason protected updateInterface() function never gets called (along with afterLoadEntity)

Is this desired behavior?

Embedding looks like this:

```
this.advFilterDialog = new IDI5.Reports.AdvancedFilterDialog();
this.advFilterDialog.element.removeClass('hidden').appendTo(sDivName);
```

**Comment by volkanceylan** [comment]
If you dont call load why it should update

**Comment by ga5tan** [comment]
@volkanceylan oh, I see. Is there document with event map? What gets called when?

**Comment by FranciscoValdesGutierrez** [comment]
Is there document with event map? What gets called when?

**Comment by ga5tan** [comment]
@FranciscoValdesGutierrez there used to be list of entity events in Wiki here, but I dont know of any for Dialogs...
