### ISSUE TITLE
Search box editor

### ISSUE THREAD

**Issue by hairangsua** [volkanceylan/Serenity#3808]
Hi everyone. 
How i can make editor like this
https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/SearchAndEditing/jQuery/Light/

i want to search some record in a list data. user can choose one or still define 1 new. It look like lookup editor but still can input like string editor.

**Comment by dfaruque** [comment]
`[LookupEditorI(typeof(kkk), AutoComplete=true)]`

**Comment by hairangsua** [comment]
Oh my...Thank u very much...............:D
