### ISSUE TITLE
How to Grid Display value from Id

### ISSUE THREAD

**Issue by write4alive** [volkanceylan/Serenity#3809]
Hello ,
I have 2 classes Customer and gender , in customer grid I can see customer information like name , surname  and Gender , I connect them with genderid. Need to see Gender Definition in Customer List but I can see only it's id.

![1](https://user-images.githubusercontent.com/16669517/43577073-8386f1f8-9653-11e8-921e-4e0547237b6f.PNG)

I know its quite easy question but cant figure it put , How can I get value from it's id that's shown in grid.

**Customer Columns;**
[ColumnsScript("Cmpny1.Customer")]
    [BasedOnRow(typeof(Entities.CustomerRow), CheckNames = true)]
    public class CustomerColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 Id { get; set; }
        [EditLink]
        [DisplayName("Ad")]
        public String Ad { get; set; }

        [DisplayName("Soyad")]
        public String Soyad { get; set; }

        [DisplayName ("Cinsiyet")]
        public String Cinsiyetid { get; set; }
}
**Customer Rows;**
 [DisplayName("Cinsiyet"), ForeignKey(typeof(GenderRow)), LeftJoin("g")]
        [LookupEditor(typeof(Cmpny1.Entities.GenderRow))]
        public Int32? Cinsiyetid
        {
            get { return Fields.Cinsiyetid[this]; }
            set { Fields.Cinsiyetid[this] = value; }
        }

**Customer Editor ;**
  @Serenity.Decorators.registerClass()
    export class CustomerEditor extends Common.GridEditorBase<CustomerRow> {
        protected getColumnsKey() { return "Cmpny1.Customer"; }
        protected getDialogType() { return CustomerDialog; }
        protected getLocalTextPrefix() { return CustomerRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        validateEntity(row, id) {
            row.cinsiyetid = Q.toId(row.Id);

            row.cinsiyetid = GenderRow.getLookup().itemById[row.Id].Tanim;

            return true;
        }

**Gender Column;**
     [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 Id { get; set; }
        [EditLink]
        public String Tanim { get; set; }

**ServerTypings for Gender;**
   export namespace GenderRow {
        export const idProperty = 'Id';
        export const nameProperty = 'Tanim';
        export const localTextPrefix = 'Cmpny1.Gender';
        export const lookupKey = 'Cmpny1.Gender';
		
	export function getLookup(): Q.Lookup<GenderRow> {
            return Q.getLookup<GenderRow>('Cmpny1.Gender');
        }
        export namespace Fields {
            export declare const Id;
            export declare const Tanim;
        }

**Comment by Estrusco** [comment]
In CustomerRow you can add an expression field for Cinsiyet description

Row
```cs
[DisplayName("Cinsiyet"), ForeignKey(typeof(GenderRow)), LeftJoin("jCinsiyet")]
[LookupEditor(typeof(Cmpny1.Entities.GenderRow))]
public Int32? Cinsiyetid
{
    get { return Fields.Cinsiyetid[this]; }
    set { Fields.Cinsiyetid[this] = value; }
}

[Expression("jCinsiyet.YourDescriptionField")]
public String jCinsiyetDescr
{
    get { return Fields.jCinsiyetDescr[this]; }
    set { Fields.jCinsiyetDescr[this] = value; }
}
```

Column
```cs
[ColumnsScript("Cmpny1.Customer")]
[BasedOnRow(typeof(Entities.CustomerRow), CheckNames = true)]
public class CustomerColumns
{
    [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
    public Int32 Id { get; set; }
    [EditLink]
    [DisplayName("Ad")]
    public String Ad { get; set; }

    [DisplayName("Soyad")]
    public String Soyad { get; set; }

    [DisplayName ("Cinsiyet")]
    public String jCinsiyetDescr { get; set; }
}
```

Alsso read manual https://volkanceylan.gitbooks.io/serenity-guide/

**Comment by write4alive** [comment]
thank you !

**Comment by chrisomeara** [comment]
for anybody coming here still trying to find a solution to this issue, I hope I can save you lot of time by highlighting this last section in the Manual (https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/the_cast_and_characters_they_played.html)

"In our MasterDetailRelation attribute, we specified an extra property, **IncludeColumns**:

[MasterDetailRelation(foreignKey: "MovieId", **IncludeColumns = "PersonFullname"**)]
This ensures that PersonFullname field on cast list is selected on retrieve. Otherwise, it wouldn't be loaded as only table fields are selected by default. When you open a movie dialog with existing cast list, full name would be empty.
Make sure you add any view field you use in grid columns to IncludeColumns. Put comma between names of multiple fields, e.g. IncludeColumns = "FieldA, FieldB, FieldC".
