### ISSUE TITLE
How to  show the total amount  in order page using serenity service

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#381]
Requirment：
The picture below is what I want to implement .Calculate the sum of some decimal columes ,and show the total data in the top  right .

**Comment by ChenZhaobin** [comment]
Step 1: Embed html elements   to show total value
Open OrderLogIndex.cshtml,add somecode there:
**<script type="text/javascript">
    jQuery(function () {
        new ZebraPartner.Business.OrderLogGrid($('#GridDiv'), {}).init
        {
            addLabel();
        }
        Q.initFullHeightGridPage($('#GridDiv')) 
    }); 
    function addLabel()
    {
        $(".tool-buttons").append('<div style="float:right;margin-right:70px:padding-top:5px"><p>&nbsp;Total:<label id="sumtotal" ></label>&nbsp;Goods:<label id="sumgoods"> </label>&nbsp;Shipping:<label id="sumshipping">  </label>&nbsp;Taxes:<label id="sumtaxes"> </label>&nbsp;</p></div>');
    }
</script>**

**Comment by ChenZhaobin** [comment]
Step 1: Embed html elements   to show total value
Open OrderLogIndex.cshtml,add somecode there:
<script type="text/javascript">
    jQuery(function () {
        new ZebraPartner.Business.OrderLogGrid($('#GridDiv'), {}).init
        {
            addLabel();
        }
        Q.initFullHeightGridPage($('#GridDiv')) 
    }); 
    function addLabel()
    {
        $(".tool-buttons").append('<div style="float:right;margin-right:70px:padding-top:5px"><p>&nbsp;Total:<label id="sumtotal" ></label>&nbsp;Goods:<label id="sumgoods"> </label>&nbsp;Shipping:<label id="sumshipping">  </label>&nbsp;Taxes:<label id="sumtaxes"> </label>&nbsp;</p></div>');
    }
</script>

**Comment by ChenZhaobin** [comment]
Step 1: Embed html elements   to show total value
Open OrderLogIndex.cshtml,add somecode there:
 [script type="text/javascript">
    jQuery(function () {
        new ZebraPartner.Business.OrderLogGrid($('#GridDiv'), {}).init
        {
            addLabel();
        }
        Q.initFullHeightGridPage($('#GridDiv')) 
    }); 
    function addLabel()
    {
        $(".tool-buttons").append('<div style="float:right;margin-right:70px:padding-top:5px"><p>&nbsp;Total:<label id="sumtotal" ></label>&nbsp;Goods:<label id="sumgoods"> </label>&nbsp;Shipping:<label id="sumshipping">  </label>&nbsp;Taxes:<label id="sumtaxes"> </label>&nbsp;</p></div>');
    }
[/script>

**Comment by ChenZhaobin** [comment]
Step 2：Build serenity service
2.1 Create Action Method in OrderEndPoint  (return subclass of ServiceResponse than you can build, transform templates and will have a OrderService.GetSumService method.)
         [Route("GetSum")]
        public OrderSumResponse GetSum(IDbConnection connection, ListRequest request)
        {
            var data = List(connection, request).Entities;
            decimal totalPrice = 0;
            decimal totalShipping = 0;
            decimal totalTaxes = 0;
            decimal total = 0; 
            foreach (var item in data)
            {
                totalPrice += item.TotalPrice== null ? 0 : (decimal)item.TotalPrice;
                totalShipping += item.TotalShippingFee == null ? 0 : (decimal)item.TotalShippingFee;
                totalTaxes += item.TotalTaxesFee == null ? 0 : (decimal)item.TotalTaxesFee;
                total += item.Total == null ? 0 : (decimal)item.Total;
            } 
            return new OrderSumResponse
            {
                Total = total,
                TotalDuty = totalTaxes,
                TotalPrice = totalPrice,
                TotalShippingFee = totalShipping
            };
        }

**Comment by ChenZhaobin** [comment]
Step 3：Handle the script file

3.1 After step1,transform templates,then you will use  OrderService.GetSumService  in OrderGrid Class.
3.2 Overrid method  OnViewProcessData() in OrderGrid
there are many client side method you can override in XXGrid.cs thanks to Saltarelle  which you can use to transform .cs to .js
the method OnViewSubmit() will happen just before the page events are triggered,the method OnViewProcessData() will happen just after the page events triggered but not render the data to view page.
So we should override method  OnViewProcessData() so that we can handle the  data before the user see it  in page.

   protected override ListResponse<OrderLogRow> OnViewProcessData(ListResponse<OrderLogRow> response)
        { 
            return base.OnViewProcessData(response);
        } 
3.3 Implement OnViewProcessData() method

In this method,we should init  request.Take request.Skip and so on   to get all rows  meet the filter condition,then use FillView to change total label's innerHtml

     protected override ListResponse<OrderLogRow> OnViewProcessData(ListResponse<OrderLogRow> response)
        {
            var grid = (IDataGrid)this;
            var request = Q.DeepClone((ListRequest)(grid.GetView().Params));
            request.Take = 0;
            request.Skip = 0;
            var sortBy = grid.GetView().SortBy;
            if (sortBy != null)
                request.Sort = sortBy;
            request.IncludeColumns = new List<string>();
            foreach (var column in grid.GetGrid().GetColumns())
                request.IncludeColumns.Add(column.Identifier ?? column.Field);
            OrderLogService.GetSum(request, ((result) => 
                  this.FillView(result) 
               ));
            return base.OnViewProcessData(response);
        } 

        private void FillView(Modules.OrderSumResponse  result)
        { 
            jQuery.Select("#sumtotal")[0].InnerHTML = "<font color=\"#0000FF\">" + "$" + result.Total + "</font>";
            jQuery.Select("#sumgoods")[0].InnerHTML = "<font color=\"#0000FF\">" + "$" + result.TotalPrice + "</font>";
            jQuery.Select("#sumshipping")[0].InnerHTML = "<font color=\"#0000FF\">" + "$" + result.TotalShippingFee + "</font>";
            jQuery.Select("#sumtaxes")[0].InnerHTML = "<font color=\"#0000FF\">" + "$" + result.TotalDuty + "</font>";
        }

3.4      Transform templates  and you will get what you want.

**Comment by volkanceylan** [comment]
Thanks @ChenZhaobin for sharing your solution.
