### ISSUE TITLE
to deploy serenity application to IISServer

### ISSUE THREAD

**Issue by Tushar5292** [volkanceylan/Serenity#3810]
![screenshot 2](https://user-images.githubusercontent.com/40889976/43629561-3ab96cd0-971b-11e8-8bdc-f78f145afed1.png)

Hello All.
I want to deploy serenity application to IIS server but facing the issue that account/login page is not displaying.How should I redirect to this page after deployment.Is there any step is missing.

![screenshot 3](https://user-images.githubusercontent.com/40889976/43629682-94c9959c-971b-11e8-97c8-d2d2213781e3.png)

**Comment by Estrusco** [comment]
Have you set folder as ASP application?

![image](https://user-images.githubusercontent.com/16304015/43631710-47cdaa7e-9704-11e8-8444-88ae2317f6e2.png)

**Comment by volkanceylan** [comment]
What you created is a folder not application
