### ISSUE TITLE
Need architecture advice about Serenity application

### ISSUE THREAD

**Issue by write4alive** [volkanceylan/Serenity#3812]
In my example ; I got different companies and different users using exacly same modules , is it possible to make it without using multitenancy architectirue , one module for all different users ?

Should I add new modules for company2 or what can I do for much easy to manage my code. Is there only way to do is multitenancy ? 

My databases like ;
company1
company2
company3
so on ...
![2222](https://user-images.githubusercontent.com/16669517/43630159-2648975c-9708-11e8-86a7-ba73713210b7.PNG)

My english not really good , if I couldn't describe what mean , please ask me to correct.

**Comment by Estrusco** [comment]
If you want use different db for same application, see this previous issue https://github.com/volkanceylan/Serenity/issues/3661

Why you want replicate code for every company?

**Comment by write4alive** [comment]
I want to use same code and different database instaces if possible but I just don't want to use multitanancy  ; same application and tenantId filtering.

**Comment by Estrusco** [comment]
In previous post there is the link that answer your question. Solution is IIS location functionality and virtual directory

**Comment by write4alive** [comment]
I check posts and what kind of implementation I need ? ,in webconfig I understand what I need to do but there is some more modifications in code too , Each row class has own connection keys written inside I think ı need to change them right ?

**Comment by Estrusco** [comment]
I have now created new wiki entry

https://github.com/volkanceylan/Serenity/wiki/One-application-with-different-database-per-customer

**Comment by write4alive** [comment]
Thank you!

**Comment by brunobola** [comment]
@write4alive You can also make another implementation using the following wiki: [Multi Database ](https://github.com/volkanceylan/Serenity/wiki/Multi-Database-Serenity)
