### ISSUE TITLE
New wiki entry

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#3813]
Hi all! 

I write this new wiki entry to help people that search for multi database application instead multy tenancy database

https://github.com/volkanceylan/Serenity/wiki/One-application-with-different-database-per-customer

**Comment by brunobola** [comment]
@Estrusco nicely done, i've created a different approach that I believe would be more beneficial to users given access to users choose in the Login the database they want to use.

![image](https://user-images.githubusercontent.com/10889019/43739224-360d6726-99bf-11e8-8f46-b4005b833c6b.png)
 
when it is 100% stable will make some wiki ;)

I believe in less code and more productivity....

**Comment by controllernet** [comment]
@brunobola ,  how's it going? And how did you get this feature something very complex ??

I need to implement something like this around here.

**Comment by brunobola** [comment]
@controllernet I'm already using that feature in a production system, it has several changes (overrides) to que cache and other behaviours to serenity (no core changes , only overrides).

When I've got this 100% maybe will give some advice on how to achieve this.
Also The actual company is always on the left preferences panel for the user to see.

**Comment by brunobola** [comment]
I've almost done testing it with the several scenarios and even introducing a fast database change using a new select that stays in the preferences tab it works as expected, also I've got to reload the login using the new database selection and it's almost 100% perfect even when it respects per database permissions as expected from a sysadmin point of view.

Will make a separate wiki when I've got it to work, ive got to fix some performance issues because I need some cookies for it to behaviour 100% correct.

**Comment by brunobola** [comment]
I've successfully done the multi-database change at logon screen:
![image](https://user-images.githubusercontent.com/10889019/44303346-8b929100-a336-11e8-92d5-0e9369ed6480.png)

Using the following changes: 

<br>

1. Create a SQL view in all the databases:

```
CREATE VIEW [dbo].[V_PRJ_Empresas] AS
SELECT ROW_NUMBER() OVER(ORDER BY name ASC) AS ID, NAME AS 'Codigo', E.IDNome AS 'Descricao'
From 
	sys.databases AS s
	LEFT JOIN PRIEMPRE.DBO.EMPRESAS E
		ON E.Codigo=RIGHT(NAME, LEN(NAME)-3)
Where 
	s.name LIKE 'PRI%' AND name NOT LIKE 'PRIEMPRE%'
```
<br>

2. Create a ServiceEndpoint descendant class:

```
public class AdvancedServiceEndpoint : ServiceEndpoint
{
	public AdvancedServiceEndpoint()
	{
		#region Reconfigura a ligação ao SQL Server
		if (Authorization.UserDefinition != null)
		{
			((UserDefinition)Authorization.UserDefinition).AtualizaLigacaoSQL();
		}
		#endregion Reconfigura a ligação ao SQL Server
	}
}
```

<br>

3. Change all Enpoints:

```
Example:
	public class LanguageController : AdvancedServiceEndpoint
```

<br>

4. LoginRequest.cs:

```
public class LoginRequest : ServiceRequest
{                        
	//[Placeholder("Escolha a empresa")]
	[DisplayName("Escolha a empresa")]
	[Required(true)]
	[LookupEditor("Tabelas.VPrjEmpresas"), Width(200)]

	...
}
```
<br>

5. UserDefinition.cs:

```
public class UserDefinition : IUserDefinition
{
	public string Id { get { return UserId.ToInvariant(); } }
	public string DisplayName { get; set; }
	public string Email { get; set; }
	public string UserImage { get; set; }
	public short IsActive { get; set; }
	public int UserId { get; set; }
	public string Username { get; set; }
	public string PasswordHash { get; set; }
	public string PasswordSalt { get; set; }
	public string Source { get; set; }
	public DateTime? UpdateDate { get; set; }
	public DateTime? LastDirectoryUpdate { get; set; }

	//Fica com a Empresa Escolhida
	public string Company { get; set; }

	public void AtualizaLigacaoSQL()
	{
		#region Reconfigura a ligação ao SQL Server
		//Configura a nova Ligação à Base de dados
		var cs = SqlConnections.GetConnectionString("Default");
		var cb = cs.ProviderFactory.CreateConnectionStringBuilder();
		cb.ConnectionString = cs.ConnectionString;

		cb["Initial Catalog"] = Company;
		SqlConnections.SetConnection("Default", cb.ConnectionString, cs.ProviderName);
		#endregion Reconfigura a ligação ao SQL Server
	}
...

```

<br>

6. AccountPage.cs:

```
[RoutePrefix("Account"), Route("{action=index}")]
public partial class AccountController : Controller
{
	[HttpPost, JsonFilter]
	public Result<ServiceResponse> Login(LoginRequest request)
	{
		return this.ExecuteMethod(() =>
		{
			request.CheckNotNull();

			var company = request.Company;

			if (string.IsNullOrWhiteSpace(request.Company))
				throw new ArgumentNullException("company");

			//Configura a nova Ligação à Base de dados
			var cs = SqlConnections.GetConnectionString("Default");
			var cb = cs.ProviderFactory.CreateConnectionStringBuilder();
			cb.ConnectionString = cs.ConnectionString;

			//Verificar se Empresa existe na instância
			string empresaSQL = string.Empty;
			using (var serverConnection = SqlConnections.New(cb.ConnectionString, cs.ProviderName))
			{
				try
				{
					serverConnection.Open();

					string databasesQuery = "SELECT Codigo FROM V_PRJ_Empresas WHERE Codigo = @name";

					empresaSQL = serverConnection.Query<string>(databasesQuery, new { name = company }).FirstOrDefault();

					//Se for o código
					empresaSQL = company;
				}
				catch (SqlException ex)
				{
					empresaSQL = string.Empty;
				}
			}

			//Se Empresa não existe
			if (string.IsNullOrEmpty(empresaSQL))
			{
				throw new Exception("A empresa escolhida não existe");
			}
			else
			{
				cb["Initial Catalog"] = empresaSQL;
			}

			if (string.IsNullOrEmpty(request.Username))
				throw new ArgumentNullException("username");

			var username = request.Username;

			//Atribui a Ligação do SQL Server
			SqlConnections.SetConnection("Default", cb.ConnectionString, cs.ProviderName);


			var user = Dependency.Resolve<UserRetrieveService>().ByUsername(username) as UserDefinition;
			if (user != null)
			{
				user.Company = empresaSQL;
			}
			else
			{
				throw new ValidationError("UserDoesntExist", Texts.Validation.UserDoesntExist);
			}



			if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
			{
				//Atribui a Ligação do SQL Server
				return new ServiceResponse();
			}

			throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);
		});
	}
	
...
}
```

I've got a more improved scenario of this behaviour but in general it's like this:

[![](http://img.youtube.com/vi/QI_hJbPLvdU/0.jpg)](http://www.youtube.com/watch?v=QI_hJbPLvdU "")

**Comment by Estrusco** [comment]
Very good! Thank you @brunobola :D

**Comment by brunobola** [comment]
@Estrusco thanks.

**Comment by volkanceylan** [comment]
Sorry but this is not a correct solution in my opinion. SqlConnections.SetConnection sets the connection string in a static dictionary. Thus, if multiple users are active in different databases at the same time, this would lead to very dangerous errors. This is not thread-safe.

**Comment by volkanceylan** [comment]
Hmm, probably i looked at solution of @brunobola, not @Estrusco one, will check that too

**Comment by volkanceylan** [comment]
Ok, @Estrusco solution looks valid, i'm using something similar for a project.

**Comment by brunobola** [comment]
My solution is in a production environment with more than 15 users at the same time and they often work in several dstabases at same time with no issues.

If you guys don't want it do as you want.

**Comment by volkanceylan** [comment]
I'm not misleading, u know nothing John Snow, it is working %99 doesnt mean it works %100, this is how thread safety works, you should read some

**Comment by brunobola** [comment]
I don't agree with you "john doe", I know you want users to buy you premium stuff, but that's not a right way to be polite and get more people to you.

Have a good year and try to respect more other peoples ideas and probably you'll get more success.

Having said that, your platform is a good entry point for beginners.

**Comment by volkanceylan** [comment]
Your logic:

if (solutionA is Free and solutionB is Free and JohnDoe suggests solutionB) { console.writeline("i think johndoe wants $"); do { console.writeline("yes i am a genius"); } while (1+1=0) } }
