### ISSUE TITLE
Update Column

### ISSUE THREAD

**Issue by Poojapusunuri** [volkanceylan/Serenity#3814]
Hi Everyone,
          
I am working on Project like this,
![status](https://user-images.githubusercontent.com/36690954/43714718-96e4b3ca-999b-11e8-887d-0f56b0f57d8f.PNG)

Is their any way in Serenity  to update Status  Column when checkbox is selected then the text which is written in WorkProcess column should be updated in status column on update button click.

Please Help me.

**Comment by hairangsua** [comment]
https://serenity.is/demo/Northwind/Product
I think this sample can help you. Editable grid.

**Comment by Poojapusunuri** [comment]
Thanks @hairangsua but I already refered it.
But  I want to update the Status Column using Textbox value on Update Button Click.

**Comment by ali-h2010** [comment]
@Poojapusunuri Were you able to resolve this? 
I have similar requirement where i need to edit the value before showing it in the table.
