### ISSUE TITLE
Facing same issue : Delete Case in detail section #3769

### ISSUE THREAD

**Issue by Tushar5292** [volkanceylan/Serenity#3816]
I noticed that adding items in the details editor updates my field in parent dialog correctly, but this is not the case when removing items. It seems that although the details editor gets updated (removing the item), the onDataChanged event never gets triggered, in order to update (subtract) the field's value in the parent dialog.
Any advice would be really appreciated.

Please help ?

Thanks in advance

**Comment by volkanceylan** [comment]
See answer in #3818
