### ISSUE TITLE
MasterDetail Ordering

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#3817]
Hey folks,

I would like to know how to resolve the masterdetail problem in ordering the columns?

in normal grid, we can order each column. But in masterdetail grid, it not working.

**Comment by hairangsua** [comment]
Ordering not work in detail editor. I think u should sort and order list in the server side.

**Comment by brunobola** [comment]
@hairangsua yes it works, just not out of the box...

**Comment by brunobola** [comment]
@rolembergfilho what is your problem with the code, it is plain simple, just put it in your editor xxx.ts file and it works, i've already using a major update of it that supports multiple columns sort as oppose to the described one column sort.

**Comment by rolembergfilho** [comment]
Hey @brunobola 

your code works!

thanks
