### ISSUE TITLE
Delete Case

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3818]
Hi all,

trying to apply issue #1068 with the great answer by @volkanceylan in my project, I noticed that adding items in the details editor updates my field in parent dialog correctly, but this is not the case when removing items. 
Any advice would be really appreciated.

Thanks in advance,

code=>
(this.form.DetailList.view as any).onDataChanged.subscribe(() => {
                    var total = 0;
                    for (var k of this.form.DetailList.getItems()) {
                        total += k.Amount || 0;
                    }
                    //Q.notifySuccess(total.toString());
                    this.form.BasicTotal.value = total;
                    this.form.LandedTotal.value = total;
                this.Calculations();
            });

**Comment by ga5tan** [comment]
maybe try to subscribe to delete event if such exists?

**Comment by ckrassas** [comment]
See #1068
