### ISSUE TITLE
Update grid masterDetails click button dialog son

### ISSUE THREAD

**Issue by alexdaywid** [volkanceylan/Serenity#3819]
I need to write directly to the bd and then update and display on the grid, when I click the button,
![sem titulo](https://user-images.githubusercontent.com/6788801/43845614-c401fa76-9b02-11e8-9d2a-d5d28d212f1d.jpg)

**Comment by ga5tan** [comment]
that's not how Master Detail works.
Updating has to be managed manually, see samples.
Detail is only saved once master entity is saved.
If you want to have different behavior, you may need different approach (not use Master Detail)

**Comment by alexdaywid** [comment]
Hi @ga5tan ,
So I could update DialogMaster by clicking the button, you would have some suggestions.

**Comment by ga5tan** [comment]
check OrderDetailsEditor.ts:
I believe validateEntity is called on getting back from editor, so u should put your stuff there
 validateEntity(row, id) {
            row.ProductID = Q.toId(row.ProductID);

            var sameProduct = Q.tryFirst(this.view.getItems(), x => x.ProductID === row.ProductID);
            if (sameProduct && this.id(sameProduct) !== id) {
                Q.alert('This product is already in order details!');
                return false;
            }

            row.ProductName = ProductRow.getLookup().itemById[row.ProductID].ProductName;
            row.LineTotal = (row.Quantity || 0) * (row.UnitPrice || 0) - (row.Discount || 0);
            return true;
        }
