### ISSUE TITLE
HideNav

### ISSUE THREAD

**Issue by BolatovAlau** [volkanceylan/Serenity#382]
Hi Volkan, it seems that hideNav in "_layout.cshtml" is always `false`
![default](https://cloud.githubusercontent.com/assets/14837842/13676730/23916a06-e711-11e5-8169-c3cd9866ce6d.png)
I hid nav, but when i updated page, It was still visible

**Comment by volkanceylan** [comment]
:) It's an option you pass from query string e.g. Northwind/Orders?hideNav=1 to hide navigation completely, intended for popup pages etc.

**Comment by volkanceylan** [comment]
Btw, are you using AspNet.Identity with Serenity. If so can you share how you implemented Serenity interfaces with a gist. Some other users asked about this.

**Comment by BolatovAlau** [comment]
Ok )

**Comment by BolatovAlau** [comment]
1. Have to delete some unused classes and interfaces in 
{MyProject}.Web/Modeules/Administration/User/Authentication folder
after delete it should look like it
![default](https://cloud.githubusercontent.com/assets/14837842/13679069/100925ae-e71c-11e5-8257-3cb1ac6b207b.png)
2. Copy default Asp.NEt MVC Folders, Controllers and classes (for that i created new project and just copied needed files) 
Here the list:
1. Controller Folder with AccountController, HomeController, ManageController controllers
2. Models Folder with AccountViewModels, IdentityModels, ManageViewModels classes
3. View Folder with Account, Home and Manage Folder
4. Have to copy _Layout.cshtml, _LoginPartial.cshtml, Error.cshtml, Lockout.cshtml files and rename  them
5. Copy some classes from App_Start or  add them to excisting files if they already excist in Serenity platform
6. Delete Dependencies From SiteInitialization class, after all it should like
```
public static partial class SiteInitialization
{
    public static void ApplicationStart()
    {
        try
        {
            SqlSettings.AutoQuotedIdentifiers = true;
            Serenity.Web.CommonInitialization.Run();

            var registrar = Dependency.Resolve<IDependencyRegistrar>();
            registrar.RegisterInstance<IAuthorizationService>(new AuthorizationService());
            registrar.RegisterInstance<IPermissionService>(new PermissionService());
        }
        catch (Exception ex)
        {
            ex.Log();
            throw;
        }
    }
}
```
7. Delete class SiteInitialization.Migrations we don't need it
8. Default Asp.Net MVC5 app uses guid for identities, serenity int for identites so you have to change default identity of asp.net from guid to int. Here is the link:
http://www.asp.net/identity/overview/extensibility/change-primary-key-for-users-in-aspnet-identity
9. Replace User, Roles, UserRoles tables to Asp.Net default Tables (AspNetUsers, AspNetRoles, AspNetUserRoles)
10. Сhange UserRow, UserCollumns, UserForms ... to match with our new tables
11. Delete Membership folder from {MyProject}.Web and {MyProject}.Script projects
12. And build and just follow to solve the errors

I think that the basic idea is clear , just need to unite projects Asp.Net MVC 5 with Serenity, and delete some unused folders, files

Volkan, I'm new GitHub , so if something is wrong , just tell me

**Comment by volkanceylan** [comment]
Thanks a lot. I put a link to related issue in Serene.

Btw, as a side note, user ID could be guid or string, but Serene sample has an integer one.

**Comment by BolatovAlau** [comment]
Glad to help you Volkan

**Comment by awesomegithubusername** [comment]
Hi @BolatovAlau;

Could you share how you implemented Serenity's  Authentication & Authorization interfaces? That would be very helpful.

**Comment by aranbenjo** [comment]
hi @BolatovAlau,
the thread is old, but for me this problem is open.
Can you share the solution or more details?
Thanks
