### ISSUE TITLE
Bulk Action onSuccess

### ISSUE THREAD

**Issue by Jigmiester** [volkanceylan/Serenity#3825]
I'm having a bit of difficulty determining when a bulk action is completed.  I tried the following in the sample app OrderBulkAction.ts.

`       protected executeForBatch(batch) {
            BasicSamplesService.OrderBulkAction(
                {
                    OrderIDs: batch.map(x => Q.parseInteger(x))
                },
                response => this.set_successCount(this.get_successCount() + batch.length),
                {
                    blockUI: false,
                    onError: response => this.set_errorCount(this.get_errorCount() + batch.length),
                    onSuccess: response => { },
                    onCleanup: () => this.serviceCallCleanup()
                });
        }`

I added the onSuccess: response => { }, portion just to see and it leaves the modal up with Please wait...  Any function I place in there was met with the same result, it keeps the UI blocked.

What is the best way to perform some js functions after a bulk action?  

Please note: I do need to use the response object post processing.

**Comment by Jigmiester** [comment]
In case someone else runs into this, I did find a way around it by manually closing the progress dialog in my onSuccess handler with the following:

`this.progressDialog.dialogClose();`

I still want to be sure I'm doing the proper thing here, so I'll leave the question open for now.

**Comment by volkanceylan** [comment]
Bulk action might trigger multiple success so doing something after that doesn't make much sense.
