### ISSUE TITLE
QuickFilterOption

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#3827]
Row 
   [LookupEditor(typeof(TanimBankaSubeRow), CascadeFrom = "BankaHesapBankaId")]

Columns    
[EditLink,  QuickFilter, QuickFilterOption("CascadeFrom", "BankaHesapBankaId")]
        public String BankaHesapBankaSubeAd { get; set; }
 böle yapmama rağpmen   Gridteki Bankalar  değiştirdikçe  Banka Şubeleri dolmuyor. bu iki alanda  bu rowa  expression ile cekiliyor.

**Comment by marcobisio** [comment]
english pls

**Comment by YunusV** [comment]
Row
[LookupEditor (typeof (TanimBankaSubeRow), CascadeFrom = "BankAccountBank")]

Columns
[EditLink, QuickFilter, QuickFilterOption ("CascadeFrom", "BankAccountBank")]
public String BankAccountBankaSubeAd {get; set; }
The Bank Branches do not fill up as the Banks in the Grid change. these two fields are drawn with this row expression.

**Comment by ga5tan** [comment]
did u check the samples?
it seem to be working fine there...
