### ISSUE TITLE
Language selection does not work in IE11

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3828]
Hi @volkanceylan ,

just a quick note: Under IE11, the language selection (switch language for currently logged in user on right, upper side) does not work in newest Serenity and also not on your demo page. With Chrome it works.

With Kind regards,

John

**Comment by rolembergfilho** [comment]
I'll did this same question.

Language selection works on firefox too. Can't check if this works on edge too, because I don't have windows 10.

The other problem is when I migrate my classes from old Serenity Version to actual version (of course, checking all tips from upgrade guide or create a new project from template and migrate) and run, I have and error "prototype can't be null"

And it point to language script.



![image](https://user-images.githubusercontent.com/19523455/43970754-fa994488-9ca4-11e8-8d36-85aee03f25bc.png)

**Comment by rolembergfilho** [comment]
late notes:
1 - restarted VS
2 - restarted PC
3 - updated packages (Update-Package Serenity.Web and Update-Package Serenity.CodeGenerator)
4 - done steps 1 and 2 again

errors still happens.

**Comment by volkanceylan** [comment]
Sorry, can't reproduce, it works in my PCs :/

![image](https://user-images.githubusercontent.com/752470/44631426-02054380-a974-11e8-9d72-41188973ac75.png)

Prototype error has no relation to this, you probably miss some /// references

**Comment by brunobola** [comment]
@volkanceylan you are using Edge, try in IE.

**Comment by JohnRanger** [comment]
@volkanceylan 

you tried it with MS Edge, not IE11. Look at your Screenshot - This is Edge. :-)

P.S: With Edge it works - with IE11 not.

As IE11 is still the most used Webbrowser within Companies internal IT infrastructure - at least with those customers I work with - this should be fixed.

With kind regards,

John

**Comment by brunobola** [comment]
@JohnRanger I already tried to tell that to @volkanceylan but it no answer, perhaps to busy ;)

**Comment by wldkrd1** [comment]
For yet another confusing data point, changing language in IE 11 using 3.7.7 (asp.net, not core) is working for me locally. On the demo site, the Language dropdown is empty:

![image](https://user-images.githubusercontent.com/2817543/46312026-b8160b80-c578-11e8-98f8-e02f872d86a0.png)

**Comment by globtech1** [comment]
Just upgraded to Serenity 3.7.7 on core and it does not work for IE either. Chrome is fine. Thanks.

**Comment by globtech1** [comment]
As I needed to solve it, I tried to find where it is happening. And in IE, the x function is undefined. 

![image](https://user-images.githubusercontent.com/39185790/47793698-2a684000-dd1f-11e8-9601-02df6053b1f6.png)

My knowledge of javascript is not deep enough to solve this in an elegant way, so I changed the async method to sync:

![image](https://user-images.githubusercontent.com/39185790/47797904-8fc02f00-dd27-11e8-8168-b22d8da8cdcc.png)

Until it gets fixed.

**Comment by volkanceylan** [comment]
Is this from AccountLogin.cshtml? If so, you just need to change arrow function to normal function, e.g. instead of `x => { } ` write, `function(x) { ... }`

**Comment by volkanceylan** [comment]
Looks like in IE 11, Promises are not working as expected, so Async doesn't work properly.

You might need to load "~/Scripts/rsvp.js" before Serenity.CoreLib.js etc. scripts in LayoutHead.cshtml or ScriptBundles.json.

I won't be doing that as i don't want to load an extra script to please IE11, and its usage percentage is pretty low.

**Comment by JohnRanger** [comment]
@Volkanceylan,

thanks for your feedback. 

I think that Serenity Framework is still mostly used within Enterprises for - borrowed from your advertisement of it :-) - data-driven business apps.

So far, all of my large customers do still use IE11 as their standard in-house browser as it is the only browser which is enough configurable to be useful within large enterprises (>=50'000 users). Chrome has some GPOs but all IT guys which I am talking to do confirm that Chrome is not yet enterprise ready.

Firefox cannot at all be used in large enterprises because it is not centrally configurable.

So I think it would be still a good thing that Serenity Framework would fully work with IE11 at this point in time.

With kind regards,

John

**Comment by volkanceylan** [comment]
And, if you are developing a software for an Enterprise, it wouldn't be that hard to add a line to ScriptBundles.json is it? And, you always say you use Serenity for personal projects, and customers are Enterprises with 50k+ users ;)

**Comment by JohnRanger** [comment]
Hi @volkanceylan ,

I just saw your last comment right now :-) Yes - It is no problem to add the relevant line to _LayoutHead.cshtml. I was more concerned about your way of thinking that IE11 is not anymore relevant and you would not anymore make sure that the current version of SF would be tested/garantied to run with IE11. 

Even today (End of June 2019), while IE11 has about 1'500 GPO settings to manage it within an enterprise, Edge has only about 20 (a good article about that is here: [https://theitbros.com/config-microsoft-edge-settings-using-gpo/](url).) This is why bigger entrerprises simply cannot just switch to anything else and are forced to continue to use an outdated browser - because the rest of them are not enterprise-ready (thank you Microsoft to leave all your well-paying enterprise customers in this really bad situation - a good new browser (Edge in Chromium mode) but not enterprise-manageable).

And with regards to my Serenity Projects... :-) With my customers, I am never contracted as a developer. Most positions are IT architect, IT admin or IT operator - depending on the needs of the customers. In these positions I often encounter situations where a Serenity-based app can relieve / solve some real problems - but I would never get any development budget for it. So I develop beside my official work and when the app then does its job, some people with which I work there (or myself) can do the work more efficient or more structured / guided because of the app. 

This as a little insight in what I am doing :-)

Wish you a nice evening.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi All, 

if you came here because you are still forced to support IE11 - and the language selection didn't work anymore with the most recent SF 3.9.9, then do this (mostly borrowed from @globtech1  but made it work with the most recent (at time of writing) SF 3.9.9.

Modify /Modules/Common/Navigation/LanguageSelection to look like this:

```ts
namespace <your name space>.Common {
    export class LanguageSelection extends Serenity.Widget<any> {

        constructor(select: JQuery, currentLanguage: string) {
            super(select);

            currentLanguage = Q.coalesce(currentLanguage, 'en');

            this.change(e => {
                $.cookie('LanguagePreference', select.val(), {
                    path: Q.Config.applicationPath,
                    expires: 365
                });
                window.location.reload(true);
            });

            <Your Prroject name>.Administration.LanguageService.List({
            }, response => {

                response.Entities.forEach( x => {
                    Q.addOption(select, x.LanguageId, x.LanguageName);
                });

                if (!Q.any(response.Entities, z => z.LanguageId === currentLanguage)) {
                    var idx = currentLanguage.lastIndexOf('-');
                    if (idx >= 0) {
                        currentLanguage = currentLanguage.substr(0, idx);
                        if (!Q.any(response.Entities, y => y.LanguageId === currentLanguage)) {
                            currentLanguage = 'en';
                        }
                    }
                    else {
                        currentLanguage = 'en';
                    }
                }

                select.val(currentLanguage);

            });

        }
    }
}
```

That's it. This pulls the neccesary data direct from the server endpoint instead of relying on the lookups (which at that point in time are not yet ready). DB access always is more reliable than lookup because of no timing problems. :-)

Hope this helps someone.

With kind regards,

John
