### ISSUE TITLE
Service method not generated

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#383]
I have added a new method (FinalizeAction) to my service endpoint class. I transformed T4 templates but FinalizeAction method was not added to the re-generated AppropriationBudgetService class in the Imports\ServiceContracts folder. What am I missing?

    [RoutePrefix("Services/LCBudgets/AppropriationBudget"), Route("{action}")]
    [ConnectionKey("Default"), ServiceAuthorize(PermissionKeys.AppropriationBudget.View)]
    public class AppropriationBudgetController : ServiceEndpoint
    {
............
        public ServiceResponse FinalizeAction(IUnitOfWork uow, FinalizeActionRequest request)
        {
            request.CheckNotNull();

            var random = new Random();

            // fail randomly with 3 percent chance
            if (random.Next(100) < 3)
                throw new ValidationError("Failed randomly!");

            foreach (var x in request.IDs)
                Thread.Sleep(random.Next(400) + 100);

            return new ServiceResponse();
        }
    }

**Comment by volkanceylan** [comment]
Your FinalizeActionRequest doesn't derive from ServiceRequest probably.

**Comment by volkanceylan** [comment]
Or forgot to build before T4 transform?

**Comment by c9482** [comment]
Yeah was not aware about building before transform. It seems logical though... Thanks again.

**Comment by volkanceylan** [comment]
T4 files uses output DLLs so you should always build before transform.

**Comment by c9482** [comment]
Makes sense - thanks again.
