### ISSUE TITLE
[BasedOnRow(typeof(xyzRow), CheckNames = true)] and [OneWay] properties in Form

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#3830]
`[BasedOnRow(typeof(xyzRow), CheckNames = true)] `
currently it checks all the properties in the Form and Column including the `[OneWay]` properties.

I think it should not be checked `[OneWay]` properties in the Form.

Am I right?

**Comment by volkanceylan** [comment]
OneWay means it might be sent from server but not sent back. There might be cases where it is desirable to check OneWay property name that it matches one on server. NotMapped is not checked but i think it is better to use SkipNameCheck etc later

**Comment by dfaruque** [comment]
Thanks @volkanceylan 
I am using `NotMapped` for now.
