### ISSUE TITLE
Translation LookUp

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#3831]
Hi everyone,

is there any way to get translation of lookup table without writing it into DB.  The best way would be to use the translation menu of serenity itself, but I dont know how to get those LookUp references into that translation list.

Thanks for any help.

**Comment by ga5tan** [comment]
I think items for translation have to be in Modules\Texts.cs
any chance to put your lookup stuff there?

**Comment by Garozh** [comment]
Yes i could register my lookUp references into that text.cs, like the following:

Db.Serene.Project.XYZLookUp.Item1 = "ItemValue1"
Db.Serene.Project.XYZLookUp.Item1 = "ItemValue2"
Db.Serene.Project.XYZLookUp.Item1 = "ItemValue3"

But how can i call these translations for the lookup editor?

**Comment by ga5tan** [comment]
check this sample for manipulating lookup
https://serenity.is/demo/BasicSamples/ChangingLookupText#!1

**Comment by Garozh** [comment]
Thank you very much that was what i was searching for
