### ISSUE TITLE
Session time out popup

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#3832]
Hello!!! Can I have a session timeout in serenity where after session timeout a popup appears and  it just asks for the password with the app running in the background.. Thanks in advance

**Comment by ga5tan** [comment]
I think there were some attempts for that, check wiki.
I recently saw in premium template something like that...

**Comment by volkanceylan** [comment]
You may try some other plugin like idletimeout.js etc, search internet for that.
