### ISSUE TITLE
Property 'cookie' does not exist on type 'JQueryStatic'.

### ISSUE THREAD

**Issue by adalberto-argente** [volkanceylan/Serenity#3833]
Has anyone ever had this kind of problem?

- Property 'cookie' does not exist on type 'JQueryStatic'.
- Cannot find module 'csstype'.

![image](https://user-images.githubusercontent.com/8500507/44039905-89c8bfba-9ef0-11e8-83d5-3916c8fdab1f.png)

**Comment by dfaruque** [comment]
workaround 
`($ as any).cookie(...)`

**Comment by adalberto-argente** [comment]
Thanks Bro! Works!
And how about de css error? Do you know something?

**Comment by dfaruque** [comment]
try to navigate the error location.
I don't understand.

**Comment by volkanceylan** [comment]
Closing double post
