### ISSUE TITLE
How to pass Foreign Key ShopId to LookUp PrePareQuery?

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#3834]
Hi to All,
   I need help on how to pass the foreign key ShopId value
to LookUp PrePareQuery use it in WHERE new Criteria.
I'm able to load the RUnNo LookUp and use it in QuickFilter, the problem
the PrePareQuery load all RunNo value instead of being dynamic 
based on ShopId value, the RunNo can be 1 to 100.

see screenshot..
![pic1](https://user-images.githubusercontent.com/22849322/44047452-f354e5a6-9f60-11e8-85c2-294c0a7c4ef0.jpg)

![pic2](https://user-images.githubusercontent.com/22849322/44047489-0a4c5e06-9f61-11e8-9dcf-57422092f27a.jpg)

This is my PrePareQuery code, and i think if i'm in the 
ts dialog i can pass a value something like this "this.form.ShopId"?

`protected` override void PrepareQuery(SqlQuery query)
        {
            var fld = ShopDetailsRow.Fields;
            var shop = ShopOrdersRow.Fields.As("shop");            
            query.Distinct(true)
                .Select(fld.RunNo)
                .Where(
                    new Criteria(fld.ShopId = shop.ShopId) & //something like this
                    new Criteria(fld.RunNo) != "" &
                    new Criteria(fld.RunNo).IsNotNull()).OrderBy();
        }`
Thank's in advance.

**Comment by alex-444** [comment]
Any advise or tips? how to do this. it's been two weeks and no results. :(

**Comment by dfaruque** [comment]
`Row.ShopId`

**Comment by volkanceylan** [comment]
This asked many times and answer is lookups cant take parameters, find other issues
