### ISSUE TITLE
Generating custom files using sergen

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#3835]
Once upon a time, I have added the feature to generate GridEditor and Dialog. Currently, it is not there for some good reason. That's ok. But we are missing that feature.

https://github.com/volkanceylan/Serenity/issues/3059

Would you please give some hint about generating custom files using sergen?

With kind regards
D Faruque

**Comment by brunobola** [comment]
@dfaruque I've also noticed that feature and missed it :(

**Comment by volkanceylan** [comment]
Check Generate Custom in Sergen UI, set custom templates path in UI, put GridEditor.scriban in that folder, open Serenity.CodeGenerator.config add such files:

```
"CustomGenerate": {
   "GridEditor": "{0}GridEditor.ts" 
}
```

**Comment by dfaruque** [comment]
Thank you very much @volkanceylan 

the following configuration is works
```
    "CustomGenerate": {
        "GridEditor": "{2}\\{0}GridEditor.ts",
        "EditorDialog": "{2}\\{0}EditorDialog.ts"
    },
```
