### ISSUE TITLE
Custom view when report is loading

### ISSUE THREAD

**Issue by qprotex** [volkanceylan/Serenity#3838]
Hello,

I am working on some big reports and some of them take about 60 seconds to load. I would like to display some custom HTML with a progress bar or something similar

![Report](https://i.imgur.com/Qcp1g90.png)

I know this is the code that is executed to prepare and download the report but I am not sure how to add some custom HTML to it.

```
 public ActionResult Download(string key, string opt, string ext)
        {
            return Execute(key, opt, ext, download: true, printing: true);
        }
```

Some advice would be appreciated.

**Comment by volkanceylan** [comment]
You can't display a progress bar. Pace.js already shows some indeterminate progress on ajax calls. Currently there is no other option. You may try long running action sample in StartSharp but still it won't work out of box with WKHTML as it doesn't support progress.
