### ISSUE TITLE
Date field cleanup error with Explorer and Chrome

### ISSUE THREAD

**Issue by MimmoDany** [volkanceylan/Serenity#3840]
I have encountered a problem on date fields.
The x button for cleaning the date appears with explorer.
while with chrome it does not appear.

See the following images.

Explorer:
![ser_data_ie](https://user-images.githubusercontent.com/35045921/44324890-4c0f9600-a457-11e8-9834-44f537cfc984.png)

Chrome:
![ser_data_chrome](https://user-images.githubusercontent.com/35045921/44324897-5af64880-a457-11e8-9fa9-741b775e0eef.png)

How can I solve this problem ?

Thanks in advance.

**Comment by Surenthiran** [comment]
This is IE future clear and show password options will be automatically added in all input fields. we can hide it by using CSS. following link will hep you with solution

https://stackoverflow.com/questions/17000562/removing-clear-and-reveal-password-icons-from-ie10

**Comment by volkanceylan** [comment]
Not a Serenity problem, not sure it is even a problem, closing.
