### ISSUE TITLE
what ValueProviderFactories.Factories.Remove is used for?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#3842]
Hi
Can anyone please help me understand what the following line of code do in Global.aspx in Serenity MVC 5 app.
            ValueProviderFactories.Factories.Remove()
            ValueProviderFactories.Factories.OfType<JsonValueProviderFactory>().First());

Thank you

**Comment by Surenthiran** [comment]
ValueProviderFactories are Basic MVC components. those provide an abstraction over where values actually come from. Value providers are responsible for aggregating the values that are part of the current request

maybe following link will help you out.

https://haacked.com/archive/2011/06/30/whatrsquos-the-difference-between-a-value-provider-and-model-binder.aspx/

**Comment by ms4hafiz** [comment]
Thank you @Surenthiran
