### ISSUE TITLE
Update Lookup Form

### ISSUE THREAD

**Issue by alexdaywid** [volkanceylan/Serenity#3845]
I changed the functions of the button, save and update, but I can not update the lookup after the return of the response ... When it records it returns me empty and when updating it does not change.
How can I update the lookup when closing Dialog.
![lookup](https://user-images.githubusercontent.com/6788801/44405800-7e40f680-a530-11e8-96ec-33470e75445b.png)

**Comment by Surenthiran** [comment]
need more explanation

**Comment by ga5tan** [comment]
if u r doing Master Detail, you have to update items in details by yourself in validateEntity.
check samples and Order Details

```
validateEntity(row, id) {
            row.RegistrantId = Q.toId(row.RegistrantId);

            var sameRegistrant = Q.tryFirst(this.view.getItems(), x => x.RegistrantId === row.RegistrantId);
            if (sameRegistrant && this.id(sameRegistrant) !== id) {
                Q.alert('This registrant is already in the list!');
                return false;
            }
            
            // Master Detail - field has to be looked up after adding to detail form before the real save
            var selectedUser = Users.UsersRow.getLookup().itemById[row.RegistrantId];
            row.RegistrantUsername = selectedUser.Username;
            row.RegistrantDisplayName = selectedUser.DisplayName;
            return true;
        }
```

**Comment by brunobola** [comment]
@alexdaywid Try to do a `Q.reloadLookup(XXXRow.lookupKey)` and use `[LookupScript("Module.XXXX", Expiration = -1)]` in you XXXRow.cs...
