### ISSUE TITLE
LeftJoin on top (Row) unable to fill <List>field 

### ISSUE THREAD

**Issue by IvoBrand** [volkanceylan/Serenity#3848]
Hello,
first of all i wish to thank you for this awesome framework.
I encountered a strange behaviour into my UserRow and i hope you can help me.

I have two entities: Users and UserSites.
Easy to know that "Users" is a table witch contains information about our users and UserSite is a junction table between Users and Sites. A user can be configured (via entity relationship, just perfectly workin) with multiple sites. 

On top on UserRow i put this line:

`[LeftJoin("jUserSite", "[CSP].[UserSites]", "jUserSite.[UserId] = t0.[UserId]", RowType = typeof(UserSiteRow), TitlePrefix = "")]`

And the field:

```
   [DisplayName("Sites id"), Origin("jUserSite"), Visible(false)]
        public List<Int64> SiteId
        {
            get { return Fields.SiteId[this]; }
            set { Fields.SiteId[this] = value; }
        }
```
Now, logging the content of the field, **it result empty**. No error raised.

The strange thing is i have another LeftJoin on top:

`[LeftJoin("jRegistrationUserDetail", "CSP.[RegistrationUserDetails]", "jRegistrationUserDetail.[UserId] = t0.[UserId]", RowType = typeof(RegistrationUserDetailRow), TitlePrefix = "")]`

and his field:
```
  [DisplayName("Company Name"), Origin("jRegistrationUserDetail"), Required]
        public String CompanyName
        {
            get { return Fields.CompanyName[this]; }
            set { Fields.CompanyName[this] = value; }
        }
```
Logging the "CompanyName" it result correctly filled.

Is there by chance an abnormal behaviour with LeftJoin and **List**Field?

Thank you.
Ivano.

**Comment by dfaruque** [comment]
use [LinkingSetRelation] or [MasterDetailRelation] to work with ListField.
see CustomerRepresentative as an example of [LinkingSetRelation]
and Order > OrderDetail for [MasterDetailRelation]

**Comment by IvoBrand** [comment]
dfaruque, this is not the point.
My relationship works perfectly. The point is that the framework seems have a problem whith this kind of LeftJoin.
However i correct 
```
   [DisplayName("Sites id"), Origin("jUserSite"), Visible(false)]
        public List<Int64> SiteId
        {
            get { return Fields.SiteId[this]; }
            set { Fields.SiteId[this] = value; }
        }
into **this**
`    [DisplayName("Sites id"), Origin("jUserSite"), OneWay]
        public List<CSH.Entities.SiteRow> SiteId
        {
            get { return Fields.SiteId[this]; }
            set { Fields.SiteId[this] = value; }
        }`
But the  SiteId field is still empty

**Comment by dfaruque** [comment]
According to my knowledge, this framework is not designed that way you think.
Please read guide to understand how [LeftJoin] works
Thanks.

**Comment by volkanceylan** [comment]
@dfaruque note is correct, list fields can't be populated automatically, they are simply unmapped, whether they are left join fields or not. They only got populated by a custom behavior, like master detail or linking set or one of your own.

**Comment by IvoBrand** [comment]
@dfaruque, @volkanceylan thank you very much.
