### ISSUE TITLE
BUG? required on checkbox does not work

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3849]
I have checkbox in Form defined like this

```
[BooleanEditor, LabelWidth(800), Required(true)]
public Boolean QASeminarPolicy { get; set; }
```

but it wont be required to be checked for some reason.
I have to explicitly call:

`Serenity.EditorUtils.setRequired(this.form.QASeminarPolicy, true);`

in updateInterface();

am I missing something, or why wont the checkbox be required?

**Comment by dfaruque** [comment]
does your QASeminarPolicy field in database save null?
the QASeminarPolicy should be saved as either 1 or 0.
i.e a checkbox is already required no matter you specify or not.

If you want to force the user to check this checkbox then why it should be in the UI.

**Comment by ga5tan** [comment]
Field is defined like this:


```
[DisplayName(UserFieldCaptions.QASerminalPolicyText), NotMapped]
        public Boolean? QASeminarPolicy
        {
            get { return Fields.QASeminarPolicy[this]; }
            set { Fields.QASeminarPolicy[this] = value; }
        }

```

My point is, when I programatically set it to required it works as desired. But when I declare it required, it does not work as desired. No matter my desires, should it NOT behave the same way in both instances ?

In another words, is declaring field Required NOT EQUAL to setting it to required programmaticaly?

**Comment by volkanceylan** [comment]
Add a validation rule to your checkbox if it is required. Required doesn't mean it has to be checked in, it means it can't be NULL. And please stop reporting BUGs for thinks that you don't actually understand.

**Comment by ga5tan** [comment]
@volkanceylan , sorry about the BUG word. 

I added validation rule previously, but it wont get triggered (like other do):

```
this.form.QASeminarPolicy.addValidationRule(this.uniqueName, e => {
                Q.alert("QASeminarPolicy");
                if (this.form.QASeminarPolicy.value != true)
                    return "Please read and agree to all the licences!";
            });
```

I admin I dont understand why declaring field Required(true) yields different result as setting it required via code: Serenity.EditorUtils.setRequired(this.form.QASeminarPolicy, true); Isnt it supposed to behave the same ?
