### ISSUE TITLE
Custom button in entity dialog

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#385]
Hi @volkanceylan,
I'm trying to add a custom button (in a dialog) that calls a new XYZendpoint method.
So I have:
1) added the endpoint method like this:

[HttpPost]
public SaveResponse DoSomething(IUnitOfWork uow, SaveRequest<MyRow> request)
{
	/* a bit of business logic here */
	return new MyRepository().Update(uow, request);
}

2) added the new button like this (in my XYZDialog):

protected override List<ToolButton> GetToolbarButtons()
{
            List<ToolButton> toolButtons = new List<ToolButton>();
            TicketDialog entityDialog = this;
            toolButtons.Add(new ToolButton()
            {
                Title = "TEST",
                Hint = "TEST 123",
                CssClass = "save-and-close-button",
                // OnClick = TBD
            });
            return toolButtons;
}

Then how I should call/bind such method from/to the button? In other words what I have to set on the OnClick attribute in order to call the "DoSomething" method?
I don't know if the right thing to do is use a Q method (like Q.Externals.PostToService() or Q.Externals.PostToUrl()) or there is a better/cleaner approach.

Thanks in advance
Best Regards

**Comment by volkanceylan** [comment]
Build, transform templates, then you will have XYZService.DoSomething method.

**Comment by volkanceylan** [comment]
Yes, Q.Confirm("asdada", () => XYZService.DoSomething())

**Comment by marcobisio** [comment]
Thank you very much Volkan for your support&patience (all these days I mean).
Your template is simply wonderful but the learning curve is a bit high for me!! ;-)

**Comment by marcobisio** [comment]
Forgot to close sorry!!
