### ISSUE TITLE
Temporary File Processing

### ISSUE THREAD

**Issue by Jigmiester** [volkanceylan/Serenity#3850]
I'm using a FileUploadEditor within my dialog and I wanted to return additional data from within the file to populate additional fields within the dialog.  In this case, it's an XML file that contains additional data within the file and a nice to have for my users would be to read the file and populate other fields with that data.

If I wanted to extend this:

       private class UploadResponse : ServiceResponse
        {
            public string TemporaryFile { get; set; }
            public long Size { get; set; }
            public bool IsImage { get; set; }
            public int Width { get; set; }
            public int Height { get; set; }
        }

Then process it when a file is uploaded through the dialog.ts, what should the typeScript look like to hook into the uploadresponse when it's returned from the FilePage.cs call TemporaryUpload?

**Comment by ga5tan** [comment]
maybe check on how XLS upload is done ?

**Comment by Jigmiester** [comment]
This item can be closed, it was my lack of understanding of the jquery file upload component.  Here's the code that hooked in where I needed.  This just throws up an alert with the temporary file name on the server.

this.form.MyFileUploader.element.bind('fileuploaddone',
                function (e, data) {
                    alert(data.result.TemporaryFile);
                });
