### ISSUE TITLE
MasterDetails Order

### ISSUE THREAD

**Issue by rogmauri** [volkanceylan/Serenity#3851]
When you click on the detail columns they are not sorted

**Comment by rogmauri** [comment]
Will I need to implement the feature?
![masterdetailss](https://user-images.githubusercontent.com/42703799/44624067-4bdd2380-a8b9-11e8-8d3d-5efdc9a967a8.png)

**Comment by ga5tan** [comment]
@rogmauri 
https://github.com/volkanceylan/Serenity/issues/3792

**Comment by rogmauri** [comment]
TKS !!!
Ordering worked. But, the filter?

**Comment by ga5tan** [comment]
I believe there is filtering as well.
Check with @brunobola  if he finished wiki entry

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/issues/3792
