### ISSUE TITLE
get the selected object from lookup editor

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#3852]
I have a lookup editor and I added [LookupInclude] attribute to four fields. now in the change event I want to access all of these fields like.
this.form._mylookupeditor_.SelectedObject.field1
this.form._mylookupeditor_.SelectedObject.field2
this.form._mylookupeditor_.SelectedObject.field3
this.form._mylookupeditor_.SelectedObject.field4

currently I can access the selected value  **_this.form._mylookupeditor_.value_**
please advise.

**Comment by dfaruque** [comment]
this.form.ProductID.changeSelect2(e => {
                var productID = Q.toId(this.form.ProductID.value);
                if (productID != null) {
                   var selectedProduct = ProductRow.getLookup().itemById[productID]
                    this.form.UnitPrice.value =selectedProduct .UnitPrice;
                }
            });

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/OrderDetail/OrderDetailDialog.ts

**Comment by amrgDev** [comment]
thank you dfaruque
