### ISSUE TITLE
XSS or Cross Site Scripting

### ISSUE THREAD

**Issue by shailendrasingh03** [volkanceylan/Serenity#3854]
How to prevent XSS attack on the MVC application

**Comment by ga5tan** [comment]
No idea, but this may give you some more info ?
https://github.com/volkanceylan/Serenity/wiki/%5BSecurity%5D-Preventing-CSRF-attacks-(Implementing-AntiForgery)

**Comment by shailendrasingh03** [comment]
No its Different .. XSS is different issue .

**Comment by shailendrasingh03** [comment]
any help

**Comment by ga5tan** [comment]
well I guess reply in Volkan style would be:
it's a MVC, so UTFG for "MVC XSS attack prevention"
(I found user switching/impersonation for MVC that way)

**Comment by shailendrasingh03** [comment]
I have found solution but its implementation is is big change .

**Comment by ga5tan** [comment]
MVC, by default, prevents any requests containing HTML markup, in order to avoid XSS attacks. By default ASP.NET 4.5 throws an exception if potentially dangerous content is detected in the request.

what did you find? what does it need ?
