### ISSUE TITLE
Sergen from Postgres with non-default schema

### ISSUE THREAD

**Issue by JesseGlidewell** [volkanceylan/Serenity#3859]
When using sergen to generate code for a table in PostgreSQL that is outside of the default schema, it throws an exception at the end: `Npgsql.PostgresException: 42P01: relation "TABLENAME" does not exist`

Tables in the default 'public' schema do not have this issue, and when working with SQLite the schema is not a problem at all. 

After tracing it back to [PostgresSchemaProvider.cs](https://github.com/volkanceylan/Serenity/blob/48b7a2135311123f6876b45a553b77b3e8833315/Serenity.Data/Schema/Providers/PostgresSchemaProvider.cs#L71), I believe this can be fixed by including the schema with the table name as follows:
`"WHERE pg_class.oid = '" + schema + ".\"" + table + "\"'::regclass " +`

**Comment by JohnRanger** [comment]
@JesseGlidewell ,

thanks for tracing and sharing this with us :-). As Volkan currently seems to be very busy implementing many of the things he has shown in the roadmap proposition, it would make it easier for him if you could implement this within a git pull request so that he can just approve and merge it.

(This would also get more attention than here in the issue forum).

Just my 5 cents...

With kind regards,

John

**Comment by JesseGlidewell** [comment]
Thanks for the suggestion John. I'll probably take a crack at it next month, since this isn't the only issue with Postgres we've had to work around, it's just the only one I currently have a real solution for. If possible I'd like to include fixes for those other bugs as well, or failing that document the workarounds for them.

**Comment by volkanceylan** [comment]
I don't have Postgress installed at the moment, if you can change it and test and ensure that this is correct for all Postgress versions, i may apply the change.

**Comment by vsudik** [comment]
Hello,
I have same problem\error "Npgsql.PostgresException: 42P01: relation "TABLENAME" does not exist" in configuration Asp .Net Core project + Serenity.CodeGenerator 3.13.4 + PostgreSQL 12 for tables that are outside of the default schema. Does it will be fixed by JesseGlidewell recommendation?

**Comment by JesseGlidewell** [comment]
@vsudik I have workarounds for this and a few other Postgres issues, so there wasn't much incentive to test the above change across all database versions before submitting a pull request. So if you have the time, please feel free to pick up the task. But if you need a quicker fix you can use this SQL command to modify the database so sergen can work with other schemas:

`ALTER DATABASE "databaseName_v1" SET search_path TO otherSchema, public`

**Comment by vsudik** [comment]
@JesseGlidewell Thank You, I will use your trick, but I have to rename some tables with same names in different schemas before it.
