### ISSUE TITLE
Problem connecting to Firebird database with.NET Core Serenity app

### ISSUE THREAD

**Issue by andrewdenton** [volkanceylan/Serenity#3860]
I have an existing Firebird database used by another application that I want to provide a web front-end for using Serenity. I created a new Serenity .NET Core app, installed the `FirebirdSql.Data.SqlClient` package and changed the Default connection string in the `appsettings.json` to read :-

 `  "Default": {
      "ConnectionString": "User=myuser; Password=userpw; Database=localhost:e:\\data\\mydb.gdb; Datasource=localhost;",
      "ProviderName": "FirebirdSql.Data.FirebirdClient"
    }`
 
When I run the application it throws an `ArgumentOutOfRangeException` for `providerInvariantName`. 

I've searched around looking for any other similar issues, but I've found nothing. Does anyone have any ideas?

**Comment by volkanceylan** [comment]
Have you take a look at Startup.cs, RegisterDataProviders??

**Comment by andrewdenton** [comment]
Doh! I feel stupid now! I assumed that all providers were registered by default. That's sorted now. Thanks for that, Volkan!
