### ISSUE TITLE
UpdateById is void - how to get Success or failure

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#3861]
This is not a serenity issue but a how to issue..
I have the following code - I simply want to know if I have had a successful update to the database , 
Currently I requery the db , and compare I don't want to do that. I think IUnitofWork would give me the result success or failure but I don't know how to use that in my code.
```
        public static bool UpdateYearCode(string YearCode)
        {
            

            bool result = false;

            using (var connection = SqlConnections.NewFor<AppDataRow>())
            {
                
                var appFld = AppDataRow.Fields;

                AppDataRow myApplicationDataRow = connection.TryFirst<AppDataRow>(q => q.Select(appFld.YearCode));


                if (myApplicationDataRow != null)
                {

                    myApplicationDataRow.YearCode = YearCode;

                    connection.UpdateById(myApplicationDataRow, ExpectedRows.One);

                    myApplicationDataRow = connection.TryFirst<AppDataRow>(q => q.Select(appFld.YearCode));

                    if (myApplicationDataRow.YearCode == YearCode)
                    {
                        result = true;
                    }
                    else
                    {
                        result = false;
                    }

                }

            }

            return result;

        }
```

**Comment by VictorTomaili** [comment]
When it's fail, it throwing exception18:08, August 30, 2018, stixoffire <notifications@github.com>:This is not a serenity issue but a how to issue..
I have the following code - I simply want to know if I have had a successful update to the database ,
Currently I requery the db , and compare I don't want to do that. I think IUnitofWork would give me the result success or failure but I don't know how to use that in my code.
        public static bool UpdateYearCode(string YearCode)
        {
            

            bool result = false;

            using (var connection = SqlConnections.NewFor<AppDataRow>())
            {
                
                var appFld = AppDataRow.Fields;

                AppDataRow myApplicationDataRow = connection.TryFirst<AppDataRow>(q => q.Select(appFld.YearCode));


                if (myApplicationDataRow != null)
                {

                    myApplicationDataRow.YearCode = YearCode;

                    connection.UpdateById(myApplicationDataRow, ExpectedRows.One);

                    myApplicationDataRow = connection.TryFirst<AppDataRow>(q => q.Select(appFld.YearCode));

                    if (myApplicationDataRow.YearCode == YearCode)
                    {
                        result = true;
                    }
                    else
                    {
                        result = false;
                    }

                }

            }

            return result;

        }


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Yandex.Mail mobil sürümünden gönderildi: http://m.ya.ru/ymail

**Comment by stixoffire** [comment]
When it's fail, it throwing exception ,  I was trying not to use exception logic try catch - would prefer return success or return failed ..

**Comment by volkanceylan** [comment]
We don't use result codes in .NET
