### ISSUE TITLE
Foreign Fields of List<xyzRow> allways null? 

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#3863]
Hey there,

When trying to call a Foreign Field out of a MasterDialog, it's allways returning null values for all Foreign Fields in DetailEditor. I guess I'm missing something simple.

So here is my MasterDetailRelation:

```
		[DisplayName("Modules"), MasterDetailRelation(foreignKey: "Id"), NotMapped]
		public List<ModuleRow> ModuleList
		{
			get { return Fields.ModuleList[this]; }
			set { Fields.ModuleList[this] = value; }
		}
		public partial class RowFields { public RowListField<ModuleRow> ModuleList; }
```

And if I'm debugging into the MasterRetrieve method and calling the Entity all Foreign Fields give me null value.

Thanks in Advance for any hint

**Comment by dfaruque** [comment]
use `[MinSelectLevel(SelectLevel.List)]` on top of the foreign fields in ModuleRow.cs

**Comment by Garozh** [comment]
Thank you very much, that solved my problem.
