### ISSUE TITLE
Sort Grid by Invisible column

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3864]
Is it possible to sort grid by invisible column?
I can only get it sorted when column is visible, once I hide it, sorting is gone.
Reason why column is hidden, because it's ID column and I look up text instead of it.
sorting by text does not work, as it wont sort it properly.

**Comment by brunobola** [comment]
You have several ways to try to achieve this, try to override xxxgrid.ts or use a datasource ordered from the database insted.

**Comment by ademc** [comment]
The best way is: Add [Width(0),SortOrder(1)] attributes to column that you dont want to show. Column will not show and still you can use sorting

**Comment by ga5tan** [comment]
this does the trick for me (in Grid.ts):

```
protected getDefaultSortBy() {
            return [EventRow.Fields.StartDate];
        }
```
