### ISSUE TITLE
Custom Page with PageAuthorize Attribute

### ISSUE THREAD

**Issue by glenngsanchez** [volkanceylan/Serenity#3868]
Hi,
Please help me...

I am trying to add PageAuthorize attribute to Dashboard from the sample.  I would like to allow only selected users that can access this page.  How do you do it?

When I tried to add this:
`[RoutePrefix("Common/Dashboard"), Route("{action=index}")]`
`[PageAuthorize(PermissionKeys.Dashboard)]`

I get this during debug:
![image](https://user-images.githubusercontent.com/23032787/44956931-05617780-aefe-11e8-9601-0c94d300d2da.png)

**Comment by volkanceylan** [comment]
The screenshot you share is not any helpful.
