### ISSUE TITLE
TimeEditor minutes does not trigger a change event

### ISSUE THREAD

**Issue by slang123** [volkanceylan/Serenity#3869]
#2382 

The 2382 was closed but this is still not working for me. I am using version 3.7.6.

**Comment by hairangsua** [comment]
`            this.propertyGrid.element.find('.field.YourField').find('.s-TimeEditor.minute').on("change", e => {
             }
            });`
let try it

**Comment by volkanceylan** [comment]
This is not a bug, it is a nice to have. You are binding to change event of the editor element, which is just hour. Minute is another element. Anyway, will be in next version.
