### ISSUE TITLE
NullReference exception in DetailListSaveHandler.cs

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#387]
I'd issue a pull request if I could find it, guessing it's part of the VS template and not in the github repository.

Anyways...lines 23-24:
`this.oldList = oldList ?? new List<TRow>();
            this.oldById = oldList.ToDictionary(x => GetID(x).Value);`
if oldList is null, line 24 will throw an exception. Suggest changing line to
`            this.oldById = this.oldList.ToDictionary(x => GetID(x).Value);`

Same with line 27: `this.newById = this.newList.ToLookup(x => GetID(x));`

**Comment by volkanceylan** [comment]
This handler is no longer used, behaviors are used actually but i'll apply fix.

**Comment by volkanceylan** [comment]
Thanks. 121d6522ee219440d03960abb080828867fcc985

**Comment by wldkrd1** [comment]
Ahh...I was following the guide for dealing with master/detail records, was wondering why it was creating duplicate records on insert. Makes sense now. I'll look at Order/OrderDetail from Northwind to learn how you're doing it now. Thanks!
