### ISSUE TITLE
Set dynamic header and footer for generated PDF( wkhtmltopdf.exe)

### ISSUE THREAD

**Issue by KumarVaibhav1801** [volkanceylan/Serenity#3872]
While generating PDF through 'wkhtmltopdf.exe', how to set dynamic header and footer for generated PDF , so that we can get page number and some constant footer on each page?
I am using a xyz.cshtml and xyz.cs(Controller) files for the customization part. Models are being populated in xyz.cs file which is having collection for comments, some notes etc.

**Comment by volkanceylan** [comment]
Check docs for wkhtml, how to pass options is in sample
