### ISSUE TITLE
Choosing a new language 

### ISSUE THREAD

**Issue by vlaca99** [volkanceylan/Serenity#3875]
Hello, I am having a problem. I added a new language (Serbian) through administration and chose LanguageId to be Lt-sr-SP as written in the document https://docs.microsoft.com/en-us/previous-versions/commerce-server/ee825488(v=cs.20) but it wont change to Serbian, it automatically changes back to English...

I have also tried LanguageId to be 'sr-SP' and 'sr' only and it didn't help.

I saw that there is a thread on this problem but you have closed it.

Thank you.

**Comment by volkanceylan** [comment]
Language IDs are two or four letter and they must be defined in windows. Your ID is from commerce server whatever it is
