### ISSUE TITLE
How to bind Grid2 from Grid1 selection

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3877]
Hello everyone!
![capture4](https://user-images.githubusercontent.com/39983941/45159480-79ed2c80-b204-11e8-873f-1ed3452a30ca.PNG)

Am Implementing BOM concept in serenity
so here you can see the first one is SuperBom which has 2 levels 
so from level1, I want to bind the level 2 grid(level1 each items  contains some value) 
and that data I want to display in the level2 grid

**Comment by brunobola** [comment]
@Shraddha996  Another way you could do it is using the [Treegrid](https://serenity.is/demo/BasicSamples/TreeGrid) and do a more complex implementation using it.

I see several avantajes like easy reorder of child nodes.

**Comment by chadburnett** [comment]
Just a quick note.  Please use a descriptive title.  

When searching this issue will never be found because no one searches for "How to". 

Thanks.
