### ISSUE TITLE
Script and style bundling

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#388]
Good Evening @volkanceylan and Serenity Community!

I have made some changes to my project's login page. It includes adding a css file that I intend to use only for this login page, and also an external javascript library for animation effects. Now, currently I have added the script to the `MyProject.Web/Scripts/` directory, but I have encountered a couple of issues. The library I am trying to use is [Vegas](http://vegas.jaysalvat.com/) by Jay Salvat. I have downloaded the library and extracted the folder to my Scripts directory. This library includes a subfolder called `overlays` which include several `.png` files for overlaying images and helping to mitigate image compression/scaling artifacts. When I rebuild my project, I receive two 404s in the browser console: 

![errors-console](https://cloud.githubusercontent.com/assets/11762092/13692902/14e7ff22-e713-11e5-9da8-e13a4624cf65.png)

Here is the way it should properly look: 

![intended-view](https://cloud.githubusercontent.com/assets/11762092/13692908/22a5d6a2-e713-11e5-8ddd-e43d4b8ab357.png)

Now, I can fix the issues with the conflicting styles of the input boxes. However, the server can't find the images, even though I've made sure to include them in the project. Is there anything I have to do to register my scripts and images

**Comment by volkanceylan** [comment]
Are you setting these images from script? Use Q.ResolveUrl go get rid of that ~ in url.

**Comment by ChenZhaobin** [comment]
I have realize this requirement,later,After I am at home,I will upload my code here

**Comment by jsbUSMC** [comment]
I am setting the images from script. I began by including javascript at the end of the page that calls the library externally, while I play around with Saltarelle and figure out how to include the library using C#.

**Comment by jsbUSMC** [comment]
@ChenZhaobin would you mind posting that code for me? Thank you.

**Comment by jsbUSMC** [comment]
I feel like the dumbest idiot in recent memory. I forgot to add the Vegas stylesheet to the Head section. It's loading my overlays and background slideshow pictures now. Sorry for overlooking such a rookie mistake for two days. Thank you very much though for your help!
