### ISSUE TITLE
Object Reference not set to instance of an object error 

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#3881]
Hello!

Could you please help me with this error, in this portion of code:
                                      
                    using (var connection = SqlConnections.NewFor<ProductosRow>())
                    {
                        model.Agotados = connection.Count<ProductosRow>(new Criteria(ProductosRow.Fields.StockActual) == 0);

                      SqlQuery query = new SqlQuery()
                      .From(s)
                      .From(f)
                       .Select(Sql.Sum(s.Subtotal.ToString()))
                       .Where(
                            new Criteria("T0.IdInvoice = s.IdInvoice") &
                            new Criteria("T0.FechaInv") == "09/05/2018");
                      

> The error is here!!

                        if (connection.Query<decimal>(query) !=null)
                        {
                            var id = connection.Query<decimal>(query);
                            model.Ventas = (int)id.First();
                        }
                        else
                        {
                            model.Ventas = 0;
                        }
                    }
                    return model;
                });

> The error is like the query not return any result, but when the query return records the error message not appears and works fine, please help me with the missing validation?

Thanks for any help!!!

**Comment by javaman63** [comment]
May be you could use

```
                    if (model.Ventas !=null)
                    {
                        var id = connection.Query<decimal>(query);
                        model.Ventas = (int)id.First();
                    }
```
Or some field you know is not null in the query like an ID, `model.VentasID` for example

Hope this help

**Comment by volkanceylan** [comment]
You should use FirstOrDefault
