### ISSUE TITLE
Serenity Login Without Database

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#3883]
Hello,

How can I Login with fixed single user name and password instead of authenticating from database ?
As I can see below code is responsible for login authentication; how can i use service response with fixed user name and password without adding database into picture.

```
[HttpPost, JsonFilter]
        public Result<ServiceResponse> Login(LoginRequest request)
        {
            return this.ExecuteMethod(() =>
            {
                request.CheckNotNull();

                if (string.IsNullOrEmpty(request.Email))
                    throw new ArgumentNullException("Email");

                var username = request.Email;
                
               // if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
                if (username == "admin" && request.Password == "admin")
                {
                        return new ServiceResponse();
                   }
                        

                throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);
            });
        }
```

**Comment by wezmag** [comment]
You need to SetAuthenticationTicket
https://github.com/volkanceylan/Serenity/blob/48b7a2135311123f6876b45a553b77b3e8833315/Serenity.Web/Security/WebSecurityHelper.cs#L34-L70

**Comment by TechAspirant** [comment]
Hello,

As I can see In my code  Only function definition is there not the whole code as you have mentioned above. So , I my case where I can edit the Authenticate method .

```
namespace Serenity
{
    public static class WebSecurityHelper
    {
        public static string HttpContextUsername { get; }

        public static bool Authenticate(ref string username, string password, bool persist);
        public static void EnsurePermission(string permission);
        public static void LogOut();
        public static void SetAuthenticationTicket(string username, bool persist);
    }
}
```

**Comment by wezmag** [comment]
You only need to call SetAuthenticationTicket in your code.
This will issue a cookie, so the application will know that the user is now logged in.
Something like this:
```
if (username == "admin" && request.Password == "admin")
{
    WebSecurityHelper.SetAuthenticationTicket("admin", false);
    return new ServiceResponse();
}
```

**Comment by TechAspirant** [comment]
Ok .....It worked but In this case still SQL Server Remains in the background I want to remove complete SQL Server dependency from my serenity application.
