### ISSUE TITLE
xyzRow.cs; in-memory only fields possible? Used to transport additional data from dialog to endpoint

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3888]
Hi all,

is it possible in an xyzRow.cs to have additional fields which are in-memory only and are not retreived and stored within the SQL database but can be used to transfer temporary data from dialog to endpoint?

If yes, how?

Thanks for your help and

with kind regards,

John

**Comment by dfaruque** [comment]
use `[NotMapped]`

**Comment by JohnRanger** [comment]
Hi @dfaruque ,

thank you very much - this I had overlooked :-)

Have a good start into this week.

With kind regards,

John
