### ISSUE TITLE
How to refresh grid after close dialog

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#389]
I have a diolog with submit approval button, i want after click this button and dialog close it will be refresh grid how to do that?

buttons.Add(new ToolButton
            {
                Title = Q.Text("Submit Approval"),
                CssClass = "users-button",
                OnClick = delegate
                {
                    System.Action submit = delegate
                    {
                        ApprovalService.SubmitApproval(new ApprovalSumbitRequest
                        {
                            AppFormID = this.Entity.AppFormId.Value,
                            UserID = Authorization.UserDefinition.UserId,
                            ApprovalLevel = 0,
                            IsSendingRequest = true
                        }, response =>
                        {
                            if (response)
                            {
                                Q.NotifySuccess("Approval has been send");
                                DialogClose();
                            }
                        }
                        );
                    };
                   Q.Confirm("Are you sure want to submit this approval?", submit);
                }
            });

**Comment by volkanceylan** [comment]
Call this.TriggerDataChange() before closing dialog.

**Comment by rudianto2008** [comment]
Thanks Jaiq, it works.

**Comment by misafer** [comment]
then what to do with this question in typescript ?

**Comment by volkanceylan** [comment]
Call this.triggerDataChange() before closing dialog.

**Comment by misafer** [comment]
hi dear Volkan. i use it in that way but there is not such method in my refrences and there is an error.
"Property triggerDataChange does not exists in XYZdialog.ts". the i've searched about the method and found it here : "Serenity.TypeScript.CoreLib/UI/Helpers/SubDialogHelper.ts"
how i use this file or its container package in my proj ? thanks for helps.

**Comment by misafer** [comment]
this works for me :  Serenity.SubDialogHelper.triggerDataChange(this); 
thanks 💯 👍
