### ISSUE TITLE
Get the query executed  from Serenity Connection

### ISSUE THREAD

**Issue by nkasam** [volkanceylan/Serenity#3893]
Can you please help, if there is any method or helper function that returns the mysql query executed,

when using the list handler process method to retrieve the results.

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/wiki/Repository-overridable-methods-and-calling-sequence

**Comment by JohnRanger** [comment]
Hi @nkasam ,
try to turn on debug logging. A lot of the SQL statements executed are then logged.

In web.config, change debug level from 'off' to 'debug':
```xml
<configuration>
  <appSettings>
    <add key="Logging" value="{  File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0,  Level: 'Debug' }" />
  </appSettings>
```

And then find your debug logs under App_Data.

Hope, this helps you.

With kind regards,

John
