### ISSUE TITLE
product Picker

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3896]
hey,
i want to implement like the one below how to implement it
![screenshot 18 _li](https://user-images.githubusercontent.com/40484328/45351102-fa2fdb00-b5d2-11e8-9ca2-9551623e8be2.jpg)
 when i click on button to add items the dialog appears to  select the items to add using check box how to do it.

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/issues/3897
