### ISSUE TITLE
Product Picker in Detail section

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3897]
Good afternoon,
I would like to see if someone could help me how to use a checkbox selection on the  Details grid to import into my Order dialog when creating a new Order. 

![capture8](https://user-images.githubusercontent.com/39983941/45351295-79251380-b5d3-11e8-8e22-cb33055f5d20.PNG)
(Advance Sample - Product Picker)

I have tried everything I've read on here so far but have yet to even get close to making it work.
If there is something else that would be a better option please let me know.
It would be great if someone share some link regarding this as soon as possible. It's really urgent

Thank you for any help!

**Comment by brunobola** [comment]
@Shraddha996 That's a Premium feature. [START#](https://serenity.is/demo/Account/Login?ReturnUrl=%2fdemo%2f) has that but u've got to pay for it.

In alternative you can try to implement it yourself and share with the community ;)
