### ISSUE TITLE
wkhtml options for reports ?

### ISSUE THREAD

**Issue by GAdji2005** [volkanceylan/Serenity#3898]
Hii there

    have been trying to figure out how to pass additional custom options to wkthml, without any luck...
from the available options (IHtmlToPdfOptions options)

   footer is not available, and have been trying to add for example:

--footer-center "Some footer text / page number"

any idea on how to pass these custom arg ? 

Thanks in advance ...

**Comment by Estrusco** [comment]
```C#
        public override void Customize(IHtmlToPdfOptions options)
        {
            string PhisicalPath = Path.Combine(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath,
                @"App_Data\Reporting\");

            options.CustomArgs.Add("--header-html");
            options.CustomArgs.Add(PhisicalPath + "header.html");

            options.CustomArgs.Add("--footer-html");
            options.CustomArgs.Add(PhisicalPath + "footer.html");
```
