### ISSUE TITLE
DynamicScripts

### ISSUE THREAD

**Issue by yankerssnh** [volkanceylan/Serenity#39]
How to pass parameter inside lookupscript?

For example:
I want to do filtering by product category. Want to pass categoryID over lookup and get back only products from this category

**Comment by volkanceylan** [comment]
Please have a look at CustomerCityEditor and how it filters cities by country. It is possible to create cascaded editors by setting bound editor id (e.g. CountryEditorID) property. Another way is to set Country option directly (e.g. on LoadEntity method of the dialog it is used), or in the form server side.

In next versions, i might add a cascading option to LookupEditor to have this functionality without having to define a custom editor type.

**Comment by volkanceylan** [comment]
Please reopen if it didnt solve your issue

**Comment by yankerssnh** [comment]
How to say LookupEditor ask LookupScript any time as dialog reopen?
Now It as only one. But If data in Lookup Table was changed, LookupEditor not know it

**Comment by volkanceylan** [comment]
Something like Q.ReloadLookup("Northwind.CustomerCity")
