### ISSUE TITLE
Adding a serenity life cycle chapter to Serenity Guide

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#390]
It would be great if Serenity Guide has a chapter that describes the serenity application life cycle, dialog life cycle etc.

What do you think about?

Regards

**Comment by jsbUSMC** [comment]
I also think this would be very helpful as well. Perhaps a flowchart or visualization to go along. I would be willing to help on that if needed

**Comment by volkanceylan** [comment]
There are many such independent lifecycles, some not so sequential to visualize. I'll probably draw sequence / flow diagrams like i did with two level cache etc. while writing documentation for them, including:

* Dynamic scripts, including form, lookup, columns, remote data etc.
* List, Retrieve, Save Handlers
* Behavior system
* Form, property grid generation and attributes
* Dialog load, save, events
* Grid events
* T4 files, what and how generated

There are probably many more. I don't know how to divide my limited time between choices like adding new features, more samples, documentation, tests, helping users etc.

**Comment by volkanceylan** [comment]
Btw, thanks @jsbUSMC for offering help. If you have some topic you think you can write some doc or visualization for, i'll be glad to help and add it to Serenity guide.

**Comment by dfaruque** [comment]
Thanks.

You are doing really a good job.
