### ISSUE TITLE
Setting Context for parallel execution

### ISSUE THREAD

**Issue by nkhand** [volkanceylan/Serenity#3902]
Hi 
I am doing parallel JBehave Execution , involving multi-browser testing . 
Setting different contexts for different threads ( using Serenity.setContext() ) , but still serenity report is taking into account only one context , and showing all stories against single browser , though actually they have been executed in different browsers . 

Please suggest a way to correct this . Thanks always for the help .

**Comment by volkanceylan** [comment]
You are in wrong repo
