### ISSUE TITLE
Split grid by quantity

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3904]
Good afternoon,
I would like to see if someone could help me with how to get products divided by their quantity
![capture4](https://user-images.githubusercontent.com/39983941/45418718-cd4af900-b6a2-11e8-90c8-a9a37b29b43d.PNG)
So here Suppose if Quantity is 10 in level 1 and when I select on edit link then the same product with 1 quantity should be displayed in Level 2 Grid(Then Level 2 Will contains 10 Products)

If there is some option please let me know.
It would be great if someone shares some link regarding this as soon as possible

Thanks in advance!

**Comment by volkanceylan** [comment]
Closing, out of scope
