### ISSUE TITLE
Row selection in GridEditor?

### ISSUE THREAD

**Issue by tomuee** [volkanceylan/Serenity#3905]
Hello all!

I tried to add a row selection column to a GridEditor like described here:
[https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_add_a_row_selection_column.html](url)
The only difference is, that the documentation adds a row selection column to a EntityGrid. I've derived from GridEditorBase instead.

But the result is not satisfying:
![grafik](https://user-images.githubusercontent.com/34380537/45421557-af26ce00-b68d-11e8-8ea7-21f01e1bcb73.png)

Is it possible to get a row selection column in a GridEditor?

Thanks in advance for your help!

**EDIT**

Maybe i should say that the Editor Class is a .ts Class and it's used for a List of Entity-Rows in another Dialog.

**Comment by hannesb** [comment]
My working implementation looks like this:

`
        private rowSelection: Serenity.GridRowSelectionMixin;

        constructor(container: JQuery) {
            super(container);
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);            
        }

        protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();
            columns.unshift(Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));
            return columns;
        }
`

**Comment by tomuee** [comment]
Oh dear, I see what i've forgotten.
Thank you very much :)

I forgot the line in the constructor, which creates a new GridRowSelectionMixin.
What a stupid mistake...

**Comment by Xeppyz** [comment]
Bro, I've been searching this solution, Ty so much
