### ISSUE TITLE
MySaveHandler doesn't call any of the override methods

### ISSUE THREAD

**Issue by njdkj** [volkanceylan/Serenity#3906]
Hi,
I am a new Serenity user.  I have a custom screen which uses default Endpoint and Repository classes for save process.  The screen is not linked to any table.  User inputs some info here and the custom processed info then to be saved in multiple tables at the back end which is a SQL server.

Endpoint class works fine.   I am trying to put all of my validation code in ValidateRequest() of MySaveHandler class.  However, it doesn't call any of the override methods defined in that class.

Here is how I am trying to do:
public SaveResponse Update(IUnitOfWork uow, CustomSaveRequest request)
{
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
}

private class MySaveHandler : SaveRequestHandler<MyRow, CustomSaveRequest, SaveResponse>
{
            protected override void ValidateRequest()
            {
                     base.ValidateRequest()
                      //.....All of the validation code goes here.........
            }

            protected override void BeforeSave()
            {
                     base.BeforeSave();
                     // Some more code goes here........
            }
}

public class CustomSaveRequest: SaveRequest<CustomRow>
{
        public CustomProps CustProps { get; set; }
}

In the dialog, the update service is called this way on the click of 'save-and-close-button' :
export class MyDialog extends Serenity.EntityDialog<CustomRow, any> {
........

     onClick: () => {
          var request = this.getSaveRequest(); 
          MyService.Update(
                {
                    Entity: request .Entity,
                    EntityId: request .EntityId,
                    CustProps : this.customProps
                },
                response => { ..... }
           );
     }
}

Note that I am using custom SaveRequest which is inherited from SaveRequest plus an additional parameter (a class of multiple variables).  When I debug, I see that the params that I send from the UI is correctly passed to MySaveHandler class, but the debugger doesn't get into ValidateRequest() method at all.  I have another screen which has similar setup but uses the default SaveRequest and it seem to work fine there.

Any Idea on what I am doing wrong here?  Any clue or suggestions is greatly appreciated.

Thank you.

**Comment by stixoffire** [comment]
Is your save handler being called and executing ? My save handler is working , I have a component that I create a special value for and I override the beforsave method to do this. Mine is called, I also use the if(IsCreate) within that override ..

**Comment by njdkj** [comment]
It seems like it tries to run the select statement on the name of my row 'Custom' as if it went through the update without running any of the override methods I have in that class.  I can step through the variables I defined in MySaveHandler class, but cannot step into any of the methods.   I believe, by default the process takes the name of the Row as the name of the table to be updated.  As I want to add and update multiple rows to multiple tables, I want to write my own code in the virtual methods defined in that class.

I have another screen with the similar approach works perfectly fine.  Just can't figure out what's different on this screen!

**Comment by njdkj** [comment]
It seems like it doesn't call the override methods in the Repository when the dialog is initiated with loadEntityAndOpenDialog and you use a Custom SaveResponse which inherits the default SaveResponse.  Not sure if there is a way to make it work.

**Comment by volkanceylan** [comment]
It works as long as you dont make it not call handler.

**Comment by njdkj** [comment]
Thanks.  However, I didn't make an exclusive call to NOT to call handler.  Hence, it calls MySaveHandler as I can step through if I define any variables in that class, but doesn't call any of the override methods.  Changed MySaveHandler to use my CustomHandler as below.

private class MySaveHandler : SaveRequestHandler<MyRow, **CustomSaveRequest**, SaveResponse>
{
            protected override void BeforeSave()
            {
                base.BeforeSave();
                //.....All of the validation code goes here.........
            }
}
