### ISSUE TITLE
ValidationRule only on custom button action

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#391]
Hi @volkanceylan,
I managed to add a new validationRule in an EntityDialog, but I was wondering if there is a way to "activate" this validation rule only when I press my custom button and not (for example) when I press the standard update / apply buttons.

Thanks

**Comment by volkanceylan** [comment]
Store which button clicked and check it there.

**Comment by marcobisio** [comment]
Do you mean in the OnClick event of the buttons? 
So every ToolButton set itself (id?) in a global Dialog variable?

**Comment by volkanceylan** [comment]
Only save buttons trigger validation. You should override their Click events, storing reference to old handlers, when clicked write it to a variable, then in validation method check which is clicked. But i'd recommend skipping validation system completely and checking form input value separately for your button, showing a Q.Alert if there is an error.

**Comment by marcobisio** [comment]
Copy that!
I'll try...once again thanks for your support!
