### ISSUE TITLE
Styling line in Theme Samples

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#3911]
I would like to style my inputs similar to the Theme Samples but I don't know where to start. Any pointers would be greatly appreciated. Many thanks in advance.
![image](https://user-images.githubusercontent.com/17013052/45574484-ce605f80-b835-11e8-92ee-e70a7f3ab22e.png)

**Comment by ga5tan** [comment]
I'd put classes from Them Samples into Form.cs

something like this:
[CssClass("sample_class")]
        public String FirstName { get; set; }

(not tested)

**Comment by c9482** [comment]
Hello @ga5tan ,
I still don't know what css class I would use for, let say email input. It seems it would take more than just providing the CssClass attribute.

![image](https://user-images.githubusercontent.com/17013052/45576961-467f5300-b83f-11e8-852b-7f8a2356c0f6.png)

**Comment by minhhungit** [comment]
@c9482  I think you have to build your own editor

**Comment by minhhungit** [comment]
Here is a sample:
```javascript
@Editor('String', [IStringValue])
    @Element("<input type=\"text\"/>")
    export class StringEditor extends Widget<any> {

        constructor(input: JQuery) {
            super(input);
        }

        public get value(): string {
            return this.element.val();
        }

        protected get_value(): string {
            return this.value;
        }

        public set value(value: string) {
            this.element.val(value);
        }

        protected set_value(value: string): void {
            this.value = value;
        }
    }
```

Check more at here:
https://github.com/volkanceylan/Serenity/blob/master/Serenity.Scripts/CoreLib/UI/Editors/Editors.ts

**Comment by c9482** [comment]
@minhhungit thanks for pointing me in the right direction. Why would this not work then?

![image](https://user-images.githubusercontent.com/17013052/45836187-b96e4b00-bcd1-11e8-9bb2-43ddeee8e3e8.png)

**Comment by minhhungit** [comment]
Can you post your code about `MaskedEditor` with option `MaskedEditorOption`

**Comment by minhhungit** [comment]
Check this
```javascript
    @Serenity.Decorators.registerEditor()
    export class TelephoneEditor extends Serenity.MaskedEditor{  // <=====================

        constructor(input: JQuery, opt: Serenity.MaskedEditorOptions) {
            super(input, opt);

            // write your code here
        }
    }
```

**Comment by c9482** [comment]
@minhhungit , now this works as I expected. Now I have a better understanding of styling but I still have a lot to learn about TypeScript. Thanks again!
