### ISSUE TITLE
dashboard help

### ISSUE THREAD

**Issue by AbhishekhHugar** [volkanceylan/Serenity#3914]
hey,
![capture5](https://user-images.githubusercontent.com/40484328/45611745-238eb200-ba7e-11e8-80a8-82ae02f97e5b.JPG)
in the above image  for different items i added filter to show items which has item type=1 so it shown count =2 when i click on more info i get all the items in the list is it possible to show on the items which has item type=1 and only the 2 items
![capture7](https://user-images.githubusercontent.com/40484328/45611908-ca734e00-ba7e-11e8-9295-4835c635a5b7.JPG)

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/daefd17cdf4713fce40d5145bde35b5a250dd26d/Serene/Serene.Core/Modules/BasicSamples/DynamicNavigation/DynamicNavigationSample.cs

**Comment by AbhishekhHugar** [comment]
hey  @Zahar661  ,
i tried the code you suggested but didnt work , is there anything missing?

**Comment by brunobola** [comment]
@AbhishekhHugar You can personalize everything using MVC queries, Dashboard is only a sample for you to change accordingly its not a serenity issue. @Zahar661 give a sample for you to use as a way to guide you.

You can change the XXXPage.cs to your needd and the XXX.cshtml also.

Sample XXXPage.cs:
```
var model = new DashboardPageModel();
using (var connection = SqlConnections.NewFor<VPrjProjetosRow>())
{
	model.TotalProjetos = connection.Count<VPrjProjetosRow>();
}
```

Sample XXX.cshtml
```
...
@model FichaProjeto.Common.DashboardPageModel
...
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>@Model.TotalProjetos</h3>
                <p>Total de Projetos</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="~/Projetos/Projetos" class="small-box-footer">Mais informação <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div><!-- ./col -->
...

```

**Comment by AbhishekhHugar** [comment]
@brunobola  i have done this  all i want is when i click on more info it should display the items to i have given condition to
like page.cs i have set to show items on dashboard that has material type to 1 and it also works but when i click on more info it should display only 2 items not all items

**Comment by Zahar661** [comment]
```

...
            <a href="~/Projetos/Projetos?type=1" class="small-box-footer">Mais informação <i class="fa fa-arrow-circle-right"></i></a>

...

```

in xxxGrid.ts
```
 protected onViewSubmit(): boolean {
            if (!super.onViewSubmit()) {
                return false;
            }

            let request = this.view.params as Serenity.ListRequest;
            var q = Q.parseQueryString();
            if (q["type"]) {
                 request.Criteria = Serenity.Criteria.and(request.Criteria, [[fld.TypeId], '=', q["type"]]);
            }
               
            }

            return true;
        }
```

**Comment by stixoffire** [comment]
@Zahar661 Thanks for that - it helped me too - I needed to link to the page and get the query - I tried the parseQuerystring - but it was that onViewSubmit () function that I needed to get..
Thanks for sharing ...
