### ISSUE TITLE
Add Default Value as Expression

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#3916]
Hello,

How can I Pass Default Value as Expression in XYZRow.cs ?
[DisplayName("Vendor Code"), Size(50), QuickSearch,DefaultValue("A" + Fields.Id.ToString())]

**Comment by volkanceylan** [comment]
You can't, default value is not an expression nor sql

**Comment by TechAspirant** [comment]
Ok, How can I get last Field Id Value in afterLoadEntity event

```
protected afterLoadEntity()
        {
            super.afterLoadEntity();
            this.form.VendorCode.value = "UPLVC";
        }
```

**Comment by volkanceylan** [comment]
See auto numbering sample
