### ISSUE TITLE
IDataReport Excel Only No pdf

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#3917]
This is more of a question than an issue - the Reports utilize IDataReport and I noticed the dialog has only Excel for the report type download. In the Report Dialog.ts file 
there is            
```
 this.toolbar.findButton('export-pdf-button')
                .toggle(this.report && !this.report.IsDataOnlyReport);
```

So if IDataReport - no PDF button.

Also in the controller 

```
            if (report is IDataOnlyReport)
            {
                ext = "xlsx";
                renderedBytes = new ReportRepository().Render((IDataOnlyReport)report);
            }
```

Is there a code design reason that PDF report is not included for an IDataReport or can / should this functionality be added for the IDataReport?

**Comment by volkanceylan** [comment]
It is by design

**Comment by stixoffire** [comment]
@volkanceylan 
Considering by design ; should I even consider to add pdf  there or should I generate a different report type instead of IDataReport and provide PDF output there , I would appreciate any suggestions / thoughts you might have .. thank you.

**Comment by volkanceylan** [comment]
You cant get pdf from an data inly report
