### ISSUE TITLE
ClonableEntity; How to trigger this functionality without using "builtin" (but hidden) button?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3919]
Hi all,

I would like to use the clonableEntity functionality but from within my own workflow within xyzDialog.ts.

Within the serene demo project, there is only the basic sample which uses this funktionality from the builtin Clone button.

How can I trigger/use this functionality from within my own workflow (withi xyzDialog.ts) without using the click-event on that particular button?

Thanks for any help and

with kind regards,

John

**Comment by Estrusco** [comment]
In dialog you can use super.getCloningEntity()

**Comment by brunobola** [comment]
@JohnRanger I make a [Wiki ](https://github.com/volkanceylan/Serenity/wiki/Implementing-isCloneMode) with a small sample It might be a starting point.

**Comment by JohnRanger** [comment]
Hi all,

thanks for all your input. I have now solved the whole story completely different (doing the cloning all on the backend and then refesh the existing dialog with this.loadById(response.EntityId); withn the service callback.

If I find the time I will make a Wiki entry for this.

With kind regards,

John
