### ISSUE TITLE
Return message in validation rule

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#392]
Hi @volkanceylan,
I don't understand how the return statement works in a validation rule.
The code of which I'm talking about is the following:
![image](https://cloud.githubusercontent.com/assets/17425690/13706909/794bb488-e7a7-11e5-9ad1-16d98fa48bfd.png)

Now, the return "Discount..." is supposed to be shown to the user?
Because if the validator "fail", I see the standard message of a failed validation:
![image](https://cloud.githubusercontent.com/assets/17425690/13706970/c4490710-e7a7-11e5-9620-ddbf611b7fdd.png)

Thanks

**Comment by volkanceylan** [comment]
It is shown on red marks as a hint

**Comment by marcobisio** [comment]
Ohhh...you're right!
Thank you very much!

**Comment by volkanceylan** [comment]
Actually its not so user friendly. I'll later add a few of such errors to message in toastr as a validation summary.

**Comment by marcobisio** [comment]
A validation summary would be perfect !
Thanks again :-)

**Comment by mantiklas** [comment]
@volkanceylan. How to reset that red marks, because sometimes the validations have dependencies not only in one field...  fixing the other field, must remove that red marks.. but that red marks is still showing.. It may confused the user.

**Comment by teafmartins** [comment]
@mantiklas  HI! I have the same problem... with validation dependecies. Do you known how to reset red marks?

**Comment by muhammedyaman** [comment]
@mantiklas @teafmartins hey its 7 years late but i'm just leaving this if anyone is looking for solution about it: 
You can simply just add the dependencies on your validation logic as below
```
this.form.WarehouseNumber.addValidationRule(this.uniqueName, e => {
    if (Q.isEmptyOrNull(this.form.WarehouseNumber.value) && this.form.IsVirtual.value == true) {
        return "Error message here";
    }
});
```
As you can see I want WarehouseNumber to be filled if IsVirtual field is set to true.
