### ISSUE TITLE
Cannot update identity column 'xxxxxxxx'

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#3920]
Why would I get error "Cannot update identity column 'PermitId'." during update operation? PermitId is marked as Identity (even though I use column RequestId as EntityId because it's unique). Any pointers would be appreciated.

Row class:
    public sealed class PermitRow : Row, IIdRow, INameRow, Modules.Common.Audit.IAuditLog
    {
        [DisplayName("Permit Id"), Identity]
        public Int32? PermitId
        {
            get { return Fields.PermitId[this]; }
            set { Fields.PermitId[this] = value; }
        }

        [DisplayName("Request"), NotNull, ForeignKey("[dbo].[REQUEST]", "RequestId"), LeftJoin("jRequest"), TextualField("RequestRequestNumber")]
        public Int32? RequestId
        {
            get { return Fields.RequestId[this]; }
            set { Fields.RequestId[this] = value; }
        }
....
        IIdField IIdRow.IdField
        {
            get { return Fields.RequestId; }
        }

Another class updating the PermitRow:

                PermitRepository permitRepo = new PermitRepository();
                PermitRow p = permitRepo.Retrieve(uow.Connection, new RetrieveRequest { EntityId = r.RequestId }).Entity;
                p.PermitNumber = nr.Year.ToString().Substring(2) + "-" + nr.NextIdFormatted;
                permitRepo.Update(uow, new SaveRequest<PermitRow> { Entity = p, EntityId = p.RequestId });

**Comment by Estrusco** [comment]
Probably when you try to update the PermitId is changed or is null.

**Comment by c9482** [comment]
Is it legal to declare IdField with a non-identity field (a field which is still unique)? In my code, PermitId is the Identity but IdField = RequestId.

**Comment by c9482** [comment]
In my code I removed the Identity column (PermitId) and left a PrimaryKey column (RequestId). The IdField = RequestId. Now when I try to save PermitRow, I get a null pointer exception inside of the AuditRowBehavior for the row class (for some reason the value of the row id is null even if I don't touch it before the update). If I disable the AuditLog, the row saves just fine. So there is something going on in AuditLog class I am using:

https://github.com/volkanceylan/Serenity/wiki/Audit-Log-for-Insert-Update-and-Delete-using-Single-Table

**Comment by volkanceylan** [comment]
You better use the audit logging system in StartSharp, which also uses a single table.
