### ISSUE TITLE
ERROR: Import To Excel

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3921]
Good Afternoon.
Getting error on-click of import From excel button(Referred BasicSamples-ProductImportFromExcel )

![capture9](https://user-images.githubusercontent.com/39983941/45668848-cfe29e00-bb3b-11e8-9a4c-7f17241c0686.PNG)

**Comment by volkanceylan** [comment]
There is no such error in demo, you fix ur code
