### ISSUE TITLE
Change lookup for another one

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3925]
I have a lookup field in my Form, but at cerain conditions I would like to swap/switch it to different lookup.
In other words, the options in combo would be differently filtered. How is it possible?

**Comment by javaman63** [comment]
See https://serenity.is/demo/BasicSamples/ChangingLookupText#!1
Or
https://serenity.is/demo/BasicSamples/FilteredLookupInDetailDialog

Depending on what you want to get

**Comment by ga5tan** [comment]
@javaman63  thx, second demo with cascadeField and cascadeValue may be what I need.
I thought of completely replacing control with the one of another LookupScript, but filtering may do
