### ISSUE TITLE
How to Change Lookup Value feild to Something else

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#3926]
I want my lookups value field should be some thing other than ID field of ROW

that is my below code, now when i click NewPerson Add form it throws DB Foreign key constraint,
Issue is In DepartmentCode feild in PersonRow it passed Select Value field as ID of DepartmentRow.
rather i want to map this to DepartmentCode field from Department Row.

To be simple, i want to change select value field of to other field from Lookup row other than Row ID Feild

**DepartmentEdior.ts**
``
namespace Nemo.Default {

    @Serenity.Decorators.registerEditor()
    export class DepartmentEditor extends Serenity.LookupEditorBase<Serenity.LookupEditorOptions, DepartmentRow> {

        constructor(hidden: JQuery) {
            super(hidden);
        }

        protected getLookupKey() {
            return DepartmentRow.lookupKey;
        }

        protected getItemText(item, lookup) {
            return item.DepartmentCode + ' [' + item.DepartmentName + ']';
        }
    }
}
``

**PersonRow**
``

        [DisplayName("Person Code"), Size(50), PrimaryKey, ForeignKey("[dbo].[Persons]", "PersonCode"), LeftJoin("jPersonCode"), TextualField("PersonCodePersonName")]
        [DepartmentEditor]
        public String PersonCode
        {
            get { return Fields.PersonCode[this]; }
            set { Fields.PersonCode[this] = value; }
        }

        [DisplayName("Person Id"), Expression("jPersonCode.[PersonID]")]
        public Int32? PersonCodePersonId
        {
            get { return Fields.PersonCodePersonId[this]; }
            set { Fields.PersonCodePersonId[this] = value; }
        }

        [DisplayName("Person Name"), Expression("jPersonCode.[PersonName]")]
        public String PersonCodePersonName
        {
            get { return Fields.PersonCodePersonName[this]; }
            set { Fields.PersonCodePersonName[this] = value; }
        }
``
DepartmentRow
``

	[LookupScript("DepartmentCode"),LookupEditor("DepartmentCode")]
    public sealed class DepartmentsRow : Row, IIdRow, INameRow
    {

      
        [DisplayName("Department Id"), Column("DepartmentID"), Identity]
        public Int32? DepartmentId
        {
            get { return Fields.DepartmentId[this]; }
            set { Fields.DepartmentId[this] = value; }
        }

        [DisplayName("Department Name"), Size(100), QuickSearch]
        public String DepartmentName
        {
            get { return Fields.DepartmentName[this]; }
            set { Fields.DepartmentName[this] = value; }
        }

      
        [DisplayName("Department Code"), Size(50), NotNull,LookupInclude]
        public String DepartmentCode
        {
            get { return Fields.DepartmentCode[this]; }
            set { Fields.DepartmentCode[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.DepartmentId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.DepartmentName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public DepartmentsRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {

            public Int32Field DepartmentId;

            public StringField DepartmentName;

            public StringField DepartmentCode;

		}
    }

**Comment by javaman63** [comment]
see https://serenity.is/demo/BasicSamples/ChangingLookupText#!1
On Basic Samples

**Comment by JohnRanger** [comment]
This is by design not possible, if I understand Volkan correctly (I had the same request some years earlier :-)).

Within your row, you should not store Department code directly but the ID of the department code.

If you do the linking (Diagramming and setting keys) of the tables before you do import them into your project with sergen then sergen will add foreign fields of your department table into the main xyzRow.cs and then you can use e.g. Department code foreign field to display within grid - and if you add the [lookupScript] within the DepartmentRow.cs and [LookupEditor] on the departmentId field within your main row it will automatically display the DepartmenCode instead of the Id.

Hope this helps.

With kind regards,

John

**Comment by jabirmoolur** [comment]
@JohnRanger Thanks.!
