### ISSUE TITLE
How to break site title into two lines

### ISSUE THREAD

**Issue by yaseen-h** [volkanceylan/Serenity#3928]

**Comment by JohnRanger** [comment]
What happens if you insert within the title a <br> where you want to break it into the next line?

**Comment by minhhungit** [comment]
@yaseen-h Try this 

```javascript
constructor(container: JQuery) {
    super(container);

    var titleElement = this.titleDiv.find(".title-text");
    var originalTitle = titleElement.text();

    titleElement.empty();
    titleElement.append($(`<div>${originalTitle}</div><div style="color: gray; font-size: 13px">This is second line</div>`));
}
```

![image](https://user-images.githubusercontent.com/2279508/45801219-6b5f4480-bcdd-11e8-96ae-27ad63f8b2a0.png)

**Comment by yaseen-h** [comment]
I meant the side bar title:
![image](https://user-images.githubusercontent.com/7968069/45858094-6beeee00-bd64-11e8-8217-9a63dcc3b7f3.png)

**Comment by edwardch** [comment]
I am no c#/css/html expert, but that is what you'll want to try and fiddle around with.

In **Views/Shared/_Layout.cshtml**, change line 45 to:

```html
<span class="logo-lg"><i></i><b>@LocalText.Get("Navigation.SiteTitle")<br />@LocalText.Get("Navigation.SiteTitleLine2")</b></span>
```

In **Content/adminlte/header.less**, inside .logo change _line-height_ to something like 20px:
(or smaller or bigger - your choice)
```css
line-height: 20px;
```
I don't know what other side effects this might have ^^

In **Modules/Texts.cs**, in the _Navigation_ class add:
```c#
public static LocalText SiteTitle2 = "Line 2 Text";
```


Good luck!

**Comment by yaseen-h** [comment]
Only change the line-height is fix the issue

Thanks
