### ISSUE TITLE
Blank page after deployment

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#393]
Sorry if this is not quite Serenity related but this is my first IIS web app... After deploying the app, I get a blank page. View source reveals proper html mark up but nothing shows up. I would appreciate any pointers.

**Comment by c9482** [comment]
BTW, the OS is Windows 2008 R2 server.

**Comment by volkanceylan** [comment]
See chrome console

**Comment by c9482** [comment]
Never mind - found the answer. Did not have ASP.net enabled. Thanks.
