### ISSUE TITLE
lookup exception

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#3930]
Hi, I am getting the following exception:
'Types DCM.Administration.Entities.LanguageRow and DCM.Administration.LanguageLookup has the same lookup key ("Administration.Language")

My Language row looks like this:
[LookupScript(typeof(LanguageLookup), LookupType = typeof(MultiTenantRowLookupScript<>))]
    public sealed class LanguageRow : Row, IIdRow, INameRow 

My LanguageLookup.cs looks like this:
[LookupScript]  
public sealed class LanguageLookup : MultiTenantRowLookupScript<LanguageRow>

if i remove the [LookupScript] attribute from the LanguageLookup class then i get the following error:
ystem.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Type xxx.Administration.LanguageLookup is specified as lookup type in a LookupScript attribute, but it has not LookupScript attribute itself.
  Source=Serenity.Core
  StackTrace:
   at Serenity.ComponentModel.LookupScriptAttribute..ctor(Type lookupType)

All help will be appriciated.
Thanks

**Comment by volkanceylan** [comment]
Remove LookupType from Row

**Comment by dudeman972** [comment]
Thanks.
