### ISSUE TITLE
Execute SqlQuery - Serenity.Data in .ts

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#3931]
How can I Execute SqlQuery - Serenity.Data in .ts and get its data in local variable ?

**Comment by minhhungit** [comment]
@TechAspirant 
SqlQuery is at server side, so if you want to call it, I think you have to create a endpoint service and call that service at  client side (typescript)

**Comment by TechAspirant** [comment]
Can you please share am example ?

**Comment by Estrusco** [comment]
Read section service endpoint of Serenity manual

https://volkanceylan.gitbooks.io/serenity-guide/services/service_endpoints.html

Then you can make your services (action method), then transform T4 and call it from .ts with 

```ts
    XYZService.YourService({
        YourRequest: value
    },
    yourResponse => {
        let tmp = yourResponse.YourData;
    });
```
