### ISSUE TITLE
Reusing Serenity's User Agent detection

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3932]
Hi all,
Serenity surely has somewhere a reliable detection mechanism for finding out which browser is currently used to access a Serenity-based application. I have looked around - but didn't find this information.

Currently I have some own code with which I more or less detect the Browser manufacturer - but I would like to use/reuse what is already within SF.

My current browser detection code (which works) looks like this:

```js
                        // *** Detect browser ***
                        var ua = navigator.userAgent;
                        if (ua.indexOf('Chrome') !== -1) {
                            // Chrome
                        }
                        else if (ua.indexOf('Firefox') !== -1) {
                            // Firefox
                        }
                        else {
                            // *** probably IE ***
                        }

```

Any hint how SF does it and how this can be used from within a SF project?

Thanks for your feedback and

with kind regards,

John

**Comment by ga5tan** [comment]
my wild guess would be Serenity is using jQuery for this kind of job...
so maybe check there?

**Comment by JohnRanger** [comment]
Hi @volkanceylan ,

thanks for your feedback.

Wow: All the whole SF works in the commonly used browsers? That's amazing...

By the way: As of today, The language selection within IE11 still doesn't work on your demo page. Confirmed by others too. Please try it with real IE11 - not Edge. 

With kind regards,

John

**Comment by ga5tan** [comment]
@JohnRanger I believe Bootstrap and maybe even Admin LTE (theme used) do have some browser specific stuff. I saw it in themes CSS/less
