### ISSUE TITLE
Issue : no view engine supports

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#3934]
I have an error, and i am a beginner serenity development, anyone or @volkanceylan  could help me ? that my error below :

The view '~/Modules/Default/Reports/MissedPickUpIndex.cshtml' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Modules/Default/Reports/MissedPickUpIndex.cshtml

**Comment by minhhungit** [comment]
Then you need to make sure that there is `MissedPickUpIndex.cshtml` file in  `/Modules/Default/Reports/`

**Comment by resitaufan** [comment]
ok, its solved many thanks bro...

**Comment by resitaufan** [comment]
@ minhhungit  can you give me a solution #4527
