### ISSUE TITLE
Serin Issue

### ISSUE THREAD

**Issue by sekeroth** [volkanceylan/Serenity#3938]
I am attempting once again to use the Serenity template on Windows. I have up-to-date versions of Typescript, nodeJS and .net core framework. The following error is repeatable. Any help would be appreciated.

PS C:\Serene> cd SereneCore
PS C:\Serene\SereneCore> serin
Welcome to Serene Initializer!

Reading latest template version from VSGallery...
You already have a cached copy of latest version.

Enter a project name (press enter for Serene1)?
Creating solution Serene1
Creating project Serene1.Web (using Serene.Core\Serene.Core.vstemplate)
Restoring packages for Serene1.Web
  Restoring packages for C:\Serene\SereneCore\Serene1.Web\Serene1.Web.csproj...
  Restore completed in 102.97 ms for C:\Serene\SereneCore\Serene1.Web\Serene1.Web.csproj.
  Generating MSBuild file C:\Serene\SereneCore\Serene1.Web\obj\Serene1.Web.csproj.nuget.g.props.
  Generating MSBuild file C:\Serene\SereneCore\Serene1.Web\obj\Serene1.Web.csproj.nuget.g.targets.
  Restore completed in 1.98 sec for C:\Serene\SereneCore\Serene1.Web\Serene1.Web.csproj.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown EPIPE
    at ReadStream.Socket._final (net.js:370:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ReadStream.onerror (_stream_readable.js:690:12)
    at ReadStream.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
PS C:\Serene\SereneCore>

**Comment by ga5tan** [comment]
sorry for asking, but why dont u just download VS Community version and get whole thing via UI ?
worked like a charm back in my day (especially on Windows)

**Comment by sekeroth** [comment]
In fact, I already tried that approach with VS Professional 2017 in the creation of the project just hangs, so I thought that I would try this approach instead.

**Comment by volkanceylan** [comment]
Sorry, can't reproduce this, should be something related to your environment

**Comment by ebekker** [comment]
I'm having the same issue -- just followed the guide to install using latest dotnet SDK (2.2.100) and latest LTS version of NodeJS.

**Comment by ebekker** [comment]
Here's the full output:
```pwsh
Welcome to Serene Initializer!

Reading latest template version from VSGallery...
You already have a cached copy of latest version.

Enter a project name (press enter for Serene1)? MyFirstSerene
Creating solution MyFirstSerene
Creating project MyFirstSerene.Web (using Serene.Core\Serene.Core.vstemplate)
Restoring packages for MyFirstSerene.Web
  Restoring packages for D:\prj\serenity\MyFirstSerenity\MyFirstSerene.Web\MyFirstSerene.Web.csproj...
  Restore completed in 83.6 ms for D:\prj\serenity\MyFirstSerenity\MyFirstSerene.Web\MyFirstSerene.Web.csproj.
  Generating MSBuild file D:\prj\serenity\MyFirstSerenity\MyFirstSerene.Web\obj\MyFirstSerene.Web.csproj.nuget.g.props.
  Generating MSBuild file D:\prj\serenity\MyFirstSerenity\MyFirstSerene.Web\obj\MyFirstSerene.Web.csproj.nuget.g.targets.
  Restore completed in 1.52 sec for D:\prj\serenity\MyFirstSerenity\MyFirstSerene.Web\MyFirstSerene.Web.csproj.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown EPIPE
    at ReadStream.Socket._final (net.js:374:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ReadStream.onerror (_stream_readable.js:690:12)
    at ReadStream.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by tonysader** [comment]
@ebekker 
I am having the same issue!! 
Did you solve this?

**Comment by ebekker** [comment]
Sorry no, I stopped pursuing it.
