### ISSUE TITLE
Errors using InplaceAdd with from multi-select LookupEditor

### ISSUE THREAD

**Issue by jcamp45** [volkanceylan/Serenity#394]
I am seeing multiple issues utilizing the InplaceAdd function within a LookupEditor where Multiple=true.

For example, take the Representatives field within the Northwind Customer Row and add InplaceAdd=true: 
[LookupEditor(typeof(EmployeeRow), Multiple = true, InplaceAdd = true), ClientSide]

The New/Edit button then appears as expected next to the field.  If there are one or zero selections, this function works fine.  However after selecting a couple items, this feature produces several errors:
1. If you just click on the Edit button, an error of "Input string was not in a correct format" is shown.
2.  If you select the option "*** No results. Click to define a new one ***, it selects that item and does not produce the New Employee dialog as expected.

Is there a workaround for allowing these two great features to work together?

**Comment by volkanceylan** [comment]
That feature is not compatible yet with multiple select

**Comment by ChenZhaobin** [comment]
haha,I met the same problem

**Comment by nidhiNV** [comment]
I am facing the same problem. Can I get any help on this as it is one of the requirements in my project.

Thanks

**Comment by mrTurkay** [comment]
I solved that issue as, not editing inplace when it is multiple. if it is multiple, always add new things. 

firstly at addInplaceCreate method in serenity.Script.UI.js
`      if (!this.$multiple)
           inplaceButton.attr('title', (isNew ? addTitle : editTitle)).toggleClass('edit', !isNew);
        `
it is at line 4468 in serenity.Script.UI.js.

and then, add if multiple control also at line 4719.

`                    if (!self.$multiple)
                        self.set_value(null);

                    if ((dci.type === 'create' || dci.type === 'update') && ss.isValue(dci.entityId)) {
                        if (self.$multiple)
                            self.set_value(self.get_value() + ',' + dci.entityId.toString());
                        else self.set_value(dci.entityId.toString());
                    }
`
