### ISSUE TITLE
How to make drop down list with multiple columns?

### ISSUE THREAD

**Issue by yaseen-h** [volkanceylan/Serenity#3940]

**Comment by yaseen-h** [comment]
Sorry, first time to submit comment in Git
How can ask question about Serenity in Git?

**Comment by ga5tan** [comment]
dunno about multicolumn combo, but there is dialog select in premium template.
also you can prolly just open dialog with rows, and pass back selected ID ?

**Comment by yaseen-h** [comment]
I have field with two values (Short and Long)
I want to show both values in drop down list for select

Currently I am showing like this:
SD | Service Desk
HR | Human Resource

But if I can formatted as two columns it will be more nice

Also I am using this field for quick filter so can search inside the drop down list using short or long value

**Comment by JohnRanger** [comment]
Hi @yaseen-h 

I never have done it - but as Serenity uses jQuery Select2 widget, have a look at this StackOverflow solution for this: https://stackoverflow.com/questions/16556261/display-multiple-columns-in-select2

Within xyzDialog, you would have to do the static part (e.g. header declaration, etc) in protected override void afterLoadEntity()
{...
}

and the rest (formatted dropdown entries) where you already are now modifying the standard drop down (which is only only column and where you now put the string with short and long names together).

Hope this hints you into the right direction.

With kind regards,

John

**Comment by minhhungit** [comment]
I don't sure what did you mean about "with multiple columns", but I can give you some suggestions:
- [How to Create Lookup Editor for code description tables ](https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables)
- Default, Serenity just load 2 fields which were implemented from IIdRow & INameRow, use `LookupInclude` attribute will tell it get more

**Comment by minhhungit** [comment]
and this one:
[ChangingLookupText](https://serenity.is/demo/BasicSamples/ChangingLookupText#!1)

**Comment by yaseen-h** [comment]
Thanks @minhhungit 
I managed to have multi columns drop down list using your suggested sample:
[How to Create Lookup Editor for code description tables](https://github.com/volkanceylan/Serenity/wiki/How-to-Create-Lookup-Editor-for-code-description-tables)
