### ISSUE TITLE
Get data in Row.cs from third table

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3942]
It is possible to lookup data in row from Left Join table like this:
[DisplayName("Registrant ID"), Column("RegistrantID"), NotNull, ForeignKey(typeof(UsersRow)), LeftJoin("jRegistrant")]

but I need to make left join on left joined column, ie add third table, which entity is referenced in second (leftJoined) table.

any idea if that's possible?

**Comment by JohnRanger** [comment]
Hi @ga5tan ,

just try it. In your case it would be on the UserId foreign field within the xyzRow where your [DisplayName("Registrant ID")...] declaration is. 

Just do again the foreignKey(typeof(<your3rdTable>)), LeftJoin("j<Your3rdTableNickname>");

I had done this long - long ago - and it had worked as I remember.

With kind regards,

John

**Comment by ga5tan** [comment]
thx @JohnRanger , it worked.
for some reason I had to specify source column in Origin tag as well, but it works!
this is second LeftJoin on already joined field:

`[DisplayName("Code"), Origin("jRegistrant"), Expression("jRegistrant.[LoginId]"), ForeignKey(typeof(Respondents.Entities.UserLoginRow)), LeftJoin("jRespondent"), MinSelectLevel(SelectLevel.List)]
`

this is from third table:

`[DisplayName("Code"), Origin("jRespondent","Username"), Expression("jRespondent.[Username]"), MinSelectLevel(SelectLevel.List)]`

**Comment by antoniojp** [comment]
I have the same problem. Could you post the complete Row file?
