### ISSUE TITLE
xyzForm/Dialog: How to display Date & Time when field is readonly

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3944]
Hi all,

this is with SF 2.9.24. I am having difficulty to make the dialog/form to show a full Date and time (not only date) within a readonly dateTime field.

I have tried already:

- [DateTimeKind...] on Form field
- [DateTimeEditor] on Form field

to no avail.

Any hint how to achieve a display of date and time on Form (the value within the DB contains date and time).

And as a bonus question: How to format the displayed timestamp within the **form** field so that it is displayed: dd.MM.yyyy HH:mm:ss (DatetimeFormatter only works on grid.)

Thanks and 

with kind regards,

John

**Comment by volkanceylan** [comment]
Please check older questions for culture. DateTimeEditor should do.
