### ISSUE TITLE
How change field value after submit client side and before submit to server side

### ISSUE THREAD

**Issue by yaseen-h** [volkanceylan/Serenity#3947]

**Comment by ga5tan** [comment]
I have replaced save buttons with my own, that way I have more control over saving. I have custom service that saves entity as well as generates invoice, Quickbooks entry and all that jazz.
So you can do your stuff, then validation, then saving...

**Comment by yaseen-h** [comment]
I found solution as following:
Override this function under Dialog.ts
`save_submitHandler(callback: (response: Serenity.SaveResponse) => void)`

Get value from:
`options.request.Entity`

Then modify it
