### ISSUE TITLE
Overide SaveRequest Handler

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#3949]
How to Overide SaveRequestHandler
Eg:
In one of repository i have the below code.

```
  private class MySaveHandler : SaveRequestHandler<MyRow> {


            protected override void BeforeSave()
            {
                base.BeforeSave();
            }

            protected override void AfterSave()
            {
               base.AfterSave();
            }
                
            protected override void SetInternalFields()
            {
                 base.SetInternalFields();

                  if (IsCreate)
                  {

                    Row.Created = DateTime.Now;
                    Row.CreatedBy = Authorization.Username;
                    Row.Modified = DateTime.Now;
                    Row.ModifiedBy = Authorization.Username;
                   }

                    if (IsUpdate)
                    {
                    Row.Modified = DateTime.Now;
                    Row.ModifiedBy = Authorization.Username;
                    }

            }
}
```

Now I dont want to write this to all repository, rather i want to override the SetInternalFields of amthod itself of SaveRequestHandler with those codes.
How can achieve this? Or suggest me with standard approach to achieve this.

**Comment by hannesb** [comment]
You might add the IUpdateLogRow and IInsertLogRow Interfaces to your row classes. This will trigger the InsertUpdateLogBehavior.

**Comment by ga5tan** [comment]
@hannesb  what does that behavior do? I presume it logs changes of a row?

@jabirmoolur you can omit Before and AfterSave.

if u have multiple tables, where u wanna set sys fields, I recommend writing behaviour doing just that.
there is sample in Tutorial

**Comment by jabirmoolur** [comment]
@ga5tan  can you please post link to same?
Thanks a lot

**Comment by hannesb** [comment]
InsertUpdateLogBehavior saves timestamp/userId in table fields of your choice. Just what you need IMHO.

**Comment by jabirmoolur** [comment]
Can you please post link to sample tutorial as you mentioned in which this behavior is implemented or used
Thanks

**Comment by hannesb** [comment]
Check LoggingRow.cs in Serene template
