### ISSUE TITLE
Master/Details grid does not populate Expression columns

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#395]
This one's a little tough to explain, but I'm trying to get the Details grid of a Master/Detail dialog to display derived columns. Best explained by example: Let's say I want to add the OrderShipCountry to OrderDetailsColumns, so I add `public String OrderShipCountry { get; set; }` Great, that column now shows up when I open an order, but the data in the column is empty and I see the query to the DB does not have the join to the Orders table to pick it up.

**Comment by wldkrd1** [comment]
Ok, I see it's making the join to get ProductName, so I must be missing something...what's different between ProductName and OrderShipCountry?

**Comment by volkanceylan** [comment]
Add MinSelectLevel(SelectLevel.List) it was noted in guide

**Comment by wldkrd1** [comment]
Ahh...didn't realize what that attribute meant. That works, thanks.
