### ISSUE TITLE
How to use IHtmlHelper read a part code in aspnetcore

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#3952]
using Microsoft.AspNetCore.Html;
using NUglify.JavaScript;
using System;

namespace Microsoft.AspNetCore.Mvc.Rendering
{
    public static class HtmlHelperExtensions
    {
        public static HtmlString JsMinify(
            this IHtmlHelper helper,
            Func<object, object> markup)
        {
            string notMinifiedJs =
                (markup.DynamicInvoke(helper.ViewContext) ?? "").ToString();

            var minifiedJs = NUglify.Uglify.Js(notMinifiedJs, new CodeSettings
            {
                EvalTreatment = EvalTreatment.MakeImmediateSafe,
                PreserveImportantComments = false
            });
            return new HtmlString(minifiedJs.ToString());
        }
    }
}

In cshtml page
@Html.JsMinify(@<text>
        jQuery(function () {
            loginPanel = new LoginPanel($('#LoginPanel')).init();
        });
    </text>)

In aspnet it can work,but in aspnetcore it didn't work.

**Comment by volkanceylan** [comment]
This is not asp.net core training site
