### ISSUE TITLE
Select Checkbox

### ISSUE THREAD

**Issue by GayathriSravya** [volkanceylan/Serenity#3953]
Hello Everyone

   Can any one help me how to select the Discontinued Column(checkbox) in the grid 

![edit](https://user-images.githubusercontent.com/34158884/46061008-a6042980-c182-11e8-8019-64f08fcfd412.png)

Regards.

**Comment by minhhungit** [comment]
Check this demo (for dropdown), it will give you the idea, you will need to write code for checkbox:
https://serenity.is/demo/Northwind/Product
