### ISSUE TITLE
User cannot log back in after changing the password

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3955]
Hi

did anybody experience the issue, that after user changes password he cannot log back in?
Debugging shows, old salt is used from cache, thus new password wont be valid.

There is this code at the end of password changing endpoint:

`BatchGenerationUpdater.OnCommit(uow, UserRow.Fields.GenerationKey);`

but it does not seem to be clearing up the cache?

**Comment by ga5tan** [comment]
this is just local development - VS 2017 CE with IIS on W10

**Comment by JohnRanger** [comment]
Hmm,

does the LocalCache.RemoveAll() help?

With kind regards,

John
