### ISSUE TITLE
Defining new "Tag" within xyzForm.cs to put placeholders within DOM

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3957]
Hi all,

as sometimes I need to add additional HTML elements within the dialog between two fields, I would like to have the possibility to add a tag like the [Category("")] tag within the form which then would place an invisible ```<div>``` or something like this at the logical position within the dom which I later (within xyzDialog.ts) can easily find with jquery or even something like ```this.form.<placeholdername>.GetPlaceholder.html = "htmlContenttoInsert"``` to manipulate its HTML.

I think of something like that:
```cs
[HTMLplaceholder("MyAdditionalHTML1")]
```
which then would render the following within the DOM at the correct logical position:
```html
<div class="HTMLPlaceholder MyAdditionalHTML1"></div>
```

How can I do the above?

(Currently, I am using ```$("htmlContentToInsert").insertAfter(this.form.<FieldBeforeInsert>.getGridField()``` but this makes no fun if you deside to move the HTML to another logical position within the form);

This within the spirit of Serenity's declarative programming approach.

Thanks for any feedback and

with kind regards,

John

**Comment by minhhungit** [comment]
This can help you IMHO: 
**Static Text Block**

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Helpers/StaticTextBlock.ts

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

thanks for pointing me into the right direction. This is already quite close to what I want - it is just static text (or pulled from the translation) instead of being an invisible marker within the DOM.

But I think that I will be able to work it out from here.

When I have the solution, I make a Wiki article.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi all, 

I am reopening this issue as - with the solution pointed out by @minhhungit -  I am not able to programmatically set the HTML content at runtime.

Although there is the option that - when we omit the Text parameter within the static text block "tag" - it will take the text from the textfield value, it seems that this is done before the dialog even instantiate as I am not able to make the HTML to appear when I set the value within the constructor or within afterLoadEntity from within the dialog.

I am setting the value like this:
```ts
            this.form.BlablaText.element.val("<b>jojo</b>supi");
            this.updateInterface();
```

(the above html does not visually appear).

But when I enter the Text within the xyzForm.cs like this:

```cs
        [StaticTextBlock(HideLabel = true, IsHtml = true, IsLocalText = false, Text <b>jojo</b>supi")]
        public String BlablaText { get; set; }
```
then the html is displayed fine.

Also I am looking for a solution which does not require fields to be created (also notMapped ones) as this is also not required by the [category] tag.

So after the above - I am looking for a solution where I can "mark" places within the dialog (form part) DOM from within the form and later find these places from within the dialog with jQuery or a better solution like this.form.placeholdername.html = "";

further inputs are anytime welcome :-)

With kind regards,

John

**Comment by minhhungit** [comment]
as I know
>.element.val 

is set value, I think you should use `element.html('<div>demo</div>')`

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

ah - that totally makes sense :-) I will try it and give feedback here.

Thanks for this hint.

with kind regards,

John

**Comment by JohnRanger** [comment]
@minhhungit ,

yes -this works perfectly - even without creating the fields within the xyzRow.cs.

Thanks again.

With kind regards,
John
