### ISSUE TITLE
Checkbox in lookupeditor to select all

### ISSUE THREAD

**Issue by PrasadK1990** [volkanceylan/Serenity#3958]
hello, i need a checkbox in lookup (i.e. drop down) so that i can select multiple value at a time. COULD ANYONE HELP ME OUT WITH THIS??

THANK YOU

**Comment by ga5tan** [comment]
in premium there is product picker, no good ?

**Comment by JohnRanger** [comment]
@PrasadK1990 

hi Prasad, no need to write in upper case :-)

Could you please explain in more details what you mean?

Could you please provide a mockup with what you exactly mean?

With kind regards,

John

**Comment by ga5tan** [comment]
I believe he wants to have checkboxes in combo.
speaking of which, I believe there is some multiselect here already ...
lemmie check samples

**Comment by ga5tan** [comment]
found it, guess what, it contains word 'multi':

https://serenity.is/demo/BasicSamples/LookupFilterByMultipleValues

it's not witch checkboxes, but I like it even more, more modern...

**Comment by PrasadK1990** [comment]
thank you

**Comment by vishmanthisuresh111** [comment]
Hi @JohnRanger  
Above mentioned Order Image 
when  Perform Bulk Action on Selected Orders Button  is clicked then the Grid All records checkboxs should be checked , is there any Option to do like that

**Comment by vishmanthisuresh111** [comment]
![Capture](https://user-images.githubusercontent.com/28822956/58624714-86fbff80-82ee-11e9-97df-fb45a3c27d66.PNG)

**Comment by JohnRanger** [comment]
To Select all checkboxes by y button, see this issue: https://github.com/volkanceylan/Serenity/issues/4467

**Comment by stixoffire** [comment]
@PrasadK1990 @ga5tan @JohnRanger 

I know this is late but thought I would post some possible solution .. to the original question.

Here is something that I found online note there are two options for this ..

[https://stackoverflow.com/questions/22918178/select2-with-a-checkbox-list-for-a-multiple-select](https://stackoverflow.com/questions/22918178/select2-with-a-checkbox-list-for-a-multiple-select)

version < 3.5
[https://github.com/wasikuss/select2-multi-checkboxes/blob/master/select2.multi-checkboxes.js](https://github.com/wasikuss/select2-multi-checkboxes/blob/master/select2.multi-checkboxes.js)

version 4.0 compatibility
[https://github.com/wasikuss/select2-multi-checkboxes/tree/amd](https://github.com/wasikuss/select2-multi-checkboxes/tree/amd)

[http://jsfiddle.net/wasikuss/gx93rwnk/](http://jsfiddle.net/wasikuss/gx93rwnk/)

[https://github.com/wasikuss/select2-multi-checkboxes](https://github.com/wasikuss/select2-multi-checkboxes)

**Example:**
```
$('.select2-multiple').select2MultiCheckboxes({
    placeholder: "Choose multiple elements",
})
```
[JsFiddle Example](http://jsfiddle.net/wasikuss/gx93rwnk/)

All other features of select2 are preserved. There are few more predefined options set to work properly.


-----------------------------------------------------------------------------------------------------
```
/**
 * jQuery Select2 Multi checkboxes
 * - allow to select multi values via normal dropdown control
 * 
 * author      : wasikuss
 * repo < ver4 : https://github.com/wasikuss/select2-multi-checkboxes/tree/select2-3.5.x
 * repo 4      : https://github.com/wasikuss/select2-multi-checkboxes/tree/amd
 * inspired by : https://github.com/select2/select2/issues/411
 * License     : MIT
 */

jQuery(function($)
{
    $('.select2-multiple').select2MultiCheckboxes({
    	placeholder: "Choose multiple elements",
    })
    $('.select2-multiple2').select2MultiCheckboxes({
    	formatSelection: function(selected, total) {
      	return "Selected " + selected.length + " of " + total;
      }
    })
    $('.select2-original').select2({
    	placeholder: "Choose elements",
      width: "100%"
    })
});
```
CSS 
----------------------------------------------------------------------------------
```
.select2-result-label .wrap:before{
    position:absolute;
    left:4px;
    font-family:fontAwesome;
    color:#999;
    content:"\f096";
    width:25px;
    height:25px;
    
}
.select2-result-label .wrap.checked:before{
    content:"\f14a";
}
.select2-result-label .wrap{
    margin-left:15px;
}

/* not required css */

.row
{
  padding: 10px;
}

```

HTML from the fiddle in case you like to see it here..
----------------------------------------------------------------------------------
```
<div class="row">
  <select name="sel-01" id="sel-01" class="select2-multiple">
    <option></option>
    <option value="AL">Alabama</option>
    <option value="CA">California</option>
    <option value="NY">New York</option>
    <option value="TX">Texas</option>
    <option value="WY">Wyoming</option>
  </select>
</div>
 <div class="row">
  <select name="sel-02" id="sel-02" class="select2-multiple2">
    <option></option>
    <option value="AL">Alabama</option>
    <option value="CA">California</option>
    <option value="NY">New York</option>
    <option value="TX">Texas</option>
    <option value="WY">Wyoming</option>
  </select>
</div>
<div class="row">
  <select name="sel-03" id="sel-03" class="select2-original" multiple>
    <option></option>
    <option value="AL">Alabama</option>
    <option value="CA">California</option>
    <option value="NY">New York</option>
    <option value="TX">Texas</option>
    <option value="WY">Wyoming</option>
  </select>
</div>
```
