### ISSUE TITLE
How to call a function that is in the repository

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3959]
Dear,
I am trying to get the IP of the computer by the hostname, in the form I have registered the hostname, I have a function that I put in the xyzrepository, as I call this function in the dialog.
I created a button in the dialog and did a test to appear an alert and it is OK.
![image](https://user-images.githubusercontent.com/7516443/46150988-39516380-c244-11e8-9a1f-97e0934b99e3.png)
Code that is in xyzdialog
![image](https://user-images.githubusercontent.com/7516443/46151039-51c17e00-c244-11e8-9cb1-08925684590e.png)

Code that is in xyzrepository
![image](https://user-images.githubusercontent.com/7516443/46151159-8b928480-c244-11e8-8e65-4d6e0c7c4bbe.png)

**Comment by minhhungit** [comment]
Move your c# method to Endpoint class (controller), generate t4 template and call it

**Comment by javaman63** [comment]
I have an endpoint called Cars. In this endpoint create a method called SendMail that I want to use from a button in the interface. Similar to the one raised in this issue.

```
        [HttpPost]
        public void SendMail(IUnitOfWork uow, ListRequest request)
        {

            Common.EmailHelper.Send("SUBJECT", "MAIL TEST ", "proof@gmail.com");
        }
```
When I transform the T4, the method does not appear in the CarService.ts file, only this methods appear:

```
        export declare function Create(request: Serenity.SaveRequest<MeetingAgendaRow>, onSuccess?: (response: Serenity.SaveResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function Update(request: Serenity.SaveRequest<MeetingAgendaRow>, onSuccess?: (response: Serenity.SaveResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function Delete(request: Serenity.DeleteRequest, onSuccess?: (response: Serenity.DeleteResponse) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function Retrieve(request: Serenity.RetrieveRequest, onSuccess?: (response: Serenity.RetrieveResponse<MeetingAgendaRow>) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;
        export declare function List(request: Serenity.ListRequest, onSuccess?: (response: Serenity.ListResponse<MeetingAgendaRow>) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;

        export namespace Methods {
            export declare const Create: string;
            export declare const Update: string;
            export declare const Delete: string;
            export declare const Retrieve: string;
            export declare const List: string;
        }
```
What am I doing wrong?

**Comment by minhhungit** [comment]
@javaman63 I am not sure why but this should work for you
```csharp
[HttpPost]
public ServiceResponse SendMail(ServiceRequest request)
{
    //Common.EmailHelper.Send("SUBJECT", "MAIL TEST ", "proof@gmail.com");
    return new ServiceResponse { };
}
```

**Comment by juliermefelix** [comment]
and in my case what would the call in the dialog look like?

**Comment by juliermefelix** [comment]
@minhhungit 
put the function in xyzendpoint
![image](https://user-images.githubusercontent.com/7516443/46165027-eab4c100-c265-11e8-8fcc-64bbafcef87b.png)

how do i call the function now in xydialog
![image](https://user-images.githubusercontent.com/7516443/46165067-07e98f80-c266-11e8-853e-3ab369392e30.png)

**Comment by ga5tan** [comment]
@juliermefelix  in my experience function has to have return some ServiceResult and have some ServiceRequest parameters to get generated to TS. 

check (for example) this function:

```
[HttpPost, JsonFilter, ServiceAuthorize]
        public Result<ServiceResponse> ChangePassword(ChangePasswordRequest request)
```

it gets generated into TS and u can call it from apropriate services

@javaman63 read above, try to pepper it by making return value of some ServiceResult type...
It believe it generator finds function just some auxiliary helper, it'w wont make service method out of it.

**Comment by minhhungit** [comment]
@juliermefelix 
```javascript
CarService.Update({}, response => {
   // do something with response                        
});
```

**Comment by juliermefelix** [comment]
Hi @JohnRanger 
when specified on the line: System.Net.IPHostEntry iphl = System.Net.Dns.GetHostEntry ("EST00800104"); the computer name, I can display the IP
![image](https://user-images.githubusercontent.com/7516443/46207296-42523b80-c2fd-11e8-8002-a7b0ab25775a.png)
![image](https://user-images.githubusercontent.com/7516443/46207314-5007c100-c2fd-11e8-8b57-bd12fd34b04f.png)

But when I put the number in place of the computer name does not work.
![image](https://user-images.githubusercontent.com/7516443/46207356-82192300-c2fd-11e8-8568-e16f3e963b8a.png)

It is not receiving the value of the variable that comes from the dialog.
![image](https://user-images.githubusercontent.com/7516443/46207488-ef2cb880-c2fd-11e8-83d2-9a3d13b62232.png)

in xydialog I put the call to this field like this:
![image](https://user-images.githubusercontent.com/7516443/46207534-1e432a00-c2fe-11e8-99f9-3e6053032190.png)


thank you!

**Comment by juliermefelix** [comment]
@JohnRanger 
I managed to make it work by changing the line below as you had previously indicated, but now the records on the grid are not appearing.
![image](https://user-images.githubusercontent.com/7516443/46225555-01bfe580-c330-11e8-9ad9-ac5ff9129500.png)

![image](https://user-images.githubusercontent.com/7516443/46225588-2025e100-c330-11e8-8f71-2b5582c39731.png)

**Comment by JohnRanger** [comment]
Hi @juliermefelix ,

please create a separate module with only the xyzEndpoint.cs (I am using for this an endpoint which is called "generic" within the "common" module), change the thing to "Controller", modify your client-side call so that it points to the correct service url and then it works.

The trick is that you have to use a separate endpoint of type "controller" for such data transfers and a standard Serenity Endpoint for the data feeds for grid and dialog.

At least that's how I use it in many projects as I didn't find a way to combine both within one xyzEndpoint.cs.

Why that Serenity's ServiceEndpoint is so completely different from a standard MVC controller - I don't know.

Hope this helps.

with kind regards,

John

**Comment by JohnRanger** [comment]
Hi @juliermefelix ,

in the meantime, I have created a Wiki article which describes everything in more details. 

See here: https://github.com/volkanceylan/Serenity/wiki/BBB:-On-client-side,-fetching-a-value-from-server-side-out-of-database

With kind regards,

John

**Comment by juliermefelix** [comment]
thank you, after the wiki I got solved.

**Comment by juliermefelix** [comment]
Dear, the first scenario was solved at the moment of the registration of the computer it searches the ip and records in the bank.
The second scenario now: I already had the registered computers now I need to select the line and when I click the "IP" button it searches the IP and saves it in the table.
![image](https://user-images.githubusercontent.com/7516443/46283290-648cc900-c54a-11e8-9f76-3085fe605952.png)
How do I pass the value of the "ComputerName" field of the selected line.

**Comment by ga5tan** [comment]
I would just go to edit dialog of entity search and assign there.
anyways, if u wanna do multiselect, check grid selection mixin for sample how to get IDs of selected rows...

**Comment by juliermefelix** [comment]
Dear @minhhungit 
I've followed your wiki, and there return the ID I'm trying to return not the IdField but the NameField, but it's giving this error: var id = item [this.NameField] .toString ();
how to solve?

wiki
https://github.com/volkanceylan/Serenity/wiki/Grid-Radio-Row-Selection-Mixin

**Comment by juliermefelix** [comment]
OK. Thanks

**Comment by haajit** [comment]
> Hi @juliermefelix ,
> 
> in the meantime, I have created a Wiki article which describes everything in more detail.
> 
> See here: https://github.com/volkanceylan/Serenity/wiki/BBB:-On-client-side,-fetching-a-value-from-server-side-out-of-database
> 
> With kind regards,
> 
> John

Hi
Why can't i see this wiki?

**Comment by VictorTomaili** [comment]
just search it in wiki, the path is changed. 
https://github.com/serenity-is/Serenity/wiki/%5BBBB%5D-On-client-side-fetching-a-value-from-server-side-out-of-database
