### ISSUE TITLE
Filters on Detail editor appear, don't do anything

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#396]
Trying to add filters on the Detail grid on the Master dialog. So in MyDetailEditor, I add 
`
using Fields = MyDetailRow.Fields;
{...}
protected override void CreateToolbarExtensions()
        {
            base.CreateToolbarExtensions();
AddDateRangeFilter(Fields.InsertDate);
        }`

Excellent, the filter shows up, am able to select the date range. But nothing happens. No network communication, no javascript errors, no database queries. Seems like for whatever reason it isn't getting wired up. 

Same code works fine when used on MyDetailGrid

Any thoughts?

**Comment by volkanceylan** [comment]
Filtering works on server side, so it won't work with in memory grids

**Comment by wldkrd1** [comment]
Ahh...well drat. Ok, I'll figure something else out. Thanks!

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/issues/3792 ;)
