### ISSUE TITLE
Filter app wide based on tenant

### ISSUE THREAD

**Issue by jgranade** [volkanceylan/Serenity#3960]
I'm trying to filter my results based on the selected tenant/client.  This means that in my layout I've added a  select drop-down that lists all the clients...when it's selected...that applies the filter to the repository.  We're shown with the multi-tenancy demo how to do ApplyFilters but I'm struggling with the best way to get that jquery selection back to the repository.cs code so I can filter on it.

Right now I'm doing it via cookie but that just seems wrong.  Session storage gets challenging going from jquery back to my C# model.  In the past I've used ViewBag/ViewData but then I'd pass that result as a parameter to my model functions but I don't want to change all those methods from the base Serenity code.  I think this is easy but I'm struggling to figure it out so I thought I'd ask for guidance.

If I want to have a "tenant selector" that's part of the navigation that allows you to filter based on that selection, what's the best way?  

Thanks,

John

**Comment by ga5tan** [comment]
my guess: just stick it to UserDefinition...
