### ISSUE TITLE
Custom lookupfilter; complex SQL query; how to do it

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3961]
Hi all,

I have a table which contains layouts (Jasper reports layouts). Within this table, there are different layouts (e.g. CoverLetter, Contract, etc) and also multiple versions of the same layout. Different layouts distinguish themself by a different key (guid). 

Same Layouts but different versions have the same key but different version numbers.

e.g.:

```
ID:       Name:                         Key:                          Version:
  1       CoverLetter                   <guid1>                       1.00.00
  2       Contract                      <guid2>                       1.00.00
  3       CoverLetter                   <guid1>                       1.00.01
```

**Goal**

I want to make a quickfilter which normally only shows the highest version of each Layout "type" (e.g. the record with the highest version of each different key).

In the above example, this would result in the following records:

```
ID:       Name:                         Key:                          Version:
  2       Contract                      <guid2>                       1.00.00
  3       CoverLetter                   <guid1>                       1.00.01
```

The sql statement for this is quite complex:

```sql
( SELECT
  TACMasterlayouts.*
FROM
  (SELECT
     TACMasterLayoutKey, MAX(TACMasterLayoutVersion) as TACMasterLayoutVersion
   FROM
     TACMasterlayouts
   GROUP BY
     TACMasterLayoutKey) AS latest_TACMasterLayouts
INNER JOIN
  TACMasterlayouts
ON
  TACMasterlayouts.TACMasterLayoutKey = latest_TACMasterLayouts.TACMasterLayoutKey AND
  TACMasterlayouts.TACMasterLayoutVersion = latest_TACMasterLayouts.TACMasterLayoutVersion
  ) 
```

This SQL statement produces the correct result - but how to apply it within quickfilters so that this can be toggled on or off (e.g. show all layout types with all versions or only the newest of each layout type).

Also additional quick filtering and sorting should still be possible.

**Questions:** 
(1) Is this at all possible with Serenity?
(2) If (1) = yes: Are quickfilters the correct way to do it?
(3) if (2) = yes: How to do it?
(4) if (2) = no: How could this be otherwise done?

**Hint:**
I have already studied the examples for custom quickfiltering within the serene demo app. But these examples filter directly on one or two columns. So there is no similar case like the one I want to use.

Any help is greatly appreciated.

With kind regards,

John

**Comment by ga5tan** [comment]
just feed the quickie from your view

**Comment by JohnRanger** [comment]
Hi @ga5tan ,

I know - I could make a view and create a 2nd grid and Dialog - and then tell the people to either use one or the other - but that's not user and also not programmer friendly because it would cause me to create double code for the same logical thing.

I also don't think that I can use a stored procedure which returns either the filtered or the full recordset as I don't know how to send a parameter ("full" or "filtered") from the client to the backend at the time when the queries within the grid fire.

If I could do that, then I would solve it on the SQL backend side.

Any hint, how to do this?

The goal should be to be able to dynamically "filter" the records according to the SQL query given above. 

With kind regards,

John

**Comment by minhhungit** [comment]
I am not sure what you want to do, I guess you want to filter grid by a custom filter, then this is what I will do:

First, create a quick filter like this:
```javascript
this.addQuickFilter({
    field: fld.Id,
    type: Serenity.LookupEditor,
    options: {
        lookupKey: "YOUR_LOOKUP_KEY"
    }
});
```
Last thing is create a custom lookup:

```csharp
[LookupScript("THIS_IS_YOUR_LOOKUP_KEY", Expiration = -1, Permission = "*")]
public class DemoLookup : Serenity.Web.LookupScript
{
    public DemoLookup()
    {
        this.IdField = "Something";
        this.TextField = "Something to display";
        this.getItems = this.GetItems;
    }

    protected virtual IEnumerable<dynamic> GetItems()
    {
        // return your result here
    }
}
```

**Comment by JohnRanger** [comment]
Hi @minhhungit ,
thanks for your valuable feedback.

I want to filter the grid by a custom query when the filter is active.

E.G. The filter should be a checkbox which is either checked or not checked.

But in your example - if I understand it correctly - this will only filter the values returned within the Quickfilter dropdown.

But that is not what I want. 

The quickfilter's visible representation should only be a booleanEditor, and if checked, this should then filter the records within the grid by my custom SQL query in addition to potentially other set quickfilters.

The problem which I see with quickfilters is that they seem to be always bound to a field within the row which is represented within the grid. But this will not work in my case.

Or did I completely missunderstand your info above?

With kind regards,

John

**Comment by minhhungit** [comment]
how many checkbox you want to show, one or many

**Comment by minhhungit** [comment]
anyway, I think lookup type with multiple is okay:

```javascript
getQuickFilters(): any {
    var filters = super.getQuickFilters();

    filters.push({
        field: fld.Id,
        type: Serenity.LookupEditor,
        title: "Test Title",
        options: {
             lookupKey: "YOUR_LOOKUP_KEY_HERE",
             multiple: true
        }
    });

    return filters;
}
```

You just need to choose a Field (column) to filter and create a lookup key which will return list filter items for that Field (column)


![image](https://user-images.githubusercontent.com/2279508/46204010-d9db7c80-c345-11e8-8060-ffa61e048a76.png)

**Comment by JohnRanger** [comment]
Hi all,

as a reference for all how to do this:

Do it on the SQL server backend side and use a calculated field which is either true (when the record is the highest version of a layout type - or false if it is not - and then use a normal Quickfilter tag within xyzRows.cs on the calculated field.

The below SQL query produces an additional (calculated / "virtual") boolean (bit) field named: isHighestVersion.

the SQL view query looks like that:

```sql
SELECT        CASE WHEN latest_TACMasterLayouts.TACMasterLayoutKey IS NOT NULL THEN 1 ELSE 0 END AS isHighestVersion, TACMasterLayouts_1.*
FROM            (SELECT        TACMasterLayoutKey, MAX(TACMasterLayoutVersion) AS TACMasterLayoutVersion
                          FROM            dbo.TACMasterLayouts
                          GROUP BY TACMasterLayoutKey) AS latest_TACMasterLayouts RIGHT OUTER JOIN
                         dbo.TACMasterLayouts AS TACMasterLayouts_1 ON TACMasterLayouts_1.TACMasterLayoutKey = latest_TACMasterLayouts.TACMasterLayoutKey AND 
                         TACMasterLayouts_1.TACMasterLayoutVersion = latest_TACMasterLayouts.TACMasterLayoutVersion
)
```

hope this helps somebody.

with kind regards,

John

**Comment by JohnRanger** [comment]
@minhhungit ,
thanks for your continuous support. I appreciate it.

With kind regards,

John

**Comment by minhhungit** [comment]
In **Grid.ts** :
```javascript
private isHighestVersionFilter: Serenity.QuickFilter<Serenity.SelectEditor, Serenity.SelectEditorOptions>;

constructor(container: JQuery) {
    super(container);

    this.isHighestVersionFilter = {
        type: Serenity.SelectEditor,
        title: "Is Highest Version",
        options: {
            items: ["yes", "no"]
        },
        handler: h => {
            var request = (h.request as CustomGridListRequest);
            var value = (h.widget as Serenity.SelectEditor).value;

            if (Q.trimToNull(value) !== null) {
                request.IsHighestVersion = value == "yes" ? true : false;
                h.active = true;
            }
            else {
                h.active = false;
            }

            h.handled = true;
        }
    };

    this.addQuickFilter(this.isHighestVersionFilter);
}
```
In **Endpoint.cs**, change **ListRequest** parameter of List() method to **MyCustomListRequest**:

```csharp
[HttpPost]
public ListResponse<MyRow> List(IDbConnection connection, MyCustomListRequest request)
{
    return new MyRepository().List(connection, request);
}

public class MyCustomListRequest: ListRequest
{
    public bool IsHighestVersion { get; set; }
}
```

In **Repository.cs**, change **ListRequest**  parameter of List() method to **MyCustomListRequest** like:
```csharp
public ListResponse<MyRow> List(IDbConnection connection, MyCustomListRequest request)
{
    return new MyListHandler().Process(connection, request);
}
```

and 
```csharp
private class MyListHandler : ListRequestHandler<MyRow> {
    protected override void ApplyFilters(SqlQuery query)
    {
        base.ApplyFilters(query);
        var request = Request as MyCustomListRequest;
        if (request != null)
        {
            if (request.IsHighestVersion == true)
            {
                // do query here, like bellow:
                // query.Where(fld.Something== 17);
            }
        }                
    }
}
```

**Comment by JohnRanger** [comment]
Thank you @minhhungit! Looks great :-). 

Although I have now handled it fully within the SQL Backend, I will try your version also as it could possibly avoid me to have to handle Insert, update and delete on SQL view with instead of xxx triggers.

I just do not yet know how to construct the neccessary query in the notation above as it is already a complex T-SQL query itself.

With kind regards,

John
