### ISSUE TITLE
Editor Hk.

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#3963]
Oluşturdugumuz  editor  ( LookupEditorBase türemektedir). Bunu girdte  cağırıp tekrar yükletmek istiyorum.Çünkü  Gridte  quickfilterda filtrelenmemiş  olarak gelmektedir.

Kolay gelsin
---------------
We create editor (LookupEditorBase is derived). I want to call this input and reboot. Because the Gridte comes with unfiltered quickfilter.
Good luck with

**Comment by ga5tan** [comment]
there is sample in Serene, where you can replace quickfilter with your control. check it out
