### ISSUE TITLE
How to pass value from search box to load data in grid?

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#3967]
Hi All,
   I'm not very familiar in type script, what i want to do is when i open the
link of students records there's no data will show until they will input there Student Number in
the search box and trigger the loading of data using the Search Button.
Any possible solution is very much appreciated. thanks!

see screenshot..
![screenstud](https://user-images.githubusercontent.com/22849322/46256936-78054900-c4e4-11e8-9d4f-9aef67df3f1c.JPG)

**Comment by alex-444** [comment]
Ok.. i tried to set a default value if i can load the data to grid.
and it works, my problem is how to trigger it using the search button and reload/refresh the grid.
this is the code i put.

I put this in StudentGrid.ts

protected onViewSubmit() {
            if (!super.onViewSubmit()) {
                return false;
            }
            var request = this.view.params as Serenity.ListRequest;
            request.Criteria = Serenity.Criteria.and(request.Criteria, [['StudNo'], '=',
            $('#StudentNo').val()]);
            return true;
        }

I put this in StudentsIndex.cshtml

div class="box">
    <div class="box-body">
        <div class="input-group margin">

            @Html.TextBox("StudentNo", "S1218-0005", new { @class = "form-control", @placeholder = "Enter Student No" })
            <span class="input-group-btn">
                <button type="button" class="btn btn-info btn-primary" id="btnSearch"><strong>SEARCH</strong></button>
            </span>
        </div>
    </div>
</div>
`

**Comment by alex-444** [comment]
Hi @volkanceylan!
i hope you can help me with this, any possible solution or
not exactly the same with my sample above. thanks!

**Comment by volkanceylan** [comment]
You should return false from onViewSubmit or getGridCanLoad while the student no is empty

**Comment by alex-444** [comment]
Thanks @volkanceylan ! I'm quite busy for other projects that i forgot to close this issue.

I changed the condition above and just use the builtin search box.

 I need to study javascript/typescript to better understand serenity, i'm more on back end side. :)
I'm getting to love this serenity platform, i hope more updates are coming and
thanks for this awesome platform that makes my work very easy, i can focus more in business side.

here is the code i used, the same above i just change the parameter.

`  protected onViewSubmit(): boolean {
            if (!super.onViewSubmit()) {
                return false;
            }
            let request = this.view.params as Serenity.ListRequest;
            request.Criteria = Serenity.Criteria.and(request.Criteria, [[fld.StudNo], '=', request.ContainsText]);
            return true;
        }`
