### ISSUE TITLE
Master detail relations details doesnt show all columns

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#3968]
I embedded master detail relation in my ServiceRow as below

```
 [DisplayName("Details"), MasterDetailRelation(foreignKey: "ServiceId", MasterKeyField = "Id"), NotMapped]
        public List<ServiceItemsRow> SerServiceItems
        {
            get { return Fields.SerServiceItems[this]; }
            set { Fields.SerServiceItems[this] = value; }
        }
```

In a details  section of ServiceRow form it shows all direct column of ServiceItems row, but not a derived columns (View field / columns from other tables linked with foreign key)

Based on belwo three columns in ServiceRow
```
  [DisplayName("Seq No"), NotNull]
        public Int32? SeqNo
        {
            get { return Fields.SeqNo[this]; }
            set { Fields.SeqNo[this] = value; }
        }


        [DisplayName("Service"), NotNull, ForeignKey("[dbo].[Service]", "Id"), LeftJoin("jService"), TextualField("ServiceName")]
        public Int32? ServiceId
        {
            get { return Fields.ServiceId[this]; }
            set { Fields.ServiceId[this] = value; }
        }

        [DisplayName("Service Name"), Expression("jService.[ServiceName]")]
        public String ServiceName
        {
            get { return Fields.ServiceName[this]; }
            set { Fields.ServiceName[this] = value; }
        }
```

It Shows SeqNo, ServiceId, But it shows blank in Service Name
Its not a column present in ServiceItems Table, rather Its View Field based on foreign key linking (i.e based on service ID)
![image](https://user-images.githubusercontent.com/4771536/46273855-4df56a80-c568-11e8-8f8c-a46117621651.png)

**Comment by dfaruque** [comment]
put` [MinSelectLevel(SelectLevel.List)]` on ServiceName field in Row.cs

**Comment by volkanceylan** [comment]
Read the guide

**Comment by c9482** [comment]
Also helpful: https://serenity.is/docs/tutorials/movies/the_cast_and_characters_they_played (Resolving Empty Actor/Actress Column Problem).
