### ISSUE TITLE
Login Persist (keep me logged in)

### ISSUE THREAD

**Issue by mafdy** [volkanceylan/Serenity#3969]
Hi all,

I'm trying to active Persist function for logged in users. basically, keep them logged in if they checked the box before they log in. I managed everything from creating the checkbox to login panel and pass the value on login request, and so on (I can write the HowTo after getting it works). 
But **it's just didn't works**.

![image](https://user-images.githubusercontent.com/30433229/46311840-af96f280-c5c3-11e8-9311-6e0be432af57.png)

I noticed that Serenity used WebSecurityHelper.Authenticate(....) as Authenticate helper, instead of HttpContext.Authentication(....). But as it a metadata I can't figure out what is going behind.

Package: AspNetCore. 
Version: 3.7.7

So, does anyone manages this part to work?

**Thanks for any feedback,**

with kind regards,
Mafdy.

**Comment by ga5tan** [comment]
This may be the source of WebSecurityHelper:

https://github.com/volkanceylan/Serenity/blob/48b7a2135311123f6876b45a553b77b3e8833315/Serenity.Web/Security/WebSecurityHelper.cs

**Comment by mafdy** [comment]
Aha, 
Firstly, **thank you dear, @ga5tan for your help.**
I see where's the problem.
```
/// <param name="persist">
///   is persistent authentication tikcet? (remember me, we don't use this for reasons considering with security)
/// </param>
```
So, it's clear that this function isn't  supported. in Serenity.
Unfortunately, this feature highly needs on the current project (Which is an Academic app for a non-profitable organization) 

Dear @volkanceylan or all of the community developers, Is there any workaround I can use to handle this issue?

**Thanks for any feedback,**

with kind regards,
Mafdy.

**Comment by mafdy** [comment]
Thank you @volkanceylan for your comment.
unfortunately, I Already did that, as you can see Inside AccountPage class, on Login method its was send false value by default to persist parameter.

```
[HttpPost, JsonFilter]
public Result<ServiceResponse> Login(LoginRequest request)
{
    return this.ExecuteMethod(() =>
    {
        request.CheckNotNull();

        if (string.IsNullOrEmpty(request.Username))
            throw new ArgumentNullException("username");

        var username = request.Username;
        if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
            return new ServiceResponse();

        throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);
    });
}
```
 So, I changed it to true but with no luck. Just nothing happened. By another word, User Authentication Ticket didn't persistent.

Thanks for your time,
with kind regards,
Mafdy.

**Comment by volkanceylan** [comment]
It just calls standard asp.net function to set persistent cookie. If you set it true and it didnt work, then research how it works in basic asp.net app. Serenity doesnt care about who or how auth ticket is created, so you dont have to use websecurityhelper.

**Comment by mafdy** [comment]
That's what I was waiting to hear from you  @volkanceylan "I don't have to use websecurityhelper".

Just want to make something clear, I didn't write the issue before 4 days of research.
I didn't know that will bother you like that. There was no need to embarrass me this way. Anyway, sorry about that. I was intending to close the issue today.

I will only add a chat module build above Serenity by SignalR and dynamic report as Grid gets its data from SP as soon as I finish them. As that I do not want to feel guilty from using your template. And this will be my last issue. that's all.

Thanks,
with kind regards,
Mafdy.

**Comment by volkanceylan** [comment]
I said nothing to embarrass you, you don't have to use WebSecurityHelper, because it just calls usual FormsAuthenticationTicket methods, so you can look at ASP.NET samples and make it work. Anyway if it is embarrassing you i have nothing to say, good luck.
