### ISSUE TITLE
Authorization has been denied for this request! Error When we load data based on user and it's roles.

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#397]
I have added multiple institutes (CA, Law, Medical etc) and one user (eg. xyz@gmail.com) that has role "Institute Admin". I assigned one institute (CA) to this user (eg. xyz@gmail.com). I login with "Institute Admin" role user (eg. xyz@gmail.com) and goto Institutes menu, I want to display and edit only that assigned institute (CA). I have implemented this by using MyListHandler class, it's working fine but it can't be open popup for click on grid linkbutton column and New Institute button. My code is as below -

InstituteRepository.cs file -

private class MyListHandler : ListRequestHandler<MyRow> 
{
            protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);
                if (Authorization.UserId != "1")
                {
                    query.Where(fld.UserId == Authorization.UserId);
                }
            }
}

**Comment by volkanceylan** [comment]
Check lookups you use and their permissions. In console you'll see which one has error.

**Comment by laxmanp** [comment]
Uncaught Can't load script data: Lookup.Administration.User!

**Comment by laxmanp** [comment]
[ConnectionKey("Default"), DisplayName("Users"), InstanceName("User"), TwoLevelCached]
    [ReadPermission(Administration.PermissionKeys.Security)]
    [ModifyPermission(Administration.PermissionKeys.Security)]
    [LookupScript("Administration.User")]
    public sealed class UserRow : LoggingRow, IIdRow, INameRow
    {
    
}

**Comment by volkanceylan** [comment]
[LookupScript("Administration.User", permission: "?")]

If you want authorized users to access user list lookup

**Comment by laxmanp** [comment]
Hello sir i set permission: "Institute Admin" but it throws error
'Serenity.ComponentModel.LookupScriptAttribute' does not contain a constructor that takes 2 arguments

**Comment by volkanceylan** [comment]
[LookupScript("Administration.User", Permission = "?")]
