### ISSUE TITLE
Passing Data to Endpoint aside from Keys

### ISSUE THREAD

**Issue by glenngsanchez** [volkanceylan/Serenity#3972]
Hi All, 

I'm so new to this, so please bear with me. how can I pass data from my vusercontactsbulkaction.ts  to the endpoint vusercontactEndpoint.cs?  

I would like to add not only keys, but also another Id that I'm planning to associate with.

**vusercontactsbulkactions.ts**
![image](https://user-images.githubusercontent.com/23032787/46341224-2edf0180-c66a-11e8-8e5f-f2046c175b3c.png)

**vusercontactsendpoint.cs**
![image](https://user-images.githubusercontent.com/23032787/46341101-f2130a80-c669-11e8-920b-3ca72f0259e8.png)

Please let me know if you need more details regarding this question.

**Comment by ga5tan** [comment]
extend Request then with other parameters u need to pass.
sample:


```
public class GenerateReportsRequest : ServiceRequest
    {
        //this is the list of IDs already in there
        public List<int> rowsIDs { get; set; }
       //additional parameters passed
        public bool chkIndividualReport { get; set; }
        public bool chkGroupReport { get; set; }

        public string rblPreparedFor { get; set; }
        public string rblSendEmails { get; set; }
        public string rblIndividualIntro { get; set; }

        public string sGetPreparedBy { get; set; }

        public string txtPreparedFor { get; set; }
        public string txtPreparedForGroupID { get; set; }
        public string txtPreparedForDate { get; set; }        
    }
```

**Comment by glenngsanchez** [comment]
Thanks @ga5tan! I have actually done this previously, but did not notice the error was referring to **number** is not assignable to **Number** .  Thank you for the code, it forced me to revisit that and fixed my issue now.

Thanks!
