### ISSUE TITLE
Navigation menu sequence

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3975]
Hello @volkanceylan,
I want to change the sequence of navigation menu
![tempsnip](https://user-images.githubusercontent.com/39983941/46393879-a6616f00-c704-11e8-9849-5c61fca2e539.png)
It would be great if you help with this

**Comment by brunobola** [comment]
Change in the xxxnavigation.cs

[assembly: NavigationMenu(1001, "First")]
[assembly: NavigationMenu(1002, "Second")]
...

**Comment by Shraddha996** [comment]
Thank you @brunobola 
But as you can see there are 10 modules and I want to rearrange those modules
Ex. in above list Master should be at first position 

I know those modules are arranged by alphabetical order but Is this possible in serenity to change the order of menu links

**Comment by mafdy** [comment]
@Shraddha996  Every module has its own xxxNavigation class. just arrange them whatever you want, and they will be arranged.

How to arrange?
```
[assembly: NavigationLink(1000, "Dashboard", url: "~/", permission: "", icon: "fa-tachometer")]
```
As you can see, NavigationLink expects some parameters, the first one is order param as an int. give it a value depends on their position on the menu list. the numbers range are created by you.
that's all, 

By the way, can I suggest you a small thing?
 on your next issue, just ask the community, **Not Volkanceylan** directly, I'm sure he's very busy on updating our beloved platform "Serenity".  unless it's something which touchs the core of Serenity.

Hope this help.
with kind regards,
Mafdy.

**Comment by Shraddha996** [comment]
@mafdy thank you so much! I will take care of that
