### ISSUE TITLE
How to add / remove a grid column only in the extended dialog grid?

### ISSUE THREAD

**Issue by controllernet** [volkanceylan/Serenity#3981]
I have an extended grid screen of a standard GRID of Serenity.

I would like to add / hide new columns only on the extended screen.

![image](https://user-images.githubusercontent.com/39500865/46482329-61e8d880-c7c3-11e8-8fd6-9261c929c1b8.png)

**Comment by ga5tan** [comment]
well u either make two Column files, or you add all the fields into parent's Columns.cs, and hide them in parent's Grid.ts

**Comment by volkanceylan** [comment]
getColumns() {
   return super.getColumns().filter(x => x.field != "SomeField")
}

**Comment by controllernet** [comment]
Obrigado @volkanceylan , worked properly.
