### ISSUE TITLE
Get the ID of the Parent Dialog and fill in the child dialog

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3983]
Dear,
I have a dialog with a masterdetails, I created a button in to open the "Child" dialog, but I am not able to get the ID of the "PAI" dialog and feed the field.
I did a test by creating the button in the dialog "Father" in this case I was able to get the ID and go to the dialog "Child

Example: click on the button in the dialog "PAI"
![image](https://user-images.githubusercontent.com/7516443/46494898-68d71180-c7ea-11e8-80af-de737c1bdae2.png)
Looking at the code I'm passing the "enityId"
![image](https://user-images.githubusercontent.com/7516443/46494991-9cb23700-c7ea-11e8-9b25-be76a484bde7.png)

Now clicking on the custom button of masterdetails I can not pass this entityID paramenter or another that can retrieve the ID of the parent.
![image](https://user-images.githubusercontent.com/7516443/46495087-e3a02c80-c7ea-11e8-8492-633b200ccd31.png)

**Comment by hairangsua** [comment]
This insert button place on Detail Editor so you need make some property to pass Entity Id to Detail editor and load it

**Comment by juliermefelix** [comment]
See the image2 that the button is in the Details and since it does not have the ID, that's what I need to know how to get the ID and work with it.

Thank you!

**Comment by juliermefelix** [comment]
Dear @hairangsua 
I solved using the following tutorial:
https://serenity.is/docs/tutorials/movies/the_cast_and_characters_they_played

**Comment by stixoffire** [comment]
@juliermefelix I wish you had posted the exact solution to your issue. as sometimes people are reading the guide but miss something and a quick post of this is where my code needed fixed ..
