### ISSUE TITLE
Handle Session expiry exception

### ISSUE THREAD

**Issue by kanadmehta** [volkanceylan/Serenity#3985]
Where can I handle Session expiry exception?
Just want to show a proper message and redirect the user to the login page.

Currently below message is shown.
![image](https://user-images.githubusercontent.com/19486929/46532452-78278f00-c8be-11e8-987e-7c29fd8680df.png)

**Comment by JohnRanger** [comment]
Session expiration is a long - sad - story in Serenity Framework. This also goes for ajax calls when the session is expired.

This is just not yet intuitively and user friendly handled. But if you find a way to optimize this - please share your solution here :-)

With kind regards,

John

**Comment by mjacoup** [comment]
any updates for this issue ?

**Comment by mjacoup** [comment]
any updates
