### ISSUE TITLE
In Grid how do I make an attribute formula only on the client side?

### ISSUE THREAD

**Issue by controllernet** [volkanceylan/Serenity#3986]
I need to create the Total field that is the formula Balance + Interest - Discounts.

These two fields: Interest and Discount are NotMapped fields in row.

![exemplo_formula_tela_baixa_expressa](https://user-images.githubusercontent.com/39500865/46560117-85de1400-c8c0-11e8-8d27-80699d75ffa3.png)

**Comment by JohnRanger** [comment]
Hi @controllernet ,

although my answer is not the answer how to do grid calculations only on client-side, it is an answer to your current problem :-).

-------

Why don't you do this within the database backend with calculated fields?

E.G. create a SQL view of your table and add calculated/virtual fields for Juros and Desconto and then map them within xyzRow.cs

So you shift the "heavy" work of calculating Juros and Descento to the DB backend and you can use these calculated fields within SF as you would do any other "real" field.

With kind regards,

John

**Comment by volkanceylan** [comment]
You should simply write a formatter function for that column
