### ISSUE TITLE
ADFS Autnetication

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#3987]
How can i enable ADFS Authentciation to serenity?
Anybody has done this? Can some one assist if its explored by you already?
Thanks in Advance.

**Comment by JohnRanger** [comment]
Hi @jabirmoolur ,

I never have done this with SF, but as it is an ASP.net MVC app, maybe this article can help you further?

https://developers.de/blogs/armin_kalajdzija/archive/2016/10/06/how-to-implement-web-sign-on-with-adfs-in-asp-net-mvc-using-owin.aspx

With kind regards,

John
