### ISSUE TITLE
FileUpload; path not rendered correctly when mapping with HttpContext.Current.Server.MapPath

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#3988]
Hi all,

this is with SF 2.9.24 (I am still on that version :-)).

I have observed that when using the fileupload solution within SF, the relative path returned seems to be wrong.

E.g. when I am calling a service within the Module /TACMasterLayouts/TacMasterLayouts this returns something like this: ```D:\<project root>\services\TACMasterLayouts\TacMasterLayouts\Temporary\xyzabcd123.<fileExtension>```

whereas the correct path would be something like: ```D:\<project root>\App_Data\Upload\Temporary\xyzabcd123.<fileExtension>```.

Currently I am working around this by replacing part of the path like this:
```cs
            var PathPartToRemove = ManageSettings.GetSettingValue("PathPartToRemove");
            var PathPartToAdd = ManageSettings.GetSettingValue("PathPartToAdd");

            return HttpContext.Current.Server.MapPath(RelativePath).Replace(PathPartToRemove, PathPartToAdd);
```

where 
 PathToRemove = \services\TACMasterLayouts\TacMasterLayouts\
 PathPartToAdd = \App_Data\upload\

Does anybody of you observe the same thing - and if yes, is there any better solution?

Thanks for your feedback and

With kind regards,

John

**Comment by volkanceylan** [comment]
Relative path is not a web relative path. Use methods of upload helper to get folder of a file.
