### ISSUE TITLE
Problem with Report Generator

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#399]
Hi,

After an update last week, two errors appeared that I haven't been able to solve.
It relates to IDataOnlyReport

Error 1: CS0738 in **DynamicDataReport.cs** (Line 12)

> 'DynamicDataReport' does not implement interface member 'IReport.GetData()'. 'DynamicDataReport.GetData()' cannot implement 'IReport.GetData()' because it does not have the matching return type of 'object'.

Error 2: CS1579 in **ReportRepository.cs** (Line 13)

> foreach statement cannot operate on variables of type 'object' because 'object' does not contain a public definition for 'GetEnumerator'

These are the only errors in the project but they are preventing me from publishing the solution.

I hope this is a minor issue and that the community can help me resolve this quick and easy.

Thanks in advance.

Kind regards,
Birgir

**Comment by volkanceylan** [comment]
Please check change log, search for ReportRepository
