### ISSUE TITLE
Cascade issue

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#3993]
I wated to add direct cascade as described in 
https://volkanceylan.gitbooks.io/serenity-guide/howto/how_to_setup_cascaded_editors.html

But cascade works in forms not in Grid.
When i tried to follw eg I cannot find CustomerGrid.cs only i can see text script file with name Customergrid.ts,

**Comment by volkanceylan** [comment]
Yes cascade works in forms

**Comment by jabirmoolur** [comment]
@volkanceylan Thanks
yes it works in forms but not in GridEditor
