### ISSUE TITLE
The controller will report errors asynchronously.

### ISSUE THREAD

**Issue by cluyun** [volkanceylan/Serenity#3997]
error Tips：”The asynchronous action method '***' returns a Task, which cannot be executed synchronously.”

How to solve this problem?
I want to use asynchronous methods.
（Machine Translation，I can't speak English）

`[HttpPost]
        public async Task<DtoSerenity> ****(SerenityRequest request)
        {
            return await ***();
        }`

**Comment by volkanceylan** [comment]
This is not a Serenity issue.
