### ISSUE TITLE
MasterDetailRelation with ID of another table

### ISSUE THREAD

**Issue by antoniojp** [volkanceylan/Serenity#3999]
Hi!

I have a structure of tables for **Customers**, **People** and **People's Addresses**. I've already mapped in Serenity, but I need register in a **one single form**, as below:
![masterdetailrelation](https://user-images.githubusercontent.com/1028501/46810341-d9c87d00-cd46-11e8-91f6-14ba7506217f.png)

Everything is working, but the problem is in the **addresses**, because `[MasterDetailRelation("IDDetail")]` writes the **Customers IDRow** (table master), and I wanted it to bind to the **People IDRow**.

Could someone guide me how to do this in the Serenity?

**Comment by hannesb** [comment]
Maybe MasterKeyField of MasterDetailRelation is what you need.

**Comment by antoniojp** [comment]
Thanks, @hannesb !

I upgraded my version of Serenity to 3.7.7.0 and used the **MasterKeyField** attribute, created by you at issue #3272, and was resolved.
