### ISSUE TITLE
Question on PDFS and links

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#400]
First off: love the platform.

So I'm working on creating a document management site but I was wondering something. How can I add a pdf to a record and have it where a user can click on it and it either A) opens in a new tab, or B) pops up to where they can view the PDFs pages or page.

Also is there a way to add a static href link to the platform? Say I want a link that goes to google.com somewhere, is this possible? 

Thanks again for your work on the platform!

**Comment by jsbUSMC** [comment]
Where would you want to place the link?

**Comment by volkanceylan** [comment]
If you want to place link in navigation, its already possible with Url parameter of navigation links. Otherwise you could put them in Page.cshtml files anywhere you like. Or append to grid.Toolbar.

UrlFormatter is possibly what you are looking for PDF links.

**Comment by wdhodges** [comment]
Awesome. I'll look into putting it on the page.cshtml, but will the PDFs be
stored in the database like the images of Keanna Reaves are stored in your
Movie dB tutorial?

**Comment by wdhodges** [comment]
I used the url: paramater but it error-ed due to not https://www.google.com is not a relative virtual path. How can I get to external sites?

**Comment by volkanceylan** [comment]
Try this code in your NavigationModel.cs:

```cs
        public NavigationModel()
        {
            Items = TwoLevelCache.GetLocalStoreOnly("LeftNavigationModel:NavigationItems:" + (Authorization.UserId ?? "-1"), TimeSpan.Zero,
                UserPermissionRow.Fields.GenerationKey, () =>
                    NavigationHelper.GetNavigationItems(x => 
                        x != null && x.StartsWith("~/") ? VirtualPathUtility.ToAbsolute(x) : x));

            SetActivePath();
        }
```

**Comment by wdhodges** [comment]
Sweet, I'll give it a go and report my findings.

**Comment by wdhodges** [comment]
That works!!
