### ISSUE TITLE
List of Default Values In New Dialog detail list

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4002]
I am following https://serenity.is/demo/BasicSamples/DefaultValuesInNewDialog example,
But i wanted to add multiple items in details list rather than single item as hown in eg

below is my modified code.

unfortunately it display or load all column values in detail grid (As shown in screenshot below )

![image](https://user-images.githubusercontent.com/4771536/46914087-ba7d5a00-cfa9-11e8-9608-79abf9ba9dc1.png)

i also added [MinSelectLevel(SelectLevel.Always)] to all required columns in ActivityMasterRow

```
 buttons.push({
                title: 'Create New Yoyage', cssClass: 'add-note-button',
                onClick: () => {
               
                    var dlg = new Default.VoyageDialog();

                   
                    this.initDialog(dlg);

                   
                    var activity_masters = Default.ActivityMasterRow.getLookup().items
                        .filter(x => x.Id >0);                 

               

                    dlg.loadEntityAndOpenDialog(<Default.VoyageRow>{
                        BUCode: 'FSTGT',
                        ServiceId: 2,
                        VoyageTimestamps: activity_masters
                    });
                }
            });
```

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/46932547-e9063e00-d058-11e8-8299-84f49380e098.png)
You need to create a list with all the columns.

![image](https://user-images.githubusercontent.com/26430136/46932673-6f228480-d059-11e8-84d7-8f8653d12eba.png)

**Comment by Zahar661** [comment]
And add LookupInclude

**Comment by brunobola** [comment]
One way is to use the validateEntity to competent what you want after selected...
