### ISSUE TITLE
Grouping Implementation makes Excel export invisible

### ISSUE THREAD

**Issue by dsCloud** [volkanceylan/Serenity#4003]
Great Volkan,

Please help, when grouping is implemented, the excel export becomes invisible.

Kindly assist.

Regards,

**Comment by brunobola** [comment]
Can you give more details for people to help you.

**Comment by dsCloud** [comment]
Thanks @brunobola : Before the implementation of Grouping and Sum In grid the excel export button was showing but after the implementation , they stopped displaying and replaced by the grouping buttons. Kindly assist.

**Comment by brunobola** [comment]
Hummm, @dsCloud perhaps you can add a new button with splice and change it to your needs, have you tried ?
