### ISSUE TITLE
Master Details Grid, detail row repository methods not triggered

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4004]
In a master details Grid,

Whenever i add bulk of details row items , (i.e ServiceItems row in below eg)  repository methods not triggered
In below eg, SerViceItems repositorie's **ValidateFieldValues** or any other override methid not triggered when i add the serviceItems through MasterDetails grid
![image](https://user-images.githubusercontent.com/4771536/46936541-b6b40b00-d06f-11e8-9ea9-089c8c2e588b.png)

It is working fine in its own grid (ServiceItems Grid)
I want to validate the items before Savings even when added through Master Details Grid
```
 private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void ValidateFieldValues()
            {
                base.ValidateFieldValues();
            }
         }
```

**Comment by ga5tan** [comment]
this grid here is "in memory" grid, different from entity grid. it only holds detail rows, and they are saved when master row is saved. 
if you wanna details events to be triggered, use  [DefaultHandler] attribute

like this:

> [DefaultHandler]
> private class MySaveHandler : SaveRequestHandler

**Comment by jabirmoolur** [comment]
@ga5tan Thanks a lot,
It was something new to me..Thanks

**Comment by ga5tan** [comment]
did it work for u?
I found it in chengelog

**Comment by jabirmoolur** [comment]
@ga5tan  Yes. Thank you
