### ISSUE TITLE
Instead of Insert Trigger; returning identity from freshly inserted row so that EntityId within saveresponse is filled correctly

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4005]
Hi all,

because I have to use complex views as the underlying data source for some of my xyzRows.cs, I have to handle the delete, updates and inserts via "MS SQL instead of xxx triggers" (because the view without that does not allow anymore any modifications on the data).

This works fine - except that I have great difficulty to return the identity value of the freshly inserted row/record back into Serenity so that the returned SaveResponse from within xyzRepository.cs within EntityId Field contains the Identity value of the freshly inserted row/record.

Currently, no matther what I try within the instead of insert trigger (like ```select @id ```(where @Id represents the correct value of the identity of the just inserted row)) I am not able to send back the identity of the inserted row back to Serenity - EntityId field within SaveResponse always is "undefined".

**Possible Workaround:**

I know that within MySaveHandler I could try to get the row with the highest Identity value and that would - in most if not any cases of my use case - represent the correct identity for freshly inserted rows - but I rather would like that the "instead of insert trigger" returns the identity of the inserted row so that It can be picked up by Serenity/Dapper like it does when doing the insert into a standard table.

(I am aware of the fact that MS SQL instead of insert triggers can theoretically handle more than one row within one trigger call and that's why there is no automatic @@identity or Scope_Identity - but how to workarround this in the case of Serenity?)

How to achieve this?

Thanks for any help and

With kind regards,

John

**Comment by edwardch** [comment]
Hi John,

I haven't had to override any of my save handlers for create/update/delete in Serenity, but I wonder if you could try a stored procedure with an output variable as the identity?

For the procedure it would be something along the lines of: [Returning ID from Stored Proc](https://stackoverflow.com/questions/9557603/need-a-stored-procedure-that-inserts-a-row-and-returns-the-id).

In my previous job (we used a custom built framework) all the inserts/updates/deletes were handled via stored procedures and the insert procedures returned the scope identity in a similar fashion to the link above.

We also created a schema called "Inserts" and all the insert procedures were kept within this schema, for better security/auth control.

I hope I understood your question correctly, and I hope this helps.

Cheers!

**Comment by JohnRanger** [comment]
For the benefit of all,

here the solution:

Within your instead of insert trigger, do the following to successfully return the identity of the just inserted record:

```sql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Trigger [dbo].[ChainsAndSingleRessortsLayouts_VersionVisibilityHandling_inserts] on [dbo].[ChainsAndSingleRessortsLayouts_VersionVisibilityHandling] INSTEAD OF insert  
as 
if @@rowcount = 0 return; 
SET NOCOUNT ON

Declare @tableToUpdate AS Nvarchar(max) = 'dbo.ChainsAndSingleRessortsLayouts';
Declare @InsertStatement AS Nvarchar(max)
Declare @IdentityField as Nvarchar(max) = (SELECT Name FROM sys.columns WHERE [object_id] = OBJECT_ID(@tableToUpdate) and is_identity = 1)

Declare @Fields AS Nvarchar(MAX)
SELECT  @Fields = COALESCE(@Fields + ', ', '') + Name FROM sys.columns WHERE [object_id] = OBJECT_ID(@tableToUpdate) and Name != @IdentityField;

set @InsertStatement = 'DECLARE @ids TABLE(id INT)'
set @InsertStatement = @InsertStatement + 'insert into ' + @tableToUpdate + ' (';
set @InsertStatement = @InsertStatement + @fields;
set @InsertStatement = @InsertStatement + ') select ';
set @InsertStatement = @InsertStatement + @fields;
set @InsertStatement = @InsertStatement + ' FROM #inserted'
set @InsertStatement = @InsertStatement + ' go '

select * into #inserted from inserted 
EXECUTE sp_executesql @InsertStatement

select @@IDENTITY
```

I do here within dynamic SQL get all fields from the table where the data has to be inserted and then fill all fields except the identity field from the inserted table (which by design drop all "non-natural" fields from within the view (where this instead of insert trigger is attached) and then execute it. 

After that, I use ```select @@identity ``` to return the identity value of the new record back to Serenity.

Hope this helps somebody.

If I have time I will do a ABB (advanced Building Block) in the Wiki about how to successfully use complex views instead of basic tables from within Serenity (with all the workarounds needed for Insert, Update and Delete).

With kind regards,

John
