### ISSUE TITLE
Lookup for dropdown; Showing only entries which have not already been choosen within other records of same table

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4008]
Hi All,

I need to have a lookup (to chose from within a dropdown) which primarily gets its data from a table (as is standard) but it should only show entries which have not already been used within the current table.

So the more records are created within the current table (and the field with the lookup is a mandatory field), the less entries within the lookup dropdown will be there - until all entries have been used.

Then no additional record can be created because the lookup will be empty.

How to create such a lookup.

Thanks for any hints and

with kind regards,

John

**Comment by brunobola** [comment]
You could do a SQL condition and then use the lookup filtervalue to achieve this behaviour.

**Comment by Zahar661** [comment]
"PickObjectRow" add "AmounUse" that he is involved and add "LookupInclude". Then use the filter in the edit form. "AmounUse=0 or PickObjectRowID=this.entity.PickObjectRowId"

**Comment by JohnRanger** [comment]
Thank you @edwardch  and @Zahar661  for your fast feedback.

@edwardch : That's exactly what I need - and just as you say - it has to include the currently selected value also :-)

@Zahar661 : I unfortunately don't understand what you mean.

Where exactly within "PickObjectRow" I have to add: AmounUse? 

May I kindly ask you to modify edwardch's example with your optimization for clarification?

Thanks again and with kind regards,

John

**Comment by Zahar661** [comment]
@JohnRanger LookupObjectRow add 
```
[Expression("(Select Count() from MyPrimariTale where T0.LookupObjectId=MyPrimariTale.LookupObjectId)"), lookupInclude]
        public Int32? AmounUse
        {
            get { return Fields.AmounUse[this]; }
            set { Fields.AmounUse[this] = value; }
        }
```
get a sign of whether a record is used or not

and lookupFilter in TS eg https://github.com/volkanceylan/Serenity/issues/3523

**Comment by JohnRanger** [comment]
@edwardch ,

I have tested your code and it works for the first record I add after I start the project within Visual studio. But If I add a 2nd record within the same serenity session (Project still running), it still shows the just added entry from the first adding.

When I debug the lookup script, it gets only triggered the first time the dialog opens.

How can I trigger the lookup script every time? 

With kind regards,

John

**Comment by JohnRanger** [comment]
@Zahar661 ,
thank you very much for your help.

in the meantime, I had to take a completely different approach and do the handling of the dropdown item list fully dynamically on the server side (no lookup "script"). With this approach, I can also dynamically add the "missing" item for the current value and immediately re-calculate the item list within the dropdown when the other dropdown (Clubselector) changes its value.

@edwardch : I will make a wiki entry how to do all of this (had cost me end-to-end about 14hrs) in order to give something back to the community :-)

Thanks for all of your help and constructive feedback.

With kind regards,

John

**Comment by jgranade** [comment]
@JohnRanger I know this is several years old now but still relevant.  Did you create that wiki entry on how you filtered out records that are already in use?  I'm looking but not finding it.  I've been wrestling with this for a while now and would love your implementation.

Thanks,

John
