### ISSUE TITLE
Add total label side of toolbar button grid

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#401]
Hi Jaiq
I want to create total label as below, total will changed after grid refresh fill with sum off total value in column, have suggestion?

![totallabel](https://cloud.githubusercontent.com/assets/6382278/13726643/5a3db402-e904-11e5-8273-a4c3366f98cd.png)

**Comment by volkanceylan** [comment]
See recent closed issues, somebody already shared solution

**Comment by rudianto2008** [comment]
Thanks Jaiq, below the result 
And special thanks for shared solution to @ChenZhaobin it's very help me.

![eas](https://cloud.githubusercontent.com/assets/6382278/13729379/55200c9c-e966-11e5-89c3-be24d230d612.png)
