### ISSUE TITLE
Error trying to change any user value

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4010]
Hi all,
Does any one has already got that message ? (see attached).
It appears on a new fresh app . My environment is VS 2017.
![user update pb](https://user-images.githubusercontent.com/28645113/47145961-4f929280-d2cb-11e8-9c3b-cf075c5cd880.PNG)

Kind regards,
Frederic

**Comment by fremar83** [comment]
For the records, it's a StartSharp app.

**Comment by brunobola** [comment]
Try in edge browser for instance and see.
Maybe something to do with chrome autocomplete...

**Comment by edwardch** [comment]
I've had some auto complete/fill issues in the past. I can't remember the exact condition or field that was edited, but I definitely remember there was _something_. 

Turn off autocomplete / try a different browser / double check all fields and their values before saving.

**Comment by fremar83** [comment]
Hi guys! Thank's for your quick answers! 
You're perfectely right!! Deleting autocomplete on Firefox saved me on all my sites (I had that problem with 3 of them).

Many thank's.
Frederic

**Comment by fremar83** [comment]
Curiously, I had access to all other parts of my site (even those with admin rights). Only the user module had this problem. I noticed by the way that there is a right issue on that user module. I have a first dev with initial "admin" user deleted and a second one with "admin" user always active. If I start this second site with VS 2017 (CTRL+F5) entering admin/serenity, I can access all my site (logical). But if I start the first site (with VS to), I don't need to log. I'm directly under "Admin" user and have acces to all the site in admin rights (even user module). See attached : User liste does not include Admin and I am logged with it ! And I can modify all I want!
![admin user pb final](https://user-images.githubusercontent.com/28645113/47166081-a912b580-d2fb-11e8-8585-25a8a39db473.png)

**Comment by volkanceylan** [comment]
Your auth cookie name for both applications are same and cookies are domain based not port, so when you login with one, you stay logged in with other. So this is normal with ASP.NET
