### ISSUE TITLE
Adding field to Login Form

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4012]
Hi,
I'm in nead to add a field in the login form representing the name of the Company.
So 3 field : Username, Password and Company.
The company has to be linked to a class representing the Company Entity.
If I use the Lookup Editor it seenms not work.
How can I work around it?
Simone

**Comment by brunobola** [comment]
Did you see [this](https://github.com/volkanceylan/Serenity/wiki/Multi-Database-Serenity)
