### ISSUE TITLE
Force update dialog grid list

### ISSUE THREAD

**Issue by kanadmehta** [volkanceylan/Serenity#4014]
I have a master dialog and within this master dialog I have an editor(GridEditorBase).

When a change is made in editor dialog and saved (and closed, no apply change).
I need to force update editor Grid list from database (I have triggers that update entity data in database).

I have added a  onChange property to the Editor, call the property from save method and listen for changes in the master Dialog. (Reference #1129)

But the  this.form.<Editor>.refresh(); doesnot force refresh from database.

**Comment by JohnRanger** [comment]
try from within xyzDialog.ts: 

```ts
this.loadById(response.EntityId); // *** Refresh the Dialog with infos from database ***
```

**Comment by ga5tan** [comment]
@JohnRanger I believe, he's taking about Detail Editor (inmemory grid)
It can be "refreshed" by loading list of rows and assigning it to .value property of it.

**Comment by fremar83** [comment]
I think I have quite similar issue. 
When I save detail dialog, the add is not done in the database. Add in the DB is done only when I save the master dialog. 
Is there a way to update DB within the detail dialog ?

**Comment by minhhungit** [comment]
@fremar83 Until now, it is normal behavior, everything changes on GridEditorBase is in memory, so you have to hit save button on your master dialog to save entity.

IMHO I think you will need to read serenity document first https://serenity.is/docs/tutorials/movies/the_cast_and_characters_they_played

>Is there a way to update DB within the detail dialog ?

To answer this question, you will need to overwrite saveRequest, saveHandler... in editor dialog, pass some variables to editor dialog and you may need to create a custom endpoint to save your entity.

Check more at [here ](https://github.com/volkanceylan/Serene/blob/daefd17cdf4713fce40d5145bde35b5a250dd26d/Serene/Serene.Core/Modules/Common/Helpers/GridEditorDialog.ts)and [here](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Scripts/CoreLib/UI/Widgets/EntityGrid.ts)


Personality  I will let it as current (hit save button on master dialog).

**Comment by fremar83** [comment]
In the same way, if I create de GroupOfTraitments from the master Project, I cannot use it in a traitment add before updating the master as the GroupsOfTraitments list is not updated in traitment form combo.

**Comment by ga5tan** [comment]
@fremar83 ever considered splitting it into two dialogs?
One would list groups, and if u choose group, u could have Traitments (is it treatment in French?) listed there in detail.

you could also consider not using Master Detail, just manage detail grid by yourself, or have it as Entity Grid...

**Comment by fremar83** [comment]
@ga5tan 
You're right, In French it's "traitements" ! that's why had that mistake.
I wanted all the treatments visible from the master project form (not only goups). That's why I have 2 master/details. If there is no other choice, I will delete groups master/detail stuff and use grouping grid field. I don't want to have side effects overwriting saveRequest or saveHandler.

**Comment by ga5tan** [comment]
@fremar83 another option is Premium Feature called "Split View Master/Detail Grids", maybe that could help

**Comment by ga5tan** [comment]
yup

**Comment by fremar83** [comment]
I use StartSharp. The only way I found is GroupingAndSummariesInGrid in basic samples. Is that the feature you have in mind ?

**Comment by ga5tan** [comment]
https://serenity.is/demo/AdvancedSamples/SplitMasterDetail

I somehow assume second grid is entity grid (since buttons and quickfilters)

so u could add third grid, with your treatments into second grid, having just one inmemory grid...

**Comment by fremar83** [comment]
That's a really good idea!
I'll try that way. Thank's for your help !

**Comment by fremar83** [comment]
After thinking on it, I definitly will prefer the grouping method because i want to see all the treatments in the project form (not filtered by groups). Thank's anyway.

**Comment by minhhungit** [comment]
@fremar83 Can you create new issue with more detail, I am not sure I follow you.
Please add some screenshots. Thank you
