### ISSUE TITLE
Lock whole site down until condition is met

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4016]
Hi

After user logs in, and he did not agree to licence agreement, I need to "ideally" stuck him on his account page, and dont let him leave it (until he agrees to licence)
He cannot place orders for examle. Any idea how and where to do that?

thx

**Comment by ga5tan** [comment]
I was able to forward user after login to the page and not let him out, but he is still able to change URL in browser and go to home/dashboard.

Is it somehow possible to intercept navigation and send him back to his account page?

**Comment by volkanceylan** [comment]
I wouldn't let user login actually in your case, would generate a token (see forgot password / reset password) and let user access some special page only with that token.
