### ISSUE TITLE
[Important Notice!] Please update handlers section in web.config files

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#4017]
While testing another site, we noticed that handlers in our web.config files also applies to sub folders. This might lead to some problems / security issues for your error log. Please put a slash in PATH attribute of these handlers. E.g. if you have these in your web.config:

```xml
  <handlers>
    <add name="ErrorLog" path="errorlog.axd" verb="POST,GET,HEAD" type="StackExchange.Exceptional.HandlerFactory, StackExchange.Exceptional" preCondition="integratedMode" />
    <add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />
  </handlers>
```

Replace them with

```xml
  <handlers>
    <add name="ErrorLog" path="/errorlog.axd" verb="POST,GET,HEAD" type="StackExchange.Exceptional.HandlerFactory, StackExchange.Exceptional" preCondition="integratedMode" />
    <add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="/DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />
  </handlers>
```

So that they only apply to root folder.

If this configuration causes any problems for you, let us know.

**Comment by stixoffire** [comment]
I had to change the order of the handlers and the modules in my web config on Visual Studio 2017.

Handlers FIRST, and then MODULES .. I don't know why that resolved the issue I was having. 

Only occurred with Windows 10 Professional 64 and IIS 10.0.1734 - I will add the slash though..

**Comment by Estrusco** [comment]
OK thank you volkan

**Comment by volkanceylan** [comment]
Didn't test that for upload yet, if it works for you, e.g. can see uploaded files after making that change, then you should
