### ISSUE TITLE
Problem with entities

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4022]
I have a entity named "TestataProventivi". It'will be retrieved by the following statement : 
public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
{
    return new MyRetrieveHandler().Process(connection, request);
}
The statement give a SQL Error on IdAzienda a field that is listed in "TestataPreventivi".
How can bypass the error?
Simone

**Comment by ga5tan** [comment]
lol, what kind of error. Is this some guessing game?
just random answer off the top of my head: did u rebuild and T4 transform?

**Comment by simonespagna** [comment]
Thanks I solved my problem.
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno mar 23 ott 2018 alle ore 22:45 Juraj Benadik <
notifications@github.com> ha scritto:
