### ISSUE TITLE
Can not get Field value w/ Expression and MinSelectLevel

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4023]
I have a field on Row like this
```csharp
[Expression("ISNULL(T0.[End], 0)"), MinSelectLevel(SelectLevel.Always)]
public Double? End
{
   get { return Fields.End[this]; }
   set { Fields.End[this] = value; }
}
```

In somewhere of Endpoint I need to get a row by TryFirst,
```csharp
using (var connection = SqlConnections.NewFor<MyRow>())
{
   MyRow preRow = connection.TryFirst<MyRow>(MyRow.Fields.Id == 1)
}
```
**It throws out an exception:**
`...Extensions like connection.List only loads table fields by default, view / expression fields are not loaded unless explicitly selected`

I added `MinSelectLevel(SelectLevel.Always)` but it did not work
It just work when I remove [Expression]

What's wrong  with me, what I should do

**Comment by minhhungit** [comment]
Btw it works on grid but not work when I query by TryFirst

**Comment by luongnv6** [comment]
You can try:
var fld = MyRow.Fields;
               MyRow preRow = connection.TryFirst<MyRow>(
                    q => q.SelectTableFields()
                   .Select(fld.test)
                   .Where(fld.Id == 1));

or
var fld = MyRow.Fields;
               MyRow preRow = connection.TryFirst<MyRow>(
                    q => q.SelectTableFields()
                   .SelectNonTableFields()
                   .Where(fld.Id == 1));


Hope to help you

**Comment by minhhungit** [comment]
Thanks @luongnv6
