### ISSUE TITLE
Label change on ChangeSelect2 event

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4024]
Hi guys, I have one question.

It's possible to change a label text based on the value of a filed of the row that I select?

Thanks!

**Comment by ga5tan** [comment]
Check this demo:
https://serenity.is/demo/BasicSamples/InlineActionButtons

it has event handler for when u click in the grid. that may help

**Comment by Shraddha996** [comment]
hey! thanks, @ga5tan  for a quick reply
But I think I need to explain a little bit
![capture11](https://user-images.githubusercontent.com/39983941/47419819-a3edb480-d79a-11e8-9c85-8f1747d96bc5.PNG)
From the above dropdown selection i want to change the label text from detail section
![capture12](https://user-images.githubusercontent.com/39983941/47419899-cf709f00-d79a-11e8-8e15-196b946cc176.PNG)

thanks in advance!

**Comment by ga5tan** [comment]
I would pass Month number to the Editor (assuming this is master detail form) and do the month logic there.

**Comment by Shraddha996** [comment]
Thank You! @ga5tan
