### ISSUE TITLE
Footer in report

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4025]
How con I put header and footer in Serenity report engine?
Thanks,
simone

**Comment by Estrusco** [comment]
https://github.com/volkanceylan/Serenity/issues/3898

**Comment by simonespagna** [comment]
Marco,
grazie. Non capisco dove devo mettere quel metodo.
Ciao,
Simone
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno mer 24 ott 2018 alle ore 12:10 Marco Muratore <
notifications@github.com> ha scritto:

**Comment by Estrusco** [comment]
Ciao. Ti rispondo in inglese così può leggere tutta la community.

You can override Customize method in your Report class. 

```cs
    public class YourReport : ReportBase, IReport, IReportDesign, ICustomizeHtmlToPdf
    {
        public Int32? ID { get; set; }

        public object GetData()
        {
            [...]
        }

        public override void Customize(IHtmlToPdfOptions options)
        {
             base.Customize(options);

             // Here is where you can set header and footer option
        }
}
```

There are other info in https://madalgo.au.dk/~jakobt/wkhtmltoxdoc/wkhtmltopdf-0.9.9-doc.html and  in wkhtmltopdf github https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by simonespagna** [comment]
Hi Marco,
thank yoir for your answer.
Applying the method you suggested me I have the error attached below.
[image: Immagine3.png]
Write me soon,
Simone
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno mer 24 ott 2018 alle ore 12:50 Marco Muratore <
notifications@github.com> ha scritto:

**Comment by BravoSierra** [comment]
Hello Marco,

Could you please explain where ReportBase and IReportDesign interfaces come from? Am I missing a reference? 

Also, surprisingly, some option.CustomArgs work fine, but others don't.
For example:

options.CustomArgs.Add("--header-line'"); //ok
options.CustomArgs.Add("--default-header"); // ok but ugly display of the page path 
options.CustomArgs.Add("--header-right='[page]/[toPage]' " // Error generating PDF
options.CustomArgs.Add("--header-left='this is a title' "); // Error 

Any guidance about which wkhtmltopdf options can be used or not in the Customize method?

Thanks

**Comment by Estrusco** [comment]
Hi, 

@simonespagna try to insert your image in an <!DOCTYPE HTML> (see code bottom).

@BravoSierra  sorry, ReportBase is my baseclass that simply contain definition of virtual public void Customize(IHtmlToPdfOptions options). IReportDesign also is mine, but you don't need.

For footer, if you want to show number page, try to use a footer.html like this, from this post https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3270

**NOTE: files for footer and heater must have absolute path in wkhtmltopdf paramters.** For example in this case 

```cs
     options.CustomArgs.Add("--footer-html");
     options.CustomArgs.Add(@"c:\app\App_Data\somedirectory\footer.html");
```

```html
<!DOCTYPE HTML>
<html>
<head>
    <script>
        function subst() {
            var vars = {};
            var x = window.location.search.substring(1).split('&');
            for (var i in x) { var z = x[i].split('=', 2); vars[z[0]] = unescape(z[1]); }
            var x = ['frompage', 'topage', 'page', 'webpage', 'section', 'subsection', 'subsubsection'];
            for (var i in x) {
                var y = document.getElementsByClassName(x[i]);
                for (var j = 0; j < y.length; ++j) y[j].textContent = vars[x[i]];
            }
        }
    </script>
</head>
<body style="border:0; margin: 0;" onload="subst()">
    <table style="width: 100%; font-size: 12px">
        <tr>
            <td style="text-align:right">
                Page <span class="page"></span> of <span class="topage"></span>
            </td>
        </tr>
    </table>
</body>
</html>

```

**Comment by simonespagna** [comment]
Hi Marco,
can you post a brief but complete example?
Thanks,
Simone

*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno gio 25 ott 2018 alle ore 08:48 Marco Muratore <
notifications@github.com> ha scritto:

**Comment by BravoSierra** [comment]
I must be missing something because before I can try the more complex examples, I cannot even succeed with very simple arguments when I try to pass any kind of information, i.e.

options.CustomArgs.Add("--footer-left"); // displays nothing, but does not break
options.CustomArgs.Add("--footer-left 'Test' "); // InvalidOperationException: Generated PDF file is empty!
options.CustomArgs.Add("--footer-left = 'Test' "); // InvalidOperationException: Generated PDF file is empty!

So sum it up, Args that do not require any extra information work fine, (like options.CustomArgs.Add("--header-line'"); 
but if they include a custom parameter like a string or or path they break

options.CustomArgs.Add("--default-header"); works, but unfortunately is not usable because it implies --header-left='[webpage]' wich is ugly

**Comment by Estrusco** [comment]
@simonespagna I will write a wiki entry as soon as possible.

**Comment by simonespagna** [comment]
I'm in urgent need ..... ( sono nella cacca e devo fare funzionare la cosa )
Bye
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno gio 25 ott 2018 alle ore 12:03 Marco Muratore <
notifications@github.com> ha scritto:

**Comment by Estrusco** [comment]
New wiki entry: https://github.com/volkanceylan/Serenity/wiki/How-to-add-Header-and-Footer-in-WKHTMLTOPDF-report

**Comment by Estrusco** [comment]
mmm, I don't know. I think no. 

cshtml file have a model and is server processed in ASP.Net, wkhtmltopdf don't know it. 

You can try dynamically pre-generate your html and pass it to wkhtmltopdf.

**Comment by simonespagna** [comment]
Ciao Marco,
un [OT}. Quale evento viene scatenato quando schiaccio un entry per entrare
nel dettaglio dati sulla grid?
Simone
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno ven 26 ott 2018 alle ore 10:37 Marco Muratore <
notifications@github.com> ha scritto:

**Comment by teafmartins** [comment]
Hello,
Can I add url parameter and use it in the header? something like:

options.CustomArgs.Add("--header-html");
options.CustomArgs.Add(PhisicalPath + "header.html?title=Report One");

Thx
