### ISSUE TITLE
Filtered drop down refresh

### ISSUE THREAD

**Issue by jgranade** [volkanceylan/Serenity#4026]
I suspect there's an easier way but after days of chasing it, here's what I have...I have table Extensions which can have a PhoneId (or Null) assigned.  When you edit Extensions and get that dropdown to select the Phone, I want to filter out all the Phones that have already been assigned.   I'm also filtering on ClientId (much like TenantId).  The tricky part for me was getting the SubQuery to work but then I figured out Nulls were the problem and once I addressed that, things work as expected (initially).

```
var fld = Entities.PhonesRow.Fields;
var eFld = Entities.ExtensionsRow.Fields;

base.PrepareQuery(query);

var clientId = "0";

if (System.Web.HttpContext.Current.Request.Cookies.Get("CurrentClient").Value != null)
{
	clientId = System.Web.HttpContext.Current.Request.Cookies.Get("CurrentClient").Value;
}

query
    .Where(new Criteria(fld.PhoneId).NotIn(query.SubQuery().From(eFld).Select(eFld.PhoneId).Where(eFld.PhoneId.IsNotNull())))
	.Where(fld.ClientId == clientId);
```

The problem is PrepareQuery is only loaded at the Page load.  So if you edit an Extensions row changing the assigned phones, and then edit another Extension, the drop down for Unassigned Phones is incorrect as it's only showing what was pulled originally before the previous row edit.  

Should I be filtering client side or is doing in this way fine and I'm just missing how to refresh the Query after every Save to any Extension row?

Thanks,

John

**Comment by ga5tan** [comment]
Try CascadeField and CascadeValue

**Comment by jgranade** [comment]
For others that need this, the resolution I found to use the onSaveSuccess to force the reload.  So in the appropriate Dialog.ts file add

```
onSaveSuccess(response) {
            super.onSaveSuccess(response);
            Q.reloadLookup('[Your Lookup Script]');
        }  
```
