### ISSUE TITLE
Intercept update state in AfterSave

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4029]
I have to intercept where a entity in update in AfterSave method.
How can I do it?
Thanks,
Simone

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Product/ProductRepository.cs
![image](https://user-images.githubusercontent.com/26430136/47714616-ced27f80-dc56-11e8-900f-0d43498814d3.png)

**Comment by simonespagna** [comment]
Thanks. I have a grid with row details opening on click on lookup fields.
I want to put alert that advise the user that a cole of the record will be
created.
Simone

*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno mar 30 ott 2018 alle ore 12:16 Zahar661 <notifications@github.com>
ha scritto:
