### ISSUE TITLE
Can't refresh or edit permissions

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#403]
So I just created a new project and for some reason I can't edit the permissions. The screen comes up, but when I go to select one of the check boxes, bam. Nothing. Can't select anything and the same goes with the refresh buttons. None of them work. Should I just uninstall the SERENE or what should I do?

**Comment by volkanceylan** [comment]
Is it 1.9.20? Probably something broken after SlickGrid update

**Comment by wdhodges** [comment]
Let me double check really quick

**Comment by wdhodges** [comment]
Yep 1.9.20. How do I fix it?

**Comment by wdhodges** [comment]
SlickGrid Version 2.2.20140120

**Comment by wdhodges** [comment]
Or can I revert back to the 1.9.19 build until this bug is fixed?

**Comment by volkanceylan** [comment]
Yes i probably found problem. Releasing 1.9.21 now. Please test and let me know if any problems persist.

**Comment by wdhodges** [comment]
Thanks my friend! Testing now.

**Comment by wdhodges** [comment]
Are you releasing via NuGet or VISX?

**Comment by volkanceylan** [comment]
Both but at the moment having difficulty with NuGet too

**Comment by volkanceylan** [comment]
Waiting for packages to be indexed

**Comment by wdhodges** [comment]
Sounds good. I'm sitting on MSDN site waiting for the version change. I'll update this thread as soon as I test it out.

**Comment by volkanceylan** [comment]
1.9.21 is out now, should fix problems.

**Comment by wdhodges** [comment]
Downloading the VISX file now

**Comment by wdhodges** [comment]
Still broken my friend. I created a new project. Straight from start up I went to Roles > Add new role. I created new Role and selected re-fresh. Nothing happened. I refreshed the entire page via browser and my new role appeared. Selected edit permissions and still cannot add anything. It's like the check boxes are there but do not function.

**Comment by wdhodges** [comment]
`packages.config` contents:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="bootstrap" version="3.3.6" targetFramework="net45" />
  <package id="EPPlus" version="4.0.5" targetFramework="net45" />
  <package id="FluentMigrator" version="1.6.1" targetFramework="net45" />
  <package id="FluentMigrator.Runner" version="1.6.1" targetFramework="net45" />
  <package id="jQuery" version="2.2.0" targetFramework="net45" />
  <package id="jquery.event.drag" version="2.2.0" targetFramework="net45" />
  <package id="jQuery.UI.Combined" version="1.11.4" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.14.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="8.0.2" targetFramework="net45" />
  <package id="Select2.js" version="3.5.1" targetFramework="net45" />
  <package id="Serenity.CodeGenerator" version="1.9.21" targetFramework="net45" />
  <package id="Serenity.Core" version="1.9.21" targetFramework="net45" />
  <package id="Serenity.Data" version="1.9.21" targetFramework="net45" />
  <package id="Serenity.Data.Entity" version="1.9.21" targetFramework="net45" />
  <package id="Serenity.Services" version="1.9.21" targetFramework="net45" />
  <package id="Serenity.Web" version="1.9.21" targetFramework="net45" />
  <package id="SlickGrid" version="2.2.20140120" targetFramework="net45" />
  <package id="toastr" version="2.1.1" targetFramework="net45" />
</packages>

**Comment by volkanceylan** [comment]
Ok will have another look

**Comment by wdhodges** [comment]
Thanks!

**Comment by volkanceylan** [comment]
Problems was due to template still has reference to old SlickGrid package, so it was overriding my customizations. Please try with 1.9.22.

**Comment by wdhodges** [comment]
trying now

**Comment by wdhodges** [comment]
SUCCESS!!! Thank you @volkanceylan for your quick response to this issue!

**Comment by volkanceylan** [comment]
You are welcome @wdhodges. Thanks, and sorry for the trouble.

**Comment by wdhodges** [comment]
Don't be sorry! It happens! Not to mention you solved a breaking issue
within 10 hours of it being raised. That's astonishing and you should he
proud!

**Comment by volkanceylan** [comment]
Thanks, feel better now ;) But still need more tests...

**Comment by Thebenmandude** [comment]
Hi,
I am having the same issue where I cannot "tick" any permissions or even filter. I am using the Multitenancy example and have made sure to update Serenity from NuGet as well as all the parts from the Package Manager Console. Still no luck. Please assist..

**Comment by volkanceylan** [comment]
Uninstall SlickGrid package, reinstall all other packages. If still not work, copy SlickGrid folder from a new Serene project.

**Comment by Thebenmandude** [comment]
Thanks, I uninstalled SlickGrid and reinstalled Serenity.Web and Serenity.Script. Didn't work, I then copied Slick grid folder from a new project. Didn't work. I then installed SlickGrid again without any luck and then copied the Slickgrid folder from a new project again. The filter is now working but I still cannot check any checkboxes.

**Comment by volkanceylan** [comment]
Is there any error in console?

**Comment by volkanceylan** [comment]
Something must be different in your project. Can you use WinMerge to compare script folders?

**Comment by Thebenmandude** [comment]
No, the project compiles and runs without errors. Also, the PM console does not produce an error. It did seem like SlickGrid was not installed as I couldn't uninstall at first. Also, this did work a couple of days ago before I made some small changes to include the Google Places API, I reverted all my custom code and still was not able to check the boxes. I am going to do a WinMerge now and compare a new project.

**Comment by volkanceylan** [comment]
Is PM console means browser console? There might be some script errors in Chrome console.

**Comment by Thebenmandude** [comment]
![image](https://cloud.githubusercontent.com/assets/6910368/13883553/9db25102-ed32-11e5-95fe-9c3029a848dc.png)

**Comment by volkanceylan** [comment]
Can you click link on ss.initClass.onClick and $slickGridOnClick lines and share which lines it fails

**Comment by volkanceylan** [comment]
Btw, was this a clone of MultiTenancy sample in Github, or you followed tutorial by creating this project manually?

**Comment by Thebenmandude** [comment]
ss.initClass.onClick is the only one that seems to have an error on line 1416
"var item = this.view.rows[row];"

**Comment by volkanceylan** [comment]
I think somehow you couldn't update to the latest version. NuGet V3 server sometimes causes this. See packages.config file under Serene.Web project. What is Serenity.Web version there?

**Comment by Thebenmandude** [comment]
<package id="Serenity.Web" version="1.9.24" targetFramework="net452" />

**Comment by volkanceylan** [comment]
What about the Serenity.Script package? I don't have a this.view.rows in my Serene.Script.js file. It must be this.rows.getDataItem(row). If Serenity.Script is also 1.9.24 try rebuilding Script project, check if your Script.js file changes date etc.

**Comment by Thebenmandude** [comment]
package id="Serenity.Script" version="1.9.24" targetFramework="net20"
I had a look at a new project and saw the this.rows.getDataItem(row). I just changed that one line and can now check permissions. Thanks for the help.

**Comment by volkanceylan** [comment]
But still its strange, you shouldn't manually do this, in next build it will turn back to old code probably.

**Comment by Thebenmandude** [comment]
It was a clone of the MultiTenancy sample in Github. Should I rather start a new project and make the MultiTenancy changes from there?

**Comment by Thebenmandude** [comment]
I see, rebuilding the serenity.script changes the line back.

**Comment by volkanceylan** [comment]
Maybe but better you should understand why it still references old version. Maybe Serenity.Script.UI project reference still to an old version. See what is referenced in MultiTenancy.Script.csproj file looking at source.

**Comment by Thebenmandude** [comment]
I have added my own code to the afterLoadEntity function in the Serenity.Script.UI file. Could this cause the file to not update?

**Comment by volkanceylan** [comment]
Maybe

**Comment by jcamp45** [comment]
FYI that I had the same issue.  Could only resolve by overwriting the UserPermission cs files in the Script project using a new blank project based on 1.9.24

**Comment by volkanceylan** [comment]
Oh, now i understand, this line in PermissionCheckEditor:

```cs
                var item = this.view.Rows[row];
```

Should be this:

```cs
                var item = Rows[row];
```

**Comment by volkanceylan** [comment]
I actually added Obsolete to this and used InlineCode but because of IntrinsicProperty, Saltaralle ignored my InlineCode attribute :(
```
        [IntrinsicProperty, Obsolete("Use GetItem and GetLength")]
        public new List<TEntity> Rows { [InlineCode("{this}.getRows()")] get { return null; } }
```

Will be fixed in next version, thanks.

**Comment by Thebenmandude** [comment]
Thanks, that did the trick!
