### ISSUE TITLE
I want to show images in a grid

### ISSUE THREAD

**Issue by karimQasem** [volkanceylan/Serenity#4032]
hello,
I want to show images in a grid how ??

**Comment by karimQasem** [comment]
I did [Inline Image Formatter, Width (450)] but it does not work

**Comment by minhhungit** [comment]
I'm not sure, but there is some steps you can review:
- any error on browser ?
- make sure that your row has data
- make sure that your image was placed in ~/upload/

**Comment by karimQasem** [comment]
thanks
