### ISSUE TITLE
Hovering informational Panel

### ISSUE THREAD

**Issue by GAdji2005** [volkanceylan/Serenity#4034]
Hiii

  was wondering if there is a way that i could display a hovering, semi transparent informational panel ( maybe like the login panel ) that can be moved around the screen or minimized ... 
    would be used for general updatable information or statistics, like:

- number of users logged in
- number of customers registered
- number of todays orders, etc, etc...

Thanks in advance
   if anyone has a sample to share ...

**Comment by Zahar661** [comment]
https://jqueryui.com/dialog/

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/47713362-8b2a4680-dc53-11e8-9779-04fdf6aea559.png)
