### ISSUE TITLE
Clone entity

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4038]
I have two entitiy A e B. A is the master of B that is the detail.
I have to clone it.
How to do it?
Ciao,
Simone

**Comment by edwardch** [comment]
See [the cloning demo](https://serenity.is/demo/BasicSamples/CloneableEntityDialog) for help.

Please refer to the demo site and Wiki's for help with your other questions before opening issues...

Good luck!

**Comment by brunobola** [comment]
https://github.com/volkanceylan/Serenity/wiki/Implementing-isCloneMode
