### ISSUE TITLE
LinkingSetRelation with string and not Id field

### ISSUE THREAD

**Issue by yaseen-h** [volkanceylan/Serenity#4039]
I have 3 tables:
- Roles table with (Id as string, Name is string)
- UserRoles table with (UserId as string, RoleId as string, Id as int)
- Users table with (WebUserId as string, Name as string)

Link between tables:
- Users to UserRoles (1 to many using WebUserId to UserId)
- Roles to UserRoles (1 to many using Id to RoleId)

How to use LinkingSetRelation to link Users table to Roles table for multiple select of roles in User form

**Comment by volkanceylan** [comment]
If you want to use LinkingSetRelation, your tables should have Identity fields.
