### ISSUE TITLE
Report tool in serenity

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4041]
Does Serenity has a report tool?
Simone

**Comment by rcoproc** [comment]
Yes .. it has serenity native using wkhtml rendering html pages, there in the example project has a report of this type in Orders. Prints an order invoice.

And you can use third-party SSRS or TELERIK Report tools with HTML clients.

**Comment by edwardch** [comment]
@simonespagna please refer to the demo site before posting issues.

[https://serenity.is/demo](https://serenity.is/demo)

**Comment by volkanceylan** [comment]
Yes, please :)
