### ISSUE TITLE
LookupEditor not selecting the current value

### ISSUE THREAD

**Issue by jgranade** [volkanceylan/Serenity#4042]
I think I could have done it without it but I created a custom lookupscript so I could do some filtering based on a subquery.

```
[LookupEditor(typeof(UnassignedPhonesLookup))]         
        [DisplayName("Phone Id"), ForeignKey("[dbo].[Phones]", "PhoneId"), LeftJoin("jPhone"), TextualField("PhoneMacAddress")]
        public Int32? PhoneId
        {
            get { return Fields.PhoneId[this]; }
            set { Fields.PhoneId[this] = value; }
        }
```
This hits the PrepareQuery code just fine and does exactly what I want to filter out assigned phones with the query.SubQuery().

```
namespace Provisioner2.Phones
{
    [LookupScript("Phones.UnassignedPhonesLookup")]
    public class UnassignedPhonesLookup : RowLookupScript<Entities.PhonesRow>
        
    {
        public UnassignedPhonesLookup()
        {
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld =  Entities.PhonesRow.Fields;
            var eFld = Entities.ExtensionsRow.Fields;
            
            base.PrepareQuery(query);

            var clientId = "0";
            
            if (System.Web.HttpContext.Current.Request.Cookies.Get("CurrentClient").Value != null)
            {
                clientId = System.Web.HttpContext.Current.Request.Cookies.Get("CurrentClient").Value;
            }
                        
            query
                .Where(new Criteria(fld.PhoneId).NotIn(query.SubQuery().From(eFld).Select(eFld.PhoneId).Where(eFld.PhoneId.IsNotNull())))
                .Where(fld.ClientId == clientId);
        }   
    }
}
```
The selection is correctly filtered and it updates perfectly.  The only problem is when you load the Form, it doesn't select the current item.

![dropdown](https://user-images.githubusercontent.com/103990/47803991-bb302300-dd01-11e8-9f8f-24f1210887c7.PNG)

So now the user doesn't see what was selected and if they save it sets the value to null.  What am I missing for the Dialog to set the value of the DropDown list to be the stored PhoneId?

Thanks,

John

**Comment by volkanceylan** [comment]
Don't do this, lookups don't accept parameters

**Comment by teafmartins** [comment]
@jgranade , did you solve your problem? how?

**Comment by maulikshah88** [comment]
What is the solution for this ?

**Comment by maulikshah88** [comment]
> Don't do this, lookups don't accept parameters

What is the solution to this  problem ? I need custom data to bind in dropdown, but when I use lookupeditor its not selecting values during edit.
