### ISSUE TITLE
How to change the "search..." placeholder from Quickfilter Input

### ISSUE THREAD

**Issue by VGsss** [volkanceylan/Serenity#4044]
I couldn't find a way to change the "search..." placeholder that comes when the quickfilter input search box is created. Where can I find how to do it?

**Comment by VGsss** [comment]
I found it: ~/Scripts/Serenity/texts/serenity.texts.XX-YY > Controls.QuickSearch.Placeholder

**Comment by heveoneron** [comment]
If i Follow @VGsss all of the textbox is same like what i Write.
I have solved with other method. Override the place holder with javascript.
this the Code :

$('#SidebarSearch').attr('placeholder', 'Search... Ctrl + /');
