### ISSUE TITLE
After updating Serenity, we cannot debug the browser. Emergency aid !... - Serenity güncelleme yaptıktan sonra browserde debug gidemiyoruz. Acil yardım !...

### ISSUE THREAD

**Issue by naykut** [volkanceylan/Serenity#4045]
Hello there,

We used and developed the old version of Serenity. We would like to update the latest version with the help below.

Update-Package Serenity.Web

with command

https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/updating_serenity_packages.html

We did the update process, but now when we run the project, we can't debug on browser sources. typescript 2.8 and 3.1 did not test the upgrade. we do what we do on sources, but it skips what we write before running the code before doing the update. Should we make an extra setting? Can you help me out?

![1](https://user-images.githubusercontent.com/44294934/47220326-243aa100-d3ba-11e8-8e12-393b39ce0e29.png)
--------------------------------------

Merhaba,

Serenity nin eski versiyonunu kullandık ve geliştirdik. Yeniden son versiyonunu aşağıdaki link te bulunan yardımla güncellemek istedik.

Update-Package Serenity.Web

komutu ile

https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/updating_serenity_packages.html

Güncelleme işlemini yaptık fakat şimdi işe projeyi çalıştırdımızda browser sources üzerinde debug gidemiyoruz. typescript 2.8 ve 3.1 de yükselterek deneme yaptık olmadı. sources üzerinde yaptıklarımız görünüyor fakat yazdıklarımızı atlayıp güncelleme yapmadan önceki kodları çalıştırıyor. Extra bir ayar yapmalı mıyız? Acil yardım edebilir misiniz?

![1](https://user-images.githubusercontent.com/44294934/47220326-243aa100-d3ba-11e8-8e12-393b39ce0e29.png)

**Comment by JohnRanger** [comment]
It has possibly something to do with a too high version of NodeJS. I had the same problem recently.

If it is an emergency, I suggest to go back to a working copy before you upgraded SF.

With kind regards,

John
