### ISSUE TITLE
Drag&Drop Treegrid; How to define/create a virtual root node

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4046]
Hi All,

I am working the first time on a Tree Grid View (Drag&Drop). So far this works fine - except that I have the problem that when a top level item (not root - currently I dont have any root) is accidentially dragged under any other item, it is impossible to bring it back to its top level position because there is a virtual root node missing where all the items with parentId = null should hang under.

The Items are fed from a real table, not like in the demo where everything is in-memory - where it is easy to define a virtual root.

**Question:**
How can I define a virtual root (which does not come out of the database) and where the items from database with parentId = null (the top level items) are attached as children?

Thanks for any help and

with kind regards,

John

**Comment by volkanceylan** [comment]
You may insert that virtual item on onViewProcessData event, return null for its parent id and its virtual id (e.g. -1) for root items.
