### ISSUE TITLE
BooleanEditor like radio button control

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#4047]
Hello Dear Community,

I need to create radio button UI control instead of checkbox for BooleanEditor visualisation. Is it possible to change view quickly?

Thank you in advance.

**Comment by brunobola** [comment]
Or this https://github.com/volkanceylan/Serenity/wiki/Bootstrap-Material-Design-Switch

**Comment by volkanceylan** [comment]
Thanks, closing

**Comment by Canodev01** [comment]
documented example would have been nice... :\
