### ISSUE TITLE
localisation for Hint and Tab attributes

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#4048]
Hello, is it possible to localise Hint and Tab attributes with localisation keys, like we can do for Categories and Navigation? Thanks.

**Comment by rcruzfalcon** [comment]
Hi, yes, you can put the Q.Text("") into Hint and Tab Captions in typescript code.

**Comment by BravoSierra** [comment]
Thanks Roberto, I created Hint keys that take the name of the property localtext key with "Hint" added at the end, and with the following code inserted in the getPropertyItems() method of xyzDialog.ts:

for (var i = 0; i < items.length; i++) {
             items[i].hint = Q.tryGetText("Db."+ xyzRow.localTextPrefix + "." + items[i].name + "Hint");
            }
It's probably a dirty hack and not the best practice but it works, thanks again.

**Comment by BravoSierra** [comment]
Thanks dfaruque, I appreciate and hope your pull request will make its way.

**Comment by volkanceylan** [comment]
Pull request is merged.

**Comment by fwd079** [comment]
Hi @dfaruque 
This didn't work for Hints unfortunately, I must be missing something here. Things I tried so far:
`

                            var hint = member.GetCustomAttribute<HintAttribute>();
                            if (hint != null && !hint.Hint.IsEmptyOrNull())// && hint is DBHintAttribute)
                            {
                                result.Add($@"Db.{attr.Key}.{member.Name}.Hint");
                                //result.Add($@"Db.{attr.Key}.{member.Name}.Hints");
                                //result.Add($@"Db.{attr.Key}.Hints.{member.Name}");
                                //result.Add($@"Forms.{attr.Key}.{member.Name}.Hints");
                                //result.Add($@"Forms.{attr.Key}.{member.Name}.Hint");
                                //result.Add($@"Forms.{attr.Key}.Hints.{member.Name}");
                                //result.Add($@"Forms.{attr.Key}.Hint.{member.Name}");
                            }
`

Please can you advise?

Regards.

**Comment by BravoSierra** [comment]
Did you try the code I posted above as a workaround?

**Comment by fwd079** [comment]
@BravoSierra  I ended up extending HintAttribute class itself, then grabbed the values off Json file into it and passed to parent.

Regards
