### ISSUE TITLE
Phone number format editor

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4049]
Hi
I would like to create an editor for phone number like following
+91-79-9427870
Any help or available work please.

**Comment by luongnv6** [comment]
Hope can help you:

        [DisplayName("Phone"), Size(50)]
        [MaskedEditor(Mask = "+99-99-9999999")]
        public String NamePhone
        {
            get { return Fields.NamePhone[this]; }
            set { Fields.NamePhone[this] = value; }
        }

**Comment by ms4hafiz** [comment]
@luongnv6
Thank you. So easy did not even thought of it.
