### ISSUE TITLE
Filter user by Permission Key / Roles

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#405]
Hello Volkanceylan,

I have following screens / forms for User Dropdown

1. Institute Screen:
    User Drop down should show only User with "**Institute Admin**" Role / Permission
2. Branches Screen: 
    User Drop down should show only User with "**Branch Admin**" Role / Permission
3. Batches Screen:
    User Drop down should show only User with "**Teachers**" Role / Permission

How can i modify UserRepository.cs for each screen

private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                ????

            }
        }

**Comment by samdubey** [comment]
Please validate my understanding

**OPTION 1**
Copy UserRow and UserRepository for 

InstituteAdminRow and InstituteAdminRepository
BranchRow and InstituteAdminRepository
TeacherRow and TeacherRepository

**OPTION 2**
Writing Dynamic Lookup Script as mentioned in Multi Tenancy Example


**OPTION 3**

Using Mixin you mentioned here
[https://github.com/volkanceylan/Serenity/issues/35](https://github.com/volkanceylan/Serenity/issues/35)

**Comment by volkanceylan** [comment]
There are many ways to do this but what i'd recommend is this: 

Add three expression fields to UserRow, IsInstituteAdmin, IsBranchAdmin, IsTeacher. Write their expressions with SQL EXISTS query e.g. 
Expression("EXISTS(SELECT 1 FROM UserRoles ur WHERE ur.RoleId = 1234 and ur.UserId = t0.UserId)")

You may use roles or permissions, whichever you like, if your Role or Permission IDs might change from DB to DB, also join to Role table and match by string name / key.

Then use FilterField and FilterValue, or CascadeField and CascadeValue with lookup editor.

**Comment by volkanceylan** [comment]
Make sure you add [LookupInclude] to these fields.

**Comment by volkanceylan** [comment]
Also you may write custom editor attributes to make it easier:

```cs
class TeacherEditorAttribute : LookupEditorAttribute {
     public TeacherEditorAttribute() 
          : base("Administration.User")
    {
            CascadeField = "IsTeacher";
            CascadeValue = true
    }
}
```

**Comment by samdubey** [comment]
getting error as

Incorrect syntax near the keyword 'EXISTS'.
Incorrect syntax near the keyword 'AS'.

**Comment by volkanceylan** [comment]
Check syntax please, turn on debug mode and see what is query

**Comment by samdubey** [comment]
**UserRow Class:**
public bool IsAdmin { get; set; }
        [DisplayName("InstituteAdmin"),Expression("EXISTS(SELECT 1 FROM UserRoles WHERE UserRoles.RoleId = 7 and UserRoles.UserId = T0.UserId)")]
        public Boolean IsInstituteAdmin
        {
            get { return (bool) Fields.IsInstituteAdmin[this]; }
            set { Fields.IsInstituteAdmin[this] = value; }
        }
        public bool IsBranchAdmin { get; set; }
        public bool IsTeacher { get; set; }
        public bool IsStudent { get; set; }
        public bool IsParent { get; set; }
        public bool IsPublic { get; set; }


New Field Added to RowFields

public BooleanField IsInstituteAdmin;

Still same issue

**Comment by samdubey** [comment]
I Think i should use CASE WHEN since Exists work after Where Clause

Please correct if i am wrong

**Comment by samdubey** [comment]
Thank you

I was able to Achieve this by Following Code:

[DisplayName("InstituteAdmin"),Expression("(CASE WHEN (SELECT 1 FROM UserRoles WHERE UserRoles.RoleId = (SELECT RoleId From Roles WHERE RoleName='Institute Admin') and UserRoles.UserId = T0.UserId)=1 THEN 'true' ELSE 'false' END)")]
        public Boolean IsInstituteAdmin
        {
            get { return (bool) Fields.IsInstituteAdmin[this]; }
            set { Fields.IsInstituteAdmin[this] = value; }
        }

        [DisplayName("BranchAdmin"), Expression("(CASE WHEN EXISTS(SELECT 1 FROM UserRoles WHERE UserRoles.RoleId = (SELECT RoleId From Roles WHERE RoleName='Branch Admin') and UserRoles.UserId = T0.UserId) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END)")]
        public Boolean IsBranchAdmin
        {
            get { return (bool)Fields.IsBranchAdmin[this]; }
            set { Fields.IsBranchAdmin[this] = value; }
        }

**Comment by volkanceylan** [comment]
Correct i missed that CASE. Why Sql doesnt have a bool type is a mistery though.
