### ISSUE TITLE
Visual Studio Gallery Questions & Answers(demo app) is not working

### ISSUE THREAD

**Issue by controllernet** [volkanceylan/Serenity#4053]
When I open the menu page it gives me this message:

![image](https://user-images.githubusercontent.com/39500865/47996687-200bc480-e0d8-11e8-80c1-53ea2dd907d1.png)

And the grid brings nothing.

**Comment by edwardch** [comment]
I see that Visual Studio gallery is now Visual Studio marketplace so probably the reason for it breaking. 

It's not always easy to pull from an endpoint or API that can change over time, so maybe we need to find an example for the demo that uses an endpoint that might be more consistent.

Github issues, perhaps?

**Comment by volkanceylan** [comment]
Yes, GitHub issues is a fine idea
