### ISSUE TITLE
HtmlContentEditor not showing colors in rendered PDF

### ISSUE THREAD

**Issue by kjaraa** [volkanceylan/Serenity#4054]
Hi all,

I've a **varchar(MAX)** field that is marked with **HtmlContentEditor** attribute, like that:

![cattura](https://user-images.githubusercontent.com/22232670/48057917-81559580-e1b5-11e8-844b-c875ff0ac36e.JPG)

I have to render PDF, so in my .cshtml file I've that:

![cattura](https://user-images.githubusercontent.com/22232670/48058018-b95cd880-e1b5-11e8-9d42-91b65b755a71.JPG)

When I put the text bold or underline, in PDF it works fine, but when I change the color in the editor, it's not working.

How can I solve that?

Thanks for your time :)

Chiara

**Comment by kjaraa** [comment]
UPDATE: I've also changed the attribute in **HtmlReportContentEditor**, but still not working :(

**Comment by volkanceylan** [comment]
HtmlContentEditor or any editor is not intended for printing itself. Your issue is WKHTML/Bootstrap has CSS that prevents color from printing. Color must have !important to print. Don't think you can do it with content from a HTML editor.

**Comment by volkanceylan** [comment]
Your issue is this:
https://stackoverflow.com/questions/33410724/bootstrap-print-css-removes-background-color
Only solution is to remove bootstrap.css

**Comment by volkanceylan** [comment]
Or you might put that content in a iframe

**Comment by volkanceylan** [comment]
You should close issue if resolved.
