### ISSUE TITLE
Grid changed lookupeditor

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#4055]
Merhaba,
Grid tek  Personel Türü diye LookupEditor mevcut onun  elemanlarıda 
Personel,ve Cari dir
ben şimdi Personeli seçitğimde PersonelRowdaki kayıtlar gelmesini istiyorum.
Cari seçtiğimde ise  CariRow daki kayıtların gelmesini istiyorum.
Yardımcı olursanız.
Kolay gelsin.
-----------------
Hello there,
Grid is one of the only Personnel Type of LookupEditor available in his elements
Personnel, and
I would like to see the records on the StaffRow now.
When I select current, I would like to see the records in CariRow.
If you can help.
Good luck with.

**Comment by ga5tan** [comment]
sorry dude, I dont understand EN description.
can u maybe provide some screenshots and try to rephrase EN text?

**Comment by volkanceylan** [comment]
İki ayrı grid yap, bu istediğin olmaz
