### ISSUE TITLE
RAD tool for senernity

### ISSUE THREAD

**Issue by papyr** [volkanceylan/Serenity#4057]
Hi, do you have a RAD tool for serenity, which also has FK object keys with it, similar ABPzero RAD

**Comment by koenmd** [comment]
Hi, I just looked at the documentation for ASPnetzero here: https://docs.aspnetzero.com/documents/zero/latest/Rapid-Application-Development
What it basically does is the same as the sergen tool for Serenity, including foreign keys.
Main difference is that with Serenity you creatie the DB first.

**Comment by papyr** [comment]
hi @koenmd  thanks for the response, I did a search and it said dont use it as graphical GUI for asp core.

![image](https://user-images.githubusercontent.com/12733414/48284405-4eb5d200-e42d-11e8-8d1e-9dce02b25b47.png)

Do you have a link to the latest version. I am happy to try and generate it from the DB.

thanks

**Comment by volkanceylan** [comment]
read the guide.

**Comment by papyr** [comment]
Isnt that what I did from the posted picture. Those comments are from your check-in! but i get your point.

Regardless, for any commercial purchase, if I want to recommend to my client, you _have me wondering, about the quality of support you would provide._
