### ISSUE TITLE
How To Fix : System.InvalidOperationException: 'BasedOnRowAttribute value (....) must be set to a subclass of ....

### ISSUE THREAD

**Issue by lingoontech** [volkanceylan/Serenity#4058]
Hi;

I need help for this error.

Error Image : https://i.hizliresim.com/oVLG0b.jpg

`
namespace IndoorNavigationPortal.IndoorNavigation.Columns
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;
    using IndoorNavigationDB;

    [ColumnsScript("IndoorNavigation.QRInfo")]
    [BasedOnRow(typeof(Entities.QRInfoRow))]
    public class QrInfoColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 QrId { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRName")]
        public String QrName { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRContent")]
        public String QrContent { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRVideo")]
        public String QrVideo { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRVoice")]
        public String QrVoice { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRText")]
        public String QrText { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRImage")]
        public String QrImage { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DXPosition"), AlignRight, Width(200)]
        public Decimal Model3DxPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DYPosition"), AlignRight, Width(200)]
        public Decimal Model3DyPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DZPosition"), AlignRight, Width(200)]
        public Decimal Model3DzPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DXRotation"), AlignRight, Width(200)]
        public Decimal Model3DxRotation { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DYRotation"), AlignRight, Width(200)]
        public Decimal Model3DyRotation { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DZRotation"), AlignRight, Width(200)]
        public Decimal Model3DzRotation { get; set; }
    }
}`

Thank you for help.

**Comment by volkanceylan** [comment]
Error says it all, start by reading the guide.
