### ISSUE TITLE
slow loading lookup

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#406]
Hello,
I have a table with 20,000 records and is used as a lookup.
I know that a lokkup should not contain many elements but imagine in serenity northwind that there are 20,000 customers .

When I open the dialog to try to set the fk of the lookup table , I saw in the profiler that makes the query select * from Entity ( lookup )

questions :
- It is possible to fetch/paging  the query lookup ?
- It is possible load the lookup in lazy loading ?
- Or is there another way in dialog to create combo that reference the lookup table?

I also saw that it could be useful to me your solution indicated in https://github.com/volkanceylan/Serenity/issues/375

Thanks in advance

**Comment by volkanceylan** [comment]
Yes, 375 is the way to go, another lazy load scenario is not possible

**Comment by volkanceylan** [comment]
Btw, why your lookup does select *? It should only include fields required in lookup.

**Comment by linpiero** [comment]
excuse me not consider " * " i was wrong io , in reality " select columns ( lookup includes ) from .....

thanks for your quick response and for you work.

Best regards
