### ISSUE TITLE
Category Translation in Example "Other Form in Tab"

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4060]
Hey there,

I guess it's an easy question, but is there any way to translate the categories in the Basic Sample "Other Form in Tab". If you look on the second Tab the categories wont be translated but the fields will.

Thanks in advance for any help

**Comment by Garozh** [comment]
Ok found it,

you have to set locatTextPrefix of the propertyGrid

**Comment by Mohamed-Ali-Salim** [comment]
hi Garozh
i can't understand your solution.
