### ISSUE TITLE
Error when running sergen

### ISSUE THREAD

**Issue by alphakex2** [volkanceylan/Serenity#4061]
![sergen](https://user-images.githubusercontent.com/3023316/48272189-1b843a80-e44f-11e8-81f7-ee4fdd427b06.PNG)

Kindly help

**Comment by volkanceylan** [comment]
Are you trying to use Sergen UI with .NET Core???

**Comment by alphakex2** [comment]
Thanks for the quick reply....No, I'm running it with the .Net MVC

**Comment by volkanceylan** [comment]
Select correct csproj file then
