### ISSUE TITLE
Can have sample for SqlQuery.Union?

### ISSUE THREAD

**Issue by yaseen-h** [volkanceylan/Serenity#4066]
I tried to use SqlQuery.Union but it failed at sort and filtering

Can have working sample for SqlQuery.Union?

**Comment by minhhungit** [comment]
Hi @yaseen-h  Check test code at here, it might help you
https://github.com/volkanceylan/Serenity/blob/48b7a2135311123f6876b45a553b77b3e8833315/Serenity.Test/Sql/SqlQueryTests.cs#L888

**Comment by volkanceylan** [comment]
Thanks @minhhungit

**Comment by SudhersanT** [comment]
Union() property is not appears in          
   var query = new SqlQuery() object
Is anything want to update ?

**Comment by SudhersanT** [comment]
> Thanks @minhhungit

Union() property is not appears in
var query = new SqlQuery() object
Is anything want to update ?
