### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#4067]
Hi,

Am working on a school project where there are three different tables
1. Class
2. Student
3. Teacher

where class has the foreign key for student and teacher. Here i want to achieve only the list of students with the class assigned for a teacher login. How can i achieve this in serenity with out any SP.

Regards
Srinivas

**Comment by ga5tan** [comment]
this is M:N relation. IMHO simplest is to make view for that and just generate Grid for it.
Otherwise you can generate grid for class table and lookup both Student and Class.
See demo app

**Comment by brunobola** [comment]
You can handle the List handler at the repository level filtered by the user logged in and make your restrictions here.

**Comment by ga5tan** [comment]
aha, sorry my bad. prolly what @brunobola  said.
You can also have behaviour (what I use) to (if lesser user) filter on specific field for logged in user's id
