### ISSUE TITLE
CTE in row definition

### ISSUE THREAD

**Issue by sottnik** [volkanceylan/Serenity#4068]
Is there a possibility to add CTE at the top of the main select of a Row Entity, so we can reference its columns normally as any other column of the RowEntity table?
Of course we can achieve something like that using views but then we would loose the automatically generated update/insert/delete functionality.

**Comment by volkanceylan** [comment]
I don't know what is CTE, but have a look at OuterApply

**Comment by sottnik** [comment]
CTE = common table expression:

```
with t as (
select col1
from t1 
)
select col1, Expression(col1) 
from t2 join t1 on t2.col = t1.col
```

It basically substitutes sub-select written inline in the table list, but there are cases where there is no other viable possibility than CTE.

I am afraid outer apply does not solve my problem. It's different kind of thing. I will investigate how to extend serenity with what I need.

**Comment by volkanceylan** [comment]
I think such things are better to go into a view, but as i replied before, you may use a outer apply to write any SQL statement you need.
