### ISSUE TITLE
Property Grid / Multiple Tabs

### ISSUE THREAD

**Issue by christowers** [volkanceylan/Serenity#407]
Is there a way to break up the propertygrid data over multiple tabs? Or a work around that accomplishes this? Basically I have a dozen or so tabs that represent a single entity. I've used ~_PropertyGrid but this doesn't seem to work across tabs. Any suggestions would be appreciated.

**Comment by volkanceylan** [comment]
Firstly, property grid over tabs wouldn't be so user friendly, as Save button in one tab would confuse user. Categories works similar to tabbed form, they are click navigatable.

Anyway if you are desperate, see how i move note editor to tab in customer dialog.

**Comment by christowers** [comment]
So this is what I am trying to accomplish... I have a legacy system that I am wrapping this around. The main table just happens to contain over 150 fields. In our existing system these fields are displayed across multiple tabs. There is a common toolbar.

I have figured out how to get the common toolbar as well as all tabs. I now need to figure out how to specify which tab a particular Category/Field should be shown on.

It would be best if I can specify this at the category level... I am looking into the source now to see if there is any way I can accomplish this.

Any thoughts?

**Comment by volkanceylan** [comment]
You may find categories by their indexes in form and move them to another div in another tab.

**Comment by christowers** [comment]
Could you please elaborate? Perhaps a simple example?

**Comment by volkanceylan** [comment]
I think i already directed you to an example in Customer dialog. I also explained you that categories are very similar to tabs in functionality. 

I didn't try such a thing yet so how you expect me to give you away something that i don't have. 

 If you want a complete example, you may wait till i add a sample, i'll probably will.
