### ISSUE TITLE
Items are not getting added in Dialog Grid

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4070]
Hello,

I am creating Master Details Relation Example just like Order & Order details in sample.
When I click on New Product in order detials dialog Items is not getting added in Grid dialog in my case.
Can you please tell me what are the steps to make it work any Tutorial for master details relation.

**Comment by TechAspirant** [comment]
I am getting error when clicked on Save in New product Item as below  in my case 
When i refer order detail endpoint and its repository there is not create method 
![image](https://user-images.githubusercontent.com/40688461/48402700-440f7b80-e752-11e8-9129-51ad04538fd0.png)

**Comment by dfaruque** [comment]
remove the following lines for DetailDialog.ts

```
        protected getIdProperty() { return SomeRow.idProperty; }
        protected getService() { return SomeRow.baseUrl; }
```

**Comment by TechAspirant** [comment]
Items are getting added but I can see blank row in Editor Grid.
