### ISSUE TITLE
How can I CHANGE the alert confirm's content?

### ISSUE THREAD

**Issue by WendyBurgerHsu** [volkanceylan/Serenity#4071]
Hi,

I am a new user for Serenity.
I have some problem on Serenity,
I set the UNIQUE KEY on MS SQL (the value is 'section')
If I write the same value again, It will jump out of the alert confirm.

My question is: How can I CHANGE the alert confirm's content?
I want to show 'this is the duplicate name in the column', not the Violation of UNIQUE KEY constraint…

![image](https://user-images.githubusercontent.com/44994587/48398606-3828b700-e75c-11e8-82a6-37bab84736ea.png)

Thanks everyone!

**Comment by ga5tan** [comment]
one way would be to check it on save event in repository....

**Comment by brunobola** [comment]
Here you have: 

```
...
private class MySaveHandler : SaveRequestHandler<MyRow>
{
	protected override void BeforeSave()
	{
		//Do your Stuff HERE
		base.BeforeSave();
	}
}
```

**Comment by WendyBurgerHsu** [comment]
Hi @ga5tan, @brunobola,
I don't use the repository, Just only put the
"[UniqueConstraint("XYZname", CheckBeforeSave = true, ErrorMessage = "Error", IgnoreDeleted = true)]"
in the xyzRow.

I still want to say thank you so much guys :)
