### ISSUE TITLE
Fatura Tasarımı

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#4073]
Merhaba,
Dinamik  olarak  Fatura tasarımı yapabilirmiyiz. yapabiliyorsak nasıl ve örnek var mıdır.(kullanıcı kendisi tasarlaması)
Kolay gelsin.
--------
Hello there,
Can we design the invoice dynamically. (If the user is able to do and how to design the sample.
Good luck with.

**Comment by volkanceylan** [comment]
Malesef.
