### ISSUE TITLE
How to select item in LookupEditor dropdown ?

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#4074]
Hello all,

I have a XYZDialog with a field which has a LookupEditor.
The items of this LookupEditor list are filtered like this :  

```
var lookup = Q.getLookup<Session.CompaniesRow>("Session.Companies");
            this.form.Company.filterField = "UserId";
            this.form.Company.filterValue = this.entity.UserId;
```

When the XYZDialog is loaded, the dropdownlist is filled with the correct items, but
the selected item is "--select--", the placeholder.
My question is, how to select the right item in the dropdownlist programmatically.

**Comment by dfaruque** [comment]
`this.form.Company.value = 'someVal';`

**Comment by GreenUtil** [comment]
Well, I expected the right item to be selected automatically based on the current value. Somehow, this is not happening in this (.NET Core) project. I've got another (.NET MVC) project in which this issue works. So,  I am going to look there and come back later here with the results.

**Comment by GreenUtil** [comment]
In case of not filtering the LookupEditor list, the right value is automatically selected in the dropdownlist. 
Somehow the filtering is causing the issue of not selecting automatically the right value.

**Comment by ga5tan** [comment]
is it possible you filter out value which is needed ?
if not, you may need to reset combo after filtering

**Comment by GreenUtil** [comment]
I tried several ways to reset the combo after filtering, without result.
I am looking for a convenient workaround.
But until then the .NET Core Serene framework doesn't work for me.
It's crucial functionality......

**Comment by ga5tan** [comment]
weird. I would not expect this to be the .NET Core issue, since the combos are some JQuery or JS components...
how do u filter anyway? do u use Cascading? works fine for me (but I use regular .NET)

**Comment by GreenUtil** [comment]
But at a higher level, this JQuery component is driven by .NET Core, isn't it ?
I guess somewhere a trigger is missing or not functioning quite well.....
I read something about the ReactJS shouldComponentUpdate().
Re-render. 
I am not sure if this has something to do with the issue.

**Comment by ga5tan** [comment]
you are right, maybe it;s under-cooked compared to MVC ver. but explicit refreshing should work no matter what. especially if data is already there.
so u r sure you value is still in combo after filtering, right ?

**Comment by GreenUtil** [comment]
The only way to solve this is filtering in the `constructor`.
I made an extra webmethod to retrieve the UserId.
