### ISSUE TITLE
Master-Detail problem when add new master

### ISSUE THREAD

**Issue by TecnologiaCapricornio** [volkanceylan/Serenity#4075]
Hi,

I'm having a problem with a master detail relation. It's a simple relation 
`[MasterDetailRelation(foreignKey: "ItemId", IncludeColumns = "ParametroNome")]`
But It didn't show when inserting, only at updating like the images below

When creating new Master
![add1](https://user-images.githubusercontent.com/44982900/48429992-6a82e600-e755-11e8-93c9-677459f5dfed.PNG)
![add2](https://user-images.githubusercontent.com/44982900/48429994-6c4ca980-e755-11e8-9a0e-e9fd995253a1.PNG)

After save and editing same Master
![add3](https://user-images.githubusercontent.com/44982900/48429997-6d7dd680-e755-11e8-960d-ab1a580c9273.PNG)

**Comment by brunobola** [comment]
You have to handle the validateEntity in your dialogxxx.ts or editorxxx.ts

```
...
protected validateEntity(row: XXXXXRow, id: number) {
	row.field = ...
}
...
```

**Comment by TecnologiaCapricornio** [comment]
I alrealdy have a validateEntity in my editorxxx.ts

`        protected validateEntity(row: Parametros_ItensRow, id: number) {

            if (!super.validateEntity(row, id))
                return false;

            row.ParametroNome = ParametrosRow.getLookup().itemById[row.ParametroId].Nome;
            return true;
        }`

**Comment by brunobola** [comment]
Then just add lookupinclude in your xxxxrow.cs

**Comment by TecnologiaCapricornio** [comment]
I added but no change.
Something I noted... When I dragged the column title just a little bit and released it showed... Is somehow to refresh grid after close the dialog?

**Comment by TechAspirant** [comment]
facing same issue did you resolve ?

**Comment by TecnologiaCapricornio** [comment]
I still haven't solved.

**Comment by ga5tan** [comment]
did u guys tried this?
MinSelectLevel(SelectLevel.List) on missing fields?

**Comment by sottnik** [comment]
yep, it solved for me, a bit inconvenient but works

**Comment by TecnologiaCapricornio** [comment]
I just removed this "auto hide grid" when in a new dialog, in my code it was optional show it, and the default was hidden. When edit this behaviour is locked so it was a problem in new only.

**Comment by volkanceylan** [comment]
After hiding the grid and showing it manually, you'll need to trigger its layout event, or SlickGrid can't size itself.

e.g. this.form.SomeGrid.element.show().triggerHandler('layout') etc
