### ISSUE TITLE
Error in Import Excel

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#4077]
Dear,
Following the steps of the Demo, I created an Excel Import button and classes according to the model (Referred BasicSamples-ProductImportFromExcel ), but clicking the button appears the error below.
![image](https://user-images.githubusercontent.com/7516443/48436250-6eb6ff80-e765-11e8-80ad-db54742bafa4.png)

Debug no chrome
![image](https://user-images.githubusercontent.com/7516443/48436325-90b08200-e765-11e8-83b2-4894d331ab4d.png)

I already ran T4 but it does not resolve, it's as if the script does not generate

How to register the script?

Thank you.

**Comment by ga5tan** [comment]
maybe typo? or check the reference:
/// <reference path="../../../Northwind/Product/ProductGrid.ts" />

**Comment by xuliujian** [comment]
I have encountered the same issue. Finnally, I found out the reason via javascript debugging. In the sample, the namespace does not contain a dot. But if there is a dot in your project namespace, you need to override the formKey in the dialog, like following code:

```
namespace ABaoTuoBi.Admin.WechatMall {
    
    @Serenity.Decorators.registerClass()
    export class CustomerExcelImportDialog extends Serenity.PropertyDialog<any, any> {
        protected getFormKey() { return CustomerExcelImportForm.formKey; }

        protected form = new CustomerExcelImportForm(this.idPrefix);

        .....
    }
}
```

**Comment by juliermefelix** [comment]
Thank you..
I changed the dialog as directed and I had to increase the lines that are marked in yellow.
![image](https://user-images.githubusercontent.com/7516443/48725575-bb8e5080-ec13-11e8-8cca-1dca06323dea.png)
