### ISSUE TITLE
How to Show Dialog with cshtml  and Controller on Button Click ?

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4079]

**Comment by ga5tan** [comment]
check demo, there is dialog opening  all the time
like:

> https://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

but to be honest, most of the dialogs open via cshtml, so maybe I dont understand your Q...

**Comment by TechAspirant** [comment]
I have cshtml page and I want to pass chtml page to dialog when clicked on toolbar button click event

**Comment by minhhungit** [comment]
Put bellow code into your cshtml
```javascript
<script type="text/javascript">
    jQuery(function () {
        var dlg = new YourProject.Default.DemoDialog();
        dlg.loadByIdAndOpenDialog(12345);
    });
</script>
```

**Comment by TechAspirant** [comment]
I have created TestDialog.ts file with below code and added button to toolbar in my parent cshtml page
I am showing my TestDialog.ts on button click event of my created toolbar button from parent cshtml page

Instead of passing html content in template of testDialog I want to pass my child cshtml page as template

```
/// <reference path="../../../scripts/typings/jquery/jquery.d.ts" />
 

namespace MovieTutorial.Test {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class TestDialog extends Serenity.TemplatedDialog<any> {

        protected onDialogOpen() {
            super.onDialogOpen()
        }

        protected getTemplate() {
            $(document).ready(function () {
            $("#btnSave").click(function () {AlertSave();});});function AlertSave() {alert("Alert Message OnClick");}
            return "<button id=\"btnSave\">Save Click</button>";
        }

    }
}
```

**Comment by minhhungit** [comment]
lol

you can create a template cshtml file which has same name with your dialog, for example: **TestDialog.Template.cshtml**

here is template sample:
```html
<div>
    <button type="button" id="~_btnMyButton">Test</button> 
</div>
```
In your dialog, get that button using `this.byId`
for example: 
```javascript
this.byId("btnMyButton").click(e=>{
   // do something
})
```

**Comment by volkanceylan** [comment]
onDialogOpen() {
   super.onDialogOpen();
   this.element.html($.get('/some/page/that/returns/your/html'))
}

**Comment by YYOHAN** [comment]
Hi,
I have a dialog that extends  Serenity.TemplatedDialog and I am able to open it and use a ...Template.html.  but I have to include a particular js file in this Dialog ("Templated"). I would like to take advantage of the bundling capabilities of Serenity framework.


`
@section Head { @Html.ScriptBundle("Pages/MyPageDefinedonScriptBundles")
}
`
How can I use a .cshtml with a TemplatedDialog?
