### ISSUE TITLE
Tips and Tricks

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#408]
Just a thought about adding a Wiki section here on the GitHub repo for like tips and tricks on the Platform. Thoughts?

**Comment by volkanceylan** [comment]
Yes good ide , troubleshooting and how to guides can be put here too

**Comment by wdhodges** [comment]
I'm not sure how you want it set up but I'm willing to help out with it. I'm still learning serenity so I'm not sure how big of a help I can be but hey. I'm willing.

**Comment by wdhodges** [comment]
Another thing that could be potentially added to it is the types of editors that there are. Such as ImageUploadEditor, TextAreaEditor etc.

**Comment by jsbUSMC** [comment]
I can definitely help out with that too. We could also post gists with code snippets for solutions to common or uncommon use scenarios.

**Comment by jsbUSMC** [comment]
For example I modified the base login screen recently and can put up a small guide with the less files I changed and the JavaScript that I used to make it all work. Some of the changes to Serene could be added there as well.

**Comment by volkanceylan** [comment]
Thanks for offering help, i added an initial wiki page with one question there. Can you check if you are able to edit there, or do i need to assign permissions to you?

**Comment by wdhodges** [comment]
I think I can edit but I'm on my mobile so I can't check it. There was a link earlier when I was looking saying to create a page so I think it's open. 

I can help out in anyway I can think of. I'm okay at databases but pretty new to mvc. Should be fun!

**Comment by wdhodges** [comment]
@jsbUSMC I look forward to seeing your tips!

@volkanceylan just checked and editing is open and good to go.

**Comment by zerodev** [comment]
Great effort all looking for that

**Comment by volkanceylan** [comment]
@jsbUSMC just saw your page about login, it looks great, vow!

**Comment by jsbUSMC** [comment]
@volkanceylan Thank you very much! If @JohnRanger wouldn't mind, I would like to also compile his code snippets into the wiki as well for the solutions that he arrives at. I think a huge boost to this community would be to share our workarounds/solutions, so that others can learn and to hopefully ease some of the burden on you and @victortomaili and everyone else who is contributing to helping us out.

**Comment by wdhodges** [comment]
@jsbUSMC wow. that login customization entry. Great job!

I'm going to start a page that lists all of the editor types and what they do. Well atleast the ones that I know of.

**Comment by JohnRanger** [comment]
**@jsbUSMC:** Yes, please compile my code snipplets. That's for what I am posting them here ;-)

**Comment by volkanceylan** [comment]
Thanks to all who added or are adding docs to wiki. We have some very good sample contributions there.
