### ISSUE TITLE
Permission Keys

### ISSUE THREAD

**Issue by Akarsh03** [volkanceylan/Serenity#4080]
I could see a new permission key in permission dialog just by having it in PermissionKeys Class i.e. without using it on any of the attributes like ReadPermission or ModifyPermission, which actually contradicts what you say in the article [https://volkanceylan.gitbooks.io/serenity-guide/howto/how_to_register_permissions_in_serene.html](url) (There is a PermissionKeys class in Serene. Some users expected that when they write their permission keys in this class, they will be discovered.
But, PermissionKeys class is only there for intellisense purposes, it is ignored by Serene.)

Note- I haven't registered it using RegisterPermission attribute as well.

**Comment by volkanceylan** [comment]
We later added a feature to auto add permissions there, doc should be updated.

**Comment by volkanceylan** [comment]
You need to compare source code of ListPermissionKeys methods.
