### ISSUE TITLE
If you create serenity template and in name of project have one or more '.' LanguageLookUp will throw error.

### ISSUE THREAD

**Issue by HairyPloper** [volkanceylan/Serenity#4081]
Core or Base version of SERENE template project if created as "Name.OtherName.Thrid.Web" will cause issue that language lookup script will be not loaded ( created) properly. Name in Registered pool of scripts will be different then its dependencies.
I assume is that generic creation of lookup keys is based on parsing of Namespaces or name of Class.

Workaround (one of two, what suits you more):
1) Hardcode name of lookup script. Administration.Language
2) install or ranme Project(Namespaces) too NameOtherNameThird. will solve your problem.

Just wanted to point on this issue For new people who want to try this template and can`t solve issue.

**Comment by volkanceylan** [comment]
You shouldnt include special chars in project name. Noted in guide.
