### ISSUE TITLE
Lookup value problem

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4083]
Hi
Anyone please if you can help with this

I want to count rows based on a filter that I want to apply.
I have written the following code but it returns 0 value while there is more

                    var id = Serenity.EditorUtils.getValue(this.form.FacilityId)

                for (var k of Regs.TblPatientsRow.getLookup().items.filter(x => x.FacilityId == id)) {
                    totalRows = totalRows + 1;
                }

and when writing the following code, it gives an error:

                    for (var k of Regs.TblPatientsRow.getLookup().items.filter(x => x.FacilityId == this.form.FacilityId.value)) {
                    totalRows = totalRows + 1;
                }
   the error is 

![image](https://user-images.githubusercontent.com/20435849/48631276-ce1e4500-e9db-11e8-94bd-70d58146a501.png)

**Comment by Garozh** [comment]
It should work like this
```
for (var k of Regs.TblPatientsRow.getLookup().items.filter(x => x.FacilityId == Number(this.form.FacilityId.value))) {
                totalRows = totalRows + 1;
```

**Comment by ms4hafiz** [comment]
@Garozh 
Thank you
I tried it but still it is not iterating rows but I am trying to solve the issue through stored procedure.
