### ISSUE TITLE
Set Database Dialect for Connections

### ISSUE THREAD

**Issue by thesnide1** [volkanceylan/Serenity#4084]
Hi Volkan,

I renamed this thread after resolving problem.  I had incorrectly added a Key to the web.config that did not produce an error. Upon reexamining the dialect topic I have discovered that code example is missing the final curly-bracket .

Thank you,

Trent

**Comment by volkanceylan** [comment]
Sorry @thesnide1, where does it miss curly-bracket? In guide? Could you give a link?

**Comment by thesnide1** [comment]
The missing curly bracket is in the guide topic "Set Database Dialect for Connections". [https://serenity.is/Docs/setting-connection-dialect](url)

The picture associated with web.config example has unbalanced curly brackets. There are 3 left brackets and only 2 right brackets.

**Comment by volkanceylan** [comment]
Thanks @thesnide1
