### ISSUE TITLE
Update to 3.8.1 dotnet sergen servertypings exited with code 134

### ISSUE THREAD

**Issue by ckrassas** [volkanceylan/Serenity#4086]
Hello Everyone,

I recently updated from 3.7.7 (dotnet core 2.0) to 3.8.1 (dotnet core 2.1).

After updating Views files and .Web.csproj file I did the following.

dotnet restore (no issues)
dotnet sergen restore (no issues)
dotnet build (issues)

I get the following error at transforming server typings:

```
Transforming ServerTypings at: ***/Imports/ServerTypings

Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=***'
     at ICSharpCode.Decompiler.UniversalAssemblyResolver.ResolveInternal(AssemblyNameReference name)
     at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name)
     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
     at Serenity.Reflection.CecilUtils.FindAttr(IEnumerable`1 attrList, String ns, String name)
     at Serenity.Reflection.CecilUtils.GetAttr(TypeDefinition klass, String ns, String name, TypeDefinition[] baseClasses)
     at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(TypeDefinition type)
     at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll()
     at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll()
     at Serenity.CodeGenerator.ServerTypingsCommand.Run(String csproj, List`1 tsTypes)
     at Serenity.CodeGenerator.Program.Main(String[] args)

 warning MSB3073: The command "dotnet sergen servertypings" exited with code 134.
```

I then tried running dotnet sergen and I get the following error:
``` 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=***'. The system cannot find the file specified.
 
    at Serenity.CodeGenerator.Program.WriteHelp()
    at Serenity.CodeGenerator.Program.Main(String[] args)
```

I've also tried creating a new project using serin and I still have the problem with the new project. It has the same errors.

Removed all SDK's and re-installed latest SDK. I also removed all nuget packages and restored from the beginning. 

Below is the dotnet --info:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

Tried removing all SDK's and clean install 2.1.500 SDK. I also removed all SDK's again and then installed 2.1.403 SDK as below and I am still having the same issue.

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by volkanceylan** [comment]
I guess didn't update Serenity.CodeGenerator, just like several others in prior closed issues, check in CSPROJ, DotNetCliToolReference.

**Comment by ckrassas** [comment]
Thanks for the reply... Just wanted to update you. 

How can I check which version of Serenity.CodeGenerator is being downloaded ??  

Below is the .csproj:
`<DotNetCliToolReference Include="Serenity.CodeGenerator" Version="3.8.1" />`

The first thing I checked was this as I did see it in another issue that was resolved. This was not the case. I also tried the same on my Windows 10 machine and I did not have an issue. I even created a completely new test project to make sure that I did not make a mistake anywhere and even compared files and so on. 

Below is the dotnet --info for my Windows 10 machine:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18282
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
I also completely removed all dotnet from my Mac. Removed all user space folders like ~/.dotnet, ~/.aspnet and anything having to do with dotnet in general. Search the entire machine and removed any and all traces of dotnet. I then deleted my project and cloned it again from my repo. 

Re-installed DotNet Core SDK 2.1.500 only. I went through and did all the steps to get my project to be able to run. 

> dotnet restore
> npm install (local project directory to install all packages)
> dotnet sergen restore (no errors)
> dotnet build (errors - same as above)

Still have issues. I'm starting to think this is related to some other problem - possible related to my mac or maybe it's not downloading the correct dotnet cli tools?

**Comment by volkanceylan** [comment]
Hmm you are building on Mac? OSX?

**Comment by volkanceylan** [comment]
Ok, looks like OSX, i don't have a OSX at the moment. Your issue is probably due to case sensitivity (not sure if so in OSX), or locations of NuGet packages being different than Windows in OSX.

Not sure if i can solve it atm without a Mac, but please share your .json files (deps.json, runtimeconfig.dev.json, runtimeconfig.json), also find Microsoft.Extensions.PlatformAbstractions.dll file in your pc under some folder like 1.1.0.0 and share absolute path to that file.

**Comment by ckrassas** [comment]
I will look into the NuGet package locations on my Mac and will post an update.

Location of Microsoft.Extensions.PlatformAbstractions.dll is C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All\2.1.6

**Comment by volkanceylan** [comment]
Seems like this can't be solved without releasing a new version. For now, please try creating a ".nuget" folder in your home (profile) directory, and a "packages" folder inside it, and copy files from /usr/local/share/dotnet/shared/ there. You might also create a symlink i think

**Comment by ckrassas** [comment]
Already a .nuget/packages folders within my home directory. Attached is the directory listing.
[Nuget-Packages.txt](https://github.com/volkanceylan/Serenity/files/2605668/Nuget-Packages.txt)

If there is a workaround I would be more than happy to use it so I can actually get working again.

**Comment by volkanceylan** [comment]
You should copy folders for missing packages that build complains, from usr local share dotnet to there.

**Comment by ckrassas** [comment]
Thank for your help. In order to Resolve the issue I copied the packages the build complained and everything worked! 

From Folder: `/usr/local/share/dotnet/sdk/NuGetFallbackFolder/`
To: `~/.nuget/packages` 

Thanks again for the quick workaround!

**Comment by Elypsia** [comment]
Hi @volkanceylan  here too it's blocking us.

**Comment by volkanceylan** [comment]
@minhhungit, @Elypsia this issue was about Mac OSX, not Windows

Your problem is probably not updating DotNetCliToolReference in your .CSPROJ file.

**Comment by minhhungit** [comment]
`dotnet sergen g`  (without minus sign) // THIS WORK

**Comment by volkanceylan** [comment]
Minus sign was never supposed to be there :)
