### ISSUE TITLE
Errors in react (index.d.ts) and prop-types (index.d.ts)

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4088]
Hey everyone,

after updating Serenity to 3.8.1 and following the Upgrade Guides I still have problems with the react and prop-types index.d.ts files. They give me errors like some reference is missing for those files, but I just got them automatically by updating my package.json file like I read in the Upgrade guide.

`  "dependencies": {
    "@types/jquery": "^2.0.39",
    "@types/jquery.blockui": "0.0.27",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jquery.validation": "^1.13.32",
    "@types/jqueryui": "^1.11.32",
    "@types/jspdf": "^1.1.31",
    "@types/sortablejs": "^1.3.31",
    "@types/toastr": "^2.1.33",
    "@types/react": "^16.1.0"
  },`

My first error in prop-types (index.d.ts) is the following code line (line 27), where "the name unique wasn't found"

`export const nominalTypeHack: unique symbol;`

Do I need some reference to something or what am I missing here?

Thanks for any help in advance.

**Comment by ga5tan** [comment]
did u try to build and transform all ?
maybe clean solution before ?

**Comment by volkanceylan** [comment]
Have you installed VS 2017 latest update, all settings in Install.md file at root etc.

**Comment by Garozh** [comment]
I have cleaned, builded and transformed multiple times without any success and I also have the latest version of VS2017 installed. Not sure where to check "Install.md", because I cant find that file

**Comment by volkanceylan** [comment]
Try setting Content Type of your tsconfig.json to Content in VS properties window. Install.md is here:

https://github.com/volkanceylan/Serenity/blob/master/INSTALL.md
