### ISSUE TITLE
Check the same columns

### ISSUE THREAD

**Issue by WendyBurgerHsu** [volkanceylan/Serenity#4092]
Hello everyone,

Like this pic, I already have "ACCT Account Manager", but still can save the same one.
How can I use the method to confirm that the data column does not have the duplicate data?

![image](https://user-images.githubusercontent.com/44994587/48936378-ba2b9380-ef45-11e8-8ac8-e5099d7aa0e3.png)

Thanks everyone!

**Comment by Zahar661** [comment]
In xyzRow.cs
[Unique]

**Comment by hubeyb** [comment]
You can use UniqueConstraint attribute at the top of the row class.

  ```
  [UniqueConstraint("Url", ErrorMessage = "you can not use sam url!")]
    public sealed class ModuleRow : LoggingRow, IIdRow, INameRow
```

**Comment by WendyBurgerHsu** [comment]
Hi @Zahar661, @hubeyb,

I think I did not explain my needs.
My need is to determine if there is a duplicate value for this column.
Like ID 1, there are already ACCT (Department) and Account Manager (Job Title) in this column, so I can't add it.
However, if there is no Cashier in ACCT(Department), you can still add it.

How can I do this?  Thanks!!

**Comment by WendyBurgerHsu** [comment]
By the way, the other Departments(like Sales) can choose Cashier, too.

**Comment by Zahar661** [comment]
In xyzRepository.cs
in MySaveHandler : SaveRequestHandler<MyRow>
```
protected override void ValidateRequest()
            {
                base.ValidateRequest();
                var f = MyRow.Fields;
                var d = Connection.First<MyRow>(f.DepartamentId == Row.DepartamentId & f.JobId == Row.JobId);
                if (d != null) throw new ValidationError("InvalidMyRow", "UniqueDepartamentIdAndJobId",
                                  "My error message");
            }
```

**Comment by edwardch** [comment]
@WendyBurgerHsu you'll probably also want to enforce uniqueness at the database level.

If your table was named "Positions" then you'd create a migration that looked something like this:
```cs
Create.UniqueConstraint("UQ_Positions_DepartmentId_JobTitleId")
    .OnTable("Positions")
    .Columns("DepartmentId", "JobTitleId");
```

**Comment by WendyBurgerHsu** [comment]
Hi @Zahar661,
I used your method, but there was another new problem....
If I choose the same value, it will appear "My error message".
It's perfect!  but if I choose the different value it will appear
**"Serenity.Services.ValidationError: 'Query returned no results!"**
How can I fix this error?
This is my code:

`
protected override void ValidateRequest()
            {
                base.ValidateRequest();
                var f = MyRow.Fields;
                if (IsCreate)
                {                    
                    var d = Connection.First<MyRow>(f.DeptId == Convert.ToInt32(Row.DeptId) & f.JobId == Convert.ToInt32(Row.JobId));
                    if (d != null)
                        throw new ValidationError("DeptJobRpw", "UniqueDeptIdAndJobId", "My error message");
                    else
                        return;
                }
            }
`

I want to try "return new SaveResponse()"
But It can not work..

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/49274528-19336000-f492-11e8-9287-ee54dcc6230a.png)
