### ISSUE TITLE
reloadLookup need to go to DB

### ISSUE THREAD

**Issue by ninoraccoon** [volkanceylan/Serenity#4095]
Hello, I know that to reload lookup whit expiration -1 always reload from db and not from cache, exist a way that use cache and in specific scenarios reload from db?.
Greetings!!!

**Comment by Zahar661** [comment]
if (Q.getLookup("Uchet.Dogovora").itemById[entity.DogovorId] == null) Q.reloadLookup("Uchet.Dogovora");

**Comment by brunobola** [comment]
use this: https://github.com/volkanceylan/Serenity/blob/master/Serenity.Services/RequestHandlers/Helpers/BatchGenerationUpdater.cs

**Comment by ninoraccoon** [comment]
Thanks  @brunobola !!! for the tip it fit me!!!
