### ISSUE TITLE
Permission key issue - even the provided sample not working

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4096]
Hi 
I am going to apply permission using permission keys.
I have written all the keys like following 
 
            public class Sample
        {
            public const string Insert = "Db:Sample:Insert";
            public const string Update = "Db:Sample:Update";
            public const string Delete = "Db:Sample:Delete";
            public const string View = "Db:Sample:View";
        }

Created a new user and granted full permission to all including **Administration** but the the main menu header is show and sub-menus are not showing excluding the admin.
![image](https://user-images.githubusercontent.com/20435849/48968407-e8c07180-f00c-11e8-9061-89aa1bbee348.png)

Any idea please

**Comment by hubeyb** [comment]
Please give us your Row property code with used this permissions.

**Comment by ms4hafiz** [comment]
Here is part of the row code.
    
    [ConnectionKey("Default"), Module("Configs"), TableName("[dbo].[TblEducation]")]
    [DisplayName("Education"), InstanceName("Education")]
    [ReadPermission(TblEducation.View)]
    [ModifyPermission(TblEducation.Update)]
    [InsertPermission(TblEducation.Insert)]
    [DeletePermission(TblEducation.Delete)]
    [LookupScript("Configs.TblEducation")]
    public sealed class TblEducationRow : Row, IIdRow, INameRow
    {

        [DisplayName("Eid"), Column("EID"), PrimaryKey]
        public Int32? Eid
        {
            get { return Fields.Eid[this]; }
            set { Fields.Eid[this] = value; }
        }

        [DisplayName("Education Dari"), Size(50), NotNull, QuickSearch]
        public String EducationDari
        {
            get { return Fields.EducationDari[this]; }
            set { Fields.EducationDari[this] = value; }
        }

**Comment by Zahar661** [comment]
[assembly: NavigationLink(10, "Plan/Manager", typeof(MyPages.PlanWorkControlController), icon: null,Permission = "PlanWork/Manager")]

**Comment by ms4hafiz** [comment]
@Zahar661
Thank you I will try this.
