### ISSUE TITLE
CKeditor

### ISSUE THREAD

**Issue by Roeligan** [volkanceylan/Serenity#4097]
Hi,

How to add plugins to CKEditor?  
I read it doesn't work through the config.js, but when using the template (thus not the sourcecode), I see no option to override?
Looking to (re)add the image upload functionality for instance.
Any particular reason it is explicitly left out?
Can the HtmlContentEditor be overriden (once again, when using the template, not the sourcecode) in some way to allow those features of inline image upload (and thus storing of the actual image)?

Using latest updates if it matters...

**Comment by Roeligan** [comment]
quick update:
I managed to create a new editor, based on code from serenity.core, and seems to work.
Just want to know if I should be able to override the default htmlcontenteditor or create a new one like I do know.  And if I can override, how to exactly (if it is possible, I'm clearly missing something...)

**Comment by volkanceylan** [comment]
There are several editor samples here, including HtmlContentEditor derived ones:

https://github.com/volkanceylan/Serenity/blob/master/Serenity.Scripts/CoreLib/UI/Editors/Editors.ts

And StartSharp has mail client sample which supports pasting images on CK editor.
