### ISSUE TITLE
Stacked in passing lookup value to stored procedure using serenity

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4098]
Hi;

I have wrritten the following code in xxEndpoint.cs to run a stored procedure.

             public int Runprocedure(IDbConnection connection)
        {
            connection.Execute("UpdateNumbers",
               param: new
               {
                   ProductId = ProductId
               }, commandType: CommandType.StoredProcedure);
            return 0;
        }

Now I am calling it fro xxDialog.ts. I have written the following but don't know how pass the lookup value to the stored procedure.

         Q.serviceRequest(ProductService.baseUrl + '/Runprocedure');

**Comment by ms4hafiz** [comment]
@Zahar661 
Thank you

**Comment by chrisomeara** [comment]
hi there - I have been searching through the wiki but can't get to a solution on this so any help would be greatly appreciated, I am trying to pass the Id of a record on a dialog through to a stored procedure (MySQL)  but after many attempts and variations on the above and other SP related posts I am now unable to get even close to to a result. 

Like the above issue #4098 I am not expecting a result returned back to the user, just trigger a bunch of code on the server.

My difficulty relates to passing the parameter from the dialog to the endpoint, with the above example "Parameter1:" and "Parameter2:" not making much sense to me in relation to the parameter  "ProductId = ProductId" in the endpoint, see one of my many interpretations below in the screenshots

[Dialog onClick]
![image](https://user-images.githubusercontent.com/60803408/90381003-5cdb5c80-e0af-11ea-92f7-31c8ded10a6c.png)

[Endpoint] - the project will not rebuild with this error
![image](https://user-images.githubusercontent.com/60803408/90383224-6a461600-e0b2-11ea-94da-f91d79f25cf5.png)


[Endpoint] - if the parameter is hard coded, the below warning message is returned
![image](https://user-images.githubusercontent.com/60803408/90383122-484c9380-e0b2-11ea-933b-7b7ea04d5c90.png)

[Error when the button is clicked on hard-coded parameter]
![image](https://user-images.githubusercontent.com/60803408/90382064-d7f14280-e0b0-11ea-88a5-f813f788d2dc.png)

**Comment by Zahar661** [comment]
@chrisomeara  Hi!
EndPoint add request
![image](https://user-images.githubusercontent.com/26430136/90393690-4da1e200-e0a2-11ea-82c8-463e30787a1b.png)
![image](https://user-images.githubusercontent.com/26430136/90393738-63170c00-e0a2-11ea-92cf-6db7be78d211.png)

in Dialog onClick
![image](https://user-images.githubusercontent.com/26430136/90393876-a1acc680-e0a2-11ea-85a2-c136266b020f.png)

**Comment by Zahar661** [comment]
[Error when the button is clicked on hard-coded parameter]

I won't help here. I do not use stored procedure

**Comment by chrisomeara** [comment]
> [Error when the button is clicked on hard-coded parameter]
> 
> I won't help here. I do not use stored procedure
thanks @Zahar661 - very fast response and all the tools to lead me to the answer!

[Endpoint] - note I got the call to the SP working without the number of args error via a SQL execution - I suspect a MySQL thing
![image](https://user-images.githubusercontent.com/60803408/90400683-696fad00-e0cf-11ea-89ed-48a28a552c26.png)

[ServiceRequest] - added that to the existing XYZmodel.cs from the bulk action request demo example!  
![image](https://user-images.githubusercontent.com/60803408/90400858-b6ec1a00-e0cf-11ea-9925-2c990ec4c7af.png)

[Dialog] - a little more work here for me on refreshing the dialog and grid
![image](https://user-images.githubusercontent.com/60803408/90400934-d4b97f00-e0cf-11ea-90c0-90216fb9ae42.png)

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/90415120-b2b90000-e0c1-11ea-971f-46c234119821.png)
![image](https://user-images.githubusercontent.com/26430136/90415306-f4e24180-e0c1-11ea-9f62-b28f889575be.png)
![image](https://user-images.githubusercontent.com/26430136/90415350-04618a80-e0c2-11ea-8549-6bb93f49172d.png)
![image](https://user-images.githubusercontent.com/26430136/90415453-278c3a00-e0c2-11ea-8000-ddbc05b8081f.png)
