### ISSUE TITLE
User type

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4099]
In my application I have 3 user type : A , B,. C.
In relation to user type I have to do various type of action.
How do I identify the type of action?
Thanks.
Simone

**Comment by Zahar661** [comment]
At what event? How are you organized types?
if ... else if .... else if...    not suitable?

**Comment by simonespagna** [comment]
If A
e.if B else
else C
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno lun 26 nov 2018 alle ore 11:32 Игорь <notifications@github.com>
ha scritto:

**Comment by Zahar661** [comment]
where do you want to determine the type?
Do you know what you want?

**Comment by simonespagna** [comment]
In xxxRepository.
Ciao,
Simone
*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno lun 26 nov 2018 alle ore 11:52 Игорь <notifications@github.com>
ha scritto:

**Comment by simonespagna** [comment]
How to translate in Sql for Serenity the following statements?

1 )SELECT IdProprietario FROM[VisibilitaAssociazione] A INNER
JOIN[dbo].[Terreni] B ON A.[IdTerreno] = B.[IdTerreno]
2)SELECT IdProprietario FROM[dbo].[AgronomiTerreni] A INNER
JOIN[dbo].[Terreni] B ON A.idTerreno = B.IdTerreno
Thanks,




*Simone Spagna*
*CEO *
*Omnialan di S&S SRLS ITC Unipersonale*
Via Chiesanuova 17
46100 Mantova (MN)
http://www.omnialan.it - Http://www.omnialanstore.it


Il giorno lun 26 nov 2018 alle ore 16:24 Chad Burnett <
notifications@github.com> ha scritto:

**Comment by Zahar661** [comment]
https://serenity.is/docs/tutorials/movies/movies Learn this lesson and you will understand.
