### ISSUE TITLE
Upgrading from version 1.9.19 to 1.9.24

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#410]
Getting this error while upgrading:

Package 'Serenity.Core 1.9.24' does not exist in folder 'C:\ngs-projects\LCBudgetsProduct\packages'
Update-Package : Response status code does not indicate success: 404 (Not Found).
At line:1 char:15
+ Update-Package <<<<  Serenity.Web
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Is it possible to go directly from .19 to .24 or do I have to install .20 first?

**Comment by volkanceylan** [comment]
Its probably an issue with nuget v3 server. Try adding v2 server as package source.

**Comment by c9482** [comment]
Yes, that was it - thanks. Adding new packages source "https://www.nuget.org/api/v2" fixed the issue.
