### ISSUE TITLE
Problem in code that resolve user 

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4102]
I have a error in this statement 
readonly VisibilitaAssociazioneRow.RowFields fldVisibilitaAssociazioneJoin = VisibilitaAssociazioneRow.Fields.As("jIdProprietario");

referring to this row definition:
 ```
public sealed class TerreniRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id Terreno"), Identity]
        public int? IdTerreno
        {
            get { return Fields.IdTerreno[this]; }
            set { Fields.IdTerreno[this] = value; }
        }
        
        [LookupEditor(typeof(ProprietariLookup))]
        [DisplayName("Id Proprietario"), NotNull, ForeignKey(typeof(AnagraficaUnicaRow), "IdAnagrafica"), LeftJoin("jIdProprietario")]
        public int? IdProprietario
        {
            get { return Fields.IdProprietario[this]; }
            set { Fields.IdProprietario[this] = value; }
        }

        [DisplayName("Descrizione"), Size(50), NotNull, QuickSearch]
        public string Descrizione
        {
            get { return Fields.Descrizione[this]; }
            set { Fields.Descrizione[this] = value; }
        }
```
For example how can code the following Sql in serenity syntax ;
1)SELECT IdProprietario
FROM[VisibilitaAssociazione] A INNER JOIN[dbo].[Terreni] B ON A.[IdTerreno] = B.[IdTerreno]
2)SELECT IdProprietario
FROM[dbo].[AgronomiTerreni] A INNER JOIN[dbo].[Terreni] B ON A.idTerreno = B.IdTerreno
Thanks,

Thanks,
Simone

**Comment by volkanceylan** [comment]
See the guide, no inner join in Serenity rows by default.
