### ISSUE TITLE
Grandchildren or Master/Details/SubDetails?

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4103]
Is there a way to define "Grandchildren" or "DetailsDetails" in the Form definition?

What I am referring to is something like the "OrderForm.cs" page in the Northwind Sample.

Lets say I had a Table that was the "Child" of "OrderDetails" and on the Order Form (Edit) page, I want to include those Rows.

Even better, would be the ability to include those "OrderDetailsDetails" Rows "indented" under each of the "Details". (I would also expect a "New Details" button to be built by the "scaffolding", if this works like I expect.)

I guess what I am asking is does the scaffolding/"conventions"/etc "support" a 3 level Hierarchy? It definitely supports 2 (Mater/Detail... Parent/Child...) But, I haven't tried to see if it will go one level deeper.

Thanks for any advice!

**Comment by dfaruque** [comment]
Yes, serenity supports multi-level hierarchy in master details.
Just define the OrderDetailsDetails in OrderDetails. 
Like OrderDetails in Order
