### ISSUE TITLE
QuickFilter items list filtered

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4105]
Hi all,

![image](https://user-images.githubusercontent.com/28645113/49157481-28929c00-f320-11e8-883b-b16d40016e45.png)

I would like to get only Janet, Nancy, Margaret and Michael is the employee QuicksFilter selection list. Has your can see, the complete list of employees is returned when we edit Alfreds customer row.

**Comment by minhhungit** [comment]
Not sure which way is the best, normally I create a custom lookup `MyCustomLookup`, after that I can have a custom lookupKey (CustomLookup.MyCustomLookupAbcXyz) and place it into custom quickfilter at client side

```csharp
[LookupScript("CustomLookup.MyCustomLookupAbcXyz", Expiration = -1, Permission = "*")]
public class MyCustomLookup : Serenity.Web.LookupScript
{
    public GridPrefixCodeLookup()
    {
        this.IdField = "ProductId";
        this.TextField = "ProductName";
        this.getItems = this.GetItems;
    }

    protected virtual IEnumerable<dynamic> GetItems()
    {
        using (var con = new SqlConnection(YOUR_CONNECTION))
        {
            var p = ProductRow.Fields.As("p");			

            var query = new SqlQuery()
                .Select(bpea.ProductId)
                .Select(bpea.ProductName)
                .From(p)
                .Where(new Criteria(p.ProductName) == "Janet");

                return con.Query(query);
        }
    }
}
```

**Grid.ts**
```javascript
getQuickFilters(): any {
    var filters = super.getQuickFilters();

    filters.push({
        field: fld.ProductId,
        type: Serenity.LookupEditor,
        title: "Product",
        cssClass: "quick-filter-width-250",
        options: {
            lookupKey: "CustomLookup.MyCustomLookupAbcXyz"
        }
    });

    return filters;
}
```

Hope it works for you

**Comment by fremar83** [comment]
Hi Jin,
I had that approach in mind. Thank's for your quick answer and sharing !
I'll try it very soon and will make a feedback.

**Comment by fremar83** [comment]
@minhhungit 
Hi, sorry for the delay. I had to manage other process before.
Hi tried this solution but I don't know how to pass parameter on "Criteria" on your solution.
In your example, you placed "Janet". To answer to my question, we should have a where as
.Where(new Criteria(p.CustomerID) == @MyParam);

**Comment by minhhungit** [comment]
unlucky, currently lookup does not support parameter, you have to hardcode it.
or trying to remove lookup item at client side, something like this:
```
afterLoadEntity() {
	super.afterLoadEntity();

	var filteredProducts: Serenity.Select2Item[] = [];

	this.form.ProductId.items.forEach(prod => {
		if (this.exitedProductIds.indexOf(Q.toId(prod.id)) === -1) {
			filteredProducts.push(prod);
		}
	});

	this.form.ProductId.items = filteredProducts;
}
```

**Comment by fremar83** [comment]
Maybe using a stored procedure would be less cost effective ?

**Comment by fremar83** [comment]
I'm talking about stored proc because I have some other quickFilter I would like to apply a quiet heavy filter to its list. But maybe another way server side could do the job ?

**Comment by minhhungit** [comment]
Try this one:

// Create a custom editor, call service with your parameters, keep an eye on `async`

```typescript
@Serenity.Decorators.registerEditor()
    export class MyTestEditor extends Serenity.Select2Editor<any, any> {
        constructor(hidden: JQuery) {
            super(hidden, null);

            YourService.CallSomething({yourParameter: "value"}, response => {
                response.Entities.forEach((item) => {
                    this.addItem({ id: item.Id.toString(), text: item.Name });
                });
            }, { async: false, blockUI: true });
        }
    }
```
// On Grid.ts
```typescript
constructor(container: JQuery) {
    super(container);

    this.addQuickFilter({
        field: fld.YOUR_FIELD,
        type: MyTestEditor,
     });

    var customFilter = this.findQuickFilter(MyTestEditor, fld.YOUR_FIELD);
    customFilter.value = "2";
}
```

**Comment by fremar83** [comment]
Thank's ! I try it right now !!

**Comment by minhhungit** [comment]
@fremar83  Another option, you can extend an editor from **Select2AjaxEditor**.
It will load data for filter by web service with parameters

**Comment by fremar83** [comment]
Hi Jin! Thanx for your interest!
I'm working on an approach that combine your suggestion and Volkan example (CustomerGrossSales Stored proc). Here is what I did 
First of all, some explanations ... My need is to populate a employe dropdown select in a form with a list of employes of an organization "A" + employes of organizations witch are partners in the project of "A".
My SP is quiet simple but requires 1 param (Project code ).

```
select Employe.* from Employe 
left join 
Partenaire on Employe.Organisation_code = Partenaire.Organisation_code where Partenaire.Projet_code = @p1
union
select Employe.* from Employe
left join
Projet on Employe.Organisation_code = Projet.Organisation_code where Projet.codeProjet = @p1
```
It returns an standard (but filtered) Employe list.

As suggested in Example, I created a request in a separate file 

```
using Serenity.Services;
using System;

namespace AppDpCarto.Modules.DpCarto.Employe
{

    public class EmployesDuProjetRequest : ListRequest
    {
        public Int32 ProjetCode_StoredProc { get; set; }
    }
}
```
I Created a new list in Employe repository (In the example it was a specific repository but as I return EmployeRows, use of its repository makes sense.
so, on EmployeRepository.cs
```
public ListResponse<MyRow> EmployesDuProjetList(IDbConnection connection, EmployesDuProjetRequest request)
        {

            var data = connection.Query<MyRow>("EmployesDuProjet",
                   param: new
                   {
                       codeProjet = request.ProjetCode_StoredProc,
                   },
                   commandType: System.Data.CommandType.StoredProcedure);

            var response = new ListResponse<MyRow>();
            response.Entities = (List<MyRow>)data;
            return response;
        }
```
On EmployeEndpoint.cs
```
[HttpPost]
        public ListResponse<MyRow> EmployesDuProjetList(IDbConnection connection, EmployesDuProjetRequest request)
        {
            return new MyRepository().List(connection, request);
        }
```
Now, I'm working on the calling of EmployesDuProjetList. Your Select2Editor suggested is what I wanted to use. But I don't now what to place at "MyService.CallSomething"
Do I have to create a service (like MeetingAgendaService in Volkan example) ?

**Comment by minhhungit** [comment]
YourService.CallSomething = DpCarto.EmployeService.EmployesDuProjetList()

normally EmployesDuProjetList will be generated by t4 template, find it and call it like this:

```typescript
DpCarto.EmployeService.EmployesDuProjetList({ProjetCode_StoredProc: "value"}, response => {
    response.Entities.forEach((item) => {
        this.addItem({ id: item.Id.toString(), text: item.Name });
    });
}, { async: false, blockUI: true });
```

**Comment by fremar83** [comment]
Yes! I found it just few minutes before you return (T4 transform had to be executed) . Thanx !
Now, I'm considering the addQuickFilter
As I use my select in a ProjetManagerEditForm, I have to place this add in an existing  projetctManagerEditor (GridEditorBase)
ProjectCode is passed from Project Dialog to ProjectManagereEditor. Works well.
So, in my Editor, I get
```
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace AppDpCarto.DpCarto.Editors {
    @Serenity.Decorators.registerEditor()
    export class ResponsableProjetEditor
        extends Common.GridEditorBase<ResponsableProjetRow> {
        protected getColumnsKey() { return "DpCarto.EditResponsableProjet"; }
        protected getLocalTextPrefix() { return ResponsableProjetRow.localTextPrefix; }
        protected getDialogType() { return ResponsableProjetEditDialog }

        PassageCodeProjet: number;

        constructor(container: JQuery) {
            super(container);
            
            this.addQuickFilter({
                field: EmployeRow.Fields.CodeEmploye,
                type: EmployesDuProjetEditor,
            });

            var customFilter = this.findQuickFilter(EmployesDuProjetEditor, EmployeRow.Fields.CodeEmploye);
            customFilter.value = this.PassageCodeProjet;
        }

        protected getAddButtonCaption() { return "Ajouter un responsable de projet" }
    }
}
```
VS informes me that Custom.value required string type. Were am I wrong ?

**Comment by minhhungit** [comment]
I guess you can use this.PassageCodeProjet.ToString()

**Comment by minhhungit** [comment]
@fremar83 value of filter is string, so you have to cast it from number to string

**Comment by fremar83** [comment]
I'm sorry but I don't get it! 
Is value of filter string "by design" or just because I'm wrong somewhere ?
parameter in the stored proc has to be int (it is the project ID key)

**Comment by minhhungit** [comment]
As I know it worked like it was designed

Lookup data are key/value pairs
- key is string
- value is string
- lookup editor value is string (customFilter.value) // always for now

But parameter of web service is difference

> DpCarto.EmployeService.EmployesDuProjetList({ProjetCode_StoredProc: 12345}

here, in your example, `ProjetCode_StoredProc` will receive INT value, it depends on type of variable which you defined in c# class 
```csharp
public Int32 ProjetCode_StoredProc { get; set; }  // Int32 
```

Summary, you just need to cast your value to a "string" value when you want to set the value to lookup editor

**Comment by fremar83** [comment]
OK, I get it !! I was affraid to have to cast this string value somewhere else manualy.
Many thank's to you for your kind help on all that stuff !
I have a problem passing ProjectCode parameter within the customFilter. I don't want to bother you so. I'm going to figure it out and will give you feedback ASAP.
kind regards

**Comment by minhhungit** [comment]
@fremar83  You're welcome

**Comment by fremar83** [comment]
Hi Jin (and other readers),
I made some research et tests (all the Stored proc is running and the rigth list is returned) but i'm in front of a question on addQuickFilter.
My code on the grid is 
```
 constructor(container: JQuery) {
            super(container);
            this.addQuickFilter({
                field: fld.CodeEmploye,
                title: "Filtre Test",
                type: EmployesDuProjetEditor,
            });
        }
```
(by the way, how can I had colors on my preview code ?)
 How can I pass the project code to the EmployeDuProjetEditor (here is the code)
```
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace AppDpCarto.DpCarto.Editors {
    @Serenity.Decorators.registerEditor()
    export class EmployesDuProjetEditor extends Serenity.Select2Editor<any, any> {

        CodeProj: number;

        constructor(hidden: JQuery) {
            super(hidden, null);

            EmployeService.EmployesDuProjetList({ ProjetCode_StoredProc: this.CodeProj }, response => {
                response.Entities.forEach((item) => {
                    this.addItem({
                        id: item.CodeEmploye.toString(),
                        text: item.NomEmployeEtOrga
                    });
                });
            }, { async: false, blockUI: true });
        }
    }
}
```

**Comment by fremar83** [comment]
@dfaruque 
Thank's !
My code will be more comprehensive for others now !!

**Comment by fremar83** [comment]
Regarding to other issues et wikis, it seems dymanics params on stored proc can't be sent. Am I wrong ?

**Comment by fremar83** [comment]
The only way  I found was to use an SQL view and make a specific row (as found in customerGrossSales sample) and then use a filterValue on my QuickFilter. I guess there is another simplest way to acheave my request. As anyone found a way ?
