### ISSUE TITLE
How to access Texts in using typescript

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4106]
Hi 
I would like to access the following in xxDialog.ts and display as message. My aim is to display translated text to user of the current language. For example I would like to access **AcceptTerms** from the following Texts.ts file or anyway to access it.
 
 
                namespace SignUp {
                export const AcceptTerms: string;
                export const ActivateEmailSubject: string;
                export const ActivationCompleteMessage: string;
                export const BackToLogin: string;
                export const ConfirmEmail: string;
                export const ConfirmPassword: string;
                export const DisplayName: string;
                export const Email: string;
                export const FormInfo: string;
                export const FormTitle: string;
                export const Password: string;
                export const SubmitButton: string;
                export const Success: string;
            }
        }

**Comment by dfaruque** [comment]
`Q.text('some.text.key')` this will return translated text

**Comment by ms4hafiz** [comment]
@dfarugue
Thank you 
It works as expected.
