### ISSUE TITLE
Row ' a  runtime   attribute ekleme

### ISSUE THREAD

**Issue by YunusV** [volkanceylan/Serenity#4107]
Merhaba,
Row daki bi alan  runtime  attribute eklemek istiyorum.Ornek
![image](https://user-images.githubusercontent.com/26811084/49223250-4a0e8900-f3ef-11e8-8f4f-c7e572915414.png)
--
Hello there,
I want to add a field runtime attribute in Row.

**Comment by ga5tan** [comment]
If it's in DB just add it same way all the other fields are. in Row and in Fields.
If it's not in DB, then just give it NotMapped attribute.
that's all
