### ISSUE TITLE
Change the name of button

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4109]
Hi.

 I want to change the name of one button in one specific form, is it possible? or if I change it in one side it will affect all the others form?
Can anyone helps me or gives me an advice on how to do it?
Thanks.

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serenity/issues/3340

**Comment by Shraddha996** [comment]
thanks, @Zahar661  for the quick reply 
But I want to change the text of my **Update button** from the Dialog box.
It would be great if  you suggest something

**Comment by Zahar661** [comment]
Change the class
var btn = Q.first(buttons, x => x.cssClass == "update-button");
btn.title = "My new Text";

**Comment by Shraddha996** [comment]
I just tried this code in my dialog.ts file

protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();
            var btn = Q.first(buttons, x => x.cssClass == "tool-button save-and-close-button");
            btn.title = "Lock MRP";
            return buttons;
        }

but it showing error
![capture55](https://user-images.githubusercontent.com/39983941/49274981-ff007e80-f49f-11e8-87ac-391c5a843675.PNG)

**Comment by Zahar661** [comment]
```
protected updateInterface(): void {

        super.updateInterface();

        this.applyChangesButton.text="Lock MRP"
        }
```

**Comment by Shraddha996** [comment]
Thank you so much @Zahar661 
This is Perfect !
