### ISSUE TITLE
Problem with user right

### ISSUE THREAD

**Issue by simonespagna** [volkanceylan/Serenity#4110]
I have a problem like this 
![image](https://user-images.githubusercontent.com/11132633/49277113-d6b55780-f480-11e8-87b7-e70f7879116c.png)
How can I solve it?
The field rules are : 
![image](https://user-images.githubusercontent.com/11132633/49279381-9c9b8400-f487-11e8-9e84-25db99c73287.png)
Thanks
Simone

**Comment by hubeyb** [comment]
I am sorry,very hard to understand in Portuguese (or Spanish I do not know) :)

**Comment by hubeyb** [comment]
What is the error message in English?
