### ISSUE TITLE
News updates

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4113]
any new updates on project or new version since 1 month ?
Wondering about what's planned in the next months regarding the Project roadmap (some very interesting stuff planned).
Having to renew the yearly subscription so it's important to know.

Please let us know.

**Comment by volkanceylan** [comment]
Hi @kilroyFR, you should be less worried about updates or changes, as i think you got access to lots of new features during your subscription period, didn't you?

Our roadmap is here:

https://github.com/volkanceylan/Serenity/projects/1

And the change log clearly shows how much changed in a year:

https://github.com/volkanceylan/Serenity/blob/master/CHANGELOG.md

**Comment by kilroyFR** [comment]
absolutely yes Volkan. Just askin
