### ISSUE TITLE
Subscribe my Youtube Channel for Learning. How to Make projects in Serenity

### ISSUE THREAD

**Issue by jaamkamran** [volkanceylan/Serenity#4114]
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q/videos?view_as=subscriber
For Learners. how to make Project in serenity? Kindly subscribe my channel.

**Comment by volkanceylan** [comment]
Nice work @jaamkamran, thanks!

**Comment by dfaruque** [comment]
Good but will be better with voice.
BTW Thanks.

**Comment by Zahar661** [comment]
Attaboy! Thank you! Need to add more voices and a more detailed description of each video. It is not always clear what you are trying to show, especially for those who do not understand English.
