### ISSUE TITLE
Use of MediumHalfWidth

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4115]
Hi all,
I don't know how to use MediumHalfWidth. Is there any example ?
Thank's

**Comment by ga5tan** [comment]
just put it like this:

> [HalfWidth]

above field u wanna have half width and you are good.

to continue have all the fields in two columns put this

> [HalfWidth (UntilNext=true)]

read blog for more info:

https://serenity.is/blog/2018/05/16/multi-column-layout




ofcourse, ther eis also [MediumHalfWidth] attribute, but I dont see how that will help you

**Comment by volkanceylan** [comment]
MediumHalfWidth is half width on medium+ devices (col-md-6), HalfWidth is half width on small+ devices (col-sm-6), refer to Bootstrap 3 docs for more info.
