### ISSUE TITLE
Odd Issue with Lookup Tables

### ISSUE THREAD

**Issue by stevenrboone** [volkanceylan/Serenity#4117]
Some of my lookup tables are dynamic, and seem to (re)populate in Serenity only upon "(re)Publishing" the app. I need to be able to update the lookup tables and have the data show in the Serenity interface without republishing the app. What did I leave out, or am I doing wrong - any suggestions?

**Comment by volkanceylan** [comment]
add expiration, e.g. [LookupScript("....", Expiration = -1)] etc. to your lookups

**Comment by stevenrboone** [comment]
I will try that, thank you!

**Comment by stevenrboone** [comment]
That worked perfectly, thank you, Volkan!
