### ISSUE TITLE
How to pass Value from one dialogue to another?

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4118]
On close of one of the dialogue which was opened via another dialogue,
How can i pass value from that dialogue to dialogue whihh instantiated this dialogue

i.e in below eg," New Transaction Dialogue's" Product Select2 change will trigger opening "Products based on transaction dialogue".
Now When i click any button/row in this new dialogue (or while closing this new opened dialogue) i want to pass a value from this dialogue to root dialoge whic is New Transaction Dialogue's Inbound Transaction."

![image](https://user-images.githubusercontent.com/4771536/49511142-c0a1ff80-f8a3-11e8-9600-9824f084ac14.png)

this.form.ProductId.changeSelect2(e => {
             
                    new Default.TransactiondetailCSDialog().dialogOpen();

                }
            });

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/49514038-49bd3480-f8ac-11e8-9879-e4e6e7b6e8a0.png)

**Comment by jabirmoolur** [comment]
@Zahar, Thanks for your reply
Can you assist whats mean by this.rowSelection.getSelectedKeys()??
is PayHandleDialog is the Grid dialog or form dialog

**Comment by jabirmoolur** [comment]
@Zahar661 Thanks a lot for your wonderful assistance.

**Comment by hhernandezCS** [comment]
@Zahar661 in this case are you from the transaction-based products dialog?

I need to send from a form the value written inside an input text to another form with input text.

**Comment by Zahar661** [comment]
@hhernandezCS I did not understand what is needed.

**Comment by VictorTomaili** [comment]
Please create a discussion topic @hhernandezCS @Zahar661

**Comment by stixoffire** [comment]
just for others finding the page 
`this.form.field = this.otherform.field;`
