### ISSUE TITLE
After 3.8.1->3.8.2

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#4119]
Hello dears! After upgrading to 3.8.2, the application stops working.

![image](https://user-images.githubusercontent.com/26430136/49514512-b127b400-f8ad-11e8-8455-d9a83b0aa6b1.png)
![image](https://user-images.githubusercontent.com/26430136/49514584-e6340680-f8ad-11e8-8c76-f6f3888132bd.png)

If you roll back to 3.8.1, everything works

**Comment by dfaruque** [comment]
I have also noticed that.

```
    <handlers>
      <add name="SkipStaticFileForUploadFolder" verb="GET" path="upload/*" type="System.Web.Handlers.TransferRequestHandler" />
      <add name="ReportViewerWebControlHandler" preCondition="integratedMode" verb="*" path="Reserved.ReportViewerWebControl.axd" type="Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" />
      
      <add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />
    </handlers>

```

after update to 3.8.2, the following line is deleted somehow

`<add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />`

bringing back this line have fixed my issue.
you might try that.

**Comment by brunobola** [comment]
I also confirmed that.

**Comment by Zahar661** [comment]
@dfaruque You're right, it helped me!

**Comment by mafdy** [comment]
After I upgrade packages from 3.8.1 to 3.9.0 same error happens.
Has had fixed by adding DynamicScriptHandler row to web.config.

thanks @dfaruque .
