### ISSUE TITLE
Do serenity provide any facility of "No multiple login"?

### ISSUE THREAD

**Issue by patelaakash** [volkanceylan/Serenity#4120]
I dont want to allow to login from multiple location at once.

Thanks in advance

**Comment by edwardch** [comment]
Have a look through this discussion: [Limit user to single access and data modification concurrency](https://github.com/volkanceylan/Serenity/issues/2965)

**Comment by patelaakash** [comment]
@edwardch Thank you for the link. I checked the link you provided but what I need is :
1.) I want to Logout the user after 10 mins of inactivity.
2.) Even on tab close user should logout.
And the problem is I have not used sesson in whole application.
In other word I want the method in Global.asax which fires on Timeout of form authentication
You can see timeout of webconfig in below image:
![image](https://user-images.githubusercontent.com/41342867/49643595-232e0380-fa3c-11e8-8e65-34f368dff976.png)

**Comment by volkanceylan** [comment]
@patelaakash this is not a Serenity question, it ASP.NET related, you may use StackOverflow etc. for such.

**Comment by Estrusco** [comment]
@patelaakash  see this post https://github.com/volkanceylan/Serenity/issues/2965
