### ISSUE TITLE
conditionnal readonly dialog

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4121]
Hi all,
I have an employe dialog that can be used (via [editlink] from an organization (form has to be updatable) and from a project (form has to be readOnly).
I was thinking about using "setReadOnly" on EmployeDialog but I don't know witch condition to apply (see "???")

` protected updateInterface(): void {

            super.updateInterface();

            if (???) {
                Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);  
            }
        }`

**Comment by brunobola** [comment]
You can use a `[NotMapped]` Field to your entity and then use it as just a trick to make what you want.

You can alto pass parameters to your dialog when evoque it.

You can see my previous posts (search git) in which you pass the parent and then control it using it, for instance see which type it is or accessing its properties...

**Comment by fremar83** [comment]
Hi brunobola,
Thank's for your quick answer ! you open my eyes on the simplest way to do it : passing parameter !
Many thank's !!!

**Comment by tmartinscopo** [comment]
Hi, can you tell the post # to passing parameters to dialog?
I couldn't find it.
