### ISSUE TITLE
inplaceAdd pass parameter

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4122]
Hi all,
I need to pass a parameter to the child insert dialog when clic InplaceAdd functionanlity. Any  clue ?

**Comment by volkanceylan** [comment]
```ts
this.form.SomeField.onInitNewEntity = entity => {
  entity.SomeInfoField = "someValue";
}
```

**Comment by fremar83** [comment]
Hi Volkan!
You rock! very helpfull solution... and so elegant, as usual!
IThank's for your amazing job.
Cheers,
Frederic
