### ISSUE TITLE
Dynamic navigation on Enum

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#4124]
I was just wondering as the dynamic navigations work for lookup values but can we use it with Enum quick filters?, checked with issue #3371 but didn't helped

**Comment by vinaykulkarni89** [comment]
var q = Q.parseQueryString();
            if (q["status"]) {
                var status = Q.tryFirst(filters, x => x.field == "Status");
                status.init = e => {
                    e.element.getWidget(Serenity.LookupEditor).value = Serenity.EnumFormatter.format(Serenity.EnumTypeRegistry.get('Masters.Status'), Q.toId(q["status"]));
                };
            }

Here status field if Enum

**Comment by volkanceylan** [comment]
Enum.GetValues...

**Comment by vinaykulkarni89** [comment]
Working code in case if anyone needs,

          if (q["status"]) {
                var status = Q.tryFirst(filters, x => x.field == "Status");
                status.init = e => {
                    var stat = Q.toId(q["status"]);
                    e.element.getWidget(Serenity.EnumEditor).value = Q.toId(stat);
                };
            }
