### ISSUE TITLE
Browser can't load any fonts - .net core linux

### ISSUE THREAD

**Issue by nightBaker** [volkanceylan/Serenity#4126]
Browser can't load any fonts because linux is case sensitive, so it expects "Fonts" in path .
There are several same errors with resources for example
jquery.maskedInput.js should be jquery.maskedinput.js

This is console log
`(index):236 GET http://localhost:8000/fonts/fontawesome-webfont.woff2?v=4.7.0 net::ERR_ABORTED 404 (Not Found)
DevTools failed to parse SourceMap: http://localhost:8000/Scripts/site/Serene1.Web.js.map
(index):701 GET http://localhost:8000/fonts/fontawesome-webfont.woff?v=4.7.0 net::ERR_ABORTED 404 (Not Found)
4(index):1 GET http://localhost:8000/fonts/fontawesome-webfont.ttf?v=4.7.0 net::ERR_ABORTED 404 (Not Found)`

**Comment by nightBaker** [comment]
There are another errors with resources not just with fonts. I think we should use right case-sensetive pathes.

**Comment by volkanceylan** [comment]
This will hopefully be fixed in next version
