### ISSUE TITLE
How to open a dialog from dashboard directly

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4127]
How can i call a dialog from .cshtml file directly  on click of button or widget
Eg from Dashboard screen.

var dlg = new Default.TransactionsDialog();
            dlg.element.on('dialogclose', () => {
                this.refresh();
            });
            this.initDialog(dlg);
            dlg.loadEntityAndOpenDialog(<Default.TransactionsRow>{
                Type: S1,
                TrnRef: "IN00",
                SubType: 2
            });

**Comment by vinaykulkarni89** [comment]
You can call it like this,
<a href="javascript:new Serenity.Default.CustomerDialog().loadNewAndOpenDialog()">here</a>
