### ISSUE TITLE
Using Date Editor for String column.

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4128]
I have a database column (ShipDate - Char(10)) that stores a date value (YYYY-MM-DD). How would I change the editor for that field to a Date Selection that is then formatted as a string in the proper format?

And then, the same thing with the "QuickFilter" for that column.

Thanks for your help!

**Comment by hubeyb** [comment]
Try to write custom date editor.  can find some editor examples in serenity codes.
