### ISSUE TITLE
using Google Maps Geocoding API in Serene (Serenity Application Template) dialog

### ISSUE THREAD

**Issue by Thebenmandude** [volkanceylan/Serenity#413]
I am new at using Serene (Serenity Application Template) and would like to know how would I go about adding the Google Maps Autocomplete feature to a field/fields on a Serene Dialog. I would like the user to enter the location as you would do on Google Maps and then populate the fields of the address retrieved by Google's API as per their example https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform I would greatly appreciate some help on this. 
Regards, Ben

**Comment by volkanceylan** [comment]
I don't have experience with this but add relevant fields to your form, and use this script code in your dialog template, or maybe write it in Saltarelle

**Comment by wdhodges** [comment]
I was wondering about this. Where are the templates located in the Serene template? Can't seem to find them lol

**Comment by Thebenmandude** [comment]
Thanks for the reply. Like wdhodges, I don't know where to look for the Dialog template? Is it under the scripts\serenity folder in the .web project? Sorry for being a noob.

**Comment by volkanceylan** [comment]
Like CustomerDialog.Template.html, you can name some file like YourModule.YourDialog.Template.html and it will be used for your dialog. Then if you want to put some javascript code there its ok but i'm not how you'll handle dialog lifetime events that way. Maybe define a global function there and call it from Saltarelle code in AfterLoadEntity method etc. Better to put such a javascript code in YourPage.cshtml file.

**Comment by Thebenmandude** [comment]
I am making some progress but it seems like I need to set some attributes on the fields for this to work. How would I add the onfocus="" and placeholder="" attributes on a specific field only?

**Comment by Thebenmandude** [comment]
I have go the field to auto complete the address as I type, the only problem I have is that the auto complete results popup underneath the dialog and I cannot select it even if I move the dialog. I added the code to the .Template.Html and also tried the cshtml. Both give me the same results. Do you have any tip on getting around this. Would be much appreciated!

**Comment by volkanceylan** [comment]
It has probably a lower z order than dialog. Check with chrome console and increase it with css

**Comment by jsbUSMC** [comment]
I know that you can add placeholder as an attribute/annotation above the field, like:

```cs
// ...

[Placeholder("Some Text")]
public string YourFieldName

// ...
```
In the xyzForm.cs class.

**Comment by Thebenmandude** [comment]
Thanks for all the help, I got it working. Still need to sort out some styling etc but here is a screenshot. Will post what I did soon.

![image](https://cloud.githubusercontent.com/assets/6910368/13840123/0e9d18a8-ec29-11e5-8fb4-5092b458bdfb.png)

**Comment by Thebenmandude** [comment]
How to add Google Places Autocomplete to Dialog field:
1. in the afterLoadEntity function in Serenity.Scripts.UI.js I added the following (onfocus trigger):
if (document.getElementById('MyFieldID') !== null) {
    var user_input = document.getElementById('MultiTenancy_Removal_RemovalDialog7_Location');
			        user_input.onfocus = function () {
			            geolocate();
			        }};
2. I added the javascript found here https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform to the MyDialog.Template.html file. I had to update the function "initAutocomplete()" to use my new field "document.getElementById('MyFieldID')"
4. Added the following Style to the MyDialog.Template.html
        .pac-container, .pac-item {
         z-index: 1200;
        }

I now need to put the results into the Dialog fields instead of the example fields at the top but that should not be a problem.
Thanks for the amazing template and quick response, its much appreciated.

**Comment by volkanceylan** [comment]
You're welcome. Just i'm not sure hardcoding dialog element id like that: MultiTenancy_Removal_RemovalDialog7_Location is a good idea. Everytime a dialog opens, your element ID's will change. You should pass a IdPrefix of dialog to your script method.

**Comment by jsbUSMC** [comment]
Wouldn't altering the Serenity.Scripts.UI file also not be recommended because of the possibility of changes being overridden after updating packages?

**Comment by volkanceylan** [comment]
Yes, right, it shouldn't be modified.

**Comment by Thebenmandude** [comment]
How would you recommend that I set the onfocus of a field?

**Comment by volkanceylan** [comment]
He didn't modify Serenity.Script.UI though. It was in another issue.

**Comment by volkanceylan** [comment]
In your dialog constructor, form.Location.Element.Focus(e => {
});

**Comment by volkanceylan** [comment]
Oh you did modify :)

Write your script code in your dialog please overriding relevant methods, not Serenity scripts

**Comment by Thebenmandude** [comment]
Sorry for another "perhaps" stupid question. Where do I find the dialog constructor?
And would I do the method overrides in the same constructor?

**Comment by jsbUSMC** [comment]
It's in the Serenity.Script project. There's a folder called Modules, nested within are the folders sergen created for your entities. Inside each folder are EntityDialog.cs and EntityGrid.cs. In the EntityDialog class, implement your code in the constructor there using override.

**Comment by Thebenmandude** [comment]
I have implemented the following: "form.Location.Element.Focus(e => {
});" to add the focus event to my field. How would I call a javascript function that resides in my .cshtml file?

**Comment by volkanceylan** [comment]
Window.Instance.As<dynamic>().yourFunction(...)

**Comment by Thebenmandude** [comment]
Am I missing a reference in my Dialog.cs? The name "Window" does not exist in the current context.

**Comment by volkanceylan** [comment]
System.Html

**Comment by Thebenmandude** [comment]
Thanks, I get the following error when building: 
Error  17	The type arguments for method 'Serenity.CastExtensions.As<T>(object)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	
I am using System.Html.Window.Instance.As().testfunction();

**Comment by volkanceylan** [comment]
Window.Instance.As< dynamic >().yourFunction(...)

Markdown eating <   >

**Comment by VictorTomaili** [comment]
what about `Window.Instance.As<dynamic>().yourFunction(...)`

**Comment by Thebenmandude** [comment]
That did it, thank you very much.
