### ISSUE TITLE
How to Populate Grid Based on lookup values

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4131]
Hello,

I have a Lookup dropdown with PO No. in Dialog.ts What I want to do is I want to populate Grid in Dialog.ts based on PO No.Selected in drop down. Can anyone please help me on this issue how can I achieve this ?

**Comment by hubeyb** [comment]
you can see the eaxmple below.

https://serenity.is/demo/BasicSamples/FilteredLookupInDetailDialog

> 
> A frequently asked question is how to pass some data from master dialog to a lookup editor in a detail dialog to filter items.
> 
> In this sample we have a custom Order dialog that has a Product Category selection.
> 
> When you click Add button in Order Details grid, Product editor in detail dialog will only show products in selected Category.
> 
> To achieve this, we need to flow selected category information on this route: Master Order Dialog -> Order Detail Grid Editor -> Order Detail Dialog -> Product Lookup Editor.
> 
> Source Files: Index.cshtml, FilteredLookupInDetailForm.cs FilteredLookupInDetailGrid.ts FilteredLookupInDetailDialog.ts FilteredLookupDetailEditor.ts FilteredLookupOrderDetailDialog.ts
>
