### ISSUE TITLE
Form/Dialog Layout?

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4132]
Is it possible to specify the "Width" of a Form/Dialog?

Also, for individual columns, how do you specify the length of a LookupEditor? I have tried "Width", "Size" and "MaxLength".  Size and MaxLength both seem to limit the number of characters that can be entered into a column and "Width" doesn't seem to have any effect (on columns in the "Row" class, it does work on the "Columns" class). (And yes, I know about the "OneThirdWidth", "HalfWidth", etc... is that the only option for limiting column widths in the "Row" class?)

I'm starting to understand the Framework and I'm very impressed with it.

Thanks for everyone's help!

**Comment by ga5tan** [comment]
Yeah. Use CSS. EACH form/ grid has it's own class. U can edit less files for that

**Comment by ShayneJud** [comment]
Thank you.  (That's actually what I did. I just want to make sure I wasn't missing a "Serenity Attribute". I'm still new to the Framework and trying to do things "Best Practice" to minimize changes when future versions are released.)

**Comment by ShayneJud** [comment]
What about the "Size" and "MaxLength" attributes. Can you explain the difference, and scenarios for using each?

**Comment by stixoffire** [comment]
@ShayneJud 
I am sure you have figured this out by now - but just in case others are reading this:
Size is for the database field , for example I have a decimal field and I need a precision value. 

> Size(2) is the precision of that field for 0.00 
> Size(4) is the precision of that field for 0.0000
