### ISSUE TITLE
Show Order Id as Lookup and Data in Editable grid

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4134]
Hello,

I want to show Order Id as lookup in my dialog.ts  and on selection of Id grid should get populate in dialog.ts in editable format so that on save I can save the results in my New table not in order details table.
Please help

**Comment by ga5tan** [comment]
One way to do it would be to make lookup for Order Ids.
Then in onchange event of that lookup you can do whatever you want to do with it.
I am not sure I understand what exactly. Do you want to load enitity into dialog? that fairly easy, just use dialogs loadEntity function.

**Comment by TechAspirant** [comment]
Yes i want to load data into grid in dialog for selected order Id from dropdown
Can you please show me how can I do this ?
Can you please show how can I write code for lookup change event and dialogs loadEntity function ?

**Comment by ga5tan** [comment]
check this demo:
https://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

it deals with loading specific entities
