### ISSUE TITLE
RowListFields are not being serialized by row.ToJson() method. How to achieve that?

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4135]
Suppose, I need to serialize OrderRow with OrderDetailsRow. But when I call `orderRow.ToJson()` it does not give me the detail records. It gives only table fields may be.

Could anybody help me, please?

**Comment by dfaruque** [comment]
Thank you.
Yes, I am also thinking that the master-detail works fine, but in order repository I have write the following

```
        private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void PerformAuditing()
            {
                base.PerformAuditing();

                var rowJson = Row.ToJson();

            }
        }
```

while I am debuging `Row` has 5 detials

![untitled](https://user-images.githubusercontent.com/16621563/49858589-82668c00-fe1f-11e8-96c5-52922e0def70.png)


but the `rowJson `give me the following
```
{
  "CustomerID": "BONAP",
  "EmployeeID": 1,
  "OrderDate": "2016-11-06T00:00:00.000",
  "RequiredDate": "2016-12-03T00:00:00.000",
  "ShipVia": 2,
  "Freight": 38.28,
  "ShipName": "Bon app'",
  "ShipAddress": "12, rue des Bouchers",
  "ShipCity": "Marseille",
  "ShipPostalCode": "13008",
  "ShipCountry": "France"
}

```

**Comment by volkanceylan** [comment]
On that stage non table fields are not Assigned, so any such field wont be serialized, including foreign fields.

**Comment by volkanceylan** [comment]
That is to generate a proper SQL insert statement. Assign Row.DetailList = Row.DetailList so it will be serialized

**Comment by dfaruque** [comment]
Got it.
At `BeforeSave()` it works as expected.

Thank you very much.
