### ISSUE TITLE
Error at Runtime

### ISSUE THREAD

**Issue by Poojapusunuri** [volkanceylan/Serenity#4136]
Hi,

Iam working on a project where iam getting the below error(screen shot attached). Am not able to identify the error.
Pls guide me to find out the error and rectify it.
![error1](https://user-images.githubusercontent.com/36690954/49870416-4cce9c80-fe39-11e8-9091-4cb0d1533124.png)

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serenity/issues/4119 check just in case

**Comment by Poojapusunuri** [comment]
hi @Zahar661 thank you for your reply,

Am using the 3.8.1, So I think version is not the issue.

**Comment by Zahar661** [comment]
@Poojapusunuri  I have not seen errors in jquery and CoreLib. Only when Dynamic Script Handler was specified incorrectly
