### ISSUE TITLE
Form/Dialog Layout?

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4137]
Many of my tables have "Modified" and "Created" DateTime columns. When those columns are displayed in the Dialogs, I want them to have the following "attributes" (or behaviors):

- **Read Only** (I am using ReadOnly(true) attribute in the "Row". Seems to be the best solution.)
- **Display the Date AND Time** (I tried using the DisplayFormay() attribute in the Row AND in the Form and it doesn't work in either location. I only get the Date.)
- **Hide the Date Editor** (It is "grayed out", but would rather hide it entirely since the column is always "ReadOnly". It would be nice if that was the "default".)   

Thanks for all the help everyone. My project is coming along well. I am seriously considering "standardizing" on Serenity for all of our futuressed with it. :)

**Comment by ShayneJud** [comment]
It seems when I specify the "DateTImeEditor" in the "Row", now I get the Time. Is that the only way I can show the Time on a Form?

**Comment by ReatKay** [comment]
[DateTimeKind(DateTimeKind.Local)]
        [DateTimeFormatter]
        public DateTime? Time
        {
            get { return Fields.Time[this]; }
            set { Fields.Time[this] = value; }
        }

resulting in full Date + Time output. Replace Local with UTC etc.
