### ISSUE TITLE
Issue of casacading from  one form to another form

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#414]
Hello Volkanceylan,

I want to display courses in course dropdown in Batches form where courses is assign to that selected branch

Following is my table structure
BranchCourse:BranchCourseId pk,BranchId fk,CourseId Fk
here is my screens

![untitled](https://cloud.githubusercontent.com/assets/16571169/13782995/8eba15c6-eaef-11e5-94c8-df2cf6a57369.png)
![untitled2](https://cloud.githubusercontent.com/assets/16571169/13782996/8ec3528a-eaef-11e5-815f-e1f2c1ac680a.png)

**Comment by volkanceylan** [comment]
If one course can be used by multiple branches, you need to add a lookup script or remote data script for this table and filter them client side in your custom lookup editor

**Comment by nilimajagtap** [comment]
I have added lookup as BanchCoursesLookup in Batches.
```
namespace Serene.Institutes.Branches.Scripts
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("Branch.Courses")]
    public class BranchCoursesLookup : RowLookupScript<Serene.Courses.Entities.CoursesRow>
    {
        public BranchCoursesLookup()
        {
            IdField = "CourseId";
            TextField = "CourseName";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Serene.Courses.Entities.CoursesRow.Fields;
            var branchCoursesFld = Entities.BranchCoursesRow.Fields;
            string branchId;

            if (LookupParams["BranchId"] != null)
                branchId = (LookupParams["BranchId"].ToString());

            query.Select(fld.CourseId, fld.CourseName)
                .Where("CourseId IN (SELECT CourseId From BranchCourses Where BranchId=2)");


        }
    }
}
```
In BatchesRow I have added this
```

 [DisplayName("Course Name"), NotNull, ForeignKey("[dbo].[Courses]", "CourseId"), LeftJoin("jCourse"), TextualField("CourseCourseName")]
        [LookupEditor(typeof(CoursesRow))]
        [LookupFiltering("Branch.Courses")]
        public Int64? CourseId
        {
            get { return Fields.CourseId[this]; }
            set { Fields.CourseId[this] = value; }
        }

```
please verify this code and let me know where I m going wrong

**Comment by volkanceylan** [comment]
This won't work. Lookup scripts are only executed once server side. They can't be parameterized so you can't pass dynamic BranchId to your lookup script.

Your lookup script or remote data should contain all BranchCourses rows with BranchId and CourseId values in BranchCoursesRow. Why your BranchCoursesLookup contains CoursesRow?

After you do this, you can filter your Courses by BranchId in script side editor GetItems method.

**Comment by samdubey** [comment]
Do you have any example in Northwind to take a look?

**Comment by volkanceylan** [comment]
There are several sample lookups there and in multi tenancy tutorial
