### ISSUE TITLE
Dashboard without CSS

### ISSUE THREAD

**Issue by vigneshkumar957** [volkanceylan/Serenity#4140]
Hi,

I have downloadedd the serene project and checked in my TFS portal. Dashboard is working for me without any issue but for my team mates (who downloaded the project from TFS) having dashboard withoyt any css style. It is just shoing the dasboard as conetnet without any design.

**Comment by vigneshkumar957** [comment]
I have checked in all code properly. Even it is working for Login Page but not only for Dashboard.

**Comment by volkanceylan** [comment]
If it is working for you, and not in your friends, then it is about your tfs or config, simple logic.

**Comment by vigneshkumar957** [comment]
I got one clue, for my machine content/site/site.css is automatically generating but in my coleagues machine it is showing as blank.

**Comment by hubeyb** [comment]
so .less tranform is not working on your coleagues. please search why.
