### ISSUE TITLE
Filtered Lookup and keeping the initial value

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4144]
Hi everyone,

I created a custom lookup editor which should filter out disabled employees and optional filter on departmentId. So far so good the editor is doing it's job, but when an employee is disabled and was allready saved in the entity before, the value wont show up again. 

What I'm trying to do was to get the actual value when the lookup is created and add that value to the itemList of the lookup, but that didn't work.

Hope it's clear what I tried to explain and I'm thankfull for any help

```
	@Serenity.Decorators.registerEditor()
	export class ActiveEmployeeEditor extends Serenity.LookupEditorBase<ActiveEmployeeLookupEditorOptions, any> {
	
		constructor(container: JQuery, options: ActiveEmployeeLookupEditorOptions) {
			super(container, options);
		}

		protected getLookupKey() {
			return Serenity.EmployeeRow.lookupKey;
		}

		protected getItems(lookup: Q.Lookup<Serenity.EmployeeRow>, filterValue = null) {
			var filteredLookUp;

			if (this.options.departmentId) {
				filteredLookUp = super.getItems(lookup).filter(x => (x.DepartmentId === this.options.departmentId && x.Disabled === false) || x.Id.toString() === this.filterValue);
			} else {
				filteredLookUp = super.getItems(lookup).filter(x => x.Disabled === false || x.Id.toString() === this.filterValue);
			}
			return filteredLookUp;
		}

		getItemText(item, lookup: Q.Lookup<any>) {
			var t1 = super.getItemText(item, lookup);
			return t1;
		}
		
		set_value(value: string): void {
			if (value) {
				var itemList = Q.getLookup<Serenity.EmployeeRow>(Serenity.EmployeeRow.lookupKey);
				var items = this.items;
				var item = itemList.items.filter(x => x.Id.toString() === value);
				this.items.push(item);
			}
			super.set_value(value);
		}
	}
```

**Comment by ga5tan** [comment]
maybe have two editors, one use for lookup without filtering, and other for editing with filtering?
is the field editable?

**Comment by Garozh** [comment]
I have two lookup's one default without filtering [LookupEditor(typeof(EmployeeRow))] and the filtered [ActiveEmployeeEditor] but that doesnt help me with my problem. And yes the lookup field is editable.

**Comment by volkanceylan** [comment]
You should override getItemDisabled method and return true for inactive employees.

**Comment by Garozh** [comment]
That's atleast the way I want it to work, but the items are still shown in the list and I want them to be hidden. If you have any solution for that, it would be great.

**Comment by Garozh** [comment]
Still looking for it, if anybody can help?

**Comment by Garozh** [comment]
I did it with saving the value in a private member variable in the set_status method of the editor and calling it in the getItems method

**Comment by Daffyydd** [comment]
> I did it with saving the value in a private member variable in the set_status method of the editor and calling it in the getItems method

Dear @Garozh,

Please kindly share the solution. am having same issue too

**Comment by haajit** [comment]
It's very late 😀
But you can refresh your lookup after any data manipulate by:
                    `Q.reloadLookup(Serenity.EmployeeRow.lookupKey);`
