### ISSUE TITLE
Filtered LookupEdior

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4146]
Hello,

I have one hardcoded Lookup Editor and one from Entity, How can I Filter Entity lookup Editor from hardcoded lookup Editor. Below is the code I have used but not working. Please help what is wrong ?

```
[HardCodedCategoryEditor]
        public String StockListCategory { get; set; }
        [LookupEditor(typeof(Entities.RmMergeStockListRow), FilterField = "StockListCategory", FilterValue = "StockListCategory")]
        public Int64 StockListId { get; set; }
```

**Comment by Zahar661** [comment]
[LookupEditor(typeof(Entities.RmMergeStockListRow), CascadeFrom= "StockListCategory")]
and in RmMergeStockListRow for field StockListCategory add [LookupInclude]
