### ISSUE TITLE
Work In Progress

### ISSUE THREAD

**Issue by rcmsoftwaredevelopment** [volkanceylan/Serenity#4152]
Good afternoon

Looking to renew my elapsed Serenity license and I was just wondering if you could briefly mention what features you are currently working on and what are you looking to release in next 6 months?  I have looked at your project plan and even thou all of those features would be great it would be good to have a head up on what rough order you are planning to work on.  I am sure other people would find this interesting as well.

Best regards

Ray

**Comment by ga5tan** [comment]
+1

**Comment by volkanceylan** [comment]
Our roadmap is already in the project we have here with pretty viisble goals. You may expect most of things in short term, many from mid term and some from long term to be completed next year. Just look at our change log to see how much changed in a year.
