### ISSUE TITLE
showing subform as dialog instead of grid

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4153]
Hi;

I have created a dialog with a tab like following.
![image](https://user-images.githubusercontent.com/20435849/50055610-caaee280-016e-11e9-906b-7238596fd465.png)
I want to show dialog instead of grid. How can i do it?

**Comment by dfaruque** [comment]
https://serenity.is/demo/BasicSamples/OtherFormInTab

**Comment by ms4hafiz** [comment]
@dfaruque  Thank you. It was what i needed.
