### ISSUE TITLE
Multiple Checkbox in Dialog

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4159]
I have multiple checkbox in Dialog what I want is i want to make check boxes check one at a time means user can check one checkbox out of multiple checkbox at a time. How can I do this ?

**Comment by ga5tan** [comment]
Do you mean radiobutton funtionality? Why not go with that?
Otherwise try to make Validation Rule, or just check how many are checked each time one of them is checked (TS)
