### ISSUE TITLE
Assigned permission does not automatically show related navigation item

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#416]
Hi JaiQ,

John Ranger here again with a "strange" Problem.

So far - when I added a new permission within xyzRow.cs or xyzEndpoint.cs (exchanged the Default "Administration" permission with something custom), the permission showed up in the permission view and I could assign it either to a role or a user.

When then a user (with the corresponding role or direct permission assigned) logged in, the GUI displayed automatically the corresponding, neccessary tree view (top Levels and drill down to the specific function).

**Problem Situation:**

Custom app, based on Serenity 1.9.13.

I have now added a new permission called "Dashboard Setup" to a xyzRow.cs (Read and modify) and the xyzEndpoint.cs (ServiceAuthorize). 

The new permission does Show up in the permission tree view and I have assigned it to a role (and - because it didn't work - also directly to the useraccount).

But when I log in with a user which has the corresponding permission "Dashboard Setup" but is not in the "Administration" role, the GUI does not Show the Top Level and the drill down and the function is not visible to that user.

If the User is in the "Administration" role, then the corresponding GUI Navigation Shows up and it works as designed.

I have done Clean, T4 transform, Rebuild solution but with no avail.

May I kindly ask you if I have overseen something in General or where I should start to look at.

thanks for oyur help and

with Kind regards,

John

**Comment by volkanceylan** [comment]
Navigation items uses permissions written on your XYZPage.cs action, check there if some another permission left.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks, that was it. I must had an amnesia. So many times done and already forgotten ;-)

With Kind regards,

John
