### ISSUE TITLE
Single form with data from different databases

### ISSUE THREAD

**Issue by nathanealg** [volkanceylan/Serenity#4160]
I have a need to have a single form, called Check, which is linked to a database db1 and table tb1.  

But the catch is I need for some data from a second database db2 and table tb2 to pre populate data on form Check Dialog when it is opened.

Then when the form Check is saved, I don't wish the data from db2 to be saved only the entries placed on the form.

Thanks

**Comment by wldkrd1** [comment]
Lots of ways to do that, none of which have native support in Serenity.

**Comment by brunobola** [comment]
You can write a "SQL View" using all the data you want from multiple databases and you can override the before save or the repository handlers and make your own saving procedures so you can achieve this behaviour this away.

There are other ways to do this also its only a hint for you.

**Comment by ga5tan** [comment]
@nathanealg you just generate entity out of view, same as from table
there are samples in serene template of getting data from multiple DBs
Try to check here:
https://serenity.is/demo/BasicSamples/VSGalleryQA

I remember seeing in sources, where there was code able to grab some data fro mother connection.

Anyway, if you cannot lookup data in Row.cs, you can definitely get therm in Repository.
Just add some NotMapped fields in Row, populate them on retrieve or list, and leave them be on saving.

**Comment by nathanealg** [comment]
Hi, so I just been playing with Views and this does seem promising.  But some databases that I need are on different servers so views will not work.  And I am not allowed to do linked-server mode. 

Open to other ideas for db's on different servers.

Thanks

**Comment by nathanealg** [comment]
Hi I did look though but I did not notice that bit (MinSelectionLevel), I tagged it with notmapped,  I will give that a go a.

Thanks
