### ISSUE TITLE
Missing .js files after rebuild

### ISSUE THREAD

**Issue by stevenrboone** [volkanceylan/Serenity#4161]
I apologize in advance if this is a repeat issue; I was unable to find a solution.

I upgraded from Serenity v2.9 to v3.8.2. I have reinstalled the packages. I updated TypeScript to v3. When I run the solution I get the following on the login screen:

![image](https://user-images.githubusercontent.com/33872312/50244460-fcf25700-039d-11e9-97f0-fc08ca142e4a.png)

where the bundled .js files are not found.  How do I generate them?

Thank you!

**Comment by stevenrboone** [comment]
I also noticed that there are several errors in TypeScript files as well:

![image](https://user-images.githubusercontent.com/33872312/50247613-5d859200-03a6-11e9-9a65-e3f751acddf9.png)

**Comment by wldkrd1** [comment]
The first problem is caused by #4119, solution in that thread.

**Comment by stevenrboone** [comment]
I am rolling back to 3.8.1 now.

Thanks - I will report back once rolled back.

**Comment by stevenrboone** [comment]
After rolling back to 3.8.1 - the initial response is that everything seems to work as designed in the Serenity app. I am performing regression testing and will provide a (hopefully) final status update.

**Comment by stevenrboone** [comment]
All appears in order, thank you for your advice!
