### ISSUE TITLE
Error in getting entity value as stored procedure parameter

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4164]
I am trying to get current row value and pass as stored procedure parameter. I have written the following code

      public void RunProcedures(IDbConnection connection, RetrieveResponse<MyRow> request)
        {
            connection.Execute("GetPresriptions",
                        param: new
                        {
                            @PatientId = request.Entity.PatientId,
                            @MedicineOrderId =request.Entity.MedicineOrderId,
                        }, commandType: CommandType.StoredProcedure);
        }

but when I run, it gives the following error. Am i missing anything?

![image](https://user-images.githubusercontent.com/20435849/50376012-3dfb9d00-0624-11e9-840a-a4ced42beb46.png)

**Comment by ga5tan** [comment]
it says your request parameter is NULL.
I guess you are passing null request into RunProcedure procedure...
