### ISSUE TITLE
How can I call a controller action from xxDialog.ts?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4165]
Hi;
I need help calling a controller action in Home controller, Edit action with parameter 1 using xxDialog.ts and open it in another tab.
Is there a way to do it? 

Thank you

**Comment by ReatKay** [comment]
A controller action is called by calling its route. So simply create a <a> with the href set to the route of the controller action. You can submit parameters via URL (see general ASP.NET MVC examples). To ensure it's opened in a new tab add the target="_blank". But be warned: Popup filters might block this (new tab/new window is literally the same, in the end the client settings decide if the link is attempted to open in a new tab or a new window.

In case you refer to Dialog Tabs of Serenity, the approach will be different (simplified):

Create a tabbed dialog template (see the example included in serenity)
Create a custom models file (analog to the examples included in serenity) with its own request & response class for that special case.
On page load:
Create the request, call the service with the request -> assign the value(s) of the response to the 
elements on the tab.
