### ISSUE TITLE
ExcelUpload to DetailsEditor View

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4166]
When i set the details editor value i get belwo error message in form
 on button lcic

        protected getButtons(): Serenity.ToolButton[] {
                buttons.push({
                title: 'Import From Excel',
                cssClass: 'export-xlsx-button',
                onClick: () => {                  
                    var dialog = new TimeStampExcelImportDialog();
                    dialog.element.on('dialogclose', () => {
                        var uprods = dialog.UploadedProducts;
                        this.view.setItems(uprods,true);
                        dialog = null;
                    });
                    dialog.dialogOpen();
                }
            });

            return buttons;
        }

**Message: Uncaught Each data element must implement a unique '__id' property. Object at index '0' has no identity value: {"UnitPrice":246.95,"DetailId":2,"InStock":5,"ProductCode":"39263000"}**

Where Details i want to load from excel to View rather than direct upload. Where DetailId is Db Identity Auto Genrated Column

I Applied CLient Side Fake id, But when i try to save it Throws errro stating 
**Could not find field '__id' on row of type 'TransactionDetailsRow'**

**Comment by dfaruque** [comment]
instead of `this.view.setItems(uprods,true);`
try `this.value = uprods`
