### ISSUE TITLE
MultipleFileUploadEditor not able to view/retrieve files

### ISSUE THREAD

**Issue by AlexaOperations70** [volkanceylan/Serenity#4169]
Hi All

I am having issues with viewing files once uploaded. I have added below code to Row.cs. I am able to upload files & column is storing details but once I revisit that record, files are not visible.

Can you please let me know if I am missing anything.

 **Code in Row.cs**
        [DisplayName("Upload Documents JPG, DOC, PDF")]
        [MultipleFileUploadEditor(FilenameFormat = "Partners/Documents/~", ScaleWidth = 800, ScaleHeight = 600, CopyToHistory = true,AllowNonImage =true)]
        public String MFILES
        {
            get { return Fields.MFILES[this]; }
            set { Fields.MFILES[this] = value; }
        }

**MFILES Column String (1000) data**
[{"Filename":"Partners/Documents/00020/00020037_p46e6txhtvml4.jpg","OriginalName":"Bd5k6jqCAAA3r7Y.jpg"}]

I have looked into Northwind: Products ( Images), but did not find anything.

Can you please help me

**Comment by HumanAftrAll** [comment]
According to your code, the files are being stored on the `~/App_Data/Partners/Documents/` folder and should be there. Do you have any other process that clears the folder? 

Have you altered the `BeforeSave()` method on your `Repository.cs` file? If so, post it here.

**Comment by AlexaOperations70** [comment]
Thanks @HumanAftrAll

There is no other process, which clears folders. Also I do not have any code in BeforeSave() under Repository.cs

I followed all steps but not sure where it is going wrong.

**Comment by AlexaOperations70** [comment]
Also I am able to open files directly navigating to Partners/Documents/ folder ( using windows explorer)
So I am guessing code is storing the file but not able to retrieve file.
