### ISSUE TITLE
Token Authentication Required for Exposing Service Endpoint to Mobile Apps

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#417]
Hello Volkanceylan,

I would like to expose Services from Serenity App for Android / iOS App

I would like to implement token authentication instead of cookie based authentication 

what code needs to be changed to achieve this?

**Comment by volkanceylan** [comment]
AFAIK token authentication and cookie is same thing. Forms authentication cookie is also a token. I don't understand what people mean when talk about token authentication. Serenity services already usable from such mobile apps as is.

**Comment by samdubey** [comment]
Thanks for your input
