### ISSUE TITLE
option  to set async false in service call options.

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4172]
I cannot see asycn parameter in listrequest

You can simply call Service2 on success callback of first service call. Another option is to set async false in service call options.

_Originally posted by @volkanceylan in https://github.com/volkanceylan/Serenity/issues/105#issuecomment-171452540_

**Comment by Estrusco** [comment]
Async is in third parameter (opt parameter)
 
```typescript
xyzService.List(
    { your request parameters }, 
    response => response, 
    { 
       async: false 
    })
```
