### ISSUE TITLE
Collapse a Form Category - But only on a Cloned Form, not the Parent Form

### ISSUE THREAD

**Issue by stevenrboone** [volkanceylan/Serenity#4174]
Is there a way to collapse (or hide) a category on a cloneable dialog window - only on the cloned dialog, not on the original dialog?

Original Dialog:
![image](https://user-images.githubusercontent.com/33872312/50491642-55020c80-09e1-11e9-881e-5bd5e9d41a62.png)

Existing Cloned Dialog:
![image](https://user-images.githubusercontent.com/33872312/50491666-6a773680-09e1-11e9-9a86-0268732d5d19.png)

Desired Cloned Dialog - initial mode with Count Identification category collapsed (or hidden):
![image](https://user-images.githubusercontent.com/33872312/50491676-811d8d80-09e1-11e9-8cc5-4f3f7cb5dd5c.png)

Thank you!

**Comment by ga5tan** [comment]
I suggest to close it programmatically on Dialog startup

**Comment by stevenrboone** [comment]
Where do I hide it? I tried to hide it in the CloneableEntityDialog and the category on the main dialog became hidden, not the one in the cloned dialog.

**Comment by ga5tan** [comment]
well, how do u pop up cloned dialog? Is it for cloning/duplicating entity?
If you open it from you code, you can pass some parameter and in constructor act accordingly?

**Comment by stevenrboone** [comment]
I believe that is what I am asking, how and where do I do that?

**Comment by stevenrboone** [comment]
The Cloned Dialog follows the example provided - from a 'Clone' button on the form. It is for cloning/duplicating the selected record. What is the line of code that would close it (NOT hide it) so that if the user wanted to reopen it, they could? Thank you.

**Comment by ga5tan** [comment]
Oh, I never did closing. I just use provided controls for that.
But I checked 'Cloneable Entity Dialog' sample and I believe u should do your logic in updateInterface()
and maybe you can make use of getCloningEntity()  to tell, if u are cloning or not
