### ISSUE TITLE
TreeGrid Column Picker Issue

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#4175]
When we use the column picker the TreeGrid gets disturbed

**Comment by ga5tan** [comment]
that is disturbing news indeed :)
can you please provide screenshot?

**Comment by vinaykulkarni89** [comment]
Normal screen
![image](https://user-images.githubusercontent.com/17939331/50570871-6e300200-0dc1-11e9-95e4-3c6453dfc05f.png)

**Comment by volkanceylan** [comment]
updating Serenity.Web.Assets to 3.8.6 should resolve this issue, make sure running dotnet sergen restore for .net core

**Comment by vinaykulkarni89** [comment]
Ok will check

**Comment by VR-Architect** [comment]
Same issue for me too. There is not Serenity.Web 3.8.6 in nuget for .NET Core version. 
![image](https://user-images.githubusercontent.com/5250669/51253692-0c4ccc00-196d-11e9-929d-a03553e07c10.png)

**Comment by vinaykulkarni89** [comment]
@volkanceylan got the fix for same(not using core)

**Comment by vinaykulkarni89** [comment]
@volkanceylan 
Another thing noticed when updated to latest packages when typing in lookup editor and if the value typed is not available then we just **click to define new** will redirect us to its Dialog along with the typed data in new define dialog, but in new update, it does not carry forward data to new dialog

**Comment by volkanceylan** [comment]
You need to update Serenity.Web.Assets not Serenity.Web, assets contains scripts etc. then run dotnet sergen restore

**Comment by vinaykulkarni89** [comment]
Hi @volkanceylan
