### ISSUE TITLE
How to Add Filters (Date and Category based) in Grid

### ISSUE THREAD

**Issue by vigneshkumar957** [volkanceylan/Serenity#4176]
Hi,

i am using serenity in my application and i have shown grid using serenity. In this i just want to add grid filters like (Country, Order Date in samples) but i am not understating the sample project code. Can you please explain me how to start

**Comment by minhhungit** [comment]
@vigneshkumar957 
Read serenity guide here: http://serenity.is/docs
Wiki here: https://github.com/volkanceylan/Serenity/wiki
It will help you

**Comment by vigneshkumar957** [comment]
@hubeyb Can you please elaborate little
