### ISSUE TITLE
How to get EntitiyId

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#418]
Hi Jaiq,

How to get entity or row that has been created in serenity?
example i create a record with invoice number combine number and date,
it will be generated in beforesave function, how to return this value after created in dialog?.
I want to show it in alert ("Creates succesfully with Invoice no xxxx")

Regards

**Comment by volkanceylan** [comment]
this.EntityId

**Comment by volkanceylan** [comment]
You should write this in OnSaveSuccess method for example.

**Comment by rudianto2008** [comment]
Sorry Jaiq for late reply, but  i cannot get the value using this method


        protected override void OnSaveSuccess(ServiceResponse response)
        {
            base.OnSaveSuccess(response);
            Q.Alert(this.EntityId.Value.ToString());
        }

"Uncaught Nullable object must have a value." in chrome debugger

Regards

**Comment by volkanceylan** [comment]
There Entity is not loaded to dialog yet, so use response.EntityId

**Comment by rudianto2008** [comment]
Cannot find response.EntityId as below

![eas](https://cloud.githubusercontent.com/assets/6382278/13904915/469e7fdc-eee3-11e5-9e05-99c5f8eeb4e5.png)

Thanks

**Comment by volkanceylan** [comment]
Cast to SaveResponse

**Comment by rudianto2008** [comment]
It works, Thanks Jaiq.
