### ISSUE TITLE
PWA for ECommerce Store [discussion]

### ISSUE THREAD

**Issue by mafdy** [volkanceylan/Serenity#4180]
How About integrate PWA as a front-end for ECommerce? maybe as a new branch!
I'm sure it will raise Serenity on the top. And there's a great open-source project build with VUE ready for implementing that!
GitHub: [https://github.com/DivanteLtd/vue-storefront](url)
Demo: [https://demo.storefrontcloud.io/](url)

**Comment by ga5tan** [comment]
I don't think it's the worst idea ever, but since we are missing more "important" features, like CMS for example..., I find it hard to imagine :)

**Comment by mafdy** [comment]
Closing Due inactivity.

**Comment by ga5tan** [comment]
oh man, u gave up too fast :)
maybe someone wi take the bait ? :)
