### ISSUE TITLE
Conditional Dialog button Formatting

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4181]
Hello 
Happy New Year 
I want to change the style of toolbar button in some condition?
How to access Toolbarbutton css in xDialog.ts file?

**Comment by dfaruque** [comment]
`this.toolbar.element` is a jquery element so you can manipulate it accordingly

**Comment by dfaruque** [comment]
what do you mean by style? be specific, please.

**Comment by MaziarSangi** [comment]
@dfaruque
I want to change background-color of one of toolbarbutton in afterloadEntity() in case of some conditions. Can you please give one example ?
