### ISSUE TITLE
How to load the header table only without loading its child 

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#4182]
I have an entity with one header and 5 childs, and I want to load only the header table records without loading its childs. until I select a specific header record to be displayed in the entity form.
now,when I check the profiler ,it loads all header records[100 record] and its childs so if i have 100 record in the header and each one contains 1000 record the system loads 100*1000 record --> 100,000 record.

please advise.

**Comment by volkanceylan** [comment]
Serenity doesn't load child records unless you add MinSelectLevel etc, or explicitly ask for it.

**Comment by dfaruque** [comment]
I have also noticed that
If load the order page https://serenity.is/demo/Northwind/Order
it brings the orders with details
![listresponse](https://user-images.githubusercontent.com/16621563/50636866-e04f4500-0f81-11e9-91bf-76cac4250330.png)

**Comment by volkanceylan** [comment]
Hmm, must be caused by MasterDetailRelation, need to check

**Comment by volkanceylan** [comment]
Ok add MinSelectLevel(SelectLevel.Details) to the property.

**Comment by amrgDev** [comment]
thanks for your efforts
it is working now.
