### ISSUE TITLE
'Import from Excel' function for master and detail both

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4183]
Good afternoon,

I would like to see if someone could help me how to **Import** data in both the master and detail relation table at a time from excel sheet

**Comment by ga5tan** [comment]
You can import anyway u like it.
I would venture to guess simplest is to have first bunch of columns to insert as master (while they are still the same) and rest insert as details.
at least that's I saw MD in Excel to look like.
What's your format?

**Comment by Shraddha996** [comment]
hello! @ga5tan 
Actually, I write code in the same endpoint below the master code by separating them into 2 worksheets.
similarly, my excel file also contains 2 different Sheets for Master and Detail table
But the problem is while importing it did not insert the ID field value i.e. ItemId, BuyerId, and PrId
For reference am attaching both the endpoint code and excel file
It would be great if you help with this.
[PR.xlsx](https://github.com/volkanceylan/Serenity/files/2735511/PR.xlsx)
`
namespace Serene1.abc.Endpoints
{
    using abc.Entities;
    using abc.Repositories;
    using OfficeOpenXml;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Web.Mvc;
    using MyRow = PurchaseRequisition.Entities.TblPrRow;
    using MyRow1 = PurchaseRequisition.Entities.TblPrTranRow;
    using Mono.Collections.Generic;
    using NUglify.Helpers;
    using CsQuery.ExtensionMethods.Internal;
    using StackExchange.Exceptional.Extensions;
    using Serene1.PurchaseRequisition.Entities;
    using Serene1.PurchaseRequisition.Repositories;

    [RoutePrefix("Services/abc/ImportPRExcel"), Route("{action}")]
    [ConnectionKey(typeof(MyRow)), ServiceAuthorize]
    public class ImportPRExcelController : ServiceEndpoint
        {
            [HttpPost]
            public ExcelImportResponse ExcelImport(IUnitOfWork uow, ExcelImportRequest request)
            {
                request.CheckNotNull();
                Check.NotNullOrWhiteSpace(request.FileName, "filename");

                UploadHelper.CheckFileNameSecurity(request.FileName);

                if (!request.FileName.StartsWith("temporary/"))
                    throw new ArgumentOutOfRangeException("filename");

                ExcelPackage ep = new ExcelPackage();
                using (var fs = new FileStream(UploadHelper.DbFilePath(request.FileName), FileMode.Open, FileAccess.Read))
                    ep.Load(fs);

                var p = TblPrRow.Fields;
                var d = TblDepartmentRow.Fields;
                var pt = TblPrTranRow.Fields;
                var i = TblItemRow.Fields;
                var b = TblBuyerRow.Fields;


            var response = new ExcelImportResponse();
                response.ErrorList = new List<string>();

                var worksheet = ep.Workbook.Worksheets[1];
                for (var row = 2; row <= worksheet.Dimension.End.Row; row++)
                {
                    try
                    {
                    ///////////////////CustomerName
                    var PRNo = Convert.ToString(worksheet.Cells[row, 5].Value ?? "");
                    if (PRNo.IsTrimmedEmpty())
                        continue;

                    var PR = uow.Connection.TryFirst<TblPrRow>(q => q
                        .Select(p.PrId)
                        .Where(p.PRNo == PRNo));

                    if (PR == null)
                        PR = new TblPrRow
                        {
                            PRNo = PRNo
                        };
                    else
                    {
                        // avoid assignment errors
                        PR.TrackWithChecks = false;
                    }
                    ////////////////////Department
                    var DepartmentName = Convert.ToString(worksheet.Cells[row, 1].Value ?? "");
                    if (!string.IsNullOrWhiteSpace(DepartmentName))
                    {
                        var Department = uow.Connection.TryFirst<TblDepartmentRow>(q => q
                            .Select(d.DepartmentId)
                            .Where(d.DepartmentName == DepartmentName));

                        if (Department == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": Department with name '" +
                                DepartmentName + "' is not found!");
                            continue;
                        }

                        PR.DepartmentId = Department.DepartmentId.Value;
                    }
                    else
                        PR.DepartmentId = null;
                    ///////////////////////////////////
                    PR.PrDate = Convert.ToDateTime(worksheet.Cells[row, 2].Value ?? 0);
                    PR.IndentorName = Convert.ToString(worksheet.Cells[row, 3].Value ?? "");
                    PR.Note = Convert.ToString(worksheet.Cells[row, 4].Value ?? "");
                    
                    ////////////////////PRId
                    if (PR.PrId == null)
                        {
                            new TblPrRepository().Create(uow, new SaveRequest<MyRow>
                            {
                                Entity = PR
                            });

                            response.Inserted = response.Inserted + 1;
                        }
                        else
                        {
                            new TblPrRepository().Update(uow, new SaveRequest<MyRow>
                            {
                                Entity = PR,
                                EntityId = PR.PrId.Value
                            });

                            response.Updated = response.Updated + 1;
                        }
                }
                    catch (Exception ex)
                    {
                        response.ErrorList.Add("Exception on Row " + row + ": " + ex.Message);
                    }
                }

            /////////////////////////////////////////////////////////////////PRTran/////////////////////////////////////////////////////////////////////////////////////
            var worksheet2 = ep.Workbook.Worksheets[2];
            for (var row = 2; row <= worksheet2.Dimension.End.Row; row++)
            {
                try
                {
                    ///////////////////PrTran(AdditionalDescription)
                    var AdditionalDescription = Convert.ToString(worksheet2.Cells[row, 4].Value ?? "");
                    if (AdditionalDescription.IsTrimmedEmpty())
                        continue;

                    var PRTran = uow.Connection.TryFirst<TblPrTranRow>(q => q
                        .Select(pt.PrTranId)
                        .Where(pt.AdditionalDescription == AdditionalDescription));

                    if (PRTran == null)
                        PRTran = new TblPrTranRow
                        {
                            AdditionalDescription = AdditionalDescription
                        };
                    else
                    {
                        // avoid assignment errors
                        PRTran.TrackWithChecks = false;
                    }
                    ///////////////////ItemId(ItemName)
                    var ItemName = Convert.ToString(worksheet2.Cells[row, 1].Value ?? "");
                    if (!string.IsNullOrWhiteSpace(ItemName))
                    {
                        var Item = uow.Connection.TryFirst<TblItemRow>(q => q
                            .Select(i.ItemId)
                            .Where(i.ItemName == ItemName));

                        if (Item == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": Item with name '" +
                                ItemName + "' is not found!");
                            continue;
                        }

                        Item.ItemId = Item.ItemId.Value;
                    }
                    else
                        PRTran.ItemId = null;
                    ///////////////////PRId(PRNo)
                    var PRNo = Convert.ToString(worksheet2.Cells[row, 2].Value ?? "");
                    if (!string.IsNullOrWhiteSpace(PRNo))
                    {
                        var PR1 = uow.Connection.TryFirst<TblPrRow>(q => q
                            .Select(p.PrId)
                            .Where(p.PRNo == PRNo));

                        if (PR1 == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": PR1 with name '" +
                                PRNo + "' is not found!");
                            continue;
                        }

                        PR1.PrId = PR1.PrId.Value;
                    }
                    else
                        PRTran.PrId = null;
                    ///////////////////BuyerId(BuyerName)
                    var BuyerName = Convert.ToString(worksheet2.Cells[row, 3].Value ?? "");
                    if (!string.IsNullOrWhiteSpace(BuyerName))
                    {
                        var Buyer = uow.Connection.TryFirst<TblBuyerRow>(q => q
                            .Select(b.BuyerId)
                            .Where(b.BuyerName == BuyerName));

                        if (Buyer == null)
                        {
                            response.ErrorList.Add("Error On Row " + row + ": Buyer with name '" +
                                BuyerName + "' is not found!");
                            continue;
                        }

                        Buyer.BuyerId = Buyer.BuyerId.Value;
                    }
                    else
                        PRTran.BuyerId = null;
                    ///////////////////////////////////
                    PRTran.Quantity = Convert.ToDecimal(worksheet2.Cells[row, 5].Value ?? "");
                    PRTran.Rate = Convert.ToDecimal(worksheet2.Cells[row, 6].Value ?? "");
                    PRTran.Amount = Convert.ToDecimal(worksheet2.Cells[row, 7].Value ?? "");
                    PRTran.DeliveryReqDate = Convert.ToDateTime(worksheet2.Cells[row, 8].Value ?? "");
                    PRTran.PendingPrQuantity = Convert.ToDecimal(worksheet2.Cells[row, 9].Value ?? "");
                    PRTran.Unit = Convert.ToString(worksheet2.Cells[row, 10].Value ?? "");

                    /////////////PRtranId
                    if (PRTran.PrTranId == null)
                    {
                        new TblPrTranRepository().Create(uow, new SaveRequest<MyRow1>
                        {
                            Entity = PRTran
                        });

                        response.Inserted = response.Inserted + 1;
                    }
                    else
                    {
                        new TblPrTranRepository().Update(uow, new SaveRequest<MyRow1>
                        {
                            Entity = PRTran,
                            EntityId = PRTran.PrTranId.Value
                        });

                        response.Updated = response.Updated + 1;
                    }

                }
                catch (Exception ex)
                {
                    response.ErrorList.Add("Exception on Row " + row + ": " + ex.Message);
                }
            }

            return response;
            }
    }
}

`

**Comment by ga5tan** [comment]
What do u mean you did not insert  'ItemId, BuyerId, and PrId' ?
You most likely have to insert them. form you code it seems, like you are trying to look them up.
Are you sure you are using the correct columns? did you try to step through code in debugger to see actual values you are looking up?

**Comment by Shraddha996** [comment]
@ga5tan 
Yes I want to insert all 3 ID's and I also debug the code, all values showing correctly but at the end, the ID columns are empty
I don't know what's wrong with this

**Comment by ga5tan** [comment]
lol
dude!
you are assigning found ID to found entity???
Buyer.BuyerId = Buyer.BuyerId.Value;
what's the point?
u ABSOLUTELY MUST assign it to the entity being saved !!!
