### ISSUE TITLE
Export Charts to PDF?

### ISSUE THREAD

**Issue by ReatKay** [volkanceylan/Serenity#4184]
Hello Serenitos :)
I'm wondering: Is there any way or workaround to export charts to PDF? I know, the pdf export is based on the grid (html/text) and the charts are based on svg. Is there maybe any option to render the chart and put the render inside a grid to include it to the pdf? 
I know, quite a a deep one - I don't expect like example code or a complete "how to" - just wanna know, if its even possible and if any of you already realized.

Thankful for any hint.

All the best from Switzerland

**Comment by volkanceylan** [comment]
Did you try with WKHMTML?
