### ISSUE TITLE
Please advise : Error 404 and Error 500 on prod server + Linux 18.0.4

### ISSUE THREAD

**Issue by mugambiwarwema** [volkanceylan/Serenity#4186]
Hello, thank you for this wonderful template and well documented. 
I Followed your docs and was able to implement it to a multi-tenant system 

My dev environment is Win10, VS-Community 2017, MySql. 

Everything works well, and was able to publish my app to /bin/Release

When I ran the published app from cmd all is well. 

When I deploy and run it behind a reverse-proxy (nginx), my trouble begin. What do I mean, 

When I open Vehicles model from my prod server I get the errors

`POST http://1xx.1xx.5x.6x/Services/Vehicles/Vehicledetail/List 500 (Internal Server Error)`
`jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:9600`

Similarly, when I open Administration/Users Management it opens up OK. However, when I click on New User, i get the error as seen in the attached Image. 

All tables/rows I added that did not come with the template seem to have an issue and I think I missed a step. 

here's my VehiclesRow.cs and UserRow.cs files attached as well. 

Please point this lad whose trying to earn his coin in this wonderful 2019.
[prod.zip](https://github.com/volkanceylan/Serenity/files/2731263/prod.zip)

**Comment by mugambiwarwema** [comment]
@volkanceylan 

Any comments in this issue, please?

**Comment by volkanceylan** [comment]
Sorry, its probably about your reverse proxy.
