### ISSUE TITLE
Multi Tenancy - Administration:Tenants Not Visible

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4188]
I have downloaded multitenancy demo project and I have created 3 users as belwo
User1 : Tenant1
User2 : Tenant2
User3 : Tenant3

but when I click on Edit Permissions Tab I can't see Permission Keys for Administration:Tenants

**Comment by samdubey** [comment]
follow multitenancy tutorial thoroughly

**Comment by ga5tan** [comment]
just my 2 cents. AFAIK (from tutorial) permissions down show up, if they are not used. it's not my experience though

**Comment by TechAspirant** [comment]
Hello,

Its working but in my case I have created role for Tenant2 which is visible in Tenant1 UserDialog -> Edit Roles tab. It is hidden in Role menu but visible in user dialog
How can I make it hide for other tenants ?

**Comment by TechAspirant** [comment]
Adding below code in RoleRow solved my issue
[LookupScript("Administration.Role", LookupType = typeof(MultiTenantRowLookupScript<>))]
