### ISSUE TITLE
Grid sorunu

### ISSUE THREAD

**Issue by Osman06** [volkanceylan/Serenity#419]
Merhaba,
Yeni oluşturduğum projede Serenity'i submodule olarak ekledim ve Northwind dosyalarını felan sildim. Fakat şöyle bir hatayla karşılaştım. Yeni kayıt eklediğimde veriler gride düşmüyor. Ajax ile veriler geliyor fakat gridde görüntülenmiyor. Ek'te resimde görebilirsiniz.Ancak sayfa yenilersem verileri görebiliyorum. Bir dosyayı yanlışlılka silmişde olabilirim. Git üzerinden inceledim fakat bulamadım. Yardımcı olabilir misiniz ?

![hata](https://cloud.githubusercontent.com/assets/8321089/13813726/d31d2d1a-eb8b-11e5-903d-e05915708f17.jpg)

**Comment by volkanceylan** [comment]
1.9.20 den falan oluşturmuşsunuzdur, 1.9.24 ya da direk Serenity altından slickgrid ile alakalı klasörleri full alın

**Comment by Osman06** [comment]
Teşekkürler sorun düzeldi.
