### ISSUE TITLE
Calling list service with ColumnSelection.Details does not retrieve the details (MasterDetail)

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4192]
The issue #4182 is solved by the following commit
bd0af2b2eec717b944a1308e40124f0153e5585e

but sadly, a new issue is introduced

when I call the list service by passing ColumnSelection.Details It should retrive all columns.
but now it does not retrive DetailList
You may check this by calling the following
  `StartSharp.Northwind.OrderService.List({ ColumnSelection: 2, Take: 10});` 
2 is `ColumnSelection.Details`

also 2nd level detail does not retrieved by calling x.xService.Retrieve or opening a record by dialog.

**Comment by dfaruque** [comment]
BTW, `StartSharp.Northwind.OrderService.List({ IncludeColumns: ['DetailList'], Take: 10});` is working as expected.

**Comment by volkanceylan** [comment]
Read the notes in list and retrieve handlers. 
It is working as designed. As loading detail rows is an expensive operation in list, it is only loaded if column is visible, e.g. explicitly included.
