### ISSUE TITLE
Update repository

### ISSUE THREAD

**Issue by rarunkumar454** [volkanceylan/Serenity#4193]
Hi i like this platform platform very nice, i have struggle in update repository. I try to update values from one repository to another repository how can i do (I try to update bulk operation particular record with some condition using store procedure).

**Comment by ms4hafiz** [comment]
What is your procedure and where you want to call it? from dialog or grid?

**Comment by rarunkumar454** [comment]
USE [Myapplication_Default_v1]
GO
/****** Object:  StoredProcedure [dbo].[S1_cursor]    Script Date: 29-01-2019 16:39:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[S1_cursor]
(
		      @Department VARCHAR(50),
              @Semester VARCHAR(50),
              @CourseFee int,
              @ExamFee int,
              @SportFee int
			  --@Total int
)
AS
BEGIN
      SET NOCOUNT ON;
	   DECLARE @Sname VARCHAR(50)
       DECLARE @counter INT
       SET @counter = 1
	   DECLARE S CURSOR 
       FOR
	   SELECT Sname
       FROM S1 WHERE Department = @Department and Semester = @Semester
	   OPEN S
	   FETCH NEXT FROM S INTO
	   @Sname
	   WHILE @@FETCH_STATUS=0
       BEGIN
            UPDATE S1 SET CourseFee = @CourseFee,ExamFee = @ExamFee,SportFee = @SportFee, Total = CourseFee+ExamFee+SportFee
            WHERE Department = @Department and Semester = @Semester 
            SET @Counter = @Counter + 1
            FETCH NEXT FROM S INTO
			@Sname 
       END
     CLOSE S
   DEALLOCATE S
END

This is my store procedure can i call from Dialog.

**Comment by stixoffire** [comment]
Put your stored procedure function call in your xyzrepository and then from your dialog call that.
There is an example in the forum look at this issue and follow the information posted - or search forum for Stored Procedure.

[2593 Stored Procedure](https://github.com/volkanceylan/Serenity/issues/2593)
