### ISSUE TITLE
How to show a column that is hidden?

### ISSUE THREAD

**Issue by galemos** [volkanceylan/Serenity#4194]
I put a [Hidden] notation in the Column Field and now and I use this grid in 2 screen, one shouldn't show this field and the other must show.

So how do i show a field that have the [Hidden] notation?
```
[ColumnsScript("Default.Declaracao")]
[BasedOnRow(typeof(Entities.DeclaracaoRow), CheckNames = true)]
public class DeclaracaoColumns
{
    ...
    [Hidden]
    public Int32 QtdDependente { get; set; }
}
```

When i do this to a Form Field I can show the field with "q.showField(this.form.NameField)", exist any "show" for a column that i can put inside the get columns?

I already have 2 Grid.ts file, each one has its own behavior. I just need to show this hidden column ( I think is something in the getColumns() method, but i couldn't figure out what)

**Comment by volkanceylan** [comment]
Create two Columns classes

**Comment by volkanceylan** [comment]
Or override getColumns and filter the column in one grid

**Comment by galemos** [comment]
Thanks @volkanceylan
