### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4196]
How can I use multitenancy such that I want to add tenants in tenants ?

**Comment by IT-LCEC** [comment]
Will the sub-tenants be able to see each other? Or does the tenant manage multiple sub-tenant and the tenant can see all the sub-tenants?

If it is the second scenario, I am working on this right now. If I get it working, will share.

**Comment by TechAspirant** [comment]
yes I want second scenario.
It will be a great help if you can share.
If wanted I can also help or conteibute if wanted

**Comment by TechAspirant** [comment]
@IT-LCEC Any success ?

**Comment by IT-LCEC** [comment]
Still working on it. Should be ready by end of this week at latest. I had to finish up another task first.

**Comment by TechAspirant** [comment]
@IT-LCEC Ok Please do share your demo project for my reference.

**Comment by VR-Architect** [comment]
Take a look at this. Each table in the database has a TenantId, but it also has a SubTenantId (I called this a child). That code presents sub-tables (children) with a foreign key to the primary table (the parent). To make the code work, make sure to honor the capital casing and replace Parent/parent and Child/child with your table names. 

For example, my parent table is call associations. And associations have child tables containing rows of data which needs to only be seen by the correct association. 

Note, with this code you will have to ensure the right permissions are set for the user. All code was sourced from the samples project in the Northwind's module, Customer folder and Orders tab. So full kudos to Volkan!

https://github.com/volkanceylan/Serenity/issues/4231

**Comment by TechAspirant** [comment]
@IT-LCEC done with your sample code sir ?

**Comment by TechAspirant** [comment]
@IT-LCEC  Any success sir ?
