### ISSUE TITLE
Disable a Select2 control programmatically (from xyzDialog)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#420]
Dear @volkanceylan,
I'm trying to disable a Select2 control from the parent (I mean container) dialog, but with no luck.
The same operation on a toolbar button was easy instead:

`toolbar.FindButton("xyz-button").Hide();`

but if I get a reference to the LookupEditor with the syntax form.MyLookupEditor then I cannot modify the enabled/disabled propery.

I also tried to get the control with the `form.ById()` syntax and then adding a readonly class, but once again it remain enabled...what I'm doing wrong?

Thanks for you support
Regards

**Comment by volkanceylan** [comment]
EditorUtils.SetReadOnly(form.MyField, true)

**Comment by marcobisio** [comment]
Perfect...thank you very much!!

**Comment by wldkrd1** [comment]
How has this changed with the move to typescript?
![setreadonly](https://cloud.githubusercontent.com/assets/2817543/17560840/6d2f2c18-5ed8-11e6-890a-b70617d50925.png)

**Comment by volkanceylan** [comment]
In TypeScript you have to type "this" to access members, if it is what you ask.

**Comment by wldkrd1** [comment]
No...the image I attached showed the code and error message
`protected afterLoadEntity() {
            if (this.entity.FindingTypeId === 1) {
                Serenity.EditorUtils.setReadOnly(this.form.FindingType, true);
            }
}`

`0x800a139e` - JavaScript runtime error: Searching for widget of type 'Serenity.LookupEditor' on a non-existent element! (#ServerReview_Review_PolicyTestResultDialog10_FindingType)`

**Comment by volkanceylan** [comment]
so, in your form there is no form element / property with name "FindingType"

**Comment by wldkrd1** [comment]
Here's the typescript for the form:

`namespace ServerReview.Review {
    export class PolicyTestResultForm extends Serenity.PrefixedContext {
        static formKey = 'Review.PolicyTestResult';

    }

    export interface PolicyTestResultForm {
        PolicyTestName: Serenity.StringEditor;
        NodeLabel: Serenity.StringEditor;
        State: Serenity.StringEditor;
        FindingType: Serenity.LookupEditor;
        CreationTime: Serenity.DateEditor;
        Expected: Serenity.TextAreaEditor;
        Actual: Serenity.TextAreaEditor;
        Comments: Serenity.TextAreaEditor;
    }

    [['PolicyTestName', () => Serenity.StringEditor], ['NodeLabel', () => Serenity.StringEditor], ['State', () => Serenity.StringEditor], ['FindingType', () => Serenity.LookupEditor], ['CreationTime', () => Serenity.DateEditor], ['Expected', () => Serenity.TextAreaEditor], ['Actual', () => Serenity.TextAreaEditor], ['Comments', () => Serenity.TextAreaEditor]].forEach(x => Object.defineProperty(PolicyTestResultForm.prototype, <string>x[0], { get: function () { return this.w(x[0], (x[1] as any)()); }, enumerable: true, configurable: true }));
}
`

**Comment by wldkrd1** [comment]
Ahh, I had to rerun the T4 templates, the ts was out of date. Working now.
