### ISSUE TITLE
File Upload File Type

### ISSUE THREAD

**Issue by MarkTeqDeveloper** [volkanceylan/Serenity#4200]
How to validate file type .
i want to upload only .jpeg file.

**Comment by MarkTeqDeveloper** [comment]
> @MarkTeqDeveloper Try this:
> 
> `this.form.YOUR_CONTROL.element.find("input:file").attr("accept", ".jpeg");`

hi @minhhungit 
i am a new in asp .net core and serenity, 
can you explain me in which file(demoColumns.cs,DemoDialog.ts,DemoIndex.xshtml etc) i can paste this code ?

plz help me.

**Comment by minhhungit** [comment]
@MarkTeqDeveloper , I guess you will need to place it in constructor of Dialog.ts

**Comment by MarkTeqDeveloper** [comment]
@minhhungit , i pasted your code in Dialog.ts but it can just filter the files as "CustomFiles", when i select Other options in File dialog, "All Files" than it can show other files(.png,.gif) and i also select those type of files and save.but it not validate only .jpeg file format properly.

protected afterLoadEntity() {
            super.afterLoadEntity();
            this.form.ProductImage.element.find("input:file").attr("accept", "image/jpg, image/jpeg");
        }

**Comment by minhhungit** [comment]
it's everything I know, about All Files options I think you have to validate it at server side
