### ISSUE TITLE
Separate DB user for Migrations

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#4203]
This is not specific to Serenity, but maybe somebody can give suggestions here...

In the connection string in Web.config we specify the credentials for the database. This user must have permissions to run arbitrary SQL code on the database. Schema-related changes like CREATE TABLE / DROP TABLE / ALTER VIEW etc. This user will probably be dbo/sa. This is so the migrations can run successfully.

Once the migrations have run, all the queries from the App server to the database will only be data-related, like SELECT x FROM y / INSERT / DELETE / UPDATE WHERE x = y / EXECUTE PROCEDURE etc. This user can be "sql_user_1" and this user only needs permissions to read/write/update data (we can configure this on the database/server level).

I would prefer not to have the credentials for dbo/sa saved in the connection string.

So my question is **how do you guys manage/run your migrations**?
* Do you deploy and keep your dbo user credentials in your app connection string?
* Do you deploy with a "data-only" user in the connection string, then run your migrations manually from your local environment?
* Do you  have a separate web server connecting as dbo to run these migrations?

Any answers/thoughts/suggestions are welcome...

Thanks!
Edward

**Comment by IT-LCEC** [comment]
I use dbo full perms when developing against dev-DB. Then switch the credentials to standard db user perms when migrating to test and prod. Of course, to do this you would not be running the migrations in Serenity. I prefer to run a tool like RedGate's compare tool to compare prod to dev, then it spits out an update script. The DBA would then run this update script on test, then prod. 

Just my 2 cents.

**Comment by edwardch** [comment]
Thanks @IT-LCEC.

I had thought about this approach and figured it might be difficult to get CI working, unless some machine/process had the rights to run with full dbo permissions.

I use Azure DevOps and it's pretty easy to get it working when dbo's credentials are in the app server's config. I have a few sites running (one instance per customer, I'm not using multi tenancy) so running a RedGate compare (or SQL Delta) might become tedious if I get a lot more customers.

I don't know enough about Azure Key Vault to know if that might be a viable option, but if I do find out I will post that here.

Thanks for your cents!

**Comment by edwardch** [comment]
@volkanceylan do you think it would be worthwhile having a "SkipMigrations" appSetting we could use instead of commenting out the safety check in the SiteInitialization.Migrations.cs file?

It could be added as a condition to the safety check as well.

Unless you have a different way of managing that?

Thanks!

**Comment by volkanceylan** [comment]
You may use some config setting, it works fine as is
