### ISSUE TITLE
Generate custom HTML from table

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4204]
Hi

I am currently using regular SlickGrid with three mixin.
I need to make top level items look more "attractive" (bigger - distinctive) compared to second level items.

One way how I thought I could achieve this would be to generate elements like this:
![image](https://user-images.githubusercontent.com/36483170/51096564-34ff8500-17f8-11e9-83f7-229ca4585613.png)

for each top level item, with it's details inside, so it can be collapsed.
It's from Dashboard v2.

Any idea where/how to start? Is there sample in Serene or Start# for this?

Other way would be restyle three grid somehow

thx

**Comment by hubeyb** [comment]
you can start form this example: https://serenity.is/demo/BasicSamples/InlineImageInGrid

and codes: https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineImageInGrid

calculate and get level of tree from row data then you must write a slickgrid formatter.
you can write any html template in any conditions with this row data.

**Comment by hubeyb** [comment]
And also will use threegrid mixin.

**Comment by ga5tan** [comment]
THX
Yeah, I am already using treegrid mixin. I just need to make top level thicker and fancier than children.
How do I figure out level from row's data or mixin?

thx again

**Comment by JohnRanger** [comment]
@ga5tan  
Maybe check if the current item has a parent - and if not, then it is a top level item and you can style it differently.

**Comment by hubeyb** [comment]
I gave this sample before  https://serenity.is/demo/BasicSamples/InlineImageInGrid

look at this sample's code below, you can use InlineImageFormatter to format your grid cells.
only find the index you achived and wrote your custom htmls in "if else" statement.

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineImageInGrid/InlineImageFormatter.ts
