### ISSUE TITLE
Customize order details dialog Title (and generally dialog titles)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#421]
Dear @volkanceylan,
I've implemented a master detail relationship like order vs order details in Northwind sample.
Everything is working fine but I noticed that in the dialog there isn't the NameField in the title:
![image](https://cloud.githubusercontent.com/assets/17425690/13820040/f2898b2a-eb9b-11e5-862d-4153c2cb81ef.png)

I was wondering if there is a way to show the NameField like in the other dialogs:
![image](https://cloud.githubusercontent.com/assets/17425690/13820085/1cfe59c6-eb9c-11e5-8f05-ec0d4531f073.png)

Moreover, I tried to customize a (different) dialog title by creating the correspondent class in Texts.cs, but without any luck...which is the canonical way to do that?

Thank as usual for your kind support
Best Regards

**Comment by volkanceylan** [comment]
There is NameProperty attribute on dialogs for that

**Comment by marcobisio** [comment]
True, but I can customize the entire string and not only the NameProperty?
I mean if I want to replace "Edit something" with "Something details etc etc" because the entire dialog is read only...obviously not globally, but for a single entity...

Thanks

**Comment by volkanceylan** [comment]
Then override UpdateTitle method and set Title property to something you like

**Comment by marcobisio** [comment]
Everytime that I think "perhaps such thing cannot be done" I always realize that the problem is between the keyboard and the chair :D

Thanks again

**Comment by marcobisio** [comment]
Forgot to close sorry
