### ISSUE TITLE
Need help getting a logged user

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4212]
Hi;
I am trying to get UserName in Controller. I have created the following but it is  not working. Any idea please.

       [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ServiceFee serviceFee)
        {

            string userName = Serenity.Authorization.Username;
         .....
        }

**Comment by Estrusco** [comment]
Try with

```cs
var userName = ((UserDefinition)Authorization.UserDefinition).Username;
```
