### ISSUE TITLE
Grouping in Grid with Expression fields

### ISSUE THREAD

**Issue by qfleurat** [volkanceylan/Serenity#4213]
I am adding grouping to my grid, the Grouping displays as it should as long as the row fields are in grid columns.ts and are visible.  The Field I am grouping on is defined as “Expression("jReference.[Category]")” using a ForeignKey.   If I use a row field from the main table it does not need to be visible or even included in the columns.ts and the grid will be grouped correctly on the the field.   How do I group on expression fields without them being visible?

`onClick: () => this.view.setGrouping(
                        [{
                            getter: AllocateDetailRow.Fields.Category
                        }])`

Thanks
Quentin

**Comment by ga5tan** [comment]
try to tak field in Columns.cs with
[Visible(false)] ?

**Comment by qfleurat** [comment]
Yes, I tried Visible, Hidden and FilterOnly.  The group row show "undefined"

**Comment by volkanceylan** [comment]
Set min select level to list or use setIncludeColumns to always load the field

**Comment by qfleurat** [comment]
Thanks, worked good.
