### ISSUE TITLE
Increase menu bottom padding

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#4215]
Minor issue: I recommend increasing the bottom padding of the menu to be above where Chrome shows the link under the mouse. It is hiding the last menu item in future release.

![image](https://user-images.githubusercontent.com/5250669/51256085-90ee1900-1972-11e9-9b04-56b51892f0e0.png)

**Comment by hubeyb** [comment]
unfortunately this general issue of chrome. maybe can be fix by override the css.
