### ISSUE TITLE
Is it possible to turn off Anti Forgery security measures?

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#4217]
I am working with a calendar framework that has a form (that I am unable to edit, otherwise I would put a @Html.AntiForgeryToken) that seems not to have an anti forgery token. Is there a way to disable the security measure entirely (or for this one instance)? Since this is an intranet project I am not too worried about the security implications.

More details: when I create/update an event on the calendar, a modal popup box appears. Once I press create/update, a method SHOULD be running, however, I get this error: https://pastebin.com/MMvbW31Y . The error displays in a pop up dialog on top of my serenity as plaintext html (meaning I can see all the tags).

Any help is greatly appreciated.

**Comment by volkanceylan** [comment]
Search for autovalidateanti etc in code and remove relevant lines

**Comment by MarcusOy** [comment]
This worked, thanks!

More information for future reference: 
1. Make sure that no tags/attributes regarding antiforgery are present in your controllers/cshtmls etc.
2. Go to FilterConfigs.cs. This class is located in the App_Start folder in my solution. 
3. Comment out these two lines:
```
filters.Add(new Serenity.Services.AntiforgeryCookieResultFilter());
filters.Add(new Serenity.Services.AutoValidateAntiforgeryTokenAttribute());
```
