### ISSUE TITLE
Concat multiple values from a LeftJoin

### ISSUE THREAD

**Issue by kstanki2** [volkanceylan/Serenity#4218]
I have 2 tables named NetworkDevice and StaticIP. The StaticIP table has a field called DeviceID which is a foreign key from NetworkDevice, this is so multiple IP's can be assigned to one device if needed. 

On my NetworkDevice grid I want to display any assigned IPs in a column. I can do this with a LeftJoin in NetworkDeviceRow.cs as an attribute of the class:

    [LeftJoin("ip","StaticIp","ip.[DeviceID] = T0.[ID]")]

and then display the IP like this:

[DisplayName("IP Address"), Expression("ip.IpAddress")]
        public String IpAddress
        {
            get { return Fields.IpAddress[this]; }
            set { Fields.IpAddress[this] = value; }
        }

This works fine as long as no device has multiple IPs assigned. If they do then you get an error because the LeftJoin returns multiple results with the same ID. My question is how do I take those results and concatenate the multiple IPAddress fields into a single field, and display it as one record to avoid that error?

**Comment by volkanceylan** [comment]
Put LeftJoin on top of row and write expression there

**Comment by kstanki2** [comment]
This is how I solved it in case anyone runs into a similar situation. I got rid of the LeftJoin attribute altogether and did everything in the expression with the STUFF sql function:

        [DisplayName("IP Address"), Expression("STUFF((Select ', ' + IPAddress From StaticIP ip where ip.DeviceID = T0.ID For XML Path('')), 1, 1, '')")]
        public String IpAddress
        {
            get { return Fields.IpAddress[this]; }
            set { Fields.IpAddress[this] = value; }
        }

**Comment by MoheebP** [comment]
Is there anyway to avoid such subquery? Such subquery is increasing execution time
