### ISSUE TITLE
Can serenity work with entity framework Code First Migration?

### ISSUE THREAD

**Issue by tusharuit25** [volkanceylan/Serenity#4219]
Instead of fluent migration?

**Comment by jaamkamran** [comment]
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q/videos?disable_polymer=1
Subscribe my channel for serenity

**Comment by volkanceylan** [comment]
Serenity doesnt depend on any migration, remove our migration code, write your own

**Comment by ra-bedo11** [comment]
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q/videos?disable_polymer=1
This Code is deleted !!!! Why
