### ISSUE TITLE
Serenity flat design

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4220]
Looking at the demo i noticed the slight modifications on button designs.

![image](https://user-images.githubusercontent.com/31513956/51427238-dbcb9300-1bf5-11e9-99b1-2730f90c27a6.png)
Is this something available in future version ? (i have updated my serenity.web.assets to 3.8.6 but cannot find this design - still having the classic raised buttons).

Thanks volkan, this is giving a more modern design to buttons

**Comment by volkanceylan** [comment]
Thanks, it will be available in next StartSharp release, still in progress.

**Comment by minhhungit** [comment]
I like new style too, hope you can share it with common users, not only StartSharp

**Comment by volkanceylan** [comment]
The theme is now released in Start#
