### ISSUE TITLE
lookup filter in dialog (do not duplicate)

### ISSUE THREAD

**Issue by WendyBurgerHsu** [volkanceylan/Serenity#4221]
Hello everyone!
I am working a lookup filter.
Is is possible Don't appear this value when the grid has a value of lookup filter.
just like my pic.
![image](https://user-images.githubusercontent.com/44994587/51469810-2e02e480-1dad-11e9-8e12-f085d9151220.png)

My OP department has selected Import, Export, etc.
So my lookup should not show these values again.
But my other departments(like MARKET) have to display all the values on the lookup,
because it has not selected any SECTIONS yet.

Any help is greatly appreciated.

**Comment by WendyBurgerHsu** [comment]
Hi @ga5tan ,
I tried to do cascade field, but it didn't work..

here is myDialog() below:
```
protected afterLoadEntity() {
            super.afterLoadEntity();
            if (this.entity.DeptId != null) {
                Serenity.EditorUtils.setReadOnly(this.form.DeptId, true);
                this.form.CompanyCode.getGridField().toggle(false);
                //(this.entity.DeptId as any).cascadeFrom;
                //(this.entity.SecId as any).cascadeValue;
                //this.form.DeptId.cascadeField;
                //this.form.SecId.cascadeValue;
            }

            else{
                this.form.SecId.getGridField().toggle(false);
                //this.form.CompanyCode.cascadeField;
                //this.form.DeptId.cascadeValue;
                //(this.entity.CompanyCode as any).cascadeFrom;
                //(this.entity.DeptId as any).cascadeValue;
            }
        }
```

Well..maybe I misunderstood what you mean?
Thanks!

**Comment by ga5tan** [comment]
this is the sample:
FilteredLookupInDetailDialog.ts

**Comment by WendyBurgerHsu** [comment]
Hi @ga5tan ,

```
DepartmentService.GetSelectableDepartments(rec, (res) => {
                    res.Entities.forEach((v, i, a) => {
                        this.form.DeptId.addOption(v.DeptId.toString(), v.Department, { Codevalue: v.DeptId }, false);
                    })
                });
```
here is my code, I reset the value of lookup, and insert sections that are not under the department.

Thanks for your advice :)
