### ISSUE TITLE
Fixed navigation bar in dialog

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4225]
Hi everyone,

I'm trying to make the navigation bar in a dialog in panel mode to keep at a fixed position. So if the dialog is scrollable you can allways see and use the navigation. 

I tried to change some css properties to keep it at 'position: fixed' but with no success. Maybe there is also something simple that I might miss here. Should also be usefull for others I guess.

![image](https://user-images.githubusercontent.com/39523006/51522154-e883fd00-1e28-11e9-8366-f6844081985f.png)

Thanks for any help in advance

**Comment by hubeyb** [comment]
yes it would be useful, but there is no way to do easly. You must write your own css to achive.
