### ISSUE TITLE
Is there a way to add custom code into Serenity Import Generator

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4227]
Hi @volkanceylan and team
As title, how can I add some code to generate something into Import classes (ex: ServerTypings classes)

Can I do it without Pull request

**Comment by ga5tan** [comment]
well if you put your code in designated places, it gets generated to server typings...
also if it meets criterias (web services must have some Service* paramters)

**Comment by minhhungit** [comment]
no @ga5tan , that is not what I want to do. I want to do more, not only generate services/row/columns/form/mvc/client types...

**Comment by stixoffire** [comment]
Take a look at the Sergen source files .. you should be able to add the custom code handler in there .

**Comment by minhhungit** [comment]
@stixoffire you mean I don't need a Pull request to create custom code on Sergen tool ?

**Comment by minhhungit** [comment]
@stixoffire  yeah thanks but the reason that I don't want to create custom code is I need to update serenity in future, so I think new updates from serenity will overwrite my code.

**Comment by minhhungit** [comment]
IMHO I think serenity should provide for users an interface to do it

**Comment by minhhungit** [comment]
@volkanceylan thank you for your suggestion, I will check

**Comment by minhhungit** [comment]
Sorry but I think there is a misunderstand here, what I want to do is adding custom code into **row.ts** typescript file which is generated by t4 transform **without github pull request**.

Exactly, I want to generate lookupKey for **custom lookup** which I implemented base on **Serenity.Web.LookupScript**, more detail in this issue: https://github.com/volkanceylan/Serenity/issues/3481

![image](https://user-images.githubusercontent.com/2279508/52171893-9089b680-2797-11e9-8419-7be36b58649a.png)

After I reviewed **CustomGenerate**, I think that it does not help in this case.

**Comment by minhhungit** [comment]
I created a function with t4 template to do it, thank you all, guys
