### ISSUE TITLE
How to add Criteria ‘in’

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#4228]
I need to search the workcenterId are in a list. But i don't know how to write the Criteria. 
Below is the wrong example, could anyone help me on this, thanks very much.
[[WorkcenterTaskRow.Fields.WorkcenterId], 'in', [1,2,3]]

**Comment by ga5tan** [comment]
Below is IN with subquery.
I sincerely believe that you can replace subquery with array of hardcoded values...

> query.Distinct(true)
>                 .Select(fld.ItemId)
>                 .Select(fld.Answer)
>                 .Select(fld.AnswerText)                
>                 .Where(fld.LanguageId == 1 && 
>                 fld.IsActive == 1 &&
>                 fld.UserLoginId.In(query.SubQuery()
>                                          .From(QueryReportRes)
>                                          .Select(QueryReportRes.UserLoginId)
>                                          .Where(QueryReportRes.RequestorId == Authorization.UserId)
>                                   )
>                       );

**Comment by dfaruque** [comment]
@ga5tan I think he asks it for client-side (ts)

**Comment by edwardch** [comment]
If you need to do it from the client side have a look at the quick filter customisation in the demo [here](https://serenity.is/demo/BasicSamples/QuickFilterCustomization). (direct link to [code](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/QuickFilterCustomization/QuickFilterCustomization.ts)) 

One of the samples is "Ship Via Not IN", and you can simply remove the 'not' from the code.
