### ISSUE TITLE
JsonServiceClient

### ISSUE THREAD

**Issue by Hochmah** [volkanceylan/Serenity#4230]
Hello!

Firstly, thank you @volkanceylan for this amazing work you did!

I'm doing some tests in order to integrate two different Serenity instances, for that I trying JsonServiceClient, as the code below:
```
var client = new JsonServiceClient("http://www.mysite.com/");
client.Post<ServiceResponse>("Account/Login", 
    new LoginRequest {
        Username = "someuser",
        Password = "somepass"
    });

var list = client.Post<ListResponse<Dictionary<string, object>>>(
    "Services/Northwind/Customer/List", 
    new ListRequest {
        Take = 100
    });
```
**Using Ajax it works fine!** But I need to call from server side and I'm getting this weird SqlExeption:

```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
```

I've tried to debug using Serenity sources as described at https://serenity.is/docs/howto/how_to_debugging_with_serenity_sources, but without success. Because VS is not able to find server sources.

Indeed there is two different issues here. 

Can you guys point some directions, please?

Thank you!

**Comment by volkanceylan** [comment]
You are probably calling service while in a transaction, e.g. unit of work so effectively blocking yourself.

**Comment by volkanceylan** [comment]
Yes it is inside transaction, you may use UnitOfWork.OnCommit event to run code after transaction ends
