### ISSUE TITLE
Filtered data with grid in dialog

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#4235]
Hi all,
Below is the project am working on asp.net C#. Require help to achieve this in 
Serenity.
![screen](https://user-images.githubusercontent.com/29406374/51727698-2dab6780-2093-11e9-9ff8-916b94c79746.jpg)

Here am using two tables,
1. Class table.
2. Attendance.

Do to be done,

1. I must get the above in a dialog where there will be a dropdown to select class from the class table.
2. From Class table student roll no and student name will be filtered and listed in grid along with present and absent check buttons with system date and time.
3.  Student roll no, Student name, datetime and present or absent will be saved in attendance table on save button click.

Achieved this by using sqldatasource in asp.net.

Please guide me how i can achieve this in serenity platform

Srinivas

**Comment by srinivas1910** [comment]
Hi @Zahar661 can you help in this issue

Regards,
Srinivas

**Comment by Zahar661** [comment]
Hi, @srinivas1910  The language barrier bothers to explain, but I'll try
Have you already created a dialog box with a grid?

**Comment by srinivas1910** [comment]
Thank You @Zahar661,

No, Searching for an example for a dialog box with a filtered grid but am not able to find any. Please give me an idea how i can achieve a dialog with a grid.

Regards,
Srinivas.

**Comment by Zahar661** [comment]
Here is an example of how to make a dialog with a grid
```
export class BusinessTripServicePickerDialog extends Serenity.EntityGrid<BusinessTripServicesRow, any> {
        protected getLocalTextPrefix() { return BusinessTripServiceDetailsRow.localTextPrefix; }

        private serviceGrid = new BusinessTripServicesPickerGrid(this.byId('serviceGrid'));

        constructor() {
            super();

            var tb = this.element.find('.s-DialogToolbar');
            this.element.append(tb);
            this.dialogTitle = "Выбор услуг";
        }

        getToolbarButtons() {
            return [{
                title: 'ОК',
                cssClass: 'ok-button',
                onClick: () => this.okClick()
            },{
                title: 'Отмена',
                cssClass: 'cancel-button',
                onClick: () => { this.dialogClose(); }
            }];
        }

        protected okClick()
        {
            var items = this.serviceGrid.rowSelection.getSelectedKeys();
                this.element.trigger(<any>{
                    type: 'okClick',
                    selectedItems: items
            });
        }

        protected getTemplate() {
            return (
                "<form id='~_Form' class='s-Form'>" +
                    "<div id='~_serviceGrid'></div>" +
                "</form>" +
                "<div id='~_Toolbar' class='s-DialogToolbar' ></div>");
        }
    }
```

**Comment by Zahar661** [comment]
`private serviceGrid = new BusinessTripServicesPickerGrid(this.byId('serviceGrid'));`
replace with
`private serviceGrid : BusinessTripServicesPickerGrid;`

add  `public classIdEditor: Serenity.LookupEditor;`
in constructor add 
```
this.classIdEditor= new Serenity.LookupEditor(this.byId('classIdEditor'), {
                lookupKey: 'Administration.User'
            });
```
'Administration.User' write your name
and 

```
protected afterLoadEntity() {
            super.afterLoadEntity();

            this.classIdEditor.change(e => {
                this.serviceGrid = new BusinessTripServicesPickerGrid(this.byId('serviceGrid'));
                this.serviceGrid.dogovorId = this.classIdEditor.value;
            });
}
```
in getTemplate() add in form
`<div class='field classIdEditor'  style='width: 500px;'><label class='caption' for='~_classIdEditor'><sup title='class'>*</sup>Class</label><div id='~_classIdEditor'></div><div class='clear'></div></div>`

**Comment by srinivas1910** [comment]
Thank you @Zahar661 will do this and let you know the result
