### ISSUE TITLE
I need to merge 2 generated entities into 1

### ISSUE THREAD

**Issue by ashawky** [volkanceylan/Serenity#4237]
Hi Everyone,

Thanks for the great community, we have found a useful answer for part of our issue in this [reply](https://github.com/volkanceylan/Serenity/issues/483#issuecomment-203483513).

**Goal**: We have an existing system based on SQLServer database with a huge logic (Views, Stored Procedures, Functions..), and our goal to enhance it by utilizing Serenity and its magic in UX/UI.

**Issue:** We have succeeded to generate (_SENGEN_) for _MyEntityTable_ (which is a database table) and for _MyEntityView_ (which is s database view of many related tables) independently, but we still can't figure out how to assemble them together, by meaning:

when Click '_List_' (in menu) or '_Retrieve_' (for a specific record), how to instruct _Serene_ to depend on files generated for _MyEntityView_, and remaining actions such as '_Insert_', '_Update_' and '_Delete_' depend on files generated for _MyEntityTable_.

Or shall we keep all files generated by _MyEntityView_, and it is easier to customize the clicks of '_Create My Entity'_, '_Update_' and '_Delete_' ?

Please advice, and thanks in advance.

Regards,

**Comment by ga5tan** [comment]
You could mix and match Grid with Dialog.
I do display view in grid and when editing, I display Form of "real" table entity...

**Comment by ashawky** [comment]
Thanks @ga5tan , your advice helped a lot.

I edited just 2 places in Grid.ts of the "real" table to point to the Row.cs and Columns.cs of MyEntityView.

Also to utilize the number of files, I replaced <MyRow> with <Entities.MyEntityView> in Retreive() methods in both Endpoint.cs & Repository.cs files of the "real" table, and kept only Row.cs and Columns.cs files of MyEntityView.
