### ISSUE TITLE
Serenity - permissions

### ISSUE THREAD

**Issue by poornimaavudari** [volkanceylan/Serenity#4239]
Hi,

I have my project in serenity with a .cs file containing constants of various composite permission keys.

I am using these keys to validate my permissions

  if (HasPermissions("XXXXX:YYYY") == false) {
              "Not Authorised"
            }

It uses serenity hasPermissions function.
At the moment these validations are in my Grid.ts files, this does not work appropriately because by the time system triggers Grid.ts data is already loaded and users who does not have access to the page can directly navigate to the url and access the page.

Can anyone suggest a better way of using permissions.

Thanks

**Comment by ga5tan** [comment]
plz, close the other (blank) issue
I dont understand. I use permissions in FE (ts) all the time and it works ok.
What data are you talking about?
You can hide pages from navigation, so that there is for user no way to navigate to page.
do you mind illustrate your issue with screenshots ?

**Comment by poornimaavudari** [comment]
Sorry, my mistake - closed the blank one.
Ok, its not easy to share screen shots but I will try. Meanwhile I would like to explain in bit more detail if that helps.

Is it possible to share some helpful links to understand the validating permissions and stop navigation to the page as you described above please.

Thanks you

**Comment by stixoffire** [comment]
Do it on your XYZ row / Column , Form.. See examples in Northwind and Movie

**Comment by poornimaavudari** [comment]
Hi,
Thanks for the above reply.
I am new to serenity , hence I did a break point in all the XYZ relatd .cs and .ts files and tried to analyse the flow it hits the XYXpages.cs  first as it contains the navigation of the link. I thought it would be good to place the validation here.

Is there any specific reason to keep it in XYX row/Column Form ---> I am trying to understand the best solution that can fit.

Thank you.

**Comment by ga5tan** [comment]
I believe, that if your entity permissions are right, you should be fine with users changing URL in browser as well. Just let Serenity do the magic, meaning, try to set privileges properly.
There is also privileges on all the webservice calls (ie, list, save, update, delete), so you can use that as well.
Then there is server level, which you should ALWAYS take into consideration if somebody tinkers with JS, or webcalls, and you can/should/must check privileges there as well.

Then, there is multitenant tutorial, which discusses variour levels of protection, which I am suggesting you to check out.
I would go as far as urge u to check it out.

**Comment by poornimaavudari** [comment]
Thank you, helpful information.

multitenant tutorial -- is it possible to share the link that you are referring. I tried searching and it gave me something with php not sure if that's what you were referring.

**Comment by ga5tan** [comment]
The page you want to check is this:
https://serenity.is/docs/
it has plenty of useful info.
More specifically tutorials section...:
direct link to multi tenancy is here:
https://serenity.is/docs/tutorials/multi_tenancy/multi_tenancy

**Comment by poornimaavudari** [comment]
Ok, thank you . found it.

**Comment by poornimaavudari** [comment]
Thanks ga5tan for your suggestions and information. very helpful.
