### ISSUE TITLE
How to open dialog by click on button in MVC using serenity application template

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#424]
Hello sir,

I have developing some custom functionality in serenity by using serenity application template. I want to open dialog or popup and display view inside of dialog or popup by click on button in MVC. When we click on button AssignExam action method call. 

[HttpPost]
public ActionResult AssignExam()
{
}

**Comment by volkanceylan** [comment]
You should put your custom functionality in an endpoint, derive its request from ServiceRequest, response from ServiceResponse. Then you'll have XYZService.AssignExam method.

Otherwise you need to call this AssignExam with standard jQuery Ajax functions.
