### ISSUE TITLE
Text Field stripping off leading spaces OR how to sort text columns with numbers

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#4240]
Hello everyone,

I have a text field to hold a user defined code. When shown in the grid, the column sort sorts like this:

1
10
100
2
20
3
etc...

This is due to the fact it is a text column. However, if the user edits the code field on the form and changes "1" to say " 1" with a space in front, the value stored in the database is "1". Thus not impacting the sort order. Of course, we could change this to a numeric field, but not all customers will use this field the same. The user could change the code to "01" to address this.

Has anyone else found an alternative solution to how best handle this?

Thanks

**Comment by JohnRanger** [comment]
Issue #739 was one of my hardest fought proves to Volkan that indead his great FW must have a bug in there somewhere :-)

**Comment by volkanceylan** [comment]
Making something thats works best %99.9999 of cases default while offering an option for others is not a bug it is a
