### ISSUE TITLE
Limit Number of Columns for Grid

### ISSUE THREAD

**Issue by MoheebP** [volkanceylan/Serenity#4241]
I need to select only 10 columns for grid instead of 100 columns from one of my table. Thnx.

**Comment by edwardch** [comment]
Why not remove the fields from YourBigTableColumns.cs ?

**Comment by MoheebP** [comment]
Hello edwardch, I did that, but in SQL Profiler, it is showing a query that is fetching all columns from that big table row. Should I use LookupInclude attribute?

**Comment by edwardch** [comment]
Ah, so what you'd want to do is add this to YourBigTableRow.cs

```cs
[DisplayName("Column Not In List"), MinSelectLevel(SelectLevel.Details)]
public String ColumnNotInList
{
    get { return Fields.ColumnNotInList[this]; }
    set { Fields.ColumnNotInList[this] = value; }
}
```

This is assuming that you want to display this field when you're opening the form/dialog. If you don't want to and/or don't care about this field you can remove it from YourBigTableRow.cs (and all other references) completely - Serenity does not care about columns that you don't tell it about.

Hope this helps!
