### ISSUE TITLE
permission for categories / single fields

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4242]
Hey there,

I'm searching for a way to give several categories of an entity different permissions. What I have now is: 

`	[ReadPermission("Project:Read")]
	[InsertPermission("Project:Insert")]
	[UpdatePermission("Project:Update")]
	[DeletePermission("Project:Delete")]
	[LookupScript("Project")]
	public sealed class ProjectRow : Row, IIdRow, INameRow, IAuditLog`

But I want to seperate the permissions to select a single category or field to get acccess to.
I also tried to set Permission for a field value but of course the permission on top of the row was blocking me to save. 

Here is what I tried with Logical Permission feature, but it wasn't working for me:

`		[DisplayName("Phone"), Size(50), QuickSearch(SearchType.Contains), UpdatePermission("Project:ContactData|Gsd:Project:Update")]
		public String Phone { get { return Fields.Phone[this]; } set { Fields.Phone[this] = value; } }
		public partial class RowFields { public StringField Phone; }`

So my question is, if there is a way to give categories permissions and if not atleast single fields and keep the row permission as it is?

**Comment by hubeyb** [comment]
Which permission do you want to give to field?

If you give a permission on row, you must give this permissions to users which will use this row because of you want to update only one field of row.
And give or do not give the permission on field which you want to use or not this field users.

for examle, you used [UpdatePermission("Project:Update")]  on row, 
and UpdatePermission("Project:ContactData") on Phone field,

so you must give Project:Update and Project:ContactData permissions to user which will allow to update this field,

and  you must give Project:Update but not give Project:ContactData permissions to user which will not allow to update this field.

is this your answer?

**Comment by Garozh** [comment]
hi @hubeyb,

what I want is a way to give users update permission to specified fields in an entity, but not for all fields.
So the users should only be able to update for example the phone field of my project entity, but not other fields.

**Comment by hubeyb** [comment]
ok your answer is below,

you must give Project:Update and Project:PhoneField permissions to user which will allow to update this field, and write special permission to all other fields but not give their permissions to this user.

**Comment by Garozh** [comment]
@hubeyb 

That's definitly what I want but sadly it's not working and giving me the error message: 'Updated field is read only!' back for the fields the user has no update permission to,

**Comment by jaamkamran** [comment]
How to add Permissions 
https://www.youtube.com/watch?v=Rf4MdsUJ5oE
If you like than subscribe

**Comment by Garozh** [comment]
Sorry but that video is not helping me with my problem, because it's just showing the permissions for a whole row not for single fields who I want to give UpdatePermission.

**Comment by JohnRanger** [comment]
Hi @Garozh,

although my suggestion here is not 100% security thight, it should still work in your case.

Why not giving all the users update permission on the row level (e.g. [UpdatePermission("Project:Update")] and then - from within xyzDialog.ts - e.g. in the constructor, set each of the relevant form fields to read only when the user does not have UpdatePermission for the corresponding field - like this:

```ts
            if (!Authorization.hasPermission("Project:Update:FormFieldX")) {
                Serenity.EditorUtils.setReadOnly(this.form.<FormFieldX>, true);
            }
```

(where FormFieldX is the name of your field you want do control modify access to.

This would at least prevent your common user base to be able to modify any field via the form/dialog GUI they don't have Modify permission on.

Hope this helps.

With kind regards,

John

**Comment by Garozh** [comment]
Thanks @JohnRanger,

this is a little bit work to seperate each category, but atleast this is working. Maybe there will be an easier way in the future for setting category depending permissions.

**Comment by ra-bedo11** [comment]
> [UpdatePermission("Project:Update")]

Not Work

**Comment by ra-bedo11** [comment]
> How to add Permissions https://www.youtube.com/watch?v=Rf4MdsUJ5oE If you like than subscribe

not work
