### ISSUE TITLE
Serenity Script 3.4.4 - Upgrade Issues

### ISSUE THREAD

**Issue by jafeli1** [volkanceylan/Serenity#4243]
Thanks for answering numerous questions that have helped resolve issues without contacting you directly.

Nonetheless the script compile time exception below has stumped me. The \packages\Saltarelle.Runtime.2.7.0\tools\Assemblies\mscorlib.dll exists. Any suggestions or ideas?

Error 1 INTERNAL ERROR: System.TypeLoadException: Type 'System.Runtime.InteropServices.ImportedFromTypeLibAttribute' not found in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a4048e8fcc593f14' at IKVM.Reflection.Universe.GetMissingTypeOrThrow(Module requester, Module module, Type declaringType, TypeName typeName) at IKVM.Reflection.Assembly.ResolveType(Module requester, TypeName typeName) at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context) at IKVM.Reflection.Module.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) at IKVM.Reflection.Reader.ModuleReader.GetMemberRef(Int32 index, Type[] genericTypeArguments, Type[] genericMethodArguments) at IKVM.Reflection.Reader.ModuleReader.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) at IKVM.Reflection.CustomAttributeData.get_Constructor() at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.AddCustomAttributes(IEnumerable1 attributes, ICollection1 targetCollection) at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.AddAttributes(Assembly assembly, IList1 outputList) at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.LoadAssembly(Assembly assembly) at Saltarelle.Compiler.Driver.CompilerDriver.&lt;LoadReferences&gt;b__27(Assembly asm) at System.Linq.Enumerable.WhereSelectListIterator2.MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at Saltarelle.Compiler.Driver.CompilerDriver.LoadReferences(IEnumerable1 references, IErrorReporter er) at Saltarelle.Compiler.Driver.CompilerDriver.Compile(CompilerOptions options). 

Thanks for any  help you can render.

Joseph

**Comment by jafeli1** [comment]
.NET 2.0 for the Script and .NET 4.5 for the Web.

However I decided to upgrade following the steps here https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_upgrade_to_serenity_2_typescript.html

I cannot find the ClientTypes.tt jocated here  
https://raw.githubusercontent.com/volkanceylan/Serene/master/Serene/Serene.Web/Modules/Common/Imports/ClientTypes/ClientTypes.tt

Any idea where I can snag a copy?

Thanks

**Comment by volkanceylan** [comment]
We no longer support Saltaralle, remove mscorlib etc if is in your bin
