### ISSUE TITLE
JsonServiceClient

### ISSUE THREAD

**Issue by Hochmah** [volkanceylan/Serenity#4244]
I'm using this example in order to access another serenity's instance endpoints.
I can successfully call list and retrieve, using generic Dictionary<string, object> to pass data to endpoint. But SaveRequest need that a TEntity be informed (like: SaveRequest<MyRow>). And as I'm calling this endpoint for another instance, I have no definition for this row. I need to have a row definition to this entity from another instance in order to pass its data when calling Create or Update endpoints, or there is a way to pass this data anonymously on the fly? 

This code below works great for list and retrieve:
`
var client = new JsonServiceClient("http://www.mysite.com/");
client.Post<ServiceResponse>("Account/Login", 
    new LoginRequest {
        Username = "someuser",
        Password = "somepass"
    });

var list = client.Post<ListResponse<Dictionary<string, object>>>(
    "Services/Northwind/Customer/List", 
    new ListRequest {
        Take = 100
    });
`
Can someone provide same code example on how can I call this endpoints?

Thank you in advance!

**Comment by volkanceylan** [comment]
You may use anonymous class or a simple dictionary
