### ISSUE TITLE
Use Controller in Dialog Template (instead of a TS grid)?

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#4245]
Hi there,

When clicking an object on its corresponding grid, it opens a dialog, which is created based on `ObjectDialog.Template.html`. To my understanding, if the dialog has tabs, each "tab" div contains another div in which the name of the TS file is stated. 

I created a custom controller that returns a calendar page view (using Razor). Is there a way to insert this controller in the place of that type script file? 

I would like to replace this grid:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/16263577/52006998-1d302e00-2493-11e9-99ff-c3318779b03e.png">

With this view that a controller returns:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/16263577/52007008-24573c00-2493-11e9-9736-c50fab039d55.png">

Many thanks in advance.

**Comment by ga5tan** [comment]
I guess you can replace empty tab or placeholder on that tab with HTML returned by controller via JQuery.
I (for example) am inserting or replacing placeholders with small dialogs (I call it user controls)

**Comment by MarcusOy** [comment]
Hi @ga5tan ,

Is it possible for you to elaborate? I'm not sure I follow.
Thank you for your response regardless.

Best Regards,
Marcus

**Comment by volkanceylan** [comment]
You might need to put an iframe there or fetch it using ajax and replace html. Templates are static text, they cant contain dynamic content.

**Comment by ga5tan** [comment]
It may be not suitable for you but here is how you insert dialog instead of placeholder (string field PaymentControl):

this.element.find('.PaymentControl').addClass('hidden');
            this.paymentDialog = new Common.PaymentDialog();

            //append dialog into template
            this.paymentDialog.element.removeClass('hidden').insertAfter('.PaymentControl');

**Comment by JohnRanger** [comment]
@ga5tan : Cool trick!

**Comment by stixoffire** [comment]
@MarcusOy  If you have a working sample - I would love to see that code !

**Comment by MarcusOy** [comment]
@stixoffire Unfortunately, I decided to work on a different aspect of the application in the meantime, as this wasn't very important. Will post here when I do get to working on this.
