### ISSUE TITLE
Height paneltopRight SlickGrid

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#4246]
@volkanceylan, If you enable the grouping pane and freeze multiple columns, the right pane does not show the headers. Here's what I came up with for myself, but it's a crutch. 
![image](https://user-images.githubusercontent.com/26430136/52047212-f5f46200-2561-11e9-9556-937288bc43e7.png)

**Comment by volkanceylan** [comment]
Thanks will have a look at it

**Comment by volkanceylan** [comment]
Couldn't reproduce this, or didn't understand the original issue:

![image](https://user-images.githubusercontent.com/752470/60645089-720c1200-9e40-11e9-875c-383b5460f65b.png)

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/60645574-13e42c80-9e4a-11e9-8e3a-33c63bb7f482.png)
This is in the premium version.

**Comment by Zahar661** [comment]
But when upgrading to 3.9.9, there seemed to be no problems, or slisk.grid.ts did not change
