### ISSUE TITLE
Quickfilter - Change Value in dropdown for bit datatype

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4247]
Hello,

How can i change default yes / No values present in quick filter drop down for a Column of type bit ?
Instead of yes / no i want to show Open / Close.

**Comment by minhhungit** [comment]
@TechAspirant  check QuickFilter custom demo at here: 

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/QuickFilterCustomization/QuickFilterCustomization.ts

my suggestion is push an enum editor and modify **handler** method, like **Freight**

**Comment by volkanceylan** [comment]
QuickFilterOption("trueText") etc might help

**Comment by TechAspirant** [comment]
what will be the string key as QuickFilterOption expects two parameter one is string key and other one is object value

**Comment by TechAspirant** [comment]
Thanks it worked
[QuickFilterOption("trueText", "Open")]
[QuickFilterOption("falseText", "Close")]
