### ISSUE TITLE
how to prevent filter fire the viewsubmit event

### ISSUE THREAD

**Issue by csabc** [volkanceylan/Serenity#4248]
how to prevent filter fire the viewsubmit event, i only want  to click refresh button to fire it,thanks!

**Comment by hubeyb** [comment]
did you consider to override onViewSubmit function?

`        protected onViewSubmit() {
            // only continue if base class returns true (didn't cancel request)
            if (!super.onViewSubmit()) {
                return false;
            }
      }`

**Comment by csabc** [comment]
> did you consider to override onViewSubmit function?
> 
>     protected onViewSubmit() {
> 
> 
>         // only continue if base class returns true (didn't cancel request)
>         if (!super.onViewSubmit()) {
>             return false;
>         }
>   }

Thanks very much.I did it as shown below.

private canSubmit: boolean;
constructor(container: JQuery) {
            super(container);
            this.canSubmit = false;
}
protected onViewSubmit() {
            super.onViewSubmit();
            if (this.canSubmit) {
                this.canSubmit = false;
                return true;
            } else {
                return false;
            }
            
        }
 protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "refresh-button"), 1);
           buttons.push({
                title: "Query",
                cssClass: "search-button",
                onClick: () => {
                    this.canSubmit = true;
                    this.view.populate();                    
                }
            });
            return buttons;
        }
