### ISSUE TITLE
Hiding Tab

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#4249]
I'm using Tab() attribute on *Form.cs to make forms on dialog, for some conditions I need to hide the specific tab. Tried with closest and find by class

Please help

**Comment by Zahar661** [comment]
in Dialog.ts try
this.tabs[0].hidden=true;

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serenity/issues/3855

**Comment by vinaykulkarni89** [comment]
@Zahar661 @dfaruque 
Thank you for suggestions but both option are not working.

I'm using Tab("Details") attribute in Form.cs over the properties

**Comment by vinaykulkarni89** [comment]
@dfaruque ya this worked in constructor well, thank you 👍

**Comment by nahidulislam-cse15** [comment]
@vinaykulkarni89 q.hideEditorTab(this.form.SomeFieldOnThatTab); for this syntax we need to install serenity extra package or something?
