### ISSUE TITLE
How can I set the gird row word wrap

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#425]
How can I set the gird row word wrap?  thank you!

**Comment by wdhodges** [comment]
You need to impliment the [TextAreaEditor].

Here is the example from the [Serenity Development Guide](https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/customizing_movie_interface.html)

This goes into the XYZForm.cs
```
[TextAreaEditor(Rows = 8)]
public String Storyline { get; set; }
```
This goes into the XYZRow.cs
```
[DisplayName("Runtime")]
[TextAreaEditor(Rows = 8)]
public Int32? Runtime
{
     get { return Fields.Runtime[this]; }
     set { Fields.Runtime[this] = value; }
}
```

Note: `XYZ` is your module name.

Hope that helps!

**Comment by kuyu7766** [comment]
Thanks ,But i mean how to do it in the list of SlickGrid.

**Comment by volkanceylan** [comment]
Need to override GetSlickOptions and set RowHeight to 60 for example. Then using css set whitespace: wrap; for your .s-XyzGrid .slick-cell

**Comment by kuyu7766** [comment]
thank you . i have set the rowHeight. but i can not find the .s-XyzGrid .Slick-cell and how can I using css . Can you show me detailedly? or a Code example ? Thank you very much!!

**Comment by dfaruque** [comment]
put these css in site.less file or another file which are included.

**Comment by volkanceylan** [comment]
In site.less add:

.s-MyModule-MyGrid .slick-cell {
  white-space: normal;
}

**Comment by kuyu7766** [comment]
Thank you , it run well. But have a new problem.  because of the  grid row height is fixed,  it can not show a long content,and "title" property is no use.  So I want limit the size of content and "title" property can be used. How to do it?

**Comment by volkanceylan** [comment]
No idea. Try putting a span with title in formatter function.

**Comment by kuyu7766** [comment]
Thank you very much. I try it  by your methord . It run well.` public string Format(SlickFormatterContext ctx)
        {
            var text = Q.HtmlEncode(ctx.Value);

            return "<span style=' white-space:normal; height:75' title='" +text.Substring(0,36)+ "'>" + (text.Length>36?text.Substring(0,36)+"...":text) + "</span>";
        }`

**Comment by volkanceylan** [comment]
I recommend to do substring before HtmlEncode. Otherwise you might break &lt; symbols etc. middle way.
