### ISSUE TITLE
Limit serenity Command timeout property

### ISSUE THREAD

**Issue by vigneshkumar957** [volkanceylan/Serenity#4250]
Hi,

I have reconfigured Serenity tool for my application and I have used Oracle as backend. I am facing one issue with Database. Due to large data my DB is somewhat slow, while running query it takes more than few minutes. What i wanted is, if query runing more than 5 minutes, it should throw timeout exception rather than keep the session alive.

**Comment by kilroyFR** [comment]
This is database level settings not Serenity.
Oracle is providing DBMS_RESOURCE_MANAGER package that should be used to define limitations on query executions (see complete example here : https://blog.pythian.com/oracle-limiting-query-runtime-without-killing-the-session/).

Hope this helps.

**Comment by stixoffire** [comment]
@vigneshkumar957 You can look at site initialization timeout settings (just for an insight into how that is done on initial start) - maybe set a timeout on your particular db , so in your xyzRepository Save / Modify  you might set a default timeout action (considering it is in all of your queries - perhaps you want to override a method in Serenity.Data) I am not sure where you can set it globally - but that is what I would look at to start.

**Comment by JohnRanger** [comment]
Multiple Minutes Run time for a query? Either your DB is really - really big (with 100dreds of Billions of records) or the Hardware of your oracle DBMS ist too weak (no In-Memory tables or slow disks) - or the DB lacks some indexes on fields which are queried. 

I mean - the User experience is really bad when they have to weit multiple minutes until they see a result.

May I kindly ask what is the ca. size (record count) of the table which you have the multiple minute wait timeout problem? Maybe this can be optimized when we understand better your use case.

With kind regards,

John

**Comment by minhhungit** [comment]
@vigneshkumar957 : try to wrap your connection

![image](https://user-images.githubusercontent.com/2279508/53319865-6b0b4b00-3906-11e9-88a9-5e682d68b1e7.png)

**Comment by minhhungit** [comment]
hello team and @volkanceylan, I tried to increase timeout with bellow code but it did not work, any suggestion please

![image](https://user-images.githubusercontent.com/2279508/53492977-c4bd7200-3acc-11e9-8bae-8fb771973ac3.png)

I have some large tables with tens of millions records, and it always throw timeout all times

**Comment by brunobola** [comment]
One way is to override the ServiceEndpoint this way:

1. First create a class to treat all the platform sql queries:

```
public class AdvancedServiceEndpoint : ServiceEndpoint
{
	public AdvancedServiceEndpoint()
	{
		//Override Connection parameters
		
		var cs = SqlConnections.GetConnectionString("Default"); //Default is you webconfig Connection String Name
		var cb = cs.ProviderFactory.CreateConnectionStringBuilder();
		cb.ConnectionString = cs.ConnectionString;

		
		cb["Connect Timeout"] = 999; //set your value here
		SqlConnections.SetConnection("Default", cb.ConnectionString, cs.ProviderName);
	}
}
```

2. then make all your controller classes descend from that, example:
```
...
public class XXXXController : AdvancedServiceEndpoint
...
```

**Comment by minhhungit** [comment]
@brunobola 

> public class XXXXController : AdvancedServiceEndpoint

for only ServiceEndpoint controllers right? not controllers on Page.cs

**Comment by minhhungit** [comment]
It looks did not work @brunobola , it likes my code

**Comment by minhhungit** [comment]
I counted it, it throws timeout error after 30 seconds

**Comment by minhhungit** [comment]
I think this is problem

![image](https://user-images.githubusercontent.com/2279508/53585412-74bbd980-3bb8-11e9-93b9-e248a53c4888.png)

Does anyone know how to increase **CommandTimeout** please

**Comment by brunobola** [comment]
You can always change it in the Web config..

But I've tested it:
![image](https://user-images.githubusercontent.com/10889019/53587081-61d9e280-3b81-11e9-8db4-73f13bfc0e94.png)

**Comment by brunobola** [comment]
Wait a moment you guys want to increase the command time it can only be increased problematically I mistaken the question.

https://forums.asp.net/t/1197160.aspx?Can+you+change+command+timeout+via+the+connection+string+

**Comment by minhhungit** [comment]
Yes, currently we want to change **COMMAND Timeout** 
- Currently I don't see anyway to adjust it without creating a pull request

With `connection timeout`:
- we can change it by connection string (this way will affect to all queries) 
- or wrap IDbConnection using SqlConnectionStringBuilder

**Comment by stixoffire** [comment]
@minhhungit When you are passing in to your repository - the connection object in the repository can't be modified ?
I have not tried this code other than a quick intellisense write .. but try this in your repository methods..

>         public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
>         {
>             var connect = uow.Connection;
>             var cnnString = connect.ConnectionString;
>             cnnString = cnnString.Replace("old", "my stringreplaced with new timeout");
>             connect.ConnectionString = cnnString;
>             IUnitOfWork uowTimeOut = new UnitOfWork(connect);
>           
>             return new MySaveHandler().Process(uowTimeOut, request, SaveRequestType.Update);
>         }


Or access the unit of work connection in the MyCRUDHandler  ... 

Try that out and let us know if it works for you ..

**Comment by minhhungit** [comment]
No @stixoffire, I don't need to change timeout for Create/Update/Delete (with IUnitOfWork)
What I need is increasing timeout for List/Retrieve

There are 2 types of timeout: **Connection**Timeout & **Command**Timeout

With ConnectionTimeout, yes, you can not set timeout value directly from repository/endpoint because it just has **get** accessor with no **set** accessor. And I used SqlConnectionStringBuilder to hack it but it did not work.

So I check serenity code (Serenity/Serenity.Data/SqlHelpers/SqlHelper.cs) and see that we need to change **CommandTimeout**, not ConnectionTimeout

=> So, do you know how to change CommandTimeout value, sir :)

**Comment by stixoffire** [comment]
I believe you will need to get access to the Execute command function and override that - but let me check on this later today when I get a chance. I believe there are ways to override the query function - and it has to be in the execute command to override that. 

I do not have time right now to look - but later today I will look into it.

**Comment by minhhungit** [comment]
I created a pull request for this issue

**Comment by rcruzfalcon** [comment]
Hi, sorry for the late answer ...

We used this scheme for our Store Procedure:

`using (var connection = SqlConnections.NewByKey("Default"))
            {                
                var paramters = {};
                var result =  connection.Query(SP,
                   paramters,
                    commandType: System.Data.CommandType.StoredProcedure, commandTimeout:999).ToList();
                
                
                return new ReportDinamicFromDbModel() {Data = result, Titulo = Titulo, Username = Username,Filtros = {}};
            }`

Best Regards

**Comment by volkanceylan** [comment]
This is added in latest version.
