### ISSUE TITLE
Unable to Insert Records from form in dashboard

### ISSUE THREAD

**Issue by mugambiwarwema** [volkanceylan/Serenity#4251]
I have trouble inserting records from my form using jquery.

I Have a cshtml page that has a jquery function to access/trigger my ActionMethod[POST].

My form submits and my action-method passes model validation.

The action method runs, without any errors but no record is inserted.

No data inserted in the DB

Here is an extract of my Action-Method

```
public Result<SaveResponse> Create([FromBody]OrderModel request)
    return this.UseConnection("Default", connection =>
        {
            using (var uow = new UnitOfWork(connection))
            {
                if (ModelState.IsValid)
                {
                    var o = new SaveRequest<OrdersRow>();

                    var orderId = connection.InsertAndGetID(new OrdersRow
                    {
                        Name = request.Name,
                        Age= request.Age
                    });
                    o.EntityId = order;
                    uow.Commit();
                }
                else
                {
                    //var errors = ModelState.Select(x => x.Value.Errors)
                    //                       .Where(y => y.Count > 0)
                    //                       .ToList();
                    //return Json(errors);
                }

                return new SaveResponse();
            }
        });
```

My browser devtools doesnot throw any error. The Method returns Http-200 
No errors raised in my logs(stdout.log)

**Comment by Zahar661** [comment]
```
var o = new OrdersRow(){
Name = request.Name,
Age= request.Age
}
var rez = new OrdersRepository().Create(uow, new SaveRequest<OrdersRow>
                            {
                                Entity = o
                            });
// rez.EntityId;
```

**Comment by mugambiwarwema** [comment]
@Zahar661 

Thank you for the response, however, after attempting your solution, I got the error
 
MySqlException: Cannot add or update a child row: a foreign key constraint fails (`db_name`.`table_name`, CONSTRAINT `FK_Order` FOREIGN KEY (`ServiceId`).

I should add that OrdersRow has a One-to-Many relationship with ServiceId. 
i.e one service can belong to many Orders. 

My final implementation

```
 public SaveResponse Create(SaveRequest<OrdersRow> request, [FromBody]OrderModel order)
        {
            var _order = new OrdersRow()
            {
                Name= order.Name,
                Age= order.Age,
                ServiceId= order.ServiceId
            };
            using (var connection = SqlConnections.NewFor<OrdersRow>())
            using (var uow = new UnitOfWork(connection))
            {
                request.Entity = _order;
                var result = new OrdersRepository().Create(uow, request);
                uow.Commit();
                return result;
            }
        }
```

I retrieve Services from the DB and append to the form dynamically. That is, subsequent values returned for ServiceId actually exists in the DB.

Please assist.

**Comment by Zahar661** [comment]
check the database. the function is all right.

**Comment by mugambiwarwema** [comment]
No rows are inserted...into the DB. 
Am glad to share any files that might help...

**Comment by Zahar661** [comment]
delete FK_Order in SQL and check
![image](https://user-images.githubusercontent.com/26430136/52525627-d37ee900-2cc5-11e9-9db9-459e36f68116.png)

**Comment by mugambiwarwema** [comment]
> delete FK_Order in SQL and check
> ![image](https://user-images.githubusercontent.com/26430136/52525627-d37ee900-2cc5-11e9-9db9-459e36f68116.png)


Thank you for the response but allow me to be skeptical. 

1: If the code works, why do I have to delete the FK?
2: The code works on the Sign-up/Register module, and the values inserted go to a single table

Username, Email, hash(password)
3: My function intends to insert values that are related, perhaps this is a bug.
4: The FK were created during migration, and editing the schema to fit/fix an error in business-logic does not sound OK. 

Perhaps we're onto something and we can probe the issue further

**Comment by mugambiwarwema** [comment]
@volkanceylan 

Could this be a possible bug?

**Comment by Zahar661** [comment]
> MySqlException: Cannot add or update a child row: a foreign key constraint fails (`db_name`.`table_name`, CONSTRAINT `FK_Order` FOREIGN KEY (`ServiceId`).
This is a DB exception, not Serenity. You are passing the wrong ServiceId

**Comment by Zahar661** [comment]
The code is written correctly, if it comes to saving in the database

**Comment by mugambiwarwema** [comment]
Please leave this open as I dig deep into the issue. 
Thanks
