### ISSUE TITLE
Unable to Insert a new Record

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4253]
When I am trying to insert a new record from the grid then create method throwing an error like 
'SysId doesn't have a default value'.  Since in database we created a Sysid with null as a default value.

Sysid is pk  of string Type ....

**Comment by karimhyatt** [comment]
Is it defined as NotNull in the xxxRow class? Perhaps some more info would help.

**Comment by flextrio-gandhi** [comment]
@karimhyatt It is defined as PrimaryKey in xxxRow class
    [DisplayName("SysId"), Size(50), PrimaryKey]
        public String SysId
        {
            get { return Fields.SysId[this]; }
            set { Fields.SysId[this] = value; }
        }

**Comment by flextrio-gandhi** [comment]
@karimhyatt Sysid id defined as PrimaryKey in xxxRow class
[DisplayName("Sysid "), Size(50), PrimaryKey]
        public String Sysid 
        {
            get { return Fields.Sysid [this]; }
            set { Fields.Sysid [this] = value; }
        }

**Comment by flextrio-gandhi** [comment]
No it is not defined as NotNull.....it is defined with PrimaryKey in xxxRow class

**Comment by JohnRanger** [comment]
As a simple best practice, let always the database engine create your id (if your Database Engine is MSSQL, set identity to yes) if there is no specific need to manually generate the identity.
