### ISSUE TITLE
Inline Action Button in masterdetail

### ISSUE THREAD

**Issue by TecnologiaCapricornio** [volkanceylan/Serenity#4254]
Hi,

How do I add Inline Action Buttons in a masterdetail grid? I put both in xxxGrid.ts and xxxEditor.ts but it didn't show.

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons
