### ISSUE TITLE
wkhtmltopdf PDF generator returned error code -1073741819!

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#4255]
hello
i am at a loss here. im getting this error when generating a report:
PDF generator returned error code -1073741819!
ive read all the other issues related to this problem and havent found anything.
i am using exactly the same code in two other projects (one being a new serene template project with samples) and its working just fine.
when i run the reporthelper to out html it works fine. so html is valid. only when i try to render as pdf i get this error...
im thinking its some permission or something set differently between the projects but for the life of me i cant find anything.
anyone can maybe point me in the right direction?

**Comment by Zahar661** [comment]
Run exe in packages\wkhtmltopdf-x86-win32.0.12.3.6\tools\wkhtmltopdf    get error with missing dll

**Comment by Zahar661** [comment]
most likely you need to install the **32bit** version of MICROSOFT VISUAL C++ REDISTRIBUTABLE FOR VISUAL STUDIO 2013

**Comment by shakazulu89** [comment]
yea i think it had something to do with the bit version .. dont know how this project ended up using a different one from the other projects i have on the same computer. but works now. 
next issue is most of the font in the rendered pdf is coming up as jibberish.
had this issue before dont remember how i fixed it :/ ....
