### ISSUE TITLE
Protect File In Upload Folder / Upload Folder Direct Download Security

### ISSUE THREAD

**Issue by wildanmuhlis2** [volkanceylan/Serenity#4257]
Hi,

Is there any suggestion on how to make uploaded file could be accessed if the user logged in or even with specific permission?

Currently, when we access the link directly without login it could be accessed
http://localhost:50231/upload/PurchaseRequest/sf/sfsdfsdf_gywj6djetsfsq.pdf

**Comment by edwardch** [comment]
I think this is something that needs to be fixed in Serene... 

But what I did was edit Modules/Common/File/FilePage.cs to this:

```cs
[Route("upload/{*pathInfo}")]
[ServiceAuthorize()]
public ActionResult Read(string pathInfo)
{
```
and
```cs
[Route("File/TemporaryUpload")]
[AcceptVerbs("POST")]
[ServiceAuthorize()]
public ActionResult TemporaryUpload()
{
```

So I basically just added [ServiceAuthorize()] to these actions...

**Comment by wdhodges** [comment]
@edwardch’s answer is correct! I had the same question about a year or so ago lol

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wildanmuhlis2** [comment]
Great !! Thanks @edwardch , your answer could be used for dynamic and granular file access permission.

If we want to just protect the file for only accessible by authenticated user, we could add this to `Web.config`

```
<?xml version="1.0" encoding="utf-8"?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  http://go.microsoft.com/fwlink/?LinkId=169433
  -->
<configuration>
...
  <location path="upload">
    <system.web>
      <authorization>
        <deny users="?" />
      </authorization>
    </system.web>
  </location>
...
</configuration>
```
