### ISSUE TITLE
How to remove back button of editor.

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#4258]
I just want to remove the back button on editor..
![backbutton](https://user-images.githubusercontent.com/28822902/52471674-7563e000-2bb7-11e9-98b4-0ffe27b5c3dc.PNG)

**Comment by edwardch** [comment]
See: [Remove Close button from titlebar on Dialog #4232](https://github.com/volkanceylan/Serenity/issues/4232) 

The class for back button is: "panel-titlebar-close"
