### ISSUE TITLE
which lookup is executed when using Multiple lookup editors for the same Entity when use getlookup()

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#4259]
I create two lookup Editors for the same entity, one returns all record and another one has a complex filter.
now ,when I write this code
xxxRow.getlookup();

which lookup will executed .

thanks

**Comment by ga5tan** [comment]
you may consider checking log, where you will see SQL statement

**Comment by amrgDev** [comment]
I duplicated the xxxRow.cs class and create lookup for each class and then I called the right xxxRow.getlookup() method.
