### ISSUE TITLE
Exclude/Include fields during code generation

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#426]
Hi,

Is there any way to Exclude/Include some common fields (createdby, updatedby etc.) during code generation.

**Comment by volkanceylan** [comment]
There are BaseRow and SkipForeignFields options in Serenity.CodeGenerator.config, in and old thread there should be some samples. Search for it please.

**Comment by dfaruque** [comment]
Ok. I will check those stuff.

**Comment by volkanceylan** [comment]
Here is one sample from a friend:

```json
    "BaseRowClasses": [{
		ClassName: 'MyLoggingRow',
		Fields: ['InsertUserId', 'UpdateUserId', 'InsertDate', 'UpdateDate', 'DeleteUserId', 'DeleteDate', 'IsActive']
	}],
    "RemoveForeignFields": ['InsertUserId', 'UpdateUserId', 'InsertDate', 'UpdateDate', 'DeleteUserId', 'DeleteDate', 'IsActive']
```
