### ISSUE TITLE
The given path's format is not supported. When using {3} as file name format

### ISSUE THREAD

**Issue by wildanmuhlis2** [volkanceylan/Serenity#4261]
I've trying to add current date and time in filename:

`[FileUploadEditor(FilenameFormat = "PurchaseRequest/{1:0000}/{0:00000000}_{2}_{3}_{4}", CopyToHistory = true, OriginalNameProperty = "ScanPrName", DisplayFileName = true)]`

An error occured:

`The given path's format is not supported.`

Anyone here face same issue?

**Comment by Zahar661** [comment]
colon in file name not allowed

**Comment by JohnRanger** [comment]
As @Zahar661 mentioned. Therefore you have to replace the ":" with for example "-".

**Comment by wildanmuhlis2** [comment]
@Zahar661 , @JohnRanger 
The colon is allowed filename format

![image](https://user-images.githubusercontent.com/11847279/52923778-f3647b80-335b-11e9-8705-2a15ae51dfa6.png)

I refer the filename from this link:
https://github.com/volkanceylan/Serenity-Blog/blob/master/2017-11-02-upload-file-name-formats.md

**Comment by JohnRanger** [comment]
![colon](https://user-images.githubusercontent.com/2699447/53305177-68fda980-387e-11e9-8d4e-8aab207bcfb6.png)

No - it is not - at least not under Windows. See above Screenshot from when I tried to type a colon (":").

With kind regards,

John

**Comment by JohnRanger** [comment]
You have to test how far your path string works - e.g. does

```cs
ProductImage/{1:0000}/{0:0000}
```

work?

If yes, try:

```cs
ProductImage/{1:0000}/{0:0000}_{2}
```

If this does not work anymore, there must be an invalid character within {2} Compare {2} with the un-allowed characters in my aboe post.

It it still works with {2} added, continue to test with {3} added - and so forth.

With kind regards,

John

**Comment by hannesb** [comment]
You have to provide a [custom date format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-hh-custom-format-specifier-1) string for the 3rd argument, like
{3:yyyyMMddHHmmss} or {3:yyyy-MM-dd_HH-mm-ss}
BTW, the format is applied in [UploadHelper.FormatDbFileName()](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Web/Upload/UploadHelper.cs)

**Comment by wildanmuhlis2** [comment]
Exactly what I need. Thank you @hannesb :+1:
