### ISSUE TITLE
Open form instead of grid

### ISSUE THREAD

**Issue by IT-LCEC** [volkanceylan/Serenity#4264]
Anyone have some sample code they could share on how to open the form (with a known key field value) instead of the grid? We navigate to this form with the standard mymoduleNavigation.cs file.

We obtain the key field value from a cookie. There is never a need to show the grid. 

We tried this in myDialog.ts 
```
...
contructor(container: JQuery) {
     super(container);

     var cookieKeyId;
     cookieKeyId = $.cookie('currentKeyId');
     ...
     this.loadEntityAndOpenDialog(
          {
               myKeyId: cookieKeyId
          },
          false);
}
...
```

Thanks for the help.

We looked at these but we are not trying to show a form in a tab.

- https://serenity.is/demo/BasicSamples/OtherFormInTab
- https://serenity.is/demo/BasicSamples/OtherFormInTabOneBar

**Comment by Zahar661** [comment]
https://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077

**Comment by IT-LCEC** [comment]
Thanks that's what I needed!
