### ISSUE TITLE
Setting a field value to new form instance

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#4265]
Anyone have a good example they would like to share for setting a value of a hidden field on a new form instance? For example, you open up your object's grid, click the new button and a hidden field value is auto-set to a value we get from a cookie. The field is required for the database insert. 

Thanks in advanced for the pointer.

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/52764876-33192380-303b-11e9-8696-bb07963a1d7c.png)

**Comment by Zahar661** [comment]
or  in Diolog.ts
```
protected afterLoadEntity() {
            super.afterLoadEntity();
            if (this.isNew) this.form.TypeId.value = "2";
        }
```

**Comment by Zahar661** [comment]
or in Grid
```
protected addButtonClick() {
            this.editItem({ TypeId: "2"});
        }
```

**Comment by VR-Architect** [comment]
Thanks guys. That worked. Much appreciated!
