### ISSUE TITLE
How to add Waiting spinner

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4266]
How to add waiting spinner or identification of loading page.... while the data is loading into grid or when page is refreshing

**Comment by Zahar661** [comment]
they are
![image](https://user-images.githubusercontent.com/26430136/52775555-636fba80-3059-11e9-9009-015c66b09e21.png)

**Comment by flextrio-gandhi** [comment]
I need to customize the spinner so how to do that..?

**Comment by edwardch** [comment]
I think look in **Content/pace.css**, and **Scripts/pace.js** (note you will also need to edit the pace.min.css/pace.min.js if you are using minified code).
