### ISSUE TITLE
how to change the range of years on dialog?

### ISSUE THREAD

**Issue by WendyBurgerHsu** [volkanceylan/Serenity#4269]
Hi everyone,
Does anyone know how to set the DateEditor starting year and the ending year?

I used 
`DateYearEditor(MaxYear = "2003", MinYear = "1949")`
But it can only choose the year, the month and the date are gone.

I tried 
`DateEditor(MaxValue = 31-12-2003, MinValue = 01-01-1949)` or
`DateEditor(MaxValue = "31-12-2003", MinValue = "01-01-1949")`
But it doesn't work.

![image](https://user-images.githubusercontent.com/44994587/53062102-a8349f00-34fa-11e9-810b-815dbcad95cb.png)

Thanks!

**Comment by Zahar661** [comment]
I think you can do so in the Dialog after loading entity
http://api.jqueryui.com/datepicker/#option-minDate

**Comment by WendyBurgerHsu** [comment]
Hi @Zahar661 ,

here is my code:
```
protected afterLoadEntity() {
            super.afterLoadEntity();
            $("[name = 'Birthday']").datepicker("option", "maxDate", new Date());
        }
```

Although the result is not what I want (1949-2003).
But can be sure that the year will not exceed this year, thank you!
