### ISSUE TITLE
Pulling data from a second database

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#427]
I was wondering if there was a way to pull data from two different databases in the same row.cs file?

This is my Aircraft field in my LandingZoneRow.cs (part of it)

`[ConnectionKey("Default"), DisplayName("Landing Zones"), InstanceName("Landing Zone"), TwoLevelCached]`
...

```
[DisplayName("1st Due"), ForeignKey("[ff].Aircraft", "AircraftID"), LeftJoin("f"), NotNull]
        [LookupEditor("AirDivision.Aircraft")]
        public Int32? PAircraftId
        {
            get { return Fields.PAircraftId[this]; }
            set { Fields.PAircraftId[this] = value; }
        }

        [DisplayName("1st Due"), Expression("f.AircraftName")]
        public String FirstDue
        {
            get { return Fields.FirstDue[this]; }
            set { Fields.FirstDue[this] = value; }
        }
```

Under the AircraftID I need that to pull from a different database. Is there a way I can get only that field to return data from a different database? Also is there a way I can filter that data? Example: I only want data to be returned if `division` = 6.

**Comment by volkanceylan** [comment]
If they are in same server, use like you would in Sql Server

ForeignKey("[SecondDB].[dbo].[Aircrafts]", "AircraftID")

Serenity can also pick database name from connection string:

ForeignKey("[YourSecondDBConnectionKeyInWebConfig^].[dbo].[Aircrafts]", "AircraftID")

**Comment by wdhodges** [comment]
Awesome. I'll have to use the second web.config connection key since they are separated on two different servers.

**Comment by volkanceylan** [comment]
No this won't work across different servers unless they are linked servers etc. Serenity just picks database name from there, not full connection string. If you can't do something in SQL Management Studio, Serenity can't do that too, its just SQL.

**Comment by wdhodges** [comment]
Aahh. They're on the same intranet but two different servers.
