### ISSUE TITLE
Signal R WIKI

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4271]
@marcobisio 
I do not seem to have a way to contact you regarding the wiki post
https://github.com/volkanceylan/Serenity/wiki/Group-notifications-with-SignalR-(by-marcobisio)

Your files are listed , but not where you placed the code - I assume the global_asax will start the hub. 
At the end you state the script should be in a separate file and then included in the layout - can you show your example ? I am not sure if I am on the right track .. but I was going to name the globalNotification with a .js extension (not sure what folder to put it in ) or should I just create a layout and include it in my _layoutheader  How can I or should I do that ?

**Comment by marcobisio** [comment]
Hi @stixoffire,
I'm not sure about your question. You're right it's the code in Global.asax.cs that starts the hub:
![image](https://user-images.githubusercontent.com/17425690/53171381-da213080-35e2-11e9-96c6-b5956ce1cc41.png)

All the other files can be placed where you prefer and about the javascript library i just pointed out that it's always better to put the code in an external javascript file and reference it in your _LayoutHead.cshtml.

**Comment by stixoffire** [comment]
@marcobisio Ok thank you - that clarifies it for me .. Yes the code in separate Javascript file is better to maintain it - changes etc.. Thank you ...

**Comment by stixoffire** [comment]
@marcobisio Just revisiting this as I have now been able to get around to the notifications by SignalR.
Right now I am just doing a notify on create - so when I create a row a notification is sent out via the Hub ..
 I am not seeing the notification - the code runs with no errors but also no notifications.
 

Your code calls for a UserSupportGroupRow Could you share that portion of your code - so I can follow it better. The WIKI does not have it either. 



I know I have  a username  and a message  - but nothing .. 

I am not seeing where the notification should appear on my Webpage - perhaps because the logged in user is the same as the user that created the message ?

**Comment by marcobisio** [comment]
Please @stixoffire share your full implementation. either server side and client side so I can guide you through this, otherwise it will be difficult to guess what it's not working.
