### ISSUE TITLE
Read only fields not to focus on tab key.

### ISSUE THREAD

**Issue by PrasadK1990** [volkanceylan/Serenity#4272]
Hello,
please guide me.
Read only fields not to focus on tab key. It only focus on Editable fields.

**Comment by Zahar661** [comment]
tabindex="-1"

**Comment by PrasadK1990** [comment]
@volkanceylan Please help me

**Comment by PrasadK1990** [comment]
@Zahar661 Not working tabindex="-1".
Please help me.

**Comment by Zahar661** [comment]
how did you use tabindex= "-1"? Works, I checked.

**Comment by PrasadK1990** [comment]
![image](https://user-images.githubusercontent.com/39614625/53223907-e8318880-3698-11e9-8886-c17787684390.png)

**Comment by PrasadK1990** [comment]
@Zahar661 In above figure. in dialog some of fields are readonly. so i have to make tab key not to focus on readonly fields. it have to focus on editable fields.

**Comment by Zahar661** [comment]
So have you tried the fields for reading add "tabindex='-1'"?

**Comment by PrasadK1990** [comment]
in editmode()
this.form.InvoiceNo.element.attr("tabindex", 1);
is this correct?
@Zahar661

**Comment by Zahar661** [comment]
No
```
protected updateInterface(): void {
            super.updateInterface();
            this.element.find('.readonly').attr("tabindex", -1);
        }
```

**Comment by PrasadK1990** [comment]
Suppose first field is readonly and second field is editable then?
@Zahar661

**Comment by Zahar661** [comment]
tabindex= '-1' will be set for all fields that are read

**Comment by PrasadK1990** [comment]
Ok
