### ISSUE TITLE
Update from version 1.9.26 to 2.0.0 and {infinity} further without TypeScript recommendations

### ISSUE THREAD

**Issue by DimaMazur** [volkanceylan/Serenity#4273]
@volkanceylan , guys, help us please. We(me and @stepankurdylo) would like to update our Serenity project from 1.9.26 version to at least 2.0.0 version without TypeScript coz we have lots of .Net client logic in cs files. Are you recommend to do it? Can we use next versions of Saltarelle (Bridge.Net) to improve out client cs logic in the future?

**Comment by volkanceylan** [comment]
Saltaralle is obsolete so long ago.
