### ISSUE TITLE
display arabic charcters in pdf print

### ISSUE THREAD

**Issue by developper02** [volkanceylan/Serenity#4274]
hello, i want print pdf in serenity using a print button, the pdf is generated but the arabic caracters are not well dipslayed. How to display the arabic word correctly in the PDF in serenity .
Thank you

**Comment by ga5tan** [comment]
U may want to check generators github

**Comment by developper02** [comment]
> U may want to check generators github

i dont understand what yu mean

**Comment by ga5tan** [comment]
sorry about that.
try to google this 'wkhtmltopdf arabic'
wkhtmltopdf is the app used to convert html to PDF.
wkhtmltopdf is dead app, but still has github where you can search for answers
