### ISSUE TITLE
Call webservice from other app

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4275]
Hi,

I tried to call repository function from other app, but got 'Default connection not found error'

Googled here and found I have to initiate app, but that also failed.

So I am thinking of calling the webservice from asp.net app.

Do you have some sample on how to do it?

Thx in advance

**Comment by hubeyb** [comment]
you can make webrequest, but you must make api call to EndPoints (by service route).

for example Route("Services/[ProjectNamespace]/[ModuleName]/[action])
you can get json result from this endpoint url. 
but not to forget authenticate. Login and get session by WebRequest

**Comment by hubeyb** [comment]
look at issue #583 
c# example given before: [https://github.com/volkanceylan/Serenity/issues/583#issuecomment-366747276](url)

and java example: 
[https://github.com/volkanceylan/Serenity/issues/583#issuecomment-211867718](url)

[https://gist.github.com/volkanceylan/1b124f58c1e2b4fc7c7c](url)

**Comment by PanChenhao** [comment]
@hubeyb The link you provided is empty,  could you please help to check it? I also need web service functions and want to learn how to do it.
Thanks very much.

**Comment by ga5tan** [comment]
@PanChenhao how do u wanna call it ?
I was able to initialize Serenity in another app, so I can call directly.
As far as calling from external app via http, I got that working too, but dunno if I can find the sample.

**Comment by hubeyb** [comment]
https://gist.github.com/volkanceylan/1b124f58c1e2b4fc7c7c
https://github.com/volkanceylan/Serenity/issues/583
