### ISSUE TITLE
Add tab visibility to TabExtentions

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#4276]
Volkan,

In your next release, can you please add a setVisibility function to the TabExtensions for Core? For use in *Dialog.ts files

Example:

`Serenity.TabsExtensions.setVisibility(tabs: JQuery, tabKey: string, isVisible: boolean)`

Thanks for the considerations

**Comment by volkanceylan** [comment]
Added a toggle method, 89891a1c1e54c187d1fe4a1e554f2e1ab8fdd0a8, will be available in next version.
