### ISSUE TITLE
Show empty grid

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4277]
Hi 
I would like to show the grid empty when it is loaded but show records based on search result from the quick search.

Any idea and help please 
Thank you

**Comment by csabc** [comment]
[https://github.com/volkanceylan/Serenity/issues/4248#issuecomment-467051332](url)
you can try it.

**Comment by ms4hafiz** [comment]
Thank you @csabc 
but the link is not working

**Comment by csabc** [comment]
> Thank you @csabc
> but the link is not working

Sorry. [https://github.com/volkanceylan/Serenity/issues/4248](url)

**Comment by ms4hafiz** [comment]
I am not able to implement it with my situation. I need to show empty grid and then show records based on search result. Thank you

**Comment by alex-444** [comment]
@ms4hafiz try this..when you load the page the grid is empty.

put this in your grid page ts

```
  protected onViewSubmit(): boolean {
            if (!super.onViewSubmit()) {
                return false;
            }
   }
```
