### ISSUE TITLE
Convert numeric value into string

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4279]
Greetings,
Am creating a report in serenity where I display the total amount 
But my question is I want to convert the total amount into words
Is there any way to do this in serenity?

**Comment by edwardch** [comment]
Check [Convert integers to written numbers](https://stackoverflow.com/questions/3213/convert-integers-to-written-numbers)

**Comment by Shraddha996** [comment]
hey @edwardch thanks for your replay
I go through with the code but am unable to fit this in serenity
it would be great if you elaborate a little bit

**Comment by edwardch** [comment]
You can create a method using the code from one of the answers to convert your number to string. Add it as a helper, maybe?

**Comment by JohnRanger** [comment]
Hi @Shraddha996 ,

you have to learn the basics of an ASP.NET MVC app (google is your friend). Then learn how to add nuget packages to a Visual Studio ASP.NET MVC app (I think install-package <package name> could be the right direction.

From a quick look through the given solutions from the Link of edwardch it looks for me that https://github.com/Humanizr/Humanizer is the most promising. There you find a lot of examples how to turn diverse strings (incl numbers) into human readable text.

I do unfortunately not have the time to develop a fully working solution for you (and have no example around as I never had the need for such a thing) but the above advice should point you into the right direction.

With kind regards,

John

**Comment by Shraddha996** [comment]
Thanks, @JohnRanger For ur valuable reply!
