### ISSUE TITLE
Deep linking - passing a URL parameter to the List() method?

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#428]
I'm having trouble figuring out the best way to do this. I'd like to be able to create deep links e.g. "~/MyArea/MyEntity?ID=3" 
Ideally, I'd like ID=3 to be passed to the List method eventually being called by SlickGrid. If it can pass it as an EqualityFilter, that would work too.

Any ideas?

**Comment by volkanceylan** [comment]
OrderPage.cshtml should have such a filter sample

**Comment by wldkrd1** [comment]
That's exactly what I was looking for, thank you!
