### ISSUE TITLE
Error while refreshing report page

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4281]
Greetings,
I created print order by referring Northwind/Order samples
It working as I expected
but when I refresh the report page then it is showing error like this
![capture](https://user-images.githubusercontent.com/39983941/53389324-d3b10100-39b4-11e9-9278-735152f1ae1f.PNG)

there is also a same error in the serenity demo site

**Comment by volkanceylan** [comment]
You don't refresh the page, you press the enter key on address bar
