### ISSUE TITLE
How to Resize the Text Box 

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4282]
Hi everyone,
I want to increase the size of the text box from the particular form 
I also tried this code  in the form.cs file

[StaticTextBlock(Text = "<textarea name='message' rows='10' cols='30'></textarea>", IsHtml = true)]
    public String ProcessName { get; set; }

But I think it creates the new text box instead of increasing the size
So am not able to save the data in the ProcessName field
Is there something am missing?
any help would be appreciated.

**Comment by ga5tan** [comment]
just tag your field like this:
[TextAreaEditor(Rows = 10)]

**Comment by Shraddha996** [comment]
hey @ga5tan Thanks! this is perfect.
