### ISSUE TITLE
Problem with LinkingSetRelation

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#4283]
I have the following field definition with LinkingSetRelation attribute:
```
    public sealed class PermitRow : Row, IIdRow, INameRow
    {
        [DisplayName("Request"), NotNull, Unique, PrimaryKey, ForeignKey("[dbo].[REQUEST]", "RequestId"), LeftJoin("jRequest"), TextualField("RequestRequestNumber")]
        public Int32? RequestId
        {
            get { return Fields.RequestId[this]; }
            set { Fields.RequestId[this] = value; }
        }
.....
        [DisplayName("Zoning"), NotMapped, LookupEditor(typeof(ZoningRow), Multiple = true)]
        [LinkingSetRelation(typeof(PermitZoningRow), "RequestId", "ZoneId")]
        [MinSelectLevel(SelectLevel.Details), QuickFilter]
        public List<Int32> PermitZones
        {
            get { return Fields.PermitZones[this]; }
            set { Fields.PermitZones[this] = value; }
        }
....
        IIdField IIdRow.IdField
        {
            get { return Fields.RequestId; }
        }
.....
   }
```

When I try to save PermitRow, I get the following error:

**Cannot insert the value NULL into column 'RequestId', table 'permitsTEST.dbo.PERMIT_ZONING'; column does not allow nulls. INSERT fails.**

The strange thing is that I've successfully used the LinkingSetRelation in other classes. Searched through other related issues and I analyzed the Northwind Customer representatives scenario "to death". The only thing different is that RequestId is both PrimaryKey and ForeignKey (there is no Identity column in PERMIT table which works just fine). I just can't tell what I'm doing wrong. Any hint will be greatly appreciated.

**Comment by JohnRanger** [comment]
I don't know the version of SF you are using - but at least until recently I thought it was not possible to not have an identity field which is not an int - and I dont know if it is already possible.

As it seems from the error message, you are trying to save a record with nothing (null) in the RequestId field. Either you have set this field within your database to not allow null (not Null) or you have set the corresponding field definition within your xyzRows.cs to "notNull".

That would be my first gueesses...

With kind regards,

John

**Comment by c9482** [comment]
Hi @JohnRanger,

The RequestId is defined as int. It is also non-null because it's a primary key of PermitRow. Looking at the LinkingSetRelationBehavior source code, everything should be working. The master key (RequestId) should be automatically set during save (it should come from the PermitRow). I tried to setup VisualStudio to debug Serenity classes but it crashes so I can't step through all the code. I have everything set up identically as in the Customer Representatives sample:

Master key: RequestId -> CustomerId (both have PrimaryKey NotNull attributes)
Item key: ZoneId -> EmployeeId (both have Identity attribute)

Not sure what I am doing wrong...

**Comment by c9482** [comment]
Spent way too much time struggling with this. Thinks the problem is that the LinkingSetRelation requires Identity field for master key (PrimaryKey will not cut it). As a workaround I stored the multiple zones in a single string field:

        [DisplayName("Zoning"), Size(50), LookupEditor(typeof(ZoningRow), Multiple = true, Delimited = true)]
        public String Zoning
        {
            get { return Fields.Zoning[this]; }
            set { Fields.Zoning[this] = value; }
        }

Not ideal but will work for now.
