### ISSUE TITLE
How to Hide the Detail Grid

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4285]
Greetings,

I want to Hide the DetailList Grid From form.cs On a Specific condition
I have written this code

if (ItemCode.substring(0, 2) == '1A' || ItemCode.substring(0, 2) == '1E') {
                    this.element.find('DetailList2').show();
                }
               
                else {
                    this.element.find('DetailList2').hide();
                }

But It hiding the element from the grid, not actual Grid

Any help would be appreciated
Thanks in advance

**Comment by edwardch** [comment]
I did something similar so I think this might help. 

I have Client and Product on the master, and when creating a new master both of these have to be set before any of the details are displayed.

In your xyzForm.cs, above your detail list element:
```cs
[Category("Some Details")]
```

Then in xyzDialog.ts add this:
```ts
protected onDialogOpen() {
    super.onDialogOpen();
    if (this.isNew()) {
        var category = 'Some Details';
        this.categoryToggler([this.form.ClientId, this.form.ProductId], category);   
    }
}


protected categoryToggler(selectFields: Serenity.LookupEditor[], categoryTitle: string) {
    var myTag = categoryTitle;
    var ele = this.element.find(".category-title:contains('" + myTag + "')").parent();

    ele.toggle(false); //hidden by default
    for (var field of selectFields) {
        field.changeSelect2(e => {
            // Client AND Product need to be selected for this category to be displayed
            if (!Q.isEmptyOrNull(this.form.ClientId.value) && !Q.isEmptyOrNull(this.form.ProductId.value)) {
                ele.toggle(true);
            } else {
                ele.toggle(false);
            }
        });
    }
}; 
```

**Comment by minhhungit** [comment]
how about this:

> this.form.ProductList.getGridField().toggle(false);

**Comment by Shraddha996** [comment]
ty @minhhungit
