### ISSUE TITLE
Serial Not found

### ISSUE THREAD

**Issue by engOmniaShawky** [volkanceylan/Serenity#4286]
i have this issue and i can't find any reason for it.

![untitled](https://user-images.githubusercontent.com/45864166/53558646-1ad3f900-3b51-11e9-93fe-19f91a105d07.png)

i don't have any field with serial name.
any help please ?!

**Comment by engOmniaShawky** [comment]
@volkanceylan

**Comment by JohnRanger** [comment]
@engOmniaShawky ,

When (at what action) does this occur?

Scan your code (whole solution) for the string "Serial". 

With kind regards,

John

**Comment by engOmniaShawky** [comment]
update & add new record it's show random not in specific scenario,

nothing with serial name .

Many Thanks for reply .

**Comment by volkanceylan** [comment]
Scan your code (whole solution) for the Serial, forms!
