### ISSUE TITLE
How to restrict permissions for the users

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4288]
In my project there are 2types of users
1.admin
2.sys
so here 'admin' will have the all type of permissions for all modules to read,Edit,Delete,Insert etc..
(this is default behaviour in serenity sample project)...

But i want my 'sys' user to restrict to only one module how can i do this???

**Comment by JohnRanger** [comment]
Hi @flextrio-gandhi ,

I see that you ask a lot of basic questions (including this one) which are mostly all excellently answered in the superb Serenity guide of Volkan: [https://legacy.gitbook.com/book/volkanceylan/serenity-guide/details](url)

Therefore I recommend that you first study this guide (wholly) and also do the examples therein.

And then - if something is not clear - please feel free to ask here again :-)

With kind regards,

John

**Comment by flextrio-gandhi** [comment]
Thank you @JohnRanger
