### ISSUE TITLE
CaptureLog and Audit Log Implementation

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#429]
I am a little bit confused here, and apologize for this being discussed before but I have some questions about the Logging capabilities of Serenity and how best to implement them. I would like to be able to prevent users from deleting information from the database and only show active rows. Additionally, I want to be able to log all insert/update operations. The key here is, I would also like to see the before/after changes of the fields that are updated/deleted. I've looked at the samples for implementing an abstract base class like `LoggingRow.cs` from Northwind sample, and also looked at the sample in Serene for using `[CaptureLog(typeof(SampleLogRow))]`. The crux of the issue then, is whether I can and/or should implement *both* of these systems or just one of them. If I do implement `[CaptureLog(...)]` attribute for a Row, do I have to create a separate LogRow table for each Entity that I have in my project? Also, if I were to implement CaptureLog, do I need to implement IDeleteLogRow and IIsActiveDeletedRow interfaces as well to prevent deletes, or does that provide the same behavior?

I have created my own abstract base class that implements ILoggingRow, IDeleteLogRow, and IIsActiveDeletedRow like so:

```cs
namespace FlowState.Operations.Entities
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;

    public abstract class OpsLoggingRow : Row, ILoggingRow, IDeleteLogRow, IIsActiveDeletedRow
    {
        protected OpsLoggingRow(RowFieldsBase fields)
            : base(fields)
        {
            opsLoggingFields = (OpsLoggingRowFields) fields;
        }

        [NotNull, Insertable(false), Updatable(false)]
        public Int32? InsertUserId
        {
            get { return opsLoggingFields.InsertUserId[this]; }
            set { opsLoggingFields.InsertUserId[this] = value; }
        }

        [NotNull, Insertable(false), Updatable(false)]
        public DateTime? InsertDate
        {
            get { return opsLoggingFields.InsertDate[this]; }
            set { opsLoggingFields.InsertDate[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public Int32? UpdateUserId
        {
            get { return opsLoggingFields.UpdateUserId[this]; }
            set { opsLoggingFields.UpdateUserId[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public DateTime? UpdateDate
        {
            get { return opsLoggingFields.UpdateDate[this]; }
            set { opsLoggingFields.UpdateDate[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public Int32? DeleteUserId
        {
            get { return opsLoggingFields.DeleteUserId[this]; }
            set { opsLoggingFields.DeleteUserId[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public DateTime? DeleteDate
        {
            get { return opsLoggingFields.DeleteDate[this]; }
            set { opsLoggingFields.DeleteDate[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        public Int16? IsActive
        {
            get { return opsLoggingFields.IsActive[this]; }
            set { opsLoggingFields.IsActive[this] = value; }
        }

        IIdField IInsertLogRow.InsertUserIdField
        {
            get { return opsLoggingFields.InsertUserId; }
        }

        IIdField IUpdateLogRow.UpdateUserIdField
        {
            get { return opsLoggingFields.UpdateUserId; }
        }

        IIdField IDeleteLogRow.DeleteUserIdField
        {
            get { return opsLoggingFields.DeleteUserId; }
        }

        DateTimeField IInsertLogRow.InsertDateField
        {
            get { return opsLoggingFields.InsertDate; }
        }

        DateTimeField IUpdateLogRow.UpdateDateField
        {
            get { return opsLoggingFields.UpdateDate; }
        }

        DateTimeField IDeleteLogRow.DeleteDateField
        {
            get { return opsLoggingFields.DeleteDate; }
        }

        Int16Field IIsActiveRow.IsActiveField
        {
            get { return opsLoggingFields.IsActive; }
        }


        private OpsLoggingRowFields opsLoggingFields;

        public class OpsLoggingRowFields : RowFieldsBase
        {
            public Int32Field InsertUserId;
            public DateTimeField InsertDate;
            public Int32Field UpdateUserId;
            public DateTimeField UpdateDate;
            public Int32Field DeleteUserId;
            public DateTimeField DeleteDate;
            public Int16Field IsActive;

            public OpsLoggingRowFields(string tableName)
                : base(tableName)
            {
            }
        }
    }
}
```

If I were to use this interface on a Row, *and* also provide a `[CaptureLog(...)]` attribute, would there be redundant information between the CaptureLogRow table and the Row table itself? Thank you for clarifying things for me!

**Comment by volkanceylan** [comment]
You don't need to implement both IDeleteLogRow and IIsActiveDeleteRow but having both won't hurt anything. I know some users that does this.

If you want to store who deleted row in a separate field, implement IDeleteLogRow. 

There is also another possibility. You may have just IUpdateLogRow and IIsActiveDeletedRow in your row, so Update log fields will be used for Insert/Update/Delete.

This is about personal preference. Some want 7 fields, some want 3, some want none.

CaptureLog will only log matching fields in your capture log table. Capture log row already has ChangingUserId (Insert/Update/Delete) and ChangeDate (ValidFrom) fields so you don't have to add these other log fields to capture table if you don't want redundancy. If you do CaptureLog will log them as is. 

A little nuance is, unlike ordinary fields, when you update a record and only its UpdateDate changes, capture log won't record that change at all. This is to keep log size minimum for users that presses Save button to close dialogs without changing anything :|

**Comment by jsbUSMC** [comment]
Thank you very much for your clarification @volkanceylan , I think I will be using your suggestion about IUpdateLogRow and IIsAciveDeletedRow. I will also be using CaptureLogRow to capture the changed fields.

To make sure I'm doing this the right way: 

* Implement interfaces for IUpdateLogRow and IIsActiveDeletedRow on my OpsLoggingRow abstract class like this:
```cs
// ...
public abstract class OpsLoggingRow : Row, IUpdateLogRow, IIsActiveDeletedRow
{ ... }
```
* Create and run migrations for adding the UpdateUserId, UpdateDate and IsActive fields to each table to satisfy the interface contracts.
* Create and run a migration to create CaptureLog tables for each EntityRow that I want CDC enabled for.
* Attribute each EntityRow with `[CaptureLog(typeof(someEntityRow))]` above the class declaration like so:
```cs
// ... other attributes omitted for brevity
[CaptureLog(typeof(WorkloadCaptureRow))]
public sealed class WorkloadRow : OpsLoggingRow, IIdRow, INameRow
```

Thank you very much for all your help. Once I get this implemented properly, I'll add to the Wiki my (sanitized) code for others to emulate.

**Comment by volkanceylan** [comment]
You're welcome. Make sure you add IsActive field to your capture log table too, otherwise you won't see "virtual deletes" in capture log as capture log only logs actual deletes. Virtual deletes, e.g. setting IsActive to -1, is logged as an update. CaptureLog is closer to database level logging.

**Comment by jsbUSMC** [comment]
Thank you for helping and clearing this up for me. I'll post code if I can get this plan to implement a change log viewer for all entities up and running.

**Comment by kanasanjee** [comment]
Hi John, were you able to complete your change log viewer? If so, could you please tell me where I can find the code?

Thanks,

Sanji

**Comment by jsbUSMC** [comment]
No not yet. I've gotten behind with other work, but my plan is to use SignalR along with possibly RxJS on the client side in order to see changes in real-time with filtering/sorting. I'll keep you posted though, maybe you can help with the code if I get stuck

**Comment by kanasanjee** [comment]
Thanks John, I’ll be monitoring the issues page,

Sanji
