### ISSUE TITLE
file upload issue (everything over 50mb failing)

### ISSUE THREAD

**Issue by ReatKay** [volkanceylan/Serenity#4290]
I'm nearly freaking out now - not because of the issue itself, more because I seem unable to resolve it.

**The Issue**
Every fileupload over 50MB is failing: Resulting in a 404 response once it hits 100% progress. Everything below 50MB works. I tried locally aswel, to erradicate connection issues - even the file is "uploaded within 2s, same problem". 

**Platform**
Serenity 3.8.1, Windows (Windows 2016 Datacenter, IIS 7.0 / Windows 10 Pro, IIS Express)
jQuery package 3.3.1, jQuery UI combined 1.12.1, jQuery Validation 1.17

**What I checked/tried**
- Checking/adjusting all request limits on IIS/web.config.
- Increased global jQuery ajax timeout value (first suspition was that it's a timeout issue, as it always happnened on 60s -> bad conincidence, it took always nearly exact 60s with my test file)
- Doing a "manual jQuery" upload - resulting in exact same behaviour.
- Setting manual filesize options/timeouts on jQuery calls.
- Adding backend debug helpers - unfortunately, they are never hit, as the backend handling function is never reached when the file is over 50MB. (PS: Filetype changes are not changing anything).

I have to say, I'm not really an expert with frontend coding (especially JS etc) - I'm totally a backend gui. But this seems to be a frontend issue (at least I suspect this) and unfortunately, jQuery does not seem to give me any error code or something (beside the nothing saying 404 response).  

Thankful for any hint/help.

All the best
RK

**Comment by volkanceylan** [comment]
See ASP.NET upload limits in their docs or StackOverflow etc.

**Comment by promiseap2014** [comment]
@ReatKay check out this wiki https://github.com/volkanceylan/Serenity/wiki/Additional-Feature:-Implementing-Large-File-Upload-Editor

**Comment by stixoffire** [comment]
@promiseap2014  The problem with the largefileupload is if you have an older version of serenity (as I do) , once a reference is made to the Asp.Net.Api it converts to rosyln - that broke my project - I got no builds (no errors on build) just no project changes in website debugging source was always different than running code. Kicked my but for 2 days.
