### ISSUE TITLE
Translation is not working when using Tab

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#4293]
when using tab control in my screen and set a translation for the tab title , the translated text not appear in the tab control.
translation is working without any problem for other controls like category or fields.
please advise

**Comment by BravoSierra** [comment]
You may want to look at #4048 localisation for Hint and Tab attributes
https://github.com/volkanceylan/Serenity/issues/4048

**Comment by amrgDev** [comment]
thanks
