### ISSUE TITLE
Latest upgrade issues - not able to see fields on UI

### ISSUE THREAD

**Issue by AlexaOperations70** [volkanceylan/Serenity#4294]
Dear volkanceylan

Need your help. After upgrading serenity to latest version I am getting errors & not able to see any fields on UI.

**Transform all T4 template exited with below error:**

Transforming templates for all project items.
-------------------------------------
Transforming template ClientTypes.tt with TextTemplatingFileGenerator ... failed.
Transforming template MVC.tt with TextTemplatingFileGenerator ... succeeded.
Transforming template ServerTypings.tt with TextTemplatingFileGenerator ... failed.
-------------------------------------
Text templating transformation complete. 

I am using VS2015 and I also upgraded typescript to 3.2 version and updated .cproj  to "<Project ToolsVersion="14.0" earlier it was 12, VS was complaining with errors. Post this issue still not resolved.

Please find build errors:

[build error.txt](https://github.com/volkanceylan/Serenity/files/2922304/build.error.txt)

Can you please point out what should I do to resolve this issue? Are there any dependencies, I should look into?

Cheers

**Comment by ga5tan** [comment]
could it be u updated Typescript.MSbuild to ver 3.2+?
#4189 
in that case consider googling and trying suggested solutions, or simply revert to older version (I did) and wait it out

**Comment by AlexaOperations70** [comment]
Thanks ga5tan for response

Earlier typescript version was 2.1 and post serenity upgrade and transforming T4 templates, it started to erroring out. 

I shall try your suggestion & get back.

**Comment by AlexaOperations70** [comment]
Dear ga5tan

I tried both solutions suggested under #4189 but it did not work

1. Installing Microsoft.TypeScript.MSBuild - This did not resolve problem ( as suggesteby @PranavSenthilnathan)

2. changing exe command as suggested by volkanceylan
 <Exec Command="&quot;$(NodePath)\node&quot; &quot;$(TSJavaScriptFile.Replace('build\\..\tools\', 'tools\'))&quot; -p ./tsconfig.json" ContinueOnError="true" />

Pls help..  ( pls find build error. I have moved back ToolsVersion to 12 ( it was earlier one) in .cproj. Just ot ensure I do not make too many changes. ( Both version 14 as well as 12 did not solve the problem)

Regards
[build error 3-march.txt](https://github.com/volkanceylan/Serenity/files/2922872/build.error.3-march.txt)

**Comment by ga5tan** [comment]
sorry man, I cannot help you any other than just repeat what I did and what worked for me.
go back to 3.1.1 (Microsoft.TypeScript.MSBuild)
I dont know what your versions are you talk about.
In my *.Web.csproj I have all the paths to :

> packages\Microsoft.TypeScript.MSBuild.3.1.1
and it works fine.
It also seems to be only place dealing with this. so if you dont have 3.1.1 anymore, install it and change paths to point there...
