### ISSUE TITLE
is built in bundling include css or it is for js files only

### ISSUE THREAD

**Issue by mjacoup** [volkanceylan/Serenity#4295]
i wonder how we can bundle the css with the built in bundle feature

**Comment by ga5tan** [comment]
I believe u could do CSS as well, just have to enable it. start with checking json configs, and maybe web.config...

**Comment by edwardch** [comment]
You'll want to enable bundling in the Web.config. 

Check for these setting keys:
- CssBundling
- ScriptBundling
