### ISSUE TITLE
Modify sql queries

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4297]
Hey,
First of all I want to thank @volkanceylan for this amazing platform,
It's not an issue but I want to ask something..
If I have something like created_by column in all of my tables and I don't want to show this field in the grids and in the same time I want it to insert the value from the c# which is a session that created when the user login
how can I do that? 
In other way to say it I want to modify the insert query so I can add a parameter created_by_value which is a value of a session created once the user logged in..

I am using core version

Thanks

**Comment by edwardch** [comment]
You can keep this field in your xyzRow.cs, but remove it from xyzColumn.cs and remove it from xyzForm.cs. 

In your xyzRepository.cs you can do something like this in your save handler:
```cs
private class MySaveHandler : SaveRequestHandler<MyRow>
{
    protected override void SetInternalFields()
    {
        base.SetInternalFields();

        if (IsCreate)
        {
            Row.Created_By = ((UserDefinition)Authorization.UserDefinition).UserId;
        }
    }
}
```

**Comment by tonysader** [comment]
@edwardch veryyyyyyyyyy helpful.. thank you very much..
I need one other thing if you could help me..
I don't want to make duplicates in my record.. In previous apps I was creating stored procedures and then throw an error when the 'title' (title is one field of my table) is existed before.. How can I do that here?? 
And again thank you for your helpful reply..

**Comment by edwardch** [comment]
If you create a unique index or a unique constraint on a specific field in your table (in SQL) then when you try to save a record with a duplicate, the database will throw the error automatically, not allowing you to save the record. 

It's best practice to set the constraint rather than to check yourself. You can also try to handle the error if you want a pretty message...

**Comment by edwardch** [comment]
Also, take a look at UserRow.cs, and look at "LoggingRow". 

The user table keeps track of created by, updated by, time created, and time updated. These are handy fields!

You'll want to put the fields in the database, but do not need to specify them in your xyzRow.cs. Look in the initial migration in DefaultDB to see which fields are put on the user table.

HTH!

**Comment by tonysader** [comment]
@edwardch very nice but I have a unique index which is of course the book_id.. I am not afraid of duplicates in this field of course, but I am afraid of the book_title that field is string--nvarchar and I don't want to duplicates in this one..
Thanks

**Comment by edwardch** [comment]
By default a table's primary key (book_id) would have a unique index on it. 
Then you can also set up your own unique indexes on other columns as well. This allows columns that are often used as lookups/joins to be referenced quickly. You can also set up non-unique indexes on columns, for performance reasons. 

But best practice is to set up a **unique index** on your book_title column. You can also use a **unique constraint**. These are both very similar.

This won't allow you to insert duplicate values.

```sql
-- You can create a unique index
CREATE UNIQUE INDEX UIX_Books_BookTitle ON Books(book_title)
-- Or you can create a unique constraint
ALTER TABLE Books ADD CONSTRAINT UC_Books_BookTitle UNIQUE (book_title)
```

You could also do these in a migration, something like this:
```cs
// Unique index
Create.Index("UIX_Books_BookTitle")
    .OnTable("Books")
    .OnColumn("book_title")
    .Ascending()
    .WithOptions().Unique();

// Or, a unique constraint
Create.UniqueConstraint("UC_Books_BookTitle")
    .OnTable("Books")
    .Column("book_title")
    .NonClustered();
```

**Comment by tonysader** [comment]
@edwardch Okk these are new sql info for me, and it will help me in the next projects very much.. Thanks
