### ISSUE TITLE
Add file field

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4299]
Hey there,
Any ideas about how can I add a file to my columns and grid..
And what type of data should be in the database??
The file(Document,picture,video...etc)

**Comment by choss21** [comment]
Hi
Here a example with image

https://serenity.is/demo/BasicSamples/InlineImageInGrid

**Comment by edwardch** [comment]
Yes, you can use the sample from the demo like @choss21 mentioned. Or if you want a download editor try using [FileDownloadFormatter()] attribute. You can set the original file name property in this so you have a "cleaner" display in your grid. 
Good luck!

**Comment by tonysader** [comment]
@edwardch @choss21 thanks guys this example helped me but something I can't figure out.. Sorry but I am noob in typescript and this platform!..
I have my table in sql-server and the module without the image so I added [this ](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineImageInGrid/InlineImageFormatter.ts) file to the module.. 
and this code

`protected getSlickOptions(): Slick.GridOptions {
            let opt = super.getSlickOptions();
            opt.rowHeight = 150;
            return opt;
        }`

to my xyzGrid.ts file 
and this code:
` [InlineImageFormatter, Width(450)]
        public String ProductImage { get; set; }`

to my xyzColumns.cs file

Now I have to add the ProductImage to my rows.. Should I add it as a string and in my sql table add it as a varchar ????????????? No sense I think 
I didn't get well the example.

Thanks

**Comment by edwardch** [comment]
I'm still not sure if you want a download link in the columns, or to display the file/image itself like in the example @choss21 referenced... 

You'll add the column as NVARCHAR() (or just specify .AsString() in your migration). You might want an extra string/nvarchar field to store the OriginalFileName as well.

But if you want to convert to binary then look around in past issues (eg #3890).

**Comment by tonysader** [comment]
Yes it worked.. and also I get the help from [here](https://serenity.is/docs/tutorials/movies/adding_primary_and_gallery_images)
Thanks @edwardch

**Comment by tonysader** [comment]
@edwardch so now everything is good dealing with pictures. But I can't add other file types.
Do you know where should I edit ?
