### ISSUE TITLE
Master Details issue not found in registered script list!

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#430]
Script data Columns.ABPnP.PeStakeholders is not found in registered script list!

Any Idea how i can debug it am lost , Followed movie cast turorial

**Comment by volkanceylan** [comment]
Check ColumnsKey on your PeStakeholdersColumns

**Comment by zerodev** [comment]
the editor you mean ?

` [ColumnsKey("ABPnP.PeStakeholders"), LocalTextPrefix("ABPnP.PeStakeholders")]
    [DialogType(typeof(PeStakeholdersEditDialog))]
    public class PeStakeholdersEditor : GridEditorBase<PeStakeholdersRow>
    {`

**Comment by volkanceylan** [comment]
No i mean server side columns...... If you don't have such columns, how do you expect it to load it?

**Comment by zerodev** [comment]
no i have the columns
`[ColumnsScript("Policy.PeStakeholders")]
    [BasedOnRow(typeof(Entities.PeStakeholdersRow))]
    public class PeStakeholdersColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 PeStakeholdersId { get; set; }
        public Int32 PersonId { get; set; }
        public Int32 PolicyExceptionId { get; set; }
        public Int32 PersonOrder { get; set; }
    }`

**Comment by volkanceylan** [comment]
Policy.PeStakeholders and ABPnP.PeStakeholders doesn't match isn't it?

**Comment by zerodev** [comment]
Shame on me :(
