### ISSUE TITLE
How can I create HTML Page with Serenity Grid ?

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4300]
Hello,

I want to add serenity grid in my .html page , which are the css and js  files responsible to it. I want similar look and feel.

**Comment by sayuga** [comment]
serenity grid is based off of slickfrid. you can use that repository as reference. Are you using serenity as the base of you site or are you just looking to add the grid template to an existing site?

**Comment by TechAspirant** [comment]
I want to add grid template in my existing site.

**Comment by sayuga** [comment]
Then I suggest looking at the Slickgrid repository from. https://github.com/mleibman/SlickGrid though I do believe there are some more active forks. Do note @volkanceylan did make changes in the functionality to meet the Serenity needs so if you want to use the features as they stand in Serenity, you'd have to use the core build of serenity as a base and then use the usual approach of adding a grid much like explained in the docs.
