### ISSUE TITLE
Radio Button on Transaction grid

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4302]
Hello,
I refer the Product Picker sample but I want radio button instead of a checkboxes
Please Help

**Comment by minhhungit** [comment]
@Shraddha996 then replace checkbox with Serenity.GridRadioSelectionMixin

**Comment by minhhungit** [comment]
check more at here: https://github.com/volkanceylan/Serenity/wiki/Grid-Radio-Row-Selection-Mixin

**Comment by Shraddha996** [comment]
@minhhungit  thanks for that link 
here u can see now am able to get the radio button on the grid
But Can I push the item in the 2nd grid on the selection of the radio button

should I use ChangeSelect2 event?

![capture1](https://user-images.githubusercontent.com/39983941/53857261-7a238480-3ffb-11e9-8277-a04bea5dcfba.PNG)

Thanks in advance

**Comment by minhhungit** [comment]
I am not sure I understand your question, can you explain more detail please

**Comment by Shraddha996** [comment]
okay In above snippet u can see there are 3 characteristics value RED BLUE GREEN which came from BOMCharacteristics table so now on the click of radio button I want to fetch items in the second grid which is ADDED ITEMS grid

I know changeSelect2 is used for lookup selection and perform event 
so similarly is there any method in serenity for the radio button click

**Comment by minhhungit** [comment]
Try this one, sir:
```javascript
constructor(container: JQuery) {
    super(container);

    this.getGrid().onClick.subscribe((e, p) => {
        if ($(e.target).hasClass('rad-select-item')) {
            e.preventDefault();

            var item = this.getView().getItem(p.row);
            var id = item[this.getIdProperty()].toString();

            console.log(item);
            console.log(id);

            // write code to add item into grid editor here
            // ...
            // ...
        }
    });
}
```

**Comment by Shraddha996** [comment]
@minhhungit  Thanks for your patients,
But am suppose to write the code in the dialog.ts and I think the above code is for grid.ts or Editor.ts
It would be great if I get a way to call from my master dialog.ts

**Comment by Shraddha996** [comment]
@minhhungit 
I tried this by referring your code
`constructor(container: JQuery) {
            super(container);
            this.getGrid().onClick.subscribe((e, p) => {
                if ($(e.target).hasClass('rad-select-item')) {
                    e.preventDefault();

                    var item = this.getView().getItem(p.row);//red and char id
                    var id = item[this.getIdProperty()].toString();//id 1,2,3
                    
                    if (item != null) {
                        var details1: TblNetworkOrderTranRow[] = [];
                        var BOMChar = RnD.TblBomCharacteristicsRow.getLookup().items.filter(x => x.CharacteristicsValue === "Red")[0];
                        var BOM = RnD.TblBomRow.getLookup().items.filter(x => x.BomId === BOMChar.BomId);
                        for (var BOMCharDetails of BOM) {
                            details1.push({ ItemItemCode: BOMCharDetails.ItemCode });
                        }
                       // this.form.DetailList1.value = details1;
                    }
                }
            });
        }`

everything is fine till details1.push
after that I want to add
` this .form.DetailList1.value = details1;`
this code but I couldn't find the form fields in the editor

please help me with this
Thanks in advance

**Comment by minhhungit** [comment]
another approach (this way you will know how to add/remove item of grid editor)

```javascript
details1.forEach((item, idx) => {
    let id = J.UniqueHelper.nextNegativeNumber();
    item["__id"] = "`" + id;

    this.form.DetailList1.view.addItem(item);
});
```

and helper class:
```javascript
namespace J {
    export class UniqueHelper {
        public static uniqueNumber = 0;
        public static uniqueNegativeNumber = 0;

        public static nextNumber() {
            return this.uniqueNumber++;
        }

        public static nextNegativeNumber() {
            this.uniqueNegativeNumber = this.uniqueNegativeNumber - 1;
            return this.uniqueNegativeNumber;
        }
    }
}
```

**Comment by Shraddha996** [comment]
hey @minhhungit 
Actually, I tried this
`Serenity.EditorUtils.setValue(this.form.DetailList1, details1);`
Now my code is
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Serene1.DomesticOrder {

    @Serenity.Decorators.registerClass()
    export class TblValueTranEditor extends Common.GridEditorBase<TblValueTranRow> {
        protected getColumnsKey() { return "DomesticOrder.TblValueTran"; }
        protected getFormKey() { return TblNetworkOrderForm.formKey; }
        protected getDialogType() { return TblValueTranDialog; }
        protected getLocalTextPrefix() { return TblValueTranRow.localTextPrefix; }
        private form: TblNetworkOrderForm;
        private radRowSelection: Serene1.ValueTranPicker;
        constructor(container: JQuery) {
            super(container);
            //this.rowSelection = new Serenity.GridRowSelectionMixin(this);
            //this.form = new TblNetworkOrderForm(this.idprefix);
            this.getGrid().onClick.subscribe((e, p) => {
                if ($(e.target).hasClass('rad-select-item')) {
                    e.preventDefault();
                    var item = this.getView().getItem(p.row);//red and bomchar id
                    var id = item[this.getIdProperty()].toString();//id 1,2,3
                    if (item != null) {
                        var details1: TblNetworkOrderTranRow[] = [];
                        var BOMChar = RnD.TblBomCharacteristicsRow.getLookup().items.filter(x => x.CharacteristicsValue === "Red")[0];
                        var BOM = RnD.TblBomRow.getLookup().items.filter(x => x.BomId === BOMChar.BomId);
                        for (var BOMCharDetails of BOM) {
                            details1.push({ ItemItemCode: BOMCharDetails.ItemCode });
                        }
                        var BOM1 = RnD.TblBomRow.getLookup().items.filter(x => x.BomId === BOMChar.BomId)[0];
                        var BOMTran = RnD.TblBomTranRow.getLookup().items.filter(x => x.BomId === BOM1.BomId);
                        for (var BOMCharDetails1 of BOMTran) {
                            details1.push({ ItemItemCode: BOMCharDetails1.ItemCode });
                        }
                        //this.form.DetailList1.value = details1;
                        Serenity.EditorUtils.setValue(this.form.DetailList1, details1);
                    }  
                }
            });
        }    
        protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.radRowSelection = new Serene1.ValueTranPicker(this);
        }
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serene1.ValueTranPicker.createSelectColumn(() => this.radRowSelection));
            return columns;
        }
    }
}`

But still getting an error
![screenshot 18](https://user-images.githubusercontent.com/39983941/53932966-495a5280-40c2-11e9-914f-538f1a19942d.png)

**Comment by minhhungit** [comment]
I saw you wrote 
> this .form.DetailList1.value = details1;

so I think DetailList1 is your **Added Items** grid editor

btw, I suggest that you also should read serenity tutorial at here http://serenity.is/docs
