### ISSUE TITLE
How to Enable Edit and Delete Icons in In-Memory Grids

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#4304]
To enable this simple feature you can use simple code like so:

in xxxxEditor.ts
```
...

//Override Columns
protected getColumns(): Slick.Column[] {
	var columns = super.getColumns();

	columns.unshift({
		field: 'Delete Row',
		name: '',
		format: ctx => '<a class="inline-action delete-row" title="delete">' +
			'<i class="fa fa-trash-o text-red"></i></a>',
		width: 24,
		minWidth: 24,
		maxWidth: 24
	});

	columns.splice(1, 0, {
		field: 'View Details',
		name: '',
		format: ctx => '<a class="inline-action view-details" title="view details">' +
			'<i class="fa fa-search text-blue"></i></a>',
		width: 24,
		minWidth: 24,
		maxWidth: 24
	});

	return columns;
}
...
//Override onClick
protected onClick(e: JQueryEventObject, row: number, cell: number): void {
	super.onClick(e, row, cell);

	if (e.isDefaultPrevented())
		return;

	var item = this.itemAt(row);
	var target = $(e.target);

	// if user clicks "i" element, e.g. icon
	if (target.parent().hasClass('inline-action'))
		target = target.parent();

	if (target.hasClass('inline-action')) {
		e.preventDefault();

		if (target.hasClass('delete-row')) {
			Q.confirm('Delete row ?', () => {

				var editRow =  (('``' + (item.__id) as unknown) as number);
                        
                        var id = this.view.getRowById(editRow)

                        if (id == null) {

                            editRow = (('`' + (item.__id) as unknown) as number);
                            id = this.view.getRowById(editRow);
                            if (id == null) {
                                editRow = item.__id;

                                id = this.view.getRowById(editRow);
                                if (id != null) {
                                    this.view.deleteItem(editRow);
                                }

                            } else {
                                this.view.deleteItem(editRow);
                            }

                        } else {
                            this.view.deleteItem(editRow);                            
                        }

			});
		}
		else if (target.hasClass('view-details')) {

			var editRow = (('``' + (row) as unknown) as number);
			var id = this.view.getIdxById(editRow);
			if (id == null) {

				editRow = (('`' + (row) as unknown) as number);
				id = this.view.getIdxById(editRow);
				if (id == null) {
					editRow = row;

					id = this.view.getIdxById(editRow);
				}
			}

			//Edit Row !!!
			this.createEntityDialog(this.getItemType(), dlg => {
				var dialog = dlg as XXXEditorDialog;
				dialog.onDelete = (opt, callback) => {
					if (!this.deleteEntity(editRow)) {
						return;
					}
					callback({});
				};

				dialog.onSave = (opt, callback) => this.save(opt, callback);
				dialog.loadEntityAndOpenDialog(item);
			});;
		}
	}
}
...

```

The behaviour should be more friendly like so:
![exemploactionicons](https://user-images.githubusercontent.com/10889019/53764804-354a0180-3ec6-11e9-9dc3-62eec8126bae.gif)

**Comment by kilroyFR** [comment]
Thanks Bruno for improving frequently Memory Grids with new features !

**Comment by Shraddha996** [comment]
Hey @brunobola 
I refer your code for inline action grid
as I wanted to create an action grid on my editor
being able to get the new column of delete 
But, deleting row was not working as I expected
It is deleting only 2nd-row from the grid even though I click on the 1st row
Am attaching code for your reference

`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Serene1.PurchaseOrder {

    @Serenity.Decorators.registerClass()
    export class TblPoTranEditor extends Common.GridEditorBase<TblPoTranRow> {
        protected getColumnsKey() { return "PurchaseOrder.TblPoTran"; }
        protected getDialogType() { return TblPoTranDialog; }
        protected getLocalTextPrefix() { return TblPoTranRow.localTextPrefix; }

        public PrId: number;

        constructor(container: JQuery) {
            super(container);
        }

        validateEntity(row, id) {
            row.ItemId = Q.toId(row.ItemId);

            var sameItem = Q.tryFirst(this.view.getItems(), x => x.ItemId === row.ItemId);
            if (sameItem && this.id(sameItem) !== id) {
                Q.alert('This item is already in order details!');
                return false;
            }

            row.ItemName = Premier.TblItemRow.getLookup().itemById[row.ItemId].ItemName;
            row.Unit = Premier.TblItemRow.getLookup().itemById[row.ItemId].UnitUnitName;
            row.RemainingQuantity = row.Quantity;
            row.Amount = (row.Quantity || 0) * (row.Rate || 0);
            return true;
        }

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        //Override Columns
        protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();

            columns.unshift({
                field: 'Delete Row',
                name: '',
                format: ctx => '<a class="inline-action delete-row" title="delete">' +
                    '<i class="fa fa-trash-o text-red"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            return columns;
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                if (target.hasClass('delete-row')) {
                    Q.confirm('Delete row ?', () => {

                        var editRow = (('``' + (row) as PurchaseOrder.TblPoTranRow) as number);

                        var id = this.view.getIdxById(editRow);
                        if (id == null) {

                            editRow = (('`' + (row) as PurchaseOrder.TblPoTranRow) as number);
                            id = this.view.getIdxById(editRow);
                            if (id == null) {
                                editRow = row;

                                id = this.view.getIdxById(editRow);
                                if (id != null) {
                                    this.view.deleteItem(editRow);
                                }

                            } else {
                                this.view.deleteItem(editRow);
                            }

                        } else {
                            this.view.deleteItem(editRow);
                        }

                    });
                }
            }
        }
        }
    }
`

Kindly take a look
Thanks in advance!

**Comment by Shraddha996** [comment]
Kind request to
@brunobola @volkanceylan @kilroyFR 
Suggest something

**Comment by JohnRanger** [comment]
Hi @brunobola ,

I have the same problem as @Shraddha996 .

The inline delete action does not work.

I can see that the correct row is detected on click onto the delete icon - but it does not get deleted.

Only when I delete the record from within the detail dialog it gets deleted.

So far I could not figure out why the this.view.deleteItem dows not work.

If you have any hint I would be glad.

With kind regards,

John

**Comment by brunobola** [comment]
The inline delete should have the reference to your dialog not the base one, I have changed the sample code for more understanding.

Sorry for late response guys, I've got a big project in hands.

**Comment by JohnRanger** [comment]
Hi @brunobola ,

thanks for taking your time to come back to our questions :-) And I wish you much success in your project!

I will test your code fix and give feedback here.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi @brunobola , @Shraddha996 , @kilroyFR ,

the delete button still didn't work for me - so I tried the following shorter way - and at least for me - this works now:

instead of:

```ts
		if (target.hasClass('delete-row')) {
			Q.confirm('Delete row ?', () => {

				var editRow =  (('``' + (item.__id) as unknown) as number);
                        
                        var id = this.view.getRowById(editRow)

                        if (id == null) {

                            editRow = (('`' + (item.__id) as unknown) as number);
                            id = this.view.getRowById(editRow);
                            if (id == null) {
                                editRow = item.__id;

                                id = this.view.getRowById(editRow);
                                if (id != null) {
                                    this.view.deleteItem(editRow);
                                }

                            } else {
                                this.view.deleteItem(editRow);
                            }

                        } else {
                            this.view.deleteItem(editRow);                            
                        }

			});
		}
```

I do only the following:

```ts
		if (target.hasClass('delete-row')) {
			Q.confirm('Delete row ?', () => {
                             var id = item.__id;
                             this.view.deleteItem(id);
                    });
		}

```

Hope this helps someone.

With kind regards,

John

**Comment by stixoffire** [comment]
@brunobola I would like to see how you integrated the Text Editor into your text area description field.
Did you use TinyMCE or another - and how did you add that - did you create a declaration formatter for the field ?

BTW - I love this post here too.
