### ISSUE TITLE
How to call Different forms in Dialog.ts

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4307]
greetings,
Hi everyone
My question is simply that I want to call 2-3 Forms in one dialog
Is it possible?

I tried like this
protected form1 = new DomesticOrder.TblValueForm(this.idPrefix);

**Comment by brunobola** [comment]
There are several options, but I would use like so:

var dialog: XXXXDialog;
dialog.loadEntityAndOpenDialog(item);
