### ISSUE TITLE
How to pass FORM.cs data from Master Dialog to Details Memory Grid editor

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4308]
hello everyone!
I want to pass the detaillist field from form.cs  to editor.ts
 so I can push data in that detaillist from editor.ts

any suggestion would be appreciated
Thanks

**Comment by brunobola** [comment]
There are several issues regarding this, just do a search first please....

**Comment by Shraddha996** [comment]
Thanks, @brunobola 
I already search for several issues regarding this but I end up by getting only fields 
I want to access my whole DetailList data on the dialog.ts

**Comment by ngaggiano** [comment]
Modify your ListHandler, to return the data, then see my post on the post button for the code, this is done in the grid ts and displays the data in the dalog ts, the data comes from the form which is mapped to the repository
