### ISSUE TITLE
Running Migrations

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#431]
So I was wondering how I could set up the ability to run migrations on an entirely new database? Example: I have developed an application using the DefaultDB. I change the connection string to connect to the production db, remove the security check. Will the migrations from the DefaultDB namespace run from the start onto the new production db? If not how can I make this happen?

**Comment by volkanceylan** [comment]
Yep it will run in empty db

**Comment by wdhodges** [comment]
So it would run the entire namespace migration (like 25 migrations) from
start to finish? That's awesome. Thank you good sir

**Comment by volkanceylan** [comment]
Yes, if they are ordered correctly (migration numbers), you shouldn't have any problems.
