### ISSUE TITLE
Export row to pdf or word

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4310]
Hello everyone..
Is there any example or demo of how can I export one record of my grid to pdf or word??
Thanks

**Comment by edwardch** [comment]
Yep check the [demo](https://serenity.is/demo/Northwind/Order), click the inline pdf invoice icon.

In the Northwind module look at Order/OrderDetailReport.cs and .cshtml.
On OrderGrid.ts you can see how this is called.

**Comment by tonysader** [comment]
@edwardch and what is the reportkey in the grid.ts ?
Thanks

**Comment by edwardch** [comment]
Same as what's in the top of OrderDetailReport.cs
```cs
[Report("Northwind.OrderDetail")]
```
