### ISSUE TITLE
Dropdown issue serenity

### ISSUE THREAD

**Issue by nareshIntelegain** [volkanceylan/Serenity#4311]
Hi Vlkanceylan,

Naresh here, I want to fill dropdown with conditionwise.

For example suppose admin is looged into website then show all role in dropdown and if other user is logged then show all role except Admin role. So how can i implement this. Because my current system display all roles.

**Comment by edwardch** [comment]
You can try doing a [Custom Row Lookup Script](https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/handling_lookup_scripts.html)

There are lots of questions about this already, so check out the other issues too. 

Good luck!
