### ISSUE TITLE
Show edit

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#4312]
Role permissions according to hiearchy

Suppose Admin has given permissions to role standbyadmin  for only menu item-1 and menu item -2 out of four menu items  and also given access to Standbyadmin to  edit role permissions option. 
Now when User with Standbyadmin role  logs in and wants to give permissions to  other users .. only permissions for Menu Item -1 and Menu item -2  permissions he should be able to give to other users , Is this possble??

**Comment by stixoffire** [comment]
As an Aside to this - I would like my user to be able to have permission to change their picture , but not be able to touch anything else - currently there is no access to Users for my users (obvious reasons) so How can I give simple permission to change User Image .. 
Anyone have any ideas ?

**Comment by volkanceylan** [comment]
Do it like change password

**Comment by vinaysalian** [comment]
Like change password ?

**Comment by vinaysalian** [comment]
I am not able to give hierachial permissions  based on role wise  . Please help
