### ISSUE TITLE
Upgrade from mvc version 3.6 to mvc core latest version

### ISSUE THREAD

**Issue by mjacoup** [volkanceylan/Serenity#4314]
I really confused and read all upgrade issues but i din't found answer to my question . My project run with version 3.6 .. can i upgrade it to mvc core latest version ? where is the steps if it is possible

**Comment by ga5tan** [comment]
If u want to upgrade same branch, just go for it.
But I don't think it would be easy to go from MVC to . Net Core

**Comment by mjacoup** [comment]
Ok i know it is not easy .. but no one  do it before so that help us about the steps ?

**Comment by ga5tan** [comment]
I guess you could follow steps for migrating existing Serene  solution to StartSharp....

One way to do it is to generate new .core solution and only move your custom stuff/modules to it.
That sounds most straightforward to me

**Comment by mafdy** [comment]
@mjacoup You'd better not to migrate from MVC to AspNetCore. Of course if you want that you can do it by creating a new project as AspNetCore, then moving your modules from the old project to the new one (I did that once, and it worked for me), by the way you will need to fix some namespaces and so on. but **my personal opinion** for you is that MVC more stable than AspNetCore, specially when it come to database and publish problems (some times it cost me days just to know what cause a little problem).
