### ISSUE TITLE
Mater/Detail - how to save only selected row

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4315]
Hello,
I created a master-detail relation in my table where I push the Items in the second grid on the selection of Characteristics Id
As you can see there are radio buttons on the second grid
So now, I want to save only one row (RED) in the transaction table on main save button
![capture2](https://user-images.githubusercontent.com/39983941/54024106-c4079880-41bc-11e9-8349-08982d103e3b.PNG)

Thanks in advance!

**Comment by ga5tan** [comment]
Maybe intercept saving in repo and just skip it if not checked?

**Comment by Shraddha996** [comment]
@ga5tan Thnks!
