### ISSUE TITLE
Problem with deployment on Ubuntu

### ISSUE THREAD

**Issue by kenghot** [volkanceylan/Serenity#4318]
I've deploy serenity on Ubutu and found that there was some error about file name and path name issues.
Serenity works well on Window but Linux doesn't .As you know Linux is case sensitive file name . When your code refer to  static files sometime Linux can not locate that file. 
For example, 
in ScriptBundles.json
"Site": [ ...,
"~/Scripts/jquery.maskedInput.js",
.... ]

but actual file name is jquery.maskedinput.js ("i" is lower case )

and bootstrap.css refers to font files in folder /fonts/ but actual folder name is /Fonts/
@font-face {

  font-family: 'Glyphicons Halflings';

  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix')

these are only some example that i've found lately. I've google for the solution to set up dot net core (Kestrel)   file name case insensitive but haven't find a solution yet.

**Comment by volkanceylan** [comment]
Fixed in latest version of Serene, tested in Ubuntu
