### ISSUE TITLE
[致命错误 Fatal] If Project Name Like 'tc-flight-flightstatus' 

### ISSUE THREAD

**Issue by MisayaJj** [volkanceylan/Serenity#432]
you can hava a test  ,name the project like 'tc-flight-flightstatus'  ;
the chrome Web  browser could not find the file like  :http://192.168.199.211/Scripts/Site/tc_flight_flightstatus.Script.js?v=2016301912

**Comment by MisayaJj** [comment]
couldn't find the js file

**Comment by MisayaJj** [comment]
infact  the path contains the file

**Comment by volkanceylan** [comment]
This is probably caused by Visual Studio replacing "-" with "_" to generate safe project name while creating template. Some things are out of control by me so you should better avoid using dashes and dots in project name.

**Comment by MisayaJj** [comment]
may i use your Serenity free in my Company use  ?

**Comment by volkanceylan** [comment]
Sure its MIT licence

**Comment by MisayaJj** [comment]
thank you !
