### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by ganesh9290** [volkanceylan/Serenity#4320]
![Capture](https://user-images.githubusercontent.com/48408736/54085274-5bf2b700-4362-11e9-940a-2c33421b6c09.PNG)

I am using visual studio 2013 ///<reference types="jquery" /> invalid reference directive error.
>>>i am installed node js and type script also.All errors in node_modules.

**Comment by ganesh9290** [comment]
hello any one please review and reply.

**Comment by stixoffire** [comment]
You have a TypeScript issue either the typescript is not the proper installation or installation is corrupt - did you install typescript (how many versions do you have installed - as windows will have a default version that gets called if you have more than one - you will need to look at the typescript docs (as I cant remember the details) .. I had this same issue before... but I had to unistall and re-install typescript .. your Build templates should open the command prompt to build the typescript from tsc.exe  visual studio will need to build with the proper version ..
