### ISSUE TITLE
How to hide a radio button

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4321]
Hi,
Maybe this issue has already been posted, but I haven't seen

I have radio buttons on my transaction grid
I want to hide the radio button while editing the records
![Capture3](https://user-images.githubusercontent.com/39983941/54104422-dfa9b380-43f5-11e9-96f0-0bcb4cf04a3e.PNG)

**Comment by promiseap2014** [comment]
You can hide it using jQuery in your dialog.ts
```
protected updateInterface() {
    super.updateInterface();
        if (this.isEditMode()) {
            this.form.Transaction.element.find('input[type=radio]').toggle(false);
        }
    }
```
The code might not be correct, it demonstrates the idea.
