### ISSUE TITLE
Dialog Grid elements change CSS

### ISSUE THREAD

**Issue by ngaggiano** [volkanceylan/Serenity#4322]
Hi,
I have data coming into a form from a database and this displays correctly and I can format the gird and colour a row if it does not match a certain criteria.

My problem comes, that when I click the add button and the Dialog box opens I cannot do the same.  I have the data in my grid, which the add button is pulling the data in for me, but I cannot for the life of me see where to be able to manipulate the rows or columns in the grid that is displayed in the dialog box.

Any help would be great thanks.

//Add button code from my DskLdnMorningCheckGrid.ts page
        protected addButtonClick() {

            this.editItem(<Serene.Deskside.IntachangeStarterRow>{
                IntachangeList: Serene.Deskside.IntachangeStarterRow.getLookup().items.map(x => {
                    return <Serene.Deskside.IntachangeStarterRow>{
                        FullName: x.FullName,
                        Class: x.Class,
                        Company: x.Company,
                        StartDate: x.StartDate,
                        UserAccountSetup: x.UserAccountSetup,
                        DeskSetup: x.DeskSetup,
                        PcSetup: x.PcSetup
                    }
                })
            });

//my dialog code
    @Serenity.Decorators.registerClass()

    export class DskLdnMorningCheckDialog extends Serenity.EntityDialog<DskLdnMorningCheckRow, any> {

        protected getFormKey() { return DskLdnMorningCheckForm.formKey; }

        //protected form = new DskLdnMorningCheckForm(this.idPrefix);
        protected form: DskLdnMorningCheckForm;

        constructor() {
            super();
            this.form = new DskLdnMorningCheckForm(this.idPrefix);
        }

//I have tried to get details from 
      protected getPropertyItems()
      {
         //i can get elements but I cannot set any grid properties
      }

**Comment by Zahar661** [comment]
if I understand you correctly, or is it about masterdetail?
loadEntity(entity: DogovoraRow) {
            super.loadEntity(entity);

            if (this.entity.DogovorStateId == 2) this.form.DogovorStateId.element.addClass("red");
            
        }

**Comment by ga5tan** [comment]
I also guess it's MD. So then manipulate DetailList collection (or whatever is the property name where is the collection of details)

**Comment by ngaggiano** [comment]
Sorry for the late reply back.  Its not MD, as the detail is not changing, the information is there for informative purposes.  So imagine a daily check, we tick off some items, but then we pull data into a table about items not done.  This is oneway readonly list.

I tried the loadEntity method, but when I try to get information from the entity list, so this.entity.IntachangeList[i].FullName for example (in a for loop) it just hangs and gets no information back.

As I say, this works on a grid.ts but I cannot seem to pull that into the dialog for some reason.

I hope this helps explain more what I am trying to do.

**Comment by ga5tan** [comment]
@ngaggiano  sorry, man, not clearer at all. any screenshots?
are you trying to read data from in memory grid or writing data to it, or something completely different?
I;d love to help you but I have no idea anymore what's going on.

**Comment by Zahar661** [comment]
@ngaggiano use foreach

```
protected updateInterface() {
            super.updateInterface();
            if (this.entity.IntachangeList) this.entity.IntachangeList.forEach(x => {
                if (x.StateId == 2) {
                    ....
                }
            })
        }
```

**Comment by ngaggiano** [comment]
Thanks, I will get some screen shots

**Comment by JohnRanger** [comment]
@ngaggiano ,

where are the screenshots? :-)

John

**Comment by ngaggiano** [comment]
Sorry, been away.  The main editor screen is displayed in the first one, and when I click the "New Core Morning Check" button brings data from another table and displays it (IntachangeUsers.png, but I would like where it says 'User Setup', 'Desk Setup' etc to be highlighted in Red.

I pull the main screen from one database table A and the Interchange users from table B

![image](https://user-images.githubusercontent.com/48206388/55338605-fd1fe980-5498-11e9-897b-ed97db0bbb1d.png)

![image](https://user-images.githubusercontent.com/48206388/55338616-01e49d80-5499-11e9-9596-44d390ced4a3.png)

**Comment by ga5tan** [comment]
So you just want to change color of columns?
I think you can CSS it...
there are also some samples of coloring the rows, so u can try it for columns as well.

**Comment by ngaggiano** [comment]
I do, but its based on criteria, if DeskSetup == "No" then Display Red Row, and thats the problem I having on the form.

**Comment by ga5tan** [comment]
The problem is, u just want single cell colored, rather than row?
If that is the case here is sample:

[https://serenity.is/demo/BasicSamples/ConditionalFormatting](url)

**Comment by ngaggiano** [comment]
Sorry, I would like the entire row highlighted,  but that highlight is based on 3 cells criteria.  If the 3 cells are No then display Red.

Thanks

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by ga5tan** [comment]
I don't understand. In formatting callback u have whole row at your disposal. Just use logical AND and add as many conditions as u like

**Comment by nathanealg** [comment]
I have done that, hence why the dialog is showing the 3 rows with all No cells.  The bit I cannot do is to format these rows to be highlighted in red in the dialog box.

**Comment by stixoffire** [comment]
Perhaps in the form.cs , or on the xyzrow a custom formatter ?

**Comment by ga5tan** [comment]
omg, are you talking about in-memory grid of master/detail ?

good luck with that. It should be possible though, I guess it's still slickGrid.
there were some attempts (AFAIKsuccessful) to do sorting and filtering on it, so I guess it may not be SG...
anyway, I would check those and maybe u can get some inspiration from there?

**Comment by ngaggiano** [comment]
I believe so yes.

I came to that conclusion as well when trying to do it.  Hence I wondered if anyone has managed it.

Cool will take a look at slickGrid and see if anything.

Thanks everyone.
