### ISSUE TITLE
'Enumarable is not defined' client error after update (Saltarelle edition)

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#4323]
Hello.
After update Serenity framework I have the following issue: in many UI controls where collection exists there is 'Enumarable is not defined' error.
Could you please advise how it can be resolved in a better solution?
P.S.: Client code completely uses Saltarelle, TypeScript doesn't match our project needs.
Thank you in advance.

**Comment by volkanceylan** [comment]
We no longer support Saltaralle, either don't update Serenity and continue to use older version, or switch to TypeScript.
