### ISSUE TITLE
PDF generator returned error code 255

### ISSUE THREAD

**Issue by Daffyydd** [volkanceylan/Serenity#4325]
Hi All

I am trying to deploy my system in AWS window server 2012 and everything is running perfect until i try to generate a PDF report. I have tried following solution in [https://github.com/volkanceylan/Serenity/issues/1143](url) but still facing the same error below 

> [InvalidOperationException: PDF generator returned error code 255!]    Serenity.Reporting.HtmlToPdfConverter.Execute() in C:\Projects\StartSharp\Serenity\Serenity.Web\Reporting\Tools\HtmlToPdfConverter.cs:162    SIMS.ReportController.RenderAsPdf(IReport report, String key, String opt) +1148    SIMS.ReportController.Execute(String key, String opt, String ext, Boolean download, Boolean printing) +1013    SIMS.ReportController.Render(String key, String opt, String ext, Nullable`1 print) +204    lambda_method(Closure , ControllerBase , Object[] ) +304    System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +209    System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35    System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39    System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +77    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +30    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +188    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +602    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128
--

I have given read/write permission to IUSR and IIS_IUSR to the entire folder but still getting the error.

The system is working on my development environment with Windows 10

Is there something i need to do or missing

**Comment by teafmartins** [comment]
@Daffyydd Did you find the solution?
