### ISSUE TITLE
NavigationLink to external website

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#4328]
Hello
Feel like i am missing something simple here:
I just want to create a navigation link in the side menu that once clicked will take the user to an external website in a new tab. for example www.nba.com.

**Comment by edwardch** [comment]
Check the link to the error log navigation link in [AdministrationNavigation.cs
](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Administration/AdministrationNavigation.cs)

For your case replace "~/errorlog.axd" with your whole url and remove the permission. Keep Target = "_blank" in there so it opens in a new tab.

**Comment by Zahar661** [comment]
[assembly: NavigationLink(20, "NBA", "http://www.nba.com","*", icon: null, Target="_blank")]

**Comment by Zahar661** [comment]
[assembly: NavigationLink(20, "NBA", "http://www.nba.com","*", icon: null, Target="_blank")]

**Comment by shakazulu89** [comment]
hehe i was so close, i had this:

[assembly: NavigationLink(3400, path: "NBA/NBA Site", url: "https://www.nba.com", permission: DynaHub.Administration.PermissionKeys.Security, icon: "icon-dynadox_form", Target = "_blank")]

just removed "path:" 👍 
thanks guys
