### ISSUE TITLE
How to insert a record when user login to application

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4329]
Hello everyone..

I have a table called 'EmployeeLogin' with columns(login,logout,.....etc) 
here when emloyee signed in  to our application, Immediately i want to insert record with current sysdate and time as login into 'EmployeeLogin' table 
and similarily for logout also.............

so where is the right place to add that logic ??
is there any approach??

**Comment by oha-li** [comment]
You could easily add this by modifying AccountPage.cs (Login/Signout).

**Comment by flextrio-gandhi** [comment]
Thanks @oha-li
