### ISSUE TITLE
Feature request: Implement template as a Single Page Application (SPA)

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#433]
The area that changes is within the content-wrapper div; main-header, main-sidebar, mainfooter etc. remain the same. Ideally navigation links would update that div instead of causing a full page load.

Tall order, I know. There are some javascript tricks to intercept the call which lets the URL change (giving you deep linking ability) without causing a full refresh. Anyways, that would give a nicer user experience and potentially less network traffic.

**Comment by jsbUSMC** [comment]
Could it be done by simply using AngularUI Router to essentially "wrap" the pages? Then convert all `href="..."` to `sref`?

**Comment by volkanceylan** [comment]
It could be possible. As all scripts are cached, there is not actually much resources loading between pages. Only navigation menu is loading alongside page. It might be extracted to a per user cached dynamic script. 

One problem is increased possibility JS memory holes.

And need a way to know when a full page load is required. Something changes, e.g. permissions.

**Comment by wldkrd1** [comment]
Yes, the AngularUI Router was the kind of behavior I was thinking of. As for knowing when a full page load is required...that's a great use case for websockets/SignalR, but that has server requirements you may not want to put into the general template.

**Comment by volkanceylan** [comment]
Websockets might be possible. Yes Signalr dependency could be much, though i don't have experience with it. Anyway i was thinking about changes that not even server aware of yet, e.g. direct SQL update in repository that didn't trigger an event. For others, push notify is the way to go.

**Comment by wldkrd1** [comment]
SignalR is excellent, except for its dependency on jQuery...that pretty much kills its use for consuming with mobile. Now, with the 3.5MB footprint of the Serenity template, you aren't really targeting mobile so that's probably not a huge concern. <br /><br />

As for dealing with changes that the server is not aware of, easiest way to handle that is with a timed pull from client to server for any updates. Could use websockets/SignalR to handle that, or just a regular webservice call.

**Comment by volkanceylan** [comment]
This goes into todo list.
