### ISSUE TITLE
How to exclude a field on a form during a SaveRequest?

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#4331]
Hi there,

So I am working on an `ObjectDialog.ts` that uses an `ObjectForm.cs` in order to determine what fields are shown. I've added a few field that do not correlate to the row class of the object, which are used to show some temporary data to help the user make a choice (its a dropdown, a custom grid that uses table-less row objects, and a textbox for duration between two dates). I've decided to change`CheckNames=false` in `ObjectForm.cs` so that Serenity would stop complaining about these fields, however, when I press save or update, it shows an error saying `Could not find field '*Field Name*' on row of type '*Row Name*'`. Is there an attribute or something that would allow these fields to exist without interfering with SaveRequests? I've already tried NotMapped, however that doesn't seem to work. Thanks in advance.

Best Regards,
Marcus Orciuch

**Comment by volkanceylan** [comment]
[OneWay]

**Comment by MarcusOy** [comment]
Thanks, this worked.
