### ISSUE TITLE
multi column sort

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#4333]
Hi all

Is there a way to multi column sort the grids? for example by date then by name...

Thanks!

**Comment by edwardch** [comment]
Click on "Date" column, then hold shift and click on "Name" column.

**Comment by shakazulu89** [comment]
o
m
g 
... mind ... blown! 
😝

**Comment by shakazulu89** [comment]
.. i tried ctrl before haha

**Comment by edwardch** [comment]
If you use the Favorite Views mixin you can do your multi column sort and then save that as a favorite for later. Pretty cool stuff!
