### ISSUE TITLE
Create Terms & Condition Agreement Check Box When Save

### ISSUE THREAD

**Issue by wildanmuhlis2** [volkanceylan/Serenity#4334]
Any idea how to make Terms & Condition Check Box Button in Custom Dialog?

![image](https://user-images.githubusercontent.com/11847279/54400740-e9356300-46f6-11e9-8d7b-5b05d34ed537.png)

What editor best match for this requirement?

Form.cs

```
    [FormScript("Procurement.F5_TnC")]
    public class F5_TnCForm
    {
        [StaticTextBlock(HideLabel = true, IsHtml = true)]
        public String TnCDescription { get; set; }

        public Boolean TnCAgree { get; set; }
    }
```

**Comment by edwardch** [comment]
Why not just have a Boolean with [DisplayName("Saya Mengerti & Setuju...")] and have this.form.TnCAgree.change(() =>{ custom code here });
