### ISSUE TITLE
How to give different permissions to different dialog which uses same row

### ISSUE THREAD

**Issue by amabndr** [volkanceylan/Serenity#4338]
Hi. How to give different permissions to different dialog which uses same row?for a eg If we have userprofile panel and users grid which both use UsersRow ,I want to hide userprofile navigation for Admin role users and show userprofile navigation link to User role users.Thanks

**Comment by Junariz** [comment]
How about :
Simply define secoundry row, repository and endpoint for the same database table, and give the another permission different from the first definition.

If you want to use sergen for create second endpoint, you would create updatable view for original table, and use sergen to view.

Note:
"admin" was probably given all of permission in PermissionService.cs#HasPermission method in your project, you would be modify there , or use an other acount for customized permission.
