### ISSUE TITLE
Creating a simple profile.

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#434]
So I would like to link my users table to a table named employee, I'm not fully sure how to do this and was wondering if anyone had some incite about a possible solution. Also, is there a way that I can set it to where the current logged in 'employee' can only see and edit their profile and not see others profile unless they are an admin?

Sorry for yet another question.

**Comment by samdubey** [comment]
Create another table called Employee
Map UserId as foreign key

**Comment by wdhodges** [comment]
Do these automatically match up?

**Comment by volkanceylan** [comment]
Employee should have UserId on it or User should have EmployeeId.

Than you should make a screen like change password etc. update users employee.

**Comment by wdhodges** [comment]
I could just add that to the add user dialogue screen is what I was
thinking. How can I I go about setting it up where only a certain user can
see their own information (e.g. certifications)? Still new at all of this
lol

**Comment by volkanceylan** [comment]
You shouldnt give them user grid or user dialog. Do something like change password page. It will be easier to add required fields to user table right.

**Comment by wdhodges** [comment]
Okay I think I understand, how ever if I do it like that wont I have to create the user in the user table and then go and create it again in the employee table? Also, do you have an example of what a query would look like to only pull the employee/user's certifications form the database and put it into a CertificationsRow.cs? I'm trying to wrap my head around it but for some reason it's just not working out for me right now.

**Comment by wdhodges** [comment]
Also how can I get the UserID for the user that is currently logged in?

**Comment by volkanceylan** [comment]
Authorization.UserId

**Comment by jsbUSMC** [comment]
To expand upon @volkanceylan response, I found that when I implemented some code to pull the currently logged in user's UserId, I had to do this:

```cs
// Example code implemented in EntityRepository.cs
private class MySaveHandler : SaveRequestHandler<MyRow>
{
    protected override void SetInternalFields()
    {
        base.SetInternalFields();

        if (IsCreate)
            Row.Analyst = ((UserDefinition) Authorization.UserDefinition).UserId;
    }
} 
```

Visual Studio barfed when I tried to assign `Row.Analyst = Authorization.UserId;`, I ended up having to cast the Authorization.UserDefinition as a UserDefinition object, and call the UserId property from that object. I think the specific error was that `VS can't assign an object of type 'int' to property of type 'stringfield'`. I may be wrong about the specific error, but this was the workaround that worked.

**Comment by volkanceylan** [comment]
Serenity.Authorization.UserId is a string to support different kinds of ID values people might have. For example ASP.NET membership was using Guid. You can simply use Convert.ToInt32() etc, or ToId32().

Serenity.IUserDefinition is an interface, again to support different types of environments. So you get a IUserDefinition from Serenity.Authorization.UserDefinition

In Serene, this interface is implemented by UserDefinition class, which is local to Serene. That's why you cast and integer get UserId from there.
