### ISSUE TITLE
How to move the Slickgrid Pager to the middle?

### ISSUE THREAD

**Issue by galemos** [volkanceylan/Serenity#4341]
The Slickgrid Pager Default position is  to the left, how do i change it? I want it in the middle

![Screenshot_93](https://user-images.githubusercontent.com/28990292/54559099-fe7feb00-499d-11e9-8605-721b0721dcf6.jpg)

**Comment by ga5tan** [comment]
Try to use CSS.
div containing navigation class is ".slick-pg-in"
float: right puts it to center, sort of, but does not look good on smaller screen.
