### ISSUE TITLE
QuickFilter on both date and time range

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#4344]
Is it possible to filter on both date and time?

![image](https://user-images.githubusercontent.com/17013052/54570642-49edc580-49ad-11e9-98b7-19143fb1fc2b.png)

I thought that using DateTimeEditor in column class would allow me to do this:

        [DateTimeEditor, DateTimeFormatter(DisplayFormat = "MM/dd/yyyy HH:mm")]
        public DateTime ReceiptDate { get; set; }

Unfortunately, the quick filter only allows to select date and not the time:

![image](https://user-images.githubusercontent.com/17013052/54570755-b8328800-49ad-11e9-98cc-c2f5a502d9ed.png)

Many thanks in advance for help with this.

**Comment by ShahzanSyed** [comment]
Try this [https://github.com/volkanceylan/Serenity/issues/4369](url)

**Comment by ShahzanSyed** [comment]
#4369

**Comment by ShahzanSyed** [comment]
#How to use QuickFilter to search for a list of items #4369

**Comment by volkanceylan** [comment]
See quick filter customization sample in demo and take freight between as a sample to use datetime editor if you like.
