### ISSUE TITLE
Dynamic Navigation Items based on User Access

### ISSUE THREAD

**Issue by glenngsanchez** [volkanceylan/Serenity#4346]
Hi,

I created a dynamic navigation based on user profile where Companies are accessible based on permission given to user.  This is how my code looks like.

```
[assembly: NavigationMenu(1, "CompanyView", icon: "fa-dashboard")]

public class CompanyViewNavigation :INavigationItemSource {
 public List<NavigationItemAttribute> GetItems() {
   var items = new List<NavigationItemAttribute>();
   var c = VUserCompaniesRow.Fields;
   using (var connection = SqlConnections.NewByKey("Default")) {
     var _coys= connection.List<VUserCompaniesRow>(
                b.UserId == Convert.ToInt32(Authorization.UserId));
    
    foreach (var co in _coys) {
        items.Add(new NavigationLinkAttribute(
                        co.CompanyId ?? 1,
                        path: "CompanyView/" + co.CompanyName,
                        url: string.Format("~/view/?coid={0}&coname={1}", co.CompanyId, co.CompanyName),
                        permission: PermissionKeys.CompanyView,
                        icon: "fa-area-chart"
       ));
   }
  return items;
 }
}
```

I don't have problem displaying companies on the navigation, but the problem is during multiple users login to the Web app.  

e.g. steps using two computers: 

1. PC 1 admin logs in and can view all companies (4 companies)
2. PC 2 standard user logs in and can view only 1 company
3. when going back to PC 1 and refresh admin session page, it's now displaying 1 company (exacty same as standard user)

Can anyone please help and tell me whats going on here?

Thanks for the help.

**Comment by JohnRanger** [comment]
@glenngsanchez 
(1) Are you logged on on the two Computers with the same windows domain user?
(2) If yes - do you have the browser's cache redirected to a network share (or some realtime sync of the user's roaming profile to a network share)?
(3) if (2) = yes: Then that's the problem --> Log on on the Admin's PC with a different windows user than that on the user's computer.

If (2) and (3) = no: Then i.m.h.o. it is impossible that the user's session should have any influence on the admin's session as the two sessions are completely separate from each other and they even don't know from each other within the Serenity Framework.

Let us know a bit more - and how it turns out.
 
With kind regards,

John

**Comment by glenngsanchez** [comment]
Hi @JohnRanger ,

Thanks for the prompt reply. so my answer is 2 & 3 is NO.  I even ask few people to replicate and they also encountered this issue.

> If (2) and (3) = no: Then i.m.h.o. it is impossible that the user's session should have any influence on the admin's session as the two sessions are completely separate from each other and they even don't know from each other within the Serenity Framework.

This is what I understand as well. I even tried to debug from server side and when doing my Step#3, the app doesn't re-query the menu items to display as expcted, and yet seems to load the items from last user login.

Could it be something to do with caching conflict?

**Comment by glenngsanchez** [comment]
Update: Somehow the constructor failed to detect the difference between the Authorization.UserId used by the two users, thus second call gives the result of the first call.

```
public NavigationModel()
{
      Items = TwoLevelCache.GetLocalStoreOnly("LeftNavigationModel:NavigationItems:" + (Authorization.UserId ?? "-1"), TimeSpan.Zero,
              UserPermissionRow.Fields.GenerationKey, () =>
               NavigationHelper.GetNavigationItems(x => 
                x != null && x.StartsWith("~/") ? VirtualPathUtility.ToAbsolute(x) : x));         
      SetActivePath();
}
```

**Comment by fletcherg** [comment]
Hi @glenngsanchez I just wanted to say thanks for your efforts, I am trying to do the same thing and seeing something similar :(

**Comment by glenngsanchez** [comment]
Hi @fletcherg ,

That fixed my issue. thanks for the help!
