### ISSUE TITLE
stored Procedure in Editor

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4347]
How to call the stored procedure in editor

**Comment by JohnRanger** [comment]
Hi @Shraddha996 

As xyzEditor.ts is client-side, you can't directly call a SQL stored procedure from there. But you **_can_** create an endpoint within xyzEndpoint.cs ()or even a completely separate MVC Controller and there put your code to call your SQL stored procedure (something with Connection.Execute("<your SQL command to execute your SP>")).

And then from the client-side (your xyzEditor.ts) you call this endpoint (on client-side, use xyzService.<yourEndpoint> to call the endpoint within your xyzEndpoint.cs (or a direct URL ajax call - see the link below for details).

As a hint how to do the client-side to server-side call, have a look in the following Wiki: https://github.com/volkanceylan/Serenity/wiki/BBB:-On-client-side,-fetching-a-value-from-server-side-out-of-database

Hope this helps.

With kind regards,

John

**Comment by Shraddha996** [comment]
@JohnRanger thanks!
