### ISSUE TITLE
The type or namespace name 'RowIndexFormatter' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by absaakash** [volkanceylan/Serenity#435]
Hello Volkan ceylan

1. Added the following in XXXXGrid.cs of Script Projet

    public class RowIndexFormatter : ISlickFormatter
    {
        public string Format(SlickFormatterContext ctx)
        {
            return (ctx.Row + 1).ToString();
        }
    }

Then Build the Script Project, Transform All T4 Templates, and added the following in XXXXColumn.cs of the WEB project

        [RowIndexFormatter, EditLink]
        public int RowIndex { get; set; }

it fails ro recognise this.

Any thing missed ? 

Thanks in advance

**Comment by volkanceylan** [comment]
Fails recognizing what, it doesn't have RowIndexFormatter server side, or it fails on client side?

Show full code to your formatter .cs and make sure you build script project before transforming.

And check namespace, and its not a nested class.

**Comment by absaakash** [comment]
WOW!

You do have some 6th sense, great your last statement carried the solution for me.

And check namespace, **and its not a nested class**. 

This was the problem with me, i nested the class. (too bad on me)

Thank you Volkan
