### ISSUE TITLE
readonly radiobutton on details grid

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4350]
Hello, everyone
I want help to set the read-only property to radio buttons on my details grid on some condition like, only while updating record
I also find the code for disabling the whole grid/Editor
`Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);`
and apply this
But, then the whole form is set as read-only and the main element which I want to set as read-only they are not able to set
![Capture11](https://user-images.githubusercontent.com/39983941/54737869-d54a9f00-4bd7-11e9-8bc0-0c09eec09d10.PNG)

You can see in this image I want to set read-only to radio button from the first grid
any help would be appreciated

with kind and regards,
shraddha

**Comment by luongnv6** [comment]
```
Serenity.EditorUtils.setReadonly(this.form.RadioControl, true);

**Comment by fwd079** [comment]
> ```
> Serenity.EditorUtils.setReadonly(this.form.RadioControl, true);
> ```
> 
> this.form.RadioControl is a field on form

Just to let everyone know. This does not work for `Serenity.RadioButtonEditor` control, you can still click it.

Regards.

**Comment by fwd079** [comment]
Hi again

This workaround for radio buttons however, works:

```typescript
let propertyName: string = "NameOfPropertyInForm"
            let radioElement: JQuery = $("[id$='" + propertyName + "']").find("input");
            radioElement.prop("disabled", true);
```

Regards.

**Comment by DevAdrian02** [comment]
did not manage to make a radiobutton, does anyone know how to create it?
