### ISSUE TITLE
another Draggable Grouping small issue (visible in DEMO)

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4352]
This can be reproduced using Demo.

Advanced Samples\Grids\Drag and Drop Grouping
Then group using CustomerName for example.
Once grouped, clicking on the Groupname raises a convert error as displayed in screenshot.

![image](https://user-images.githubusercontent.com/31513956/54843963-f2fe2e00-4cd5-11e9-9a01-609182e0f307.png)

**Comment by volkanceylan** [comment]
Yes thats expected as group row doesnt have a valid ID. Formatter shouldnt create a link though.
