### ISSUE TITLE
Editor filter want to show only "Open" status

### ISSUE THREAD

**Issue by Takecarecom** [volkanceylan/Serenity#4353]
![image](https://user-images.githubusercontent.com/13514630/54876881-f4506780-4e49-11e9-9748-9a80d5e4bbdf.png)

from editor
![image](https://user-images.githubusercontent.com/13514630/54876889-134ef980-4e4a-11e9-95ad-b1a71a411a10.png)

Where do you need to enter the conditions?

**Comment by ga5tan** [comment]
maybe getItems() ?

**Comment by edwardch** [comment]
Or create a custom lookup... See the docs for [Handling Lookup Scripts](https://serenity.is/docs/tutorials/multi_tenancy/handling_lookup_scripts)

Your criteria would be something like 
```cs
.Where(new Criteria(fld.InvoiceStatus) = "Open");
```
