### ISSUE TITLE
Join table between databases

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#4355]
Hi all!

Is there an out-of-the-box method to join table from two or more different databases?

Some like [this](https://stackoverflow.com/questions/5698378/join-between-tables-in-two-different-databases)

Now I have try with a workaround but I want avoid to hardcode the database and table name

```c#
ForeignKey("[MySecondDatabase].[dbo].[MyTable]", "ID"), LeftJoin("jMyJoin")]
```

I try also with TableName on Row
```c#
[TableName("[MySecondDatabase].[dbo].[MyTable]")] 
```
and 
```c#
[ForeignKey(typeof(MyRow), "ID"), LeftJoin("jMyJoin")]
```
and it works, but the database name is hardcoded. I want to get It from connection string indicated by ConnectionKey attribute

If there isn't I try to implement it in FrorignKey attribute

**Comment by kilroyFR** [comment]
I am doing multi database requests using Oracle Database Link feature.
ConnectString is always same on all my objects. Database Links resolves the "remote" objects transparently (they could be local, remote, it works).
I have database link on tables (to access remote tables) + public synonyms on schema tables/views.
This way i dont have to prefix tablename (that is necessarily hardcoded) with owner of the object.

All my object are defined with their name. DBLink resolution is done transparently.

**Comment by volkanceylan** [comment]
You can use [YourConnecitonKey^].sometable

**Comment by Estrusco** [comment]
Wow, very good! Thank you @volkanceylan !

Thank you too @kilroyFR for your time :)
