### ISSUE TITLE
Change field labels from the left to the right

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4357]
![serenity arabic problemm](https://user-images.githubusercontent.com/28954016/55015841-46ce8700-4ff6-11e9-8688-f7c7e20c95e2.png)
Any ideas how to make this happens ?????????
Thanks

**Comment by hubeyb** [comment]
You can simply make with css override. There is no attribute to achive you wanted.

**Comment by tonysader** [comment]
Where to do this ?

**Comment by hubeyb** [comment]
You can write your own less code if you know to write css (serenity uses less technology, write less code in Content/site/site.less file, and it converts auto to css code).  I use "!important" css tag to override. I you do not have any idea about less or css, please ask anyone who know css (or less).
