### ISSUE TITLE
How to save enum text not value

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#436]
Dear All,

I have this enum

 [EnumKey("XL.ACDC")]
    public enum ACDC
    {
        [Description("AC")]
        AC = 0,
        [Description("DC")]
        DC = 1,
    }

How to save ACDC column with text AC or DC not int value?

**Comment by volkanceylan** [comment]
Don't use enums for this. Use a StringField, write a custom select editor, deriving from SelectEditor, add your items using AddItem("AC", "AC") etc. then use it.

```cs
    [Editor]
    public class XYZEditor : Select2Editor<object, object>
    {
        public XYZEditor(jQueryObject hidden)
            : base(hidden, null)
        {
            AddItem("AC", "AC");
            AddItem("DC", "DC");
        }
    }
```

**Comment by rudianto2008** [comment]
Works perfectly.

Thanks

**Comment by jadsouza** [comment]
Hi 
I created the above example but I just fail to understand how to implement it. Please help

**Comment by jadsouza** [comment]
and to add to my earlier question, where do i create custom editor ?

**Comment by jadsouza** [comment]
Hi 
I managed to write the code. Following is my implemetation

namespace OrchestrationAdmin.Common
{

    [Editor]
    public class EnabledFlagEditor:Select2Editor<object,object>

    {
        public EnabledFlagEditor(jQueryObject hidden)
           : base(hidden, null)
        {
            AddItem("Enabled", "Y");
            AddItem("Disabled", "N");
        }
    }

I executed the T4 templates successfully. However when i run the web app it gives me the following error

**An exception of type 'System.Reflection.ReflectionTypeLoadException' occurred in OrchestrationAdmin.Web.dll but was not handled in user code

Additional information: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.**

What am I doing wrong ?

**Comment by volkanceylan** [comment]
Cleanup bin, some dll cant be loaded, build and try again

**Comment by jadsouza** [comment]
Will try that. On another note. You have done a fantastic job on this framework.

**Comment by volkanceylan** [comment]
Thanks a lot. Also check copy local is true for references. Unfortunately that message doesnt show which DLL cant be loaded.

**Comment by jadsouza** [comment]
I did a clean up of the bin folder and that error was gone. However it has come up with something new. I keep getting this window pop to open a file MigrationRunner.cs

**Comment by volkanceylan** [comment]
This time its about FluentMigrator or LocalDB. It should show exception if you continue running. Also see event log, and make sure copy local is true for all refs.
