### ISSUE TITLE
Currency symbol in DisplayFormat

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#4362]
Anyone know how to get a currency symbol in front of a decimal value? I tried these but doesn't work.

[DisplayFormat("$##,##0.00")]
[DisplayFormat("$ ##,##0.00")]
[DisplayFormat("\\$##,##0.00")]
[DisplayFormat("\\$ ##,##0.00")]
[DisplayFormat(\@"\\$##,##0.00")]

Ideally, I would like the column to display the values with the $ left aligned and the value right aligned:

$   1.25
$ 34.12

Any thoughts?

ref: https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings
ref: https://volkanceylan.gitbooks.io/serenity-guide/attributes/attributes.html

**Comment by volkanceylan** [comment]
You would need a custom formatter, dispay formats in JS doesnt support extra chars atm

**Comment by brunobola** [comment]
https://stackoverflow.com/questions/149055/how-can-i-format-numbers-as-dollars-currency-string-in-javascript

**Comment by stixoffire** [comment]
@VR-Architect I do a simple string replace, html encode in my typescript file.

CurrencyFormatter.ts
namespace YourNameSpace.Namespace {

    @Serenity.Decorators.registerFormatter([Serenity.ISlickFormatter, Serenity.IInitializeColumn])
    export class CurrencyFormatter implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {
            // var text = Q.htmlEncode(ctx.value);
            if (ctx.value == null) ctx.value = 0.00;
            var text = Q.htmlEncode("$ " + Q.formatNumber(ctx.value, "#,###.00"));

            return text;

        }

       @Serenity.Decorators.option()
        public contractAmount: string;

        public initializeColumn(column: Slick.Column) {
            column.referencedFields = column.referencedFields || [];
            if (this.contractAmount)
                column.referencedFields.push(this.contractAmount);
        }
    }
}
