### ISSUE TITLE
Hide dialog category based on permission

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#4363]
Hi all
Couldnt find anything about this. Is there an option to hide a form category based on permission? 
I have a situation for example where i have a field inside the form dialog. but if a user doesnt have permission to view this field the category above it is still visible, with no fields under it. looks kinda weird and also shows the user he is not seeing something.
Is there any way to hide categories based on permission or any other conditional?
Thanks

**Comment by Estrusco** [comment]
```ts
    if (!Q.Authorization.hasPermission("yourPermissionKey)) {        
        this.form.SomeFieldInCategory.element.closest('.category').toggle(false);
    }
```

**Comment by shakazulu89** [comment]
perfecto!
