### ISSUE TITLE
Details Dialog Save button event

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4364]
I want to get save button click event in TS, Where button present on Details Dialog.
How can I ?

**Comment by minhhungit** [comment]
check this @TechAspirant  https://github.com/volkanceylan/Serenity/issues/814#issuecomment-363510483

it might help you

**Comment by vinaykulkarni89** [comment]
If you want to perform anything on save event you can check with onSaveSuccess()
