### ISSUE TITLE
How to make Memory grid only based on user permissions

### ISSUE THREAD

**Issue by Daffyydd** [volkanceylan/Serenity#4366]
Dear All,

I have a form with 2 different memory grids. 

I have to restrict editing based on user permissions.  I have managed to set all fields to Read-only based on user permission but Add button in the memory grid is enabled and edit link in the grid opens in edit mode enabling the user to update the grid it as much as he cannot update the record.

If all the elements in the form are read-only,

1. How can I disable the Add button on the grid? 

2. How can I restrict memory grid Edit dialog to ready-only too?

Thank you

**Comment by in32bit** [comment]
1. In your Grid.ts

```
        constructor(container: JQuery) {
            super(container);

            if (!Authorization.hasPermission("Administration:Security")) {
                $(".add-button").remove();
            }
        }
```

2. in your dialog.ts

```
loadEntity(entity: YourRow) {
            super.loadEntity(entity);

            if (!Authorization.hasPermission("Administration:Security")) {

                var user = Authorization.userDefinition;

                    $(".s-DialogToolbar").hide();
                    Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);
                }
            }
        }
```

**Comment by Daffyydd** [comment]
Thanks, @in32bit  for your guidance. At least the Add button is  gone. However, the link in the memory grid is active and when clicked, it opens editable dialog. How can i make the records in the memory grid read only?

**Comment by Daffyydd** [comment]
I have managed to create readonly based on @JohnRanger in #4343. Thanks
