### ISSUE TITLE
RDLC REPORT IN SERENITY

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4368]
hello, Everyone and @volkanceylan 
what is the simple way to create a report in serenity using RDLC  I also refer #3980 But couldn't reach to end

Thanks and regards,

**Comment by volkanceylan** [comment]
There is enough info in that issue

**Comment by Shraddha996** [comment]
hey @volkanceylan First of all thanks for this great platform
Actually, am stuck in my report, there is a minor issue
![Capture12](https://user-images.githubusercontent.com/39983941/55538000-08625780-56db-11e9-97f2-ac0357d65a57.PNG)
I just want to fix this and design like a normal initial page of other forms

here's my code of cshtml file
`@using ReportViewerForMvc
@{
    ViewData["Title"] = "ReportViewer";
}


<div class="box box-primary" id="boxId" style="height:1000px">
    <div class="box-body">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)
    </div>
</div>


`
