### ISSUE TITLE
if i can change the web config file is getting error from localdb to localhost of that in our local server

### ISSUE THREAD

**Issue by pgksunilkumar** [volkanceylan/Serenity#437]

**Comment by volkanceylan** [comment]
If your local server is SqlExpress then it should be .\SqlExpress. If you have a full SQL server in local machine then it might be localhost. Otherwise type name of machine, not localhost.

**Comment by pgksunilkumar** [comment]
thanks  volkanceylan,

me as a code of web config this is also working ,but i want if i can host in godaddy or any web serivices what we do

 <add name="Default" connectionString="server=localhost; Initial Catalog=Serene1_Default_v1; User ID=sa;Password=admin123; Integrated Security=True;"  providerName="System.Data.SqlClient"/>
  <add name="Northwind" connectionString="server=localhost; Initial Catalog=Serene1_Northwind_v1; User ID=sa;Password=admin123; Integrated Security=True;" providerName="System.Data.SqlClient"/>

**Comment by volkanceylan** [comment]
You set it to Sql server address they give you. This is not right place for these questions really.

**Comment by pgksunilkumar** [comment]
thanks volkanceylan for giving reply 
I don't have your email id can you please share your details to me

**Comment by volkanceylan** [comment]
Man i mean this is not SQL server or .NET general support line ;)
