### ISSUE TITLE
How to get detail entity Id in AfterSave handler on a Master/Detail 

### ISSUE THREAD

**Issue by wchitirobho** [volkanceylan/Serenity#4370]
Hi Guys,

I have a master/detail relation between an invoice(master) and a detail entity (detail). The CRUD work very well for both master and detail entities.

My issue, is that I need to use the detail entity Id after I have saved the master entity(invoice).

The master (Invoice) and detail both have autoIncrement Ids.

Here is a piece of my code in the Save handler of the master repository:
          protected override void AfterSave()
            {
                base.AfterSave();
                    if (Row.OrderItems != null)
                    {
                        foreach (var item in Row.OrderItems)
                        {
                            var purchaseInvoiceItemId = item.PurchaseInvoiceItemId.Value;
         
.....
item.PurchaseInvoiceItemId.Value = null when creating the record, it only has a value when updating.

How can I get the detail entity Id when creating the creating the detail record? or how can I refresh to get the Id.

![How to refresh detail record](https://user-images.githubusercontent.com/5858493/55372471-29238500-5502-11e9-8a0b-2f01d4b9e7c8.png)

**Comment by wchitirobho** [comment]
managed.

**Comment by vinaykulkarni89** [comment]
Hi @wchitirobho can you please share what work around you followed
As we are also facing same issue

**Comment by reach2rv** [comment]
@wchitirobho and @vinaykulkarni89 can you guys please post your solution for this.

**Comment by minhhungit** [comment]
I know we are using Discussion for questions but to avoid people keep asking on this thread I will post the solution here

My solution is quite simple I think, we will re-load child items where child.ParentId = Row.Id (master.ID)

```csharp
protected override void AfterSave()
{
    base.AfterSave();

    var products = this.Connection.List<Entities.OrderProductRow>(new Criteria(Entities.OrderProductRow.Fields.OrderId) == (int)Row.Id);
}
```
