### ISSUE TITLE
Installation error while installing StartSharp_v3.9.5.1 VSIX with Visual Studio Enterprise 2017

### ISSUE THREAD

**Issue by ryasin** [volkanceylan/Serenity#4371]
4/2/2019 4:55:18 PM - Microsoft VSIX Installer
4/2/2019 4:55:18 PM - -------------------------------------------
4/2/2019 4:55:18 PM - Initializing Install...
4/2/2019 4:55:19 PM - Extension Details...
4/2/2019 4:55:19 PM - 	Identifier      : StartSharp_SerenityApplicationTemplate
4/2/2019 4:55:19 PM - 	Name            : StartSharp
4/2/2019 4:55:19 PM - 	Author          : Volkan Ceylan
4/2/2019 4:55:19 PM - 	Version         : 3.9.5.1
4/2/2019 4:55:19 PM - 	Description     : Serenity is an ASP.NET MVC / TypeScript application platform designed to simplify and shorten development of data-centric business applications with a service based architecture. 
    StartSharp is a starter template to build Serenity applications.
4/2/2019 4:55:19 PM - 	Locale          : en-US
4/2/2019 4:55:19 PM - 	MoreInfoURL     : https://github.com/volkanceylan/Serenity
4/2/2019 4:55:19 PM - 	InstalledByMSI  : False
4/2/2019 4:55:19 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
4/2/2019 4:55:19 PM - 
4/2/2019 4:55:19 PM - 	Supported Products : 
4/2/2019 4:55:19 PM - 		Microsoft.VisualStudio.Community
4/2/2019 4:55:19 PM - 			Version : [11.0,16.0)
4/2/2019 4:55:19 PM - 		Microsoft.VisualStudio.Pro
4/2/2019 4:55:19 PM - 			Version : [11.0,16.0)
4/2/2019 4:55:19 PM - 		Microsoft.VisualStudio.Enterprise
4/2/2019 4:55:19 PM - 			Version : [11.0,16.0)
4/2/2019 4:55:19 PM - 
4/2/2019 4:55:19 PM - 	References      : 
4/2/2019 4:55:19 PM - 
4/2/2019 4:55:19 PM - Searching for applicable products...
4/2/2019 4:55:19 PM - Found installed product - Global Location
4/2/2019 4:55:19 PM - Found installed product - ssms
4/2/2019 4:55:19 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by volkanceylan** [comment]
Please dont double post, already replied in StartSharp repo.

**Comment by ryasin** [comment]
Thank You Volkan, I raised the issue in serenity first, then i figured that i am facing issue in startsharp, so posted in that. I will close this after the following comment
