### ISSUE TITLE
Active Directory Serenity Core

### ISSUE THREAD

**Issue by Dim-PL** [volkanceylan/Serenity#4372]
Hi 

I am using Serenity Core, Could you please let me know if AD authentication is supported in core?
I have used it successfully in Serenity Dot Net application but its not working with my core application. If its not supported is there any alternate to this.

Thanks

**Comment by ShahzanSyed** [comment]
@Dim-PL could you share your implementation of AD or guide how to implement it in Serenity Dot Net Application.

**Comment by RasaRinkeviciute** [comment]
It does work. You need to add ActiveDirectoryService.cs in Modules/Administration/Authentication/
`using Serenity;
using Serenity.ComponentModel;
using System;
using System.DirectoryServices.AccountManagement;

namespace DimensionsOnline.Administration
{
    public class ActiveDirectoryService : IDirectoryService
    {
        public DirectoryEntry Validate(string username, string password)
        {
            var config = Config.Get<Settings>();
            using (var context = new PrincipalContext(ContextType.Domain, config.Domain))
            {
                bool isValid;
                try
                {
                    isValid = context.ValidateCredentials(username, password, ContextOptions.Negotiate);
                }
                catch (Exception ex)
                {
                    Log.Error("Error authenticating user", ex, this.GetType());
                    return null;
                }

                if (!isValid)
                    return null;

                var identity = UserPrincipal.FindByIdentity(context, IdentityType.SamAccountName, username);
                return new DirectoryEntry
                {
                    Username = identity.SamAccountName,
                    Email = identity.EmailAddress.TrimToNull(),
                    FirstName = identity.GivenName,
                    LastName = identity.Surname
                };
            }
        }

        [Hidden, SettingScope("Application"), SettingKey("ActiveDirectory")]
        private class Settings
        {
            public string Domain { get; set; }
        }
    }
}`

Then add this line in Startup.cs ConfigureServices:
`services.AddSingleton<IDirectoryService, ActiveDirectoryService>();`


Also don't forger to add namespace:
`using ProjectName.Administration;` 

That should do the job.

**Comment by volkanceylan** [comment]
Thanks for sharing.

**Comment by Sevigorr** [comment]
I added a wiki page for this. 

https://github.com/serenity-is/Serenity/wiki/Authenticate-with-Active-Directory-(.Net-Core)

**Comment by LiranBN** [comment]
> I added a wiki page for this.
> 
> https://github.com/serenity-is/Serenity/wiki/Authenticate-with-Active-Directory-(.Net-Core)

I tried to follow this but I get same errors:
It does not recognize SettingScope, SettingKey attribute
and it does not recognize Config.Get<Settings>()
what do I have to do ? is there a package I have to install and reference it ?

**Comment by Sevigorr** [comment]
@LiranBN Are you using the Serenity .Net Core version? Both of those are under the 'Serenity.ComponentModel', so just add it to your usings. 

Everything you need to do is right there in the wiki I created.

**Comment by erehtolleh** [comment]
@LiranBN Most likely you have to inject it.  The newer core uses dependency injections...


```
                //ADSettings.cs 
                public class ADSettings : IOptions<ADSettings>
               {
                        public const string SectionKey = "ADSettings";
                        public ADSettings() {
                            Domain = "xxdomainxxx";
                        }
                        
                        public string Domain { get; set; }
                        public ADSettings Value { get; }
                }
```



```
   //appsettings.json

  "ADSettings": {
    "Domain": "xxxdomainxxx"
  }
```


   
```
//activedirectoryservice.cs
        protected ILogger Log { get; }
        protected IExceptionLogger ExceptionLogger { get; }
        protected ADSettings Config { get; }

        public ActiveDirectoryService(
            IOptions<ADSettings> options,
            ILogger<ActiveDirectoryService> log = null, IExceptionLogger exceptionLog = null)
        {
           
            Config = (options ?? throw new ArgumentNullException(nameof(options))).Value;
            Log = log;
            ExceptionLogger = exceptionLog;
        }

```

**Comment by VictorTomaili** [comment]
Please continue on discussions.

**Comment by LiranBN** [comment]
> @LiranBN Are you using the Serenity .Net Core version? Both of those are under the 'Serenity.ComponentModel', so just add it to your usings.
> 
> Everything you need to do is right there in the wiki I created.

I am using the Serenity .Net Core version but it does not recognize them.

**Comment by nugrahaddict** [comment]
there are 2 type core package with serenity,
1. Serenity.Core
2. Serenity.Net.Core

I think @LiranBN user Serenity.Net.Core but @TravisFinlan use Serenity.Core, is it correct ?
