### ISSUE TITLE
How to enable QuickFilter on a list of strings

### ISSUE THREAD

**Issue by Onyx3910** [volkanceylan/Serenity#4373]
Hi,

I'm attempting to follow this [tutorial](https://volkanceylan.gitbooks.io/serenity-guide/tutorials/movies/filtering_with_multiple_genre_list.html). For some reason, it doesn't appear to work with strings. 

Essentially, I have Invoices with integer ID's acting as primary key. In the same row are string serial numbers. Each invoice can have more than one serial number attached to it. 

The two issues I've found is that: 1. There does not appear to be a LookupEditor for strings - I'm only getting a Serenity_StringEditor. 2. I need to pass in a List<string> via the search bar, but it's just coming through as a basic string. I suspect that issue 1 is the main problem, however.

Please let me know if I can provide any more information.

**Comment by vinaykulkarni89** [comment]
If I have understood you correctly, your problem can be solved if you define a custom lookup editor
