### ISSUE TITLE
QuickSearch : Disable Autosearch

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#4374]
Currently "QuickSearch" starts searching as soon as user type in the box. Is there any way it can be delayed or disabled and fired when user hit enter once typing is complete?

**Comment by DavidKing0193** [comment]
I'm kind of surprised no one's responded to this. You should just need to do this:

```
let columnFilter = Q.first(filters, x => x.field == fld.column);
columnFilter.handler = h => {
    if (h.active) {
        h.request.Criteria = Serenity.Criteria.and(h.request.Criteria,
        [[fld.column], 'like', '%' + h.value + '%']);
    }
};
```

**Comment by XDDDev** [comment]
Thank you @DavidKing0193 for your input. Would you please let us know which function to override to add those lines?

**Comment by DavidKing0193** [comment]
Ah yes, sorry! 

That should go in yout xyzGrid.ts file overriding function: getQuickFilters(). Please let me know if you need further information!

**Comment by XDDDev** [comment]
Thank you @DavidKing0193 for your input. Actually we are looking for QuickSearch, not QuickFilter. They are two different. QuickSearch is in grid, and when user type something in that field, it starts searching immediately on fields which are set for "QuickSearch" (defined in myRows.cs file.

**Comment by DavidKing0193** [comment]
Of course I had to misread that. I'm so sorry to have gotten your hopes up! Based on my research (#1187), it appears that searching by a user defined action isn't possible.

**Comment by XDDDev** [comment]
Dear DavidKing,
Thank you so much for the help, and nothing to be sorry about.
