### ISSUE TITLE
How to hide row based on value

### ISSUE THREAD

**Issue by DavidKing0193** [volkanceylan/Serenity#4376]
Hello!

I'm dealing with a table that's only supposed to list active dealers. Currently, inactive dealers unfortunately show up as well. 

Is it possible to hide a row from being displayed based on a value - in my case, a status of 'inactive'?

Thanks,
David

**Comment by ga5tan** [comment]
yeah
I believe you can open up grid with some filter on, so that it shows only active
or you can do it on repository level and return only active rows (based on user level for example) - what I do

**Comment by DavidKing0193** [comment]
Can you elaborate on how to do it from a repository level? I'm looking at my repository file, but don't see a clear spot to do it at.

**Comment by edwardch** [comment]
Update your list handler inside your DealerRepository file...

```cs
private class MyListHandler : ListRequestHandler<MyRow>
{
	protected override void ApplyFilters(SqlQuery query)
	{
		base.ApplyFilters(query);
		query.Where(new Criteria(DealerRow.Fields.IsActive) == 1);
	}
}
```

**Comment by DavidKing0193** [comment]
@edwardch Thank you so much! I'm relatively new to serenity so it's hard for me to determine when it's applicable to write a Query, or even how through C#. Regardless, it works like a charm!

**Comment by edwardch** [comment]
Cool, glad it worked... 

Since you're new to Serenity, there are loads of examples in the demo/Northwind project that will help you a lot - set up an test project on your machine and go through all of these examples. That made a big difference to me when I started out.

**Comment by DavidKing0193** [comment]
Ah, that's not a bad idea. I definitely would do that if I had the time. I only have a week of development left (minor overhaul of an existing website), so I'm trying to focus on specific features that the end users requested.
