### ISSUE TITLE
Master Detail Issue

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4378]
Hello,

After adding new data in master detail table, data is not available in detail section unless I refresh the page. I want to refresh and load the new data in entity after adding new data.

**Comment by luongnv6** [comment]
//GridEditor.ts

 validateEntity(row: OrderDetailsRow, id) {
            row.ProductId = Q.toId(row.ProductId);

            var sameProduct = Q.tryFirst(this.view.getItems(), x => x.ProductId === row.ProductId);
            if (sameProduct && this.id(sameProduct) !== id) {
                Q.alert('The product is already in the list!');
                return false;
            }

            row.ProductName = Q.getLookup<ProductsRow>("Default.ProductsLookupActive").itemById[row.ProductId].Name;
            var temp = (row.Quantity || 0) * (row.UnitPrice || 0);
            row.LineTotal = temp - (temp * row.Discount / 100);
            return true;
        }
