### ISSUE TITLE
Json field type on Dialog

### ISSUE THREAD

**Issue by jovdej** [volkanceylan/Serenity#4379]
Hi Volkan,
I have a question about Json field. In the MSSQL database, I have a json field type.  I created xyzRow based on the table via sergen. Json serialize/deserialize into xyzModel. How to add xyzModel input fields on the Form(Dialog) from jso? I was wondering what would be the best practice: between manually adding through xyzRow or there is some automated way to generate Forms for xyzModel.

Thank You.

**Comment by kilroyFR** [comment]
You could write a formatter to display json data correctly. I have done this already (but yes, it's only for display)

**Comment by jovdej** [comment]
Hi kilroyFR,
I agree JSON can be formatted and displayed, it is not a problem. My question is whether there is a way to automatically generate a form (dialog) for creating and modifying the JSON string similar to that how sergen creates form from SQL DB Table or I must manually add input fields to an existing dialog generated by sergen.

**Comment by volkanceylan** [comment]
Sorry auto generation for JSON not possible, there is not enough metadata.
