### ISSUE TITLE
Check if a grid column has value

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4381]
HI;
I am struggling to check if entire column A in xxGrid is empty or has value.  Thank you

**Comment by ga5tan** [comment]
check summary or multiselect plugins/mixins, they must be iterating tru whole data set, so you can take code from there

**Comment by ms4hafiz** [comment]
@ga5tan thank you for the hint;

Using following code, i am tyring to count rows with null "reason" but it is not working. 

                   var selected = Expenditure.StagingBudgetRow.idProperty;
            var selectedOutput = 0;
            for (var i = 0; i < selected.length; i++) {
                if (Expenditure.StagingBudgetRow.Fields.Reason === null) {
                    selectedOutput+=1;
                }
            }
            if (selectedOutput==0) {
                buttons[Q.indexOf(buttons, x => x.cssClass == "synchronize-button")].cssClass += " disabled";
            } else {
                buttons[Q.indexOf(buttons, x => x.cssClass == "synchronize-button")].cssClass += " ";
            }
