### ISSUE TITLE
Bootstrap Switch [Help]

### ISSUE THREAD

**Issue by TecnologiaCapricornio** [volkanceylan/Serenity#4382]
Hi everyone,

I've followed  [this wiki](https://github.com/volkanceylan/Serenity/wiki/UI:-Bootstrap-Switch-plugin-(by-marcobisio)) but I get this error:

![image](https://user-images.githubusercontent.com/44982900/55724995-03571e00-59e3-11e9-8d9e-e41595fc377b.png)

It sounds simple but I can't figure it out

**Comment by minhhungit** [comment]
try this:
> (this.element as any).bootstrapSwitch(....

and make sure that you add bootstrapswitch library

**Comment by TecnologiaCapricornio** [comment]
I'm sure I added the NuGet packages, but I don't have this two scripts

```
@Html.Stylesheet("~/Content/bootstrap-switch/bootstrap3/bootstrap-switch.css")

@Html.Script("~/Scripts/bootstrap-switch.js")
```

**Comment by minhhungit** [comment]
if you don't have those file then download and add them by manual
my code is just a "hack" for typescript type validator

**Comment by marcobisio** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bootstrap-switch/index.d.ts

**Comment by judejay** [comment]
I had same error, check the name of the file.
