### ISSUE TITLE
Excel export - Master Detail

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4385]
Hello,

How can I Export Master detail table on button click ?

**Comment by luongnv6** [comment]
Hope can help you

`   public class OrderDetailsColumns
    {
        [EditLink]
        [Width(140)]
        public String ProductName { get; set; }
        [AlignRight]
        public Int32 Quantity { get; set; }
        [AlignRight]
        public Decimal UnitPrice { get; set; }
        [AlignRight]
        public Decimal Discount { get; set; }
    }`

//gridEditor.ts
`protected getButtons(): Serenity.ToolButton[] {
            return [{
                    title: 'Export',
                    cssClass: 'button-export',
                    icon: 'fa-cloud-download',
                    onClick: () => {
                        let _orderDetailsRows: OrderDetailsRow[] = [];
                        this.view.getItems().forEach((v, i) => {
                            _orderDetailsRows.push({ ProductName: v.ProductName, Quantity: v.Quantity, UnitPrice: v.UnitPrice, Discount: v.Discount });
                        });
                        Q.postToService({
                            service: OrderDetailsService.baseUrl + '/OrderDetailExportExcel',
                            request: {
                                orderDetailsRows: _orderDetailsRows,
                            },
                            target: '_blank'
                        });
                    }
                }];
        }`

//EndPoint
`  public FileContentResult OrderDetailExportExcel(IDbConnection connection, ExportExcelRequest request)
        {
            var report = new DynamicDataReport(request.orderDetailsRows, new List<string> { "ProductName", "Quantity", "UnitPrice", "Discount" }, typeof(Columns.OrderDetailsColumns));
            var bytes = new ReportRepository().Render(report);
            return ExcelContentResult.Create(bytes, $"Order Detail.xlsx");
        }`

**Comment by ziaatrix** [comment]
@volkanceylan 

It seems the above is already outdated, on my version of serenity following the above sample is giving me below error. Could you please help me on the below. Thanks.

![image](https://github.com/user-attachments/assets/89fe0858-ec75-4195-a81e-1464268bb7e7)

![image](https://github.com/user-attachments/assets/053c8495-ebdd-450a-b0a7-fb4549505355)

**Comment by ziaatrix** [comment]
@VictorTomaili any idea please? Thanks
