### ISSUE TITLE
"getPersistanceFlags()" not being recognized in Serenity project

### ISSUE THREAD

**Issue by DavidKing0193** [volkanceylan/Serenity#4386]
For my project, I don't want the quick filter information saved. I've tried using the getPersistanceFlags function per this [tutorial](https://serenity.is/Docs/grids/persisting_settings). However, I can't get Serenity to recognize it as a built in function that can be overridden. In the meantime, I've made my own solution (a hack really) to get around the issue. It works fine honestly, but as a programmer, I know hacks aren't exactly maintainable.

So, does anyone have any idea why it's not being recognized? I'm attempting to override the function in one of my xyzGrid.ts files.

**Comment by edwardch** [comment]
Looks like it might be a mistake in the guide... I've never tried to override the persisted settings but I see that you can do it in your grid.ts like this:

```ts
protected gridPersistanceFlags() {
    return {
        columnWidths: false,
        filterItems: false
    }
}
```

**Comment by DavidKing0193** [comment]
Interesting. Well, now that hack is gone and my code is much simpler for it! Thanks again!

**Comment by ckrassas** [comment]
I seem to be seeing this issue in the current version. I am persisting settings to the database. When using either of the two methods mentioned (one in the guide and the one in this post) it just keeps persisting no matter what. 

Any help on this would be greatly appreciated.

Using Serenity Version 3.14
