### ISSUE TITLE
Demo Reports To Grid display

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4387]
hey !

i am looking for something like reporting (https://serenity.is/demo/Northwind/Reports#!2), i mean showing a prompt with Start/End date input + execute button but that would display data in a regular SlickGrid.

On current sample reports it generates an excel document.

Is there any chance to have a simple sample showing to to make this ? (inputs in form and results in a grid).

When i look at SalesByCategory sample code, it looks like it's close to the solution but i cannot find out how to display result in grid.

I would like to prove to my managers i can do this (form + grid display accordingly)

**Comment by Shraddha996** [comment]
@kilroyFR  Actually I also stuck here! 
Do you find any solution for this?
