### ISSUE TITLE
Couldn't read template version from VSGallery when use serin

### ISSUE THREAD

**Issue by jedsada-jed** [volkanceylan/Serenity#4388]
Hello, When i run `serin` by powershell in Windows. I found below.

```
PS E:\Projects\Git\project-serin> serin
Welcome to Serene Initializer!

Reading latest template version from VSGallery...
Couldn't read template version from VSGallery.
```

### My version `node` and `npm`

```
PS E:\Projects\Git\project-serin> node -v
v10.10.0
PS E:\Projects\Git\project-serin> npm -v
6.4.1
```
### My `dotnet core` info

```
PS E:\Projects\Git\project-serin> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.0.0-preview1-005977 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview1-002111-00 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by volkanceylan** [comment]
It's probably about some firewall or network connection issue. It needs to connect to vs marketplace.

**Comment by jedsada-jed** [comment]
Thank you @volkanceylan for your suggestion. But still not work for me.

### **Case 1**:  I disconnect wifi. I get result when run `serin`
![image](https://user-images.githubusercontent.com/21008002/56261002-968b0480-6103-11e9-8eb9-7dc7c3dd419e.png)

### **Case 2**: I connect wifi and turn off firewall.
![image](https://user-images.githubusercontent.com/21008002/56260616-14e6a700-6102-11e9-888e-d0bbfb351c2e.png)

Result when run `serin`
![image](https://user-images.githubusercontent.com/21008002/56260694-6131e700-6102-11e9-8018-9593e30a93ff.png)

### **Case 3**:  I connect wifi and turn on firewall.
![image](https://user-images.githubusercontent.com/21008002/56260727-89214a80-6102-11e9-831e-9f1bf9470ecf.png)

Result when run `serin`
![image](https://user-images.githubusercontent.com/21008002/56260764-aa823680-6102-11e9-9fe5-dc7dd4a363a1.png)

**Comment by volkanceylan** [comment]
OK, seems like they changed the HTML code for visual studio marketplace, have to parse HTML as there is no service to read versions and VSIX url.

please npm update -g serin and try again.

**Comment by jedsada-jed** [comment]
Thanks for the help. I can create project by `serin`. 🙏🙏🙏

**Comment by Raithybabes** [comment]
Hi. This seems to have changed again. There now IS a public API for reading versions and the VSIX url. I have hacked my local serin index.js to get this working. Is there a public repo for the serin npm package that I could contribute the fix to?

**Comment by Raithybabes** [comment]
Hi @volkanceylan , the Marketplace extension info seems to have changed again. There is an extensionquery endpoint which seems to return the info needed. I have created a PR in the Serene project that I hope you will take a look at please.

[Serene PR 61](https://github.com/volkanceylan/Serene/pull/61)
