### ISSUE TITLE
Open calculator on button click

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4389]
Hello,

Is there any way I can open calc.exe from system32 on button click on dialog ?

**Comment by edwardch** [comment]
Sounds dangerous if you could do this. 

Maybe rather prompt the user to open calculator when they click that button.

**Comment by TechAspirant** [comment]
Can we create html and javascript calculator and place in EditorDialog ?

**Comment by edwardch** [comment]
Of course! 

You can build your own (check [Let’s Make A JavaScript Calculator](https://medium.com/@ethanryan/lets-make-a-javascript-calculator-a81186cb912f)) or look around on GitHub. There must be quite a few examples...

**Comment by TechAspirant** [comment]
But how can I Integrate and show in Editor dialog of serenity ?

**Comment by JohnRanger** [comment]
@TechAspirant ,

can you provide a mockup on what you want to achieve? (use MS Paint to creatively show what you want :-))

John
