### ISSUE TITLE
How to use EnumEditor with multiple options selection

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4390]
In version 3.8.3, enum editor supports multiple options were added.

How can we use this?

I have tried the following but did not work
```
[EnumEditor(Multiple = true)]
public List<SomeEnum> SomeEnums { get; set; } 
```

**Comment by volkanceylan** [comment]
This should be working now, isn't it?

**Comment by in32bit** [comment]
Hi Volkan,

Do you have an example how to create a drop multi-selection base on an enum?

Thank you

**Comment by volkanceylan** [comment]
You might need to add [editorOption("enumKey", "Your.Namespace.SomeEnum")]

**Comment by dfaruque** [comment]
[EnumEditor(Multiple = true), EditorOption("enumKey", "some.key"), EnumFormatter]
        public List<SomeEnum> SomeEnumList { get { return Fields.SomeEnumList [this]; } set { Fields.SomeEnumList [this] = value; } }
        public partial class RowFields { public JsonField<List<SomeEnum>> SomeEnumList ; }

**Comment by xuliujian** [comment]
I tried to add a field by using multipe enum editor, but when i open the list, it shows following error.

![image](https://github.com/serenity-is/Serenity/assets/28293644/58516f97-5af9-47ee-a6c5-92da1f41d14f)

Row.cs:
```
    [DisplayName("Color")]
    [EnumEditor(Multiple = true)]
    public List<MyColors> Color { get => fields.Color[this]; set => fields.Color[this] = value; }

    public class RowFields : Serenity.Extensions.Entities.LoggingRowFields
    {
         public JsonField<List<MyColors>> Color;
    }
```

Column.cs:

  ```
  [EnumFormatter]
    public List<MyColors> Color { get; set; }
```

I checked that the module is created.

![image](https://github.com/serenity-is/Serenity/assets/28293644/00a27cea-3e66-42e1-bfe7-ab0f262e3c68)

**Comment by VictorTomaili** [comment]
You can use enum flags. https://github.com/serenity-premium/startsharp/blob/master/pro-features/src/Serenity.Demo.AdvancedSamples/Modules/Editors/EnumFlagsEditor/EnumFlagsEnum.cs

And please use discussions to ask questions.
