### ISSUE TITLE
Dapper Version included in Serenity

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4394]
Hey, i know Dapper version included in Serenity is custom version.
But do we know from which version it is related to ? (base version of Dapper)

Thanks !

**Comment by VictorTomaili** [comment]
https://github.com/volkanceylan/Serenity/blob/e611f93683fcde4a3dab8712fd938edb19619fa8/Serenity.Data/Serenity.Data.csproj#L19

**Comment by kilroyFR** [comment]
nope this apply only for .netStandard

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.4.3" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    <PackageReference Include="Dapper" Version="1.50.5" />
    <PackageReference Include="Microsoft.CSharp" Version="4.5.0" />
  </ItemGroup>

for framework 4.5

  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System.Data" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

there are SqlHelpers\Dapper.cs etc. that are custom version.

**Comment by kilroyFR** [comment]
not sure, this version is reference when using netstandard framework (not 4.5)

**Comment by VictorTomaili** [comment]
I guess this is most possible commit from source of google project what written on file description. 

https://github.com/StackExchange/Dapper/blob/b87d958314b1/Dapper%20NET40/SqlMapper.cs
