### ISSUE TITLE
Horizontal PDF Report generate

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4396]
Hello everyone,
I develop the printing option in my TblCustomer module and its working fine but I want to generate the pdf horizontally not vertically I don't have any idea how to do that 
Please help me with this

Thanks and Regards

**Comment by vinaykulkarni89** [comment]
public void Customize(IHtmlToPdfOptions options)
        {
            // you may customize HTML to PDF converter (WKHTML) parameters here, e.g. 
            options.MarginsAll = "2cm";
            options.Landscape = true;
        }

**Comment by Shraddha996** [comment]
@vinaykulkarni89  Perfect!  Thank you
