### ISSUE TITLE
Compatibility Visual Studio 2019

### ISSUE THREAD

**Issue by VirtualHome** [volkanceylan/Serenity#4398]
Hello!

Any plan to Serenity compatibility for Visual Studio 2019?

Thanks for your important comments.

**Comment by edwardch** [comment]
I'm using VS 2019 and my projects run fine... 

Or are you looking for the create site extension? Doesn't look like there are any out yet.

**Comment by VirtualHome** [comment]
> I'm using VS 2019 and my projects run fine...
> 
> Or are you looking for the create site extension? Doesn't look like there are any out yet.

**Comment by brunobola** [comment]
Serenity must change the behaviour to support node instead tsc.exe, but beside that it should run fine.
