### ISSUE TITLE
Not able to implement InplaceAdd successfully

### ISSUE THREAD

**Issue by absaakash** [volkanceylan/Serenity#440]
Hi Volkan

Added the following in my xxxxrow.cs

        [DisplayName("Sdw"), Column("SdwID"), ForeignKey("[dbo].[SDW]", "PKey"), LeftJoin("jSdw"), TextualField("SdwRelations"), LookupInclude]
        [LookupEditor(typeof(SdwRow), InplaceAdd = true )]
        public Int64? SdwId
        {
            get { return Fields.SdwId[this]; }
            set { Fields.SdwId[this] = value; }
        }
New button does shows up in Form, but clicking does not do the magic.

Compared with Northwind Product implementation, but still not able to make it work.

What else to look for?

Lots of Thanks in advance

**Comment by volkanceylan** [comment]
Chrome Console log please. Dear developers does not work is not a developer report.

**Comment by absaakash** [comment]
![image2](https://cloud.githubusercontent.com/assets/5682134/13943140/2190cda6-f020-11e5-977a-579f8912c60f.JPG)

Is This helpful for you to point something missing ?

Appreciate your patience

**Comment by tvldev02** [comment]
did you perform t4 transformation and build script project?

**Comment by volkanceylan** [comment]
Your dialog is probably named SdwDialog while lookup key is Default.SDW. So you need to either make lookup key compatible or set dialog type in LookupEditor attribute to Default.Sdw.

**Comment by absaakash** [comment]
Script Project

    [IdProperty(SdwRow.IdProperty), NameProperty(SdwRow.NameProperty), Flexify, Maximizable]
    [FormKey("Domain.Sdw"), LocalTextPrefix(SdwRow.LocalTextPrefix), Service(SdwService.BaseUrl)]
    public class SdwDialog : EntityDialog<SdwRow>
    {
        protected SdwForm form;

        public SdwDialog()
        {
            form = new SdwForm(this.IdPrefix);
        }
    }


Web Project

SdwRow.cs

    [ConnectionKey("Default"), DisplayName("Relationships"), InstanceName("Relationship"), TwoLevelCached]
    [ReadPermission("Administration")]
    [ModifyPermission("Administration")]
    [LookupScript("Default.Sdw")]
    public sealed class SdwRow : LoggingRow, IIdRow, INameRow, IIsActiveRow


xxxRow.cs

        [DisplayName("Sdw"), Column("SdwID"), ForeignKey("[dbo].[SDW]", "PKey"), LeftJoin("jSdw"), TextualField("SdwRelations")]
        [LookupEditor(typeof(SdwRow),InplaceAdd = true)]
        public Int64? SdwId
        {
            get { return Fields.SdwId[this]; }
            set { Fields.SdwId[this] = value; }
        }

Still i am getting Serenity.Script.UI.js?v=tIjtoygziomjoc0bDAxLcQ2:1946 Uncaught Default.SdwDialog dialog class is not found!

Also tried 

        [DisplayName("Sdw"), Column("SdwID"), ForeignKey("[dbo].[SDW]", "PKey"), LeftJoin("jSdw"), TextualField("SdwRelations")]
        [LookupEditor(typeof(SdwRow),DialogType ="Default.Sdw" ,InplaceAdd = true)]
        public Int64? SdwId
        {
            get { return Fields.SdwId[this]; }
            set { Fields.SdwId[this] = value; }
        }

Still i get

Uncaught Default.SdwDialog dialog class is not found!

**Comment by volkanceylan** [comment]
What is namespace of SdwDialog?

**Comment by volkanceylan** [comment]
My fifty cents on Domain.SdwDialog, why do you expect it to work as Default.SdwDialog. Why using "Default" as module name while it is connection key??

**Comment by absaakash** [comment]
namespace TestSample.Domain
{
    using jQueryApi;
    using Serenity;
    using System.Collections.Generic;

    [IdProperty(SdwRow.IdProperty), NameProperty(SdwRow.NameProperty), Flexify, Maximizable]
    [FormKey("Domain.Sdw"), LocalTextPrefix(SdwRow.LocalTextPrefix), Service(SdwService.BaseUrl)]
    public class SdwDialog : EntityDialog<SdwRow>
    {
        protected SdwForm form;

        public SdwDialog()
        {
            form = new SdwForm(this.IdPrefix);
        }
    }
}

------------------
I tried to follow how it has been implemented , and working

    [ConnectionKey("Northwind"), DisplayName("Products"), InstanceName("Product"), TwoLevelCached]
    [ReadPermission(Northwind.PermissionKeys.General)]
    [ModifyPermission(Northwind.PermissionKeys.General)]
    [LookupScript("Northwind.Product")]
    [CaptureLog(typeof(ProductLogRow))]
    [LocalizationRow(typeof(ProductLangRow))]
    public sealed class ProductRow : Row, IIdRow, INameRow

**Comment by volkanceylan** [comment]
Northwind is both module and connection key. In your case, Default is connection key while module is Domain.

**Comment by absaakash** [comment]
Bingo....... 

Thank you so much
