### ISSUE TITLE
Programming Side-Menu from TypeScript/JavaScript file

### ISSUE THREAD

**Issue by DavidKing0193** [volkanceylan/Serenity#4400]
Is it possible to enable and disable items on the side-menu through a typescript or javascript file?

Basically, I'm looking hide/enable items on the side navigation based on whether or not a user has a dealer selected.

**Comment by volkanceylan** [comment]
You might use CssClass property in navigation item attributes to locate the items in client side code and toggle its disabled state.

**Comment by bt101** [comment]
Hi @DavidKing0193,
Did you ever get this working? I was looking to implement something similar.
