### ISSUE TITLE
Remove EditLink based on Grid Column value

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4402]
Hello,

How can I add or remove Editlink  based on grid column value; for example if column value is equal to 1 then show edit link else remove edit link.

**Comment by RasaRinkeviciute** [comment]
protected getColumns(): Slick.Column[] {
            var columns = super.getColumns();

            for (let col of columns) {
                if (col.name.toLocaleLowerCase() == 'value') {
                    col.format = ctx => `<a href="javascript:;" class="column-link">${Q.htmlEncode(ctx.value)}</a>`;
                }
            }

            return columns;
        }
