### ISSUE TITLE
Prevent delete on condition

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4404]
Hi;

Like following validating request on save. I would like to validate delete as well. What I need is to check if the user name is like 'abc' then allow delete otherwise prevent delete.

                 protected override void ValidateRequest()
            {
                base.ValidateRequest();

                if (IsUpdate && Old.Approved==true)
                {
                    throw new ValidationError("This record is already approved and is locked. You cannot change/revise it.");
                }
            }

**Comment by Junariz** [comment]
how about imprementing IDeleteBehavior?

```
namespace SereneDemoServer.Sample.Behaviors
{
    using System;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using SereneDemoServer;

    /// <summary>
    /// Save Validation Behavior : Sample
    /// </summary>
    public class SaveValidateByLoginUserBehavior : IImplicitBehavior, IDeleteBehavior
    {

        /// <summary>
        /// return true for Validating row type...
        /// i.e. has a interface..
        /// </summary>
        /// <param name="row"></param>
        /// <returns></returns>
        public bool ActivateFor(Row row)
        {
            return true;
        }

        public virtual void OnPrepareQuery(IDeleteRequestHandler handler, SqlQuery query)
        {
        }

        public virtual void OnValidateRequest(IDeleteRequestHandler handler)
        {
            var user = Authorization.UserDefinition as UserDefinition;

            if (user == null)
            {
                throw new Exception("Unknown User");
            }
            // check user name...
            if (!user.Username.Equals(@"abc"))
            {
                throw new Exception("You must login user \"abc\" for delete row!");
            }
        }

        public virtual void OnBeforeDelete(IDeleteRequestHandler handler)
        {
        }

        public virtual void OnAfterDelete(IDeleteRequestHandler handler)
        {
        }

        public virtual void OnAudit(IDeleteRequestHandler handler)
        {
        }

        public virtual void OnReturn(IDeleteRequestHandler handler)
        {
        }
    }
}
```

**Comment by ms4hafiz** [comment]
@Junariz 

Thank you but they are not working

**Comment by Junariz** [comment]
Oh, thats sad.
1 Namespace in sample(SereneDemoServer) has dependency for your project.
2 I hope that you set breakpoints in the #ActivateFor and #OnValidateRequest of the behavior, and check where the control has been lost.

**Comment by ms4hafiz** [comment]
Thank you
But when apply it for one entity then it applies for all. Is there a problem.
    
    public class CoaMappingRepository:IImplicitBehavior, IDeleteBehavior
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void ValidateRequest()
            {
                base.ValidateRequest();
                if (((UserDefinition)Serenity.Authorization.UserDefinition).CanApprove == false)
                {
                    if (IsUpdate && Old.Approved == true)
                    {
                        throw new ValidationError("This record is already approved and is locked. You cannot change/edit it.");
                    }
                }
            }
        }
        private class MyDeleteHandler : DeleteRequestHandler<MyRow> {
        }
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { }
        private class MyListHandler : ListRequestHandler<MyRow> { }

        public bool ActivateFor(Row row)
        {
            return true;
        }

        public virtual void OnPrepareQuery(IDeleteRequestHandler handler, SqlQuery query)
        {
        }

        public virtual void OnValidateRequest(IDeleteRequestHandler handler)
        {
            var user = Authorization.UserDefinition as UserDefinition;

            if (user == null)
            {
                throw new Exception("Unknown User");
            }
            // check user name...
            if (!user.Username.Equals(@"hm"))
            {
                throw new Exception("You must login user \"hm\" for delete row!");
            }
        }

        public virtual void OnBeforeDelete(IDeleteRequestHandler handler)
        {
        }

        public virtual void OnAfterDelete(IDeleteRequestHandler handler)
        {
        }

        public virtual void OnAudit(IDeleteRequestHandler handler)
        {
        }

        public virtual void OnReturn(IDeleteRequestHandler handler)
        {
        }
    }

**Comment by Junariz** [comment]
Oh! Behavior interface is not for repository, see tutorial below:

https://serenity.is/docs/tutorials/multi_tenancy/using_serenity_service_behaviors

If you want to limit the entity on which the behavior works,

1) Create a interface (i.e. ILimitationDeleteInterface).

```
namespace Yoursystem.YourModule.Interface
{
    public interface ILimitationDeleteInterface
    {
    }
}
```

2) Imprement the interafce to the entity that you want to apply behavior.

```
public sealed class CoaRow : Row, IIdRow, INameRow,  ILimitationDeleteInterface
{
...
```

3) Modify behavior's ActivateFor method for find if the behavior act to the row or not.

```
    public class SaveValidateByLoginUserBehavior : IImplicitBehavior, IDeleteBehavior
    {

        public bool ActivateFor(Row row)
        {
            if(row is ILimitationDeleteInterface)
            {
                return true;
            }
            return false;
        }
```

**Comment by ms4hafiz** [comment]
Thank you
I am almost there..
I have a column name Approve in 4 tables. 
I am now stacked on how to identify which table is called in OnValidateRequest
I have the following but it does not work

            public virtual void OnValidateRequest(IDeleteRequestHandler handler)
        {
            var coamap = CoaMappingRow.Fields;
            var perBrkdown = PeriodBreakdownRow.Fields;

            if(coamap.Approved[handler.Row]==true)
            {
                throw new Exception("You are not allowed to delete this record!");
            }
            if(perBrkdown.Approved[handler.Row]==true)
            {
                throw new Exception("You are not allowed to delete this record!");
            }
        }

**Comment by Junariz** [comment]
How about below:

```
    public virtual void OnValidateRequest(IDeleteRequestHandler handler)
    {
        if(handler.Row is CoaMappingRow){
	        if(((CoaMappingRow)(handler.Row)).Approved)
	        {
	            throw new Exception("You are not allowed to delete this record!");
	        }
        }
        if(handler.Row is PeriodBreakdownRow){
	        if(((PeriodBreakdownRow)(handler.Row)).Approved)
	        {
	            throw new Exception("You are not allowed to delete this record!");
	        }
        }
    }
```

if all rows has "Approved" property and all are same type(Boolean?), all rows implements interface below, 

```
namespace Yoursystem.YourModule.Interface
{
    public interface ILimitationDeleteInterface
    {
       Boolean? Approved { get; }
    }
}
```

and it wouldl be simply

```
    public virtual void OnValidateRequest(IDeleteRequestHandler handler)
    {
        if(((ILimitationDeleteInterface)(handler.Row)).Approved)
        {
            throw new Exception("You are not allowed to delete this record!");
        }
    }
```

**Comment by ms4hafiz** [comment]
Thank you @Junariz . It works now very well.
