### ISSUE TITLE
ImageUploadEditor in .NET Core ThumbMode/ScaleMode

### ISSUE THREAD

**Issue by RasaRinkeviciute** [volkanceylan/Serenity#4405]
In .NET Core ImageUploadEditor has reduced properties and doesn't have ThumbMode or ScaleMode. How to preserve the ratio of the picture when image if uploaded into ImageUploadEditor? Also when it is planned to add this functionality to .NET Core? Thank you

**Comment by hubeyb** [comment]
maybe you can write your own editor by inherit the ImageUploadEditor.

**Comment by volkanceylan** [comment]
.NET Core version now has thumbnail generation since 3.9.12
