### ISSUE TITLE
Access afterloadEntity in Editor.ts

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4406]
Hello,

How can I get the afterloadentity in Details Editor.ts ?
Wanted to change details grid column format based on master form field.

**Comment by wezmag** [comment]
You can probably get master row in `setEditValue`
``` typescript
public setEditValue(source: XYZRow, property) {
    console.log(source); //<-- this is the master row
    super.setEditValue(source, property);
}
```
You can then call `this.slickGrid.setColumns` to change details grid column.
