### ISSUE TITLE
RowField Type JSON Array

### ISSUE THREAD

**Issue by qubess** [volkanceylan/Serenity#4407]
Is there a way to read Database Table Column as JSON JArray? In Serenity we have number or field type such as StringField, DoubleField etc... same way I want to parse column value to Jarray.

**Comment by Junariz** [comment]
If you would want to get simply row fields as json array(application/json formats) on http request with specular type, how about writing your own endpoint, use repository ?

(If you can Newtonsoft.Json Jarray type entity in server, it goes more simple.)

```

namespace SereneDemoServer.Sample.Endpoints
{
    using System;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using Serenity.ComponentModel;
    using System.Data;
    using System.Web.Mvc;
    using System.Collections.Generic;
    using SereneDemoServer;
    using SereneDemoServer.Administration.Entities;
    using SereneDemoServer.Administration.Repositories;

    [RoutePrefix("Services/Sample/JSONArrayAPI"), Route("{action}")]
    [ServiceAuthorize("Administration:General")]
    public class JsonArrayAPIController : Controller
    {

        /// <summary>
        /// returns json array Type result sample...
        /// read "quicksearch" parameter from request, and list it and returns as json array...
        /// </summary>
        /// <param name="uow"></param>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult UserRow()
        {
            var quickSearch = Request.Params["quicksearch"];

            var entities = new List<Object>();

            using (var connection = SqlConnections.NewFor<SereneDemoServer.Administration.Entities.UserRow>())
            {
                var repos = new SereneDemoServer.Administration.Repositories.UserRepository();
                var listResponse = repos.List(connection, new ListRequest() {
                    Take = 100,
                    ContainsText = quickSearch
                });

                foreach (var e in listResponse.Entities)
                {
                    var fields = new List<Object>();
                    foreach (var f in e.GetFields())
                    {
                        fields.Add(e.GetType().GetProperty(f.PropertyName).GetValue(e));
                    }
                    entities.Add(fields);
                }

            }
            return Json(entities, JsonRequestBehavior.AllowGet);

        }
    }
}
```

![serenity-json-arrayresult](https://user-images.githubusercontent.com/26323684/56222167-86910780-60a6-11e9-971c-6af19f3aebde.PNG)

**Comment by qubess** [comment]
Sorry for not explaining it in detail. What I want is that one of the field in ListResponse contain string in JSON array format from database. I don't want to set/get this column value in stringfield, if I do so then I need to parse the value of this column as Json explicitly. So is there any field type which can set/get Json string.
Ex:
Oracle Database Table consists below rows:
`ID       Name             PhoneNumbers
1         Qubess Ali      ["123","456","789"]`

**Comment by qubess** [comment]
Sorry for not explaining it in detail. What I want is that one of the field in ListResponse contain string in JSON array format from database. I don't want to set/get this column value in stringfield, if I do so then I need to parse the value of this column as Json explicitly. So is there any field type which can set/get Json string.
Ex:
Oracle Database Table consists below rows:
ID       Name               PhoneNumbers 
1        Qubess Ali        ["123","456","789"]
2        XYZ                   ["987","654","321"]

In above example my table consists three columns.
So my PersonRow would be defined as below

`public sealed class PersonRow : Row
    {
        [DisplayName("ID")]
        public Double? ID
        {
            get { return Fields.ID[this]; }
            set { Fields.ID[this] = value; }
        }

        [DisplayName("Name")]
        public String Name
        {
            get { return Fields.Name[this]; }
            set { Fields.Name[this] = value; }
        }

        [DisplayName("PhoneNumbers")]
        public String PhoneNumbers
        {
            get { return Fields.PhoneNumbers[this]; }
            set { Fields.PhoneNumbers[this] = value; }
        }
        
        public static readonly RowFields Fields = new RowFields().Init();

        public PersonRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public DoubleField ID;
            public StringField Name;
            public StringField PhoneNumbers;
            
            public RowFields() : base("tablename")
            {
                LocalTextPrefix = "Person";
            }
        }
    }`

So instead of below line
public StringField PhoneNumbers;

I am looking for
public JarrayField PhoneNumbers;

**Comment by Junariz** [comment]
Wow! I was misunderstood.
This is only an idea, If you do not require column data as "Field", but it is enough if there is a "property", how is that : property with NotMapped attribute.
Sample Below is with not JArray , but JObject Column, and very sorry I do not test Update method.

```
namespace SereneDemoServer.Default.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;

    [ConnectionKey("Default"), Module("Default"), TableName("[dbo].[JsonSample]")]
    [DisplayName("Json Sample"), InstanceName("Json Sample")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class JsonSampleRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), Column("ID"), Identity]
        public Int64? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Rowversion"), Column("ROWVERSION"), Insertable(false), Updatable(false), NotNull]
        public byte[] Rowversion
        {
            get { return Fields.Rowversion[this]; }
            set { Fields.Rowversion[this] = value; }
        }

        [DisplayName("User Name"), Size(16), QuickSearch]
        public String UserName
        {
            get { return Fields.UserName[this]; }
            set { Fields.UserName[this] = value; }
        }

        [DisplayName("Json Data"), Size(128)]
        public String JsonData
        {
            get { return Fields.JsonData[this]; }
            set { Fields.JsonData[this] = value; }
        }

        [NotMapped]
        public JObject JObject
        {
            get {
                if (String.IsNullOrEmpty(Fields.JsonData[this]))
                {
                    return null;
                }
                else
                {
                    try
                    {
                        return JObject.Parse(Fields.JsonData[this]);
                    }
                    catch
                    {
                        return null;
                    }
                }
            }
            set {
                if (value == null)
                {
                    Fields.JsonData[this] = null;
                }
                else
                {
                    Fields.JsonData[this]  = value.ToString();
                }
            }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.UserName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public JsonSampleRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int64Field Id;
            public ByteArrayField Rowversion;
            public StringField UserName;
            public StringField JsonData;
        }
    }
}

```

![jsonobject-sample01](https://user-images.githubusercontent.com/26323684/56284997-15f2f500-6151-11e9-8a08-a3161d5668b9.PNG)

![jsonobject-sample02](https://user-images.githubusercontent.com/26323684/56285003-1c816c80-6151-11e9-924b-146e6766c727.PNG)


With .Net application with serenity, I can deserialize JObject at client application.

![jsonobject-sample03](https://user-images.githubusercontent.com/26323684/56285020-2905c500-6151-11e9-8184-a0ae1a5ae560.PNG)

**Comment by qubess** [comment]
Thanks for your prompt reply. And this is exactly the answer, I was dying for. It worked. Great!!!

I am really a big fan of Serenity framework. My company wants to subscribe for the Serenity support. Give us some discount. I am the part of American University of Middle East, Kuwait, working as Senior Software Engineer.
