### ISSUE TITLE
Upgrading to 3.9.8 and package management

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#4409]
Hello, I'm trying to upgrade a project to VS 2019 - serenity 3.9.8 but after several attempts I'm a bit lost on the package management part.

I have installed asp.net core 2.2 sdk for VS 2019 as per the prerequisites
C:\Program Files\dotnet\sdk\2.2.203

The problem is I cannot upgrade Microsoft.AspNetCore.All from 2.0.8 and I cannot either install  AspNetNetCore.App 2.2.4 "not compatible with netcoreapp2.0"

If I change the Target framework in the project properties to .NET Core 2.2, , all the nuget packages are uninstalled, that leaves the project with thousands errors and most nuget packages to re-install, 

- can you please help with the order all this should be done, upgrading packages vs switching the Target framework 
- which package should be installed / kept / upgraded : AspNetCore.All or AspNet.Core.App or both (when AspNetCore.All was previously installed)?
- how do you get the asp.net core 2.2 sdk to be found by VS 2019 when you have it installed and the package manager keeps saying: 
 
_"Package Microsoft.AspNetCore.All 2.2.4 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.All 2.2.4 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)"_	

For information, a new 3.9.8 project works fine with VS 2019.
Existing projects also work fine with 3.9.8 and VS 2019 but when staying on the 2.0 core target and without AspNetCore package upgrade.

**Comment by minhhungit** [comment]
In .csproj file, try to update this
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.2.4" />
```
to
```
<PackageReference Include="Microsoft.AspNetCore.All" />
```

it might work

**Comment by BravoSierra** [comment]
The only difference it makes is that the package manager sees the current version as "0.0.0" but still does not want to install 2.2.4. The nuget error NU1202 suggests "Change the project's target framework to one that the package supports.", but this destroys my packages including those that were up to date for 2.2.4

It looks like a circular reference issue beetween updating the target or the packages

**Comment by cengkaplan33** [comment]
I have the same problem .  change which one . specifically specified for core 2.1 :(
I guess 2.2 will be real problem for me :(

I opened same issue  https://github.com/volkanceylan/Serenity/issues/4488
#4488 


![image](https://user-images.githubusercontent.com/3457947/59601557-fe15fe00-910c-11e9-99e1-db46e29da394.png)

**Comment by volkanceylan** [comment]
Please take a look at latest Serene/StartSharp project codes.
