### ISSUE TITLE
Issue creating Custom Dialog

### ISSUE THREAD

**Issue by absaakash** [volkanceylan/Serenity#441]
Created a new class in Script Project

Note: we do have working GuestDialog and GuestGrid

using jQueryApi;
using SolutionDomain.Visitor;
using Serenity;

namespace SolutionDomain.Visitor
{
    class GuestMasterCustomDialog : GuestDialog
    {
        public GuestMasterCustomDialog()
        {
            form.AgeY.Element.FlexXFactor(.33);
            form.AgeM.Element.FlexXFactor(.33);
            form.AgeD.Element.FlexXFactor(.33);
        } 
    }

    [DialogType(typeof(GuestMasterCustomDialog))]
    public class GuestMasterCustomGrid : GuestGrid
    {
        public GuestMasterCustomGrid(jQueryObject container)
            : base(container)
        {
        }
    }
}

After this when Script project is Build we get following error

![customproblem](https://cloud.githubusercontent.com/assets/5682134/13942509/190e6636-f019-11e5-8587-25ef6937afbb.JPG)

Any sequence of steps needed to accomplish customization of Forms ?

Now even if i remove this new class, Project now always hits the above error.

Thanks in Advance

**Comment by jsbUSMC** [comment]
You need to remove the `System` reference from Script project. It conflicts with `mscorlib`, which is the custom System reference that Saltarelle uses. If you still receive errors about the ambiguous `Stack<T>` reference, right click on Editor and prefer the Serenity.EditorAttribute

**Comment by absaakash** [comment]
![customproblem2](https://cloud.githubusercontent.com/assets/5682134/13964814/9cd64e66-f091-11e5-84e6-138eee06d8e3.JPG)

Tried as per your suggestion, still no luck

**Comment by volkanceylan** [comment]
:) Remove System assembly reference from project, not namespace
