### ISSUE TITLE
Error in Editor.ts file

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4410]
Hello everyone and @volkanceylan 
I create a new project in serenity  by name TechproBooks with forms like a customer, supplier, SalesInvoice, etc
 I want a master-detail relation in SalesInvoice form
So I created typescript file naming TblSalesInvoiceEditor.ts
But I couldn't find a reference to the row, dialog, from TblSalesInvoiceEditor.ts file and it is showing error like this

![Capture14](https://user-images.githubusercontent.com/39983941/56275239-f1c9f080-611d-11e9-85fe-9abd0ec421cc.PNG)

In my previous project of serenity, I created many editors for master-detail relations that time it was working fine 
Now am unable to find the solution for this

It would be a great pleasure if anyone helps

**Comment by Shraddha996** [comment]
And also getting warnings like,

C:\Users\Pc101\source\repos\TechproBooks\TechproBooks\TechproBooks.Web\node_modules/@types/react/index.d.ts(379,23): warning TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later. 

&

C:\Users\Pc101\source\repos\TechproBooks\TechproBooks\TechproBooks.Web\TechproBooks.Web.csproj(2598,5): warning MSB3073: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\x86\node" "C:\Users\Pc101\source\repos\TechproBooks\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\..\tools\tsc\tsc.js" -p ./tsconfig.json" exited with code 2.

**Comment by DavidKing0193** [comment]
I'm a bit of a novice, so I'm probably wrong, but have you transformed your T4 templates? I ran into a similar issue and I was neglecting to do that.

**Comment by Shraddha996** [comment]
@DavidKing0193  I did transform T4 template still the same warnings

**Comment by JohnRanger** [comment]
Hi @Shraddha996 

if I look at your screenshot, it does not even recognize your row and dialog classes. Are you in the correct namespace with your xyzEditor.ts?

John

**Comment by dxh141130** [comment]
@Shraddha996  I have the same issue like you. Did you solve that? I can transform and compile successfully, but it always warning.

**Comment by Shraddha996** [comment]
@dxh141130  after successfully Transforming T4 templates and restart of application the error is gone but warnings are still there

**Comment by JohnRanger** [comment]
Hi all,

I also have the same problems - including the "Set" problem.

It seems that the recent development environment of Serenity is extremely unstable/sensible to smallest - but correct - changes.

I can have 0 errors and then add a minimal change in one of the cs or ts files and immediately more than 100 (seemingly unrelated) errors show up.

This I do not have with my good "proved" SF 2.9.24-based projects.

Also after transforming T4 multiple times, these problems do not go away.

Will try with VS 2019 - but if these issues prevail, I simply cannot use a newer SF-based project. Have already wasted 2 days in trying to forward migrate a larger project.

With kind regards,

John

**Comment by chynoradsky** [comment]
Had a similar problem....restarting VS solved it
