### ISSUE TITLE
Can't see the login page

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4412]
I was created a sample serenity project without selecting..

1.BasicSample Checkbox
2.NorthWind Checkbox
3.Theme Samples Checkbox

when i try to run the project, login page is broken.. 
![Serenity_Template](https://user-images.githubusercontent.com/28822452/56454223-1a92f580-636b-11e9-8d1f-9e3627043ad7.png)

**Comment by JohnRanger** [comment]
Use Chrome and then press F12 to see the console. Any Errors shown?

**Comment by flextrio-gandhi** [comment]
Yes Some of the resources(libraries) were missing i added externally now its working fine...
iam wondering why that resources got missed?
