### ISSUE TITLE
Why this is not working?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4413]
I have the following trying to check if TenantId==1 

but it is not working and not showing while TenantId is 1

            public virtual void OnValidateRequest(IDeleteRequestHandler handler)
        {

            if (fld.TenantId==1)
            {
                throw new Exception("You are not allowed to delete this record. It is already approved!");
            }

        }

**Comment by flextrio-gandhi** [comment]
try this.. 
if (fld.TenantId.Equals("1"))
        {
            throw new Exception("You are not allowed to delete this record. It is already approved!");
        }

**Comment by ms4hafiz** [comment]
@flextrio-gandhi 
The same problem. Not working.

**Comment by Junariz** [comment]
try once:
handler.Row.TenantId
