### ISSUE TITLE
How to return the Parameter Output in Unit of Work Response

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#4415]
Hi All,
   I have a problem getting the result of @RESULT parameter.
i want to get the message from this parameter so i can show an alert message after click event.

see sample code

` [HttpPost]
        public MyActionResponse CreateMaterials(IUnitOfWork uow, MyActionRequest request)
        {
            string account = System.Convert.ToString(Authorization.Username);

            uow.Connection.Execute("PopulateMaterials",
                                      param: new
                                      {

                                          @id = request.Id,
                                          @user = account.ToString(),
                                          @RESULT = ParameterDirection.Output

                                      }
                                      , commandType: CommandType.StoredProcedure);

          return new MyActionResponse();
       
        }`

this is the code in my Grid.ts
`if (target.hasClass('approve-row')) {
                    Q.confirm('Populate records?', () => {
                        MaterialsService.CreateMaterials({
                            Id: item.Id
                           
                        }, response => {
                            Q.notifySuccess("Success", '', null), this.refresh();
                        });
                    });
                }`

TIA!

**Comment by Junariz** [comment]
Have you tried declare dynamic parameter, and used Get<T> method  for output?

https://dapper-tutorial.net/parameter-dynamic
https://stackoverflow.com/questions/51187043/dapper-sql-server-get-output-from-stored-procedure-containing-insert-and-selec

**Comment by alex-444** [comment]
@Junariz thanks for suggestions.
I tried a different approach.
