### ISSUE TITLE
How to change CSS for buttons to use fontawesome icons?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4416]
Dear all,

I can see that in the current demo, some buttons (like the delete button) are using fontawesome icons and not anymore bitmap images.

When I look at the most recent "free" version of the Serenity framework (3.9.3.6) then there are still the "old" bitmaps used.

How to change the css of e.g. the delete button to use fontawesome icons?

I have looked at the DOM and have seen that it is made like this:

```html
<span class="button-inner"><i class="fa fa-trash-o text-red"></i> Löschen</span>
```

But I could not figure it out how to change the relevant CSS:
```css
.delete-button span.button-inner {
    background-image: url(images/cross-script.png);
}
```

I would have expected it to be something like this:
```css
.delete-button span.button-inner.i::before {
    ???: "fa fa-trash-o";   
}
```
As I unfortunately do not understand CSS very well, I could not figure it out (even with studying some SO articles).

Is this at all possible with pure CSS - or do I have to involve the setting of the image class via javascript?

Any help is greatly appreciated.

With kind regards,

John

**Comment by brunobola** [comment]
Just use any icon like so:
    background-image: url(data:xxx;base64,Pxxxxxx);
    background-repeat: no-repeat;
    background-size: 16px 16px;

**Comment by JohnRanger** [comment]
Hi @brunobola ,

Hmm, 
that only moves the Image data directly into CSS - which I don't want. If I have to use images, then I will continue to use it in separate files which easily can be exchanged and previewed when I want to (as in older Serene apps).

But what I want now (therefore my question here) is to use the Fontawesome Icons within the buttons - like in the current online demo of serene (If you inspect the DOM of the current Serenity online demo and look at the delete button, you will notice that it is done with the fontawesome fa-trash-o icon and not a bitmap).

So my question still stands :-)

With kind regards,

John

**Comment by brunobola** [comment]
Hi @JohnRanger,

I know what you mean, I only give you a hint on how to use css.
You can offcourse use paths like so:

`background-image: url(images/trash.png);`

As off the demo you just have to inspect it and do the same:

Try this

1. Create a class that descend "span.button-inner"
2. Create the padding as off: "padding: 3px 3px 3px 0px;"
3. Create a style to it to have "<i class="fa fa-trash-o text-red"></i>"
4. Create a Class to your button that descend from your previous created Class
5. Add "background-image: none;" to it

I believe you can do it like so.

**Comment by wezmag** [comment]
Try this.
``` css
.delete-button span.button-inner:before {
    content: "\f014";
    font-family: FontAwesome;
    padding-right:3px;
}
.delete-button span.button-inner {
    padding-left: 3px;
}
```

**Comment by JohnRanger** [comment]
@wezmag ,

wow! Perfect :-) Exactly what I was looking for.

Thank you very much!

I will do a wiki entry for this.

With kind regards,

John
