### ISSUE TITLE
Open a Dialog and Populate it With User Names

### ISSUE THREAD

**Issue by ShahzanSyed** [volkanceylan/Serenity#4417]
![MainImg](https://user-images.githubusercontent.com/16576818/56627650-16781800-668a-11e9-99e9-90cbd78780c9.PNG)
Hello, 
I want to build this functionality(see image). I've tried below code but I'm able to load only 1 value in the new dialog. I want to load all the Users in the new dialog something like a Grid with a single column as can be seen in the above image( with names).

I've created a Form for displaying Usernames and on the Grid, I'm writing below code to add an Up-arrow button and on click of this button it should open another dialog with a username which when selected will get assigned to the text field( named Tm in image).

`
protected afterLoadEntity()

 {

            super.afterLoadEntity();

	$('<a class="classnames"><b><\/b><\/a>')

                .insertAfter(this.form.Tm.element)

                .click(() => {

                    {
                        var dlg = new DWPlus.WCID.UserFormWCIDDialog(); // New form for Username fields

                        this.initDialog();

                        var users = Q.first(Administration.UserRow.getLookup().items, x => x.Username === 'Steve')                        

                        dlg.loadEntityAndOpenDialog(<Administration.UserRow>{

                            Username: users.Username

                        });

                    }

                });
}`

**Comment by JohnRanger** [comment]
Hi @ShahzanSyed ,
Why don't you just use a standard Serenity lookup field (which stores the ID of the user whcih you want to search for) for the TM field and assign it with the Lookupeditor which points to the lookupscript on the xyzRow.cs, where the user data is stored?

Then you get automatically a jquery select2 search dropdownvox, which provides exactly the functionality of your custom dialog - just in a more compact form.

With kind regards,

John

**Comment by ShahzanSyed** [comment]
That's the solution. Don't know how I missed this. Thanks a lot, @JohnRanger

**Comment by ShahzanSyed** [comment]
@JohnRanger I implemented the lookup in a demo project. But I have an issue, the table(fields) screen in my earlier post doesn't have a relationship with the User table i.e. there is no foreign key in table I'm displaying. Any idea how to get the User list without a foreign key?
