### ISSUE TITLE
Dynamic lookup table

### ISSUE THREAD

**Issue by gulgil** [volkanceylan/Serenity#4418]
First off, I'm new to Serenity, so I'm not fully into how it works.

I have this bit of weird scenario. I have tried to simplify it here. The real case is more complex, but I just need to find out how to do this, then I can apply it to my case.

Take this database structure and data:
[Type] 
id, name, lookupTable
1, Car, Car
2, Ship, Ship
3, Airplane, Airplane
4, Other, NULL

[Car] 
id, name
1, BMW
2, Audi
...

[Ship] 
id, name
1, Maersk
2, MSC
...

[Airplane] 
id, name
1, Airbus 
2, Boeing 
...

[DataSet]
id, type, typeId, Note
1, 1, '1', 'This is BMW'
2, 1, '2', 'This is Audi'
3, 2, '1', 'This is Maersk'
4, 4, 'somthing', 'This is some other undefined thing'

(Note that typeId is a loose coupling)

What I want to do in Serenity is to create a CRUD for [DataSet] table.
First you select the type, and depending on what you select (car, ship, plane, other), it should show a dropdown with that given data, or for "other" it should show a input field. And last it shows a note field.

I can easily set TypeId to Car by adding [LookupEditor(typeof(CarsRow))], but I need to change it dynamically base on the selection in Type.
And I need to remove it completely in case of "other" is selected, and show a basic textbox instead.

I have thought of simply adding Car, Ship, Airplain and Other as NotMapped fields, an then try to show/hide them based on type selection, and then override executesave in SaveRequestHandler. But I don't know how to show/hide them in the form editor, and I am not sure how my override of executesave should work.
Also... Since new types could be added later, I would then need to add them as NotMapped fields, and change the executesave override code. I would prefer if it could work dynamically base on lookupTable column.

How would you go about creating this?

For now I have simply created typeId as a string, which results in a plain textbox , and then it is up to the user to write the correct Id into it. But it would be much better if they could choose the Id from a dropdown.

**Comment by wezmag** [comment]
You need to change your table as below:

**Types**

Id | Name
------------ | -------------
1 | Car
2 | Ship
3 | Airplane
4 | Other

**Vehicles**

Id | TypeId | Name
-- | ------- | --------
1 | 1 | BMW
2 | 1 | Audi
3 | 2 | Maersk
4 | 2 | MSC
5 | 3 | Airbus
5 | 4 | Boeing

Then you can use the build in cascaded editor.
[https://serenity.is/docs/howto/how_to_setup_cascaded_editors](https://serenity.is/docs/howto/how_to_setup_cascaded_editors)

To hide the vehicles lookup editor when "Other" is selected is also very simple.
In the constructor of your Dialog.ts, write the following code:
``` typescript
this.form.Type.changeSelect2((e: any) => {
    if (e.val === 4) { //id of Other
        this.form.Vehicles.element.closest('.field').toggle(false);
        this.form.BasicTextbox.element.closest('.field').toggle(true);
    }
    else {
        this.form.Vehicles.element.closest('.field').toggle(true);
        this.form.BasicTextbox.element.closest('.field').toggle(true);
    }
});
``` 

In your **DataSet** table, you will need to add columns for BasicTextBox and Vehicle Id.

**Comment by gulgil** [comment]
@wezmag
Per techinaly circumstances, It is not possible for me to combine car, ship and plane to one table.  

But I have used the change event on the dropdown to show/hide the correct selector. And then I override the save handler to get the correct value.
