### ISSUE TITLE
Implementing send email facility

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4419]
Hello everyone and @volkanceylan 
Am trying to implement the send email option on my Main **SAVE** ButtonClick so I write code in Repository.cs file
 `
namespace TechproBooks.Books.Repositories
{
    using Mono.Collections.Generic;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using System;
    using System.Collections.ObjectModel;
    using System.Configuration;
    using System.Data;
    using System.Net.Mail;
    using System.Text;
    using TechproBooks.Administration.Entities;
    using MyRow = Entities.TblSalesInvoiceRow;

    public class TblSalesInvoiceRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            var abc = new MySaveHandler().Process(uow, request, SaveRequestType.Create);
            var emailSubject = Texts.Forms.Membership.SendMail.MailSubject.ToString();
            var emailBody = Texts.Forms.Membership.SendMail.MailBody.ToString();

            Common.EmailHelper.Send(emailSubject, emailBody, Authorization.UserDefinition.Email);

            return abc;
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow> { }
        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { }
        private class MyListHandler : ListRequestHandler<MyRow> { }
    }
}`

and also added below code in web.config file
`<smtp from="abc@gmail.com" deliveryMethod="SpecifiedPickupDirectory">
        <network host="mail.google.com" userName="abc@gmail.com" password="abc" />
      </smtp>`

Am not getting any error on save button click but It didn't send any mail
Maybe am missing something really important Or should I need to try another method which is easier?

Please help me throughout this.

**Comment by edwardch** [comment]
Can you remove delivery method and try again?
```
<smtp from="abc@gmail.com" >
<network host="mail.google.com" userName="abc@gmail.com" password="abc" />
</smtp>
```

**Comment by Shraddha996** [comment]
@edwardch  Hey I tried that but it shows the alert message
as **"failure sending mail"**

**Comment by edwardch** [comment]
Hmm it's hard to say, maybe put it all inside a try..catch and see what the exact error is?

I've had difficulty sending smtp emails through gmail in the past (in other projects). I think you might need to change the port and SSL settings so you might need to look it up.

I'm currently using SendGrid to send my emails in Serenity using smtp and it works really well... They have a free tier that allows 100 emails per day, so maybe give that a try?

Once you have an account, you can just set your mail settings like this:
```
<system.net>
	<mailSettings>
		<smtp from="no-reply@yourdomain.com">
			<network host="smtp.sendgrid.net" password="yourSendGridPassword" userName="yourSendGridUsername" port="587"/>
		</smtp>
	</mailSettings>
</system.net>
```

PS. I'm not affiliated with SendGrid in any way, just a happy customer.

**Comment by Shraddha996** [comment]
@edwardch thanks but if you don't mind, will you share your send mail code?
Am still getting error

**Comment by edwardch** [comment]
So I just use the code in Modules/Common/EmailHelper.cs file...

Did you add a try..catch and debug to get the error?

**Comment by Shraddha996** [comment]
hey, @edwardch thanks for your quick response!
Actually, I made a little change in my web.config and now it is working fine
One more question for you is do you use attachment in your mailing option?
I want to attach serenity through generated PDF with the mail

Thanks in advance

**Comment by edwardch** [comment]
Cool, glad its working!

When you build your message you need an attachment path, then you can also set your attachment to have a custom name like so:

```cs
var attachment = new Attachment(attachmentPath);
attachment.Name = attachmentName;
message.Attachments.Add(attachment);
```

**Comment by Shraddha996** [comment]
@edwardch  am unable to find the **attachmentpath** will you please elaborate a bit?

**Comment by edwardch** [comment]
attachmentPath and attachmentName are both strings that you'll need to specify. They're dependent on where your file is, and what you want to name your attachment. 

You could create a custom Send() method with the attachmentPath and attachmentName as optional string parameters. If it's blank then don't add the attachment, otherwise attach them using the code above...

**Comment by Shraddha996** [comment]
@edwardch thank you for your time and help! you cleared almost all difficulty

**Comment by Shraddha996** [comment]
hello @edwardch  am having an issue while sending the attachment
As we know in serenity we have a  generate reportToPDF option and I want to email that pdf 
I think we didn't save that pdf in our solution so I'm unable to set the path for the attachment

Please help!

**Comment by edwardch** [comment]
If your report is not in your serenity app directory you could always convert it to a Stream and then to add the attachment:
```cs
Stream contentStream = SomeMethodToGetYourPdfAsStream();
var contentType = "application/pdf";
var attachment = new Attachment(contentStream, attachmentName, contentType);
```
Or something along those lines...

**Comment by Shraddha996** [comment]
@edwardch Thank you! looks like perfect
