### ISSUE TITLE
ask: is it possible to change the Admin LTE template into other?

### ISSUE THREAD

**Issue by go2ismail** [volkanceylan/Serenity#442]
hi @volkanceylan ,

i'm still learning how to use and be productive with serene. enjoying the learning and having fun also.

i would like to ask, is it possible to change the Admin LTE template into other bootstrap template that i can found on wrapbootstrap.com maybe? if its possible, would you like please to share the big picture of how of doing it?

thank you for create and share this great product

merci,
ismail.

**Comment by volkanceylan** [comment]
AdminLTE is also a bootstrap template so it shouldn't be very hard. Make sure you change LeftNavigation.cshtml, site.less with adminlte include and script includes to something compatible with your new template.

**Comment by go2ismail** [comment]
hi @volkanceylan ,

thank you for your feedback.

merci,
ismail

**Comment by tonysader** [comment]
@go2ismail Does it work for you ? can u give me a short description how you do it please
Thanks
