### ISSUE TITLE
Inline Grid Delete error

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4420]
Hello everyone and @volkanceylan 
I have implemented the inline action grid to delete the items 
and also written code for calculation on delete button click event
![Capture21](https://user-images.githubusercontent.com/39983941/56800620-1b2efe80-6839-11e9-8f5f-b9904a096d66.PNG)

 as you can see the addition of the items doing a great job
![Capture22](https://user-images.githubusercontent.com/39983941/56800721-5d584000-6839-11e9-867c-d72608a72801.PNG)

 But when I delete the items it is showing correct results, but adding (-) sign to the number

**CODE OF DELETING ITEM**
` this.form.DetailList.element.on('DOMNodeInserted DOMNodeRemoved', () => {
                this.doSomething();
            });
        }

        protected doSomething(): any {
            var total = 0;
            var total1 = 0;
            var total2 = 0;
            var total3 = 0;
            var total4 = 0;
            for (var k of this.form.DetailList.getItems()) {
                total -= k.Net || 0;
                total1 -= k.Vat || 0;
                total2 -= k.Gross || 0;
                total3 -= k.LessCIS || 0;
                total4 -= k.AmountDue || 0;
            }
            //Q.notifySuccess(total.toString());
            this.form.Net.value = total;
            this.form.Vat.value = total1;
            this.form.Gross.value = total2;
            this.form.LessCIS.value = total3;
            this.form.AmountDue.value = total4;
        }`

Hope this information is enough
any suggestion would be appreciated

Thanks!

**Comment by wezmag** [comment]
@Shraddha996 
Use `this.deleteEntity(id)` to delete item from grid.
You can refer to my code in another issue of yours.
