### ISSUE TITLE
MasterDetailRelation will not save on customized DetailsEditor

### ISSUE THREAD

**Issue by nickdonato** [volkanceylan/Serenity#4421]
I have customized the DetailsEditor to provide some user friendly stuff, but when I click the save button, the form will make sure that all fields are validated, but it will not save the data. I have no idea what's wrong and I've spent 7 hours trying to figure this out. Someone please help.

`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Atlas.Atlas {

    @Serenity.Decorators.registerClass()
    export class TimeLogDetailsEditor extends Common.GridEditorBase<TimeLogRow>
    {
        protected getColumnsKey() { return "Atlas.TimeLog"; }
        protected getDialogType() { return TimeLogDetailDialog; }
        protected getLocalTextPrefix() { return TimeLogRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        /**
         * This method is called to get list of buttons to be created.
         */
        protected getButtons(): Serenity.ToolButton[] {

            var buttons = super.getButtons();

            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);

            buttons.push({
                title: 'Add Time', cssClass: 'add-note-button',
                onClick: () => {
                    var dlg = new Atlas.TimeLogDetailDialog();

                    var user = Q.Authorization.userDefinition;

                    this.initDialog(dlg);

                    dlg.loadEntityAndOpenDialog(<Atlas.TimeLogRow>{
                        User: Administration.UserRow.getLookup().items
                            .filter(x => x.Username === user.Username)[0].UserId,
                        Date: Q.formatDate(new Date(), 'yyyy-MM-dd')
                    });
                }
            });

            return buttons;
        }

    }       
}`

**Comment by ga5tan** [comment]
I would venture to guess, that you either have to provide/override some before save event, or do the saving/binding by yourself...

**Comment by nickdonato** [comment]
That's what I thought as well so I tried writing a validate method to just return true, hoping that would trigger the save event, but it didn't. I figure there has to be some easier way of doing this.

**Comment by nickdonato** [comment]
Following [this](https://github.com/volkanceylan/Serenity/issues/837) thread now has my time log saving to memory just fine and the code now looks like this:

`
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />
namespace Atlas.Atlas {

    @Serenity.Decorators.registerEditor()
    export class TimeLogDetailsEditor extends Common.GridEditorBase<TimeLogRow>
    {
        protected getColumnsKey() { return "Atlas.TimeLog"; }
        protected getDialogType() { return TimeLogDetailDialog; }
        protected getLocalTextPrefix() { return TimeLogRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        public subtaskId: number;

        /**
         * This method is called to get list of buttons to be created.
         */
        protected getButtons(): Serenity.ToolButton[] {

            var buttons = super.getButtons();

            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);

            buttons.push({
                title: 'Add Time', cssClass: 'add-note-button',
                onClick: () => {
                    
                    this.createEntityDialog(this.getItemType(), dlg => {
                        var dialog = dlg as TimeLogDetailDialog;
                        var user = Q.Authorization.userDefinition
                        dialog.onSave = (opt, callback) => this.save(opt, callback);
                        var entity = this.getNewEntity() as TimeLogRow;
                        entity.User = Administration.UserRow.getLookup().items
                            .filter(x => x.Username === user.Username)[0].UserId;
                        entity.Date = Q.formatDate(new Date(), 'yyyy-MM-dd');
                        dialog.loadEntityAndOpenDialog(entity);
                    })
                }
            });

            return buttons;
        }

        protected validateEntity(row: TimeLogRow, id: number) {
            if (!super.validateEntity(row, id))
                return false;  

            row.SubTaskId = this.subtaskId;
            return true;
        }
    }       
}
`

The issue now is that I actually need the time log row committed to the database without having to save the parent dialog. It seems that according to [this](https://github.com/volkanceylan/Serenity/issues/4014) issue, this is not something that the MasterDetailsRelation allow. However, I absolutely need that to work. If anyone has any code that could help with this, I'd appreciate it.

**Comment by JohnRanger** [comment]
On a high level view (and I have not tested it), change the detail editor to not extend from Common.GridEditorBase but - like the "normal" grids, extend from Serenity.EntityGrid.

And then you have to modify your DetailEndpoint.cs + DetailRepository.cs to similar like a "normal" (non detail) Endpoint and Repository.

Because these to save on each click on the save button in the dialog.

Hope this helps.

John
