### ISSUE TITLE
Embracing Blazor

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4423]
Dear @volkanceylan 
Do you have any plan to introduce Blazor in Serenity?

Blazor now in official preview!
https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/?utm_source=vs_developer_news&utm_medium=referral

**Comment by edwardch** [comment]
Do you mean "Embracing"? ;)

**Comment by dfaruque** [comment]
Yes. 
Thank you @edwardch

**Comment by minhhungit** [comment]
I think the same, I dare blazor will match with Serenity

**Comment by volkanceylan** [comment]
Will think about it, using C# both side is interesting (though tried that with Saltarelle before), but wouldn't want to create just another option (they are tiring for us and confusing for end users), there are some showstoppers like 2MB+ framework download, and as a bonus anybody remember Silverlight?

**Comment by dfaruque** [comment]
Thank you very much @volkanceylan for your response.

**Comment by mahmuthaktan** [comment]
Adding Blazor to an Existing MVC Application 

https://www.youtube.com/watch?v=rfPQytn7tfk&list=PL8h4jt35t1wjvwFnvcB2LlYL4jLRzRmoz&index=20
