### ISSUE TITLE
IIS Publish Error

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4424]
Hello everyone and @volkanceylan
When publishing to IIS am getting the runtime error about the scripts
I also included all **3** files from Script->site folder But still shows the same error

![Screenshot (5)](https://user-images.githubusercontent.com/39983941/56945147-ab27bd80-6b43-11e9-921a-ed638eaa398e.png)

Please help with this am clueless

**Comment by YYOHAN** [comment]
If it is working fine in your development computer, the problem you might be with your web.config file.
If you have a forward slash  (/) in front of DynJS.axd, Remove it!. Use:
<add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />

**Comment by Shraddha996** [comment]
@YYOHAN  wonderful! This is Perfect
Thanks!
