### ISSUE TITLE
Display the grid in jqGrid

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#4427]
Dear,
How do I display the grid using jqGrid in place of slickgrid?

**Comment by ga5tan** [comment]
check the samples, ,there is some grid/list
https://serenity.is/demo/AdvancedSamples/BootstrapFormList
and populating from stored procedure:
https://serenity.is/demo/BasicSamples/StoredProcedureGrid

so you can feed you grid from stored procedure.
alternatively, check how slickgrid is populated and just try to replace it 1:1
(I am assuming, if that was so easy, we would long got rid of SG)

**Comment by juliermefelix** [comment]
It really is very difficult to change the slickgrid.

**Comment by volkanceylan** [comment]
Yes, requires good JS knowledge
