### ISSUE TITLE
Wiki - Links broken!

### ISSUE THREAD

**Issue by euclidesgc** [volkanceylan/Serenity#4428]
The links on this page its broken!

https://github.com/volkanceylan/Serenity/wiki

**Comment by edwardch** [comment]
Some of these pages have recently been renamed or recategorised and the links need to be worked on.

The wiki search still works and you can find all of the pages there, and you can also take a look at [the guide](https://serenity.is/docs/) for help...

**Comment by JohnRanger** [comment]
Please close as this has been answered.

With kind regards,

John

**Comment by JohnRanger** [comment]
@euclidesgc ,

as this has been answered above, would you mind to close your issue? :-)

with kind regards,

John
