### ISSUE TITLE
MasterDetailRelation: check if the parent and/or one (or more) child has been modified

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#443]
Dear @volkanceylan ,
in a MasterDetailRelation there is a simple way to check if the entities of the parent and/or of the childs has been modified?
I'm trying to do that in the override of AfterSave() method in "MySaveHandler" class...
I can banally compare the Row object with the Old object or there is a better/cleaner way to do that?
And the same approach should be taken when comparing the child items?
What I want to achieve, is to trigger an action (write a record into a table) if the parent and/or the childs has been modified...

Edit: just found a "Row.IsAnyFieldChanged"...this is the right approach?

Thanks for your support
Best Regards

**Comment by volkanceylan** [comment]
If you only care about table fields:

```cs
            bool anyChanged = false;
            foreach (var field in Row.GetTableFields())
            {
                if (field.IndexCompare(Old, Row) != 0)
                {
                    anyChanged = true;
                    break;
                }
            }
```

You can do something similar for children. Make sure you load old children rows and only compare assigned fields (Row.IsAssigned(field))

See MasterDetailBehavior source for some sample.

**Comment by marcobisio** [comment]
Thanks @volkanceylan now it's working fine, but now in another dialog I've a problem with a null field.
My dialog has some fields HideOnInsert(true) or HideOnUpdate(true) and viceversa: this is because at the moment of the creation of a new item I show a couple of (prefiltered) select, but instead on further updates I only show the readonly value (I mean description value and not the Id).
So the hidden value (that are Ids....FK to other table for the records) becames automatically null...I'm doing something wrong or it's the correct behaviour?

Thanks

**Comment by volkanceylan** [comment]
I dont understand but behavior of hidden fields are same with visible ones.

**Comment by marcobisio** [comment]
I'm in the following situation:
![image](https://cloud.githubusercontent.com/assets/17425690/13949229/25dae0f0-f024-11e5-878f-5cb3dacb4738.png)

and my form is the following:
![image](https://cloud.githubusercontent.com/assets/17425690/13949270/5a28f3ce-f024-11e5-998b-660f21527661.png)

Here I show mutually the EquipmentId (with a lookup) in insert mode or the attribute (Knumber) in update mode.
To do that if I have the following code in TicketRow.cs:
![image](https://cloud.githubusercontent.com/assets/17425690/13949327/ab2157e4-f024-11e5-8cf7-696bac6e9ace.png)
and
![image](https://cloud.githubusercontent.com/assets/17425690/13949350/ca356918-f024-11e5-811a-68468fc42385.png)



So seems that when the EquipmentId field is hidden, that value is set to null (even if the user cannot change it).

Thanks for your support

**Comment by marcobisio** [comment]
One more (important) detail: the lookup is filtered in a way that may not contain the value already set in the ticket.
This is in order to allow user to see ALL tickets but to create only in a specific subset of countries, sites and equipments.

**Comment by volkanceylan** [comment]
If you don't want those hidden fields to change something, why you put them in the form in the first place?

Put [OneWay] attribute if you don't want them to be serialized.

**Comment by marcobisio** [comment]
Because I have only one form for both insert and update....
So I have to put them in the form in insert mode and then hide them in update mode...is this correct?
If I put [OneWay] attribute then they will not even be serialized during creation...i'm right?

**Comment by volkanceylan** [comment]
Hmm, if so update GetSaveEntity method in dialog and delete one you don't want from entity. Type.DeleteField etc.

**Comment by marcobisio** [comment]
Just got a warning for deprecated method...this is what I have done:

protected override TicketRow GetSaveEntity()
        {
            if (IsEditMode)
            {
                Script.Delete(Entity, TicketRow.Fields.EquipmentId);
            }
            return base.GetSaveEntity();
        }

Sounds good?

Thanks

**Comment by volkanceylan** [comment]
No, 

var entity = base.GetSaveEntity();
if (IsEditMode)
     Script.Delete(entity, ...)
return entity;

**Comment by volkanceylan** [comment]
You were deleting from dialog's loaded entity, which is not good.

**Comment by marcobisio** [comment]
Ohhh you're right...I'm a bit tired :-(
Done and perfectly working now!!

Thank you very much @volkanceylan 
P.S. If there is a way (I mean a place) to collect all information, I would be happy to collect them to make them available to other users of Serenity

**Comment by volkanceylan** [comment]
You're welcome. You may put them in Wiki here as a page.

**Comment by marcobisio** [comment]
ok thanks! I will do it!

**Comment by marcobisio** [comment]
Another problem... :-(
My Old.NoteList (the childs) is always null...I'm testing it in the AfterSave() method of MySaveHandler...
The Row.NoteList instead contains all the updated notes...
Any ideas?

Thanks

**Comment by volkanceylan** [comment]
You should load it yourself.

**Comment by marcobisio** [comment]
ahhhh...ah I had misunderstood your "...Make sure you load old children rows..."
Sorry for that...

Thanks
