### ISSUE TITLE
Error after upgrading to 3.4

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#4430]
After the upgrade, we are getting below error
"In 'const' enum declarations member initializer must be constant expression" in generated TypeScript row file.  

Please see below screenshot for the error: 

![image](https://user-images.githubusercontent.com/25874638/57156803-87af7d80-6da4-11e9-9f80-3fd2ddf2f414.png)

TS Version: 2.4

Please share your experience to solve this issue.

**Comment by rcruzfalcon** [comment]
Hi @XDDDev 

Take a look to this issue:
        https://github.com/volkanceylan/Serenity/issues/3171
best regards.

**Comment by JohnRanger** [comment]
@XDDDev ,

as this has been answered above, would you mind to close your issue? :-)

with kind regards,

John
