### ISSUE TITLE
set value Field in Dialog when lookupeditor dropdown changes

### ISSUE THREAD

**Issue by GitHubOrim** [volkanceylan/Serenity#4432]
![grafik](https://user-images.githubusercontent.com/25506715/57166779-89f0f680-6dfb-11e9-8973-b87c51707ffd.png)

How can i update the field values OwnerDomain and OwnerAccount on selecting dropdown... in which function store the code
THX

**Comment by minhhungit** [comment]
Add bellow code in your Dialog.ts
```javascript
this.form.NewOwnerAccount.change(e => {
    // do anything here, for example:
    Serenity.EditorUtils.setValue(this.form.OwnerDomain, 'YOUR_VALUE');
});
```

**Comment by minhhungit** [comment]
or using .changeSelect2

**Comment by GitHubOrim** [comment]
> 
> 
> or using .changeSelect2

Thanks both change and changeSelect2 works. But only if i set LookupEditor to Autocomplete = true;
Want to have --select-- in DropDown... But if Autocomplete = false nothing happens on change or changeSelect2
THX
