### ISSUE TITLE
Migration Order

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4435]
It seems that migration are not running in order.
I have migration 190429 running before migrations from 2018, so that it errors out on nonexisting tables :(
How are migration sorted, what could be causing this?

Yeah, it's confirmed. From the Version table:
As first migration is run the last one (2019042914270)
and only as second is the first migration (20141103140000)

I have FluentMigrator.runner ver 1.6.2.
I remember trying to use newer, but there were some problems when updating
Could that be the problem?

**Comment by edwardch** [comment]
I know you've closed this issue in the other project, but this is just for the other users...

2019042914270
is less than
20141103140000

You left out a **0** at the end of the migration starting with "2019...", so the "2019..." script will run first.

**Comment by ga5tan** [comment]
yes, thank you
