### ISSUE TITLE
Inline create records in detail section

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4436]
Hello @volkanceylan,
I want a form where I can create records in the inline editable grid in the detail section. 
I know the inline grid is an option which is not fully supported by serenity as its mentioned in the samples
Is there any different subscription for such samples?

**Comment by wezmag** [comment]
You need to rewrite the detail editor.
Check out the Northwind Order sample below, the code is not tested.
Just to demonstrate the idea.
You also need to change ProductID text input to select2 input


``` typescript
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Serene2.Northwind {

    import fld = OrderDetailRow.Fields;

    @Serenity.Decorators.registerClass()
    export class OrderDetailsEditor extends Common.GridEditorBase<OrderDetailRow> {
        protected getColumnsKey() { return "Northwind.OrderDetail"; }
        protected getDialogType() { return OrderDetailDialog; }
        protected getLocalTextPrefix() { return OrderDetailRow.localTextPrefix; }

        private pendingChanges: Q.Dictionary<any> = {};

        constructor(container: JQuery) {
            super(container);
            this.slickContainer.on('change', '.edit:input', (e) => this.inputsChange(e));
            this.element.find('.s-Toolbar').toggle(false);
        }

        protected getColumns() {
            var columns = super.getColumns();
            var num = ctx => this.numericInputFormatter(ctx);
            var int = ctx => this.integerInputFormatter(ctx);
            var str = ctx => this.stringInputFormatter(ctx);

            Q.first(columns, x => x.field === fld.ProductID).format = int;
            Q.first(columns, x => x.field === fld.UnitPrice).format = num;
            Q.first(columns, x => x.field === fld.Discount).format = num;
            Q.first(columns, x => x.field === fld.Quantity).format = int;

            columns.splice(0, 0, {
                field: '#',
                name: '#',
                width: 28,
                minWidth: 28,
                maxWidth: 28,
                format: ctx => '<div style="padding:0 3px">' + (ctx.row + 1).toString() + '</div>',
                sortable: false,
                headerCssClass: 'align-center',
                cssClass: 'align-right'
            });

            columns.splice(columns.length, 0, {
                field: 'Add',
                name: '',
                format: ctx => '<a class="inline-action add-row" title="Add"><i class="fa fa-fw fa-plus text-success"></i></a>',
                width: 28,
                minWidth: 28,
                maxWidth: 28
            });

            columns.splice(columns.length, 0, {
                field: 'Delete',
                name: '',
                format: ctx => '<a class="inline-action delete-row" title="Delete"><i class="fa fa-fw fa-minus text-danger"></i></a>',
                width: 28,
                minWidth: 28,
                maxWidth: 28
            });

            return columns;
        }

        private inputsChange(e: JQueryEventObject) {
            var cell = this.slickGrid.getCellFromEvent(e);
            var item = this.itemAt(cell.row);
            var input = $(e.target);
            var field = input.data('field');
            var text = Q.coalesce(Q.trimToNull(input.val()), '0');
            var pending = this.pendingChanges[item.__id];

            var effective = this.getEffectiveValue(item, field);
            var oldText: string = input.hasClass('numeric')
                ? Q.formatNumber(effective, '0.00')
                : effective as string;

            var value;
            if (field === fld.UnitPrice || field === fld.Discount) {
                value = Q.parseDecimal(text);
                if (value == null || isNaN(value)) {
                    Q.notifyError(Q.text('Validation.Decimal'), '', null);
                    input.val(oldText);
                    input.focus();
                    return;
                }
            }
            else if (input.hasClass('numeric')) {
                var i = Q.parseInteger(text);
                if (isNaN(i) || i > 32767 || i < 0) {
                    Q.notifyError(Q.text('Validation.Integer'), '', null);
                    input.val(oldText);
                    input.focus();
                    return;
                }
                value = i;
            }
            else {
                value = text;
            }

            if (!pending) {
                this.pendingChanges[item.__id] = pending = {};
            }

            pending[field] = value;
            item[field] = value;
            this.view.refresh();

            if (input.hasClass('numeric'))
                value = Q.formatNumber(value, '0.00');

            if (input.hasClass('integer'))
                value = Q.formatNumber(value, '0');

            input.val(value).addClass('dirty');
        }

        private getEffectiveValue(item, field: any): any {
            var pending = this.pendingChanges[item.__id];
            if (pending && pending[field] !== undefined) {
                return pending[field];
            }

            return item[field];
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                if (target.hasClass('add-row')) {
                    let newEntity = this.getNewEntity();
                    let newRequest: Serenity.SaveRequest<OrderDetailRow> = {
                        Entity: newEntity
                    };
                    this.save({ request: newRequest }, () => {
                    });
                }
                else if (target.hasClass('delete-row')) {
                    if (this.element.find('a.delete-row').length === 1) {
                        return;
                    }
                    this.deleteEntity(item.__id);
                }
            }
        }

        protected onViewProcessData(response) {
            this.pendingChanges = {};
            return super.onViewProcessData(response);
        }

        public setEditValue(source: OrderRow, property) {
            if (source.DetailList === undefined) {
                source.DetailList = [{}];
            }

            super.setEditValue(source, property);
        }

        private numericInputFormatter(ctx) {
            var klass = 'edit numeric';
            var item = ctx.item;
            var pending = this.pendingChanges[item.__id];

            if (pending && pending[ctx.column.field] !== undefined) {
                klass += ' dirty';
            }
            var value = this.getEffectiveValue(item, ctx.column.field) as number;
            return value === undefined
                ? "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='' />"
                : "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='" + Q.formatNumber(value, '0.00') + "' />";
        }

        private integerInputFormatter(ctx) {
            var klass = 'edit numeric integer';
            var item = ctx.item;
            var pending = this.pendingChanges[item.__id];

            if (pending && pending[ctx.column.field] !== undefined) {
                klass += ' dirty';
            }
            var value = this.getEffectiveValue(item, ctx.column.field) as number;
            return value === undefined
                ? "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='' />"
                : "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='" + Q.formatNumber(value, '0') + "' />";
        }

        private stringInputFormatter(ctx) {
            var klass = 'edit string';
            var item = ctx.item;
            var pending = this.pendingChanges[item.__id];
            var column = ctx.column as Slick.Column;

            if (pending && pending[column.field] !== undefined) {
                klass += ' dirty';
            }
            var value = this.getEffectiveValue(item, column.field) as string;
            return "<input type='text' required class='" + klass +
                "' data-field='" + column.field +
                "' value='" + Q.attrEncode(value) +
                "' maxlength='" + column.sourceItem.maxLength + "' />";
        }
    }
}
```

**Comment by Shraddha996** [comment]
hey! Thanks @wezmag  I'll try it

**Comment by Shraddha996** [comment]
Hello! @wezmag  I modified my code using your suggested code
but its shows error whenever I try to type in the textbox(ItemName)
Please Help!

**My code**
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace ABC.Books {

    import fld = ABC.Books.TblSalesInvoiceTranRow.Fields

    @Serenity.Decorators.registerClass()
    export class TblSalesInvoiceEditor extends Common.GridEditorBase<TblSalesInvoiceTranRow> {
        protected getColumnsKey() { return "Books.TblSalesInvoiceTran"; }
        protected getDialogType() { return TblSalesInvoiceTranDialog; }
        protected getLocalTextPrefix() { return TblSalesInvoiceTranRow.localTextPrefix; }

        private pendingChanges: Q.Dictionary<any> = {};

        constructor(container: JQuery) {
            super(container);
            this.getGrid().onKeyDown.subscribe((e, p) => {
                    var item = this.getView().getItem(p.row);
                var id = item[this.getIdProperty()].toString();
                var AccountId = item.AccountId;
            });
            this.slickContainer.on('change', '.edit:input', (e) => this.inputsChange(e));
            this.element.find('.s-Toolbar').toggle(false);
        }

        protected getColumns() {
            var columns = super.getColumns();
            var num = ctx => this.numericInputFormatter(ctx);
            var str = ctx => this.stringInputFormatter(ctx);

            Q.first(columns, x => x.field === 'ItemName').format = str;

            var category = Q.first(columns, x => x.field === fld.AccountName);
            category.referencedFields = [fld.AccountId];
            category.format = ctx => this.selectFormatter(ctx, fld.AccountId, TblAccountRow.getLookup());

            var supplier = Q.first(columns, x => x.field === fld.VatRateName);
            supplier.referencedFields = [fld.VatRateId];
            supplier.format = ctx => this.selectFormatter(ctx, fld.VatRateId, TblVatRateRow.getLookup());

            Q.first(columns, x => x.field === fld.Quantity).format = num;
            Q.first(columns, x => x.field === fld.UnitPrice).format = num;
            //Q.first(columns, x => x.field === fld.Net).format = num;
            Q.first(columns, x => x.field === fld.SubTotal).format = num;


            columns.splice(0, 0, {
                field: '#',
                name: '#',
                width: 28,
                minWidth: 28,
                maxWidth: 28,
                format: ctx => '<div style="padding:0 3px">' + (ctx.row + 1).toString() + '</div>',
                sortable: false,
                headerCssClass: 'align-center',
                cssClass: 'align-right'
            });

            columns.splice(columns.length, 0, {
                field: 'Add',
                name: '',
                format: ctx => '<a class="inline-action add-row" title="Add"><i class="fa fa-fw fa-plus text-success"></i></a>',
                width: 28,
                minWidth: 28,
                maxWidth: 28
            });

            columns.splice(columns.length, 0, {
                field: 'Delete',
                name: '',
                format: ctx => '<a class="inline-action delete-row" title="Delete"><i class="fa fa-fw fa-minus text-danger"></i></a>',
                width: 28,
                minWidth: 28,
                maxWidth: 28
            });

            return columns;
        }


        private inputsChange(e: JQueryEventObject) {
            var cell = this.slickGrid.getCellFromEvent(e);
            var item = this.itemAt(cell.row);
            var input = $(e.target);
            var field = input.data('field');
            var text = Q.coalesce(Q.trimToNull(input.val()), '0');
            var pending = this.pendingChanges[item.__id];

            var effective = this.getEffectiveValue(item, field);
            var oldText: string = input.hasClass('numeric')
                ? Q.formatNumber(effective, '0.00')
                : effective as string;

            var value;
            if (field === fld.UnitPrice || field === fld.Quantity) {
                value = Q.parseDecimal(text);
                if (value == null || isNaN(value)) {
                    Q.notifyError(Q.text('Validation.Decimal'), '', null);
                    input.val(oldText);
                    input.focus();
                    return;
                }
            }
            else if (input.hasClass('numeric')) {
                var i = Q.parseInteger(text);
                if (isNaN(i) || i > 32767 || i < 0) {
                    Q.notifyError(Q.text('Validation.Integer'), '', null);
                    input.val(oldText);
                    input.focus();
                    return;
                }
                value = i;
            }
            else {
                value = text;
            }

            if (!pending) {
                this.pendingChanges[item.__id] = pending = {};
            }

            pending[field] = value;
            item[field] = value;
            this.view.refresh();

            if (input.hasClass('numeric'))
                value = Q.formatNumber(value, '0.00');

            if (input.hasClass('integer'))
                value = Q.formatNumber(value, '0');

            input.val(value).addClass('dirty');
        }

        private getEffectiveValue(item, field: any): any {
            var pending = this.pendingChanges[item.__id];
            if (pending && pending[field] !== undefined) {
                return pending[field];
            }

            return item[field];
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                if (target.hasClass('add-row')) {
                    let newEntity = this.getNewEntity();
                    let newRequest: Serenity.SaveRequest<TblSalesInvoiceTranRow> = {
                        Entity: newEntity
                    };
                    this.save({ request: newRequest }, () => {
                    });
                }
                else if (target.hasClass('delete-row')) {
                    if (this.element.find('a.delete-row').length === 1) {
                        return;
                    }
                    this.deleteEntity(item.__id);
                }
            }
        }

        protected onViewProcessData(response) {
            this.pendingChanges = {};
            return super.onViewProcessData(response);
        }

        public setEditValue(source: TblSalesInvoiceRow, property) {
            if (source.DetailList === undefined) {
                source.DetailList = [{}];
            }

            super.setEditValue(source, property);
        }

        private numericInputFormatter(ctx) {
            var klass = 'edit numeric';
            var item = ctx.item as TblSalesInvoiceTranRow;
            var pending = this.pendingChanges[item.SalesInvoiceTranId];

            if (pending && pending[ctx.column.field] !== undefined) {
                klass += ' dirty';
            }

            var value = this.getEffectiveValue(item, ctx.column.field) as number;

            return "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='" + Q.formatNumber(value, '0.##') + "'/>";
        }

        private integerInputFormatter(ctx) {
            var klass = 'edit numeric integer';
            var item = ctx.item;
            var pending = this.pendingChanges[item.__id];

            if (pending && pending[ctx.column.field] !== undefined) {
                klass += ' dirty';
            }
            var value = this.getEffectiveValue(item, ctx.column.field) as number;
            return value === undefined
                ? "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='' />"
                : "<input type='text' class='" + klass +
                "' data-field='" + ctx.column.field +
                "' value='" + Q.formatNumber(value, '0') + "' />";
        }

        private stringInputFormatter(ctx) {
            var klass = 'edit string';
            var item = ctx.item as TblSalesInvoiceTranRow;
            var pending = this.pendingChanges[item.SalesInvoiceTranId];
            var column = ctx.column as Slick.Column;

            if (pending && pending[column.field] !== undefined) {
                klass += ' dirty';
            }

            var value = this.getEffectiveValue(item, column.field) as string;

            return "<input type='text' class='" + klass +
                "' data-field='" + column.field +
                "' value='" + Q.attrEncode(value) +
                "' maxlength='" + column.sourceItem.maxLength + "'/>";
        }

        private selectFormatter(ctx: Slick.FormatterContext, idField: string, lookup: Q.Lookup<any>) {
            var klass = 'edit';
            var item = ctx.item as TblSalesInvoiceTranRow;
            var pending = this.pendingChanges[item.SalesInvoiceTranId];
            var column = ctx.column as Slick.Column;

            if (pending && pending[idField] !== undefined) {
                klass += ' dirty';
            }

            var value = this.getEffectiveValue(item, idField);
            var markup = "<select class='" + klass +
                "' data-field='" + idField +
                "' style='width: 100%; max-width: 100%'>";
            for (var c of lookup.items) {
                let id = c[lookup.idField];
                markup += "<option value='" + Q.attrEncode(id) + "'"
                if (id == value) {
                    markup += " selected";
                }
                markup += ">" + Q.htmlEncode(c[lookup.textField]) + "</option>";
            }
            return markup + "</select>";
        }
        

    }
}`


**ERROR**
![Screenshot (27)](https://user-images.githubusercontent.com/39983941/57443541-ef197180-726b-11e9-9844-fd137c8254d9.png)

**Comment by Shraddha996** [comment]
@wezmag also one question 
can we add validations to that inline fields?

**Comment by rcruzfalcon** [comment]
Hi @Shraddha996 , if you getIdProperty() is default "__id", you must add this field to the new Entity for used  in grid.
You can use the method setNewId and send the new Entity like parameter.

best regards.

**Comment by rcruzfalcon** [comment]
About add validations, you can add the controls to form validator and will be validate when try to save the Dialog.

**Comment by wezmag** [comment]
@Shraddha996 This is the problematic part.
```
this.getGrid().onKeyDown.subscribe((e, p) => {
        var item = this.getView().getItem(p.row);
        var id = item[this.getIdProperty()].toString();
        var AccountId = item.AccountId;
});
```
The `item` is undefined. Actually `p` is also undefined.
You need to fix it yourself.

For validation, you can validate input in `inputsChange` method, or override `validateEntity` method which is inherit from `GridEditorBase`

**Comment by wezmag** [comment]
@Shraddha996  Just spent some time digging in.
You can do this in your onKeyDown code to get `item`.
``` typescript
this.getGrid().onKeyDown.subscribe((e, p) => {
    var cell = this.slickGrid.getCellFromEvent(e);
    var item = this.itemAt(cell.row);
    console.log(item);
});
```
You can always use Developer Tools (F12) to find out which part of your code causes problem.

**Comment by Shraddha996** [comment]
@wezmag thank you so much! now it's working fine Now am working for validations do you have any reference issue link or something.

**Comment by wezmag** [comment]
@Shraddha996 
For required field validation, try add `required` and `name` attribute to the input.
`name='" + ctx.column.field + item.__id + "' required`
The build-in validator will handle the rest.
This is what I have done...
```
return value === undefined
    ? "<input type='text' name='" + ctx.column.field + item.__id + "' required class='" + klass +
    "' data-field='" + ctx.column.field +
    "' value='' />"
    : "<input type='text' name='" + ctx.column.field + item.__id + "' required class='" + klass +
    "' data-field='" + ctx.column.field +
    "' value='" + Q.formatNumber(value, '0') + "' />";
```

**Comment by Shraddha996** [comment]
hello, @wezmag Thanks for the validation code.
Actually, I stuck while saving the open grid value
As you know I created an open grid for my transaction section but after saving the value the transaction table is empty and it doesn't store any value in it

**Comment by Shraddha996** [comment]
Hello @wezmag  Please kindly look towards my issue #4518
