### ISSUE TITLE
DynJS.axd - Unable to Load Bundles

### ISSUE THREAD

**Issue by glenngsanchez** [volkanceylan/Serenity#4438]
Hi All,

I'm just trying to build an app from scratch. when run in visual studio, i dont see any problem.  But when I try do deploy to IIS Server, Im getting the below error from console.

![image](https://user-images.githubusercontent.com/23032787/57437053-9057f600-7273-11e9-85c3-71ce3100bf00.png)

May I know where the problem is coming from and how to fix this?

Thank You!

**Comment by mafdy** [comment]
Add the following to your web.config.
```
<add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />
```

**Comment by glenngsanchez** [comment]
> Add the following to your web.config.
> 
> ```
> <add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />
> ```

Hi mafdy,  
thanks for the prompt reply. I already got this in the default project's webconfig.

![image](https://user-images.githubusercontent.com/23032787/57441330-49223300-727c-11e9-81bd-0789807a4f65.png)

**Comment by volkanceylan** [comment]
Your server might not be in Integrated mode, or very old IIS

**Comment by YYOHAN** [comment]
Remove the forward slash  ("/") from DynJS.axd . It should be as mafdy user told you in a previous suggestion.

**Comment by YYOHAN** [comment]
This question was answered before.
https://github.com/volkanceylan/Serenity/issues/4424

**Comment by YYOHAN** [comment]
If it is working fine in your development computer, the problem might be with your web.config file.
If you have a forward slash (/) in front of DynJS.axd, Remove it!. Use:
<add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />

**Comment by glenngsanchez** [comment]
> > Add the following to your web.config.
> > ```
> > <add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />
> > ```
> 
> Hi mafdy,
> thanks for the prompt reply. I already got this in the default project's webconfig. But still the issue persist.
> 
> ![image](https://user-images.githubusercontent.com/23032787/57441330-49223300-727c-11e9-81bd-0789807a4f65.png)

I did not notice that "/" . thanks mafdy.

**Comment by glenngsanchez** [comment]
> This question was answered before.
> #4424

Many thanks for pointing me to the previous issue raised @YYOHAN.
