### ISSUE TITLE
How to Increase the Maximum File Upload Size

### ISSUE THREAD

**Issue by alak447** [volkanceylan/Serenity#4439]
Hi, I'm new in Serenity MVC. Please help me how to increase the maximum file upload size

**Comment by volkanceylan** [comment]
Nee user please learn to use search in github

**Comment by alak447** [comment]
Thanks for the help

**Comment by aurony** [comment]
Please use below code under <system.web>
<httpRuntime targetFramework="4.5" maxRequestLength="10240000" executionTimeout="100000" />
