### ISSUE TITLE
Template dialog bool option not passed if false

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#4440]
Hi @volkanceylan in this line of Widget.ts

https://github.com/volkanceylan/Serenity/blob/3a13f38934dbd0eec397f3d37f7b003524d65d53/Serenity.Scripts/CoreLib/UI/Widgets/Widget.ts#L53

if I pass an option of type bool as false, the option is set to ({} as TOptions) then a test if (this.options) fail (is always true).

IMHO is better 

```ts
    this.options = options != undefined || ({} as TOptions);
```

**Comment by volkanceylan** [comment]
Yes, but options are supposed to be an object, not a value type

**Comment by Estrusco** [comment]
Ah ok, I thinking that but not sure. I move the value into an interface. Tnx guy 👍
