### ISSUE TITLE
Dialog Buttons not responsive

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4443]
Hi,

I have couple of buttons in dialog and once I view it in phone, buttons are smashed together and does not look good:

![image](https://user-images.githubusercontent.com/36483170/57649579-ef49a200-75c8-11e9-8bd4-d3f8245091b1.png)

any idea how that can be fixed?

**Comment by karimQasem** [comment]
show me your code

**Comment by ga5tan** [comment]
Hi @karimQasem 
I have a update.
I used separator = true when adding button (as seen in Northwind/orders), which helped to split buttons into groups and they break better, but still the outer container does not stretch and it's lower boundary line cuts trough second line of buttons.
I ended up hacking LESS file and adding min-height: auto; for toolbar. It's not proper, as the bottom border line is touching bottom of second line of buttons, but it's has to do for now.
