### ISSUE TITLE
How Get More Details from Active Directory

### ISSUE THREAD

**Issue by ShahzanSyed** [volkanceylan/Serenity#4444]
Hello,
I have a dialog to add a request. I want to AutoFill some of the fields of this dialog with the details of Requester like Mob. No, Business Unit, Emp Id [coming from AD of the Org.]
I'm able to AutoFill the Requester Name in Dialog using below:-
`Serenity.EditorUtils.setValue(this.form.EmployeeName, Authorization.userDefinition.DisplayName);`

I have made the changes in the following files to include data for other Requester fields from AD :

ActiveDirectoryService.cs [ Validate()] - Returns a DirectoryEntry
DirectoryEntry.cs
UserDefinition.cs
ScriptUserDefinition.cs

Can anyone help me where else to make changes in order to get the remaining details AutoFilll on the dialog? Thanks

**Comment by ShahzanSyed** [comment]
@volkanceylan would appreciate if you could provide your inputs on this. Thanks, much!!

**Comment by wezmag** [comment]
It's hard to imagine what changes you had made to those files so far.

I can only give you a rough idea.
1. Add additional fields to Users table
2. Add additional fields to `UserRow.cs`, `DirectoryEntry.cs`, `UserDefinition.cs`, `ScriptUserDefinition.cs`
3. In `ActiveDirectoryService.cs`, `Validate` method, try to retrieve the additional fields value from `identity` and return the values in `DirectoryEntry` entity.
4. In `AuthenticationService.cs`, `ValidateExistingUser` and `ValidateFirstTimeUser` methods, save the values retrieved from Active Directory to Users table.
5. In `UserRetrieveService.cs`, `GetFirst` method, return additional fields values in `UserDefinition` entity.
6. In `UserEndpoint.cs`, `GetUserData` method, return additional fields values in `ScriptUserDefinition` entity

Build the project and run T4 template.

You can now get additional field value in `Authorization.userDefinition`

**Comment by ShahzanSyed** [comment]
Thanks for your comment @wezmag 

I was able to achieve this yesterday. These are the changes I made in the application :

1. Added New Columns in Database Table
2. Added Fields in UserRow, UserColumns, UserForm, DirectoryEntry.cs, ScriptUserDefinition and UserDefinition

3. Changed the `Validate() of ActiveDirectory.cs`  to retrieve additional fields like below 
`var identity = UserPrincipal.FindByIdentity(context, IdentityType.SamAccountName, username);

                Entry.DirectoryEntry up_de = (Entry.DirectoryEntry)identity.GetUnderlyingObject();
                Entry.DirectorySearcher deSearch = new Entry.DirectorySearcher(up_de);
                deSearch.PropertiesToLoad.Add("mobile");
                deSearch.PropertiesToLoad.Add("department");
                string mobile = "", dept = "";
                Entry.SearchResultCollection results = deSearch.FindAll();
                if (results != null && results.Count > 0)
                {
                    Entry.ResultPropertyCollection rpc = results[0].Properties;
                    foreach (string rp in rpc.PropertyNames)
                    {
                        if (rp == "mobile")
                            mobile = rpc["mobile"][0].ToString();

                        if (rp == "department")
                            dept = rpc["department"][0].ToString();
                    }
                    return new DirectoryEntry
                    {
                        Username = identity.SamAccountName.ToUpper(), // #DWPlusCutover
                        Email = identity.EmailAddress.TrimToNull(),
                        FirstName = identity.GivenName,
                        LastName = identity.Surname,
                        EmployeeId = identity.EmployeeId,
                        WorkPhone = identity.VoiceTelephoneNumber,
                        MobileNumber = mobile,
                        BU = dept

                    };
                }`

4. Change `ValidateFirstTimeUser` of `AuthenticationService.cs`  to save the new fields retrieved from AD into Users Table
5. Change `GetUserData` of `UserEndpoint.cs` to include new fields - Here I was not getting new fields from UserDefinition as I didn't make changes in `UserRetrieveService.cs,` `GetFirst`  and run T4 Template (thanks for this), so I add code to query DB for that user and get the details. 

I'll now other changes mentioned by you. Thanks a lot for your help.

**Comment by JohnRanger** [comment]
Hi @ShahzanSyed ,

would it be ok for you to write a short wiki article here in the forum when you have a fully working solution? (So others can profit too :-))?

With kind regards,

John
