### ISSUE TITLE
Index.cshtml de ki gi bi Dialog.Themlate.html içinde Model nasıl kullanırım?

### ISSUE THREAD

**Issue by ubuluCRM** [volkanceylan/Serenity#4445]
Index.cshtml de bulunan 
örnek:
`@model ViewModel<Entities.TanimBankaHesapRow, Entities.TanimBankaHesapAyarRow>
@

            @{ if (Model.serverMvc.modul.IsMuhasebe){ }@
                < li>< a href="#TabPosGrid" data-toggle="tab"><i class="icon16x16 iconssite-pos">< /i>POSlar< /a>< /li>
`
şeklinde yazdığımda çalıştırabiliyorum.

Aynı şekilde Dialog.Themlate.html içinde yapmak istiyorum bu şekilde yazdığımda ekrana string olarak kodlar görünüyor. Dialog.Themlate.html de Index.cshtml de olduğu gibi nasıl yazabilirim?

**Comment by ga5tan** [comment]
I believe there would be much more people to help you if you would use EN language
