### ISSUE TITLE
Using scriban as report at production

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#4446]
Hey @volkanceylan 

Scriban is amazing!

I would like to know if exists a way to use scriban in Serenity Web in production.

The purpose is generate medical prescriptions from a scriban template.

Thanks in advanced

**Comment by volkanceylan** [comment]
If i understand correctly, you want to use scriban instead of cshtml right? In that case, where you should change is ReportController.cs. In RenderAsHtml method, check if designAttr.Design has the extension ".scriban", if so use Scriban engine to generate the HTML.

**Comment by rolembergfilho** [comment]
Thanks!!!
