### ISSUE TITLE
how to map the db fields to the property with different name?

### ISSUE THREAD

**Issue by csabc** [volkanceylan/Serenity#4448]
if the db fields have different name ,how can i map to the property? eg..
id -->UserId 
id is db field ,UserId is a property in c# class.
how can i do ?

**Comment by wezmag** [comment]
Use [Column](https://github.com/volkanceylan/Serenity/wiki/Entity-Framework:-ColumnAttribute-%5BMapping%5D) attribute
``` csharp
[Column("id")]
public Int32? UserId
{
   get { return Fields.UserId[this]; }
   set { Fields.UserId[this] = value; }
}
```

**Comment by csabc** [comment]
thanks，but i want to use dapper.sqlmapper.update，so the property must keep consistent with db fields。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by volkanceylan** [comment]
In that case you can't use Dapper with Row.
