### ISSUE TITLE
ORA-00911: invalid character

### ISSUE THREAD

**Issue by yaseenhejazi** [volkanceylan/Serenity#4449]
Is there any way to remove semicolon from end of SQL statement as it cause Oracle database to return this error:
ORA-00911: invalid character

**Comment by csabc** [comment]
download source code ,remove it yourself.

**Comment by yaseenhejazi** [comment]
I am using serene project template under Visual Studio 2019

I copied the source code from GitHub and try to build it but got error in Serenity.CodeGenerator project

Also can help on how to use the GutHub solution DLL files on my project?

**Comment by csabc** [comment]
i am using the version 3.9.5. it doesnot support oracle. so the only way is to build source code yourself.can you show errors.

**Comment by yaseenhejazi** [comment]
Only Serenity.CodeGenerator failed to build, all other project are built successfully
This the error:
Error code CS0433: The type 'Assembly' exists in both 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Serenity.CodeGenerator (netcoreapp2.2)	C:\Users\yaseen.hejazi\source\repos\Serenity-master\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs

But how to replace NuGet serenity packages with DLL files from GitHub downloaded solution?

**Comment by csabc** [comment]
you can  explicitly use System.Reflection.Assembly to replace Assembly.

**Comment by kilroyFR** [comment]
I am using Oracle for years with serenity right now and not having this kind of issue. 
Would be glad to help but please provide more informations (using Code gen ? serene ? other ?)

**Comment by volkanceylan** [comment]
I guess his issue is about using a reserved keyword as column name / table name, or a different version of Oracle.
