### ISSUE TITLE
BUG?: How to get rid of Add button?

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4450]
Hi

in my Row I have following permissions:

[ReadPermission("?")]
    [InsertPermission(PermissionKeys.Administration.Modify)]
    [ModifyPermission(PermissionKeys.Administration.Modify)]

but there is still Add button on my grid, even though user does not have PermissionKeys.Administration.Modify.

Is this normal? What's the point of add button, when user cannot save new records? What am I doing wrong?

**Comment by edwardch** [comment]
Yes this is normal, you need to remove it in the grid.

See this wiki: [UI: Button handling](https://github.com/volkanceylan/Serenity/wiki/UI:-Button-handling)

In your xyzGrid.ts

```ts
protected getButtons() {
    var buttons = super.getButtons();

    buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);

    return buttons;
}
```

**Comment by minhhungit** [comment]
@edwardch's code will help you

just want to show you a demo for it
https://serenity.is/demo/BasicSamples/RemovingAddButton

using admin/serenity to login

**Comment by mafdy** [comment]
> Hi
> 
> in my Row I have following permissions:
> 
> [ReadPermission("?")]
> [InsertPermission(PermissionKeys.Administration.Modify)]
> [ModifyPermission(PermissionKeys.Administration.Modify)]
> 
> but there is still Add button on my grid, even though user does not have PermissionKeys.Administration.Modify.
> 
> Is this normal? What's the point of add button, when user cannot save new records? What am I doing wrong?

@minhhungit @edwardch 
I don't think that you guys get his point, I think that he meant if any serenity screen (Entity Grid) has neither add nor edit permissions related to the logged user by default add button must not visible. not by writing a hard-coded way to remove add button in some screen, as in this way Xyz screen in some case with show add Button if the logged user has required permission, in other case add Button will disappear if the logged user doesn't.

Unfortunately, this isn't handled in serenity (According to my knowledge).

@ga5tan  Maybe you can achieve this by creating GridBase and extend EntityGrid, then override GetButton method by check if current Entity screen and logged user have access to add or edit and then decide weather add Button will be added to the Button list or not. After that use your new GridBase to be inherited in all your screens (just brainstorming, didn't try it before).

**Comment by ga5tan** [comment]
@mafdy you got it right. 
I was able and eventually forced to hide button explicitly, but was wondering if maybe I missed some detail.
I must say I see it now as BUG rather than "feature". I feel, there are bunch of "less meaningful" features than this, which are working as expected.

**Comment by minhhungit** [comment]
@mafdy haa, sorry, honestly I just read comment of @edwardch 
@ga5tan  anyway, try this code:
```js
constructor(container: JQuery) {
    super(container);
	
    if (!Authorization.hasPermission("abc-xyz")) {
        $(".add-button").remove();
    }
}
```

**Comment by fwd079** [comment]
@minhhungit  this is a much better approach, however, adding an attribute to `XYZColumns.cs' or `XYZRow.cs` would've been even better approach in my view. Just add there and any Grid.ts getting that Row class would hide the Add button just by looking at permissions. But thank you for your approach as that's exactly what I ended up doing after looking around.

Regards.
