### ISSUE TITLE
Hide paging, search and sorting serenity in grid

### ISSUE THREAD

**Issue by nareshIntelegain** [volkanceylan/Serenity#4451]
How to Hide paging, search and sorting serenity in grid and at  which  place needs to update code for same.

**Comment by minhhungit** [comment]
Hi @nareshIntelegain, 

To hide grid pager, update **grid.ts** file:
```javascript
protected usePager() {
    return false;
}
```
To remove searchbox, you also need to update **grid.ts** file:
```javascript
protected createQuickSearchInput() {

}
```

About sorting, add **[Sortable(false)]** attribute on fields you want, either Row.cs or Column.cs
