### ISSUE TITLE
SaveRequestHandler constructor  and GetBehavior override

### ISSUE THREAD

**Issue by sottnik** [volkanceylan/Serenity#4453]
Currently the GetBehavior is called in the SaveRequestHandler constructor, where the IsCreate  and IsUpdate produce incorrect result as the RequestType is checked and Old member is properly processed only later on in execution of Process method.

Could you improve the SaveRequestHandler so the GetBehavior can react on IsCreate and IsUpdate? If the Behavior collection is needed right after construction there could be an optional parameter in it saying whether it's update or create. If not, then simply move the filling of the behavior collection right at the beginning of the Process method.
 
We had a case where we needed to include or exclude a behavior on LinkingSetRelation and MasterDetailRelation according to the type of the request. We could implement a workaround where we don't use the overrideable GetBehavior method, but rather fill the behavior directly (luckily it's protected and not private) in the BeforeSave override (before calling base.BeforeSave).

**Comment by volkanceylan** [comment]
I may consider moving it to Process method before ValidateRequest, though to need to check if it might cause any breaking changes.

Modifying behaviors list is a bit risky, as same handler might be used multiple times by calling Process in theory, but for usual workflow it won't probably occur.

For the moment, you could override ValidateRequest and write this.behaviors = GetBehaviors() before calling base method.
