### ISSUE TITLE
Grid overflows Copyright/footer

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4455]
I have this issue where when browser window height is smaller Grid wont get smaller that 4 rows and ultimately overflows footer/copyright.

image
![image](https://user-images.githubusercontent.com/36483170/58245395-f99c3680-7d54-11e9-90b2-fdbc315f2642.png)

This is also happening in latest 3.9.8 StartSharp solution I just generated. It only works nice in online demo (Where there is nice long scrollable grid):

![image](https://user-images.githubusercontent.com/36483170/58245417-0882e900-7d55-11e9-9e39-b8c19b58eab8.png)

any idea how to achieve that?

thx in advance

**Comment by ga5tan** [comment]
noone?
Can you please somebody check if you have the same problem or not?
First (nonworking) screenshot is from freshly generated MVC project in VS 2017

**Comment by JohnRanger** [comment]
Yep - I can confirm that I have the same issue here with Serene V3.9.6 in Chrome and IE11 (FF not tested) when resizing windows very small.

But who cares for the copyright notice when space is thight... :-)

John

**Comment by ga5tan** [comment]
screw copyright notice, it looks amateurish, but if I only knew how to enforce it to work like online, that would do it
