### ISSUE TITLE
Display data conditionwise in grid

### ISSUE THREAD

**Issue by nareshIntelegain** [volkanceylan/Serenity#4459]
I want to show only activestatus=true data in grid , 

Total 50 recodrs in table where 10 active and remaining 40 inactive , I want to show active only i.e. 10 only in grid, i implement the code below.

Its showing 10 only after adding below code but issue is when i am going to search from grid it shows both active and inactive as well i.e. 50

Also when i am going to paging it shows all i.e. 50.
And also when i am going to sort that time also it display all record .

Kindly help me for same.
 
  public ListResponse<EmplyeeRow> List(IDbConnection connection, ListRequest request)
        {
   ListResponse<EmplyeeRow> lst = new EmployeeRepository.MyListHandler().Process(connection, request);

 foreach (var item in lst.Entities.ToList())
                {
                    if (item.activestatus== False)
                    {
                        lst.Entities.Remove(item);
                    }
                    
                }

}

**Comment by edwardch** [comment]
You can do this in your list handler in your EmployeeRepository.cs file:

```cs
private class MyListHandler : ListRequestHandler<MyRow>
{
	protected override void ApplyFilters(SqlQuery query)
	{
		base.ApplyFilters(query);
		// Ignore inactive records
		query.Where(new Criteria(fld.activestatus) == 1);
	}
}
```

This will never show inactive records on the screen.

If you want to be able to filter them in the grid you can just add a QuickFilter flag to your EmployeeColumns.cs file:
```cs
[QuickFilter]
public Boolean activestatus { get; set; }
```

Good luck!

**Comment by nareshIntelegain** [comment]
Hey Edward,

It's working as expected. Thanks for help really appreciated!!.

Thanks
Naresh

**Comment by edwardch** [comment]
Glad it helped. Please close issue if you're happy...

**Comment by nareshIntelegain** [comment]
Thanks
