### ISSUE TITLE
Error in paging grid

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#446]
Hi Jaiq,

There is error when click arrow or change page number in paging grid, kindly your help?

![ser1](https://cloud.githubusercontent.com/assets/6382278/13962372/32f372e2-f093-11e5-997a-0d4f3e73750e.png)

Thanks

**Comment by VictorTomaili** [comment]
Look to sql dialect

**Comment by zerodev** [comment]
Yep as victor said had same issue
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_set_database_dialect_for_connections.html
