### ISSUE TITLE
Checkbox checked issue

### ISSUE THREAD

**Issue by Tushar5292** [volkanceylan/Serenity#4461]
**I have a slickgrid with a checkbox column. I want to capture the row id when the checkbox in the selected row is checked or unchecked. Attached is the script for slickgrid in my view I want when user checks the checkbox, active column in database should be set to true and when it is unchecked, Active column should be set to false.**

Please help.

**Comment by JohnRanger** [comment]
You will have to learn how slickgrid works. There is good information everywhere. Google is your friend. With that, you will find how to get the ID out of the event of the checked grid row (see your other question here in this forum).

Then you have to write a method in your xyzEndpoint.cs (server-side) which takes 2 parameters:
- The ID
- checked (true/false)

and then you have to do your c# code to update the relevant record within the correct ID to reflect checked/unchecked status.

After that, you will have to call your new endpoint via an AJAX call.

With kind regards,

John
