### ISSUE TITLE
How do I find CheckBox checked and unchecked events in editor

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4462]
hello everyone and @volkanceylan 
In my master-detail relation form am pushing value in grid2 on the checkbox OnClick event of grid1
![Capture8](https://user-images.githubusercontent.com/39983941/58413381-3db17300-8096-11e9-8604-16a3d2058ebc.PNG)
 As you can see  on click of **LENGTH 505** the value got inserted into 2nd grid i.e. **Length 404**

The problem is when I unchecked the same  characteristics Constant again it is adding same value in grid2

![Capture9](https://user-images.githubusercontent.com/39983941/58413759-33dc3f80-8097-11e9-9904-09d749d50a2f.PNG)

On the editor am unable to find checked and unchecked event 
Hope this information is enough
Any suggestion would be appreciated
Thank You!

Editor Code for reference

`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Serene1.DomesticOrder {

    @Serenity.Decorators.registerClass()
    export class TblNetworkCharacteristicsEditor extends Common.GridEditorBase<TblNetworkCharacteristicsRow> {
        protected getColumnsKey() { return "DomesticOrder.TblNetworkCharacteristics"; }
        protected getDialogType() { return TblNetworkCharacteristicsDialog; }
        protected getLocalTextPrefix() { return TblNetworkCharacteristicsRow.localTextPrefix; }

        private rowSelection: Serenity.GridRowSelectionMixin;

        constructor(container: JQuery) {
            super(container);
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
            var details: TblValueTranRow[] = [];
            this.getGrid().onClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-item check-box')) {
                    e.preventDefault();
                    var item = this.getView().getItem(p.row);//red and bomchar id
                    var id = item[this.getIdProperty()].toString();//id 1,2...
                        if (item != null) {
                            var bomchar = RnD.TblBomCharacteristicsRow.getLookup().items.filter(x => x.CharacteristicsId === item.CharacteristicsId);
                            for (var BOMCharDetails1 of bomchar) {
                                details.push({ BOMCharacteristicsId: BOMCharDetails1.BomCharacteristicsId, CharacteristicsValue: BOMCharDetails1.CharacteristicsValue });
                                var data = details;
                                var fieldAEditor = Q.findElementWithRelativeId(this.element, "DetailList1").tryGetWidget(Serene1.DomesticOrder.TblValueTranEditor);
                                fieldAEditor.value = data;
                            }
                            /////////////////////////////////to hide the radiobuttons after selection of CharValue
                        }
                }
                
            });
        }

        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));
            return columns;
        }
        protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            buttons.push({
                title: "Pick Characteristics Constant",
                cssClass: "add-button1",
                icon: "fa-plus",
                onClick: () => {
                    var dlg = new CharacteristicsCheckDialog();
                    dlg.onSuccess = (selected) => {
                        // filter already existing products
                        selected = selected.filter(x => !Q.any(this.view.getItems(), y => y.CharacteristicsId == x.CharacteristicsId));

                        for (var sel of selected) {
                            var item = <DomesticOrder.TblNetworkCharacteristicsRow>{
                                CharacteristicsId: sel.CharacteristicsId,
                                CharacteristicsCharacteristicsName: sel.CharacteristicsCharacteristicsName,
                            };

                            var id = this.getNextId();
                            item[this.getIdProperty()] = id;
                            this.view.addItem(item);
                        }

                        return true;
                    };
                    dlg.dialogOpen();
                }
            });
            return buttons;
        }
    }
}`

**Comment by luongnv6** [comment]
```csharp
this.getGrid().onClick.subscribe((e, p) => {
            if ($(e.target).hasClass('select-item check-box')) {
                e.preventDefault();
                var item = this.getView().getItem(p.row);//red and bomchar id
                var id = item[this.getIdProperty()].toString();//id 1,2...
if (this.rowSelection.getSelectedAsInt32().filter((v, i) => { return v == item.Id; }).length > 0){
                    if (item != null) {
                        var bomchar = RnD.TblBomCharacteristicsRow.getLookup().items.filter(x => x.CharacteristicsId === item.CharacteristicsId);
                        for (var BOMCharDetails1 of bomchar) {
                            details.push({ BOMCharacteristicsId: BOMCharDetails1.BomCharacteristicsId, CharacteristicsValue: BOMCharDetails1.CharacteristicsValue });
                            var data = details;
                            var fieldAEditor = Q.findElementWithRelativeId(this.element, "DetailList1").tryGetWidget(Serene1.DomesticOrder.TblValueTranEditor);
                            fieldAEditor.value = data;
                        }
                        /////////////////////////////////to hide the radiobuttons after selection of CharValue
                    }
            }
} else {////// remove item from details list}
            
        });
```

**Comment by Shraddha996** [comment]
@luongnv6  I tried this code but it always comes under else loop whether I checked or unchecked
Please help me through this
I just want an event for unchecking checkbox

**Comment by stixoffire** [comment]
this.getGrid().onClick.subscribe((e, p) => {

                this.setHilitedRows(e, p);
            });

       protected setHilitedRows(e: JQueryEventObject, p: any) {

            if ($(e.target).hasClass('select-item')) {
                e.preventDefault();
                let cellCurrent = this.slickGrid.getCellNode(p.row, p.cell);
                let currentRow = this.slickGrid.getDataItem(p.row);

                if (jQuery(cellCurrent).find('span').hasClass('checked')) {
                
                   //do stuff checked (uncheck it remove the class checked
                }
                else {
                   // do other stuff 
                }
            }
        }
