### ISSUE TITLE
Dialog Template subfolders path

### ISSUE THREAD

**Issue by ZioZenigata** [volkanceylan/Serenity#4463]
When I use template dialog (... Dialog.Template.html) with path with many subfolders, my dialog is not loaded. 

For example, up to these subfolders everything works:
~\Modules\Level0\Level1\Level2\Level3\Level3Dialog.ts
~\Modules\Level0\Level1\Level2\Level3\Level3Form.cs
~\Modules\Level0\Level1\Level2\Level3\Level0.Level1.Level2.Level3Dialog.Template.html

If you add an extra level, it doesn't work:
~\Modules\Level0\Level1\Level2\Level3\Level4\Level4Dialog.ts
~\Modules\Level0\Level1\Level2\Level3\Level4\Level4Form.cs
~\Modules\Level0\Level1\Level2\Level3\Level4\Level0.Level1.Level2.Level3.Level4Dialog.Template.html

Could you help me, please?

**Comment by wezmag** [comment]
Please check if the **classname** of Level4Dialog.ts matches the filename.
In my experience, you don't need to name your template file with such long name.
As long as the **classname** of you Level4Dialog.ts matches the filename, just "Level4Dialog.Template.html" should work.

In the official manual.
> By default, all templated widgets (EntityDialog also derives from TemplatedWidget class), looks for a template with their own **classname**. Thus, PersonDialog looks for a template with the name MovieDB.PersonDialog.Template.html, followed by PersonDialog.Template.html.


[https://serenity.is/docs/tutorials/movies/listing_movies_in_person_dialog](https://serenity.is/docs/tutorials/movies/listing_movies_in_person_dialog)

**Comment by ZioZenigata** [comment]
My Level4Dialog.Template.html is loaded correctly but using paths with many sub-folders, if I insert a grid in my ~\Modules\Level0\Level1\Level2\Level3\Level4\Level4Dialog.ts, I get this error:

slick.grid.js?v=1CYuU0jp0NSv1mspwAJtHA2:281 Uncaught Error: SlickGrid requires a valid container, [object Object] does not exist in the DOM.
    at init (slick.grid.js?v=1CYuU0jp0NSv1mspwAJtHA2:281)
    at new SlickGrid (slick.grid.js?v=1CYuU0jp0NSv1mspwAJtHA2:5131)
    at Level4Grid.DataGrid.createSlickGrid (DataGrid.ts:388)
    at Level4Grid.createSlickGrid (Level4Grid.ts:22)
    at Level4Grid.DataGrid [as constructor] (DataGrid.ts:61)
    at Level4Grid.EntityGrid [as constructor] (EntityGrid.ts:7)
    at new Level4Grid (Level4Grid.ts:6)
    at new Level4Dialog (Level4Dialog.ts:35)
    at SlickGrid.<anonymous> (ReachRoHsGrid.ts:67)
    at Event.notify (slick.core.js?v=BLCRBDx7U3jsEuDNgnEQkw2:144)

**Comment by ZioZenigata** [comment]
I found that if I use in Level4Dialog.Template.html :
<div id="~_**AnyNameGrid**"></div>

end in LevelDialog.ts:
private myGrid: Level4Grid;
constructor(opt: Level4Row) {
            super(opt);
            this.myGrid = new Level4Grid(this.byId('**AnyNameGrid**'));
}
It doesn't work

But if I replace "AnyNameGrid" with "**PropertyGrid**" it works fine!
