### ISSUE TITLE
Bulk Create

### ISSUE THREAD

**Issue by JPiris88** [volkanceylan/Serenity#4464]
Hi.

I have an entity called "Document" where a user can upload several documents through an Excel. The problem is that the Excel can contains thousands and thousands of rows so if something goes wrong while creating the documents the system will rollback the transaction. Worried about the database primary key could grow too much, I decided to make an "CreateBulk" action in "DocumentEndpoint". Here, first I can check if all the documents are valid and then insert them into the database.

I know I can do a loop calling "documentController.Create(uow, request)" for each document but if something goes wrong at the middle of the process I'll lose a lot of primary keys value because of the rollback.

Here is my code:
``` c#
        public class BulkDocumentSaveResponse : ServiceResponse
        {
            public int[] EntitiesIds;
        }

        [HttpPost, AuthorizeCreate(typeof(MyRow))]
        public BulkDocumentSaveResponse CreateBulk(IUnitOfWork uow, List<DocumentSaveRequest<MyRow>> requests)
        {
            var mySaveHandlers = new List<Tuple<MySaveHandler, DocumentSaveRequest<MyRow>>>();

            foreach (var request in requests)
            {
                var mySaveHandler = new MySaveHandler(request.Entity, request, documentSaveResponse: null, uow: uow);

                mySaveHandler.CustomValidate();

                mySaveHandlers.Add(new Tuple<MySaveHandler, DocumentSaveRequest<MyRow>>(mySaveHandler, request));
            }

            var createdDocumentIds = new List<int>();

            foreach (var mySaveHandler in mySaveHandlers)
            {
                var documentSaveResponse = mySaveHandler.Item1.Process(uow, mySaveHandler.Item2, SaveRequestType.Create);

                createdDocumentIds.Add(Convert.ToInt32(documentSaveResponse.EntityId));
            }

            return new BulkDocumentSaveResponse { EntitiesIds = createdDocumentIds.ToArray() };
        }
```

and here is my "MySaveHandler" code:

``` c#
        private class MySaveHandler : SaveRequestHandler<MyRow, DocumentSaveRequest<MyRow>, DocumentSaveResponse>
        {
            bool _validated = false;

            public MySaveHandler()
            {

            }

            public MySaveHandler(MyRow myRow, DocumentSaveRequest<MyRow> documentSaveRequest, DocumentSaveResponse documentSaveResponse, IUnitOfWork uow)
            {
                base.Row = myRow;
                base.Request = documentSaveRequest;
                base.Response = documentSaveResponse;
                base.UnitOfWork = uow;
            }

            public void CustomValidate()
            {
                var editableFields = ValidateEditable();

                ValidateRequired(editableFields);
                SetInternalFields();
                BeforeSave();

                _validated = true;
            }

            protected override void BeforeSave()
            {
                if (_validated)
                    return;

                base.BeforeSave();

				//throw an exception if something is not valid
            }

            protected override void SetInternalFields()
            {
                if (_validated)
                    return;

                base.SetInternalFields();
				
				//throw an exception if something is not valid
            }

            protected override void ValidateRequired(HashSet<Field> editableFields)
            {
                if (_validated)
                    return;

                base.ValidateRequired(editableFields);

				//throw an exception if something is not valid
            }
        }
```

What do you think? Is there another easiest way to do this?

**Comment by Febriantos** [comment]
@JPiris88 : I recommend to separate the functionalities, 
First use serenity to upload files to folder/S3/WhateverStorage you use.
Second create separate background application/job/worker/service to load/process the data to thevdatabase.
Third add queuing using HangFire if needed.

**Comment by JPiris88** [comment]
That can help me on a long task, but what about the rules of business logic of the "Document" entity? They're defined in "DocumentController.MySaveHandler" and I don't want to duplicate them into another background process. The main idea is:
- Read all Excel's rows
- Validate that all documents comply with the business rules defined in "MySaveHandler"
- Only when all documents are valid insert them into the database using "MySaveHanlder.Process()" method

**Comment by JPiris88** [comment]
> 
> 
> @JPiris88 : I recommend to separate the functionalities,
> First use Serenity to upload files to folder/S3/WhateverStorage you use.
> Second create separate background application/job/worker/service to load/process the data to the database.
> Third add queuing using HangFire if needed.

**Comment by Febriantos** [comment]
@JPiris88 : It depends on your situation and expectation, how many rows, files, users are going to use the application? If it contains millions rows in a single file and user can upload multiple files at the same time and multiple concurrent users uploading at the same time then I suggest to use serenity only for uploading the file. For me, I will prefer the validation as part of the background process. Since I'm not a fan of running heavy computation/calculation on the WebServer. My2¢.
