### ISSUE TITLE
QuickSearch Box on DetailList Grid

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4466]
Hello!
I want a search option on the DetailList grid 
Is there any sample?

**Comment by ga5tan** [comment]
I believe there were some samples about sorting and filtering, that may set u in the right direction.
or maybe split grid sample in premium package...

**Comment by Shraddha996** [comment]
hello @ga5tan  It would be great if you share some reference link here.

**Comment by Shraddha996** [comment]
Hey @ga5tan  I also add **Quickfilter** attribute to my details column and it creates the searchbox but couldn't search for the string
I think am missing something very basic Please guide me.

![Capture5](https://user-images.githubusercontent.com/39983941/61181686-38f54e00-a647-11e9-811a-fdb89752ece2.JPG)

**Comment by ga5tan** [comment]
just search here in forums for the in-memory grid search and sorting option
Quickserach usualy works, do you use lookup columns? maybe that needs some extra tricks...

**Comment by Shraddha996** [comment]
@ga5tan  Thanks for the reply.
As you suggest I have gone through the previous issue but I fail to find actual QuickSearch on detail editor
As well as you can see in the previous screenshot the **characteristics constant** coming from **populate items on the selection of dropdown BOM** 
![Capture12](https://user-images.githubusercontent.com/39983941/61269220-8a264e80-a7bb-11e9-9f84-aad50f2d1ad9.PNG)
and for that I want quicksearch option


Hope this is enough
Thanks in advance!

**Comment by ga5tan** [comment]
I dont thin there was quicksearch for in-memory grid.

**Comment by brunobola** [comment]
I've already demonstrated that there is a way to implement search/filtering and sort order on in-memory grids, just search the issues ;)

**Comment by Shraddha996** [comment]
@brunobola am unable to find search in-memory grid samples. please help me ASAP

**Comment by Shraddha996** [comment]
I used some code from PermissionCheckEditor.ts and modify it a bit and now my searchbox works perfectly fine like grid serachbox

If anyone needs help regarding this then let me know and for now, am closing this issue

**Comment by sispk6** [comment]
@Shraddha996,   Yes Please , Share the sample code. thank you

**Comment by Shraddha996** [comment]
@sispk6 add this in your editor.ts file 

protected onViewFilter(item: PermissionCheckItem): boolean {
            if (!super.onViewFilter(item)) {
                return false;
            }

            if (!Serenity.SlickTreeHelper.filterById(item, this.view, x => x.ParentKey))
                return false;

            if (this.searchText) {
                return this.matchContains(item) || item.IsGroup && Q.any(this.getDescendants(item, false), x => this.matchContains(x));
            }

            return true;
        }

        private matchContains(item: PermissionCheckItem): boolean {
            //Select2.util.stripDiacritics(item.ItemMaterialDescription || '').toLowerCase().indexOf(this.searchText) >= 0;
            return Select2.util.stripDiacritics(item.CharacteristicsCharacteristicsName || '').toLowerCase().indexOf(this.searchText) >= 0;
        }

        private getDescendants(item: PermissionCheckItem, excludeGroups: boolean): PermissionCheckItem[] {
            let result: PermissionCheckItem[] = [];
            let stack = [item];
            while (stack.length > 0) {
                let i = stack.pop();
                let children = this.byParentKey[i.Key];
                if (!children)
                    continue;

                for (let child of children) {
                    if (!excludeGroups || !child.IsGroup) {
                        result.push(child);
                    }

                    stack.push(child);
                }
            }

            return result;
        }

    export interface PermissionCheckItem {
        ParentKey?: string;
        Key?: string;
        IsGroup?: boolean;
        CharacteristicsCharacteristicsName?: string;
    }
