### ISSUE TITLE
When Button clicked  Grid checkboxes  should be checked 

### ISSUE THREAD

**Issue by vishmanthisuresh111** [volkanceylan/Serenity#4467]
Hi
See this demo for this: https://serenity.is/demo/BasicSamples/CancellableBulkAction
when Perform Bulk Action on Selected Orders Button is clicked then the Grid All records checkboxes should be checked , is there any Option to do like this

reverse functionality of above
I Appreciate if you can help.

**Comment by vishmanthisuresh111** [comment]
![Capture](https://user-images.githubusercontent.com/28822956/58625057-43ee5c00-82ef-11e9-9e9e-f5448dac7ccc.PNG)

**Comment by ga5tan** [comment]
just check how checkbox mixin is doing it.
there is checkbox in upper left corner, that checks and unchecks all the checkboxes. You can take inspiration there, if you insist on duplicating that functionality

**Comment by JohnRanger** [comment]
@vishmanthisuresh111 ,

why do you need to have abutton for "Select all checkboxes"? If your users click on the checkbox above all checkboxes (the "title" checkbox, all Checkboxes get automatically selected).

![row-selection](https://user-images.githubusercontent.com/2699447/59528985-0f2df780-8ee0-11e9-86fb-96d2ea7dbfc8.png)

John

**Comment by ga5tan** [comment]
the problem I see now is, that checkbox selects ONLY first page of the grid, NOT all the rows in the result-set. Any ideas?

**Comment by stixoffire** [comment]
@ga5tan Did you figure out how to do this on all rows returned for each page - I think that is the issue is that you have one page in the view at a time ..
