### ISSUE TITLE
How to check or uncheck checkboxes inside an editor on button click

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4469]
I have an editor with multiple columns..on that editor first column is checkbox column..and i have buttons like 
'select all'-->when i click on selectall, all checkboxes should be checked 
 'deselect all'--->when i click on deselectall  all the checkboxes in the editor should be unchecked

can anyone suggest above behaviour on button clicks
thanks..

**Comment by ga5tan** [comment]
Checkboxes mixin for the grid has already this feature. Checkbox in upper left corner checks and unchecks all the rows.
I think you can get sample there?

**Comment by flextrio-gandhi** [comment]
Yes that was there...but how to achive that task on button clicks...because i have other buttons as well based
on each button click conditionally should load records
