### ISSUE TITLE
xyzGrid.cs; Auto-resize with of columns; slickgrid plugin; how to best "add" it in serenity framework so that all grids have the additional plugin automatically included?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#447]
Hi JaiQ,

I am looking for a way to include the slickgrid plugin from naresh (https://github.com/naresh-n/slickgrid-column-data-autosize) to have the slickgrid columns in serenity do auto-size the width when double-clicking between the column headers.

What I mean is this: I want to place the including of the **slick.autocolumnsize.js** at the best possible place within Serenity in order that all serenity grids have the plugin automatically included.

So far I have added the plugin to the xyz.Web/Scripts/SlickGrid/Plugins/ Folder and added the file to the VS Project.

I have tried to find the place within Serenity where the other existing Slickgrid plugins are listed/included but even a fulltext search over the whole VS solution only Returns the file xyz.Web.csproj and some DesignTimeResolveAssemblyReferencesInput.cache files.

How would I best include this plugin to be loaded automatically within each Grid?

P.S: I have looked at the resulting DOM but the new plugin js was not listed - so it is not automatically picked up by the DynamicScriptManager. I have tried to find the Definition (list) for the "ColumnsBundle" (referenced within _LayoutHead.cshtml) as it sounds like a reasonable place to define things for the grid but didn't find the Definition.

Thanks for your help 

and 

with Kind regards,

John

**Comment by jsbUSMC** [comment]
I'm sorry I can't provide a better answer as to why the script isn't bundled or how to do so, but you could try to add it to the _LayoutHead.cshtml file. This way it will be included in the `<head>` tag for every page. However, do you need to initialize the plugin? You might have to write custom import for this, or perform the initialization in each page of your grid.

**Comment by JohnRanger** [comment]
Hi jsbUSMC,

thanks for your Feedback. Yes - I could include it in the _LayoutHead.cshtml file - but then it would be loaded/included in every page - not only in the grids.

But... ;-)
There is this DynamicScriptManager which - at least from looking at it (as a dev beginner like I am) - seems to dynamically load the "bundles" of scripts according to the Destination type of page which should be rendered.

**@JaiQ:** Any thoughts about this?

With Kind regards,

John

**Comment by volkanceylan** [comment]
It's a little script so loading it in every page wouldn't hurt so much. But anyway you can load it from @section Head in your Page.cshtml.

**Comment by jsbUSMC** [comment]
Ah yes, I totally forgot about
```cshtml
@section Head
{
    <script src="path/to/your/script.js"></script>
}
```

@JohnRanger this is what I did when I added a script to my login page that was only to be used on the login page.

**Comment by JohnRanger** [comment]
Hi JaiQ and jsbISMC,

thanks for all of your Feedback. I appreciate it.

I know that I can do this either in one central location (In the _Layout Head) or on every page (head). but is there a central way to do this so that it only loads when used on any grid but not on any other type of page?

(I know that this Little script doesn't hurt to be loaded always but I am a fan of your (JaiQ)  optimization Approach to only load things when needed and to do this in a centralized way. This is what I love in the Serenity Framework:

- Structured, optimized Approach.

That's why it stays fast even when the app complexity and DB size increases and there is no chaos.

With Kind regards,

John

**Comment by volkanceylan** [comment]
Thanks John, 

I'm actually not big fan of loading static scripts dynamically, as long as such a script is big and not used in 90% of all pages. Serenity includes a script bundling system that i'll write later about, so in production that little script will get minimized and bundled alongside other scripts, unless you exclude it from bundles specially.

There are so many libraries, script loaders, that can do on-demand script loading for for you, requirejs, headjs etc, and a thousand i don't even remember.

Anyway for a quick & dirty solution, see how i load CKEditor dynamically in HtmlContentEditor.cs (serenity source code) IncludeCKEditor method, if it is not loaded already. 

Your plugin needs to be registered to SlickGrid, with slickGrid.registerPlugin method, so while registering your plugin in grids you want, you may call IncludeCKEditor method. Or better, extract both into a helper method and call it from your grid.

**Comment by JohnRanger** [comment]
Hi JaiQ,

many thanks for your valuable Feedback. Looking Forward to read about the script bundling System of serenity. :-)

I have looked at the slickgrid.registerPlugin method.

Sorry for my lack of knowledge but even by trying to reverse-engineer the serenity original code I didn't got how you created the "slickgrid.registerPlugin" objects for the serenity-built-in SlickGrid plugins. 

How would I create the new object for the AutoColumnSize plugin so that I can stick it into slickGrid.registerPlugin?

Thanks again and

with Kind regards,

John

**Comment by volkanceylan** [comment]
See GroupingAndSummariesInGrid.cs for how i register groupitemmetadataprovider plugin. You need to write a simple import class for your plugin similar to that one.

**Comment by volkanceylan** [comment]
e.g.
```
    [Imported, ScriptNamespace("Slick.Data"), ScriptName("GroupItemMetadataProvider")]
    public class SlickGroupItemMetadataProvider
    {
        public SlickGroupItemMetadataProvider()
        {
        }

        public SlickGroupItemMetadataProvider(object options)
        {
        }
    }
```

Replace namespace and scriptname with yours.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks again for your excellent help.

I have created a new file under the xyz.Script Project and added the following code:

```cs
#region Assembly Serenity.Script.Imports, Version=1.9.25.0, Culture=neutral, PublicKeyToken=null
// C:\Temp\DEV\Serene6\packages\Serenity.Script.1.9.25\lib\net2\Serenity.Script.Imports.dll
#endregion

using System.Runtime.CompilerServices;

namespace ClientAndAssetManagement

{
        [Imported]
        [ScriptName("AutoColumnSize")]
        [ScriptNamespace("Slick")]
        public class SlickAutoColumnSize
        {
            public SlickAutoColumnSizeProvider()
            {
                
            }

            public SlickAutoColumnSizeProvider(object options)

            {
            }
        }
}
```
Now it is complaining 2x that SlickAutoColumnSizeProvider must have a return type.

I have looked at the Definition of your SlickGroupItemMetadataProvider (from Metadata) but there is nothing given regarding a return type.

When I put **public void SlickAutoColumnSizeProvider** then it compiles - I can use the SlickAutoColumnSize in the registerPlugin function but it actually does nothing.

What would I do here? (Sorry again for bothering you with some probably Basic knowledge questions)

In the xyzGrid.cs, I use the registering of the plugin like this:

```cs
 protected override SlickGrid CreateSlickGrid()
        {
            //return base.CreateSlickGrid();

            var grid = base.CreateSlickGrid();
            grid.RegisterPlugin(new SlickAutoColumnSize());

            return grid;

        }
```




With Kind regards,

John

**Comment by volkanceylan** [comment]
Your class name and constructor name doesn't match. SlickAutoColumnSize and SlickAutoColumnSizeProvider.

**Comment by JohnRanger** [comment]
I am ashamed ;-)

Thanks, JaiQ.

As soon as the whole solution fully works, I will provide here the straight Forward implementation.

With Kind regards,

John

**Comment by JohnRanger** [comment]
Hi all, as promised, here the fully working solution.

**Limitation:**
Currently, I am not yet able to Auto-resize all rows on initial load as proposed here: http://stackoverflow.com/questions/6794656/how-do-i-autosize-the-column-in-slickgrid

This must have something to do with the way how serenity Framework is initializing the slickgrid (have still to investigate).

```JavaScript
Add $container.ready(resizeAllColumns); to the init function.
```

***
**There are two approaches:**
1) You want this Feature globally active on all grids --> Modification of Serenity.Script.UI.js is required
2) You want to add this Feature on selected grids only

**Preparation for both Solutions:**

You need the following (slightly modified) **slick.autocolumnsize.js** file (original is from naresh: https://github.com/naresh-n/slickgrid-column-data-autosize/tree/master/src but does not work within Serenity for yet unknown reason)

```JavaScript
(function($) {

    $.extend(true, window, {
        "Slick": {
            "AutoColumnSize": AutoColumnSize
        }
    });

    function AutoColumnSize(maxWidth) {

        var grid, $container, context,
            keyCodes = {
                'A': 65
            };

        function init(_grid) {
            grid = _grid;
            maxWidth = maxWidth || 200;

            $container = $(grid.getContainerNode());
            $container.on("dblclick.autosize", ".slick-resizable-handle", reSizeColumn);
            $container.keydown(handleControlKeys);

            context = document.createElement("canvas").getContext("2d");

        }

        function destroy() {
            $container.off();
        }

        function handleControlKeys(event) {
            if (event.ctrlKey && event.shiftKey && event.keyCode === keyCodes.A) {
                resizeAllColumns();
            }
        }

        function resizeAllColumns() {
            var elHeaders = $container.find(".slick-header-column");
            var allColumns = grid.getColumns();
            elHeaders.each(function(index, el) {
                var columnDef = $(el).data('column');
                var headerWidth = getElementWidth(el);
                var colIndex = grid.getColumnIndex(columnDef.id);
                var column = allColumns[colIndex];
                var autoSizeWidth = Math.max(headerWidth, getMaxColumnTextWidth(columnDef, colIndex)) + 1;

                // *** John Ranger 2016-03-23: Remarked as this causes some problems with some columns ***
                //autoSizeWidth = Math.min(maxWidth, autoSizeWidth);

                column.width = autoSizeWidth;
            });
            grid.setColumns(allColumns);
            grid.onColumnsResized.notify();
        }

        function reSizeColumn(e) {
            var headerEl = $(e.currentTarget).closest('.slick-header-column');
            var columnDef = headerEl.data('column');

            if (!columnDef || !columnDef.resizable) {
                return;
            }

            e.preventDefault();
            e.stopPropagation();

            var headerWidth = getElementWidth(headerEl[0]);
            var colIndex = grid.getColumnIndex(columnDef.id);
            var allColumns = grid.getColumns();
            var column = allColumns[colIndex];

            var autoSizeWidth = Math.max(headerWidth, getMaxColumnTextWidth(columnDef, colIndex)) + 1;

            if (autoSizeWidth !== column.width) {
                column.width = autoSizeWidth;
                grid.setColumns(allColumns);
                grid.onColumnsResized.notify();
            }
        }

        function getMaxColumnTextWidth(columnDef, colIndex) {

            var texts = [];
            var rowEl = createRow(columnDef);

            var data = grid.getData();

            // *** John Ranger 2016-03-23: Block remarked as this causes the plugin not to work within serenity framework ***
            //if (Slick.Data && data instanceof Slick.Data.DataView) {
            //    alert('jojo in 2.5');
            //    data = data.getItems();
            //}

            for (var i = 0; i < data.length; i++) {
                texts.push(data[i][columnDef.field]);
            }
            var template = getMaxTextTemplate(texts, columnDef, colIndex, data, rowEl);
            var width = getTemplateWidth(rowEl, template);
            deleteRow(rowEl);
            return width;
        }

        function getTemplateWidth(rowEl, template) {
            var cell = $(rowEl.find(".slick-cell"));
            cell.append(template);
            $(cell).find("*").css("position", "relative");
            return cell.outerWidth() + 1;
        }

        function getMaxTextTemplate(texts, columnDef, colIndex, data, rowEl) {
            var max = 0,
                maxTemplate = null;
            var formatFun = columnDef.formatter;
            $(texts).each(function(index, text) {
                var template;
                if (formatFun) {
                    template = $("<span>" + formatFun(index, colIndex, text, columnDef, data) + "</span>");
                    text = template.text() || text;
                }
                var length = text ? getElementWidthUsingCanvas(rowEl, text) : 0;
                if (length > max) {
                    max = length;
                    maxTemplate = template || text;
                }
            });
            return maxTemplate;
        }

        function createRow(columnDef) {
            var rowEl = $('<div class="slick-row"><div class="slick-cell"></div></div>');
            rowEl.find(".slick-cell").css({
                "visibility": "hidden",
                "text-overflow": "initial",
                "white-space": "nowrap"
            });
            var gridCanvas = $container.find(".grid-canvas");
            $(gridCanvas).append(rowEl);
            return rowEl;
        }

        function deleteRow(rowEl) {
            $(rowEl).remove();
        }

        function getElementWidth(element) {
            var width, clone = element.cloneNode(true);
            clone.style.cssText = 'position: absolute; visibility: hidden;right: auto;text-overflow: initial;white-space: nowrap;';
            element.parentNode.insertBefore(clone, element);
            width = clone.offsetWidth;
            clone.parentNode.removeChild(clone);
            return width;
        }

        function getElementWidthUsingCanvas(element, text) {
            context.font = element.css("font-size") + " " + element.css("font-family");
            var metrics = context.measureText(text);
            return metrics.width;
        }

        return {
            init: init,
            destroy: destroy
        };
    }
}(jQuery));
```
--> You insert this script in your serenity web Project under **/Scripts/SlickGrid/Plugins/ slick.autocolumnsize.js**.

In the web Project in file **/Views/Shared/_LayoutHead.cshtml**, search for the following Content:
**@foreach (var x in CommonIncludes.Scripts) { @Html.Script(x) }**
and insert the following line directly after the above line:
**@Html.Script("~/Scripts/SlickGrid/Plugins/slick.autocolumnsize.js")**

***

**For solution 1** (auto-resize working in all grids),
open /Scripts/serenity/Serenity.Script.UI.js and search for the following string: **grid.registerPlugin(new Slick.AutoTooltips({ enableForHeaderCells: true }));**

Immediately after this line, insert the following new line: **grid.registerPlugin(new Slick.AutoColumnSize());**

--> That's it: From now on, all your grids have the following auto-resize capabilities:
- Double-click between two Header columns will Auto-resize the left column
- Clicking on any cell in any row and then pressing Ctrl + Shift + A does Auto-resize all columns at once

***

**For solution 2** (only activate auto-resizing on some grids),
we have a bit more work to do.

1) Create a new file called SlickGridPlugins.cs with content below and place it in the script Project ( I have put it under **/Common/Helper/SlickGridPlugins.cs**).

```cs
using System.Runtime.CompilerServices;

namespace <your Project>

{
    [Imported]
    [ScriptName("AutoColumnSize")]
    [ScriptNamespace("Slick")]
    public class SlickAutoColumnSize
    {
        public SlickAutoColumnSize()
        {

        }     
    }
}
```

Then, in each of your xyzGrid.cs files where you want the Auto-resize Feature available, insert the following code:

```cs
 protected override SlickGrid CreateSlickGrid()
        {
           var grid = base.CreateSlickGrid();
            grid.RegisterPlugin(new SlickAutoColumnSize());

            return grid;
        }
```

--> That's it: From now on the grids which are "improved" with above code will have the auto-resize-Feature.

***

Hope this helps some of you.

**P.S: If some of you find out how to Trigger the resizeAllColumns() function of this plugin at initial load from within serenity, please post it here.**

With Kind regards,

John

**Comment by volkanceylan** [comment]
Thanks John but please don't update Serenity.Script.UI.js. Your changes might be overridden on next update.

**Comment by volkanceylan** [comment]
You might create a common base grid class for all your grids and derive from it if required.

**Comment by volkanceylan** [comment]
Try this for initial resize (not tested):

```
        return {
            init: init,
            resizeAllColumns: resizeAllColumns,
            destroy: destroy
        };
```

```cs
private SlickAutoColumnSize autoSize;

protected override SlickGrid CreateSlickGrid()
{
     var grid = base.CreateSlickGrid();
     autoSize = new SlickAutoColumnSize();
     grid.RegisterPlugin(autoSize);
     return grid;
}

protected override MarkupReady() 
{
    autoSize.As<dynamic>().resizeAllColumns();
}
```

**Comment by JohnRanger** [comment]
Hi JaiQ,

many thanks for your fast reply.

1) How would I create a common base grid class? (I have no idea, unfortunately but sounds like the way to go). If you could direct me into the right direction (with some key steps in between) - then I will update my above Feedback to do it like this.

2) I am not 100% sure with the proper positionning of 
```javascript
return {
            init: init,
            resizeAllColumns: resizeAllColumns,
            destroy: destroy
        };
```

I have put this into the main function of the autocolumnsize.js file (function($)... Is that correct?

Also: It complained when I used only protected override Markupready() but with "void" it runs.

Currently, the Client side Fails when executing the **autoSize.As<dynamic>().resizeAllColumns();** line.

I have put some Q.Alerts around it like this:

```cs
 protected override void MarkupReady()
        {
            base.MarkupReady();

            Q.Alert("test1");
            autoSize.As<dynamic>().resizeAllColumns();
            Q.Alert("test2");
        }
```

Test1 is shown at Markup ready but test2 not.

Do you have any more things I could try?

Thanks again and

with Kind regards,

John

**Comment by volkanceylan** [comment]
What is error in console?

**Comment by JohnRanger** [comment]
Hi JaiQ,

I have now modified the Slick.autocolumnsize.js return section according to the given section by you but it still crashes on the Client side.

when I debug with Chrome, it says: **TypeError: Cannot read property 'resizeAllColumns' of null**

Somehow it thinks that this is a property, not a function.

The final JavaScript it Shows Looks like this: **this.$autoSize.resizeAllColumns();**

Above this (at the initiation of the function(container) I can see the following line: **this.$autoSize = null;**

Beside of that, no reference to $autoSize can be found.

So for me ( a beginner in programming) it seems that the "autoSize" in the xyzGrid.cs never really reaches over to the functions within Slick.autocolumsize.js.

Do you have any thoughts how to Access These inside functions?

With Kind regards,

John

**Comment by volkanceylan** [comment]
Write 
```
if (autoSize != null)
    autoSize.As<dynamic>().resizeAllColumns();
```

**Comment by JohnRanger** [comment]
I have modified the Code as follows:

```cs
 if (autoSize != null)
            {
                Q.Alert("autoSize != null");
                autoSize.As<dynamic>().resizeAllColumns();
                Q.Alert("after autoSize");
            }

            Q.Alert("test2");
```

Only "Test2" is shown (because autoSize really is null and does not get initialized or set).

There is also something which is shown with a green line in the following line: ** private SlickAutoColumnSize autoSize;**

(Green line under autoSize which says: Field xyzGrid.autoSize is never assigned to and will always have ist Default value to null)

Do we have to "initialize" or so the autoSize?

With Kind regards,

John

**Comment by volkanceylan** [comment]
John, wake up John ;)

```cs
protected override SlickGrid CreateSlickGrid()
{
     var grid = base.CreateSlickGrid();
     autoSize = new SlickAutoColumnSize();
     grid.RegisterPlugin(autoSize);
     return grid;
}
```

**Comment by JohnRanger** [comment]
Good suggestion ;-) It's a Long day (already 13.5h at work and still here... ;-))

It works!

congratulation. I am amazed. Thanks for your help.

Question:
Don't you want to include the autosize Feature within serenity as a standard?

--> Maybe with an attibute in the xyzColumn.cs to allow for initial autosize of the whole grid and an Attribute on each column to auto-size that column (only) at initialization of grid?

**Comment by JohnRanger** [comment]
Now...
Comes the part with the central base class which then is used in all grids.

How would I create such a base class?

I mean: the goal should be to only modify/create one particular Piece of file (like I did with Serenity.script.UI.js and then all grids should automatically have the functionality.

Is that at all possible or do all xyzGrid.cs have to be modified (at least a Little bit to derive from the new base class)?

**Comment by JohnRanger** [comment]
for all: if you want to have initial auto-resize of the whole grid, use the following code within your xyzGridcs:
```cs

        protected override SlickGrid CreateSlickGrid()
        {
            //return base.CreateSlickGrid();

            var grid = base.CreateSlickGrid();
            autoSize = new SlickAutoColumnSize();
            grid.RegisterPlugin(autoSize);
            return grid;

        }

        protected override void MarkupReady()
        {
            base.MarkupReady();

            if (autoSize != null)
            {
                autoSize.As<dynamic>().resizeAllColumns();
            }

        }
```

Hint: This works only with above solution (2).

For proper solution 1 (without modifying Serenity.Script.UI.js), I will give Feedback here as soon as I (actually it's more JaiQ) have worked it out.

John

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your excellent help. Case closed I would say :-)

Have a nice evening 

and with Kind regards,

John

**Comment by ramveersgh** [comment]
Hi @JohnRanger 
How you do it by creating common base grid class?
Please share instruction for it...  Thanks in advance...

**Comment by JohnRanger** [comment]
Hi Ramveersgh,

I honestly have no idea. Info regarding this would have to come from JaiQ/Volkan. I am no real developer, just an admin.

My solution for my own Project is to add it in the Serenity.Script.UI.js (as described above) as I don't update the serenity packages now because the whole Project is stable. This adds the functionality to all grids with just one line of code.

**Please note that Volkan does not recommend this** because it would be overwritten as soon as you update the serenity packages. (But it really works just fine otherwise. If you have to update the Serenity packages, just add the line of code afterwards again.)

If somebody else finds a way to build a base class with this added functionality, please let us know :-)

**Or better:** Write to Volkan and ask him, if he would please add this functionality into the Standard Serenity Framework as this is surely an often required Feature.

With Kind regards,

John

**Comment by ramveersgh** [comment]
Thanks John for your comments.
Yes.. I was made the changes as suggested to auto resize and to allow text to copy inside grid.. but when i took update my changes get overridden.

I will create a another issue and ask to volkan with suggestion to add auto resize and allow text to copy as default in serenity. 
I will have a try myself before creating it as new issue.

Thanks
Ram

**Comment by JohnRanger** [comment]
Hi all,
as I have tested upgrading the SFW from V1.9.13 (where this solution works fine) to some newer Version I found that you can update up to SFW V1.9.19 and this solution still works.

In V1.9.20, JaiQ changed something within the Slickgrid and somehow this plugin does not work anymore (or does not get properly registered) and autoColumn sizing (at least with this solution) does not work anymore.

Unfortunately, I couldn't figure out so far what has changed and what breaks this.

If you figure it out, please post it here so we can Profit also :-)

With Kind regards,

John

**Comment by JohnRanger** [comment]
Hi all,

a late update to this thread: Just because out of interest I have tested the auto-colum resize slickgrid plugin with a recent Version of Serenity (2.7.2.0) and it works again. Seems that what was broken from Serenity V1.9.20 on in this regard has lately been fixed.

At least with the here described method (1) you can use the plugin again.

I was not yet able to call the auto-resize-all from the new typescript when the grid is initally loaded (as I don't find similar functions like in Saltarelle) but the auto-resize-on click works already.

Maybe somebody can give me a quick guide on how to call the autosize function:

In Saltarelle, we could do something like this:

```cs
using System.Runtime.CompilerServices;

namespace <your Project>

{
    [Imported]
    [ScriptName("AutoColumnSize")]
    [ScriptNamespace("Slick")]
    public class SlickAutoColumnSize
    {
        public SlickAutoColumnSize()
        {

        }     
    }
}
```
How can I do something like this in Typescript in order to Access the methods of this plugin?

Thanks and with Kind regards,

John

**Comment by JohnRanger** [comment]
Hi all,

in order that the autocolumnresize slickgrid plugin fully works with the current serenity Framework, I had to fix some more stuff.

Here the working Code:

```js
(function($) {

    $.extend(true, window, {
        "Slick": {
            "AutoColumnSize": AutoColumnSize
        }
    });




    function AutoColumnSize(maxWidth) {



        var grid, $container, context,
            keyCodes = {
                'A': 65
            };

        function init(_grid) {
            grid = _grid;
            maxWidth = maxWidth || 200;

            $container = $(grid.getContainerNode());
            $container.on("dblclick.autosize", ".slick-resizable-handle", reSizeColumn);
            $container.keydown(handleControlKeys);

            context = document.createElement("canvas").getContext("2d");

        }

        function destroy() {
            $container.off();
        }

        function handleControlKeys(event) {
            if (event.ctrlKey && event.shiftKey && event.keyCode === keyCodes.A) {
                resizeAllColumns();
            }
        }

        function resizeAllColumns() {
            var elHeaders = $container.find(".slick-header-column");
            var allColumns = grid.getColumns();
            elHeaders.each(function(index, el) {
                var columnDef = $(el).data('column');
                var headerWidth = getElementWidth(el);
                var colIndex = grid.getColumnIndex(columnDef.id);
                var column = allColumns[colIndex];
                var autoSizeWidth = Math.max(headerWidth, getMaxColumnTextWidth(columnDef, colIndex)) + 1;

                // *** John Ranger 2016-03-23: Remarked as this causes some problems with some columns ***
                //autoSizeWidth = Math.min(maxWidth, autoSizeWidth);

                column.width = autoSizeWidth;
            });
            grid.setColumns(allColumns);
            grid.onColumnsResized.notify();
        }

        function reSizeColumn(e) {
            var headerEl = $(e.currentTarget).closest('.slick-header-column');
            var columnDef = headerEl.data('column');

            if (!columnDef || !columnDef.resizable) {
                return;
            }

            e.preventDefault();
            e.stopPropagation();

            var headerWidth = getElementWidth(headerEl[0]);
            var colIndex = grid.getColumnIndex(columnDef.id);
            var allColumns = grid.getColumns();

            var column = allColumns[colIndex];

            var autoSizeWidth = Math.max(headerWidth, getMaxColumnTextWidth(columnDef, colIndex)) + 1;

            if (autoSizeWidth !== column.width) {
                column.width = autoSizeWidth;
                grid.setColumns(allColumns);
                grid.onColumnsResized.notify();
            }
        }

        function getMaxColumnTextWidth(columnDef, colIndex) {

            var texts = [];
            var rowEl = createRow(columnDef);

            var data = grid.getData();

            // *** John Ranger 2016-03-23: Block remarked as this causes the plugin not to work within serenity framework ***
            //if (Slick.Data && data instanceof Slick.Data.DataView) {
            //    alert('jojo in 2.5');
            //    data = data.getItems();
            //}

            data = data.getItems(); // *** John Ranger 2017-02-09 added in order to make this plugin work with current serenity version (2.9.4) ***

            for (var i = 0; i < data.length; i++) {
                texts.push(data[i][columnDef.field]);
            }
            var maxWidth = getMaxWidth(texts, columnDef, colIndex, data, rowEl);    // *** Using new function to directly get max width without running over template mechanism (which does not work anymore) ***
            deleteRow(rowEl);

            maxWidth = maxWidth + 15;   // *** Additional space for better reading and to accomodate additional little space used by diverse invisible objects - adjust if needed ***
            return maxWidth;
        }


        function getMaxWidth(texts, columnDef, colIndex, data, rowEl) {
            var max = 0;
            var formatFun = columnDef.formatter;
            $(texts).each(function (index, text) {
                var template;
                if (formatFun) {
                    template = $("<span>" + formatFun(index, colIndex, text, columnDef, data) + "</span>");
                    text = template.text() || text;
                }
                var length = text ? getElementWidthUsingCanvas(rowEl, text) : 0;

                if (length > max) {
                    max = length;
                }
            });

            return max;
        }

        function createRow(columnDef) {
            var rowEl = $('<div class="slick-row"><div class="slick-cell"></div></div>');
            rowEl.find(".slick-cell").css({
                "visibility": "hidden",
                "text-overflow": "initial",
                "white-space": "nowrap"
            });
            var gridCanvas = $container.find(".grid-canvas");
            $(gridCanvas).append(rowEl);
            return rowEl;
        }

        function deleteRow(rowEl) {
            $(rowEl).remove();
        }

        function getElementWidth(element) {
            var width, clone = element.cloneNode(true);
            clone.style.cssText = 'position: absolute; visibility: hidden;right: auto;text-overflow: initial;white-space: nowrap;';
            element.parentNode.insertBefore(clone, element);
            width = clone.offsetWidth;
            clone.parentNode.removeChild(clone);
            return width;
        }

        function getElementWidthUsingCanvas(element, text) {
            context.font = element.css("font-size") + " " + element.css("font-family");
            var metrics = context.measureText(text);
            return metrics.width;
        }

        return {
            init: init,
            resizeAllColumns: resizeAllColumns,
            destroy: destroy
        };
    }
}(jQuery));
```

Just replace all code within slick.autocolumnsize.js with the above Code.

Hope this helps someone.

P.S: I am still trying to get the resizeAllColumns() function of the plugin to be triggered when the grid is fully loaded - but this time from Typescript.

--> If somebody knows how to do it, please let us know.

John

**Comment by JohnRanger** [comment]
Hi all,

here now the solution for "current" (as of time of writing) serenity Framework with typescript:

1) Create new slickgrid plugin file called slick.autocolumnsize.js and place it under: \scripts\slickgrid\plugins\

```js
(function($) {

    $.extend(true, window, {
        "Slick": {
            "AutoColumnSize": AutoColumnSize
        }
    });

    function AutoColumnSize(initialAutosize) {

        var grid, $container, context,
            keyCodes = {
                'A': 65
            };

        function init(_grid) {
            grid = _grid;
            //maxWidth = maxWidth || 200;
            maxwidth = 200;

            $container = $(grid.getContainerNode());
            $container.on("dblclick.autosize", ".slick-resizable-handle", reSizeColumn);
            $container.keydown(handleControlKeys);

            context = document.createElement("canvas").getContext("2d");

            if (initialAutosize) {
                $container.ready(resizeAllColumns());
            }
        }

        function destroy() {
            $container.off();
        }

        function handleControlKeys(event) {
            if (event.ctrlKey && event.shiftKey && event.keyCode === keyCodes.A) {
                resizeAllColumns();
            }
        }

        function resizeAllColumns() {

            // *** John Ranger 2017-02-12 added in order to make this plugin work with current serenity version (2.9.4). Somehow it takes some time until all data is loaded in the grid - so we have to make sure that the data is there before we try to find out the max width of each column ***
            var data = grid.getData();
            data = data.getItems();
            if (data.length >0) {
                var elHeaders = $container.find(".slick-header-column");
                var allColumns = grid.getColumns();
                elHeaders.each(function (index, el) {
                    var columnDef = $(el).data('column');
                    var headerWidth = getElementWidth(el);
                    var colIndex = grid.getColumnIndex(columnDef.id);
                    var column = allColumns[colIndex];
                    var autoSizeWidth = Math.max(headerWidth, getMaxColumnTextWidth(columnDef, colIndex)) + 1;

                    // *** John Ranger 2016-03-23: Remarked as this causes some problems with some columns ***
                    //autoSizeWidth = Math.min(maxWidth, autoSizeWidth);

                    column.width = autoSizeWidth;
                });
                grid.setColumns(allColumns);
                grid.onColumnsResized.notify();
            }   // *** John Ranger 2017-02-12 added in order to make this plugin work with current serenity version (2.9.4). Somehow it takes some time until all data is loaded in the grid - so we have to make sure that the data is there before we try to find out the max width of each column ***
            else {
                setTimeout(resizeAllColumns, 200);
            }
        }



        function reSizeColumn(e) {
            var headerEl = $(e.currentTarget).closest('.slick-header-column');
            var columnDef = headerEl.data('column');

            if (!columnDef || !columnDef.resizable) {
                return;
            }

            e.preventDefault();
            e.stopPropagation();

            var headerWidth = getElementWidth(headerEl[0]);
            var colIndex = grid.getColumnIndex(columnDef.id);
            var allColumns = grid.getColumns();

            var column = allColumns[colIndex];

            var autoSizeWidth = Math.max(headerWidth, getMaxColumnTextWidth(columnDef, colIndex)) + 1;

            if (autoSizeWidth !== column.width) {
                column.width = autoSizeWidth;
                grid.setColumns(allColumns);
                grid.onColumnsResized.notify();
            }
        }

        function getMaxColumnTextWidth(columnDef, colIndex) {

            var texts = [];
            var rowEl = createRow(columnDef);

            var data = grid.getData();

            // *** John Ranger 2016-03-23: Block remarked as this causes the plugin not to work within serenity framework ***
            //if (Slick.Data && data instanceof Slick.Data.DataView) {
            //    alert('jojo in 2.5');
            //    data = data.getItems();
            //}

            data = data.getItems(); // *** John Ranger 2017-02-09 added in order to make this plugin work with current serenity version (2.9.4) ***

            //alert(data.length);
            for (var i = 0; i < data.length; i++) {
                texts.push(data[i][columnDef.field]);
            }
            var maxWidth = getMaxWidth(texts, columnDef, colIndex, data, rowEl);    // *** Using new function to directly get max width without running over template mechanism (which does not work anymore) ***
            deleteRow(rowEl);

            maxWidth = maxWidth + 15;   // *** Additional space for better reading and to accomodate additional little space used by diverse invisible objects - adjust if needed ***
            return maxWidth;
        }


        function getMaxWidth(texts, columnDef, colIndex, data, rowEl) {
            var max = 0;
            var formatFun = columnDef.formatter;
            $(texts).each(function (index, text) {
                var template;
                if (formatFun) {
                    template = $("<span>" + formatFun(index, colIndex, text, columnDef, data) + "</span>");
                    text = template.text() || text;
                }
                var length = text ? getElementWidthUsingCanvas(rowEl, text) : 0;

                if (length > max) {
                    max = length;
                }
            });

            return max;
        }

        function createRow(columnDef) {
            var rowEl = $('<div class="slick-row"><div class="slick-cell"></div></div>');
            rowEl.find(".slick-cell").css({
                "visibility": "hidden",
                "text-overflow": "initial",
                "white-space": "nowrap"
            });
            var gridCanvas = $container.find(".grid-canvas");
            $(gridCanvas).append(rowEl);
            return rowEl;
        }

        function deleteRow(rowEl) {
            $(rowEl).remove();
        }

        function getElementWidth(element) {
            var width, clone = element.cloneNode(true);
            clone.style.cssText = 'position: absolute; visibility: hidden;right: auto;text-overflow: initial;white-space: nowrap;';
            element.parentNode.insertBefore(clone, element);
            width = clone.offsetWidth;
            clone.parentNode.removeChild(clone);
            return width;
        }

        function getElementWidthUsingCanvas(element, text) {
            context.font = element.css("font-size") + " " + element.css("font-family");
            var metrics = context.measureText(text);
            return metrics.width;
        }

        return {
            init: init,
            resizeAllColumns: resizeAllColumns,
            destroy: destroy
        };
    }
}(jQuery));
```

2) In your xyzGrid.ts, add the following:

```ts
        protected createSlickGrid(): Slick.Grid {
            let grid = super.createSlickGrid();

            this.autoSize = new Slick.AutoColumnSize(); // *** If you want to make it autoresize when grid is loaded, use: new Slick.AutoColumnSize(true);
            grid.registerPlugin(this.autoSize);

            return grid;
        }
```

This works fine. 

Hint: Only Typescript is complaining when you do ```ts new Slick.AutoColumnSize(true);
``` that it does not understand the Syntax but from a JavaScript side this works fine.

Hope this helps somebody.

With Kind regards,

John

**Comment by Hochmah** [comment]
I implemented it as the last post above, but I'm getting this error messages: 

Uncaught TypeError: Slick.AutoColumnSize is not a constructor
    at xyzGrid.createSlickGrid (serenity.web.js:1583)
    at xyzGrid.$Serenity_DataGrid [as constructor] (Serenity.Script.UI.js:360)
    at xyzGrid.$Serenity_EntityGrid [as constructor] (Serenity.Script.UI.js:1284)
    at new xyzGrid(serenity.web.js:1574)
    at HTMLDocument.<anonymous> (xyz:615)
    at mightThrow (jquery-3.1.1.js:3570)
    at process (jquery-3.1.1.js:3638)

Could someone point me some directions, please?

Thank you in advance!

**Comment by shakazulu89** [comment]
hey sorry to piggy back on this issue but i am getting this error:
"Object doesn't support this action" on this line:
let autoSize = new Slick.AutoColumnSize(true);
any idea why?
thanks!!!

**Comment by shakazulu89** [comment]
ive figured this out :)

**Comment by jsguru-git** [comment]
Thanks @JohnRanger 
Your method works like a charm. 
But I think you forget to import slick.autocolumnsize.js 
Insert the following line at the end of Views/Shared/_LayoutHead.cshtml.
@Html.Script("~/Scripts/SlickGrid/Plugins/slick.autocolumnsize.js")
