### ISSUE TITLE
Exceptions logged not in English

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4470]
Hi

I have non English language exceptions in my Exception log. This is causing confusion, because it's often unclear what do they mean. Especially if it's in Chinese.
Any idea how to (ideally) log exceptions in English, or (temporarily) disable whole localization feature?

**Comment by volkanceylan** [comment]
Double post, it is about web.config ui culture setting.

**Comment by ga5tan** [comment]
Thanks
changing
`<globalization culture="auto:en-US" uiCulture="auto:en-US" />`
to 
`<globalization culture="en-US" uiCulture="en-US" />`

did the trick
