### ISSUE TITLE
How to store EntityId in a server side variable

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4472]
I am trying to save/store EntityId value in a server side variable and use the value in filtering some data in another form. I want to save when the dialog is loaded.

I have the following code in the xxRepository but it is not working.

             private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> {
            protected override void OnReturn()
                {
                publicvars.MyMRID =Request.EntityId;
                }
            }

**Comment by JohnRanger** [comment]
Hi @ms4hafiz ,

I don't think that this is a good idea. Keep it client-side (you can store it anywhere in a client-side class as this is javascript - if needed even at the DOM document level) and then reuse it wherever you need to. 

John
