### ISSUE TITLE
Import hardcoded value

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4473]
hello everyone and @volkanceylan 
am having an issue  while importing hardcoded value from import excel
this is the code 
`Material.Quality_Inspection_Required = Convert.ToInt32(worksheet.Cells[row, 21].Value ?? "");`
As you can see **Quality_Inspection_Required** is the field which has hardcoded dropdown
But in the database, this field is **integer**
But still, it shows error on the line

**_error_**
_cannot implicitly convert type 'int' to 'serene1.Premier.InspectionRequired?'.An explicit conversion exists(are you missing a cast?)_

where the **InspectionRequired**  is the name of my enum file
I tried all the datatypes after Convert but still not getting any solution

any help would be appreciated
Thanks in advance

**Row.cs code**

[DisplayName("Quality Inspection Required"), Column("Quality_Inspection_Required"), QuickSearch]
        public InspectionRequired? Quality_Inspection_Required
        {
            get { return (InspectionRequired?)Fields.Quality_Inspection_Required[this]; }
            set { Fields.Quality_Inspection_Required[this] = (Int32?)value; }

        }

public Int32Field Quality_Inspection_Required;

**enum file code**

namespace Serene1.Premier
{
    using Serenity.ComponentModel;
    using System.ComponentModel;

    [EnumKey("Premier.InspectionRequired")]
    public enum InspectionRequired
    {
        [Description("Yes")]
        Yes = 1,
        [Description("No")]
        No = 0,
        
    }
}

**Comment by Shraddha996** [comment]
Please Help someone.

**Comment by martheen** [comment]
Material.Quality_Inspection_Required = 
(worksheet.Cells[row, 21].Value ?? "").ToString()=="0"?InspectionRequired.No:InspectionRequired.Yes;

**Comment by Shraddha996** [comment]
@martheen  thank you so much! but one more question
what if I had 3 values like yes no and both how do I pass that?

**Comment by martheen** [comment]
Then just put it into switch statement. Or if there's a value for all option, perhaps Material.Quality_Inspection_Required = (InspectionRequired) Convert.ToInt32(worksheet.Cells[row, 21].Value ?? "0");

**Comment by luongnv6** [comment]
you can use:
```csharp
Material.Quality_Inspection_Required = Convert.ToString(worksheet.Cells[row, 21].Value ?? null).TrimToNull();
Material.Quality_Inspection_Required = Material.Quality_Inspection_Required.IsEmptyOrNull() ? null : Convert.ToInt32(Material.Quality_Inspection_Required);
```
