### ISSUE TITLE
How to do sorting On Editor???

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4475]
I have an OrderEditor ..
When i click on Editor column header Data is not sorting..
How to achieve sorting on editor??

![Sorting](https://user-images.githubusercontent.com/28822452/59175058-ac4fff80-8b71-11e9-94f7-49a31de0dbf0.png)

**Comment by minhhungit** [comment]
Hi @flextrio-gandhi  Check this tutorial https://github.com/volkanceylan/Serenity/issues/3792

**Comment by JohnRanger** [comment]
@flextrio-gandhi ,

I have created a Wiki entry from the given info by BrunoBola. You can find it here: [https://github.com/volkanceylan/Serenity/wiki/Grid:-Make-detail-grid-in-Master-Detail-sortable](url)

John

**Comment by fwd079** [comment]
Above link seems broken now. Try this one:

[https://github.com/volkanceylan/Serenity/wiki/Grid:-Make-detail-grid-in-Master-Detail-sortable](https://github.com/volkanceylan/Serenity/wiki/Grid:-Make-detail-grid-in-Master-Detail-sortable)

Regards.

**Comment by JohnRanger** [comment]
@flextrio-gandhi ,

this has now been answered. Would you mind to close your issue? :-)

With kind regards,

John
