### ISSUE TITLE
Show/hide programmatically a message below a field in dialog

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#448]
Dear @volkanceylan,
I've successfully modified a dialog in order to add a toast after a value change on a select in the following way:

form.MyField.ChangeSelect2(e =>
            {
                Q.NotifyWarning("bla bla);
            });

I was wondering if there is instead a way to show/hide a message (below?) such field...something like a div or a label...the simplest one!

Thanks for your support

**Comment by volkanceylan** [comment]
You can create a div 

J("<div/>").appendTo(form.MyField.Element.Closest())

Then use that div to show message but don't know if it's what u want. Bootstrap has something like callout etc.

**Comment by marcobisio** [comment]
It's fine!
Then to programmatically show/hide the element the smart thing to do is to assign an Id to the div and then referencing with "this.ById()" and then Show() or Hide() ?
Or it better to add and remove the div everytime?

Thanks again

**Comment by volkanceylan** [comment]
I'd choose to show and hide but not much difference. Anyway dont need ID for that div, just save reference in a private variable while creating.

**Comment by marcobisio** [comment]
Perfect!
Thanks very much!
