### ISSUE TITLE
Adding separator lines on navigation menu

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4480]
Dear all,

as one of my apps starts now to grow I would like to add separator lines at certain places of the navigation menu to make the navigation more intuitive. A generic search for that together with AdminLTE didn't bring any useful info - also not here in the forum.

This should look more or less like this:

![Separator](https://user-images.githubusercontent.com/2699447/59299418-dba75f00-8c8c-11e9-97b3-ad01d09679f2.png)

How could this best be achieved?

Thanks for any recommendations and help.

With kind regards,

John

**Comment by volkanceylan** [comment]
Navigation items has a css class option, use that combined with CSS to add such bottom borders

**Comment by JohnRanger** [comment]
Hi @volkanceylan ,

thanks for this advice. Will do this and make a small wiki entry when properly implemented.

Wish you a nice evening.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hmm,

in the 2.9.24 version which I am currently using this (ItemClass) is not yet implemented. Will have to back port this functionality from a more recent version.

Will post here the end-to-end solution when it is done.

John

**Comment by juliermefelix** [comment]
In my case here I am using a class called nav-list, it has set a border of 1px.
![image](https://user-images.githubusercontent.com/7516443/59344282-27d1be00-8ce4-11e9-80d8-54cbd76be43c.png)

_Layout.cshtml
![image](https://user-images.githubusercontent.com/7516443/59344401-66677880-8ce4-11e9-8c8f-818e4db44d45.png)


site.css
![image](https://user-images.githubusercontent.com/7516443/59344336-40da6f00-8ce4-11e9-82c2-961c08c6811c.png)

**Comment by JohnRanger** [comment]
@juliermefelix ,

thanks - that's a good idea - but I wanted to achieve 2 additional things (which may be not too obvious from my question):

- Setting the divider line individually as needed (not generally after every top level menu entry)
- Having the divider line to have left and right offset (as this looks better).

But I have now figured it out and will do a wiki entry.

With kind regards,

John

**Comment by JohnRanger** [comment]
For Reference to anybody which wants to have this too: Here the promised Wiki article: [https://github.com/volkanceylan/Serenity/wiki/UI:-Inserting-divider-lines-after-individual-top-level-menu-entries-on-the-left-navigation-bar](url)

With kind regards,

John
