### ISSUE TITLE
Overrid getSlickOptions

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4481]
In xyzGrid.ts how can I override some grid properties??
or how can I change the default values of these properties for all my Grids ?? 
Please anyone who wants to help me, include some code
Thanks

**Comment by Garozh** [comment]
Hi,

if you want to change grid properties and use it for several grids on your project, I suggest to derive from "GridEditorBase". 

Like I did in the following example to create grids which are allways visible without any vertical scrolling.

`	@Serenity.Decorators.editor()
	export class GridEditorFullsize<TEntity> extends Common.GridEditorBase<TEntity>{

		constructor(container: JQuery) {
			super(container);
		}

		protected getSlickOptions(): Slick.GridOptions {
			var opt = super.getSlickOptions();
			opt.showHeaderRow = true;
			opt.autoHeight = true;
			return opt;
		}
	}`

**Comment by tonysader** [comment]
@Garozh thanks that's very helpful but I want to know for example in your code 
what is the default value of showHeaderRow is it true or false
obviously you override it by true so it's by default false
but if I want to know the default value of the rowHeight, how can I do this??
Thanks again

**Comment by Garozh** [comment]
By default slickgrid has the following default option values:

[https://github.com/mleibman/SlickGrid/wiki/Grid-Options]

But you could also debug into the 'opt' variable if you wanna see the actual values.

**Comment by tonysader** [comment]
Ok thank you very much @Garozh
