### ISSUE TITLE
Remake the delete button 

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4482]
Hello, 
I am trying to remake the delete button in xyzDialog.ts
So in the dialog I tried to make this:
```
doDelete() {
            var _this = this;
            super.doDelete(function () { return _this.dialogClose(); });
        }
        dialogClose() {
            super.dialogClose();
        }
        getToolbarButtons() {
            var btns = super.getToolbarButtons();
            var _this = this;
            btns.splice(2, 1);
            var deleteBtn = {
                title: Q.text(''),
                cssClass: 'btn btn-danger fa fa-trash-o',
                hotkey: 'alt+x',
                onClick: function () {
                    Q.confirm(Q.text('Controls.EntityDialog.DeleteConfirmation'), function () {
                        _this.doDelete();
                    });
                }
            };
            
            btns.push(deleteBtn);
            return btns;
        }
```
It looks very good for me but I have two issues I want to know how to solve them if you can help me.
getToolbarsButtons() is giving me the buttons of the add dialog and the update dialog
how to specify that the deleteBtn I created if I want it only with update dialog???
and the second issue,
when I create button by default it created divs called button-outer and button-inner 
how to delete them ??
Thank you

**Comment by JohnRanger** [comment]
Hmm,

why would you need to remake the delete button? you can hide it conditionally if you don't need it - and when you want to re-style it - just use CSS and/or DOM manipulation.

Also you can hook into the events of the existing delete button.

So why all the effort to redo it...

With kind regards,

John
