### ISSUE TITLE
How to show only Date part (without time part) in a Select (LookupEditor) box?

### ISSUE THREAD

**Issue by aurony** [volkanceylan/Serenity#4484]
I need to show patient name, id & Date of Birth in a lookupEditor box. It is showing here but I do not want the time beside the date. Below is my code:

`[Expression("CONCAT(' ', T0.[PCodPaz], CONCAT(' ', T0.[PCognome]), CONCAT(' ', T0.[PNome]), CONCAT(' ', T0.[PDtNasPadre]))"), QuickSearch]`

Can I show only date without time part in a lookupEditor box?

**Comment by volkanceylan** [comment]
This is about SQL knowledge, use CONVERT function
