### ISSUE TITLE
The Best Way to Filter Detail Grid (In-Memory Grid) 

### ISSUE THREAD

**Issue by wildanmuhlis2** [volkanceylan/Serenity#4486]
Hi, 

Currently my filtering method is by overriding `OnReturn` in `RetrieveRequestHandler` at `OrderRepository.cs` . I feel it could be optimized because the current method filters the data after the data loaded.

```
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>
        {
            protected override void OnReturn()
            {
                base.OnReturn();
                Row.DetailList = Row.DetailList.Where(x => x.Discount > 0).ToList();
            }
        }
```

I've tried to override `ApplyFilter` in `OrderDetailRepository.cs`, but the override method not fired when used as detail grid:

```
        private class MyListHandler : ListRequestHandler<MyRow> {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);
                query.Where(new Criteria(fld.Discount) > 0);
            }
        }
```

Do you have any suggestions? cheers.

_Originally posted by @wildanmuhlis2 in https://github.com/volkanceylan/Serenity/issues/4483#issuecomment-502048443_

**Comment by brunobola** [comment]
Have you search the issues and WIKI for similar problems ?
https://github.com/volkanceylan/Serenity/issues/3792
