### ISSUE TITLE
ImageUploadEditor on tables wit GUID key

### ISSUE THREAD

**Issue by gulgil** [volkanceylan/Serenity#4487]
I can't get ImageUploadEditor to work on a table that have a GUID key.
It works fine when I try on a table with Int32 key.

When I try on a GUID key table, I just get an "Query affected 0 rows while 1 expected!" error.

This works fine:
```
[DisplayName("Id"), Column("id"), Identity]
    public Int32? Id
    {
      get { return Fields.Id[this]; }
      set { Fields.Id[this] = value; }
    }

    [DisplayName("Name"), Column("name"), Size(50), NotNull, QuickSearch]
    public String Name
    {
      get { return Fields.Name[this]; }
      set { Fields.Name[this] = value; }
    }

    [DisplayName("Primaryimage"), Column("primaryimage"), Size(500)]
    [ImageUploadEditor(FilenameFormat = "Person/PrimaryImage/~")]
    public String Primaryimage
    {
      get { return Fields.Primaryimage[this]; }
      set { Fields.Primaryimage[this] = value; }
    }

```

This gives me the error:
```
[DisplayName("Id"), PrimaryKey]
    public Guid? Id
    {
      get { return Fields.Id[this]; }
      set { Fields.Id[this] = value; }
    }

    [DisplayName("Name"), Column("name"), Size(50), NotNull, QuickSearch]
    public String Name
    {
      get { return Fields.Name[this]; }
      set { Fields.Name[this] = value; }
    }

    [DisplayName("Primaryimage"), Column("primaryimage"), Size(500)]
    [ImageUploadEditor(FilenameFormat = "Person/PrimaryImage/~")]
    public String Primaryimage
    {
      get { return Fields.Primaryimage[this]; }
      set { Fields.Primaryimage[this] = value; }
    }

```

I think it might have to do with the ~automatic naming scheme "{1:00000}/{0:00000000}_{2}". mentioned in the Movie tutorial: https://serenity.is/docs/tutorials/movies/adding_primary_and_gallery_images
Since it can't calculate the 1000 image/folder limit, when ID is not a number.

But even if I change the FilenameFormat to "Person/GalleryImages/img_{2}", it still fails. I assume it still tries to calculate {1} even when it's not used.

Any ideas how to fix it?

**Comment by hubeyb** [comment]
did you try to use Id and Guid together with changing the IdField on row?

> 
>  IIdField IIdRow.IdField
>         {
>             get { return Fields.Id; }
>         }

**Comment by gulgil** [comment]
In this case I can't edit the database, since it's not mine.

The example I provided was made on a test database.

**Comment by volkanceylan** [comment]
Assign the guid on create
