### ISSUE TITLE
core 2.2 problem

### ISSUE THREAD

**Issue by cengkaplan33** [volkanceylan/Serenity#4488]
Hi people.  when I migrated Microsoft.Netcore.App 2.1 to  Microsoft.Netcore.App 2.2.0.  , the following code block gives an error.

#if !COREFX
            Dependency.Resolve<IDependencyRegistrar>().RegisterInstance<ILocalTextRegistry>(new LocalTextRegistry());
            CommonInitialization.InitializeLocalTexts();
#endif

I'm really stuck here very badly. and I can't find a solution.
After netcore migrate serenity dll missed.  After I realized that problem I added all packages from nuget. then error count down to until 14 . 

can anyone help?

![serenitycore error](https://user-images.githubusercontent.com/3457947/59599527-72e63980-9107-11e9-9131-0d332444b98c.PNG)

**Comment by Brami-oh** [comment]
Hi,
I had the same problem, but I resolve like that : 
![image](https://user-images.githubusercontent.com/17801277/59703063-a51b9800-91e8-11e9-85db-6a3967fdc105.png)
