### ISSUE TITLE
Problem with Favorite Views

### ISSUE THREAD

**Issue by Marcod93** [volkanceylan/Serenity#4489]
Hi everyone, I have a problem when I enter the command in my grid

```
protected createToolbarExtensions() {
    super.createToolbarExtensions(); 

    new Serenity.FavoriteViewsMixin({
        grid: this
    });
}
```

the error is the following Property "'FavoriteViewsMixin' does not exist on type 'typeof Serenity'".
I got this code from Serenity Guide.

**Comment by brunobola** [comment]
That's a premium feature.

**Comment by Marcod93** [comment]
Thanks
