### ISSUE TITLE
Error after upgrading to latest version and using VS2019

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#4490]
I've got an error that prevent me from making changes from ts files and see them, I've tried the upgrade steps and get build succeeded but the changes aren't applied.

The error from vs output is the following:

``
1>------ Rebuild All started: Project: ScoreAPP.Web, Configuration: Debug Any CPU ------
1>  ScoreAPP.Web -> G:\Implementacoes\ID FABRY SCORE\ScoreAPP\ScoreAPP\ScoreAPP.Web\bin\ScoreAPP.Web.dll
1>  Executing TypeScript compiler...
1>  '"\node"' is not recognized as an internal or external command,
1>  operable program or batch file.
1>G:\Implementacoes\ID FABRY SCORE\ScoreAPP\ScoreAPP\ScoreAPP.Web\ScoreAPP.Web.csproj(1960,5): warning MSB3073: The command ""\node" "" -p ./tsconfig.json" exited with code 9009.
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
``

**Comment by brunobola** [comment]
@volkanceylan any tip please

**Comment by brunobola** [comment]
I've managed to make it work but just using old "TSC" line and 3.1.1 version even following the upgrade this was the only way for me.

**Comment by mrhb** [comment]
@brunobola  what do you mean about "using old "TSC" line and 3.1.1 version even following the upgrade this was the only way for me."
please explain more
thanks

**Comment by csabc** [comment]
> @brunobola what do you mean about "using old "TSC" line and 3.1.1 version even following the upgrade this was the only way for me."
> please explain more
> thanks
make sure that you can run the command "tsc" correctly using the cmd or powershell . you can change the Project file as below.
 `  <Target Name="CompileTSC" AfterTargets="AfterBuild" Inputs="@(CompileTSCInputs)" Outputs="wwwroot\Scripts\site\xx.Web.js">
    <Message Text="Executing TypeScript compiler..." Importance="high"></Message>
    <Exec Command="tsc -p ./tsconfig.json" ContinueOnError="true" />
  </Target>`
