### ISSUE TITLE
Show Dialog Button according to Current Row Status

### ISSUE THREAD

**Issue by mjacoup** [volkanceylan/Serenity#4498]
Here i need to show button will print current dialog or row only if it has specific status . The problem that when i try to check "this.entity" inside  getToolbarButtons it retrieve null and so can't show conditional button . any one know a slolution

 protected getToolbarButtons() {
            debugger;
            let buttons = super.getToolbarButtons();
            var ent = this.entity;
          
            if (ent != null) {
            if (ent.StatusType = WorkFlowStatusType.Approved_And_Closed) {
                buttons.push({
                    title: Q.text('Site.UserDialog.EditRolesButton'),
                    cssClass: 'edit-roles-button',
                    icon: 'icon-people text-blue',
                    onClick: () => {
                        if (this.entity.LeaveRequestId != 0) {
                            alert('s');
                        }
                    }
                });
                }
            }

**Comment by mafdy** [comment]
You can add the button without condition, then you can do whatever you want for this button (hide, disable, rename...etc) but you can do that inside another method which is afterLoadEntity, as you can get an entity value just after the entity has been loaded, not before.
for ex:
```
protected afterLoadEntity() {
     super.afterLoadEntity();
     if (this.entity.LeaveRequestId != 0) {
           // you can disable it, or remove it, or whatever you want.
           this.toolbar.findButton('edit-roles-button').toggleClass('disabled', false);
     }
}
```
Hope this can help 
أي خدمة يا هندسة 🤓

**Comment by mjacoup** [comment]
> You can add the button without condition, then you can do whatever you want for this button (hide, disable, rename...etc) but you can do that inside another method which is afterLoadEntity, as you can get an entity value just after the entity has been loaded, not before.
> for ex:
> 
> ```
> protected afterLoadEntity() {
>      super.afterLoadEntity();
>      if (this.entity.LeaveRequestId != 0) {
>            // you can disable it, or remove it, or whatever you want.
>            this.toolbar.findButton('edit-roles-button').toggleClass('disabled', false);
>      }
> }
> ```
> 
> Hope this can help
> أي خدمة يا هندسة 🤓

excellent many tanks my tech hero :)
