### ISSUE TITLE
Where to import modules ??

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4499]
I want to:

`import { Calendar } from '@fullcalendar/core';`

I have installed @fullcalendar using npm:

`npm install --save @fullcalendar/core `

now I want to use this module in the xyzGrid.ts file 
where can I put the import statement ???

**Comment by volkanceylan** [comment]
We use namespaces, not modules

**Comment by jsguru-git** [comment]
Hi @volkanceylan 
Could you explain in more details?
I need to use toJSON function from 'cssjson' npm package.
But I could not import toJSON in xyzEditor.ts
import { toJSON } from 'cssjson'
