### ISSUE TITLE
How to add grid filter editor for an enum field?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#45]
Hi,

I can add filter editor into toolbar for any field in Grid screen.

````csharp
protected override void CreateToolbarExtensions()
        {
            AddEqualityFilter<LookupEditor>(SomeRow.Fields.FirmaId,
               options: new LookupEditorOptions { LookupKey = "LookupKey" });
        }
```
But if i add enum type field i do not know what is lookup key for an enum. 
I found a key in Project.Sciprt.js file, like this:

Project.Module.....SomeEnumTypeId 

if i use this gives error "there is no lookup in registered list bla bla bla"

I means ***enum type field***
```csharp
public class XXXRow:...
{
...
public SomeEnumTypeId Field1{
get{....}
set{...}
...
}
```

**Comment by VictorTomaili** [comment]
Hi ademc,
There is a sample for your question. 
 
[Enum description](https://github.com/volkanceylan/Serene/blob/a4f4a9a5f52fcc7422898798139de4f2d7c3499c/Serene/Serene.Web/Modules/Northwind/Order/OrderShippingState.cs)
[Grid Toolbar Extension](https://github.com/volkanceylan/Serene/blob/8d846906bdd211bc80c48b287b0f8f85c34f0e01/Serene/Serene.Script/Northwind/Order/OrderGrid.cs#L26-L27)

**Comment by ademc** [comment]
Thanks victor i did not see

**Comment by VictorTomaili** [comment]
I didnt see too :smile: sorry for late answer.
