### ISSUE TITLE
Adjusting SQL 

### ISSUE THREAD

**Issue by SenderTsx** [volkanceylan/Serenity#450]
Dear Volkan,

first of all, huge thank to this very impressive Work!

I have one question: Is it possible to adjust/Customize the SQL so for example, I will only see products from Germany or Turkey when I click the Northwind Products page?

Right now I see everything, but I would love to "filter" this.

Unfortuanely I was not able to find any kind of SQL script in the Code. Could you please inform me, where the direct connection to the database is made? in which module?

Best Regards,
Hüseyin

PS: I am know that this is not a issue, but its a deep request from my side. Any help is highly appreciated!!

**Comment by volkanceylan** [comment]
You can use AddEqualityFilter method in grid or if you need more customization, override OnViewSubmit method and set Criteria request parameter. See GridFilteredByCriteria sample, under BasicSamples section in Serene.

**Comment by SenderTsx** [comment]
Thank you very much!

I am curious: Where do acutally connect to the database and "take" the datas?. 
I have expected somewhere sth like a SQL satement, but I have not found anything.
Sorry if this question is dump, but i am really absolutely new in web programming.

Tessekürler,
Hüseyin Kasapoglu

**Comment by jsbUSMC** [comment]
The database connection is in the web.config file of your Serenity.Web project. Serenity uses dapper.net to compose SQL statements and they are part of the Serenity assemblies. You can add your own editors, attributes, and statements that query the data source using LINQ style queries in your script classes for client-side or server-side projects. I suggest reading through the Serenity Developer Guide and following along with the Movie tutorial to get a good grip on the Serenity system.

**Comment by volkanceylan** [comment]
As @jsbUSMC pointed out, Serenity generates dynamic SQL behind the scenes for everything. Base classes, particularly ListRequestHandler generates a query with our Select builder (SqlQuery) using information in your row class based on list request parameters. Anyway its possible to customize these queries by modifying row, overriding relevant ListRequestHandler methods, or writing your own handler manually. If you want to see whats going on, you need to clone Serenity, replace Nuget references with project references and debug a list request starting from your XyzEndpoint List method.

**Comment by JohnRanger** [comment]
**Hint:** If you just want to see the SQL Statements being fired towards the SQL Server, set loglevel to debug in web.config and look at the log files in App_Data/Log. --> Very impressive if you for example type something slowly into a grid search box :-)
