### ISSUE TITLE
Master-Detail; Putting details on different tab but still using full functionality of builtin-Master Detail

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4500]
Dear all,

I have studied issue [https://github.com/volkanceylan/Serenity/issues/1818](url) as well as the demo project but I have to admit that I don't get it by the information provided there how to use Master-detail functionality of Serenity and "simply" move a detail grid / editor to another tab to segregate detail infos. I will have about 5 different detail sections linked with one master - and I would like to continuously let Serenity Framework handle the in-memory editing of the details and the deleting of details when the master is deleted.

I have created the HTML template and the desired tabs are properly displayed (changed the position of the toolbar to be above all tabs) and this works fine so far. But how to move a part of the form "fields" to another tab I cannot figure out.

All examples - including the ones provided of the demo project - seem to use completely separate "detail" grids (e.g. Order) and doing the handling of the details all server-side and not in-memory.

Question: If I already have a working Master-detail form - is there no "easy" solution to just let a certain part of the form be displayed within a separate TAB?

Like this:
```cs
public class ChainSpanningLayoutSetsForm
    {
        [Hidden]
        public Int32 ChainSpanningLayoutSetId { get; set; }

        [Category("Db.ChainSpanningLayoutSet")]
        public String ChainSpanningLayoutSetName { get; set; }

        [Category("Db.CheckInStatus")]
        [BooleanSwitchEditor(Css = "label-success")]
        public Boolean ChainSpanningLayoutSetisCheckedIn { get; set; }

        public String CheckInStatus { get; set; }

        [TextAreaEditor(Rows =8)]
        public String ChainSpanningLayoutSetDescription { get; set; }

This below should go to a separate tab
---------------------------------------------------------------------------

        [Category("Db.Chains.Chains.EntityPlural")]                       
        public List<Entities.ChainSpanningLayoutSetsDetailsRow> DetailList { get; set; }   

---------------------------------------------------------------------------
This above should go to a separate tab

        [Category("Db.Versionning")]
        public String ChainSpanningLayoutSetVersion { get; set; }
        public Guid ChainSpanningLayoutSetKey { get; set; }
        
        public String ChainSpanningLayoutSetCheckedInByUserUsername { get; set; }
        public Int32 ChainSpanningLayoutSetCheckedInByUserId { get; set; }

        [DateTimeKind(DateTimeKind.Local)]
        public DateTime ChainSpanningLayoutSetTimestampLastModified { get; set; }
        public DateTime ChainSpanningLayoutSetTimeStampLastCheckout { get; set; }

        public String ChainSpanningLayoutSetCheckedOutByUserUsername { get; set; }
        public Int32 ChainSpanningLayoutSetCheckedOutByUserId { get; set; }
    }
```

This would then be accessible like this:

![Serenity-Tabs](https://user-images.githubusercontent.com/2699447/60286029-312b6f00-990f-11e9-8321-cd635fa2881d.png)

Thanks for your feedback and
 
with kidn regards,

John

**Comment by wezmag** [comment]
Use Tab attribute.
```
public class OrderDetailForm
{
    [Tab("Tab1")]
    public Int32 OrderId { get; set; }
    public Decimal Width { get; set; }
    [Tab("Tab2")]
    public Decimal Height { get; set; }
    public Int32 Amount { get; set; }
}
```

**Comment by JohnRanger** [comment]
@wezmag ,

thank you for this info. That is exactly what I need. As I am using SF 2.9.24, this seems not yet available - but I will backport it from a more recent version.

With kind regards,

John

**Comment by JohnRanger** [comment]
@All, 
it was too difficult to port back as parts of Serenity Framework in V2.9.24 were still done in Saltarelle at that time - especially the entityDialog.

Therefore I have now forward ported the whole project - and - after ironing out some ugly problems with old assemblies within GAC and visual studio/environment problems, the actual migration from a Serene 2.9.24-based project to a current 3.9.9 SF / 3.9.6 Serene-based project was extremely smooth. Done within ca. 8h of work (and it took so long because I am not a professional dev).

I have now again a stable project environment as before - but now with newest Visual Studio 2019 and an up-to-date Serene/Serenity-based app.

Really - Really 👍 Thank you @volkanceylan !! 👍  for keeping the stuff *just* working between such a big version gap and so much technology change under the hood.

My deep apreciation for this. 

With kind regards,

John

**Comment by Garozh** [comment]
@JohnRanger 

Is this working for you?

When I use a detail Editor in a tab, the data is not loading correctly in the details on startup. I only see "half" of the input row values. Only when changing between the tabs again the data is shown correctly.
