### ISSUE TITLE
The command tsc.exe -p tsconfig.json exited with code 127

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#4504]
Hello

My project works well in Windows. However, on Mac it has an error when compiling with TypeScript.

Run by hand in a tsc -p ./tsconfig.json console then it does work.

But with "dotnet run" or "dotnet watch run" it does not work.

I have created a new project with "serin" and it presents the same problem.

I have:
Node: v12.4.0
NMP: 6.9.0
TSC: Version 3.5.2

`<Target Name="CompileTSC" AfterTargets="AfterBuild" Inputs="@(CompileTSCInputs)" Outputs="wwwroot\Scripts\site\Serene1.Web.js">
    <Message Text="Executing TypeScript compiler..." Importance="high"></Message>
    <Exec Command="&quot;$(TscToolPath.Replace('build\\..\tools\', 'tools\'))\tsc&quot; -p ./tsconfig.json" ContinueOnError="true" />
  </Target>`

<img width="1098" alt="Captura de Pantalla 2019-06-28 a la(s) 10 38 48" src="https://user-images.githubusercontent.com/11929923/60350335-53fe6780-9991-11e9-9b4e-3346cf8940c0.png">

I think the problem is in the path "Applications/Microsoft SDKs/TypeScript\tsc".

**Comment by RKayCH** [comment]
TSC compilation issues can be tedious. I was struggling with one for nearly a week, ended up doing a fresh project and just copy-pasting my code back into it. 

Are there any other errors reported - or any "non-build-errors" showing up on any TS files ?
Have you tried reinstalling the nuget package for TypeScriptBuild?

**Comment by ArsenioInojosa** [comment]
Yes, I have already tried that option. The problem happens even with a new project.

I have installed the package "Microsoft.TypeScript.MSBuild" Version = "3.1.1". That is the version that comes by default, I have not updated it because the new one causes problems even in Windows.

**Comment by RKayCH** [comment]
MSB3073 often (often, not always) is coming from file access issue, so youre guess with the path might be correct.

Try to run the tsc command directly from the Project folder  containing the tsconfig.json 
via PowerShell - that often gives you more details.

**Comment by ArsenioInojosa** [comment]
I already said that running "ts -p ./tsconfig.json" in the console works. It's what I've been doing so far to be able to work.

The problem is Mac OS, in Windows there are no problems.

**Comment by RKayCH** [comment]
i'll ask my buddy on monday, he's doing doing a lot of Core stuff on mac, maybe he has an idea.

**Comment by ArsenioInojosa** [comment]
Hello,

After updating TypeScript and Microsoft.Typescript.Msbuild to version 3.5.2, now the problem also occurs in Windows.

To make it work you have to generate the TS manually with the command "ts -p ./tsconfig.json"

warning MSB3073: The command ""C:\Users\Arsenio\.nuget\packages\microsoft.typescript.msbuild\3.5.2\build\..\tools\tsc\tsc.js\tsc" -p ./tsconfig.json" exited with code 267.

**Comment by brunobola** [comment]
Just keep Typescript in version 3.1 not 3.1.1

**Comment by volkanceylan** [comment]
Please check the document here:

https://serenity.is/docs/startsharp/updating-startsharp

The part about Serenity 3.8.5:

This is not actually an issue about Serenity itself, but you might have this problem if you choose to update Microsoft.TypeScript.MsBuild in your Serene/StartSharp project.

TypeScript no longer has a tsc.exe file and it uses NodeJS instead of Chakra (Edge) so you need to update your .CSPROJ file, find CompileTSC section in your project file and replace it like below:
```xml
<Exec Command="&quot;$(NodePath)\node&quot; &quot;$(TSJavaScriptFile.Replace('build\\..\tools\', 'too....
```

**Comment by Garozh** [comment]
@volkanceylan I was searching so long to find the place where the tsconfig.json is called and with your help finally got a solution.

thanks alot
