### ISSUE TITLE
Unable to recompile the project after "Transform All T4 Templates" because of locked DLLs

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#4505]
This happens every time I run "Transform All T4 Templates". I have to either wait about 5 minutes or restart Visual Studio and reload the project to be able to recompile. Any ideas why rebuilding templates would lock all the project DLLs? Many thanks in advance for help in resolving this frustrating issue. 

1>------ Rebuild All started: Project: LCReservations.Web, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\FluentMigrator.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\FluentMigrator.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\MimeKit.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\MimeKit.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Newtonsoft.Json.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Newtonsoft.Json.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Core.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Core.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Data.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Data.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Data.Entity.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Data.Entity.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Services.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Services.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Web.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\Serenity.Web.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\StackExchange.Exceptional.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\StackExchange.Exceptional.dll' because it is being used by another process.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4604,5): warning MSB3061: Unable to delete file "C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\System.Web.Mvc.dll". The process cannot access the file 'C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\System.Web.Mvc.dll' because it is being used by another process.
1>  LCReservations.Web -> C:\ngs-projects\LCReservationsProduct\LCReservations\LCReservations.Web\bin\LCReservations.Web.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by JohnRanger** [comment]
Hi all, I observe this problem also with a fresh serene 3.9.6.x project (newest available on VS marketplace).

Conditions like typescript version >xxxx and Nodejs >yyyy are fulfilled (Typescript and NodeJS are on newest available versions).

This is with Visual Studio 2017, most current update.

Also it seems that NodeJs has a problem after the 1st T4 run as the black command window is not launched anymore after it shows the lines that the transformation is complete.

Any help to solve this is greatly appreciated.

P.S: Contrary to that, my "good old" V2.9.24-based Serenity Project compiles/runs perfectly on the same machine, same Visual Studio.

With kind regards,

 John

**Comment by JohnRanger** [comment]
Hi all,

this seems to be a general problem of Visual Studio. See this issue here:https://developercommunity.visualstudio.com/content/problem/221300/warning-msb3061-unable-to-delete-file.html

The temporary workaround for this is, to kill the "VBCSCompiler.exe" process.

With kind regards,

John

**Comment by c9482** [comment]
Hi @JohnRanger. Many thanks for the workaround - it works!

**Comment by JohnRanger** [comment]
Hi @c9482 ,

see my just now updated comment. I have it now automated via pre-build events.

John

**Comment by c9482** [comment]
Awesome, this solution makes the annoying problem disappear. Thanks for your help again.

**Comment by JohnRanger** [comment]
For all of you, have made a quick Wiki article about the automated workaround.

See here: https://github.com/volkanceylan/Serenity/wiki/Visual-Studio:-Workaround-for-locked-files-when-trying-to-build

With kind regards,

John
