### ISSUE TITLE
PermissionKey Issue

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4506]
Hello everyone! and @volkanceylan 
First I will explain the issue 
I created new User with name **SalesOrder** by assigning permissions
but when I click on the navigation link of sales order form it shows error
![Screenshot (30)](https://user-images.githubusercontent.com/39983941/60427840-2c1f3600-9c15-11e9-8347-4b9273dd3896.png)
and when I click on the 
new button it shows another error
![Screenshot (31)](https://user-images.githubusercontent.com/39983941/60427881-3fca9c80-9c15-11e9-9f93-79650c098ff1.png)
Just because amusing **tbl_networkorder** ForeignKey in **sales order** form do I need to set  the access permission to **tbl_NetworkOrder** form

Hope this information is enough
Thanks in advance!

**Comment by jmkamran** [comment]
I have a solution. Subscribe it
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q/
