### ISSUE TITLE
Slick.Aggregators.Sum(Avg('XYZ'))

### ISSUE THREAD

**Issue by WendyBurgerHsu** [volkanceylan/Serenity#4507]
Hi, does anyone know how can just only Sum the Grouping number?

![image](https://user-images.githubusercontent.com/44994587/60561600-a622fc80-9d86-11e9-935e-1cef9161b6a9.png)

I hope: 19 + 3.5 + 413 + 1879.5 + 500 + 4539 + 1549 = 8903
Not the "total" sum 17970

Thanks!

**Comment by volkanceylan** [comment]
No you cant
