### ISSUE TITLE
LeftJoin in MasterDetailRelation (detail side)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#451]
Dear @volkanceylan,
I've successfully implemented a MasterDetailRelation, but I'm facing a strange problem when I try to show a left joined valued on the detail table (in the master dialog).
Here there is the code of detail row:
![image](https://cloud.githubusercontent.com/assets/17425690/13994634/129286c6-f126-11e5-99ec-e8a7b8ccba79.png)

Here instead the code of the columns.cs:
![image](https://cloud.githubusercontent.com/assets/17425690/13994663/2b618544-f126-11e5-9767-9d04a464fcc3.png)

And finally, here the result:
![image](https://cloud.githubusercontent.com/assets/17425690/13994548/a62c5926-f125-11e5-9e5e-b7ff197af9fe.png)

What I'm doing wrong? I checked ten thousands time and the syntax that I've used is the same that is perfectly working in the rest of the application...

Thanks for your support
Best Regards

P.S. I haven't forgotten my promise to fill the wiki page, but I have to complete this project before the end of month!

**Comment by volkanceylan** [comment]
If this problem is about opening an existing Ticket record, you don't have [MinSelectLevel(SelectLevel.List)] on your ActionDescription field. It was stated in master detail tutorial. 

If about adding, you should handle filling it in your ValidateEntity method.

**Comment by marcobisio** [comment]
You're right...I totally forgotten that setting...but please, if you have a bit of time, could you kindly explain the behaviour of the different Select Levels?

Thanks

**Comment by volkanceylan** [comment]
Here you go

https://volkanceylan.gitbooks.io/serenity-guide/content/services/list_request_handler.html

**Comment by marcobisio** [comment]
Thank you very much!
