### ISSUE TITLE
How to set default datepicker format to dd/MM/yyyy for all language in net core?

### ISSUE THREAD

**Issue by underwaterhp93** [volkanceylan/Serenity#4512]
I try to set <globalization culture="vi-VN" uiCulture="auto:vi-VN" /> in web.config but it seem does not work

**Comment by WendyBurgerHsu** [comment]
in your xyzColumns.cs:
[DisplayFormat("dd/MM/yyyy")]
public DateTime xyzDate { get; set; }

**Comment by WendyBurgerHsu** [comment]
Or change JavaScript in .ts:
$("#xyzDate").datepicker({
	changeMonth: true,
	changeYear: true,
	dateFormat: 'dd/MM/yyyy'
});
