### ISSUE TITLE
How to create a custom grid in a custom dialog

### ISSUE THREAD

**Issue by xuliujian2019** [volkanceylan/Serenity#4513]
I want to create a custom dialog which includes a custom grid. The dialog is extended from TemplatedDialog. It can display normal. Now, i want to create a custom grid in the dialog. 

This is my custom dialog:
**CheckRecordDetailDialog.ts**

    @Serenity.Decorators.registerClass()
    export class CheckRecordDetailDialog extends Serenity.TemplatedDialog<any> {
                                                                         
        constructor(container: JQuery, id:number) {
            super(container);

            var detailGrid = new AcsServer.ShippingDetect.CheckDataGrid($('#DetailDataGrid'));
            detailGrid.init();
            detailGrid.loadDetailData(id);

            Q.initFullHeightGridPage($('#DetailDataGrid'));
        }

        protected onDialogOpen() {
            super.onDialogOpen();  
        }
    }

CheckDataGrid is my custom grid. It can display in my dialog. But i encountered following issues:
1.  I want to load data when the dialog shows. If i move the **loadDetailData** method to onDialogOpen, it will display error which says can not find property loadDetailData.
2. I update the CheckDataService to customize the List request. The ts file(serverType) is generated correctly, however, in visual studio, it shows "can not find name 'CheckDataListRequest'".

`export declare function List(request: CheckDataListRequest, onSuccess?: (response: Serenity.ListResponse<CheckDataRow>) => void, opt?: Q.ServiceOptions<any>): JQueryXHR;`

**CheckDataListRequest.cs**

```
public class CheckDataListRequest : ListRequest
{
      public int SnId { get; set; }
}
```

3. How can i modify the grid shown columns dynamically? In other word, i want to determine the display column according with the retrieved data instead the default list method. Is there a sample for that?

It is very appreciated.

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerDialog.ts

**Comment by anaiappan1899** [comment]
How to add comment section in serenity ? @volkanceylan

**Comment by VictorTomaili** [comment]
Check the customers grid sample, notes tab.  

https://demo.serenity.is/Northwind/Customer#edit/1
