### ISSUE TITLE
Check total a column when the input

### ISSUE THREAD

**Issue by vnkrsvda** [volkanceylan/Serenity#4514]
Hello everyone,
Where am i wrong, please just help me.
Thanks everyone!

![Orders](https://user-images.githubusercontent.com/52552424/60696409-cf22c900-9f0f-11e9-83c7-a34c37dfb0e7.png)

**Comment by Zahar661** [comment]
var sumr = connection.Query<decimal>("SELECT SUM(Amounts) From dbo.Order where GroupId="+Row.GroupId).FirstOrDefault();

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/60698477-92030a80-9f00-11e9-88a8-c2fc4ea114ea.png)
The breakpoint should be later. There is no query result yet.

**Comment by vnkrsvda** [comment]
Thanks @Zahar661, it worked.
