### ISSUE TITLE
EntityGrid: gridPersistanceFlags.quickSearch not working as expected

### ISSUE THREAD

**Issue by hannesb** [volkanceylan/Serenity#4516]
If you set the quickSearch flag to true in EntityGrid.getPersistanceFlags, the quick search criteria is not always persisted.

Steps to reproduce with Northwind sample:
- Add protected gridPersistanceFlags(): Serenity.GridPersistanceFlags { return { quickSearch: true }; } to CustomerGrid.ts
- Start sample
- enter i.e. 'be' in quick search field of customer grid
- go to another grid, i.e. products
- go back to customer grid. Expected result: Quick filter is set to 'be', but it is not!
- enter 'be' again, and make some change to the layout (i.e. change column order)
- go to another grid, i.e. products
- go back to customer grid. Expected result: Quick filter is set to 'be'. Now it is!
- change the quick search criteria to something else
- go to another grid, i.e. products
- go back to customer grid. Quick filter is set back to 'be', not what you entered last!

-> it seems that a call to persistSettings() is missing after the quick search criteria was changed

**Comment by hannesb** [comment]
There is a related issue when using EntityGrid.getQuickSearchFields. The column the user has selected for quicksearch is not always persisted.

**Comment by volkanceylan** [comment]
Fixed 9e09829a768d7e6773f585acc11ff414ee2cc463
