### ISSUE TITLE
How to set value in Editor (Inline editable grid)

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4518]
Hello everyone!
Am working on the Inline editable grid and I successfully create that
Now, I want to insert some data into the fields on the change event of  fields from the same grid
![Capture10](https://user-images.githubusercontent.com/39983941/60723717-09ad5580-9f52-11e9-9692-a8d98f101404.PNG)
As you can see on the change event of the item I want to insert value in material_description textbox
Code--->
private inputsChange(e: JQueryEventObject) {
            var cell = this.slickGrid.getCellFromEvent(e);
            var item = this.itemAt(cell.row);
            var input = $(e.target);
            var field = input.data('field');
            var text = Q.coalesce(Q.trimToNull(input.val()), '0');//ItemId
            var pending = this.pendingChanges[item.__id];

            var effective = this.getEffectiveValue(item, field);
            var oldText: string = input.hasClass('numeric')
                ? Q.formatNumber(effective, '0.00')
                : effective as string;

            var value;
            if (field == "ItemId") {
                var Descr = Premier.TblItemRow.getLookup().itemById[text].Material_Description;
                var f1 = this.element.find(' Material_Description');
            }
            if (field == "Quantity") {
                var Quantity = text;
                var rate = item.Rate;

            }
            if (field == "Rate") {

            }
        }

Am able to get the Description of the selected ItemId in the **var Descr**
but am unable to find Material_Description element in the editor

Hope this is enough explanation
Thanks in advance!

**Comment by jmkamran** [comment]
Hay dear you should implement serenity.extra in your project. and give bundle of thanks to @dfaruque
and if you want how to implement than see this link and subscribe my channel.
https://www.youtube.com/watch?v=FwFFi_AFrSA&t

**Comment by ra-bedo11** [comment]
> Hay dear you should implement serenity.extra in your project. and give bundle of thanks to @dfaruque and if you want how to implement than see this link and subscribe my channel. https://www.youtube.com/watch?v=FwFFi_AFrSA&t
https://www.youtube.com/watch?v=FwFFi_AFrSA&t
This Link
Its Closed Why????
