### ISSUE TITLE
Why are 2 themes, adminlte, jQuery UI?

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#452]
In the end which ah, which can be used to customize the primary key character string,Jquery UI embedded DLL Libuka it

**Comment by volkanceylan** [comment]
It's hard to understand your english? but jQuery UI is not a theme, just used for dialogs, widgets etc._

**Comment by 107295472** [comment]
Script data Columns.Storage.Test is not found in registered script list!  This error, can not find where the problem

**Comment by 107295472** [comment]
Translated

**Comment by volkanceylan** [comment]
Do you have ColumnsScript("Storage.Test") somewhere in your web project?

**Comment by volkanceylan** [comment]
If there is,  try rebuilding solution

**Comment by 107295472** [comment]
Wow, good, there is no batch delete

**Comment by 107295472** [comment]
I want to give a primary key assignment, the string type key, where the assignment.
