### ISSUE TITLE
Authentication Error while working on system

### ISSUE THREAD

**Issue by mjacoup** [volkanceylan/Serenity#4523]
While testing the web application suddenly it gives me the following error and if if make refresh it redirect me to the login page .
![image](https://user-images.githubusercontent.com/1003656/60932571-ec181d00-a2be-11e9-9744-38f312e7f484.png)

**Comment by edwardch** [comment]
Looks like you were logged out. This can happen if you leave the application idle for too long and then try do an action.

**Comment by mjacoup** [comment]
No it works while i'm working on the application .. please i need help if any one face these problem also

**Comment by mjacoup** [comment]
It doesn't happen locally , it is happen only when the application is hosted online

**Comment by mafdy** [comment]
@mjacoup 

This happens because of the session timeout.

According to my knowledge, there are two workarounds:
1- Login Persist: "keep the user logged in"
         AccountController >> public Result<ServiceResponse> Login(--).

2- Cookie expiration: "make it expires after a very long time"
        Startup.cs >> public void ConfigureServices(--).

Hope this helps.

**Comment by mjacoup** [comment]
Thanks Mafdy for the help...  I realized that our host was limiting memory
of IIS dedicated pool to 256 .. So when reach to this limit , IIS make
restart and all looged session terminated.

**Comment by jmkamran** [comment]
you should to change timeout  in web.config 
 <authentication mode="Forms">
      <forms loginUrl="~/Account/Login" timeout="30" path="/" slidingExpiration="true" />
    </authentication>
if you want to get more help subscribe my channel 
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q

**Comment by mjacoup** [comment]
Hi di

> you should to change timeout in web.config
> 
> ```
>   forms loginUrl="~/Account/Login" timeout="30" path="/" slidingExpiration="true" 
> ```
> 
> if you want to get more help subscribe my channel
> https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q

please read my reply
