### ISSUE TITLE
using expression max to left join in Row

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4524]
Halloo All,
I have an issue if using expression of Row, I want left join with a max due date , that's code below, Please Correct , thank you 
` [DisplayName("Lead Id"), Identity,
        ForeignKey("tActivity", "ParentId"), LeftJoin("a")]
        public Int32? LeadId
        {
            get { return Fields.LeadId[this]; }
            set { Fields.LeadId[this] = value; }
        }

        [DisplayName("last due date ") ,Expression("max(a.[duedate]) group by a.parentId")]
        public DateTime? LastActivityDate
        {
            get { return Fields.LastActivityDate[this]; }
            set { Fields.LastActivityDate[this] = value; }
        }
`

**Comment by edwardch** [comment]
You could also try this in xyzRow.cs
```cs
[DisplayName("Lead Id"), Identity]
[ForeignKey("(SELECT ta.parentId, MAX(ta.[duedate]) AS LastActivityDate FROM tActivity ta GROUP BY ta.parentId)", "parentId"), LeftJoin("a")]
```
I haven't tried that myself but it should work. If not, try creating a view and referencing that as your ForeignKey.
```sql
CREATE VIEW vwMaxMinActivityDates AS
SELECT 
	ta.parentId, 
	MAX(ta.[duedate]) AS LastActivityDate, 
	MIN(ta.[duedate]) AS FirstActivityDate
FROM tActivity ta GROUP BY ta.parentId
```
*_I included the MIN as well in case you need to use the first activity date too._
In xyzRow.cs
```cs
[ForeignKey("[dbo].[vwMaxMinActivityDates]", "parentId"), LeftJoin("a")]
```

Then to get your date you can just use something like this.
```cs
[DisplayName("Last Due Date"), Expression("a.LastActivityDate"))]
public DateTime? LastActivityDate
{
    get { return Fields.LastActivityDate[this]; }
    set { Fields.LastActivityDate[this] = value; }
}
```

If you get any query errors take a look at the queries being generated in [SQL Server Profiler ](https://www.mssqltips.com/sqlservertutorial/3502/how-to-launch-a-sql-server-profiler-session/) and try work it out from there.

**Comment by resitaufan** [comment]
thank you @edwardch, I am using that too,  with create a new View,
but is it possible without cretae view?

**Comment by edwardch** [comment]
It should work using the first code block in my comment, then you can ignore code block 2 and 3...

**Comment by resitaufan** [comment]
yes, before you give a solution, I have done a issue with create view.. and i want a solution without generate a new view because it will make many source.. but thanks a lot

**Comment by hannesb** [comment]
What about a subselect instead of a join?

Expression("(SELECT Max(duedate) FROM tActivity WHERE ParentId = T0.LeadId)")

**Comment by resitaufan** [comment]
@hannesb ok i want to try. thank you

**Comment by resitaufan** [comment]
please help me  in issue #4527 @edwardch and @hannesb .
