### ISSUE TITLE
Type Serene1.Premier.CustomerUnitListReport can't be registered as a lookup script!

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4525]
Hello everyone!
I have implemented reports by referring  CustomerGrossSaleReport and I want to give permission for that report and am unable to give that
if I add [lookupscript] then its shows error

Type Serene1.Premier.CustomerUnitListReport can't be registered as a lookup script!
code 
`
namespace Serene1.Premier
{
    using Entities;
    using Serene1.DomesticOrder.Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using Serenity.Reporting;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Drawing;

    [Report,ReadPermission(PermissionKeys.ReportsPremier.View)]
    [ModifyPermission(PermissionKeys.ReportsPremier.Modify)]
    [DeletePermission(PermissionKeys.ReportsPremier.Delete)]
    [Category("Premier/Design"), DisplayName("Customer Unit List")]
    [LookupScript("Premier.ReportsPremier", Permission = "?")]
    public class CustomerUnitListReport : IReport, IDataOnlyReport
    {
        [LookupEditor(typeof(TblNetworkOrderRow))]
        public Int32? NetworkOrderId { get; set; }

        //[DisplayName("Start Date")]
        //public DateTime? StartDate { get; set; }

        //[DisplayName("End Date")]
        //public DateTime? EndDate { get; set; }

        public object GetData()
        {
            using (var connection = SqlConnections.NewFor<Entities.TblItemRow>())
            {
                return connection.Query<Item>("Report_CustomerUnitList",
                    param: new
                    {
                        @NetworkOrderId = NetworkOrderId
                    },
                    commandType: System.Data.CommandType.StoredProcedure);
            }
        }

        public List<ReportColumn> GetColumnList()
        {
            return ReportColumnConverter.ObjectTypeToList(typeof(Item));
        }

        //[BasedOnRow(typeof(Premier.Entities.TblItemRow), CheckNames = false)]
        public class Item
        {
            [DisplayName("Object ID")]
            public string UnitAssemblyNo { get; set; }
            [DisplayName("Object Description")]
            public string Material_Description { get; set; }
            public decimal Quantity { get; set; }
            [DisplayName("Unit")]
            public string UnitName { get; set; }

        }

        //public class AmountDecorator : BaseCellDecorator
        //{
        //    public override void Decorate()
        //    {
        //        var item = this.Item as Item;
        //        if (item.GrossAmount > 1000)
        //            Foreground = Color.Red;
        //        else if (item.GrossAmount > 500)
        //            Foreground = Color.Orange;
        //    }
        //}
    }
}`

![Capture11](https://user-images.githubusercontent.com/39983941/61024075-14d90900-a3ca-11e9-9c9b-07d87a07a2dc.PNG)

**Comment by volkanceylan** [comment]
Report and lookup script??
