### ISSUE TITLE
DateFormatter for month name

### ISSUE THREAD

**Issue by fwd079** [volkanceylan/Serenity#4526]
Hi, 

Need some guidance please. 
Unless missing something, Formatters in Serenity do not seem to provide anyway to go for `yyyy MMMM` that would in turn give a `2019 July` back, out of the box. Do not want to use moment.js as that's an overkill for just one task.

Currently using this hack on client side for month names:

```
public GetMonthName(month: number): string {
            switch (month) {
                case 1:
                    return "January";
                case 2:
                    return "February";
                case 3:
                    return "March";
                case 4:
                    return "April";
                case 5:
                    return "May";
                case 6:
                    return "June";
                case 7:
                    return "July";
                case 8:
                    return "August";
                case 9:
                    return "September";
                case 10:
                    return "October";
                case 11:
                    return "November";
                case 12:
                    return "December";
                default:
                    return "ERROR";
            }
        }
```

Anything missed, please point me to right direction, as search on Git and serenity website was futile.

Kind Regards.

**Comment by edwardch** [comment]
In your xyzColumn.cs use this:
```cs
[DisplayFormat("yyyy MMMM")]
public DateTime YourDateTimeField { get; set; }
```

**Comment by fwd079** [comment]
> In your xyzColumn.cs use this:
> 
> ```cs
> [DisplayFormat("yyyy MMMM")]
> public DateTime YourDateTimeField { get; set; }
> ```

No tried that and almost everything else can think of, but that doesn't work unfortunately. Gives me 2018 0606 for June 2018.

![image](https://user-images.githubusercontent.com/7912632/61046762-d3e6f180-a3d5-11e9-9e48-c3a29c602848.png)

![image](https://user-images.githubusercontent.com/7912632/61046776-dcd7c300-a3d5-11e9-96c1-1f7e491324da.png)

Environment is .NET MVC not .NET Core MVC, if it helps. Please let me know if I missed anything.

Kind Regards.

**Comment by edwardch** [comment]
That's odd because it worked for me, I tested before I posted my comment. 

Another (lazy) option is to add a field to xyzRow.cs
```cs
[Expression("FORMAT(T0.[PayDate],N'yyyy MMMM')")]
public DateTime? PayDateYearMonth
```

**Comment by fwd079** [comment]
Hi again,

Format doesn't work but yes you are correct about lazy option, that doesn't return desired results though because this `FORMAT` returns a `varchar` and thus, no ordering is possible. 
But thank you for your efforts. Appreciated.

Kind Regards.

**Comment by fwd079** [comment]
So, could not make it work, the current workaround in place, for anyone else having same problem:

```
protected getColumns()
{
	let columns: Slick.Column[] = super.getColumns();
	columns[0].format = ctx => GetMonthName(parseInt(Q.formatDate(ctx.value, "MM"))); // Gives 01,02 etc.
	return columns;
}

public GetMonthName(month: number): string
{
	switch (month)
	{
		case 1:
			return "January";
		case 2:
			return "February";
		case 3:
			return "March";
		case 4:
			return "April";
		case 5:
			return "May";
		case 6:
			return "June";
		case 7:
			return "July";
		case 8:
			return "August";
		case 9:
			return "September";
		case 10:
			return "October";
		case 11:
			return "November";
		case 12:
			return "December";
		default:
			return "ERROR";
	}
}
```

Regards.

**Comment by minhhungit** [comment]
how about this approach, I used momentjs library

>moment('2019/09/25', "YYYY/MM/DD").format("MMMM DD, YYYY")

=> result: "September 25, 2019"

**Comment by fwd079** [comment]
> how about this approach, I used momentjs library
> 
> > moment('2019/09/25', "YYYY/MM/DD").format("MMMM DD, YYYY")
> 
> => result: "September 25, 2019"

Yes thank you, as said above, importing moment.js for just one feature of a one-off task, seemed an overkill. So decided against it in a hope since moment.js is used within Serenity anyway (for calendar part) so perhaps the `Q.formatDate` had an overload for that would give me desired result. Sadly not to be.

Kind Regards.

**Comment by minhhungit** [comment]
agree with you about momentjs, I have more simple version I think it will help
```javascript
const monthNames = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

const d = new Date();
document.write("The current month is " + monthNames[d.getMonth()]);
```
https://stackoverflow.com/a/1643468/3007147
