### ISSUE TITLE
How to show item with format DisplayFormat("#,##0") in CardViewMixin

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4527]
Hello Could You give a solution please, I want to show Price with format example 1,000,000 ?
that's code below : 
`<td class="contact" >{{item.PriceC2C}}</td>`

![Capture](https://user-images.githubusercontent.com/43465534/61063776-ba23c980-a42a-11e9-9960-55ac89c4301c.PNG)

**Comment by minhhungit** [comment]
Hello, sorry I'm not on computer today, I will be back soon and will check if I can help

**Comment by resitaufan** [comment]
> 
> 
> Hello, sorry I'm not on computer today, I will be back soon and will check if I can help

thank you,

**Comment by minhhungit** [comment]
Hello @resitaufan , I think you can try this bellow code
```javascript
var yournumber  = 12345678901234;
console.log(yournumber.toLocaleString(undefined, {maximumFractionDigits : 0}))
```
result = "12,345,678,901,234"

ref here: https://stackoverflow.com/questions/44784774/in-react-how-to-format-a-number-with-commas

**Comment by resitaufan** [comment]
hello @volkanceylan , Could you help me"

**Comment by luongnv6** [comment]
you try:

Q.formatNumber(item.PriceC2C, "#,##0")

**Comment by jmkamran** [comment]
[DisplayName("Unit Price"), Scale(4), NotNull, AlignRight, DisplayFormat("#,##0.00")]
        public Decimal? UnitPrice
        {
            get { return Fields.UnitPrice[this]; }
            set { Fields.UnitPrice[this] = value; }
        }
put this line 
DisplayFormat("#,##0.00")

**Comment by wezmag** [comment]
Not sure if you can use `Q.formatNumber` inside the template. 
Please give a try. 
`Q.formatNumber(item.PriceC2C, '#,##0')`

**Comment by minhhungit** [comment]
![image](https://user-images.githubusercontent.com/2279508/62696717-34804300-ba03-11e9-8242-5c9e7053ad24.png)
@resitaufan  why this did not work for you ?

**Comment by resitaufan** [comment]
@minhhungit sorry it's not work for me,but  thank you for your hand

**Comment by resitaufan** [comment]
@wezmag thank a lot, and then it's solved
