### ISSUE TITLE
report render query string too long

### ISSUE THREAD

**Issue by shakazulu89** [volkanceylan/Serenity#4528]
Hi
Im trying to bulk render invoices but running into an issue when sending all the data needed for the invoice template. the error i am getting is that the query string is too long. The thing is i cant just send the id of the data row as shown in the example because that will force me to do a select on every invoice printed in the batch, which can contain 100s of invoices. obviously that will not be great for performance all those server calls. what im trying to do now is select all the invoices on the batch action then i loop all of them and passing all the data i need for the template via query string to the Render() method. 
Hope i explained myself sufficiently! Any ideas?
thanks!

**Comment by minhhungit** [comment]
hi @shakazulu89 

firstly, create one sql table like this
- Id bigint FK & Identifier
- SessionId uniqueidentifier (guid)
- InvoiceId

and create index on SessionId, include InvoiceId

- before you create your invoice, generate 1 session Id (guid value) and insert all invoice Ids into the table with current sessionId
- after inserting is successfully then pass sessionId into report parameter
- on your c# code to create report data, call a query to get list invoice ids by sessionId

That is my idea and the idea is replacing your invoice Ids by sessionId, you might need to find a way to implement it

Ok, your turn!

**Comment by Sevigorr** [comment]
Add the following to your web.config. This will 'fix' your issue.

`<security>
    <requestFiltering>
      <requestLimits maxQueryString="32768"/>
    </requestFiltering>
  </security>`

**Comment by shakazulu89** [comment]
thanks guys for the replies. i ended up using caching per advice from volkan.
