### ISSUE TITLE
Serenity in a 3 tier (n tier) environment

### ISSUE THREAD

**Issue by scottcottingham** [volkanceylan/Serenity#453]
Hi Volkan,

Is there a way to split Serenity to run in a 3 tier (3 server) environment?  We are building our first Serenity-based case management system for use internally, and I'm so impressed that I would like our organization to standardize new app development around Serenity.  Our current policies for public-facing web applications require a web server, app server, and sql server, each behind a firewall.  Our current apps use WCF (or old SOAP/asmx) to communicate with our services project running on the app server, which in turn persists data to the sql server.

I'd like to try to move Serenity's services into it's own solution and get the communication working, but I wanted to check with you to see if you already had experience with this or could share your thoughts, pointers, or samples.

-Scott

**Comment by volkanceylan** [comment]
Hi Scott,

It is possible, i had similar applications, e.g. a set of public facing B2C sites, which are also written using Serenity but under the hood passing service requests to another Serenity based admin portal in DMZ.

Services and entities should be straightforward to move into a separate assembly, there is usually only one way dependency. A little exception is imported editor and formatter attributes in web project that are used on rows, but you may take around it by moving some into Columns/Forms or generating these imports in row assembly.

**Comment by scottcottingham** [comment]
Excellent.  Thanks for the insight.  I'll close the issue, but will report back my progress.
