### ISSUE TITLE
Unable to refresh grid

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4530]
hello everyone and @volkanceylan
First I explain what I have implemented
![Capture1](https://user-images.githubusercontent.com/39983941/61168040-070bbb00-a565-11e9-84b6-24eb85030324.JPG)
On the selection of **BOM** all characteristics will be display in the above grid i.e. **characteristics constant**
![Capture2](https://user-images.githubusercontent.com/39983941/61168056-3de1d100-a565-11e9-8b68-2b73cc78f428.JPG)
and by selecting any **Characteristics Constant**  the SubCharacteristics will be display in next grid i.e. **characteristics value** and after selecting the value both characteristics and its value will be display in third grid to ensure that how many characteristics selected against that BOM 
![Capture3](https://user-images.githubusercontent.com/39983941/61168140-f78d7180-a566-11e9-8973-966811b0a602.JPG)

**TILL HERE everything is working as I expected**
But when I selected more than 1 characteristics Value and delete one of them and again when I select that same value which I deleted then Its shows notification that this value is already selected. Here am unable to refresh grid and also do not understand which grid should be refresh.
![Screenshot (112)](https://user-images.githubusercontent.com/39983941/61168235-a2525f80-a568-11e9-86dd-3d3bae5e74e4.png)

Please help me with this!

**Comment by jmkamran** [comment]
Hay dear you should implement serenity.extra in your project. and give bundle of thanks to @dfaruque 
and if you want how to implement than see this link and subscribe my channel.
https://www.youtube.com/watch?v=FwFFi_AFrSA&t

**Comment by JohnRanger** [comment]
@jmkamran ,

again - stop spamming the issues of others here in the Serenity forum with plain advertising for your youtube channel when your linked youtube video does not at least solve a considerable part of the asked question.

The linked youtube video only shows how to add dfaruques serenity.extra - but this does not - in no wise - solve the asked question.

If you continue like this I will consider reporting your activities as abuse.

With kind regards,

John

**Comment by stixoffire** [comment]
@Shraddha996  Did you solve your issue ? Also You stated the things you had were working as expected - I certainly would like to see an example of that - as I am trying to implement the same thing.
