### ISSUE TITLE
How to display a "hello world" page on serenity? How to link that with the navigation?

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4534]
Trying to create my first page on serenity. Not able to figure it how?

**Comment by minhhungit** [comment]
start from here: https://serenity.is/docs/getting_started/README

**Comment by reacharihant** [comment]
Hi Volkanceylan/Serenity

I have already started from here. The thing is I have to create a table,
run the sergen to get started with this. That is fine!!
But now, say, I want to just add a sample model, view and controller and
link it with navigation -- I am not able to do it.

E.g. I have created "Task" folder under Module. I have created the MVCs
here. Now how do it link it with the navigation?

Regards
Arihant

**Comment by reacharihant** [comment]
I got it! I created a page which contained the controller name and the index method. Then from the navigation menu called the controller.

e.g. [assembly: NavigationLink(3000, "Tasks/TestPage", typeof(TestPages.TestController), icon: "fa-tachometer")]

Thanks!!
