### ISSUE TITLE
file upload form more than one in a form

### ISSUE THREAD

**Issue by hamkairama** [volkanceylan/Serenity#4539]
hi @volkanceylan,, 
i create like this :
    [DisplayName("ESR Document"), MultipleFileUploadEditor]
        public String ESRDocument
        {
            get { return Fields.ESRDocument[this]; }
            set { Fields.ESRDocument[this] = value; }
        }

        [DisplayName("CAF Document"), MultipleFileUploadEditor]
        public String CAFDocument
        {
            get { return Fields.CAFDocument[this]; }
            set { Fields.CAFDocument[this] = value; }
        }

        [DisplayName("MLA Document"), MultipleFileUploadEditor]
        public String MLADocument
        {
            get { return Fields.MLADocument[this]; }
            set { Fields.MLADocument[this] = value; }
        }

and when i drag and drop my file to ESRDocument, the other form (CAFDocument, MLADocument) also automatically filled with the same file.

and i don't want to be like that.

do you have any idea ?

![image](https://user-images.githubusercontent.com/34258727/61614775-c3b0fb00-ac8e-11e9-9ea9-65b979e04eed.png)

![image](https://user-images.githubusercontent.com/34258727/61614846-e511e700-ac8e-11e9-9d10-456c4dc03bf4.png)

**Comment by hamkairama** [comment]
hi @volkanceylan where are you ?
i need your help

**Comment by mfathy00** [comment]
@hamkairama try to change location of file for every upload document something like 

```
[DisplayName("CAF Document"), MultipleFileUploadEditor (FilenameFormat = "Document/CAF /{1:00000}/{0:00000000}_{2}")]
    public String CAFDocument
    {
        get { return Fields.CAFDocument[this]; }
        set { Fields.CAFDocument[this] = value; }
    }

    [DisplayName("MLA Document"), MultipleFileUploadEditor(FilenameFormat = "Document/MLA /{1:00000}/{0:00000000}_{2}")]
    public String MLADocument
    {
        get { return Fields.MLADocument[this]; }
        set { Fields.MLADocument[this] = value; }
    }
```

**Comment by hamkairama** [comment]
@mfathy00  i have done it. but still not work..
everything fine if i select using browse.
but when i do with drag and drop, it's still happen.

**Comment by wezmag** [comment]
@hamkairama What browser do you use? 
I tried on Google Chrome, Edge, Firefox and IE11, but I didn't experience the same behavior as you.
Also your browser rendered the page different from mine.
I think there is something wrong with your browser.
Try to turn off any extensions or try with other browsers.
 
![Image 7](https://user-images.githubusercontent.com/340794/62603030-9d928880-b927-11e9-8183-2e90287327af.jpg)

**Comment by volkanceylan** [comment]
```ts
        protected getUploadInputOptions(): UploadInputOptions {
            return {
                container: this.toolbar.findButton('add-file-button'),
                zone: this.element,

```

Upload zone (drag drop zone) is set to this.element, e.g. the upload editor itself, if it is not working on your side something else should be wrong, probably with the upload component (jQueryFileUpload) and last commenter can't reproduce such behavior.
