### ISSUE TITLE
LookupEditor(typeof(CountriesRow), Multiple = true)  on grid filter

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#454]
i have a  row with the following 
` [LookupEditor(typeof(CountriesRow), Multiple = true), ClientSide]
        [LinkingSetRelation(typeof(PolicyCountrysRow), "PolicyID", "CountryID")]
        public List<Int32> PolicyCountrysList
        {
            get { return Fields.PolicyCountrysList[this]; }
            set { Fields.PolicyCountrysList[this] = value; }
        }`

is there a way to filter the grid based on a country  these are saved in lookup table?

**Comment by volkanceylan** [comment]
Add an expression field with EXISTS

**Comment by zerodev** [comment]
i need to add in the grid when adding the CreateToolbarExtensions  filters?

**Comment by xjbsky** [comment]
How to? I can't figure out how to use expression field with EXISTS.......

**Comment by xjbsky** [comment]
@zerodev @volkanceylan How to? I can't figure out how to use expression field with EXISTS.......
