### ISSUE TITLE
Update  from .net core 2.1 Asp to .net core 2.2  

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4540]
when I set Target Framework to .Net Core2.2 I received  about  4200 Errors.
Current is set to .Net Core2.1. 
Anybody Knows How to Upgrade it to 2.2?

**Comment by zainvegeta** [comment]
I tried this today in our project.These are the steps i did.
1.In visual studio change your target framework to 2.2.
2.unload your project and edit your .csproj file and make following changes

<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <PackageReference Include="EPPlus" Version="4.5.2.1" />
    <PackageReference Include="FastMember" Version="1.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Serenity.Web" Version="3.9.9" />
    <PackageReference Include="Serenity.Web.Assets" Version="3.9.2" />
    <PackageReference Include="Serenity.Scripts" Version="3.9.9" />
  </ItemGroup>

<PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <DefineConstants>$(DefineConstants);COREFX;ASPNETCORE</DefineConstants>
  </PropertyGroup>

 <ItemGroup>
    <DotNetCliToolReference Include="Serenity.CodeGenerator" Version="3.9.9" />
  </ItemGroup>

3.Reload your project and build.

**Comment by MaziarSangi** [comment]
@zainvegeta  
Thank you.
