### ISSUE TITLE
Help-desk ticketing system with Serenity

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Serenity#4541]
Hello community, before implementing a very basic ticketing system with Serenity I was wondering if someone has already done that and would be willing to share or add to the samples collection.
 
Basically I need something like question/issue, answer, status, the LoggingRow fields (dates and users) and sending notifications to the author/subscribers on update.

Similar to github issues but customizable, localizable and better looking for non-techs.
Thanks

**Comment by jmkamran** [comment]
Hi bravo we made it if you required than contact us if you see demo than 
http://server.abitcons.com:84/
and if you want to get more help subscribe my channel
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q

**Comment by BravoSierra** [comment]
I've seen your projects, nice.

**Comment by BravoSierra** [comment]
Do you share the project? BTW I can't send you an email, antispamed by Google (aspmx.l.google.com #5.1.1 smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces)

**Comment by jmkamran** [comment]
@BravoSierra 
Are you want to purchase this product or made it by yourself ??

**Comment by BravoSierra** [comment]
Since my initial post a week ago I've done my quick hack with a single ticket table, an enum for the level and sending an email on updates.  That's enough for me now but I'm happy I discovered your projects. If you share you ticketing project I'll be happy to improve my existing solution. Can you clarify if your business model is selling your apps or just sharing them to get a recognition in the community and sell add-ons or customization or other serenity developments? Thanks for your videos anyway.

**Comment by jmkamran** [comment]
My business model is only for selling. We have a team. we make many projects in serenity plateform. thanks for @volkanceylan .

**Comment by jmkamran** [comment]
@BravoSierra 
http://server.abitcons.com:84
you can test helpdesk here
