### ISSUE TITLE
Missing constructor in Sergen-generated code

### ISSUE THREAD

**Issue by josgood88** [volkanceylan/Serenity#4543]
After generating UI code for a new table, then running the application and opening the table by clicking the table in the application UI, I get a popup reading, in part
Message: Uncaught TypeError: CRM2.Default.KeywordStringsGrid is not a constructor.
(see attached)
![UncaughtException](https://user-images.githubusercontent.com/5847424/61966038-85fdec00-af86-11e9-957b-3d8cd6839207.PNG)
CRM2 is the program, KeywordStrings is the table.
I get this error because I upgraded Microsoft.TypeScript.MSBuild from 3.1.1 (as distributed with Serene) to v3.6.0.  

By working through the available versions, I've demonstrated that the problem shows up at the transition from 3.1.5 to 3.2.1.  Either there is a bug in Microsoft.TypeScript.MSBuild at that point or Sergen becomes incompatible at that point.

I am currently running with Microsoft.TypeScript.MSBuild v3.1.5 and all is well.

This problem occurs only when creating a new table.  It does not appear when updating an existing table.

I am using VS2019 on Win 8.1.  My Serene package is 3.9.9 (2019-05-24).  As delivered, I have no problem.  The problem only arises when I Nuget updates.

I am happy to provide any additional information that you need or want.  Just let me know.

Thank you for providing this most excellent product!

**Comment by jmkamran** [comment]
I think you should add [LookupScript] in KeywordStringRow and than clean your project ,than build it. and click on transform t4 template 
Hope this will help you 
subscribe my channel
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q/

**Comment by naushadqamar** [comment]
I am getting same issue , 
I am using vscode and generated code using sergen.

**Comment by volkanceylan** [comment]
Such issues are usually due to failing to /// reference to the base class in your subclass, e.g. not referencing GridEditorBase in your class that derives from GridEditorBase , as TypeScript can't reorder generated code properly, unfortunately.
