### ISSUE TITLE
How to show Grid and Dialog in same page

### ISSUE THREAD

**Issue by jabirmoolur** [volkanceylan/Serenity#4545]
Ther are two ways to to show a dialogue,
One as popup(dialog) or as panel,
But if i want to show a panel right next to grid, how can achive this.
i adjusted sizes with css, now the requirment is to show dynamic dialog(panel) in grid page on clicking it

**Comment by kilroyFR** [comment]
Looks like this requirement matches the EntityGrid Dialog feature of last 3.9.10 (see demo)

https://serenity.is/demo/AdvancedSamples/EntityGridDialog

**Comment by jabirmoolur** [comment]
Oh, taht means i cannot use/extend in community edition

**Comment by brunobola** [comment]
@jabirmoolur You can but have to implement it yourself ;)

**Comment by JohnRanger** [comment]
@jabirmoolur 

And when you develop it, please share it here :-)

**Comment by kilroyFR** [comment]
@volkanceylan topic to close as solution already exists in StartSharp

**Comment by JohnRanger** [comment]
@jabirmoolur,

thanks to @minhhungit , I could now make a wiki entry for this

https://github.com/volkanceylan/Serenity/wiki/UI:-Slider-dialog-(poor-man's-EntityGridDialog)

With kind regards,

John
