### ISSUE TITLE
Preventing Duplicate Codes or Names Entry

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4547]
How can I prevent or alert users from entering a duplicate product code or name in the form?

**Comment by minhhungit** [comment]
@reacharihant 
There are many ways, I will show you the way I think it's the easiest 
On your ROW.cs add a [UniqueConstraint] attribute, for example:

```csharp
[UniqueConstraint(new[] { "ProductCode", "More_Field_Here", "One_More_xyz" })]
public sealed class ProductRow : Row, IIdRow
{
   //  ....
}
```

**Comment by reacharihant** [comment]
Yes, it solved my problem. Thank you very much for your quick help!!
