### ISSUE TITLE
Change ToolButton title and Onclicke in AfterLoadEntity

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4549]
Hello 
I want to change one of Toolbarbuttons(its title and Onclick) in some conditions.
The condition is : one boolean value of form entities is true.
AnyBody knows How to ??

**Comment by brunobola** [comment]
One ways is:

1. Do an override "Toolbarbuttons" methods and then (if condition ? do action else do other action).
2. Catch the boolean field method and then override the caption with jQuery for instance...

**Comment by MaziarSangi** [comment]
@brunobola 
In "getToolbarbuttons" method I don't have values of form. it returns undefined.

**Comment by wezmag** [comment]
It's better to add a new button instead of modify an existing button's title and onclick event.

``` typescript
protected getToolbarButtons() {
    let buttons = super.getToolbarButtons();
    buttons.push({
        cssClass: 'some-button',
        title: 'Some Button',
        icon: 'fa-eye',
        onClick: () => {
            doSomeThing();
        }
    });
    return buttons;
}

```
Then toggle the new button visibility according to the form value

``` typescript
protected updateInterface() {
    super.updateInterface();
    this.toolbar.findButton('some-button').toggle(this.form.IsEnabled.value);
}
```

**Comment by MaziarSangi** [comment]
@wezmag  
Thank you.
