### ISSUE TITLE
System.ComponentModel.DisplayNameAttribute Error

### ISSUE THREAD

**Issue by Thebenmandude** [volkanceylan/Serenity#455]
Hi, I get the following errors when building/rebuilding my project. 
Both errors refer to line 8 of HtmlBasicContentEditor.cs file.

The type 'System.ComponentModel.DisplayNameAttribute' exists in both 'Serenity.Script.UI.dll' and 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll'	

The type or namespace name 'DisplayName' could not be found (are you missing a using directive or an assembly reference?)	

I have tried to implement the SlickGrid Formatter as per the documentation example but have removed all changes made but still get the errors.

**Comment by volkanceylan** [comment]
why nobody read. troubleshooting section.
