### ISSUE TITLE
SortBy doesn't work on StoredProcedureGrid example

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4550]
Hey Guys,

Sort by doesn't work when set on any column for the Stored Procedure Grid example below

https://serenity.is/demo/BasicSamples/StoredProcedureGrid

I assume that to make it work we need to use LINQ after getting the data from DB.

Thanks!

**Comment by edwardch** [comment]
Nope, the grid displays exactly what is returned from the SP and you can't sort a SP result in SQL.

You can add [Sortable(false)] to your fields in your xyzRow.cs so the user doesn't _think_ they can sort it. If you really have to sort by columns try using a view, or you could add paramaters to your SP and map your sorted columns from the request to that, then add logic to the SP, but that sounds like work...

Have not tried the LINQ solution but I've never needed to override the result of a SP.

**Comment by lechu90ns** [comment]
Thank you
