### ISSUE TITLE
Lookupscript with different table

### ISSUE THREAD

**Issue by rarunkumar454** [volkanceylan/Serenity#4553]
Hi, I am having Account, User and Report tables. AccoutId is refered to user table and userId and AccountId were refered to reports table. I need to get the Username based on the account which i choose on report row. I need to write the lookupscript for this. If there is any possible solution kindly let me know.

**Comment by jmkamran** [comment]
Authorization.userDefinition.Username;

**Comment by jmkamran** [comment]
If you want to get any help of serenity subscribe my youtube channel
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q
