### ISSUE TITLE
[Proposal] Using ChromeHtmlToPDF instead of/alongside wkHtmlToPDF

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4554]
I am facing a problem with wkhtmltopdf to render Unicode characters. while chrome print to pdf works fine.

So, I think chrome print to pdf is a better option for rendring pdf.

The following resource I have found
https://github.com/Sicos1977/ChromeHtmlToPdf

The command to generate pdf using headless chrome
`chrome --headless --print-to-pdf="d:\\{{path and file name}}.pdf" https://google.com`

@volkanceylan What is your thoughts on this?
Regards.

**Comment by wezmag** [comment]
Looks like it needs Google Chrome to work.
Might not be suitable for websites that doesn't have full control to the web servers.

**Comment by mafdy** [comment]
https://github.com/foliojs/pdfkit

Take a look!

**Comment by dfaruque** [comment]
@wezmag portable-chrome could be used just like wkhtmltopdf.exe we use currently.

**Comment by dfaruque** [comment]
@mafdy have you used that. I need wkhtmltopdf like a tool which can generate pdf from Html.

**Comment by volkanceylan** [comment]
@dfaruque i used Puppeteer successfully for a customer project, they had some requirements that Wkhtml doesn't support.. And Puppeteer can download Chrome itself, though it takes some time at first try. I can't share the code here but you may be able to do it similar to HtmlToPdfConverter.

**Comment by dfaruque** [comment]
Thank you very much for your valuable comment. I will try puppeteer.

**Comment by muhammedyaman** [comment]
@dfaruque did you manage to use puppeteer? do you have an example?

**Comment by dfaruque** [comment]
yes. I have used PuppeteerSharp nuget package

**Comment by dfaruque** [comment]
sorry. there is no example to share

**Comment by muhammedyaman** [comment]
I implemented SelectPdf instead. Thanks anyway.
