### ISSUE TITLE
Upload file to Amazon S3

### ISSUE THREAD

**Issue by Billylalalallaa** [volkanceylan/Serenity#4556]
Hello everyone!

is possible upload file to Amazon S3? example ImageUploadEditor

**Comment by edwardch** [comment]
You have to write some custom behaviour to do this.

See [this comment](https://github.com/volkanceylan/Serenity/issues/3890#issuecomment-435669469) and the rest of the discussion for some information. 

I'm also very interested in a solution. I have managed to do retrieve a file from Azure blob storage, but not upload to Azure in the ImageUploadEditor. 

Hope this helps!

**Comment by manishbupadhyay** [comment]
Hi @wakaleo I want to upload serenity-summary.html report file to AWS S3 bucket. Can you please help me on this? Thanks!
