### ISSUE TITLE
Unable to convert to pdf and print

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4559]
While trying to print a report, I am getting the following error:
System.InvalidOperationException: 'Can't find wkhtmltopdf.exe which is required for PDF generation.
Please download a stable version from http://wkhtmltopdf.org/downloads.html
 and place it under directory 'C:\Users\..\..\...\wwwroot\..\App_Data\Reporting'.'

I do not have the folders ".. App_Data\Repository" under wwwroot folder. 

Can anyone suggest a solution?

**Comment by javaman63** [comment]
You have to put the file wkhtmltopdf.exe  on your bin directory
\[YOUR_PROYECT].Web\bin

**Comment by jmkamran** [comment]
If you want any help of serenity subscribe my youtube channel
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q

**Comment by reacharihant** [comment]
Thanks!
