### ISSUE TITLE
Inserting selected rows from grid to Sql

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#456]
Could someone kindly suggest some Serenity reading or documentation regarding sql inserting of **selected rows** upon button click (yellow). I am using GridRowSelectionMixin to enable multiple row selection.

Thank you in advance.
![image](https://cloud.githubusercontent.com/assets/15879719/14023930/c044d310-f1de-11e5-9032-d44f10ac68a5.png)

**Comment by jsbUSMC** [comment]
The grid rows are pulled from SQL...what are you trying to do?

**Comment by biggikalli** [comment]
My grid is pulled from a sql view which is combining 2 tables.
I am trying to take the values from selected rows in this grid and insert those rows to to a third table.
That table is ready for the new data but I am a bit lost on how to execute the insertion.

**Comment by biggikalli** [comment]
I probably should put the code inside the "else" portion of this code in xxxGrid.cs:

`        protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();

            buttons.Add(new ToolButton
            {
                CssClass = "tag-button",
                Title = "Færa í tollað",
                OnClick = delegate
                {
                    var selectedIDs = rowSelection.GetSelectedKeys();
                    if (selectedIDs.Count == 0)
                        Q.NotifyWarning("Veldu raðir með því að haka í reitina");
                    else

                        Q.NotifySuccess("Þú hefur tollad " + selectedIDs.Count +
                            " línu(r) með ID: " + string.Join(", ", selectedIDs));
                }
            });

            buttons.RemoveAt(0);
            return buttons;`

I just need a little more know-how to implement this in C# and Serenity as I am more used to small vb programs!! :/

**Comment by zerodev** [comment]
check the clone example in the northwind i think this is a start

**Comment by biggikalli** [comment]
Thanks for the reply. 
Do you mean the product section of Northwind or something else by "the clone"?

**Comment by jsbUSMC** [comment]
It's part of the Basic Samples module. Serene.Script\BasicSamples\CloneableEntityDialog.cs

**Comment by biggikalli** [comment]
Ok, found it. I will give it a go. 
Thank you for your help :) :+1:

**Comment by jsbUSMC** [comment]
No worries, glad that I could help!

**Comment by volkanceylan** [comment]
Also have a look at bulk action sample.

**Comment by biggikalli** [comment]
Hi again, thank you all for your suggestion. I am somewhat closer to the end line, but I am missing something. I would be greatly thankful if someone could assist me on how to handle the SQL insertion trigger.

Please see below where my buttonClick code is, where I want to take **selected rows** and insert to SQL table. This is from my xxx**Grid.cs** on the Script side where I should put the trigger in the else portion.

```
`        protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();

            buttons.Add(new ToolButton
            {
                CssClass = "tag-button",
                Title = "Færa í tollað",
                OnClick = delegate
                {
                    var selectedIDs = rowSelection.GetSelectedKeys();
                    if (selectedIDs.Count == 0)
                        Q.NotifyWarning("Veldu raðir með því að haka í reitina");
                    else
                                            
                        Q.NotifySuccess("Þú hefur tollad " + selectedIDs.Count +
                            " línu(r) með ID: " + string.Join(", ", selectedIDs));
                }
            });
            return buttons;`

```
I have some questions:
1. Should I put the insertion trigger in the script project? I have noticed that script doesn't include any reference regarding sqlclient. The web project has those references but I assume that I should put the necessary code into the else portion of xxx**Grid.cs** which is on the script side. Where can I find information on how the Linq code should be?
2. I would be on familiar grounds if I can use the System.Data.SqlClient reference on the web side. Can I perhaps use a controller in the web project to handle the insertion, is it safe?

I have taken a look at the cloneable sample and also the bulkactionorder sample. I have copied and adapted the code from the BasicSampleXXXService.cs classes into my service class. It looks to me though as it is missing triggers for SQL insertion, am I right? See below:


```
`    [Imported, PreserveMemberCase]
    public partial class LagerService
    {
        [InlineConstant] public const string BaseUrl = "Inventory/Lager";


        [Imported, Serializable, PreserveMemberCase]
        public partial class LagerTollunRequest : ServiceRequest
        {
            public List<Int32> selectedIDs { get; set; }
        }

        [InlineCode("Q.serviceRequest('Inventory/Lager/Create', {request}, {onSuccess}, {options})")]
        public static jQueryXmlHttpRequest Create(SaveRequest<TolladRow> request, Action<SaveResponse> onSuccess, ServiceCallOptions options = null)
        {
            return null;
        }

        [InlineCode("Q.serviceRequest('Inventory/Lager/Update', {request}, {onSuccess}, {options})")]
        public static jQueryXmlHttpRequest Update(SaveRequest<TolladRow> request, Action<SaveResponse> onSuccess, ServiceCallOptions options = null)
        {
            return null;
        }
 
        [InlineCode("Q.serviceRequest('Inventory/Lager/Delete', {request}, {onSuccess}, {options})")]
        public static jQueryXmlHttpRequest Delete(DeleteRequest request, Action<DeleteResponse> onSuccess, ServiceCallOptions options = null)
        {
            return null;
        }

        [InlineCode("Q.serviceRequest('Inventory/Lager/Retrieve', {request}, {onSuccess}, {options})")]
        public static jQueryXmlHttpRequest Retrieve(RetrieveRequest request, Action<RetrieveResponse<TolladRow>> onSuccess, ServiceCallOptions options = null)
        {
            return null;
        }

        [InlineCode("Q.serviceRequest('Inventory/Lager/List', {request}, {onSuccess}, {options})")]
        public static jQueryXmlHttpRequest List(ListRequest request, Action<ListResponse<TolladRow>> onSuccess, ServiceCallOptions options = null)
        {
            return null;
        }

        [Imported, PreserveMemberCase]
        public static class Methods
        {
            [InlineConstant] public const string Create = "Inventory/Lager/Create";
            [InlineConstant] public const string Update = "Inventory/Lager/Update";
            [InlineConstant] public const string Delete = "Inventory/Lager/Delete";
            [InlineConstant] public const string Retrieve = "Inventory/Lager/Retrieve";
            [InlineConstant] public const string List = "Inventory/Lager/List";
            [InlineConstant] public const string Lagertollun = "Inventory/Lager/Lagertollun";
        }

        [InlineCode("Q.serviceRequest('Inventory/Lager/Lagertollun', {request}, {onSuccess}, {options})")]
        public static jQueryXmlHttpRequest LagerTollunBulkAction(LagerTollunRequest request, Action<ServiceResponse> onSuccess, ServiceCallOptions options = null)
        {
            return null;
        }
    }`

```
Maybe I am on the totally wrong track. But I hope this is a easy question for someone and I would really appreciate some direction.

Thank you in advance.
