### ISSUE TITLE
Order Amount in Northwind Application [Order Table]

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4560]
In the northwind's order table, I did not find the order amount stored anywhere. Can anyone explain the reason? Also, what must be done in accordance with best practices?

**Comment by jmkamran** [comment]
If you want any help of serenity subscribe my youtube channel
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q

**Comment by JohnRanger** [comment]
@jmkamran ,

please avoid doing advertising here of your youtube channel - if it does not directly answer the question or at least is a considerable help to answer the question.

With kind regards,

John

**Comment by reacharihant** [comment]
The issue is resolved.
