### ISSUE TITLE
Responsive issues on mobile devices while loading big amount of data to SlickGrid

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4561]
Hey guys!

I created a grouped slickgrid for reports, so I had to skip pagination. I am loading 8k records, grouped by 3 columns and I have 2 aggregate columns with summing values.

Although, when I use chrome's tool to resize my browser to a mobile device, it appears that loading time is greatly increased to about 20 sec

I believe, it is related to CSS resizing somehow.

Can you advise?

Thanks!

**Comment by lechu90ns** [comment]
@volkanceylan 
Hey Volkanceylan, can you advise please? it seems rather painful for mobile devices to display such a number of data. Shall I consider filtering the number of data, or is there anything that might get fixed with auto-resizing feature?

Thanks

**Comment by lechu90ns** [comment]
Collapsing everything by default on load fixed the issue.

Feel free to close it you like

**Comment by JohnRanger** [comment]
@lechu90ns ,

thanks for sharing. Please close your issue yourself as only you and Volkan can do it :-)

With kind regards,

John

**Comment by lechu90ns** [comment]
sure thing! Closing
