### ISSUE TITLE
Line break and in the right position

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4565]
I modified a form  with css properties like this :

        [HalfWidth, FormCssClass("line-break-sm")]
        public Decimal SubTotal { get; set; }

![image](https://user-images.githubusercontent.com/43465534/63010962-92a0a080-beb1-11e9-9fa6-549760186497.png)

then,
how to put forms with break and in the right position as like below?
![image](https://user-images.githubusercontent.com/43465534/63011214-0f337f00-beb2-11e9-85fb-edca0b2c3b82.png)

**Comment by rcruzfalcon** [comment]
Hi, you can put before each field :

        [HalfWidth]
        [DisplayName(""), LabelWidth(0)]
        [StaticTextBlock()]
        public String StaticText0 { get; set; }

in the form.cs.

Best Regards.
Roberto

**Comment by wezmag** [comment]
You can use bootstrap css classes to control the position.
This is how I did in my previous project.

``` csharp
[CssClass("col-md-6 col-md-offset-6")]
public Decimal SubTotal { get; set; }
[CssClass("col-md-6 col-md-offset-6")]
public Decimal Tax { get; set; }
[CssClass("col-md-6 col-md-offset-6")]
public Decimal Shipping { get; set; }
[CssClass("col-md-6 col-md-offset-6")]
public Decimal Discount { get; set; }
[CssClass("col-md-6 col-md-offset-6")]
public Decimal Total { get; set; }
```

**Comment by resitaufan** [comment]
> 
> 
> Hi, you can put before each field :
> 
> ```
>     [HalfWidth]
>     [DisplayName(""), LabelWidth(0)]
>     [StaticTextBlock()]
>     public String StaticText0 { get; set; }
> ```
> 
> in the form.cs.
> 
> Best Regards.
> Roberto

I got an error becouse the form unavailable in row
![image](https://user-images.githubusercontent.com/43465534/63067609-f9699c80-bf39-11e9-8dc2-599f793e823c.png)

**Comment by resitaufan** [comment]
> 
> 
> You can use [bootstrap](https://getbootstrap.com/docs/3.3/css/#grid) css classes to control the position.
> This is how I did in my previous project.
> 
> ```cs
> [CssClass("col-md-6 col-md-offset-6")]
> public Decimal SubTotal { get; set; }
> [CssClass("col-md-6 col-md-offset-6")]
> public Decimal Tax { get; set; }
> [CssClass("col-md-6 col-md-offset-6")]
> public Decimal Shipping { get; set; }
> [CssClass("col-md-6 col-md-offset-6")]
> public Decimal Discount { get; set; }
> [CssClass("col-md-6 col-md-offset-6")]
> public Decimal Total { get; set; }
> ```
> 
> ![Image 1](https://user-images.githubusercontent.com/340794/63065168-a0006e00-bf37-11e9-96f7-ad0ca1ca8d44.jpg)

thank you, It's so usefull,and just solved .

**Comment by chrisomeara** [comment]
very helpful post - quick question - how did you the text in the subtotal, tax etc to align right within the field?

**Comment by wezmag** [comment]
> very helpful post - quick question - how did you get the text in the subtotal, tax etc to align right within the field?

apply `text-align: right;` to the `.s-DecimalEditor` in your css file.
