### ISSUE TITLE
AdminLogin AdminLTE

### ISSUE THREAD

**Issue by doanhuybinh90** [volkanceylan/Serenity#4566]
Hi all,

i'm tried use AdminLogin.Adminlte... by change in AccountPage which **UseAdminLTELoginBox = true**. After that i'm clean and rebuild code, look error as image below...

![Screen Shot 2019-08-14 at 23 25 45](https://user-images.githubusercontent.com/22341360/63038313-1460f000-beeb-11e9-87b0-e32eeae995c7.png)

please advise ...

**Comment by volkanceylan** [comment]
AdminLTE login option was contributed by another user, probably not updated and is not supported.
