### ISSUE TITLE
How to generate a docx file on the grid?

### ISSUE THREAD

**Issue by mrcvieira78** [volkanceylan/Serenity#4567]
How to generate a docx file on the grid. Tried as follows, but it did not work.

             buttons.push (IntraSerene.Common.ReportHelper.createToolButton ({
                 title: 'LaudasDocx',
                 cssClass: 'export-docx-button',
                 reportKey: 'SOCIETY.SocBookLauda.SocBookLaudaDetailsReport',
                 getParams: () => ({
                     NrMes: this.findQuickFilter (Serenity.LookupEditor, SOCIETY.SocBookLaudaRow.Fields.NrMes.toString ()). Value.toString ()
                 })
             }));

**Comment by kilroyFR** [comment]
How do you expect to generate a docx (word) document with this command ?

**Comment by JohnRanger** [comment]
@mrcvieira78 

I don't think that there is a docx generator available in Serenity. You would have to implement one yourself.

There is at least one free docx generator for .net on github: https://github.com/xceedsoftware/DocX. You would have to implement the rendering on server side by e.g. transfer your currently visible records on client side to a backend endpoint, there render the docx and then provide the redered docx as a download.

Or if you want to do this all client side: https://docx.js.org/#/
(No idea if you then can save the file from the inside of your browser as this would be a security risk).

John

**Comment by mrcvieira78** [comment]
Thank you for your help. I will take a look.

**Comment by Zahar661** [comment]
@mrcvieira78  Did you manage to implement it?
