### ISSUE TITLE
Translation not working in .net core 

### ISSUE THREAD

**Issue by mfathy00** [volkanceylan/Serenity#4568]
Hi i notice while i am using the demo for .net core, translation not updated immediately not like MVC, To apply the update you need to rebuild your application even try logout or clear Cache still not working any help about how to fix it.

**Comment by mfathy00** [comment]
Any help would be appreciated

**Comment by volkanceylan** [comment]
You probably mean it does not update translation after editing it in translation page right?

**Comment by mfathy00** [comment]
@volkanceylan Yes :)

**Comment by volkanceylan** [comment]
Latest version of Serene/Serenity should resolve this issue.
