### ISSUE TITLE
Filter Grid from query parameter

### ISSUE THREAD

**Issue by trackitaero** [volkanceylan/Serenity#4569]
Need to filter grid from query parameter.. in Grid I have added following code

import fld = ExcepMaintenanceRow.Fields;

protected statusFilter: Serenity.EnumEditor;

 protected createQuickFilters() {
            super.createQuickFilters();

            this.statusFilter = this.findQuickFilter(Serenity.EnumEditor, fld.Status);
        }

 public set_Status(value: string): void {
            this.statusFilter.value = value == null ? '' : value.toString();
        }

In Chtml I have added

 jQuery(function () {

        var maintGrid = new StartSharp1.GSE.MaintenanceLogGrid($('#GridDiv'), {}).init();

        var q = Q.parseQueryString();
        if (q.status != null && q.status.length) {
            maintGrid.set_Status(q.status);
        }
        
        Q.initFullHeightGridPage($('#GridDiv'));
    });

But I am getting following exception in the browser

_message: "Searching for widget of type 'Serenity.EnumEditor' on a non-existent element! ()"

Tried multiple times rebuild and T4 transfer, build is successfull, no errors... but at run time I am getting above error..

Please help..

**Comment by trackitaero** [comment]
I have added LookupEditor and quickfilter to the column "Status", now its not displaying the error, 

**_message: "Searching for widget of type 'Serenity.EnumEditor' on a non-existent element! ()"**

but the values in the status dropdown in quickfilter area are from different column.. 

Any idea what is happening here..

**Comment by luongnv6** [comment]
try:
```
 protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {

            // get quick filter list from base class, e.g. columns
            let filters = super.getQuickFilters();

            Q.first(filters, x => x.field == fld.Status).init = w => {
                this.statusFilter= (w as Serenity.EnumEditor);
            };

            return filters;
        }
```

**Comment by trackitaero** [comment]
hi luongnv6, it works.. thanks.
