### ISSUE TITLE
Adding Filter

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4570]
Hi everyone, 

I'm struggling adding a filter to the filter dialog at grid level.
Is there any example or wiki to go through. What i allready found was the quickfilter guide and this helped me, but I need to filter my grid on several detail tables and I cant handle all filters with Quickfilter => that would be a mess.

Any suggestions?

**Comment by JohnRanger** [comment]
Hi @Garozh ,

if you look at the following SF demo: https://serenity.is/demo/Northwind/Customer

The Filter function in the lower right corner is not sufficient for your filter needs?

With kind regards,

John

**Comment by Garozh** [comment]
Hi @JohnRanger ,

the lower right filter is exactly what I'm searching for. But I need to add more custom filters to that filter option. And I can't just use the FilterOnly Attribute or anything because I want to filter in my detail tables. 

So I need some way to add a custom filter to the lower right corner one (what's the name of this filter?)

Greetings

**Comment by wezmag** [comment]
Hi @Garozh 

I use https://serenity.is/demo/Northwind/Order as example, and add a Product filter to the filter function.
This is how I did it.
### OrderGrid.ts
This will add an item 'Product' to the dropdown in the filter function
``` typescript
protected initializeFilterBar() {
    let propertyItems = this.allColumns
        .filter(c => this.canFilterColumn(c))
        .map(x => x.sourceItem);

    console.log(propertyItems);

    propertyItems.push({
        name: 'ProductID',
        title: 'Product',
        filteringType: 'Lookup',
        filteringParams: { lookupKey: ProductRow.lookupKey },
    });

    this.filterBar.set_store(new Serenity.FilterStore(propertyItems));

    this.filterBar.get_store().add_changed((s: JQueryEventObject, e: any) => {
        if (this.restoringSettings <= 0) {
            this.persistSettings(null);
            this.view && (this.view.seekToPage = 1);
            this.refresh();
        }
    });
}
```

### OrderRepository.cs
This will modify the output SQL query.
``` csharp
protected override void ApplyFilters(SqlQuery query)
{
    // <---------- add this part
    if (Request.Criteria != (object)null)
    {
        if (Request.Criteria.ToStringIgnoreParams().Contains("ProductID"))
        {
            query.Distinct(true)
                .LeftJoin(new Alias("[Order Details]", "odd"), new Criteria("T0.OrderId") == new Criteria("odd.OrderId"));
        }
    }
    // --------->

    base.ApplyFilters(query);
    
    if (Request.ProductID != null)
    {
        var od = Entities.OrderDetailRow.Fields.As("od");

        query.Where(Criteria.Exists(
            query.SubQuery()
                .Select("1")
                .From(od)
                .Where(
                    od.OrderID == fld.OrderID &
                    od.ProductID == Request.ProductID.Value)
                .ToString()));
    }
}
```

### OrderRow.cs
Add this to pass field validation.
``` csharp
[Expression("odd.ProductID"), MinSelectLevel(SelectLevel.Never)]
public Int32? ProductID
{
    get { return Fields.ProductID[this]; }
    set { Fields.ProductID[this] = value; }
}

public class RowFields : RowFieldsBase
{
    // ...
    public Int32Field ProductID;
}
```

However, it does not work perfectly.
Only `equal` operator will give you the right result.
Some operators don't work at all.
But that gives you an idea how to add custom filter to FilterDialog.

**Comment by Garozh** [comment]
Thanks very much helped me alot @wezmag

**Comment by gfo2007** [comment]
@wezmag,

```
  if (Request.ProductID != null)
    {
        var od = Entities.OrderDetailRow.Fields.As("od");

        query.Where(Criteria.Exists(
            query.SubQuery()
                .Select("1")
                .From(od)
                .Where(
                    od.OrderID == fld.OrderID &
                    od.ProductID == Request.ProductID.Value)
                .ToString()));
    }
```

Request is not giving me access to the Property I have set up. Below is my code.

**MIRegisterRow.cs**
```
[Expression("odd.MiHeadingId"), MinSelectLevel(SelectLevel.Never)]
        public Int32? MiHeadingId
        {
            get { return Fields.MiHeadingId[this]; }
            set { Fields.MiHeadingId[this] = value; }
        }
```

```
  public Int32Field MiHeadingId;
```

**MIRegisterRepository.cs**
```
 private class MyListHandler : ListRequestHandler<MyRow> 
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                // <---------- add this part
                if (Request.Criteria != (object)null)
                {
                    if (Request.Criteria.ToStringIgnoreParams().Contains("MiHeadingId"))
                    {
                        query.Distinct(true)
                            .LeftJoin(new Alias("[MIHeadings]", "odd"), new Criteria("T0.MiId") == new Criteria("odd.MiId"));
                    }
                }
                // --------->

                base.ApplyFilters(query);

                if (Request.MiHeadingId != null)
                {
                    var od = Entities.MIHeadingRow.Fields.As("od");

                    query.Where(Criteria.Exists(
                        query.SubQuery()
                            .Select("1")
                            .From(od)
                            .Where(
                                od.MiId == fld.MiId &
                                od.MiHeadingId == Request.MiHeadingId.Value)
                            .ToString()));
                }
            }
        }
```

The repository code error is in the image below.
![repository error](https://user-images.githubusercontent.com/14317420/78391369-c281ed00-75d5-11ea-81f0-d585eb76ad81.PNG)

**Comment by Weblife123** [comment]
Dear volkanceylan  

I am trying to user ServiceLookupEditor Filter  in Grid.ts  but I am getting Error 
Please give me Any Idea 

 filters.push({
                type: Serenity.ServiceLookupEditor,
                options: {
                    service: "Movie/Product/List",
                    cascadeFrom: "AccountId",
                    cascadeField: "AccountId"
                },
                field: fld.Id,
                title: 'Account', 


I didn't got any Example for your side how to user ServiceLookupEditor  in Quick Filter using Type Script  (Grid.ts)

Please update me if you have any idea 

Thanks

**Comment by isadam** [comment]
I also got this kind of problem. Please help! Thanks a lot.
