### ISSUE TITLE
Validation on Lookup editors -Attribute "Not null" does not work as expected

### ISSUE THREAD

**Issue by PAAutofac** [volkanceylan/Serenity#4573]
It looks like the lookup editor validation does not work as expected ,I am referring to attribute "Not Null" .

Demo project eg Northwind -> Orders ->(New Order) -> Tab General , If the user clicks save button without any inputs . Required fields are Customer and Order date, if you observe the Customer lookup editor validation does not change the color to Red and the error tool tip is also not displayed.

Is it a known issue? 

While using Not Null - ideally I was expecting the editor to change the colour to RED and the tooltip message as "This field is required"

In my case apart from above issue, it displays the label name within the tool tip instead of the standard error tooltip message.

Thanks

**Comment by hubeyb** [comment]
yes known issue, 
you can fix with this css below;
maybe we can request from @volkanceylan to fix this css if there is no obstacle :)

```
.s-Form .required.error {
    border: 1px solid #ff4040 !important;
}
```

**Comment by volkanceylan** [comment]
This is because validation is performed on the hidden input and error class is appended to that input, while actual visible control is select2 container div. Thus, the border is there but can't be seen. Will try to apply a workaround though.

**Comment by volkanceylan** [comment]
Ok, this commit should solve the issue: https://github.com/volkanceylan/Serenity/commit/78950a58ace07701ab0150da632696bce4c8dc01
