### ISSUE TITLE
Login Page Not Loading Fully - ASP.NET CORE

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4578]
Hi,
I just finished setting up an asp.net core project in visual studio in windows. The login page does not load fully. Attached is the inage. Please help.
![IMG-20190826-WA0002](https://user-images.githubusercontent.com/14317420/63704729-290e8380-c81b-11e9-830d-006419e176d1.jpg)

**Comment by kipergil** [comment]
Hey there, this is my first trial and i faced with the same problem.
Could you please share how you resolved this issue ?

**Comment by minhhungit** [comment]
Run 2 commands:
>dotnet restore
>dotnet sergen restore

then rebuild solution

**Comment by planetaws** [comment]
Hi All!

I am suddenly having the same issue, but the fix did not work for me.. any other ideas?

**Comment by planetaws** [comment]
> Hi All!
> 
> I am suddenly having the same issue, but the fix did not work for me.. any other ideas?

Btw, just realized it was an unfortunate coincidence raising this bug... My namespace was "Vantage.X.Vantage.Y" and somehow that inner ns with the same name was causing some trouble.
