### ISSUE TITLE
Inplace add, Create refreshing parent dialog

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4579]
Hi everyone,

this may be an easy problem, but I have tried so much and nothing helped me till now.

When using inplaceAdd of a lookup editor and creating a new entity, my parent dialog is not refreshed. 

My problem is that I'm showing expression fields on the selected entity in my parent dialog. So if I select an entity, several fields are shown in my parent dialog. But when creating or editing the entity with lookup edit or create it's not refreshing those fields.

Thanks for any help.

**Comment by rcruzfalcon** [comment]
Hi @Garozh 

You try put `Q.reloadLookup('...')` after change value in your form?

best regards.
Roberto

**Comment by Garozh** [comment]
Yes, I allready tried that, but it's not refreshing

**Comment by luongnv6** [comment]
[LookupScript("Lookupkey", Expiration = -1)]

or

 [LookupScript("Lookupkey")]
    public class MyLookup: RowLookupScript<MyRow>
    {
        public MyLookup()
        {
            IdField = MyRow.Fields.Id.PropertyName;
            TextField = MyRow.Fields.Name.PropertyName;
            Expiration = TimeSpan.FromDays(-1);
        }
}

hope help
