### ISSUE TITLE
Changing a value in _layout.cshtml

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4580]
I want to have dynamic header values in _layout.cshtml file. In the example below:
![image](https://user-images.githubusercontent.com/29174403/63768666-70b20f80-c8ee-11e9-9106-a3cb9010af8b.png)

I would like to change the header to company name (i.e. Company A) when the user clicks the company name in the grid. How can this be done?

**Comment by Estrusco** [comment]
You can override onClick of DataGrid object, then use jQuery to modify title

```ts
        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            var item = <YourRow>this.itemAt(row);

            // jquery instructions
        }
```

**Comment by reacharihant** [comment]
In the above example, I would like to limit the record entry to only 1 record and then disable the "+ New Company". How can this be done? Also can the field value of Company name be shown in the title bar using the _layout.chtml file?
