### ISSUE TITLE
DateTimeFormatter(DisplayFormat = "MMM MM/dd/yyyy")

### ISSUE THREAD

**Issue by lijiahe** [volkanceylan/Serenity#4581]
I want to display the full name of the day of the week or The full name of the month on date time field. doesn't work at all,  any idea?

**Comment by PAAutofac** [comment]
Try something like 

[DisplayName("Work Date"), Expression("CAST(ISNULL(t0.WorkDate,'') AS VARCHAR(50))"), Size(100), DateTimeFormatter(DisplayFormat = "MM dd")]

public string WorkDateString
    {
        get { return Fields.WorkDateString[this]; }
        set { Fields.WorkDateString[this] = value; }
    }

**Comment by volkanceylan** [comment]
Display formats are applied on client side and it doesn't support all kind of format strings, especially month names etc.
