### ISSUE TITLE
Conditional Formatting on Details Editor

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4584]
Hello everyone and @volkanceylan 
I saw the conditional formatting sample and I want to use it on my details grid (Editor.ts) and am unable to find how to do the same 
If someone already worked on that or something similar then please help.
Any suggestion would be appreciated
Thanks in advance!

For Reference:
As you can see here on the checked event of checkbox I want to color that entire row and if I unchecked that same row then it will back to the previous stage
![Capture14](https://user-images.githubusercontent.com/39983941/63924985-e80aaf00-ca66-11e9-861a-ba6fd631aba5.PNG)

**Comment by luongnv6** [comment]
Hope help you

In xyzGrid.ts

```
public rowSelection: Serenity.GridRowSelectionMixin;
constructor(container: JQuery) {
            super(container);

            //checked row
            this.getGrid().onClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-item')) {
                    e.preventDefault();

                    let cellCurrent = this.slickGrid.getCellNode(p.row, p.cell);
                    if (jQuery(cellCurrent).find('span').hasClass('checked'))
                        jQuery(cellCurrent).parent().css('background-color', 'yellow');
                    else
                        jQuery(cellCurrent).parent().css('background-color', '');
                }
            });

            //checked all
            this.getGrid().onHeaderClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-all-items')) {
                    e.preventDefault();
                    if (this.rowSelection.getSelectedAsInt64().length == this.view.getItems().length)
                        this.slickContainer.find('.slick-row').css('background-color', 'yellow');
                    else
                        this.slickContainer.find('.slick-row').css('background-color', '');
                }
            });
        }`

**Comment by Shraddha996** [comment]
@luongnv6  thanks for this code. I also tried this but in my case, the yellow highlight disappears after a second I want to hold it until I click the main save/Update button(it's okay if it disappears after I uncheck the event) hope this makes sense.
thanks in advance

**Comment by luongnv6** [comment]
I checked again and did not have the problem as you mentioned
![select item grid](https://user-images.githubusercontent.com/21300748/66191907-94b8fb80-e6b9-11e9-866d-9ae19c1dccdb.gif)

**Comment by Shraddha996** [comment]
@luongnv6  thanks for your constant support
I will check again what is the problem in my code and let you know hope you will remain helpfull

**Comment by Shraddha996** [comment]
@luongnv6  still having the same issue please have a look to my code

`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Serene1.Inventory {

    @Serenity.Decorators.registerClass()
    export class TblMinDetailsEditor extends Common.GridEditorBase<TblMinDetailsRow> {
        protected getColumnsKey() { return "Inventory.TblMinDetails"; }
        protected getDialogType() { return TblMinDetailsDialog; }
        protected getLocalTextPrefix() { return TblMinDetailsRow.localTextPrefix; }
        public rowSelection: Serenity.GridRowSelectionMixin;
        private checkGrid: TblMinDetailsEditor;

        constructor(container: JQuery) {
            super(container);
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
            this.getGrid().onClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-item')) {
                    e.preventDefault();

                    let cellCurrent = this.slickGrid.getCellNode(p.row, p.cell);
                    if (jQuery(cellCurrent).find('span').hasClass('checked'))
                        jQuery(cellCurrent).parent().css('background-color', 'yellow');
                    else
                        jQuery(cellCurrent).parent().css('background-color', '');
                }
            });

            //checked all
            this.getGrid().onHeaderClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-all-items')) {
                    e.preventDefault();
                    if (this.rowSelection.getSelectedAsInt64().length == this.view.getItems().length)
                        this.slickContainer.find('.slick-row').css('background-color', 'yellow');
                    else
                        this.slickContainer.find('.slick-row').css('background-color', '');
                }
            });
        }
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 1, {
                field: '#',
                name: 'Item No',
                width: 60,
                //minWidth: 28,
                //maxWidth: 28,
                format: ctx => '<div style="padding:0 3px">' + (ctx.row + 1).toString() + '</div>',
                sortable: false,
                headerCssClass: 'align-center',
                cssClass: 'align-right'
            });

            columns.splice(0, 0,
                Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));

            return columns;
        }
    }
}`
hope this is helpfull

**Comment by luongnv6** [comment]
Just add in grid.ts

        protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
        }
`///

namespace Serene1.Inventory {

@Serenity.Decorators.registerClass()
export class TblMinDetailsEditor extends Common.GridEditorBase<TblMinDetailsRow> {
    protected getColumnsKey() { return "Inventory.TblMinDetails"; }
    protected getDialogType() { return TblMinDetailsDialog; }
    protected getLocalTextPrefix() { return TblMinDetailsRow.localTextPrefix; }
    public rowSelection: Serenity.GridRowSelectionMixin;
    private checkGrid: TblMinDetailsEditor;

    constructor(container: JQuery) {
        super(container);
        this.getGrid().onClick.subscribe((e, p) => {
            if ($(e.target).hasClass('select-item')) {
                e.preventDefault();

                let cellCurrent = this.slickGrid.getCellNode(p.row, p.cell);
                if (jQuery(cellCurrent).find('span').hasClass('checked'))
                    jQuery(cellCurrent).parent().css('background-color', 'yellow');
                else
                    jQuery(cellCurrent).parent().css('background-color', '');
            }
        });

        //checked all
        this.getGrid().onHeaderClick.subscribe((e, p) => {
            if ($(e.target).hasClass('select-all-items')) {
                e.preventDefault();
                if (this.rowSelection.getSelectedAsInt64().length == this.view.getItems().length)
                    this.slickContainer.find('.slick-row').css('background-color', 'yellow');
                else
                    this.slickContainer.find('.slick-row').css('background-color', '');
            }
        });
    }


        protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
        }

    protected getColumns() {
        var columns = super.getColumns();
        columns.splice(0, 1, {
            field: '#',
            name: 'Item No',
            width: 60,
            //minWidth: 28,
            //maxWidth: 28,
            format: ctx => '<div style="padding:0 3px">' + (ctx.row + 1).toString() + '</div>',
            sortable: false,
            headerCssClass: 'align-center',
            cssClass: 'align-right'
        });

        columns.splice(0, 0,
            Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));

        return columns;
    }
}
}`

**Comment by Shraddha996** [comment]
@luongnv6 still having the same issue 
actual code

`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace Serene1.Inventory {

    @Serenity.Decorators.registerClass()
    export class TblMinDetailsEditor extends Common.GridEditorBase<TblMinDetailsRow> {
        protected getColumnsKey() { return "Inventory.TblMinDetails"; }
        protected getDialogType() { return TblMinDetailsDialog; }
        protected getLocalTextPrefix() { return TblMinDetailsRow.localTextPrefix; }
        public rowSelection: Serenity.GridRowSelectionMixin;
        private checkGrid: TblMinDetailsEditor;
        public myPassValue: number;
        public CurrentId: number;

        constructor(container: JQuery) {
            super(container);
            var details: TblMinTranRow[] = [];
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
            this.getGrid().onClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-item')) {
                    e.preventDefault();
                    let cellCurrent = this.slickGrid.getCellNode(p.row, p.cell);
                    if (jQuery(cellCurrent).find('span').hasClass('checked')) {
                        jQuery(cellCurrent).parent().css('background-color', 'yellow');
                    }
                    else {
                        jQuery(cellCurrent).parent().css('background-color', '');
                    }

                    var item = this.getView().getItem(p.row);
                    var id = item[this.getIdProperty()].toString();//id 1,2...
                    if (item.Quantity > item.CurrentStock) {
                        Q.alert("CurrentStock is Invalid. Please select another Material");
                    }
                    else {
                        details.push({ ItemId: item.ItemId, ItemMaterialNumber: item.ItemMaterialNumber, ItemMaterialDescription: item.ItemMaterialDescription, Unit: item.Unit, Quantity: item.Quantity, CurrentStock: item.CurrentStock - item.Quantity, Rate: item.Rate, StorageLocation: item.StorageLocation, Amount: item.Amount });
                        var fieldAEditor1 = Q.findElementWithRelativeId(this.element, "DetailList").tryGetWidget(Serene1.Inventory.TblMinTranEditor);
                        fieldAEditor1.value = details;
                        if (this.CurrentId != null) {
                            Q.reloadLookup('Inventory.TblMinTran');
                            var MinDetails = Inventory.TblMinTranRow.getLookup().items.filter(x => x.MinId === this.CurrentId);
                            var details1: TblMinTranRow[] = [];
                            for (var MIN of MinDetails) {
                                var Amount = (MIN.Quantity * MIN.Rate);
                                details1.push({ ItemId: MIN.ItemId, ItemMaterialNumber: MIN.ItemMaterialNumber, ItemMaterialDescription: MIN.ItemMaterialDescription, Unit: MIN.Unit, Quantity: MIN.Quantity, CurrentStock: MIN.CurrentStock - MIN.Quantity, Rate: MIN.Rate, StorageLocation: MIN.StorageLocation, Amount: Amount });
                            }
                            fieldAEditor1.value = details.concat(details1);
                            ///////////////
                            var abc = details.concat(details1).map(x => x.ItemId);//seprate all SelectedValueName from details2
                            var unique = abc.filter(function (elem, index, self) {//////To find unique SelectedValueName
                                return index === self.indexOf(elem);
                            })
                            var details4: TblMinTranRow[] = [];
                            for (var u of unique) {
                                var networktran = DomesticOrder.TblNetworkOrderTranRow.getLookup().items.filter(x => x.ItemId === u)[0];
                                var unitname = Premier.TblUnitRow.getLookup().itemById[networktran.ItemUnitId].UnitName;
                                var Itemgodown = Premier.TblItemRow.getLookup().itemById[networktran.ItemId].GoDownId;
                                var storage = Premier.TblGoDownRow.getLookup().itemById[Itemgodown].GoDownName;
                                var rate = Premier.TblItemRow.getLookup().itemById[networktran.ItemId].Moving_Price;
                                var currentstock = Inventory.TblItemStockRow.getLookup().items.filter(x => x.ItemId === networktran.ItemId)[0];
                                if (networktran.Quantity > currentstock) {
                                    Q.alert("CurrentStock is Invalid. Please select another Material");
                                }
                                else {
                                    var amount = (networktran.Quantity * rate);
                                    details4.push({ ItemId: u, ItemMaterialNumber: networktran.Material_Number, ItemMaterialDescription: networktran.Material_Description, Unit: unitname, Quantity: networktran.Quantity, CurrentStock: currentstock.CurrentStock - networktran.Quantity, Rate: rate, StorageLocation: storage, Amount: amount });
                                    var fieldAEditor01 = Q.findElementWithRelativeId(this.element, "DetailList").tryGetWidget(Serene1.Inventory.TblMinTranEditor);
                                }
                                fieldAEditor01.value = details4;
                            }
                            ////////////
                        }
                    }//to do

                    if (details.length > 1) {
                        var abc6 = details.map(x => x.ItemId);//seprate all SelectedValueName from details2
                        var unique6 = abc6.filter(function (elem, index, self) {//////To find unique SelectedValueName
                            return index === self.indexOf(elem);
                        })
                        var details3: TblMinTranRow[] = [];
                        for (var u1 of unique6) {
                            var networktran = DomesticOrder.TblNetworkOrderTranRow.getLookup().items.filter(x => x.ItemId === u1)[0];
                            var unitname = Premier.TblUnitRow.getLookup().itemById[networktran.ItemUnitId].UnitName;
                            var Itemgodown = Premier.TblItemRow.getLookup().itemById[networktran.ItemId].GoDownId;
                            var rate = Premier.TblItemRow.getLookup().itemById[networktran.ItemId].Moving_Price;
                            var storage = Premier.TblGoDownRow.getLookup().itemById[Itemgodown].GoDownName;
                            var currentstock = Inventory.TblItemStockRow.getLookup().items.filter(x => x.ItemId === networktran.ItemId)[0];
                            if (networktran.Quantity > currentstock) {
                                Q.alert("CurrentStock is Invalid. Please select another Material");
                            }
                            else {
                                var amount1 = (networktran.Quantity * rate);
                                details3.push({ ItemId: u1, ItemMaterialNumber: networktran.Material_Number, ItemMaterialDescription: networktran.Material_Description, Unit: unitname, Quantity: networktran.Quantity, CurrentStock: currentstock.CurrentStock - networktran.Quantity, Rate: rate, StorageLocation: storage, Amount: amount1 });
                                var fieldAEditor1 = Q.findElementWithRelativeId(this.element, "DetailList").tryGetWidget(Serene1.Inventory.TblMinTranEditor);
                            }
                        }
                        fieldAEditor1.value = details3;
                        if (this.CurrentId != null) {
                            var MinDetails = Inventory.TblMinTranRow.getLookup().items.filter(x => x.MinId === this.CurrentId);
                            var details1: TblMinTranRow[] = [];
                            for (var MIN of MinDetails) {
                                var Amount2 = (MIN.Quantity * MIN.Rate);
                                details1.push({ ItemId: MIN.ItemId, ItemMaterialNumber: MIN.ItemMaterialNumber, ItemMaterialDescription: MIN.ItemMaterialDescription, Unit: MIN.Unit, Quantity: MIN.Quantity, CurrentStock: MIN.CurrentStock - MIN.Quantity, Rate: MIN.Rate, StorageLocation: MIN.StorageLocation, Amount: Amount2 });
                            }
                            fieldAEditor1.value = details3.concat(details1);
                        }
                    }
                }
            });

            this.getGrid().onHeaderClick.subscribe((e, p) => {
                if ($(e.target).hasClass('select-all-items')) {
                    e.preventDefault();
                    if (this.rowSelection.getSelectedAsInt64().length == this.view.getItems().length) {
                        this.slickContainer.find('.slick-row').css('background-color', 'yellow');
                    }
                    else {
                        this.slickContainer.find('.slick-row').css('background-color', '');
                    }

                    var NetworkId = this.myPassValue;
                    if (NetworkId != null) {
                        var networktrandetails = DomesticOrder.TblNetworkOrderTranRow.getLookup().items.filter(x => x.NetworkOrderId === NetworkId);
                        var details2: TblMinTranRow[] = [];
                        for (var details1 of networktrandetails) {
                            var itemcurrentStock = Inventory.TblItemStockRow.getLookup().items.filter(x => x.ItemId === details1.ItemId)[0];
                            var UnitId = Premier.TblItemRow.getLookup().itemById[details1.ItemId].UnitId;
                            var UnitName = Premier.TblUnitRow.getLookup().itemById[UnitId].UnitName;
                            var Rate = Premier.TblItemRow.getLookup().itemById[details1.ItemId].Moving_Price;
                            var Itemgodown1 = Premier.TblItemRow.getLookup().itemById[details1.ItemId].GoDownId;
                            var storage1 = Premier.TblGoDownRow.getLookup().itemById[Itemgodown1].GoDownName;
                            if (itemcurrentStock.CurrentStock >= details1.Quantity) {
                                var Amount = (details1.Quantity * Rate);
                                details2.push({ ItemId: details1.ItemId, ItemMaterialNumber: details1.Material_Number, ItemMaterialDescription: details1.Material_Description, Unit: UnitName, Quantity: details1.Quantity, CurrentStock: itemcurrentStock.CurrentStock - details1.Quantity, Rate: Rate, StorageLocation: storage1, Amount: Amount });
                            }
                        }
                        var fieldAEditor2 = Q.findElementWithRelativeId(this.element, "DetailList").tryGetWidget(Serene1.Inventory.TblMinTranEditor);
                        fieldAEditor2.value = details2;
                    }
                }
            });
        }

        protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
        }
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 1, {
                field: '#',
                name: 'Item No',
                width: 60,
                //minWidth: 28,
                //maxWidth: 28,
                format: ctx => '<div style="padding:0 3px">' + (ctx.row + 1).toString() + '</div>',
                sortable: false,
                headerCssClass: 'align-center',
                cssClass: 'align-right'
            });

            columns.splice(0, 0,
                Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));

            return columns;
        }
        protected usePager() {
            return false;
        }

        protected getInitialTitle() {
            return null;
        }

        get selectedItems() {
            return this.rowSelection.getSelectedAsInt32().map(x => this.view.getItemById(x));
        }
        protected initEntityDialog(itemType: string, dialog: Serenity.Widget<any>) {
            super.initEntityDialog(itemType, dialog);

            // passing codeComite from grid editor to detail dialog
            (dialog as TblMinDetailsEditor).myPassValue = this.myPassValue;
            (dialog as TblMinDetailsEditor).CurrentId = this.CurrentId;
        }

    }
}`

**Comment by Shraddha996** [comment]
@luongnv6  Also I noticed that the yellow highlight disappears when I scroll the GridEditor. I don't get the exact problem.
and if I performed scroll then it remain as is
Please help!

**Comment by luongnv6** [comment]
I don't know what this issue is about. I think you should delete all other jobs in the click action to see if the problem occurs. Then you should find out

```C#
constructor(container: JQuery) {
    super(container);
    this.getGrid().onClick.subscribe((e, p) => {
        if ($(e.target).hasClass('select-item')) {
            e.preventDefault();

            let cellCurrent = this.slickGrid.getCellNode(p.row, p.cell);
            if (jQuery(cellCurrent).find('span').hasClass('checked'))
                jQuery(cellCurrent).parent().css('background-color', 'yellow');
            else
                jQuery(cellCurrent).parent().css('background-color', '');
        }
    });

    //checked all
    this.getGrid().onHeaderClick.subscribe((e, p) => {
        if ($(e.target).hasClass('select-all-items')) {
            e.preventDefault();
            if (this.rowSelection.getSelectedAsInt64().length == this.view.getItems().length)
                this.slickContainer.find('.slick-row').css('background-color', 'yellow');
            else
                this.slickContainer.find('.slick-row').css('background-color', '');
        }
    });
}
```

**Comment by Shraddha996** [comment]
Yes I also tried that but still, it disappears when I scroll GridEditor

**Comment by luongnv6** [comment]
please try:

```C#


            this.getGrid().onScroll.subscribe((e) => {
                if (this.rowSelection.getSelectedKeys().length > 0) {
                    this.rowSelection.getSelectedKeys().forEach((v, i) => {
                        let row = this.view.getRowById(v);
                        let cellCurrent = this.slickGrid.getCellNode(row, 0);
                        if (jQuery(cellCurrent).find('span').hasClass('checked'))
                            jQuery(cellCurrent).parent().css('background-color', 'yellow');
                        else
                            jQuery(cellCurrent).parent().css('background-color', '');
                    });
                }
            });
```

**Comment by Shraddha996** [comment]
@luongnv6 Thanx a lot! It's working now
