### ISSUE TITLE
How can I read a value defined in my appsettings.json file to my _Layout.cshtml file?

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4585]

**Comment by wezmag** [comment]
It's in the Official Serenity Guide.
https://serenity.is/docs/configuration_system/README

1. Add your settings in `appsettings.json`.
``` 
{
  ...
  "AppSettings": {
    ...
    "Foo": {
      "Bar": "Foobar" 
    }
  }
}
```
2. Define your class 
``` csharp
namespace YourProjectNamespace
{
    [SettingScope("Application"), SettingKey("Foo")]
    public class Foo {
        public string Bar { get; set; }
    }
}
```

3. Get setting value in controller (I used a ViewBag to store the value, you can use ViewData or a model instead.)
``` csharp
namespace YourProjectNamespace.YourModuleName.Pages
{
    using Serenity.Web;
    using Microsoft.AspNetCore.Mvc;
    using Serenity.Abstractions;
    using Serenity;

    [PageAuthorize(typeof(Entities.YourRow))]
    public class YourController : Controller
    {
        [Route("YourModuleName/Your")]
        public ActionResult Index()
        {
            ViewBag.Foobar = Config.Get<Foo>().Bar;   // get setting value and store in a ViewBag
            return View(MVC.Views.YourModuleName.Your.YourIndex);
        }
    }
}
```

4. Retrieve the value in your `_Layout.cshtml`
``` cshtml
@ViewBag.Foobar?.ToString()
```

If you need to retrieve the value in every controller, you might need to use a base controller class.

**Comment by rcruzfalcon** [comment]
Hi @reacharihant 

We use one method in the EndPoint

 ` [RoutePrefix("Services/Common/Config"), Route("{action}")]
    [ConnectionKey("Default"), ServiceAuthorize]
    public class ConfigController : ServiceEndpoint
    {
        public ConfigRetrieveResponse Retrieve(IDbConnection connection, ConfigRetrieveRequest request)
        {
            var iTrafficSettings = Config.Get<Common.Services.Foo>();

            return new ConfigRetrieveResponse { Settings = Foo };
        }
    }`

and from the .ts make a call to this.

`...ConfigService.Retrieve({} ,r=>{ 
   ...
})`

Best regards.
Roberto

**Comment by reacharihant** [comment]
Thanks to both of you!!
