### ISSUE TITLE
Auth Cookies from mobile expired

### ISSUE THREAD

**Issue by mjacoup** [volkanceylan/Serenity#4588]
I success-ed call all serenity api's from android APP . but discovered that the cookies expires , and need to auth again , the logic that mobile app will auth one time only and then every api call will send the cookie only . So how you handle these scenarios in mobile app ?? do you make two calls in every request one for auth and another for the target request ??? if i think it will be too long and affect performance , any help ??

**Comment by MaziarSangi** [comment]
You can Increase Expire time in startup Like this: 
ervices.AddAuthentication(o =>
            {
                o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                o.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                o.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie(o =>
            {
                o.Cookie.Name = ".AspNetAuth";
            
                o.ExpireTimeSpan = TimeSpan.FromHours(1);
             
           
                o.LoginPath = new PathString("/Account/Login/");
                o.AccessDeniedPath = new PathString("/Account/AccessDenied");
            });

**Comment by MaziarSangi** [comment]
You can Increase Expire time of  Cookie like this example : 
services.AddAuthentication(o =>
            {
                o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                o.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                o.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie(o =>
            {
                o.Cookie.Name = ".AspNetAuth";
                o.ExpireTimeSpan = TimeSpan.FromHours(1);
               
                o.LoginPath = new PathString("/Account/Login/");
                o.AccessDeniedPath = new PathString("/Account/AccessDenied");
            });

**Comment by chockyu** [comment]
@mjacoup  hello , would you please give me an example about serenity on android app ,I have no idea about it
