### ISSUE TITLE
Filegroup reference and partitioning scheme' is not supported when deployed to Azure Web Service

### ISSUE THREAD

**Issue by felixckt** [volkanceylan/Serenity#459]
When I deployed the project to Azure and run at first time, even I removed the security check of the database. Below error displayed during the migration of the sample data. I checked the web the script should be modified. Is this the recommended method ?

Felix

http://anandpandey.com/post/2014/03/31/filegroup-reference-and-partitioning-scheme-is-not-supported-in-this-version-of-sql-server

Server Error in '/' Application.

'Filegroup reference and partitioning scheme' is not supported in this version of SQL Server.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: 'Filegroup reference and partitioning scheme' is not supported in this version of SQL Server.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[SqlException (0x80131904): 'Filegroup reference and partitioning scheme' is not supported in this version of SQL Server.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +2434922
   System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +5736592
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +285
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +3731
   System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) +940
   System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) +272
   System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +280
   FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteBatchNonQuery(String sql) +294

[Exception: An error occurred executing the following sql:
/****** Object:  Table [dbo].[CustomerDemographics]    Script Date: 08/12/2011 11:46:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerDemographics](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerTypeID] [nvarchar](10) NOT NULL,

**Comment by 107295472** [comment]
Your database version is low

**Comment by volkanceylan** [comment]
Remove Northwind, or open NorthwindDBScript_SqlServer and remove all
`ON [PRIMARY]` statements.

**Comment by volkanceylan** [comment]
Also `TEXTIMAGE_ON [PRIMARY]`, in short remove anything with [PRIMARY]
