### ISSUE TITLE
ConnectionKey change at runtime

### ISSUE THREAD

**Issue by ZioZenigata** [volkanceylan/Serenity#4591]
Is it possible to change ConnectionKey at runtime ?
Thanks a lot

**Comment by minhhungit** [comment]
@ZioZenigata This way may work for you
```csharp
using System.Reflection;

var connectionKey = typeof(UserRow).GetCustomAttribute<ConnectionKeyAttribute>()?.Value;
```

**Comment by ZioZenigata** [comment]
I have not explained myself correctly. I would like to point a database based on the connected user.
In  my  file myModuleRow.cs

if connect User1
[ConnectionKey("connectionKeyUser1"), Module(myModule), TableName("myTable")]

if connect User2
[ConnectionKey("connectionKeyUser2"), Module(myModule), TableName("myTable")]

Thanks

**Comment by Estrusco** [comment]
Is better switch to multi tenant. If you want different DB for different user, you can see at this wiki entry (but this work for .Net, don't work if you use .Net Core)


https://github.com/volkanceylan/Serenity/wiki/Database:-One-application-with-different-database-per-customer

**Comment by ZioZenigata** [comment]
Very nice..... Thanks a lot!
