### ISSUE TITLE
JsonField<Type>

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4594]
Dear @volkanceylan 
Please consider to add a new field type called JsonField<Type> 
To work with JSON strings stored in the database. 

Currently, I am using StringField and parsing the JSON to a certain type.
It will be nice to have JsonField which will handle these parse and stringify things.

FYI
https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017

**Comment by kilroyFR** [comment]
@dfaruque which library (js/ts) are you using to display json content in form ?

**Comment by dfaruque** [comment]
@kilroyFR I have used Serenity's PropertyGrid and slightly customized GridEditor.ts

**Comment by JohnRanger** [comment]
@dfaruque ,

it's probably not the full blown solution you are suggesting - but could this here help solving your issue? https://radekmaziarka.pl/2018/01/22/dapper-json-type-custom-mapper/

John

**Comment by volkanceylan** [comment]
OK, nice idea, i'll consider this, just can't do it specific to SQL server, but agree it should handle serialize / deserialize

**Comment by dfaruque** [comment]
Thanks, I have mentioned the SQL server for example. Many database engines have such a feature nowadays.

**Comment by dfaruque** [comment]
BTW, handling serialize/deserialize will be enough.

**Comment by volkanceylan** [comment]
There is a JsonField type now.

**Comment by ShakotkoPavel** [comment]
How I can use JsonField type to write data to postgres database to column with type 'json'?
