### ISSUE TITLE
	 How do I generate Chart Dynamically Using Chart.js with Serenity ?

### ISSUE THREAD

**Issue by Mohammad-Yasfo** [volkanceylan/Serenity#4595]
Hello Serenitos 
I need to edit or generate charts in Dashboard Serenity that dynamically interacts with changing data.

**Comment by kilroyFR** [comment]
see the example given here : https://github.com/volkanceylan/Serenity/issues/4572

**Comment by Mohammad-Yasfo** [comment]
Hi @kilroyFR 
I tried several ways to generate charts in Dashboard, but my attempts have failed. I have little experience with this platform
Please, send me the source code for GitHub example that you applied #4572 
I look forward to hearing from you.
Yours sincerely,
