### ISSUE TITLE
QuickSearch  not appear in DetailListGrid 

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4597]
Hello
I have Master-Detail Form and I added QuickSearch to Name field of Detail Row class 
But QuickSearch widget does not appear in top of DetailList in Master Form.
Does anybody Knows How to add it?

**Comment by JohnRanger** [comment]
Quicksearch is currently - according to my knowledge - not supported in Serenity Framework in detail list.

With kind regards,

John

**Comment by Shraddha996** [comment]
@MaziarSangi Hello, After a lot of RND finally am able to get the Quicksearch on my DetailListGrid
and also it works just like grid QuickSearch
If you want then I can post the code here and explain

**Comment by MaziarSangi** [comment]
@Shraddha996 
Can you please explain how to add it in DetailListGrid?

**Comment by Shraddha996** [comment]
@MaziarSangi  just add below code in the **DetailList** Editor.ts file    **(Outside the constructor)**

private searchText: string;
private byParentKey: Q.Grouping<PermissionCheckItem>;

   protected createToolbarExtensions(): void {
            super.createToolbarExtensions();
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);//chechbox
            Serenity.GridUtils.addQuickSearchInputCustom(this.toolbar.element, (field, text) => {
                this.searchText = Select2.util.stripDiacritics(Q.trimToNull(text) || '').toLowerCase();
                this.view.setItems(this.view.getItems(), true);
            });
        }

        protected onViewFilter(item: PermissionCheckItem): boolean {
            if (!super.onViewFilter(item)) {
                return false;
            }

            if (!Serenity.SlickTreeHelper.filterById(item, this.view, x => x.ParentKey))
                return false;

            if (this.searchText) {
                return this.matchContains(item) || item.IsGroup && Q.any(this.getDescendants(item, false), x => this.matchContains(x));
            }

            return true;
        }

        private matchContains(item: PermissionCheckItem): boolean {
            return Select2.util.stripDiacritics(item.ItemMaterialNumber || '').toLowerCase().indexOf(this.searchText) >= 0;
        }

        private getDescendants(item: PermissionCheckItem, excludeGroups: boolean): PermissionCheckItem[] {
            let result: PermissionCheckItem[] = [];
            let stack = [item];
            while (stack.length > 0) {
                let i = stack.pop();
                let children = this.byParentKey[i.Key];
                if (!children)
                    continue;
                 
                for (let child of children) {
                    if (!excludeGroups || !child.IsGroup) {
                        result.push(child);
                    }
                    stack.push(child);
                }
            }
            return result;
        }
    }

    export interface PermissionCheckItem {
        ParentKey?: string;
        Key?: string;
        IsGroup?: boolean;
        ItemMaterialNumber?: string;///field name on which you want to add quicksearch
    }
