### ISSUE TITLE
grid detail editor - how to disable 

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4599]
hi, does anyone know how to disable/enable a grid detail editor
thanks

**Comment by minhhungit** [comment]
This is a ugly solution :disappointed_relieved:

```javascript
private disableGridEditor(gridEditor: Common.GridEditorBase<any>, isDisable: boolean) {
    if (isDisable) {
        gridEditor.getGridField().find(".editor").css("position", "relative");
        gridEditor.getGridField().find(".editor").append(`<div class='disable-mask-flag' style="position: absolute;top: 0;left: 0;background: #ccc;width: 100%;height: 100%;z-index: 999;opacity: 0.35;"></div>`);
    }
    else {
        gridEditor.getGridField().find(".editor").css("position", "static");
        gridEditor.getGridField().find(".editor").find(".disable-mask-flag").remove();
    }
}
```

**Comment by JohnRanger** [comment]
Hi @minhhungit ,
do you mean a detail grid editor?

What exactly do you want to achieve?

A technical/optical disable (greying out and no editing possible) or an invisible-making of the detail grid editor?

With kind regards,

John

**Comment by minhhungit** [comment]
@JohnRanger  Yes, I mean grid detail editor, sorry about title (updated)

I showed my solution above (it added a layer on top of grid detail editor, but that solution is ugly, some people may know that technical and can remove that layer using F12)

I don't want that way, so my question is do you know any better way to disable grid detail editor

Thanks

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

sorry for the longer delay...


What I do when I have to "disable" a detail editor is the following:

Generally for all my detail editors (detail grids) I remove all [editlink] tags for any column that is displayed in the detail grid so no user can trigger the edit of any of these entries by just clicking on an editlink.

Then I add two additional columns at the left of the detail grid (idea from @brunobola not so long ago here in the forum - https://github.com/volkanceylan/Serenity/issues/4304):

![DetailGrid-AdditionalColumns](https://user-images.githubusercontent.com/2699447/64873397-4039d780-d649-11e9-96a4-6b4cc0160186.png)

Then I attach delete and edit functionality to the icons of these two columns (by hijacking the onclick event).

---------------

Now when I have to "disable" a detail grid, I 

1. Remove all buttons on the detail editor (detail grid) which could allow the user to manipulate something in the grid (like the add button)
2. I am splicing (removing) then the two special columns at the very left

Which gives me a technically disabled detail editor/grid - like this:

![DetailGrid-AdditionalColumns-disabled](https://user-images.githubusercontent.com/2699447/64873645-d2da7680-d649-11e9-8088-1ed451cec830.png)

Here the relevant code from the detail editor (xyzEditor.ts):

```ts
// *******************************************************************************************************************

        //Override onClick
        protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                // *** has clicked on edit magnifying glass icon ***
                if (target.hasClass('view-details')) {

                    var editRow = (('``' + (row) as RALayoutManager3.Ressorts.RessortsLayoutTransformationDetailsRow) as number);
                    var id = this.view.getIdxById(editRow);
                    if (id == null) {

                        editRow = (('`' + (row) as RALayoutManager3.Ressorts.RessortsLayoutTransformationDetailsRow) as number);
                        id = this.view.getIdxById(editRow);
                        if (id == null) {
                            editRow = row;

                            id = this.view.getIdxById(editRow);
                        }
                    }

                    // *** Edit Row ***
                    this.createEntityDialog(this.getItemType(), dlg => {
                        var dialog = dlg as RALayoutManager3.Common.GridEditorDialog<RessortsLayoutTransformationDetailsRow>;
                        dialog.onDelete = (opt, callback) => {
                            if (!this.deleteEntity(editRow)) {
                                return;
                            }
                            callback({});
                        };

                        dialog.onSave = (opt, callback) => this.save(opt, callback);
                        dialog.loadEntityAndOpenDialog(item);
                    });;
                }
                else if (target.hasClass('delete-row')) {
                    Q.confirm(Q.text("Db.deleteEntry"), () => {


                        //var id = item.__id;
                        var id = this.id(item);
                        this.view.deleteItem(id);

                    });
                }
            }
        }

        // *******************************************************************************************************************
```

```ts
// *******************************************************************************************************************
        
        protected getAddButtonCaption() {
            return "Add";
        }

        // *******************************************************************************************************************
```

```ts
// *******************************************************************************************************************
        
        protected initEntityDialog(itemType: string, dialog: Serenity.Widget<any>) {
            super.initEntityDialog(itemType, dialog);

            // *** Debug only ***
            //alert('Rid from Editor: ' + this.RessortId);
            //alert('Tid from Editor: ' + this.TacMasterLayoutTransformationId);
            
            // *** passing RessortID from grid editor to detail dialog ***
            (dialog as RessortsLayoutTransformationDetailsDialog).RessortId = this.RessortId;

            // *** passing TacMasterLayoutTransformationId from grid editor to detail dialog ***
            (dialog as RessortsLayoutTransformationDetailsDialog).TacMasterLayoutTransformationId = this.TacMasterLayoutTransformationId;

            // *** passing currently existing details from grid editor to detail dialog ***
            (dialog as RessortsLayoutTransformationDetailsDialog).details = this.view.getItems();
            
        }

        // *******************************************************************************************************************

        public DisableAddButton()
        {
            this.toolbar.findButton('add-button').hide();
        }

        public EnableAddButton() {
            this.toolbar.findButton('add-button').show();
        }

        public DisableModifyIcon() {
            var columns = this.slickGrid.getColumns();

            columns.splice(0, 1);   // *** Delete delete icon column ***
            columns.splice(0, 1);   // *** Delete modify icon column ***

            this.slickGrid.setColumns(columns);
        }

        public EnableModifyIcon() {
            var columns = this.slickGrid.getColumns();

        

            // *** Add magnifying glass (edit)
            columns.unshift({
                defaultSortAsc: true,
                field: 'Edit Details',
                focusable: true,
                name: '',
                id: 'Edit Detail',
                formatter: function (row, cell, value, columnDef, dataContext) {
                    
                    return '<a class="inline-action view-details" title="' + Q.text("Controls.Edit") + '">' + '<i class="fa fa-search text-blue"></i></a>';
                },
                resizable: true,
                selectable: true,
                sortable: true,
                width: 24,
                minWidth: 24,
                maxWidth: 24,
                visible: true
            });

            // *** Add Delete button ***
            columns.unshift({
                field: 'Delete Row',
                name: '',
                formatter: function (row, cell, value, columnDef, dataContext) {

                    return '<a class="inline-action delete-row" title="' + Q.text("Controls.Delete") + '">' + '<i class="fa fa-trash-o text-red"></i></a>';
                },
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            this.slickGrid.setColumns(columns);

            Serenity.SubDialogHelper.triggerDataChange(this);

        }
```

If you need to enable or disable these two columns (trash and magnyfying glass) and the add button 
 from the parent xyzDialog.ts, then you simply can call these methods of the detail editor like this (in the parent xyzDialog.ts, this.form.Detaillist is the form field for the detail grid):

**Handle Add button:**
- this.form.DetailList.EnableAddButton(); 
- this.form.DetailList.DisableAddButton(); 

**Handle the two trash/edit columns:**
- this.form.DetailList.EnableModifyIcon(); 
- this.form.DetailList.DisableModifyIcon(); 



Hope this helps you further.

With kind regards,

John

**Comment by minhhungit** [comment]
thanks @JohnRanger 

I agree that it's a solution !

but honestly I feel it's quite complex just for disabling an editor

hope we have a simpler solution

**Comment by JohnRanger** [comment]
@minhhungit 

yeah - I know. Took me a while to figure this out - If you find a simpler solution, please let me know  as I am also interested in such a solution :-)

I tried other things - but I never was able to work out the toggling back and forth of the editlinks.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

just now I had another idea.

Use your approach to "shield" (and potentially optically dim) the whole detail grid, but additionally - within the detail editor / detail grid - add a public variable like this:

```ts
public isDisabled: boolean = false;
```

and override the onClick event within the detail editor / detail grid like this:

```ts
        //Override onClick
        protected onClick(e: JQueryEventObject, row: number, cell: number): void {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            // *** Here we add a protection so the users cannot click on anything when the detail editor has the isDisabled set to true ***
            if (this.isDisabled)
                return;
        }
```

Now in your parent xyzDialog.ts  in your disable method, add the following:

```ts
private disableGridEditor(gridEditor: Common.GridEditorBase<any>, isDisable: boolean) {
    if (isDisable) {
        gridEditor.isDisabled = true;  // *** here we set the isDisabled flag within the detail editor / detail grid to true (disabled) ***
        gridEditor.getGridField().find(".editor").css("position", "relative");
        gridEditor.getGridField().find(".editor").append(`<div class='disable-mask-flag' style="position: absolute;top: 0;left: 0;background: #ccc;width: 100%;height: 100%;z-index: 999;opacity: 0.35;"></div>`);
    }
    else {
        gridEditor.isDisabled = false;  // *** here we set the isDisabled flag within the detail editor / detail grid to false (enabled) ***
        gridEditor.getGridField().find(".editor").css("position", "static");
        gridEditor.getGridField().find(".editor").find(".disable-mask-flag").remove();
    }
}
```
Now from the parent xyzDialog.ts - when you want to disable the detail editor/ detail grid - just call your disableGridEditor method.

This not only "shields" the detail editor / detail grid by the layer you put over it - but the detail grid also actively refuses to accept any click on it when the detail grid is disabled.

As this functionality during runtime is embedded within the minified javascript of the whole page, this is substantially more difficult to hack than just press F12 and remove the protecting layer.

Final words: 

1. Eventually it is also needed to capture and "trash" keyboard clicks within the detail grid when it is disabled - but I never have done this - so nothing, which I could contribute quickly.
2. I didn't try the above yet. But it should work.

Please let me know if this would be a better solution :-)

With kind regards,

John

**Comment by minhhungit** [comment]
@JohnRanger  it looks a better solution, thank you

I have not test it yet, but I will test with buttons on grid editor, not sure we can prevent its click event

**Comment by JohnRanger** [comment]
@minhhungit ,

you should be able to suppress the buttons' click event with this: https://www.w3schools.com/jsref/event_preventdefault.asp

And something like this to re-establish the click: 
https://stackoverflow.com/questions/11772926/event-preventdefault-on-first-click-then-remove

Please post here if you have found a good, reasonable solution :-)

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

did the above resolve your challenge? If yes then would you be willing to share here the tested - final - version? If also yes, then I will make a wiki article out of it.

Regards,

John

**Comment by minhhungit** [comment]
@JohnRanger  I have not test it yet sir, I will try

**Comment by volkanceylan** [comment]
Grids have a readonly property now, might be useful for some cases but needs manual implementation.

**Comment by sispk6** [comment]
thread is old , but in case anyone still looking for it ..
`
  Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);              
                this.form.detail1.set_readOnly(true);
                this.form.detail1.set_readOnly(true);
`
works like a charm
