### ISSUE TITLE
Serene template won't F5 out of the box.

### ISSUE THREAD

**Issue by Tomcu** [volkanceylan/Serenity#46]
I'm using VS2015, I installed the template and hit F5. It appears that the script project is not built when launching the web project. Under solution configuration if you make the script project a dependency of the web project it should alleviate this.

**Comment by volkanceylan** [comment]
I am also using VS2015, and but i can't reproduce this. 

As template contains an already compiled version of Serene.Script under Serene.Web/Scripts/site/Serene.Script.js, you actually don't have to build before F5. What kind of error you are getting? 

Maybe something is different in your environment. I also tested in some friends computer.

**Comment by volkanceylan** [comment]
Anyway i updated Serene.sln with dependency, thanks for suggestion.

**Comment by Tomcu** [comment]
Huh, that's odd. As for specific errors I'm not sure, there were about 2,500 and when I see that it usually means one or more dependent projects failed to build. So I built .Script (just right click, build), then built .Web, then f5 worked. 

It's entirely possible this issue is specific to me. My current installation has seen progression from vs2012 to vs2013 to vs2015 ctp, to vs2015 rtm. There could definitely be remnants or crud causing the issue.

**Comment by Tomcu** [comment]
How long does it take for the online template to propagate? I'd be happy to clean things up locally and test this for you.

**Comment by volkanceylan** [comment]
I tested now but seems like Visual Studio template ignores the build order i set while publishing template.

I'll work a bit more to find a workaround. Your issue might be specific to Saltarelle compiler not being located under packages directory, but i have no idea why VS2015 didn't extract it from the template.

**Comment by volkanceylan** [comment]
Tried also changing project order in root template but this results in startup project set to Script one. And there is no way to set it. Seems like MS created multi project templates in a hurry :)

**Comment by Tomcu** [comment]
I created a new clean project from the template and this time there were no issues. False alarm maybe?

**Comment by volkanceylan** [comment]
Maybe, anyway thanks again for reporting ;) Seems like need a wizard to set dependencies.

**Comment by volkanceylan** [comment]
Another possibility is if you had an older / different version of Saltarelle compiler, Visual Studio couldn't load new targets and got confused so you got errors. It happens to me sometimes when i upgrade Saltarelle. I needed to reopen VS.
