### ISSUE TITLE
Collect a reason in a confirm dialog

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#460]
Dear @volkanceylan,
I was wondering if there is a simple way to collect a reason (string) in a confirm dialog or something like that...
I have not seen any example to adapt...

Thanks for you support
Best Regards

**Comment by volkanceylan** [comment]
You need to write one deriving from PropertyDialog. You can take NoteDialog as a sample.

**Comment by marcobisio** [comment]
Copy that!
Thank you very much
