### ISSUE TITLE
Overriding the ConnectionString value in Appsettings.json

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4601]
While trying to publish a serene app to Azure, I get an "...SQL Exception" because the Azure App Service is reading from appsettings.json which is connected to my local db. To overcome that I have to manually update the connection string of my AzureSQL in the appsetting.json everytime I have to publish my app to Azure.

How can I handle this scenario in Serene app that is uses localdb only for development and AzureSQL mapped to Appservice when on Production?

**Comment by edwardch** [comment]
I haven't done this with .NET Core, but maybe take a look here: [Configure an App Service app in the Azure portal](https://docs.microsoft.com/en-us/azure/app-service/configure-common#app-settings).

For MVC version you can just add them as connection strings in Settings>Configuration in your Azure App Service.

**Comment by reacharihant** [comment]
Thanks @edwardch but no avail. I am yet to find a solution wherein the connectionstring of AzureSql takes precedence over the appsettings.json which points to my local db automatically (i.e. without me going to appsettings.json, updating the connection string and re-publishing the app).

**Comment by edwardch** [comment]
Did you try adding an app setting (in Azure) called `SQLAZURECONNSTR_YOURCONNECTIONNAME` or `SQLCONNSTR_YOURCONNECTIONNAME` ?

If this doesn't work I'll set up a demo app in Azure (.NET Core) and see if I can get it working. Probably not this week though...

**Comment by edwardch** [comment]
Hey @reacharihant, just checking if you had any luck with this?

I've been testing my .NET Core app in Docker and managed to get the connection strings overridden by using environment variables. The trick was to use a double underscore in place of a colon.

So in your appsettings.json, you have
```json
{
  "Data": {
    "Default": {
      "ConnectionString": "YourConnectionString",
      "ProviderName": "System.Data.SqlClient"
    }
    // Other settings
}
```

To override this connection string `Data:Default:ConnectionString` with an Azure SQL Server connection string I added this environment variable, which works:

`Data__Default__ConnectionString="Server=tcp:YourServer.database.windows.net,1433;Initial Catalog=YourDatabase;Persist Security Info=False;User ID=YourUser;Password=YourPassword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"`

From my understanding Azure app service uses container under the hood so there may be a chance that this works for you.

I'll try do a Docker wiki entry later this week.

Hope this helps!

**Comment by reacharihant** [comment]
Hi @edwardch, thanks for your suggestion. It worked for me and am happy to get a solution finally!! All this while I was focusing more on the serenity's app code to handle it than using the Azure's app settings. Thanks once again!!

**Comment by edwardch** [comment]
Great! Good to know that this works in Azure App Service as well as Docker...
