### ISSUE TITLE
AutoSizeColumn and Dialog.Template

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4603]
hey Volkan, i have defined Modules with each one using AutosizeColumn mixin on each Grid.
It works great when each grid is displayed on its own cshtml, but when i try to display those same grids into tabs (as in the demo, i mean using Dialog.Template.cshtml) then the grids are displayed but autosizecolumn mixin is not executed( i have to resize each column manually).

Do you have any idea why it does not work ?

in my base class i have :

    protected createSlickGrid(): Slick.Grid {
      var grid = super.createSlickGrid();

      // Full Row Selection
      grid.setSelectionModel(new Slick.RowSelectionModel());

      // Columns auto resize
      new Serenity.AutoColumnWidthMixin({grid: this});

      return grid;
    }
Thanks !

**Comment by hubeyb** [comment]
did you try to find grid and rerun AutoColumnWidthMixin by override updateInterface()

**Comment by kilroyFR** [comment]
How can i force Refresh ?

In my main Dialog, doing a Refresh does not force AutoColumnWidthMixin to execute.

```
    protected updateInterface(): void {

      super.updateInterface();

      this.bolValidationTapGrid.refresh();

      this.bolTransactionGrid.refresh();
    }
```

**Comment by hubeyb** [comment]
Ok, do not refresh the grid,

call AutoColumnWidthMixin in updateInterface()

```
  // Columns auto resize
  new Serenity.AutoColumnWidthMixin({grid: this.bolTransactionGrid});
```
