### ISSUE TITLE
ImageUploadEditor and svg files

### ISSUE THREAD

**Issue by gulgil** [volkanceylan/Serenity#4604]
It appears that ImageUploadEditor does not support .svg files.

When I try to upload a .svg it gives me a "Uploaded file is not an image!" error. But svg's are images (vector graphics).

Is there anyway to make ImageUploadEditor accept .svg files?

**Comment by JohnRanger** [comment]
probably the error message is a bit wrong. It better should be: "Uploaded file is not a bitmap image!".

As long as you are willing to accept that there will be no preview of the svg directly within the imageUploadEditor widget, then you can set the attribute: AllowNonImage which _should_ allow you to upload unrenderable files.

Hope, this helps.

With kind regards,

John

**Comment by gulgil** [comment]
I can accept that. 
I have created a ImageFormater to display ths SVG on xyzColumns, and it works perfectly. 
So thanks :)
