### ISSUE TITLE
Insert DropDown Menu Button on Toolbar - xyzDialog.ts

### ISSUE THREAD

**Issue by MimmoDany** [volkanceylan/Serenity#4605]
Hello

I have the StartSharp version 3.9.9
How can I manage the dropdown menu button on the toolbar?
Is a code example possible?

Thanks in advance.

![Button](https://user-images.githubusercontent.com/35045921/64776963-80219180-d559-11e9-8bec-065b0a8ab924.png)

**Comment by JohnRanger** [comment]
Hi @MimmoDany 

some questions :-)

(1) what is the purpose of this "button"? (looks for me technically more like a select drop down)
(2) what kind of button is this? (Which library)
(3) did you already managed to put this kind of button into the button toolbar or is this a graphical mockup?
(4) What do you want to achieve?

This helps people here in the forum to better understand what you want to do and possibly can then better help you

With kind regards,

John

**Comment by MimmoDany** [comment]
Hello
What I need is to be able, in serenity, to be able to manage drop-down buttons as foreseen in bootstrap.

https://getbootstrap.com/docs/4.0/components/dropdowns/​

I think this native integration in serenity is necessary.

Thanks in advance

**Comment by JohnRanger** [comment]
Hi @MimmoDany ,
unfortunately, the link you provided gives me currently a 404 (not found). Anyway: I see 3 possibilities for you to get this - currently non-existing - feature in Serenity:

(1) Someone else has already done it for Serenity and is willing to share it
(2) You develop it by yourself (but you wouldn't ask here if you would/could do that) - and if you are kind you will share it here for others :-)
(3) You get in contact with Volkan and pay him for the development / integration of this new feature

The Serenity way to to the same functionality (but different optical representation) you can see here in the demo: https://serenity.is/demo/BasicSamples/QuickFilterCustomization

Look at the quick filter "ship via not in".

With kind regards,

John
I know - this is probably not the answer you were looking for- but that is the way how

**Comment by JohnRanger** [comment]
@MimmoDany ,

ok - let's assume that we will be able to add such a button (your link by the way returns a 404). to the button bar within xyzDialog.ts.

From where does the button gets its selectable options (entries)? A SQL table or are these static elements?

What should the action be, once one of these elements (printers) has been selected by the user?

--> Stored in the database?

Thanks for further clarification.

With kind regards,

John

**Comment by MimmoDany** [comment]
The correct link:
https://getbootstrap.com/docs/4.0/components/dropdowns/

**Comment by JohnRanger** [comment]
@MimmoDany ,

because I was curious (and had nothing more important to do) I invested some hours and I finally got a solution. It is _not_ the real bootstrap dropdown button - but it is very similar.

You will have to style the menu so it fits the Serenity design yourself.

![dropdown button](https://user-images.githubusercontent.com/2699447/65354348-9978ac80-dbef-11e9-879a-1249a4d90fb3.png)

I just did test integrate this with nordwind product dialog.

This is done by using the following library: 
- Description / Documentation https://labs.abeautifulsite.net/jquery-dropdown/ 
- Code: https://github.com/soundasleep/jquery-dropdown

You need only the following 2 files from above library:
- jquery.dropdown.js
- jquery.dropdown.css

Put these 2 files in a new directory under /Scripts/jquery.dropdown/

You have to map the css file in your CssBundles.json in the Site section like this:
```json
"~/Scripts/jquery.dropdown/jquery.dropdown.css",
```
The js file has to be mapped within ScriptBundles.json in the site section like this:
```js
"~/Scripts/jquery.dropdown/jquery.dropdown.js",
```

And then in your xyzDialog.ts, put the following in::
```ts
namespace Serene1.Northwind {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.maximizable()
    export class ProductDialog extends Serenity.EntityDialog<ProductRow, any> {
        protected getFormKey() { return ProductForm.formKey; }
        protected getIdProperty() { return ProductRow.idProperty; }
        protected getLocalTextPrefix() { return ProductRow.localTextPrefix; }
        protected getNameProperty() { return ProductRow.nameProperty; }
        protected getService() { return ProductService.baseUrl; }

        protected form = new ProductForm(this.idPrefix);

        protected afterLoadEntity() {
            super.afterLoadEntity();

            // *** Add attributes to Dropdown button ***
            var stampebutton = this.toolbar.findButton('stampe');
            stampebutton.attr("data-jq-dropdown", "#jq-dropdown-1");

            // *** Create drop down menu ***
            var Menu = "<div id=\"jq-dropdown-1\" class=\"jq-dropdown jq-dropdown-relative\">";
            Menu += "<ul class=\"jq-dropdown-menu\">";
            Menu += "<li><a onclick=\"processMenuChoice(1);\" class=\"fa fa-print\">Stampante 1</a></li>";
            Menu += "<li><a onclick=\"processMenuChoice(2);\" class=\"fa fa-print\">Stampante 2</a></li>";
            Menu += "<li><a onclick=\"processMenuChoice(3);\" class=\"fa fa-print\">Stampante 3</a></li>";
            Menu += "</ul>"; 
            Menu += "</div>";
            
            stampebutton.after(Menu);

        }

        protected getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            // *** Create Dropdown-Button ***
            buttons.push(
                {
                    title: Q.text("Dialogs.Documents.Button.Stampante"),	// *** Get button text from translation
                    cssClass: 'stampe',
                    icon: 'fa-print',
                    onClick: () => {

                        // *** do something on click if you want **

                    },
                }
            );

            

            return buttons;
        }
    }
}

function processMenuChoice(menuId: number) {

    alert("Menu id: " + menuId + " clicked");

}
```

Hope this helps.

With kind regards,

John

**Comment by MimmoDany** [comment]
Thanks John

I will integrate your solution as soon as possible.
I think it's an important function to complete the Serenity toolbar.

Thanks for your availability

**Comment by JohnRanger** [comment]
Hi @MimmoDany ,

if you have properly integrated this, would you mind to make a quick wiki article out of it? :-)  (Especially of the missing styling and the proper integration of the onclick-function into the object model of Serenity)

Then all can benefit from your and mine effort.

With kind regards,

John

**Comment by MimmoDany** [comment]
Hello John

I will publish the code as soon as possible. However I am evaluating other possible menus.
I found this page that collects some examples available on the internet:
https://www.jqueryscript.net/tags.php?/Drop%20Down%20Menu/

I like these two:
https://www.jqueryscript.net/menu/Drop-Down-Menu-with-Images-Plugin-ddSlick.html
https://www.jqueryscript.net/menu/Multilevel-Dropdown-Menu-Plugin-For-Bootstrap-Dropdown-On-Hover.html

Bye

**Comment by JohnRanger** [comment]
Hi @MimmoDany ,

they optically for themselves look nice -but in my opinion they do not integrate really well with the current graphical design of Serenity. 

One has wild animations (which the rest of a Serenity app does not have) and the other has a relatively different graphical style.

Looking forward for your final implementation :-)

With kind regards,

John

**Comment by volkanceylan** [comment]
Simple bootstrap dropdowns should work, there was an issue with css if i remember right, will check.

**Comment by volkanceylan** [comment]
This issue is due to buttons-inner div having overflow hidden. If you override it to visible, bootstrap dropdowns will be shown.
