### ISSUE TITLE
extra point in bulk action example?

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#4606]
with some update there came a point into the grid?
![Serenity](https://user-images.githubusercontent.com/39523006/64786247-545cd680-d56e-11e9-9b46-2d5c7010d046.PNG)

**Comment by JohnRanger** [comment]
yep see this here also - with Chrome at least.

@volkanceylan : I see this additional dot also in a brand new Serene test project.

In your demo project on serenity.is this is not there.

With kind regards,

John

**Comment by dfaruque** [comment]
increasing the width of the checkbox columns might be solved this issue.
