### ISSUE TITLE
How can I make a serenity style guide?

### ISSUE THREAD

**Issue by MimmoDany** [volkanceylan/Serenity#4607]
I would like to make a Serenity style guide for my programs. 
similar to: https://serenity.is/docs/
Where can I start from? Is there a template?

Thank you

**Comment by JohnRanger** [comment]
Hi @MimmoDany ,

the Serenity guide is a gitbook. Please have a look at this guide here how to create one for yourself: https://medium.com/@rebeccapeltz/publish-your-book-online-with-gitbook-fc0ce9b7f12

With kind regards,

John
