### ISSUE TITLE
PDF report shows random characters when using <strong> or <th>

### ISSUE THREAD

**Issue by qprotex** [volkanceylan/Serenity#4608]
Hello

I am using the OrderDetailReport.cshtml sample from Northwind to create an invoice on my application but for some reason the fields that uses <strong> or <th> does not appear properly. I am missing something?

![image](https://user-images.githubusercontent.com/13024779/64830141-15924500-d59d-11e9-9222-ec93ad82fb59.png)

**Comment by rcruzfalcon** [comment]
Hi @qprotex , in print view is wrong too?
Try to upgrade the wkhtmltopdf.exe to the last version.
best regards.

**Comment by qprotex** [comment]
> Hi @qprotex , in print view is wrong too?
> Try to upgrade the wkhtmltopdf.exe to the last version.
> best regards.

Hello @rcruzfalcon I have tried new version but still the same issue. Found the reason: My web application was adding the attached CSS in the HTML. It seems this font is not compatible with wkhtmltopdf.

[font-open-sans-base64.zip](https://github.com/volkanceylan/Serenity/files/3611668/font-open-sans-base64.zip)
