### ISSUE TITLE
replace with Today if column is now 

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4609]
I am success for changing background color, but not working for replace column , Could you help me again and again? it's my code below:  
 
` protected getItemCssClass(item: Default.MLeadRow, index: number): string {` 
`             let klass: string = ""; ` 
` if (item.LastActivityDate != null)` 
`                 klass += " yellow-zone ";  ` 
`             return Q.trimToNull(klass);` 
` }
`

**Comment by JohnRanger** [comment]
Hi @resitaufan ,

it works somehow like this:

In your xyzGrid.ts, add the following:

```ts
	protected getColumns(): Slick.Column[] {
            let columns = super.getColumns();
            let fld = ForWorkstationsRow.Fields;			// *** Replace "ForWorkstationsRow" with your row name ***
            
            let DefaultPrinter_PrintqueueIDShareNameColumn = Q.first(columns, x => x.field == fld.DefaultPrinter_PrintqueueIDShareName);	  // *** Replace "DefaultPrinter_PrintqueueIDShareName" with the name of your column/field which should show "today" ***
            DefaultPrinter_PrintqueueIDShareNameColumn.format = ctx => {

                if (ctx.value == <now>)					// *** Replace "ctx.value == <now>" with the correct javascript formula to compare the current row's timestamp in the field with "now" so that the formula returns "true" for values which are from "today" 
                {
                    ctx.value = "today";		// *** Returns the word "today" instead of the timestamp stored in the database ***
		    return ctx.value;
                }
                else
                {
                    return ctx.value;			// *** Returns the timestamp stored within the Database
                }
                
            };

            return columns;
        }
```

Important: You have to work out the exact formula in the line 
```ts
if (ctx.value == <now>)
```

yourself (didn't had the time to work this out myself).

Hope this helps.

With kind regards,

John

**Comment by resitaufan** [comment]
`let DefaultPrinter_PrintqueueIDShareNameColumn = Q.first(columns, x => x.field == fld.LastActivityDate);	  // *** Replace "DefaultPrinter_PrintqueueIDShareName" with the name of your column/field which should show "today" ***
            DefaultPrinter_PrintqueueIDShareNameColumn.format = ctx => {
                var todayDate = new Date();
                if (ctx.value == todayDate)	
                {
                    ctx.value = "today";		
                    return ctx.value;
                }
                else {
                    return ctx.value;		
                }
            };
                  return columns;`
your code  is not working for me ,@JohnRanger..

**Comment by JohnRanger** [comment]
Hi @resitaufan ,
The above code is just out of one of my projects. It works for my application.

What exactly does not work?

Do you get an error?

Do the rows which are "today" do not show the word "today"? --> If this is the case then debug the content of ctx.value and the content of todayDate and see if they match. If not, make them match.

With kind regards,

John

**Comment by resitaufan** [comment]
it's work now
