### ISSUE TITLE
Two levels memory grids.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#461]
I need to implement two level memory grid as shown in below screen shot - 
https://drive.google.com/file/d/0B9UGZZFXh-e6R1o4dWVWdnRFcUU/view

How can i do that? I have to use memory grids at both places...
Please guide as i am confused how to start looking to get it implement.

**Comment by volkanceylan** [comment]
Did you read topic u wrote in VS gallery?

**Comment by ramveersgh** [comment]
Yes... an try to implement following as per your comment there -
_"Hmm, that behavior is not designed for nested relations. Problem is order details are loaded with a List service call, which can't load task details with a simple query. You need to write a List behavior for OrderDetails, which intercepts OnReturn method, gets a list of Task IDs from handler.Response.Entities and loads them from DB using a connection.List<TaskRow>(q => q.Where(TaskRow.Fields.Id.In(...)). Then sets them in entities by their detail ID. Rather complex."_

But could not get it and getting confuse to start... Request to help little more so that i can troubleshoot to implement it.

**Comment by volkanceylan** [comment]
As i wrote there it's an advanced topic, so if you can't understand with these explanations and looking at source, better don't try.
