### ISSUE TITLE
Lefletjs sample for custom template dialog

### ISSUE THREAD

**Issue by infiycloud** [volkanceylan/Serenity#4611]
Can someone help how to use leafletjs with this platform, I have to show map in custom template dialog to pickup latlong and return selected latlong from child dialog to Editor

Is there any way how I can use L.Map in MyDialog.ts file to init map?

Thanks for your time.

**Comment by JohnRanger** [comment]
Hi @infiycloud ,

for the embedding of your custom map javascript library you can have a look at this official serenity demo: https://serenity.is/demo/BasicSamples/ChartInDialog#.

In your xyzDialog.ts you can add two public fields before the constructor - like this:

```ts
public latitude: number = 0;
public longitude: number = 0;
```

Now create your leaflet object and attach an event handler to it (see documentation of leadlet.js at https://leafletjs.com/examples/quick-start/):

```ts
var myThis = this;
function onMapClick(e) {
		myThis.latitude =e.latlng[0];
		myThis.longiitude =e.latlng[1];
}
```

**Comment by MaziarSangi** [comment]
@JohnRanger 
I've tested it by Open Street Map and it worked well.

**Comment by JohnRanger** [comment]
Hi @infiycloud ,

this would make up a nice wiki entry. Would you mind to share your working implementation so others could benefit from it? :-)

Wiki is here: https://github.com/volkanceylan/Serenity/wiki

With kind regards,

John

**Comment by MaziarSangi** [comment]
@JohnRanger 
For leaflet.js , I used MapBox access-token to download tiles of maps.
Anyone can Sign Up in MapBox and take his/her own access-token to render MapBox tiles.
