### ISSUE TITLE
Hide fields on drop-down change

### ISSUE THREAD

**Issue by dhanrajKumbhar** [volkanceylan/Serenity#4613]
I am trobling to hide fields on  drop-down change with the condition

I tried with code
 this.form.OptionsCategoryId.changeSelect2(e => {
                var id = this.form.OptionsCategoryId.value
                if (id == 1) {
                    // hide some fields 
                }
                else {
                    //hide some field
                }

            });
            

but it gives error like:
1.  Message: Uncaught Element has no widget of type 'Serenity.IntegerEditor'! If you have recently changed editor type of a property in a form class, or changed data type in row (which also changes editor type) your script side Form definition might be out of date. Make sure your project builds successfully and transform T4 templates

2  Element has no widget of type 'Serenity.IntegerEditor'! If you have recently changed editor type of a property in a form class, or changed data type in row (which also changes editor type) your script side Form definition might be out of date. Make sure your project builds successfully and transform T4 templates

Please help me 
I'm new for serenity
thanks in advance
![ErrorOnSelectionChanges](https://user-images.githubusercontent.com/55383898/64947096-e841e180-d891-11e9-9b47-e35cea8bf6f8.jpg)

**Comment by dhanrajKumbhar** [comment]
@volkanceylan Please help me

**Comment by edwardch** [comment]
Try using ` var id = Q.toId(this.form.OptionsCategoryId.value);`

For debugging you can also try use ``console.log(`${someVariable}`);`` to see what your variable values are.

**Comment by dhanrajKumbhar** [comment]
@edwardch 
Thanks for replay
but it gives the same above error(see above error)
When I click on the Add / Edit button at that time it comes
I think it unable to generate serenity code.

**Comment by edwardch** [comment]
Did you transform T4 templates?

**Comment by dhanrajKumbhar** [comment]
@edwardch 
No, I don't do anything,
but when I build solution then Output window's show

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>   at System.Diagnostics.Process.Start()
1>   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
1>   at Serenity.CodeGenerator.TSTypeLister.List()
1>   at Serenity.CodeGenerator.Program.<>c__DisplayClass0_1.<Main>b__1()
1>   at Serenity.CodeGenerator.Program.Main(String[] args)
1>C:\Dhanraj\Projects\IEPGlobalContacts\IEPGlobalContacts\IEPGlobalContacts.Web\IEPGlobalContacts.Web.csproj(95,5): warning MSB3073: The command "dotnet sergen mvct" exited with code -532462766.
1>IEPGlobalContacts.Web -> C:\Dhanraj\Projects\IEPGlobalContacts\IEPGlobalContacts\IEPGlobalContacts.Web\bin\Debug\netcoreapp2.2\IEPGlobalContacts.Web.dll
1>IEPGlobalContacts.Web -> C:\Dhanraj\Projects\IEPGlobalContacts\IEPGlobalContacts\IEPGlobalContacts.Web\bin\Debug\netcoreapp2.2\IEPGlobalContacts.Web.Views.dll
1>
1>Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>   at System.Diagnostics.Process.Start()
1>   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
1>   at Serenity.CodeGenerator.TSTypeLister.List()
1>   at Serenity.CodeGenerator.Program.<>c__DisplayClass0_1.<Main>b__1()
1>   at Serenity.CodeGenerator.Program.Main(String[] args)
1>C:\Dhanraj\Projects\IEPGlobalContacts\IEPGlobalContacts\IEPGlobalContacts.Web\IEPGlobalContacts.Web.csproj(102,5): warning MSB3073: The command "dotnet sergen servertypings" exited with code -532462766.
1>Done building project "IEPGlobalContacts.Web.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by dhanrajKumbhar** [comment]
@volkanceylan @edwardch  Please help me for how to transfer t4 template

**Comment by edwardch** [comment]
If you're using .NET Core they should run for you, but if not you can go to your menu: Build > Transform All T4 Templates

Read your error message carefully and make sure your lookup script keys are right.

**Comment by dhanrajKumbhar** [comment]
@edwardch I'm using .NET Core 2.2

**Comment by dhanrajKumbhar** [comment]
@edwardch @volkanceylan After the building project  I'm not able to transfer T4 template 
I'm using .Net core 2.2 

It gives a warning like - The command "dotnet sergen servertypings" exited with code -532462766.

**Comment by dhanrajKumbhar** [comment]
Please help me 
I'm new for serenity 
Thanks in advance

**Comment by dhanrajKumbhar** [comment]
I had solved this issue 
I missed some npm installation

**Comment by mrajalko** [comment]
> I had solved this issue
> I missed some npm installation

please guide me on missing npm installations, I am also facing same issue.
