### ISSUE TITLE
Filter Dropdown based on a RadioButton

### ISSUE THREAD

**Issue by leovamos** [volkanceylan/Serenity#4616]
Hi, guys

I need to show the apps according to the selected OS: Android or IOS.
The OS is chosen by a Radio Button, and after that it would need to filter the dropdown with the respective OS apps. I know this can be done by typescript, which is where I'm trying, but to no avail so far.
The main question, besides how to make this filter, is how it would retrieve the information, relating app and OS, since they are in a SQL table.
Any suggestions are welcome. Thanks.

**Comment by JohnRanger** [comment]
Hi @leovamos ,

can you show a screenshot / mockup what you are trying to achieve so we can better understand?

Is the dropdown within a Serenity form (an official form field) which has a lookup editor on it?

Tell us more...

With kind regards,

John

**Comment by leovamos** [comment]
Hi @JohnRanger 
Thanks for answer

Here is my Dialog for the problem. The code is just an attempt I had but it doesn't really works. I get it from another site just to try.
`@Serenity.Decorators.registerClass()


    export class AppTrustDialog extends Serenity.EntityDialog<AppTrustRow, any> {

        protected getFormKey() { return AppTrustForm.formKey; }
        protected getIdProperty() { return AppTrustRow.idProperty; }
        protected getLocalTextPrefix() { return AppTrustRow.localTextPrefix; }
        protected getService() { return AppTrustService.baseUrl; }

 `       protected form = new AppTrustForm(this.idPrefix);

        protected getToolbarButtons(): Serenity.ToolButton[] {
            $("#Serenity_RadioButtonEditor10_10").change(function () {
                var filterValue = $(this).val();
                var row = $('.row');

                row.hide()
                row.each(function (i, el) {
                    if ($(el).attr('data-type') == filterValue) {
                        $(el).show();
                    }
                })


            });*/
            

            var buttons = super.getToolbarButtons();
            return buttons;
            //Serenity_RadioButtonEditor10_10
            //Serenity_RadioButtonEditor10_11
            //s2id_DashboardSMICv2_Smic_AppTrustDialog7_AppId1 
            //s2id_DashboardSMICv2_Smic_AppTrustDialog7_AppId2
        }
    }

The last four lines are the IDs of the components Radio Button and the Dropdowns in HTML. I want to get the value of the radio button, and based on it, change the shown values in both dropdowns.
The two Radio Buttons have values like 10 and 11, each one representing an OS (Android for 10, iOS for 11), and after clicking on one of them, the list of values in both dropdowns are changed according to the OS you choose, showing apps from that OS.

The main problem, like I said, as well as how to assemble the JQuery code, is how to search for data in SQL Server by JQuery, for me it seems kind of impossible. I can even imagine the query: "SELECT * FROM Apps WHERE Platform=x", where x is the value of the chosen platform and 'Apps' would be the table which contains all the apps. 

Sorry if there's some error, thanks in advance

Leonardo

**Comment by JohnRanger** [comment]
Hi @leovamos ,

ah - if the main problem here is how to fetch data on the client-side (the whole xyzDialog.ts is client-side) over from the server side (SQL and xyzEndpoint.cs) - then look at this wiki: https://github.com/volkanceylan/Serenity/wiki/BBB:-On-client-side,-fetching-a-value-from-server-side-out-of-database 

Here I explain how to fetch data from server-side to client-side.

But I would be very interested in your RadioButtonEditor code :-) As this is really an interesting feature.

Hope, above helps a bit.

Otherwise, let me know :-)

With kind regards,

John

**Comment by JohnRanger** [comment]
@leovamos ,

I am unfortunately not good in converting code within my mind into a visualization.

Please use MS paint or so to quickly draw a mockup on what you want to achieve - with comments beside the form fields (what should happen when in the fields a selection is made).

If I understand correct, you want to fill the 2nd dropdown field based on a choice in 1st dropdown, correct?

For this the best way is to fill the 1st form field via a lookup editor (your OS choice).

Assign the EmptyLookupEditor (from dfaruque's Serenity.Extra - a repository here on Github) so that the 2nd dropdown stays empty.

Aand then in the onChange-Event of the 1st dropdown do a query via xyzService on the client side (by passing the just selected value form the 1st dropdown) to the server side (via a custom written endpoint (an additional entry in the xyzEndpoint.cs within the entity which will deliver the desired data for the 2nd dropdown) and the matching sql query in xyzRepository.ts.

The Query should only deliver a list of ids with the corresponding texts. This list is returned to the xyzEndpoint and from there over to the client-side.

And then do a foreach on the returned data and add the items to the 2nd dropdown (a jquery select2 widget).

Hope this gives you an overview on what to do.

With kind regards,

John

**Comment by leovamos** [comment]
Hi @JohnRanger, here is basically a screenshot of my page with the problem:

![smic_help_jquery](https://user-images.githubusercontent.com/38430921/65445841-7cb7c100-de09-11e9-9c3d-4939eb962fd8.png)

**Comment by leovamos** [comment]
Hey @JohnRanger, I just read the wiki you recommended (https://github.com/volkanceylan/Serenity/wiki/BBB:-On-client-side,-fetching-a-value-from-server-side-out-of-database), and apparently it works, but I may have done something wrong or not adapted to what I wanted. All the entries in my table don't appear in the grid anymore. Here are all my codes:

Just explaining - this row I've sent the screenshot is in a row named AppTrustRow. The Apps are in another table (row) named AppRow. What I did was:

1 - Create the Endpoint in AppTrustEndpoint.cs (sorry, I don't know how to fix the problem in showing all usings like the second half of the code):

` 
namespace DashboardSMICv2.Smic.Endpoints
{
    using DashboardSMICv2.Modules.Common.Helpers;
    using DashboardSMICv2.Smic.Entities;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using System;
    using System.Data;
    using System.Web.Mvc;
    using MyRepository = Repositories.AppTrustRepository;
    using MyRow = Entities.AppTrustRow;

    [RoutePrefix("Services/Smic/AppTrust"), Route("{action}")]
    [ConnectionKey(typeof(MyRow)), ServiceAuthorize(typeof(MyRow))]
    public class AppTrustController : Controller
    {   
        [HttpPost]
        public ActionResult GetApps(string platform)
        {
            String output = ManageApps.GetApps(platform);
            return Json(new { result = output }, JsonRequestBehavior.AllowGet);
        }
`

2 - Create a ManageApps in Common/Helpers:

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Serenity.Data;
using System.Data;

using appRow = DashboardSMICv2.Smic.Entities.AppRow;

namespace DashboardSMICv2.Modules.Common.Helpers
{
    public class ManageApps
    {
        public static string GetApps(string platform)
        {
            var connection = SqlConnections.NewFor<appRow>();

            var row = new appRow();
            if(new SqlQuery().From(row)
                .Select(appRow.Fields.UniqueName)
                .Where(appRow.Fields.Platform == platform)
                .GetSingle(connection))
            {
                return row.UniqueName;
            }

            return null;
        }
    }
}
`

3 - Create an AppHelper.ts also in Common/Helpers:
`
namespace DashboardSMICv2.AppHelper {
    export function GetAppName(Platform: string){
        let myResult = "";
        let serviceEndpoint = "/services/" + DashboardSMICv2.Smic.AppTrustService.baseUrl + "/GetApps";

        $.ajax({
            type: "post",
            dataType: "json",
            async: false,
            url: serviceEndpoint,
            data: { 'Platform': Platform },
            success: function (response) {
                if (response instanceof Object) {
                    var json = response;
                }
                else {
                    var json = $.parseJSON(response);
                }

                var output = json['result'];
                myResult = output;
            }.bind(this),
            error: function (jqxhr, textStatus, error) {
                var err = textStatus + ", " + error;
                alert("Erro! " + err);
            }
        });

        return myResult;
    }
}
`

4 - Call the Helper function in AppTrustDialog.ts:
`
namespace DashboardSMICv2.Smic {

    @Serenity.Decorators.registerClass()
    export class AppTrustDialog extends Serenity.EntityDialog<AppTrustRow, any> {
        protected getFormKey() { return AppTrustForm.formKey; }
        protected getIdProperty() { return AppTrustRow.idProperty; }
        protected getLocalTextPrefix() { return AppTrustRow.localTextPrefix; }
        protected getService() { return AppTrustService.baseUrl; }

        protected form = new AppTrustForm(this.idPrefix);

        protected getToolbarButtons(): Serenity.ToolButton[] {

            var buttons = super.getToolbarButtons();

            buttons.push(
                {
                    title: "Busca App",
                    cssClass: 'buscaApp-button',
                    onClick: () => {
                        let platform = "Android";
                        let myAppName = AppHelper.GetAppName(platform);

                        Q.notifySuccess(platform + " puxou o(s) app(s): " + myAppName);
                    }
                });
            return buttons;
}
`

And what it does is:
![smic_help_trust](https://user-images.githubusercontent.com/38430921/65451060-d07bd780-de14-11e9-817c-776e9896abfd.png) 

All the entries are gone

And in the dialog:
![smic_help_trust_dialog](https://user-images.githubusercontent.com/38430921/65451158-fb662b80-de14-11e9-84e8-a117af33f0b2.png)

Now it shows all the apps, but no filtering is made. Ok, the code really doesn't filter anything, so this is obvious to happen.

What I think may have happened is that I must have confused the places where to insert the ManageApps or Endpoint codes, and maybe the value type of the Platform variable is wrong, after all the value in the table is 10 or 11 (integer, not string) as well in HTML, which is where I imagine it fetches the value of each OS.

But it is something, indeed. I hope to count on your help, it has been of great value.

**Comment by luongnv6** [comment]
create lookup: AppLookup.cs
```
[LookupScript("Default.AppLookup")]
    public class AppLookup: RowLookupScript<DashboardSMICv2.Smic.Entities.AppRow>
    {
        public AppLookup()
        {
            IdField = DashboardSMICv2.Smic.Entities.AppRow.Fields.Id.PropertyName;
            TextField = DashboardSMICv2.Smic.Entities.AppRow.Fields.Name.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = DashboardSMICv2.Smic.Entities.AppRow.Fields;

            query.Select(fld.Id)
                .Select(fld.Name)
                .Select(fld.Platform)
                .Where(fld.Archive == 0);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }

in AppTrustDialog.ts

            this.form.OriginId.change((e) => {
                this.form.RailcarTypeId.cascadeField = "Platform";
                this.form.RailcarTypeId.cascadeValue = this.form.OriginId.value;
            })
``

**Comment by leovamos** [comment]
Hi @luongnv6 
Thanks for the suggestion, but I don't quite understand what this code does. If you can explain the idea to me, I'm grateful.
And we have two problems here: there is no fld.Archive field in AppLookup ... I don't know where that comes from by the way. The other problem is that the form in AppTrustDialog doesn't have RailcarTypeId, which I don't know where it comes from either. If you can better explain these things and work out how to solve them, that's great. I will test the code as soon as there is a way to fix these problems.

**Comment by JohnRanger** [comment]
Hi @leovamos ,

the problem why all your grid rows are gone is because you have changed the original xyzEndpoint.cs controller type from what it was to "controller".

This does not work :-)

In my example oyu have to create an own - independent - controller (e.g. create it with sergen) and _then_ change the class of that new controller (while leaving the original one in peace).

But I will try to make up an end to end example how to fill an empty dropdown with a list of values from the server side.

Give me some time...

John

**Comment by leovamos** [comment]
Oh, I understand now. Thanks for explaining.

Ok, @JohnRanger, I'll be waiting for your example, and meanwhile, I'll try to understand how to solve this problem. Thanks again!

**Comment by JohnRanger** [comment]
Use the EmptyLookupEditor from @dfaruque 's Serenity.Extra

Decorate the two appsId fields in your xyzRow.cs with it. [EmptyLookupEditor]

-----------------------------

Create a new file called Select2DataItem.cs
```cs
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DashboardSMICv2.Modules.Common.Helpers
{
    public class Select2DataItem
    {
        public int id { get; set; }
        public string text { get; set; }
    }
}
```

--------------------

Create a new Endpoint file called DataProvider.cs with the following content:
```cs
using System;
using DashboardSMICv2.Modules.Common.Helpers;
using System.Web.Mvc;
using System.Linq;
using Serenity.Data;
using System.Data;
using System.Collections.Generic;
using Newtonsoft.Json;

using appRow = DashboardSMICv2.Smic.Entities.AppRow;

namespace DashboardSMICv2.Common.Endpoints
{
    [RoutePrefix("Services/Common/DataProvider"), Route("{action}")]
    public class DataProviderController : Controller
    {
        [HttpPost]
        public ActionResult AppsForPlatform(int FilterId)
        {
            var connection = SqlConnections.NewFor<appRow>();
            var query = "select id, name from approw where platformId = " + FilterId;
            var Result = connection.Query(query);
            connection.Close();            

            List<Select2DataItem> DataItems = new List<Select2DataItem>();
            foreach (var Resultrow in Result)
            {
                var data = (IDictionary<string, object>)Resultrow;
                var currentItem = new Select2DataItem();
                currentItem.id = (int)data[approw .Fields.id.Name];
                currentItem.text = (string)data[approw.Fields.Name.Name];
            }
            
            // *** Re-sort items ***
            DataItems = DataItems.OrderBy(o => o.text).ToList();

            var output = JsonConvert.SerializeObject(DataItems);
            return Json(output, JsonRequestBehavior.AllowGet);      
        }
    }
}   
``` 
---------------------

Create a new file called JSONDataFetcher.ts and put the following inside:
```ts
namespace DashboardSMICv2.JSONDatafetcher {
// *** Fetches JSON Data from Server side ***
    export function GetItemsAsJSON(ServiceEndpointURL: string, FilterId: String) {

        let myresult = "";

        FilterId = (FilterId == "" ? "0" : FilterId);

        // *** Debug only ***
        //alert(ServiceEndpointURL);
        //alert(FilterId);
        
        $.ajax({
            type: "post",
            dataType: "json",
            async: false,
            url: ServiceEndpointURL,
            data: {
                'FilterId': FilterId
            }
            ,
            success: function (response) {

                if (response instanceof Object) {
                    var json = response;
                }
                else {
                    var json = JSON.parse(response);
                }

                var output = json;
                myresult = output;


            }.bind(this),
            error: function (jqxhr, textStatus, error) {
                var err = textStatus + ", " + error;
                alert("Error! " + err);
            }

        });

        return myresult;
    }
}
```

-----------------------

In the change event of your RadioButton field (I call it here PlatformId), insert the following:

```ts
                let ServiceEndpoint = "/services/Common/DataProvider/AppsForPlatform";
                var data = JSONDatafetcher.GetItemsAsJSON(ServiceEndpoint, this.form.PlatformId.value;
                this.form.AppId1.select2({data: data});
                this.form.AppId1.select2({data: data});
```

That should do it. I use this system in my apps to dynamically fill the dropdowns of fields directly from the database. Never having any caching problems - no matter how the data gets into the DB - and fully offloading the whole work to DB and Web server. That's for what they are made, no? :-)

Hope, this helps.

With kind regards,

John

**Comment by JohnRanger** [comment]
@leovamos ,

in your screenshot - the Radiobutton line - how did you implement this? As a true Serenity editor or just DOM manipulation?

If it is a true radiobutoneditor, would you mind to share your code for this here?

With kind regards,

John

**Comment by luongnv6** [comment]
sorry @leovamos

The above code will cascade the data on App 1 according to the Platform (Android, ISO).
You just need to create a lookupeditor to get all the data for the App1 lookup (including the Platform field).
When you change the radio, you will set the cascade value for the App1 lookup to filter data.

same for App2 lookup
 
create lookup: AppLookup.cs
```
namespace DashboardSMICv2.Smic.CustomLookup
{
[LookupScript("Default.AppLookup")]
    public class AppLookup: RowLookupScript<DashboardSMICv2.Smic.Entities.AppRow>
    {
        public AppLookup()
        {
            IdField = DashboardSMICv2.Smic.Entities.AppRow.Fields.Id.PropertyName;
            TextField = DashboardSMICv2.Smic.Entities.AppRow.Fields.Name.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = DashboardSMICv2.Smic.Entities.AppRow.Fields;

            query.Select(fld.Id)
                .Select(fld.Name)
                .Select(fld.PlatformId);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}

in AppTrustForm.cs
public class AppTrustForm
    {
//.....
        [RadioButtonEditor]
        public Int32 PlatformId { get; set; }
        [LookupEditor(typeof(DashboardSMICv2.Smic.CustomLookup.AppLookup))]
        public Int32 App1Id { get; set; }
        [LookupEditor(typeof(DashboardSMICv2.Smic.CustomLookup.AppLookup))]
        public Int32 App2Id { get; set; }
       //......
    }

in AppTrustDialog.ts

            this.form.PlatformId.change((e) => {
                this.form.App1Id.cascadeField = "PlatformId";
                this.form.App1Id.cascadeValue = this.form.PlatformId.value;
                this.form.App2Id.cascadeField = "PlatformId";
                this.form.App2Id.cascadeValue = this.form.PlatformId.value;
            })
``

You should correct the field names to match your table structure, the above fields are based on my conjecture only

good luck

**Comment by JohnRanger** [comment]
@leovamos ,

the solution of @luongnv6 looks for me the much more elegant solution than mine. So I recommend the solution of @luongnv6 .

With kind regards,

John

**Comment by leovamos** [comment]
Well, guys, I tried the @luongnv6's solution, and here are the results:

First, the codes:
(I really wanna know how to fix this problem with some parts of the code doesn't showing like it should)

AppLookup.cs
`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Serenity.ComponentModel;
using Serenity.Data;
using Serenity.Web;
    
namespace DashboardSMICv2.Smic.CustomLookup
{
    [LookupScript("Smic.AppLookup")]
    public class AppLookup: RowLookupScript<Smic.Entities.AppRow>
    {
        public AppLookup()
        {
            IdField = Smic.Entities.AppRow.Fields.AppId.PropertyName;
            TextField = Smic.Entities.AppRow.Fields.UniqueName.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Smic.Entities.AppRow.Fields;

            query.Select(fld.AppId)
                .Select(fld.UniqueName)
                .Select(fld.Platform);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}
`

AppTrustForm.cs

`
namespace DashboardSMICv2.Smic.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;


    [FormScript("Smic.AppTrust")]
    [BasedOnRow(typeof(Entities.AppTrustRow), CheckNames = true)]
    public class AppTrustForm
    {
        [RadioButtonEditor(typeof(PlatformEnum))]
        public PlatformEnum Platform { get; set; }
        [LookupEditor(typeof(CustomLookup.AppLookup))]
        public Int32 AppId1 { get; set; }
        [LookupEditor(typeof(CustomLookup.AppLookup))]
        public Int32 AppId2 { get; set; }
        [RadioButtonEditor(typeof(AppTrustStatus))]
        public AppTrustStatus Status { get; set; }
    }
}
`

And AppTrustDialog.ts

`

namespace DashboardSMICv2.Smic {

    @Serenity.Decorators.registerClass()
    export class AppTrustDialog extends Serenity.EntityDialog<AppTrustRow, any> {
        protected getFormKey() { return AppTrustForm.formKey; }
        protected getIdProperty() { return AppTrustRow.idProperty; }
        protected getLocalTextPrefix() { return AppTrustRow.localTextPrefix; }
        protected getService() { return AppTrustService.baseUrl; }

        protected form = new AppTrustForm(this.idPrefix);

        protected getToolbarButtons(): Serenity.ToolButton[] {

            var buttons = super.getToolbarButtons();

            this.form.Platform.change((e) => {
                this.form.AppId1.cascadeField = "Platform";
                this.form.AppId1.cascadeValue = this.form.Platform.value;
                this.form.AppId2.cascadeField = "Platform";
                this.form.AppId2.cascadeValue = this.form.Platform.value;
            });

            return buttons;
      }
    }
   }
`

And it shows this:

![smic_help_trust_error](https://user-images.githubusercontent.com/38430921/65802769-04c40080-e153-11e9-9ee3-116bb8422b2a.png)


In the console:
`
Uncaught TypeError: Cannot read property 'Platform' of undefined
    at AppTrustDialog.getToolbarButtons (AppTrustDialog.ts:17)
    at AppTrustDialog.TemplatedDialog.initToolbar (TemplatedDialog.ts:158)
    at AppTrustDialog.EntityDialog.initToolbar (EntityDialog.ts:868)
    at AppTrustDialog.TemplatedDialog [as constructor] (TemplatedDialog.ts:25)
    at new EntityDialog (EntityDialog.ts:33)
    at new AppTrustDialog (AppTrustDialog.ts:4)
    at Function.Widget.create (Widget.ts:133)
    at AppTrustGrid.EntityGrid.createEntityDialog (EntityGrid.ts:273)
    at AppTrustGrid.EntityGrid.editItem (EntityGrid.ts:172)
    at AppTrustGrid.EntityGrid.addButtonClick (EntityGrid.ts:168)
`

I ain't so sure about that, but my guess is that about the fact Platform is a PlatformEnum type, this may conflict with the rest of the code. But it's just a guess.

Well, hope you can help. Thanks.

**Comment by leovamos** [comment]
Oh, by the way, I tried something I used in another code, and apparently it works, but I don't know how to proceed after that:


$(document).ready(function () {
               $("input[name = 'Serenity_RadioButtonEditor10']").click(function () {
                    var radioValue = $("input[name='Serenity_RadioButtonEditor10']:checked").val();
               });
         });

This only gets the value in the radio button, and the next step should be use this value in a query to retrieve the apps which match the condition 'Platform = radioValue', but I don't know how to do that.

**Comment by luongnv6** [comment]
In row.cs
```
public class AppTrustRow{
        [DisplayName("Platform "), NotNull, QuickFilter]
        public PlatformEnum? Platform 
        {
            get { return (PlatformEnum?)Fields.Platform [this]; }
            set { Fields.Platform [this] = (Int16?)value; }
        }
        [DisplayName("Archive"), NotNull]
        [LookupEditor(typeof(CustomLookup.AppLookup))]
        public Int32? AppId1
        {
            get { return Fields.AppId1[this]; }
            set { Fields.AppId1[this] = value; }
        }

        [DisplayName("Archive"), NotNull]
       [LookupEditor(typeof(CustomLookup.AppLookup))]
        public Int32? AppId2
        {
            get { return Fields.AppId2[this]; }
            set { Fields.AppId2[this] = value; }
        }

        [DisplayName("Status"), NotNull, QuickFilter]
        public AppTrustStatus ? Status
        {
            get { return (AppTrustStatus ?)Fields.Status[this]; }
            set { Fields.Status[this] = (Int16?)value; }
        }
         ...

       public class RowFields : RowFieldsBase
        {
....
            public Int16Field TypeCode;
            public Int32Field AppId1;
            public Int32Field AppId2;
            public Int16Field Status;
....
         }
}
``
In form.cs```
[FormScript("Smic.AppTrust")]
[BasedOnRow(typeof(Entities.AppTrustRow), CheckNames = true)]
public class AppTrustForm
{
    [RadioButtonEditor]
    public Int16 Platform { get; set; }
    public Int32 AppId1 { get; set; }
    public Int32 AppId2 { get; set; }
    [RadioButtonEditor]
    public Int16 Status { get; set; }
}

please T4 after rebuild

thanks

**Comment by JohnRanger** [comment]
@leovamos ,

I don't have time to reverse-engineer @luongnv6 's proposal - but if you follow mine this would work. Look in the section "In the change event of your RadioButton field..." There I call the server-side webservice with giving over the ID of the chosen OS.

With kind regards,

John

**Comment by leovamos** [comment]
Well, guys, I tried the @luongnv6's solution, and here are the results:

First, the codes:
(I really wanna know how to fix this problem with some parts of the code doesn't showing like it should)

AppLookup.cs
`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Serenity.ComponentModel;
using Serenity.Data;
using Serenity.Web;
    
namespace DashboardSMICv2.Smic.CustomLookup
{
    [LookupScript("Smic.AppLookup")]
    public class AppLookup: RowLookupScript<Smic.Entities.AppRow>
    {
        public AppLookup()
        {
            IdField = Smic.Entities.AppRow.Fields.AppId.PropertyName;
            TextField = Smic.Entities.AppRow.Fields.UniqueName.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Smic.Entities.AppRow.Fields;

            query.Select(fld.AppId)
                .Select(fld.UniqueName)
                .Select(fld.Platform);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}
`

AppTrustForm.cs

`
namespace DashboardSMICv2.Smic.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;


    [FormScript("Smic.AppTrust")]
    [BasedOnRow(typeof(Entities.AppTrustRow), CheckNames = true)]
    public class AppTrustForm
    {
        [RadioButtonEditor(typeof(PlatformEnum))]
        public PlatformEnum Platform { get; set; }
        [LookupEditor(typeof(CustomLookup.AppLookup))]
        public Int32 AppId1 { get; set; }
        [LookupEditor(typeof(CustomLookup.AppLookup))]
        public Int32 AppId2 { get; set; }
        [RadioButtonEditor(typeof(AppTrustStatus))]
        public AppTrustStatus Status { get; set; }
    }
}
`

And AppTrustDialog.ts

`

namespace DashboardSMICv2.Smic {

    @Serenity.Decorators.registerClass()
    export class AppTrustDialog extends Serenity.EntityDialog<AppTrustRow, any> {
        protected getFormKey() { return AppTrustForm.formKey; }
        protected getIdProperty() { return AppTrustRow.idProperty; }
        protected getLocalTextPrefix() { return AppTrustRow.localTextPrefix; }
        protected getService() { return AppTrustService.baseUrl; }

        protected form = new AppTrustForm(this.idPrefix);

        protected getToolbarButtons(): Serenity.ToolButton[] {

            var buttons = super.getToolbarButtons();

            this.form.Platform.change((e) => {
                this.form.AppId1.cascadeField = "Platform";
                this.form.AppId1.cascadeValue = this.form.Platform.value;
                this.form.AppId2.cascadeField = "Platform";
                this.form.AppId2.cascadeValue = this.form.Platform.value;
            });

            return buttons;
      }
    }
   }
`

And it shows this:

![smic_help_trust_error](https://user-images.githubusercontent.com/38430921/65802769-04c40080-e153-11e9-9ee3-116bb8422b2a.png)


In the console:

Uncaught TypeError: Cannot read property 'Platform' of undefined
    at AppTrustDialog.getToolbarButtons (AppTrustDialog.ts:17)
    at AppTrustDialog.TemplatedDialog.initToolbar (TemplatedDialog.ts:158)
    at AppTrustDialog.EntityDialog.initToolbar (EntityDialog.ts:868)
    at AppTrustDialog.TemplatedDialog [as constructor] (TemplatedDialog.ts:25)
    at new EntityDialog (EntityDialog.ts:33)
    at new AppTrustDialog (AppTrustDialog.ts:4)
    at Function.Widget.create (Widget.ts:133)
    at AppTrustGrid.EntityGrid.createEntityDialog (EntityGrid.ts:273)
    at AppTrustGrid.EntityGrid.editItem (EntityGrid.ts:172)
    at AppTrustGrid.EntityGrid.addButtonClick (EntityGrid.ts:168)

**Comment by leovamos** [comment]
Well, I tried again, with @luongnv6's help, and...

![smic_help_trust_error2](https://user-images.githubusercontent.com/38430921/65914478-d3903e00-e3a7-11e9-956a-c99337352d09.png)

The line where the error comes up is:

![smic_help_trust_error_code](https://user-images.githubusercontent.com/38430921/65914549-f7538400-e3a7-11e9-8595-f1ca33da351a.png)

It can't find this Platform field in form.
![smic_help_trust_error_code2](https://user-images.githubusercontent.com/38430921/65914619-1a7e3380-e3a8-11e9-9aa5-491c0aabd800.png)

With this, it can't even open the form to create a new App Trust, it just shows that error and that's it.

**Comment by leovamos** [comment]
Here is AppTrustDialog.ts:

`namespace DashboardSMICv2.Smic {

    @Serenity.Decorators.registerClass()
    export class AppTrustDialog extends Serenity.EntityDialog<AppTrustRow, any> {
        protected getFormKey() { return AppTrustForm.formKey; }
        protected getIdProperty() { return AppTrustRow.idProperty; }
        protected getLocalTextPrefix() { return AppTrustRow.localTextPrefix; }
        protected getService() { return AppTrustService.baseUrl; }

        protected form = new AppTrustForm(this.idPrefix);

        protected getToolbarButtons(): Serenity.ToolButton[] {

            var buttons = super.getToolbarButtons();

            this.form.Platform.change((e) => {
                this.form.AppId1.cascadeField = "Platform";
                this.form.AppId1.cascadeValue = this.form.Platform.value;
                this.form.AppId2.cascadeField = "Platform";
                this.form.AppId2.cascadeValue = this.form.Platform.value;
            });

            
           /* $(document).ready(function () {
                $("input[name = 'Serenity_RadioButtonEditor10']").click(function () {
                    var radioValue = $("input[name='Serenity_RadioButtonEditor10']:checked").val();
                    /*$.ajax({
                        url: 'AppTrustEndpoint.cs/get_data',
                        type: "post",
                        data: JSON.stringify(radioValue),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function () {
                            alert("success");
                        }
                    });
                });
            });*/

            return buttons;
        }
            /*var text = "Selected - ";
                    if (radioValue.valueOf() == 10) {
                        alert("Android");
                    } else {
                        alert("iOS");
                    }*/
          
            
        
    }
}`

There are some comments on it, but it's just attempts.

**Comment by JohnRanger** [comment]
Also the field "platform" must be in the xyzForm.cs. If you don't want it to be shown, tag it with [hidden].

If it _is_ in the xyzForm.cs, then a T4 transform (sometimes 2x) is neccessary to create the fields on the client-side (so that they appear when you do this.form.xxx.

Also if you do have callbacks, make sure that you put .bind(this) at the end of the callback code (after the closing bracket "}" in order to guide the callback to what scope "this" within the callback code belongs to).

Regards,

John

**Comment by luongnv6** [comment]
You should write events in the constructor
```
namespace DashboardSMICv2.Smic {

@Serenity.Decorators.registerClass()
export class AppTrustDialog extends Serenity.EntityDialog<AppTrustRow, any> {
    protected getFormKey() { return AppTrustForm.formKey; }
    protected getIdProperty() { return AppTrustRow.idProperty; }
    protected getLocalTextPrefix() { return AppTrustRow.localTextPrefix; }
    protected getService() { return AppTrustService.baseUrl; }

    protected form = new AppTrustForm(this.idPrefix);
 constructor() {
            super();
this.form.Platform.change((e) => {
            this.form.AppId1.cascadeField = "Platform";
            this.form.AppId1.cascadeValue = this.form.Platform.value;
            this.form.AppId2.cascadeField = "Platform";
            this.form.AppId2.cascadeValue = this.form.Platform.value;
        });

        
       /* $(document).ready(function () {
            $("input[name = 'Serenity_RadioButtonEditor10']").click(function () {
                var radioValue = $("input[name='Serenity_RadioButtonEditor10']:checked").val();
                /*$.ajax({
                    url: 'AppTrustEndpoint.cs/get_data',
                    type: "post",
                    data: JSON.stringify(radioValue),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function () {
                        alert("success");
                    }
                });
            });
        });*/
}
    protected getToolbarButtons(): Serenity.ToolButton[] {

        var buttons = super.getToolbarButtons();
        return buttons;
    }
}

**Comment by leovamos** [comment]
@luongnv6 and @JohnRanger, you're amazing! Thank you very much for the help. Now it's working how it should:

![smic_help_trust_sucess](https://user-images.githubusercontent.com/38430921/66226431-2c661c00-e6b1-11e9-95b7-ce3f48e41084.png)

Android has six apps and iOS doesn't have any associated yet

![smic_help_trust_sucess2](https://user-images.githubusercontent.com/38430921/66226470-40118280-e6b1-11e9-9a40-a0babaed4d2b.png)

Now for clarification and later use in perhaps an upcoming attempt to change a Form. Why is the code in the constructor()? I mean, what is this constructor method for? I know, the name is trivial, but I want to understand the methods better.

And reading the code better, it seems to me that this format in which it is written is basically:
"This field of this form has such a value". It looks like a jQuery, but simplified. My real confusion is in cascadeField and cascadeValue, what are they?

Anyway, thank you so much for the help. I'm glad to have @JohnRanger 's constant help and now with your, @luongnv6.

**Comment by leovamos** [comment]
Hey, @luongnv6 

I had some problems with posting code in my issues, and now I'm deleting all my codes from my issues. Could you delete or erase all your comments with codes, please? It will help me a lot.

**Comment by jacklengthy** [comment]
@JohnRanger https://stackdev.space/questions/retrieve-matching-rows-from-a-sql-server-table-by-querying-a-json-column-using-c
