### ISSUE TITLE
How can I store the user ID using key="Logging" in web.config.

### ISSUE THREAD

**Issue by angelogl** [volkanceylan/Serenity#4617]
I finished a Application WEB and need to implement a logging access to control the operations made against the Databases' Tables. I test the SqlLogger and the log file, but i need to store the User ID with the rest of the information available to know who made the operations..

Besides, I am using a additional table to store only the 'insert', 'update' and 'delete' operations through a trigger:

ALTER TRIGGER trgLog   ON [dbo].[SystemLogs]
   INSTEAD OF INSERT
AS
BEGIN
   SET NOCOUNT ON;
   INSERT INTO LogAcceso (EventDate, LogMessage )
   SELECT i.EventDate, i.LogMessage
   FROM  inserted i
   WHERE i.LogMessage LIKE ('%INSERT%') or i.LogMessage LIKE ('%UPDATE%') or i.LogMessage LIKE ('%DELETE%');
END

Thans for your help.

**Comment by Febriantos** [comment]
Have you checked this tutorial ?
https://github.com/volkanceylan/Serenity/wiki/Auditing:-Audit-Log-for-Insert-Update-and-Delete-using-Single-Table

**Comment by angelogl** [comment]
Thanks a lot @Febriantos. I found a solutions copying the _SqlLogger_.cs class to my project, adding 
       **{ "@UserName", user != null ? user.Username : string.Empty}**

and in the Web.config
**INSERT INTO SystemLogs (EventDate, LogLevel, LogMessage, Exception, SourceType, UserName, Operacion, Tabla) VALUES (@date, @level, @message, @exception, @source, @UserName)**

But your tutorial represents a better way to do what I want.

Now, I would like to ask you a question. if i use _IAuditLog_ it means that I must have a Int32Field in my tables? I have tables with no IDENTITY or INT field, due to the simple of the content.

Thank again for your answer, it helped me a lot. I really appreciate your help.
