### ISSUE TITLE
how to add a button in a dialog

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4618]
When iam adding a button in dialog using xyzdialog.ts file. Then the button is getting displayed on the top of the grid aswell.
How to restrict the button displaying on the grid?? instead i need to display button on the dialog only

**Comment by JohnRanger** [comment]
@flextrio-gandhi ,

that's strange. when I am adding buttons in my xyzDialogs, then they appear only on that specific dialog where I do the override of the getButtons method.

can you share your full xyzDialog code where this problem occur?

With kind regards,

John

**Comment by flextrio-gandhi** [comment]
was using  below functin in dialog.ts, Is that fine or should override any other function??
protected getToolbarButtons(): Serenity.ToolButton[] {
            let newBtn: Serenity.ToolButton =
            {
                //button creation logic goes here 
            }
            buttons.push(newBtn);
            return buttons;
        }

**Comment by Febriantos** [comment]
Which version of serenity do you use?

**Comment by JohnRanger** [comment]
Hi @flextrio-gandhi ,

in my xyzDialog.ts, I override the same function but do it like this:
```ts
       protected getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            // *** Create Dropdown-Button ***
            buttons.push(
                {
                    title: Q.text("Dialogs.Documents.Button.Stampante"),	// *** Get button text from translation
                    cssClass: 'stampe',
                    icon: 'fa-print',
                    onClick: () => {

                        // *** do something on click if you want **

                    },
                }
            );

            

            return buttons;
        }
```

The only real difference between your and my code I see in your override declaration. But I have to admit that I am no real developer - just an admin with some DEV ambitions. So I cannot tell if your way of overriding getToolbarButtons is correct or not.

But I know this: I add buttons all the time to many differnet dialogs and they never appear on any grid - only in the dialog where I have added (pushed) them to the existing buttons.

I normally do "var buttons = super.getToolbarButtons();" and then splice (remove) standard buttons if I don't need them in a specific dialog - and after that add my own. But I surely also have had the case where I didn't use the "super..." and just pushed my buttons and this also has worked as expected.

 What version of SF is your project based - and core or "real" .net? (I still only use "real" .net as SF on core according to the issues here in the forum seems to have still some issues which the .net version does not have)

Hope this helps.

With kind regards,

John
