### ISSUE TITLE
authentication using DotNetCasClientAuth

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#4619]
Hi,
I've change the authentication from form to DotNetCasClientAuth  (apero CAS) all are working fine so far, however sometime the users after 20 to 30 minutes are getting "Authorization is required for this services" , after refreshing the page the session get retrieved and Serenity.Authorization.UserDefinition become not null.
 the sessionState is 180 minutes and CAS sessions state is the same, but I'm unable to find why the UserDefinition become null after 20 to 30 minutes?

Any idea how to fix this?

thanks

**Comment by JohnRanger** [comment]
That's probably something which @volkanceylan can answer best.

With kind regards,

John

**Comment by volkanceylan** [comment]
I don't know about DotNetCasClientAuth etc, sorry.
