### ISSUE TITLE
Dashboard permission

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#462]
Is there anyway to set dashboard permission? So parts of the dashboard appears to a user who has a particular permission?

**Comment by 107295472** [comment]
The default permissions,I want to give Employees and Users permission to do ah

**Comment by volkanceylan** [comment]
Use Serenity.Authorization.HasPermission in dashboardindex.cshtml to hide parts with IF statements based on permission.

**Comment by wdhodges** [comment]
Thank you, I'll try it out tonight!

**Comment by jmkamran** [comment]
I want to reopen this case for new update of core5. Kindly tell me in core 5 how can i set permission in dashboard in previous version  the code is like this
if (Serenity.Authorization.HasPermission("HelpDesk:General"))
    {


        @section ContentHeader {
            <h1> @LocalText.Get("Dashboard: HelpDesk") </h1>
        }
    }

**Comment by dfaruque** [comment]
at the top of your cshtml file `@inject Serenity.Abstractions.IPermissionService Permissions`
then you can write
`if (Permissions.HasPermission("Some:key"))`
