### ISSUE TITLE
Detail Data in Master Grid

### ISSUE THREAD

**Issue by tomuee** [volkanceylan/Serenity#4620]
Hello all!

First, I want to thank @volkanceylan for this great template! I love it!

My question is: Can I view Detail Data comma-separated in the Master Grid?
My Entity has a field which looks like this:
```
[DisplayName("Drive"), MasterDetailRelation("DoorId"), NotMapped]
public List<DrivesRow> DrivesList
{
    get { return Fields.DrivesList[this]; }
    set { Fields.DrivesList[this] = value; }
}
```
The `DrivesRow` has other fields (`SerialNumber`, `InstallationDate`, ...) which i want to display in the Master Grid. This is a requirement from the customer.
I already tried somthing like this:
```
[DisplayName("Drives Serial Numbers"), NotMapped]
[Expression("(SELECT SUBSTRING( (SELECT ', ' + d1.[SerialNumber]  AS [text()] FROM [hsw].[Drives] d1 WHERE d1.[DoorId]  = T0.[DoorId] AND d1.[RemovalDate] IS NULL ORDER BY d1.[SerialNumber] FOR XML PATH('')), 3, 10000) [Drives])")]
[LookupInclude, QuickSearch]
public String DrivesSerialNumbers
{
    get { return Fields.DrivesSerialNumbers[this]; }
    set { Fields.DrivesSerialNumbers[this] = value; }
}
```
This works fine, also the `QuickSearch` works. But I want to get rid of these Subselects, they make the whole program really slow. The Master row grew to 78 fields which are all needed as columns by the customer.
With the SQL Profiler I found out that Serenity makes two Selects, one on the Master row and one on the Detail row. So the Subselects for the SerialNumbers and InstallationDates and so on do the work which is already done by the `MasterDetailRelation` Attribute of the Detail-Field.

So, to conclude this: Is it possible to get "A List of SerialNumbers, InstallationDates, ..." (a List of Strings or DateTimes) or a comma-joined string of these fields off the `MasterDetailRelation`? This would make my DB-Query really faster.
I already thought about adding the columns manually to the grid in the `getColumns()` method. But then the QuickSearch does not work anymore.

For now, a normal `List` in the grid takes ~4.5 Seconds. Loading the Lookup needs about ~9 Seconds. Sorting on a field results in a timeout and searching with the QuickSearch too. I looked at the QuickSearch-query through the profiler and tried it manually in SQL Server Management Studio, it needed about ~4.5 Minutes. This is way too much.
The Master Row has ~15,000, the Detail row ~12,000 entries.

This is a real problem and I would appreciate any help you can give me!

**Comment by JohnRanger** [comment]
Hi @tomuee ,

first: 15000 rows are not much for a decent SQL system. Do you have indexes on all the foreign keys? If not, put them there. This should dramatically speedup the whole thing.

Then - instead of doing sub querys within Serenity, you could virtually merge the data already in the SQL server by creating a view which will deliver all the data you want to see in one row of the master grid. So that offloads the hard work over to the SQL server which is better suited to do joins.

What do you think about above suggestions?

With kind regards,

John

**Comment by tomuee** [comment]
Hello @JohnRanger 

thank you for your suggestions!

No, i have no indeces added to the FK fields. I'll try it.

I didn't think about a view, this is a good idea. I'll give it a try!

But for my own interest, isn't it possible to load fields of a `MasterDetailRelation` into a List of, for example, strings (a List of `SerialNumber`)? In some cases (but not here) I need to process this data.
This would give easier access to the data an the Lookup of the detail field would stay small.

**Comment by tomuee** [comment]
Hello @JohnRanger 

the indeces did the trick. For now the software is fast enough.
The problem of the view is, that the columns of the master grid row often change. So I have to change the view too in most cases. This is why i didn't implement a view.

I'll come back later on this problem when I have enough time. But for now it's running well.

Thank you for your help!
