### ISSUE TITLE
Lookup on Insert and different on Update

### ISSUE THREAD

**Issue by jrl123** [volkanceylan/Serenity#4624]
How may we set a Lookup when a user goes to Insert new record, and another different lookup if is updating.

I cannot be able to find something like that.

**Comment by JohnRanger** [comment]
Hi @jrl123 ,

what exactly do you want to achieve?

Having list1 of items in a dropdown when adding and another list2 of items in the same dropdown when editing?

If yes then you will have to programmatically fill the dropdowns in each situation.

Look at my answer here on how to fill the dropdowns programmatically: https://github.com/volkanceylan/Serenity/issues/4616 (last long comment of mine at the near bottom).

Hope this helps.

With kind regards,

John
