### ISSUE TITLE
How to add groupable checkbox in grid 

### ISSUE THREAD

**Issue by dhanrajKumbhar** [volkanceylan/Serenity#4627]
Is it possible? I want to add a checkbox on grouping level
If I select checkbox on the group level entire row of the group also selected

see the below screenshots

![image](https://user-images.githubusercontent.com/55383898/65772813-a1d56800-e158-11e9-983f-a87425a77d10.png)

Please help me
Thanks in advance

**Comment by dhanrajKumbhar** [comment]
@volkanceylan Please help me
it's very argent

**Comment by minhhungit** [comment]
@dhanrajKumbhar  I'm working to help you :)

**Comment by dhanrajKumbhar** [comment]
@minhhungit Thank you

**Comment by minhhungit** [comment]
hi @dhanrajKumbhar , I tried to implement it, here is my code:

``` javascript
private rowSelection: Serenity.GridRowSelectionMixin;
private selectionByGroup: Q.Dictionary<boolean> = {};

private defaultGrouping = [{
	formatter: x => {
		let groupId: number = x.rows[0].YOUR_GROUP_ID;
		let groupName: number = x.rows[0].YOUR_GROUP_NAME;
		
		let chk = `<input type="checkbox" class="inline-action chk-group" style="padding: 0 !important; margin: 0 !important; min-height: auto" x-group-id="${groupId}" ${(curState == true ? "checked" :"")} />`;
		
		return 'Group: ' + groupName +  chk ;
	},
	getter: fld.YOUR_GROUP_ID
}

constructor(container: JQuery) {
	super(container);
}

protected createToolbarExtensions() {
	super.createToolbarExtensions();
	this.rowSelection = new Serenity.GridRowSelectionMixin(this);
}

protected onClick(e: JQueryEventObject, row: number, cell: number) {
	super.onClick(e, row, cell);

	if (e.isDefaultPrevented())
		return;

	let item = this.itemAt(row);
	let target = $(e.target);

	// if user clicks "i" element, e.g. icon
	if (target.parent().hasClass('inline-action'))
		target = target.parent();
		
	if (target.hasClass("chk-group")) {
		//e.preventDefault();

		var itemAtRow = <YOUR_ROW>item;

		let groupId = Q.toId(target.attr("x-group-id"));

		let currentChkState = $(e.target).is(":checked");
		this.selectionByGroup[groupId] = currentChkState;

		let currentChecked = this.rowSelection.getSelectedKeys();                
		let itemsByGroup = this.view.getItems().filter(x => x.GroupId == groupId).map(x => x.Id.toString());
		
		if (!currentChkState) {

			let newItems = currentChecked.filter(
				function (e) {
					return this.indexOf(e) < 0;
				},
				itemsByGroup
			);

			this.rowSelection.setSelectedKeys(newItems);

			this.view.populate();
		}
		else {

			this.rowSelection.setSelectedKeys((currentChecked || []).concat(itemsByGroup || []));
			this.view.populate();
		}
	}
	
	protected getColumns() {
		var columns = super.getColumns();

		let selectionCol = Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection);
		selectionCol.width = 30;
		selectionCol.minWidth = 30;
		columns.splice(0, 0, selectionCol);

		return columns;
	}
}
```

I hope it helps you, please update it to match with yours

**Comment by dhanrajKumbhar** [comment]
@minhhungit  Thanks for replay
I tried with your code but I got errors on code 

getter: **fld**.Id
let chk = `<input type="checkbox" class="inline-action chk-group" style="padding: 0 !important; margin: 0 !important; min-height: auto" x-group-id="${groupId}" ${(**curState** == true ? "checked" :"")} />`;

**Comment by minhhungit** [comment]
@dhanrajKumbhar 

put this line into your grid.ts

>import fld = [YOUR_ROW].Fields;

```js
namespace [Your_Namespace].Default {

    import fld = [Your_Row].Fields;
   
    @Serenity.Decorators.registerClass()
    export class YourGrid extends Serenity.Ent ....
    //    ...
```

**Comment by dhanrajKumbhar** [comment]
@minhhungit  
Thank u 
I had implemented your code but it doesn't work for me.
it seems the same functionality as previous 
My code is:

 private defaultGrouping = [{
            formatter: x => {
                let groupId: number = x.rows[0].UsersInfoId;
                let groupName: number = x.rows[0].UsersInfoName;
                let curState: true;
                let chk = `<input type="checkbox" class="inline-action chk-group" style="padding: 0 !important; margin: 0 !important; min-height: auto" x-group-id="${groupId}" ${(curState == true ? "checked" : "")} />`;

                return 'Group: ' + groupName + chk;
            },
            getter: fld.UsersInfoId
        }]

  protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);
            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass("chk-group")) {
                    //e.preventDefault();

                    var itemAtRow = this.itemAt(row);

                    let groupId = Q.toId(target.attr("x-group-id"));

                    let currentChkState = $(e.target).is(":checked");
                    this.selectionByGroup[groupId] = currentChkState;

                    let currentChecked = this.rowSelection.getSelectedKeys();
                    let itemsByGroup = this.view.getItems().filter(x => x.UsersInfoId == groupId).map(x => x.Id.toString());

                    if (!currentChkState) {

                        let newItems = currentChecked.filter(
                            function (e) {
                                return this.indexOf(e) < 0;
                            },
                            itemsByGroup
                        );

                        this.rowSelection.setSelectedKeys(newItems);

                        this.view.populate();
                    }
                    else {

                        this.rowSelection.setSelectedKeys((currentChecked || []).concat(itemsByGroup || []));
                        this.view.populate();
                    }
                }

**Comment by dhanrajKumbhar** [comment]
@minhhungit 

Can you please send me the demo link

**Comment by minhhungit** [comment]
@dhanrajKumbhar sorry I don't have demo for you
the easiest is you should provide error information, any clue, any javascript error, any strange behaviors...
please describe more detail about your problem so I can help

**Comment by dhanrajKumbhar** [comment]
@minhhungit 
I'm new for serenity
It doesn't see any error information 
It seems basic functionality same like =>
![image](https://user-images.githubusercontent.com/55383898/65877548-988f0a00-e3a9-11e9-8535-11f199bbc5a1.png)

I'm sharing my code if you get the idea 
My previous code before implementing your code =>

  export class CategoryUserMappingGrid extends Serenity.EntityGrid<CategoryUserMappingRow, any> {
        protected getColumnsKey() { return 'Master.CategoryUserMapping'; }
        protected getIdProperty() { return CategoryUserMappingRow.idProperty; }
        protected getLocalTextPrefix() { return CategoryUserMappingRow.localTextPrefix; }
        protected getService() { return CategoryUserMappingService.baseUrl; }

        private rowSelection: Serenity.GridRowSelectionMixin;


        constructor(container: JQuery) {
            super(container);

        }
   
        protected createToolbarExtensions() {
            super.createToolbarExtensions();

            this.slickGrid.registerPlugin(new Slick.Data.GroupItemMetadataProvider());
            var groupingMixin = new Serenity.DraggableGroupingMixin({
                grid: this
            });
            this.rowSelection = new Serenity.GridRowSelectionMixin(this);
            groupingMixin.plugin.setDroppedGroups(["UsersInfoName"]);
            this.view.expandAllGroups(0);
        }

        protected getSlickOptions() {
            var opt = super.getSlickOptions();
            // need to turn grouping panel ON for drag drop grouping to work properly
            opt.groupingPanel = true;
          
            return opt;
        }

        protected markupReady() {
            super.markupReady();

        }


        protected getColumns() {
            var columns = super.getColumns();
            
            let selectionCol = Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection);
            selectionCol.width = 20;
            selectionCol.minWidth = 20;
            selectionCol.maxWidth = 20;
            
            columns.splice(0, 0, selectionCol);
           // columns.splice(0, 0, Serenity.GridRowSelectionMixin.createSelectColumn(() => this.rowSelection));

          
            return columns;

        }

        
        }
    }
}

**Comment by minhhungit** [comment]
make sure that you have this code, it look I missed this line

```js
constructor(container: JQuery) {
    super(container);
    this.view.setGrouping(this.defaultGrouping); // <==================
}
```

btw, try to open develop mode on your browser (F12) and show me anything you see

**Comment by minhhungit** [comment]
And I see you are working on DraggableGroupingMixin, I did not test with that mode. 
The code that create checkbox on group line might not work for you

**Comment by minhhungit** [comment]
This is my demo, but sorry I can not share it

https://ibb.co/5LMZcD3

**Comment by dhanrajKumbhar** [comment]
@minhhungit 
Where you declare curState

**Comment by minhhungit** [comment]
I tested with DraggableGroupingMixin, it works

make sure that when you click on checkbox on group line, it can get groupId value
console.log to see value

and it looks I also miss this line:

```js
let curState = Q.coalesce(this.selectionByGroup[wellId], false); // <============
let chk = `<input type="checkbox" class="inline-action chk-group" style="padding: 0 !important; margin: 0 !important; min-height: auto" x-group-id="${groupId}" ${(curState == true ? "checked" :"")} />`;
		
return 'Group: ' + groupName +  chk ;
```

so sorry :D

**Comment by minhhungit** [comment]
let me know if it works or not, or any stuck

**Comment by dhanrajKumbhar** [comment]
wellId means?

**Comment by minhhungit** [comment]
@dhanrajKumbhar  It is your group id

**Comment by dhanrajKumbhar** [comment]
@minhhungit 
Thanks lot Brother
  Now It's working after removing DraggableGroupingMixin

**Comment by dhanrajKumbhar** [comment]
It works if grouping is fixed 
it doesn't work for dynamic grouping

**Comment by minhhungit** [comment]
Yes,  groupId must be fixed, if you use drag and drop then you have to add more code to get group id, because it is dynamic field

**Comment by dhanrajKumbhar** [comment]
Yes
 Now I am moving with fixed group id
I appreciate your time so much
Thank you so much for the code It took a few hours to implement and get working but It's working great.

**Comment by JohnRanger** [comment]
@dhanrajKumbhar ,

this would make up a great wiki entry :-)

Would you mind to share your working version with us?

With kind regards,

John

**Comment by dhanrajKumbhar** [comment]
@minhhungit 
jin

Select all functionality is not working
![image](https://user-images.githubusercontent.com/55383898/65944452-591af900-e44f-11e9-8a60-02d35224f7e6.png)

**Comment by minhhungit** [comment]
that function is default (serenity GridRowSelectionMixin), I don't think new code cause that issue

**Comment by dhanrajKumbhar** [comment]
@minhhungit 
Yes, This was resolved now
I think that the causes of DraggableGroupingMixin
