### ISSUE TITLE
return http error codes

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#4636]
hi all,

searched around but couldn't find a solution so hoping someone kind enough to help.

I have a slightly complex query performed inside MySaveHandler which works well however, what I'd like to do is return a 401 if the method fails (user has no permission). I know ValidationError can be used from a service but that returns a 400. Any ideas how to return http error codes from repository or service?

many thanks in advance

**Comment by fwd079** [comment]
Bit late here but was looking for that myself and ended up achieving it as below.

```csharp
if (!YourMethodToCheckPermissions())
{
 Response.StatusCode = (int)System.Net.HttpStatusCode.Unauthorized;
  var res = new SaveResponse() { 
   Error = new ServiceError() { 
    Code = @"AccessDenied",
    Message = LocalText.Get(@"Authorization.AccessDenied")
   }
  }; 
 return res;
}
else
{
 // Your complex query performed inside MySaveHandler
}
``` 

Produces this error message:

![image](https://user-images.githubusercontent.com/7912632/68238534-4ae96b00-0001-11ea-854e-9c15677f28df.png)

And shows this on response:

![image](https://user-images.githubusercontent.com/7912632/68238605-66ed0c80-0001-11ea-977e-7ea81d49492f.png)

Regards.

**Comment by abelal83** [comment]
@fwd079 thank you so much for the response! I knew someone would eventually have the answer, much appreciated!
