### ISSUE TITLE
Generated ServerType form does not include field when using custom LookupEditor

### ISSUE THREAD

**Issue by qprotex** [volkanceylan/Serenity#4637]
I have implemented the code described in the following link:

https://github.com/volkanceylan/Serenity/wiki/Lookup-Editors:-How-to-Create-Lookup-Editor-for-code-description-tables

On the form file Modules\Default\EstimationsDetail\EstimationsDetailForm.cs I have use the ItemsEditor2 custom Lookupeditor and it works perfectly:
![image](https://user-images.githubusercontent.com/13024779/65926797-f4b35780-e3c4-11e9-94a4-da0bee8c9a9e.png)

![image](https://user-images.githubusercontent.com/13024779/65926902-7efbbb80-e3c5-11e9-8255-bc6a5dbe8e06.png)

But after running the T4 templates , the generated file  \Imports\ServerTypings\Default.EstimationsDetailForm.ts does not have the ItemId field:
![image](https://user-images.githubusercontent.com/13024779/65926808-ff6dec80-e3c4-11e9-8eba-6c4f3b2649ba.png)

If I use instead the standard [LookupEditor(typeof(ItemsRow))], the field ItemId is generated. I need that field as I need access to the changeSelect2 event in the dialog file.

**Comment by Estrusco** [comment]
In wiki, at this point there is an error

```cs
 public partial class LKCodeDescrAttribute : LKCodeDescrAttribute
```

is instead

```cs
 public partial class LKCodeDescrAttribute : LookupEditorBaseAttribute
```

Your source is correct?
(now I correct the wiky)

**Comment by dfaruque** [comment]
Don't know whether it is a bug or not. For some reason, the serenity does not generate for sub-namespace like `RootNamespace.Default`

I think your namespace in customEditor.ts is other than your  RootNamespace (maybe it is `RootNamespace.Default`) remove the `.Default` part from namespace then build and t4. I hope your issue will be resolved.

**Comment by qprotex** [comment]
> ```cs
> LookupEditorBaseAttribute
> ```

Thanks, I have fixed that part although it was not the reason why the field was not being generated. Additionally I needed to remove the base prefix from the values below:

CodeName = codeFieldName;
DescrName = descriptionFieldName;

**Comment by qprotex** [comment]
> Don't know whether it is a bug or not. For some reason, the serenity does not generate for sub-namespace like `RootNamespace.Default`
> 
> I think your namespace in customEditor.ts is other than your RootNamespace (maybe it is `RootNamespace.Default`) remove the `.Default` part from namespace then build and t4. I hope your issue will be resolved.

It worked, thanks!!!
