### ISSUE TITLE
Pdf is not getting generated

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4638]
I am trying to get an order printed and have downloaded the wkhtmltopdf .

Have few queries and blockers as:
1) I am not sure at which location this needs to be copied. I have downloaded and tried both 32/64 bits.
2) I am getting the following error when pasted in wkhtmlpath (rootfolder/wwwroot/bin):
 System.ComponentModel.Win32Exception: 'The requested operation requires elevation'
3) I have provided "full control access" to all users of this application but still get the above exception.

Request suggestions/solution.

**Comment by edwardch** [comment]
If I remember correctly you were using .NET Core, and I don't think wkhtmltopdf.exe will work in a non-Windows environment... 

You could try using some other html-to-pdf API or tool though?

**Comment by reacharihant** [comment]
Thanks once again @edwardch. I was trying unnecessarily. Will look into html-to-pdf API solutions. It would be better if wkhtmltopdf.exe not working in .NET Core is documented and displayed upfront in Serenity tutorials (or may be I missed it ).

**Comment by edwardch** [comment]
I _think_ wkhtmltopdf.exe does work with .NET Core, but I just don't think it will work in a non-Windows environment. Linux/OSX doesn't run .exe's unless you have something like wine (which could be complicated). 

Try take a look at [Wkhtmltopdf.NetCore](https://github.com/fpanaccia/Wkhtmltopdf.NetCore), [DinkToPdf](https://github.com/rdvojmoc/DinkToPdf) or something commercial like [PDFShift](https://pdfshift.io/) or equivalent. 

If you find a solution, I'd be interested to know what it is...
