### ISSUE TITLE
How to make one field in XXEnitityColume  just visible to special role

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#464]
I have learned how to make one field just visible to special role in XXEntiyForm ,but how can I implement one field in XXEnitityColume  just visible to special role?

**Comment by zerodev** [comment]
How did you do the first one?

**Comment by ChenZhaobin** [comment]
Follow the tutorials of tenant ,which handle the field of tenantId Just follow this way.

**Comment by volkanceylan** [comment]
I recommend using permissions for this. Assign a permission only to that role. Roles are only a set of permissions. Don't depend on them.

**Comment by 107295472** [comment]
Navigasyon daha uygun yapılandırılmış edilemiyorsa, doğrudan veritabanına eklemek

**Comment by 107295472** [comment]
Admin can be removed, it should be prohibited under the

**Comment by ChenZhaobin** [comment]
@volkanceylan yes, I just want to make one field has a special read/write permission,how can I do this?

**Comment by 107295472** [comment]
Look at the document, it's all over.

**Comment by volkanceylan** [comment]
There is a topic about GetEditableFields in multi tenant guide. That is what you need.
