### ISSUE TITLE
Pass param to stored procedure

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4640]
Hi all!
In customerGrossSalesGrid example, we can pass parameter from a dateRangeQuickFilter to a stored procedure.
`
protected getQuickFilters() {
            var filters = super.getQuickFilters();

            // we create a date-range quick filter, which is a composite
            // filter with two date time editors
            var orderDate = this.dateRangeQuickFilter('OrderDate', 'Order Date');

            // need to override its handler, as default date-range filter will set Criteria parameter of list request.
            // we need to set StartDate and EndDate custom parameters of our CustomerGrossSalesListRequest
            orderDate.handler = args => {
                
                // args.widget here is the start date editor. value of a date editor is a ISO date string
                var start = args.widget.value;

                // to find end date editor, need to search it by its css class among siblings
                var end = args.widget.element.nextAll('.s-DateEditor')
                    .getWidget(Serenity.DateEditor).value;

                (args.request as CustomerGrossSalesListRequest).StartDate = start;
                (args.request as CustomerGrossSalesListRequest).EndDate = end;

                // active option controls when a filter editor looks active, e.g. its label is blueish
                args.active = !Q.isEmptyOrNull(start) || !Q.isEmptyOrNull(end);
            };
`
That's pretty cool :)!
I have a stored procedure that is used to populate a lookupEditor in a detail form.
I would like to pass my parameter in this Master/detail (via editor?) and relaod my lookup.
Where (and how) can I acheive this ?
Thanks

**Comment by JohnRanger** [comment]
I don't know if this is possible - but whenever I have to dynamically retrieve some list of rows depending on a dynamic parameter from client-side, I do what I have described here: https://github.com/volkanceylan/Serenity/issues/4616 (my last very long comment in that thread there - a bit before the middle if you look at the scroll bar).

Hope this helps,

John

**Comment by volkanceylan** [comment]
Lookups doesn't support parameters, and are like static variables shared by every user of your site. You'll need to use service calls for that.

**Comment by JohnRanger** [comment]
@volkanceylan ,

thanks for clarification - I never have looked too much into the lookups and I just used them for relatively static tables.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi @fremar83 ,

look up my above comment. there I lined to issue  #4616 (my last very long comment in that thread there - a bit before the middle if you look at the scroll bar).

That is exactly such a service call.

Regards,

John

**Comment by fremar83** [comment]
@JohnRanger
OMG! I've just found your response!!
Thank's for your help! I'll look better at your issue ASAP!
Best regards,
Frederic
