### ISSUE TITLE
Replace Slick Grid to table or custom HTML code

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#4641]
Hi!

After long time, back!

So, I got this challenge: I need to show a map of the rooms of my business.
I would like to do it in custon html page or custom table, instead serenity's tradicional grid.
But I would like to use Serenity original buttons and criteria filters.

How to do it?

Thank's in advanced

**Comment by Febriantos** [comment]
Hi @rolembergfilho,

I believe you can use TemplatedWidget to accomplish what you want. I have implement a custom dashboard with TemplatedWidget  successfully and added multiple widgets on the same page. 

How to do it?
>>> Unfortunately I can't share the code since it's proprietary. But you can start with TemplatedWidget. 

Would you mind sharing your requirement in more detail so other person can have better suggestions for you.

Thanks.

**Comment by JohnRanger** [comment]
Hi @rolembergfilho ,

why not doing this in a dialog? We just had a similar question - how to display a map within a dialog.

This should possibly be adaptable to display map points too. And these could be sent from the checkbox-marked grid via button click to the dialog.

For the map in dialog, look this issue: https://github.com/volkanceylan/Serenity/issues/4611

And have a look at leaflet.js.

Hope this gives you a creative input :-).

With kind regards,

John

**Comment by rolembergfilho** [comment]
Hi @Febriantos , that's cool. Could you share the how-to that you did it? Or something like a check list?

Hey @JohnRanger, thanks for the suggestion. I'll try do it like a dialog. For me, dialog is just for show fields and captions. I'll try to call dialog to show custom forms.

What's I'm trying to do: I have a physical map, with rooms, hall, floor, etc.... Each room have a professional (or professionals) that work with one speciality, like physiotherapy or speech therapy.

And I would like to control it by time and by patience, or by time and by professional, for example.

So, I want to draw this map in custom html. And each room will be green (free) or yellow (busy).

When i select a room, a pop up or modal form will be show, with information in this moment.

**Comment by JohnRanger** [comment]
Hi @rolembergfilho ,

ahh :-) A floor map. Maybe you could use this jquery plugin to do the image map: http://www.outsharked.com/imagemapster/default.aspx?faq.html.

Although I never have used this, from looking at it - it could possibly be very helpful. Of course you would have to invent a kind of mapping between the image areas and your data.

Please let us know your progress as this sounds an interesting thing.

Regards,

John

**Comment by rolembergfilho** [comment]
Amazing library, @JohnRanger !!!

I'll study it and try to do it
