### ISSUE TITLE
How to integrate auto print when click a print button?

### ISSUE THREAD

**Issue by fredvaliant** [volkanceylan/Serenity#4643]
When doing a printing, is there a way to do direct printing instead of showing a preview first? Thanks in advance.

**Comment by Estrusco** [comment]
You can't. If anyone could print from website without user permission, we should keep the printers off :)

You can auto open print dialog, but not direct print a document, for security reasons. 

```ts
Common.PdfExportHelper.exportToPdf(
{
    grid: this,
    onViewSubmit: () => this.onViewSubmit(),
    output: "newwindow",
    autoPrint: true
});
```

**Comment by luongnv6** [comment]
Common.ReportHelper.execute({
                        reportKey: YourReportKey,
                        download: true,
                        params: yourParam
                    });

**Comment by JohnRanger** [comment]
@fredvaliant ,

if you want that, you would have to implement printing from the backend (if this is an inhouse app and all printers are reachable from the web server(s) where you SF-App is running.

But this is a complete different thing - a beast - and I never yet have implemented this.

With kind regards,

John

**Comment by fredvaliant** [comment]
Thanks guys for the inputs, ill keep this noted and implement your suggestions and give you updates.

**Comment by JohnRanger** [comment]
Hi @fredvaliant ,

if you want to go the server-side route, have a look at this article: https://www.codeproject.com/Articles/335595/Rotativa-how-to-print-PDF-in-Asp-Net-MVC.

This shows how to generate PDFs on server-side out of HTML (by using [wkhtmltopdf](https://wkhtmltopdf.org/).

Then you have a pdf file which you then could print to a printer with the help of the following SO article:

https://stackoverflow.com/questions/6103705/how-can-i-send-a-file-document-to-the-printer-and-have-it-print/41751184#41751184

Hope this helps,

With kind regards,

John

**Comment by fredvaliant** [comment]
Is there a way that we can show the pdf on a pop up instead of new tab?

**Comment by JohnRanger** [comment]
Hmm,

I suppose that you use Chrome. Because this is a local PDF file which opens (if I am right), I don't think that this can be embedded within the existing page - so a new tab opens.

But I am open to correction if some real profi here has a way to do it.

With kind regards,

John
