### ISSUE TITLE
Missing Serenity Script after update Serenity at 3.9.11

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#4644]
After update Serenity a 3.9.11 version, are missing files in Scripts/Serenity and in Scripts/typings/Serenity

Anyone experimented this?

**Comment by luongnv6** [comment]
me too

**Comment by volkanceylan** [comment]
Have you run dotnet sergen restore if you are using .NET Core, and have you applied steps for Serenity 3.9.0?

https://serenity.is/docs/startsharp/updating-startsharp

**Comment by Estrusco** [comment]
I'm using .Net Framework version, I'm update all using NuGet Package Manager from Visual Studio

**Comment by volkanceylan** [comment]
Ok but did you apply 3.9.0 upgrade steps? It applies to MVC as well.

**Comment by Estrusco** [comment]
I missing it!
Thank you @volkanceylan 👍
