### ISSUE TITLE
[Bug] grid frozenColumn and sidebar toogle

### ISSUE THREAD

**Issue by hannesb** [volkanceylan/Serenity#4649]
If you set the frozenColumn in getSlickOptions(), the width of the slick grid is not adjusted when collapsing/expanding the sidebar.

Steps to reproduce:
- create sample project with Northwind included
- add to CustomerGrid.ts:
`        protected getSlickOptions(): Slick.GridOptions {
            let opts = super.getSlickOptions();
            opts.frozenColumn = 0;
            return opts;
        }
`
- start project
- click top left to expand/collapse sidebar. Notice that the width of the grid is not adjusted.

**Comment by volkanceylan** [comment]
This is a problem with frozen columns function and adminlte, as the window height doesn't change it doesn't relayout itself,

Find these lines in app.js:

```js
$("body").removeClass('sidebar-collapse').trigger('expanded.pushMenu');
$("body").addClass('sidebar-collapse').trigger('collapsed.pushMenu');
$("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');
$("body").addClass('sidebar-open').trigger('expanded.pushMenu');
```
and add following after each one:
```js
window.setTimeout(() => $('.require-layout').filter(':visible').trigger('layout'), 500);
```

**Comment by JohnRanger** [comment]
Have quickly made a wiki out of it for easier finding [over here](https://github.com/volkanceylan/Serenity/wiki/Fix:-grid-frozenColumn-and-sidebar-toogle).

Regards,

John

**Comment by hannesb** [comment]
Thx @volkanceylan 

For compatibility with IE11 (default browser in my customers company :( ), use:

```javascript
window.setTimeout(function () { $('.require-layout').filter(':visible').trigger('layout'); }, 500);
```

And don't forget to minify app.js to app.min.js for production use...
