### ISSUE TITLE
Question re purchase to anyone

### ISSUE THREAD

**Issue by gordonkenyon** [volkanceylan/Serenity#4651]
Question not an issue : Is a Visx for StartSharp supplied with purchase or do you just use the Serenity visx and are supplied examples of extra features with StartSharp ?
Thanks in advance
Gordon

**Comment by edwardch** [comment]
It's supplied... 

_Source: I am a happy StartSharp customer!_

**Comment by gordonkenyon** [comment]
Thanks mate :)
