### ISSUE TITLE
Edit Dialog

### ISSUE THREAD

**Issue by MohamedEbrahimSaad** [volkanceylan/Serenity#4652]
Please how can i make the edit dialog appears in the same page without opening a popup like in customer when adding new customer it doesn't open new popup instead the form appears directly

**Comment by MohamedEbrahimSaad** [comment]
...

**Comment by edwardch** [comment]
Add 
```ts
@Serenity.Decorators.panel()
```
to your xyzDialog.ts like line 4 here: [CustomerDialog.ts](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerDialog.ts#L4)
