### ISSUE TITLE
Underscore issue on column names

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#4653]
Hi,

There is an issue with column mapping with underscore character. 

If column name contains underscore, Query function does not fill that column. 

Example:
`var rows = connection.Query<SomeRow>("SELECT x1, some, other, columns, but_i_am_not_cool FROM hede")`

after this:

rows[0].x1 //OK
rows[0].some //OK
rows[0].other //OK
rows[0].columns//OK
rows[0].but_i_am_not_cool // NOT OK, always null

**Comment by kilroyFR** [comment]
Isn't it related to Dapper ?

Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
