### ISSUE TITLE
Order details tab is not taking orderID

### ISSUE THREAD

**Issue by tonysader** [volkanceylan/Serenity#4655]
HELLO,

I have 
Employee(EmployeeId, employeeName.. etc)
EmployeeNationality(EmployeeId,CountryId..) 
Country(CountryId, countryName...) 
tables.

I am trying to create the same example of orders- Order detail - Products in the serenity demo 

https://serenity.is/demo/Northwind/Order#new

I have created the employeeNationalitiesEditor:
```

 @Serenity.Decorators.registerClass()
    export class EmployeeNationalitiesEditor extends Common.GridEditorBase<EmployeeNationalityRow>{

        protected getColumnsKey() {
            return "HRM.EmployeeNationality";
        }
        protected getDialogType() { return EmployeeNationalityDialog; }
        protected getLocalTextPrefix() { return EmployeeNationalityRow.localTextPrefix; }
        constructor(container: JQuery) {
            super(container);
            console.log(this.getIdProperty);
        }
        validateEntity(row, id) {
            console.log(row);
            console.log(id);

            row.CountryId = Q.toId(row.CountryId);
            var sameCountry = Q.tryFirst(this.view.getItems(), x => x.CountryId === row.CountryId);
            if (sameCountry && this.id(sameCountry) !== id) {
                Q.alert('This country is already in the nationalities list');
                return false;
            }
            row.CountryCountryName = Configuration.CountryRow.getLookup().itemById[row.CountryId].CountryName;
            console.log(row);
            console.log(Q);
            return true;
        }

    }
```

In employee form I add:
```

  [Tab("Nationality")]
        [EmployeeNationalitiesEditor]
        public List<Entities.EmployeeNationalityRow> NationalityList { get; set; }

```

In employeeRow.cs I added:
```
[DisplayName("Nationalities"),MasterDetailRelation(foreignKey: "EmployeeId"),NotMapped]
        public List<EmployeeNationalityRow> NationalityList {
            get { return Fields.NationalityList[this]; }
            set { Fields.NationalityList[this] = value; }
        }
```

And in the fields of employeeRow:
`
 public RowListField<EmployeeNationalityRow> NationalityList;`

And when I open the form of the employee it opened successfully but when I save the employee nationality, inside an employee form it shows me that the employeeId cannot be null
Is there a way I can set the employeeID ???
Thanks

**Comment by volkanceylan** [comment]
Your grid dialog probably not deriving from GridEditorDialog, check your Dialog.ts

**Comment by JohnRanger** [comment]
@tonysader ,

did you initially create your xyzDialog.ts file by using sergen - and then transforming it to a detail dialog?

Then what @volkanceylan says, happens. You have to change your ```extends Common.GridEditorBase``` to ```extends Serenity.GridEditorDialog```

Regards,

John

**Comment by tonysader** [comment]
Solved. Thanks
