### ISSUE TITLE
Multitenancy with .net core 2.1

### ISSUE THREAD

**Issue by Mohammad-Yasfo** [volkanceylan/Serenity#4656]
Hello,
I have applied MultiTenancy with net core 2.1, But I have got this Error Exception: System.MissingMethodException: 'No parameterless constructor defined for this object.'

This error exception showed in Startup.cs file with code
`var textRegistry = app.ApplicationServices.GetRequiredService<ILocalTextRegistry>();
            textRegistry.AddNestedTexts();
            textRegistry.AddNestedPermissions();
            textRegistry.AddEnumTexts();
            textRegistry.AddRowTexts();`

**Comment by Mohammad-Yasfo** [comment]
> Hello,
> I have applied MultiTenancy with net core 2.0, But I have got this Error Exception: System.MissingMethodException: 'No parameterless constructor defined for this object.'
> 
> This error exception showed in Startup.cs file with code
> `var textRegistry = app.ApplicationServices.GetRequiredService<ILocalTextRegistry>(); textRegistry.AddNestedTexts(); textRegistry.AddNestedPermissions(); textRegistry.AddEnumTexts(); textRegistry.AddRowTexts();`

**Comment by Mohammad-Yasfo** [comment]
Does anyone have an example of MultiTenancy with core 2.x?

**Comment by Mohammad-Yasfo** [comment]
Does anyone have an example of MultiTenancy with core 2.x?

**Comment by edwardch** [comment]
Is this an old or a brand new project? 

I created a new project, followed the steps on [the guide](https://serenity.is/docs/tutorials/multi_tenancy/multi_tenancy) and it works fine for me. 

The `textRegistry` stuff you mentioned shouldn't have anything to do with multi tenancy...

**Comment by Mohammad-Yasfo** [comment]
@edwardch  This's a brand new project.
I'll check that, for `textRegistry`.
I followed the steps on the guide and It failed with asp .net core.

**Comment by volkanceylan** [comment]
You might have a class with [NestedLocalTexts] attribute and a parameterized constructor, which is not possible and you shouldn't.

**Comment by Mohammad-Yasfo** [comment]
Solved, the problem was using abstract class `MultiTenantRow`
Thanks for all.
