### ISSUE TITLE
Show data of a row in another table in Edit Link

### ISSUE THREAD

**Issue by leovamos** [volkanceylan/Serenity#4657]
Hi, guys

My idea is to display information from one row by clicking on its id in another table.
For example, I have the Manifest table and the ManifestTrust table.
What I want is to click on the Id that appears in the ManifestTrust table and display the Manifest information for that ID.

Here is Manifest Trust, with the clickables IDs:
![smic_help_manifesttrust](https://user-images.githubusercontent.com/38430921/66774930-3817c680-ee99-11e9-8eb9-f657cb1768e7.png)

And here is Manifest Form, what I want to show when click on ID in ManifestTrust:
![smic_help_manifest](https://user-images.githubusercontent.com/38430921/66774931-3817c680-ee99-11e9-867f-e95c9d3d1694.png)

By the way, ManifestTrust links a Manifest with another by its IDs.

The codes in ManifestTrust, for ManifestId1 and ManifestId2:
`public Int64? ManifestId1
        {
            get { return Fields.ManifestId1[this]; }
            set { Fields.ManifestId1[this] = value; }
        }

        [DisplayName("Manifest Id2"), NotNull, ForeignKey("[dbo].[Manifest]", "ManifestId"), LeftJoin("jManifestId2"),EditLink]
        public Int64? ManifestId2
        {
            get { return Fields.ManifestId2[this]; }
            set { Fields.ManifestId2[this] = value; }
        }`

The code in Manifest, in short:

`namespace DashboardSMICv2.Smic.Entities
{
    using DashboardSMICv2.Modules;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Smic"), Module("Smic"), TableName("[dbo].[Manifest]")]
    [DisplayName("Manifest"), InstanceName("Manifest")]
    [ReadPermission(SmicPermissionKeys.ReadManifest)]
    [ModifyPermission(SmicPermissionKeys.ModifyManifest)]
    [LookupScript("Smic.Manifest")]
    public sealed class ManifestRow : Row, IIdRow, INameRow
    {
        [DisplayName("Manifest Id"), Identity]
        public Int64? ManifestId
        {
            get { return Fields.ManifestId[this]; }
            set { Fields.ManifestId[this] = value; }
        }`

Thanks for the help

**Comment by luongnv6** [comment]
Hi,  

in ManifestTrustGrid.ts
```


        protected getColumns() {
            var columns = super.getColumns();          
            Q.first(columns, x => x.field == fld.ManifestId1).format =
                ctx => {
                    var item = <ManifestTrustRow><any>ctx.item;
                    return `<a href="#" class="link-manifest1">${Q.isEmptyOrNull(item.ManifestId1) ? '' : item.ManifestId1}</a>`;
                };
     
            Q.first(columns, x => x.field == fld.ManifestId2).format =
                ctx => {
                    var item = <ManifestTrustRow><any>ctx.item;
                    return `<a href="#" class="link-manifest2">${Q.isEmptyOrNull(item.ManifestId2) ? '' : item.ManifestId2}</a>`;
                };
            return columns;
        }
protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);
            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

           if (target.hasClass('link-manifest1')) {
                var dlg = new ManifestDialog();
                dlg.loadByIdAndOpenDialog(item.ManifestId1);
                this.initDialog(dlg);
            } else if (target.hasClass('link-manifest2')) {
                var dlg = new ManifestDialog();
                dlg.loadByIdAndOpenDialog(item.ManifestId2);
                this.initDialog(dlg);
            }
        }

`
Hope help you
