### ISSUE TITLE
Error After publishing

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#4658]
I had created Serenity Application using Serene ( version 3.9.10.0 ),
build the solution and created publish release.
copy all files to my server.
after login into web app, when i am clicking on user management, i am getting following error.

![1](https://user-images.githubusercontent.com/19570368/66808393-c39c6080-ef48-11e9-8894-4838d82b40a0.png)

where as web app is working fine on local IIS Express.

package.config is as follows

 `<package`` id="Serenity.CodeGenerator" version="3.9.10" targetFramework="net45" />`
`<package id="Serenity.Core" version="3.9.10" targetFramework="net45" />`
  `<package id="Serenity.Data" version="3.9.10" targetFramework="net45" />`
  `<package id="Serenity.Data.Entity" version="3.9.10" targetFramework="net45" />`
  `<package id="Serenity.Scripts" version="3.9.10" targetFramework="net45" />`
  `<package id="Serenity.Services" version="3.9.10" targetFramework="net45" />`
  `<package id="Serenity.Web" version="3.9.10" targetFramework="net45" />`
  `<package id="Serenity.Web.Assets" version="3.9.2" targetFramework="net45" />`
  `<package id="Serenity.Web.Tooling" version="3.5.1" targetFramework="net45" />`
  

Let me know, what i am doing wrong.
regards
Shailesh

**Comment by volkanceylan** [comment]
Your project is under a subfolder, check these lines in web.config and either remove / in path, or type the correct path there, e.g. instead of "/DynJS.axd", use "DynJS.axd" or "LinenTracking/DynJS.axd"

```
      <add name="DynamicScriptHandler" verb="POST,GET,HEAD" path="/DynJS.axd" type="Serenity.Web.HttpHandlers.DynamicScriptHandler, Serenity.Web" />      
      <add name="ErrorLog" path="/errorlog.axd" verb="POST,GET,HEAD" type="StackExchange.Exceptional.HandlerFactory, StackExchange.Exceptional" preCondition="integratedMode" />
      <add name="SkipStaticFileForUploadFolder" verb="GET" path="/upload/*" type="System.Web.Handlers.TransferRequestHandler" />
```

**Comment by shaileshbc** [comment]
It works, Thanks volkan ceylan
shailesh
