### ISSUE TITLE
ServerTypings/ModuleRow.ts file not being generated by sergen

### ISSUE THREAD

**Issue by UlyssesAlves** [volkanceylan/Serenity#4659]
I've created a new table called "GruposAtualizacaoAutomatica", and then I runned serenity sergen to generate the code for this new entity/module. The files were generated inside the module folder Administration/GruposAtualizacaoAutomatica, as shown in the picture below:

![image](https://user-images.githubusercontent.com/2872102/66827573-65aa5180-ef25-11e9-9da6-5835a513b578.png)

The problem is, when I run the application and try to access the new module (GruposAtualizacaoAutomatica) pages, I get an JavaScript error saying object GrupoAtualizacaoAutomaticaRow is not defined:

![image](https://user-images.githubusercontent.com/2872102/66827697-9db19480-ef25-11e9-9d25-4c73598ab812.png)

Looking at the source code generated for the module, I can see there are compilation errors on the TypeScript files GruposAtualizacaoAutomaticaDialog.ts and GruposAtualizacaoAutomaticaGrid.ts, and it's also complaining about the row, in this case saying that GrupoAtualizacaoAutomaticaRow is not defined.

![image](https://user-images.githubusercontent.com/2872102/66827930-334d2400-ef26-11e9-9e3a-21627675ace2.png)

By looking at other working modules, I could see that this missing code (GruposAtualizacaoAutomaticaRow) should have been generated inside folder Imports/ServerTypings and it should have a name of Administration.GrupoAtualizacaoAutomaticaRow.ts, but shuch file doesn't exist, and this is where I think the root of the issue is, but I don't know why this file has not been generated neither what should I do so it may be generated.

We can see below all other generated files for Administration module inside ServerTypings folder, and we also can see Administration.GrupoAtualizacaoAutomaticaRow.ts and all other files for this module (form, grid, columns, service, etc) are missing:

![image](https://user-images.githubusercontent.com/2872102/66828310-1402c680-ef27-11e9-955a-d41da8ac524a.png)

Could someone please help me on solving this issue? What to do to get those files to be correctly generated by sergen?

**Comment by edwardch** [comment]
Did you run your T4 transformations? (Menu > Build > Transform All T4 Templates")

Also, make sure you keep the S consistent: GrupoAtualizacaoAutomaticaRow and Grupo**s**AtualizacaoAutomaticaRow

**Comment by UlyssesAlves** [comment]
@edwardch the project uses .Net Core, so T4 transformations are run automatically, for what I learned in the [previous issue](https://github.com/volkanceylan/Serenity/issues/4621) I opened here on this repository.

> Also, make sure you keep the S consistent: GrupoAtualizacaoAutomaticaRow and GruposAtualizacaoAutomaticaRow

You mean that in my code or in my text?

**Comment by edwardch** [comment]
Ah right sorry, didn't realise it was .NET Core... 

If you search your solution for GrupoAtualizacaoAutomaticaRow ?

It's missing the **s** and I wonder if this was something that was changed intentionally and causing this issue. Is there anything more descriptive in the browser console?

**Comment by UlyssesAlves** [comment]
@edwardch I removed the "s" for the class identifier when generating the code. So, my table is called GruposAtualizacaoAutomatica and the class identifier for it is GrupoAtualizacaoAutomatica (without the "s"). Since it's a valid sergen option, I don't think the absence of the "s" in the class identifier would be the cause of this issue, would it?

**Comment by edwardch** [comment]
I thought maybe keep the s consistent and make sure it works first, because the browser error is looking for an object _without_ the **s**.

Also because I'm not sure what all the other contents of your files are...

**Comment by UlyssesAlves** [comment]
@edwardch Got it. I see what you are pointing to now. The browser error is related with an object without "s", and the source code is looking for a classe with "s". Interesting. I'll regenerate with the same name as the table, with "s", and share the outcome.

**Comment by UlyssesAlves** [comment]
@UlyssesAlves I've cleared all previously generated files, and then I run sergen code generation again, giving the same name for the class identifier as the name of my table. Now the error in the browser and the error in the source code are the same, and it is because the ServerTypings files were not generated for my module. So the "s" has no impact on the issue, as it happens no matter how I call my class identifier.

Do you know what are the rules/dynamics followed by sergen to generate those server typings files? I know the problem is because those files are not being generated, but I don't have a clue on how these files are generated and much less cues on why they are not being generated. But I'm positive there are something amiss related to this server typings files generation.

**Comment by edwardch** [comment]
I'm not 100% sure why you're getting this result, and it's hard to say without seeing code, schema etc...

Could you try adding this to a different module (i.e other than Administration)?

> Do you know what are the rules/dynamics followed...
Unfortunately I don't. Are you using a fresh install of Serenity? 

The only time I've seen something like this is when I have manually changed the name of something (similar to the "s" mention above).

**Comment by UlyssesAlves** [comment]
@edwardch I tried a different module, and it produces same error.

Now I have looked at the error a bit closer, and for what I have observed sergen is properly generating the servertypings files, and I can see these files in ServerTypings folder right after running sergen tool.

But for some reason these files are being deleted when I build the project in Visual Studio. Then, when I run the project, those files doesn't exist anymore, and that's what produces both the TypeScript and Browser errors.

@edwardch or someone else: do you know why would VS delete these files when building the project?

**Comment by UlyssesAlves** [comment]
I've found now exactly when my ServerTypings files are being deleted, as we can see in the picture:

![image](https://user-images.githubusercontent.com/2872102/66952171-75638c00-f032-11e9-87e2-539114567a25.png)

So, it's while Transforming ServerTypings, either via "dotnet sergen transform". Why does it delete these files, guys? Is it possible to prevent this behaviour?

**Comment by UlyssesAlves** [comment]
You are right, @volkanceylan . I'm developing in debug mode, but there was a release folder besides the debug folder in the bin directory. After removing the release folder, my server typings files were not deleted anymore, so as you said Sergen was choosing the realease version instead of choosing the debug version. 

Problem solve. Thanks.
