### ISSUE TITLE
Multi-level roles for different users

### ISSUE THREAD

**Issue by Mohammad-Yasfo** [volkanceylan/Serenity#4660]
Hello,
I need some architecture advice about Serenity application.

What is the simplest way to be able to generate a master tenant that would have access to all tenant files regardless of their Multi-Tenancy? Or to essentially create a duplicate Master Admin account?

My end goal will have 3 Permission levels of access:

- Developer(MasterAdmin): Access to anything and everything including configuration files regardless of tenancy.

- Admin(LimitedAdmin): Access to all data regardless of tenancy but removes access to configuration files (this one is essentially clones of the Developer but with less views.)

- Client(ReadOnly): Read only access to Tenant Filtered Data. Client will see preset SQLView reports on grid which can be filtered, exported to excel and exported to PDF, but will not be able to see any data outside their tenancy.

**Comment by judejay** [comment]
Add what you want to UserRetrieve service 
AdminGroup = user.AdminGroup.GetValueOrDefault()

like MultitanancyIn Permission service. HasPermission, 
   //AdminGroup
            if (user.AdminGroup == true)
                return true;
