### ISSUE TITLE
Import from .txt file

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4661]
hello everyone and @volkanceylan 
Is there any way to Import from .txt file like **IMPORT FROM EXCEL**

**Comment by edwardch** [comment]
You'll have to write some custom code for that, similar to the Excel importer. You can use [CsvHelper](https://joshclose.github.io/CsvHelper/getting-started) to make things easier for yourself. Also check its [Reading by Hand example](https://joshclose.github.io/CsvHelper/examples/reading/reading-by-hand)
