### ISSUE TITLE
Show Just Created Item in Grid

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4662]
How can I show a value from the just created item in the grid. So for example a product - if I create a new product. I want a specific value from that newly created Item to be displayed in the grid - preferably either in the Title area or the Search / Buttons Area .. 
So like this :
[https://imgur.com/GHSkejP](https://imgur.com/GHSkejP)

I know I can get the value after saving - but how to get that back to the gridview ?

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

why don't you just create a "toast" message within the xyzDialog in the onSaveSuccess method?

There you get the inserted ID back within the response variable and then you can do a lookup and gather all desired info together for the toast message.

Would this be a solution or does the info regarding the newly created item has to be visible longer than a few seconds to the end user?

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger - the info has to be visible for longer than a few seconds. They want to see it - because there is a specialized sequencing number created (and it is this number that they want to have) . For now I have them click the update button even though it is create - but that leaves the dialog open and in the way . So I thought if I can get the value back and pop it into the grid that would be acceptable.  I know I can get that number in the after save method - I assume also the Max(Id) is the latest - so either would allow me to have the latest, but how to display that  in the grid

**Comment by JohnRanger** [comment]
Hi @stixoffire ,
sorry for the long delay. I had unexpectedly an extremely busy month.

You could always manipulate the DOM directly with jquery within the callback on client-side.

```ts
protected onSaveSuccess(response) {

            // *** Debug only ***
            //alert(response.yourTableID);

            this.EditorObject.ShowInsertedRow(response.LinkTableInsertedID);    // *** Call the method in the grid via reference to show new row within detail grid editor ***

        }
```
For more details have a look at the following [issue](https://github.com/volkanceylan/Serenity/issues/4697): 

Within the onSaveSuccess method, add for example an additional div within the class ```<div class="tool-buttons">``` (at the end after the last button) and then display whatever information you want.

Something like this:
```ts
$("<div>Your inserted content goes here</div>").insertAfter($("div.tool-buttons:last-child"))
```

I know, this is not a complete Copy&Paste solution - but should give you a creative hint how to do something like this.

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 
I am posting my solution here so others might be able to get use it - maybe it helps someone.
The following is what I had done :

my XYZ DIALOG is a panel
```
    @Serenity.Decorators.panel()
    export class QuoteDialog extends Serenity.EntityDialog<QuoteRow, any> {

```

In my XYZGRID
``
namespace myproject{

    import fld = QuoteRow.Fields;

    @Serenity.Decorators.registerClass()
    export class QuoteGrid extends Serenity.EntityGrid<QuoteRow, any> {
        protected getColumnsKey() { return 'TDSINCQUOTESDB.Quote'; }
        protected getDialogType() { return QuoteDialog; }
        protected getIdProperty() { return QuoteRow.idProperty; }
        protected getLocalTextPrefix() { return QuoteRow.localTextPrefix; }
        protected getService() { return QuoteService.baseUrl; }
`
        public lastNewQuote = "";
        private _originalPager = $(".s-SlickPager");
        private _lastQuote: JQuery = $("<span><strong><span class='.customquoter-curquote' id='lastQuoteNumber'>Two</span></strong></span>");


        constructor(container: JQuery) {
            super(container);

            var qs = Q.parseQueryString();

            this._originalPager.find(".slick-pg-in").append(this._lastQuote);

         //   this._originalPager.find(".customquoter-curquote").text($(this._lastQuote).val());
            this._originalPager.find(".customquoter-curquote").text($("TEST").val());

        }

        protected onSaveSuccess(response: Serenity.SaveResponse): void {

            var latestQuote = "";
            // check that this is an insert
         //   if ( response.  this.isNew()) {
             //   Q.notifySuccess("Just inserted a category with ID: " + response.EntityId);

                // you could also open a new dialog
                // new MyProject.CategoryDialog().loadByIdAndOpenDialog(response.EntityId);

                // but let's better load inserted record using Retrieve service
                MyProject.QuoteService.Retrieve(<any>{
                    EntityId: response.EntityId
                }, resp => {
                    Q.notifyInfo("Looks like the Quote you added was: " + resp.Entity.Number);

                    latestQuote = resp.Entity.Number;
                });


            this._originalPager.find(".slick-pg-in").append(this._lastQuote);
 
            this._originalPager.find(".customquoter-curquote").text($(this._lastQuote).val());
            this._originalPager.find(".customquoter-curquote").text($("TEST").val());
  
        }

// other things that take lots of our time ..
}


```
