### ISSUE TITLE
Best way to reference Row Classes from another C# project/solution?

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#4663]
Hi there,

I made an API for my application and each API controller is outputting a json serialized response that contain lists of row objects. I am using Xamarin (different project and solution) to deserialize the response containing these objects and displaying them in the app. I imported the outputted dll from the Serenity project (.net core project btw) as an assembly dependency. This played nicely until a compile, in which the linker is trying to find the assemblies for the numerous assemblies Serenity uses (MVC nugets, etc). All I want to import from that project are those Row classes. What is the best approach for the issue I'm having? Last resort for me is copy and pasting each row class (without extending Row, IidRow, INameRow, etc) and whenever I change the Row class in the Serenity project, I proceed to change those classes in the Xamarin project. You can see why I want to avoid this as this create loads of redundancy.

Also: when I serialize my Row objects for the API, none of the properties from the parent class (Row) is included, which is what I want, so I have no need for anything Serenity related when I want to deserialize my response. I just want the data.

Best Regards,
Marcus

**Comment by volkanceylan** [comment]
Annotation type system, which is recently introduced might help. This is a sample from StartSharp, but should also work with Serene projects:

```cs
    /// <summary>
    /// This is annotation sample for OrderRow. Annotation types 
    /// are normally not required, and you could put these attributes
    /// directly on OrderRow properties, but such an annotation type
    /// lets you to move out UI specific dependencies from the row,
    /// so that you could move OrderRow itself into a separate 
    /// class library, e.g. a DLL with just the entities, if desired.
    /// </summary>
    [AnnotationType(typeof(OrderRow))]
    public sealed class OrderRowAnnotations
    {
        [CustomerEditor]
        public String CustomerID { get; set; }

        [LookupEditor(typeof(EmployeeRow))]
        public Int32? EmployeeID { get; set; }

        [LookupEditor(typeof(ShipperRow))]
        public Int32? ShipVia { get; set; }
    }
```

Remove any attributes from your row that introduces an extra dependency, and move them into this annotation class, then move your row class into a shared library.

This won't save you from all the dependencies. But Serenity.Core, Serenity.Data and Serenity.Data.Entity should be enough. They are basic libraries with not many dependencies (except System.Data etc.) so i guess they can be used with Xamarin.

Note that this is a very new feature, not throughly tested yet, and probably needs more docs / a blog post.

If you wanted to completely remove Serenity dependency, you would probably need some DTO generator, e.g. one that analyzes rows and creates dummy transfer classes corresponding to properties. I wrote one years ago it shouldn't be so hard, and there may be a third party ones. Another option is a fake Serenity Row layer you use only during Xamarin compile, but it would probably be harder.

**Comment by MarcusOy** [comment]
I found a somewhat viable alternative (someone please let me know if there are any negative serious implications). Instead of deseralizing the response from the API into their respective classes, I am deserializing them into a `new Dictionary<string, object>`, where string is the property name and the object seems to be automatically casted by Newtonsoft's JsonConvert into its correct format for primitive types at least. For a list, I deserialized it into a `new List<Dictionary<string, object>>`. Will close this issue for now until someone comes with any constructive feedback.

**Comment by juliermefelix** [comment]
@MarcusOy 
I'm trying to consume the Serenity Rows in an app with Xamarin, but I'm not getting it.
If you did it could help me. julierme@hotmail.com
