### ISSUE TITLE
SlickGrid: Change background color style instead class in getItemCssClass

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#4665]
Hi,

In XYZGrid, in method getItemCssClass, I would like to change background color with style tags, instead original klass.

I need to set background color according the rules of each row. These rules was defined by User, dinamically. So, I had 7 actives rules and 300 inactives rules. That's why I can't create css class in hard code.

So, how to do it?

**Comment by Febriantos** [comment]
Would you mind giving the expected result and the sample rules?

**Comment by volkanceylan** [comment]
I dont think its possible to set style rules directly on slick cell, as they may be reused for other rows / cells due to virtualization of slick grid. Classes are possible though, there is a slickgrid sample in its repo. You may remove padding from cell completely and add a intermediate div which you may apply styles on.

**Comment by rolembergfilho** [comment]
Hi Volkan and Febriantos.

The expected result is for each item in a collection I got the background color of this item.

so I need to set the background color ofthis row with this information.

it's because I got more than 300 hundred of items, each item with specific color.

I tried to create css in runtime, but it became heavy. That's why I think that it's the best solution to draw each background color with style.

**Comment by volkanceylan** [comment]
Sorry, AFAIK its not possible

**Comment by GersonTrigenius** [comment]
I know this is an old issue, but it was the most relevant result that I got when I was looking for this, therefore I assume more people might end up here and thinking there's no way to do it.
I got a way to make it work (in Serenity 3.14.4 on .NET Framework, yes it's an old version, but I'm basically not allowed to upgrade because it'll take too long, anyway, chances are this can still be done with newer versions).

Here's my sample class.
Tried to translate everything I thought was relevant to English, but I might've missed something.
`namespace FichaProjeto.Configuracoes.Assistentes.Propostas
{
	@Serenity.Decorators.registerClass()
	export class TduConfiguracaoAssistenteGrid extends Serenity.EntityGrid<TduConfiguracaoAssistenteRow, any> {
		protected getColumnsKey() { return 'Configuracoes.TduConfiguracaoAssistente'; }
		protected getDialogType() { return TduConfiguracaoAssistenteDialog; }
		protected getIdProperty() { return TduConfiguracaoAssistenteRow.idProperty; }
		protected getInsertPermission() { return TduConfiguracaoAssistenteRow.insertPermission; }
		protected getLocalTextPrefix() { return TduConfiguracaoAssistenteRow.localTextPrefix; }
		protected getService() { return TduConfiguracaoAssistenteService.baseUrl; }

		private readonly CSSDataRow: string = "DataRow";
		private readonly CSSItemId: string = "ItemId-";

		constructor (container: JQuery)
		{
			super(container);

			//Group by TipoPavimento //I left this here just to show it works even if you group the rows by some field, but it's not necessary
			this.view.setGrouping(
				[{
					formatter: x => 'Tipo de Pavimento: ' + (TriUtils.IsNullOrWhiteSpace(x.value) ? '*Sem Tipo de Pavimento definido*' : x.value) +
						' (' + x.count + ' Linhas)',
					getter: 'TipoPavimento'
				}]);

			//Custom background-color is lost when the columns are reordered, hence we repaint them
			this.getGrid().onColumnsReordered.subscribe(() => this.TryPaintRows(false)); //It works without a timeout

			//Resizing the windows removes the custom background-color of the last row for some reasone, so we repaint them
			addEventListener("resize", () => this.TryPaintRows(true)); //É preciso o timeout, senão a última linha é pintada e perde a cor logo a seguir outra vez
		}

		protected createView(): Slick.RemoteView<TduConfiguracaoAssistenteRow>
		{
			//This cover most scenarious were you need to repaint your rows, but not all, that's why we have those last 2 lines in the constructor
			let view = super.createView();
			view.onDataLoaded.subscribe(() => this.TryPaintRows(true)); //Timeout is needed because of some painting behaviour with "odd" and "even" rows

			return view;
		}

		//In my project, this event is being triggered hundreds of times (400+) at load. I don't know why this happens, it's important to use this override.
		protected getItemCssClass(item: TduConfiguracaoAssistenteRow, index: number): string
		{
			return this.CSSDataRow + " " + this.CSSItemId + item.Id; //Adicionam-se classes que não existem para depois se conseguir ir buscar as linhas facilmente e aplicar a cor certa
		}

		/**
		 * Try to paint rows based on the existing entities (TduConfiguracaoAssistenteRow)
		 * @param timeout Whether to apply a timeout before painting - necessary because some standard behaviours are applied after our event handlers, so we wait for them to finish and paint the rows after
		 * @returns
		 */
		private TryPaintRows(timeout: boolean): void
		{
			const rows = document.getElementsByClassName(this.CSSDataRow);
			if (rows.length == 0)
				return;

			const items = this.getItems();

			if (items.length == 0)
				return;

			//Even and odd classes are applied later automatically, the timeout will wait for that to finish before painting the rows
			//I know it's not a great solution, maybe there are better events or overrides to use to paint the rows, but for now this works
			if (timeout)
				setTimeout(() => this.PaintRows(items, rows), 500); //In case of failure, increase timeout duration...
			else
				this.PaintRows(items, rows);

		}

		/**
		 * Paint rows with classes this.CSSDataRow and this.CSSItemId based on the Color property of the corresponding TduConfiguracaoAssistenteRow
		 * @param items TduConfiguracaoAssistenteRows that have the color we'll use
		 * @param rows Rows to be painted
		 */
		private PaintRows(items: TduConfiguracaoAssistenteRow[], linhas: HTMLCollectionOf<Element>): void
		{
			//Remove "even" and "odd" classes from all data rows
			$("." + this.CSSDataRow).removeClass("even odd");

			let row: Element;
			let item: TduConfiguracaoAssistenteRow;
			for (let i = 0; i < rows.length; i++)
			{
				item = items[i];

				//Ignore entities without a Color defined
				if (TriUtils.IsNullOrWhiteSpace(item.Color))
					continue;

				row = this.GetFirstChild(rows, e => e.classList.contains(this.CSSItemId + item.Id)); //Here you can use something like row.getElementsByClassName() and just get the first element of the array.
				if (TriUtils.IsNullOrUndefined(row)) //In theory, there will always be a row with this class, but just in case there isn't, we skip avoid an error here.
					continue;

				//Finally apply the color
				$(row).css('background-color', item.Color);
			}
		}

		/**
		 * Get the first child element that meets a condition
		 * @param collection 
		 * @param action 
		 * @returns 
		 */
		private GetFirstChild(collection: HTMLCollection, action: (element: Element) => boolean): Element
		{
			for (let i = 0; i < collection.length; i++)
			{
				let element = collection[i];
		
				if (action(element))
					return element;
			}
		
			return null;
		}
	}
}`

It's not a pretty solution because it envolves a setTimeout and using non-existing classes, but it works and, maybe, it can be improved by someone with more knowledge, so I thought I should share it.
