### ISSUE TITLE
Update value

### ISSUE THREAD

**Issue by rahooftkh** [volkanceylan/Serenity#4667]
i want to update my products stock when complete create or update  process in order repository  how to manage this

**Comment by rcruzfalcon** [comment]
Hi @rahooftkh 
You can do it in the front (.ts) o back (.cs), like you like better.
In the front, you should send the update/create call to the ProductsService with the Entity after saveSuccess.
In the back, you override the method AfterSave in Order and put your update/create code here, inside the current Transactions. For me this is the best option.
best regards
Roberto
