### ISSUE TITLE
How to migrate from .NetCore 2.2 to .NetCore 3

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4673]

**Comment by JohnRanger** [comment]
@MaziarSangi ,

I suggest you don't until Volkan has upgraded SF to .NetCore3 :-)

Or you are on your own...

With kind regards,

John

**Comment by volkanceylan** [comment]
Yes i would wait :)

**Comment by abelal83** [comment]
Any eta when you may upgrade?

**Comment by yodiaz87** [comment]
Hello @volkanceylan, can I know when we can use StartSharp with .NetCore 3?

**Comment by volkanceylan** [comment]
There is already an upgrade guide, closing.
