### ISSUE TITLE
"~" character is not shown correctly in textbox (form)

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#4674]
When a user type "~" character in textbox, it shows as "-".
Is there anyway to fix it or is it a bug? 

![image](https://user-images.githubusercontent.com/25874638/67223741-72331c00-f3f5-11e9-9891-ebd09ee4dfe0.png)

**Comment by XDDDev** [comment]
@minhhungit Do you know how to fix it?

**Comment by minhhungit** [comment]
@XDDDev  change your font style

https://www.lifewire.com/change-fonts-using-css-3464229
