### ISSUE TITLE
Download Excel file on buttonclick from grid

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4675]
Hello everyone 
I want to download an excel file on button-click from the Grid.ts any suggestions?
(File is available on my content/site/images folder)

**Comment by luongnv6** [comment]
pls see
https://serenity.is/demo/Northwind/Order
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Order/OrderGrid.ts

thanks

**Comment by Shraddha996** [comment]
hello @luongnv6  Thnks for the quick response
But I want to download the template file of excel which will be useful to the Users for some reason
But ListExcel just download the grid data 
**I want simple code for download file which is present in the solution folders**
Hope this is enough explanation
Thanks in advance!

**Comment by JohnRanger** [comment]
@Shraddha996 ,

you just display them an "a href" to the relative path of the file. Then it should get downloaded automatically by the client's browser.

If you want to provide the file on click on a button, look up [this wiki article](https://github.com/volkanceylan/Serenity/wiki/File-Download-at-click-on-button).

there the file is just stored as a binary blob within the database but the general principle of providing a file on button click is still usable for your case.

with kind regards,

John

**Comment by Shraddha996** [comment]
@JohnRanger and @luongnv6  thanks for the replay! I got the answer
