### ISSUE TITLE
 Error occurs only when I publish the project - 404 error

### ISSUE THREAD

**Issue by viniciusmultiplice** [volkanceylan/Serenity#4676]
![image](https://user-images.githubusercontent.com/52297532/67284534-22fbf280-f4ac-11e9-8bf8-40fd49221359.png)

**Comment by viniciusmultiplice** [comment]
![image](https://user-images.githubusercontent.com/52297532/67313017-a59aa700-f4d8-11e9-9347-0d884aec29a4.png)

**Comment by CMIT-RomanP** [comment]
The same issue, after updates in a previously working project. What was the solution in your case?

**Comment by viniciusmultiplice** [comment]
The error happened in the project's Web.Config, just copy the web.config from your application and paste it into the web.config file generated when publishing. (translated by google translator)

**Comment by CMIT-RomanP** [comment]
Thank you for your answer, I already resolved. In my case it was more complicated, path="/DynJS.axd" in web.config should be on IIS 7 without slash, path="DynJS.axd", and similarly for errorlog.axd and upload.

**Comment by JohnRanger** [comment]
Hi @CMIT-RomanP ,

thank you :-) Removing the "/" did the trick.

It is very interesting, that in Visual Studio it works flawlessly - just on IIS 7.5 not.

Really appreciate your feedback here.

Regards,

John
