### ISSUE TITLE
How to toggle field based on options selected.

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4678]
I have three radio buttons based on ENUM with options from 1 to 3. When the radio button option is clicked i need the value updating in a textbox Score according to: 
Score textbox vlaue = ENUM1 * ENUM2 * ENUM3
When Score is over 8 want to make it visible :
                this.form.ExtraDesc.getGridField().toggle(true);

I have done this in afterLoadEntity:
            var mScore: number;
            mScore = (i * j * k);
            this.form.Score.value = mScore;

But doesn't work dynamically, have to save it first.
I tried making a function updateScore in EditDialog calling it when radio buttons are changed but it didn't work.

**Comment by haoas** [comment]
you can put function  updateScore in ondialogopen
