### ISSUE TITLE
GridUtils makeOrderable

### ISSUE THREAD

**Issue by fenixhoma** [volkanceylan/Serenity#4679]
Hi!
I found two functions in the serenity core in specific in the GridUtils, makeOrderable and makeOrderableWithUpdateRequest.
I need to apply both in a grid to make a sortable element in the grid, like a jQuery Sortable.
i need a example of implementation.

function makeOrderable(grid: Slick.Grid, handleMove: (p1: any, p2: number) => void): void; 

function makeOrderableWithUpdateRequest(grid: DataGrid<any, any>, getId: (p1: any) => number, getDisplayOrder: (p1: any) => any, service: string, getUpdateRequest: (p1: number, p2: number) => SaveRequest<any>): void;

**Comment by fenixhoma** [comment]
`function makeOrderable(grid: Slick.Grid, handleMove: (p1: any, p2: number) => void): void;
        function makeOrderableWithUpdateRequest(grid: DataGrid<any, any>, getId: (p1: any) => number, getDisplayOrder: (p1: any) => any, service: string, getUpdateRequest: (p1: number, p2: number) => SaveRequest<any>): void;`

**Comment by volkanceylan** [comment]
Those methods are for grid and there should be a sample in demo for that. Just use find reference or simple find.

**Comment by rcruzfalcon** [comment]
Hi @fenixhoma 

Here are the example:
https://github.com/mleibman/SlickGrid/blob/gh-pages/examples/example9-row-reordering.html

this apply to Serene would be like this (in the grid ctor):

`this.slickGrid.setSelectionModel(new Slick.RowSelectionModel());
                Serenity.GridUtils.makeOrderable(this.slickGrid, (rows: number[], insertBefore: number) => {
                    if (rows.length == 0) {
                        return;
                    }
                    let currentRow = Q.deepClone(this.itemAt(rows[0]));
                    let currentItems = this.view.getItems();
                    currentItems.splice(rows[0], 1);
                    currentItems.splice(insertBefore, 0, currentRow);                   
                    this.view.setItems(currentItems, true);
                });`

Best regards
