### ISSUE TITLE
Dialect

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#468]
![qq 20160328150814](https://cloud.githubusercontent.com/assets/6436116/14072882/f8b90962-f4f6-11e5-9b6a-473d485291c2.png)
Variables connect dialect 2005, but there are still CONCAT query sql function not found

**Comment by volkanceylan** [comment]
```
        [DisplayName("FullName"), Expression("CONCAT(T0.[FirstName], CONCAT(' ', T0.[LastName]))"), QuickSearch]
        public String FullName
        {
            get { return Fields.FullName[this]; }
            set { Fields.FullName[this] = value; }
        }
```

Search and replace these with +

**Comment by 107295472** [comment]
Expression("T0.[FirstName]+T0.[LastName]") ,thank you

**Comment by 107295472** [comment]
You write Serenity too good

**Comment by volkanceylan** [comment]
Serene has to support a variety of database engines, including MySQL, Postgress etc. These databases don't have a string plus (+) operator like MsSqlServer. Thus, in Northwind, CONCAT function is used in place of '+' operator:

```cs
[Expression("CONCAT(T0.[FirstName], CONCAT(' ', T0.[LastName]))")]
public String FullName
{
    get { return Fields.FullName[this]; }
    set { Fields.FullName[this] = value; }
}
```

CONCAT is available after Sql Server 2012. So if you are going to use an older version of SQL server, e.g. 2005 or 2008, replace these expressions with such:

```cs
[Expression("T0.[FirstName] + ' ' + T0.[LastName]")]
public String FullName
{
    get { return Fields.FullName[this]; }
    set { Fields.FullName[this] = value; }
}
```

Added this to guide, sorry i didn't understand problem at first.

**Comment by 107295472** [comment]
God

**Comment by 107295472** [comment]
I can not speak English,My fault

**Comment by volkanceylan** [comment]
No, it's fine. Not my native language either :)
