### ISSUE TITLE
Calling a Repository method without checking permissions

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4681]
By default calling the repository methods require the permission of logged in user. Which is fine while calling the repository from endpoints. But withing server-side code I want to ignore the permission checks.

`new MyRepository().Retrieve(connection, request);`

Is there any way to ignore the permission check for every repository call withing my server-side code?

I know `connection.ById(id)` does not require permission, but it does not load master-detail fields.

Something like the following will be great.
`new MyRepository(ignorePermissionCheck: false).Retrieve(connection, request);`

**Comment by volkanceylan** [comment]
You may use TransientGrantingPermissionService, or Impersonation system

**Comment by dfaruque** [comment]
Thank you. 

I have found detail about TransientGrantingPermissionService in this issue https://github.com/volkanceylan/Serenity/issues/1383
