### ISSUE TITLE
javascript in templated dialog with js bundling

### ISSUE THREAD

**Issue by YYOHAN** [volkanceylan/Serenity#4685]
Hi,
I have a dialog that extends Serenity.TemplatedDialog and I am able to open it and use a ...Template.html. but I have to include a particular js file in this Dialog ("Templated"). I would like to take advantage of the bundling capabilities of Serenity framework.

`@section Head { @Html.ScriptBundle("Pages/MyPageDefinedonScriptBundles") }`
How can I use a .cshtml with a TemplatedDialog?

I saw [https://github.com/volkanceylan/Serenity/issues/4079](4079)

**Comment by JohnRanger** [comment]
Hmm @YYOHAN ,

why do you not just add your js to the site section within scriptbundle.json under /Scripts/site/scriptbundle.json?

Then it is always available to any of your dialogs.

As you can see, even Volkan is not dividing the JS libraries more than into base, site and dashboard (and yeah - into the ckeditor also).

With kind regards,

John
