### ISSUE TITLE
Master-Detail; Updating Detail grid programmatically after adding detail row directly in Database

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4688]
Hi all,

I have a special workflow where the click on the add button within the detail grid does not open the standard detailDialog but it opens an intermediate dialog where a layout can be choosen and then the desired action (e.g. adding (=creating)) a new layout can be triggered.

**The workflow:**
![Issue-1](https://user-images.githubusercontent.com/2699447/67617029-5954ad00-f7df-11e9-8a27-d686d03a0aed.png)

This opens the layout dialog which is _not_ the detail dialog (explanation why this must be so see further below).

![issue2](https://user-images.githubusercontent.com/2699447/67617030-5e196100-f7df-11e9-92f1-14acfa4649a7.png)

**The problem:**
How to programmatically update the detail grid visualization / in-memory grid within the master dialog after the new link row has been added directly into the link table within the database.

![issue3](https://user-images.githubusercontent.com/2699447/67617113-0cbda180-f7e0-11e9-8966-a1f1cfe2a550.png)

**Desired outcome:**
The visual representation of the detail grid shows also the just added row - according to what is in the detail database table.

**The data structure:**
- Master is layoutset table
- Detail is link table between layoutset and layouts table
- Layouts table has nothing directly to do within master-detail but holds layouts

**The challenge:**
The record for the new layout is not (must not be) created as an in-memory row of the master-detail dialog but it is created in a different table (because there are multiple versions of a layoutset and potential multiple versions of a layout. therefore the details of a layoutset are in a link table between layouts and layoutsets). 

In the afterSave method which is called when a new layout is created, also a new entry in the link table between layoutset and layouts is created, so that a newly created layout is also automatically linked to the layoutset from where it was created. 

This additional link record should be displayed within the detail grid after the workflow is finished.

How can I refresh / update the detail list on the Layoutset master dialog without having to close/reopen the layoutset master dialog?

Any help would be deeply appreciated.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi all,

challenge solved. As it would take quite some time to document it here I will only do it on request.

Regards,

John

**Comment by kuyu7766** [comment]
how to do it  ? could you paste the code please?

**Comment by mohesa78** [comment]
@JohnRanger 
I am facing the same problem , please guide.
