### ISSUE TITLE
Export PDF with images.

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4690]
How to export the images present on the form created by multple image uploader.
Printing the window just writes the value contained in the DB.
I did some string manipulation to get just the file name.
Added them to  a Img src = "~/App_Data/upload/" + filenames
Not sure how to continue.

![image](https://user-images.githubusercontent.com/27406433/67779582-bf019d00-fa5c-11e9-86c8-328dbaa92141.png)

**Comment by AlexSoul1903** [comment]
Hello, how did you solve that?
