### ISSUE TITLE
CentOS7 & Nginx: 404 error on DynJS.axd

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4691]
Hi

I tried to make demo project to run on CentOS7 with Nginx reverse proxy. Page loads partly:
![image](https://user-images.githubusercontent.com/36483170/67782097-ba2df080-fa3e-11e9-8277-ada66aa1ae6e.png)

Problem is that DynJS.axd is not interpreted by Serenity, but NGinx thinks it a real folder on FS:

> open() "/home/nginx/domains/demodomain.com/public/publish/wwwroot/DynJS.axd/Form.Membership.Login.js" failed (2: No such file or directory)

any idea what could be the problem?

**Comment by abelal83** [comment]
Check that it's all in correct case as linux is case sensitive. I have serenity working on docker running inside kubernetes with nginx ingress with no issues.

**Comment by ga5tan** [comment]
thank you sir,
I am sure it is some small stupid thing.
so far nothing.
It seems like nginx is not passing DynJs.axd requests to Serenity OR Serenity is for some reason not thinking it's hers to take care of :(

I'll keep digging.
Can you please confirm there is still /DynJS.axd/ in path of most of the JS scripts ?
do you run with ScriptBundling on?

**Comment by kilroyFR** [comment]
> Check that it's all in correct case as linux is case sensitive. I have serenity working on docker running inside kubernetes with nginx ingress with no issues.

Would love to get infos on this. Trying myself to move from windows to Linux. Guess you are using .NetCore ?

**Comment by ga5tan** [comment]
yup, .NetCore
casing (at least DynJs.axd seems to be ok.
I dont really know what to check next :(

this is what browser wants
https://demo.com/DynJS.axd/ColumnsBundle.js?v=SzOiiPFBdH1qh-GtH3dIdw
but somehow middleware in Serenity wont deal with it and nginx is trying to find it on disk

**Comment by abelal83** [comment]
> > Check that it's all in correct case as linux is case sensitive. I have serenity working on docker running inside kubernetes with nginx ingress with no issues.
> 
> Would love to get infos on this. Trying myself to move from windows to Linux. Guess you are using .NetCore ?

Happy to help.  I'm running in kubernetes/docker and correct dotnet core.

**Comment by abelal83** [comment]
> thank you sir,
> I am sure it is some small stupid thing.
> so far nothing.
> It seems like nginx is not passing DynJs.axd requests to Serenity OR Serenity is for some reason not thinking it's hers to take care of :(
> 
> I'll keep digging.
> Can you please confirm there is still /DynJS.axd/ in path of most of the JS scripts ?
> do you run with ScriptBundling on?

Script bundling is off. Have you tried exposing kestrel directly so go direct without nginx as a test?

**Comment by JohnRanger** [comment]
Hi @ga5tan ,
from the symptoms you describe it looks like nginx is not passing the request to the kestrel backend but tries to get it on its own from the disk.

Therefore it makes total sense what @abelal83 suggests - to temporarily bypass nginx and see if kestrel would do the right thing. If yes, then the problem lies in nginx and/or its configuration.

Probably you had already followed these steps over here - but if not - give them a look: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?highlight=nginx&view=aspnetcore-3.0

With kind regards,

John

**Comment by ga5tan** [comment]
It seems that app is working fine on 5000
so it will be probably reverse proxy setup that's causing the issues.

Thx for link, I followed similar, but this seems more complex, so I  will give it a try
