### ISSUE TITLE
Product Picker Dialog Sample Missing from Guide

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4693]
@volkanceylan @BobMunn
I was reading the Guide (I know an oddity) however I got to a point where I found The [Product Picker Dialog ](https://volkanceylan.gitbooks.io/serenity-guide/startsharp/features/product-picker-dialog.html)

I thought this would work great for adding items to an order etc.. and it had a thanks to Bob Munn for sharing it, but no code :-(  .  Does anyone out there have a copy of that code?

**Comment by haoas** [comment]
you need to buy  premium packages which includes StartSharp template with additional samples, features and modules.

**Comment by stixoffire** [comment]
Ok thanks - I would that the guide stated that - so I would know the difference. When it stated donated by Munn - I was thinking it was in the open source side.

**Comment by gfo2007** [comment]
@stixoffire please were you able to implement the Product Picker logic? If yes, could you share your code?

**Comment by stixoffire** [comment]
@gfo2007 I don't have the premium progress so I have not done this.
