### ISSUE TITLE
Conditional Formatting Helper - Key or Legend for colors 

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4694]
Hi,
Many thanks for this awesome framweork!
Mangaed to do conditional formatting on the editor of detail grid. 
Just wondering if there is any existing function to put the colors used in to a legend for the user to easily understand.

**Comment by minhhungit** [comment]
Just create a column formatter like you did on main grid, they are same

You can find formatter sample code on wiki, serenity demo code or serenity  docs

Sorry I am on phone so can not give you the code

**Comment by judejay** [comment]
Is there a way of using  [InlineImageFormatter] on grid? Not on the columns but in the dialog. Or removing the buttons?
![image](https://user-images.githubusercontent.com/27406433/67946592-918e2e00-fbd9-11e9-8e3c-c98c8e778ec1.png)
I will just set that column to have a default value of the filename.

**Comment by judejay** [comment]
![image](https://user-images.githubusercontent.com/27406433/67956717-77118000-fbec-11e9-9467-b0fa122581b4.png)
Updatable false. All I could do.

**Comment by stixoffire** [comment]
@judejay if you had a datatable with your static image in it - I would just do a join on the static image or pull it in dring retrieve as an UnMapped column .
table StaticImages
Id, ParamName, Image 

Id is identity and Primary Key, ParamName = MyGroupLegend, Image = Legend.  
Your main table of course would require that Legend Column Index  or you could simply add the unmapped column and pull it in during Retrieve ..
Then you get rid of the ugly Select File as well ..
