### ISSUE TITLE
How to make a condition when create a foreign key

### ISSUE THREAD

**Issue by Mondaii** [volkanceylan/Serenity#4695]
I have a grid that show some values from a foreign key contas pagar, and i have another foreign key called contas receber that have almost the same fields and i want to show these value on my grid. Something like if contas receber == null show contas pagar value and if contas pagar == null show contas receber.

**Comment by stixoffire** [comment]
onCriteria is what you might be looking for - check examples in the guide for Joins ("T0.Field ==")
Now if you are intending to join table x if receber = null this or table y if pagar == null  - that is a different thing and you probably should look at your design

**Comment by Mondaii** [comment]
![serenity](https://user-images.githubusercontent.com/50410459/68027418-15572180-fc91-11e9-8a80-f6c74166bb71.PNG)
basically i need the marked collumn to come from contaspagar or contasreceber depending on which tables has a value.
