### ISSUE TITLE
Having a Calculated Column in Editable Grid

### ISSUE THREAD

**Issue by MagDev175** [volkanceylan/Serenity#4696]
I'd like to have a calculated column in the editable grid (eg price+quantity = cost).  I'd want it to update before save on inputs change when any of the component parts change.  I'm trying to implement this in the inputs change class but I can't seem to set the cost column.  I've read through the slick grid documentation and it should be item['Total'] = price + cost.  

Does anyone know how I can go about doing this?

**Comment by haoas** [comment]
`this.form.Total.value=this.form.price .value+this.form.cost.value`

**Comment by MagDev175** [comment]
@haoas It's in a grid not a form.

**Comment by haoas** [comment]
`var cell = this.slickGrid.getCellFromEvent(e);
            var item = this.itemAt(cell.row);
            item.Total = item.price+item.cost;
            this.getGrid().updateRow(cell.row);`

**Comment by MagDev175** [comment]
@haoas Thank you.  It's so easy.  I think I was missing: this.getGrid().updateRow(cell.row);

**Comment by minhhungit** [comment]
I know you closed this issue, just note for dev


this might be also a good sample http://mleibman.github.io/SlickGrid/examples/example-totals-via-data-provider.html
