### ISSUE TITLE
Refresh Master Detail Grid on close Dialog

### ISSUE THREAD

**Issue by fenixhoma** [volkanceylan/Serenity#4697]
Hi !

I modify the methods to save and update directly to the database in mi EditorDialog, the problem is when I close the dialog (create or update) the grid not refresh the data and not show the new row inserted.
I need to refresh the grid with the data in the database

thanks!

**Comment by minhhungit** [comment]
This case I think you have to read tutorial first, the tutorial explained it very detail 
Grid editor is in-memory data so you can not call something like "refresh grid"

Check tutorial here: https://serenity.is/docs/tutorials/movies/the_cast_and_characters_they_played

**Comment by JohnRanger** [comment]
Hi @fenixhoma .
this is possible but you have to programatically update the editor/grid.

I do it like this:

Within the xyzEditorDialog (the "Dialog"), I create a public variable of type xyzEditor.ts (the "Grid"). This is used to pass a reference of the grid to the Dialog when the dialog is created within xyzEditor.ts (the "Grid") (so we can later call a method on the grid to update itself).

```ts
.
.
                       export class ChainSpanningLayoutSetsDetails_Layouts_AddDialog extends                       Serenity.EntityDialog<ChainSpanningLayoutsRow,any> {
.
.
                            public EditorObject: ChainSpanningLayoutsDetailsEditor;
.
.
```

Then in the xyzEditor.ts (the "Grid") - after you create the xyzEditorDialog but before you open it - you pass a reference of the current xyzEditor.ts (the in-memory grid) to the xyzEditorDialog - like this:

```ts
                       var addDialog = new ChainSpanningLayoutSetsDetails_Layouts_AddDialog(); // *** Create dialog ***

                       // *** passing a reference from grid to dialog ***
                        addDialog.EditorObject = this;

                        //// *** Open the dialog ***
                        //addDialog.dialogOpen();
```

Now - within the xyzEditor.ts (the "Grid"), you create a new public method like this:
```ts
public ShowInsertedRow(LinkTableInsertedId : number) {

            Q.reloadLookup('ChainSpanningLayouts.ChainSpanningLayoutSetsDetails_Layouts');
            var row = ChainSpanningLayoutSetsDetails_LayoutsRow.getLookup().itemById[LinkTableInsertedId];

            var id = this.id(row);
            if (id == null) {
                (row as any)[this.getIdProperty()] = this.getNextId();
            }

            var items = this.view.getItems().slice();
            if (id == null) {
                items.push(row);
            }

            this.setEntities(items);

        }
```

Please note that I pass here the ID of the just inserted record from the DB. You have to retrieve this by yourself. Also I refresh the lookup for the table where the new record has been inserted and I pull all neccessary data for displaying the new row from this lookup. With this.setEntities() all rows are pushed to the grid. 

Now - in your xyzEditorDialog.ts (the "Dialog") you add the following:

```ts
        protected onSaveSuccess(response) {

            // *** Debug only ***
            //alert(response.LinkTableInsertedID);

            this.EditorObject.ShowInsertedRow(response.LinkTableInsertedID);    // *** Call the method in the grid via reference to show new row within detail grid editor ***

        }

```

Please note that in my case, the onSaveSuccess method is within a completely different dialog type - one from a normal grid which directly saves to database via xyzEndpoint.ts.  And I also have modified the server-side to return the inserted record's new ID which I retrieve from response.

This you have to implement yourself as you situation here is a bit different. But you should get the basic idea.

Hope this helps.

With kind regards,

John
