### ISSUE TITLE
Pull through string alias on detail editor

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4698]
Hi,

I want to show an alias instead of the string value only in the details grid of the details editor. Such as:

```
Select  
    Case 
        When LongString is NULL  Then '' ELSE 'Completed' 
    End 
From dbo.MyTable
```

Tried a filter in DetailEditor.ts, but only returns the row where it is true or not.

Been searching on how to do this, but only seen an example that I don't quite understand in GitBook
under "Criteria Objects"  > Usage with Field Objects. 
 ```
query.Where(
        o.CustomerCountry == "France" &
        o.ShippingState == 1 &
```

Translate to :

```
WHERE 
    o_c.[Country] = @p2
    AND (CASE WHEN 
        o.[ShippedDate] IS NULL THEN 0
     ELSE 1 
```

**Comment by minhhungit** [comment]
I think you can use [Expression("case when ...")] on your field on your Row.cs

**Comment by judejay** [comment]
I have done this:
  [Expression("Case WHEN T0.[LongString] is NULL THEN 'Required' ELSE 'Complete' END")]
On the details row, but on the Detail editor is still the same, only working on its own page's columns, but these are not used. Same expression on the Detail column doesn't work.
