### ISSUE TITLE
xyzDialog; Toolbars within categories

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4699]
Hi all,

I am currently using the programmatic hiding and showing of categories within a dialog as a kind of wizard.  This works really great and gives a nice top-down workflow - except that I am currently not able to add a specific toolbar to within a category.

That means that I have to put all possible buttons of all wizard steps within the main toolbar (which I have placed with the help of the xyzDialog.template.html at the bottom of the dialog) and hide/show these buttons according to which category is currently shown (means: which step in the wizard is currently active).

**Question:**
Is there a relatively simple way to add an additional toolbar like the main toolbar at the bottom of a category?

If yes, how? :-)

Thanks for any help and

with kind regards,

John

**Comment by RKayCH** [comment]
The Movie Tutorial could help, as it covers the Templating system - which is - what I would use for these requirements. 

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/listing_movies_in_person_dialog.html

**Comment by JohnRanger** [comment]
Hi @RKayCH ,
thanks for your feedback. I am already using the template to put the toolbar at the bottom of the dialog. But how to add another - similar - toolbar at the bottom of a category this I don't know. Can you please elaborate a bit on that?

With kind regards,

John

**Comment by JohnRanger** [comment]
not solved - but long time no answer.

Closing this therefore.

John
