### ISSUE TITLE
Tab/New Entity behaviour since 1.6.5?

### ISSUE THREAD

**Issue by stickybro** [volkanceylan/Serenity#47]
Hi Volkan :)

I'm sorry but I'm not sure if an update broke things... I was developing on 1.6.4 on Friday and then updated this morning when VS said there were updates available.

Since then the Add New behaviour on tab pages seems to open a new master page instead of a new detail page?

For example in Customer --> Edit Customer(CustomerName) --> Orders Tab : when you click "New Order", the New Order dialog opens with OrderForm on a "Customer" tab and a blank "Orders" tab and the New Order Detail does the same thing.

![customers](https://cloud.githubusercontent.com/assets/15202893/11173783/7fe02316-8c7f-11e5-8f0d-0fa9a26ce997.png)

Is this a bug or did I break it :)

Thanks s

**Comment by volkanceylan** [comment]
You didn't break it, i did. Recently i changed template name determination algorithm in TemplatedWidget but did a very wrong usage of a static variable. 

Thanks for reporting. Think i need more tests and more coffee. Fixed in 1.6.7

**Comment by stickybro** [comment]
lol next time I'll get you the coffee :)
