### ISSUE TITLE
Use jquery UI Spinner in serenity

### ISSUE THREAD

**Issue by fenixhoma** [volkanceylan/Serenity#4700]
Hi 
I am working with a serenity form and a try to add a jQuery method "Spinner" y tried in two different ways but doesn't work 

`$("#Number").spinner();`

`this.form. Number.element.spinner({
                spin: function (event, ui) {
                    alert(ui.value);
                    }
            });`

in those case the answer is the same 

**TypeError: $(...).spinner is not a function**

Thanks!

**Comment by volkanceylan** [comment]
jQuery UI that is used contains a subset of widgets, it might not contain that spinner as we are using pace.js, in that case you should use the full jquery ui script, like jquery-ui-1.12.1.js not jquery-ui.js.
