### ISSUE TITLE
Misspelling Message, work "occured" should be "occurred"

### ISSUE THREAD

**Issue by inzare** [volkanceylan/Serenity#4701]
In the file Serenity.Web\Mvc\EndpointExtensions.cs on line 51 the following line of code has a misspelling:
error.Message = "An error occured while processing your request.";

It should be:
error.Message = "An error occurred while processing your request.";

**Comment by volkanceylan** [comment]
Thanks, a6a025019fdebb36565db6e8ff80e185ccb60f2c
