### ISSUE TITLE
'No service for type 'Serenity.Data.IAuditLogRow' has been registered.' in Aspnet Core project

### ISSUE THREAD

**Issue by cengkaplan33** [volkanceylan/Serenity#4703]
when i used AuditLog attribute on XYZrow , system give me that error. bu I havent AuditlogService it is in the base  so how can I register that service for IAuditLogRow. 
Is there any solution ?

![image](https://user-images.githubusercontent.com/3457947/68128836-87499800-ff29-11e9-8a42-220e876fac23.png)

**Comment by lechu90ns** [comment]
The solution is simple. Create data table in your database, generate the code via "dotnet sergen g", add "IAuditLogRow" interface to your new Row class then you need to register it in your IoC.

`public sealed class AuditLogRow : Row, IIdRow, INameRow, IAuditLogRow`

\YourProject.Web\Initialization\Startup.cs, in 
`void ConfigureServices(IServiceCollection services)` 

add
`services.AddTransient<IAuditLogRow, AuditLogRow>();`

What columns you need, you may ask. You need to match to IAuditLogRow interface and it looks like this:
https://github.com/volkanceylan/Serenity/blob/48b7a2135311123f6876b45a553b77b3e8833315/Serenity.Services/RequestHandlers/IntegratedFeatures/AuditLog/IAuditLogRow.cs

In my case it looks like that:
`StringField IAuditLogRow.EntityTypeIdField => Fields.EntityTableName;
        Int64Field IAuditLogRow.EntityIdField => Fields.EntityId;
        StringField IAuditLogRow.ParentTypeIdField => Fields.ForeignTableName;
        Int64Field IAuditLogRow.OldParentIdField => Fields.OldParentId;
        Int64Field IAuditLogRow.NewParentIdField => Fields.NewParentId;
        DateTimeField IAuditLogRow.DateField => Fields.LogData;
        IIdField IAuditLogRow.UserIdField => Fields.UserId;
        Int32Field IAuditLogRow.AuditTypeIdField => Fields.LogType;
        StringField IAuditLogRow.OldAuditDataField => Fields.OldValue;
        StringField IAuditLogRow.NewAuditDataField => Fields.NewValue;`

**Comment by lechu90ns** [comment]
Otherwise you would need to buy StartSharp package where it is customized more and works better than OTB Serenity one.

**Comment by haoas** [comment]
there are two examples.one is
 `  public sealed class ProductLogRow : Row, ICaptureLogRow
{}`
`[CaptureLog(typeof(ProductLogRow))]
    public sealed class ProductRow : Row, IIdRow, INameRow` .
   You can find this example as part of the Northwind examples. another is [Audit-Log-for-Insert-Update-and-Delete-using-Single-Table](https://github.com/volkanceylan/Serenity/wiki/Auditing:-Audit-Log-for-Insert-Update-and-Delete-using-Single-Table)，you can find it in wiki.But in asp.net core project ,we need to do sth, inject a static Microsoft.AspNetCore.Http.HttpContext in the startup class.

**Comment by cengkaplan33** [comment]
thanks you guys. It will be so helpfull. I solved my problem.
