### ISSUE TITLE
Is it possible to use FileDownloadFormatter with MultipleFileUploadEditor??

### ISSUE THREAD

**Issue by Mondaii** [volkanceylan/Serenity#4709]
I'm trying to use MultipleFileUploadEditor with FileDownloadFormatter  without any sucess, is there a way to do it?

**Comment by volkanceylan** [comment]
No, you would need to write a custom formatter, the string in the multiple file upload data is a JSON string like [ { filename: 'sdasdasd', originalName: 'asdadad' } ], you need to parse the json and do it similar to FileDownloadFormatter but for multiple files.

**Comment by Mondaii** [comment]
thank you, i did that and worked fine.
