### ISSUE TITLE
Using a RESTful API

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#471]
I have replaced the Endpoint calls with calls to a RESTful API.  Lists and Dialogs populate correctly with the data but fields with using a LookupEditor retrieve data from the database.  Where does a LookupEditor make database calls?  How can I update it to use the RESTful API?

Thanks

```
public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
{
#if USE_RESTFUL_SERVICE
           return MyApi.List(connection, request);
#else
           return new MyRepository().List(connection, request);
#endif
}
```

**Comment by volkanceylan** [comment]
It's not easily possible to intercept their calls. But you may remove LookupScript attributes from rows. Then write your custom lookup scripts, by deriving from Serenity.Web.LookupScript, and passing your delegate function that returns a list of rows, by calling your REST service.

**Comment by volkanceylan** [comment]
You also need to set LookupKey, IdField and TextField properties at minimum in constructor.

**Comment by brettbeard** [comment]
Is there an example of deriving from Serenity.Web.LookupScript in Serene by any chance?

**Comment by volkanceylan** [comment]
No, see Serenity code for others

**Comment by 107295472** [comment]
join  web api

**Comment by teafmartins** [comment]
HI @brettbeard , can you share and example of your MyApi.List ? 
Thank You
