### ISSUE TITLE
nuget packages to upgdrade

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#4710]
Hi,
i have installed the latest version of Serene Template (v. 3.9.10.0) and create the project.
I noticed though that the Serenity packages are to be updated, see image.
it's normal?
Thanks
![immagine](https://user-images.githubusercontent.com/15787703/68236371-52ab0e80-0005-11ea-907f-459e743ab8f2.png)

**Comment by Garozh** [comment]
Latest version is 3.9.11.

See [https://github.com/volkanceylan/Serenity/blob/master/CHANGELOG.md]

**Comment by linpiero** [comment]
Thanks for the reply.
Then the template should be updated because it has remained at version 3.9.10.0
(Https://marketplace.visualstudio.com/items?itemName=VolkanCeylan.SereneSerenityApplicationTemplate)

**Comment by ga5tan** [comment]
good one.
who's gonna do it?

**Comment by volkanceylan** [comment]
Template doesn't have to always have the latest version of Serenity, you may update Serenity anytime you like

**Comment by linpiero** [comment]
ok!!! tks
