### ISSUE TITLE
[Proposal] Delete button on entity dialog should be hidden if user does not have Delete permission

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4714]
Currently if user does not have Delete permission and click on Delete button, it will throw an error message, I think we should hide the button.

Consider Create New/Save/Localization/Clone button as well.

**Comment by minhhungit** [comment]
btw consider to update Sergen to generate PermissionKeys for client side (typescript) so we can use it strongly-type, for example:

```javascript
Q.Authorization.hasPermission(PermissionKeys.Product_Delete)
```

**Comment by dfaruque** [comment]
I am also thinking about this.

**Comment by volkanceylan** [comment]
Yes, i am also planning to add permission keys to the row, like SomeRow.insertPermission etc, and also generate a per module permission key class in TS, then use such information in a method like getAddPermission(), getDeletePermission() in grid/dialog similar to other methods

**Comment by mreid2005** [comment]
Funny enough 2 years after deploying our in-house app I have had this come up three times in the last two weeks by my co-workers.

**Comment by volkanceylan** [comment]
Ok, first step is done, 867fae09e35e6d66449b142cc17e32644d6004eb

**Comment by volkanceylan** [comment]
3.9.13 has this implemented.

**Comment by minhhungit** [comment]
Many thanks @volkanceylan I tried to upgrade serenity and it works very good
I see that it will disable buttons (not hide it) but it's okay
