### ISSUE TITLE
Retrieve instance of a dialog from another dialog.

### ISSUE THREAD

**Issue by magno193** [volkanceylan/Serenity#4715]
Hello, does anyone know how I could retrieve an instance of a dialog already opened in another dialog or update a dialog box field in addition to another dialog box?

Thanks in advance.

**Comment by hubeyb** [comment]
You may read this [article ](https://serenity.is/demo/BasicSamples/FilteredLookupInDetailDialog#)
[and this typecript code](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Editors/FilteredLookupInDetail/FilteredLookupDetailEditor.ts)

You can pass your data through initEntityDialog method like below.

```
 protected initEntityDialog(itemType: string, dialog: Serenity.Widget<any>) {
            super.initEntityDialog(itemType, dialog);

            // passing category ID from grid editor to detail dialog
            (dialog as FilteredLookupOrderDetailDialog).categoryID = this.categoryID;
        }
```

**Comment by magno193** [comment]
Thank you for your help, i was able to solve my problem with the solution bellow:

>                     onClick: () => {
>                         var dlg = new ClinicaBeta.WebCamDialog();
>                         dlg.PacienteDialog = this;
>                         dlg.dialogOpen();
> 
>                         dlg.element.one("dialogclose", () => this.Atualiza());
>                     }
