### ISSUE TITLE
Using newer Fontawesome version than 4.70?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4717]
Hi all and @volkanceylan ,

as there are many nice new icons in fontawesome versions newer than the 4.7.0 of SF (visible on their website),  how can these newer fonts be used / installed within Serenity? 

If I download the free FA file, I see there basically 3 groups of font files:

- brands
- regular
- solid

Looks like FA has splitted the one font file of V4.7.0 into 3 separate icon groups.

Actually I would like to just add these newer FA versions to the existing FA 4.7.0 icons and just map missing icons into Serenity.

Is this possible and if yes - how can this be done?

**What I already have tried:**

- Copied all the fonts from the /webfonts/ directory of the Zip-File for FA-V5.11.2 from FA to the SF project's /fonts dir
- copied the all.css file from the same zip file to /Content/
- Replaced the font path within the all.css file from ../webfonts/... to ../fonts/
- Referenced the all.css file directly before the already existing font-awesome.css in CssBundles.json like this: 
```json
"Base": [
    "~/Content/font-open-sans-base64.css",
    "~/Content/all.css",              /* Load V5.11 before */
    "~/Content/font-awesome.css",     /* existing V4.7.0 */
    "~/Content/bootstrap.css",
    "~/Content/css/select2.css",
    "~/Content/pace.css",
    "~/Content/toastr.css",
    "~/Content/slick.grid.css",
    "~/Content/serenity/serenity.css",
    "~/Scripts/vegas/vegas.css"
  ],
```
- Tried to use such a new icon (fa-shipping-fast - https://fontawesome.com/icons/shipping-fast?style=solid) by using: ```[assembly: NavigationMenu(NavItems.Realtime, "Realtime", icon: "fas fa-shipping-fast")]```.

I have also followed this SO article here: https://stackoverflow.com/questions/47712987/font-awesome-5-on-pseudo-elements

and this one: https://stackoverflow.com/questions/49467856/font-awesome-4-and-5-in-same-page

Unfortunately, the Corresponding menu entry only shows a small square instead of the desired icon.

Any help would be greatly appreciated.

With kind regards,

John

**Comment by fabio-luiz** [comment]
Actually, it's much easier to add the newest Font Awesome package using a provider like cdnjs or similar. But first, delete the old version of FA that you have in your project (the webfonts, the css, the reference in CssBundles.json, all of it). Then, add the current version of FA using your favorite method. Then, reference these files into your CssBundles.json file:
`    "~/Content/font-awesome/css/all.css",
    "~/Content/font-awesome/css/svg-with-js.css",
    "~/Content/font-awesome/css/v4-shims.css",` 

all.css is your main FA file, svg-with-js.css serves, as the name implies, if you want to render the SVG files with JavaScript. And v4-shims.css helps if you used (as Serenity and AdminLTE did) older versions of FA in your project, which contained some icon references that may have changed or deprecated, and replaces them with the current references compatible with FontAwesome v5+ so you don't have to manually search and dig for every reference in your source code that may point to nothing at all or show a different icon than the one you actually want.

Naturally, a css file wouldn't do that without a corresponding js file to help, so in ScriptBundles.json, in the Base bundle, add:
`    "~/fonts/font-awesome/js/all.js",
    "~/fonts/font-awesome/js/v4-shims.js",`

This will add the current version of Font Awesome, which suffered quite a change from v4 to v5 and these steps are actually very recomended if you want to keep up.

Now, if you just do that and build your project, you will notice some issues, specially in the sidebar and the header, like the sidebar-toggle is missing, the arrows in the sidebar menus are huge, etc.. To fix those, go to the corresponding .less files (sidebar.less and header.less to name  a few), and change the font-family attribute from fontAwesome (or something like that) to 'Font Awesome 5 Free', set font-weight to 900. Example (in header.less):
`  //Navbar toggle button
  .sidebar-toggle {
    float: left;
    background-color: transparent;
    background-image: none;
    padding: @navbar-padding-vertical @navbar-padding-horizontal;
    //Add the fontawesome bars icon
      font-family: 'Font Awesome 5 Free';
      font-weight: 900;
    &:before {
        content: "\f0c9";
    }
    &:hover {
      color: #fff;
    }
    &:focus,
    &:active {
      background: transparent;
    }
  }`

In the case of the arrows in the sidebar, in sidebar.less, set the width attribute in the fa-angle-left item to .5em, like this:
`  li > a > .fa-angle-left,
  li > a > .pull-right-container > .fa-angle-left {
    width: .5em;
    height: auto;
    padding: 0;
    margin-right: 10px;
  }`
and
`  // Tree view menu
  .treeview-menu {
    display: none;
    list-style: none;
    padding:0;
    margin:0;
    padding-left: 5px;
    .treeview-menu {
      padding-left: 20px;
    }
    > li {
      margin: 0;
      > a {
        padding: 5px 5px 5px 15px;
        display: block;
        font-size: 14px;
        > .fa,
        > .glyphicon,
        > .ion {
          width: 20px;
        }
        > .pull-right-container > .fa-angle-left,
        > .pull-right-container > .fa-angle-down,
        > .fa-angle-left,
        > .fa-angle-down {
          width: .5em;
        }
      }
    }
  }`

this should fix the size of the submenu arrows.

Set the font-family and font-weight attributes in the items in serenity.css that use old FontAwesome references and you won't worry about FA anymore.

**Comment by JohnRanger** [comment]
Hi @fabio-luiz ,

wow - great description. Makes totally sense and I will try that out ASAP and give feedback here. Would also make up a nice wiki entry :-)

With kind regards,

John

**Comment by volkanceylan** [comment]
Thanks for instructions. I think migrating to FA5 does not bring much unless you are going to buy premium set.
