### ISSUE TITLE
How to configure two different dialogs for the grid

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4719]
Hello,
I want to open a two different dialogs for single grid, ie on button click i want to open one dialog and on edit link click i need to open a different dialog
![Image](https://user-images.githubusercontent.com/28822452/68582887-cfc10280-04a1-11ea-882e-564226e86197.png)

**Comment by haoas** [comment]
override additem and edititem

**Comment by flextrio-gandhi** [comment]
we are adding a button in the grid which should open a new dialog and the edit link should open another dialog for the same grid.    
can you please elaborate how to override additem and edititem to achive the above task

**Comment by minhhungit** [comment]
@flextrio-gandhi check this demo

https://serenity.is/demo/BasicSamples/InlineActionButtons

![image](https://user-images.githubusercontent.com/2279508/68585912-13be0280-04b6-11ea-8e98-ca34683ee016.png)

**Comment by minhhungit** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons/InlineActionGrid.ts#L74-L80

**Comment by minhhungit** [comment]
https://github.com/volkanceylan/Serene/blob/7544f351a3373741949c56081fd18fba4034aa65/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons/InlineActionGrid.ts#L74-L80

**Comment by hubeyb** [comment]
[https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/CustomLinksInGrid/CustomLinksInGrid.ts](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/CustomLinksInGrid/CustomLinksInGrid.ts)
