### ISSUE TITLE
The type of failure

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#472]
![qq 20160329092528](https://cloud.githubusercontent.com/assets/6436116/14095188/3b3df696-f590-11e5-9785-e311c0dff07f.png)
![qq 20160329090206](https://cloud.githubusercontent.com/assets/6436116/14094886/fff934cc-f58c-11e5-9be8-968f42197c96.png)

**Comment by 107295472** [comment]
Other places can, on the Users table can not

**Comment by volkanceylan** [comment]
((Field)insertLogRow) should be ((Field)insertLogRow.InsertUserId)

Where is this code

**Comment by 107295472** [comment]
![qq 20160329104406](https://cloud.githubusercontent.com/assets/6436116/14096408/30326a38-f59b-11e5-99cd-56d81fbdd814.png) Serenity.Services

**Comment by 107295472** [comment]
You want to change the primary key type,int to string guid

**Comment by 107295472** [comment]
override  SetInternalFields    Is assigned a value

**Comment by 107295472** [comment]
There is no way, can not find where the error

**Comment by volkanceylan** [comment]
Update to 1.9.26

**Comment by 107295472** [comment]
ok
