### ISSUE TITLE
[InplaceAdd] throws error: Cannot find xyz dialog class

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4722]
Hi all,

recent project (V3.9.6 based) where I have added the InplaceAdd tag to a specific field.

When I click on this add button, a typescript error message appears and says that the xyz dialog class could not be found.

If I also add the tag DialogType = <myProject.Namespace>.xyz then it works.

Hint: xyzDialog.ts is generated with sergen 3.0.2 (as this is the last sergen version which creates the very nice partial class RowFields).

Is this a known problem?

With kind regards,

John

**Comment by hubeyb** [comment]
Could you have written the dialog under the wrong module or namespace?
please check this. 
if namespaces or modules are different, most probably serenity's default InplaceAdd decleration can not reach the dialog.

**Comment by fremar83** [comment]
I just had the problem. It was only due to a specific lookup. I only had to inform my dialogType

        [LookupEditor(typeof(ResidentNomCompletLookup), InplaceAdd = true, DialogType = "Residents.Resident")]
