### ISSUE TITLE
How to custom display on Slickgrid?

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4724]
Hey Guys!

Has anyone tried to apply an alternative display to slickGrid in Serenity?

Here is the example:
https://mleibman.github.io/SlickGrid/examples/example8-alternative-display.html

Thanks!

**Comment by minhhungit** [comment]
@lechu90ns  Serenity has a demo like that at [here](https://serenity.is/demo/BasicSamples/VSGalleryQA)
Unlucky, the demo page does not work at this time

But you can review its code, it will work for you

https://github.com/volkanceylan/Serene/blob/7544f351a3373741949c56081fd18fba4034aa65/Serene/Serene.Web/Modules/BasicSamples/Grids/VSGalleryQA/VSGalleryQAGrid.ts#L22-L46

**Comment by lechu90ns** [comment]
Thank you for your point! closing
