### ISSUE TITLE
Auto generate value 

### ISSUE THREAD

**Issue by nazrulbspi5** [volkanceylan/Serenity#4726]
hi, 
I want to auto-generate value and save to database when clicking the save button, remember that field is hidden.

**Comment by JohnRanger** [comment]
in your xyzRepository.cs in the MySaveHandler, override the beforeSave() method.

You can access the current row which is in progress to be saved just before it is actually been saved. 

Then you can do a Row.<yourHiddenField> = <your auto-generated vallue>

It will be automatically saved together with all the values coming over from the client-side form and you can do all the data manipulation for this field on the server-side, so no "hacker" (your advanced users) can manipulate the auto-generation of this value.

Hope this helps.

With kind regards,

John
