### ISSUE TITLE
InplaceAdd; how to prevent inplaceAdd button change into inplaceEdit?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4727]
Hi all,

I am using the InplaceAdd tag to allow for inplace adding of new referenced items. By default, SF changes the inplaceadd functionality automatically into an inplaceEdit as soon as the main dialog is in edit and not add mode.

![InplaceAdd](https://user-images.githubusercontent.com/2699447/68705750-edb86100-058e-11ea-8c98-331a164687c0.png)

I would like to keep the inplaceadd button in add mode - even when the main dialog is in edit mode. How to do this?

Thanks for any help and

with kind regards,

John

**Comment by dfaruque** [comment]
Yes, there should be two different parameters. one is for `InplaceAdd `and another is for `InplaceEdit`. There might be InplaceView also.

**Comment by volkanceylan** [comment]
That's not possible without writing your own editor and handling.
