### ISSUE TITLE
language RTL switching

### ISSUE THREAD

**Issue by Parbil** [volkanceylan/Serenity#4728]
Hi All, After updating to the latest I have noticed that the right to left switching for Farsi is not working. Is there anyone facing same issue and what is the workaround.

**Comment by ramikhalyleh** [comment]
Hi Parbil,

I think you can add, in the file Initialization/UserCultureProvider.cs, to the property "Dictionary<string, string> TwoLetterToFourLetter = new Dictionary<string, string>",
the following line
            { "fa", "fa-IR" }

please check https://github.com/volkanceylan/Serene/pull/62/commits/75dbd002bf2ae7dac9eac4860ce3cc8745d8e091#diff-278788fb8a8b7d35d92bc6549b2de2d8

thank you

**Comment by ga5tan** [comment]
I have problem now, that user reports having site in Farsi, RTL, but claims to have Chrome set to EN lang.
any idea where it could go wrong?
