### ISSUE TITLE
sorting and filtering not working in editor grid

### ISSUE THREAD

**Issue by flextrio-gandhi** [volkanceylan/Serenity#4729]
not able to do sorting and filtering(Lookupeditor functionality) in editor
![screen](https://user-images.githubusercontent.com/28822452/68757725-6a504b80-0632-11ea-891b-5ae97ae2a0f0.png)

**Comment by judejay** [comment]
#3792

**Comment by flextrio-gandhi** [comment]
I have a drop down(hard coded value) box in dialog and below that have a tabular list so i need to filter the list based on drop down but this is not working. How to map or filter the hard coded values to the DataRow/Column/Editor?

**Comment by judejay** [comment]
https://github.com/volkanceylan/Serenity/wiki/Serenity-LookupEditor---Pass-Parameter-And-Change-LookupKey
