### ISSUE TITLE
Thumbnail Image not appeared in Chrome

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4730]
Hello All 
I Used InlineImageFormatter for Image in Serenity and it works fine in mozilla FireFox.
But In Google chrome thumbnail not shown.
This is my code: 
[Width(80), EditLink]
[XYZ.Default.InlineImageFormatter(Thumb = true)]
public String ImagePath { get; set; }

**Comment by hubeyb** [comment]
Hello,

you can try this css below, maybe chrome's default css is different I do not know,

```
.file-image a {
  background-size: contain !important;
}
```
if you can not achive, can you send screenshot please.
