### ISSUE TITLE
Signature Pad is not working on IIS Server.

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4732]
ReferenceError: SignaturePad is not defined

![image](https://user-images.githubusercontent.com/27406433/68950944-1752d180-07b5-11ea-9360-0eff4b308db6.png)

Windows Server2016   IIS  Version 10.
Both ways cause the red squiggle, both complie, run and publish.
On server it errors.

**Comment by marcobisio** [comment]
Did you add the javascript to the ScriptBundle ? And double check that the javascript library is included in the deploy package.
Signature pad is working fine in my projects.

**Comment by judejay** [comment]
Hi,

I put this in ScriptBundle at Base

    "~/node_modules/signature_pad/dist/signature_pad.umd.js"

As per Wiki.
But i just noticed it is different to the other as they start with script, I aslo added it to 

"Site":

    "~/node_modules/signature_pad/dist/signature_pad.umd.js",
    "dynamic://ColumnsBundle",
    "dynamic://FormBundle",
    "dynamic://TemplateBundle"

Doesn't appear to be in deployment Scripts , just running a search in the folder for "signature".

**Comment by marcobisio** [comment]
Try the v2.3.0 (stable) instead of the beta.

**Comment by judejay** [comment]
Thanks Marco, that did the trick!

**Comment by marcobisio** [comment]
You're welcome @judejay :-)
