### ISSUE TITLE
Filtering / displaying Rows according to User's permisions

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4733]
Hi all,

I have a table called "settings" which stores pairs of SettingName and SettingValue.

I want to set permission (view/modify) on each SettingsRow so that only authorized users can view or modify a specific setting.

This I would like to achieve with Serenity's integrated permission system as this would be easy to integrate in existing roles.

I have searched around in already existing issues here and in the wiki but didn't find any hint on how to do it.

Any concrete help is much appreciated.

With kind regards,

John

**Comment by abelal83** [comment]
Not done it myself but if I had to it would be using the multi tenancy example with service behaviour.

**Comment by hubeyb** [comment]
Your need is keyword is Multitenancy, you can search with this keyword on Serenity Document.

if you want to filter in grid by permission, you can override Preparequery and can write your conditions by permissions.

```
private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>
{
    protected override void PrepareQuery(SqlQuery query)
    {
        base.PrepareQuery(query);
        //write your permission condition filters here
        query = query.Select(MyRow.Fields.YourJoinFieldName);
    }
}
```

if you want to use in lookups consider this url;

[](https://volkanceylan.gitbooks.io/serenity-guide/tutorials/multi_tenancy/handling_lookup_scripts.html)

**Comment by JohnRanger** [comment]
@hubeyb ,

thanks for the additional detail infos regarding the preparequery. Will have a look into it - and if I come up with a reusable solution I will post it here.

Regards,

John
