### ISSUE TITLE
Dynamic form/entity

### ISSUE THREAD

**Issue by svamplus** [volkanceylan/Serenity#4734]
Hi, I would like to create a dynamic form/entity. A definition would be stored in a DB table EntityDefinition (FieldName, FieldType, Nullable). Does anybody have any code examples or experiences?

**Comment by JohnRanger** [comment]
Hi @svamplus ,

may I kindly ask what is the purpose of this?

As the code of each entity is generated statically by sergen (if you are doing "real" .net SF projects) and transported to client-side when doing a T4 transform, this is not trivial.

For dynamically generating a C# class (server side, xyzRow.cs, xyzFrom.cs, xyzColumns.cs), have a look at [this SO question](https://stackoverflow.com/questions/3862226/how-to-dynamically-create-a-class).

How to dynamically generate the client-side classes at runtime, I don't know (yet).

Regards,

John
