### ISSUE TITLE
Join table information is not getting values

### ISSUE THREAD

**Issue by fredvaliant** [volkanceylan/Serenity#4735]
When retrieving data, join table is not being generated even if data is exist from the foreign key. I already used LeftJoin and Origin, but no success. Is there any other way that this should be automatically gives the value of the joined table?

**Comment by hubeyb** [comment]
Where do you want to show joined data? if you want to show in grid, you must override prepare query on repository like below.

`  private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>
        {
            protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);

                query = query.Select(MyRow.Fields.YourJoinFieldName);
            }
        }`

**Comment by fredvaliant** [comment]
what if I need more columns or should I say I need most of the information of the joined table? Currently I have to query again for the joined table since the value of he joined table as property is null or error.

**Comment by hubeyb** [comment]
you can select all fields;
null is not important like default select.

```
query = query.Select(MyRow.Fields.Field1)
                       .Select(MyRow.Fields.Field2)
                       .Select(MyRow.Fields.Field3);
```

**Comment by fredvaliant** [comment]
I guess we have misunderstood each other, those fields from the joined table does not have value as expected.

**Comment by hubeyb** [comment]
If you do not share your code, most probably anyone can not help you :)

**Comment by judejay** [comment]
Make join on top of row.

**Comment by fredvaliant** [comment]
` 
    [LeftJoin("cd", "Applicants", "cd.[ApplicantId] = t0.[ApplicantId]", RowType = typeof(ApplicantsRow), TitlePrefix = "")]
    [LookupScript]
    
    public sealed class TestsRow : LoggingRow, IIdRow, INameRow
    {`

Is this what you mean @judejay

**Comment by judejay** [comment]
![image](https://user-images.githubusercontent.com/27406433/69319059-5dd18180-0c36-11ea-9b95-ec24e982dc88.png)
Run the Sql Profiler to see your requests on your dev server.
