### ISSUE TITLE
after 3.9.12 Upgrade 

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#4736]
![Capture](https://user-images.githubusercontent.com/23294782/69135600-cc95ca00-0ad2-11ea-9490-a0f2b592d2e2.JPG)

Hi some one quick help what is the Issue? I have popper.js in project still error.

**Comment by mustafalotiya** [comment]
![console](https://user-images.githubusercontent.com/23294782/69135937-6e1d1b80-0ad3-11ea-9dc6-0abdb70b6ffe.JPG)

**Comment by haoas** [comment]
try `dotnet sergen restore`

**Comment by mustafalotiya** [comment]
Hi haons,

i m not using .net core.. it's asp.net mvc.

**Comment by haoas** [comment]
the version of bootstrap.js  is higher.you’d better downgrade.Maybe the higher bootstrap.css can  cause other issue.

**Comment by mustafalotiya** [comment]
what is commended version of bootstrap with serenity 3.9.12

**Comment by haoas** [comment]
3.4.1.  the adminlte 2  also doesn't support the bootstrap4.

**Comment by mustafalotiya** [comment]
Yes , 3.4.1 solved the issue. 
Thanks hoas. I was struggling since morning to solve this issue. 
Actually i didn't update bootstrap to latest version. It was updated along with Serenity updates.

**Comment by mustafalotiya** [comment]
There is one more issue after upgrade started is navigation. Some of the action result i have put Page authorize to get navigation menu but since last update page authorize raise "Slack Empty" error. 
![PageAuthorize](https://user-images.githubusercontent.com/23294782/69153891-73409180-0af8-11ea-8ae2-a193c1926e74.JPG)

Is there any alternative to resolve this issue.

**Comment by haoas** [comment]
Today i also upgrade to 3.9.12, it works well.if you upgrade from more older version.serenity has some break changes,have you added all  serenity packages？

**Comment by mustafalotiya** [comment]
i have upgraded from 3.9.10.  

Basically what i have is: One a table  i have following permission. 
[ReadPermission("XLAccounts:XLTransaction:Led1Row:Read")]
[InsertPermission("XLAccounts:XLTransaction:Led1Row:Insert")]
[UpdatePermission("XLAccounts:XLTransaction:Led1Row:Update")]
[DeletePermission("XLAccounts:XLTransaction:Led1Row:Delete")]

I have more than one view from single table and each view requires additional permission aprt from read, insert etc.. which I was doing though pageauthorize.

now after upgrade, i got below error and so i have commented page authorize. it worked after commented. So looking for alternative option to achieve
![stack empty](https://user-images.githubusercontent.com/23294782/69156043-40989800-0afc-11ea-929e-30aa49a5d9ab.JPG)
 business logic for additional permission key.

**Comment by mustafalotiya** [comment]
Ok
said issue has been resolved by putting additional parameter on pageAuthorize.

### **[PageAuthorize("Page Authorize: XLTransactions:Reports-Accounts Statement",1, "Accounts")]**

Thanks @haoas for your efforts. Saves lots of time and effort.

**Comment by Zahar661** [comment]
@mustafalotiya I figured out what’s the matter, before it was still all the same about errors in permissions, but now it’s not. You cannot use spaces and some characters

**Comment by mustafalotiya** [comment]
@Zahar661  thanks for update.
