### ISSUE TITLE
Get value from Expression and save to DB

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4738]
Hi,
I'm tryiing to use an expression to load the value from a different table list of values.
Getting the Max from Score on table Games, to insert into Master row .

 [DisplayName("Max Score")]
        [Expression("(SELECT Max(Score) FROM [dbo].[Games] gam WHERE gam.[MatchID] = T0.[MatchD])")]
       // [SetFieldFlags(FieldFlags.Reflective)]
  //  [Column("MaxScore"), Insertable, up]

I can't get the value to save in database. tried a number of different ways.

**Comment by hubeyb** [comment]
you can try declare new proprty to save this value to db
then override onreturn and give this max value to save property like below

```
    private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> {
            protected override void OnReturn()
            {
                base.OnReturn();
                Response.Entity.SaveMaxScoreField= Response.Entity.MaxScoreExpressionField;
            }
        }
```

**Comment by judejay** [comment]
Thanks!
