### ISSUE TITLE
How to load new entity after Cloning?

### ISSUE THREAD

**Issue by fredvaliant** [volkanceylan/Serenity#4739]
When doing a clone entity, after saving it shows the last entity we clone. What is the best way to redirect it to the new entity instead of the entity we clone?

**Comment by JohnRanger** [comment]
Hi @fredvaliant ,

I do cloning always on the backend (server-side and then return the ID of the newly created record (the clone) to client-side - and then do a loadEntityById on client-side on the returned ID of the new record.

John

**Comment by fredvaliant** [comment]
Hi JohnRanger,

Thanks for the suggestions, which method should I used loadEntityById after saving clone item? It's still show the entity that I've clone upon saving. Again, thank you in advance for you help.

**Comment by JohnRanger** [comment]
Hmm,

possibly I don't fully understand your problem. If you clone something, the clone looks exactly identical as the original. So optically you cannot distinguish the original from the clone.

But if you retrieve the ID of the clone (which you can do on the server side within the aftersave method (just read Row.yourIDcolumn) and then refresh the xyzDialog with loadEntityById(<the returned ID which you just retrieved on Server-side>) within the onSaveSuccess method within xyzDialog.ts then your Dialog will reload its values from the clone record.

Did I explain it understandable? :-)

John

**Comment by fredvaliant** [comment]
Hi John,
Yes you did explain it perfectly but got stuck I can't see loadEntityById method and confuse on getting the id of new clone entity.

**Comment by JohnRanger** [comment]
Hi @fredvaliant,

:-)

I still do not understand, what your problem with the clone workflow really is.

Can you explain with a simple workflow like I did - what you actually want to achieve and what does not work as you expect in which step?

Regards,

John

**Comment by volkanceylan** [comment]
Clone shows a new dialog, and when you use Save button it closes the new dialog, so the dialog under gets displayed. If you want to keep the cloned entity why not use apply changes button, next to save (and close) button.
