### ISSUE TITLE
AdminLTE counters and notification icons

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#474]
Dear @volkanceylan,
I was wondering if there is a way to implement the icons/counters that already exists in the AdminLTE template.
I'm talking about this:
![image](https://cloud.githubusercontent.com/assets/17425690/14100736/ebb99ff8-f58f-11e5-9944-220bb41d3f39.png)

and this:
![image](https://cloud.githubusercontent.com/assets/17425690/14100743/fa2bbf3a-f58f-11e5-84a7-75b688b2fb93.png)

What I would like to know if there is something (I mean page counters o an automatism to refresh the page) that already exists in Serenity on which I can "hook" to implement these notifications.
I'm trying to do that with the orders in order to highlight when a new order is inserted in the system.

Thanks for your support
Best Regards

**Comment by volkanceylan** [comment]
There is no such mechanism. You may try polling with a timer to a service or try push notify with sockets/signalr

**Comment by marcobisio** [comment]
Ok thanks @volkanceylan...I'll try and I let you know if I manage to do it, in order to share the code with  the community.

Thanks again

**Comment by marcobisio** [comment]
Dear @volkanceylan,
first of all thanks for your valuable suggestion: I managed to implement a timed notification with SignalR using this nice article:

http://dontcodetired.com/blog/post/Using-Server-Side-Timers-and-SignalR-in-ASPNET-MVC-Applications.aspx

At the moment I have placed the following code:

<script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
                            <script src="~/signalr/hubs"></script>

                            <script>
                                $(function () {
                                    var hub = $.connection.notificationHub;

                                    $.connection.hub.start();

                                    hub.client.internetUpTime = function (time) {
                                        Q.notifySuccess('time');
                                    };
                                });
                            </script>

 in _Layout.cshtml in order to be sure that the notifications are already displayed, but do you think that there is a better/more appropriated place?

Just to know, the code above simply show a toast with the current timestamp every tot seconds...
How I can share this with the community? Wiki page or do you prefer to integrate such library in Serenity?

**Comment by linpiero** [comment]
Hi, I have already implemented notifications for serenity.
I used Microsoft signalR and jquery, but all in trasfersale way to serenity,  however about persistence I used the repository and WebAPI (endpoint) of serenity.

![image](https://cloud.githubusercontent.com/assets/15787703/14146848/760c1c08-f699-11e5-9133-b1c02ccd288a.png)

**Comment by marcobisio** [comment]
Sorry about that but I don't fully understand your answer....it's a bad thing what I have done using the layouy.cshtml to "host" my global notifier script?
Moreover, where I have to put the screwdriver in order to modify the left side navigation menù? I'm trying yo add the icons with numbers...

Thanks as always for your kind support
Regards

**Comment by volkanceylan** [comment]
Includes should go in LayoutHead as they will be used in every page. I recommend putting your notification scripts in an external file and including it in page. 

For menu, you may try modifying icon class in NavigationItem, e.g.

IconClass: "icon-layers my-custom-class1"

Then using this class and jQuery, locate that navigation item in page load ($(function() { ... }) , then inject those number items.

You may share your experiences in public wiki here. Some other users already shared such samples. Thanks.

**Comment by marcobisio** [comment]
Ok I'll do it!
Last question....if i want to get a simple "count(*)" of a table (the numbers that I'll show in the icons), there is a smart way to do that with the already existing XYZrepository? 

Thanks again

**Comment by volkanceylan** [comment]
It wouldn't be wise to call repository to take a count. See Dashboard code for how i get counts.

**Comment by linpiero** [comment]
Hello Mark, sorry for the reply I did not understand the question.

**Comment by marcobisio** [comment]
Sorry @linpiero I'm a bit tired and I was thinking that it was an answer from @volkanceylan :-D
All solved btw with all your suggestions: thanks @volkanceylan and thanks @linpiero 

Best Regards

**Comment by RahulShete01** [comment]
@linpiero Hi. I want to implement notification count using serenity. I am very new in serenity so can you please share code to implement the same.

**Comment by marcobisio** [comment]
Hi @RahulShete01,
look at this: https://github.com/volkanceylan/Serenity/issues/1301

Bye

**Comment by RahulShete01** [comment]
@linpiero .. Thank in advance. I am implemented like this but now i want to reduce notification count, if i read notification  from list. 
Suppose i have 10 notification and count display , but suppose i read 1 notification, now  9 notification count display. please help.

**Comment by SamCam15** [comment]
I changed the timespan.fromMinutes to 0.05, probably not what your after, but then I'm not a programmer, I just jumped in, to ask, If I changed this to Meetings module, it works, but is it exculsive, Like can there be a method that draws from diffferent modules or do they have to have a join? Just trying to understand the scheme of it.

                    using (var connection = SqlConnections.NewFor<MeetingRow>())
                    {                                    
                        model.MeetingCount = connection.Count<MeetingRow>();
                    }
