### ISSUE TITLE
Dynamic Home/Landing Page, based on permissions?

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4740]
As the subject says, I am looking for a good/best practice way to "redirect" a users login/landing page (after authentication, of course), based on that users "permissions" (and/or "roles"). Is anyone willing to share what they have done?

**Comment by hubeyb** [comment]
you can redirect like in MVC after Loggedin. 
If you want to reach this page with any permission who is loggedin, you can use Permission("?") on action.

**Comment by volkanceylan** [comment]
You could also handle this in AccountLogin.cshtml or Login.ts based on your version, use Q.Authorization.hasPermission etc.
