### ISSUE TITLE
Dot Net Core 3.0?

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4741]
I don't see this topic anywhere. I was just wondering what the plans were for Dot Net Core 3.0? Has anyone tried using Serenity with the latest version? What about "Blazor" any plans for support? Just wondering and a little surprised it hasn't been brought up...

**Comment by JohnRanger** [comment]
Hi @ShayneJud ,

this question has already been asked and answered [here](https://github.com/volkanceylan/Serenity/issues/4673).

Regards,
John

**Comment by ShayneJud** [comment]
Ahhhh.... I searched for "Core 3.0". ;)

Thanks for the heads up.
