### ISSUE TITLE
Upgraded to latest version...

### ISSUE THREAD

**Issue by ShayneJud** [volkanceylan/Serenity#4742]
(Maybe this would be better to post on the "paid" (StartSharp) forum, but I figured I'm not the only person that's going to go through this....)

I just updated my Serenity app to the latest version (from 3.8.1 to 3.9.12...I know, about time!). Anyway, I am having trouble getting the T4s to translate and/or get a successful build. I saw the note about Mono.Cecil.dll and "tried" to pull the latest "CodeGenerationHelpers.ttinclude" that isn't suppose to include a reference to it, but I am unable to find a version that doesn't. I created a new/blank project with the latest version and it even includes the reference. So, I deleted the reference, now it can't transform because the DLL to my App is missing. (And I can't "build" that DLL, because I can't transform.)

I also added "Serenity.Scripts" and "Serenity.Web.Assets" (per the 3.9.0 notes).

I am just in a loop here. I have restarted Visual Studio, etc. Been battling this for a few hours now and finally decided to ask for help.

**Comment by ga5tan** [comment]
I may have similar problem, thought my solution worked (in VS2017) up until I cloned it into VS2019

**Comment by ga5tan** [comment]
I deleted bin folder and was able to transform

**Comment by mustafalotiya** [comment]
check this one 
https://github.com/volkanceylan/Serenity/issues/4736
might help.

**Comment by Zahar661** [comment]
returned net 4.5.2 for the project, added a lot of references and deleted everything from NuGet S****.Web S****.Runtime ....
I don’t remember what they’re called, but when adding Systems. Web there will be a conflict with them.
