### ISSUE TITLE
datetime editor limits

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#4743]
hi all, 

Is there a way to allow datetime to be selectable for a given range? For example, I want to ensure only 2 weeks can be selected on the datetime UI.

Many thanks all!

**Comment by judejay** [comment]
Hi,
Have you tried :
SqlMinMax 

https://github.com/volkanceylan/Serenity/wiki/Editors:-Editor-Types

**Comment by abelal83** [comment]
thank you! No idea how I even missed that.
