### ISSUE TITLE
SlickGrid - Advanced Export. Any ETA?

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4745]
Hey guys!

I am seeing that Advanced Export is planned to do, but anyone know about any estimated completion date on this one? Is there anything that I could help?

I am in need of exporting grouped data from slickgrid but currently we only gives possibility of export "raw" data to excel/pdf from grid. 

Thanks!

**Comment by brunobola** [comment]
Alternatively you can create a method in your endpoint, and afterwords call it.
You can use for instance <a href="https://github.com/JanKallman/EPPlus">EPPLUS</a> and make the export what you wan't.
