### ISSUE TITLE
Problem in Edit Detail Row  in Master Detail Form

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4746]
Hello 
I have a Master-Detail Form and when I edit one row of Detail Grid and click save it adds another Row to Grid of Detail in the form.
Any Idea?

**Comment by hubeyb** [comment]
please double check the  code below
Grid must derived from GridEditorBase
and Dialog must derived from GridEditorDialog

do not use getIdProperty() in extended Dialog 

```
/// <reference path="..//..//Common//Helpers//GridEditorBase.ts" />

namespace Panel.XYZProvider {
    @Serenity.Decorators.registerEditor()

    export class GuestGridEditor extends Common.GridEditorBase<GuestRow> {
        protected getColumnsKey() { return 'XYZProvider.Guest'; }
        protected getDialogType() { return GuestDialog; }
        protected getLocalTextPrefix() { return GuestRow.localTextPrefix; }
    }
}

```

```
/// <reference path="..//../Common/Helpers/GridEditorDialog.ts" />

namespace Panel.XYZProvider {

    @Serenity.Decorators.registerClass()
    export class RoomGridEditorDialog extends Common.GridEditorDialog<RoomRow> {
        protected getFormKey() { return RoomForm.formKey; }
        protected getNameProperty() { return RoomRow.nameProperty; }

        public form: RoomForm;
   }
}
```

**Comment by haoas** [comment]
you can create a template file ,like yournamespace.xxDialog.Template.html,

**Comment by JohnRanger** [comment]
@haoas ,

what has your answer to do with OP's question? :-)

Regards,
John

**Comment by MaziarSangi** [comment]
@hubeyb 
Thank You 
I have created these two classes But I have another Problem  :
when I want to add a new Detail Row and whant to Update Master Form getting this error :
"Cannot insert the value NULL into column 'Id', table 'Detail Table' "

**Comment by mugambiwarwema** [comment]
@hubeyb @MaziarSangi 

I seem to be getting an error as well. 

Cannot insert the value NULL into column 'LoanPaymentId', table 'Breeze_v2.dbo.LoanPayments'; column does not allow nulls. INSERT fails.
The statement has been terminated.

LoansRow.cs

` 
     [ConnectionKey("Default"), Module("LoanManager"), TableName("[dbo].[Loans]")]
     [DisplayName("Loans"), InstanceName("Loans")]
     [LookupScript]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class LoansRow : Row, IIdRow, INameRow
    {
    [DisplayName("ID"), PrimaryKey]
        public Guid? LoanId
        {
            get { return Fields.LoanId[this]; }
            set { Fields.LoanId[this] = value; }
        }
    [MasterDetailRelation(foreignKey: "LoanId"), Insertable(true)]
        [DisplayName("PaymentRecords"), NotMapped]
        public List<LoanPaymentsRow> LoanPaymentsList
        {
            get { return Fields.LoanPaymentsList[this]; }
            set { Fields.LoanPaymentsList[this] = value; }
        }
     }
`

LoansPaymentsRow.cs
`

          [ConnectionKey("Default"), Module("LoanManager"), TableName("[dbo].[LoanPayments]")]
          [DisplayName("Loan Payments"), InstanceName("Loan Payments")]
         [ReadPermission("Administration:General")]
         [ModifyPermission("Administration:General")]
          public sealed class LoanPaymentsRow : Row, IIdRow, INameRow
          {
         [DisplayName("ID")]
         public Guid? LoanPaymentId
         {
            get { return Fields.LoanPaymentId[this]; }
            set { Fields.LoanPaymentId[this] = value; }
         }

        [DisplayName("Loan"), ForeignKey("[dbo].[Loans]", "LoanId"), LeftJoin("jLoan"), 
        TextualField("LoanMpesaMobileNumber")]
        [LookupEditor(typeof(LoansRow))]
        public Guid? LoanId
        {
            get { return Fields.LoanId[this]; }
            set { Fields.LoanId[this] = value; }
        }
      }
`

LoanPaymentsDialog
`         
           /// <reference path="../../Common/Helpers/GridEditorDialog.ts" />

          namespace BreezeLoanManager.LoanManager {

           @Serenity.Decorators.registerClass()
           @Serenity.Decorators.panel()

             export class LoanPaymentsDialog extends Common.GridEditorDialog<LoanPaymentsRow> {

             protected getFormKey() { return LoanPaymentsForm.formKey; }
             protected getNameProperty() { return LoanPaymentsRow.nameProperty; }
             protected getLocalTextPrefix() { return LoanPaymentsRow.localTextPrefix; }

             protected form: LoanPaymentsForm;

             constructor() {
                super();
                this.form = new LoanPaymentsForm(this.idPrefix)
             }
          }
         }
`

LoanPaymentsEditor.ts
`
            /// <reference path="../../Common/Helpers/GridEditorBase.ts" />

            namespace BreezeLoanManager.LoanManager {

             @Serenity.Decorators.registerEditor()
             @Serenity.Decorators.panel()

             export class LoanPaymentsEditor extends Common.GridEditorBase<LoanPaymentsRow> {

              protected getColumnsKey() { return "LoanManager.LoanPayments" }
              protected getLocalTextPrefix() { return LoanPaymentsRow.localTextPrefix; }
              protected getDialogType() { return LoanPaymentsDialog; }

              constructor(container: JQuery) {
                    super(container);
               }

               protected getAddButtonCaption() {
               return "Add Payment";
              }
          }
      }
`

**Comment by hubeyb** [comment]
> @hubeyb
> Thank You
> I have created these two classes But I have another Problem :
> when I want to add a new Detail Row and whant to Update Master Form getting this error :
> "Cannot insert the value NULL into column 'Id', table 'Detail Table' "
> Note Detail has Guid Type

Hi @MaziarSangi 
Can you send your code please,

**Comment by MaziarSangi** [comment]
@hubeyb 
My code is similar to @mugambiwarwema  code . 
I think the problem is Guid datatype. 
@hubeyb  Have you ever tried MasterDetail Relation with Guid datatype of Detail PrimaryKey?

**Comment by mugambiwarwema** [comment]
@MaziarSangi @hubeyb 

The issue is with Guid.

I changed my PK to Int32 with Identity and all works well now.

**Comment by MaziarSangi** [comment]
@mugambiwarwema 
I know 
So what should we do with Guid PrimaryKey?
Model changing is not possible in my project.

**Comment by mugambiwarwema** [comment]
I am afraid you’d have to talk to the serenity guys for further assistance.

My initial suggestion would be to manually implement it

**Comment by volkanceylan** [comment]
Either add a default value to table for the guild, or set it in your save handler and make it the [Default Handler]

**Comment by MaziarSangi** [comment]
@volkanceylan adding default value for guid works only for simple forms(Not MasterDetail Form)!
Because InsertAndGetId Have been used to set Id for new detail Row and this Method not work for guid datatype.

**Comment by PanChenhao** [comment]
@MaziarSangi, have you solved this issue? I also used GUID as primary key, I also get the error inforamtion 'The method or operation is not implemented', when I chagne the field type to int, then it works. but in my project, I have to use GUID,

**Comment by fremar83** [comment]
Hi
if you edit a detailform and have a new one saving it, it's because you don't have the "getIdProperty()" in your editor and/or in your detailDialog.

**Comment by stixoffire** [comment]
@Nathan2020-0126 Do what Volkan said - handle it in your save handler.

**Comment by volkanceylan** [comment]
Yes that's the correct way.
