### ISSUE TITLE
MasterDetailRelation

### ISSUE THREAD

**Issue by ILAOHE** [volkanceylan/Serenity#4747]
three Entity:A,B,C
Entity A ,have a property add MasterDetailRelation Attribute to Entity B,and B  add MasterDetailRelation Attribute to Entity C.
A B,no problem.
B and C   not work.
My English is not very good. I hope Nin。thanks！

**Comment by hubeyb** [comment]
yo must save manually in free version (serenity), 
override AfterSave method and save other properties

```
  protected override void AfterSave()
  {
        base.AfterSave();

       //write your save code here
  }
```

**Comment by mugambiwarwema** [comment]
@hubeyb The issue is with GUID. I changed my PKs to Int32 and it worked.
