### ISSUE TITLE
Cannot select in grid for copying using mouse

### ISSUE THREAD

**Issue by chuyi8008** [volkanceylan/Serenity#4748]
Tried the demo site and my own project (3.9.10). I cannot select any text in a grid such as NorthWind Customer grid.

**Comment by choss21** [comment]
Hi
Check https://serenity.is/demo/BasicSamples/EnablingRowSelection

**Comment by arunkumar12712** [comment]
write code grid ts file 


protected getSlickOptions(): Slick.GridOptions {
            var opt = super.getSlickOptions();
            opt.enableTextSelectionOnCells = true;
            opt.selectedCellCssClass = "slick-row-selected";
            opt.enableCellNavigation = true;
            return opt;
        }

        protected createSlickGrid(): Slick.Grid {
            var grid = super.createSlickGrid();
            grid.setSelectionModel(new Slick.RowSelectionModel());
            return grid;
        }

**Comment by shakazulu89** [comment]
i was about to create an issue for this as well.
@arunkumar12712  i have done this and while i can highlight the text as soon as i let go the highlight disappears as the row selection event seems to cancel my cell value highlight.
you can see this behavior in the link @choss21  shared. try to highlight a value from a cell and copy it...

**Comment by volkanceylan** [comment]
Override getSlickOptions and set enableTextSelectionOnCells to true
