### ISSUE TITLE
Problem with ExcelExportHelper

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#475]
Hi,

Does anyone had issues with Excel exporting?
I might be missing something but I am getting the following "Resource not found" error when using exporting to Excel.
![image](https://cloud.githubusercontent.com/assets/15879719/14107541/700bfedc-f5a8-11e5-9edf-9924c31300c9.png)

My code is the following:

```
 protected override List<ToolButton> GetButtons()
            {
                var buttons = base.GetButtons();
                buttons.Add(Common.ExcelExportHelper.CreateToolButton(this,
                GreidaBeintService.BaseUrl + "/ListExcel", this.OnViewSubmit));
                buttons.RemoveAt(0);
                return buttons;
            }
```

I would really appreciate if someone knows a quick fix for this :)

**Comment by 107295472** [comment]
Too difficult, or learning to learn it

**Comment by zerodev** [comment]
Did you add the action Endpoint FileContentResult ListExcel to greidabeing or waht ever module ?

**Comment by volkanceylan** [comment]
@107295472 Yin stop commenting on all topics. If it is so difficult, try your luck with something else. Start with English maybe.

**Comment by volkanceylan** [comment]
@biggikalli If you don't implement ListExcel action in your GreidaBeintEndpoint, it won't find resource.

**Comment by 107295472** [comment]
Start  English

**Comment by biggikalli** [comment]
Thank you for your quick answers. Worked like a charm as always.
According to your suggestions, I referred to how the Northwind.Order Endpoint is set up.

And Yin, thank you for the motivation - if you could do it, then the rest of us can :)
Everything is possible with a little patience!
