### ISSUE TITLE
Icon width is set to Zero on dashboard small boxes 

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4752]
Hi,

On serenity demo dashboard, the blue small box "Open Orders" has an icon that is not visible :

class="ion ion-bag" is 0 x 0.

Similarly case with the other boxes, only asking because I tried addding an icon and its always zero width. Tried ticking off the styles in chrome F12, no difference.

**Comment by edwardch** [comment]
The last I checked ionicons didn't work and I replaced them with FontAwesome icons which do work. 

Try replace it with `"fa fa-shopping-bag"` and see what you get?

**Comment by judejay** [comment]
> Try replace it with "fa fa-shopping-bag" and see what you get?


"fa fa-shopping-bag" works. 
Probably have to update the FA, if no one knows how to debug the Ionic.
