### ISSUE TITLE
SF project; setting the connectionKey at runtime from web.config / getting rid of the "default" connectionKey

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4754]
Hi all,

I am currently trying to "get rid" of the extremely static way how the connectionKey has to be set within an SF project and how everything is hard-coded to the "default" connectionKey. 

Because it is implemented as a mandatory attribute to a row class, the connectionKey string has to be set at compile time. This means it cannot be set via an appsetting within web.config.

-----------

Why do I want at all to do that and not just set the "default" connectionKey to the correct value?

-----------

As my current SF project (as do most of my SF projects) has to run within different environments (e.g. TEST, Prod) and there are multiple independent Test/Prod pairs (and when the SF project is in a Non-Prod environment, it must be able to copy Data from its matching Prod environment) I want to define within web.config within appsettings the Test/Prod pair which has to be used by the current SF project - like this:

```xml
<appSettings>
	...
    <add key="thisEnvironment" value="Test"/>
    <add key="liveEnvironmentConnectionKeyName" value="Live"/>
</appSettings>
```

In another Test/Prod environment pair, this could look like this:

```xml
<appSettings>
	...
    <add key="thisEnvironment" value="XYZ_Test"/>
    <add key="liveEnvironmentConnectionKeyName" value="XYZ_Live"/>
</appSettings>
```

Regarding the connectionStrings, for easier maintenance I just want to have all of the connectionStrings of all environments declared within the Web.configs of all instances of this SF project - like this:

```xml
<connectionStrings>
    <add name="Live" connectionString="Data Source = prodserver\SQLinstance; Initial Catalog=abc; Uid=user; Pwd=password" providerName="System.Data.SqlClient" />
    <add name="TEST" connectionString="Data Source = testserver; Initial Catalog=abc_TEST; Uid=user; Pwd=password" providerName="System.Data.SqlClient" />
    <add name="TRAINING" connectionString="Data Source = testserver; Initial Catalog=abc_TRAINING; Uid=user; Pwd=password" providerName="System.Data.SqlClient" />
    <add name="SCHULUNG" connectionString="Data Source = testserver; Initial Catalog=abc_SCHULUNG; Uid=user; Pwd=password" providerName="System.Data.SqlClient" />
    <add name="XYZ_LIVE" connectionString="Data Source = prodserver\SQLinstance; Initial Catalog=xyz; Uid=user; Pwd=password" providerName="System.Data.SqlClient" />
    <add name="XYZ_TEST" connectionString="Data Source = testserver; Initial Catalog=xyz_TEST; Uid=user; Pwd=password" providerName="System.Data.SqlClient" />
 </connectionStrings>
```

As the application has to adjust many internal things according to the given test/Prod pair, the connection strings are only one of these many things and I want - if reasonably possible - avoid to have to manually set also the "default" connectionKey to the same value as the connectionKey with the name which actually is defined within the app setting "thisEnvironment".

Hint: I have read [this issue here](https://github.com/volkanceylan/Serenity/issues/2153) and already modified my xyzEndpoints - but there are still many places within SF (not serene) where the "default" connectionKey is hard-coded and where I didn't just found a reasonable simple way to set the connection key from within the serene project.

Any input towards "getting rid" of the static connection key (and the "default" connection key) is greatly appreciated.

From a high level view, I am looking to something like this:

- Making the ConnectionKey attribute on a row class optional.
- If it is not set on a row class as attribute, then SF will expect the connectionKey be set as property of the row.rowfield class (I have seen that within RowFieldBase the connectionKey is available as an internal property - but I didn't yet manage to make it setable from a serene project.)
- Making it possible to dynamically (at site startup) to set the name of the "default" connection key (so that SF uses this connectionKey instead of the "default" connKey)

With kind regards,

John

**Comment by JohnRanger** [comment]
Update:

it seems that the solution lies within each xyzRow.cs - within the constructor of the sub class "RowFields".

If you want to dynamically assign the connectionKey at runtime, remove the **connectionKey("default")** attribute from the row class (delete it completely) and then add the following to the embedded RowField class within each xyzRow.cs:
```cs
...
        public partial class RowFields : RowFieldsBase
        {
            public RowFields()
            : base("[dbo].[someTable]")
            {
                LocalTextPrefix = "SetDefaultPrinter.ForWorkstationGroups";
                connectionKey = EnvironmentConstants.thisEnvironment; // <<<<<< add this line
            }
        }
        #endregion RowFields
```

**Hint:** EnvironmentConstants.thisEnvironment is my "global" variable which holds the name of the connectionString from web.config.

Hope this helps somebody.

P.S: As I have modified some stuff within Serenity Framework during my research for a solution, I will have to reverse these and see if the above trick still work without any of my modifications. 

Will post here an update as soon as I have done that.

With kind regards,
John

**Comment by edwardch** [comment]
Storing extra settings in the same file doesn't _seem_ like the cleanest way of doing it, and I think you might be able to use `configSource` inside your connection string or app setting section in your Web.config. 

I haven't done this myself, but you should be able to use it to keep different 'environment' settings. I don't have any links or resources (sorry) so maybe have a quick look around in case that might help.

Let me know if that helps?

**Comment by RouteTech** [comment]
I did something like this but I used the default database to store details about the environment (connection strings, pairs etc.) The username and password directs me to the correct settings. That way I don't have to modify the web.config etc.
Just another idea.

**Comment by shakazulu89** [comment]
i know this is super older but using serene 3.14 that ConnectionKey property for me is ReadOnly .... anyone any thoughts?
