### ISSUE TITLE
Clear a QuickFilter after press Enter Key

### ISSUE THREAD

**Issue by Jeremy-2019** [volkanceylan/Serenity#4755]
Hello All,

I have a problem. I create a dialog. In this dialog, we have a QuickFilter for "BarCode" and a datagrid with contains datas.

The handler value of the quickfilter has been set. Like this when I press Enter I can call webservice for the barcode set in the filter.

After the job, I need to clear the quick filter automatically. As I said, without clicking the X button on the quickfilter.

This will be very useful for the operators which scan some objects continously

**Comment by hubeyb** [comment]
Write catch key event handler in constructor of grid,
then when catched the event, try to change or remove filter value with code below

```
    var customFilter = this.findQuickFilter(MyTestEditor, fld.YOUR_FIELD);
    customFilter.value = "2"; 
```
