### ISSUE TITLE
Font Size on Grid in Dialog

### ISSUE THREAD

**Issue by MagDev175** [volkanceylan/Serenity#4756]
I'm trying to change the font size on a grid in dialog and cannot get it to work.
I have the below code both alone and as part of the dialog in the site.less page, but neither seems to do anything.  This snippet does work for a grid not in a dialog.
.s-MyGrid {
     .slick-cell {
        font-size: 8px;
    }
}

**Comment by judejay** [comment]
.s-Module-DetailsEditDialog {
    background-color: green;
    color: #fff;
    .field {
                  font-size: 18px !important;
            }
}
