### ISSUE TITLE
Save button is not functioning after an entity is cloned in memory grid

### ISSUE THREAD

**Issue by atikcandurmus** [volkanceylan/Serenity#4757]
I have an in-memory grid (Common.GridEditorBase) as a child of entity dialog (Serenity.EntityDialog).
When I clone an item in in-memory grid as clicking the clone button, save button in cloned entity is not working. Anyone encountered an issue like this and got a solution? Can you help me?

**Comment by atikcandurmus** [comment]
Anyone?

**Comment by volkanceylan** [comment]
Clone is only supported for normal dialogs, not in memory dialogs
