### ISSUE TITLE
card view set as default view

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#4759]
Hello,
How can I set card view as default view and hide list view?

Thanks

**Comment by volkanceylan** [comment]
In your grid constructor:

```ts
this.element.find('.grid-title .view-switch').hide().find('input[type=radio]').eq(1).click();
```

**Comment by teafmartins** [comment]
Great volkanceylan! thx!

**Comment by gfo2007** [comment]
@teafmartins did the code snippet from volkan work? I tried it in my grid constructor but nothing changed.

**Comment by teafmartins** [comment]
Yes, in grid.ts you should add:

        constructor(container: JQuery) {
            super(container);
            
            this.element.find('.grid-title .view-switch').hide().find('input[type=radio]').eq(1).click();
        }

**Comment by gfo2007** [comment]
@teafmartins I have done that in Northwind Customer demo grid as a test but nothing is happening.

Here is the code and image below. Please help me to know if I am doing anything wrong.

**CustomerGrid.ts**
```
namespace Serene1.Northwind {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.filterable()
    export class CustomerGrid extends Serenity.EntityGrid<CustomerRow, any> {
        protected getColumnsKey() { return "Northwind.Customer"; }
        protected getDialogType() { return <any>CustomerDialog; }
        protected getIdProperty() { return CustomerRow.idProperty; }
        protected getLocalTextPrefix() { return CustomerRow.localTextPrefix; }
        protected getService() { return CustomerService.baseUrl; }

        constructor(container: JQuery) {
            super(container);

            this.element.find('.grid-title .view-switch').hide().find('input[type=radio]').eq(1).click();
        }

        getButtons() {
            var buttons = super.getButtons();

            buttons.push(Serene1.Common.ExcelExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: 'Northwind/Customer/ListExcel',
                separator: true
            }));

            buttons.push(Serene1.Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));

            return buttons;
        }

    }
}
```

![Northwind Customer](https://user-images.githubusercontent.com/14317420/89095803-da6d5000-d3c0-11ea-9cb6-eb945d92f6c0.PNG)

**Comment by teafmartins** [comment]
I added code in CustomerGrid.ts and it's working!

constructor(container: JQuery) {
            super(container);

            this.element.find('.grid-title .view-switch').hide().find('input[type=radio]').eq(1).click();
        }

![image](https://user-images.githubusercontent.com/17210232/89349344-f2d1b900-d6a5-11ea-85a3-326de00ad564.png)
