### ISSUE TITLE
adding CSS Class ToolbarExtensions  collapse

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#476]
can we add a class to ToolbarExtensions utlizing AdminLte  collapse functionality 
` <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>`

**Comment by volkanceylan** [comment]
I don't what it is

**Comment by zerodev** [comment]
in AdminLte  you can add the collapse attribute to the data-widget to add the DIV collapse effect
![collaps](https://cloud.githubusercontent.com/assets/728937/14119050/a0179052-f5ec-11e5-8ebf-a1c9c9ccf01b.png)

**Comment by volkanceylan** [comment]
So add it in CSHTML, what prevents you from?

**Comment by zerodev** [comment]
there is no place to add it there , the filters are added dynmicly ? the collapse  must be added to the 
created dic with class name  "quick-filters-bar" ,  and this is done by calling  base.CreateToolbarExtensions();  and addthing the filters one by one if am right?

My Goal is to add collapse fuctionality to the filters "toggle visability"

**Comment by volkanceylan** [comment]
Add it with jQuery
