### ISSUE TITLE
MasterDetailRelation always returns The method or operation is not implemented. 

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4760]
Hello All 
I have two tables with Guid Id and I want to show Detail Grid in Master Form.
But When I want to Insert new Detail in Master Form and Submit Master Form  Update buttons this error will appear from GuidField.cs :
 The method or operation is not implemented

**Comment by mugambiwarwema** [comment]
In one of the PrimaryKeys property, when setting the attributes eg [Idenity/PrimaryKey] be sure to make sure you include either and appropriately.

**Comment by MaziarSangi** [comment]
@mugambiwarwema  
I replaced Identity with PrimaryKey and the problem is it sends null for Id to sql and sql can not insert new Row to table. the error is "Cannot insert the value NULL into column 'Id'" 
I think MasterDetail does not support Guid.

**Comment by mugambiwarwema** [comment]
I am having the same problem as you. I will keep you posted on how I progress

**Comment by MaziarSangi** [comment]
#4746

**Comment by PanChenhao** [comment]
@mugambiwarwema have you solved the issue with Guid and MasterDetailRelation?
I met the same issue now, i got the error information 'The method or operation is not implemented.'
