### ISSUE TITLE
How to use iCheck in serenity.

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4763]
Hi,
In the Serenity demo, there is and advanced form element that is demo'd , called icheck.
How to use this?
Searched already.

**Comment by welcometoall** [comment]
Create your own TypeScript definition file (**jquery.icheck.d.ts**) based on following example and use it.

iCheck Methods:
[http://icheck.fronteed.com/#methods](http://icheck.fronteed.com/#methods)
```
interface JQuery {
    iCheck(options?: iCheckOptions): JQuery;
...
}
```

iCheck Options:
[http://icheck.fronteed.com/#options](http://icheck.fronteed.com/#options)

```
interface iCheckOptions{
    handle?: string;
...
}
```

For more info, refer to following [Select2 Type Defenition](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Scripts/CoreLib/Imports/Select2.ts)
