### ISSUE TITLE
Cant see value on grid MasterDetailEditor

### ISSUE THREAD

**Issue by Mondaii** [volkanceylan/Serenity#4765]
i have a masterdetail editor that on its form calls another masterdetail editor,
the problem is that on the first editor don't show any value on grid until i resize the form then all values appears and on the second editor the grid don't show any value at all, but the rest is working as intended.

1 editor 

 #region ProfissionalAgendaList
        [MasterDetailRelation(foreignKey: "EscalaId")]       
        [DisplayName("Horários"), NotMapped]
        public List<ProfissionaisAgendasRow> ProfissionalAgendaList
        {
            get { return Fields.ProfissionalAgendaList[this]; }
            set { Fields.ProfissionalAgendaList[this] = value; }
        }
        public partial class RowFields { public readonly RowListField<ProfissionaisAgendasRow> ProfissionalAgendaList; }
        #endregion ProfissionalAgendaList

/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace CFRV.Clinica {
	    
    @Serenity.Decorators.registerEditor()
    export class ProfissionaisAgendasEditor extends Common.GridEditorBase<ProfissionaisAgendasRow> {
        protected getColumnsKey() { return 'Clinica.ProfissionaisAgendas'; }
        protected getDialogType() { return ProfissionaisAgendasEditorDialog; }
        protected getLocalTextPrefix() { return ProfissionaisAgendasRow.localTextPrefix; }
        protected getIdProperty() { return ProfissionaisAgendasRow.idProperty; }
        protected getService() { return ProfissionaisAgendasService.baseUrl; }
       

 
        public Escalas: string;
     

        public Profissional: string;

     

        protected getAddButtonCaption() {
            return "Adicionar";
        }

        //Ao iniciar o dialog, atribuir o que tiver em myParentForm
        protected initEntityDialog(itemType: string, dialog: ProfissionaisAgendasEditorDialog) {
            super.initEntityDialog(itemType, dialog);            
            dialog.Profissional = this.Profissional;
            dialog.Escalas = this.Escalas
        }

        constructor(container: JQuery) {
            super(container);
        }

       
    }
}

2 editor
        #region ProfissionalAgendaHorasList
        [MasterDetailRelation(foreignKey: "ProfissionalAgendaId")]
        [DisplayName("Horários"), NotMapped]
        public List<ProfissionaisAgendasHorasRow> ProfissionalAgendaHorasList
        {
            get { return Fields.ProfissionalAgendaHorasList[this]; }
            set { Fields.ProfissionalAgendaHorasList[this] = value; }
        }
        public partial class RowFields { public readonly RowListField<ProfissionaisAgendasHorasRow> ProfissionalAgendaHorasList; }
        #endregion ProfissionalAgendaHorasList

/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace CFRV.Clinica {
	    
    @Serenity.Decorators.registerEditor()
    export class ProfissionaisAgendasHorasEditor extends Common.GridEditorBase<ProfissionaisAgendasHorasRow> {
        protected getColumnsKey() { return 'Clinica.ProfissionaisAgendasHoras'; }
        protected getDialogType() { return ProfissionaisAgendasHorasEditorDialog; }
        protected getLocalTextPrefix() { return ProfissionaisAgendasHorasRow.localTextPrefix; }
        protected getIdProperty() { return ProfissionaisAgendasHorasRow.idProperty; }
        protected getService() { return ProfissionaisAgendasHorasService.baseUrl; }
        public ProfissionalAgenda: string;
        
        protected getAddButtonCaption() {
            return "Adicionar";
        }
        protected initEntityDialog(itemType: string, dialog: ProfissionaisAgendasHorasEditorDialog) {
            super.initEntityDialog(itemType, dialog);
            dialog.ProfissionaisAgenda = this.ProfissionalAgenda;
         
        }

        constructor(container: JQuery) {
            super(container);
        }
    }
}

**Comment by MaziarSangi** [comment]
You have to add this attribute on List field in Row Class:
MinSelectLevel(SelectLevel.List)

**Comment by Mondaii** [comment]
thanks that worked.
