### ISSUE TITLE
Placeholder helper text "--select--" not visible till click off field

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#4766]
Hi,
Thanks to Volkan and the team for this awesome framework!
I have small issue with the form placeholder for a LinkingSetRelation field.
The default helper text "--select--" ,  doesn't show up on my form unless I click on the field and not select anything, and then double click anywhere.
Tried inserting a Placeholder value on the Row but no change to its behaviour. But the text does change to new text.
Also tried :
`            this.form.LinkedSetList.getGridField().attr('placeholder', 'Select multiple values from the list');`
Does nothing.

**Comment by judejay** [comment]
Hi,
Updated to latest version of everything, no change, only happens when place:
Multiple = true.

Any help ?

**Comment by judejay** [comment]
Placeholder is empty in F12.


`   <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="select2-input select2-default" id="s2id_autogen1" style="width: 1414px;" placeholder="" aria-activedescendant="select2-result-label-237">`

**Comment by sayuga** [comment]
any errors or messages on the console? Something may be interrupting the build of the dialog.

**Comment by volkanceylan** [comment]
The placeholder is there, but Select2 sets the width of select2 input to 10px initially so it is not shown. I don't think it can be fixed, maybe you can apply some css override to that select2-input with !important. Closing this as it is a problem with select2 itself.

**Comment by volkanceylan** [comment]
https://stackoverflow.com/questions/28140705/select2-multiple-placeholder-does-not-work
