### ISSUE TITLE
'Generated PDF File is empty" error

### ISSUE THREAD

**Issue by vishmanthisuresh111** [volkanceylan/Serenity#4772]
Hi, 
I am trying to convert html to pdf and am getting 'Generated PDF file is empty' error. As mentioned in the existing issues we have tried adding the wkhtmltopdf.exe with the correct version. Also tried using footerhtmlurl by giving absolute url.. While debugging the issue we can also find that the 'ID' is coming correctly but finally it is throwing this error. Could you please help us in resolving the issue we are badly struck here and we are not getting any further solution?

Please find below the code which we are trying to use similar to the OrderDetail
var externalUrl = Config.Get<EnvironmentSettings>().SiteExternalUrl ??
                Request.GetBaseUri().ToString();

            var renderUrl = UriHelper.Combine(externalUrl, "Report/Render?" +
                "key=" + Uri.EscapeDataString(key));

            if (!string.IsNullOrEmpty(opt))
                renderUrl += "&opt=" + Uri.EscapeDataString(opt);

            renderUrl += "&print=1";

            var converter = new HtmlToPdfConverter();
            var wkhtmlPath = HostingEnvironment.MapPath("~/bin/wkhtmltopdf.exe");
            if (System.IO.File.Exists(wkhtmlPath))
                converter.UtilityExePath = wkhtmlPath;
            
            converter.Url = renderUrl;
            var formsCookieName = ".AspNetAuth";
            var formsCookie = Request.Cookies[formsCookieName];
            if (formsCookie != null)
                converter.Cookies[formsCookieName] = formsCookie;

            var icustomize = report as ICustomizeHtmlToPdf;
            if (icustomize != null)
                icustomize.Customize(converter);

            return converter.Execute();
At return we are getting the above error.
Thanks and Regards,
Suresh.

**Comment by rcruzfalcon** [comment]
Hi @vishmanthisuresh111 
This error when it happened to us was because of the url "public" from the server is unaccesible.
Try open the final url inside the server by any explorer and check if open right.
best regards.
Roberto
