### ISSUE TITLE
3.9.13 warning - es5 async Promise

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4773]
hey there, i have moved serenity nugets to new 3.9.13 version.

In the xxxDialog.ts i noticed a "warning" (but this does not affect correct execution of application).

![image](https://user-images.githubusercontent.com/31513956/70614505-fb531c00-1c0a-11ea-987e-a2b4c7336582.png)

There is an "asyncPromise" property (new ?).
Is there some special modifications to apply on existing code to remove this ? 

PS : Same warning is easy to reproduce from a brand new startsharp project.

**Comment by volkanceylan** [comment]
Can't reproduce such a warning, probably due to something / version in your environment like VS / TypeScript version, or npm package mismatch

**Comment by kilroyFR** [comment]
I have just checked, this warning appears when : 
"target": "es5" => in tsconfig.json 
(i have to use IE as browser so enabling "es6" is not the focus right now).

**Comment by volkanceylan** [comment]
There is no asyncPromise anywhere in our code.
