### ISSUE TITLE
Finding Join Aliases? Using Serene Template

### ISSUE THREAD

**Issue by cad-masters** [volkanceylan/Serenity#4775]
I have limited SQL/C# knowledge and maybe this is an easy question but I was wondering where I could find the aliases for the joins as I am trying to have the City Field in the Customer Row reference the territory table.

`[DisplayName("City"), ForeignKey(typeof(TerritoryRow)), LeftJoin(**"via"**), LookupEditor(typeof(TerritoryRow))]
        public String City
        {
            get { return Fields.TerritoryDescription[this]; }
            set { Fields.TerritoryDescription[this] = value; }
        }`

Unfortunately I have no idea what "via" means in this instance or where to figure that out. Any help would be appreciated

**Comment by minhhungit** [comment]
Alias is temporary name, represent for your table (dbo.Territory). 

read more about SQL Alias here 
https://www.w3schools.com/sql/sql_alias.asp or 
https://www.geeksforgeeks.org/sql-aliases/

**IMHO**, Serenity seems simple but it's really complex so you should know SQL /C# as much as possible 

You can naming it as whatever you want, for example: LeftJoin("helloworld")
