### ISSUE TITLE
grid itemAt(row) return type issue, break change maybe ?

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4776]
Hello @volkanceylan @AlperanQ 

I see that we changed return type of itemAt() method
https://github.com/volkanceylan/Serenity/commit/d2f11d1dc9c5b425480d59b1b1a2ac8b0c1d0a25#diff-a41bee038d1672048cd690a539c13a08

I think it should return **any**, not *TItem*
because the row can be a "grouping row"

so I think it's better if we use 'any' type and let developer decide what type it will be cast to

```javascript
let groupRow = this.itemAt(row);
let rowsOfCurrentGroup: MyRow[] = groupRow.rows; // ts error if we did not mark groupRow as 'any'
```

**Comment by volkanceylan** [comment]
i understand but group rows are much less common so this is for better, writing as any for groups is much easier than all items

**Comment by minhhungit** [comment]
I think I'm okay with the reason => no need to change

**Comment by minhhungit** [comment]
Thank you!
