### ISSUE TITLE
StringField.cs  IIdField NotImplementedException

### ISSUE THREAD

**Issue by YoselYohan** [volkanceylan/Serenity#4778]
IIdField.this[Row row] throws a NotImplementedException in StringField.cs file. What will be the future implementation of this property?. For now, I know IIdField supports Int16, Int32 and Int64 but there is an issue with JavaScript and big numbers. In my case I was able to use string as PrimaryKey (to handle long values)   but I had to change the property as follow:
from:
```
     long? IIdField.this[Row row]
        {
            get
            {
                throw new NotImplementedException();
            }

            set
            {
                 throw new NotImplementedException();
            }
        }
```

to this
```
long? IIdField.this[Row row]
        {
            get
            {
                CheckUnassignedRead(row);
                string numString = _getValue(row);
                long longToBeReturned = 0;
                bool canConvert = long.TryParse(numString, out longToBeReturned);
                if (canConvert == true)
                    return longToBeReturned;
                else
                    throw new InvalidCastException($"value {numString} is not numeric!.");
            }
            set
            {
                _setValue(row, value.ToString());
                if (row.tracking)
                    row.FieldAssignedValue(this);

            }
        }
```

**Comment by volkanceylan** [comment]
Don't change anything, it's just a backward compatibility placeholder and many use non integer fields as ID.

**Comment by YoselYohan** [comment]
Thank you. I created my own "FieldType" inheriting from StringField while implementin IIdfield interface and created my own SaveRequestHandler. Now my primary key is a string holding this big numbers that are computed server side. I am just pointing out that when you have a primary key Int64? once you get to certain point it will stop working. You can try that in your Serene application reseeding the identity value of any table to very large number still valid for and int64 while Serenity is returning the correct value in the response object from the repository/Service the value will be rounded/truncated to the significant digits of JavaScript "number" datatype.

**Comment by volkanceylan** [comment]
Thanks, as i said in another issue using StringEditor for those id fields should help.
