### ISSUE TITLE
How to call RESTful webservice without login

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#478]
Hello sir,

I want to create RESTful webservice and call it without login it shows message : Authorization is required for this request! So how to call this web service without login.

And another problem is suppose i want to call below web service how to send IUnitOfWork and SaveRequest<MyRow> .object to call this web service.

        [HttpPost]
        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MyRepository().Create(uow, request);
        }

**Comment by volkanceylan** [comment]
So remove ServiceAuthorize
