### ISSUE TITLE
hiding parameter in url serenity

### ISSUE THREAD

**Issue by hamkairama** [volkanceylan/Serenity#4781]
Hi volcan,
I get the issue...
i have 2 project serenity.

1. using version 2.4.13.0. in this version the parameter url is hide.
![image](https://user-images.githubusercontent.com/34258727/71078716-7f357700-21bc-11ea-8bb9-91fa3f59e43d.png)

![image](https://user-images.githubusercontent.com/34258727/71078661-6a58e380-21bc-11ea-8758-e5d6b286da5a.png)

2. using version 3.7.7.0 in this version the parameter url is show.
![image](https://user-images.githubusercontent.com/34258727/71078555-37165480-21bc-11ea-9334-c6611cc1e75e.png)

![image](https://user-images.githubusercontent.com/34258727/71078607-51e8c900-21bc-11ea-94b9-2a15c3f102b6.png)

**the question is how hide parameter url in serenity version 3.7.7.0 ?**

**Comment by volkanceylan** [comment]
Add Q.Router.enabled = false in ScriptInitialization.ts or similar
