### ISSUE TITLE
Northwind expression issue causing row retrieve to fail on case sensitive database collations

### ISSUE THREAD

**Issue by OpenlabWA** [volkanceylan/Serenity#4783]
In Modules\Northwind\OrderDetail\OrderDetailRow.cs - Line 59
[DisplayName("Line Total"), Expression("(t0.[UnitPrice] * t0.[Quantity] - t0.[Discount])")]
and
Modules\Northwind\Customer\CustomerRow.cs - Line 16
[LeftJoin("cd", "CustomerDetails", "cd.[ID] = t0.[ID]", RowType = typeof(CustomerDetailsRow), TitlePrefix = "")]

t0 should be T0
Was causing row retrieve to fail on case sensitive collation (was using MariaDB and MySql connector at time)

Not sure if this was a manual typo, or issue in code generation as I'm not familiar with how this was generated initially.

Thanks very much!

**Comment by volkanceylan** [comment]
It is written manually, normally it should be T0, but Northwind is not supposed to work with case sensitive collations. Anyway, will change them to be uppercase

**Comment by volkanceylan** [comment]
Should be handled in this commit: fda1204b66f590b4a57b27fdb593baae7d68cd45
