### ISSUE TITLE
show count of each Detail Grid in Master Form

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4787]
I have a MasterDetail Form and I want to get count of Detail Grid Rows and show this count in Master Form as Notmapped Field. 
AnyBody knows how to Implement it?

**Comment by hubeyb** [comment]
you can use expression to count detail with condition.
But if you have a lots of data in table, avoid to use this property in DataGrid (..Columns.cs), use only in form (...Form.cs).
 

>    [DisplayName("Total Worked Hours"), AlignRight]
>    [Expression("(Select SUM(WorkedHours) from WorkItemLog Where WorkItemId = T0.WorkItemId)")]
>         public Decimal? TotalWorkedHours
>         {
>             get { return Fields.TotalWorkedHours[this]; }
>             set { Fields.TotalWorkedHours[this] = value; }
>         }

**Comment by MaziarSangi** [comment]
@hubeyb 
Thank you.
