### ISSUE TITLE
Openin SQL Connection in Async

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4788]
Hey Guys!

Will we ever get Async support in any SQL connection code? I would love to get opening new connection by using Serenity out of the box methods instead of creating my own, like:

`SqlConnections.NewByKey(Constants.ConnectionKeys.DEFAULT)`
`SqlConnections.NewByKeyAsync(Constants.ConnectionKeys.DEFAULT, cancellationToken)`

Is there any chance to implement and support this kind of opening connections?

Thank you

**Comment by volkanceylan** [comment]
You may create the connection with NewByKey and open it async as you like, creating a connection does not open it.

**Comment by lechu90ns** [comment]
Okay, I see the point of it. Although, I am not sure since I need to open it with providing CancellationToken. Do you think that while using Task.Factory, aborting via token will force the connection to drop and abandon?

Thanks!

`Task.Factory.StartNew(() =>
            {
                using (var conn = SqlConnections.NewByKey(Constants.ConnectionKeys.DEFAULT))
                {
                    conn.EnsureOpen();

                    //Work
                }
            }, cancellationToken);`

**Comment by lechu90ns** [comment]
I figured out that probably this code below is needed instead. 

```
                var cmd = conn.CreateCommand();

                // We will cancel our IDbCommand
                cancellationToken.Register(() => cmd.Cancel());
```
