### ISSUE TITLE
Check only one checkbox and disable all others

### ISSUE THREAD

**Issue by leovamos** [volkanceylan/Serenity#4789]
Hi, guys

My problem is as follows: I have a dialog that contains checkboxes for each role that a user can own. Due to errors in database relationships, a user can assume multiple roles (user, administrator, etc.) on the current system, but what I have to do is correct so that only one role is assumed for one user. The arrow marks the dialog I'm interested:

![mtoken_help_dialog_1](https://user-images.githubusercontent.com/38430921/71525136-357d1880-28af-11ea-8f9e-6d1bd1d89757.png)

One idea is that as soon as one role is checked, others already marked are unmarked and cannot be clicked until the last clicked is unmarked as well. I am trying to do this by JavaScript in the UserRoleDialog.ts file, but apparently the functions of this file are only executed when called, and I want this to happen while the window is open, after all I can click as many times as I want in the options. (I ain't so sure of this, but is what I'm seeing from tests. Functions are only executed when they're called).

Another idea is to transform this options in a dropdown/combobox, what is guaranteed that only one option is selected, but I don't know how to create and customize an dialog and use it.

One thing is that dialog is formed with spans with classes "check-box" and "check-box checked" when is checked. So I cannot retrieve the elements by its id because they don't have it.

My actual code for UserRoleDialog.ts is with comments and some unfinished parts because I'm trying different solutions. It is as follows:

´´namespace MobileMonitor.Administration {

    @Serenity.Decorators.registerClass()
    export class UserRoleDialog extends Serenity.TemplatedDialog<UserRoleDialogOptions> {

        private permissions: RoleCheckEditor;

        constructor(opt: UserRoleDialogOptions) {
            super(opt);

            this.permissions = new RoleCheckEditor(this.byId('Roles'));
            this.changeText();
            UserRoleService.List({
                UserID: this.options.userID
            }, response => {
                this.permissions.value = response.Entities.map(x => x.toString());
                });
            
        }

        changeText() {
            $(document).ready(function () {
                var buttons = document.getElementsByClassName('ui-button ui-corner-all ui-widget');
                var okButton = buttons[2];
                okButton.textContent = 'Atualizar';
            });
        }

        disableCheckbox() {
            $(document).ready(function () {
                var checkbox = document.querySelector('.check-box');
                console.log(checkbox);
                checkbox.addEventListener('change', function () {
                    alert(this);
                    console.log(this);
                    if ($(this).hasClass('checked')) {
                        $('.check-box').not($(this)).removeClass('checked');
                        $('.check-box').not($(this)).css('pointer-events', 'none');
                    } else {
                        $('.check-box').css('pointer-events', 'auto');
                    };
                    /*var checkedOne = Array.prototype.slice.call(checkboxes).some(x => $(x).hasClass('checked'));
                     if (checkedOne) {
                         Array.prototype.slice.call(checkboxes).forEach(function (element) {
                             if (!$(element).hasClass('checked')) {
                                 $(element).css('pointer-events', 'none');
                             }
                         });
                     } else {
                         Array.prototype.slice.call(checkboxes).forEach(x => $(x).css('pointer-events', 'auto'));
                     }*/

                    //$('.check-box.checked').css('pointer-events', 'none');
                });
            });
        }´´

Thanks in advance ;)

**Comment by sayuga** [comment]
Why don't you just edit the .ts for the dialog and add the behavior there using a validation sorta-scheme. This way you can add a user, select a user security level and set the behavior to do exactly what you described. This also keeps you from having to change much on the server side of things.
