### ISSUE TITLE
Displaying multiple select values in Coulumn of Grid.

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#479]
Is there example of displaying all the selected values in a lookup editor in a column of a grid. 
![image](https://cloud.githubusercontent.com/assets/17201265/14122131/e3748d64-f5bf-11e5-9f45-f0c6013f7050.png)

If so is there a example anywhere out there?

**Comment by volkanceylan** [comment]
No there is no example. Best option is to write a sql expression field that returns them as concatted string.
