### ISSUE TITLE
Remove DOT after Checkbox field

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#4791]
How to remove DOT after Checkbox field. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/25874638/71627541-05b87280-2c19-11ea-9334-019c40678889.png)

**Comment by minhhungit** [comment]
I created pull request for this issue here https://github.com/volkanceylan/Serenity/pull/4777
still waiting response from @volkanceylan
