### ISSUE TITLE
JsonserviceClient get loggedin User Details

### ISSUE THREAD

**Issue by reach2rv** [volkanceylan/Serenity#4794]
How we can get details of User like id, name, email etc.. using Jsonserviceclient (in Xamarin App). after user login.

I am aware of creating Action in the endpoint of user row and calling it after login but I am looking for a solution where we can get those details in login response itself.

Thanks in advance.

**Comment by kilroyFR** [comment]
why not querying the Retrieve endpoint ?

**Comment by reach2rv** [comment]
I am aware it as a workaround, but by asking this I am trying to avoid one more around of API call

**Comment by volkanceylan** [comment]
Yes you won't get it without retrieve.
