### ISSUE TITLE
SlickGrid - creating meta group provider

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4795]
Hey Guys,

I have an issue with creating meta group item metadata provider with my own options. I am not able to provide this due code below in \Serenity.Scripts\CoreLib\Externals\Serenity.Externals.Slick.ts:

```
export class RemoteView<TEntity> {
        constructor(options: any) {
            var self = this;

            var defaults = {
                groupItemMetadataProvider: <any>null,
                inlineFilters: false
            }
```

and then:
```
if (!options.groupItemMetadataProvider) {
                    options.groupItemMetadataProvider = new Slick.Data.GroupItemMetadataProvider();
                }
```

so no matter what `new Slick.Data.GroupItemMetadataProvider({ })` I would register, it is replaced with the code above anyway.

I would appreciate for any help.

Thanks!

**Comment by volkanceylan** [comment]
Override getViewOptions in your grid and set groupMetadataProvider yourself.

**Comment by lechu90ns** [comment]
Thank you, closing.
