### ISSUE TITLE
Disable Dates before todays date

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#4798]
Please help me to disable dates before today in date picker .

**Comment by vinaysalian** [comment]
Done.. thank You

**Comment by gfo2007** [comment]
@vinaysalian please can you share your solution. I want to disable future dates so that users will be prevented from picking dates that are beyond today.

**Comment by gfo2007** [comment]
@vinaysalian can you please share your code? I need to do something similar.

**Comment by vinaysalian** [comment]
> @vinaysalian can you please share your code? I need to do something similar.
We have done this in a popup and its working for disabling past dates. Still trying to make it work in forms  .
setTimeout(function () {
                            $('[name="ExpiryDate"]').datepicker("destroy");
                            $('[name="ExpiryDate"]').datepicker({ minDate: 0 });
