### ISSUE TITLE
User personal page

### ISSUE THREAD

**Issue by yankerssnh** [volkanceylan/Serenity#48]
How to realize User personal page. Where he can change password, remind forgot password and ... ?

**Comment by volkanceylan** [comment]
hmm, there are no such functionality in template, but i'll have a look

**Comment by yankerssnh** [comment]
maybe add standard .net ASP membership to Serenity?

**Comment by volkanceylan** [comment]
You can always use any kind of membership with Serenity. Just implement IAuthenticationService, IUserRetrieveService etc.

**Comment by volkanceylan** [comment]
Template 1.7.0 has sample change password and forgot password pages. By default, it places mails in App_Data\Mail directory. You need to set SMTP configuration in web.config.

Please try and let me know if something doesn't work properly.
