### ISSUE TITLE
Linux Ubuntu FileUpload Error

### ISSUE THREAD

**Issue by fikriisik** [volkanceylan/Serenity#4800]
Hi,
When I tried to upload a picture, I received the attached error. I'm trying Linux Ubuntu. Can you help me?  I'm having no problems loading documents.

<img width="1255" alt="Screen Shot 2020-01-07 at 22 46 45" src="https://user-images.githubusercontent.com/31852708/71925289-c6060380-31a1-11ea-8050-02931dacba8c.png">

**Comment by volkanceylan** [comment]
https://www.hanselman.com/blog/HowDoYouUseSystemDrawingInNETCore.aspx

might need to install missing packages

**Comment by fikriisik** [comment]
Thankyou.

**Comment by samdubey** [comment]
Installing following make things work on Linux Machine
**sudo apt install libc6-dev 
sudo apt install libgdiplus**

**Comment by DzunN86** [comment]
nice info. Thankyou.
