### ISSUE TITLE
Insert Date field is required!

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#4802]
After latest update Serenity.Web 3.12.0.
While inserting new row, System prompt for error message "Insert Date field is required!" Which is part of interface on respective rows.

Additionally, all Not null -read only fields on form are prompted error to input field while saving.

Please advise.

**Comment by volkanceylan** [comment]
Do you have NotNull on that field? If you are setting InsertDate yourself somewhere like SetInternalFields etc, you'll need to add [Insertable(false)] to the field or remove NotNull.

In older versions there was a bug that didn't validate NotNull/Required constraint for non-string fields properly.

**Comment by mustafalotiya** [comment]
Yes, Its not null field on **insert date**.  which was updating though IInsertLogRow. 
So , should we remove Not null?

**Comment by mustafalotiya** [comment]
Ok thanks for update.

**Comment by ga5tan** [comment]
but why is this happening before SetInternalFields?
I have behaviour, that sets internal fields, but it's not triggered before validation

**Comment by volkanceylan** [comment]
If you are setting a field in SetInternalFields it is not a [NotNull] field, or you have to add Insertable(false) or Updatable(false) or both.

This was working as it is now for all String fields, it wasn't working for non-string fields so far, we just fixed the bug, so this is how it should have been working.
