### ISSUE TITLE
Slick.checkboxSelectColumn

### ISSUE THREAD

**Issue by Mondaii** [volkanceylan/Serenity#4804]
I was trying to make checkbox for my rows on the grid using the plugin slick.checkboxselctcolumn, but i can't get the reference on my grid class, the Slick.checkboxSelectColumn gives an error saying that this proprety don't exist.

  protected getSlickOptions(): Slick.GridOptions {

            var checkboxSelector = new Slick.CheckboxSelectColumn

            var opt = super.getSlickOptions();
            opt.multiSelect = true;            
            //opt.ena = true;
            opt.selectedCellCssClass = "slick-row-selected";
            opt.enableCellNavigation = true;
            return opt;
        }

**Comment by lechu90ns** [comment]
don't you have to register the plugin first on while creating SlickGrid?

**Comment by Mondaii** [comment]
on the example in the slickgrid site they register the instance checkboxSelector like that 
grid.registerPlugin(checkboxSelector);
 but the type Slick in the grid don't have a CheckBoxSelectColumn, so i can't create the variable.

**Comment by JohnRanger** [comment]
You always can - as this is client-side javascript in the end. It is only typescript which complains and does not find the types for the plugins - but who cares :-)

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger  the typescript mapping classes - should eliminate the complaints in the editor. nodes >> typescript.. I think because it is a plugin that it is not getting a mapping automatically built in the typescript.

**Comment by stixoffire** [comment]
@Mondaii  I do not see where you registered the plugin.

Try this function in your constructor:  this.slickGrid.registerPlugin("slick.checkboxselctcolumn");
