### ISSUE TITLE
[Need Help] How to change date format of the system

### ISSUE THREAD

**Issue by Davidwsk** [volkanceylan/Serenity#4805]
Hi,

Default date format is MM/DD/YYYY.
How to change to DD/MM/YYYY?

For both column display and datepicker.

I think this is a very standard requirement for any application.
I would suggest to add a section concerning date format in the manual.

Thanks!

**Comment by choss21** [comment]
Hi 
Test Change file Web.config culture
Example
I use:
<globalization culture="es-MX" uiCulture="es-MX"/>

**Comment by arunkumar12712** [comment]
hi
try this in web config
<globalization culture="en-in" uiCulture="en-in" />

**Comment by arunkumar12712** [comment]
try this 
`<globalization` culture="en-in" uiCulture="en-in" />

**Comment by Davidwsk** [comment]
I am using dot net core version.
It seems that dot net core not make use of web.config.

Tried a few suggestion on the web but not seems working.
Anyone can give some suggestion?

Thanks!

**Comment by Davidwsk** [comment]
After some testing.
It seems that ASP.NET Core version date format not following any configuration file.
It follow the language setting.
(I not sure about ASP.NET MVC version.)

I changed "en":
![Date Format - 00](https://user-images.githubusercontent.com/31944359/72204736-281e7b80-34b6-11ea-9a72-e570442cafc4.png)
to "en-GB":
![Date Format - 01](https://user-images.githubusercontent.com/31944359/72204739-310f4d00-34b6-11ea-9462-f3edecd8b509.png)

It worked perfectly!

Thanks!

**Comment by sayuga** [comment]
See #4512  and #1184 if you are just looking to see how to change the display on the date on the interface.
