### ISSUE TITLE
When updating the marketplace.visualstudio.com to netcore3.1?

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#4806]
https://marketplace.visualstudio.com/items?itemName=VolkanCeylan.SereneSerenityApplicationTemplate

When updating the marketplace.visualstudio.com to netcore3.1?

Please.
Thank you very much!

**Comment by volkanceylan** [comment]
I won't soon, not everybody has VS 2019

**Comment by volkanceylan** [comment]
It's updated and .NET Core version is separated from MVC version as it only supports VS2019
