### ISSUE TITLE
Cancelable bulk action and Idle (session) timeout dont cooperate

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4807]
Hi,
is there a way for Long Running action to keep user logged out?
After some time I get "You will be logged out in X seconds progress bar dialog", but I cannot press Stay Logged in, because long running action dialog is displayed :(
Any idea how to avoid this?

**Comment by haoas** [comment]
hangfire or message queue，and notify user with signalr.

**Comment by ga5tan** [comment]
@haoas thx, but that seems a little overboard.
all is implemented in standard Serenity, just the logout counter does not take long running action in account

**Comment by haoas** [comment]
i didin't get.is there any sample?

**Comment by ga5tan** [comment]
this is cancelable bulk action:
https://serenity.is/demo/BasicSamples/CancellableBulkAction

and this is idle (session) timeout.
https://serenity.is/demo/AdvancedSamples/IdleTimeout

sorry, did not use proper terms

**Comment by JohnRanger** [comment]
Hmm, 
as Idle session timeout is premium feature, I can't really help you directly (I don't have Premium). 

But as a suggestion: Don't you have the possibility from within your long running action (which always returns to the client-side for updating the progress in the GUI) to reset this session timeout each time the long-running action returns to the client-side?

(To find what is done to reset the session timeout, look at the code which is executed when you would hit that "Stay Logged in" button - and then just execute that same code from your progress updater code).

Makes sense? :-)

With kind regards,

John

**Comment by volkanceylan** [comment]
Idle timeout works based on user action like moving mouse etc. If that's too few, either increase timeout, or you may disable it, it is optional.

**Comment by ga5tan** [comment]
@JohnRanger it worked. I just call
`localStorage.setItem('IdleTimeout:LastActivity', $.now().toString());`

in 

`executeForBatch(batch)`
