### ISSUE TITLE
Layout function "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by yaseenhejazi** [volkanceylan/Serenity#4808]
If added this code
`
        protected layout(): void {
            super.layout();
            this.view.setItems(this.view.getItems(), true);
        }
`
under OrderDetailsEditor for NorthWind sample, then I am getting "Maximum call stack size exceeded" error message

This issue is not happening in old version

Version tested and has this issue: 3.9.10, 3.12.1
Version tested and don't have this issue: 3.9.0

**Comment by volkanceylan** [comment]
Setting items in layout does not make any sense, layout is for layout only.

**Comment by yaseenhejazi** [comment]
I added set items under layout as I need to sort data before layout them
This in editor of master details dialog
I could not find any other place to add sorting data except this

Also it was working with me fine with older version (3.9.5)

**Comment by volkanceylan** [comment]
You may keep using older version if you want older behavior. You are using wrong location.
