### ISSUE TITLE
[3.12.1] "Tutorial - Movie Database - Listing Movies in Person Dialog" Error

### ISSUE THREAD

**Issue by Davidwsk** [volkanceylan/Serenity#4809]
When I follow the Tutorial, there is an error:
![getButtons error - 00](https://user-images.githubusercontent.com/31944359/72348615-bf353e80-3715-11ea-99a3-a80ba0bd47de.png)
![getButtons error - 01](https://user-images.githubusercontent.com/31944359/72348641-c9efd380-3715-11ea-8a22-41b030f0705a.png)

I found out that the error was caused by the following line.
![getButtons error - 02](https://user-images.githubusercontent.com/31944359/72348726-fdcaf900-3715-11ea-8d1e-0c1cea35a385.png)

It seems that the "toolbar" don't have the function "updateInterface" when "getButtons return null".

Think the system need to be updated.

Thanks!

**Comment by volkanceylan** [comment]
Hmm, thanks, yes need to add a null check there

**Comment by volkanceylan** [comment]
Fixed in 3.12.2
