### ISSUE TITLE
This code, should be deleted

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#481]
insertLogRow.InsertUserIdField[row] = Authorization.UserId.TryParseID();

**Comment by 107295472** [comment]
string Primary key This code is a problem

**Comment by volkanceylan** [comment]
Oh ok noticed where, will in next version

**Comment by 107295472** [comment]
public interface IIdField
    {
        Int64? this[Row row] { get; set; }
        bool IsIntegerType { get; }
    }
I don't know what to do with it    Int64? this

**Comment by 107295472** [comment]
Delete false

**Comment by 107295472** [comment]
But the realization of data recovery

**Comment by volkanceylan** [comment]
Serenity supported only integer ID before. It has to stay like this for backward compability.
