### ISSUE TITLE
Retrieving Data via fields of a Foreign Key

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4812]
Hi,
I have a Machine Table in the database and  have a MachinePeriod Table with the MachineID as a foreign key in the MachinePeriod table. I am creating a lookup class for Machine but need to make use the MachinePeriod fields as part of my criteria. How do I pull the Machine data through the MachineID on the MachinePeriod table?

Example
**MachinePeriodRow . Fields . MachineId . MachineRow . Fields . MachineCode** 

How can I implement the above in serenity?

**Comment by arunkumar12712** [comment]
try this 

var machinePeriodRow = new MachinePeriodRepository().List(Connection, new ListRequest { Criteria = new Criteria("MachineID") == MachineID }).Entities;

**Comment by gfo2007** [comment]
@arunkumar12712 
![MinRepExt Error](https://user-images.githubusercontent.com/14317420/72418582-06055180-3773-11ea-9f6c-13286935773c.PNG)

I get the error **"DbConnection is a type which is not valid in this context"**

**Comment by arunkumar12712** [comment]
using (var connection = SqlConnections.NewByKey("default"))
 {
    var machine = new MachineRepository().List(connection .................................)
 }
