### ISSUE TITLE
Use ImpersonatingAuthorizationService or TransientGrantor to temporarilly allow anonymous user to access an endpoint?

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#4815]
Hi there,
So I have written an API for my Serenity application which will interface with my Xamarin app using POST requests. In my separate API controllers, I have previously opened a new connection and then made my request to the database using an SqlQuery. I wasn't sure if this was a good idea since I was creating a new connection every call to the API, so I wanted to move from using connection.Query() and to use the repositories for each module of my application. However, I do not want to remove authorization attributes from my service endpoints (so that people can't just POST request into those as I will be putting certain limits on my separate API controllers), so I wanted to use either the ImpersonationAuthorizationService or TransientGrantor, however, both have failed most likely due to the reason that Postman (which is where I'm sending requests from) isn't authenticated with a Serenity account. A few questions:

- Was I right in using connection.Query() but wrong in the way I handled creating connections (and/or that I should use repository methods to interact with the db)?
- Is there another technique that I should be using?
- Is there a way to modify either the ImpersonationAuthorizationService or TransientGrantor so that I can use them on unauthenticated users?

Many thanks,
Marcus

**Comment by haoas** [comment]
By default, Authentication of  serenity app is based on the cookies.ImpersonationAuthorizationService  or TransientGrantor works after logged in.

**Comment by MarcusOy** [comment]
@haoas Yes, I am aware of this. What I would like to do is have a flow of:

Mobile App -> API Controller -> Service Endpoint -> Database Query -> Service Endpoint Response -> API Controller Response -> Mobile App

but with using an anonymous user. I want the API controller to temporarily allow use of the service endpoint (because of reasons displayed above), so that an anonymous user cannot skip the API controller and go straight to the service endpoint like this:

Whatever client -> Service Endpoint -> Database -> Service Response -> Whatever client

**Comment by volkanceylan** [comment]
In .NET connections are supposed to be opened latest possible and closed earliest time possible. Repositories don't open connections themselves, but an action filter in endpoints does. When you have a IDbConnection parameter in your action, it is automatically created, and automatically opened when used. So using SqlQuery or Repository does not make any difference. If a row has "*" permission, it can be used by anonymous users. Or simply remove ServiceAuthorize from the endpoint.

**Comment by volkanceylan** [comment]
Creating/opening a connection for every call is the right way to go, they are pooled anyway.

**Comment by MarcusOy** [comment]
Sounds good @volkanceylan . Knowing connection.Query() has no disadvantages compared to Repository endpoints in my case is great to know. Closing issue.
