### ISSUE TITLE
Converting ROW with all fields (including ListFields) to JSON C# string 

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#4817]
I have tried with
                    `var rowJson = JsonConvert.SerializeObject(row);`
and
                    `var rowJson = row.ToJson();`
but both of these give me the JSON with only table fields. How can I get the JSON with all the fields including ListField etc.

Thanks

**Comment by volkankalkan** [comment]
initially row returns only table fields. If you want to get relational fileds you must select these fileds first. Also you have ListField you must populate list before converting to json.
