### ISSUE TITLE
What's the command in .net core to generate code?

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#4818]
I use **dotnet sergen** but it didn't work!
```
+ dotnet sergen
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (无法执行，因为找不到指定的命令或文件。:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 ```

**Comment by sirichoke-kunwed** [comment]
dotnet sergen --help
run in xxx.web folder

**Comment by PanChenhao** [comment]
![image](https://user-images.githubusercontent.com/16734387/72673534-cd34e780-3aa6-11ea-8a4e-ed31c922f635.png)
Still the same error

**Comment by dviellaris** [comment]
For the ASP.NET Core Version, open a command prompt at your project folder and type
`dotnet sergen g`

sergen will list connections from appsettings.json. You can use TAB completion at the prompts

[https://serenity.is/docs/tutorials/movies/generating_code_for_movie_table](https://serenity.is/docs/tutorials/movies/generating_code_for_movie_table)
[https://serenity.is/docs/sergen/code_generator_sergen](https://serenity.is/docs/sergen/code_generator_sergen)

**Comment by PanChenhao** [comment]
@dviellaris thanks very much. I don't aware i need to excute dotnet sergen g in command prompt.
