### ISSUE TITLE
Some Field data not showing on Edit Form

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4822]
Hi,
The image below shows the edit form of VentLog which contains Heading Id as a foreign key.

Heading is Cascaded to Level since Level Id is a foreign key in the Heading table. 
LevelId is not a field in VentLog table so it has the attribute [NotMapped] in VentLogRow. It is there basically to help with the cascading effect of Heading.

However when I go to edit mode, as seen in the image, both Level and Heading which have values, go blank.

Please help.

**Comment by kilroyFR** [comment]
how did you fix this issue ? i am having same problem with a basic int notmapped attribute. Even when set in loadEntity() it displays nothing on form
