### ISSUE TITLE
casecade DropDowns in Forms

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4824]
Hello All.
I have 3 tables in  my project :
Country - Province - City 
I want to show all these fields in 3 CaseCade dropdowns.
After User selects Country, Filter province and After he Selects province Filter Cities Automatically.
Does anybody knows how to add these three fields in one form?

**Comment by fremar83** [comment]
Hi,
have a look at serenity guide. You have the exact example.

[https://volkanceylan.gitbooks.io/serenity-guide/howto/how_to_setup_cascaded_editors.html]
