### ISSUE TITLE
File Format File Upload

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4825]
Hi,
From the snippet code on the blog, how do I make the ProductImage dynamic so that the file is save in a particular folder based on a condition?

[ImageUploadEditor(FilenameFormat = "|SupplierId|/ProductImage/{4}")]
public String ProductImage
{
    get { return Fields.ProductImage[this]; }
    set { Fields.ProductImage[this] = value; }
}

**Comment by sayuga** [comment]
You'll probably want to add a handler on the repository file so that it can identify the supplier and assign the location accordingly. Start by overriding the save handler. You'll need to have it identify the currently selected supplier id

**Comment by gfo2007** [comment]
@sayuga long time. Hope you are doing great. I want to be able to save images into different folders based on a condition. 

For instance, if the employee belongs to the Finance Department, save the employee's image in the Finance folder, etc. 

I am struggling to make the [ImageUploadEditor(FileFormat)] save images into folders based on a condition. How do I make the path to an image or file dynamic and not static?
