### ISSUE TITLE
[Tutorial] Integrating Telerik Reporting with Serenity

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#4827]
Hi Serenity contributors and members!

I've just added a Wiki entry on how to integrate [Telerik Reporting](https://www.telerik.com/products/reporting.aspx) with Serenity: [Reporting: Integrating Telerik Reporting](https://github.com/volkanceylan/Serenity/wiki/Reporting:-Integrating-Telerik-Reporting)

@mustafalotiya, please check it out.

Please give feedback here if something doesn't work or is confusing.

I'll close this issue in a few days. I hope somebody finds this useful!

Cheers,
Edward

**Comment by mustafalotiya** [comment]
Thanks @edwardch . Appreciate your efforts.

Will try same today and revert back.

**Comment by edwardch** [comment]
If you want to try before you buy you can download the Trial version and you would use `Telerik.Reporting.Trial` in place of `Telerik.Reporting` for the packages. All the code remains the same...

Happy to help if you run into any issues.

**Comment by mustafalotiya** [comment]
@edwardch  Yes, I m trying with Trial version. 
Thanks.

**Comment by mustafalotiya** [comment]
Thank you. @edwardch  

Very well written wiki page. Able to load out of box telerik report.

Will customise some reports with actual database and try it out. may bug u for any issue.

![image](https://user-images.githubusercontent.com/23294782/72718099-b23da280-3b8e-11ea-9c42-5af93f45e4f9.png)

**Comment by edwardch** [comment]
Great to hear! 

I am struggling to get the connection string working on an Azure web app and also struggling to get it right with Docker. They _should_ behave in a similar fashion in that you can modify appsettings by setting environment variables.

Setting an environment variable named `Data__Default__ConnectionString` with my connection string works for my app data.

[Telerik uses the so-called "standard" way](https://docs.telerik.com/reporting/knowledge-base/how-to-implement-telerik-reporting-in-asp-net-core-mvc) of setting a connection string but I can't seem to figure out how to override it.
I've tried to set these environment variables with no successs:
`SQLCONNSTR_TelerikReports`
`ConnectionStrings__TelerikReports`
`ConnectionStrings__TelerikReports__ConnectionString`

If anyone has had to use another connection string setup with the .NET Core version and managed to get it right with Azure App Service or with Docker please let me know.

Thanks!

**Comment by edwardch** [comment]
For anyone reading the above comment(s).

I have updated the Wiki entry so that it works correctly when deploying to Azure on .NET Core, and also with docker. 

You can now set the environment variable `ConnectionStrings__TelerikReports__ConnectionString` and it will work.

**Comment by haajit** [comment]
Hi

**Comment by haajit** [comment]
Hi
I am beginner in serenity
and by use of this wiki I could show a report
but don't know how to show report after press this button
![image](https://user-images.githubusercontent.com/9511137/161427733-c07a0309-2c3f-418d-bc5e-0c5e52350088.png)

**Comment by haajit** [comment]
> Hi Serenity contributors and members!
> 
> I've just added a Wiki entry on how to integrate [Telerik Reporting](https://www.telerik.com/products/reporting.aspx) with Serenity: [Reporting: Integrating Telerik Reporting](https://github.com/volkanceylan/Serenity/wiki/Reporting:-Integrating-Telerik-Reporting)
> 
> @mustafalotiya, please check it out.
> 
> Please give feedback here if something doesn't work or is confusing.
> 
> I'll close this issue in a few days. I hope somebody finds this useful!
> 
> Cheers, Edward
Hi
I am beginner in serenity
and by use of this wiki I could show a report
but don't know how to show report after press this button
![image](https://user-images.githubusercontent.com/9511137/161427912-5de2b27b-fc85-4770-95f8-384723ef7c84.png)
