### ISSUE TITLE
Hide add button in Detail toolbar buttons Master/Detail Relation

### ISSUE THREAD

**Issue by asilmertkan** [volkanceylan/Serenity#4829]
Hi Volkan

It may be a simple question, but please note that I am someone who tries to learn programming after the age of 40. The learning curve is a bit steep for me, but I must say that, it did an amazing job. It is proud to see such studies as a Turkish.

I have a project and using Master/Detail relation in there. Users should be able to add rows in the new recording mode. But I must hide add button (top of Detail Grid) when it edit mode. I searched lots of sample code but I couldn't find true way for this. 

My English is not perfect. I hope explain exactly what I want to say.

**Comment by judejay** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/RemovingAddButton/RemovingAddButton.ts
Good luck! , close the issue if resolved.

**Comment by asilmertkan** [comment]
Hi judejay, 
Thank you for your advice, I already check this, but it does not meet my need. I need to control Master mode (new or edit mode) and if mode edit I must hide button (not Master Grid, top of Detail Editor).

**Comment by judejay** [comment]
So I don't know how you would do it, maybe try making two pages one editable, and then another readonly, and control by permissions. The DetailEditor is based off the GridEditorDialog, and the master off the GridEditorBase.

https://serenity.is/demo/BasicSamples/ReadOnlyDialog

**Comment by JohnRanger** [comment]
Hi @asilmertkan ,

the high level way is like this:

1) within your detail grid (xyzEditor.ts), you add two functions - one which hides the add button, another which shows the add button within the detail grid. Like this:

```ts
        public DisableAddButton()
        {
            this.toolbar.findButton('add-button').hide();
        }

        public EnableAddButton() {
            this.toolbar.findButton('add-button').show();
        }
```

2) As the detail grid gets created from within the Master dialog by defining the master-detail (e.g. with a field called detaillist), you have access to the detail grid methods from the master like this:

To enable the add button within the detail grid, use this from the master:
```ts
            // *** Button handling within detail grid ***
            this.form.DetailList.EnableAddButton();
```

To disable the add button within the detail grid, use this from the master:
```ts
            // *** Button handling within detail grid ***
            this.form.DetailList.DisableAddButton();
```

In a similar way, you can can create additional action methods within the detail grid and run them from the master for anything you like to do within the detail grid.

Hope this helps you.

With kind regards,

John

**Comment by asilmertkan** [comment]
Hi @JohnRanger ,

The method you sent, solved my problem completely. I am grateful for your support. 

Thank you.

**Comment by stixoffire** [comment]
@JohnRanger  

This is actually more useful information than just enabling and disabling buttons in the details editor.

This method works to set properties or access methods in the detailseditor (this manner of doing it never dawned on me). 
I had a need to acquire a value that was only available in the parentdialog and use in the details editor and spent lots of time trying to figure that out. I ended up reading this answer for research on another issue and had that epiphany moment of aha. 
`this.form.DetailList.MyMethod(value_to_pass_in);`

I created a public method in my detailseditor and passed in the value to set the property value.
While I could have set it directly, I needed to do some processing first.
This little tidbit of accessing the details editor gave me the aha moment that I needed.

Perhaps you could make a simple write up in your Basic Building blocks series?

**Comment by spirit1989hcm** [comment]
Can you help me remove search bar?
