### ISSUE TITLE
How to extend Logging?

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4830]
Hi
I use Log.Info (and others) to log various events. But I would like to add bunch of app specific columns (for further filtering and querying), rather than trying parse single LogMessage string.

Any idea on how to extend Serenitys logging functionality?

**Comment by kilroyFR** [comment]
I have personnally replaced the standard Serenity log (FileLogger) by Serilog (to generate json log files that are later pushed into an ELK for analysis, filtering etc).

Serenity is based on Serenity.Abstractions.ILogger.

so i basically created a class that implements Write like this :  

```
  public class SerilogLogger : Serenity.Abstractions.ILogger
  {
    public SerilogLogger(string indexName, string appName)
    {
      LoggerBase.Configure(indexName, appName); // This function create the serilog object with indexname and appname additional infos
    }

    public void SetLogLevel(string logEventLevel)
    {
      LoggerBase.SetLogLevel(logEventLevel); // Set allows to dynamically change log level
    }

    public string GetLoggerUri()
    {
      return LoggerBase.LoggerUri;
    }

    public void Write(LoggingLevel level, string message, Exception exception, Type source)
    {
      var msgTrimmed = message.Replace("\n", " ").Replace("\r", " ");

      switch (level)
      {
        case LoggingLevel.Verbose:
        case LoggingLevel.Debug:
          Log.Debug(msgTrimmed);
          break;

        case LoggingLevel.Error:
          Log.Error(msgTrimmed);
          break;

        case LoggingLevel.Warn:
          Log.Warning(msgTrimmed);
          break;

        case LoggingLevel.Info:
          Log.Information(msgTrimmed);
          break;
      }
    }
  }
```
Serilog is used (so the general Log object is available everywhere).
In the SiteInitialization.ApplicationStart() i registered the new logger this way : 

```
        // Logger - Serilog (not the standard Serenity logger - FileLogger)
        _logger = new SerilogLogger("my app", System.Web.Hosting.HostingEnvironment.ApplicationVirtualPath.Replace("/", ""));
        registrar.RegisterInstance<ILogger>(_logger);
```

**Comment by ga5tan** [comment]
@kilroyFR - thank you sir.
so u are using this one:
https://serilog.net/

instead of Serenitys Log ?
cause I still see Log in your Write function.

ELK is this?
https://www.elastic.co/what-is/elk-stack

I will study it some, but sounds like overkill. I just wanna be able to filter by level and user, maybe couple of specific actions (login, logout, search).
But I dont wanna parse logged text, but store relevant info into separate columns.

**Comment by kilroyFR** [comment]
yes i am using serilog.sinks.elasticsearch to record log into json files that are automatically pushed into elastic nosql db (later accessed using Kibana for querying on log).
The Write is doing the job to route serenity Log events into my custom serilogger.
Serilog is used to record unstrcuctured events (that are not colum/row the way we use a regular DBMS). But you can use other Serilog Sinks to format your log events not in Json but save into a regular db.
ex : https://github.com/lucascebertin/Serilog.Sinks.Oracle

**Comment by Moheeb-U** [comment]
@ga5tan couple of days ago, I needed to extend logger in one of my project. I just share my solution here if it helps. I have used SqlLogger instead of normal logging.

Normal Logging is working like Log.Info() or Log.Debug() etc. 
But I wanted to store some additional information and like to filter if necessary. Thats why SqlLogger.

I have copied SqlLogger.cs class into project and renamed to MySqlLogger (Common --> MySqlLogger) and added UserId, ZoneInfoId and ModuleId parameters under write function.
SqlLogger.cs class can be found from https://github.com/volkanceylan/Serenity/blob/master/Serenity.Data/Utility/SqlLogger.cs

In Web.Config, I have commented file logger key and added sql logger key like below:
`	<!--<add key="Logging" value="{  File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0,  Level: 'Info' }" />-->`
`	<add key="Logging" value="{ ConnectionKey:'Audit', InsertCommand:'Common_SystemLogs', Level:'Info' }" />`

I have used Stored Procedure instead of insert command.

In App_Start --> SiteInitialization.cs,
	I have added registrar.RegisterInstance<ILogger>(new Water.Common.MySqlLogger());

I have added following table and stored procedure in my database.

` CREATE TABLE [dbo].[SystemLogs](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EventDate] [datetime] NOT NULL,
	[LogLevel] [nvarchar](10) NULL,
	[LogMessage] [nvarchar](max) NULL,
	[Exception] [nvarchar](max) NULL,
	[SourceType] [nvarchar](200) NULL,
	[UserId] [int] NULL,
	[ZoneInfoId] [int] NULL,
	[ModuleId] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO`

`
CREATE PROCEDURE [dbo].[Common_SystemLogs]
	@date			Datetime
	,@level			NVARCHAR(50)
	,@message		NVARCHAR(MAX)
	,@exception		NVARCHAR(MAX)
	,@source		NVARCHAR(200)
	,@UserId		INT
	,@ZoneInfoId	INT
	,@ModuleId		INT
AS
BEGIN
INSERT INTO [dbo].SystemLogs
           (EventDate
           ,LogLevel
			,LogMessage
           ,Exception
           ,SourceType
           ,UserId
           ,ZoneInfoId
           ,ModuleId)
     VALUES
           (
			   @date    
			  ,@level
			  ,@message
			  ,@exception
			  ,@source
			  ,@UserId
			  ,@ZoneInfoId
			  ,@ModuleId
		  )
END
GO`

my MySqlLogger.cs file looks like following -

`
using Serenity;
using Serenity.Abstractions;
using Serenity.ComponentModel;
using Serenity.Data;
using Serenity.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;

namespace Water.Common
{
    /// <summary>
    /// A simple logger that logs to an SQL table.
    /// </summary>
    /// <seealso cref="Serenity.Abstractions.ILogger" />
    /// <seealso cref="System.IDisposable" />
    public class MySqlLogger : ILogger, IDisposable
    {
        private object sync = new object();
        private int inProgress;
        private Queue<Dictionary<string, object>> queue = new Queue<Dictionary<string, object>>();
        private AutoResetEvent signal = new AutoResetEvent(false);

        /// <summary>
        /// Initializes a new instance of the <see cref="SqlLogger"/> class.
        /// </summary>
        public MySqlLogger()
        {
            var settings = Config.TryGet<LogSettings>() ?? new LogSettings();
            ConnectionKey = settings.ConnectionKey;
            InsertCommand = settings.InsertCommand;
            new Thread(Worker).Start();
        }

        /// <summary>
        /// Finalizes an instance of the <see cref="SqlLogger"/> class.
        /// </summary>
        ~MySqlLogger()
        {
            Dispose(false);
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
        }

        private void Dispose(bool disposing)
        {
            lock (sync)
            {
                queue = null;
            }

            if (disposing)
                GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Flushes this instance.
        /// </summary>
        public void Flush()
        {
            while (true)
            {
                lock (sync)
                {
                    if (inProgress == 0 && (queue == null || queue.Count == 0))
                        return;
                }
                Thread.Sleep(1);
            }
        }

        private void Worker()
        {
            while (queue != null)
            {
                signal.WaitOne();

                if (queue == null)
                    break;

                while (true)
                    try
                    {
                        Dictionary<string, object> parameters;
                        lock (sync)
                        {
                            if (queue == null || queue.Count == 0)
                                break;

                            parameters = queue.Dequeue();
                            inProgress++;
                        }

                        try
                        {
                            using (var connection = SqlConnections.NewByKey(ConnectionKey))
                            {

                                connection.Open();
                                using (IDbCommand command = connection.CreateCommand())
                                {
                                    IDbDataParameter pdate = command.CreateParameter();
                                    pdate.ParameterName = "@date";
                                    pdate.Value = parameters["date"];
                                    command.Parameters.Add(pdate);

                                    IDbDataParameter plevel = command.CreateParameter();
                                    plevel.ParameterName = "@level";
                                    plevel.Value = parameters["level"];
                                    command.Parameters.Add(plevel);

                                    IDbDataParameter pmessage = command.CreateParameter();
                                    pmessage.ParameterName = "@message";
                                    pmessage.Value = parameters["message"];
                                    command.Parameters.Add(pmessage);

                                    IDbDataParameter pexception = command.CreateParameter();
                                    pexception.ParameterName = "@exception";
                                    pexception.Value = parameters["exception"];
                                    command.Parameters.Add(pexception);

                                    IDbDataParameter psource = command.CreateParameter();
                                    psource.ParameterName = "@source";
                                    psource.Value = parameters["source"];
                                    command.Parameters.Add(psource);

                                    IDbDataParameter pUserId = command.CreateParameter();
                                    pUserId.ParameterName = "@UserId";
                                    pUserId.Value = parameters["UserId"];
                                    command.Parameters.Add(pUserId);

                                    IDbDataParameter pZoneInfoId = command.CreateParameter();
                                    pZoneInfoId.ParameterName = "@ZoneInfoId";
                                    pZoneInfoId.Value = parameters["ZoneInfoId"];
                                    command.Parameters.Add(pZoneInfoId);

                                    IDbDataParameter pModuleId = command.CreateParameter();
                                    pModuleId.ParameterName = "@ModuleId";
                                    pModuleId.Value = parameters["ModuleId"];
                                    command.Parameters.Add(pModuleId);


                                    command.CommandType = CommandType.StoredProcedure;
                                    command.CommandText = InsertCommand;
                                    command.ExecuteNonQuery();
                                }
                                connection.Close();
                            }
                        }
                        finally
                        {
                            inProgress--;
                        }
                    }
#if !NET45
                    catch (Exception ex)
                    {

                    }
#else
                    catch (Exception ex)
                    {
                        var internalLogger = Dependency.TryResolve<ILogger>("Internal");
                        if (internalLogger != null)
                            internalLogger.Write(LoggingLevel.Fatal, null, ex, this.GetType());
                    }
#endif
            }
        }

        /// <summary>
        /// Gets or sets the connection key.
        /// </summary>
        /// <value>
        /// The connection key.
        /// </value>
        public string ConnectionKey { get; set; }

        /// <summary>
        /// Gets or sets the insert command.
        /// </summary>
        /// <value>
        /// The insert command.
        /// </value>
        public string InsertCommand { get; set; }

        [SettingScope("Application"), SettingKey("Logging"), Ignore]
        private class LogSettings
        {
            public string ConnectionKey { get; set; }
            public string InsertCommand { get; set; }
        }

        /// <summary>
        /// Writes the specified level log message.
        /// </summary>
        /// <param name="level">The level.</param>
        /// <param name="message">The message.</param>
        /// <param name="exception">The exception.</param>
        /// <param name="source">The source.</param>
        public void Write(LoggingLevel level, string message, Exception exception, Type source)
        {
            var connectionKey = ConnectionKey;
            var insertCommand = InsertCommand;

            var parameters = new Dictionary<string, object>();
            parameters.Add("date", DateTime.Now);
            parameters.Add("level", EnumMapper.GetName(level));
            parameters.Add("message", message);
            parameters.Add("exception", exception != null ? exception.ToString() : string.Empty);
            parameters.Add("source", source != null ? source.FullName : string.Empty);
            parameters.Add("UserId", int.Parse(Authorization.UserId));
            parameters.Add("ZoneInfoId", ((UserDefinition)Authorization.UserDefinition).ZoneInfoId);
            parameters.Add("ModuleId", ((UserDefinition)Authorization.UserDefinition).ModuleId);


            lock (sync)
                queue.Enqueue(parameters);

            signal.Set();
        }
    }

}
`

**Comment by ga5tan** [comment]
@Moheeb-U thanks mate, u've been the most helpful.
that's what I was looking for!
