### ISSUE TITLE
Error Deploying in IIS

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4831]
Hi,
I have deployed my application in IIS. However, it appears jquery is unable to load correctly and throws the error below when trying to load and of the grid pages. Please help.

![Jquery Error](https://user-images.githubusercontent.com/14317420/72821982-37958580-3c69-11ea-9b5b-92d8ede13500.PNG)

**Comment by fremar83** [comment]
Looks like a security access problem. did you check the servicePool connection on Database ?

**Comment by gfo2007** [comment]
@fremar83 I feel the same way about it being a security access problem since it runs perfectly from the development server from Visual Studio.

Where can I check the service pool?

**Comment by fremar83** [comment]
Just have a look at this :   
[https://www.syncfusion.com/kb/6897/how-to-add-permission-for-iis-application-pool-to-access-sql-server-database](url)

**Comment by gfo2007** [comment]
@fremar83 the link you provided doesn't show anything. But I doubt it's a SQL server issue since I am able to login via SQL server without any issue. It rather appears jQuery is not being loaded correctly which I suspect it's some permissions issue but I have given full control to IIUSR so I still don't get why jQuery is not being loaded.

**Comment by fremar83** [comment]
I'm sorry. It seems I don't use the link button properly. Just paste the link bellow to a new nav page.

https://www.syncfusion.com/kb/6897/how-to-add-permission-for-iis-application-pool-to-access-sql-server-database

**Comment by fremar83** [comment]
Curiously, it seems that link is fonctional when we don't use the "link button"...

**Comment by gfo2007** [comment]
@fremar83 I have checked the link. It's not really different from what I have done. I am able to connect fine to the database. It appears IIS is unable to find the path for the file jquery-3.3.1.js resulting in the jQuery not being loaded and throwing the error.

**Comment by gfo2007** [comment]
@fremar83 this is what I found in google chrome console. It appears the javascript files are are not being loaded in IIS. See image below.

![JS Files not loaded](https://user-images.githubusercontent.com/14317420/72878711-60625d00-3cf3-11ea-8d43-b344eae5bc61.PNG)

**Comment by gfo2007** [comment]
Solved.

I just saw the same issue on #4424 and the answer was right there.
