### ISSUE TITLE
How to change the format of code generator - sergen

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4833]
Dear all,
I know if we want to change the format of code generator, we could change the  .scriban file. but I don't know after I change the .scriban file, which folder i need to put this file?

**Comment by hannesb** [comment]
Use 'Custom templates path' in the 'Generation Options' dialog of sergen.

**Comment by Nathan2020-0126** [comment]
@hannesb  thank your for your feedback very much. What I am using is .net core version. When i try to use dotnet sergen -g in cmd, I cannot find the 'Generation Opetions'. Could you please give me any more hints?

**Comment by volkanceylan** [comment]
.NET Core version has options in sergen.json as it has no UI, see GeneratorConfig.cs for format information.
