### ISSUE TITLE
Convert BootstrapFormList to Excel

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4834]
I am success for implementing BootstrapFormList from
https://serenity.is/demo/AdvancedSamples/BootstrapFormList.

But How I  can convert to Excel.

Dear All, I need a help more .. thanks

**Comment by arunkumar12712** [comment]
try this

`List<Test> obj= new    List<Test>();
 IEnumerable<string> column = typeof(Test).GetProperties().Select(t => t.Name);
            var report = new DynamicDataReport(obj, column, typeof(Test));
            var bytes = new ReportRepository().Render(report);
            return ExcelContentResult.Create(bytes, "fileName_" +
                DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".xlsx");`
