### ISSUE TITLE
Generating a hyperlink

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4837]
Hi,
I have files that are already stored in folders on a network shared drive. Some properties of the file like MI No and Date Signed are entered via a serenity form.

Since the files are already stored at their right locations, I don't want to use serenity to upload the file. Instead, I want to generate a hyperlink on the form that points to the file so that when you click on the hyperlink, it opens the file in a browser.

Can anyone show me a code snippet on how to do this?

**Comment by judejay** [comment]
The browser blocks the path.
