### ISSUE TITLE
Master Detail GridEditDialog Error

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4839]
Hi,
I am creating a detail dialog to be able to display the detail form in the by clicking a button on the master form as shown in the Movie Tutorial.

However, the Typescript file is showing the errors below to my surprise.

![MasterDetail Form Error](https://user-images.githubusercontent.com/14317420/73134449-8c048080-402e-11ea-9a61-edcb5a7b44d7.PNG)

**Comment by arunkumar12712** [comment]
probably miscellaneous files issue in visual studio reopen visual studio it might be problem solved.
