### ISSUE TITLE
Masked Input not working

### ISSUE THREAD

**Issue by Thebenmandude** [volkanceylan/Serenity#484]
Hi, I have also tried to mask a String field by using MaskedEditor(Mask="(###) ### ####") in my Row.cs. I have also added the following to my cshtml file but I still cannot get the mask to work.
"< script src="~/Scripts/input-mask/jquery.inputmask.js" type="text/javascript">"

When opening the dialog I get the following: 
![be03ee2e-f508-11e5-9ae2-38373e8670e3](https://cloud.githubusercontent.com/assets/6910368/14150670/6c5a86d4-f6aa-11e5-99a0-d36e23e3a63e.png)
![da1f428e-f508-11e5-9bc7-b328c4b99cdc](https://cloud.githubusercontent.com/assets/6910368/14150671/6c5e2ce4-f6aa-11e5-9c1d-151f44fb675a.png)

Am I missing something? And also, DisplayFormat does not seem to make any difference.

**Comment by volkanceylan** [comment]
It was using this one:

http://digitalbush.com/projects/masked-input-plugin/

Though i didn't try it for long.

**Comment by Thebenmandude** [comment]
Thanks, got it working!

**Comment by rolembergfilho** [comment]
@Thebenmandude ,

could you post or gist how you implement this?

and how mask you used to phone mask?

**Comment by gmg1967** [comment]
Referencing the "~/Scripts/input-mask/jquery.inputmask.js" script didn't work for me either, but using the script from the above mentioned digitalbush link worked. Here is what you have to do:

- Download the minified script from the above mentioned digitalbush link and include it in your project (e.g. at ~/Scripts/digitalbush/jquery.maskedinput.min.js.)

- Insert a link to the script to the .cshtml file: 
`@Html.Script("~/Scripts/digitalbush/jquery.maskedinput.min.js")`

- Add the MaskedEditor attribute to the respective properties in your Row.cs file:
`[DisplayName("Phone"), Size(24), MaskedEditor(Mask ="(999) 999-9999")]`

**Comment by volkanceylan** [comment]
I should include it by default in Serene
