### ISSUE TITLE
thumbnail proportion problem

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#4841]
Hi,
In #2443, it seems that thumbnails keep proportions.
Then , why mine do not ?

![00000004_xss2u34uvqnn2](https://user-images.githubusercontent.com/28645113/73387426-d573fa80-42d0-11ea-815f-887491b00801.jpg)
![00000004_xss2u34uvqnn2_t](https://user-images.githubusercontent.com/28645113/73387434-d9a01800-42d0-11ea-8f3e-3b073f0c03d6.jpg)

Thank's

**Comment by volkanceylan** [comment]
Unless you changed thumbnail mode to PreserveRatioNoFill, it shouldn't. Closing as old issue.
