### ISSUE TITLE
Trial/demo mode 

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#4844]
Has anyone created a trial/demo mode for an existing serenity app?
Suggestions, best practices?

Thanks

**Comment by edwardch** [comment]
I think this depends entirely on how you want your demo/trial users to be able to use your software.

You might want to put an expiry date on your Users table, then do any custom behaviour based on what its value is. Look at how the TenantID is used in the multi-tenancy examples, and then use this ExpiryDate in a similar fashion.

For new users you could set this value to something like Now() + 30 days, and then you could set this value to `NULL` for regular non-trial users. 

You may check this date on user login, and then whenever they want to perform some limited action. This might be restricting adding new records, limiting the number of records a user can have, restricting access to certain functionality, etc - this would be entirely up to you to decide.

Disclaimer - I've never done this or needed to and I'm sure there are other ways to achieve this, you just need to think and plan out what you want your trial users to be allowed/not allowed to do.

Good luck!
