### ISSUE TITLE
Turn off sidebar expand on hover

### ISSUE THREAD

**Issue by hansen168** [volkanceylan/Serenity#4847]
It seems like :
$.AdminLTE.options.sidebarExpandOnHover is already false.
But how come it has no effect.
Sidebar always expand on hover. Any help to turn it off?

**Comment by JohnRanger** [comment]
Hi @hansen168 ,

as this is not a Serenity problem but an AdminLTE one, please have a look at this issue directly over at AdminLTE: https://github.com/ColorlibHQ/AdminLTE/issues/1234#issuecomment-320605497

With kind regards,

John
