### ISSUE TITLE
Extending lokupeditor to add additional markup

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#4848]
How can i extend lookupeditor to add additional markup after o select2 dropdown (belwo select2 markup)

Something like this

![image](https://user-images.githubusercontent.com/59920049/73747234-76026880-4770-11ea-84bb-5275f45bf61c.png)

![image](https://user-images.githubusercontent.com/59920049/73747612-38520f80-4771-11ea-8b26-64bb8e2a82db.png)

its not for list of options inside select2 dropdown,
Its additional div after selecting entries from dropdown

**Comment by minhhungit** [comment]
there are some samples for example https://github.com/volkanceylan/Serenity/wiki/Lookup-Editors:-How-to-Create-Lookup-Editor-for-code-description-tables 

it might help you

**Comment by djabeeryusuf** [comment]
Thanks @minhhungit ,
Its not to format the options inside select2 editor,
Its basically to display additional div after the dropdown.

selec2Options.formatResult and selec2Options.formatSelection gives control to modify the how options are rendered inside.

this is to basically show a custom widget (a simple div) belwo the select2 dropdown

**Comment by volkanceylan** [comment]
Yes formatResult and formatSelection, see Select2 docs
