### ISSUE TITLE
Field read before assigned value error

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#485]
I have modified UserDefinition to include user departments as shown below:

        private UserDefinition GetFirst(IDbConnection connection, BaseCriteria criteria)
        {
            var user = connection.TrySingle<Entities.UserRow>(criteria);
            if (user != null)
                return new UserDefinition
                {
                    UserId = user.UserId.Value,
                    Username = user.Username,
                    Email = user.Email,
                    DisplayName = user.DisplayName,
                    IsActive = user.IsActive.Value,
                    Source = user.Source,
                    PasswordHash = user.PasswordHash,
                    PasswordSalt = user.PasswordSalt,
                    UpdateDate = user.UpdateDate,
                    LastDirectoryUpdate = user.LastDirectoryUpdate,
                    DeptNbr = user.DeptNbr,
                    Departments = user.Departments
                };

            return null;
        }

The UserRow code to load related departments looks like this:

        // Related departments
        [DisplayName("Department(s)"), LookupEditor(typeof(DepartmentRow), Multiple = true), ClientSide]
        [LinkingSetRelation(typeof(UserDepartmentsRow), "UserId", "DeptNbr")]
        public List<String> Departments
        {
            get { return Fields.Departments[this]; }
            set { Fields.Departments[this] = value; }
        }

I get the following error:

 Departments field on UserRow is read before assigned a value!
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: Departments field on UserRow is read before assigned a value!

Source Error:

Line 113:        public List<String> Departments
Line 114:        {
Line 115:            get { return Fields.Departments[this]; }
Line 116:            set { Fields.Departments[this] = value; }
Line 117:        }

Source File: C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Administration\User\UserRow.cs    Line: 115

Stack Trace:

[InvalidOperationException: Departments field on UserRow is read before assigned a value!]
   Serenity.Data.Field.CheckUnassignedRead(Row row) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\FieldTypes\Field.cs:333
   Serenity.Data.GenericClassField`1.get_Item(Row row) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\FieldTypes\GenericClassField.cs:34
   LCBudgets.Administration.Entities.UserRow.get_Departments() in C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Administration\User\UserRow.cs:115
   LCBudgets.Administration.UserRetrieveService.GetFirst(IDbConnection connection, BaseCriteria criteria) in C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Administration\User\Authentication\UserRetrieveService.cs:18
   LCBudgets.Administration.<>c__DisplayClass4_0.<ByUsername>b__0() in C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Administration\User\Authentication\UserRetrieveService.cs:54
   Serenity.TwoLevelCache.GetInternal(String cacheKey, TimeSpan localExpiration, TimeSpan remoteExpiration, String groupKey, Func`1 loader, Func`2 serialize, Func`2 deserialize) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\TwoLevelCache.cs:251
   Serenity.TwoLevelCache.Get(String cacheKey, TimeSpan localExpiration, TimeSpan remoteExpiration, String groupKey, Func`1 loader) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\TwoLevelCache.cs:45
   LCBudgets.Administration.UserRetrieveService.ByUsername(String username) in C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Administration\User\Authentication\UserRetrieveService.cs:51
   Serenity.Authorization.get_UserDefinition() in P:\Sandbox\Serene\Serenity\Serenity.Core\Authorization\Authorization.cs:41
   Serenity.Authorization.get_UserId() in P:\Sandbox\Serene\Serenity\Serenity.Core\Authorization\Authorization.cs:55
   LCBudgets.Navigation.NavigationModel..ctor() in C:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Modules\Common\Navigation\NavigationModel.cs:18
   ASP._Page_Views_Shared__Layout_cshtml.Execute() in c:\ngs-projects\LCBudgetsProduct\LCBudgets\LCBudgets.Web\Views\Shared\_Layout.cshtml:85
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +105
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +90
   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +232
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +63
   System.Web.WebPages.WebPageBase.PopContext() +237
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +98
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +235
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +291
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +173
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9644037
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

I thought [LinkingSetRelation] attribute will load related departments. Do I have to do something special to load related departments?

**Comment by 107295472** [comment]
List<String>Field, you can also this type?

**Comment by 107295472** [comment]
see Serenity.Data.Entity.FieldTypes

**Comment by 107295472** [comment]
A user a number of departments

**Comment by 107295472** [comment]
Stack Trace:    Don't look confused

**Comment by c9482** [comment]
Added this code to populate the departments:

        private UserDefinition GetFirst(IDbConnection connection, BaseCriteria criteria)
        {
            **var user = connection.TrySingle<Entities.UserRow>(criteria);
            if (user != null)
            {
                List<UserDepartmentsRow> udrs = new UserDepartmentsRepository().GetExisting(connection, user.UserId.Value);
                List<String> deptNbrs = new List<string>();
                foreach (UserDepartmentsRow udr in udrs)
                {
                    deptNbrs.Add(udr.DeptNbr);
                }**

                return new UserDefinition
                {
                    UserId = user.UserId.Value,
                    Username = user.Username,
                    Email = user.Email,
                    DisplayName = user.DisplayName,
                    IsActive = user.IsActive.Value,
                    Source = user.Source,
                    PasswordHash = user.PasswordHash,
                    PasswordSalt = user.PasswordSalt,
                    UpdateDate = user.UpdateDate,
                    LastDirectoryUpdate = user.LastDirectoryUpdate,
                    DeptNbr = user.DeptNbr,
                    Departments = deptNbrs
                };
            }

            return null;
        }
