### ISSUE TITLE
RetrieveRequestHandler - Need to turn off Entity Validation Error

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4851]
Hey guys!

Is there a way to disable the ValidationError exception when entity is not found while processing the query in RetrieveRequestHandler<T> class? I would be great to get such an option while inheriting this class since I use it in customized logic and I am predicting that a specific record might not be in DB yet.

Thanks!

**Comment by volkanceylan** [comment]
You may also use a ListRequestHandler with Details mode and equality filter on id column

**Comment by lechu90ns** [comment]
That worked. Thank you!

Closing.
