### ISSUE TITLE
Could not find resource named script.sql

### ISSUE THREAD

**Issue by matt-tro** [volkanceylan/Serenity#4853]
I have created a project without northwind samples and I have created a SQL script to create custom database but, when I launch IIS, VS brings me back following error:

InvalidOperationException: Could not find resource named MagazzinoVigna.Migrations.DefaultDB.DBVigna.sql in assemblies MagazzinoVigna.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

How can I resolve?

**Comment by kuyu7766** [comment]
how did you resolved?   can you tell me ? thank you!

**Comment by matt-tro** [comment]
You must embed the SQL script in the project going in Properties of the script and changing the Build Action option setting 'Embedded resource'
