### ISSUE TITLE
Is serenity a good choice for document management?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4855]
One question:
Is serenity a good choice for document management? and is there any example available to start with?

**Comment by fredvaliant** [comment]
It depends, what are the contents of your document management?

**Comment by ms4hafiz** [comment]
I want to upload documents as PDF with a functionality to view PDF online.

**Comment by JohnRanger** [comment]
@ms4hafiz ,

you are "hanging" around here in this forum long enough to probably know what Serenity Framework's focus is - namely data-centric work :-)

Everything you need for data-centric work (Pull reports via filtering, export to Excel, enter new data, etc) is provided out-of-the box by SF. This includes file upload.

Everything else you have to add yourself. So the part of viewing PDF online you have to code yourself and work with other frameworks/toolset to provide this feature.

Also I have found it easier over time to store uploaded files as binary blobs directly within the SQL database and only use the upload feature to get the data to the server. This functionality you owuld also have to program yourself.

With kind regards,

John

**Comment by ms4hafiz** [comment]
@JohnRanger 
Thanks
