### ISSUE TITLE
GridEditorBase without MasterDetails Relation

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#4856]
How to use GridEditorBase without masterdetail relation of foreign key
eg, if i want to hardcode the key it extension of GridEditorBase (to show list of entitities inline in other form)

![image](https://user-images.githubusercontent.com/59920049/74148149-2a433980-4c1e-11ea-8612-ec4aed8f2434.png)

**Comment by JohnRanger** [comment]
Hi @djabeeryusuf ,

it is a bit difficult to understand what you want to achieve. Can you provide a quick mockup how the result should look like and what you want to filter how?

With kind regards,

John

**Comment by djabeeryusuf** [comment]
> Hi @djabeeryusuf ,
> 
> it is a bit difficult to understand what you want to achieve. Can you provide a quick mockup how the result should look like and what you want to filter how?
> 
> With kind regards,
> 
> John

Basically when we have Foreign key & Master-Details relation and when we use that with Grid editor base, it loads all records (eg data from events table based on that key), i don't want to define foreign key relation, rather want to load the records on grid-like this.

public getGriditems(){
items = "select * from events where departmentid=this.form.departmentid"
}
