### ISSUE TITLE
VS  Build fail due to unrecognized element "Remove" 

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#4858]
This is to inform in the event anyone else runs into this. 

Recently had to change over to a new laptop since my last system is simply on its last leg. As I generated a fresh .Net Serenity (not the Core) build to play with for a new project, I ran into a issue were the project file was not being built properly, kept getting a project load fail error followed by the following error output: 

c:\Users\sayug\Documents\Visual Studio 2015\Projects\Serene3\Serene3\Serene3.Web\Serene3.Web.csproj : error  : The attribute "Remove" in element <None> is unrecognized.  c:\Users\sayug\Documents\Visual Studio 2015\Projects\Serene3\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.props

What appears to be the issue is that the Microsoft.TypeScript.MSBuild.props has a attribute reference to "Remove" that it's not recognizing. This is being used as part of the <ItemGroup> reference in the file. I just commented it out to get the project back up and running. 

Should end up looking like this: 

```
 <ItemGroup Condition="'$(EnableDefaultItems)' == 'true' AND '$(EnableDefaultTypeScriptItems)' == 'true'">
    <!--<None Remove="$(DefaultTypeScriptIncludePattern)" Condition="'$(EnableDefaultNoneItems)' == 'true'" />
    <Content Remove="$(DefaultTypeScriptIncludePattern)" Condition="'$(EnableDefaultContentItems)' == 'true'" />-->
    <TypeScriptCompile Include="$(DefaultTypeScriptIncludePattern)" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>

```

All in all I believe this is just a small bug from setting up the exclusion of Typescript files from the default items in the Core projects.

**Comment by volkanceylan** [comment]
Thanks @sayuga, newer TypeScript msbuild package is not compatible with VS2015, need 2017+

**Comment by Nathan2020-0126** [comment]
I have created a new project, also cannot build successful. I got a smilar issue with you, but a litter different.  Could you please help me to check it?

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.props.	SERENE.Web	D:\02_工作\05_我的项目\Serene\SERENE\SERENE.Web	D:\02_工作\05_我的项目\Serene\SERENE\SERENE.Web\SERENE.Web.csproj	1897	生成
