### ISSUE TITLE
ImageUpload Thumbnail

### ISSUE THREAD

**Issue by KishanVaishnani** [volkanceylan/Serenity#4861]
Thumbnail not creating in folder

**Comment by edwardch** [comment]
What version of Serenity are you using?

See #4405 or ["thumbnail" issues](https://github.com/volkanceylan/Serenity/search?q=Thumbnail&type=Issues)

**Comment by KishanVaishnani** [comment]
![image](https://user-images.githubusercontent.com/60768270/74525866-2e39c900-4f48-11ea-80f2-5d52b7aa5910.png)

You will see here

**Comment by KishanVaishnani** [comment]
![image](https://user-images.githubusercontent.com/60768270/75089376-1a144e00-557e-11ea-88e4-b3d1cfb5ea28.png)
I can't see any _t.jpg files in upload/temporary due to that i am not able to set the thumbnail image in the uploaded file under fileupload editor

**Comment by volkanceylan** [comment]
This was an issue in .NET Core version, shouldn't be anymore.
