### ISSUE TITLE
Serenity.CodeGenerator - Async methods issue

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#4862]
Hello!

I have an issue with generating TS code on ServiceEndpoint inherited class. Async Task<> action does not render when I add CancellationToken.

```
public class TestController : ServiceEndpoint
{
public async Task<SaveResponse> Save(SaveRequest request, CancellationToken cancellationToken)
{
...
}
}
```

\Imports\ServerTypings\Application.TestService.ts does not render Save method.

Any chance to get it fixed?

Thanks!

**Comment by lechu90ns** [comment]
It seems the issue got fixed once upgrading Serenity from 3.9.12 to the newest one 3.12.2 with .NET Core 3.1

Thanks

**Comment by lechu90ns** [comment]
Reopening.

This still might be the case. My web site does not compile C# -> typescript files inside /Import folder.

Can someone test the origin issue?

**Comment by volkanceylan** [comment]
Service endpoints doesn't support async tasks and extra parameters in methods. Either write it like other methods, o if you have a reason to make it async, and don't want code generated for that method, add ScriptSkip attribute to the method.

**Comment by lechu90ns** [comment]
Hey @volkanceylan, in my case I want to generate the code in Typescript but it doesn't generate once I add cancellation token. The thing is when I add the same to another endpoint controller with async method - it works. Perhaps naming my endpoint is the issue with generating the code `AppSettingsController : ServiceEndpoint` .

**Comment by volkanceylan** [comment]
Service endpoints doesn't support extra parameters in methods
