### ISSUE TITLE
Best practices for querying data in Backend

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4863]
Dear,

What is the best practice for querying data in backend?
Which way do you used mostly?

1. **Connection.List** 
this way is convenient to write search condition in ICriteria, but we need to remember add IsActive==1
```
var prodOrderOperationItems = uow.Connection.List<ProdOrderOperationItemRow>(ProdOrderOperationItemRow.Fields.ProdOrderOperationId == (Guid)prodOrderOperation.ProdOrderOperationId &&
                  ProdOrderOperationItemRow.Fields.IsActive==1);
```
2. New XXXXRepository().List
```
prodOrderOperationItems = new ProdOrderOperationItemRepository().List(uow.Connection, new ListRequest
            {
                EqualityFilter = new Dictionary<string, object>() { { ProdOrderOperationItemRow.Fields.ProdOrderOperationId.Name, prodOrderOperation.ProdOrderOperationId } }
            }).Entities;
```

**Comment by dfaruque** [comment]
It depends on the situation. I use both of the above methods.
If you want to select most of the fields with master details then the repository method is better. otherwise,  `Connection.List` method is better in terms of performance I think.

**Comment by Nathan2020-0126** [comment]
@dfaruque  thansk for your feedback very much
