### ISSUE TITLE
Masked Input Numeric value

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4864]
hey all, 

I have a special request.
On DB side i store decimal values (amount or percentage) without the decimals (so for most values it's saved in cents).
On db i keep value like this (1245 for 12.45).
Why ? because sometimes amount or percentage are not expressed with 2 digits but more or less.
On DB my field is not DECIMAL but an INTEGER (considering the number of decimal is customer preference request for display).
This requirement would also help for PAN cards (masking the entered numbers but at the end getting the full PAN numbers as a value not a string).

=> I can then display the amount/percentage the way i want using a custom DecimalFormatter i have created (that display on SlickGrid the correct way).

=> My issue comes with Input of this field.
I would like to use a MASK to input the field with the number of decimal i customized (even if on db it will always be without decimals)

My needs are to allow input of Masked data but to get the unmasked value (that i will use to save into db).

I tried the `MaskedEditor(Mask = "9.99")` hoping getting a 999 value but with no luck, actually getting an error message 'The format of the input string is incorrect.'.

Any chance someone did manage this situation ?

Where should i catch this ? (i would like to use the unmaskAsNumber value)

`https://github.com/RobinHerbots/Inputmask`

**Comment by edwardch** [comment]
Maybe this is hacky, but you could put a new NotMapped string field on your Form.cs with the input mask. Then handle it in getSaveEntity() in your Dialog.ts to be the integer from your Row.cs? You'd also need to do something in your loadEntity() as well.

**Comment by JohnRanger** [comment]
@kilroyFR ,

@edwardch : Good point with the notmapped field. 

So to expand on this idea, I would do it like this:

1) add the unmapped field (let's name it: unmappedValue) to xyzrow.cs and add the input mask
2) make sure that your original field from the DB dows not have the NotNull attribute in xyzRow.cs
3) Set the original field in xyzRow.cs or xyzForm.cs to [Hidden]
4) In your beforeSave event on the server-side (saveHandler in xyzRepository.cs), do it like this:
```cs
var stringValue = Row.unmappedValue.toString().Replace(".",""); // remove the decimal point by converting the raw value from the notmapped field to string, do a replace(".","") on it - Hint: If your country uses a comma for the decimal point, change the dot to a comma
Row.<originalDBfield> = Int.Parse(stringValue); // and then assign this Value to the real DB field like this: Row.<originalDBfield> = stringValue.
```
With this, your decimal value from the form will be stored in the save event in the correct field within the DB as an integer without decimals.

Regards,

John

**Comment by kilroyFR** [comment]
hey thanks John &Edward. 
It works almost perfectly except the unmapped field whose value is set in loadEntity is not displayed.
unmapped field iq always set to empty at display.

**Comment by kilroyFR** [comment]
I could finally make it work this way :
   ```
in xxxRow.cs
 [DisplayName("Money")]
    public Int32? Money
    {
      get { return Fields.Money[this]; }
      set { Fields.Money[this] = value; }
    }

    [DisplayName("MoneyDecimal"), NotMapped, NotNull]
    [MaskedEditor(Mask = "9.99")]
    public String MoneyDecimal
    {
      get { return Fields.MoneyDecimal[this]; }
      set { Fields.MoneyDecimal[this] = value; }
    }

and in xxxRepository.cs

    private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>
    {
      protected override void OnReturn()
      {
        base.OnReturn();
        var decimalValue = Row.Money / Math.Pow(10, 2);
        Row.MoneyDecimal = decimalValue.ToString();
      }
    }
```

thnkas for your help John & Edward.
