### ISSUE TITLE
Explorer vs. Chrome

### ISSUE THREAD

**Issue by YoavArmony** [volkanceylan/Serenity#4865]
Hi
I am a new developer in Serenity,
Working in MVC in **Hebrew** environment
I did some simple tests and notice that the result working perfectly in Explorer but in chrom part of the field's content not shown and filtering is not working properly
Do I have to setup somthing
Thanks
Yoav

**Comment by kilroyFR** [comment]
Just an idea : Did you try settings  "target": "es6" in ts.config ?

**Comment by YoavArmony** [comment]
thnaks for the quick reply,
I did try es6, No change

**Comment by YoavArmony** [comment]
I investigated more and it look like R2L (Hebrew) issues:
- Some of the fields are empty 
- functions like [WidthFull] [ThreeQuarterWidth] etc. not working
- PDF Hebrew letters look like chinese
All work OK in L2R (English)
do I have to setup anything in addition to the language definition

**Comment by volkanceylan** [comment]
It works fine for arabic, farsi etc. No idea about what can be different with Hebrew.

**Comment by YoavArmony** [comment]
Hi Volkanceylan
You close the issue but...
I did try Arabic and it look like it have the same issue:
This is a table I have:
    public class TbBudgetForm
    {
        [FullWidth]
        public Int32 YearIdFk { get; set; }
        [DisplayFormat("#,##0."), NumberFormatter]
        public Int32 BudgetAmount { get; set; }
        [DisplayFormat("#,##0."), NumberFormatter]
        public Int32 BudgetCanalder { get; set; }
        public String Description { get; set; }
    }

 This is how it look in English:
 
![image](https://user-images.githubusercontent.com/61151659/76389681-7ba52c80-6374-11ea-9db7-87dcdc05b8b4.png)

And in Hebrew or Arabic it look like this, the system ignore the [FullWidth] 
 
![image](https://user-images.githubusercontent.com/61151659/76389711-924b8380-6374-11ea-88d5-888fd2d298a1.png)

thanks
Yoav

**Comment by stixoffire** [comment]
@YoavArmony - it might be picking up something in currentCulture of the machine it is running on.
Is this all on development box - browser running and web application ? or on different boxes ? 

Check the currentCulture of both ..

**Comment by YoavArmony** [comment]
i have the same on both development and production (azure) and also if I run it on a differant box or  from IOS or Android phones
