### ISSUE TITLE
Time Editor

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4867]
Hi,
I have a sql server field with data type time(7). When I format the field in the Serenity Form with [TimeEditor] and try to save a record, I get the error in the image below.

Please help.

![Time Error](https://user-images.githubusercontent.com/14317420/75035762-262ddc00-54a8-11ea-987f-a16f1dae6d86.PNG)

**Comment by Nathan2020-0126** [comment]
I have the same issue

**Comment by Estrusco** [comment]
Try to see if this pull request can help

https://github.com/volkanceylan/Serenity/pull/4191

**Comment by gfo2007** [comment]
@Estrusco TimeSpanEditor is not found as an attribute. Please could you clarify.

**Comment by Estrusco** [comment]
The pull request isn't merged. You have to make your editor with suggested code:

Make EditTimeEditor.ts under your Common/Helper directory. Then perform T4 transformation to obtain the EditTimeEditorAttribute.cs

```ts
namespace YourNamespace {
    @Serenity.Decorators.element("<input type='number' min='0' max='23'/>")
    @Serenity.Decorators.registerEditor([Serenity.IGetEditValue, Serenity.ISetEditValue, Serenity.IReadOnly])
    export class EditTimeEditor extends Serenity.Widget<EditTimeEditorOptions> {
        constructor(input: JQuery, opt: EditTimeEditorOptions) {
            super(input, opt);

            input.addClass('hours');

            let spanStyle = 'style="margin-left: 6px; min-width: 10px; max-width: 10px;"';
            let stdClass = 'editor s-EditTimeEditor ';
            let colon1 = $('<span ' + spanStyle + ' />').text(':').addClass(stdClass + 'colon1').insertAfter(input);
            let minutes = $('<input type="number" min="0" max="59"/>').addClass(stdClass + 'minutes').addClass('flexify').insertAfter(colon1);
            if (opt.showSeconds) {
                let colon2 = $('<span ' + spanStyle + ' />').text(':').addClass(stdClass + 'colon2').insertAfter(minutes);
                $('<input type="number" min="0" max="59"/>').addClass(stdClass + 'seconds').addClass('flexify').insertAfter(colon2);
            }
        }

        // Implement get and set
        public get value(): string {
            let hours = this.element.val();
            hours = ("0" + hours).slice(-2);
            let mins = this.element.siblings('.minutes').val();
            mins = ("0" + mins).slice(-2);

            let retVal = hours + ':' + mins;

            if (this.options.showSeconds) {
                let secs = this.element.siblings('.seconds').val()
                secs = ("0" +  secs).slice(-2);
                retVal += ':' + secs;
            }

            return retVal;
        }

        public set value(value: string) {
            if (!value)
                return;
            let vals = value.split(':');
            this.element.val(vals[0]);
            this.element.siblings('.minutes').val(vals[1]);
            if (this.options.showSeconds)
                this.element.siblings('.seconds').val(vals[2]);
        }

        public getEditValue(property, target) {
            target[property.name] = this.value;
        }

        public setEditValue(source, property) {
            this.value = source[property.name];
        }

        // Implement get and set read-only
        get_readOnly(): boolean {
            return !(this.element.attr('readonly') == null);
        }

        set_readOnly(value: boolean): void {
            if (value) {
                this.element.attr('readonly', 'readonly').addClass('readonly');
                this.element.nextAll('.s-EditTimeEditor:not(span)').attr('readonly', 'readonly').addClass('readonly');
            }
            else {
                this.element.removeAttr('readonly').removeClass('readonly');
                this.element.nextAll('.s-EditTimeEditor:not(span)').removeAttr('readonly').removeClass('readonly');
            }
        }
    }

    export interface EditTimeEditorOptions {
        showSeconds?: boolean;
    }
}
```

Then use in your form

```cs
[DisplayName("MyTime"), EditTimeEditor(ShowSeconds = true)]
public TimeSpan MyTime { get; set; }
```

and field in yourRow

```cs
        [DisplayName("MyTime")]
        public TimeSpan? MyTime
        {
            get { return Fields.MyTime[this]; }
            set { Fields.MyTime[this] = value; }
        }

[...]

public TimeSpanField MyTime;
```

Then in your db use type time(7)

**Comment by gfo2007** [comment]
@Estrusco thank you very much. Will try it out.

**Comment by gfo2007** [comment]
@Estrusco it worked perfectly. Thanks buddy for your help. God bless you

**Comment by nazrulbspi5** [comment]
When I fetch the time value in report, how can I show AM Or PM?

**Comment by minhhungit** [comment]
![image](https://user-images.githubusercontent.com/2279508/76675257-004cb080-65ea-11ea-91cd-89979d6feeba.png)
I have not tried @Estrusco's editor yet but I created a time editor like this, does anyone need it

**Comment by sangincode404** [comment]
> @huynhvanquy
> 
> ```ts
> @Serenity.Decorators.element("<div/>")
>     @Serenity.Decorators.registerEditor([Serenity.ISetEditValue, Serenity.IGetEditValue])
>     export class CustomTimePickerEditor extends Serenity.Widget<ICustomTimePickerEditorOptions>
>     implements Serenity.ISetEditValue, Serenity.IGetEditValue {
>         getEditValue(property: Serenity.PropertyItem, target): void {
>             let pValue = this.element.find(".custom-timepicker-editor").val();
>             target[property.name] = moment(pValue, 'LTS').format('HH:mm:ss');
>         }
> 
>         private value: string;
>         constructor(container: JQuery, options: ICustomTimePickerEditorOptions) {
>             super(container, options);
> 
>             // hide the caption label for this editor if in a form. ugly hack
>             if (this.options.hideLabel)
>                 this.element.closest('.field').find('.caption').hide();
> 
>             let elementFormat =
>                 '<div class="input-group bootstrap-timepicker timepicker">' +
>                 //'   <div class="input-group-addon">' +
>                 //'       <input type="checkbox" class="chkEnable">' +
>                 //'   </div>' +
>                 '   <input type="text" class="form-control custom-timepicker-editor">' +
>                 //'   <div class="input-group-addon set-time-now">' +
>                 //'       <i class="fa fa-clock-o"></i>' +
>                 //'   </div>' +
>                 //'   <div class="input-group-addon reset-time">' +
>                 //'       <i class="fa fa-undo"></i>' +
>                 //'   </div>' +
>                 '</div>';
> 
>             this.element.html(elementFormat);
> 
>             if (this.options.containerClass) {
>                 this.element.addClass(this.options.containerClass);
>             }                
> 
>             if (this.options.enable) {
>                 this.element.find(".chkEnable").attr("checked", "checked");
>             }
>             else {
>                 this.element.find(".chkEnable").removeAttr("checked");
>             }
> 
>             var timePickerElement = this.element.find(".custom-timepicker-editor");
>             timePickerElement.timepicker();
>         }
> 
>         //setTimeNow(): void {
>         //    console.log("1");
>         //    element.timepicker('setTime', moment().format('LTS'));
>         //}
> 
>         //resetTime(): void{
>         //    console.log("2");
>         //    element.timepicker('setTime', moment(this.value, 'HH:mm:ss').format('LTS'));
>         //}
> 
>         public setEditValue(source: any, property: Serenity.PropertyItem) {
>             let timePickerElement = this.element.find(".custom-timepicker-editor");
> 
>             if (!timePickerElement.hasClass(property.name)) {
>                 timePickerElement.addClass(property.name);
>             }
>             
>             let propValue = source[property.name];
> 
>             if (Q.isEmptyOrNull(propValue)) {
>                 this.value = "00:00:00";
>             }
>             else {
>                 this.value = propValue;
>             }
>             //console.log(this.value);
>             timePickerElement.timepicker('setTime', moment(this.value, 'HH:mm:ss').format('LTS'));
>         }
>     }
> 
>     export interface ICustomTimePickerEditorOptions {
>         hideLabel: boolean;
>         containerClass: string;
>         enable: boolean;
>         // declare TimePicker options here
>     }
> ```
> 
> **You also need to install momentjs into your project**
> 
> Use
> 
> ```cs
> [DisplayName("Set End Of Day Time"), Width(90)]
> [CustomTimePickerEditor]
> public TimeSpan? SetEndofDayTime
> {
>     get { return Fields.SetEndofDayTime[this]; }
>     set { Fields.SetEndofDayTime[this] = value; }
> }
> ```

My project has a moment.js file and also i created the editor as well but in the editor this code is giving an error, the moment and format functions are not define error so please guide me how to do it?  @minhhungit

**Comment by SudhersanT** [comment]
@minhhungit 
![image](https://github.com/serenity-is/Serenity/assets/43756223/8a60cf80-22ce-41b0-b8d7-26808efcefb2)
it seems like timepicker not available in timePickerElement. how to resolve it?

**Comment by minhhungit** [comment]
@SudhersanT you might need to add this library https://github.com/jdewit/bootstrap-timepicker

**Comment by minhhungit** [comment]
and "moment" library

**Comment by mayyola** [comment]
import { Decorators, IGetEditValue, IReadOnly, ISetEditValue, Widget} from '@serenity-is/corelib';
import { formatDate } from '@serenity-is/corelib/q';
import { moment } from 'wwwroot/lib/moment.js/moment.min.js';
import { timepicker } from 'bootstrap-timepicker';
@Decorators.element("<div/>")
@Decorators.registerEditor([ISetEditValue, IGetEditValue])
export class CustomTimePickerEditor extends Widget<ICustomTimePickerEditorOptions>
    implements ISetEditValue, IGetEditValue {
    getEditValue(property, target): void {
        let pValue = this.element.find(".custom-timepicker-editor").val();
        target[property.name] = moment(pValue, 'LTS').format('HH:mm:ss');
    }

    private value: string;
    constructor(container: JQuery, options: ICustomTimePickerEditorOptions) {
        super(container, options);

        // hide the caption label for this editor if in a form. ugly hack
        if (this.options.hideLabel)
            this.element.closest('.field').find('.caption').hide();

        let elementFormat =
            '<div class="input-group bootstrap-timepicker timepicker">' +
            //'   <div class="input-group-addon">' +
            //'       <input type="checkbox" class="chkEnable">' +
            //'   </div>' +
            '   <input type="text" class="form-control custom-timepicker-editor">' +
            //'   <div class="input-group-addon set-time-now">' +
            //'       <i class="fa fa-clock-o"></i>' +
            //'   </div>' +
            //'   <div class="input-group-addon reset-time">' +
            //'       <i class="fa fa-undo"></i>' +
            //'   </div>' +
            '</div>';

        this.element.html(elementFormat);

        if (this.options.containerClass) {
            this.element.addClass(this.options.containerClass);
        }

        if (this.options.enable) {
            this.element.find(".chkEnable").attr("checked", "checked");
        }
        else {
            this.element.find(".chkEnable").removeAttr("checked");
        }

        var timePickerElement = this.element.find(".custom-timepicker-editor");
        timePickerElement.timepicker();
    }

    //setTimeNow(): void {
    //    console.log("1");
    //    element.timepicker('setTime', moment().format('LTS'));
    //}

    //resetTime(): void{
    //    console.log("2");
    //    element.timepicker('setTime', moment(this.value, 'HH:mm:ss').format('LTS'));
    //}

    public setEditValue(source, property) {
        let timePickerElement = this.element.find(".custom-timepicker-editor");

        if (!timePickerElement.hasClass(property.name)) {
            timePickerElement.addClass(property.name);
        }

        let propValue = source[property.name];

        if (Q.isEmptyOrNull(propValue)) {
            this.value = "00:00:00";
        }
        else {
            this.value = propValue;
        }
        //console.log(this.value);
        timePickerElement.timepicker('setTime', moment(this.value, 'HH:mm:ss').format('LTS'));
    }
}

export interface ICustomTimePickerEditorOptions {
    hideLabel: boolean;
    containerClass: string;
    enable: boolean;
    // declare TimePicker options here
}

@minhhungit  package.json has download ,and i import them,but timepicker still not working, i don't know how to solve it.
 "bootstrap-timepicker": "^0.5.2",
 "moment": "^2.30.1"
![q](https://github.com/serenity-is/Serenity/assets/38484042/a85d9780-7008-44c9-8924-c9961c9c5543)
