### ISSUE TITLE
Grid Row details

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4868]
Is there any example like Grid Row Details?
Link: [Datatables Row Detais Example](http://datatables.club/example/user_share/row_details.html)
![image](https://user-images.githubusercontent.com/16734387/75080246-6cd21380-5546-11ea-8489-4757745f28d1.png)

**Comment by arifsamitekinkaya** [comment]
Sample 1 - https://serenity.is/demo/BasicSamples/TreeGrid
Sample 2 - https://serenity.is/demo/BasicSamples/DragDropInTreeGrid

**Comment by minhhungit** [comment]
There is a sample with slickgrid here

![image](https://user-images.githubusercontent.com/2279508/75848949-39c93300-5e16-11ea-8a88-0b1431d05db6.png)

http://6pac.github.io/SlickGrid/examples/example16-row-detail.html
