### ISSUE TITLE
How to set height column in grid serenity

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4870]
Halloo Community ... I put code below in site.less :
.s-Default-MContactGrid {
    .slick-header-columns {
        white-space: normal;
        height: 45px;
        border-bottom: 2px solid #ccc;
    }

    .slick-header-column.ui-state-default {
        height: 100%;
    }
    
    height: 280px;
}
but it's just working in header-columns, How can I change height of detail/cell? .. Please give me a solution.. thank a lot..

**Comment by arifsamitekinkaya** [comment]
in your MContactGrid.ts file, just put method below
<pre>getSlickOptions() {
     var opt = super.getSlickOptions();
     opt.rowHeight = 36;
     return opt;
}</pre>

**Comment by resitaufan** [comment]
Thx  @arifsamitekinkaya
