### ISSUE TITLE
Get Text from MultiLookup (Dialog)

### ISSUE THREAD

**Issue by resitaufan** [volkanceylan/Serenity#4871]
Hello can someone help me ,
I want get text from MultiLookup. I tried with `this.form.MyField.text` but it's just working in single lookup

Thanks

**Comment by arifsamitekinkaya** [comment]
Try this: 

> this.form.MyField.**values**

**Comment by resitaufan** [comment]
@arifsamitekinkaya it's get value not text.

**Comment by Nathan2020-0126** [comment]
After you get values by **this.form.MyField.values**, then you can try using getLookup().itemById to get the text.
`ProductRow.getLookup().itemById[row.ProductID].ProductName`
