### ISSUE TITLE
IAuditLog Details

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4873]
Not really a Serenity Issue but an implementation question.

I am looking for how to add a details to the AuditLog created when using the nice [WIKI IAudit Auditing](https://github.com/volkanceylan/Serenity/wiki/Auditing:-Audit-Log-for-Insert-Update-and-Delete-using-Single-Table).

Has anyone implemented a details page for that ? If so do you have a sample to share ?

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

in case you create one - would you mind to share it here? :-)

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 
When I get that done - I sure will - I try to post in the wiki when I have something that might be useful to others (and when the code is neat.) - I have a Complete typescript implementation of SignaturePad that I want to post - only one method Update has an issue right now (it adds the image on the image).

**Comment by stixoffire** [comment]
@JohnRanger  

I have created an Audit log details  (but on the row level ) in other words when you look at a record you can see the edits of that record. It works nicely .. 

![QuoteAudit_Share](https://user-images.githubusercontent.com/9748682/77694619-5588aa80-6f78-11ea-9feb-dd08349dfa68.png)


As I was doing this I originally wanted to go the other way around - seeing the entire table.  I still would like to do that - but that will take time. AuditLogRow is sealed so it has to be made inheritable, as well as the Form, and Columns etc.. then Derive from that class adding in the specific table as a MasterDetail. 

In a small db - you could skip the inheritance and simply add a few Master Detail relations  , but in a larger system - that much data could be really sluggish. 

IMO the best way is to just inherit from AuditLogRow , Column, Form, Grid,  Add in the Join Table on the new Row class as a MasterDetailRelation setting foreign key RowId and master key , filter on module parameter ; seems the IAUditLog uses the actual rowtype as Module.
