### ISSUE TITLE
UNC path for file uploads not found

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4874]
Hi,
I have created a unc path for uploading my files. The path is on a network file server as shown in the image below.

![UploadSettings](https://user-images.githubusercontent.com/14317420/75539522-46165000-5a12-11ea-829f-0cf12224caab.PNG)

When I try to open the uploaded file, it throws the error in the image below. Please help

![Directory Not Found Error](https://user-images.githubusercontent.com/14317420/75539637-81188380-5a12-11ea-90a0-8390516ae7c0.PNG)

**Comment by mijaved** [comment]
Possible duplicate #3671
Please check my answer here: https://github.com/volkanceylan/Serenity/issues/3671#issuecomment-626475076
