### ISSUE TITLE
.Net Core TypeError:MovieTutorial.MovieDB is undefined

### ISSUE THREAD

**Issue by Xaninho** [volkanceylan/Serenity#4875]
Hey everyone, I'm a newbie and I'm following the Movie Tutorial on the Serenity documentation. After following step by step how to generate code with sergen, I get this error when opening the Movies Grid. (The only difference with the tutorial is that the namespace is _MovieManager_ insted of _MovieTutorial_.

![Captura de Ecrã (7)](https://user-images.githubusercontent.com/52694651/75540941-f2593600-5a14-11ea-8444-c5cfe4488d61.png)

And it is getting an error on line 218:

![Anotação 2020-02-28 102859](https://user-images.githubusercontent.com/52694651/75541124-449a5700-5a15-11ea-95c3-bcec6de1a54f.png)

Any ideas? Perhaps Startsharp things? I've updated my Typescript to 3.7.0 and still no results.

**Comment by volkanceylan** [comment]
Are you sure your project is building correctly? Please open MovieManager.Web.js under scripts/site and see if you have a MovieManager MovieDB MovieGrid code there.
