### ISSUE TITLE
PDF icon in grid

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4877]
Hi,
Please how do I display a pdf thumbnail in grid as a link to a file as shown in the demo image below?

![pdf thumbnail](https://user-images.githubusercontent.com/14317420/75620535-dd4de580-5b81-11ea-8933-3d228047aa12.PNG)

**Comment by minhhungit** [comment]
I've never a chance to do this feature, but If I have this is my idea:
- https://github.com/mephraim/ghostscriptsharp This library help we gen pdf thumbnail 
- And we should have a background job which will using above library, save thumbnails into hard-disk with path include item-id
- finally we will show those images on grid, if image does not exist then show a default image

Hope it helps

**Comment by gfo2007** [comment]
@minhhungit the thumbnail showing is already implemented in serenity. So I was thinking you had an idea how the implementation was done in serenity.

**Comment by minhhungit** [comment]
that's icon not thumbnail , and it's also has demo code
you always can find demo in Serene project, or check this link

https://serenity.is/demo/BasicSamples/InlineActionButtons

**Comment by lechu90ns** [comment]
Are you asking on how to make such an icon (in this case PDF one) inside each record in grid?

**Comment by minhhungit** [comment]
```javascript
columns.splice(2, 0, {
                field: 'Download pdf',
                name: '',
                format: ctx => '<a class="inline-action download-pdf-button fa fa-file-pdf-o text-green" title="new order"></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });
```

It's not too hard right ?

**Comment by gfo2007** [comment]
@lechu90ns yes please.

**Comment by lechu90ns** [comment]
Minhhngit responded with an answer to you.

**Comment by gfo2007** [comment]
@lechu90ns and @minhhungit please am I doing something wrong in the code below? I am trying to open the link stored in a column of a table.

 protected getColumns() {
            var columns = super.getColumns();

            Q.first(columns, x => x.field == fld.MiFileUrl).format = ctx => '<a class="inline-action download-pdf-button fa fa-file-pdf-o text-red" title="new order"></a>';


            return columns;
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;
            
            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass("inline-action")) {
                this.editItem(Q.format(Q.htmlEncode(item.MiFileUrl)));

            }

        }

**Comment by minhhungit** [comment]
@gfo2007  You can find the button by class `download-pdf-button` 

```javascript
    // ....
    if (target.parent().hasClass('inline-action'))
        target = target.parent();

    if (target.hasClass('inline-action')) {
        e.preventDefault();

        if (target.hasClass('download-pdf-button')) {  // <======================
            Q.alert("hello, you clicked on download button");
        }
    }
    // ....
```
