### ISSUE TITLE
Error in configuring postgresql

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4879]
I am trying to use postgresql with Serenity mvc core but it gives the following error.
![image](https://user-images.githubusercontent.com/20435849/75624293-b1a61c00-5bd0-11ea-8827-9b29de98d3e2.png)

While the connection string is setup like following. Do I have to do any extra configuration or am I missing anything?

    "Default": {
      "Default": "Server=localhost;Port=5432;Database=HRS_Default_v1;User Id=dbuser;Password=****;"
    },

**Comment by edwardch** [comment]
Have you tried

```json
{
  "Data": {
    "Default": {
      "ConnectionString": "Server=localhost;Port=5432;Database=HRS_Default_v1;User Id=dbuser;Password=****;",
      "ProviderName": "System.Data.SqlClient" // You might have to change this to PG something?
    },
    // Other connection strings
  },
  // Other config 
}
```
