### ISSUE TITLE
ASP.NET 5 and .NET Core

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#488]
Is there any issues if we use .Net Core when building and publishing the Serenity framework? I was trying to find dependencies but can't really locate it directly. Also is the serene project template asp.net 5?

note: I started and I am still using the serene project template.

**Comment by volkanceylan** [comment]
.Net core is currently still a work in progress and is a real mess. DNX, DNVM, netcore, dnxcore451, dnxcore54 they have so many terms and changing names every second. I'll have a look at it after it got stabilized. Dont really know if it will work now.

**Comment by wdhodges** [comment]
I saw an article talking about how core and asp5 can be used side by side
but just wanted to check with you. What's the minimum dependency? .net4.5?

**Comment by volkanceylan** [comment]
We are using 4.5.1 at the moment

**Comment by wdhodges** [comment]
Thank you
