### ISSUE TITLE
Multiple Tables on one Page

### ISSUE THREAD

**Issue by WakanaYuki** [volkanceylan/Serenity#4880]
Hey, so I want to have 3 tables on one site. They need to be different tables, because the 2 selected values in the first 2 tables are a database filter for the third table.
Is that possible with serinity?

(Example:

Table1: Selected Value=1
Table2: selected values=5
Table3: selected values=TableXY Where ID1=1 AND ID2=5)

**Comment by stixoffire** [comment]
@WakanaYuki  Can you use dropdowns for your first two tables ? 
ID1, ID2 is a FK of TableXY ..
If you really want the grid layout for them .
You can also Put those in a list object .. In Table3 XYZROW 
List<Table1> myTable1 {get .. fieldvalue ;set;}
List<Table2> myTable2 {get .. fieldvalue ;set;}

**Comment by WakanaYuki** [comment]
Sadly not, they need to be seperate tables :/
