### ISSUE TITLE
ReportDialog Dropdown selection.

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4882]
In the report dialog I am trying to put a dropdown selector populated from database

I am thinking I need to Extend the ReportDialog.ts script to add it but just do not know where to start. typescript is not my forte` .  Any help and examples is appreciated .

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

can you provide a little mockup from what you want to achieve? Where should the dropdown go? what should be the result of selecting something of the dropdown? etc...

It is a little bit difficult to understand what you want to achieve :-)

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 
The picture below is basically what I would like to have in my report dialog, I want the selector to be populated and when I select a value - I want to use that value in the report.

![ReportDialogDesired](https://user-images.githubusercontent.com/9748682/77399515-9ebddc00-6d77-11ea-8647-6bc9f66112bf.png)

**Comment by JohnRanger** [comment]
HI @stixoffire ,

ok - I think this has to be splitted into 2 parts:

1) Populate the dropdown from server side
2) send the selected value from the dropdown to server-side in order to use it within the report generator.

For (1), you could do it like this (fetching the vendor list in the format which select2 (your JQueryUI dropdown widget) likes to have.

On the server-side (xyzEndpoint.cs), return the following:

```cs
[HttpPost]
public ActionResult forChainDocuments(int FilterId, int CurrentId, bool isEdit)
{
	var connection = SqlConnections.NewFor<myTACMasterLayoutsAdditionalDocumentsRow>();

	var row = new myTACMasterLayoutsAdditionalDocumentsRow();
	var NotInrow = new myChainAdditionalDocumentsRow();
	var query = "SELECT t1." + myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentId.Name + ", t1." + myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentName.Name + ", t1." + myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentDescription.Name;
	query += " FROM " + row.Table;
	query += " t1 LEFT JOIN (select * from " + NotInrow.Table + " where " + myChainsLayoutsRow.Fields.ChainId.Name + " = " + FilterId + ") t2 ON t2." + myChainAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentId.Name + " = t1." + myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentId.Name;
	query += " WHERE t2." + myChainAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentId.Name + " IS NULL";

	var Result = connection.Query(query);

	List<Select2DataItem> DataItems = new List<Select2DataItem>();

	foreach (var Resultrow in Result)
	{
		var data = (IDictionary<string, object>)Resultrow;

		var currentItem = new Select2DataItem();
		currentItem.id = (int)data[myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentId.Name];
		currentItem.text = (string)data[myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentName.Name] + " | " + (string)data[myTACMasterLayoutsAdditionalDocumentsRow.Fields.TacMasterLayoutsAdditionalDocumentDescription.Name];
		DataItems.Add(currentItem);
	}

	// *** Re-sort items ***
	DataItems = DataItems.OrderBy(o => o.text).ToList();

	connection.Close();

	var output = JsonConvert.SerializeObject(DataItems);
	return Json(output, JsonRequestBehavior.AllowGet);

}
```

On the client-side (xyzDialog.ts), do this to fill the dropdown:

```ts
  let ServiceEndpoint = "/services/Common/LeftOver/forChainDocuments";
var data = JSONDatafetcher.GetLeftOverItemsAsJSON(ServiceEndpoint, this.form.ChainId.value, (this.form.TacMasterLayoutsAdditionalDocumentId.value == null ? "0" : this.form.TacMasterLayoutsAdditionalDocumentId.value), this.isEditMode());
this.form.TacMasterLayoutsAdditionalDocumentId.element.select2({ data: data });
```

Point (2) I have not yet any real idea - but let me think it through.

Regards,

John

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

in order to think about (2) and (3), could you attach here your SF Report module - or at least a generalized version of it - So I can study the client- and server side for sending over the selected value with the excel button?

Regards,

John

**Comment by JohnRanger** [comment]
Hi @stixoffire,

for your excel button sending the vendorID over to server-side, you could do it like this (directly out of one of my projects - please adapt to your requirements):

```ts
// *** Create Export additional Document Button ***
buttons.push(
{
	title: Q.text("Dialogs.Documents.Button.ExportDocument"),
	cssClass: 'excel-button',
	onClick: () => {

		let ServiceEndpoint = this.getService() + "/ExportDocument";	// *** your action method in xyzEndpoint.cs ***
		Q.postToService({ service: ServiceEndpoint, request: { VendorId: <value from Vendor dropdown> }, target: '_blank' }); 

		Q.notifySuccess(Q.text("Dialogs.FileExport.Document.Success")); // *** Optional notification that the excel has been created ***
	},
});
```



With that, you get the VendorID within your xyzEndpoint action method and you can do whatever is needed to add it within your report.

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger  - I will attempt to modify what you have posted - I am working on so many different functionalities of this project right now it might take me some time to get back here.

**Comment by JohnRanger** [comment]
@stixoffire ,

wish you success - If something is unclear, just post more questions. 

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger - I don't have a direct way to send this to you - but I posted an AuditLog detail solution - it is not the way I originally desired but for now it works per record [Audit Details per record](https://github.com/volkanceylan/Serenity/wiki/Audit-Details-in-the-XYZ-form-as-Master-Detail-relation.)

**Comment by stixoffire** [comment]
@JohnRanger I am putting this together right now - but have some difficulty with the 
Select2DataItem I am not sure where that object is constructed - it does not look like it is in the framework, and searching online not finding anything - I am guessing you created that object. 
What does it consist of  
```
Select2DataItem(){
Id {get;set;}
Text  {get;set;}
}
```

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

good question :-)

This is a simple CS class. The whole file content looks like this:

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace <your project>.Modules.Common.Helpers
{
    public class Select2DataItem
    {
        public int id { get; set; }
        public string text { get; set; }
    }
}
```

This is useful to represent 1 entry within the select2 dropdown (ID and the visible text).

(Select2 is a standard jQuery UI widget.)

Regards,

John

**Comment by pradeep-pandit** [comment]
private FillUserCategoryRoleDropDown() {
            var ID = Q.toId(this.form.UserCategoryId.value);

            if (ID != null) {

                Q.serviceRequest(UserCategoryRoleService.Methods.List, {
                }, (response: Serenity.ListResponse<UserCategoryRoleRow>) => {
                    var entities = response.Entities.filter(x => x.UserCategoryId == ID);

                    this.form.UserCategoryRoleId.clearItems();

                    for (var i = 0; i < entities.length; i++) {
                        this.form.UserCategoryRoleId.addItem({ id: entities[i].UserCategoryRoleId.toString(), text: entities[i].UserCategoryRoleName });
                    }

                });
            }
        }
