### ISSUE TITLE
Textbox Default Value

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4883]
I want to add default value in textbox
where the size of the textbox will be 14
the default value will be like this
(    -    -    )
4 space then ("-")  , 4 space and then ("-")
so in the space user can add the numbers.

**Comment by volkankalkan** [comment]
You can use DisplayFormat attribute for example DisplayFormat("#,##0.00")

**Comment by Shraddha996** [comment]
I added like this but doesn't work
DisplayFormat("####-####-####")

**Comment by luongnv6** [comment]
please add attribute:
        [MaskedEditor(Mask = "(999) 999-9999"), Placeholder("(999) 999-9999")]

**Comment by Shraddha996** [comment]
Thank you, it works!
