### ISSUE TITLE
TreeGrid not working in Common.GridEditorBase

### ISSUE THREAD

**Issue by zainvegeta** [volkanceylan/Serenity#4885]
I am Trying to show in my form order and orderItems. The order item will be loaded in a grid.Certain orderitems have a parentId which will be id of an item in same table.But for some reason treeGrid mixin is not working in GridEditorBase.But it works fine with EntityGrid.I am adding my code
 

GridEditor
![image](https://user-images.githubusercontent.com/38037830/75869544-b87e9a00-5e2f-11ea-8719-dbe99121e361.png)

OrderItemROw
![image](https://user-images.githubusercontent.com/38037830/75869625-d8ae5900-5e2f-11ea-8ecc-9d1527020b6c.png)
OrderRow with masterdetail relation
![image](https://user-images.githubusercontent.com/38037830/75869704-f8458180-5e2f-11ea-8baf-e8d5e8f3def6.png)

I already saw two posts here with some solutions.But i cant understand it or how they got it to work

**Comment by volkanceylan** [comment]
TreeGridMixin works at onViewProcessData event, which does not happen for in memory grids. See source of TreeGridMixin and try to implement something similar.

**Comment by zainvegeta** [comment]
Thnx for clarifying.I will try a custom implementation
