### ISSUE TITLE
Login Page Is Blank

### ISSUE THREAD

**Issue by msdastlan** [volkanceylan/Serenity#4886]
hi there is a problem at login page that i just see a empty box,
inspect element show that  the css and js resource  coud not be find

**Comment by stixoffire** [comment]
@msdastlan 
Look in your ~Scripts/site/ScriptsBundle.Json file. 
You should have a path to your different scripts in there - like mine has jquery folder in Scripts so in ScriptsBundle.json I have this - yours might be different. 
    "~/Scripts/jquery/jquery.js",

**Comment by msdastlan** [comment]
here is my json,whats wrong?
{
  "Base": [
    "~/Scripts/pace.js",
    "~/Scripts/jquery-{version}.js",
    "~/Scripts/jquery-ui.js",
    "~/Scripts/jquery-ui-i18n.js",
    "~/Scripts/jquery.validate.js",
    "~/Scripts/jquery.blockUI.js",
    "~/Scripts/jquery.cookie.js",
    "~/Scripts/jquery.json.js",
    "~/Scripts/bootstrap.js",
    "~/Scripts/select2.js",
    "~/Scripts/toastr.js",
    "~/Scripts/vegas/vegas.js",
    "~/Scripts/saltarelle/mscorlib.js",
    "~/Scripts/serenity/Serenity.CoreLib.js"
  ],
  "Site": [
    "~/Scripts/jquery.autoNumeric.js",
    "~/Scripts/jquery.colorbox.js",
    "~/Scripts/jquery.dialogextendQ.js",
    "~/Scripts/jquery.event.drag.js",
    "~/Scripts/jquery.maskedinput.js",
    "~/Scripts/jquery.scrollintoview.js",
    "~/Scripts/sortable.js",
    "~/Scripts/SlickGrid/slick.core.js",
    "~/Scripts/SlickGrid/slick.grid.js",
    "~/Scripts/SlickGrid/slick.groupitemmetadataprovider.js",
    "~/Scripts/SlickGrid/Plugins/slick.autotooltips.js",
    "~/Scripts/SlickGrid/Plugins/slick.headerbuttons.js",
    "~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js",
    "~/Scripts/SlickGrid/Plugins/slick.rowmovemanager.js",
    "~/Scripts/jquery.fileupload.js",
    "~/Scripts/jquery.iframe-transport.js",
    "~/Scripts/jquery.slimscroll.js",
    "~/Scripts/mousetrap.js",
    "~/Scripts/vue.js",
    "~/Scripts/adminlte/app.js",
    "~/Scripts/site/Serene3.Web.js",
    "dynamic://ColumnsBundle",
    "dynamic://FormBundle",
    "dynamic://TemplateBundle"
  ],
  "CKEditor": [
    "~/Scripts/ckeditor/ckeditor.js",
    "~/Scripts/ckeditor/lang/en.js",
    "~/Scripts/ckeditor/styles.js"
  ],
  "NorthwindLookups": [
    "dynamic://Lookup.Northwind.Category",
    "dynamic://Lookup.Northwind.Customer",
    "dynamic://Lookup.Northwind.CustomerCountry",
    "dynamic://Lookup.Northwind.CustomerCity",
    "dynamic://Lookup.Northwind.Employee",
    "dynamic://Lookup.Northwind.Shipper",
    "dynamic://Lookup.Northwind.OrderShipCountry",
    "dynamic://Lookup.Northwind.OrderShipCity",
    "dynamic://Lookup.Northwind.Product",
    "dynamic://Lookup.Northwind.Region",
    "dynamic://Lookup.Northwind.Supplier",
    "dynamic://Lookup.Northwind.Territory"
  ],
  "Pages/Dashboard": [
    "~/Scripts/raphael/raphael-min.js",
    "~/Scripts/morris/morris.min.js",
    "~/Scripts/sparkline/jquery.sparkline.min.js",
    "~/Scripts/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "~/Scripts/jvectormap/jquery-jvectormap-world-mill-en.js",
    "~/Scripts/knob/jquery.knob.js",
    "~/Scripts/daterangepicker/moment.min.js",
    "~/Scripts/daterangepicker/daterangepicker.js",
    "~/Scripts/datepicker/bootstrap-datepicker.js",
    "~/Scripts/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js",
    "~/Scripts/adminlte/pages/dashboard.js",
    "~/Scripts/adminlte/demo.js"
  ]
}

**Comment by stixoffire** [comment]
Here is a copy of mine - looks like you are missing reference to JQeury.js

```
"Base": [
    "~/Scripts/pace.js",
    "~/Scripts/jquery/jquery-{version}.js",
    "~/Scripts/jquery/jquery.js",
    "~/Scripts/jquery/jquery-ui.js",
    "~/Scripts/jquery/jquery-ui-i18n.js",
    "~/Scripts/jquery/jquery.validate.js",
    "~/Scripts/jquery/jquery.blockUI.js",
    "~/Scripts/jquery/jquery.cookie.js",
    "~/Scripts/jquery/jquery.json.js",
    "~/Scripts/bootstrap.js",
    "~/Scripts/select2.js",
    "~/Scripts/toastr.js",
    "~/Scripts/vegas/vegas.js",
    "~/Scripts/saltarelle/mscorlib.js",
    "~/Scripts/serenity/Serenity.CoreLib.js",
    "~/Scripts/signature_pad/signature_pad.js"
  ],
  "Site": [
    "~/Scripts/jquery/jquery.autoNumeric.js",
    "~/Scripts/jquery/jquery.colorbox.js",
    "~/Scripts/jquery/jquery.dialogextendQ.js",
    "~/Scripts/jquery/jquery.event.drag.js",
    "~/Scripts/jquery/jquery.maskedInput.js",
    "~/Scripts/jquery/jquery.scrollintoview.js",
    "~/Scripts/sortable.js",
    "~/Scripts/SlickGrid/slick.core.js",
    "~/Scripts/SlickGrid/slick.grid.js",
    "~/Scripts/SlickGrid/slick.groupitemmetadataprovider.js",
    "~/Scripts/SlickGrid/Plugins/slick.autotooltips.js",
    "~/Scripts/SlickGrid/Plugins/slick.headerbuttons.js",
    "~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js",
    "~/Scripts/SlickGrid/Plugins/slick.rowmovemanager.js",
    "~/Scripts/jquery/jquery.fileupload.js",
    "~/Scripts/jquery/jquery.iframe-transport.js",
    "~/Scripts/jquery/jquery.slimscroll.js",
    "~/Scripts/mousetrap.js",
    "~/Scripts/vue.js",
    "~/Scripts/adminlte/app.js",
    "~/Scripts/site/TDSProjects.Web.js",
    "~/Scripts/signature_pad/signature_pad.js",
    "dynamic://ColumnsBundle",
    "dynamic://FormBundle",
    "dynamic://TemplateBundle"
  ],
  "CKEditor": [
    "~/Scripts/ckeditor/ckeditor.js",
    "~/Scripts/ckeditor/lang/en.js",
    "~/Scripts/ckeditor/styles.js"
  ],
  "NorthwindLookups": [
    "dynamic://Lookup.Northwind.Category",
    "dynamic://Lookup.Northwind.Customer",
    "dynamic://Lookup.Northwind.CustomerCountry",
    "dynamic://Lookup.Northwind.CustomerCity",
    "dynamic://Lookup.Northwind.Employee",
    "dynamic://Lookup.Northwind.Shipper",
    "dynamic://Lookup.Northwind.OrderShipCountry",
    "dynamic://Lookup.Northwind.OrderShipCity",
    "dynamic://Lookup.Northwind.Product",
    "dynamic://Lookup.Northwind.Region",
    "dynamic://Lookup.Northwind.Supplier",
    "dynamic://Lookup.Northwind.Territory"
  ],
  "Pages/Dashboard": [
    "~/Scripts/raphael/raphael-min.js",
    "~/Scripts/morris/morris.min.js",
    "~/Scripts/sparkline/jquery.sparkline.min.js",
    "~/Scripts/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "~/Scripts/jvectormap/jquery-jvectormap-world-mill-en.js",
    "~/Scripts/knob/jquery.knob.js",
    "~/Scripts/daterangepicker/moment.min.js",
    "~/Scripts/daterangepicker/daterangepicker.js",
    "~/Scripts/datepicker/bootstrap-datepicker.js",
    "~/Scripts/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js",
    "~/Scripts/adminlte/pages/dashboard.js",
    "~/Scripts/adminlte/demo.js"
  ],
```

**Comment by volkanceylan** [comment]
You should first look at browser console and identify what is the first error you got there. Probably some script can't be loaded.
