### ISSUE TITLE
SlickGrid requires a valid container error. Works on local environment but not on IIS

### ISSUE THREAD

**Issue by zappitmr** [volkanceylan/Serenity#4887]
SlickGrid requires a valid container, [object Object] does not exist in the DOM.

Getting the above error when I add a grid to a dialog. It works when I run it locally and it runs for several different other grids but not for one particular grid. Even though it is using the same code.

**Comment by stixoffire** [comment]
@zappitmr 
A simple search first : 
[#3879](https://github.com/volkanceylan/Serenity/issues/3879)
SlickGrid requires a valid container #3879

**Comment by zappitmr** [comment]
@stixoffire Thanks for the reference. Had seen that post but that doesn't resolve my issue. It runs locally and IDs are correct.

**Comment by stixoffire** [comment]
@zappitmr if it runs locally and runs other grids with same code?  Check Permissions on the grid / xyzrow that you are trying to add to the dialog. It sounds like it can't access it - so you don't get it.

**Comment by zappitmr** [comment]
@stixoffire Thanks for the reply but I have checked the above also. It has access. The same as with the other grids.

**Comment by stixoffire** [comment]
@zappitmr did you do a clean and rebuild? - delete your files in obj folder as well , then rebuild and Transform T4 .

**Comment by zappitmr** [comment]
Yes had tried clean and rebuild. Just deleted files in obj and still same issue.

Uncaught Error: SlickGrid requires a valid container, [object Object] does not exist in the DOM.
    at init (slick.grid.js?v=-UNs7rVmehG4hGOYJukWAg2:283)
    at new SlickGrid (slick.grid.js?v=-UNs7rVmehG4hGOYJukWAg2:5154)
    at CustomerVwContactsGrid.DataGrid.createSlickGrid (DataGrid.ts:395)
    at CustomerVwContactsGrid.DataGrid [as constructor] (DataGrid.ts:62)
    at CustomerVwContactsGrid.EntityGrid [as constructor] (EntityGrid.ts:7)
    at new CustomerVwContactsGrid (Delpac.Web.js?v=M9jRY8EI3VmobseXv9Y22g2:3758)
    at new CustomerDialog (Delpac.Web.js?v=M9jRY8EI3VmobseXv9Y22g2:3568)
    at Function.Widget.create (Widget.ts:133)
    at CustomerGrid.EntityGrid.createEntityDialog (EntityGrid.ts:273)
    at CustomerGrid.EntityGrid.editItem (EntityGrid.ts:172)

**Comment by edwardch** [comment]
Are you using a custom template by any chance?

I had a similar issue where it worked in my local environment but not when deployed. I was using a grid in a tab within my dialog.

If you're trying something like this, click on `YourModule.XYZDialog.Template.html`, go to properties, and set `Build Action` to `None`.

**Comment by volkanceylan** [comment]
Probably you have multiple templates with same name, in production files might be coming out in different order.

Anyway put a breakpoint in Chrome console at new CustomerDialog (Delpac.Web.js?v=M9jRY8EI3VmobseXv9Y22g2:3568) line and see output of this.element.html() by printing it to console etc.

**Comment by zappitmr** [comment]
<div id="Delpac_Default_CustomerDialog7_Tabs" class="s-DialogContent ui-tabs ui-corner-all ui-widget ui-widget-content">    <ul role="tablist" class="ui-tabs-nav ui-corner-all ui-helper-reset ui-helper-clearfix ui-widget-header">        <li role="tab" tabindex="0" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab ui-tabs-active ui-state-active" aria-controls="Delpac_Default_CustomerDialog7_TabInfo" aria-labelledby="ui-id-1" aria-selected="true" aria-expanded="true"><a href="#Delpac_Default_CustomerDialog7_TabInfo" role="presentation" tabindex="-1" class="ui-tabs-anchor" id="ui-id-1"><span>Customer Details</span></a></li>              <li role="tab" tabindex="-1" class="ui-tabs-tab ui-corner-top ui-state-default ui-tab" aria-controls="Delpac_Default_CustomerDialog7_TabVwContacts" aria-labelledby="ui-id-2" aria-selected="false" aria-expanded="false"><a href="#Delpac_Default_CustomerDialog7_TabVwContacts" role="presentation" tabindex="-1" class="ui-tabs-anchor" id="ui-id-2"><span>Details</span></a></li>    </ul>    <div id="Delpac_Default_CustomerDialog7_TabInfo" class="tab-pane s-TabInfo ui-tabs-panel ui-corner-bottom ui-widget-content" aria-labelledby="ui-id-1" role="tabpanel" aria-hidden="false">        <div id="Delpac_Default_CustomerDialog7_Toolbar" class="s-DialogToolbar s-Toolbar clearfix"><div class="tool-buttons"><div class="buttons-outer"><div class="buttons-inner"><div class="tool-button undo-delete-button"><div class="button-outer"><span class="button-inner">Undelete</span></div></div><div class="tool-button localization-button"><div class="button-outer"><span class="button-inner">Localization</span></div></div><div class="tool-button clone-button"><div class="button-outer"><span class="button-inner">Clone</span></div></div></div></div></div></div>        <div class="s-Form">            <form id="Delpac_Default_CustomerDialog7_Form" action="" novalidate="novalidate">                <div class="fieldset ui-widget ui-widget-content ui-corner-all">                    <div id="Delpac_Default_CustomerDialog7_PropertyGrid" class="s-PropertyGrid"><div class="categories"><div class="category"><div class="field CustNumber"><label class="caption" for="Delpac_Default_CustomerDialog7_CustNumber" title="Cust Number">Cust Number</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_CustNumber" name="CustNumber" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Name"><label class="caption" for="Delpac_Default_CustomerDialog7_Name" title="Name">Name</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Name" name="Name" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Address1"><label class="caption" for="Delpac_Default_CustomerDialog7_Address1" title="Address1">Address1</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Address1" name="Address1" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Address2"><label class="caption" for="Delpac_Default_CustomerDialog7_Address2" title="Address2">Address2</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Address2" name="Address2" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Address3"><label class="caption" for="Delpac_Default_CustomerDialog7_Address3" title="Address3">Address3</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Address3" name="Address3" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Address4"><label class="caption" for="Delpac_Default_CustomerDialog7_Address4" title="Address4">Address4</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Address4" name="Address4" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Address5"><label class="caption" for="Delpac_Default_CustomerDialog7_Address5" title="Address5">Address5</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Address5" name="Address5" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field InvAddress" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_InvAddress" title="Inv Address">Inv Address</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_InvAddress" name="InvAddress" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Phone1"><label class="caption" for="Delpac_Default_CustomerDialog7_Phone1" title="Phone1">Phone1</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Phone1" name="Phone1" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Phone2"><label class="caption" for="Delpac_Default_CustomerDialog7_Phone2" title="Phone2">Phone2</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Phone2" name="Phone2" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Phone3"><label class="caption" for="Delpac_Default_CustomerDialog7_Phone3" title="Phone3">Phone3</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Phone3" name="Phone3" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Phone4"><label class="caption" for="Delpac_Default_CustomerDialog7_Phone4" title="Phone4">Phone4</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Phone4" name="Phone4" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Phone5"><label class="caption" for="Delpac_Default_CustomerDialog7_Phone5" title="Phone5">Phone5</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Phone5" name="Phone5" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Fax1"><label class="caption" for="Delpac_Default_CustomerDialog7_Fax1" title="Fax1">Fax1</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Fax1" name="Fax1" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Fax2" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_Fax2" title="Fax2">Fax2</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Fax2" name="Fax2" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Area" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_Area" title="Area">Area</label><input type="text" class="editor flexify s-IntegerEditor integerQ readonly" id="Delpac_Default_CustomerDialog7_Area" name="Area" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Industry" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_Industry" title="Industry">Industry</label><input type="text" class="editor flexify s-IntegerEditor integerQ readonly" id="Delpac_Default_CustomerDialog7_Industry" name="Industry" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Currency" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_Currency" title="Currency">Currency</label><input type="text" class="editor flexify s-IntegerEditor integerQ readonly" id="Delpac_Default_CustomerDialog7_Currency" name="Currency" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Contact"><label class="caption" for="Delpac_Default_CustomerDialog7_Contact" title="Contact">Contact</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Contact" name="Contact" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Email"><label class="caption" for="Delpac_Default_CustomerDialog7_Email" title="Email">Email</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Email" name="Email" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Website"><label class="caption" for="Delpac_Default_CustomerDialog7_Website" title="Website">Website</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Website" name="Website" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Balance" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_Balance" title="Balance">Balance</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Balance" name="Balance" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field CreditRef" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_CreditRef" title="Credit Ref">Credit Ref</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_CreditRef" name="CreditRef" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field Hq" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_Hq" title="Hq">Hq</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_Hq" name="Hq" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field VatNumber" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_VatNumber" title="Vat Number">Vat Number</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_VatNumber" name="VatNumber" readonly="readonly"><div class="vx"></div><div class="clear"></div></div><div class="field WebEnabled" style="display: none;"><label class="caption" for="Delpac_Default_CustomerDialog7_WebEnabled" title="Web Enabled">Web Enabled</label><input type="text" class="editor flexify s-StringEditor readonly" id="Delpac_Default_CustomerDialog7_WebEnabled" name="WebEnabled" readonly="readonly"><div class="vx"></div><div class="clear"></div></div></div></div></div>                    <div class="clear"></div>                </div>            </form>        </div>    </div>               <div id="Delpac_Default_CustomerDialog7_VwContactsGrid">        </div>   </div>

**Comment by zappitmr** [comment]
@edwardch Tried that, still no luck. I have 3 tabs on the dialog each with a grid. 2 of the tabs are working without an issue, but as soon as I add the contacts tab with the contacts grid on it it gives the error above. But all works ok on the local environment.

**Comment by zappitmr** [comment]
On template called CustomerDialog.Template.html. I've removed the other tabs and grids and just have one dialog with one tab Contacts with a grid on this tab and still getting the same issue. I can't understand why it works in local environment and not on live.

**Comment by zappitmr** [comment]
I didn't find the root of this issue So I had to resort to deleting the modules and rebuilding and is now working as it should.

**Comment by stixoffire** [comment]
@zappitmr  yes sometimes after spending time to figure it out - I rename my existing, and run the template creator sergen , see if that works, then start adding the features back in little by little and sometimes I find my mistake (usually something dumb that I have done like forgetting this or that or adding some declarative attribute that I should not have).

**Comment by ibrahimGit123** [comment]
I recently migrated from .Net 3 to .Net 6 and I am seeing the same error explained here (e.g. only when I Deploy to my Web App but not on Local Host). I tried all the suggested solutions above but with no luck. Was anyone able to solve this issue?

**Comment by d-donato** [comment]
@ibrahimGit123 in the .Net 6 when you compile and publish, templates.cshtml aren't automatically created. 
You have 2 options:
  you can create manually the Modules/Common/YourPage/YourTemplate.cshtml in your published directory
  or you can go in your project, right click on the template.cshtml, click on properties and change the "Copy in output directory" option from don't copy to always copy
