### ISSUE TITLE
Add lookupeditor in signup page

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#489]
Hi All,

I need to add  dropdownlist in User Sign up as below, but no data populated in Site dropdownlist, already set LookupEditor in SignUpForm.cs. Please Help.

![eas](https://cloud.githubusercontent.com/assets/6382278/14168853/c4779cae-f74e-11e5-90f7-a4abc4ef619c.png)

**Comment by volkanceylan** [comment]
Set LookupScript("BlaBla.Site", Permission = "*")

**Comment by rudianto2008** [comment]
Works thanks Jaiq

**Comment by mzamonkosi** [comment]
Hi Fazanan
 
I'm trying to do the same thing but im getting the following error 

{"Type SignUpForm can't be registered as a lookup script!"}

Could you please give me pointers on how to resolve it

Regards,
Mzamo
