### ISSUE TITLE
Requested value 'admin' was not found.

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4890]
When I try to modify/create user, I always got error information 'Requested value 'admin' was not found.'    (modify/create other entity is ok)

![image](https://user-images.githubusercontent.com/16734387/76034110-f0452900-5f78-11ea-8f57-78f6dc5d678a.png)

And it even cannot get into the create EndPoint. 
![image](https://user-images.githubusercontent.com/16734387/76034188-2bdff300-5f79-11ea-9fb0-94438fe14a2a.png)

**Comment by Nathan2020-0126** [comment]
When I tried with Google Chrome, it work.
Wehn I tried with Firefox, it didnot work, and came with the error 'Requested value 'admin' was not found'

**Comment by edwardch** [comment]
I've seen this before and I think you need to turn off the autofill/auto complete options in Firefox. 

You should be able to do it on the browser level, and also on a site level. 

Try fiddle around with those settings and let me know if it helps?

**Comment by Nathan2020-0126** [comment]
It works, thanks very much

**Comment by edwardch** [comment]
Good to hear. 

I have also seen this happen on Safari where the quicksearch fields are autocorrected and you can't actually search what you want to search for. In case you use Safari and experience this issue, you must disable autocorrect like so:

![image](https://user-images.githubusercontent.com/4890069/76085639-1f7c8a00-5fbb-11ea-9d78-6427caa1011a.png)
Uncheck this menu item.

@Nathan2020-0126 if you're happy please close the issue.

Thanks!

**Comment by Nathan2020-0126** [comment]
ok, thanks very much for your further infomation.
