### ISSUE TITLE
New project in ASP.NET Core 3.1 dont load the .ts source in front for debug. 

### ISSUE THREAD

**Issue by rcruzfalcon** [volkanceylan/Serenity#4895]
Hi

In new project when try to see any .ts source, always return:

Could not load content for http://localhost:59952/Modules/Administration/Language/LanguageDialog.ts : HTTP status code: 404

I miss something?

Best regards
Roberto

**Comment by rcruzfalcon** [comment]
We must add in tsconfig.json this lines:

 "inlineSourceMap": true,
    "inlineSources": true,

best regards
Roberto

**Comment by petebr** [comment]
I've just had this issue, your suggestion didn't work. Any further ideas?

**Comment by petebr** [comment]
Just realized they need to be inside "compilerOptions" - but having moved them, still no joy. Clean and rebuild didn't help.

**Comment by petebr** [comment]
nuts! I put in a `debugger;` to stop inside javascript and the modules appeared. Must have been a cache problem in Chrome.

thanks!
