### ISSUE TITLE
ICellDecorator netstandard2.0 string type not Color 

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4896]
Hi,

I'm upgrading system to .net core 3.1 and getting this error

![image](https://user-images.githubusercontent.com/2279508/76288298-ffa9d680-62d8-11ea-8947-7957b3bf22df.png)

I checked [ICellDecorator.cs](https://github.com/volkanceylan/Serenity/blob/57f134e452848034c50c79cee56ba2a5f81cf216/Serenity.Services/Reporting/ICellDecorator.cs) here, it said **Background** and **Foreground** is Color type

but after installing package Serenity.Services 3.12.4 they are string type

![image](https://user-images.githubusercontent.com/2279508/76288465-5ca58c80-62d9-11ea-8a6c-4dbf0c1e538b.png)

Btw I also getting error with TranslationRepository

>The type or namespace name 'IDependencyRegistrar' could not be found (are you missing a using directive or an assembly reference?)

**Comment by minhhungit** [comment]
Nevermind I fixed it

It's my mistake, I forgot remove **$(TargetFramework)' == 'netcoreapp2.2** in bellow PropertyGroup

It should like this like suggestion from [here](https://github.com/volkanceylan/Serenity/issues/4801)

```
<PropertyGroup>
    <DefineConstants>$(DefineConstants);COREFX;ASPNETCORE</DefineConstants>
  </PropertyGroup>
```
not
```
<PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <DefineConstants>$(DefineConstants);COREFX;ASPNETCORE</DefineConstants>
  </PropertyGroup>
```

**Comment by DanielRuanova** [comment]
Thanks to your problem and answer it was very helpful since I had the same problem today.
