### ISSUE TITLE
Adding Label to Footer Slickgrid Row

### ISSUE THREAD

**Issue by glenngsanchez** [volkanceylan/Serenity#4898]
Hi All,

How can add label inside grid footer like below?  

![image](https://user-images.githubusercontent.com/23032787/76392312-41f01800-63ac-11ea-9909-c099ab30fd54.png)

Thanks!

**Comment by stixoffire** [comment]
in your grid  constructor : this.element..append("<tr><td></td><td></td></tr>")
element should be the grid (it is in the editor.ts) it might be named something else, you can do a this.find(whatever the class of the grid is).append(your html);

I just did something similar to this myself.

**Comment by glenngsanchez** [comment]
Hi @stixoffire , 

I'm not sure which editor your referring to but i tried updating this AppointmentsGrid.ts and 
this is my constructor.
`constructor(container: JQuery) {
super(container);
     $(".slick-footerrow-columns").first().children().first().html("Total");
}
`

this line thou works on the browser's console.

` $(".slick-footerrow-columns").first().children().first().html("Total");`


![image](https://user-images.githubusercontent.com/23032787/76581783-89db8000-650f-11ea-8c72-1e11415053d4.png)

did not work for my case.

**Comment by stixoffire** [comment]
@glenngsanchez  .html("TOTAL") is a text value not html , if you want to place 'TEXT' use the .Text  method on the element , or a valid html '<div>Text<div>'  you might also get away with html(myhtmlencoded string) but I don't think so.
Remember you can use .Prepend, .append etc ..to place it anywhere you like.

```
       private _originalPager = $(".s-SlickPager");
        private _lastQuote: JQuery = $("<span><strong><span class='customquoter-curquote' id='lastQuoteNumber'>STUFF</span></strong></span>");

        constructor(container: JQuery) {
            super(container);

             // Method 1
	     this._originalPager.find(".slick-pg-in").append(this._lastQuote);
}

```

Also while I was posting this for you - I posted something similar but more involved.

[Add Summary Footer to Detail Grid](https://github.com/volkanceylan/Serenity/issues/282)

**Comment by glenngsanchez** [comment]
This line works when run in browser console:

$(".slick-footerrow-columns").first().children().first().html("Total");

I am not trying to append and html element but just text.

If there is a document to show where should this line must be place, or some kind of Slickgrid lifecycle inside Serenity, that will be helpful.

cheers!

**Comment by JohnRanger** [comment]
Hi @glenngsanchez ,

I am in no way an expert in HTML an Javascript - but could it be that you have to put it into the document.ready event instead of the constructor? (I had often the problem that when I have put things into the constructor within Serenity Framework, that it was executed too early - so the objects were not yet available).

With kind regards,

John

**Comment by stixoffire** [comment]
@glenngsanchez 

I spent a couple hours testing this - and I have to say I ran into the same issues - I researched the slickGrid component and it seems those method for 

> getFooterRowColumn(columnId);

 is not in the serenity application - I am wondering if the slickGrid version in Serenity is up to date with the code I found online. I am not sure if you can update it directly with out some issues to arise . If you have a new app I would try it - you can always revert, if it is an older app - copy to a different folder and work on it there and test it out.

**Comment by stixoffire** [comment]
@glenngsanchez [slickGrid 2.4](https://github.com/6pac/SlickGrid) supports this functionality . I do not know if slickGrid can be updated with out any issues ..

**Comment by glenngsanchez** [comment]
nice. I will try 

> Hi @glenngsanchez ,
> 
> I am in no way an expert in HTML an Javascript - but could it be that you have to put it into the document.ready event instead of the constructor? (I had often the problem that when I have put things into the constructor within Serenity Framework, that it was executed too early - so the objects were not yet available).
> 
> With kind regards,
> 
> John

I have tried this as well.  document.ready seems to be fired first than slickgrid constructor.

**Comment by glenngsanchez** [comment]
> @glenngsanchez [slickGrid 2.4](https://github.com/6pac/SlickGrid) supports this functionality . I do not know if slickGrid can be updated with out any issues ..

i will try this and let you know my findings. thanks!

**Comment by JohnRanger** [comment]
Hi @glenngsanchez ,

in some case I had to do things within SF-based apps with delayed execution in order to get the execution sequence right - i.e. putting the code which should be executed later into a setTimeout block and find the necessary delay by trial and error - and then adding a good amount of margin so that it would work also in slower machines. I know - totally ugly - but what can you do if browsers behaves unexpectedly.

Timing issues are my "friends"...

Regards,

John
