### ISSUE TITLE
'CONCAT' is not a recognized built-in function name.

### ISSUE THREAD

**Issue by huynhvanquy** [volkanceylan/Serenity#4899]
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: 'CONCAT' is not a recognized built-in function name.

Source Error:
Line 7:  @Html.Script("dynamic://Lookup.Northwind.CustomerCountry") Line 8:  @Html.Script("dynamic://Lookup.Northwind.CustomerCity") Line 9:  @Html.Script("dynamic://Lookup.Northwind.Employee") Line 10: <script>var CKEDITOR_BASEPATH = '@ContentHashCache.ResolvePath("~/Scripts/ckeditor/")';</script> Line 11: @Html.ScriptBundle("CKEditor")

**Comment by volkanceylan** [comment]
Check your SQL version

**Comment by stixoffire** [comment]
@huynhvanquy I had something similar happen one time. When I looked at the actual query going to the sql server it was not correct - I found a small error in my code that caused the query to be malformed - but project still built. I fixed the error and problem went away.

**Comment by minhhungit** [comment]
@huynhvanquy check your sql server version as Volkan suggested, CONCAT was introduced in SQL Server 2012, you might using sql 2008 or older

**Comment by minhhungit** [comment]
Check more at here: https://serenity.is/Docs/work-with-other-database-types

**Comment by huynhvanquy** [comment]
Thanks all!

**Comment by S-Muthuselvakumar** [comment]
> Check more at here: https://serenity.is/Docs/work-with-other-database-types

Its not opened
![image](https://github.com/serenity-is/Serenity/assets/138861620/d91ed76d-d91d-4c94-94df-9cb8f90ed1ef)

**Comment by VictorTomaili** [comment]
https://serenity.is/docs/framework/data-access/sql-connections
