### ISSUE TITLE
IIdField Fails when key is a string

### ISSUE THREAD

**Issue by rturluck** [volkanceylan/Serenity#49]
```
Cannot implicitly convert type 'Serenity.Data.StringField' to 'Serenity.Data.IIdField'. 
An explicit conversion exists (are you missing a cast?)
```

It seems that the only table(s) that are causing issues are those with key fields that are strings/varchars.  Its possible that I may have configured something incorrectly.  I used sergen to auto generate the code that has the issue.  If I remove the table(s) that contain StringField keys then everything works.

**Comment by volkanceylan** [comment]
IIdField interface is only implemented by integer field types (Int16, Int32, Int64). Is it not possible to add an autoincrementing integer ID to tables you use? Otherwise, you can remove IIdRow interface from generated code, but this time you'll get errors on SaveHandler etc.

Customer table in Northwind also had string primary keys, but i added an integer ID column to use it with Serenity.

**Comment by rturluck** [comment]
No its not going to be possible to add a auto inc field.  The keys we use in most cases are not arbitrary numbers but meaningful keys and in some cases they are company codes (varchars).  I need to figure out a workaround for this.  Ill walk through the code and see if there is something I can do to make it work with my scenario. 

Thanks for the quick response!!!

**Comment by volkanceylan** [comment]
I didn't mean to change primary key, just add an additional autoincrementing field to the table, you don't need to include it in the primary key, it is just to help Serenity work with your table. You will just set it as ID field in interface implementation in row.

**Comment by rturluck** [comment]
I completely understand I just dont think they will go for it.  Changing table structures so that they can conform to a scaffolding tool.  They will most likely tell me that it should be the other way around.  That the tool should hook into the existing structure.  Its hard to get something changed like a DB that has been in a production environment for close to a decade.  Adding a field could cause legacy systems to fail (ex-inserts without param specification).  Looks like im going to try and hack it....Thanks for your help!
