### ISSUE TITLE
Dynamically add external links

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#490]
In issue #400 I asked about adding external links into the navigation. I have been able to do this without any issue, but now I have another question. How can I do this (doesn't have to be in the navigation panel, it would be nice, but doesn't have to be) from the website itself. i.e. not in the actual code. 

The goal I am trying to accomplish is allowing the admins of the site to be able to add / change / delete external links so that it doesn't require me to run to the source code to change a link.

Can this be done? If so how might one implement this?

**Comment by volkanceylan** [comment]
Take a copy of NavigationHelper as MyNavigationHelper, modify GetNavigationItemAttributes method, after 

```cs
                foreach (var assembly in ExtensibilityHelper.SelfAssemblies)
                {
                    foreach (NavigationItemAttribute attr in assembly.GetCustomAttributes(typeof(NavigationItemAttribute), false))
                    {
                        if (filter == null || filter(attr))
                            list.Add(attr);
                    }
                }
```

this load your items from database, json etc. add them to list.

Call your MyNavigationHelper from NavigationModel.cs

**Comment by wdhodges** [comment]
Then just add a new screen where a user can Insert / Update / Delete links from the database?

**Comment by volkanceylan** [comment]
Yes :+1:

**Comment by wdhodges** [comment]
Awesome, I'll test this out as soon as I return to the office. Thanks @volkanceylan

**Comment by 107295472** [comment]
You saved the menu to the database

**Comment by wdhodges** [comment]
@volkanceylan hate to comment on a closed issue but I was trying this out tonight and can't seem to figure it out. Where do I find the NaviationHelper? and how do I pull it from the database (sql)? This level of coding is a little beyond me, Thanks in advance!

**Comment by volkanceylan** [comment]
In Serenity source code. You should use connection.List< MyEntityRow >() thats all. Of course open a connection first, SqlConnections.NewFor < MyEntityRow >

**Comment by wdhodges** [comment]
I never downloaded the source code for Serenity, I've just been using the Serene template. Is there a way to change it from Serene Template?

**Comment by volkanceylan** [comment]
Search it here, you don't have to download

**Comment by wdhodges** [comment]
I'm sorry my friend, what do you mean by search it here? It's been a long night.

**Comment by volkanceylan** [comment]
There is a search box at top

**Comment by wdhodges** [comment]
wow...long night indeed. Thanks

**Comment by wdhodges** [comment]
@volkanceylan sorry to comment on this issue yet again, but I was wondering how do I actually get the information from the database? You said alter it after the code section above, but I'm not sure what you mean? I have a table named fire.ExternalLinks..

**Comment by wdhodges** [comment]
@volkanceylan anything sir?

**Comment by volkanceylan** [comment]
connection.List< MyRow> ()

**Comment by wdhodges** [comment]
Again, my friend I'm sorry for commenting again...Where and how do I call connection.List<MyRow>() from NavigationModel.cs?

**Comment by wdhodges** [comment]
@volkanceylan I know that i'm probably annoying you with this issue, but this is a huge todo in our progress to 1.0.0. Is there anyway you could shed additional light on this? Thanks in advance my friend, and again sorry bothering you yet again with this.

**Comment by volkanceylan** [comment]
Position is correct

```cs
using (var connection = SqlConnections.NewFor<ExternalLinksRow>()) {
    foreach (var x in connection.List<ExternalLinksRow>()) {
        list.Add(new NavigationLinkAttribute(x.Order, x.Path, ....));
    }
}

return list;

```

Don't forget to return list.

**Comment by wdhodges** [comment]
Outstanding. I will work with tonight. Thank you man, seriously.

**Comment by wdhodges** [comment]
@volkanceylan hate to bother you again...

This is my DynamicNavigationHelper.cs file where you have been helping me. 

![image](https://cloud.githubusercontent.com/assets/11448029/15090013/11996962-13e3-11e6-977a-849726a54fd9.png)

But I'm running into the issue of not knowing where to call the DynamicNavigationHelper.cs from in the NavigationModel.cs. Here is my NavigationModel.cs at the beginning where I think I need to put it, but I'm not sure the parameter to pass it. I've tried removing the `filter` parameter, but that didn't work either.

![image](https://cloud.githubusercontent.com/assets/11448029/15090024/6438472e-13e3-11e6-8256-bb61311c9a12.png)

**Comment by volkanceylan** [comment]
Just replace with yours and pass null

**Comment by wdhodges** [comment]
replace the entire content of NavigationModel() ?

**Comment by volkanceylan** [comment]
just replace old NavigationHelper with yours

**Comment by DucThanhNguyen** [comment]
Now you can inject dynamic navigation items in Serene without modify Senerity. Look at this wiki
[Dynamic navigation items](https://github.com/volkanceylan/Serenity/wiki/Dynamic-navigation-items)

**Comment by PedroHFranco** [comment]
Hi @DucThanhNguyen 
How could i reload this Navigation? 
Cause i have an register of dashboards, so when users add a new navigation custumer i need to reload the navigation to apears the new "menu" without recompiling my application...

```
public class DynamicDashboards : INavigationItemSource
    {
        public List<NavigationItemAttribute> GetItems()
        {
            var items = new List<NavigationItemAttribute>
            {
                new NavigationMenuAttribute(1000, "Dashboards", "icon-speedometer")
            };

            using (var connection = SqlConnections.NewByKey("Default"))
            {
                var dashboards = connection.List<DashboardsRow>();
                foreach (var dashboard in dashboards)
                    items.Add(new NavigationLinkAttribute(1000,
                        path: "Dashboards/" + dashboard.Descricao.Replace("/", "//"),
                        url: "~/Dashboards/DefaultDashboard?link=" + dashboard.Link,
                        permission: CadastrosPermissionKeys.General,
                        icon: "icon-folder-alt"));
            }

            return items;
        }
    }
```

This is my custom navigation...

Them, user can register it.

![image](https://user-images.githubusercontent.com/10779853/29972047-2051d580-8f01-11e7-8c6d-308ec79e9499.png)

![image](https://user-images.githubusercontent.com/10779853/29972095-47a8a870-8f01-11e7-86c4-3f789b66d227.png)

**Comment by Magik3a** [comment]
Navigation is cached, so i think the best way is to just remove it from cache in DashboardsRepository

`
        private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void AfterSave()
            {
                base.AfterSave();

                TwoLevelCache.Remove("LeftNavigationModel:NavigationItems:" + (Authorization.UserId ?? "-1"));
            }
        }

        private class MyDeleteHandler : DeleteRequestHandler<MyRow>
        {
            protected override void OnAfterDelete()
            {
                base.OnAfterDelete();

                TwoLevelCache.Remove("LeftNavigationModel:NavigationItems:" + (Authorization.UserId ?? "-1"));
            }
        }`

**Comment by jmkamran** [comment]
subscribe my channel also your answer is in my video https://youtu.be/Ib8OLxC4Jrs
