### ISSUE TITLE
Document History

### ISSUE THREAD

**Issue by dekzao** [volkanceylan/Serenity#4900]
I have a documents table and i would like that when i create an entry or edit one that would go to a history table. can you help me doing that? im new to serenity and i couldn't find a similar thing in the tutorials

**Comment by stixoffire** [comment]
@dekzao  There is a sample of Auditing - you can utilize the auditing sample - so on inserts / updates / deletes you get a record in a table - you can modify it for your use. Should be straight forward. The code is fairly simple.

Or you can place a trigger on your table in the database and simply on trigger write to your other table.

**Comment by dekzao** [comment]
@stixoffire im using serene net core, i don't know if it is because of that but in 
"string GetPageUrl()
        {
            string pageUrl = "";
            if (HttpContext.Current != null && HttpContext.Current.Request != null)
            {
                var httpRequest = HttpContext.Current.Request;
                if (httpRequest.UrlReferrer != null)
                    pageUrl = httpRequest.UrlReferrer.PathAndQuery;
                else if (httpRequest.Url != null)
                    pageUrl = httpRequest.Url.PathAndQuery;
            }
            return pageUrl;
        }"

i get an error saying that httpcontext does not contain a definition for current any suggestions?

**Comment by stixoffire** [comment]
@dekzao 

HttpContext.Current doesn't exist anymore in ASP.NET Core  you need to use Microsoft.AspNetCore.Http.HttpContext and  access the interface IHttpContextAccessor 


```
public class MyComponent : IMyComponent
{
    private readonly IHttpContextAccessor _contextAccessor;

    public MyComponent(IHttpContextAccessor contextAccessor)
    {
        _contextAccessor = contextAccessor;
    }

    public string GetDataFromSession()
    {
        return _contextAccessor.HttpContext.Session.GetString(*KEY*);
    }
}
```
[How To Get Context in .NET CORE (https://stackoverflow.com/questions/38571032/how-to-get-httpcontext-current-in-asp-net-core)
