### ISSUE TITLE
Serenity Guide: The Cast and Characters they played.

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4901]
[Serenity Guide - Cast and Characters they played](https://serenity.is/docs/tutorials/movies/the_cast_and_characters_they_played)
Has an issue with the intermediary table layout - PersonId and MovieId column headers are over the wrong data.
Not sure if this should go here but thought - I should at least FYI. (I am reading that guide in detail.)
Intermediary Table - data does not line up with the column headers.
![PersonsIntermediary](https://user-images.githubusercontent.com/9748682/76536598-9053f400-644a-11ea-84d1-79c7db7b35a9.png)

Below is what it should look like. 

![PersonsIntermediary_Corrected](https://user-images.githubusercontent.com/9748682/76536622-96e26b80-644a-11ea-9ab1-993190346d69.png)

**Comment by volkanceylan** [comment]
Fixed in docs.
