### ISSUE TITLE
Fetch multiple rows

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4902]
How can I fetch multiple rows from an entity (example columns as follows):

Table ID  |	Col A	|   Col B	|    ItemId  	|    Col D

I want to retrieve rows using **Item Id**  as above and not Table ID.

I tried getLookup but am not sure of its exact usage. Or Should I try writing lookup service. Or Can I use existing Retrieve service. Explanation around the above will be of great help.

**Comment by stixoffire** [comment]
Query the Table and use where clause .. Add Criteria to your request ..
Search the code that was generated for Northwind - you can find example there .
Also in [MovieDB example ](https://serenity.is/docs/tutorials/movies/the_cast_and_characters_they_played)

**Comment by reacharihant** [comment]
Thanks, I have written a service for this.
