### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by DavidMhluzi** [volkanceylan/Serenity#4904]
Hi,

All my pages including the default ones like Administration -> User management are coming up as blank and shows the above error on the browsers console. Another error is "ProjectName is not defined". 

I tried cleaning the Solution, Transform All T4 templates and rebuild but still no luck. Please help @volkanceylan

**Comment by JohnRanger** [comment]
@DavidMhluzi ,

I also had this recently with a brand new project which I tried to create with the most recent VS from the newest Serene template (3.14.x).

In my case in the Content folder there were about 75% of the usual files missing. I had to copy them from an older project I had around and then putting the files in the correct folder structure (I just looked at the 404 errors and have moved the files into the appropriate folders (create them if they don't exist) until there were no errors anymore).

I don't know if this is an issue with one of the newest Visual Studio updates in conjunction with the newest Serene templates on the VS marketplace - but this resolved the problem.

Hope this helps.

With kind regards,

John

**Comment by Zahar661** [comment]
@DavidMhluzi Hello! Now I also suffered while creating the project. As he created all the modules with jackdaws, he immediately started and worked. clean did not start.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
