### ISSUE TITLE
Fluent Runner for Sqlite

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#4906]
Hi All,
I'm trying to use sqlite with serenity core 3.1 and am getting the following error when RunMigrations is called.
Invalid attempt to call Read when reader is closed.
The database is created but the error occurs when creating the versioninfo table, so it probably has something to do with the open failing?

**Comment by RouteTech** [comment]
FWIW,
the resolution to this problem was to remove Serenity.FluentMigrator.Runner nuget package which is described as "This is a temporary .NET Core port of FluentMigrator for Serenity applications. It will only be used until an official version is out.".
replaced the following in DataMigrations.cs
            using (var sw = new StringWriter())
            {
                Announcer announcer = isOracle || isFirebird ?
                    new TextWriterAnnouncer(sw) { ShowSql = true } :
                    new TextWriterWithGoAnnouncer(sw) { ShowSql = true };

                var runner = new RunnerContext(announcer)
                {
                    Database = databaseType,
                    Connection = cs.ConnectionString,
#if COREFX
                    TargetAssemblies = new[] { typeof(DataMigrations).Assembly },
#else
                                Targets = new string[] { typeof(DataMigrations).Assembly.Location },
#endif
                    Task = "migrate:up",
                    WorkingDirectory = Path.GetDirectoryName(typeof(DataMigrations).Assembly.Location),
                    Namespace = "Scott.Migrations." + databaseKey + "DB",
                    Timeout = 90
                };

                var culture = CultureInfo.CurrentCulture;
                try
                {
                    if (isFirebird)
                        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;


                    new TaskExecutor(runner)
                    {
#if COREFX
                        ConnectionString = cs.ConnectionString
#endif
                    }.Execute();
                }
                catch (Exception ex)
                {
                    throw new Exception("Error executing migration:\r\n" +
                        sw.ToString(), ex);
                }
                finally
                {
                    if (isFirebird)
                        Thread.CurrentThread.CurrentCulture = culture;
                }
            }

Replaced with

var serviceProvider = new ServiceCollection()
                    // Logging is the replacement for the old IAnnouncer
                    .AddLogging(lb => lb.AddFluentMigratorConsole())
                    // Registration of all FluentMigrator-specific services
                    .AddFluentMigratorCore()
                    // Configure the runner
                    .ConfigureRunner(
                        builder => builder
                            // Use SQLite
                            .AddSQLite()
                            // The SQLite connection string
                            .WithGlobalConnectionString(connection)
                            // Specify the assembly with the migrations
                            .WithMigrationsIn(typeof(DataMigrations).Assembly))
                    .BuildServiceProvider();

            // Put the database update into a scope to ensure
            // that all resources will be disposed.
            using (var scope = serviceProvider.CreateScope())
            {
                // Instantiate the runner
                var runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();

                // Execute the migrations
                runner.MigrateUp();
            }

**Comment by JohnRanger** [comment]
@RouteTech ,

thank you very much for this very helpful information. The problem is still there in newest Serene 3.

**Comment by RouteTech** [comment]
@JohnRanger 
I just upgraded that project to Serene 3.13.4 and it still seems to work.
You have to have the Microsoft.Data.Sqlite nuget package installed.
FWIW, I found that most times it failed because the provider failed to load or the permissions to the local directory were incorrect.
HTH
