### ISSUE TITLE
Asp.net Core Error

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4907]
Hi, 
I have create an Asp.net Core Project but when I try to build or run, I get the error in the image below. Please help.

![asp net core error](https://user-images.githubusercontent.com/14317420/76699152-554bfd80-66a2-11ea-9e31-6c2bc9d2afeb.PNG)

**Comment by kilroyFR** [comment]
Looks like an internet connections error not serenity related issue. I am using .net core project with no issues

**Comment by gfo2007** [comment]
@kilroyFR my internet connection is perfectly fine. I am however behind the corporate proxy so I don't know if that it what is causing the error.

Any other clues?

**Comment by kilroyFR** [comment]
https://www.freecodecamp.org/forum/t/how-to-run-npm-behind-a-proxy-server-a-step-by-step-guide/19386
