### ISSUE TITLE
how to popup another form

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4908]
I need help in popping up a form based on selecting a value from the drop down list.
For example the drop down will have three values like

- Active
-Closed
-Moved

I need to open a separate form for "Closed" for example and another for "Moved" value. Each form will have different properties that need to be filled.

I am familiar with inplace editor but I am not sure how to configure it and I also found a good wiki [here ](https://github.com/volkanceylan/Serenity/wiki/UI:-Slider-dialog-(poor-man's-EntityGridDialog)) by @minhhungit but It is working on the same form. 

Thanks for any help

**Comment by JohnRanger** [comment]
Hi @ms4hafiz ,

I don't understand your use case. Can you elaborate more? Are these 3 stati (closed, moved, Active) values of a field within the grid? If yes - What is the reason you cannot use one form which includes all fields needed for all 3 stati and then selectively hide those which are not needed for a specific status (e.g. if you want to show the form for a "closed" status, hide those fields which are not desired for the "closed" status).

With kind regards,

John

**Comment by ms4hafiz** [comment]
@JohnRanger 
Thanks. One way could be as you suggested but the forms requirements for each status is much different. Anyway I have now figure it through database modeling.
