### ISSUE TITLE
ICaptureLogRow doubt

### ISSUE THREAD

**Issue by dekzao** [volkanceylan/Serenity#4910]
Hey, im trying to use the ICaptureLogRow so i can make the history of a record. In my database i have both the table for the record and another for the history but im having problems. In my record's table it's identity is id and the identity for my logs table is also id. 

This is what i want to do
Log table     -> Document
IdDocument -> Id

The thing is "Can't find match in the row for log table field "; and IdDocument is set as foreign key
Any suggestions?

**Comment by dekzao** [comment]
ok i managed to solve this issue by modifying my database and now instead of id i got IdDocument -> IdDocument but now if i try to edit the record i got an error saying invalid column 'id' but in the code its detecting 'IdDocument' suggestions?

**Comment by volkanceylan** [comment]
All field names in capture log table must match, and there should be a ID column (does not need to be ID, just identity + primary key)
