### ISSUE TITLE
add div (list,textboxes)  above inline edit grid

### ISSUE THREAD

**Issue by imtiazhashmi** [volkanceylan/Serenity#4912]
Im new to serenity , tried to search the topic without success.
i have an inline edit grid , 4 columns in the grid will have similar data , i want to place them above inline edit.
I want to add a new bar (Div)  below toolbar to hold static html input controls .
Help will be appreciated.

**Comment by stixoffire** [comment]
Start [here ^](https://github.com/volkanceylan/Serenity/issues/4898)

**Comment by imtiazhashmi** [comment]
Thanks
