### ISSUE TITLE
How to pre-populate a grid with multiple rows

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4913]
I have followed example from the Northwind:
///
.
.
dlg.loadEntityAndOpenDialog(<Northwind.OrderRow>{
                        CustomerID: 'GOURL',
                        EmployeeID: lauraCallahanID,
                        DetailList: [{
                            ProductID: chai.ProductID,
                            ProductName: chai.ProductName,
                            UnitPrice: chai.UnitPrice,
                            Quantity: 5,
                            LineTotal: chai.UnitPrice * 5
                        }]
                    });

**However, I have an array and would want populate multiple rows here**. Also, related to this question is that how can I fetch specific items from the array to populate this grid. Any working example would be very helpful.

**Comment by csabc** [comment]
you can see that example: northwid  order`   public RowListField<OrderDetailRow> DetailList;`
