### ISSUE TITLE
*bug?* Thumbnail generation not enabled by default in serene.core template

### ISSUE THREAD

**Issue by OpenlabWA** [volkanceylan/Serenity#4914]
Not sure if intentionally disabled by default.

In the serene.web template a default thumbnail size is specified and therefore thumbnails are created, however in the serene.core template, the UploadProcessor is instantiated (inside FilePage.cs) without default thumbnail resolutions specified causing the thumbnail not to be created.

Serene.web 
https://github.com/volkanceylan/Serene/blob/4b03007dadacfe912c1161a2896ea515bb0cd720/Serene/Serene.Web/Modules/Common/File/FilePage.cs#L50

Serene.core
https://github.com/volkanceylan/Serene/blob/4b03007dadacfe912c1161a2896ea515bb0cd720/Serene/Serene.Core/Modules/Common/File/FilePage.cs#L66

**Comment by volkanceylan** [comment]
.NET core didn't have system.drawing before so we had to. Now it has.
