### ISSUE TITLE
How to enable errorlog.axd

### ISSUE THREAD

**Issue by rafjsouza** [volkanceylan/Serenity#4916]
How can i enable the errorlog.axd on a dotnet core application on Serenity?

**Comment by volkanceylan** [comment]
It has a different url, see the link in menu

**Comment by petebr** [comment]
There is no menu for errorlog in dot net core version, that I can see...

> It has a different url, see the link in menu

please tell us what the link is.

**Comment by volkanceylan** [comment]
It is under Administration/Exception Log, if you can't find it in menu, then you don't have it.

**Comment by petebr** [comment]
Thanks for your update.
I'm taking this to mean that there is no error logging in dot net core version. 
Please correct me if this is untrue.
