### ISSUE TITLE
Quicksearch; How to treat multiple words as "and" and not as whole text

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4917]
Hi all,

currently, the quicksearch acts as a "block" text search - i.e. the whole entered string must be found.

I would like to change the search behavior for one specific grid/quicksearch - so that multiple words entered within the quicksearch act like an additional filter.

For example - When we have the following searchable record values within a field flagged for quicksearch:

- Green car
- Blue Car
- Car xyz blue

 When there is the String "car" entered entered in the quicksearch, all rows which contain the word "car" should be listed.
- Green car
- Blue Car
- Car xyz blue

(This works with the standard quicksearch filtering implementation).

-------------------

When there is the string "blue car" entered in the quicksearch, the following records should be listed:

- Blue Car
- Car xyz blue

In the standard implementation of the quicksearch filtering, only the following record is listed:

- Blue Car

---------

How to do this?

(I had a look at overriding protected onViewSubmit() in the xyzGrid.ts but do not understand how to retrieve the currently entered quicksearch string and how to modify the request.Criteria in order to achieve this).

Maybe I am looking at the wrong place.

any help is greatly appreciated.

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger in your QuickSearch I am assuming that the code looks something like this:

`[QuickSearch]`

try something like:
> QuickSearch(SearchType.Contains)
> QuickSearch(SearchType.FullTextContains)

**Comment by JohnRanger** [comment]
@stixoffire ,
thanks for your feedback. Will have to look into this and give feedback if it works or not.

With kind regards,

John

**Comment by leahmayschneider** [comment]
If it helps anyone here, I had this same issue and while looking into the generated SQL from searching (contains is default), I found that you can use SQL wildcards (% and _). "Blue car" will only find "Blue car" but "Blue%car" will find "Blue car" and "Blue shiny car". I don't think there's a way to find both "blue car" and "car blue".
