### ISSUE TITLE
Parse Serenity.Services.ValidationError in a simple Razor Page

### ISSUE THREAD

**Issue by blindesti** [volkanceylan/Serenity#4919]
I want to parse thrown error messages from serenity (that are returned as JSON) in simple View mvc page, is there any posibility? i get the json as response after error is thrown but is not poped up as alert, but is loaded as new page with json response.
![image](https://user-images.githubusercontent.com/9266361/77262134-685f5e80-6c9c-11ea-8b0b-703a5b5f4081.png)

**Comment by volkanceylan** [comment]
Why dont you use YourProject.SomeService.SomeMethod while calling the service.

If you call the service as if an url, you ll get an error response but as it is a service error will be json
