### ISSUE TITLE
Build Error = Editor' is an ambiguous reference

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#492]
Hi,
Could someone explain this error to me? I got it all of a sudden:
"_Editor' is an ambiguous reference between 'System.ComponentModel.EditorAttribute' and 'Serenity.EditorAttribute'_"

Am I screwed??

**Comment by volkanceylan** [comment]
See troubleshooting

**Comment by biggikalli** [comment]
Thank you Sir 😊
