### ISSUE TITLE
[Question] Serenity.Scripts .net core 2.2 / 3.1 does not include script files into project

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4920]
Hi @volkanceylan 

I am upgrading Serenity.Scripts package for .net core and I see that it does not include scripts files into project so project is still using old files. I tested with both .net core 2.2 and .net core 3.1.

Latest version 3.12.4. 

I also tried to install older versions but it looks no version work.

It works with .net framework project.

I thought that when I upgrade Serenity.Scripts package it will overwrite old files, is that correct ?

![image](https://user-images.githubusercontent.com/2279508/77338901-98226b00-6d5d-11ea-879e-46a87f77f1a1.png)

**Comment by volkanceylan** [comment]
You should run dotnet sergen restore after updating packages, as specified in guide.

.Net core packages cant install static content unlike classic packages.

**Comment by minhhungit** [comment]
>dotnet sergen restore

This works, many thanks
