### ISSUE TITLE
MySQL - SELECT Command denied to user '' for table 'Log'

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4921]
Hi

I just generated .Net Core app, upgraded to 3.1 and runt it again MySQL DB on Centos 7.7
I can log in, but when I try to browse newly added Log table I get this $subj error.
I dont see what is the problem. DB was created by the user, who has all the privileges and all the other tables seem to work :(

**Comment by stixoffire** [comment]
@ga5tan Enable your logging in webconfig and see what the query is . 
You will need to post more info on the error in order for others to try to help .

**Comment by ga5tan** [comment]
I enabled this, but it's not showing SQL statements :(
stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout

**Comment by JohnRanger** [comment]
Hi all,

does it not log within \app_data\logs?

(At least the .net "normal" version logs within \app_data\logs\).

Regards,

John

**Comment by ga5tan** [comment]
It's there, but without SQL
anyway, I think the problem was, that Tablename was generated as [dbo].[Log], which MySQL did not like
