### ISSUE TITLE
Data not getting retrieved from database in typescript

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4922]
Hi,
I have a Sites table in the database. When I try to retrieve data from the table in typescript, I get the error in the image below. SiteCode is a field in the Sites table. The code for retrieving the data is also captured below.

`var siteCode = LookUps.SiteRow.getLookup().itemById[user.SiteId].SiteCode;`

![undefined error](https://user-images.githubusercontent.com/14317420/77395853-6085e400-6d9a-11ea-908a-f53998dbba0b.PNG)

**Comment by stixoffire** [comment]
@gfo2007 

So something like this is not working for you 
`this.form.UnitPrice.value = InventoryItemRow.getLookup().itemById[itemId].UnitPrice;`

Which would tell me perhaps you have no value for your Id field in the ItemById or you have NO record there ..
if you had this prior to your lookup 
`var itemId = Q.toId(this.form.ItemId.value);`

Are you sure you actually have a value for user.SiteId ?
Use IE and set your break points .. use 
var myId = user.SiteId; 
See if you get a value there - if so then query your db and see if it has a record at that location ..

**Comment by gfo2007** [comment]
@stixoffire the user.SiteId is valid. The SiteId for the the logged in user is 17. Below is the full code. It is meant to automatically generate a requisition number. If there are existing requisitions, generate the next requisition by incrementing the number part of the last requisition. If No requisition exists, pick the Site Code from the logged in user's site and and 1 to form the first requisition number.

`/**
         * This method is called when New Item button is clicked.
         * By default, it calls EditItem with an empty entity.
         * This is a good place to fill in default values for New Item button.
         */
        protected addButtonClick() {
            var user = Q.Authorization.userDefinition as ScriptUserDefinition;
            var pendingReq = this.getLookup().items.filter(x => x.SiteId === user.SiteId).sort((a, b) => (a > b ? -1 : 1))[0];
            var newReqNo = "";
            var newNoPart = 0;
            if (pendingReq != null) {
                var lastNoPart = +(pendingReq.RequisitionNo.substring(3));
                newNoPart = lastNoPart + 1;
                newReqNo = pendingReq.RequisitionNo.substring(0, 3) + newNoPart;
            }
            else {
                newNoPart = 1
                var myId = user.SiteId;
                var siteCode = LookUps.SiteRow.getLookup().itemById[user.SiteId].SiteCode;
                console.log(siteCode);
                newReqNo = siteCode + newNoPart;
            }

            
            this.editItem(<AllRequisitions.PendingRequisitionRow>{
                EmployeeID: newReqNo
            });
        }

        private getLookup(): Q.Lookup<PendingRequisitionRow> {
            return Q.getLookup<PendingRequisitionRow>('AllRequisitions.PendingRequisition');
        }

        protected getButtons() {
            // preserving default New Item button
            var buttons = super.getButtons();

            return buttons;
        }
    }`

**Comment by stixoffire** [comment]
@gfo2007 
I reformatted the code and made a couple remarks in the code:

```
        protected addButtonClick() {
            var user = Q.Authorization.userDefinition as ScriptUserDefinition;

            // A sample routine .. not sure what data you are trying to get .. 
            // so this is an example to use to see if you get anything returned.
            if (user.SiteId != null) {
                var pendingReqItem = SiteRow.getLookup().itemById[user.SiteId];
            }

            // What is the object: this .
            // what are the 'items' ? Are they in the grid or truly in your database table ?
            var pendingReq = this.getLookup().items
                     .filter(x => x.SiteId === user.SiteId)
                     .sort((a, b) => (a > b ? -1 : 1))[0];

            var newReqNo = "";
            var newNoPart = 0;
            if (pendingReq != null) {
                var lastNoPart = +(pendingReq.RequisitionNo.substring(3));
                newNoPart = lastNoPart + 1;
                newReqNo = pendingReq.RequisitionNo.substring(0, 3) + newNoPart;
            } else {
                newNoPart = 1 var myId = user.SiteId;
                var siteCode = LookUps.SiteRow.getLookup().itemById[user.SiteId].SiteCode; console.log(siteCode);
                newReqNo = siteCode + newNoPart;
            } this.editItem(<AllRequisitions.PendingRequisitionRow>{ EmployeeID: newReqNo });
        }
        private getLookup(): Q.Lookup<PendingRequisitionRow> { return Q.getLookup<PendingRequisitionRow>('AllRequisitions.PendingRequisition'); }
        protected getButtons() {
            // preserving default New Item button 
            var buttons = super.getButtons(); 
            return buttons;
        }
```

Another way to retrieve data:

```

            MyModuleDB.SiteService.Retrieve(<any>{
                EntityId: "Id"
            }, resp => {

                Q.notifyInfo("My Number: " + resp.Entity.Number);

            });

```

**Comment by gfo2007** [comment]
@stixoffire thanks for your responses so far. I am realizing that I am unable to retrieve the logged in SiteCode of the user.

Please do you have any code snippet in typescript I can use to retrieve details of the logged in user?

**Comment by stixoffire** [comment]
[Doing a quick search here Issues](https://github.com/volkanceylan/Serenity/issues/3345) #3345 
Try this ...
`((UserDefinition)Serenity.Authorization.UserDefinition).UserId`

**Comment by gfo2007** [comment]
@stixoffire the user definition code you have there is for server side. I was hoping to get one for typescript at the client side.

**Comment by gfo2007** [comment]
@stixoffire thanks for all your initial help. I have made some significant progress. The last thing I need help with is how to retrieve a list using the code snippet you pasted.

` MyModuleDB.SiteService.Retrieve(<any>{
                EntityId: "Id"
            }, resp => {

                Q.notifyInfo("My Number: " + resp.Entity.Number);

            });`

The code is for retrieving one record. How do I retrieve a list? I have seen List method for the Service class but I am not sure how to call it to get my data retrieved. Please help.

**Comment by stixoffire** [comment]
@gfo2007 

I believe all you need to change the method from 
MyModuleDB.SiteService..Retrieve
To:
MyModuleDB.SiteService.List


All of your methods in the module XYZService
Can be found in your XYZEndpoint.cs
```
        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyRepository().List(connection, request);
        }
```

Your .cs code is all server side code. 
Your .ts code is all client side code.

In order to communicate to the server your typescript has to have access of those server side code methods So that is actually what you are doing.  Hope that helps you.
