### ISSUE TITLE
Upgrading SlickGrid to Version 2.4 ?

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4923]
Has anyone upgraded SlickGrid to Version 2.4 ? 

@volkanceylan 
Are there any issues with upgrading SlickGrid to version 2.4 ?
There is a lot of functionality in V2.4 like easy access to the footer column and frozen rows - not sure on all of the others but those two seem useful .

**Comment by kilroyFR** [comment]
Volkan said in the past Slickgrid version integrated in Serenity was a customized version.
Guess it would require work to integrate/merge SlickGrid new features.

From which source do you get this v2.4 ? there are som many fork projects of this one on the net.

**Comment by stixoffire** [comment]
@kilroyFR Yes that is the official version right now.  I guess I will need to look into updating the slickGrid by splicing in the functionality that I would like to have.  I am not a real fan of that - because anytime the baseline changes - updates can take your brains away for a while..

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

I believe this is also one of the reasons why "sleekgrid" is on Volkan's roadmap - beside of making it a proper typescript version.

Regards,

John
