### ISSUE TITLE
Less/css not working with .Net Core serenity

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4927]
Hi;
I am trying to align the caption of xDialog but it not working. For example, i have made the following
less

     .s-Master-zProvincesDialog {
     > .size {
        width: 650px;
      }

    .caption {
        width: 200px !important;
        text-align: left !important;
    }

    .editor {
        text-align: left;
           }
     }

Am I missing anything?

**Comment by ga5tan** [comment]
does it transpile?
can u see it in final CSS ?

**Comment by ms4hafiz** [comment]
Found the issue. The problem was with naming of the dialog. When there is the small "z" like zProvincesDialog it is not working but when I changed to capital "Z" like ZProvincesDialog or remove Z it works. I don't know the reason. I could be a validation by serenity or some other issues.
