### ISSUE TITLE
How to put data on a MasterDetail Field via code

### ISSUE THREAD

**Issue by Mondaii** [volkanceylan/Serenity#4929]
I'm trying to put new entities on a ListField,of a MasterDetail field via the main dialog without any sucess, any idea on how i can do this.

  var  produto: EstoquesVendasRow;
                        produto = {
                            Estoque: response.Values[0].cod_estoque,
                            Quantidade: 1                
                        };
                        
                        this.form.ProdutoVenda.value.push(produto);

this is what i was trying to do but the value of entities don't change and the push method is doing nothing.

**Comment by haoas** [comment]
`protected save(opt: Serenity.ServiceOptions<any>, callback: (r: Serenity.ServiceResponse) => void)`
