### ISSUE TITLE
Different Toolbar button set for EntityDialog

### ISSUE THREAD

**Issue by djabeeryusuf** [volkanceylan/Serenity#4930]
I have two EntityDialog even though both are extended from Serenity.EntityDialog each rendering differently

in the second one its missing backbutton with title section..why? what i am missing.

![image](https://user-images.githubusercontent.com/59920049/77896960-16b16800-728a-11ea-998e-735a69897567.png)

below section is missing, rtaher its adding undelete,localization,clone buttons usually that doesnt appear in entitydialog
![image](https://user-images.githubusercontent.com/59920049/77897185-63953e80-728a-11ea-929f-ed9d60adbd23.png)

    @Serenity.Decorators.panel()
    @Serenity.Decorators.registerClass()
    export class Dialogtype1 extends Serenity.EntityDialog<rowtype1, any> {
.....
}

    @Serenity.Decorators.panel()
    @Serenity.Decorators.registerClass()
    export class Dialogtype2 extends Serenity.EntityDialog<rowtype2, any> {
.....
}

**Comment by JohnRanger** [comment]
How does it behave when you remove the panel decorator? What I mean by that is: Does the same problem also occurs if the dialog is displayed as a "real" jQuery dialog and not with this integrated panel?

Regards,

John

**Comment by djabeeryusuf** [comment]
Hi Jhon,
Thanks fo reply.
Yes its still the same without  "@Serenity.Decorators.panel()"
It shows "Clone", "Localisation" and "Undelete" buttonsm whihc not the usualu behaviour of entity Dialog

**Comment by djabeeryusuf** [comment]
@JohnRanger Thanks.
I Figured out,
It was due to not added super.afterLoadEntity(); in overridden afterLoadEntity() method
Thanks

**Comment by JohnRanger** [comment]
@djabeeryusuf ,

then this issue could now be closed, not? Would you mind to close it? :-)

With kind regards,

John

**Comment by djabeeryusuf** [comment]
@JohnRanger Thanks, closed
