### ISSUE TITLE
How to use the defaul value [DefaultValue ("now")] by reading the date from the server

### ISSUE THREAD

**Issue by MimmoDany** [volkanceylan/Serenity#4931]
Hi Volkan

I use the professional version of your framework and it's fantastic.

I want to submit a problem that I encountered on the default dates.

On some forms I have the field to acquire the date [ReadOnly (true)] which I pass with the command: [DefaultValue ("now")]

A user, who had set an incorrect date on his computer, entered an incorrect date.
This is because the date that acquires Serenity as DefaultValue is that of the client.

Can I get the server date as [DefaultValue ("now")]?
Maybe as an optional "ServerDate" parameter
Is there another way to do this?

Thanks in advance

**Comment by volkanceylan** [comment]
You should use a behavior and set such fields on server side, or you may set them in repository manually. Such fields should not be insertable.

**Comment by JohnRanger** [comment]
Or - if the date has to be visible to the user at creating the record, fetch it via service from the server-side.

Regards,

John
