### ISSUE TITLE
How to make posgresql accept pascal case via c# code?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4933]
I have the following code for concatenating postgresql
`[Expression("CONCAT(CONCAT(FirstName, '-'), LastName)")]`
The column names `FirstName` and `LastName` but when I run the above code, it is giving error that `firstname` does not exist. Apparently the posgresql does not like pascal case `FirstName` and changes to lower case. Now how can I write the code to make postgresql accept pascal case `FirstName` .

**Comment by JohnRanger** [comment]
Hi @ms4hafiz .

maybe this SO question/answer could help you: https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

With kind regards,

John

**Comment by ms4hafiz** [comment]
@JohnRanger 
Yes that is what it should work when directly working with a DBMS editor but 
I am stacked with this line of code C# code 
[Expression("CONCAT(CONCAT(FirstName, '-'), LastName)")]
public string fullname
{
}

**Comment by JohnRanger** [comment]
Hi @ms4hafiz ,

this would make up a nice little Wiki article. Would you mind to put it within the wiki - and then close this issue here? :-)

With kind regards,

John
