### ISSUE TITLE
MultipleFileUploadEditor not able to upload file on host server

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#4934]
Hi,

I install aplication on windows server host , but MultipleFileUploadEditor not able to upload file. I get file, but cannot  be attached in form.
When I manualy add to nvrachar max filed in DB, it show attach file in form.
On my computer everything work ok.

Please help .

**Comment by Surenthiran** [comment]
Check upload folder has write file permission

**Comment by Nikola7i** [comment]
Hi, do you mean folder where picture is ?

**Comment by Nikola7i** [comment]
Yes, the problem is folder read write perm... 
Tnx
