### ISSUE TITLE
sequence/serial no in grid for each row (visual only), always starting from 1

### ISSUE THREAD

**Issue by sispk6** [volkanceylan/Serenity#4935]
I want to add new column to mygrid.ts at position 0, and assign a row number(incremental) to it.

**Comment by arifsamitekinkaya** [comment]
> a row number(incremental)

 should be your table's identity number (auto incremental), and you can put identity column at 1st position in your "mygridcolumns.cs"
Also you can put a column at any position in your grid columns, 
check it out:  https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/InlineActionButtons/InlineActionGrid.ts

**Comment by sispk6** [comment]
Thanks For your reply. 
i dont want a database field. just a new column that  give the serial no to all the records. always starting from 1 and so on. (call it sequence no/serial no  for each row in the grid) ,

**Comment by JohnRanger** [comment]
Hi @sispk6 ,

How has this "visual only sequence number" to behave when the records are resorted? Keeping the initial value or again the most top line starting with 1 and ascending to the most bottom one?

**Comment by sispk6** [comment]
@JohnRanger  
again the most top line starting with 1 .
actually trying to implement this code now

Add to grid.ts, as it is
```
 public class RowIndexFormatter : ISlickFormatter
    {
        public string Format(SlickFormatterContext ctx)
        {
            return (ctx.Row + 1).ToString();
        }
    }

```
column.cs
```
[RowIndexFormatter, EditLink]
public int RowIndex { get; set; }
```
ISlickFormatter is unidentified in grid.ts

**Comment by sispk6** [comment]
@JohnRanger This should be pretty simple since a common requirement of Grid. but i have not been able to do it. Above example was the only clue i got in forum. still struggling.

**Comment by sispk6** [comment]
Im still stuck in this.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Grids/ViewWithoutID/ViewWithoutIDGrid.ts
