### ISSUE TITLE
How to pass vaue from one tab to another tab

### ISSUE THREAD

**Issue by djabeeryusuf** [volkanceylan/Serenity#4936]
There is an example in BasicSamples->Dialogs->OtherFormInTab-> at line#26, thre is snippet below

 // this is just a helper to access editors if needed
`this.customerForm = new Northwind.CustomerForm((this.customerPropertyGrid as any).idPrefix);`

but if i set  
`this.customerForm.CompanyName.value = "hello";`
 in line #98( this.form.CustomerID.change() method)

it throws below error "searching for widget of type 'Serenity.StringEditor' on a non-existent element! ()"

How can i set public variable of any editor in second tab's form  from main tab

**Comment by JohnRanger** [comment]
Hi @djabeeryusuf ,

if I understand the situation correct, the two tabs are within the same dialog. Just add a property within your xyzDialog - like this:

```ts
private CompanyName: string;
```

Then within the onChange event of the first field, copy the value from the updated field to the above property (this.CompanyName = this.form.<your field>.value; ).

And in the focus() event of the 2nd tab, you retrieve the value from this.CompanyName and store it within this.form.CompanyName.value).

Makes sense?

With kind regards,

John

**Comment by djabeeryusuf** [comment]
Hi Jhon
Thanks for the comment.
It was due to improper id field in the example, it wasn't referencing to actual form from DOM.

I have changed this line to
`this.customerForm = new Northwind.CustomerForm((this.customerPropertyGrid as any).idPrefix);`
to
`this.customerForm = new Northwind.CustomerForm(this.idPrefix + "CustomerForm");`

started working

Thanks
