### ISSUE TITLE
Serenity in VS2019 - HTTP Error 500.31 - ANCM Failed to Find Native Dependencies

### ISSUE THREAD

**Issue by eclipzd** [volkanceylan/Serenity#4937]
I downloaded the latest Serenity for ASP.NET CORE.  Compile and get the following:
HTTP Error 500.31 - ANCM Failed to Find Native Dependencies.  Complaining that The framework 'Microsoft.NETCore.App', version '2.2.0' was not found - yet I have installed 2.2.0. Please advise how to get around this?  Thanks

**Comment by volkanceylan** [comment]
Do you have. NET sdk 2.2 installed?

**Comment by eclipzd** [comment]
Yes.  I  the following installed

Microsoft.AspNetCore.App (2.2.0)
Microsoft.NetCore.App (2.2.0)


[cid:image001.png@01D6083E.1DD940A0]

**Comment by volkanceylan** [comment]
SDK is not nuget packages

https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by volkanceylan** [comment]
Especially hosting bundle

**Comment by eclipzd** [comment]
Hi,

I have been running Serenity Framework (ASP.NET Core 2.2) for a while now – but just installed the latest Serenity ASP.NET Core (3.1) application from the latest Project Template through VS2019, and then tried to run it – but am getting the following screen.  Would you know what may be causing this issue?

[cid:image002.png@01D64A37.E08AD560]

Thanks

From: Timothy B
Sent: Wednesday, 1 April 2020 3:57 PM
To: volkanceylan/Serenity <reply@reply.github.com>; volkanceylan/Serenity <Serenity@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [volkanceylan/Serenity] Serenity in VS2019 - HTTP Error 500.31 - ANCM Failed to Find Native Dependencies (#4937)

Yes.  I  the following installed

Microsoft.AspNetCore.App (2.2.0)
Microsoft.NetCore.App (2.2.0)


[cid:image003.png@01D64A37.E08AD560]
