### ISSUE TITLE
I am failing to apply casecade editor. Urgent help needed

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4938]
I have the following code in serenity MVC 5 which works without any issue

        [LookupEditor(typeof(Entities.ProvinceRow)),DisplayName("Province")]
        public Int16 ProvinceId { get; set; }
        [LookupEditor(typeof(Entities.DistrictRow), CascadeFrom = "ProvinceId", CascadeField = "ProvinceId")]
        public Int32 DistrictId { get; set; }

but I have a similar one with .Netcore which is not working. I am stacked. I tried different options and searched the issues here but could not find any solution. Is it changed or I am making problem.

        [LookupEditor(typeof(Entities.ProvincesRow))]
        public Int32 ProvinceId { get; set; }
        [LookupEditor(typeof(Entities.DistrictsRow), CascadeFrom = "ProvinceId", CascadeField = "ProvinceId")]
        public Int32 DistrictId { get; set; }

**Comment by minhhungit** [comment]
any error information pls

**Comment by ms4hafiz** [comment]
It is not giving any error. It is really weird.

I am sharing you the row details for all three entities if you can spot the error

1. Provinces
    [ConnectionKey("Default"), Module("Masters"), TableName("[dbo].[Provinces]")]
    [DisplayName("Provinces"), InstanceName("Provinces")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [LookupScript("Masters.Provinces")]
    public sealed class ProvincesRow : Row, IIdRow, INameRow
    {
        [DisplayName("Province Id"), Identity]
        public Int32? ProvinceId
        {
            get { return Fields.ProvinceId[this]; }
            set { Fields.ProvinceId[this] = value; }
        }

        [DisplayName("Province Code"), Size(2), QuickSearch]
        public String ProvinceCode
        {
            get { return Fields.ProvinceCode[this]; }
            set { Fields.ProvinceCode[this] = value; }
        }

        [DisplayName("Province Name"), Size(50)]
        public String ProvinceName
        {
            get { return Fields.ProvinceName[this]; }
            set { Fields.ProvinceName[this] = value; }
        }

        [DisplayName("Province Namelocal"), Size(50)]
        public String ProvinceNamelocal
        {
            get { return Fields.ProvinceNamelocal[this]; }
            set { Fields.ProvinceNamelocal[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.ProvinceId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.ProvinceCode; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public ProvincesRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field ProvinceId;
            public StringField ProvinceCode;
            public StringField ProvinceName;
            public StringField ProvinceNamelocal;
        }
    }

2. Districts

    [ConnectionKey("Default"), Module("Masters"), TableName("[dbo].[Districts]")]
    [DisplayName("Districts"), InstanceName("Districts")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [LookupScript("Masters.Districts")]
    public sealed class DistrictsRow : Row, IIdRow, INameRow
    {
        [DisplayName("District Id"), Identity]
        public Int32? DistrictId
        {
            get { return Fields.DistrictId[this]; }
            set { Fields.DistrictId[this] = value; }
        }

        [DisplayName("District Code"), Size(4), QuickSearch]
        public String DistrictCode
        {
            get { return Fields.DistrictCode[this]; }
            set { Fields.DistrictCode[this] = value; }
        }

        [DisplayName("Province"), ForeignKey("[dbo].[Provinces]", "ProvinceId"), LeftJoin("jProvince")]
        public Int32? ProvinceId
        {
            get { return Fields.ProvinceId[this]; }
            set { Fields.ProvinceId[this] = value; }
        }

        [DisplayName("District Name"), Size(50)]
        public String DistrictName
        {
            get { return Fields.DistrictName[this]; }
            set { Fields.DistrictName[this] = value; }
        }

        [DisplayName("District Namelocal"), Size(50)]
        public String DistrictNamelocal
        {
            get { return Fields.DistrictNamelocal[this]; }
            set { Fields.DistrictNamelocal[this] = value; }
        }

        [DisplayName("Province Province Code"), Expression("jProvince.[ProvinceCode]")]
        public String ProvinceProvinceCode
        {
            get { return Fields.ProvinceProvinceCode[this]; }
            set { Fields.ProvinceProvinceCode[this] = value; }
        }

        [DisplayName("Province Province Name"), Expression("jProvince.[ProvinceName]")]
        public String ProvinceProvinceName
        {
            get { return Fields.ProvinceProvinceName[this]; }
            set { Fields.ProvinceProvinceName[this] = value; }
        }

        [DisplayName("Province Province Namelocal"), Expression("jProvince.[ProvinceNamelocal]")]
        public String ProvinceProvinceNamelocal
        {
            get { return Fields.ProvinceProvinceNamelocal[this]; }
            set { Fields.ProvinceProvinceNamelocal[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.DistrictId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.DistrictCode; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public DistrictsRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field DistrictId;
            public StringField DistrictCode;
            public Int32Field ProvinceId;
            public StringField DistrictName;
            public StringField DistrictNamelocal;

            public StringField ProvinceProvinceCode;
            public StringField ProvinceProvinceName;
            public StringField ProvinceProvinceNamelocal;
        }
    }

3. Nahiyas

    public sealed class NahiyasRow : Row, IIdRow, INameRow
    {
        [DisplayName("Nahiya Id"), Identity]
        public Int32? NahiyaId
        {
            get { return Fields.NahiyaId[this]; }
            set { Fields.NahiyaId[this] = value; }
        }

        [DisplayName("District"), ForeignKey("[dbo].[Districts]", "DistrictId"), LeftJoin("jDist")]
        public Int32? DistrictId
        {
            get { return Fields.DistrictId[this]; }
            set { Fields.DistrictId[this] = value; }
        }

        [DisplayName("Nahiya Name"), Size(255), QuickSearch]
        public String NahiyaName
        {
            get { return Fields.NahiyaName[this]; }
            set { Fields.NahiyaName[this] = value; }
        }

        [DisplayName("Nahiya Namelocal"), Size(255)]
        public String NahiyaNamelocal
        {
            get { return Fields.NahiyaNamelocal[this]; }
            set { Fields.NahiyaNamelocal[this] = value; }
        }

        [DisplayName("Nahiya Number")]
        public Int32? NahiyaNumber
        {
            get { return Fields.NahiyaNumber[this]; }
            set { Fields.NahiyaNumber[this] = value; }
        }

        [DisplayName("District District Code"), Expression("jDist.[DistrictCode]")]
        public String DistrictDistrictCode
        {
            get { return Fields.DistrictDistrictCode[this]; }
            set { Fields.DistrictDistrictCode[this] = value; }
        }

        [DisplayName("Province"), Expression("jDist.[ProvinceId]"), ForeignKey("dbo.Provinces", "ProvinceId"),LookupInclude, LeftJoin("r"), QuickSearch]
        public Int32? PProvinceId
        {
            get { return Fields.PProvinceId[this]; }
            set { Fields.PProvinceId[this] = value; }
        }

        [DisplayName("District District Name"), Expression("jDist.[DistrictName]")]
        public String DistrictDistrictName
        {
            get { return Fields.DistrictDistrictName[this]; }
            set { Fields.DistrictDistrictName[this] = value; }
        }

        [DisplayName("District District Namelocal"), Expression("jDist.[DistrictNamelocal]")]
        public String DistrictDistrictNamelocal
        {
            get { return Fields.DistrictDistrictNamelocal[this]; }
            set { Fields.DistrictDistrictNamelocal[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.NahiyaId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.NahiyaName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public NahiyasRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field NahiyaId;
            public Int32Field DistrictId;
            public StringField NahiyaName;
            public StringField NahiyaNamelocal;
            public Int32Field NahiyaNumber;

            public StringField DistrictDistrictCode;
            public Int32Field PProvinceId;
            public StringField DistrictDistrictName;
            public StringField DistrictDistrictNamelocal;
        }
    }

**Comment by minhhungit** [comment]
On your NahiyasRow.cs
try this:

```csharp
[DisplayName("District"), ForeignKey("[dbo].[Districts]", "DistrictId"), LeftJoin("jDist")]
[LookupEditor(typeof(DistrictRow), CascadeFrom = "ProvinceId", CascadeField = "PProvinceId")]
public Int32? DistrictId
{
     get { return Fields.DistrictId[this]; }
     set { Fields.DistrictId[this] = value; }
}
```

**Comment by ms4hafiz** [comment]
@minhhungit 

I had missed to include one thing `LookupInclude` in the following line in DistrictsRow.cs

    [DisplayName("Province"), ForeignKey("[dbo].[Provinces]", "ProvinceId"), LeftJoin("jProvince")]
    public Int32? ProvinceId
    {
        get { return Fields.ProvinceId[this]; }
        set { Fields.ProvinceId[this] = value; }
    }
