### ISSUE TITLE
MultiTenancyLookup error

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#494]
I have followed the MultiTenancy sample to adopt to my needs (multiple departments). I created MultiDepartmentRowLookupScript class and removed LookupScript attribute from DepartmentRow class. I created DepartmentLookup which extends MultiDepartmentRowLookupScript. 

using LCBudgets.Administration;
using Serenity;
using Serenity.Data;
using Serenity.Web;
using System;
using System.Linq;

namespace LCBudgets.Modules.LCBudgets.Department
{
    public abstract class MultiDepartmentRowLookupScript<TRow> :
        RowLookupScript<TRow>
        where TRow : Row, IMultiDepartmentRow, new()
    {
        public MultiDepartmentRowLookupScript()
        {
            Expiration = TimeSpan.FromDays(-1);
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            AddDepartmentFilter(query);
        }

        protected void AddDepartmentFilter(SqlQuery query)
        {
            var user = (UserDefinition)Authorization.UserDefinition;
            var r = new TRow();
            query.Where(new Criteria("T0.dept_nbr").In(user.Departments));
        }

        public override string GetScript()
        {
            return TwoLevelCache.GetLocalStoreOnly("MultiDepartmentLookup:" +
                    this.ScriptName + ":" +
                    ((UserDefinition)Authorization.UserDefinition).DeptNbr,
                    TimeSpan.FromHours(1),
                new TRow().GetFields().GenerationKey, () =>
                {
                    return base.GetScript();
                });
        }
    }
}

namespace LCBudgets.Modules.LCBudgets.Department
{
    using global::LCBudgets.LCBudgets.Entities;
    using Serenity.ComponentModel;
    using Serenity.Web;

    [LookupScript("LCBudgets.Department")]
    public class DepartmentLookup : MultiDepartmentRowLookupScript<DepartmentRow>
    {
        public DepartmentLookup()
        {
            IdField = DepartmentRow.Fields.Nbr.PropertyName;
            TextField = DepartmentRow.Fields.Name.PropertyName;
        }
    }
}

In the UserRow, I have the following code to associate user with 1 or more departments:

        [DisplayName("Department(s)"), LookupEditor("LCBudgets.Department", Multiple = true), ClientSide]
        [LinkingSetRelation(typeof(UserDepartmentsRow), "UserId", "DeptNbr")]
        public List<String> Departments
        {
            get { return Fields.Departments[this]; }
            set { Fields.Departments[this] = value; }
        }

In other classes, I have the following code to lookup the department:

        [DisplayName("Dept Nbr"), Column("dept_nbr"), Size(32), ForeignKey("[dbo].[department]", "dept_nbr"), LeftJoin("jDeptNbr"), QuickSearch, Updatable(true), Insertable(true)]
        [LookupEditor("LCBudgets.Department")]
        public String DeptNbr
        {
            get { return Fields.DeptNbr[this]; }
            set { Fields.DeptNbr[this] = value; }
        }

I get the following error when opening a form with DepartmentLookup defined (certain users only):

> uncaught exception: Can't load script data: Lookup.LCBudgets.Department!

I suspect this has something to do with the way the script is cached but I don't yet know enough to figure it out. Many thanks in advance for any pointers.

**Comment by volkanceylan** [comment]
Lookup scripts use the permission on row by default. Your Department row probably has read permission. Either make it relaxed or 

[LookupScript("LCBudgets.Department", Permission: "?")]

for all logged users, 

[LookupScript("LCBudgets.Department", Permission: "*")]

for any users

**Comment by volkanceylan** [comment]
Also your namespaces are a bit strange:

namespace LCBudgets.Modules.LCBudgets.Department

There is possibility that this might cause you trouble later.

Use SolutionName.ModuleName syntax

**Comment by c9482** [comment]
Hi Volkan,

It appears you were right about the namespaces - that fixed my problem. I am still getting used to C# namespaces. These are equivalent to Java packages which are simple - they must mirror the folder structure the file is in. Thanks again.
