### ISSUE TITLE
Multi Selecting 

### ISSUE THREAD

**Issue by Asp1993** [volkanceylan/Serenity#4940]
Hello
I need some help to auto populate DIALOG based on drop down selection
Here is the structure of my Tables:
1. Classes: ClassID, Name,TearcherID
2. Teachers: TearcherID, Name 
3. Students: StudentID, Name
3. TeacherStudent (a relational table): TeacherStudentID, TeacherID,StudentID

Each Class has one Teacher.
Each Teacher has multiple Students

What I want is, when a new Class is created , if a user select a particular Teacher from drop down (single selection), all of its students should automatically be set in the FORM so that user does not have to select each student from drop down (multi select). 

How can I achieve this?

**Comment by ms4hafiz** [comment]
This may help in some way
https://serenity.is/demo/AdvancedSamples/ProductPicker#

**Comment by dhaka1993** [comment]
@ms4hafiz Thank you friend, I went through this sample but it is not what I am looking for.

**Comment by Asp1993** [comment]
Closing this due to no response/solution to this problem.
