### ISSUE TITLE
getLookup() method returns undefined

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4942]
Hi, 
The code below in typescript keeps returning the error undefined. Is there a problem the getLookup() method in serenity? I have seen code samples of it being used but when I use it, my returned object and properties show "Undeined" error.

`var pendingReq = AllRequisitions.PendingRequisitionRow.getLookup().items.filter(x => x.SiteId === user.SiteId).sort((a, b) => (a > b ? -1 : 1))[0];`

**Comment by minhhungit** [comment]
Do you have [LookupScripts] on your row.cs

**Comment by gfo2007** [comment]
@minhhungit yes I do.

**Comment by minhhungit** [comment]
Can you take a screenshot or push your code of the Row class

If you have the attribute on top of Row, I think it should work

try to change it with something like this

 >[LookupScripts("helloworld")]

build solution, test it by this way

run project, F12 on browser > Console > and type: **Q.getLookup("helloworld")** , like this

![image](https://user-images.githubusercontent.com/2279508/78247324-e8938880-7514-11ea-9b48-1d91d3f6eb83.png)

**Comment by gfo2007** [comment]
@minhhungit please find below the error I get

```
 [ConnectionKey("Default"), Module("AllRequisitions"), TableName("[dbo].[Requisitions]")]
    [DisplayName("Pending Requisition"), InstanceName("Pending Requisition")]
    [ReadPermission(AllRequisitions.PermissionKeys.PendingRequisition.View)]
    [InsertPermission(AllRequisitions.PermissionKeys.PendingRequisition.Add)]
    [UpdatePermission(AllRequisitions.PermissionKeys.PendingRequisition.Edit)]
    [DeletePermission(AllRequisitions.PermissionKeys.PendingRequisition.Delete)]
    [LookupScript("Hello World")]
```


![getlookup error](https://user-images.githubusercontent.com/14317420/78253456-f0870480-74e3-11ea-8832-093fa0987e39.PNG)

**Comment by minhhungit** [comment]
remove space please [LookupScript("HelloWorld")]

![image](https://user-images.githubusercontent.com/2279508/78259448-ec300b00-7526-11ea-9fe5-7973ab6ac02f.png)

**Comment by gfo2007** [comment]
@minhhungit thanks for your help so far. I am realizing why I am getting the undefined error. My filter seems not to be working. SiteId is a foreign key in the Requisions table so in the code snippet, I am using the user's SiteId (17) to match the SiteId in the Requisitions table (also 17) to retrieve the record but the filtering doesn't seem to find a match, hence the error.

```
var pendingReq = AllRequisitions.PendingRequisitionRow.getLookup().items.filter(x => x.SiteId === user.SiteId).sort((a, b) => (a > b ? -1 : 1))[0];
```

Below are the images of the SiteId in both the User's Table and Requisitions Table

![users site id](https://user-images.githubusercontent.com/14317420/78336847-93d92780-757f-11ea-86de-83c54c4d9947.PNG)


![requisition site id](https://user-images.githubusercontent.com/14317420/78336881-9dfb2600-757f-11ea-853f-a6631960b95f.PNG)

**Comment by minhhungit** [comment]
Default Serenity just uses 2 fields for lookup data, they are **Id** and **Name** in your row, if you need other fields you need to add [**LookupInclude**] attribute

**Comment by gfo2007** [comment]
@minhhungit thank you so much. It's working after adding LookupInclude attribute to the SiteId foreign key.

**Comment by minhhungit** [comment]
@gfo2007  If it worked pls close this issue
