### ISSUE TITLE
How to dynamically calculate the size of dialog panels

### ISSUE THREAD

**Issue by MimmoDany** [volkanceylan/Serenity#4943]
How do I go about dynamically calculating dialog sizes when viewed in pannel mode.
I tried to insert the dimensions in the css. But when you change resolution or zoom in it doesn't scale down.
A function like: Q.initFullHeightGridPage () would be needed, but I don't know how.

an idea of how to do it? or is there already a system that I don't know yet?

Thank you all

<img width="749" alt="griglia" src="https://user-images.githubusercontent.com/35045921/78239419-f7127d80-74dd-11ea-9b0d-20e07e174c1d.png">

<img width="749" alt="dialog" src="https://user-images.githubusercontent.com/35045921/78239543-1ad5c380-74de-11ea-9568-384163d4cd23.png">

<img width="1128" alt="css" src="https://user-images.githubusercontent.com/35045921/78239554-1f9a7780-74de-11ea-9943-e0bf3efb19ee.png">

**Comment by welcometoall** [comment]
Add responsive decorator in Dialog.ts file.
`@Serenity.Decorators.responsive()`

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
