### ISSUE TITLE
Multiple whitespaces within a string value

### ISSUE THREAD

**Issue by axMAS** [volkanceylan/Serenity#4944]
Hi,

it seems to be that Serenity removes multiple whitespaces within a string value.
For example:
Value in the database field: "ADA       7011" (seven whitespaces between ADA and 7011!)
How it looks in Serenity:
Grid:
![grafik](https://user-images.githubusercontent.com/54072926/78364023-146a4900-75bd-11ea-994c-3c393d45fa0b.png)
and
LookupEditor:
![grafik](https://user-images.githubusercontent.com/54072926/78364063-24822880-75bd-11ea-899c-d1025824b47b.png)

Only the grid and the LookupEditor are affected.
Without the LookupEditor the value is showing correctly.
![grafik](https://user-images.githubusercontent.com/54072926/78364157-4aa7c880-75bd-11ea-9898-f065e286a11c.png)

But, the value is saved correctly in the database (with seven whitespaces) after update the item.

Can the behaviour be changed, because it irritates the user?

Thank you!

Regards
axMAS

**Comment by volkanceylan** [comment]
Serenity does not do anything to cause that
