### ISSUE TITLE
Bug: Brand new Serene .net core demo project from visual Studio marketplace; missing most of what has to go within wwwroot directory

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4946]
Hi @volkanceylan 

multiple people - including myself - have the problem that the most current serene .net core project - when deploying it via Visual Studio Marketplace template - simply does not work out-of-the-box (it gives instantly 45x 404 not found errors after hitting the 1st time on F5) and the login screen is only displayed as a small grey centered rectangle).

I investigated the problem, by creating a fresh VirtualBox VM with newest fully patched Win10, installing the prerequisites like .NET core 2.2.x SDK, newest NodeJS and newest stable Typescript and of course Visual Studio 2019 Community Edition with the ASP.NET workload..

The problem still occurs under above optimal conditions - So it has nothing to do with my setup.

The root cause of the problem is that about 80-90% of what has to go into the ./wwwroot directory (e.g. Content, fonts, Scripts) are mostly missing (although ./content/ exists, its subfolders and files are mostly missing. ./fonts/ does not exist at all and ./scripts/ is missing most of its content).

The solution for me was to also create a .NET full framework project and copy over the directories **Content**, **fonts** and **Scripts** into the .NET core project - and **not** overwriting existing files.

After that, it immediately worked.

Interestingly - if I look at the current Serene core project on Github, the missing resources under wwwroot are present. So there must be something wrong with the vs marketplace template for .NET core.

When looking at the user extensions folder ```C:\Users\Papa\AppData\Local\Microsoft\VisualStudio\<version>\Extensions\<random foldername>\ProjectTemplates\SereneCore.Template\Serene.Core\wwwroot ```, it is clear that the wwwroot folder within the serene core template is incomplete:

![image](https://user-images.githubusercontent.com/2699447/78422840-a4160300-7662-11ea-8e46-dda226d04c0e.png)

I recommend to fix this problem.

With kind regards,

John

**Comment by petebr** [comment]
I've the same issue. New project from vs2019 produces project with many missing scripts/css and wont run. New project from vs2017 still works ok.

**Comment by minhhungit** [comment]
@petebr I think you might need to restore project using commands:

>dotnet restore
>dotnet sergen restore

**Comment by petebr** [comment]
thanks @minhhungit 
Interesting, I just tried a new project on vs2019 (and unticked all options) in order to try your suggestion and it worked right away. Then tried again with theme samples, again it worked.
Can't explain what might have gone wrong yesterday but seem fine now.

**Comment by minhhungit** [comment]
this is reason

![image](https://user-images.githubusercontent.com/2279508/81921239-7e3a3180-9604-11ea-85cc-c1c65faf2e6e.png)

Ref: https://serenity.is/docs/startsharp/updating-startsharp

**Comment by JohnRanger** [comment]
@minhhungit ,

thank you for the clear explanation.

I will therefore close this issue.

Regards,

John

**Comment by cg3y** [comment]
You need to then include the missing step ("dotnet sergen restore") in the documentation here (https://serenity.is/Docs/getting_started/instaling-serene-aspnet-core-version-with-serin) as this critical step is missing. Update the documentation and all is good as that step was the missing piece.  As a new user I almost gave up on evaluating this since it didn't work following the instructions.
