### ISSUE TITLE
ESLint/TSlint issue after update

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#4949]
Yesterday i updated visual studio to (16.5.2)

after that, it started giving green warnings for all typescripts.

![image](https://user-images.githubusercontent.com/59920049/78471818-17904100-7745-11ea-92b4-9869a1e7c869.png)

i tried by adding below line to tslint.json, but no success
```

{
  "rules": {
    "no-namespace": false
  }
}
```

can any one help me what's going wrong?

**Comment by edwardch** [comment]
I disabled mine in Tools>Options
![image](https://user-images.githubusercontent.com/4890069/78558081-4a543b00-7812-11ea-8e4e-f35a399759f7.png)

It was lazy but maybe there is something we need to be addressing instead.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
