### ISSUE TITLE
mscorlib.dll

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#495]
Don't let the reference

**Comment by Thebenmandude** [comment]
What do you mean by "Don't let the reference"?

**Comment by 107295472** [comment]
yes

**Comment by 107295472** [comment]
System generation, do not let the reference

**Comment by VictorTomaili** [comment]
its an issue about visual studio. Saltarelle project doesnt need microsofts mscorlib. When you create new class, visual studo add own mscorlib reference too. And its break project. You need remove mscorlib reference and use copy paste on solution explorer when create new class file. 

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Dev.Serene.Script.csproj#L431

**Comment by 107295472** [comment]
Indirectly referenced assembly System.Security must be referenced.	Serenity.Script.Imports

**Comment by Thebenmandude** [comment]
Thanks for the replies. Sorry if I sound rude, I am having trouble understanding (I assume English is not your first language).
I cannot remove the mscorlib reference as it causes other errors. I had a look at the link Victor sent and my project file is exactly as the example. Serenity.Script.Imports are already referenced in my Script project.

**Comment by 107295472** [comment]
![qq 20160401171329](https://cloud.githubusercontent.com/assets/6436116/14202870/16662fc4-f82d-11e5-9753-ac47502a305c.png)

**Comment by 107295472** [comment]
mscorlib.dll  Its problems

**Comment by 107295472** [comment]
@VictorTomaili   According to what you said, but not yet.

**Comment by 107295472** [comment]
@VictorTomaili   Reference,But there is this error [https://cloud.githubusercontent.com/assets/6436116/14202870/16662fc4-f82d-11e5-9753-ac47502a305c.png](url)

**Comment by volkanceylan** [comment]
Don't remove mscorlib, remote System.dll reference and other similar. This is stated in guide troubleshooting.

**Comment by 107295472** [comment]
You don't report me, I just love to talk.

**Comment by volkanceylan** [comment]
:scream: I see
