### ISSUE TITLE
How to refresh grid after saving record

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#4950]
Hi,
The code below sets a default value of a field when the "New Button" on top of the grid is clicked. After saving the record, and clicking the new button again, the default value must increase by 1. But because the grid is not being refreshed after saving, when you click on the new button, the default value stays the same. From the image, you will realize that even though OBU1 has been saved already, because I didn't go to the main menu on the left to refresh the page, the dialog is still showing OBU1 when it should have changed to OBU2.

How do I refresh the grid so that when I call the getLookup() method in the "New Button" click, the default value of the field will increase by 1? Please help.

**PendingRequisitionGrid.ts**
```
 /**
         * This method is called when New Item button is clicked.
         * By default, it calls EditItem with an empty entity.
         * This is a good place to fill in default values for New Item button.
         */
        protected addButtonClick() {

            var user = Q.Authorization.userDefinition as ScriptUserDefinition;
            //var currentUserInfo = Administration.UserRow.getLookup().itemById[user.Username];
            var pendingReq = AllRequisitions.PendingRequisitionRow.getLookup().items.filter(x => x.SiteId === user.SiteId).reverse()[0];

            var newReqNo = "";
            var newNo = 0;
            if (pendingReq != null) {
                var lastNo = +(pendingReq.RequisitionNo.substring(3));
                newNo = lastNo + 1;
                newReqNo = pendingReq.RequisitionNo.substring(0, 3) + newNo;
               
                this.editItem(<AllRequisitions.PendingRequisitionRow>{
                    RequisitionNo: newReqNo
                });           
            }
            else {
               
                LookUps.SiteService.Retrieve({
                    EntityId: user.SiteId
                }, response => {
                        this.editItem(<AllRequisitions.PendingRequisitionRow>{
                            RequisitionNo: response.Entity.SiteCode + 1
                        });
                });
                //Serenity.SubDialogHelper.triggerDataChange(this);
            }  
        }

        protected getButtons() {
            // preserving default New Item button
            var buttons = super.getButtons();
            return buttons;
        }
```

![pending requisition problem](https://user-images.githubusercontent.com/14317420/78547398-91303980-77ee-11ea-9b57-34785bd33ba0.PNG)

**Comment by KishanVaishnani** [comment]
@gfo2007 Did you have a used inside response of service call?

this.view.refresh();

**Comment by gfo2007** [comment]
@KishanVaishnani thnks for the response. But the code is not working inside the service call.

**Comment by KishanVaishnani** [comment]
@gfo2007 Can you make another function and put the line inside, and call that function from service response

**Comment by JohnRanger** [comment]
@gfo2007 ,

please see my comments on your new issue which you just have opened 3h ago.

With kind regards,

John
