### ISSUE TITLE
Showing Data

### ISSUE THREAD

**Issue by dekzao** [volkanceylan/Serenity#4951]
I have a main table that has an id to a person's table, in that person's table i have another foreign key leading to another table. How can i show in my main table page the third table data i need? so far i only got to the second table foreign key

**Comment by edwardch** [comment]
Can you try something like this on your xyzRow.cs
```cs
[DisplayName("First Relationship ID"), ForeignKey(typeof(FirstRelationshipRow)), LeftJoin("jFirstRelationship")]
public Int32? FirstRelationshipId
{
    get { return Fields.FirstRelationshipId[this]; }
    set { Fields.FirstRelationshipId[this] = value; }
}

// We can use an expression here
[DisplayName("Second Relationship ID"), ForeignKey(typeof(SecondRelationshipRow)), LeftJoin("jSecondRelationship")]
[Expression("jFirstRelationship.[SecondRelationshipId]")]
public Int32? SecondRelationshipId
{
    get { return Fields.SecondRelationshipId[this]; }
    set { Fields.SecondRelationshipId[this] = value; }
}

// Or set the "origin" of the field
// Note that with "Origin" the column name needs to match the property name
// e.g if the column on SecondRelationship table was called "Name", then
// you would just have this as:
// public string Name
[DisplayName("Second Relationship Name")]
[Origin("jSecondRelationship")]
public String SecondRelationshipName
{
    get { return Fields.SecondRelationshipName[this]; }
    set { Fields.SecondRelationshipName[this] = value; }
}
```

This assumes your main table is called something like `xyz` which has a FK to `FirstRelationship` table, which has a FK to `SecondRelationship` table.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
