### ISSUE TITLE
how to show confirmation on logout

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#4952]
I want to show confirmation message before logout ?
If user click Yes button serenity will logout otherwise stay logged in .
How can i do this?

**Comment by KishanVaishnani** [comment]
@teafmartins please refer link https://serenity.is/demo/BasicSamples/DialogBoxes

let me know if any help needed

**Comment by teafmartins** [comment]
That's it, didn't remeber that demo. :) thx
