### ISSUE TITLE
Cannot add test project

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#4953]
I tried creating very simple test project for my Serene Project
But it gives error stating 
**System.InvalidOperationException : 
This method cannot be called during the applications pre-start initialization phase.** when invoking **Serenity.Web.CommonInitialization.Run() **, without Serenity.Web.CommonInitialization.Run() it says connection string not found
```

[TestMethod]
        public void TestF()
        {

          Serenity.Web.CommonInitialization.Run();
            var crepo = new CurrenciesRepository();

            var crow = new CurrenciesRow { CurrenyCode = "USD", ExchangeRate = 1.000m, CurrenyDescription = "US Dollar" };

            var request = new SaveRequest<CurrenciesRow>();
            request.Entity = crow;

            using (var connection = SqlConnections.NewByKey("Default")
            using (var uow = new UnitOfWork(connection))
            {
                crepo.Create(uow, request);
                uow.Commit();
            }


            int i = 10;
            Assert.AreEqual(i, 10);
        }
```

**Comment by volkanceylan** [comment]
See https://github.com/volkanceylan/Serenity/blob/master/Serenity.Test/Services/MasterDetailRelationBehavior/MasterDetailRelationBehaviorTests.Int32LoadsDetailsOnRetrieve.cs and other similar tests in Serene/StartSharp

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
