### ISSUE TITLE
Is it possible to define an expression within xyzRow.cs which does an inner join to localization extension table and respects current selected language of user?

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4957]
Hi all,

I am trying to use the localization feature of SF. So far I have managed to be able to define localizations for my desired data and it is stored correctly within the extension table. 

Also I can in general do the inner join of the localization table to the main table - but I am struggling with the following:

- How to define a field within the main table so that the inner join joins only exactly with the localization extension record for the currently selected language of the user and does a fallback to default value in main table when no localization for desired language is available?

**Why do I want that?**

My goal is to have the entity framework output the localization of a specific value /field in the currently selected language of the user when there is a specific localization for that. If there is no localization available in the current language of the user, it should fall back to the value defined within the main table.

P.S: This would also be a great standard feature of SF - in case this is currently not possible.

**Question:** Do I have to overWrite the list service in xyzEndpoint.cs in order to achieve this?

Any help is highly regarded.

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger from your question I am thinking you are desiring to use the Declarative Programming in order to accomplish your end goal. 
I do not currently use language translations as it is not needed for my applications so I am not sure of all the workings however I offer up the following just in case it might be useful to you. 

Given declarative programming is compile time , I am thinking you might need to handle this somewhat like how the LookupEditor filterfield, filtervalue  functions.

**Comment by JohnRanger** [comment]
Hi all, I am closing this issue because I will go down another route to solve this problem. Will ask new questions and then make a wiki.

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 
I know that you are looking for another route , however now that I am more awake and thinking about this ..

Actually innerjoin with criteria could work for your purpose, 
Passing the currentUI Culture set  as a criteria can be as simple as an unmapped field that returns the currentUI culture. Of course this might be server side Culture - so you would need a work around for that - passing in from client side .. I do not see culture in the request object. So in some manner that field would need to be set Entity.UnmappedCultureField = currentculture.

Of course there is also a bad design of using a static dictionary in your web application Dictionary< userId, language>  and you would set this when they logged in or changed the language

You could override the request or response to include the culture info in the request ..


```
        [InnerJoin("jLang","tblLanguage", "T0.Language = T0.CurrentUserCulture")]
        public String CulturedTranslation
        {
            get { return Fields.CulturedTranslation[this]; }
            set { Fields.CulturedTranslation[this] = value; }
        }


        [DisplayName("CurrentUserCulture"), NotMapped, DefaultValue("en-US")]
        public String CurrentUserCulture
        {
            get
            { // Have not tested
                if (Fields.CurrentUserCulture[this] == null)
                {
                    Fields.CurrentUserCulture[this] = System.Globalization.CultureInfo.CurrentUICulture.Name;
                }

                return  Fields.CurrentUserCulture[this];
            }
            set
            {

                if (value == null)
                {
                   value = System.Globalization.CultureInfo.CurrentUICulture.Name;
                }

                Fields.CurrentUserCulture[this] = value;
            }
        }
```
