### ISSUE TITLE
Dropdown with inline button

### ISSUE THREAD

**Issue by nazrulbspi5** [volkanceylan/Serenity#4958]
Hello, I need to implement a dropdown with an inline button in the serenity project.
how to implement?
anyone suggest me, please.

![Screenshot_7](https://user-images.githubusercontent.com/25577964/78889314-42e89800-7a85-11ea-9c46-b0cc1f680117.png)

**Comment by stixoffire** [comment]
There is an example of how to inline button in the issues listing, I think there is an example in the project as well. 
However there is also [Split Button Dropdown in the WIKI](https://github.com/volkanceylan/Serenity/wiki/UI:-SplitButton-dropdowns)

This might give you a start.

**Comment by JohnRanger** [comment]
Hi @nazrulbspi5 ,

as @stixoffire has pointed out - The solution for this is shown within SF demo in Northwind, 

https://serenity.is/demo/Northwind/Product 

Products --> click on one of the products --> See for example the supplier dropdown:

![image](https://user-images.githubusercontent.com/2699447/79023072-b1aa1c00-7b7f-11ea-8a29-548ff1686bbb.png)

Please note that this button dynamically changes from "Create mode" (the star you showed in your screenshot) to the pen when in "edit mode".

If you find a way how to always keep this button in create mode - even when the dialog itself is in edit mode, please let us know :-)

Hope this helps.

With kind regards,

John

**Comment by KishanVaishnani** [comment]
Hey @nazrulbspi5 

You have create custom editor for Serenity.Select2Editor

![image](https://user-images.githubusercontent.com/60768270/79103171-c0641f00-7d89-11ea-87cb-14d4bf55deb8.png)

And in constructor, you have to add html block and insertAfter current element

![image](https://user-images.githubusercontent.com/60768270/79102947-61060f00-7d89-11ea-86ab-259a1ee026d7.png)
 
![image](https://user-images.githubusercontent.com/60768270/79103289-ed183680-7d89-11ea-9d92-0b78b53ad94f.png)

**Comment by stixoffire** [comment]
@KishanVaishnani there is more than one way to do this - a custom editor for it is only required if you intend to use it in multiple locations - which is fine.
you can alos use the inline button example - I think it is in the wiki

Issue #4138 

[Inline Button Example](https://serenity.is/demo/Account/Login?ReturnUrl=%2fdemo%2fAdvancedSamples%2fInputWithInlineButtons#!1)
