### ISSUE TITLE
Focus event and Mask clash???

### ISSUE THREAD

**Issue by Thebenmandude** [volkanceylan/Serenity#496]
Hi, I have an issue where I add a focus trigger on a field to call a javascript function. This works well for all fields except those that have MaskedEditor(). If I remove the MaskedEditor from the myPageRow.cs it works. I need to have both the Mask and my on focus trigger working.
What happens is that the Dialog does not even open. Here's the console output:
![image](https://cloud.githubusercontent.com/assets/6910368/14201693/c84760a8-f7f3-11e5-92e2-326845ff9488.png)

**Comment by 107295472** [comment]
#495 Can you help me look good

**Comment by volkanceylan** [comment]
Transform templates first

**Comment by volkanceylan** [comment]
Reopen if not resolved.
