### ISSUE TITLE
PrepareQuery and ProcessEntity; Joined field in ProcessEntity is null

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4960]
Hi all,

I am currently working on using the localization functionality builtin within serenity framework.

So far, I have successfully managed to create a language extension table and I am able to register localizations for the desired value within the main table.

What I now want to achieve, is, to modify the retrieve- and the listHandler - in order to return either the localizated value (if it exists for the current item in the main table for the current user's language) or the fallback value which is the value stored within the main table.

in real SQL, I have the following - working - query which returns all records from the main table and the localization field from the localization extension table:

```sql
SELECT T0.*, jbooksLang.bookname
FROM books T0 
LEFT JOIN [bookslang] jbooksLang ON (jbooksLang.BookId = T0.BookId and jbooksLang.languageId = 9)
```

Hint : The languageID of the user's current language I retrieve within the prepareQuery method like this:

```cs
   var languageID = CultureInfo.CurrentUICulture.LCID;
```

Hint: Here seems to be a bug in SF (or an understanding problem on my side) when applying an query.leftJoin (actually it happens with every xxxJoin operation I have tested) when the sequence of applying the operations on an SQLquery object is like below:.

I get the error
![image](https://user-images.githubusercontent.com/2699447/78950464-16596e00-7acf-11ea-8c6e-03fdc5af0d89.png)

If it is applied in this sequence it gives above Error:
```sql
                query.Select("T0.*");
                query.Select("jBooksLang.BookName as BookName_Localization");   <<<-- This line is responsible for the error
                query.LeftJoin(aliasBookLang, joinCriteria); <<<-- At this line, the error is thrown
```

If applied in the following sequence, it does not throw any error and passes the SQL query to the DB engine correctly (verified within debug log):

```sql
                query.LeftJoin(aliasBookLang, joinCriteria);
                query.Select("T0.*");
                query.Select("jBooksLang.BookName as BookName_Localization");
```

------------------------

But now I have the problem that within protected override ProcessEntity, the joined field has always value "null" - even when the query itslef returns this value correctly, when I just copy&Paste from debug log into SQL Management studio.

My PrepareQuery looks like this:
```cs
            protected override void PrepareQuery(SqlQuery query)
            {
                var languageID = CultureInfo.CurrentUICulture.LCID; // name

                var aliasBookLang = new Alias("Bookslang", "jBooksLang");
                var joinCriteria = new Criteria("jBooksLang.BookId = T0.BookId and jBooksLang.languageId = " + languageID);

                query.LeftJoin(aliasBookLang, joinCriteria);
                query.Select("T0.*");
                query.Select("jBooksLang.BookName as BookName_Localization");
            }
```

My ProcessEntity method looks like this:

```cs
            protected override MyRow ProcessEntity(MyRow row)
            {
                var currentRow = row;
                currentRow.BookName_Localization = currentRow.BookName_Localization.IsEmptyOrNull() ? currentRow.BookName : currentRow.BookName_Localization;
                return currentRow;
            }
```

How do I make the ListRequestHandler to also fill the joined field when it gives row by row to ProcessEntity method?

Thanks for any help and

with kind regards,

John

**Comment by JohnRanger** [comment]
Update:

the original query - after base.PrepareQuery(query) has run looks like this:

```sql
SELECT T0.[bookId] AS [BookId], T0.[bookName] AS [BookName], T0.[OTNT] AS [Otnt], jBooksLang.[BookName] AS [BookName_Localization] T0.*, jBooksLang.bookname as BookName_Localization
FROM [books] T0 
LEFT JOIN [Bookslang] jBooksLang ON (jBooksLang.[BookId] = T0.[bookId])
```

so I would need just to exchange the join criteria - but if I use the existing query given to the listhandler, when I do a

```cs
var languageID = CultureInfo.CurrentUICulture.LCID; // name
var alias = new Alias("Bookslang", "jBooksLang");
var joinCriteria = new Criteria("jBooksLang.BookId = T0.BookId and jBooksLang.languageId = " + languageID);
query.LeftJoin(alias, joinCriteria);
```

I get the error
![image](https://user-images.githubusercontent.com/2699447/78950464-16596e00-7acf-11ea-8c6e-03fdc5af0d89.png)

Because it seems that th query.LeftJoin method just adds another join criteria instead of replacing it.

How to do this properly?

With kind regards,

John

**Comment by JohnRanger** [comment]
Again next update:

There seems to be a bug in SF (or an understanding problem on my side) when applying an query.leftJoin (actually it happens with every xxxJoin operation I have tested) when the sequence of applying the operations on an SQLquery object is like below:.



If it is applied in this sequence it gives above Error:
```sql
                query.Select("T0.*");
                query.Select("jBooksLang.BookName as BookName_Localization");   <<<-- This line is responsible for the error
                query.LeftJoin(aliasBookLang, joinCriteria); <<<-- At this line, the error is thrown


This way does not throw any error and passes the SQL query to the DB engine correcty:

```sql
                query.LeftJoin(aliasBookLang, joinCriteria);
                query.Select("T0.*");
                query.Select("jBooksLang.BookName as BookName_Localization");
```


------------------------

But now I have the problem that within protected override ProcessEntity, the joined field has always value "null" - even when the query returns this value correctly, when I just copy&Paste from debug log into Management studio.

My ProcessEntity method looks like this:

```cs
            protected override MyRow ProcessEntity(MyRow row)
            {
                var currentRow = row;
                currentRow.BookName_Localization = currentRow.BookName_Localization.IsEmptyOrNull() ? currentRow.BookName : currentRow.BookName_Localization;
                return currentRow;
            }
```

**Comment by minhhungit** [comment]
@JohnRanger your purpose is you want to load data by specific language? 

Try to created 2 new handlers for example CustomRetrieveHandler and CustomListHandler that inherit from RetrieveRequestHandler/ListRequestHandler

Note: You should rename the handles for your case !

**In repository.cs**

```csharp
private class MyRetrieveHandler : CustomRetrieveHandler<MyRow> { }
private class MyListHandler : CustomListHandler<MyRow> { }
```

**CustomRetrieveHandler and CustomListHandler classes:**
```csharp
public class CustomRetrieveHandler<TRow> : RetrieveRequestHandler<TRow> where TRow : Row, new()
{
    protected override SqlQuery CreateQuery()
    {
        // find current language here, something like `Serenity.Authorization.UserId`
        var curLanguage = ....

        return base.CreateQuery().ApplyCurrentLanguageFilter(curLanguage);
    }
}

public class CustomListHandler<TRow> : ListRequestHandler<TRow> where TRow : Row, new()
{
    protected override SqlQuery CreateQuery()
    {
        // find current language here, something like `Serenity.Authorization.UserId`
        var curLanguage = ....

        return base.CreateQuery().ApplyCurrentLanguageFilter(curLanguage);
    }
}
```

**ApplyCurrentLanguageFilter extension method:**
```csharp
public static SqlQuery ApplyCurrentLanguageFilter(this SqlQuery query, string currentLanguageId, string objByLanguageJoinAlias = "bl")
{
    int.TryParse(currentLanguageId, out int id);
    query.EnsureJoinsInExpression(objByLanguageJoinAlias).Where($"{objByLanguageJoinAlias}.LanguageId = {id}");
    return query;
}
```

**Your dbo.BooksLang looks like this:**
```
- Id int,
- LanguageId int,
- BookId int
```

**On Row.cs** (your object you want to apply logic)

```csharp
[ConnectionKey("Default"), Module("Default"), TableName("[dbo].[Books]")]
[InnerJoin("bl", "dbo.BooksLang", "T0.Id = bl.BookId")] // <=============== add this line on head of class
public sealed class BookRow : Row, IIdRow, INameRow
{
    // ...
}
```

---
**Bonus:** In case you want to apply the rule for custom query like custom lookup, remember to apply `ApplyCurrentLanguageFilter` extension method, for example:

```csharp
protected virtual IEnumerable<YourRow> GetItems()
{

    // define your FIELDS
    var x = XyzRow.Fields.As("x");
    var bl = BookLanguageRow.Fields.As("bl");

    var currentLanguageId = ... ;

    using (var connection = SqlConnections.NewFor<YourRow>())
    {
        var query = new SqlQuery()
            .Select(...)
            .Select(...)
            .From(x)
            .InnerJoin(bl, new Criteria(bl.BookId) == new Criteria(x.BookId))
            .ApplyCurrentLanguageFilter(currentLanguageId);   // <==============

        return connection.Query<YourRow>(query);
    }
}
```

Let me know if it work for you

**Comment by JohnRanger** [comment]
Hi @minhhungit ,
wow - thanks for such a detailed reply - I will try this today and will let you know how it went.

Regards,

John

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

it "kind* of works in certain situations (e.g. when there is a localization for a specific entry in the main books table, then it returns a record - but when ther eis no localization for a specific record, it does not) - but what I need is not an inner join - but a left join.

Meaning that no matter if there is a localization or not for a given entry within the main table, the record must be returned - but of course then the localization joined field would be empty.

So if I have 66 records within the main table (books) and for a given localization language I only have 5 localizations for these 66 records, the resultset must still be all 66 records - but only within 5 of these 66 reords the joined localisation field would have a value.

So the records actually must not really be filtered.

How would I do this then?

With kind regards,

John

**Comment by minhhungit** [comment]
then try to use LeftJoin [Expression] with ISNULL() or CASE WHEN, it might work

**Comment by minhhungit** [comment]
change this line to LeftJoin
```csharp
[InnerJoin("bl", "dbo.BooksLang", "T0.Id = bl.BookId")]
```

**Comment by JohnRanger** [comment]
Hi @minhhungit ,
thanks for your feedback.

In the meantime, I also found it out :-). For all others, here the full way how to use a localization 

Basically it works like this: <update follows>

**Comment by JohnRanger** [comment]
Hi all,

with the gracious help of @minhhungit (thank you!) , I could work out a solution which dynamically substitutes a localizated value if there exists one for a given value in the main table. If there is no localizated value, it takes the standard value from the field in the main table.

This is now the streamlined version to achieve this:

In xyzRow.cs (your main row class) on the ID field, add the following:

```cs
[ForeignKey("[<name of localization table>]", "<foreign key field which links to this ID field here>"), LeftJoin("<foreign table alias>")]

e.g:
[ForeignKey("[BooksLang]", "BookId"), LeftJoin("jBooksLang")]

```

Also add a foreign field which references the field within the localization table which holds the localization text:

```cs
#region Localization
        [DisplayName("Localization"), Expression("<Localization table alias>.<Real name of field which holds the localization text>"), LookupInclude]
        public String xxx { get { return xxx[this]; } set { xxx[this] = value; } }
        public partial class RowFields { public StringField xxx; }
        #endregion Localization

xxx = <virtual FieldName under which the localization field should be accessed within SF>

e.g.

        [DisplayName("Localization"), Expression("jBooksLang.[BookName]"), LookupInclude]
        public String BookName_Localization { get { return Fields.BookName_Localization[this]; } set { Fields.BookName_Localization[this] = value; } }
        public partial class RowFields { public StringField BookName_Localization; }
        #endregion Localization
```

Under /Modules/Common/Helpers/ create a new cs file named Extensions.cs with the following content:
```cs
    public static class SqlQueryExtensions
    {
        public static SqlQuery ApplyCurrentLanguage(this SqlQuery query, Alias joinAlias, Criteria joinCriteria)
        {   
            query.LeftJoin(joinAlias, joinCriteria);
            return query;
        }
    }
```
