### ISSUE TITLE
Changing the UI language; how to bind to event on server-side

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4963]
Hi all,

I want to re-generate some lookup scripts when the user changes the UI language in order to reflect the new language on some lookup dropdowns.

For this I would had to invalidate/re-create the relevant lookupscripts on server-side.

Where (or if at all) can this event on server-side be handled - and how?

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger  in the client when the LanguageID is changed -
Will   subscribing to the change event there  and then use  ReloadLookup() in the change handler work for you ? 
If rather I needed some additional processing server side..
I would handle this in the Language Endpoint / Repository  and call my Common Method to reload those there from the endpoint (like endoint.ChangeLookupLanguages(Id : Int) { do what I need to do }.

I am not sure if that is what your intention is ..

**Comment by JohnRanger** [comment]
Hi @stixoffire ,
thanks for your feedback - I will have to think it through. I mean - somehow the server-side exactly knows what the current selected UI language is- because if you use server-side translations it pulls them from the correct <language>.json file. So the server-side somehow must recognize the language change - or it gets the info every time at a click on anything which does a round-trip to the server from the client-side...

So I wnated to do some server-side stuff when that language changes- but yes - of course - I could write my own language-change endpoint and call it from client-side when the language is changed within the language selection dropdown.

I will close this question as it is a valuable solution.

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 

Sorry about the clarity on my previous response - but I am wearing many hats and basically in this I am putting together 3/4ths of an erp system.

I know in the layout it sets the culture to the selection

` new TDSProjects.Common.LanguageSelection($('#LanguageSelect'), '@(System.Globalization.CultureInfo.CurrentUICulture.Name)');`

I am thinking it knows from the CultureInfo.CurrentUICulture.Name .

Some of the samples have the Database Language rows - so I am wondering how that is joined to the descriptions or field names ..

**Comment by stixoffire** [comment]
@JohnRanger 
Just one more thing that I found is this gets set in the Global.asax file - so when you change the language on the UI - the global asax is performing this in a cookie..so perhaps just changing the language in the cookie will work. 
```
            var cookie = Request.Cookies["LanguagePreference"];
            if (cookie != null && !string.IsNullOrEmpty(cookie.Value))
            {
                try
                {
                    var culture = CultureInfo.GetCultureInfo(cookie.Value);
                    Thread.CurrentThread.CurrentUICulture = culture;
                }
                catch (CultureNotFoundException)
                {
                    // ignore
                }
            }
```
