### ISSUE TITLE
Replace jQuery UI datepicker with a lighter alternative

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#4968]
Possibly flatPickr (https://flatpickr.js.org/) to remove dependency on jQuery UI

**Comment by marcobisio** [comment]
Hi @volkanceylan, I've tried a bunch of datepicker, but in the end I chose just that (and I'm currently using it in production): highly recommended and quality one.

Bye!

**Comment by Zahar661** [comment]
How to do it?

**Comment by volkanceylan** [comment]
This is available in latest version, if you don't have ui datepicker loaded, but have flatpicker, then Serenity uses that one

**Comment by kilroyFR** [comment]
@volkanceylan i have 2 questions related to DateTime Editors :

a/ I have just updated to StartSharp 3.14 and generated a sample app + npm install flatpick, but still having the old DatePicker on generated application.
(datepicker is commented  on ScriptBundles.json   //"~/Scripts/datepicker/bootstrap-datepicker.js")
Q1 : Is there Something special to be done to activate flatpickr ?

b/ When using QuickFilter on Date Selection (from Date -> to Date) i can only select Date (not date+time).
There is a RangeDateTime selector available on the demo (that allows input of such parameters).
Q2 : how is it possible to enable this and replace existing QuickFilter DateTime fields ? (see Orders grids as in below picture) 

![image](https://user-images.githubusercontent.com/31513956/90450203-6e415a80-e0e9-11ea-9a3c-bf099aab7748.png)

to be replaced by : 
![image](https://user-images.githubusercontent.com/31513956/90450269-98931800-e0e9-11ea-9b36-f91932067cc2.png)

Is that possible ?

Thanks !

**Comment by kilroyFR** [comment]
@marcobisio any idea ?
