### ISSUE TITLE
Fix issues in Serenity.CoreLib.js when jQuery UI or jQuery validate is not loaded

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#4969]

**Comment by kartalbas** [comment]
Hi Volkan, before Im opening a new issug...

Since I upgrade a test project from NetCore 2.2.to 3.1. on changing a User Role on UI, I get following exception

```
jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:9600 Failed to load resource: the server responded with a status of 403 (Forbidden)
send @ jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:9600
jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:3827 Uncaught Error: Can't load script data: RemoteData.UserData!
    at Object.ensure (Q.ScriptData.ts:114)
    at Object.getRemoteData (Q.ScriptData.ts:177)
    at Object.get (Q.Authorization.ts:63)
    at Object.hasPermission (Q.Authorization.ts:13)
    at ReportOpenGrid.EntityGrid.hasInsertPermission (EntityGrid.ts:257)
    at Object.disabled (EntityGrid.ts:148)
    at HTMLDivElement.<anonymous> (Toolbar.ts:180)
    at HTMLDivElement.dispatch (jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:5183)
    at HTMLDivElement.$event.dispatch (jquery.event.drag.js?v=Q42_cWjms19Czv7rSFThUg:380)
    at HTMLDivElement.elemData.handle (jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:4991)

```

Also my newly generated modules with `dotnet sergen g` shows me the same exception.

does this issue pointing this?

**Comment by volkanceylan** [comment]
No relation at all

**Comment by reach2rv** [comment]
> 
> 
> Hi Volkan, before Im opening a new issue...
> 
> Since I upgrade a test project from NetCore 2.2 to 3.1. on changing a User Role on UI, I get following exception
> 
> ```
> jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:9600 Failed to load resource: the server responded with a status of 403 (Forbidden)
> send @ jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:9600
> jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:3827 Uncaught Error: Can't load script data: RemoteData.UserData!
>     at Object.ensure (Q.ScriptData.ts:114)
>     at Object.getRemoteData (Q.ScriptData.ts:177)
>     at Object.get (Q.Authorization.ts:63)
>     at Object.hasPermission (Q.Authorization.ts:13)
>     at ReportOpenGrid.EntityGrid.hasInsertPermission (EntityGrid.ts:257)
>     at Object.disabled (EntityGrid.ts:148)
>     at HTMLDivElement.<anonymous> (Toolbar.ts:180)
>     at HTMLDivElement.dispatch (jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:5183)
>     at HTMLDivElement.$event.dispatch (jquery.event.drag.js?v=Q42_cWjms19Czv7rSFThUg:380)
>     at HTMLDivElement.elemData.handle (jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg:4991)
> ```
> 
> Also my newly generated modules with `dotnet sergen g` shows me the same exception.
> 
> does this issue pointing this?
> 
> P.S. the project was genereated from scratch with Serene and [upgraded](https://github.com/volkanceylan/Serenity/issues/4801) to Net Core 3.1

@kartalbas Hi, are you able to resolve this issue?? if yes can you please help me with the solution
