### ISSUE TITLE
ToastrOptions

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#497]
Dear @volkanceylan,
I'm playing with ToastrOptions trying to create a Toast with the close button that never disappear (until the close button is clicked).
So I managed to add the button and also modify the timeout like this

hub.client.globalNotification = function (notification) {
            var to = {};
            to.timeOut = 10000;
            to.closeButton = true;
            Q.notifySuccess(notification, '', to);
        };

but I was wondering if there a 0 or -1 trick to obtain what I'm looking for...

Moreover, which is the difference between the **TimeOut** property and the **ExtendedTimeOut** one?

Thanks for your support
Best Regards

**Comment by 107295472** [comment]
He's sleeping

**Comment by marcobisio** [comment]
copy that...I'll wait :-)

**Comment by 107295472** [comment]
This does not directly write js, c# generated

**Comment by volkanceylan** [comment]
See toastr options in its own repository / docs. I dont know this.

**Comment by marcobisio** [comment]
Ok thanks!
