### ISSUE TITLE
Serenity homepage and open-source option

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4972]
Hello @volkanceylan 

I see that Serenity's homepage has new UI, it's nice UI !

But there is a small problem, I introduced Serenity to many people and they always ask me is if it's free, because when they look at Serenity homepage, all options of Pricing have a price.

So can you add one more options that show that Serenity also has a free version (open source) too.

I think that small change will help them spend more time to research Serenity framework

**Comment by Nathan2020-0126** [comment]
I think it would be a good idea.

**Comment by JohnRanger** [comment]
Hi @volkanceylan ,

on your new serenity.is page, both the "Demo" and the "buy now" button do currently (2020-04-13, 14:10) not work. tested both with Chromium-based browser and Edge. 

![image](https://user-images.githubusercontent.com/2699447/79119478-c27dac00-7d90-11ea-9a30-9641e61ae325.png)
