### ISSUE TITLE
How to modify insert/update query dynamically within saverequesthandler

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4973]
Hi all,

in my "quest" to provide a generic usable solution for data localization (multi-language, data translation - similar to UI multi-language capabilities of SF) I have advanced so far very well.

Reading of the localized values from database is now fully transparent and does require very little customization on the SF project itself. The workflow is very straight forward. (I will post a full wiki when all sharp edges are ironed out).

The only thing left now is to be able to transparently **write** to the fields within the main table.

As on the database side, the transparent localization is implemented via an intelligent - writeable - view (on MSSQL and SQLite see Instead of INSERT|UPDATE|Delete triggers to achieve that), the only thing needed is always to additionally provide the language ID within the SQL statements which go to the database engine.

For Retrieve and list handlers, this is easily done by overriding PrepareQuery like this:

```ts
        private class MyListHandler : ListRequestHandler<MyRow> {
            protected override void PrepareQuery(SqlQuery query)
            {
                base.PrepareQuery(query);

                var UI_languageID = LanguageHelpers.getCurrentUIlanguageID();
                query.Where($"languageId = {UI_languageID}");
            }
        }

```

But the prepareQery method available also in the saveHandler, does only affect the reading part of that action (a select statement). 

**Question:**

How to dynamically modify the update / insert query before it is executed against the database engine?

Thanks for your help.

John

**Comment by minhhungit** [comment]
I guess it will update/delete by id so I think it's still okay

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

I have found out now that I can influence the query within the ExecuteSave() method.

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger  Have you thought of modifying the request / response object to pass the languageId /..CurrentCulture  ..if it is in that object it is always dynamic and the code would probably be able to easier to add - perhaps not good to add after the fact in a large project .. just thinking out load ..that is where I would place it and I would be able to change languages on the fly - even request to request ..for example I could request a listing for a report in one language and do it in another  right after wards.

**Comment by bitcubetoka** [comment]
Hi @JohnRanger. Do you have an example of this ? I am looking to do something similar to you.
