### ISSUE TITLE
Serenity-netCore news Questions & migration process

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4974]
Hey Volkan, thanks for the direction the framework is going, everything is logical and makes sense in the decisions taken in your framework.

One small question : 
Why you did not choose to (for those shared code) use of #if COREFX at least the time for the people to move to .netCore.
For now i have both applications on .netFullFramework and on .netCore and i could share components using this kind of directives (moved all the common stuffs into a shared package).
One day when all my applications have moved i will simply remove all #if !COREFX code.
I am currently in the transition period, probably like many.

ex : 
![image](https://user-images.githubusercontent.com/31513956/79105117-483d2f80-7d70-11ea-9e0f-808c19020751.png)
And it also is useful to learn (visually) the differences between these 2 Framework versions.
Yes it leads to useless code but at least facilitate transitions without having to list all modifications in every file of the generated applications.

**Comment by kilroyFR** [comment]
Another (1) small question related to aspnetCore Version.
I noticed `Vegas` plugins is still present but no progress bar is made visible (even on serenity.is/demo).
Is that normal ?

**Comment by volkanceylan** [comment]
In demo there is a progress bar. 

I'll better remove all these ifdefs, and will soon be obsoleting .NET MVC version.

Legacy .NET framework is dead, we have to accept it. .NET 5 will be based on .NET Core.

**Comment by kilroyFR** [comment]
yes they are obviously not the future but please do not forget to warn us when you decide to remove (please not the way they do on webhosting when they suddenly decide to remove support of a PHP version).
I have personally not moved all my current applications to .netCore but in the process (my personal goal is max time october in order to be ready to move to .net5).
Thanks

**Comment by volkanceylan** [comment]
Opened an issue for migration process, closing.
