### ISSUE TITLE
New serenity.is homepage; Demo and buy now buttons do currently not work

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4975]
Hi @volkanceylan ,

on your new serenity.is page, both the "Demo" and the "buy now" button do currently (2020-04-13, 14:10) not work. tested both with Chromium-based browser and Edge. 

![image](https://user-images.githubusercontent.com/2699447/79119478-c27dac00-7d90-11ea-9a30-9641e61ae325.png)

**Comment by volkanceylan** [comment]
Oops thanks for reporting will fix soon
