### ISSUE TITLE
Please add Dark Mode skin.

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#4976]
Hi

Please add Dark Mode skin, Just like macOS Mojave support the same. This is most popular desgin style.

Thank you very much!

**Comment by kilroyFR** [comment]
Current themes are available only to Registered StartSharp users.
But anyone willing to share a dark theme is welcomed. 
I customized mine for my applications (as we have a special set of colors to respect in my company).

**Comment by JohnRanger** [comment]
Hi @kilroyFR ,
is there anything you could share in regard to customize the SF theme, which would make it easier and faster to make a new theme - or do we just have to go through all css & images within /Content/themes/base/ and change what is required?

(Or is there some guide already available?)

With kind regards,

John
