### ISSUE TITLE
New Developer - Change button Text

### ISSUE THREAD

**Issue by mykedeabreu** [volkanceylan/Serenity#4977]
Hi Volkan and community,

During the Covid19 Outbreak I have decided to finally try on taking some programming as it is something I have always wanted to do - so please forgive me if I ask any silly questions.

I have been using Serenity to try and learn and absolutely love it. 

Can someone please walk me through changing the Text on the "New <sqlTable" button when creating a new entry? I have seen a couple people say to create a CSS class for it but I don't quite understand.

**Comment by vegalic** [comment]
Hi,

I think you can just change InstanceName and DisplayName attributes on Row class.

Example:
![image](https://user-images.githubusercontent.com/6953746/79251349-50849000-7e80-11ea-8324-0a4268df7c41.png)

**Comment by mykedeabreu** [comment]
How would this allow me to change text on buttons withing forms I am creating?
