### ISSUE TITLE
How to deal with Repository with background job

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4978]
Dear all,

I have implemented Hangfire in Serenity.
But I found there is a problem when running hangfire job which contain Repository. So I have to write another method which without Repository. 

Do you have any good experience with using background job?

**Comment by stixoffire** [comment]
Check out the BulkCancellable action in the samples - also you can find it in questions here. I am really tired long long day (20hours) so sorry for short answer

**Comment by marcobisio** [comment]
Hangfire and Serenity can be integrated seamlessy, i'm using both without any kind of issue. Can you describe what do you mean when you're talking about "problem"?
Keep in mind that in a Hangfire job, you're outside of the Serenity authorization context, so you've two options:

- using repositories together with the ImpersonatingAuthorizationService
- using connection extension methods that dosn't take care of the permissions

Regards

**Comment by Nathan2020-0126** [comment]
@marcobisio , thanks for your information.
the problem I means are:
1. InsertUserId cannot be automatic filled because the job is running in background, no user login.
2. As you mentioned, cannot pass permission check

I will try to use ImpersonatingAuthorizationService.
