### ISSUE TITLE
Add Company and Financial Year to UserDefination

### ISSUE THREAD

**Issue by reach2rv** [volkanceylan/Serenity#4979]
Hi **@volkanceylan,**

We have Company table which is linked to user details table and financial year which is independent table.

we are able to add company lookup and financial year lookup to login and it works only issue we are facing is if user close the tab of browser and open another tab with app he gets logged in and companyid and financial year id become 0.

what is the best way to overcome from this.  or how we can force user to relogin if either of company of financialyear id is 0 or null?

if required I can share a complete code snippet of changes we have made. this is very much required for all inventory and accounting applications.

regards,

Arvind

**Comment by stixoffire** [comment]
If they are 0 or null simply call the logout function.

**Comment by reach2rv** [comment]
solved it using
` var user = (UserDefinition)Serenity.Authorization.UserDefinition;
    if (user.CompanyId == 0)
    {
       Context.Response.Redirect("/Account/Login");
    }`
in _layout.cshtml

I am closing this.. but if anyone has more elegant solution do post it here.
Regards,

Arvind
