### ISSUE TITLE
How to view an inserted document at the left side of an Edit Dialog?

### ISSUE THREAD

**Issue by Xaninho** [volkanceylan/Serenity#4980]
On a certain Edit Dialog I want the option for the user to add a pdf file (and it's working fine).

However, one of my project requirements is that the user is able to view the document while editing it in the Edit Dialog. While opening the PDF document in a separate tab is a lazy solution, it would be great if the PDF was shown at the left side of the Edit Dialog! Here's an example: 

![imagem](https://user-images.githubusercontent.com/52694651/79327897-20cf9980-7f0d-11ea-9cef-15f347a79f4e.png)

In this mockup, when the user would anex a file, it would appear at the left position of the Edit Dialog box, allowing the technician to analyze the document and modify information real-time. Would it be possible to achieve this? I've already read some documentation but the only way I've found to edit a form would be a vertical edit, and without HTML/CSS manipulation, inside the Form.cs.

Any help would be greatly appreciated 😊

PS.: If somehow it would make more sense/ it would make it easier to anex a .jpeg of .png file instead of a .pdf, so be it. I've already come across a plugin to embed pdf into html (https://stackoverflow.com/questions/291813/recommended-way-to-embed-pdf-in-html), but I don't know how to apply it to Serenity.

**Comment by stixoffire** [comment]
add the html element like you would in regular typescript, then set the canvas - see my write up on pure typescript signaturePad in the wiki - you will see the html element canvas added and how it is done there .
Basically you are adding the canvas element to the form (or in a field) and then put your image there. Look at the wiki home page - 100% pure type script signaturePad

**Comment by Xaninho** [comment]
@stixoffire That seems to make a lot of sense and that it would work! Could you point me to where I could find the example please? 🙂

**Comment by Xaninho** [comment]
@stixoffire Thank you! I'll check it and make some experiences, hopefully I'll get back quickly with a response 🙂

**Comment by Xaninho** [comment]
@stixoffire So 3 point here:

- I've tried to follow the article on the wiki to add the SignaturePad field to my form. First of all, I've added the files to Imports/ServerTypings and then added the implementation to the DocumentRow, DocumentColumns.cs and DocumentForm.cs. The [SignatorEditor] started to work correctly. But after doing a Rebuild, all of my .ts files that I added were now gone and added 2 signature classes to my Imports/ClientTypes... Bottom of the line is that the [SignatureEditor] is still working but the files are gone;

- Over at the DocumentDialog.ts, getSlickOptions() property does not exist: 

![Captura de Ecrã (14)](https://user-images.githubusercontent.com/52694651/79353219-ae71b000-7f32-11ea-92d7-764474f220b0.png)

- Is this the simplest way to achieve the image at the left? I get the idea of building the canvas, using these methods, but what I really needed was a way of editing the HTML of a specific form to allow it to have an image attached to the left of it.

**Comment by stixoffire** [comment]
The SignaturePad was meant as an example - the code that places the canvas - Jquery is how you place a canvas in a particular position ..  Then just looking at the code how th eimage is drawn on it  

Below is an outline of what you need to do .. 
1:create the canvas in your TS file, myCanvas = HtmlCanvasElement() // with an Id such as "myCanvas" 
Standard typescript html ..
2: find the place in your document  where you want to place the new canvas . var myPlaceHolder = this.element.find() .. standard JQuery will work ..to find the element in your document to place the Canvas at or Before the other stuff .
3: Add the Canvas myPlaceHolder.Add(myCanvas);

4: then it is basically like this to place the image 
```
  var c = document.getElementById("myCanvas");
  var ctx = c.getContext("2d");
  var img = yourImage;
  ctx.drawImage(img, 10, 10);
```

In all of this you might need to find the existing document data - like this.element

Place it in a 
```
<div class=row>
<div class=pdfLeft><canvas id='myCanvas'></canvas></div>
<div>{place your right hand stiff here}</div>
```

**Comment by Xaninho** [comment]
@stixoffire That's a nice guide on how to achieve it. Thanks a lot!

**Comment by stixoffire** [comment]
@Xaninho  if you have it working - it would be a good idea to post it in the WIKI - since Volkan has shared this nice platform ;  I try to share my solutions in the WIKI so others can benefit. I hope that in turn they too will do things that perhaps others (including myself) might need or be able to modify for whatever requirement.
