### ISSUE TITLE
How to  show image with  original path in filed

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#4981]
Hi,
I have saved image path in string field like :  C:\User\N\logo.jpg in other program.

I want to show it on form and try it with ,
 [ImageUploadEditor(FilenameFormat = "ProductImage/{1:0000}/{0:00000000}_{4}")], but no help. 

Always path  start with localhost/upload folder.

Please help.

**Comment by gfo2007** [comment]
@Nikola7i you would have to go to your web.config file and change the value in UpLoadSettings.

However, keep in mind that only internet explorer of microsoft edge allows paths with drive letters as they are deemed insecure. Both firefox and chrome will block paths with drive letters in them.

Regards.

**Comment by Nikola7i** [comment]
Tnx,

Can this generic path with drive letters converted to readble  format with some code ?

**Comment by gfo2007** [comment]
@Nikola7i you can rather consider using the UNC path to the file. The link below will give you an idea how to create such a path.

https://stackoverflow.com/questions/2787203/unc-path-to-a-folder-on-my-local-computer

Regards

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
