### ISSUE TITLE
Populate Lookup Editor with RowFields (Column Names of a Table)?

### ISSUE THREAD

**Issue by bt101** [volkanceylan/Serenity#4983]
Hello,
I am trying to populate a Lookup Editor with the Column Names from a different table.  

I have tried adding a Lookup Editor in abcColumn with the RowFields from zyxRow.

Here is the example RowFields in zyxRow:

      public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public StringField Column01;
            public StringField Column02;
            public StringField Column03;
      }

Here is the example abcColumns:

    public class abcColumns
    {
       [LookupEditor(typeof(zyxRow.RowFields))]
        public String Field { get; set; }
    }

In this example I would like the Field Lookup Editor to be populated with values Column01, Column02 and Column03.

Thanks in advance!

**Comment by haoas** [comment]
[https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/BasicSamples/Editors/SelectWithHardcodedValues/HardcodedValuesEditor.ts](url)

**Comment by bt101** [comment]
Hi haoas,
Thanks for the response. I figured I would resort to hard coded values if I'm unable to do it dynamically.  I was hoping there would be some way to do it programmatically within the framework like the behavior of the dynamic grid filter -- @Serenity.Decorators.filterable().

Thanks,
Ben

**Comment by RouteTech** [comment]
Hi Ben,
you can try something like this.

public ListResponse<TableFieldInfo> GetTableHeaders(GetTableHeaderListRequest request)
        {
            ListResponse<TableFieldInfo> response = new ListResponse<TableFieldInfo>();
            string entityName = request.TableName;
            Type rowType = Type.GetType(entityName);
            if (rowType == null)
                throw new ArgumentOutOfRangeException("Table not found");

            Row tableRow = (Row)Activator.CreateInstance(rowType);
            List<Field> tableFields = tableRow.GetTableFields().ToList();
            List<TableFieldInfo> tableFieldInfoList = new List<TableFieldInfo>();
            foreach (var item in tableFields)
            {
                TableFieldInfo tableFieldInfo = new TableFieldInfo
                {
                    Name = item.Name,
                    Title = item.Title,
                    Type = item.Type.GetName()
                };
                tableFieldInfoList.Add(tableFieldInfo);
            }
            response.Entities = tableFieldInfoList;
            return response;
        }

**Comment by bt101** [comment]
Hi @RouteTech 
Thank you! Most people would probably be able to take this and run with it but when I try to implement it, things don't seem obvious. At least to me.

I consider myself stronger with databases and non-web based programming.  I still have trouble knowing what goes where -- at least it doesn't seem intuitive like SQL and non-web based programs.

Where would I put this code?  Is it a new Repository function?  And how do I call it so that it populates the Lookup Editor?  A few more tips would be greatly appreciated!

Thanks in advance!

**Comment by RouteTech** [comment]
The example above that Haoas cited will work. Instead of hard coding the values the response will contain the field info.
The section on "Handling Lookup scripts" will show you how to override the prepare query function.
If you need the list for more than the lookup then put the code in the endpoint and call it like any other service.

**Comment by bt101** [comment]
Thanks @haoas and @RouteTech! I'll give this a shot and report back.  Greatly appreciate your help.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform

**Comment by fremar83** [comment]
Just in case ...
MyRow.Fields.MyField.Name
