### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of null     at GridRowSelectionMixin.updateSelectAll

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#4984]
Many times I'm getting error while return to Grid from dialog.. any help!

Uncaught TypeError: Cannot read property 'find' of null
    at GridRowSelectionMixin.updateSelectAll (SlickHelpers.ts:76)
    at RemoteView.<anonymous> (SlickHelpers.ts:71)
    at Event.notify (slick.core.js?v=BLCRBDx7U3jsEuDNgnEQkw2:144)
    at refresh (Serenity.Externals.Slick.ts:1447)
    at setItems (Serenity.Externals.Slick.ts:708)
    at addData (Serenity.Externals.Slick.ts:1592)
    at Object.success (Serenity.Externals.Slick.ts:1658)
    at fire (jquery-3.4.1.js?v=EcBesobtV2Umv0VDdgeFuQ2:3291)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.js?v=EcBesobtV2Umv0VDdgeFuQ2:3421)
    at done (jquery-3.4.1.js?v=EcBesobtV2Umv0VDdgeFuQ2:9533)

![image](https://user-images.githubusercontent.com/23294782/79688942-c7e06800-8262-11ea-8e23-84705c570122.png)

![image](https://user-images.githubusercontent.com/23294782/79688951-da5aa180-8262-11ea-818d-e2c19b69ba69.png)

**Comment by JohnRanger** [comment]
HI @mustafalotiya ,

in what kind of browser do you get this?

With kind regards,

John

**Comment by mustafalotiya** [comment]
Hi John,

I'm using Google chrome.

**Comment by JohnRanger** [comment]
Hmm,

so far I never had this problem. What is your environment?

- Project type? (Full .NET or core)
- SF version (to see that, look under packages and there you can see the Serenity core with a version)
- Is this happening in visual studio or when the project is deployed to a webserver (I see localhost - but this could be a webserver on your machine)?
- Is this on Linux or Windows?
- Do you have any specific antivirus app running on your machine?
- Do you have fiddler installed and running?

I am just trying to understand your environment better to ally suggest some actions.

Regards,

John

**Comment by mustafalotiya** [comment]
Hi John 
Thanks for your time.
Please find below highlighted response.

Project type? (Full .NET or core)  - **.NET** 
SF version (to see that, look under packages and there you can see the Serenity core with a version)  : **3.12.6**
Is this happening in visual studio or when the project is deployed to a webserver (I see localhost - but this could be a webserver on your machine)? **Yes in production and development both**
Is this on Linux or Windows? **Windows** 
Do you have any specific antivirus app running on your machine? **No Antivirus** 
Do you have fiddler installed and running? **No fiddler installed**

**Comment by stixoffire** [comment]
@mustafalotiya 

Your XYZgrid has a function find that is being called on an object - that object does not exist.

So imagine you call find from an object that is not instantiated basically like doing this;
`null.find('this_thing') `

Null does not exist and so you can't call find either.

I would start searching the XYZGrid for the .find() function and then start checking that object for why it is not defined so for example 

`myobjectIsNotdefined.find('blah') `

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
