### ISSUE TITLE
MultipleFileUploadEditor and clone entity

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#4986]
Hi! 
When cloning an entity that has an attachment, this error occurs. 

> For security reasons, only temporary files can be used in uploads!

Who knows how to solve a problem?

**Comment by stixoffire** [comment]
@Zahar661 Where is the file located ? On the client machine ?  then you need to upload it as a temporary file first and attach there - I think the issue is that chrome will not report back the file path - but instead gives it an alias ..

**Comment by Zahar661** [comment]
@stixoffire The file is already on the server in the persistent storage, it is attached to the original entity.

**Comment by hannesb** [comment]
AFAIK cloning attachments is not supported. What should be the expected behavior anyway?

For me, not cloning any attachments is the way to go. Just override getCloningEntity in your dialog class like this:

`protected getCloningEntity() { `
`   var clone = super.getCloningEntity();`
`   clone.<Your attachment field name> = null;`
`   return clone;`
`}`

HTH
Hannes

**Comment by Zahar661** [comment]
@hannesb  I need it((((

**Comment by stixoffire** [comment]
@Zahar661 After you clone the entity - assign the original attachment to the cloned entity ..
clone.<Your attachment field name> = MyOriginalEntity . <Your attachment field name>;

I know that is round about way but with HannesB answer the only way I know of to workaround is to copy from original - long way.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform

**Comment by talhacetin01** [comment]
I'm also having problems with this topic. I need to clone an entity that has an uploaded file. Cloned entity must have a temporary copy of its original uploaded file. 

Right now, I'm trying this:
`protected getCloningEntity() {
    var clone = super.getCloningEntity();

    if (clone.FilePath) {
        SummaryService.CopyToTemporary({ FilePath: clone.FilePath }, response => {
            clone.FilePath = response.TemporaryFilePath;
            this.form.FilePath.value = {
                Filename: response.TemporaryFilePath,
                OriginalName: ''
            }
        }, {
            blockUI: true,
            onError: e => notifyError("Copy error: \n" + (e?.Message || e))
        }
        )
    }
    return clone;
}`

But it doesn't update the ImageUploadEditor.
