### ISSUE TITLE
Script data Form.XYZExcelImport is not found in registered script list!

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#4988]
when i Import Excel , i am getting error: Script data Form.xyz.ExcelImport is not found in registered script list!
I find when I modify the code indicated by the arrow in the figure below.   the application is ok.
but i do not understand why the path is wrong?
![2020-04-24_11-57-33](https://user-images.githubusercontent.com/3275525/80173608-f1aedb80-8622-11ea-8dc3-a5f62adb49da.jpg)

Debug I find the XYZform path is like this
![2020-04-24_11-51-32](https://user-images.githubusercontent.com/3275525/80173464-89f89080-8622-11ea-9aef-87c59e72cba3.jpg)

thank you!!

**Comment by Nathan2020-0126** [comment]
Did you using the PropertyDialog?
if yes, please add below code to explicit tell the form whcih formkey is needed.
 
  protected getFormKey() { return MaterialForm.formKey; }

**Comment by kuyu7766** [comment]
@Nathan2020-0126  work well !!  thank you!  
it's strange, because the demo northwind do not need to add this code

**Comment by Nathan2020-0126** [comment]
@kuyu7766  Are you chinese?   personally  I like Serenity very much, But it seems not popular in China.

**Comment by stixoffire** [comment]
Notice your FormXYZImport you do not have MyMoodule DOT ExcelImport
[FormScript("MyModule.OrderExcelImport")]

The path in your registered name is :  "Form DOT OrderExcelImport" 
FORM.MyImport 
Is not the same as MyImport ..

Define your script correctly and it will work as advertised.

**Comment by kuyu7766** [comment]
@Nathan2020-0126  是啊，   幸会幸会。 这个框架用了很多模式设计在里面，还没有完全熟悉，多多指教。

**Comment by kuyu7766** [comment]
@stixoffire thank you.

**Comment by Nathan2020-0126** [comment]
@kuyu7766  我用这个框架已经三四年了。 我们可以多交流交流。 你有什么联系方式吗？ 我们可以经常沟通。  
这里有我整理的一些常用代码块，写代码时复制黏贴快。
https://nathan2020-0126.github.io/SerenityMannual/2020/03/18/%E4%BB%80%E4%B9%88%E6%98%AFSerenity/

**Comment by kuyu7766** [comment]
QQ: 32361551 ^^

**Comment by kuyu7766** [comment]
@Nathan2020-0126  QQ 32361551
