### ISSUE TITLE
How get view template for Mail in Repository Class

### ISSUE THREAD

**Issue by jaydeeprsakariya** [volkanceylan/Serenity#4989]
private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void AfterSave()
            {                          
                base.AfterSave();
                var emailModel = new OrderEmailModel();
                emailModel.RequestedBy = Connection.ById<UserRow>(Row.UserId).DisplayName;
                emailModel.UrgencyLevel = Connection.ById<UrgencyChoicesRow>(Row.UrgencyLevel).Name;
                emailModel.Line = Connection.ById<LineChoicesRow>(Row.Line).Name;
                emailModel.Facility = Connection.ById<FacilityChoicesRow>(Row.Facility).Name;

                if (Row.DetailList != null)
                {
                    List<OrderDetailsEmailModel> ordDetails = new List<OrderDetailsEmailModel>();
                    foreach (var item in Row.DetailList)
                    {
                        OrderDetailsEmailModel ordDetail = new OrderDetailsEmailModel();
                        ordDetail.PartNo = item.ItemName;
                        ordDetail.Description = item.Description;
                        ordDetail.Vendor = item.Vendor;
                        ordDetail.Cost = item.Cost == null ? "" : item.Cost.ToString();
                        ordDetail.Quantity = item.Quantity == null ? "" : item.Quantity.ToString();
                        ordDetails.Add(ordDetail);
                    }
                    emailModel.OrderDetails = ordDetails;
                }
                
                var emailSubject = "Order " + Row.OrderId + " - Pending Approval";
                string emailBody = TemplateHelper.RenderViewToString(HttpContext.RequestServices,
                    MVC.Views.ManageOrders.Orders.OrderEmail, emailModel);
                var email = "abc@gmail.com";
                Common.EmailHelper.Send(emailSubject, emailBody, email,"abc");
            }          
        }

> I am getting error in "HttpContext.RequestServices"

**Comment by stixoffire** [comment]
It would help to know what error you are getting - not just where you are getting an error .

HttpContext.RequestServices might be null ..

**Comment by ga5tan** [comment]
it may be, because u dont have httpcontext.
that happens, if you are running bkg tasks for example.
in that case, u have to fake that http context

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
