### ISSUE TITLE
New to Serenity

### ISSUE THREAD

**Issue by tunminster** [volkanceylan/Serenity#499]
I have successfully install Serenity. All the tables are generated in my local database.

But when i run the application, I only see blank pages.  I am looking to see order, product, category pages as I see them in sql tables.

Any thoughts?

Regards,
Tun

**Comment by volkanceylan** [comment]
Try rebuilding solution as it was stated in code generator

**Comment by tunminster** [comment]
I was trying to do that. after that nothing much different.

![image](https://cloud.githubusercontent.com/assets/2794565/14210142/9bfb902e-f81f-11e5-81b1-bb0469842df1.png)

**Comment by tunminster** [comment]
It is going to '/account/login' which doesn't exist in the project.
![image](https://cloud.githubusercontent.com/assets/2794565/14210195/dca4bbd2-f81f-11e5-85fb-bf3324788d54.png)

**Comment by volkanceylan** [comment]
It's a MVC controller, it doesn't have to exist in project

**Comment by volkanceylan** [comment]
Please see Chrome console on what errors you get from these blank pages

**Comment by zerodev** [comment]
I can see that ur project name is in the wrong format :+1:  SMT.Admin No dots in the Solution name

**Comment by volkanceylan** [comment]
Oh how did i miss that. VS generates a safe project name, replacing dots with underscores, that's why your solution name shouldn't have dots at creation. You may rename it later.

**Comment by tunminster** [comment]
Yes. I've found this from chrome console page.
![image](https://cloud.githubusercontent.com/assets/2794565/14215302/14240940-f83a-11e5-960d-d1d68918bfc5.png)

**Comment by volkanceylan** [comment]
You should create a new solution without dots in name

**Comment by tunminster** [comment]
Thank you very much. It works. yes it was project name causing the probelm

**Comment by tunminster** [comment]
sorry. after I generated category management session successfully, 

I've tried to add a new category. 
Then, I've received the below error. If there is some file missing in the project?


![image](https://cloud.githubusercontent.com/assets/2794565/14215791/16cedc6c-f83d-11e5-845d-1488ba0dcf49.png)

**Comment by volkanceylan** [comment]
There is no missing file i guess. It probably gives an exception and trying to show source.

**Comment by tunminster** [comment]
this is it then.  

![image](https://cloud.githubusercontent.com/assets/2794565/14220245/bbad5876-f856-11e5-9843-bff060081159.png)

**Comment by volkanceylan** [comment]
This is typescript code, just install latest version but it shouldnt be causing exception
