### ISSUE TITLE
DetailDetails not loading in multi level MasterDetail editor

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#4990]
Hi Serenity community,

I am having trouble with a multi-level MasterDetail editor. 

It started off with just Master-Detail and it worked fine. Then I tried the same steps on my Detail-Detail and that's where I'm tripping up.

**Problem**:
- When I open an existing Detail record from the Master dialog, I can see the Detail properties, but the DetailDetail records are not showing. 
- I can add a new DetailDetail, and it is displayed in the DetailDetail grid until the Master is saved, then it disappears. 
- The DetailDetail does get saved to the database, but when loading the master, the Detail is shown, but not the DetailDetail.

I think I might need a filter/cascade on my dialog (TypeScript), but I'm not sure what I am missing.

Has anyone done this and can help?

Some context:
My three tables are: _Sites_, _Devices_, _DeviceConfigSchedules_

Sites can have multiple Devices
Devices can have multiple DeviceConfigSchedules

They are loosely defined as such:
**Sites**
- SiteId
- Name

**Devices**
- DeviceId
- SiteId
- Name

**DeviceConfigSchedules**
- DeviceConfigScheduleId
- DeviceId
- StartDate

In SiteRow.cs I have:
```cs
[LookupEditor(typeof(SiteRow))]
[DisplayName("Site"), NotNull, ForeignKey("[dbo].[Sites]", "SiteId"), LeftJoin("jSite"), TextualField("SiteName")]
public Int32? SiteId

// other properties

[DisplayName("Devices"), MasterDetailRelation(foreignKey: "SiteId"), NotMapped]
public List<DeviceRow> DeviceList
```

In SiteForm.cs I have:
```cs
[DevicesEditor]
public List<Entities.DeviceRow> DeviceList { get; set; }
```

In DeviceRow.cs I have:
```cs
[DisplayName("Config Schedules"), MasterDetailRelation(foreignKey: "DeviceId"), NotMapped]
public List<DeviceConfigScheduleRow> ConfigScheduleList
```

In DeviceForm.cs
```cs
[DeviceConfigSchedulesEditor]
public List<Entities.DeviceConfigScheduleRow> ConfigScheduleList { get; set; }
```

In DevicesEditor.ts
```ts
/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace MyProject.MyModule {

    @Serenity.Decorators.registerClass()
    export class DevicesEditor extends Common.GridEditorBase<DeviceRow> {
        protected getColumnsKey() { return "MyModule.Device"; }
        protected getDialogType() { return DeviceDialog; }
        protected getLocalTextPrefix() { return DeviceRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        validateEntity(row, id) {
            return true;
        }
    }
}
```

On DeviceConfigScheduleRow.cs
```cs
[LookupEditor(typeof(DeviceRow))]
[DisplayName("Device"), NotNull, ForeignKey("[dbo].[Devices]", "DeviceId"), LeftJoin("jDevice")]
public Int32? DeviceId
```

In DeviceConfigSchedulesEditor.ts
Same layout as DevicesEditor.ts, but for DeviceConfigSchedules

TIA!
Edward

**Comment by hannesb** [comment]
Probably the IncludeColumns parameter in MasterDetailRelation is missing.

HTH
Hannes

**Comment by edwardch** [comment]
Ahhhh, thank you @hannesb, that was it!

I changed SiteRow.cs like so:
```cs
[DisplayName("Devices"), MasterDetailRelation(foreignKey: "SiteId", IncludeColumns = "ConfigScheduleList"), NotMapped]
public List<DeviceRow> DeviceList
```

Cheers,
Edward
