### ISSUE TITLE
How to set first row as default selected

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4991]
I Implemented RowSelectionModel in Grid. I want to make first row as default selected. how to do ti?
I try to use  **self.prodOrderItemGrid.slickGrid.setSelectedRows([items[0]])**, but it didnot work.
`
 protected createSlickGrid(): Slick.Grid {
            var grid = super.createSlickGrid();
            grid.setSelectionModel(new Slick.RowSelectionModel());
            return grid;
        }`

**Comment by stixoffire** [comment]
You might need to call the layout update.. I forget the exact method - but it has to do with redrawing the layout .

**Comment by Nathan2020-0126** [comment]
@stixoffire  Do you mean like below? but it didnot work
  self.prodOrderItemGrid.element.triggerHandler("layout");

**Comment by stixoffire** [comment]
@Nathan2020-0126  
Yes, however looking at a couple things - there are issues with [slickGrid selection](https://github.com/mleibman/SlickGrid/issues/391) in the manner you describe. First lets see what we actually have .

1: Does the setSelectedRows([Item[0]]) exist ? 
If not - then we need to determine how to reference the row ..
2: Is the row really defined as  setSelectedRows([0])?
If 2 You would need to search the rows for that Item first and get the index and then set it. so IndexOf(Item[0])).

You could try this from #1192
you need to trigger its resizeCanvas method.
and the way to do that is:
$('.require-layout').filter(':visible').each(function (i, e) {
$(e).triggerHandler('layout');
});
[Issue 1192](https://github.com/volkanceylan/Serenity/issues/1192#)

**Comment by Nathan2020-0126** [comment]
@stixoffire thanks for your detailed answers. I will try it and feedback here.

**Comment by hannesb** [comment]
This should work (in grid constructor):

`setTimeout(() => this.slickGrid.setSelectedRows([0]), 100);
`

Note: setSelectedRows wants an array of indexes, not entities

HTH
Hannes

**Comment by Nathan2020-0126** [comment]
@hannesb  It works. thank you very much. I used as below
```
 self.prodOrderItemGrid.view.onDataLoaded.subscribe(e => {
                self.prodOrderItemGrid.slickGrid.setSelectedRows([0]);
            });
```
