### ISSUE TITLE
How to config CkFinder in HtmlContentEditor

### ISSUE THREAD

**Issue by huynhvanquy** [volkanceylan/Serenity#4994]
Dear All Pro,
I tried many times configuring CKFinder into HtmlContentEditor but it's really different from the regular MVC I did.

Specifically with regular Mvc, I can easily configure:

![image](https://user-images.githubusercontent.com/9621306/80782875-0864ad80-8ba2-11ea-91d2-d95b2036f574.png)

For Serenity, I can only use the attribute [HtmlContentEditor] or custom with [MyCustomHtmlContentEditor], and the result looks like the image below:

![image](https://user-images.githubusercontent.com/9621306/80783150-efa8c780-8ba2-11ea-9a2b-3467650e9ffc.png)

![image](https://user-images.githubusercontent.com/9621306/80782847-ecf9a280-8ba1-11ea-99bc-d80f6e68d26e.png)

I am really having trouble, please share me your way. Thank you!

@volkanceylan please help me!

**Comment by JohnRanger** [comment]
Hi @huynhvanquy ,

what exactly do you want to achieve?

Do you just want to have an action button after that text field?

With kind regards,

John

**Comment by huynhvanquy** [comment]
> Hi @huynhvanquy ,
> 
> what exactly do you want to achieve?
> 
> Do you just want to have an action button after that text field?
> 
> With kind regards,
> 
> John

Hi @JohnRanger 
I want to upload image, file in CKEditor (using CKFinder or other). Now, i only upload image from url. Thanks!

**Comment by huynhvanquy** [comment]
![image](https://user-images.githubusercontent.com/9621306/93706648-6d6d6f80-fb52-11ea-80ee-a6277960b3c3.png)

Share for those who are in need!

**Comment by Nathan2020-0126** [comment]
@huynhvanquy Did you made it? I also create a MyCustomHtmlContentEditor.ts like yours. So i also need to put ckfinder under **Script** filefolder?
I download the ckfinder from this url https://ckeditor.com/ckfinder/download/#net

**Comment by Nathan2020-0126** [comment]
I got an error like below. What should I need to change?
![image](https://user-images.githubusercontent.com/16734387/99931447-83382480-2d8f-11eb-9e9b-1134f3161549.png)
