### ISSUE TITLE
System.Data.SqlClient.SqlException: 'Must declare the scalar variable "@p1".'

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#4995]
I get the above error in the following code:
.
.
.
var odt = OrderDetailTermsRow.Fields;
data.OrderDetailTerms = connection.List<OrderDetailTermsRow>(q => q
                    .SelectTableFields()
                    .Where(odt.OrderDetailsId.In(query.SubQuery().From(od).Select(od.OrderDetailsId)
                    .Where(od.OrderId == this.OrderID)))
                    );

which is a similar implementation that I have borrowed from the Northwind example:

var o = OrderRow.Fields;
data.Order = connection.TryById<OrderRow>(this.OrderID, q => q
                     .SelectTableFields()
                     .Select(o.EmployeeFullName)
                     .Select(o.ShipViaCompanyName)) ?? new OrderRow();

                var od = OrderDetailRow.Fields;
                data.Details = connection.List<OrderDetailRow>(q => q
                    .SelectTableFields()
                    .Select(od.ProductName)
                    .Select(od.LineTotal)
                    .Where(od.OrderID == this.OrderID));

Can anyone please suggest what needs to be done?

**Comment by edwardch** [comment]
The query should work...

Has the OrderID property definitely been set on the OrderDetailReport class?

Also I see that your have `od.OrderId`, and I think it needs to be `od.OrderID` (capital "d").

**Comment by dviellaris** [comment]
You can try adding an alias to your OrderDetailRow.. it might be using T0 for both tables.
var od = OrderDetailRow.Fields.As("od");

**Comment by reacharihant** [comment]
Thanks for your reverts!

I tried both the aforesaid ideas but to no avail. To confirm, the OrderID is set on the OrderDetailReport class and also have checked the spelling of OrderId (which is lower case in my definition too).

Also, I tried alias but got the same error!!

Don't know where this going wrong!!

**Comment by edwardch** [comment]
Hmmm... Can you open SQL Server profiler in SSMS to see the query that is actually hitting your database? I find that often helps finding out what's going on.

**Comment by reacharihant** [comment]
Ok, will try to do it. Many thanks!!

**Comment by stixoffire** [comment]
@reacharihant I know you closed this - but for future reference you and others - your web.config has a debug level output parameter - set it to debug. Your SQL query will be logged in order to provide some very useful info.
I have used the query generated in the log to troubleshoot what appears to be incorrect or missing ..
From Web Config find or add this 


```
<configuration>
  <appSettings>

<add key="Logging" value="{  File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0,  Level: 'Debug' }" />

     <appSettings>
<configuration>

```
