### ISSUE TITLE
URL hyperlink in form dialog?

### ISSUE THREAD

**Issue by dms2701** [volkanceylan/Serenity#4996]
I have a basic form/table from sergen. I have URLs in the data (i.e. www.domain.com), but when a user clicks it, it only opens the form (it is the ID clm).

Then within the form, it is just plain text and not a hyperlink.

How can I make it a hyperlink to that page?

**Comment by edwardch** [comment]
Try using `[UrlFormatter]` on the property in xyzColumns.cs.

I don't think there's a formatter for editors/forms, since the form is in edit mode of your record already.

**Comment by Zahar661** [comment]
if you need a link in the form, then:
in xyzform.cs 
`[LinkCloseEditor]`

add LinkCloseEditor.ts
```
namespace MyProject {
    @Serenity.Decorators.element("<a target='_blank'>Open</a>")
    export class LinkCloseEditor extends Serenity.StringEditor {

        constructor(element: JQuery) {
            super(element);
        }
        public set value(val: string) {
            if (val != null) {
                    this.element.prop("href", val);
            }
            else {
                this.element.text("-");
            }
        }
        public get value() {
            return this.element.prop("href");
        }
    }
}
```

**Comment by ms4hafiz** [comment]
Hi @Zahar661 
How can we use it xyzColumns.cs that is working. Currently it is not working and if we use in xxDialog.cs but we cannot add any website.

**Comment by Zahar661** [comment]
[UrlFormatter] on the property in xyzColumns.cs.
in xxDialog.cs for editing, different forms

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
