### ISSUE TITLE
Applying less to specific dialogs

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4998]
Hi 

```
.s-Form label.caption {
    margin-bottom: 2px;
    text-align: left;
    flex-basis: 100%;
}

.flex-layout .field {
    flex-wrap: wrap;
}
```

I would like to apply the following less for specific forms but not all forms.
Currently it affects all the forms.

![image](https://user-images.githubusercontent.com/20435849/80988235-70d4b880-8e48-11ea-8f11-9e0bf6d865a4.png)

Thanks

**Comment by ga5tan** [comment]
you can customize specific dialog like this:
.s-Orders-CustomizedQsDialog {
    max-width: 900px;

    > .size {
        width: 900px;
    }

    .caption {
        width: 80px !important;
    }

    .s-DialogToolbar {
        height: 15px;
    }

    .s-Toolbar {
        min-height: 15px;
    }

    .button-inner {
        font-size: 10px;
    }
}
