### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by yankerssnh** [volkanceylan/Serenity#50]
Is sessionState as "SQL server" supported?
I mean standard aspStateDB base in SQL server to store session between IIS instances in farm.

Now farm balance load between servers and Authorization lost very often

**Comment by volkanceylan** [comment]
There is nothing that prevents you from using session state in Serenity, be it inproc or sql. But i strongly recommend avoiding session state. In my applications, session state is always off and i had no problem ever even with 40 server web farms. Forms authentication uses a cookie. If you need a state per user, like shopping cart, you can keep it in db yourself.

**Comment by yankerssnh** [comment]
Ohh, forgot add 
<machineKey validationKey="blablabla" decryptionKey="blablabla" />

to the <system.web>

Now all good!
