### ISSUE TITLE
LinkingSetRelation, how to retrieve certain field. 

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#500]
[DisplayName("Type of the Property"), Size(50)]
        [LookupEditor(typeof(PropertyTypeRow), Multiple = true), ClientSide]//
        [LinkingSetRelation(typeof(ValuationPropertyTypesRow), "ValuationID", "PropertyTypeID")]
        public List<int> ValuationPropertyTypes
        {
            get { return Fields.ValuationPropertyTypes[this]; }
            set { Fields.ValuationPropertyTypes[this] = value; }
        }

PropertyTypeRow has a field named ProperyTypeName, now when I retrieve a record it give me the int array of PropertyTypeID. which is good for showing it in lookup editor, but I want to display them on report, So I have to retrieve the array of ProperyTypeNames.

any suggestion is appreciated.

Regards

**Comment by volkanceylan** [comment]
You may load them with an separate IN query

**Comment by dfaruque** [comment]
I have fixed them by following code
       
 private class MyRetrieveHandler : RetrieveRequestHandler<MyRow>
        {
            protected override void OnReturn()
            {
                base.OnReturn();
                Response.Entity.ValuationPropertyTypeNames = new System.Collections.Generic.List<string>();
                foreach (var PropertyTypeID in Response.Entity.ValuationPropertyTypes)
                {
                    Response.Entity.ValuationPropertyTypeNames.Add(Connection.ById<Entities.PropertyTypeRow>(PropertyTypeID).PropertyTypeName);
                }
        }

IN query sounds great, how can I use IN query here?

**Comment by volkanceylan** [comment]
```cs
var pt = Entities.PropertyTypeRow.Fields;
if (Response.Entity.ValuationPropertyTypes.Count > 0)
Response.Entity.ValuationPropertyTypes.AddRange(Connection.List<Entities.PropertyTypeRow>(
pt.PropertyTypeId.In(Response.Entity.ValuationPropertyTypes);
));
```

**Comment by dfaruque** [comment]
cool. 

thanks.

**Comment by volkanceylan** [comment]
.Select(x => x.PropertyTypeName) at end
