### ISSUE TITLE
how to use RowField

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5001]
I found there is field type RowField, similar to RowListField.
But i don't know how to use it. For RowListField, we can use MasterDetailRelation to define the relation.
For RowField, what kind of mapping we can use?
```
  //[MasterDetailRelation(foreignKey: "WorkcenterTaskConfirmId",MasterKeyField = "SourceDocumentId")]
       // [LinkingSetRelation(typeof(WorkcenterTaskConfirmRow), "field1", "field2")]
**### // what kind of mapping we can use here??**
        public WorkcenterTaskConfirmRow WorkcenterTaskConfirm
        {
            get { return Fields.WorkcenterTaskConfirm[this]; }
            set { Fields.WorkcenterTaskConfirm[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.MaterialMovementRecordId; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.SourceDocumentCode; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public MaterialMovementRecordRow()
            : base(Fields)
        {
        }

        public class RowFields : Mom.Administration.Entities.LoggingAllRow.LoggingAllRowFields
        {
            public GuidField MaterialMovementRecordId;
            public Int16Field MovementType;
            public GuidField SourceDocumentId;
            public Int16Field SourceDocumentKind;
            public StringField SourceDocumentCode;
            public DecimalField PlanQty;
            public DecimalField ActualQty;
            public GuidField UnitId;
            public BooleanField IsCompleted;
            public Int32Field CompleteUserId;
            public DateTimeField CompleteTime;
            public BooleanField IsClosed;
            public Int32Field ClosedUserId;
            public DateTimeField ClosedTime;
            public RowField<WorkcenterTaskConfirmRow> WorkcenterTaskConfirm;
        }
```

**Comment by hannesb** [comment]
Maybe 'UpdatableExtension' (see CustomerRow in Serene template) is what you need.

HTH
Hannes

**Comment by Nathan2020-0126** [comment]
@hannesb  it is not what I need, but it is also a new information for me.  thanks you very much

**Comment by stixoffire** [comment]
@hannesb if I had to guess - I would think it is a single row represented in the xyzRow, but I am not sure of the use case. Although RowFieldList , perhaps in a  for each RowField in RowFieldList - so it might be used internally and just left public . Not sure ..

**Comment by Nathan2020-0126** [comment]
@stixoffire ， Yes, I want to have a single row represented in a xyzRow.  currently I have to add each field in xyzRows. like  below picture
![image](https://user-images.githubusercontent.com/16734387/81999249-2395e980-9687-11ea-88ba-121908b3e4f0.png)
if we can represent the row entity here, it would be much easier
![image](https://user-images.githubusercontent.com/16734387/81999357-6657c180-9687-11ea-9c9b-83ab37114f35.png)

**Comment by stixoffire** [comment]
@Nathan2020-0126 it would need to be ensured that you only had one result returned .. I believe you might be able to do this with an expression and limit to getfirst. Have you tried to use a join on the row ?

**Comment by Nathan2020-0126** [comment]
@stixoffire  thanks for your suggestion. I tried but it didnot work. it is not a urgent issue, and we can use expression attribute on the field(just take a little bit more time), therefor  I close it.

**Comment by Hochmah** [comment]
> @stixoffire ， Yes, I want to have a single row represented in a xyzRow. currently I have to add each field in xyzRows. like below picture ![image](https://user-images.githubusercontent.com/16734387/81999249-2395e980-9687-11ea-88ba-121908b3e4f0.png) if we can represent the row entity here, it would be much easier ![image](https://user-images.githubusercontent.com/16734387/81999357-6657c180-9687-11ea-9c9b-83ab37114f35.png)

That would be really, really useful. It's a pain to redeclare many fields from other row using Expression("OtherTable.Field"). And that happens a lot!

**Comment by stixoffire** [comment]
RowFieldList is a list of the row .
RowField is  a base type used in the RowFields - each one of those elements is a RowField.

Usage is not a row level but a field level.
You are using them in the RowFields class that is contained by the Row Class .

Sergen can autogenerate , as an aside you can write your own autogen tool to do the same or use templates.

If you desire a single row - have you tried simply 
public EmployeeRow MyEmployeeRow
{
  get{ return Fields.MyEmployeeRow[this];} set{Fields.MyEmployeeRow[this] = value;}
}

class RowFields 
{
EmployeeRow,Fields  MyEmployeeRow
}
