### ISSUE TITLE
Permission to specific fields in xxDialog

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5002]
I have a dialog with for example 4 fields on it.
I want to give permission to 2 of the fields for some category of users and the 2 for other type of users. So when a type of user can edit 2 of the fields then they are not able to edit the 2 other fields. 
Searched the existing, but could not find any to help me.

Thank you for the help

**Comment by stixoffire** [comment]
@ms4hafiz  Add your permission level above the fields. Your users need to have those permissions set.
I think you can do this in the formXYZ 
FormXYZ
[Permissions(PermissionKey.Special)]
MyField
