### ISSUE TITLE
Lookup Editor not showing up on Gridview

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#5004]
I have several look up editors on a XYZGrid based on a view. One of those Lookups are not showing up on the gridview , I have isolated down to what I think is the issue but I don't know how to get around the issue.

I have a View based on many joined tables, and one of those tables is my InventoryItemRow in that row the field name is different than my view ,  the field name is ItemName.

[InventoryItemRow ]
```
        [DisplayName("Item Name"), Size(60), NotNull, QuickSearch, LookupInclude, MinSelectLevel(SelectLevel.Details)]
        public String ItemName
        {
            get { return Fields.ItemName[this]; }
            set { Fields.ItemName[this] = value; }
        }

```

[ XYZViewRow ]
From my XYZViewRow  
```
        [DisplayName("Item"), Size(60), NotNull, QuickSearch(SearchType.Contains), QuickFilter(true)]
        [LookupEditor(typeof(Lookups.InventoryItemLookup))]
        public String Item
        {
            get { return Fields.Item[this]; }
            set { Fields.Item[this] = value; }
        }

        [DisplayName("Part Number"), Size(60), QuickSearch(SearchType.Contains), QuickFilter(true)]
        [LookupEditor(typeof(Lookups.InventoryPartLookup))]
        public String PartNumber
        {
            get { return Fields.PartNumber[this]; }
            set { Fields.PartNumber[this] = value; }
        }
```

**Comment by Nathan2020-0126** [comment]
Do you mean the QuickFilter on the grid?

**Comment by hannesb** [comment]
You could include the 'Item' property in XYZColumns.cs and decorate it with the 'FilterOnly' attribute.

HTH
Hannes

**Comment by stixoffire** [comment]
@hannesb Are you suggesting I use expression for Item in XYZRow to declare it [Expression("T0.ItemName"), FilterOnly, NotMapped] and then it should show up on my view page .. take a closer look at my configuration where ItemName is in the column and Item is in the view , the search component does not show up at all in the filterBar.

**Comment by stixoffire** [comment]
@Nathan2020-0126 You specify the IdField - this is not the issue with the lookup editor - I have another lookupeditor that is based on the same table but is used for a partnumber that one shows up just fine. The idfield is ItemId - it does not change for the lookups .. one is by name and the other by number the first one in the row column shows up - the second one does not.

**Comment by stixoffire** [comment]
I am just skipping using the lookup editor  for right now .. the issues still exists.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
