### ISSUE TITLE
Boolean QuickFilter Initial Value not working

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#5005]
Hi there,

I noticed that if you want to use initial values for quickfilters with an boolean editor the value wont be set. I found a workaround to make it work but maybe someone knows what the real problem is?

```
protected getQuickFilters(): Serenity.QuickFilter<Serenity.Widget<any>, any>[] {
			let filters = super.getQuickFilters();
			Q.first(filters, x => x.field == fld.Disabled).init = w => {
				//This is working
				(w as Serenity.LookupEditor).value = "0";
				//This is not working
				(w as Serenity.BooleanEditor).value = false;
			};

			return filters;
		}
```

**Comment by minhhungit** [comment]
@Garozh at this comment I also demo a way to set initial value for filter

https://github.com/volkanceylan/Serenity/issues/5013#issuecomment-631623946

try it ^^

**Comment by Garozh** [comment]
hey thanks for the answer but the solution on top is allready working, but i think the booleanEditor should work also, thats why I opened a new issue

**Comment by volkanceylan** [comment]
Quick filter for boolean fields is a select2 editor, thus it is not false / true
