### ISSUE TITLE
Exception log not working with asp.net core version

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5006]
Hi;

I see that the .net core version serenity is not saving exceptions. Has anyone faced the same issue and how can I make sure it is working.

Thank you

**Comment by djysf** [comment]
@volkanceylan , @ms4hafiz 
Same here..
There is no module nor it's recorded in DB. anybody found any resolution to this?

**Comment by petebr** [comment]
I'm looking for an answer too. It might have something to do with the `StackExchange` exceptional package which gets configured in startup as ` app.UseExceptional();` but I could be completely wrong.

**Comment by petebr** [comment]
I made a tiny step forward following this tutorial
[https://tutexchange.com/logging-errors-in-asp-net-core-3-1-using-stackexchange-exceptional-logger/](url)

But only un-handled exceptions got logged and no styling was present on the log page.
This must be fairly easy to configure properly, can anyone help here?

to `Startup.cs` I added  
``` 
services.AddExceptional(settings =>
            {
                settings.Store.ApplicationName = "my app name";
            });
```
then a new controller 
```
using Microsoft.AspNetCore.Mvc;
using Serenity.Web;
using StackExchange.Exceptional;
using System;
using System.Threading.Tasks;

namespace myapp.Administration.Pages
{
    [PageAuthorize(PermissionKeys.Security)]
    public class ShowErrorsController : Controller
    {
        [Route("Administration/Errors")]
        public async Task Index()
        {
            await ExceptionalMiddleware.HandleRequestAsync(HttpContext).ConfigureAwait(false);
        }

        [Route("Administration/Errors/test")]
        public IActionResult test()
        {
            throw new NotImplementedException();
        }
    }
}
```
in `Administration` module and I got a very basic error log at `myappurl.../Administration/Errors` when hitting the `Administration/Errors/test` end-point, but it doesn't seem fully functional.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
