### ISSUE TITLE
Filter in Lookup Editor

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#5008]
I need filter in lookupeditor i want to show only active records in dropdownlist, I tried
 [LookupEditor(typeof(UserRow),FilterField ="StatusId",FilterValue ="1")] but won't work.I have machine table that contain machineid,machinename,statusid
userId is primary key int data type,user name to be shown in dropdown and statusid is boolean so i want to show only statusid=true,I used lookupscript as well but won't work.
Please help me to solve this issue

**Comment by stixoffire** [comment]
@vinaysalian 

1: Your Value is it a string value ? FilterField = "InActive", FilterValue = false.
There is also an interface IISActiveRow that you can implement , handles a lot of things for you automagically - read the docs.

Here is another example utilizing a string value
        [MasterDetailRelation(foreignKey: "Id", MasterKeyField = "RowId",
            FilterField = "T0.Module", FilterValue = "QuoteRow"), NotMapped, Updatable(false), Insertable(false)]

Just an FYI , there are also Interfaces for soft deletes IUndelete ,

**Comment by vinaysalian** [comment]
Is active is a Boolean value

**Comment by stixoffire** [comment]
@vinaysalian  IsActive is INT16, you can however use boolean for that field and it will still work. IIsDeleted field must be int16 , but isActive works either way - boolean or Int16 as it can only be 0 or 1.

**Comment by minhhungit** [comment]
@vinaysalian This will help you

https://github.com/volkanceylan/Serenity/issues/5013#issuecomment-631623946

**Comment by gfo2007** [comment]
@vinaysalian I think you should create a lookup class and write your query to filter out the records you want. You can then call the lookup class in your LookupEditor. Let me illustrate with an example.

**Lookup Class**

```
using MinRepExtension.LookUps.Entities;
using Serenity.ComponentModel;
using Serenity.Data;
using Serenity.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MinRepExtension.Modules.LookUps.UGLevel
{
    [LookupScript("LookUps.DevelopmentMachineNew", Permission ="?")]
    public class DevelopmentMachineNewLookup : RowLookupScript<MachineRow>
    {
        public DevelopmentMachineNewLookup()
        {
            IdField = "MachineId";
            TextField = "MachineCode";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            //base.PrepareQuery(query);
            var fld = MachineRow.Fields.As("fld");
            var mp = MachinePeriodRow.Fields.As("mp");
            var mc = MachineCategoryRow.Fields.As("mc");

            query
                .Select(fld.MachineId, fld.MachineCode)
                .From(fld)
                .LeftJoin(mp, new Criteria(mp.MachineId) == new Criteria(fld.MachineId))
                .LeftJoin(mc, new Criteria(mc.MachineCategoryId) == new Criteria(fld.MachineCategoryId))
                .Where(new Criteria(mp.SiteId) == 17)
                .Where(new Criteria(mc.MachineCategoryId) == 1)
                .Where(new Criteria(fld.Obsolete) == 0)
                .OrderBy(fld.MachineCode, desc: false)
                .Distinct(true);
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
}
```

**LookupEditor call in Row**

```
[LookupEditor("LookUps.DevelopmentMachineNew")]
```

Hope this helos.

**Comment by stixoffire** [comment]
@vinaysalian 

I went through my project and here is a quick example on a related field ..

MyRow contains a ForiegnKey to SalesPersonId in the Sales person table. InActive is actually a BIT field.  You can do this same thing with the IISActive functionality - but it handles that for you automagically .. with a shortInt (INT16). NOTE CASING IN MY EXAMPLE!

        [DisplayName("Sales Person"), ForeignKey("[dbo].[SalesPerson]", "Id"), LeftJoin("jSalesPerson"), TextualField("SalesPersonFullName")]          
        [LookupEditor(typeof(SalesPersonRow), FilterField = "InActive", FilterValue = false)]
        [Width(100), QuickSearch, QuickFilter(true), UpdatePermission(PermissionKeys.Administration), Placeholder("Admin Can Modify.")]
        public Int32? SalesPersonId
        {
            get { return Fields.SalesPersonId[this]; }
            set { Fields.SalesPersonId[this] = value; }
        }

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
