### ISSUE TITLE
Decorator to Alias values  -1,0,1 in report

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#5009]
Does anyone have an idea how I can create a decorator for a report where I have an integer -1,0, and 1. I want to assign Partial,, Waiting and Complete.

**Comment by JohnRanger** [comment]
Hi @stixoffire,

the easiest way to do this is - if your SQL backend is MS SQL, you can create a calculated field on DB-side which translates the 3 integer values to nvarchar values, holding Partial for -1, Waiting for 0 and Complete for 1.

Regards,

John

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
