### ISSUE TITLE
Serenity default 'admin' user has no ability to grant permissions or roles.

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#501]
I have been able to use the application as admin user before on the machine I originally created the project on. Now that it has been imaged, I have cloned the repository and when I go to interact with the user roles/administration, I cannot assign permissions to roles/users. I haven't touched the code for the Project.Web\Administration module, so I'm not sure why this is happening.

**Comment by volkanceylan** [comment]
Can you check if you have some javascript error in console?

**Comment by jsbUSMC** [comment]
Sorry for the late reply, I had the weekend off. I am receiving an Uncaught type error: cannot read property '0' of undefined in the console. I have taken a screencap of the console for you.

![admin permissions console errors](https://cloud.githubusercontent.com/assets/11762092/14261635/90f805ba-fa7f-11e5-98cc-4b92ae797ebb.png)

**Comment by volkanceylan** [comment]
It seems like failing on some array access. Click on FlowState.Script and try to see at which exact line it fails at. Probably something related to slickgrid

**Comment by jsbUSMC** [comment]
I am not sure where exactly it failed, but I just created a new project and copied over the entire Administration folder for both projects, changed namespaces and transformed templates. Now it works! Thank you for your help
