### ISSUE TITLE
Translation not refreshed-what can suggest?

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5010]
Please help me with this.

I am using the asp.net core version of the platform.
When I translate from source to target language and save but it is not affecting the target language. 
Am i missing anything? **However, it gets affected after I re-run the application using visual studio or stop and start the production server?**
![image](https://user-images.githubusercontent.com/20435849/81819393-816de880-9544-11ea-923b-332ef6d00a82.png)

Thank you

**Comment by karimhyatt** [comment]
I'm getting the same thing all of a sudden. Not sure when it started. All was working well.
