### ISSUE TITLE
Excel Style Filtering is not working

### ISSUE THREAD

**Issue by Asp1993** [volkanceylan/Serenity#5011]
Hello,
I am using below in my grid, but I do not see any filter icon next to column header as mentioned in 
https://serenity.is/docs/startsharp/features/excel-style-filtering

constructor(container: JQuery) {
    super(container);
    new Serenity.HeaderFiltersMixin({
        grid: this
    });
}

Am I missing anything?

**Comment by JohnRanger** [comment]
@Asp1993 ,

just a quick question: Do you have the StartSharp commercial package and your project is derived from the commercial project?

(Because Excel-style filtering is only available within the commercial package).

With kind regards,

John

**Comment by XDDDev** [comment]
Yes we do.
