### ISSUE TITLE
Message : Uncaught typeError : cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5015]
![ERROR](https://user-images.githubusercontent.com/42218266/82404366-1bdf9780-9a2f-11ea-8894-01666b29c663.png)
Hello community !!! Hello community !!! I have a mistake I've been able to fix. I have a mistake I've been able to fix. Send the image and class zyzDialog.cs if anyone can help. 

/// <reference path="../../Common/Helpers/GridEditorDialog.ts" />

namespace SegurosMAPC.BaseDatos **{**

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.panel()
    export class CargaReprocesoDialog extends Serenity.EntityDialog<CargaReprocesoRow, any> {
        protected getFormKey() { return CargaReprocesoForm.formKey; }
        protected getIdProperty() { return CargaReprocesoRow.idProperty; }
        protected getLocalTextPrefix() { return CargaReprocesoRow.localTextPrefix; }
        protected getNameProperty() { return CargaReprocesoRow.nameProperty; }
        protected getService() { return CargaReprocesoService.baseUrl; }
        protected getDeletePermission() { return CargaReprocesoRow.deletePermission; }
        protected getInsertPermission() { return CargaReprocesoRow.insertPermission; }
        protected getUpdatePermission() { return CargaReprocesoRow.updatePermission; }

        protected form = new CargaReprocesoForm(this.idPrefix);

        //  deshabilitar botones        
        protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();

            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "save-and-close-button"), 1);
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "apply-changes-button"), 1);
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);

            if (!this.isEditMode()) {
                let newBtn: Serenity.ToolButton =
                {
                    title: "Confirme Operacion",
                    hint: "Permite reprocesar un Archivo",
                    separator: false,
                    icon: 'fa fa-save text-red',
                    onClick: (e) => {
                          Q.confirm(Q.text('Confirma Reproceso'), function () {
                           e.preventDefault();
                           this.saveAndCloseButton.click();**
                        });
                    }
                }
                buttons.push(newBtn);
            }

            return buttons;
        }
        //
        
        protected updateTitle(): void {
            super.updateTitle();
            this.dialogTitle = 'Reprocesar un Archivo';
        }

    }
}

**Comment by hannesb** [comment]
Use a lambda expression instead of function():

```
...
onClick: (e) => {
                      Q.confirm(Q.text('Confirma Reproceso'), () => {
                       e.preventDefault();
                       this.saveAndCloseButton.click();
                    });
                }
...
```

HTH
Hannes

**Comment by minhhungit** [comment]
Hi @patriciomh1965 , I checked your code

There is a problem at here:

```javascript
Q.confirm(Q.text('Confirma Reproceso'), () => { // at this line you have to use arrow function, it will bound 'this' to parent context
     e.preventDefault();
     this.saveAndCloseButton.click(); // you are using 'this' here, saveAndCloseButton is in parent context
});
```
Next, I see that you want to use **saveAndCloseButton** button, but you removed it before so when you click on it, it will not work

You have to find a way to hide it, not remove it
firstly, you must comment out this line

```javascript
//buttons.splice(Q.indexOf(buttons, x => x.cssClass == "save-and-close-button"), 1);
```
and add this code block:
```javascript
updateInterface() {
    super.updateInterface();
    if (this.saveAndCloseButton) {
        this.saveAndCloseButton.hide();
    }            
}
```

Here is full code, it will work for you:
```javascript
protected getToolbarButtons(): Serenity.ToolButton[] {
    let buttons = super.getToolbarButtons();
    //buttons.splice(Q.indexOf(buttons, x => x.cssClass == "save-and-close-button"), 1);
    buttons.splice(Q.indexOf(buttons, x => x.cssClass == "apply-changes-button"), 1);
    buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
    if (!this.isEditMode()) {
        let newBtn: Serenity.ToolButton =
        {
            title: "Confirme Operacion",
            hint: "Permite reprocesar un Archivo",
            separator: false,
            icon: 'fa fa-save text-red',
            onClick: (e) => {
                Q.confirm(Q.text('Confirma Reproceso'), () => {
                    e.preventDefault();
                    this.saveAndCloseButton.click();
                });
            }
        }

        buttons.push(newBtn);
    }

    return buttons;
}

updateInterface() {
    super.updateInterface();
    if (this.saveAndCloseButton) {
        this.saveAndCloseButton.hide();
    }            
}
```
But wait, I also see that you are trying to implement confirming feature for buttons, I know a way to do it, I think it is more elegant:

```javascript
protected getToolbarButtons(): Serenity.ToolButton[] {
    let btns = super.getToolbarButtons();
    var btnSave = Q.first(btns, x => x.cssClass == "save-and-close-button");
    var btnApply = Q.first(btns, x => x.cssClass == "apply-changes-button");
    var oldSaveClick = btnSave.onClick;
    var oldApplyClick = btnApply.onClick;
    btnSave.onClick = e => { this.confirmBeforeSave(oldSaveClick, e); };
    btnApply.onClick = e => { this.confirmBeforeSave(oldApplyClick, e); };
    return btns;
}
private confirmBeforeSave(oldEvt, e) {
    Q.confirm("Here is confirm message?", () => {
        oldEvt(e);
    });
}
```

Let me know if it work for you

**Comment by patriciomh1965** [comment]
It worked well !!! Thanks for the help.

**Comment by patriciomh1965** [comment]
/// <reference path="../../Common/Helpers/GridEditorDialog.ts" />

namespace SegurosMAPC.BaseDatos {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.panel()
    export class CargaReprocesoDialog extends Serenity.EntityDialog<CargaReprocesoRow, any> {
        protected getFormKey() { return CargaReprocesoForm.formKey; }
        protected getIdProperty() { return CargaReprocesoRow.idProperty; }
        protected getLocalTextPrefix() { return CargaReprocesoRow.localTextPrefix; }
        protected getNameProperty() { return CargaReprocesoRow.nameProperty; }
        protected getService() { return CargaReprocesoService.baseUrl; }
        protected getDeletePermission() { return CargaReprocesoRow.deletePermission; }
        protected getInsertPermission() { return CargaReprocesoRow.insertPermission; }
        protected getUpdatePermission() { return CargaReprocesoRow.updatePermission; }
        
        protected form = new CargaReprocesoForm(this.idPrefix);
             

        protected getToolbarButtons(): Serenity.ToolButton[] {
            let buttons = super.getToolbarButtons();
            //buttons.splice(Q.indexOf(buttons, x => x.cssClass == "save-and-close-button"), 1);
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "apply-changes-button"), 1);
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "delete-button"), 1);
            if (!this.isEditMode()) {
                let newBtn: Serenity.ToolButton =
                {
                    title: "Confirme Operacion",
                    hint: "Permite reprocesar un Archivo",
                    separator: false,
                    icon: 'fa fa-save text-red',
                    onClick: (e) => {
                        Q.confirm(Q.text('Confirma Reproceso'), () => {
                            e.preventDefault();
                            this.saveAndCloseButton.click();
                        });
                    }
                }
                buttons.push(newBtn);
            }
            return buttons;
        }
        updateInterface() {
            super.updateInterface();
            if (this.saveAndCloseButton) {
                this.saveAndCloseButton.hide();
            }
        }
        
        protected updateTitle(): void {
            super.updateTitle();
            this.dialogTitle = 'Reprocesar un Archivo';
        }

    }
}

**Comment by patriciomh1965** [comment]
Code Applied !!
