### ISSUE TITLE
what is ss and arrayAddRange ?

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5018]
When I looking into the source code, i found there is a ss and arrayAddRange?
I don't understand what is ss and arrayAddRange? how to use them in typescript.
![image](https://user-images.githubusercontent.com/16734387/82526715-37e65480-9b67-11ea-829e-7c4e8620e43d.png)

**Comment by dfaruque** [comment]
Before typescript, serenity was based on Salterelle (A C# to JS compiler). I think this `ss` is from the salterelle's compiled JS.

**Comment by Nathan2020-0126** [comment]
I soloved my problem with below code.
```
private _filterLines: Serenity.FilterLine[];

        get filterLines() {
            return this._filterLines;
        }

        set filterLines(value: Serenity.FilterLine[]) {
            if (this._filterLines !== value) {
                this._filterLines = value;
                (ss as any).clear(this.filterBar.get_store().get_items());
                (ss as any).arrayAddRange(this.filterBar.get_store().get_items(), value);
                this.filterBar.get_store().raiseChanged();

            }
        }
```

**Comment by Nathan2020-0126** [comment]
But i still don't understand how is (ss as any).clear() and (ss as any).arrayAddRange working

**Comment by dfaruque** [comment]
if you type `ss` in the browser console you will be able to find the all ss methods as well as definition.

![image](https://user-images.githubusercontent.com/16621563/82647150-967b0380-9c37-11ea-8698-631c8d12a049.png)

To get the definition you might type `ss.clear` and press enter

**Comment by Nathan2020-0126** [comment]
@dfaruque thanks very much
