### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by rcmsoftwaredevelopment** [volkanceylan/Serenity#5019]
Hi folk, hope everyone is safe and sound. I am frustrated at the lack of progress,  I signed up to StartShart about 24 months ago with a  6 month subscription with a project that went well.  I am possibly looking at using Serenity or StartSharp again and there are a few grid functionality which I would use which came out about 11 months ago but when I look at the demo website I am some what disappointed at the amount of progress that has been made unless this doesn't have the latest source code.  There are no new modules and I was expecting more work being done on the feature list such as the slick grid rewrite, to do list, and the mobile framework.  I can see there are other frameworks which are possibly more functional but cost a lot more.  I would like to stick with serenity  but need to know if and what imminent functionality is coming out soon as in 1month - 6 months.  Thanks Ray

**Comment by kilroyFR** [comment]
May be it's not a visual widget visible in the demo but Core3.1 is major update and hiding lot of stuffs/time.
I am personnally more interested in new stuffs scheduled in the next months for Startsharp users like me. So far everything being added recently is available to everyone.
