### ISSUE TITLE
Editor  [HtmlContentEditor]

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5021]
Hello community ... I am using the editor [HtmlContentEditor]. I have a file whose lines are very large, when entering the editor the line scrolls down. Is it possible that the line is kept in a single position using scroll?

![Editor](https://user-images.githubusercontent.com/42218266/82721244-6b210480-9c89-11ea-82bc-df9fb0b33eff.jpg)

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform

**Comment by minhhungit** [comment]
@patriciomh1965 

Create a custom html editor which extends from `Serenity.HtmlContentEditor` like this link

https://github.com/volkanceylan/Serenity/issues/4793#issuecomment-605315165

then use ckeditor addCss method like bellow:

```typescript
protected getConfig(): Serenity.CKEditorConfig {
       var config = super.getConfig();

       //
       // --> something else here
       //

       var CKEDITOR = window['CKEDITOR'];
       CKEDITOR.addCss('p { white-space: nowrap;}');

       return config;
}
```
demo: 
![image](https://user-images.githubusercontent.com/2279508/96182219-5d815980-0f5f-11eb-91a9-113c35f158bf.png)

**Comment by patriciomh1965** [comment]
Thank you very much my friend !!
