### ISSUE TITLE
How to display column dividers?

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#5023]
Hello everyone,

How can I show vertical lines like in the image?

Thank you!

![image](https://user-images.githubusercontent.com/11929923/82849616-ad835500-9ec6-11ea-98a3-c1cf70245b37.png)

**Comment by kilroyFR** [comment]
Try to add this in your site.less file

```
.slick-cell {
  color: #000;
  padding: 1px 4px 0 4px;
  border-style: solid solid solid none;
  border-bottom-color: #e7e7e7;
}
```

**Comment by minhhungit** [comment]
for specific column, you can add attribute [CssClass("something")] on Columns.cs fields
and combine with @kilroyFR 's answer your grid will has border

something like this

```css
.something.slick-cell {
   // ....
}
```

**Comment by ArsenioInojosa** [comment]
> Try to add this in your site.less file
> 
> ```
> .slick-cell {
>   color: #000;
>   padding: 1px 4px 0 4px;
>   border-style: none solid none none;
>   border-bottom-color: #e7e7e7;
> }
> ```

Thanks to both.

It worked perfectly.
