### ISSUE TITLE
How to set the DateTo for a QuickFilter on a DateTime field?

### ISSUE THREAD

**Issue by axMAS** [volkanceylan/Serenity#5024]
Hi,

how to set the _DateTo_ for a QuickFilter on a DateTime field?
![grafik](https://user-images.githubusercontent.com/54072926/82890846-20371380-9f4d-11ea-99af-c38a3255a30d.png)
The current code only set the _DateFrom_.
```
Q.first(filters, x => x.field == fld.CalendarDay).init = w => {
          (w as Serenity.DateEditor).value = "today";
};
```

Thank you!

Regards
axMAS

**Comment by arunkumar12712** [comment]
Q.first(filters, x => x.field == fld.InTime).init = w => {
                var date = new Date();
                // w is a reference to the editor for this quick filter widget
                // here we cast it to DateEditor, and set its value as date.
                // note that in Javascript, months are 0 based, so date below
                // is actually 2016-05-01
                (w as Serenity.DateEditor).valueAsDate = new Date(date.getFullYear(), date.getMonth(), 1);

                // setting start date was simple. but this quick filter is actually
                // a combination of two date editors. to get reference to second one,
                // need to find its next sibling element by its class
                let endDate = w.element.nextAll(".s-DateEditor").getWidget(Serenity.DateEditor);
                endDate.valueAsDate = new Date(date.getFullYear(), date.getMonth() + 1, 0);
            };
