### ISSUE TITLE
RCL library and Serenity

### ISSUE THREAD

**Issue by petstrani** [volkanceylan/Serenity#5025]
I want to use  Serene in RCL library. Does anyone have any experience how to do that?

**Comment by kilroyFR** [comment]
What do you mean by RCL ? Razor ?

**Comment by petstrani** [comment]
RCL means Razor Class Library. For particular customer I would like to extend functionality of main web application. So I would like to save Serenity model with view (contents that I get with sergen)  in RCL library and use it in my main application. 
I can prepare classic razor page or view (without Serenity) and use it in main application, but I would like to use Serenity. I think that this is impossible, because some javascript objects does not register in main app,

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
