### ISSUE TITLE
Send client Error Message in FileUpload

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#5026]
Hello All 
I Use FileuploadEditor in one of My Form and  I want to Inform user when he Upload a file Larger than MaxSize I defined for FileUploadEditor.
Does anybody knows how to NotifyError a message in this  condition?

**Comment by hannesb** [comment]
Check your maxAllowedContentLength setting in Web.config. Maybe you are running against that limit and not the one given by MaxSize.

HTH
Hannes

**Comment by MaziarSangi** [comment]
@hannesb 
I want to show size limit to Inform user which size of file/files should  he choose for uploading.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
