### ISSUE TITLE
Sign in with Google Account

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#5027]
How to change Authentication Method for all services and how to use gmail login token to call all webservices(instead of ordinary cookie returned by serenity Login Service)

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
