### ISSUE TITLE
LDAP connection - table users

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#5028]
Hello,

In an LDAP/Active Directory connection the user is automatically created in the Users table?
In my application it is not being created. What could be the problem?

Thx
BR

**Comment by stixoffire** [comment]
@teafmartins Have you looked at the example here in the forums for Active Directory - mine is working perfectly using the example in this forum.

I used the code located here [Active Directory Authentication](https://github.com/volkanceylan/Serenity/issues/1134)

This is issue #1134

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
