### ISSUE TITLE
 Read the lines of a grid to update a status

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5029]
Hello community. I have the following requirement: I need to approve all the lines of the grid with the button [Approve lines]. Reviewing the examples I was able to program the following, but it doesn't work for me. Could someone help me with a problem. Thank you.

Aqui les presento mi xyzGrid.ts :

namespace SegurosMAPC.BaseDatos {

    import fld = CargaElePendienteRow.Fields;

    @Serenity.Decorators.registerClass()
    export class CargaElePendienteGrid extends Serenity.EntityGrid<CargaElePendienteRow, any> {
        protected getColumnsKey() { return 'BaseDatos.CargaElePendiente'; }
        protected getDialogType() { return CargaElePendienteDialog; }
        protected getIdProperty() { return CargaElePendienteRow.idProperty; }
        protected getInsertPermission() { return CargaElePendienteRow.insertPermission; }
        protected getLocalTextPrefix() { return CargaElePendienteRow.localTextPrefix; }
        protected getService() { return CargaElePendienteService.baseUrl; }

        private pendingChanges: Q.Dictionary<any> = {};
        private grid: Serenity.IDataGrid;
     
        constructor(container: JQuery) {
            super(container);                 
        }

        getButtons() {
            var buttons = super.getButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1); // QUITAR BOTON NUEVO
            //
            buttons.push({
                title: "Aprobar Lineas",
                hint: "Permite dejar lista las lineas para ser mapeadas",
                //  separator: false,
                icon: 'fa fa-check-circle text-blue',
                onClick: (e) => {
                    Q.confirm(Q.text('Confirma Aprobacion'), () => {
                        e.preventDefault();

                        //
                        var enumerator = Q.DeepClone(pendingChanges).GetEnumerator();
                        int done = 0;
                        int total = pendingChanges.Count;

                        Action saveNext = null;
                        saveNext = delegate()
                        {
                            if (!enumerator.MoveNext()) {
                                Refresh();
                                return;
                            }
                            var pair = enumerator.Current;
                            var c = Q.DeepClone(pair.Value);
                            entity.KeyProLine = pair.Key;
                            CargaElePendienteAprobarService.Update(
                            {
                                EntityId =item.KeyProLine,
                                Entity = c
                            }, response => {
                                pendingChanges.Remove(pair.Key);
                                Q.NotifyInfo((++done) + " / " + total + " Estan aprobadas ...");
                                saveNext();
                            });
                        };                                                            
                        //
                    });
                }
            });

            return buttons;
        }
        //

                
        // busquedas
        protected getQuickSearchFields():
            Serenity.QuickSearchField[] {
            return [
                { name: "", title: "Todo" },
                { name: "ProcesoNumero", title: "Proceso" },
                { name: "FechaProceso", title: "Periodo" },
                { name: "NombreEvento", title: "Evento" },
                { name: "CetDescripcion", title: "Etapa" }
            ];
        }

        // filtros
        protected onViewSubmit(): boolean {
            if (!super.onViewSubmit()) {
                return false;
            }
            let request = this.view.params as Serenity.ListRequest;
            request.Criteria = Serenity.Criteria.and(request.Criteria, [['mst_estado_carga_ele'], '=', 1]); //Pendiente de Aprobacion
            return true;
        }
        //

        //  APROBACION POR LINEAS
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, {
                field: 'APROBAR',
                name: '',
                format: ctx => '<a class="inline-action aprobar" title="APROBAR">' +
                    '<i class="fa fa-cogs text-green"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });
            return columns;
        }
        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();
                // ACCION APROBAR                
                if (target.hasClass('aprobar')) {
                    var valor = item.KeyProLine;
                    //  Q.warning(valor);

                    Q.confirm('Esta seguro aprobar la linea ?', () => {
                        var $this = this;
                        // 
                        var c = <CargaElePendienteAprobarRow>{};                       
                        CargaElePendienteAprobarService.Update({
                            EntityId: item.KeyProLine,
                            Entity: c
                        }, response => {                             
                                window.setTimeout(() => Q.notifySuccess(Q.text('Linea Aprobada')), 0);
                                window.document.location.reload(true);
                        });
                    });
                }
                // ACCION VER DETALLE
                else if (target.hasClass('view-details')) {
                    this.editItem(item.KeyProLine);
                }
            }
        }
        //

    }
}
![grilla](https://user-images.githubusercontent.com/42218266/83289889-bc625400-a1b3-11ea-96eb-2ced5deb374b.png)

THE xyzRepository.cs repository:

namespace SegurosMAPC.BaseDatos.Repositories
{
    using SegurosMAPC.BaseDatos.Entities;
    using Serenity;
    using Serenity.Data;
    using Serenity.Services;
    using System;
    using System.Data;
    using MyRow = Entities.CargaElePendienteAprobarRow;

    public class CargaElePendienteAprobarRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { }
        private class MyListHandler : ListRequestHandler<MyRow> { }

        // APROBAR POR LINEA
        private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                Row.EstadoCargaEle = 2; // estado Carga ELE Aprobado
                Row.EstadoMapeo = 4; // estado mapeo Pendiente Aprobación
            }
        }
        //
    }
}

**Comment by arunkumar12712** [comment]
please check this may be help you.
https://serenity.is/demo/BasicSamples/CancellableBulkAction

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
