### ISSUE TITLE
Serene.Script Interception request

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#503]
How to do it

**Comment by 107295472** [comment]
Gender   The database does not have this field, how to determine the gender

**Comment by wdhodges** [comment]
The gender is an enum value

**Comment by 107295472** [comment]
Employees  Without this field, the data is fake.

**Comment by 107295472** [comment]
See enumeration value, but how to judge this data is a man

**Comment by volkanceylan** [comment]
There is no gender info in employees, so i used a workaround.
