### ISSUE TITLE
update serenity after removing somedata column from sql

### ISSUE THREAD

**Issue by snur1996** [volkanceylan/Serenity#5031]
I made some changes from sql server..I removed some data coloum from there.After that I try to run serenity project I get some errors about this changes.It can not find this deleted coloums.How can ı solve this and update coloums in project?

**Comment by edwardch** [comment]
It's advisable to put all database schema changes into migrations, including removing columns. Unless you already have another way of maintaining your database schema.

First add a migration to remove the column, with the following code:
```cs
Delete.Column("OldColumn").FromTable("XYZ");
```

Then remove the references to your OldColumn inside
* xyzRow.cs
* xyzForm.cs
* xyzColumns.cs

You'll want to rebuild & run your project, and run T4 transformations if you're on an older version of Serenity.

That's pretty much it, unless you have references to your OldColumn inside other helpers, which your IDE will complain about when you try to build and run your project anyway.

HTH.
Edward

**Comment by stixoffire** [comment]
@snur1996   @edwardch 
You can also run Sergen - as long as you have KDiff3 configured in your options .. you can then edit and save or discard changes ..

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
