### ISSUE TITLE
Can't auto open a closed connection that was previously open!

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5033]
I met a very strange problem. What's the problem?
The function is called by 4 times, the first 3 times  are running successfully, but the last time is failed.
![image](https://user-images.githubusercontent.com/16734387/83485891-92be6b00-a4da-11ea-8dae-31260e4464e6.png)

**Comment by stixoffire** [comment]
@Nathan2020-0126 
I am not sure what you mean by the function is called 4 times - which function the main function or the encapsulated function varqualityIssueList ?

However I can tell you where your problem most likely comes from (as I have had this error )  .. your code seems to be fine to a point.


Enable your Logging in the web.config ..
Look at your query that is in the applog .. run it manually in your Database query editor with the supplied parameters and values in the applog .

What you will find is that you have a null result or null parameter or an error result of some sort that closes you SQL connection and makes it unusable. 

The SQL connection has been made toast - by the sql error ..

**Comment by Nathan2020-0126** [comment]
@stixoffire  thanks very much. I tried as you suggested. 
```
 public Decimal Count(IDbConnection connection, DateRangeDto dateRangeDto, BaseCriteria criteria = null)
        {

            var fld = MachineIssueRow.Fields;
            dateRangeDto.EndDate = dateRangeDto.EndDate.Value.AddDays(1);

            BaseCriteria baseCriteria = fld.IsActive == 1;
            baseCriteria = baseCriteria && criteria;

            baseCriteria = baseCriteria && fld.InsertDate >= (DateTime)dateRangeDto.StartDate && fld.InsertDate < (DateTime)dateRangeDto.EndDate;

// below code is running successfully
            SqlQuery query = new SqlQuery().Select(Sql.Count()).Where(baseCriteria).From(fld);
            Decimal r = connection.Query<Decimal>(query).Single();

//below code is running failed, Error: Cannot auto open a closed connection that was previously open
            Decimal count = connection.Count<MachineIssueRow>(baseCriteria);
            return count;
        }
```

**Comment by Nathan2020-0126** [comment]
my problem is sloved with using SqlQuery. But i don't know why.  I used the same baseCriteria in connection.Query and connection.Count. but Query works and Count didnot work

**Comment by stixoffire** [comment]
@Nathan2020-0126 
Glad you resolved the issue ..

When you set debug to true in your webconfig , your app_data\log folder will contain a log of the query that was generated .. that query placed into Management Studio [SQL Server] or Workbench [MySQL] would give you the information that will define why the one query did not work .. it must be malformed.
