### ISSUE TITLE
How to disable deletion on a joined masterDetailRelation?

### ISSUE THREAD

**Issue by Garozh** [volkanceylan/Serenity#5036]
Hey there,

I have the following problem. I m using a detailRow where I'm joining the masterRow and with the help of the masterRow I'm creating a MasterDetailRelation on another detail row. I can easily show and edit those fields of the joined masterDetailList, but when I delete the first detailRow my masterDetailRow is also deleted, which shouldnt happen.

//Joined field
`		#region Automat
		[DisplayName("Automat")]
		[LeftJoin("jAutomat", "Automat", "Id")]
		[LookupEditor(typeof(AutomatRow))]
		public Int32? AutomatId { get { return Fields.AutomatId[this]; } set { Fields.AutomatId[this] = value; } }
		public partial class RowFields { public Int32Field AutomatId; }
		#endregion AutomatId`

//masterDetailList which is also deleted on original row deletion
`		[DisplayName("Businesshours"), MasterDetailRelation(foreignKey: "AutomatId", MasterKeyField = "AutomatId"), NotMapped]
		public List<BusinessHoursRow> BusinessHoursList
		{
			get { return Fields.BusinessHoursList[this]; }
			set { Fields.BusinessHoursList[this] = value; }
		}`

**Comment by stixoffire** [comment]
How is your database configured on Delete of detail row are you deleting the PrimaryTableRecord ?

**Comment by Garozh** [comment]
Hi @stixoffire,

my database has no cascade delete neither on one of the 2 detail tables and also not on the master table. To explain it a little bit more my primary row is a detailRow of my parent table "AutomatRow", which i LeftJoin (see example above). And then with that left joined parent Id, I join the detail table "BusinessHours" as MasterDetailRelation.

And when I delete my primary row, my second detail row "BusinessHours" is also deleted

**Comment by stixoffire** [comment]
@Garozh 

So you have 3 Tables ..
AutomatParent
AutomatChild  
BusinessHours
A table diagram would be helpful if this is not the case ..

When you delete the AutomatId of the child the business hours gets deleted as well, which should be done as those are related to the row you are deleting - or they will be orphaned , if you have them related in some other ways and need to preserve them, then  you might need to add a constraint in your MasterDetailRelation I think this should work but no sure ..

Try Adding this  ForceCascadeDelete = false:
```
MasterDetailRelation(foreignKey: "AutomatId", MasterKeyField = "AutomatId" , ForceCascadeDelete = false)

```

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
