### ISSUE TITLE
How to get the HTML report content

### ISSUE THREAD

**Issue by Hochmah** [volkanceylan/Serenity#5037]
I have this button below that generates a HTML report. Instead of opening the report in the browser, I need to get its result as a variable.

` buttons.push(Common.ReportHelper.createToolButton({`
`    title: 'Enviar',`
`    hint: 'Enviar Email Relatório Clipping',`
`    cssClass: 'mail-button',`
`    reportKey: 'Default.MateriasReport',`
`    extension: 'html',`
`    getParams: () => ({`
`        request: Q.deepClone(this.getView().params) as Serenity.ListRequest`
`    })`
`}));`

I really appreciate any direction. I'm stuck on this for days.

**Comment by volkanceylan** [comment]
You should get the file content on server side, not client side, i guess you are trying to attach that to an e-mail which you should do on server side.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
