### ISSUE TITLE
Where to override client alert boxes?

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#5038]
Hi there,
I was wondering where alert boxes are called for alert boxes from server side errors and throws. Was thinking of implementing my own solution.

Best regards,
Marcus

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
