### ISSUE TITLE
How to use IDependencyRegistrar in .net Core

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5039]
I want to change the default config function as descriped in  [user mannual](https://serenity.is/docs/service_locator/idependencyregistrar_interface).

but it seems IDependencyRegistrar  cannot be use in .net core version.  
![image](https://user-images.githubusercontent.com/16734387/83755153-b41c8400-a69f-11ea-81a0-493c13d3db7f.png)

How to do it in .net core?

**Comment by welcometoall** [comment]
Did you check [Migrating to ASP.NET Core](https://serenity.is/blog/2020/04/12/migrating-dotnetcore)

**Comment by Nathan2020-0126** [comment]
@welcometoall  I checked the document, but there is no helpful information.

**Comment by Nathan2020-0126** [comment]
I guess in .net core, we should use 
```
services.AddSingleton<IConfigurationRepository, Serenity.Configuration.AppSettingsJsonConfigRepository> ();
```
in ConfigureServices.
