### ISSUE TITLE
Excel Yükleme Hatası

### ISSUE THREAD

**Issue by fatihsimsekk** [volkanceylan/Serenity#5041]
Merhabalar 
Ben tabloma excelden veri almaya çalışıyorum BasicSamples  ProductExcelImport daki demoyu kullanarak yaptım fakat dosyayı seçiyorum upload ediyor ama 
"var worksheet = ep.Workbook.Worksheets[0];" bu satırda hata veriyor hatada 
"System.IndexOutOfRangeException: 'Worksheet position out of range.'" acaba ayrı bir yerde yapmam gereken başka bir işlem mi var.

yardımlarınız için şimdiden teşekkürler.

**Comment by volkanceylan** [comment]
In .NET Core worksheet indexes starts from 1 for EPPlus
