### ISSUE TITLE
 Excel Upload Error

### ISSUE THREAD

**Issue by fatihsimsekk** [volkanceylan/Serenity#5042]
Hello
I am trying to import data from excel to my table. I did it using the demo in BasicSamples ProductExcelImport, but I select the file, it is uploading but
"var worksheet = ep.Workbook.Worksheets [0];" error in this line error
"System.IndexOutOfRangeException: 'Worksheet position out of range." "I wonder if there is another process I need to do in a separate place.

thanks for your help in advance.

**Comment by RouteTech** [comment]
Try
var worksheet = ep.Workbook.Worksheets.First();

**Comment by fatihsimsekk** [comment]
then the error is 
"System.InvalidOperationException: 'Sequence contains no elements'"
it turns into

**Comment by edwardch** [comment]
Have you tried setting a breakpoint and inspecting the variables?

You'll want to hover over ep.Workbook.**Worksheets**

This will help you find issues like if the file is not correctly loaded to the ExcelPackage, and also double check your Excel file has valid data/is not corrupt.

**Comment by arunkumar12712** [comment]
try this  

ExcelPackage ep = new ExcelPackage();
 using (var fs = new FileStream(UploadHelper.DbFilePath(Row.FileName), FileMode.Open, FileAccess.Read))
                        ep.Load(fs);
                    var worksheet = ep.Workbook.Worksheets[1];

**Comment by fatihsimsekk** [comment]
thank you solved the problem
