### ISSUE TITLE
Left Join on 1 to 1 (table and view) worked only once and after that its not in select statment.

### ISSUE THREAD

**Issue by 04071967** [volkanceylan/Serenity#5043]
Hi

I have BookingHRow as a Table
and BookingDispatchStatus as a View on a (1 to 1 relation)

in BookingHRow.cs

    [LeftJoin("bds", "BookingDispatchStatus", "bds.[pkey] = T0.[pkey]")]
    public sealed class BookingHRow : Row, IIdRow
    {
...
        [DisplayName("Weight Status"), Expression("bds.[WeightStatus]")]
        public String WeightStatus
        {
            get { return Fields.WeightStatus[this]; }
            set { Fields.WeightStatus[this] = value; }
        }

        [DisplayName("Qty Status"), Expression("bds.[QtyStatus]")]
        public String QtyStatus
        {
            get { return Fields.QtyStatus[this]; }
            set { Fields.QtyStatus[this] = value; }
        }

        [DisplayName("Booking Flag"), Expression("bds.[StatusFlag]")]
        public String StatusFlag
        {
            get { return Fields.StatusFlag[this]; }
            set { Fields.StatusFlag[this] = value; }
        }

This got compiled and Run for fist time, but never brought value of StatusFlag from backend
From profiler could see that its not part of select statement.

Then did some modification in the view

Now Serenity does not sends BookingDispatchStatus in the select statement.

**Comment by stixoffire** [comment]
@04071967 

How is T0.pkey being selected is it in your BookingHRow ?

You can't join on what is not available to join .

**Comment by absaakash1967** [comment]
Hello stixoffire

Thanks for taking interest in my question.

Yes BookingHRow do have T0.pkey 

i have not pasted full BookingHRow 

As mentioned in my question, this did compiled and gave me result for the first time, but after changing the view definition in SQL it stopped referring to it. Don't know why,
