### ISSUE TITLE
 Problem displaying information in MasterDetailRelation

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5044]
I have the following requirement: I am opening a new Dialog ... 
Where I call a class to show some data, then this class does a MasterDetailRelation to another class. 
The problem that the last class does not show the information. I attach the images and the classes involved: 
If you know how to do it, you can help me with that. 
![p1](https://user-images.githubusercontent.com/42218266/83954657-1baa0f00-a819-11ea-8111-3be82dfabf1b.png)
![p2](https://user-images.githubusercontent.com/42218266/83954658-1d73d280-a819-11ea-987c-f2114cda7b94.png)

MapeoPendienteGrid :
==============
namespace SegurosMAPC.BaseDatos {
    
    @Serenity.Decorators.registerClass()
    export class MapeoPendienteGrid extends Serenity.EntityGrid<MapeoPendienteRow, any> {
        protected getColumnsKey() { return 'BaseDatos.MapeoPendiente'; }
        protected getDialogType() { return MapeoPendienteDialog; }
        protected getIdProperty() { return MapeoPendienteRow.idProperty; }
        protected getInsertPermission() { return MapeoPendienteRow.insertPermission; }
        protected getLocalTextPrefix() { return MapeoPendienteRow.localTextPrefix; }
        protected getService() { return MapeoPendienteService.baseUrl; }

        private pendingChanges: Q.Dictionary<any> = {};

        constructor(container: JQuery) {
            super(container);                       
        }

        getButtons() {
            var buttons = super.getButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1); // QUITAR BOTON NUEVO
                        
            return buttons;
        }

       
        /// busquedas
        protected getQuickSearchFields():
        Serenity.QuickSearchField[] {
        return [
            { name: "", title: "Todo" },
            { name: "ProcesoNumero", title: "Proceso" },
            { name: "FechaProceso", title: "Periodo" },
            { name: "NombreEvento", title: "Evento" },
            { name: "CetDescripcion2", title: "Etapa" }
            ];
        }

        // filtros
        protected onViewSubmit(): boolean {
            if (!super.onViewSubmit()) {
                return false;
            }
            let request = this.view.params as Serenity.ListRequest;
            request.Criteria = Serenity.Criteria.and(request.Criteria, [['mst_estado_mapeo_ele_isol'], '=', 3]); // lineas mapeadas pendiente de aprobacion
            return true;
        }
        //

        //  APROBACION POR LINEAS
        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, {
                field: 'APROBAR',
                name: '',
                format: ctx => '<a class="inline-action aprobar" title="Aprobar Linea para la etapa inyeccion ISOL">' +
                    '<i class="fa fa-cogs text-green"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            columns.splice(1, 0,
                {
                    field: 'EDITAR',
                    name: '',
                    format: ctx => '<a class="inline-action editar" title="EDITAR">' +
                        '<i class="fa fa-pencil text-red"></i></a>',
                    width: 24,
                    minWidth: 24,
                    maxWidth: 24
                });
            return columns;
        }
        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var estado = item.EstadoMapeo;
            if (estado == 4) { Q.notifyWarning("La linea ya se encuentra OK"); return; }  // linea aprobada
            var target = $(e.target);

            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();
                // ACCION APROBAR                
                if (target.hasClass('aprobar')) {
                    var valor = item.KeyProLine;
                    //  Q.warning(valor);

                    Q.confirm('Esta seguro aprobar la linea ?', () => {
                        var $this = this;
                        // 
                        var c = <MapeoAprobarRow>{};
                        MapeoAprobarService.Update({
                            EntityId: item.KeyProLine,
                            Entity: c
                        }, response => {
                            window.setTimeout(() => Q.notifySuccess(Q.text('Linea Aprobada')), 0);
                            window.document.location.reload(true);
                        });
                    });
                }
                if (target.hasClass('editar')) {
                    var valor = item.CodEvento;
                    //Q.warning(valor);
                    // BAJAS
                    if (valor == 3 || valor == 4 || valor == 8 || valor == 10 || valor == 11 || valor == 13) {
                        var $this = this;
                        var dlg3 = new MapeoBajasDialog();
                        this.initDialog(dlg3);
                        dlg3.loadEntityAndOpenDialog(<MapeoBajasRow>{
                            KeyProLine: item.KeyProLine,
                            ProcesoNumero: item.ProcesoNumero,
                            FechaProceso: item.FechaProceso,
                            CodEvento: item.CodEvento,
                            NroContrato: item.NroContrato,                            
                            CodMaterial: item.CodMaterial,
                            FecSuscripcion: item.FecSuscripcion,
                            FecFinContrato: item.FecFinContrato,
                            EstadoMapeo: item.EstadoMapeo
                        });
                        // titulos
                        if (valor == 3) { dlg3.dialogTitle = 'Baja por Mera Tenencia (WS Baja)' }
                        else if (valor == 4) { dlg3.dialogTitle = 'Baja por Término de contrato(WS Baja)' }
                        else if (valor == 8) { dlg3.dialogTitle = 'Baja Opción Vencida (WS Baja)' }
                        else if (valor == 10) { dlg3.dialogTitle = 'Baja por Siniestro Pérdida Total  (WS Baja)' }
                        else if (valor == 11) { dlg3.dialogTitle = 'Baja por Modificaciones (WS Baja)' }
                        else if (valor == 13) { dlg3.dialogTitle = 'Baja de Seguro Cliente (Baja)' }
                    }
                }
            }
        }
        //

    }
}

MapeoBajasRow : 
===========

namespace SegurosMAPC.BaseDatos.Entities
{
    using SegurosMAPC.Modules.BaseDatos.Lookups;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("BaseDatos"), Module("BaseDatos"), TableName("[dbo].[vw_monitor_lineas]")]
    [DisplayName("Proceso Diario"), InstanceName("Proceso Diario")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class MapeoBajasRow : Row, IIdRow
    {
        [Insertable(false), Updatable(false)]
        [DisplayName("Key ProLine"), Column("key_proline"), PrimaryKey]
        public Int32? KeyProLine
        {
            get { return Fields.KeyProLine[this]; }
            set { Fields.KeyProLine[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        [DisplayName("Numero Proceso"), Column("mst_proc_numero"), NotNull, QuickSearch, LookupInclude]
        public Int32? ProcesoNumero
        {
            get { return Fields.ProcesoNumero[this]; }
            set { Fields.ProcesoNumero[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        [DisplayName("Periodo"), Column("proc_fecha_proceso")]
        public String FechaProceso
        {
            get { return Fields.FechaProceso[this]; }
            set { Fields.FechaProceso[this] = value; }
        }
        //

        [Insertable(false), Updatable(false)]
        [DisplayName("Nro. Linea"), Column("mst_num_linea"), PrimaryKey]
        public Int32? NumLinea
        {
            get { return Fields.NumLinea[this]; }
            set { Fields.NumLinea[this] = value; }
        }

        //
        [Insertable(false), Updatable(false)]
        [DisplayName("Evento"), Column("mst_cod_evento"), ForeignKey("[dbo].[ta_codigo_eventos]", "eve_cod_evento"), LeftJoin("jEventos"), TextualField("NombreEvento")]
        [LookupEditor(typeof(TaCodigoEventosRow))]
        public Int32? CodEvento
        {
            get { return Fields.CodEvento[this]; }
            set { Fields.CodEvento[this] = value; }
        }
        [DisplayName("Evento"), Expression("jEventos.[eve_descripcion]")]
        public String NombreEvento
        {
            get { return Fields.NombreEvento[this]; }
            set { Fields.NombreEvento[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        [DisplayName("Nro. Contrato"), Column("mst_nro_contrato"), NotNull]
        public Int32? NroContrato
        {
            get { return Fields.NroContrato[this]; }
            set { Fields.NroContrato[this] = value; }
        }

        //       
        [Insertable(false), Updatable(false)]
        [DisplayName("Material"), Column("mst_cod_material"), ForeignKey("[dbo].[ta_ele_cnfg_material]", "cnf_codigo_ele"), LeftJoin("jMaterial"), TextualField("NombreMaterial")]
        [LookupEditor(typeof(TaEleCnfgMaterialRow))]
        public Int32? CodMaterial
        {
            get { return Fields.CodMaterial[this]; }
            set { Fields.CodMaterial[this] = value; }
        }
        [DisplayName("Material"), Expression("jMaterial.[cnf_glosa]")]
        public String NombreMaterial
        {
            get { return Fields.NombreMaterial[this]; }
            set { Fields.NombreMaterial[this] = value; }
        }
        //
        
        [Insertable(false), Updatable(false)]
        [DisplayName("Fecha Suscripcion"), Column("mst_fec_suscripcion")]
        public DateTime? FecSuscripcion
        {
            get { return Fields.FecSuscripcion[this]; }
            set { Fields.FecSuscripcion[this] = value; }
        }

        [Insertable(false), Updatable(false)]
        [DisplayName("Fecha Fin Contrato"), Column("mst_fec_fin_contrato")]
        public DateTime? FecFinContrato
        {
            get { return Fields.FecFinContrato[this]; }
            set { Fields.FecFinContrato[this] = value; }
        }

        //       
        //       
        [DisplayName("Estado Mapeo"), Column("mst_estado_mapeo_ele_isol"), ForeignKey(typeof(TaCodigosEstadosEtapas2Row)), LeftJoin("x")]
        [LookupEditor(typeof(ComboEstadoMapeoLooKup))]
        public Int32? EstadoMapeo
        {
            get { return Fields.EstadoMapeo[this]; }
            set { Fields.EstadoMapeo[this] = value; }
        }
        [DisplayName("Estado Mapeo")]
        [Origin("x"), MinSelectLevel(SelectLevel.List)]
        public String CetDescripcion2
        {
            get { return Fields.CetDescripcion2[this]; }
            set { Fields.CetDescripcion2[this] = value; }
        }
       
        //  VINCULACION BAJAS
        [DisplayName(""), MasterDetailRelation(foreignKey: "key_pro", MasterKeyField = "key_proline",IncludeColumns = "DetailList44")]
        public List<TablaBajasRow> DetailList4
        {
            get { return Fields.DetailList4[this]; }
            set { Fields.DetailList4[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.KeyProLine; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public MapeoBajasRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field KeyProLine;
            public Int32Field ProcesoNumero;
            public StringField FechaProceso;
            public Int32Field NumLinea;
            public Int32Field CodEvento;
            public Int32Field NroContrato;
            public Int32Field CodMaterial;
            public DateTimeField FecSuscripcion;
            public DateTimeField FecFinContrato;
            public Int32Field EstadoMapeo; 
            //
            public StringField CetDescripcion2;  // glosa del estado de la etapa 
            public StringField NombreEvento;
            public StringField NombreMaterial;
            //           
            public RowListField<TablaBajasRow> DetailList4;          
        }
    }
}

TablaBajasRow:
==========

namespace SegurosMAPC.BaseDatos.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("BaseDatos"), Module("BaseDatos"), TableName("[dbo].[ta_evento_bajas]")]
    [DisplayName("Bajas"), InstanceName("Bajas")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class TablaBajasRow : Row, IIdRow
    {
        [DisplayName("Key Proline"), Column("key_proline"), PrimaryKey]
        public Int32? KeyProline
        {
            get { return Fields.KeyProline[this]; }
            set { Fields.KeyProline[this] = value; }
        }

        [DisplayName("Numero Proceso"), Column("baj_proc_numero"), NotNull]
        public Int32? BajProcNumero
        {
            get { return Fields.BajProcNumero[this]; }
            set { Fields.BajProcNumero[this] = value; }
        }

        [DisplayName("Linea"), Column("baj_num_linea"), NotNull]
        public Int32? BajNumLinea
        {
            get { return Fields.BajNumLinea[this]; }
            set { Fields.BajNumLinea[this] = value; }
        }
                
        [DisplayName("Motivo"), Column("baj_id_motivo_ele"), ForeignKey(typeof(TaCodigoMotivoBajasRow)), LeftJoin("p")]
        [LookupEditor(typeof(TaCodigoMotivoBajasRow))]
        public Int32? BajIdMotivoEle
        {
            get { return Fields.BajIdMotivoEle[this]; }
            set { Fields.BajIdMotivoEle[this] = value; }
        }
        [Origin("p"), MinSelectLevel(SelectLevel.List)]
        public String Motivo
        {
            get { return Fields.Motivo[this]; }
            set { Fields.Motivo[this] = value; }
        }

        [DisplayName("Fecha Eliminacion"), Column("baj_fecha_eliminacion")]
        public DateTime? BajFechaEliminacion
        {
            get { return Fields.BajFechaEliminacion[this]; }
            set { Fields.BajFechaEliminacion[this] = value; }
        }

        //  VINCULACION LOG
        [DisplayName(""), MasterDetailRelation(foreignKey: "key_proline")]
        public List<LogEtapaCargaRow> DetailList44
        {
            get { return Fields.DetailList44[this]; }
            set { Fields.DetailList44[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.KeyProline; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public TablaBajasRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field KeyProline;
            public Int32Field BajProcNumero;
            public Int32Field BajNumLinea;
            public Int32Field BajIdMotivoEle;
            public DateTimeField BajFechaEliminacion;
            //
            public StringField Motivo;
            //
            public RowListField<LogEtapaCargaRow> DetailList44;
        }
    }
}

**Comment by minhhungit** [comment]
I guess you need to put **MinSelectLevel(SelectLevel.List)** on your TablaBajasRow.DetailList44

for example

```csharp
    [DisplayName(""), MasterDetailRelation(foreignKey: "key_proline")]
    [MinSelectLevel(SelectLevel.List)] // <============================== this line
    public List<LogEtapaCargaRow> DetailList44
    {
        get { return Fields.DetailList44[this]; }
        set { Fields.DetailList44[this] = value; }
    }
```

**Comment by patriciomh1965** [comment]
Thank you very much colleagues ... I will implement them.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
