### ISSUE TITLE
Ask aboout export to excel with Group and sum in Grid

### ISSUE THREAD

**Issue by spirit1989hcm** [volkanceylan/Serenity#5045]
hii all.
I have one gridview with grouping enabled. When I export the gridview data to Excel, the grouping is removed. Can you help me keep the grouping and the gridview styles?
Example
https://serenity.is/demo/BasicSamples/GroupingAndSummariesInGrid

**Comment by spirit1989hcm** [comment]
Help me

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
