### ISSUE TITLE
Question: Has anybody implemented camera upload to Form Field ?

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#5046]
This is not an issue per se` but I am looking to see if any one has implemented a camera upload to form field. Since many of my users can access by phone - there is a functionality that in my next wave I must implement and I would like to be able to include phone upload. Perhaps a button under the form field for capture image .. Any one have any functionality like this ?

**Comment by edwardch** [comment]
I just took a look at the Northwind Products page using my phone, opened the form and was presented with options of taking a picture, selecting from library, or browsing my phone’s file system.

I selected take picture and the upload worked fine.

I think most phones interpret the upload button as option to upload a picture.

Try from your phone and see what you get?

**Comment by stixoffire** [comment]
@edwardch Which version of the project are you using ?

**Comment by edwardch** [comment]
That test I did was just using the [serenity demo site](https://serenity.is/demo/Northwind/Product).

You might need to use something like MediaDevices .getUserMedia or webcamjs or some other file upload library. I haven't had a requirement for this so I don't know of an exact implementation, though I am intrigued to hear of any updates or progress you make.

**Comment by stixoffire** [comment]
@edwardch 
I am trying to use WebRTC - modifying my type script SignaturePad and implementing Declaration very similar.
[ImageCapture]
MyXYZField

This way I get the bells and whistles inclusive and have an opportunity to do other things with the captured image - for example barcode reads .., expense receipts, invoice, shipping forms ..etc..

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
