### ISSUE TITLE
import excel big data

### ISSUE THREAD

**Issue by spirit1989hcm** [volkanceylan/Serenity#5048]
Hi all, i have 1 file excel with 30 column and > 100.000 row, i imported excel to sqlserver sucessfull, but time import about >20minute, very slow. B/c every import 1 row will open 1 connection to sqlserver and close. 
Can you help me import excel big data to sqlserver faster?
I code like demo https://serenity.is/demo/BasicSamples/ProductExcelImport

**Comment by arunkumar12712** [comment]
use SqlBulkCopy

**Comment by arunkumar12712** [comment]
https://github.com/KostovMartin/Dapper.Bulk

**Comment by spirit1989hcm** [comment]
> https://github.com/KostovMartin/Dapper.Bulk

i'm learning about serenity, can you tell me file name to replace function import default of serenity?

**Comment by volkanceylan** [comment]
These are just samples, you should perform optimizations yourself.
