### ISSUE TITLE
[Tutorial] Create toolbar dropdown button

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#5049]
Hi team, I created wiki demo how to create a dropdown on toolbar

![](https://minhhungit.github.io/2020/06/10/008-create-serenity-toolbar-dropdown-button/serenity-toolbar-dropdown-button.gif)

Here is wiki link: https://github.com/volkanceylan/Serenity/wiki/Create-toolbar-dropdown-button

**Comment by Nathan2020-0126** [comment]
@minhhungit  thanks for your sharing, it looks very nice.

**Comment by dfaruque** [comment]
Thank you. I will add this to my https://github.com/dfaruque/Serenity.Extra

**Comment by minhhungit** [comment]
@dfaruque :+1:

**Comment by lechu90ns** [comment]
That's a lot of effort you put in there. It looks awesome :) thank you for your hard work.

**Comment by tmartinscopo** [comment]
Fantastic work! Thank you

**Comment by minhhungit** [comment]
@volkanceylan could I create PR to merge this feature to serenity
