### ISSUE TITLE
Getting Data by calling StoredProcedure from Script Projects

### ISSUE THREAD

**Issue by 04071967** [volkanceylan/Serenity#505]
Hi Volkanceylan

Is it possible to fetch data using Stored Procedure from XXXXXDialog.cs

Why i am looking for this ? - Based on value chosen by user from drowndown i need to pick record based on complex logic to populate the elements in Form.

Please guide

**Comment by VictorTomaili** [comment]
generate a service for run stored procedure with dapper. Call this service from dialog. reload dialog with response data.

**Comment by 107295472** [comment]
Can you connect to the request in the script project
