### ISSUE TITLE
Custom Error Pages not displaying

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#5050]
Hi Serenity community!

My custom error pages (in .NET Core version) don't seem to be working and I'm looking for guidance. I'd like the Error template in the **Views** directory to deliver the error message.

To start
- I set my ASPNETCORE_ENVIRONMENT to "Production" in web.config, and confirmed that it is being used.
- In `Startup.cs` my `app.UseExceptionHandler("/Home/Error");` matches the code in the Serene project (and also StartSharp). 

When I force an error to be thrown on the `DashboardPage.cs` my browser returns a **blank screen**, and I see in my browser dev tools that a 404 has been returned.

If I change my `app.UseExceptionHandler(////)` to what is in [Microsoft's Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-handler-lambda) I get a simple error page that works.

Is anyone else not able to display a custom error page?

As an aside, I see there's an `app.UseStatusCodePages` option which I can get a simple page showing by following the [official docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#usestatuscodepages-with-lambda), but I struggle to show a customised one using a cshtml file in the **Views** directory.

TIA!
Edward

**Comment by volkanceylan** [comment]
I have following in one of projects
```cs
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStatusCodePagesWithReExecute("/Home/Error", "?statusCode={0}"); // Custom error pages

```

Make sure you also have a Home/Error page.

**Comment by edwardch** [comment]
Thanks Volkan, I'm still getting a blank error page when I set the environment to "Production". 

(I am forcing an error by placing a divide by zero before returning the DashboardPageModel.)

My `Error.cshtml` is in the `Shared` folder per the default Serene project. Does this need to move somewhere else?

Thanks in advance,
Edward

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform

**Comment by StevenKnoop** [comment]
Hi there!

I am experiencing the same problem here except only for startup errors. I have already tried using the following:

- webBuilder.CaptureStartupErrors(captureStartupErrors: true); 
- app.UseExceptionHandler("/StartupError"); (this ActionResult never fires)

I created a new migration with the same migration version on purpose to trigger a startup error however I keep getting a detailed error page.

I don't want to use the webconfig HttpErrors to handle errors because it seems to interfere with the serenity toast notifications e.g. incorrect login looks like this:

![image](https://user-images.githubusercontent.com/5389509/105006674-a3a6f700-5a3f-11eb-876b-a519ad7f5340.png)

Happy Tuesday,
Steven

**Comment by elenaaralla** [comment]
> I have following in one of projects
> 
> ```cs
>             if (env.IsDevelopment())
>             {
>                 app.UseDeveloperExceptionPage();
>             }
>             else
>             {
>                 app.UseExceptionHandler("/Home/Error");
>             }
> 
>             app.UseStatusCodePagesWithReExecute("/Home/Error", "?statusCode={0}"); // Custom error pages
> ```
> 
> Make sure you also have a Home/Error page.

Hi,
do we have to create the controller Home/Error?

Thank you
