### ISSUE TITLE
Swashbuckle increasing continuously memory until crashes.

### ISSUE THREAD

**Issue by PedroNunoSantos** [volkanceylan/Serenity#5051]
Hello,

i did a test, and added Swashbuckle.AspNetCore to a new serene project.

I added the minimum swagger config (https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio), but after navigating to swagger the endpoint (http://localhost:5000/swagger/), the dotnet process went nuts, increasing continuously memory until i have to kill the process.

![image](https://user-images.githubusercontent.com/13595217/84495567-45dd5000-aca3-11ea-83ba-6bbc2d764c20.png)

Does anyone have any idea why?

Regards,
Pedro

**Comment by volkanceylan** [comment]
You should probably open an issue in Swashbuckle repo itself

**Comment by PedroNunoSantos** [comment]
I guess Swashbuckle does some infinite loop while reflecting the controllers.

Anyway, i found this guide and it fixed my problem: 
https://joonasw.net/view/hide-actions-from-swagger-openapi-documentation-in-aspnet-core

Add a ControllerModelConvention

```csharp
using System.Linq;
using Microsoft.AspNetCore.Mvc.ApplicationModels;

public class ControllerHidingConvention : IControllerModelConvention
{
    public void Apply(ControllerModel controller)
    {
        // any other logic, can be used here
        if (controller.ControllerType.Namespace.StartsWith("Serene.SwaggerTest.Web.Api"))
        {
            return;
        }
        
        foreach (ActionModel action in controller.Actions)
        {
            action.ApiExplorer.IsVisible = false;
        }
    }
}
```

then add the convention on the ConfigureServices method

```csharp
...
var builder = services.AddControllersWithViews(options =>
{
   options.Filters.Add(typeof(AutoValidateAntiforgeryTokenAttribute));
   options.Filters.Add(typeof(AntiforgeryCookieResultFilterAttribute));
   options.ModelBinderProviders.Insert(0, new ServiceEndpointModelBinderProvider());
   options.Conventions.Add(new ServiceEndpointActionModelConvention());

   // added this line
   options.Conventions.Add(new ControllerHidingConvention());

}).AddNewtonsoftJson(options =>
{
   options.SerializerSettings.ContractResolver = new DefaultContractResolver();
});
...
```

Regards.

**Comment by kilroyFR** [comment]
Question here ! i did test aspnet.core+NSwag + your fix. I still cannot see any of the endpoints. Anything i missed ?

**Comment by kilroyFR** [comment]
@PedroNunoSantos
any help ? do you see your controllers ?

**Comment by edwardch** [comment]
@kilroyFR or @PedroNunoSantos did you make any progress on getting Swashbuckle working?

I modified the `ControllerHidingConvention` to filter my charts controller, and set all **other** actions to not visible, and it works.

But when I put additional filters in to only set one Module with one class in it to visible, it hangs and eats up memory.

```cs
namespace MyProject.Charts.Endpoints
{
    [ServiceAuthorize, Route("Charts/DashboardCharts/[action]")]
    [ConnectionKey(typeof(SomeModule.Entities.SomeRow))]
    public class DashboardChartsController : Controller
    {
        [PageAuthorize, HttpGet]
        public BarChartResponse MyChart()
        {
            return new BarChartResponse();
        }
    }
}
```

```cs
public class BarChartResponse : ServiceResponse
{
    public List<BarChartDataSet> DataSets { get; set; }
    public List<string> Labels { get; set; }

    public BarChartResponse()
    {
        DataSets = new List<BarChartDataSet>();
        Labels = new List<string>();
    }
}
```

My ControllerHidingConvention looks like this:
```cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.ApplicationModels;

public class ControllerHidingConvention : IControllerModelConvention
{
    public void Apply(ControllerModel controller)
    {
        var nameSpace = controller.ControllerType.Namespace.ToLower();
        var controllerName = controller.ControllerName.ToLower();

        if (!controllerName.Contains("chart"))
        {
            SetHidden(controller);
        }
    }

    private void SetHidden(ControllerModel controller)
    {
        SetVisibility(controller, false);
    }

    private void SetVisibility(ControllerModel controller, bool visible)
    {
        foreach (ActionModel action in controller.Actions)
        {
            action.ApiExplorer.IsVisible = visible;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/4890069/157738625-9f81bf52-2833-4827-9338-15a4a1434c2d.png)


So the default controllers don't seem to work.

Any ideas?

TIA!

**Comment by minhhungit** [comment]
Hi everyone,

As I was testing the default project with Serenity, I noticed that it couldn't load endpoints because of two reference libraries: Serenity.Demo.Northwind and Serenity.Demo.BasicSamples. After ignoring them, everything loads fine, including Serenity endpoints and standard controllers like dashboardPage.

I'm using NSwag, and I suspect the issue arises from the reflection code in NSwag when it explores APIs and encounters exceptions with endpoints outside of the main project.

Has anyone already resolved this issue?

![image](https://github.com/serenity-is/Serenity/assets/2279508/fd9fa037-b22c-4d74-ad1b-d4186a539fdc)

**Comment by minhhungit** [comment]
Reality, having `Serenity.Demo.Sample` still work, but Northwind doesn't


![image](https://github.com/serenity-is/Serenity/assets/2279508/12f2a391-4d69-404c-a465-a3322b1535dd)
