### ISSUE TITLE
Dialog Constructor prematurely firing changeSelect2 in 3.13.4

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#5052]
Hi @volkanceylan 

Thank you for the latest update - there are some exciting changes and I like the direction Serenity is going!

After updating an existing project to 3.13.4 (from 3.12.3, which works) I experienced an issue where I have an information dialog set to go off when a user changes a dropdown select property in a dialog. 

The issue is that this information dialog appears whenever the xyzDialog is opened. 

I created a new project and tested this on the UserDialog.ts and I still experience this behaviour. 

To test this behaviour, add this to the `constructor()` of `UserDialog.ts`:

```ts
// This behaves as expected
this.form.MobilePhoneVerified.change(() => {
    Q.information("Mobile Phone Verified CHANGED", () => { });
});

// This is the issue
// It gets fired when opening the user dialog, even before this field is changed
this.form.TwoFactorAuth.changeSelect2(() => {
    Q.information("2FA CHANGED", () => { });
});
```

Thanks in advance,
Edward

**Comment by stixoffire** [comment]
@edwardch 
I believe change is only after the field has been loaded. 
changeSelect2 on the drop down ; the dropdown is being changed to a default value - the first value or another value - therefore it has changed.  you might want to set a value in the constructor to prohibit the function of the selection , and then after construction document ready ..- re-enable ..

**Comment by edwardch** [comment]
Thanks @stixoffire. I have placed this code above inside the `afterLoadEntity()` and I get my desired behaviour. 

I was looking also around a bit and what you say contradicts [Volkan's comment](https://github.com/volkanceylan/Serenity/issues/3602#issuecomment-393069157) from a similar question.

He states
> changeSelect2 only fires when user changes the value, change fires when value is set, e.g. when data is loaded into dialog.

For anyone else with a similar issue
- When I use Serenity 3.12.3 this code is inside my `constructor()` and it works like I expect.
- When I use Serenity 3.13.4 the changeSelect2() fires immediately, so I need to put it in `afterLoadEntity()`. 

@volkanceylan could you clarify which is the right place to put this, as of the latest version of Serenity?

Do you think that this deserves a mention in what to watch out for when upgrading this version?

Thanks again,
Edward

**Comment by JohnRanger** [comment]
@edwardch ,

what @stixoffire is proposing is the right way to do this. I had to do that long ago already - and I set a private property called launchingDialog with default value to true within the xyzDialog.ts which will be set to false within :

```ts
        // *** Launching Dialog flag (used to suppress early change triggers on change event of fields) ***
        private LaunchingDialog = true;
```

and then within afterLoadEntity:

```ts
protected afterLoadEntity() {
            super.afterLoadEntity();
            .
            .
            .
            // *** End the LaunchDialog phase ***
            this.LaunchingDialog = false;
```

And then you can use this property wherever you need to suppress onchange events.

Regards,

John

**Comment by edwardch** [comment]
Thank you John.

I had ended up putting the code inside `afterLoadEntity()` (after `super.afterLoadEntity()`) and it's working. And I get to use the latest version of Serenity :) 

Probably better to do it your and stixoffire's way though.

Thank you both for your help and contribution to this community, and also to all the other contributors. We all appreciate it!

Cheers,
Edward

**Comment by Davidwsk** [comment]
Thank you for this post!

My system is going live on Monday. (in 2 days!)
Only now discovered this issue.
During UAT, I was using 3.12.6 and everything work fine.
It seems that I have to change most of my screen now.... but at least we have a solution!

But it seems that .changeSelect2() and .change() function is exactly the same now.
Is my understanding correct?

Thanks!
