### ISSUE TITLE
Save First Child (Detail) of MasterDetailRelation

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#5053]
How to save details data (Child) data in master-detail relation soon after click save button of child without waiting until master save is clicked.

(I have complex Child form, i don't want to keep all till Master Save, On saving Each Child i want to save each child one by one to DB,  on saving master I just want to update the Foreign Key of the child to master)

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
