### ISSUE TITLE
Feild required error

### ISSUE THREAD

**Issue by Dim-PL** [volkanceylan/Serenity#5056]
Hi

I have upgraded my serenity project to dotnet core 3.1 and serenity to 3.12.6. After the upgrade, the project runs ok but I am getting below error in forms for all NotNull fields which I was not getting earlier before the upgrade.
 
![image](https://user-images.githubusercontent.com/49212601/84665859-403c7000-af18-11ea-89e3-d528db02108c.png)

I have set up the default values for 'NotNull' fields in the migration file, which was working ok before the upgrade.

If I add the [DefaultValue] attribute for the field in xxRow.cs file then its working fine but it's not a practical solution for me to add it for the whole project now.

Why after the upgrade I started getting this error and is there any workaround for this.?

Thanks
PL

**Comment by edwardch** [comment]
If you look at [The changelog to 3.12.3](https://github.com/volkanceylan/Serenity/blob/master/CHANGELOG.md#3123-2020-02-22) you'll see some comments about fixing null value handling. I think I also had one or two classes that I had to tweak.

Check the field flags to see whether it is being trimmed to null (default) or to empty. You might need to update your flags to get the desired result.

Hope that helps!

**Comment by Dim-PL** [comment]
Thanks for your reply, 

My problem is the **Default Values for NotNull fields**. I have no issues with handling null values.

Please see the below code, This is how I am setting up the default value in the migration file. 

```
           Action<ICreateTableWithColumnSyntax> addCols = expr => expr
                .WithColumn("name").AsString(20).NotNullable().WithDefaultValue("").Unique()
                .WithColumn("is_obsolete").AsBoolean().NotNullable().WithDefaultValue(false)
```

[DefaultValue(false)] is working for me in Row.cs file but this will be a big change to make in the whole project.

```
        [DefaultValue(false)]
        [DisplayName("Is Obselete"), Column("is_obselete"), NotNull]
        public Boolean? IsObselete
        {
            get { return Fields.IsObselete[this]; }
            set { Fields.IsObselete[this] = value; }
        }
```

Thanks

**Comment by edwardch** [comment]
I see what you mean, and I think the way that the project has been updated is the correct way with expected behaviour so unfortunately you may need to add the `DefaultValue` wherever it is used in your project. I hope your code base is a manageable size.

Another option would be to just remove the `NotNull` flag, since it is not nullable at the database-level, and you already have a default set for it. Meaning that your database should set it to false by default.

**Comment by Dim-PL** [comment]
Yes, I agree. This is the correct way. Serenity had this bug and its resolved now and I will need to set the default values in my project. 

Thanks for your help,

**Comment by volkanceylan** [comment]
Yes, Serenity had a bug where it didn't validate not-null non-string fields like Int32 etc. server side (it was still validated client side), that's why you didn't get any error before on such fields while you should.
