### ISSUE TITLE
Arabic characters in PDF export isn't work 

### ISSUE THREAD

**Issue by waleed51** [volkanceylan/Serenity#5057]
i want to add button to export pdf of arabic data , i use this 
 buttons.push(Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));
it's work but arabic characters no. 
how can i solve this problem ? 
![pdf serenity](https://user-images.githubusercontent.com/18492471/84770352-b05dfb00-afd7-11ea-8568-67cb4bda239c.PNG)

Regards
![Uploading pdf serenity.PNG…]()

**Comment by volkanceylan** [comment]
This is asked many times, the library is jsPDF, it does not support some chars, check in their repo.

**Comment by waleed51** [comment]
> This is asked many times, the library is jsPDF, it does not support some chars, check in their repo.

ok thanks 
can you help me in another problem, i'm new with serenity

**Comment by waleed51** [comment]
> check in their repo.

thank you , but sorry i'm new with serenity what are you meen by "check in their repo."

**Comment by dfaruque** [comment]
Please check [this](https://github.com/MrRio/jsPDF) repo

**Comment by waleed51** [comment]
> Please check [this](https://github.com/MrRio/jsPDF) repo

thank you , but how can i use it to show arabic characters

**Comment by ra-bedo11** [comment]
how can i use this in serenity https://github.com/parallax/jsPDF
be cause arabic not work in pdf?

plz help me !!!!!!!!!!
