### ISSUE TITLE
Entity Grid as Panel scroll to top automatically while add/edit details

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#5059]
Steps to reproduce the issue
Go to https://serenity.is/demo/BasicSamples/EntityDialogAsPanel/11077
then open an Order Detail and update the detail.
the page is scroll to top which should not be.

**Comment by volkanceylan** [comment]
It is the browser which scrolls page to top because of #. Disable router if you worry about it.

**Comment by dfaruque** [comment]
OK. Thank You.

Putting the following line at that page is solved the issue
        `Q.Router.enabled = false;`
