### ISSUE TITLE
Cascading Editor: Could not find field 'XXXId' on row of type 'ZZZRow'

### ISSUE THREAD

**Issue by MrPec** [volkanceylan/Serenity#506]
Hi,

I use the cascading editor. Everything works fine, but when I try to save the entity the client shows me the above error dialog. Well, indeed the ZZZRow does not have that Id. I just use the lookup editor to get eventually the right Id of an (underlying) item.

I followed your tutorial, it is as if the MyModule.Customer does only have a reference to District, not to City or Country.

How can I fix that, or how do I exclude the other fields from being validated?

Thanks!

Alex

**Comment by MrPec** [comment]
Ok, I got it to work by adding the field XXXId to the entity and decorating the property with [SetFieldFlags(FieldFlags.ClientSide)]

**Comment by volkanceylan** [comment]
You could also add that as a foreign field.
