### ISSUE TITLE
Impersonating Authorization Service for .NET Core

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5062]
Hi,

Can you please help with ASP.NET Core alternative for following code?
`(Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).Impersonate("systemuser");`

FYI: When I call this, I am getting following error
> Object reference not set to an instance of an object.

@volkanceylan Please check this.

Regards,

**Comment by wezmag** [comment]
Did you register `ImpersonatingAuthorizationService` in `Startup.cs`?

If not, this is how you do it.

In `Startup.cs`, replace `services.AddSingleton<IAuthorizationService, AuthorizationService>();` with
```csharp
services.AddSingleton<IRequestContext, RequestContext>();
services.AddSingleton<IAuthorizationService>(new ImpersonatingAuthorizationService(new AuthorizationService()));
```

**Comment by welcometoall** [comment]
I have added those 2 lines, but didn't remove following line
`services.AddSingleton<IAuthorizationService, AuthorizationService>();`

Now it is working... Thanks @wezmag !!!
