### ISSUE TITLE
Conditionally Disable EditLink in Detail Grid 

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#5063]
I have an OrderGrid, when the Order is submitted it gets locked so no other items can be added, however even though it is locked it still must allow for order items to be received. Which when receiving a column is unhidden and shown for entry of received items. While I can set the grid to read only - the Link for Editing Items that were placed i still available and functioning.

I want to disable that link on condition

@volkanceylan - The grid editors with the ReadOnly property - does not disable an EditLink from the XYZcolumns (I have a detail editor) .  

My Parent Table has a Field 'ItemLocked' when it is locked the details can't be changed in any way Except one field - when I receive Items.

 Would like to do this : EditLink(EnableField=myField, Value= True) but that is not available.

I have looked at issue #4459 , neither of JohnRangers answers will allow for the second requirement nor fulfill the first requirement.

Issue #4402  does not handle the case of add or remove the link , for example each row has an id , and that needs to be provided along with the editor in the link.

```
<div class="slick-cell l0 r0 align-center" title="">
<a href="#MyRealDB-ItemLocationEditor/``1" data-item-type="MyRealDB.ItemLocationEditor" data-item-id="``1" class="s-EditLink s-MyRealDB-ItemLocationEditorLink">Not Set</a></div>

<div class="slick-cell l0 r1 align-center" title="">
<a href="#MyRealDB-ItemLocationEditor/``2" data-item-type="MyRealDB.ItemLocationEditor" data-item-id="``2" class="s-EditLink s-MyRealDB-ItemLocationEditorLink">Over Yonder</a></div>

``` 
So far I have the following to try and generate the link manually, I need to be able to get each row in the grid for the column with the link .. not sure on how to go about that.

```
        protected getEditLink(idField: string, editorName: string, ctxValue: any): string {

            var klass = "s-EditLink";
            var klassEnd = "Link";

            var linkEdit = "<a href='#" + editorName + "/``" + idField + "'";
            var dataItem = " data-item-type='" + editorName + "' data-item-id=``" + idField + "'";
            klass = "'" + klass + " s-" + editorName + klassEnd + "'";
            var linkEnd = "</a>";
            var markup = linkEdit + dataItem + klass + Q.htmlEncode(ctxValue) + linkEnd;

            return markup;
        }

```

I have been banging my head on this for a couple days and now I know I need some direction..

**Comment by hannesb** [comment]
Maybe a Slick formatter (like [EmployeeListFormatter.ts](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/EmployeeListFormatter.ts)) is what you are looking for?

HTH
Hannes

**Comment by stixoffire** [comment]
I have  my answer. I will share it on the WIKI.

I wanted to do this an easier way , there are probably better ways.

However I did accomplish this not as well as I would like - but it works. 

[Conditionally-disable-the-EditLinks-in-a-Detail-Editor-that-is-part-of--MasterDialog-with-a--Parent-Child-Relationship.](https://github.com/volkanceylan/Serenity/wiki/Conditionally-disable-the-EditLinks-in-a-Detail-Editor-that-is-part-of--MasterDialog-with-a--Parent-Child-Relationship.)
