### ISSUE TITLE
PDF with Unicode Chars

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5064]
When PDF is exported, Unicode chars are not displaying properly.

![image](https://user-images.githubusercontent.com/11242099/85130136-f920e880-b251-11ea-80d8-b4fe4a3dff29.png)

![image](https://user-images.githubusercontent.com/11242099/85130094-e4445500-b251-11ea-853c-eaea402bbe9a.png)

**Comment by volkanceylan** [comment]
You should search wkhtmltopdf issues about it.
