### ISSUE TITLE
LayoutTimer in the Grid - HOW to use?

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#5065]
Any idea how to use this?
I have groups that expand and collapse and this is causing issues with grid at the bottom :(

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
