### ISSUE TITLE
Disable Drag and drop Column feature in serenity grid

### ISSUE THREAD

**Issue by nareshIntelegain** [volkanceylan/Serenity#5067]
I have added one extra column by using columns.splice(1, 0, applycolumn) method to grid but issue is user is now able to drag the column wherever he wants but i dont want to allow drag for column in grid to user. Plz suggest me option to disable drag and drop for column in grid serenity.

            MyGrid.prototype.getColumns = function () {
                var _this = this;
                //var buttons = _super.prototype.getButtons.call(this);
                var columns = _super.prototype.getColumns.call(this);
                var applycolumn = {
                    name:'Action' 
                  
                    width: 300,
                    sortable: false,
                    
                   

                    format: function (ctx) {
                        // console.log(ctx.item.Remark);
                        
                                return Q.outerHtml($('<button/>')
                                    .addClass('target-text')
                                    .attr('disabled', 'disabled')
                                    .attr('height', 50)
                                    .attr('onclick', 'GetDetails(this,' + ctx.item.ProductId+ ',true);')
                                    .text('Apply'));
                            
                           
                columns.splice(1, 0, applycolumn);
                return columns;
            };

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
