### ISSUE TITLE
IListBehavior： How to add a list behavior into current ListRequestHandler

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5068]
Dear all,
I want to dynamic change the query in ListRequestHandler. 
I store the dynamic criteria in database.  How to add a behavior to get the criteria from database and change the query citeria in  ListRequestHandler. I don't want to change the ListRequestHandler one by one. Is it possible?
![image](https://user-images.githubusercontent.com/16734387/85204516-a6c1f380-b347-11ea-8029-36f651ae9cf2.png)

**Comment by Nathan2020-0126** [comment]
I create a class as below, but it didnot work.
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Serenity.Services;
using Serenity.Data;
using Serenity;

namespace Mom.Common
{
    public class ListBehavior: IListBehavior
    {
        public void OnValidateRequest(IListRequestHandler handler) { 
            
        }
        public void OnPrepareQuery(IListRequestHandler handler, Serenity.Data.SqlQuery query)
        {
            var fld = Mom.Administration.Entities.UserRow.Fields;
            BaseCriteria criteria = fld.OrganizationName.Contains("滚针2");
            query.Where(criteria);
        }
        public void OnApplyFilters(IListRequestHandler handler, Serenity.Data.SqlQuery query)
        {

        }
        public void OnBeforeExecuteQuery(IListRequestHandler handler)
        {

        }
        public void OnAfterExecuteQuery(IListRequestHandler handler)
        {


        }
        public void OnReturn(IListRequestHandler handler)
        {


        }
    }
}
```

**Comment by hannesb** [comment]
You must implement the IImplicitBehaviour if your Behaviour should trigger for all tables.

Maybe the [multi tenancy example](https://serenity.is/docs/tutorials/multi_tenancy/multi_tenancy) is a good starting point for what you want to achieve.

HTH
Hannes

**Comment by Nathan2020-0126** [comment]
@hannesb  thanks very much. It works with IImplicitBehaviour
