### ISSUE TITLE
Print Template

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#5069]
hi all
please guide me how to achieve the attached print type format in serenity.

Thanks and Regards,
Srinivas
![TC-745x1024](https://user-images.githubusercontent.com/29406374/85256044-14256f80-b481-11ea-80d4-5b902324c75c.jpg)

**Comment by welcometoall** [comment]
Go through
[https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Modules/Northwind/Order/OrderGrid.ts](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Modules/Northwind/Order/OrderGrid.ts)

 [https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Modules/Northwind/Order/OrderDetailReport.cs](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Modules/Northwind/Order/OrderDetailReport.cs)
