### ISSUE TITLE
jquery-ui-i18n

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#507]
Where to set,Datetime type

**Comment by wdhodges** [comment]
Are you referring to the DateTime editior? You will do this in XYZRow.cs

**Comment by 107295472** [comment]
[DisplayName("Hire Date")]
        public DateTime? HireDate
        {
            get { return Fields.HireDate[this]; }
            set { Fields.HireDate[this] = value; }
        }

**Comment by 107295472** [comment]
Multi language
![qq 20160404092153](https://cloud.githubusercontent.com/assets/6436116/14236367/de1fd612-fa46-11e5-97ec-e04b23728124.png)
