### ISSUE TITLE
how to upload file PDF from form

### ISSUE THREAD

**Issue by spirit1989hcm** [volkanceylan/Serenity#5070]
Hi every one, in exam https://serenity.is/demo/Northwind/Product#new 
I see row "Product Image" to upload file image to product, but i can't upload 1 file pdf.
How i can upload 1 file PDF to sqlserver?

**Comment by edwardch** [comment]
Check the `ProductImage` field in `ProductRow.cs`, you want to replace `ImageUploadEditor` with `FileUploadEditor`.

**Comment by spirit1989hcm** [comment]
I replaced ImageUploadEditor with FileUploadEditor. 
Error: 

The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

**Comment by edwardch** [comment]
When do you get this error? On build? On grid load? On entity open? On entity save? After upload? Is it in your browser console or within Visual Studio?

I have something like this and it works for me:
```cs
[DisplayName("File"), Size(255), NotNull, QuickSearch]
[FileUploadEditor(FilenameFormat = "Files/Uploads/~", AllowNonImage = true, CopyToHistory = true)]
public String Path
{
    get { return Fields.Path[this]; }
    set { Fields.Path[this] = value; }
}
```

**Comment by spirit1989hcm** [comment]
I brown file ok, after that I click button SAVE to add new record is error.
I created database  from https://codingsight.com/storing-files-in-sql-database-using-filestream-part1/

**Comment by edwardch** [comment]
Ok I see you want to store your file as VARBINARY in your database.

Serenity's default for the file upload is to store the file on disk, and store the file path in the column as a VARCHAR, this works well.

I haven't needed to do your method myself, but you can look in previous issues for some direction, e.g [#3890](https://github.com/volkanceylan/Serenity/issues/3890).

Hope that helps!

**Comment by spirit1989hcm** [comment]
Serenity's default for the file upload is to store the file on disk, and store the file path in the column as a VARCHAR=> Example when I upload 1 file, how can i view this file? because it store file path in database
