### ISSUE TITLE
Convert expression to List<Int>

### ISSUE THREAD

**Issue by rahooftkh** [volkanceylan/Serenity#5071]
When try to set data from query expression to slick.grid its appear blank 

 [DisplayName("Promotions"),Expression("(select p.Id from students s inner join PromotionDetails pd on pd.studentid=s.Id inner join promotions p on p.id=pd.PromotionId where pd.IsCompleted=0 and pd.StudentId=T0.Id)")]
        public List<Int32> Promotions
        {
            get { return Fields.Promotions[this]; }
            set { Fields.Promotions[this] = value; }
        }

**Comment by welcometoall** [comment]
Check [https://github.com/volkanceylan/Serenity/wiki/LinkingSetRelation-Explanation](https://github.com/volkanceylan/Serenity/wiki/LinkingSetRelation-Explanation)
