### ISSUE TITLE
Reload data on tab change

### ISSUE THREAD

**Issue by PassionateDeveloper86** [volkanceylan/Serenity#5073]
Hi

I have 4 tabs and on the 4. tab I want to reload data by en allready given endpoint.
So I know how to reach this endpoint in my ts file in my dialog.ts but I dont know 
1) how to set the result value into a textfield
2) how to do this whenever the tab is selcted (which event, where to register to that event

**Comment by welcometoall** [comment]
You can handle the tab click using following code.
```
this.tabs.click((e, h) => {
	let key = e.target.innerText;
	/* your code/logic goes here */
});
```

**Comment by Wasseratem** [comment]
Tried that. I allways get 
Message: TypeError: this.tabs is undefined

I tried it within the constructor and afterLoadEntity, but both same error.

**Comment by stixoffire** [comment]
@Wasseratem 

Try in  markupReady or the updateInterface.
Also are your tabs visible at load or do you toggle that ?
Are you sure you are in the dialog and not an editor ?

Also make sure you do not have any errors in your code - the typescript T4 translation does not transform if there are errors.

You can also get Tabs byId   , this.byId('TabNotes')

Example setting a field value - if it is not a field but a text there is another way to do that
```
                OrdersDB.InventoryItemService.Retrieve({
                    EntityId: itemId
                }, response => {
                    this.setFieldValues(response.Entity);
                });

        // Set field values
        private setFieldValues(details: InventoryItemRow) {

            this.form.UnitPrice.value = Number((details.UnitPrice).toFixed(2));
            this.form.QuantityPerUnit.value = details.QuantityPerUnit;

        }
```

**if you need to set the value of an element and not a data point**

```
                this.orderTotal = formatter.format(total).toString();

// Find the element that I want to set the text value of.
                var objOrderTotal = this.element.parent().parent().find(".grid-container").parent().find(".OrderTotal");

                objOrderTotal.html("<font color='black'>Order Total: <b>" + this.orderTotal + "</b></font>");
```
