### ISSUE TITLE
is onViewFilter supposed to work with navigation in the Grid?

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#5074]
Hi

does anybody have experience with onViewFilter?
I managed for it to work and add further filtering, but it does not update number or rows, nor pages, that are displayed in the grid.
IS this suppose to work, and I found a bug, or is this a feature?

**Comment by volkanceylan** [comment]
onViewFilter is for client side in memory filtering and it never updates paging which is server side.
