### ISSUE TITLE
Is Serenity.is down ?

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#5075]
Cannot access this website anymore (only accessing Serenity thru GitHub), anyone else experiencing same issue ?

So being unable to access dotnecore migration steps : https://serenity.is/blog/2020/06/17/migrating-dotnetcore

**Comment by zappitmr** [comment]
Not working for me either.

**Comment by MafdyAzer** [comment]
@kilroyFR Yes site is down, but you can access dotnecore migration from blog repository:

https://github.com/volkanceylan/Serenity-Blog/blob/master/2020-06-17-migrating-dotnetcore.md

**Comment by volkanceylan** [comment]
Yes we have some server issues atm

**Comment by VictorTomaili** [comment]
Serenity.is live again. Sorry for trouble.

**Comment by edwardch** [comment]
@volkanceylan  just to let you know this seems to be down again...
