### ISSUE TITLE
Quick filter Year

### ISSUE THREAD

**Issue by spirit1989hcm** [volkanceylan/Serenity#5079]
Hi everyone, I have datetime column, I want to quickfilter lookup Year from this datetime column.
This is file lookup:

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Entities.DateRow.Fields;
            
            query.Distinct(true)
                .Select(fld.Datetime)
                .Where(
                    new Criteria(fld.Datetime) != "" &
                    new Criteria(fld.Datetime).IsNotNull());
        }

Can you help me?

**Comment by arunkumar12712** [comment]
try this
add this line in DateRow
     
   [DisplayName("Total Days"),  Expression("Year(T0.Datetime)")]
        public Int32? Years
        {
            get { return Fields.Years[this]; }
            set { Fields.Years[this] = value; }
        }

/**********/

query.Distinct(true)
            .Select(fld.Years)
            .Where(
                new Criteria(fld.Datetime) != "" &
                new Criteria(fld.Datetime).IsNotNull());

**Comment by spirit1989hcm** [comment]
tks for your help, code working well
