### ISSUE TITLE
Creating a new page (Without Sergen)

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#508]
@volkanceylan or @VictorTomaili 

Do you either one of you guys have a tutorial on how to create a new page like the register a new user page or what have you? I'm working on creating the dialog where you can add a new external link to the database but have come to realized I'm not to sure how to add an entire new page to the Serenity. (still new to asp.net)

Reference #490

**Comment by 107295472** [comment]
Serenity.CodeGenerator

**Comment by wdhodges** [comment]
@107295472 please reference the title. It states _without_ Sergen

**Comment by volkanceylan** [comment]
Why are you doing this like register page. It should be just like ordinary grid/dialog pages. Just create tables and let sergen handle rest.

**Comment by wdhodges** [comment]
Ohhh. I hate a complete lapse in conscious thought last night. Thanks for
this.

**Comment by ancasabu20** [comment]
Hi, when use sergen this delete options in template, and show me the page blank
