### ISSUE TITLE
How can i generate Custom HTML Table in form dialog

### ISSUE THREAD

**Issue by paradey** [volkanceylan/Serenity#5080]
Hi,

I'm working some ERP project and i need create payment plan in form dialog.

Dialog.ts

```
            Q.serviceRequest('ERP/Member/Calculate', {
              // Some parameters
            }, (response) => {
             //   returned payment plan list.
            });
```

![image](https://user-images.githubusercontent.com/9864321/85701306-ebea7a80-b6e5-11ea-89b8-f7f9a2268293.png)

I want to create dynamic html table for paymant plan list just view table.

**Comment by edwardch** [comment]
Try to add a String property to your xyzForm.cs, and above it add `[StaticTextBlock(IsHtml = true)]`. The property can then be populated with your custom HTML.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
