### ISSUE TITLE
Open a link after click on inline button

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5081]
Hi;

I am trying to open a link using inline button. I have the following code:

    `protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();
                if (target.hasClass('view-details')) {
                    **this.editItem(item.Id);**
                }
            }
        }`

I want to fire the following page after button click :

**Citities/CityDetails?CityId={0}**

**Comment by minhhungit** [comment]
try this:

> window.location.href = Q.resolveUrl(`~/Citities/CityDetails?CityId=${your_param}`);
