### ISSUE TITLE
Generate dynamic form

### ISSUE THREAD

**Issue by belalAhmed** [volkanceylan/Serenity#5082]
How i can generate or add dynamic controls in form dialog from database

**Comment by edwardch** [comment]
You will have to come up with some custom design for that, see [#4941](https://github.com/volkanceylan/Serenity/issues/4941) and [#4734](https://github.com/volkanceylan/Serenity/issues/4734) for example. In those issues are links to [a StackOverflow question](https://stackoverflow.com/questions/3862226/how-to-dynamically-create-a-class) that might give some further insight too.

The [Data Explorer in the demo](https://serenity.is/demo/AdvancedSamples/DataExplorer) can help with your grid. [Dynamically formatting Field in grid and Dialog according to "virtual type" #2475 ](https://github.com/volkanceylan/Serenity/issues/2475) wasn't really resolved but might give you ideas for a direction.

Hope these links help.
