### ISSUE TITLE
Modules in separate projects

### ISSUE THREAD

**Issue by belalAhmed** [volkanceylan/Serenity#5083]
How i can create each module as separate projects. then load  all of them in main project

**Comment by KishanVaishnani** [comment]
Hi @belalAhmed 
1. you will need to load Assemblies in your main serenity project insided sergen.json

"ServerTypings": {
    "Assemblies": [
      "./bin/debug/netcoreapp2.2/xxx.dll",
      "./bin/debug/netcoreapp2.2/xxx.dll"
    ],

2. Create one class in your main project and include all your class,enum, modules files in created one with [ScriptInclude]

**Comment by mrhb** [comment]
https://github.com/volkanceylan/Serenity/issues/5083#issuecomment-650899262
is this worked for anybody?

**Comment by minhhungit** [comment]
hi, it works for me ( for .net core version )

but I have to include my main web dll in the first line, for example
```json
"Assemblies": [
    "./bin/debug/netcoreapp3.1/Serene1.Web.dll",
    "./bin/debug/netcoreapp3.1/HelloWorldLib.dll"
],
```

```csharp
namespace HelloWorldLib
{
    public class MyModel: ServiceRequest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
    }

    [ScriptInclude]
    public enum MyEnum
    {
        Hello,
        World
    }
}
```

**Comment by KishanVaishnani** [comment]
@marcobisio Yes maybe there was some changed in asp.net core version, but the concept was same

**Comment by reach2rv** [comment]
@KishanVaishnani @minhhungit can you guys please add some more information to this. Like how servertypings and other things will work.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
