### ISSUE TITLE
Filter grid based on query string

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5084]
Hi;

I need help in filtering the grid results based on query string
For example, I have the following url with query string:
"/Cities/Citylist?CountryId=20"

Now I need help on how to get the CountryId (weather to get it in Service or Endpoint) and then apply the filtering based on the CountryId

Thank you

**Comment by arunkumar12712** [comment]
https://serenity.is/demo/Northwind/Product?cat=1

**Comment by ms4hafiz** [comment]
@arunkumar12712
I have to grids. One grid is Country list and other is supposed to list list of cities for a specified country. Now I have to deal with two grids to filter cities in the second grid from a country selected in first grid.

**Comment by arunkumar12712** [comment]
try this
https://github.com/volkanceylan/Serenity/issues/4235

**Comment by ms4hafiz** [comment]
I found the following which is kind of similar to what I need but in my case I am using each grid in separate pages

https://serenity.is/demo/Northwind/Order#edit/11076
or 
https://serenity.is/demo/AdvancedSamples/SplitMasterDetail#edit/1
