### ISSUE TITLE
Select a Tab Programmitically in Dialog

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#5085]
Hello All
How to Select one tab between 3 tabs programmitically in Dialog class?

**Comment by stixoffire** [comment]
@MaziarSangi 

You should really search the "Issues" as most of the issues are questions  - if you had you would have found your answer 
in issue #1432 

You should read the above linked issue and you will have all the information you need ..

There is an example in Serene https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/BasicSamples/Dialogs/OtherFormInTabOneBar that use Serenity.TabsExtensions.selectTab method

this.tabs.tabs('option', 'active', 0) or selectKeys method in that sample
