### ISSUE TITLE
problem saving dialog in masterDetailRelation

### ISSUE THREAD

**Issue by fremar83** [volkanceylan/Serenity#5086]
I intercept the detail changes (adding of a new record)  from master dialog and try to force the dialog to save.
Master changes are saved but detail adds are not.
I tried with :
- this.save((response: Serenity.SaveResponse) => { });
- this.saveAndCloseButton.click;
- this.applyChangesButton.click,
- this.toolbar.findButton('apply-changes-button').click()

It always saves master changes but without adding new detail record

**Comment by fremar83** [comment]
Hi all,
Has anyone a clue on this problem ?
When I tried to programaticaly save the master form, the detail adds are not saved.
Thank's.

**Comment by volkanceylan** [comment]
I guess where you intercept (is it validateEntity??) records are not yet appended to the grid, may use setTimeout or prefer a better place.
