### ISSUE TITLE
Filter lookup with Like operator

### ISSUE THREAD

**Issue by jiecerbo** [volkanceylan/Serenity#5088]
I have created a custom editor and want to apply a filter on it based on a user's entry. I am currently filtering it using this code:

` return super.getItems(lookup).filter(x => x.Name == this.clientName);`

Is there a way to filter it using Like, as in 
` return super.getItems(lookup).filter(x => x.Name like '%this.clientName%');`

Thanks.

**Comment by welcometoall** [comment]
try indexOf, `return super.getItems(lookup).filter(x => x.Name.indexOf(this.clientName) != -1);`

**Comment by jiecerbo** [comment]
Thanks for the suggestion @welcometoall. I have tried doing it as you saym however i'm getting the error below:

`JavaScript runtime error: Unable to get property 'indexOf' of undefined or null reference`

**Comment by volkanceylan** [comment]
So you have items with null Name property.
