### ISSUE TITLE
In Repository Methods: Iterate Field Values of Row foreach fld in Row.Fields get the value

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#5089]
I am trying to iterate the Values in the Row Fields in order to notify certain users of changes to a particular table and I would like to provide Old Value and New value
Consider this code, how can I iterate the values of each field to provide in my message?
```
                    if (this.Row.IsAnyFieldChanged)
                    {
                        foreach (var rowFld in Fld)
                        {
                            if (this.Row.IsFieldChanged(rowFld))
                            {
                                    // Some really nice text to add to my notification message
messageData[0] = messageData[0]  + rowFld.Caption + " has been Changed." + nl + "OLD:" + nl + this.Old.[rowFld Value access] + " NEW:" + this.Row..[rowFld Value access];

                            }
                        }
                    }

```

**Comment by welcometoall** [comment]
Use c# reflection to get property values for properties from object
[PropertyInfo.GetValue Method](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo.getvalue?view=netcore-3.1)

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
