### ISSUE TITLE
Adding Editor for detail creates problem

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#509]
'Editor' is an ambiguous reference between 'System.ComponentModel.EditorAttribute' 
and 'Serenity.EditorAttribute'

Once the Editor for detail table is created in script project. it generates an error as shown above.

can someone please help me in resolving this issue.

**Comment by volkanceylan** [comment]
Remove System reference. Use copy paste to create files. It was stated in reference, troubleshooting....

**Comment by mrajalko** [comment]
thanks
it worked.
