### ISSUE TITLE
Data URI malformed - Date picker icon

### ISSUE THREAD

**Issue by sjcdtm** [volkanceylan/Serenity#5090]
Apologies if this is already reported, I could not find an open issue that discussed this.

 I think that this bug has reappeared in the latest (3.13.4) release:

3.12.6
April 12, 2020
Bugfixes:

fix css bundle manager removes quotes in url for data uris while adjusting relative paths in css bundle

I updated to the latest release and found that the date picker icons were not rendering correctly, the error associated with this is: error on line 1 at column 287: AttValue: ' expected

This agrees with the above bugfix scenario so I rolled back to release 3.12.6 and this has resolved the issue. I haven't tested to see which if any interim release reintroduced this issue but it did appear when updating to 3.13.4

If others are experiencing this problem, rolling back to a previous release may resolve this.

**Comment by volkanceylan** [comment]
Fixed in latest
