### ISSUE TITLE
TextBox input in  Dialog ToolBar 

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#5094]
Hello All
Does anybody knows How to add input text box before one ToolBar button of a dialog?

**Comment by stixoffire** [comment]
In your browser - hit F12 get the class name of the tool bar button you want to add the text box in front of.
After that you can use 
var el = this.element.parent().parent();
// el tells you what item it found in the tree  so you can experiment with how high up the ladder you need to go, I do think there is a method for getToolbar - so perhaps possible when you have the element you can prepend to it.

this.element.parent().parent().find('class name').prepend(myhtml for input text box);

**Comment by arunkumar12712** [comment]
try this

constructor() {
            super();
            this.toolbar.element.append("<input type=text id='text'/>");
        }

**Comment by arunkumar12712** [comment]
try this

`constructor() {
            super();
            this.toolbar.element.append("<input type=text id='text'/>");
        }
`

**Comment by stixoffire** [comment]
@arunkumar12712  thanks for posting that  - @MaziarSangi  will need to use prepend instead of append.
