### ISSUE TITLE
Validate grid upon before adding new record

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5095]
Hi;

I have a grid like following child grid which will have few records

![image](https://user-images.githubusercontent.com/20435849/86523863-17a8f580-be88-11ea-8e38-81979e35cf1f.png)

Now I need to apply a validation upon click of "New.." button. When a user clicks on "New ..." I want the program to check the **Through Date**  if it is blank then it should not allow adding new record and give a warning otherwise it should allow adding new record.

Thank you for help

**Comment by Nathan2020-0126** [comment]
you can override addButtonClick function like below
```
protect addButtonClick(){
           this.getItems().forEach(e=>{
                  check the through date here
           });
}
```

**Comment by ms4hafiz** [comment]
Hi @Nathan2020-0126 
Thank you for the response
I added the following code but is not working

        protected addButtonClick() {
            this.getItems().forEach(e => {
                this.getItems().forEach(e => {
                    if (e.SThroughDate == null || String(e.SThroughDate).length == 0) {
                        alert("testing");
                    }
                });
            });
        }

I then tried to create a function to count number of blanks rows based on a specific condition. The code is following but  it does not recognize **getItems()**

        countGridblanks() {
            var cnt = 0;
            
            this.getItems().forEach(e => {
                if (e.SThroughDate == null || String(e.SThroughDate).length == 0) {
                    cnt = cnt + 1;
                }
            });

            return cnt;
        }
