### ISSUE TITLE
Formatter issue 

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5096]
Hi;

I have create a custom formatter  for checkbox like following:

    @Serenity.Decorators.registerFormatter()
    export class CheckBoxFormatter implements Slick.Formatter {

        format(ctx: Slick.FormatterContext) {

            if ((ctx.value === true)) {
                return '<i class="fa fa-check-circle text-green text-center">';
            }
            else if ((ctx.value === false)) {
                return '<i class="fa fa-fa-times text-green text-center">';
            }
        }
    }

after I apply them on the column

       [CheckBoxFormatter]
        public Boolean IsSubgrant { get; set; }
        [Width(120)]
        [CheckBoxFormatter]
        public Boolean IsActive { get; set; }

it results like following in the grid
![image](https://user-images.githubusercontent.com/20435849/86524562-568f7900-be91-11ea-9549-4e6468b23429.png)

I wonder if anybody has faced the same issue and how fix this?

Thank you

**Comment by JohnRanger** [comment]
Hi @ms4hafiz ,

if I see it correctly in your HTML output, you don't close the ```<i>``` tag with e.g. ```<i ..../> or <i>...</i>```.

Regards,

John
