### ISSUE TITLE
Nested Tab

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#5101]
How can I show tab inside another tab
eg: For First Tab 2 sub-tabs
For second tab another 2 sub-tabs
On main tab bar only two tabs
But 2 additional tab inside tab element

Something like this
   ```
public class SampleForm
    {
        [Tab("First Tab")]
        public String FirstName { get; set; }

        [InnerTab("IT1")]
        public String LastName { get; set; }

        [InnerTab("IT2")]
        public String Place { get; set; }


        [Tab("Second Tab")]
        public String Address1 { get; set; }

        [InnerTab("IT1")]
        public String Address2 { get; set; }

        [InnerTab("IT2")]
        public String Address3 { get; set; }
    }
```

**Comment by stixoffire** [comment]
@djysf  Look at how the customtemplate is done - I think the Customer - Customer Orders in the Northwind sample has an implementation of the custom template . This is what you will most likely need to do . I am about 99% sure you will find your answer there.

**Comment by djysf** [comment]
@stixoffire Thanks a lot,
But that custom template has just adding top-level Custom Tabs from the template.

I am ok with the custom template as far as I can reuse to create multiple nested tabs from the form through declaration

**Comment by stixoffire** [comment]
@djhonb I believe when you look at the form in the template in that section you will need to assign the two tabs - but then place the code for the standard inner tabs .The_PropertyGrid object is what holds the property for the table , That is what you will most likely need to do - what I would try to do is disect the actual markup and move it around in the browsers Developer tools area (where you can manipulate the html) then you can get an Idea of what you need to do to create the proper template .

**Comment by stixoffire** [comment]
@djhonb 
[is it possible split form fields across multiple tabs in a dialogue?
is it possible to nest tabs in a dialogue?](https://github.com/volkanceylan/Serenity/issues/2148)
https://github.com/volkanceylan/Serenity/issues/2148
