### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5102]
Is there any chance of adding support for Browser push notifications?

[Using the Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)

**Comment by stixoffire** [comment]
Can be that the GridEditorBase could be modified and or extended .. I like the link you provided .. I would like to try it - but I am swamped  right now .. if you caught me 4 months ago I would have done it.

**Comment by volkanceylan** [comment]
You may add it using that doc.

**Comment by juliermefelix** [comment]
I'm also interested in using the serenity API, but I don't know how to do it.
@welcometoall  
You got it? Could you show the way?
