### ISSUE TITLE
AccountLogin page didn't show corrently

### ISSUE THREAD

**Issue by hepe00** [volkanceylan/Serenity#5106]
Hi,  when i used a serenity template, the AccountLogin page didn't show corrently , but within any exceptions.

how can i do to check that ?

![1](https://user-images.githubusercontent.com/47873631/87280556-dc13c880-c524-11ea-8197-c18d7801d935.png)

**Comment by JohnRanger** [comment]
@hepe00 ,

if this is an .net **core** app, this is a known and documented issue.

Directly after you have deployed a new project from template, do a **dotnet restore**, followed by a **dotnet sergen restore**.

Then all components (including the missing content stuff) is restored into your new project.

Hope, this helps.

With kind regards,

John

**Comment by hepe00** [comment]
Hi , @John.

It works for me , thank for your kindesssly.

Best wishes. 

Hepe00

**Comment by volkanceylan** [comment]
This should be done automatically while creating project, not sure what causes this, maybe an error in Visual Studio or environment problem

**Comment by JohnRanger** [comment]
Hi @volkanceylan ,

I am regularly having this problem - whenever I deploy a fresh .net core serene project from the VS gallery (I am doing this every few weeks when I am testing something or so). I am always on newest VS 2019 community revision (not preview) and newest serene template.

I am on Windows 10 x64.

Not one of these deployments worked without doing a manual dotnet sergen restore. - But as long as I remember doing this, everything works pretty fine 👍 

Regards,

John

**Comment by Jaccoky** [comment]
Hi,

I am new to Serenity and I struggled for quite some hours with this issue as well. Maybe you could add this tip to the 'Getting started' manual.

Bye,
Jacco

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
