### ISSUE TITLE
Overlay on xxGrid

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5109]
Hi

How to create overlay on xxGrid?

Thank you

**Comment by JohnRanger** [comment]
@ms4hafiz ,

what exactly do you want to achieve? Please show us a mockup for easier understanding.

With kind regards,

John

**Comment by ms4hafiz** [comment]
Hi @JohnRanger ;

For certain users I want to hide the records in grid and display a message that It is being used by some one else. There might be a better solution for the same but I needed a quick solution. 

I don't want Multi tenancy to achieve this because it is a kind staging table and should be only by one user at the same time and this message will conditionally appear on top of the grid.

![image](https://user-images.githubusercontent.com/20435849/87615201-6592e880-c727-11ea-8217-0e25baa2cf07.png)

Thank you

**Comment by stixoffire** [comment]
@ms4hafiz I think @JohnRanger did something like this for disabling a grid , but I don't remember the exact post. Disabling Grid editor .

What you can do is is use JQuery find the element by class name , then insert your overlay on top .. if I am not mistaken you you can simply add the class to the <div> or some other identifier. you can include an onClick event to prevent other clicking

`this.element.find("myGrid").AddCssClass("overlay")`
so you end up with something like this <div class="overlay"></div> Check your browser via F12 inspect for the right division to get..
the #overlay might need to be changed to .overlay in your css file - as I think # is for Id of elements..

```
#overlay {
  position: fixed; /* Sit on top of the page content */
  display: none; /* Hidden by default */
  width: 100%; /* Full width (cover the whole page) */
  height: 100%; /* Full height (cover the whole page) */
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0,0,0,0.5); /* Black background with opacity */
  z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
  cursor: pointer; /* Add a pointer on hover */
}
```

**Comment by JohnRanger** [comment]
Hi @ms4hafiz ,

@stixoffire was faster than I with the reply ;-) ... but his reply is exactly along the line what I would have proposed. F12 the grid in question and find the dom element which displays the grid. And then use jQuery after the dom is fully loaded to add an overlay div directly in front of the grid element with a higher z-index. Or - if you want to be radical - delete the original grid from the dom and replace it with the overlay. So noone can just simply remov the overlay by F12 your page and delete the overlay ;-) ...

With kind regards,

John

**Comment by ms4hafiz** [comment]
@JohnRanger and @stixoffire 

Thanks for the guides tipes.
