### ISSUE TITLE
Checking UniqueConstraint validation on field change

### ISSUE THREAD

**Issue by Sevigorr** [volkanceylan/Serenity#5112]
Is it possible to validate a UniqueConstraint from a dialog? 

I have the unique constraint set on my row, it works correctly when saving the entry. 

Except I need the ability to check this constraint on field change. Calling this.validateForm() and this.validateBeforeSave() doesn't check the UniqueConstraints, even when I have the CheckBeforeSave set to true.

**Comment by edwardch** [comment]
Uniqueness is usually caught on save at the database-level, you can try do a IF EXISTS select in your endpoint, check something like this #4625

**Comment by Sevigorr** [comment]
@edwardch I actually stumbled upon your linked issue yesterday when searching to see if checking UniqueConstraints on the fly was possible. I just wanted to be sure there wasn't a better way to check this validation, As I knew creating a service request and doing an exists query would work. 

But nonetheless, it does appear I'll need to create a new service request in my endpoint. 

But just in case someone else runs is looking to do some "UniqueConstraint" validation on field change, here's what I did...

xyzEndpoint.cs
`
public ServiceResponse ValidateUniqueConstraint(IDbConnection connection, UniqueConstraintRequest request)
 {
            bool IsValid = !connection.Exists<xyzRow>(xyzRow.Fields.IDToCheck == request.IDToCheck && 
                        xyzRow.Fields.UniqueValuePerID == request.UniqueValuePerID);

            if (!IsValid)
            {
                throw new ValidationError("This Purchase Order has already been entered for this Customer.");
            }

            return new ServiceResponse();
}
`

I just threw this at the bottom of xyzEndPoint.cs for now, 
`
public class UniqueConstraintRequest : ServiceRequest
    {
        public int IDToCheck { get; set; }
        public string UniqueValuePerID { get; set; }
    }
`

Then in my dialog.ts constructor I added....

`
this.form.xyzField.changeSelect2(e =>
            {
                xyzService.ValidateUniqueConstraint({
                    IDToCheck: <any>this.form.IDToCheckField.value,
                    UniqueValuePerID : this.form.xyzField.value
                }, response => {});
            });
`

In my dialog.ts, I used "changeSelect2" instead of addValidationRule because I'm throwing the validation error directly in my endpoint and there's no need for the return value that addValidationRule requires.
