### ISSUE TITLE
Asp.net Core Login Page Not Loading

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#5113]
Hi,
I have created an asp.net core serenity project. When I run it, the login page does not load fully. Below is the image.

Please help.

![asp net core error](https://user-images.githubusercontent.com/14317420/87526506-733e6480-c67a-11ea-994f-75ff8d3e7188.PNG)

**Comment by juliermefelix** [comment]
@gfo2007 
I have the same problem. how did you solve it?

**Comment by zengxinle** [comment]
How to solve ?
