### ISSUE TITLE
Height in Dialog as Panel

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#5116]
Hi all,

I am displaying a Dialog as a Panel, but the height of the tab content is not displayed correctly.

When a grid is used and then a Dialog is opened as a panel then it does display correctly.

Can you help me?

![image](https://user-images.githubusercontent.com/11929923/87879569-aa35b280-c9b9-11ea-919f-c84ac1ae9ace.png)

![image](https://user-images.githubusercontent.com/11929923/87879507-3dbab380-c9b9-11ea-8b43-3752a4b1d75e.png)

**Comment by karimQasem** [comment]
check this : https://github.com/volkanceylan/Serenity/issues/1882#issuecomment-278366036

**Comment by ArsenioInojosa** [comment]
> check this : [#1882 (comment)](https://github.com/volkanceylan/Serenity/issues/1882#issuecomment-278366036)

Thanks for the reply but it doesn't work for what I want.

**Comment by karimQasem** [comment]
in file css : `...\Content\site\site.css` i find CSS for height Panel for Module Northwind Customer Dialog Panel
```
.s-Northwind-OrderDialog.s-Panel,
.s-Northwind-CustomerOrderDialog.s-Panel {
  min-height: 750px;
}
```
so you need to add `min-height: 750px;` to class css  `.s-Dialog, .s-Panel`

**Comment by ArsenioInojosa** [comment]
Hello, the file ...\Content\ site\site.css should not be modified manually because it is generated automatically when the project is compiled.

On the other hand 750px is a static value, it is not suitable for all screens.

**Comment by karimQasem** [comment]
but it works for me, I add `min-height: 750px`; and i test for all screens, everything is fine.
and for all screens the default value `min-heigh` in serenity is 750px.

**Comment by ArsenioInojosa** [comment]
If it works for you, I'm happy for you.

Can you tell where it is set that in Serenity the min-heigh is 750px?

**Comment by karimQasem** [comment]
in `...\Content\site\site.css`
```
.s-Northwind-CustomerDialog.s-Panel {
  min-height: 750px;
}
```
```
.s-Northwind-OrderDialog.s-Panel,
.s-Northwind-CustomerOrderDialog.s-Panel {
  min-height: 750px;
}
```
I suggested a solution only. Is modifying CSS , Try modifying

**Comment by ArsenioInojosa** [comment]
> for Module Northwind Panels in `...\Content\site\site.css`
> 
> ```
> .s-Northwind-CustomerDialog.s-Panel {
>   min-height: 750px;
> }
> ```
> 
> ```
> .s-Northwind-OrderDialog.s-Panel,
> .s-Northwind-CustomerOrderDialog.s-Panel {
>   min-height: 750px;
> }
> ```
> 
> I suggested a solution only. Is modifying CSS , Try modifying


That CSS is the result of compiling site.northwind.less

```
.s-Northwind-CustomerDialog.s-Panel {
    .categories {
        height: auto;
    }

    min-height: 750px;
}

.s-Northwind-OrderDialog.s-Panel, .s-Northwind-CustomerOrderDialog.s-Panel {
    .categories {
        height: auto;
    }

    min-height: 750px;

    .grid-container {
        min-height: 300px;
    }
}

```
We will close the topic. I need to solve my problem. At another time we can talk about why min-height: 750px is not a suitable solution.

Thanks

**Comment by karimQasem** [comment]
I know my friend that it is not a perfect solution but I tried to help you .

**Comment by JohnRanger** [comment]
@ArsenioInojosa ,

if min-height: 750px does not work for you, then you need to calculate the necessary min-height dynamically after the dom is fully loaded, by 

1) querying the height of the diverse involved dom elements with javascript - parent dom element, all other sibling elements
2) calculate the min-height by doing height of parent minus height of all other sibling elements
3) set min-height of your s-panel css  via javascript to the value which you got with (2)

With kind regards,

John

**Comment by ArsenioInojosa** [comment]
Closed without solution.
