### ISSUE TITLE
How to write Logs especially expcetions on serenity core

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#5117]
How to write Logs especially expectations on serenity core since it's not working like asp.net mvc version of serenity

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
