### ISSUE TITLE
Postgresql Support PostgresException: 42P01: relation "Languages" does not exist

### ISSUE THREAD

**Issue by doutdex** [volkanceylan/Serenity#5118]
Hi

Trying to start using postgresql with serenity I set config from https://serenity.is/docs/postgresql

however I can't find SiteInitialization.cs file ->         SqlSettings.AutoQuotedIdentifiers = true;

Please could you help me

Exception

An unhandled exception occurred while processing the request.

PostgresException: 42P01: relation "Languages" does not exist
Npgsql.NpgsqlConnector+<>c__DisplayClass160_0+<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()

Stack Query Cookies Headers Routing
PostgresException: 42P01: relation "Languages" does not exist
Npgsql.NpgsqlConnector+<>c__DisplayClass160_0+<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
Npgsql.NpgsqlConnector+<>c__DisplayClass160_0+<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
Npgsql.NpgsqlDataReader.NextResult(bool async, bool isConsuming)
Npgsql.NpgsqlDataReader.NextResult()
Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, bool async, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
Serenity.Data.SqlHelper.ExecuteReader(IDbConnection connection, string commandText, IDictionary<string, object> param)
Serenity.Data.EntitySqlHelper.ForEach(SqlQuery query, IDbConnection connection, Action callBack)
Serenity.Web.RowLookupScript<TRow>.GetItems()
Serenity.Web.LookupScript.GetScript()
Serenity.Web.DynamicScriptManager+Item.GenerateContent()
Serenity.Web.DynamicScriptManager+Item.EnsureContentBytes()
Serenity.Web.DynamicScriptManager.GetScriptText(string name)
AspNetCore.Views_Shared__LayoutHead.ExecuteAsync() in _LayoutHead.cshtml
+
    @Html.Raw(DynamicScriptManager.GetScriptText("Lookup.Administration.Language"))
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, object model, IView view)
Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
AspNetCore.Views_Shared__LayoutNoNavigation.<ExecuteAsync>b__9_0() in _LayoutNoNavigation.cshtml
+
    <partial name="@MVC.Views.Shared._LayoutHead" />
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore.Views_Shared__LayoutNoNavigation.ExecuteAsync() in _LayoutNoNavigation.cshtml
+
<html lang="@System.Globalization.CultureInfo.CurrentUICulture.Name"@Html.Raw(rtl ? " dir=\"rtl\"" : "")>
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)
StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

appsettings.json

  "Data": {
    "Default": {
      "ConnectionString": "Server=127.0.0.1;Database=bd1;User Id=postgres;Password=xxxx;",
      "ProviderName": "Npgsql"
    },
    "Northwind": {
      "ConnectionString": "Server=127.0.0.1;Database=bd1;User Id=postgres;Password=xxxx;",
      "ProviderName": "Npgsql"
    }

Startup.cs
        public static void RegisterDataProviders()
             DbProviderFactories.RegisterFactory("Npgsql", Npgsql.NpgsqlFactory.Instance);

**Comment by edwardch** [comment]
You have to manually add this line in SiteInitialization.cs.

I got Postgres working about a month ago (this was my first time trying it with Serenity), it definitely does work.

Can you try manually adding that AutoQuotedIdentifiers setting, if you still have trouble let me know and I can try look tomorrow.

**Comment by edwardch** [comment]
Looking at it now, I had added this to my Startup.cs and seemed to work fine
```cs
    public partial class Startup
    {
        public Startup(IConfiguration configuration, IWebHostEnvironment hostEnvironment)
        {
            Configuration = configuration;
            HostEnvironment = hostEnvironment;
            // Add this line
            SqlSettings.DefaultDialect = PostgresDialect.Instance;
        }
/// ...
        // Bottom of file
        public static void RegisterDataProviders()
        {
            DbProviderFactories.RegisterFactory("System.Data.SqlClient", SqlClientFactory.Instance);
            DbProviderFactories.RegisterFactory("Microsoft.Data.Sqlite", Microsoft.Data.Sqlite.SqliteFactory.Instance);
            // to enable POSTGRES: add Npgsql reference, set connections, and uncomment line below
            DbProviderFactories.RegisterFactory("Npgsql", Npgsql.NpgsqlFactory.Instance);
        }
```

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform

**Comment by ArmelleBouveret** [comment]
The first message is generated because the tables do not exist.
Indeed, in appsettings.json, the default name of the database has been changed to "bd1".
In the DataMigration.cs file line 200, a protection prevents the database from being modified.
In your case, you must comment these lines to let the migration run.
