### ISSUE TITLE
SQL Generation Steps for OuterApply 

### ISSUE THREAD

**Issue by fwd079** [volkanceylan/Serenity#5120]
Hi,

**Shorter version:** 
Found out today that Serenity picks `OUTER APPLY` clause in its query builder **before** it goes for `LEFT JOIN` values in `XyzRow.cs` class, causing errors (there is a workaround causing more data reads than needed).

**Longer version:** 
So in practical terms, if we have a `LeftJoin` on a property in `XyzRow.cs` class and want to use that left join in `OuterApply` to limit data reads, Serenity throws a SQL error:
```
The multi-part identifier "jLeftJoinedTable.foreign_key_column" could not be bound.
```
That means, instead of generating a SQL with main tables and Property LeftJoins first e.g. the expected SQL would be:

```sql
SELECT * FROM [schema].[main_table] AS T0
LEFT JOIN [schema].[property_table] AS jLeftJoinedTable ON T0.foreign_key_column = jLeftJoinedTable.foreign_key_column
OUTER APPLY
(
	SELECT DISTINCT
		[outer_table].[column_id],
		[outer_table].[column_name],
		[outer_table].[effected_date]
	FROM [schema].[some_other_table] AS [outer_table]
	WHERE jLeftJoinedTable.outer_table_related_id = outer_table.id
)outerTable
```

The generated code for `XyzRow.cs` class actually comes out as.

```sql
SELECT * FROM [schema].[main_table] AS T0
OUTER APPLY
(
	SELECT DISTINCT
		[outer_table].[column_id],
		[outer_table].[column_name],
		[outer_table].[effected_date]
	FROM [schema].[some_other_table] AS [outer_table]
	WHERE jLeftJoinedTable.outer_table_related_id = outer_table.id
)outerTable
LEFT JOIN [schema].[property_table] AS jLeftJoinedTable ON T0.foreign_key_column = jLeftJoinedTable.foreign_key_column
```

This causes `The multi-part identifier` error mentioned above.

The workaround would be to force more data reads than necessary:

```csharp
[OuterApply("outerTable", @"
	SELECT DISTINCT
		[outer_table].[column_id],
		[outer_table].[column_name],
		[outer_table].[effected_date]
	FROM [schema].[some_other_table] AS [outer_table]
	LEFT JOIN [schema].[a_third_table] AS [unnecessary_joined_table] ON outerTable.column = unnecessary_joined_table.column
	LEFT JOIN [schema].[main_table] AS T1 ON a_third_table.some_column = T1.some_column
	LEFT JOIN [schema].[property_table] AS jLeftJoinedTable ON T1.foreign_key_column = jLeftJoinedTable.foreign_key_column
	WHERE jLeftJoinedTable.outer_table_related_id = outer_table.id
"])
// XyzRow code..
```

This makes for a painful SQL where we'd want just a setting label etc.

Interestingly, if we bypass `List()` method of `XyzRepository.cs` class and instead follow this:

```csharp
[OuterApply("outerTable", @"
	SELECT DISTINCT
		[outer_table].[column_id],
		[outer_table].[column_name],
		[outer_table].[effected_date]
	FROM [schema].[some_other_table] AS [outer_table]
	WHERE jLeftJoinedTable.outer_table_related_id = outer_table.id
")]
// XyzRow code..

```

Then in XyzRepository.cs create a method:

```csharp
List<XyzRow> CustomListMethod()
{

	// Get latest by create datetime descending.
	void action(SqlQuery query)
	{
		query.Distinct(true);
		query.SelectTableFields();
		query.SelectNonTableFields();
		// query.DebugText.Dump("--List OuContractWeeklyActivityEventRow"); <= checked in LINQPad 6
		//query.ToString().Dump("--GetOUsByPostAssignment");
	}

	List<XyzRow> rows = null;
	using (var connection = SqlConnections.NewByKey(fld.ConnectionKey))
	{
		rows = connection.List<XyzRow>(action);		
	}
	return rows;
}

// XyzRepository code...
```

Then the SQL is correctly generated as:

```sql
SELECT * FROM [schema].[main_table] AS T0
LEFT JOIN [schema].[property_table] AS jLeftJoinedTable ON T0.foreign_key_column = jLeftJoinedTable.foreign_key_column
OUTER APPLY
(
	SELECT DISTINCT
		[outer_table].[column_id],
		[outer_table].[column_name],
		[outer_table].[effected_date]
	FROM [schema].[some_other_table] AS [outer_table]
	WHERE jLeftJoinedTable.outer_table_related_id = outer_table.id
)outerTable
```

Please can this be looked into? Will save us from creating unnecessary `CustomList()` methods in repositories.

Kind Regards.

**Comment by volkanceylan** [comment]
Outer apply is just another kind of join (just like LeftJoin, but you can't simply apply OuterApply on a field directly, but only on top of a row), all joins in your row must have a different join alias, then you may reference that join alias in your field expressions.

You don't need custom list method, i don't understand why you have a custom method.

**Comment by volkanceylan** [comment]
If your issue is about order, then select a column in left joined table so that the join is included in query before outer apply.

**Comment by fwd079** [comment]
> Outer apply is just another kind of join (just like LeftJoin, but you can't simply apply OuterApply on a field directly, but only on top of a row), all joins in your row must have a different join alias, then you may reference that join alias in your field expressions.
> 
> You don't need custom list method, i don't understand why you have a custom method.
>
>
Thanks for looking into it, appreciate it.

Yes I am aware of `OUTER APPLY` vs `LEFT JOIN` etc. and how they work in Serenity, one being on a class and other on a Property, also you did understand why I needed a custom method as this below comment shows. Otherwise SQL Server generates the error `The multi-part identifier "jLeftJoinedTable.foreign_key_column" could not be bound.` at runtime.  
  
>  
>
> If **your issue is about order**, then select a column in left joined table so that the join is included in query before outer apply.
>
>   
  

Exactly, the issue is _how_ Serenity generates/emits the SQL for `XyzRow.cs`. Serenity **actually generates incorrect SQL** if an `OuterApply` Attribute's SQL uses a property, as its `WHERE` clause value, within `XyzRow.cs` with `LeftJoin` Attribute set on it.  Please see example at the end, for clarity.

So if I understand you correctly, then perhaps the problem occurs because I do not want to select something from `LeftJoin` table inside my `OuterApply` Attribute's SQL query. Why bring in a field twice?

Anyway, currently `CustomListMethod()` is the only way I could see to use a field from `jLeftJoinedTable` into `OuterApply` Attribute's SQL. 

That is why suggestion is that **Serenity should always emit SQL query in same way** as below example suggests,  whether or not a `LeftJoin` table is selected inside an `OuterApply` Attribute's SQL, it should always be **above** `OUTER APPLY` statement, to save SQL from generating runtime errors. (this below correct SQL was emitted when we use  `CustomListMethod()` instead of `List()` method).

```sql
SELECT * FROM [schema].[main_table] AS T0
LEFT JOIN [schema].[property_table] AS jLeftJoinedTable  -- <= LEFT JOIN is written in correct order.
        ON T0.foreign_key_column = jLeftJoinedTable.foreign_key_column
OUTER APPLY
(
	SELECT DISTINCT
		[outer_table].[column_id],
		[outer_table].[column_name],
		[outer_table].[effected_date]
	FROM [schema].[some_other_table] AS [outer_table]
	WHERE
        [jLeftJoinedTable].[outer_table_related_id] = [outer_table].id -- <= jLeftJoinedTable value used only in WHERE clause.
) AS outerApplyAlias
```

Kind Regards.

**Comment by volkanceylan** [comment]
You don't need to bring in a field in your outer apply. You just need to ensure the join you want to come first is used first in your repository or wherever you build your query.

Serenity repository never generates a query with "*", you probably omitted your select list from the generated query. I suspect your row has a field that is coming from that outer apply before a field that is coming from that left join.

Serenity auto includes joins when they are referenced by a SELECT or WHERE statement including fields / expressions that reference them. And it only checks ON statement to identify the best order it should apply those joins, even when fields are selected out of order. There is no code that checks the inner query in an outer apply and perform that logic. We could check that but i don't remember why, probably added OUTER APPLY in a later phase, and initially didn't consider that as other types of JOINS only has expressions on their ON statement. If you check source code of Join.cs it only locates join aliases in criteria parameter, not tablename (which corresponds to inner query in OuterApply). Should add a virtual method to also check the table, only for OuterApply (fancy sending a pull request?)

Anyway, as i said just ensure your row selects a field from that LEFT JOIN first, before OUTER APPLY, or override CreateQuery in your repository List method and call EnsureJoinsInExpression like:
```cs
            protected override SqlQuery CreateQuery()
            {
                return base.CreateQuery().EnsureJoinsInExpression("jYourLeftJoin.anything");
            }
```

**Comment by volkanceylan** [comment]
Hmm actually there is a code block that checks expressions in toTable, don't understand how it happens in your case, need to debug.
```cs
            var toTableAliases = JoinAliasLocator.Locate(this.Table);
            if (toTableAliases != null && toTableAliases.Count > 0)
            {
                if (referencedAliases == null)
                    referencedAliases = toTableAliases;
                else
                {
                    foreach (var x in toTableAliases)
                        referencedAliases.Add(x);
                }
            }
```

**Comment by volkanceylan** [comment]
Please check this commit with a row similar to yours and the test for it:

https://github.com/volkanceylan/Serenity/commit/875fd6dc9c9493ab3b2ecfbcc7401cef227b933d

I got expected results with your outer apply statement. Need to identify what is different with your row.

**Comment by fwd079** [comment]
Very interesting, quick testing reveals it is still broken on my `xyzRow.cs` sadly. But  will deep dive on it later since workaround, well, works, and I am currently on another part of project. But thanks for that, doesn't look like it should break, but it does.

Closing the issue for now, will reopen when come back to this. 

Kind Regards.
