### ISSUE TITLE
Point of sales.

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#5121]
Dear,
I need an example of a point of sale using Serenity, whoever has and can make it available with me please send an example to the email juliermefelix@gmail.com.

thank you!

**Comment by JohnRanger** [comment]
Hi @juliermefelix ,

I don't have a ready example and never seen something similar here - but a POS app would probably need at least a touch kassa and eventually even must be PCI DSS compliant if it also has to process payments made with credit cards (that depends on the app and api integration which the customer's payment card processor can provide).

Depending on the scope of your app (should it become a general usable product - or is it a one fit for a specific customer situation) you will have to support many different payment processors.

We are talking here about things which each easily can outdo the whole (already big) Serenity Framework in terms of complexity.

A quick search with Google did not reveal any free - open source - C#-based POS solution to me.

But - of course - if someone else here has already done such a thing and is willing to share it- I don't want to stand in the way ;-)

With kind regards,

John
