### ISSUE TITLE
report authentication error with active directory

### ISSUE THREAD

**Issue by tmartinscopo** [volkanceylan/Serenity#5122]
Hello,

I am using active directory / windows authenticaion in IIS. 
In reports/pdf and when executing /report/render I get an authentication error (HTTP Error 401.2 - Unauthorized).
If I activate anonymous mode in IIS it works without a problem. What's missing?

I mean., PDF is generated but it shows inside "Error HTTP 401.2 - Unauthorized". Rendering in HTML is ok!

Thx

**Comment by tmartinscopo** [comment]
![image](https://user-images.githubusercontent.com/37545074/88416780-af8b6680-cdd8-11ea-8a6e-6292a5ea91ab.png)

What's missing?

**Comment by tmartinscopo** [comment]
With forms authentication it works!
What's missing with AD authentication?

**Comment by volkanceylan** [comment]
Your server makes a request to itself using wkhtml to render pdf, so you should find a way to authenticate wkhtml itself.

**Comment by volkanceylan** [comment]
Don't ask me how, i don't use AD auth in IIS...

**Comment by tmartinscopo** [comment]
Thanks Volkan. Anyone using AD auth in IIS and rendering PDF ?

**Comment by tmartinscopo** [comment]
Found it! Just add thids: 

public void Customize(IHtmlToPdfOptions options)
{
....
options.CustomArgs.Add("--username");
options.CustomArgs.Add("username");
options.CustomArgs.Add("--password");
options.CustomArgs.Add("password");
...
}
