### ISSUE TITLE
Date picker icon missing

### ISSUE THREAD

**Issue by jimmybanegas93** [volkanceylan/Serenity#5123]
![image](https://user-images.githubusercontent.com/2421080/88462162-831e2b80-ce66-11ea-8b59-1128d4b7699d.png)

I've been working on a project and I keep getting this problem with the date picker icon, it's missing.

Things I've tried: 
1. https://github.com/volkanceylan/Serenity/issues/2895 (Replacing what this thread mentions, but login gets messed up)
2. https://github.com/volkanceylan/Serenity/issues/2861 (Setting minification to false)
3. Installed serin, update to latest packages, restoring packages, none seem to work.

Here's my current ScriptBundles.json

`{
  "Base": [
    "~/Scripts/pace.js",
    "~/Scripts/jquery-ui.js",
    "~/Scripts/jquery-ui-i18n.js",
    "~/Scripts/jquery.validate.js",
    "~/Scripts/jquery.blockUI.js",
    "~/Scripts/jquery.cookie.js",
    "~/Scripts/jquery.json.js",
    "~/Scripts/bootstrap.js",
    "~/Scripts/select2.js",
    "~/Scripts/toastr.js",
    "~/Scripts/vegas/vegas.js",
    "~/Scripts/saltarelle/mscorlib.js",
    "~/Scripts/serenity/Serenity.CoreLib.js"
  ],
  "Site": [
    "~/Scripts/jquery.autoNumeric.js",
    "~/Scripts/jquery.colorbox.js",
    "~/Scripts/jquery.dialogextendQ.js",
    "~/Scripts/jquery.event.drag.js",
    "~/Scripts/jquery.maskedinput.js",
    "~/Scripts/jquery.scrollintoview.js",
    "~/Scripts/sortable.js",
    "~/Scripts/SlickGrid/slick.core.js",
    "~/Scripts/SlickGrid/slick.grid.js",
    "~/Scripts/SlickGrid/slick.groupitemmetadataprovider.js",
    "~/Scripts/SlickGrid/Plugins/slick.autotooltips.js",
    "~/Scripts/SlickGrid/Plugins/slick.headerbuttons.js",
    "~/Scripts/SlickGrid/Plugins/slick.rowselectionmodel.js",
    "~/Scripts/SlickGrid/Plugins/slick.rowmovemanager.js",
    "~/Scripts/jquery.fileupload.js",
    "~/Scripts/jquery.iframe-transport.js",
    "~/Scripts/jquery.slimscroll.js",
    "~/Scripts/mousetrap.js",
    "~/Scripts/vue.js",
    "~/Scripts/adminlte/app.js",
    "~/Scripts/site/CustomsAgencyManagementSystem.Web.js",
    "dynamic://ColumnsBundle",
    "dynamic://FormBundle",
    "dynamic://TemplateBundle"
  ],
  "CKEditor": [
    "~/Scripts/ckeditor/ckeditor.js",
    "~/Scripts/ckeditor/lang/en.js",
    "~/Scripts/ckeditor/styles.js"
  ],
  "NorthwindLookups": [
    "dynamic://Lookup.Northwind.Category",
    "dynamic://Lookup.Northwind.Customer",
    "dynamic://Lookup.Northwind.CustomerCountry",
    "dynamic://Lookup.Northwind.CustomerCity",
    "dynamic://Lookup.Northwind.Employee",
    "dynamic://Lookup.Northwind.Shipper",
    "dynamic://Lookup.Northwind.OrderShipCountry",
    "dynamic://Lookup.Northwind.OrderShipCity",
    "dynamic://Lookup.Northwind.Product",
    "dynamic://Lookup.Northwind.Region",
    "dynamic://Lookup.Northwind.Supplier",
    "dynamic://Lookup.Northwind.Territory"
  ],
  "Pages/Dashboard": [
    "~/Scripts/raphael/raphael-min.js",
    "~/Scripts/morris/morris.min.js",
    "~/Scripts/sparkline/jquery.sparkline.min.js",
    "~/Scripts/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "~/Scripts/jvectormap/jquery-jvectormap-world-mill-en.js",
    "~/Scripts/knob/jquery.knob.js",
    "~/Scripts/daterangepicker/moment.min.js",
    "~/Scripts/daterangepicker/daterangepicker.js",
    "~/Scripts/datepicker/bootstrap-datepicker.js",
    "~/Scripts/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js",
    "~/Scripts/adminlte/pages/dashboard.js",
    "~/Scripts/adminlte/demo.js"
  ]
}
`

**Comment by volkanceylan** [comment]
You should inspect icon and see the url and if thats there

**Comment by volkanceylan** [comment]
Are you using linux btw?

**Comment by Davidwsk** [comment]
I am having same issue.
It happen on IE, Edge and Chrome.

I am using Windows.
"Serenity.Web" Version="3.13.7"
"Serenity.Web.Assets" Version="3.9.2"
"Serenity.Scripts" Version="3.13.7"

![Date picker icon mssing](https://user-images.githubusercontent.com/31944359/88607074-dd123180-d0b0-11ea-989f-1cd9624c998b.png)

**Comment by arunkumar12712** [comment]
same problem here

i am using windows & asp.netcore

**Comment by JohnRanger** [comment]
@jimmybanegas93 ,

directly after you have created your new porject from the VS template did you:

1) dotnet restore
2) dotnet sergen restore?

With kind regards,

John

**Comment by jimmybanegas93** [comment]
> @jimmybanegas93 ,
> 
> directly after you have created your new porject from the VS template did you:
> 
> 1. dotnet restore
> 2. dotnet sergen restore?
> 
> With kind regards,
> 
> John

@JohnRanger I did, actually I just created a brand new project because I wasn't sure. But still same issue. :/

**Comment by sjcdtm** [comment]
I had a similar issue when I updated to 13.3.4 (see #5090 ), which seemed to be caused by the data URI for the icon being incorrectly formed. A fix for this is mentioned in 13.12.6 - reverting to this solved the problem for me although I can't use the latest version for now. I don't know if the bug came back or if I did something wrong but this has helped me for now.

**Comment by choss21** [comment]
SameProblem :(

**Comment by volkanceylan** [comment]
It should be resolved in 3.14.0, please update and don't forget to run dotnet sergen restore after.

**Comment by minhhungit** [comment]
it works for me after upgrading to 3.14.0

**Comment by arunkumar12712** [comment]
it working.

**Comment by jimmybanegas93** [comment]
Great, it is working for me too. Thanks @volkanceylan  for fixing that for us!

**Comment by younis-source** [comment]
> It should be resolved in 3.14.0, please update and don't forget to run dotnet sergen restore after.

How to run (dotnet sergen restore) in asp.net core ?
