### ISSUE TITLE
Not working NewProject SereneTemplate NetCore

### ISSUE THREAD

**Issue by choss21** [volkanceylan/Serenity#5124]
![image](https://user-images.githubusercontent.com/13734677/88464316-46aaf980-ce7f-11ea-9690-5bab0aaa1298.png)

![image](https://user-images.githubusercontent.com/13734677/88464295-24b17700-ce7f-11ea-9c75-16eaba5714b6.png)

**Comment by minhhungit** [comment]
try to run 2 commands:

>dotnet restore
>dotnet sergen restore

then rebuild

**Comment by choss21** [comment]
Thank you

it works now
