### ISSUE TITLE
How to make automatic login using serenity

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5127]
Hi

I need help in automatic login with serenity. I have a default user and password that would like to automatically sign in when the page is loaded.

Thank you

**Comment by JohnRanger** [comment]
Yes - I am looking for this too - Is useful when creating an Electron App out of a Serene App which does not need login.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
