### ISSUE TITLE
"0,0000" format problem

### ISSUE THREAD

**Issue by fatihsimsekk** [volkanceylan/Serenity#5128]
row

 [DisplayName("Kabul Tutar"), Column("kabul_tutar"),  DisplayFormat("#,##0.00"), Size(19), Scale(4)]
        public Decimal? KabulTutar
        {
            get { return Fields.KabulTutar[this]; }
            set { Fields.KabulTutar[this] = value; }
        }

form
 [DisplayFormat("#,##0.00"), AlignRight]
        [HalfWidth]

       
        public Decimal? KabulTutar { get; set; }

money type in the database

Hello, I'm new to the seren, sorry
Although I set it this way, it still shows "0.0000" after the comma. How can I make it two zeros?

**Comment by volkanceylan** [comment]
Is this shown in editor or grid?

**Comment by fatihsimsekk** [comment]
yes it is shown when i write the same code to colums but it is not in the form[
![dene1](https://user-images.githubusercontent.com/55793437/88576963-ee2a5680-d04e-11ea-819d-5aac86d9a004.PNG)
![dene32](https://user-images.githubusercontent.com/55793437/88576969-ef5b8380-d04e-11ea-8d63-ce1d845d1987.PNG)

](url)

**Comment by JohnRanger** [comment]
@volkanceylan ,

so then it is in the form - not grid.

With kind regards,

John

**Comment by volkanceylan** [comment]
Display format does not apply to editors

**Comment by volkanceylan** [comment]
Use DecimalEditor and min max value to control decimals, or set Scale properly
