### ISSUE TITLE
xxxxrepository.update()

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5129]
I get a entity by connection.byid<xxrow>(id),
And I change one of the fields, xxrow.xxfield=xx, then I call update function, repository.update(uow,new saverequest{
	entity=xxxrow
});
I only want to update xxfield into datatable.
but I found all the fields in xxrow are updated into datatable, includes the fields which are not changed.

Is it possible only update fields which has changed into datatable?

**Comment by volkanceylan** [comment]
use connection.UpdateById(entityId, new MyRow() { SetField1 = Value1 })

**Comment by Nathan2020-0126** [comment]
@volkanceylan thansk for your answer. I konw this function. I means in a situation like below. I have to mannual set 
 workcenterTask.WorkcenterTaskStatusId = WorkcenterTaskStatus.Finished, then return WorkcenterTaskRow.

```
 public WorkcenterTaskRow ResetWorkcenterTaskStatus(IUnitOfWork uow, WorkcenterTaskRow workcenterTask) {
            WorkcenterTaskRow _workcenterTask = new WorkcenterTaskRow
            {
                WorkcenterTaskId = workcenterTask.WorkcenterTaskId,
                WorkcenterTaskStatusId= WorkcenterTaskStatus.Finished
             };
             new WorkcenterTaskRepository().Update(uow, new SaveRequest<WorkcenterTaskRow>
             {
                 Entity = _workcenterTask
             });
            workcenterTask.WorkcenterTaskStatusId = WorkcenterTaskStatus.Finished;
            return workcenterTask;
```

I just wonder if there is a more convenient way to do it.
