### ISSUE TITLE
Can the lookup script be based on a where condition

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#513]
Can the lookup script show only a portion of master data based on value of a field.

**Comment by marcobisio** [comment]
Sure you can override the PrepareQuery() method in your lookup class and customize your where condition.

**Comment by volkanceylan** [comment]
You can use FilterField FilterValue properties.

**Comment by mrajalko** [comment]
LookupEditor("SalesDB.Party", FilterField ="P_TYPE",FilterValue ="B") syntax is not working not showing any data.

**Comment by volkanceylan** [comment]
Add LookupInclude to referenced fields

**Comment by mrajalko** [comment]
Thanks it worked. Please guide me on value for a boolean field.
I have tried "1" , "-1" and "True" without much luck

**Comment by volkanceylan** [comment]
FilterValue(true)

**Comment by mrajalko** [comment]
Thanks. FilterValue = true worked.
