### ISSUE TITLE
 Increase the number of lines

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5130]
Community, I need to increase the number of lines in the following grid:
![imagen_grilla](https://user-images.githubusercontent.com/42218266/88624544-2a70ad80-d075-11ea-8559-cf44e33401f1.png)

**Comment by patriciomh1965** [comment]
I have the following instruction in the parent XYZform:

**Comment by patriciomh1965** [comment]
namespace SegurosMAPC.BaseDatos.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;

    [FormScript("BaseDatos.MeraTenenciaMasivo")]
    [BasedOnRow(typeof(Entities.MeraTenenciaMasivoRow), CheckNames = true)]
    public class MeraTenenciaMasivoForm
    {       

        [HalfWidth]
        [Updatable(false)]
        [Hidden]
        public DateTime Periodo { get; set; } 
        [HalfWidth]
        [Updatable(false)]
        public Int32 EventoMdc { get; set; }        
        [HalfWidth]
        [Updatable(false)]
        public Int16 Estado { get; set; }

        // ARCHIVO INTERFACE
        [Category("Archivo de Carga")]
        [MeraTenenciaInterfaceEditor]
        public List<Entities.MeraTenenciaInterfaceRow> DetailList5 { get; set; } 
    }
}

**Comment by patriciomh1965** [comment]
In the parent XYZRow class I have the following instruction:

...
...

        //  VINCULACION LINEAS DE CONTRATOS
        [DisplayName(""), MasterDetailRelation(foreignKey: "imt_periodo", MasterKeyField = "mev_fecha_inicio"), NotMapped]
        public List<MeraTenenciaInterfaceRow> DetailList5
        {
            get { return Fields.DetailList5[this]; }
            set { Fields.DetailList5[this] = value; }
        }

**Comment by patriciomh1965** [comment]
If anyone knows how to do it, I would appreciate it. Atte.

**Comment by kilroyFR** [comment]
You can fix this using css

**Comment by choss21** [comment]
Use serenity.extra https://github.com/dfaruque/Serenity.Extra
Its VeryGood 
protected updateInterface() {
            super.updateInterface();
            q.initDetailEditor(this, this.form.DetailList, {
                autoHeight: true
            });
        }

**Comment by patriciomh1965** [comment]
> You can fix this using css


Do you have any example to guide me?

**Comment by minhhungit** [comment]
@patriciomh1965 check this link

https://github.com/volkanceylan/Serenity/issues/1729

**Comment by patriciomh1965** [comment]
It worked !!! Thank you all.
