### ISSUE TITLE
ForeignKey Details

### ISSUE THREAD

**Issue by eadjeidjan** [volkanceylan/Serenity#5134]
I have a table that references another table by foreign key, now i want to get the details of other columns on the foreign table, based on the id of the foreign key. how do i go about that

**Comment by fwd079** [comment]
This [tutorial step (click)](https://serenity.is/Docs/entities/mapping_attributes#foreignkey-attribute) should help you.

**Comment by eadjeidjan** [comment]
Thanks very much, I did by getting the values always return null;
example
int band = Row.CustomerDomesticBand ?? 0;

Row.CustomerDomesticBand shows null though there is a value in the column DomesticBand of the Customer

**Comment by eadjeidjan** [comment]
[DisplayName("Customer Domestic Band"), Expression("jCustomer.[DomesticBand]")]
        public Int32? CustomerDomesticBand
        {
            get { return Fields.CustomerDomesticBand[this]; }
            set { Fields.CustomerDomesticBand[this] = value; }
        }

above is an example and it returns null

**Comment by fwd079** [comment]
> [DisplayName("Customer Domestic Band"), Expression("jCustomer.[DomesticBand]")]
> public Int32? CustomerDomesticBand
> {
> get { return Fields.CustomerDomesticBand[this]; }
> set { Fields.CustomerDomesticBand[this] = value; }
> }
> 
> above is an example and it returns null

If it is .NET Core then rebuild the project, if it is .NET Framework then run relevant `*.tt` files.

**Comment by eadjeidjan** [comment]
Thanks, I'll check it out

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
