### ISSUE TITLE
slider with 3 options -1, 0, 2.5

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#5135]
Hello,

I need to make a slider with only 3 options -1, 0, 2.5, slider inserts 3 ticks (first image) but user can always select 1 or 2 (second image). How can avoid this?

![image](https://user-images.githubusercontent.com/17210232/88987149-f8f21f00-d2cc-11ea-8737-b12ea4fa2179.png)

![image](https://user-images.githubusercontent.com/17210232/88986868-170b4f80-d2cc-11ea-98ab-45e4ad038177.png)

I'm using slider in [https://github.com/volkanceylan/Serenity/issues/3100](url) with [SliderEditorAttribute(Min=1, Max=3, Ticks = "[-1, 0, 2.5]") in my form.

**Comment by JohnRanger** [comment]
Hi @teafmartins ,

a click on your link does not lead anywhere although it looks correct. 

For everyone who wants to read the linked article, just copy&paste it from teafmartins article into a now browser tab - I also tried and get the same error - Bug of Github.

Regards,

John

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
