### ISSUE TITLE
how to get CascadeFrom & CascadeField

### ISSUE THREAD

**Issue by younis-source** [volkanceylan/Serenity#5136]
I tried to follow this link https://serenity.is/docs/howto/how_to_setup_cascaded_editors 
but I dont know how to fix this problem in red line
please can I get help 
![SharedScreenshot](https://user-images.githubusercontent.com/67063459/89114275-9e52f180-d48b-11ea-8910-26eef1c95994.jpg)

**Comment by younis-source** [comment]
I mean how I can make Cascade editor... Because when I follow the link above I dont know how I can to write the code at the last page in instruction

**Comment by arunkumar12712** [comment]
please read serenity document 
try this --
[lookupeditor(typeof(TblToolsRow), CascadeFrom = "SubId", CascadeField = "SubId")]

**Comment by younis-source** [comment]
It's work thank you **arunkumar12712**
