### ISSUE TITLE
Supplier update with asmx web service

### ISSUE THREAD

**Issue by serkansonmez** [volkanceylan/Serenity#5138]
I have an XML-based web service that brings some information by ID number. http://genweb.gencer.com:9009/TigerWebService/TigerWebService.asmx?op=TcKimlikNoSorgula
1.  First of all, my goal is to bring the information over the service when the TNB button is pressed, but I have not been successful with the code below.

supplierDialog.ts

`   constructor() {
            super();

            this.dialogTitle = "Vergi Kimlik Numarasından data getirmek";

            $('<a class="inplace-button inplace-action3"><b><i class="fa fa-magic text-red"></i></b></a>')
                .attr("title", "TNB'den Veri Getir")
                .insertAfter(this.form.TaxNr.element)
                .click(e => {
                    var SoapMessage2 =   this.form.TaxNr.value ;
                    var SoapMessage = '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">   <soap:Body>     <TcKimlikNoSorgula xmlns="http://tempuri.org/">       <pTcKimlikNo>' + this.form.TaxNr.value  + '</pTcKimlikNo>     </TcKimlikNoSorgula>   </soap:Body> </soap:Envelope>';  
                    Q.notifySuccess(SoapMessage);
                   
                   
                    $.ajax({
                        url: "http://genweb.gencer.com:9009/TigerWebService/TigerWebService.asmx?op=TcKimlikNoSorgula",
                        type: "POST",
                        dataType: "xml",
                        data: SoapMessage,
                        error: function (xml2) { alert("No data found." + xml2); },
                        success: function (xml) {
                            alert("it works");
                            
                        },
                        contentType: "text/xml; charset=utf-8"
                    });  
                    

                });
            
        }`

   
![image](https://user-images.githubusercontent.com/25242018/89181460-756e5180-d59c-11ea-8df7-42a899c67185.png)

2. When the first item did not work, I tried to bring the data in the registration phase to bring the data in the registration phase, it brings the records from the web service but does not write it in the table.
Note: There is no problem when you transfer a fixed value to the variables without calling the service.

`SupplierRepository.cs
    private class  MySaveHandler : SaveRequestHandler<MyRow>
        {

            protected override async void BeforeSave()
            {
                base.BeforeSave();             
                try
                {
                    TnbRepository tnbRepository = new TnbRepository("http://genweb.gencer.com:9009/TigerWebService/TigerWebService.asmx", 100);
                    var result = await tnbRepository.TcKimlikNoSorgula(Row.TaxNr);
                    base.Row.Address = result.IkametgahAdresi.MahalleSemt + " " + result.IkametgahAdresi.CaddeSokak + " " + result.IkametgahAdresi.DaireNO + " " + result.IkametgahAdresi.KapiNO + " " + result.IkametgahAdresi.IlceAdi + " " + result.IkametgahAdresi.IlAdi + " ";
                    base.Row.TaxOffice = result.VergiDairesiAdi;

                    //base.Row.Country = "Türkiye";
                    //base.Row.Address = "address";
                    //base.Row.TaxOffice = "result.VergiDairesiAdi";

                }
                catch (Exception ex)
                {
                    throw new Exception("Hata : " + ex.Message);
                }
            }
        }`

` public class TnbRepository
    {
        // private readonly ICalculatorChannel proxy;
        private readonly TigerWebService.TigerWebServiceSoapChannel proxy;
        /// <summary>
        /// Initializes a new instance of the <see cref="T:AdamStacey.DemoCalculator.CalculatorRepository"/> class.
        /// </summary>
        /// <param name="endpointAddress">Endpoint address.</param>
        /// <param name="timeout">The timeout.</param>
        public TnbRepository(string endpointAddress, double timeout)
        {
            BasicHttpBinding binding = new BasicHttpBinding
            {
                SendTimeout = TimeSpan.FromSeconds(timeout),
                MaxBufferSize = int.MaxValue,
                MaxReceivedMessageSize = int.MaxValue,
                AllowCookies = true,
               
                ReaderQuotas = XmlDictionaryReaderQuotas.Max
            };
            binding.Security.Mode = BasicHttpSecurityMode.None;
            
            EndpointAddress address = new EndpointAddress(endpointAddress);
            ChannelFactory<TigerWebServiceSoapChannel> factory = new ChannelFactory<TigerWebServiceSoapChannel>(binding, address);
            this.proxy = factory.CreateChannel();
             
        }
        /// <summary>
        /// Adds asynchronously.
        /// </summary>
      
        public async Task<MerkezBilgiSorguSonuc> TcKimlikNoSorgula(string  pTCNo)
        {
            return await this.proxy.TcKimlikNoSorgulaAsync(pTCNo).ConfigureAwait(false);
            
        }`
Greetings.
Serkan Sönmez

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
