### ISSUE TITLE
Populate Linked Data not work by ID datatype in integer with me

### ISSUE THREAD

**Issue by younis-source** [volkanceylan/Serenity#5139]
helle everyone
I tried to make dialog that to demonstrates  refresh related fields when a joined field value changes. In Basic Samples the CustomerID is string datatype but in my project is integer datatype (EmpId) and that is not make my project work
![pp3](https://user-images.githubusercontent.com/67063459/89230382-39ff7180-d5f4-11ea-96ae-67bffb38c492.jpg)
![pp4](https://user-images.githubusercontent.com/67063459/89230476-6adfa680-d5f4-11ea-9cca-96053b97f3de.jpg)
![pp2](https://user-images.githubusercontent.com/67063459/89230488-7206b480-d5f4-11ea-948f-2407322e6646.jpg)

When I comment this line :
//var id = Q.first(AuditDb.EmpInfRow.getLookup().items, x => x.Id == empId).Id;
and change  EntityId from (id) to (empId) that will show in next picture .. the project will work but when save or update the dialog an acception will show that can not update integr in string properties
![pp5](https://user-images.githubusercontent.com/67063459/89230948-56e87480-d5f5-11ea-9733-69f743f099d9.jpg)
![pp6](https://user-images.githubusercontent.com/67063459/89230958-5e0f8280-d5f5-11ea-8e9f-a75c8563a029.jpg)

please can help me to fix that . I appreciate in advance your time.

 I dont know how to fix it , so please can anyone help

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
