### ISSUE TITLE
Create a windows service using data model from serenity project

### ISSUE THREAD

**Issue by leonidcan** [volkanceylan/Serenity#514]
How to use data model in other project?
Add new module project to serenity solution (Serenity.Module in addition to Serenity.Script/Web)?

**Comment by volkanceylan** [comment]
Yes, it's possible like that

**Comment by leonidcan** [comment]
What I meant buy adding module project is to move the data model into separate project which can be used in other projects/solutions (isolate data model from UI project). Similar to what DevExpress has for XAF. I understand this requires changes to Serenity framework.

Do you suggest to add windows service project to Serenity solution and reference Serenity.Web in it?

**Comment by volkanceylan** [comment]
You don't need Serenity.Web reference for assembly that contains entities / repositories.

**Comment by leonidcan** [comment]
Do I understand correctly, that I need create new project *.Module and add all entities from *.Web and compile into assembly? And keep it up to date with the changes I am making to *.Web project (adding/removing tables)?

**Comment by leonidcan** [comment]
I am not quite understand :(. Can you, please, give me some steps to make data model assembly project on example of MovieTutorial? I understand that MovieTutorial.Web.dll  contains data model but also much more (that's web application). I know I can create my model from database, but isn't it much better to reuse the model from main project?

**Comment by volkanceylan** [comment]
Take Rows and Repositories into a YourProject.Model or (YourProject.Entities / YourProject.Repositories) projects. Just move code. Add their project references to web project.

**Comment by leonidcan** [comment]
Ok, got it. Thank you!
