### ISSUE TITLE
Error PDF

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5140]
Hello community, I have an error when building a PDF report:

**Comment by patriciomh1965** [comment]
![error_pdf](https://user-images.githubusercontent.com/42218266/89251801-f6057000-d5e5-11ea-93b2-d9cf903a0bb0.png)


Then I have the following class:

namespace SegurosMAPC.Modules.BaseDatos.CuadraturaReporteCarteras
{
    using SegurosMAPC.BaseDatos.Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Reporting;
    using System;
    using System.Collections.Generic;

    [Report("BaseDatos.CuadraturaReporteCarteras")]
    [ReportDesign(MVC.Views.BaseDatos.CuadraturaReporteCarteras.ContratoReport)] 
    //[RequiredPermission(PermissionKeys.General)]
    public class ContratoReport : IReport, ICustomizeHtmlToPdf 
    {
        public Int32 ContratoID { get; set; }

        public object GetData()
        {
            var data = new ContratoReportData();

            using (var connection = SqlConnections.NewFor<TaMaeContratoRow>())
            {
                var o = TaMaeContratoRow.Fields;

                data.Contrato = connection.TryById<TaMaeContratoRow>(this.ContratoID, q => q
                     .SelectTableFields()
                     .Select(o.FecSuscripcion)
                     .Select(o.FecInicioSeguro)) ?? new TaMaeContratoRow();
            }

            return data;
        }

        public void Customize(IHtmlToPdfOptions options)
        {
            // you may customize HTML to PDF converter (WKHTML) parameters here, e.g. 
            // options.MarginsAll = "2cm";
        }
    }

    public class ContratoReportData
    {
        public TaMaeContratoRow Contrato { get; set; }
     
    }
}


-------------------------------------------------------------------------------------------
The view is:

@model SegurosMAPC.BaseDatos.ContratoReportData

@if ((bool?)ViewData["Printing"] == true)
{
    Layout = MVC.Views.Shared._LayoutNoNavigation;
}

<section class="invoice">
    <div class="row">
        <div class="col-xs-12">
            <h2 class="page-header">
                Invoice
                <small class="pull-right">Date: @DateTime.Now.ToShortDateString()</small>
            </h2>
        </div>
    </div>
    
    <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
            From
            <address>
                <strong>Northwind, Inc.</strong><br>
                1357 Serenity Road<br>
                Visual Studio Gallery, VS 97653<br>
                Phone: (804) 123-5432<br>
                Email: info@northwind.net
            </address>
        </div>
    </div>
</section>

--------
Does not recognize class: ContractReportData

Your help is important. Thank you.

**Comment by patriciomh1965** [comment]
Also I want to add a screen where the PDF is generated:
![panta](https://user-images.githubusercontent.com/42218266/89252208-0f5aec00-d5e7-11ea-9e6f-4709cc620fe9.png)


----

The XYZgrid grid: 

.....
....
  protected getColumns() {
            var columns = super.getColumns();

            columns.splice(1, 0, {
                field: 'Print Invoice',
                name: '',
                format: ctx => '<a class="inline-action print-invoice" title="invoice">' +
                    '<i class="fa fa-file-pdf-o text-red"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });

            return columns;
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                if (target.hasClass('print-invoice')) {
                    SegurosMAPC.Common.ReportHelper.execute({
                        reportKey: 'BaseDatos.CuadraturaReporteCarteras',
                        params: {
                            NroContrato: item.NroContrato
                        }
                    });
                }
            }
        }
        //

**Comment by volkanceylan** [comment]
Check your view code, this is a Razor compilation error.

**Comment by patriciomh1965** [comment]
Solved !!! Thank you.
