### ISSUE TITLE
CardViewMixin when Grouping

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5141]
@volkanceylan: Please provide a sample for [Card View & React](https://serenity.is/docs/startsharp/features/card-view-react) when Grouping is used in Grid.ts.

`this.view.setGrouping([...]);`

**Comment by volkanceylan** [comment]
We don't have your name on our customer list.

**Comment by welcometoall** [comment]
@volkanceylan I am looking for demo in demo site to see if its possible and not for source code.
