### ISSUE TITLE
Change logo and rename buttom

### ISSUE THREAD

**Issue by spirit1989hcm** [volkanceylan/Serenity#5143]
Hi every one, i want to change logo serenity 
upper left corner,  left of the character "Start Sharp"and rename buttton (buttton new,save, delete in edit)
can you help me

**Comment by spirit1989hcm** [comment]
This is picture about question 
![2](https://user-images.githubusercontent.com/66616328/89374549-e6854480-d715-11ea-824b-e028d833b721.PNG)
![3](https://user-images.githubusercontent.com/66616328/89374552-e7b67180-d715-11ea-97d7-035ea42d2556.PNG)
![1](https://user-images.githubusercontent.com/66616328/89374553-e7b67180-d715-11ea-99f6-4a1c8aefc049.PNG)

**Comment by edwardch** [comment]
To change button text look here at JohnRanger's: [comment](https://github.com/volkanceylan/Serenity/issues/4954#issuecomment-612189013)

To update the logo please [search existing issues](https://github.com/volkanceylan/Serenity/issues?utf8=%E2%9C%93&q=is%3Aissue+logo+) like [#2234](https://github.com/volkanceylan/Serenity/issues/2234).

Good luck!

**Comment by spirit1989hcm** [comment]
tks for your help
