### ISSUE TITLE
Couldn't set up Serenity due to uncompatible .NET Core versions

### ISSUE THREAD

**Issue by kuttamuwa** [volkanceylan/Serenity#5144]
I'm following this document to install Serenity:
https://serenity.is/Docs/getting_started/instaling-serene-aspnet-core-version-with-serin

I've tried this on my Windows 10 machine and also Linux (Ubuntu 18.04). 
Document says we need to install .NET Core 2.0 SDK which is end of the life. We should use 2.1, i guess.
However, after installed serin with npm and run serin, I got this error:
![image](https://user-images.githubusercontent.com/26677935/89414896-cc5a5f00-d733-11ea-856e-1b3ee0149eac.png)

When I look at .csproj file, I see that project targeting 3.1. But document says 2? Anyway I changed this to 2.1
![image](https://user-images.githubusercontent.com/26677935/89415152-28bd7e80-d734-11ea-9f44-7da5bd7f1b74.png)

Then I run 'dotnet restore', another error comes up:
![image](https://user-images.githubusercontent.com/26677935/89415421-7c2fcc80-d734-11ea-930a-6da70721fbb7.png)
 I started thinking Serenity has terrible documentation and led us to wrong ways. 

Well .. I am really tired. When I test Serene at last year, just download it on nuget and that's it. 
By the way documents doesnt say but you have to install VS2019. Not VS2017 or 2015. The page I have followed has an SS may confuse people. In SS it says MVC but in the page it says .NET Core. 

Serene MVC seems obsolete and says we should prefer .NET Core.

**Comment by volkanceylan** [comment]
Serenity uses .NET Core 3.1, that's what you should install as shown in error message

**Comment by volkanceylan** [comment]
Documentation should be updated though

**Comment by volkanceylan** [comment]
If you are so tired and think Serenity leds you wrong ways, take a break, find a better tool etc.

**Comment by kuttamuwa** [comment]
Yes it is. That's why I changed my mind. I'll go forward with Django. Besides, I like to do everything manually.
I don't think that I'll ever never get into serenity and .net
