### ISSUE TITLE
[Tutorial] Create Bootstrap 3 Popover Button On Serenity Form

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#5145]
Hi team,

I wrote a bit code to integrate bootstrap 3 popover with serenity form, I think it might help someone

![](https://minhhungit.github.io/2020/08/06/009-implement-helping-button-using-popover-bootstrap-3-on-serenity-form/popover-button.gif)

![image](https://minhhungit.github.io/2020/08/06/009-implement-helping-button-using-popover-bootstrap-3-on-serenity-form/form-code.png)

--- 

In this tutorial, I also explain a way to pass value from c# FORM (server side) to typescript (client side) for form editor by using **EditorOption**

---

Link wiki: https://github.com/volkanceylan/Serenity/wiki/Create-Bootstrap-3-Popover-Button-On-Serenity-Form
Link code: https://gist.github.com/minhhungit/4915e4d6cf96c9868a7648f7d2f7cacd

**Comment by promiseap2014** [comment]
Looks great! 
It would be better if you use enum for `placement`, `trigger` and `position`.

**Comment by minhhungit** [comment]
Thank you @promiseap2014 that is good idea

**Comment by minhhungit** [comment]
I updated to use const string, something like this

```csharp
[HelpPopover(
    "Test 1", 
    trigger: HelpPopoverTypes.Trigger.Click, 
    placement: HelpPopoverTypes.Placement.Auto, 
    position: HelpPopoverTypes.Position.Caption)]
public List<TimelogTaskItemRow> TaskList { get; set; }
```

Due to limitation of enum on c# with null parameter also popover trigger can have multi values so string is still good choice I guess

```
How popover is triggered - click | hover | focus | manual. 
You may pass multiple triggers; separate them with a space. 
manual cannot be combined with any other trigger.
```
>https://bootstrapdocs.com/v3.3.6/docs/javascript/#popovers

**Comment by kilroyFR** [comment]
Where is : J.createGuid() source code ?

**Comment by minhhungit** [comment]
here it is @kilroyFR 

```js
namespace J {

    export function createGuid() {
        function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
                .toString(16)
                .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
    }
}
```

**Comment by minhhungit** [comment]
Updated new code and allow CSS specific popover by field name
```javascript
let helpPopover = new J.HelpPopover(this.form, this.getPropertyItems(), "i-am-a-class").init();
```

and less/css

```css
.popover.i-am-a-class.Date {
    width: 600px;
    max-width: unset;
    color:red;
}
```

**_init()_** method will generate all popovers we defined on form.cs, if we want to create popover for specific field then can do something like this:

```javascript
let helpPopover = new J.HelpPopover(this.form, this.getPropertyItems(), "i-am-a-class");
helpPopover.createHelpPopoverButton(TimelogRecordRow.Fields.UserId, { content: "My content", title: "My title" });
```

**Comment by kilroyFR** [comment]
i would personnaly add feature to enable loading Translated text/content (Q.text()) as it's no possible on attribute to set LocalText.Get()

**Comment by MafdyAzer** [comment]
Great, Thanks @minhhungit for sharing ❤️

**Comment by kilroyFR** [comment]
Just one feature that could be really useful is to enable loading globalized resource from form declaration (the way it's done with [DisplayName("MyRessource")] in xxxRow.cs.

**Comment by minhhungit** [comment]
@kilroyFR I guess you can use Q.text at client side

https://gist.github.com/minhhungit/4915e4d6cf96c9868a7648f7d2f7cacd#file-j-helppopover-ts-L106

**Comment by edwardch** [comment]
Hi @minhhungit !

I was looking to implement (something like) this and noticed that your GitHub page is down so I couldn't see any of the images (also in the Serenity wiki). 

Have you moved it or would you be able to upload those screenshots to the wiki. It may be useful for someone to see what they're doing before implementing it.

Cheers,
Edward

**Comment by minhhungit** [comment]
@edwardch try again please, I can access the page https://gist.github.com/minhhungit/4915e4d6cf96c9868a7648f7d2f7cacd

**Comment by edwardch** [comment]
Thanks @minhhungit, 

I can access that page, but the image on the wiki is blank, and your GitHub page is also down 

This gives me a 404 site not found - https://minhhungit.github.io/2020/08/06/009-implement-helping-button-using-popover-bootstrap-3-on-serenity-form/

Then the wiki doesn't have the preview either:
![Image](https://github.com/user-attachments/assets/d89126b3-10ce-476b-bd2f-5aacef0372ca)

Cheers,
Edward

**Comment by minhhungit** [comment]
this is the image 
![Image](https://github.com/user-attachments/assets/9bfb7207-3fe7-4c32-9150-11d14fdf5cae)

**Comment by edwardch** [comment]
Ah it's an image of the code!

Sorry, I thought it was the image of what the popover looked like

**Comment by minhhungit** [comment]
> Sorry, I thought it was the image of what the popover looked like

![Image](https://github.com/user-attachments/assets/852b9531-17b2-43df-9063-b0e40b5d262d)
https://github.com/user-attachments/assets/850c7d64-31df-4050-a245-45c7fd334304
