### ISSUE TITLE
Datetime field loses Time portion when saving

### ISSUE THREAD

**Issue by eclipzd** [volkanceylan/Serenity#5147]
I have a datetime field which has a date and time portion in it.  I want to display both date and time in the Dialog, so I set the ScriptCulture in _LayoutHead.cshtml to include (new ScriptCulture { DateFormat = "dd/MM/yyyy HH:mm:ss" }) - and datetime displays correctly.  Then when I press the 'Update' record button, the Time portion is updated with 00:00:00.  So, somewhere between loading the value into memory and then pressing 'Save', the Datetime flag od 'DateOnly' is set to 'True' - which removes the Time portion - and then since the time is set to 00:00:00, the record can no longer update.

Is there a way to enable the updating and 'saving' in a Dialog of a datime field to keep both the date and time?  Thanks

**Comment by volkanceylan** [comment]
First, remove DateFormat override in ScriptCulture, it has nothing to do with date time editing. Use DateTimeEditor in your row / form.

**Comment by eclipzd** [comment]
Thanks so much for you response Volkan.  It is really appreciated.  I replied directly so I could include screen shots.

I removed the DateFormat override, but now I cannot see the time in the edit box.  When I add the [DateTimeEditor] in my ‘…Form.cs’ file to the Updated On field (but not to the Created On field), now the UI looks like this;
[cid:image002.png@01D66D17.316B2870]


When I do use the _LayoutHead.cshtml file with;  ScriptCulture{ DateFormat = "dd/MM/yyyy hh:mm:ss tt" }
It shows the date time perfectly.
[cid:image001.png@01D66D18.05943510]

But when I press ‘Update’ – the following error appears – yet it is a read-only field and has not changed.
[cid:image003.png@01D66D18.05943510]
[cid:image004.png@01D66D18.05943510]

Is there any way I can over-write the validation – since it is not working correctly (when I ‘watch’ the field – it has the DateOnly flag set before it saves.)

Any ideas?

Thanks

**Comment by volkanceylan** [comment]
If those fields are server side set, then use Insertable(false), Updatable(false)

**Comment by eclipzd** [comment]
Thanks for your reply.  The CreatedOn field is set to the current datetime when a new record is inserted from the client and saved to the DB, and the UpdatedOn field is updated whenever there is a change made to the record - so I cannot use those 2 properties.  I just need to be able to display datetime in the edit box, and not have it remove the time portion on a save (update).  Is there any way to do this through Serenity?  Thx

**Comment by volkanceylan** [comment]
Those fields must be set server side. They always have those attributes.
