### ISSUE TITLE
how to refresh grid in another tab

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5150]
Hi

I have a form with 3 tabs. I want to refresh the grid in third tab after a record is saved in second tab.

Thank you for the help

**Comment by djhonb** [comment]
Its a PropertGridtab or Custom tab by customizing the template? 

**_Case1 i,e (PropertGrid Tab)_** 
As far as its in same form and if the grid belongs to list of items the editor will be EntityGrid/Datagrid/MemoryGrid, in this case, you can call 
`this.form.fieldname.refresh();` after whatever your event is (on change of another form field in your case)

_**Case2 (i,e Template based tab)**_
In this case first you need to have reference to your form where grid is located
this.form_in_thirdtab= new Default.FormName(this.idPrefix + "FormName");
and then you can call
`this.form.fieldname.refresh();`

or you can directly get the grid reference by id inside a dialog and call the refresh method.

**Comment by ms4hafiz** [comment]
@djhonb 

thank you for the response but I am going to refresh Grid in another Tab.

**Comment by welcometoall** [comment]
you can do it in [Tab click](https://github.com/volkanceylan/Serenity/issues/5073#issuecomment-648743932) event

**Comment by JohnRanger** [comment]
@ms4hafiz ,

as @welcometoall already stated - do the refresh (mentioned in code by @djhonb) when you click on 3rd tab - as you only need the visible refresh when focus is going back to 3rd tab.

With kind regards,

John

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
