### ISSUE TITLE
Creating a dynamic Carousel

### ISSUE THREAD

**Issue by dms2701** [volkanceylan/Serenity#5154]
I've been looking at the Admin LTE samples, specifically the carousel; [](https://serenity.is/demo/AdminLTE/UIElements/General)

However, I cannot get it to work. It creates the carousel with the first active slide, but it never changes, and the right and left click buttons do not work. I have included my code below. I can confirm the model variable contains multiple values that I am looping through, so the data source is not the issue.

(Count is an int var = 0)
```
<div class="row">
    <div class="col-md-6">
        <div class="box box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Carousel</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        @for (var i = 0; i < Model.MyData.Rows.Count; i++)
                        {
                            if (i == 0)
                            {
                                <li data-target="#carousel-example-generic" data-slide-to=@i class="active"></li>
                            }
                            else
                            {
                                <li data-target="#carousel-example-generic" data-slide-to=@i class=""></li>
                            }
                        }

                    </ol>
                    <div class="carousel-inner">
                        @foreach (DataRow row in Model.MyData.Rows)
                        {
                            if (count> 0)
                            {
                                <div class="item">
                                    Source: @row["Something"]
                                    <div class="carousel-caption">
                                        Slide @count
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="item-active">
                                    Source: @row["Something"]
                                    <div class="carousel-caption">
                                        Slide @count
                                    </div>
                                </div>
                            }
                            count++;
                        }
                    </div>
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="fa fa-angle-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="fa fa-angle-right"></span>
                    </a>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->
```

**Comment by dms2701** [comment]
Anyone?

**Comment by dms2701** [comment]
@volkanceylan Hi Volkan, appreciate you are busy, wondering if you could shed some light?

**Comment by arunkumar12712** [comment]
<div class="col-lg-4 col-xs-6">
        <div class="panel panel-primary">
            
            <div class="panel-heading">Birth Days</div>
            <div class="panel-body">
                <div class="carousel slide" id="myCarousel">
                    
                    <div class="carousel-inner" style="height:250px !important;width:100%">
                        @foreach (var item in Model.DashEmployeeBirths.Where(t => t.EventType == 1).ToList())
                        {
                            <div class="item @(isActive == true ? "active": "")" data-slide-number="0">
                                @if (!item.ImagePath.IsEmptyOrNull())
                                {
                                    <img src="@(VirtualPathUtility.ToAbsolute("~/upload/" + item.ImagePath))" class="img-responsive">
                                }
                                else
                                {
                                    <img src="http://placehold.it/300/f44336/000000" class="img-responsive">
                                }
                                <div class="carousel-caption">
                                    <p><b>@item.EmployeeName - @item.EmployeeCode</b></p>
                                    <p> @item.Designation</p>
                                </div>
                            </div>
                            isActive = false;
                        }
                    </div>

                    
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>

            <div class="col-sm-4" id="carousel-text"></div>
        </div>
    </div>



<style>
    img {
        border-radius: 50% 50% 50% 50%;
        width: 150px;
        height: 100px;
    }

    .carousel-inner > .item > img {
        margin: 0 auto;
    }

    .carousel-caption {
        color: black;
        position: relative;
        text-align: initial;
    }
</style>

**Comment by arunkumar12712** [comment]
try this

https://codepen.io/kchez/pen/zrRMZw

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
