### ISSUE TITLE
Uncaught TypeError: Serenity.DraggableGroupingMixin is not a constructor

### ISSUE THREAD

**Issue by sottnik** [volkanceylan/Serenity#5155]
Running Serenity v3.13.5 with pro scripts v3.9.10.
```
Uncaught TypeError: Serenity.DraggableGroupingMixin is not a constructor
```

```
protected createToolbarExtensions() {
            super.createToolbarExtensions();


            this.slickGrid.registerPlugin(new Slick.Data.GroupItemMetadataProvider());

            var groupingMixin = new Serenity.DraggableGroupingMixin({
                grid: this
            });
```

Intellisense sees the DraggableGroupingMixin as accessible in the include path. Compilation of ts is without errors. The above exception comes during runtime. I compared all relevant files between Startsharp and our project. They are identical. The Startsharp project is running without any problems. 

Any ideas?

**Comment by volkanceylan** [comment]
dotnet sergen restore

**Comment by volkanceylan** [comment]
And include Pro script files in your ScriptBundles.json etc.

**Comment by sottnik** [comment]
> And include Pro script files in your ScriptBundles.json etc.

That was it! Thank you!
