### ISSUE TITLE
DraggableGroupingMixin Sort problem

### ISSUE THREAD

**Issue by Nikola7i** [volkanceylan/Serenity#5157]
Hi,

When I use Draggable Grouping Mixin, on third column in sort is number, and when I try to sort desc, nothing happens.
First two columns are string (and default), third is number.

groupingMixin.plugin.setDroppedGroups(["NazivPartnera", "NazivPj"]);
          

![Serenity](https://user-images.githubusercontent.com/16926063/90127208-1a3f1a80-dd65-11ea-8f60-7fd45e1ac667.png)

Please help,

Regards,
Nikola (Salvus)

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
