### ISSUE TITLE
Totals in fotter do not work in groups

### ISSUE THREAD

**Issue by choss21** [volkanceylan/Serenity#5158]
hello everyone, I'm having this problem
![Captura1](https://user-images.githubusercontent.com/13734677/90260242-d7d31780-de10-11ea-909c-1c940dc04af1.PNG)

The solution I found is as follows
- Remove line 13356 from Serenity.CoreLib.js file
![image](https://user-images.githubusercontent.com/13734677/90260768-97c06480-de11-11ea-9c91-67e332d5d271.png)

![BgLcpkUrZF](https://user-images.githubusercontent.com/13734677/90261556-c0952980-de12-11ea-8214-4a35e223b494.gif)

I hope you can give me feedback

Best regards

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
