### ISSUE TITLE
LDAP - Duplicated users info

### ISSUE THREAD

**Issue by qprotex** [volkanceylan/Serenity#5159]
Hello,

In one of my Serenity projects where I have LDAP enabled, some users reported that they were having issues when login in.

This is the screenshot I received:
![image](https://user-images.githubusercontent.com/13024779/90275450-55f2e680-de30-11ea-815a-3f4501e0f6b1.png)

When I checked the database, I found duplicated records for those 3 users that reported the issues:
![image](https://user-images.githubusercontent.com/13024779/90275731-c1d54f00-de30-11ea-9765-71bc1d9035e0.png)

I have blurred the display name and email columns, but as you can see in the username column, they are the same users that for some reason were created multiple times. Any hint on why this happened?

**Comment by volkanceylan** [comment]
Don't know maybe there was some space at the end?

**Comment by qprotex** [comment]
There is no space in the username nor the displayname nor the email. Could it be that the organization is using 2 ADs that are sync from time to time? I am not familiar on how AD works internally but I know they use AD replication. In any case, do you have any suggestion on where in the code I can add a validation to avoid this to happen again? Thanks

**Comment by volkanceylan** [comment]
You may put a unique constraint in DB to username col

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
