### ISSUE TITLE
change default caption of Add button and Edit Dialog

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#516]
How can i change default caption of Add button and Add / Edit Dialog. It is showing Table Name as default.

**Comment by volkanceylan** [comment]
See guide

**Comment by mrajalko** [comment]
Now i am able to change add button caption 

protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();
            buttons[0].Title = "Add Sale Advice";
            return buttons;
        }

but i am still searching for ways to change caption of edit dialog.

**Comment by wldkrd1** [comment]
The Add/Edit dialog caption (aka title) takes the form of "Add <ItemDisplayName> (<ItemNameField>)"
If you want to keep that format but change the content of ItemNameField, then point the NameField of your whateverRow to a field containing whatever it is you want to display.

**Comment by volkanceylan** [comment]
You may also set Title property directly in UpdateTitle method, based on IsNew state

**Comment by volkanceylan** [comment]
Btw, i recommend changing DisplayName and InstanceName properties on your server side Row directly. If your entities should be called Sale Advice, set them to Sale Advices and Sale Advice. 

Don't do this on buttons. Text on rows changes buttons too.

**Comment by mrajalko** [comment]
Sorry i was not changing Instance Name Property.
It worked as soon as I changed Instance Name Property.

thanks for your guidance.
