### ISSUE TITLE
Datetime editor problems

### ISSUE THREAD

**Issue by danlem** [volkanceylan/Serenity#5160]
Brand new Serene project with all options (AdminLte, Northwind and Basic Samples)

Latest stable version (3.14)

Goto the  "Default Values In New Dialog" page
Click the "+ New Order" button

Problem #1 - editor icon is missing
Problem #2 - Required Date is set to yesterday but the code sets it to today

Problem #3 - When using a datetime editor, setting to readonly does not affect the time selector
![serene_3_14_date](https://user-images.githubusercontent.com/16088184/90304532-efe57e00-de86-11ea-99e6-4cb3a3c7a9dc.png)

**Comment by minhhungit** [comment]
- make sure that you upgraded all serenity packages
- run `dotnet restore` and `dotnet sergen restore`
- clear cache / force refresh

**Comment by danlem** [comment]
Thanks but nothing changed after following these steps.

I had hopes because It restored the glyphicons svg files and the datepicker button is using an svg icon.

`data:image/svg+xml,%3Csvg%20version=%221.1%22%20xmlns=%22http://www.w3.org/2000/svg%22%20xmlns:xlink=%22http://www.w3.org/1999/xlink%22%20viewBox=%220%200%2017%2017%22%3E%3Cg%3E%3C/g%3E%3Cpath%20d=%22M14%202v-1h-3v1h-5v-1h-3v1h-3v15h17v-15h-3zM12%202h1v2h-1v-2zM4%202h1v2h-1v-2zM16%2016h-15v-8.921h15v8.921zM1%206.079v-3.079h2v2h3v-2h5v2h3v-2h2v3.079h-15z%22%20fill=%22#000000%22%3E%3C/path%3E%3C/svg%3E`

Here are my Serene Nuget versions.
Serenity.FluentMigrator.Runner V1.9.604
Serenity.Scripts V3.14.0
Serenity.Web.Assets V3.9.2
Serenity.Web V3.14.0


And here is the output of the commands
`dotnet restore`
  Determining projects to restore...
  Restored E:\App\csharp\spa\SpaAppels.Web\SpaAppels.Web.csproj (in 696 ms).

`dotnet sergen restore`
Processing: Mapster
Processing: StackExchange.Exceptional.AspNetCore
Processing: Serenity.FluentMigrator.Runner
Processing: Serenity.Scripts
Processing: Serenity.Web
Processing: Serenity.Web.Assets
Restoring: wwwroot\fonts\glyphicons-halflings-regular.svg
Processing: StackExchange.Exceptional.Shared
Processing: Serenity.Core
Processing: Serenity.Data
Processing: Serenity.Data.Entity
Processing: Serenity.Services
Processing: jQuery
Processing: jQuery.UI.Combined
Processing: jQuery.Validation
Processing: bootstrap
Restoring: wwwroot\fonts\glyphicons-halflings-regular.svg
Processing: toastr
Processing: Select2.js

**Comment by minhhungit** [comment]
run `dotnet sergen restore` some times and make sure that Serenity.CoreLib.js has updated with new code

![image](https://user-images.githubusercontent.com/2279508/90315299-8b88f400-df44-11ea-8cd8-8c246da7301b.png)

**Comment by danlem** [comment]
Even after the command I am still left with the old version (left on image)

**Comment by minhhungit** [comment]
>Even after the command I am still left with the old version

Yep, I don't know why, I also meet the issue yesterday but at that time I think I was crazy, I restored again and it worked

**Comment by danlem** [comment]
Ran it multiple times but no change.

Decided to modify the Serenity.CoreLib.js file myself but it gave a strange result.

Ran the restore command again and this time lots of files were updates.

Fixed the icon problem but the incorrect date problem is still there.
And so is the reaonly datetimepicker not setting the time selector to readonly.

**Comment by minhhungit** [comment]
yes, I also tried to manual modify file Serenity.CoreLib.js before I re-run sergen restore ===> this step might be a clue

**Comment by danlem** [comment]
Since the icon problem has been fixed, I created an issues for most problematic issue :

incorrect date problem [issue #5167](https://github.com/volkanceylan/Serenity/issues/5167)
