### ISSUE TITLE
how to prevent a user not to enter a special character in a textbox with typescript?

### ISSUE THREAD

**Issue by amirkian** [volkanceylan/Serenity#5161]
I totally a beginner in typescript and I use it in a serenity framework and I wonder how to prevent a user not to enter a special character in a textbox with typescript.
as a result, I tried this:

`
            this.form.FirstName.element.on('keyup', event => {
                var initval = this.form.FirstName.element.val;
                var keyCode = (event.keyCode ? event.keyCode : event.which);

                if (keyCode == 32 || (48 <= keyCode && keyCode <= 57) || (65 <= keyCode && keyCode <= 90) || (97 <= keyCode && keyCode <= 122)) {
                    
                    console.log("sucssed!");
                    this.form.FirstName.element.val = initval;
                }   
                 
                    else {
                        console.log("faild!");
                    }
              });
`

but I don't know its alright or what fault it has.

**Comment by welcometoall** [comment]
Use regex.
`initval.match('...')`
