### ISSUE TITLE
Problem in Multiple Rows Selection in Grid

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#5163]
Hello All,
I have a datagrid and I want to activate multiple Row Selection on it. 
I followed https://serenity.is/demo/BasicSamples/CancellableBulkAction this link but cant select rows.
Any Idea?

**Comment by JohnRanger** [comment]
Hi @MaziarSangi ,

can you explain a bit more clearly, what exactly is your problem?

With kind regards,

John

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
