### ISSUE TITLE
MaskedEditor attribute for two or three digits.

### ISSUE THREAD

**Issue by amirkian** [volkanceylan/Serenity#5164]
I used this code 

`
     [MaskedEditor(Mask = "999")]
        public Int32? HomeTotalArea { get; set; }
`

to mask an input that  a user can't enter more than 3 numbers.

when on a form a user just enters 2 digits and set focus to another input , the value of the first input will be lost but when they enter 3 digits and change focus to another element , it is alright.

**Comment by edwardch** [comment]
Can you try 
```cs
[IntegerEditor(MaxValue = 999)]
public Int32? HomeTotalArea
{
	get { return Fields.HomeTotalArea[this]; }
	set { Fields.HomeTotalArea[this] = value; }
}
```

**Comment by amirkian** [comment]
thanks
done.
