### ISSUE TITLE
Run Sql command

### ISSUE THREAD

**Issue by spirit1989hcm** [volkanceylan/Serenity#5165]
Hi every body, i have a code in file endpoint.cs, run store procedure in SQL server,  code run ok.
My code: 
        `public ListResponse<MyRow> RunSQL (IDbConnection connection, ListRequest request)
        {

            string sql = "EXEC SP @Name='" + Authorization.UserDefinition.Username + "'";
                        SqlHelper.ExecuteNonQuery(connection, sql);
            return new MyRepository().List(connection, request);
        }`

**But I have a problem when run, my web will IDLE waiting for when query SQL finish. 
I  only want run query and don't want my web waiting query finish. (I need not sql server respone when query finish)**

**Comment by wezmag** [comment]
You can use [Hangfire](https://www.hangfire.io/) or [Quartz.Net](https://www.quartz-scheduler.net/) for this kind of implementation.
There is a wiki article on how to [Using Hangfire Background Jobs with Serenity](https://github.com/volkanceylan/Serenity/wiki/Background-Tasks:-Using-Hangfire-Background-Jobs)

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
