### ISSUE TITLE
Serenity demo dosen't load on .NetCore 3.0

### ISSUE THREAD

**Issue by amirkian** [volkanceylan/Serenity#5166]
I need a virsion that I can run on.NetCore 3.0 but when follow this link

[https://marketplace.visualstudio.com/items?itemName=VolkanCeylan.SereneSerenityApplicationTemplate]
`
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.1.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.1.0 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)	Serene3.Web	C:\Users\javaheri\source\repos\Serene3\Serene3\Serene3.Web\Serene3.Web.csproj	
`
how can I get the older version that runs in .NetCore 3.0?

**Comment by JohnRanger** [comment]
Hi @amirkian ,

If you know the Serenity version which was built to run on .NET core 3.0 (unfortunately I don't know this - I am not sure if there ever was one - I think there was only one for .NET core 2.2 and then the .net Core 3.1-based version), then you can go into github, click on the code button and then click on commit:

![image](https://user-images.githubusercontent.com/2699447/91092268-098d7f00-e658-11ea-9659-d31e7824058d.png)

There you can scroll down (and you will have to page back until you have the version which is for .net core 3.0 - if there is any at all - see my comment above).

Then you click on the desired version:
![image](https://user-images.githubusercontent.com/2699447/91092567-7ef94f80-e658-11ea-9734-8f38ec07b0f2.png)


Then you click on Browse files:
![image](https://user-images.githubusercontent.com/2699447/91092639-9e907800-e658-11ea-839c-9a1154eb207a.png)

Then you click on Code and then on Download ZIP:
![image](https://user-images.githubusercontent.com/2699447/91092792-d5668e00-e658-11ea-9d6c-76d22ede05ec.png)


Hope this helps.

With kind regards,

John

**Comment by amirkian** [comment]
I did so and I installed this version  and I set the senerity.core to my start up project in the soulotion but I get this error

> "Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
> Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	Serenity.Core (netstandard2.0)	C:\Users\javaheri\source\repos\oldersenerity\Serenity.Core\CSC	1		Active
> "

**Comment by welcometoall** [comment]
Compare your csproj with [https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Serene.Core.csproj](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Serene.Core.csproj)

**Comment by amirkian** [comment]
by updating visual studio version its done .
