### ISSUE TITLE
StaticTextBlock

### ISSUE THREAD

**Issue by belalAhmed** [volkanceylan/Serenity#5169]
Hi 
1- how i can set the value in StaticTextBlock from the current row
2- i want to set the one parameter in request with fixed value from Dialog.ts and it's not in the form 
example
  this.form.xyz=123
i want or replace it to
this.request.xyz=123
so in my Repository i can make some conditions

**Comment by luongnv6** [comment]
Add a new field with the [NotMapped] property in the row:
```C#
        [DisplayName("xyz"), NotMapped]
        public String xyz
        {
            get { return Fields.xyz[this]; }
            set { Fields.xyz[this] = value; }
        }
```
Then on dialog, you can assign a value to it
  ```C#
protected getSaveEntity () {
             let entity = super.getSaveEntity ();
             entity.xyz = '123';
             return entity;
         }
```

Next in Repository:
```C#
 private class MySaveHandler : SaveRequestHandler<MyRow>
        {
            protected override void BeforeSave()
            {
                base.BeforeSave();
                if (Row.xzy == '123')
                {
                        //todo
                }
                else
                {
                    //todo else
                }
            }
        }
```

hope help you

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
