### ISSUE TITLE
 Problem with the Title in Permissions for users.

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5171]
Hello community, I have the following problem:
In the Administration menu, the option "Users", when editing the permissions I display a menu for the permissions. There is a title that I need to change and I have n
![image1](https://user-images.githubusercontent.com/42218266/90963882-aea62d00-e489-11ea-977b-bd90bd45b245.png)
ot been able to. I present the following images:

The class for the permissions is as follows:

![image2](https://user-images.githubusercontent.com/42218266/90963915-fd53c700-e489-11ea-95a9-ec90946228d7.png)

If you know how to change the name from "Database" to "Mapc Services", it would be of great help.
Atte.

**Comment by welcometoall** [comment]
This can be changed in 
> wwwroot/Scripts/site/texts/site.texts.**{Language}**.json

**Comment by patriciomh1965** [comment]
Thank you very much friend !!! I turned.

**Comment by patriciomh1965** [comment]
![ima1](https://user-images.githubusercontent.com/42218266/91321248-6ab66f00-e78c-11ea-9297-ce00e3e120e3.png)

**Comment by patriciomh1965** [comment]
This can help other friends.
