### ISSUE TITLE
change event for a field in *.ts file

### ISSUE THREAD

**Issue by amirkian** [volkanceylan/Serenity#5172]
I have a field with this name 'ApplicantHealthStatusHistories_CommisionId'
in a ts file.
I want to check if this value changed, something happens but I don't know how to check this change.

**Comment by edwardch** [comment]
Try something like this inside your `XYZDialog.ts` file:

```ts
protected form: XYZForm;

constructor() {
    super();

    this.form = new XYZForm(this.idPrefix);

    this.form.ApplicantHealthStatusHistories_CommisionId.change(e => {
        console.log("It changed");
    });
}
```

**Comment by amirkian** [comment]
the ApplicantHealthStatusHistories_CommisionId is a foreign key as sub table in this form.
it shows a related table on this form ,so it doesn't have change event but I want to if some record added to this table 
a message will show like change event.
