### ISSUE TITLE
Serenity Startsharp Sern

### ISSUE THREAD

**Issue by nighilgeorge84** [volkanceylan/Serenity#5173]
![image](https://user-images.githubusercontent.com/70127997/91008026-0ca65200-e5fb-11ea-8143-7c1765963199.png)

Using serenity startsharp code generator exception occurring  that **"System.Threading.Tasks.Extensions"** version issue.
I upload exception as preview image .Please help to solve this issue .
i am using **VS2019**

**Comment by VictorTomaili** [comment]
Closed due inactivity
If you still have issue check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines)
