### ISSUE TITLE
StartSharp

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#5175]
Hi Volkan and Serenity Team,
Does Startsharp have a way of managing subscriptions of one's customers? If I have a multi-tenancy application and I want customers to subscribe, does startsharp already have a way of managing their subscriptions, the period it expires, invoices to be sent to them per subscription or renewal, etc?

And if I want to be able to set up customer logos and urls, can that easily be done?

Regards

**Comment by volkanceylan** [comment]
We have a serenity.is application which does what you ask for, but it is not part of StartSharp and is a private application. We'll not be open sourcing it.

**Comment by gfo2007** [comment]
@volkanceylan thanks very much for your response. It would be nice though to have such features for extra dollars in Startsharp. This will help customers of Startsharp to manage everything from within the serenity ecosystem.

I am planning to sign up for Startsharp for a project early next year.
