### ISSUE TITLE
 It does not show the detail.

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5179]
Hello community, I have the following problem.
It does not show the detail.
I am using XYZGrid.cs to open a page, as follows:

namespace SegurosMAPC.BaseDatos {

    @Serenity.Decorators.registerClass()
    export class MonitorArchivosGrid extends Serenity.EntityGrid<MonitorArchivosRow, any> {
        protected getColumnsKey() { return 'BaseDatos.MonitorArchivos'; }
        protected getDialogType() { return MonitorArchivosDialog; }
        protected getIdProperty() { return MonitorArchivosRow.idProperty; }
        protected getLocalTextPrefix() { return MonitorArchivosRow.localTextPrefix; }
        protected getService() { return MonitorArchivosService.baseUrl; }

        constructor(container: JQuery) {
            super(container);
        }

        ///

        getButtons() {
            var buttons = super.getButtons();

            buttons.push(SegurosMAPC.Common.ExcelExportHelper.createToolButton({
                title: "Exportar",
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: 'BaseDatos/MonitorArchivos/ListExcel',
                separator: true
            }));

            buttons.push(SegurosMAPC.Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                title: "Exportar",
                hint: "H I N T",
                separator: true,
                reportTitle: "Carga de Archivos",
                titleTop: 2,
                titleFontSize: 12,
                fileName: "MonitorArchivos",
                pageNumbers: true,
                columnTitles: {
                    'OriginalColumn': 'OCol.',
                },
                tableOptions: {
                    columnStyles: {
                        OriginalColumn: {
                            columnWidth: 25,
                            halign: 'right'
                        }
                    }
                }
            }));

            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1); // QUITAR BOTON NUEVO

            return buttons;
        }
        //
        protected getQuickSearchFields():
            Serenity.QuickSearchField[] {
            return [               
                { name: "FechaProceso", title: "Periodo" },
                { name: "InicioProceso", title: "Fecha Inicio Carga" },
                { name: "NombreArchivo", title: "Nombre Archivo" },
            ];
        }
        ///

        protected getColumns() {
            var columns = super.getColumns();

            columns.splice(0, 0, {
                field: 'RevisionLOG',
                name: '',
                format: ctx => '<a class="inline-action revision-log" title="Revisión LOG">' +
                    '<i class="fa fa-edit text-red"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });        

            columns.splice(2, 0, {
                field: 'Download File',
                name: '',
                format: ctx => '<a class="inline-action download-file" title="Descargar Archivo">' +
                    '<i class="fa fa-file-text-o text-blue"></i></a>',
                width: 24,
                minWidth: 24,
                maxWidth: 24
            });     
            return columns;
        }

        protected onClick(e: JQueryEventObject, row: number, cell: number) {
            super.onClick(e, row, cell);

            if (e.isDefaultPrevented())
                return;

            var item = this.itemAt(row);
            var target = $(e.target);

            // if user clicks "i" element, e.g. icon
            if (target.parent().hasClass('inline-action'))
                target = target.parent();

            if (target.hasClass('revision-log')) {
                var dlg1 = new MonitorLogeoDialog();
                this.initDialog(dlg1);

               dlg1.loadEntityAndOpenDialog(<MonitorLogeoRow>
                    {
                        NumeroProceso: item.NumeroProceso,
                        FechaProceso: item.FechaProceso,
                        NombreArchivo: item.NombreArchivo,                       
                        DetailList20: [{ NumeroProceso: item.NumeroProceso }]
                });
            }

            if (target.hasClass('inline-action')) {
                e.preventDefault();

                if (target.hasClass('download-file')) {
                    let ServiceEndpoint = this.getService() + "/ExportFile";
                    Q.postToService({ service: ServiceEndpoint, request: { EntityId: item.NumeroProceso }, target: '_blank' });
                }

            }
        }
    //
    }
}

![ima1](https://user-images.githubusercontent.com/42218266/91342946-c93e1600-e7a9-11ea-9d80-110dde6d6125.png)
![ima2](https://user-images.githubusercontent.com/42218266/91342951-cc390680-e7a9-11ea-8285-59146b4415f6.png)

Then I have XYZRow:

namespace SegurosMAPC.BaseDatos.Entities
{
    using SegurosMAPC.Modules.BaseDatos;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("BaseDatos"), Module("BaseDatos"), TableName("[dbo].[vw_monitor_archivos]")]
    [DisplayName("Monitor - Cargas de Archivos"), InstanceName("CargaArchivos")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [LookupScript] // VINCULACION
    public sealed class MonitorLogeoRow : Row, IIdRow, INameRow
    {
        [DisplayName("Numero Proceso"), Column("proc_numero")]
        public System.Int32? NumeroProceso 
        {
            get { return Fields.NumeroProceso[this]; }
            set { Fields.NumeroProceso[this] = value; }
        }

        [DisplayName("Periodo"), Column("proc_fecha_proceso")]
        public String FechaProceso
        {
            get { return Fields.FechaProceso[this]; }
            set { Fields.FechaProceso[this] = value; }
        }
        //
        [DisplayName("Nombre Archivo"), Column("proc_nombre_archivo"), Size(255)]
        public String NombreArchivo
        {
            get { return Fields.NombreArchivo[this]; }
            set { Fields.NombreArchivo[this] = value; }
        }
        //

        //  VINCULACION LOG
        [DisplayName(""), MasterDetailRelation(foreignKey: "proc_numero", MasterKeyField = "proc_numero"), NotMapped]
        [MinSelectLevel(SelectLevel.List)]
        public List<LogDetalleArchivoRow> DetailList20
        {
            get { return Fields.DetailList20[this]; }
            set { Fields.DetailList20[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.NumeroProceso; } 
        }

        StringField INameRow.NameField
        {
            get { return Fields.NombreArchivo; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public MonitorLogeoRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public StringField FechaProceso;
            public Int32Field NumeroProceso; 
            public StringField NombreArchivo;
            //
            public RowListField<LogDetalleArchivoRow> DetailList20;  
        }
    }
}

The detail class is:

namespace SegurosMAPC.BaseDatos.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("BaseDatos"), Module("BaseDatos"), TableName("[dbo].[vw_log_archivo]")]
    [DisplayName("LOG"), InstanceName("LOG")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    public sealed class LogDetalleArchivoRow : Row, IIdRow, INameRow
    {
        [DisplayName("Proc Id"), Column("proc_id"), PrimaryKey]
        public Int32? ProcId 
        {
            get { return Fields.ProcId[this]; } 
            set { Fields.ProcId[this] = value; }
        }

        [DisplayName("Key Proline Uni"), Column("key_proline_uni")]
        public Int32? KeyProlineUni
        {
            get { return Fields.KeyProlineUni[this]; } 
            set { Fields.KeyProlineUni[this] = value; } 
        }      

        [DisplayName("Key Proline"), Column("key_proline")]
        public Int32? KeyProline
        {
            get { return Fields.KeyProline[this]; }
            set { Fields.KeyProline[this] = value; }
        }     

        [DisplayName("Numero Proceso"), Column("proc_numero"), NotNull]
        public Int32? NumeroProceso
        {
            get { return Fields.NumeroProceso[this]; }
            set { Fields.NumeroProceso[this] = value; }
        }

        [DisplayName("Numero Linea"), Column("log_num_linea"), NotNull]
        public Int32? NumeroLinea
        {
            get { return Fields.NumeroLinea[this]; }
            set { Fields.NumeroLinea[this] = value; }
        }

        [DisplayName("Etapa"), Column("log_etapa"), NotNull]
        public Int32? Etapa
        {
            get { return Fields.Etapa[this]; }
            set { Fields.Etapa[this] = value; }
        }
        [DisplayName("Etapa"), Column("eta_descripcion"), NotNull]
        public String EtapaNombre
        {
            get { return Fields.EtapaNombre[this]; }
            set { Fields.EtapaNombre[this] = value; }
        }
        [DisplayName("Fecha"), Column("log_fec_crea")]
        public String FechaLog 
        {
            get { return Fields.FechaLog[this]; }
            set { Fields.FechaLog[this] = value; }
        }

        [DisplayName("Categoria"), Column("det_cod_categoria"), ForeignKey(typeof(TaProcLogCategoriaRow)), LeftJoin("c")]
        [LookupEditor(typeof(TaProcLogCategoriaRow))]
        public Int32? Categoria
        {
            get { return Fields.Categoria[this]; }
            set { Fields.Categoria[this] = value; }
        }
        [Origin("c"), MinSelectLevel(SelectLevel.List)]
        public String DatObservacion
        {
            get { return Fields.DatObservacion[this]; }
            set { Fields.DatObservacion[this] = value; }
        }

        [DisplayName("Nro. Observacion"), Column("det_observacion"), NotNull]
        public Int32? DetObservacion
        {
            get { return Fields.DetObservacion[this]; }
            set { Fields.DetObservacion[this] = value; }
        }

        [DisplayName("Observacion"), Column("det_dat_observacion"), Size(2147483647), QuickSearch]
        public String DetDatObservacion
        {
            get { return Fields.DetDatObservacion[this]; }
            set { Fields.DetDatObservacion[this] = value; }
        }

        [DateTimeFormatter(DisplayFormat = "yyyy-MM-dd HH:mm"), DefaultValue("now"), DateTimeEditor()]
        [DisplayName("Fecha Registro"), Column("det_fecha_registro")]
        public DateTime? FechaRegistro
        {
            get { return Fields.FechaRegistro[this]; }
            set { Fields.FechaRegistro[this] = value; }
        }
        [DisplayName("Usuario"), Column("DisplayName")]
        public String Usuario
        {
            get { return Fields.Usuario[this]; }
            set { Fields.Usuario[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.ProcId; } 
        }

        StringField INameRow.NameField
        {
            get { return Fields.DetDatObservacion; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public LogDetalleArchivoRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field ProcId; 
            public Int32Field KeyProlineUni;
            public Int32Field KeyProline; 
            public Int32Field NumeroProceso;
            public Int32Field NumeroLinea;
            public Int32Field Etapa;
            public StringField EtapaNombre;
            public StringField FechaLog;
            public Int32Field Categoria;
            public StringField DatObservacion;             
            public Int32Field DetObservacion;
            public StringField DetDatObservacion;
            public DateTimeField FechaRegistro;
            public StringField Usuario;
        }
    }
}

Edit of the detail class is:

/// <reference path="../../Common/Helpers/GridEditorBase.ts" />

namespace SegurosMAPC.BaseDatos {

    @Serenity.Decorators.registerClass()
    export class LogDetalleArchivoEditor extends Common.GridEditorBase<LogDetalleArchivoRow> {
        protected getColumnsKey() { return "BaseDatos.LogDetalleArchivo"; }
        protected getDialogType() { return LogDetalleArchivoDialog; }
        protected getLocalTextPrefix() { return LogDetalleArchivoRow.localTextPrefix; }

        constructor(container: JQuery) {
            super(container);
        }

        protected validateEntity(row: LogDetalleArchivoRow, id: number) {
            if (!super.validateEntity(row, id))
                return false;
            row.NumeroProceso = Q.toId(row.NumeroProceso);

            row.DatObservacion = TaProcLogCategoriaRow.getLookup().itemById[row.Categoria].DatObservacion;

            return true;
        }

        protected getButtons(): Serenity.ToolButton[] {
            var buttons = super.getButtons();
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);
            return buttons;

        }

        protected getAddButtonCaption() {
            return "Agregar Bajas";
        }
        
    }
}

Any help I will appreciate.
Atte.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
