### ISSUE TITLE
Default start page

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#518]
Dear @volkanceylan,
I would like to know which is the proper way to change the default start page...
I'm trying to set "Northwind/Order?shippingState=0" as default page, but without any luck...
I was playing with the route attribute:
...Route("~/")...
in the DashboardPage.cs, but clearly I'm doing something wrong because when I open the application the default page is still the Dashboard (and also when I click on the Serenity logo).

Thanks (as always) for your support
Best Regards

**Comment by volkanceylan** [comment]
You should put Route("~/") on OrderPage Index action and remove one in DashboardPage Index action.

**Comment by marcobisio** [comment]
This is exactly what I have done, but still I'm not able to add url parameter (shippingState for example).
Any idea?

**Comment by volkanceylan** [comment]
So use Route("~/{shippingState=}")

**Comment by volkanceylan** [comment]
You shouldnt add shippingState default to url. It should be a nullable parameter that defaults to 0

**Comment by marcobisio** [comment]
Uhm only with a single route is working fine, but my custom navigation link has stopped working...
In fact, in the left navigation menu I have added a couple of navigation link with a custom url:

    [assembly: NavigationLink(1100, "Inbox", url: "~/CSH/Ticket?isInbox=1", permission: "Inbox", icon: "icon-envelope-letter")]
    [assembly: NavigationLink(1200, "My Tickets", url: "~/CSH/Ticket?isCurrentUser=1", permission: "MyTickets", icon: "icon-user")]

And to make it works I had to add two route directive:
    
    namespace eService.CSH.Pages
    {
    	using Serenity;
    	using Serenity.Web;
    	using System.Web.Mvc;
    
    	[RoutePrefix("CSH/Ticket"), Route("{action=index}")]
    	public class TicketController : Controller
    	{
    		[Route("~/")]
    		[Route("~/CSH/Ticket")]
    		[PageAuthorize(CSH.PermissionKeys.Ticket.View)]
    		public ActionResult Index()
    		{
    			return View("~/Modules/CSH/Ticket/TicketIndex.cshtml");
    		}
    	}
    }

But what I'm still trying to achieve is that the default page is the "Inbox" one or, in other words, that the default url is the same of the "Inbox" navigation link.
If this is not possibile I'll take the nullable parameter way as per your suggestion...

Thanks again
Best Regards

**Comment by volkanceylan** [comment]
This should go into logic of your inbox page not url. When user types "/" he expects to get default page. Anyway if you insist, change links directing to "~/" everywhere to "~/?x=inbox etc, e.g. in layout.

**Comment by marcobisio** [comment]
Copy that!

Thanks for your support
Best Regards
