### ISSUE TITLE
Properties for CommonDialogOptions

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5180]
JQueryUI.DialogOptions has `minHeight, maxHeight, minWidth, maxWidth, zIndex`, but since it is not inherited anymore, those are not available

@volkanceylan Is there a way or possibility to set `minHeight, maxHeight, minWidth, maxWidth, zIndex` options to [CommonDialogOptions](https://github.com/volkanceylan/Serenity/blob/master/Serenity.Scripts/CoreLib/Q/Q.Dialogs.ts#L14)?

**Comment by volkanceylan** [comment]
No, but you can always cast to any like as any etc.
