### ISSUE TITLE
FlatPickr integration bugs - Serenity 3.14.0

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#5181]
hey there, may be i will have more chances to ask here :

2 bugs about FlatPickr integration that do not behave like previous jQuery DatePicker

My previous date field was using jQuery and was read only. 
After switching to FlatPickr,
Before : (i cannot modify date nor time) => correct behavior

![image](https://user-images.githubusercontent.com/31513956/91059018-7ccbcc80-e629-11ea-9eec-453c268a85d4.png)

After : not correct behavior
![image](https://user-images.githubusercontent.com/31513956/91058862-44c48980-e629-11ea-8df4-d23f20450234.png)
I can modify the field date (it seems not longer being readonly) => it gives user the feeling user can change the value (while he cannot save changes actually).

Another side effect, the date field being the first one on the form, when the form is displayed the calendar is automatically displayed, hiding field content (i did not click into the field) :

![image](https://user-images.githubusercontent.com/31513956/91059439-011e4f80-e62a-11ea-9b66-3844dae7fdcc.png)

**Comment by volkanceylan** [comment]
@kilroyFR that is how it works. They are not 100% percent compatible. Maybe we'll find workarounds for some, maybe not. We provided an option to use flatpickr, mostly for frontend pages where jQuery UI will not be available. It's up to you to use flatpickr, or not, considering these subtle differences.

**Comment by kilroyFR** [comment]
ok thanks. Good to know.
