### ISSUE TITLE
how to make a list from *.row.cs file ?

### ISSUE THREAD

**Issue by amirkian** [volkanceylan/Serenity#5183]
I used this code to make a list 
`
      AnswerSheetService.List({  }
                        , response => {
                                       var myentities = response.Entities;

                            for (var i = 0; i < myentities.length; i++) {
                                myentities[i].Id = i.toString();
                                myentities[i].CurrentStatusScore = 0;
                                myentities[i].OptimalStatuScore = 0;
                                myentities[i].QuestionnaireId = "38308bf0-9fab-4dff-a8c7-55608502d470";
                                myentities[i].ItGQuestionText = ItGQuestionRow.getLookup().items[i].Text;
    
                            }
                         this.setItems(myentities);
                        })
`
as you can see I get my list by response  methdo but I like to make a list with nth item as i like 
I need somthing like this

`list < AnswerSheetRow > mylist=new AnswerSheetRow;`

but it dosen't work in typescript.
how can I make a list from *.row.cs file ?

**Comment by welcometoall** [comment]
Did you try IncludeColumns?
`AnswerSheetService.List({ IncludeColumns:["ItGQuestionText"] }`?
