### ISSUE TITLE
using rowSelection.getSelectedKeys on grid to generate PDF based on selected records

### ISSUE THREAD

**Issue by chrisomeara** [volkanceylan/Serenity#5185]
hi all - apologies in advance if this a basic coding question, I have spent quite a bit of time trying to implement this extract from [ https://serenity.is/docs/fluent_sql/criteria_objects ](url):
 
![image](https://user-images.githubusercontent.com/60803408/91790361-25d68080-ec43-11ea-8ab5-dcdc25c79ed1.png)
but I seem to be at an impasse, so I humbly seek your help. I am at the tail end of my project.

My goal is to select records in the grid using GridRowSelectionMixin as per the guide, and generate a PDF based on the id's of those selected records.

Note all works perfectly when one record is selected and I pass a single integer to a "WHERE ID == ID" query.

I would like to replicate a WHERE od.id IN (TradeIDs) query.  eg WHERE od.id IN (3592, 3593) 

[grid.ts] - here is the button onclick event which in this example  passes  {[  3592,  3593]} in the variable TradeIDs to the report.cs if record ids 3592 and 3593 are selected
![image](https://user-images.githubusercontent.com/60803408/91791138-ee68d380-ec44-11ea-8780-26707b645c91.png)

[report.cs] based on [https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Order/OrderDetailReport.cs](url)

my quesion is how do I pass {[3592, 3593]} from this.TradeIDs to the `new Criteria(od.Id).In(x)  ` section of the query ?

Note when hard coded as `IEnumerable<int> x = new int[] { 3592, 3593 }; `  it works perfectly as desired

![image](https://user-images.githubusercontent.com/60803408/91793285-5a9a0600-ec4a-11ea-9d55-ce06500d40a3.png)

Thank you

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
