### ISSUE TITLE
Sponsored  Development

### ISSUE THREAD

**Issue by reach2rv** [volkanceylan/Serenity#5186]
Hi @volkanceylan 

We would like to achieve

1. https://github.com/volkanceylan/Serenity/projects/1#card-11424052
2. https://github.com/volkanceylan/Serenity/projects/1#card-11424077

Can you please help us with approx costing if we have to support this development.

Thank you.

**Comment by volkanceylan** [comment]
Hi @reach2rv, please contact us from support@serenity.is with your requirements if any like scale of customization ability, expected ui, features etc.
