### ISSUE TITLE
Shortcut Keys [Hot Keys] for Editor buttons

### ISSUE THREAD

**Issue by reach2rv** [volkanceylan/Serenity#5187]
Hi @volkanceylan @minhhungit 

Can you guys please guide me how I can assign a shortcut Key [hotkey] to Editor Button till now I have tried following and it doesn't work. It is very important to get this functionality for the project I am working on.

```JavaScript
// *** Add Select Button to Grid Editor ***
            buttons.push({
                title: "Select Items",
                cssClass: "add-button",
                hotkey: "Alt+K",
                onClick: () => {}
});

```

Thank you for your support

Regards,

Arvind

**Comment by minhhungit** [comment]
I am not sure about "editor button", what is that

**Comment by minhhungit** [comment]
@reach2rv you mean button on inline grid editor ?

![image](https://user-images.githubusercontent.com/2279508/92412570-8e0ef000-f176-11ea-9d84-28acc38068dc.png)

**Comment by reach2rv** [comment]
> @reach2rv you mean button on inline grid editor ?
> 
> ![image](https://user-images.githubusercontent.com/2279508/92412570-8e0ef000-f176-11ea-9d84-28acc38068dc.png)

yes

**Comment by reach2rv** [comment]
@minhhungit 

I have tried following code too to make it focusable but onclick and shortcut key still doesn't work

```JavaScript
 this.element.find('.add-button').attr("role", "button");
            this.element.find('.add-button').attr("tabindex", "0");
            var addbutton = this.element.find('.add-button');
            $('document').bind('keypress', function (e) {
                var alt = false;
                if (e.keyCode == 18)
                    alt = true;
                if (alt == true && e.keyCode == 75)
                    addbutton.trigger('click');
            });
```

**Comment by minhhungit** [comment]
@reach2rv where did you put the code on?, grid, dialog or inline grid on dialog

**Comment by reach2rv** [comment]
inline grid Editor constructor

**Comment by minhhungit** [comment]
@reach2rv  ah I see your comment, try this code

put it on editor.ts

```js
protected createToolbar(buttons: Serenity.ToolButton[]): void {
            var toolbarDiv = $('<div class="grid-toolbar"></div>').appendTo(this.element);
            this.toolbar = new Serenity.Toolbar(toolbarDiv, { buttons: buttons, hotkeyContext: document.getElementsByTagName('body')[0] });
        }

        getButtons() {
            let buttons = super.getButtons();

            buttons.push({
                title: "Test shortkey",
                hotkey: "alt+k",
                //hotkeyContext: document.getElementsByTagName('body')[0],
                onClick: () => {
                    Q.notifyInfo("Hello");
                }
            })

            return buttons;
        }
```

**Comment by reach2rv** [comment]
@minhhungit the above code works. I do get a notification.  Thank you.. before closing the last query

if I am not wrong I need to change 
`document.getElementsByTagName('body')[0]`

this to 

```
document.getElementsByTagName('body')[1] or 

document.getElementsByTagName('body')[2]
```

depending upon the number of buttons??
