### ISSUE TITLE
Layout problem in Halfwidth form fields

### ISSUE THREAD

**Issue by premsudheer** [volkanceylan/Serenity#5188]
Hi All,
Looking for a CSS trick for the below. 
when I am making the form fields half-width, all the fields are not getting aligned properly as below. I want to achieve the layout as per the second image.
![image](https://user-images.githubusercontent.com/48126071/92190137-f19ad400-ee7d-11ea-96d2-6fa02236af73.png)

I want to fill the layout with  the remaining fields as below
![image](https://user-images.githubusercontent.com/48126071/92190206-2575f980-ee7e-11ea-940f-5936511552a6.png)

Could anybody help with some guidelines?

**Comment by premsudheer** [comment]
Hi Volkanceylan,
appreciate your comment on this. I just want to utilize (hence form looks good) right-hand side of the HtmlReportContentEditor and filled with remaining fields of the form. because when I am increasing the height of the HtmlReportContentEditor , then the right side of it remains a huge plain blank space after the one field on the right side. 
I guess you might have written some mixins to handle this.

Kindly advise.
Regards
Prem

**Comment by reach2rv** [comment]
Hi,

Please check the following issues, it might help you. 

#5119

**Comment by premsudheer** [comment]
Hello @reach2rv, Thank you so much for your help and this leads me in the right direction. I will try this.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform

**Comment by premsudheer** [comment]
@VictorTomaili thanks. the solution by @reach2rv is working for me
