### ISSUE TITLE
Filter data based on extended user profile

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#519]
I was able to extend the use profile to hold a country relation done with a new **UserCountry** Table
so user can belong to multiple countries  as below 

![usernewprofile](https://cloud.githubusercontent.com/assets/728937/14290400/9db475fc-fb67-11e5-96b6-e43dfd77fcd3.png)

in another form called **PE** a record can also belong to multiple countries  as below with a table called **PEcountries** as below

![pecountries](https://cloud.githubusercontent.com/assets/728937/14290414/a92b3056-fb67-11e5-876c-bac04fe21f62.png)

all working fine data is updated inserted deleted perfectly thanks to **Serenity** and @volkanceylan 

my next objective is to view data in PE Row based on logged in user tried to follow Multi Tenancy tutorial but this is not the behavior I  want as all users login to the same application 

any directions is appreciated form any one have implemented successfully filter data by user ,

Again thanks to @volkanceylan for the effort and time spent on the template as its highly sophisticated and professional peace of art

**Comment by volkanceylan** [comment]
You should do such filtering in repository with exists or IN filters

**Comment by zerodev** [comment]
that's what I have done in the list handler
