### ISSUE TITLE
Any working example for optgroup for select2 in serenity?

### ISSUE THREAD

**Issue by Moheeb-U** [volkanceylan/Serenity#5190]
I would appreciate if someone provide an example of  optgroup for select2 in serenity.

I could use cascase dropdown. still if someone have already worked on optgroup. ;)

**Comment by RouteTech** [comment]
You could try something like

                var localServerListElement = document.getElementById("LocalServerList");
                for (var i = 0; i < this.LocalSqlServerInstanceNames.length; i++) {
                    var newOption = new Option(this.LocalSqlServerInstanceNames[i], i.toString(), true, true);
                    localServerListElement.appendChild(newOption);
                }

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
