### ISSUE TITLE
How to make sections in Form.cs

### ISSUE THREAD

**Issue by waqarkabir** [volkanceylan/Serenity#5193]
I want to make sections of my Form.cs with headings of different colors and fonts.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
