### ISSUE TITLE
prevent two users from saving the same record and data overlap

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#5195]
Hello,
What is the best approach to prevent two users from saving the same record and data overlap? Any example would be appreciated.

Any option better than compare form last update field with last update field in DB inside "BeforeSave()" / "MySaveHandler" ?

Thx

**Comment by minhhungit** [comment]
IMHO

- you can write code to check duplicate row before insert by overwriting ValidateRequest method on repository.MySaveHandler
- or using UniqueConstraint attribute on your row, like this:

```csharp
   [UniqueConstraint(new[] { "SupplierId", "OemNumber", "StockNumber", "YardLocation" })]
   public sealed class InventoryStoreRow : Row, IIdRow, INameRow {
      [DisplayName("Id"), Identity]
      public Int32? Id
      {
          get { return Fields.Id[this]; }
          set { Fields.Id[this] = value; }
      }
   }
```
or you can even create an unique index on your table

**Comment by teafmartins** [comment]
And if it is an update? how can you avoid saving non updated fields?

**Comment by minhhungit** [comment]
how updating can be duplicated :?

**Comment by minhhungit** [comment]
I think you can use a "version" column to check if it's dirty

**Comment by minhhungit** [comment]
@teafmartins check optimistic locking

![image](https://user-images.githubusercontent.com/2279508/92344366-75f48d80-f0f0-11ea-9e88-361f63a38e70.png)

**Comment by minhhungit** [comment]
here is a link on wiki which I think it relates to your problem

https://github.com/volkanceylan/Serenity/wiki/Database:-Optimistic-locking-support-for-MS-SQL-Server-by-hannesb

**Comment by teafmartins** [comment]
Thanks
