### ISSUE TITLE
Why does Serenity.Data not support asynchronous operations?

### ISSUE THREAD

**Issue by newyearsoft** [volkanceylan/Serenity#5197]
Hi,
Why does Serenity.Data not support asynchronous operations?
In some cases asynchronous operations are required for performance.
Please update the Serenity.Data package to support asynchronous query operations.
Thank you very much!

**Comment by volkanceylan** [comment]
You may use Dapper for asynchronous operations if you like. Asynchronous and performance does not have much relation, it is mostly for IO bound app scalability in some cases. Anyway this is open source project, so you fork and add async methods if you like.

**Comment by newyearsoft** [comment]
https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1
