### ISSUE TITLE
remove blank from lookup.

### ISSUE THREAD

**Issue by tmartinscopo** [volkanceylan/Serenity#5199]
Hi,
How can I prevent a filter (quickfilter) from being blank?
I want to remove blank from lookup.
Thanks

**Comment by minhhungit** [comment]
you can create a custom lookup, ex;

```csharp
[LookupScript("THIS_IS_YOUR_LOOKUP_KEY", Expiration = -1, Permission = "*")]
public class DemoLookup : Serenity.Web.LookupScript
{
    public DemoLookup()
    {
        this.IdField = "Something";
        this.TextField = "Something to display";
        this.getItems = this.GetItems;
    }

    protected virtual IEnumerable<dynamic> GetItems()
    {
        // return your result here, remove empty value
    }
}
```

then use it on your row
```csharp
[lookupeditor(typeof(DemoLookup))]
public Int64 AbcField{

}
````

**Comment by tmartinscopo** [comment]
But the lookup is based on a database table 
I want to force the user to enter a value in the quickfilter field and not allow empty values.
Thx

**Comment by hannesb** [comment]
try this:
`        [QuickFilter, QuickFilterOption("allowClear", false)]
`

HTH
Hannes

**Comment by tmartinscopo** [comment]
works like a charm
thx
