### ISSUE TITLE
New auto generated code not work correctly sometimes

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#52]
Hi JaiQ
I'm trying to add a Subject form by sergen.exe code auto generated but i can't work properly. The browser console show that 'Uncaught TypeError: IntraMVC.CourseDB.SubjectGrid is not a function.  after that i delete Subject folder in CourseDB from IntaMVC.Script and IntraMVC.Web and agian run sergen.exe and code generated. This procedure try 3 to 4 times after it work fine.

Please tell me the exact problem how misbehave it. How can i fix this?

**Comment by volkanceylan** [comment]
Please try rebuilding project after generating code. Maybe Visual Studio thinks nothing changed and doesn't rebuild script project. Check if IntaMVC.Script.Site.js is copied from IntaMVC.Script\bin\debug\ directory to IntaMVC.Web\scripts\site folder (same contents/size). If they are different after rebuild, it means something is wrong. Try adding InvaMVC.Script to project dependencies of IntaMVC.Web.

**Comment by volkanceylan** [comment]
Reopen if it didn't resolve your issue.

@laxmanp you should close your issues if they are resolved, or do status updates
