### ISSUE TITLE
Save grid to PDF

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#520]
Is it possible to render a grid to PDF file (similar to Excel export option)? I looked for an example of this but all I found was the invoice example. Many thanks in advance.

**Comment by volkanceylan** [comment]
No there is no such option, closest you can get is order detail list in invoice example.

**Comment by c9482** [comment]
But is it possible to do? What would it take?

**Comment by volkanceylan** [comment]
It shouldn't be so hard, see how excel generator converts it to excel, especially data and representation, than make a CSHTML report and convert to a table
