### ISSUE TITLE
form top button to open another form

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#5202]
Hello,
How can I create a button in Product form to open supplier edit form?
(something like inplace button, but at the top of product form)
![image](https://user-images.githubusercontent.com/17210232/92829905-a8daa200-f3cc-11ea-9809-b91c78928092.png)
Thank you community.

**Comment by waqarkabir** [comment]
Please refer to issue #4715

**Comment by teafmartins** [comment]
Nice! Thank you.
And it you want to open some record ID, just use loadById:

var dlg = new yourDialog()
dlg.dialogOpen();
dlg.loadById(this.entityId);
