### ISSUE TITLE
Unable to use @Serenity.Decorators.panel() along with onDialogOpen() event on dialog.ts

### ISSUE THREAD

**Issue by spisipa** [volkanceylan/Serenity#5203]
If you use the Decorators.panel on a dialog.ts and you also use the onDialogOpen() event handler, you get the following error
jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg2:7856 Uncaught RangeError: Maximum call stack size exceeded

Once you remove the onDialogOpen() event handler on the dialog.ts , there is NO error and the dialog is in panel mode.

**Comment by waqarkabir** [comment]
Are you calling same dialog.ts from onDialogOpen() ?

**Comment by spisipa** [comment]
Thank You!! 

Your question lead me to  realize that I had   super.dialogOpen() (instead of super.onDialogOpen())  in the onDialogOpen() code.
Fixing this resolved the issue.
