### ISSUE TITLE
Serenity .Net Core in Visual Studio Code Works Defective

### ISSUE THREAD

**Issue by muhammedyaman** [volkanceylan/Serenity#5204]
I am trying to develop a .net core application with visual studio code. Whenever I create a new grid, editor or dialog template with tabs it doesn't work. For grid it gives xxxGrid is not a constructor, editor gives xxxEditor editor type not found, for dialog template it doesn't give an error but second tab doesn't load data. When i build the project in visual studio without any changes it works. Is there a solution to this?

**Comment by volkanceylan** [comment]
If you don't build typescript of course it won't work and give error. Also TypeScript language service has issues with newly generated files.

**Comment by muhammedyaman** [comment]
I didn't know that I had to build tsc manually in vs code. Thanks very much.
