### ISSUE TITLE
Two or Three Fields on same line in Dialog Declaratively

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#5205]
Hi,
I read a tutorial that shows how to declaratively arrange more than one field on the same line in dialog. I have been searching for it for hours and I can't find that tutorial.

Can anyone please help me locate it?

Regards,

**Comment by dfaruque** [comment]
use `[HalfWidth]` attribute for showing two fields in a line.
use `[OneThirdWidth]` attribute for showing three fields in a line.

**Comment by gfo2007** [comment]
@dfaruque thank you. I was looking for the tutorial that explains everything. I just realized it was a blog post on Serenity site. For anyone interested, the link is below

https://serenity.is/blog/2018/05/16/multi-column-layout
