### ISSUE TITLE
Cascaded Editors again: Has CustomerRow a CountryId, CityId and DistrictId?

### ISSUE THREAD

**Issue by MrPec** [volkanceylan/Serenity#521]
Hello,

I still got an issue with the HowTo.
Could you please post the full example, or at least the CustomerRow?

I'm not sure if the customer entity needs a reference to CountryId, CityId and DistrictId. I try to get it to work that the customer only has a reference to DistrictId.

Alex

**Comment by volkanceylan** [comment]
You should add these fields as view fields to Customer entity, see mapping guide

**Comment by jsbUSMC** [comment]
@MrPec you can go to the [Serene Repository][1] to browse the code for the Serene sample. In the case that you're inquiring about, you'll specifically want to take a close look at the Customer module in [Serene.Web project][2] and the CustomerCity.cs and CustomerCountryLookup.cs classes. This is one way that you can create cascaded lookup editors. If you want the cascaded lookup editors on the grid, then take a glance at the [CustomerGrid.cs class][3] in the Serene.Script project. Check out the `AddEqualityFilter<>` methods. Here is a snippet:

```cs
// ...
protected override void CreateToolbarExtensions()
        {
            base.CreateToolbarExtensions();

            AddEqualityFilter<LookupEditor>(Fields.Country,
                options: new LookupEditorOptions { LookupKey = "Northwind.CustomerCountry" });

            AddEqualityFilter<LookupEditor>(Fields.City, options: new LookupEditorOptions {
                LookupKey = "Northwind.CustomerCity", CascadeFrom = Fields.Country });
        }
// ...
```

Hope this helps straighten some things out.

[1]: https://github.com/volkanceylan/Serene
[2]:https://github.com/volkanceylan/Serene/tree/master/Serene/Serene.Web/Modules/Northwind/Customer
[3]: https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Northwind/Customer/CustomerGrid.cs

**Comment by MrPec** [comment]
Great, thank you! I found the information right here:
https://volkanceylan.gitbooks.io/serenity-guide/content/entities/mapping_attributes.html

What I need is exactly answered in the question "What if we don't have a CountryId field in Customer table, but we want to bring Country names of cities through CountryId field in city table?" :)

Thank you!

**Comment by volkanceylan** [comment]
You're welcome, thanks @jsbUSMC
