### ISSUE TITLE
Card View

### ISSUE THREAD

**Issue by gfo2007** [volkanceylan/Serenity#5210]
Hi,
I chanced on the issue #4759 which shows how to turn a grid view into a card view with the code snippet below.
```
this.element.find('.grid-title .view-switch').hide().find('input[type=radio]').eq(1).click();
```
The card view should look like below.

![card view](https://user-images.githubusercontent.com/14317420/93208834-bbe2ce80-f74c-11ea-83fe-26cc79a060b5.png)

However, when I insert the code snippet above in my XYZGrid.ts, it doesn't change into the card view.

What am I doing wrong?

Regards.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
