### ISSUE TITLE
FormWidth does not work with CSS

### ISSUE THREAD

**Issue by reach2rv** [volkanceylan/Serenity#5212]
Hi

I am trying to apply formwidth to form fields

[FormWidth (Small=12, Medium=6, Large= 4)]

![sc1](https://user-images.githubusercontent.com/16520558/93346517-b28f5a00-f851-11ea-9bcd-ad1abd107166.png)

I have added column width to the media query in serenity css

![sc2](https://user-images.githubusercontent.com/16520558/93346524-b3c08700-f851-11ea-86e8-ab4b8d3bb3fd.png)

After doing this when I run the application and use chrome dev tools to validate responsiveness using the device iPad only the width of col-md-6 shows as applied and UI looks weird when I manually apply col-sm-12 in dev tools UI looks okay. 

![test](https://user-images.githubusercontent.com/16520558/93346641-d18dec00-f851-11ea-90b6-563f23b2b896.gif)

Any Idea what I am doing wrong.

**Comment by VictorTomaili** [comment]
Serenity uses flex layout system there. Check CSS Flex

**Comment by reach2rv** [comment]
@VictorTomaili thanks for your reply. Me being a C# developer is bit confusing as never directly worked on CSS. If I am not wrong do I need to add .flexlayout before .col-sm-12.field??

**Comment by VictorTomaili** [comment]
I never directly worked on css either. But I think you must check how to work flex system on css before made any changes.
