### ISSUE TITLE
[Suggestion] Search Suggestions in QuickSearch if Contains Field is selected

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5216]
Is there any possibility to do Search suggestions based on options `{name: 'FieldName', title: 'Field Name', searchSuggestions: true}` for Quick Search `getQuickSearchFields()` when Contains field is selected?

**Comment by VictorTomaili** [comment]
Quick filter is already shows all suggestions as grid results.

**Comment by welcometoall** [comment]
if we want to have multiple fields in quick search drop down, It looks very bad to add multiple Quick filters.

**Comment by VictorTomaili** [comment]
If you need search multiple field on grid. Just add QuickSearch attribute on your row.

**Comment by welcometoall** [comment]
```
protected getQuickSearchFields(): Serenity.QuickSearchField[] {
            let fld = MovieRow.Fields;
            let txt = (s) => Q.text("Db." + 
                MovieRow.localTextPrefix + "." + s).toLowerCase();
            return [
                { name: "", title: "all" },
                { name: fld.Description, title: txt(fld.Description) },
                { name: fld.Storyline, title: txt(fld.Storyline) },
                { name: fld.Year, title: txt(fld.Year) }
            ];
        }
```

![image](https://user-images.githubusercontent.com/11242099/93736401-cfcf7a00-fbfd-11ea-97ff-0c0fdd905ec5.png)

**Comment by VictorTomaili** [comment]
You can edit or write your own quicksearch editor if you want. Also PR's are allowed if you have done some of improvements.
