### ISSUE TITLE
Ideas please - display entity on validation of two fields

### ISSUE THREAD

**Issue by bigjezza** [volkanceylan/Serenity#5218]
In a nutshell,
I have a form with two fields. Membership number and PIN.

Upon submitting it will show an entity dialog for the row that matches those two fields. Membership number is not the ID column.

I'd like to prevent access to that table if the two fields don't match the data.

Would a stored procedure be the right way? ie select memberid from dbo.members where PIN = field AND number = field which returns the ID column, then send that ID over to loadByIdAndOpenDialog?

Any other ideas?

**Comment by reach2rv** [comment]
apart from stored procedure you can create a custom list request class and create a repository method and endpoint with that class. in typescript you can call the endpoint and if response.entity >0 the load dialog with response.entity

**Comment by bigjezza** [comment]
Thanks.
I’m calling a vanilla list request made with sergen from a js function in the cshtml with the ListRequests EqualityFilter set to the fields on the page.

Is there a smarter way?
