### ISSUE TITLE
How to extend Serenity Row class

### ISSUE THREAD

**Issue by qubess** [volkanceylan/Serenity#5219]
Hi Volkan,

Trying to extend Row class properties, below is the code snippet. It is generating the typescript model successfully but getting runtime error as "**_exception of type 'System.InvalidCastException'_**"

`

    public abstract class _ARow : Row
    {
        public String AField
        {
            get { return Fields.AField[this]; }
            set { Fields.AField[this] = value; }
        }

        public static readonly ARowFields Fields = new ARowFields().Init();

        public _ARow(ARowFields fields)
            : base(fields: fields)
        {
        }

        public class ARowFields : RowFieldsBase
        {
            public StringField AField;
        }
    }

    public sealed class BRow : _ARow
    {
        public String BField
        {
            get { return Fields.BField[this]; }
            set { Fields.BField[this] = value; }
        }

        public new static readonly BRowFields Fields = new BRowFields().Init();

        public BRow()
            : base(Fields)
        {
        }

        public class BRowFields : ARowFields
        {
            public StringField BField;

            public BRowFields()
            {
                LocalTextPrefix = "BRowFields";
            }
        }
    }
`

**Comment by qubess** [comment]
`


	export interface BRow {
		BField?: string;
		AField?: string;
	}

	export namespace BRow {
		export const localTextPrefix = 'BRowFields';

		export namespace Fields {
			export declare const BField: string;
			export declare const AField: string;
		}

		[
			'BField', 
			'AField'
		].forEach(x => (<any>Fields)[x] = x);
	}
	
	
`

**Comment by dfaruque** [comment]
do not initialize RowFields in base class
instead of `public static readonly ARowFields Fields = new ARowFields().Init();` write `private ARowFields Fields;`

**Comment by qubess** [comment]
Thanks dear for your prompt help, it works perfectly.
