### ISSUE TITLE
Serenity in Typescript

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#522]
I have seen a great progress on typescript implementation.

I am little bit excited to play with typescript in serenity. 
So can you please give me an idea about the release date (expected).

Thanks for your great work. :+1:

**Comment by volkanceylan** [comment]
Serenity 2.0.0 nuget packages with TypeScript support has just been published. Should wait for Serene release tomorrow and migration guide. It will take some time for it to stabilize, as there has been so many changes underneath.

**Comment by wdhodges** [comment]
Is it save to upgrade existing applications to 2.0.0 or will you cover this in the migration guide? 

Either way, still very excited

**Comment by volkanceylan** [comment]
It should be but of course there are some risks, so take a backup first... I'll document how to configure existing projects to use TypeScript

**Comment by awesomegithubusername** [comment]
Exciting  news indeed. Looking forward to tomorrow !

**Comment by volkanceylan** [comment]
Here is migration guide for old projects:

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_upgrade_to_serenity_2_typescript.html

For new projects, just download latest Serene.

**Comment by dfaruque** [comment]
wow. I am trying now..........
