### ISSUE TITLE
Sending Email As Attachment 

### ISSUE THREAD

**Issue by reacharihant** [volkanceylan/Serenity#5220]
....
If you call the action method ReportController.Render or ReportController.Download (which are the standard action that Serenity use) the Request (HttpRequestBase type) contains valid information.
But if you call RenderAsPdf directly, you must pass a ControllerContext that contains context information.

E.g. : 

```cs
private byte[] RenderAsPdf(IReport report, string key, string opt, ControllerContext context = null)
{
    string externalUrl = string.Empty;
     if (context == null)
         externalUrl = Config.Get<EnvironmentSettings>().SiteExternalUrl ??
         Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
     else
     {
         externalUrl = ((System.Web.HttpRequestWrapper)((System.Web.HttpContextWrapper)((System.Web.Mvc.Controller)context.Controller)
                    .Url.RequestContext.HttpContext).Request)
                    .Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");
            }
    [...]
```

I have used this way to generate a PDF on the fly without output it.

Sei italiana? :)

_Originally posted by @Estrusco in https://github.com/volkanceylan/Serenity/issues/2819#issuecomment-339887478_

**Comment by reacharihant** [comment]
I am facing issue in the line from above code:

Request.Url.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/");

It is not finding the Request.Url property. Can you suggest solution? I am trying to send an email with an attachment.

**Comment by VictorTomaili** [comment]
Can you edit the title clearly?

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
