### ISSUE TITLE
Resize Grid in CSS table on page resize

### ISSUE THREAD

**Issue by bigjezza** [volkanceylan/Serenity#5221]
Hi, I have a couple of grids in separate columns in a simple css table.
If I resize the page, the grid view width resizes down. But if I then make the page larger, the grid views don't change. They are stuck on their smaller size.

Right now I've got this on the page which seems to fix it (I've disabled headers and pager, hence why I'm only touching grid canvas)

```
$(window).resize(function () {

    $('.grid-canvas').css('width', '100%');

});
```

But I'm wondering how to implement layouttimer, or another option? Will it work for this problem?

Or how do I call resizeCanvas(), or is there some other function to resize the grid and the columns?

**Comment by VictorTomaili** [comment]
Your grids must be a parent container widget. You can store grid objects there and trigger resizeCanvas() from there. Or just call event named `resize.slickgrid` from element of grid. This event also trigger resizeCanvas() function of grid.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
