### ISSUE TITLE
Why we use Transform all T4 Templates in serenity.

### ISSUE THREAD

**Issue by saiprasadchinna** [volkanceylan/Serenity#5223]
Hi everyone,

Why we use Transform all T4 Templates in Visual studio.

@volkanceylan @VictorTomaili

**Comment by volkanceylan** [comment]
You don't use that with .NET Core, and if you haven't still migrated, you should.

**Comment by VictorTomaili** [comment]
This question is same as "Why we build project before run?". T4 Templates are for creating serverside and clientside auto generated codes. .Net Core version doesn't needs T4 Templates like Asp.Net version. 

Check: #5060 and #4801
