### ISSUE TITLE
 Problem to view the application

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5226]
![imagen](https://user-images.githubusercontent.com/42218266/94311944-72fff680-ff52-11ea-85e5-021dd6a0c28a.png)
Community, I have the following problem, it does not display the screens correctly. I have looked for solutions but have not been able to find. If there is someone who can guide me to solve it. In the meantime I leave you an image that shows the indicated problem. Thank you :

**Comment by VictorTomaili** [comment]
It's looks less doesn't compiled well. Do you have node js and npm? If not, install node.js LTS version.

**Comment by patriciomh1965** [comment]
Well, I'm going to install it, Thanks !!

**Comment by VictorTomaili** [comment]
It's seems like fixed. I close this issue 👍
