### ISSUE TITLE
lookupeditor show saved but inactive record

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#5227]
Hello,
I have a lookupeditor that shows only active active records. If the actual record is inactive it will not show up.
Is there any easy way to aslo include the saved record (even if inactive) in the lookupeditor.
Any paramteter for this? can't find it.

[LookupEditor("Department", FilterField = "Status", FilterValue = 1 )]

**Comment by VictorTomaili** [comment]
Create your own custom lookup for use it on lookup editor. There is some sample in wiki and docs.
