### ISSUE TITLE
The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#523]
Hi everyone,

I got this error when trying to open a dialog from a row that contains a lookup with a TextField having the NTEXT SQL type : (fiddler)

[SqlException (0x80131904): The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +212
   System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +81
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +631
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +3790
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +58
   System.Data.SqlClient.SqlDataReader.get_MetaData() +89
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +388
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest) +2041
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +377
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +53
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +254
   System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) +37
   System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader() +12
   Serenity.Data.SqlHelper.ExecuteReader(IDbConnection connection, String commandText, IDictionary`2 param) in C:\Projects\Serene\Serenity\Serenity.Data\SqlHelpers\SqlHelper.cs:635
   Serenity.Data.SqlHelper.ExecuteReader(IDbConnection connection, SqlQuery query) in C:\Projects\Serene\Serenity\Serenity.Data\SqlHelpers\SqlHelper.cs:691
   Serenity.Data.EntitySqlHelper.ForEach(SqlQuery query, IDbConnection connection, Action callBack) in C:\Projects\Serene\Serenity\Serenity.Data.Entity\Extensions\EntitySqlHelper.cs:227
   Serenity.Web.RowLookupScript`1.GetItems() in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScriptTypes\RowLookupScript.cs:91
   Serenity.Web.LookupScript.GetScript() in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScriptTypes\LookupScript.cs:28
   Serenity.Web.Item.GenerateContent() in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScript\DynamicScriptManager.Item.cs:79
   Serenity.Web.Item.EnsureContentBytes() in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScript\DynamicScriptManager.Item.cs:135
   Serenity.Web.DynamicScriptManager.GetScript(String name) in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScript\DynamicScriptManager.cs:94
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScript\DynamicScriptHandler.cs:18
   Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessRequest(HttpContext context) in C:\Projects\Serene\Serenity\Serenity.Web\Script\DynamicScript\DynamicScriptHandler.cs:58
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +816
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +80

I had to modify the corresponding query (thanks to Stackify Prefix, an excellent  .NET profiler) from something like this:
 `SELECT T0.[xyzId] AS [CgmpNaturesureteId],T0.[xyzText]
FROM [cgmp].[xyz] T0
ORDER BY T0.[xyzText]`

to something like this:
`SELECT T0.[xyzId] AS [xyzId],CAST(T0.[xyzText] AS NVARCHAR(100)) AS [xyzTextCasted]
FROM [dbo].[xyz] T0
ORDER BY [xyzTextCasted]`

My lookup for reference:
`namespace MultiTenancy.Something.Scripts
{
    using Entities;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("Something.xyz")]
    public class xyzLookup : RowLookupScript<xyzRow>
    {
        public xyzLookup()
        {
            IdField = xyzRow.Fields.xyzId.PropertyName;
            TextField = xyzRow.Fields.xyzText.PropertyName;
        }
    }
}`

**Comment by volkanceylan** [comment]
Your text field cannot be a NTEXT field, use NVARCHAR(MAX) or use an expression field that casts to nvarchar(max)

**Comment by awesomegithubusername** [comment]
That's what I ended up doing. Thanks, man
