### ISSUE TITLE
SSPI

### ISSUE THREAD

**Issue by MohamedEbrahimSaad** [volkanceylan/Serenity#5235]
Cannot Generate SSPI Context  when initiating connection to online sql server with user id and password when oppenning sergen and selecting the database this errors appers is this a serenity problem or a sql server problem ?
![384a4120-1dd7-4a4f-845f-6b35e903e444](https://user-images.githubusercontent.com/10961851/94873427-6ea27480-044f-11eb-841b-6e6fc511bd9b.jpg)

i tried to take backup from the online database and make it local and then generate the sergen files then changed the connection again to the online server and this what i get note that i used same connection name
![qqq](https://user-images.githubusercontent.com/10961851/94873600-ebcde980-044f-11eb-87a7-9553c445b400.jpg)

**Comment by VictorTomaili** [comment]
It's not related serenity. Check error message on google. Cause I guess your windows account doesn't have permission or AD password is expired.

**Comment by VictorTomaili** [comment]
Closed due inactivity
