### ISSUE TITLE
Totals in Grouping Header

### ISSUE THREAD

**Issue by lechu90ns** [volkanceylan/Serenity#5236]
Hey Guys!

After updating Serenity libraries from 3.12.3 to 3.14.1 I got issues with retrieving totals inside a formatter of a grouped info (Slick.GroupInfo object).

Aggregators are set on two columns "RowCount" and "Weight"
`protected createSlickGrid() {
            let grid = super.createSlickGrid();

            grid.registerPlugin(new Slick.Data.GroupItemMetadataProvider());
            
            this.view.setSummaryOptions({
                aggregators: [
                    new Slick.Aggregators.Sum(String(fld.RowCount)),
                    new Slick.Aggregators.Sum(String(fld.Weight))
                ]
            });

            return grid;
        }`

After an update the x.totals property is null, where on 3.12.3 it was filled with values, so I could display totals in the grouping header instead of as a new line footer.
`let groupByRow = <Slick.GroupInfo<PackagedDataRow>>{
                    formatter: x => {
                        console.log(x, x.totals);`

I use this code to get a SUM of grouped records
`x.totals.sum[fieldName]`

Is that a bug or I have to set anything more? Thanks!

**Comment by lechu90ns** [comment]
It seems that setting aggregators property as null fixed the issue.


`let groupByRow = <Slick.GroupInfo<PackagedDataRow>>{
                    formatter: x => {
                        console.log(x, x.totals); // x.totals is now having values!

                        var output = '<span class="slick-group-title-header">' + Q.text(this.getLocalTextDbPrefix() + iFldName) + ' ' + x.value + '</span>';
                        if (x.totals) {
                            if (x.totals.sum) {
//REMOVED BODY
                            }
                        }
                        return output;
                    },
                    aggregators: null
                };`

**Comment by reach2rv** [comment]
@lechu90ns  Can you please share the full code, Or can guide where to put this 

```
let groupByRow = <Slick.GroupInfo<PackagedDataRow>>{
                    formatter: x => {
                        console.log(x, x.totals); // x.totals is now having values!

                        var output = '<span class="slick-group-title-header">' + Q.text(this.getLocalTextDbPrefix() + iFldName) + ' ' + x.value + '</span>';
                        if (x.totals) {
                            if (x.totals.sum) {
//REMOVED BODY
                            }
                        }
                        return output;
                    },
                    aggregators: null
                };
```

**Comment by lechu90ns** [comment]
I assume, that you want to test it anyway? Sure, the context of it is that I want to put totals in the grouped header of a SlickGrid instead of creating a new grid line for the footer.

Init code:
```
protected createSlickGrid() {
	let grid = super.createSlickGrid();

	// need to register this plugin for grouping or you'll have errors
	grid.registerPlugin(new Slick.Data.GroupItemMetadataProvider());
	
	this.view.setSummaryOptions({
		aggregators: [
			new Slick.Aggregators.Sum(String(fld.RowCount)),
			new Slick.Aggregators.Sum(String(fld.Weight))
		]
	});

	return grid;
}
```

SlickGrid (that works now), you can see two grouped headers with displayed totals. Without aggregators: null in a grouping setting, it doesn't work.

![image](https://user-images.githubusercontent.com/19293837/95719437-14d05480-0c70-11eb-880d-53a6dc14544c.png)


```
let list = [] as Slick.GroupInfo<PackagedDataRow>[];

for (let i = 0; i < this.groupByList.length; i++) {
	const iFldName = this.groupByList[i];
	let groupByRow = <Slick.GroupInfo<PackagedDataRow>>{
		formatter: x => {
			var output = '<span class="slick-group-title-header">' + Q.text(this.getLocalTextDbPrefix() + iFldName) + ' ' + x.value + '</span>';
			if (x.totals) {
				if (x.totals.sum) {
					let getSumTotal: (fldName: string) => void = (fldName: string) => 
						(Math.round(Q.coalesce(x.totals.sum[fldName], 0) * 100) / 100);

					output += '<span style=\'position:absolute;left:' + (x.level * 5) + 'px;\' >';

					var rowIndexColumn = Q.indexOf(this.getSortedColumns(), x => x.id === String(fld.RowCount));

					if (rowIndexColumn >= 0) {
						output += '<span class=\'slick-header-text l' + rowIndexColumn + '\' ' +
							'title=\'' + Q.text(this.getLocalTextDbPrefix() + String(fld.RowCount)) + ': ' + getSumTotal(String(fld.RowCount)) + '\'>' +
							'(' + getSumTotal(String(fld.RowCount)) + ' ' + Q.dbText('Reports')('Qty') + ')' +
							'</span>';
					}

					var weightIndexColumn = Q.indexOf(this.getSortedColumns(), x => x.id === String(fld.Weight));

					if (weightIndexColumn >= 0) {
						output += '<span class=\'slick-header-text l' + weightIndexColumn + '\' ' +
							'title=\'' + Q.text(this.getLocalTextDbPrefix() + String(fld.Weight)) + ': ' + getSumTotal(String(fld.Weight)) + '\'>' +
							'(' + getSumTotal(String(fld.Weight)) + ' ' + Q.dbText('Reports')('Kg') + ')' +
							'</span>';
					}

					output += '</span>';
				}
			}

			return output;
		},
		getter: item => {
			if (iFldName === String(fld.CreateDate)) {
				return Q.formatDate(Q.parseISODateTime(item[iFldName]), 'yyyy-MM-dd');
			}

			return item[iFldName];
		},
		aggregators: null,
		displayTotalsRow: false,
		//aggregateCollapsed: i === 0,
		lazyTotalsCalculation: false
	};

	list.push(groupByRow);
}

```

Thanks
