### ISSUE TITLE
Creating new .Net Core project Issue in Visual Studio

### ISSUE THREAD

**Issue by vajlo** [volkanceylan/Serenity#5239]
Hello
after creating new project (.NET Core) in Visual studio solution shows errors:
The type or namespace name 'Repositories' could not be found
The type or namespace name 'Entities' could not be found
in *Endpoint.cs and *Repository.cs files

Visual studio Serene Extension version is 3.14.0.0
Visual studio Version

**Comment by JohnRanger** [comment]
@vajlo ,
have you tried to do a dotnet restore, followed by a dotnet sergen restore?

With kind regards,

John

**Comment by vajlo** [comment]
@JohnRanger,

yes i tried it.
The problem is that in previous version it looked like this

```
namespace Serene1.Administration.Repositories
{
    using Serenity.Data;
    using Serenity.Services;
    using System.Data;
    using MyRow = Entities.LanguageRow;

    public class LanguageRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }
        ......
    }
}
```
and now it looks like this
```
using Serenity.Data;
using Serenity.Services;
using System.Data;
using MyRow = Entities.LanguageRow;

namespace Serene1.Administration.Repositories
{
    public class LanguageRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }
        ....
    }
}
```
The  Entities.LanguageRow is out of namespace now, so it should look like this Serene1.Administration.Entities.LanguageRow

But the problem is that using moved from namespace over namespace as it is used in C # and then I need the whole path

When I tried it a few days (maybe a month) ago, it was okay (I don't know what version of the SERENE addon I had). And when I finally decided to migrate my Serenity project from ASP.NET MVC to .NET Core. So I ran into such a problem. Which can be easily solved even after generating a new Serenity .Net Core project

Creating a new project using SERIN is fine.

I'm not good in English, so I won't write a perfect explanation :(

With kind regards,
Vajlo

**Comment by VictorTomaili** [comment]
I didn't see an issue like this on core version of code generator. We actively use it without any problem. If you still have issue you can try create new project and transfer your modules on there. 

Except we need more detailed issue case for reproduce it and fix it.

**Comment by muhammedyaman** [comment]
I found the solution [here](https://stackoverflow.com/a/66759485) thanks for pointing the using directives @vajlo you enlightened me. :)
If anyone encounters same problem this is not an error. Its just a visual studio preference.
