### ISSUE TITLE
Filterable grid not getting yesNoEditor for boolean fields.

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#524]
I am trying to implement the filterable feature on my grid like the products example in the Northwind DB. But my Boolean field keeps giving me a lookUpEdotor with out any boolean values. Please help

![image](https://cloud.githubusercontent.com/assets/17201265/14324478/8d286cb0-fbea-11e5-8df6-979cc2f4e545.png)

**Comment by volkanceylan** [comment]
Is this boolean field BooleanField or Int16Field etc?

**Comment by swordz36** [comment]
Nullable Boolean
![image](https://cloud.githubusercontent.com/assets/17201265/14328136/0b3b3d20-fbfb-11e5-9d25-be5ab7787c78.png)

**Comment by swordz36** [comment]
![image](https://cloud.githubusercontent.com/assets/17201265/14328192/4197116e-fbfb-11e5-994e-b7258e73e14b.png)

**Comment by volkanceylan** [comment]
Why did you put LookupFiltering on it? You should use BooleanFiltering.

**Comment by swordz36** [comment]
Thanks
