### ISSUE TITLE
ts file generation for Custom c# Class

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5241]
@volkanceylan Is there a way to transform Custom C# class to ts?

**Comment by VictorTomaili** [comment]
Try to use ScriptInclude attribute on class.

**Comment by fwd079** [comment]
Doesn't work, @VictorTomaili

**Comment by VictorTomaili** [comment]
Please ask your question on Discussions section. Write what you tried, how you tried etc. Don't do comment on old issues.
