### ISSUE TITLE
 The combos do not work in the detail, a help please.

### ISSUE THREAD

**Issue by patriciomh1965** [volkanceylan/Serenity#5242]
I have a parent table with data, then on the next page I display the children. I use filters called combos, which don't work for me. I'm going to show the following classes and image:
![problem](https://user-images.githubusercontent.com/42218266/95408439-cb8da700-08f5-11eb-8643-cdc7bbcbdea6.png)

The parent class
==========
MonitorArchivosRow.cs 
.......
---
  //  VINCULACION LINEAS
        [DisplayName(""), MasterDetailRelation(foreignKey: "det_proc_numero",  MasterKeyField = "proc_numero", IncludeColumns = "DetailList21"), NotMapped]
        public List<MonitorArchivosLineasRow> DetailList2
        {
            get { return Fields.DetailList2[this]; }
            set { Fields.DetailList2[this] = value; }
        }
.......
.......
       public RowListField<MonitorArchivosLineasRow> DetailList2; 
.......
.......

MonitorArchivosForm.cs
.....
......
        [Category("Lineas del Archivo")]
        [MonitorArchivosLineasEditor]
        public List<Entities.MonitorArchivosLineasRow> DetailList2 { get; set; } 
.....
....

The child class
=========
XYZColumns

namespace SegurosMAPC.BaseDatos.Columns
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;
    using SegurosMAPC.Modules.BaseDatos.Lookups;
    using SegurosMAPC.Modules.BaseDatos;

    [ColumnsScript("BaseDatos.MonitorArchivosLineas")]
    [BasedOnRow(typeof(Entities.MonitorArchivosLineasRow), CheckNames = true)]
    public class MonitorArchivosLineasColumns
    {
        [EditLink]
        [SortOrder(1, descending: true)]
        [Width(100)]
        public Int32 NumLinea { get; set; }
        [Width(100)]       
        public Int32 NroContrato { get; set; }
        [Width(150)]
        public DateTime FechaSuscripcionContrato { get; set; }
        [Width(300)]
        **[QuickFilter(CssClass = "hidden-xs")]**
        public String EveDescripcion { get; set; } // nombre evento
        [Width(130)]       
        public Int32 CodMaterial { get; set; }
        [Width(120)]
        public String CodCobertura { get; set; }
        [Width(250)]
        **[QuickFilter(CssClass = "hidden-xs")]**
        public String TseDescripcion { get; set; } // tipo seguro
        [Width(100)]
        public Int32 DatosLibresDeducible { get; set; }       
        **[Width(400), QuickFilter(CssClass = "hidden-xs")]**
        public String Descripcion { get; set; } // nombre estado carga
}

I appreciate any help. Thank you

**Comment by VictorTomaili** [comment]
Closed because it's does not meet the issue [requirements](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines). 
If you still need help, you can ask this on stackoverflow.
https://stackoverflow.com/tags/serenity-platform

**Comment by teafmartins** [comment]
@patriciomh1965 , did you find any solution?

**Comment by VictorTomaili** [comment]
Please open new discussion for your question. Old issues are not suitable for this. Thank you for understand.
