### ISSUE TITLE
Accessing Service from other repo from backend .cs file

### ISSUE THREAD

**Issue by djhonb** [volkanceylan/Serenity#5243]
If I want to access another rows repository functionality from the backend, it's obvious that I can call another repository within one repository
 
```
like var orepo = new OrdersRepository(); 
orepo.List();
```
If I want to access the same through service endpoint rather than directly accessing through a repo, is there any wrapper available like the one available in frontend (ts).?

The objective here is I don't want access certain repo within certain repo(isolation of functionalities) rather access through service only..and each will be deployed as a separate service.

to start with whats the easiest way to access service within repo?

Thanks

**Comment by VictorTomaili** [comment]
Closed because it's does not meet the issue requirements. 
If you still need help, you can ask this on stackoverflow.
https://stackoverflow.com/tags/serenity-platform
