### ISSUE TITLE
Update/Change Interface Editor

### ISSUE THREAD

**Issue by alex-444** [volkanceylan/Serenity#5246]
Hi All,
   This is not an issue in Serenity, i just had a requirements that is not very standard and i already search for a sample
but i do not see any. My problem is how can i update/change the Text Editor to ImageUploadEditor / Number Editor
once i open a Dialog. The data type is all Varchar in database but i need to update the interface based on what is setup/insert 
in the table. Is this available in StartSharp?

see screenshot.. the encoder need to supply the ParamValue

![image](https://user-images.githubusercontent.com/22849322/95707416-11e35d00-0c8c-11eb-893f-b47e0dd407ad.png)

TIA!

**Comment by VictorTomaili** [comment]
We don't have a sample for this in startsharp. But some of our customers requested similar workflow from us already and this codes are private. You need to handle it in `dialog.ts` yourself.

**Comment by muhammedyaman** [comment]
Hi @alex-444 did you achieve this? I am trying to do this but cant. I tried this: 
```
switch (this.form.AnswerType.value) {
                case 'boolean': {
                    debugger;
                    var val = JSON.parse(this.form.Answer.value).value;
                    var edt = new _Ext.BooleanSwitchEditor($(".Answer"), {});
                    edt.value = val;
                }
                default:
                    ""
            }
```
This only adds s-BooleanSwitchEditor class to input element.
