### ISSUE TITLE
error in LinkingSetRelation 

### ISSUE THREAD

**Issue by teafmartins** [volkanceylan/Serenity#5248]
Hello,

I have the following error when I try to save a form with linkingsetrelation field:

Invalid cast exception while trying to set the value of ProductId field on ProductRow as object.

What can cause this error? any idea?
Thx

**Comment by VictorTomaili** [comment]
Can you close this issue and post a question to stackoverflow instead of serenity issues?

All of "How do I?" and "I got this error, why?" questions can be posted on stackoverflow with "serenity-platform" tag. https://stackoverflow.com/tags/serenity-platform

**Comment by teafmartins** [comment]
sure, thx anyway
