### ISSUE TITLE
an inaccessible field in ts file with jquery

### ISSUE THREAD

**Issue by amirkian** [volkanceylan/Serenity#5249]
I have an EditDialog file that named CommissionEditDialog
it includes a filed CommissionMembers_CommissionId that is a grid table

but when I in CommissionEditDialog.ts try to read CommissionMembers_CommissionId  by jquery it is unknown. I don't know why

`
            jQuery("div.category").on('DOMSubtreeModified', ".CommissionMembers_CommissionId", function () {

                

                console.log('CommissionMembers_CommissionId:', this.CommissionMembers_CommissionId);

            });`
I think because this refer to jquery here not to parent class.

**Comment by VictorTomaili** [comment]
Hello @amirkian,
Can you post this question to stackoverflow instead issues?

https://stackoverflow.com/tags/serenity-platform
