### ISSUE TITLE
wkhtmltopdf dependency

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#525]
wkhtmltopdf.exe is a dependency for generating PDF reports; please consider adding wkhtmltopdf.msvc.exe NuGet package to the Serene template and update HtmlToPdfConverter() to use it. Thanks!

**Comment by volkanceylan** [comment]
I dont think its a good idea. It will add 20mb more. Also licence terms might cause problems.

**Comment by volkanceylan** [comment]
Serene is already 30mb, i think its too big for a template. This is due to nuget packages and nodejs inside. I actually want to find a way to download this nuget packs on project creation but VS fails on node and some others.
