### ISSUE TITLE
[3.14.1-3.14.2] Oracle Invalid Character (ORA-00911)

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#5251]
Hey there, i have just switched to 3.14.2 and now getting an Oracle Error on List() Endpoint of every modules.

I have changed Nothing else only updated the nugets.

**Comment by VictorTomaili** [comment]
From which version do you upgrade?

**Comment by kilroyFR** [comment]
from 3.14.1

**Comment by kilroyFR** [comment]
on the generated query i have an extra code :

---SELECT count(*)  FROM TOL_REQUEST_LOG T0 

that causes the error

**Comment by kilroyFR** [comment]
full query : 

"SELECT * FROM (\nSELECT \nT0.REQUEST_LOG_ID AS \"REQUESTLOGID\",\nT0.EVT_DATE AS \"EVTDATE\",\nT0.REQUEST_TYPE AS \"REQUESTTYPE\",\nT0.REQUEST_ID AS \"REQUESTID\",\nT0.RECEIVED_DATE AS \"RECEIVEDDATE\",\nT0.EVT_TYPE AS \"EVTTYPE\",\nTO_CHAR(CONTENT) AS \"CONTENT\",\nT0.STATUS AS \"STATUS\", ROW_NUMBER() OVER (ORDER BY T0.REQUEST_LOG_ID DESC) AS __rownum__ \nFROM TOL_REQUEST_LOG T0 \nORDER BY T0.REQUEST_LOG_ID DESC) WHERE __rownum__ > 0 AND ROWNUM <= 100\n---\nSELECT count(*)  \nFROM TOL_REQUEST_LOG T0"

**Comment by kilroyFR** [comment]
The issue comes from the __rownum__' alias. It is not accepted as valid name with Oracle.

rownum_ => works
__rownum__ => does not work

**Comment by kilroyFR** [comment]
It works double quoting the alias "__rownum__" => works

**Comment by kilroyFR** [comment]
![Sans titre](https://user-images.githubusercontent.com/31513956/96501985-759ff400-1251-11eb-8d32-4204a32149e4.png)
=> works

Without the double quote it's an error for Oracle.

**Comment by kilroyFR** [comment]
![Sans titre](https://user-images.githubusercontent.com/31513956/96506314-b569da00-1257-11eb-8dfe-45ca992a74fa.png)

It's working this way.
If you could take it into account ?

My previous version was Serenity 3.14.0 (and there was no such `__rownum__` alias) that explains why it worked.

**Comment by VictorTomaili** [comment]
Fixed 24d312990857e4fb2364a34937cd4c877148a87a
you can update serenity to  3.14.3
