### ISSUE TITLE
Auto populate Customer Id field before save

### ISSUE THREAD

**Issue by nfulgen** [volkanceylan/Serenity#5252]
I have this scenario. I want to auto populate customer id field before save. It will contain 3 letter prefix "CUS" + auto increment number which will be the max Id from customer table + 1. Any idea how i can implement this?

Thank you in advance

**Comment by VictorTomaili** [comment]
Hi @nfulgen 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
