### ISSUE TITLE
How to hide a field and its display name

### ISSUE THREAD

**Issue by nfulgen** [volkanceylan/Serenity#5253]
Hi,

I have a logic on my AbcDialog.cs file which hides a field based on a ceratin condition. This code "this.form.SomeField.element.hide()" hides a field but it doesn't hide the field's display name. Any idea how can I hide a field and its display name?

**Comment by VictorTomaili** [comment]
Hi @nfulgen 
Same as previous issue. Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
