### ISSUE TITLE
Make field required/not required based on condition

### ISSUE THREAD

**Issue by nfulgen** [volkanceylan/Serenity#5254]
Hi,

I want to make the field required/not required based on a condition. Any idea please

**Comment by VictorTomaili** [comment]
Hi @nfulgen 
Same as previous issue. Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
