### ISSUE TITLE
Filter pop up screen didnn't force the server side code to be executed to get the result

### ISSUE THREAD

**Issue by amrgDev** [volkanceylan/Serenity#5255]
I created dynamic grid like [https://serenity.is/demo/AdvancedSamples/DataExplorer](url)
and I added filter to this dynamic grid at runtime but when select the criteria from the pop up filter screen
the filter does not applied on the grid and the service function "List" did not called.
I want to force the filter pop up screen to call the "List Function"

please advise.

**Comment by VictorTomaili** [comment]
Hi @amrgDev 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
