### ISSUE TITLE
MultiTenant with separate Databases.

### ISSUE THREAD

**Issue by desconfiado** [volkanceylan/Serenity#5261]
Hi.

I want to make a multi-tenant web aap with serenity. I made an app and i added a field to the user database in order to define the name of the Database assigned to that user. This was very easy to do but now i need to change the connection string when user logs in so that the user, or users, work with the assigned Database. How do i do that?

**Comment by JohnRanger** [comment]
Please see this wiki entry. This is for multi-database. 

https://github.com/volkanceylan/Serenity/wiki/Database:-Multi-Database-Serenity

With kind regards,

John

**Comment by desconfiado** [comment]
Thank you very much. 
I didn't found that article.
What i want is to open the database define for each usar, without the chance to choose, but for what saw this solves my problem.

Oncet again, thank you.
