### ISSUE TITLE
Sort LookupScript items (not based on label)

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#5262]
hey all, i am requesting an help on basic feature.

On my xxxRow.cs i have set the SortOrder() on the required columns => i know it applies ONLY to Columns => OK

I have set a :   [LookupScript("Factory.RomTariffMethod")] on top of my xxxRow.cs.

When i use the lookup script in another screen like this :     [EditLink(ItemType = "Factory.RomTariffMethod")]
=> then the drop down displays items but sorting alphabetically (on the label).

My request : I would like to set the display order on drop down using another internal field (id).

How is it possible to do this ? Do i really need to make it Client Side ?

**Comment by VictorTomaili** [comment]
Hi @kilroyFR 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

**Comment by kilroyFR** [comment]
> Hi @kilroyFR
> Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?
> 
> Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

Sorry i am gonna post this question on StartSharp side
