### ISSUE TITLE
Form new Entity Default Values from DB.

### ISSUE THREAD

**Issue by desconfiado** [volkanceylan/Serenity#5263]
Hi.

I am new to serenity and i am enjoying very much but the learning curve and some rigidity is killing me.
I am trying to fill the default values in the form when adding new entity but can't get there.

I tried using this:

```
export class DefaultValuesInNewGrid extends UtentesGrid {

        constructor(container: JQuery) {
            super(container);
        }

        /**
         * This method is called when New Item button is clicked.
         * By default, it calls EditItem with an empty entity.
         * This is a good place to fill in default values for New Item button.
         */
        protected getNewEntity() {
            //myUts = UtentesRow.getLookup;
            //.Items.Where(x => x.JobTypeId == form.JobTypeId.Value.ToInt32());
            this.editItem(<IpssDB.UtentesRow>{
                Codigo: 5.

                //RequiredDate: Q.formatDate(new Date(), 'yyyy-MM-dd'),
                //EmployeeID: Northwind.EmployeeRow.getLookup().items
                //    .filter(x => x.FullName === 'Robert King')[0].EmployeeID,
                //ShipVia: Northwind.ShipperRow.getLookup().items
                //    .filter(x => x.CompanyName === 'Speedy Express')[0].ShipperID
            });
            return this;
        }
    }
```

But even this doesn't work.

I would like to set the default Enttty code to the max value on the database where the place (this is a field in a filter on the grid or a field in the user table). How can i do this?

**Comment by JohnRanger** [comment]
Hi @desconfiado ,

please have a look at the demo: https://serenity.is/demo/BasicSamples/DefaultValuesInNewDialog

With kind regards,

John

**Comment by VictorTomaili** [comment]
Hi @desconfiado 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

**Comment by desconfiado** [comment]
Ok. Sorry.

 

De: Victor Tomaili <notifications@github.com> 
Enviada: 26 de outubro de 2020 19:07
Para: volkanceylan/Serenity <Serenity@noreply.github.com>
Cc: desconfiado <desconfiado@mail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [volkanceylan/Serenity] Form new Entity Default Values from DB. (#5263)

 

Hi @desconfiado <https://github.com/desconfiado> 
Can you post this question to stackoverflow  <https://stackoverflow.com/tags/serenity-platform> instead issues?

Also check the issue guidelines <https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines> .
