### ISSUE TITLE
validate field at run time on field change

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#5265]
I need to know if the phone to register already exists in the bank before clicking Save or Update.
I need to check this restriction when changing the field.
In other words, when leaving the Celular field, if it exists in the bank, it will already notify me.

![image](https://user-images.githubusercontent.com/7516443/97352854-f2def080-1871-11eb-8f3b-aef98d91a432.png)

**Comment by kilroyFR** [comment]
Something like :

      this.form.myfield.change(e => {
        … Do whatever control
        }

**Comment by JohnRanger** [comment]
@juliermefelix , write an endpoint (in xyzEndpoint.cs) which takes the cellular phone number as an input and queries the database for it - and then returns true or false according if it has been found or not. And then take action on the client side.

If you don't know how to send a value from client-side to server, do something with it on server-side and then return something from server-side to  client-side, please have a look at the following wiki entry: https://github.com/volkanceylan/Serenity/wiki/BBB:-On-client-side,-fetching-a-value-from-server-side-out-of-database

Hope this helps to give you the basic idea.

Regards,

John

**Comment by VictorTomaili** [comment]
Hi @juliermefelix 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

**Comment by juliermefelix** [comment]
@JohnRanger 
Dear Jhon
Thanks for the answer.
I tried to do this at the endpoint
`public ServiceResponse ValidateUniqueConstraint(IDbConnection connection, UniqueConstraintRequest request)
        {
            
            bool IsValid = !connection.Exists<Entities.PessoaRow>(MyRow.Fields.Celular == request.Celular );
            if (!IsValid)
            {
                throw new ValidationError("Celular já cadastrado.");
            }
            return new ServiceResponse();
        }

        public class UniqueConstraintRequest : ServiceRequest
        {
            
            public string Celular { get; set; }
        }`

and I did that in the dialog
` this.form.Celular.change(
                e => {
                    
                    PessoaService.ValidateUniqueConstraint({
                        Celular: this.form.Celular.value
                    }, response => { });

                })
`

but this is giving stack error

if you can help me i thank you.

**Comment by edwardch** [comment]
Hey @juliermefelix, did you take a look at this example #4625 ?

I see in your endpoint you're throwing a validation error, which might not be great from a UX perspective. It might be better to return a message or boolean value, and handle that in your TypeScript code (see my example link above).

Hope that helps?
