### ISSUE TITLE
Conceptional bug?; culture/locale depends on selected language, not system locale

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#5266]
Hi all,

I was trying to find out why I always get datetime values displayed like this: MM/dd/yyyy in the dialogs/forms even when my computer (from where I browse to the SF project) is set to Switzerland locale which has the following datetime format: dd.MM.yyyy.

While trying to find out the problem, I discovered that Serenity is using the selected language to change locale.

In my example, I was using the english language. When I changed it to german, the date format changed to the desired format of dd.MM.yyyy.

**In my opinion, this is conceptionally wrong.**

An example: Switzerland has 4 official languages (german, french, italian and rumantsch - and we often use english within applications).

But the locale must not change depending on the selected language - it is still Swiss locale whose date format is dd.MM.yyyy.

So Serenity should read the locale from the browser and use this for formatting datetime fields within dialogs - independent of the selected app language.

Any chance that this behavior could be corrected? :-)

With kind regards,

John

**Comment by volkanceylan** [comment]
See DetermineProviderCultureResult method UserCultureProvider.cs:

```cs
return Task.FromResult(new ProviderCultureResult(culture ?? "en-US", culture ?? "en-US"));
```

The first one is current culture (formats) while second one is ui culture (texts). It determines the "culture" based on language selected. The culture information sent by the browser is often not enough to determine corresponding .NET Culture. Plus, not everybody is aware of the system / browser culture like you assume. Most expect that when they change the language, they expect the culture to match the language. There is a TwoLetterToFourLetter dictionary there for that purpose. Browser or the language key is just "en", in that case it looks up from that dictionary to match it to a four letter culture, which is "en-US". In case of german, "de" is matched to "de-DE" as it does not have another match in the dictionary.

If you can find the perfect algorithm, which can please all kind of users, please share your completed work with a pull request.
