### ISSUE TITLE
Broken link in documentation for Two Level Cache

### ISSUE THREAD

**Issue by g-massone** [volkanceylan/Serenity#5267]
Hello volkanceylan,
just wanted to report that the following link is currently broken:

https://serenity.is/Docs/caching/two_level_cache

It can be accessed from: https://serenity.is/docs/caching/README

Thank you,
Regards

**Comment by thesnide1** [comment]
The "search topics" in the Serenity Guide is broken also. 

This serenity.is page can’t be found
No webpage was found for the web address: https://serenity.is/docs/search?q=serenity
HTTP ERROR 404

**Comment by volkanceylan** [comment]
Thanks, fixed the link and search. We recently moved serenity.is itself to Linux / .NET Core so such issues are possible during migration.
