### ISSUE TITLE
Default form values problem with key field.

### ISSUE THREAD

**Issue by desconfiado** [volkanceylan/Serenity#5268]
Hi. I am sorry to be posting this here but i can't seem to get an answer anywhere else.

I have a customer table in wich the key field, Number, must fall between a range of values according to the customer loaction. For instance, if customer is from Portugal the number must be between 0 and 10000 but if is from spain then it must be between 10000 and 20000.
I have this code, that i managed to code from the northwind sample 'GetNextNumber' and it works. The problem is that the field being changed is the key field of the table. Because of this, i suppose, the dialog form to edit the new record assumes that it is an existing record and not a new one.
How can i overcome this?
This is my code:

The helper
```
public static GetUtenteNextNumberResponse GetUtenteNextNumber(IDbConnection connection, GetUtenteNextNumberRequest request)
        {
            
            var min = connection.Query<string>(new SqlQuery()
                .From("Locais")
                .Select("UtenteCodMin")
                .Where("Codigo = " + request.Local))
                .FirstOrDefault();

            var minN = (string.IsNullOrEmpty(min) ? 0 : int.Parse(min));

            var minCod = connection.Query<string>(new SqlQuery()
                .From("Utentes")
                .Select("Codigo")
                .Where("Codigo >= " + minN ))
                .FirstOrDefault();

            var response = new GetUtenteNextNumberResponse();

            var n = 0;
            response.Number = minCod == null ||
                !int.TryParse(minCod, out n) ? minN + 1 : n + 1;

            return response;
        }

```

and the UtentesGrid.ts

```
protected addButtonClick() {
            var eq = this.view.params.EqualityFilter;
            var local = 0
            local = eq ? eq.Local : 0;
            var ultCod = 0;

            IPSS.IpssDB.UtentesService.GetUtenteNextNumber({
                Local: local,
                User: '' 
            }, response => {
                    this.editItem(<IpssDB.UtentesRow>{
                        Codigo: response.Number,
                        Local: eq ? eq.Local : null
                    });
            });        }

```

**Comment by VictorTomaili** [comment]
Hi @desconfiado 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
