### ISSUE TITLE
Serenity skin

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#5269]
Hey all, I have to say I like Serenity's UI because it is simple, clean and very good UX, definitely, but I also trust that 9/10 people will say that the UI is quite "old" like 1990s. I work and look it everyday, honestly default skins are quite boring at this time for me. Long time we don't have new skin, although I'm not good at designing but I also tried to create new one. I have just created the skin some days ago, I will be happy if everyone can contribute to complete it, and make it more beatiful.

In future if it is good enough I hope we can merge it into Serenity's main  repository, but right now I think it's better if I create new repository so everyone can contribute it easier and avoid bother Vokan also his team. But everyone will be happy if Vokan and his team can give some ideas and also sharing their experience!

Here is repository: https://github.com/minhhungit/SerenitySkins/

Thanks all !

---

And here are some demo images (not completed yet)

![1](https://user-images.githubusercontent.com/2279508/97650503-678d7700-1a8c-11eb-827a-570bded3a924.png)
![2](https://user-images.githubusercontent.com/2279508/97650507-69573a80-1a8c-11eb-9225-e9b058191609.png)
![3](https://user-images.githubusercontent.com/2279508/97650509-69efd100-1a8c-11eb-8cba-214e34fe89fc.png)
![4](https://user-images.githubusercontent.com/2279508/97650511-6a886780-1a8c-11eb-946d-ac9c3dc69f16.png)
![5](https://user-images.githubusercontent.com/2279508/97650514-6b20fe00-1a8c-11eb-8f30-5545a22c5565.png)
![6](https://user-images.githubusercontent.com/2279508/97650515-6b20fe00-1a8c-11eb-884f-7ecf9bb344b1.png)
![7](https://user-images.githubusercontent.com/2279508/97650517-6bb99480-1a8c-11eb-9f5c-ccc58f7f533a.png)
![8](https://user-images.githubusercontent.com/2279508/97650518-6c522b00-1a8c-11eb-87ba-693772dbc70a.png)

**Comment by JohnRanger** [comment]
Hi @minhhungit ,

looks really nice.

Thanks for your work and sharing here.

Regards,

John

**Comment by minhhungit** [comment]
work in progress: **Glass skin**

![image](https://user-images.githubusercontent.com/2279508/98487685-f94c6f80-2256-11eb-9a35-9f8376334f0b.png)

**Comment by minhhungit** [comment]
Demo glass theme (WIP)
https://media.giphy.com/media/uYNgiAMahwNHG4VGnW/source.gif

![](https://media.giphy.com/media/uYNgiAMahwNHG4VGnW/source.gif)

**Comment by minhhungit** [comment]
Hi all,
I public those skins here https://github.com/minhhungit/SerenitySkins/

There are **21** skins right now, 18 dark skins and 3 light skins

Please fork, review, at this time I just support Serene version

**Comment by VictorTomaili** [comment]
@minhhungit thanks for your work. But as you know, this is not an serenity issue. So can we close this issue?

**Comment by minhhungit** [comment]
Sure @VictorTomaili  :)
