### ISSUE TITLE
Custom guid

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#527]
Where is the assignment,Do not have to manually assign each time
public static Guid SequentialGuid()
        {
            var tempGuid = Guid.NewGuid();
            var bytes = tempGuid.ToByteArray();
            var time = DateTime.Now;
            bytes[3] = (byte)time.Year;
            bytes[2] = (byte)time.Month;
            bytes[1] = (byte)time.Day;
            bytes[0] = (byte)time.Hour;
            bytes[5] = (byte)time.Minute;
            bytes[4] = (byte)time.Second;
            return new Guid(bytes);
        }

**Comment by 107295472** [comment]
DefaultValue(typeof(Guid),Yin.Common.Utils.SequentialGuid())

**Comment by volkanceylan** [comment]
Make your guids generate in sql with newid() or override SetInternalFields
