### ISSUE TITLE
Hide PDF Icon

### ISSUE THREAD

**Issue by saiprasadchinna** [volkanceylan/Serenity#5271]
Hi Team,

I want to hide/disable pdf icon based on survey name. Please provide suggestions where i have to write the logic?

@volkankalkan @Serenis @VictorTomaili 

![Github_censored](https://user-images.githubusercontent.com/17807790/97855591-f6b2bd00-1d20-11eb-87a9-fca88a5dba49.jpg)

**Comment by VictorTomaili** [comment]
Hi @saiprasadchinna 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

Tip: check slick grid formatter for columns in serene sample files.
