### ISSUE TITLE
Added a grid to a dialog, but it doesn't resize.

### ISSUE THREAD

**Issue by mgbadia** [volkanceylan/Serenity#5272]
I have used the code below. Not sure what to write in the event handler for dialog resize. I added the s-DialogContent class to the div. The grid is an entity grid I automatically generated with sergen.
Thanks!

namespace ManagedCareHub.Default {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.resizable()
    @Serenity.Decorators.maximizable()
    export class HccSearchDialog extends Serenity.TemplatedDialog<any> {
        private hcc: string;
        private grid: Hcc2020Icd10Grid;
       
        constructor(hcc: string) {
            super();
            this.hcc = hcc;
        }
        protected onDialogOpen() {
            super.onDialogOpen();
            var ref = '#' + this.idPrefix + 'HCC_SearchGrid';
            //var ref = '#' + this.idPrefix
            this.grid = new Hcc2020Icd10Grid($(ref), this.hcc);
            this.grid.init();
            // this.element.bind("dialogresize", () => {  });
        }

        protected getTemplate() {
            return "<div id='~_HCC_SearchGrid' class='s-DialogContent'></div>";
        }

        protected getDialogOptions() {
            var opt = super.getDialogOptions();
            opt.title = 'Search HCC';
            return opt;
        }
    }
}

**Comment by VictorTomaili** [comment]
Hi @mgbadia 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

Tip: Hcc2020Icd10Grid.element.triggerHandler("layout");
