### ISSUE TITLE
How to use enter key like tab?

### ISSUE THREAD

**Issue by mbchandak** [volkanceylan/Serenity#5273]
Hi,

How to use enter key in one control to another control jump like tab key.

**Comment by VictorTomaili** [comment]
Hi @mbchandak 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
