### ISSUE TITLE
Kestrel; "launchUrl" within launchSettings.json should be "applicationUrl"

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#5274]
By default, a freshly deployed 3.14.3 Serene project has "launchUrl" within the Kestrel section of launchSettings.json.

When changing the URL part within "launchUrl", only the browser changes its port but the Kestrel webserver does not.

**Before:**
![image](https://user-images.githubusercontent.com/2699447/98159534-0e36a500-1edd-11eb-9534-cfa481c91984.png)

Replacing "launchUrl" with "applicationUrl" solves this problem.

**After:**
![image](https://user-images.githubusercontent.com/2699447/98158033-99626b80-1eda-11eb-8e31-e6d4672444f1.png)

With kind regards,

John

**Comment by volkanceylan** [comment]
@VictorTomaili can you please check if that's the case?

**Comment by VictorTomaili** [comment]
launchUrl: 5000
```bash
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
```
Browser opens localhost:5001

------------------
launchUrl: 5080

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
```
Browser opens localhost:5080 - page cannot be loaded

------------------
applicationUrl: 5000

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
```

Browser opens localhost:5000

------------------
applicationUrl: 5080

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5080
```

Browser opens localhost:5080

------------------
applicationUrl: 5080
launchUrl: 5081

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5080
```

Browser opens localhost:5081 - page cannot be loaded


@volkanceylan also start from commandline working as expected with `applicationUrl`

**Comment by volkanceylan** [comment]
Ok then change it to applicationUrl
