### ISSUE TITLE
Error using Postgresql 12 on fresh template

### ISSUE THREAD

**Issue by mugambiwarwema** [volkanceylan/Serenity#5276]
Hello?

I downloaded a fresh template and followed the instruction to to use Postgresql. Although when I run my app I get the error below.

> PostgresException: 3D000: database "smart_user" does not exist

Heres my appsettings.json

```
  "Data": {
    "Default": {
      "ConnectionString": "Server=127.0.0.1; Database=smarta_v2; User Id=smart_user; Password=smart_Password;",
      "ProviderName": "Npgsql"
    }
```

Heres the configure() method in startup.cs

```
       SqlSettings.DefaultDialect = PostgresDialect.Instance;
            SqlSettings.AutoQuotedIdentifiers = true;
            RegisterDataProviders();
```

What am I doing wrong?

**Comment by JohnRanger** [comment]
Hi @mugambiwarwema ,

although I don't have any experience with PostgreSQL - if it is similar structured as MS SQL or MySQL - then I would expect that according to your error message, something is wrong with your connection string. 

Maybe try the following (from https://www.connectionstrings.com/postgresql/)

```Data Source=myServerAddress; location=myDataBase; User ID=myUsername; password=myPassword;```

With kind regards,

John

**Comment by javaman63** [comment]
I use this conecction string on the web.config file

`    <add key="CadenaConexion" value="Server=YOUR_SERVER;Port=5432;User Id=YOUR_USER;Password=YOUR_PASS;Database=YOUR_DATABASE;timeout=1024;CommandTimeout=100000" />`

**Comment by VictorTomaili** [comment]
Hi @mugambiwarwema  
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform)? It's seems some of connection string mistakes. Not serenity related bug. You can continue discussion at stackoverflow. If result of discussion point to a bug, then you open issue here with description. 
Thank you for understanding.

**Comment by mugambiwarwema** [comment]
I still think this is an issue/bug with Serenity or Npsql...because no answer exists

**Comment by ArmelleBouveret** [comment]
First, you have to create a database wich name is the name of your user "smart_user".

**Comment by mugambiwarwema** [comment]
I have created the database, I have created the user who has access to the
DB. But I keep getting the error.
