### ISSUE TITLE
IDeleteLogRow cannot log DeleteUserIdField when GuidField is used.

### ISSUE THREAD

**Issue by zainvegeta** [volkanceylan/Serenity#5277]
I am using using serenity to develop an application. I changed the default Id to Guid as it is of requirement.So i noticed that 
IDeleteLogRow cannot log DeleteUserIdField when GuidField is used.

**Comment by volkanceylan** [comment]
Delete log and other logs expects numerical ids due to historical reasons. You may implement your own behavior / interface.
