### ISSUE TITLE
Filter LookUpEditor for user table

### ISSUE THREAD

**Issue by mugambiwarwema** [volkanceylan/Serenity#5278]
I have added a column for UserType on user's table. 

I have referenced User table on Unit table.

I have added a LookUpScript on UnitsRow as shown below:

```
        [DisplayName("Lecturer"), NotNull, ForeignKey("[dbo].[Users]", "UserId"), LeftJoin("jLecturer"), TextualField("Lecturer")]
        [LookupEditor(typeof(UserRow), FilterField = "UserType", FilterValue = UserTypes.Lecturer)]
        public Int32? LecturerId
        {
            get { return Fields.LecturerId[this]; }
            set { Fields.LecturerId[this] = value; }
        }
```

UserType  is of type enum, as shown below:

```
    [EnumKey("SmartAttendance.UserTypes")]
    public enum UserTypes
    {
        [Description("Admin")] Admin = 1,
        [Description("Lecturer")] Lecturer = 2,
        [Description("Student")] Student = 3
    }
```

However, when I go to add a new unit/edit an existing one the dropdown is empty. I have 3 users in the database and one user is of type **UserTypes.Lecturer**

Please advise what I am missing.

**Comment by VictorTomaili** [comment]
Hi @mugambiwarwema  
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
