### ISSUE TITLE
Sergen oracle support

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#5279]
Hi EveryBody
Does Sergen Supports Oracle Database ?

**Comment by kilroyFR** [comment]
I am using it since 2018 with Oracle Db

**Comment by MaziarSangi** [comment]
Thanks @kilroyFR 
So you can Generate all classes with Sergen from Oracle Db in Asp.net core?

**Comment by VictorTomaili** [comment]
@kilroyFR thanks for answer, 
@mugambiwarwema  
Can you continue this discussion on [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues? If you faced any bug etc, you can open issue there. But for questions we prefer stackoverflow. 

So with your indulgence, I close this issue.

**Comment by sispk6** [comment]
"Data": {
    "Default": {
      "ConnectionString": "Data Source=192.168.1.4:1521/db19c;User Id=EA;Password=eE6sA",
      "ProviderName": "Oracle.ManagedDataAccess.Client"
    }

**Comment by MaziarSangi** [comment]
Thank you @sispk6 
I have installed Oracle.ManagedDataAccess.Core and sql developer to create tables.
But wen I Load Sergen It gives me Error While Running Sergen.

**Comment by Nathan2020-0126** [comment]
@sispk6, could you please give me more hint? I still cannot work with oracle. 
My appsetting
`    "WMS_DB": {
      //      "ConnectionString": "Data Source=(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.128.16.23)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = SCPRD)));User Id=wmwhse2;Password=WMwhSqlWMwhSql2;",
      "ConnectionString": "Data Source=10.128.16.23:1521/SCPRD;User Id=wmwhse2;Password=WMwhSqlWMwhSql2;",
      "ProviderName": "Oracle.ManagedDataAccess.Client"
    }`

RegisterDataProviders
`
 public static void RegisterDataProviders()
        {
            DbProviderFactories.RegisterFactory("System.Data.SqlClient", SqlClientFactory.Instance);
            DbProviderFactories.RegisterFactory("Microsoft.Data.Sqlite", Microsoft.Data.Sqlite.SqliteFactory.Instance);
            DbProviderFactories.RegisterFactory("Oracle.ManagedDataAccess.Client", Oracle.ManagedDataAccess.Client.OracleClientFactory.Instance);
            // to enable FIREBIRD: add FirebirdSql.Data.FirebirdClient reference, set connections, and uncomment line below
            // DbProviderFactories.RegisterFactory("FirebirdSql.Data.FirebirdClient", FirebirdSql.Data.FirebirdClient.FirebirdClientFactory.Instance);

            // to enable MYSQL: add MySql.Data reference, set connections, and uncomment line below
            // DbProviderFactories.RegisterFactory("MySql.Data.MySqlClient", MySql.Data.MySqlClient.MySqlClientFactory.Instance);

            // to enable POSTGRES: add Npgsql reference, set connections, and uncomment line below
            // DbProviderFactories.RegisterFactory("Npgsql", Npgsql.NpgsqlFactory.Instance);
        }
`

**Comment by N4N** [comment]
It is solved here fam: https://github.com/serenity-is/Serenity/pull/3309
