### ISSUE TITLE
How to show a partial view on Dashboard

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#528]
I want to show a partial view on dashboard for displaying a chart. can you guide me on how to approach this.

**Comment by volkanceylan** [comment]
Check a MVC guide, there is nothing special about this in Serenity

**Comment by mrajalko** [comment]
Can i add another action result in DashboardPage.cs as under:

public ActionResult CityChart()
{
        return PartialView("_CityChart");
 }
