### ISSUE TITLE
 Google geo chart help please

### ISSUE THREAD

**Issue by fatihsimsekk** [volkanceylan/Serenity#5280]
Hello, I ran the donut chart by looking at the examples on the page. but I'm trying to do the graphics google map geo turkey but I could somehow I would be very pleased if you would please help I am very beginner.

**Comment by VictorTomaili** [comment]
Hi @fatihsimsekk 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
