### ISSUE TITLE
Sergen using different app config

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#5282]
When I was using the Sergen web interface (under Administration) I noticed that the tables in the list were not the same tables that were in my app's database.

I use an extra app config file, _appsettings.Development.json_, for local development. This config file does not get checked in to source control.

* appsettings.json points to some "master" database.
* appsettings.Development.json points to my local development database.

My application runs off the database referenced in the appsettings.Development.json, and migrations are also run on this same database.

**Sergen seems to be looking at the database that is referenced in appsettings.json.** 

Is this desired behaviour, or is this a bug?

**PS**. The page title in SergenIndex.cshtml is using "Db.Administration.Translation.EntityPlural" instead of it's own name.

**Comment by volkanceylan** [comment]
Sergen does not modify your "master" database, but if you expect it to generate code for development one, you may put the connection strings in a appsettings.Production file, while development ones should stay in appsettings.json.

A master (production) connection string should not be checked into source control. I always exclude it from publish.

**Comment by edwardch** [comment]
Apologies, the word "master" was ambiguous. I didn't mean SQL Server's "master" database - I know Sergen isn't modifying this database. 

Better with an example:
Let's say developers have their own DEV database (to break/fix), and then also a local TEST database. A PROD database would be optional (probably only for some person with special permissions).

**Included in source control**
* appsettings.json points to a database named "Serene_Northwind_TEST"

If developers have this TEST database then there is no need to edit/commit the appsettings.config file.

**Excluded from source control**
* appsettings.Development.json points to a database named "Serene_Northwind_Edward_DEV"
* appsettings.Production.json points to a database named "Serene_Northwind_PROD"

Developers can do what they like with these, as they are not checked into source control.

Now when I set my environment to "Development" or "Production", Serenity and the migrations will run on my _DEV or _PROD databases. But no matter what my environment is, Sergen always seems to only look at my _TEST database.

@volkanceylan should Sergen also be using the connection based on the environment setting or is there a reason that it does not?

Thanks in advance,
Edward

**Comment by edwardch** [comment]
@VictorTomaili pinging you since I don't know if I will get clarity on an issue that you closed?

Then this is also a tiny mistake in the UI:
> PS. The page title in SergenIndex.cshtml is using "Db.Administration.Translation.EntityPlural" instead of it's own name.

**Comment by elenaaralla** [comment]
Hi,

I have the same problem; sergen only read connection in appsetting.json, not in my environment configuration file, i.e: appsettings.developement.json.

How can configure sergen to read the right connection (depending on environment setings?)

Thank you,
Elena.
