### ISSUE TITLE
Namespaces could not be found errors after first build try

### ISSUE THREAD

**Issue by umutdr** [volkanceylan/Serenity#5283]
I installed all of the dependencies then I created a dotnet core project using Serenity template from Visual Studio 2019. When I try to build the project first time it responds me with these errors below.

![seren](https://user-images.githubusercontent.com/42785142/99444734-ae54eb00-292d-11eb-8334-846bf3f6c513.png)

**Comment by VictorTomaili** [comment]
Hi @umutdr 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
