### ISSUE TITLE
ReadPermission on the xxxRow is required even with implicitpermission set

### ISSUE THREAD

**Issue by wirble** [volkanceylan/Serenity#5284]
Not sure if this is a bug or I am using it incorrectly.  If I have ImplicityPermission set on a permission key and in the row I just use ModifyPermission but not ReadPermission. It throws an error.

`[Description("Create/Update"), ImplicitPermission(General), ImplicitPermission(View)] 
         public const string Modify = "xxxmodule:Modify";`

`[ModifyPermission(PermissionKeys.Modify)]
     public sealed class xxxRow : Row, IIdRow, INameRow
    {`

Error:

`System.ArgumentOutOfRangeException: 'PageAuthorize attribute is created with source type of xxxRow, but it has no NavigationPermissionAttribute OR ReadPermissionAttribute attribute(s) (Parameter 'sourceType')'
`

**Comment by VictorTomaili** [comment]
Hi @wirble 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform)? After discussion if it's points to a bug, then open issue here.

Have a good day. 🙋‍♂️

**Comment by volkanceylan** [comment]
As error implies, your row does not have those attributes.
