### ISSUE TITLE
Can we use any ES6 library with?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#5286]
Can we use serenity with compiled with ES6 sytanx library? Example: https://reactstrap.github.io/

I have just tested on two diffrenet scenario:
libary: https://reactstrap.github.io
My project is already converted to react style

1- Only added library CDN url (https://cdnjs.cloudflare.com/ajax/libs/reactstrap/4.8.0/reactstrap.min.js) 
Nothing happened. Any component recognized.

2- Changed tsconfig.json  "target": "es5",===>   "target": "ES6". Added library url
Lots of simple syntax changing on Web.js 
Any screen loaded succssfully.
Common components like SideBar, LanguagerBar etc not founded.

Is there any way to use compiled these type of UI libraries with serenity?

**Comment by VictorTomaili** [comment]
Hi @ademc 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
