### ISSUE TITLE
Pages are not displayed

### ISSUE THREAD

**Issue by pesnunj0** [volkanceylan/Serenity#5287]
Hi,
making changes on one grid, in my project all pages with Grid are not displayed anymore. Only login page, dashboard and menu are visible.
Any idea?
Thank you so much

**Comment by VictorTomaili** [comment]
Hi @pesnunj0 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
