### ISSUE TITLE
Intergrate Ckfinder

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#5288]
Dear all,

I try to intergrate CKfinder.  I follow the steps in [#4994](https://github.com/volkanceylan/Serenity/issues/4994), but in the last, I got an error like below. what should I need to change?
![image](https://user-images.githubusercontent.com/16734387/99931524-ceeace00-2d8f-11eb-8ade-454e85e04a83.png)

**Comment by VictorTomaili** [comment]
Hi @Nathan2020-0126 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
