### ISSUE TITLE
Lookup Editor Codepage (Turkish Character) saving problem

### ISSUE THREAD

**Issue by serkansonmez** [volkanceylan/Serenity#5289]
Hi,

Turkish characters in the list produced by LookupScript automatically turn into English characters after save (such as İ -> I, Ş -> S), how can I prevent this?

Thanks.

![image](https://user-images.githubusercontent.com/25242018/99943375-4154b180-2d82-11eb-958c-7d8bd69d7a39.png)

```

 [LookupScript]
    public class MevsimLookup : RowLookupScript<Entities.EmyEnvanterRow>
    {
        public MevsimLookup()
        {
            IdField = TextField = "Mevsim";
        }
        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = Entities.EmyEnvanterRow.Fields;
            query.Distinct(true)
                .Select(fld.Mevsim)
                .Where(
                    new Criteria(fld.Mevsim) != "" &
                    new Criteria(fld.Mevsim).IsNotNull());
        }

        protected override void ApplyOrder(SqlQuery query)
        {
        }
    }
```

in Row.cs
   ```
[DisplayName("Mevsim"), Size(150), NotNull, QuickSearch, LookupEditor(typeof(Lookups.MevsimLookup))]
        public String Mevsim
        {
            get { return Fields.Mevsim[this]; }
            set { Fields.Mevsim[this] = value; }
        }
```

**Comment by VictorTomaili** [comment]
Hi @serkansonmez 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).

Tip: I guess your table column collation is defined wrong. But anyway, if it's not you need to ask on stackoverflow. Serenity doesn't have behavior like this.
