### ISSUE TITLE
Can I retrieve the Row entities from a Dictionary?

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#529]
Hello to all!

I have a multi table query like this:

     {
       [...]
       Alias One = new Alias(fld.TableName, "ONE");
       Alias Two = new Alias(fld2.TableName, "TWO");
                
       CustomQuery = new SqlQuery()
             .From(One)
             .Select("*")
             .Select("*")
             .Where(new Criteria(One, fld.Id) == code &
                    new Criteria(One, fld.Date) == date)
             .LeftJoin(TwoTab.TableName, Two, 
                         new Criteria(One, fld.Id) == new Criteria(Two, fld2.Id) &
                         new Criteria(One, fld.IdDateFrom) == new Criteria(Two, fld2.IdDateFrom));
     
      var Entities = RequestParams.Connection.Query(CustomQuery).ToList();
      System.Collections.Generic.Dictionary<string, object>[] multiRowArray = ExtractDic(Entities ....);
      [...]
       Table1Row  t1 = new  ExtractT1FromDic(multiRowArray[0]);  // Here the code for extract the Row entity
       Table2Row  t2 = new  ExtractT2FromDic(multiRowArray[0]);  // Here the code for extract the Row entity
    }

      private Dictionary<string, object>[] ExtractDic(List<dynamic> entities, int iFrom, int iTo)
      {
                 Dictionary<string, object>[] dic = new System.Collections.Generic.Dictionary<string, object>[entities.Count];

                int i = 0;
                foreach (IDictionary<string, object> entry in entities)
                {
                    [...]
                            dic[i].Add(pair.Key, pair.Value)
                    [...]

Can I retrieve the Row entities from a Dictionary (or other object)?
I would like to retrieve a separated row object for each table in the query, like this:

      Table1Row  t1 = new  ExtractT1FromDic(dic);  // Here the code for extract the Row entity
      Table2Row  t2 = new  ExtractT2FromDic(dic);  // Here the code for extract the Row entity

Thank you a lot, and congratulations for the splendid work Volkan

**Comment by volkanceylan** [comment]
RequestParams.Connection.Query(CustomQuery).ToList(),

you should use Query < Dictionary<string, object> > if you want to get a dictionary.

Anyway i don't recommend such queries. If possible add fields you require to one of rows as view fields. See mapping guide. Aliases was just a sample in guide, you shouldn't use them when working with entities.

**Comment by Estrusco** [comment]
Then I will use the view fields, I will follow your advice.

Thank you very much Volkan.
