### ISSUE TITLE
changeSelect2 event is not firing (after version: 3.14.4)

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#5290]
After upgrading to latest version 3.14.4; changeSelect2 event is not firing
```
            this.form.SomeLookup.changeSelect2(e => {
                 Q.Alert('');// this is not executed anymore.
            });
```
changeSelect2 related issues https://github.com/volkanceylan/Serenity/issues/3602 https://github.com/volkanceylan/Serenity/issues/5052

**Comment by VictorTomaili** [comment]
@dfaruque can you try with  3.14.5 ?

**Comment by dfaruque** [comment]
Yes. It is fixed now. Thanks.
