### ISSUE TITLE
has anyone implemented: integrating serenity app inside ELECTRON.NET

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#5294]
I am able to run serenity app inside https://github.com/ElectronNET/Electron.NET
but typescript is not getting executed causing javascript/jquery not found error

**Comment by VictorTomaili** [comment]
Hi @samdubey 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
