### ISSUE TITLE
How to apply window function in serenity row

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5297]
Hi All;

Is there a way to apply SQL window function like following in the serenity xxRow.cs or any xxcolumn.cs.
I have applied, it does not give any error however it is showing blank:
 `count(ID) over (partition by MainID order by ID rows unbounded preceding)`

Thanks for any help

**Comment by VictorTomaili** [comment]
Hi @ms4hafiz 
Can you post this question to [stackoverflow ](https://stackoverflow.com/tags/serenity-platform) instead issues?

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
