### ISSUE TITLE
How to add third party control

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#53]
How to add third party control like tinymce editor in place of TextAreaEditor, Treeview control, radio button list, checkboxlist and many more...
How to bind default values to dropdown list. In Serenity guide show example of Adding a Movie	Kind	Field doesn't work. I work on Class Year drop down has some default values like 

[EnumKey("CourseDB.ClassYearKind")]
    public enum ClassYearKind
    {
        [Description("First")]
        First = 1,
        [Description("Second")]
        Second = 2,
        [Description("Third")]
        Third = 3,
        [Description("Fourth")]
        Four = 4,
        [Description("Fourth")]
        Five = 5,
        [Description("Sixth")]
        Six = 6
    } 

but it didn't work.

**Comment by volkanceylan** [comment]
After adding new enums, you must rebuild project and then transform all templates and rebuild again before running application. This imports new enum to script side code. Also make sure you use this new enum in row property declaration and forms.

**Comment by laxmanp** [comment]
ok. but how to add third party control like tinymce editor in place of TextAreaEditor, Treeview control, radio button list, checkboxlist and many more...

**Comment by volkanceylan** [comment]
I'll add a howto to serenity guide for CKEditor. And maybe another third party control. Meanwhile, you might look at source code for DateEditor, Select2, SlickGrid, GoogleMaps etc. to see how to integrate a 3rd party control.

**Comment by volkanceylan** [comment]
As CKEditor scripts are now in Serene template, you can simply use [HtmlContentEditor] instead of [TextAreaEditor] attribute to use CKEditor.
