### ISSUE TITLE
Alert message not in local language

### ISSUE THREAD

**Issue by wpvking** [volkanceylan/Serenity#530]
Hi, this I cannot understand :).

![image](https://cloud.githubusercontent.com/assets/7986251/14348499/2eb31f30-fcbd-11e5-9952-cc0742cc3bb2.png)

Should be English.

**Comment by 107295472** [comment]
Configuration automatically loaded web.config  <globalization culture="zh-cn" uiCulture="zh-cn" />

**Comment by volkanceylan** [comment]
Converted to localtext, will be in next version.
