### ISSUE TITLE
Scrollbars in Default templates

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#531]
I realise this is probably an entirely silly issue and I am just looking in the wrong place. But the extension in to the top nav bar is really quite odd. Where am I supposed to be configuring that?

**Comment by volkanceylan** [comment]
I dont understand but you may try AdminLTE repository for issues about theme

**Comment by solabar** [comment]
Hi Volkan, I have it figured out. It's a specific IE issue. adding -ms-overflow-style: scrollbar; to the body fixes the issue. Essentially the content was being flowed over by IE's autohiding scrollbars. Irritating more than anything else.

**Comment by volkanceylan** [comment]
Thanks, your fix will go into next Serene version.
