### ISSUE TITLE
Upgraded from 1.9.28 to 2.02, TextAreaEditor breaks dialog forms

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#532]
Any forms with a TextAreaEditor no longer load. Javascript errors in Serenity.Script.UI.js

```
var $Serenity_TextAreaEditor = function(input, opt) {
		ss.makeGenericType($Serenity_Widget$1, [$Serenity_TextAreaEditorOptions]).call(this, input, opt);
		if (this.options.cols !== 0) {
			input.attr('cols', this.options.cols.toString());
		}
		if (this.options.rows !== 0) {
			input.attr('rows', this.options.rows.toString());
		}
	};
```

`if (this.options.cols !== 0) {
			input.attr('cols', this.options.cols.toString());`
cols and rows is null, so the .toString() call is throwing a nullreference exception.

**Comment by wldkrd1** [comment]
Note that this is with the Saltarelle forms, not Typescript forms; I haven't tried Typescript yet.

**Comment by volkanceylan** [comment]
Ok will have a look, probably imported class issue

**Comment by wldkrd1** [comment]
Hoo mama, you weren't kidding about the difficulty in going back. I was relying on my source control to take care of it, but apparently there were some items which never made it in there...

**Comment by volkanceylan** [comment]
Btw, are you using Serenity as a submodule? The code you listed looks like its from 1.9.28. Because widget is no longer generic. Your serenity script files are probably old. Copy them from a new template or see Serenity/tools/serenity.submodule.web.targets file and include that target it your web project to make them auto copied on build. Sample is in Dev.Serene.Web.csproj

**Comment by volkanceylan** [comment]
Should be fixed with 2.0.3

**Comment by wldkrd1** [comment]
I noticed this problem during the 'Ensuring Package Updates Caused No Problems' step from the upgrade guide :-)

I'm back on 1.9.28, will try again when 2.0.3 is available. Thanks!

**Comment by wldkrd1** [comment]
Confirmed this is resolved with 2.0.3

**Comment by volkanceylan** [comment]
Thanks, sorry for trouble.

**Comment by wldkrd1** [comment]
No worries; the problem was I didn't follow instructions yesterday when I was told to back up the solution. The upgrade this morning went smoothly, I assume because I did the backup this time :+1: .
