### ISSUE TITLE
ServerTypings.tt issue

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#533]
Dear,

![image](https://cloud.githubusercontent.com/assets/16621563/14360229/424fe3fc-fd17-11e5-9ae4-cb0ce8fd5ba9.png)

here some tt files generated code
```
export namespace Methods {
            export declare const Create: 'Administration/User/Create'; //I think here instead of : it should be =
            ..........
        }

export namespace Fields {
            export declare const CategoryID: 'CategoryID'; //I think here instead of : it should be =
            .........
        }
```
thanks

**Comment by volkanceylan** [comment]
Maybe but it doesnt give error in my VS. Did you install 1.8 latest typescript

**Comment by volkanceylan** [comment]
Yes this is supported in 1.8, you don't have it. Anyway removed them as they were only informational.
