### ISSUE TITLE
Formatting of message box

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#534]
I have the following confirmation format for BulkServiceAction. Inserting HTML tags or crlf did not help formatting it properly. How can I format it as a list with each item on a separate line? 

    public class RecalcBudgetAction : BulkServiceAction
    {
        protected override string GetConfirmationFormat()
        {
            StringBuilder buffer = new StringBuilder("This action will automatically perform the following for selected department(s):");
            buffer.Append(" ");
            buffer.Append(" (1). Calculate default appropriation requested budget (last year $ + user defined %");
            buffer.Append(" (2). Calculate default position requested budget (last year $ + user defined %)");
            buffer.Append(" (3). Calculate default insurance amount (full time employee count * user defined $)");
            buffer.Append(" (4). Calculate default FICA amount (total salary $ * user defined %)");
            buffer.Append(" (5). Calculate default PERF amount (total salary $ * user defined %)");
            buffer.Append(" ");
            buffer.Append("Perform this operation on {0} selected record(s)?");

            return buffer.ToString();
        }

![2016-04-07_191811](https://cloud.githubusercontent.com/assets/17013052/14370617/826903fa-fcf5-11e5-968c-c4ec11809401.png)

**Comment by volkanceylan** [comment]
Try using < p > and < br / > tags then set HtmlEncode false in third param to confirm

**Comment by volkanceylan** [comment]
Ah you need to override Confirm method in BulkServiceAction to set these options

**Comment by c9482** [comment]
That worked beautifully - thanks again. Here is the code I used:

    public class RecalcBudgetAction : BulkServiceAction
    {
        protected override void Confirm(int targetCount, Action action)
        {
            ConfirmOptions co = new ConfirmOptions();
            co.HtmlEncode = false;
            Q.Confirm(GetConfirmationMessage(targetCount), action, co);
        }

        protected override string GetConfirmationFormat()
        {
            StringBuilder buffer = new StringBuilder("This action will automatically perform the following for selected department(s):");
            buffer.Append("<ol>");
            buffer.Append("<li>Calculate default appropriation requested budget (last year $ + user defined %</li>");
            buffer.Append("<li>Calculate default position requested budget (last year $ + user defined %)</li>");
            buffer.Append("<li>Calculate default insurance amount (full time employee count * user defined $)</li>");
            buffer.Append("<li>Calculate default FICA amount (total salary $ * user defined %)</li>");
            buffer.Append("<li>Calculate default PERF amount (total salary $ * user defined %)</li>");
            buffer.Append("<li>Roll up salaries by account category into matching appropriation line items</li>");
            buffer.Append("</ol>");
            buffer.Append("Perform this operation on {0} selected record(s)?");

            return buffer.ToString();
        }
