### ISSUE TITLE
How to format a date column 

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#535]
How to format a date column to show in format "dd/MM/yyyy"

**Comment by mrajalko** [comment]
done by using DateFormatter(DisplayFormat = "dd/MM/yyyy")

**Comment by paulobriennz** [comment]
thanks for this - works great on columns.. but what do you use on a form?

**Comment by mrajalko** [comment]
Use DateTimeEditor

**Comment by paulobriennz** [comment]
Thankyou

Confirm [DateTimeEditor] shows the time of day as well.  Could you also advise how you set the date format on the DateTimeEditor?  I have tried various scenarios but it is showing MM/dd/yyyy for the date format and i am trying to get it to match the format ive set in the COumn with the above dd/MM/yyyy format.

Thanks in advance.

**Comment by volkanceylan** [comment]
You should change culture in web.config to something that uses dd/MM/yyyy, or set your preferred format in LayoutHead, setting your prefs in ScriptCulture object constructor.
