### ISSUE TITLE
Dynamic DisplayName

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#536]
Hi,
I would like to know if it is possible to change the display name of a field Dynamically. I have a table that defines the display names of fields for each customer. This table also specifies whether a field is visible or not.

If have tried the following  but it does not work.

        String DispVarChar1 = "New Column Name";
        [DisplayName(DispVarChar1), Column("varchar1"), Size(200)]
        public String Varchar1
        {
            get { return Fields.Varchar1[this]; }
            set { Fields.Varchar1[this] = value; }
        }

**Comment by volkanceylan** [comment]
No its not possible this way, you should try doing it client side, overriding GetPropertyItems

**Comment by volkanceylan** [comment]
There is also a AfterInitialize method of RowFields, you may set display name there overriding it

**Comment by GeorgeBarkhuizen** [comment]
Thank you for the quick response.

**Comment by qprotex** [comment]
> There is also a AfterInitialize method of RowFields, you may set display name there overriding it

Hello @volkanceylan . Do you have a sample on how to implement this but for a class rather than a field?
