### ISSUE TITLE
adding jquery-2.2.0.min.js on dashboard page

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#538]
adding jquery-2.2.0.min.js on dashboard page has same effect as adding jquery-2.0.0.min.js.

i am using it as i am using highchart as charting tool and it requires jquery.

**Comment by volkanceylan** [comment]
Dont add it, its already included in all pages.

**Comment by volkanceylan** [comment]
Jquey2.2.0.js and jquery.2.2.0.min.js are same things, latter is just minimized

**Comment by mrajalko** [comment]
without adding unable to show highcharts. 
after adding in section head of dashboardIndex.cshtml highcharts works but some error in serenity.

the console in such case is as under:

Uncaught TypeError: Cannot read property 'messages' of undefined
Serenity.Script.Core.js:2009 TypeError: $.blockUI is not a function(…)
Serenity.Script.Core.js:2010 TypeError: $.blockUI is not a function
    at Function.$Q.$blockUIWithCheck (Serenity.Script.Core.js:17)
    at Function.$Q.blockUI (Serenity.Script.Core.js:28)
    at Serenity.Script.Core.js:651
    at $$$internal$$tryCatch (rsvp.js:487)
    at $$$internal$$invokeCallback (rsvp.js:499)
    at rsvp.js:1083
    at MutationObserver.$$rsvp$asap$$flush (rsvp.js:1556)

**Comment by chadburnett** [comment]
I have this issue while using fullcalendar.  I am not sure if it's related.  
![image](https://user-images.githubusercontent.com/12171582/42581529-9073f734-84f2-11e8-952a-93688e33c9d1.png)
