### ISSUE TITLE
want to show highcharts in serenity

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#539]
if I include jquery-2.2.0.js in DashboardIndex.cshtml file in header section as under

<script src="~/Scripts/jquery-2.2.0.js"></script>

then i am able to show the highchart otherwise highchart does not displays.
in this scenario serenity gives some issue. the console log picture is as under:

![jquery error](https://cloud.githubusercontent.com/assets/18166582/14384025/5c04c8a4-fdb6-11e5-9325-f09d5f91a322.png)

**Comment by awesomegithubusername** [comment]
I think you're getting this error because jquery is already included with serenity so you're dealing with a double reference. Check network tab for details.

**Comment by volkanceylan** [comment]
First, third time, stop including jquery yourself. Then move highcharts include to bottom of layouthead. If it is still not working read docs of highcharts carefully.

**Comment by mrajalko** [comment]
Thanks, It worked the way you suggested. I have to comment out morris and dashboard script reference in DashboardIndex.cshtml file.

thanks again for bearing with me.
