### ISSUE TITLE
How to add custom code or logic

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#54]
Hello sir,

How to add custom code like send email or sms by click on button. Where to add some logic like test generation and calculation.

**Comment by volkanceylan** [comment]
Have a look at forgot password code to see a sample of sending mail on button click through a service.

Though that sample puts service in a AccountPage.cs, while you should put yours in MyEndpoint.cs

**Comment by volkanceylan** [comment]
Reopen if it didn't resolve your issue
