### ISSUE TITLE
whats wrog with this code

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#540]
`private class MyListHandler : ListRequestHandler<MyRow> {

            
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                
                var usrID = Authorization.UserId;
                var Uclist = new uclist();
                using (var conn = SqlConnections.NewFor<Entities.UserCountryRow>())
                {
                    var UCFields = UserCountryRow.Fields;
                    Uclist.CountryIDs = conn.List<UserCountryRow>(q => q
                    .Select(UCFields.CountryId)
                    .Where(new Criteria(UCFields.UserId) == usrID)
                    );
                }

               query.Where(fld.CountryId.In(Uclist.CountryIDs));
            }
        }
       
        public class uclist
        {
            public List <UserCountryRow> CountryIDs{ get; set; }
        }`

**Comment by wldkrd1** [comment]
It's missing comments? You're not using the One True Brace Style? You've lowercased a class name?
I give up. What's wrong with the code? Or...why do you think something is wrong with it?

**Comment by volkanceylan** [comment]
He's probably trying to use a custom list request. Your list handler should be deriving from `ListRequestHandler<MyRow, UCListRequest>`

UCListRequest should derive from ListRequest.

Then, you should read Request.CountryIDs in while calling query.Where

Also need to change ListRequest to UCListRequest in Repository.List and Endpoint.List  methods

**Comment by zerodev** [comment]
well am just trying to filter the query by overriding  `Protected override void ApplyFilters(SqlQuery query)` am getting a list of user countries to pass it as where condition in the query using In
the code is a mess I know am just playing with it to check behaviors 
I ant to filter data for the current user  by getting  the list form another table
