### ISSUE TITLE
Lookup Editor filtering Items that already assigned

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#542]
Is there a way to Filter the lookup editor items to return all items that is not assigned to a parent record.

Something like this
var result = peopleList2.Where(p => !peopleList1.Any(p2 => p2.ID == p.ID));
i will get all results that are not  in both tables

**Comment by swordz36** [comment]
Essentially I would like to filter my list on the server side rather that using the script project.

**Comment by volkanceylan** [comment]
See this issue https://github.com/volkanceylan/Serenity/issues/375

**Comment by swordz36** [comment]
I have a query to  solve it but I am not familiar with where to add this in the serenity framework

SELECT *
FROM MaterialCodeSKU m
LEFT JOIN ProductMaterialCode pm ON pm.MaterialCodeId = m.MaterialCodeId
WHERE pm.MaterialCodeId IS NULL

**Comment by swordz36** [comment]
@volkanceylan is the OrginaziationalEditor the joining table the example you referenced?

**Comment by volkanceylan** [comment]
Yes it is cascaded.
