### ISSUE TITLE
Popping error message box after clicking inline button

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#543]
I have the following endpoint method:

        public FileContentResult ListExcel(IDbConnection connection, ListRequest request)
        {
            new MyRepository().RefreshExportTable(connection);

            var data = List(connection, request).Entities;
            var report = new DynamicDataReport(data, request.IncludeColumns, typeof(Columns.LawsonLineItemExportColumns));
            var bytes = new ReportRepository().Render(report);
            return ExcelContentResult.Create(bytes, "LawsonLineItemExport_" +
                DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".xlsx");
        }
And here is the grid code to invoke it:

        protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();

            buttons.RemoveAt(0);

            buttons.Add(Common.ExcelExportHelper.CreateToolButton(this,
                LawsonLineItemExportService.BaseUrl + "/ListExcel", this.OnViewSubmit));

            return buttons;
        }

        protected override bool OnViewSubmit()
        {
            bool result = false;

            try
            {
                result = base.OnViewSubmit();
            }
            catch (System.Exception e)
            {
                Q.NotifyError(e.Message, "Error");
            }

            return result;
        }

If an exception occurs calling RefreshExportTable, get some textual data instead of the expected message box (Q.NotifyError(e.Message, "Error")):

{"Error":{"Code":"Exception","Message":"All departments must be finalized","Details":"System.Data.SqlClient.SqlException (0x80131904): All departments must be finalized\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at ......

What is the proper method to display error message box when exception occurs? Many thanks in advance.

**Comment by volkanceylan** [comment]
We can't display a proper message box here, because it's a service endpoint and called from a new tab, but it could be possible to redirect to an error page.

Why we are using a new tab, because if some error occurs we would lose current grid page, all filters, state etc.

Try something like this:
```cs
        public ActionResult ListExcel(IDbConnection connection, ListRequest request)
        {
            try
            {
                var data = List(connection, request).Entities;
                var report = new DynamicDataReport(data, request.IncludeColumns, typeof(Columns.OrderColumns));
                var bytes = new ReportRepository().Render(report);
                throw new Exception("Something went wrong");
                return ExcelContentResult.Create(bytes, "OrderList_" +
                    DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".xlsx");
            }
            catch (Exception ex)
            {
                return View(MVC.Views.Errors.ValidationError, new ValidationError(ex.Message));
            }
        }
```

**Comment by c9482** [comment]
This works but how to display the error on the same tab
OR
Flash a message similar to OrderBulkAction?

**Comment by volkanceylan** [comment]
Simply you cant have both at same time. Browsers doesnt let you post and download a file with ajax request. So your only option is to make a second action e.g. ListExcelValidate, do your validation there and if it is success then call ListExcel

**Comment by volkanceylan** [comment]
http://stackoverflow.com/questions/3499597/javascript-jquery-to-download-file-via-post-with-json-data

**Comment by volkanceylan** [comment]
Please reopen if this workaround didn't help.
