### ISSUE TITLE
tree dailog   I would like to ask what plug-ins

### ISSUE THREAD

**Issue by 107295472** [volkanceylan/Serenity#544]
Copyright © 2016.volkanceylan All rights reserved.    At the bottom of the copyright

**Comment by 107295472** [comment]
Uncaught TypeError: Cannot read property '__typeName' of undefined    mscorlib.js

**Comment by 107295472** [comment]
Page blank data

**Comment by 107295472** [comment]
![qq 20160409172148](https://cloud.githubusercontent.com/assets/6436116/14402974/c3f2984e-fe77-11e5-85d9-a49d745dfc42.png)

**Comment by volkanceylan** [comment]
Let me check my magic sphere

**Comment by 107295472** [comment]
Found error, generate dependency script
