### ISSUE TITLE
SQL Calculated Fields

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#545]
Hi,
 I have a SQL Table that contains a calculated Field. I receive an error "Field not update-able" when saving the record.  Is it possible to modify the auto generated  Insert/Update statements  to exclude that specific field from the statement?

**Comment by zerodev** [comment]
add this to the row field
[DisplayName("fld display name"), SetFieldFlags(FieldFlags.Calculated)]

**Comment by GeorgeBarkhuizen** [comment]
Thanks, 
 This works for the calculated field but is there a way to change the auto generated Insert/Update statements?

**Comment by volkanceylan** [comment]
What is that you want to change in statements

**Comment by zerodev** [comment]
if you mean for same field and you want to hide it I use this [HideOnUpdate, HideOnInsert]

but I did as @volkanceylan  said why changing insert

**Comment by GeorgeBarkhuizen** [comment]
It seems that [HideOnUpdate] just hide the field from display but the Update Statement still affects that field.

**Comment by GeorgeBarkhuizen** [comment]
I have a table with an after update trigger on a field. Currently the update statement will update all fields in the table thus causing the trigger to fire even if the data in that field  has not changed.  I would therefor want to exclude that field from the update statement.    Currently I am receiving an Error “The Query affected 10 records when 1 is expected” because of the trigger .

**Comment by volkanceylan** [comment]
You may add SET NOCOUNT ON to trigger, or Row.ClearAssignment(fld.SomeField) overriding BeforeUpdate

**Comment by GeorgeBarkhuizen** [comment]
Where would I do Row.ClearAssignment(fld.SomeField)

**Comment by dfaruque** [comment]
inside MyUpdateHandler override BeforeUpdate method in your row.cs

**Comment by GeorgeBarkhuizen** [comment]
Do you perhaps have Sample Code for this?

**Comment by volkanceylan** [comment]
I don't have a sample, sorry, try it first

**Comment by GeorgeBarkhuizen** [comment]
I did this in the repository.cs file.

  private class MySaveHandler : SaveRequestHandler<MyRow> 

        {
            protected override void BeforeSave()

            {
                base.BeforeSave();
                Row.ClearAssignment(fld.SubsidyBandId);

            }          
        }

**Comment by ali-h2010** [comment]
I need to add a new column that i get from another table. How can i intersect the values before showing them. I am not seeing any controllers. All i see are some meathods to get the repo values. Please help me understand the structure of this project

**Comment by ali-h2010** [comment]
I think i found the answer in the documentation!
https://serenity.is/Docs/entities/mapping_attributes
