### ISSUE TITLE
Connection strings

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#546]
Sorry for all my questions but I have just started with Serenity. 

I have a situation where I have multiple databases with similar structure.  I want to store the connection string to each database in a table  and present the user with a selection to choose the preferred dataset at login time and then set the connection string based on the selection made. 

Is it possible to do?

**Comment by volkanceylan** [comment]
There is a method in SqlConnections to override a connection string by its key but this won't work properly when two different users login that are using different databases at same time. So short answer is no.

**Comment by GeorgeBarkhuizen** [comment]
Can one not dynamically change the ConnectionKey value to use a different connection?

**Comment by volkanceylan** [comment]
Nah, just like you can't change connection strings in web.config dynamically.

**Comment by vinaykulkarni89** [comment]
@GeorgeBarkhuizen you can add another config file and reference that in web.config, I have never tried but have read about this, and this external config file can be altered at runtime and even these settings can be read by xml object at server side
