### ISSUE TITLE
How to set MinimumResultsForSearch for AddEqualityFilter<EnumEditor>?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#548]
I want to hide search box form the EqualityFilter which his based on  EnumEditor but i could not found any option to set MinimumResultsForSearch.
 `lkeVoucherMismatch = AddEqualityFilter<EnumEditor>(Fields.IsAmountMatch,`
               `options: new EnumEditorOptions { EnumKey = "Enum.Accounting.MismatchAmount" });`

but this is available in LookupEditor -
 `lkeVoucherStatus = AddEqualityFilter<LookupEditor>(Fields.Status,
             options: new LookupEditorOptions { LookupKey = ApprovalStatusRow.LookupKey, MinimumResultsForSearch = 10 });`

How to set MinimumResultsForSearch for AddEqualityFilter<EnumEditor>?

**Comment by volkanceylan** [comment]
You can't, subclass enumeditor if you need.
