### ISSUE TITLE
Serenity Code Generator failed after upgrading to 2.4

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#551]
I follow upgrade tutorial and able to upgrade to 2.4 and code is working fine but i am getting following error -
https://drive.google.com/file/d/0B9UGZZFXh-e6VzhzQ0ROcWxJQW8/view?usp=sharing

Although  files gets generated after closing the sergen exe.

Do i need to do any configuration to avoid this error?

**Comment by ramveersgh** [comment]
Its generated files in .web project but did not create anything in .script project.

**Comment by volkanceylan** [comment]
It's a bug, please update packages to 2.0.5

**Comment by ramveersgh** [comment]
OK, After upgrading to 2.0.5 it gets fixed.
Thanks.
