### ISSUE TITLE
Set default value Select2editor

### ISSUE THREAD

**Issue by rudianto2008** [volkanceylan/Serenity#553]
Hi Jaiq,

How to set default value in Select2Editor i want to set "Waiting Approval" as default value.

 [Editor]
    public class StatusEditor : Select2Editor<object, object>
    {
        public StatusEditor(jQueryObject hidden)
            : base(hidden, null)
        {
            AddItem("Waiting Approval", "Waiting Approval");
            AddItem("Approve", "Approve");
            AddItem("Reject", "Reject");
        }
    }

**Comment by volkanceylan** [comment]
Use [DefaultValue] attribute in your form

**Comment by rudianto2008** [comment]
i used this just as equality filter, how to set default value? not in form

  protected override void CreateToolbarExtensions()
        {
            base.CreateToolbarExtensions();
            AddEqualityFilter<ApprovalUserStatusEditor>(Fields.ApprovalStatus);
        }

**Comment by volkanceylan** [comment]
See how i set it in other sources maybe? Don't be lazy...

**Comment by rudianto2008** [comment]
Noted, thanks
