### ISSUE TITLE
Cascading Lookup filters

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#555]
I have the following scenario:
Customer -> Department -> Order
Is it possible to have a Cascading Filter on Order  which starts with Customer?

**Comment by jsbUSMC** [comment]
Yes. Did you read the Developer Guide?

**Comment by GeorgeBarkhuizen** [comment]
This example explains a one level Parent Child Relationship. In my case I have a 2 level relationship.
I want to filter Orders first on Customer and then by Departments.

![image](https://cloud.githubusercontent.com/assets/18344607/14450671/ef378946-0080-11e6-9807-f9a5cc6dd0d1.png)

**Comment by GeorgeBarkhuizen** [comment]
Sorry, My bad.

My Foreign keys on the database was not correct so sergen did not generate  Department_CompanyID as part of Orders.

**Comment by volkanceylan** [comment]
Sergen wont generate more than one level. See mapping guide
