### ISSUE TITLE
Required EqualityFilter<LookupEditor> ?

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#556]
I'm adding an `EqualityFilter<LookupEditor>` to my grid, but I'd like to make it required, i.e. prevent the user from clearing the filter. Have any ideas for how to accomplish that?

Thanks!

**Comment by volkanceylan** [comment]
You should probably subclass LookupEditor, override GetSelect2Options and turn off AllowClear

**Comment by wldkrd1** [comment]
That did it, thanks!
