### ISSUE TITLE
Changing default 'X' and Okay/Cancel Look

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#557]
I was wondering how I could change the default 'X' icon on forms (the popup dialogs) and how to change the look of the Okay/Cancel, Update, and other default button looks on the dialog forms as well as the columns? Can't seem to figure out what part of the less files holds this information.
Also, how do I add a favicon?
Thanks!

**Comment by volkanceylan** [comment]
Its in serenity.css and aristo.css

**Comment by volkanceylan** [comment]
For favicon add favicon.ico to your webroot

**Comment by wdhodges** [comment]
Thank you sir
