### ISSUE TITLE
Report based on Stored Procedures

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#558]
Is there any sample to show report based on result from a stored procedure.

can someone please guide me on how to approach this requirement.

**Comment by volkanceylan** [comment]
See dapper docs on how to call a stored proc

**Comment by mrajalko** [comment]
I have already done that for save.

[HttpPost]
        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            //return new MyRepository().Create(uow, request);
            int ret = uow.Connection.Execute("SaleAdvice_Save"
                , new { AdviceDate = request.Entity.Date
                    , AgentCode = request.Entity.Agent
                    , SoleAgentCode = request.Entity.SoleAgent
                    , ValidTill = request.Entity.ValidTill }
                ,null,null, CommandType.StoredProcedure);
            int detLength = request.Entity.DetailList.Count;
            for (int i = 0;i< detLength;i++)
            {
                ret = uow.Connection.Execute("SaleAdviceDetail_Save"
                    , new {SerialNumber = request.Entity.DetailList[i].SrNo
                            ,ProductCode = request.Entity.DetailList[i].Product
                            ,Grade = request.Entity.DetailList[i].Grade
                            ,Quantity = request.Entity.DetailList[i].Qty
                            ,Rate = request.Entity.DetailList[i].Rate
                    }
                ,null,null, CommandType.StoredProcedure);
            }
            return new SaveResponse();
        }

I was asking how can i generate script portion for columns of a stored procedure or how can i hand code it manually.

please give me a guideline on that.

**Comment by volkanceylan** [comment]
You can hand code one taking existing rows as sample. There is no tool to generate code for stored proc.
