### ISSUE TITLE
Cascading dropdown display

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#56]
Hello sir I have four table, course, class, subject and topic. Class has ref. of CourseId, Subject has ref. ClassId, Topic has ref. of SubjectId. I have generated all form and customize it work fine, but there is additional requirement in topic popup has facility to add course, class same as Nothwind=>Product=>Product Name click => Display Supplier and Category like functionality.
Class name filter on Course dropdown.
Plz help me.

**Comment by volkanceylan** [comment]
I have difficulty understanding question, sorry but can you explain it a bit more.

**Comment by laxmanp** [comment]
I have requirement class name dropdown populate based on course dropdown selection and subject name dropdown populate based on class name selection. Plz explain me step by step procedure how to do? In our project city populate based on country like this functionality requirement but i can't understand how to implement it there code is more complex to understand.
Please help me.

**Comment by volkanceylan** [comment]
I have written a how-to guide for Serenity 1.8.2

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

See it and let me know if you still have a problem.

**Comment by vijaykumar3060** [comment]
Hi Volkanceyln,

1.As per the above link for : Setup Cascaded Editors - I have issue with Multitenance implemented as you know we do not have the [LookupScript("module.task")] attribute in row files. 
2.Hence LookupEditor attribute fails in other Form files.

**Comment by volkanceylan** [comment]
So what? Use lookup key instead of row type.

**Comment by vijaykumar3060** [comment]
Yes, Worked perfectly well thank you :-)
