### ISSUE TITLE
AD Authentication Passthrough

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#561]
Volkan,
I am building my own sub template of Serene to use for internal applications.

I am trying to implement the AD example. I have it working to the point that when a user logs in the first time that it is passing them through fine and creating their account for them which is great and works well.

My problem is that I want to implement a sign on once and never bother again approach. As in I can retrieve their information fine with UserDefinition, I can also populate personalisation based on that. My sticking point is flagging them as authorised. 

If I change AccountPage:Action this:
 
public ActionResult Login(string activated)
        {
            ViewBag.Activated = activated;
            if (string.IsNullOrEmpty(Request.LogonUserIdentity.Name))
            {
                ViewBag.HideLeftNavigation = true;
                return View(MVC.Views.Membership.Account.AccountLogin);
            }
            else
            {
                // Have to allow here setting authentication for Domain Users
               // And pass them through to the called page.
            }
        }

I can trap the user if they are not on the right domain etc. But how can I pass a domain user through. Is there an authenticate call I can use that just accepts a valid username?

**Comment by volkanceylan** [comment]
Set persistent cookie in AccountPage Login method, with last parameter TRUE. They won't have to login again. If not, you may also set authentication ticket like they logged in already, with WebSecurityHelper.SetAuthenticationTicket

**Comment by solabar** [comment]
Works perfectly. Guess I was overthinking it.
