### ISSUE TITLE
Validation summary when save button is clicked

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#563]
If there are any validation errors in form, we currently show an error to fix fields marked with red, but user has to hover red marks to see actual validation errors. Need to provide a short summary of errors, and/or show popovers on editors momentarily.

**Comment by jsbUSMC** [comment]
Bootstrap has a popover library for JavaScript. It requires that the tooltip library be installed also. As long as we are using the full Bootstrap suite (I haven't checked) we should be able to use that library. If in script library, along the lines of:

```cs
// ...
if (!ModelState.IsValid)
{
    J('this').popover({
        content: "You need to enter correct data into this field!",
        title: "Required Field",
        placement: "right",
        trigger: "manual"
    });

    J('element').popover('show');
}
```

Of course, this is pretty much pseudo code but I hope that it helps point out a possible solution, or path to a solution.

**Comment by volkanceylan** [comment]
Thanks John, i'll have a look at it too.

**Comment by rolembergfilho** [comment]
Yeah,

it is was i looking for.

with an example from CustomerRow.cs, located in Dev.Serene.Web, 
how to set a custom message like "Please insert the name of the company"?

I think that a good way to take the custom message is from

        [DisplayName("Company Name"), Size(40), NotNull, QuickSearch, LookupInclude]
	[Required(ErrorMessage = "Please insert the name of the company")]
        public String CompanyName
        {
            get { return Fields.CompanyName[this]; }
            set { Fields.CompanyName[this] = value; }
        }

**Comment by volkanceylan** [comment]
I dont agree. Entering validation message for such simple cases is waste of time and resources. There is already this field is required message.

You can use AddValidationRule for others.

**Comment by rolembergfilho** [comment]
I agree with you with a vision of developer. The form show field required and alert.

But with a vision of final users, with small business that don't have time and efforts for training, it's very usefull.

For example, in my case I have a familiar small business in physiotherapy. Our employee change every year, and business rules are huge. 

For example, to made therapy for injuried arm or leg, my secretary need to know:
1 - The service will be paid by health care or private?
2- If Health care, whats max sessions allowed, with intervals of days or week

and on....

so, if the system give her a lot of information of error in field (like error in typing or whats kind of error was done), it's good, so you have more attention in who is most important: the patience.

So, I really agree with you that it's a question of attentions of final users, in any kind of business, to take a care to read the fields, to understand and typing correctly.

But, with all fast time of nowaday, I'm sure that it's confortable to users (and system admin, business admin and all) when a error message appears with a brief explanation what's happened.

In all these time with this politics, the users and business admin glad me for this attention.


Man! It's so long time that I didn't speech in english. I hope if you undestand my point of view. 

Your template is amazing. I hope one day I will help you to develop this.

**Comment by volkanceylan** [comment]
:) Thanks for detailed explanation. I'm using jQuery validate, you may look its documentation or samples for something you like. This is javascript, so anything is overridable. validateOptions method in Serenity.Externals.ts is what you should change. In some place, like ScriptInitialization.ts:

```ts
Q.Externals.validateOptions = function(options: JQueryValidation.ValidationOptions) {
}
```

Inside that function apply anything you like.

**Comment by rolembergfilho** [comment]
thanks.

I'll try do it!
