### ISSUE TITLE
Correct way to implement background service

### ISSUE THREAD

**Issue by MrPec** [volkanceylan/Serenity#564]
Hi,

I have to pull data from an external source on a regular basis.
Right now I included this service on site startup

registrar.RegisterInstance<IOrderSynchronizer>(new OrderManagement.ShopwareOrderSynchronizer());

Well, I start a thread and insert new Orders. What is the best way? Use the connection.ForTable directly, use the Repository with UnitOfWork? Or with SqlInsert(...)?

I'm a bit lost here, for example I don't know who to validate the user (I get "Access denied" when using the Repository). 

Is there an example I can follow? I also have to include a settings page and so on...

Thank you!

**Comment by volkanceylan** [comment]
In a separate thread, as there is no http request, user is null.

You need to register an ImpersonatingAuthenticationService encapsulating your own AuthenticationService, and call its Impersonate and UndoImpersonate methods to fake a user that has rights.

Serenity has a background task system. There is not a sample yet, but on todo list.

**Comment by MrPec** [comment]
Ok, thank you, I'm going to try it. Regarding the background system - is it used somewhere in serene?

**Comment by volkanceylan** [comment]
No, not yet

**Comment by MrPec** [comment]
Thank you very much! Really appreciate your work

**Comment by MrPec** [comment]
If others have the same requirement... There's already an ImpersonatingAuthorizationService in Serenity. I just did the following:

In SiteInitialization:
var registrar = Dependency.Resolve<IDependencyRegistrar>();
registrar.RegisterInstance<IAuthorizationService>(new ImpersonatingAuthorizationService(new Administration.AuthorizationService()));

And in my background service:

(Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).Impersonate("admin");
....
(Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).UndoImpersonate();

**Comment by samdubey** [comment]
@MrPec I am still getting validation / permission issues after using above code
can you please suggest what else you might have done to make it work?
