### ISSUE TITLE
Category based permissions tutorial

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#566]
Add department or use role table, and add a screen where user can set which product categories are visible to which department / roles. Then filter products based on this information.

**Comment by zerodev** [comment]
where can we find this sample

**Comment by fazanan** [comment]
Hi Jaiq,

How i can get the sample?

Thanks

**Comment by volkanceylan** [comment]
You can't there is no sample, this is an issue

**Comment by fazanan** [comment]
Oke, thanks Jaiq.

**Comment by mlutzow** [comment]
@volkanceylan, I like the idea of this sample, Thanks.

**Comment by samdubey** [comment]
waiting for this sample :8ball:

**Comment by DucThanhNguyen** [comment]
I did this but my project is a bit complex. I'm not sure if it is suitable for sample in Serene.

If you haven't started working on this issue then I can implement this sample. I would like to know your opinion on following things:
- Should we add a simple Department list (no hierarchy) or Organization tree? Each user can belong to only one or multiple departments/organiztions?
- Should we add Organzition to the Administration module (Default database) as base functionality to extend or just put it as a sample in Basic Samples/Northwind module? Which fields do you think it must has?
- Any other suggestions on implementing this?

**Comment by volkanceylan** [comment]
I think we could reuse Role table for now. In sample, user should be able to see records only belonging to his own role. For this, need a table with InsertUserId etc. fields so we can determine which record is created by whom. I did implement it a few times for some projects actually, and its pretty simple. Only problem is how to demonstrate this without having to create users, roles, records and logging in/out. So i think this should be written as a little how-to in guide.

I will eventually add an Organization table, for some new module, e.g. task management etc. It will probably be in Default database as most users needs that sooner or later. It should actually be under some schema but that is not supported in all database types we use, so not sure.

**Comment by mrajalko** [comment]
I also need similar feature, but the records filtered are not added by the user. what i need is different where conditions on individual tables defined based on user.

can someone please guide me on how to approach this.
