### ISSUE TITLE
Investigate possibility to detect SQL server version

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#567]
Currently we use 2012 as default dialect for SQL server. It is possible to detect dialect by opening a connection and executing some query. 

Even though it is clearly stated in docs, most users has problems when using an older version of Sql Server.

Maybe, we'd open a connection when dialect for a connection is queried first time.

**Comment by shaileshbc** [comment]
When we connect Sql Server through Sql Management studio, it shows Version of SQL Server.
We can use Express Profiler ( https://expressprofiler.codeplex.com ) to check what kind of command being send by Sql Management Studio to find SQL Version.
regards
Shailesh

**Comment by shaileshbc** [comment]
When we connect Sql Server through Sql Management studio, it shows Version of SQL Server.
We can use Express Profiler ( https://expressprofiler.codeplex.com ) to check what kind of command being send by Sql Management Studio to find SQL Version.
regards
Shailesh

**Comment by volkanceylan** [comment]
Thanks, i know which commands, just need to figure out when to execute this.

**Comment by volkanceylan** [comment]
Will evaluate later, not so critical
