### ISSUE TITLE
SerGen and T4 template code generation and source control

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#569]
SerGen and the T4 templates generate files and add them to the solution, but they are not marked as new files for source control. Also, If they are updating an existing file, it doesn't perform the checkout before attempting (and failing) to modifying them. Consequently, it's tough to keep the solution always up to date so that it can be built from source.

Thanks!

**Comment by volkanceylan** [comment]
Switch to GIT from TFS maybe :) I really don't know much about TFS.

**Comment by wldkrd1** [comment]
Here's a blog explaining what needs to be done for T4 templates https://philiv99.wordpress.com/2013/08/30/t4-template-tips-1-integration-with-team-foundation-server-tfs/
I think that example assumes TFS is being used; not sure how you can detect whether it's actually in use or not

**Comment by volkanceylan** [comment]
@wldkrd1 can you have a look at MultipleOutputHelper.ttinclude. There are lines with "checkout" which were commented. Uncommenting them will probably resolve your problems with TFS for .tt files.

**Comment by wldkrd1** [comment]
Nice, that works for editing existing items, but it doesn't add new items under source control. It looks like EnvDTE doesn't give you the ability to add items to a TFS workspace, only checkout/checkin items already under source control. You can use the PendAdd() method of the Workspace object, but I haven't yet found a way to retrieve the active Workspace object (the code from that blog has it hardcoded). I'll keep digging.

**Comment by wldkrd1** [comment]
Ok, so I replied 2 minutes too early. The last reply here has the answer:
http://stackoverflow.com/questions/422293/identify-current-open-workspace-through-tfs-api

**Comment by volkanceylan** [comment]
I'm planning to call tf.exe with add / checkout for sergen. But will need help from you to test, as don't have TFS

**Comment by volkanceylan** [comment]
Try with 2.0.10 sergen

**Comment by wldkrd1** [comment]
Fixed in 2.0.11 but needs PR #580 to work correctly when the user does not have TFPath configured
