### ISSUE TITLE
Add filter above grid

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#57]
How to add filter like Country and City dropdown in Northwind => Customer form and bind cascading City dropdown and filter data on grid. Please guide me step by step procedure.

**Comment by volkanceylan** [comment]
Please have a look at customercityeditor first. You may not need a custom dynamic script if you have cascading table lookups. Just include required fields using LookupInclude attribute and filter them client side

**Comment by volkanceylan** [comment]
I think you have same question in another issue. Closing this one.
