### ISSUE TITLE
Grid not appearing when imported using sergen.exe

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#570]
I have never had a problem adding new grids to serenity but this problem makes no sense to me because this is my first time having an issue like this.
![image](https://cloud.githubusercontent.com/assets/17201265/14532972/bb465ca8-0228-11e6-83d5-d79fb3620917.png)
![image](https://cloud.githubusercontent.com/assets/17201265/14532981/c2ea3718-0228-11e6-97b5-7f98278a999f.png)
![image](https://cloud.githubusercontent.com/assets/17201265/14533000/d811133c-0228-11e6-8fac-b829f8027585.png)

**Comment by volkanceylan** [comment]
Did you rebuild solution before testing this.

**Comment by swordz36** [comment]
yes. I did a clean full build and transformed all templates and I still get the same results.

**Comment by swordz36** [comment]
Made sure the table had a primary key also

**Comment by volkanceylan** [comment]
Copy paste your grid code

**Comment by swordz36** [comment]
namespace MRP3.Processing
{
    using jQueryApi;
    using Serenity;
    using System;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;

    [ColumnsKey("Processing.Claim"), IdProperty(ClaimRow.IdProperty), NameProperty(ClaimRow.NameProperty)]
    [DialogType(typeof(ClaimDialog)), LocalTextPrefix(ClaimRow.LocalTextPrefix), Service(ClaimService.BaseUrl)]
    public class ClaimGrid : EntityGrid<ClaimRow>
    {
        public ClaimGrid(jQueryObject container)
            : base(container)
        {
        }
    }
}

**Comment by swordz36** [comment]
@{
    ViewData["Title"] = Serenity.LocalText.Get("Db.Processing.Claim.EntityPlural");
}

<div id="GridDiv"></div>

<script type="text/javascript">
    jQuery(function () {
        new MRP3.Processing.ClaimGrid($('#GridDiv'), {}).init();

        Q.initFullHeightGridPage($('#GridDiv'));
    });
</script>

**Comment by volkanceylan** [comment]
Don't know all seems ok, what you get when you type MRP3.Processing.ClaimGrid in javascript console? Probably something else is overriding it. Maybe something from Typescript

**Comment by swordz36** [comment]
its undefined

**Comment by volkanceylan** [comment]
No idea. Either your script project is not building properly. See MyProject.Script.js source code under scripts/site, check if ClaimGrid class is there. Also see MyProject.Web.js file if it is overriding MRP3.Processing namespace. Try removing MyProject.Web.js include from LayoutHead.cshtml

**Comment by volkanceylan** [comment]
Also check than MyProject.Web.js file is included after MyProject.Script.js, not before

**Comment by volkanceylan** [comment]
Please reopen with more details if not resolved.
