### ISSUE TITLE
SerGen creating .bak files as read-only, then crashing because it can't access them

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#571]
![sergenerr1](https://cloud.githubusercontent.com/assets/2817543/14545479/27fad1a0-0254-11e6-850e-e93f33123306.png)

I have to manually clear the read-only flag for each of the .bak files it creates and re-run

**Comment by volkanceylan** [comment]
Sergen cant create files as readonly. Its probably tfs that makes them readonly. Can't you add this extension to ignore list in tfs?

**Comment by volkanceylan** [comment]
Oh understood, sergen copies files, as source file is readonly, bak also readonly.

**Comment by wldkrd1** [comment]
Related, sergen crashes if it can't write to its config file

**Comment by volkanceylan** [comment]
Try with 2.0.10 please. Set TFSIntegration true in config file.

**Comment by wldkrd1** [comment]
Fixed in 2.0.11, but needs PR #580 to work correctly if the user does not have TFPath configured
