### ISSUE TITLE
Customizing the TS dialogs/grids

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#572]
I'm starting to migrate my dialogs from Saltarelle to TypeScript. Works great for the simple ones, but I'd like to start tackling the slightly more complex ones, which in my case requires adding/removing toolbar buttons, adding columns and adding filters. Are those scenarios supported yet?

Thanks and fantastic work!

**Comment by volkanceylan** [comment]
All is supported, as Saltaralle and TypeScript are using same infrastructure. One little issue is there is no intellisense for overriding methods in TypeScript, so you should manually look at base class signatures. I've already migrated user and role dialog, which has toolbuttons, have a look at latest template. Others should also be trivial, as long as you find the method name and parameters from base class. I'm also gonna port all code if possible to TypeScript.
