### ISSUE TITLE
share my chinese localization file

### ISSUE THREAD

**Issue by billyxing** [volkanceylan/Serenity#573]
Don't know if someone has already shared the chinese localization file. So here is mine.  
File link: https://github.com/billyxing/Serenity/blob/bf187c1027ff25d63a13bb4833a4b60f9d66b920/Serenity.Web/Includes/Scripts/serenity/texts/user.texts.cn.json
PS: I did not translate anything related to the northwind db. There are a few lines I did not transtate as I have not figured out how to translate them more accurately. So it needs to be improved in the future.

**Comment by volkanceylan** [comment]
Thanks @billyxing, i'll try to integrate your translations in new version.

**Comment by volkanceylan** [comment]
Its in 2.0.10, thanks
