### ISSUE TITLE
 ISlickFormatter value other row

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#575]
Hi,
i have a class formatter which implements ISlickFormatter.
in method "public string Format(SlickFormatterContext ctx)....." there a way to know the value of the other rows in the grid? Maybe I should take another strategy?
Thanks in advance

**Comment by volkanceylan** [comment]
Currently it's not possible to access other rows from a formatter object. It might be in a later version. You may put your formatter function directly on column, overriding GetColumns method. There you may access rows.

**Comment by linpiero** [comment]
Thank you very much.
