### ISSUE TITLE
Error running website on Microsoft Azure 

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#577]
for Azure Database it runs into following error:

DBCC command 'CHECKIDENT' is not supported in this version of SQL Server.

**Comment by linpiero** [comment]
http://stackoverflow.com/questions/12415434/how-to-reset-identity-seed-in-sql-azure

**Comment by volkanceylan** [comment]
See second answer you should upgrade your database

**Comment by volkanceylan** [comment]
I couldn't find CHECKIDENT anywhere in Serene or Serenity, so this is probably non Serenity issue anyway.
