### ISSUE TITLE
Role permission functionality step by step guide

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#58]
Hello sir,

Please give me step by step process of edit role permission functionality in Administration section and how to disable edit permission button by specific role. Where to set button text? I've tried to set button text in site.texts.tr.json file but it can't works and in this file contain other language text set so i can't understand how to translate this text to source language(means set language).

Please help me step by step guide.

**Comment by volkanceylan** [comment]
In languages screen add a language like Indian with your two letter language code (**in**).

Don't manually translate texts in JSON files. Use translation interface to translate any text you need from English to Indian by setting source and target languages. When you save them they will be saved to a file like *Scripts/site/texts.user.in.js*. Move translated texts from that file to site.texts.in.json.

To disable edit permission button, override UpdateInterface method of UserDialog, find button by classname and add disabled class to it. You can check for user permissions in Authorization.HasPermission("XYZ") with 1.8.2+
