### ISSUE TITLE
Authorization error by calling serenity webapi in android application

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#583]
Hello sir,

I want to call serenity webapi in android application. Webapi run fine in browser but It throws following response in android application -
{"Error":{"Code":"NotLoggedIn","Message":"Authorization is required for this request!"}}

How to achieve this webapi get correct response. Please help me, my webapi detail is -
Url : http://knowtulus.azurewebsites.net/Services/Courses/Classes/List
POST /Services/Courses/Classes/List HTTP/1.1
Host: knowtulus.azurewebsites.net
Content-Type: application/json

Request :
{"Take":100,"IncludeColumns""CourseCourseName","CourseId","ClassName","Description","ClassYear"],"EqualityFilter":{"CourseId":""}}

Response :
{"Entities"{"ClassId":1,"CourseId":1,"ClassName":"11th Science","Description":"11th Science","ClassYear":1,"IsSoftDelete":false,"CourseCourseName":"Science"},{"ClassId":2,"CourseId":1,"ClassName":"12th Science","Description":"12th Science","ClassYear":1,"IsSoftDelete":false,"CourseCourseName":"Science"},{"ClassId":3,"CourseId":2,"ClassName":"CPT","Description":"This is CPT","ClassYear":1,"IsSoftDelete":false,"CourseCourseName":"Charted Accountant"},{"ClassId":6,"CourseId":2,"ClassName":"Final Group 1","Description":"Final Group 1","ClassYear":3,"IsSoftDelete":false,"CourseCourseName":"Charted Accountant"},{"ClassId":7,"CourseId":2,"ClassName":"Final Group 2","Description":"Final Group 2","ClassYear":3,"IsSoftDelete":false,"CourseCourseName":"Charted Accountant"},{"ClassId":4,"CourseId":2,"ClassName":"IPCC Group 1","Description":"IPCC Group 1","ClassYear":2,"IsSoftDelete":false,"CourseCourseName":"Charted Accountant"},{"ClassId":5,"CourseId":2,"ClassName":"IPCC Group 2","Description":"IPCC Group 2","ClassYear":2,"IsSoftDelete":false,"CourseCourseName":"Charted Accountant"}],"TotalCount":7,"Skip":0,"Take":100}

**Comment by volkanceylan** [comment]
https://gist.github.com/volkanceylan/1b124f58c1e2b4fc7c7c

**Comment by laxmanp** [comment]
Thanks,
Ok I will try it.

**Comment by laxmanp** [comment]
Hello sir, 
i tried many times by applying some changes in code and same code but it can't work.. It get response error. What is the format of  List<String> params. I have set json string in params[0] = "{ "EntityId" : "2" }" is it right.  This below line throws exception "java.lang.IllegalArgumentException: Illegal character in scheme at index 0: {"EntityId":"2"}" -
 HttpPost httpPost = new HttpPost(params.get(1));

I uses SharedPreferences for storing data in Android application. I haven't use CookieStore please give me below webapi example. I have stored Username and Password in SharedPreferences -

Username : laxmanp
Password : laxman1234

POST /services/Courses/Classes/Retrieve HTTP/1.1
Host: knowtulus.azurewebsites.net
Content-Type: application/json
Request :
{"EntityId":"2"}
url = http://knowtulus.azurewebsites.net/services/Courses/Classes/Retrieve

Response :

{"Entity":{"ClassId":2,"CourseId":1,"ClassName":"12th Science","Description":"12th Science","ClassYear":1,"IsSoftDelete":false,"CourseCourseName":"Science","CourseDescription":"Science","CourseIsSoftDelete":false}}

Please help me.

**Comment by volkanceylan** [comment]
I can't give you WebApi example, i don't use web api

**Comment by laxmanp** [comment]
Hello sir,

How to call below webservice/webapi in android application without paasing username or password. It gives error response {"Error":{"Code":"NotLoggedIn","Message":"Authorization is required for this request!"}} by sending request data  {"EntityId":"2"}  -
http://knowtulus.azurewebsites.net/services/Courses/Classes/Retrieve 

In serenity application

**Comment by volkanceylan** [comment]
I gave you example already

**Comment by laxmanp** [comment]
Plz give me hint for how authorization request check by calling web service???

**Comment by fazanan** [comment]
Could you have this sample in C# not familiar with java :)

**Comment by chiangim** [comment]
using RestSharp;
        private static void TestRestSharpClient()
        {
            var client = new RestClient("http://localhost:5000/Account/Login");
            var request = new RestRequest(Method.POST);
            request.AddHeader("Postman-Token", "f60b80e2-8378-829d-47a7-c022418b184c");
            request.AddHeader("Cache-Control", "no-cache");
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("undefined", "{ Username: \"admin\", Password: \"serenity\"}", ParameterType.RequestBody);
            client.CookieContainer = new System.Net.CookieContainer();
            IRestResponse response = client.Execute(request);
            Assert.IsTrue(response.StatusCode == System.Net.HttpStatusCode.OK);

            var hasCookies = response.Cookies.Count > 0;
            var token = response.Cookies[0].Value;

            client.BaseUrl = new Uri("http://localhost:5000/Services/Default/Servicecategories/List");
            var request2 = new RestRequest(Method.POST);
            request2.AddHeader("Postman-Token", "06c39413-0e57-cc4b-83bb-7886b6967710");
            request2.AddHeader("Cache-Control", "no-cache");
            request2.AddHeader("Accept-Language", "en-US,en;q=0.9");
            request2.AddHeader("Accept-Encoding", "gzip, deflate, br");
            request2.AddParameter("undefined", "{\"Take\":1,\"IncludeColumns\":[\"ServiceCategoryId\",\"Name\",\"ParentCategoryId\",\"Image\",\"IsActive\"]}", ParameterType.RequestBody);
            var response2 = client.Execute(request2);
            Assert.IsTrue(response2.StatusCode == System.Net.HttpStatusCode.OK);
        }
