### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#584]
In English:                    In Spanish:
New Bank         ->        Nuevo Banco       (Male)
New Account    ->        Nueva Cuenta      (Femenine)

Recommendation:

In English:                    In Spanish:
Add Bank         ->        Agregar Banco   o    Añadir Banco
Add Account    ->        Agregar Cuenta  o    Añadir Cuenta

Applies to all entities

**Comment by volkanceylan** [comment]
Spanish translations was machine based. Can you translate them using translation interface and share your users.texts.json file?

**Comment by ArsenioInojosa** [comment]
Yes, I do and I share it here.
