### ISSUE TITLE
Can I add a grid data (from memory data or db data) in a panel?

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#588]
Hi all!

I try to add a grid editor from memory data to a panel, but I do not know how to do.

A picture of what I want to achieve.

![example](https://cloud.githubusercontent.com/assets/16304015/14666280/0d4e8746-06d9-11e6-9c42-e811746f2e67.png)

Thank you

**Comment by volkanceylan** [comment]
You can add any editor you can to a dialog, to a panel

**Comment by Estrusco** [comment]
OK @volkanceylan thank you. 
I'm try. 

But I am confused in adding a grid without entity row associated to db. And adding them some rows programmatically.

**Comment by Estrusco** [comment]
Good morning. I have get this panel

![example2](https://cloud.githubusercontent.com/assets/16304015/14702173/5cd3be6e-07a9-11e6-916a-71633e356892.png)

with this code

```cs
    [...]
    [Panel, FormKey(MyTestForm.FormKey)]
    public class MyTestPanel : PropertyPanel<MyTestRow>
    {
 
        public MyTestPanel (jQueryObject container)
            : base(container)
        {

           // This code not work
           var req = new RetrieveRequest();
           req.EntityId = 1;
           MyTestService.Retrieve(req, onSuccess: e => this.Entity = e.Entity);
          
           /// this.LoadInitialEntity();
           
           MyTestRow myTestEntity = this.Entity;

           this.ById("SubmitButton").Click((s, e) =>
            {
                e.PreventDefault();

                if (!ValidateForm())
                    return;
      [...]
```

Now, I can not load a default data. the form is always empty. Here myTestEntity is correct, but how can I set the data in the form?
Where am I wrong?

Thank you

**Comment by volkanceylan** [comment]
MyTestService.Retrieve(req, onSuccess: e => this.LoadEntity(entity));

**Comment by Estrusco** [comment]
I don't have the this.LoadEntity(entity) method.

![example3](https://cloud.githubusercontent.com/assets/16304015/14703866/611a912e-07b2-11e6-8034-7ed50d7c61e8.png)

**Comment by volkanceylan** [comment]
Hmm its property panel, so propertyGrid.Load

**Comment by Estrusco** [comment]
Oh yeah! Thank you very much @volkanceylan !
