### ISSUE TITLE
Username and Password in plaintext (Post Data)

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#589]
Hi everyone;

I was profiling Serene and I've noticed that Usrname and Password are displayed in plaintext. Is there a way to prevent this or switching to HTTPS Protocol will be enough?
![serene-password](https://cloud.githubusercontent.com/assets/13295503/14667760/c11602e6-06d8-11e6-849d-01228689ee86.png)

Excuse my paranoia:) I'm new to web development  and I wanna make sure the app is secure enough.

**Comment by volkanceylan** [comment]
Yes you should enable HTTPS if you care about sniffing.

**Comment by awesomegithubusername** [comment]
Thanks volkan. I'll switch to HTTPS when the website is ready for production. Have a good day.
