### ISSUE TITLE
new development lookup cascadedfrom attr didnot work on not Row based (with diffrent manuel class) lookup script

### ISSUE THREAD

**Issue by receptuna** [volkanceylan/Serenity#59]
Hi @volkanceylan ,

Here, manuel scripts,

        public static IDynamicScript SchemaTable =
            new DbLookupScript<SchemaTableItem>("Common.SchemaTable",
                getItems: c =>
                {
                    c.Open();
                    return SqlSchemaInfo.GetTableNames(c).Select(t => new SchemaTableItem { SchemaTable = ((t.Item1 != null) ? string.Format("{0}.{1}", t.Item1, t.Item2) : string.Format("{0}", t.Item2)) }).ToList();
                })
            {
                IdField = "SchemaTable",
                TextField = "SchemaTable",
                Expiration = TimeSpan.FromHours(-1)
            };

        public static IDynamicScript SchemaTableField =
            new DbLookupScript<SchemaTableFieldItem>("Common.SchemaTableField",
                getItems: c =>
                {
                    c.Open();
                    var r = new List<SchemaTableFieldItem>();
                    foreach (var t in SqlSchemaInfo.GetTableNames(c))
                    {
                        r.AddRange(SqlSchemaInfo.GetTableFieldNames(c, t.Item1, t.Item2, true)
                            .Select(x => new SchemaTableFieldItem { FieldName = string.Format("{0}", x), SchemaTable = ((t.Item1 != null) ? string.Format("{0}.{1}", t.Item1, t.Item2) : string.Format("{0}", t.Item2)) }));
                    }

                    return r;
                })
        {
            IdField = "FieldName",
            TextField = "FieldName",
            Expiration = TimeSpan.FromHours(-1)
        };

    public class SchemaTableItem
    {
        public string SchemaTable { get; set; }
    }

    public class SchemaTableFieldItem
    {
        public string FieldName { get; set; }
        public string SchemaTable { get; set; }
    }

/// on Row

        [DisplayName("Primary Table"), Size(30), NotNull, LookupEditor("Common.SchemaTable")]
        public String PrimaryTable
        {
            get { return Fields.PrimaryTable[this]; }
            set { Fields.PrimaryTable[this] = value; }
        }

        [DisplayName("Primary Field"), Size(30), NotNull, LookupEditor("Common.SchemaTableField", CascadeFrom = "PrimaryTable")]
        public String PrimaryField
        {
            get { return Fields.PrimaryField[this]; }
            set { Fields.PrimaryField[this] = value; }
        }

its showing the table lookup , but itsnt showing tables columns, when table lookup editor value changed no error,,
![image](https://cloud.githubusercontent.com/assets/2880274/11454712/02e3db12-9640-11e5-805f-25ecc4f7b9d9.png)

same thing working working on row class lookup script.
![image](https://cloud.githubusercontent.com/assets/2880274/11454719/7043e6fc-9640-11e5-81ca-446be838953b.png)

also old manuel editor is working

    public class TableFieldEditor : LookupEditorBase<SchemaTableFieldItem>
    {
        private readonly CascadedWidgetLink<LookupEditor> _schemaTableLink;

        public TableFieldEditor(jQueryObject container)
            : base(container)
        {
            _schemaTableLink = new CascadedWidgetLink<LookupEditor>(this, p => this.SchemaTable = p.Value);
        }

        protected override string GetLookupKey()
        {
            return SchemaTableFieldItem.LookupKey;
        }

        protected override IEnumerable<SchemaTableFieldItem> GetItems(Lookup<SchemaTableFieldItem> lookup)
        {
            return base.GetItems(lookup).Where(x => x.SchemaTable == SchemaTable);
        }

        [Option]
        public string SchemaTableField
        {
            get { return _schemaTableLink.ParentID; }
            set { _schemaTableLink.ParentID = value; }
        }

        private string schemaTable;

        [Option]
        public string SchemaTable
        {
            get
            {
                return schemaTable;
            }
            set
            {
                if (schemaTable != value)
                {
                    schemaTable = value;
                    Value = null;
                    UpdateItems();
                }
            }
        }
    }

    [Imported, Serializable, PreserveMemberCase]
    public partial class SchemaTableFieldItem
    {
        [InlineConstant]
        public const string IdProperty = "FieldName";
        [InlineConstant]
        public const string NameProperty = "FieldName";
        [InlineConstant]
        public const string LocalTextPrefix = "Common.SchemaTableField";
        [InlineConstant]
        public const string LookupKey = "Common.SchemaTableField";

        public static Lookup<SchemaTableFieldItem> Lookup { [InlineCode("Q.getLookup('Common.SchemaTableField')")] get { return null; } }

        public String FieldName { get; set; }
        public String SchemaTable { get; set; }

        [Imported, PreserveMemberCase]
        public static class Fields
        {
            [InlineConstant]
            public const string FieldName = "FieldName";
            [InlineConstant]
            public const string SchemaTable = "SchemaTable";
        }
    }
}

**Comment by volkanceylan** [comment]
CascadeField a SchemaTable dememişsin, nereden bilecek hangi alana göre
süzeceğini kayıtları

2015-11-29 2:34 GMT+02:00 receptuna <notifications@github.com>:

**Comment by volkanceylan** [comment]
You didn't specify CascadeField so it tries to filter on PrimaryTable field which doesn't exist in your lookup (FieldName, SchemaTable)

**Comment by receptuna** [comment]
thanks sir, ok, i understood , iam trying with cascadefiled attr,

 but row based lookup script, It makes auto filtering only cascadefrom attr, ithink, form filed name == cascade lookup field name :)
