### ISSUE TITLE
FileUploadEditor can't be upload file more than 3 MB size?

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#590]
Hello sir,

FileUploadEditor can't be upload file more than 3 MB size. It has MaxSize attribute -
FileUploadEditor(FilenameFormat = "DownloadFiles/~", CopyToHistory = true, MaxSize=10240) but it can't work.

**Comment by volkanceylan** [comment]
See Asp.net docs

**Comment by c9482** [comment]
I have the following entry in my Web.config but attempt to upload a 151 MB file fails without error. Is there some other setting that I am missing or is there possibly a conflicting setting somewhere else?

<security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="2147483648" />
      </requestFiltering>
    </security>

**Comment by c9482** [comment]
Also, changed this setting without success:

![2016-04-28_105727](https://cloud.githubusercontent.com/assets/17013052/14892363/17b62cfe-0d30-11e6-9a7f-a2b241dfa17c.png)

**Comment by c9482** [comment]
As it turns out, the setting varies depending on the IIS version used - for IIS 5.0 and 6.0, the setting is:

```
<system.web>
  <httpRuntime maxRequestLength="1048576" executionTimeout="100000" />
</system.web>
```
