### ISSUE TITLE
Increase or decrease amount of columns during runtime

### ISSUE THREAD

**Issue by stepankurdylo** [volkanceylan/Serenity#591]
Hello Volkan,

Could You please advise me how to resolve the following problem:
I have **EntityGrid** with 3 predefined columns and I need dynamically add or remove some columns depending on the value of property, for example, **if amountOfAdditionalColumns equals to 5 - should be added additional 5 columns**.
I believe that it is not an issue related to the framework, but currently I have no idea how to resolve it during the runtime process, such as haven't got a big experience in JavaScript development.

Thank You in advance.
Stepan Kurdylo.

**Comment by volkanceylan** [comment]
You may override GetColumns() method in grid and add columns you want

**Comment by stepankurdylo** [comment]
OK.
I was trying this solution before, but grid doesn't change its properties next time - it is happening only during construction of it. Sorry for disturbing, but could You please share some piece of pseudo code for this solution?
Regards.
Stepan Kurdylo.

**Comment by volkanceylan** [comment]
If you want to change it after constructor, then use this.slickGrid.SetColumns() method

**Comment by stepankurdylo** [comment]
This is possible solution for such things. Thanks. Issue resolved.
