### ISSUE TITLE
Why images stay temporary folder when using multiple image upload editor?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#592]
If I use ImageUploadEditor image file moves related (EntityName/000/000/xyxyxyx.png) folder with renaming. But MultipleImageUploadEditor attribute puts images to temporary folder and stay there even after save entity? I dont use any parameter, there is only attrbute name

[MultipleImageUploadEditor]
public String Resimler { get; set; }

Serenity ver: 1.9

**Comment by volkanceylan** [comment]
It's probably a bug, will have a look.

**Comment by volkanceylan** [comment]
Can't reproduce this. They don't stay after save entity. They only stay if you select some file and close without saving, which works as designed. They got deleted after some time, if you have a ".temporary" in temporary folder.

**Comment by ademc** [comment]
I could. If I put MultipleImageUploadEditor to top of form property this issue occurs. But If I put MultipleImageUploadEditor to top of Row field works good. You can ty and fix if necessary you think. Thanks.

**Comment by volkanceylan** [comment]
Yes if you put it to Form, repository has no idea there is a MultipleImageUploadEditor related to that field so MultipleImageUploadBehavior can't handle uploaded images, so not only files will stay in temporary folder, they won't be uploaded / processed at all. So it has to be at row.

**Comment by amnippon** [comment]
I use MultipleFileUploadEditor in Row.cs with attr FilenameFormat = "IndividualTraining/Certificate/~"
but file could not move to IndividualTraining/Certificate folder even following folder not created.
