### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by ArsenioInojosa** [volkanceylan/Serenity#593]
Hi, 

I share my translation into Spanish. As you go using the template I'll improve it.

I have doubts about the context of these words:

Controls.EntityDialog.UndeleteButton
Controls.EntityDialog.UndeleteButtonConfirmation
Db.Administration.RolePermission.RoleRoleName
Db.Administration.User.PasswordSalt
Validation.EntituIsNotActive

# user.texts.es.json  : [https://drive.google.com/open?id=0B1qSgngdJGV7RE5lOUpOV3lMWlk](url)

**Comment by volkanceylan** [comment]
Thanks a lot, i'll include them in next version.

**Comment by volkanceylan** [comment]
Merged translations, will go out with 2.0.13, thanks again.
