### ISSUE TITLE
What do I need to override to remove the add button from the grid view

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#594]
I just want the quick search and refresh visible.

![image](https://cloud.githubusercontent.com/assets/17201265/14726272/a199cd44-07e6-11e6-8b67-a9a9b640bcef.png)

**Comment by wldkrd1** [comment]
If you're using Saltarelle, in your MaterialCodeGrid.cs in the script project:

`protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();
            buttons.RemoveAt(0);
            return buttons;
        }`

**Comment by wldkrd1** [comment]
(I made an assumption your table was called MaterialCode)

**Comment by volkanceylan** [comment]
And this question asked 10th time, even though there is a howto for it :/
