### ISSUE TITLE
Added Serenity-Attributes page to Wiki

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#595]
I write here for information, if someone wants to contribute by writing about other attributes

Added Serenity-Attributes page to Wiki.

https://github.com/volkanceylan/Serenity/wiki/Serenity-Attributes

Added some pages:
ColumnAttribute [Mapping]. 
TableNameAttribute [Mapping]. 
ExpressionAttribute [Mapping].
ForeignKeyAttribute [Mapping]. 
LeftJoinAttribute [Mapping].
SetFieldFlagsAttribute [Mapping]. 
FieldFlags Enumeration. 

and edit the Editor Types pages.

Have a nice weekend

**Comment by volkanceylan** [comment]
Thank you very much Estrusco, such contributions make me glad working on this

**Comment by Estrusco** [comment]
Oh, thank you @volkanceylan  for all this great work ;) 
For me it is a pleasure to contribute.
