### ISSUE TITLE
Error with the ExcelExportHelper

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#596]
So I just added the following to my RideALongGrid.cs in my Project.script:
![code](https://cloud.githubusercontent.com/assets/11448029/14759177/b2ec8086-08e6-11e6-96dd-bb2489833940.PNG)

how ever when I try to exported, I get the following error:

![error](https://cloud.githubusercontent.com/assets/11448029/14759173/a248118c-08e6-11e6-8303-acf651ce9699.PNG)

**Comment by volkanceylan** [comment]
Did you add ListExcel method to endpoint?

**Comment by wdhodges** [comment]
nope...testing now

**Comment by wdhodges** [comment]
I added it and received this error:

{"Error":{"Code":"Exception","Message":"Table Table1 Column Start Date does not have a unique name.","Details":"System.IO.InvalidDataException: Table Table1 Column Start Date does not have a unique name.\r\n   at OfficeOpenXml.ExcelWorksheet.SaveTables()\r\n   at OfficeOpenXml.ExcelWorksheet.Save()\r\n   at OfficeOpenXml.ExcelWorkbook.Save()\r\n   at OfficeOpenXml.ExcelPackage.GetAsByteArray(Boolean save)\r\n   at OfficeOpenXml.ExcelPackage.GetAsByteArray()\r\n   at Serenity.Reporting.ExcelReportGenerator.GeneratePackageBytes(List`1 columns, IList rows, String sheetName, String tableName, TableStyles tableStyle) in D:\\Development\\firefly\\Firefly\\Firefly.Web\\Modules\\Common\\Reporting\\ExcelReportGenerator.cs:line 18\r\n   at Firefly.ReportRepository.Render(IDataOnlyReport report) in D:\\Development\\firefly\\Firefly\\Firefly.Web\\Modules\\Common\\Reporting\\ReportRepository.cs:line 19\r\n   at Firefly.CommunicationsCenter.Endpoints.RideALongsController.ListExcel(IDbConnection connection, ListRequest request) in D:\\Development\\firefly\\Firefly\\Firefly.Web\\Modules\\CommunicationsCenter\\RideALongs\\RideALongsEndpoint.cs:line 51\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in P:\\Sandbox\\Serene\\Serenity\\Serenity.Web\\Mvc\\ServiceEndpoint.cs:line 72\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)"}}

**Comment by volkanceylan** [comment]
You have two columns with same title, Start Date

**Comment by vinaykulkarni89** [comment]
Happened same to me, but your issue helped me, thanks
