### ISSUE TITLE
How to open dialog from external page.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#597]
Hi

I have created some HTML reports using MVC. I want to serenity editing dialog  from the link on html report. How can i do it??
This is similar to use EditLink attribute in grid as below
`[EditLink(IdField="VoucherId", ItemType="Accounting.Vouchers")]`

But how i do it outside serenity in other html page?

Here is the screen shot for more information - 
https://drive.google.com/file/d/0B9UGZZFXh-e6YU9lakRwNVlaalU/view?usp=sharing

**Comment by volkanceylan** [comment]
new XYZDialog().loadByIdAndOpenDialog(12345)

**Comment by ramveersgh** [comment]
@volkanceylan 
Thanks! I do not have any code behind for this html report in script project so i am looking to do it in javascript.
So i get its js converted code which is working for me.
`(new global.Tranzol.Accounting.VouchersDialog()).loadByIdAndOpenDialog(@group.VoucherId);`

Thanks for your guidance.

**Comment by volkanceylan** [comment]
You don't need global actually.

**Comment by qfleurat** [comment]
ramveersgh, I have a question on your js code that you used on the external site to call the dialog, what files did you include in the scrip scr="..." from your serenity site to be able to call "new global.Tranzol..."?

Thanks
Quentin

**Comment by ramveersgh** [comment]
@qfleurat
I do not have external site. I have simple HTML report page which use Serenity Master. So all reference included in Serenity Master are available on this page.

For external site, Probably you need to add <projectname>.Scripts.js inside you Scripts/Site folder along with some  prerequisites like jquery etc.
Here is for me -
~/Scripts/Site/Tranzol.Script.js
