### ISSUE TITLE
Support Right to Left

### ISSUE THREAD

**Issue by roozbehzand** [volkanceylan/Serenity#598]
any way can use this themplate for right to left web application ?

**Comment by volkanceylan** [comment]
It's not so simple, but adding to todo list...

**Comment by zerodev** [comment]
Dont Know if this will help as a start 
https://github.com/mmdsharifi/AdminLTE-RTL

**Comment by volkanceylan** [comment]
This is very low priority for me atm, but i'll accept a pull request.
