### ISSUE TITLE
Now...what to do with checked rows?

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#599]
Hi community,

I am stuck at one thing.
I have implemented checkboxes to my grid.
![image](https://cloud.githubusercontent.com/assets/15879719/14768666/2a644a48-0a38-11e6-8a02-22c116aee188.png)

Now when I want to click the button to "do something with selected rows", I come short of knowledge in this genius but somewhat implicit (coding) platform.

1. I want to export the checked rows to Excel. Now the whole grid is exported when Excel is clicked.
2. I would also like to perform some sql maneuvers with the checked items.

I suspect the solution to no. 1 is somewhere hidden in the Endpoint.cs where the Excel handler is.
But that is in the web project but selected rows are in the script project.

Regarding no. 2, can I call some LINQ procedure and have an SQL Trigger in my database handle what I have to do??

I would appreciate all suggestions on this matter.

Best,
Biggi

ps. I am aware of the sample code below:

![image](https://cloud.githubusercontent.com/assets/15879719/14768679/5643cd00-0a38-11e6-8422-433d88d3fb7e.png)

**Comment by volkanceylan** [comment]
You see onViewSubmit parameter that you give to ExcelExportHelper.CreateToolButton right. Now instead of returning this.onViewSubmit() in it, do like this:

```cs
ExcelExportHelper.CreateToolButton(this, 
                CustomerService.BaseUrl + "/ListExcel", () => {
if (this.OnViewSubmit()) {
     ((ListRequest)this.View.Params).Criteria &= new Criteria("SomeField").In(rowSelectionGetSelectedKeys())
     return true;
}
else
   return false;
}
```

gotcha?

**Comment by volkanceylan** [comment]
Now for second question, see cancellable batch action sample under basic samples. It passes a list to a service endpoint, in your case this might be all checked IDs. Than do what you like in endpoint.

**Comment by biggikalli** [comment]
Hi and thank you for the quick reply.
The code sample was also well received.

I took it for a spin last night but did not succeed.
See my code with your suggestion below

`        protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();
            buttons.Add(ExcelExportHelper.CreateToolButton(this, GreidaLanService.BaseUrl + "/ListExcel", () =>
            {
                if (this.OnViewSubmit())
                {
                    ((ListRequest)this.View.Params).Criteria &= new Criteria("DEVICEID").In(rowSelection.GetSelectedKeys());
                    return true;
                }
                else
                    return false;
            }));`

Maybe you could see what is wrong with it but I get an error in a new window when using it.
![image](https://cloud.githubusercontent.com/assets/15879719/14777136/ad8e9234-0aba-11e6-98d0-6f301868a70f.png)

When I replace .GetSelectedKeys to .In(rowSelection.GetSelectedKeys(() with .ToString(), then I get an Excel file only with headers though.

Any suggestions?

Best,
Birgir

**Comment by biggikalli** [comment]
No worries - Problem solved :)
On to the next one.
