### ISSUE TITLE
Exporting form data into flat file or excel

### ISSUE THREAD

**Issue by denonc** [volkanceylan/Serenity#60]
Hi, 

I would like to write a function on exporting form data (i.e. Orders) into a flat file or excel upon clicking the save button, where can I insert the export function coding at in order to detect and trigger when the form is successfully saved?

Thanks to advise!

**Comment by volkanceylan** [comment]
If you mean on client side, override OnSaveSuccess method, for server side you can override OnReturn or OnAfterSave methods at repository level.

**Comment by denonc** [comment]
Thanks for the prompt reply, worked fine using AfterSave method at server side repository. 
One more issue, I am able to retrieve Row.CustomerID but when retrieving Row.CustomerCompanyName it shows empty. Tried using lookup itembyid but was not able to. Thanks to advise again!

**Comment by volkanceylan** [comment]
By default save handler selects only table fields of old entity for performance reasons as usually you dont need view fields for update. Override prepare query and add query.Select(fld.CustomerCompanyName)

**Comment by denonc** [comment]
Do you mean to place the override PrepareQuery(SqlQuery) in the savehandler?

**Comment by volkanceylan** [comment]
Yes, SaveHandler
