### ISSUE TITLE
Integers and decimal places

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#601]
In the grid on a page I have several numbers that don't have decimal places. both int and short. However in the edit dialog both numeric values get appended to two decimal places. Is there any way I can stop that without resorting to Masks? As in a whole number editor. I tried IntegerEditor.  I could change them to be characters but this seems counter intuitive.

**Comment by volkanceylan** [comment]
This is probably a bug related to jQuery version upgrade or changes made for TypeScript. You may try [IntegerEditor(MinValue = 0, MaxValue = 2147483647)] till this is resolved in next version.

**Comment by solabar** [comment]
Thanks Volkan, the workaround works fine.

**Comment by volkanceylan** [comment]
You're welcome, just keeping open to remember.

**Comment by volkanceylan** [comment]
Should be resolved with 2.0.12
