### ISSUE TITLE
Implement 3rd party jquery plugin

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#602]
Dear @volkanceylan,
I'm trying to add some JQuery plugin (bootbox for example) into Serenity (like you have done for toastr), but I'm a bit lost with Saltarelle.
I know that I have to add a metadata library in order to use such library from Saltarelle project, but I would like to do it in an upgrade-safe way...
My question is: I have to modify che Script.Core library of Serenity and/or extend your "Q" implementation, or there is a better/cleaner way to do that?
In fact, I would like to add plugins in a way that not prevent/broke any further Serenity platform update...

Thanks for your support
Best Regards

**Comment by volkanceylan** [comment]
I recommend you put them in MyProject.Script, and use a namespace specific to plugin or your project. This way it won't conflict with Serenity classes.

You may also put them in Serenity.Imports library and send a pull request, so i can include these imports in Serenity.

Btw, try to use TypeScript if possible as i'm probably gonna remove Script project by default, after porting all code to TypeScript. Your old code will work but new templates won't come with Saltaralle option.

**Comment by marcobisio** [comment]
Ok I'll try to switch to TypeScript and then I let you know.
Thanks for your support 
Regards

**Comment by ChenZhaobin** [comment]
@marcobisio @volkanceylan  if sometime you make it please  Integrate bootbox into serenity.script,I also need it ,and I think this is a common require to prompt an input box ! best regards to all

**Comment by marcobisio** [comment]
Dear @ChenZhaobin,
integrate bootbox in Serenity it's quite straightforward:

1) from NuGet in VS add the Bootbox.JS package (v4.4.0 currently)
2) again from NuGet add the TypeScript definition for bootbox (bootbox.TypeScript.DefinitelyTyped)
3) then add the following line in your _LayoutHead.cshtml, just before your @Html.Script("~/Scripts/Site/MY_PROJECT.Web.js"):

    @Html.Script("~/Scripts/bootbox.min.js")

4) then in your .ts (dialog for example) you can do something like:

    var box = bootbox.alert("my beautiful message");
    box.zIndex(1102);

Note that I've added the zindex instructions in order to allow the proper visibility if the alert it's created from a dialog (dialogs have zindex = 1101).

This is working fine in my project, but I suggest to wait for the opinion of the master (@volkanceylan).

Best Regards

**Comment by ChenZhaobin** [comment]
haha ,I can sniffer that TypeScript is more convenient  than Saltarelle,thank  you.

**Comment by ChenZhaobin** [comment]
@marcobisio  After TypeScript implement of bootbox  ,Can I use bootbox  in Saltarelle (MyProject.Script      Classes)?

**Comment by ChenZhaobin** [comment]
Absolutely not ,aha,I will substitution mydialog and mygrid using TypeScript,thanks a lot

**Comment by marcobisio** [comment]
you answered yourself :-)
