### ISSUE TITLE
Dialog sizing issues

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#603]
I'm seeing some weird sizing behaviors with the new typescript dialogs, specifically the form width and control widths. How is this controlled?
![exdialog1](https://cloud.githubusercontent.com/assets/2817543/14824200/f9d798aa-0b89-11e6-9702-c127b4daaab7.png)
![exdialog2](https://cloud.githubusercontent.com/assets/2817543/14824205/ff368dce-0b89-11e6-9e2b-929d68441fb9.png)

**Comment by volkanceylan** [comment]
Do you have @Serenity.Decorators.registerClass on top of your dialog classes?

**Comment by wldkrd1** [comment]
Yes, here's the first dialog definition:
`namespace ServerReview.Administration {
    
    @Serenity.Decorators.registerClass()
    export class RequestTypeReviewerTypeDialog extends Serenity.EntityDialog<RequestTypeReviewerTypeRow, any> {
        protected getFormKey() { return RequestTypeReviewerTypeForm.formKey; }
        protected getIdProperty() { return RequestTypeReviewerTypeRow.idProperty; }
        protected getLocalTextPrefix() { return RequestTypeReviewerTypeRow.localTextPrefix; }
        protected getService() { return RequestTypeReviewerTypeService.baseUrl; }

        protected form = new RequestTypeReviewerTypeForm(this.idPrefix);
    }
} `

And here's the second:
`
namespace ServerReview.Administration {
    
    @Serenity.Decorators.registerClass()
    export class ReviewerTypeReviewerDialog extends Serenity.EntityDialog<ReviewerTypeReviewerRow, any> {
        protected getFormKey() { return ReviewerTypeReviewerForm.formKey; }
        protected getIdProperty() { return ReviewerTypeReviewerRow.idProperty; }
        protected getLocalTextPrefix() { return ReviewerTypeReviewerRow.localTextPrefix; }
        protected getService() { return ReviewerTypeReviewerService.baseUrl; }

        protected form = new ReviewerTypeReviewerForm(this.idPrefix);
    }
}`

**Comment by volkanceylan** [comment]
Hmm strange, and you have css rules with .s-ReviewerTypeReviewerDialog or .s-Administration-ReviewerTypeReviewerDialog?

**Comment by wldkrd1** [comment]
I don't! Nothing in site.less for that. Manually adding those sections fixed it. I'm going to call that one a user errors since I renamed db table, form etc. and apparently neglected to update site.less. Whoops...
