### ISSUE TITLE
LookupEditor CascadeFrom vs FilterField

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#605]
Hi Can you explain to me the Difference between  CascadeField,CascadeFrom and FilterField, FilterValue and the usage Scenario  for this.

I have tried
` [LookupEditor("ProjectManagement.PayeesPerProject",FilterField="ProjNo", FilterValue="ProjNo")]`
to filter  all Payees in all projects  to show only Payees in  the current project. But I get an error:
Failed to parse SourceMap: http://localhost:53227/Scripts/Site/HSSOnline2016.Web.js.map

**Comment by swordz36** [comment]
Cascade is based on a selection from another field on your form. 

Filtering is limiting the result displayed on the UI by setting a Field and Value to filter on.

**Comment by GeorgeBarkhuizen** [comment]
Can I Reference a Row Filed  as FilterValue?   If so, How?

**Comment by swordz36** [comment]
Yes, as long as that Field has the LookUpInclude Attribute on the Row Field Property

**Comment by volkanceylan** [comment]
See basic samples for custom filtering lookups.
