### ISSUE TITLE
Add UserDisplayName to Row

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#606]
Hi 
I would like to add the current UserName to the Audit Trail Field "CreatedBy" in my table.  I managed to implement  IInsertLogRow in my xyz.row
 ```
  IIdField IInsertLogRow.InsertUserIdField
        {
            get { return Fields.CreatedBy; }
        }
```
But this only gives me the User Id.

How would I get the UserName?

**Comment by volkanceylan** [comment]
Add view field, see mapping guide

**Comment by GeorgeBarkhuizen** [comment]
I actually want to store the username in the table  not just display it on the form.  Can I save the view field back to the database?

**Comment by volkanceylan** [comment]
You can but instead remove those IInsertLogRow etc interfaces and fill in your Username fields by overriding SetInternalFields method in your SaveHandler.

**Comment by GeorgeBarkhuizen** [comment]
Can you maybe give me some sample code to retrieve the UserName  from within the SaveHandler?

**Comment by volkanceylan** [comment]
Read docs please Auth section

**Comment by GeorgeBarkhuizen** [comment]
Thanks,

In the end it was easy enough.

Here is how I implemented it and it seems to work fine.

   ```
  private class MySaveHandler : SaveRequestHandler<MyRow> 
        {
            protected override void SetInternalFields()
            {
                base.SetInternalFields();

                String username = WebSecurityHelper.HttpContextUsername;
                if (IsCreate)
                {
                    Row.CreatedBy = username;
                    Row.CreatedOn = DateTime.Now;
                   
                }
                if (IsUpdate)
                {
                    Row.ModifiedBy = username;
                    Row.ModifiedOn = DateTime.Now;
                }                                             
            }
        }
```
`

**Comment by volkanceylan** [comment]
You could also use Authorization.Username too, it works in non-http environments too

**Comment by volkanceylan** [comment]
Btw, i'd recommend ID, username might change...

**Comment by GeorgeBarkhuizen** [comment]
OK Thanks
