### ISSUE TITLE
ModelRow best practice

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#607]
Hi Volkan,

First, thank you for sharing your amazing work.

I was wondering what would be the best practice: between using the modelRow generated by sergen and creating a bunch of methods around it to manipulate the object, or recreating a parralel "more complex" model in a different library and mapping it to the model (sounds bad to me) or simply plugin superclass to mystuffRow and maybe using override.

I was going for the superclass, but I would really appreciate your expertise.

Thank You

**Comment by volkanceylan** [comment]
I'm not sure what operations you'll do on that complex model but why dont you try adding some extension methods for your ModelRow. You could also add them to row directly but it might introduce extra dependencies to your row class. Actually all business logic should go into service behaviors or repository.

**Comment by Boumboumjack** [comment]
Thank you for your answer. 
I will do this. I have to transform/check  the model and send it to another webservice, I used to do it in Matlab and files had to be split a lot to keep it clean...
