### ISSUE TITLE
Best way to filter deleted records from Lookups using IsActive property

### ISSUE THREAD

**Issue by she-ll-b-rite** [volkanceylan/Serenity#608]
Hi there. Looking for some advice on how best to do the following:
* Filter rows marked as deleted using IsActive from a Lookup, but...
* For parent rows that have had a now deleted child row assigned, I still want to be able to show for those records. 

As an example, I have a Widget that is made up of a number of Parts. I have a lookup on Parts that I only want to show current (IsActive = 1) parts when creating a Widget. But for existing Widget records that used now deleted Parts (IsActive = -1) I still want to have the Part show in the field when I view the Widget record. 

Many thx.

**Comment by swordz36** [comment]
[LookupEditor(typeof(**[yourRowHere]**Row), Multiple = true, FilterField = nameof(**[YourRowHere]**.IsActive), FilterValue = true)]

**Comment by she-ll-b-rite** [comment]
Thanks for the response. I tried this and works perfectly in filtering to only currently active Parts, but deleted parts won't show in widgets that assigned the part while it was active. Code below.

The best I could come up with is to have 2 properties pointing to the same field. One is visible only on insert which returns the filtered list and the other is only visible on update (Updatable is also set to false) which returns all rows. Was hoping there might be a more elegant solution though?

```
        [DisplayName("Distributor"), HideOnUpdate, Column("DistributorId")]
        [LookupEditor(typeof(Entities.DistributorRow), FilterField = nameof(Entities.DistributorRow.IsActive), FilterValue = 1)]
        public Int32? DistributorIdInsert
        {
            get { return Fields.DistributorId[this]; }
            set { Fields.DistributorId[this] = value; }
        }

        [DisplayName("Distributor"), HideOnInsert, Column("DistributorId"), Updatable(false)]
        [LookupEditor(typeof(Entities.DistributorRow))]
        public Int32? DistributorIdUpdate
        {
            get { return Fields.DistributorId[this]; }
            set { Fields.DistributorId[this] = value; }
        }
```

**Comment by she-ll-b-rite** [comment]
Figured out a better solution. 
Changed back to original property code in the Row entity to return all rows:

```
        [LookupEditor(typeof(Entities.DistributorRow))]
        public Int32? DistributorId
        {
            get { return Fields.DistributorId[this]; }
            set { Fields.DistributorId[this] = value; }
        }
```

Then added the following in the EntityDialog to filter to only active rows when creating a new row.

```
        protected override void AfterLoadEntity()
        {
            base.AfterLoadEntity();

            if (IsNew)
            {
                form.DistributorId.FilterField = DistributorRow.IsActiveProperty;
                form.DistributorId.FilterValue = 1;
            }
        }
```

Many thanks.
