### ISSUE TITLE
Importe data from excel and Bulk Insert  into database

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#609]
Thanks a lot for serenity,I helps me a lot ,best wishes to it!
I want implement something like importing  data from excel,then bulk insert into database，could you give me some suggestion?

**Comment by ChenZhaobin** [comment]
Current service code is below:
  [Route("ImportData")]
         public ImportFailedCollection ImportData(IUnitOfWork uow,IDbConnection connection, ListRequest request)
         { 
             var data = List(connection, request).Entities;
             List<MyRow>responseEntities=new List<MyRow> (); 
             foreach (var item in data)
             {
                 SaveRequest<MyRow> insertRequest = new SaveRequest<MyRow>();
                 insertRequest.Entity = item;
               var saveResponse= new MyRepository().Create(uow, insertRequest);
                 if(saveResponse.Error.Message !="")
                 {
                     responseEntities.Add(item);
                 }
             }
             return new ImportFailedCollection
             {
                 Entities=responseEntities 
             };
         }

**Comment by LambertW** [comment]
May be you can use some 3th part etl tools like **kettle **for import data.

**Comment by volkanceylan** [comment]
EPPlus can read excel files too.

**Comment by ChenZhaobin** [comment]
Thanks,I will implement and paste  it  here

**Comment by GeorgeBarkhuizen** [comment]
Hi,

I would like to implement the same.  Any progress?
