### ISSUE TITLE
AuditLog and CaptureLog example

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#61]
I checked up on serenity code about logging functions. I guess serenity has matured Audit Log and Capture Log abilites. Is there any example about these?

Thank you

**Comment by volkanceylan** [comment]
Not yet, but planning for capture log soon. Leaving this issue open.

**Comment by volkanceylan** [comment]
See latest commit in Serene, to understand how to enable CaptureLog for ProductRow. Currently, there is no user friendly viewer yet, though you can generate one using code generator for simple change data viewing.

I'm planning to write an user friendly log viewer.

**Comment by ademc** [comment]
Thanks a lot. I see that:

[CaptureLog("TableName","Fields")]

changed to

[CaptureLog(typeof(TableName))]

Actually logging is complicated topic. Every table has to be a log table and it is so painful process. When any field name/type change or adding new field, this change must be represent to log table exactly.

So what about a generic log table:

GenericLogTable
Id-UserId-OperationType(save/update/delete)-TableName-ChangeDate-TableLastData (json serialized)

By the way issue may be close. I'm thinking. sorry for noise :)

**Comment by volkanceylan** [comment]
If you are using migrations it is very simple, and as a bonus it allows temporal queries like give me my organization tree at that point of time, or how many active students i had at 1999. AuditLog does what you ask for, but i prefer capture log.
