### ISSUE TITLE
No data when export to excel

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#610]
Hi Jaiq,

Why i cannot find any data in excel file, I have found one data from service,
but not generated in excel file, as below

![s3](https://cloud.githubusercontent.com/assets/6382278/14874278/a77fd662-0d28-11e6-9383-99fc59853c55.png)

![s2](https://cloud.githubusercontent.com/assets/6382278/14874279/a8ffc772-0d28-11e6-8065-4060e63f4129.png)

Thanks

**Comment by ChenZhaobin** [comment]
there is no problem with this code snippet,please check your columnList Data first,maybe it only include id values.

**Comment by fazanan** [comment]
Thanks for your answer, this my column list data and my data value, how to solve this?

![s4](https://cloud.githubusercontent.com/assets/6382278/14876089/968d462e-0d3b-11e6-80c6-905ce0e08423.png)

![s5](https://cloud.githubusercontent.com/assets/6382278/14876095/a3fe5afa-0d3b-11e6-9c6a-b5e8e62dcd18.png)

**Comment by volkanceylan** [comment]
Can't reproduce this. Tried with one record, resulting excel is normal. Does it happen with more records or when only one?

**Comment by fazanan** [comment]
Both, one or many records, is maybe relate with authorization or permission?

Thanks

**Comment by volkanceylan** [comment]
Strange, does it happen also with another entity, e.g. Northwind Orders. Make sure it doesn't double call service, and have a look at contents of generated excel file, and check bytes.Length is equal to file downloaded.

**Comment by fazanan** [comment]
The same issue with order or customer export file, the bytes.length also same with the file download 3661 bytes, fyi i used serenity 1.19.10 already upgrade 1.19.28 but still same.

Thanks

**Comment by volkanceylan** [comment]
Send me XLSX please

**Comment by fazanan** [comment]
Hi Jaiq,

Very sorry for my stupidiy,  i comment some line in code below related this issue
https://github.com/volkanceylan/Serenity/issues/278, error reporting after upgrading serenity.

namespace EAS
{
    using Serenity.Reporting;
using System.Collections.Generic;

public class ReportRepository
{
    public byte[] Render(IDataOnlyReport report)
    {
        var columns = report.GetColumnList();

        var data = new List<object>();
        //foreach (var item in report.GetData())
            //data.Add(item);

        return ExcelReportGenerator.GeneratePackageBytes(columns, data);
    }
}
}

Problem solved after copy this one

namespace EAS
{
    using Serenity.Reporting;
    using System.Collections;
    using System.Collections.Generic;

    public class ReportRepository
    {
        public byte[] Render(IDataOnlyReport report)
        {
            var columns = report.GetColumnList();

            var data = new List<object>();
            var input = report.GetData();
            var list = (input as IEnumerable) ?? new List<object> { input };
            foreach (var item in list)
                data.Add(item);

            return ExcelReportGenerator.GeneratePackageBytes(columns, data);
        }
    }
}

Very sorry and appreciate for your kindly support. 

Thanks
