### ISSUE TITLE
LanguageGrid convert to typescript issue

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#612]
Hi all.

I successfully completed the migration guide to TypeScript.

Now I'm trying to convert my project LanguageGrid and LanguageDialog to typescript. I have copied the ts files (LanguageDialog.ts and LanguageGrid.ts) from Serene and (LanguageDialog.cs and LanguageGrid.cs in script project). But after compile and run, in the Language grid I get this error:

`Error: Each data element must implement a unique 'ID' property. Object at index '0' has no identity value: {"Id":1,"LanguageId":"en","LanguageName":"English"}`

Where am I doing wrong?

Thank you

**Comment by volkanceylan** [comment]
ID and Id, your id property name is wrong case sensitively

**Comment by Estrusco** [comment]
Hello @volkanceylan 
I have checked all Id entity, and these are all "Id". 
Then after debug in browser I saw that I omitted the line of code `@Html.Script("~/Scripts/Site/MyApp.Web.js")` in _LayoutHead.cshtml.
This information is missin in manual in upgrade tutorial from old version to 2.0.x.x Typescript.

Now all work.

Thank you.

**Comment by volkanceylan** [comment]
Oh sorry ill add that to guide

**Comment by Estrusco** [comment]
Thank you!
