### ISSUE TITLE
Routing to controllers

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#614]
Slightly odd one here. The code is sergen created. Everything Rebuilt fine. Navigation links have been moved.

```
using Helpdesk = MyApp.Helpdesk.Pages;

[assembly: NavigationMenu(8100, "Helpdesk", icon: "fa-phone")]
[assembly: NavigationLink(8120, "Helpdesk/Tickets", typeof(Helpdesk.TicketsController), icon: "fa-pencil-square-o")]
[assembly: NavigationLink(8121, "Helpdesk/TicketComments", typeof(Helpdesk.TicketCommentsController), icon: "fa-pencil-square-o")]
[assembly: NavigationLink(8122, "Helpdesk/TicketCategories", typeof(Helpdesk.TicketCategoriesController), icon: "fa-pencil-square-o")]
```
When I try to navigate to any of the Links I get this:

> Multiple types were found that match the controller named 'Tickets'. This can happen if the route that services this request ('Helpdesk/{controller}/{action}/{id}') does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the 'MapRoute' method that takes a 'namespaces' parameter.
> 
> The request for 'Tickets' has found the following matching controllers:
> MyApp.Helpdesk.Pages.TicketsController
> MyApp.Helpdesk.Endpoints.TicketsController 

I checked page routing and it seems fine unless I am missing something blindingly obvious. But as I said it is all Sergen code.
In TicketsPage
` [RoutePrefix("Helpdesk/Tickets"), Route("{action=index}")]`

In TicketsEndpoint:
```
 [RoutePrefix("Services/Helpdesk/Tickets"), Route("{action}")]
    [ConnectionKey("Default"), ServiceAuthorize("Helpdesk")]
```

**Comment by volkanceylan** [comment]
See if some other package added a default route.

**Comment by volkanceylan** [comment]
also search for "Helpdesk/

**Comment by solabar** [comment]
After a bunch of hunting around I managed to fix the routing. It was a confused old version of the .dlls in build that were not being properly overwitten. manually deleting them and rebuilding eventually fixed the issue.
