### ISSUE TITLE
LookUpEditor not able to filter when Multiple = true

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#615]
I am not able to figure out what is causing this issue or how to trace it down completely. I have a LookUpEditor that allows multiple selections but I cannot get it to Filter

 [FormScript("SetUp.PromotionProductDetail")]
    [BasedOnRow(typeof(Entities.PromotionProductDetailRow))]
    public class PromotionProductDetailForm
    {
        [LookupEditor(typeof(ProductRow),Multiple = true, FilterField = nameof(ProductRow.Fields.IsActive), FilterValue = true)]
        public List<int> Products { get; set; }

![image](https://cloud.githubusercontent.com/assets/17201265/14898321/ca01afbc-0d4b-11e6-8df0-5cc49871aecb.png)
![image](https://cloud.githubusercontent.com/assets/17201265/14898343/d7c2d022-0d4b-11e6-8292-836aab0580ec.png)

**Comment by volkanceylan** [comment]
Try FilterValue = 1

**Comment by swordz36** [comment]
I tried that also 
![image](https://cloud.githubusercontent.com/assets/17201265/14901944/a27120a6-0d5d-11e6-81c7-dc37e7871e73.png)
  But it still returns no results found

**Comment by volkanceylan** [comment]
[LookupInclude]

**Comment by swordz36** [comment]
Thanks that has now been committed to memory
