### ISSUE TITLE
Usage of Serenity.CodeGenerator.config

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#616]
Please give some hints on using Serenity.CodeGenerator.config

For example, 
How can we change BaseRowClass for Row and RowFields
How can we exclude some fields which is the the BaseRowClass.

Thanks.

**Comment by dfaruque** [comment]
Thank you.

**Comment by volkanceylan** [comment]
Here it is

https://volkanceylan.gitbooks.io/serenity-guide/content/sergen/code_generator_sergen.html
