### ISSUE TITLE
Can view uploaded documents without signing in

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#617]
So I found that if you know the exact URL to an uploaded document then you can view it / download it without going through any type of permission. Is this a bug? I tested this by opening a pdf, copied the link and the closed all browser windows and opened an incognito browser and was able to navigate right to the PDF.

**Comment by volkanceylan** [comment]
This is not a bug, URL is random, so if you got file before, you got it, and can share it with anybody you like.

**Comment by wdhodges** [comment]
Ahh, thanks for the clarification!
