### ISSUE TITLE
Client-side permission checking problem

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#620]
I'm trying to check permissions on the client, but the Permissions don't seem to be coming across.
Here's what I have in my dialog.ts file:
`if (!Authorization.hasPermission("Review:Review:Modify")) {`

That eventually calls `t.get_userDefinition().Permissions[n]` where n = "Review:Review:Modify"
Q.getRemoteData("UserData") returns an object with a Permissions property which is not null, but it doesn't appear to hold any data either. 

The user is a member of a role which has that permission. Any ideas what I'm missing?

**Comment by volkanceylan** [comment]
Does it return different results for a user with explicit permissions?

**Comment by wldkrd1** [comment]
Yes; it works if the user is granted explicit permissions, doesn't if inherited through the role.

**Comment by volkanceylan** [comment]
Shouldn't be, as user permissions are passed to script in UserEndpoint.cs with Authorization.HasPermission call. If this is not working properly it means PermissionService has a problem too.
```cs
                    foreach (var permissionKey in permissionsUsedFromScript)
                    {
                        if (Authorization.HasPermission(permissionKey))
                            permissions[permissionKey] = true;
                    }
```

**Comment by wldkrd1** [comment]
I'm not able to break into this section. It jumps straight from result.Permissions assignment to  return result (where result.Permissions is empty):
`result.Permissions = TwoLevelCache.GetLocalStoreOnly("UserPermissions:" + user.Id, TimeSpan.Zero,
                UserPermissionRow.Fields.GenerationKey, () =>
                {
                    var permissions = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);

                    if (permissionsUsedFromScript == null)
                    {
                        permissionsUsedFromScript = new UserPermissionRepository().ListPermissionKeys().Entities
                            .Where(permissionKey =>
                            {
                                // this sends permission information for all permission keys to client side.
                                // if you don't need all of them to be available from script, filter them here.
                                // this is recommended for security / performance reasons...
                                return true;
                            }).ToArray();
                    }

                    foreach (var permissionKey in permissionsUsedFromScript)
                    {
                        if (Authorization.HasPermission(permissionKey))
                            permissions[permissionKey] = true;
                    }

                    return permissions;
                });`

**Comment by wldkrd1** [comment]
Breakpoints in PermissionService.HasPermission(), GetUserPermissions() and GetRolePermissions() aren't being hit either when the dialog is opened, though they are hit when the grid is loaded for the ReadPermissions() assigned for the row.

**Comment by volkanceylan** [comment]
Yes because they are cached. You need to save web.config or clear cache

**Comment by wldkrd1** [comment]
Saved web.config, cleared cache. No change, still not retrieving Role permissions

**Comment by volkanceylan** [comment]
Ok, i'll have a look myself, please make sure you use same code for UserPermissionService

**Comment by volkanceylan** [comment]
Hmm there is something wrong with display of permissions in latest version

**Comment by volkanceylan** [comment]
Alright, found the bug:

```
            result.Permissions = TwoLevelCache.GetLocalStoreOnly("UserPermissions:" + user.Id, TimeSpan.Zero,
                UserPermissionRow.Fields.GenerationKey, () =>
```

I used same key for UserPermissionService and UserData, so one was returning other. 

Replace "UserPermissions:" with "ScriptUserPermissions:" in UserEndpoint.cs. Funny nobody noticed this before, including me

**Comment by wldkrd1** [comment]
Yup, that fixed it. Thanks!

**Comment by JohnRanger** [comment]
Had exactly the same error. This fixed it!
