### ISSUE TITLE
Typescript grid not showing IncludeDeletedToggle for rows implementing IIsActiveDeletedRow

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#622]
Definition of my row:
`public sealed class ReviewRow : Row, IIdRow, INameRow, IIsActiveDeletedRow`

manually calling this in the grid:
`constructor(container: JQuery) {
            super(container);
	        super.createIncludeDeletedButton();`

toggle button doesn't show up.

Manually calling this in the constructor does show the button since it isn't querying the isActive property first:
`Serenity.GridUtils.addIncludeDeletedToggle(this.toolbar.element, this.view, null, false);`

Anything I'm missing?

**Comment by volkanceylan** [comment]
Did you override getIsActiveProperty in grid?

**Comment by wldkrd1** [comment]
No; here's the complete definition of my grid:

`@Serenity.Decorators.registerClass()
    export class ReviewGrid extends Serenity.EntityGrid<ReviewRow, any> {
        protected getColumnsKey() { return 'Review.Review'; }
        protected getDialogType() { return ReviewDialog; }
        protected getIdProperty() { return ReviewRow.idProperty; }
        protected getLocalTextPrefix() { return ReviewRow.localTextPrefix; }
        protected getService() { return ReviewService.baseUrl; }

        constructor(container: JQuery) {
            super(container);
	        //super.createIncludeDeletedButton();
			Serenity.GridUtils.addIncludeDeletedToggle(this.toolbar.element, this.view, null, false);
        }
		protected createToolbarExtensions() {
			super.createToolbarExtensions();

			let auditOpt: Serenity.LookupEditorOptions = {
                lookupKey: 'Review.Audit'
            };
			this.addEqualityFilter(Serenity.LookupEditor).call(this, "AuditId", "Audit", auditOpt, null);

			let revTypeOpt: Serenity.LookupEditorOptions = {
                lookupKey: 'Administration.ReviewerType'
            };
			this.addEqualityFilter(Serenity.LookupEditor).call(this, "ReviewerTypeId", "Reviewer Role", revTypeOpt, null);

			let reviewerOpt: Serenity.LookupEditorOptions = {
                lookupKey: 'Administration.Reviewer'
				//,cascadeFrom: 'ReviewerTypeId'
            };
			this.addEqualityFilter(Serenity.LookupEditor).call(this, "ReviewerId", "Reviewer", reviewerOpt, null);

			let decisionOpt: Serenity.LookupEditorOptions = {
                lookupKey: 'Administration.DecisionType'
            };
			this.addEqualityFilter(Serenity.LookupEditor).call(this, "DecisionTypeId", "Decision Type", decisionOpt, null);
			
		}
    }`

**Comment by volkanceylan** [comment]
Without IsActiveProperty, it shouldnt show that toggle

**Comment by wldkrd1** [comment]
Yup, that's what I was missing. Thanks!
