### ISSUE TITLE
Replay grid LookupEditor (Select2)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#624]
Dear @volkanceylan, 
I was wondering if there is a way to replace the Select2 component with another one, but only in a grid page (not applicaton wide).

Thanks for your support
Regards

**Comment by volkanceylan** [comment]
You can use any component, what is the problem you are having?

**Comment by marcobisio** [comment]
Honestly I don't know where I have to put the screwdriver...
Until now I had always used the lookupeditor with the following syntax:

    protected override void CreateToolbarExtensions()
    {
    base.CreateToolbarExtensions();
    
    AddEqualityFilter<LookupEditor>(Fields.Country,
    options: new LookupEditorOptions { LookupKey = "Northwind.CustomerCountry" });
    
    AddEqualityFilter<LookupEditor>(Fields.City, options: new LookupEditorOptions
    {
    LookupKey = "Northwind.CustomerCity",
    CascadeFrom = Fields.Country,
    Multiple = true
    });
    }

But in ordet to "tell" Serenity to user another kind of component what I supposed to do?
I have to define a new LookupEditor?
Btw I'm trying to use something like that: http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/

I know that is a bit old, but it's a specific requirements from our customer...

Thanks as always for your precious support
Best Regards

**Comment by volkanceylan** [comment]
See this howto:

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_use_a_third_party_plugin_with_serenity.html

I used bootstrap multiselect plugin but if you want that ui-multiselect one, steps should be pretty similar.

**Comment by marcobisio** [comment]
This is exactly what I'm looking for!!!
This bootstrap component seems to be even better!
Thanks again @volkanceylan, I'll try to put all pieces togheter and I let you know!

Best Regards

**Comment by marcobisio** [comment]
Dear @volkanceylan,
successfully implemented, but now in the ServerImports I have this:
![image](https://cloud.githubusercontent.com/assets/17425690/14956314/5c08b410-107f-11e6-9e84-82238225cafb.png)

How can I fix this (namespace?) issue?
I'm trying to add an include instruction in the ServerImports.tt, but seems not working anyway...

Thanks
Regards

**Comment by volkanceylan** [comment]
Use same namespace with your project

**Comment by marcobisio** [comment]
I tried both xyz.Northwind or xyz, but without any luck...

Viceversa, for the equality filter can you give me a hint?
This is what I'm doing:

    protected createToolbarExtensions(): void {
    super.createToolbarExtensions();
    super.addEqualityFilter<BSMultiSelectEditor>(...);
    }

thanks again

**Comment by marcobisio** [comment]
I don't know what happened but I have closed and reopened visual studio and now it's ok O_O
Btw I need help only with the grid level equalityfilter...the syntax it's a bit tricky...

thanks again

**Comment by volkanceylan** [comment]
```ts

            this.addEqualityFilter(BSMultiSelectEditor).call(this, "YourField", "Title", <BSMultiSelectEditorOptions>{}, e => {
                let val = Serenity.EditorUtils.getValue(e.widget);
                if (e.active = !!(val && val.length))
                    e.request.Criteria = Serenity.Criteria.join(e.request.Criteria, "and",
                        [[e.field], "in", [val]]);
            });
```

**Comment by marcobisio** [comment]
Thank you very much!
Best Regards

**Comment by volkanceylan** [comment]
Yes syntax is bad, wasn't designed for TypeScript, will change in later version

**Comment by marcobisio** [comment]
No problem: fortunately I know who to ask questions ; -) 
I'm joking: thank you very much for all your support!

**Comment by marcobisio** [comment]
Once again, rebuild all projects, transformed all templates and this is the same problem as before:
![image](https://cloud.githubusercontent.com/assets/17425690/14981297/76672594-112e-11e6-97b8-966d2445d8bf.png)

I don't know why sometime this errors pop up again...i double checked the namespace, but it's correct...

**Comment by volkanceylan** [comment]
Write an import class for your BSMultiSelectEditor in Saltaralle. See UserDialog etc imports

**Comment by marcobisio** [comment]
The equality filter is still not working:
![image](https://cloud.githubusercontent.com/assets/17425690/14983361/0c8a7a72-113d-11e6-845b-8daa24d1a64f.png)

![image](https://cloud.githubusercontent.com/assets/17425690/14983368/22489b28-113d-11e6-8583-35dbb4f4cbd1.png)

Any idea?

Thanks

**Comment by volkanceylan** [comment]
< BsMultiSelectOptions > { lookupKey: "asdasdasd" }

**Comment by marcobisio** [comment]
sorry but I'm very uncomfortable with this syntax...

**Comment by volkanceylan** [comment]
np, me too :)
