### ISSUE TITLE
Use Bootbox prompt from a dialog

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#625]
Dear @volkanceylan,
first of all sorry for the two concurrent issues, but are different argument so I preferred to create two distinct ones.
Btw I have successfully upgraded Serenity to the last version and also I have enabled the Typescript support.
Now I'm trying to use Bootbox (http://bootboxjs.com/) like a "Q.confirm()", but obviously with the Bootbox component.
I was able to call a bootbox prompt from typescript in the following way:

    buttons.push({
    title: "Reject",
    hint: "Reject Ticket",
    cssClass: "lock-button",
    onClick: () => {
    if (!this.validateForm()) {
    return;
    }
    bootbox.prompt("blabla", function (result) {
    console.log(result);
    });
    }
    });

but the prompt seems to be in background (the dialog is modal) and therefore I cannot interact with the bootbox prompt until I close the dialog.
I'm doing something wrong or this is the expected behaviour and I need to solve the problem in another way?

Thanks for your support
Regards

**Comment by volkanceylan** [comment]
You should override its CSS to make its z-index higher than ui-front, e.g. 1000 etc.

**Comment by marcobisio** [comment]
Copy that!
Thanks
Best Regards
