### ISSUE TITLE
ReloadLookup only works for delete not for create / update

### ISSUE THREAD

**Issue by 4lamosky** [volkanceylan/Serenity#626]
protected override void InternalRefresh()
        {
            base.InternalRefresh();
            Q.ReloadLookup("MyModule");
            var rowCnt = MyModuleRow.Lookup.Items.Count(x => x.Id == kdId);
            titleDiv.Children().Text("Title - " + rowCnt );
        }
this only works for delete not for create/update.

After delete record rowCnt updated but not when create.

try to read Rows.Count with the same result.
Regards

**Comment by volkanceylan** [comment]
There is no difference between delete or update. Your InternalRefresh probably not called. Add Q.Log, Q.Notify etc to see. Also, reloading lookup is not a good idea to get a count.

**Comment by 4lamosky** [comment]
I see in my Console.Writeline.... that record not changed but called.
In your dashboard page total Customers not changed when you add some new record .
is it the same problem or i'm missing something in your manual?

**Comment by 4lamosky** [comment]
![2016-05-01_200537](https://cloud.githubusercontent.com/assets/18552029/14941935/3382e2a6-0fd8-11e6-9d90-4743fb16b089.png)

**Comment by volkanceylan** [comment]
Numbers on Dashboard page change only when you change an Order or wait 3 minutes.

            var cachedModel = TwoLevelCache.GetLocalStoreOnly("DashboardPageModel", TimeSpan.FromMinutes(5),
                OrderRow.Fields.GenerationKey, () =>

Here caching is dependent on OrderRow grouping cache key, not customer. It also doesn't change if you add 20 customers and delete one.

How your lookup is defined, and does your row has TwoLevelCached attribute on it?

**Comment by volkanceylan** [comment]
Btw, is this screen editing interface for Penerbit.lsmn entity? Or some related table?

What's this?

MyModuleRow.Lookup.Items.Count(x => x.Id == kdId)

**Comment by 4lamosky** [comment]
i'm trying to get max from Ismn table, for this example i use count  first to make sure that this lookup works properly. 

IsmnRow.cs:
 [LookupScript("Penerbit.Ismn")]

var rowI = IsmnRow.Lookup.Items.Count(x => x.Id == kdId);

Console.Writeline(rowl)

**Comment by volkanceylan** [comment]
What is x.Id == kdId, what is kdId

**Comment by 4lamosky** [comment]
var kdId = Lookup value from other table

**Comment by 4lamosky** [comment]
I found solution for this..
Thanks a lot...

**Comment by stixoffire** [comment]
@4lamosky I would like to see the solution as to how you got the data back to the grid. I want to get last record back to grid and this thread seemed so promising until I got to - I found solution - with no sample ..
