### ISSUE TITLE
AddEqualityFilter title setting

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#627]
I was wondering about the AddEqualityFilter setting title. 

![image](https://cloud.githubusercontent.com/assets/11448029/14949607/774560ae-1019-11e6-8e39-518b02f2c13f.png)

When I use the title, is that the title of what is to be displayed in the grid? Or am I misreading this or using it wrong?

**Comment by volkanceylan** [comment]
It is the title of filter, not column

**Comment by wdhodges** [comment]
Right but when I run my application, this is what I see:

![image](https://cloud.githubusercontent.com/assets/11448029/14950458/c0425630-101f-11e6-8da1-a994adb6be17.png)

which isn't what I set the filter name as

**Comment by volkanceylan** [comment]
What is Serenity version

**Comment by wdhodges** [comment]
1.9.25

**Comment by volkanceylan** [comment]
Fixed in later versions, you should update

**Comment by wdhodges** [comment]
Aye it's in my JIRA for this sprint
