### ISSUE TITLE
Date Range Filter Issue

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#628]
Hi,

I just want to find out if there is a know issue relating to the DateRange Filter.  It seems to return incorrect values. Below I am filtering an a date range from 2015-04-01 to 2016-04-01 but I a gettting values back that falls outside this range. 

![image](https://cloud.githubusercontent.com/assets/18344607/14954365/19dd5918-1072-11e6-9c79-81117787c344.png)

**Comment by volkanceylan** [comment]
Do you use DisplayFormat on columns, if so your culture might be yyyy-dd-MM while columns yyyy-MM-dd

**Comment by GeorgeBarkhuizen** [comment]
No I am not using DisplayFormat on columns I am only using culture en-ZA

**Comment by volkanceylan** [comment]
Try writing 2015/01/04 there

**Comment by GeorgeBarkhuizen** [comment]
The filter works when I write it as 2015/01/04 but on the Calendar control this represents 4 January 2015 and it should be 1 April 2015.

**Comment by volkanceylan** [comment]
Please type Q.Culture in chrome console and share its contents.

**Comment by GeorgeBarkhuizen** [comment]
Q.Culture

Object {decimalSeparator: ".", dateSeparator: "/", dateOrder: "ymd", dateFormat: "yyyy/MM/dd", dateTimeFormat: "yyyy/MM/dd HH:mm:ss"}dateFormat: "yyyy/MM/dd"dateOrder: "ymd"dateSeparator: "/"dateTimeFormat: "yyyy/MM/dd HH:mm:ss"decimalSeparator: "."get_groupSeperator: get_groupSeperator()__proto__: Object

**Comment by volkanceylan** [comment]
It seems fine but i still suspect your date picker use yyyy/dd/mm because on the fifth line 2015/02/25 is shown. This is probably related to jquery ui datepicker culture doesnt match yours. As there is no en-ZA culture in jquery ui datepicker, or different.
