### ISSUE TITLE
BeforeSave() event is not executed for Memory Grid.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#629]
Hi

I have implemented a memory grid and i want to execute a stored procedure before saving / deleting row from memory grid in database.
I tried to override BeforeSave() in Repository.cs  but it is not working.
How i can do this?

**Comment by volkanceylan** [comment]
Write a behavior, see multi tenant guide

**Comment by ramveersgh** [comment]
@volkanceylan 
Thanks for your help, It worked.
I already gone through the multi tenant guide but could not map my requirement could solve with custom behavior...
Thanks for guidance... I will take care more for doc while reading them :-):-)

**Comment by volkanceylan** [comment]
You're welcome. Unfortunately repositories are not not called by MasterDetailBehavior, so you needed to use behavior for this. I'll probably find a way to locate repositories later.
