### ISSUE TITLE
[Question]Can't Deploy to IIS?

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#63]
I've attempted to deploy this to a local IIS in the attempt to make it a intranet style website. I get an error on the <handler> on the web.config. I'm new at using Serenity, does anyone have any tips?

**Comment by VictorTomaili** [comment]
Be more specific please. for identify error we are need error details.

**Comment by wdhodges** [comment]
When I go to publish the website, (For this I just created a new Serene project, built and ran it prior to publishing it.) I select Custom > File System > Target Location = `X:\IIS\www\MSGN`. It deploys to the file system, I then go to webmatrix to run the site and this is what I get:

![error](https://cloud.githubusercontent.com/assets/11448029/11526826/2c76071c-98ab-11e5-8952-8b9fb1ed4c0c.png)

I'm trying to make this an intranet style website but it's different than other ASP.NET websites that I have come across. Mind you, I just found this platform last night.

**Comment by wdhodges** [comment]
Can this platform run from a file system style of publishing?

**Comment by volkanceylan** [comment]
Did you convert it to application in IIS and is asp.net installed from windows features or using aspnet_regiis.

**Comment by volkanceylan** [comment]
Btw www folder should have contents of MyApplication.Web

**Comment by wdhodges** [comment]
I'm new to all of this, so how do I convert it to application? In IIS just
select the "add application"? And asp.net is installed with my vs 2015.

**Comment by volkanceylan** [comment]
Yes add application.

Serenity is no different then ordinary Asp.Net application. There are no special deployment steps.

You might only have problem with sql local db as IIS doesnt run on your context. You may need to use Sql express, or setup IIS to load user profile but it is beyond scope of explaining here.

**Comment by wdhodges** [comment]
Okay, sounds good. Is there a way to change the default connection string
to do everything on my own sql server? Basically pull everything from the
"DefaultDB" and have it do the exact same on my server database? I've been
reading the manual but there wasn't a clear description on how to do that.

**Comment by volkanceylan** [comment]
Just change connection string. Thats all. Migrations by default wont run in your database if not localdb. Remove this check in SiteInitialization, and you are all set.

**Comment by wdhodges** [comment]
Alright, I'll give that a try tonight. Thank you! Also, sorry for all the
questions. I followed your tutorial on how to make the new additions to the
platform. What I couldn't figure out was how to add it to where I can set
the user permissions to allow just that one section. Like it allows you to
set access to Northwind for example.

**Comment by volkanceylan** [comment]
There are Northwind:General and Northwind:Customer permission keys, Northwind group is automatically shown in edit permissions dialog. It is not defined anywhere, it is implicitly calculated from permission keys, parsing colons.

So if you want, let's say MyModule, use permission keys on rows or services like

MyModule:General
MyModule:Something
MyModule:Else

and it will show them under MyModule group.

**Comment by wdhodges** [comment]
Outstanding! Thank you for your speedy response and generosity in answering
my questions.

**Comment by ShayneJud** [comment]
Should "Pass-through authentication" be used as the app user? Or, set a specific user? (If so, what are the ramifications of choosing a Local versus AD user.) In the near future I will switch my authentication for this Application to AD, if that matters. This site is an "Intranet" site. (Windows Server 2016 and IIS version 10.)

**Comment by ShayneJud** [comment]
This is the only "Web Site" (Web Application) running on this IIS Server. So, I would like to simply have a single Web Site/Application. Is there a "guide" anywhere on setting it (IIS and Serenity ASP app) up "from scratch"?

**Comment by havvanur160401046** [comment]
![image](https://user-images.githubusercontent.com/24252615/102503488-d3ee2500-4090-11eb-8695-8926afe0f68a.png)

Serenity uygulamamı IIS yüklediğimde bu şekilde bir hata alıyorum sebebi nereden kaynaklı olabilir
