### ISSUE TITLE
Sample: Token Authentication Required for Exposing Service Endpoint to Mobile Apps

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#630]
Hello Volkanceylan,

Can you guide me where to write authentication filter for token authentication which can work seamlessly with existing forms ( cookie) authentication in Serenity Application

Api layer should get accessed by Mobile (Android / iOS) using token authentication

Thanks,

Sameer

**Comment by volkanceylan** [comment]
Cookie auth is also a token authentication. I dont have a sample for this. Any MVC token auth filter you find in internet should work with Serenity as well.

**Comment by NikunjGadhiya07** [comment]
Hello @samdubey, have you any solution for this question? I used serenity API in kotlin android(retrofit). using that API login successfully done. but, In another API for fetching data, I got **Authorization is required for this request!**.

**Comment by samdubey** [comment]
@NikunjGadhiya07 I have successfully implemented Serenity in Android Application, I am using CookieContainer to store cookie which i am using to pass along with api request to access the data.

**Comment by mjacoup** [comment]
> @NikunjGadhiya07 I have successfully implemented Serenity in Android Application, I am using CookieContainer to store cookie which i am using to pass along with api request to access the data.

Can you please share with us the android code used to consume serenity API !! and if you have to authenticate first for every single request ???

**Comment by baliuzao** [comment]
Hi guys, 
Did you make it?

**Comment by samdubey** [comment]
Hello @baliuzao @NikunjGadhiya07 @mjacoup 
I have successfully implemented token authentication with Serenity

Option 1:

Using serenity as it is using Cookie Authentication, where we use CookieContainer class to store cookies after authentication is successful and passing same cookie in every subsequent request.

Option 2: Token Authentication

Implemented JWT Token Authentication with Serenity where I will be generating First Token by passing username and password and retrieving AuthToken from Service

Then passing this AuthToken in every subsequent request to get data / post data to serenity services.

Option 3: I have successfully implemented Identity Server 4 for Serenity with Existing cookie Authentication yet to implement token authentication with IdentityServer and Serenity.

I will post code for all above option soon, may write wiki section.

**Comment by ILAOHE** [comment]
@samdubey thanks，When can I release the code？

**Comment by samdubey** [comment]
> Hello @baliuzao @NikunjGadhiya07 @mjacoup
> I have successfully implemented token authentication with Serenity
> 
> Option 1:
> 
> Using serenity as it is using Cookie Authentication, where we use CookieContainer class to store cookies after authentication is successful and passing same cookie in every subsequent request.
> 
> Option 2: Token Authentication
> 
> Implemented JWT Token Authentication with Serenity where I will be generating First Token by passing username and password and retrieving AuthToken from Service
> 
> Then passing this AuthToken in every subsequent request to get data / post data to serenity services.
> 
> Option 3: I have successfully implemented Identity Server 4 for Serenity with Existing cookie Authentication yet to implement token authentication with IdentityServer and Serenity.
> 
> I will post code for all above option soon, may write wiki section.

Code For Option 1:
https://github.com/samdubey/SerenityApiAccessCookieAuthentication

Code For Option 2:
Will be added shortly

Code for Option 3:
https://github.com/Antargyan/Serenity-IdentityServer4-Integration

**Comment by Nathan2020-0126** [comment]
@samdubey 
I have tried with your solution https://github.com/samdubey/SerenityApiAccessTokenAuthentication
I have success got the token. But when I try to post another API with send token back, I always got Error Code with NotLoggedIn.
![图片](https://user-images.githubusercontent.com/16734387/75881756-a9f9a800-5e5a-11ea-9d8b-3217de0e3dfb.png)

**Comment by Nathan2020-0126** [comment]
I also tried with your code, also got the same error.
![图片](https://user-images.githubusercontent.com/16734387/75882457-3062b980-5e5c-11ea-82b3-b65e95153480.png)

**Comment by samdubey** [comment]
you must create another endpoint from existing CustomerEndPoint as below:
You need to add following and remove existing permissions from Serenity to make it work
 **[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]**
    [Route("Api/Services/Northwind/Customer/[action]")]
    [ConnectionKey(typeof(MyRow))]
    public class CustomerApiController : ServiceEndpoint
    {

**Comment by samdubey** [comment]
It has no effect on Authorization, It works flawlessly
It only enables you to use Token Authentication for that service

**Comment by Metanoy** [comment]
@samdubey I cloned this > https://github.com/samdubey/SerenityApiAccessTokenAuthentication but I a 400 bad request error when I try to hit the GenerateToken nethod from postman


![image](https://user-images.githubusercontent.com/24276385/114154307-8b4cc700-9920-11eb-90c1-c4cd4f825539.png)

**Comment by VictorTomaili** [comment]
@Metanoy please use discussions
