### ISSUE TITLE
Migrate code from Saltarelle to Typescript

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#631]
Dear @volkanceylan,
I'm progressively migrating all previous Saltarelle code in the Typescript syntax, but I don't know how to reference my custom ListRequest (TicketListRequest in the following code).

![image](https://cloud.githubusercontent.com/assets/17425690/14986846/c6f230e8-114d-11e6-8781-6f27c0dd3b2a.png)

I tried almost every combination with/without namespaces, but without any luck...

Thanks

**Comment by volkanceylan** [comment]
Casting in TypeScript is 
```ts
(< TicketListRequest >this.view.params) 
or 
(this.view.params as TicketListRequest)
```

**Comment by marcobisio** [comment]
Copy that!

Thanks
