### ISSUE TITLE
HtmlContentEditor causing a 'Permission Denied' error in IE

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#632]
If a dialog form includes a HtmlContentEditor, a Permission Denied error will be written to the console when the dialog is opened.

**Comment by volkanceylan** [comment]
Can't reproduce this. What service / url / script etc returns this Permission Denied error.

**Comment by wldkrd1** [comment]
It's not an error from a service or script; it's probably an error when trying to manipulate the DOM. And I just confirmed it is happening in IE11 and not FireFox. Here's what I see:

SCRIPT70: Permission denied
File: RequestType, Line: 61, Column: 288

The dialog is simple enough:

```
[FormScript("Administration.RequestType")]
    [BasedOnRow(typeof(Entities.RequestTypeRow))]
    public class RequestTypeForm
    {
        public String Name { get; set; }
        [HtmlContentEditor]
        public String Description { get; set; }
    }
```

**Comment by wldkrd1** [comment]
The functionality of the dialog is fine; it behaves as expected, near as I can tell. This is probably low priority.

**Comment by volkanceylan** [comment]
This is IE bug, https://connect.microsoft.com/IE/feedback/details/802251/script70-permission-denied-error-when-trying-to-access-old-document-from-reloaded-iframe

**Comment by wldkrd1** [comment]
I'm closing it, then...seems unlikely that MS will fix this bug and it appears to be a cosmetic annoyance.
