### ISSUE TITLE
How to get response back and bind it to text box at client side

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#634]
![afterfill](https://cloud.githubusercontent.com/assets/16666095/15006929/24084c32-11f2-11e6-98dd-b3cdc12d3241.png)

Hi volkan , here is my form for **Product Key generation** , I am posting value to controller action method **Create** of this form and returning **response** back. 
How to get response back and bind it to **Product Key** text box at client side in .script project .
Also give reference code on ,  how to **Send Email** and  **Send SMS**  to send email and sms.

```

namespace SereneORS.GenerateSerials
{
    using jQueryApi;
    using jQueryApi.UI.Widgets;
    using Serenity;
    using System.Collections.Generic;

    [IdProperty(GenerateKeyRow.IdProperty), NameProperty(GenerateKeyRow.NameProperty)]
    [FormKey("GenerateSerials.GenerateKey"), LocalTextPrefix(GenerateKeyRow.LocalTextPrefix), Service(GenerateKeyService.BaseUrl)]
    public class GenerateKeyDialog : EntityDialog<GenerateKeyRow>
    {
        protected GenerateKeyForm form;

        public GenerateKeyDialog()
        {
            form = new GenerateKeyForm(this.IdPrefix);
        }

        protected override List<ToolButton> GetToolbarButtons()
        {
            var buttons = base.GetToolbarButtons();
            buttons.RemoveRange(1,1);

            ToolButton btn = new ToolButton
            {
                Title = "Send Email",
                CssClass = "save-button",
                OnClick = delegate
                {
                }
            };

            buttons.Add(btn);


            ToolButton btnsms = new ToolButton
            {
                Title = "Send SMS",
                CssClass = "save-button",
                OnClick = delegate
                {
                   
                }
            };

            buttons.Add(btnsms);

            return buttons;

        }
    }
}
```

The code for dialog is as above

**Comment by Estrusco** [comment]
This could be a way

```cs
Q.ServiceCall<MYResponse>(new ServiceCallOptions<MYResponse>
{
   Url = Q.ResolveUrl("~/Services/Test/MyTest/TestingMethod"),
   Request = request,
   OnSuccess = response =>
   {
     J("#IDControl").Text(response.MyTestValue);
   }
});
```

Where in project.web (xyzmodels.cs)
```cs
public class MYResponse: ServiceResponse
{
   pubblic string MyTestValue;

```

I apologize if it is not the correct answer.

**Comment by volkanceylan** [comment]
If you generate it at server side, overriding SetInternalFields, it will come back after save.

There is e-mail sample in registration. It should be enough.

Can't help you with SMS.

**Comment by jsbUSMC** [comment]
ASP.NET Identity 2.0 has an empty class for configuration of SMS. However, you need to set it up with your own configuration. I've been working on integrating Identity with Serenity, unfortunately the tutorial that another user posted awhile back didn't explain how they implemented the Serenity interfaces for Identity.
