### ISSUE TITLE
MultipleFileUploadEditor

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#635]
Dear @volkanceylan,
I'm trying to make MultipleFileUploadEditor work, but without any luck...

Edit: just realized that I have not given you enough details...
I tried to modify the ProductRow this way:

![image](https://cloud.githubusercontent.com/assets/17425690/15022221/ef769e86-122a-11e6-971a-11b75a860ac2.png)

then I tried to upload 3 files, I have seen the array returned (in debug in the ProductRepository - SaveResponse method), but than the save fail and throws an exception...I cannot find any example with the MultipleFileUploadEditor control so honestly I don't know if ProductImage db type is the right one...

Viceversa the FileUploadEditor is working perfectly...
Moreover, I would like to put the attachments in the database (sql server in my environment), but I don't know at which "level" start to work: I have to customize the save/retrieve response? Or there is another way to do that?

Thanks
Regards

**Comment by volkanceylan** [comment]
Your ProductImage field should be nvarchar(max), as it will store JSON. Avoid storing image files in DB. I didn't try nor have sample for storing in database.

**Comment by marcobisio** [comment]
Make sense...
Suggestion received...and accepted ;-)
Thank you very much
