### ISSUE TITLE
xyzEditor: Saltarelle to Typescript

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#636]
Dear @volkanceylan,
I'm trying to "translate" a custom editor from saltarelle to typescript, but I don't know which class to extend in typescript.
Here we go:

    namespace eService.CSH
    {
        using Common;
        using Administration;
        using jQueryApi;
        using Serenity;
    
        [ColumnsKey("CSH.TicketNote"), DialogType(typeof(TicketNoteDialog)), LocalTextPrefix("CSH.TicketNote")]
        public class TicketNotesEditor : GridEditorBase<TicketNoteRow>
        {
            public TicketNotesEditor(jQueryObject container)
                : base(container)
            {
            }
    
            protected override bool ValidateEntity(TicketNoteRow row, int? id)
            {
                row.ActionDescription = NoteActionRow.Lookup.ItemById[row.ActionId].Description;
                row.CreatorId = Authorization.UserDefinition.UserId;
                row.CreatorDisplayName = UserRow.Lookup.ItemById[row.CreatorId].DisplayName;
                return true;
            }
        }
    }

I'm using the PermissionCheckEditor to re-use the syntax, but obviously my editor needs to extend another class...

Thanks as usual for all your kind support

**Comment by volkanceylan** [comment]
It should be eService.Common.GridEditorBase < TicketNoteRow >, check type names in C# first

**Comment by marcobisio** [comment]
Copy that...I'll try...
Thanks!

**Comment by marcobisio** [comment]
Still fighting with typescript...my new editor class is something like that:
![image](https://cloud.githubusercontent.com/assets/17425690/15041548/1c64e546-12bd-11e6-839f-78d1f5f1991c.png)

but I cannot use the "TicketNotesEditor" attribute in my TicketForm...

![image](https://cloud.githubusercontent.com/assets/17425690/15041552/2fb455be-12bd-11e6-8ecc-3c9906653d4c.png)


Any ideas?

Thanks

**Comment by volkanceylan** [comment]
Try putting @Serenity.Decorators.editor() on your TicketNotesEditor before transforming templates.

Where do you place this editor .ts file? It should be under Modules folder.

If still doesn't work there is something wrong with your configuration.

Use them with [EditorType("CSH.TicketNotesEditor")] etc

**Comment by volkanceylan** [comment]
Did you follow steps to add ClientTypes.tt to your project in migration guide?

**Comment by marcobisio** [comment]
The project isn't migrated, but instead it's a brand new 2.0.13 Serenity where I have manually merged all code frome the previous 1.9.x.
I do that in this way in order to review e recheck all my previous code (with a better understanding of the platform).
The editor .ts file is in Modules\CSH\Ticket so should be fine...
Probably the editor instrunction have done the trick, but I have another question: when my project (I mean my namespace) will be fully migrated to typescript, can I remove all the CSH.* entry from ServerImports.tt?

Thank you very much

**Comment by volkanceylan** [comment]
Why you want to remove them. They are just import classes.

**Comment by marcobisio** [comment]
Because the import classes give me error:
![image](https://cloud.githubusercontent.com/assets/17425690/15045466/e3cf84d4-12da-11e6-9a3a-ebd2aed0fa90.png)

 but I don't need the imports anymore (in the script project).
The screenshot above is taken from CSH.TicketForm.cs in the ServerImport (Script project).
Btw the TicketNoteEditor is still not working...I don't know what I'm doing wrong...in the Saltarelle implementation was working fine...

Thanks

**Comment by marcobisio** [comment]
One more details:

- reverted the editor class to saltarelle and it's working fine
- switched the only TicketDialog.cs (Script) class to TicketDialog.ts (Web) and then the editor stop working...I mean no exception, no error, nothing...simply the the add note button in the sub table seems not responding...

**Comment by volkanceylan** [comment]
Type import from typeScript to Saltaralle is currently limited.  You need to manually define an imported TicketNotesEditor dummy class to stop that error. Saltaralle will eventually be removed so i dont want to waste time trying to import types from TS to Saltaralle.

**Comment by marcobisio** [comment]
Copy that...
Viceversa any idea on the editor? I don't understand why when I've switched the TicketDialog to TypeScript   the notes subtable has stopped working...
There isn'n any logic in there...it'the form that container the editor type configuraton and such Class (the form I mean) has not been modified...

Thanks

**Comment by volkanceylan** [comment]
Need to see both source code

**Comment by marcobisio** [comment]
Right!
So this is the Saltarelle version of the editor (perfectly working):

![image](https://cloud.githubusercontent.com/assets/17425690/15048591/7f54b834-12ea-11e6-9f3c-6744070847ba.png)

and this is the Typescript version (not working):

![image](https://cloud.githubusercontent.com/assets/17425690/15048630/a227072c-12ea-11e6-98b0-72bdb6934e99.png)

and this is the editor attribute in the TicketForm.cs (working with Saltarelle editor and TypeScript TicketDialog generated from sergen and not customized):

![image](https://cloud.githubusercontent.com/assets/17425690/15048668/c77ecbcc-12ea-11e6-894c-1f63111f34f6.png)

**Comment by volkanceylan** [comment]
It should be lookup().get_itemById()[...] if you are on 2.0.13

Will become lookup().itemById[...] in next version

Btw, you should have some typescript error in browser console.

**Comment by marcobisio** [comment]
Gonna try...and I let you know...
Thanks!
