### ISSUE TITLE
Create Toolbar Extensions override causing listing page grid to dissapear

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#637]
Data is being returned on the POST but the grid is not showing up.
![image](https://cloud.githubusercontent.com/assets/17201265/15025939/660ef9d2-1201-11e6-80e5-9e585d2ec13a.png)

**Comment by volkanceylan** [comment]
This is not about data. You have some javascript error.

**Comment by volkanceylan** [comment]
Or empty columns

**Comment by swordz36** [comment]
Yes I do have some empty columns because all rows do not contain data for all those columns.

**Comment by volkanceylan** [comment]
Your grid doesn't have any columns
