### ISSUE TITLE
Logic to filter displayed rows in one table based on column value in another

### ISSUE THREAD

**Issue by SirSpam** [volkanceylan/Serenity#64]
So the basic design of the app is one master table where all information is added, with several Boolean columns based on what users need to see the rows.  Basically, if the column is true, I want that row to be displayed in another table, and if the column is false, that row is omitted.  I have the master table and 5 of these sub tables that need to see the master rows when the appropriate columns are true.  Right now I have all the sub tables pointing to the master table for the RowFields() Base to sync the data between them, and to make sure that any edits to the subtables also change the master.  But what I need is the appropriate logic to edit what rows of the master table is displayed to the subs, again, based on columns in the master table that the sub tables don't get.

**Comment by volkanceylan** [comment]
Sorry but i can't figure out question. Maybe give some sample tables, and final result you are trying to achieve

**Comment by SirSpam** [comment]
So the app is going to be an internal app for a machine shop.

The business need is for an admin to be able to put in orders in the master table along with what machines need to be used.

There are 5 terminals in the back that correspond to each machine, so I am planning on 6 users, one admin, and 5 terminal logins.  The terminals should only see the orders that have been marked to use their machine.

So the admin table will be something like:
orderID   Customer  Part   Due Date   Done   Machine1    Machine2    Machine3    Machine4   Machine5

and the terminals should see the

orderID   Customer   Part   Due Date  Done

but only for the orders that the admin has marked their machine for
The also need to be able to mark done and have that reflected on the admin table

**Comment by volkanceylan** [comment]
So, make this machine number information a part of user table, like a MachineNumber field. Make it available in client side, through ScriptUserData, and remove Machine1..N columns if user has a machine number assigned, by overriding GetColumns method of the grid. Also filter rows depending on logged user MachineNumber server side, by overriding ApplyFilter of ListRequestHandler. If you want to hide Machine1..N fields from form, also override GetPropertyItems method of your dialog, and remove them by their field name etc, if user is not an admin.

**Comment by SirSpam** [comment]
What would the ApplyFilter override look like?

**Comment by volkanceylan** [comment]
```
override ApplyFilter(SqlQuery query) {
    base.ApplyFilter(query);

   var machine = (AuthorizedUser.UserDefinition as UserDefinition).MachineAssigned;
   switch (machine) {
       case 1: query.Where(fld.Machine1 == 1); break;
       case 2: query.Where(fld.Machine2 == 1); break;
....
   }
}
````
