### ISSUE TITLE
Slickgrid default tables - Sorting option question

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#640]
Hi,
Right here is a quick one. If I looking <page>Columns.cs I can set things such as SortOrder, EditLink etc in the attributes. Is there an attribute I can use to disable click sorting on a column. 

The reason I am asking is that I am using a text field (which will be truncated for the column display when I get there) but it flagged as unsortable except for NULL etc which I would expect anyway. I did override the fact that any call to the page cause the error by using SortOrder on a more appropriate column anyway.

**Comment by volkanceylan** [comment]
No attribute yet, you can set it client side

**Comment by solabar** [comment]
Ok not a problem I can do that.

**Comment by volkanceylan** [comment]
There is Sortable option now
