### ISSUE TITLE
UserLookup editor

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#642]
Given my situation I am looking for a lookup editor that would pull back users with specified roles or permissions. I was thinking I might have to build a custom one for that. Unless there is one that already is hiding somewhere?

Is there a way of pulling out a lookup editor in a dialog with an inline SQL or Stored Procedure call? Or am I totally missing it in the documentation?

Hold it a sec. Is this what I want: FilteredLookupInDetailForm.cs in basic samples?

**Comment by marcobisio** [comment]
Define a UserLookup class like that:


	namespace xyz.Administration.Scripts
	{
		using Entities;
		using Serenity.ComponentModel;
		using Serenity.Data;
		using Serenity.Web;
	
		[LookupScript("Administration.User")]
		public sealed class UserLookup : RowLookupScript<UserRow>
		{
			public UserLookup()
			{
				IdField = UserRow.Fields.UserId.PropertyName;
				TextField = UserRow.Fields.DisplayName.PropertyName;
			}
	
			protected override void PrepareQuery(SqlQuery query)
			{
				base.PrepareQuery(query);
	
				query.Where(PUT_HERE_YOUR_WHERE_CONDITION);
			}
		}
	}

then comment out the LookupScript attribute (if any) in your UserRow.

**Comment by solabar** [comment]
Still having some trouble with this. Here is what I have so far.
TicketsRow.cs has this
```
[DisplayName("Ownerid"), Column("ownerid"), ForeignKey("[dbo].Users", "UserId"), LeftJoin("u"), NotNull]
        [LookupEditor("Administration.User")]
        public int? Ownerid
        {
            get { return Fields.Ownerid[this]; }
            set { Fields.Ownerid[this] = value; }
        }

        [DisplayName("Owned By"), Expression("u.DisplayName")]
        public string OwnedBy
        {
            get { return Fields.OwnedBy[this]; }
            set { Fields.OwnedBy[this] = value; }
        }
```
I made a UserLookup.cs as outlined above.
I effectively want to pass _WHERE RoleName = 'Helpdesk'_ as the where clause, but this will necessitate joining across the UserRoles table

I tried this
```
 protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);

            query.From(" u left JOIN UserRoles ur on u.UserId = ur.UserId left join Roles r on ur.UserRoleId = r.RoleId");
            query.Where(" r.RoleName = 'Helpdesk'");
        }
```

But its throwing me JavaScript runtime error: Can't load script data: Lookup.Administration.User!
I must have missed a step somewhere to register the script, but I have been looking at it so long I can't think where!

**Comment by marcobisio** [comment]
You can do that (just an example):

    protected override void PrepareQuery(SqlQuery query)
    {
        base.PrepareQuery(query);
        var fldUser = UserRow.Fields;
        var fldUserCountry = UserCountryRow.Fields.As("uc");
    
        query.Where(
            fldUser.Id.In(
                query.SubQuery()
                    .Select(fldUserCountry.CountryId)
                    .From(fldUserCountry)
                    .Where(fldUserCountry.UserId == Authorization.UserDefinition.Id)
            )
        );
    }

**Comment by solabar** [comment]
Seems a bit clunky that I have to execute 2 subqueries to get that back though. A dynamic lookup return would seem much more reasonable to me. For example implementing it as [LookupEditor("Administration.User"), RoleName("Role")] then using the role as part of the query build would eliminate the need for hardcoding and less DB calls.

This would need a bit more knowledge of Serenity than I have to implement though.

**Comment by solabar** [comment]
If I could pass a string as an additional part of the call this would be much more versatile. But is this essentially what you were suggesting?

```
protected override void PrepareQuery(SqlQuery query)
        {
            //this is an incredibly clunky method to get back what I want
            string sRole = "Helpdesk";

            base.PrepareQuery(query);
            var fldUser = UserRow.Fields;
            var fldUserRole = UserRoleRow.Fields.As("ur");
            var fldRole = RoleRow.Fields.As("r");

            query.Where(
                fldUser.UserId.In(
                    query.SubQuery()
                        .Select(fldUserRole.UserId)
                        .From(fldUserRole)
                        .Where(
                            fldUserRole.RoleId.In(
                                query.SubQuery()
                                    .Select(fldRole.RoleId)
                                    .From(fldRole)
                                    .Where("RoleName = '" + sRole + "'")
                            )
                        )

                    )
            );
```

**Comment by volkanceylan** [comment]
Lookups, and other types dynamic scripts doesn't support parameters and they shouldn't be. They are cached statically. They don't change from user to user. It's like a static variable. They can only be filtered client side. You're trying to misuse a feature not designed for parameterization, for something it's not supposed to be.

That's why you need to define a secondary remote data script containing UserId / RoleId etc. pairs, e.g. UserRoles And filter your users (UserRow.Lookup) based on information in this data script, "client side". It can be done by overriding getItems method of LookupEditor.

If you want a server side solution, search for Select2AjaxEditor in issues and implement such a solution.

**Comment by solabar** [comment]
Ok I found a midway solution. I wanted it server side but it didn't have to be as variable as I thought, defined myself a HelpdeskUser lookup with the where clause and it isn't going to be super unpleasant to use it given the application. It's a bit kludgy but in the interests of expediency I will go with it.
