### ISSUE TITLE
Is there an editor that will display values as an HyperLink?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#643]
When a form is opened I have a column in my entity that stores a URL value, Is there a way to make that value a link on the Form for that entity. 

My Example:
I have a front end app that users can upload a proof of purchase that is saved on the server and the location path is stored in the DB. I want the admin to be able to open that record and click a link and open that file in the browser.

**Comment by volkanceylan** [comment]
UrlFormatter

**Comment by swordz36** [comment]
Thanks, Where can I find a list of all the formatters and editors?

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/blob/bbae4c7075ee6ab6339343d63fd1986eefd2ad24/Serenity.Core/ComponentModel/PropertyGrid/Editing/BasicEditorTypes.cs

https://github.com/volkanceylan/Serenity/blob/master/Serenity.Core/ComponentModel/Columns/Formatting/BasicFormatterTypes.cs

**Comment by swordz36** [comment]
Looks like I am not implementing this right. The dialog form is still displaying as a textbox, and I want to be displayed a link to click on. Maybe I do not fully understand the control.

**Comment by volkanceylan** [comment]
It's only for columns, not editors. There is no such editor.

**Comment by swordz36** [comment]
Is there a way that I could extend the code to create this editor

**Comment by fwd079** [comment]
> It's only for columns, not editors. There is no such editor.

Hi, looks like it is still not there.
Well could you please let us know if/when there's something like `[HyperLink("Click here to open URL")]` type attribute in Dialog as well? 

Regards.
