### ISSUE TITLE
Persisting filter settings after navigating away

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#645]
If I use a filter, navigate away to another page and then come back the filter is reset. Is there an option to persist the filter settings? Many thanks in advance.

**Comment by volkanceylan** [comment]
Unfortunately, there is currently no such option. You may try serializing this.filterBar.Store.Items to JSON, then save it in database / local storage, then when return load them back, and restore this.filterBar.Store.Items again.

**Comment by c9482** [comment]
Thanks. It would be a nice feature to add in the future.
