### ISSUE TITLE
Typescript: Script.Delete()

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#646]
Dear @volkanceylan,
can you help me on translate the "Script.Delete(....)" instruction in Typescript pls?
I'm using that in a getSaveEntity override....
I'm trying the usual namespaces and also I have tried to search in the sources, but with no luck,,,

Thanks

**Comment by volkanceylan** [comment]
delete myobject.myproperty

**Comment by volkanceylan** [comment]
When you are stuck, you may at your MyProject.Script.js file and see what it is translated to

**Comment by marcobisio** [comment]
Thank you very much...especially for the hint on how to resolve by myself those kind of "problem".
Best Regards
