### ISSUE TITLE
Thousands separators - Setting it globally?

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#647]
Hi community,

Does anyone have experience in setting the number format to include thousand separators?
Is it possible to set it globally, maybe in the Webconfig file??

I want my grids to show numbers with thousand separators, like this (12.345,67) - marked **red**
I also need to have percentages shown like in (100%) and (90%) - marked **blue**

Now it only show this
![image](https://cloud.githubusercontent.com/assets/15879719/15071980/3ba02d90-137f-11e6-845f-2ee1d18c12ad.png)

As always,
Biggi

**Comment by volkanceylan** [comment]
Try [DisplayFormat("#,##0.##")]

**Comment by volkanceylan** [comment]
For percentage you need to write a formatter, there are samples in Serene

**Comment by biggikalli** [comment]
You still amaze me Maestro Volkan with your quick replies :)

Where should I put this [DisplayFormat("#.##0,##")] ?
I have already tried this on xxxColumns.cs and also in xxxRow.cs.

Thank you

**Comment by biggikalli** [comment]
Is it possible to set it globally, e.g. in webconfig

Somewhere here maybe:
![image](https://cloud.githubusercontent.com/assets/15879719/15072135/94b0c588-1380-11e6-985e-727711165cd9.png)

I have already set the culture to Icelandic and the dates are shown correctly but not the numbers.

**Comment by volkanceylan** [comment]
Put it on columns. You cannot set it globally.

**Comment by biggikalli** [comment]
Ok, thanks. I will try :+1:

**Comment by biggikalli** [comment]
FANTASTIC - IT WORKS

Thank you Sir.

**Comment by biggikalli** [comment]
Dear Volkan,

Could you point out where I can find the percentage formatter sample in Serene?

Regards,
Biggi

**Comment by SimeonDD** [comment]
Hi biggikalli
Did you put the formatting in the xxxxColumns.cs?
Like
 [DisplayFormat("#.##0,##")]
        public Decimal BudgetConsolidated { get; set; }

I tried and it does not work for me.

**Comment by SimeonDD** [comment]
I also tried in xxxxRow.cs like:
[DisplayName("Budget Consolidated"),DisplayFormat("#.##0,##"), Size(18), Scale(2)]
        public Decimal? BudgetConsolidated
        {....

**Comment by biggikalli** [comment]
Hi @SimeonDD 

I did wrong the first time....but the thing is to follow Volkan entirely.
That means having [DisplayFormat("#**,**##0**.**##")]

That is to have the decimal first and the thousand separator last, just like it is in the USA.
Have the comma first and then the dot.

It should work, it did for me when I realized :)

**Comment by biggikalli** [comment]
...and yes. Put it in the xxxColumns.cs

**Comment by SimeonDD** [comment]
Huh .... I TOTALLY missed this!!
You DA MAN!
Btw. also looking for currency syntax if you happen to know.
If not no worries.

Thank you so much biggikalli!

**Comment by biggikalli** [comment]
No probs amigo.

Regarding the Currency syntax, I suspect you would need to create some special formatter for that.
There must be someone in the community which has already solved that.

I was dealing with a simple XX% last spring, see #653 
The guys were really helpful to me but I was unable to finish that problem. That was in the Saltarella era.

If I were you, I would fire up an issue with that question and see what happens.

**Comment by SimeonDD** [comment]
Thanks man!
Totally appreciate you helping me out.

**Comment by biggikalli** [comment]
Hey, have you tried to include the sign in like: [DisplayFormat("$#,##0.##")] ??

**Comment by SimeonDD** [comment]
Oh yes! But it did not work.
Please check what I came up with in  here: [https://github.com/volkanceylan/Serenity/issues/1077](url)
