### ISSUE TITLE
ActiveDirectory first connection

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#648]
Hi,

I want to manage permission locally and I am trying to redirect the user to a profile setup page on first login. 
Though I am unable to catch anything. I set  <authentication mode="Windows"> in Web.config. The username code is shown on the top left, but I am unable to catch the first connection.

I would be very gratefull for any clue where should I look,

Thank you

**Comment by volkanceylan** [comment]
You may do this in AuthenticationService, ValidateFirstTimeUser method, instead of returning true, redirect user to a setup page.

**Comment by Boumboumjack** [comment]
Hi,

Thank you for your answer. I was looking to do more work, you already did everything in the best way! I was struggling as I was messing up with  <authentication mode="Forms"> (puting windows instead) and therefore bypassing your classes.

You work is really great, thank you!
