### ISSUE TITLE
Globally remove tabindex="-1" from dialogs

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#649]
Dear @volkanceylan,
there is an upgrade safe way to redefine the tabindex value of the dialog? I came across an issue with tabindex="-1" and bootbox (input textbox not writable) that is resolved by removing the tabindex from the dialog...
I do that directly from the browser in develop mode, but now I would like to know how to modify this attribute programmatically...

Thanks for your support
Best Regards

**Comment by marcobisio** [comment]
Ahh wait the dialog are an implementation of the colorbox library...so now (perhaps) I know where to search...

**Comment by volkanceylan** [comment]
This.element.closest('.ui-dialog').removeAttr('tabindex') but this might bring other problems.

**Comment by marcobisio** [comment]
Do you mean in the dialog constructor?

**Comment by marcobisio** [comment]
Btw I'll try and I let you know.

Thanks
Have a nice weekend :-)
Bye
