### ISSUE TITLE
Reports with graphical display such as Charts?

### ISSUE THREAD

**Issue by denonc** [volkanceylan/Serenity#65]
Hi, will there be reports with common charts feature in the upcoming enhancements? Meanwhile, could you advise briefly on how to create reports with graphical display? Thanks!!

**Comment by volkanceylan** [comment]
You might use wkhtmltopdf for this. Another option is SQL reporting services or another similar report tool. Yes there will be reporting samples, but not sure about timeline yet.

**Comment by denonc** [comment]
I have take a look at wkhtmltopdf, it seems like a feature to convert html to pdf format, but how does it create reports with graphical display or work with serenity to show reports?

**Comment by volkanceylan** [comment]
Create a page without layout but chart contents, like dashboard. Then convert it to PDF. Isn't this what reporting tools do?

**Comment by denonc** [comment]
Noted with thanks!

**Comment by c9482** [comment]
I would appreciate any help on how to embed a report into, say, dashboard cshtml page. I tried adding the required assembly:

`<%@ Register assembly="Microsoft.ReportViewer.WebForms, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>`

and the control

```
<rsweb:ReportViewer ID="MainReportViewer" runat="server" ProcessingMode="Remote" Width="100%" ShowParameterPrompts="False">
                    <ServerReport ReportPath="/SubDirectory/ReportName" ReportServerUrl="http://cpand0047/reportserver" />
                </rsweb:ReportViewer>

```
but I am only getting a parsing error when displaying the page....

>  Parser Error
> Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately.
> 
> Parser Error Message: A space or line break was encountered after the "@" character.  Only valid identifiers, keywords, comments, "(" and "{" are valid at the start of a code block and they must occur immediately following "@" with no space in between.
> 
> 
> Source Error:
> 
> 
> Line 1:  <%@ Register assembly="Microsoft.ReportViewer.WebForms, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>
> Line 2:  
> Line 3:  @model LCBudgets.Common.DashboardPageModel
> 
> 
> Source File: /LCBudgets.Web/Modules/Common/Dashboard/DashboardIndex.cshtml    Line: 1
>

**Comment by volkanceylan** [comment]
You can't mix CSHTML with WebForms controls. Only IFRAME is possible.

**Comment by c9482** [comment]
Can I use .asp page in a seamless fashion?
