### ISSUE TITLE
How to get entity with its id at client side

### ISSUE THREAD

**Issue by chetanjoshi1988** [volkanceylan/Serenity#650]
![serenors](https://cloud.githubusercontent.com/assets/16666095/15092562/49db42f2-148b-11e6-82e3-a0ce878e517a.png)

I want **Product Id** ,
As click on **Generate Key** button of selected **Serial Number**
now I  am stuck over there . Plz tell me how to get product id which is selected

**Comment by fzhenmei** [comment]
check this [https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_add_a_row_selection_column.html](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_add_a_row_selection_column.html)

**Comment by chetanjoshi1988** [comment]
@fzhenmei  thanks for reply but my problem is somewhat different.

SerialNumbers grid is as follows

![frm1](https://cloud.githubusercontent.com/assets/16666095/15212554/0c581b62-185f-11e6-9091-4718d409cd28.png)

After selecting a perticular row when i click on **Generate Key** button , then dialog opens as follows.

![frm2](https://cloud.githubusercontent.com/assets/16666095/15212565/1da27ce6-185f-11e6-84e9-dd2c699af4c7.png)

In above image
Im getting **Serial Number** on the form but not getting other values. 
**Product Value** text box is  **empty** as follows

![frm3](https://cloud.githubusercontent.com/assets/16666095/15212685/dba89338-185f-11e6-9812-8878e58e0f54.png)



My code on button click is as follows.

```
 buttons.Add(new ToolButton
            {
                Title = "Generate Key",
                CssClass = "add-button",
                OnClick = delegate
                {
      
                    var dlg = new GenerateKeyDialog();

                    InitEntityDialog(dlg);
                   
     
                    long id = 0;
                    long i = 0;
                    List<string> rs = rowSelection.GetSelectedKeys();

                 
                   

                    foreach (string str in rs)
                    {
                        id = (long)str.ToInt64();
                        i = i + 1;
                    }
                    if (id == 0 )
                    {
                        Q.Alert("Please select serial number !");
                    }
              
                    else
                    {

                        if (i > 1)
                        {
                            Q.Alert("Please select only one serial number !");
                        }
                        else
                        {

                            

                            dlg.LoadEntityAndOpenDialog(new GenerateKeyRow
                            {
                                IdSerialNumber = SerialNumbersRow.Lookup.Items.First(x => x.IdSerialNumber == id).Serial ,
                                ProductId = SerialNumbersRow.Lookup.Items.First(x => x.IdSerialNumber == id ).IdProduct ,
                                ProductProductValue = SerialNumbersRow.Lookup.Items.First(x => x.IdSerialNumber == id).IdProductProductValue
                            });
                        }

                    }
                   
                }
            });

```


The table structure of **SerialNumbers** table and **Products** table is as follows


![relation](https://cloud.githubusercontent.com/assets/16666095/15212727/1aad9c5e-1860-11e6-9b31-b7e192e729bf.png)


How to get **Product Id** and **Product Value** on New Generate Key dialog.

**Comment by volkanceylan** [comment]
Why are you not using LoadById, but LoadEntity then?

**Comment by chetanjoshi1988** [comment]
I dont want entire entity of **Serial Number** to be open in dialog , rather i want some fields value of **Serial Number** of selected row to be shown on **Generate Key** dialog which is different from Serial Number

**Comment by volkanceylan** [comment]
Then access current row in grid with this.ItemAt(row) fill in values in your entity

**Comment by onerkaloglu** [comment]
hello,
is there any example of this question
