### ISSUE TITLE
Error after Transform All T4

### ISSUE THREAD

**Issue by 4lamosky** [volkanceylan/Serenity#652]
After click Transform T4 I get this error:

![error t4](https://cloud.githubusercontent.com/assets/18552029/15095604/3befc7a8-14f9-11e6-9e55-900728538f51.png)

What should I do ?

Fyi, I was Add one C# project, so i have 3 projects now, (script, web and report), but i have no idea this error cause of my new project(report) or not ?
Thank a lot as usual

**Comment by volkanceylan** [comment]
Your web project has ref to script project or had. See references and clean bin directory.

**Comment by 4lamosky** [comment]
clean script/bin/debug and clean web/bin with same result.
where i should start find references?

**Comment by volkanceylan** [comment]
Your web project -> references

**Comment by 4lamosky** [comment]
same error, but since I removed reporting project, the problem solved.
my reporting project working find...i'll find again whats wrong with my reporting project.

Thank volkan for all your guide and fast response.
