### ISSUE TITLE
Call servicerequest from Typescript

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#655]
Dear @volkanceylan,
probably still fighting with typescript, but here I get a "Uncaught TypeError: this.getSaveEntity is not a function" error:

    protected getToolbarButtons() {
            let buttons = super.getToolbarButtons();
    
            buttons.push({
                title: Q.text('Site.TicketDialog.AcceptButton'),
                hint: "Accept Ticket",
                cssClass: 'accept-ticket-button',
                onClick: () => {
                    if (!this.validateForm()) {
                        return;
                    }
    
                    var box = bootbox.prompt({
                        title: "Please enter a reason?",
                        value: "",
                        callback: function (result) {
                            if (result === null) {
                                Q.notifyWarning("test");
                            } else {
                                Q.serviceRequest(TicketService.baseUrl + "/Accept", { Entity: this.getSaveEntity() }, () => {
                                    Q.notifySuccess('Case ' + this.form.SourceSystemId().get_value() + ' has been successfully assigned to ' + this.form.OwnerId() + '.', '', null);
                                    Serenity.SubDialogHelper.triggerDataChange(this);
                                    this.dialogClose();
                                });
                            }
                        }
                    });
                    box.zIndex(1200);
    
                    // remove tabindex attribute for bootbox compatibility
                    this.element.closest('.ui-dialog').removeAttr('tabindex');
                }
            });
    ......				
	
I already checked Script.js file to see how code is translated, but with no luck...
Any idea?

Thanks for your support
Best Regards

**Comment by volkanceylan** [comment]
"this" changes in events to clicked button etc. Saltaralle handles it with ss.mkDel by wrapping this in a closure variable, so you dont notice it. Typescript offers lambda functions that provides same functionality. So instead of onClick: function() { this.xx } do onClick: () => { this.xx }

**Comment by volkanceylan** [comment]
Here problem is in callback

**Comment by marcobisio** [comment]
Solved!
Thank you very much
