### ISSUE TITLE
bootstrap multiselect: fix for Firefox and IE 11

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#656]
Dear @volkanceylan,
this time instead of asking for support I (hope) to give my contribute...
In your developer guide you suggest this code:

![image](https://cloud.githubusercontent.com/assets/17425690/15115728/a996bb1a-1600-11e6-89c1-fe60b87c39b2.png)

but unfortunately it doesn't work properly on Firefox and IE 11 (the first item is already selected when the page opens).

So this is my working version:

![image](https://cloud.githubusercontent.com/assets/17425690/15116200/a68bade8-1602-11e6-900d-34b5a8d01094.png)

Thanks
Best Regards

**Comment by volkanceylan** [comment]
Oh, thank you i must have missed that part

**Comment by marcobisio** [comment]
You're welcome :-)
