### ISSUE TITLE
Chrome on mac ... slick.grid problem

### ISSUE THREAD

**Issue by patcout26** [volkanceylan/Serenity#657]
I have this error 
Uncaught ReferenceError: restoreCssFromHiddenInit is not defined
slick.grid.js?v=_nQiZmDgVVVqRocSsDBhPA2:524

**Comment by volkanceylan** [comment]
Open slick.grid.js remove line with restoreCssFromHiddenInit till its resolved in next version

**Comment by patcout26** [comment]
Thanks

**Comment by volkanceylan** [comment]
Fixed with 2.1.0
