### ISSUE TITLE
Get exception "Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'." using code generated by the sergen utility before any customisation!!

### ISSUE THREAD

**Issue by RichardBr** [volkanceylan/Serenity#658]
Hi @volkanceylan 

I get the exception "Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'." when my table contains a column with a datatype of "Timestamp".

The exception occurs in file {entity}Repository.cs at line "return new MyListHandler().Process(connection, request);" in method shown below:
```
        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }
```

Below is parts of my {entity}Row.cs file:
```
........
[DisplayName("Ver Col"), NotNull]
public Int64? VerCol
{
    get { return Fields.VerCol[this]; }
    set { Fields.VerCol[this] = value; }
}
........
        public class RowFields : RowFieldsBase
        {
........
            public Int64Field VerCol;
```

Looking at some current issues, I notice other people using concurrency control column had other problems but didnt mention this issue as a problem !?!?

Any ideas?

**Comment by volkanceylan** [comment]
Need to test with a timestamp column. I didnt try one before. Can you test using a StreamField meanwhile?

**Comment by RichardBr** [comment]
I made changes as you suggested and it now works.

Using StreamField my code looks like this:
```
........
[DisplayName("Ver Col"), NotNull]
public Stream VerCol
{
    get { return Fields.VerCol[this]; }
    set { Fields.VerCol[this] = value; }
}
........
        public class RowFields : RowFieldsBase
        {
........
            public StreamField VerCol;
```

I will continue using the streamField until you have implemented the "TimestampField".

**Comment by volkanceylan** [comment]
Thanks i'll try to look into this soon

**Comment by volkanceylan** [comment]
It seems like a RowVersion or timestamp field in Sql server is a better match for StreamField (or byte[] field). 

So probably we don't need a TimestampField. But i'll update sergen to match it to a StreamField by default.
