### ISSUE TITLE
What's name rule of "[EnumKey("Material.mPlant")]

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#659]
My code is
 ` [EnumKey("Material.mPlant")]
    public enum mPlant
    {
        [Description("clyinder")]
        clyinder = 1,
        [Description("HPU")]
        HPU = 2,
        [Description("Manifold")]
        Manifold = 3,
    }`

it's map to

`[DisplayName("M Plant"), Column("mPlant")]
        public mPlant? MPlant
        {
            get { return (mPlant?)Fields.MPlant[this]; }
            set { Fields.MPlant[this] = (Int32?)value; }
        }`

But when i list all the material.  the list is empty, but at the bottom has the number of material.

**Comment by PanChenhao** [comment]
When I try "Transfer all T4 Template" and rebuild the solution, it works now.
But I still do not know the name rule of "[EnumKey("Material.mPlant")] "

**Comment by volkanceylan** [comment]
Its a unique key for enum type client side. It deteröines local text prefix also. E.g. Enums.Material.mPlant.HPU. If not specified full type name is used

**Comment by PanChenhao** [comment]
Thanks
