### ISSUE TITLE
Add Oracle dialect and how-to guide

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#66]

**Comment by zerodev** [comment]
looking forward for that ....

**Comment by tvldev02** [comment]
+1

**Comment by tqvtqv** [comment]
i'm looking forward to this too

**Comment by tvldev02** [comment]
Greeting,

If we use oracle as database, how much effort is needed?

Can you please give a quick hint? Or it is so difficult to add oracle dialect?

**Comment by volkanceylan** [comment]
There are several dialects in Serenity source code. Take them as sample and develop yours.

**Comment by dfaruque** [comment]
Hopefully, next version will have the oracle support.

**Comment by volkanceylan** [comment]
If it goes like this, no it won't. Oracle is a real headache. And FluentMigrator doesn't support it properly.

First of all, it doesn't support identity columns so i have to write separate migration statements for fluent migrator.

I have tried to use a SEQUENCE with FluentMigrator:

```cs
IfDatabase("Oracle")
    .Execute.Sql(@"
BEGIN
CREATE SEQUENCE Users_SEQ;

CREATE OR REPLACE TRIGGER Users_SEQ_TRG
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
	IF :new.UserId IS NULL THEN
		SELECT Users_SEQ.nextval INTO :new.UserId FROM DUAL;
	END IF;
END;

ALTER TRIGGER Users_SEQ_TRG ENABLE;
END;
/");
```

It says ORA-911 invalid character. Where is this invalid character, there is no info at all.

I tried removing /, moving it, with commas no commas, adding / removing BEGIN END and no luck.

Oracle must be really from stone age.

Anyone has an idea?

**Comment by dfaruque** [comment]
Users is not a valid identifier for oracle.

**Comment by volkanceylan** [comment]
Nah, i fixed it, its about semicolons

**Comment by dfaruque** [comment]
You are genius... :+1:

**Comment by samdubey** [comment]
I agree
