### ISSUE TITLE
Multiselect with composite keys

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#660]
Declaration:LinkingSetRelationAttribute(Type rowType, string thisKey, string itemKey)
How is when param 'thisKey' is 'composite keys' just like tenantId and orderId compose the primary key?

**Comment by volkanceylan** [comment]
It won't work with composite keys. Need to use a proper ID or implement behavior yourself.

**Comment by ChenZhaobin** [comment]
thanks,I have use  a guid field as substitute for 'composite keys'.After all,'composite keys' has some drawback,try to avoid it.
