### ISSUE TITLE
How can guid primary key auto generated just like identity attribute?

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#661]
Maybe this has no ralation with serenity,I just want to know how can I write  a Migration wich can  generate sql  likes below:
create table tguid
(
gid uniqueidentifier not null default(newid()),
val varchar(12)
)

**Comment by volkanceylan** [comment]
Try this 
http://stackoverflow.com/questions/7530221/is-it-possible-to-set-column-default-to-sql-servers-newid
