### ISSUE TITLE
Strange behavior Mac+Azure

### ISSUE THREAD

**Issue by James-A-White** [volkanceylan/Serenity#662]
Hey!

First, a huge thanks for this framework!  My word how much time this has saved me!  :-)

So, I just deployed as a WebApp to Azure and... this is quite strange... When I access my site from Windows machines, no problems... I see all data. However, when I access from my Mac, I see the screens, but no data.  I've tried clearing all browser caches, restarting the webapp on Azure and even deleting and reloading the Azure app.  Any idea what might be going on?

I see that you've fixed a bug in the recent release that affects Mac/Safari, but this is happening on both Safari and Chrome.  Could it be some sort of firewall setting blocking both browsers?

Thanks!

James

**Comment by volkanceylan** [comment]
Hi James, it might be affecting Mac too, did you try with 2.1.0, or removing that line as i suggested other user?

**Comment by volkanceylan** [comment]
Yes it might also affect chrome in mac as it is also webkit based
