### ISSUE TITLE
Open more than a dialog at the same time

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#663]
Dear @volkanceylan,
first of all thanks for the new 2.1.0 version!!

Btw I was wondering if there is a way to open more than a dialog at the same time or to open a dialog directly from an URL: I see that if I click on a grid and "open to another window", I get an URL like "my_address#CSH-Ticket/18" and in effect the last part of the URL allows me to identify which record to open, but at the moment what I get it's only the same grid opened in another window and no dialog opens.

I was thinking about url parsing in order to automatically open a dialog, but I would like to know if you have already thought about that and/or if there is a better/cleaner approach to this...

Edit: just to clarify...I know that multiple dialogs can be opened at the same time, but it's possibile to use only one at a time...like the clone functionality,,,

Thank you very much
Best Regards

**Comment by volkanceylan** [comment]
Actually those URLs can be parsed to a dialog type: e.g. reading hash and replacing "-" with ".". You could even call that handling code from a script referenced by your _Layout.cshtml. Using DialogTypeRegistry you could find dialog that matches CSH.Ticket, then new that dialog type and loadById.  That would probably be how i would do it.

I'm thinking about some browser history manupilation to allow bookmarking records, and ability to back/forward, but its in very early stages of designing.

**Comment by marcobisio** [comment]
Thank you very much for the suggestion @volkanceylan...now that I know the "way" I'll try and I let you know...

Have a good evening!
Bye

**Comment by marcobisio** [comment]
Dear @volkanceylan,
I'm trying to implement what you have suggested...
I've added the following piece of code in the constructor of my xyzGrid.ts:

    var dialogType: any = Serenity.DialogTypeRegistry.get(PARSED_TYPE_FROM_HASH);
    var dialog = Serenity.Widget.create({
        type: dialogType
    });
    (dialog as Serenity.EntityDialog<any, any>).loadByIdAndOpenDialog(20);

where PARSED_TYPE_FROM_HASH is "taken" from the location.hash attribute (something like #CSH-Ticket/532).

The previous ts code is translated in something like that (in js I mean):

    var dialogType = Serenity.DialogTypeRegistry.get(PARSED_TYPE_FROM_HASH);
	var dialog = Serenity.Widget.create({
		type: dialogType
	});
	dialog.loadByIdAndOpenDialog(20);

Now, while the ts code is working fine, if I try to pick the generated js code and put it in the _LayoutHead.cshtml (in order to generalize the mechanism), then I got "Uncaught TypeError" and obviously the dialog does not open.
I tried with different type of dialog, but I always got errors...what I'm missing?
Do you have any idea?

Thank you very much for your support
Bye

**Comment by volkanceylan** [comment]
Check replacing "-" with ".".

Also if you put it in LayoutHead, you should also call this methods after page is loaded, e.g. $(function() {....});

**Comment by marcobisio** [comment]
Already replaced...in fact in my xyzGrid the same code it'working fine...
I'll try again  and I let you know...
Thank you very much
Bye

**Comment by marcobisio** [comment]
Dear @volkanceylan,
when I open an editor in a dialog (master detail) the url of the detail item is something like that:

    #CSH-TicketNotesEditor/1
but I would like to have in the hash parameter the "real" id of such item instead of a progressive one, because the real id allows me to open the related object dialog with the system the I have implemented .In fact the other hash parameter of the item (outside of a master detail relation) already contains the real id (after the last slash I mean).

Any idea on how to customize such hash parameter on the onclick event of the detail object?

Thank you very much
Bye

**Comment by volkanceylan** [comment]
You need to write custom formatter. Real ID is not possible as some records are not created yet.

**Comment by marcobisio** [comment]
You're right...I had not thought about this scenario...
Once again, thank you very much for your support!
Bye
