### ISSUE TITLE
Typescript slick formatter

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#664]
Dear @volkanceylan,
I'm trying to use a slick formatter in typescript (like I used to in Saltarelle), but I'm doing something wrong and I cannot find a suitable example...
Here what I have done:

    namespace x.y {
        @Serenity.Decorators.registerClass()
        @Serenity.Decorators.registerFormatter()
        export class MyFormatter extends Serenity.ISlickFormatter {
    
            public Format(ctx): string {
                var text = Q.htmlEncode(ctx.Value);
                var retVal: string;
                
				// do something
    
                return retVal;
            }
        }
    }

Any suggestion?

Thanks
Best Regards

**Comment by volkanceylan** [comment]
Only registerFormatter, method name is format not Format, there are samples in 2.1

**Comment by marcobisio** [comment]
Ah thanks I checked out this early morning the 2.1.0 but there wasn't...now in the 2.1.2 I found them!
Thank you very much
