### ISSUE TITLE
sergen .less generation issue

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#665]
Hi @volkanceylan 
I have noticed that the sergen generator, in version 2.1.2 miss the **height** parameter in .less code 

```cs
.s-Table-BaseTableXYZDialog {
    > .size { width: 650px; }
    .caption { width: 150px; }
}
```

**Comment by volkanceylan** [comment]
Yes, because all dialogs are responsive, flexbox by default. You may add .s-PropertyGrid .categories { height: xyz } if you want some initial height

**Comment by volkanceylan** [comment]
Or > .size { width: 650px; height: 400px; } etc

**Comment by Estrusco** [comment]
Ah ok. I assumed was a little bug. Thank you.
