### ISSUE TITLE
Conditional hiding of buttons

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#666]
I have the following code in the grid class (not sure how to refer to the Department.Reopen constant so I just hard coded the reference):

```
            if (Authorization.HasPermission("Department:Reopen"))
            {
                buttons.Add(new ToolButton
                {
                    Title = "Reopen Budget",
                    CssClass = "approve-button",
                    OnClick = delegate
                    {
                        if (!this.OnViewSubmit())
                            return;

                        var action = new ReopenBudgetAction();
                        action.Done += rowSelection.ResetCheckedAndRefresh;
                        action.Execute(rowSelection.GetSelectedKeys());
                    }
                });
            }
```

The permission is defined and registered:

        public class Department
        {
            public const string Delete = "Department:Delete";
            public const string Insert = "Department:Insert";
            public const string Modify = "Department:Modify";
            public const string View = "Department:View";
            public const string Admin = "Department:Admin";
            public const string Finalize = "Department:Finalize";
            public const string Reopen = "Department:Reopen";
            public const string Recalc = "Department:Recalc";
            public const string Reset = "Department:Reset";
        }
[assembly: Serenity.ComponentModel.RegisterPermissionKey(PermissionKeys.Department.Reopen)]

The permission is checked for current user's role but the button remains hidden. Many thanks in advance for your help.

**Comment by c9482** [comment]
![2016-05-10_142153](https://cloud.githubusercontent.com/assets/17013052/15159506/a300d230-16ba-11e6-9f57-876412fc1655.png)

**Comment by volkanceylan** [comment]
You probably have same issue here

https://github.com/volkanceylan/Serenity/issues/620

Apply fix on my last comment there.

**Comment by c9482** [comment]
Yes, that was it. Thank you for quick reply.
