### ISSUE TITLE
LookupEditor CascadeFrom used on Many to Many entity relationships

### ISSUE THREAD

**Issue by florin-nitulescu** [volkanceylan/Serenity#667]
The CascadeFrom functionality it's great for one to many relationships, but in the case of many to many it's complicated: the solution that I found was to create a custom LookupScript where I could include columns from the relation-table and the entity table, and control the IdField, and TextField of the returned items.

**Comment by volkanceylan** [comment]
This is also how i do it, if want to work with such lookup editors. I don't want to make LookupEditor more complicated any further. For such matters, users should better write custom editors. Of course i should document it and add more samples.

**Comment by weiguanhai** [comment]
Can you use the CascadeFrom for one to many relationships?   how make it?
I need your help, really thank you!

**Comment by florin-nitulescu** [comment]
For that case you could use the tutorial from [the guide](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html)

**Comment by weiguanhai** [comment]
yep,I have read the guide : https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html
is this page??
I follow the guide ,code step by step.  but it doesn't work?
@florin-nitulescu

**Comment by florin-nitulescu** [comment]
Can you give a sample on how your entities rows look? The master and the details.

**Comment by weiguanhai** [comment]
[BAreasRow.docx](https://github.com/volkanceylan/Serenity/files/371221/BAreasRow.docx)
[CatcherInfoForm.docx](https://github.com/volkanceylan/Serenity/files/371222/CatcherInfoForm.docx)
the BAreasRow.cs  is Country Province  City  data resource。
the CatcherInfoForm.cs is I want to show the cascade EditColumn like  the following picture
![image](https://cloud.githubusercontent.com/assets/20295114/16947412/714ff49c-4de1-11e6-92f2-e1c704fc3103.png)


the following picture is my sqlserver data
![image](https://cloud.githubusercontent.com/assets/20295114/16947481/e9ad8864-4de1-11e6-9313-36ab4735fa1f.png)
the Country Province City is all in the table...

@florin-nitulescu
