### ISSUE TITLE
how to overide MyDeleteHandler

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#668]
I do not want to true delete row when user click on delete button. I only want to give the row a deleted flag.
How to do it?

**Comment by Estrusco** [comment]
In repository, MyDeleteHandler override OnBeforeDelete() method:

```cs
    public class TableRepository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        [...]

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

        [...]

        private class MyDeleteHandler : DeleteRequestHandler<MyRow>
        {
            protected override void OnBeforeDelete()
            {
                base.OnBeforeDelete();
            }
```

See also: https://github.com/volkanceylan/Serenity/wiki/Repository-overridable-methods-and-calling-sequence#delete-handler

**Comment by PanChenhao** [comment]
Thanks for your answer. but I do not understand.  In my opinion, should not I overide ExecuteDelete?

`protected override void ExecuteDelete() {
                Connection.UpdateById(new MyRow { MaterialState = 0,id=row.id });
            }
`
This is my code. and i made it successfully

**Comment by Estrusco** [comment]
Oh yes, sorry, override ExecuteDelete. 
The ID is also in Request.EntityId

Bye

**Comment by florin-nitulescu** [comment]
Another solution it's to implement IIsActiveDeletedRow (it's only one property) on your entity row. This has integration with the grid (show hide deleted rows, undelete deleted row) and you can make on your entity endpoint a method for undelete request and use the UndeleteRequestHandler:
```c#
[HttpPost]
public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request)
{
    return new MyRepository().Undelete(uow, request);
}
```
The Undelete method on your Repository looks like this:
```c#
public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request)
{
    return new UndeleteRequestHandler<MyRow>().Process(uow, request);
}
```
You also need to add the attribute on your Grid in the Scripts project:
```c#
[IsActiveProperty(MyEntityRow.IsActiveProperty)]
public class MyEntityGrid : EntityGrid<MyEntityRow>
{
//...
}
```

**Comment by PanChenhao** [comment]
Thanks for you detailed introduction.  :)

**Comment by volkanceylan** [comment]
Thanks @florin-nitulescu, think i need to add a basic sample.
