### ISSUE TITLE
How to use IncludeColumns

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#669]
Hi

I have created following function to retrive Invoice object.

```
        public static RetrieveResponse<MyRow> Retrieve(int InvoiceId)
        {
            RetrieveRequest request = new RetrieveRequest();
            request.EntityId = InvoiceId;
            request.IncludeColumns = new System.Collections.Generic.HashSet<string>();
            request.IncludeColumns.Add(fld.JobMaterial.Name);
            request.IncludeColumns.Add(fld.JobWo.Name);
            request.IncludeColumns.Add(fld.JobJobNo.Name);
            return new MyRetrieveHandler().Process(SqlConnections.NewByKey("Default"), request);
        }
```
But the object is not have value in the matching property of IncludeColumns.
For example: JobMaterial, JobWo and JobJobNo are null in return object.

**Comment by volkanceylan** [comment]
Retrieve already returns all colums. If data is null it means columns are null or mapping is wrong

**Comment by ramveersgh** [comment]
Ahh Sorryyyyyyyyyyyyy
My Mistake, Just realize taht I was checking for wrong Id which has null Data.
Sorry Again...
