### ISSUE TITLE
how to add an input or other controls in ToolButtonContainer

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#670]
Is there some way to add a file upload control  in  ToolButtonContainer just like below? 
 buttons.Add(new ToolButton
{
....
}
 buttons.Add(new FileUploadControl
{
....
}

**Comment by volkanceylan** [comment]
No, you can't add it that way. Maybe try putting a dummy button and replacing it with jQuery after button is created. E.g. in createToolbarExtensions method.

**Comment by ChenZhaobin** [comment]
thank you very much
I doubt why it must be ToolButton ,why not div or just inherit from HtmlElement?
