### ISSUE TITLE
Switch To Typescript

### ISSUE THREAD

**Issue by 4lamosky** [volkanceylan/Serenity#671]
that's good idea to create only one project for serene no script project anymore, but i have a little problem here:

1. I use resharper and switch to typescript and causing duplicate identifier for all forms, i give one example below:
```javascript`    
export class LanguageForm extends Serenity.PrefixedContext {
        static formKey = 'Administration.Language';

    }
    export interface LanguageForm {
        LanguageId: Serenity.StringEditor;
        LanguageName: Serenity.StringEditor;
    }`
````
2. The project can build and running with error still there
3. With typescript i can't see intellisense again ...(i can live with that)
4. I have files with saltarelle now

Should i convert my existing project to typescript ?
Regards

**Comment by ChenZhaobin** [comment]
@volkanceylan Hi charming man,these files below are missing:
https://raw.githubusercontent.com/volkanceylan/Serene/master/Serene/Serene.Script/Imports/ServerImports/ServerImports.tt
https://raw.githubusercontent.com/volkanceylan/Serene/master/Serene/Serene.Script/Imports/CodeGenerationHelpers.ttinclude

**Comment by volkanceylan** [comment]
New Serene comes with one project only but this doesn't mean there will be any changes to your project. I just dont want new users to write Saltaralle code anymore.

It might be a Resharper problem, maybe its not considering settings in tsconfig.json and ignoring TypeScriptCompiledBlocked setting in Web.csproj. If possible disable Resharper for TypeScript. One possibility is you have MyProject.Web.d.ts included into your project, it shouldn't be. Check under scripts/site/ folder if there is a MyProject.Web.d.ts and if its included, exclude it from project.

Also check that you have this exclude config in tsconfig.json, replace Serene with your project name:

```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "declaration": true,
        "emitBOM": true,
        "sourceMap": true,
        "outFile": "Scripts/site/Serene.Web.js",
        "target": "ES5"
    },
    "exclude": [
        "Scripts/site/Serene.Web.d.ts"
    ]
}
```

I didn't have that exclude part in tsconfig.json before. Updated guide.

Yes, you should try porting project, but me also have an app with 1000+ pages, which would take a very long time to port to TypeScript. So, i'll try to preserve compability as long as possible.

**Comment by volkanceylan** [comment]
@ChenZhaobin, yes as that project is deleted now, updated their reference to an old commit in guide, thanks.

**Comment by ChenZhaobin** [comment]
@volkanceylan thank you ,it works well!

**Comment by 4lamosky** [comment]
thank for your advice
