### ISSUE TITLE
Add Social Logins to Serenity 

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#672]
I need to add social logins to existing accounts to serenity

Google , Facebook, Twitter Authentication using OAuth Provider

**Comment by volkanceylan** [comment]
See https://github.com/DotNetOpenAuth/DotNetOpenAuth

**Comment by samdubey** [comment]
Thanks

**Comment by ShifanilaSenthil** [comment]
How could we add Social Media logins instead of SignUp Page?
