### ISSUE TITLE
Programmatically add grid filters

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#673]
Dear @volkanceylan,
before the last update I used to do something like that:

    this.addEqualityFilter(BSMultiSelectEditor).call(this, "EquipmentProductName", "Product", <BSMultiSelectOptions>{
        lookupKey: "CSH.EquipmentProductName",
        includeSelectAllOption: true,
        maxHeight: 200,
        enableFiltering: true,
        enableCaseInsensitiveFiltering: true
    }, e => {
        let val = Serenity.EditorUtils.getValue(e.widget);
        if (e.active = !!(val && val.length))
            e.request.Criteria = Serenity.Criteria.join(e.request.Criteria, "and", [[e.field], "in", [val]]);
    });
    
	
    this.addEqualityFilter(Serenity.LookupEditor).call(this, 'EquipmentSiteId', null, { lookupKey: "CSH.Site" }, null, null, null);

The first is a BSMultiSelectEditor (added with your tutorial) and the 2nd is a classic lookup.

Now I'm struggling a bit with the new syntax:
- the addQuickFilter method is the right one ?
- when I've to use the findQuickFilter method ?

And if I have understood, to add a filter declaratively I can use the QuickFilter attribute in the xyzColumns.cs ...right?

Thanks as usual for your support
Bye

**Comment by volkanceylan** [comment]
addQuickFilter method is the right one.

```ts
            this.addQuickFilter({
                type: BSMultiSelectEditor,
                field: "EquipmentProductName",
                title: "Product",
                options: {
                    lookupKey: "CSH.EquipmentProductName",
                    includeSelectAllOption: true,
                    maxHeight: 200,
                    enableFiltering: true,
                    enableCaseInsensitiveFiltering: true
                }
            });
```

This should be more readable for TypeScript.

You may also add this filter in your Columns.cs declaratively, using it like [BSMultiSelectEditor(...), QuickFilter]

**Comment by volkanceylan** [comment]
findQuickFilter can be used to find a declaratively created quick filter widget in case you need it, as you won't have reference to that widget unless you create it manually.

**Comment by marcobisio** [comment]
Copy that!
And for the classic filter should be the same "story" but with the Serenity.LookupEditor type I guess...
Well,I'll try @volkanceylan. ...

Thank you very much!
Bye
