### ISSUE TITLE
Conditional coloring of grid row

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#674]
Is it possible to change the text font color for a row based on certain column's value?

**Comment by volkanceylan** [comment]
You may add a CSS class to row, by overriding GetItemCssClass method of your grid. Then color it using less / css.

**Comment by c9482** [comment]
Thanks for your help and quick (as usual) reply.

**Comment by volkanceylan** [comment]
Added sample in 2.2.0

**Comment by c9482** [comment]
Thanks for the sample.
