### ISSUE TITLE
[HowTo] add columnpicker capability to SlickGrid

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#675]
Dear all,
here there is a quick guide on how to activate the columnpicker functionality on the SlickGrids.
1) add slick.columnpicker.d.ts file in Scripts\typings\slickgrid folder (you have to create the last level). Such file will be something like this:

    declare namespace Slick.Controls {
        class ColumnPicker {
            constructor(columns: Slick.Column[], grid: Slick.Grid, options?: Slick.Controls.ColumnPickerOptions);
        }
    
        interface ColumnPickerOptions {
            fadeSpeed?: number;
        }
    }

2) in your xyzGrid.ts override the createSlickGrid() method in the following way:

    protected createSlickGrid(): Slick.Grid {
        let grid = super.createSlickGrid();
        let columnPicker = new Slick.Controls.ColumnPicker(grid.getColumns(), grid);
        return grid;
    }

3) add the following instruction in your _LayoutHead.cshtml (just before your MyProject.Web.js line):

    @Html.Script("~/Scripts/SlickGrid/Controls/slick.columnpicker.js")

Edit: forgot to add the final result...
![image](https://cloud.githubusercontent.com/assets/17425690/15229440/5e89741c-1891-11e6-8be3-8e442d091d2b.png)

@volkanceylan: if it sounds good (and if you agree), I'll move such informations on a wiki article.

Best Regards

**Comment by volkanceylan** [comment]
Thank you very much @marcobisio, i'm sure many users would like to see this in wiki

**Comment by marcobisio** [comment]
A bit quick&dirty, but here it is:
https://github.com/volkanceylan/Serenity/wiki/SlickGrid:-Column-Picker-(TypeScript-only)

Thanks to you for sharing all your (hard) job with us :-)
Bye

**Comment by wldkrd1** [comment]
Also, don't forget to reference ~/Content/slick.columnpicker.css in _LayoutHead.cshtml, otherwise you won't get the nice styling it provides.
