### ISSUE TITLE
Is there a way to reroute an edit link to another view?

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#676]
Is anything like this possible or to I need to create a custom dialog template?

**Comment by volkanceylan** [comment]
You need to add a custom formatter, or better use already available UrlFormatter

**Comment by volkanceylan** [comment]
Don't add EditLink, just [UrlFormatter(...)]

**Comment by swordz36** [comment]
My client wants something like this.... 
[ClaimProcessing.pdf](https://github.com/volkanceylan/Serenity/files/263694/ClaimProcessing.pdf)
I am considering creating a strongly typed view using razor for the layout. and just using the actions on the Endpoint/Controller to update the data to the database.

**Comment by volkanceylan** [comment]
Yep, it's possible

**Comment by swordz36** [comment]
![image](https://cloud.githubusercontent.com/assets/17201265/15256216/125b8ace-1906-11e6-8ec8-31327f23c17a.png)  I am tring to figure out how get this edit link to call my custom action.

**Comment by volkanceylan** [comment]
use UrlFormatter
