### ISSUE TITLE
tt error when upgrading to 2.1.x

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#677]
So I just took the plunge and upgraded to the 2.1.x (latest stable build). When following the upgrade guide, I got to the point where I needed to change to the ClientTypes.tt files. I get this error when saving:

![image](https://cloud.githubusercontent.com/assets/11448029/15266925/4714113e-1981-11e6-87e6-93121143a8c0.png)

Something similar happens with the ServerTypings.tt as well. Project runs okay, no notable difference just wanted to make sure this is okay or how can I fix it.

UPDATE: Just attempted to Transform all T4s and I get the same 50 errors from the screenshot...so how can I fix this?

**Comment by volkanceylan** [comment]
You probably didn't replace but copy paste code to end. Replace code with given one.

**Comment by wdhodges** [comment]
Alright I'll give it a try

**Comment by wdhodges** [comment]
So I went to ClientTypes.tt, delete all content. Got the raw file contents from 

https://raw.githubusercontent.com/volkanceylan/Serene/master/Serene/Serene.Web/Modules/Common/Imports/ClientTypes/ClientTypes.tt

Pasted it into ClientTypes.tt and then replaced all `Serene` with MyProject. I still get the same errors.

**Comment by volkanceylan** [comment]
Did you take CodeGenerationHelpers aldo

**Comment by volkanceylan** [comment]
Also

**Comment by wdhodges** [comment]
I just ended up creating a new project. Since I was in the early stages of my application it was simple to recreate the tables using sergen. I like the new layout. A lot.
