### ISSUE TITLE
T4 Template not updating

### ISSUE THREAD

**Issue by paulobriennz** [volkanceylan/Serenity#678]
Hi. For a start, Awesome Template you have designed.

An issue i am seeing is trying to follow your tutorial to add Enums.  I've added all the C# side OK and project builds fine,  I am going to Build > Transform All T4 Templates.  It says successful but when i go to run the app and click on the New xxx button i get a script error like you refer to in your notes as if the T4 templates are not up to date - cant find enum type

I also was getting a warning message (not error) like below when running T4 generation process.

http://stackoverflow.com/questions/35412460/compiling-transformation-the-type-object-is-defined-in-an-assembly-that-is-no 

I ran the Visual Studio 2015 Update 2 as per this article and the warning has gone away when i run the Transform T4 Templates process now.

But, i still get the error Can't find ...... enum type!

Is there a way i can clear the templates and force them to build again?  Sorry im a newbie with T4..
I'm not missing the point am I?  my understanding is when you make a change to server side code like the enums that can affect the client side, you go to run Transform All T4 Templates to up date the client side?  Or is there some other step i need to do as well?

**Comment by volkanceylan** [comment]
Another user also reported this but cant reproduce it. It is probably related to switch to TypeScript. Does TSC, a black console window run after transforming templates? If not save a TS file, it should compile. Or better update to 2.1.4

**Comment by paulobriennz** [comment]
thanks for your comments.  I have sorted issue.  i did two things and not sure which one fixed, but reading a few guides on issues with T4 files not compiling in VS2015, i did the following:

1) added the C:\Program Files (x86)... typescript folder to my System Path (so i can open a new CMD window now and type TSC and it it finds it, previously it wasnt).

2) Run Visual Studio as Administrator

**Comment by paulobriennz** [comment]
oh, and i upgarded packages from 2.1.2 to 2.1.4 before i started the other troubleshooting but didnt fix the issue.. i think more a VS issue than an issue with Serenity

**Comment by volkanceylan** [comment]
Ah, sorry, i missed one topic, you need to take CodeGenerationHelpers.tt and ServerTypings.tt from latest version too. I have added code that executes TSC after running templates to 2.1.4 in these files. You need to copy/paste them and replace Serene with your project name, e.g. MyProject. Then you'll see that black window.

There is something wrong with compile on save feature in Visual Studio. It only works in 2015 and looks like sometimes doesn't.

You may try removing TypeScriptCompileBlocked from your Web.csproj file, so that .ts files built by Visual Studio. I added it to use Compile on Save feature, making use of tsconfig.json.

**Comment by volkanceylan** [comment]
In 2.1.5 i've found a way to execute TSC on build of Serene.Web, without blocking build on error. I shouldn't let TypeScript errors to prevent building of Serene.Web.dll, as T4 files uses it to generate TypeScript / other code. Otherwise i'd fall into a chicken - egg problem.

Basically you need to add line below under CompileSiteLess section bottom of your Serene.Web.csproj:

```xml
  <Target Name="CompileSiteLess" AfterTargets="AfterBuild">
    <Exec Command="&quot;$(ProjectDir)tools\node\lessc.cmd&quot; &quot;$(ProjectDir)Content\site\site.less&quot; &gt; &quot;$(ProjectDir)Content\site\site.css&quot;">
    </Exec>
    <Exec Command="&quot;$(TscToolPath)\$(TypeScriptToolsVersion)\$(TscToolExe)&quot; -project &quot;$(ProjectDir)tsconfig.json&quot;" ContinueOnError="true" />
  </Target>
```

**Comment by paulobriennz** [comment]
If I have upgraded to 2.1.5 do I need to do the below?

**Comment by volkanceylan** [comment]
Yes, you should. Portions specific to Serene can'be updated by Serenity updates.

**Comment by MaximilianoSoftur** [comment]
Hola, al utilizar el Transform T4 Templates, sobre un proyecto utilizando serenity. Se me esta reiniciando el visual studio solo. Me pasa esto en dos escritorios con windows 10 y VS 2015. En uno con windows 7 funciona bien me genera todo bien. Me podrian ayudar. Saludos

**Comment by MaximilianoSoftur** [comment]
Hello, when using the Transform T4 Templates, on a project using serenity. I'm restarting visual studio alone. This happens to me on two desktops with windows 10 and VS 2015. In one with windows 7 it works fine it generates everything fine. Could you help me. Thank you!

**Comment by Deeplalka** [comment]
I'm too geting following error:
Running transformation: MsieJavaScriptEngine.JsRuntimeException: Object expected
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate(String expression)
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.SetupJsEngine() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 251
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.List() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 262
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TransformText() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\ServerTypings.tt:line 32		E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude	251	
 can any one gaide me for this please

im using win7 64 bit os and vs2017 community with sql server 2008 and google chrome leatest version
