### ISSUE TITLE
Subforms in IE on WIndows 10 need re sizing to see any controls

### ISSUE THREAD

**Issue by paulobriennz** [volkanceylan/Serenity#679]
On several machines I've tried from using Internet Explorer (Windows 2012R2 and Windows 10), the sub forms that open up show no controls until you grab and re-size the sub-form, then you can see the controls.

Same Subforms look fine on Chrome...

**Comment by volkanceylan** [comment]
Hmm must be about flexbox, will have a look, thanks

**Comment by volkanceylan** [comment]
This should be fixed in 2.1.5

**Comment by paulobriennz** [comment]
Great, yes I have just updated to 2.1.5 and can confirm working.

 

Thank you
