### ISSUE TITLE
Remove Delete button from a Form

### ISSUE THREAD

**Issue by SirSpam** [volkanceylan/Serenity#68]
I assume that its done in the MyTableDialog.cs, and Ive tried the method listed in the tutorial for removing buttons from the grid:

``` 
protected override List<ToolButton> GetButtons()
        {
            var buttons = base.GetButtons();
            buttons.RemoveAt(0);
            return buttons;
        }
```
On the Dialog.cs page, but it seems to be having a problem with the GetButtons() 

Figured it out, GetToolbarButtons()

**Comment by zehranur** [comment]
if u want to remove all buttons u can do like that;
 protected override List<ToolButton> GetToolbarButtons()
        {
            var buttons = new List<ToolButton>();
            return buttons ;
         }

But i suppose u just try to remove "delete" buttons. then ur methot is runing with me may be it needs rebuild .
  protected override List<ToolButton> GetToolbarButtons()
        {
            var buttons = base.GetToolbarButtons();
            buttons.RemoveAt(2);
            return buttons ;
        }
