### ISSUE TITLE
How to properly use the URLFormatter tag that was just introduced?

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#680]
So I have saved a string in my database for the upload path, and use the FileUploadEditor to upload it in MyEntRow.cs. In MyEntColumn.cs I'm using URLFormatter so that I can just have the users click the link and the pdf opens in another tab. The issue that I'm running into is when I click the button I don't get the document because the string and the document path do not match. 

If I hover over the 'view' link in MyEntColumn.cs the path it's searching for is `localhost:123//CommCenter/Kb/Kb/General/000.....pdf`

But I need it to search for `localhost:123/upload/Kb/General/000.....pdf`I can view the document if it to edit, but not everyone will be able to modify.

Any idea how to resolve?

Love the new updates by the way!

**Comment by wdhodges** [comment]
I know there is the new URL formatter, which is what I'm using. But for the UrlFormat, I place /upload/ yet I can't seem to figure out how to get the rest of the path from the Document string as listed above.

**Comment by volkanceylan** [comment]
UrlFormatter(UrlFormat="~/upload/{0}")

**Comment by wdhodges** [comment]
Thank you!!!

**Comment by wdhodges** [comment]
Is there somewhere I can go to find out how to use all of these formatters and their arguments correctly without bothering you with issues?

**Comment by serin** [comment]
No, unfortunately, it's impossible to document all

**Comment by volkanceylan** [comment]
One for UrlFormatter
https://volkanceylan.gitbooks.io/serenity-guide/content/grids/formatter_types.html

**Comment by wdhodges** [comment]
Thank you Volkan. If I had a larger understanding of all the attributes I'll start documenting. But there's so many lol

**Comment by volkanceylan** [comment]
There are not so many actually. Most are documented or sampled. Some are in wiki.
