### ISSUE TITLE
Permissions are broken

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#681]
So I was testing it out, when you mark a role with the Northwind permission for Customers to Create/Update, you cannot actually create nor update a customer. I have verified this in Firefox and Edge. Even if you have all, read - update and delete you still cannot update, edit, create a new entry.

Build: 2.1.4

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/620

**Comment by wdhodges** [comment]
Thanks you!

**Comment by wdhodges** [comment]
Changed the UserPermissions to ScriptUserPermissions as suggested in #620, still doesn't work.

**Comment by wdhodges** [comment]
![image](https://cloud.githubusercontent.com/assets/11448029/15272293/20622912-1a40-11e6-93b0-8b4831d2de86.png)

**Comment by wdhodges** [comment]
Doesn't work if I just grant the permission to the user instead of going through a role.

**Comment by wdhodges** [comment]
I'm a dumbass and need sleep. I figured my single miss typed letter out.
