### ISSUE TITLE
How to add an customized button 

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#682]
How to add an customized button in Order Edit page, and can it be conditional change?
In the guide, i see the paragraph: 
> Most Serenity editing dialogs has this familiar interface, though you can always customize buttons, fields, add tabs, and other interface elements.

But i do not know how to do it. Is anyone can help me?

**Comment by volkanceylan** [comment]
Search in Serene source for getToolbarButtons, getButtons. There you can see several samples on adding buttons, enabling disabling them etc.

**Comment by PanChenhao** [comment]
I have found it, thanks. Another question is, Can the button change based on value? for example,
If order type=1, The button text should be A; If order type=2, the button text should be B. How to do it?

**Comment by volkanceylan** [comment]
Better put two buttons and toggle

**Comment by PanChenhao** [comment]
How to get order type in typescript? then I can use this value to decide which button shown.

**Comment by PanChenhao** [comment]
I know how to do it. Thank you for your patient.
