### ISSUE TITLE
Breaking Issue with FileUploadEditior

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#683]
I have upgraded to the new 2.1.5. 

When I go to upload a file using the FileUploadEditior it says that a document is required (see picture) however, I have uploaded a file.

![image](https://cloud.githubusercontent.com/assets/11448029/15278023/7a26106c-1ae0-11e6-8165-c70952030b51.png)

What looks like that it's not saving it to the /upload/temp/ file when it's initially uploaded. Any idea what could be the issue?

**GeneralKBRows.cs**
![image](https://cloud.githubusercontent.com/assets/11448029/15278361/a6466a70-1ae5-11e6-9de5-43af4d961884.png)

**GeneralKBColumns.cs**
```
public class GeneralKbColumns
    {
        [EditLink, Width(300)]
        public String Title { get; set; }

        [Width(600), TextAreaEditor(Cols = 4)]
        public String Description { get; set; }

        [UrlFormatter(DisplayFormat = "View Document",UrlFormat = "~/upload{0}",Target = "_blank")]
        public String Document { get; set; }
        [Width(200), DateFormatter(DisplayFormat = "MM-dd-yyyy")]
        public DateTime PublishDate { get; set; }
        [Width(200), LookupEditor(typeof(Scripts.GeneralTagLookup)), QuickFilter]
        public String GeneralTag { get; set; }

    }

```
UPDATE: So when I debug the program, on my local machine it works perfectly fine. It puts the file in /upload/temporary/~ but when I send it through Bitbucket, then trigger a build in TeamCity, OctoPack it and deploy it to IIS something happens and it takes the /upload/temporary/~ off. 

Enviroment: Debugging in Microsoft Edge and Firefox. Production is in Chrome (issue) and Firefox (issue)

**Comment by wdhodges** [comment]
I reverted back to 2.1.4 but it's still not working.

**Comment by volkanceylan** [comment]
There is nothing wrong with file uploads in 2.1.5. Check file permissions on app_data/upload folder.

**Comment by volkanceylan** [comment]
UrlFormat = "~/upload{0}" 

this is also wrong,  should be "~/upload/{0}"

**Comment by wdhodges** [comment]
I checked the permissions, it's all good to go. It was working prior to the upgrade to 2.0+. Could there be another issue somewhere that I'm missing?

**Comment by volkanceylan** [comment]
I have no idea. Check web.config settings. I'm pretty sure its not about Serenity as it works locally. You have pretty complex publish process. I just copy paste.

**Comment by wdhodges** [comment]
Okay so. I promoted that build to our m-Production server and it worked. I'm not sure what the difference is with test and m-Production but never the less it worked.
