### ISSUE TITLE
Latest update to serenity via NuGet

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#684]
[Failure] Could not find a part of the path 'C:\xxx.Web\Scripts\typings\rsvp\rsvp.d.ts'.
[Failure] Could not find file 'C:\xxx.Web\Scripts\serenity\Serenity.CoreLib.d.ts'.
[Failure] Could not find file 'C:\xxx.Web\Scripts\serenity\Serenity.Externals.d.ts'.
[Failure] Could not find file 'C:\xxx.Web\Scripts\serenity\Serenity.Externals.Slick.d.ts'.
[Failure] Could not find a part of the path 'C:\xxx.Web\Scripts\typings\jqueryui\jqueryui.d.ts'.

Will fix this manually but might need a quick check in the package.

**Comment by volkanceylan** [comment]
I couldn't understand what you mean here

**Comment by wdhodges** [comment]
Do you have any spaces in your projects name?

**Comment by solabar** [comment]
Nope no spaces.
It's all working, seemed more like a warning than an error.

**Comment by marcobisio** [comment]
Same "issue" here upgrading from 2.1.2 to 2.1.8...

**Comment by marcobisio** [comment]
Uhm slickgrid.d.ts is an empty file (0 byte) both in my "upgraded" project and in a brand new one...

**Comment by volkanceylan** [comment]
Yep it's empty, not a problem

**Comment by marcobisio** [comment]
Ok no problem then!
Btw in the upgrade process from nuget I get this:

    [Failure] Could not find file 'C:\......xyz.Web\Scripts\typings\slickgrid\slickgrid.d.ts'.
    [Failure] Could not find a part of the path 'C:\......xyz.Web\Scripts\typings\rsvp\rsvp.d.ts'.
    [Failure] Could not find a part of the path 'C:\......xyz.Web\Scripts\serenity\Serenity.CoreLib.d.ts'.

The application seems to be working fine, but just to share this warning with you...needless to say, the previous upgrade (I mean before 2.1.2) did not report this failure message...

Thanks
Bye

**Comment by volkanceylan** [comment]
The errors you get are from TypeScript language service, they are intellisense errors, while NuGet is removing and re-adding package contents to your project. So this is not a problem at all, especially with Serenity packages.
