### ISSUE TITLE
DefaultValue utc datetime

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#685]
Dear @volkanceylan, 
I was wondering if there is already a way to add the current utc date with the DefaultValue attribute in my xyzRow.
If not, which is the better way to do that? TypeScript Side when open the new xyzDialog or it's better to manipulate the row obj server side? 

Thank you very much for you support
Bye

**Comment by volkanceylan** [comment]
Add [DateKind(DateTimeKind.Utc)] to your field.

**Comment by marcobisio** [comment]
Ah wonderful...I didn't know that attribute!

Thank you!
Bye

**Comment by marcobisio** [comment]
One more

**Comment by volkanceylan** [comment]
There is no such precision

**Comment by marcobisio** [comment]
Thanks for the quick answer!
I'll try to set directly in the entity...

Have a nice evening!
Bye

**Comment by volkanceylan** [comment]
I mean it doesn't get any precision setting. It sets what it gets from client side. You probably use DateTimeEditor, which of course has 1 minute precision.

**Comment by marcobisio** [comment]
Yes you're right,but actually is an hidden field (creation date)...I'll try again removing the useless editor...

**Comment by marcobisio** [comment]
I don't know why but even without the DateTimeEditor attribute, the datetime field is always with 00 seconds...

**Comment by volkanceylan** [comment]
It might have DateTime editor by default, even if you don't set one explicitly. Anyway you shouldnt let client side set such a value. It should be done in SetInternalFields.

**Comment by marcobisio** [comment]
Ah ok thanks for the suggestion!
I'll do in that way...

Thanks again! 
Bye

**Comment by naveenare** [comment]
with out form fields can we store current user and current time in database.
