### ISSUE TITLE
PDF report shows bulk selection check boxes

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#687]
One thing that broke with the new column picker functionality is that the check boxes are shown in the column selection dialog and PDF report (see below):

![2016-05-16_160029](https://cloud.githubusercontent.com/assets/17013052/15308368/1a100972-1ba2-11e6-9e9b-644b8ada8779.png)

**Comment by c9482** [comment]
Is there a way to disable column picker as a workaround until this is fixed?

**Comment by volkanceylan** [comment]
It shouldnt be about column picker. PDF output was probably skipping that column before. Ill fix that soon.

**Comment by volkanceylan** [comment]
On a second thought, you can use columnTitles option of PdfExportHelper, to change title for that column in PDF to whitespace string " ". See ProductGrid.ts for a sample. That column has id of __select__,

so 
{
   columnTitles: {
       __select__: " "
   }
}

**Comment by volkanceylan** [comment]
PDF export won't include that row selection column by default in next version. You can copy latest source from Serene now though:

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Reporting/PdfExportHelper.ts

**Comment by c9482** [comment]
I don't currently have PdfExportHelper.ts in my project. Where do I place it? When I put it in the same location as the .cs version, I get whole bunch of compile errors?

**Comment by c9482** [comment]
Yes, looks like that file came with one of the updates but was not included on the project. As soon as I include it and re-compile, I get errors. Sorry, TypeScript is still foreign to me.
![2016-05-16_160029](https://cloud.githubusercontent.com/assets/17013052/15328777/b65b53a8-1c1b-11e6-958e-fb8aeeb7265c.png)

**Comment by volkanceylan** [comment]
You need to also include typings (kinda imports) for jsPDF. I remember sending you this helper (PdfExportHelper.ts) before, otherwise your PDF table wouldn't work. Is this some other project?

**Comment by volkanceylan** [comment]
Typings are under YourProject.Web\Scripts\typings\jspdf

**Comment by c9482** [comment]
The folder jspdf was empty in Solution Explorer. I had to manually include
the 2 .ts files which were physically in that folder but were not
associated with the solution.

I think I am starting to understand the problem: upgrading the application
to new package level is not enough, many manual adjustments are still
needed especially with the TypeScript stuff.

Best regards,

Mark C. Orciuch
N e x t  G e n e r a t i o n  S o l u t i o n s, L t d.
e-mail: mark_orciuch@ngsltd.com
website: http://www.ngsltd.com
LinkedIn: http://www.linkedin.com/in/ngsltd
Twitter: http://twitter.com/ngsltd
Twitter: http://twitter.com/activenwi
YouTube: http://www.youtube.com/user/ngsltdtube
office: 219-488-9066
mobile: 219-488-9002
fax: 815-572-8292

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material.  Any review, re-transmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and destroy this material.

**Comment by volkanceylan** [comment]
Serene is not currently updatable by package updates. And jsPDF and that helper is not part of Serenity yet, it's implemented in Serene only. When you update packages, only content withing Serenity packages, e.g. Serenity.Web etc is updated. I usually wait till some feature is complete before integrating it into Serenity. And some features, like wkhtmltopdf for example, can't be integrated, as it would create extra dependencies and large size to Serenity packages.

**Comment by volkanceylan** [comment]
And it's not only about TypeScript. Story was same with Saltaralle. But as Serene didn't get so much changes like now for some time, you probably didn't notice, and could live without migrating Serene changes manually.

**Comment by c9482** [comment]
I still don't really understand TypeScript and how it replaces certain features in Serenity. Not even sure how .ts files get compiled.

I eliminated error in PdfExportHelper.ts but the generated PDF still contains that extra column. The workaround below requires using TypeScript but my grid class is still .cs. Do I have to convert toTypeScript to use this feature? Looks like there is a mix of .cs and .ts in my project and some features now only work with .ts? Please explain.

{
   columnTitles: {
       __select__: " "
   }
}

**Comment by volkanceylan** [comment]
No, all features should also work with Saltaralle, just i'm writing new code with TypeScript.

I suppose you have PdfExportHelper.cs from an older Serene version right? It was an import class, that actually was calling code generated from TypeScript. You included PdfExportHelper.js which was output of that TypeScript code that i wrote before. Now you should remove that PdfExportHelper.js file, and include PdfExportHelper.ts in your web project. When compiled that .ts file goes outputted into YourProject.Web\scripts\site\YourProject.Web.js file. Just like Saltaralle code gots compiled into YourProject.Web\scripts\site\YourProject.Script.js file. 

Now if you don't have YourProject.Web.js included in your _LayoutHead.cshtml, you should include it just after YourProject.Script.js.

And as call signature for PdfExportHelper is changed a bit, you should modify your Saltaralle import like below:

```cs
namespace Serene.Common
{
    using Serenity;
    using System;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;

    [Imported]
    public class PdfExportHelper
    {
        public static ToolButton CreateToolButton(PdfExportOptions options)
        {
            return null;
        }

        public static ToolButton ExportToPdf(PdfExportOptions options)
        {
            return null;
        }
    }

    [Imported, Serializable]
    public class PdfExportOptions
    {
        public string IDataGrid Grid { get; set; }
        public Func<bool> OnViewSubmit { get;set; }
        public string Title { get; set; }
        public string Hint { get; set; }
        public bool? Separator { get; set; }
        public string ReportTitle { get; set; }
        public double? TitleTop { get; set; }
        public double? TitleFontSize { get; set; }
        public double? FileName { get; set; }
        public bool? PageNumbers { get; set; }
        public JsDictionary<string, string> ColumnTitles { get; set; }
        public AutoTableOptions TableOptions { get; set; }
    }
}
```

Now where you create the PDF button, you write

PdfExportHelper.CreateToolButton(new PdfExportOptions {
     Grid = this,
     OnViewSubmit = () => this.OnViewSubmit()
     //, ColumnTitles = new JsDictionary<string, string> {
     //      { "__select__": "" }
     //}
});

I commented ColumnTitles because in latest PdfExportHelper.ts, i am filtering that checkbox column, so you need to override its title. It won't be shown simply.

**Comment by volkanceylan** [comment]
If you don't have your project TypeScript configured, you may still use PdfExportHelper.js extracted from latest Serene.Web.js:

```js
(function (Serene) {
    var Common;
    (function (Common) {
        var PdfExportHelper;
        (function (PdfExportHelper) {
            function toAutoTableColumns(srcColumns, columnStyles, columnTitles) {
                return srcColumns.map(function (src) {
                    var col = {
                        dataKey: src.id || src.field,
                        title: src.name || ''
                    };
                    if (columnTitles && columnTitles[col.dataKey] != null)
                        col.title = columnTitles[col.dataKey];
                    var style = {};
                    if ((src.cssClass || '').indexOf("align-right") >= 0)
                        style.halign = 'right';
                    else if ((src.cssClass || '').indexOf("align-center") >= 0)
                        style.halign = 'center';
                    columnStyles[col.dataKey] = style;
                    return col;
                });
            }
            function toAutoTableData(entities, keys, srcColumns) {
                var el = document.createElement('span');
                var row = 0;
                return entities.map(function (item) {
                    var dst = {};
                    for (var cell = 0; cell < srcColumns.length; cell++) {
                        var src = srcColumns[cell];
                        var fld = src.field || '';
                        var key = keys[cell];
                        var txt = void 0;
                        var html = void 0;
                        if (src.formatter) {
                            html = src.formatter(row, cell, item[fld], src, item);
                        }
                        else if (src.format) {
                            html = src.format({ row: row, cell: cell, item: item, value: item[fld] });
                        }
                        else {
                            dst[key] = item[fld];
                            continue;
                        }
                        if (!html || (html.indexOf('<') < 0 && html.indexOf('&') < 0))
                            dst[key] = html;
                        else {
                            el.innerHTML = html;
                            if (el.children.length == 1 &&
                                $(el.children[0]).is(":input")) {
                                dst[key] = $(el.children[0]).val();
                            }
                            else if (el.children.length == 1 &&
                                $(el.children).is('.check-box')) {
                                dst[key] = $(el.children).hasClass("checked") ? "X" : "";
                            }
                            else
                                dst[key] = el.textContent || '';
                        }
                    }
                    row++;
                    return dst;
                });
            }
            function exportToPdf(options) {
                var g = options.grid;
                if (!options.onViewSubmit())
                    return;
                includeAutoTable();
                var request = Q.deepClone(g.view.params);
                request.Take = 0;
                request.Skip = 0;
                var sortBy = g.view.sortBy;
                if (sortBy != null)
                    request.Sort = sortBy;
                request.IncludeColumns = [];
                for (var _i = 0, _a = g.slickGrid.getColumns(); _i < _a.length; _i++) {
                    var column = _a[_i];
                    request.IncludeColumns.push(column.id || column.field);
                }
                Q.serviceCall({
                    url: g.view.url,
                    request: request,
                    onSuccess: function (response) {
                        var doc = new jsPDF('l', 'pt');
                        var srcColumns = g.slickGrid.getColumns();
                        var columnStyles = {};
                        var columns = toAutoTableColumns(srcColumns, columnStyles, options.columnTitles);
                        var keys = columns.map(function (x) { return x.dataKey; });
                        var entities = response.Entities || [];
                        var data = toAutoTableData(entities, keys, srcColumns);
                        doc.setFontSize(options.titleFontSize || 10);
                        doc.setFontStyle('bold');
                        var reportTitle = options.reportTitle || g.getTitle() || "Report";
                        doc.autoTableText(reportTitle, doc.internal.pageSize.width / 2, options.titleTop || 25, { halign: 'center' });
                        var totalPagesExp = "{{T}}";
                        var pageNumbers = options.pageNumbers == null || options.pageNumbers;
                        var autoOptions = $.extend({
                            margin: { top: 25, left: 25, right: 25, bottom: pageNumbers ? 25 : 30 },
                            startY: 60,
                            styles: {
                                fontSize: 8,
                                overflow: 'linebreak',
                                cellPadding: 2,
                                valign: 'middle'
                            },
                            columnStyles: columnStyles
                        }, options.tableOptions);
                        if (pageNumbers) {
                            var footer = function (data) {
                                var str = data.pageCount;
                                // Total page number plugin only available in jspdf v1.0+
                                if (typeof doc.putTotalPages === 'function') {
                                    str = str + " / " + totalPagesExp;
                                }
                                doc.autoTableText(str, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - autoOptions.margin.bottom, {
                                    halign: 'center'
                                });
                            };
                            autoOptions.afterPageContent = footer;
                        }
                        doc.autoTable(columns, data, autoOptions);
                        if (typeof doc.putTotalPages === 'function') {
                            doc.putTotalPages(totalPagesExp);
                        }
                        var fileName = options.reportTitle || "{0}_{1}.pdf";
                        fileName = Q.format(fileName, g.getTitle() || "report", Q.formatDate(new Date(), "yyyyMMdd_HHmm"));
                        doc.save(fileName);
                    }
                });
            }
            PdfExportHelper.exportToPdf = exportToPdf;
            function createToolButton(options) {
                return {
                    title: options.title || '',
                    hint: options.hint || 'PDF',
                    cssClass: 'export-pdf-button',
                    onClick: function () { return exportToPdf(options); },
                    separator: options.separator
                };
            }
            PdfExportHelper.createToolButton = createToolButton;
            function includeJsPDF() {
                if (typeof jsPDF !== "undefined")
                    return;
                var script = $("jsPDFScript");
                if (script.length > 0)
                    return;
                $("<script/>")
                    .attr("type", "text/javascript")
                    .attr("id", "jsPDFScript")
                    .attr("src", Q.resolveUrl("~/Scripts/jspdf.min.js"))
                    .appendTo(document.head);
            }
            function includeAutoTable() {
                includeJsPDF();
                if (typeof jsPDF === "undefined" ||
                    typeof jsPDF.API == "undefined" ||
                    typeof jsPDF.API.autoTable !== "undefined")
                    return;
                var script = $("jsPDFAutoTableScript");
                if (script.length > 0)
                    return;
                $("<script/>")
                    .attr("type", "text/javascript")
                    .attr("id", "jsPDFAutoTableScript")
                    .attr("src", Q.resolveUrl("~/Scripts/jspdf.plugin.autotable.min.js"))
                    .appendTo(document.head);
            }
        })(PdfExportHelper = Common.PdfExportHelper || (Common.PdfExportHelper = {}));
    })(Common = Serene.Common || (Serene.Common = {}));
})(Serene || (Serene = {}));
```

**Comment by volkanceylan** [comment]
Sorry, updated JS code above

**Comment by c9482** [comment]
Still struggling - this is more complex to integrate than I thought it
would be. I tried replacing the code in PdfExportHelper.cs as above but I
get compile errors. I don't have
*LCBudgets.Web\scripts\site\LCBudgets.Web.js* anywhere. I only see
*LCBudgets.Script.js*.

Also, is my TypeScript configured properly? See below.

Perhaps it may be easier to zip up my entire solution and send it to you?


​

Best regards,

Mark C. Orciuch
N e x t  G e n e r a t i o n  S o l u t i o n s, L t d.
e-mail: mark_orciuch@ngsltd.com
website: http://www.ngsltd.com
LinkedIn: http://www.linkedin.com/in/ngsltd
Twitter: http://twitter.com/ngsltd
Twitter: http://twitter.com/activenwi
YouTube: http://www.youtube.com/user/ngsltdtube
office: 219-488-9066
mobile: 219-488-9002
fax: 815-572-8292

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material.  Any review, re-transmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and destroy this material.

**Comment by volkanceylan** [comment]
Ok continue from e-mail maybe
