### ISSUE TITLE
Replacing username with email address messes up permissions

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#688]
Scenario:

1. Create a user with username such as "admin"
2. Assign role
3. Log in - all works as expected
4. Modify the username to an arbitrary email address and log out
3. Log in - all menu items show as expected but clicking on a menu items redirects to Login Page with denied=1 in the url.

Theoretically, this should work since username is not a key. Many thanks in advance with help on this.

**Comment by volkanceylan** [comment]
Is this happens with "admin" user only or same with another user. "admin" username has some special permissions in Serene, hard coded in a few places.

**Comment by c9482** [comment]
You are correct, it only happens when I replaced "admin" with email address. Thanks.
