### ISSUE TITLE
Odd Template.LoginPanel error

### ISSUE THREAD

**Issue by yangyer** [volkanceylan/Serenity#69]
I ran into this wierd issue when I created a new project. When I ran the project it error on the login page stating that the Template.LoginPanel was not found. I added a Template.LoginPanel into my Membership/Account/ dir and that seem to fix the error.

I tried creating another project but didn't get the same error. I'll see if I can repro the issue and post the steps but just wanted to make you aware.

**Comment by volkanceylan** [comment]
The template for LoginPanel is embedded in AccountLogin.cshtml:

```html
<script id="Template_Membership_LoginPanel" type="text/template">
```

So there should be no need to add a Template.LoginPanel. Maybe it didn't build project before running, so some kind of script error prevented it?
