### ISSUE TITLE
New to Serenity Data, Trying to use this query in my custom Lookup Query

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#692]
I am trying to learn how to convert my SQL statement to the built-in SQLQuery object with Serenity I I don't get how to use the Criteria object.

SELECT *
FROM MaterialCodeSKU m
    LEFT JOIN ProductMaterialCode pc ON m.MaterialCodeId = pc.MaterialCodeId
	LEFT JOIN SecondaryItemMaterialCode sc ON m.MaterialCodeId = sc.MaterialCodeId
WHERE pc.ProductId IS NULL AND sc.SecondaryItemId IS NULL

![image](https://cloud.githubusercontent.com/assets/17201265/15334529/3214b94a-1c34-11e6-9e94-6327894ed6a3.png)

**Comment by volkanceylan** [comment]
Don't use Alias objects. Use Fields.As("x")

Also you don't need to make joins as long as you use fields from a row

**Comment by swordz36** [comment]
Not quite following your suggestion, I looked in the Documentation for a similar example on LeftJoin for multiple tables but maybe I missed it.

**Comment by volkanceylan** [comment]
Did you see sample at the end of this topic?

https://volkanceylan.gitbooks.io/serenity-guide/content/fluent_sql/criteria_objects.html

**Comment by swordz36** [comment]
I have updated to this:

            query.Distinct(true)
                .LeftJoin("ProductMaterialCode", null, null)
                .LeftJoin("SecondaryItemMaterialCode", null, null)
                .Select(fields.MaterialCode)
                .Where(""):
But how do I get the reference on the foreign key on the joining table  for this Criteria WHERE pc.ProductId IS NULL AND sc.SecondaryItemId IS NULL

**Comment by volkanceylan** [comment]
What are these NULLs? :) I don't have nulls anywhere in that sample. Man do you have fields that are originating from ProductMaterialCode and SecondaryItemMaterialCode in your MaterialCodeSkuRow?

**Comment by swordz36** [comment]
![image](https://cloud.githubusercontent.com/assets/17201265/15336325/b0c3b50a-1c3b-11e6-8247-a2fcbc03ea30.png)

**Comment by volkanceylan** [comment]
Ok lets write your SQL with Serenity:

```cs
var m = MaterialCodeSKURow.Fields; // i'm not using .As("m") as base.PrepareQuery will assign "t0"
var pc = ProductMaterialCodeRow.Fields.As("pc");
var sc = SecondaryItemMaterialCodeRow.Fields.As("sc");
query
    .Select(m.MaterialCode)
    // .Select(m.XYZ).....
    .LeftJoin(pc, m.MaterialCodeId == pc.MaterialCodeId)
    .LeftJoin(sc, m.MaterialCodeId == sc.MaterialCodeId)
    .Where(pc.ProductId.IsNull() & sc.SecondaryItemId.IsNull())
```

Looks pretty similar to SQL? ;)

**Comment by swordz36** [comment]
So Fields on the row represent the table and that was my disconnect. Thanks a lot

**Comment by volkanceylan** [comment]
You're welcome

**Comment by swordz36** [comment]
When using custom creating a custom lookup does the lookup name in Javascript have to match the collection property on the Row?

![image](https://cloud.githubusercontent.com/assets/17201265/15367412/85002166-1cee-11e6-81b6-df30d3a133ce.png)

I am asking becasue my response is returning with data but I my dropdown won't populate with that data?

![image](https://cloud.githubusercontent.com/assets/17201265/15367441/a407adf4-1cee-11e6-86be-430ff8853aa7.png)

**Comment by volkanceylan** [comment]
Did you add [LookupInclude] to IsActive property, or did you select that field in your custom lookup

**Comment by rarunkumar454** [comment]
Hi, I was created lookup script with left jion but it's not working in my look up.

var UR = UsersRow.Fields;
var RR = ReportsRow.Fields.As("RRT");
            query.Distinct(true)
                .Select(UR.Username)
             .Select(UR.UserId)
             .LeftJoin(RR, UR.AccountId == RR.AccountId)
             .Where(new Criteria(UR.IsActive).In(1)&
                    new Criteria(RR.AccountId).IsNotNull() & new Criteria(UR.UserId).IsNotNull());

**Comment by rarunkumar454** [comment]
> Hi, I was created lookup script with left jion but it's not working in my look up.
> 
> var UR = UsersRow.Fields;
> var RR = ReportsRow.Fields.As("RRT");
> query.Distinct(true)
> .Select(UR.Username)
> .Select(UR.UserId)
> .LeftJoin(RR, UR.AccountId == RR.AccountId)
> .Where(new Criteria(UR.IsActive).In(1)&
> new Criteria(RR.AccountId).IsNotNull() & new Criteria(UR.UserId).IsNotNull());

Thanks to all, I got it.
