### ISSUE TITLE
How to open a dialog from the dashboard?

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#694]
So I was wondering how I can open a dialog from the dashboard. I want to open up RALDialog from a button click on the dashboard but I can seem to figure out how to do this. Is it something basic that I'm missing?

**Comment by volkanceylan** [comment]
new YourProject.YourModule.RALDialog().dialogOpen() or loadByIdAndDialogOpen()...

**Comment by wdhodges** [comment]
Do I do that on the onclick?

**Comment by volkanceylan** [comment]
Sure :)
