### ISSUE TITLE
Blank page show ------http://localhost:1421/Account/Login?ReturnUrl=%2f

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#695]
Hi volkanceylan,

                          Today i perform the tutorial based example like movie and person table process and after the time like show the blank page of the full task, what is the main problem hear please tell me.

screen shot:
https://cloud.githubusercontent.com/assets/18713252/15358164/90525796-1d20-11e6-92ab-151989819d4e.png

**Comment by volkanceylan** [comment]
See console

**Comment by samdubey** [comment]
Look like connection string is wrong

**Comment by GOBIBE** [comment]
the connection string is correct but not show the login page and other page  also

**Comment by GOBIBE** [comment]
the page could not contain the tables

**Comment by volkanceylan** [comment]
Why don't you look at console tab, there are two errors in console

**Comment by GOBIBE** [comment]
thank you volkanceylan its woring
