### ISSUE TITLE
Cannot find refernce to entityRow

### ISSUE THREAD

**Issue by Boumboumjack** [volkanceylan/Serenity#697]
Hi,

I updated vs 2013 from upgrade 1 to upgrade 5 this morning, and since then , most of my new row are not recognised by the typscript file (grid and dialog) . I tested an older project that used to work, and it appears to do the same.

Plus I get the Experimental decorator support error once I creat new entity from db, while I set true to both csproj and tsconfig.

Any idea what config should I tweak?

Thank you,

**Comment by volkanceylan** [comment]
I dont really know. Maybe you should report at TS repo with details.

**Comment by volkanceylan** [comment]
Especially decorator part doesnt make much sense

**Comment by Boumboumjack** [comment]
Thank you,
I will post their response here.
I think though that updating VS did mess up the thing...
