### ISSUE TITLE
addQuickFilter + enum

### ISSUE THREAD

**Issue by patcout26** [volkanceylan/Serenity#698]
How transform this in typescript ...

AddEqualityFilter<EnumEditor>(ProductCultureRow.Fields.Culture,
                options: new EnumEditorOptions { EnumKey = "Construction.Culture" });

**Comment by volkanceylan** [comment]
this.addQuickFilter({
     field: ProductCultureRow.Fields.Culture
     type: EnumEditor, 
     options: {
         enumType: Construction.Culture
     }
});

**Comment by patcout26** [comment]
Thanks it work
