### ISSUE TITLE
Retrieve Selected Items for LookUpEditor() w/ Multiple = true

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#699]
Retrieve method on Repository returns items but those values are not showing up in the select list. Is anyone else experiencing this?

**Comment by volkanceylan** [comment]
Retrieve service and lookup are different things. They are not related at all.

**Comment by volkanceylan** [comment]
Try Q.reloadLookup if this is about new items added to row

**Comment by volkanceylan** [comment]
I see you wrote in another issue. My two cents on not adding LookupInclude attribute or not selecting IsActive in your custom lookup.

**Comment by swordz36** [comment]
Well, the behavior is similar to issue #498, the only confusing part is that in looking at the network log in the devtools I can see he items being returned they are just not showing up in the custom lookup.

**Comment by volkanceylan** [comment]
Man, what is custom lookup, where are you seeing them and not showing, how do you expect me to help you like this?
