### ISSUE TITLE
How to add a tab button for a EditDialog form To List or Creat a detail recoder?

### ISSUE THREAD

**Issue by billjone** [volkanceylan/Serenity#70]
How to add a tab button for a EditDialog form To List or Creat a detail recoder?
I find the sample Customer Orders Dialog use the TabButton. How Can I do?

**Comment by volkanceylan** [comment]
You need to define a template for your dialog, just take one in CustomerDialog as a sample

**Comment by volkanceylan** [comment]
Please reopen if you still need help.
