### ISSUE TITLE
sergen 字符集问题

### ISSUE THREAD

**Issue by chunlizh** [volkanceylan/Serenity#700]
在自动生成代码时，建议默认使用UTF8字符集，不要使用本地字符集，否则会出现乱码

> bing translator
> In the automatically generated code, recommends using the UTF8 character set by default, do not use the local character set, to prevent garbled

**Comment by volkanceylan** [comment]
Which files doesn't have UTF8 by default? I'm usually generating UTF-8 with BOM.

**Comment by volkanceylan** [comment]
OK, i understood what you mean. Sergen doesn't generate files with BOM. They are UTF-8 but has no BOM. It happened after TFS integration. Didn't notice "new Utf8Encoding(true).GetBytes()" returns bytes without the preamble.

Will be fixed in next version.
