### ISSUE TITLE
How to open custom dialog from grid

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#702]
How to open custom dialog from itemlink in grid, i create dialog in web.script where dialog inherits from TemplateDialog.

Thanks

**Comment by volkanceylan** [comment]
See how to about action in grid, you need to follow similar steps, creating a < a class='my-link'> element , handling click event for that class and opening your dialog with new MyProject.MyModule.MyDialog().dialogOpen()

**Comment by volkanceylan** [comment]
Added sample in 2.2.0.1

**Comment by fazanan** [comment]
Hi Jaiq,

Appreciate your support.

Thanks
