### ISSUE TITLE
Add new field in xyzDialog not related to entity

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#703]
Dear @volkanceylan,
I was wondering if there is a way to add a field to an entityDialog, to let Serenity serialize the user value, but prevent the normal "save behaviour" only for such field, because that field not belong to the entity itself.
I remember the OneWay attribute, but it's prevent the field to be serialized from client to server while I would like to retrieve the value server side and simply tell Serenity to not try to update such field on the entity.
There is a way?

Thanks!

**Comment by volkanceylan** [comment]
Updatable(false)

**Comment by marcobisio** [comment]
Ohhh it was so easy!! 
Thank you very much!!!

**Comment by marcobisio** [comment]
But with Updatable(false) the field is readonly...I have to set it client "writable" programmatically?

**Comment by ramveersgh** [comment]
Use ClientSide attribute on the field.

**Comment by volkanceylan** [comment]
Yes, ClientSide

**Comment by marcobisio** [comment]
Thanks!!
