### ISSUE TITLE
Access denied error occurred when we calling webservice and pass cookie through header in android application

### ISSUE THREAD

**Issue by laxmanp** [volkanceylan/Serenity#704]
Hello sir,

Access denied error occurred when we calling webservice and pass cookie through header in android application.
When we execute login webservice through the android app using httpresponse that time 
we are retrieve cookie using httpresponse.getAllHeaders(); and processing the operation for correct cookie. Passes the cookie to cookie store and local context then local context to webservice for 
excute webservice that time access denied message displayed.

This is my Code :

                DefaultHttpClient httpclient = new DefaultHttpClient();
                HttpPost httppostreq = new HttpPost("http://crewingduck.azurewebsites.net/Account/Login");
        
                JSONObject jsonobj = new JSONObject();
                
                jsonobj.put("Password", Password);	           	 
                jsonobj.put("Username", Username);
                
                StringEntity se = new StringEntity(jsonobj.toString());
                se.setContentType("application/json;charset=UTF-8");
                se.setContentEncoding(new BasicHeader(HTTP.CONTENT_TYPE, "application/json;charset=UTF-8"));
                httppostreq.setEntity(se);
                HttpResponse httpresponse = httpclient.execute(httppostreq);
                
                //Retrieving Cookie from httpResponse
                
                Header[] headers = httpresponse.getAllHeaders();
                Header h = headers[8];
                cookieHeader = h.getValue();
                h = headers[4];
                cookieHeader = cookieHeader +"   "+ h.getValue();
                int lastIndex = cookieHeader.lastIndexOf(";");
                cookieHeader = cookieHeader.substring(0, lastIndex - 1);
                lastIndex = cookieHeader.lastIndexOf(";");
                cookieHeader = cookieHeader.substring(0, lastIndex);
                int firstIndex = cookieHeader.indexOf(";");
                lastIndex = cookieHeader.indexOf(".ASPXAUTH=");
                String replaceString = cookieHeader.substring(firstIndex + 1, lastIndex - 1);
                cookieHeader = cookieHeader.replaceAll(replaceString, "");
                
                CookieStore cookieStore = new BasicCookieStore();               
                Cookie cookie = new BasicClientCookie("name", cookieHeader);
                cookieStore.addCookie(cookie);
                HttpContext localContext = new BasicHttpContext();
                localContext.setAttribute(ClientContext.COOKIE_STORE, cookieStore);
       
                       
                responseServer = EntityUtils.toString(httpresponse.getEntity());
                
                JSONObject obj = new JSONObject(responseServer);
                int objectlength = obj.length();
                if(objectlength == 0)
                {
                   session.createLoginSession(Username,  Password);          
                    
                   //List Web Service
                   DefaultHttpClient httpclientw = new DefaultHttpClient();
                   HttpPost httppostreqw = new HttpPost("http://crewingduck.azurewebsites.net/Services/Northwind/Customer/List");

                   String Take="100";               
                   
                   ArrayList<String> list = new ArrayList<String>();
                   list.add("CustomerID");
                   list.add("CompanyName");
                   list.add("ContactName");
                   list.add("City");
                   list.add("Region");
                   list.add("PostalCode");
                   list.add("Country");
                   list.add("Phone");
                   list.add("Fax");        
                      
                    JSONObject secjsonobj = new JSONObject();
                    
                    JSONObject equalityobj = new JSONObject();
                    equalityobj.put("Country", "");
                    equalityobj.put("City","");
                    
                    secjsonobj.put("Take", Take);	           	 
                    secjsonobj.put("IncludeColumns", new JSONArray(list));
                    secjsonobj.put("EqualityFilter", equalityobj);
                    
                    
                    StringEntity sew = new StringEntity(secjsonobj.toString());
                    sew.setContentType("application/json;charset=UTF-8");
                    sew.setContentEncoding(new BasicHeader(HTTP.CONTENT_TYPE, "application/json;charset=UTF-8"));
                    httppostreqw.setEntity(sew);
                    HttpResponse httpresponsew = httpclientw.execute(httppostreqw,localContext);
                    String  responseServerw = EntityUtils.toString(httpresponsew.getEntity());
                    String secondResponse= responseServerw; 

		}

**Comment by volkanceylan** [comment]
This is real bad code, especially accessing headers by index.

https://gist.github.com/volkanceylan/1b124f58c1e2b4fc7c7c

This is a sample by some friend. It's a bit better.
