### ISSUE TITLE
Retrieve category block from typescript

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#706]
Dear @volkanceylan,
I was wondering if there is a way to retrieve (and show/hide programmatically) a form category like this:

    [Category("my wonderful category")]

Thanks as usual for your support!
Bye

**Comment by volkanceylan** [comment]
form.SomeField.element.closest('.category').toggle(...)

**Comment by marcobisio** [comment]
Sooner or later I'll learn. ...
Thank you very much!!
Bye

**Comment by awesomegithubusername** [comment]
Hi;

I tried this and it worked. Now the category name is still displayed in "category-links" even if the category itself is hidden. Any workaround?

**Comment by WasimAhmad** [comment]
having same problem.. how to also hide or remove from category-links?? any solution...

**Comment by awesomegithubusername** [comment]
Try this:

```javascript
$('.category-link').each(function () {

          if ($(this).text() == "YourCategoryName") 
          {
               $(this).next().toggle(false);
               $(this).toggle(false);
          }

});
```

**Comment by WasimAhmad** [comment]
thanks @awesomegithubusername
