### ISSUE TITLE
Lookup editor + InplaceAdd

### ISSUE THREAD

**Issue by patcout26** [volkanceylan/Serenity#707]
I just migrate with the version with 2.1.8
the (InplaceAdd = true) parameter doesn't work .... didn't show in the form

**Comment by patcout26** [comment]
This is the code from my custom lookup editor:
 

@Serenity.Decorators.registerEditor()
    export class ModelEditor extends Serenity.LookupEditorBase<ModelRow, any> {

        constructor(hidden: JQuery) {
            super(hidden);
        }

        protected getLookupKey() {
            return ModelRow.lookupKey;
        }

        protected getItemText(item, lookup) {
            return super.getItemText(item, lookup) + ' [' + item.BrandName + ']';
        }
    }


This is the code for the row:


public sealed class VehicleTireRow : Row, IIdRow, INameRow
    {    

        [DisplayName("Model"), ForeignKey("[co].[Model]", "Id"), LeftJoin("jModel"), TextualField("ModelName")]
[ModelEditor(InplaceAdd = true)]
        public Int32? ModelId
        {
            get { return Fields.ModelId[this]; }
            set { Fields.ModelId[this] = value; }
        }

.....

**Comment by volkanceylan** [comment]
Check console first for errors

**Comment by patcout26** [comment]
No error, the problem is that the add button doesn't appear ....

**Comment by volkanceylan** [comment]
Your lookup editor doesn't take LookupEditorOptions. It might be the issue.

```ts
export class ModelEditor extends Serenity.LookupEditorBase<ModelRow, Serenity.LookupEditorOptions> {
   constructor(hidden: JQuery, options: LookupEditorOptions) {
       super(hidden, options);
   }
}
```

**Comment by patcout26** [comment]
Thanks a lot, you are a master :)
