### ISSUE TITLE
Customizing columns in grid derived from another grid

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#708]
How do I customize column definition in descendant grid class? I can't figure out how the columns class is used by the grid class and how to override it. Many thanks in advance.

**Comment by volkanceylan** [comment]
You may override GetColumns method. This gives you a list of SlickColumn objects. Using linq find column by its field, e.g.

```cs
var columns = base.GetColumns();
columns.First(x => x.Field == "SomeField").Format = ctx => Q.HtmlEncode(ctx.Value);
columns.RemoveAt(7);
...
return columns;
```

GetColumns in default implementation, takes a look at ColumnsKey attribute to understand which Columns class to retrieve that is defined server side.

That XYZColumns class, is converted to a list of property items, PropertyItem objects server side.

Then grid loads these property items with Q.GetColumns("ABCModule.XYZ") and converts them to SlickColumn object.

**Comment by c9482** [comment]
Thanks for your reply. So if I have XXGrid derived from XGrid, I could define XXColumns class do customize the columns (instead of overriding GetColumns() method)?

Also, how would I override access permission for the derived grid?

**Comment by volkanceylan** [comment]
Yes you can create another columns class. Permissions are not set on grid, but page, endpoint, or row level.
