### ISSUE TITLE
GridEditorDialog error after T4 templates transformation

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#709]
Dear @volkanceylan,
just updated to 2.1.9 and after a rebuild of the T4 templates i got this error on browser (chrome) console:

![image](https://cloud.githubusercontent.com/assets/17425690/15421515/0a518cb6-1e74-11e6-81a9-c67bef7f0902.png)

and then the grids are not visible (I mean I can only see the adminlte template).
After a "save" (from visual studio) on GridEditorDialog.ts the issue is resolved and the grids are working as expected...it's that the normal behaviour?

Thank you very much

**Comment by volkanceylan** [comment]
Your Web.js file somehow got deleted. I'm pretty sure this is not about templates, nor update.

**Comment by marcobisio** [comment]
Not deleted but drammatically different (before/after ts compilation)...honestly I don't know why...
I'll try to merge my code in a new serenity template and I let you know...

Thanks

**Comment by volkanceylan** [comment]
If you have Q.arrayClone(this.view.getItems()) somewhere, replace it with this.view.getItems().slice(0)

Also you should get TranslationGrid.ts, GridEditorBase.ts and FilteredLookupEditor.ts from latest source, replacing Serene with your project name

**Comment by marcobisio** [comment]
Already replaced Q.arrayClone and also already "patched" TranslationGrid.ts and GridEditorBase.ts (not FilteredLookupEditor.ts because I've removed the basic samples section from the project).
While opening for example the Langue table, I got this:

![image](https://cloud.githubusercontent.com/assets/17425690/15422944/564ca306-1e7b-11e6-8e31-fa920a0d094d.png)


and once again after a ts recompile, everything is working fine...

**Comment by volkanceylan** [comment]
There is some TypeScript file in your project that is without /// references to its base class. TypeScript has problem with file ordering unless you specify references explicitly.

Here is the issue i reported:

https://github.com/Microsoft/TypeScript/issues/8013

**Comment by volkanceylan** [comment]
Worst part is it is not deterministic in file ordering. So, when you compile with tsc, and compile with save, order might be different. With luck, one works while one not.

**Comment by volkanceylan** [comment]
Check for your ts files referencing GridEditorDialog

**Comment by volkanceylan** [comment]
and GridEditorBase

**Comment by marcobisio** [comment]
Solved!

Also added:
`/// <reference path="../../Common/Helpers/GridEditorBase.ts" />`

in ts files referencing GridEditorBase and ta-dan...now it's working fine!

**Comment by marcobisio** [comment]
Concurrent answers :-)

Do you prefer to leave this issue open for the community or I can close?

Thank you very much for your support
bye

**Comment by volkanceylan** [comment]
You're welcome. Nobody will see anyway :) So let's close.

**Comment by basselz** [comment]
I saw, 
and thanks both for the discussion,
it directs me in the right way 
I was referencing the wrong file in one of the ts files

**Comment by PedroHFranco** [comment]
I saw too,
I was getting a little diferent error, but was reference missing in extends xyzGRID and xyzDIALOG,
its was woking fine, then start to compile myproject.js file wrong.
Thanks for discussion.
