### ISSUE TITLE
Putting the MovieCast Editor on a second tab.

### ISSUE THREAD

**Issue by SirSpam** [volkanceylan/Serenity#71]
Having trouble when trying to put the MovieCast Editor on a second tab.  Id like the initial dialog when clicking on a movie to edit have two tabs, one for info, and one for cast.  Id like the cast tab to display the MovieCastEditor, fully populated with the cast for the selected movie.  Ive gotten that far.  The problem is that when trying to modify or edit a cast entry using the MovieCastEditDialog on the second tab, the movie Id does not get set implicitly as if the MovieCastEditor was in the main form.  

Any ways around this problem?

**Comment by volkanceylan** [comment]
First, need to understand what are you trying to do. Are you trying to make it behave same, after moving it to a tab, meaning grid data loaded / saved along the main form and dialog save button, or work independently, like it works in customer orders tab?

**Comment by SirSpam** [comment]
I trying to make the behavior the same, with the grid data loaded and saved along with the main form.

**Comment by volkanceylan** [comment]
Ok, than just move grid into tab with jQuery, in dialog constructor, like
this:

this.ById("CastList").Closest(".field").Hide(); // this is to hide field
containing grid and its label
this.ById("CastList").AppendTo(this.ById("IdOfYourPlaceHolderDivInTab")) //
move grid with id ~_CastList to div with ID ~_IdOfYourPlaceHolderDivInTab

2015-12-11 21:13 GMT+02:00 SirSpam <notifications@github.com>:

**Comment by volkanceylan** [comment]
Did you resolve your issue @SirSpam?

**Comment by SirSpam** [comment]
Nope, still working on it.  What would the dialog look like?
