### ISSUE TITLE
about "SignUp" page 

### ISSUE THREAD

**Issue by chunlizh** [volkanceylan/Serenity#713]
"SignUp" page isn't localization!

**Comment by volkanceylan** [comment]
Right, i'm accepting pull requests

**Comment by chunlizh** [comment]
How to pull, i'm a beginner.

text.cs
                public static class SignUp
                {
                    public static LocalText ActivateEmailSubject = "Activate Your IsMicroWF Account";
                    public static LocalText ActivationCompleteMessage = "Your account is now activated. " +
                        "Use the e-mail and password you used while signing up to login.";
                    public static LocalText FormInfo = "Enter your details to create a free account.";
                    public static LocalText FormTitle = "Sign up for IsMicroWF";
                    public static LocalText SubmitButton = "Sign Up";
                    public static LocalText Success = "An e-mail with instructions to active your account is " +
                        "sent to your e-mail address. Please check your e-mails.";
                    public static LocalText DisplayName = "Full Name";
                    public static LocalText Email = "E-mail";
                    public static LocalText ConfirmEmail = "Confirm Email";
                    public static LocalText Password = "Password";
                    public static LocalText ConfirmPassword = "Confirm Password";
                }

SignUpForm.cs
    using Serenity.ComponentModel;
    using System;
    using System.ComponentModel;

    [FormScript("Membership.SignUp")]
    public class SignUpForm
    {
        [DisplayName("Forms.Membership.SignUp.DisplayName"), Required(true)]
        public String DisplayName { get; set; }
        [DisplayName("Forms.Membership.SignUp.Email"), EmailEditor, Required(true)]
        public String Email { get; set; }
        [DisplayName("Forms.Membership.SignUp.ConfirmEmail"), EmailEditor, Required(true)]
        public String ConfirmEmail { get; set; }
        [DisplayName("Forms.Membership.SignUp.Password"), PasswordEditor, Required(true)]
        public String Password { get; set; }
        [DisplayName("Forms.Membership.SignUp.ConfirmPassword"), PasswordEditor, Required(true)]
        public String ConfirmPassword { get; set; }
    }
