### ISSUE TITLE
Cascading Editor

### ISSUE THREAD

**Issue by GeorgeBarkhuizen** [volkanceylan/Serenity#714]
Hi,

I am having problems getting a Cascading Editor to work. It works when I hard code a value in CascadeValue  but when I use the CascadeFrom option the editor always returns empty.  Is the a way to see what value is passed to the editor when using CasscadeFrom?

**Comment by volkanceylan** [comment]
CascadeFrom is the name of the editor.

**Comment by volkanceylan** [comment]
The other one that this one should bind to

**Comment by GeorgeBarkhuizen** [comment]
This is what I have but it is not working

 

 

        [DisplayName("Payment Milestone Project Type Id"), Expression("jPaymentMilestone.[ProjectTypeID]")]

        public Int32? ProjectTypeId

        {

            get { return Fields.ProjectTypeId[this]; }

            set { Fields.ProjectTypeId[this] = value; }

        }

 

 

        [DisplayName("Milestone Profile"), Column("PaymentMilestoneID"), NotNull, ForeignKey("[dbo].[tblPaymentMilestoneSetup]", "PaymentMilestoneID"), LeftJoin("jPaymentMilestone"), TextualField("PaymentMilestoneDescription")]

        [LookupEditor(typeof(Entities.PaymentMilestoneSetupRow), CascadeField = nameof(PaymentMilestoneSetupRow.ProjectTypeId),CascadeValue = nameof(ProjectTypeId))]

           

        public Int32? PaymentMilestoneId

        {

            get { return Fields.PaymentMilestoneId[this]; }

            set { Fields.PaymentMilestoneId[this] = value; }

        }

 

 

 

 

And 

 

 

namespace HSSOnline2016.ProjectManagement.Entities

{

    using Newtonsoft.Json;

    using Serenity;

    using Serenity.ComponentModel;

    using Serenity.Data;

    using Serenity.Data.Mapping;

    using System;

    using System.ComponentModel;

    using System.IO;

 

    [ConnectionKey("HSSDB"), DisplayName("tblPaymentMilestoneSetup"), InstanceName("tblPaymentMilestoneSetup"), TwoLevelCached]

    [ReadPermission("ProjectManagement:General")]

    [ModifyPermission("Administration")]

    [LookupScript("ProjectManagement.PaymentMilestoneSetup")]

    public sealed class PaymentMilestoneSetupRow : Row, IIdRow, INameRow

    {

        [DisplayName("Project Type Id"), Column("ProjectTypeID"), NotNull, LookupInclude]

        public Int32? ProjectTypeId

        {

            get { return Fields.ProjectTypeId[this]; }

            set { Fields.ProjectTypeId[this] = value; }

        }

 

        [DisplayName("Payment Milestone Item"), Column("PaymentMilestoneItemID"), ForeignKey("[dbo].[tblPaymentMilestoneItems]", "PaymentMilestoneItemId"), LeftJoin("jPaymentMilestoneItem"), TextualField("PaymentMilestoneItem")]

        public Int32? PaymentMilestoneItemId

        {

            get { return Fields.PaymentMilestoneItemId[this]; }

            set { Fields.PaymentMilestoneItemId[this] = value; }

        }

 

        [DisplayName("Description"), Size(50), NotNull, QuickSearch]

        public String Description

        {

            get { return Fields.Description[this]; }

            set { Fields.Description[this] = value; }

        }

 

        [DisplayName("Payment Rule Id"), Column("PaymentRuleID"), NotNull]

        public Int32? PaymentRuleId

        {

            get { return Fields.PaymentRuleId[this]; }

            set { Fields.PaymentRuleId[this] = value; }

        }

 

        [DisplayName("Payment Milestone Id"), Column("PaymentMilestoneID"), Identity]

        public Int32? PaymentMilestoneId

        {

            get { return Fields.PaymentMilestoneId[this]; }

            set { Fields.PaymentMilestoneId[this] = value; }

        }

 

        [DisplayName("Payment Milestone Item Subsidy Instrument Id"), Expression("jPaymentMilestoneItem.[SubsidyInstrumentID]")]

        public Int32? PaymentMilestoneItemSubsidyInstrumentId

        {

            get { return Fields.PaymentMilestoneItemSubsidyInstrumentId[this]; }

            set { Fields.PaymentMilestoneItemSubsidyInstrumentId[this] = value; }

        }

 

        [DisplayName("Payment Milestone Item"), Expression("jPaymentMilestoneItem.[PaymentMilestoneItem]")]

        public String PaymentMilestoneItem

        {

            get { return Fields.PaymentMilestoneItem[this]; }

            set { Fields.PaymentMilestoneItem[this] = value; }

        }

 

        [DisplayName("Payment Milestone Item Parent Id"), Expression("jPaymentMilestoneItem.[ParentID]")]

        public Int32? PaymentMilestoneItemParentId

        {

            get { return Fields.PaymentMilestoneItemParentId[this]; }

            set { Fields.PaymentMilestoneItemParentId[this] = value; }

        }

 

        IIdField IIdRow.IdField

        {

            get { return Fields.PaymentMilestoneId; }

        }

 

        StringField INameRow.NameField

        {

            get { return Fields.Description; }

        }

 

        public static readonly RowFields Fields = new RowFields().Init();

 

        public PaymentMilestoneSetupRow()

            : base(Fields)

        {

        }

 

        public class RowFields : RowFieldsBase

        {

            public Int32Field ProjectTypeId;

            public Int32Field PaymentMilestoneItemId;

            public StringField Description;

            public Int32Field PaymentRuleId;

            public Int32Field PaymentMilestoneId;

 

            public Int32Field PaymentMilestoneItemSubsidyInstrumentId;

            public StringField PaymentMilestoneItem;

            public Int32Field PaymentMilestoneItemParentId;

 

            public RowFields()

                : base("[dbo].[tblPaymentMilestoneSetup]")

            {

                LocalTextPrefix = "ProjectManagement.PaymentMilestoneSetup";

            }

        }

    }

}

**Comment by volkanceylan** [comment]
Dont specify CascadeValue, only CascadeFrom and CascadeField

**Comment by GeorgeBarkhuizen** [comment]
Changed it to this but still  no luck

 

        [DisplayName("Milestone Profile"), Column("PaymentMilestoneID"), NotNull, ForeignKey("[dbo].[tblPaymentMilestoneSetup]", "PaymentMilestoneID"), LeftJoin("jPaymentMilestone"), TextualField("PaymentMilestoneDescription")]

        [LookupEditor(typeof(Entities.PaymentMilestoneSetupRow), CascadeField = nameof(PaymentMilestoneSetupRow.ProjectTypeId), CascadeFrom = nameof(ProjectTypeId))]

           

        public Int32? PaymentMilestoneId

        {

            get { return Fields.PaymentMilestoneId[this]; }

            set { Fields.PaymentMilestoneId[this] = value; }

        }

**Comment by volkanceylan** [comment]
Omg, you don't have an editor on ProjectTypeId, how do you expect it to work with CascadeFrom

**Comment by GeorgeBarkhuizen** [comment]
I do not want to display ProjectTypeId  on the form but I still want to filter the PaymentMilestoneId based on ProjectTypeId.  Should I rather use FilterField and FilterValue?

**Comment by volkanceylan** [comment]
None will work, only set CascadeField on editor, override LoadEntity and set CascadeValue there.

**Comment by volkanceylan** [comment]
Or add a hidden editor for ProjectTypeId [Visible(false)]

**Comment by GeorgeBarkhuizen** [comment]
Thank you, 

I added a hidden editor  for ProjectTypeId and now it is working.

**Comment by GeorgeBarkhuizen** [comment]
Hi Volcan,

 

I am looking for a freelance developer to assist me on a project built on Serenity Framework. Are you able to assist or can you put me in contact with someone that would be interested to work on this project?

**Comment by volkanceylan** [comment]
You can contact me here:
https://www.linkedin.com/in/volkan-ceylan-68a44841

**Comment by GeorgeBarkhuizen** [comment]
I cannot contact you on LinkedIn. Can you not email me directly?
