### ISSUE TITLE
How to validateentity with confirm in editor

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#716]
Hi Jaiq,

How to validate entity with confirm?,  If user choose Ok button, entity will be added in editor list.
confirm delegate cannat return value.

            RackCapacityViewRow rackCap = RackCapacityViewRow.Lookup.ItemById[row.RackId];
            if (rackCap.PS == "Warning" || rackCap.HS == "Warning" || rackCap.WS == "Warning")
            {
                System.Action submit = delegate
                {
                    return true; // Error in this line//
                };
                Q.Confirm("Power, Heat or Weight equipment is more than capacity for this rack", submit);
            }
            return false;

  Try this but not success

            bool status = false;
            RackCapacityViewRow rackCap = RackCapacityViewRow.Lookup.ItemById[row.RackId];
            if (rackCap.PS == "Warning" || rackCap.HS == "Warning" || rackCap.WS == "Warning")
            {
                System.Action submit = delegate
                {
                    status = true;
                };
                Q.Confirm("Power, Heat or Weight equipment is more than capacity for this rack", submit);
            }
            return status;

Thanks

**Comment by volkanceylan** [comment]
It's not possible this way. What is this code for.

**Comment by fazanan** [comment]
Hi Jaiq,

Thanks for answer, i just want to show confirm dialog in validateentity function, so user cannot added row in editor (like moviecasteditor), but if it's not possible, i will try to change show confirmation dialog in button save click, i think it possible.

Thanks

**Comment by volkanceylan** [comment]
Yes intercepting save button should be better
