### ISSUE TITLE
doesn't support property or method array Clone 

### ISSUE THREAD

**Issue by srimsriram** [volkanceylan/Serenity#717]
Please make sure these boxes are checked before submitting your issue --- thank you!

- [ ] Check Serenity Users Guide, including how-to and troubleshooting sections
- [ ] Check Serenity WIKI in GitHub
- [ ] Please have a look CHANGELOG.md for directions on breaking changes
- [ ] Try a search for previous issues here, that might have similar case
- [ ] Check your browsers's CONSOLE tab for errors, and include them here
- [ ] Please report with as many details as possible to help us identify the problem

### Steps to reproduce the behavior

**Comment by volkanceylan** [comment]
Seems like you read everything so carefully :)

**Comment by volkanceylan** [comment]
That function is removed. Please search for Q.arrayClone(something) in your project and replace it with something.slice(). And also report the file here so i can share it in change log. I don't know how that code is left in yours.

**Comment by srimsriram** [comment]
Thank you!
