### ISSUE TITLE
Tooltip in fields forms

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#720]
Hey Volkan,

I would like to know how to set tooltip fot the fields in forms.

in ContasBancariasRow.cs i tried this.

        [DisplayName("Numero Agencia"), Size(50), Description("Número da Agência")]
        public String NumeroAgencia
        {
            get { return Fields.NumeroAgencia[this]; }
            set { Fields.NumeroAgencia[this] = value; }
        }

But description is not showing in textbox field in web. It's important to describe for user the target of this fields.

I know that we have jquery tooltip in serenity (https://jqueryui.com/tooltip/), but i can't understand how to set it in serenity.

Thanks in advanced.

**Comment by volkanceylan** [comment]
Use Hint or Placeholder, Description is not used

**Comment by rolembergfilho** [comment]
do you have any tutorial to do it?

**Comment by volkanceylan** [comment]
[Placeholder("Número da Agência")]

**Comment by rolembergfilho** [comment]
GOOD!

it's works !

to finally this post, i tried to set Hint in field "site", but not appeared

        [DisplayName("Site"), Size(100)]
	[Hint("Site")]
	public String Site
        {
            get { return Fields.Site[this]; }
            set { Fields.Site[this] = value; }
        }

in follow, i sent an image from this form. In my esperience in ASP.NET web form, these descriptions was show for user just like the "Close" hint

So... how to make these description appeared like "Close" hint?

![form with placeholder and hint](https://cloud.githubusercontent.com/assets/19523455/15524189/7fe315b4-21f6-11e6-88ad-6633c9d0b418.png)

**Comment by rolembergfilho** [comment]
I found this tips & tricks in wiki (https://github.com/volkanceylan/Serenity/wiki/Tips-&-Tricks), but i don't know where and how set it:

**_private jQueryObject customDiv = J("<div style='text-align:center;color:red'>MY_CUSTOM_TEXT</div>");
// show
customDiv.AppendTo(form.MyField.Element.Closest(".field"));
// hide
customDiv.Remove();_**


thanks again for your patience in these questions. I think that i'm having these issues because i didn't understand yet where is "code behind" and where is "view source". I know that serenity is mvc project, but it's different from the book and sites that i studied.

**Comment by volkanceylan** [comment]
Hint shows on label. You should avoid hints, not compatible with touch devices. If you still want to show another, e.g. qtip, form.MyField.Element.qtip("sdadad") considering you have qtip included.

**Comment by rolembergfilho** [comment]
sorry. I tried and quit....

could you make a mini tutorial how to do it using existing Northwind Product in Serene?

**Comment by Mumarda** [comment]
@rolembergfilho Hello I was wondering if this is something to add help information for the users?

![help](https://cloud.githubusercontent.com/assets/19939324/19946677/b0f8dbe6-a123-11e6-89b9-f83f2d69e441.jpg)

I would like to add "help" information for the user, an example about what information is required in the field... is there any way to do it...

Something like this... In Excel:

![help2](https://cloud.githubusercontent.com/assets/19939324/19946919/9838025c-a124-11e6-8aa2-89f4f4607d5a.jpg)

When you "mouse over" you can see the help information.

Thank you

**Comment by Estrusco** [comment]
See at https://github.com/volkanceylan/Serenity/issues/1306
