### ISSUE TITLE
Replace references of String with string

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#722]
This one's ridiculous I know, but here it is. I have a 3rd party proxy class I have to use which has defined String as a custom class which is causing problems with Serenity's use of String (which it assumes means System.String and not this funky redefined String thing). Switching from String to string changes it from a class identifier to a c# keyword and removes the confusion.

I see the problem most often in generated code, e.g. CustomFormatter string fields.

**Comment by volkanceylan** [comment]
How does your used proxy class show up in generated files?

**Comment by volkanceylan** [comment]
Or its namespace

**Comment by wldkrd1** [comment]
Ok, so my proxy class didn't have a namespace, which put it into the global space which apparently is why it was introducing a conflict. Wrapping the proxy class in a namespace and updating references to using it resolved it.

My personal opinion is that I prefer keywords over classnames, but that's completely a stylistic preference, not a technical one. :-)
