### ISSUE TITLE
SlickFormatter properties not being assigned correctly

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#723]
It appears that the new TS SlickFormatters (e.g. EmployeeFormatter's genderProperty in Northwind) are not assigning property values correctly. There should be an image next to the employee name.

![formatterissue](https://cloud.githubusercontent.com/assets/2817543/15514826/d73703ea-219f-11e6-8ae2-66f62f406412.png)

**Comment by volkanceylan** [comment]
Thanks for the report, i'll have a look at it

**Comment by volkanceylan** [comment]
This was due to fields defined in TypeScript not actual properties in Saltaralle type system. Should be fixed in 2.2.1.
