### ISSUE TITLE
Add dialog lookup editor programmatically

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#724]
Dear @volkanceylan,
in my xyzDialog I've 3 cascaded lookup editors with about 10k records.
Those editors should be displayed only in insert mode, so I have added the HideOnUpdate(true).
When I open the dialog in edit mode, I see in the network analyzer of the browser that all the values of such lookup are sent (however) to the client, even if they are hidden.
This is a way to avoid this?
I'm asking that because while the 2-3 seconds of loading are legit while inserting, this is not true while editing, because those fields are not visible and not editable.

So I was wondering if there is a way to add the lookup editors programmatically in the dialog...something like that (in the constructor):

    constructor(container: JQuery) {
        super(container);
        
        if (this.isNew()) {
            // add my lookups
        }
    }

Thank you very much as usual for your support
Bye

**Comment by volkanceylan** [comment]
You may dynamically create editor in AfterLoadEntity, e.g. 

if (this.IsNew() && !didICreateEditorsAlready)
new SomeEditor(this.ById("MyLookup"), { ... })

Of course in form first put a string editor, then replace it in New mode.

Anyway if your lookups are so big & slow, you should look for alternatives like Ajax editor.

**Comment by marcobisio** [comment]
Copy that!
Yesterday I have completed the "porting" of you sample ( #375 ) in typescript...
If you have a minute or two just to check that my code sounds good, then I'll be happy to share such implementation with the community (in a wiki article I mean).

Thank you very much
Bye
