### ISSUE TITLE
Adding Quickfilter item in New dialog box

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#725]
How can i use QuickFilter item and add it into New Dialog for an entity?
for eg. Application has two entity Student and ClassRoom.
Students are filtered based on Classroom Name and i want to use same classRoomId when i am trying to Create New Student.

**Comment by volkanceylan** [comment]
See custom links sample on how to find a quick filter. In same page one of links prepopulates some dialog, you should populate just like that one.

**Comment by shaileshbc** [comment]
Can you provide link of sample, as i am unable to find it.
Thanks in Advance

**Comment by shaileshbc** [comment]
i found Custom Link Example, sorry.
I will check the same.
Thanks
