### ISSUE TITLE
Active Directory Duplicate Entries

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#726]
Please make sure these boxes are checked before submitting your issue --- thank you!

- [x ] Check Serenity Users Guide, including how-to and troubleshooting sections
- [x ] Check Serenity WIKI in GitHub
- [x ] Please have a look CHANGELOG.md for directions on breaking changes
- [x ] Try a search for previous issues here, that might have similar case
- [x ] Check your browsers's CONSOLE tab for errors, and include them here
- [x ] Please report with as many details as possible to help us identify the problem

### Configuration (Serenity / Serene version, OS, Browser used etc.)
Serentiy with the Serenity 2.2.0.1, Windows 10, IE 11 and Microsoft Edge 25.10586.0.0, Microsoft EdgeHTML 13.10586

Included the Active Directory 'Key' to Web.config as <add key="ActiveDirectory" value="{ Domain: 'hmndgroup' }" />

### Expected behavior
Users are not manually added to the Users table but handled by the Active Directory functionality.

a users First time successful login generates a record being written (correctly) to the 'Users' table and there would not be additional records written on subsequent user logins. Users can login and use the application as often as desired.

### Actual behavior
We have two users with very similar names (the same name, except for two 'i' added to the UID to distinguish the two names), User 1 is 'rsmith', User 2 is 'rsmithii'.  User 1 (rsmith) logs in successfully the first time, a record is created to the 'Users' table containing the expected data elements. User 2 (rsmithii) logs in successfully the first time and a record is created to the 'Users' table containing the correct data elements.

User 1 (rsmith) logs in multiple additional times and everything works as expected.
User 2 (rsmithii) logs in a second, or any subsequent time, and receives error messages delivered via IE (attached as .txt file) stating that more than one record was returned. Upon examination of the 'Users' table a partial record for User 2 (rsmithii) had been written to 'Users' the table. User 2 (rsmithii) has two records in the 'Users' table one complete and correct and the second record is complete except for the 'UpdateDate' and 'UpdateTime' fields, which are NULL.

User 2 (rsmithii) is not able to use the application.
User 1 (rsmith) or any other users can log onto the application and use the application without any issues.

### Steps to reproduce the behavior
Create two users in Active Directory with the same name, differentiated the names by appending 2 i's to the end of the UID. i.e. rsmith and rsmithii, mlutzow and mlutzowii, jjones and jjonesii.

Activate the Active Directory Key in the Web.config file (only), build the application and run. Have both users log in the first time. Have both users log out. Have both users log in a second or as many subsequent time as necessary. User 2 (<name>ii) will always fail with an error.

[Query returned more than one result.txt](https://github.com/volkanceylan/Serenity/files/282394/Query.returned.more.than.one.result.txt)

**Comment by volkanceylan** [comment]
What is your database type, and what is the collation used. I guess this is a collation issue.

**Comment by mlutzow** [comment]
Sorry, forgot that information.

Microsoft SQL Server 2008 (SP3) - 10.0.5500.0 (X64),  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 

Collation:  Latin1_General_BIN

**Comment by volkanceylan** [comment]
BIN should be binary. If this is correct i don't think it is related to collation.

Can you add a unique index to user table, after removing duplicates, and see if same thing happens?

**Comment by volkanceylan** [comment]
Thanks a lot for detailed information btw.

**Comment by mlutzow** [comment]
You're welcome and it's my pleasure. I find front loading as much information as I can safely give away usually results in much better solutions in shorter amounts of time. Also, I have a request for help, related to this functionality being submitted as soon as I'm finished rebuilding some other items I need to finish.

Cheers.

**Comment by mlutzow** [comment]
Just saw the unique index request, I will do that now.

**Comment by mlutzow** [comment]
There is already a 'Unique' Index on the table based on UserID which is created as an 'int' data type with the 'Identity Specification' set to true with a count starting at 1 and incremented by 1.

**Comment by volkanceylan** [comment]
I meant unique index on username

**Comment by mlutzow** [comment]
Added a unique index to the UserName field and now the User 2 can successfully log in the first time but afterwards User 2 is always presented with Invalid username message (attached). 

I cycled through several users all of which were first time logged on and the also the admin account. All of the users were able to log on successfully several times but every time I came back to the User 2 account  (Ends with ii) I would get the invalid account message, now.


![dupliacteusersalmost](https://cloud.githubusercontent.com/assets/19471794/15553918/4d57fbb6-2276-11e6-80cd-79ddb6cb820d.PNG)

**Comment by volkanceylan** [comment]
Sorry but i can't reproduce this. Are you sure that your username field is not very short, e.g. 6-7 characters? I tried with a fake AD service that returns true for any username and tried with rsmith and rsmithii users the scenario you suggested but i got no such error.

**Comment by mlutzow** [comment]
The User and related tables are all Serenity, out of the box (so to say) tables, I have not customized or modified them at, in any way what-so-ever.  When Serenity launches the first time these tables are created by the migrations. The actual usernames being used are 7 characters and 9 characters, respectively and the users can't do much about the character length's of their names.

The Active Directory piece appears to be working absolutely fine. It appears to me that when Serenity has received the information from the AD, the check against the user table to either write a first time user (which seems to work fine for first time users) then for subsequent logins where the first x number of characters are the same (in our case the first 5 characters) seems to be what is used or triggers the issue, anything that would differentiate the name ('ii') is ignored for some reason after the first 5 characters and Serenity attempts to write a duplicate record.

I've seen AD do some interesting things, but that has been almost exclusively dealing with special characters (the '@', '$', and similar), these are plain text strings of letters where only the last two characters are different. I know the AD handles these two names correctly (they've been present for at least the last three years on the AD) so that is why I believe this to be a Serenity or more probably C# type of issue.

Unfortunately, my skill level with both Serenity and C# is rather low at this time and I really don't have the tools available to me to figure this one out, heck I don't even know where to start looking right now.

Regards.

**Comment by volkanceylan** [comment]
I dont think this is about two characters. It might be about case sensitivity. Serenity and AD is case insensitive while your collation is case sensitive. You should try converting collation for username column to SQL_LATIN1_GENERAL_CI_AS. Otherwise have to debug ActiveDirectoryService and AuthorizationService to see whats going on with your usernames.

**Comment by mlutzow** [comment]
Hadn't thought about the case sensitivity with regards to the user table. Every other user works without an issue, however, and I would think if this was due to case, all users would fail in the same way, which isn't the case.

**Comment by mlutzow** [comment]
Regardless, I'm pretty swamped trying to get this project completed and also trying to learn C#. The likelihood of this situation happening in production is quite small so I'll revisit this at another time when I have additional time.

Just found it as a definite bug when I was using some accounts I had access to and this happened.

**Comment by volkanceylan** [comment]
You may try lowercasing both with invariant culture in your AD provider.
