### ISSUE TITLE
Column Picker Presets in toolbar

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#728]
HI there, 

I've been transitioning a lot of my code into the .TypeScript flavor of serenity and I've been playing around with the column picker. 

I got the thought of using preset column pickers to create templates for the toolbar that will make up for quick preset I can then export using the excel exporter or pdf printer. 

I'm picking through the column-picker code but I figured I'd ask if you have any suggestion on the approach to create tool buttons that designates which columns to hide. 

i've been playing with the xyzGrid.ts with the following but still no success: 

 getButtons() {
            var buttons = super.getButtons();
            var MyRow = MatrixRow.Fields;

            buttons.push(Serenity.ColumnPickerDialog.createToolButton({
                grid: this,
                visibleColumns: MyRow.Make, MyRow.SerialNumber
                
            }));

            return buttons;
        }

I also find interesting the possibility of having these views appear in separate windows if possible since I could then set it in the navigation file so that I can click right into the view of choice from the side menu and then control the access to the views according to tenancy. 

Anyhow, Any guidance?

**Comment by volkanceylan** [comment]
You shouldn't use ColumnPicker for this, see guide about persisting / restoring settings manually.

**Comment by sayuga** [comment]
I continue to read on the persistent storage but, i may be (definitely am) in over my head. I've managed to get the persistent storage to function as needed while using the UserPreferences without much issue but I'm having difficulty in figuring out how to properly define multiple predefined lists of which columns to hide so that I may create button triggers for them. 


**Here is what I have so far:** 

In ScriptInitialization.ts (btw, manual says SiteInitialization.ts. Typo) I added the line: 

    Serenity.DataGrid.defaultPersistanceStorage = new UserLocalStorage();


**Then defined the custom provider in a separate .ts file:** 

namespace FMCDashboardv3 {

    export class UserLocalStorage implements Serenity.SettingStorage {
        getItem(key: string): string {
            return window.localStorage.getItem(
                Authorization.userDefinition.Username + ":" + key);
        }

        setItem(key: string, value: string): void {
            window.localStorage.setItem(
                Authorization.userDefinition.Username + ":" + key, value);
        }
    }
}

In the MatrixGrid.cs (the section I want with the views) I will be adding multiple buttons that will call the predefined view on click. 

               buttons.push({
                title: 'ReportView1',
                cssClass: 'add-button',
                onClick: () => {
                    this.getPersistanceStorage(<FMCorp.MatrixRow>{/*//<reference to function that hides un-needed columns>//*/ });
                }
            });

If I make progress on my own I'll write an update

**Comment by volkanceylan** [comment]
See methods at the end of guide, they are what you should call to store some settings manually and restore. Anyway user store is not somewhere you should store your custom settings. Take them from there ok but save them to a global table.

**Comment by sayuga** [comment]
Alright, I'll give that a try and let you know how it plays out. thanks for the gudance

**Comment by volkanceylan** [comment]
I may add a sample later for presets. Probably in a reporting page.
