### ISSUE TITLE
Feature request for InPlaceSearch (similar to InPlaceAdd)

### ISSUE THREAD

**Issue by tvldev02** [volkanceylan/Serenity#729]
Since lookup editor shows only NameField then sometimes it is difficult to find it by just NameField.

I think if we had button besides lookup editor and 
clicking this button would popup a grid with filter enabled 
and after selecting a record and closing the popup.

Thanks for your work. This is really awesome framework.

**Comment by VictorTomaili** [comment]
you can create new editor based lookup editor. AdvancedSearchLookupEditor and make pull request :smile:

**Comment by volkanceylan** [comment]
You may use a combination of fields as name field. I don't think opening another dialog to select something is a good idea. But might add a sample later.
