### ISSUE TITLE
How no permission works?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#731]
There are some pages where i don't want any permission. I checked in the template there is following field in PermissionKeys. (Means to remove permission and enable to everyone use *)
public const string NoPermission = " * ";

But i checked int function that NoPermission is not used hence i was getting unauthorized access for those pages. So i added following in HasPermission function -
```
if (permission == PermissionKeys.NoPermission)
                return true; //Check if NoPermission is defined that also allow to access
```

**Just want to confirm if this is the right way??**

 ```
public bool HasPermission(string permission)
        {
            if (Authorization.Username.ToUpper() == "ADMIN")
                return true;

            var user = (UserDefinition)Authorization.UserDefinition;
            if (user == null)
                return false;

            if (permission == PermissionKeys.NoPermission)
                return true; //Check if NoPermission is defined that also allow to access
            bool grant;
            if (GetUserPermissions(user.UserId).TryGetValue(permission, out grant))
                return grant;

            foreach (var roleId in GetUserRoles(user.UserId))
            {
                if (GetRolePermissions(roleId).Contains(permission))
                    return true;
            }

            return false;
        }
```

**Comment by volkanceylan** [comment]
No this is not correct way. If you don't want permissions, don't put permission attributes. Or use empty string for any users.

**Comment by ramveersgh** [comment]
Ah!!! Thanks for correcting me...
I got biased due to old code which has NoPermission field.

Thanks Again!!
