### ISSUE TITLE
AddEqualityFilter 

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity#732]
Volkan bey,

namespace Serenity

public abstract class DataGrid<TItem, TOptions>

public TWidget AddEqualityFilter<TWidget>(string field, string title = null, object options = null, Action<QuickFilterArgs<TWidget>> handler = null, Action<jQueryObject> element = null, Action<TWidget> init = null) where TWidget : Widget;

method u yerine ne kullanabilirim, typescript içerisinde ilgili method yer almıyor sanırım, saygılarımla.

**Comment by volkanceylan** [comment]
AddQuickFilter kullanabilirsiniz

**Comment by neonemivar** [comment]
Örnek bir satır varmıdır,

Uncaught TypeError: Cannot read property '__interfaces' of undefined

hatası alıyorum.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/698

**Comment by volkanceylan** [comment]
Server tarafında column üzerine [QuickFilter] da ekleyebilirsiniz.

**Comment by neonemivar** [comment]
QuestionBankEditor diye bir Serenity.LookupEditorBase<QuestionBankRow, any> class var ve bir önceki versiyonda 

`protected override void CreateToolbarExtensions() {
base.CreateToolbarExtensions();
QuestionBankFilter = AddEqualityFilter<QuestionBankEditor>(QuestionOptionRow.Fields.QuestionBankId); 
}`

şeklinde edit form oluşturulurken tanımlayıp daha sonra yan Tab da yer alan grid için ilgili filtre ile verileri çekiyordum.

Sizin önerdiğiniz yöntem için şu an hata vermekte, return type da sorun var. xxRow üzerine filtre olarak eklemekte çözüm üretmeyecektir. Yukarı da yer alan code TypeScript olarak yazılabilir mi?

**Comment by volkanceylan** [comment]
Niye çözüm üretmeyecektir, denediniz mi acaba?

[QuestionBankEditor, QuickFilter]
public string MyColumn;

ya da 

AddQuickFilter({
    type: QuestionBankEditor,
    field: QuestionOptionRow.Fields.QuestionBankId
});

**Comment by neonemivar** [comment]
İkinci satır çözüm üretti, 
Kodlama yapısı itibari ile çözüm üretmeyeceği yorumunda bulundum, yoksa yapının çalışmadığı anlamında değil, desteğiniz için teşekkür ederim,

Konu ile ilgili değil ancak, menü item tıklandığında grid boş geliyor, ikinci defa tıklamadan sonra grid dolmakta, bu tarz bir sorun yaşadınız mı? Projeye SlickGrid i ekledim sanırım sorun ondan kaynaklı diye düşünüyorum, Projede SlickGrid ihtiyaç yok sanırım,,,

**Comment by volkanceylan** [comment]
Evet ondan olmalı, SlickGrid zaten var include larda

**Comment by neonemivar** [comment]
Dediğiniz gibi az kullanılacak bir konu, mantık olarak browse edilecek bir item list üzerinden işleyiş yürütülür ise, farklı ihtiyaçlar (karar mekanizmaları) içinde kullanışlı olabilir,
