### ISSUE TITLE
FilterBar ile ilgili

### ISSUE THREAD

**Issue by neonemivar** [volkanceylan/Serenity#733]
Volkan bey,

Bir filtre eklediğinizde ve hide edildiğinde, quick-filters-bar ekran üzerinde ince bir çizgi olarak görünmekte, hiç görünmemesi daha iyi olabilir, saygılarımla.

![01](https://cloud.githubusercontent.com/assets/2571927/15573682/5983652a-2351-11e6-9935-55aa6403f6c9.PNG)

**Comment by VictorTomaili** [comment]
filtre eklendiğinde gizlenmesi gerekiyorsa bar'ı da gizleyebilrsiniz grid tarafında js yazarak. Bunun kontrolünün otomatik olması bir milyonda bir kullanılacak birşey.

**Comment by neonemivar** [comment]
Dediğiniz gibi az kullanılacak bir konu, mantık olarak browse edilecek bir item list üzerinden işleyiş yürütülür ise, farklı ihtiyaçlar (karar mekanizmaları) içinde kullanışlı olabilir,
