### ISSUE TITLE
Select all items in dropdown list

### ISSUE THREAD

**Issue by fzhenmei** [volkanceylan/Serenity#734]
Is there a way let user select all items of a dropdown list quickly?
Like below image, may be user can click some button or some combination key to select all items in "Representatives" dropdown list?
![select_all](https://cloud.githubusercontent.com/assets/167262/15578279/732ebb32-2392-11e6-992a-b0f29cb0daf2.png)

**Comment by VictorTomaili** [comment]
its select2 plugin. Look at select2 documentation for other options. You can write own editors

**Comment by volkanceylan** [comment]
There is a howto about integrating third party plugin.

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_use_a_third_party_plugin_with_serenity.html

**Comment by fzhenmei** [comment]
Thanks, i'll try it.
