### ISSUE TITLE
Set custom validator with custom error messagem

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#735]
how to set and show custom validator with custom error message, like the image bellow

![validator callout](https://cloud.githubusercontent.com/assets/19523455/15578570/5491b202-2337-11e6-87c9-4cc4cfdab119.png)

**Comment by volkanceylan** [comment]
This is not supported atm

**Comment by rolembergfilho** [comment]
Any example in how to do it with jQuery?

And where do it?

**Comment by volkanceylan** [comment]
I don't have an example

**Comment by UlyssesAlves** [comment]
I can see there's now code related to frontend validation. How to use ValidationHelper to set custom validation rules with ValidationHelper?

https://github.com/volkanceylan/Serenity/blob/master/Serenity.Scripts/CoreLib/UI/Helpers/ValidationHelper.ts
