### ISSUE TITLE
How to add a row field, which doesn't come from database? 

### ISSUE THREAD

**Issue by yj320696** [volkanceylan/Serenity#736]
Please make sure these boxes are checked before submitting your issue --- thank you!

- [x] Check Serenity Users Guide, including how-to and troubleshooting sections
- [x] Check Serenity WIKI in GitHub
- [x] Please have a look CHANGELOG.md for directions on breaking changes
- [x] Try a search for previous issues here, that might have similar case
- [x] Check your browsers's CONSOLE tab for errors, and include them here
- [x] Please report with as many details as possible to help us identify the problem

### Steps to reproduce the behavior
How to add a row field, which doesn't come from database? It could be a const value, or the calculation based on other row fields. I guess it should use "ClientSide" Attribute. Could you give me some example? Thanks.

**Comment by florin-nitulescu** [comment]
You declare it in your EntityRow like any other field (property in subclass of Row and - **very important** - corresponding field in RowFieldsBase subclass), but your decorate it with the ClientSideAttribute. If it's based on other db persisted fields you can decorate it with the **ExpressionAttribute** instead of ClientSideAttribute (I don't think you can do both) .

Example from **MovieTutorial** with Expression based field: 
```
public sealed class MovieCastRow : Row, IIdRow, INameRow
    {
        [DisplayName("Movie Cast Id"), Identity]
        public Int32? MovieCastId
        {
            get { return Fields.MovieCastId[this]; }
            set { Fields.MovieCastId[this] = value; }
        }

        //...

        [DisplayName("Actor/Actress"), NotNull, ForeignKey("[mov].Person", "PersonId"), LeftJoin("jPerson")]
        public Int32? PersonId
        {
            get { return Fields.PersonId[this]; }
            set { Fields.PersonId[this] = value; }
        }
       // ...
        [DisplayName("Actor/Actress"), Expression("(jPerson.Firstname + ' ' + jPerson.Lastname)")]
        [MinSelectLevel(SelectLevel.List)] // useful for loading field in master detail scenarios
        public String PersonFullname
        {
            get { return Fields.PersonFullname[this]; }
            set { Fields.PersonFullname[this] = value; }
        }

        // ....

        public static readonly RowFields Fields = new RowFields().Init();

        public MovieCastRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public readonly Int32Field MovieCastId;
            // ...
            public readonly Int32Field PersonId;
            
            // ....

            public readonly StringField PersonFirstname;
            public readonly StringField PersonLastname;

            public readonly StringField PersonFullname;

           // ....

            public RowFields()
                : base("[mov].MovieCast")
            {
                LocalTextPrefix = "MovieDB.MovieCast";
            }
        }
    }
```

If you use ClientSideAttribute and you can set it (through the property setter or field[row]) at any time. Don't replace the "standard" property getter. I think the framework retrieves the value using the inner field not the property getter.

You have an example with the ClientSideAttribute in the [gitbook](https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/the_cast_and_characters_they_played.html) for CastList property (which is loaded by a behavior).

**Comment by volkanceylan** [comment]
Thanks @florin-nitulescu

**Comment by yj320696** [comment]
Thanks @florin-nitulescu. It still has some problem.
I added clientside row field as you said, and override OnReturn function in MyRetrieveHandler. In OnReturn function, I set the value of that clientside row field.
If I want to show that extra field in the form to edit, yes, it works!
But if I just want to show it in grid, which comes from "...Cloumns" class, (ie, TransactionCloumns), MyRetrieveHandler is not called. 
Could you reopen the issue for me, please? @volkanceylan

**Comment by florin-nitulescu** [comment]
Adding the corresponding property in TransactionColumns class and overriding OnReturn in MyListHandler should work. Can you post a code example of how you handled OnReturn? Also try clearing your browser's cache and refresh. After that open developer console in browser and try Q.getColumns("Module.Entity") (replace "Module.Entity" with the key given to your columns class when decorated with the ColumnsScript attribute) to see how the JSON array that describes the grid columns.

**Comment by yj320696** [comment]
The code is very simple.
The new row field is called StoredTare, which is boolean type.
It should be set based on other row field, but at the moment, I hard code it to "true".
private class MyListHandler : ListRequestHandler<MyRow>
{ 
    protected override void OnReturn()
   {
        base.OnReturn();
        Row.StoredTare = true;
   }
}

**Comment by florin-nitulescu** [comment]
Ok. I see what s the problem. You have to foreach through **Response.Entities** and for each one of them to set the *StoredTare* property. In list request handler you do not return just one row... **Row** has another purpose here.

**Comment by yj320696** [comment]
Thanks. @florin-nitulescu . Problem is solved!

I have another minor issue, could you help me out if you like. Or I can create a new issue to address it.
The issue is about datetime type. I define it as DateTimeField in TransactionRow, and DateTime in TransactionCloumns. But it only shows date. And in edit dialog, only date editor is used to edit. How can I show both date and time, and edit them in same time? Thanks.

**Comment by volkanceylan** [comment]
Use [DateTimeEditor]

**Comment by yj320696** [comment]
Thanks. @volkanceylan, [DateTimeEditor] fixed the issue in the form.
But it is still displayed as date only in the grid.

**Comment by yj320696** [comment]
More information:
In my Script.js file, that DateTime field, which is named as "dateIn", use Serenity.DateEditor to get the value.
get_dateIn:function(){
    return this.byId(Serenity.DateEditor).call(this, 'DateIn');
}
Does that force datetime field as date field?

**Comment by yj320696** [comment]
Any thoughts? @volkanceylan @florin-nitulescu 
Is it a bug? I am using Serenity 1.8.20

**Comment by volkanceylan** [comment]
Use DispalyFormat or DateTimeKind. Its not a bug.
