### ISSUE TITLE
CssClass attribute in xyzRow

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#737]
Dear @volkanceylan,
I've added a CssClass attribute in two fields of my xyzRow: CssClass("myclass")
Now I'm trying to call the following methods on such items:

    Serenity.EditorUtils.setRequired()
    Serenity.EditorUtils.setReadOnly()

but probably I'm doing something wrong.
In fact I'm trying with:

    this.element.find(".myclass")
    this.element.find(".myclass").closest(".editor")

but I'm not able to retrieve/cast the right element...which is the better way to retrieve the Serenity.Widget object (looking by cssclass) in order to pass them to your utility function?

Thank you very much

**Comment by volkanceylan** [comment]
Not closest, continue with find, closest looks at parents, your editors are under field div

**Comment by marcobisio** [comment]
Serenity.EditorUtils.setRequired(this.element.find(".myclass").find(".editor").getWidget(Serenity.StringEditor), true);

something like that?
I have to iterate with jquery or your utility accept also a collection of object?

thanks!

**Comment by marcobisio** [comment]
This is working fine...

    this.element.find(".myclass").find(".editor").each(function () {
                Serenity.EditorUtils.setRequired($(this).getWidget(Serenity.Widget), true);
            });

**Comment by marcobisio** [comment]
Forgot to close sorry!

Thanks
Bye

**Comment by volkanceylan** [comment]
Another option:

Serenity.EditorUtils.setReadOnly(this.element.find(".myclass").find(".editor").map(x => $(x).getWidget(Serenity.Widget), true))

**Comment by marcobisio** [comment]
Even better!
Thank you very much!
Bye
