### ISSUE TITLE
xyzDialog.cs; trailing spaces in a field are trimmed off when they are required; how to disable trimming

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#739]
Hi JaiQ,

John Ranger here again with an issue.

- [X ] Check Serenity Users Guide, including how-to and troubleshooting sections
- [ ] Check Serenity WIKI in GitHub
- [ X] Please have a look CHANGELOG.md for directions on breaking changes
- [ X] Try a search for previous issues here, that might have similar case
- [X] Check your browsers's CONSOLE tab for errors, and include them here
- [X] Please report with as many details as possible to help us identify the problem

### Configuration (Serenity / Serene version, OS, Browser used etc.)
- Serenity V1.9.13
- Any browser
- SQL 2012

### Expected behavior
Content which Comes from DB and is displayed within a field in a Dialog (even with leading/trailing spaces) and the Content of the field is not modified and then the update button is clicked - must never be trimmed.

Why would I want/Need that? For example the SerialNumber field of a VMware virtual machine has unfortunately a trailing space and I Need to store this unmodified.

### Actual behavior
Content loaded from DB into a field in a Dialog (Content has trailing spaces) is properly displayed (has the trailing spaces). When the update button is clicked, the Content of the field with trailing spaces is trimmed and then stored back into the DB

### Steps to reproduce the behavior
1) Create Content in a field in DB with trailing spaces which is in table used by xyzRow.cs
2) Within xyzGrid (in GUI), click on the record, in which you have created the Content with trailing spaces
3) check within relevant field that there are the trailing spaces
4) Click on update button
5) Within xyzGrid (in GUI), click on the record, in which you have created the Content with trailing spaces
6) check within relevant field that there are the trailing spaces --> they are gone

Question: Is there a way to configure the trim behavior of fields within a Dialog and if yes, how?

Thank you and with Kind regards,

John

**Comment by volkanceylan** [comment]
Add to your field

[SetFieldFlags(FieldFlags.None, FieldFlags.TrimToEmpty)]

**Comment by volkanceylan** [comment]
or better

[SetFieldFlags(FieldFlags.None, FieldFlags.TrimToEmpty | FieldFlags.TrimToNull)]

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks again for your very fast answer. It seems to me that in V1.9.13 the TrimToNull command does not yet exist. Only the TrimToEmpty exists.

I have added the SetFieldFlags command as in your 1st suggestion (in xyzRows.cs on the SerialNumber field) but the behavior didn't change - On clicking the update button, the trailing spaces are still trimmed off.

Do I have to update the Serenity framework (which I would try to avoid as the V1.9.13 is extremely stable and I don't yet feel comfortable with the change to TypeScript/no Saltarelle and all breaking changes from V1.9.13 to the current version) in order to make this work?

With kind regards,

John

**Comment by volkanceylan** [comment]
Try Trim

**Comment by JohnRanger** [comment]
HI JaiQ,

thanks again. I have (for testing reasons) now temporarily upgraded the Serenity FW to the newest available version and added trim instead of TrimToNull (as TrimToNull also does not exist in the newest SFW).

The definition within xyzRows.cs loooks now like this:

```cs
 [DisplayName("Db.Clients.Clients.SerialNumber"), Size(100), NotNull, QuickSearch]
        [SetFieldFlags(FieldFlags.None, FieldFlags.TrimToEmpty | FieldFlags.Trim)]
        public String SerialNumber
        {
            get { return Fields.SerialNumber[this]; }
            set { Fields.SerialNumber[this] = value; }
        }
```

But: Still no success. The trailing spaces are still trimmed off when clicking on update.

Do I have to do something on the client side or is this something which happens in the xzRepository.cs?

With kind regards,

John

**Comment by volkanceylan** [comment]
Try with [SetFieldFlags(FieldFlags.None, FieldFlags.Trim)], if it is still not working, sorry but Serenity is not trimming anything other than this flags.

**Comment by JohnRanger** [comment]
Hi JaiQ,

I have also tried the following - but with no avail:

```cs
[SetFieldFlags(FieldFlags.None, remove:FieldFlags.Trim)]
```

This is with the latest SFW.

May I ask for your help what to do?

With kind regards,

John

**Comment by volkanceylan** [comment]
Man i told you, Serenity is not trimming anything. Check SQL side.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thank you for your continual support.
In order to be sure and to verify your saying, I have created a new serene project with the newest serene template 2.2.1.1.

I have only modified the productsRow.cs like this:

```cs
[DisplayName("Product Name"), Size(40), NotNull, QuickSearch, LookupInclude]
        [SetFieldFlags(FieldFlags.None,FieldFlags.Trim | FieldFlags.TrimToEmpty)]
        public String ProductName
        {
            get { return Fields.ProductName[this]; }
            set { Fields.ProductName[this] = value; }
        }
```
and then added a space in the product name of ProductID 17 (Alice Mutton) directly in the database.

*Result:*
- The space is showed correctly when opening the relevant dialog in products
- The space gets trimmed when pressing the update button

The following is the relevant part from SQL trace with debugging log level on:
```SQL
[D] 2016-05-30T14:08:13.747 END - ExecuteReader
[D] 2016-05-30T14:08:13.758 ExecuteNonQuery
DECLARE @p1 NVARCHAR(4000) = 'Alice Mutton';
DECLARE @p2 NVARCHAR(1) = NULL;
DECLARE @p3 BIT = 1;
DECLARE @p4 INT = 7;
DECLARE @p5 INT = 6;
DECLARE @p6 NVARCHAR(4000) = '20 - 1 kg tins';
DECLARE @p7 DECIMAL = 39;
DECLARE @p8 SMALLINT = 0;
DECLARE @p9 SMALLINT = 0;
DECLARE @p10 SMALLINT = 0;
DECLARE @p11 INT = 17;

UPDATE [Products] SET [ProductName] = @p1, [ProductImage] = @p2, [Discontinued] = @p3, [SupplierID] = @p4, [CategoryID] = @p5, [QuantityPerUnit] = @p6, [UnitPrice] = @p7, [UnitsInStock] = @p8, [UnitsOnOrder] = @p9, [ReorderLevel] = @p10 WHERE ([ProductID] = @p11)
```
As you can see, the trailing space is already trimmed off when the declare@p1 is generated from Serenity framework.

According to my current understanding, the FieldFlags removing of trim and trimToEmpty does somehow not work (or do not have the desired effect) and Serenity FW is continually trimming off the trailing space in the fields.

Sorry to bother you with something like this but may I ask you to have a look into this by yourself?

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi JaiQ,

during further investigation, I have modified the beforeSave method in the productRepository like this:

```cs
            protected override void BeforeSave()
            {
                var bla = "'" + Row.ProductName + "'";

                base.BeforeSave();

                var bla2 = "'" + Row.ProductName + "'";

            }
```
Before the update even hits the database, the var bla shows that the trailing spaces are already trimmed off by the Serenity framework.

So I am back at my saying that the spaces are trimmed off by the SFW and not by the database. :-)

May I kindly ask you to verify this for yourself and investigate why the fieldflags removing of trim and trimtoempty do not work?

In the meantime, I will try to figure out what on the client side is responsible for the trimming.

Thanks again and with kind regards,

John

**Comment by volkanceylan** [comment]
Did you try with [SetFieldFlags(FieldFlags.None, FieldFlags.Trim)]

**Comment by JohnRanger** [comment]
Hi JaiQ,

yes - I tried the above variant and also the one which has both trim flags removed. But both have the same (non)-effect.

Means: Both do not prevent the SFW of trimming off the trailing spaces.

With kind regards,

John

**Comment by volkanceylan** [comment]
Ok i understood the problem:

There is a bug in RowFieldsBase

```
                            foreach (var attr in property.GetCustomAttributes<SetFieldFlagsAttribute>(false))
                            {
                                addFlags |= attr.Add;
                                removeFlags |= attr.Remove;
                            }
```

It doesn't remove Trim flag, but add it again.

Till this is resolved you can do so:

```cs
            public RowFields()
                : base("Products")
            {
                LocalTextPrefix = "Northwind.Product";
            }

            protected override void AfterInitialize()
            {
                base.AfterInitialize();

                ProductName.Flags -= FieldFlags.Trim;
            }
```

**Comment by volkanceylan** [comment]
Hmm thats not the bug :(

**Comment by volkanceylan** [comment]
Ok, hope this time correct, remove NotNull from your field for now. Use Required in Form, not Row. This should resolve the issue. This is caused by required field validation trimming before checking if field value is empty.

**Comment by volkanceylan** [comment]
And better ask VMWare what kind of genius decided to put trailing whitespace to machine keys :|

**Comment by JohnRanger** [comment]
I have quickly tested - the workarround didn't prevented SFW to still trim the trailing space.

Also: I have put the following code within AfterInitialize:
```cs
protected override void AfterInitialize()
            {
                var bla1 = ProductName.Flags;

                base.AfterInitialize();

                var bla4 = ProductName.Flags;

                ProductName.Flags -= FieldFlags.Trim;
            }
```

but bla1 shows only the following fieldflags:

```cs
Serenity.Data.FieldFlags.Insertable | Serenity.Data.FieldFlags.Updatable | Serenity.Data.FieldFlags.NotNull
```

So according to my understanding, there are already no Trim flags at this time for the ProductName field.

In comparison - When I remark the SetFieldFlags line in the field definition, it looks like this:
```cs
Serenity.Data.FieldFlags.Required
```

As FieldFlags.Required contains NotNull, trim, updatable and insertable, it seems to me that the removal of the trim flag works correctly but it has no effect on the trimming.

With kind regards,

John

**Comment by JohnRanger** [comment]
I have now:

- No SetFieldFlags in xyzRow.cs
- The following line in xyzForm.cs:
```cs
 [SetFieldFlags(FieldFlags.Required, FieldFlags.NotNull | FieldFlags.Trim)]
```

I have also tried only with the below in xyzForm.cs:
```cs
 [SetFieldFlags(FieldFlags.Required, FieldFlags.NotNull]
```

But the var bla in the BeforeSave method shows still a trimmed off field.

```cs
protected override void BeforeSave()
            {
                var bla = "'" + Row.ProductName + "'";

                base.BeforeSave();

                var bla2 = "'" + Row.ProductName + "'";

            }
```

Did I miss something in your explanation above?

With kind regards,

John

**Comment by JohnRanger** [comment]
Hmm, that was what I have done all along since I have had your first response (this is in xyzRow.cs).

The problem with that is that if you check the value of 
*ProductName.Flags* in the AfterInitialize event (like I did below), it always forcibly defaults to FieldFlags.required which includes the trim flag - no matter if you try to remove it in the SetFieldFlags definition with [SetFieldFlags(FieldFlags.None, FieldFlags.Trim)] .

```cs
 protected override void AfterInitialize()
            {
                var bla1 = ProductName.Flags;

                base.AfterInitialize();

               ProductName.Flags -= FieldFlags.Trim;
            }
```

So currently it is not possible to remove the Trim flag within SetFieldFlags definition in xyzRow.cs because something is always forcing it to have at least the FieldFlags.required flags.

I also have tried to not set a SetFieldFlags definition in xyzRows.cs and only put the definition on the field in the xyzForm.cs like this:
```cs
[SetFieldFlags(FieldFlags.None, FieldFlags.Trim)] 
```

but still the space gets trimmed of the moment when the update button is clicked.

Question: Where actually is the trimming done? on the client side or in the repository part?

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi JaiQ,

based on all of your input, I have experienced a bit more and found the following temporary solution:

In the afterInitialize event, I also remove the NotNull flag and then it preserves the trailing space:

```cs
 protected override void AfterInitialize()
            {
                var bla1 = ProductName.Flags;

                base.AfterInitialize();

               ProductName.Flags -= FieldFlags.Trim;
               ProductName.Flags -= FieldFlags.NotNull;

            }
```

From my understanding, there is a logic within SFW which prevents the removal of flags via SetFlags if it tries to remove some of the "required" flags. Maybe this behavior should be changed for the trim flag and the NotNull flag (I don't know the reason why the trim flag and the NotNull flag is member of the "required" flags).

I am looking forward to see how you tackle this one :-)

Thanks for all of your help and with kind regards,

John
