### ISSUE TITLE
 using sqlserver 2005  List paging have worng

### ISSUE THREAD

**Issue by kuyu7766** [volkanceylan/Serenity#74]
We use sqlserver 2005 .The database is not supported FETCH to  list paging. but  we must use this version sqlserver. How can I do it to adapt  this version ?

**Comment by volkanceylan** [comment]
You can set dialect for connections in ApplicationStart method:

```cs
    public static partial class SiteInitialization
    {
        public static void ApplicationStart()
        {
            try
            {
                SqlConnections.GetConnectionString("Default").Dialect = 
                       SqlServer2005Dialect.Instance;
                SqlConnections.GetConnectionString("Northwind").Dialect = 
                       SqlServer2005Dialect.Instance;
                SqlSettings.AutoQuotedIdentifiers = true;
                Serenity.Web.CommonInitialization.Run();
```

Next version will also support this through a appSettings key.

**Comment by kuyu7766** [comment]
sorry, i didn't mean  how to change the database connection to change the system default database version.  I mean when I use sqlserver2005 ,the function of list  paging will be wrong. And I have konw the reason is that this version of database is not support "FETCH... From...Next" SQL syntax. So if I want to use sqlserver2005   how can i do with it.

**Comment by volkanceylan** [comment]
This is how you can do it :) Did you try it?

**Comment by volkanceylan** [comment]
See https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_set_database_dialect_for_connections.html

**Comment by kuyu7766** [comment]
Thank you very much:)

**Comment by volkanceylan** [comment]
you're welcome ;)
