### ISSUE TITLE
Template.PropertyPanel is not found in registered script list

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#740]
I'm attempting to get my Serenity solution building and running on another machine; it works on the old one, fails on the new with 

> Error: Script data Template.PropertyPanel is not found in registered script list!

 when it tries to load the login page http://localhost:58619/Account/Login?ReturnUrl=%2f

I've compared the http requests, they're requesting and receiving the same things, no errors. I've translated the T4 templates, Clean and Rebuild, but same result. Any ideas where I can look to figure this out?

### Configuration (Serenity / Serene version, OS, Browser used etc.)
2.2.0
### Expected behavior
Login page loads without error
### Actual behavior
Fails to load with > Error: Script data Template.PropertyPanel is not found in registered script list!
### Steps to reproduce the behavior

**Comment by wldkrd1** [comment]
Some observations: the new computer is configured with a different locale (en-GB). Template.PropertyPanel is not in the registered scripts for either machine, but only the new machine appears to be trying to use it. I'm switching the locale match the old system, will update if any change.

**Comment by wldkrd1** [comment]
Ok, that's not it, but it looks like it isn't resolving the type correctly.
Working: e.__typeName = "MyProject.Membership.LoginPanel"
Not working: e.__typeName = "Serenity.PropertyPanel"

Still digging...

**Comment by volkanceylan** [comment]
I remember such a report from another user before, but couldn't reproduce it. It's strange as LoginPanel uses a template embedded in CSHTML, so it doesn't have to be in registered scripts.

What do you get when you type MyProject.Membership.LoginPanel.__typeName

**Comment by rolembergfilho** [comment]
Hey wldkrd1,

did you made a deploy in the new machine?
or did you open VS and run serenity?

if you did a deploy in a new machine, what's happened to me is the intial login screen was blank.

so i opened IIS and set Application Pool of the site to:
- .NET  4.5
- Integrated Pipeline

and it's works fine.

when I changed to classic pipeline, it's fails again. So i leave this configuration to Integrated Pipeline.

Is this the error that you wrote?

**Comment by volkanceylan** [comment]
Classic is for IE6 compability mode. Any recent app should use Integrated mode. I don't think wldkrd1 is having this issue.

**Comment by wldkrd1** [comment]
MyProject.Membership.LoginPanel.__typeName returns "Serenity.PropertyPanel"

**Comment by wldkrd1** [comment]
Using IISExpress with Integrated Pipeline

**Comment by wldkrd1** [comment]
Here are a couple screenshots of the javascript debugger right about the time things go haywire. First the working one:
![goodloginpanel](https://cloud.githubusercontent.com/assets/2817543/15682962/eba29a54-2714-11e6-8a73-dba3886eeb7a.png)

And here's the busted one: 
![badloginpanel](https://cloud.githubusercontent.com/assets/2817543/15682964/ee1fdb48-2714-11e6-885d-35a937724a47.png)

**Comment by volkanceylan** [comment]
Register true in second screenshot shows like Serenity method that registers classes with Saltaralle couldnt run there. Can you check if enumerateTypes method is hit?

**Comment by wldkrd1** [comment]
Running Fiddler, I'm not finding enumerateTypes in any of the sessions sent to the browser. I see it in Serenity.CoreLib.js but not in any of the bundles.

**Comment by volkanceylan** [comment]
It is called by initializeTypes. Probably minimize is on, turn of minimize flag and try again.

**Comment by wldkrd1** [comment]
Ok, turned off minimizing and now I see it being hit. namespaces has one item, "Serenity". So far looks the same between working and not.

**Comment by wldkrd1** [comment]
Ok, now I've got both machines failing with the same error. I had upgraded this solution to remove the Script project, but the MyProject.Script.js was still being referenced (and it still existed on disk on my old machine). Those files, since they are generated, are not stored in TFS so it doesn't exist on the new machine.

Once I removed the reference to it on the old machine, the error shows up there as well.

**Comment by wldkrd1** [comment]
Since these were converted by hand, I suspect I neglected to do something which sergen does when creating new forms.

**Comment by volkanceylan** [comment]
Maybe reference exists in ScriptBundles.json?

**Comment by volkanceylan** [comment]
In your ScriptInitialization.ts there should be your root namespace added, e.g. Serene

**Comment by wldkrd1** [comment]
Aha, that was it. ScriptInitialization.ts didn't exist in my project, looks like I missed that one. Added it and all is well with the world.

Unrelated, but Serenity.CoreLib.d.ts doesn't seem to be generating Serenity.CoreLib.js. Should it?

**Comment by volkanceylan** [comment]
CoreLib.d.ts is a output file, it is output of CoreLib.ts in Serenity.Web, along with CoreLib.js

**Comment by wldkrd1** [comment]
Got it. Thanks for the help!
