### ISSUE TITLE
how to add Default user id in table column also how to add record in history table for all the change  

### ISSUE THREAD

**Issue by shailendrasingh03** [volkanceylan/Serenity#741]
Please make sure these boxes are checked before submitting your issue --- thank you!

- [ ] Check Serenity Users Guide, including how-to and troubleshooting sections
- [ ] Check Serenity WIKI in GitHub
- [ ] Please have a look CHANGELOG.md for directions on breaking changes
- [ ] Try a search for previous issues here, that might have similar case
- [ ] Check your browsers's CONSOLE tab for errors, and include them here
- [ ] Please report with as many details as possible to help us identify the problem

### Steps to reproduce the behavior

**Comment by volkanceylan** [comment]
See LoggingRow, ProductRow and ProductLogRow.

**Comment by shailendrasingh03** [comment]
Thanks a lot .. for help ..
