### ISSUE TITLE
any way to upload data from excel 

### ISSUE THREAD

**Issue by shailendrasingh03** [volkanceylan/Serenity#744]
Please make sure these boxes are checked before submitting your issue --- thank you!

- [ ] Check Serenity Users Guide, including how-to and troubleshooting sections
- [ ] Check Serenity WIKI in GitHub
- [ ] Please have a look CHANGELOG.md for directions on breaking changes
- [ ] Try a search for previous issues here, that might have similar case
- [ ] Check your browsers's CONSOLE tab for errors, and include them here
- [ ] Please report with as many details as possible to help us identify the problem

### Steps to reproduce the behavior

**Comment by volkanceylan** [comment]
No, EPPlus can read Excel files though.

**Comment by shailendrasingh03** [comment]
how to work on Bulk data upload by user any other way .. also any way to make textbox field disable from client side avoiding entering data from front end .. 

One more thing thanks for giving this framework .. 

this is one of the best opensource framework i have ever seen .

**Comment by volkanceylan** [comment]
Thanks, but i don't have sample for bulk data upload.
