### ISSUE TITLE
Upload pt-br Translation

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#745]
Hey Volkan,

The pt translation in serenity is pt from Portugual.

So, I did the pt-br translations:
- serenity.texts.pt-br.json
- site.texts.pt_br.json

how can i send them for you?

**Comment by dfaruque** [comment]
Please ask to google how to pull request in github or some thing like this...

**Comment by volkanceylan** [comment]
Yes, pull request or share them as gist, using link on top right

**Comment by rolembergfilho** [comment]
for my 1st collaboration, i preffer do a gist (in order to avoid doing mistake in pull request!)

here's the link: https://gist.github.com/rolembergfilho/b7130acd54c278491ca568397e93f085

**Comment by volkanceylan** [comment]
Thanks, especially for splitting Serenity and Site texts, it was very helpful.
