### ISSUE TITLE
How to set value in select2 editor

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#746]
Hi Jaiq,

I have this custom editor

[Editor]
    public class Acdceditor : Select2Editor<object, object>
    {
        public Acdceditor(jQueryObject hidden)
            : base(hidden, null)
        {
            AddItem("AC", "AC");
            AddItem("DC", "DC");
        }
    }

how to set value to this editor? try this in loadentity but cannot work

form.Acdc.Value = entity.Acdc;

and

J(".field.Acdc").value(entitiy.Acdc);

Thanks

**Comment by volkanceylan** [comment]
It is loaded from entity, whatever value is there. What are you trying to do.

**Comment by fazanan** [comment]
form.Acdc. is my editor in form (AcdcForm.cs)

public String Acdc { get; set; }

and below my Acdc property in Row (AcdcRow.cs)

[DisplayName("AC/DC"), Column("ACDC"), Acdceditor]
        public String Acdc
        {
            get { return Fields.Acdc[this]; }
            set { Fields.Acdc[this] = value; }
        }

How to set value in form.Acdc?

**Comment by volkanceylan** [comment]
form.Acdc.Value = "CC"

**Comment by AlifAbhiesa** [comment]
value text isn't show

**Comment by AlifAbhiesa** [comment]
Here's my form

![image](https://user-images.githubusercontent.com/27193997/42358590-8bf29b00-8107-11e8-89f5-e394ce66ff47.png)

and this my code to set the default value, but value didn't show

![image](https://user-images.githubusercontent.com/27193997/42358626-b5848c1c-8107-11e8-8479-58b3c4e7752f.png)

can you please explain @volkanceylan
