### ISSUE TITLE
How to show all items in lookupeditor if cascade field does not have value. 

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#747]
Is it possible to show all Items if cascade field is not selected. Currently its does not show any item until cascade field does not have any value.
Ex. 
**Client** and **Branch** are two lookup editors.
If we select Client then Branch is filtered according to selected client and if we do not select client then Branch will also not have any item to select.

I want if Client is not selected then Branch should show all items for all client and when client is selected then Branch should filter for selected client only.  

How to do this?

**Comment by volkanceylan** [comment]
Write a custom editor deriving from LookupEditorBase, override CascadeItems method, have a look at original source and modify it as you like.

**Comment by ramveersgh** [comment]
Thanks!
I will have a look and let you know.
