### ISSUE TITLE
Adding oracle dialect to serenity

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#748]
I am now trying to add oracle dialect.

What I have done:
copy an existing dialect and change some properties getter.

I am now stack on giving oracle compatible parameter name.

How can I replace @ sign before each parameters.

Please advice.

Thanks

**Comment by dfaruque** [comment]
I have found a place where you have placed the @ sign

        public static string IndexParam(this int param)
        {
            if (_indexParam == null)
            {
                var indexParam = new string[1000];
                for (int index = 0; index < indexParam.Length; index++)
                    indexParam[index] =  "@p" + index;
                _indexParam = indexParam;
            }

            if (param >= 0 && param < _indexParam.Length)
                return _indexParam[param];
            else
                return "@p" + param;
        }

Now how to decide whether to put @ sign here or not based on selected dialect (Oracle dialect) here.

**Comment by volkanceylan** [comment]
Don't replace @ sign, ADO should handle it

**Comment by volkanceylan** [comment]
Seems like not, but not sure if this is correct place to do this. There is no dialect info here.

**Comment by dfaruque** [comment]
I have successfully executed list request in oracle. Now I have to somehow replace @ sign to :
https://msdn.microsoft.com/en-us/library/yy6y35y8(v=vs.100).aspx

**Comment by dfaruque** [comment]
This code is executes fine

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.OracleClient;
using System.Data;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            OracleConnection con = new OracleConnection("Data Source=tvl11g;User ID=SecurityDB;Password=SecurityDB;");

            var sql = @"SELECT T0.CompanyID CompanyId,
                        T0.CompanyName CompanyName,
                        T0.ADDRESS ADDRESS,
                        T0.CreatedBy CreatedBy,
                        T0.UpdatedBy UpdatedBy,
                        T0.CreatedDate CreatedDate,
                        T0.UpdatedDate UpdatedDate,
                        T0.ApplicationId ApplicationId
                      FROM TblCompany T0
                      WHERE(T0.CompanyID = :p1)";

            OracleCommand com = new OracleCommand(sql, con);
            com.Parameters.AddWithValue(":p1", 1);
            OracleDataAdapter da = new OracleDataAdapter(com);
            DataSet ds = new DataSet();
            con.Open();

            da.Fill(ds);



            con.Close();
        }
    }
}

**Comment by dfaruque** [comment]
Should I add a property called ParameterPrefix to ISqlDialect?

**Comment by volkanceylan** [comment]
I'm not sure where to inject this change. I'll have a look at your pull request, than try to handle that myself later. Must make sure Serene, and Northwind works with Oracle out of the box.
