### ISSUE TITLE
Q.text('Order.Function.StartPicking') not work

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#749]
I use `Q.text('Order.Function.StartPicking')` in TypeScript,
and in user.texts.zh-CN.json, i wrote `"Order.Function.StartPicking": "开始配货",` but why it not work, it still display 'Order.Function.StartPicking', Did i miss something?

**Comment by volkanceylan** [comment]
See FAQ / Troubleshooting
