### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by yankerssnh** [volkanceylan/Serenity#75]
Not worked, if date as dd.MM.yyyy format

**Comment by volkanceylan** [comment]
What and where not worked, explain please, i can't read minds

**Comment by yankerssnh** [comment]
[DisplayName("Dt"), Column("dt"),DisplayFormat("dd.MM.yyyy HH:mm:ss"),DateTimeEditor()]
        public DateTime? Dt
        {
            get { return Fields.Dt[this]; }
            set { Fields.Dt[this] = value; }
        }

When add filter ("edit filter" button in table) for this DT, it in "dd/MM//yyyy". So grid not filtered.

![image](https://cloud.githubusercontent.com/assets/7975431/11810550/b9b7b59e-a350-11e5-8489-c3f5d60a8885.png)

**Comment by volkanceylan** [comment]
I'll have a look, what is your system culture and meanwhile can you try with 8/8/2015 to see if they are filtered.

**Comment by yankerssnh** [comment]
yes, if 1 dec 2015 write as 12/01/2015 is work. But build-in calendar editor return it as 01/12/2015. Yes, I think culture problem

**Comment by volkanceylan** [comment]
You are probably setting display format for date columns manually. As the format in displayed strings and your server/client culture doesn't match, it's normal to have such errors.

Can you set culture in web.config to some culture that handles dates in dd/MM/yyyy format like this:

<globalization culture="tr-TR" uiCulture="tr-TR" />

Culture is what is important, uiCulture is for translations only.

and try again?

**Comment by yankerssnh** [comment]
Result is same, not filtered. I tried with
<globalization culture="tr-TR" uiCulture="tr-TR" />
and my 
<globalization culture="ru-RU" uiCulture="auto:ru-RU" />

**Comment by volkanceylan** [comment]
I'm trying but can't reproduce this. Does your dates looks in M/d/y format if you don't set culture in web.config? And what is your control panel system culture set?

**Comment by yankerssnh** [comment]
yes, if not use display format it in M/d/y

my culture in Windows is ru-RU, d/m/y format

**Comment by volkanceylan** [comment]
I did this but still no luck. Actually i noticed i forgot to pass culture information to script side in Serene. But this means  whatever you server culture is it will show dates in default d/m/y format. I can't understand how in your case it shows in m/d/y format. Can you set a demo site so i can have a look?

**Comment by yankerssnh** [comment]
demo - it is sample project of serene. As is

**Comment by yankerssnh** [comment]
if I dont use display format, I have "d/m/yyyy". But datetime editor has "m/d/yyyy". I think it is problem

**Comment by volkanceylan** [comment]
How do you change datetime editor to m/d/y. Display format only affects columns, not editors.

**Comment by yankerssnh** [comment]
simply, instead 1 dec 15 (01/12/15), I use for example 12 Jan 15 (12/01/15).

**Comment by VictorTomaili** [comment]
wahat about IIS culture config?

**Comment by volkanceylan** [comment]
IIS culture shouldn't matter. Btw, he says if he dont set culture, dates in columns shows in m/d/y format. First need to understand how it is possible.

**Comment by volkanceylan** [comment]
@yankerssnh, i'm afraid only way i can help you is set a public web site, where i can have a look how dates look in m/d/y format. Or teamviewer etc. PM me with details

**Comment by yankerssnh** [comment]
ok, I`ll try do public. But I think filter culture is not right

**Comment by volkanceylan** [comment]
@yankerssnh are you going to offer a public site?

**Comment by yankerssnh** [comment]
sure, but I think after NY holidays :) Happy NY to all :)

**Comment by volkanceylan** [comment]
Please reopen if script culture functionality in latest Serene doesn't resolve your problem.
