### ISSUE TITLE
Serenity.Web.RowLookupScript and Serenity.Data.IIsActiveDeletedRow

### ISSUE THREAD

**Issue by florin-nitulescu** [volkanceylan/Serenity#750]
RowLookupScript<TRow> does not filters rows based on IIsActiveDeletedRow.IsActiveField causing deleted (IsActive = -1) rows to show up in LookupEditor.

**Comment by volkanceylan** [comment]
So you can filter them if you like

**Comment by florin-nitulescu** [comment]
Sorry! Now I noticed the FilterField and FilterValue properties on the LookupEditorAttribute. I saw that the EntityGrid and the EntityDialog knows about the IIsActiveDeletedRow interface and I assumed that the LookupScript should know too :( 

Can you help me please with a short suggestion on how can I replace the RowLookupScript class with a custom subclass of that for filtering inactive rows? If it's possible want to avoid using FilterField and FilterValue on all my lookup editors and adding LookupInclude attribute on all IsActive fields.

**Comment by volkanceylan** [comment]
You should just override PrepareQuery, cast Row to IIsActiveDeletedRow, have reference to IsActiveField and

query.Where((Field)((Row as IIsActiveDeletedRow).IsActiveField) >= 0)

**Comment by florin-nitulescu** [comment]
OK! Thank you!
