### ISSUE TITLE
ActiveDirectoryService problem with username casing

### ISSUE THREAD

**Issue by florin-nitulescu** [volkanceylan/Serenity#751]
The problem is that it seems like active directory usernames are case insensitive but the usernames in serenity are case sensitive.

For example: If I login with the AD user **"Radu"** and the password validation passes then at the first login a user with username **"radu"** (this is the username stored in the directory entry) is created. If Radu signs out and logins again typing "Radu" for username then UserRetrieveService will not find an entry. The *AuthenticationService* will consider him a first time user and will create another entry with the same username **"radu"** in the database. From now on ... you know!

P.S.: When debugging this the *TwoLevelCache* may help hide the problem by saving the *UserDefinition*.

**Update**: I've noticed that **the serenity usernames are actually case insensitive :)** and the problem can be reproduced only when trying username "Radu" the first time and the second time also. If you try something like "Radu" for the first time and then "rAdu" for the second time it will work. I think that it's something related to caching but I can't figure out what. For some reason after the first login the caching - inside *TwoLevelCache.GetInternal* - returns *DBNull.Value* for "UserByName_Radu" and does not invokes the **loader** function returning null to the caller (*UserRetriveService.ByUserName*). I can't figure out where from the *DBNull.Value* is coming.

**Comment by volkanceylan** [comment]
return TwoLevelCache.Get<UserDefinition>("UserByName_" + username

You may use username.ToLowerInvariant() there

**Comment by volkanceylan** [comment]
I also did this change in latest template, so this should be resolved.
