### ISSUE TITLE
Error in Select2Editor typescript

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#752]
Hi Jaiq,

I have custom editor with typescript below

@Serenity.Decorators.registerEditor()
    export class ClientEditor extends Serenity.Select2Editor<Object, Object> {

        constructor(hidden: JQuery) {
            super(hidden, null);
            super.addItem("Clieant A", "Clieant A");
            super.addItem("Clieant B", "Clieant B");
            super.addItem("Clieant C", "Clieant C");
        }
    }

No data loaded and error as captured
![g](https://cloud.githubusercontent.com/assets/6382278/15666192/93f3b322-2739-11e6-8b6d-9db544c41e15.PNG)
![e](https://cloud.githubusercontent.com/assets/6382278/15666033/b0a5d370-2738-11e6-98bb-c268495c8af4.PNG)
![f](https://cloud.githubusercontent.com/assets/6382278/15666101/0d191752-2739-11e6-90ad-356d5467bbc7.PNG)

**Comment by volkanceylan** [comment]
No idea, find out why your text is null

**Comment by weiguanhai** [comment]
have you solved the problem?

@fazanan

**Comment by smv2001ua** [comment]
Instead of 
`
super.addItem("Clieant A", "Clieant A");
`

try
```
super.addItem({
  id: "Clieant A",
  text: "Clieant A",
  source: null,
  disabled: false
});
```
