### ISSUE TITLE
Q.serviceRequest List: get response

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#753]
Dear @volkanceylan,
I have some problem to properly use the Q.serviceRequest method.
I'm trying to create a custom editor with an overriden getItems() method:

    namespace x.y {
    
        @Serenity.Decorators.registerEditor()
        export class OwnerEditor extends Serenity.LookupEditorBase<Administration.UserRow, any> {
    
            constructor(hidden: JQuery) {
                super(hidden);
            }
    
            protected getLookupKey() {
                return 'Administration.User';
            }
    
            protected getItems(lookup: Q.Lookup<Administration.UserRow>) {
                var userSupportGroups: Administration.UserSupportGroupListResponse;
                Q.serviceRequest(Administration.UserSupportGroupService.Methods.List, { UserID: Authorization.userDefinition.UserId }, (response) => {
                    userSupportGroups = response;
                });
                return super.getItems(lookup).filter(__TBD__);
            }
        }
    }

Server side it's working fine (I got the response with my support groups entities), but typescript side I'm doing some kind of mistake...I mean the "userSupportGroups" variable is always undefined...
In the previous code, how to properly retrieve the response of the list servicerequest?

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Service calls are async by default, it won't work this way, use last parameter to set it to sync { async: false }

**Comment by marcobisio** [comment]
I didn't know...thank you very much!
Bye

**Comment by marcobisio** [comment]
One more question...there is a way to pass a parameter to the customeditor?
I need to know if the editor is readonly or not, but when I use the hasClass() method in the getItems() it's to early...

Thank you very much

**Comment by volkanceylan** [comment]
You may check when readonly property change (implementing ISetReadOnly) and call UpdateItems to repopulate records.

**Comment by volkanceylan** [comment]
Also this.options.readOnly should be true

**Comment by marcobisio** [comment]
Thank you very much @volkanceylan...I'll try!

Have a good evening
Bye
