### ISSUE TITLE
Getting Error: At least one object must implement IComparable.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#754]
I am getting following error in saving dialog which have memory grid.
**Getting Error: At least one object must implement IComparable.**
The dialog of memory grid contains dropdown with multiple value true.

Steps - 
1. Open dialog which already have data in memory grid.
2. Do nothing with memory grid, but modify any field on dailog.
3. Click on Save button, Error occured.

Temporary Workaround - 
If click on row inside memory grid and save them with out any changes for all rows inside memory grid then error does not occurred.

Please help to resolve this issue.

**Comment by ramveersgh** [comment]
Error is coming due to field CheckChangesOnUpdate inside DetailListHandler.cs for checking field.IndexCompare(old, row).

**Comment by volkanceylan** [comment]
Turn off CheckChangesOnUpdate of MasterDetailRelation

**Comment by ramveersgh** [comment]
Thank you very much for your quick response.......
Just one more help... How to override default Take (No Of Records to show in grid) to 20. Currently it is 100.

**Comment by volkanceylan** [comment]
You may override getViewOptions and set RowsPerPage

**Comment by ramveersgh** [comment]
@volkanceylan 
Hey,
Is this issue resolved in current latest version?
I am using v2.2.1.0 which does not have this fix.

**Comment by wirble** [comment]
I am getting this error when I have two levels of master detail relation also and had to use the CheckChangesOnUpdate 

Master>Detail (master)> Detail
