### ISSUE TITLE
Is there a tutorial for setting up Serenity on iis 8.5.9?

### ISSUE THREAD

**Issue by SuckyCoder** [volkanceylan/Serenity#755]
Hello,
I am still really new to this project and would really like to get it running. It seems like one of those projects which are really fun to trying to understand and use.

So here the problem...
I've made a fresh project (v2.2.1.1) and it starts just fine on my development workstation (the one with VS2015 and express version of IIS).

However getting published version to work on my *webserver is really hard and i dont really understand the error message (see below). 

*Windows server 2012 with iis 8.5.9 and  .net 4.5 enabled
![image](https://cloud.githubusercontent.com/assets/19668529/15704783/75418cca-27ec-11e6-9853-7cc7614f5f42.png)

I have checked: 
- connection strings
- existance of .cshtml-files
- folder access

May I provide some additional information to get it running?

Thanks in advance.

**Comment by volkanceylan** [comment]
You probably dont have views under modules directory.

**Comment by volkanceylan** [comment]
Or the layouts under views

**Comment by SuckyCoder** [comment]
It seems like views are still there.
Project Account-files:
![image](https://cloud.githubusercontent.com/assets/19668529/15708187/6d53795e-27fd-11e6-80de-ca0580a512e0.png)

Published Account-files:
![image](https://cloud.githubusercontent.com/assets/19668529/15708506/1f679386-27ff-11e6-86d4-d2b0e02dd9f5.png)

Views are identical in both project and published version:
![image](https://cloud.githubusercontent.com/assets/19668529/15708656/0c255eec-2800-11e6-9e6d-c09c0d876e63.png)

I have copied whole project to my win2012 server and it gives me the same error. So it is most likely something with my server. What could it be? IIS express which is used by Visual Studio runs it perfectly. Serenity 1.8 worked perfectly on 2012 server.
Is it possible that I am missing something on my web server? What are the requirement to run serenity? IIS with .net 4.5 should be enough, right?

Thanks for your fast replay.

**Comment by volkanceylan** [comment]
There is no special steps, IIS with ASP.NET 4.5 is enough, application pool integrated thats all. Try reinstalling IIS/ASP.NET

**Comment by volkanceylan** [comment]
Where did you deploy files? IIS might not be able to read files. Try granting IIS_IUSRS group access.

**Comment by jsbUSMC** [comment]
I used the WebDeploy publish from VS to package the app, create the zip and push it to the server. Have you used MSBuild? There are default build configs, development and release, I think. You can define your own. Also like @volkanceylan said, make sure that IIS_IUSRS has the correct permissions in IIS Manager.

**Comment by SuckyCoder** [comment]
Hello!

I've added "IIS_IUSRS"-group to my "inetpub"-folder and it works now!
Sorry to bother you about something so simple.

Thanks everyone for your help and have a nice day.
