### ISSUE TITLE
Random Idea - Feature generators

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#758]
I just wanted to put this out there as I think it may be a decent idea to consider. 

As I continue to review the code from the base Serenity model and pick and choose features from it that I can make use of and then attempt to implement, I find myself wondering if there may not be a easier way to transition features already implemented in the sample, onto a custom template. 

Examples: 
Easier: 
The simple NotesBehaviour feature on the Northwind Customer table dialog is something many can find useful and if built as a secondaryAttribute, would be much easier to implement. Then it can be added with simplicity to tables as needed. 

More Difficult:
-Multitenancy (I know it's not one of the proffered features but it was requested often enough to make it into the guide.) If we had a codeGenerator clone that would, if selected, add Multitenancy changes and features to the Serenity core and then the leftover changes would be minimal such as adding IMultiTenantRow to xyzRow.cs files and the xyzRepository.cs authorization check. 

This could make building systems with tested features more streamline plus easier to troubleshoot since it'd be more consistent as more people adopt Serenity as a base. 

I saw someone earlier ask about adding a wizard and that is what got me thinking about this. Not everyone needs Multitenancy, server tools, CRMS, etc, but if it's compartmentalized it's easier to pick and implement features that make sense for the need of the build but wont bog down with any unnecessary features. 

I hope i'm not speaking out of line on this, just wanted to get your thoughts on the matter as I know there has been discussions of new features to be added as serenity continues to grow. 

Some other thoughts that came to mind that could be auto-template through a generator: 
-Widget Implementations (Such as the once from AdminLTE
-Mail Server Mapping
-the Items within the Basic Samples such as Grouping
- One-Click Northwind and Samples removal. 
- "Usual Suspects" design that may be ready to implement with empty template tables and features such as a: 
           + Customer Table
           + Contacts Table 
           + Employee Column 
           + 10 Column Data Table with Excel and PDF Exporter  
           + Basic Management Tables (Languages, Translations, etc.) 
I actually, keep a copy of serenity up to date but with the Sample and Northwind data removed in the event I need to do a quick re-build. I then only need to pull in my custom tables.

**Comment by volkanceylan** [comment]
I'm considering some such architecture, but its not trivial. Users should be able to update such features, while having ability to modify some parts. Offering customizability and easy updates is not so easy. I'm moving stabilized features into Serenity itself. Maybe ill add more optional packages like Serenity.App.TranslationUI etc. One might use it or choose to write his own taking source as sample. Plugin system is possible but Serene is not a product, its a code sample. Offering plugins like CMS or e-commerce systems doesnt make much sense. Also writing such packages shouldnt make it harder for me to add new features or avoid breaking compability. Its already hard enough.

**Comment by sayuga** [comment]
I don't disagree. I do like to be able to get in deep. It's good practice to know what it is you're working with inside and out if there is to be an end product design. Also, I do understand that Serenity is not a end product but a starting point. 

I'm more leaning towards the notion that I see a lot of repeat requests on the issues board as well as I've found myself making pieces of the puzzle, if you will, to make it easier to upkeep.

I know it's not a simple matter and honestly, I've fallen in love with serenity. I am not the only one from what I've seen, thus I would love to see it continue to grow. That being said, there are so many people working with serenity now, that I figured a "add-ons" library of sorts for the many puzzle pieces everyone goes making and is willing to share, would be nice. Mostly because it'll greatly reduce time spend troubleshooting the same issue multiple times plus it allows for documentation and analysis of these sections in a smaller, more, digestible form. 

I've actually been studying file by file in a second clean copy of serenity just testing out plausible features that I hope to at some point bring in for everyone to use.

**Comment by volkanceylan** [comment]
Thanks, maybe after figuring out how to handle this mechanism, i'll open a plugin / extension / sample repository, e.g. marketplace for Serenity

**Comment by FARIVER** [comment]
https://github.com/volkanceylan/Serenity-Tutorials/tree/master/MultiTenancy

I can not find!

**Comment by FARIVER** [comment]
MultiTenancy.Script 

This is where!

**Comment by FARIVER** [comment]
I can not operate according to the multi-user guide function, is not what I lack! (serentiy for VS)
