### ISSUE TITLE
Bug - Northwind Orders Dialog - InvoicePDF

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#759]
I'm running a clean, unedited, run of current serenity build and I'm getting a break when attempting to render a pdf invoice from within the Northwind Orders Dialog. 

{"Can't find wkhtmltopdf.exe which is required for PDF generation.\nPlease download a stable version from http://wkhtmltopdf.org/downloads.html\n and place it under directory 'D:\\VisualStudio2015\\Projects\\Serenity1\\Serenity1\\Serenity1.Web\\App_Data\\Reporting'."}

**Comment by volkanceylan** [comment]
Do as message says. Wkhtml is not integrated.

**Comment by sayuga** [comment]
Oh, for some reason I thought it had been integrated as part of the pdfExportHelper. I should have checked more thoroughly. I apologize.

**Comment by volkanceylan** [comment]
NP, may be i should state this in message more clearly. WKHTML has different licence and 20mb+ so i don't want to include in template, would increase download size
