### ISSUE TITLE
Cascade Look Up

### ISSUE THREAD

**Issue by driveromora** [volkanceylan/Serenity#760]
Hi guy,

can you help me?.

I try to put a look up cascade with two levels, this is my code:
****************************************************************************************************************************
[DisplayName("Móduloss"), Column("MACMOD_CODIGO_K"), PrimaryKey, ForeignKey("[MACUS].[MAC_MODULO]", "MACMOD_CODIGO_K"), LeftJoin("a")]
        [LookupEditor(typeof(Entities.ModuloRow))]
        public Int32? MacmodCodigoK
        {
            get { return Fields.MacmodCodigoK[this]; }
            set { Fields.MacmodCodigoK[this] = value; }
        }

        [DisplayName("Sub Móduloss"), Column("MACSMO_CODIGO_K"), PrimaryKey, ForeignKey("[MACUS].[MAC_SUBMODULO]", "MACSMO_CODIGO_K"), LeftJoin("e")]
        [LookupEditor(typeof(Entities.SubModulosRow), CascadeField = nameof(SubModulosRow.MacmodCodigoK), CascadeFrom = nameof(MacmodCodigoK))]

        public Int32? MacsmoCodigoK
        {
            get { return Fields.MacsmoCodigoK[this]; }
            set { Fields.MacsmoCodigoK[this] = value; }
        }

******************************************************************************************************************

and this is the code for the modulo

[DisplayName("Modulo"), Column("MACMOD_CODIGO_K"), NotNull, ForeignKey("[MACUS].[MAC_MODULO]", "MACMOD_CODIGO_K"), LeftJoin("jMacmodCodigoK"), LookupInclude]
        [LookupEditor("MACUS.Modulo", InplaceAdd = true)]

        public Int32? MacmodCodigoK
        {
            get { return Fields.MacmodCodigoK[this]; }
            set { Fields.MacmodCodigoK[this] = value; }
        }
**************************************************************************************************************

but the lookup of SubModulo doesnt works.

regards

**Comment by volkanceylan** [comment]
Please share a gist of SubModuloRow

**Comment by PanChenhao** [comment]
i have the same problem
