### ISSUE TITLE
Windows authentication

### ISSUE THREAD

**Issue by totacz** [volkanceylan/Serenity#762]
It is possible to switch Windows authentication for automatic login?
And manualy inserting security roles from AD to Serenity Administration role?
Authorization  manage by Serenity users, AD users and AD security group.

Thank You

ToTa.

**Comment by volkanceylan** [comment]
I don't know how Windows Auth automatic login works. Serenity reads user from HttpContext so if you can find some document on how to enable it Serenity will also be able to work with it.

I don't have experience with others.
