### ISSUE TITLE
How to show lookup without caching.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#763]
I have some other service which import data in database and i need to show that data in lookup.
Due to caching, lookup is not able to show the new data imported in database. 

So i want to use lookup without caching. I tried to remove TwoLevelCaching attribute but that also not work.
Do i need to do similar to following thread?
https://github.com/volkanceylan/Serenity/issues/375

In this thread you mentioned that there may be a new type of ServiceLookupEditor in serenity for ajax based lookup.

Please confirm if i need to follow above link to get this functionality or there is anything in serenity for this?

**Comment by volkanceylan** [comment]
Create a custom lookup script with Timeout negative value

**Comment by ramveersgh** [comment]
I am sorry.. but could not get.
How to create that?

**Comment by ramveersgh** [comment]
@volkanceylan 
Please help me on this... What should i do..

**Comment by volkanceylan** [comment]
See multi-tenant guide for custom lookup scripts

**Comment by ramveersgh** [comment]
Ok, Thanks for point me.
I have created Custom Lookup script by inhering from RowLookupScript and Set `Expiration = TimeSpan.FromDays(-1);` in constructor.

Now i want to create a custom editor inheriting from LookupEditorBase so that i can override CascadeItems to show all Item by defualt.  But i am not able to create CustomEditor becasue there is no class generated for Custom Lookup script.
I also tried to transform and build many times.
_ Just to inform you that still i am using saltarelle for my old code._

Here is screen shot to illustrate the problem -
![customlookup](https://cloud.githubusercontent.com/assets/2145218/15775900/337bf296-29a2-11e6-87d9-0246b44701da.png)

**Comment by volkanceylan** [comment]
Your editor wont change, just its lookup key change.

**Comment by ramveersgh** [comment]
Thanks for your help and guidance..
Its working..

**Comment by pkupriec** [comment]
Maybe it could help somebody. In current version it's possible to set expiration period for lookup cache directly in LookupScript attribute of row class:
`[LookupScript ("YourLookupScript", Expiration = -1)]// in seconds`
