### ISSUE TITLE
update orderdetail issue

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#764]
when i save the order, the orderdetail table said orderid is null, my app like the serene, i used the serenity firstly. thanks!

**Comment by mrajalko** [comment]
change orderdetaildialog.ts file as explained in sample template.

**Comment by cp1319421** [comment]
I meaning the db table update failed, like below:
不能将值 NULL 插入列 'InOrderID'，表 'TestManageSystem_TMS.dbo.InOrderDetail'；列不允许有 Null 值。INSERT 失败。

**Comment by billyxing** [comment]
错误信息说的很明白，你要插入的记录里，没有给InOrderId赋值。你可以参考moviedb的教程，如果还有问题，就把相关代码贴出来吧

**Comment by cp1319421** [comment]
@billyxing 是参考moviedb来的，订单页中添加详细信息，然后保存时订单页更新关联详细信息表时失败，使用如下，跟踪实例调用public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)时OrderID也为空，是不是还有调用别的？

关联如下
[DisplayName("Details"), MasterDetailRelation(foreignKey: "InOrderId"), ClientSide]
        public List<InOrderDetailRow> DetailList
        {
            get { return Fields.DetailList[this]; }
            set { Fields.DetailList[this] = value; }
        }

第一次用这个，请多指教，谢谢！

**Comment by billyxing** [comment]
@cp1319421 不需要调用别的。你的外键是不是写错了啊，你的代码里写的InOrderId，错误信息里提示的InOrderID

**Comment by cp1319421** [comment]
更改了也不行，row.cs里面定义的名字要和数据库的字段一样吗，自动生成的脚本改变了大小写，保存数据库的时候后台master没有传InOrderID给details

**Comment by cp1319421** [comment]
the master/details not useful for a non int field？

**Comment by cp1319421** [comment]
inorder表里面的InOrderID是用触发生成的，会影响到inorderdetail表的更新吗？

**Comment by billyxing** [comment]
@cp1319421 我qq5213388，回头qq上说吧

**Comment by volkanceylan** [comment]
If your InOrderID in master table is trigger generated, Serenity can't know what is its value after insert for master record, so it can't set it in detail records. You need to use an identity column if you want to use MasterDetailRelation. Otherwise, you need to use manual methods. I don't know how you can get ID of inserted record if it's not an identity.
