### ISSUE TITLE
Get attachment file name

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#766]
Hi Jaiq,

Has serenity framework have a function to get only filename in attachment file column?

[{"Filename":"SupportingFile/00000/00000087_i7gnz3ejkptps.pdf","OriginalName":"123pdf"},{"Filename":"SupportingFile/0000/00000087_6z6m5eqvrtyh2.jpg","OriginalName":"11888089_894988523883989_4847519518939692811_n.jpg"}]

Regards

**Comment by volkanceylan** [comment]
Nope. Its json, just deserialize and read.
