### ISSUE TITLE
How to get userDefinition from client side?

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#767]
`public class UserDefinition : IUserDefinition
    {
        public string Id { get { return UserId.ToInvariant(); } }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public short IsActive { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string Source { get; set; }
        public int storageType { get; set; }
        public DateTime? UpdateDate { get; set; }
        public DateTime? LastDirectoryUpdate { get; set; }
    }`
I want to get such information of current user from client side, is it possible? and how to do it.

**Comment by volkanceylan** [comment]
Did you see ScriptUserDefinition?

**Comment by PanChenhao** [comment]
Thanks for you remind. 

`public class ScriptUserDefinition
    {
        public String Username { get; set; }
        public String DisplayName { get; set; }
        public Int32 storageType { get; set; }
        public Dictionary<string, bool> Permissions { get; set; }
    }`

Then i can get it by use
`var userdata = Q.getRemoteData('UserData');`
