### ISSUE TITLE
How to remove edit link from gird dynamically?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#768]
I am using memory grid on the dialog and i want to remove edit link from the memory grid to restrict user to modify the details.
How to do it?

**Comment by PanChenhao** [comment]
have the same problem

**Comment by volkanceylan** [comment]
Try writing a custom formatter

**Comment by ramveersgh** [comment]
Thanks for reply..
Here is my scenario, I don't want to allow editing if status is approved. Here is the screen shot -
![stopediting](https://cloud.githubusercontent.com/assets/2145218/15851442/5d8b1c68-2cba-11e6-83c9-a5df1d02e351.png)

I tried to override OnClick even on grid but i am not able to access the status of voucher from dialog inside this event. 
**How i can access VoucherStatus from the dialog to grid?**
```
        protected override void OnClick(jQueryEvent e, int row, int cell)
        {
            //How to get VoucherStatus from the dialog???
            if (VoucherStatus == ApprovalStatus.Approved)
                Q.Alert("I Said Not allowed");
            else
                base.OnClick(e, row, cell);
        }
```

I am sorry but i did not tried the custom formatter yet, Do you think that i can meet my requirement with custom formatter? I want to add this validation based on the dialog field.

**Comment by volkanceylan** [comment]
You should add a status / readonly property to your grid. Dialog should set in AfterLoadEntity. In grid, override EditItem method, and don't call base.EditItem if readonly is true.

**Comment by ramveersgh** [comment]
Thanks! Its working now with the suggestions.
