### ISSUE TITLE
masterdetailrelation don't work

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#769]
I create a order table and a order detail table, use MasterdetailRelation(foreignKey: "Order ID")to save detail table when I save order table, but it said can't insert a NULL to OrderID field in detail table, and both table all have OrderID field, what's wrong about this?

**Comment by volkanceylan** [comment]
space "Order ID"

**Comment by cp1319421** [comment]
Sorry, there is a mistake in writing, the code in my project is "OrderID", and it don't work !

**Comment by volkanceylan** [comment]
It does work with Order/Detail in Northwind, so take a look at code and find differences with yours.
