### ISSUE TITLE
how to print a database row

### ISSUE THREAD

**Issue by JesseBn** [volkanceylan/Serenity#77]
I am trying create a print out of a database row. I have added a button to the dialog box but I cannot send the row data to the html page which will be printed. I am assuming I need to use PostToUrl but I am not sure how to use the params property.
 the code I have is: 

        protected override List<ToolButton> GetToolbarButtons()
        {
            var buttons = base.GetToolbarButtons();
            buttons.Add(new ToolButton
            {
                Title = Q.Text("Print"),
                CssClass = "print-preview-button",
                OnClick = delegate
                {
                    PostToUrlOptions Options = new PostToUrlOptions();
                    Options.Url = "~/Database/Weighing/WeighingReciept";
                    Options.Params = WeighingRow.IdProperty;
                    //WindowInstance reciept = Window.Open(Q.ResolveUrl("~/Database/Weighing/WeighingReciept"));
                    Q.PostToUrl(Options);
                }
            });

            return buttons;
        }

**Comment by volkanceylan** [comment]
Params property takes a anonymous object or js dictionary with keys and their values to post to the target page.

**Comment by JesseBn** [comment]
Thanks, that worked.
