### ISSUE TITLE
HELP! Serenity 

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#770]
Until yesterday my project work. Now the serenity name is not found in typescript.
Can help me?

![cattura](https://cloud.githubusercontent.com/assets/16304015/15817498/8af28a0c-2bd8-11e6-9943-b093170a940e.PNG)

**Comment by volkanceylan** [comment]
Nobody touched your project, so you should find out what changed from yesterday.

**Comment by Estrusco** [comment]
Yes, I know, but I have not done changes. Then now I realized that the Scripts\serenity dir is empty. 
I copied the files from serene and is ok.
But I really not deleted those files...
The computer science mysteries :D

![cattura](https://cloud.githubusercontent.com/assets/16304015/15818604/ab3d2bcc-2bde-11e6-881d-85f34db55972.PNG)
