### ISSUE TITLE
Login Screen, Persistent Storage clash - Issues after last update

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#772]
I just did a package update and it seems It's not playing nice with persistent storage. If I have persistent storage set I get the following breaks at the login screen plus login input boxes are not present: 

ScriptInitialization.ts:5Uncaught TypeError: FMCDashboardv3.UserLocalStorage is not a constructor
LoginPanel.ts:6Uncaught TypeError: Cannot read property 'formKey' of undefined

I am able to login if I use the console but anything affected by persistent storage shows the same error. 

I commented out persistent storage and the error disappears plus the older, pre-update version runs persistent storage fine. This is how I have persistent storage set up. I am running into this error on 2.2.2:

namespace FMCDashboardv3.ScriptInitialization {
    Q.Config.responsiveDialogs = true;
    Q.Config.rootNamespaces.push('FMCDashboardv3');

    Serenity.DataGrid.defaultPersistanceStorage = new UserLocalStorage();

}

namespace FMCDashboardv3 {

    export class UserLocalStorage implements Serenity.SettingStorage {
        getItem(key: string): string {
            return window.localStorage.getItem(
                Authorization.userDefinition.Username + ":" + key);
        }

        setItem(key: string, value: string): void {
            window.localStorage.setItem(
                Authorization.userDefinition.Username + ":" + key, value);
        }
    }
}

**Comment by volkanceylan** [comment]
If you don't put ///<references , you'll always have these errors.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/776

Same issue
