### ISSUE TITLE
Different toolbar button in dialog AfterLoadEntity

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#774]
Hi Jaiq,

I have an entity dialog, in dialog.ts with default toolbar button when new or editing as below

![ant1](https://cloud.githubusercontent.com/assets/6382278/15848611/19ac59e6-2cb8-11e6-8b1d-2015ee489fd0.PNG)

Now, i added  afterLoadEntity function in that dialog.ts my dialog has changed to be

![ant2](https://cloud.githubusercontent.com/assets/6382278/15848517/9ca04fa2-2cb7-11e6-9e74-b377fca68160.PNG)

        public afterLoadEntity(): void
        {
            if (this.isEditMode) {
                if (this.entity.Eqp == 2) {
                    jQuery(".field.A").hide();
                    jQuery(".field.V").hide();
                }
            }
        }

Any suggestion? I don't want my dialog changes.

Thanks

**Comment by volkanceylan** [comment]
Don't forget to call super.afterLoadEntity()

**Comment by fazanan** [comment]
It works, thank you Jaiq.
