### ISSUE TITLE
.Identity() missing in UserID definition in [Migration(20141103140000)]

### ISSUE THREAD

**Issue by LuboSta** [volkanceylan/Serenity#775]
Hello , I used VS2015 to create Serenity project.
And had to add .Idenity() into [Migration(20141103140000)] otherwise insert of first userID failed ( no auto increment of ID so UserID was null). Could be that Oracle need similar modification

	addUsersColumns(IfDatabase(Utils.AllExceptOracle)
		.Create.Table("Users")
	          .WithColumn("UserId").AsInt32().PrimaryKey().NotNullable()**.Identity()**);

**Comment by volkanceylan** [comment]
It's fixed in 2.2.2, Oracle doesn't support identity.

**Comment by volkanceylan** [comment]
2.2.2.1 actually
