### ISSUE TITLE
Persisting Settings to Database (User Preferences Table)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#776]
Dear @volkanceylan,
I'm trying to enable the user settings persist feature with the dedicated db table (following your instructions), but I got an error:

![image](https://cloud.githubusercontent.com/assets/17425690/15856993/3c026d5e-2cb9-11e6-8099-7f298cd75306.png)

I'm using the version 2.2.2...any idea?
Thank you very much
Bye

**Comment by volkanceylan** [comment]
Try putting //references to UserPreferenceStorage.ts

**Comment by marcobisio** [comment]
You're right...thank you very much!

Just to clarify (not to you @volkanceylan, but for the community!), the following instruction:

    /// <reference path="../Common/UserPreference/UserPreferenceStorage.ts" />

must be put in the ScriptInitialization.ts file.

Thanks again
Bye

**Comment by volkanceylan** [comment]
Think i should add that to guide, thanks.
