### ISSUE TITLE
2 tables in the same grid

### ISSUE THREAD

**Issue by mindfreak93** [volkanceylan/Serenity#777]
Hi!
I searched on this section, but i don't find a solution for this type of problem.
I have 2 tables which are connected by the ID(TbTask is Primary and TbTask_Details is Foreign).
This is an example of the schema:
![image](https://cloud.githubusercontent.com/assets/19779762/15861281/c0516a5e-2cd4-11e6-9876-be4d5edfa2cc.png)
I want to display both tables in the same grid like this:
![image](https://cloud.githubusercontent.com/assets/19779762/15861413/f98d14c6-2cd4-11e6-9c88-45acee390121.png)
Is this possible at this moment?
I tried to use the tutorial, but is not giving me any good examples for this.
I followed the tutorial like you added the genre, but now i am stacked.
I want the insert to be done from one popup only.
This is a part of the code in the TbTaskRow which i modified without any success:
```
        [DisplayName("ID"), ForeignKey("dbo.TbTask_Details", "ID"), LeftJoin("g")]
        public Int32 ID
        {
            get { return (Int32)Fields.TaskId[this]; }
            set { Fields.TaskId[this] = value; }
        }
        [DisplayName("Action"),DatabaseAlias("g"), Column("Action") ]
        public String Action
        {
            get { return Fields.Action[this]; }
            set { Fields.Action[this] = value; }
        }
```
I am still a beginner in C#, so I am pretty sure that is something which i missed and the solution is pretty simple.
Thank you for your time!

**Comment by volkanceylan** [comment]
See mapping guide for joins. Where did you get DatabaseAlias etc??

You need to show task details in a grid, you can't both. It is not supported.

**Comment by mindfreak93** [comment]
Thank you for the answer. I found another way to do it, but i have a problem with insertion.
I created a view with those tables and in this way the gird will be updated with all the necessary information. The think is that the insert command can not be done as it is in the current configuration made by sergen. Sergen is trying to add files into the view directly which is not possible, because the view contain more than one table.
```
            public RowFields() : base("[dbo].[View]")
            {
                LocalTextPrefix = "Project.ViewTask";
            }
```
I studied the entire code today and i see that the database is selected from the RowFields class ctor:
```
            public RowFields() : base("[dbo].[TbTask_Details]")
            {
                LocalTextPrefix = "Project.ViewTask";
            }
```
The Code seems to work in this case, but is not good because is using only one Table and is not able to find some fields in that Database.
I want to know if there is any possibilities to select only some fields that i will add in one database and the other fields in the other database or another way to achieve that.
Serenity is a great powerful tool and i would like to use it forward. Thank you for your time!

**Comment by volkanceylan** [comment]
Why you needed to declare a view? Serenity rows can do almost anything a view can do. Anyway, if you insist, you may open another dialog type, e.g. original table, for your view grid. getDialogType method is the one you set it.

**Comment by mindfreak93** [comment]
Thank you for your help and patience.
I worked on it using your guidance and now it show me something like I wanted to do.
Maybe i will need your guidance again, but i hope that i will not need any help in the future.:)
You've been very helpful. Thank you again!
 Have a nice day!
