### ISSUE TITLE
Two entities forms in tabbed pane

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#778]
Good morning!

There is a way to insert, in a tabbed pane, two "form" from two distinct entities (in two separate row classes)?

I would like to manage these two entities in tab format.
I know there are the Category link, but even with the categories, I can manage two distinct entities (in two separate row classes)?

![example](https://cloud.githubusercontent.com/assets/16304015/15886322/b67cf6c8-2d5c-11e6-9590-2fbb74036591.png)

Thank you for all!

**Comment by volkanceylan** [comment]
This is called extension table. You may try using an updatable view.

**Comment by Estrusco** [comment]
Thank you @volkanceylan  
Please, can you indicate me an initial approach for updatable view? I have implemented an entity row with view fields from this extension table, but at moment of save the view table is not update (using a single form with Categories). 
I have modified MySaveHandler overraiding AfterSave() in this manner, but there is a better way?


My Row
```cs
    [LeftJoin("jExtTable", "[dbo].[Base.ExtTable]", "T0.[Key1] = jExtTable.[Key1] and T0.[Key2] = jExtTable.[Key2]")]
    [LeftJoin("jExtTable2", "[dbo].[Base.ExtTable2]", "T0.[Key1] = jExtTable2.[Key1] and T0.[Key2] = jExtTable2.[Key2]")]
    public sealed class Base_MainTableRow : Row, IIdRow, INameRow
    {
      fields...
       [...]

#region ViewFiels
        [Updatable, Expression("jExtTable.[Field1]"), MinSelectLevel(SelectLevel.Details)]
        public Int64? jExtTableField1
        {
            get { return Fields.jExtTableField1[this]; }
            set { Fields.jExtTableField1[this] = value; }
        }

       [...]
#endregion ViewFiels
```

 My MySaveHandler in MainTableRepository
 
```cs
   if (Row != null)
   {
      var viewTableFields = Entities.Base_ExtTableRow.Fields;
      var oldList = IsCreate ? null : Connection.List<Entities.Base_ExtTableRow>(
             viewTableFields.Key1 == this.Row.Key1.Value && viewTableFields.Key2 == this.Row.Key2.Value).First();

       var updList = oldList != null ? oldList : new Entities.Base_ExtTableRow() { Key1 = Row.Key1, Key2 = Row.Key2 };
       
        updList.Field1 = Row.jExtTableField1;
        updList.Field2 = Row.jExtTableField2; 
        updList.Field3 = Row.jExtTableField3;
        updList.Field4 = Row.jExtTableField4;
        [etc.]

        var saveRequset = new SaveRequest<Entities.Base_ExtTableRow>();
        saveRequset .Entity = updL;
        saveRequset .EntityId = updL.Id;
        new Base_ExtTableRepository().Update(this.UnitOfWork, saveRequset );
```

**Comment by volkanceylan** [comment]
Why do you have an oldList here, isn't extension table 1-1. Use TryFirst

**Comment by Estrusco** [comment]
Ok, thanks for the correction.
After this, there is an automatic way to associate or save the join view fields to the original table? I have to use the Reflection?
Or my method is correct?

Thank you

**Comment by volkanceylan** [comment]
You might make use of FindField.

**Comment by Estrusco** [comment]
Thank you very much @volkanceylan . 

I try :)
