### ISSUE TITLE
Beyond standard apps - Integrating CMS/DMS into Serenity

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#779]
Hi,
This is more of a question than anything else. I have a serenity site up and running, I am happily developing specific applications in it. Core business based applications are a breeze. But I am looking to extend Serenity into some CMS/DMS functionality. I have been looking around but most CMS is bloated framework stuff that doesn't integrate well. What I am really looking for is an API I can use inside Serenity to do the DMS/CMS so that I can develop my own interfaces for it.

For example using Serenity as the host for CMS for an extranet. This will mean that I can use serenity for permissions and whatnot, and integrate any data from it.

I guess I could just start from scratch but I was wondering if anyone had used anything to fulfill this already?

I have looked at things like DNN, Umbraco, Orchard, OpenKN, SenseNet but they are all hard to integrate into Serenity.

**Comment by volkanceylan** [comment]
An older version of Serenity had some kind of simple CMS. I'm not sure how it compared to others you listed. We had several public B2C sites, that also run on Serenity but didn't have administrative interface of their own for data. Their data and content is fed from another Serenity site behind in intranet.
