### ISSUE TITLE
Add MySQL dialect and how-to guide

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#78]

**Comment by volkanceylan** [comment]
Aye aye, sir ;)

**Comment by volkanceylan** [comment]
1.8.13 supports MySql,

See https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_work_with_other_database_types.html

**Comment by china0zzl** [comment]
All the pages from gitbooks not founded.[https://volkanceylan.gitbooks.io](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_work_with_other_database_types.html)
