### ISSUE TITLE
I am trying to Override the addButtonClick() 

### ISSUE THREAD

**Issue by swordz36** [volkanceylan/Serenity#780]
I see that in [Object]Grid.cs I can override the AddButtonClick to call a  separate Controller action when the add button is clicked. I have another view that I created a different from the standard serenity dialog. Is this even possible or will I be locked into using the Entity Dialog?

**Comment by volkanceylan** [comment]
You can redirect to your page containing your view. Or use javascript to show it in an iframe or div.

**Comment by swordz36** [comment]
I tried this

   var xmlHttp = new XmlHttpRequest();
            xmlHttp.Open("Get", "[CustomUrl]",false);
            xmlHttp.Send();

but it remains on the EntityGrid even though it hits the controller and returns the View for the action

**Comment by swordz36** [comment]
Nevermind I wasn't updating the GridDiv content
