### ISSUE TITLE
setTitle on DataGrid

### ISSUE THREAD

**Issue by geniewithsolder** [volkanceylan/Serenity#781]
in Serenity.Script.UI.js the setTitle function does not seem to allow the datagrid title to be updated once it has initially been set.

I have modified my version as shown to address this ( can't work out how to format it correctly):

`\\\.........`
`else`
`{`
      `    this.titleDiv.children().text(value);`
`}`
`this.layout();`

Is this a valid change?

**Comment by volkanceylan** [comment]
No, its a little bug, set it to null then set again. Will be fixed in next version.

**Comment by volkanceylan** [comment]
Fixed in 2.2.3
