### ISSUE TITLE
App can't run on local IIS

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#783]
I build a project base on serene, and it can run on VS2015 iis express, but i try to use local iis, the page is empty, check with chrome, find below error, wath's wrong?

LocalText.Site.zh-CN.Public.js:1 Uncaught ReferenceError: Q is not defined
ColumnsBundle.js:1 Uncaught ReferenceError: Q is not defined
FormBundle.js:1 Uncaught ReferenceError: Q is not defined
TemplateBundle.js:1 Uncaught ReferenceError: Q is not defined
RegisteredScripts.js:1 Uncaught ReferenceError: Q is not defined
Login:129 Uncaught ReferenceError: jQuery is not defined

**Comment by volkanceylan** [comment]
See troubleshooting. This is reported about Nth time.
