### ISSUE TITLE
Is there any configuration to remove schema prefix when code is generated.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#784]
public partial class RowFields : NRowFields
        {
            public RowFields()
            : base("[dbo].[UserRole]") // I want to remove these [dbo].
            {
                LocalTextPrefix = "Security.UserRole";
            }
        }
// I want to remove these [dbo].

**Comment by volkanceylan** [comment]
Search replace is an useful tool :)

**Comment by dfaruque** [comment]
I have already done this. but want to know for next time.

I have to generate code from sqlserver but run on oracle.

**Comment by dfaruque** [comment]
Ok. Thank you.

**Comment by volkanceylan** [comment]
As i said its just a search replace i dont think this is required.

**Comment by dfaruque** [comment]
Can you please give me the regular expression for replacing of "[dbo].[Role]" with "Role"?

**Comment by dfaruque** [comment]
I have found 
"\[dbo\].\[([a-zA-Z]+)\]" 
with 
"$1"

**Comment by volkanceylan** [comment]
[dbo].[([a-zA-Z]+)]

You might want to escape "["

\[dbo\]\.\[([a-zA-Z]+)\]
