### ISSUE TITLE
[ReadPermission()] for multiples

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#785]
What is the way to grant read to multiple permissions?
Say for example
```
[ReadPermission("GroupA")]
[ReadPermission("GroupB")]
```
Will create a duplicate entry. It might be because I am sleepy this morning.

**Comment by volkanceylan** [comment]
There is no such thing. Either define a common permission, or implement manual check with Authorization.ValidatePermission etc.

**Comment by solabar** [comment]
Ok that makes sense then. I can do that. Thanks Volkan.
