### ISSUE TITLE
Question regarding Permissions in Permission Dialog

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#786]
If I open the Edit Permission dialog, I see the permissions I have in place as expected (including the ones I have registered specially) What confuses me though is that there are 2 Administration entries One as the root of my Administration sub permissions and a Administration one above it. Is the one that is a root of other Admin permissions just there as a placeholder for the tree start? As in if you grant that it ticks the boxes below it? 
Would the way to clear this up be to create a new Sub Permission called Administration:General and then get rid of the non sub type one? Or would this break everything?

**Comment by volkanceylan** [comment]
You should change "Administration" to something like "Administration:General"

One you see is group ("Administration:"), while one is a permission key ("Administration").

**Comment by solabar** [comment]
Thanks Volkan. I went through and did that. I noticed that there is some variance in the way Permissions are assigned in the standard code. Some use PermissionKeys.<key> and others name key explicitly with "<key>". Might be worth going through the code to make this standard just in case. It's not a functional issue at all and I can understand if you don't feel like doing that :)
