### ISSUE TITLE
QuickFilter; Add Enum for filtering; Enum does not exist on client side

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#787]
Hi all,

I am trying to implement a simple quickfilter in a grid which should provide the two possible values: True or False (1 or 0) and filter on a specific boolean field. 
I have followed the infos in this thread here: https://github.com/volkanceylan/Serenity/issues/45

and I have supposedly reverse-engineered the order grid from the serene example with NorthWind where the quickfilter for ordershippingstate is a very close sample but I have somehow the problem that my enum defined within the Web part does not come over to the script part. --> Of course, I have run the Transform T4 template.

I also have tried the MovieKind enum part from within the Developer guide but I still have the problem that my Server-side defined Enum does not get transported over to the client-side.

**Environment:**
- Custom app based on serenity FW 1.9.13
- T4 transforms done

**Additional info:**
- The javascript console from chrome also confirms that the enum is not found
- there is no file with the enum definition within /Imports/ServiceContracts on the client-side

**Question:**
Is there anything special to be done to register the server-side enum to be transformed over to the client-side?

Server-side definition of the Enum:
```cs
using Serenity.ComponentModel;
using System.ComponentModel;

namespace ClientAndAssetManagement.Clients //Modules.Common.Enums
{
    [EnumKey("Enums.TrueFalse")]
    public enum TrueFalse
    {
        [Description("True")]
        T = 1,
        [Description("False")]
        F = 0
    }
}
```

client-side usage in xyzGrid.cs:
```cs

namespace ClientAndAssetManagement.Clients
{

....

protected override void CreateToolbarExtensions()
{
            base.CreateToolbarExtensions();

   ....

    AddEqualityFilter<EnumEditor>(Fields.UseFMOStagingSolution,
             options: new EnumEditorOptions { EnumKey = "Enums.TrueFalse" });

}

...

}

```

**Comment by volkanceylan** [comment]
Add [ScriptInclude] to enum or use it in a row / form

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks. that was it.

Have a nice evening.

With kind regards,

John

**Comment by JohnRanger** [comment]
Even after 3 years, this feedback is still useful. Had the same problem with a recent TS-based SF project.

Thanks again.

John
