### ISSUE TITLE
Cannot sign value to variable under services in typescript

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#788]
I have this code
![capture4](https://cloud.githubusercontent.com/assets/6382278/15953260/1a541248-2ef3-11e6-93de-e8141f1a6903.PNG)

Why isValidated always return true though it response.entity.length more than 0.

**Comment by volkanceylan** [comment]
Its async

**Comment by fazanan** [comment]
Great, it works

Thanks Jaiq
