### ISSUE TITLE
How to update application with new releases

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#79]
Dear Team,

Thank you very much for fantastic framework for Rapid Application Development

How do i keep track of development with latest Serenity Application Template Updates?

Your help in this regards will be highly appreciated

**Comment by volkanceylan** [comment]
There is some information here

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/updating_serenity_packages.html

Most of the functionality exists in Serenity NuGet packages so updating them should be enough in most cases. There is some sample classes and code in Serene too but they are limited. There is currently no way to update such classes automatically, so you need to follow commits or use a tool like Winmerge. There are some plans to make parts of Serene as nuget packages but its not easy for now.

**Comment by samdubey** [comment]
Thank you Volkanceylan for your help
