### ISSUE TITLE
[Bug] grid "Edit Filter"

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#790]
Dear @volkanceylan,
I think that I have a little bug in the edit filter: with an "OR" search condition the filter values are not displayed

![image](https://cloud.githubusercontent.com/assets/17425690/15963972/3480e614-2f16-11e6-93e2-bf40e481a4ef.png)

while with an "AND" condition it's ok:

![image](https://cloud.githubusercontent.com/assets/17425690/15964045/bdab569a-2f16-11e6-926a-552875ba6cf1.png)

Serenity v2.2.2 here...

P.S. the edit filter dialog in the screenshots was first closed with "OK" button and then reopened in order to show you the issue.

Thank you very much!
Bye

**Comment by volkanceylan** [comment]
I'm aware if this issue. It's not about OR, just a display error when you open second time

**Comment by marcobisio** [comment]
Ah ok...good to know!
I let you know if I find a way to fix such issue...

Thanks!
Bye

**Comment by volkanceylan** [comment]
Fixed in 2.2.4

**Comment by marcobisio** [comment]
Great!!
Thanks
