### ISSUE TITLE
UserDialog.ts

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#791]
Not sure what I did to cause this, but my usedialog.ts file decided to change. This was a breaking change on the user dialog. I rectified the problem by getting userdialog.ts from the source in serene again. But what had happened was certain lines were changed.

For example: this.form.Password.addValidationRule became this.form.Password().addValidationRule
It's almost like it merged itself with the old deprecated version. Any idea why this might have happened?

**Comment by volkanceylan** [comment]
You probably took source from an older commit.

**Comment by solabar** [comment]
Probably. What I have done now I tried to convert over to TS completely. Seems to be ok for the most part but now my .ts files under servertypings.tt are throwing me some errors. Cannot fine name "Serenity" I expect I did something stupid. 

Also as a related note. If I want to get rid of the .Script project as you did do I need to do anything special in the serverTypings?

**Comment by volkanceylan** [comment]
When you delete script project, it will stop generating SS imports, so probably no.
