### ISSUE TITLE
Upgraded project from SFW 1.9.13 to 2.2.2.2; no logon screen

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#792]
Hi JaiQ,

I have upgraded (tried to) my current SFW V1.9.13 based Project to the most current V 2.2.2.2 according to your guidance within the newest serenity dev guide.

The Migration so far worked. I mean by that that only 3 warnings from SlickRemoteview and no Errors are left within Visual Studio.

The Project (script and web) compiles and the web browser is started and points to the Login URL 
but: The Login Screen is completely blank and the following 2 errors are shown in Chrome:

- mscorlib.js?v=HVXVT1tVrBXEMnCn7bC0ww2:304 Uncaught TypeError: Cannot read property '__typeName' of undefined

- Failed to load resource: the Server responded with a Status of 404 --> http://localhost:<some port>/favicon.ico

The second error I think we can ignore but the 1st one I don't have any idea where to search for.

---------------
**Regarding the warnings: **

Update: I have found the fixed Versions of PermissionCheckEditor.cs and TranslationGrid.cs under the Github/Serene Project and going back in history. 

---------------

I ask for your help to get the upgraded project working again.
May I ask you to Point out what has changed from V 1.9.13 when upgrading such a Project to V2.2.2.2 because as I understand you in the dev guide, an existing Project should more or less work after an upgrade and conversion of client side projekt to "server-side" TypeScript is not yet enforced.

Thank you for your help and

With kind regards,

John

**Comment by volkanceylan** [comment]
I don't know. You might have have missed something. Put a breakpoint and see whats that cannot read typeName of undefined comes from.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your feedback. I will then just try to upgrade the versions in smaller steps. Up to 1.9.19 it already fully works and I will see when it brakes.

With kind regards,

John
