### ISSUE TITLE
How to create date and time control in javascript?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#793]
Is it possible to create date with time control in java-script?? For date control i am using following which is working - 
Html -
```
<div class="quick-filter-item">
            <span class="quick-filter-label">Period</span>
            <input type="text" id="DateFrom" name="DateFrom" class="s-DateEditor"  /> 
</div>
```
and Javascript -
```
 $(function () {
        $("#DateFrom").datepicker();
    });
```

What to do to add TimeControl with calendar? I have a simple html page so i need to do it in js only.

Thanks

**Comment by volkanceylan** [comment]
new Serenity.DateTimeEditor($('#Date'), {});

**Comment by PanChenhao** [comment]
I use DateTimeEditor() like `[DisplayName("Require Time"), Column("requireTime"), DateTimeFormatter(DisplayFormat = "yyyy-MM-dd HH:mm"), DateTimeEditor()]` 
it work fine. but an custom request is how to set time options, i want  to get time options from database

**Comment by ramveersgh** [comment]
Thanks for your help.
I used following addon over jquery to have TimeControl inside calendar.
http://trentrichardson.com/examples/timepicker/

@PanChenhao 
I am not using any C# code. I am using it on a simple HTML page with. I think if Field has time then it should display automatically.

**Comment by rolembergfilho** [comment]
@ramveersgh could you post an example of what you done with this time picker?

how to use it in Serenity?
