### ISSUE TITLE
Changes in Slickgrid "environement" from SFW V1.9.20 prevents grid.getData() to return anything

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#794]
Hi JaiQ,

John Ranger here again :-)

I am trying to get the autocolumn resize slickgrid plugin working again after the changes which you have introduced around Slickgrid with SFW 1.9.20.

The reason why the autoresize column plugin does not anymore work is because I don't get anything back within the plugin when I do a:

```js
var bla = grid.getData()
```

The var bla is undefined. 

This was not so in previous SFW versions up to 1.9.19.

Other grid properties I can retrieve at the same time (e.g. grid.getDataLength() gives back the amount of data rows of the current grid page).

It seems for me that this is either a timing issue (e.g. the Data in the new slickgrid implementation gets loaded sometime after the plugin wants already to access the data) or getData() does not work anymore.

I have looked through some of the SG plugins which come standard with SFW but none of them uses the grid.getData() function.

May I ask what (except some added functionality which I have seen in the slick.core and slick.grid js) in general you have changed in the V1.9.20 so I can focus on that?

Hint: I have already tried to use the original slick.core and slick.grid js files from V1.9.19 in V1.9.20 but this didn't restore the autocolumn resize plugin back to work so it must be something deeper (like how SFW calls the slickgrid or loads the data).

**Additional info:** The project has been upgraded to SFW 2.2.2.

Thank you for some insight.

With kind regards,

John

**Comment by volkanceylan** [comment]
SlickGrid.getData() function is there, i didn't change anything.

**Comment by volkanceylan** [comment]
Get latest slickgrid folder from latest Serene, you probably have old/invalid files.

**Comment by JohnRanger** [comment]
Hi JaiQ,

thanks for your feedback. I tried that (from Serene 2.2.3) but with the same result: grid.GetData() results in "undefined". So there were definitely some braking changes within the changes which were introduced with SFW 1.9.20.

The grid.getData() function is there but seems to be broken within the implementation of SFW 1.9.20 and upwards.

To say that you didn't change anything around SlickGrid implementation with 1.9.20 compared to 1.9.19 would be a small understatement... :-)

See your release notes from 1.9.20:
---------------------------
•rewrote slick remote view in typescript
•port extra features from x-slickgrid fork (https://github.com/ddomingues/X-SlickGrid)
•experimental grouping and summaries feature (works client side only, no server support so don't use with paging)
•experimental frozen columns and rows feature
•grouping and summaries in grid sample [Serene]
---------------------------

**Comment by JohnRanger** [comment]
Hi JaiQ,

I have further tested and the situation is like this:
- Up to SFW 1.9.19, grid.getData() returns the correct data within the plugins
- From SFW 1.9.20 and higher, grid.getData() returns undefined
- If I replace the /Scripts/Slickgrid folder in V2.2.3 with the content from working SFW V1.9.19, I get not undefined but a 0 if I do var count = grid.getData().length (instead of the expected number of 100 which I get in V1.9.19).

So it seems that something outside of Slickgrid - which has changed from SFW 1.9.19 to V1.9.20 - is causing the slickgrid.getData() function to behave differently.

But it must be around the slickgrid "sphere".

So my question is now: What has been changed in the SFW 1.9.20 from V1.9.19 with regard of loading the grid data / displaying the grid / timing changes, etc?

Thanks again for your time and some insight there.

With kind regards,

John

**Comment by volkanceylan** [comment]
Open Customers page, open F12 developer tools, type

$('#GridDiv').data()['Serene_Northwind_CustomerGrid'].slickGrid.getData()

It returns an object. So, slickGrid.getData() is certainly there. I'm not sure where you are calling getData(), and for what object. You might be creating plugin at a wrong place, or at a wrong phase of lifetime.
