### ISSUE TITLE
Serenity is undefined

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#795]
@Serenity.Decorators.registerClass() Thowing an error on debug run
Pretty much happens in all the .ts files I created. I am guessing a reference in some code is missing but or the life of me I can't find it.

> Unhandled exception at line 16, column 9 in http://localhost:62269/Scripts/Site/MySite.Web.js?v=THeiYK_K912Mfct3q4-lHQ2
> 
> 0x800a1391 - JavaScript runtime error: 'Serenity' is undefined

Project builds fine, but there when I look at the.ts files in Virtual file view there are some highlighted errors.

**Comment by volkanceylan** [comment]
Make sure Serenity.CoreLib.js is included before Web.js

**Comment by solabar** [comment]
That fixed that error, but I am no getting news ones in CoreLib

Unhandled exception at line 1827, column 9 in http://localhost:62269/Scripts/Serenity/Serenity.CoreLib.js?v=eYyXlBM0RdAjrMJgB46FVQ2

0x800a1391 - JavaScript runtime error: 'ss' is undefined

**Comment by volkanceylan** [comment]
This one is about mscorlib.js.

I don't know how you managed to mix ordering.

Create a new project and compare.

**Comment by solabar** [comment]
No idea either. But I'll get there.

**Comment by solabar** [comment]
Ok I have it working again. I have no real idea how I got it into the state that I did. Probably just something I did when I got rid of the Script project and converted everything to TS. Thanks for your help, and sorry to be a pain at times :D
