### ISSUE TITLE
Compilation Error during build of Serenity-master

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#796]
following error is showing during rebuild of current version (2.2.3) of serenity.

Error		The command "..\tools\node\uglifyjs.cmd bin\Release\Serenity.Script.UI.js -o bin\Release\Serenity.Script.UI.min.js --comments --mangle" exited with code -1073741819.	Serenity.Script.UI	M:\MVC\Lib\Serenity-master\Serenity.Script.UI\Serenity.Script.UI.csproj	227	

Error		The command "M:\MVC\Lib\Serenity-master\Serenity.Web\..\tools\node\lessc.cmd M:\MVC\Lib\Serenity-master\Serenity.Web\style\serenity.less > bin\Release\serenity.css" exited with code -1073741819.	Serenity.Web	M:\MVC\Lib\Serenity-master\Serenity.Web\Serenity.Web.csproj	837

**Comment by volkanceylan** [comment]
See console for errors.

**Comment by mrajalko** [comment]
Can you please elaborate. I am newbie in this.
My existing Web Project are also throwing same error.

**Comment by volkanceylan** [comment]
Look at output tab of your Visual Studio to see actual errors.
