### ISSUE TITLE
Multitenancy - Creating clonable Master Tenant account

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#797]
I have an account I created that shares the same tenant ID as the admin account. When I go to attempt to access pages where grids containing protected data are, I keep getting a denied  access error. I confirmed in the User and User Permissions table and both the admin and the new account share the same tenant ID on the table. Any idea what may be the cause? I've implemented Multitenancy using the same method as the manual. Figured I'd ask in case it's something related to .ts

**Comment by volkanceylan** [comment]
Check service permissions, endpoint, row etc.

**Comment by sayuga** [comment]
I've come to see the issue is not with multi-tenancy specifically. I was assuming (dumbly) that Tenant 1 would have Master Admin access similar to the admin account that Serenitiy begins with. This is not the case. Tenants have tenant access and only this one admin account has full admin rights. 

What is my simplest way to be able to generate a master tenant that would have access to all tenant files regardless of their Multi-Tenancy? Or to essentially create a duplicate Master Admin account? 

My end goal will have 3 Permission levels of access: 

-Developer(MasterAdmin): Access to anything and everything including configuration files regardless of tenancy. 

- Admin(LimitedAdmin):  Access to all data regardless of tenancy but removes access to configuration files (this one is essentially clones of the Developer but with less views.) 

- Client(ReadOnly): Read only access to Tenant Filtered Data. Client will see preset SQLView reports on grid which can be filtered, exported to excel and exported to PDF, but will not be able to see any data outside their tenancy.

**Comment by volkanceylan** [comment]
There is info about this with Tenants permission in guide. E.g. Users are not filtered for admin.

**Comment by Mohammad-Yasfo** [comment]
I have the same end goal, do you share your experience, please? @sayuga
