### ISSUE TITLE
Is it necessary to convert existing code to TypeScript?

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#798]
Hi @volkanceylan 

As i heard in another thread that most of peoples have converted their code from saltarelle to typescript. 
Is it necessary? Because i have huge code written using saltarelle and will take lot of time to convert to typescript. **Can i use TypeScript only for new forms?**

I have read in the doc at following that if If Bridge.NET v2.0 (next Saltaralle) comes out, we may also try to switch. 
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_upgrade_to_serenity_2_typescript.html

Bridge.NET  has confirmed that hey are not going to release any version of Saltaralle, but releasing Bridge instead of Saltaralle. Is there any possibility to use Bridge.NET in future instead of typescript?

**Comment by volkanceylan** [comment]
You should only use TypeScript for new dialogs, don't have to transform old ones.

I'm probably not going back to Bridge anymore, as Erik, Saltaralle author is not in that team. They are not gonna release a Saltaralle compatible version, and i don't trust them.

**Comment by ramveersgh** [comment]
Ok, Thanks for the suggestions.
