### ISSUE TITLE
Master Detail

### ISSUE THREAD

**Issue by lubismargana** [volkanceylan/Serenity#799]
I Have 3 tabels Vendor, PIC and PIC Attachments,
When I Update Data in Vendor, i found error
![test](https://cloud.githubusercontent.com/assets/19926648/16038061/90dbdeca-324d-11e6-953d-a032634d102e.JPG)

Please help.
Thanks.

**Comment by volkanceylan** [comment]
Set CompareOldValues = false in MasterDetailRelation

**Comment by lubismargana** [comment]
It works for me CheckChangesOnUpdate =false
Thanks.
