### ISSUE TITLE
Sergen not generating correct datatypes from db tables

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#80]
First of all, I love this project, and it's helping me immensely with a personal project of mine. However, I've noticed a possible issue I believe with sergen. I've created several tables using FluentMigrator syntax and the db migrations as you've shown in the tutorial, which works great. The problem I'm seeing seems to be when I use sergen to create the code from those tables. Specifically, with regards to time. My migration will look like: 

```c#
// ...
Create.Table("Call").InSchema("ops")
    .WithColumn("CallId").AsInt32().PrimaryKey().Identity().NotNullable()
    .WithColumn("CallTime").AsTime().NotNullable()
// ...
```

And when I check the table in SQL Server Object Explorer it correctly displays the column datatype property as `time(7)`. I am going to correct that to show the proper scale `time(0)` but that isn't the issue. What happens is after I generate the code from the table using `sergen.exe` I will see the following in `CallRow.cs`:

```c#
// ...
[DisplayName("Call Time")]
public Stream CallTime
// ...
```

Now I know that I can go and change this manually and then rebuild the project and it should work, but I was wondering if we could figure out a fix for `sergen.exe` so it doesn't actually generate that code. I didn't realize it until I built the project and then received an unhandled user exception that said something about not being able to convert `varbinary`. I have a lot of occurrences in many tables of time column. I really appreciate you taking the time to address this issue, and I want to reiterate again how thankful I am that you've put so much hard work into this project!

**Comment by volkanceylan** [comment]
Thanks for nice words. I didnt use time column before so i probably missed that one. You are using SqlServer right? And what do you think, should it be mapped to DateTime field or we need a TimeSpan column?

**Comment by volkanceylan** [comment]
It looks like TimeSpan is correct type. 1.8.16 has TimeSpanField and Sergen uses this type for time fields. I did a quick test and it seems to work. There is just not a custom editor type for now, but string editor works, though it does no client side validation. You can add CssClass("hourAndMin") to your TimeSpan fields for some basic validation support.

**Comment by volkanceylan** [comment]
@jsbUSMC any updates on this?

**Comment by jsbUSMC** [comment]
Sorry man I had a couple days off from work and haven't been checking my Github account in the meantime. Yes, I am using SQL Server 2014 Express, and I think that having TimeSpan would be the correct field. I think it's more appropriate since the DateTime field is already mapped to Date, Datetime2 and DateTime. I will check around a bit and see if I can't help come up with a good solution for the client-side validation of the time editor. Could we use a custom regexp validator or include a library? I think the latter is probably a better choice.

**Comment by volkanceylan** [comment]
You might create an editor subclassing StringEditor, for regex based validation:

```cs
    [Editor]
    public class MyTimeEditor : StringEditor
    {
        public MyTimeEditor(jQueryObject input)
            : base(input)
        {
            this.AddValidationRule(this.uniqueName, (e) =>
            {
                if (!new Regex("ab:cd:ef.ffff?").Test(this.Value.Trim()))
                    return "Not a valid time...";

                return null;
            });
        } 
   }
```

**Comment by jsbUSMC** [comment]
I appreciate the help and the quick response! If you want to close this issue, that's cool with me. As far as the validation client-side, I will let you know how I go about validating the time input and perhaps open a PR for you to check.

**Comment by volkanceylan** [comment]
You're welcome, let me know if any problems, have a nice year
