### ISSUE TITLE
Lookup Script is not found in registered scripts

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#800]
I have defined a new lookup:
```
    [LookupScript("Administration.NameUserlookup")]
    public sealed class NameUserLookup : RowLookupScript<UserRow>
    {
        public NameUserLookup()
        {
            IdField = UserRow.Fields.UserId.PropertyName;
            TextField = UserRow.Fields.DisplayName.PropertyName;
        }

    }
```
This lookup is referenced in a row file
```
  [DisplayName("Raised By"), ForeignKey("[Core].[dbo].[Users]", "UserId"), LeftJoin("rUser")]
        [LookupEditor("Administration.NameUserlookup")]
        public Int32? RaisedBy
        {
            get { return Fields.RaisedBy[this]; }
            set { Fields.RaisedBy[this] = value; }
        }

        [DisplayName("Raised By"), Expression("rUser.DisplayName")]
        public string RaisedByName
        {
            get { return Fields.RaisedByName[this]; }
            set { Fields.RaisedByName[this] = value; }
        }
```
If I go to the form the dropdown appears empty. But items are selectable in it and transfer data back. So it looks like the ID is going into the dropdown correctly. It shows the names in the grid correctly.

If I go to the console and try Q.getLookup('Administration.NameUserLookup') as per the movie tutorial is responds with

>  Script data Lookup.Administration.NameUserLookup is not found in registered script list!

It was working before I made the wholesale switch to TS.

**Comment by solabar** [comment]
Update: The same problem seems to be affecting QuickFilter
```
[Width(200), QuickFilter]
public String AssignedToName { get; set; }
```
in my columns.cs is returning a dropdown with blank entries but id's are there as it applies a filter.

**Comment by volkanceylan** [comment]
Administration.NameUserlookup
Q.getLookup('Administration.NameUserLookup')

Please stop relating everything to TypeScript, check case first

Your name field is not included in lookup, that's the problem probably.
