### ISSUE TITLE
Is there any sample for inline editing with Add/Update/Delete in Grid.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#801]
Hi @volkanceylan 

Do you have any sample or guideline to add inline editing functionality with Add/Update/Delete in Grid?
I can check on products for inline update but can't look for Add and Delete.

**Comment by volkanceylan** [comment]
No there isnt

**Comment by ramveersgh** [comment]
@volkanceylan 
Ok,  If it is not too much complex then i may try to do it if you suggest me any way or guideline OR I can wait until you release a sample for it (off-course if you are planning to have it)?
well, It may be a good feature to add in serenity to support inline editing.

**Comment by volkanceylan** [comment]
I dont have such a plan
