### ISSUE TITLE
FilterValue=null

### ISSUE THREAD

**Issue by oaltay** [volkanceylan/Serenity#802]
public Int32? TurId
        {
            get { return Fields.TurId[this]; }
            set { Fields.TurId[this] = value; }
        }

[LookupEditor(typeof(BasvuruRow), FilterField = "TurId", FilterValue=null), QuickFilter]

Boş kayıtları getirmek için FilterValue = null işe yaramadı. başka bir yolu var mıdır.

tşk.ler

**Comment by volkanceylan** [comment]
CascadeField, CascadeValue ile deneyin.
