### ISSUE TITLE
Error DateTimeEditor

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#803]
Hi Jaiq,

I used datetimeeditor, but always error when update value,
supect it caused datetime format,  in json i found this format "2013-08-26T00:00:00.000"

![capture5](https://cloud.githubusercontent.com/assets/6382278/16069459/c6986758-32f8-11e6-997a-40e9afa29df6.PNG)

Any suggest?

Thanks

**Comment by volkanceylan** [comment]
It's correct ISO format. See whats wrong with your field.

**Comment by fazanan** [comment]
Hi Jaiq,

Sorry for this i think something happend with datetimeeditor control, 

I tried to save dialog with datetimeeditor control enabled it post json data like this. **"OrderDate":"2016-06-29T00:00:00.000"**, saved data sucessfully

But when trying to save the data with disable control it post like this **"OrderDate":"2016-06-29Tnull:00.000"**, error as my question.

Any suggestion?.

Thanks

**Comment by volkanceylan** [comment]
How do you disable the control

**Comment by fazanan** [comment]
Use this, disable all control under category

 jQuery(".category:eq(0) *").attr("disabled", "disabled");

Thanks

**Comment by volkanceylan** [comment]
Use EditorUtils.SetReadOnly

**Comment by fazanan** [comment]
Hi Jaiq,

Thanks for answer, it works, but is posible to set all control under category to readonly use this function?

Serenity.EditorUtils.setReadOnly(jQuery(".category:eq(0)"), true); it's error 

![capture7](https://cloud.githubusercontent.com/assets/6382278/16253638/32aaeb00-3862-11e6-95ac-1f4d9062ec24.PNG)

Regards

**Comment by fazanan** [comment]
Hi Jaiq,

Any suggestion for last question? :)

Regards

**Comment by volkanceylan** [comment]
SetReadOnly only works with ediors

**Comment by fazanan** [comment]
Thanks for answer, 

I have many control under category, and need to set enable/disable based on condition,
so i should setting them one by one? or you have another suggestion?

Regards

**Comment by volkanceylan** [comment]
Find editors by. editor
