### ISSUE TITLE
How to debug SqlScript in VS 2015

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#805]
I'm sorry, just simple question how to show or debug sql script that generated by serenity in VS 2015? :)

Thanks

**Comment by volkanceylan** [comment]
You debug it in Chrome, not VS

**Comment by volkanceylan** [comment]
Sorry, i though you are talking about javascript.

You can see it while debugging it in VS2015, or turn logging level to Debug in web.config settings and have log files under App_Data/log, or use Stackify Prefix, Glimpse, Mini profiler or similar tool.

**Comment by fazanan** [comment]
Thanks Jaiq.
