### ISSUE TITLE
Call Services

### ISSUE THREAD

**Issue by lubismargana** [volkanceylan/Serenity#806]
How to call service from another application with ServiceAuthorize?
Please help me.

Thanks.

**Comment by jsbUSMC** [comment]
The ServiceAuthorize() attribute is part of the permissions system _inside_ of Serenity. When placed above a controller method in XYZEndpoint.cs, it checks that the user is currently logged in. If you're going to call a service from an external application, you'll have to add the service to your controller manually.

**Comment by volkanceylan** [comment]
Use JsonServiceClient from Serenity.Services:

```cs
var client = new JsonServiceClient("http://www.mysite.com/");
var client = new JsonServiceClient("http://www.mysite.com/");
client.Post<ServiceResponse>("Account/Login", 
	new LoginRequest {
		Username = "someuser",
	    Password = "somepass"
    });

var list = client.Post<ListResponse<Dictionary<string, object>>>(
	"Services/Northwind/Customer/List", 
	new ListRequest {
		Take = 100
   	});
```

**Comment by lubismargana** [comment]
Thanks mr. volkanceylan

**Comment by sebacamino** [comment]
Hey @volkanceylan It's possible install Serenity.Services in Xamarin? I have some problems... Thanks

**Comment by volkanceylan** [comment]
Take code for ServiceClient, modify it a bit.

**Comment by PAAutofac** [comment]
@volkanceylan : I want to replace the standard "Unauthorised Access" message with a custom Html Page, could you please let me know what is the best option to implement the same.

Thanks

**Comment by reach2rv** [comment]
Hi,
I am getting an error on new LoginRequest how to create this object??
