### ISSUE TITLE
Loading data from table with duplicate PKs/FKs

### ISSUE THREAD

**Issue by CAlva123** [volkanceylan/Serenity#809]
Hello!

In my database there's a table with 3 Primary Keys (IDs), 2 of which are also Foreign Keys. 
The FKs can have duplicate values, but when I map that table using Sergen, and there are duplicate values in those FKs, no data is shown. And when I try to insert/update an entry to add a duplicate ID, the application crashes, from the corresponding method in the Repository class, showing a conflict in FKs.

How can I solve this?

EDIT: Insert and Update queries in SQL work as expected, I can add registries with duplicate values.

**Comment by volkanceylan** [comment]
Either add an identity field to table, or use a composite expression field with CONCAT.

**Comment by CAlva123** [comment]
Changing to identity worked. Thank you.
