### ISSUE TITLE
Cannot add new user (when using MySQL database)

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#81]
1. Using Serene website
2. Select "Administration"
3. Select "User Management"
4. Select "New User"
5. Enter information for user.
6. Select "Save"

Get exception:
"An exception of type 'MySql.Data.MySqlClient.MySqlException' occurred in Serenity.Data.dll but was not handled in user code

Additional information: FUNCTION serene_default_v1.SCOPE_IDENTITY does not exist"

**Comment by volkanceylan** [comment]
Can you check if identity inserts succeed in other tables? Like in Northwind?

**Comment by brettbeard** [comment]
It does not seem to work for the Northwind database either.  Same "SCOPE_IDENTITY does not exist" exception.

**Comment by volkanceylan** [comment]
Ok, i could reproduce it. It seems like connection dialect is not used properly. Will release a new version soon.

**Comment by volkanceylan** [comment]
Please update to 1.8.17 nuget packages, and let me know if you still have any problems. I don't have tests for other database types yet.

**Comment by volkanceylan** [comment]
@brettbeard is your problem solved?

**Comment by brettbeard** [comment]
Yes, this appears to be fixed now.
