### ISSUE TITLE
How to set selection value in lookup editor with multiple = true

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#811]
Hi Jaiq,

How to set selection value in (AC/DC Site lookup editor) based on equipment change?

![capture6](https://cloud.githubusercontent.com/assets/6382278/16135460/f442ad84-344d-11e6-837f-6181f01232e3.PNG)

Use this tricky now work properly.

 form.Eqp.ChangeSelect2(e =>
 {
          EquipmentService.Retrieve(new RetrieveRequest
          {
                        EntityId = IEqpId
           }, response =>
          {
EquipmentRow eqp = response.Entity;
  J(".select2-choices").Append("<li class='select2-search-choice'>" + eqp.acdc + "<div></div><a tabindex = '-1' class='select2-search-choice-close' href='#'></a>");
          }
 }

**Comment by volkanceylan** [comment]
use form.ACDC.Values

**Comment by fazanan** [comment]
I user this when row class
      [DisplayName("AC/DC Site")]
        [LookupEditor(typeof(AcDcSiteRow), Multiple = true), ClientSide]
        [LinkingSetRelation(typeof(ApprovalEqpAcDcRow), "AppEqpId", "ACDCSiteId"), NotNull]
        public List<Int32> AcDcSiteList
        {
            get { return Fields.AcDcSiteList[this]; }
            set { Fields.AcDcSiteList[this] = value; }
        }


What the data type that should be sign List<Int32> right ?

**Comment by fazanan** [comment]
I user this when row class
[DisplayName("AC/DC Site")]
[LookupEditor(typeof(AcDcSiteRow), Multiple = true), ClientSide]
[LinkingSetRelation(typeof(ApprovalEqpAcDcRow), "AppEqpId", "ACDCSiteId"), NotNull]
public List AcDcSiteList
{
get { return Fields.AcDcSiteList[this]; }
set { Fields.AcDcSiteList[this] = value; }
}

What the data type that should be sign "List Int32 " right ?

**Comment by fazanan** [comment]
Thanks Jaiq,

It works, with passing the ID in string type

form.AcDcSiteList.Values = new string[] { "1", "2" };

Regards
