### ISSUE TITLE
Grid QuickFilter: filter items on dynamic condition

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#812]
Dear @volkanceylan,
I would like to filter my grid quick search items on a dynamic condition.
I have a quick filter like that:

	this.addQuickFilter({
		type: BSMultiSelectEditor,
		field: "SupportGroupId",
		title: "Support Group",
		options: {
			//lookupKey: "CSH.SupportGroup",
			lookupKey: "CSH.SupportGroupByUser",
			includeSelectAllOption: true,
			maxHeight: 200,
			enableFiltering: true,
			enableCaseInsensitiveFiltering: true
		}
	});

and I would like to filter the items based on the Support Group which the current (logged) user belong.
To do that I created a new SupportGroupLookup class (with the [LookupScript("CSH.SupportGroupByUser")] attribute) and then I have overridden the PrepareQuery() method adding a "blabla== Authorization.UserDefinition.Id" condition.
Now everything is working fine, but I remember than in a previous issue #642 you had discouraged the usage of such technique because of the caching mechanism of Serenity,
For the custom dialog editors I put all this kind of logics in the getItems() method, but I would like to know which is the right approach here...

Thank you very much for your support (and your time)
Bye

**Comment by volkanceylan** [comment]
You should better filter records server side, not with quick filter. If you meant to filter lookup client side, you should create an editor, get current support group from somewhere, e.g. ScriptUserDefinition and filter in editor, not with lookup server side. Another option is to turn off caching for your lookup.

**Comment by marcobisio** [comment]
So I can use the same approach of the custom LookupEditor editor in dialog?
Create a quick filter from a custom LookupEditor and put my logic/filter in
the getItems() method?
The other way round, in order to turno off caching I have to remove the
TwoLevelCache attribute from the entity...right?

Thank you very much
Bye

Marco Bisio

Sent by Note4 mobile
Il 18 Giu 2016 00:35, "Volkan Ceylan" <notifications@github.com> ha scritto:

**Comment by volkanceylan** [comment]
No, you should write a custom lookup and set expiration to negative value.

**Comment by marcobisio** [comment]
Copy that...I'll try!
Thank you very much
Bye
