### ISSUE TITLE
How to add Edit Filters button

### ISSUE THREAD

**Issue by CAlva123** [volkanceylan/Serenity#815]
Hello!

In most tables shown in the Northwind sample, there is an "Edit Filters" button in the lower right part, which opens a filter panel for the current table. The pages I generated via sergen don't have this button, and I cannot find the exact part where the button is loaded in the samples. How can I add this button to my generated pages?

**Comment by jsbUSMC** [comment]
There's an attribute you place above your Row class

**Comment by jsbUSMC** [comment]
Sorry I was wrong. In XYZGrid.ts add method `protected createQuickFilters() { super.createQuickFilters(); }`

**Comment by volkanceylan** [comment]
[Filterable] or @Serenity.Decorators.filterable

**Comment by CAlva123** [comment]
Modifying the *Grid.ts file worked. Thanks to both of you.
