### ISSUE TITLE
Extending BSMultiSelectEditor

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#816]
Dear @volkanceylan,
I'm trying to extend the BSMultiSelectEditor (implemented in the "How To: Use a Third Party Plugin With Serenity" chapter of the Serenity developer guide).
I modified a bit the BSMultiSelectEditor  in order to expose a getItems() method and that part it's working fine, but when I try to add a new editor by extending the BSMultiSelectEditor, then I got the following console error:
![image](https://cloud.githubusercontent.com/assets/17425690/16177483/22bce58e-362f-11e6-9572-593d197c4cea.png)

Here my code of the extended BSMultiSelectEditor:

    namespace myProject {
        @Serenity.Decorators.registerClass([Serenity.IGetEditValue, Serenity.ISetEditValue])
        export class SupportGroupEditor extends BSMultiSelectEditor {
    
            constructor(element: JQuery, opt: BSMultiSelectOptions) {
                super(element, opt);
            }
    
            protected getLookupKey() {
                return 'CSH.SupportGroup';
            }
    
            protected getItems(lookup: Q.Lookup<CSH.SupportGroupRow>) {
                // TBD
            }
        }
    }

Any idea on what I'm doing wrong?
Thank you very much
Bye

**Comment by volkanceylan** [comment]
///references

**Comment by marcobisio** [comment]
Once again the same "fake problem"...honestly I have not yet figured out when I must use such instructions...I mean when it's required...
Btw thanks for your support!
Bye
