### ISSUE TITLE
Module 'System' has no exported member 'String'

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#817]
I created a function which returns string in one of the entity EndPoint class. after that i am getting 
error 
Module 'System' has no exported member 'String' 
while rebuilding application. 
Application runs. But i wan to know
where i can make changes for this error.
regards
Shailesh

**Comment by volkanceylan** [comment]
Endpoints can't return string, must be something derived from ServiceResponse

**Comment by shaileshbc** [comment]
It works fine.
Thanks
regards
Shailesh
