### ISSUE TITLE
LeftJoin with Where statement (or Filterable dropdownbox)

### ISSUE THREAD

**Issue by SuckyCoder** [volkanceylan/Serenity#818]
Hi,

I have a table that contains items which are supposed to be used in different dropdown-boxes(around 10-13 of them). Each item in that table has a "List_name". (ComputerStatus , ComputerUsedAs, ComputerHddType, ComputerRamType, ComputerCpuType... etc etc)

I wonder if there is a way to add a "where" statement to LeftJoin, so that only items with one specific "List_name" would show up, instead of all items. List items need to be managable from the web, so I cant just hardcode choices for each dropdownbox as in Movie Kind example.

![image](https://cloud.githubusercontent.com/assets/19668529/16196475/658c8386-36fe-11e6-9248-de34df0d6fc1.png)

This is what i have so far. (using Movie Genre as an example)

```
[DisplayName("Status"), Column("Status")]
        [ForeignKey("[hw].[List_entry]", "Id"), LeftJoin("jstat")]
        public Int32? Status
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }

        [DisplayName("StatusName")]
        [Expression("jstat.Value")]
        public String StatusName
        {
            get { return Fields.StatusName[this]; }
            set { Fields.StatusName[this] = value; }
        }

        [DisplayName("StatusListName")]
        [Expression("jstat.[List_name]")]
        public String StatusListName
        {
            get { return Fields.StatusListName[this]; }
            set { Fields.StatusListName[this] = value; }
        }
```

Any ideas on how i can make it work without having to create separate tables for each drop down box? Having 10-13 tables just for one form seems silly, specially in already crowded DB.

**Comment by volkanceylan** [comment]
Add LookupInclude to your StatusListName field and use FilterField, FilterValue

**Comment by SuckyCoder** [comment]
I've added FilterField and FilterValue. Now all my values disappear :(. Any ideas?

```
[DisplayName("Status"), NotNull, 
    ForeignKey("[hw].[List_entry]", "Id"), 
    LeftJoin("jStatus"), TextualField("StatusValue")]
[LookupEditor(typeof(ListEntryRow), 
    FilterField = "StatusListName", FilterValue = "ComputerStatus")]
public Int32? Status
{
    get { return Fields.Status[this]; }
    set { Fields.Status[this] = value; }
}

[DisplayName("Status Value"), Expression("jStatus.[Value]")]
public String StatusValue
{
    get { return Fields.StatusValue[this]; }
    set { Fields.StatusValue[this] = value; }
}

[DisplayName("Status List Name"), Expression("jStatus.[List_name]"), LookupInclude]
public String StatusListName
{
    get { return Fields.StatusListName[this]; }
    set { Fields.StatusListName[this] = value; }
}
```

**Comment by volkanceylan** [comment]
Add LookupInclude in lookup row, not here!
