### ISSUE TITLE
Using Dialogs from differerent places

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#819]
Hi Volkan,

Here is an interesting supposition for you. I have a sergen generated section which all works great. What I would like to do is use the model and dialog to this section from somewhere else. I could use the dialog directly I assume (although haven't pieced out the right way to call it) but it would be handy if I could set permissions on individual controls on the dialog. For example, Administrators and department managers can change everything, a regular user can't and wouldn't even see the control (making it a hidden control instead for example) Is there any way to achieve this?

Obviously I can just write another dialog separate from the first, but reusing code would be a better method.

**Comment by volkanceylan** [comment]
Model it around permissions.
