### ISSUE TITLE
Help with Dialog print preview button

### ISSUE THREAD

**Issue by TataFalat** [volkanceylan/Serenity#82]
Hello,
I'm in Serenity discovery phase. I've successfully added simple Request registry agenda to your Serenity demo. So I have RequestDialog and can edit and save all details needed. Now I want to add Print button to the Dialog. The result should be printable html page with all data filled. I have already added button to GetToolbarButtons, but without OnClick function. I have working Request.html template with appropriate styling and some simple javascript to fill the data through document.getElementById().innerHTML just to see whether the templete is OK. What are next steps you reccomend to do: where (in the MSProj structure) to put the template, what is the best way to fill it with the selected Request data and to show the resulting page on screen.
Thank you for your time, Jan.

**Comment by volkanceylan** [comment]
I recommend putting your Request.html next to RequestPage.cs, but it is better to make it RequestPrint.cshtml and add an action to RequestPage.cs that returns it as a view. The model for this page should be RequestRow or a class containing a RequestRow. You can take which request to print from query string (action parameter) and call RequestRepository.Retrieve with this request id. Then, in RequestPrint.cshtml use this model and lay properties in print layout.

**Comment by volkanceylan** [comment]
Reopen if it didn't resolve this.
