### ISSUE TITLE
ScriptBundling requirements

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#820]
Dear @volkanceylan,
I've successfully enabled the script bundling feature and when I run the application from Visual Studio I can see the two bundles instead of the single js library files.
Now I moved the application to the quality environment, but for some reasons the script bundling seems to be not working.
I've double checked the web.config and it's ok...

    <add key="ScriptBundling" value="{ Enabled: true, Minimize: true, UseMinJS: true }" />
So my question is: such feature require some specific setting and/or version of IIS? Or I'm missing something?

Thank you very much
Bye

**Comment by marcobisio** [comment]
ScriptBundles.json is missing on the server...it should be there?

**Comment by volkanceylan** [comment]
:)

**Comment by marcobisio** [comment]
argh the property was "Do not copy"...I think should be "Copy always" by default!
Still not working btw... :-(

    @Html.Script() Object doesn't support this property or method

Still fighting...

**Comment by volkanceylan** [comment]
Check your config files, compare files with a tool like Winmerge

**Comment by marcobisio** [comment]
Changed the build action to "Content" and now the json file is properly included in my publish package.
The "Copy to Output Directory" wasn't the right approach...
Double checked, but still I got this:
![image](https://cloud.githubusercontent.com/assets/17425690/16222829/8d86dc78-379a-11e6-8f72-37cc686a55f3.png)

I don't know why because in the dev environment it's working fine...

**Comment by solabar** [comment]
Two things worth checking here since this looks similar to something I had.

- Did you update any NuGet packages? I was getting some MsieJavaScriptEngine problems when I did that.

- Second, since it is working on dev but not live, check that all your files are included in the project. If they are on your dev server they will be found fine, but won't copy when you publish/deploy.Might be why your json was missing.

**Comment by marcobisio** [comment]
Thanks for your contribute @solabar.
A part of Select2, all the other packages are updated and serenity v2.2.2. The MsieJavaScriptEngine package it's the v1.7.1 version.

I'll try a "manual" deploy and I let you know...
Btw I'm sure that the issue appears only when I enable the ScriptBundling...just switching Enabled to false and everything it's working fine also in the quality environment...switch to True and I see the error page above...

**Comment by volkanceylan** [comment]
Check web.config files are copied under modules and views folders

**Comment by marcobisio** [comment]
Both the web.config files are under modules and views folders

**Comment by volkanceylan** [comment]
So sorry Marco, this is not about Serenity, you should see what's wrong with your IIS/deployment.

**Comment by marcobisio** [comment]
You're right @volkanceylan, but I don't know the detail of the implementation of the ScriptBundler and this is why I'm asking support...btw I copied ALLfiles to the quality environment and it's still not working...there is something else that I should check? Otherwise I'll give up with the script bundler :-(

**Comment by volkanceylan** [comment]
The error you have getting has nothing at all related to Script Bundler

**Comment by marcobisio** [comment]
Probably you're right, but for some reasons it's related to the SetupJsEngine() method of the Serenity.Web,ScriptBundleManager (from what I can see from the stacktrace)...
Btw no problem, I can live without such feature....

Thanks as always for your support!
Bye

**Comment by volkanceylan** [comment]
You probably have IE8 in server, upgrade it.

**Comment by marcobisio** [comment]
Honestly @volkanceylan, you're a f@ck1ng genius...
Just upgraded from IE8 to IE11 and now it'works like a charm...

Once again thank you very much!!!
Bye

**Comment by volkanceylan** [comment]
You're welcome. Sorry i thought error was in Html.Script line, didn't see stack trace.
