### ISSUE TITLE
Multitenant with different Schema problem

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#821]
I have created a project using Serene 2.2.3 version. I want to make it Multitenant, but instead of Multitenant i say as MultiCustomer. Also i had changed Schema of all Tables from default dbo to STA.
Created Migration for Customer table and created view also. I have made changes as per your Serenity guide from Page No. 125 Page No. 141.
Now when i try to modify any User, it gives me error "Invalid Object Customer",  which can be resolved if
i create Customer table again for dbo schema. But i want it to be used in my Schema.
you can download code from
[http://ddsindia.co.in/STA.rar](url)
can u let me know, what steps i have missed out and to be corrected.
regards
Shailesh

**Comment by volkanceylan** [comment]
I'm not offering such a support here, sorry

**Comment by shaileshbc** [comment]
I have changed CustomerID field in UserRow from 
[DisplayName("Customer"), ForeignKey("Customer", "Id"), LeftJoin("cust")] to
[DisplayName("Customer"), ForeignKey("[STA].[Customer]", "Id"), LeftJoin("cust")]
and it works fine.
thanks
regards
Shailesh
