### ISSUE TITLE
Dropdown & multiselect is getting empty

### ISSUE THREAD

**Issue by nilimajagtap** [volkanceylan/Serenity#822]
Hello
 I am stuck in very basic issue.Dropdown and Multiselect dropdown is getting empty since data is there.
I have tried evrything,checked in issue list too,but it could'nt resolve my problem.
I have override the onReturn() method in repository although its not working
Here is my screen:
![image](https://cloud.githubusercontent.com/assets/16571169/16221092/79784866-37ae-11e6-9b38-117cec296f89.png)

here is screen for Multiselect dropdown:

![image](https://cloud.githubusercontent.com/assets/16571169/16221130/ae5814e4-37ae-11e6-8fe2-6708fccb3922.png)

**Comment by volkanceylan** [comment]
Check your name field, both in row and client side, check that it has lookupinclude

**Comment by nilimajagtap** [comment]
Yes,I Have added

```
    [DisplayName("Student"), NotNull, ForeignKey("[dbo].[Students]", "Id"), LeftJoin("jStudent"), TextualField("FirstName"), LookupInclude]
        [LookupEditor(typeof(StudentsRow))]
        public Int32? StudentId
        {
            get { return Fields.StudentId[this]; }
            set { Fields.StudentId[this] = value; }
        }
```

**Comment by volkanceylan** [comment]
This is ID field, check name field omg.
