### ISSUE TITLE
Changing Display Field in Lookup Dropdown

### ISSUE THREAD

**Issue by AtillaBilgic** [volkanceylan/Serenity#823]
Hi @volkanceylan 

I would like to know how to change or declare Display Field in dropdown. 

![image](https://cloud.githubusercontent.com/assets/5714485/16222879/2ca09364-37a3-11e6-9bb2-055ef425d4e7.png)

I want to display computer name instead of MAC Address.
Thanks

**Comment by solabar** [comment]
You need to change you lookupscript ot make a new one.

```
[LookupScript("Computer.NameUserLookup")]
    public sealed class NameUserLookup : RowLookupScript<ComputerRow>
    {
        public NameUserLookup()
        {
            IdField = UserRow.Fields.Id.PropertyName;
            TextField = UserRow.Fields.ComputerName.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {

            base.PrepareQuery(query);
            var fldComputer = ComputerRow.Fields;

            query.Select(fldComputer.Id, fldComputer.ComputerName);

        }
    }
```

For example. I used something similar on the User table to bring back display name rather than their Loginid.

**Comment by AtillaBilgic** [comment]
Thanks @volkanceylan

**Comment by volkanceylan** [comment]
You should modify name field in row

**Comment by AtillaBilgic** [comment]
Hi @volkanceylan 

I check the whole documentation and wiki but I could not find how to define a name field in row.

**Comment by volkanceylan** [comment]
You must have missed it, shown in many places, INameField interface

**Comment by AtillaBilgic** [comment]
Hi 

For everyone's reference it is code block under xyzRow.cs

        StringField INameRow.NameField
        {
            get { return Fields.ComputerName; }
        }

Thanks for your patience and help.

**Comment by vinaykulkarni89** [comment]
@volkanceylan 

in below scenario i need two Stringfields

StringField INameRow.NameField
    {
        get { return Fields.ProductName; }
    } 

StringField INameRow.NameField
    {
        get { return Fields.SerialNo; }
    }

as my form where im using this lookup i need drop down for ProductName and SerialNo also

**Comment by VictorTomaili** [comment]
Use computed property for name field.

**Join us on Slack**
[Get Invitation](https://serenityslackinvitation.herokuapp.com)
[Login](http://serenityplatform.slack.com/)

**Comment by vinaykulkarni89** [comment]
@VictorTomaili how can i use calculated property

**Comment by VictorTomaili** [comment]
Read docs

**Comment by vinaykulkarni89** [comment]
how can i perform computation on stringfield

**Comment by VictorTomaili** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Employee/EmployeeRow.cs#L41
