### ISSUE TITLE
Add EntityType on CaptureLog

### ISSUE THREAD

**Issue by auareve** [volkanceylan/Serenity#826]
Hi everyone!

Any idea to get this?

**Comment by jsbUSMC** [comment]
What do you mean? Your capture log is defined in your entity class. You decorate the class declaration with the `[CaptureLog(typeof(MyEntityCaptureLogRow))]`. You have to create a migration to create the capture log tables fields that you want captured. Thus, your EntityType is in the name of the capture log table.

**Comment by auareve** [comment]
Thanks for the answer and your colaboration jsbUSMC..... 
In my app, i have some tables with the same structure (Id, Name) and i want make only one class CaptureLog to all this, i need some way to differentiate every one of the registers and i suppose this is the way... if any one have other idea please let me know

**Comment by volkanceylan** [comment]
You need to write your own capture log for this, copy, paste, modify
