### ISSUE TITLE
Lookup with open button without inplaceadd

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#829]
Hello to all.

Is there a way to add a lookup field with an associated button to open dialogue, without entering the InplaceAdd true?

For example:
`[LookupEditor("Default.MyTable" InplaceAdd = false, DialogType = "MyTable")]`

I would like an inspection button without the ability to create new records in place, but in this way nothing is shown.

Thank you

**Comment by marcobisio** [comment]
More or less something like that:

    var fieldEditor: JQuery = this.form.YourField.element.closest(".editor");
    fieldEditor.addClass("has-inplace-button");
    $('<a><b/></a>')
    	.addClass('your-css-class')
    	.attr('title', 'your-title')
    	.insertAfter(fieldEditor)
    	.click(() => {
    		new yourProject.xyz.yourDialog().loadByIdAndOpenDialog(YOUR_ENTITY_ID);
    });

**Comment by volkanceylan** [comment]
Thanks @marcobisio

**Comment by marcobisio** [comment]
You're welcome :-)

**Comment by Estrusco** [comment]
Thank you @marcobisio ! My final code 

```cs
var fieldEditor: JQuery = this.form.YourField.element.closest(".editor");
fieldEditor.addClass("has-inplace-button");
$('<a><b/></a>')
	.addClass('inplace-button')
    .addClass('inplace-create edit')
    .attr('title', 'Details')
    .insertAfter(fieldEditor)
    .click(() => {
           new yourProject.xyz.yourDialog().loadByIdAndOpenDialog(Id);
    });
});
```

**Comment by Estrusco** [comment]
close
