### ISSUE TITLE
How to Pass Master Record ID to Detail Edit Dialog

### ISSUE THREAD

**Issue by AtillaBilgic** [volkanceylan/Serenity#830]
Hi All, 

I have a question about Master Detail Related list screens
I have followed "The Cast and Characters They Played" section in tutorial.
I could be able to save master records but when I wanted to save a detail record it says MasterID field is not available.
What I am missing?

**Comment by volkanceylan** [comment]
See MovieTutorial source in its repository to check what you are missing.
