### ISSUE TITLE
LookupEditor List in Html.DropdownListFor

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#832]
I have a second interface intended for non administrative users. This uses a regular view with razor.
What I would like to work out is how to call my lookup here:

`@Html.DropDownListFor(model => Model.Ownerid, *LOOKUP*, new { @class = "form-control" })`

Or could I use [LookupEditor("xxx.xxx")] in the model I am using for the new interface?
```
[LookupEditor("Administration.HelpdeskUser")]
public Int32 Ownerid { get; set; }
public string OwnedBy { get; set; }
```

**Comment by volkanceylan** [comment]
It can't be used that way. You can create it with javascript though.

```cs
new Serenity.LookupEditor($('#SomeElement'), { 
    lookupKey: 'Administration.HelpdeskUser' 
})
```

**Comment by solabar** [comment]
That works great to produce the right dropdown. It does lead me on to the next question though.
Can I set the selected value in the same call? 
Is there any provision for styling the Select2 boxes that get written with the code? Looking through LookupEditorOptions it seems not, but I figure it's worth an ask. I don't want to change the base .css file if I can avoid it. I don't want my other LookupEditors going strange.

**Comment by volkanceylan** [comment]
Either override CSS in your page/stylesheet, or use ordinary select by creating one getting lookup items with Q.getLookup

**Comment by solabar** [comment]
The problem appears to be a disparity between:
`<div class="select2-container col-sm-10 s-LookupEditor" id="s2id_Owner">`
and
`<a tabindex="-1" class="select2-choice select2-default" href="javascript:void(0)">`

The first is defining the size of the hidden dropdown, the second is the size of the displayed control.
is there a way to match them? I don't know exactly where in serenity this is defined.
Can you point me at the right place and I will have a look. As I cant seem to change it with css to look right and I would like to keep a consistent ui.

**Comment by volkanceylan** [comment]
I don't know what kind of CSS or element for Select2 you are using. I don't use a custom markup. This is not about Serenity.

**Comment by solabar** [comment]
new Serenity.LookupEditor($('#Owner'), {
    lookupKey: 'Administration.HelpdeskUser',
    value: '@Model.OwnedBy'
});

must generate the select2 markup. That was what I wanted to look at but was having trouble finding.

**Comment by volkanceylan** [comment]
col-sm-2 is wrong. put it on container div not select2 input.

**Comment by solabar** [comment]
Genius! Thank you. How did I miss that. Wrapped it in a new div and it works fine.
