### ISSUE TITLE
how to used Form for Views Page

### ISSUE THREAD

**Issue by alitarkian** [volkanceylan/Serenity#834]
Hi
for example , we need a contact us form.
how to used this in a single webpage !?!?
not dialog box or something. in a standard view page.
can you help me!?

**Comment by solabar** [comment]
Can't you just write this as a standard view using regular ASP and not really using Serenity at all? That would just be standard MVC?
I don't think this is related to Serenity at all.

**Comment by volkanceylan** [comment]
There are several sample pages from AdminLTE using ordinary MVC. If you want to do it in Serenity way, there are signup, change password etc. pages.
