### ISSUE TITLE
LoggingRow fails to insert InserDate while Creating Entity

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#835]
I am trying to put AuditLog into all the tables. For that i have changed Row to LoggingRow in all tables.
like Users, Roles, UserRoles, UserPermissions, UserPreferences, RolePermissions. 
My roles are getting Inserted into Database but while inserting RolePermissions, it gives error that InsertDate cannot be Null. Similar error comes while inserting UserPermissions, UserRoles.

regards
Shailesh

**Comment by volkanceylan** [comment]
You need to set that field in RowPermissionsRepository while it prepares insert query. RowPermissions etc are not originally designed to be audit logged.
