### ISSUE TITLE
deploy serenity like area in mvc

### ISSUE THREAD

**Issue by windwp** [volkanceylan/Serenity#838]
I use serenity for manage my database.
But I want integrated this into my exists website like area in mvc with link http://mysite.com/admin. 
But I think it need many change in serenity for route config.
Is there any simple solution to do this?
(I don't like to use sub domain in my website)

**Comment by samdubey** [comment]
Similar thing is implemented in [NopCommerce ](https://github.com/nopSolutions/nopCommerce)- Open Source ECommerce Framework 
NopCommerce uses [AdminAreaRegistration ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Administration/AdminAreaRegistration.cs)

I tried to implemented it but no success till now

**Comment by volkanceylan** [comment]
Add Serenity as sub application, admin. Thats all

**Comment by samdubey** [comment]
You are right Volkaceylan, but NopCommerce maintain same login across all the application
Will login will work across both the application?

**Comment by samdubey** [comment]
There are two projects in NopCommerce 
Nop.Web (Suppose Located at : C:\NopCommerce\Nop.Web )
Nop.Admin ( Located at C:\NopCommerce\Nop.Web\Administration )

Nop.Admin copies all the DLL to ..\bin folder which is Nop.Web Bin Directory

It also has  AdminAreaRegistration setup

**Comment by windwp** [comment]
I try to implement this but it still not work.
I copy all serenity file to admin folder in my exists project try to add nuget and rebuild.
After change many route link in navigationitem.cs and MVC.cs (generated code) I can login in dashboard page.
But it have problem with typescript I can't open modal when I click row item .browser console display error like this "Uncaught Error: Can't load script data: Lookup.Administration.Language!".  I can't use ServerTypings.tt to regenerated script and can't rebuild typescript :(

**Comment by volkanceylan** [comment]
Have a look at IIS & ASP.NET guides, you don't know what an IIS application is
