### ISSUE TITLE
Set value of a property at client side.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#839]
I have a dialog that has a submit button just like save but I want to set its Status field to ApplicationStatus.Submitted. For doing this I have added a button and its click event I have set the status field then call save method. but unfortunately Status does not saved. 
[Note that in my Form.cs there is no such status field.]

```
            buttons.push({
                title: 'Submit',
                cssClass: 'add-button',
                onClick: (e) => {
                    this.entity.Status = ApplicationStatus.Submitted;
                    this.save(s => { Q.notifySuccess('Application has been submitted successfully.'); });
                }
            });
```

**Comment by volkanceylan** [comment]
Entity is the loaded one, not the one going to be saved. Override getSaveEntity

**Comment by tvldev02** [comment]
Ok. but I have different buttons for saving a single entity different ways. such as draft, submit etc.

**Comment by volkanceylan** [comment]
Hope you know how to define a private variable and set in on click
