### ISSUE TITLE
Northwind Customer List Page Do not Open Dialog when Switch to SQL Server from LocalDb

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#84]
If we change connectionstring to use SqlServer Northwind Example Customer List do not open dialog
Code generates different for MS SQL Local Db and SQL Server

**Comment by volkanceylan** [comment]
What is the error you are getting in console? And are you changing only Northwind connection or both?

**Comment by samdubey** [comment]
Sorted

**Comment by volkanceylan** [comment]
Would help others if you shared what was the problem.

**Comment by samdubey** [comment]
Auto fixed with latest update :-)
