### ISSUE TITLE
Image From Database With Stream Type

### ISSUE THREAD

**Issue by orknist** [volkanceylan/Serenity#840]
İmaj dosyalarını klasör yerine veritabanında varbinary tipinde tutmamız durumunda, nasıl bir yol izlememiz gerekiyor, ImageUploadEditor yerine ne kullanabiliriz? 

If we store the images in database (varbinary) instead of folder, how we need to follow a path, what can we use instead of ImageUploadEditor?

![2016-06-26_06-31-15](https://cloud.githubusercontent.com/assets/4700526/16360368/d8bb96f4-3b67-11e6-9003-33d161101706.png)

![2016-06-26_06-34-06](https://cloud.githubusercontent.com/assets/4700526/16360370/0fc1fc06-3b68-11e6-8705-181883eb6054.png)

**Comment by volkanceylan** [comment]
It is not supported. You need to develop your custom solution for it. There is no sample,sorry.
