### ISSUE TITLE
[Please Comment]: Serenity as mBaaS solution

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#841]
Dear @volkanceylan,

I would like to see possibility of utilizing Serenity as Mobile Back-end since it creates API out of the Box

If we could add token authentication, social logins for the API it could become Mobile Backend Service just like Azure Mobile Services,

Although It Need some customization in regards to Offline Sync and Push Notification, Api calls logging per IP, Per User

Just thought, please comment / feedback about Idea

**Comment by volkanceylan** [comment]
Hi Samdubey,

We are already using Serenity as mobile backend and have no problems. For other nice-to-have features, it could be, there are some plans, but not prioritized and i don't have a timeline.

Serenity will probably have a paid mobile version, though not decided yet.

**Comment by samdubey** [comment]
Thanks for your views
