### ISSUE TITLE
Input string incorrect in inplaceadd

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#842]
Hi.

I have added for testing, in Serene Orders form, the inplaceadd for CustomerEditor. 

```cs
        [..., CustomerEditor(InplaceAdd = true)]
        public String CustomerID
        {
            get { return Fields.CustomerID[this]; }
            set { Fields.CustomerID[this] = value; }
        }
```

![cattura3](https://cloud.githubusercontent.com/assets/16304015/16371332/4e25be7c-3c46-11e6-83a8-dcc1568752ce.PNG)

CustomerID is nvarchar(5). When I try to click on the edit button of CustomerID field, this message is displayed:

![cattura1](https://cloud.githubusercontent.com/assets/16304015/16371257/b368c816-3c45-11e6-93ce-f53f678cbc6a.PNG)

In browser develpment tools the request content for retrieve customer is:
 
![cattura2](https://cloud.githubusercontent.com/assets/16304015/16371299/1809281a-3c46-11e6-9700-e96de7c70063.PNG)

If I change the code of  class CustomerLookup from

```cs
        public CustomerLookup()
        {
            // IdField = CustomerID
            IdField = CustomerRow.Fields.CustomerID.PropertyName;
            [...]
        }
```

to 

```cs
        public CustomerLookup()
        {
            // IdField = ID
            IdField = CustomerRow.Fields.ID.PropertyName;
            [...]
        }
```

the edit button it's ok, but in update data of ther form this is shown:

![cattura4](https://cloud.githubusercontent.com/assets/16304015/16371551/85e2552c-3c47-11e6-962c-184d6f0ba0bd.PNG)

This becouse the ID is take for CustomerID field.
Can I specify an ID to use to open the form and an ID (in this case CustomerID) to use for the update data?

**Comment by volkanceylan** [comment]
No, IDField is single

**Comment by Estrusco** [comment]
Ok, thanks.
