### ISSUE TITLE
Value with lookupinclude not showing chrome

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#844]
dear all,

I have properties with lookupinclude, not showing in chrome, already rebuild solution, and tranform T4 template in VS 2015, it's only occured in some properties not all.

![capture7](https://cloud.githubusercontent.com/assets/6382278/16402608/af1cc29e-3d17-11e6-9008-4cc0bffe9872.PNG)

![capture8](https://cloud.githubusercontent.com/assets/6382278/16402718/d14980b8-3d18-11e6-8819-974402d5a432.PNG)

Regards

**Comment by volkanceylan** [comment]
Its probably null

**Comment by fazanan** [comment]
Solved. Should be declare Column in properties.
