### ISSUE TITLE
Issue with SQL joins generated on Row

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#845]
I have a problem that I'm experiencing that I cannot seem to be able to figure out with the SQL joins that are being created on a detail row in my master/detail relationship. The structure is like so:

EntityRow | Relationship
------------- | --------------
WorkOrderRow | Master
OrderDetailRow | Detail
ItemRow | FK on Detail, similar to PersonRow in tutorial
LocationRow | FK on Detail, same as ItemRow

For further illustration, ItemRow itself has three FK table fields, to ItemTypeRow, ItemColorRow, and ItemLengthRow. Now, I'm able to add a view field to ItemRow that does a string concatenation of the textualfields for each of these entities, like so:

```cs
[DisplayName("Description")]
[Expression("(it.[ItemTypeDesc] + ' ' + ic.[ColorName] + ' ' + il.[Length])")]
public String Description
{
    get { return Fields.Description[this]; }
    set { Fields.Description[this] = value; }
}
```

The problem I've consistently encountered is trying to get this description to show up in my OrderDetailEditor class. If I specify in my columns to only display the `public Int32 Item { get; set; }` for the ItemId, they show up upon saving in the OrderDetailEditor grid columns. However, when I try to use the `public String ItemName { get; set; }` view field in the columns, I get an error from SQL when it goes to load the WorkOrderGrid:

> The multi-part identifier "jItem.ItemType" could not be bound.
> The multi-part identifier "jItem.ItemColor" could not be bound.
> The multi-part identifier "jItem.ItemLength" could not be bound.
> The multi-part identifier "jItem.ItemType" could not be bound.
> The multi-part identifier "jItem.ItemColor" could not be bound.
> The multi-part identifier "jItem.ItemLength" could not be bound.
> The multi-part identifier "jItem.Description" could not be bound.

I checked the debug logs in App_Data to see what the SQL looked like that Serenity generated, and this is what I found:

```sql
SELECT 
T0.[OrderDetailId] AS [OrderDetailId],
T0.[Ticket] AS [Ticket],
T0.[Item] AS [Item],
T0.[Quantity] AS [Quantity],
T0.[Location] AS [Location],
T0.[Inventoried] AS [Inventoried],
jItem.[ItemType] AS [ItemType],
jItem.[ItemColor] AS [ItemColor],
jItem.[ItemLength] AS [ItemLength],
it.[ItemTypeDesc] AS [ItemTypeDesc],
ic.[ColorName] AS [ItemColorName],
il.[Length] AS [ItemLengthName],
jItem.[Description] AS [ItemName],
jLocation.[Description] AS [LocationDescription] 
FROM [inv].[OrderDetail] T0 
LEFT JOIN [inv].[ItemType] it ON (it.[Id] = jItem.[ItemType]) 
LEFT JOIN [inv].[ItemColor] ic ON (ic.[Id] = jItem.[ItemColor]) 
LEFT JOIN [inv].[ItemLength] il ON (il.[Id] = jItem.[ItemLength]) 
LEFT JOIN [inv].[Location] jLocation ON (jLocation.[LocId] = T0.[Location]) 
WHERE ((T0.[Ticket] IN (@p1))) 
ORDER BY T0.[OrderDetailId]
```

It seems like for some reason the FK on Item, which has an alias of "jItem" isn't created by Serenity, which would explain why the ItemType, ItemColor, ItemLength, and Description identifiers couldn't be bound. I have defined the relationship correctly, it appears, as it looks nearly exactly the same as the way I defined the FK relationship on Location:

```cs
        [DisplayName("Item"), ForeignKey("[inv].[Item]", "ItemId"), LeftJoin("jItem")]
        [LookupEditor(typeof(ItemRow))]
        public Int32? Item
        {
            get { return Fields.Item[this]; }
            set { Fields.Item[this] = value; }
        }

        [DisplayName("Location"), ForeignKey("[inv].[Location]", "LocId"), LeftJoin("jLocation"), TextualField("LocationDescription")]
        [LookupEditor(typeof(LocationRow))]
        public Int32? Location
        {
            get { return Fields.Location[this]; }
            set { Fields.Location[this] = value; }
        }
```

Any idea why Serenity isn't generating the LeftJoin on ItemRow? I'm willing to bet that if the SQL had the following line:

```sql
LEFT JOIN [inv].[Item] jItem ON (jItem.[ItemId] = T0.[Item])
```

the whole thing would work.

**Comment by volkanceylan** [comment]
Your query seems like its generated from OrderDetailRow. Check if you have a jItem left join defined there. Having a join in one row doesnt mean it will be available in another.

**Comment by volkanceylan** [comment]
Please post full OrderDetailRow and your custom lookup if any, as a gist

**Comment by jsbUSMC** [comment]
Here is the link to the gist I've created with the OrderDetailRow class. I don't have a custom lookup defined as of now. [OrderDetailRow.cs gist](https://gist.github.com/jsbUSMC/ccf149bc7bdce02e0ef9f622383d1c43)

In the gist, you'll see above my ItemType, ItemColor, and ItemLength properties that I have single line comments with random strings preceded by a comma. Those strings are from the overload of the LeftJoin attribute, and when I had them in my attribute after running the code I was receiving an exception that stated "Syntax error encountered near '='. "

**Comment by volkanceylan** [comment]
Item property name is the problem. Somehow it is treated differently. Probably a special name.

Use it like this:

```
        [DisplayName("Item"), Column("Item"), ForeignKey("[inv].[Item]", "ItemId"), LeftJoin("jItem")]
        [LookupEditor(typeof(ItemRow))]
        public Int32? ItemID
        {
            get { return Fields.ItemID[this]; }
            set { Fields.ItemID[this] = value; }
        }
```

**Comment by jsbUSMC** [comment]
Thank you @volkanceylan , this seems to have fixed the issue with multi-part identifiers being unbound. However, after the fix like you suggested, trying to load the grid for WorkOrder or OrderDetail crashes the application with the exception being `Invalid column name "Description"`. This is from the Expression that I have placed above ItemName property, bringing it in as a view field from ItemRow. It is itself, however,  a view field on ItemRow as well. It is a concatenated string.

**Comment by jsbUSMC** [comment]
Ok...I figured out what I needed to do. For the Expression, I needed to re-create the same Expression that I did for ItemRow. It now works like a charm. Thank you!

**Comment by slang123** [comment]
I had the same issue and the problem was that I had to add IncludeColumns on the master detail list. Hope this helps someone else.
