### ISSUE TITLE
Records inserted via database aren't shown in lookup

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#846]
Hi everyone;

I'm running a scheduled web service that synchronizes one of my web site's tables with an MS CRM table (directly via data base). I use this table as a lookup in another row. Everything looks fine, except that new added records are not displayed in the lookup unless I update them (via the app) or I rerun the website. Is there a way around it? Thanks.

**Comment by samdubey** [comment]
If you check Multitenancy tutorial for handling Lookups
You will find setting timeout to -1 does the trick
It doesn't cache the lookup data

**Comment by awesomegithubusername** [comment]
Thanks a lot  @samdubey. I added "Expiration = TimeSpan.FromDays(-1);" (The funny thing is,I used it before. For some reason I forget it ) Although a refresh is still required, I don't have to update inserted records anymore.
