### ISSUE TITLE
Load grid by selected value when first load

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#847]
Hi Jaiq,

I have the solution using satarelle as this ticket #727 , but how you can do it in typescript?
Please help.

Regards

**Comment by jsbUSMC** [comment]
I believe that you can do this the following way, though I may be wrong. Add this method to your EntityGrid.ts class:

```ts
protected getButtons()
{
    var buttons = super.getButtons();

    // create your lookup lookup editor here
    myWidget = Widget.Create<LookupEditor>( ... );

    myWidget.init( e => e.Value = newValue; );
}
```

getButtons() method is analogous to the `protected override void CreateToolbarExtensions()` method in Salterelle, and the init method will initialize the editor element with a default value.

**Comment by fazanan** [comment]
It works thanks for your help.
