### ISSUE TITLE
[Question] Upgrade to ASP.NET Core 1.0

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#848]
Since microsoft released Asp.Net Core 1.0 

Looking forward to have Serenity upgrade to it 

https://blogs.msdn.microsoft.com/webdev/2016/06/27/announcing-asp-net-core-1-0/?utm_source=twitterfeed&utm_medium=facebook

I think we need to consider other dependent libraries upgrade before we upgrade Serenity App Framework.

**Comment by jsbUSMC** [comment]
Big issue I see here, even though it is not a dependent library, is lack of support for SignalR. It's a great library for abstracting out the connection plumbing for real-time functionality - like notifications, newsfeeds and streams, things like that.

**Comment by volkanceylan** [comment]
I'll wait for VS 15 (VS 2017?). All these .netstandard16 dotnetcore dnx451, project.json, xproj, is killing my mind. And docs are worse than zero, full with out of date information. I'm happy with .NET framework.

**Comment by bensonokiora** [comment]
Waiting for ASP CORE 1.0 serenity version
