### ISSUE TITLE
Creating user signup / registration page in Serenity

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#85]
Dear Volkanceylan,

how do we create User Signup / Registration Page for Serenity

Do we need to custom create Html page or should we use Serenity App Template for the same

**Comment by volkanceylan** [comment]
You need a custom page like forgot password. For creating user, take a look at AuthenticationService and how it creates them for LDAP/AD. Or you may wait for me to write one sample, have some plans.

**Comment by volkanceylan** [comment]
1.8.18.1 has sign up sample now.
