### ISSUE TITLE
default value for quickfilter

### ISSUE THREAD

**Issue by nmajeed** [volkanceylan/Serenity#850]
is it possible to set default/initial value for a quickfilter (dropdownlist) from a querystring?

**Comment by volkanceylan** [comment]
There is already such a sample in orders page, from dashboard

**Comment by nmajeed** [comment]
sorry, i think my question was not clear.. in same example, I would like to pass  employeeId in querystring so, it select the employee in dropdown  and filter the grid as well.

**Comment by volkanceylan** [comment]
Did you click more info links from Dashboard

**Comment by nmajeed** [comment]
got it - Thanks!
