### ISSUE TITLE
Serenity Code Generator Give Empty View

### ISSUE THREAD

**Issue by mohammad0011** [volkanceylan/Serenity#851]
Hi, 
First of all, Thank you very much for this great project.

I tried to follow you Movie Database Tutorial, everything goes well but when I navigate to "MovieData/Movies" I get an empty view

The following exception thrown 

"0x800a138f - JavaScript runtime error: Unable to get property 'MoviesGrid' of undefined or null reference"

**Comment by volkanceylan** [comment]
Install TypeScript 1.8

**Comment by mohammad0011** [comment]
Thanks :)
