### ISSUE TITLE
MultiTenant Lookup editor - Input String incorrect format

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#852]
I've been playing around with this one and could use some outside help. I keep getting an "input string is in incorrect format" error. I cant seem to figure out the fix. 

I've set up as a multitenant. I have a table which acts as my master table. At that table I have a TenantId that is defaulted to 1, thus only one tenant can see data in that table. I also have another ID, CustomerID, which I have joined to the TenantId from the tenants table. I use this so that I can use the CustomerID to designate the TenantId in the SqlViews thus, create reports which clients can only see the data pertaining to them. Those views work perfectly. 

I created the following lookup script to deal with the search box: 

 [LookupScript("FMCorp.MatrixCustomerName")]
    public class MatrixCustomerNameLookup : MultiTenantRowLookupScript<MyRow>
    {
        Field fld = MyRow.Fields.CustomerName;

        public MatrixCustomerNameLookup()
        {
            IdField = TextField = fld.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            query.Distinct(true)
                .Select(fld)
                .Where(
                    new Criteria(fld) != "" &
                    new Criteria(fld).IsNotNull()
                    );
            AddTenantFilter(query);
        }
        protected override void ApplyOrder(SqlQuery query) { }
    }

Matrix row designates the fields affected like this: 

   [DisplayName("Customer Id"), ForeignKey("[dbo].Tenants", "TenantId"), LeftJoin("cust"), Width(100), AlignCenter] //Join TenantID from Tenant Table to Matrix Table. Identifier is "cust"
        [LookupEditor("Administrative.Tenants")]//Added for  DropBox type Lookup
        public Int32? CustomerId
        {
            get { return Fields.CustomerId[this]; }
            set { Fields.CustomerId[this] = value; }
        }
        [DisplayName("Customer Name"), Expression("cust.TenantName"), Width(100), AlignCenter] //Calls upon Name column from Customer Table. 
        [LookupEditor(typeof(Script.MatrixCustomerNameLookup))]
        public String CustomerName
        {
            get { return Fields.CustomerName[this]; }
            set { Fields.CustomerName[this] = value; }
        }

I then added the lookup script to the columns table for customer name but I also hid the CustomerId

. 
        //Client and Location Information
        [Hidden]
        public Int32 CustomerId { get; set; }
        [EditLink, LookupEditor(typeof(Script.MatrixCustomerNameLookup)), QuickFilter]        
        public String CustomerName { get; set; }

**Comment by Estrusco** [comment]
Check the `IdField = TextField = fld.PropertyName;` where fld is `MyRow.Fields.CustomerName`. Second my opinion there is an error.

The IdField should be fld.CustomerId

**Comment by sayuga** [comment]
I did attempt that. (see sample below) but that just creates the drop down list but there is no dynamic search. I can't figure out why. I believe it has something to do with the transition of the Id field after it has been through the Join but I can't seem to figure it out. I feel I'm overlooking something basic. 
 
[LookupScript("FMCorp.MatrixCustomerName")]
public class MatrixCustomerNameLookup : MultiTenantRowLookupScript
{
Field fld = MyRow.Fields.CustomerName;
Field fldtwo = MyRow.Fields.CustomerId;

    public MatrixCustomerNameLookup()
    {
        TextField = fld.PropertyName;
        IdField = fldtwo.PropertyName;
    }

    protected override void PrepareQuery(SqlQuery query)
    {
        query.Distinct(true)
            .Select(fld)
            .Where(
                new Criteria(fld) != "" &
                new Criteria(fld).IsNotNull()
                );
        AddTenantFilter(query);
    }
    protected override void ApplyOrder(SqlQuery query) { }
}

**Comment by Estrusco** [comment]
But your base class is  MultiTenantRowLookupScript.

It should be MultiTenantRowLookupScript<xyzRow>

In addition to this I think you must call the base.PreparayQuery

 ```cs
protected override void PrepareQuery(SqlQuery query)
{
            base.PrepareQuery(query)
 ```
The PrepareQuery of base class MultitenantRowLookupScript is

  ```cs
protected override void PrepareQuery(SqlQuery query)
{
            base.PrepareQuery(query);
            AddTenantFilter(query);
}
 ```

so your method must

 ```cs
protected override void PrepareQuery(SqlQuery query)
{
       base.PrepareQuery(query);
 
       query.Distinct(true)
           .Select(fld)
           .Where(
                new Criteria(fld) != "" &
                new Criteria(fld).IsNotNull()
            );
    //AddTenantFilter(query);
}
 ```

**Comment by sayuga** [comment]
hmm....I tried it out but still no good. I'm beginning to think there is an alternative conflict elsewhere. 

For the sake of being thorough though: 

The abstract class for MultiTenant Row, does implement the base class already. I've emulated directly from the manual. 

namespace FMCDashboardv3.Administrative.Script
{    
    using Serenity;
    using Serenity.Data;
    using Serenity.Web;
    using System;


    public abstract class MultiTenantRowLookupScript<TRow> :
        RowLookupScript<TRow>
        where TRow : Row, IMultiTenantRow, new()
    {
        public MultiTenantRowLookupScript()
        {
            Expiration = TimeSpan.FromDays(-1);
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            AddTenantFilter(query);
        }

        protected void AddTenantFilter(SqlQuery query)
        {
            var r = new TRow();
            query.Where(r.TenantIdField == ((UserDefinition)Authorization.UserDefinition).TenantId);
        }

        public override string GetScript()
        {
            return TwoLevelCache.GetLocalStoreOnly("MultiTenantLookup:" +
                    this.ScriptName + ":" +
                    ((UserDefinition)Authorization.UserDefinition).TenantId,
                    TimeSpan.FromHours(1),
                new TRow().GetFields().GenerationKey, () =>
                {
                    return base.GetScript();
                });
        }
    }
}

Additionally, If I call upon it in the search all I get is the same outcome with no dynamic search plus it duplicates the entries instead of providing distinct values since it is calling upon itself and when I do a selection I get the same error as I did to begin with. 

      public class MatrixCustomerNameLookup : MultiTenantRowLookupScript<MyRow>
    {
        Field fld = MyRow.Fields.CustomerName;
        Field fldtwo = MyRow.Fields.CustomerId;
        
        public MatrixCustomerNameLookup()
        {
            IdField =fldtwo.PropertyName;
                TextField = fld.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            base.PrepareQuery(query);
            query.Distinct(true)
                .Select(fld)
                .Where(
                    new Criteria(fld) != "" &
                    new Criteria(fld).IsNotNull()                   
                    );
            AddTenantFilter(query);
        }

        protected override void ApplyOrder(SqlQuery query) { }
    }
}

![image](https://cloud.githubusercontent.com/assets/16759829/16521711/af2700fa-3f66-11e6-97cb-5eb34347a673.png)


I have an alternative plan I'm going to pursue for now. I had made a lot of changes to the tables and code so I'm going to give it an etch-and-scetch moment and rebuild that section with a more relevant setup. I think that may help. It'll at least make sure I don't have excess code that may be conflicting. 


Side Note: I do have the base class set to <xyz> but I just noticed that when I paste the code snip in, if I don't remove the [LookupScript(xyz)], it removes the <xyz> from the post.

**Comment by Estrusco** [comment]
Da not reapeat the AddTenantFilter(query) in overraided method of MatrixCustomerNameLookup . This is already in PrepareQuery of MultiTenantRowLookupScript

**Comment by sayuga** [comment]
When I remove it I still get the same situation. Here is the iteration of the code I tried most recently: 

public class MatrixCustomerNameLookup : MultiTenantRowLookupScript<MyRow>
    {
        Field fld = MyRow.Fields.CustomerName; //Is Joined field. 
        Field fldtwo = MyRow.Fields.CustomerId;
        
        public MatrixCustomerNameLookup()
        {
            //IdField = TextField = fld.PropertyName;// original
            IdField = fldtwo.PropertyName;
            TextField = fld.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            
            query.Distinct(true)
                .Select(fld)
                .Where(
                    new Criteria(fld) != "" &
                    new Criteria(fld).IsNotNull()                   
                    );
            // AddTenantFilter(query);  //original
            base.PrepareQuery(query);
        }

        protected override void ApplyOrder(SqlQuery query) { }
    }

And here is my current output:

![image](https://cloud.githubusercontent.com/assets/16759829/16619319/a0f464e8-435b-11e6-87b7-acf90f4d822e.png)

Seeing as I seem to have trouble creating the advanced lookup I want I'll make due with the standard [LookupScript("Administration.Client")] option. I don't want to waste too much of your and others time with this. I'll probably notice what I was doing wrong, later when I'm not so focused on it. 

Thank you for all the advice though.,

**Comment by Estrusco** [comment]
Sorry, I forgot what is your problem. Your problem is that the lookup displays records of all tenant?
What is the result you want to achieve?
Post row.

My lookup code is simply this and work

```cs
namespace Project.Modules.Test
{     
     [LookupScript("Default.MyLookup")]
     public class MyLookup : MultiTenantRowLookupScript<MYRow>
    {
        public MyLookup()
        {
            IdField = MyRow.Fields.Id.PropertyName;
            TextField = MyRow.Fields.Description.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
              base.PrepareQuery(query);

              // Other work on query
             query.Where [etc etc]
        }
    }
}
```

If in row the ID field is  IIdField IIdRow.IdField and the Description field is StringField INameRow.NameField the constructor is not needed.

**Comment by sayuga** [comment]
My end result is: Take a field set with a LeftJoin() that feeds off of a secondary table, and create a lookup filter that still maintains Tenancy rules. 

I implemented the changes in the manual (https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/handling_lookup_scripts.html) such that the list should do exactly that. It works for regular, non-join, fields but if I use it on a field with a join, I can't seem to get it to work. It states that the query is incorrect. 

My guess is that since it's a join field, the query is attempting to pull the joint field from the primary table (where it doesn't exist) instead of from the secondary table. 

If I create a SqlView with the columns joint server side, I can make it work but it seems that when I do it through the new lookup script client side, it doesn't like it. 

 Example: 
PrimaryTable.CustomerId Field LeftJoins with SecondaryTable.Id and pulls in CustomerName

Admin User: 

CustomerId Field shows all Customer Names from the Secondary Table. Drop down box allows Admin user to select Customer Name and filter dynamically by customer name.

Customer User: 
CustomerId Field shows ONLY tenant specific Customer Name and hides any other customer names from the secondary table. Only selection available in drop down for Customer User is the Company for the user according to their TenantId.

**Comment by volkanceylan** [comment]
Where is your query
