### ISSUE TITLE
How can I add a radio button?

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#853]
How can I add a radio button control in serenity forms?

**Comment by jsbUSMC** [comment]
Perhaps create a new editor? I will also look into it as I could use this too now that I think about it.

**Comment by Estrusco** [comment]
Thanks for your answer. But I do not know well how to implement it

**Comment by Estrusco** [comment]
I have added a pull request with RadioButtonEditorAttribute.
