### ISSUE TITLE
Compatibility issue with chrome?

### ISSUE THREAD

**Issue by RRodrigoR** [volkanceylan/Serenity#854]
Hi,
Im learning to use serenity template, and was fantastic in IE, but when I try to test in Chrome, some grid dont show nothing but in footer detail show the correct number of registers (this work fine in IE). I was clean all temporaly files but nothing, what could be the problem? is a know issue?

Im using VS2015, framework 4.6.1

Thanks!

**Comment by volkanceylan** [comment]
I always use Chrome and no known issues. Something wrong in your side. Might be browser link.

**Comment by RRodrigoR** [comment]
I don't know whats happend , but I was re-install chrome and work correctly. thanks any ways! I will close thi issue.
