### ISSUE TITLE
SelectList from from Customlookup

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#855]
Is there any easy way to create a new SelectList from a lookup?

The reason i ask is that I am running into some very odd problems with Select2 passing values on a submit when a form is in a partial view. The model just won't seem to take a value other than 0 from the select2 box, So I figured I would try with Html.DropDownListFor

I already have Html.EnumDropDownListFor working so guessed it might be worth a shot.

I can build a new select list easily enough if I just make it myself, I just wondered if there was a way to call a lookup back to being an enumerable list.

**Comment by volkanceylan** [comment]
Q.getLookup

**Comment by solabar** [comment]
But isn't Q.getLookup a client side call? No way for this to be a server side rendered list allowing me to use Razor? Sorry if I am being thick here.

**Comment by volkanceylan** [comment]
Lookup scripts, as its name implies, is a script and its only accessible from client side. Anway, why not create a connection and select items from database with connection.List

**Comment by solabar** [comment]
That's what I did in the end. It's all good. Made a server lookup creator for my dynamic selects.
