### ISSUE TITLE
Best Place to put business logic using serenity

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#856]
What is best place to put business logic during saving of a record.

Is it in endpoints or in services.

For Example before raising a new bill for a customer we want to check already unpaid balance and if it beyond a certain limit, we would like to deny further billing till the payments for old bills are settled.

**Comment by Estrusco** [comment]
For business logic server side, the best place is Repository.

**Comment by mrajalko** [comment]
Can you please elaborate by giving some example (sample code)

**Comment by jsbUSMC** [comment]
Look at the base classes for RequestHandler types and you can see the kind of methods that you can override to perform any business logic needs.

**Comment by awesomegithubusername** [comment]
An example of overriding the AfterSave() method :   

    private class MySaveHandler : SaveRequestHandler<MyRow>
        {
             protected override void AfterSave()
            {
               base.AfterSave();

               var anotherRow=this.Connection.ById<xyzRow>(this.Row.field1);

               if (IsCreate)
                {
		    anotherRow.Field2 +=  this.Row.Field7;		
                }
                else
                {
		     anotherRow.Field2 +=  this.Row.Field7  - this.Old.Field7
                }

                Connection.UpdateById(anotherRow, ExpectedRows.One);
             }
        }

**Comment by volkanceylan** [comment]
Repository or service behavior

**Comment by mrajalko** [comment]
Thanks awsomegithubusername for your insight with example.
i would try it.
