### ISSUE TITLE
Add another type of captcha option than Recaptcha

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#86]
Can you show me a sample of how to  add  a richeditor replace of  textarea ?thanks.
Also ,how can I add validatecode ;In my Country ,we can't use google recapcha

**Comment by volkanceylan** [comment]
Just replace TextAreaEditor with HtmlContentEditor. I don't have a sample for other captcha systems yet. May add in future, todo+1

**Comment by ademc** [comment]
If you can not use google rechacha you can use different validation methods. Some of these talked about: https://www.usertesting.com/blog/2014/04/09/think-your-site-needs-captcha-try-these-user-friendly-alternatives/

Or simply ask as simple question to your visitors, for example 

"What is the most highest mountain in the world: **rest": 
"Solve this problem: 4 +9":

For achieve this: you'll be generate question and encrypted answer field in repository, and put it into response entity in retrive method.

**Comment by volkanceylan** [comment]
This goes into todo list
