### ISSUE TITLE
MasterDetailRelation and identity autoincrement PK on details

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#861]
Dear @volkanceylan,
I've a master-detail relation and both two table have a PK which is also an identity autoincrement.
Now for the master object I can get the "assigned" PK directly from the Row.Id field (in the after save method for example), so I was wondering if there is a similar way to retrieve also the id of the inserted details. I'm asking that because I need to track those events in a sort of synch mechanism.
I tried to put some breakpoint both in the detail endpoint and repository but apparently the MasterDetailRelation doesn't trigger/use such classes...
If I create a new master obj with a detail, in the aftersave method the following code:

    Row.xyzList[0].Id
is always null (where Id is the PK autoincrement identity field).

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Write a behavior for details

**Comment by marcobisio** [comment]
Ok I need to write a custom one...
Thanks!
Bye
