### ISSUE TITLE
Error ("entityId field is required!")  when clicking on "Apply Changes" before saving (GUID ID field)

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#863]
Hi;

I'm getting this error : "entityId field is required!" when creating a new record and clicking on "Apply changes" before saving. The record is created, the dialog is still open and if I click on "Apply changes" again or on "Save" another record gets created . No problem if I click on "Save" first. The type of the ID field is GUID:
![untitled1](https://cloud.githubusercontent.com/assets/13295503/16541357/78d1a1dc-4078-11e6-94fb-6ef7e108c677.png)
 
![untitled2](https://cloud.githubusercontent.com/assets/13295503/16541360/935b1d6c-4078-11e6-8c6d-5696d22a39f8.png)

Stackify:
![untitled4](https://cloud.githubusercontent.com/assets/13295503/16541393/2bac711a-4079-11e6-8f1c-bf4fec70d4da.png)

![untitled3](https://cloud.githubusercontent.com/assets/13295503/16541371/bb99c90e-4078-11e6-9187-f4c26fa4e5f1.png)

**Comment by volkanceylan** [comment]
Your ID field is guid. Serenity has no way to get it from database. So you should set guid field manually.

**Comment by awesomegithubusername** [comment]
Hi volkan;

Should I set the field in the code? It's already set in Sql:
      [Id] uniqueidentifier DEFAULT (newid()) NOT NULL

**Comment by volkanceylan** [comment]
Yes

**Comment by awesomegithubusername** [comment]
I wrote this and it worked. Just wondering if it's the right way to do it:

```c#

       private class MySaveHandler : SaveRequestHandler<MyRow> 
      {

            protected override void BeforeSave()
            {
                base.BeforeSave();
                Row.Id = Guid.NewGuid();

            }

        }

**Comment by volkanceylan** [comment]
Yes, it's the right way. Better is not to use GUIDs at all
