### ISSUE TITLE
Filter Grid Data onload where filter value from max(field) server side

### ISSUE THREAD

**Issue by zerodev** [volkanceylan/Serenity#864]
what is the best way to Filter Grids Data on load where filter value from max(field) server side
the Grid is on a tab in a master details form 

If am going to use setEquality then I need to get the latest value in the field to filter on, same issue when  using       request.Criteria = Serenity.Criteria

![capture](https://cloud.githubusercontent.com/assets/728937/16541557/ba68a3f0-408e-11e6-8a14-52668b1bc688.PNG)

**Comment by volkanceylan** [comment]
Sorry i don't have time to solve puzzles :)

**Comment by zerodev** [comment]
even i did not understand what i wrote :-1:
