### ISSUE TITLE
What is difference between ICaptureLogRow and IAuditLogRow

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#865]
Hi

What is difference between ICaptureLogRow  and IAuditLogRow?
I can see sample for ICaptureLogRow , which is use to create a audit log for all changes. What is different with IAuditLogRow? Is there any sample for this?

Thanks

**Comment by ramveersgh** [comment]
Hi @volkanceylan 
I am writing my custom behaviour to capture logging in single table (Instead of creating table for each master table).
I have written it and it seems to be working. When I rename my audit handler to IAuditLogRow then i realize that this is already available in serenity. So i changed my handler name.
How is it different from ICaptureLogRow? Does it can be use in same way as ICaptureLogRow?

Thanks in advance!

**Comment by jsbUSMC** [comment]
IAuditLogRow will log the UserID and date of insert/update of records in your table. ICaptureLogRow does the same, however it allows you to define which fields to capture, so you can see which content is changed/inserted and at what time, by whom. ICaptureLogRow though does not update the rows itself, but captures the data and logs to a separate db table.

**Comment by ramveersgh** [comment]
Thanks @jsbUSMC 
But I think that is ILoggingRow not IAuditLogRow which is use to update UserID and date of insert/update of records in master table. 
If I am wrong then what is difference between  ILoggingRow and IAuditLogRow?

**Comment by jsbUSMC** [comment]
Oh I was confused then. I just looked at the code for IAuditLogRow and see that it is indeed different. I'm not sure when it is better to use either one. Perhaps @volkanceylan will better be able to explain this

**Comment by volkanceylan** [comment]
AuditLog is similar to CaptureLog but stores old and new values as JSON, and it is possible to use one table for all tables in database. It was working three years ago in a few projects but Serenity went through so many changes, so it needs to be tested. I'm not sure if it will work as is. Also, both methods has no change viewer atm.

**Comment by ramveersgh** [comment]
Thanks @volkanceylan for the explanation.
