### ISSUE TITLE
T4 transformation template problem 

### ISSUE THREAD

**Issue by caitingting** [volkanceylan/Serenity#866]
hello,Error prompted when I converted the T4 template :Can't determine path of TSC.exe that is required to compile generated TypeScript files!

**Comment by Estrusco** [comment]
Install typescript

**Comment by caitingting** [comment]
how to Install typescript？I installed the TypeScript_Dev12 before, and later used the VS15, can be used before, today suddenly can not.

**Comment by volkanceylan** [comment]
http://www.typescriptlang.org/

Wish you could use google

**Comment by caitingting** [comment]
I installed TypeScript_Dev14Full.exe.I use google.But that is the error.

**Comment by volkanceylan** [comment]
install 1.8+ are you reading guide?

**Comment by caitingting** [comment]
I'm sorry, I didn't say it clearly. I install 1.8.6,but that is the error.

**Comment by caitingting** [comment]
The problem solved, I put the VS to reinstall it. 
Sincerely thank you !
