### ISSUE TITLE
How to add multiple  Movie Genres

### ISSUE THREAD

**Issue by ChenZhaobin** [volkanceylan/Serenity#87]
I do after the gitbook https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/adding_movie_genres.html step by step and success to implement the single movie genres,but how can I select more than one genre for my test

**Comment by ChenZhaobin** [comment]
I got it ;Just use List<Genre> in MovieRow,then attribute it with a multiselect widget ;how poweful!

**Comment by volkanceylan** [comment]
You are right. It might work like detail list sample but actually a tagging Select2 editor would be more useful. I'll add the sample to tutorial.

**Comment by jsbUSMC** [comment]
@ChenZhaobin would you mind providing a sample of the code you used to do this?

**Comment by volkanceylan** [comment]
@ChenZhaobin, @jsbUSMC see customer representatives sample in 1.9.3 template
