### ISSUE TITLE
Code sharing for audit log in single table.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#874]
Hi

I was having a requirement to generate report for work done by user on daily basis and the details of actions (Insert/Update/Delete) by user. Initially i was using ICaptureLogRow but i have so many table and i have to create a copy of each table and a log class for each module. My table also changed frequently so maintaining  log table and log class was becoming pain for me. So i created custom behaviour to log all changes in single table.

I am sharing code by thinking that it may be helpful for someone else.
DBScripts for Table, Stored Procedure and Code file is attached.
DB Scripts
[SQLServer_AuditScript.txt](https://github.com/volkanceylan/Serenity/files/346533/SQLServer_AuditScript.txt)

Code File
[AuditBehavior.txt](https://github.com/volkanceylan/Serenity/files/346536/AuditBehavior.txt)

**How To Use**
1. Run the DBScript in your SQL Server Database
2. If there is already a column named Identity then inherit your RowClass with IAuditLog
Ex: 
```
public sealed class UserRow : LoggingRow, IIdRow, INameRow, IIsActiveRow, IAuditLog
{
}
```
3.  If you want to save any other column value as RowId in AuditTable then use following 
```
public sealed class UserRow : LoggingRow, IIdRow, INameRow, IIsActiveRow, IExAuditLog
{
         public Int32Field UserId
        {
            get { return Fields.IdField; }
        }
}
```

Here is screenshot of log table
![changelog](https://cloud.githubusercontent.com/assets/2145218/16565080/a044b518-4228-11e6-8bb6-ae1121ad15b2.png)

Hope this will be helpful for someone. Please let me know if you find any improvement in this or have any suggestions.

**Comment by awesomegithubusername** [comment]
Thanks for sharing @ramveersgh. How do you know which row got deleted?
P.S: Could you move this thread to the Wiki?

**Comment by ramveersgh** [comment]
I am inserting primary key in the log table for deleted row. Offcourse this primary key will have log for insert and updated too. So RowId is enough to have for delete log.

I never created any page on wiki but i will try to add it in Wiki if @volkanceylan verify and allow me to add this.

**Comment by volkanceylan** [comment]
Thanks for sharing @ramveersgh. Actually yours is similar to AuditLog but i didn't test it for long time. You should share your solution in wiki. Another option is SQL Server Change Data Capture (CDC).

**Comment by ramveersgh** [comment]
Thanks @volkanceylan 
I also thought that IAuditLogRow should be similar to what i did. I will share my solution to wiki and will close this.
I am using SQL Express version which does not support CDC.

**Comment by ramveersgh** [comment]
Add the Wiki Page for this.
https://github.com/volkanceylan/Serenity/wiki/Audit-Log-for-Insert,-Update-and-Delete-using-Single-Table.

**Comment by awesomegithubusername** [comment]
Good job @ramveersgh. Much appreciated.

**Comment by ramveersgh** [comment]
Thanks @awesomegithubusername !!

**Comment by Qasem2022** [comment]
great effort
Thank you for posting the code

But when I apply the code, I see an error in the process of deleting and adding
(Object reference not set to an instance of an object)
can you help
Also, the class mentioned in Namespace (http://using IBS_ACOC.Modules.Common.Enums;) I don't know what it is / can it be published?
There is an error in Namespace (//using IBS_ACOC.DAL;) / Is it related to the error?

Once again thank you

hope for help

**Comment by nahidulislam-cse15** [comment]
@ramveersgh   When this procedure will call ?or  from where to call this procedure?
