### ISSUE TITLE
Serene throwing 'Error establishing a database connection' when deployed

### ISSUE THREAD

**Issue by andrecsa** [volkanceylan/Serenity#875]
Hello there,
I've got a local Serene web app connecting to MySql databases hosted in GoDaddy. Everything works fine when I'm running the web app locally in the debugger, even connecting to the remote databases.
But when I deploy the app to GoDaddy, which is also my hosting provider, when accessing the website I only see the message 'Error establishing a database connection'. 

![screen shot 2016-07-05 at 8 10 00 am](https://cloud.githubusercontent.com/assets/15334159/16570439/5ad9b194-4288-11e6-81c4-eaf69117fc5d.png)

I've tried googling the issue, but most of the results are related to WordPress permalink. Couldn't find anything related to what I'm experiencing.

Any comments will be appreciated.

Thanks,
-Andre.

**Comment by Estrusco** [comment]
Check connectionStrings int your web.config

**Comment by andrecsa** [comment]
Connection strings are correct in the web.config. As I mentioned, it all works fine when running on the debugger.

**Comment by Estrusco** [comment]
The connection string could be different from debugging and deployed version. However, the problem can be either the connection string or the DB server.
There are too few information to understand.

**Comment by andrecsa** [comment]
Thanks for your input, @Estrusco.
But yeah, I can connect to the databases using MySql Workbench and the hostname and credentials from the connection strings of the deployed web.config.
Which other information would you need? I'm unsure what else I could try...
Thanks anyways.

**Comment by volkanceylan** [comment]
I think you should set up some page where you only open a connection standard way. This is not some problem related to Serenity, and i guess there is not much MySql / GoDaddy users that can help you here. So after getting exception details, better ask in their forums.

**Comment by jsbUSMC** [comment]
Could your connection driver somehow be at fault? Is it possible that it is available locally but not on your remote server?
