### ISSUE TITLE
PhoneEditor 

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#877]
What is the syntax for the Serenity [PhoneEditor] attribute. If I add it like any other attribute it fails the validation and gives a message in another language. From the source code it looks like maybe it was hardcoded for Turkish?  Or should I be using [Phone] from dataanotations?

**Comment by volkanceylan** [comment]
Yes, PhoneEditor in Serenity namespace was written for Turkish phones. It was not intended to be used by others yet. You might use masked editor or use something similar to Northwind Phone editor in Serene.

**Comment by samdubey** [comment]
Can we have PhoneEditor with Format Specifier like (###) ### #### ?
