### ISSUE TITLE
Problem creating new poject in VS2015

### ISSUE THREAD

**Issue by dcvikl** [volkanceylan/Serenity#88]
Hi,
I have just downloaded the template and installed it in VS 2015 Community Edition. 
Following the Developer Guide and try to create a new Project with the Serene Template I get the error: "A problem was encountered creating sub project "MovieTutorial.web".

Any clues why?

**Comment by volkanceylan** [comment]
Do you have any errors in VS console, log etc. except this message? I also use that edition.

**Comment by dcvikl** [comment]
Sorry for my late response ... Just tried to install it at home on VS2015 Enterprise and all is working. Must be the computer at work.

I'll try on my Laptop and see what will happen.
