### ISSUE TITLE
Conditionally show Quick Filter

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#880]
whether we can show Quickfilter only if more then one item present in quickfilter.
otherwise it should be invisible ( for one or zero items ).

regards
Shailesh

**Comment by Estrusco** [comment]
You can override createQuickFilters or createQuickSearchInput in xyzGrid.ts

```js
protected createQuickFilters() {
            super.createQuickFilters();

           // your code
}

protected createQuickSearchInput() {
           if (yourtest == true)
                 return;
}
```

**Comment by shaileshbc** [comment]
Dear Estrusco,
There are more than one quick filter so
i tried with following code, but it didn't work.
`protected createQuickFilters() {
            super.createQuickFilters();
            var institutefilter = this.findQuickFilter(Serenity.LookupEditor, Master.ClassRoomRow.Fields.InstituteName);
            if (institutefilter.items.length <= 1) {
                institutefilter.destroy();
            //    institutefilter = null;
            }

        }`
any suggestion.
regards
Shailesh

**Comment by Estrusco** [comment]
This work for me

```js
[...]
protected myLookupQuickFilter: Serenity.LookupEditor;

protected createQuickFilters() {
    super.createQuickFilters();

    this.myLookupQuickFilter= this.findQuickFilter(Serenity.LookupEditor, fld.IdForLU);

    if (this.myLookupQuickFilter.items.length <= 1)
        this.myLookupQuickFilter.element.parent().remove("*");
}
```

**Comment by shaileshbc** [comment]
thanks for your quick response.
This solves my problem
regards
shailesh

**Comment by shaileshbc** [comment]
thanks for your quick response.
This solves my problem
regards
shailesh
