### ISSUE TITLE
LookupFilter for Checkboxes (booleans) 

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#881]
I've seen the multiple lookup and the cascade lookup can be implemented using the QuickFilterOption. I was wondering if there is an implementation for the 3 iterations of a boolean. (Null, True and False). I'm reading through the documentation and I don't see it. 

Ideally I wanted to make a checkbox button filter for a set of values. I currently use: 

public class MatrixHasAlarmLookup : MultiTenantRowLookupScript<MyRow>
    {
        Field fld = MyRow.Fields.Alarm;

        public MatrixHasAlarmLookup()
        {
            IdField = TextField = fld.PropertyName;
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            query.Distinct(true)
                .Select(fld)
                .Where(new Criteria(fld).IsNotNull());

            AddTenantFilter(query);
        }
        protected override void ApplyOrder(SqlQuery query) { }
    }

This let's me do a drop down search box with the true or false options and I make the field not nullable but I have multiple fields like these and they become bulky. 

I'm planning on writing a lookup script but figured I'd ask first.

**Comment by volkanceylan** [comment]
See how order state filter in Orders work

**Comment by sayuga** [comment]
Thank you for the quick response but let me be a bit more explicit on what I meant. I am looking to change the look of the filter box that is used, not the filter itself.  

I have a total of 19 boolean fields that I use  for designating whether a entry uses a particular item (argon, compressed air, nitrogen, etc) But each of these give a fairly large box for each option and they start becoming bulky on the quick filter. 

![image](https://cloud.githubusercontent.com/assets/16759829/16652868/58d32fc6-441b-11e6-88ad-2fc5b3022d84.png)


What I would like is to replace the drop down box look with a more compact checkbox look, or similar there-of, that would emulate the checkbox entry used when adding entries. This would give me a cleaner look.

**Comment by volkanceylan** [comment]
Make them smaller with CSS. I can't help with custom solutions.

**Comment by sayuga** [comment]
That's alright. My original question was just asking if there was already something in place. I was planning on making a custom solution myself but I didn't want to do it if there was already a solution I didn't know of. Thank you for the info.

**Comment by volkanceylan** [comment]
I would use advanced filter probably. Your quick filter is too loaded.
