### ISSUE TITLE
Custom folders for assets (css, js, fonts)

### ISSUE THREAD

**Issue by tb-mtg** [volkanceylan/Serenity#882]
If i move the either **content** or **scripts** folder **_SiteInitialization.cs_** throws an exception.

Can the client-side static content folders (**_/content_**, **_/fonts_** & **_/scripts_**) be moved to custom locations so that the following project folder structure would be possible?

\Assets\
\Assets\\**Site**\
\Assets\\**Site**\Css (currently in **_/content/site/_** folder)
\Assets\\**Site**\Fonts (currently in **_/fonts_** folder)
\Assets\\**Site**\Js (currently in **_/scripts/site/_** folder)
\Assets\ExternalLibs\
\Assets\ExternalLibs\\**Bootstrap**\
\Assets\ExternalLibs\\**JQuery**\ 
\Assets\ExternalLibs\\**JQueryUi**\
etc..

The \Assets\ExternalLibs\{package}\ are currently mixed across the **_/content/_**, **_/fonts/_** & **_/scripts/_** folders.

Perhaps application settings could be used to point to the default location for each:
Site-Content
Site-Fonts
Site-Scripts
External-Packages (where each external package would have its own sub-folder)

**Comment by volkanceylan** [comment]
This is where ASP.NET MVC and NuGet packages places them by default. I don't see any advantages to moving them.

**Comment by tb-mtg** [comment]
What about projects that use packet mangers other than NuGet (like NPM, Bower)?

**Comment by jsbUSMC** [comment]
You can configure those paths to install to the default content folders using `package.json` and/or `.bowerconfig`.

**Comment by volkanceylan** [comment]
We are currently not using Bower/NPM, as it means some additional dependency, which i'd like to avoid. When we switch to ASP.NET Core (looks far away), we'll probably make use of Bower.

**Comment by jsbUSMC** [comment]
Just wanted to say that Bower looks to be no longer maintained. If anyone is worrying about the npm dependency tree, npm 3 looks to have introduced de-duping in the dependency graph for all libraries installed and flattens the dependency structure to only 1 level deep in `/node_modules`. I think if we do move to npm it should force use of npm 3.

**Comment by volkanceylan** [comment]
Hmm, sad to hear, they are just recently integrated into VS. NuGet works kinda fine for now, though not all packages are available, or up to date.
