### ISSUE TITLE
Inline editing grid, custom control, and report design

### ISSUE THREAD

**Issue by kimheangcheng** [volkanceylan/Serenity#886]
Dear Volkanceylan,

I've just found serenity recently. I am very appreciate with you work and contribution to everyone. I think Serenity is very useful to me. However, I have some difficult in using it especially to make the system met users' requirements. So, I would like to ask you to enable users to edit data on grid row/column directly. Here is a link of demo Kendo UI grid "[http://demos.telerik.com/aspnet-mvc/grid/editing-inline]". And It would be great if you can implement the combobox/dropdown with multiple comlumns and support large dataset similar to the demo of DevExpress components in here [https://demos.devexpress.com/MVCxDataEditorsDemos/Editors/LargeDataComboBox].

![image](https://cloud.githubusercontent.com/assets/11472843/16678140/81600342-4506-11e6-8892-196fe9788791.png)

In addition, Could you please guide me on how to use other custom controls and design report in Serenity due to I have to follow the request from my users and report format of my organization.

Thank you so much,

Kim

**Comment by volkanceylan** [comment]
SlickGrid doesn't support such details, nor does Serenity. You need to handle such UI with dialogs. There is an inline editing sample in product page, this is best you can get. We are not competing with any commercial packages, nor have a requirement to implement feature X they provide.

**Comment by kimheangcheng** [comment]
Thank Volkan for your information.

**Comment by wldkrd1** [comment]
Totally get the explanation and reasoning. FYI my users are also now requiring inline editing. Just another data point to consider as you guys are evaluating new features/changes to Serenity.

Thanks again for all your hard work on this project!
