### ISSUE TITLE
Handling MultiTenant Cascade Quick Filter with Tenant Login

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#887]
I am doing Multi Tenant Application, in that i have two quick filters on one Entity.
One quick filter is of Tenant and other one is cascaded with Tenant Quick filter.
Both the filter will be available to admin but, only one filter will be available to a tenant.
In case of tenant Logs in, it shows error that cannot find parentId  'TenantID'.
How this situation can be handled.
regards
Shailesh

**Comment by volkanceylan** [comment]
Create quick filter using addQuickFilter manually, and don't set CascadeFrom if non admin

**Comment by shaileshbc** [comment]
Can you provide any sample in which addQuickFilter has been used.
regards
Shailesh

**Comment by volkanceylan** [comment]
Well, what about typing addQuickFilter and search?
