### ISSUE TITLE
ExecuteSave() throws Exception from underlying MS SQL engine () in AfterSave Event when Record is created

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#89]
**Environment:**
- Current Serene template (Nuget packages updated at 01.01.2016) --> Modified to new purpose (using Serenity Developer guide)
- MS SQL local DB
- File: xyzRepository.cs
- Class: private class MySaveHandler : SaveRequestHandler<MyRow>
- Method: protected override void AfterSave()
- "Event": Record create

**Situation, error and possible solution (proposal) description:**

I have to do some update (final Status info) on the record which is currenty being created, after the record is just being created (because I need the Indenity identifier number to create some records in another table/Entity which uses this ID in referential integrity and if this has been processed, I want to set the final Status info of the whole processing (e.g. all ok or something went wrong).

So I have to use AfterSave Event because only there the new Identity ID is known.

Within the AfterSave() method, I use the following Statements to update the current row/record:

`Row.CsvDataImportStatusInfo = "Some final Statusfeedback";`
`ExecuteSave();`

This works fine when the record already exists in the database (e.g. update the record) 

**but fails** in the case of new record creation with an underlying MS SQL exception which states that IDENTITY_INSERT is off within the MS SQL DB.

**Problem Detail description:**
Identitiy Identifiers (ID) are autogenerated by MS SQL and should never be updated by Serenity. 

**Solution proposal** (I am no developer - just an admin with some programming enthusiasm), so this could be a totally wrong approach):

The ExecutionSave() method should respect identity columns (can pull this info out of xyzRow.cs) and should never try to write to an identiy column.

-----------------------
Let me say a word of thanks to you for putting together Serenity as it allowed me within a week (incl. learning Serenity) to develop a good part of an app which I had in mind for our servicedesk without wasting my time with Javascript, Database Access, AJAX etc.

When it is finished I gladly will give more Information on the app, its purposes, etc.

Thanks for looking into the above issue. Please let me know if there is a workarround.

With Kind regards,

John

**Comment by volkanceylan** [comment]
I don't recommend you call ExecuteSave() in AfterSave(), it is already called before it. This way you are simply trying to insert same record, but this time with an ID value into database again. ExecuteSave remembers that this a CREATE handler, and generates INSERT statement.

What you are trying to do, if i understand right, updating a field of inserted record, after insert. So what you should do is an UPDATE.

You can do it like this:
```cs
            protected override void AfterSave()
            {
                base.AfterSave();

                Connection.UpdateById(new MyRow
                {
                    EmployeeID = Row.EmployeeID,
                    Address = "Some final Statusfeedback"
                });
            }
```

Replace EmployeeID with your identity field.

**Comment by JohnRanger** [comment]
Volkan, 

many thanks for your very fast and precise answer. This has perfectly solved the Problem.

With kind regards,

John

**Comment by volkanceylan** [comment]
Thanks to you also for your detailed report. It's rare.
