### ISSUE TITLE
Input Control Types

### ISSUE THREAD

**Issue by amorpeth** [volkanceylan/Serenity#892]
Hi,

First of all, thanks you very much for creating and maintaining this excellent framework. As a novice programmer it makes things a lot easier :)

I have a question about how to manage the input control types. E.g:
- If my database column holds a date, how do I tell serenity to treat it as a DateTime selector rather than a TextBox?
- Similarly how can I create a ComboBox selector from a database column?

I have completed the movie tutorial, and search the user guide but couldn't find anything. I

Any pointers or assistance would be greatly appreciated.

Thanks,
Andrew

**Comment by volkanceylan** [comment]
use [DateTimeEditor] attribute. for combo box did you miss LookupEditor in movie tutorial?

**Comment by amorpeth** [comment]
Cheers, date was easy :)

For combo are you referring to "Adding a "Movie Kind Field"? I have completed that tutorial but it uses a static Enum list. I want the combo to be populated from a dynamically changing Db column e.g. I might have a column with users. I am sure I am probably just missing something obvious!

Andrew

**Comment by amorpeth** [comment]
Also could you please tell me if the Quickfilter can be configured to either handle a wildcard or perform a contains operation. Currently the default Quickfilters I have added require an exact match.

Cheers!!

**Comment by volkanceylan** [comment]
You missed Genre. Quick search is for contains, not quick filter.
