### ISSUE TITLE
Getting started with the downloaded "Serenity-master.zip"

### ISSUE THREAD

**Issue by DavidMhluzi** [volkanceylan/Serenity#893]
HI,

Kudos on the work and effort put on this, hence I wanted to try it out for the first time. So I downloaded the whole solution. But it seems as if it only has library projects only so I cant actually run it. 

Is there something I'm missing? How do I get started? Please help in this regard or point me in the correct direction?

Regards,

**Comment by samdubey** [comment]
You should download Serene-master not Serenity-master
As Serenity is underlying framework that do magic ;-)

**Comment by volkanceylan** [comment]
I recommend downloading template from Visual Studio Gallery, not GitHub repository, see guide.
