### ISSUE TITLE
Uncaught TypeError: Cannot read property 'VehiclesGrid' of undefined

### ISSUE THREAD

**Issue by Thebenmandude** [volkanceylan/Serenity#895]
Hi,
I have been getting this error and couldn't find any fix in the current issue list. I then Installed Visual Studio 2015, re-downloaded the template and recreated my DB with the migration added, TypeScript was installed but I am still getting the error when I run the solution and try to open the Grid.
Could you please assist me in where to look for the issue?

**Comment by volkanceylan** [comment]
Check your page index.cshtml. See which namespace your VehicleGrid is in there, and in actual Web.js file.
