### ISSUE TITLE
Split javascript/typescript in more files

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#897]
Hello.

Can anyone advise me on how to split the JavaScript file into multiple files? And how to divide the output of typescript on multiple files instead of just one?

Thank you

**Comment by volkanceylan** [comment]
You may remove outFile setting, and get each .js generated next to its .ts. But this will create more pain than it provides, don't know why bother.

**Comment by Estrusco** [comment]
Thank you @volkanceylan :D
I would divide the javascript generated file to insert the js files only when necessary (for example Adminitration, BaseTable, Management, etc.), for performance reasons. 
The goal would be one js files per group, not one for management. 
Also with many typescript to generate Visual Studio crashes all the time even though I have 12GB of memory (I also tried it on other pc but the problem occurs the same).

**Comment by volkanceylan** [comment]
Strange, in my machine TypeScript compilation is instant. Do you have too many files? It might help to list files in tsconfig.json explicitly.

**Comment by Estrusco** [comment]
I have about 200 tables. The compilation TypeScript is very fast, but Visual Studio crash after 30-40 seconds.
I have found this in TypeScript issues  https://github.com/Microsoft/TypeScript/issues/9417 where is suggest to avoid the "compile on save" as temporary workaround.

**Comment by volkanceylan** [comment]
Yes you might disable compile on save, and use watch mode or it compiles at build anyway

**Comment by Estrusco** [comment]
OK @volkanceylan  I think I disable it.
And thanks for diet to Serene 2.3.1 and for your hair :D

**Comment by Estrusco** [comment]
Just for information for any interested persons, this problem was solved with Update 3 of Visual Studio 2015.

https://www.visualstudio.com/it-it/news/releasenotes/vs2015-update3-vs#typescript
