### ISSUE TITLE
Got a error: t4 templates transformation: MsieJavaScriptEngine.JsRuntimeException

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#898]
Hi,volkanceylan.Nice to see you,
I can't Transform T4 templates, The follow informmations you can analysis it.

 MsieJavaScriptEngine.JsRuntimeException: [object Error]undefined
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate[T](String expression)
  at

Microsoft.VisualStudio.TextTemplating715B2C5B36B7F50406D149BF768AE0AA33537A6AEC6F35EB2DBB92106B4401F637BB0FCF1A0F8F

5B49A99E81EA5E188BA724914846765EF50FBB4B09E10323A0.GeneratedTextTransformation.TSTypeLister.List()
   at

Microsoft.VisualStudio.TextTemplating715B2C5B36B7F50406D149BF768AE0AA33537A6AEC6F35EB2DBB92106B4401F637BB0FCF1A0F8F

5B49A99E81EA5E188BA724914846765EF50FBB4B09E10323A0.GeneratedTextTransformation.TransformText()	D:\WGHWorkSpaces

\WGHFiles\VS2013Files\Serene1\Serene1\Serene1.Web\Modules\Common\Imports\ClientTypes\ClientTypes.tt	1	1	

Serene1.Web

I also install TypeScript  for 2013. but the error exist still.  Is there something I make mistake?

**Comment by volkanceylan** [comment]
Install IE11, TS 1.8.6

**Comment by weiguanhai** [comment]
I use VS2013 now ,Can I install TS 1.8.5 for VS2013？  @volkanceylan

**Comment by volkanceylan** [comment]
Yep but error is probably about IE

**Comment by weiguanhai** [comment]
OK,I will have a try later, Thank you.
