### ISSUE TITLE
[General Comment] - Nuget packages on Build

### ISSUE THREAD

**Issue by sayuga** [volkanceylan/Serenity#899]
I was going through the old issues for guidance on a few things when I came across issue  #525 which reminded me of something I had seen before regarding Nuget packages. 

I believe Nuget allows Package Restore via Visual Studio. Was wondering if this was something that could be put into place to allow all the Nuget pacakges to be pulled upon build, allowing Serene to be smaller upon start. 

https://docs.nuget.org/Consume/Package-Restore 

Just generally putting this out there since I don't think package restore is currently being used with serene.

**Comment by volkanceylan** [comment]
NuGet packages needs to be in template. This is clearly stated in NuGet docs. Although you can try and hack, last time i tried resulted in broken template, especially Saltaralle packages.

**Comment by sayuga** [comment]
Hmm... I might play around with this a bit later just for the fun of it. I don't expect much success but I'll let you know how it goes. thanks for the reply. ^_^

**Comment by volkanceylan** [comment]
Well i tried and looks like this time it might work for DLL only references. Problem was with Saltaralle / Node etc. that was running install scripts.

**Comment by volkanceylan** [comment]
Ok, Serene 2.3.1 is down to 2.5 mb from 21mb, though my white hairs is %50 more :)

**Comment by sayuga** [comment]
They say grey is the sign of wisdom and Serene/Serenity is proof of this. ^_^ We all greatly appreciate all you're efforts.
