### ISSUE TITLE
cascade join

### ISSUE THREAD

**Issue by linpiero** [volkanceylan/Serenity#90]
hi,
compliments for Your Fantastic work.
I have the tables A, B, C.
A have fk to B and B have fk to C
It's possible view in A dialog or A grid some columns of table C?

Thanks

**Comment by volkanceylan** [comment]
Please have a look at mapping attributes chapter of Serenity guide:

https://volkanceylan.gitbooks.io/serenity-guide/content/entities/mapping_attributes.html

**Comment by linpiero** [comment]
Thanks, Your framework is really functional and complete :-) :+1:

**Comment by volkanceylan** [comment]
Thanks ;)
