### ISSUE TITLE
I need Help with Master - Detail Relation and Form, Populating the Detail Form.

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#901]
Prior to this projected I've been handed about six weeks ago, I had zero experience with C#, Typescript, ASP.NET MVC 5, and several other of the tools. While I've been able to get many things working for the program in the Serene Framework, I have run into some issues.

I have a master detail relationship with some tables where I have a primary key on each table and the primary key on the Mater table is also a Foreign Key in the Detail table, that is BudgetKey (Primary Key)  => RevenueSummaryLink (Foreign Key Relationship).  This is a 1 to m relationship where the Summary table will have one record and 12 related Detail records.

I've gone through the Serene Manual several times and have tried the examples from the Genres section, The Cast and Characters, I've examined the Northwind Order and Details sample and tried using that as well as reviewed some of the Basic Samples available and I just can't seem to get the form to populate.

I'm able to get the Detail form to be available in the Master form, but I can't get the data to populate properly, or at all.  I'm sure I'm missing something quite basic, but at this point I don't know where to look.

I'm happy to provide any code that may be necessary to facilitate assistance.

Thank you in advance for any insights you may be able to offer.

**Comment by jsbUSMC** [comment]
What are the Master class and Detail class? What properties are you trying  to populate, and where? Provide any code you think is helpful, please.
