### ISSUE TITLE
Adding Workflow .net engine

### ISSUE THREAD

**Issue by josh64057** [volkanceylan/Serenity#902]
would any one know how to add the workflow .net engine API to serene. it can be installed with nuget, but im unable to get it to work. http://workflowenginenet.com/Documentation/detail/howtoconnect.

i went through the how to connect instruction from their website. now what? do i need to move the designer from the view folder to the modules folder?

**Comment by volkanceylan** [comment]
Serenity is just another ASP.NET MVC application. Views works also under Views folder as usual. Though we prefer to put them under modules. I don't have experience with that library and can't offer support for it. You better ask for help there.
