### ISSUE TITLE
I need your help with it

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#903]
Hi,volkanceylan ! I have some question with the serenity.

I create a table in sql server2012 , the table have a column which is "releaseTime". Now I want insert a record by the serenity.  How can I compare the moment time with  the max value of the column "releaseTime"  ?   What can I do with it ?

**Comment by volkanceylan** [comment]
Dapper is integrated, you can write a simple query in your SaveHandler ValidateRequest or SetInternalFields etc. methods. 

```
var maxDate = this.Connection.Query<DateTime?>("SELECT Max(ReleaseTime) FROM ...").FirstOrDefault();
```
