### ISSUE TITLE
author , Can you help me?

### ISSUE THREAD

**Issue by thisXYH** [volkanceylan/Serenity#904]
I create an new table,and I use the Serenity Code Generator to generate code.Some field of the table are required that it can insert but can't update.  How  to achieve it?

**Comment by thisXYH** [comment]
And a DateTime's field of the table, the field can insert when the current field's value > max(the field's column),,how to add zhe condition;

**Comment by ramveersgh** [comment]
Use Updatable(false) attribute for that field. This will make it readonly at the time of update. This is mention in guide too.
For DateTime's  field you need to write your logic in repository in before SaveHandler.

**Comment by thisXYH** [comment]
thank you ,your frame so powerful that I am Confusing

**Comment by thisXYH** [comment]
how to get current  the DateTime's field  list

**Comment by thisXYH** [comment]
` public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            request.Entity.CreateTime = DateTime.Now;
            request.Entity.UpdateTime = DateTime.Now;
            if (mySysList==null)
            {
                string account =  request.Entity.Account;
                string channel = request.Entity.Channel;
                if (!account.IsEmptyOrNull() && account.LastIndexOf("，") != account.Length-1)
                    account += "，";
                if (!channel.IsEmptyOrNull() && channel.LastIndexOf("，") != channel.Length-1)
                    channel += "，";
                
                 return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
            }
            else if (mySysList.FindAll(item => item.DownTime >= request.Entity.DownTime) != null)
            {
               //how to tell user zhe time be ban
            }
            



           
        }`

**Comment by thisXYH** [comment]
User-defined validation's logic where it is writed. and how use ajax validate the datetime's field value

**Comment by Estrusco** [comment]
Have you readed the manual?

https://www.gitbook.com/download/pdf/book/volkanceylan/serenity-guide

also take a look at Wiki https://github.com/volkanceylan/Serenity/wiki

**Comment by thisXYH** [comment]
I readed,but I am not good at English and not found this  content . I already  write some logic  in repository in before SaveHandler,but I don't know  how to tell my users  the field's value is not allow when their mouse  leave the editor

**Comment by Estrusco** [comment]
The frontend  validation is done by javascript (or typescript during development). You can see UserDialog.ts in Serene for ValidationRule.

Also see https://github.com/volkanceylan/Serenity/wiki/EnableDisableControls for enable/disable controls in react the user input, and also see Serenity.EditorUtils in Serenity.CoreLib.d.ts for get, set value and other utility function.

**Comment by volkanceylan** [comment]
Search for AddValidationRule in code for samples of client side validation.
