### ISSUE TITLE
Regarding XML documentation in code

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#908]
Dear Volkanceylan,

Do you like XML comments on code?
If you like I can try to write some of them.

**Comment by volkanceylan** [comment]
I don't like much to be honest, but don't have much alternatives :) I have some on base classes in Serenity.Core etc. and had actually much more before, but had to remove them as it was hard to keep them up to date.

Anyway i'd appreciate any help. Thanks.
