### ISSUE TITLE
Custom Pdf Report layout

### ISSUE THREAD

**Issue by reybatacjr** [volkanceylan/Serenity#909]
Hi, I was planning to use Serenity on my upcoming project which is Water Billing and Management System.
My question is, how can I customize / format the pdf output for receipt printing.

I'm using Onion Architecture on my previous projects but found this framework much faster.

**Comment by sayuga** [comment]
you would want to download the wkhtmltopdf and then you can update the output by creating a HTML version of the report you want for the receipt. Look at the OrderDetailReport.cshtml for a sample unde the Norhwind/Order sample of serene.

**Comment by volkanceylan** [comment]
Serenity reports by default are just HTML / CSS pages.  You customize them with CSS. It's also possible to use reporting services etc, though i don't think it adds much value. Samples are a bit lacking though.

**Comment by reybatacjr** [comment]
Thank you for a quick response I will look on it and see if I can come up with a tutorial regarding this topic.
