### ISSUE TITLE
DatePicker is not using MM/dd/yyyy as defined in system and globalization culture

### ISSUE THREAD

**Issue by gregg1ep00** [volkanceylan/Serenity#91]
Hi, first, thank you so much for providing this framework.  It is truly beautiful.

I'm trying to figure out why the jQuery datepicker seems to be stuck on dd/MM/yyyy format.  I have the following entry in my web.config:

`<globalization culture="en-US" uiCulture="auto:en-US" />`

System culture is set to en-US.

Any ideas?  Thanks in advance!

**Comment by volkanceylan** [comment]
Currently Serene doesnt pass server culture info to script side. So dates stays dd/MM/yyyy. I noticed this recently and fix on the way. Actually there was support in an older version. It's just a bit blurry if i should use server culture or ui culture at client side. Open to ideas.

**Comment by volkanceylan** [comment]
Btw, you can set Q.Culture.DateOrder and Q.Culture.DateFormat method in a static constructor of MyProject.Script project as a workaround.

**Comment by gregg1ep00** [comment]
Thanks for the workaround, I will try that and let you know if I have any further issues.

In terms of how it "should" behave, I would think that the client side would detect and use the locale from the browser, and any scripts would use the browser-specific culture.  Case in point, If the server is in the UK but I am browsing from the US, I should not be expected to enter dates in UK format.

Of course this is just my humble opinion.  Great work on this framework!

**Comment by volkanceylan** [comment]
1.8.19 provides this support now.

Simply update template, or NuGet packages.

Set culture to auto too in web.config, like:

```xml
<globalization culture="auto:en-US" uiCulture="auto:en-US" />
```

Add this line in LayoutHead before CommonIncludes:

```xml
<script type="application/json" id="ScriptCulture">
   @Html.Raw(Serenity.JSON.Stringify(new ScriptCulture()))
</script>
```

**Comment by gregg1ep00** [comment]
Beautiful!  Works great here!  Thanks so much!
