### ISSUE TITLE
Custom Lookups and Permissions

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serenity#911]
Hi,

More of an FYI than an issue, since I have already fixed it. :)

I am assuming this is intended behavior but it confused me for a bit. Might be worth dropping into the guide something about it.

When you make a custom lookup and forget to set the Permission="?" key. When you go to a grid that has that lookup script included on its row definition. The row displays fine in the grid but you obviously can't do much else.

What confused me more than anything else was that the New (whatever) button was not clickable so I didn't easily connect that it was permissions on a lookup causing that.

**Comment by volkanceylan** [comment]
What is so suprising that a lookup uses permission of row you put it on. This is correct behavior security-wise. If something doesn't work, first thing you should do is to look at browser console.
