### ISSUE TITLE
Attribute: ClientSide vs OneWay

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#912]
Dear @volkanceylan,
I'm a bit confused about the attribute ClientSide and OneWay...which is the exact behaviour of such attributes?
Could you kindly explain the logic behind?

Thank you very much
Bye

**Comment by marcobisio** [comment]
I'm asking that because I'm trying to use a not nullable db field with a default value (on the table), but Serenity always pass the null value (because it's null in the entity)...there is way to exclude such field from the insert statement?

**Comment by zerodev** [comment]
Insertable Attribute

To turn off Insertable flag for a field, put a [Insertable(false)] attribute on it:
[Insertable(false)]
public string MyField
{
    get { return Fields.MyField[this];
    set { Fields.MyField[this] = value;
}

https://volkanceylan.gitbooks.io/serenity-guide/content/entities/fieldflags_enumeration.html 

https://github.com/volkanceylan/Serenity/wiki/SetFieldFlagsAttribute%20%5BMapping%5D

**Comment by marcobisio** [comment]
thank you very much @zerodev !

**Comment by volkanceylan** [comment]
OneWay is for fields that may be sent to client side, but shouldn't be sent back. Usually for temporary fields that you use in a form, but doesn't exist in row, so OneWay can be used to avoid deserialization errors.

ClientSide is for unmapped fields in row.

**Comment by marcobisio** [comment]
Oh now it's all clear!
Thank you very much @volkanceylan 
Bye
