### ISSUE TITLE
Disabling jsrender.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#914]
Dear Volkanceylan,

I am using Vue.js as frontend framework for some part of my application. and it has {{}} binding expression. So it conflict with jsrender.

Is there any way to disable the jsrender for particular dialog template?

Many thanks for your guidance.

**Comment by volkanceylan** [comment]
Override Q.jsRender function and find a way to determine if this is a Vue template or JsRender one, e.g. add some header to Vue ones, check it, if it doesn't exist call old Q.jsRender.

```js
var oldJsRender = Q.jsRender;
Q.jsRender = function(markup: string, data?: any) {
    if ((markup || '').indexOf('<!--VUE-->') >= 0) {
    }
   else
       return oldJsRender(markup, data);
}

**Comment by dfaruque** [comment]
Thanks a lot...
