### ISSUE TITLE
SQL == versus 'in'

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#915]
I have a filter setup on one of my forms that works well for a single item. The field may contain from 1 to n comma separated values, however. When the field contains a single item, the filter (below) works like a charm, however if there is more than one value, the filter breaks. I've found that I can't use the SQL command 'IN' with the code either.

Note, Division has been added to the users table and included in the Users form .cs files and  UserEndpoint.cs, UserRetrieveService.cs, ScriptUserDefinition.ts, UserDefinition.cs, ScriptUserDefinition.cs.

Are there any suggestions:

Example 1; Division = 'a'             - Works very well.
`        private class MyListHandler : ListRequestHandler<MyRow>
        {
            protected override void ApplyFilters(SqlQuery query)
            {
                base.ApplyFilters(query);

                var user = (UserDefinition)Authorization.UserDefinition;

                query.Where(fld.Division == user.Division);
            }
        }
`
Example 2: Divisions = 'a', 'b', 'c'                  - Filter Breaks and the 'IN' word doesn't work

**Comment by volkanceylan** [comment]
fld.Division.In(new[] { "a", "b", "c" })

**Comment by mlutzow** [comment]
The values I'm trying to evaluate against are table based in [Users].[Division]. User 1` might have Division a available where user 2 might have Division a, b, d available.

I'm trying to filter the form based on whatever the Division(s) the user has been authorized to access.  If I could use something like fld.Division In([user.Division}) that would be great.

**Comment by volkanceylan** [comment]
Do you know how to split a string? How do you expect something that doesn't work in SQL to work here?

**Comment by mlutzow** [comment]
Quite frankly, with T-SQL or the other proprietary (old technology) languages I've been using for the last 10 years ... yes I do. With ASP.NET MVC and C# and name the tool in the SERENE template, I'm in learning mode - overdrive learning mode. 

I can tell the template is a well thought out, well put together package, and support that is quite nice and has helped me advance in my knowledge of the technology substantially, but a persons level of expertise with a set of tools is what it is in whatever endeavor you want to name. Not everyone picks up and starts developing with the toolset with 10 years prior experience under their belt.

**Comment by volkanceylan** [comment]
Sorry, i probably misunderstood your aim. Thought you wanted to write something like Field1 in Field2 and expected Field2 to be assumed as an expression.

You can do

query.Where(fld.Division.Expression + ' IN ' + user.Divisions)

But still id recommend not putting an SQL statement inside a field, as it is not safe and prone to errors. I'd parse allowed divisions myself or better hold their list in a linking table.

**Comment by mlutzow** [comment]
Agree with your analysis. I'd be inclined to use a linking table, but I've recently found out the multiple division usage would be very limited in nature, this item is moving down the list of priorities for now.

Thank you.
