### ISSUE TITLE
Changing the accordion navigation layout to single tabled items

### ISSUE THREAD

**Issue by DavidMhluzi** [volkanceylan/Serenity#916]
Hi,

I would like to change the accordion navigation items to single items(icons) that's layed in a table form. Is there an article related to that or tutorial on that?

I know this post might not be understandable so I utilized paint to illustrate what I have in mind

Current menu navigation.
![image](https://cloud.githubusercontent.com/assets/12898572/16855356/43a66a1e-4a15-11e6-9d81-32fa23eb38d1.png)

Desired menu navigation
![image](https://cloud.githubusercontent.com/assets/12898572/16855433/97ae14fe-4a15-11e6-98bf-cdaf75547336.png)

The red "circles" being my items for the menu. Is this achievable? Any source of information will be highly appreciated.

**Comment by volkanceylan** [comment]
Navigation items are available in NavigationModel and are rendered into that navigation in LeftNavigation.cshtml. You are free to convert rendering to whatever you like.
