### ISSUE TITLE
Date format in ExcelReportGenerator

### ISSUE THREAD

**Issue by kermiv** [volkanceylan/Serenity#919]
ExcelReportGenerator set incorrect format for second parts. In .NET DateTime seconds part format char is "f", but in excel "0", and DateTime "25.06.2015 14:33:11.123" displays as "25.06.2015 14:33:11.fff".

I add in ExcelReportGenerator line 108 new check:
```
if (!column.Format.IsEmptyOrNull())
{
    if (column.DataType == typeof(DateTime) ||
        column.DataType == typeof(DateTime?) ||
        column.DataType == typeof(TimeSpan) ||
        column.DataType == typeof(TimeSpan?)) 
    {
        column.Format = column.Format.Replace('f', '0');
    }
    worksheet.Column(i).Style.Numberformat.Format = column.Format;
```
I do not know will it be enough, but for me it works.

**Comment by volkanceylan** [comment]
Excel report generator doesn't have such a format specifier, are you sure you don't have a DisplayFormat attribute on your columns?

**Comment by kermiv** [comment]
I have DisplayFormat = "HH:mm:ss.fff"
But excel not recognize "fff" and time in these columns is displayed such as "14:33:11.fff"

I can't use DisplayFormat = "HH:mm:ss.000" on column, because then in SlickGrid time "14:33:11.123" became as "14:33:11.000"

**Comment by volkanceylan** [comment]
Ok, i applied your fix, thanks
