### ISSUE TITLE
how to custom field PdfExportHelper 

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#920]
How to display custom field in pdf formats like generate invoice,  only contain custom fields, Now display the hole grid part

**Comment by shaileshbc** [comment]
kindly refer to Northwind/Orders, click on any Order, you will see Invoice Button, This sample uses PDFExportHelper to generate PDF file based on OrderDetailReport.cshtml template.
regards
Shailesh

**Comment by GOBIBE** [comment]
thanks mr shaileshbc
