### ISSUE TITLE
Can't find wkhtmltopdf.exe which is required for PDF generation

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#921]
how to rectify this issues

**Comment by shaileshbc** [comment]
You can download it from http://wkhtmltopdf.org/downloads.html and install software.
copy wkhtmltopdf.exe to App_Data\Reporting folder.
regards
Shailesh

**Comment by volkanceylan** [comment]
Read the rest of the error message, how can you read first sentence and not rest!
