### ISSUE TITLE
editable grid in master/detail forms

### ISSUE THREAD

**Issue by osmankaratemiz** [volkanceylan/Serenity#923]
first of all Serenity is great, although I'm not an expert in programming I've been able to do what I need by reading just tutorials.

I need to make an editable grid in a master/detail form, like an order/order details form. it takes to much time to add order details one by one. some of the columns in details grid should be selected from drop-down and some of them needs to be default values.

I'm sure this can be done easily by experts but a tutorial or a basic sample would be great for me.

note: I'm not sure if this is the right place to post this, so sorry about that if I'm wrong.

thanks in advance

**Comment by volkanceylan** [comment]
Sorry, i don't support inline add. Best you can get is inline editing sample in ProductGrid.

**Comment by volkanceylan** [comment]
Also, it's not a fact that inline add is any faster than form based add. There is only two button clicks difference,which can be assigned shortcut keys. Inline editing is not user friendly, almost impossible in mobile and limited space makes editing horrible. Validation is another problem.
