### ISSUE TITLE
How to add FilterValue with multiple values for LookupEditor

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#925]
Hi

Is it possible to provide multiple values in FilterField for lookup?
I have lookup with Fields Id, Name, Type. I want to apply filter in records based in multiple Types.
For Example
form.Party.FilterField = "Type";
form.Party.FilterValue = 1, 2, 5; ???

**Comment by volkanceylan** [comment]
No, see basic samples

**Comment by in32bit** [comment]
We edit "Serenity.Script.UI"

filterItems: function (items) {
            if (ss.isNullOrUndefined(this.get_filterValue()) || ss.safeCast(this.get_filterValue(), String) === '') {
                return items;
            }
            var key = this.get_filterValue().toString();
            return Enumerable.from(items).where(ss.mkdel(this, function (x) {
                var $t1 = x[this.get_filterField()];
                if (ss.isNullOrUndefined($t1)) {
                    $t1 = $Serenity_ReflectionUtils.getPropertyValue(x, this.get_filterField());
                }
                var itemKey = $t1;
                return !!(ss.isValue(itemKey) && ss.contains(key.split(","), itemKey + ""));
            })).toArray();
        }
