### ISSUE TITLE
Lookup search dialog

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#926]
Hi,

I wanted to place a search button next to a field, much like "InPlaceAdd", so that it pop's up a Search Dialog. 
Then, when the user selects a row and click "OK" the field (or fields) would be filled with some data.

Could this be achieved?

Thanks

**Comment by volkanceylan** [comment]
Yes anything can be achieved but not with a few words here. You may look at source of how inplace add works.

**Comment by Estrusco** [comment]
You can add some like this in dialog.ts. See also issue https://github.com/volkanceylan/Serenity/issues/829


```js
            var fieldEditor: JQuery = this.form.YourField.element.closest(".editor");
            fieldEditor.addClass("has-inplace-button");
            $('<a><b/></a>')
                .addClass('inplace-button')
                .addClass('inplace-create edit')
                .attr('title', 'Details')
                .insertAfter(fieldEditor)
                .click(() => { .... }
            );
```
