### ISSUE TITLE
Stay safe, Volkan

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#928]
This isn't your normal issue, but I think Volkan is from Turkey and just wanted to say stay safe my friend!

**Comment by wdhodges** [comment]
Profile says he's from Instanbul Turkey, where there is currently a military coup going on. @volkanceylan we hope you are okay, let us know if your safe!

**Comment by Estrusco** [comment]
I read this... hope volkanceylan and all turkish is ok.

**Comment by jsbUSMC** [comment]
Yes please stay safe. We are all wishing and/or praying for your safety and of all your friends and family. Take care and be cautious!

From all of your friends and students

**Comment by volkanceylan** [comment]
Thanks a lot guys, i'm fine. It was a long night but things are getting back to normal at the moment.

**Comment by samdubey** [comment]
Please stay safe @volkanceylan

**Comment by ramveersgh** [comment]
Good to hear @volkanceylan  that you are fine.
Be safe and Take Care.

**Comment by Estrusco** [comment]
Well, we like to hear this @volkanceylan

**Comment by wdhodges** [comment]
Glad to hear you're okay! Hope everything returns to normal soon man!

**Comment by awesomegithubusername** [comment]
I hope you're doing great volkan. Stay safe.

**Comment by mlutzow** [comment]
Agreed, praying / wishing that you and your friends family are and remain safe.

**Comment by rolembergfilho** [comment]
It's great to you safe!

Be careful, because first actions always have a reaction.

So, stay safe !

**Comment by dfaruque** [comment]
I pray for the peace and safety of the entire world. 
Btw I am from Bangladesh.

**Comment by volkanceylan** [comment]
Thanks to everyone again.
