### ISSUE TITLE
Cascading LookupEditor Programmatically

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#929]
I had created lookupEditor as per TranslationGrid.ts in createToolbarExtensions method. 
I need to create another lookupEditor which is cascaded to the earlier one. 
what value should i put in cascadedfrom option, as it is not working if
I give lookupeditor name.
regards
Shailesh

**Comment by volkanceylan** [comment]
You should put name of the first field

**Comment by shaileshbc** [comment]
i tried to put field name but its not working. my code is as follows

`let customerOpt: Serenity.LookupEditorOptions = {
                    lookupKey: 'Administration.Customers'
                };
                this.customerFilter = Serenity.Widget.create({
                    type: Serenity.LookupEditor,
                    element: el => el.appendTo(this.toolbar.element).attr('placeholder', '--- ' +
                        'Select Customer' + ' ---'),
                    options: customerOpt
                });
                this.customerFilter.changeSelect2(e => {
                    this.refresh();
                });
let instituteOpt: Serenity.LookupEditorOptions = {
                lookupKey: 'Administration.Institute',
cascadeField = 'customerId'
            };
            this.instituteFilter = Serenity.Widget.create({
                type: Serenity.LookupEditor,
                element: el => el.appendTo(this.toolbar.element).attr('placeholder', '--- ' +
                    'Select Institute' + ' ---'),
                options: instituteOpt
            });
            this.instituteFilter.changeSelect2(e => {
                this.refresh();
            });`
in this case, even putting filter name does not work.
regards
shailesh

**Comment by volkanceylan** [comment]
There are several lookup filter cascade samples in guide. Find one. I can't even read your code.

**Comment by shaileshbc** [comment]
I want to put lookupeditor in toolbar so i want code adding lookupeditor in toolbar, which i find in TranslationGrid.ts, where you had added two lookupeditor. 
so i changed my code similarly
attaching code so you can able to read properly.
[StudentGrid.txt](https://github.com/volkanceylan/Serenity/files/367260/StudentGrid.txt)
In most of the sample, Cascading is done on Quickfilter, but here i am trying to put LookupEditor programatically, hence require more help.
regards
shailesh

**Comment by volkanceylan** [comment]
Your elements doesn't have ID

**Comment by shaileshbc** [comment]
I changed code for CustomerFilter as 
`element: el => el.appendTo(this.toolbar.element).attr('placeholder', '--- ' +
                        'Select Customer' + ' ---').attr('ID','CustomerId'),`

and for instituteOpt changed 

`cascadeField = 'CustomerId'`

still it is not performing cascading.
My Institute LookupEditor is Blank only i.e. without any items.
regards
Shailesh

**Comment by volkanceylan** [comment]
Where is cascadeFrom?

**Comment by shaileshbc** [comment]
I changed code and now it is working for single level filtering, but not second level filter.
[StudentGrid.txt](https://github.com/volkanceylan/Serenity/files/368433/StudentGrid.txt)
Institute filter changed according to Customer filter.
But Classroom filter does not show any item, eventhough Institute filter is changed.
regards
Shailesh

**Comment by shaileshbc** [comment]
One more thing, it does not filter Grid Data, when you select item from CustomerFilter or InstituteFilter.
regards
Shailesh

**Comment by weiguanhai** [comment]
Have you solved this proble about cascade?  If solved, I need your help,  Really thank you!
@shaileshbc
