### ISSUE TITLE
Placing icon in front of Grid DisplayName.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#931]
I want to place  navigation link icon in front of grid title. just like this.

![image](https://cloud.githubusercontent.com/assets/16621563/16899563/6e3c5ae2-4c2a-11e6-8216-5e2361da3fbb.png)

But in this solution I have put this icon manually. and have to do in every grid.
So can you please give me a perfect solution to do this?

**Comment by volkanceylan** [comment]
I'd extract that functionality into an helper and call it in constructor
