### ISSUE TITLE
Disable New/Edit

### ISSUE THREAD

**Issue by amorpeth** [volkanceylan/Serenity#932]
Hey!

We have some tables that we dont want to allowing editing from the web UI. Is there a way to allow view only, and remove the "New" button?

Cheers!
Andrew

**Comment by Estrusco** [comment]
This question has been asked a thousand times. Search in the issues

**Comment by amorpeth** [comment]
I have searched, but couldn't find anything I could follow. Kindly provide a link to a posted issue.

**Comment by volkanceylan** [comment]
Have a look at basic samples

**Comment by amorpeth** [comment]
Hey,

I looked at those but cant figure it out. I have managed to remove the form buttons, but not the new button on the main page using the following code:

![2016-07-18_13-43-44](https://cloud.githubusercontent.com/assets/10904996/16904638/c4e686ba-4ced-11e6-8651-0f8a05e39b57.png)

--------------------------------------------------------
namespace UCGWebPortal.Unilytic {
    
    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class EventLogDialog extends Serenity.EntityDialog<EventLogRow, any> {
        protected getFormKey() { return EventLogForm.formKey; }
        protected getIdProperty() { return EventLogRow.idProperty; }
        protected getLocalTextPrefix() { return EventLogRow.localTextPrefix; }
        protected getNameProperty() { return EventLogRow.nameProperty; }
        protected getService() { return EventLogService.baseUrl; }

        protected form = new EventLogForm(this.idPrefix);

        constructor(container: JQuery) {
            super(container);
        }

//Tried to copy this from the suggested example, but it doesn't do anything
        protected getButtons() {
            return [{
                title: 'Perform Bulk Action on Selected Orders',
                cssClass: 'send-button'
                
            }];
        }

//This appears to work:
        protected getToolbarButtons() {
            return [];
        }

    }
}
--------------------------------------------------------

I take it there is no way to put an "entity" in to read only mode removing buttons and disabling controls?

Thanks!
Andrew

**Comment by Estrusco** [comment]
You can add the attribute Updatable(false) in the fields of the form (or in the row) or you can set read-only programmatically in dialog.ts

https://github.com/volkanceylan/Serenity/wiki/EnableDisableControls

**Comment by amorpeth** [comment]
That worked a treat thanks!

Apologies for all the dumb questions, struggle to find docs when searching.

Whats the best approach to disable and hide the buttons? Ideally I want to hide the "New", "Update", and "Save" button, but keep the "Delete" button. I attempted the above approach but couldn't achieve my requirement.

![2016-07-18_19-36-20](https://cloud.githubusercontent.com/assets/10904996/16908414/783cf506-4d1f-11e6-928a-81ebbabea308.png)

Thanks again!
Andrew

**Comment by Estrusco** [comment]
Override protected getButtons() in grid.ts and/or in dialog.ts

See RemovingAddButton.ts in the latest Serene template. **volkanceylan** has already answered you on this. 
This is for add button, but work in the same way for the other buttons. Check their css classes. 
This code is from basic sample in **Serene**: 

```ts
        /**
         * This method is called to get list of buttons to be created.
         */
        protected getButtons(): Serenity.ToolButton[] {

            // call base method to get list of buttons
            // by default, base entity grid adds a few buttons, 
            // add, refresh, column selection in order.
            var buttons = super.getButtons();

            // here is several methods to remove add button
            // only one is enabled, others are commented

            // METHOD 1
            // we would be able to simply return an empty button list,
            // but this would also remove all other buttons
            // return [];

            // METHOD 2
            // remove by splicing (something like delete by index)
            // here we hard code add button index (not nice!)
            // buttons.splice(0, 1);

            // METHOD 3 - recommended
            // remove by splicing, but this time find button index
            // by its css class. it is the best and safer method
            buttons.splice(Q.indexOf(buttons, x => x.cssClass == "add-button"), 1);

            return buttons;
        }
```

**Comment by volkanceylan** [comment]
In dialog, method name is getToolButtons(), you override similarly and find buttons by their css class.

**Comment by amorpeth** [comment]
Thanks so much guys, got it all working :)

**Comment by volkanceylan** [comment]
2.3.3 also has read-only dialog sample, for those interested.
