### ISSUE TITLE
How can I make Country,Province,City Relation

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#933]
Hi  volkanceylan, Nice to see you.
Now, I got in trouble.
I  have a table Areas includes Country ,Province ,City Column.   How can  I   code it  by  serenity ?
that Result likes the follow ,   Forms Dialog(Insert or Update) , When  I  choose China in  Country Column,  The Province Column automatically Get Data from Sql Server Which I write query Sentence.   
How can  I  make it comes true ?

**Comment by volkanceylan** [comment]
There is a cascade how to. And samples in code.

**Comment by weiguanhai** [comment]
Sorry, I can't make sense of what you just said.

**Comment by weiguanhai** [comment]
Maybe you can see the document.  It may easily understand
[Question.docx](https://github.com/volkanceylan/Serenity/files/368484/Question.docx)

**Comment by weiguanhai** [comment]
I really got in trouble deeply , Can you Help me solve them?  Thank you!
[Question.docx](https://github.com/volkanceylan/Serenity/files/368692/Question.docx)

**Comment by Estrusco** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

**Comment by weiguanhai** [comment]
But I just have a table to storage my data about Country&Province&City??

**Comment by weiguanhai** [comment]
![image](https://cloud.githubusercontent.com/assets/20295114/16937876/4654b250-4da5-11e6-8758-3ec064aba694.png)
 can I use this filterField or other to filter some records from sql table.
Such as  I want to write sql (  select CountryName  from Areas where ParentId=0  ) 
like this sentence, to select some records .  and show in the column.

**Comment by weiguanhai** [comment]
![image](https://cloud.githubusercontent.com/assets/20295114/16940720/3b9dd6f2-4dbe-11e6-9dfa-1b0388e21330.png)
Is there I miss some code or other Lead to this ?

**Comment by weiguanhai** [comment]
I also change to nameof  like this
   [LookupEditor(typeof(BAreasRow), CascadeFrom = nameof(BAreasRow.ParentId), CascadeValue = nameof(BAreasRow.ParentId))]
but the error remain exists

**Comment by Estrusco** [comment]
Add LookupInclude to ParentID if there isn't.
Also, if CascadeFrom and CascadeValue are equal, you can indicate only CascadeFrom

**Comment by weiguanhai** [comment]
I have already added it ,but reminds error
![image](https://cloud.githubusercontent.com/assets/20295114/16944244/3529053a-4dd2-11e6-9d8a-dfeaeed0f674.png)

**Comment by Estrusco** [comment]
Post the entire row with ParentID field  and CascadeField.

Your row must be like this:

```cs
    [ConnectionKey("Default"), DisplayName("XYZRow"), InstanceName("XYZRow"), TwoLevelCached]
    public sealed class XYZRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), Column("ID"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Code"), Column("ParentID"), NotNull, ForeignKey("[dbo].[ParentTable]", "ID"), LeftJoin("jParent")]
        [LookupEditor("Default.ParentTable"), LookupInclude]
        public Int32? ParentID
        {
            get { return Fields.ParentID[this]; }
            set { Fields.ParentID[this] = value; }
        }

        [DisplayName("Cascade field"), NotNull, ForeignKey("[dbo].[OtherTable]", "ID"), LeftJoin("jOther")]
        [LookupEditor("Default.OtherTable", CascadeFrom = "ParentID")]]
        public Int32? CascadeField
        {
            get { return Fields.CascadeField[this]; }
            set { Fields.CascadeField[this] = value; }
        }

    [...]
```

**Comment by weiguanhai** [comment]
why the CascadeField should code here?   it may code in editForm ?

**Comment by weiguanhai** [comment]
![image](https://cloud.githubusercontent.com/assets/20295114/16946220/f87db1e0-4dda-11e6-9c83-66bab2097c6c.png)
the pic in BAreasRow.cs

![image](https://cloud.githubusercontent.com/assets/20295114/16946256/2135dcde-4ddb-11e6-9bef-2b27caf58b53.png)
and this in MyForm.cs  which use to edit the cascade DropDownList

**Comment by weiguanhai** [comment]
I code follow the guide ,But it also have the error

https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html

**Comment by Estrusco** [comment]
Where is your ParentID? Is in the same row of Province? 
 The editor can be in the row or in the dialog indifferently.
Why your ParentID and Province have the same LookupEditor type?

Your pseudo row class:

```cs
    public sealed class ProvinceRow : Row, IIdRow, INameRow
    {
        [Column("ParentID"), ForeignKey("[dbo].[B_Areas]", "ID"), LeftJoin("jAreas")]
        [LookupEditor(typeof(BAreasRow), LookupInclude]
        public Int32? ParentID
        {
            get { return Fields.ParentID[this]; }
            set { Fields.ParentID[this] = value; }
        }

        [DisplayName("Province")]
        [LookupEditor(typeof(PROVINCEROW), CascadeFrom = "ParentID")]]
        public Int32? Province
        {
            get { return Fields.Province[this]; }
            set { Fields.Province[this] = value; }
        }

    [...]
```

Need your complete code to understand.

**Comment by volkanceylan** [comment]
He doesnt know what he is doing. CascadeFrom must be Country for Province and Province for City. CascadeField should be ParentID

**Comment by weiguanhai** [comment]
[BAreasRow.docx](https://github.com/volkanceylan/Serenity/files/371221/BAreasRow.docx)
[CatcherInfoForm.docx](https://github.com/volkanceylan/Serenity/files/371222/CatcherInfoForm.docx)
the BAreasRow.cs  is Country Province  City  data resource。
the CatcherInfoForm.cs is I want to show the cascade EditColumn like  the following picture
![image](https://cloud.githubusercontent.com/assets/20295114/16947412/714ff49c-4de1-11e6-92f2-e1c704fc3103.png)

**Comment by weiguanhai** [comment]
Is there can be save from the error ?  
the cascade issue has realy bother me deeply!   can you help me solve them?
Sincerely appreciate you!

**Comment by weiguanhai** [comment]
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html
I  follow the guide step by step .  but also show me like this
![image](https://cloud.githubusercontent.com/assets/20295114/16978112/c99c1a62-4e8c-11e6-8f4d-c7332a9d91ae.png)
![image](https://cloud.githubusercontent.com/assets/20295114/16978122/d56a4b0c-4e8c-11e6-9bec-d674ee514a54.png)

is the way of the guide doesn't work effectively or out of date ?

@Estrusco
