### ISSUE TITLE
How make dropdownlist  in editForm

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#934]
Hi volkanceylan.  
I have a "encoding" column in a table , the type is string .  I want to add some value such as UTF-8,GBK to the editForm  ,  But not use enumType  ,
Is there have a attribute can I add them.

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serenity/issues/436

**Comment by weiguanhai** [comment]
[Editor]
    public class XYZEditor : Select2Editor<object, object>
    {
        public XYZEditor(jQueryObject hidden)
            : base(hidden, null)
        {
            AddItem("AC", "AC");
            AddItem("DC", "DC");
        }
    }

sorry!
I want to know that where should I code them?

**Comment by jsbUSMC** [comment]
If you mean where to actually create this file? You should create the file in the entity folder under `~/Modules` directory where you plan to use the editor. Create the file `XYZEditor.cs`.

**Comment by weiguanhai** [comment]
I also meet the problem
#752





the following code is my EncodingEditor.  is there something wrong?
     
@Serenity.Decorators.registerEditor()
    export class EncodingEditor extends Serenity.Select2Editor<Object, Object> {
        constructor(div: JQuery) {
            super(div, Option);
            super.addItem("gb2312", "gb2312");
            super.addItem("UTF-8", "UTF-8");
            super.addItem("GBK", "GBK");
        }
