### ISSUE TITLE
Login Screen Customiztion - Minor Issue

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#935]
I have the customization working fairly well. I have one small item that I can't seem to figure out.

On the LoginForm.cs the Username and Password each have a decoration of the type Placeholder which passes some text to the fields.

After the customization I get not only the Placeholder text but the words 'Username' and 'Password' respectively. I can clear the 'Placeholder' to resolve the issue, but would prefer to pass the text.

My guess is that I need to make some changes around the code below in the AccountLogin.cshtml, but I'm not positive.

`@if (ViewData["Activated"] != null)
{
    <text>
    $(function() { 
        $('#HgiBudgets_Membership_LoginPanel0_Username').val(@Html.Raw(Serenity.JSON.Stringify(ViewData["Activated"])));
        $('#HgiBudgets_Membership_LoginPanel0_Password').focus();
    });
    </text>
}
`

Sorry if this seems like a basic question, this is all still very new to me.

![loginscreendoublemessage](https://cloud.githubusercontent.com/assets/19471794/16928573/0fc44ce8-4cf9-11e6-92e8-5cb12e1b583a.PNG)

**Comment by volkanceylan** [comment]
Where does these texts (Username, Password) comes from? If they are captions remove them if you won't use them, or move them to a better place.

**Comment by mlutzow** [comment]
Thanks for the hint, I'll post something later.

**Comment by mlutzow** [comment]
Thank you, I've been able to get the screen looking much better. I needed to make several changes in two different files. There may have been better ways but this is what I was able to do.  There are two small formatting issues, but I'll come back to these later unless someone has a hint or suggestion of where I need to look.

First change, decorate the LoginForm.cs -- Removed my PlaceHolder string and changed to DisplayName decorator.

```       
//...
        [PasswordEditor]
        [DisplayName("Use 'Active Directory' Password")]
        [Required(true)]
        public string Password { get; set; }

        [DisplayName("HGI User ID, Case sensitive")]
        public string Username { get; set; }
//...
```
Next went into site.membership.less and had to made changes in several places.

First change was to h3.buttons, added width (comments are temporary while I'm learning) Also changed padding the fourth item from 158px to 120px.

'''
//...
    .buttons 
    {
        padding: 8px 0 0 120px /*158px*/;
		/*mlutzow added*/
		width:200px;
		//text-align: left;		
		/*End adds*/
//...
'''

Next change was to .s-Form .field, again added width

```
//...
.s-Form .field 
    {
        /*padding: 8px;*/
        /*mlutzow added*/
        width:300px;
        /*End Adds*/
        padding-top: 0px;
        padding-bottom: 0px;
        padding-left: 158px;
        padding-right: 0px;
        position: relative;
    }
...//
```

finally added width.

```
//...
    .s-Form .caption 
    {
        padding: 6px 10px;
        color: #d7d9da;
        position: absolute;
        top: 20px;
        left: 150px;
        font-size: 16px;
        transition: 0.5s ease all;
        pointer-events: none;
        /*mlutzow added*/
        width: 300px;
        /*End Adds*/
    }
.../
```
In the end I've wound up with a form like below:

![loginscreenbetternotperfect](https://cloud.githubusercontent.com/assets/19471794/16958282/752b5606-4da5-11e6-8dda-4778f43da5e2.PNG)

**Comment by jsbUSMC** [comment]
You're going to have to adjust the cshtml for the forgot password link. Add style rules to the `.less` file to fix the placement. As far as the input field captions, I will have to go back to my code and dig through to find out where you may have gone wrong. I will post a gist for you to help out. I am sorry if I didn't do a very good job posting the complete code necessary to make the changes to the login screen. I will fix that article if there are any discrepancies. There's been a few issues posted concerning the customization of the login screen from folks who followed my wiki article so I think it's best that I update that article with as complete information as possible regarding the changes I made.

**Comment by mlutzow** [comment]
Thank you jsbUSMC, I think you did a fine piece of work with the wiki article you posted. Unfortunately my experience levels with C#, ASP.NET MVC, CSS, JScript, etc. were practically non-existent before I was handed this project. I did learn from the article. You can't anticipate everything a user base might run into, of course I'd never pass up the opportunity to review and take in any extra information you'd like to pass on.

**Comment by jsbUSMC** [comment]
No worries. We all start learning somewhere. I'm pretty sure I had to fiddle with the HTML inside the template to get what I wanted. Also then having to add or alter the LESS files to achieve what I needed. I may even have created a mixin. I'll post some more stuff, I want the tutorial to be a good walk through for altering styles within the project, so devs can get comfortable with the design side and not just the functionality part of the app development.

**Comment by mlutzow** [comment]
Thanks.

**Comment by mlutzow** [comment]
jsbUSMC, is there any way I can PM you?

**Comment by jsbUSMC** [comment]
Yeah, sorry, I've been a little busy. I put up a gist with all the files that I changed to complete the login screen customization: AccountLogin.cshtml, site.membership.less, a custom css file I made for my site, and LoginForm.cs. It's available [here](https://gist.github.com/jsbUSMC/c89ac1b8c6464903a90c1ba55726bab7)
