### ISSUE TITLE
When Using Nuget Update Commands recieve message Update not available.

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#936]
Noticed that there are Serenity updates available. I'm able to update the 'master' template file using Tools => Extensions and Updates.

When I open the project and use either the 'Update-Package Serenity.Web' or the 'Update-Package Serenity.CodeGenerator' commands I receive the standard '...There are no updates available...' message.

I find this puzzling.

**Comment by volkanceylan** [comment]
You probably should report to NuGet, if there is really an update pending. Template update and NuGet package updates are not same thing. There are more updates to template than Serenity nuget packages.

**Comment by mlutzow** [comment]
When was the last time you posted an update to NuGet?

**Comment by volkanceylan** [comment]
Half an hour ago. https://www.nuget.org/packages/Serenity.Core/

**Comment by mlutzow** [comment]
Okay, the available packages must not have been updated through the NuGet system when I tried to update, came in this morning and the update commands are working fine.
