### ISSUE TITLE
Latitude / Longitude

### ISSUE THREAD

**Issue by RouteTech** [volkanceylan/Serenity#937]
I was trying out the meeting demo and tried to enter lat/long values (40.702805466,-73.981046767) but the form does accept negative values. My test data set has valid lat/long values but the form fails with the value "from the 'set' method falls outside of the vMin / vMax range". I've tried setting the Range attribute but that doesn't seem to work. Any ideas?

**Comment by volkanceylan** [comment]
See FAQ in wiki
