### ISSUE TITLE
Additional Permission

### ISSUE THREAD

**Issue by Me-Kal** [volkanceylan/Serenity#938]
how to add additional permission like permission based on branch .
note : branch from database table

thanks

**Comment by solabar** [comment]
You don't mean this do you?
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_register_permissions_in_serene.html

**Comment by Me-Kal** [comment]
could pleae give me example for this 

if you don't use a permission key with any of them but still want to show it in permission dialogs, you can use RegisterPermission attribute on assembly (write this anywhere in YourProject.Web):

[assembly: Serenity.ComponentModel.RegisterPermissionKey("MySpecialPermissionKey")]

i tried but not working

**Comment by volkanceylan** [comment]
It's working. Permission based on database table is not possible simply. Use something like roles and its interface.
