### ISSUE TITLE
Cannot get FluentMigrator to install database on IIS 7 production server

### ISSUE THREAD

**Issue by kerrgibson** [volkanceylan/Serenity#939]
I have just started using Serenity and it is a great product!

But I am confused about how to deploy it using Visual Studio 2015 Web publishing.
I'm developing on my personal machine (With a local SQL Server) and then trying to deploy on an internal web server set up with IIS 7 and SQL Server 2008R2. I tried to publish it to the server using "Publish *Project*.Web", but it only published the application, not the database. I have created a database using FluentMigrator and it works on my development SQL Server.

Thinking maybe I needed to use the "Databases" section in Publish:Settings I tried that. I put in the data source - but the database of course does not exist yet- so I used *Project*_Default_v1 (where *Project* is my actual project name). Here I wasn't even sure if I could just use any name. I also checked "Use this connection string at runtime" and "Update Database" using \[Auto schema update\] (Not sure about these settings a well).

Once on the Preview screen- clicking the "Start Preview" button works fine and shows the files that will be installed. But clicking on the "Preview Database" link gives me the following error:

Web deployment task failed. (Could not generate deployment script.
Internal Error. The database platform service with type Microsoft.Data.Tools.Schema.Sql.Sql130DatabaseSchemaProvider is not valid. You must make sure the service is loaded, or you must provide the full type name of a valid database platform service.

This same error appears if actually publishing. If I publish without the DB info, the application will install and I can connect to it with a browser- it just gets an error because it cannot find the database.
I assure you that "Web Management Service" and "Web Deployment Agent Service" are both running on the server. And I have installed the latest SSDT software on my development machine.

Anyway- my questions:

1. Am I even following the correct process to get FluentMigrator to install the DB on the production IIS server?
2. If so, why does the internal error show up? Must something else be installed on my development machine or on the IIS server?

Thanks in advance!

**Comment by volkanceylan** [comment]
You just create your empty database in production server, and change connection strings in web.config, thats all.

**Comment by jsbUSMC** [comment]
Also check to make sure that you have SQL server connections enabled over TCP/IP. I think that's disabled by default, and the SQL Server services are running.

**Comment by kerrgibson** [comment]
That worked. Thanks so much! I was over-complicating it. However I did need to create a new user "IIS APPPOOL\xyz" to get it to work.

**Comment by kerrgibson** [comment]
Just one more thing if you will, then I will close out. I cannot get the "loading" icon to stop spinning in the corner of the header. I tried to do what the manual set but it did not seem to work. Is there a way to do this in the latest version of Serenity?

**Comment by volkanceylan** [comment]
You might have another extension, check what ajax request is running.

**Comment by kerrgibson** [comment]
Never mind. I was mistaken about something. Thanks for all your help!
