### ISSUE TITLE
Problem deploying to IIS

### ISSUE THREAD

**Issue by JesseBn** [volkanceylan/Serenity#94]
I have deployed the solution to IIS however when the website is viewed from any browser it seems like there is no formatting data. Any idea what could be causing this or how to fix it? I have attached a screenshot with how the site is being displayed.

![capture](https://cloud.githubusercontent.com/assets/16333035/12222272/d1f1bbb2-b80b-11e5-8b98-f1100d3ee0d2.png)

**Comment by volkanceylan** [comment]
You application pool user can't access to files. Try granting IIS_IUSR read access.

**Comment by JesseBn** [comment]
IUSR did have read access. I did notice that site.css and fontawsome-webfont.woff2 had 404 errors in the IIS log. I have resolved the issue for the moment by copying the site.css from the debug deployment in visual studio. 

Did I miss a step in the deployment to IIS which caused these files to not be created?

**Comment by volkanceylan** [comment]
Probably their build action was set to none.
