### ISSUE TITLE
Sergen Stop Working

### ISSUE THREAD

**Issue by reybatacjr** [volkanceylan/Serenity#942]
Hi again, after using on 10 different forms/list vies sergen suddenly stop working.

sergen : The term 'sergen' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.

please help.

**Comment by jsbUSMC** [comment]
Restart Visual Studio

**Comment by volkanceylan** [comment]
It's stated in guide that sometimes package manager console can't set paths correctly. Restart or use file explorer.
