### ISSUE TITLE
Enum value

### ISSUE THREAD

**Issue by caitingting** [volkanceylan/Serenity#943]
Hi again.
public enum FieldFlags
{
    None = 0,
    Insertable = 1,
    Updatable = 2,
    NotNull = 4,
    PrimaryKey = 8,
    AutoIncrement = 16,
}

I define a similar to the above enumeration. If my value is 3, I would like to display the value of 1 and 2 of the display name,but I don't know how to do it.

**Comment by volkanceylan** [comment]
Write a custom formatter, see samples in template, but for enum, this not place for such question, try StackOverflow maybe.
