### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by amorpeth** [volkanceylan/Serenity#945]
Hey,

Hopefully not a stupid question, but whats the best way to replace the text logo with an image logo?

Thanks!
Andrew

**Comment by jsbUSMC** [comment]
Edit the _Layout.cshtml and add your image

**Comment by amorpeth** [comment]
Thanks so much that did the trick!!

For anyone else, here's what I did in _Layout.cshtml:

```
<a href="~/" class="logo">
                @*<span class="logo-mini"><i></i></span>*@
                <span class="logo-lg">
                @*<i></i><b>@LocalText.Get("Navigation.SiteTitle")</b>*@
                <img src="/Unilytic-Logo.png" alt="Unilytic">
            </span>
            </a>
```

**Comment by volkanceylan** [comment]
Thanks for sharing
