### ISSUE TITLE
import excel data & customize excel export  report 

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#946]
Hi Guys,
      1. The first one is how to import excel data to the table like customer table click import button the excel data store to customer table 

       2. Then how to perform customize excel export reports like export customize pdf report based

**Comment by sayuga** [comment]
The excel import and export are powered by EPPlus. I suggest looking at http://epplus.codeplex.com/ for more information.

**Comment by GOBIBE** [comment]
how to implement the epplus concept in seren web app

**Comment by volkanceylan** [comment]
No samples sorry, add a button and implement your logic with a service call.

**Comment by volkanceylan** [comment]
@GOBIBE, 2.3.7.5 has excel import sample

**Comment by GOBIBE** [comment]
thanks volkan

**Comment by GOBIBE** [comment]
@ volkan The build error present on the 2.3.7 version error how to rectify and the site.css nothing to present its like module based error

**Comment by volkanceylan** [comment]
@GOBIBE try with latest. It's possible nuget bug with extensionless files, i changed lessc to lessc.js in 2.4.0
