### ISSUE TITLE
[Bug] UserPreference: column sort order not persisted

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#947]
Dear @volkanceylan,
I think that I found a bug: the user preferences should save also the sort type (asc or desc) of the columns, but seems to be not working:

![image](https://cloud.githubusercontent.com/assets/17425690/16982552/c41ea9d6-4e70-11e6-8a58-d599dd28f668.png)

Here is a screenshot from a brand new 2.3.3 serenity template with the

    Serenity.DataGrid.defaultPersistanceStorage = window.sessionStorage;
 
directive in the ScriptInitialization.ts file: as you can see the small arrow in the column header is set like a desc sorting but rows are sorted in the asc way.

P.S. There is a typo in the serenity guide:

![image](https://cloud.githubusercontent.com/assets/17425690/16982644/52b07198-4e71-11e6-9c79-e3df2c0f8152.png)

should be "ScriptInitialization.ts" and not "SiteInitialization.ts" :-)

Thanks as always
Bye

**Comment by volkanceylan** [comment]
Ok, i'll have a look.

**Comment by volkanceylan** [comment]
Fixed in 2.3.7, thanks.

**Comment by marcobisio** [comment]
Thank you very much!
