### ISSUE TITLE
Responsive Dialogues - my fields in site.css not shown by VS intellisense?

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#948]
Hi community,

I am trying to change my dialogues windows to multi-column.

I can see that it is done in the CSS like shown below:
![image](https://cloud.githubusercontent.com/assets/15879719/16982965/35a880ea-4e62-11e6-8262-63ac1264ceda.png)

My trouble is getting my fields from XYZrow.ts to activate in my new part of CSS. The fields are not shown in the intellisense dropdown which I would really like it to do ;)

Any suggestions anyone?

**Comment by volkanceylan** [comment]
Me too, not something i can.

**Comment by biggikalli** [comment]
Ok, thank. I assume it won't matter though the intellisense doesn't work? ;)
