### ISSUE TITLE
Grid Editor and Grid Editor dialog

### ISSUE THREAD

**Issue by abelal83** [volkanceylan/Serenity#949]
Hi, 

I recently upgraded to the latest serene and noticed sergen has new options to create Grid Editor and Grid Editor dialog. I've just created a new page using these and apart from a few new .ts files there doesn't seem to be any difference in the web page itself. I know I'm missing something as I assume there should be a grid that I can edit in the page?

**Comment by volkanceylan** [comment]
It's an option added by @dfaruque. It just generates two additional files, that you might use later for master detail scenarios. There is no change in UI.
