### ISSUE TITLE
Error in Compilations

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#95]
Hi JaiQ
I checkout the code for solving following error in my project which is comminf for a page which contains about 100 fields - 
Input string was not in a correct format.
and i am not able to find that particular field out of 100 for this error.

So i took checkout of the code and after troubleshooting the compilation, I am getting following error in compilation in project Serenity.Script.Core.
I download https://visualstudiogallery.msdn.microsoft.com/2d42d8dc-e085-45eb-a30b-3f7d50d55304/file/151666/1/TypeScript_1.4_VS2013.exe for TypeScript.

2>E:\Projects\Serenity\_TFS\Serenity.Script.Core\Resources\Serenity.Core.d.ts(27,9): error TS1005: Build: ';' expected.
2>E:\Projects\Serenity\_TFS\Serenity.Script.Core\Resources\Serenity.Core.d.ts(27,19): error TS1005: Build: ';' expected.
2>E:\Projects\Serenity\_TFS\Serenity.Script.Core\Resources\Serenity.Core.d.ts(27,28): error TS1005: Build: ';' expected.
2>E:\Projects\Serenity\_TFS\Serenity.Script.Core\Resources\Serenity.Core.d.ts(28,5): error TS1129: Build: Statement expected.
2>E:\Projects\Serenity\_TFS\Serenity.Script.Core\Resources\Serenity.Core.d.ts(31,1): error TS1128: Build: Declaration or statement expected.

Can you please help me to remove these errors?
I will be very thankful to you.

**Comment by volkanceylan** [comment]
Update typescript to latest version. These seems like typescript errors.

**Comment by volkanceylan** [comment]
Latest should be 1.7.5 or 1.7.6

**Comment by volkanceylan** [comment]
That error, input string was not in a correct format, probably comes from a Int32 field. Check fields you manually mapped that could return string instead of an integer.

**Comment by ramveersgh** [comment]
Thank you very much volkanceylan!
The issue is resolved, it was due to manually modified the fields from Int to String but was not replaced everywhere.

Now code is also compiled.
Thanks!

**Comment by MBagherii** [comment]
I have this error : input string was not in a correct format... when I clicked on a row for edit that it was throw this exception. I didn't manually mapped fields... what should I do????
