### ISSUE TITLE
Using WEB API like /services/model/list 

### ISSUE THREAD

**Issue by alexsandrocruz** [volkanceylan/Serenity#950]
How do I authenticate to access webservices through another application, such as a mobileapp? I tried ~ / services / model / list that works in the browser that I'm logged in another browser returns "you're not logged in."

Is there a solution or suggestions for my problem? 

(Congratulations Serenity is the best framework I know to asp.net) :)

**Comment by Estrusco** [comment]
See issue https://github.com/volkanceylan/Serenity/issues/806

**Comment by alexsandrocruz** [comment]
Thanks mrs. Estrusco and volkanceylan.
