### ISSUE TITLE
Connect database in xyzDialog.ts

### ISSUE THREAD

**Issue by caitingting** [volkanceylan/Serenity#951]
Hello.
I want to Connect database in xyzDialog.ts,but I have no way.It's been bothering me for a long time. 
Can you give me some advice? 
Thank you very much.

**Comment by volkanceylan** [comment]
You can't connect to database in client side code. You write a service.

**Comment by caitingting** [comment]
Thank you for your generous answers. 
I would like to add a button in the editor, this button can be modified to modify the table and other tables of the data.
 onClick: () => {}      In this,how to write call service ?
There are examples can refer to it?

**Comment by volkanceylan** [comment]
```MyService.Update(new SaveRequest<MyRow> { Entity = new MyRow.... }});..```
