### ISSUE TITLE
Grid Editor - SlickGrid with pre set Date Range 

### ISSUE THREAD

**Issue by rolembergfilho** [volkanceylan/Serenity#952]
Hey.

In the grid editor, the date range filter have two fields, a from to date range, like image below:

![date range - actual](https://cloud.githubusercontent.com/assets/19523455/17010465/978847b4-4eda-11e6-9297-ed436c0dbaf4.png)

In Dashboard, we have a Visitor widget, with this kind of date range filter (image below)

![date range](https://cloud.githubusercontent.com/assets/19523455/17010490/ce1f813e-4eda-11e6-9b64-fb3d82c0171f.png)

How can I set or configure this kind of date range filter in Grid Editor (in Slick Grid)

**Comment by jsbUSMC** [comment]
This is from a jQuery plugin that comes with AdminLTE called [bootstrap-daterangepicker](https://github.com/dangrossman/bootstrap-daterangepicker). You can include that plugin on the page or pages you'd like to incorporate it, or you can create a widget/editor using that plugin instead. Make sure you include the necessary resources on your pages.

**Comment by rolembergfilho** [comment]
I found it. Thanks

My doubt now is how change the default date range filter to this new one (bootstrap-daterangepicker).

Did you do it in your grid?

**Comment by jsbUSMC** [comment]
No I haven't, sorry.

**Comment by volkanceylan** [comment]
In your createQuickFilters method, find those pickers by their class name etc, remove one, attach your custom picker to remaining one. but don't have sample.

**Comment by rolembergfilho** [comment]
Hey @volkanceylan 

Could you add this sample in Serene?
