### ISSUE TITLE
User role permission

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#953]
Hi guys,

              1. How to set the user only perform read or modify or delete or both specified operation will be perform , giving specified access permission to user role

**Comment by volkanceylan** [comment]
See wiki, faq in guide...

**Comment by GOBIBE** [comment]
where to find wiki sir

**Comment by Estrusco** [comment]
https://github.com/volkanceylan/Serenity/wiki

**Comment by GOBIBE** [comment]
thank you @volkanceylan ,Estrusco
