### ISSUE TITLE
Error creating new Project with template 2.3.6

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#954]
After upgrading the Template, it cannot create a new project.
![image](https://cloud.githubusercontent.com/assets/20357414/17016047/164e2b32-4f25-11e6-8e82-1b50c708290d.png)
This is with VS 2013

**Comment by volkanceylan** [comment]
This is fixed in latest template, e.g. 2.3.5.0

**Comment by rgilsimoes** [comment]
I used 2.3.6 and the same thing happens.

**Comment by volkanceylan** [comment]
Not NuGet packages, template. 

Serene 2.3.6 doesn't have reference to 14.0 of ComponentModelHost, that error should not be possible

```
    <Reference Include="Microsoft.VisualStudio.ComponentModelHost, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\packages\VSSDK.ComponentModelHost.10.0.4\lib\net40\Microsoft.VisualStudio.ComponentModelHost.dll</HintPath>
      <Private>True</Private>
      <Private>False</Private>
    </Reference>
```

**Comment by rgilsimoes** [comment]
After installed VS 2015 and re-installing Serene Template the problem fixes on VS2013.
