### ISSUE TITLE
How can I set Some rows Disable Edit   When I choose A row In EditForm.

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#955]
Hi ,Nice to see you!
When I  choose One row  In EditForm. such like this

![image](https://cloud.githubusercontent.com/assets/20295114/17020514/8c12c6da-4f74-11e6-8201-1635639506c2.png)

Can I get the choose value to make some row Edit disable. (as that say attribute [Updatable(false)])....
Is the XYZDialog.ts ? Or  Where Should I code and Code what ?  
I need your help , Thank you Sincerely !

**Comment by volkanceylan** [comment]
In your dialog constructor

```
form.SomeField.change(e => {
   Serenity.EditorUtils.setReadOnly(form.SomeAnotherField, true);
});
```

**Comment by weiguanhai** [comment]
Thank you.. what you said  make a prefect effect !

**Comment by volkanceylan** [comment]
form.SomeAnotherField.getGridField().toggle(false)

**Comment by weiguanhai** [comment]
I can't meet the toggle method, just show like this
![image](https://cloud.githubusercontent.com/assets/20295114/17088167/5a40101c-524a-11e6-97a7-6c887ed0ec5b.png)

**Comment by vinaykulkarni89** [comment]
You need to add parenthesis () after getGridField
