### ISSUE TITLE
Refresh linked data on dialog after dropdown update

### ISSUE THREAD

**Issue by kerrgibson** [volkanceylan/Serenity#956]
I looked for the answer to this but cannot seem to find the right info. Please excuse my newbie ignorance.

I need to re-populate linked data on a dialog when the user changes a joined record using a LookupEditor, including if InplaceAdd = true and the user has added a new record or changed it.

An example would be in Northwind when in the Product dialog. You can assign or add a new supplier. If we wanted to display the supplier phone number on the Product dialog- it would need to update if the supplier updates or we add a new supplier.

In another case- we may want to populate non-linked data with defaults from the linked record. In Northwind, on the Order dialog, you have (non linked) shipping information. When adding a customer from the LookupEditor, how could we populate the shipping fields with default customer shipping address information?

So, what handler must I override to detect a value change in the LookupEditor? And what must I do to get the data in the dialog to conform to the linked record? Should this be done in the xyzDialog.ts script?

Also, is there full documentation (other than just the code) of Serenity objects and their methods?

Thank you!

**Comment by volkanceylan** [comment]
Something like 
```
form.MyLookupField.changeSelect2(e => {
     MyLookupService.Retrieve({
         EntityId: Q.toId(form.MyLookupField.value)
     }, response => {
         form.SomeDependentField.value = response.Entity.SomeField.value;
     }
});
```

**Comment by volkanceylan** [comment]
There is wiki, guide as documentation, and comments in code.

**Comment by kerrgibson** [comment]
OK, I'll try this. But where to put it? Would it go in the xyzDialog.ts script? And what is the handler that I must override? Would it be onchange() ?

**Comment by volkanceylan** [comment]
Just put it in constructor.

**Comment by volkanceylan** [comment]
See populate linked data sample in latest template (2.3.7.4)

**Comment by kerrgibson** [comment]
Just wanted to inform you that I did implement this and it worked great. I did have to test for blank data first though or else it failed the lookup. Thanks for your help!

E.g.

`
form.MyLookupField.changeSelect2(e => {
    if (form.MyLookupField.value != "")
    {
         MyLookupService.Retrieve({
             EntityId: Q.toId(form.MyLookupField.value)
         }, response => {
             form.SomeDependentField.value = response.Entity.SomeField.value;
     }
    else
    {
         form.SomeDependentField.value = null; 
    }
    
});
`

**Comment by john20xdoe** [comment]
@kerrgibson 

Thumbs-up for the advice on using `change()` instead of `changeSelect2()`!. Been pulling my hair out all day because the inPlaceAdd button does not reflect the changes back in the form.
