### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by soongsta** [volkanceylan/Serenity#957]
Hi There

I downloaded the whole project from github and tried to compile. It gave me the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "C:\Users\soongsta\Documents\Visual Studio 2015\Projects\Serene2\Serenity-master\Serenity.Web\..\tools\node\lessc.cmd C:\Users\soongsta\Documents\Visual Studio 2015\Projects\Serene2\Serenity-master\Serenity.Web\style\serenity.less > bin\Debug\serenity.css" exited with code 9009.	Serenity.Web	C:\Users\soongsta\Documents\Visual Studio 2015\Projects\Serene2\Serenity-master\Serenity.Web\Serenity.Web.csproj	1089

**Comment by volkanceylan** [comment]
See output window for errors from less. You should clone full repository with GIT, not download

**Comment by rgilsimoes** [comment]
You are missing the "bin" directory inside "node". It happened to me too.

**Comment by emocasares** [comment]
This is the error that I see on my output window. How to fix it?

1>EXEC : error : Cannot find module 'c:\Tech\serenitu1\Serene1\Serene1\Serene1.Web\tools\Node\less\bin\lessc'
1>      at Function.Module._resolveFilename (module.js:338:15)
1>      at Function.Module._load (module.js:280:25)
1>      at Function.Module.runMain (module.js:497:10)
1>      at startup (node.js:119:16)
1>      at node.js:929:3
1>c:\tech\serenitu1\Serene1\Serene1\Serene1.Web\Serene1.Web.csproj(2225,5): error MSB3073: The command ""c:\tech\serenitu1\Serene1\Serene1\Serene1.Web\tools\node\lessc.cmd" "c:\tech\serenitu1\Serene1\Serene1\Serene1.Web\Content\site\site.less" > "c:\tech\serenitu1\Serene1\Serene1\Serene1.Web\Content\site\site.css"" exited with code 8.

**Comment by emocasares** [comment]
Note: I installed the template from Visual Studio and created a new project, then when I compile the solution I had the first error telling me that tsc.exe was not found, so I installed TypeScript integration with Visual Studio 2013. This error about lessc.cmd is the second one that I have

**Comment by jsbUSMC** [comment]
Make sure that the bin folder is included in your project by right clicking and selecting Include

**Comment by soongsta** [comment]
I followed these steps:
1. Sign in to GitHub and GitHub Desktop before you start to clone.
2. On GitHub, navigate to the main page of the repository.
3. Under your repository name, click Clone or download.
4. Click Open in Desktop to clone the repository and open it in GitHub Desktop.
5. In GitHub Desktop, after verifying the name and location on your hard drive where you'd like to clone the repository, click Clone.

found here https://help.github.com/desktop/guides/contributing/cloning-a-repository-from-github-to-github-desktop/

And it worked. Thanks very much.
