### ISSUE TITLE
Handling millions+ of records

### ISSUE THREAD

**Issue by amorpeth** [volkanceylan/Serenity#958]
Hey,

One of our SQL tables holds millions of records. Displaying this in Serenity results in a page timeout. I assume this is because Serenity is pre-loading all records? I guess I can control the timeout somewhere?

Preferably, what would be the best approach to implement a load on demand approach? e.g. initially load the last months records, and only load more as per a defined date range.

Appreciated some simple pointers fit for a noob :)

Andrew

**Comment by Estrusco** [comment]
See https://github.com/volkanceylan/Serenity/issues/375
and https://github.com/volkanceylan/Serenity/issues/406

**Comment by amorpeth** [comment]
Hey,

Thanks very much or your response. I am looking for a way to do the same, but on the actual grid, rather than the drop downs. Can I take a similar approach?

I am reasonably new at C# dev so a bit more detail is appreciated.

Andrew

**Comment by volkanceylan** [comment]
Grid doesn't load all records, unless you set rowsPerPage to 0. If it is timing out, you miss some index.

**Comment by amorpeth** [comment]
When you say miss some index, what does that mean exactly?

**Comment by volkanceylan** [comment]
Missing table index on column that you use
