### ISSUE TITLE
Code from Northwind OrderDetailDialog not working on my implementation.

### ISSUE THREAD

**Issue by rsbatacjr** [volkanceylan/Serenity#959]
Hi, I tried to copy this functionality from Northwind where in I select a product from a "lookupeditor" it will populate the price. I followed the MovieTutorial on how to add details from master dialog (execute sergen, create ts file for Editor and Dialog) but this code is not working :( on my investigation it appear that my Price field is not defined.

            this.form.ProductID.changeSelect2(e => {
                var productID = Q.toId(this.form.ProductID.value);
                if (productID != null) {
                    this.form.UnitPrice.value = ProductRow.getLookup().itemById[productID].UnitPrice;
                }
            });

**Comment by Estrusco** [comment]
See if in ProductRow the field UnitPrice has the LookupInclude attribute.

**Comment by reybatacjr** [comment]
Thanks a Lot man, that did the trick :)
