### ISSUE TITLE
Missing serenity/Serenity.Externals.js

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#960]
Hi,
After nuget update I get a javascript reference missing.
In the _references.js file it has this line:
/// <reference path="serenity/Serenity.Externals.js" />
but there is no such file anymore.

**Comment by rgilsimoes** [comment]
When I run the project I get this error: 

Script data Template.PropertyPanel is not found in registered script list!

The login Panel does not show up.

**Comment by Estrusco** [comment]
The _references.js must be these row

```
/// <reference path="jquery-ui-1.11.4.js" />
/// <reference path="jquery-2.2.3.js" />
/// <autosync enabled="false" />
/// <reference path="serenity/Serenity.CoreLib.js" />
/// <reference path="serenity/Serenity.Externals.js" />
/// <reference path="serenity/Serenity.Externals.Slick.js" />
/// <reference path="serenity/Serenity.Script.UI.js" />
/// <reference path="site/YourProject.Web.js" />
```

**Comment by volkanceylan** [comment]
references.js is for intellisense, not used at runtime. do you have other errors in browser console. do you have PropertyPanel.Template.html file under ~/views/templates/ with correct file casing.

**Comment by rgilsimoes** [comment]
I don't have that file

**Comment by volkanceylan** [comment]
You have errors in corelib. Try it in chrome. And english please.

**Comment by rgilsimoes** [comment]
Here it is:
![image](https://cloud.githubusercontent.com/assets/20357414/17095822/683f5070-524e-11e6-950d-46cf0423f40e.png)
