### ISSUE TITLE
I add a custom button in EditForm,how to add action?

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#961]
Hi ,  so nice to see you again!  I got in trouble ,

![image](https://cloud.githubusercontent.com/assets/20295114/17052501/4e28ffee-5030-11e6-8434-5621f0444525.png)
as the picture ,the last button is my custom in the XYZDialog.ts.  like this
![image](https://cloud.githubusercontent.com/assets/20295114/17052678/1fb83d2c-5031-11e6-98d2-061f866b11d7.png)

 how can I add onclick action to update data to the table from database , and  up to me custom the sql sentence.   I am just a new user , if can ,tell me more details about it please !
Thank you in advance.

**Comment by Estrusco** [comment]
```ts
[...]
onClick: () =>
{
    var request = this.getSaveEntity();
    // Update or other endpoint service (see your generated XYZService.ts)
    XYZService.Update(
        request,
        response => {
            [...]
        },
        {
            blockUI: false,
            onError: err => {
                [...]
            }
        }
    }
);
}
```

**Comment by volkanceylan** [comment]
You can't send SQL to server, even if you can it would be a big supermassive security black hole.
