### ISSUE TITLE
HTML OrderDetailReport

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#962]
Hi all!

I would implement HTML Report. I saw that in Serene there is an OrderDetailReport but I can not figure out how or where it is executed. From Order grid there are only Excel and PDF
Can someone show me the way?

**Comment by volkanceylan** [comment]
It is in OrderDetailDialog

**Comment by volkanceylan** [comment]
Sorry, OrderDialog

**Comment by Estrusco** [comment]
Oh thank you! Sorry, I've missed it
