### ISSUE TITLE
Implement Auto Count

### ISSUE THREAD

**Issue by reybatacjr** [volkanceylan/Serenity#963]
Hi, how can I implement auto count on form?

I would like to make my Invoice form have an auto incremeting number: "INV-0001"

**Comment by reybatacjr** [comment]
Sorry I hit Submit button :D format of Invoice Number is "INV-####"

Thanks

**Comment by volkanceylan** [comment]
See serial auto numbering sample in latest template.

**Comment by biggikalli** [comment]
WOW, how this will come in handy.
Funny how I was exactly at this moment praying for a solution like this..
Thank you Maestro Volkan :+1:

**Comment by AmuthaKondusamy** [comment]
Hi @volkanceylan ,

I have gone through the serial auto numbering in Serenity demo. But I don't need the Prefix text. I need a auto serial number to be in integer format. Can u please help me with this

**Comment by volkanceylan** [comment]
So, you need to code that :)
