### ISSUE TITLE
Lookup fails - getlookup() - ChangeSelect2 - Leading 0/zero in ID field

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#964]
Hi community,

I am having trouble with a LookupEditor in a Dialogue.
The dependant field doesn't update when I choose an item which starts with a zero from the dropdown.
See image below (where `getlookup()` doesn't work):

![image](https://cloud.githubusercontent.com/assets/15879719/17077942/9432e614-50d3-11e6-8dcf-e4b7026a67ca.png)

But here it works, where the ID row starts with something else than zero:

![image](https://cloud.githubusercontent.com/assets/15879719/17077946/e8dc179e-50d3-11e6-9532-079503aebb36.png)

I have scanned and read through previous issues here in volkanceylan/Serenity and have found some threads where I see some similarities with my problem. Like issue #386 which dates back to March '16 but haven't been able to see a solution that fits my case.

I used the code from OrderDetailDialog.ts and it works although I have changed it in my attempts to fix the leading zero's issue:

            this.form.EmployeeId.changeSelect2(e => {
                var EmployeeId = Q.text(this.form.EmployeeId.get_text());
                if (EmployeeId != null) {
                    this.form.EmployeeName.value = Stillingar.StarfsmennRow.getLookup().itemById[EmployeeId].EmployeeName.toString();
        }

I would truly appreciate if anyone has suggestions on how to fix this.

**Comment by biggikalli** [comment]
I know that some would suggest that I would use an incremental Identity field in my database to use in the `getlookup(),` function - but I want this EmployeeID field to be my primary key, hence this setup....unless composite primary is perhaps the solution??

**Comment by volkanceylan** [comment]
What is Q.text etc doing there, why not this.form.EmployeeId.value

**Comment by biggikalli** [comment]
Hi Volkan,

It seems to not matter, it was just me trying to make the value more like a text value, not an int or nvarchar isolating the leading zero in front of some ID's.

The problem still exists although I use the original:

            this.form.EmployeeId.changeSelect2(e => {
                var EmployeeId = Q.toId(this.form.EmployeeId.value);
                if (EmployeeId != null) {
                    this.form.EmployeeName.value = Stillingar.StarfsmennRow.getLookup().itemById[EmployeeId].EmployeeName;
        }
    });

The problem is the leading zero's.

Should I use a composite primary or is there a more simple solution?

**Comment by volkanceylan** [comment]
Don't use toId, its for integers, if your ID values has leading zero, they are not integers!

**Comment by biggikalli** [comment]
Ok, thanks.

I was on the wrong road...I found the answer in issue #279 which you resolved earlier in February.
I simply added a non primary key integer field into my table. Solved everything.

Should have seen it earlier.

Thank you again for your support.
I am really thrilled about how Serenity has developed the past few months... typescript etc.

Regards,
BK
