### ISSUE TITLE
Resharper

### ISSUE THREAD

**Issue by wdhodges** [volkanceylan/Serenity#965]
Hey Volkan! Hope everything is going well in your part of the world. Hey so I wanted to give you some information on something by jetbrains called resharper. It's an amazing (and I mean AMAZING) visual studio extension that I use that helps with code readability, tips on what something should be or look like. Its basically intellisense on steroids. There's so much it can do. While the price for it is about $120 a year, it's free for open source projects. And as your engine grows, I highly recommend you get this. Seriously it's simply amazing.

Go take a look at jetbrains resharper. If you have any question let me know. At least sign up for the free trail so you can see the amazing Ness that comes from resharper and .net cover.

I just wanted you to know this because I figured it could help out, alot! And we all want to see the Serenity Engine grow :)

William

**Comment by wdhodges** [comment]
Wednesday I'll the Serenity code through the resharper and .net cover and .net memory profiler and I'll post the results of you would like me to.

**Comment by jsbUSMC** [comment]
ReSharper is awesome

**Comment by volkanceylan** [comment]
Thanks a lot for suggestion. I know that tool, but i have different opinions on that one. First of all, it takes Visual Studio to crawl. Also, it messes with my key bindings even if i tell it not to. Yeah there is an option that doesnt actually work which couldnt be fixed by them for ten years straight. I think its an overrated tool, a toy made for rookies.

**Comment by wldkrd1** [comment]
Dunno which version you've used, but in my experience, they fixed the performance problems years ago (~2008 when I first tried it, it was unusable)

**Comment by volkanceylan** [comment]
I don't know, some of my teammates uses it and a solution with 250 projects (no i didn't design it :), loading takes 10 times more, so they turn off Resharper, load solution, unload most of projects then turn it on etc. I might be sometimes overreacting but messing with my shortcuts is unforgivable :-)

**Comment by volkanceylan** [comment]
I'm acting similar towards notebook producers who remove home end page down page up keys from their models, because Apple or some other genius did so

**Comment by wldkrd1** [comment]
> solution with 250 projects
Well...yeah. I'm going to put much of the blame on Visual Studio remaining 32-bit for this rather than Resharper, but still. Good news is you soon won't need to reference 250 projects which will speed VS tremendously but you'll still keep the ability to step into them. 

> messing with my shortcuts is unforgivable
Agreed
