### ISSUE TITLE
Removing Scripts from _LayoutHead.cs partial

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#966]
I am about to try this, but I thought to remove all the scripts from the `_LayoutHead.cshtml` partial and instead create a new partial and insert that into the `_Layout.cshtml` partial right before the closing `</body>` tag. This way the scripts are downloaded and rendered last instead of blocking the rendering of the page. This should make the site appear to load faster, even after accounting for bundling, minification, and gzipping of the scripts. Is there any reason not to do things this way?

**Comment by volkanceylan** [comment]
If you write an inline script in some of views, jQuery etc. wont be available. You may leave jQuery, pace etc at top but still have to be careful. Order might get messed in some pages. I dont think that detail is really so noticable but you are free to try.

**Comment by jsbUSMC** [comment]
Thanks for the input.
