### ISSUE TITLE
Live Serenity Sample: Cultural Learnings of Serene for Make Benefit Glorious Applications of Serenity!

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#967]
Hi there @volkanceylan 

I write this to thank you for an incredible donation to the world of web development.

I am now finishing my second deliverable system built on the Serene platform. Previous one was built during the Saltarelle "era" and the newest with the Typescript compiler. The change from Saltarelle to Typescript was a genius one and made the template so much better in endless ways.

My strong opinion is that Serenity is more than ready and that the template should be accessible live as a demo via a website under your ruling. Bringing it closer to the mass audience of devs who might miss to see the incredible potentials it brings in practicality, streamlining, time saving etc. 

The fact that a potential user needs to download the template, install, create a new project and fire it up with an IDE is perhaps too big of a threshold, in my opinion, for some people to experience the beauty of Serenity. Although the favorable publicity is growing fast into a high level.

I myself, was lucky enough to get past this "threshold" but I easily could have missed to discover Serenity all-together if I hadn't had the time and curiosity as I had at that moment in the past.

I am more than willing and hereby offer to provide the resources and credentials needed to run such a website in a setting suited best for an online demo. My two penny suggestion is that an Azure VM (SQL server with IIS) or simply a Web App would be launched under a name friendly domain where the newest update of Serenity and other related samples (e.g. the Movie Tutorial) is accessible directly for display and surface testing.

I realize that such a project calls for an extra work effort but no one says that it should fall on your shoulders as I have seen many dedicated Serenity soldiers in the community that are more than capable, trustworthy and willing of assisting in maintaining a fresh display website with the newest versions and a daily reset of the databases. That includes me, although I am far from being able to call myself anything near to a developer or a programmer. I am actually a CPA/Auditor that just happened to have some good ideas for applications that have now been given lift-off by your unselfish donation and hard work around Serenity.

How about it? Is this something that is feasible and beneficial in your opinion?

Kind regards,
Biggi
A true **Serenist** _(e. a big enthusist/endorser of Serenity)_

> biggi@biggi.is

**Comment by volkanceylan** [comment]
Thanks @biggikalli for your ideas, comments, and enthusiastic support. 

I think demo is a nice idea, and a Serenity user already setup one at http://serenedemo.azurewebsites.net/ (thanks @samdubey), which is continuosly deploying whenever i push to Serene repository.

It's probably free because of his BizSpark subscription, but I don't know about resources allocated or how long he would be able to keep it there. A dedicated Azure virtual machine with SQL would be nice.

In addition to demo, getting mentioned in some blogs / articles by known professionals in community would give a real boost to Serenity, but so far i didn't see any. It might be due to my advertisement ability which is probably the weakest one :)

There are many things i would like to have with Serenity. Having a home web site, a blog where i can announce / detail new features and samples, more tutorials, more tests, better in code documentation, some articles in CodeProject and similar dev sites, .NET Core support, custom dynamic entities, UI designer, plugin system, CRM, CMS, task management and many more.

I'm currently devoting more than half of my spare time to Serenity. It's not possible to spend more due to my full time job, so things are moving a bit slower than i'd like. Still, Serenity is getting more frequent updates than many other projects with better resources and support.

I feel like a community is being formed nowadays, and its good news.

**Comment by biggikalli** [comment]
Dear @volkanceylan,

Thank you for replying and sharing your thoughts about this idea.

Yes - since I got to know Serenity in October 2015, there has been a much more rapid growth in users, especially in the last few months and that is good news... as long as some of those users give back and participate in the community in some way.

Yes, yes - Serenity is getting more updates than many other corporate funded projects and that fact is simply incredible. It is extraordinary that Serenity is already moving at a pace most web development groups/companies could only dream of. 

Yes, yes, yes - Serenity and you personally should absolutely get all the positive publicity that you have earned. I am really surprised to hear that there has not been any major external discussions, introduction or articles written already. I call upon the community and Serenity users to give your work full exposure and credit and also help spreading the word. I know that feeling people get when wanting to keep great tools to yourself and under-the-wraps, but that must and will not be the case here!

I really was not aware of the effort and kindness of Sameer of already setting up a live demo -  A great call by Sameer. I though searched for a live demo recently and did not find one - hence this idea here.

In my opinion, the live demo should be plain vanilla out of the repository and with frequent rollback/resetting of SQL data. That way it is more stable and presentable and you could keep it more out in the public which is really important in my opinion. There absolutely should, at least, be a direct link from GitHub and the VS Gallery to a home website of Serenity where you can easily access the testing platform and all the other good resources you mentioned in your answer above.

I  am also in the Bizspark program but that does not last forever and meanwhile the Azure credits are appreciated, we need to think outside of that box. I am more than happy to contribute and support the Serenity community in any way I can. God knows that I am the least likely person to be helping others out with complex coding but there are many other ways people can contribute to the development and prosperity of Serenity.

I already have some ideas for a domain (always a first step, haha), so if you could please email me directly at your convenience I would send you my ideas. I also would really like to know your thoughts about a possible CMS for Serenity's upcoming website, e.g. the Umbraco platform which I see some potential in due to its .NET connection but the final choice of that would certainly be yours.

Please allow me to give back by getting a small ball rolling in your direction this time.
My hope with this is not to create any extra work or tasks for you - quite the opposite and you are more the welcome to keep answering me in "one-liners" :) That is just more than one could ask for in the light of things.

Also, if there are other Serenity users reading this thread - let's all participate in supporting this new community.

Kind regards,
Biggi

**Comment by wdhodges** [comment]
I'd be happy to help anyway that I can! Tell me what needs to be done and I'll try my best to complete it

**Comment by samdubey** [comment]
Same here

**Comment by volkanceylan** [comment]
Sorry for late reply, i'm planning to start with GitHub pages for Serenity home page / blog (not demo). If it doesn't work, we may consider other options. Bootstrap home page and blog looks fine, so don't know why it shouldn't.

For domain name, i have some ideas, but you don't have a contact address @biggikalli in GitHub. You can use my full name at search giants mail to contact me ;)

**Comment by paulobriennz** [comment]
im happy to help out too.. i own a hosting company in NZ so can supply a VM to run on..

**Comment by volkanceylan** [comment]
@paulobriennz thanks for offer. @biggikalli just got a cool domain name for Serenity, "serenity.is". He is now planning to set Azure VM and SQL, but if your offer is still i'll ask him not to. I don't expect much traffic and don't need much resources, but should have a windows VM with remote access and SQL. What do you say?

**Comment by samdubey** [comment]
@volkanceylan If you need good theme for Serenity Website Please let me know

I own multiple application license for following themes:

Very popular HTML theme Unify:
http://wrapbootstrap.com/preview/WB0412697

Umbraco StarterKit :
http://uskinned.net/demos/1365/

If anything else i can help you with, please let me know

**Comment by volkanceylan** [comment]
Thanks @samdubey. Unify looks good. I'll start with a home page and blog. There are some suitable samples there. I don't know much about Umbraco, do you think it'll worth learning curve / setting up time in comparison to writing a quick & dirty one using Serenity / ASP.NET MVC, as i don't need much features, other than markdown support yet?

**Comment by samdubey** [comment]
Umbraco has some learning curve,  for current requirement quick way with Serenity and ASP.NET MVC would be great option.

where should i send you link to download Unify theme? ( Gitter Chat / Email )

**Comment by volkanceylan** [comment]
I'm not sure if it would be fine licence wise. I can buy it no big deal.
