### ISSUE TITLE
what's error with the cascade ,help me please!

### ISSUE THREAD

**Issue by weiguanhai** [volkanceylan/Serenity#968]
Hi, nice to see you , Genius!
I follow the guide 
https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html
and code it. but got error like the picture
![image](https://cloud.githubusercontent.com/assets/20295114/17125279/af3b0d1c-5324-11e6-9932-103a873554fb.png)
and the second dropdownlist  said no matches found
![image](https://cloud.githubusercontent.com/assets/20295114/17125300/d7658cb8-5324-11e6-9811-51364de4d6a6.png)

is the step necessary？
![image](https://cloud.githubusercontent.com/assets/20295114/17125319/f7e4d7d2-5324-11e6-82f2-feacf8279897.png)

The follow is my step
First  of all,I generate code for two tables using Sergen
the first table is like this
![image](https://cloud.githubusercontent.com/assets/20295114/17125338/3568c9e2-5325-11e6-87b4-8dfb7d12d81c.png)
and the second table is 
![image](https://cloud.githubusercontent.com/assets/20295114/17125347/4c211a9a-5325-11e6-8603-0a550d778553.png)

Second,  I add the two table LookupScript()

Third, I  add ForeignKey,and LookupInclude like this
![image](https://cloud.githubusercontent.com/assets/20295114/17125420/c8b91dbe-5325-11e6-84cf-d7d490b606d9.png)

And finally, I add LookupEditor in myCustomForm
![image](https://cloud.githubusercontent.com/assets/20295114/17125441/0d0e836e-5326-11e6-9bd6-f56796251159.png)

But it doesn't work, error is that I mention at the first.
Is there I miss something or do something error?  
I'm looking forward to your kind advice.

**Comment by volkanceylan** [comment]
Your CascadeFrom should be ArticleType not ArticleTypeId

**Comment by weiguanhai** [comment]
oh my god! it work effectively !!! Sincerely thank you, that's wonderful !

I just code like this
![image](https://cloud.githubusercontent.com/assets/20295114/17126419/d633809c-532f-11e6-8ce1-7f214b927274.png)
Maybe I should write the detials like the issue than before ,

**Comment by weiguanhai** [comment]
I also want know CascadeFrom = "ArticleType"  , what's the mean of the "ArticleType" ,  is part of the  "ArticleTypeRow" Name or others?

**Comment by volkanceylan** [comment]
Your first lookup editor is on property ArticleType

**Comment by weiguanhai** [comment]
Sorry! I still can't understand ,  is there? which number is?
No1   at the first of ArticleTypeRow
![image](https://cloud.githubusercontent.com/assets/20295114/17132151/0d913232-5353-11e6-8a9e-0f3fd400c5eb.png)

No2  at  the end of ArticleTypeRow
![image](https://cloud.githubusercontent.com/assets/20295114/17132176/2a524ff0-5353-11e6-95dc-153f0cd18c02.png)

No3 at ArticleSecondTypeRow

[DisplayName("Article Type Id"), NotNull]
        [ForeignKey("[dbo].[ArticleType]", "ID"), LookupInclude]
        public Int32? ArticleTypeId
        {
            get { return Fields.ArticleTypeId[this]; }
            set { Fields.ArticleTypeId[this] = value; }
        }

**Comment by volkanceylan** [comment]
Man look at properties where you put LookupEditor attribute in your form definition, cascadeFrom is name of property or editor that an editor will attach to

**Comment by weiguanhai** [comment]
If I only have one table ,to store my data about "country" "province" "city".  Can I use it for my CustomerForm with Cascade
the table have a column "ParentId" , that Self association.
like this
![image](https://cloud.githubusercontent.com/assets/20295114/17133626/75e20950-5359-11e6-89c7-7929793dea10.png)

First, I generate code for the tables using Sergen

Second, I add LookupScript at the first of BAreas
![image](https://cloud.githubusercontent.com/assets/20295114/17133729/e712ec2a-5359-11e6-9f00-8a68d701946f.png)

Third, I add ForeignKey and lookupInclude
![image](https://cloud.githubusercontent.com/assets/20295114/17133753/049919b8-535a-11e6-93ae-8ae9ddc7ac56.png)

And finally I edit in myCustomerForm
![image](https://cloud.githubusercontent.com/assets/20295114/17133797/34825f22-535a-11e6-8213-09595a65804b.png)


Is there I code error? or something miss?
or We can't use one table to make cascade relation

**Comment by volkanceylan** [comment]
Are you really reading what i wrote? CASCADEFROM IS PROPERTY NAME IN YOUR FORM!

So, 

```
[LookupEditor(typeof(Entities.BAreasRow)), CascadeFrom = "Country", CascadeField= "ParentId")]
public Int32 Provice { get; set; }
```

**Comment by volkanceylan** [comment]
Please someone speaking Chinese, explain him

**Comment by weiguanhai** [comment]
Oh,Oh...Sorry..I finally understand it,  really thanks for your patient teach!

**Comment by weiguanhai** [comment]
You know, all the areas data are in the "BAreas" table .  In the ”country“ column,  the dropdownlist data has some of the province and city data.  How can I filter them?    Is the filterField of the LookupEditor can be used ?  how can I use it

**Comment by volkanceylan** [comment]
You might need to write a custom lookup editor for it. See samples in Serene.

**Comment by weiguanhai** [comment]
Is like this picture?
![image](https://cloud.githubusercontent.com/assets/20295114/17198337/03031092-54a7-11e6-9480-61a982055717.png)

and it works perfectly,  Thans for you genius answer!

**Comment by volkanceylan** [comment]
You're welcome. You could also write a custom editor instead of custom lookup, but this is also fine.
