### ISSUE TITLE
Error when running List function

### ISSUE THREAD

**Issue by fazanan** [volkanceylan/Serenity#969]
Hi Jaiq,

I have this error

{"Error":{"Code":"Exception","Message":"Property accessor 'xxxxx' on object 'xxx.xx.xxx.Entities.xxxx' threw the following exception:'RevisionNo field on TableRow is read before assigned a value!'",

It's occured when running this script 

List<TableRow > dataCollectionD = connection.List<TableRow >(new Criteria("ID= " + id.ToString()));

Any suggestion?

Regards,

**Comment by volkanceylan** [comment]
List only loads table fields, you are trying to read a view field.

**Comment by mjacoup** [comment]
what we can do for view case ?
