### ISSUE TITLE
UTC time conversion in Columns/Form

### ISSUE THREAD

**Issue by paulobriennz** [volkanceylan/Serenity#970]
Hi, i am storing the time of an event in UTC time (thats how is given to me) in the database table.

Is there any snazzy way of converting the time to local time in the Grid/Form?

I looked in to adding an Expression, but ideally dont want to do conversion in SQL as C# has better date handling stuff and it would be maybe a variable in C# that hold my current UTC offset.

Any suggestions welcomed

Thanks 
Paul

**Comment by volkanceylan** [comment]
Add [DateTimeKind(DateTimeKind.UTC)] to your field

**Comment by paulobriennz** [comment]
Perfect, thank you again.  

Just to confirm for anyone else, apply this to the field in your xxxxxxRow.cs file
