### ISSUE TITLE
update version errors 2.2.2 to 2.3.7

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#972]
Hi Guys,
          i am using  serenity 2.2.2 version now i update 2.3.7 version , now i have Lot of error is present in my error list, how to rectify this

**Comment by GOBIBE** [comment]
The error present in site.css exited with code 8 and build error like  module.js:340   throw err; modules load errors

**Comment by volkanceylan** [comment]
Update-Package Serenity.Web.Tooling -Reinstall

if doesn't work 

rename Serenity.Web.Tooling.nupkg file to .zip, open it, copy paste files under content/tools directory to your tools directory.

**Comment by GOBIBE** [comment]
![image](https://cloud.githubusercontent.com/assets/18713252/17176200/2f538c72-5429-11e6-8bfa-749c1dc98946.png)
 its not working

**Comment by volkanceylan** [comment]
You have missing files, copy paste, period.
