### ISSUE TITLE
Close button says Close in addition to the X image

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#975]
![funkyclose](https://cloud.githubusercontent.com/assets/2817543/17193622/cdde1702-5408-11e6-82b7-ad972a3131eb.png)

Since updating to 2.4.0, the close button on my dialog boxes is actually showing the word "Close" on top of the X image.

**Comment by volkanceylan** [comment]
Are you sure you didn't update jQuery / jQuery UI by mistake?

**Comment by wldkrd1** [comment]
jQuery is version 2.2.3, jQueryUI is version 1.12.0

**Comment by volkanceylan** [comment]
Hmm Serene has 1.11.4, they might have changed something with dialogs. I wouldn't update it yet.

**Comment by wldkrd1** [comment]
Yup, that was it. Didn't see anything indicating a breaking change in their notes, but clearly that doesn't mean anything. Thanks!

**Comment by volkanceylan** [comment]
It might be not a breaking change, but we are using a custom css with a subset of their original css (Aristo). Might need to add a rule to hide that close text.

**Comment by wldkrd1** [comment]
Reopening to keep track of it

**Comment by wldkrd1** [comment]
Yeah, the DOM structure is different.
Old:
`<button><span class="ui-button-icon-primary ui-icon ui-icon-closethick"></span><span class="ui-button-text">Close</span></button>`

New:
`<button><span class="ui-button-icon ui-icon ui-icon-closethick"></span><span class="ui-button-icon-space"></span>Close</button>`

**Comment by volkanceylan** [comment]
Think need to add this CSS

.ui-button-icon-only {
    text-indent: -9999px;
}

**Comment by wldkrd1** [comment]
Yeah, that'll do it.

**Comment by volkanceylan** [comment]
Added CSS with latest update, but still need to test new versions of jQuery and jQuery UI before updating.

**Comment by sumalokesh** [comment]
Hello,

I came across one of your very old posts regarding jquery and jquery-ui updates.

I am upgrading to jquery2.2.3 and jquery-ui-1.12.1.  Eventually I will go with jquery 3.0.  For now I am following migration guidelines. 
I am having the same issue where text 'close' is coming behind 'X' image.  How can I resolve this?

![quickview](https://cloud.githubusercontent.com/assets/4367943/22515248/da4c41a2-e86f-11e6-84d1-b7e7f4dea5f9.PNG)

**Comment by volkanceylan** [comment]
You see my comment two above? Thats what i did.

**Comment by sumalokesh** [comment]
I am sorry..I am very new to jquery.  I have to upgrade both jquery & jquery-ui.  As wldkrd1 has mentioned..I have the exact same version - jQuery is version 2.2.3, jQueryUI is version 1.12.0

In jquery - ui - 1,12, we already have - 
/* to make room for the icon, a width needs to be set here */
.ui-button-icon-only {
	width: 2em;
	box-sizing: border-box;
	**text-indent: -9999px;**
	white-space: nowrap;
}

This is generated code from console-
<div class="ui-dialog-titlebar ui-corner-all ui-widget-header ui-helper-clearfix ui-draggable-handle">
     ::before
     <span id="ui-id-2" class="ui-dialog-title">Product Quickview</span>
     <button type="button" class="ui-button ui-corner-all ui-widget **ui-button-icon-only** ui-dialog- 
         titlebar-close" title="Close">
         <span class="ui-button-icon ui-icon ui-icon-closethick"></span>
         <span class="ui-button-icon-space"> </span>Close
     </button>
  ::after
</div>

Can you please let me know what needs to be changed/added?  By your update - comment two above did you mean "Added CSS with latest update"??

I appreciate your input.  Thanks.  Suma.

**Comment by volkanceylan** [comment]
Sorry thats all i know, use chrome dev tools, F12

**Comment by sumalokesh** [comment]
Thanks.  Will try it.

Just to confirm - 
By comment two above did you mean "Added CSS with latest update"??  Bcos you had also mentioned not to update UI..

**Comment by Hectort9021** [comment]
This is already fix or it´s the same? 
I´m asking because I have the same issue and using jquery 3.3 and UI 1.12.1.

Please let me know if somebody knows how to fix this permantly witout adding that CSS code.

Thanks.
