### ISSUE TITLE
about,Dialog add button

### ISSUE THREAD

**Issue by thisXYH** [volkanceylan/Serenity#976]
I added a button in a dialog box, and it can work properly, but there is no way the same as the original button to refresh the data corresponding to the Grid, and how to achieve refresh Grid

**Comment by volkanceylan** [comment]
In dialog,

Serenity.SubDialogHelper.triggerDataChange(this.element);

**Comment by thisXYH** [comment]
Hope this is not a stupid question, I do not know where to write this code, my code is this.
` protected getToolbarButtons() {
            var buttons = super.getToolbarButtons();

            buttons.push({
                title: '\u6587\u7ae0\u4e0b\u67b6\u0028\u4e0b\u67b6\u540e\u8981\u5237\u65b0\u9875\u9762\uff01\u0029',
                cssClass: 'send-button',
                onClick: () => {

                    var action = new ArticleReportOffBulkAction();
                    var ss: string[] = [this.entity.Id.toString()];
                    
                    action.done = () => { Serenity.SubDialogHelper.triggerDataChange(this.element); }
                    action.execute(ss);
                    //this.dialogClose();
                   // Serenity.SubDialogHelper.triggerDataChange(this.element);
                }
            });

            return buttons;
        }`
Emergence of this issue: Can not read property 'triggerHandler' of undefined,

**Comment by volkanceylan** [comment]
Try with triggerDataChange(this). It's probably Saltaralle generic to typescript issue.

**Comment by thisXYH** [comment]
perfect! I succeed !  thank !thank!than! you
