### ISSUE TITLE
xyzTableRow.cs ForiegnKey Attribute, More than one field

### ISSUE THREAD

**Issue by mlutzow** [volkanceylan/Serenity#977]
Hopefully this is something I just missed in the documentation..  I've been using the Row field definition of the form:

'[DisplayName("Address Code"), Column("Address_Code"), ForeignKey("refCustomer_Addresses", "Address_Code"), LeftJoin("addr")]'

successfully throughout the application. However there are in some certain cases where I need to use two fields to create an adequate join. For instance, above I'd prefer to use ((a.Customer_Number = b.Customer_Number) AND (a.Address_Code = b.Address_Code.)).

Can I do this using the FoeignKey attribute above or should I define this somewhere else and refer to it in my ...Row.cs file.

Thank you for any assistance.

**Comment by volkanceylan** [comment]
Use [LeftJoin] attribute on top of row, you can write arbitrary SQL there for join condition.

**Comment by mlutzow** [comment]
Thank you for the quick response.

**Comment by Estrusco** [comment]
Also there is an example in wiki https://github.com/volkanceylan/Serenity/wiki/LeftJoinAttribute%20%5BMapping%5D

**Comment by mlutzow** [comment]
Gentlemen, thank you for your help, worked out great.  I'm going to post the final form of my code...on the outside chance it might help someone in the future.

One additional question, the Left Join works well, is there anyway to specify a Left-Outer-Join?

```//...`
 [LeftJoin("jAddr", "[budgets].[refCustomer_Addresses]", "T0.Company_Code = jAddr.Company_Code AND T0.Customer_Number = jAddr.Customer_Number AND T0.Address_Code = Addr.Address_Code")]

public sealed class MainTableRow : Row, IIdRow, INameRow
//...
        [DisplayName("Address Code"), Column("Address_Code")] 
        [ForeignKey("[budgets].[refCustomer_Addresses]", "Address_Code")]
        [Size(10)]
        public String AddressCode
        {
            get { return Fields.AddressCode[this]; }
            set { Fields.AddressCode[this] = value; }
        }

        [DisplayName("Address Hint")]
        [Expression("jAddr.[City] + ', ' + jAddr.[State] + '  ' + jAddr.[Country]")]
        [ReadOnly(true)]
        [LookupInclude]
        public String AddressHint
        {
            get { return Fields.AddressHint[this]; }
            set { Fields.AddressHint[this] = value; }
        }
//...

**Comment by volkanceylan** [comment]
Left join and left outer join is same thing

**Comment by mlutzow** [comment]
Yep, my mistake, don't know what I was thinking about.
