### ISSUE TITLE
ImageUploadEditor updated again after insert?

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#978]
I have a grid inside a tab for my table (Like Movies in Person Dialog example) When I click to open editor and then "Add New". It will successfully add the first file, but when I try to add another file later I get the "update affected 2 row while 1 was expected" error. I do not have any triggers on the table at all. I am using Firebird. My table is as follows with 3 columns, none of my columns are set to not null and orderID is not PK (So I can have multiple files with the same OrderID) ;

[DisplayName("Orderid"), Column("ORDERID"), QuickSearch, LookupInclude]
        public Int32? Orderid
        {
            get { return Fields.Orderid[this]; }
            set { Fields.Orderid[this] = value; }
        }

        [DisplayName("Attch Dt"), Column("ATTCH_DT")]
        public DateTime? AttchDt
        {
            get { return Fields.AttchDt[this]; }
            set { Fields.AttchDt[this] = value; }
        }

        [DisplayName("Filename"), Column("FILENAME"), Size(300), QuickSearch, ImageUploadEditor(AllowNonImage= true, FilenameFormat = "Orders/Documents/~")]
        public String Filename
        {
            get { return Fields.Filename[this]; }
            set { Fields.Filename[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Orderid; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.Filename; }

It looks like it Inserts, then after the "ImageUploadBehavior.OnAfterSave" it update again. What have I missed? I am sure there is a logical reason it does this (temp filename, then filename maybe) but I can't find where or how to change this. Would I need to add some criteria somewhere? I need to look at multiplefileupload but I need to be able to upload files to the same order at different times so I am not sure that would change the behavior anyway. Here is my call stack;

 	Serenity.Data.dll!Serenity.Data.SqlHelper.CheckExpectedRows(Serenity.Data.ExpectedRows expectedRows, int affectedRows) Line 140	C#

 	Serenity.Data.dll!Serenity.Data.SqlHelper.Execute(Serenity.Data.SqlUpdate query, System.Data.IDbConnection connection, Serenity.Data.ExpectedRows expectedRows) Line 131	C#
 	Serenity.Web.dll!Serenity.Services.ImageUploadBehavior.OnAfterSave(Serenity.Services.ISaveRequestHandler handler) Line 192	C#
 	Serenity.Services.dll!Serenity.Services.SaveRequestHandler<SereneNM.NotaryManager.Entities.DocumentsRow, Serenity.Services.SaveRequest<SereneNM.NotaryManager.Entities.DocumentsRow>, Serenity.Services.SaveResponse>.AfterSave() Line 41	C#
 	Serenity.Services.dll!Serenity.Services.SaveRequestHandler<SereneNM.NotaryManager.Entities.DocumentsRow, Serenity.Services.SaveRequest<SereneNM.NotaryManager.Entities.DocumentsRow>, Serenity.Services.SaveResponse>.Process(Serenity.Data.IUnitOfWork unitOfWork, Serenity.Services.SaveRequest<SereneNM.NotaryManager.Entities.DocumentsRow> request, Serenity.Services.SaveRequestType requestType) Line 290	C#
>	SereneNM.Web.dll!SereneNM.NotaryManager.Repositories.DocumentsRepository.Create(Serenity.Data.IUnitOfWork uow, Serenity.Services.SaveRequest<SereneNM.NotaryManager.Entities.DocumentsRow> request) Line 18	C#
 	SereneNM.Web.dll!SereneNM.NotaryManager.Endpoints.DocumentsController.Create(Serenity.Data.IUnitOfWork uow, Serenity.Services.SaveRequest<SereneNM.NotaryManager.Entities.DocumentsRow> request) Line 19	C#

**Comment by volkanceylan** [comment]
Please set loggin level to Debug in web.config. You'll have files under App_Data/log directory. Find the UPDATE statement that fails with this error. Try it in SQL etc, why updates more than one record. Probaby due to an identity error. 

This error is not raised when you do multiple updates, but when you have an UPDATE statement that is expected to update one record only but updates multiple.

**Comment by volkanceylan** [comment]
I put that check to SqlUpdate, because some devs in my team forgot to add WHERE statement, or put an invalid WHERE statement, so they actually updated all records and we noticed it much later. It's a common error so wanted to avoid that.

**Comment by jdready5** [comment]
I'm glad you put the check in there, that kind of safety net is almost always needed. Thanks for the tip on the logging in web config. That helps a ton. The INSERT has the filename as "temporary/875081bfe1d24c90a67581f441dfab0c.pdf " then the UPDATE has the modified filename "Orders/Documents/00034/00034353_x5ov6u5f2j53e.pdf" I understand this and this is needed. The program works as it should, this is an error on my part of poor database design I had not yet fixed. (No PK) My table will always have multiple files under the same OrderID. I need to add a PK to my table and that should fix it the UPDATE issue for this table. Thank you very much for all your hard work on this platform!

**Comment by jdready5** [comment]
Maybe you could point me in the right direction, now that I have added my PK to the database when adding a new document the update now fails because the PK is null at that time. I believe Serenity uses a "fake" id for this normally but I guess not in this situation. Where should I call for the last inserted id or is that even possible since both the insert and update are on the same transaction. Here is the log and some of the code.


[D] 2016-07-30T01:47:37.040 ExecuteNonQuery
INSERT INTO DOCUMENTS (DOC_ID, ORDERID, ATTCH_DT, FILENAME) VALUES (@p1, @p2, @p3, @p4) --- PARAMS --- @p1=<NULL> @p2=34353 @p3=7/30/2016 12:00:00 AM @p4=temporary/6b5b6c7ae8e647fd998c2f302a54b884.pdf 
[D] 2016-07-30T01:47:37.250 END - ExecuteNonQuery
[D] 2016-07-30T01:47:37.300 ExecuteNonQuery
UPDATE DOCUMENTS SET FILENAME = @p1 WHERE (DOC_ID = @p2) --- PARAMS --- @p1=Orders/Documents/_/_nivqjtjyyqcrq.pdf @p2=<NULL> 
[D] 2016-07-30T01:47:37.529 END - ExecuteNonQuery

My order/documents ts file

namespace SereneNM.Manager {

    @Serenity.Decorators.registerClass()

    export class NOrderDocumentsGrid extends Serenity.EntityGrid<DocumentsRow, any>
    {
        protected getColumnsKey() { return 'Manager.NOrderDocuments'; }
        protected getDialogType() { return DocumentsDialog; }
        protected getIdProperty() { return DocumentsRow.idProperty; }
        protected getLocalTextPrefix() { return DocumentsRow.localTextPrefix; }
        protected getService() { return DocumentsService.baseUrl; }

        constructor(container: JQuery) {
            super(container);

        }

        protected subDialogsDataChange() {

            super.subDialogDataChange();
            Q.reloadLookup('NotaryManager.NOrderDocuments');

        }


        protected getInitialTitle() {
            return null;
        }

        protected getGridCanLoad() {
            return this.orderID != null;
        }

        private _orderID: number;

        get orderID() {
            return this._orderID;
        }

        set orderID(value: number) {
            if (this._orderID != value) {
                this._orderID = value;
                this.setEquality(DocumentsRow.Fields.Orderid, value);
                this.refresh();
            }
        }
    }
}

and my documents dialog


namespace SereneNM.Manager {

    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.responsive()
    export class DocumentsDialog extends Serenity.EntityDialog<DocumentsRow, any> {
        protected getFormKey() { return DocumentsForm.formKey; }
        protected getLocalTextPrefix() { return DocumentsRow.localTextPrefix; }
        protected getNameProperty() { return DocumentsRow.nameProperty; }
        protected getService() { return DocumentsService.baseUrl; }

        protected form = new DocumentsForm(this.idPrefix);

        constructor() {
            super();        


            this.form.Orderid.change(e => {
                var OrderID = this.form.Orderid.value.toString();
        if (Q.isEmptyOrNull(OrderID)) {
            this.setDocumentDetails({});
            return;
        }

    });}
        

                private setDocumentDetails(details: Manager.NOrderRow) {
            this.form.Orderid.value = details.OrderId;
        }

    }   
}

**Comment by volkanceylan** [comment]
Did you add [Identity] to to your DOC_ID field and set row as IIdRow and return DocId.

**Comment by jdready5** [comment]
I am so sorry I even posted that last one, I simply needed to add AutoIncrement to DOC_ID field. Thanks so much for all your help though I really appreciate the quick response.

**Comment by jdready5** [comment]
One last question if I may, Is it possible to adjust the FilenameFormat parameter {1} which is identity (my DOC_ID) to include my ORDER_ID as well (another field) without causing too much strange behavior?

**Comment by volkanceylan** [comment]
Currently it can only contain ID of the table its in. Youll need to write a custom ImageUploadBehavior for that and disable the default one.

**Comment by jdready5** [comment]
Okay that makes sense, Thanks again!

**Comment by volkanceylan** [comment]
You're welcome. That makes sense, ill try to add that option later.
