### ISSUE TITLE
Expression not showing on Grid

### ISSUE THREAD

**Issue by rsbatacjr** [volkanceylan/Serenity#979]
Hi, thank you volkan for the Get New Serial example. I am having problem with my master detail entry.
Foreign key name for detail is blank after hitting save button. I have foreign key on my detailRow.cs and expression field that is suppost to be shown on columns.cs.

sorry for my english :(

**Comment by volkanceylan** [comment]
Set MinSelectLevel on your column. Guide states this.

**Comment by volkanceylan** [comment]
Also you need to set it manually, view/expression columns don't work in master detail

**Comment by reybatacjr** [comment]
thanks, i will retry following the MovieCast on Movie Tutorial. It was working before I delete the whole database to mimic publication on demo server.
