### ISSUE TITLE
Question: What is the best way to generate a Report using the Serenity Framework?

### ISSUE THREAD

**Issue by brettbeard** [volkanceylan/Serenity#98]
For example, if I wanted to generate an Invoice from an Order in the Northwind sample data.  What is the best to link data in a form to a different view or report (or invoice)?  How should that be done?  Thanks.

BTW, Serenity is awesome.

**Comment by volkanceylan** [comment]
I use SSRS or wkhtmltopdf for reporting. I need to make some more changes to stabilize before i'll make them public.

**Comment by Shraddha996** [comment]
@volkanceylan  
Hello sir,
I want to use SSRS for reporting, as you said after some changes you will make them public 
I could not find the link here
would be great if you share this here

Thanks and regards
