### ISSUE TITLE
Dialog - Wrong column data saved to grid

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#980]
Hi,

I have a small issue with a LookupEditor (changeSelect2) within a dialog.

In the dialog it shows the correct column data in the dropdown to choose from.
However when saved, it writes the table's ID column data to my grid row. Not the EmployeeID column data (from the dialog field) like I want it to do.

See picture:

![image](https://cloud.githubusercontent.com/assets/15879719/17243626/53fa6f06-556d-11e6-9ab6-33774272c756.png)

See code in xxxDialog.ts

`            this.form.EmployeeId.changeSelect2(e => {
                var EmployeeId = Q.toId(this.form.EmployeeId.value);
                if (EmployeeId != null) {
                    this.form.EmployeeName.value = Stillingar.StarfsmennRow.getLookup().itemById[EmployeeId].EmployeeName;
        }
    });`

I hope this is a simple rookie error, easily solved.

**Comment by rsbatacjr** [comment]
I think you need to check your xxxColumns.cs, add EmployeeID property in before Employee Name or replace ID.

**Comment by biggikalli** [comment]
Thank you @rsbatacjr for quick reply :)

I am such a newbie...
Here is the beginning of my xxxColumns.cs

    [ColumnsScript("Ferdir.Utanlands")]
    [BasedOnRow(typeof(Entities.UtanlandsRow))]
    public class UtanlandsColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Int32 Id { get; set; }
        [EditLink]
        public String Username { get; set; }
        public String EmployeeId { get; set; }
        public String EmployeeName { get; set; }
        public String TravelId { get; set; }
        public DateTime ReportDate { get; set; }
  `
If I change this, would my grid not get all messed up?

**Comment by Estrusco** [comment]
I think you must add an EmployeeDescrption in your Utanlands Row where

```cs
        [DisplayName("EmployeeID"), ForeignKey("employtable...", "ID", LeftJoin("jEmployee")]
        public Int32? EmployeeID
        {
            get { return Fields.jEmployeeDescription[this]; }
            set { Fields.jEmployeeDescription[this] = value; }
        }

        [DisplayName("Employee"), Expression("jEmployee.[Description...]"), QuickSearch]
        public String jEmployeeDescription
        {
            get { return Fields.jEmployeeDescription[this]; }
            set { Fields.jEmployeeDescription[this] = value; }
        }
```

and then in UtanlandsColumns add jEmployeeDescription

**Comment by biggikalli** [comment]
Thanks @Estrusco - I think I see where you are going with this and it sounds logical.
I will try your solution and post results...

**Comment by volkanceylan** [comment]
What columns you have in employee table? Something like ID, EmployeeID and EmployeeName? And which of these are mapped in your TravelMaster table?

**Comment by volkanceylan** [comment]
Please post your EmployeeRow and TravelMasterRow

**Comment by biggikalli** [comment]
Am I missing/forgetting some joins?

**EmployeeRow:**

`

    [ConnectionKey("Perdiem"), DisplayName("1Employees"), InstanceName("1Employees"), TwoLevelCached]
    [ReadPermission("Administration")]
    [ModifyPermission("Administration")]
    [LookupScript("Stillingar.Starfsmenn")]
    public sealed class StarfsmennRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id")]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Employee Id"), PrimaryKey, Column("EmployeeID"), Size(50), QuickSearch]
        public String EmployeeId
        {
            get { return Fields.EmployeeId[this]; }
            set { Fields.EmployeeId[this] = value; }
        }

        [DisplayName("Email"), Size(100)]
        public String Email
        {
            get { return Fields.Email[this]; }
            set { Fields.Email[this] = value; }
        }

        [DisplayName("Employee Name"), Size(50), NotNull, LookupInclude]
        public String EmployeeName
        {
            get { return Fields.EmployeeName[this]; }
            set { Fields.EmployeeName[this] = value; }
        }`

**TravelMasterRow:**

`

    [ConnectionKey("Perdiem"), DisplayName("2TravelMaster"), InstanceName("2TravelMaster"), TwoLevelCached]
    [ReadPermission("Administration")]
    [ModifyPermission("Administration")]
    [LookupScript("Ferdir.Utanlands")]
    public sealed class UtanlandsRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), PrimaryKey]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Username"), Column("Username"), Size(100), NotNull, QuickSearch]
        public String Username
        {
            get { return Fields.Username[this]; }
            set { Fields.Username[this] = value; }
        }

        [DisplayName("Employee Id"), Column("EmployeeId"), Size(50), NotNull]
        [LookupEditor(typeof(PerDiem.Stillingar.Entities.StarfsmennRow), InplaceAdd = true)]
        public String EmployeeId
        {
            get { return Fields.EmployeeId[this]; }
            set { Fields.EmployeeId[this] = value; }
        }

        [DisplayName("Employee Name"), Column("EmployeeName"), Size(50), NotNull]
        public String EmployeeName
        {
            get { return Fields.EmployeeName[this]; }
            set { Fields.EmployeeName[this] = value; }
        }

        [DisplayName("Travel Id"), Column("TravelID"), Size(50), NotNull]
        public String TravelId
        {
            get { return Fields.TravelId[this]; }
            set { Fields.TravelId[this] = value; }
        }

        [DisplayName("Report Date"), NotNull]
        public DateTime? ReportDate
        {
            get { return Fields.ReportDate[this]; }
            set { Fields.ReportDate[this] = value; }
        }`

Again, here is my xxxDialog.ts:

`        
            this.form.EmployeeId.changeSelect2(e => {
                var EmployeeId = Q.toId(this.form.EmployeeId.value);
                if (EmployeeId != null) {
                    this.form.EmployeeName.value = Stillingar.StarfsmennRow.getLookup().itemById[EmployeeId].EmployeeName;
        }
            });`

Thank you for your assistance.

**Comment by volkanceylan** [comment]
I guess "ID" is identity in your EmployeeRow, your grid is showing this value. At the moment you don't have any joins in UtanlandsRow, don't know why. Do you really have EmployeeName etc in UtanlandsRow or expect them to get filled through joins?

First you should decide if you want Utanlands table to hold identity of employee (ID - 1, 2, 3, 4, 5) or string EmployeeID (081050491...) of Employee. I would choose to use ID, but its also possible to use other.

If you'll use EmployeeID everywhere, then set EmployeeID as identity of your employee row. Then editors will start to use that one. Or you need to define a custom lookup and set IdField to EmployeeId there.

**Comment by biggikalli** [comment]
Thank you Volkan.

You are right - I will choose to use ID in my Utanlands table instead of this string type EmployeeID that could possibly include leading zero's in it => Can lead to complications throughout the system.

Now I really look forward to dive in and learn how to define and use joins in Serenity. I see that it is difficult to build a sophisticated system/solution without that knowledge. 

Does Serenity automatically transcribe "already defined SQL relationships" into correct joins in Serenity with Sergen?? I haven't tried but I am curious.

**Comment by volkanceylan** [comment]
Yes if you add foreign keys, Serenity will add necessary joins and view fields. You should only have employee ID in your Utanlands to have better normalization

**Comment by biggikalli** [comment]
Great to know and I see the light now. 

Thank you.
