### ISSUE TITLE
Modification suggestion with PropertyPanel

### ISSUE THREAD

**Issue by tobesoeasy** [volkanceylan/Serenity#981]
~/Scripts/Serenity/Serenity.Script.UI.js  
line number:9722 
loadInitialEntity: function() {
			if (ss.isValue(this.propertyGrid)) {
			    this.propertyGrid.load(this.get_entity() || new Object());
			}
		}
English is not good, please forgive me

**Comment by volkanceylan** [comment]
You can override loadInitialEntity and load entity you like, e.g.

protected loadInitialEntity() {
     this.propertyGrid.load(someEntity);
}

**Comment by tobesoeasy** [comment]
Do not know why not get “propertyGrid”

 	Property 'propertyGrid' does not exist on type 'UserInformationPanel'.

**Comment by volkanceylan** [comment]
If you are using C# its

protected override void LoadInitialEntity

**Comment by tobesoeasy** [comment]
![111](https://cloud.githubusercontent.com/assets/13215836/17254311/d42f792c-55e6-11e6-838d-80fe78d6bb87.png)
It's been working, but it shows the error.
Thank you for your answer

**Comment by volkanceylan** [comment]
It is a .d.ts error, for now write (this as any).propertyGrid

**Comment by tobesoeasy** [comment]
Thank you very much for your patience.

**Comment by volkanceylan** [comment]
You're welcome. Intellisense should be fixed in latest.
