### ISSUE TITLE
InplaceAdd button click nothing happens

### ISSUE THREAD

**Issue by vishalaj1** [volkanceylan/Serenity#982]
Hi,

I have added option for inplaceadd. I can see the button and the custom text. However, nothing happens wen i click it.

I am trying to debug the serene library and find out what I am missing.

Any quick thought on this would help.

Regards,
Vishal

**Comment by volkanceylan** [comment]
Check browser console, read the error and set dialog type parameter if your lookup type and dialog type is not compatible

**Comment by vishalaj1** [comment]
Yes, you are right. The console gives an class exception. However, the value of dialog type should the edit dialog of the main entity right?

**Comment by volkanceylan** [comment]
@vishalaj1 read the guide please.

**Comment by vishalaj1** [comment]
It worked, i was not giving correct class name. 

For Others:

[LookupEditor( typeof(CARow),InplaceAdd =true, DialogType = "A.CA")]

Here I have Dialog class with name: A.CADialog

Thanks!

**Comment by volkanceylan** [comment]
If you dialog is A.CADialog, your lookup key should be A.CA too. I strongly recommend using compatible names, so you won't have to specify dialog type.

**Comment by vishalaj1** [comment]
1. Dint work
[LookupEditor( typeof(A.CARow),InplaceAdd =true)] 
lookupkey in CARow is A.CARow
Reason: Class it is trying to look for is CARowDialog

2. Dint Work
[LookupEditor( typeof(A.CARow),InplaceAdd =true)] 
lookupkey in CARow is A.CADialog
Reason: Class it is trying to look for is Actions.CARowDialog
