### ISSUE TITLE
Parent dialogue refresh from child dialogue refresh 

### ISSUE THREAD

**Issue by shailendrasingh03** [volkanceylan/Serenity#985]
Hi , opening another dialogue parent dialogue but once after updating record on child form parent data is not getting refresh . 

 buttons.push({
                title: 'Move',
                cssClass: 'alocate-button',
                onClick: () => {
                    if (this.entity.AlocaitonStatus == 'Checkin') {
                        new Asset.AssetAlocateDialog().loadByIdAndOpenDialog(this.entity.Id );

**Comment by jdready5** [comment]
Try Q.reloadLookup('yourEntity')

**Comment by shailendrasingh03** [comment]
No luck I tried after loading the entity . 
Remember I am opening dialog from another dialog

**Comment by jdready5** [comment]
In mine, I have 

protected subDialogsDataChange() {

            super.subDialogDataChange();
            Q.reloadLookup('MyModule.MyEntity');

        }

**Comment by volkanceylan** [comment]
Write reloadLookup in onSaveSuccess method of your subdialog.

**Comment by volkanceylan** [comment]
Hope it resolved this. Reopen if not.
