### ISSUE TITLE
Mysql - Pagination

### ISSUE THREAD

**Issue by indigitale** [volkanceylan/Serenity#986]
Hi,

first of all I thank you for the fantastic job .
I'm testing your application with one of my MySQL database and I have a problem with pagination .
The first and the second page are displayed correctly with the defined limits , but from the third onwards data is added at the end of the second page .
Thanks again!!

**Comment by volkanceylan** [comment]
Turn LoggingLevel to Debug in web config and see files under AppData/log for generated SQL. Check what is wrong with paging queries.

**Comment by volkanceylan** [comment]
Please reopen with details.

**Comment by freddiezhou** [comment]
I faced the same problem on Pagination when use mysql database. 

When I turn to 'Page 4' in my application, and traced the loging file, and sql as below:
_SELECT T0.`sId` AS `SId` FROM `odm_packing` T0 ORDER BY T0.`WORKORDER`, T0.`sId` **LIMIT 300 OFFSET 100**_

And it's error, and correct one should be **LIMIT 100 OFFSET 300**.

So could you please advise how to fix this? Thank you very much.
