### ISSUE TITLE
Get navigating items from another source (e.g. API etc.)

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#988]
After changing the following it works when I am in http://localhost:58223/
but after navigating to another page such as http://localhost:58223/someModule/somePage then 
the url of all the navigation links are changed to http://localhost:58223/someModule/someModule/somePage

I cannot figure it out. Can anyone help me.
```
public NavigationModel()
        {
            Items = TwoLevelCache.GetLocalStoreOnly("LeftNavigationModel:NavigationItems:" + (Authorization.UserId ?? "-1"), TimeSpan.Zero,
                Security.Entities.RoleMenuPermissionRow.Fields.GenerationKey, () =>
                    //NavigationHelper.GetNavigationItems(x =>
                    //    x != null && x.StartsWith("~/") ? VirtualPathUtility.ToAbsolute(x) : x)

                    new Security.Repositories.AppUserRepository().GetUserData().NavigationItems;
                    );

            SetActivePath();
        }
```

**Comment by volkanceylan** [comment]
Your URLs should be starting with ~/ and you should use VirtualPathUtility.ToAbsolute(x), see code block you commented

**Comment by dfaruque** [comment]
Works... :)
Thank you very much.
