### ISSUE TITLE
In Place add not working properly

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#989]
The INPLACE add button now working as a edit button like below manner
![image](https://cloud.githubusercontent.com/assets/18713252/17289567/e7b39114-57f7-11e6-810c-fbdc3f866768.png)
how set to perform inplace add process

**Comment by Estrusco** [comment]
Click on edit button and see console for error.

**Comment by volkanceylan** [comment]
Inplace add only works when editor is empty.
