### ISSUE TITLE
Microsoft Edge - Blank Login Page

### ISSUE THREAD

**Issue by monovisual** [volkanceylan/Serenity#99]
Hello, 

Please forgive me if the answer to this issue is staring me right in the face! My deployment of the Serenity template functions on all browsers with the exception of Microsoft Edge. For some reason the "LoginPanel" div is empty when using Edge, which isn't the case in all other browsers. 

Is this a known issue? 

Many thanks,

Clyde

**Comment by volkanceylan** [comment]
I did a quick test with Edge and couldn't see any problem. Do you see any errors in console? If it is a public site, can you share a link?

**Comment by monovisual** [comment]
It is a public site: https://preview.eos.london

**Comment by monovisual** [comment]
It is a public website: https://preview.eos.london

There are numerous errors reported in the console but I am unsure what they mean...

**Errors**

SCRIPT1048: The use of a keyword for an identifier is invalid
mscorlib.js (3761,39)
SCRIPT5009: 'ss' is undefined
linq.js (155,5)
SCRIPT5009: 'global' is undefined
Serenity.Script.Core.js (4,2)
SCRIPT5009: 'global' is undefined
Serenity.Script.UI.js (4,2)
SCRIPT5009: 'Serenity' is undefined
Serenity.Externals.js (605,9)
SCRIPT5009: 'global' is undefined
Eos.Script.js (4,2)
SCRIPT5009: 'Q$LT' is undefined
LocalText.Site.en-GB.Public.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
ColumnsBundle.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
FormBundle.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
TemplateBundle.js (1,1)
SCRIPT5009: 'Q$ScriptData' is undefined
RegisteredScripts.js (1,1)
SCRIPT5009: 'Eos' is undefined
Login (127,5)

**Comment by volkanceylan** [comment]
Ok, i checked your site, it works in my Edge browser, version 20.10240.16384.0

It seeems like your Edge browser or some settings is different. I guess problem is usage of "await" variable name in mscorlib.js from Saltarelle. This is a future keyword for ES6. I'm renaming this variable in Serenity copy of mscorlib.js. 

Try updating Nuget packages to 1.8.21.

**Comment by monovisual** [comment]
Ahh OK! Thank you very much for the clarification!
