### ISSUE TITLE
Audit Log its present or not in serenity

### ISSUE THREAD

**Issue by GOBIBE** [volkanceylan/Serenity#990]
Audit Log
This page provide a list of all actions that occur in the system.  This includes:
1.	Login in
2.	Submitting new failure modes
3.	Adding personal notes
4.	Adding and editing any other record (as per the forms in this document)
5.	Approving a failure mode
6.	Rejecting a new failure mode
7.	Changing of permissions/users/roles

**Comment by volkanceylan** [comment]
Last time i check there wasn't :)
