### ISSUE TITLE
Visual Studio 2012 won't build

### ISSUE THREAD

**Issue by dandrejvv** [volkanceylan/Serenity#992]
I've been battling to get this to work with Visual Studio 2012 (plugin says that it should work with 2012), and I still can't get it to compile and run.

The problem is that the typescript compiler fails to recognise the `namespace` keyword.
It seems to be a feature only found in Typescript after 1.0 (and it seems that 1.0 is the last available version supported for Visual Studio 2012, am I right?).

Is there a way to get this to work with Visual studio 2012 and Typescript 1.0?

**Comment by volkanceylan** [comment]
You need TypeScript 1.8.6. It doesn't look available for VS 2012. Either you need to setup VS 2015 Community, or disable TypeScript compilation from your csproj and invoke command line compiler.
