### ISSUE TITLE
Best Practice of SQL Joins and Relationships

### ISSUE THREAD

**Issue by biggikalli** [volkanceylan/Serenity#993]
Dear Volkan,

Excuse me for creating a new issue thread for this question but I think clarification/confirmation would be really benefical to many users
.
I understand Serenity as not depending on "already defined SQL relationships" liked created via SQL Database Diagram or simply a SQL query when you create a table. Is it true that Serenity itself is capable of handling and creating those kinds of relations in xxxRow.cs for example?

E.g. the dependencies defined directly in the Northwind database are irrelevant and not needed really for the Northwind demo in Serenity:

![image](https://cloud.githubusercontent.com/assets/15879719/17295304/0939144c-57eb-11e6-96a7-0459a2fec1e0.png)

I am just curious because I would love to be able to fully control everything within Serenity rather than waste time on battling joins at the Database level and trying to generate code from that.

Was wondering about this because I noticed the following in the Serenity Guide:
![image](https://cloud.githubusercontent.com/assets/15879719/17295547/23e5af02-57ec-11e6-9a48-8f823cc6c63b.png)

Are SQL views somewhat outdated in the eyes of Serenity?
What is really the preferred practice in your opinion (in just few words)?

**Comment by volkanceylan** [comment]
Hi Biggikali,

I mostly avoid views, as they one more layer in database that needs to be kept up to date and versioned. When their numbers become high, it is hard to find which view is for what. Also views are not updatable even for main table. 

Serenity entities can bring in fields from other tables with left joins and act like views. You may also do other types of joins using SqlQuery. Aggregates are also possible.

Views also has their uses, for reporting, custom aggregate views, easier querying from  sql, just like stored procs. But i try to avoid both unless there is a strong reason to as i prevfer my business logic in service layer instead of database layer for flexibility.

**Comment by biggikalli** [comment]
Hi Volkan and thanks for quick responses,

So my understanding is correct?
I do not **need** any joins/relations in database layer?

As a model for my current project, I spent bunch of time analyzing how the Order table of Northwind database functions and how it's relations/joins at the database layer affect the Order module in the Serenity code. **Do these dependencies (see picture in first comment) have any affect into Serenity or is the business logic done from scratch in Serenity?**

If so, I would be relieved as that simplifies my "view of the world" and the way I understand the examples :+1: 

Ps. I already have successfully developed and delivered an application built on Serenity earlier this year (Saltarelle). That system relied 90% on views and a dozen of SQL triggers to handle the insert/update/delete functions of the underlying tables. So anything is possible but like you mentioned, there is a strong reason to handle the logic in the service layer. "Keep it clean" :)

**Comment by volkanceylan** [comment]
Yes, you should only add FK's for integrity, and to help Sergen generate required joins for 1st level relations. Don't use views unless you have a real need.

Northwind has several views, as it is a demo database for SQL Server, which is primarily targeted at DBAs.

Serenity doesn't force you to use any working model. It just provides you some out-of-box solutions for common patterns. These are my recommendations but this doesn't mean you have to.

I prefer logic in service layer, as i'm a code oriented person. DBAs might like everything it in DB, as it makes it easier to manage for them, and work with multiple applications using same DB.

**Comment by biggikalli** [comment]
Thanks @volkanceylan for a good answer.

This makes total sense to me now and I agree with you that location of the logic depends largely on habit and sometimes circumstances, this is not black/white issue.

I am glad now because I am getting success with joins and relations directly in the code of my project thanks to your guidance, the serenity guide (e.g. **LeftJoin Attribute** chapter) and the Northwind Example (Order/Customer).

Thank you :+1:
