### ISSUE TITLE
Serenity.css vs site.css in dialogs

### ISSUE THREAD

**Issue by jdready5** [volkanceylan/Serenity#994]
I have a strange issue I haven't been able to figure out (It must've been something I did). I have multiple entities, in some, I can make changes to site.less with no problem but in a couple of my edit dialogs for some reason none of it is reading from site.css so my site.less changes have no effect. In reviewing console my fields and form is only reading from serenity.css instead. I have noticed in those that I have EditiorAttributes.cs files in my ClientTypes folder where as the forms that work do not. Could this be related? So my question is this should I / can I 
A.) create a serenity.less file and make my changes there without side effects to the rest of the platform (I don't think I should, I think I need to find out why the element is not reading from site.css.
B.) Where can I direct the dialog which css to read from.

**Comment by volkanceylan** [comment]
Check your UI dialog class with inspect element. It's s-ModuleName-DialogClassName. It's also case sensitive. You are applying CSS to wrong class.

**Comment by jdready5** [comment]
my UI Dialog class from inspect element is .s-NotaryManager-NotaryDialog and my site.less is .s-NotaryManager-NotaryDialog as well. Is there some place I may have inadvertently changed a name somewhere that may be giving me grief?

**Comment by jdready5** [comment]
Sorry about that, It was my mistake. I had a } in the wrong place causing me grief. I looked everywhere this morning to make sure that wasn't the issue but I still missed it.

**Comment by volkanceylan** [comment]
:) np it happens
