### ISSUE TITLE
Question: The ASP.NET Team tweeted: Announcing Scripty: An Roslyn-based alternative to T4 for compile-time code generation

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#997]
The ASP.NET Team tweeted: Announcing Scripty: An Roslyn-based alternative to T4 for compile-time code generation

http://daveaglick.com/posts/announcing-scripty?utm_source=twitterfeed&utm_medium=facebook

Can we use this as replacement of T4 Template generation?

**Comment by volkanceylan** [comment]
It looks interesting. I'll evaluate it, probably first for ASP.NET core, thanks.
