### ISSUE TITLE
SplitButton dropdowns in grid

### ISSUE THREAD

**Issue by Estrusco** [volkanceylan/Serenity#998]
If you're interested I have added this in the wiki

https://github.com/volkanceylan/Serenity/wiki/SplitButton-dropdowns

![resultbuttonpdf](https://cloud.githubusercontent.com/assets/16304015/17327132/47af1084-58b6-11e6-9fca-0a0f34d1bd33.PNG)

**Comment by volkanceylan** [comment]
Thanks @Estrusco, looks very useful, i'll see if i can use it somewhere, have some ideas
