### ISSUE TITLE
Validating values in a Detail table (from a Master-Detail table duo)

### ISSUE THREAD

**Issue by CAlva123** [volkanceylan/Serenity#999]
I have two tables in a Master-Detail relationship (Parameter and ParameterDetail), made by taking the Order-OrderDetails tables from Northwind as a reference. 

I'm trying to validate one of the fields in ParemeterDetail (name) to avoid duplicate values. I tried using UserRepository as a reference, but since my table is in a Master-Detail relationship, I can't find where to add the validation, so I'd like some help with this.

Thanks in advance.

**Comment by jsbUSMC** [comment]
You can check out the `GridFilteredByCriteria.ts` in the Basic Samples of the Serene template for a possible resolution. Also, check out FilteredLookupInDetailDialog section of the Basic Samples. I hope this helps.

**Comment by volkanceylan** [comment]
See OrderDetailsEditor.ts, validateEntity method.

**Comment by CAlva123** [comment]
Using validateEntity worked. Thanks to both of you.
